### ISSUE TITLE
bots shouldn't open doors and hatches when repairing them

### ISSUE THREAD

**Issue by AdamMil** [Regalis11/Barotrauma#10005]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When bots go to repair a door or hatch, they open it before beginning the repair. (Perhaps if it's already open, they close it; I'm not sure about that.) Normally this is not a problem, but it's a big problem when they repair docking hatches, for example. They will climb up to repair the hatch and then open it, flooding the ship. Moreover, the rush of water will knock them down, so they can't continue the repair until the ship floods all the way up to the top of the hatch. Meanwhile, chaos is ensuing.

There's really just no reason for bots to open (or close) doors or hatches before repairing them. It's not necessary and in some cases can be very harmful.

A problem that I suspect is related is that when repairing a hatch (or door?) that leads to water, they will go put on a diving suit first. Perhaps that is because they plan to open it. If they don't open it, they won't need a diving suit.

### Reproduction steps

1. Open the sub editor.
2. Place a floor.
3. Place a door with buttons, and/or a ladder and hatch with buttons.
4. Place appropriate waypoints.
5. Drag a hull around everything.
6. Go into test mode.
7. Order the engineer to repair broken objects.
8. Switch to the mechanic and use the plasma cutter to damage the door or hatch.
9. When the engineer comes running, step aside.
10. Watch as the engineer opens the door or hatch before repairing it.

If you need a screenshot of this setup, let me know.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d4a56fc5171fd0842490f66081b0201e49fe8487

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
