### ISSUE TITLE
Toolbelts/Storage containers placed in older subs can go inside toolbelts

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10003]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Toolbelts that were pre-placed in subs predating the Hoist update haven't been updated and can be placed inside toolbelts.

![image](https://user-images.githubusercontent.com/73229309/194434952-25cf42bc-5731-43b6-bbc9-e676a87f392f.png)
![image](https://user-images.githubusercontent.com/73229309/194439257-02cc926a-96d7-4d87-b6a3-b1319bc0608e.png)

Probably related to the change from the fact that Toolbets don't use `excludeditems` to exclude themselves, but are `mediumitem` and can only contain `smallitem` (so they can't contain themselves).

_I opened a ticket that led to this change but cannot find it did it disappear?_

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06576e65ee3594142be97df1e7baa2483a307fa5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
