### ISSUE TITLE
Quick save now throws an error.

### ISSUE THREAD

**Issue by bwinter** [Regalis11/Barotrauma#10007]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After the update, when I try to use quick save in the submarine editor I get an error.
![Screen Shot 2022-10-06 at 8 26 57 PM](https://user-images.githubusercontent.com/4021445/194461669-40406061-19a3-4a60-b554-de46718ee2dc.png)

### Reproduction steps

1. Open submarine editor
2. Create a submarine.
3. Attempt to quick save. (cmd+shift+s) (also tried and saw it in on windows pc.)

### Bug prevalence

Happens regularly

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/79e7f8fbf50e553e8d7414b968d94da1db1ac435

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/3f874d71a8cdc82d1d16314abdd6ae91f7e42098, no issues found, closing.
