### ISSUE TITLE
heavy lobby list shuffling/flickering

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10016]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the list of lobbies shuffles heavily as it loads in/updates

would be nice if it only shuffled once every second or something - or just waited until the list is fully loaded. as it's not really usable when the list is dancing all like that anyway.

it gets worse if i type in a filter and press "scan"

### Reproduction steps

1. open server browser
2. my eyes

https://user-images.githubusercontent.com/5103517/194650797-d0d7fc70-f0db-4d3f-822f-bede1b449f34.mp4

### Bug prevalence

Happens regularly

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, I didn't spot any issues with this, can be merged and closed.
