### ISSUE TITLE
Old campaign save impossible to continue

### ISSUE THREAD

**Issue by Artemiy988** [Regalis11/Barotrauma#10014]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

My old campaign save is impossible to continue because my submarine instantly crashes(I have maxed hull)
![20221006205418_1](https://user-images.githubusercontent.com/102730515/194594689-0796773c-39cd-454e-b3c6-2c587a5fadc6.jpg)
![20221006205436_1](https://user-images.githubusercontent.com/102730515/194594693-a8146d73-40fa-482c-9c7f-487357198055.jpg)
![20221006205411_1](https://user-images.githubusercontent.com/102730515/194594697-1b91a940-1918-4fb1-b335-bf15431df53d.jpg)

### Reproduction steps

1. Use old save of campaign (hydrotermal wastes biome)
2. Use submarine R-278 from steam workshop with maxed hull
3. Your sub will instantly crash on the start of lvl

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by VitalyArtemiev** [comment]
You can use [Barotrauma Save Decompressor](**https://github.com/Jlobblet/Barotrauma-Save-Decompressor/releases**) to extract your sub from the save and edit the hull to withstand higher pressures.

**Comment by Regalis11** [comment]
Thank you for the report! This should have been addressed in the v0.19.11.0 patch, but it seems the fix isn't working in this case for some reason. The patch made the game force the crush depth of the submarine to at least the depth of the current level (+500 m) in saves made prior to v0.19.10.0, which should mean you can still travel back to switch to a submarine with a higher crush depth. 

Would it be possible to send us the save file so we can give it a test? Note that you need to .zip it first, because github doesn't allow attaching files with the .save file extension. I'm sorry for the inconvenience!

**Comment by thesteveirwin** [comment]
> Thank you for the report! This should have been addressed in the v0.19.11.0 patch, but it seems the fix isn't working in this case for some reason. The patch made the game force the crush depth of the submarine to at least the depth of the current level (+500 m) in saves made prior to v0.19.10.0, which should mean you can still travel back to switch to a submarine with a higher crush depth.
> 
> Would it be possible to send us the save file so we can give it a test? Note that you need to .zip it first, because github doesn't allow attaching files with the .save file extension. I'm sorry for the inconvenience!

any idea how i send the save cause my saves folder is empty for some reason

**Comment by thesteveirwin** [comment]
mine is about the issue with the save not loading

**Comment by VitalyArtemiev** [comment]
If this is multiplayer, your saves should be in C:\Users\<YOUR_USERNAME>\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer

**Comment by Regalis11** [comment]
No known steps to repro, closing
