### ISSUE TITLE
FPS drop constant

### ISSUE THREAD

**Issue by AlanGuardsman** [Regalis11/Barotrauma#10017]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After the update the game runs 40-60 fps for 2-3 minutes and then drops and constantly holds at 6-8 fps no matter the mods, computer temperature or stuff, not even mentioning this stuff not happening in the previous update.

### Reproduction steps

1. Launch the game
2. Join server.
3. Wait a few minutes
4. Observe PowerPoint even worse than it was before Hoist the Sails

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

We unfortunately haven't run into these kinds of performance issues while testing the game at our end, so I suspect it requires some specific circumstances to occur. It might help us diagnose this if you could open the debug console (F3), enter the command "showperf" which shows some performance statistics on the screen, and sent us a screenshot of what those statistics show when the FPS drops like this. Your PC specs might also give us some more clues on this.

Thanks and sorry for the inconvenience! :/

**Comment by AlanGuardsman** [comment]
> Thank you for the report!
> 
> We unfortunately haven't run into these kinds of performance issues while testing the game at our end, so I suspect it requires some specific circumstances to occur. It might help us diagnose this if you could open the debug console (F3), enter the command "showperf" which shows some performance statistics on the screen, and sent us a screenshot of what those statistics show when the FPS drops like this. Your PC specs might also give us some more clues on this.
> 
> Thanks and sorry for the inconvenience! :/

Windows 10 x64, Acer Aspire A315-55G, Intel Core i5, 8GB RAM.

I will get performance later tonight

**Comment by JoneKone** [comment]
I would first check if your PC is overheating.

**Comment by AlanGuardsman** [comment]
> I would first check if your PC is overheating.

as stated above in the issue - heating do not affect it in any significant way + these lags did not appear smoothly as if my thermopaste was going off the processor, it appeared right after the update was applied

**Comment by AlanGuardsman** [comment]
> Thank you for the report!
> 
> We unfortunately haven't run into these kinds of performance issues while testing the game at our end, so I suspect it requires some specific circumstances to occur. It might help us diagnose this if you could open the debug console (F3), enter the command "showperf" which shows some performance statistics on the screen, and sent us a screenshot of what those statistics show when the FPS drops like this. Your PC specs might also give us some more clues on this.
> 
> Thanks and sorry for the inconvenience! :/

![image](https://user-images.githubusercontent.com/95501699/194954744-8d5c1a8d-5c91-4643-8856-1c1289b75b1b.png)

**Comment by Regalis11** [comment]
Hmm, that's very strange. There doesn't seem to be anything there taking an excessive amount of  time to execute, which might imply whatever is causing the slowdown is happening outside the game logic. This could be related to some of the problems discussed in https://github.com/Regalis11/Barotrauma/issues/9396. Since it's very difficult to determine if this is a different issue than the earlier one, I think I'll close this as a duplicate and repurpose the previous one as a general ticket about these mystery performance drops.
