### ISSUE TITLE
submarine list in lobby excessively large

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10015]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

submarine listings takes up way more space than before - due to showing price

this is detrimental outside of campaign mode, as it means more scrolling is needed, shows fewer ships at a time, and makes the sub class worse to read

### Reproduction steps

![image](https://user-images.githubusercontent.com/5103517/194644947-c61e3d60-74a1-4349-9fd5-0124fd3ce4ca.png)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment]
Honestly even with the price there, I feel like the margins between the lines could come down like 75%.
There is more empty space there than there is words!

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/90085a4c7dfcedb053ec8b5cf257b6a0c9a60505

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
