### ISSUE TITLE
Additional Cargo menu (multiplayer spawn option)

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10019]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

- missing items (for example thermal goggles, i think)
- item order seems random
- no search function, relies on randomly scrolling and praying

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment]
> * item order seems random
> * no search function, relies on randomly scrolling and praying

I feel like this technically count's as a F.R. & should get merged?

Also I'm genuinely curious about that second one, how the *heck* does the game determine item order, because it seems completely unrelated to item-id, item-name, or load-order.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/232939360a43dfcf4037e125580991fc1fdfb119 and https://github.com/Regalis11/Barotrauma-development/commit/25eecc602d7ca5ae8d4bf839ae278db002c29df4

> how the heck does the game determine item order, because it seems completely unrelated to item-id, item-name, or load-order.

The prefabs are stored in a dictionary which has no defined order: i.e. it's basically random.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
