### ISSUE TITLE
Cannot place storage containers in medicine cabinets

### ISSUE THREAD

**Issue by nomnivore1** [Regalis11/Barotrauma#10028]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Storage Containers (one handed briefcase like item storage device) can no longer be placed in the medicine cabinet. They can however still be placed in steel cabinets just fine. This presents issues to previous inventory storage and management strategies for the Medic role. (I Cannot Fit All Of My Materials In This Cabinet) 

### Reproduction steps

1. open a submarine in the editor, or in singleplayer. no mods were used and no modifications were made to the properties of the relevant items
2. attempt to place a storage container in a medicine cabinet
3. cry, because it does not fit and you have nowhere to put your strategic plastiseal reserve of 80 bandages. 

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3f874d71a8cdc82d1d16314abdd6ae91f7e42098

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/3f874d71a8cdc82d1d16314abdd6ae91f7e42098, no issues found, closing.

**Comment by TheRealBlitze** [comment]
Seems to be back on the menu on the latest Version v1.0.9.0:
Cant place half of my storage Containers in that Medic Container 
[https://i.imgur.com/lnIfXpv.jpeg](url)
