### ISSUE TITLE
Unnecessary Railgun shell racks on Vanilla Submarines

### ISSUE THREAD

**Issue by MarkCringan** [Regalis11/Barotrauma#10029]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Dugong, Orca, Orca 2, and other subs that are unable to equip railguns still have the shell rack.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TheMinerBoy** [comment]
The Orca 2 can equip a railgun though. You can replace the double coilgun with a railgun.

**Comment by MarkCringan** [comment]
> The Orca 2 can equip a railgun though. You can replace the double coilgun with a railgun.

Oops lol, but I know it's definitely true for the dugong.

**Comment by Regalis11** [comment]
I would actually argue there is some use for these racks even if the sub doesn't have a railgun: if you switch from a sub with a railgun to one of these, it's good to have at least that one rack for storing the shells for future use.

**Comment by Ek-Videogames** [comment]
Huh - I was sort of hoping this meant there would be a reason to have these railgun racks still.
( Like some other use for railgun shells, or a small submarine weapon that stores ammo in racks the same way )
