### ISSUE TITLE
Submarine tier resets to default between save dialogs

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#10022]
- Build Unstable 0.19.11.0 Windows
- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Description
The issue of tiers not saving to begin with was fixed with #9821 , however the save GUI's tier value is replaced with the auto-generated tier every time it opens rather than being persistent.
Maybe this behavior should only occur when saving a submarine from an older version, as it can be tedious/confusing to reset the sub tier every time.

### Reproduction steps
- Set a sub with a price that would normally be tier-1.
- Save the submarine with a tier-2 or tier-3 setting.
- Open the save dialog again. It has not reverted to tier-1 in the GUI.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c70f94a2f5a8537c0e48844c75c17fce91d164e4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
