### ISSUE TITLE
Bot can't fix docking hatch on top of Typhon 2

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#10023]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The docking hatch on top of the Typhon 2 cannot be reached by the AI crew (unless the submarine is already full of water, which they can reach by swimming), nor can the small wall on either side of the docking hatch be fix.

### Reproduction steps

1.Order a Bot to repair the machinery.
2.The upper docking hatch was damaged.
3.The bot will repeatedly move up and down the ladder under the docking hatch, unable to reach the docking hatch, and will stay stuck there, causing other damaged items to not be repaired until the player repairs the docking hatch.

Additional Info: This problem still occurs even though the docking hatch's health has only dropped a little. So this is not a problem caused by the impact of the water current.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AnalogKnight** [comment]
@Regalis11 Problem still exists, please check.

**Comment by ekqvist** [comment]
Fixed by creating more waypoints near the hatch to allow them to navigate closer to the hatch properly (Regalis11/Barotrauma-development@7a6f529)

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8, no issues found, closing.
