### ISSUE TITLE
Camel invis hull 

### ISSUE THREAD

**Issue by John50387** [Regalis11/Barotrauma#10024]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

From what I've noticed, the lower part of the hull , once it's fully broken by whatever, once you fix it, it becomes see through until you dock at a station or travel to a new location

### Reproduction steps

Get creatures underneath camel, have them destroy a large part of the outer hull, once it's fixed it acts like glass and you can see through it.

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately couldn't find a way to get this to happen at my end. 

The wall seems to become non-transparent as soon as the wall is repaired:
![image](https://user-images.githubusercontent.com/14351070/194764264-4a9a24d4-18c4-4068-b641-50011ad660a0.png)

I also gave a try at damaging the wall below the crew quarters, but couldn't get the issue to occur there either.
