### ISSUE TITLE
Monsters sometimes spawn in indestructible rocks

### ISSUE THREAD

**Issue by fw-cc** [Regalis11/Barotrauma#10026]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Took two "Kill Hammerhead" missions, the first spawned fine, but this one appeared off the map, clipped deep into the rocks.

### Reproduction steps

The primary thing of note was taking two "Kill Hammerhead" missions at the same time, nothing else was untoward.

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/ac42dd2c-e773-4154-b648-8d84caac8736)

**Comment by itchyOwl** [comment]
An older ticket about the same issue here: #8244

**Comment by Regalis11** [comment]
@itchyOwl fixed that cave issue in https://github.com/Regalis11/Barotrauma-development/commit/2300c085e9d2f3dd58e57f27c879cda3132cf51b, although that seems to be a different issue: this one is about indestructible rocks

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/40f2828310ed4b63fdba9ad3b581c710fac0a042. I was able to repro monsters spawning inside islands (the extra wall chunks piezo crystals spawn on in the Great Sea), and addressed that in the commit, but I'm not 100% if this is the same issue.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
