### ISSUE TITLE
serversettings.xml Not Downloading (Barotrauma 0.8.2.3)

### ISSUE THREAD

**Issue by Maggot1970** [Regalis11/Barotrauma#1002]
So, to put it most simply, serversettings.xml is missing from the root directory of Barotrauma. I don't know how, or why this is happening, all I know is that it worked previously with no issues. 

All I did was download the game from the main website where Barotrauma's download was, only to find I got connection errors while in-game, so I went and checked in BarotraumaServer.exe and found serversettings.xml was missing. I tried redownloading everything 4-5 times to no avail. It never seemed to download amongst the other files.

I am running a Windows 10 (64 bit) PC with the newest version of Barotrauma installed. I originally had installed mods but then tried redownloading without any mods to see if it'd work without them. Of-course, it didn't seem to work.

Some help with this would be amazing, as I haven't been able to play online at all. Every other folder/ file is alright except this one folder, for a better understanding, if that helps.

**Comment by Regalis11** [comment]
I think your connection errors are probably not caused by the missing serversettings file. It's only needed when you're hosting servers, and if it is missing, the server automatically creates it.

1. Just to clarify, are you trying to host a server or play on other servers?
2. What kind of connection errors are you getting? Can you connect to servers or do the errors happen when a round is running? Is there some sort of an error message?

Sorry for the trouble, I hope we can figure out what's causing this. :/

**Comment by Maggot1970** [comment]
> I think your connection errors are probably not caused by the missing serversettings file. It's only needed when you're hosting servers, and if it is missing, the server automatically creates it.
> 
> 1. Just to clarify, are you trying to host a server or play on other servers?
> 2. What kind of connection errors are you getting? Can you connect to servers or do the errors happen when a round is running? Is there some sort of an error message?
> 
> Sorry for the trouble, I hope we can figure out what's causing this. :/

Thanks for the response, and sorry for the 7 hour interval. I've been rather busy. 

To clarify, I am only trying to join servers, sorry for not making that clear. I can't host or join servers (when I pull up the server menu, it comes up with a connection error) and the error message that comes with the connection error states  "Error while connecting to master server (404 - http://www.undertowgames.com/baromaster not found)" 

My friend also plays this game and he's also in my same region. He says the servers work for him, making it only an issue with my game. Thanks for responding, yet again. Your help would be greatly appreciated.

**Comment by Regalis11** [comment]
Ah I see! My guess would be that your firewall/antivirus is blocking the game from connecting to the internet.

**Comment by Maggot1970** [comment]
Hey, back again. It turns out that's not the issue. I've tried running it as admin, disabling my firewall, checking to see if Barotrauma.exe isn't blocked, etc. I don't know what could possibly be wrong with the game, as this doesn't happen with any other. I've even checked my antivirus to no avail.

**Comment by Regalis11** [comment]
I'm sorry but in that case I'm not quite sure what could be causing this. One thing you could try is opening config.xml in the game's root folder, and change the masterserverurl value to "https://www.undertowgames.com/baromaster".

You can also play the game without a connection to the master server, although finding servers will be a bit more difficult. The master server is only used to find available servers and make your server visible to others, but you can also join servers by entering the IP address directly in the "Server IP" textbox in the "join server" menu. You can get a list of the public servers by going to http://www.undertowgames.com/baromaster/masterserver2.php?action=listservers with your web browser.

Again, sorry for the inconvenience. I hope the upcoming Steam release will make issues like this less likely... :/

**Comment by Maggot1970** [comment]
Does the fact it says "forbidden" as an error in the BarotraumaServer.exe help anything? I'm just curious. 
It goes as the following : 

Selected sub: Aegir Mark III
Selected shuttle: The Blind Carp
Starting the server...
Server started
Error while connecting to master server (Forbidden: Forbidden)

If the issue isn't fixable, I won't mind. Like you said, I can just join via IP. Thanks for your help.
