### ISSUE TITLE
Oxygen tanks in the diving masks of outpost NPCs don't count as stolen items

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#10025]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I found the randomly-generated overdosed NPC and searched them after diagnosing them incorrectly and found that the oxygen tank in their diving mask wasn't marked as not belonging to me.

### Reproduction steps

1. Find any outpost NPC that you can search
2. Steal their oxygen tank with no consequences even if the guards are right beside you

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d2c0010a974af79431440f6ea06a73a1dc319e7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
