### ISSUE TITLE
Sub Save Duplicating №2

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10027]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Saving a sub in the sub editor will cause the sub file to duplicate in the load/save list.

### Reproduction steps

https://user-images.githubusercontent.com/93348499/194721304-198e9ddf-eca0-4c4c-8cab-62e4ff624263.mp4

What I think about it:
![Image 001_15-24](https://user-images.githubusercontent.com/93348499/194721312-37108a91-ba63-4f3b-b00e-066204d92b2b.png)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a4a386fa5a07c3026469d327e0be4999f3143b6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
