### ISSUE TITLE
Failed quest with unconscious opiate overdosed station citizen if given naloxone before the quest prompts

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#10032]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I gave an unconscious with opiate addiction station personnel my only nalexone, which cured them, but they stayed stunned and only after doing the quest prompts was I asked for nalexone, but didn't have any.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by thegrb93** [comment]
I think maybe if I had more nalexone, it would've succeeded, but since I used it on them before the prompt, it couldn't be completed.

**Comment by TheMinerBoy** [comment]
Honestly the heal menu shouldn't show up at all for the NPC (At least until you complete the quest, failing the quest should still leave the heal menu inaccessible) After all, the point is that you don't know what's wrong with them unless you have high medical skill.

**Comment by itchyOwl** [comment]
Sounds bugged, but not sure how it's intended to work.

**Comment by TheMinerBoy** [comment]
> Sounds bugged, but not sure how it's intended to work.

It's supposed to be a medical skill test, just like the "Fix the engine" event with the mechanic tests mechanical skill, or the "Find a route" event with the captain tests helm skill. Unfortunately, if you are able to use the heal menu, it basically breaks this event.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8236854e6b3d021bc70526a848c44cd49c2be92c

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4488/commits/2b575c97307f8d5c9de8d14e5e9b1142e4f17ed5

Couldn't open health UI anymore.
Technically you could still use naloxone manually, if you get them in the right position, but this is not indicated so i don't see it as a problem.

No other issues found
Closing ticket
