### ISSUE TITLE
Huge amount of enemy spawns + pirates in vanilla campaign

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10038]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

About 20+ enemies spawned at the same time as pirate, including several threshers, crawlers and one watcher. They all proceeded to murder every single pirate within less than a minute

Trying to get the host to send me server logs desperately

![image](https://user-images.githubusercontent.com/73229309/194781745-84b17278-92fe-486e-aaad-9dd9a5970aae.png)
![image](https://user-images.githubusercontent.com/73229309/194781748-fd94c92b-a42f-4925-a68f-efe5f4371f4f.png)

### Version

0.19.11.0

**Comment by TheMinerBoy** [comment]
This happened to me as well with crawlers, mudraptors, and spinelings at the same time, but I don't think it's a bug? More like an extremely rare event that you have to deal with.

**Comment by Regalis11** [comment]
I'm afraid there's not enough information here for us to diagnose the issue. It seems like this could've just been a very unlucky random occurrence, with multiple monster spawns happening close enough to each other that they all managed to spot the pirate sub at the same time.
