### ISSUE TITLE
Engineer can pick All Seeing Eye from first level up.

### ISSUE THREAD

**Issue by 8on8er** [Regalis11/Barotrauma#10034]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Engineers can access All Seeing Eye from first level up and gain all talents in the talent tree.

### Reproduction steps

1. Start any campaign/mission etc...
2. Get an engineer.
3. Level up the engineer.
4. Select All Seeing Eye.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately wasn't able to reproduce the issue: the talent does not seem to be selectable until I've unlocked the previous ones:

![image](https://user-images.githubusercontent.com/14351070/194810772-193334bd-0048-4f34-afb1-a2bd11a7f36c.png)

Did this happen in single player or multiplayer? Are you using any mods?

**Comment by Regalis11** [comment]
Actually, it seems that this has already been reported https://github.com/regalis11/barotrauma/issues/9335

**Comment by 8on8er** [comment]
It was on single player, vanilla no mods.
