### ISSUE TITLE
Abandoned Outpost Doctor joins with nametag "Human"

### ISSUE THREAD

**Issue by c33tz** [Regalis11/Barotrauma#10037]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Cleared an abandoned outpost and met a doctor that we spared and offered to join. To my suprise his name was "Human"... only that. Nametag is present, but for the name "Human"

I assume that was not intended! (or was it?)

### Reproduction steps

1. Start Campaign
2. Visit & clear Abandoned Outpost with event
3. Follow event to take new crewmember (doctor)
4. witness their name!

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I could not find a way to reproduce this issue. Tested in both the single player and multiplayer campaign, and in both the character's name seems to be working correctly:
![image](https://user-images.githubusercontent.com/14351070/194810078-a1e32b9c-f2b9-4f03-8131-1b28c915b1e8.png)

Did this happen in multiplayer or single player? Are you playing in a language other than English?

**Comment by c33tz** [comment]
Thanks for digging into it, sorry it's causing grief to reproduce!

This was in Single Player, playing in English, no mods.

Some other notes/oddities that "may" help, I've done the Captain Hognose twice (only awarded him to join once which was good), and had accepted a 3rd time at some point.

Also The nametag does say "human" on it, but on the loading/summary screen the name appears blank (but while walking around, still presents as "Human" the doctor)

Not sure that will help at all, if there is anything else I can provide, let me know... hopefully it was just a freak occurance with a very specific set of conditions i lucked out on.
