### ISSUE TITLE
Research outpost uses abandoned outpost module

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#10042]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Noticed that sometimes a outpost can have a abandoned outpost module

### Reproduction steps

1. Load leveleditor
2. Select outpostlevel and researchoutpost
3. Use seed oBIwG05W

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ba972e23a7fe09027f215ce4699ee6c78d1f71fd

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
