### ISSUE TITLE
Drunken Sailor Talent gives damage resist forever

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10045]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Drunken Sailor talent gives damage resistance when the character `AbilityConditionHasAffliction afflictionidentifier="drunk"`.

The problem is that since the drunk affliction does not passively decay below 20 strength, and so unless a medicine like stabilozine is taken, the character will remain with ~19 drunk forever, and thus the character will continue to have the damage resistance, even if it has been a very long time since they last drank ethanol.

I'm aware that the talents are being reworked, so this bug might not even exist in the next update, but here it is anyway.

### Reproduction steps

1. give a character the drunken sailor talent
2. give the same character the drunkenness affliction (any amount)
3. wait any amount of time (I've tested up to 20 minutes)
4. attack the character, and observe that the damage resistance is still there

### Bug prevalence

Happens regularly

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
