### ISSUE TITLE
Alien ruins crawlspaces very hard to swim through due to character entering crouch mode

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#10048]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It's very easy to get stuck in the tight horizonal shafts because despite swimming with a water scooter, the character will enter crouch mode and get stuck. You have to hold down and shimmy yourself with ragdoll mode to get through.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Alien_maintenancepassages does this a lot

![image](https://user-images.githubusercontent.com/73229309/194914688-9cd69cb3-11bf-4d2d-91eb-5a35a67ade26.png)

You can hold crouch to not crouch, ironically

**Comment by itchyOwl** [comment]
The passages are intentionally claustrophobic, but you souldn't get stuck in them.

**Comment by Wheatley1002** [comment]
Can confirm this issue still exists within 100.15.0.0 and previous builds. Navigating the tighter passageways of the ruins is difficult due to the character model getting caught on the walls. The only way to swiftly navigate them is by holding "S".

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61d271845dae2c82692f6032f700942239d2d29a

**Comment by itchyOwl** [comment]
Tested, works correctly.
