### ISSUE TITLE
Captain's tutorial UI bug

### ISSUE THREAD

**Issue by Arifisar** [Regalis11/Barotrauma#10049]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

船长教程中，“寻找导师”消息框会出现没有正确移除并覆盖对话选项的情况，导致无法进行下一步操作而卡死
In the Captain's tutorial, the "Find a Mentor" message box has not been removed, it will override the dialog options, resulting in the failure of next any operations and stucking in this place.

### Reproduction steps

![image](https://user-images.githubusercontent.com/66297144/194915501-ee3e9c8c-ba38-4c9f-a01a-f5302c6bd243.png)

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Unfortunately no-one in the team speaks Chinese, but if Google Translate is accurate, I think we have addressed this issue for the next patch.
