### ISSUE TITLE
Diving Suit isnt preventing the high pressure effect

### ISSUE THREAD

**Issue by GrandAdmiralCommieCat** [Regalis11/Barotrauma#10041]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My character in a diving suit is still affected by high pressure. I am above 4000 meters 

### Reproduction steps

I was repairing beacons both times this happened if that helps

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

MacOS

for the record i was at 1500 meters

<img width="1273" alt="Screen Shot 2022-10-09 at 11 41 00 PM" src="https://user-images.githubusercontent.com/115429433/194796877-c7c9390b-91fa-403b-a59d-3ac6b0aafd59.png">

**Comment by Regalis11** [comment]
This is intentional: the icon is always displayed in high-pressure environments regardless if you're wearing a suit or not.
