### ISSUE TITLE
卡模型啦

### ISSUE THREAD

**Issue by 3072734660** [Regalis11/Barotrauma#10043]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/93265782/194837865-53a1b4f7-10e9-4a5f-80de-9fa65e24f40e.png">

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Insufficient information to address the issue
