### ISSUE TITLE
Deconstructor wrong output recipe preview

### ISSUE THREAD

**Issue by x13x54** [Regalis11/Barotrauma#10054]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I put a regular Fuel Rod in the Deconstructor.
The output preview indicates it will deconstruct into 1x steel bar and 1x uranium.
I only got 1x steel bar.

I like that there's an output preview now, but it's important that it displays the actual output and not just what the recipe to fabricate it is.
Players tend to just put metal crates in the output slots so there's a decent chance that an incorrect output recipe preview isn't noticed until many items have been wasted

This doesn't seem to be exclusive to fuel rods per @Instant2116 's comment below

### Reproduction steps

1. Put fuel rod in deconstructor.
2. Look at output preview, memorize the materials.
3. Deconstruct the fuel rod.
4. Compare actual output to what the machine told you it would be

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Instant2116** [comment]
Same trouble for empty stun grenades

**Comment by Regalis11** [comment]
Thank you for the report! It seems the issue was that the output didn't take the condition of the item into account, always showing the output as if the item was in full condition. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/30b440ad8d07e443ca96003d945f6d623cb9caa6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
