### ISSUE TITLE
Reactor changes from recent update breaks (the best) reactor controller

### ISSUE THREAD

**Issue by x13x54** [Regalis11/Barotrauma#10055]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Reactor controllers that rely on instant reactor response to input either 100 or 0 signals have been broken by the Hoist The Sales update.
I've had 4 reactor fires in one play session before i figured out what's wrong, one killing all paying passengers on my submarine (do they not run away from or report fire??).

Increasing the benefits of manual reactor control is a good thing, but making reactor controllers favored by casual players unusable without any kind of in-game notice or warning is ultimately going to upset people as it's legitimately not their fault their submarine burned to a crisp because it's a _known-good_ system that caused the fire.

### Reproduction steps

1. Place a regex find component with pattern `^[1-4]?.?.?.$` and configure output `100` for true and `0` for false.
2. Connect reactor temp output to regex component input and regex component output to reactor fission rate input.
3. Place 4 fuel rods in your reactor (the controller ~~can~~ could handle any number of rods but more might be more likely to reproduce issue).
4. Grab a fire extinguisher and observe reactor from a safe distance

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This was intentional to an extent: we feel these kinds of simple on/off ARCs were a way too easy way to automatize the operation of the reactor, and that they essentially allowed using a single, cheap component to essentially remove the entire power management mechanic from the game. 

So I'm afraid people tinkering with the reactors will need to put some more effort into designing the ARCs to get them to perform well, especially if using such an excessive amount of fuel.

**Comment by x13x54** [comment]
i agree with cracking down on these cheesy reactor controllers, but not if that results in a fire or possibly meltdown (haven't tested max rods yet).
I would prefer a mechanic where really rapidly changing reactor controls between both extremes causes the reactor to break down, fuel efficiency to plummet, or even some kind of xenon poisoning effect.
The catastrophic nature of the failure of cheesy ARCs over a contained failure is what i'm most upset about, especially if there's nothing actively telling me in-game that my reactor is now wired to catch fire.
At the minimum something should notify each user after the update similar to how the tutorial hints do it, but in red text, so that users aren't oblivious to the fact the update turned their stable reactor into a space heater

**Comment by VaelophisNyx** [comment]
years later and this nerf still feels excessively limiting to player ingenuity in the face of a painfully boring reactor control "minigame"
