### ISSUE TITLE
Problems with the respawn shuttle

### ISSUE THREAD

**Issue by DarthTauntaun** [Regalis11/Barotrauma#1005]
Hello! I have never used GitHub before now, so forgive me if I do something wrong here. I have looked through the forums regarding this issue, and didn't seem to find anything like this. For many, MANY games now, I have experienced difficulties concerning the respawn shuttle. Some of them aren't awful, like how the destination terminal will sometimes lock on to autopilot, but there is a very specific one I would like to address. When I play in a submarine that is too close to the top of the map, the respawn shuttle spawns outside of the map's boundaries. This is incredibly annoying, as the entire screen goes black, and you have to fumble around in darkness to find your gear. However, the bigger concern is when you get off the shuttle. Keep in mind that, when the shuttle is outside of where it should be, the destination terminal doesn't work until the player has left. When you get off of the shuttle, you are stuck between a pitch black abyss, and the rock wall on the top of the map. This can lead to me dying multiple times, due to the fact that I can't clip through solid objects (but sometimes it does glitch me through), and respawning in the same scenario. This has led me to leave many games, and renders some of the moving stations unplayable.

![respawnshuttleissue](https://user-images.githubusercontent.com/47067452/51793093-a50af500-2180-11e9-93d1-c2f64a4f334d.jpg)

Edit: I'm not gonna lie, this is the best thing I've ever created in MS Paint

**Comment by Regalis11** [comment]
Should be fixed for the next patch, as the shuttles now spawn inside the level instead of above it.

**Comment by Rokvach** [comment]
Tested, working correctly now. Closing.
