### ISSUE TITLE
LocalMods Broken

### ISSUE THREAD

**Issue by Galaxies12** [Regalis11/Barotrauma#10052]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

For some reason, I chose to delete all of my mods from F:\steam\steamapps\workshop\content\602960, and then unsubscribe from them.

This may have been before, or after the most recent update.

Whenever I download a new mod, it doesn't appear in F:\steam\steamapps\workshop\content\602960. And whenever I make a new save of any sort, it doesn't appear in my LocalMods.

I have no clue how I did this, and no idea how to fix it. I've validated files and re-installed my game.

### Reproduction steps

1. I deleted all of my mods, manually, from F:\steam\steamapps\workshop\content\602960
2. I unsubscribed from all of my workshop mods

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I could not find a way to reproduce this. :/ The mods seem to appear in `steam\steamapps\workshop\content\602960` after I subscribe to them. Local mods also appear in the game folder as expected. What's bizarre is that Barotrauma doesn't touch the workshop folder in steamapps - that's handled entirely by Steam. I wonder if it's possible there's something wrong with your Steam installation? Do the mods still work despite not appearing in that folder?

**Comment by Galaxies12** [comment]
Yes, the mods work, it's just that I have no new mods in steam\steamapps\workshop\content\602960, and whenever I save a ship or item preset, it just doesn't appear.

**Comment by Galaxies12** [comment]
Evil Factory just showed me where my Workshop mods are, "%LocalAppData%/Local/Daedalic Entertainment GmbH/WorkshopMods", but my LocalMods are still screwy.

**Comment by Regalis11** [comment]
That seems quite bizarre, the mods must be saving somewhere if they work. Where are you looking for the files - the LocalMods folder in the game's root folder? Have you tried clicking the "open in explorer" button next to the mod's name in the mod list?

**Comment by Galaxies12** [comment]
What... I never knew that was a thing... for some reason, I have 2 different LocalMods folders, the old one, and the new one. I will never understand coding.

The new LocalMods folder is now under my E: drive, where my old one was under my F: drive.

Thank you so much!
