### ISSUE TITLE
using an item that requires aiming makes the character stand up  once they let go of aim

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10061]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

using a weapon while on a chair/bed maeks the character stand up after they stop aiming

### Reproduction steps

1. lie down in bed
2. hold pistol, aim, shoot clown
3. let go of aim
4. player stands up :(

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Even though this isn't an exact duplicate, it's technically the same issue as https://github.com/Regalis11/Barotrauma/issues/9790 so I'll close this one as a duplicate.
