### ISSUE TITLE
MacOS compatibility branch not compatible with latest version

### ISSUE THREAD

**Issue by xxxcollapse** [Regalis11/Barotrauma#10068]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seeing as i am a player using a mac OS lower than 1.14/1.15, i am not able to play in any multiplayer servers because i have had to downgrade to a compatible macOS version BETA. If it is possible i would highly  request that you guys update the game version from the compatible macOS version 0.18.15.2 to the latest as i would really love to join my friends in this fun game.

### Reproduction steps

1. downgrade to the BETA called mac-os compatibility- last build that supported macOS systems older than 1.15
2. open the game
3. go to server browser
4. try to join one

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.15.2

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
SteamP2P connection failed to establish.
SteamP2P error
```

**Comment by Regalis11** [comment]
Thank you for the report!

I'm sorry to say this, but we cannot update the compatibility branch to the latest version. As explained [in one of our earlier Steam posts](https://store.steampowered.com/news/app/602960/view/3367025204056277713), we updated the .NET runtime to a newer version which isn't supported on macOS versions lower than 10.15.
