### ISSUE TITLE
Deconstructor drops output on the floor if the linked container is interacted with at the same time

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10069]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you manage the storage locker that's linked to a deconstructor while it is active, the output items of the deconstructor tends to fall out onto the floor if you move something in the linked container at the same time as it outputs.

### Reproduction steps

A decent amount of workshop subs tend to have their deconstructor linked with a locker or storage. For testing purposes, I used the Gato Revamped https://steamcommunity.com/sharedfiles/filedetails/?id=2798217062&searchtext= , but can also just edit some vanilla sub to have a locker linked with a decon as well.
1. Host a server into sandbox or w/e, this effect doesn't seem to work as well in single player/ sub editor
2. Start deconstruction on anything that can output
3. Move stuff around in the linked storage locker, can be putting stuff in, taking out, or shifting item positions within storage, anything really. You can do it actively while something is being deconed, or just time item movement with the decon finishing item processing to cause it as well.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe.
