### ISSUE TITLE
New subs have high overload voltage limits

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10060]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

new subs - herja, orca2, winterhalter, barsuk, camel - have 2.0 / default overload voltage limits for their junction boxes

all other vanilla subs have 1.7

leaving them on default seems more like an oversight than intentional setting.

overvolt junction box

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem like this causes any issues in practice, closing

**Comment by Tsunder** [comment]
Don't closed tickets not get read?

all of the new ones are 2 - the default on JB

the old ones are 1.7 - which allows for power balances to have overload damage to occur without requiring the reverse ratios to result in ship browning out (from <0.5 voltage), and is generally more likely for JBs to take damage. 

2.0, the 0.3 extra, means a lot less OL damage will be taken - doubly so with changes to other electrical - reactors are higher maxes, resulting in quicker turnarounds and supercaps add more more load, resulting in higher voltage needed to deal OL damage.
