### ISSUE TITLE
Resources from stolen items are marked stolen when deconstructed on an another outpost.

### ISSUE THREAD

**Issue by Laihela** [Regalis11/Barotrauma#10064]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I robbed some items from an outpost. The red hand indicating them as stolen items disappears when I leave. It comes back when I enter the same outpost I stole them from, but not when I enter a different one. If I deconstruct the stolen item in the other outpost, the output resources are marked as stolen, even though the item is not.
![image](https://user-images.githubusercontent.com/31377771/195255180-edae1be4-df2d-421c-800f-8c2790ccf256.png)
![image](https://user-images.githubusercontent.com/31377771/195255202-147aa69f-6a7e-474e-bba8-b1fc58c9d5ed.png)
![image](https://user-images.githubusercontent.com/31377771/195255328-3b4aeda3-3baf-4c2a-b96f-08eeb9bab062.png)

### Reproduction steps

1. Start a single-player campaign.
2. Steal a deconstructable item from the starting outpost.
3. Travel to an outpost which is not the same one where you stole the item from.
4. Observe that the item is no longer marked stolen.
5. Deconstruct the item in the station's deconstructor.
6. Observe that the output item(s) are marked stolen.

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Lithosagym** [comment]
Tested, stolen items that are deconstructed in another outpost are no longer considered stolen in that outpost. The deconstructed materials are also still considered stolen when returning to the initial outpost. Fixed.
