### ISSUE TITLE
camel diving area gapping

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10062]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

bit of water gets stuck up here due to the gap not reaching the bottom

![image](https://user-images.githubusercontent.com/5103517/195238826-27b539d5-0789-4b39-a2ba-805069f4a858.png)

![image](https://user-images.githubusercontent.com/5103517/195238904-86470f60-5428-45b7-bb55-bedfff87c8ed.png)

### Reproduction steps

player
1. destroy the room/flood
2. no power to pumps
3. weld room
4. start pumps
5. some water remaining in the hull

ALTERNATIVE for testing
1. plasma cut the  right wall into ballast
2. weld the wall
3. some water remaining

### Bug prevalence

Happens regularly

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/38d45b2e2a7e94864a04b9bcadb5757367d9464b

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/2262c951144821188b96c387907934f8308b0e75

Looked into the drainage capabilities of every hull in the submarine, found the lower diving exit cannot fully drain either, though the hull mentioned in this issue now drains correctly.

![image](https://user-images.githubusercontent.com/29177976/197415435-0bbd840d-e81c-48a0-8025-2bc2d8803ee1.png)

**Comment by Tsunder** [comment]
re: airlock bottom: the solution on other vanilla subs is to move the bottom edge of hull up, to be flush with the top of the hatch/water detector. this ofc visually moves the edge of the water.

an alternative that doesn't move either detector nor hull would be to use the detector's %_water pin -> set_state pump (manual set speed -100).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1b7af6b14cd547da35cd4a13890fa071f2f8004d

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/1b7af6b14cd547da35cd4a13890fa071f2f8004d, no issues found, closing.
