### ISSUE TITLE
Mudraptor and mines event

### ISSUE THREAD

**Issue by Lafken26** [Regalis11/Barotrauma#10067]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I arrived at the station, I found an event of some fangoraptor eggs, something about a mine and mating season, after talking to that man I couldn't do anything, not even continue with the mission that I had to talk to another more and I could not select normal missions to continue, I tried to restart it but it does not let me select anything else

### Reproduction steps

1. Arrive at the station
2. meet the man of the event
3. talk to him and then go to the other guy to continue the event
4. Observed how I couldn't interact with quest npc's

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3680/commits/1554d0057e3eeab2a84f143c7d34a9550c7e341a

Note for testing: the event in question is called '`occupationalhazards`'.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
