### ISSUE TITLE
Tandem Fire buff being disrupted

### ISSUE THREAD

**Issue by SmugFruit** [Regalis11/Barotrauma#10071]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In singleplayer I noticed that the tandem fire buff seemed to be disrupted if a bot/crewmate was standing in between the two people on periscopes. Neither person on the periscope has the buff or the person standing between them, its just gone.

### Reproduction steps

1.start new round
2.givetalent tandemfire
3.have two people operate periscopes
4.have another stand in between the two people on periscopes

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0433de7a4090f50d017b406a7e1cfab3d52835cc

**Comment by Jade-Harleyy** [comment]
Tested; Game now immediately crashes to desktop when a crewmate with Tandem Fire uses a periscope.
[crashreport (39).log](https://github.com/Regalis11/Barotrauma/files/9788921/crashreport.39.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/85b71bd5fc3d5a6edeea4bf5e3439d9b9f46b322
