### ISSUE TITLE
Duplicate lines in localization

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10075]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Duplicate strings are found in localization.

**EnglishVanilla.xml:**

- ``<servertag.friendlyfire.true>On</servertag.friendlyfire.true>``
- ``<servertag.friendlyfire.false>Off</servertag.friendlyfire.false>``
- ``<servertag.voip.true>Enabled</servertag.voip.true>``
- ``<servertag.voip.false>Disabled</servertag.voip.false>``
- ``<servertag.karma.true>Enabled</servertag.karma.true>``
- ``<servertag.karma.false>Disabled</servertag.karma.false>``
- ``<missionname.pvpmission>Search and destroy</missionname.pvpmission>``
- ``<missiondescriptionneutral.pvpmission>A Coalition vessel has been dispatched from [location1] to destroy a renegade vessel at the outskirts of [location2].</missiondescriptionneutral.pvpmission>``
- ``<missiondescription1.pvpmission>A renegade vessel has been detected at the outskirts of [location2]. Treason against the Europa Coalition is punishable by death—eliminate the renegades by any means necessary.</missiondescription1.pvpmission>``
- ``<missiondescription2.pvpmission>You're a member of the Jovian Separatists, a group opposing the Europa Coalition. According to your informants at [location1], a Coalition vessel has just been dispatched on a mission to take down your boat. Eliminate their crew by any means necessary.</missiondescription2.pvpmission>``
- ``<selectedsub>Selected submarine</selectedsub>``
- ``<talentdescription.stillkickingheal>Whenever you fall below 0 health, rapidly heal normal damage types and remove stun over a short duration.</talentdescription.stillkickingheal>``

**RussianVanilla.xml**

**_1. Twice:_**
- ``<servertag.friendlyfire.true>Вкл.</servertag.friendlyfire.true>``
- ``<servertag.friendlyfire.false>Откл.</servertag.friendlyfire.false>``
- ``<missionname.pvpmission>Найти и уничтожить</missionname.pvpmission>``
- ``<missiondescription2.pvpmission>Вы состоите в организации «Юпитерианские сепаратисты», выступающей против Коалиции Европы. Ваши агенты в точке «[location1]» докладывают, что Коалиция отправила за вами одну из своих боевых подлодок. Уничтожьте противника любыми доступными средствами.</missiondescription2.pvpmission>``
- ``<selectedsub>Выбранная подлодка</selectedsub>``
- ``<talentdescription.stillkickingheal>Когда ваше здоровье опускается ниже 0, урон обычных видов быстро исцеляется, а оглушение проходит через короткий промежуток времени.</talentdescription.stillkickingheal>``

**_2. Four times:_**
- ``<locationnameformat.city>[name]</locationnameformat.city>``

### Reproduction steps

Check text for duplicate lines.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed this now (although the changes won't be going in until we import the next batch of localized texts). The duplicate location name formats in Russian don't actually seem to be a bug, the translators seem to just have decided to use one format for all of the variations.
