### ISSUE TITLE
Barotrauma Dev version bags dock

### ISSUE THREAD

**Issue by nomot132Rus** [Regalis11/Barotrauma#1007]
Bags in dock. Don`t docking shuttle and submarine...

The dock is not attached to the submarine

Maybe because the Dock in physical shape and can't go to the other Dock. 
The result: the Dock can't sign in with a different Dock because of the physical form. Thereby not giving proper connections.
Video with problem https://streamable.com/up9op

Windows 10/9.0/Dev version

**Comment by Regalis11** [comment]
Fixed in bc2a56c
