### ISSUE TITLE
Reactor fade in sprite visual error

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#10073]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The reactor sprite between 39 and 1 condition shows a small part of another reactor
![bug](https://user-images.githubusercontent.com/87786019/195508336-4123edaa-dcfe-4c4d-9e64-0daf3ecfd4f6.png)

### Reproduction steps

Bring the reactor between 39 and 1 condition, a small part of the red light sprite show ups on the right

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by dinhtuananhfakefish** [comment]
Fixed in a6d91cc976

**Comment by Rokvach** [comment]
No issues, closing.
