### ISSUE TITLE
Texts in EnglishVanillaNew.xml cannot override texts in EnglishVanilla.xml.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#10074]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

i have noticed that the description of Mg is still using the old description.
![image](https://user-images.githubusercontent.com/44423036/195580916-83616019-a3fe-4310-b39d-39a45ffebc71.png)

see texts in EnglishVanillaNew.xml: 
<entitydescription.magnesium>Used in the manufacture of explosives and medical compounds.</entitydescription.magnesium>
also see texts in EnglishVanilla.xml: 
<entitydescription.magnesium>Used in the manufacture of explosives and medical compounds. Reacts violently when in contact with water.</entitydescription.magnesium>

I guess texts in EnglishVanillaNew.xml can override texts in EnglishVanilla.xml, so this will be good for update and translate, but now for some reason it doesn't work.

Also noticed that issue #8450 may related to this. But that one had a tag "feature request". 

As an unofficial workshop mod localize modder, I think it is good to let modders to override the localizations, so official won't have to check the localization, especially in languages they don't know. Yes, as devs you still need [Waiting](https://github.com/Regalis11/Barotrauma/labels/Waiting) official-localizers' work and merge them. But as players and modders we will have other solution. Such as "Simplified Chinese Texts Optimisation"(https://steamcommunity.com/sharedfiles/filedetails/?id=2608626775), it has 47,098 subscribers. But because mods cannot override the localizations, some texts will blink, like #8450.

### Reproduction steps

1.start a game and see magnesium's description

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This is not really a bug though - EnglishVanillaNew is not a file for overriding texts, it's just an additional text file. There is currently no way to override texts.

**Comment by tinygrox** [comment]
> There is currently no way to override texts.

@Regalis11 
NTYMI, I'd like to ask: What things could `<override>` the tag overrides for now? Only Items?

**Comment by Regalis11** [comment]
@tinygrox I think it should work for practically [all content types that use identifiers](https://regalis11.github.io/BaroModDoc/Intro/ContentTypes.html) (when you define an override with some identifier, it'll override the base content with that identifier). Texts don't really work the same way (at least now) - texts defined with the same tag are treated as alternatives of that piece of text.

**Comment by tinygrox** [comment]
Alright then. Thanks for the patience. 😬 
I just found a way to "override" texts by create a new language as a mod.
