### ISSUE TITLE
[Bug] Docking ports do not generate dynamic hull zone near outpost dock module

### ISSUE THREAD

**Issue by DanJF** [Regalis11/Barotrauma#10087]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Greetings,

Trying to make a transport vessel which uses a coupled-minisub as a cargo lift, that I'm attempting to "dock" to outposts.

The challenge is that the docking outposts have no docking ports (vertical), just a docking hatch (horizontal).
So to accomplish this, my sub has a free-floating docking port piece above it, and the cargo lift essentially re-docks with the main-sub, and in a way where it's aligned with the outpost door.

In it's initial state at the bottom of the lift, the docking ports of the main and minisub generate the dynamic hull, as expected.
When I test this in the sub editor test mode, it works just fine, and the docking ports generate a dynamic hull. I can move between the outpost module and the lift without flooding or issue.
But when I test in single/multiplayer, the game does _not_ generate a dynamic hull for the docking ports.

The bug being that it _should_ generate the dynamic docking port even while in proximity to the outpost docking module.
Is this coded into the game a fix from years gone by? 
If so, please consider reviewing it again? 
Or perhaps adding docking-ports to the side doors of the station as well?

Pictures and .sub files provided below.
Thank you for your time to review this bug, and consideration for it's change.

![ECN Angler Dynamic Hulls](https://user-images.githubusercontent.com/12960364/195990448-bf1b5f31-94a3-44e0-8d09-279fd177a408.png)

![ECN Angler Docking No Dynamic Hull Generated](https://user-images.githubusercontent.com/12960364/195990445-cd61d6ff-72e1-43e3-adfa-4649de2f6f2b.png)

ZIP with .sub files for my test configuration.
[ECN Angler Sub Files.zip](https://github.com/Regalis11/Barotrauma/files/9792256/ECN.Angler.Sub.Files.zip)

### Reproduction steps

1. Create a janky little tugboat sub with a novelty cargo lift 'cause it's neat and how my imagination portrays dat Europa transport trucker lifestyle

2. Use the Outpost_Docking_Module_01 pieces in the editor, and spend a silly amount of hours to dial-in to pixel-perfect hull-meshing, and perfect the docking to where it never floods thinking that it successfully works, and that all is right in the world.

3. Try it out in single player and find that for some reason it doesn't work. Investigate further to find that docking ports generate dynamic hull zones in all cases...except this specific one that would let you dock the cargo lift. T-T

4. Respectfully submit a bug and pray to the honkmother

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Just to make sure I understood the problem correctly, the hulls don't generate between the lift and the outpost's docking module when the lift is in the upper position? 
![image](https://user-images.githubusercontent.com/14351070/196044928-1c5a8437-4ca7-4bf0-9eaf-5ad76f08187d.png)

I would not necessarily consider that a bug: there is no docking port there, and no way for the lift to dock to the outpost, so there will be no hulls between them either.

**Comment by DanJF** [comment]
Correct, the outpost module has no docking port.
However I am not truly docking to the module, but a free-floating docking port which is part of my own sub.

If you look at the sub in the editor, the submarine has a free-floating docking port above it. I may have forgot to set its transparency to 255, sorry about that!
This aligns the lift to the outpost door, and allows the cargo lift to appear as though it docks to the outpost.

The two ports for the lower stage of the lift generate a dynamic hull.
But the two ports at the upper stage do not.
Not understanding why it'd generate in one case, but not they other, and the only indicator I have is the presence of the outpost. 
And, when I used the outpost dock module parts in the editor to test all of this, it generated the dynamic hulls.

Hopefully this clarifies!
Thank you again for your time.

**Comment by Regalis11** [comment]
Thanks for the clarification! Giving this a test in the sub editor, it seems there's no hulls generated there either. There's a warning in the console that explains why: the dynamic hulls are only generated if there's a hull at the other side of the port.
![image](https://user-images.githubusercontent.com/14351070/196047753-9175e01f-601f-48b6-b244-0e54f81f47d4.png)

However, even if you added an extra hull near that hidden docking port, I doubt this will work correctly - the dynamic hulls would be generated between that extra hull and the lift, not the lift and the outpost, most likely leading to all sorts of oddities if you try to get through the port.

So I'm afraid there probably isn't a way to get this working reliably at the moment due to the lack of a docking port at the side of the outpost (or at least I can't think of one myself). But I do think this is a really cool idea and a clever way to implement it, so I think we might look into adding a port to the side of the airlock at some point.

**Comment by DanJF** [comment]
I think it just crossed my mind why.
In sub editor testing, my main sub was not docked to the outpost parts.. just aligned in the waybi mentioned.

Single player, main sub starts docked.
Guessing main sub can't be docked to the outpost AND to the lift? (Limit on # of docked entities?)

**Comment by DanJF** [comment]
Did it with the outpost part as a docked piece, instead of free-floating+aligned. Now reflects SP/MP condition.
[ECN Angler Bug Recreation.zip](https://github.com/Regalis11/Barotrauma/files/9806449/ECN.Angler.Bug.Recreation.zip)

I could swear though I've docked Minisub>Minisub>Main-Sub before with other vessels with no problem, but it seems to be an issue here. This is pretty much it though so, closing. Thanks for your time examining this!
