### ISSUE TITLE
[Dev version] Texture scale not saving/loading

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1008]
Setting texture scale setting in the sub editor works, but, once you reload the sub, it goes back to default.
Was it disabled for reasons similar to ones with the item scaling function or is that a bug?

The latest version that i have with saving/loading still working is from 15.12.2018
The one where it stopped working for me is from 09.01.2019

**Comment by Regalis11** [comment]
Fixed in 9425505
