### ISSUE TITLE
If Barotrauma starts on other keyboard layout than english, controls doesn't work

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#10085]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When playing on arch linux, if barotrauma starts on other keyboard layout (like russian keyboard layout), controls doesn't work. Same issue #8186

### Reproduction steps

1.Choose russian or other keyboard language, but not english.
2.Start barotrauma.
3.Try to play anywhere, WASD will not work

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Same issue as https://github.com/Regalis11/Barotrauma/issues/8186
