### ISSUE TITLE
Physicorium railgun shell XML issue

### ISSUE THREAD

**Issue by Robathome** [Regalis11/Barotrauma#10088]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Found a spelling mistake in railgun.xml, line 245. Current tag type is "Addliction", should be "Affliction". I suspect this is causing the game to skip the bleeding damage that should be applied with this ammunition type. Haven't confirmed effects in game, since it's kind of difficult to tell if something that wants to kill you is actually bleeding.

### Reproduction steps

Railgun.xml, line 245

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/10f6ce069e17c7b9f0c049d294af295b61933599

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
