### ISSUE TITLE
updating/validating barotrauma resets player/server configs

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10089]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

configplayer and serversettings seem to be lost on validation/ game update

server  name is reset to Server, players to 10, karma is reset

enabled mods/sub list is wiped 

#4048 

I think that for the average user this is only annoying, and I misconfigured/corrupted settings seem to reset the files on load anyway (last time i put some bad xml), so I don't think there's any benefit to resetting.

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
> configplayer 

By this you mean config_player.xml? I wasn't able to reproduce the issue: that file isn't included in the Steam depot by generated by the game, and verifying file integrity doesn't seem to do any modifications to it.

**Comment by Regalis11** [comment]
Removed the default server settings file in https://github.com/Regalis11/Barotrauma-development/commit/79b2cf9e13244ea72413f45d6bb7c4b1ba6ce90f

**Comment by JustOneSummer** [comment]
> > 配置播放器
> 
> 你的意思是config_player.xml？我无法找到该文件的任何问题：它不包含在Steam仓库中，而是由游戏生成的，并且验证文件完整性似乎不会对其进行任何修改。



> > configplayer
> 
> By this you mean config_player.xml? I wasn't able to find any issues with that file: it isn't included in the Steam depot, but generated by the game, and verifying file integrity doesn't seem to do any modifications to it.

each time you restart the server, serversettings.xml will be reset

**Comment by JustOneSummer** [comment]
> > configplayer
> 
> By this you mean config_player.xml? I wasn't able to find any issues with that file: it isn't included in the Steam depot, but generated by the game, and verifying file integrity doesn't seem to do any modifications to it.

each time you restart the server, serversettings.xml will be reset

**Comment by Regalis11** [comment]
The issue with serversettings.xml has been addressed in the commit mentioned above (and the fix is included in the unstable version and coming up in the next public release), but there should be no issue with config_player.xml. No known steps to repro that part of the problem, closing
