### ISSUE TITLE
Console keeps popping up FailedNotConnected, causing the server to be very stuck

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10083]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

It happens almost while round is starting and ending. Console keeps popping up the following things:
Failed to send message to {EndPoint}: FailedNotConnected
![image](https://user-images.githubusercontent.com/73634685/195959690-a8ded8b5-cb2d-4bfe-884f-9ccc086a3aee.png)
When I find who has this end point and kick it, the server will working fine.
Not sure is this caused by mods(Lua For Barotrauma, CsForBarotrauma, CQB Mode, Extended Vanilla Traitor), and I don't know how to reproduce this.

I'm managing a server and every time the player count goes above 20 (probably irrelevant to the player count), there is really high chance produce this and i have to restart the server because of it.

### Bug prevalence

Happens regularly

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

**Comment by zhu-rengong** [comment]
More details: During the server lags, most players will disconnect with the server because of the failure of STEAM authentication.

**Comment by zhu-rengong** [comment]
Seems to be easy to reproduce it on a server with a very large number of players (＞20 ppl), but don't know the exact conditions to reproduce it.

**Comment by Regalis11** [comment]
No known steps to repro, and we haven't received reports of this occurring in the vanilla game. Closing
