### ISSUE TITLE
Tandem Fire Bug with Max Health Talents

### ISSUE THREAD

**Issue by SmugFruit** [Regalis11/Barotrauma#10082]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Currently found a couple more issues with Tandem fire and its interaction with another crew member/bot with endocrine booster talents.

A security officer with Enforcer, Field medic and College Athletics the latter two talents granted by Endocrine booster has the Tandem Fire buff applied to them much slower than normal. I suspect its the increase in max HP from these three talents as its this specific combination that causes this behaviour
![Tandem Fire Bug 1](https://user-images.githubusercontent.com/115676495/195956922-82df7975-a427-4a2c-8cd5-0847b519e3ca.png)

In addition to this slow application of the buff, it seems some other combination or addition of talents causes it to be constantly 'purged' and reapplied while in continued operation of the periscope. I haven't been able to pin it down to any specific talents or combinations as of right now but I do have a security officer experiencing this bug in my solo campaign with the talents in the image below.

Full list of Extra talents is as follows: College Athletics, Double Duty, Fireman's Carry, Field Medic, Still Kicking.
![Tandem Fire Bug 2](https://user-images.githubusercontent.com/115676495/195956932-cebb00c9-946b-42af-84e3-efc5d344488e.png)

### Reproduction steps

1.start a test sub or campaign
2.spawn two security officers
3.give security officer 1 givetalent tandemfire
4.give security officer 2 givetalent enforcer, givetalent fieldmedic, givetalent collegeathletics
5.have both security officers operate periscopes
6.observe application of tandem fire buff to security officer 2 is slowed dramatically 
7.add additional talents as detailed in the 2nd image until you observe behaviour of tandem fire buff constantly being removed and reapplied

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Tandem Fire still exists, so probably the interaction with Max health increases is still bugged.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/949d9d6e4402c5ded784ba0b4820e4afa561f9a3

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
