### ISSUE TITLE
going freecam in solo campaign in MP immediately ends the round/goes to lobby

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10094]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

using freecam command immediately ended the round and went back to lobby.

expectation is freecam to work and not go back to lobby

### Reproduction steps

1. enter MP campaign with 1 player, 1 bot
2. enablecheats
3. freecam

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is in a sense intentional: if there are no players alive / controlling a character, the round ends automatically.
