### ISSUE TITLE
Husk gene bot gets treated by medic bot, defeating the purpose of the genes.

### ISSUE THREAD

**Issue by Champaris** [Regalis11/Barotrauma#10097]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Now I dont think any of the mods I used were even remotely involved with this. One of my bots which I take as a guard while going out of the submarine has husk genes and a husk infection, which allows a good old mudraptor shell instead of a diving suit or the need for oxygen tanks. While I did not notice it when it happened, I believe they got injured, probably by ballast flora, and one of the bot medics treated them for husk infection when there was no need. A simple solution is to simply lock the anti husk medicine where only the player can get it. I don't know wether it is a one time thing or not, but it is genuinely the only cause I can think of.

### Reproduction steps

1. Start a solo campaign.
2. Get a bot guard husk genes and husk infection.
3. Get a bot medic with ample medical supplies and calyxanide/broad spectrum antibiotics.
4. Injure the guard badly enough to get the medic to treat them.

### Bug prevalence

Just once

### Version

Other

### -

I use the most up to date barotrauma version, and have server side lua installed for macOS, this shouldnmt interfere in any way though.

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
No malfunction of the game here, so no error text from the console.
```

**Comment by Champaris** [comment]
Additional notes, Ive already seen in the chat the medic bot state that they needed either morphine or calyxanide to treat my guard.

**Comment by Dimasw99** [comment]
Had the same issue accrue to me on vanilla. Same situation where the bots ignored the husk infection up until they had to get treated due to severe burns

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/24aad1892591b07abbfdda1680c759abec9ffe9e

In the current release - The bots generally do not appear to try to attempt to heal the husk infections, medic bots on heal and rescue order ignore it, all the way up to the point they start convulsing. Tried calling out for a medic both as a player controlling the infected at both lower and higher stages as well as calling out a hull containing an infected (even when convulsing).

It appears they might attempt to heal them if they have lost vitality to other afflictions (or if the husk affliction itself was setup to lose vitality) indicating it has something to do with order priorities on selecting who to treat being linked to said vitality.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/7f4419b844f51ca2fa31f33f7c509ab1eb783aeb.

After much testing, I've found that once a character obtains husk genes (for the infection immunity), the removal of husk genes (IE. by giveaffliction) medic AI's will not treat that character for husk infection when having other wounds, even if fully healed of it and getting a new instance of husk infection.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843, no issues found, closing.

Notes: At time of testing there were some issues involving the injection of calyxanide having no effect, but AI-wise it was doing the correct actions (in terms of avoiding treating it with husk immunity when treating other afflictions, and treating husk infection once the immunity is gone or was not there).
