### ISSUE TITLE
Networking errors after level transition ("Received STARTGAMEFINALIZE packet" spam)

### ISSUE THREAD

**Issue by Yonderwolf** [Regalis11/Barotrauma#10098]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**Issue:**
Alright I don't know if this is a bug, but for people like me that uses big ships to host serves, it crashes the server (Not the game) when transitioning from the station to Depths of Europa, or from the Depths of Europa to the station. When the server crashes everything is loaded in, but the players. On top of this from the players/host perspective when this issue occurs sees everything like if they're spectating. (Loading in from server lobby to ingame does not cause any issues known so far)

**Tedious Solution:**
After every round in campaign restarting the host and having people rejoin is the only way to progress forward.

### Reproduction steps

1. host a game with 10 - 12+ players and a decent size ship. Example sub we use: https://steamcommunity.com/sharedfiles/filedetails/?id=21217256862
2. Go from station to the depths of Europa or other way around.
3. The issue occurs after completing step 2.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Could you send us the crash report?

**Comment by Moose1002** [comment]
I'm suffering from the same issue with a crew of roughly 10 people on the R-29 sub. I am using mods so one of them could very well be causing it, but I figured I would send a
[Moose Co Campaign_2022-10-17_2154.txt](https://github.com/Regalis11/Barotrauma/files/9806177/Moose.Co.Campaign_2022-10-17_2154.txt)
 log of mine just to see if it could help, or if I could figure out what mod is the problem.[](url)

**Comment by Regalis11** [comment]
Thank you for the logs! Unfortunately there doesn't seem to be anything there that'd indicate why the server crashed, nor any error messages that could give us extra clues. To be clear, does the server actually crash (is there a notification saying it crashed), or do the clients just disconnect due to some kind of an error? Are there any kinds of error messages displayed?

**Comment by Yonderwolf** [comment]
Sorry for the late response, but no the server doesn't actually crashes,
it's more rather it's very slow on loading in the players causing some
players to timeout. I sadly don't have nay crash report as the server
doesn't necessarily crash, but I do have picture of the console saying
multiple things. One of them being "WARNING: Failed to send message to
remote peer! (With a random amount of Bytes)" which is spamed in the
console. Another that pops up is this message "Server Running Slowly (55
Updates/s)". Lastly the other console message that pops up is the
"Received STARTGAMEFINALIZE packet. Round init status

**Comment by Yonderwolf** [comment]
Sorry I accidentally sent the previous message without completing it, so
I'll complete it here. Lastly the other console message that pops up is the
"Received STARTGAMEFINALIZE packet. Round init status: Started", this
message is spammed repeatedly more than the amount of players in the
server.

*I have pictures of the console saying all of this and if you need me to
send it to you let me know.*

**Comment by Yonderwolf** [comment]
I'll be recording this issue in game when I get a chance and will be posting the recording on here for evidence.

**Comment by Regalis11** [comment]
Thanks! The most useful information for diagnosing the problem would be the exact error message (you can copy it from the debug console by double clicking) or the crash report if there is one available. Although based on the console messages, it sounds like the server is not a crash, but some kind of a networking issue that leads to a disconnect.

**Comment by Yonderwolf** [comment]
This specific issue I have seen raised on the official discord technical support channel multiple times from multiple people, and I'm assuming this is what they're experiencing.

**Comment by Yonderwolf** [comment]
Let me add. **Loading from the server menu to in game works fine no matter where at. The issue only occurs when in game transitioning to different areas.**

**Comment by Yonderwolf** [comment]
It's seeming the problem is that when transitioning between levels is that the save doesn't send to any of the clients at all, which causes everyone to lose connection.

**Comment by Yonderwolf** [comment]
![Screenshot 2022-10-20 023932](https://user-images.githubusercontent.com/115947743/196887317-d2d280b8-8668-49ed-9748-67088409317f.png)

**Comment by Yonderwolf** [comment]
This message popped up repeatedly and on top of this I have recording as well mind you this is on the client view.

**Comment by Moose1002** [comment]
> ![Screenshot 2022-10-20 023932](https://user-images.githubusercontent.com/115947743/196887317-d2d280b8-8668-49ed-9748-67088409317f.png)

This is the same error that clients connected to the server get every level change for me as well. I don't get it as the host, but clients connected to the server will occasionally get disconnected because of it. Those who don't end up getting disconnected wait in the spectator view for roughly 1-2 minutes before everyone loads in. Some clients still seem to be loaded before everyone gets in, and leaving the reactor off as you leave an outpost seems to cause specific players to get random afflictions (I think this is caused by the oxygen generator not running because it has no power and draining the sub of oxygen while everyone waits the 2 minutes to load into the sub, but this could just be a mod issue since we're running Neurotrauma). One thing I mentioned above is that I've noticed that the people getting the file transfer cancelled seem to be players that have died, and since re-spawned. I don't know for sure if that is actually related to the problem, but I figured I would mention it just in case it can provide any leads. It also could totally be coincidental, as I think sometimes players have had the issue even when they haven't died, but I'm not for sure, I'd have to test some more.

**Comment by Yonderwolf** [comment]
> > ![Screenshot 2022-10-20 023932](https://user-images.githubusercontent.com/115947743/196887317-d2d280b8-8668-49ed-9748-67088409317f.png)
> 
> This is the same error that clients connected to the server get every level change for me as well. I don't get it as the host, but clients connected to the server will occasionally get disconnected because of it. Those who don't end up getting disconnected wait in the spectator view for roughly 1-2 minutes before everyone loads in. Some clients still seem to be loaded before everyone gets in, and leaving the reactor off as you leave an outpost seems to cause specific players to get random afflictions (I think this is caused by the oxygen generator not running because it has no power and draining the sub of oxygen while everyone waits the 2 minutes to load into the sub, but this could just be a mod issue since we're running Neurotrauma). One thing I mentioned above is that I've noticed that the people getting the file transfer cancelled seem to be players that have died, and since re-spawned. I don't know for sure if that is actually related to the problem, but I figured I would mention it just in case it can provide any leads. It also could totally be coincidental, as I think sometimes players have had the issue even when they haven't died, but I'm not for sure, I'd have to test some more.

When I was in game with someone else hosting, I did not die, and this exact situation where the save doesn't transfer happened. On top of this I was surprised to find out we were also using a vanilla ship called "The Camel" or something along these lines. It was also a non-modded server.

**Comment by Regalis11** [comment]
We did several fixes that addressed issues in starting a multiplayer campaign round in the Summer Patch, it's likely that those fixes took care of this issue as well, since there don't seem to have been any reports about it after the patch.
