### ISSUE TITLE
One of two coilgun loaders in wrecked dugong is non-interactable

### ISSUE THREAD

**Issue by feru7** [Regalis11/Barotrauma#10096]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The right of the two wrecked coilgun ammo loaders in the dugong wreck is set to non-interactable, but can spawn loot inside. The left one is set to be interactable and spawns loot.

![dugong_wreck](https://user-images.githubusercontent.com/96304666/196040396-805a8e7c-a382-4d1f-9c74-02e675c0aba6.jpg)

### Reproduction steps

Open wrecked dugong in submarine editor.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2bdfdd536520eb14ba79a420ec86a2e32d17284a

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/2262c951144821188b96c387907934f8308b0e75, no issues found, closing.
