### ISSUE TITLE
funny magnesium description

### ISSUE THREAD

**Issue by deltanedas** [Regalis11/Barotrauma#10093]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

i think magnesium has flash powder's description??
it says it is made of magnesium...

![22:45:22](https://user-images.githubusercontent.com/39013340/196008753-ba3480d6-17b6-4e08-a2b6-096fd663dd2d.png)

### Reproduction steps

1. look at magnesium in shop
2. it says its made of magnesium

magnesium

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91e3c191c3fc8f760a4e4cbaf5a45cdea9fbb1d4

**Comment by Lithosagym** [comment]
Tested, magnesium's description now reads, "Used in the manufacture of explosives and medical compounds." Issue is fixed.
