### ISSUE TITLE
non-detachable item / doors/hatches show up on status monitor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10092]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

doors/hatches can be searched for in the item finder

not sure if intentional, as well, they can't be picked up or put anywhere.

however, they do clog up the search (for example searching for "button")

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Even though this might not have been intentional originally, I think it may have some niche uses: you might for example want to see where some of the ducts that drain the sub are located.
