### ISSUE TITLE
Turning sonar off while still in directional mode alerts Molochs from every direction, completely defeating its purpose

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#10099]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This includes cases when you emit a single directional ping

### Reproduction steps

Debug AI targets:

`quickstart azimuth`
`debugdraw`
`aitargets`

Set the ship sonar to directional and turn it on

`freecam`
Spawn a moloch off the axis of the sonar beam
`spawn Moloch cursor`
Moloch will be idle.
![image](https://user-images.githubusercontent.com/68995233/196068358-16293c68-f445-48e1-9fed-a020e301e968.png)

Take control of the crew captain from the "C" menu
Open the Navigation terminal

Press F3 before turning off the sonar to pause the game, then turn off the sonar while "Directional Ping" is on
`pause`
`freecam`

The moment you turn off the sonar completely, it emits an omnidirectional pulse which will enrage the Moloch
![image](https://user-images.githubusercontent.com/68995233/196068591-ce274342-3771-4050-bc38-5acd055517e2.png)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/49b94885ab1a29e76822d99f4466d75f889ba774

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
