### ISSUE TITLE
Severe Performance Drop while in Lobby (Hosted or Joined)

### ISSUE THREAD

**Issue by CrayonEaterExtraordinaire** [Regalis11/Barotrauma#10101]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game performance inexplicably has declined in recent days. 
Specifically the game stutters to a slide show - not registering inputs or User interactions (Mouse movement, key inputs, <5fps).
The load time of the game, time from "host" to lobby, and loading into a hosted/joined server has increased significantly.

Shown here:
<https://www.youtube.com/watch?v=_lQ5pnCvkGY>
-Live Resource Monitor
-Game Load (Significantly slower that initial pre-purchase of game - and 24 hours after)
-Single Player New Game start
-Host Server Launch (Severe performance drop without increase hardware performance issues)
-Hosted server game play
-Return to Server Lobby (Severe performance stop without increase hardware performance issues)

This is of concern as deleting/uninstalling the game via steam and deleting of system files containing meta data of the game (ex. Daedalic Entertainment GmbH folder located in %localappdata%) has not reverted the issue. 

Note: If game had performed such during the free weekend user wouldn't have purchased it and accepted the performance as hardware limitations.

### Reproduction steps

1. Start game (note load time)
2. Host/Join a server (note join time)
3. While in lobby  (note performance drop)

If specifics on how to submit game log for these actions are provided, will gladly follow and report back with data. 

As well - if there are more through and specific ways to ensure the entirety of the game is deleted from the system before reinstall, those steps will also be followed and reported back on.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Log provided in the recording of the video shared earlier in this report.

[10/16/2022 00:34:24]
  Starting the server...
[10/16/2022 00:34:24]
  Using SteamP2P networking.
[10/16/2022 00:34:24]
  Server started
[10/16/2022 00:34:24]
  Gubbin has joined the server.
[10/16/2022 00:34:24]
  Saving client permissions
[10/16/2022 00:34:24]
  Saving client permissions
[10/16/2022 00:34:25]
  Gamemode changed to Campaign
[10/16/2022 00:34:54]
  Starting a new round...
[10/16/2022 00:35:06]
  Game mode: Campaign
[10/16/2022 00:35:06]
  Submarine: Azimuth
[10/16/2022 00:35:06]
  Level seed: Shinkonai
[10/16/2022 00:35:09]
  Andres Geist equipped Wrench
[10/16/2022 00:35:09]
  Andres Geist unequipped Wrench
[10/16/2022 00:35:09]
  Andres Geist equipped Screwdriver
[10/16/2022 00:35:09]
  Dahlia Suarez equipped Wrench
[10/16/2022 00:35:09]
  Dahlia Suarez unequipped Wrench
[10/16/2022 00:35:09]
  Dahlia Suarez equipped Screwdriver
[10/16/2022 00:35:09]
  Fanny Mell equipped Wrench
[10/16/2022 00:35:09]
  Fanny Mell unequipped Wrench
[10/16/2022 00:35:09]

Thank you for your patience - I am not a trained or casual programmer, please forgive my lack of knowledge and feel free to give directions to be followed and tried. Thank you for this game, I hope I'm able to enjoy it as it used to play.
  Fanny Mell equipped Screwdriver
[10/16/2022 00:35:10]
  Sherita Lee equipped Wrench
[10/16/2022 00:35:10]
  Sherita Lee unequipped Wrench
[10/16/2022 00:35:10]
  Sherita Lee equipped Screwdriver
[10/16/2022 00:35:10]
  Sherita Lee unequipped Screwdriver
[10/16/2022 00:35:10]
  Sherita Lee equipped Crowbar
[10/16/2022 00:35:11]
  Shin Rowe equipped Wrench
[10/16/2022 00:35:11]
  Shin Rowe unequipped Wrench
[10/16/2022 00:35:11]
  Shin Rowe equipped Screwdriver
[10/16/2022 00:35:14]
  Jina Ellison equipped Crowbar
[10/16/2022 00:35:14]
  Jodee Chaney equipped Screwdriver
[10/16/2022 00:35:14]
  Cara Wiley equipped Crowbar
[10/16/2022 00:35:15]
  Round started.
[10/16/2022 00:35:16]
  Jodee Chaney unequipped Screwdriver
[10/16/2022 00:35:17]
  Andres Geist unequipped Screwdriver
[10/16/2022 00:35:17]
  Sherita Lee unequipped Crowbar
[10/16/2022 00:35:17]
  Jina Ellison unequipped Crowbar
[10/16/2022 00:35:17]
  Cara Wiley unequipped Crowbar
[10/16/2022 00:35:49]
  Gubbin set the value "Channel" of the item "Headset" to "0".
[10/16/2022 00:36:10]
  Client "Gubbin" ended the round.
[10/16/2022 00:36:10]
  Ending the round...
```

**Comment by Regalis11** [comment]
Thank you for the report!

> Game performance inexplicably has declined in recent days.
> Note: If game had performed such during the free weekend user wouldn't have purchased it and accepted the performance as hardware limitations.

This sounds quite strange, since there have been no patches/hotfixes/changes whatsoever to the game since October 6. I think that might imply something has changed at your end, not in the game itself. I noticed that texture compression was disabled in the game settings (by default it is on), I would try re-enabling it. It could be possible that you're starting to run low on video memory due to the uncompressed textures.

In any case, we have an [existing ticket about general performance issues](https://github.com/Regalis11/Barotrauma/issues/9396), so I'll close this one as a duplicate.

I'm sorry for the inconvenience!

**Comment by CrayonEaterExtraordinaire** [comment]
100% Already tried texture compressing, no change in the identified lobby performance.

If you'd please, share instructions for a complete uninstall of the game and I'll be glad to follow.

I request this because the "Uninstall" via steam left many things in game - workshop items, previous ban lists, completion of tutorial etc. meaning it wasn't a complete uninstall.

Would love to get this game back to how it was playing.

**Comment by CrayonEaterExtraordinaire** [comment]
> Thank you for the report!
> 
> > Game performance inexplicably has declined in recent days.
> > Note: If game had performed such during the free weekend user wouldn't have purchased it and accepted the performance as hardware limitations.
> 
> This sounds quite strange, since there have been no patches/hotfixes/changes whatsoever to the game since October 6. I think that might imply something has changed at your end, not in the game itself. I noticed that texture compression was disabled in the game settings (by default it is on), I would try re-enabling it. It could be possible that you're starting to run low on video memory due to the uncompressed textures.
> 
> In any case, we have an [existing ticket about general performance issues](https://github.com/Regalis11/Barotrauma/issues/9396), so I'll close this one as a duplicate.
> 
> I'm sorry for the inconvenience!

Also - if you review the video, you'll see that the hardware wasn't running out of resources. I'll create a new video using GPU-Z to showcase the GPU specifically.

**Comment by mygamingaccount** [comment]
@Regalis11 this is not a duplicate

I decided to try to investigate after getting reports from Windows users too about this

Running a debug build of Barotrauma with `dotnet-trace` recording the performance while in the lobby menu, the result suggests that it's one of the native libraries linked by Barotrauma:

```
~/Projects/Barotrauma/game$ dotnet-trace report ../Barotrauma_20221020_085439.nettrace topN
Top 5 Functions (Exclusive)                                                  Inclusive           Exclusive
1. Missing Symbol                                                            55.38%              55.38%
2. WaitHandle.WaitOneNoCheck(int32)                                          13.76%              13.76%
3. EventSource.DefineEventPipeEvents()                                       8.83%               8.83%
4. Alc.GetStringList(int,int32)                                              7.13%               7.12%
5. Thread.Sleep(int32)                                                       6.73%               6.73%
```

Loading the trace into Speedscope, the external function seems to be called by `Barotrauma!OpenAL.Alc.GetStringList(int,int32)`:
![image](https://user-images.githubusercontent.com/68995233/196883383-717ee465-10c0-4f89-afd8-53a9fdefbba9.png)

Attaching the nettrace file:
[Barotrauma_20221020_085439.nettrace.tar.gz](https://github.com/Regalis11/Barotrauma/files/9827331/Barotrauma_20221020_085439.nettrace.tar.gz)

**Comment by esirprus** [comment]
This happens on my friends too.
