### ISSUE TITLE
No way to fix wrecked sub without spawining into said wrecked sub

### ISSUE THREAD

**Issue by Myrdden** [Regalis11/Barotrauma#10102]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Okay, so, scenario: We have just completed a mission, and docked at an outpost. Immediately upon loading in, we hear an alarm, we go down into the sub to investigate, and upon opening the door to the reactor room it melts down and explodes in our faces. Still no idea why, as it was fine when we docked. So, that sub is completely trashed, and we have no money to repair it, so we switch to our starter sub to attempt to earn enough to repair it. Once we've done so, we encounter our problem: There doesn't appear to be a way to repair a sub that is not currently selected, and upon selecting the wrecked sub, the engineer says they can't repair it until it's been delivered. So in order to initiate the switch, we'd have to start the mission, but starting a mission spawns us all into a completely wrecked sub with no power at which point we're basically screwed, and that campaign came to a very unwelcome close.

### Reproduction steps

1. Wreck a sub
2. Switch to different sub
3. Try to switch back & repair wrecked sub in outpost
4. Have to start a mission in wrecked sub in order to switch to it, essentially rendering that sub entirely unusable from then on.

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I understand how frustrating this situation is, but I would not consider it a bug: it is intentional that the repair option only repairs your current submarine.

> So in order to initiate the switch, we'd have to start the mission, but starting a mission spawns us all into a completely wrecked sub with no power at which point we're basically screwed, 

Wouldn't it be possible to repair the sub manually at that point? Or repair it enough to redock and pay for repairing the rest of the damages?

**Comment by Myrdden** [comment]
@Regalis11 You're probably right, we did attempt it but weren't terribly successful and eventually decided to give up. But even still that feels somewhat unreasonable? Why is it not the case that selecting a submarine does not make it your current submarine? Perhaps it would be better player experience to allow the mechanic to repair the hull of a selected sub and simply provide a confirmation that the options being selected in that menu will apply to the selected sub rather than the one currently docked? Or perhaps provide an alternative method, with the select screen or the sub merchant or something, to repair subs. This feels akin to like: You get into a car crash, your car is towed to the perimeter of a mechanic's shop, and the mechanic says that they won't be able to fix your car unless you go out and drive it into their garage.
