### ISSUE TITLE
Wreck1 railgun loader set as non-interactable despite autofilled with railgun shells.

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10103]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar issue to #10096, could potentially be more of the same problem elsewhere but haven't found any more so far.

Wreck1's railgun loader is unable to be interacted with, despite railguns spawning inside it

![image](https://user-images.githubusercontent.com/85914375/196185720-e4434545-cabe-409e-88f3-5ee8c2e21ccb.png)

### Reproduction steps

Look in the sub editor for wreck1.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/03efa7df11dee70b3fb101e77dca86134cae9470

Also prevented autofilling items into non-interactable containers in https://github.com/Regalis11/Barotrauma-development/commit/1ab21edeae6c6400efd2d896fbe8d1dfd49945a1

**Comment by NilanthAnimosus** [comment]
Tested first fix against dev commit https://github.com/Regalis11/Barotrauma-development/commit/2262c951144821188b96c387907934f8308b0e75, no issues found

Tested second fix against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/1fe17cd7d8d1f67f80ffb6f6ef33977517f4a4d3, no issues found, closing.
