### ISSUE TITLE
Highlightable Rust Decal

### ISSUE THREAD

**Issue by DailyCounselor** [Regalis11/Barotrauma#10100]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I just found a highlightable rust decal on one of the vanilla abandoned outpost maps.

![image](https://user-images.githubusercontent.com/115964567/196080018-b86a9cbb-e726-45f0-bd97-3cd12ab614b2.png)

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f737810ec5107495b7e73bf3efa5a598808ce95

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/1359aa355bc64bfeece9d4c4c807133affd8ff14, no issues found, closing.
