### ISSUE TITLE
PUCS does not trigger oxygen alarm when inside hulls

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10109]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When wearing a PUCS with no oxygen/<5% oxygen, while out in the open ocean, it will play the beeping loop as intended. 

However, inside hulls, such as those found in the submarine, wrecks and ruins, the PUCS sometimes does not play the beeping loop. Looking at the debug information, these hulls still have oxygen in them, even if they are full of water. This means that when the PUCS checks whether the hull it is in has oxygen in it, it will not play the beeping loop, even if the character cannot breathe.

Probably also the cause of this report
https://github.com/Regalis11/Barotrauma/issues/9627#issue-1315564166

### Reproduction steps

1. start a round in any submarine (I chose humpback because it has a ballast right next to the captain)
2. spawn in a PUCS (don't put any oxygen inside it)
3. set the ship to move directly down (fill up the ballasts)
4. jump into the ballast
5. observe that there is no beeping

### Bug prevalence

Happens regularly

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by MaaiG** [comment]
>these hulls still have oxygen in them, even if they are full of water.

In this respect, the game has a serious drawback! Oxygen not leaking anywhere in principle. Opening the hatch does not lead to oxygen leakage and flooding. Oxygen exists simultaneously with water. The oxygen detector demonstrates this perfectly! 👎 

https://user-images.githubusercontent.com/93348499/196507170-46e93944-37ae-4a30-aee9-6abeeae7126e.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06a4be12dbc0568661f5e5307706af3cd06a48c0

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/1b7af6b14cd547da35cd4a13890fa071f2f8004d, no issues found, closing.

Notes: Tested with both empty and full oxygen tanks, in the ocean, a dry hull and submerged in water in a hull, alarm worked as expected.
