### ISSUE TITLE
gun and ammo duplication through bandit ouposts

### ISSUE THREAD

**Issue by TMWReborn** [Regalis11/Barotrauma#10105]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when u enter an abandoned oupost theres a chance that the mission will be "return the captured outpost by blowing up the reactor". armed bandits spawns in this mission. if u kill all the bandits and leave the outpost without compleeting the mission. the bandits will respawn when u reenter it. and u can kill them as much as u want

### Reproduction steps

1. find the abandoned outpost with mission "blow up the reactor"
2. kill all the armed bandits and take their guns
3. leave the outpost without compleeting the mission
4. reenter the abandoned outpost 
5. repeat until u have enough guns and ammo

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Max112358** [comment]
Im not sure this is a bug.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/3856/commits/bb68de609bbf609ce013d315e15cc6b4aff3401d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
