### ISSUE TITLE
In "Consultant" event, option 3 checks wrong skill type.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10118]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

File "OutpostEvent.xml".
Line 1215,1216 and 1218 are:
`<Option text="EventText.consultant.o1.o1.c1.o3.o1">`
`<SkillCheckAction requiredskill="Medical" requiredlevel="50" targettag="triggerer_player">`
`<GiveSkillEXPAction skill="medical" amount="5" targettag="triggerer_player" />`

However, it should check "mechanical" skill according to the texts:
`<eventtext.consultant.o1.o1.c1.o3.o1>Attempt to solve the ventilation problem.</eventtext.consultant.o1.o1.c1.o3.o1>`
`<eventtext.consultant.o1.o1.c1.o3.o1.c1>You study a map of ventilation ducts. “Why not install an extra air filtration system right here?” you suggest, pointing to a junction near the dorms. “Should pump out all the mercury before it spreads farther.” And sure enough, it does. You collect a fee from the manager for solving the problem.</eventtext.consultant.o1.o1.c1.o3.o1.c1>`

### Reproduction steps

1.Trigger this event and finish it with the option 3 ("Attempt to solve the ventilation problem.").
2.It checks the character's "medical" skill instead of "mechanical" and gives the character 5 points of "medical" skill instead of "mechanical".

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional: you're investigating a problem with toxic gases causing health problems in the outpost, and solving it requires medical knowledge.

**Comment by BiffW** [comment]
Let me put it in a clearer way.
There are 3 options to solve this event.

Option 1: Persuade workers to give up demanding extra payment for high risk operation.
Requires: 50 helm skills
Rewards on success: 5 helm + 2000mk

Option 2: Tell the worker to treat themselves with “A combination of iron, Stabilozine and crawler liver”.
Requires: 50 medical skills
Rewards on success: 5 medical + 2000mk

Option 3: Study a map of ventilation ducts and suggest installing an extra air filtration system.
Requires: 50 medical skills
Rewards on success: 5 medical + 2000mk

Are you sure that option 3 is intended to be the same as option 2?
If so, I'd stop asking again.
