### ISSUE TITLE
Climbing the stairs - is too far from the bottom step

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10110]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Climbing the `stairs` is too far from the bottom step.
The character can interact in the middle of the `stairs`.
![Image 001_13-56](https://user-images.githubusercontent.com/93348499/196411447-7bd7f76d-7843-4f97-b4e5-f446c25d7dce.png)

### Reproduction steps

https://user-images.githubusercontent.com/93348499/196411487-34b0df4c-a6a5-401a-ba07-5a98a9c359c3.mp4

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional
