### ISSUE TITLE
Oxygen detector - strange readings

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10119]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the small compartment, the oxygen detector gives strange readings.
- Detector readings 99%
- Then the readings jump between 99% and 100%

https://user-images.githubusercontent.com/93348499/196748767-015a27e8-0bac-4496-a97b-7360ec48cd55.mp4

### Reproduction steps

[_Test-Strange_OxyDetector.zip](https://github.com/Regalis11/Barotrauma/files/9822433/_Test-Strange_OxyDetector.zip)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I don't think this a bug. The amount of oxygen flowing between the rooms is making the level fluctuate a bit.
