### ISSUE TITLE
Cargo Scooter no longer staying in place

### ISSUE THREAD

**Issue by SmugFruit** [Regalis11/Barotrauma#10117]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've noticed since the new update that the Cargo Scooter no longer stays in the place where you drop it in the ocean as the description says, and instead slowly falls down at about half the rate of other non buoyant items.

### Reproduction steps

1. Start a new test
2. Spawnitem cargoscooter cursor
3. Exit submarine with cargo scooter
4. Drop cargo scooter in open ocean
5. Observe how the cargo scooter now slowly descends instead of staying in place

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you! I'm afraid I could not reproduce this. The scooter does slowly sink, but extremely slowly, nowhere near half the speed of heavier items.


https://user-images.githubusercontent.com/14351070/196892848-3c13d316-e44d-4a98-be01-97e3b6ceaf57.mp4

**Comment by Regalis11** [comment]
Ah, that makes sense. :) It does seem the behavior changed slightly due to the optimizations we did to the buoyancy logic. I did a small adjustment to the logic that should fix the issue: https://github.com/Regalis11/Barotrauma-development/commit/c64f222cde160f22aee711f3051296cbc7460d51.

**Comment by Lithosagym** [comment]
Tested, cargo scooters stay completely still when dropped. Cargo scooters when spawned through commands sink down for a bit before becoming still again. Issue appears to be fixed.
