### ISSUE TITLE
Sub editor - When you save a file, it does not fit into a directory with the same name

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10120]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sub editor - when you save a file with a new name it is placed in the same folder where the original file was!

### Reproduction steps

1. Open the some file (`_Test-Strange_OxyDetector`) in the editor
2. Save the file under the some new name (`_Test-123`)
3. Open `\Barotrauma\LocalMods\_Test-Strange_OxyDetector\`
4. New file is saved in the same directory as a source file!

![4345767](https://user-images.githubusercontent.com/93348499/196755410-61fdb96f-e14f-4a06-88c4-88689ad25302.png)

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Could not reproduce. Are you sure you selected "create new local package" instead of "update local package" in the save dialog?
![image](https://user-images.githubusercontent.com/14351070/196871625-676096b2-ad4c-4ecc-8ceb-ca3937d87002.png)

**Comment by MaaiG** [comment]
Oops, you’re right! My mistake. I didn’t notice this feature. Sorry! Can be closed.
