### ISSUE TITLE
Banip and Banaddress Not functioning.

### ISSUE THREAD

**Issue by Hater4** [Regalis11/Barotrauma#10126]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So I run the Galilean Servers and ever since "Hoist the Sails" update came we have not able to ban anyone with Banip and Banaddress it would register the ban but the person would be able to join. I tried remote banning myself and it has not work with these methods, we used to be able to ban players from our server with banendpoint before the update came out. Btw the mods we are using are all server side and we run custom scripts on the server's end.
I have also tried this on vanilla server hosted by a friend.

### Reproduction steps

1. host a server.
2. open the debug menu/command console.
3. use Banip or Banaddress.  
4. then put in Steam ID or Steam64 ID of someone that's willing to help with the test who not in in the server.
5. and have them try to join back in after the command.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

![Capture1](https://user-images.githubusercontent.com/116253813/196883212-77bb1a9e-1b36-4cb8-bf79-0ed5f02244a9.png)

**Comment by NilanthAnimosus** [comment]
Tested against banaddress-fix commit https://github.com/Regalis11/Barotrauma-development/commit/2a004f069c507536c7c79157a558b96ff1714ab5, no issues found, can be merged.

**Comment by NilanthAnimosus** [comment]
Tested against banaddress-fix commit https://github.com/Regalis11/Barotrauma-development/commit/2a004f069c507536c7c79157a558b96ff1714ab5, no issues found, closing.

**Comment by Regalis11** [comment]
Merged
