### ISSUE TITLE
"Failed to start campaign round (campaign map not loaded yet)" error when starting a campaign

### ISSUE THREAD

**Issue by 3eyc** [Regalis11/Barotrauma#10121]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So when i am starting multiplayer campaign we all loading in but for some reason after a couple of seconds everyone except me getting back into lobby with console error. Rejoining and pressing spectate button didnt helped.

### Reproduction steps

1. Start a multiplayer campaign

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to start campaign round (campaign map not loaded yet).
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__107" has failed
```

**Comment by Regalis11** [comment]
Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/11261, closing as a duplicate
