### ISSUE TITLE
Steamcmd not updating dedicated server

### ISSUE THREAD

**Issue by Riking27** [Regalis11/Barotrauma#10139]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I had installed a Linux dedicated server through steamcmd with 19.11.0, and running the app_update command doesn't bring the server up to 19.14.0- it stays on 19.11.0.

Am I meant to copy my local game files to the server or something?

### Reproduction steps

1. Already have an installed dedicated server using steamcmd with an old version (???)
2. Update the server, and presumably get 19.11.0 instead of 19.14.0.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I could not find a way to reproduce this, the server seems to update correctly: 
![image](https://user-images.githubusercontent.com/14351070/197472941-7b5986e1-8587-46bd-a969-73d1207cd8fc.png)

**Comment by Riking27** [comment]
This seems like a steamcmd issue to me. I was able to get it to work by uninstalling and reinstalling the app, so 19.14.0 was available all along, but steamcmd was refusing to update it for some reason.
Thanks!
