### ISSUE TITLE
a problem with the doors

### ISSUE THREAD

**Issue by PlayerMatu** [Regalis11/Barotrauma#1013]
so basically when i started playing barotrauma the doors were fine as i remembered but like a week or a month later they started being super annoying when i closed the doors and went out they closed and then pulled me back some times its like i open a hatch or a door they close really fast and sometimes when i try to open them they dot he sound a slight bit of it moves and it closed to basically it doesn't open at all
and when it does open and someone closes it and i get out it keeps pulling me back and such until i stand still then i get teleported back idk if you are trying to fix it or no but please do its getting on my nerves
![untitled](https://user-images.githubusercontent.com/47240572/52112235-92743e00-260e-11e9-83ab-bf1de10723e0.png)

**Comment by v5844** [comment]
I don't think this necessarily a game issue, just a poor connection to the server
