### ISSUE TITLE
Artifact Transport Case - Can be placed in a character’s inventory

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10138]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The `storage container` can be carried only in the hand, but the `Artifact Transport Case` can be placed in the character’s inventory.
The suitcase should not fit in the character’s pocket!

### Reproduction steps

https://user-images.githubusercontent.com/93348499/197345506-e61ae9e6-35cf-40a1-a1bf-397d1d3cb85f.mp4

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug. The transport case is specifically meant for allowing you to put artifacts in the inventory, so you don't have to carry it in your hand and slowly swim back to the sub without being able to use an underwater scooter.

**Comment by MaaiG** [comment]
> This is not a bug. The transport case is specifically meant for allowing you to put artifacts in the inventory

Funny, I can not put in my pocket the usual suitcase, but the case for the artifact I can! ))
21st century, but the games continue to be absurd )).

> so you don't have to carry it in your hand and slowly swim back to the sub without being able to use an underwater scooter.

Perhaps if you are better prepared for the expedition then you will have no problems with transportation. If you have an artifact but you have nothing to carry it on, that’s your problem. Either you drag him slowly on your own, or you find a way to drive him.

I don’t think life should be made much simpler to facilitate gameplay for lazy player.
If the artifacts were small, the container for them could be a small box. Otherwise, it could be a special backpack!
But if you only have the case - then carry it in your hand! Even if it is inconvenient!
Otherwise - equip with a special backpack and swim wherever you want!

Honestly, I never liked games in which the character pulled out of the pants: sword, bazooka or shotgun. ))

It seems that until now the only normal game is Bloodrayne from Terminal Reality. There the heroine always carried a weapon on her body. Rifle and bazooka behind. Pistols and grenades on the belt, machine guns on the shoulder or on the hip. And it was cool, even visually!
