### ISSUE TITLE
game crashed once I open proccessing table

### ISSUE THREAD

**Issue by killyang123** [Regalis11/Barotrauma#10132]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/9840833/crashreport.8.log)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It seems something went wrong with the crash report attachment: there's unfortunately not enough info here to address the issue. Although, I suspect this might be the same issue as https://github.com/Regalis11/Barotrauma/issues/10134
