### ISSUE TITLE
Blood pack recipe only makes 1 item

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10141]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The xml of the blood pack recipe indicates that it should create two blood pack items, however this is not the case in-game.
(Recipe for blood pack is line 400 of medical.xml - `<RequiredSkill identifier="medical" level="31" amount="2" />`)

This makes crafting blood packs extremely unviable. Even before the recipe changes, blood packs were an expensive and unnecessary resource sink. As it is, blood packs heal far too much, but is still not worth the cost considering that Saline is already extremely good at healing almost any bloodloss anyway.

### Reproduction steps

1. Open up a medical fabricator
2. Observe that the bloodpack recipe only produces a single item

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/865ff8c3db204045d53a89432e6bce61457a1250

**Comment by Lithosagym** [comment]
Tested, fabricating a blood pack now properly gives 2 of them as the outpost. Issue is fixed.
