### ISSUE TITLE
Arrow buttons do not highlight a piece of text when holding Shift

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10144]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Configuring Objects in the Editor:
Now I can no longer select a part of the text when I hold down the `Shift` key and move the cursor with the `arrow` buttons. It worked earlier...

The `Shift` key does not seem to work in conjunction with other keys...

### Reproduction steps

https://user-images.githubusercontent.com/93348499/198093350-d3682bde-d1dc-422b-a323-772a2aee2093.mp4

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. More of a feature request than a bug report. Closing.
