### ISSUE TITLE
constructor consumes uranium ore and full fuel rod to make one full fuel rod

### ISSUE THREAD

**Issue by allan-gilber** [Regalis11/Barotrauma#10143]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you have in your hands an full fuel rod and empty fuel rod, the game will aways use the full fuel rod first and waste a uranium making another fuel rod.

### Reproduction steps

1) Have full fuel rod and empty fueld rod on your hands. Also need uranium
2) Open constructor and try to recicle the fuel rod.
3) The game will take one full fuel rod and one uranium from your inventory and will return a full fuel rod (wasting the uranium in the process)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/regalis11/barotrauma/issues/10143#event-7652590543

**Comment by mygamingaccount** [comment]
It's also possible to recycle a 100% full Welding Fuel tank
