### ISSUE TITLE
SpawnAction spawnlocation does not work as intended

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#10158]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Was testing event spawning in another branch (though this is in release/dev) and found the code effectively ignores submarine types if you specify it (Such as beacon stations).

This has an effect of beacon encounters without tags / other limitations spawning in wreck encounters and vice versa.

The problem is in Lines 262 to 267 of SpawnAction.cs shared. It uses Item.ItemList.FindAll by submarine which does not find any spawnpoints (as these are not items but MapEntity's I believe) thus defaulting on any spawnpoint tag from any submarine.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/484b98a2b63622818e2a66ac1bb055fedce02b76

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
