### ISSUE TITLE
Cafeteria Chair can't be sit in

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10151]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

cafeteria chair can't be sit in - no controller and non-interactable

### Reproduction steps

1. place cafeteria chair in sub editor
2. try to sit in chair
3. ate without chair, morale -3

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
additionally, benches, armchair, and metal chair 
![image](https://user-images.githubusercontent.com/5103517/197863606-da28bf53-98d4-43fd-90eb-db1507ab5686.png)

**Comment by iceball3** [comment]
The screen-facing chairs may never have been intended for sitting, with the main reason likely being that there is no screen-facing perspective for player sprites.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e176d08351da8d12043ea5020c9227d120dd502b

**Comment by Lithosagym** [comment]
Tested, cafeteria chairs are interactable and can be sat in. Issue is fixed.
