### ISSUE TITLE
[Unstable] Talent issues v0.20.0.0

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10169]
Item stuff
- [x] Ceremonial Sword can't be crafted
- [x] ~Dirty bomb can't be crafted~ (we can make it a separatist item, there's no designed talent for having it unlocked)
- [x] Handcannon can't be crafted
- [x] Gunsmith description doesnt have Revolver bullets
- [x] Clown Crate sprite is too big for crate shelf/ULD
- [x] Exosuit drains ALL contained batteries/O2 (it should not be able to contain them anyway)
- [x] ~Arc emitter is using RFA holstered texture~

- [x] Defense bot can take psychosis/nausea/organ damage

Talent stuff
- [x] Non-Threatening doesnt make enemies ignore you?
- [x] Gun Runner makes you run so fast you take damage when hitting doors/walls
- [x] Bootcamp also unlocks SMG magazine (Munitions Expertise)
- [x] Peer Learning description says 30xp instead of 30%
- [x] Pyromaniac also unlocks Cargo Scooter (Sample Collection)
- [x] Berserker/Foolhardy always active even above 50% health?
- [x] Unstoppable Curiosity and PHD in Nuclear Physics (both crowbar talents) bonus damage doesn't stack
- [ ] ~Apprenticeship icon is always "whited" out even if you don't have the experience~
- [x] Camaraderie description is broken
- [x] Family doesn't give a level to the crew
- [x] Disloyal Scum allows crafting Masterworks with very low skill (the talent is very overpowered regardless bug or not)

- [ ] ~Egghead and Prodigy are the same talent~
- [ ] ~Health Insurance and Protect and Serve are the same talent (protect being worse)~

### Version

v0.20.0.0

**Comment by ubertpendragon** [comment]
- [ ] Multifunctional doesn't give wrench bonus damage due to typo
![image](https://user-images.githubusercontent.com/73229309/198836434-3c3ec17e-f142-41b5-b3e4-b3e74da15e7a.png)

- [ ] Iamthatguy doubles blunt damage, unspecified (if you fix the wrench talent, heavy wrench will be very OP)
![image](https://user-images.githubusercontent.com/73229309/198836518-1b668bf6-1f49-412c-b4d8-ae95940eef8f.png)


- [ ] Aggressive Engineering has the wrong item tag and doesn't boost screwdrivers. Should use `electricalrepairtool`
![image](https://user-images.githubusercontent.com/73229309/198836508-86f13431-d8e3-4582-8a86-d6587e3d3f81.png)

**Comment by JeroonBosch** [comment]
Fixed the things that I could fix, passing on the torch

**Comment by NamAnhLe** [comment]
Clown crate sprite issue fixed in b00bf3f

**Comment by itchyOwl** [comment]
Fixed the defense bot in Regalis11/Barotrauma-development@9007327 (dev).

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
