### ISSUE TITLE
Defense bot appears to aim at a wrong direction in mp

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#10162]
Caused by the fact that the turret (limb) rotation is not synced, so the turret appears to be pointing to a wrong direction. But this doesn't prevent the attacks from actually hitting the target. Nevertheless, needs fixing.

**Comment by Regalis11** [comment]
I think we could maybe use the SetAttackTarget events for this, without having to worry about syncing the state of the limbs? The clients should already know which entity the bot is targeting, so it could be all we'd need to do is make the clients run the aiming logic too?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/152c1b8b83dc048be454cfae9308a31cbd1be195

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
