### ISSUE TITLE
Emergency response gives permanent 40% movement speed

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10172]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Getting emergency response increases your speed by 40% without needing anyone downed.
Probably a WIP talent since its early but good to report anyway.

### Reproduction steps

Get the talent without anyone downed and you will get the buff

### Bug prevalence

Happens every time I play

### Version

0.20.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd5031d0b14c428b4cf3a7b1bd6f6956ddee287b

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b

It seems if any character dies, you gain a permanent 40% speed increase for that round (Or perhaps as long as the body exists).  reviving removes the effect and is definitely treating dead characters as unconscious for this talent.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bfd048816fed39fd6193e04cdd815ca9b29cc2f3
