### ISSUE TITLE
Arc Emitter uses wrong sprite when worn on back, and cannot be stored in storage

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10176]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Engineer's arc emitter has the Rapid Fissile Accelerator sprite when worn on the back.
It also cannot be stored in any containers.

### Reproduction steps

Wear the emitter on your back
Try to store it anywhere

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.20.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a0a22255b6be3bdd9cbaaa75d0a5c3e52d2a2ce9

**Comment by Lithosagym** [comment]
Tested (in faction testing v100.1.0.0), Arc Emitter has its own sprite when worn on the back and can be placed in containers. Issue fixed.
