### ISSUE TITLE
Status monitor data flickering when using wired water/oxygen detectors

### ISSUE THREAD

**Issue by Herbalicious** [Regalis11/Barotrauma#10178]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using wired data inputs for the status monitor, the data flickers and reads `Air quality data not available` (or Water level, respectively) for a single frame every second before returning to the correct value. This happens regardless of the data path (if it's routed directly, or through a relay or junction box.)

See: https://youtu.be/XTx37BTIhFQ

### Reproduction steps

1. Create a new submarine.
2. Place a status monitor, and tick both `Require (water/oxygen) detectors` options.
3. Place a water detector and/or an oxygen detector.
4. Wire the status monitor to the water/oxygen detectors (and power).
5. Test the submarine, and look at the status monitor.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Herbalicious** [comment]
This seems to be specific to certain subs, somehow? I loaded up a different project that is (as far as I can tell) wired the exact same but does not have the issue, while a newly created sub does.

I uploaded the test sub which displays the issue for me to google drive, in case it doesn't reproduce easily.
[Google Drive](https://drive.google.com/drive/folders/1hWvGrPGcEQbLO_LmZwWyIgQq1CSS-MzP?usp=sharing)

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2aa75ea8a0802cf2b721be7d191336ed6088386d (commit in our private repo).

It seems the reason why this only happened in some subs was that the update order of the devices affected the issue:
> Happened because we reset the data every second to make sure the values disappear if the detectors stop working, but if the detector didn't update again before the monitor, you'd see "data not available" for one frame.
