### ISSUE TITLE
Using snap to grid on doors dislocates their gap

### ISSUE THREAD

**Issue by Laihela** [Regalis11/Barotrauma#10182]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using snap to grid on doors in the submarine editor, the door gets snapped but the gap stays in place. This causes them to become misaligned. This offset accumulates over consecutive 'snaps'.
![image](https://user-images.githubusercontent.com/31377771/198689531-fb1fed13-42b5-4a01-a525-b3fc0ded7063.png)

### Reproduction steps

1. Enter sub editor.
2. Enable gaps in the visibility tab.
3. Place any door.
4. Move door slightly.
5. Press "snap to grid" while door is selected.
6. Repeat steps 3 and 4 to increase the misaligment.

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ff4ce5e6b95f37124959fbf9423f50bbaff522e9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
