### ISSUE TITLE
Mission XP gain talent issues

### ISSUE THREAD

**Issue by Petethegoat** [Regalis11/Barotrauma#10183]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

It seems to happen with any talent that gives extra XP for missions

Completed mission in passage (not to an outpost) to kill hammerheads, this happened when transitioning to the next area
![image](https://user-images.githubusercontent.com/734762/198680368-6a127f3e-30b9-4bb6-baa8-a85928620a48.png)

Seems to also happen with the engi talent for beacon mission XP.
![image](https://user-images.githubusercontent.com/734762/198684903-298f862c-530d-421d-a9f8-4ac51fe53ca6.png)

Happened a few other times, seems 100% consistent.
Didn't grab logs, sorry. Mods active aren't doing anything to talents, binary built from dev branch.

### Reproduction steps

Start campaign
Unlock mission XP talents (bounty hunter)
Complete mission of that type and finish the level
Error

### Bug prevalence

Happens every time I play

### Version

Other

### -

Unstable V0.20.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a2766cc76d6a2fc0ae60835f34dc1d81ef683c7

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/f9ace46c636157ec9d37bcde5084063bbd176e1f, no issues found, closing.
