### ISSUE TITLE
Editor - dragging objects - parasitic ladder texture under cursor

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10186]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When moving a `ladder` or a group of objects including a `ladder`, a parasitic texture appears under the mouse cursor.
![Image 001_12-21](https://user-images.githubusercontent.com/93348499/198824373-12d0df49-719a-4809-826b-db0242bf56de.png)

### Reproduction steps

https://user-images.githubusercontent.com/93348499/198824469-9f3fadb9-4c53-4f62-a6e2-e9a9d4f1453d.mp4

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
