### ISSUE TITLE
Security's perk "Gun Runner"

### ISSUE THREAD

**Issue by oktopus34** [Regalis11/Barotrauma#10188]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Perk "Gun Runner" adds 50% Movement speed when carrying ammo box, but instead it increases standard movement speed, after picking the perk I can run faster than Crawler swims

### Reproduction steps

1. Host server
2. Launch any gamemode (sandbox, missions, campaign)
3. Pick "Gun Runner" perk
4. Done, im running like a bullet

### Bug prevalence

Happens every now and then

### Version

0.20.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No errors.
```

**Comment by 3e849f2e5c** [comment]
The issue is caused by the same bug as #10172 so closing this as a duplicate
