### ISSUE TITLE
[dev]"Humanhusk" lacks head sprite in character editor.

### ISSUE THREAD

**Issue by Deelite34** [Regalis11/Barotrauma#1018]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Humanhusk" lacks head sprite in character editor.
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Enter character editor, select humanhusk, bug will pop up in console, and character will lack head, and have spine/husk visible.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows 10 closed beta
**Additional information**
Screenshot of error: https://i.postimg.cc/Jn7jQpwP/humahusk.png

**Comment by itchyOwl** [comment]
Fixed in the husk-refactor branch.
