### ISSUE TITLE
Unintended Result From Engineer's Buzzin' Talent

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#10184]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The "Buzzin'" talent for the Engineer appears to set the max reactor output by 10% rather than boost the max reactor output by 10%. This usually leads to the submarine to be permanently crippled due to the reactor being no longer able to reach the load threshold.

### Reproduction steps

1. `quickstart [submarine]` from menu or select a submarine through Submarine Editor
2. `givetalent Buzzin'` to Engineer or other crewmember
3. Manually operate the nuclear reactor for a couple of minutes, 5 minutes maximum
4. Notice the Turbine Output make a sharp increase until it goes over the right side and puts itself all the way to the right. The reactor's output has now been reduced to about 10% and no amount of fission rate increase or automatic control can increase it.
![image](https://user-images.githubusercontent.com/39580303/198821064-e46ee9e0-c3be-4a28-9055-80b75ebc93a3.png)

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.20.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1cc87bf668c91baed9f064bf422da5f785b451bc

**Comment by Lithosagym** [comment]
Tested, the Buzzin' talent properly increases reactor max output rather than decreasing it. I also now know how to embed an image. Issues are fixed.
