### ISSUE TITLE
Hats clipping thru Exosuit

### ISSUE THREAD

**Issue by Well-to-doGaming** [Regalis11/Barotrauma#10189]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Equiped the new "Exosuit" and saw that my hat was clipping thru it.
![20221030161314_2](https://user-images.githubusercontent.com/59537574/198886362-c0107eac-afb9-4819-9652-698ee6299d00.jpg)

### Reproduction steps

1. Equip the "Exosuit" with a hat also equiped.

### Bug prevalence

Happens every time I play

### Version

0.20.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/A
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a623161

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
