### ISSUE TITLE
Text Display "lightcomponent" setting cannot be turned off

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#10181]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After unchecking **IS_ON** in the **TEXT DISPLAY** settings, and going into **TEST** mode, the **TEXT DISPLAY** still has light emanating from it.
After exiting **TEST** mode, the **IS_ON** setting is checked.

Unchecking **IS_ON** in the **TEXT DISPLAY** settings should disable any light emanating from the **TEXT DISPLAY**, and should remain unchecked after exiting **TEST** mode.

### Reproduction steps

1) Load a Sub file
2) Place/Select a **TEXT DISPLAY** and uncheck **IS_ON** in its settings
3) Load into **TEST** mode
_You will see the **TEXT DISPLAY** still lit_
4) Exit **TEST** mode and select the **TEXT DISPLAY**
_You will see the **IS_ON** checked_

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.20.0.0 [Unstable]

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/196744820b705764d3e7e0dffb9cb4bc534495c0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
