### ISSUE TITLE
Outpost generate isolated rooms

### ISSUE THREAD

**Issue by Instant2116** [Regalis11/Barotrauma#10187]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wrong outpost generation. some rooms and tunnels to the rooms are separated from the outpost and can't be reach without breaking walls. Map seed vxh4rrYG
![20221024062703_1](https://user-images.githubusercontent.com/46164525/198852394-14247dac-d444-4a28-afea-3d58b981d3ef.jpg)

### Reproduction steps

1. load save file (can't attach this to report, will send where ever you want to or use it from [google drive](https://drive.google.com/file/d/1GrBmLm5XhvF_XCHfy0-mPIcjOPxvNk0Y/view?usp=share_link))
2. launch single player campaign from save file 
3. observe outpost generation/ bot behavior (tries to reach isolated rooms)/swim around from outside.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fb993f82ad6a26b28b70254b3d2b4ea9b4747181

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
