### ISSUE TITLE
Radiation Sickness doesn't naturally decrease when its strength is lower than 25

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10197]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Just like Drunkness in previous version.
Radiation Sickness does not decrease naturally when lower than 25.

### Reproduction steps

1. start a campaign.
2. use "giveaffliction radiationsickness 27" on any crewmate.
3. go to the outpost doctor and watch the sick crewmate's status change.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/95d42acb0ba5531ee544a2f2ae553b31980a1b7e
