### ISSUE TITLE
Outpost events reset when saving and quitting

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#10192]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you save and exit at an outpost, the things you did are saved, but the outpost is reset. For example, you can get missions from the guy who gives missions then save and exit and get more missions. I have also encountered random events by doing this.

Example of what you can get from this:
![image](https://user-images.githubusercontent.com/42877449/198898500-87ffc8e6-cef5-44db-9b4b-2e9c984a5c74.png)

### Reproduction steps

1. Start a singleplayer campaign
2. Get to an outpost
3. Get all the missions from the mission guy
4. Save and exit
5. Reload the save
6. You still have the missions available on your map, but the mission guy can give more missions.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! We just pushed a related fix in the latest unstable version (ticket in our private repository https://github.com/Regalis11/Barotrauma-development/issues/3689), and I think that should take care of this as well. We'll need to test and verify it internally before we close this ticket though.

**Comment by Rokvach** [comment]
Tested, each time I reload a save there's always new missions and a event in outpost. So looks like this issue hasn't been fixed.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@17426af

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.0 commit https://github.com/Regalis11/Barotrauma-development/commit/eec9386090f5fd1b055c64aa74beba14b41e1781

Creating a fresh campaign then doing a save and quit to reload the save I was able to continually pick up new missions, until repeatedly failing to unlock as I only had one node (but there seemed to be no limitations here) in single player.

On a server, I was able to keep saving, quitting and loading to get more jobs than I should have, but it stopped after I had 6 missions total (Unlike single player) - but this is still more than you are normally given for one outpost (which was around 3 or 4 at most).

![image](https://user-images.githubusercontent.com/29177976/221607275-41e50582-112c-4657-a604-856873471774.png)

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.1 commit https://github.com/Regalis11/Barotrauma-development/commit/eec9386090f5fd1b055c64aa74beba14b41e1781, no issues found, closing.

Notes: the fixes for this were not included in 1.0, and are part of the 1.1 patch.

**Comment by RooneyRoll** [comment]
Is this fixed in single player (version 1.0.13.2) ?

**Comment by Regalis11** [comment]
@RooneyRoll should be, the fix was added in version 1.0.13.0

**Comment by RooneyRoll** [comment]
Fantastic, Thank you!
