### ISSUE TITLE
Bots repairing wrecks. (wait really?)

### ISSUE THREAD

**Issue by TMWReborn** [Regalis11/Barotrauma#10196]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

i found a wreck in single player compaign i had both mechanik with scrap skill and engeneer with reactor wreck skill, so i send both of them while they still had orders to repair, when i was controlling one of them i saw that the other one started repairing everything (including doors(including hulls)) in the wreck, im not sure if that intentional.

### Reproduction steps

- start any campagin with bots
- find or spawn a wreck
- give them order to repair
- move them to the wreck
- observe how the bots try to bring wreck back to life 

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional. The bots normally won't try to repair wrecks (or any other subs/stations not belonging to your crew), but will do so if ordered to.
