### ISSUE TITLE
Quest Items not counted if in Toolbelt

### ISSUE THREAD

**Issue by gkcopperdrag** [Regalis11/Barotrauma#10193]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Encountered an opiate overdose on Gope as medic. I had Naloxone in a toolbelt on me, and the quest told me that I didn't have any on me, so there was nothing I could do.

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e6e44e85d044b677531108575d8651b0d73718f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
