### ISSUE TITLE
Exception: readStream was disconnected unexpectedly & Exception: Pipe is broken

### ISSUE THREAD

**Issue by rbjaxter** [Regalis11/Barotrauma#10194]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Approximately 90 minutes in to a multiplayer (4 players total) and after leaving a ruin, a crash to desktop occurred on my end with no apparent error messages (near instant crash).

Leading up to the crash, I was streaming my POV through Discord while simultaneously watching another player's POV. The crash seemed to occur a few seconds after an alt-tab out of the game and then back into the game (probably within 10 seconds of alt-tabbing back into the game).

This is the first time this has happened. The server was hosted on my end, but not through the dedicated multiplayer client. It was hosted through the in-game multiplayer feature.

It produced two server crash logs at the same time, which I've attached below.

[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/9897028/servercrashreport.log)
[servercrashreport (2).log](https://github.com/Regalis11/Barotrauma/files/9897027/servercrashreport.2.log)

### Bug prevalence

~Just once~ Twice now, same error logs created

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void UpdateRead()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 160
   at System.Threading.Thread.StartCallback()

Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|26_0(WriteStatus writeStatus, <>c__DisplayClass26_0& ) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 255
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 260
   at System.Threading.Thread.StartCallback()
```

Edit: it has now crashed a second time, 30-60 minutes into the same set of missions, albeit in a different location with no discernible correlation between the two crashes

**Comment by Regalis11** [comment]
Potentially related to https://github.com/regalis11/barotrauma/issues/7985
