### ISSUE TITLE
Medicine is missing the label

### ISSUE THREAD

**Issue by Well-to-doGaming** [Regalis11/Barotrauma#10191]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![onerr](https://user-images.githubusercontent.com/59537574/198887455-dd861e89-8184-47e4-ad1f-279314b69f36.PNG)
![twoerr](https://user-images.githubusercontent.com/59537574/198887456-4bd2587b-7bf9-47fd-aeee-86143d570bd3.PNG)

### Bug prevalence

Happens every time I play

### Version

0.20.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Well-to-doGaming** [comment]
It seems that this issue is displayed with every medical item.

**Comment by Regalis11** [comment]
This isn't really a bug: the labels are omitted from the in-game sprite so we can reuse some of the sprites for multiple items, and because the labels would be unreadable in such a small sprite anyway.
