### ISSUE TITLE
SMG Magazine has 21 bullets whilst Depleted Fuel SMG Magazine has 20 bullets

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10205]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

RELATED TO ISSUE #8423 (https://github.com/Regalis11/Barotrauma/issues/8423)

The SMG Magazine's ammo count was adjusted to fix burst fire issues highlighted in issue #8423. However, the Depleted Fuel SMG Magazine was not adjusted in the same way.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67ba10959bd02ff385cdd5e80ea465c311c46822

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
