### ISSUE TITLE
Mb BUG

### ISSUE THREAD

**Issue by vovapidoras** [Regalis11/Barotrauma#10207]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I downloaded the source code for compiling under Linux, compiled it, but there were no textures, pictures, and other content. I went to pirate sites, installed a version for windows, took missing files from there and threw everything into the game folder, everything was fixed. I suppose that this is a bug please fix it

### Reproduction steps

4. Observe the game crash

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Please read the contribution guideline which includes instructions on how to compile the game. The game assets like textures, sounds and such are not included in the repository, you need to get them from your copy of the game (= preferably the copy you've purchased from Steam, not one you've downloaded illegally).
