### ISSUE TITLE
Strings localization of the RussianVanillaEditorTexts.xml is not applied in the editor

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#10202]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There is no translation in the game editor. The required translation strings exist in the `RussianVanillaEditorTexts.xml` file, but you must place these strings in the `RussianVanilla.xml` file to apply the game changes.
For example:
![Image 001_19-02 (1)](https://user-images.githubusercontent.com/93348499/199059882-73da1f73-bcb3-4c81-a80f-3f95cadf7de3.png)
Required strings are in the file `RussianVanillaEditorTexts.xml`.
String: `<savesubbutton>Сохранить</savesubbutton>`.

However, for localization you need to duplicate this string in to the file `RussianVanilla.xml`.
Result:
![Image 001_19-28 (1)](https://user-images.githubusercontent.com/93348499/199060024-62dfe8a0-5969-4ad7-bcc4-6fe67d3778c3.png)

### Reproduction steps

Try to translate the strings in the file RussianVanillaEditorTexts.xml as shown above.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
There is no file called RussianVanillaEditorTexts.xml in the game, so I assume this is some kind of a mod? If it's one you're making yourself, have you added it to the content package?

**Comment by MaaiG** [comment]
Oh, I see. Often I supplemented and corrected localization. When I localizing the "Character Editor" and other missing localization strings, seems like I did it myself once, created the file "RussianVanillaEditorTexts.xml", similar to its English version and I forgot about it. In time, all is forgotten... I'm sorry. Сan be closed.
