### ISSUE TITLE
Expanded research doesn't work

### ISSUE THREAD

**Issue by Xayrlen** [Regalis11/Barotrauma#10208]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Expanded Research: "Whenever you or another allied crewmember deconstructs depleted fuel, they gain 200 experience."

This perk never gives experience. I tried this immediately after activating it, after completing a mission/multiple missions, but deconstructing fuel rods simply won't give experience to a crewmember nor to the electrician himself.

### Reproduction steps

1. Start a single player game;
2. Uinlock "Expanded Research" perk from "Weapons Engineer" tree;
3. Put fully depleted fuel rod in a deconstructor and process it either as an electrician or someone else.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This talent will be removed in the upcoming faction overhaul, so I don't think we'll fix this
