### ISSUE TITLE
Adding Turret/ItemLabel before LightComponent and write light's properties' changes in server will cause desync.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10203]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In the executing of `Item.WritePropertyChange` will gets all Editable properties of the specific item, and finds its related property index.
but i noticed in some cases that actual property which propertyIndex indicated is different in server and client.
Taking ItemLabel as an example, its property list looks like this:
|Editable Property Sequence|Server|Client|
|-|-|-|
1|TextColor|IgnoreLocalization|
2|TextScale|TextColor|
3||TextScale|

Assume I want the server to write TextScale to the client, but the client will actually sets its value to IgnoreLocalization

This problem doesn't occur in Vanilla, because Vanilla only provides the ability for the client to write `Item.WritePropertyChange` to the server, and the properties are limited to InGameEditable, and coincidentally, the client and server have the same sequence of InGameEditable-properties.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This happens because the property in question is only implemented for clients, and doesn't exist server-side. 

I wouldn't consider this a bug, as non-ingame-editable properties cannot be edited in-game by clients in the vanilla game. If you want to change that, I think you need to come up with some other way to sync them than using the index of the property: perhaps the name? Or ensure that all Editable properties exist both client-side and server-side.

**Comment by zhu-rengong** [comment]
The server always synchronizes some non-ingame-editable properties of the headset to the clients, if some modder override headset such as adding an ItemLabel for it, this will happens, and there're other ways which also can causes this. This could be a potential bug in the future, but as for now it's not a bug. Maybe it's better to look property up by name rather then index? But at the moment I don't have any ways to get all players having modding client installed, so I'd love to see there's a way to deal with this in the future.
