### ISSUE TITLE
[Faction test branch] Getting into an outpost after tutorial throws an error

### ISSUE THREAD

**Issue by JupeOwl** [Regalis11/Barotrauma#10218]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I did tutorial and went to an outpost and got this error
![kuva](https://user-images.githubusercontent.com/55913455/199799052-e79d392e-c47f-44cb-9e69-34da9db43d76.png)

### Reproduction steps

1. Start new campaign as usual
2. Take a mission
3. Start travel
4. Get to next outpost

### Bug prevalence

Happens regularly

### Version

Other

### -

faction testing

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error in event set "secondoutpostevents" (Vanilla) - could not find an event prefab with the identifier "missionevent_escort1".
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d4330aaf2065791bc186a77cd64125b6f314e6eb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
