### ISSUE TITLE
[Factions] "Your reputation" talent causing crash

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10219]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you try to reach a linea after completing a mission with "Your reputation", the game crashes

[crashreport (17).log](https://github.com/Regalis11/Barotrauma/files/9932366/crashreport.17.log)

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8163a63cfa02d5d999cc115f8d5604ddc629412f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
