### ISSUE TITLE
ballast tanks on custom subs not filling up with the assigned neutral ballast level on level load

### ISSUE THREAD

**Issue by Padex98** [Regalis11/Barotrauma#10214]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The vanilla subs always start with their ballasts filled around 50% with water. With custom subs ballast tanks however, no matter their size, and no matter the number of the neutral ballast level, are always filled up to around 1/6th, resulting in the sub floating extremely fast before it can balance itself out once the power gets turned on.

### Reproduction steps

-make a custom sub with the ballasts set up correctly (tags, etc to)
-start the test and watch the ballast water level and/or the speed at which he sub is floating

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I think the issue here was that the game only considered hulls with a pump tagged as "ballast" as ballast tanks when neutralizing the ballast level. I changed the logic to also include hulls that include "ballast" in the name https://github.com/Regalis11/Barotrauma-development/commit/d747dd608646340d5474efa2d5ace023097fbfe8

**Comment by Padex98** [comment]
After talking with other people, it appears that this issue happens when there is a shuttle on the sub, and the ballasts wrongly utilize the Neutral ballast level of the shuttle on level load!

**Comment by Padex98** [comment]
No matter isf the navigation terminal of the shuttle is in any way connected to the pumps or not

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/aa8388e4f9e8067110ef6827b3b1760f5a2f3f97

It now correctly fills rooms on submarines that contain ballast within the name (even if no pumps in the room have the tag ballast). Though I'm not sure on the mentioned issues of linked submarines. they did all share roughly the same water level (shuttles included) and the submarine only slowly raised before power came on (not quickly).

**Comment by Rokvach** [comment]
Closing.
