### ISSUE TITLE
Herja has a very low device repair threshold

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#10210]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Herja has a very low repair threshold of 50 for most of its electrical and mechanical devices
![Screenshot 2022-11-02 at 18-15-06 unknown png (PNG-kuva 1565 × 679 kuvapistettä) — Pienennetty (98 _ alkuperäisestä)](https://user-images.githubusercontent.com/86321358/199546536-814a458d-e806-4823-a1dc-ce683851b60c.png)
![Screenshot 2022-11-02 at 18-15-31 unknown png (PNG-kuva 1511 × 753 kuvapistettä) — Pienennetty (98 _ alkuperäisestä)](https://user-images.githubusercontent.com/86321358/199546561-5fbde38f-c4c9-4c6f-b44e-75eb0985919b.png)
The low repair threshold makes you unable to fix junction boxes despite them being visibly broken or engines making the sub slower

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6518db9fe22784a4bf5d32ae51dd870f8746a2b0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
