### ISSUE TITLE
[Unstable] Talent issues v0.20.2.0

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10211]
Continued from #10169

- [x] Exosuit can breathe if oxygen bottle is NOT in the oxygen slot _(the concept of exosuit carrying dozens of spare oxygen bottles/batteries in its own inventory is broken regardless)_
- [x] Exosuit can function without batteries
- [x] Exosuit can use the diving scooter `PropulsionSpeedMultiplier="0.5"` _(bypassing the need for batteries)_
- [x] Aggressive Engineering (screwdriver damage talent) also increases screwdriver stun, meaning you can stunlock with regular/hardened screwdrivers
- [x] The Waiting List (grayshirt talent) says vitality bar decreases 75% slower when unconscious, but only affects Low O2 _(which makes it a very weak talent)._
- [x] Journeyman talent disappeared from Apprentice tree
- [x] Makeshift Armor/Helmet can be bought at outposts 
- [x] Melodic Respite (engineer) description not done
- [x] Skedaddle doesn't give passive 10% move speed
- [x] Warlord doesn't seem to give a damage bonus (either nearbycharactercount or weapontype="handheldranged" doesnt work)

more to come

**Comment by Regalis11** [comment]
> Exosuit can use the diving scooter PropulsionSpeedMultiplier="0.5" (bypassing the need for batteries)

This is not really a bug: I don't see why the scooter wouldn't work when wearing the suit. I did reduce the movement speed though.
