### ISSUE TITLE
[Unstable] Shotguns from older versions cannot shoot

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10212]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Riot Shotgun says "Out of Ammo" when loaded and trying to shoot.

~~Forgot to add the "Use" line in xml under Rangedweapon:~~
```
      <StatusEffect type="OnUse" target="Contained">
        <Use />
      </StatusEffect>
```

### Version

0.20.2.0 (Unstable)

**Comment by Regalis11** [comment]
Steps to repro? I couldn't reproduce this at my end.

I also don't see why we should have a `<Use />` there, what does using a shotgun shell do?

**Comment by itchyOwl** [comment]
Couldn't repro either

**Comment by ubertpendragon** [comment]
Ok so apparently this affects shotguns placed before the update

Shotguns added via sub editor or console work just fine

**Comment by itchyOwl** [comment]
Tested on an old save and still can't repro. Can you give the save file?
