### ISSUE TITLE
Talent reset Button does nothing

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10223]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pressing the reset button doesnt do anything anymore, however talents can still be unselected by just clicking on the icon again. This all goes for non-spent points before pressing apply.
![image](https://user-images.githubusercontent.com/104232152/199828598-89a61e4d-5d00-4d6a-a965-74fe969ef319.png)

### Reproduction steps

1.Put a talent point into a talent before pressing apply
2.Try using reset
(3.Find new worth in its use as a stress relief button)

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/865a814d4e6981295d1ae388129bec03dbe76562
