### ISSUE TITLE
Crawler Swarm missions possibly broken (excessive reward)

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10220]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems like when doing a crawler swarm misson, the game has given me a bit more than the regular amount of cash in payout, doubt thats intentional 
![image](https://user-images.githubusercontent.com/104232152/199824819-bb796468-f98a-475a-8093-6e46cf1e3f4f.png)

### Reproduction steps

1.Start Campaign
2.Play up until Crawler Swarm Mission
3.Kill Broodmother and crawlers
4.Finish mission and profit a little too much

### Bug prevalence

Just once

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately couldn't find a way to reproduce this. Did you have some kind of talents unlocked? I'm wondering if some of those could be modifying the reward. And did this happen in single player or multiplayer?

**Comment by Regalis11** [comment]
I think this may actually have been caused by a cargo mission and the mailman talent. Steps to repro:
1. `unlocktalent mailman`
2. Complete a cargo mission
3. Notice the reward gets multiplied by 150 instead of getting a flat 150 mk bonus

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fca90b09ba909a1f012f7d41a028105a4c8e24fd https://github.com/Regalis11/Barotrauma-development/commit/1604c7e6cea1e44253202ba209afa5cdf50e7a71

**Comment by Rehexr** [comment]
Thanks for figuring it out, hard to nail some things down specifically

**Comment by Rehexr** [comment]
Certainly fixed in the newest build, so im closing it
