### ISSUE TITLE
Container indicator shows how full the 1st slot is, instead of how full the container is

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#10228]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/14351070/199917577-2e9be735-c97d-4a33-b54b-9f2aa6a9d060.png)

### Reproduction steps

1. Put items inside a storage container or crate
2. Make sure the item in the 1st (bottom-left) slot is stackable
3. Notice the indicator below the inventory slot displays how full the stack is instead of the how full the whole container is

### Bug prevalence

Happens every time I play

### Version

0.20.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@327919e.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
