### ISSUE TITLE
petraptors' limbs got ripped off but wont die from it

### ISSUE THREAD

**Issue by ErenDeca** [Regalis11/Barotrauma#10229]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

petraptor got ripped by mudraptor during fight but didn't die, instead it just float around ith its' upperbody

### Bug prevalence

Just once

### Version

0.20.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This also seems to apply to normal mudraptors

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10213
