### ISSUE TITLE
Some talents cause console errors when finishing a mission

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#10224]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Completing a mission with certain talents unlocked causes the following console errors. I didn't test all of these individually, but used the `unlocktalents` command to unlock all of them, so I'm not sure if it's caused by some specific combination of talents or if all of these are bugged:
![image](https://user-images.githubusercontent.com/14351070/199835405-04f5d380-62d1-464e-add2-0a0f284689bc.png)

### Reproduction steps

1. Start a monster mission
2. `unlocktalents`
3. `killmonsters`
4. Leave the level

### Bug prevalence

Happens regularly

### Version

Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/cffb1f608eede8355453a561d9bfedc6d6f979a2

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1da71844a20facd622ab141dba9c40f46c176e9f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
