### ISSUE TITLE
Honker Blast is infinitely Spammable

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10221]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Title tells the whole story, as long as youre commited enough to getting your senses assaulted, youre free to just keep pressing the button to have it run for an infinite amount of time.

### Reproduction steps

1.Honker blast
2.Repeat step Nr.1

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
