### ISSUE TITLE
Reloading saves resets tutorial mission progress

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10222]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When reloading a save, after for example buying a fuel rod, as instructed, upon reload the rod will be bought, but the mission will again ask for you to buy one. Its possible to even sell out stock this way and get your save stuck.

### Reproduction steps

1.Buy items as requested
2.Save, Quit and reload
3.Note bought items, but reset tutorial missions

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@a2aff68
