### ISSUE TITLE
Hardened screwdrivers do not inflict bleed

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10239]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The normal screwdrivers are able to inflict bleed, but not the hardened ones?

### Reproduction steps

Smack someone with screwdriver, see the bleed
Smack someone with hardened screwdriver, see the lack of bleed

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
