### ISSUE TITLE
issue with fabricator linked to a container.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10235]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using a fabricator with a linked container, it consumes materials in the linked container instead of materials pulled from the linked container.

### Reproduction steps

1. place a fabricator in sub editor.
2. link it to a steel cabinet.
3. place 16 steels in the cabinet.
4. fabricate a storage container.
5. you will see fabricator pulls 2 steels from the cabinet. however, the 2 steels are not used. steels that remain in the cabinet are consumed.

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem to be specific to the faction branch, occurs in Unstable too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0a784c71177246a34f4e61d882a3d206cbb6622

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
