### ISSUE TITLE
[Unstable] Rifle bullets appear at the tip of the gun

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10238]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/73229309/200046411-9e19cbac-c770-4411-8904-597ff6574f1c.png)

There's also some Z-fighting with grenade

Just saw the TODO in rifle XML

### Version

0.20.3.0 (Unstable)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@d7a5e8a (dev).

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
