### ISSUE TITLE
[Unstable] HMG sends you flying FAST when not touching the ground

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10237]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

HMG has too much propulsion and sends you flying if you aim downwards

### Reproduction steps

Fall through a platform while shooting the HMG

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

**Comment by JeroonBosch** [comment]
Fixed in 0e93c3a7a55685bdb945f1c1a41a39b64746ad44

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
