### ISSUE TITLE
Captain can unlock "Politician" sub tree before unlocking primary talent tree.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10232]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the picture shows.
![captain politician](https://user-images.githubusercontent.com/99462070/199969882-5d94dfca-1c0f-455c-bd1f-7a42a1747874.png)

The reason is that in TalentTree.xml, line 52, sub tree "Politician" requires "captainprimary" while it probably should be "captain_primary".
![captain politician 2](https://user-images.githubusercontent.com/99462070/199970146-3301fbed-149d-48e6-a94e-c35975b84c8b.png)

### Reproduction steps

1.use "giveexperience" to give a captain some experience.
2.you will see the first talent on sub tree "politician" is selectable.

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Should no longer be an issue on the `feature/talent-tree-politician` branch https://github.com/Regalis11/Barotrauma-development/commit/5c5177c87c899b979249e2acc2558674cd99b863

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
