### ISSUE TITLE
Medical Fabricator items still do not require a recipe to craft, despite being talent specific

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10236]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Europabrew and Sulphuric Acid syringes both require a talent to unlock. Despite this, everyone can craft them at a medical fabricator without any talents needed. 

![image](https://user-images.githubusercontent.com/105495756/200044894-3ba64bf5-4fa2-4b99-98a9-a2a13704a488.png)
![image](https://user-images.githubusercontent.com/105495756/200044920-2212c086-250e-4507-bd24-9acdf1b2695e.png)
![image](https://user-images.githubusercontent.com/105495756/200044937-7bd25c47-7e24-49ec-a51b-eaadd5fed6e7.png)

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch, happens in the Unstable branch too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/757398a1726ad90e6ae4bcb61cb7b8207203c6ae

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
