### ISSUE TITLE
[Unstable] Makeshift armor torso is too small

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10233]
### What happened?

You can see it's poorly adjusted and the clothes underneath

![image](https://user-images.githubusercontent.com/73229309/199986774-92f26baf-b928-420c-9725-901b0e2c6371.png)

### Version

0.20.1.0 (Unstable)

**Comment by itchyOwl** [comment]
Note: torso pieces shouldn't hide the other wearables, unless there's a collar, because otherwise the character doesn't have a neck. Mind that neck is a part of the torso! So you'll have to adjust the art.

**Comment by dinhtuananhfakefish** [comment]
xml fixed in c8177075aa
sprite adjust in c35a9261d3

![image.png](https://images.zenhubusercontent.com/5c9243aad06a4e6d359ee4ac/03959038-9195-4a4f-be75-ba6b32d6d857)

**Comment by Regalis11** [comment]
The dropped sprite is still very small + the collider is too large (the item floats mid-air)
![image](https://user-images.githubusercontent.com/14351070/201339600-c6fdb734-83db-49ba-9ff8-2d17c292d91e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e075eb69394aee2879977f36b8bba522a10d7d6

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
