### ISSUE TITLE
[Factions] Coalition security NPCs don't attack during Jacov Subra rescue mission

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10234]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Jacov Subra spawns a lot of security officers on the way back, but they don't attack you
I assume they're supposed to be hostile?

![image](https://user-images.githubusercontent.com/73229309/199987510-3b667e05-45f6-4bb6-91e7-f7e52bb50090.png)

Also the outpost is full of husks in diving suits (as opposed to humanhusk without suit or in cultist clothing) which is weird considering it's a functional station and all.

### Bug prevalence

Just once

### Version

Faction test branch

**Comment by ubertpendragon** [comment]
Note that I did use cheats to get max reputation on all factions if that's a factor

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd32b2909a5909fc247f142698add3780292ff6f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
