### ISSUE TITLE
Sending a trigger_in signal to an empty turret hardpoint causes it to drop/fire a round.

### ISSUE THREAD

**Issue by KonigP86** [Regalis11/Barotrauma#10230]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sending a signal into the trigger_in of an empty turret hardpoint that is linked to an active ammo loader occasionally causes it to fire a "round" directly down.

### Reproduction steps

1. Link an empty turret hardpoint to a loaded ammo loader that is also linked to an active turret hardpoint (e.g. Coilgun)
2. Send signal to the empty hardpoints trigger_in pin. For testing purposes a lever's output can be used but it also occurs from continuous output from the trigger_out of a periscope.
3. Wait a few seconds. A round will drop out of the bottom of the hardpoint, usually into the sub's hull creating a breach.
![Hardpoint round - Copy](https://user-images.githubusercontent.com/114788696/199957806-37714c84-d920-42d5-8c78-84d2b2795962.jpg)

### Bug prevalence

Happens every time I play

### Version

0.20.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d79297a714af2893e318de4247f73c253f0bb8f5

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
