### ISSUE TITLE
Gunners trying to shoot enemies through the Alien Ruins walls

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#10246]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the sub approaching to Alien Ruins the bot gunners trying to shoot enemies through the walls inside the ruins. After a few seconds the firing ending. Also I noticed when someone spawning inside the ruins (Swarm Feeders for example), bot gunners trying to shoot them within a few seconds too.

Also when the sub approaching to the Beacon and the monster spawning inside, gunners triggering too (aiming at the beacon), but not firing

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Fixed bots firing turrets when there are indestructible structures in the way (Regalis11/Barotrauma-development@5ff79c2)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
