### ISSUE TITLE
Bots discard an item from PUCS auto injector slot when replacing oxygen tank

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#10245]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bot had a Deusizine in PUCS auto injector slot. When it was time to replace the oxygen tank it also discarded a Deusizine.

If the inventory is full bot drops out an item.

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10039
