### ISSUE TITLE
AI walks against a door in an outpost

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#10243]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I played on the faction branch
![image](https://user-images.githubusercontent.com/59519434/200089003-799db863-7403-4be3-ae2d-e2e4be5d01e5.png)

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
The issue there seems to be that the waypoint on the door is not linked to the door.

**Comment by itchyOwl** [comment]
The waypoints seem to be correct on both the faction test and dev (below).

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/6d05241b-3f38-47e7-a8de-1c5dc1436457)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/81f09294-4c1b-4c39-8b68-5a4df5f0cb10)

**Comment by Regalis11** [comment]
Seems to happen in the pre-built "campaign start outpost", fixed in https://github.com/Regalis11/Barotrauma-development/commit/ecb88ad2842ca0605ca63c62557f82495e2bb4ec

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8, no issues found, closing.
