### ISSUE TITLE
[Factions] Specific mining mission sonar tag replaced with [resourcename1]

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10242]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Selecting specific mining missions will result in the resource name being replaced with [resourcename1] on the sonar monitor.

![image](https://user-images.githubusercontent.com/105495756/200081910-2297714a-9387-4d17-9032-0facfb965378.png)
(Mission mineral is supposed to be Quartz)

### Bug prevalence

Happens regularly

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/164c8f47d055a4a9c4039c82145251cabc220ee9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
