### ISSUE TITLE
Unable to quick reload a smg.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10248]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to quick reload a smg with hotkey, the character unequips the gun and equips the magazine.

### Reproduction steps

1. have a smg equipped and a magazine on your hotslot.
2. press the hotkey to reload the gun.
3. the character equips the magazine instead of doing a reload.

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/373bea1343780117836d81b289b011b2d2362964

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
