### ISSUE TITLE
Advanced Syringe Gun is missing a proper inventory Sprite

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10251]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The advanced syringe gun is simply still using the regular syringe gun sprite, when in the inventory, but not when dropped.
![image](https://user-images.githubusercontent.com/104232152/200135779-6c21ceec-39d2-419a-b41e-4dbf4002aa3a.png)

### Reproduction steps

1.Simply note the sprite on the advanced syringe gun

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/22fc981646b01d80005c92b2e0f00c7f4abd5575

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
