### ISSUE TITLE
Outposts are not stocked with Weapons

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10258]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When checking any outpost, even military ones, no vendor sells any new weapons, aswell as shotguns or smgs. Tried looking at 3 different military outposts, and none sell them. Though this issue is inconsistent, as some people on discord havent had the same issue, yet others did. The rifle cannot be crafted either, so might be related to the items appearing in the campaign at all.

### Reproduction steps

1.Start a campaign and visit any regular/military Outpost
2.Look for new Weapons with any or all vendors.
3.Find that none of them are listed or can be bought

### Bug prevalence

Happens regularly

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The new weapons only become available when you're far enough in the campaign, for example the machine pistols and rifles are only sold past 15 difficulty and the HMG past 60 difficulty.
