### ISSUE TITLE
[faction test] Unlocking PVP sub v sub achievement in campaign

### ISSUE THREAD

**Issue by Petethegoat** [Regalis11/Barotrauma#10259]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/734762/200142295-b6e507ad-68f2-44fe-924a-65c00f2d72ab.png)
![image](https://user-images.githubusercontent.com/734762/200142298-36313abb-9b46-46e8-86df-1f687dad8643.png)

I obviously didn't have this achievement before, and I unlocked it while testing the singleplayer campaign, at mission end.

I restarted the mission several times both before and after defeating the sub, but only unlocked it when I defeated it and docked at the next station, bringing up the normal mission end screen.

My understanding from other users on the discord is that it's meant to be a PVP only achievement.

### Bug prevalence

Just once

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
> My understanding from other users on the discord is that it's meant to be a PVP only achievement.

It no longer is
