### ISSUE TITLE
Phantom Item holding?

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10256]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unsure what triggered this, but for some reason i could manage to get my character to be looking like theyre holding something, when nothing is equipped. Please note that the item in my Hand can still be used as it appears, aka i can still inject/swing the alien blood. See Image 
![image](https://user-images.githubusercontent.com/104232152/200140231-4c769d1d-f349-4692-b562-4c1d4e792bd4.png)
(Short update, ive noticed that theres some delay between equipping the item vs when it appears in my hand, might be related)

### Reproduction steps

1.Currently unaware of what caused this, though its likely related to switching between items using the hotbar

### Bug prevalence

Just once

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Incredibly annoyingly, ive had this happen multiple times, seems to be related to trying to hold multiple one handed items in one slot at the same time, yet i couldnt repro this at all testing it outside of playing. Frustrating

**Comment by Rehexr** [comment]
Didnt mean to close

**Comment by Regalis11** [comment]
No known steps to repro, closing
