### ISSUE TITLE
Machine pistol is two-handed, not one-handed.

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10250]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The new machine pistol is currently two-handed like the larger SMG, yet almost identically fires like one with worst accuracy. It seems intended that this machine pistol is meant to be used in one hand, as right now its just a worse SMG.

### Reproduction steps

Equip the machine pistol

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
