### ISSUE TITLE
Iron helmet can be found in stores

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10254]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/200136941-2c6603f8-1239-410a-9c4c-d04336f4386a.png)
Simply, the makeshift armor isnt in stores anymore, the iron helmet still is. Happened on a residential Outpost, if that helps.

### Reproduction steps

1.Check stores for iron Helmets

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
