### ISSUE TITLE
Cannot craft SMG despite having "Weaponsmith"

### ISSUE THREAD

**Issue by teh-player** [Regalis11/Barotrauma#10252]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The recipe for the SMG is never in fabricators, doesn't matter if you have the talent or not. The riot shotgun is there, though.

### Reproduction steps

1. click on a fabricator
2. search for smg

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60b5593abe1d2ccec8cd6d49f731370512c57c1a

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
