### ISSUE TITLE
Hallway Module doesnt Connect Properly

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10255]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/200138954-8b82f3f1-27bc-4c64-a3fd-34b5c6c79f6d.png)
New Case of a Hallway not generating properly, leaving a gap in the back wall.

![image](https://user-images.githubusercontent.com/104232152/200141272-bd8548f3-a30e-4aab-95ee-f8de38aaf718.png)

(Edit: Its that hallway module explicitly, happened multiple times)

### Reproduction steps

1.Attempt generating some Outposts, until specific cases of Gaps appear

### Bug prevalence

Happens every now and then

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57b936583318dba2f31dacb043a517b32422730e

**Comment by Rehexr** [comment]
It be fixed, closing
