### ISSUE TITLE
Ability to change items max health

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1025]
it would allow to give battaries and oxygen tanks a certain capacity rather than defining drain for each single item.
it's also needed for mod compatibilty so you don't need to chechk every mod with battaries out there and add specific ammount of drain for each battery and instead use some sort of standardised tag

**Comment by Regalis11** [comment]
This can be done by adding a "health" attribute to the item xml.

**Comment by etet2** [comment]
oh, never knew it's a thing
