### ISSUE TITLE
Pulse Laser missing parts in sub preview

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10253]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A minor issue with only the main part of a pulse laser showing up on the sub preview, noticable but not a big issue regardless.
![image](https://user-images.githubusercontent.com/104232152/200136034-b9f5844d-608a-4c98-8980-ddeebf71ad6b.png)

### Reproduction steps

1.Open a preview on any sub with Pulse Laser (Easiest example being the Barsuk)
2.Look at the pulse laser

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe.

**Comment by Rehexr** [comment]
Understandable
