### ISSUE TITLE
Some smg rounds come from nowhere after switching submarine with item transfer

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10264]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In singleplayer campaign, I switched from Barsuk to Humpback.
Some smg rounds showed up as transfered items in metal crates.
![smgrounds](https://user-images.githubusercontent.com/99462070/200161749-1fcbe631-8fa1-4c36-807b-1c1cdbb93446.png)
![smgrounds_2](https://user-images.githubusercontent.com/99462070/200161754-e1054a8a-9b1a-4cf4-bc0b-dfb8132fec3e.png)

### Reproduction steps

1. Switch sub in a campaign.
2. Check if there's some smg rounds.

### Bug prevalence

Just once

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
Plus, I'm sure there wasn't any smg or smg ammo on my Barsuk.

**Comment by Regalis11** [comment]
Haven't been able to find a way to reproduce this, but I implemented a workaround in https://github.com/Regalis11/Barotrauma-development/commit/5190773bb9bf3e73abc965a499fe12f0cdb0a054 that might help with this

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
