### ISSUE TITLE
Talent "Affiliation" on Ignatius softlocks campaign.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10266]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I recruited Ignatius to my team.
When leaving the station the following shows up.
![AbilityCondition affiliation none](https://user-images.githubusercontent.com/99462070/200163059-2796924a-4b6a-4671-bdf9-24a6df10f7e1.png)

When completing any mission and try to dock to a station.
The following errors keeps showing which softlock my campaign.
![docking error](https://user-images.githubusercontent.com/99462070/200163039-27e6955e-6b7a-424d-b3c9-40a5a3450f5c.png)
![docking error_2](https://user-images.githubusercontent.com/99462070/200163050-6413d864-c2a4-4f0c-8d40-3e66dc1728d2.png)

I opened my save file with Barotrauma Save Editor and compared Ignatius' data with my captain who has "affiliation" talent too.
![Ignatius](https://user-images.githubusercontent.com/99462070/200163073-a1ff09e1-a55e-47d8-92dd-ed76fcc50c8d.png)
![my captain](https://user-images.githubusercontent.com/99462070/200163100-2130b927-19d0-4d06-ae92-614bcf4089ff.png)

It seems Ignatius' "Affiliation" doesn't associate to any faction.
Which might be the reason to this issue.

### Reproduction steps

1. Start a campaign
2. use "givetalent affiliation" on a character
3. complete any mission and try docking
4. errors pop up and prevent docking

### Bug prevalence

Just once

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
This behavior has been reworked in https://github.com/Regalis11/Barotrauma-development/commit/d97c30c0dca201aa3c11cbbb35d5c544258ff8bb and should no longer be an issue

The NPC's talents need to be changed however still

**Comment by Regalis11** [comment]
>The NPC's talents need to be changed however still

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2cb81fdc043707078f256abbe465838d1859ef53

**Comment by JeroonBosch** [comment]
Possibly outdated, with the new functionality of Affiliation

**Comment by JeroonBosch** [comment]
There's no softlock, but despite having the talent defined:
`<talent identifier="affiliation"/>`
the NPC doesn't actually have the talent
![image](https://user-images.githubusercontent.com/8641689/215095654-4d41eec8-c4a2-454e-82f5-b180a050c376.png)
![image](https://user-images.githubusercontent.com/8641689/215095691-8399d13f-e13b-4b44-b094-2669f5f2896f.png)

**Comment by JeroonBosch** [comment]
Nevermind, used old save accidentally, closing
