### ISSUE TITLE
Researchescort event causes error

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10261]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When entering a research outpost, this error popped up, seems like a broken event 
![image](https://user-images.githubusercontent.com/104232152/200142738-d13cf38a-ee5c-493a-b464-a40732f5a2fd.png)

### Reproduction steps

Enter research outpost, until researchescort event might happen

### Bug prevalence

Happens every now and then

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/975d21ecab6fd665e6a35f6a4126769d144a5152
