### ISSUE TITLE
Ignatius' handcannon rounds marked as stolen

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10265]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I met Ignatius May and welcomed him to my crew.
![Ignatius handcannon rounds marked as stolen](https://user-images.githubusercontent.com/99462070/200161970-c81b8324-1c8d-431c-805e-87a500ea6d2e.png)

### Reproduction steps

1. Meet Ignatius in campaign and let him join your team

### Bug prevalence

Just once

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2f0d2f9e6ba7d8a0b7c34e1efd1441321e2f2005

**Comment by Lithosagym** [comment]
Tested, Ignatius May's handcannon rounds are no longer marked as stolen. Issue is fixed.

**Comment by JeroonBosch** [comment]
Confirmed fixed, but recommend decreasing the trigger radius, in some cases it can trigger while being in a different room:
![image](https://user-images.githubusercontent.com/8641689/212890931-b9a4535f-7a54-4ddb-b46b-775387c8a11b.png)
