### ISSUE TITLE
Server browser crashes to desktop when opened

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#10271]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Most times when I open the server browser, the game crashes to desktop after ~2 seconds.
No crash report is created.

### Reproduction steps

1. Launch game.
2. Open the server browser.
3. Game crashes.

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Server filter settings:
  <serverfilters
    FilterSameVersion="True"
    FilterPassword="False"
    FilterIncompatibleServers="False"
    FilterFullServers="False"
    FilterEmptyServers="False"
    FilterWhitelistedServers="False"
    FilterOffensiveServers="False"
    servertag.Serious="True"
    servertag.Casual="True"
    servertag.Roleplay="True"
    servertag.Rampage="True"
    servertag.SomethingDifferent="True"
    sandbox="True"
    mission="True"
    pvp="True"
    multiplayercampaign="True"
    karma="Any"
    traitors="Any"
    friendlyfire="Any"
    voip="Any"
    modded="Any" />
```

**Comment by Jade-Harleyy** [comment]
**Note:** I have [ReShade](https://reshade.me/) installed for Barotrauma, using this preset: [ReShadeBarotrauma.txt](https://github.com/Regalis11/Barotrauma/files/9946644/ReShadeBarotrauma.txt)
(As GitHub does not allow uploading .ini files, please replace the .txt extention with .ini)

**Comment by Regalis11** [comment]
I unfortunately wasn't able to reproduce this, but didn't test with ReShade yet, so I'd suspect it has something to do with the issue.

**Comment by Regalis11** [comment]
No known steps to repro, closing
