### ISSUE TITLE
Lab Contacts gives incorrect discounts

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10276]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When taking the the talent Lab Discounts, all items are given a 30% discount, with the exception of items with the chem tag, which recieve a ~9% discount.

Quick spreadsheeting for a selection of items.
![image](https://user-images.githubusercontent.com/37850646/200364593-2c6f8040-321b-456f-8e51-9a2ef78c7a19.png)

Here are two examples of the shop prices as they change.

Without the talent:
![image_2022-11-08_032511406](https://user-images.githubusercontent.com/37850646/200361963-61074242-315d-4089-91c0-94645db20c79.png)

And the same shop with the talent
![image](https://user-images.githubusercontent.com/37850646/200362029-4345c1d1-7ff0-4591-937c-5e73abfb1138.png)

Without the talent:
![image_2022-11-08_032340272](https://user-images.githubusercontent.com/37850646/200361632-dbe1b5ca-ccfe-4bdd-a8b1-731c7619290f.png)

And the same shop with the talent
![image](https://user-images.githubusercontent.com/37850646/200361711-ed820ff7-9a18-4d28-bd0f-82fc5e7e7b17.png)

### Reproduction steps

1. start a campaign (tested on a multiplayer save)
2. check the merchant's prices
3. give yourself the lab contact talent
4. observe that all items receive a 30% discount, except items with the "chem" tag, which receive about a 9%

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d67b6a316d7c6af5aefc5646988ab2c92f8fe285

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
