### ISSUE TITLE
Barsuk engine & reactor low repair threshold

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#10275]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Barsuks engine and reactor have a low repair threshold of 50

![image](https://user-images.githubusercontent.com/86321358/200285717-81b4e5da-c422-4721-a63e-90146d6e675c.png)
![image-3](https://user-images.githubusercontent.com/86321358/200285754-4ff170be-b7c2-49f0-9991-6c73e1f87c99.png)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not a bug: the default repair threshold for engines and reactors is 50.

**Comment by Smau35** [comment]
Not being able to repair the engine until its 50 durability makes barsuk very slow and its slow to begin with
