### ISSUE TITLE
Projectile spawn positions on some ship guns offset from barrel

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10277]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For the following guns the projectiles spawn inside the gun, hitting things that would be "behind" the muzzle and should be out of gun range:

Coilgun, Railgun, Double Coilgun

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/7f4419b844f51ca2fa31f33f7c509ab1eb783aeb no issues found, closing.
