### ISSUE TITLE
"Manually Outfitted" doesn't do anything when starting a campaign

### ISSUE THREAD

**Issue by Petethegoat** [Regalis11/Barotrauma#10272]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/734762/200195652-3222358e-0727-4d3f-b189-ddf0d927ec29.png)

When saving a submarine, the description of the manually outfitted checkbox strongly implies that it will prevent extra supplies being spawned with the submarine, when in fact it only does anything when switching subs.

It'd be very nice if this worked properly. If it's working as intended, then the tooltip definitely needs to be adjusted to reflect it's actual function.

I made a very naive edit to fix this here: https://github.com/Regalis11/Barotrauma/compare/master...Petethegoat:Barotrauma:manual-outfitting, and I've confirmed it works but not that it doesn't break anything else.

### Reproduction steps

Start a campaign with a manually outfitted sub.
Note how it spawned items anyway, in crates if there's no autofill containers available.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
That "naive" fix is actually all that's needed. Added that in Regalis11/Barotrauma-development@25d9370.

**Comment by Regalis11** [comment]
Tested, couldn't spot any issues. Closing.
