### ISSUE TITLE
Can't fabricate Clown Crate 

### ISSUE THREAD

**Issue by Spazhero** [Regalis11/Barotrauma#10282]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some crafting fabricators seem to now allow for the crafting of the Clown Crate

### Reproduction steps

1) Enter a friendly station
2) bring materials to fabricator
3) Fabricator doesn't acknowledge metal crate as crafting material

### Bug prevalence

Just once

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f80f8ef07b3cf64e3541128bdf11268b98bd8077

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
