### ISSUE TITLE
[Unstable] Husk doesn't show up in security tutorial

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#10280]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Doing the security officer tutorial, the husk that is supposed to appear doesn't show up and I can't progress.
![image](https://user-images.githubusercontent.com/42877449/200423447-cd50d2f4-836b-4d49-b050-3a6b29ada5b6.png)

### Reproduction steps

Start the job tutorial.
Choose security officer.
Get to the part where the enemy should show up.
No enemy

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5eed33a665f0e71bb578b88de284ec4d2561b48c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
