### ISSUE TITLE
Inability to dock with the Outpost.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1028]
**Description**
Because of the length of the submarine it was impossible to dock with the "base". The ice prevents.

**Version**
Windows. 0.8.9.2.

**Additional information**
![image](https://user-images.githubusercontent.com/33912761/52170091-015baf00-2755-11e9-9459-cc7e8ed371ca.png)

**Comment by Regalis11** [comment]
Should be fixed by 19d5ed5. Although it's worth noting that the level generator will not always be able to make the path wide enough for extremely large subs. This particular one doesn't seem that large, but something to keep in mind when building subs.
