### ISSUE TITLE
An error occurred while trying to finish a round in the campaign.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1029]
**Steps To Reproduce**
I sailed on the submarine to the Outpost, went up to the bot and answered his question "Yes".

**Version**
Windows. 0.8.9.2.

**Additional information**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/2825013/crashreport.2.log)
And this is my attempt to finish the round with the help of the top-right button:
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/2825023/crashreport.3.log)

P.S. Actually, I have the best video card.

**Update**
If you end the game using the terminal behind the bot, no errors appear.

**Comment by Regalis11** [comment]
Haven't seen this occur after bbb41a5 nor found a way to reproduce this. I think this can be closed, will open again if the problem reappears.
