### ISSUE TITLE
Medical Clinic cites incorrect vitality loss

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10299]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When viewing afflictions on crewmates in the medical clinic, the Vitality loss always cites the affliction strength, even if the affliction is doing more or less, or no vitality damage. This often leads to incorrect results when dealing with afflictions that do not do damage, or when the character has maximum vitality greater than 100. (For example bloodloss - when at 50 affliction strength, it does ~94.7 vitality loss, whereas the clinic will just show -50 vitality)

Shown below is an example of Husk Infection being displayed as impacting vitality.
![Screenshot (424)](https://user-images.githubusercontent.com/37850646/200868181-7c5b24f0-685e-4e7c-a538-302d3c37701c.png)

Either the clinic should specify that the number being displayed is the affliction strength, or the vitality should be calculated. (Or a combination of both)

### Reproduction steps

1. Start a campaign
2. go to the medical clinic in the outpost
3. give one of your crewmates a non-damaging affliction, like husk infection at strength 50
4. observe that the clinic states that the affliction is doing damage (but it is instead just citing the affliction strength)

Tested using unstable version 0.20.3.0 but this occurs in the stable version as well.

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
