### ISSUE TITLE
Issues on recent clothes stats update

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10290]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. "pirateclothesnovice" (price:150) has more resistance than "pirateclothes" (price:225) and its sprites are named as "Pirate Uniform 2"(should be "Pirate Uniform 1"), swapping their stats should be what you intended.
2. In a previous update, you updated width and density of most clothes, but you forgot to change that of pirate clothes.(Because they are in "Map" folder instead of "Jobgear". That's weird too)
3. Watchman clothes have no damage resistance at all.

### Reproduction steps

Related files:
Map\Pirates\PirateItems.xml
Items\Jobgear\Watchman\watchman_gear.xml

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/db3ba3cb4a5708af57b7265ebdf1e64039b7e824.
Can't see any issues with the changes, closing.
