### ISSUE TITLE
SMG recipe missing

### ISSUE THREAD

**Issue by eriktheraddest** [Regalis11/Barotrauma#10293]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I acquired the perk in the security class for the SMG recipe but it doesn't show up at the Fabricator, as if it does not exist at all.

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10252
