### ISSUE TITLE
Tool Maintenance only gives +1 quality to the mechanic.

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10297]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Tool Maintenance is supposed to give +1 quality to every crew member, however it only gives the quality bonus to the mechanic that takes the talent.

### Reproduction steps

1. start up a game
2. give a mechanic the "Tool Maintenance" talent
3. observe that the mechanic is crafting at +1 higher quality, but all other crew members are crafting without any boost to their quality.

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f604a04ec44463853f501a5998aeb7c5469f31a3 and https://github.com/Regalis11/Barotrauma-development/commit/d0190387c9d495db8b137f3d12aa9e1bb32c5972

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
