### ISSUE TITLE
"Spawnitem" command bug

### ISSUE THREAD

**Issue by VulpesFerrilata4** [Regalis11/Barotrauma#10292]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If trying to spawn item in someone inventory (character_name) if [amount] argument not ommited, the game is giving an error(pic1) and item will spawn in the center(pic2) of the sub. But if (inventory) used as 2 argument, everything works right.
![20221108210620_1](https://user-images.githubusercontent.com/107763144/200643727-6b9ca5e4-efb8-407f-996f-72f761dc8397.jpg)
![20221108210825_1](https://user-images.githubusercontent.com/107763144/200643733-05377b24-f7aa-4ccd-819d-34ea09f23091.jpg)

### Reproduction steps

1. Start a game
2. Use command - spawnitem [item name/id] [cursor/inventory/cargo/random/character name] [amount] using [character name] as 2 argument and without leaving argument [amount] empty
3. Items spawn on the floor somewhere instead of character inventory

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Lithosagym** [comment]
Tested, spawning multiple of an item into a character's inventory properly functions and does not come up with any errors. Issue is fixed.
