### ISSUE TITLE
Genetic Genius spelt as "Genetic Genious"

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10298]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the item name and item identifier, the final talent in the medic's xenologist tree is called "Genetic Genious" and "geneticgenious" 

The correct spelling is "genius", not "genious"

### Reproduction steps

1. Look at the final talent in the medic's xenologist tree

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d00dfe6893da8137462786df9709c6cf56602386

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
