### ISSUE TITLE
CPR can give oxygen without a source of oxygen on the receiving character

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#103]
Although its almost pointless, this does deny death despite there being nothing to breathe.

using a medic on single player to check the code in case, I found a character can be revived for around 0.8 to 1.5 seconds without a diving mask or diving suit equipped while in a fully flooded room.

Although a small issue this does mean you can keep players or AI alive without any oxygen available and doesn't quite make sense.

**Comment by Regalis11** [comment]
Fixed in dde320b
