### ISSUE TITLE
Miracle Worker talent has incorrect description

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10304]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The description of the the Miracle Worker talent is incorrect.

![image](https://user-images.githubusercontent.com/37850646/201079350-1c072f4d-b38f-4228-8f93-f3101c68906a.png)

### Reproduction steps

1. start a game
2. hover over the Miracle Worker talent

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by PokkeTigrex** [comment]
Was able to post an issue regarding this but saw its already posted, also for reference, this was the original description:

![image](https://user-images.githubusercontent.com/85914375/201736188-1b094444-f885-4b46-bf7f-8fb1b2347612.png)

It probably accidentally got overridden when clarifying the immunity.

**Comment by Wheatley1001** [comment]
Talent description now ignores the "You become immune to Miracle in Progress" section as of update 100.5.0.0

![image](https://user-images.githubusercontent.com/105495756/202919234-86bef15e-bc27-4bf8-ae31-08d89860e147.png)
