### ISSUE TITLE
Researcher npcs do not spawn in research modules

### ISSUE THREAD

**Issue by Rimrue** [Regalis11/Barotrauma#10305]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Neither the research outpost nor the colony research modules spawn researcher npcs, making it extremely easy to thieve supplies.

Research outposts: The spawnpoints on research outpost modules contain the tags "research", but these spawnpoints do not spawn any npcs at all. If you remove the tags, then researchers will spawn in the module. Currently they spawn in the crew module, but don't seem to migrate to the research module from there, leaving it empty.

Colonies: The spawnpoints in colony research modules do not contain tags and therefore should spawn researchers (they do commoners), but the XML for generating npcs in cities does not include researchers in the list. Adding researchers to the list should solve the problem. I will attach a screenshot of both the outpost npc generation XML and the city one for comparison.
![image](https://user-images.githubusercontent.com/27902974/201106880-f21f150a-2dc4-468e-a207-10e1d79c66f0.png)

![image-1](https://user-images.githubusercontent.com/27902974/201106821-2365a320-82e0-4382-afe3-d75dedcb307e.png)

### Reproduction steps

1. Open level editor.
2. Generate a research outpost or city.
3. Notice the empty research modules.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8656f0b767aecd211d545db9120ea96dfe3914ac

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
