### ISSUE TITLE
[Factions] Hammerhead Matriarch Genes are experiencing incredibly odd behaviour

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10309]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### The following is a recollection of my experiences shared in the dedicated channel. 

I noticed that my Hammerhead Matriarch genes were not working at all. I had combined Tiger Thresher (100%) genes with Hammerhead Matriarch (100%, and will be referred to as simply "Matriarch") genes with a tainted result (Decrepify). After suffering blunt force trauma and lacerations from my crewmember, the wounds did not heal after extended periods of time had passed. The first images show this.
![image](https://user-images.githubusercontent.com/105495756/201224174-4356b6fb-1ac6-4bc4-995b-cfcd7b5ffc7f.png)
_Figure 1. Evidence of Matriarch genes_

![image](https://user-images.githubusercontent.com/105495756/201224285-23234865-2486-494b-a541-3f9b438cdd43.png)
_Figure 2. Evidence of injuries. Taken at 21:53_

After taking further damage and waiting for roughly three minutes, the wounds did not heal.

![image](https://user-images.githubusercontent.com/105495756/201224612-35db44b8-b9a5-461b-958a-68b4434f0591.png)
_Figure 3. Evidence of further injuries. Taken at 21:56_

My crewmate also used Matriarch genes. His were working as intended. I checked my Tiger Thresher genes, they were also working as intended. The issue was solely with my Matriarch genes. The following is an exert taken directly from my comments in the discord channel:

_"I've used opium on myself to see if that resets it
further tests show that his healing works rapidly whilst mine is non existent
perhaps there's an issue with gene placement?
the only thing I did differently was when giving him his genes, I put the genes in the genetic splicer and then gave it to him
whereas with my genes, I put the genes into the genetic splicer within my head
that's the only thing I did differently. Would that break the genes' functionality?
The OTHER thing that's super weird is that the Tiger Thresher genes which I'm using in combination work perfectly fine
so only half of the genetic content is active"_

Upon starting a new mission, however, the ill-effects completely subsided and acted normal. When we docked at the next outpost, there were further issues with genes. 

Notably, the healing rate of the genes was significantly lower in my character than previously observed. In the case of my crewmember, he reported "rubber-banding healing" of his health. Upon further inspection, it was revealed that his health was healing from 68% bite wounds down to 65% bite wounds, only to reset to 68% for half a frame and jump down to 67%. 

![image](https://user-images.githubusercontent.com/105495756/201225521-37e3bb85-e4b8-463d-b22b-2b22d31769e4.png)
_Figure 4. Initial health using health HUD_

![image](https://user-images.githubusercontent.com/105495756/201225401-5705b0cf-8c2a-433e-a0f8-b8a8935fffad.png)
_Figure 5. Evidence of wounds healing_

![image](https://user-images.githubusercontent.com/105495756/201225442-57616e6b-4213-4cad-8729-a909086accd3.png)
_Figure 6. Evidence of wounds resetting_

In complete honesty, I have absolutely no idea what caused this or how to reproduce it. I do not know the scale of which it works upon, whether it is exclusive to Matriarch genes or if it has wider reaching influences. I am hoping someone can shed light on this issue or a dev more knowledgeable in these areas can work out what is going on.

### Bug prevalence

Happens regularly

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I gave this a quick test, but so far wasn't able to reproduce the issue. To me it sounds like some kind of an issue with syncing the genetic afflictions in multiplayer, will need to do some more debugging.

**Comment by Wheatley1001** [comment]
Another user has experienced the start of this issue. Padex (he's in the discord), when asked about their experience with it, responded with _"No clue. In my case I had stun locked to a certain amount and it wouldn't go away. Had to resort to using the outpost medic"_. Hopefully this helps or narrows down the search.

**Comment by Vykn** [comment]
I was able to replicate the issue with matriarch genes not healing. Tested in the sub editor.
https://user-images.githubusercontent.com/37850646/201510212-58a74245-f399-4021-86c4-30a9d4329d29.mp4

**Comment by Wheatley1001** [comment]
As of 100.5.0.0 this issue occurred again. Matriarch genes also overall felt inactive or heavily reduced for them being 100%. This was with two people using Matriarch genes if that helps.

![image](https://user-images.githubusercontent.com/105495756/202860108-31ae0154-a55d-49bf-aff9-9cdac59d3abf.png)

**Comment by Rokvach** [comment]
Moving to Team1

**Comment by Regalis11** [comment]
I unfortunately couldn't find a way to reproduce this

**Comment by ArnasAdomaitis** [comment]
I noticed this depends on character positioning on the list, me and my friend were having the same issue, and used characterdata file to switch positions, as a result, whoever is on the list's first slot, will have their matriarch gene work perfectly no problem, the other person won't be able to make it work no matter what, hope this helps
