### ISSUE TITLE
Balance query: Ballast flora infection at outposts

### ISSUE THREAD

**Issue by lewri** [Regalis11/Barotrauma#10301]
I'm not sure if this really is a bug but I had my sub docked at an outpost for quite a while while sorting out other things and when the sub left it reported ballast flora with an extreme spread across most of the sub.

I can only assume that the ballast flora infected the generators while docked. I'm not entirely sure if that should've happened since the generators weren't running or the ship moving. It also feels a bit cruel to depart an outpost with a ballast flora infestation you got while there? 

Ver: 0.19.14.0 - Win 10.

**Comment by Regalis11** [comment]
Thank you for the report!

This sounds like it might be a bug: there should never be ballast flora spores in outpost levels. Although, based on this information, it's hard to tell whether the sub got infected in the outpost level or not: it could be you got infected during the previous mission, but the flora didn't burst out until later. Also, what do you mean by "generators"? The ballast flora should get in the sub through the ballast pumps.

**Comment by lewri** [comment]
Yes sorry Regalis, I meant the pumps.
It may be likely it happened in the very last moment before docking, though none of the crew or anything alterted me to its presense. Unfortunately it was a few weeks ago so the save is probably gone now :( If I find it again I'll try to report it.

It was more just a query if ballast flora shouldn't be possible to start infection at an outpost?

**Comment by Regalis11** [comment]
Ok, thank you for the clarification. :) I think the most likely explanation is that the sub was already infected when you reached the outpost. It takes a while for the ballast flora to grow enough to be visible and spread through the sub, so you might not have noticed it even if you took a look inside the ballast after the infection.
