### ISSUE TITLE
[Factions] Cultist Robes overlaps Diving Suit Helmet

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10308]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whilst wearing the Cultist Robes and a Combat Diving Suit, the hood overlaps with the helmet. This is represented below.

![image](https://user-images.githubusercontent.com/105495756/201223105-e6ddd92b-bd02-48af-8c22-9c752ef18101.png)

### Reproduction steps

1. Wear Cultist Robes
2. Wear Combat Diving Suit
3. Observe hood overlapping the helmet

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/057282b4b695464d212fc7c71a99da614e880cbb

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
