### ISSUE TITLE
Texture error: Depleted smg magzine

### ISSUE THREAD

**Issue by Raven-233486** [Regalis11/Barotrauma#10302]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I think it is a silly problem that you forget to write sourcerect in the xml.
![屏幕截图 2022-11-09 121218](https://user-images.githubusercontent.com/72175577/200932094-b969e8d9-6eda-49e4-a838-068245530533.png)
![屏幕截图 2022-11-09 121425](https://user-images.githubusercontent.com/72175577/200932559-db4c5488-7eac-4f75-aaab-73011cd3f8a1.png)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We did not forget to write it: this is a variant of another item, and inherits the sourcerect from the base item. Did you notice some kind of problems caused by this? The icon seems to be working correctly to me.

**Comment by Raven-233486** [comment]
Yes, the texture in my computer can not display correctly. I may show you
the screenshot after i back home.

**Comment by Raven-233486** [comment]
Strange. It is now displaying correctly.
