### ISSUE TITLE
Legacy railguns don't work

### ISSUE THREAD

**Issue by Gobrich** [Regalis11/Barotrauma#10300]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The projectile simply falls down and does not fly forward when fired from an old railgun. Previously, it was possible to fire a railgun projectile from any weapon by selecting the desired tags in the editor. In version 0.19 this feature is no longer available.

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d6fca1a5e4410a092ef4f1b5a890f450bae0a0d4

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
