### ISSUE TITLE
ruler uses wrong symbol for metre

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10303]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ruler in sub editor uses wrong symbol for metres.

Should be a lowercase m but editor shows an uppercase M

![image](https://user-images.githubusercontent.com/5103517/200974980-39453730-b20d-4504-ba6a-26f32f5ef8f1.png)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cb574de228dc451c4caedcd39a845b9ce84df9b0

**Comment by Tsunder** [comment]
Thanks, you're the best around!

**Comment by Regalis11** [comment]
There should also be a space between the number and the symbol @3e849f2e5c

**Comment by 3e849f2e5c** [comment]
Added a space in https://github.com/Regalis11/Barotrauma-development/commit/a78d0ec9ddeaa03687f3273c9e4c70c7a7f35255
