### ISSUE TITLE
Incorrect keybinding(open chat)

### ISSUE THREAD

**Issue by Dmitry386** [Regalis11/Barotrauma#10312]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pressing the NUM5 button opens the chat. In the settings, the opening of the chat is on the B button.

### Reproduction steps

Press NUM5 button in game

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6d39e1206ef35eb8f3eb616327e99a7a14a2cf82

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
