### ISSUE TITLE
Genetic material is too abundant with Blackmarket Genes talent

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10315]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Currently, with the Blackmarket Genes talent, 100% genes are selling for 300-400 marks, which is extremely cheap. 100% genes requires from ~4-10 refines, and so getting high quality genes is rather laborious, and certainly worth a fair bit more than 400 marks.
In addition, some genes should perhaps be valued differently. Husk, Mudraptor, and Spineling genes have no difference between 10% and 100% genes, so they are less valuable compared to the rest.

There are also a very large amount found at each store, which makes accumulating them in large quantities fairly trivial.

![image](https://user-images.githubusercontent.com/37850646/201391627-ec64023f-75b1-463e-a1b8-23e1025a0901.png)

UGM (unidentified genetic material) also seems to be priced at a similar amount to the spliceable genes. Since creating 100% genes requires 4-10 UGM, and you don't know which types of UGM you are purchasing, there really should be a price difference.

In my opinion, selling 100% genes at stores makes redundant the whole process of refining genes into stronger ones. 100% genetic material should either be really expensive or really hard to find in shops. Purchasing UGM from shops makes a lot more sense, since the talent is "Blackmarket Genes", it's somewhat appropriate that you don't know what kind of genes you're purchasing until you research them.

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5bb41477d8559d0cb3ad28d28320f284232496c8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
