### ISSUE TITLE
Bot talent recipes not unlocking for player

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10317]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I hosted a private session to try out bot talents and made a new save. Gave a security officer bot experience to unlock Munitions Expertise and Weaponsmith and an engineer bot experience for Remote Monitor, Sample Collection, Grid Maintainer and Pyromaniac. Expected my assistant player character to be able to craft the items unlocked by those talents but they remained unavailable to craft even after redocking the sub and saving & quitting/restarting the session.

### Reproduction steps

[save and gamesession.zip](https://github.com/Regalis11/Barotrauma/files/9992440/save.and.gamesession.zip)

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not yet implemented in this build, ticket in our private repo https://github.com/Regalis11/Barotrauma-development/issues/3741
