### ISSUE TITLE
Piezo crystals have gone missing

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10316]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Piezo crystals no longer spawn in the Great Sea.

In the <LevelResource> block for pizeo crystals at the bottom of minerals.xml, the leveltype should be "greatseabasic" but is currently set to "thegreatsea".

### Reproduction steps

1. enter the level editor
2. generate a "greatseabasic" level
3. observe that there are no piezo crystals

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8ffdff3f64eaa62509acf172be1c2b50b3ceb81c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
