### ISSUE TITLE
Focus isn't lost on a object if you play a accordion 

### ISSUE THREAD

**Issue by LunaaRatTips** [Regalis11/Barotrauma#10319]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was just playing accordion that I found on a ship and meanwhile playing it, I noticed that while playing it you don't lose focus on items, like you'd have a option to rewire it and such.

### Reproduction steps

1. Get in a game, multiplier or single doesn't matter (done on multiplier)
2. Acquire a accordion, no matter the way
3. Hold right click and hover your mouse over any interactable object
4. Play and start walking away

https://youtu.be/6M-Ym2JBdXU
That is a link to a video of how it looks like.

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97c2e7523e0cd7f7ef5d51e6ee777dcf8a589555

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
