### ISSUE TITLE
[Closed Beta/Dev Version] Light Bugs

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1031]
So basically, when looking through a periscope or gun the outside of the hull flashes in shadows and things such as that.

Also the guns and periscopes produce lights that generally bug out and go all over the place.

That's about it.

**Comment by danielasteljoki** [comment]
Possibly related: seeing through alien ruin walls when using a periscope.

**Comment by rico6822** [comment]
> So basically, when looking through a periscope or gun the outside of the hull flashes in shadows and things such as that.
> 
> Also the guns and periscopes produce lights that generally bug out and go all over the place.
> 
> That's about it.

Sometimes when I install a searchlight to my submarine it releases light to it's placeholder direction even when not powered up. yes, I remembered to power it up and set up all the wiring.

Also Banisher we had been noticed in Barotrauma's official media for our github activity in here which I am personally thankful for. To be honest the only way I can maturely respond to it is to paradoxically claim how I cannot be aware enough of it.

[https://barotraumagame.com/gameplay-features/greetings-from-the-closed-alpha/](url)

**Comment by rico6822** [comment]
> So basically, when looking through a periscope or gun the outside of the hull flashes in shadows and things such as that.
> 
> Also the guns and periscopes produce lights that generally bug out and go all over the place.
> 
> That's about it.

Sometimes when I install a searchlight to my submarine it releases light to it's placeholder direction even when not powered up. Yes, I remembered to power it up and set up all the wiring.

Also Banisher we had been noticed in Barotrauma's official media for our github activity in here which I am personally thankful for. To be honest the only way I can maturely respond to it is to paradoxically claim how I cannot be aware enough of it.

[https://barotraumagame.com/gameplay-features/greetings-from-the-closed-alpha/](url)

**Comment by rico6822** [comment]
> So basically, when looking through a periscope or gun the outside of the hull flashes in shadows and things such as that.
> 
> Also the guns and periscopes produce lights that generally bug out and go all over the place.
> 
> That's about it.

Sometimes when I install a searchlight to my submarine it releases light to it's placeholder direction even when not powered up. Yes, I remembered to power it up and set up all the wiring.

Also Banisher we had been noticed in Barotrauma's official media for our github activity in here which I am personally thankful for. To be honest the only way I can maturely respond to it is to paradoxically claim how I cannot be aware enough of it.

https://barotraumagame.com/gameplay-features/greetings-from-the-closed-alpha/

**Comment by Rokvach** [comment]
I don't think this is a issue anymore. Closing.
