### ISSUE TITLE
Latcher and hammerhead matriarch death sounds not working

### ISSUE THREAD

**Issue by HungusHumongous** [Regalis11/Barotrauma#10313]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ive never noticed death sounds in the game, and when trying to get the latcher to trigger its death sounds ingame i couldnt, i reloaded the same three times and it never happened.
to test this further i spawned in the hammer head matriarch several times, to which i never had an explosion sound.

### Reproduction steps

1. Start a game
2. find a latcher or hammer head matriarch or spawn one in using the console
3. have the creature die or kill it and youll hear the lack of sound

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### -

null

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No error code
```

**Comment by Regalis11** [comment]
Thank you for the report! The latcher has no death sound, so that's not really a bug. I couldn't spot any issues with the Matriarch's death sound, it does seem to play. It's pretty subtle though, so maybe it's possible you just didn't notice it?
![image](https://user-images.githubusercontent.com/14351070/201469441-8a881e8d-521f-4ca2-9849-6ffe1093b304.png)

**Comment by HungusHumongous** [comment]
It is possible i just didnt notice it. Although that doesnt to me atleast
make much sense.
The latcher is supposed to play one of two "escape sounds" upon state
`Die`. Although I tested whether changing the contents of the audio file
would make the death sound play, i neglected to do the same for the
Matriarch which is my bad.
Ill take it that the latcher achieves state Die whilist leaving the abyss
depth threshold then.
below are both line 30 of both the Hammerhead Matriarch and the Latcher
XML. I apologise for the miss report of a bug, Although the file name of
the sound isnt ambiguous the state is.

<sound file="Content/Characters/Latcher/ABYSSM_escape.ogg" state="Die" range
="30000" volume="1" />
<sound file=
"Content/Characters/Hammerheadmatriarch/MHAMMERHEAD_explosion3.ogg" state=
"Die" range="10000" volume="1" />

**Comment by Regalis11** [comment]
Hmm, you're right - I didn't notice those "escape sounds" being used as the latcher's death sounds. Giving the latcher a test, I couldn't notice any issues with that either: the death sound did seem to play as expected.
![image](https://user-images.githubusercontent.com/14351070/201471031-12ffc4d4-0095-47d9-bed0-d6d238bdb42e.png)

**Comment by itchyOwl** [comment]
Couldn't repro. Matriarch's death sound is just a dampened explosion, so it's easy to miss it if it doesn't hit the sub. Latcher's death sound is a scream, which should be fairly audible when it's closeby.

**Comment by Regalis11** [comment]
No known steps to repro, closing
