### ISSUE TITLE
Campaign tutorial keeps adding new objectives, events keep looping

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#10320]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/14351070/201413100-cac3bdda-b6de-4161-90d6-ec7636d7207e.png)

### Reproduction steps

1. Start the campaign tutorial

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57098607a688bbe5b84bc521e213909b60f460e8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
