### ISSUE TITLE
Endless tutorial mission

### ISSUE THREAD

**Issue by k0l4un6** [Regalis11/Barotrauma#10322]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Endless giving a mission: tutorial.campaing.introdaction.converstation_start . It is stopping character in one place.
![image](https://user-images.githubusercontent.com/118017393/201414994-c08363a9-7c46-4a4f-a440-728e5d113ff1.png)

### Reproduction steps

1. Start individual company
2. Start expedition
3. Endless mission and moveless.

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by c33tz** [comment]
Same for me. Unplayable in SP now (on unstable branch)

**Comment by GoodDays13** [comment]
I have this too, here's a debug thing I saw.
![image](https://user-images.githubusercontent.com/42877449/201441368-d6c66fc2-8089-4b01-8cfe-47631db5f1e5.png)
You can turn off the tutorial in the settings so it's playable for now btw, @c33tz

**Comment by yiitbrak** [comment]
Can confirm this bug also happens on linux. Had to kill poor guy from console to get out of loop
![image](https://user-images.githubusercontent.com/50929670/201441514-dd9d7d9e-bb8e-48fa-aa80-670da52f9082.png)

**Comment by GoodDays13** [comment]
I have tested a bit further and ran into another guy with a mission. the same loop happens when I accept until I decline. i still have the mission

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320
