### ISSUE TITLE
Diving suits' Husk infection resistance is misleading

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10323]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Husk infection can be very dangerous, and to many newer players it is quite scary to deal with. Players may seek to use items or medicines to prevent the disease, rather than having to go the trouble to cure it once infected.

There are a few items in the game that provide protection against Husk infection; notably the several diving suits offer resistance.
The diving suits, like most gear, provides resistances to various afflictions. For example, diving suits negate most damage types by a certain amount - when you are hit by a crawler, you receive 30% less damage (the damage is multiplied by 0.7). This is intuitive and understood by everyone. 
![image](https://user-images.githubusercontent.com/37850646/201416099-e87d1af9-b768-4b98-8802-797623272a06.png)

The problem arises when talking about resistances to poisons. Specifically, Husk infection. The diving suit cites "-75% Husk Infection". Many people interpret this as a reduction in the _chance to catch husk infection_ - and this is sensible to assume, because it doesn't matter if you receive less husk, so why would the suit reduce the amount? It doesn't matter if you receive 5 husk or 1.25 husk, because you have to spend the same amount of medical resources curing it either way. All that has been saved is a few seconds, which is fairly insignificant.

Diving suits do in fact reduce the chance to catch husk infection. However this chance is 50%. The figure of -75% comes from the fact that the suit reduces incoming husk damage by 50%, which as previously stated, makes no difference. It doesn't make sense to multiply these two figures together when talking about Husk Infection. The diving suit advertises a reduction of husk infection by 75%, but in the context of a husk infection, this is misleading, since Husk advances on its own. The practical reduction is only 50%.

There is no need for the diving suits to provide husk infection resistance. It does not slow down the infection once it has taken hold, and the reduction in initial affliction strength makes very little difference. Although, if it were possible to specify that the chance reduction and strength reduction were separate, that would solve this.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by soledad630** [comment]
I would say maybe add "husk resistant" and "bleed resistant" as keywords on armor, which covers the 50% reduction part. Then the chance to block can be interpreted/reworded as a separate value.

**Comment by itchyOwl** [comment]
Addressed in in Regalis11/Barotrauma-development@3879d42.
