### ISSUE TITLE
[Endgame Branch] Events interactions can be infinitely repeated

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10326]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When repeatedly pressing "e" to activate an event, itll start that event for each press. This happened to me most notably during the lost captain event, which let me repeatedly finish the textbox interaction for Helm skill. Aswell as this funny example of the case event, spawning pets and crawlers repeatedly

![image](https://user-images.githubusercontent.com/104232152/201433226-eb3cb4d1-ef6f-4dd6-8d32-026496c006c5.png)

### Reproduction steps

1.Go to an outpost
2.Find an event that has to be interacted with
3.Keep pressing "e" after the textbox opens
4.The Textbox can be repeated through as many times as "e" was pressed, including reaping the rewards

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to be caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/10320
