### ISSUE TITLE
Outpost Manager Clown Issue Event Gives Infinite Money and Skills

### ISSUE THREAD

**Issue by TheModernNano** [Regalis11/Barotrauma#10329]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In singleplayer, after completing the quest for the outpost manager, it goes into an infinite loop of completing the quest, giving you +20 weapons skill until you are at 100, and 1,000 marks each time.

Note that when I say it happens every time I play, I mean every time I encounter the clown event, it happens if you offer to help.

### Reproduction steps

1. Start a single-player campaign.
2. Talk to the outpost manager with the clown event active in the outpost.
3. Offer to help and accept the quest, saying got it.
4. Threaten the clowns.
5. Complete the mission.
6. You are now stuck in an infinite loop.

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Made a note for this, this is actually an issue with all interactible text events currently

**Comment by Regalis11** [comment]
Seems to be caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/10320
