### ISSUE TITLE
[Unstable] HMG skill check ALWAYS stuns you when shooting it

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10325]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://cdn.discordapp.com/attachments/668819422919524352/1040735234523660329/2022-11-11_18-08-38.mp4

The HMG ALWAYS stuns you when using it with less than 75 weapons, it's therefore impossible to use
Maybe change that so it's a % chance to stun instead? You're already penalized by bigger spread

```xml
      <StatusEffect type="OnUse" target="Character">
        <Conditional skillrequirement="true" weapons="lt 75" />
        <Affliction identifier="stun" strength="20" />
      </StatusEffect>
      <StatusEffect type="OnUse" target="Character">
        <Conditional skillrequirement="true" weapons="lt 50" />
        <Affliction identifier="stun" strength="40" />
      </StatusEffect>
      <StatusEffect type="OnUse" target="Character">
        <Conditional skillrequirement="true" weapons="lt 25" />
        <Affliction identifier="stun" strength="80" />
      </StatusEffect>
```

to

```xml
      <StatusEffect type="OnUse" target="Character">
        <Conditional skillrequirement="true" weapons="lt 75" />
        <Affliction identifier="stun" strength="40" probability="0.05" />
      </StatusEffect>
      <StatusEffect type="OnUse" target="Character">
        <Conditional skillrequirement="true" weapons="lt 50" />
        <Affliction identifier="stun" strength="40" probability="0.05" />
      </StatusEffect>
      <StatusEffect type="OnUse" target="Character">
        <Conditional skillrequirement="true" weapons="lt 25" />
        <Affliction identifier="stun" strength="40" probability="0.05" />
      </StatusEffect>
```

15%/10%/5% chance to stun (well that's not exactly how statistics work but you get the idea) 

### Version

0.20.5.0 (Unstable)

**Comment by Ek-Videogames** [comment]
So the 'Junction Conundrum' now applies to guns? sounds fun.

**Comment by ubertpendragon** [comment]
Food for thought
https://user-images.githubusercontent.com/73229309/201475912-21e62731-c379-4710-bfd5-91350b625d1c.mp4

**Comment by JeroonBosch** [comment]
Working as designed/intended, closed
