### ISSUE TITLE
Medical Doctor stuck trying to treat active character

### ISSUE THREAD

**Issue by SKie72** [Regalis11/Barotrauma#10321]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When playing singleplayer on the new unstable build, anytime the medic see's me as any active character with treatable injuries, they latch onto me and hold me as they attempt to treat it without actually treating it. The moment I swap to another character they let go and say the injury is treated or ignorable. This repeats infinitely.

### Reproduction steps

1. Start a singleplayer campaign
2. Get a doctor and 2 other characters of any role.
3. injure one of the characters by falling down
4. get the doctor to notice your injury
5. swap to other character and see results as you swap back and forth.

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None.
```

**Comment by NilanthAnimosus** [comment]
Got this on essentially 0.20.5.0 (WIP branch), but with it being bot to bot. Image of debugai:

![image](https://user-images.githubusercontent.com/29177976/201677084-3f67568e-bbf0-409e-ba30-901ff18bd438.png)

Medic AI (their inventory mostly visible):
![image](https://user-images.githubusercontent.com/29177976/201677339-aea065ec-1c1c-4dd1-b32a-434f573c6544.png)

when switching to the medic AI I noticed there was no health interface open only grabbing, but I assume this is normal.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/3850e6c21d8ed796e006aacc799f8d54f879ac34, no issues found, closing.
