### ISSUE TITLE
[Factions] Assistant unlocking Politician tree

### ISSUE THREAD

**Issue by SquareEyeGamin** [Regalis11/Barotrauma#10335]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When unlocking graduation ceremony as assistant who choose captain apprenticeship if you get the Politician tree you will get all the faction effects
![Barotrauma_r75MNtLFbX](https://user-images.githubusercontent.com/43591726/201444413-bedffe3c-bba4-4981-a0c2-ec98fb718d4e.png)

### Reproduction steps

1. Start a campaign
2. Spawn assistant
3. go through talents making sure to pick captain as apprenticeship
4. get Graduation Ceremony
5. repeat 2-4 until you get Politician tree

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0c285c6e1a6239695835fd755cda2917a09aa560

**Comment by ekqvist** [comment]
Tested after the fix. Seems that now only a single affiliation talent is selected so seems to be working correctly. Closing.
