### ISSUE TITLE
Affliction icons overlap with the inventory

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10332]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When holding another character, mostly bots, and accessing their inventory, your inventory ui will overlap with the afflictions, a minor inconvinience at best. 
![image](https://user-images.githubusercontent.com/104232152/201436457-f9b77d4b-d093-4ac5-925e-d78ea07757b4.png)

### Reproduction steps

1.Hold another character while having an affliction visible on the right
2.See your inventory items overlapped by it

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fb58e4b702a3d4561ece5a8a5c481b90eb24ae00

**Comment by Lithosagym** [comment]
Tested, rather than overlapping the affliction icons onto the inventory, the affliction icons are instead hidden. Issue is fixed.
