### ISSUE TITLE
[Faction] All open doors cannot be shot through with hitscan weapons

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10330]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some reason specifically on the faction branch, hitscan gunshots cannot pass basically every door, from hatches, custom doors, even alien doors. Harpoons and 40mm's and whatever other projectile based weapons are fine however.

![image](https://user-images.githubusercontent.com/85914375/201434252-81c4bea1-93e8-44c0-857c-b28f6cd9867a.png)

![image](https://user-images.githubusercontent.com/85914375/201434261-6920e282-d4c7-4a4b-a479-d8d3125a2698.png)

![image](https://user-images.githubusercontent.com/85914375/201434274-4a1aa54a-847e-49f9-aff6-c1fb9bf8e08c.png)

### Reproduction steps

Shoot through a open door with a revolver, smg, whatever is hitscan.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/592fbef1fd16dccfd3ff1f41393b1fc40415cd36

**Comment by Lithosagym** [comment]
Tested, hitscan weapons such as the Revolver, SMG, Riot Shotgun, Deadeye Carbine, and Rifle are properly able to be fired through open doors. Issue is fixed.
