### ISSUE TITLE
StatusEffect.PlaySound doesn't consider the FrequencyMultiplier of the Sound

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10339]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In many places in the code, when playing sound, no FrequencyMultiplier argument is passed in.
Not sure if it's intentional, but it makes modding a bit inconvenient.

![image](https://user-images.githubusercontent.com/73634685/201452896-78fc1195-9325-4988-9fcf-e0fc837f7099.png)
It seems that only ItemComponent has this feature

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a066b99f9faedc36872f36510827542e495a7d58

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/ec9a79ff19284f92646af6bf90405b1ea27792ae

The only issue I could spot is line 415 of reactor client code does not support frequencymultipliers still (function applyTemperatureBoost(float amount, RoundSound sound) )

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3de7b3abda56d779d97872ef5f427696c03ec8b

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/fcbf02495c0520877afe5b6dc737c3174cf631eb, no issues found, closing.
