### ISSUE TITLE
Assistant Skill: Inspiring Tunes Tooltip (and function?) only applies to Bike Horn

### ISSUE THREAD

**Issue by c33tz** [Regalis11/Barotrauma#10336]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Not sure if it was intentional or not, I assume this skill was taken right form the previous Clown Tree, but the new "Inspiring Tunes" Skill for Assistant, tooltip (and function?) seems to only mention the Bike Horn, when I imagine it should also be for instruments? (thus "Tunes")

### Reproduction steps

1. Start Multiplayer game as Assistant
2. Check Skills, Read Tooltip
3. Honk horn
4. Play Harmonica
5. Observe results.

### Bug prevalence

Happens regularly

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
We could change this to include more instruments to be less clown specific - but would require adjusting the talent description, so wouldn't be able to do it this patch anyways

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
