### ISSUE TITLE
[Faction] Ancient Weapons dont consume fuel

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10333]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Name says it all, anchient weapons dont consume alien power cells.

### Reproduction steps

1.Try using an anchient weapon, really

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/650d764bb531952feb854a86caeef20c2d380c0c

**Comment by Lithosagym** [comment]
Tested, the Ancient Weapon properly uses fuel from the Alien Power Cell. Issue is fixed.
