### ISSUE TITLE
[Faction] 40mm mini nuke just kills you

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10331]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You cannot safely shoot the 40mm mini nuke, it will explode right in your face, even in open waters.

![image](https://user-images.githubusercontent.com/85914375/201435821-a287edc9-7803-470d-94a5-18122797394f.png)

### Reproduction steps

Just try to shoot that 40mm mini nuke without combusting

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56512605046e7b43f33ff2f089c5e3824251a443

**Comment by Lithosagym** [comment]
Tested, the 40mm Mini Nuke no longer explodes immediately when fired, either inside of the submarine or in water. Issue is fixed.
