### ISSUE TITLE
MAJOR BUG AT THE START OF SINGLEPLAYER GAME FIXED! by Me!

### ISSUE THREAD

**Issue by vvFaLvv** [Regalis11/Barotrauma#10340]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/118033455/201453923-5d1dc12b-91a9-4a8b-941e-d35cbfe6611f.mp4

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
It also affect other events like "returner". I can't end the conversation. There must be something wrong with events.

**Comment by BiffW** [comment]
Tested again, it affects mission events too.

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320
