### ISSUE TITLE
(Unstable) Issues with crafting talent items (such as HMG)

### ISSUE THREAD

**Issue by EctoplasmIsGood** [Regalis11/Barotrauma#10342]
Having issues crafting items such as the heavy machine gun even though requirements are met (perk, weapons level, power, and materials).

**Comment by Regalis11** [comment]
What kind of issues?

I gave crafting the HMG a try, and can't spot any issues myself. :/
![image](https://user-images.githubusercontent.com/14351070/201468460-d30dc827-9ce5-42df-af63-89764b0a6eed.png)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/10320

**Comment by Regalis11** [comment]
No known steps to repro, closing
