### ISSUE TITLE
Wrecked sub reactors are fueled and running

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10344]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So when exploring a wrecked sub since the changes over the legacy version, youll find that the reactor will always be turned on, on automatic control with a fuel rod inside, probably because the wreck reactors are being treated by the game like regular ones. Seems unintentional 

### Reproduction steps

1.Try checking the reactor on a wreck which has one

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to reproduce this: all the reactors in vanilla wrecks seem to start in a fully destroyed state, turned off and without a fuel rod:
![image](https://user-images.githubusercontent.com/14351070/201470907-00364d45-64a0-4842-b491-611ff0951d89.png)

Do you remember if you noticed this in some specific wreck? Are you using any modded wrecks?

**Comment by Rehexr** [comment]
> I'm afraid I couldn't find a way to reproduce this: all the reactors in vanilla wrecks seem to start in a fully destroyed state, turned off and without a fuel rod: ![image](https://user-images.githubusercontent.com/14351070/201470907-00364d45-64a0-4842-b491-611ff0951d89.png)
> 
> Do you remember if you noticed this in some specific wreck? Are you using any modded wrecks?

Suppose it was a mistake on my part then, might be final mission specific, but in hindsight it couldve definitely been a mod, might be worth closing i suppose

**Comment by Rehexr** [comment]
Yeah sorry, just figured out, it was definitely a new wrecks mod, just had me confused since the wrecks were still the vanilla ones

**Comment by Rehexr** [comment]
Mod related
