### ISSUE TITLE
Shotguns and Scrap cannon have significantly poorer accuracy than indicated.

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10354]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The way shotgun spread is handled in the game appears to cause accuracy to be much more off than it really is told through the crosshair. It appears that for some reason, the spread indicated by the crosshair is actually choosing the origin of the cone of the pellets, instead of it being centered and the spread within the crosshair. This means two things are a factor of accuracy, which is where the cone originates, and the randomness of the pellet spread. In game, this causes accuracy of all shotguns to be WAY off, going completely up or down with no respect to where the crosshair is. Weapon skill nor Expert Commando has basically no regard to this effect either, so the most skilled user will still miss wildly.

Normal shotgun with weapon skill 100
![image](https://user-images.githubusercontent.com/85914375/201492988-74bc7163-03e2-4339-81fa-add41cee10a2.png)

Autoshotgun with weapon skill 100
![image](https://user-images.githubusercontent.com/85914375/201493020-a654fc9b-a395-49a6-a9b3-3a1bcfd333f5.png)

Scrap Cannon (this is just sad)
![image](https://user-images.githubusercontent.com/85914375/201492971-6a7a0104-7566-4eb7-a8b3-e0dd5f4b652d.png)

### Reproduction steps

Shoot shotgun, autoshotgun, boomstick, or scrap cannon for a bit, see the horrendous accuracy. Try with weapon 100 and Expert Commando to be even more disappointed.

### Bug prevalence

Happens regularly

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
The WEAPON itself has a spead (the deviation), and the AMMO also has a spread

`   <RangedWeapon barrelpos="80,5" spread="1" unskilledspread="10" combatPriority="80" reload="1" drawhudwhenequipped="true" crosshairscale="0.2">`

`    <Projectile characterusable="false" hitscan="true" hitscancount="8" removeonhit="true" spread="15">`

It explains why instead of having a very big fan of pellets, you get a localized cluster at weird angles. 

In purple the spread of the gun itself
In yellow the potential spread of the ammunition

![image](https://user-images.githubusercontent.com/73229309/201498790-68ba0325-1d9a-43e9-9e93-f6bedbe872a9.png)

Shotguns just need less spread?

**Comment by Abkim27** [comment]
I would want to not to decrease ammunition spread, because it's not making sense. Spread of shotgun needs to be heavily decrease up to point, when you have 50-80 weapon skill there will be 0 spread of shotgun.

**Comment by JeroonBosch** [comment]
For reviewers: Potentially fixed on fix/shotgun-spread branch

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be merged and closed.

**Comment by PokkeTigrex** [comment]
Tested the spread from the latest unstable today, and well...

![image](https://user-images.githubusercontent.com/85914375/204043696-69e847d7-0280-489e-b407-a39de5de4762.png)

![image](https://user-images.githubusercontent.com/85914375/204043705-287b9db1-edca-47d5-9f8c-7578412b0ca7.png)

This is all with weapon skill 100 too, now unless the patch notes lie and the fix that was done wasn't actually in, I still see major accuracy issues with these weapons. It FEELS slightly more consistently towards the middle, but I'm unsure if its just a placebo effect.
