### ISSUE TITLE
[Unstable] Bots do not gain experience during Multiplayer Campaign

### ISSUE THREAD

**Issue by JackMerideth** [Regalis11/Barotrauma#10352]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

**Expected Behavior:**
Bots also gain experience to make use of the new "Manage Talents" feature.

**Actual Behavior:**
Bots gain no experience, and thus the "Manage Talents" button is useless.

Can confirm that Bots not gaining experience is present in current stable build as well, using `setClientCharacter` command

_Current Mods are only cosmetic._

### Reproduction steps

1. start multiplayer campaign
2. recruit bots
3. finish a mission
4. check Bots' Manage Talents

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e084c067d6631a695f6512cbdb5dc522ae8b16a9

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
