### ISSUE TITLE
Scrap cannon shot origin is further in front of its barrel

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10356]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using Scrap Cannon, the pellets originate further from the barrel, which can make you miss point blank shots as they shoot behind the target.

![image](https://user-images.githubusercontent.com/85914375/201493517-09952aeb-2708-4a54-a973-13376eb49bfa.png)

### Reproduction steps

Shoot the scrap cannon

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2704fca4f7f57244da9af8f970c14e6c4a3a8303

**Comment by Lithosagym** [comment]
Tested, Scrap Cannon's pellets properly originate at the barrel and point blank shots are possible. Issue is fixed.
![image](https://i.imgur.com/jLknldU.png) ![image](https://i.imgur.com/w3k6m0D.png) 
![image](https://i.imgur.com/hlB8lRV.png) Shot goes past character at this distance
