### ISSUE TITLE
[Unstable]Acid Grenades can be triggered by Detonators but produce no effects

### ISSUE THREAD

**Issue by malcomshot** [Regalis11/Barotrauma#10355]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Was experimenting with invulnerable acid grenades as a pipe mechanic, when it didn't work I tried wiring up a button to the detonator and using a normal acid grenade. The acid grenade is consume but doesn't produce any acid at all.

### Reproduction steps

1. Place an acid grenade in a detonator
2. Trigger the detonator
3. Grenade is consumed, no acid is produced

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
It's because Acid Grenade only spawns the string of acidemitters `OnSecondaryUse  `(throw)  and not `Onbroken`

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@acf8740.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
