### ISSUE TITLE
Assistant's Graduation Ceremony gives more than one tree of skills 

### ISSUE THREAD

**Issue by VibeMasta** [Regalis11/Barotrauma#10351]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I select any apprenticeship and get the graduation ceremony perk, it gives me two trees instead of one. 

### Reproduction steps

1. Load into campaign/ sandbox 
2. Give yourself 99999 exp
3. Get any apprenticeship and get the graduation ceremony perk
4. Find yourself with 8-12 perks (depending on apprenticeship)

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
The change seems to have fix this

**Comment by 3e849f2e5c** [comment]
The change seems to have fix this

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b

The issue does not appear to be fixed. I chose engineer and graduated with it on an AI assistant in Multiplayer campaign, and got a total of 10 skills. 

Server console showed this too:
![image](https://user-images.githubusercontent.com/29177976/204569641-a0455cb3-533a-4922-836f-2da1a77b31e6.png)

Perhaps a multiplayer syncing issue is at play and only one tree actually unlocked. as changing location went from 10 talents unlocked to 5 (which is one whole tree of the engineer in count, including the exclusive picks).

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/af365c39614ac023871cf6c9e3edbaf4ea362ef3

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf

Looks like the fix hasn't worked in the current release version, still getting double copies in multiplayer:

![image](https://user-images.githubusercontent.com/29177976/207294684-b5efe171-3ca3-43fc-9469-368e4d854912.png)

![image](https://user-images.githubusercontent.com/29177976/207294952-9032b637-683b-4150-ad42-74245ce0b467.png)

**Comment by 3e849f2e5c** [comment]
Hopefully fixed for good this time in https://github.com/Regalis11/Barotrauma-development/commit/dd209a4dfa8ca6ab479c175ce28fee394ad3a317

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
