### ISSUE TITLE
Arc emitter can collateral allies (and non allies) in a very large area too easily

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10358]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Arc emitter feels like a massive AOE surrounding the user instead of being concentrated towards where they are aiming. You could be aiming in a direction where no one is, and have people be basically off screen in the opposite direction, and still get hit regardless. 

Bots being at the edge of my screen getting hit despite aiming away and being decently far.
![image](https://user-images.githubusercontent.com/85914375/201494187-ee91a0e2-61e1-4fc1-a581-aba139cb3c0e.png)

![image](https://user-images.githubusercontent.com/85914375/201494221-b36fb196-13b0-408a-ad05-05c1e5330e7b.png)

### Reproduction steps

Use the arc emitter, looking away from a bot or whatever, even better in a different room and a bit off screen. There's a very good chance shooting it will knock them out anyway.

### Bug prevalence

Happens regularly

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/95813b24dc5fcfd182d7bc1814012ecc8b62663a

**Comment by Lithosagym** [comment]
Tested, the Arc Emitter no longer hits other characters that are in the opposite direction or in a large area near the firing of the arc emitter. Issue appears to be fixed.

**Comment by Rokvach** [comment]
Closing.
