### ISSUE TITLE
[Factions] Flak Cannon ammo is always overstocked

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10357]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ive noticed that outposts, especially right at the start of a campaign, will always be overstocked in Flak ammuniton boxes, featuring 3 of each kind of Flak box right at the start of the campaign. In comparison to railgun shells, of which also 3 spawn, this is a lot and considering the fact that explosive ones are also included, seems unintentional, since coilgun ammo is not available in the same way. 
![image](https://user-images.githubusercontent.com/104232152/201494058-d0ae95bc-21f2-474f-83c8-d78b915ee549.png)

### Reproduction steps

1.Start campaign and visit general shop
2.Look for flak ammo boxes
3.Note the fact that overall 9 boxes of ammo are available, much more than for any other kind of turret

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by PokkeTigrex** [comment]
I think this is an issue in stable as well, the basic outpost were selling flak ammo.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c02d2d9d5b4c5c868c9e61700c1c0c7ea09200b5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
