### ISSUE TITLE
Setting a reactor's condition to 0 in the sub editor causes it to explode

### ISSUE THREAD

**Issue by Just-Jamess** [Regalis11/Barotrauma#1035]
- [X] I have searched the issue tracker to check if the issue has already been reported.

Essentially, whenever I save and load a submarine, I come back and it has blue gaps all over the rear of the submarine. This causes, once you load into the game, the rear hull to be destroyed by gaps and for the submarine to instantly sink. Not a great deal for gameplay.

As far as I can think, I believe the issue may be related to putting the reactor's condition to 0 while in the sub designer and then putting it back up to 100. The gaps look to me like a reactor meltdown explosion on the rear of the submarine.

Windows 10, Barotrauma Open Alpha Steam Version

**Comment by EdusFF** [comment]
Fixed in d038072
