### ISSUE TITLE
[Factions] Research Beacons dont produce power

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10363]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The special alien version of the Water generator beacon does not currently generate any power, so will simply use up exisiting battery power with no way to recharge, seems a result of it seemingly being unfinished in general, considering the light components simply floating in the air
Also the alien generator thats supposed to make the power doesnt have anything in it

### Reproduction steps

1.Go and check the alien Beacons wiring, it doesnt generate anything

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0eb581a8ee07f373ebac4fc1212732199965fa89

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
