### ISSUE TITLE
[Factions] Random Empty Store slots

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10364]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/201496420-4b1cab7a-f754-4440-b0df-93e3a00d3cca.png)
When entering a seperatist outpost, ive come to notice the fact that theres two random empty slots in the store, right after the discount. My best guess is that its related to something like the traveling salesman trait, a trait i dont have here.

### Reproduction steps

Currently not very aware of what caused this

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. Did it happen in single player or multiplayer? Could it be that other players/bots might have talents that affect the stores?

**Comment by Rehexr** [comment]
Thanks for the response.
Initially ive strugged to replicate this, but i believe ive found the reason for this. Being that you have a medic in your crew, but one who doesnt have the Blackmail Genes Trait, likely leaving the Genetic material to be "Hidden" and leaving empty slots.
Also as to answer the question, i was playing singleplayer and did not have any bots that have any talents related to stores

**Comment by Rehexr** [comment]
![image](https://user-images.githubusercontent.com/104232152/202278891-2dd5aa11-bb2e-41d4-ab84-308f82f3e2a6.png)
Though the number of empty Slots isnt the same, probably related to stocking per store

**Comment by feru7** [comment]
The same happened to me on the current unstable branch in single player. It seemingly occurs completely random. I also did not have the "Traveling Tradesman" perk and no medic in my crew.

**Comment by Regalis11** [comment]
Ran into this myself now: it seems the issue was that genetic materials were being selected as daily specials, but they wouldn't be visible in the interface unless you had the "Blackmarket Genes" talent.

[Save 69.zip](https://github.com/Regalis11/Barotrauma/files/10075131/Save.69.zip)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
