### ISSUE TITLE
[Unstable] Acid grenades have no effect on Ballast Flora

### ISSUE THREAD

**Issue by malcomshot** [Regalis11/Barotrauma#10366]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whether in water or with the ballast drained acid grenades don't have any effect on Ballast Flora

### Reproduction steps

1. Be infected with Ballast Flora
2. Use a 40mm/Normal Acid grenade on the ballast flora
3. Ballast flora takes no damage

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by PokkeTigrex** [comment]
To be fair, ballast flora literally releases acidic clouds when you try to burn it. I don't think using the same thing against that would work.
