### ISSUE TITLE
[Factions] Double beacon markers on research beacon

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10362]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When taking a beacon mission and getting the special alien beacon, itll show up as two map markers, for some reason (Upon further elaboration, its clearly the sonar beacon placed at the foot of it)
![image](https://user-images.githubusercontent.com/104232152/201495641-b88508ad-ccae-42be-982d-20821062d8c1.png)

### Reproduction steps

1.Find the special Alien Beacon during a Beacon mission
2.Note the fact that two map markers appear, one at the regular display another seemingly at the alien structure

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The issue here is the beacon shouldn't be spawning in beacon missions in the first place, fixed in https://github.com/Regalis11/Barotrauma-development/commit/59c143f

**Comment by Rehexr** [comment]
Fixed up when i tried it, so closing it
