### ISSUE TITLE
[UNSTABLE BRANCH] handheld sonar kills multiplayer sessions

### ISSUE THREAD

**Issue by begginfokillz** [Regalis11/Barotrauma#10376]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

whenever a base game and/or custom sub is used in current unstable branch, game will freak the fuck out and kill the coop session, giving a multitude of errors at a single time

### Reproduction steps

step 1: set up multiplayer
step 2: start a campaign
step 3: kill game and crash

### Bug prevalence

Happens regularly

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not entirely sure I understand the issue (nor could I spot any problems myself when giving the handheld sonar a test in multiplayer). Is there a problem with the handheld sonar specifically, even though you didn't mention it in the reproduction steps? Do you need to do something specific with it for the error to occur? It's also unclear to me if this crashes the game or not, in the description you say it leads to what I presume are console errors, but in the reproduction steps you say it crashes the game? Would it possible to send us a screenshot of the errors or the crash report if the game does crash?

Thanks, and sorry for the inconvenience!

**Comment by Regalis11** [comment]
Insufficient information to diagnose this, closing
