### ISSUE TITLE
Non-Threatening doesn't work if you're wearing Provocative items

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10375]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/73229309/201544282-7f83a7ec-2a7b-43d3-9c69-eab76de76efa.png)

Enemies will ignore YOU, the human, but will attack any item you wear that is provocative.

**This includes diving suits**, flashlights, flares, sonar beacons, and even some weapons that have `aitarget`

Once you take off the diving suit (with godmode on), enemies will properly ignore you

### Version

0.20.5.0 (Unstable)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@7300b3b (bugfixes). Also affects the "survival package" talent.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
