### ISSUE TITLE
[Unstable] Gunsmith talent for captain does not grant Revolver recipe.

### ISSUE THREAD

**Issue by SKie72** [Regalis11/Barotrauma#10378]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Took the gunsmith talent, can craft revolver rounds but no revolver itself as the recipe does not show up in the fabricator.

### Reproduction steps

1. Start any campaign as Captain
2. Pick gunsmith Talent
3. Search for revolver recipe.

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/37e4a762d35edf1b922c24b531c6615d495f3d7e

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
