### ISSUE TITLE
Talent reset on captains "Skipper" tree with game load

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#10381]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Occured on WIP branch (Version 0.20.5.0)

Reloading a campaign save with the following talents selected caused the following error and reset the talents:

![image](https://user-images.githubusercontent.com/29177976/201642013-afe13085-15a4-4398-a985-48a4818bb1a2.png)

![image](https://user-images.githubusercontent.com/29177976/201642029-c397093f-5b9a-4d21-a1e0-7ee9bf5217e2.png)

### Reproduction steps

In a campaign, as a campaign select the Talents above.

When reloading the save or moving to a new location, it should throw the console error and reset all talent choices refunding the points.

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
Same with assistant's middle talent tree.

**Comment by 3e849f2e5c** [comment]
Seems to have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/f85ffdb4a3c6b7c94f52b2da87992df07c550c1a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
