### ISSUE TITLE
[Unstable] Ladder in Engineeringmodule_01_colony misaligned, causes bots to fall

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10386]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This ladder in Engineeringmodule_01_colony causes bots to fall repeatedly

![image](https://user-images.githubusercontent.com/73229309/201719933-7fb5ed90-0168-4481-9c54-d37364d95a62.png)

https://discord.com/channels/103209684680323072/540532000860143616/1041756698110603344

### Version

0.20.6.0 (Unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8d5e2d03f865cb730cd62a74f9c7dd75e4bf31ff

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
