### ISSUE TITLE
Emergency Response's description is wrong

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10380]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The second part of the description for Emergency Response is "You move 40% faster if any crew member on the submarine is in need of CPR."

In testing, the crew member neither needs to be on the submarine, nor in need of CPR for the bonus to come into effect.
The description should probably be reworded to reflect this; something along the lines of "You move 40% faster if any crew member is unconscious."

### Bug prevalence

Happens every time I play

### Version

0.20.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a4bbd7d28f30e960f976b27d1f7ee27456a9a1e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
