### ISSUE TITLE
[Factions] Specific vending machine gets filled with outpost items in output

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10388]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A very specific vending machinee, on a city module, will always have some kind of engineering item in the output. Specifically the first vending machine in engineeringmodule_01, as it uses the improper tags, being vendingmachine,locker,container,outpostengcab. Please note that this also happens in variants of the module, like the clown variant etc.
![image](https://user-images.githubusercontent.com/104232152/201721067-491d4e0a-6edb-4bf2-a073-fb25eb9e97b9.png)

### Reproduction steps

1.Spawn into a city outpost
2.Check the vending machine of engineeringmodule_01

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cc74dee1905ed7d363f47291d6dffc337acd9c66

**Comment by Rehexr** [comment]
Patched and working as should be, so im closing it
