### ISSUE TITLE
Unreachable mission minerals in cave

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#10387]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Minerals required for a mining mission are unreachable behind solid walls in a cave.

In game:
![image](https://user-images.githubusercontent.com/67431770/201720666-c08e47c4-e6e2-4de7-8891-0b415e8d1b10.png)

Level editor w/ debugdraw:
![image](https://user-images.githubusercontent.com/67431770/201721105-f0737497-002b-4857-9a3a-5be4cb372c5f.png)

### Reproduction steps

1. Open level editor.
2. Enter parameters as in the console output below.
3. Select ```rockcave``` for the cave parameters.
4. Select ```Humpback``` as the submarine.
5. Enable debugdraw to view the wall collision of the cave.

**Console Output:**
```
Level seed: ErlangshenAttis
Level generation params: coldcavernsadvanced
Adjacent locations: Outpost, Outpost
Mirrored: false
Level size: 142000x70000
Minimum main path width: 6500
```

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment]
Kind of a similiar problem on unstable/factiontest. Mission minerals are actually on the left side of the level wall (outside the lvl)
save:
[bugreport_mineraltargetoutsidelvl.zip](https://github.com/Regalis11/Barotrauma/files/10024845/bugreport_mineraltargetoutsidelvl.zip)


![image](https://user-images.githubusercontent.com/59519434/202268082-dc1b5a45-1b8f-4cf1-a237-28619e439c58.png)

**Comment by Jade-Harleyy** [comment]
Happened to me again too:
![image](https://user-images.githubusercontent.com/67431770/204077005-455ef6cf-cad9-4e45-9117-65e9de013113.png)
Submarine being used is vanilla humpback.
Mod used in the picture is [Frith's Biomes Patch](https://steamcommunity.com/sharedfiles/filedetails/?id=2841269801).

**Comment by Regalis11** [comment]
Fixed the 1st issue in https://github.com/Regalis11/Barotrauma-development/commit/f7a86683042d09bab900324821b43d60a18d1990 and the 2nd issue in https://github.com/Regalis11/Barotrauma-development/commit/4169769c3198c77d2c6b1f1d8a08a7992469a5cf
