### ISSUE TITLE
Quickfixer provides a much bigger speed boost than just 20%

### ISSUE THREAD

**Issue by Momonii** [Regalis11/Barotrauma#10394]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Quickfixer's speed boost is extremely fast, way beyond 20% 

### Reproduction steps

1. Start a campaign
2. Unlock Quickfixer
3. Fix a Mechanical object
4. Break the sound barrier

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Momonii** [comment]
> Doesn't seem to be related to the exosuit, Quickfixer's speed boost is just way too high (20, which was probably meant to be 20% - now it's a multiplier of x20)

Will try to recreate the bug when I'm free and rename the report to reflect it

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
