### ISSUE TITLE
[Factions] Hair Appearing under hats

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10396]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When transitioning between levels, sometimes a players hair will be visible beneath any hat theyre wearing, which seems unintentional, as some hair styles stand out from it.  However, this hasnt happened each time ive tried this. Even re-eqiupping the hat doesnt reset this
![image](https://user-images.githubusercontent.com/104232152/201755107-83f5cf9d-d961-41bd-bfc3-2b6d46433843.png)

### Reproduction steps

1.Have a character with a hat, prefferably with big hair
2.Transition from one level to another
3.Notice the hair, clipping out of the hat

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@f599904. Was able to repro only after loading a save, but that was consistent.

**Comment by Rehexr** [comment]
Havent had this issue since the current version of the branch, so certainly fixed, no point in keeping this up

**Comment by itchyOwl** [comment]
Great, if it seems to be fixed! But please don't close the tickets on your own. Our QA handles it.

**Comment by Rokvach** [comment]
No issues, closing.
