### ISSUE TITLE
Campaign tutorial fails to complete "Operate Turret" if done in the listed order

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#10390]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the campaign tutorial Operate turret does not complete successfully if objectives are done in the order presented.

The issue appears to be because the CheckOrderAction.cs defaults to OrderPriority.Top instead of OrderPriority.Any (Checking only the first most objective, disregarding if its the active objective or not).

![image](https://user-images.githubusercontent.com/29177976/201724966-50ba8f42-365a-4a7d-a027-c372b4d9a31b.png)

### Reproduction steps

Create a new campaign with the tutorial on
leave the station
Set the orders for crew in the order presented (Reactor, fix leaks, repair electrical, repair mechanical)
Once ordering operate turret, find it doesn't complete.
Re-order so Operate turret is first (or remove all other orders and order a turret operated again) will seemingly complete the objective.

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@c1db0ee. Default value is now OrderPriority.Any.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/c8ceeef48ec332d821d71a3a61df167f473a313b, no issues found, closing.
