### ISSUE TITLE
[Factions] Fiber Plants sometimes just turn into material sprite sheets

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10392]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unsure what causes this, since its inconsistent every load, but placed fiber plant will often use part if the sprite sheet for materials. 
![image](https://user-images.githubusercontent.com/104232152/201737651-60c05c35-50c8-4a00-ae53-e5c401a8165d.png)

### Reproduction steps

1.Repeatedly load into a sub with fiber plants placed
2.Do that until the issue arrises

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
![image](https://user-images.githubusercontent.com/73229309/201739018-c9372293-347c-4123-a2ab-40f0a8aaf2b0.png)

`<DecorativeSprite texture="Content/Items/Materials/Minerals.png" depth="0.4" sourcerect="810,893,173,131" offset="0,-40" randomrotation="-20,20" origin="0.5,0.5" />`

**Comment by NamAnhLe** [comment]
Pushed a fix in 35c8d70

**Comment by Rehexr** [comment]
Id probably notice if this wasnt patched, but it sure is, closing it
