### ISSUE TITLE
[Factions] Visual Ragdolling while navigating and sitting

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10393]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some reason, when moving the sub, navigating it while sitting, your character will occasionally visually ragdoll, although it is purely visual, as you dont get stunned. This happens especially when moving fairly quickly.

### Reproduction steps

1.Click on a chair
2.While walking towards the chair, click on the nav terminal, before actually sitting down
3.Find your character randomly ragdolling occasionally, then sitting back in the chair

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Yeah this still persists, far from a large issue but a bit funny seeing others do it. 

https://user-images.githubusercontent.com/104232152/220165802-cffc785a-d23b-4198-986f-feda1d211707.mp4

**Comment by Jasontti** [comment]
Related to: https://github.com/Regalis11/Barotrauma/issues/12580
Closing ticket
