### ISSUE TITLE
Unable to craft higher than GOOD quality tools

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#10408]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mechanic crafting quality does not go above "**GOOD**" when crafting tools even with 80+ skill AND **Tool Maintenance** activated.

### Reproduction steps

1. Get mechanic skill to lvl 85
2. Activate "Tool Maintenance" talent
3. Try to craft a tool e.g. Welding Tool

e.g. 
![untable 02060_bugged crafting quality](https://user-images.githubusercontent.com/58775950/201963964-2c050f13-bf15-438f-adb5-b9d21cfdca4e.jpg)

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/38fce57d0329ecfc3faf0d12bb21da976780f75f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
