### ISSUE TITLE
[Unstable] Danger Zone uses "multiplier" instead of "resistance"

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10405]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Danger Zone XML uses "multiplier" instead of "resistance", does nothing

`        <CharacterAbilityModifyResistance  resistanceid="radiationsickness" multiplier="0.5"/>`

Could also be a side effect of https://github.com/Regalis11/Barotrauma/issues/10403

### Version

0.20.6.0 (Unstable)

**Comment by 3e849f2e5c** [comment]
Seems to be already fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f4188a52b8233765bc871b2d64cc8c6c5b4a8e4

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
