### ISSUE TITLE
(Unstable) Low repair threshold on multiple subs engines slowing them down

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#10407]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Multiple subs engines have a repair threshold of 50 which makes you unable to repair the engine for a long time causing the subs to not be able to reach their top speeds.

Barsuk:
![Barsuk1](https://user-images.githubusercontent.com/86321358/201900208-80133d36-37e8-46cb-bd92-992f8bbf990c.png)
![Barsuk2](https://user-images.githubusercontent.com/86321358/201900225-da416a99-12a4-43a0-89c3-b962c63b87de.png)

Camel:
![Camel1](https://user-images.githubusercontent.com/86321358/201900324-e2cb96f5-78e8-4390-a7c8-00baf999fb9d.png)
![Camel2](https://user-images.githubusercontent.com/86321358/201900337-66b79832-5c8c-41b2-a84a-429d4d959a47.png)

Herja (both engines):
![Herja1](https://user-images.githubusercontent.com/86321358/201900396-1c1473e0-c180-44f8-ad88-735c8c035dce.png)
![Herja2](https://user-images.githubusercontent.com/86321358/201900409-4b2847f1-ba40-4c38-a56d-e9a53e545eb8.png)

Orca 2:
![Orca21](https://user-images.githubusercontent.com/86321358/201900568-b0193056-cb11-433d-a23b-00299073dfb7.png)
![Orca22](https://user-images.githubusercontent.com/86321358/201900577-b41c55c9-36c6-43e9-8053-62b892daabbd.png)

R-29:
![R291](https://user-images.githubusercontent.com/86321358/201900679-1062b805-4970-4850-886c-5dda6c9eee8b.png)
![R292](https://user-images.githubusercontent.com/86321358/201900693-ce7fbf14-f072-4183-ba04-812f4e0fda7d.png)

Remora (though only a speed loss of 1 km/h since only the aux engine has a repair threshold of 50):
![Remora1](https://user-images.githubusercontent.com/86321358/201901275-114329bc-bab2-4fd6-8a7b-3947fe40210c.png)
![Remora2](https://user-images.githubusercontent.com/86321358/201901331-6c6abd38-84b6-471f-8fac-d9b20127ab21.png)

Winterhalter (both engines):
![Winterhalter1](https://user-images.githubusercontent.com/86321358/201901356-bf0f107e-16a2-4940-a858-7cf7d5883195.png)
![Winterhalter2](https://user-images.githubusercontent.com/86321358/201901365-e9b5775d-f4cd-495f-8fe0-9b1a0d3dd08e.png)

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/82fe9357d718c9404c88366c4d5e16b03a2d17f7

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
