### ISSUE TITLE
[Factions] Husk containers seemingly produce chitin

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10401]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When looking up what huskcontainers eat, ive come to find that for some reason they also produce chitin aside from husk eggs, which doesnt seem intentional, nor make sense, really. 
![image-3](https://user-images.githubusercontent.com/104232152/201789594-03c67061-43b7-425c-a411-b2bcdc2a4509.png)

### Reproduction steps

1.Check xml of Huskcontainer

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It's a creature that rapidly grows chitinous appendages out of the host's body, so imo it makes more sense for it to produce chitin than any other creature.
