### ISSUE TITLE
[Unstable] Trickle Down / Inspiring Presence speed bonus only applies to captain

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10400]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

 Both Trickle Down / Inspiring Presence speed bonus only applies to captain.

 How it is:

```xml
    <AbilityGroupEffect abilityeffecttype="None">
      <Abilities>
        <CharacterAbilityGiveStat stattype="SwimmingSpeed" value="0.10"/>
      </Abilities>
    </AbilityGroupEffect>
```

How it should be:

```xml
    <AbilityGroupEffect abilityeffecttype="None">
      <Abilities>
        <CharacterAbilityGivePermanentStat stattype="SwimmingSpeed" value="0.10" targetallies="true"/>
      </Abilities>
    </AbilityGroupEffect>
```

Also see  #10385

### Version

0.20.6.0 (Unstable)

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.

Notes: Fixed in https://github.com/Regalis11/Barotrauma-development/commit/90a25edf4cba2c2dd5463790b629a6857f61cc3a
