### ISSUE TITLE
[Modding] Make RepairTool.UseEnvironment compatible with Propulsion's

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10406]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

`RepairTool.UseEnvironment` includes `None` EnumValue but Propulsion doesn't. If there is a status effect that's used to change `Usable`, the game will keep throwing the errors in the console.
I think it's better to add `None` for `Propulsion.UseEnvironment` to skip the `Use()` likes RepairTool.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/3850e6c21d8ed796e006aacc799f8d54f879ac34

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/aa8388e4f9e8067110ef6827b3b1760f5a2f3f97, no issues found, closing.
