### ISSUE TITLE
[UNSTABLE] Liquid Oxygenite Explodes Upon Spawning In (Dugong)

### ISSUE THREAD

**Issue by Kaktar-1** [Regalis11/Barotrauma#10411]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Crates spawning inside the Dugong spontaneously explode upon starting the map. This has happened three times in different instances now and it has all involved Liquid Oxygenite and the Dugong. It appears the liquid oxygenite spawns too high off the ground and explodes upon loading the map. Since the Assistants can spawn exactly where the crates spawn, incredible amounts of collateral damage is often devastating and unavoidable. Such as if an assistant is carrying explosives of any kind.

I would like to add this: Crates that hold nothing and come for free from outposts should despawn by round end since there might be a chance this bug is associated with all the empty crates I have sitting in the ballast.

### Reproduction steps

1: Select the Dugong sub or any other sub that spawns crates high off the ground.
2: Purchase explosives, specifically liquid oxygenite, at an outpost.

Alt 1: Stockpile a ton of crates from outposts for about ten rounds.
Alt 2: Purchase liquid oxygenite or any other physics-activated explosion and see if the crate spawns in the air, possibly due to there being "no slots" left on the ground.

### Bug prevalence

Happens regularly

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JBKlazema** [comment]
I experience the same problem with the Humpback in version 0.20.7.0 (Unstable).

**Comment by WeebCactus** [comment]
Had the same problem on camel V0.20.7.0 (Unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f0feaef298e08cfdf82f067d12564dab55b39d9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
