### ISSUE TITLE
[Factions] Alien ruin module issues

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10414]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Turns out that for some reason the walls of the doors on Alien_Entrance3 will never dissapear, not even with a module connected, leaving a wall to cut through each time its generated. 
![image](https://user-images.githubusercontent.com/104232152/202013047-383bbe6c-ea53-42c2-990d-cef79045200d.png)
![image](https://user-images.githubusercontent.com/104232152/202013162-a7a30107-00ca-4ae0-937e-6f6cd6a6ca8e.png)

### Reproduction steps

1.Generate an Alien ruin until one is generated including the Alien Entrance 3
2.Find the walls blocking the hatch to connected modules.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bfdb063b2e6ae63078b55420321dd5c5612bf6d4

**Comment by Rehexr** [comment]
Seemed to work fine testing it. Closing
