### ISSUE TITLE
[Unstable] Medical Expertise doesn't boost bandages, applies a burn/bleed heal to the entire body instead

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10429]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

 Medical Expertise doesn't boost the effectiveness of bandages, instead applies a burn/bleed heal to **the entire body** via a statuseffect
 
 How it is: 
```xml
    <AbilityGroupEffect abilityeffecttype="OnApplyTreatment">
      <Conditions>
        <AbilityConditionItem identifiers="antibleeding1" />
      </Conditions>
      <Abilities>
        <CharacterAbilityApplyStatusEffects>
          <StatusEffects>
            <!-- improve bandage effectiveness -->
            <StatusEffect tags="medical" type="OnAbility" target="UseTarget" duration="6.0">
              <ReduceAffliction type="bleeding" amount="1.5" />
              <ReduceAffliction type="burn" amount="1.5" />
            </StatusEffect>
          </StatusEffects>
        </CharacterAbilityApplyStatusEffects>
```

How it should be (1 being +30% effectiveness)
```xml
    <AbilityGroupEffect abilityeffecttype="None">
      <Conditions>
        <AbilityConditionItem identifiers="antibleeding1"/>
      </Conditions>
      <Abilities>
        <CharacterAbilityGiveStat stattype="MedicalItemApplyingMultiplier" value="0.3"/>
      </Abilities>
    </AbilityGroupEffect>
```

Default bandage does -5 burn/bleeding on a limb for 6 seconds
Statuseffect applies -1.5, so the boost is 30%

### Version

0.20.6.0 (Unstable)

**Comment by JeroonBosch** [comment]
Conditions won't work for
`<AbilityGroupEffect abilityeffecttype="None">`

Might need some additional code instead.

**Comment by JeroonBosch** [comment]
target="Limb" appeared to work in a test, moving to QA

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found, closing.
