### ISSUE TITLE
Outpost security getting stunlocked duing crawler outbreak event

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10425]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Ive had this happen each time i got the event. The stun and attack speed of the couple of crawlers get the security to be stunlocked and slowly chipped at until theyre dead, unless you step in. The video basically shows the whole issue. 

https://user-images.githubusercontent.com/104232152/202509588-30fd3c0b-03b2-4f3f-ad85-7287012657d2.mp4

### Reproduction steps

1.Try spawning the crawler outbreak event in a room with outpost security in it

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Tested this in a couple of outposts, but couldn't repro. The security seems to be fairly effective at killing the crawlers:

https://user-images.githubusercontent.com/14351070/202521328-0c90abbd-f828-46f6-aef4-86b709f026dd.mp4

I also wonder how they ended up in the docking module? In my tests, they couldn't get anywhere near that far from the research module. In fact, in the 3 tests I did, they made it outside the research module only once, and that was when they broke through the module's walls.

**Comment by Rehexr** [comment]
Good to see it doesnt always happen, but i suppose its usually just the case if they spawn in the same room as the security. Also not sure how they ended up in there, might be related to them having a bit of an odd range for spawning, often spawning when youre in a completely different room...
