### ISSUE TITLE
[Factions] Pricing on alien artifact seems off

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10421]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Come to notice that the price for alien artifacts has gotten very low since the recent update, so i did some digging, the code suggests the price should be roughly 1000mk depending on some multipliers, though the actual price doesnt come close to that, ending up at roughly 200mk (goes for all artifacts), which seems like a mistake, especially when comparing the pricing to the price of curios.
![image](https://user-images.githubusercontent.com/104232152/202315524-2de5694d-7600-4ae9-8acf-580a5702667e.png)
![image](https://user-images.githubusercontent.com/104232152/202315542-aee3f56a-89da-45ce-a543-ecf1296b78fb.png)

### Reproduction steps

1.Try to sell an alien artifact at a merchant of your choosing

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Thanks for the response, suppose i missed the sell modifier, considering that seems to be stored elsewhere, but id definitely say upping it to 0.3 would make some sense

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
