### ISSUE TITLE
Cannot select next station "Cannot continue the campaign from the previous save (round allready running)"

### ISSUE THREAD

**Issue by GrumpyPhysicist** [Regalis11/Barotrauma#10427]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At the end of a level, we where unable to select the next target.

This was a "no outpost" situation.

The server reported the message "Cannot continue from the previous save (round already running)" as a red textbox for the person attempting to select the next target on the map.

I don't know of a way to attach a save when the issue happens at the end of a running map.
I do not know how to reproduce the issue.

Dedicated server from steam, linux and windows clients.

the steam error message in the journal where empty. Messages from the round, like "player placed item in container" show up, but nothing about the issue.

I would like to also note that getting the message "round is running" when trying to end the round is: funny.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Cannot continue the campaign from the previous save (round already running)
```

**Comment by GrumpyPhysicist** [comment]
... Returning to the other side of the map and docking with the abandoned station, did not produce the same error.

The error, therefore, occoured when not docking at a station

**Comment by itchyOwl** [comment]
I'll close this one as a duplicate, because there's another ticket about it: #10457. Updated that one with the information gathered from here.
