### ISSUE TITLE
[UNSTABLE] Exosuit Drains All Oxygen in Storage When Subjected to Gas Vents

### ISSUE THREAD

**Issue by Kaktar-1** [Regalis11/Barotrauma#10423]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There's already a similar post of the Exosuit draining all the oxygen in storage but it doesn't clarify that all the oxygen in storage drains specifically when the Exosuit is hit by the gas from a Gas Vent.

### Reproduction steps

1: Wear an Exosuit and fill its inventory with oxygen tanks
2: Subject the suit to the gas of a Gas Vent

### Bug prevalence

Happens every time I play

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I wouldn't consider this a bug really: the gas vents drain any tank inside a suit, so I think it makes sense in this case too. + I think it's a nice downside for balancing the exosuit.

**Comment by AnalogKnight** [comment]
>> I think it's a nice downside for balancing the exosuit.
Just a question. If this is balance, players can avoid this by putting the oxygen tanks in their own inventory instead of the Exosuit's inventory. Should this be modified?

**Comment by AnalogKnight** [comment]
> I wouldn't consider this a bug really: the gas vents drain any tank inside a suit, so I think it makes sense in this case too. + I think it's a nice downside for balancing the exosuit.

Just a question. If this is balance, players can avoid this by putting the oxygen tanks in their own inventory instead of the Exosuit's inventory. Should this be modified?
