### ISSUE TITLE
[Factions] Resolution changes causes navigation terminal to break

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10436]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Credit for this bug goes to Nilanth.

Upon changing the resolution, the UI of the game proceeds to break as demonstrated in the image below. 

![image](https://user-images.githubusercontent.com/105495756/202828394-35f9553a-bc74-497d-aaf0-0e30da97fa45.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by evilfactory** [comment]
I can confirm that this happens on Stable v0.19.14.0 too.

**Comment by Regalis11** [comment]
Nvm, found the issue now: seems that this only happens with the wiring interface. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e507b2e97242d20039834ae0e37fc2f3208f973

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
