### ISSUE TITLE
Ballast Denizen does not work properly

### ISSUE THREAD

**Issue by WeebCactus** [Regalis11/Barotrauma#10431]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The talent Ballast Denizen does not apply it's effect properly. instead of reducing the time taken for oxygen low to build up it reduces the time taken for oxygen low to decrease when exposed to oxygen.

### Reproduction steps

Use a character without the talent and time the amount of time taken for oxygen low to increase
Do the same for a character with the talent

### Bug prevalence

Happens every now and then

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No crashes
```

**Comment by ubertpendragon** [comment]
This is the xml I used to fix it.

It's not using "holdbreathmultiplier"

```xml
    <AbilityGroupInterval>
      <Conditions>
        <AbilityConditionHasAffliction afflictionidentifier="oxygenlow" strength="lt 50" />
      </Conditions>
      <Abilities>
        <CharacterAbilityModifyResistance resistanceid="oxygenlow" resistance="0.5" />
      </Abilities>
    </AbilityGroupInterval>
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ecd0d89844377f28b2b5baf5036e30ff554c902b

**Comment by ubertpendragon** [comment]
My bad 50% of oxygenlow resistance actually doubles how long you can stay without breathing.

Increasing holding breath by 50% means a 33% resistance
