### ISSUE TITLE
Affliction infliction has a few strange issues and discrepancies with its distribution

### ISSUE THREAD

**Issue by GlitchAnims** [Regalis11/Barotrauma#10430]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

There is a strange problem on how the game applies non-limb-specific afflictions when the limb is not specified. I used mods to test different items, affliction types and affliction strengths.

![imagen](https://user-images.githubusercontent.com/38194089/202589187-73ddbbf2-917d-4a5b-98e7-6b2581d504cd.png)

Infliction follows an inconsistent but predictable distribution: Most of the affliction goes into the right arm, but some of it appears on the torso and left arm. **Head and legs remain undamaged**.

Related, using <ReduceAffliction/> did **not** have the same issue as <Affliction/>.

### Reproduction steps

Simple way to reproduce: Start a game. Shoot a Sulphuric Acid syringe into a person. The distribution issues will occur.

On the modding side of testing, I was able to properly spot a few problems:
Take this for example:
```
<StatusEffect tags="medical" type="OnAbility" **target="Character"** duration="50.0">
    <Affliction identifier="bleeding" amount="4.0"/>
</StatusEffect>
```

The part in bold, the target, whether it is target="Character" OR target="UseTarget", it will have the same effect.
The affliction identifier was tested with bleed, burn and acid burn. All had very similar effects.

![imagen](https://user-images.githubusercontent.com/38194089/202589636-6ae471aa-5561-480b-bc20-99c832092570.png)
In this example, burn followed the same distribution. It seems the probabilty of the left arm getting damaged is very low and inconsistent.

### Bug prevalence

Happens regularly

### Version

0.20.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No errors or anything, as this does not crash
```

**Comment by GlitchAnims** [comment]
Part of the code piece disappeared... This is the full:
```
<StatusEffect tags="medical" type="OnAbility" target="Character" duration="50.0">
    <Affliction identifier="bleeding" amount="4.0"/>
</StatusEffect>
```

**Comment by Regalis11** [comment]
The problem here seems to be that the status effect doesn't specify which limb to apply the affliction on despite the affliction being limb-specific. Fixed Sulphuric Acid in https://github.com/Regalis11/Barotrauma-development/commit/845676dda16125b3681adb234e8c4f6d9cc72190

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/24aad1892591b07abbfdda1680c759abec9ffe9e, no issues found, closing.

Notes:

It isn't intended to use a limb-specific affliction in a none-limb specific character target. The issues with the vanilla item are resolved but this would be less of a fix and more perhaps a feature request, as well as determining what the intention of using the affliction that way - All limbs? random limb? limb a syringe hit and would be better to be explicit in the intended targetting, but that is likely a discussion for another time.
