### ISSUE TITLE
Trickle Down applies books to everyone

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10449]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue is the opposite of #10385. Where that ticket states that books apply everything to the Captain, this bug applies book bonuses to everyone. This gets quickly out of hand for obvious reasons. 

Images below demonstrates the level of chaos provided.

![image](https://user-images.githubusercontent.com/105495756/202871325-8218ca70-966e-443a-8e9c-0b68cbdb2062.png)
![image](https://user-images.githubusercontent.com/105495756/202871374-63a54269-588c-4a26-a0d9-a6ad3f871739.png)
![image](https://user-images.githubusercontent.com/105495756/202871379-ad98cc82-9163-47c7-b9b0-0116fdf3c424.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/203446421-c336c132-a81f-4284-a019-81754b9e9407.png)
Relevant image

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/69bc57475915a5ac8b4069bdb9c1eb991db707ca

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b, no issues found

I was already testing the trickle down talent for another issue while this is still in review, can confirm it is working just fine there.
