### ISSUE TITLE
Exosuit leg sprite depth covers held items

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#10445]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Exosuit leg sprite depth covers held items

### Reproduction steps

1. Get an exosuit
2. Equip a handheld item, such as diving scooter or revolver
3. aim the item
4. Notice the leg sprite depth covers up the held item

### Bug prevalence

Happens every time I play

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
Here's an image of it in action. Item used is the Heavy Wrench.

![image](https://user-images.githubusercontent.com/105495756/202923746-5dc82815-d959-41f9-9804-595ab6756858.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
