### ISSUE TITLE
Defense bot can either have a name ID card or ammo, not both

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#10448]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Please add a slot for a name card. It's cute.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@9142947.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
