### ISSUE TITLE
[Unstable] Rifle doesn't reload correctly

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#10440]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When reloading rifle, it reloads incorrectly (like how, before fix, revolver did)

### Reproduction steps

1.Grab rifle with 6 bullets
2.Press inventory button which holds 1-5 rifle bullets
3.Bullets from rifle drags out to inventory cell

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Linux

**Comment by BiffW** [comment]
Not just rifle, but also revolver, harpoon gun and riot shotgun, the bug that should have been fixed in [#8948](https://github.com/Regalis11/Barotrauma/issues/8948#issue-1213553839) long ago regenerated somehow.

**Comment by BiffW** [comment]
Different from last time, revolver quick reloading seems fine.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66d52bf9e14a8f9ef4d6a021549228c3557260db

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
