### ISSUE TITLE
[Faction] Ritual Lantern lacks the healing properties described

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10450]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The husk cult's purchasable ritual lantern describes pacifying husks and giving off mild healing properties. It is able to make husks passive but the healing doesn't appear to work. Injured myself and used the whole duration of the lantern, no afflictions went down.

### Reproduction steps

Use the lantern with injuries.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The lantern only healed organ damage and burns, but I changed it to heal all normal damage types now https://github.com/Regalis11/Barotrauma-development/commit/f22d062938fdd73f36899e2b009723fdd20d5e01

**Comment by JeroonBosch** [comment]
Damage healing aspect works, but equipping ritual lanterns (one in each hand when I tested) prevents unconscious people from dying. Probably not intended?

**Comment by Regalis11** [comment]
Tested with the same afflictions as @JeroonBosch, and I don't think there's actually an issue there.  If the character just has the oxygenlow affliction, the ritual lantern won't prevent them from dying. But if they have some afflictions that are affected by the lantern, their health will not drop because the healing will compensate for the increasing oxygenlow affliction.

**Comment by JeroonBosch** [comment]
Tested following cases:
- Stacking around 20 ritual lanterns on the floor: no issue, as OnActive isn't triggered so no excessive healing takes place
- Wielding a lantern in each hand: healing is also not excessive.. maybe if 10 players got together and all of them equipped 2 lanterns each there might be some stacking issue, but the healing is rather low, so I don't see a big issue here.
- Crew in need of CPR may stay alive longer, but it doesn't reduce Oxygen Low as mentioned above, so no issue
- Tested on multiple types of damage, they all seemed to be decreased over time

Closed (unless you can think of other test cases?)
