### ISSUE TITLE
[Factions] Cultist Robes overlaps with Iron Helmet

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10456]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Identical to #10308 but with a different subject.

![image](https://user-images.githubusercontent.com/105495756/202919918-fdb5bd44-12b6-4044-9f4b-05eebd733f16.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
