### ISSUE TITLE
[Unstable] Hot keys are sometimes not working

### ISSUE THREAD

**Issue by pubrrr** [Regalis11/Barotrauma#10453]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was trying the latest unstable release in single player campagne. In every other mission, the hotkeys stopped working:
* 0-9 to select item in hand did _not_ work
* H to display healt did _not_ work
* C to display crew did _not_ work
* WASD and mouse button however did work.

### Reproduction steps

Unfortunately I can't tell how to reproduce this.
* It happened 4-5 times
* It always mysteriously fixed itself, either after some time or upon docking to a station

### Bug prevalence

Happens regularly

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by pubrrr** [comment]
Maybe another data point: In longer missions, this sometimes happens multiple times. It is definitely a frequent issue. Although I cannot "reproduce" it, I can just keep playing for another 10 minutes and will happen again.

**Comment by Regalis11** [comment]
This seems to happen when you interact with elements in a listbox. This includes for example rearranging the order icons in the crew list.

**Comment by Rokvach** [comment]
Tested, this is working correctly, can be closed once the PR is merged
