### ISSUE TITLE
[Factions] Captain Hognose has no talents

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10455]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Many unique NPCs added in the faction branch have talents to allow them to stand out. Auntie Doris is one such example.  Captain Hognose has absolutely no talents. 

![image](https://user-images.githubusercontent.com/105495756/202919707-11fa73f8-92b9-47b3-ab15-14dddf7d838d.png)

It isn't clear why this unique NPC would be undeserving of talents, especially considering that he is a seasoned captain who surely has experience from his previous adventures.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/81ba7559f0ffc2e86499b4e4c7e89788cbf60df5

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Additions commit https://github.com/Regalis11/Barotrauma-development/commit/64bdfc9887d23d7c3c2b9f3d6ead0ab9836983c1, Works fine. closing

Now gets 6000 experience (No starter talents) which is equal to 4 talent picks and 1425/2450 which is fair for an early-game special recruit with no requirements than a kill monster mission.
