### ISSUE TITLE
Changing your selected outpost changes what outpost you are currently at according to the menu in tab

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10452]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon changing your desired destination in the campaign map, the in-game tab menu will change your current location depending on the location you have selected. This impacts everyone in a server and has caused several instances of confusion over where we actually are, as the mining claim we are currently docked at is named after a military outpost we haven't visited yet. 

Below are images of this issue in practice.

![image](https://user-images.githubusercontent.com/105495756/202918877-2a11a265-4d50-4005-9e7b-cc2c6466cb10.png)
_Figure 1. Tab menu showing location._

![image](https://user-images.githubusercontent.com/105495756/202918881-f9c2d58d-8cf4-44bc-bb2e-3a822da22245.png)
_Figure 2. Campaign map showing location name of node we are not in._

![image](https://user-images.githubusercontent.com/105495756/202918890-1c3490d4-bc56-402b-a04c-438786813c0c.png)
_Figure 3. Campaign map showing location of natural formation we are not in._

![image](https://user-images.githubusercontent.com/105495756/202918892-f1888d2e-ff1a-4e3c-b2f8-0886901ab0e8.png)
_Figure 4. Tab menu showing that we are in the natural formation we still have not visited._

### Reproduction steps

1. Start a campaign
2. Observe your location in the tab menu
3. Go to the map and change your destination 
4. Return to the tab menu and observe how your location has changed
5. Repeat until satisfied

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be an issue specific to the faction branch. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86c17da73fc845928336b02a8c483870d2983324

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
