### ISSUE TITLE
Alien Ruin generated an impassable invisible wall above the module

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10458]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I want to preface this by saying this has only occurred **once**. I do not have the seed this came from (it was part of a larger testing campaign which is where all these reports are coming from). There was a rather large invisible wall above an Alien Ruin which prevented any players from passing. Objects dropped on the wall caused them to slip off and fall, as if there were no flat surfaces on it. 

Below is the screenshot I took of the event. I apologise for the dark image, we didn't have much lighting gear during the raid. The rough size of the wall can be highlighted by using the left-most diver and CaithLoki. The wall is in between those two.

![image](https://user-images.githubusercontent.com/105495756/202920070-922163df-7b62-46d7-9875-781333d5074d.png)

I understand the image above is difficult to visualise the issue with, however it _is_ an invisible wall. I'm not entirely sure how I would picture something that cannot be perceived. 

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
we found another invisible wall on seed BerithKecnash in 100.6.0.0

**Comment by Wheatley1001** [comment]
**Seed: Drizzlecomb LineaSabbati Macula**:
![image](https://user-images.githubusercontent.com/105495756/204137855-54b740d1-4bde-42da-9fcb-2879416bdf13.png)

More invisible walls (and odd visuals):
![image](https://user-images.githubusercontent.com/105495756/204137887-758e33b4-bb88-4970-befe-510430061903.png)
![image](https://user-images.githubusercontent.com/105495756/204137893-d4fefcfc-6466-480e-b0da-5b30d250437f.png)

The odd visuals were completely surrounded by invisible walls. Once you got close to it, you could partially enter the wall.

**Comment by HawkinsThe71st** [comment]
Another one found while doing artifact salvage mission in 100.8.0.0

https://user-images.githubusercontent.com/115734437/205648048-7d0086b2-cf05-4429-9d97-c84296722562.mp4

![image](https://user-images.githubusercontent.com/115734437/205648242-70dbab83-b0af-4bdf-89b4-7e21dc3ce58a.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/10f734c92fd76d5ca736ffbe4adb9905883a9082

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
