### ISSUE TITLE
[Factions] Character duplication

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10451]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When playing campaign within a public server, i died midround and crashed while Spectating.
After trying to rejoin, which i couldnt, as the server had filled up, i closed the game for a while, to return later.
When i later rejoined, i rejoined as my chararcter, including all the items i had with me, as i died.
Mind that all the items were duplicated, as some other players were using that which i had on me earlier.

### Reproduction steps

(Currently havent had the chance to replicate, as it requires you to have a server hosted independently of your own, though i will describe the process ive had myself)
1.Die in a campaign hosted by another player
2.While spectating, alt f4, or alternatively force the game closed
3.Return to the campaign server, after the round has concluded, with instant respawn enabled
4.Find youve spawned with your character, as before the round you died

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
This fix doesn't seem to be working, following the exact steps we were still able to duplicate items as my old characters duffelbag contained all the items which my character spawned with, even a Fire Extinguisher which I was carrying was duplicated.

**Comment by Regalis11** [comment]
Looks like the logic still didn't work correctly if the character had despawned at the end of the round. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ebf7269c761b77a6cec2e70f9973a0d62bb1ff8
