### ISSUE TITLE
[Unstable] Can't enter station

### ISSUE THREAD

**Issue by pubrrr** [Regalis11/Barotrauma#10457]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On unstable single player campagne, I went from an unhabited location to a city. I sucessfully docked there, but then the submarine "jumped back" to the uninhabited location that I came from. I also can't select that passage again.

![grafik](https://user-images.githubusercontent.com/62142301/202919890-36411972-89f1-4b7e-a9b8-b5316f6b35c1.png)

### Reproduction steps

Screenshot from campagne loading thingy:

![grafik](https://user-images.githubusercontent.com/62142301/202919837-cb9116e4-681d-4d07-82c7-a59af9fe09c1.png)

### Bug prevalence

Just once

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Hello, thanks for the report!

Do you happen to have a save file of your campaign? On Windows you can find the files in C:\Users\username\AppData\Local\Daedalic Entertainment GmbH\Barotrauma. The AppData folder is hidden by default, but you can see it by checking the "Hidden files" on the "View" tab of the file browser: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b97c626b-6965-468a-8dc0-28dccd22940d)

If you find the save file, please pack it (e.g. with [7zip](https://www.7-zip.org/)) and upload here.

**Comment by itchyOwl** [comment]
There was another report about the same issue:

> At the end of a level, we where unable to select the next target.
> 
> This was a "no outpost" situation.
> 
> The server reported the message "Cannot continue from the previous save (round already running)" as a red textbox for the person attempting to select the next target on the map.
> 
> I don't know of a way to attach a save when the issue happens at the end of a running map.
> I do not know how to reproduce the issue.
> 
> Dedicated server from steam, linux and windows clients.
> 
> the steam error message in the journal where empty. Messages from the round, like "player placed item in container" show up, but nothing about the issue.
> 
> I would like to also note that getting the message "round is running" when trying to end the round is: funny.

**Comment by pubrrr** [comment]
@itchyOwl I've continued playing, so the save game is not in that state anymore:
[unstable1.zip](https://github.com/Regalis11/Barotrauma/files/10200232/unstable1.zip)

**Comment by Regalis11** [comment]
Thank you for the save file! I gave it a quick test, but unfortunately couldn't reproduce the issue (possibly because that uninhabited location has now become a military outpost). If anyone happens to run into it again, a campaign save done in that stuck state would most likely help us a lot in diagnosing this.
