### ISSUE TITLE
[Factions] Autoinjectors trigger prematurely

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10462]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems when using an autoinjector, it seems to apply the item when the person is below 50% Health, rather than being triggered when knocked out, meaning it activates a lot more frequently than reasonable.

### Reproduction steps

1.Equip an autoinjector with any medicine
2.Apply `giveaffliction Burn 10` in commands, or anything else that counts as damage
3.Find it triggers at 50 affliction damage and repeatedly if the injector is filled with medicine while below that bar

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is the way the autoinjectors are intended to work (injecting the meds when you're below 50% health).
