### ISSUE TITLE
Hand-injected meds cannot be used on a player if a player is in a clown crate between them.

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10466]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to inject a player through method of the hand, for example morphine being injected by stabbing them with it, does not work if a player is inside a clown crate that is between the medic and the patient. The visual imagery shows that the medic clearly hits the patient with the syringe, yet the patient does not get any benefit. The player in the clown crate, however, will get the benefits. 

This caused a problem because I wasted three syringes trying to heal someone before realising the clown crate goblin was eating them all.

![image](https://user-images.githubusercontent.com/105495756/202921801-e03b93d9-f6fb-4422-84d2-b697ea8a4282.png)
_Figure 1. Distance of player needing meds and clown crate. The player outside the clown crate cannot receive meds because of the crate._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem to be specific to the faction branch

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/addbea4ff66d2d8111c89fb5981f61357d616f81

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/aa8388e4f9e8067110ef6827b3b1760f5a2f3f97, no issues found, closing.
