### ISSUE TITLE
Disconnected players sometimes spawn dead

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10463]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a spooky one. Allow me to tell the tale of this murder mystery. 

During the first session of our testing campaign, Hexcode disconnected with the intention of sleeping. The crew made sure to keep his body in good condition so his cause of death would be "Brain Death", meaning he wouldn't lose his character. 

Upon joining the next hosting session, his body spawned dead and he was sent to the respawn queue. His cause of death was listed as "Lacerations" and he was covered in blood. This, of course, isn't how Hexcode died as demonstrated in the first paragraph. Nobody mutilated him nor was there ever a breach which caused harm to his body. 

![image](https://user-images.githubusercontent.com/105495756/202921002-0908d9b8-e91b-412b-8cff-25440843c88e.png)

Furthermore, once Hexcode respawned his body stayed behind. Typically a body will become a duffle bag once the player comes back. This has always been the case. As shown in the image below, there were two instances of Hexcode Gaming at one time. Nobody took his ID, the body was completely untouched. I cannot explain why he was naked. As I just said, nobody touched his body. His clothes were still on him when he disconnected. 

![image](https://user-images.githubusercontent.com/105495756/202921063-42d31d22-59be-46f6-8d42-380d28e8aa5a.png)

It may be possible that this issue relates to #10451, as both instances occurred in the same testing session.

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
There isn't clear enough repro steps to follow here, but we tried couple approaches and weren't able to get this to happen, its hard to tell if the issue has been fixed and thats why we weren't able to repro it or if we are just using wrong repro steps.

**Comment by Rokvach** [comment]
We tried to repro this outside of the PR too but weren't able to

**Comment by Regalis11** [comment]
Hmm, I wasn't able to repro this now either. I don't actually remember if I managed to do it when implementing that fix - looking at the commit message, I think I might've just guessed that this could be related to https://github.com/regalis11/barotrauma/issues/10451 and fix by the same commit.

**Comment by Rokvach** [comment]
As we haven't been able to reproduce this issue again and there is no mention of it happening for awhile now I don't see the need to keep this ticket open. Can be opened if someone happens to come across the issue again, until then. Closing.

**Comment by Vykn** [comment]
Did some multiplayer respawn testing today and found steps to reproduce:

1. have a player disconnect during a level
2. wait until they go braindead
3. chop up the braindead corpse (we used ceremonial swords, but presumably any damage source will do)
4. dock/transition to a different level
5. have the player reconnect
6. when they spawn in, they will die instantly

I'm assuming that whatever damage is applied to the braindead corpse is saved to the character, so when they spawn in they just receive it all. Didn't test for non-lethal damage, though.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d24c3e463d01fbcf4702ff323e9f252a81896b51

**Comment by giists** [comment]
No issues found, closing.
