### ISSUE TITLE
Rough visuals on water flooding in with tall hulls

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10469]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue has been a thing for a long while now, and while strictly visual and just slightly annoying, i felt its worth a report regardless.
So, when a hull with a tall wall is being flooded and it flows off immediately, the water will always end up with a visually irritating flickering and "jumping" up and down. Included a sub file in the zip to demonstrate this issue.

https://user-images.githubusercontent.com/104232152/202922516-c5243e80-169f-403c-ba5a-8d02a3684a1b.mp4

[Spiking Water demonstration.zip](https://github.com/Regalis11/Barotrauma/files/10050552/Spiking.Water.demonstration.zip)

### Reproduction steps

1.Cut the wall connected to a tall hull, as to make water flood in
2.Note that if the room isnt filling up, though still flooding in, it will repeatedly be visually jittering up and down (I included a sub file to demonstrate this issue)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9ce72c7ebfc7923bcb1a1f5c650e8507c01b391

**Comment by Rehexr** [comment]
Works nicely now, so im closing it
