### ISSUE TITLE
[Factions] Clear Ruin mission gives no reputation reward.

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10467]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Completing a Clear Ruins mission provides absolutely no reputational benefit. Money rewards pay out as expected.

![image](https://user-images.githubusercontent.com/105495756/202921994-2da3661d-e2e9-4310-9659-9adb9aeb3af7.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d85c97e80f4fa028339aaceca7388fde59229f2

**Comment by JeroonBosch** [comment]
Tested, no issues found (moving from separatist station, where I obtained the mission, to coalition station)

**Comment by JeroonBosch** [comment]
Unsure how to reproduce. @Regalis11 mentioned I need a location without any faction to start the mission? But in that case:
1. why would it be a bug to not get any faction reputation?
2. every location has a faction?

**Comment by JeroonBosch** [comment]
Tested it again ensuring in the debugger than Locations[0].Faction == null before trying. Couldn't run into any cases where I did not get reputation, so closing
