### ISSUE TITLE
[Factions] Players inside the Clown Crate can interact with players outside the Clown Crate

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10464]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Players hiding within the Clown Crate can access the health menu of nearby players. This allows players to inject other players with potentially harmful substances in complete stealth. 

![image](https://user-images.githubusercontent.com/105495756/202921327-c362222e-d15f-44ea-bec5-a2ed639e8843.png)
_Figure 1. Medic (me) getting grabbed by a player inside a clown crate._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/69489d57bd91fbf99d3bf0b8e70f9dee6bda7af8
