### ISSUE TITLE
Scrap Cannon is hardly visible when stored on the back

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10473]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The scrap cannon sprite is essentially invisible when stored on the back of a player.

![image](https://user-images.githubusercontent.com/105495756/202924377-c7db92a4-552c-4bdf-b08e-c9e71fd7a6d8.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/bef4cf3280dbcc8545395dc0d0476df768546442

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
