### ISSUE TITLE
Reset position does nothing

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10476]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I moved the Status Monitor display to see if I could find a position that worked better for me. After a while I wanted to reset its position. Upon clicking the reset position button, nothing happened.

![image](https://user-images.githubusercontent.com/105495756/202922954-f2c13d34-7cbe-40ef-94ea-4e63d4818631.png)
![image](https://user-images.githubusercontent.com/105495756/202922958-f4c2d489-4d8c-485e-9174-91b1081d77d1.png)
![image](https://user-images.githubusercontent.com/105495756/202922962-d4cc8293-bfd5-4535-ad9d-3a16b0bfaced.png)

### Reproduction steps

1. Move the status monitor's display
2. Click reset position
3. Observe nothing changing

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6da75aff9983f79cadba09a66636114e68e1b33

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
