### ISSUE TITLE
[Factions] Guardian weapon never despawns if the guardian's arm gets severed

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10479]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During a ruin mission, one of the Ruin Guardians actively attempted to board the submarine (successfully) and was killed inside. The steam cannon part of its arm was severed. Over the course of 16 hours and two separate sessions, the limb never despawned as captured below.

![image](https://user-images.githubusercontent.com/105495756/202919815-b5bc4381-4c1b-42cc-831b-4eb99d819acd.png)
_Figure 1. First instance of severed limb._

![image](https://user-images.githubusercontent.com/105495756/202919823-c84aa533-4ff2-4795-9436-361c2b827a94.png)
_Figure 2. Another player encounters the severed limb._

![image](https://user-images.githubusercontent.com/105495756/202919990-208620e0-9fc2-40d3-b96f-ed4efc26c089.png)
_Figure 3. A second instance of the severed limb, encountered five nodes after instance one._

![image](https://user-images.githubusercontent.com/105495756/202920238-446ce5d5-52a0-4b43-befa-4f1c77988e8c.png)
_Figure 4. The lovely Jade Harley's highlight of the Alien Ruin arm from the previous image._

![image](https://user-images.githubusercontent.com/105495756/202921481-df5dffe1-e587-406c-b21d-306d547d4a49.png)
_Figure 5. The same limb being on the sub a day later after the server had been closed and reopened._

It is also important to note that the Guardian boarding the submarine might not be a bug. As of 0.19.14.0, it cannot board the submarine. This may have been changed during one of the unstable builds.

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by PokkeTigrex** [comment]
Its not actually a limb, but the item the ruin guardians uses. Its uninteractable though so you can't do anything with it and its basically stuck in the sub forever.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/239058fda6a6c3141075ef0b0d2c79173f87b828

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
