### ISSUE TITLE
Slight inconsistencies between syringe sprites

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10471]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Again, another nitpick really, but the syringe sprites for `Europabrew` and `Sulphuric Acid Syringe` dont allign with the other syringe sprites, especially noticable with Europabrew, being a sprite thats a lot larger than the others.
![image](https://user-images.githubusercontent.com/104232152/202923093-c195bfc8-d1a1-4f36-adbc-87e2c0911b0e.png)

### Reproduction steps

1.Try looking at the syringe sprites next to each other

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
No issues, closing.
