### ISSUE TITLE
Saltvine is a two handed item until it isn't

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10470]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you equip a Saltvine fruit using a number key, you will equip the fruit like normal. If you then press the same number key again, you will now have the fruit as a two handed item. If you press the key for a third time, it will return to a one handed item but you will automatically stop holding the item after roughly 1-2 seconds. 

![image](https://user-images.githubusercontent.com/105495756/202922387-05b0ad28-4251-4e41-9043-e50f6b7d0c7a.png)
![image](https://user-images.githubusercontent.com/105495756/202922391-c5fe155a-a638-49cc-b6ae-016012b9f84b.png)

### Reproduction steps

1. Obtain a saltvine fruit
2. Press a number key to equip the fruit (for this example, we will use number 2)
3. Press 2 again whilst the fruit is still equipped 
4. Observe how the fruit is now a two handed item
5. Press 2 again
6. Observe how the fruit returns to one handed item status
7. Wait 1-2 seconds and observe how the game refuses to let you hold the fruit for any longer

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
100.6.0.0

Same issue happens with Mutated Raptor Bane. Identical steps to reproduce.
![image](https://user-images.githubusercontent.com/105495756/204067812-52233e71-9871-4b32-b2d3-342560fe19a4.png)
![image](https://user-images.githubusercontent.com/105495756/204067816-c20ac7e3-3b5b-419a-ad19-5197f868bc3e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dc0ee65db4055d872a135000a6237d065445fed5

> Fixed some items (plants and paints) having both a Holdable and Throwable component, which is unnecessary because Throwable is a subclass of Holdable and leads to weird inventory behavior. Also added a console warning about this.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
