### ISSUE TITLE
[Factions] You can play with the Defense Bot and it makes the sound of a happy Psilotoad

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10475]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The ability to play with the Defense Bot doesn't make sense, but it's cute. What isn't cute, however, is it making the happy Psilotoad sound when you play with it. I cannot even begin to justify how this would be possible.

![image](https://user-images.githubusercontent.com/105495756/202922991-9d63a3cd-cd6a-4e37-a357-2a4191976144.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
The sound is a placeholder. "Playing" is maybe a bit misleading name, but it has a function : it makes the bot follow you.

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@cc3bb09.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
