### ISSUE TITLE
Abandoned Outpost has gap issue which prevents waterflow

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10477]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I do not know which module this is nor do I have the seed. I also apologise for the low light level of the image, we didn't bring flashlights on the raid. 

![image](https://user-images.githubusercontent.com/105495756/202920332-c35e1ad3-3ff6-457e-867b-61314e53c835.png)
_Figure 1, The top left room has water unable to leave despite having a clear connecting staircase._ 

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dfa8bcd2a41185e4cd0d31aa68ce523e3d371738

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
