### ISSUE TITLE
[Factions] Separatist Outpost layering issues

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10478]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During testing I observed object layering issues with some of the decorative elements of the Separatist Outpost. These are the ones I have found so far, I'll report any new findings in the comments of the ticket.

![image](https://user-images.githubusercontent.com/105495756/202919378-069b1691-43e6-420d-91b7-adc9400c1611.png)
_Figure 1. Lamp post is on top of the floor._

![image](https://user-images.githubusercontent.com/105495756/202919408-f5a19d67-98f9-4842-88e2-35fc15c9f38f.png)
_Figure 2. Vent is in front of decorative elements._

![image](https://user-images.githubusercontent.com/105495756/202921257-d90749b7-4d5c-4769-8e29-75468a6a6a4d.png)
_Figure 3. Barbed wire is in front of the wall to the left (difficult to see)._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by IiroEnges** [comment]
Pushed into wip-additions branch

**Comment by Regalis11** [comment]
Found some more issues in ResidentialModule_01_Colony (there were a couple more of those lightposts with an incorrect sprite depth), fixed in https://github.com/Regalis11/Barotrauma-development/commit/73e8cec10e881b2864aa4a92fd34aad0bd7c4cac

**Comment by Wheatley1001** [comment]
Found another issue in version 100.13.0.0, same one in Figure 3 of the original report. The left barbed wire goes behind the player whilst the right barbed wire goes in front of the player (the wire looks like it's supposed to be one unit rather than two individual objects).
![image](https://user-images.githubusercontent.com/105495756/212445911-79fad1de-4f10-497d-9f46-fb858df90a13.png)

**Comment by Wheatley1001** [comment]
100.15.0.0 update

![image](https://user-images.githubusercontent.com/105495756/213842451-f2d28d92-cc68-40c6-ae62-2d7f573e730e.png)
_Figure 1. Vending machine and bin behind the wall._

![image](https://user-images.githubusercontent.com/105495756/213842456-de1592d3-c71b-410c-bdf1-e56ed10d2bac.png)
_Figure 2. Graffiti on wall but on top of staircase._

**Comment by IiroEnges** [comment]
![image.png](https://images.zenhubusercontent.com/5cc180b45e6eda2917828e55/cc1acd24-f24f-4f7e-9d61-bee5bf721392)
This is adminmodule_01_colony, and the "graffiti" is actually the light sprite of a jukebox, which is only supposed to be visible in the clown variant of the outpost. Help @Regalis11 ?

**Comment by IiroEnges** [comment]
![image.png](https://images.zenhubusercontent.com/5cc180b45e6eda2917828e55/5670ca58-f7f4-4b10-a17a-a30025b55fea)
I couldn't get the stairs to go behind the floor (without placing them behind the player character as well). I think it's a relatively minor visual hiccup, so unless there's a quick fix, maybe we should just skip them?

**Comment by Regalis11** [comment]
[I addressed the light sprite issue a while ago](https://github.com/Regalis11/Barotrauma-development/commit/e3e1afbb83b0934ee6b335e27baa8c253b6394) a when fixing https://github.com/regalis11/barotrauma/issues/10530, that should no longer be an issue in this module either.

**Comment by Regalis11** [comment]
Tested, no further issues found.

**Comment by Wheatley1001** [comment]
Found a floating vending machine in one of the medical modules. I've attached a close up and a full image shot for reference.

![image](https://user-images.githubusercontent.com/105495756/215240830-3c546970-0078-4a95-ae60-ada226d5900e.png)
![image](https://user-images.githubusercontent.com/105495756/215240846-144fe400-36cd-4e58-be48-b96d093762e1.png)

**Comment by Wheatley1001** [comment]
Found another issue, these two objects have the same sprite depth so they flash on top of each other for some clients. 

![image](https://user-images.githubusercontent.com/105495756/221011579-747aab2d-6359-45e3-b9f2-e0a872a3a882.png)
![image](https://user-images.githubusercontent.com/105495756/221011588-2d345c68-770c-440c-851c-e8d1df5bcde6.png)

I believe this is one of the entrance modules to the non-city outposts. 

Also, a question for future instances - should they be mentioned in a new ticket or continued in the comments of this one?
