### ISSUE TITLE
[Factions] You can see through walls sometimes

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10480]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sometimes when a wall is broken by creatures and then repaired, players can still see through it entirely. Other times this effect happens without any cause. It seems entirely random as to what triggers this.

Below is a compilation of random instances of see-through walls captured by different players during the testing campaign.

![image](https://user-images.githubusercontent.com/105495756/202921768-8fa1af65-baec-45aa-a7c1-5e0306bd817e.png)
_Figure 1. Caused by creatures._

![image](https://user-images.githubusercontent.com/105495756/202921969-88fb6dc7-20c0-4b02-a8ed-387f6b4487fe.png)
_Figure 2. Unknown cause._ 

![image](https://user-images.githubusercontent.com/105495756/202922353-48cf0644-719f-4e05-8ef4-5913bc556972.png)
_Figure 3. Caused by creatures._

![image](https://user-images.githubusercontent.com/105495756/202922758-b182cb96-92dc-4b74-bf3d-d4ced71a6f56.png)
_Figure 4. Unknown cause._

![image](https://user-images.githubusercontent.com/105495756/202922763-5c20de6a-d2f3-4b78-87ee-669c0935ce2d.png)
_Figure 5. Unknown cause._ 

![image](https://user-images.githubusercontent.com/105495756/202923120-9c4838bd-7021-486b-93b1-47c4aedfe2db.png)
_Figure 6. Unknown cause._ 

![image](https://user-images.githubusercontent.com/105495756/202923175-ef6a6e75-e58a-4fbc-9aea-5528d0b99433.png)
_Figure 7. Unknown cause._ 

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
Updates as of 100.6.0.0:

![image](https://user-images.githubusercontent.com/105495756/204066923-d509c51e-d79a-4bf2-9f48-83aa6c8e07bd.png)
![image](https://user-images.githubusercontent.com/105495756/204067310-0a62fa00-0728-452d-8494-fc85701fee36.png)
![image](https://user-images.githubusercontent.com/105495756/204067315-710699a7-ecd4-4c22-af8e-e679a42436cf.png)
![image](https://user-images.githubusercontent.com/105495756/204067509-aafd6592-c649-4950-8979-616fefa84ee5.png)
![image](https://user-images.githubusercontent.com/105495756/204067511-ec288433-451f-44a4-9660-647bb5bc96fc.png)

**Comment by Wheatley1001** [comment]
Had this show up again in 100.8.0.0. It seems to be server-wide rather than client-side, which may be helpful in diagnosing the issue.

![image](https://user-images.githubusercontent.com/105495756/205414506-befe44c4-d590-4e32-b348-20dd9b0a1303.png)
![image](https://user-images.githubusercontent.com/105495756/205414511-5a8a1b04-700f-4642-82f6-cdf1a4d41e60.png)

**Comment by Regalis11** [comment]
I unfortunately haven't been able to find a way to reproduce this. If anyone has a save file with one of these see-through walls, sending it to us would help a lot in diagnosing this!

**Comment by Wheatley1002** [comment]
I think I can get it to appear consistently on one of my custom sub builds. There are two sections with this issue, one being 100% and the other being 90% in terms of reliability. I'm not sure how helpful custom subs are in terms of diagnosis, but I'm hoping it provides something. Give me about a day or so and I'll do my best to send the file your way (I'm actively out of the country and have no direct access to the files).

**Comment by Wheatley1001** [comment]
100.13.0.0, present as you can see the wall through the floor (no save file because I forgor, will check custom sub thing again in the morning).
![image](https://user-images.githubusercontent.com/105495756/212445451-d284a7a9-633a-4a90-a179-1a8f4d516ff9.png)

**Comment by Caithloki** [comment]
Nother to add to the pile, custom sub. Will try to mess about with it to see if I can reproduce.
![image](https://user-images.githubusercontent.com/12504812/213197900-dffb997a-4819-438f-9e83-14cbb46d1265.png)

**Comment by Wheatley1001** [comment]
This issue consistently occurs within my custom sub "The Schism". I have attached a zip file which contains the .sub file and appropriate xml file in this comment, as well as the two sections in which this bug exists consistently. 
I hope this helps diagnose the issue! 
[The Schism.zip](https://github.com/Regalis11/Barotrauma/files/10471438/The.Schism.zip)

![image](https://user-images.githubusercontent.com/105495756/213842060-c62ae8b6-5c2b-4abb-92ca-f274d3d50890.png)
![image](https://user-images.githubusercontent.com/105495756/213842063-f611156a-38a9-4b2e-9bbd-38f16d4c0862.png)

**Comment by Traumatic-apricot** [comment]
Traumatic_apricot#6494
campaign singleplayer version: 100.15.0.0
got the same bug on a station and have the save file hopefully this can help in diagnosing it:
[test build save.zip](https://github.com/Regalis11/Barotrauma/files/10497282/test.build.save.zip)
![20230125172032_1](https://user-images.githubusercontent.com/123396519/214510637-7a11525f-2909-41d6-8853-a361eaee1ab1.jpg)
![20230125174223_1](https://user-images.githubusercontent.com/123396519/214510644-0cb43250-4c5c-4d20-934a-76626e2359bf.jpg)
