### ISSUE TITLE
Player able to sell genes without having appropriate genes on their person

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10487]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar to #10474.

My character has Tiger Thresher Genes and Hammerhead Matriarch genes combined into a single combination gene. This is installed in my Gene Splicer which is actively used on my person. I do not have any other instances of genetic material on my character.

Despite this, I am able to sell Tiger Thresher genes. I do not know where these genes have come from, but I assume they refer to the genes used by my character. This is an issue in itself, as the player should not be able to sell genetic material that is actively in use by a genetic splicer installed in the head (in the same way you cannot sell ammunition in a loaded gun).

![image](https://user-images.githubusercontent.com/105495756/202924136-8bf3c557-7527-46b6-a3b3-07264cdbf23d.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@528eb97

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
