### ISSUE TITLE
The new weapons use the same audio files as old weapons

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10481]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon firing the Rifle, I noticed it used the exact same sound files as the Shotgun. When the rifle was reloading (the time between two shots), it used the shotgun sound effect for cocking the shotgun. I am unsure if this is intentional, a placeholder, or a bug but regardless I wanted to bring it forward.

### Reproduction steps

1. Grab rifle
2. Fire rifle
3. Hear rifle 

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
It's a placeholder, but thanks for the report.

**Comment by JeroonBosch** [comment]
Goes for all new weapons, as no sounds were implemented yet, so I changed the title to include those

**Comment by Rokvach** [comment]
No issues, closing.
