### ISSUE TITLE
[Factions] Event made during previous build gave massive rep bonus

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10485]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I completed the event where the Separatists ask you to check on their buddy who has been tied up and beaten in one of the rooms. Upon completion I gained 40 reputation with the Separatists. For an event that took no skill nor effort whatsoever, it gave a higher reputation reward than four late-stage VIP transports in a single instance. Is this intentional or a leftover from an older build that wasn't adjusted to the new reputation gains?

![image](https://user-images.githubusercontent.com/105495756/202923895-f9c3d958-2da3-4b4c-83a2-a8f919b1c899.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/485b52b08a4bec84a13a32821154e57cbd709fa6

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
