### ISSUE TITLE
Recycled ammo mags do not have appropriate names

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10486]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Regular ammunition crafting recipes and recycled ammunition crafting recipes have the exact same name. There is no way to identify which is which from a glance, which is not seen in other items that can be recycled such as Welding Fuel Tanks. 

As far as I have observed, only two items have this issue, pictured below.

![image](https://user-images.githubusercontent.com/105495756/202923943-76217ece-1a6f-4b96-9ee4-1d0cf2d7aaa7.png)
_Figure 1. HMG Magazine recipes having identical names._

![image](https://user-images.githubusercontent.com/105495756/202923944-df957d9c-36c9-4f02-a6fe-6fb306e69758.png)
_Figure 2. Welding Fuel Tank to demonstrate other recycled recipes using this naming convention._

![image](https://user-images.githubusercontent.com/105495756/202923951-0296bda6-98ea-4da5-9281-9f75d350cf7d.png)
_Figure 3. Assault Rifle Magazine recipes having identical names._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
