### ISSUE TITLE
Affliction icons overlap menus

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10489]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar to issue #10332

Affliction icons overlap on menus. The example used specifically is the Motion Detector. This has not been tested on every single menu available as of writing.

![image](https://user-images.githubusercontent.com/105495756/202923253-77b70e83-33d4-4709-ae6b-2b769f7d0d00.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/708cfbef6a7cc9c8da3d325163bb379fb3013069

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
