### ISSUE TITLE
Servers are reporting vastly incorrect player counts

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1049]
I have been hosting for long periods of time aiming for 24 hour uptimes only interrupted by the server having frozen 3 times in around a 24-30 hour period.

However, I am finding that the player counts are getting incorrect very fast, causing nobody to join the server as they think its full so they don't actually try!

Having checked with a second client to examine the server list, I myself see the two server bug as expected, but the player count is 16/16, despite the servers GUI list showing me there are only 4 players.

It is likely caused by any combination of double-round start coroutines firing off causing disconnects, desync disconnects or steamworks auth disconnects. One of which is not properly being factored in causing steam player counts to not be subtracted right / connections not removed properly.

**Comment by NilanthAnimosus** [comment]
As an additional to when I first initially posted this, the reason this occurs is the steamworks does not have an implementation for cancelling a steam authentication once they leave.

I seem to have fixed it simply adding a StopAuthSession method to the steammanager, and coupling it into the disconnect/remove unauthed methods of gameserver - but I feel it might not be remotely as simple as that.
