### ISSUE TITLE
[Factions] Funbringer 3000 Anti-husk Protocol

### ISSUE THREAD

**Issue by SirNightKnight** [Regalis11/Barotrauma#10498]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Husked players who turn while wearing the Funbringer 3000 will promptly have their freshly shelled corpse be ejected from the suit. The newly born husk will then function as normal. 

If you do force the Funbringer 3000 back onto the husk, the husk will wear the suit. However, the fuel consumption rate will be drastically increased (observed to completely drain a thorium fuel rod in a few short seconds). This will then cause the husk to be immobile within the suit as there is no power.

This is inconsistent with the exosuit as husks will still be wearing the exosuit once they are born. The exosuit husk will also consume fuel at the normal rates unlike the Funbringer 3000 husks.

### Reproduction steps

1. Have a player/bot wear the Funbringer 3000
2. Infect said player/bot with husk parasites
3. Once they turn, observe how the suit will instantly eject the husk
4. Force the Funbringer 3000 back onto the husk while they are downed
5. Observe how the suit will drain fuel at a much higher rate than normal once worn by the husk

Tests were conducted in the sub-editor but I assume there would be no difference in the behaviour elsewhere.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9a6b8a29d93eda6361a6f3c277fe08639cabbd57 and https://github.com/Regalis11/Barotrauma-development/commit/bab5590ee3e14a01af9c41b0d41176e618fec2a6

**Comment by NilanthAnimosus** [comment]
Tested against Feature/WIP commit https://github.com/Regalis11/Barotrauma-development/commit/6dfdafa8986d1c5fa63059f5c1550b0f918ca134, no issues found, closing.
