### ISSUE TITLE
[Factions] Mass disconnect at the end of rounds (P2P server, "mission equality check failed")

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10497]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At the end of a round, roughly 3-7 players will be disconnected from the server and presented with the same error message. This same error message showed up when one of the players was trying to reconnect and pressed the "spectate" button. The server used was P2P and connected over steam. I have no explanations for why some players were unaffected by this issue.

Below is a series of similar error messages presented to players who were disconnected. Some were disconnected when trying to use the spectate button, others were disconnected at the end of a round. 

![image](https://user-images.githubusercontent.com/105495756/202922545-1962d010-8799-49e5-969f-53444f3dada7.png)
![image](https://user-images.githubusercontent.com/105495756/202923989-d03bd94d-35ee-480c-ae74-37795dc4f7b5.png)
![image](https://user-images.githubusercontent.com/105495756/202923129-0a5f9d83-48a2-44a5-ae66-1f035afa8abe.png)
![image](https://user-images.githubusercontent.com/105495756/202924215-fc53fb2f-185e-401b-aac6-0124931cc524.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. {Mission equality check failed. Mission count doesn't match the server (server: 1, client: 0)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 878
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 739
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 260
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 483
```

**Comment by Regalis11** [comment]
Potentially addressed in https://github.com/Regalis11/Barotrauma-development/commit/34e552c369a9c5459486e469005a4980d0fdf6b9 + added some extra logging to diagnose it in case it still occurs

> Potentially addressed "mission count doesn't match" errors. We were using GameSession.Missions instead of GameMode.Missions client-side when checking mission equality. The former is filled from the latter in GameSession.InitializeLevel, and I suspect in some cases that might not have run yet when the client receives the mission count. + Also added extra logging for the error (list mission identifiers instead of just count).

**Comment by Wheatley1001** [comment]
Unsure if this is related to this error log or if it's a variant of it, but we had a user disconnect after receiving the following log (version: 100.6.0.0):

There was an error initializing the round. {Mission equality check failed. Mission count doesn't match the server. Server: , client: salvageartifactcave, killmolochblack, game session: salvageartifactcave, killmolochblack)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 878
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1553

**Comment by Wheatley1001** [comment]
Another two mission equality check failed disconnect bugs. These are from 100.8.0.0, unsure if related to this ticket or not. I don't particularly want to flood the github with these types of bugs, especially if they're all related.

![image](https://user-images.githubusercontent.com/105495756/205414395-e404f9a0-7c59-469e-8a30-dbfe5bd65f53.png)

![image](https://user-images.githubusercontent.com/105495756/205414432-469cba19-fa80-441e-a4ce-5b2c9c5b2573.png)

**Comment by Wheatley1001** [comment]
Error surfaced again in 100.15.0.0, three players got disconnected at once

![image](https://user-images.githubusercontent.com/105495756/215236763-6e1fdb78-f421-47fc-b91f-e97146adeb23.png)
![image](https://user-images.githubusercontent.com/105495756/215238010-4a1d9e54-6c42-45c7-805e-21e5034efe06.png)

**Comment by AzureNocte** [comment]
I've encountered this issue too, and it happens almost every end of rounds in thegreatsea map.
I play with no mod, and did not edit the subs.

Error while reading a message from server. 
Submarine equality check failed. The submarine loaded at your end doesn't match the one loaded by the server. There may have been an error in receiving the up-to-date submarine file from the server.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc)
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc)
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime)
   at Barotrauma.Networking.GameClient.Update(Single deltaTime)

![20230218211725_1](https://user-images.githubusercontent.com/44329789/219904836-67e23237-e3c7-4859-924d-ebab519af119.jpg)

**Comment by Wheatley1001** [comment]
Another instance from 1.0.2.0
![image](https://user-images.githubusercontent.com/105495756/221038575-9b252a95-bf77-4a0d-80f9-0dc86cc0e452.png)
