### ISSUE TITLE
[Factions] Players wearing the Exosuit can hide in the Clown Crate

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10496]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Players wearing the Exosuit can hide in the Clown Crate despite being roughly 5x its size. The sheer difference in size makes this difficult to believe, however it _is_ a **clown** crate. This could be intentional or it could be an issue. 

I don't have images for this one, sorry. 

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'd consider this a non-issue, considering it's somewhat of a joke item
