### ISSUE TITLE
[Factions] Invalid target type "Head" in StatusEffect (Hammerheadmatriarch)

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10492]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At the start of campaign rounds, the title error log would appear in the console. Some players would suffer disconnects after this, but most players were unaffected by the error. The prevalence of the error log and consistent appearance is what made me bring it forward.

Below are four instances of the same error log. These are collected from different users at different points in the campaign.

![image](https://user-images.githubusercontent.com/105495756/202920624-d0291212-74b9-44ca-a50b-57c3af2a502f.png)
![image](https://user-images.githubusercontent.com/105495756/202921958-b83ad798-0743-4e1e-ab96-b4011164eaca.png)
![image](https://user-images.githubusercontent.com/105495756/202923158-48b50ba7-7a0b-41a1-ba69-983500fe1865.png)
![image](https://user-images.githubusercontent.com/105495756/202924033-5357eaff-ea28-46fe-b556-647dc4c3d8af.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@cbc4c0e.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
