### ISSUE TITLE
Secure Weapon & Toxin Cabinet denies all access

### ISSUE THREAD

**Issue by Reggie-Marshale** [Regalis11/Barotrauma#10504]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This occured in Singleplayer Campaign. After buying the R-29, as well as the Winterhalter (note that the latter occured in stable builds), None of the crew can gain access to the secure cabinets (both weapons & toxins). As it occured on more than one sub, I suspect the bug occured in other vanilla ships as well. However, I tried starting a new save with vanilla subs (the bugged saves started with a workshop one) and the bug does not reproduce itself

### Reproduction steps

1. Start a new save (try comparing the starter sub between vanilla & workshop)
2. If the starter sub is from the workshop, purchase a vanilla one and re-enter the save
3. Attempt to open the secure cabinets to see if the bug is present

### Bug prevalence

Happens every time I play

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Are you using the `Keep you down` mod? Ive had the same issue with that mod specifically

**Comment by Reggie-Marshale** [comment]
> 

No, I don't. However, I do use EK modpacks

**Comment by Regalis11** [comment]
No known steps to repro, closing
