### ISSUE TITLE
[Unstable][Feature Request] swap grenade slot and bullet slot on rifle

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10500]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Previously, grenade is on the first slot.
You can load'n shoot a grenade easily.
But now, you will have to unload all bullets before shooting a grenade.

### Reproduction steps

1. equip a rifle loaded with bullets and a grenade
2. shoot it
3. the bullet is shot, not the grenade

### Bug prevalence

Happens every time I play

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
