### ISSUE TITLE
[Factions] Slight inconsistencies with turret loader box positions

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10505]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On todays episode of me nitpicking visual issues, turret loader boxes.
![image](https://user-images.githubusercontent.com/104232152/203131660-3aa80742-fa97-4f70-85a4-a4257f1e6516.png)
As you can see in the image, each kind of loader has a different position for the box, the pulse laser connecting to the top part (makes sense), the coilgun loader having the box from the lip of the loader up, and the chaingun loader, having the box set to have the symbol at the lip.
When you look at a lignup of these, its slightly annoying to see them being somewhat randomly inconsistent.

### Reproduction steps

1.Check out them loaders with boxes in them in the sub editor

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/52e6c1edd36882a1ddf6be0c5d060cae0e24d432
