### ISSUE TITLE
Can't see inside wreck with periscope

### ISSUE THREAD

**Issue by pubrrr** [Regalis11/Barotrauma#10501]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I don't know whether this is really a bug or rather a feature, but to me it seems illogical:

When you shoot holes into the hull of a wreck with a turret, you can't see inside. However, sometimes you see shades inside. You can also see, if you hit something with HP, like hatches and creatures.

Players can see inside the wreck with a flashlight or the light of a scooter.

![grafik](https://user-images.githubusercontent.com/62142301/203011439-b3925a01-cc6f-484a-89f7-ffb1cf748525.png)

Either you should not be able to see inside at all from periscopes, or you should be able to. Also if you manage to shoot your way though the whole wreck, you can see the light on the other side of the wreck.

### Bug prevalence

Happens regularly

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
I think this is caused by the fact that all turret lights have "draw behind sub" checked by default.

**Comment by Regalis11** [comment]
> I think this is caused by the fact that all turret lights have "draw behind sub" checked by default.

Yep, that seems to be the cause. Personally I think this is such a minor issue that it's not worth the trouble to rework the lighting algorithm (or make the lights not drawn behind subs, which causes a large performance hit) to address it.
