### ISSUE TITLE
Crafting multiple items takes items from your inventory and works after death

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10508]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Credit to Hawkins for finding this issue.

Setting the fabricator to craft multiple of one item and walking away from the fabricator will cause the fabricator to consume items from your inventory regardless of distance. In addition, this continues into death.

### Demonstration of distance crafting
![image](https://user-images.githubusercontent.com/105495756/203148044-646e4dc8-2a4c-428f-aaa2-4c76fa76cd65.png)
_Figure 1. Crafting as many steel bars as possible._

![image](https://user-images.githubusercontent.com/105495756/203148084-809fa0bf-fdaa-45fc-930c-f9f4c56c0cf2.png)
_Figure 2. Walking away from the fabricator and waiting for time to pass._

![image](https://user-images.githubusercontent.com/105495756/203148153-2b3974f8-863c-42d2-a227-0bcc10d1bc10.png)
_Figure 3. The fabricator takes items from the inventory and crafts another item despite considerable distance from the fabricator._

### Demonstration of death crafting 
![image](https://user-images.githubusercontent.com/105495756/203149777-c848a1fd-b199-4299-8f99-d97cedc3d7b1.png)
_Figure 4. Inventory filled with steel bar ingredients, same circumstances as Figure 1._

![image](https://user-images.githubusercontent.com/105495756/203149912-270e00a1-3ac4-45ea-9c36-83d830b517d1.png)
_Figure 5. Items taken, crafting begins._

![image](https://user-images.githubusercontent.com/105495756/203150026-5c53c046-bb55-4e27-8044-491004c5f33b.png)
_Figure 6. Captain's corpse gaining mechanical skill._

![image](https://user-images.githubusercontent.com/105495756/203150052-9c1ddff1-bb23-4d54-92ec-ab48ac26a88f.png)
_Figure 7. Inventory immediately taken after Figure 6. Note slots 6 and 0._

![image](https://user-images.githubusercontent.com/105495756/203150076-7780da53-0e38-48dd-bda2-79822588064d.png)
_Figure 8. Inventory with items stolen by fabricator and skill bonus continuing after death. Note slots 6 and 0._

### Reproduction steps

1. Get crafting materials 
2. Set fabricator to craft 8 items 
3. Walk away from the fabricator (with materials still in inventory)
4. Observe how the fabricator takes items from your inventory regardless of distance

For death crafting:
1. Repeat steps 1 and 2 from previous method
2. Kill the player who started the crafting (by changing to a bot or by having another player kill them)
3. Observe how the corpse's inventory is slowly looted by the fabricator

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f6177d315515329a21bdb51e498ad9c56e17c4b

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/09b8873e88f8ca7b179d3f0fda9384e6ec5e727e, no issues found, closing.
