### ISSUE TITLE
[Factions] Artie Dolittle has no talents

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10509]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Many unique NPCs added in the faction branch have talents to allow them to stand out. Auntie Doris is one such example. Artie Dolittle has absolutely no talents.

![image](https://user-images.githubusercontent.com/105495756/203153026-33a13e3b-1990-41db-9ad9-0ae249d19a97.png)

It isn't clear why this unique NPC would be undeserving of talents, especially considering that there are talents that fit his character perfectly such as Crew Layabout.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'd say it's fine Artie has no talents, he's a low-level character with no indication of ever having worked on a submarine.

**Comment by SergSel2006** [comment]
Don't worry, as long as you give him ethanol he will be your ultimate death machine.
