### ISSUE TITLE
[Factions] Opiate overdose outpost event, character is invincible

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10517]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A somewhat silly thing with the opiate addict overdose events character being invincible until interacted with, even in pure pressure
![image](https://user-images.githubusercontent.com/104232152/203435384-a0bbe343-718b-4434-8581-a83472fd20d9.png)

### Reproduction steps

1.Get the opiate addict overdose event
2.Try to kill them before interacting with them

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional
