### ISSUE TITLE
[Factions] Ending switch objective doesnt dissapear

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10516]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the fist stage of the final level, when flicking the switch, the objective doesnt dissapear, just staying stuck there. 
![image](https://user-images.githubusercontent.com/104232152/203427435-d992e642-e99a-4e11-96fa-d3c76cd0daf8.png)

### Reproduction steps

1.Get to the eye of europa
2.Collect all the logbooks
3.Flick the switch and look at the nav terminal

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0685778d8211047121bd29cc290abe23eb64ed65

**Comment by Rehexr** [comment]
Objectives worked properly when the big server tested it, so im closing it
