### ISSUE TITLE
SteamCMD support

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1051]
I'm trying to run a dedicated 24/7 server for the testing rounds through Steam. I'm facing a problem where Steam thinks I'm playing Barotrauma when in reality I'm running the server. This means I can't actually play Barotrauma on another machine. SteamCMD support or making it so it doesn't come up as 'Playing' in Steam would be very much appreciated.

**Comment by Regalis11** [comment]
Partially fixed in 8249d78, although we should still have SteamCMD support to make it easier to install and run the dedicated server.

**Comment by Heldex** [comment]
Hello sorry for a necro, I just tried making a server with appID 602960 with app_update on steamcmd, but when I configured and booted the server. It said in red text, Initializing Steam server failed. And when attempting to connect it doesn't work, could you make it compatible?

**Comment by Regalis11** [comment]
Available now: https://steamcommunity.com/games/602960/announcements/detail/1585744934762671298
