### ISSUE TITLE
[Factions] Sprite depth of chairs in outposts are wrong

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#10518]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/59519434/203448291-6a7d6d92-3c45-4dfd-91e6-190fb6cb8c02.png)

I'm in front of the guy, but at the same time behind the chair, creating a paradox. Better check the depths of all the chairs in outposts for this.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to have been fixed by https://github.com/Regalis11/Barotrauma-development/commit/1a857fddd31b408c9c9f233b34d968a16a0c9186
