### ISSUE TITLE
[Factions] Building husk reputation practically impossible

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10514]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wheather this be related to the lack of husk related events or missions, which build reputation, or an issue with those appearing in general (almost every outpost ive gone to had a clown distict), its currently not really possible to build reputation with the cult of the husk, no matter how hard you try, making getting their specific items impossible to get in conjunction.
To elaborate on my sitiuation, ive taken, and sided with, every husk event i could, i even used the affiliation perk, but after a whole playthrough, finally reaching the final outpost, its gotten pretty clear to me that getting the appropriate amount of rep for the cult of the husk is currently not really possible, or too rng dependant.
![image](https://user-images.githubusercontent.com/104232152/203376938-39bb067a-3c84-4f5e-92f7-28f5818f65c9.png)
![image](https://user-images.githubusercontent.com/104232152/203376967-9c4a2487-4333-40fc-a58b-43a4c8d580a3.png)

### Reproduction steps

1.Try working through a campaign, taking all cult of the husk opportunities
2.Find that it is very hard to gain reputation, possibly depending of rng

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Did you complete the husk event chain (the one where you rescue a specific NPC and work towards ascension)? Or did you not run into those events during the whole campaign?

**Comment by Rehexr** [comment]
Yeah fairly safe to say that i didnt run into it all campaign, though I did scower each outpost for events, mightve just been a pretty unlucky case of just not getting any related events

**Comment by Regalis11** [comment]
Ah, I think I see the issue: the main event chain doesn't start until you're above 15 rep, but you need to be very lucky to get enough random events to get up there. Especially when a couple of the random husk events actually require high reputation to complete successfully.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e2d340a8fb79099845e04fa0d19e90ed63157909:
- Removed the 15 rep requirement for starting the main event chain
- Made clown/husk-specific missions more common
- The "young cultists" events can repeat if you ignore it

**Comment by ekqvist** [comment]
Tested that

- the "young cultists" events can be repeated if you select to ignore it after triggering it when you first encounter it; and
- you can start the first "way to ascension" event when your hust cult reputation is at 0.

Seems to be working correctly, closing.

**Comment by Regalis11** [comment]
This still seems to be an issue, reopening.
