### ISSUE TITLE
Scrap Savant can't craft with scrap

### ISSUE THREAD

**Issue by MaxEyess** [Regalis11/Barotrauma#10510]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Can't craft the alien materials with scrap

### Reproduction steps

Happen every play, after unlock the scrap savant talent.

### Bug prevalence

Happens every time I play

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
The Scrap Savant talent has been reworked, as it made it too trivial to get these alien materials. Removed the XML, so those recipes no longer show at up the constructor.

**Comment by feru7** [comment]
The recipes for dementonite tools are also still available, altough they can no longer be crafted.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
