### ISSUE TITLE
Weapons still not stocked in outposts

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10511]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have finally reached the final outpost of the game, the outpost difficulty is 64.9, its a city outpost, and not once have i had an outpost which stocks shotguns, shotgun ammo, hmgs, or smgs/smg magazines in this entire run, so in conclusion, check the appearence of weapons stocked in outposts.
And as to elaborate, not even military outposts or arms dealers stock them, with the exeption of rifles and accompanying ammo, which later couldnt be bought aswell.
All of this is specifically on coalition outposts, with which i have perfect standing, so really theres not much reason for them not to be stocked correctly. Though i will specifically have to say that this may be singleplayer campaign related.

### Reproduction steps

1.Start a campaign
2.Progress until appropriate difficulty for weapon stockings
3.Find that weapons are never stocked at their approapriate place

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
