### ISSUE TITLE
[Factions] Bots dont prioritise shooting repair bots

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10519]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the final area, ive found it quite gruelling to complete with bots, as they never prioritise repair bots over guardians, only ever hitting them occasionally in the crossfire 

### Reproduction steps

1. Have  bot on a turret
2. Spawn a guardian and repair bots
3. Notice them shooting just the guardian 

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Seems anomalies dont get targeted either, making them just ignored by bots, apparently

**Comment by itchyOwl** [comment]
Making the bots prioritize the repair bots was trivial, but making them shoot anomalies (which are items) required a bit more, because shooting at items wasn't implemented at all. Nevertheless, both issues are now addressed in Regalis11/Barotrauma-development@b22b403 and in Regalis11/Barotrauma-development@fd86e2b.

**Comment by itchyOwl** [comment]
Addressed in 5f4b26f. Also test how it works with a tigerthresher + bonethresher swarm (I gave tigerthreshers and crawlers a lower priority). Besides guardian repair bots, also leucocytes, spinelings, and terminal cells are now ignored when operating railguns.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
