### ISSUE TITLE
[Bug] Knife still retains physics when set to non-interactable

### ISSUE THREAD

**Issue by DanJF** [Regalis11/Barotrauma#10521]
As title says : most items when set to non-interactable will no longer have physics applied to them, and can be used as aesthetic prop pieces for setting scenery in subs.

Knives seem to still retain their physics when non-interactable.

**Comment by Regalis11** [comment]
Thank you for the report!

I don't think this is a bug: interactability shouldn't affect whether physics apply to the item or not. 

> most items when set to non-interactable will no longer have physics applied to them

Which items do you mean?

**Comment by Regalis11** [comment]
No known steps to repro, closing
