### ISSUE TITLE
[Unstable] Wrecked Pericope can't be used

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10526]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wrecked Pericope can't be used. It doesn't control your position, despite being a simple variant of regular periscope

### Version

0.20.7.0 (Unstable)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/368f4dc5cec4c45a5c317a188e8cf7fe74df0e7d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
