### ISSUE TITLE
Bug with outpost text

### ISSUE THREAD

**Issue by LazyTurtle61** [Regalis11/Barotrauma#10529]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

so a outpost got changed into sepratists outpost but this the text says it turned into coalition outpost.
![image](https://user-images.githubusercontent.com/64089224/203826651-d9d70fdc-0977-4918-abee-900e803c166b.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately wasn't able to get this to happen - tested by teleporting across the map for a while, and the message seemed to be displayed correctly on the dozen or so outposts that were established. So I suppose this either requires some more specific circumstances to occur, or has a low random chance of happening. Need to do some more testing it seems.
![image](https://user-images.githubusercontent.com/14351070/203943790-c52710bb-8d11-48f9-9cc9-e33217b2be1a.png)

**Comment by Regalis11** [comment]
No known steps to repro, closing
