### ISSUE TITLE
[Factions] Commendations and Figurehead issues

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10527]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Captain with the talent Commendations without the talent Figurehead will gain a Medal instead of the intended Commendation. Meanwhile, completing a mission with Figurehead will reward a Commendation instead of the intended Medal. 
Captain with Figurehead giving a Medal to a character under level 5 doesn't seem to give them the experience required to reach level 5.

### Reproduction steps

1. Complete a mission with a captain who has the Commendations talent but not the Figurehead talent
2. Complete a mission with a captain who has both of the talents
3. Have the Captain with Figurehead give a Medal to a character under level 5

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ffa5b6f1fda4b6cf218274640c1e3c96a13aee3

**Comment by JeroonBosch** [comment]
Tested, found no issues
