### ISSUE TITLE
[Factions] Faction bribes to pass into new areas text show for everyone, and prices are impossibly expensive

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10525]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This ticket will be split into two key issues relating to faction bribes.

### Bribe text ending shows up for everyone regardless of position

Talking to the NPC in order to unlock the next area works as intended until the final message. If you decide not to offer a bribe and walk away, the final message is given to everyone in the lobby regardless of position. This occurs regardless of who interacts with the NPC and happens every time the NPC is interacted with.

### Bribes are impossibly expensive compared to reputation milestones

At the passage into the Great Sea, our reputation with the Coalition sat at +47. To pass into the next biome, we needed +50 reputation. We decided to try out a bribe, expecting a relatively cheap cost considering how close we were to passing without needing a bribe. 

The bribe total we were told to pay was 8,000 marks (roughly half of the bank's savings). For a reputation difference of -3, this seems outrageously high for a submarine crew who was already very friendly with the coalition. The salt in the wound was when the NPC called us an "unknown crew". Ouch.

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed the issue of the text being shown to everyone in https://github.com/Regalis11/Barotrauma-development/commit/5fc8fa55c8e3586da717e6084947f7e28ae25914

I disagree about the cost being "impossibly expensive" though. It was mainly intended as failsafe that gives you some way to get past the outpost regardless of your reputation. The cost is intentionally very high, incentivizing you to actually get the reputation above the threshold, and serving as a gating mechanism that forces you to complete a certain amount of missions (or alternative, farm enough money) before you can proceed.

**Comment by JeroonBosch** [comment]
No issues with the texts showing to everyone anymore. If prices are too expensive (they don't take into account reputation at all it seems) we could consider scaling the cost with missing rep?

Could be closed if we do not want to do that.
