### ISSUE TITLE
Inconsistent view range of large turrets

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10520]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Railgun has broader view range than small turrets while Flak Cannon and Double Coilgun has exactly the same view range as small turrets.

### Reproduction steps

1. place railgun, flak cannon and double coilgun in a horizontal line with sub editor
2. use them with periscopes and compare their maximum view range

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d74443b8fe8f964b55b85af86a64d2fe4008ed7b

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
