### ISSUE TITLE
Lights in your inventory attract monsters the same as if they were in your hand

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#10531]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Lights like flashlights and glowsticks have the same attraction range even if they're off in your inventory.

### Reproduction steps

Turn on `aitargets` and `debugai`.
Swim outside with a flashlight in your inventory but not being held or used.
`freecam` to see the range of the circles around you.
Drop or remove the battery of the flashlight.
Look at the circles again.
https://streamable.com/c6lc1v

### Bug prevalence

Happens every now and then

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@3ff8291 (bugfixes). Happened when the flashlight was first equipped and then unequipped (still in the inventory).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
