### ISSUE TITLE
Drunken sailor doesn't make you immune to drunkenness

### ISSUE THREAD

**Issue by Demomangodofbeer** [Regalis11/Barotrauma#10539]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the talent drunken sailor doesn't make you immune you drunkenness. tested this in the ship editor so don't know if it works in campaign. still bug though

### Reproduction steps

1. get talent 
2. use rum 
3. watch as you not immune to it

### Bug prevalence

Happens regularly

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no error message just bug
```

**Comment by Regalis11** [comment]
The talent doesn't make you immune to drunkenness, just the _negative effects_ of drunkenness as the description says. Gave this a test now and it seems to be working correctly: drunkenness doesn't cause nausea, impair movement or kill you when you have the talent.
