### ISSUE TITLE
Wrong identifier for Don't push it talent - explosive shotgunshells are not unlocked

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#10534]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/59519434/203872751-2ff344bb-df61-488d-8e23-36fc34907684.png)
img by Hawkins: ![image](https://user-images.githubusercontent.com/59519434/203872756-b86afba8-f1d1-4b99-bfdd-cd09e9997b74.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem to be specific to the faction branch, occurs in unstable as well

**Comment by Regalis11** [comment]
Can't spot any issues [in the changes](https://github.com/Regalis11/Barotrauma-development/commit/523778c6775910a5b9031abfafeb302fda44f6b4), moving to QA

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
