### ISSUE TITLE
[Unstable] Clown quest issue

### ISSUE THREAD

**Issue by Earthspiritio** [Regalis11/Barotrauma#10535]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The crate for the clown item retrieval quest appears in a different room and when you succeed in the quest it for some reason doesn't register that you did it properly and just says 'You return to the clown empty handed' even if you bring the crate to them.

### Reproduction steps

1. get into a city
2. find the clown item retrieval quest
3. find crate and succeed in tricking the guard
4. try to talk to clown to finish quest (will fail if the crate spawned in a different area than the quest giver room)

### Bug prevalence

Just once

### Version

0.20.7.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3fed54acdde52f00156814b58de17fd99a35ce99

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
