### ISSUE TITLE
Z-fighting in an outpost module

### ISSUE THREAD

**Issue by Mikal95** [Regalis11/Barotrauma#10530]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When i go the the station manager's office at the start of a new campaign, the background wall texture overlaps the bookshelf texture when i move my mouse cursor up and down.

https://user-images.githubusercontent.com/62056128/203836908-4a165b16-51fc-4a37-b119-c10d6ff2d439.mp4

### Reproduction steps

1. Start a new singleplayer campaign.
2. Go to the station manager's office.
3. Move the mouse cursor up and down the screen so the game zoomes in and out.
4. As you do step 3, the background wall should start overlapping the bookshelf texture.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/307f89d6fad8cb458206f814d5b108ae830bd564, no issues found, closing.

Z issues are fixed, but appears the lighting from a small separatist monitor is bleeding through into coalition stations. I feel this might warrant a new issue but its still relevant to this specific module (Adminmodule_02L)

![image](https://user-images.githubusercontent.com/29177976/207892287-c238be00-b50b-4fa5-8e40-c9c7dacae354.png)

![image](https://user-images.githubusercontent.com/29177976/207892320-27062c26-bdd5-45b0-88c5-b0f0c113d0eb.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3810/commits/e3e1afbb83b0934ee6b335e27baa8c253b63947a

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
