### ISSUE TITLE
Players cannot easily leave the clown crate

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10545]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Once you enter the clown crate, the only way to leave it is to hold space and ragdoll. This means on servers with ragdoll disabled, the only way to leave the clown crate is for someone else to pick it up whilst you're inside of it.

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem specific to the faction branch

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd0a5778613960ccaad68a26c29eff374570db05

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
