### ISSUE TITLE
Harpoon-coil sound can be heard across the entire sub (it's very goofy)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10556]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The range on the harpoon chargesound is 3000 which covers the entirety of almost every submarine

The sound itself is quite hilarious if spammed when you charge it up without firing

### Version

Faction/endgame test branch

**Comment by HeatedWafflez** [comment]
Regarding this, I'd also like to state the flak cannon is incredibly obnoxious in my opinion. It's not that it sounds bad, but you'd expect it to sound sort of muffled/lower pitched seeing as the explosion is happening in water. It sounds more so like an explosion is occurring within the sub and it can quite honestly be disorientating.

**Comment by Rokvach** [comment]
No issues, closing.
