### ISSUE TITLE
[Unstable] Talents UI is slightly too small for campaign (due to Bank line)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10553]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Post talent rework, If you play missions or sub editor, the talents window is properly sized (on a 1920x1080 resolution)

But in campaign, it adds the "bank" line at the bottom and it makes the UI slightly too small to fit all the talents without adding a scroll bar

![image](https://user-images.githubusercontent.com/73229309/204057666-731a95ac-55b3-4404-9174-d4f1f6cf2fb5.png)

### Version

0.20.8.0 (Unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dde5b4cafe4b1ca9ef5997fd63165d13255ec2f2

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
