### ISSUE TITLE
Water-reactant items generate particles inside waterproof storage, big performance issues

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10552]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The items don't actually explode, they just keep generating particles and sound. 

When underwater this massively impacts the Mapentity Items as seen in showperf, a single cabinet can hold dozens of water reactant items 

![image](https://user-images.githubusercontent.com/73229309/204057271-b3661950-d0f9-40ba-a7d3-f3bb1c401250.png)

### Version

Faction/endgame test branch

**Comment by ubertpendragon** [comment]
#10538

**Comment by Regalis11** [comment]
Does not seem specific to the faction branch

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f14a48cf95d001a2661667295f5c46f08c82fc12

**Comment by HeatedWafflez** [comment]
https://user-images.githubusercontent.com/51425624/204115037-91159b68-e5c5-4ca9-bdcb-efd45aad2ec9.mp4

Just gonna stick this here as a reference to how it was then.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/09b8873e88f8ca7b179d3f0fda9384e6ec5e727e, no issues found, closing.
