### ISSUE TITLE
Junction boxes don't get damaged by water

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#10555]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I assume that because junction boxes are electrical devices they're supposed to be damaged by water, but they don't seem to be.

### Reproduction steps

Open a ship like the Dugong in the editor and click test.
Go in the junction room and do the commands `debugai` and `water`.
Put water in the room and see how it damages the batteries but not the junction boxes.
![image](https://user-images.githubusercontent.com/42877449/204060167-80537b30-8995-4444-b792-ac1b35077cab.png)
![image](https://user-images.githubusercontent.com/42877449/204060179-2a63b062-27e2-4157-8f2b-6f8164fd5092.png)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1251a988c873a90fb1dce453dbbc25feedd0dbda

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
