### ISSUE TITLE
[Factions] Floating minerals

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10559]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unfortunately didn't grab the seed for this. I've learned my lesson (I have seeds in future issues).

![image](https://user-images.githubusercontent.com/105495756/204066877-8242944b-a1ce-4e34-9d5e-be107024abab.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by mrjpjr** [comment]
I have also encountered this.
**Version: Unstable 0.20.11.0**
![floating minerals bug](https://user-images.githubusercontent.com/58775950/206435058-147265a7-d3c8-4298-82bd-fffd5ec624d0.jpg)
Hexcode said you need more info, and that a seed and/or a save file would help.
Seeing as I just completed the map with the floating minerals, I am able to get the seed.
![floating minerals Map Seed](https://user-images.githubusercontent.com/58775950/206435726-24d0219c-50f8-405b-8cf9-a26beead0816.jpg)
Below is the location on the map where I encountered the floating minerals
![floating minerals location on map](https://user-images.githubusercontent.com/58775950/206436097-7165f262-40ca-4010-bc5d-633cb8628d1b.jpg)
Unfortunately, when I loaded back into the map to get the seed and checked for them, the floating minerals in question were not there.
Below is the save file. Hopefully this will help.
[Unstable 20.1 test.zip](https://github.com/Regalis11/Barotrauma/files/10184906/Unstable.20.1.test.zip)

**Comment by Wheatley1001** [comment]
I don't have any detailed info for this instance since this is an image taken by another player so idk when or where this was, but the issue persists in 100.13.0.0.

![image](https://user-images.githubusercontent.com/105495756/212446773-255fb19f-612c-4aa9-9df7-3d14639cfeab.png)
