### ISSUE TITLE
Camel reactor has 1000 condition

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#10554]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I didn't actually know reactors didn't usually have 1000 condition until I checked other subs, but it seems like they're usually supposed to have 100 condition.
![image](https://user-images.githubusercontent.com/42877449/204058688-7a5ec9a6-f104-4d68-96c5-abec9afdccfb.png)

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment]
Kastrull reactor seems to be at 1000 as well
![image](https://user-images.githubusercontent.com/115734437/204238116-3f2ccb15-a0da-44ab-a098-c8a6af65cf25.png)

**Comment by Regalis11** [comment]
There seems to be some code issue here that's causing the reactor conditions to change, I'll look into it

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/bff04c91088ffa56f04ab2198eaca9a6938e9239

> Fixed Kastrull's reactor having 1000 condition. I think this and the other reactor condition issues were caused by me accidentally saving the subs with a mod that sets reactors' HealthMultiplier to 10, which I used when testing the changes to condition serialization (see #9850). I now added a debug-only warning to the sub editor that shows a warning when you try to save a sub with mods enabled.

**Comment by Rokvach** [comment]
No issues, closing.
