### ISSUE TITLE
player gain no weapons skill when inflicting damage with flak shrapnel

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10569]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

player gain no weapon skill when inflicting damage with flak shrapnel.
probably because the shrapnels are not launched by the player but the bolt itself.

### Reproduction steps

1. get a flak cannon in sub editor
2. use "setskill weapons 0" on your character
3. use "disableenemyai" to disable enemy from moving
4. spawn some crawlers and kill them with flak shrapnel instead of direct impact repeatedly
5. the weapons skill never grows

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@0b2d49c.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843, no issues found, closing.
