### ISSUE TITLE
Submarine weapons unable to use 0% ammunition boxes

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10567]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The double coilgun cannot use ammunition boxes if they are 0% full. The chaingun also seems to have this issue, though it's much less common. 

This is a problem as it renders the ammunition boxes completely useless. You need empty boxes to recycle them, but you also cannot fully empty them as the weapons refuse to fire using the boxes. 

![image](https://user-images.githubusercontent.com/105495756/204067844-643f22f0-982d-4338-b51b-f428d20152f7.png)
![image](https://user-images.githubusercontent.com/105495756/204067846-77c54310-7308-4726-a992-fa0530308d3f.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by HeatedWafflez** [comment]
Honestly you should be able to recycle any form of ammunition at any durability with varying material requirements. Having a box that's almost empty sucks, but having to fire off and waste the rest of the shots just so you can recycle it is even worse.

**Comment by ubertpendragon** [comment]
True, increasing the max required condition from recycle boxes would solve that problem, it's currently at 0 why not 10%

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6a0a2a3041d628ac85199608e7525f3237ddba38 by allowing the boxes to be recycled when <10% full and in https://github.com/Regalis11/Barotrauma/issues/10568 by fixing the bug that prevented firing the gun when the ammo box was almost empty.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/09b8873e88f8ca7b179d3f0fda9384e6ec5e727e, no issues found, closing.
