### ISSUE TITLE
[Factions] Outposts acting like they still have outpost specific rep

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10560]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some of our crewmembers were attacking outpost dwellers. Eventually they gave the threatening lines you would expect from a hostile outpost in 0.19.14.0, one that uses outpost specific reputation. This is even more confusing as none of our factions are considered hostile- only unfriendly with the Honkmother. The outpost was a Separatist outpost.

![image](https://user-images.githubusercontent.com/105495756/204067008-651b7608-8aa9-403d-a395-5d6ac553cf35.png)
![image](https://user-images.githubusercontent.com/105495756/204067011-db5a2e7f-b99a-4745-8a09-1ba552068e1f.png)
![image](https://user-images.githubusercontent.com/105495756/204067012-9770919d-a232-4b8b-b5e8-a6b588524a92.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro, closing
