### ISSUE TITLE
Exosuit sprite clips through doors

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10564]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Image speaks for itself.

![image](https://user-images.githubusercontent.com/105495756/204067642-81733ca8-fab2-4975-9bae-ff3df8a16b14.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Extremely minor visual issue that'd be complex to solve. Closing.
