### ISSUE TITLE
Attempted to access potentially removed character. Character: Mudraptor_veteran

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10563]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Credit for the error logs goes to Hawkins.

![image](https://user-images.githubusercontent.com/105495756/204067566-ccd1e1c7-0068-41e9-a3a9-0e579b49cf8e.png)
![image](https://user-images.githubusercontent.com/105495756/204067568-1ad9fbe6-32cb-457f-bc6c-6130d6fb0f86.png)
![image](https://user-images.githubusercontent.com/105495756/204067571-1e50993e-1923-4661-9347-80758996d41f.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma@689fc36. I was able to repro it once. Happens only in multiplayer.

Steps to repro: Play the game in multiplayer with a bunch of defensebots.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
