### ISSUE TITLE
Ready check doesn't seem to finish if you don't answer the prompt

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10561]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you don't vote in a ready check, it won't go away. It sits in the top right of your screen with a full bar and does nothing until you interact with it. 
![image](https://user-images.githubusercontent.com/105495756/204067117-4906c9af-ca7d-4331-a421-c7f7f4a0f97d.png)

In addition, if multiple users submit multiple ready checks that enter this state, interacting with the ready check shows a list of players with no responses whatsoever. 
![image](https://user-images.githubusercontent.com/105495756/204067128-f89b9514-7119-41bd-a6b4-cac88344169a.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem specific to the faction branch

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/77979ff6044cca48c009c30fba4ca3d4cad94ed1https://github.com/Regalis11/Barotrauma-development/commit/a7c861105a0887299d0e1caf10d9fdaffac6a6c6 and https://github.com/Regalis11/Barotrauma-development/commit/0bc380a692bb87a994186e68e0bc3e7248350ab5

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/09b8873e88f8ca7b179d3f0fda9384e6ec5e727e

Those who vote or start the ready check see the result, and although those who do not vote do not have this stuck on their screen until they vote they also do not see the results.

**Comment by 3e849f2e5c** [comment]
do we need to show the results to people who don't vote? to me it doesn't make much sense since if you don't vote there's a big chance that you are AFK or is there some other kind of issue here that I'm not understanding

**Comment by Regalis11** [comment]
I think we should make it visible to everyone. I think there's plenty of situations where you might not want to vote but still want to see the results: for example if the crew wants to switch to a sub you don't know (and don't want to take a stance on), or you might have recently joined a server and don't have an opinion on whether someone should be kicked or not.

**Comment by Regalis11** [comment]
Didn't realize this only concerned ready checks, not other votes. I agree it doesn't matter the results aren't shown to those who don't vote.
