### ISSUE TITLE
[Factions] Unknown Floating Object sighting

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10565]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**MAP SEED: NoctaeCastalia Macula**

In the abyss, we discovered an un-interactable unknown object. Below are images of this mysterious object.

Some crewmembers believe this to be a Fractal Guardian weapon 3, or an Ancient Weapon. Personally, I have absolutely no clue.

![image](https://user-images.githubusercontent.com/105495756/204067708-897a6cf7-12d7-4c0d-bb02-47a7c0d16f5b.png)
![image](https://user-images.githubusercontent.com/105495756/204067711-0d075019-7dfb-499c-8520-e6b28adbfdc9.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment]
my guess is Jove's poop

**Comment by ubertpendragon** [comment]
It looks like a deattached arm of Fractalguardian3

When you kill it the arm simply disappears, maybe it teleports somewhere in the map and that's what we saw

**Comment by 3e849f2e5c** [comment]
some notes, it was permanently fixed in that position and even phased thru the submarine, saw it on sonar bottom left of the map, my guess is that it was the 0,0 coordinate

**Comment by itchyOwl** [comment]
> It looks like a deattached arm of Fractalguardian3
If it's non-interactable, then it's an ancient weapon (or "guardianbeamweapon") from a dead fractal guardian 3. Since Regalis11/Barotrauma-development@239058f, it should be removed when the guardian dies, but I guess that fix wasn't in the faction testing branch when you found it? So needs testing if it still happens.

**Comment by itchyOwl** [comment]
Moving to QA, because it's likely that this issue is fixed by the commit mentioned above.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
