### ISSUE TITLE
Starting outpost in single player campaign offers no missions

### ISSUE THREAD

**Issue by feru7** [Regalis11/Barotrauma#10573]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The starting outpost in single player campaign offers no missions, you have no option to speak to the outpost manager and he is not marked with a speech bubble.

### Reproduction steps

1. Start a single player campaign
2. Try to talk to outpost manager

### Bug prevalence

Happens every time I play

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by TheMinerBoy** [comment]
Did you finish the checklist on the top right of the screen?

**Comment by feru7** [comment]
I am not sure what you mean by that? There is no checklist. Is this is from the campaign tutorial (which I do not usually use)?

If it is from the campaign tutorial, I tried starting with and without enabled. In both cases, there are no missions, and the tutorial did nothing for me?

**Comment by TheMinerBoy** [comment]
Yeah, it's about the campaign tutorial. Nevermind.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/765c1596fea004b96f251bb0ebab06b799617ed7

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
