### ISSUE TITLE
Lab Contracts crafting bonus works in reverse

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10576]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Our assistant with 100 medical skill crafts Morphine in 11 seconds. 
Our two medics with Lab Contracts unlocked and 100 medical skill crafts Morphine in 23 seconds. 

The 100% crafting bonus currently works in reverse.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cd6b3b352ac439fa64fb92f20bf132e0f06adae2

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
