### ISSUE TITLE
Special civilian transport mission instantly gives 1000mk on accepting

### ISSUE THREAD

**Issue by feru7** [Regalis11/Barotrauma#10574]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The special civilian transport mission random event (Guy with Rex the raptor) gives 1000mk instantly on accepting, and another 2000mk as reward for actually doing it (which is up to the players choice).

### Reproduction steps

1. Start a single player campaign
2. Get the random event mission 
3. Accept mission

Or try the attached save, where Severo Ruiz on the outpost gives the mission.

[Unstable.zip](https://github.com/Regalis11/Barotrauma/files/10096578/Unstable.zip)

### Bug prevalence

Happens every time I play

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This intentional. As the NPC says “I'll pay you three thousand. One when we leave, two when we get there.”.

**Comment by feru7** [comment]
The text is still the same from the old event, the NPC does not say “I'll pay you three thousand. One when we leave, two when we get there.”.

![20221127160708_1](https://user-images.githubusercontent.com/96304666/204142391-b1882d3f-9f6d-4af0-a204-d3c549c89eb3.jpg)

**Comment by Regalis11** [comment]
Ah, yes, you're right! It seems the money was given in a wrong branch of the dialog - the NPC only says they'll pay you if you choose "be suspicious". Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f56e163f6c9ef034802268e426e5d611e3156208

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
