### ISSUE TITLE
[Factions] End level backwards compatibility logic doesn't work in saves started in the 1st faction test builds

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10578]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The ending is absolutely, totally fucked. Seed attached. Images to provide detail. 

Nothing spawned, absolutely nothing. There was a normal wreck and a normal alien ruins. The location was ??? and we had the mission. Nothing happened. We just passed through an entirely empty map.

Zipped save file attached.

[SECRET_TESTING_CAMPAIGN.zip](https://github.com/Regalis11/Barotrauma/files/10097048/SECRET_TESTING_CAMPAIGN.zip)

![image](https://user-images.githubusercontent.com/105495756/204108935-db2714aa-1bd8-4b7f-bfb2-e5b444daccce.png)
![image](https://user-images.githubusercontent.com/105495756/204108938-6d610ea9-32db-4c37-907f-81948e33a735.png)
![image](https://user-images.githubusercontent.com/105495756/204108944-9dd93d8c-437a-43ad-a8b4-b8e659ec5b19.png)
![image](https://user-images.githubusercontent.com/105495756/204108947-86f46092-4954-421f-8c84-e4e501535a58.png)
![image](https://user-images.githubusercontent.com/105495756/204108958-9a41b159-64c1-4175-bd0a-224608b11881.png)
![image](https://user-images.githubusercontent.com/39580303/204109091-7d2116e8-2ba6-4f25-8230-ae5b53fcccc7.png)

[SECRET_TESTING_CAMPAIGN.zip](https://github.com/Regalis11/Barotrauma/files/10097046/SECRET_TESTING_CAMPAIGN.zip)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Do you recall when (or which version) this campaign save was started? There's some backwards compatibility logic in place that forces the "new" end levels to generate in saves done prior to version 1.xxx, so if this save was originally done in the faction-testing branch before the new ending was introduced there, the levels wouldn't have generated.

**Comment by Wheatley1001** [comment]
The campaign was started in version 100.0.0.0 as a private testing campaign.

**Comment by Regalis11** [comment]
I don't think we'll be addressing this, considering it only affects a specific test build that's no longer available anywhere.
