### ISSUE TITLE
Military Outpost Listening Device Quest is quite broken

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#10575]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you get the "special announcement" from the security chief in a military outpost and accept the "listening device" quest from them, they tell you to install listening devices in the crew quarters. However, the dialogue option to install the devices always appears in the dining room/ central room of the outpost. Also, the quest doesn't have a fail condition. It doesn't matter if an outpost guard is sitting a metre away and staring right at you. You will always install the devices and get the money (As well as electrical skill if you're smart).

### Reproduction steps

1. Visit a military outpost
2. Get the special announcement from the security chief
3. Try to reach the crew quarters
4. Watch as the quest dialogue appears in the dining room
5. Finish the quest while surrounded by outpost NPCs

### Bug prevalence

Happens every time I play

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not sure what you mean by "dining room". These rooms maybe?
![image](https://user-images.githubusercontent.com/14351070/204142070-8ceb3201-33f3-49ca-bc96-5274f26bd3db.png)

If so, I think this is working as expected: those rooms are a part of the crew quarters.

**Comment by TheMinerBoy** [comment]
Yeah, those are the rooms I'm referring to. Shouldn't this quest have a fail condition though/ requirements? Right now it's free money. Maybe have multiple possible install points that players can choose, and they have to choose the one with no people watching to complete the quest?

**Comment by Regalis11** [comment]
I agree it'd be a more interesting event if there was a failure condition, although I think that's more of a feature request than a bug report.
