### ISSUE TITLE
Slip suit requires more material than intended to craft

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10571]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Due to xml element inheritation, Slip suit requires an extra Ti-Al and an extra rubber to craft.
Logically, it doesn't make sense to require an extra titanium-aluminum alloy to upgrade a combat suit into a slip suit because slip suit doesn't provide more protection but only a boost to swimming speed.
And for long-term development and modding improvements. We do need a way to partially inherit elements from xml.

### Reproduction steps

check slip suit recipe in a fabricator

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The slipsuit recipe has been reworked and this issue fixed in https://github.com/Regalis11/Barotrauma-development/commit/e4d15867e61df2d86429cbdee54558fcf7551f84

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
