### ISSUE TITLE
[WIP]Russian language

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1058]
**Description**
At the moment, translated:
- Professions;
- Affliction;
- Mission;
- AI order/report;
- CodeWords;
- EnglishVanilla;
- EnglishVanillaLoadingTips.

**Version**
Windows. 0.8.9.2.

**Additional information**
All text has been checked by me, so there may be errors. Sign" (?) "at the end of the line I indicated that I could not translate correctly. Some words have been left untouched, as in Russian it sounds stupid or is too long (Ragdoll, Use that SEED...).

After a short rest I will translate:
- A description of the items, their name;
- Structures;
- Conversation AI.

___---====---___
**Описание**
На данный момент переведено:
- Профессии;
- Болезни;
- Миссии;
- Приказы для ботов, репорты;
- Коды для Предателей;
- EnglishVanilla;
- EnglishVanillaLoadingTips.

**Доп. информация**
Весь текст был проверен мною, поэтому могут быть ошибки. Знаком "(?)" в конце строчки Я обозначил то, что не смог корректно по смыслу перевести. Некоторые слова оставил нетронутыми, так как на русском звучит глупо или слишком длинно (Ragdoll, Use, SEED...).

После кратковременного отдыха Я переведу:
- Описание предметов, их название;
- Структуры (стены);
- Разговоры ботов.

P.S. Хейт со стороны некоторых Игроков ожидаем (Especially for Russians).

https://drive.google.com/drive/folders/1cF7jLuxyjnUpulrAplAwA_jTOuOroByO?usp=sharing

**Comment by Regalis11** [comment]
I don't think the issue tracker is the right place for this - the tracker is intended for bug reports and feature requests. Perhaps you could post this in the [modding subforum](https://undertowgames.com/forum/viewforum.php?f=20&sid=25523583df964ac8e560059ffbd1236f) instead?
