### ISSUE TITLE
[Factions] Non-waterproof containers will spark forever when sodium is inside while flooded

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10582]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems even containers that werent considered waterproof will now constantly spark when in water with sodium inside, and never explode... Also sorry i have no funny comment, its just a minor, seemingly unintended thing
![image](https://user-images.githubusercontent.com/104232152/204113834-44f99ce4-4a90-4e8d-859e-95fb25389b88.png)

### Reproduction steps

1.Put sodium in a regular cabinet
2.Flood said room with the cabinet
3.Watch it spark, but never explode

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Ignore the name changes, i cannot type properly apparently

**Comment by Rehexr** [comment]
Duplicate, yada yada

**Comment by WeebCactus** [comment]
Whenever it happens it seems the host begins to drop frames massively

**Comment by Rehexr** [comment]
Closing
