### ISSUE TITLE
Quickfixer and Tinkerer issues 

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10585]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mechanic with Tinkerer cannot repair mechanical devices past their normal max condition. The repair ends at 100 condition instead of it lasting until the condition reaches 140.
Repairing a mechanical device with and without Quickfixer seems to take the same amount of time.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7c292e9f61cb745b76b843d16f3d002f4dfc2529 and https://github.com/Regalis11/Barotrauma-development/commit/b4a32703d3d03c7291dda8b31709fb9f67489d76

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
