### ISSUE TITLE
[Factions] Raptor Bane and mutated raptor bane have different sizes

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10581]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pretty simple, nitpicky, sprite issue again, the sprites for the mutated and regular raptor banes are different, which does seem unintentional.
![image](https://user-images.githubusercontent.com/104232152/204113592-c6a8db3d-538f-4b5b-a291-121ac23511f9.png)

### Reproduction steps

1.Look at em next to each other in the editor (not the inventory sprites)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Not a bug, mutated fruits grow bigger before exploding

**Comment by Rehexr** [comment]
Seems wierd, but ite, ill take it
