### ISSUE TITLE
Abandoned Outpost has weird raised floor

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10594]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is an issue I've noticed in every instance of this module. As far as I know, this module is in every abandoned outpost below the reactor room (it resembles the fabrication and deconstruction module of regular outposts).

As shown in the image below, there are two inner walls which protrude beyond their wall caps and create a weird step. 

![image](https://user-images.githubusercontent.com/105495756/204136387-14c97fb3-eac5-473c-8a89-5530099ae28d.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2806095825ef1a1a392ca165163e18681ddbacbe

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
