### ISSUE TITLE
[Factions] Menu constantly shows rep requirement for Aphotic Plateau 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10599]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This has existed on the menu ever since we passed the Aphotic Plateau.

![image](https://user-images.githubusercontent.com/105495756/204137395-3a06d589-44f7-4070-84e3-1ad9101431a4.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
Found this issue on a new 100.8.0.0 campaign save, seems to happen with Separatists regardless of location. 

![image](https://user-images.githubusercontent.com/105495756/205413408-a0a4cd79-1733-474f-9411-7cee81d7474e.png)

![image](https://user-images.githubusercontent.com/105495756/205413414-affcb745-c278-45ff-b9bf-91622a9e914b.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c664feed2854fdb2dc1d9f72a97140e76e4a3ef0

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d, no issues found, closing.

**Comment by Wheatley1001** [comment]
Hello again!~ Found this issue resurfacing for 1.0.2.0. 
![image](https://user-images.githubusercontent.com/105495756/221043789-7f40c02c-a465-445f-9044-7bdda16bb5f3.png)
![image](https://user-images.githubusercontent.com/105495756/221043807-575ed1db-89e1-454c-9c85-5e9647ff9494.png)

Notice the submarine's location on the map relative to the biome passageways.

**Comment by Regalis11** [comment]
@Wheatley1001 I'm not sure I understand the issue there. In the screenshot you posted, both paths are still unlocked, so unless I'm missing something the menu should still be showing the rep requirement...?
