### ISSUE TITLE
Players within the clown crate can both be inside and outside the crate

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10598]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**I suspect this is due to networking related issues.**

A player hid within the clown crate and from their perspective were still standing. They could run in both directions, but were unable to move anywhere. From my perspective, the player was still within the clown crate but a weird clothing-like appendage was popping out of the right side of the crate.

![image](https://user-images.githubusercontent.com/105495756/204137165-a6184817-655d-4c4a-be9a-9100e97866c6.png)
![image](https://user-images.githubusercontent.com/105495756/204137167-30fd7529-e885-46b3-b56e-22306924297c.png)
![image](https://user-images.githubusercontent.com/105495756/204137181-20d000d6-e7c5-4558-ae05-e593c29c88a9.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd0a5778613960ccaad68a26c29eff374570db05

**Comment by Regalis11** [comment]
> Also, handheld weapons still render (Just use a HMG in the crate to see this or other item).

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e15b2cc48e1af1a4e16255a9af7cd26bfeca0bb

Couldn't repro the other issues

**Comment by NilanthAnimosus** [comment]
For the ability to "melee a player" and cause the desync bug of standing outside of the clown crate when they are in it on the client side this I noted in another bug ticket (But is more relevant here):

Appears to be based on placing the crate at unusual spots physics wise, such as between a hull floor piece and glass piece (IE. azimuth submarine has a few of these in its floors and I did it below the junctions at that hull to glass area on its left side) and when dropped at a place that causes the camera to move back and forth slightly - crowbars will hit then and (although not causing damage as server-side it doesn't actually hit but instead hits client side) will make the player visibly stand at the crate but be unable to move from it before rubber banding back.
