### ISSUE TITLE
New creature drops fit into any container

### ISSUE THREAD

**Issue by bananaman6213** [Regalis11/Barotrauma#10590]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The new creature drops (moloch bone, diver's remains, etc.) are able to fit into any container
While this is reasonable for small items like Spineling's Spikes, larger items such as the Moloch Bone and Hammerhead Ribs are visually much larger than the containers they can fit in
![image](https://user-images.githubusercontent.com/119143410/204116033-44c3f890-e489-490a-8727-ccc8b22f3ccc.png)
![image](https://user-images.githubusercontent.com/119143410/204116198-8d68dc2d-7bc5-4f95-bd1f-009d5459f96e.png)

### Reproduction steps

1. Start any game type
2. Spawn any of the new creature drops (Moloch Bone, Hammerhead Ribs, Spineling's Spike, Endworm/Watcher Shell Fragment, Diver's Remains, Alien Circuitry) and a container of choice (Toolbelt, Storage Container, Crate, etc.)
3. Observe how the creature loot fits into any of the containers

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem specific to the faction branch

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
