### ISSUE TITLE
Saved sub in editor, corrupts it, opening causes crash

### ISSUE THREAD

**Issue by Vaniloth** [Regalis11/Barotrauma#10591]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I saved my sub in the sub editor.  When I clicked confirm, everything in the editor disappeared and the only thing present was an abyssal suit.  I zoomed out and didn't see anything else.  Some kind of message popped up which doesn't usually pop up on this sub.  I didn't read it since I'm used to errors showing up about "ballast" tags and such (critiques to my design), so I closed it without thinking.  Now, whenever I try to open this sub in the editor, the game crashes.
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/10097358/crashreport.2.log)

-Here's a bit of my background.  I've been playing for a while, and my subs are old, half to 3/4 of a year old.  I'm catching them up to the changes from the latest major update some several months ago.  So, maybe the version or age is involved.
-I now have multiple files for the same design.  A couple of my subs appear four times in my file list.  So, there's some sort of mess happening in the background induced from some update.  I don't know why subs are appearing in multiple directories, and I don't know how I should clean it up, so I haven't messed around with them.  I've just been picking one to make changes to.
-The sub that's crashing is a local copy (name not purple).  I made my first edits yesterday, and saved several times without issue.  Today, saving my first edit caused the corruption.  In both days, I played online in other servers before beginning editing.  Yesterday, I added a couple relays, and added/removed some wires.  Today, I just removed like three wires, and added one.  Didn't add new components, and change any of their variables.

I'm failing to quickly reproduce the error.

lmk if I can provide any other information.
  -I guess I'm Vaniloth here.

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Vaniloth** [comment]
[Illuminator.zip](https://github.com/Regalis11/Barotrauma/files/10118858/Illuminator.zip)
Attaching the sub that's crashing.

No pressure on recovering the file.  This is one of those subs that has multiple file paths in the editor.  I already implemented my updates to another copy 👍

**Comment by mygamingaccount** [comment]
Hey @Vaniloth here's your sub, I fixed it
[Illuminator.zip](https://github.com/Regalis11/Barotrauma/files/10124052/Illuminator.zip)

**Comment by mygamingaccount** [comment]
The issue was, not surprisingly, a duplicate Abyss diving suit with the same ID as a wire.

**Comment by Regalis11** [comment]
Fixed the crashing in https://github.com/Regalis11/Barotrauma-development/commit/87cc4ac5686b392cd73fa97d9861694ac8528e67 (now the game logs an error instead of crashing).

The issue that caused this is still not fixed though - I have no clue how that abyss diving suit with the same ID as another item could've ended up in the submarine. If anyone has any guesses or comes up with a way to reproduce the problem, please let us know!

**Comment by NenaTheSilent** [comment]
[Big Belly Barsuk.zip](https://github.com/Regalis11/Barotrauma/files/11019221/Big.Belly.Barsuk.zip)

Had the same thing happen with this sub. I disabled the local mod for a bit, then when I re-enabled it and opened it in the editor it seemed fine at first. As I tried to save it warned me about objects being placed far away, then took me to a single diving suit locker in the middle of nowhere before corrupting the save. 

I'd really like my sub back :(

**Comment by Regalis11** [comment]
@NenaTheSilent I attached a fixed version of the corrupted sub file [in the report you made](https://github.com/Regalis11/Barotrauma/issues/11639).

Unfortunately I still have no clue what's causing these mystery items with duplicate IDs to appear though. :/

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
