### ISSUE TITLE
[Factions] Coalition reputation display is inconsistent between actual rep and map-shown rep

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10596]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Outpost locations show incorrect coalition reputation points in relation to the tab menu and the game's own recognition of how much rep players have with the coalition. We still get bonuses for high rep, but the campaign map seems to display the starting reputation factors (I think, I'm not 100% familiar with starting faction rep).

Curiously, this does not apply to the Separatists. 

![image](https://user-images.githubusercontent.com/105495756/204136654-b58fa794-8af6-44fe-9565-b5cd43b3bfad.png)
![image](https://user-images.githubusercontent.com/105495756/204136679-617f1a06-db9e-4524-8034-4b0af417546d.png)
![image](https://user-images.githubusercontent.com/105495756/204136796-0b05b2b6-a809-4327-9ec7-6d53fdcc1831.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/830d13dce212e16509bcf663a6ebcdf7489e42b2

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d, no issues found, closing.
