### ISSUE TITLE
Allow job preference changes mid-round (During spectator for instance).

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#106]
A feature suggestion I overheard that sounded quite nice, when respawns are enabled but you have set yourself to a class you do not prefer, all you can do is rejoin (Which there are now enough players on barotrauma to easilly take the slot you were playing on) or wait for the round to end.

Instead allow for a way to return to the lobby screen to change the preferences or an in-game menu to rearrange and change the job preferences (Such as a tab in the top left info button perhaps).

**Comment by Crystalwarrior** [comment]
:+1: for sure, this is pretty good
