### ISSUE TITLE
[Factions] Outpost ladder is in front of docking hatch

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10605]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/105495756/204139436-d5e1c82c-ba78-4ebd-87d2-6ce617c4e8a7.png)
![image](https://user-images.githubusercontent.com/105495756/204139446-8be306db-bc1c-4007-8f9f-339014f8463a.png)

### Reproduction steps

1. Start a multiplayer campaign (Typhon 2 was used in the example)
2. Go to the hatch that connects the sub with the outpost
3. Observe the ladder going above the hatch

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c1dd149b72bba78874903c0f2f8cba7f670b81b

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/307f89d6fad8cb458206f814d5b108ae830bd564, no issues found, closing.
