### ISSUE TITLE
Flak Cannons audio is very loud

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10608]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While i assume, that the flak cannon is supposed to be loud, it seems a but extreme, especially with spreader ammo, being at points loud enough to really overtone everything. It's certainly a whole lot louder than a railgun, so might make sense to tune that down a little.
Though this might just be a result ofnthe explosion sound being a lot more "piercing" in the ears, than regular shooting. 

### Reproduction steps

1.Shoot a Flak Cannon with spreader ammo
2.Compare the loudness to that of a railgun shell

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment]
Yea, it was jarring

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6d1e5fb70cc6ab99ab2beb126eb2e53a97e102b6

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
