### ISSUE TITLE
[Factions] You can read the final location's depth through text displays

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10603]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the final level, the navigation terminal's depth meter reads "Error". However, if you create a text display that reads depth it will read the actual depth, which is about 3550 meters. 

![image](https://user-images.githubusercontent.com/105495756/204138754-b2b4c0fc-ae5e-4afd-b5ef-5559e715ebd9.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I don't really see why this is a problem
