### ISSUE TITLE
[Factions SPOILERS] End text issues

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10602]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### This ticket contains screenshots of the end text and lore options. I advise anyone who does not want the ending spoiled to not read this ticket and move elsewhere. You have been warned both here and in the title of the ticket.

With that out of the way, let this be a small mega ticket of the issues we found during the final mission (once we got it working). I'm making one ticket because I don't want to increase the chance of spoiling the ending for other players by having several similar tickets.

Without further ado (I'm padding to move the images further down to make it harder to accidentally spoil it for yourself, I do apologise), here are the three issues we found during our ending.

**First Issue**

Previous dialogue options (represented in green) can still be selected after they have already been selected.

![image](https://user-images.githubusercontent.com/105495756/204138459-295ee471-6fe9-4dc1-ade6-e4ed60e4a52a.png)

**Second Issue**

Both dialogue options show up after one has been chosen, making it unclear which option was actually chosen.

![image](https://user-images.githubusercontent.com/105495756/204138496-4b38c9d0-6667-41b2-8c12-1265f2f528b4.png)

**Third Issue**

"On a Unknown earlier" is, according to Hex, supposed to be the name of the submarine (we used a Typhon 2)

![image](https://user-images.githubusercontent.com/105495756/204138298-7e26013d-c1a9-4412-a40d-731ba2f610b5.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56c52aac4b5bd9759e7b04b2e1a95eba1166868a

**Comment by JeroonBosch** [comment]
Tested 1st and 2nd issue in multiplayer on latest branch. Now it correctly shows which option was chosen, plus previous options cannot be selected anymore, so seems to be fixed.

Only the option that closes the encounter stays open even if another player already closed the convo -> but I think that makes sense and is intended to allow all players to read at their own pace?

One thing that might bother players though, is it multiple people can click options, they may be in the middle of a sentence when the conversation suddenly already moves on by another player clicking something. In the future we could consider a few options to remedy that:
- Only the player that clicked a conversation-answer-option first can answer following options
- Some cooldown/delay before being able to click to continue the conversation (to allow reading without impatient people 'spamming' answers?)

**Comment by JeroonBosch** [comment]
Issue 3 correctly showed Winterhalter on latest

**Comment by JeroonBosch** [comment]
Issue 3:
Before fix in SP: No issue
After fix in SP: No issue
Before fix in MP: Unknown
After fix in MP: No issue

Closed
