### ISSUE TITLE
Scrap Cannon's firing sound is barely audible 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10606]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The sound of firing the Scrap Cannon cannot be heard in any realistic scenario. In controlled environments, the sound can be heard. However, in combat or against walls, the sound of scrap impacting surfaces covers the firing sound of the scrap cannon easily. This can lead players to believe there is no firing sound at all.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
This is still an issue, if you shoot at a door you can hear the scrap cannon but if it hits the sub walls the wall hit sound is twice as loud as the scrap cannon sound. Moving to Team1

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/beded50949dd2bd57e2c41e9f46f19f84b9df4ee

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf

Sounds still play when striking the walls of the submarine, pretty much every time from almost all angles I've tried, as a result it still sounds fairly quiet if used inside a submarine.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e2027c9f9cbff2557adae4725e96bff54a3f0174

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843, no issues found, closing.
