### ISSUE TITLE
Miracle Worker is cruel and softlocks players who die to pressure

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10601]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Miracle Worker talent refuses to let players who die to pressure die. They will remain permanently unconscious. Their vitals show minimal damage but there's nothing you can do to bring them back. 

Attempts at mercy killings failed. From boarding axe beheadings to firing squads of explosive shotgun slugs, nothing could kill the softlocked player.

I knew the cause of death was pressure due to the appearance of the skin being blood red. This was confirmed by the Health HUD after I ran to the other end of the ship in order to make Miracle Worker stop working.

![image](https://user-images.githubusercontent.com/105495756/204137976-84dd323b-0d25-4ac1-9ccd-3022f19256a9.png)
![image](https://user-images.githubusercontent.com/105495756/204137978-745f83f3-7df5-4ebc-b9dc-827982f80da2.png)
![image](https://user-images.githubusercontent.com/105495756/204137984-4f6ca91c-8834-47ad-82e2-317d94c1bdf3.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be specific to the faction branch

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b65fe8baf0c31bddc68cd5b5b7a8dcf40fb35d22

**Comment by Jade-Harleyy** [comment]
Tested in **Unstable v0.20.10.1** - 
Characters now properly die from pressure while recieving "Miracle In Progress" from a medic with the "Miracle Worker" talent.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
