### ISSUE TITLE
[Minor] Typhon 2 layering issue

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10604]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Minor low priority report here. Blood appears behind one of the elements of the Typhon 2's command bay.

![image](https://user-images.githubusercontent.com/105495756/204139038-e5da13bb-58a2-4464-b1c6-b7866d4894ee.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug, decals are set to display at the depth of the background walls
