### ISSUE TITLE
Ore from Mining Missions blocked

### ISSUE THREAD

**Issue by henrique2d** [Regalis11/Barotrauma#10609]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/44242795/204156808-5967e480-05be-4e9c-b94d-cccfbadfe5bc.png)
The ore from mining missions are inaccessible some times

### Reproduction steps

Normal Campaign 

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No steps to repro, closing

**Comment by henrique2d** [comment]
I don't think there are steps to reproduce it, in normal campaign you choose some random mining missions and sometimes they just have their ores between the terrain, totally out of reach
