### ISSUE TITLE
Non-abandoned outpost module spawning in abandoned outpost

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10610]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A regular admin module spawned in my abandoned outpost

Abandoned outpost mission (hosted multiplayer)
Seed: 5DcKIDYu

![image](https://user-images.githubusercontent.com/73229309/204320339-5f48477e-f8a0-4541-ad73-12a0c9dd3e1e.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8d1bd331cb20e7c04520982799102d6be395e201

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8, no issues found, closing.
