### ISSUE TITLE
Rifles with just grenades loaded, show up as unloaded in the ui

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10615]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As always, minor issue, but having a 40mm grenade in a rifle seems to still have it show up as empty. Though i do fear that this might just be a limitation of the "Fullness" of an item being restricted by one bar in the ui, which is unfortunate, wanted to report it regardless.
![image](https://user-images.githubusercontent.com/104232152/204395214-a916772d-efdc-431e-9f0a-9ea0675f94dc.png)

### Reproduction steps

1.Put nothing in a rifle, but a 40mm grenade 
2.Notice it showing up as empty in the ui

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug, the indicator shows the status of the actual ammo instead of the grenade.
