### ISSUE TITLE
Unsupported compression method

### ISSUE THREAD

**Issue by JaxMesa** [Regalis11/Barotrauma#10619]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After accidently deleting mods and subs from Localfiles, I tried to recover them via some tools and I got this, but the game doesn't accept this files anymore and says "The archive entry was compressed using an unsupported compression method". Now, I have no idea what to do, but I very need them back...

### Reproduction steps

1. Start the game.
2. Activate the mod
3. Get the issue in console. 

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Loading submarine "LocalMods/Charybdis/Charybdis.sub" failed! {The archive entry was compressed using an unsupported compression method.}
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at Barotrauma.SaveUtil.DecompressFileToStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 393
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 748
```

**Comment by Regalis11** [comment]
Thank you for the report!

Unfortunately I don't think there's enough information here for us to figure out what could've caused this. It seems the file is corrupted somehow - perhaps it is uncompressed already if you got access to the raw xml of the sub from somewhere? How exactly did you try to recover the file, and with what kind of tools?

**Comment by JaxMesa** [comment]
Thank you for reply.

I used "Recuva"(Link: https://www.ccleaner.com/de-de/recuva) recovery tool. After I got "Unsupported compression method" issue, I started to try out different tools like "Disk Drill"(Link: https://www.cleverfiles.com) and "Win Zip"(which is actully for compression; Link: https://www.winzip.com/en/). They two gave me the same recovered file so it didn't make any sense.

Here is one of many corrupted files:
[Charybdis.zip](https://github.com/Regalis11/Barotrauma/files/10113106/Charybdis.zip)

If you need more information, I am ready to try out everything to get it for you. The files are very important to me.

**Comment by Regalis11** [comment]
I took a look at the corrupted file, but unfortunately could not find a way to resolve the problem. Opening the file, it seems the file is indeed corrupted somehow (or perhaps not a submarine file at all?):

![image](https://user-images.githubusercontent.com/14351070/204571157-a8d85b9e-3100-41d9-a2b5-2e3fef7e7aba.png)

There's a part in the file that seems to be the XML config of a leucocyte, which should not be there in a submarine file, nor in a save file. So I'm afraid it seems like Recuva might have failed to fully recover the file, getting the data mixed up with some of the other game files.

One thing you could potentially try if you haven't already is checking whether you can recover an older version of the submarine from the submarine editor's autosaves (assuming you have edited the submarine(s) in question recently). There's a dropdown at the top of the submarine editor's load dialog that lists the autosaves, and the files can also be accessed in the folder Submarines/.AutoSaves inside the game folder (note that the folder is hidden by default though).

Another potential option is extracting the submarine from a campaign save file if you have any saves with that submarine. There's a player-made tool for decompressing the save file available here: https://github.com/Jlobblet/Barotrauma-Save-Decompressor. If you need instructions for using the tool, I recommend joining our [Discord server](https://discordapp.com/invite/undertow) where you'll most likely find people who can give you a hand.

I'm sorry I'm not able to offer any more help, I can imagine how frustrating the possibility of losing submarines you've spent a ton of time on must be. But I hope you can still find some way to recover them!

**Comment by mygamingaccount** [comment]
```
$  zcat < Charybdis.sub
<Submarine description="" checkval="1294722185" price="42250" tier="3" initialsuppliesspawned="false" noitems="false" lowfuel="true" type="Player" ismanuallyoutfitted="false" class="Scout" tags="HideInMenus" gameversion="0.19.14.0" dimensions="0,0" cargocapacity="40" recommendedcrewsizemin="6" recommendedcrewsizemax="16" recommendedcrewexperience="CrewExperienceHigh" requiredcontentpackages="" name="Charybdis" previewimage="iVBORw0KGgoAAA...
```

base64 png data continues, but before it ends:

```
...iM37wIapqbAGGRDK
gzip: stdin: invalid compressed data--format violated
```

Your recovery program failed to get your deleted file back. It's gone forever.

**Comment by mygamingaccount** [comment]
@Regalis11 you missed an important part, this is not file corruption due to the game or the OS, this is the user accidentally deleting the file.

**Comment by mygamingaccount** [comment]
Reproduction steps should be:

1. Create and save a sub
2. Delete the sub file
3. Attempt to recover/undelete the file
4. Try to load the recovered file

**Comment by Regalis11** [comment]
That seems to be the case, so I think ticket can be closed. Again, I'm sorry we're not able to offer you any more help on this! :/
