### ISSUE TITLE
Apply ActionType.OnSpawn StatusEffect twice

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10622]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This issue has been existing for a long time, but i noticed no one reported it.
as the title says e.g. the following item.xml
```xml
<Item name="" identifier="stunbaton" category="Weapon" Tags="smallitem,weapon,stunner,gunsmith,mountableweapon" Scale="0.5" cargocontaineridentifier="metalcrate" impactsoundtag="impact_metal_light" RequireAimToUse="True">
    <InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="770,0,58,64" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="0,0,191,63" depth="0.55" origin="0.4954025,0.7936202" />
    <Body width="170" height="30" density="25" />
    <ItemContainer capacity="5" maxstacksize="1" hideitems="true" containedstateindicatorstyle="battery">
        <StatusEffect type="OnSpawn" target="This">
            <SpawnItem identifier="batterycell" spawnposition="ThisInventory" count="3" SpawnIfInventoryFull="true" />
        </StatusEffect>
        <Containable items="mobilebattery" />
    </ItemContainer>
</Item>
```
I want the Stun Baton to start spawn 3 batteries, but it got 6, and extra 1 battery droped down.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
It's a feature. On every round start, all of the items are respawned from your save file. That means every time you start a new round, this StatusEffect will be applied.

**Comment by zhu-rengong** [comment]
> It's a feature. On every round start, all of the items are respawned from your save file. That means every time you start a new round, this StatusEffect will be applied.

It was applied twice in an instant.
The code that may cause it in BarotraumaShared\SharedSource\Items\Item.cs
![image](https://user-images.githubusercontent.com/73634685/204951576-83eddbe1-7326-4dab-8e5e-0b058983fb43.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dfae2584c4e7434415d2f3b0872cc32c7b572961

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
