### ISSUE TITLE
Doors don't seem to be weldable

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1062]
I spent an entire bottle of welding fuel in an attempt to weld this door, but it did not work. I also confirmed that the door was not locked just in case that would be what was preventing it.

![2019-02-04_06-42-42](https://user-images.githubusercontent.com/10775991/52264472-60c6e400-293a-11e9-9e11-69cee7ed7c24.png)

**Comment by Regalis11** [comment]
Duplicate of #1053
