### ISSUE TITLE
[Factions] Newest faction build consistently crashes on startup

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10627]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Error message included, basic as it gets
Just start game and recieve a crash, enjoy
[crashreport (22).log](https://github.com/Regalis11/Barotrauma/files/10134332/crashreport.22.log)

### Reproduction steps

1.Start barotauma
2.Dead 

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

[crashreport (22).log](https://github.com/Regalis11/Barotrauma/files/10134346/crashreport.22.log)

**Comment by Regalis11** [comment]
Fixed in v100.8.0.0.
