### ISSUE TITLE
Research Stations having their own category seems redundant

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10629]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The fact that Research stations are Marked in the submarine editor as "Outpost" Machines seems redundant, as they are not only not limited to outposts (as the Winterhalter has one), but have no requirements that would differenciate them from any other Machines that can be installed on the sub when it comes to setting them up.
Also for some reason this has gotten even more noticable, since they are now for some reason at the top of the list, rather than the bottom in the newest Factions update.
![image](https://user-images.githubusercontent.com/104232152/205125815-31151261-2e4d-46e0-98b8-0bcf11fa0ac5.png)

### Reproduction steps

1.Open editor
2.View "Machines" Category

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b5c1c4214216e81897c5dbe79d2b1032665e5d2

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8, no issues found, closing.
