### ISSUE TITLE
Reactor Temperature Boost Up/Down doesn't work in multiplayer game.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10623]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

As the title says.
It seems like there is no synchronization of `temperatureBoost` between the server and the client
I created a test.sub
[TEST.zip](https://github.com/Regalis11/Barotrauma/files/10128922/TEST.zip)
There is a circuit that keeps the temperature of the reactor at the meltdown threshold.

### Reproduction steps

1. Open test.sub and test in sub editor
2. temperature up reactor and it will meltdown after 1s
3. Host a server and start a round with test.sub selected
4. temperature up reactor and it will emits overload particles but nothing happened.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/be13344bee57e2a24f5d4894e774cda4d20bf6b0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
