### ISSUE TITLE
Arc Emitter counted as "Machine" in Sub editor

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10630]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Despite being a handheld item, well, the arc emitter shows up under the machine category, which doesnt make much sense. My best guess is this being a result of the arc emitter being a reworked Electrical Discharge Coil, still belonging in the same category.
![image](https://user-images.githubusercontent.com/104232152/205126330-f8f19db7-775c-4b6f-acbe-1d86cdc86e1d.png)

### Reproduction steps

1.Look at Machines Category in Sub editor
2.1st result is the arc emitter

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b93bb4b71c83668e86594953e6841ad2ae4a4e5f

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8, no issues found, closing.
