### ISSUE TITLE
Steam P2P connection could not be established, Connection from incorrect SteamID was rejected

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#10635]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I kept restarting Barotrauma but couldn't join a specific server, as it was giving me the same error each time. It only stopped after the host restarted the server.

Clicking on a friend's (host's) icon in the server list had no effect (only with a particular friend)
Right-clicking the same host and selecting Join Game in the Steam friends list would make the game attempt to connect me to the SteamID of a client on the server (see - error)

It would always connect to the same ID of a _client_.

Note that the first Steam ID (`expected`) in the error is a client, while the second ID (`got`) wasn't even on the server at that time, which has been confirmed by a few friends.

### Reproduction steps

try to join a host
I didn't try connecting directly or from the server browser. This was the only time such a thing happened to me.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Connection from incorrect SteamID was rejected: expected STEAM_1:0:47525763,got STEAM_1:0:419526879
```

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Seems like a one-time occurrence, and without clearer repro steps I don't think there's much we can do about this.

**Comment by P6g9YHK6** [comment]
on my side this error happens plenty of times since i reinstalled the game.

![image](https://user-images.githubusercontent.com/17877371/224573422-aab695d2-ba6e-4510-a9da-4ca598e39648.png)
