### ISSUE TITLE
Minor Spelling Mistake (Alien Circuitry desc).

### ISSUE THREAD

**Issue by GlitchAnims** [Regalis11/Barotrauma#10633]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![imagen](https://user-images.githubusercontent.com/38194089/205134216-8bbc3e19-fdb6-4849-996f-8f6d8ef171ca.png)

Please use the word "Inorganic"
"organic**AL**" is also the old version of "organic"
I am malding
I am fuming
I am coping
please.

### Reproduction steps

Read

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Internal note: fixed this in the localization kit, let's wait for the next loca batch to be imported before closing this.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
