### ISSUE TITLE
Chairs missing drawuserbehind="true"

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10639]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unlike beds, you will always sit infront of chairs when their sprite depth is 0.500+
Chairs are 0.100 by default

![image](https://user-images.githubusercontent.com/73229309/205202759-d98ed5ee-3c5e-4ca0-ba46-935a43be892e.png)

Simply add `drawuserbehind="true"` to the Controller line

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a857fddd31b408c9c9f233b34d968a16a0c9186

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/aa8388e4f9e8067110ef6827b3b1760f5a2f3f97, no issues found, closing.
