### ISSUE TITLE
Alien Flares are very rare

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10632]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Well the Alien Flare is a funny one, for one, it cant be crafted, so it has to be looted from somewhere, but even then its only ever in Abandoned outposts, and not exactly frequently either (During my full singleplayer playthough i have found exactly 1 single one lol).
Frankly i dont even know if theres much of a point in redeeming the Alien Flare, but either way gotta report the fact that it theorhetically exists, but practically not really, putting them into a bit of an odd spot when it comes to existance.
Frankly id just reccomend making them craftable at large amounts for Incendium, so that they can at least be aqquired somewhat normally.

### Reproduction steps

1.Alien Flare :pensive:
2.Refer to previous part
(3.Alternatively, try to aqquire an Alien Flare under normal means, being noticably hard to get for its worth)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
And consider renaming it to "Incendium Flare" to reflect the change.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3868d0200efebf0de10f0ff9d2778cd9430743ff

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/7f4419b844f51ca2fa31f33f7c509ab1eb783aeb no issues found, closing.
