### ISSUE TITLE
duplicate submarine in editor (again)

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10634]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

once again, there's duplicate entries in the submarine loader

![image](https://user-images.githubusercontent.com/5103517/205137033-d54368e8-c3f8-46ad-b3d9-c5735e704eda.png)

![image](https://user-images.githubusercontent.com/5103517/205137058-22c037f4-2f55-4324-b4db-f10473081651.png)

but only for this one. my other submarines are not duplicate

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No steps to repro, closing
