### ISSUE TITLE
[Factions] Rex (Special Civilian Transport Event) mission gives no reputation 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10648]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon selecting the mission for the event mission that transports a man and his mudraptor, it was noticed that there is no reputation gain or loss for accepting the mission.

![image](https://user-images.githubusercontent.com/105495756/205412418-9d092fdb-630b-450e-ada5-3be4de10137d.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
There should be no reputation gain from this event as it's not related to any faction.
