### ISSUE TITLE
Harpoon Coil-Rifle can fire without a battery if it has a flashlight with a battery attached

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10646]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you remove the battery of the Harpoon Coil-Rifle, the weapon can still fire after the charge-up sequence providing it has a flashlight attached to it with a functioning battery. It makes the charging sound and proceeds to fire the harpoon.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not specific to the faction branch.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@46af183.

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/0b2d49ccd119c0e932389f71cf6fa7ab6d7680f0 no issues found, closing.
