### ISSUE TITLE
[Factions] Dugong caught clipping through the Clown District

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10644]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

We entered a new outpost with the Dugong and the crew quickly discovered it had merged with the Clown District. Players could clip into the rooms and submarine as if they were one entity, though sometimes walls would act like walls again and trap players.

Here's the seed:
![image](https://user-images.githubusercontent.com/105495756/205387379-11e479d5-59df-4778-b059-2a21594fe9ca.png)
(Maughanasilly Fossa)

Here's the compressed save file:
[Submarine x Outpost.zip](https://github.com/Regalis11/Barotrauma/files/10144367/Submarine.x.Outpost.zip)

And here are some screenshots of the wacky event!

![image](https://user-images.githubusercontent.com/105495756/205387344-afa61f8f-9b90-4e3e-8606-992dd74f1006.png)
![image](https://user-images.githubusercontent.com/105495756/205387359-b910f78e-16fe-4239-9b03-d59b50b0cfec.png)
![image](https://user-images.githubusercontent.com/105495756/205387400-bff8e867-f592-46f1-80ee-f427aaf06c55.png)
![image](https://user-images.githubusercontent.com/105495756/205387418-ddc34ddf-607f-4e21-8f20-013f08e78e5c.png)
![image](https://user-images.githubusercontent.com/105495756/205387437-de153155-93df-4cee-8c55-f980826e66af.png)
![image](https://user-images.githubusercontent.com/105495756/205387473-1a65daf6-2822-435e-aa0e-a143f78522b3.png)
![image](https://user-images.githubusercontent.com/105495756/205387804-3fe4f1ec-12a3-4251-93ed-6b5b4677caf4.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d, no issues found, closing.
