### ISSUE TITLE
Better Than New isn't exclusive to electrical devices

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10643]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The talent Better Than New states repaired electrical devices deteriorate 30% slower but non-electrical devices also benefit from it.
For comparison I used a Battery and a Oxygen Generator as they share the same deterioration speed. They both had the same slower deterioration speed after being repaired.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't seem to be related to the factions nor exclusive to the faction branch

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/92c5e2d4cf73d9bd07970c5744d1213af46aa2fe

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf


Works fine mechanically for junction boxes and other electricals.

Have some concerns for a few electrical devices not tagged as electrical (IE. command and such) not counting. yet also noticed electrical devices such as junctions are not present in the electrical tab (instead in machine only) which had two categories so not sure simply adding the extra category to other electrical devices missing the electrical category is the immediate correct choice here (Short of fixing both so items appear in two or more categories on the sub editor?)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a96aa0052303f0d23fa1344afa3ab97c449ec7b2

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/aa8388e4f9e8067110ef6827b3b1760f5a2f3f97, no issues found, closing.
