### ISSUE TITLE
[Factions] Explosive Cargo description has a minor grammar mistake

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10654]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

"The Jovian Separatists are is offering..." should be "The Jovian Separatists are offering..."

![image](https://user-images.githubusercontent.com/105495756/205414632-14b908b0-3ed0-4c6c-b0b0-2c0cb22597e8.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/258c16b8790f4e3a17345ead9f50270553c187be

**Comment by JeroonBosch** [comment]
No issues found, closing
