### ISSUE TITLE
[Factions] Husk Cultist event text duplicates

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10653]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There were two players actively engaged with the event text (myself and another). I started the event chain, the other player started interacting afterwards. The second player made their dialogue choice which progressed the text forward, but it kept the choice behind for me; thus duplicating the text.

![image](https://user-images.githubusercontent.com/105495756/205414000-4f7e3493-b2a2-489e-b3e1-76044135c0e9.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug, the options are the same for every line of this conversation.

**Comment by Wheatley1001** [comment]
Hey @Regalis11, I hate to tag you in a closed ticket but I don't think I accurately described the issue (the screenshot isn't very helpful in hindsight, should've captured the entire event dialogue). I also don't think #10602 addresses this specific problem.

The "Then we shall make it be" line being used to come back to the event makes sense if a player clicks "I still need to think about this". The issue is that the second player clicked "Yes". When the second player clicked "Yes", the conversation dialogue progressed as normal but it also duplicated the previous message without anyone leaving the conversation. I didn't touch any option, so the only input given was the one that, in theory, should progress the event without needing to repeat itself. 

If this is still intentional behaviour then that should be everything for this ticket, I have no further information to add or questions to ask.

**Comment by Regalis11** [comment]
I'm sorry but I still don't quite understand the issue. What texts duplicated specifically? The lines in the screenshot aren't duplicates (although very similar), and the options are intentionally the same for every step of this event.

**Comment by Wheatley1002** [comment]
Oh my god you're completely right. The two lines are different sentences. The identical nature of the first line and the start of the next sentence, along with the similar length of the sentences made my brain immediately think they were duplicate text. I'm so sorry. 

This could either be dismissed as me being a moron, or you could use it to change the passages slightly so people like me don't end up thinking it's bugged. Either way works. At the very least this ticket can serve as a marker for anyone who thinks it's bugged in the same way I did. Silver linings, right?
