### ISSUE TITLE
Can't create an entity event for Blood Pack - the entity has been removed.

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1065]
Server side error seems to be triggered when a player does some action with a blood pack. Does not crash the server, no crashreport has been created. Does not affect the client, no console errors.
![q8ywxt5](https://user-images.githubusercontent.com/10775991/52265834-9a4d1e80-293d-11e9-9148-08e775795411.png)

**Comment by Regalis11** [comment]
Haven't been able to reproduce this anymore
