### ISSUE TITLE
Sodium constantly flashes without any reason

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10651]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sodium will constantly flash on and off whenever it exists in the world. Even when actively held by a player, Sodium will flash on and off like a light component. 

![image](https://user-images.githubusercontent.com/105495756/205413334-8a1dc77e-b32d-4926-8ec7-c35bdb8cc52a.png)
![image](https://user-images.githubusercontent.com/105495756/205413336-591de844-77a0-4889-b56b-bd933a974d05.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/74d3150022ed2cff0b374f038be5e75af5f156b8

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8
