### ISSUE TITLE
[Factions] Unfriendly outpost greets crew with friendly dialogue 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10652]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When we arrived at an unfriendly separatist outpost, the AI greeted us with "Nice to see a friendly face!". This isn't appropriate given they actively dislike us.

![image](https://user-images.githubusercontent.com/105495756/205413807-2226be7e-3a2f-4208-b895-41ae5fe1cd0a.png)
![image](https://user-images.githubusercontent.com/105495756/205413811-532baae8-03cd-4a35-8255-1141f0753b27.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by oldboot6666** [comment]
how did you get this version?

**Comment by Wheatley1001** [comment]
@oldboot6666 you need to be in the Undertow Games server and find out. It's under NDA (though not legally binding, just something we've been asked to do) so I can't entirely give you detailed instructions on how to get it. Of course, we can still report bugs which is what I've been doing :)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ae3fb074e2979c69f1d3b09e8b87c7194c17ad3c

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d, no issues found, closing.
