### ISSUE TITLE
WARNING: File transfer error: received data without a transfer initiation message

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#10659]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Nothing major this time.

What happens:
1. The console is getting spammed by this warning (in the lobby and at the start of a round). The spam will stop during the round.
2. The game is infinitely trying to download many missing submarines (each time I join the server) and the loading wheel next to my name won't disappear. 
 
Fortunately enough, I can still join the game and the warning spam stops eventually. It started happening today and never stopped.

![Barotrauma_PcsHnNxNV2](https://user-images.githubusercontent.com/10529134/205460794-a37d36fe-558e-4252-bfe5-ca8ad701f845.png)

Mod list:
```
Selected content packages: Vanilla, BaroTraumatic Nightmare, Improved Husks, Barotraumatic Creature Pack, Lua For Barotrauma, CsForBarotrauma, AVP-Aliens, Neurotrauma, Neurotrauma Cybernetics, NT Pharmacy, Enhanced Armaments, Enhanced Armaments Neurotrauma Patch, Visual Variety Pack, ADV Beacon Stations, Beacons Extended, EK | Dockyard, EK | Gunnery, Alarms Extended, Custom Fins and Decals (New custom letters added), Submarine Weapon Sound Makeover, Stations from beyond, Movable and Sellable Wrecks, New Wrecks For Barotrauma (With sellable wrecks), Spoon's Pirate Vessels Expanded, Avali Posters, MoreMissionsMod, Dont Open Debug Console On Errors, BaroCraftables, Acolyte Job, BetterFabricatorUI, No Role Balance v2, BetterHealthUI
Level seed: YasaPhoenix Linea
Loaded submarine: Lucifer (72EC8E70DF927973488714547E0857D2)
```
### Reproduction steps

Join a server

### Bug prevalence

Happens regularly

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
WARNING: File transfer error: received data without a transfer initiation message
```

**Comment by itchyOwl** [comment]
Not sure if this this something that should be addressed or not.

**Comment by Krzeszny** [comment]
I don't remember seeing this error recently
