### ISSUE TITLE
Character reset (removed when dead on round end)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#10660]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The character of one of the players in our host's campaign had died and got removed from the save file completely on round end. The player spawned with a new character. There were no traces of the previous character in the save file after when we returned to the lobby, not of his name and not even of his job (Engineer). There was no way to revert it.

**The name of the character was different than the player's name.**

Mod list from a crash file I got at the same time (coincidentally, I crashed when the round ended):
```
Selected content packages: Vanilla, BaroTraumatic Nightmare, Improved Husks, Barotraumatic Creature Pack, Lua For Barotrauma, CsForBarotrauma, AVP-Aliens, Neurotrauma, Neurotrauma Cybernetics, NT Pharmacy, Enhanced Armaments, Enhanced Armaments Neurotrauma Patch, Visual Variety Pack, ADV Beacon Stations, Beacons Extended, EK | Dockyard, EK | Gunnery, Alarms Extended, Custom Fins and Decals (New custom letters added), Submarine Weapon Sound Makeover, Stations from beyond, Movable and Sellable Wrecks, New Wrecks For Barotrauma (With sellable wrecks), Spoon's Pirate Vessels Expanded, Avali Posters, MoreMissionsMod, Dont Open Debug Console On Errors, BaroCraftables, Acolyte Job, BetterFabricatorUI, No Role Balance v2, BetterHealthUI
Level seed: YasaPhoenix Linea
Loaded submarine: Lucifer (72EC8E70DF927973488714547E0857D2)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)
```

### Reproduction steps

unknown

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid this might be next to impossible to diagnose unless we manage to figure out the conditions this might happen in. To be sure, this player had not opted to create a new character at any point...? Do you by any chance still have that crash report (or did you post it as a separate issue), in case that might've had something to do with this?

**Comment by Krzeszny** [comment]
> Thank you for the report!
> 
> I'm afraid this might be next to impossible to diagnose unless we manage to figure out the conditions this might happen in. To be sure, this player had not opted to create a new character at any point...? Do you by any chance still have that crash report (or did you post it as a separate issue), in case that might've had something to do with this?

The player hasn't said anything about creating a new character, so I'm 99% sure they haven't created a new character. The full crash report is #10661 but nobody crashed except for me.

**Comment by Regalis11** [comment]
No known steps to repro, closing
