### ISSUE TITLE
(XML) Mudraptor eggs in the second and third stage are missing [Holdable]

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#10668]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mudraptor eggs (`mediummudraptoregg` and `largemudraptoregg`) theoretically deconstruct into more materials and cost more, but are unholdable, unlike `smallmudraptoregg`.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I don't quite understand the issue here. Why should they have a Holdable component?

**Comment by Krzeszny** [comment]
> Thank you for the report! I don't quite understand the issue here. Why should they have a Holdable component? The point of the 2nd and 3rd stages is that the egg becomes too large to hold in your inventory, and that you need to find a safe spot to grow it in.

Not that I think it _needs_ a Holdable component, but if stage 2 and 3 eggs cost more (but you can't sell them) and are worth more materials (but you can't place them in a deconstructor), something seems unintended. Furthermore, recent Barotrauma versions have seen cost and deconstructino changes to these items – items you can't sell and can't deconstruct (unless maybe you pre-place one in a deconstructor before it matures).

**Comment by Regalis11** [comment]
Thank you for the clarification!

Yeah, the deconstruction and price definitions are pretty much redundant, considering the items can't be picked up. But I don't think they cause any issues either, so I think this can be closed.

**Comment by itchyOwl** [comment]
Actually both have now Holdable components, since the addition of [new creature loot](https://github.com/Regalis11/Barotrauma-development/pull/3707).

**Comment by itchyOwl** [comment]
So it's changed in the latest unstable.

**Comment by JeroonBosch** [comment]
Yea, should be okay now - figured it could be funny to have mudraptor egg farming be a viable, albeit risky, thing. Stores sell them, so why not give them a purpose.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
