### ISSUE TITLE
Event editor - everything related to tags cannot be edited

### ISSUE THREAD

**Issue by Irradaven** [Regalis11/Barotrauma#10663]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Its not possible to edit anything related to tags in the event editor.
![multi — копия](https://user-images.githubusercontent.com/97521293/205481036-1c519b85-6cd1-4583-8250-15a3bb65922d.png)
When you try, a non-interactive window opens.
![multi — копия (2)](https://user-images.githubusercontent.com/97521293/205481043-81594307-be8c-4a4d-8e87-0ab8d698fa55.png)

### Reproduction steps

1. Load eventeditor;
2. Load any event;
3. Try to edit any "tag" line;
4. Profit.

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7fefea1fff999ef4b9dcd84634093790299d5baf

**Comment by Regalis11** [comment]
Tested, seems to work with no issues now. Closing.
