### ISSUE TITLE
Swarm out of the map!

### ISSUE THREAD

**Issue by sergeykosarev** [Regalis11/Barotrauma#10664]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The swarm just go past the destination outpost and out of the map.

Insted of waiting close to the outpost, they swimed away behind the map generation(not so far, only -+100m, yet they didn`t stop descending).

P.S. I think there should be a barrier in this area for creatures.

https://steamcommunity.com/sharedfiles/filedetails/?id=2897381569 

https://steamcommunity.com/sharedfiles/filedetails/?id=2897381625 

https://steamcommunity.com/sharedfiles/filedetails/?id=2897381661 

### Reproduction steps

Probably not possible to recreate because of random.

### Bug prevalence

Just once

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by GoodDays13** [comment]
I've had this happen before, I had to follow them near the abyss. There should be a thing discouraging them from going a certain distance from the lip.

**Comment by itchyOwl** [comment]
We had a ticket about it: #9528. I'll reopen it and close this as duplicate.

**Comment by Regalis11** [comment]
The older ticket seems to be about a subtly different issue, reopening this one

**Comment by Regalis11** [comment]
Possibly addressed in https://github.com/Regalis11/Barotrauma-development/commit/413859ddb1003e2eda412b08517f5e2438c4f1f7

> Monsters avoid moving outside the horizontal boundaries of the level when using the SteeringWander steering behavior. We have a "hard limit" that forces the monster to swim back in EnemyAIController too, but it doesn't kick in until the monster is some distance outside the level (at the point where the water current starts pushing the sub back).

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/0b2d49ccd119c0e932389f71cf6fa7ab6d7680f0 no issues found, closing.

notes: tried with crawlers, and some mission enemies like multiple hammerhead_m's and used teleport commands, they moved as a group and whenever I moved them past the level boundry they had a strong inclination to return, and never went straight down instead.
