### ISSUE TITLE
The toy hammer is defined to have multiple hit sounds, when ingame only one of them plays

### ISSUE THREAD

**Issue by Mannatwo** [Regalis11/Barotrauma#10677]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So i'm making a mod that adds something similar to the toy hammer, and its supposed to have multiple hit sounds.
Took the toy hammer as a base, and rejoiced, finding out that it declares multiple hit sounds in its xml, which means it should be a cakewalk to give my custom item multiple hit sounds aswell.
The only problem is that its bugged and only one hit sound ever plays ingame.

### Reproduction steps

1. Quickstart with any sub
2. Spawn in a toy hammer
3. Use the toy hammer on a bot repeatedly
4. Observe that only one of the defined hitsounds of the item ever plays, instead of randomly selecting one of them

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@bf20def (bugfixes).

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/0b2d49ccd119c0e932389f71cf6fa7ab6d7680f0

There is a regular hit sound + the toy mallet sound, not sure if the regular hit sound was present before but the toy mallet sound does not always play (even in single player) if you attack fast, needing to take up to 2 or more seconds at times to get the toy hammer sounds to go off consistently.

They are random now, but the inconsistency on whether it plays feels unusual and I feel it always should make one of the toy mallet sounds on hit.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@0f881f7.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
