### ISSUE TITLE
barotrauma for mac cannot connect to win local server

### ISSUE THREAD

**Issue by zyyk78** [Regalis11/Barotrauma#10678]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

cannot connect to my windows server by insert ip in LAN
others Windows player can connect me
however he can join via steam
maybe it's a bug?

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Thank you for the report!

To be clear, is the windows server a dedicated server or one hosted from in-game? If it's the latter, i.e. if you're trying to host a server while being logged in to Steam, and trying to join the server using the same account you're hosting the server on, that won't work.

Are you using the external IP address of the server? If it's in the same local network, you might need to use the local IP address in stead (something like 192.168.xxx.xxx)

**Comment by zyyk78** [comment]
Thanks！
I'm using a local network and other win players can join by input local ip(192.168.x.x)
however, just one mac player cannot do that, but he can only join by steam 
Its' strange !

**Comment by my-drea-ms** [comment]
+1. We can not connect from Mac to Win dedicated server.
Tested with g-portal.com and pingperfect.com dedicated servers.
"Connection timed out"

**Comment by Regalis11** [comment]
Most likely related to https://github.com/Regalis11/Barotrauma/issues/6190, we'll need to check and verify whether the fix implemented for that one takes care of this issue too. Sorry for the inconvenience!
