### ISSUE TITLE
Pyromaniac talent extra burn doesn't work

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10676]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pyromaniac extra burning damage doesn't seem to work. Tested with Alien Pistol and Prototype Steam Cannon which both inflicted the same burn damage with and without the talent.
Ballast flora also takes the same amount of time to kill with and without the talent.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment]
Opened the same save I found the issues on to check again and the extra burn damage somehow works now, I don't know what could have caused it to not work in the first place since I restarted the game a few times while testing and it was still not affecting the damage in any way.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/7f4419b844f51ca2fa31f33f7c509ab1eb783aeb no issues found, closing.
