### ISSUE TITLE
Inherited status effects are sometimes launched twice

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#10675]
Symptoms:
- liquid oxygenite is twice as powerful as intended

- syringes used with the auto injector are twice as strong as normally

Causes:
Items that have components inheriting status effects from other components effectively have duplicate status effects in Item.statusEffectLists, because both components had the same status effects and we added all the status effects in the list. Normally this would be intentional, but with inherited status effects there's just one definition of each effect, so it doesn't make sense to trigger two identical effects. Moreover, this resulted in different outcomes depending on whether the effects were triggered on the ItemComponent.ApplyStatusEffect() or Item.ApplyStatusEffects(). Hence, most medicines worked as intended, but e.g. liquid oxygenite didn't.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@a1b8c3d

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/0b2d49ccd119c0e932389f71cf6fa7ab6d7680f0 no issues found, closing.
