### ISSUE TITLE
Aiming The Sprayer Removes Outpost NPC Markers

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#10671]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Aiming the Sprayer tool, with or without paint/ethanol, makes the icons for the Outpost NPCs to disappear.
![image](https://i.imgur.com/Xqvby9s.png) ![image](https://i.imgur.com/U3LO3yQ.png)

### Reproduction steps

1. Enter an outpost
2. Aim with the Sprayer
3. Notice the NPC markers disappear

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional (the sprayer hides all overlays to make it easier to paint)
