### ISSUE TITLE
HUD Issues when resolution is 5760x1080 (ultrawide)

### ISSUE THREAD

**Issue by totalsoupsloud** [Regalis11/Barotrauma#10679]
Hello Devs, first of all, thank you for this amazing game. You guys deserve some donuts for the office!

I stumbled on a good deal for three 1080p monitors and Baro was the first test on the widescreen!

As I prepare for my immersion to be Extreme Flavor Blasted, I press C...
________________

My Extreme plateau sunk to regular Flavor Blasted, when I couldn't see any of my crews names, or, some of their tasks, making it unusable to see which crew member is assigned to which task. making single player and 2-3 multi-player games very hard to control my NPC mates.

The only other HUD Issue is some overlap using the navigation interface.
________________

I was only able to find a reported test submitted to pcgamingwiki.com , with a resolution of 2560x1080, on the matter of widescreen support. I was able to find many articles persisting for moveable HUD's, and perhaps even separately resizable ones. 

I tried all the HUD settings possible to fix it, but here this post is.

Thank you for reading about this minor gameplay issue.

**Comment by itchyOwl** [comment]
Thanks for the report! I'm not sure if we have ever tested the game on such a resolution, but I guess now there's a good reason to do that!

**Comment by Regalis11** [comment]
Somewhat related to https://github.com/Regalis11/Barotrauma-development/pull/3752 (PR in out internal repo): in order to support Retina displays we need to improve HUD scaling on very large (5K) resolutions.

**Comment by totalsoupsloud** [comment]
Sorry but the link is 404. I hope to find the variable inside style.xml
A quick glance gives me hope to find the right line!

**Comment by totalsoupsloud** [comment]
All I could find was the styling..... 
...not the actual code that dictates the limits of how far the crew list horizontal border exceeds. 
If I was able to find the source code with comments, I could look for whatever I need to fix this.

**Comment by Regalis11** [comment]
@totalsoupsloud that's a link to our private repository, just for our internal use when we get around to addressing this issue.

There are probably quite a lot of places that need some code changes to get the UI to work right, many of them most likely hard to find if you're not very familiar with the codebase. I can't tell off the top of my head where the limits of the crew list are defined, but my guess would be HUDLayoutSettings or CrewManager.

**Comment by totalsoupsloud** [comment]
I was looking and you used this line on 161 under (master/Barotrauma/BarotraumaClient/ClientSource/GUI/HUDLayoutSettings.cs)
     CrewArea = new Rectangle(Padding, crewAreaY, (int)Math.Max(400 * GUI.Scale, 220), crewAreaHeight);
I am trying to find documentation on this "Rectangle" function, and its parameters. 


I also found this on line 100 in (master/Barotrauma/BarotraumaClient/ClientSource/GameSession/CrewManager.cs)
     // AbsoluteOffset is set in UpdateProjectSpecific based on crewListOpenState
     crewList = new GUIListBox(new RectTransform(Vector2.One, crewArea.RectTransform), style: null, isScrollBarOnDefaultSide:   false) { ... };


I am currently trying to find other known open source material that offers multi screen differentiation.

**Comment by itchyOwl** [comment]
Note to myself (or someone else): Let's ask Eetu to test how it looks when we have an unstable build.
