### ISSUE TITLE
[Dev version] Batteries connected to relay components are losing power even if relay components are turned off and not connected to anything else

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1069]
Video: https://streamable.com/eekz9

Also, for some reason if, while connecting things to battery output, you begin the connection at the battery's one, it will not work unless you move the wire to battery's input and back to the output. Starting connection from the thing seems to work fine.

Video: https://streamable.com/8xcxt

Likely related to #329

**Comment by BillCombs** [comment]
It seems that the batteries don't just lose power if you connect them to a relay component without any other connections; you need to connect the relay component to some power consuming item and then turn it off. After that, it does not matter any more if the component is connected to anything power consuming or not.

Another thing i noticed is that for some reason if you turn the relay component back on after disconnecting the wires that lead to any power consuming items, the batteries stop losing power for no reason.
https://streamable.com/whyby

**Comment by Regalis11** [comment]
Fixed in d51c9a2
