### ISSUE TITLE
Wreck extra loot spawn from security allows water reactive materials to spawn

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#10699]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Having Scavenger talent from Security will sometimes spawn water reactive elements, which promptly detonate after a few seconds.

### Reproduction steps

1. Level Security to level 6 and level scavenger.
2. Use said Security to loot wrecks.
3. Repeat until said scenario occurs.

### Bug prevalence

Happens every now and then

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Reviewed and tested https://github.com/Regalis11/Barotrauma-development/commit/7bbaff62f4670d51ff96491dc7db8a0f8468e725, no issues found. Closing and merging
