### ISSUE TITLE
Bots unable to load ammo from anywhere but rack

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#10697]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When all ammo box on racks are not the right type for a weapon, bots will consistently fail to load ammo to gun despite having correct type of ammo, full condition, on the ground next to them. (Tested on double coilgun and chaingun)

### Reproduction steps

1. Assign bot to a sub weapon that uses ammo box
2. Remove all ammo for said sub weapon from ammo racks and fill them with ammo for other weapons.
3. Deplete said sub weapon's ammo.

### Bug prevalence

Happens regularly

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment]
It may be worth noting, bot's seem to be capable of finding ammo when ordered to "Operate Weapons" and their ammo is expended. However when using the "Load Items: Ammo" order recently introduced a few updates back, bots fail to find any ammo.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/32420b0e4ea9565560a9e78a3e300d4a7542a51f

**Comment by itchyOwl** [comment]
Confirmed that it now works.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
