### ISSUE TITLE
Rifle Bullet recipe can't be unlocked

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10693]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The recipe for rifle bullets isn't unlockable by any talents. 
![image](https://user-images.githubusercontent.com/115734437/206870227-2b2c7596-ab50-4fca-b511-0e72a08ebd3d.png)

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Fixed in 8490dab170f583905143378af7c4c8481de2da5c fix/rifle-bullet-recipe branch

**Comment by Regalis11** [comment]
Reviewed the changes and couldn't spot any issues. Merged to release.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
