### ISSUE TITLE
Outpost Module connectivity issue

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#10692]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am unable to access a certain part of the Outpost, because of a lack of ladder and a wall blocking a staircase.
See screenshot below

### Reproduction steps

Issue: 
![20221209142713_1](https://user-images.githubusercontent.com/58775950/206770152-1258263d-ce21-4d9c-a167-6b92e537fe38.jpg)
Seed: 
![no ladder seed](https://user-images.githubusercontent.com/58775950/206770613-5b527b4e-e885-4d04-a36a-2e2998a6483b.jpg)

### Bug prevalence

Just once

### Version

Other

### -

0.20.12.0, revision 7f4419b844

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
