### ISSUE TITLE
[Unstable] Rifle doesn't have a fabricate section in the xml, which means it can't be crafted

### ISSUE THREAD

**Issue by G3jzer** [Regalis11/Barotrauma#10701]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Rifle whose recipe is now unlocked in the Rifleman talent doesn't have a fabricate section in the xml, which means it's not in the fabricator and therefore can't be crafted.

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
