### ISSUE TITLE
Hatches re-appear later due to mechanic Tinkerer Talent

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#10703]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hatches and doors that are broken usually re-materialize when durability reaches 50%. With tinkerer talent from mechanic, they reappear at 70%, which is a potential downside to a talent that may or may not suppose to have it.

### Reproduction steps

1. Level Mechanic to lvl6, level tinkerer talent.
2. Break a hatch/door fully.
3. Use Mechanic to repair said hatch, and observe the timing when it re-appears.

### Bug prevalence

Happens every now and then

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/28bbecf2cde0c366daebb03fb181ae99305b4675

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843

Fixes do not appear to resolve the issue, hatches/doors repair at 50% condition but with the talent Tinkerer this is increased to needing around 90-100 % condition before they become functional doors again.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1721aeb592c9be1d190ad2c374434f94c2334b87

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/27e7acfa61579aa6dab0a4efd040ee2a5b1d2963, no issues found, closing.
