### ISSUE TITLE
Flamer Does Not Require Recipe

### ISSUE THREAD

**Issue by vitrifiedglass** [Regalis11/Barotrauma#10709]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The flamer is _theoretically_ only craftable with a recipe from Pyromaniac (engineer talent). However, no recipe is presently required, see below.

![image](https://user-images.githubusercontent.com/59235840/207515902-1037d2d6-c514-457e-a022-93c4d44a862e.png)

### Reproduction steps

Create or join any game, then attempt to craft a Flamer.

### Bug prevalence

Happens every time I play

### Version

0.20.14.0 (Unstable)

### Which operating system did you encounter this bug on?

MacOS

**Comment by Rokvach** [comment]
Mechanical skill will be lowered for the item otherwise all good, working correctly. Closing.
