### ISSUE TITLE
[dev] instead of requiring ballast tag for ballast pumps, make ai ignore pumps that have setspeed/setlevel being inputed as they wont be able to change them anyways

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1070]

**Comment by Regalis11** [comment]
There's a potential problem with this, a sub might have some specialized pumps that only use those connections in some specific circumstances but can still be operated manually.

**Comment by etet2** [comment]
Instead of checking for a wire, check if the wire is inputing something or is just connected.

**Comment by etet2** [comment]
Also you forgot dev lable

**Comment by Regalis11** [comment]
That wouldn't fully solve the problem. For example, the ballast pumps may not always be receiving a signal (for example when the nav terminal is broken).

**Comment by etet2** [comment]
when that happends, i dont see a reason why not to use them as regular pumps, other than wasting ai's time.
