### ISSUE TITLE
[Unstable] Assistant talent Journeyman Description error

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10708]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The assistant's journeyman talent description contains an error. In the English.xml, the [skillamount] tag is spelt as [skilamount].

Additionally, the journeyman talent's description would cite +20 skill to the crewmates with matching job to the assistant's apprenticeship (as per the xml `<Replace tag="[skillamount]" value="20" color="gui.green"/>`), however the assistant's talent and the other crewmembers' afflictions only give +10.
![image](https://user-images.githubusercontent.com/37850646/207511457-7fe193cc-dbbd-4607-bd33-c731e55cf8cc.png)

### Reproduction steps

1. Start a game
2. Look at Journeyman talent in an Assistant's talent tree

### Bug prevalence

Happens every time I play

### Version

0.20.14.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Closing.
