### ISSUE TITLE
hulls placed in sub editor do not show left border initially

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10705]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

placed a new hull in sub editor, left border is missing until further editing

![image](https://user-images.githubusercontent.com/5103517/207277104-8409b07f-ea0f-4ba1-be7d-2c7f97bba794.png)

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
or at other times, even.

(re-entered sub editor after test mode)

expected is two complete boxes here. horizontal lines missing

![image](https://user-images.githubusercontent.com/5103517/207277628-10b05f38-850c-48cd-8a0d-1fbce716cb55.png)


they only return after moving the view up/down

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cf0e7b4753861d31bc2cae3c84eb8a9643286ee3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
