### ISSUE TITLE
While immune to the needs of oxygen - existing oxygen afflictions do not decrease.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#10700]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Having husk genes and husk infection, once the character turned oxygen immune the oxygenlow affliction simply froze, instead of being removed or reducing itself over time.

Notes - this was  single player, and thus not a sync issue.

![image](https://user-images.githubusercontent.com/29177976/207058187-515b8eef-ca4d-47ea-9835-c06e17c89bef.png)

![image](https://user-images.githubusercontent.com/29177976/207058823-e0c6ad22-c6e7-4856-bd46-bbab237292e8.png)

### Reproduction steps

1. Give the affliction husk genes (Probably not required)
2. Give oxygen low affliction
3. Give husk infection (around 90 strength, or any strength above the oxygen immune threshold)
4. Find it will become stuck and not remove itself in the characters afflictions, causing a permanent vitality loss if high enough until husk infection is removed enough to require oxygen again

### Bug prevalence

Happens every now and then

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a65380942965976dd70ee3c0faad61b7df83ee7

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843, no issues found, closing.
