### ISSUE TITLE
[Unstable] Revenge squad gives incorrect damage resistance values

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10710]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The talent description for Revenge Squad cites a 30% resistance to damage-type afflictions, however the value is actually 70%.

![image](https://user-images.githubusercontent.com/37850646/207517568-062232bc-cbf3-4ae2-ac36-19e673718f27.png)
![image](https://user-images.githubusercontent.com/37850646/207517627-e038ce6e-4bd0-44ad-8c4b-723c62773cd5.png)

### Reproduction steps

1. Start a game
2. fire a revolver round at a character
3. observe with the Health Scanner HUD that it deals 14 affliction strength gunshot wounds
4. give another character the `revengesquad` affliction
5. fire a revolver round at the character
6. observe that the affliction strength is 4, instead of the expected 9 `(0.3*14=4.2, 0.7*14=9.8)`

### Bug prevalence

Happens every time I play

### Version

0.20.14.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
