### ISSUE TITLE
Specialized outposts don't have an increased chance of turning into a colony if they are close enough to one

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10714]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

According to locationTypes.xml, Military, Mining and Research outposts have an added 10% chance of becoming a Colony if they are within the required proximity but due to Colonies being listed as a disallowed location with the same proximity they never gain this bonus. 
```
    <!-- can become a city if there are no adjacent lairs -->
    <ChangeTo type="City"
          requireddurationrange="2,4"
          probability="0.2"
          requiredlocations="City" requiredproximity="3" requiredproximityforprobabilityincrease="2" proximityprobabilityincrease="0.1"
          disallowedadjacentlocations="Lair,City"
          disallowedproximity="2"
          messagetag="locationchange.research.changeto.city"/>
```

### Bug prevalence

Happens every time I play

### Version

0.20.14.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I don't think this caused any functional issues, but removed the probability increase anyway in https://github.com/Regalis11/Barotrauma-development/commit/b5e721f5f67ea7ae0d01d335a7c59062639085a1 since it makes the xml more confusing
