### ISSUE TITLE
[Charybdis crash]

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1071]
Alrighty, listen up yall.

I had killed a charybdis I had spawned using commands.

Unfortunately that resulted in a crash. I suppose that's all the information needed here.

**Comment by Regalis11** [comment]
Was this is single player or multiplayer? Which version of the game did it happen in (I'm assuming v0.8.9.2)? You don't happen to have the crash report?

**Comment by AbominationBanisher** [comment]
Singleplayer and 0.8.9.2

**Comment by Regalis11** [comment]
Alright, thanks for the info. I still wasn't able to reproduce this, would you by any chance still have the crash report?

**Comment by NilanthAnimosus** [comment]
If you cant get the crash log anymore (Which is the most invaluable part of any crash) then reproduction steps like the method of killing might be something. I don't think there is nearly enough information here to workout if the crash is even related to a charybdis or what could have potentially caused it.
