### ISSUE TITLE
HMG magazine spawn with assault rifle round

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10713]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

File: weapons.xml, line 1548
```
    <ItemContainer hideitems="true" capacity="1" drawinventory="false" canbeselected="false" ShowConditionInContainedStateIndicator="true" SpawnWithId="assaultrifleround" removecontaineditemsondeconstruct="true" containedstateindicatorstyle="bullet">
      <Containable items="hmground" />
      <StatusEffect type="OnUse" target="This" condition="-1" disabledeltatime="true">
        <SpawnItem identifiers="hmground" spawnposition="ThisInventory" />
      </StatusEffect>
    </ItemContainer>
```

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Tested and couldn't find any issues, closing
