### ISSUE TITLE
Morphine and Fentanyl are marked as suitable treatments for Husk Infection despite not healing it whatsoever

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#10712]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Morphine and Fentanyl are set to have 50 and 75 suitability respectively as a treatment for Husk Infection, however they don't actually decrease Husk Infection whatsoever.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/593e189e4fdebcb371e7657880b30c5fdfaa5fa5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
