### ISSUE TITLE
[[Unstable]] Quickdraw affliction does not get reduced when firing revolver

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10711]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The captain's talent Quickdraw's description says "If it has been longer than 8 seconds since you've attacked with a pistol, your next attack with a pistol is 25% more powerful."

However the quickdraw affliction is only removed when firing if the affliction is already at 8 (i.e. the maximum, and the threshold at which the damage bonus is applied)

This means that it does not matter how many times a revolver is fired, the affliction will continue growing until it reaches the maximum.

For example:
The affliction is at maximum
Captain fires revolver at a character (thus setting the affliction back to zero)
Captain waits 4 seconds, then fires again. This does not reset the affliction back to zero.
After another 4 seconds, the affliction is at full strength, and the damage bonus will be applied.

This contradicts the description of the talent, because it has not been the full 8 seconds since a revolver was last fired.

### Reproduction steps

1. Start a game
2. give the talent to a character via console (+ a revolver and enough bullets)
3. Fire the revolver repeatedly at a character
4. Observe that the quickdraw affliction still appears, even though it has been less than 8 seconds since the last attack.

### Bug prevalence

Happens every time I play

### Version

0.20.14.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly.  Closing.
