### ISSUE TITLE
Wrecked Coilgun/Railgun condition cannot be set above 0

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10718]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wrecked Coilgun/Railgun cannot be set above 0 in sub editor; even if you edit the value to 100 when loading the game it will still be 0. Saving the submarine doesn't work either

`fixitems` repairs them fully and makes them useable

Might prevent thalamus from using guns entirely

### Reproduction steps

1. Open sub editor
2. Place and wire a periscope and a wrecked coilgun
3. Change wrecked coilgun condition to 100
4. Test (it doesn't work)
5. F3 and `fixitems` (it works)
6. Go back to editor
7. Coilgun condition is 0

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
I've set the condition to 100, which for some reason sets it back to 0

Condition to 5 somehow makes it work
Thalamus coilguns are however broken until you use fixitems

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
