### ISSUE TITLE
Camaraderie talent description implies it works with assistants whilst talent ignores assistants

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10729]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This was mentioned in #10169.

The description for Camaraderie is "Whenever you finish a mission without a crewmember dying, your crew gains an additional 20% experience". There is no mention of the deaths of assistants not counting. However, the code for the talent implies that the deaths of assistants do indeed not count. 

![image](https://user-images.githubusercontent.com/120612589/207935478-dcf83efa-b1b1-42d4-a41b-d200b37f69c9.png)

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Since assistant deaths pretty much never count, decided adding text was the way to go

**Comment by Regalis11** [comment]
No issues found, closing
