### ISSUE TITLE
Non-hitscan projectiles are going through doors.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#10728]
Version: v0.20.15.0

Non-hitscan projectiles like harpoon spears and syringes are going through doors when shot. Doesn't affect hitscan weapons like revolvers, smg etc.

Fixed in Regalis11/Barotrauma-development@e841cde.
Caused by Regalis11/Barotrauma-development@f3f08c9.

**Comment by Regalis11** [comment]
Can't spot any issues in the changes, and can't think of any side-effects they could cause, moving to QA.

**Comment by Rokvach** [comment]
Tested, I didn't find any issues with this. Working correctly, closing.
