### ISSUE TITLE
Horizontal sprite origin value is reversed on conditional sprites if the character is flipped

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#10721]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Horizontal values for "origin" on sprites used by limbs are reversed if the sprite in question is a conditional sprite and the character is flipped.

### Reproduction steps
This issue can be technically seen in baby molochs and molochs if they die while flipped, though their conditional sprite's origin needs to be tweaked in order to properly see the issue.
1. Modify the baby moloch's ragdoll so that its main limb's sprite and conditional sprite has an origin of 0.1, 0.5
2. Use the "kill" command in the editor while the baby moloch's ragdoll is not flipped, notice how the position of the conditional is the same as the normal sprite
3. Swap to a different character and then back to the baby moloch to quickly bring it back to life
4. Use the "kill" command while the baby moloch's ragdoll is flipped (move the character to the left until it flips), notice how the conditional sprite visibly snaps backwards, as if the origin was instead set to 0.9, 0.5

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/017f12b2b5e8ebc9667b86f65e3b3b6cd0dda246

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
