### ISSUE TITLE
Spawning a Thalamus'd sub in editor crashes the game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10720]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Spawn a dugong wreck with thalamus enable in sub editor using `spawnsub Dugong_Wrecked true`
Crash

[crashreport (31).log](https://github.com/Regalis11/Barotrauma/files/10230815/crashreport.31.log)

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/153f52fe9dbd89d1b8ac9a9bccce0467c136dee7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
