### ISSUE TITLE
Exosuit has incorrect huskinfection resistance

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10722]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ingame Exosuit husk infection resistance doesn't seem to match up to what it's actually set as.
![image](https://user-images.githubusercontent.com/115734437/207754468-fd4536f1-e702-49d6-b5b0-fc30aa52a35e.png)
`   <damagemodifier armorsector="0.0,360.0" afflictionidentifiers="huskinfection" damagemultiplier="0.5" probabilitymultiplier="0.5" damagesound="LimbArmor"/>
`

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by soledad630** [comment]
This is accurate. Iirc bleed and husk resistance is always a -50% strength reduction multiplied with a x% chance of completely avoiding it, due to the nature of these afflictions.

**Comment by Regalis11** [comment]
This is correct. 50% chance of getting the affliction with a reduction of 50% adds up to 75%.

I agree this is a bit unintuitive/misleading though; we have an existing ticket about changing how these probability-based resistances are displayed: https://github.com/Regalis11/Barotrauma/issues/10323
