### ISSUE TITLE
Higher difficulty campaigns are positively impacted by quality difficulty scaling

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10726]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A level's difficulty determines item quality. Higher difficulty = higher quality. This makes sense for campaign progression. However, harder campaigns that start with high mission difficulty (Hard/Hellish) have insanely high quality drops immediately. Within the Cold Caverns we discovered beacon stations with oxygen shelves filled with masterwork oxygen tanks. Outposts had masterwork tools and excellent quality gear on them. 
By the start of the game, most of the players had incredibly high quality items with little to no effort in regard to obtaining them. This makes the harder difficulty presets of the campaign drastically easier. 

My personal suggestion would be to limit quality scaling based on biomes. Maintain the current difficulty scaling but add a secondary measure that prevents items from exceeding specific quality thresholds based on their biome. That way you still have the campaign progression but won't have masterwork quality items in the Cold Caverns. 

An additional comment would be to remove item quality from outposts outright. Since stealing these items yields little to no punishment compared to the reward, removing item quality from outpost loot would prevent grabbing masterwork items such as a crowbar or welding tool for only a -1 or no reputation drawback.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e0e7e31908637b594fdb8628bd6419bfa85ec016

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
