### ISSUE TITLE
The bug with the captain from the "base"

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1072]
**Steps To Reproduce**
I decided to test the resistance of that NPC from the base. Nothing took him, but when I threw him overboard, he began to continuously "break" from the pressure. So the body else in addition "flew" like a rocket.

![image](https://user-images.githubusercontent.com/33912761/52302584-b46b1900-299e-11e9-94d1-337bd589b6f7.png)

**Version**
Windows. 0.8.9.2.

**Comment by BillCombs** [comment]
Not sure if that is what you used to throw him overboard, but just going to add that it's possible to move that bot around by holding them using health interface menu.
