### ISSUE TITLE
Dirty Bomb has a crafting recipe, is talent locked, but has no talent to unlock it

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10723]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Dirty Bomb cannot be crafted despite having a recipe shown. To check whether this was a bug in the written description, I gave myself every talent in the game. Upon doing so, the Dirty Bomb remained uncraftable to me.

<img width="830" alt="Screenshot 2022-12-15 at 01 25 37" src="https://user-images.githubusercontent.com/120612589/207750619-bcf719c5-745f-43c1-97b9-561efb104ea1.png">
**Figure 1. Me giving myself all of the talents in my testing environment.**

<img width="576" alt="Screenshot 2022-12-15 at 01 25 50" src="https://user-images.githubusercontent.com/120612589/207750645-2c695926-0b4e-4b04-b15f-60749f0a0619.png">
**Figure 2. Dirty Bomb recipe remaining locked behind a talent.**

Idk why my formatting is fucked in this report. Pretend the text is bold or italicised. 

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2809a528e678dd727af9fd54cbd53adbc5e7bb7b

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by Wheatley1001** [comment]
Issue is present in 1.0.0.0.
![image](https://user-images.githubusercontent.com/105495756/218346502-dcc43aa3-c671-4ec2-970b-4ba582f56a9c.png)

**Comment by ndevenney1002** [comment]
![image](https://user-images.githubusercontent.com/90515654/224852721-5b35a397-afc6-463d-9a04-330fedd75d0e.png)
I am having the same issue as of latest update despite having given myself all of the talents
