### ISSUE TITLE
The question of translate the names of items

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1073]
**Description**
Line added to" English Vanilla " based on the example at the bottom in file.
There are no changes in the game.

```xml
  <steelcabinet.Name>Большой стальной шкаф</steelcabinet.Name>
```
**Version**
Windows. 0.8.9.2.

**Comment by Regalis11** [comment]
You can change item/structure names and descriptions using the following (as instructed in the EnglishVanilla file):

<EntityName.steelcabinet>Большой стальной шкаф</EntityName.steelcabinet>
<EntityDescription.steelcabinet>Description here</EntityDescription.steelcabinet>

**Comment by Nevol2110** [comment]
I'm sorry, but there was no "Entity". Only "Name"and " Description".

**Comment by Regalis11** [comment]
Ahh right, the instruction text at the end of the file was not up to date. The one at the top is however, and using <EntityName.identifier> instead of <identifier.Name> should fix this problem.

**Comment by Nevol2110** [comment]
Item descriptions do not work. Used Your template. No result.
```xml
  <EntityName.captainscap>Капитанская фуражка</EntityName.captainscap>
  <EntityDescription.captainscap>Знак неоспоримого авторитета капитана.</EntityDescription.captainscap>
```
