### ISSUE TITLE
Killing the intro tutorial shopkeep basically breaks your save

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10739]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While a bit silly to do practically, killing the intro shopkeep will brick your save file and keep you from progressing, since you can never complete your objectives. Goes for both the inital one and the ones following it.

### Reproduction steps

1.Start campaign with tutorial enabled
2.Kill shopkeep
3.Rot slowly (be unable to progress, ever.)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm not sure if I'm missing something, but this shouldn't softlock the game. None of the objectives are mandatory to complete, you can leave the outpost at any point of any of the tutorials.

**Comment by Rehexr** [comment]
Wasnt aware that using the undock on the nav terminal would let you skip the intro tutorial objectives, good to know, just assumed it wouldn't work, since the map menu doesnt show up. Guess its a non-issue then
