### ISSUE TITLE
Syringes shot at walls/doors make the syringe applied sound.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#10736]
Version: release/dev/any

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@3cd68c6 (feature/poisons, because that branch changes so many things related to syringes).

**Comment by NilanthAnimosus** [comment]
Tested against Feature/Poisons commit https://github.com/Regalis11/Barotrauma-development/commit/693b612aeea8d01afa810b9e97c55743a339375c, no issues found, closing.
