### ISSUE TITLE
Phantom Affliction

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#10731]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My character has the affliction icon for lacerations, but he doesn't actually have any lacerations (He used to but they healed a while ago). Using the medical clinic doesn't get rid of the phantom affliction, even though it shows up in the medical clinic UI. Here's my save file:
[Phantom Afflictions.zip](https://github.com/Regalis11/Barotrauma/files/10241733/Phantom.Afflictions.zip)

### Reproduction steps

I have no idea. I'm guessing:
1. Get lacerations from something (I got them from ship shrapnel)
2. Wait for them to heal
3. Phantom lacerations

### Bug prevalence

Just once

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/454369a339ab98e42b382a14dc672ba7bb83e796

> Fixed affliction icons sometimes being shown above the health bar even if though they're not visible in the health interface. Could happen with limb-specific afflictions: if all of them were below the ShowIconThreshold, they wouldn't shown in the health interface, but the icons above the health bar use the sum of the afflictions in all limbs, which can be above the threshold even if the individual afflictions aren't.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
