### ISSUE TITLE
Broken/missing particle effects. 

### ISSUE THREAD

**Issue by Psyduckdeluxe** [Regalis11/Barotrauma#10733]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

particle effects are missing for some items it seems.  Electrics discharge coil effects not showing when firing, docking port effects missing, broken items not smoking. Possible more? 

weapons and  sparks from wires still working as intended.

### Reproduction steps

start test mode fire electric discharge coil. Does not even show test effects in sub editor.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately wasn't able to reproduce the issue, all the mentioned particle effects seem to be working correctly:
![image](https://user-images.githubusercontent.com/14351070/208140079-97c1153e-2a1c-4a12-a588-c9d0d1321d0e.png)
![image](https://user-images.githubusercontent.com/14351070/208140108-bc3c4739-8a22-4113-a7d6-f31f67312925.png)
![image](https://user-images.githubusercontent.com/14351070/208140135-dfc55a13-d28c-406d-9295-8b91ef870a5e.png)

I wonder if there's something nearby that could be emitting a very large number of particles, causing the maximum limit of visible particles to be reached? What's the particle limit set to in the game settings? You can see the number of particles in the top-left corner by entering the command "debugdraw" in the debug console:
![image](https://user-images.githubusercontent.com/14351070/208140414-5e559bd4-3e77-41f4-8878-db383d0ee8ba.png)

**Comment by Psyduckdeluxe** [comment]
Im 1 of 3 people now who all confirmed this being an issue...just had another guy check on discord sub builders >.<
Did i select unstable release and its been fixed there or something ?  Since we are all  missing them?

**Comment by Psyduckdeluxe** [comment]
ahh was just told it is fixed in unstable

**Comment by Regalis11** [comment]
We have done nothing to address this in unstable actually. I did that testing in the current stable version, but could not find any issues.
