### ISSUE TITLE
Unique NPC Appearances Are Not Unique: A Collection of Instances

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10730]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Introduction
There are many unique NPCs within the world of Barotrauma. These NPCs come with their own events and splash art, complete with flavourful descriptions of the person you're interacting with. However, as you will see from the screenshots below, the descriptions of these people do not match the visual representation of these people. As a matter of fact, they all seem to look identical: grey hair, pale skin, and male. 

### Man and his Raptor
This NPC comes from the **Special Civilian Transport** mission and its respective event, in which you transport an NPC along with his friendly pet Mudraptor. Below is the first interaction a player witnesses at the event's start.

![image](https://user-images.githubusercontent.com/105495756/202925423-b4fa3b63-23ab-4fe7-a028-61d1f3f3d32b.png)
_Figure 1. Man and his Raptor starting event dialogue. Notice the black beard and medium skin tone._

The artwork for this character shows a man with a thick black beard with medium toned skin. As you can see in the same screenshot, the man standing before the player is one of a sickly pale complexion with grey hair and no beard. 

### A Bandit turns a new leaf
This NPC comes from an abandoned outpost. Whilst the appearance for this NPC being generic can be justified through it being a random outpost bandit (and subsequently having unique splash arts for every appearance would be completely unreasonable and wildly out of scope), the XML code for this NPC (and most unique NPCs) lacks any specific hair or skin colour section. As a result, it defaults to sickly pale skin with grey hair. 

![image](https://user-images.githubusercontent.com/105495756/202925668-6c610346-46c2-4d73-aa32-3348c05ce64a.png)
_Figure 2. Spawned event at an outpost to demonstrate the initial event dialogue and character that came with it. Notice the difference in skin tone between splash art and physical character._

![image](https://user-images.githubusercontent.com/105495756/202925675-b828c761-b58c-4488-bd57-c6bbac12e453.png)
_Figure 3. The XML file shows what parameters influence character appearance. Click on the image to see it clearly._

### Artie Dolittle
Artie Dolittle needs no introduction. A community favourite, a loved drunkard, and infamous for becoming an immortal god or dying in the first mission. However, not even gods are safe from generic appearance issues. Artie Dolittle's text description describes him as "_A gaunt young man..._". His character shows him having grey hair (not typical for young people to have), whilst the descriptor "gaunt" (Thin or emaciated, bleak or desolate. Synonym of "lean") wouldn't necessarily be used to describe skin tone.

![image](https://user-images.githubusercontent.com/105495756/202925817-7b60a035-cbbc-4c21-9afc-8f8ebaac9924.png)
_Figure 4. Artie Dolittle's event text._

![image](https://user-images.githubusercontent.com/105495756/205440701-999e3c7b-f0ea-4f4f-a423-f496874bd31f.png)
_Figure 5. A close-up of Artie Dolittle's face._

### Honourable Mentions
The following characters suffer similar issues but are less specific with their appearances. They deserve to be mentioned but do not hold specific weight with consistent appearances.
-The Artifact Victim 
-The Teen Stowaway - Titus Zell
-The Shockjack - William O'Kelly

### Conclusion
The lack of skin and hair colour parameters within the XML files for these NPCs causes the grey and pale skins to become the default. This makes every unique character look painfully similar. It also disrespects the splash art's depiction of the character, as the splash art and physical representation show two vastly different people.

![image](https://user-images.githubusercontent.com/105495756/205441609-94c49c1e-6a78-4f63-bb29-2158730f7681.png)
_Figure 6. Top: Titus Zell. Middle: Artie Dolittle. Bottom: Bandit Drug Dealer._

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/752279d99dc4944f4e96827c7d534abb6980004a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
