### ISSUE TITLE
Background needs changing

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1074]
![image](https://user-images.githubusercontent.com/41457828/52311253-cc06c980-29bf-11e9-90c4-2553d72fb174.png)

I suppose something with holes would be better than the boring ol background we have as of now, why not change it?

**Comment by NilanthAnimosus** [comment]
its already been stated on issue #1077 that the menu will be redone.

**Comment by BillCombs** [comment]
Perhaps they meant the background we see behind our sub during the gameplay

**Comment by NilanthAnimosus** [comment]
This is why one shouldn't comment when waking up/tired or drinking. Though if its meant in a level that won't match most biome types. it also will look back towards the abyss where it usually fades out to have no background. But if it can look better than what we currently have I'd be interested to see the difference
