### ISSUE TITLE
Cannot "create new" or swap jobs while dead/in spectator 

### ISSUE THREAD

**Issue by ProphetCrow** [Regalis11/Barotrauma#10741]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Cannot "create new" character while dead/in spectator 
![image](https://user-images.githubusercontent.com/120760556/208210685-0596b281-5b5c-4a5f-b760-68e4e35f3860.png)

I wanted to swap to mechanic and buy an engi bot, create new was available before departing from the station but inst available while dead. 

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c097e3bc4c6de6bb566b70f23c64e85383a39889

**Comment by Rokvach** [comment]
On mission mode I don't get the option to create a new character while I'm waiting for a respawn.

**Comment by Rokvach** [comment]
Moved to team1

**Comment by Rokvach** [comment]
Nvm I was just blind, working correctly. Closing.
