### ISSUE TITLE
Picking up Gene Splicers with a full inventory equips them

### ISSUE THREAD

**Issue by bananaman6213** [Regalis11/Barotrauma#10740]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a player attempts to pick up a gene splicer with a full hotbar it will automatically be "equipped", potentially leading them to use a gene they did not want.

https://user-images.githubusercontent.com/119143410/208202113-908371e0-1580-415e-8377-0dd2efaffa91.mp4

### Reproduction steps

1. Start any game type
2. Fill the hotbar with any item
3. Pick up a gene splicer (either empty or full) from a container or off of the ground
4. The splicer should be equipped and visible in the health menu

### Bug prevalence

Happens every now and then

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
While I understand how this can be problematic, I wouldn't really consider it a bug: the item can go into the equip slot when picking one up if there is no room anywhere else. Imo adding an exception to that rule specifically for gene splicer doesn't seem necessary: it'd make the inventory system more inconsistent just to address a very specific edge case. It'd also raise the question of whether there are other items that can be potentially harmful to equip - should this apply to all of those items too?
