### ISSUE TITLE
When loading a save created in old version, non-full condition items' condition resets to full

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10744]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I created a mod called Material IO which transform item instances into condition of storage containers to reduce the total item count. 
If the condition of the container resets, the materials stored as condition will be lost.
This happens when loading a save created in old version with current version.

### Reproduction steps

1. Start a singleplayer game with old version of Barotrauma (0.19 or older)
2. Use a welding tool, make the fuel can's condition more than 0% and less than 100%
3. Save the game
4. Load the save with current version of Barotrauma
5. Observe the fuel can's condition reseted

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This seems to have happened as a result of the changes we did to address https://github.com/Regalis11/Barotrauma/issues/9850. Unfortunately I think it's a bit too late to address this, as most players have already moved on from v0.19 (only 0.09% active users still in 0.19).
