### ISSUE TITLE
Power Network Issue

### ISSUE THREAD

**Issue by SaiborgR** [Regalis11/Barotrauma#10745]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Power_In pin of Big Engine works in both directions

### Reproduction steps

1. connect battery and power network to Engine
2. power off reactor
3. your sub is powered by battery connecting to engine

### Bug prevalence

Just once

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional, wires connected to the same pin are considered to be part of the same grid. More details on why we ended up going with this approach when we reworked the power system https://github.com/Regalis11/Barotrauma/pull/8184
