### ISSUE TITLE
Appearance resets when selecting a different head

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#10753]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you customize your character in multiplayer, after you have found the hair etc you want to use if you then change head all the sliders will reset. 

### Reproduction steps

1. Host a server
2. Change your appearance by adjusting the sliders
3. Select a different head
4. Notice that everything resets

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@3f32dd2 (bugfixes).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
