### ISSUE TITLE
Smoky background needs changing

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1075]
![image](https://user-images.githubusercontent.com/41457828/52311287-e80a6b00-29bf-11e9-9ad9-a64681cb6fec.png)
![image](https://user-images.githubusercontent.com/41457828/52311298-ee98e280-29bf-11e9-8d10-749fa12e5ebb.png)

It is merely low resolution, making it unflattering to the submarine's shadows as well as the rocks. I suggest it be changed.

**Comment by Rokvach** [comment]
Changed in fb7a69d6179824dde0a44d27ce5143a1a25d0147
