### ISSUE TITLE
Unintended Lighting Wizard triggers + effect

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10752]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/73229309/208267143-660c34bc-29af-448d-8ecc-37858e1f5d21.png)

Lightining Wizard is only supposed to work against melee attacks, but has unintended ranged triggers such as:
-Liquid oxygenite being shot from a syringe gun
-Wall "shrapnel" when a wall is broken

Additionally, it seems to hit multiple limbs at once, triggering the stun multiple times and the effect cumulating for a very long stun time

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7aaf79185fb337132732e044110ab4cb63c1b1db and https://github.com/Regalis11/Barotrauma-development/commit/5daaef515154f6aa71ec94ebb9486154e762792f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
