### ISSUE TITLE
Drinking Rum manually with Drunken Sailor gives wrong affliction

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10759]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Drinking Rum by holding right click bypasses Drunken Sailor's effects, and gives the regular Drunk affliction (instead of drunknodebuffs)

This causes the captain with the talent to potentially go unconscious when drinking.

### Reproduction steps

1. start a game
2. give a captain the drunken sailor talent
3. give the character a few rum and hold right click to drink them
4. the character will go unconscious from drunkenness

### Bug prevalence

Just once

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce4288077dd39cd0dfccf6237c240176b170ff43

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
