### ISSUE TITLE
Magnesium Unretrievable

### ISSUE THREAD

**Issue by LothairKarling** [Regalis11/Barotrauma#10757]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Magnesium found on wrecks (2 different spots) cannot be salvaged and are considered locked items. 
We cant pull it, swap it, or quick switch it. 

### Bug prevalence

Happens every now and then

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
One of the bigger wrecks in the top section where all of the mineral components were.
```

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not find a way to reproduce this. What exactly do you mean by "locked items"? I wonder if it could be that some of the mods you're using modify the magnesium item in some way?

https://user-images.githubusercontent.com/14351070/208295915-042e3492-b8be-420a-b43b-5b294cae843e.mp4

**Comment by LothairKarling** [comment]
I should have taken a video of it at the time.
I have been able to salvage magnesium from other wrecks and other locations in that same wreck at different times, but the magnesium could not be moved or grabbed, and upon clicking on it, it gave the "cannot retrieve item" sound as if it were a large item or i did not have inventory space, despite having ample inventory space both in toolbelt, hotbar, exosuit, and the carried storage containers.  
Both of them also were in the bottom left inventory slot of the cabinet, as opposed to everything else which stacked normally in reading order. 
![Mag ungrabable](https://user-images.githubusercontent.com/77587003/208311527-dead6eb1-68df-4778-a962-96e00b2ecb66.png)
 (Mockup)
 
It may, perhaps, have been a visual bug where magnesium was not actually there. 
I was playing on a public server who was using the europa waifu, improved husks, a submarine editor ships, and i believe that was all. 

I am sorry for the barebones response last time, i was tired and realized i did not provide enough info, if you have any more questions let me know!

**Comment by Regalis11** [comment]
No known steps to repro, closing
