### ISSUE TITLE
Defensebotammobox deconstruction code has "RequiredItem" tag under Aluminum

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10765]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Under the fabrication section of item xml code, "RequiredItem" typically refers to items that are required to craft the object. For deconstruction, this is replaced with "Item". In the "defensebotammobox" code, the deconstruction tab has aluminum under "RequiredItem" which implies you need to sacrifice one aluminum to use the deconstructor. 

This isn't the case, but I wanted to bring it to your attention in case this causes problems later down the line.

<img width="382" alt="Screenshot 2022-12-19 at 01 57 24" src="https://user-images.githubusercontent.com/120612589/208333149-c497aeae-0726-4095-ba4b-f396b41f7f39.png">

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@80a99ee. It should be "Item", like you noted, but "RequiredItem" seems to work as well (the name of the xml element doesn't matter).

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
