### ISSUE TITLE
Radio voice static plays even if you don't have a headset

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10761]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The headset radio static plays even if you don't have a headset on.

### Reproduction steps

1. Join a server with a friend
2. Remove your headset
3. Tell your friend to talk in voice radio
4. Get a room or two away from your friend
5. Hear radio static without a headset

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d9fa17c74b6d2f2e01230bae09dc548b2fdede8

**Comment by Wheatley1001** [comment]
Issue occurs in 100.13.0.0. Played in a campaign save started in the newest build.

**Comment by Regalis11** [comment]
The fix is not included in v100.13.0.0.

**Comment by Rokvach** [comment]
Tested, we were still able to reproduce this issue

Steps used
1. In outpost at airlock
2. One player takes off their headset and walks behind a door
3. Another player stays still with headset still on and talks
4. Player behind door will hear radio static

**Comment by Regalis11** [comment]
It seems my earlier fix only checked if the character speaking has a headset, but not the character receiving the message. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd370fec4d37bb9762ea1554d0ee1216f8d8d0d7

**Comment by Wheatley1001** [comment]
Unsure if the issue was pushed with 100.17.0.0 but it still occurs in that build, although with reduced consistency compared to previous builds.

**Comment by JeroonBosch** [comment]
Tested, no issues found in the fix
