### ISSUE TITLE
Wrecked Sonar transducer using the wrong sprite

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10760]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wrecked Sonar transducer using status monitor sprite
![image](https://user-images.githubusercontent.com/73229309/208311248-2e7494fd-b051-4d76-89f5-eaa6e3432df4.png)

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cf11ad61f134472c301ccfd3a4fc315467a13d72

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
