### ISSUE TITLE
Quality stat type "FiringRateMultiplier" have no effect

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10767]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When creating custom ranged weapons with mods.
Quality stat type "FiringRateMultiplier" doesn't affect the firing rate of the weapon.

### Reproduction steps

1. modify smg's quality
2. add a new stat type as "FiringRateMultiplier"
3. spawn a normal qulity smg and a master quality smg in sub editor and fire them
4. observe the master quality smg's firing rate not changing

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
[Test Mod for Non-Working Quality Stat Type.zip](https://github.com/Regalis11/Barotrauma/files/10255828/Test.Mod.for.Non-Working.Quality.Stat.Type.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/36d8725c8f94a2d4e8d10bbb81ecdfd45102b8f9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
