### ISSUE TITLE
The Defense Bot resists burn damage, which conflicts with Regalis' statement on its burn damage

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10762]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Context/Background
I'm the creature editor for the wiki and have been working on the new pet pages. In the defensebot.xml file, I noticed some parameters which were confusing to me: 
"BurnReduction="2"" 
and 
"<limb
    <VitalityMultiplier type="burn" multiplier="0.5"
 </limb"
(closing statements removed as the code is hidden if they are added)

Overall, I have no idea what this means. What do you do if you're confused? Test it, of course! And that's precisely what I did. 

### Testing Conditions and Modded Files 

I needed two ammunition types to test the burn damage against my control variable: gunshot wound damage. I decided on using the Revolver Round and Depleted Fuel Revolver Rounds. I went into their respective XML files and modified them accordingly:

The Revolver Round had every affliction bar gunshot wounds removed. Gunshot wounds had their strength remain default (28). 
Depleted Fuel Revolver Rounds had the status effect parameter removed and all other afflictions removed. It was set to deal 28 burn damage. 

I studied changes in damage using the Health Scanner HUD item. 

**The overall changes were:**

Revolver Round: All afflictions (excluding Gunshot Wounds) removed
Depleted Fuel Revolver Round: Status effect removed, all afflictions removed, Burn (strength = 28) added

### Results 
The Defense Bot HEAVILY resists burn damage. Both ammunition types dealt 55% damage of their respective affliction types, but the loss in vitality was night and day. The gunshot wound vitality reduction brought the Defense Bot to roughly **40%** of its total health. The burn damage vitality reduction brought the Defense Bot to roughly **80%** of its total health. Images below for visual support. 

<img width="462" alt="Screenshot 2022-12-19 at 00 18 00" src="https://user-images.githubusercontent.com/120612589/208327142-ddd86377-34c9-4033-b6f7-565584e1cd9c.png">

Figure 1. Burn wound vitality reduction on Defense Bot.

<img width="389" alt="Screenshot 2022-12-19 at 00 19 30" src="https://user-images.githubusercontent.com/120612589/208327197-7d594862-7a66-4116-8baf-0ba7c279c734.png">

Figure 2. Gunshot wound vitality reduction on Defense Bot.

### Conclusion
The Defense Bot heavily resists burn damage. 

### Additional Notes
My biggest point of confusion with this entire ordeal is that Regalis himself stated in issue #10383 that "_the defense bot is intentionally vulnerable to burn damage_". The tests show that is not the case.

Any input, questions, or feedback is greatly appreciated. I don't want false information displayed on the wiki.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by itchyOwl** [comment]
Commented this on the ticket: 

> This is incorrect. Defensebot and Fractal guardians are intentionally resistant to burn damage, because they are artificial creatures. However, they are are vulnerable to explosion damage, which often comes from the same sources. They should also be invulnerable to poisons.

So it works as intended.
