### ISSUE TITLE
Cannot download steam workshop content.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#10768]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I installed workshop version cl-lua for barotrauma, and i wanna download a mod, then I find cannot download steam workshop content.
then i verfied files
![image](https://user-images.githubusercontent.com/44423036/208376683-f471001f-99ae-4861-9742-81cb64360972.png)
then the mods can download/update.
i'm not sure this is a vanilla issue or not (but i will report it on github), because i just installed client side lua and find some mods need update, and then i find steam cannot download workshop contents.

https://user-images.githubusercontent.com/44423036/208380240-1ebcc93a-0f84-45be-8ea6-eaa3e39fd71c.mp4

### Reproduction steps

(1. install client side lua)
2. subscribe some mods or update some mods
3. see the steam download page

### Bug prevalence

Happens regularly

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by esirprus** [comment]
anyone have this issue?
and if you have this issue, have u installed client side lua before? 
I'm *just* wondering if changing some files could cause this error.

**Comment by evilfactory** [comment]
Same here, bunch of friends also with the same issue, but i don't think it's Barotrauma's fault, it might be that steam received some kind of update that introduced this bug.

**Comment by Torca2001** [comment]
Seems like a problem on steams end, just had the bug occur repeatedly and it would occur with any mod, closing barotrauma would make steam to validate and then fail validation due to "Missing installed files" for the workshop content and sit there in a loop failing to download and then revalidating constantly. After 10 minutes of repeated failures the validation suddenly passed and all following downloads proceeded as normal.

**Comment by cshingle** [comment]
I ran into this issue a few days ago. It seemed to fix it self after a while.

**Comment by Krzeszny** [comment]
The most annoying bug these days
