### ISSUE TITLE
Z-fighting on husk district walls

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10774]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Seems that occasionally theres some z-fighting on some husk district walls, only came across this twice, so its certainly not consistent in my experience. 

https://user-images.githubusercontent.com/104232152/208501332-b372cfdc-e583-4fe3-9004-ab05e05767a2.mp4

### Reproduction steps

1.Generate some husk outposts
2.Happen to come across one with z fighting walls

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d096e6dbb1f4f841ff178f55f155cf71bb38790b. Can't spot any issues, moving to QA

**Comment by Regalis11** [comment]
Tested, closing
