### ISSUE TITLE
Cruisin' works in reverse

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10775]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Instead of the expected increased 20% fuel rod efficiency it seems like the talent instead reduces efficiency, making fuel rods deplete quicker. 
```
      <Abilities>
        <CharacterAbilityGiveItemStatToTags tags="reactor" stattype="ReactorFuelEfficiency" value="1.1" />
      </Abilities>
    </AbilityGroupInterval>
    <AbilityGroupEffect abilityeffecttype="None">
      <Abilities>
        <CharacterAbilityGiveItemStatToTags tags="reactor" stattype="ReactorFuelEfficiency" value="1.1" />
      </Abilities>
    </AbilityGroupEffect>
```
Increasing the value to 2 resulted in fuel rods depleting about twice as quickly

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Can confirm

0.1 slows down rod consumption, 10 accelerates it

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4cdbd8ce30a5feda1ffaf6fe572f265c4eec281c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
