### ISSUE TITLE
Menu Background Suggestion

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1077]
The floating fish background is getting tiring.

Suggesting you use your own art and add some animations to it and voila, have a gmod style background with the background changing each time you go in game.

![image](https://user-images.githubusercontent.com/41457828/52311430-57805a80-29c0-11e9-9341-d6db472b32bb.png)

**Comment by Regalis11** [comment]
Yep, the menu will be reworked once we get some of the more high-priority tasks out of the way. Here's a quick sketch of what the menu could look like in the future:
![image](https://user-images.githubusercontent.com/14351070/52332449-51f83400-2a03-11e9-8bf4-94a82ddb8906.png)
