### ISSUE TITLE
Sprite bleed issues in structures (Fin Wing Corner 12, Submarine Bow D)

### ISSUE THREAD

**Issue by Anarengon** [Regalis11/Barotrauma#10777]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Fin Wing Corner 12 has some sort of misalignment on the sprite and has a row of pixels show up on the wrong side of it. most visible at sprite scale .6. Same issue with Submarine Bow D easily visible at scale 1.1. 
Picture:
![image](https://user-images.githubusercontent.com/97921339/208625517-1e42eda1-d584-4e66-98dc-feb5f408d6ce.png)

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

Edit: Another instance of the issue on: Fin Wing E 1 
![image](https://user-images.githubusercontent.com/97921339/208778847-36d2dc1e-0799-440e-ad71-3e64ad04e64a.png)

Edit: another instance on Fin Wing D 2 at .8 scale
![image](https://user-images.githubusercontent.com/97921339/208845972-1168b8a0-696e-4632-8ae7-a282b8b0f9f8.png)

Edit: Fin Wing A 3 at .5 scale 
![image](https://user-images.githubusercontent.com/97921339/208849468-e846ed35-eca2-4d65-9e40-b098fcf67e06.png)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1864dd17f874da91989673c8467f98122dc0a5e2
