### ISSUE TITLE
Grid Maintainer repair speed bonus doesn't work

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10770]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Repairing electrical devices with the talent Grid Maintainer doesn't seem to be any quicker than the usual repair speed.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a2c6b5fc5ea54c2d3f6da0b131111c442300078

**Comment by itchyOwl** [comment]
Tested in the sub editor with broken supercharges: fixing the item with the grid maintainer is 50% faster when I ignore the minigame: ~15 seconds vs ~10 seconds (with the same character). So, it seems to be working.

**Comment by Regalis11** [comment]
Note for testing, this affects at least the following talents, possibly more: Grid Maintainer, I Am That Guy, Egghead, Veteran.

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/3f32dd2540c4790006ce65b83e648e1672c88071, no issues found, closing.

From what I can tell its only grid maintainer, I am that guy and egghead currently.

Veteran worked fine, so does grid maintainer and egghead.
