### ISSUE TITLE
Small desc error in submarine editor: incorrect "Mirror Y" tooltip

### ISSUE THREAD

**Issue by WEelCh** [Regalis11/Barotrauma#10771]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The "Mirror X" and "Mirror Y" Buttons are wrongly labled. Both buttons say, they are used to "Mirror the entity horizontally"

### Reproduction steps

1. Submarin Editor
2. Load something or make something
3. Select an element (in Edit Mode)

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f170972f551391d2b418b40f3781f4ae88102e44
