### ISSUE TITLE
No back wall behind humpback ballast hatch

### ISSUE THREAD

**Issue by AlexAr4815** [Regalis11/Barotrauma#10776]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On the vanilla Humpback there is no back wall behind the hatch between engine room and ballast tank A, this allows you to see into the ocean occasionally.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/984dad7c7a56969a9d74c6e2894737bef2f179e0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
