### ISSUE TITLE
[DEV] Capelin Mk4 electrical room ceiling doesn't let water pass through

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1078]
I've seen the ceiling of the electrical room completely destroyed and no water flows through.

**Comment by NilanthAnimosus** [comment]
That is a custom submarine, I think its because the sub designer did not make the hull of that room partially intersect with the outer hull.

![image](https://user-images.githubusercontent.com/29177976/52330020-333a7300-29ec-11e9-8d23-c90569d4cd53.png)

**Comment by NilanthAnimosus** [comment]
Editing the submarine with a hull that intersects with the submarine outer wall:

![image](https://user-images.githubusercontent.com/29177976/52330325-1e121400-29ed-11e9-900a-770568a625b4.png)
