### ISSUE TITLE
Publishing/Updating a mod causes the description to be cut down to the first 255 letters.

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10782]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Publishing/Updating a mod causes the description to be cut down to the first 255 letters.

### Reproduction steps

1. Make your mod description have more than 255 letters
2. Publish/Update the mod
3. Watch the description get cut down.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ee8ddc2eea1ae90b60e297f67485211f1371d2db

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
