### ISSUE TITLE
Egghead effect works at half the described value

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10786]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Egghead description states the skill gain speed increase is +100% but the actual effect is set to +50%

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b58c247

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
