### ISSUE TITLE
[Factions] Faction reputation fails to save in multiplayer

### ISSUE THREAD

**Issue by dakkhuza** [Regalis11/Barotrauma#10789]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever loading a campaign save, all faction reputation will fail to load and instead default back to their starting values.

### Reproduction steps

- Start multiplayer campaign
- Affect faction reputation in some way
- Save and exit
- Load the campaign
- Observe the reputation not being saved

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3f636fb61e3631db45620f8bf4d89f5ae974d322

**Comment by JeroonBosch** [comment]
Tested by starting a new MP campaign, `setreputation coalition 100` and saving + reloading the campaign.
No issues found this way.
