### ISSUE TITLE
battery can't be shift-dropped into charger in editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10787]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

battery cells fit in chargers, but can't be shift-dropped into them... UNLESS they're placed onto the sub already.

video showing attempting to shift+drop a battery from item spawner into charger. highlighter only goes onto the large cabinet.

placing onto the ground and then moving it does work however.

[Barotrauma_22-12-21--eunRu93WBa.webm](https://user-images.githubusercontent.com/5103517/209005464-c25f15d4-446f-4f55-bc9b-93b4355525f9.webm)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa00c5296255225ce3e9a99eb36678aab25c8b46

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
