### ISSUE TITLE
Spec Ops does not properly work with shotguns.

### ISSUE THREAD

**Issue by SadStarfish7** [Regalis11/Barotrauma#10783]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Spec Ops' damage boost on full health targets does not properly work with shotguns.  Where it should apply the damage multiplier with every pellet, it only does so with the first pellet that connects.  Explosive slugs do not have this issue.

### Reproduction steps

1. Start a multiplayer campaign
2. Give yourself the talent "Spec Ops" with console commands.
3. Spawn a riot shotgun and some shells with console commands.
4. Spawn 2 enemies.  (The talent does not apply when firing on crewmates)
5. Shoot enemy with regular shotgun shell.
6. Attack the other enemy using a weak item (Wrench, storage container, etc.) and shoot the enemy with a regular shotgun shell

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/A
```

**Comment by Regalis11** [comment]
Thank you for the report!

I think it could actually be argued this is the correct behavior: the description of the talent says it only works on full health enemies, and that's only the case for the first pellet that hits. Although I do agree that's a little unintuitive, so it might make sense to change.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b402b4b35bd9e795eccc2b652670176d54b9be8b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
