### ISSUE TITLE
Explosive Flak Shells Box recycleitem requires UEX rather than C-4

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#10796]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It requires C-4 to create explosive flak, but only requires UEX to refill it. This means that refilling requires two less plastic to refill. I assume this was missed rather than intended because the recycleitem are typically pretty consistent.
```
    <Fabricate suitablefabricators="fabricator" requiredtime="20">
      <RequiredSkill identifier="weapons" level="50" />
      <RequiredItem identifier="c4block" amount="2" />
      <RequiredItem identifier="steel" />
      <RequiredItem identifier="aluminium" />
    </Fabricate>
    <Fabricate suitablefabricators="fabricator" displayname="recycleitem" requiredtime="15">
      <RequiredSkill identifier="weapons" level="40" />
      <RequiredItem identifier="uex" amount="2" />
      <RequiredItem identifier="steel" />
      <RequiredItem identifier="flakcannonammoboxexplosive" mincondition="0.0" maxcondition="0.1" usecondition="false"/>
    </Fabricate>
```

### Reproduction steps

Take a look at the XML for flakcannonammoboxexplosive

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
