### ISSUE TITLE
crashes when trying to play single player or multiplayer with mods

### ISSUE THREAD

**Issue by lowrck** [Regalis11/Barotrauma#10792]
I keep crashing whenever i try to launch singleplayer or connect to mulitplayer servers with mods. they seem to crash with a path not found error.

**Comment by Regalis11** [comment]
Thank you for the report! Could you please post the error message here? Or if the game actually crashes to the desktop (instead of just displaying an error message), could you attach the crash report here? Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
No known steps to repro, closing
