### ISSUE TITLE
One of Captain Hognose's dialogue segments is replaced by a dialogue segment from "The Crawler with Weird Eyes".

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#10791]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I began to talk to Captain Hognose, selecting all the dialogue options that led to him giving me the quest. For some reason, his second-last dialogue segment was replaced by one from the crawler dialogue tree. I still got his quest in the end, though.

### Reproduction steps

1. Find Captain Hognose
2. Talk to him

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2e1facafedcafd661aacab4be401bd813ed62fd

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
