### ISSUE TITLE
item assembly UI blocks cursor even when the UI isn't active

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10790]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

[Barotrauma_22-12-21--dcT21ySSfN.webm](https://user-images.githubusercontent.com/5103517/209005635-d28e9797-5875-4bcf-8033-332bab7286b7.webm)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d0a1e806a011b79172f6cb505b364bc279f341b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
