### ISSUE TITLE
Endworm doesn't hurt the submarine - he just pushes it

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#108]
So much for an "endworm", right now he's a huge disappointment compared to every other monster in the game (ESPECIALLY charybdis).

pls buff

**Comment by G234i** [comment]
Does he have a hitbox that does the damage upon cintact with a submarine? If so using debugdraw might show if said hitbox can come in cintact with the sub.

**Comment by AlyMar1994** [comment]
Going off how large it is, I wouldn't be surprised if the box is attached to some point of origin for the entity, which usually is at its center.

I do remember having a sub at some point get merked by an Endworm, so maybe it's a more recent bug?

**Comment by NilanthAnimosus** [comment]
The end-worm is actually the least overwhelming enemy unless you park your sub next to a wall and wait, its largest witnessed direct-damage attack was around 1 or at most 2 hull pieces taken off when facing the 'perfect angle' even then not quite guaranteeing the strike.

They DO correctly hit, but they steer so slowly, and its own collider is so massive compared to the size of its attacking limbs, so most attacking angles will generally push harmlessly over actually hitting.

Comparatively a Moloch will one-hit a sub and tear off its hull, crawlers, mantises and tiger threshers are a true and proven threat time and again killing entire crews single handedly.
