### ISSUE TITLE
"Down with the Ship" talent description changes when you have an unspent talent point available and the second row of talents is unlocked

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#10804]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was looking at the Captain's talents when I noticed that the description for "Down with the Ship" changed somehow.
Here is the incorrect/glitched description:
![20221223091826_1](https://user-images.githubusercontent.com/81781733/209375780-f9c0903f-3cc1-40b2-bc08-892a2adcf6fb.jpg)

Here is the correct description:
![20221223122738_1](https://user-images.githubusercontent.com/81781733/209402964-90eddec1-86a5-4319-bcf3-fdc82d52e12b.jpg)

### Reproduction steps

1. Start a Campaign run
2. Look at the "Down with the Ship" talent description
3. Unlock the second row of talents and get a talent point

### Bug prevalence

Happens occasionally

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fabd63ed1fc0c3a6295f6580de6e192a2f5d018a

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
