### ISSUE TITLE
The Infini-Flare

### ISSUE THREAD

**Issue by DailyCounselor** [Regalis11/Barotrauma#10802]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Flares continue to give light source even once it fully depletes.

### Reproduction steps

1. Get into the game
2. Obtain a flare
3. Pop the flare and wait for it to fully deplete
**Flare still continues to emit light even at 0%**

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd81d902abca4460a8f94c2899f5781ce04f290b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
