### ISSUE TITLE
Tutorial/Multiplayer lobby desync when accepting a multiplayer invite during a tutorial

### ISSUE THREAD

**Issue by Azyaln** [Regalis11/Barotrauma#10805]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Accepting an invite via steam to a multiplayer lobby while in the tutorial results in your name appearing in the lobby for other players as expected, however you are still in the tutorial level & cannot interact with objects (I.e mechanical/electrical repair minigame does not work, and neither do controls).

### Reproduction steps

1. Have player 1 enter the tutorial
2. Player 2 creates a multiplayer lobby and invites player 1 via steam
3. Player 1 accepts the steam invite
4. Player 2 can see Player 1 in the lobby, however Player 1 still sees the tutorial and is softlocked (controls/inputs do not work)
5. Even after Player 1 closes the game, their name is still visible in the lobby and they must be kicked

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/09c96b3c984fc8e8637fa82ac14dd726487ed116

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
