### ISSUE TITLE
Ruins fail to fill with water after opening

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1081]
Ruins with an entrance that requires a crowbar to enter failed to fill with water after being opened. The ruin can be progressed further into, but getting out can prove to be impossible.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this. If anyone happens to find a seed where this happens or figure out the steps to reproduce it, please let me know.

**Comment by compilin** [comment]
I just ran into the same issue. Had to enable cheats and use wateredit to navigate through the ruins. showseed says level seed is "ArgadnelSet". You can see on the screenshot, that is the artifact room at the top of the ruins and it's only half full of water

![image](https://user-images.githubusercontent.com/40794281/59149298-105cb180-8a14-11e9-9d02-9cff1cda1f78.png)
