### ISSUE TITLE
Blinking lights desynchronize in gameplay

### ISSUE THREAD

**Issue by MikeBrBa** [Regalis11/Barotrauma#10818]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Lights that have a nonzero blink frequency can be observed to be synchronous in the sub editor but nonsynchronous in gameplay. This happens even when the lights are placed at the same time.

### Reproduction steps

1. Observe a sub in the sub editor with multiple blinking lights (Dugong for example)
2. Open test mode
3. Observe blinking lights

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f386f9a06098ffd572a72a90750d46cc76af43f4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
