### ISSUE TITLE
Giant Spineling drops regular-sized Spineling Spike

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10814]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Giant Spineling drops the regular Spineling's Spike creature loot. This doesn't make sense given the smallest spine on the Giant Spineling is considerably larger than the Spineling's Spike loot that gets dropped.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thought they just spawned a wrong item, but apparently there is no giant spineling's spike item that the players could loot. And on another thought, I don't think it would work anyway. Maybe the giant spinelings should just have some other loot instead?

**Comment by JeroonBosch** [comment]
Since the small spikes deconstruct to Carbon and Zinc, I decided to have the Giant Spinelings just drop these materials in a larger quantity.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
