### ISSUE TITLE
Dirtybomb is currently unobtainable.

### ISSUE THREAD

**Issue by Joku-Suomalainen** [Regalis11/Barotrauma#10823]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

well as the title says the recipe for dirtybombs is currently unobtainable. 
no class has a skill that unlocks the recipe.

### Reproduction steps

![image](https://user-images.githubusercontent.com/82796678/209566927-b3b7656d-ad35-43c1-b8bb-33378734cc91.png)
![image](https://user-images.githubusercontent.com/82796678/209566967-a8c71374-8f48-46f6-88c2-02c55d4046c1.png)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
none
```

**Comment by Regalis11** [comment]
The recipe for the dirty bomb was intentionally removed, but the item will be reintroduced as a part of the upcoming faction overhaul
