### ISSUE TITLE
Pressure Death while infected with Husk material

### ISSUE THREAD

**Issue by JackGA208** [Regalis11/Barotrauma#10825]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was playing on a campaign in the Europan Ridge at a depth of around 3000m aboard a camel operating the front chaingun. I was a sec officer wearing makeshift armor and an iron helmet. I had a gene splicer in my neck with husk genetic material at 14% quality. My husk infection had developed to heavy at 90 something percent. I had been outside of the ship on several excursions without a suit, so the genes were working. Our ship had sunk as we were fighting off a latcher. After being stunned by the latcher and thrown off the gun, I got back onto it only to explode to pressure. 

### Reproduction steps

1. Enter a campaign in the Europan Ridge in a Camel as a security officer wearing an iron helmet and makeshift armor
2. be infected with husk genes 
3. proceed to a depth of around 3000 meters and be attacked by a latcher. 
4. get shocked off of chaingun by latcher attack, then get back on it. 

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1002** [comment]
It sounds like you were in the abyss. Just so you're aware, Husk pressure protection does not cover abyssal travel. You will still die to pressure down there. The way this is calculated seems to be a bit arbitrary though and may require its own ticket. However, being crushed in the abyss is intentional. I hope this helps!

**Comment by ubertpendragon** [comment]
The "Abyss" is a pretty relative thing that doesn't translate well in terms of depth especially in campaign.

In one mission you can die at -2000 depth because you went too far below the level, the next mission you'll be just fine at -3000

**Comment by Regalis11** [comment]
Wheatley1002 is right: the husk infection only protects you from pressure until a certain depth. 

The inconsistent depth is not intentional though. Addressed that in https://github.com/Regalis11/Barotrauma-development/pull/3836

**Comment by Rokvach** [comment]
Tested only issue I spotted was that Spinelings throw a warning

![image](https://user-images.githubusercontent.com/7299826/214964480-36883a38-482e-414d-a1b5-c3c23b0c69ec.png)

**Comment by Regalis11** [comment]
Fixed and merged
