### ISSUE TITLE
Multiplayer Fabricator not working

### ISSUE THREAD

**Issue by dumbabbler** [Regalis11/Barotrauma#10827]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Fabricator does not work in multiplayer games.

The Fabricator shows the craftable recipies correctly and the required materieals can correctly be put into the fabricator.
However when pressing the craft button, nothing happens. Having more or less then the required skill or materials seems to have no effect either

### Reproduction steps

1. Start a multiplayer campain
2. deconstruct some items to obtain materials
3. select a recipe (e.g battery)
4. put the required materials into the fabricator
5. press craft
6. nothing happens

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Potentially related to https://github.com/Regalis11/Barotrauma/issues/10846

**Comment by dumbabbler** [comment]
We did not observe the problem in [#10846](https://github.com/Regalis11/Barotrauma/issues/10846). In fact we were able to deconstruct Hydroxyapatite using the deconstructor.

However we observed our issue (replicator not working) when using the vending machines in a station. 
Reproduction Steps:

1. Start a multiplayer campain
2. Find a vending machine
3. Select a item to be bought
4. Nothing happens

**Comment by Regalis11** [comment]
Yep, on a closer look, I doubt https://github.com/Regalis11/Barotrauma/issues/10846 is related.

I was unfortunately unable to reproduce the issue, both the vending machines and the fabricators seem to work as expected:

https://user-images.githubusercontent.com/14351070/211292921-bc85c2b7-f5de-45d8-937c-8e496e74e8e5.mp4


https://user-images.githubusercontent.com/14351070/211292932-4212c43d-a4c9-4b3a-aedb-35b352a3cb8b.mp4

So I think this requires some specific circumstances to occur. Does it seem to always happen in every campaign, or did it start happening in some specific campaign save...? Are you using any mods?

**Comment by dumbabbler** [comment]
I am not using any mods but i did some further testing.
The bug seems to only occur on my PC but in every multiplayer campaign i host. When installing Barotrauma on a different PC the bug did not occur and fabricator and vending machines are working. I was even able to move the campaign save files to a different PC and use the vending machines and fabricator. This leads me to believe, that there is something wrong with my Barotrauma installation, which can not be recognised via the steam repair option. 
This might also apply to [#10826 ](https://github.com/Regalis11/Barotrauma/issues/10826) as both issues happened when using the same host pc. I will try to check that aswell
