### ISSUE TITLE
Подлодка стыкуется сама по себе

### ISSUE THREAD

**Issue by KaRtOsHkAnS** [Regalis11/Barotrauma#10831]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Когда я беру задание (и без задания) и начаю экспедицию, моя подлодка (дюгонь) через несколько секунд сама стыкуется обратно. 

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by cshingle** [comment]
@KaRtOsHkAnS Are you playing multiplayer campaign? It used to be common for trolls to wire up an component to the docking port to trigger a dock as soon as you undock.

**Comment by KaRtOsHkAnS** [comment]
нет это в одиночном режиме.
Возможно, что после частого нажатия, она багом началась сама стыковаться.

**Comment by cshingle** [comment]
@KaRtOsHkAnS Attach your save to bug report so that the devs can load it up and look at it.

**Comment by Regalis11** [comment]
No know steps to repro, closing
