### ISSUE TITLE
Ceremonial Sword doesn't have a requiredtime attribute set for Fabricate in the XML

### ISSUE THREAD

**Issue by G3jzer** [Regalis11/Barotrauma#10834]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Ceremonial Sword doesn't have a requiredtime attribute set for Fabricate in the XML and it defaults to 1 second in-game.

The deconstruction time is set to 10 seconds by comparison.

### Reproduction steps

1. Go here: Barotrauma\Content\Items\Jobgear\Assistant\assistant_talent_items.xml
2. Find "ceremonialsword"
3. No requiredtime in Fabricate

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
