### ISSUE TITLE
Non-interactable docking ports can still be docked to.

### ISSUE THREAD

**Issue by Herbalicious** [Regalis11/Barotrauma#10836]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have two docking ports lined up on top of each other to decorate the inside of a small chute to get to a shuttle/drone area. (To make it look like a single, long docking port.) The lower docking port is set up as normal, while the higher one is set as non-interactable. Whenever I try to dock after getting just a little too close, (read: just about perfectly lined up with the *correct* docking port) the docking check favours the upper port, causing the entire shuttle to clip into and fuse with the main ship.

Maybe not quite "not as intended", but at least overlooked/unplanned for, I feel.

### Reproduction steps

1. Build a shuttle with top-facing docking port.
2. Build a sub or outpost with a long, bottom-facing docking port built from two separate docking ports stacked on top of each other. (Align the little docking finger things to match up.) 
3. I imagine this is probably an item ID thing, so place the top docking port first?
4. Set the _top_ docking port to non-interactable.
5. Attach the shuttle to the lower docking port, test, undock, and dock again.
6. (Hopefully) see that the sub docks to the wrong port.

I don't feel like I'm describing it well enough, so [here's a picture](https://i.imgur.com/LxLKvJM.png).

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Non-interactable doesn't mean non-functional, I don't see why docking ports should be deactivated

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/860ac5c690d5dc75a2943a0653f19e9b15bf512b by making the game choose the closest port, heavily preferring ports that interactable.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
