### ISSUE TITLE
Thorium fuel rods have unlimited durability in specific circumstances

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10835]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am writing this report because several people have brought it up in the discord server. As of writing, I have yet to successfully reproduce the issue for myself, though my tests have been in the sub-editor. This issue might be more common in multiplayer (though reportedly it occurs in singleplayer too). 

Using masterwork thorium fuel rods in the reactor with the Cruisin' talent unlocked (though some have reportedly done this with regular quality rods) will cause the fuel rods to have unlimited durability. This issue could be exclusive to multiplayer as explained by Jade Harley's theory behind the issue:

"The only thing I can guess is happening is that its trying to change the condition of the rod by a value less than 0.000001, in which case it doesn't allow it to change at all. But even then, doing the math for the default reactor:

0.2 (consumption rate) * 0.8 (cruisin' multiplier) = 0.16

0.16 * (20 (fission rate) / 100) = 0.032

0.032 / 4 (# of rods) = 0.008 (change/rod/second)

0.008 / 60 (# of ticks per second) = ~0.00013 (change/rod/tick)

Although, the server will only send condition updates to clients if the condition change was greater than 1 from the last time it sent a condition update".

I will update this ticket using my own findings if I am able to reproduce this issue personally.

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

MacOS

**Comment by cshingle** [comment]
I have experienced this in multiplayer with masterwork fulguriumfuelrodvolatile. We have a tier 3 scout sub with all the reactor upgrades and our engineer has the talent that makes rods last longer.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2bd4fd2aa805c4aa1fac7009f49c871301f55555

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
