### ISSUE TITLE
Alien Flares Don't Activate On Throw

### ISSUE THREAD

**Issue by VaelophisNyx** [Regalis11/Barotrauma#10843]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Alien flares can't be lit, though can still be thrown. They aren't turning on and just not making light/noise, they're just not even turning on at all.

### Reproduction steps

1. start game
2. spawn an alien flare
3. attempt to light it
4. fail to light it

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment]
investigating this with a small override mod. if i figure it out I'll upload it here for comparison's sake

**Comment by VaelophisNyx** [comment]
addendum; alien flares DO work, but they don't automatically activate on throw like normal flares.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/43b0f128922861b144f5b25d8282d6f0491ab91d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
