### ISSUE TITLE
Talent "Bounty Hunter" and "Logistics Expert" don't give 15% experience bonus

### ISSUE THREAD

**Issue by Cyana-ir** [Regalis11/Barotrauma#10840]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

To test captain talents, I set a new campaign and copy it.

Figure 1. the mission unlocked by "unlockmission killmudraptors_basic
![ILMI(YO2SY3YNK VX{JSLD](https://user-images.githubusercontent.com/106088471/210044961-5e400fde-ab09-4f6b-ad53-6350b17d99f4.png)

Figure 2. the Test guy

![I28@361EV7QY VI$VG( HDU](https://user-images.githubusercontent.com/106088471/210045034-2988f4d8-9c75-46c5-a9f5-f035c4fe3f94.png)

Figure 3. Finising the mission without Talent
![Z1G(%V0~Z@I8C}RAXMLPR~4](https://user-images.githubusercontent.com/106088471/210045096-aa3331e0-a71a-433b-9fb4-98669f4e9eeb.png)

After finishing 1500mk mission with 4% difficulty, Test Guy get 1500*0.09*(1+4%)=140(.4) xp (formula from baro-wiki)

Figure 4. unlock same mission but different destination 
![(7GF44MR OIRF)T9}O11Y7](https://user-images.githubusercontent.com/106088471/210045361-c91ea601-17cb-4156-8c00-9545cbf7b9a3.png)

Figure 5&6. Before and after finising the mission with "Boundy Hunter"
![8FIIY`$N}E4@NA2(7JVXQRK](https://user-images.githubusercontent.com/106088471/210045578-3e2b9954-96d3-4d68-b133-b4c1db58892a.png)

![@0J$E IMTN)0H%2T4_A8UDD](https://user-images.githubusercontent.com/106088471/210045478-cf476fa8-70e2-4cf6-87aa-10726d2cc604.png)

1751mk-26mk=1725mk=1500*1.15
But for xp, it is 1500*0.09*(1+2%)=137(.7) xp  instead of 1500*0.09*1.02*1.15=158(.355)xp

Same problem happened on "Logistics Expert"

### Reproduction steps

1.Start a campaign.
2. Using "enable cheats" to unlock a mission like "killmudraptors_basic“ or "cargoegghusks".
3. Using "giveexperience" to unlock "Bounty Hunter" and "Logistics Expert" for captain.
4. Using "godmode_mainsub" to quickly finish the mission.
5. check experience and wallet.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b4b7714f973f41206f8873a70fe0c52f92793a3

**Comment by NonCancerAlias** [comment]
Should be mentioned that the similar talent for the assistant “Mailman” similarly doesn’t work. Might also be worth checking if the escort experience talents for medics and security work

**Comment by NonCancerAlias** [comment]
I'm probably beating a dead horse at this point but I just discovered that "Station Engineer" doesn't work either D:

**Comment by Regalis11** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/commit/8b4b7714f973f41206f8873a70fe0c52f92793a3, no issues found. Bounty Hunter, Logistics Expert, Mailman and Station Engineer all seem to work. Closing.
