### ISSUE TITLE
[Modding & Consistency] HMG's require HMG Magazines instead of just HMG Ammo to fire

### ISSUE THREAD

**Issue by VaelophisNyx** [Regalis11/Barotrauma#10842]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So I'm bringing this up mostly because of modding issues but basically, if  anyone wants to add *new* mags for the HMG, they MUST override the entire gun to fix this misplaced use of hmgmagazine where it should be hmgammo like every other gun with a magazine. This is a severe issue for mod compatibility overall and it would be nice if this could be cleaned up.

code in question is line 1544 in weapons.xml
`<RequiredItems items="hmgmagazine" type="Contained" msg="ItemMsgAmmoRequired" />`

should be this if consistency is the goal here
`<RequiredItems items="hmgammo" type="Contained" msg="ItemMsgAmmoRequired" />`

### Reproduction steps

n/a

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@f52ba78.

On testing:
Create a copy of the hmgmagazine item and give it a different identifier. Then spawn the new item in the game and try to load it in an HMG.
