### ISSUE TITLE
Trying To Host Server... But Nothing Happens?

### ISSUE THREAD

**Issue by MissWaffleSocks** [Regalis11/Barotrauma#10848]
I'm trying to host a server, like I've done many, many times. When I start the server, everything on the following screen comes up completely blank. Sever name, description, etc. And my server doesn't show up in the active servers, nor is it found when searched for. Is this a common issue? Is this an issue related to mods I'm trying to run? Any help would be greatly appreciated!

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by MissWaffleSocks** [comment]
I deleted my ban list and was able to host
