### ISSUE TITLE
Attempting to autocomplete the setreputation command outside of a campaign causes a crash

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10858]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pressing tab to autocomplete the faction name after `setreputation` causes a crash. Happens while testing a sub in the sub editor and in mission mode. Typing the name and value works fine and shows the "Could not set faction reputation (no active campaign)." error as usual.

### Reproduction steps

1. Quickstart, host mission mode or test any submarine in the sub editor
2. Open console and type "setrep", autocompleting this part works fine
3. Autocompleting the faction part causes a crash

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment]
Included crash log
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/10334496/crashreport.3.log)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6717fc6cc780c11600e43b0263c60a9f20c7692

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
