### ISSUE TITLE
Comparison completely breaks status effect when used inside lightcomponents

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#10854]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Using comparison And/Or in a status effect within the lightcomponent section of an item breaks it by ingoring the conditionals its meant to check

### Reproduction steps

Take an item with a lightcomponent

Make a SE that turn it on if condition is below X, it works

Add comparison="And" to said SE, it now doesn't work at all

At least on the reactor its the case

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not reproduce the problem: the following effect seems to work with no issues (turning the light on when the condition of the reactor is below 80).

```
<LightComponent range="10.0" lightcolor="255,255,255,0" powerconsumption="0" IsOn="false" castshadows="false" allowingameediting="false">
  <Upgrade gameversion="0.9.600.0" lightcolor="255,255,255,0" />
  <StatusEffect type="Always" target="This" IsOn="true" disabledeltatime="true" conditionalcomparison="And">
    <Conditional Condition="lt 80" />
  </StatusEffect>
  <sprite texture="Content/Items/Reactor/reactor.png" depth="0.025" sourcerect="523,0,482,336" origin="0.5,0.45" alpha="1.0" />
</LightComponent>
```

Could you post the XML you're using here so we can try to diagnose the issue?

**Comment by Foxtrot39** [comment]
<StatusEffect type="Always" target="This" IsOn="true" comparison="And">
        <Conditional targetitem="reactor1" condition="lte 25" />
      </StatusEffect>
    
Tested with just this adding comparison prevent light to turn on only one reactor was in the sub editor

**Comment by Foxtrot39** [comment]
also I attempt toturn off when active and it never works usign this

      <StatusEffect type="Always" target="This" IsOn="false" conditionalcomparison="And" >
        <Conditional condition="lte 25" />
        <Conditional targetitemcomponent="Reactor" temperaturecritical="neq true" />
      </StatusEffect>

**Comment by Foxtrot39** [comment]
Attempting to turn it off with the following SE also fails all the time

      <StatusEffect type="Always" target="This" IsOn="false" conditionalcomparison="And" >
        <Conditional condition="lte 25" />
        <Conditional targetitemcomponent="Reactor" temperaturecritical="false" />
      </StatusEffect>

**Comment by Foxtrot39** [comment]
you mean the full item xml or just the snipet of the lightcomponent?

**Comment by Regalis11** [comment]
Thanks! It seems there's an error in that xml: what it's accidentally doing is checking that the item is in less than 25 condition, _and_ that it's `targetitem` property is set to "reactor1". There is no property called `targetitem`, so the conditional will always fail. Removing the `targetitem` check should fix the issue. I'm curious what you're trying to do with that check, and whether there'd be another way to get it working the way your intending it to work?

**Comment by Foxtrot39** [comment]
My mod is about overhauling the reactor so I wanted alarms to go off when either criticaly damaged, overheated or molten fuel rods being inside

Workaround the item part was to simply to make it force the reactor at max heat so I only have overheated or criticaly damaged as conditionals

Now attempting to prevent the overheat alarm to play along the new one I made to warn about fuel meltdown but no succes so far with the connection pannel meltdown out status effect

**Comment by Regalis11** [comment]
I see! I'm not entirely sure what'd be the best way to implement something like that without knowing how exactly the molten fuel rods and the other effects are set up, but the properties `TargetContainer` and `TargetContainedItem` might be what you're looking for. `TargetContainer` makes the conditional target the container the item is inside (reactor the rod is inside), and `TargetContainedItem` makes it target a contained item (the rod inside the reactor).

```
<!-- turn this item on when the container is in poor condition -->
<StatusEffect type="Always" target="This" IsOn="true">
  <Conditional TargetContainer="true" condition="lte 25" />
</StatusEffect>

<!-- turn this item on when the contained item is in poor condition -->
<StatusEffect type="Always" target="This" IsOn="true">
  <Conditional TargetContainedItem="true" condition="lte 25" />
</StatusEffect>
```

Or perhaps something like this?
```
<!-- turn this item on when it's in poor condition but not overheating -->
<StatusEffect type="Always" target="This" IsOn="true" comparison="And">
  <Conditional condition="lte 25" />
  <Conditional TemperatureCritical="false" />
</StatusEffect>
<!-- turn this item on when it's overheating but not in poor condition -->
<StatusEffect type="Always" target="This" IsOn="true" comparison="And">
  <Conditional TemperatureCritical="true" />
  <Conditional condition="gt 25" />
</StatusEffect>
```
