### ISSUE TITLE
True Potential / Chonky Honks don't require clown power to work

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10850]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

True Potential / Chonky Honks don't require clown power to work

It's not mentioned in the description that you need clown power, and the talents don't have clowpower as a conditional, but it seems like an oversight considering Psycho Clown does require it

### Version

0.20.16.1

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
