### ISSUE TITLE
Client rejoin but not control character

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#10857]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I finally found a way to reliably replicate the rejoin and get stuck outside your body issue. We had XML based mods on at the time, but I highly doubt they had any affect of this issue.

The stuck out of body issue is when a player was in the server and left. If they rejoin before their body dies they get in the game and their client thinks it is playing but they do not control their in game character. To fix this they can quit and wait for their body to die, or the `control` command can be used, but that requires cheats be enabled. 

My bet is that the game includes IP address in the identification of what client should control the character. When the client rejoins with a different IP the server recognizes they are rejoining but does not attach the client to their character.

### Reproduction steps

1. Start playing multiplayer round as a client hosted by a dedicated server.
2. Leave/disconnect
3. Change your internet connection (An Australian user switched from wired to cellular data to get a better connection which would also change their IP address. Australian internet is a bad meme at this point.)
4. Rejoin the server before brain death.
5. Get suck outside your body

This seemed to happen regularly when the client switched IP addresses, but I can't say with certainty that it happened every time.
The dedicated server was running on Linux, and the client was running Windows.

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report!

I gave this a test, and I'm not entirely sure if I was able to reproduce the issue correctly. What do you mean by "getting stuck outside the body" - that the client stays as a spectator? To me that doesn't seem like a bug. If you're playing on a dedicated server that uses IP addresses instead of Steam IDs to identify players, a client joining with a different IP address should not gain access to the character.

**Comment by cshingle** [comment]
I was able to replicate this using the following setup.
1) Start the dedicated server on my system using no mods. I set IsPublic="False" in the serversettings.xml so no one else joined.
2) I joined the server using my public IP Address in Direct Join. (I already have port forwarding, etc setup for running a dedicated server from my system.)
3) I had another client running on a different computer with a different steam account join. (Who doesn't have multiple steam accounts that own Barotrauma?)
4) I started a new campaign and then started a round. 
5) I disconnected my client from the server after the round was fully loaded and I was able to move around.
6) I rejoined the server using direct join via 127.0.0.1 (localhost). (This is just an easy way to replicate an IP Address change without having multiple internet connections or any other fancy network setup.)
7) When I joined the game I was unable to control my character and unable to spawn.

This is me stuck in spectator. My character is zig158 which you can see laying on the floor by the nav terminal. Only about 30 seconds have passed since I disconnected, so my character has not yet died.
![image](https://user-images.githubusercontent.com/2231937/211431766-0d787a9e-2ade-4c83-a2e0-6cf2f360ec1c.png)
This is what the player menu looks like. I took a look at both client computers to make sure it looked the same. Apparently the character name doesn't show up twice as I stated earlier.
![image](https://user-images.githubusercontent.com/2231937/211431944-29f88137-501b-4829-91a8-59d7d72a19cd.png)

**Comment by Regalis11** [comment]
Thank you, I think I was able to reproduce and fix this now! https://github.com/Regalis11/Barotrauma-development/commit/5ff3ca9d7ad2000198b2a904f568a113cc3ae9f3

> Fixed rejoining clients not regaining control of their character even if the character is still alive, if the client's IP address has changed. A respawn would also not trigger. The problem was that we only checked the IP address when determining whether the client should regain control, but respawnmanager (correctly) checked the Steam ID first and only used the IP address if the Steam ID isn't known.

The key here was that the server must be using Steam authentication (the issue won't occur if you're running the server without Steam, as I was when debugging this earlier). Otherwise rejoining will just trigger a respawn.

**Comment by Rokvach** [comment]
Tested using the repro steps in the comments and we didn't find any issues with the fix. Can be merged.
