### ISSUE TITLE
Can't preview Discharge Coil range in sub editor

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10853]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Can't preview Discharge Coil range in sub editor by holding space

### Version

0.20.16.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67eacbb8aa7002904576629c8377f8cff12b0887

**Comment by Rokvach** [comment]
Moving to Team1

I'm not seeing any type of preview when selecting a EDC
![image](https://user-images.githubusercontent.com/7299826/210556750-8e0f68db-cf57-4fc0-8c23-5979be58b278.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
