### ISSUE TITLE
Spreader Flak outperforms Focused Flak in all scenarios

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#10865]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://youtu.be/hmedC4fqXRE
As seen in this video analysis:
- Focused Flak is _not_ significantly better versus single targets than other ammo types
- Spreader Flak is more powerful against single targets than Focused Flak (Latcher and human examples)
- Focused Flak seems too expensive (2 lead) compared to other flak ammo, given its relatively low damage potential
- Spreader Flak seems too cheap

Possible solution:
- Copper instead of Lead for Focused Flak
- 2x Steel instead of 1 Steel for Spreader Flak
- Buffing Focused Flak or nerfing Spreader Flak

### Reproduction steps

Compare Focused Shells DPS with other ammo types, considering their price in materials

### Bug prevalence

n/a

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
I think it's more of an issue that Spreader Flak Ammo overperforms against large targets / in general. With the Latcher example, the time needed to kill it with Focused Flak Ammo is more in line with the Railgun (probably a bit slower), which is where it should be.

**Comment by Krzeszny** [comment]
> Spreader Flak Ammo overperforms against large targets / in general.

fair point

**Comment by ubertpendragon** [comment]
There are multiple factors at play, like how the barrel of the flak is long, so it can clip inside big enemies like Molochs, and you will hit every single shell, killing them in 2-3 shots

![image](https://user-images.githubusercontent.com/73229309/210608814-7897c5f9-7ac0-42f4-a40a-3b246da04a2f.png)


Latency could also be an issue with motion detection, causing shells to explode later than they should and get inside enemies before detonating?

**Comment by cshingle** [comment]
I feel that flak makes the Railgun entirely obsolete. Flak is much cheaper per shot and in many cases does more damage per shot.

**Comment by Krzeszny** [comment]
> I feel that flak makes the Railgun entirely obsolete. Flak is much cheaper per shot and in many cases does more damage per shot.

The only use the Railgun has is nuclear shells. Normal shells are useless compared to the Flak gun.

**Comment by JeroonBosch** [comment]
Adjusted in [a75b58750e48349368bbec7656a5b765aff62071](https://github.com/Regalis11/Barotrauma-development/commit/a75b58750e48349368bbec7656a5b765aff62071)

**Comment by Regalis11** [comment]
Tested all the ammo types, couldn't find any problems and the new damage values seem to be better balanced. Closing.
