### ISSUE TITLE
Pulse lasers blocked by invisble walls while laying on the sea bed

### ISSUE THREAD

**Issue by dprsd** [Regalis11/Barotrauma#10864]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hammerheads attacked. We sank to the floor. While laying on the floor sometimes lasers stop seemingly on nothing. No bodies were blocking it. Seems its an issue with terrain.

![image](https://user-images.githubusercontent.com/118803633/210436285-385da912-d238-46ba-8675-33ccc3eabaa8.png)
![image2](https://user-images.githubusercontent.com/118803633/210436886-4efe0e89-3e7d-4676-bcaa-716df16c7ecb.png)
![image3](https://user-images.githubusercontent.com/118803633/210437249-50bb31cb-6239-4a36-ac45-086e5ac81a19.png)

Off-Topic: Are Dementonite tools still obtainable?

### Reproduction steps

1. Start a MP campaign.
2. Go to some rock formations i guess.
3. Check if there are invisble walls.

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. Tested a couple of different levels, parking the sub on the bottom of the level, on abyss islands and on the sea floor. So I think this only occurs in some very specific situation or in specific levels. If anyone happens to run into this again, a save file or the level seed would most likely help us a lot in diagnosing this!

**Comment by Regalis11** [comment]
> Off-Topic: Are Dementonite tools still obtainable?

And as for this, there's currently no way to obtain them. We still haven't decided what to do with them: perhaps remove them altogether as they're no longer that important considering the number of other ways to speed up repairs, or change their effects in some way.

**Comment by Regalis11** [comment]
No known steps to repro, closing
