### ISSUE TITLE
Endlevel have terrain blocking progression

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#10863]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Untitled](https://user-images.githubusercontent.com/86010664/210433549-441b6006-8c1f-44a0-8c07-e92df9ec5e41.png)

![Untitled](https://user-images.githubusercontent.com/86010664/210435028-160d6191-98af-4754-817e-e4a1624309eb.png)

The passage towards the switch is blocked by terrain which halts the progression of the ending.

### Reproduction steps

So far no idea how to replicate. The only thing I know for certain is that I reloaded once and the issue persisted, so it likely has something to do with seed. Seed is LdaVIG8O.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/50bc36a4bab035c3d25a8b8c9cad065d5398b752

**Comment by JeroonBosch** [comment]
Couldn't spot any such blockers on the same seed now

**Comment by Regalis11** [comment]
The issue doesn't happen when you start a campaign with that seed, it's an issue with backwards compatibility. 

Steps to repro:
1. Start a campaign in the current stable version
2. Switch to unstable
3. Load the save and teleport to the end

**Comment by JeroonBosch** [comment]
Tested again, this time following the steps:
1. Start campaign on current stable version
2. Save & Quit, switch to unstable (without the fix applied) --> encountered the same terrain blocking the path
3. Save & Quit, switch to branch with fix applied --> Terrain is gone
