### ISSUE TITLE
Hitscan-Projectile are going through submarine

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#10862]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

![4BQT0~KMUIW0B~NRTMWX4N3](https://user-images.githubusercontent.com/73634685/210412748-8e827dee-d281-492e-88fc-732b7e480ae0.png)

### Reproduction steps
1. Start with any sub which you like
2. Spawn another sub near your main sub
3. Inside main sub and use HMG to shoot at another sub
4. HMG round are going through another sub

_No response_

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
