### ISSUE TITLE
[Unstable] Each hull upgrade level requires all three resources

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10861]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Each level requires 5 Steel, 5 T-A Alloy and 5 Physicorium: 
![image](https://user-images.githubusercontent.com/115734437/210404585-47967770-ed11-4b2c-b7c5-2d134fc0f376.png)
The resource costs seem like they are supposed to only take Steel for the tier 1 levels, T-A Alloy for the tier 2 levels and Physicorium for the tier 3 levels of hull upgrades.
```
    <ResourceCost item="steel" amount="5" levels="1-2"/>
    <ResourceCost item="titaniumaluminiumalloy" amount="5" levels="3-4"/>
    <ResourceCost item="physicorium" amount="5" levels="5-6"/>
```

### Bug prevalence

Happens every time I play

### Version

0.21.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/386154aef1791257726fd287eb7157224ab36ac7

**Comment by Rokvach** [comment]
This has been tested already as part of the PR and is working correctly, closing.
