### ISSUE TITLE
Random events can take the crew beyond 16, up to a maximum of 19.

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#10867]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When your crew is already 16, free crew given by random events, such as the medic at an abandoned outpost will let the crew beyond 16.
Players can get up to 19 crew, because there are up to three such random events.

That being said, I wish the crew cap had been raised and not limited to 16 - at least in single player. It's a lot of fun to drive a very large submarine, and that requires a larger crew.

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not a bug, the limit only applies to hiring new crew members from the hiring interface.

**Comment by AnalogKnight** [comment]
@Regalis11 
Thanks for clarifying this.
Do you have idea for the limit of crew I mentioned? I think the performance of recent versions of the game is good enough to support more crew. It might be fun to play with more crew.
