### ISSUE TITLE
"Mass Production" works on magazines and diving suits

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#10870]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you're loading magazines or crafting more advanced diving suits, the "Mass Production" talent still works on items that don't appear to be "materials".
For example, when I reload an HMG magazine, I may get a full magazine and an empty magazine. Combat diving suits may not be consumed when I make PUCS.
I'm not sure if this is a bug or expected behavior, but this seems really weird.

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3263a80751f34134341f1c4ac837d0cb56d3d90b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
