### ISSUE TITLE
[Crash] Object reference not set to an instance of an object. (System.NullReferenceException) Target site: Void DragCharacter(Barotrauma.Character, Single)

### ISSUE THREAD

**Issue by T-oasterO-ven** [Regalis11/Barotrauma#10876]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Game crashes in the middle of a level; doesn't matter what is happening as it seems to crash when nothing is happening and the 
sub is simply moving forward within the level.

### Reproduction steps

1.) Load the save with the enabled content packages in the same order (included in the full crash log)
2.) Play the level normally
3.) Refer to 'What happened?'

[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/10347382/crashreport.4.log)

Save file: [Barotraumatic_EW6.zip](https://github.com/Regalis11/Barotrauma/files/10347406/Barotraumatic_EW6.zip)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/04/2023 15:42:37)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B1E3E2D3D6E9C339D6CB342EC5799AD4

Game version 0.20.16.1 (ReleaseWindows, branch master, revision 5807900556)
Graphics mode: 1280x720 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla, EuropaWaifu++ Enhanced Armaments Patch, EuropaWaifu++ EK mods Patch, EuropaWaifu++ Improved Husks Patch, EuropaWaifu++, FrithsMissionTweak, BaroTraumatic, DynamicEuropa, Husk Mod Missions, AVP-Aliens, SCP-500 "The Panacea", Improved Husks, SOFA'S CREATURES, EK | Gunnery, EK | Armory, EK | Utility, EK | Dockyard, Meaningful Upgrades, Meaningful CPR, Abyssal Warsuit, T.I.T.A.N. power suit V2, ADV Beacon Stations, CsForBarotrauma, Lua For Barotrauma, Stations from beyond, BaroDrama V4.0, Better Vanilla Turret Ammo, APFSDS Railgun shells, Ammo extended 2 (RUS/ENG/汉语), BetterHealthUI, Enhanced Armaments, Detectable Alien Materials 可探测的异星矿物！, New Wrecks For Barotrauma (With sellable wrecks), Sellable Pirates, Movable and Sellable Wrecks, Vengeance Mk. III, EK Nurse Shark Mk-VI, EK Matriarch Mk-VII, B-71 sub-fortress (Mk2 update), Falcata-class Assault Sub (Goph Original Ship), EKM Myrith Mk-VI, EK Kira Mk-V, [VH] The Iroh, EK Skipper Mk-IV, EK Berith Mk-IV, EKM Stiletto Mk-V, Merkava mk-4, IKATERE, EK Gladius Mk-II, R-278 «Dugong», Arlcliff Raider, EK Marauder Mk-VII, Project 941 Akula, Room FX, Performance Fix, SFB with DE, PARAKI, Zubtrauma (Dialog Only), Unlock Parallel Talents (V.20), More Unique Weapons [EN/RU], The Atron, Ssparky's Gunnery, Alarms Extended, More Level Content - Hoist The Sails Update!, More Artifacts (AOCS), [UPDATED!] Frith's Biomes
Level seed: The BucketAstypalaea Linea
Loaded submarine: R-278 «Dugong» [ENG] (3C5750F3BF9D83E67D74915B8CA91E47)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: Intel(R) Iris(R) Plus Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DragCharacter(Barotrauma.Character, Single)
Stack trace: 
   at Barotrauma.HumanoidAnimController.DragCharacter(Character target, Single deltaTime)
   at Barotrauma.HumanoidAnimController.UpdateAnim(Single deltaTime)
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args)
```

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce the issue, even after installing the listed mods. Tested by grabbing other human characters: alive, dead and with the limbs cut off. If you have any ideas what could've been happening the moment the game crashed (some humanoid character was grabbing something?), that would most likely help us a lot in diagnosing this! Thanks and sorry for the inconvenience!

**Comment by T-oasterO-ven** [comment]
> Thank you for the report!
> 
> I unfortunately couldn't find a way to reproduce the issue, even after installing the listed mods. Tested by grabbing other human characters: alive, dead and with the limbs cut off. If you have any ideas what could've been happening the moment the game crashed (some humanoid character was grabbing something?), that would most likely help us a lot in diagnosing this! Thanks and sorry for the inconvenience!

After I validated the game files (which uninstalls the Client-side Lua) and then reinstalled client-side lua---
it still crashed; weirdly however, after trying the save one more time----I was able to get through the level without the crash.
The only difference from the previous attempt is that I switched characters a few times and had the debug console open a few times---wherein previously I stayed as the captain and didn't really bother with the console.

I played on encountering no crashing issues in the other levels, maybe when it does crash consistently it's level specific because
I was unable to identify any inklings of a consistent reason for the crash related to 'humanoids grabbing or interacting with things,' it could be another reason---I don't know.

One other observation that I thought was strange with the first level (on save load) is that after arriving at the Military Outpost and loading in---instead of spawning in the sub the whole crew spawns in the station, but strangely there are no NPCs other than my crew and the occasional event NPC (clown, etc)----no shop, no mission, no crew hiring npc---nothing. 
The debug console doesn't open with any red errors, just an empty Military Outpost. Even worse though, 
this seems to be the case with every military outpost, so there are times where you don't have access to any shops or missions for ages. Strangely, this isn't a problem for the other types of station (have not tested every type though).

If you wish for me to open a new Issue for this probably separate bug related to one of the mods instead of discussing it here, please let me know (unless you already know what mod could be causing the issue for hopefully a quick disable fix).

Either way, so far I have not crashed since the first test, but I kinda wish I knew for sure what was causing it in the first place---it really could still happen again considering how difficult this one is to pinpoint any consistent cause whether a mod or something else.

**Comment by Regalis11** [comment]
No known steps to repro, closing
