### ISSUE TITLE
Client and Server projectile spread is completely different?

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10878]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As you can witness on the video:
first shot hits on client, but server thinks it's a miss
second shot misses on client, but server thinks it's a hit?

This is on a self-hosted session

https://user-images.githubusercontent.com/73229309/210671475-453eec43-41cf-4d75-bf11-103829c75380.mp4

With godmode on (prevents HMG stun, but not clientside?)

https://user-images.githubusercontent.com/73229309/210672216-c0b8c92d-5a69-4b00-a386-1d89e517cf62.mp4

This is part of the "rubberbanding" problem, players see a hit, but on the server it's probably a miss

Other examples:

https://user-images.githubusercontent.com/73229309/210671666-4080b14b-7816-4c4a-95db-cf51690b4eec.mp4

Health rolling back

https://user-images.githubusercontent.com/73229309/210671711-05d17ad1-7a61-4c36-986d-206456674d76.mp4

### Version

0.20.16.1

**Comment by ubertpendragon** [comment]
https://github.com/Regalis11/Barotrauma/issues/9825

https://github.com/Regalis11/Barotrauma/issues/10278

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3845/commits/5aee2776034ebdb1a1e86351bd67827c997c86cf

**Comment by 3e849f2e5c** [comment]
Tested various weapons with different weapon skill levels and ranges and could not spot any cases where the server and the client would disagree on whether or not a bullet hit or not
