### ISSUE TITLE
Scrap Savant actually have 80% chance to find an additional scrap, not 20%.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#10887]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

unlock Scrap Savant, it says will have 20% to find scrap. In xml code we can see 
(1) Replace tag="[probability]" value="20" color="gui.green"
and
(2) CharacterAbilitySpawnItemsToContainer randomchance="0.8" oncepercontainer="true"
the source code shows:
(3)if (randomChance < Rand.Range(0f, 1f, Rand.RandSync.Unsynced)) { return;}
so if randomchance="0.8" then it will have 80% chance trigger Scrap Savant, not 20%

### Reproduction steps

1. unlock Scrap Savant.
2. find a wreck and trigger Scrap Savant.
3. Counting the number of triggers
4. if it is not obviously, then change randomchance's value to 0.99 in (2)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Fixed in ae5fa67d02a06d6d272273100aaf26b43dd0643a

**Comment by Regalis11** [comment]
Tested, working correctly. Closing.
