### ISSUE TITLE
Memory component can send empty signals. These signals are treated as true because they are not 0.

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#10880]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Signal inputs do not check whether the strings they receive are zero length strings, and this causes no problems only because no component can be set up to send an empty signal.
Except the memory component whose value can indeed be set to empty.

This leads to weird behavior: logic gates send their value upon receiving the empty signal, lights turn on, turrets fire, etc.
I don't think this is intended.

Not a bug until someone sets up a memory component incorrectly.
Workaround: don't set empty value to memory components.

### Reproduction steps

1. Take a memory component
2. Set its value to nothing
3. Connect it to a turret

Turret will fire

Connecting it to a text terminal nothing will show up

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by cshingle** [comment]
My experience is that an empty strings are treated as null which is ignored and the previous state is maintained. I am typically using And, Or and Signal components. I'll have to give it a try to see if putting a memory component inline changes the behavior.

**Comment by mygamingaccount** [comment]
AND, OR, and all the other components, when they do not have a value set for their true or false outputs _do not send signals_. You do not expect the undefined signal from an OR component to trigger a turret, right? The undefined Memory component will send an empty string signal which _will_ fire the gun.

**Comment by mygamingaccount** [comment]
I have figured out a way for this behavior to be useful: by sending the empty signal through a wifi component or a relay, you can overwrite the values stored by true outputs of components via the `set_output` pins.

So this may be unintended, I don't know, but it has a use when dealing with three-state logic circuits. Therefore I'm closing the issue.
