### ISSUE TITLE
body armour for security/clown costumes uses legacy damage modifiers

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1088]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Security body armour and clown jumpsuits use legacy damage modifiers (Slash / blunt ? not defining afflictions etc). I don't think these will work correctly in game as a result.

**Version**
Barotrauma closed alpha 0.8.9.3

**Additional information**
Honestly, what is even the point of clown jumpsuits having damage modifiers of 1.0 ? this seems more redundant now than out of date.

Example:
```xml
<damagemodifier damagetype="Burn" armorsector="0.0,360.0" damagemultiplier="0.9" />
<damagemodifier damagetype="Blunt" armorsector="0.0,360.0" damagemultiplier="0.3" bleedingmultiplier="0.3" damagesound="LimbArmor" deflectprojectiles="true" />
<damagemodifier damagetype="Slash" armorsector="0.0,360.0" damagemultiplier="0.1" bleedingmultiplier="0.0" damagesound="LimbArmor" deflectprojectiles="true" />
```

vs

```xml
<damagemodifier armorsector="0.0,360.0" afflictiontypes="damage" damagemultiplier="0.8" damagesound="LimbArmor" deflectprojectiles="true" />
<damagemodifier armorsector="0.0,360.0" afflictiontypes="bleeding" damagemultiplier="0.3" damagesound="LimbArmor" deflectprojectiles="true" />
<damagemodifier armorsector="0.0,360.0" afflictiontypes="burn" damagemultiplier="0.6" damagesound="LimbArmor" deflectprojectiles="true" />
```

**Comment by Regalis11** [comment]
The point of the damage modifiers in the clown costume is simply to change the sound type (= play a honk sound when hitting a clown).
