### ISSUE TITLE
Lone Wolf resistances don't work

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10893]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Lone Wolf's melee damage increase works but the damage and stun resistances don't seem to work.
Tried shooting the captain at a distance, enemy human and crawler attacks. All of them seem to do the same damage to the captain regardless of him having the affliction active.
Might be caused by the lonewolf affliction having separate effects with the same strength range so only one of them ends up working:
```
<Effect minstrength="0" maxstrength="1">
      <StatValue stattype="MeleeAttackMultiplier" value="0.2" />
    </Effect>
    <Effect minstrength="0" maxstrength="1"
            resistancefor="damage"
            minresistance="0.2"
            maxresistance="0.2" >
    </Effect>
    <Effect minstrength="0" maxstrength="1"
            resistancefor="stun"
            minresistance="0.2"
            maxresistance="0.2" >
    </Effect>
```

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c8871a4c1dc0e73d97ea8700478da757bdd419b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
