### ISSUE TITLE
Minor Body Armor sprite issue

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10897]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Body Armor sprite sourcerect doesn't seem to fit the whole sprite
`texture="Content/Items/Jobgear/Mechanic/safetyharness.png" sourcerect="14,45,103,180"`
In game, scaled up:
![image](https://user-images.githubusercontent.com/115734437/211305176-68b78aab-dda5-4d3e-af33-ceefa05bd6c1.png)
How it appears in an image editor:
![image](https://user-images.githubusercontent.com/115734437/211305144-ce947518-c108-4c64-b108-9c6720e3bdf2.png)

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment]
Apologies if I should have posted this as a separate issue instead of here but I noticed the SMG Magazine sprite is also slightly cut off:
`sourcerect="146,157,17,44"`
![image](https://user-images.githubusercontent.com/115734437/211822863-2a8a0ced-c5b0-4be8-b385-6605b4c77ad3.png)
![image](https://user-images.githubusercontent.com/115734437/211823239-2e4448f0-68b2-4414-a4c0-8ce53ff5b3a2.png)

**Comment by Regalis11** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/commit/bab5e256e4439f554378d17b685e3734acbb9e3b, does not seem to be fully addressed. Part of the worn sprite is still clipped off, and the magazine sprite hasn't been touched.

![image](https://user-images.githubusercontent.com/14351070/215990027-2f0ce45d-bcf8-4896-b59d-716122adcf52.png)

**Comment by Regalis11** [comment]
Tested the latest fixes, no issues found. Closing.
