### ISSUE TITLE
Genes cannot be sold when not at 100%

### ISSUE THREAD

**Issue by JeroonBosch** [Regalis11/Barotrauma#10899]
Identified genes are rarely at 100%, but items that are below 100% condition seemingly cannot be sold, making that part of the Blackmarket Genes disfunctional

**Comment by JeroonBosch** [comment]
We could go with either:
1. Adding XML property that allows selling regardless of condition % (at full price)
2. Same as above, but price scales with condition

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ab58a95d928c1b3c6be4bfedb1054f03ca116e9. Can't spot any issues in the changes, moving to QA

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
