### ISSUE TITLE
Items placed on the floor spawn if shuttle is spawned as main ship, but items don't spawn when the shuttle spawns as a respawn shuttle

### ISSUE THREAD

**Issue by GGSnipa** [Regalis11/Barotrauma#109]
I first noticed it when the depth charge shells didn't spawn on my newly made respawn shuttle. I'm using Chiko's Barotrauma Extended mod if that changes anything.

**Comment by Regalis11** [comment]
Duplicate of #234. I'll close this one and keep the newer issue because it describes the problem more accurately.
