### ISSUE TITLE
LightComponent sprites overlay incorrectly on base sprite

### ISSUE THREAD

**Issue by dakkhuza** [Regalis11/Barotrauma#10900]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sprites inside of a light component overlay seemingly multiplicity, which causes issues when the base sprite has black as part of it's texture. The parts of the sprite that overlap with the black part of the base sprite will become invisible.

For example, take the super capacitor. If you look at the raw sprites, you would assume the sprite would look like this when it's glowing.

![example](https://user-images.githubusercontent.com/48874322/211459096-f9c83456-8821-415f-9a48-97b9eb865a66.png)

However if you look at the glowing super capacitor in game, you'll see this

![example2](https://user-images.githubusercontent.com/48874322/211459304-4e968015-aa86-4409-b4ba-f3098a2c751f.png)

No glow, which is a shame because they'd look even cooler if they glowed like the sprites imply.

This also affects junction boxes, it looks like this was introduced sometime after October 2019, as junction boxes glow correctly in footage I've found from around that time.

![example3](https://user-images.githubusercontent.com/48874322/211459943-911156b0-6c81-42e7-b56b-b11c9c93d225.png)

### Reproduction steps

- Load up any submarine
- Look at active junction boxes / maxed out charging super capacitors
- Observe lame, non-glowing versions

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3852/commits/29370955a8066ee6e4fb052ba790b2fb0b99de16

**Comment by Rokvach** [comment]
Tested I didn't spot any issues with this. Can be merged and closed.
