### ISSUE TITLE
Steady Tune (harmonica talent) description is wrong

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10904]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**Steady tune** states it gives 50% psychosis resistance for 60 seconds

![image](https://user-images.githubusercontent.com/73229309/211624211-eacbcdb9-4edc-49f9-a618-5c01a6925588.png)

In fact, it gives 60 psychosis resistance every 1s after 10 seconds of playing.

Psychosis resistance has a max strength of 600, -1 per second
The effect gives 0 to 75% psychosis resistance depending on strength
So the effect can give you between 0 to 75% psychosis resistance for 10 minutes

----
Even if this is a lot better than what it looks like on paper, I still think this is *the* worst talent in the game, because psychosis resistance simply isn't useful

Either make psychosis resistance 75% or full immunity at all values, give it resistance to hallucinating/watcher's gaze, have the talent actively remove psychosis, and reduce the duration of the buff

### Version

0.20.16.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9092aee7050e45bc9318764e8a19af24ac9ecaab

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
