### ISSUE TITLE
Liquid Oxygenite is too fragile

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#10903]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Liquid Oxygenite will explode even if you put it on the ground while the character is crouching. This makes it impossible to share it with other players when there are no containers nearby.

When you buy Liquid Oxygenite at an outpost, sometimes they will **explode right after being delivered to the sub**, because the container containing them spawns some distance above the ground.
If the output slots of the Deconstructor are full, the product of deconstructing the Oxygenite Tank or Deusizine will explode immediately, and the explosion will prevent you from even going to stop the Deconstructor until it wastes all the materials.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a0a0605ea15d8189114738661879ad77768be37f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
