### ISSUE TITLE
Unstoppable Curiosity and Ph.D in Nuclear Physics descriptions are incorrect

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10909]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unstoppable Curiosity and Ph.D in Nuclear Physics both increase crowbar damage by a percentage amount. The descriptions cite a 200% increase and a 300% increase respectively. However the increase is only 100% and 200% - an increase of 200% would imply that the total damage is triple the original, and an increase of 300% is quadruple.

![image](https://user-images.githubusercontent.com/37850646/211834531-a1aca4d1-61a4-4faa-95c4-57a1f55e1453.png)
![image](https://user-images.githubusercontent.com/37850646/211834655-a1a7720d-77c8-477e-992b-67dcaf2be106.png)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b996c54e7e572cc436df6a74ebffbc98cdd6ec41

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
