### ISSUE TITLE
Multifunctional doesn't work on crowbars

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10908]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Multifunctional is supposed to give +50% damage to crowbars, however due to an incorrect tag in the talent xml, it gives no bonus damage.

Crowbar has the `crowbaritem` tag, but the talent uses `crowbar`

![image](https://user-images.githubusercontent.com/37850646/211809681-ec8bf6e2-f814-42bd-9fda-73e0e81fae1a.png)![image](https://user-images.githubusercontent.com/37850646/211809727-835b767b-bfd0-445b-a217-c3e07d68f2f1.png)

### Reproduction steps

1. Hit a character with a crowbar - it does 5 damage (base 10, halved by human resistance) (view affliction strength with health scanner HUD)
2. Get the multifunctional talent via console
3. Hit a character again
4. Observe that it is still doing 5 damage, instead of the expected 7

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b39ee283b36d06d67d6fd00e8aafa79967757e61

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
