### ISSUE TITLE
Killing myself with fentanyl on a multiplayer server leads to terminal message

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1090]
Join an empty server, found some fentanyl, injected myself with it for kicks, terminal kicks out the message in the image attached when i go unconscious.

![barotrauma_2019-02-06_09-16-42](https://user-images.githubusercontent.com/10775991/52405910-22196100-2ad5-11e9-8d4d-1d816af2d62b.png)

**Comment by NilanthAnimosus** [comment]
This might be related to my comment for commit 5d3ab5084b8bc5357bc4a53993ad8dfcc44d0412 that fixed the exception before.
