### ISSUE TITLE
Job limits bypassed on server with respawn

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1091]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have seen a case where multiple captains have spawned, which bypasses normal job limitations.

**Steps To Reproduce**
I believe this may be caused by rejoining a server due to getting disconnected, the players were on the server however during the shuttle deployment however, but I think I recall the first getting disconnected and rejoining that session

**Version**
Windows 7 64bit, closed alpha 0.8.9.2, Hosted on client server.

**Additional information**
The player respawning was a client, and the player who was already a captain since round start was also a client. Neither had died or gone unconscious.

![image](https://user-images.githubusercontent.com/29177976/52405999-913a8980-2ac4-11e9-83fe-1d2bbf5d6abc.png)

![image](https://user-images.githubusercontent.com/29177976/52406006-95ff3d80-2ac4-11e9-8814-6f5f27240283.png)

It appears it may be going off connected clients somehow and their info's instead of living characters who are actively controlled by a connected player. - Essentially, I believe this may be rejoining characters not updating their info's (?). I'm just hazarding a guess at the moment from what I remember of the respawning code.

As a final note, no debug console commands were used.

**Comment by Rokvach** [comment]
This should be fixed with the new job assigning logic, closing.
