### ISSUE TITLE
Monsters not attacking the player

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#10912]
Monsters won't target humans since Regalis11/Barotrauma-development@488da45, because they all try to target "hostiles". Fortunately most monsters also target the diving suit and retaliate when attacked, but the monster AI still badly broken now.

Version:
v0.20.16.1 (latest bugfixes, not in release)

Steps to repro:
- Spawn a leucocyte next to a player character outside of the sub OR spawn a crawler next to the player character in the sub.
- Observe how the monster doesn't react to the player (+ debugai).

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c0fbcfb.

**Comment by Regalis11** [comment]
Tested, couldn't spot any issues. Closing.
