### ISSUE TITLE
Liquid oxygenite not fragile enough (when shot)

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10910]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bit of an oversight, i hope, from the changes made just recently seems it was changed to not explode when shot at someone with a syringe gun, which kinda ruins its fun use as an improvized weapon /: 
Id assume this is an oversight, considering its also acted wierdly with being dropped.

### Reproduction steps

1.Load liquid oxygenite into a syringe gun
2.Shoot it at a human/monster
3.Watch it act as if it were normally injected, instead of exploding, as it did previously

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a39b97c9837d1ebfb6ef14689f1bacf11903769

> Fixed liquid oxygenite not exploding when fired from a syringe gun. Happened because the effects in the MeleeWeapon component set the condition to 0, and the OnImpact effect wasn't allowed to execute if the condition is 0.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
