### ISSUE TITLE
Bots try to contain multiple ammoboxes when reloading turrets

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#10916]
Caused by Regalis11/Barotrauma-development@b7684ad, which was a fix to #10039.  Fixed in Regalis11/Barotrauma-development@5e8f688.

On testing: Can't be reliably reproduced before Regalis11/Barotrauma-development@7c47cd4, which breaks bots loading ammoboxes. Test on the latest bugfixes.

Steps:
- ensure that you have at least two ammoboxes for a turret
- ensure that the turret doesn't have any ammunition
- order a bot to operate a turret
- observe how the bot attempts to load all the boxes in the turret (throwing them next to the controller) before operating the gun

**Comment by TheMinerBoy** [comment]
This also occurs with the reactor as well as welding torches.

**Comment by Regalis11** [comment]
No issues found, closing
