### ISSUE TITLE
EMP doesn't affect lights

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10913]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Lights have the "Vulnerable to EMP" option, but it does nothing.
Almost every lightcomponent xml has vulnerabletoemp="false"
![image](https://user-images.githubusercontent.com/73229309/211900388-8030534b-e467-41d9-8232-5d616789389b.png)

Only items that have a "repairable" property can be damaged by EMPs _(I assume so they're not permanently damaged)_

![image](https://user-images.githubusercontent.com/73229309/211900516-e2bf6047-e443-45f0-8f1f-7a410e8a7fc6.png)

It's possible to make lamps take damage from EMPs and self repair + adding a flickering effect by increasing minvoltage when damaged, unfortunately the repair icon/UI shows up, as part of Repairable

```xml
    <LightComponent lightcolor="1.0,1.0,1.0,0.5" range="800.0" powerconsumption="5" minvoltage="0.5" vulnerabletoemp="true" >
      <LightTexture texture="Content/Lights/pointlight_bounce.png" origin="0.5,0.5" />
      <sprite texture="Content/Items/Electricity/signalcomp.png" sourcerect="784,528,64,96" alpha="1.0" />
	  <!-- self-repair all the time -->
	  <StatusEffect type="Always" target="this" Condition="25" />
	  <!-- flicker when damage by increasing minvoltage -->
 		<StatusEffect type="Always" target="this" minvoltage="10" setvalue="true" >
			<Conditional Condition="lt 99" />
		</StatusEffect>
		<StatusEffect type="Always" target="this" minvoltage="0.5" setvalue="true" >
			<Conditional Condition="gte 99" />
		</StatusEffect>
    </LightComponent>
```

https://user-images.githubusercontent.com/73229309/211900447-5e55831e-1cf2-48fb-b4a7-fc5a8f6b92e6.mp4

It'd be much simpler if this behavior of temporarily increasing minvoltage for a short while after being hit by EMP was default for all lights and didn't have to use statuseffects
Is it a bug? Is it a feature request? I just think it'd give EMPs good visual feedback

### Version

0.20.16.1

**Comment by Regalis11** [comment]
This is intentional: items that are impossible to repair generally don't receive damage from anything. Although, I do agree some kind of a temporary effect (like increasing minvoltage) would be a nice little addition!

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/4daf3d5b3220b598adde534f883c56bbddef4d3b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
