### ISSUE TITLE
Some beacon stations won't fill with water, and Bone Threshers will still spawn inside.

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#10924]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![20230108155246_1](https://user-images.githubusercontent.com/61218809/212361945-2a6efa27-b5d9-4137-a065-f73b1e0af16b.jpg)
Bone Threshers require water, so they can suffocate before the player enters the beacon station.
(My mod only replaces the appearance of some items, this should not cause problems. So I didn't check the second option.)

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro, closing
