### ISSUE TITLE
Assistant's "Journey Man" gives 10 less skill bonus than description

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10923]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

this was mentioned in #10708, but not fixed yet

### Reproduction steps

1. play as assistant
2. get an apprenticeship job
3. get "Journey Man"
4. issue occurs

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Tested, no issues found. Closing.
