### ISSUE TITLE
A projectile bug from Rapid fissile accelerator

### ISSUE THREAD

**Issue by YIMINNNNN** [Regalis11/Barotrauma#10921]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the character shoots with a Rapid fissile accelerator in the water,the character will be hit strangely.

https://user-images.githubusercontent.com/111684755/212205568-8db2f9a8-fdbb-436e-8ab8-9af43e5ebcb2.mp4

There seems to be a bug on line 468 of  _engineer_talent_items.xml_ ,I changed them to _type="OnImpact" target="UseTarget"_ and then it went back to normal.

### Reproduction steps

1.Use Rapid fissile accelerator in the water

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/148e3f35509524ac5c86c96ec1ad4b961a46bfde

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
