### ISSUE TITLE
[Factions] Ready checks do not work at all

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10929]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever a user starts a ready check, it will not show up for anyone else, aside from incredibly rare occasions (I am unsure what prompts them to show). In the rare event that the player sees a ready check started by someone else, voting in said ready check will only show the player's vote. The player who started the ready check's green tick is absent and it will state that only 1 player voted in the check (despite the fact that two people had to have voted since this is a player voting on another player's ready check).

Imaging for this issue is difficult but here is a collection of whatever we managed to collect.

![image](https://user-images.githubusercontent.com/105495756/212444681-6df0a352-698c-45d6-8329-9d00679b08df.png)
_Figure 1. Screenshot of chat showing only 1/15 players voted in the ready check despite two players being shown to have voted in the ready check._

![image](https://user-images.githubusercontent.com/105495756/212444821-4433ea73-3964-475d-b0d0-ceea12ea8390.png)
_Figure 2. Player's vote being shown despite player never having received the ready check prompt. No other votes are registered._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Was unable to repro in feature/fullrelease-testing branch, possibly need to join the campaign testing with a debugger on to figure out what's happening

**Comment by Wheatley1002** [comment]
This bug seemed to have stopped appearing in E2, so perhaps it was purely a networking issue? But I'm not sure what could've caused it or fixed it since both sessions were in the same build from the same campaign

**Comment by Regalis11** [comment]
No known steps to repro, closing
