### ISSUE TITLE
Herja airlock doors can be opened at the same time

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10928]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Both doors of the Herja airlock can be opened at the same time if you press the outer buttons while leaving one of the doors opened, causing flooding.

![image](https://user-images.githubusercontent.com/73229309/212444146-7318095e-4321-4d77-a880-b40ab6482a63.png)

Elegant Solution: 
AND with 0 output wired to both doors State_Out into both doors Set_State. Requires two presses if one door is opened, prevents water from flowing in
Allows for a **Door With Buttons** which is more user and bot friendly
![image](https://user-images.githubusercontent.com/73229309/212444608-ebe7df14-279d-4d60-ba2b-6149773ed6df.png)

Simpler Solution:
Wire the outer buttons to the signal checks (in white) so the doors properly close

![image](https://user-images.githubusercontent.com/73229309/212443933-428e060a-1641-4d99-8e36-d3af529cfdf6.png)

### Version

0.20.16.1

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/869990f2098929391f9abc8a9d3414f72131ad79

Tested, could not find any issues. Closing.
