### ISSUE TITLE
Biohazard and Handle With Care missions give two separate prompts

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1092]
On multiplayer servers you are given two separate prompts as to where you're delivering whatever you're delivering in Biohazard and Handle With Care missions.

https://gfycat.com/InsecureTatteredEland
https://gfycat.com/EminentLoneCusimanse

**Comment by NilanthAnimosus** [comment]
sounds like it could be caused due to #1056 depending on the age of this report since that caused two different locations and two different starts of the same mission type and level.

**Comment by Regalis11** [comment]
Yep, I believe this was fixed in eaa4818
