### ISSUE TITLE
Flashlights affecting performance significantly

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10939]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Now that flashlights can be attached to guns, they're being used much more often

As a result you have 1000 range, wide shadow-casting beams sweeping across multiple surfaces fast, significantly increasing the Lighting draws

![image](https://user-images.githubusercontent.com/73229309/212500548-588a4824-70f3-467b-a9d3-4a80fd8a2cad.png)

Reducing the range of flashlights (view range stops at around 650 for 1920x1080 resolution) and width of the cone would alleviate the high draw number

Range comparison
![image](https://user-images.githubusercontent.com/73229309/212556147-9d66ee9f-ffc3-40d7-aa14-19fe49a6de31.png)

![image](https://user-images.githubusercontent.com/73229309/212556122-e282f6fa-fa30-4ab9-9fbf-0fbc133850e4.png)

Other observations:

-Scooters have the same problem (range+shadow casting)
-Light draws even with LOS being opaque, for example, while manning a railgun, I have high light draw while diving team is messing around in a wreck within the range of the screen but out of my LOS. I couldnt get a picture but here's how it looked liked:

![image](https://user-images.githubusercontent.com/73229309/212557266-b4bdb883-8684-435b-8c54-5c6ac6ed506e.png)
As soon as the wreck was in the screen, the lights increased massively

### Version

0.20.16.1

**Comment by Rokvach** [comment]
Tested, I compared this branch with the traitor-update branch and saw that the performance of large quantity of flashlights is worse in this branch than what it is in the branch without the optimizations

flashlight-optimizations
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/d495069c-f075-4e66-b4ff-77b84c4b84ff)

traitor-update
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/919decbb-8d1d-4dd9-b6fb-301db79ec294)

Testing steps:
1. Load Dugong in sub editor
2. Place down flashlights under the navigation terminal until the item count hits 600
3. Load into test mode with fpscounter enabled

In flashlight-optimizations the closer you get to the stack of flashlights the worse your FPS gets while in traitor-update this isn't the case, in traitor-update only way I was able to drop my FPS was when I opened the door on the right leading to the diving suit lockers the FPS was noticeable lower while the door stayed open. 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/36bbf709-0d65-4dc0-acfb-0ffb6d873705)

**Comment by Regalis11** [comment]
I wasn't able to reproduce those results. With that test setup, the performance seems to be practically identical between the branches (around ~270 FPS, no noticeable differences in the profiler). Which is to be expected, because the optimizations only affect moving flashlights (not rendering or updating them if you're behind the light cone).

**Comment by Jasontti** [comment]
Tested.
Had 34 bots walking around with flashlights on their heads.
There was improvement in outposts, Draw avg. improved by 1-2ms and max by same amount in optimized build, but performance was never really bad (multithreaded lighting helps here).
At map loading on start unoptimized fps dropped to ~20, compared to ~35 in optimized.
No issues found.
