### ISSUE TITLE
Submarine editor doesn't show descriptions for item assemblies

### ISSUE THREAD

**Issue by Prolbo** [Regalis11/Barotrauma#10935]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Submarine editor allows you to enter description when you are saving item assebly. It doesnt show this description when you are picking said assebmbly from pallete.
![111](https://user-images.githubusercontent.com/54717422/212467553-9f3c449c-99a7-4bbf-8171-f93caef09b7b.png)
![112](https://user-images.githubusercontent.com/54717422/212467711-c727f82e-1a10-4283-8d65-373324689a99.png)

### Reproduction steps

1. Go to submarine editor
2. Place few items
3. Select them and push "save as item assembly"
4. Enter name and description and save it
5. Open tab with Item Assemblies in pallete
6. Hoover over your item, try to read the description. There is none.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7804306ab2312f0c4a73ffdfe290283f481c5fd8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
