### ISSUE TITLE
[Factions] Clown District layering issues

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10931]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/105495756/212445494-cd25c2f0-3422-43c6-82e9-61921d2b802f.png)
_Figure 1. Misc trash being on top of the inner wall._

![image](https://user-images.githubusercontent.com/105495756/212445529-919757fc-c51b-414e-a580-7bfb83b8321f.png)
_Figure 2. Red curtain being above the wall above the door, but below the wall cap. Cable holder is also above this wall (harder to see due to lighting)._

![image](https://user-images.githubusercontent.com/105495756/212445581-0b927986-eab6-4f06-8444-752a029d43f5.png)
_Figure 3. Red rope is too far forward as players climbing the ladder can clip underneath it, presenting the visual effect of it floating._

![image](https://user-images.githubusercontent.com/105495756/212445626-c7dd3237-0563-4caa-8d13-9178e1289d4e.png)
_Figure 4. Repeat instance of Figure 3._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
There's still something strange going on with the curtain. 
![image](https://user-images.githubusercontent.com/14351070/214889364-5eb37fa7-77ad-4334-9db1-0fbe6f078fa4.png)

The right curtain is in front of the door, but behind characters, but the left curtain is in front of the characters. The characters' feet are also visible from behind the curtain (intentional?)

**Comment by IiroEnges** [comment]
fixed

**Comment by Regalis11** [comment]
Looks good to me, closing

**Comment by Wheatley1001** [comment]
Found some more layering issues for the clown outpost module. This came from 1.1.3.0.

![image](https://user-images.githubusercontent.com/105495756/232174052-31b962e8-fa15-4e97-a94d-92b0c3f9bf08.png)
_Figure 1. Clown items floating above the platform._

![image](https://user-images.githubusercontent.com/105495756/232174062-fb217708-881b-49bd-9b49-93936d611d1f.png)
_Figure 2. The overall module this issue occurred in._
