### ISSUE TITLE
Storage item menus overlap admin menus

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10932]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In-game storage item menus take priority over admin menus, such as the permissions screen for players. This is problematic as someone in an admin menu isn't going to be concerned about storage items they're holding.

(menu moved directly over admin menu to show issue clearly. Please note that this did not cause the issue as it was already overlapped before I interacted with it)

![image](https://user-images.githubusercontent.com/105495756/212446090-128f620d-fc99-45e9-8f3d-23443d9ea58a.png)

### Reproduction steps

1. Hold a steel crate
2. Press tab to open player list
3. Right click a player and click "manage"
4. Observe how the steel crate's menu overlaps the admin menu

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does not seem specific to the faction branch

**Comment by Rokvach** [comment]
I noticed that dragged items are rendered below inventories now
![image](https://user-images.githubusercontent.com/7299826/212879218-f0bde9bd-a9f4-4e11-8cda-4d78192cb171.png)

**Comment by Rokvach** [comment]
Tooltips are also rendered below
![image](https://user-images.githubusercontent.com/7299826/212879657-51bf687b-d2ff-4cf2-9d83-3920143a00ce.png)

**Comment by Regalis11** [comment]
Reverted the commit for now

**Comment by Regalis11** [comment]
2nd attempt: https://github.com/Regalis11/Barotrauma-development/commit/22beb88c8dfd9d78a2ce76dd1b3899747934fd85

**Comment by Rokvach** [comment]
Only thing I noticed is that you can interact with the Crate inventory through any other inventory

Note these issues only happens if you have moved the crate UI or cabinet UI so they overlap which I think will be quite rare.  

Can't access the item on cabinet as the crate inventory move handle is behind it
![image](https://user-images.githubusercontent.com/7299826/215064150-71d85ccd-21e2-4a01-a128-615e22a31727.png)


Trying to store a item places it to the crate inventory
![image](https://user-images.githubusercontent.com/7299826/215064300-634796bb-bd07-474f-914c-026db8bf483b.png)

**Comment by Regalis11** [comment]
[Reverted again](https://github.com/Regalis11/Barotrauma-development/commit/4a3d3c521d7d1030400841e1e2b4f9f5b9ac6446). This is turning out to be a way bigger can of worms than I thought due to the way the inventories have been implemented (not part of the normal GUI system).

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. This is unfortunately quite tricky to address as mentioned above, and the issue is very minor and easy to work around.
