### ISSUE TITLE
Event "Stuck in the middle" has a line from "A man and his raptor"

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10941]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the "Stuck in the middle" event, during the second conversation with the handcuffed separatist, this line from "A man and his raptor" is shown instead of the intended line: (The person is semi-delirious, but they manage to mutter a question: “You ever- ever had V-versas liver?”)
![image](https://user-images.githubusercontent.com/115734437/212533032-6a8d7e33-264e-47f3-8e22-3277e553c6ac.png)

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b59456a470429e0aa50f623ccd4da6eacef95a71

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
