### ISSUE TITLE
Power flowback still exists on EDCs

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10942]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/issues/9899

If you activate any of the two EDCs on the left or right, it will drain power from all supercapacitors (connected through the middle coilgun). Here I pressed the left button, it drew from all supercaps (but more from the one directly connected)
![image](https://user-images.githubusercontent.com/73229309/212555621-39f21dc6-1401-4342-b19e-8c6c271ade31.png)

Coilgun flowback has been fixed as this setup doesnt have the same issue
![image](https://user-images.githubusercontent.com/73229309/212555695-2b5a54ef-9de8-42e0-8b5a-7be8f9c7b2ba.png)

### Version

(reported on live version)
0.20.16.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05a586d3e5d0dcf69a20bfc526c8f860dc9b6e8c

**Comment by Jasontti** [comment]
Tested.
Power flows trough connected turrets.

Setup on the left takes power from both capacitors and setup on the right doesn't work (as expected).
![Screenshot_8](https://github.com/Regalis11/Barotrauma/assets/8488224/fec00c93-d447-4615-82af-bcf33fae7696)

**Comment by Jasontti** [comment]
Tested in above mentioned configurations, also turret-edc-turret setup and no issues found.
Closing ticket.
