### ISSUE TITLE
Pirate subs spawn with regular diving suits when level starting depth is >4000m

### ISSUE THREAD

**Issue by dakkhuza** [Regalis11/Barotrauma#10949]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In pirate missions in the later half of the campaign, pirate subs will be able to withstand at least the same depth as the player submarine as you can see [here](https://github.com/Regalis11/Barotrauma/blob/b7201c497d533a676d0bc1e62e5d5fb16ecf5659/Barotrauma/BarotraumaShared/SharedSource/Events/Missions/PirateMission.cs#L204) however the diving suits that spawn inside the pirate submarine will always be green suits. 

This causes issues when the starting depth is >4000m as poking a single hole into the enemy submarine guarantees the whole pirate crew will die to pressure as the bots will enter the room with the leak to fix it before running away from the pressure due to their suit being insufficient, flooding the whole sub. This arguably makes it easier to fight harder pirates as all you need to do is cause one hull breach and the pirate crew will be unable to repair it.

![example1](https://user-images.githubusercontent.com/48874322/212753759-056a16c6-429e-44aa-9e00-db1561bdb214.png)
![example2](https://user-images.githubusercontent.com/48874322/212753765-a703698f-8225-4a63-aa0a-c65c785214f5.png)

### Reproduction steps

1. Start multiplayer campaign
2. Teleport to either the great sea or hydrothermal wastes 
3. `unlockmission pirate1` in console
4. Load into the pirate mission level and observe the green diving suits when starting depth is >4000m
5. (Optionally) use `explosion` to punch a hole in the sub, watch the bots get diving suits, run into the room and then run out without fixing the leak due to the pressure, flooding the whole sub

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by dakkhuza** [comment]
I believe a similar issue might have been reported over diving suits on wrecks being green suits in deep areas but I was unable to find it on the issue tracker (might have been moved to discussions?)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/3990. Tested & merged
