### ISSUE TITLE
Host ingame option "Public server" always defaults to true after restarting game

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#10959]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When starting a new instance of the game, it forgets you unchecked "Public server" when hosting, regardless of what the server last used.

### Reproduction steps

1. Click host server from main menu on client
2. uncheck public
3. host
4. Close server and check host menu - public is still unchecked
5. restart the client
6. Click host server and find public option is checked again - while other settings (such as name and password) are saved.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/515f0a0b51e1e36ebb90b4d61d983f69464a2b91

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
