### ISSUE TITLE
Lighting Wizard ragdolls enemies really fast out of water (physics issue?)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10954]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When an enemy attacks and immediately gets stunned as a result of that attack, they can get ragdolled extremely fast and phase through walls. Lightning wizard is currently the only practical case I can think of.

Stun probably causes the enemy to ragdoll at the exact same time as the attack animation torque/impulse is applied, sending it flying.

-Mass/Size seems to affect how fast an enemy gets ragdolled
-Humanoids don't seem to be affected as much, mostly crawlers/mudraptors

Baby crawler getting stunned and ragdolled through the ceiling at lighting speed

https://user-images.githubusercontent.com/73229309/213001874-49755345-7ece-444b-b438-2d4d0ca591a3.mp4

Adding a very small delay seems to prevent this
`			<StatusEffect type="OnAbility" target="Character" targetlimb="Torso" delay="0.1" stackable="false" >`

![image](https://user-images.githubusercontent.com/73229309/213004853-65fc7514-21c4-4b89-85a1-14df4b702cc5.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d58c6d7d43bd166e2f2fd94a0ec35a4d7dcea270

**Comment by NilanthAnimosus** [comment]
Tested against Fix/Bugfixes-2 commit https://github.com/Regalis11/Barotrauma-development/commit/97e99c225a92460269a4fc0937de649b36f450cb

When a character is hit and the effect triggers, although they do not go flying they do not appear to become stunned.

I tested this at first on crawlers and crawler hatchlings which didn't flinch and no stun appeared to occur so I used another character with a crowbar and on the controlled character attacking the one with the lightning wizard talent no stun appeared to occur.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/691b0c1cce897938ec8e0d793c3ec1e79b0d1856

**Comment by NilanthAnimosus** [comment]
Tested against Fix/Bugfixes-2 commit https://github.com/Regalis11/Barotrauma-development/commit/f05512708ea926f46853cbab08e1af3471a83b9e, no issues found, closing.
