### ISSUE TITLE
[Factions] Medical items spawned in medical crate refuse to work

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10952]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It's simply impossible to use the items that spawn in the medical crate for some reason.
Might be limited to sub editor?

Spawned or crafted items work just fine

https://user-images.githubusercontent.com/73229309/212978905-c8e5d535-e85d-49ec-9d4e-bf5c30a877e4.mp4

### Reproduction steps

1. Open Selkie in Sub editor
2. Grab 8x morphine from the medical crate
3. Try injecting yourself with all the meds, using any method available

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/468f790
