### ISSUE TITLE
Oiled Machinery using "Fabricatorspeed" instead of "Fabricationspeed"

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10953]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The mechanic talent **Oiled Machinery** uses "Fabricatorspeed" instead of "Fabricationspeed"

Desconstruction speed is increased but not fabrication

![image](https://user-images.githubusercontent.com/73229309/212986659-89188638-3ecc-4136-990b-e1e22f6e74b1.png)
![image](https://user-images.githubusercontent.com/73229309/212986675-ce93aa81-6b67-433d-b4c4-b1cd10669cfb.png)

### Version

0.20.16.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/87eb271b6c989ea623eb6466210c9eed60b157ae

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
