### ISSUE TITLE
Blackmarket Genes issues and changing how genes work in general

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10958]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Currently, there are **36** "Unidentified" Genes: 
One for each gene (12), for each quality (3). Quality determines the spawn probability and condition of the outcoming gene.
_I assume this is for mod compatibility: mods only have to add one more gene and 3 genetic materials, and since those are separate items the mods do not conflict._ 

This causes problems with blackmarket genes

1. Blackmarket Genes will have all 36 genes appear as "unidentified genetic material", cluttering the shop
2. You can "snipe" a specific gene/quality: the order of genes in the shop seems predetermined. Every 3rd gene on the list is consistently a high quality gene (30-60%) 

![image](https://user-images.githubusercontent.com/73229309/213191128-28e58200-2ac2-4488-b112-84d3a2b474ee.png)

Overall this isn't a clean system, and it feels like there are 36 individual genes where there could only be 3 (for quality).

The problem lies in using `identifier="geneticmaterialX"`, which means 1 unidentified material = 1 gene

```xml
    <Deconstruct time="5" requireddeconstructor="geneticresearchstation">
      <Item identifier="geneticmaterialcrawler" requiredotheritem="stabilozine" outconditionmin="0.1" outconditionmax="0.2" activatebuttontext="researchstation.research" infotext="researchstation.research.infotext" infotextonotheritemmissing="researchstation.combine.missingitem" />
    </Deconstruct>
```

The deconstruct system should be able to handle tags to avoid that. 
Replacing individual identifiers with `tag="refinedgene"`, adding said tag to all identified genetic materials, and picking the deconstruct outcome at random between ALL items with _refinedgene_ tag. Assuming of course you only want genes to be obtained randomly and not specifically dropping from the affiliated species

This wouldnt cause compatibility issues with Mods, and you would only have to add a single item (the refined gene) instead of 4 whenever you add a new gene

### Version

0.20.16.1

**Comment by Regalis11** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/commit/b8ee8604bb89a5680d98d2de74a95f2ba8b1d50b, no issues found.
