### ISSUE TITLE
Campaign settings menu doesn't show which preset is selected

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#10957]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The preset dropdown is always empty when you open the campaign settings. Not a huge issue, but I could imagine a new player being confused. 

Have I selected easy, normal or hard now? Which way does the difficulty go if I select one of these presets?
![image](https://user-images.githubusercontent.com/14351070/213193929-0997ed4a-d7aa-45bd-b74c-82157057369b.png)

### Reproduction steps

1. Open the campaign settings
2. Notice the preset dropdown is empty, even though I assume the Normal preset is selected
3. Change the preset to something else
4. Close and reopen the settings
5. The dropdown is empty again

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab1bcea1df10bd4554ef3b553bce87a68654970f

**Comment by Regalis11** [comment]
Tested, no issues found. Closing.
