### ISSUE TITLE
game immediately closes/crashes when opening server browser

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#10963]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

opening the server browser crashes or straight up closes the game

### Reproduction steps

open the server browser

### Bug prevalence

Happens every time I play

### Version

0.21.2.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/492bc284ed0f4e40347b64b023c08c6d0db280df
