### ISSUE TITLE
Bots refueling the reactor insert then drop more then one rod.

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#10966]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Well refueling the reactor bots will tend to insert and multiple rods into the reactor then onto the floor with the last one finally being left in the reactor.
![image](https://user-images.githubusercontent.com/12504812/213303952-69d0fe35-0a86-4a7d-bcd5-5cbc37081085.png)
(only 2 were partly used this time but more then 2 were dropped.)
Sometimes they will be used a bit or not at all. 
![image](https://user-images.githubusercontent.com/12504812/213303984-729c0272-866b-4f73-ab77-76c75c667bf4.png)
(all rods in this inventory were dropped by bot, on refueling)

### Reproduction steps

1. wait for rod to get low.
2. bot goes to refuel.
3. bot inserts and drops multiple rods.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No crashes caused.
```

**Comment by itchyOwl** [comment]
Didn't try it, but I suspect this would be another symptom of #10916, which is now fixed in unstable.

**Comment by Rokvach** [comment]
There hasn't been any sightings of this happening since the fix was released in the previous patch, seems to be working correctly. Closing.
