### ISSUE TITLE
Moloch Shell Fragment can be stored in the Toolbelt, but not the inventory

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10969]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue was discovered in 100.13.0.0.

The Moloch Shell Fragment can only be held by a player as a two handed item, except when being stored in the Toolbelt. 

### Reproduction steps

1. Spawn a toolbelt and moloch shell fragment
2. Place moloch shell fragment in the toolbelt
3. Observe how the moloch shell fragment is now inside the toolbelt

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Doesn't have anything to do with factions

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/acab4238a36f81cd0434ab1a7c5ca1724cf7ff49

**Comment by Wheatley1002** [comment]
The riot shield can also be stored in the toolbelt. This was confirmed by Hawkins#6699 just now, not sure if it's worth making a separate bug report for that since the two items are functionally similar

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0c56d9fb577adeb3ab47f28f3930fd95e6619deb

**Comment by JeroonBosch** [comment]
No issues found, closing
