### ISSUE TITLE
[Factions] Item conditions show incorrect values (networking issue?)

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10976]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.13.0.0
Server type: Steam P2P

### Issue Report
Item conditions seem to be reported differently from the server and the client. I have two examples of this and will go into detail based on the specific conditions in which this issue occurred. 

**Instance 1: Welding Fuel Tanks**
![image](https://user-images.githubusercontent.com/120612589/213438174-ccc7b8d0-338c-49dd-b294-46bfc0ebe6b7.png)
_Figure 1. Two stacks of Welding Fuel Tanks both showing max condition._

![image](https://user-images.githubusercontent.com/120612589/213438244-fd574638-e61d-42fd-b315-55d87aa0bd27.png)
_Figure 2. Both stacks have been combined into one stack of three tanks._

![image](https://user-images.githubusercontent.com/120612589/213438316-f7700326-3265-4901-9f0c-8a229e1b29de.png)
_Figure 3. Two tanks are dropped on the floor without player input after a delay of roughly one-two seconds._

As shown in the images above, the instances of welding fuel tanks all show max condition. Despite this, two of the tanks do not interact with the other tank like normal welding fuel tanks should. It is important to note that the two tanks which are causing issues were once at 0% max condition before becoming 100% at some point in the session. 

**Instance 2: Canister Shells**
![image](https://user-images.githubusercontent.com/120612589/213436511-2ade0bc8-37c9-4e96-ae46-0ed3a3cba68d.png)
_Figure 4. Canister Shells unable to be fired despite being 100% condition._

Whilst an image does not do much in displaying the issue, Canister Shells reported to the client (me) that they were at 100% condition. Despite this, they would not fire when the left mouse button was pressed in order to fire the railgun. My theory is that this was due to the server reporting the item condition at 0% whilst my client reported them at 100%.

I do not know what specifically caused the networking conflicts, as no significant disconnection or instance of lag occurred before these issues manifested within the session.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
> issue occurred in version 100.13.0.0

Top be clear, you mean the previous build, not the one that was just released yesterday (v100.14.0.0)? I.e. you hadn't updated to the latest version?

This issue should be fixed in v100.14.0.0 (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/3e86689).

**Comment by Wheatley1002** [comment]
> you mean the previous build

Yep! I have yet to host any test sessions in the new build. All of the recent reports made by me are from S2E2 (the last session which took place last Saturday (for future reference, that's the 19th of January 2023, aka 19/01/23)). I never got around to filing them so I've used the time I had today to report them. 
I've started adding the key information tag at the top of my reports to make it easier for you and other devs to know exactly what build the issue happened in, what mode, what server type, and how old the save file is. I'm also going to start backing up save files for each session so that, if needed, files from each "season" (complete testing session) can be accessed at any point :) I do apologise if any recent reports are ones that have already been fixed, but I'd rather not risk letting something slip through on the assumption that it was fixed in 100.14.0.0.

**Comment by Regalis11** [comment]
Alright, thank you for the clarification! :) In that case this should be fixed.

> I do apologise if any recent reports are ones that have already been fixed, but I'd rather not risk letting something slip through on the assumption that it was fixed in 100.14.0.0.

No need to apologize, your reports have been very helpful! It's better to get the occasional reports about duplicate or already-fixed issues than to have an issue go unnoticed by us.
