### ISSUE TITLE
Fuel rods can be recycled at any percentage and this increases the quality of the rod

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10974]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The recycle fuel rod recipe does not have a percentage limit like ammo boxes do (0-10%). This allows players to recycle fuel rods of 99% or lower. Additionally, doing so increases the quality of the fuel rod if appropriate quality conditions are met.

![image](https://user-images.githubusercontent.com/120612589/213431800-25067075-3c29-49c7-bd0f-cb4b2ad4116b.png)

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Why's this an issue? Doesn't it just mean you waste some uranium?

**Comment by Regalis11** [comment]
Yep, seems to have already been addressed in https://github.com/Regalis11/Barotrauma-development/commit/03fba0a1289e505df35ebd1f43816ee9c5c7083c. Closing.
