### ISSUE TITLE
Player other than host trying to purchase submarine upgrades without sufficient money receive an error and the option to try again is unavailable

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10970]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.13.0.0
Server type: Steam P2P

### Issue Report
A player with the manage money permission attempted to purchase a submarine hull upgrade with ~1k marks in their personal wallet (assuming the game would take money from the bank to cover the difference). Upon attempt of purchase, the game gave this error:
**Tried to purchase an upgrade with insufficient funds, the transaction has not been completed. Upgrade: Hull Reinforcements, Cost: 3062, Have: 1086.**
The player took 3k marks from the bank and tried to buy the upgrade again but was unable to do so.

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a5a5e288dd71783ef39323f41a9809b87b80620

**Comment by JeroonBosch** [comment]
Tested the fix with two clients, no issues found:

- Could not buy submarine if I did not have the bank permissions / wallet money [no error, no issues]
- Could buy submarine if I did have the money in my own wallet
- People with correct permissions could buy submarine just fine

closing
