### ISSUE TITLE
[Factions] Herja has a section which allows divers to stand on exterior hull in the water

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10977]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.13.0.0
Server type: Steam P2P
### Issue Report
I want to start this off by saying this is an incredibly difficult spot to get into. It will take time and some trial and error, but it is achievable and reproducible. 

Outside the Herja's airlock, if you destroy two parts of the floor and swim into the triangular crevice left behind, your model will be dragged into the wall and you won't be able to move. If you then ragdoll or move around enough, you will eventually free yourself of this issue and be standing on the hull in the water. You are actively outside of the submarine yet you can run around this small space as if you were inside the sub. Additionally, you can remove your diving suit and suffer no high pressure visual effects (despite the high pressure warning shown in the afflictions bar). You will still suffer oxygen low if you remove your diving suit. No player attempted to see if pressure still killed them in this spot as it was featured in Wheatley Gaming Season 2 Episode 2 and we did not want our progress impeded. 

![image](https://user-images.githubusercontent.com/120612589/213442314-4434debc-4b9e-4517-b09f-7020b1655b69.png)
_Figure 1. Me standing upright outside with a diving suit._

![image](https://user-images.githubusercontent.com/120612589/213442389-016ca389-cb4b-4229-b971-f7a02e9ce6d6.png)
_Figure 2. Me standing upright without a diving suit on, whilst another player stands beside me._

I will now attempt to document the reproduction steps. If you have any questions about them, please feel free to ask and I'll clarify any steps, but as I mentioned before the process is incredibly scuffed and difficult to get into. 

### Reproduction steps

1. Go onto the Herja
2. Get a plasma cutter 
3. Step outside the airlock
4. Break the two sections of hull above the small triangular structure which provides support to the airlock (see figure 1 for reference)
5. Swim into the point of the triangular structure (if the shape is a V you want to swim into the bottom part of the V)
6. If done correctly, your body should be dragged into a weird space between hull and no hull, causing you to lose control of your body
7. Hold space (ragdoll button) and release it. If you are still stuck, repeat this step multiple times until you are freed from step 6
8. You should stand up in the triangular structure and be able to walk back and forth as if you were in the submarine 

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
