### ISSUE TITLE
[Factions] Canister Shell can be recycled at 100% 

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#10975]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Issue occurred in 100.14.0.0.

![image](https://user-images.githubusercontent.com/120612589/213434888-b1e20b27-17f5-4d47-b5fa-e42731aec21b.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not a bug
