### ISSUE TITLE
[Factions] Repair bot sprites unfinished (?)

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10980]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While messing around a bit in the character editor, ive noticed that the repair bot seems to only ever use its light sprites, instead of that and the mechanical part present in the sprite sheet, which, unless an intentional choice, seems unfinished. Video of how a "full" version may look like using the present sprite attached. 

https://user-images.githubusercontent.com/104232152/213473020-b46ed691-2298-44f5-af06-3ac72dd3de94.mp4

### Reproduction steps

1.Check the sprite sheet for the guardian repair bot in comparison to its appearance ingame

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional. The mechanical part isn't for the repair bot, but for the fractal guardian's head.
