### ISSUE TITLE
AI Crewmates attack you when attacking hostile outpost dwellers

### ISSUE THREAD

**Issue by AtobaAzul** [Regalis11/Barotrauma#10981]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When attacking other humans in an outpost, AI crewmates will attack you, regardless of your reputation with the station's faction.
Ex: Attack a security officer, your own security officer starts attacking you.

While I'm here, I'd like to mention some feedback related to hostile outposts and AI as well: The crewmates casually walk around the station, and get shot by security shortly after. I'd suggest making hostile stations be like abandoned outpost, where you and your crew stay inside the sub.

### Reproduction steps

1. Enter an outpost which you have hostile reputation with.
2. Attack people inside the outpost.
3. Watch as you get gunned down by both security and your crew mates.

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea9f7117f18438ada1c5de99860d9591d5b0028e

**Comment by JeroonBosch** [comment]
Tested with security bots, could not get them to attack me after the fix, closing

**Comment by Regalis11** [comment]
Reopening, the crew still seems to spawn inside hostile outposts (at least in MP, didn't test SP yet).

**Comment by JeroonBosch** [comment]
Tested with -100 reputation, spawned on the submarine this time instead of in the outpost.
