### ISSUE TITLE
Stacks of welding fuel depleted while in storage container

### ISSUE THREAD

**Issue by Surpex** [Regalis11/Barotrauma#10987]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Stacks of welding fuel/oxygen tanks were depleted seemingly at random in storage containers during multiplayer. 

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid there's probably not enough information here to diagnose the issue. This might not even actually be a bug: it could be that the tanks were for example depleted by nearby fires or explosions. It could also be that the mods you're using had some kind of an effect on this, but hard to say without knowing what kinds of mods you're using.

**Comment by Surpex** [comment]
Ah... This is exactly it. I wasn't aware that local fires would deplete fuel. My friend started a fire in the same compartment. Thanks!
