### ISSUE TITLE
Rum description typo

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10983]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Rum has a typo in the description. 

It says "...good luck finding any of that Europa."

I assume it's supposed to be "...good luck finding any of that on Europa."

![image](https://user-images.githubusercontent.com/37850646/213514507-47496071-6113-4150-8ad8-efd1616e4146.png)

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Internal note: I fixed this in the localization kit now, but let's wait for the texts to be imported before closing this.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
