### ISSUE TITLE
Inconsistent "Rules" around water reactivity

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10986]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So, seems like when you put a water reacting item from your inventory into a waterproof  container it will, instead of resetting the delay, simply explode within the waterproof container, as if it werent waterproof.
I dont get why, considering it resets fine when you take it out of the water, but it doesnt count when put into a waterproof container. Video demonstrates it

https://user-images.githubusercontent.com/104232152/213554607-4279a7b2-36f0-4a29-aad0-c8fd296110f0.mp4

I can certainly see this being an issue when panic-stuffing a thing about to explode from your inventory into a waterproof container to save it, only for it to pop after.

### Reproduction steps

1.Take sodium
2.Enter Water
3.Before it explodes in your inventory, put it into a waterproof container, that wouldnt normally trigger it exploding
4.Note that it will now explode inside the container thats waterproof, as if it were still submerged.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
