### ISSUE TITLE
Most of the game sounds are encoded at 44100Hz, but VoIP works at 48000Hz

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#10989]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Most sound files, though not all (attaching list of 48kHz files), are encoded at a sampling rate of 44100Hz

Since the VoIP uses Opus that only works at 48000Hz, this will guarantee easily avoidable resampling of audio.

Converting all .ogg files to 48kHz with a script is proving to have no downsides on my machine.

[48000.txt](https://github.com/Regalis11/Barotrauma/files/10464156/48000.txt)

### Reproduction steps

Get sample rate of ogg files:
`find -name '*.ogg' | parallel ffmpeg -i 2>&1 | egrep -B2 '44100|48000'`

Convert all 44.1kHz files to 48kHz:
`cat 44100.txt | parallel ffmpeg -i {} -af aresample=resampler=soxr  -ar 48000 -q 10 {}.48k`
`cat 44100.txt | parallel mv {}.48k {}`

I no longer have the 44100.txt file, sorry.
*edit: a more sane `q` value might be preferable for distribution*

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not that familiar with how resampling even works, or why this is an issue. Could you elaborate a bit on why VoIP and the in-game sounds should use the same sample rate? Or why 48kHz is preferable over 44.1kHz, when the latter is a more commonly used sampling rate? I would've expected that using 48kHz across the board would be more likely to cause resampling.

**Comment by mygamingaccount** [comment]
Your audio hardware can only operate either at 44.1kHz or 48kHz at a time, everything else is resampled by the OS sound server.

If the OS chooses to run at 44.1kHz, then voice will be resampled. Then, if the hardware can run AD and DA at separate clocks (like HD Audio must be able to)  then only the sound from other players is resampled, most of the game audio will run at a native 44.1kHz, except for those sounds, which will be resampled by OpenAL.
If the hardware can _not_ run the AD and DA at separate rates (like many USB audio devices) then the voice _input_ from the player's microphone will also be resampled.

If the OS chooses to run at 48kHz, then voice will run at the native rate both in and out, but most game sounds will be resampled by OpenAL.

Vorbis can be coded at either, but Opus, the codec used for in-game voice, only operates at sampling rates of 8, 12, 16, 24, and 48kHz. Barotrauma uses 48kHz for voice. My suggestion therefore is to stick with 48000Hz for everything.

**Comment by mygamingaccount** [comment]
Resampling has some bad effects the less control you have over audio, like in the case of VoIP.  It increases latency, and it can cause clipping even when the input is clean. It also uses some CPU time, but it's rather irrelevant these days, and so is the quality loss.
Mixing different input and output sample rates can also cause some issues to surface in experimental sound servers on Linux which then have to be fixed by yours truly. But that's only my machine.

**Comment by mygamingaccount** [comment]
Adding to this mess is OpenAL Soft defaulting to 44100Hz unless directed otherwise by either `alsoft.conf` or the OS

**Comment by mygamingaccount** [comment]
I'm testing this:

Works even on hardware that only supports 44100Hz

```
diff --git a/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundManager.cs b/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundManager.cs
index 835981330..094afcbf1 100644
--- a/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundManager.cs
+++ b/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundManager.cs
@@ -300,7 +300,7 @@ namespace Barotrauma.Sounds

             Disconnected = false;

-            int[] alcContextAttrs = new int[] { };
+            int[] alcContextAttrs = new int[] { Alc.Frequency, 48000 };
             alcContext = Alc.CreateContext(alcDevice, alcContextAttrs);
             if (alcContext == null)
             {
```

**Comment by Regalis11** [comment]
We decided to go with just converting the handful of 48kHz sounds to 44.1kHz. https://github.com/Regalis11/Barotrauma-development/commit/b63a07d4d59c9133056f44fc574700dee9a4e66d

44.1kHz seems to be a more common sampling rate, and it's better to downsample than to upsample.

**Comment by mygamingaccount** [comment]
That's worse than doing nothing

This guarantees resampling of sounds in the game
