### ISSUE TITLE
Portable Pump's "Special training required to place this item." popup appears globally

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10993]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.13.0.0
Server type: Steam P2P
### Issue Report
Whilst in an outpost, a player within the submarine attempted to place a Portable Pump. This prompted the "Special training required to place this item." popup to appear for everyone in the game regardless of their position.

![image](https://user-images.githubusercontent.com/105495756/213835658-66545ed7-3043-4cd6-8c20-9d0cd4295338.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8826cda919b38ace56869b8b66881c4238269c14

**Comment by JeroonBosch** [comment]
No issues found
