### ISSUE TITLE
[Factions] Taste Test event appears globally and refuses to progress

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10998]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P
### Issue Report
Potentially identical to #9497 

A significant portion (roughly seven people) of the server lobby experienced the Taste Test event. The event refused to progress after input was given.

![image](https://user-images.githubusercontent.com/105495756/213843591-ef8b76a3-92dd-4bd1-9336-a7adea1a6b99.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7cb7b7539f5ff82cbe4857d23d73ce79c1e3b487

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
