### ISSUE TITLE
[Factions] Players who disconnect wearing Zealot Robes whilst infected with the husk become husks upon disconnection

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10999]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P
### Issue Report
If you infect yourself with the husk infection whilst wearing Zealot Robes, you will not succumb to the husk infection fully. A lot of players in the faction branch enjoy this part of the new faction items. I recently discovered, however, that if a player is infected with the husk whilst wearing the Zealot Robes and they disconnect, the "brain death" cause of death (given to players after they disconnect and enough time has passed) causes the player to reanimate as a husk.

This causes issues for several reasons:
1) It doesn't make sense as to why they became a husk
2) Ammo and meds need to be wasted over a supposedly immune individual turning into a husk
3) **It can mess with reconnecting into the character since it became AI controlled**
4) Players wanting to engage with Church of the Husk content will need to take extra precautions when disconnecting from the server. To ensure a character survives with the infection still applied, the host needs to immediately move location when the other player disconnects

I won't know the full effects of this situation until E4 happens tomorrow. If the player infected with the husk has to make a new character because of this, I will update the ticket accordingly.

UPDATE: This caused an item duplication glitch since I stored the items in a container. The same items spawned on the player's character, thus duplicating them.

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2c6a3481b2204f7d7855207b6100eaa8316a5b5b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
