### ISSUE TITLE
Rifle plays incorrect audio when firing 40mm Grenades

### ISSUE THREAD

**Issue by Lolnoobwut1** [Regalis11/Barotrauma#10992]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Rifle is intended to use unique firing sounds when firing 40mm Grenades, according to lines 1398-1403 in weapons.xml:
```
      <StatusEffect type="OnUse">
        <RequiredItem items="grenade" type="Contained" targetslot="1" />
        <Sound file="Content/Items/Weapons/WEAPON_rifleGrenadeShot1.ogg" type="OnUse" range="3000" selectionmode="Random" />
        <Sound file="Content/Items/Weapons/WEAPON_rifleGrenadeShot2.ogg" type="OnUse" range="3000" />
        <Sound file="Content/Items/Weapons/WEAPON_rifleGrenadeShot3.ogg" type="OnUse" range="3000" />
      </StatusEffect>
```

However, these sounds never play. The default firing sound for the Rifle (Content/Items/Weapons/WEAPON_rifleShot#) plays instead.

### Reproduction steps

1. Spawn a 40mm Grenade and a Rifle.
2. Load the 40mm Grenade into the Rifle and fire.

### Bug prevalence

Happens every time I play

### Version

0.21.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97e99c225a92460269a4fc0937de649b36f450cb

**Comment by JeroonBosch** [comment]
Tested, works now
