### ISSUE TITLE
[Factions] 40mm mini nuke causes wires (item) to have 0% condition if caught in explosion

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11000]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P
### Issue Report

If a red wire is in a container and a 40mm mini nuke is detonated in the area nearby, the condition of the wire will drop to 0%. This is an unnatural process since, to my knowledge, nothing else can cause the wire to drop condition. Additionally, trying to use the 0% red wire causes interesting conflicts. The wire cannot be placed down anywhere like normal wire, and the wire constantly tries to go to a fixed point in the submarine. This is regardless of what device the wire is hooked up to, as well as the distance from the fixed point and the device.

![image](https://user-images.githubusercontent.com/105495756/213844020-446b7ef3-f8c3-4b1f-9e6e-45e8fc363e4d.png)
![image](https://user-images.githubusercontent.com/105495756/213844022-5397d07b-48a7-4dd7-84cb-d20fe891e8ae.png)
_Figures 1. 0% red wire._

![image](https://user-images.githubusercontent.com/105495756/213844029-7fbf4cd9-e91e-40a4-ba93-e18a99cd8d74.png)
![image](https://user-images.githubusercontent.com/105495756/213844031-a633a7d9-b3d0-44a6-b2e8-fd518f8ea674.png)
_Figures 2, Players trying to interact with 0% red wire and being unable to._

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. Tested with wires on the floor and wires in a metal crate, and couldn't find a way to get either to take any damage from the explosion.

**Comment by Wheatley1002** [comment]
I can provide you with the save if that helps! The 0% condition wires should be stored in the Herja's reactor room (unless someone took them). The only thing that happened abnormally was the 40mm nuke being used, as we wanted to test it and other separatist items.

**Comment by Regalis11** [comment]
The save file could give us some more clues on what happened here, so please do send it! Thanks!

**Comment by Wheatley1001** [comment]
Here's the save file and character data taken from the end of S2E4. Due to the backup system I've got, I can only give you the saves as of the end of each session. That way if something goes horribly wrong, I can revert the campaign to the start of the session. Hopefully this helps though!

[S2E4 Save File and Character Data.zip](https://github.com/Regalis11/Barotrauma/files/10481690/S2E4.Save.File.and.Character.Data.zip)

**Comment by Regalis11** [comment]
No known steps to repro, closing
