### ISSUE TITLE
Exosuit has no buzzer for running out of oxygen

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11004]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Very simply, the exosuit will buzz when running out of battery, but not when running out of oxygen, so its easy to not realize what the issue is when youre slowly dying of oxygen deprivation.

### Reproduction steps

1.Equip exosuit
2.Wait until the oxygen for it runs out 
3.Note that when it does, its silent

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a97f529a1168a1eb1d3249d6500c91603430f6ac

**Comment by JeroonBosch** [comment]
No issues found

**Comment by Regalis11** [comment]
Does not work correctly, reopening. See https://github.com/Regalis11/Barotrauma/issues/11076

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/31afcf0ac26d16c2fcc6366f8da046147dbd4061

**Comment by JeroonBosch** [comment]
Now tried to also put the low oxygen tank in other slots - seemed to correctly beep or not beep depending on the oxygen tank %
