### ISSUE TITLE
[Factions] Lobby menu used endgame splash art for the background (SPOILERS)

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11007]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P

### Issue Report
I went to start up the lobby for S2E4 and was met with the background art used for the ending level of the game.

![image](https://user-images.githubusercontent.com/105495756/213896918-1763586c-5c94-41b0-b596-0922422bf52b.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/deaecdc16f33709fcfb7a5f5a3bc4fea297dba2b

**Comment by Rokvach** [comment]
There hasn't been any sightings, seems to be working correctly. Closing.
