### ISSUE TITLE
[Factions] Scavenger works on outposts and the items spawn marked as stolen

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11002]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P
### Issue Report

![image](https://user-images.githubusercontent.com/105495756/213842921-5699e3c1-583c-47c8-b27b-7e174c6cfc90.png)
![image](https://user-images.githubusercontent.com/105495756/213842922-6833fa6a-4961-452e-9dc3-46f449ea5c36.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I wouldn't consider this a bug. The description says "a container outside your sub", which includes outposts.
