### ISSUE TITLE
Hemulen shuttle cannot drain its lower airlock if flooded

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11019]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you add water (leaks, command etc) to the hemulen in the lower airlock area, the pump can only drain the upper hull but not the lower smaller hull:

![image](https://user-images.githubusercontent.com/29177976/214061923-67b42ed6-8de8-4baf-93b4-a7038b7ab782.png)

### Bug prevalence

Happens every time I play

### Version

0.21.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0a49f6b01c522e1bb191bb73a895b62db0d5f8f1 by moving the pump to the bottom of the room.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
