### ISSUE TITLE
Junction box has Lightcomponent properties in subeditor twice

### ISSUE THREAD

**Issue by DuckY-Y** [Regalis11/Barotrauma#11012]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The junction box has in the properties the "LIGHTCOMPONENT" stated twice as seen below.
![image_2023-01-22_190658760](https://user-images.githubusercontent.com/84920066/213932356-aaad5ff8-9963-4bf0-985d-c362d545b87c.png)

Editing a property in one of the two will change it in both.
Current order of properties as displayed:
JUNCTION BOX
POWERTRANSFER
LIGHTCOMPONENT
LIGHTCOMPONENT
CONNECTIONPANEL
REPAIRABLE

### Reproduction steps

1. Open sub editor
2. Place junction box
3. Scroll down the properties

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment]
I'm pretty sure this is normal, it seems that one lightcomponent is used for green light(normal state) and the other for red blinking light (heavy overvoltage).

**Comment by Regalis11** [comment]
Yep, this is not a bug: the boxes have two lights, the green and the red one.

**Comment by DuckY-Y** [comment]
ah ok
