### ISSUE TITLE
[Factions] Toy Hammer unable to trigger event 

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11010]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hitting an abyss creature with a Toy Hammer after completing the Path of the Bike Horn 2 event doesn't seem to trigger the event `toyhammeronabyssmonster`.

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/69250438e7ff902d4d41fee2b19e5e7234cbd184

**Comment by JeroonBosch** [comment]
Tested, no issues found:
Gave myself a toyhammer, used `setcampaignmetadata pathofthebikehorn 2` command
Spawned an abyssal creature (disabled AI) and bonked it: it successfully triggered the ConversationAction.
