### ISSUE TITLE
[Multiplayer only] There's no inventory visual warning if you try to pickup a two-handed item from the floor while you are already carrying a two-handed item

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#11018]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Noticed during testing that I wasn't able to pickup any two-handed items while carrying a Fire Extinguisher and there wasn't any warning telling me as to why I couldn't pick them up. 

### Reproduction steps

1. Host a server and load into mission mode
2. Pickup Fire Extinguisher
3. Drop a ammo box from a loader
4. Try to pick it up from the floor
5. Notice that there is no red flashing over the hand slot where the Fire Extinguisher is
6. You can see the red inventory slash if you try to pickup the ammo box from the loader directly

### Bug prevalence

Happens every time I play

### Version

0.21.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/87a7e8993077ea5a624cfebc64e4c9e19292f0a4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
