### ISSUE TITLE
Publishing a sub to the workshop greets me with an Error in the console.

### ISSUE THREAD

**Issue by DuckY-Y** [Regalis11/Barotrauma#11021]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I wanted to update a sub but for some reason it didn't let me so I deleted it and tried to publish again.
![image](https://user-images.githubusercontent.com/84920066/214151832-3039e160-cd3c-4f22-9443-7a5900f2bfc7.png)

This error isn't limited to only one sub.
I managed to fix this by validating.

### Reproduction steps

1. delete published version of sub.
2. try to publish updated version of sub.
3. get error in console

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by DuckY-Y** [comment]
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/10608769/crashreport.10.log)
@Regalis11 is enough info?
it happened again

**Comment by DuckY-Y** [comment]
![image](https://user-images.githubusercontent.com/84920066/216771290-90f80636-45b3-4097-985c-7a9a6e000836.png)
I think the issue is uploading a different local package of the same sub that's very similar or something like that, it has happened to me trying to do something with sub packages..

**Comment by Regalis11** [comment]
No known steps to repro, closing
