### ISSUE TITLE
Issues/Lack of warning for new requirements for a sub to be campaign compatible

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11025]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While only relevant in very rare cases, considering the max size requirements for the ending, it may be important to introduce some kind of warning for a sub, if is not compaitble with finishing the campaign, if it is too large. Going off of the rough estimate of a max sub size of 200m by 200m going by the endzone entrance gate, subs should probably have some kind of warning, either ingame, or when saving it in the sub editor, as in its current state _somebody_ would probably eventually get to the end with an oversized sub and get stuck. /:

### Reproduction steps

Not much to add here

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f584fb10186a33953e500b722df501a4eaaabfea

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/ad8a00975de30dcd281146ac3b1684e0272bc421

Dimensions are displayed in different order in the warning than sub preview or wiki.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/f6dacf9c-1229-475b-80c8-4df2cd950093)
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/14252a1d-c3ef-462f-a1bf-1fa3826f7ec5)

No other issues found

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/07c2f9f79ade033617fd8ea955e3aee3caf4b5fa

No issues found
Closing ticket
