### ISSUE TITLE
Events double pop on dock.

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#11022]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When entering a station with two PA missions they will send two messages, feels like a redundancy more then a bug per say. 
![image](https://user-images.githubusercontent.com/12504812/214207110-23250666-84f4-48c9-a3db-eb88c7d397aa.png)

### Reproduction steps

1.Enter station with two ! missions
2.Will require 2 message clears.
3.(does not include any ! conversations related to characters that are hireable from what I have seen)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
> feels like a redundancy more then a bug per say.

I agree, and it's also quite rare to get two of these events in the same outpost.
