### ISSUE TITLE
the flashlight discharges even when the assault rifle is on the belt

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11023]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the flashlight discharges even when the assault rifle is on the belt
it would be nice if the flashlight on the weapon could be turned on and off
or at least make it turn off when you hang a rifle on your belt

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by pavel4win** [comment]
when I took the flashlight out of the rifle and put it into inventory, then, took it into my hand, removed it from my hand, put it back into the rifle, the discharge of the flashlight stopped.

**Comment by itchyOwl** [comment]
Can't repro this: the flashlight doesn't seem to discharge when it's attached to an assault rifle placed on the belt slot (back). And it does discharge when I'm holding the gun in hand. Tried unattaching/reattaching the flashlight both when the gun is in hands and on back. Also tested equipping the flashlight in hands before inserting it in the gun. Also tried removing and inserting the battery cell. In all cases, the light is off when it should be and the battery doesn't discharge when the light is off.

**Comment by OCDscavenger** [comment]
While already wearing something in the belt slot, grab a belt slot weapon with a flashlight attached to it. then, swap the position of the weapon you are holding with what you are wearing on the belt slot, so that you are now wearing the weapon and holding what was originally on the belt slot. If performed correctly, the visual effect of the flashlight will still be active and pointing directly to the left or right of the character.

**Comment by itchyOwl** [comment]
Managed to repro. Here's the steps as screenshots:
![image](https://github.com/Regalis11/Barotrauma/assets/5370738/96224fd0-0bb5-4561-8999-cfd3345fe13a)

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/9e99b5ba-aa8c-48c8-af7c-0e2e1bfb9c28)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@8d879c0

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
