### ISSUE TITLE
EventText.waytoascension1.04.c1 / church of the husk ecclesiast text

### ISSUE THREAD

**Issue by Traumatic-apricot** [Regalis11/Barotrauma#11020]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when talking to a church of the husk member i got this filename instead of the text: EventText.waytoascension1.04.c1
![Capture](https://user-images.githubusercontent.com/123396519/214093745-4a448c62-3a3d-47d8-bada-dd6afe7f2fc6.PNG)

### Reproduction steps

1. start campaign 
2. and express your interest in learning more about the church of the husk
3. when the man humors you get his question about the second metamorphosis wrong
4. find a new husk ecclesiast guy on a different station 
5. when asked about the second metamorphosis once again chose option 4 / "I'm afraid I don't know. Yet."

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no error messages just the file name it gave: EventText.waytoascension1.04.c1
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a7af6a7db92d4fb9cc236203836f659d9bc48c8 (commit in our private repository)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
