### ISSUE TITLE
[Unstable] Problems with sufforin

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11038]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sufforin has some unintuitive behaviour when transitioning from nearly full strength to full strength, which causes some problems when trying to heal the poison.

At 199 strength, sufforin poisoning deals -200 vitality. at 200 strength, it deals 0. This means that when the poison progresses to full strength, a creature who has been afflicted with the poison, and is very injured, suddenly recovers instantly, its health bar seemingly refilling itself. The creature then has a 10% chance to remove the poison each second, which means in many cases using Sufforin leads to an extremely small amount of organ damage, and not much else.

https://user-images.githubusercontent.com/37850646/214890655-df2b68ef-1b37-4966-9110-62b16ad5c393.mp4

I'm not sure if this is intended behaviour - it seems that sufforin can be very useless in some cases, and the health jumping up by 200 is a little odd, and can impact whether the affliction is shrugged off by the creature that is poisoned.

Next, it is almost impossible to heal sufforin is almost impossible without killing the patient accidentally. This is for the opposite reason to above; going from 200 affliction strength to 199 instantly reduces the patient's vitality by 200, which means using stabilozine or sufforin antidote will drop the affliction strength, and just instantly kill the character who had the treatment applied to them.
Now, I'll admit this behaviour is pretty funny, but I can't imagine it's intentional.

https://user-images.githubusercontent.com/37850646/214895630-a7c00733-47df-4f05-bb0c-e12ba0b91123.mp4

### Bug prevalence

Just once

### Version

0.21.4.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development#3911.

**Comment by Regalis11** [comment]
Tested, no issues found. Merging and closing
