### ISSUE TITLE
[factions] accepting jestmaster on board gives two identical characters

### ISSUE THREAD

**Issue by Fentanyl1984** [Regalis11/Barotrauma#11034]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

after fully finishing the Children of the honkmother questline, option to talk with jestmaster appeared. After accepting him on board, two exact characters spawned

### Reproduction steps

1.fully finish the children fo the honkmother main questline
2.reload the save(at least thats what i did, but finding jesmaster manually may work the same)
3. Talk with jestmaster and accept him on board
![20230126153032_1](https://user-images.githubusercontent.com/123274797/214845027-4827a6cb-dbfc-430d-9fc9-842bc9dd34da.jpg)
![20230126153139_1(1)](https://user-images.githubusercontent.com/123274797/214845035-42262190-9e7a-4ddf-a3b3-2181b6e28a15.jpg)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1b5ab41273f1887006ee7e3eba447c38c390c354

**Comment by Regalis11** [comment]
Note for testing: we should also check if this applies to any of the other hireable faction NPCs.

**Comment by Regalis11** [comment]
Looks like the issue applies to the other NPCs too, fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a41f1adc7c30ce2e5c7c2fb2e8274aed0a64434

**Comment by NilanthAnimosus** [comment]
Tested against Fix/wip-fixes-january commit https://github.com/Regalis11/Barotrauma-development/commit/1a41f1adc7c30ce2e5c7c2fb2e8274aed0a64434, no issues found, closing.
