### ISSUE TITLE
[Factions] Clown Haven event issues

### ISSUE THREAD

**Issue by JeroonBosch** [Regalis11/Barotrauma#11035]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There's a few things I noticed trying to complete the clownhaven questline:

- [x] Funbringer 3000 comes without Fuel Rod
- [ ] No message or description suggests it needs a Fuel Rod
- [x] Funbringer 3000 comes without Oxygen
- [x] No Oxygen Alarm in Funbringer 3000
- [x] Label reference missing clownhaven.progress
![image](https://user-images.githubusercontent.com/8641689/214847423-8e0473f6-9c9c-489a-8bb2-1fb568979f4f.png)
- [ ] Progress was rather hard to fill. At 2/3rds security started to arrest me. I needed to switch to a bot to uncuff me. The second time I got arrested, they took my Funbringer 3000 and I got stuck?

### Reproduction steps

1. Get to an outpost with a clown module
2. setcampaignmetadeta pathofthebikehorn 4
3. triggerevent pathofthebikehorn4
4. Talk to the Jestmaster
5. Obtain the Funbringer, notice missing Fuel Rod and Oxygen (player starts suffocating right away and cannot move)
6. Find the target of the Clownhaven mission on the map and go there
7. Try to fulfill the objective, it is hard not to get arrested as there's little defense against stun batons. Notice how the suit gets taken away after 2 times (unless this was a random bug)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Fentanyl1984** [comment]
in my case all, once event passed the point where security gets triggered , my bots started fighting security back even before outpost security actually started using guns instead of stun batons

**Comment by Regalis11** [comment]
Save file for easier testing: 
[Save 133.zip](https://github.com/Regalis11/Barotrauma/files/10510548/Save.133.zip)

**Comment by juanjp600** [comment]
Tested this, found a bug with the Funbringer 3000:
![image](https://user-images.githubusercontent.com/8607119/216076139-91cff8ff-ee97-40d2-8c9d-36420584a291.png)
