### ISSUE TITLE
[factions] ai pathing in city outpost / ai falling of ladders 

### ISSUE THREAD

**Issue by Traumatic-apricot** [Regalis11/Barotrauma#11036]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

campaign singleplayer version100.16.0.0
every ai that attempts to use this ladder from a hallway in the city outpost to the clown area is falling of at the top, its hard to show with images but it think i did an ok job
save file: [test build save.zip](https://github.com/Regalis11/Barotrauma/files/10509761/test.build.save.zip)
image 1: you see them climbing
![20230126232633_1](https://user-images.githubusercontent.com/123396519/214849641-fafa60fb-9af4-44d4-b799-28c70ef8c8f3.jpg)
image 2: you see more climbing + a guy hitting the floor
![20230126232638_1](https://user-images.githubusercontent.com/123396519/214849864-690b521a-cdc3-437e-b18d-a7ac80eb8be4.jpg)
image 3: same thing people climbing dude on floor
![20230126232645_1](https://user-images.githubusercontent.com/123396519/214850042-c6be4639-9e94-4eb2-9844-7cf858253442.jpg)
image 4: same thing
![20230126232648_1](https://user-images.githubusercontent.com/123396519/214850132-1345f462-6afe-473c-8235-49e3a866d644.jpg)
image 5: the guy at the top has just got to that part of the ladder and gotten off to early as you can see
![20230126232655_1](https://user-images.githubusercontent.com/123396519/214850400-b08755de-763f-4ccd-86ec-42ef96be3ccc.jpg)
i have more images but you get the point just comment if you need more don't want to make this more lengthy 

### Reproduction steps

1.open the save file
2.go left to the top of the clown area ladder then there is a guy next to a HR manger
3. to get people to start climbing inspect him and give him the cure even though you don't have any
4. you will be told you have no cure but he will get up in a bit anyway 
5. go to where the ai where falling the image and wait

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none hope my bug report helped :)
```

**Comment by itchyOwl** [comment]
Adjusted the waypoints a bit in Regalis11/Barotrauma-development@6f0bb96. I suspect it's an edge case with the outpost modules, where we shouldn't maybe generate the waypoints using the same logic as we do on other ladders. Possibly something to get back to later.

On testing: Just use the save file above and make a bot follow you.

**Comment by Regalis11** [comment]
Nothing to review here, moving to QA

**Comment by NilanthAnimosus** [comment]
Tested against Dev commit https://github.com/Regalis11/Barotrauma-development/commit/cb8bb64424ca2bf987f2fd617fb4e33dd9a0382c, no issues found, closing.
