### ISSUE TITLE
cannot stack items if the stack contains an item with none max condition

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11030]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It is possible on consumables to partially consume an item in a stack, and then have it become hidden within the stack preventing combining or stacking until its removed from said item stack.

So I encountered this when testing poison tweaks, but it is in the game for other things (Such as protein bars) and not relevant to the changes there. The short video below showing the issue after partially consuming an item (then unequiping it from hands):

https://user-images.githubusercontent.com/29177976/214561252-011f436e-cc9e-4fcb-98b3-b3220b832f53.mp4

### Reproduction steps

1. spawn 8 protein bars into your inventory (Or at least, a stack of 3 or higher)
2. equip one via the number keys and aim with it, do not fully consume the item
3. unequip the item - note that there is no longer a visible condition
4. Try to add an extra item to the stack - note it is denied as seen in the gif
5. pull the stack apart one at a time to find the lower condition item is inside the stack hidden

### Bug prevalence

Happens every time I play

### Version

0.21.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b4d64e968b168c81f08f85fc93a3a2163aaddd75

**Comment by Rokvach** [comment]
This is working weirdly

1. Spawn a stack of Protein Bars
2. Remove one from the stack
3. Slightly eat a Protein Bar on the stack
4. Try to place the item you took out back into the stack
5. Notice that you get a warning that the item can't be moved onto the stack
6. Notice that the partially eaten Protein Bar isn't at the top of the stack anymore
7. Try and place the item which previously didn't go into the stack to the stack again
8. Notice that the item is placed into the stack and the partially eaten Protein Bar gets thrown out to its own slot
9. Notice that you can't place the partially eaten Protein Bar back into the stack even though it was in the stack when you ate it

Imo partially used items should either always be stackable or then thrown out of the stack when you eat them, always stackable would be the simpler solution.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7b623a0995c54ce98e9c6d91a8b7bb13b19a5da0

> Imo partially used items should either always be stackable or then thrown out of the stack when you eat them, always stackable would be the simpler solution.

Perhaps, but I'd consider that a separate issue

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
