### ISSUE TITLE
Depleted fuel revolver rounds has different fabrication materials in-game than defined in the XML.

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11032]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The xml for depleted fuel revolver rounds is:
![image](https://user-images.githubusercontent.com/37850646/214798382-810bbdb3-535c-4148-9b5a-2f3f0db37238.png)

However in-game the recipe is different:
![image](https://user-images.githubusercontent.com/37850646/214798733-4b8b45ae-85f4-4e01-b272-685b5431fb85.png)

It was expected that the in-game recipe should be the same as defined in the xml.

In testing, it was found that explicitly defining the `amount="1"` to the magnesium and depleted fuel corrects the recipe. It is possible that since the amounts are not defined for this recipe, it uses the amounts from the resources in the base recipe, (depleted fuel revolvers is an item variant of revolver rounds, whose recipe is 2 magnesium, 2 lead, 1 copper).

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@b95cda4. Tested to be craftable with 1 of each material now.

**Comment by ekqvist** [comment]
Merged. Closing.

**Comment by HawkinsThe71st** [comment]
Advanced Syringe Gun recipe seems to have the same issue:
![image](https://user-images.githubusercontent.com/115734437/214859536-d50c9d7d-97e9-49cc-b33a-c94e5c9d7c17.png)
Advanced Syringe Gun xml:
```
<Fabricate suitablefabricators="fabricator" requiredtime="10" requiresrecipe="true">
      <RequiredSkill identifier="medical" level="50" />
      <RequiredItem identifier="titaniumaluminiumalloy" />
      <RequiredItem identifier="aluminium" />
      <RequiredItem identifier="plastic" amount="2" />
    </Fabricate>
```
