### ISSUE TITLE
Too many non shadow casting lights cause issues.

### ISSUE THREAD

**Issue by SeaverBeaver** [Regalis11/Barotrauma#11041]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When enough non shadow casting lights are in close proximity, (in testing, more than 18 lights within 5 meters,) some of the lights lose both their brightness and their range, seemingly related to the position of the player. When moving past them, the lights flicker in/out based on the players current position.

![image](https://user-images.githubusercontent.com/95244788/215005549-7c8ffd83-30ef-484c-96be-989c85d8ca53.png)

In this image, all of the lights pictured at the top of the screen should be on, and at full brightness, however that is clearly not the case. When walking past them, the lights flicker based on character position, and return to full brightness when the player is nearly out of eyesight. I have found this problem with both modded and vanilla light sources.

Enabling shadow casting on the lights fixes this issue, but given the "soft limit' on shadow casting lights and the desire to keep performance, that's not really a viable solution for lots of decorative lights.

### Reproduction steps

1. Open the Submarine Editor
2. Open any sub
3. place down 20 light components within close proximity (5m) of each other, ensuring all are on and none are casting shadows.
4. Test the sub, walking back and forth past the lights, they should flicker in/out based on your position.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by SeaverBeaver** [comment]
https://user-images.githubusercontent.com/95244788/215007120-a47b2d2f-b543-4d83-b510-5999cb191dde.mp4

A short video showing the problem in greater detail.

**Comment by Regalis11** [comment]
Thank you for the report!

This is actually an intentional feature: as an optimization, there's a limit to how many lights there can be visible on the screen at a time. The limit can be adjusted or disabled in the game settings ("visible light limit" at the right side of the "graphics" tab).
