### ISSUE TITLE
[Minor] Herja layering issues

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11048]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**Floating Ballast Pumps**

![image](https://user-images.githubusercontent.com/105495756/215237022-1f7450d2-d4ff-4730-aa03-8396f7e3802b.png)
_Figure 1. Ballast Tank A's pump floating slightly above the ground._

![image](https://user-images.githubusercontent.com/105495756/215237245-657bae94-eec2-4427-bc34-ffd994dd8459.png)
_Figure 2. Ballast Tank B's pump floating slightly above the ground._

**Ladder Layering Issue**

![image](https://user-images.githubusercontent.com/105495756/215241022-913e94e3-d7de-407e-9a82-cc5a3ae75831.png)
_Figure 3. The ladder is both behind and in front of the hatch, implying the hatch goes through the metal ladder steps._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
The hatch has been fixed, but now starts open:
![image](https://user-images.githubusercontent.com/8641689/216935653-9fbd12f7-b69f-42b3-a9f5-1dd857765d9f.png)
Not sure if already before it was open by default. I don't think it's an issue though, so closing
