### ISSUE TITLE
Unable quickly swap item from condition-based* subcontainer and inventory

### ISSUE THREAD

**Issue by Stolaire** [Regalis11/Barotrauma#11044]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can't quickly reload from inventory condition-based* subcontainer. Example:
![image](https://user-images.githubusercontent.com/17797554/215141363-8bf88688-a090-43ea-b7ac-00f4a68b8e20.png)
When pressing 4 I can't quickly swap battery on a scrap cannon. It also occurs with harpoon coil-rifle.
Meanwhile:
![image](https://user-images.githubusercontent.com/17797554/215145336-4723950f-1bd0-418b-b263-b85572aa9275.png)
You can swap condition-based* main container from inventory. As you see, I can quickly replace assault rifle magazine.
![image](https://user-images.githubusercontent.com/17797554/215145547-ea0347fd-ea04-4eac-9365-0bbf1654a331.png)
I can also fill up capacity-based** subcontainer in rifle, regardless of main container condition.

*the container that consumes the condition of contained item on use - SMG, flashlight, welder, etc
**the container that consumes whole item on use - revolver, detonator, PUCS' subcontainer, etc

### Reproduction steps

See examples.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I wouldn't necessarily consider this a bug: you can only swap items in the container's "primary" slot (the first slot).
