### ISSUE TITLE
Game won't start after new updates.

### ISSUE THREAD

**Issue by Amog0** [Regalis11/Barotrauma#11042]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some reason, a few months earlier i think after the thunder under the ice update (the update that followed that one) the game just doesn't want to boot up anymore, at all. I removed my mods, reinstalled the game a few times and nothing.

Before the game ran perfectly fine, this might be an issue of me using an old laptop but, it ran perfectly good at 30 fps before? 
So, unless something is wrong with my copy of the game. It could be a technical issue of a very oudated graphics driver.

Though, i'd like to know that for certain. As i enjoyed the game alot and want to come back to it.

### Reproduction steps

1. Have a HP pavillion laptop
2. Game updates
3. Game not work
4. ???????????????????

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/27/2023 13:41:00)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    Game not initialized

Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: Void Load()
Stack trace: 
   at Barotrauma.Md5Hash.Cache.Load() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Md5Hash.cs:line 24
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 231
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57

Last debug messages:
[01/27/2023 13:40:59] Logged in as _____ (SteamID _________)

(ID and name blurted out for privacy reasons.)
```

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not completely sure what could be causing this, but based on the error report it seems the MD5 cache file might be corrupted. I suggest trying the following: navigate inside the game folder, go to a folder called "Data" and delete a file called "hashcache.txt". 

Please let us know if that helped or not! Sorry for the inconvenience.

**Comment by Regalis11** [comment]
I implemented a fix that should prevent a corrupted cache file from crashing the game now https://github.com/Regalis11/Barotrauma-development/commit/01be6f0b9cae90c549a07ea18df875183537512e (commit in out private repo, not publicly available yet)

**Comment by Amog0** [comment]
No way, thanks so much man. It was just that little corrupted cash and i just waited hoping for it to get fixed by itself or thinking my laptop was just shite. Super fast response too!

**Comment by Regalis11** [comment]
Internal note for testing: just save an empty text file to "Data/hashcache.txt" and launch the game.

**Comment by 3e849f2e5c** [comment]
Tested, hash caching was removed in https://github.com/Regalis11/Barotrauma-development/commit/02ab3f5ea2f2eb9621d89ea92b76cddcee4f3eed didn't spot anything else
