### ISSUE TITLE
Sulphurite can be thrown

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11049]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sulphurite can be thrown despite it having no functions when thrown. It is the only alien item other than Oxygenite which can be thrown. According to one of the players in the session, this is because of unremoved code copied from the Oxygenite item. 

Whilst this doesn't cause any gameplay related issue, this ticket serves more as written proof to see if this function is intentional or not. 

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I'm not sure if it's intended to have some effects or not, but don't see this an issue.

**Comment by Wheatley1001** [comment]
> I'm not sure if it's intended to have some effects or not, but don't see this an issue.

If it's supposed to have effects, they currently don't exist. It's an item you can throw and there's no reason as to why you would want to do this. No other "non-throwables" item can be thrown aside from the Sulphurite Shard. It's not an issue that directly impacts gameplay, more of something that should be brought to your attention to see if it's supposed to be a throwable item (because if it isn't then it's a bug).

**Comment by itchyOwl** [comment]
I don't think it's a bug, because there's just no effects defined. Anyway, something we should address for the sake of consistency. Either make it non-throwable or make other similar items throwable (and add some effect maybe).

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f0f307b61f5a3d3fe5fa1b152b2c0c16ef8a8cc5

**Comment by Jasontti** [comment]
Tested, sulphurite shard now explodes when thrown and gives correctly acid burn and stun effects. Closing ticket.
