### ISSUE TITLE
Status Monitor orders constantly show as in the command room and do not show up to other players

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11054]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0 (also occurred in 100.17.0.0)
Server type: Steam P2P
### Issue Report
I'm pretty sure this is a much older bug but I couldn't find a ticket using keyword searches so I apologise if this is a duplicate.

Trying to use the quick report feature (dragging icons onto hulls in the ship) will not report the correct hull. Regardless of the hull you drag the icon onto, it will always report this as the command room. In addition to this, other players cannot see the location of the order. They will be able to read the callout in the chat, but will be unable to see the icon pointer which typically shows up when an order is given in this way.

![image](https://user-images.githubusercontent.com/105495756/213844050-36cfc28c-b6c2-4322-9fc9-354cd358fd6d.png)
![image](https://user-images.githubusercontent.com/105495756/213844052-43c10ba0-74eb-4db1-9e55-548f4f12fff1.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dbe61c154c3d4cd99cbe3714bd9d8597a292b344
