### ISSUE TITLE
[Factions] Outpost Rescue text doesn't make sense when aligned to Separatists

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11052]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon accepting an Outpost Rescue mission for an abandoned Coalition outpost, the text will read "The Coalition doesn't negotiate with terrorists". This text makes perfect sense unless you're aligned with the Separatists (which we were) and have extremely low reputation with the Coalition (which we did). The Coalition considers the Separatists to be terrorists, so for the text to tell the players that the Coalition does not negotiate with terrorists whilst actively negotiating with terrorists to remove the terrorists from their outpost, it sends a few mixed signals. 

![image](https://user-images.githubusercontent.com/105495756/215238078-50ca01e5-c2b5-41d1-8911-0933ed794ef9.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Personally I don't think there's an issue here. The Coalition isn't negotiating with your "terrorist crew", they've just promised a reward to whoever rescues the hostages from the outpost.
