### ISSUE TITLE
Genetic Material Taints falsely report themselves as untainted during level transitions

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11057]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P
### Issue Report
Genetic material refined at an outpost recorded itself as tainted. However, upon level transition, the material changed to reporting itself as not tainted. This caught our attention and we wanted to see if the tainted materials would report themselves correctly at the next outpost. Upon arrival, we confirmed that the material reported itself as tainted once again. The material was still tainted if used during the level transition (in which the taint was not reported).

This could be due to networking. We're not entirely sure what specifically caused this issue to surface, as the only thing we did was travel to a new location. 

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ff8d7391b2547ca4764693bff856f8bc4d0e7f4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
