### ISSUE TITLE
[Factions] Nest Creatures spawned outside of the cave

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11053]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P

### Issue Report
Our gunner spotted Tiger Threshers outside of the Tiger Thresher nest cave constantly swimming into the wall in the general direction of the nest, as if they were trying to get back to the nest location. These creatures were not part of any random encounter and only spawned once our dive team got close enough to the eggs. The dive team did not encounter any Tiger Threshers inside the nest as a result of this issue.

![image](https://user-images.githubusercontent.com/105495756/215238371-3a1c1916-0e66-4d97-8c52-64daaedcbf7e.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro, closing
