### ISSUE TITLE
[Factions] Potential backwards compatibility issue with unrefined genetic material 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11059]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.17.0.0
Server type: Steam P2P
### Issue Report
Using a save started in 100.13.0.0 which had genetic materials, we were met with the following error messages in the console:

![image](https://user-images.githubusercontent.com/105495756/215239830-8b2b83e2-3a53-4af5-86d4-9a5992888506.png)

The error did not cause any crashes or problems during gameplay to my knowledge. I suspect this is due to the changes to how Unrefined Genetic Material is handled. This may be nothing of issue, but I wanted to report it anyway just in case this causes additional problems.

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/47d66a69b4490c7e16dd6b803e8d51d535cedfd2 by making the game replace old creature-specific unidentified materials with the new unidentified material (which can turn into any creature-specific material).

**Comment by juanjp600** [comment]
I created a submarine on revision Regalis11/Barotrauma-development@c4ce99517f1, with the following items:
![image](https://user-images.githubusercontent.com/8607119/215854680-c403594b-9376-4c9e-b439-42384c6d0aa7.png)

Switched to revision Regalis11/Barotrauma-development@0530a4a6096, opened the previous submarine, saved it again, got this:
![image](https://user-images.githubusercontent.com/8607119/215855858-1d5e3339-5e91-4aac-845b-79cd7e1acc85.png)

This appears to be working correctly.
