### ISSUE TITLE
Watcher's Gaze effects the Petraptor

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11050]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Watcher's Gaze effects the Petraptor. I'm unsure if the positive effects are applied to the Petraptor, but the mask certainly is. Whilst it makes sense for the Watcher's Gaze to effect the Petraptor given that it effects Mudraptors, it doesn't necessarily make sense for the enemy's buff to positively influence a friendly creature. 

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not an issue imo
