### ISSUE TITLE
[Factions] Zealot Robes hood overlaps diving suit

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11058]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/105495756/215239746-07694c7b-3d93-4f80-a679-6d433074ae0c.png)
![image](https://user-images.githubusercontent.com/105495756/215239750-43a169c6-b69a-4ab2-bf9d-4553c77407c9.png)
![image](https://user-images.githubusercontent.com/105495756/215239754-cc4ee369-9e37-4ae9-b7ac-b77cc59752ed.png)
![image](https://user-images.githubusercontent.com/105495756/215239757-38c23fb3-c361-4dac-a43e-9bf984c2a7c0.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/836bc607cb9279d0dab926235a7035ba288f2dd2

**Comment by 3e849f2e5c** [comment]
Tested, could not spot any more visual issues
