### ISSUE TITLE
[Factions] Reputation reward goes to Location (+2)

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11066]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.17.0.0
Server type: Steam P2P
### Issue Report
Completing a hunting grounds mission in a natural formation gives the reputation bonus to "Location". 

![image](https://user-images.githubusercontent.com/105495756/215241760-9f9e2f52-db4b-4a29-9cfa-8bb5a8c15726.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8c850aff1d9a8374eddbf1133b0b78d1cbab6d8

**Comment by NilanthAnimosus** [comment]
Tested against Fix/WIP-fixes-jan28 commit https://github.com/Regalis11/Barotrauma-development/commit/97e99c225a92460269a4fc0937de649b36f450cb, no issues found, closing.
