### ISSUE TITLE
Status monitor doesn't show all relevant items in electrical menu

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11067]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There are two types of machine that the Status Monitor does not report on despite them being able to be damaged. These are:
1) The Research Table (for genetic materials, found on the Winterhalter)
2) Weapon Loaders

The image below shows the Winterhalter's Research Table being hidden from the Status Monitor.

![image](https://user-images.githubusercontent.com/105495756/215241870-ee014a2f-05a6-4333-80ad-a0081c7bc9a1.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/002545560b21b8ef6578f5c894477509d23107e1

**Comment by 3e849f2e5c** [comment]
Tested, icons show up properly now
