### ISSUE TITLE
[Factions] Molotov Cocktail can be accidentally lit when trying to unequip it

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11065]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unequipping the Molotov Cocktail using the left mouse button on the small bar above items in the inventory causes the Molotov to light itself. This is problematic as players who do not want to use the Molotov can accidentally use the Molotov when their intentions were to unequip the item.

### Reproduction steps

1. Equip a Molotov Cocktail
2. Click the small bar above the Molotov Cocktail with your mouse to unequip the Molotov
3. Observe how the Molotov lights itself before entering your inventory

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a1e2aa2ad19a3afd7f99b7ac15982deab315427

**Comment by JeroonBosch** [comment]
Doesn't seem to occur anymore after the fix, closing
