### ISSUE TITLE
[Factions] husk symbiosis causing ai to become totally useless in cases of flooding

### ISSUE THREAD

**Issue by Traumatic-apricot** [Regalis11/Barotrauma#11060]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

after you have worked with the church of the husk and you have reached husk symbiosis with your crew if your ship floods they will ignore all tasks and assignments to swim together they will chose a spot and swim around in a circle (single player)
assume this has something to do with them looking for diving suits but getting told they don't need them
image 1:you see they are not actively fixing leaks getting on guns or other tasks that are assigned just swimming
![20230128130227_1](https://user-images.githubusercontent.com/123396519/215239573-4a470c3a-924f-47d6-b22b-01d214fd4d51.jpg)
image 2: i had some crawler come aboard and even when caught in my shotgun cross fire they just kept swimming
 (brit was the ai shot if you look in chat and still nothing)
![20230128130330_1](https://user-images.githubusercontent.com/123396519/215239676-295189e0-6673-43ec-a8cb-71211c4976de.jpg)
save file:[test build save.zip](https://github.com/Regalis11/Barotrauma/files/10524831/test.build.save.zip)
note my perks are a bit messed up from going from v100.16.0.0 to 100.17.0.0 but i have been experiencing this since 100.16.0.0 so that is unrelated

### Reproduction steps

1. use mine or start your own campaign 
2. if you started your own give your AI the husk symbiote not the infection no clue if the infection also causes the issue and make sure they have tasks to help around the ship
3. go get sunk my some monsters and if your ship floods you should see that all the ai once its flooded enough will stop doing anything

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by Regalis11** [comment]
Seems like the same issue as https://github.com/Regalis11/Barotrauma/issues/9970. We've implemented a fix for this but it isn't available in the public builds yet: we need to verify it fixes the issue with husk symbiosis as well.

**Comment by Regalis11** [comment]
Tested, it seems that the fix implemented for https://github.com/Regalis11/Barotrauma/issues/9970 took care of this one as well.
