### ISSUE TITLE
Local active voice icon changes to radio icon at the end of conversations

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11068]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Players using local chat will have their white icons flash yellow once the push-to-talk button is released. This does  **not** appear on the client's end for their own chat icons, only for others they can see.

https://user-images.githubusercontent.com/105495756/215242123-1c956f4b-d530-4c4e-97ff-e8f819d312dc.mp4

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I don't understand what's the issue. Maybe it's obvious when tested, but can you clarify what exactly is the issue? The client doesn't see the icon when he's talking? Could be intentional?

**Comment by Wheatley1001** [comment]
When a player uses a push to talk key whilst using the local chat, it flashes the radio chat icon once they release the key. This gives the impression that the player was speaking in local chat, then changed to the radio chat at the end without any player input on their end. This does not show up for the player speaking; the icons work as intended for that. It seems to only apply to other players who speak.

For evidence of this issue, the video demonstrates it. The perspective is taken from a spectator who observes two players communicating using local chat. Neither player switches to the radio chat at all. Despite this, at the end of their communications, the active voice icon flashes yellow which indicates they're using radio chat.

**Comment by Rokvach** [comment]
Yeah this is something we should try fixing, no need further testing as this has always happened when using local voip.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e0e3415bf7d32697d7702b93280a1179d7bcc590

**Comment by Jasontti** [comment]
Tested. Voicechat icon works correctly in local and radio mode.
