### ISSUE TITLE
[Factions] Molotov Cocktail doesn't disappear at 0% condition if thrown

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11064]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Like many throwables in the game, the Molotov Cocktail can reach 0% condition. This can be achieved by lighting the Molotov and jumping in the ballast tank. Over time, the condition will reach 0%. If the Molotov is then thrown, it doesn't break and can be thrown continuously. This doesn't make sense for a glass bottle to not break upon impact. 

![image](https://user-images.githubusercontent.com/105495756/215241533-c0b5e9ea-9245-4c47-8e3e-b3e81bea32b8.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a1e2aa2ad19a3afd7f99b7ac15982deab315427

**Comment by JeroonBosch** [comment]
No longer an issue now that they don't reach 0% condition after the fix

**Comment by Regalis11** [comment]
Reopened because now that https://github.com/regalis11/barotrauma/issues/11134 has been fixed, we can fix this "properly" instead of working around the issue by making the molotov light up when thrown. 

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/41420145171f502851f1fdaee2f7c1c875d126a2

**Comment by JeroonBosch** [comment]
No issues found here. Balance should be adjusted, but it behaves correctly at 0% so closing this
