### ISSUE TITLE
[Factions] You can interact with hostile outposts as if they were friendly

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11062]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.17.0.0
Server type: Steam P2P
### Issue Report
I will be covering two different issues in this report. As such, I will split it up into two different sections.

**Mission Gathering**
You can still collect missions from -100 reputation outposts and complete them for profit. If you kill or slip past the outpost security and make it to the Watchman, you can talk to them and take their missions. Of course, they will run away from you eventually, but that's irrelevant. They still give you missions and talk to you as if they're a friendly outpost. 

![image](https://user-images.githubusercontent.com/105495756/215240522-261bdc35-8405-44e1-8856-e26c5ded2842.png)
_Figure 1. Hostile Coalition outpost providing missions, money, and reputation rewards._

________________________________________________________________________________________________________________________________________
**Purchasing Submarines**
You can purchase and switch submarines with a faction that has -100 reputation with you. Considering these outposts attempt to shoot you on sight, it makes no sense for them to willingly sell you a submarine and keep hold of your old submarine whilst also transferring the items from your old submarine to the new one.

![image](https://user-images.githubusercontent.com/105495756/215240577-a43307f2-12d8-445b-9b07-7dc8a3250de5.png)
_Figure 2. Current faction reputation shown on the campaign map._

![image](https://user-images.githubusercontent.com/105495756/215240579-0ce13007-a5d1-4de5-9bcb-549e7fea9295.png)
_Figure 3. Started submarine transfer vote._

![image](https://user-images.githubusercontent.com/105495756/215240606-fd74978e-b40c-4306-b0e3-1459fbac0a83.png)
_Figure 4. Successful transfer vote._

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Hmm, this is kind of a tricky one. I think it might be a good thing you're able to interact with the NPCs: otherwise it could be possible to get stuck with a negative reputation, with no way to unlock missions and get it back up. But this does feel a little buggy, so I think we need to consider some alternative ways to handle it.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/988231a18104080aeaf6bf44e7dc999b2258c0d7

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
