### ISSUE TITLE
Translation errors (russian)

### ISSUE THREAD

**Issue by Randy624** [Regalis11/Barotrauma#11074]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Incorrect translations in this RussianVanila.xml:

Wrong(current):
<talentdescription.slightlypowerfulcpr>Проведение реанимации члену экипажа устраняет ‖color:gui.orange‖нехватку кислорода‖end‖ на [amount]% эффективнее.</talentdescription.slightlypowerfulcpr>
Right:
<talentdescription.slightlypowerfulcpr>Проведение реанимации членами экипажа устраняет ‖color:gui.orange‖нехватку кислорода‖end‖ на [amount]% эффективнее.</talentdescription.slightlypowerfulcpr>

Wrong:
<serversettingslockalldefaultwires>Блокировать все стандартные линии</serversettingslockalldefaultwires>
Right:
<serversettingslockalldefaultwires>Блокировать штатную проводку</serversettingslockalldefaultwires>

Wrong:
<roomname.junctioncompartment>Соединительный отсек</roomname.junctioncompartment>
Right:
<roomname.junctioncompartment>Электрощитовая</roomname.junctioncompartment>

Wrong:
<roomname.cargo>Трюм</roomname.cargo>
Right:
<roomname.cargo>Грузовой отсек</roomname.cargo>

talentdescription.aggressiveengineering - using 2 times
Wrong:
<talentdescription.aggressiveengineering>Используя при атаке гаечный ключ, вы с вероятностью [probability]% получаете +[powerincrease]% к силе атаки и возможность оглушения.</talentdescription.aggressiveengineering>
Right:
<talentdescription.aggressiveengineering>Вы наносите ‖color:gui.green‖втрое‖end‖ больше урона ‖color:gui.orange‖отвертками‖end‖.</talentdescription.aggressiveengineering>

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment]
Why would you translate "standart" as "штатная' in <serversettingslockalldefaultwires>Блокировать все стандартные линии</serversettingslockalldefaultwires> if it can be translated literally as "стандартная"? This just makes things confusing. Then, we already have roomname.electrical which is "Электрика", why would you need a second one? Finally, term "Трюм" is used to translate roomname.cargo because it is a ship term and Barotrauma is all about that, only on hostile alien planet.

**Comment by Randy624** [comment]
1. You can say "Блокировать стандартные провода" too. But "штатная"(pre-installed) is a better word here. The mistake here is in the word "линии" (lines). This is not about "lines".
2. This is not the second one. "Электрощитотовая" (literally "junction boxes room") - is the most correct translate here (imho). Электрика (electrical) - is a broader concept. It's not the same. 
"Соединительный отсек" (Connection compartment) - it's not about wires. Is this supposed to be a room for connecting people maybe? :)
You can look "Электрощитотовая" in Google Images, or wikipedia:
https://ru.wikipedia.org/wiki/%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D1%89%D0%B8%D1%82%D0%BE%D0%B2%D0%B0%D1%8F
3. The problem that you use "Трюм" two times.
<roomname.bilge>Трюм</roomname.bilge>
<roomname.cargo>Трюм</roomname.cargo>
For cargo more correct translate is - "Грузовой отсек" (literally "cargo compartment")

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1b693f90443ceabd3d9f84d2cc2bb885ac7cdeff (coming up in the next update)
