### ISSUE TITLE
Transparent Line of Sight seems to not work anymore?

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#11073]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to enable the transparent line of sight effect in options.
![image](https://user-images.githubusercontent.com/69410159/215259527-f0cccdf7-0cff-49b2-9bbf-b05907e671b5.png)

It should look like this: 
https://user-images.githubusercontent.com/69410159/215259638-fcbe8a8a-ec28-4c76-88f6-9c212c555a40.mp4

But it behaves like regular opaque line of sight instead.

### Reproduction steps

1. Go into options.
2. Enable transparent under line of sight.
3. Start up campaign.
4. Try changing line of sight settings and restart to confirm opaque and "none" work.

### Bug prevalence

Happens every time I play

### Version

0.21.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Couldn't spot any issues with the transparent setting. It is darker now (set to the ambient light of the level), but not opaque.
