### ISSUE TITLE
Makeshift Helmet clips out of pucs

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11077]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When having a makeshift helmet on, and wearing the pucs suit, for example, the top of the helmet will clip over whatever is hiding hats and leave a tiny floating piece of it above your head, comedically. 

### Reproduction steps

1.Equip a pucs suit
2.Equip a makeshift helmet
3.Notice the floating piece of helmet above your head 

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Reopened https://github.com/Regalis11/Barotrauma/issues/10572, closing this one
