### ISSUE TITLE
Sprite depth in labels and text displays doesn't work properly (bug)

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#1107]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the sprite depth of a label is changed its text goes behind the label.
Note that the sprite depth does work for the label and it goes in front of objects as it should, it's just that the text stays at the original depth and is no longer readable.

(Same goes for Text Displays)

**Steps To Reproduce**
Change the sprite depth of the label/text display to be lower than ~0.85.

**Version**
- 0.8.9.3 (Steam)
- Windows 7

**Image**
![image](https://user-images.githubusercontent.com/15182031/52535227-ffdd4880-2d4b-11e9-84d6-b72c65028388.png)

**Comment by BillCombs** [comment]
Just want to ask for the fix not to affect possibility of hiding the labels/text displays behind objects while showing the text in front of them(For example, if the fix would make the text's depth same as depth of the labels, that option would be gone). I am currently using it for nav terminals, and it looks awesome, at least in my opinion. Really don't want to lose that.
![-2019-feb-10-002](https://user-images.githubusercontent.com/38168249/52535580-ae9c7b80-2d82-11e9-97cf-90eb41d1ef83.jpg)
Perhaps depth settings of the label and its text could be separate? Not sure how hard that would be to implement.

**Comment by Regalis11** [comment]
@BillCombs I believe you could get the same effect by changing the spritecolor of the labels to transparent.
