### ISSUE TITLE
No way to differentiate between "Small Planter Box" and "Small Planter Box" when wanting to spawn the item in.

### ISSUE THREAD

**Issue by DuckY-Y** [Regalis11/Barotrauma#11079]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unable to spawn the item "small planter box" with the console command, inventory nor cursor works. It only lets me spawn the uninteractable one with cursor, the most useless thing to spawn. the planter box that's actually useful is not spawnable with the console.

### Reproduction steps

`spawnitem "Small Planter Box" cursor / inventory`

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
You can spawn the item using it's identifier (`smallplanter`) instead of the name.
