### ISSUE TITLE
Exosuit incorrectly beeps the alarm 

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11076]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems that, when having an empty/low condition item that is used for the exosuit (battery/oxygen tank) in the exosuit inventory not equipment slots, it will incorrectly beep, as if it is currently being used and not just stown away inside the suit. 

### Reproduction steps

1.Have an oxgen tank/battery with low condition and put it inside the exosuit
2.Make sure its simply placed in the inventory, seperately of the oxygen tank/battery that is currently being used
3.Note that the suit will beep regardless, as if the empts item is being used

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Reopened https://github.com/Regalis11/Barotrauma/issues/11004, closing this one
