### ISSUE TITLE
[Factions: SPOILERS] Issues related to the end

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11080]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Forgive the vague title and lumped ticket, I don't want to spoil the stuff related to the end. Here are the issues related to the ending:
### The final boss has no resistances and as such is far too weak, whilst also not posing a threat to the crew
The Cyborg Worm which intercepts the submarine crew was a tougher boss fight compared to Jove. Including transit times from the final pylon to Jove on top of the boss fight time, it took roughly 2-3 minutes to finish. We only used the Flak Cannon (explosive ammo) and Pulse Laser (Tri-Laser) on the Winterhalter (top right for Flak Cannon, top left for Pulse Laser). The submarine physically rammed Jove during the fight, which didn't cause issues for the crew or submarine. 

The general consensus from the crew is that the fight needs to be improved. The current fight is anti-climactic and far too short. Of course, this is more discussion territory (#11082), so I'm reserving this section for the lack of resistances. 

### Wrecked Status Monitor shows entire map layout
On one of the wrecks in the second "stage" of the ending, the wrecked status monitor shows the layout of the entire ruin. 

![image](https://user-images.githubusercontent.com/105495756/215291052-6e2f5f39-bca3-416c-9ea8-3d2b73696950.png)

### Layering Issues

Part of the Alien Ruin has layering conflicts which cause these two items to fight for layering priority.
![image](https://user-images.githubusercontent.com/105495756/215290989-861bcdbc-1455-4abc-907e-5370959c0a94.png)
![image](https://user-images.githubusercontent.com/105495756/215290992-5ecbaf56-c185-42a2-b4fb-c8d36c6abfcb.png)

### The Cyborg Worm clips into the submarine easily
Upon killing the Cyborg Worm, it folded in on itself and started clipping through the submarine. This caused the submarine to shake violently whilst also presenting weird visual bugs (shown below).
![image](https://user-images.githubusercontent.com/105495756/215291009-112e2661-895f-4493-a1ea-f12eb5166895.png)
![image](https://user-images.githubusercontent.com/105495756/215291011-230cf8db-b832-4811-8307-047c399acb04.png)
![image](https://user-images.githubusercontent.com/105495756/215291016-1e0bfe35-bf1a-4698-83fc-fca072c9eeb8.png)
![image](https://user-images.githubusercontent.com/105495756/215291022-e0147441-2bcb-41f4-8f18-10540a7aec69.png)
![image](https://user-images.githubusercontent.com/105495756/215291024-43befe6f-c28c-4ba0-9be3-84d57260fa4a.png)
![image](https://user-images.githubusercontent.com/105495756/215291027-ce2dd937-d2c0-410e-9163-50d8ad81aa1c.png)
![image](https://user-images.githubusercontent.com/105495756/215291030-48f3118b-4359-4699-9503-f7f0f00dd3be.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Lithosagym** [comment]
Is this planned

**Comment by Rehexr** [comment]
Opened as planned

**Comment by soledad630** [comment]
Maybe it's planned.

**Comment by Fentanyl1984** [comment]
this can be planned

**Comment by Regalis11** [comment]
Addressed the issue with thee status monitors in https://github.com/Regalis11/Barotrauma-development/commit/487e7b7a5b40157c2e77b09e7b63e6d50ed45506.

I couldn't find those spots with the layering issues anywhere in the levels. Can you give any more info on where exactly those spots are? Were they in the 2nd level too? Near any points of interests?

> Is this planned

I've wondered why the option that means "won't fix, can't repro, duplicate" as opposed to "this issue is now fixed" is called "not planned" on GitHub.

**Comment by Wheatley1001** [comment]
> Can you give any more info on where exactly those spots are? Were they in the 2nd level too? Near any points of interests?

This layering issue was found at the first ending stage iirc. It was from the very first structure players come across after talking with the Beacon Station Scientist whose name I cannot spell. I can hop into the sub editor and try to pull up the exact location and edit it into this comment.

**Comment by Regalis11** [comment]
Another layering issue in the final level:
![image](https://user-images.githubusercontent.com/14351070/215782234-22664796-2a3b-4a93-a935-5c53c7d4ece8.png)

**Comment by Regalis11** [comment]
Remaining issues should be addressed in https://github.com/Regalis11/Barotrauma-development/commit/b66d6c4db90988a720ae5f5cfc1662ea492dfc0e and https://github.com/Regalis11/Barotrauma-development/commit/b79146a8d69b12f79fd1025a3d594ffac562a677

**Comment by JeroonBosch** [comment]
Checked the solved issues and found no problems anymore:
- Layering issues / z-fighting in Entrance level
- Wrecked status monitors showing the entire level
- Being able to pass the 'central coils' in final level

Other issues should probably get separate tickets
