### ISSUE TITLE
Make the fact that the chat window has been selected more obvious.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#1108]
I tend to wind up in a lot of situations where my character abruptly stops responding to my keyboard input, only to realize that I somehow enabled typing in chat while performing some other action.

Regardless of why I keep accidentally hitting the key, there should be a visual and/or audio cue that occurs when the chat box is opened. Maybe the chat window should flash a bright yellow?

**Comment by rico6822** [comment]
The entire lower screen would shine in green by a short range from it until chat is left.
