### ISSUE TITLE
Pulse laser turret arc misaligned

### ISSUE THREAD

**Issue by Anarengon** [Regalis11/Barotrauma#11087]
The pulse laser's turret arc is a little too far up, and a little too far to the left, as compared to the coilgun and chaingun's turret arcs, which are both perfectly aligned and stay aligned when you mirror x. 

If you x mirror the pulse laser, it then is a little too far to the right. 

Easily visible if you simply align the turrets together

![image](https://user-images.githubusercontent.com/97921339/215310354-2d160fb1-9748-4dcd-b055-068b6ea38744.png)

edit: while I have your attention, a half-related issue: a turret hardpoint's turret arc is nowhere near the arc of the turret a player would subsequently install. 

For someone creating a submarine, you should change the turret hardpoint so that the centerpoint of it's visible turret arc is offset to be at the same point of an actual turret. Otherwise an editor can't correctly set a turret arc. 
![image](https://user-images.githubusercontent.com/97921339/215311759-0d6ad510-3541-4a55-9692-62dd66db5ea4.png)

edit: the flak/double coil/rail have a similar issue to the pulse laser, but with the railgun being the odd one out. what's also somewhat strange is that all 3 are offset from center: they all change the centerpoint when flipped over the x. also the large turret hardpoint's turret arc is misaligned horizontally (obviously vertically as well) from all 3 large turrets.

**Comment by JeroonBosch** [comment]
Mirroring X seemed fine now, closing

**Comment by Anarengon** [comment]
> Mirroring X seemed fine now, closing

Have you also considered aligning the arc on the turret base items, so that sub editors can use them?

**Comment by Regalis11** [comment]
Yep, we also adjusted the barrel positions of the hardpoints to match the turrets.
