### ISSUE TITLE
[Factions] Husk event only removes one type of husk eggs from inventory

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11083]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The event Way to Ascension 2 accepts both Velonaceps Calyx Eggs and Calyx Extract to progress the event but only takes away Calyx Extract from the players inventory.
![image](https://user-images.githubusercontent.com/115734437/215295886-92cbbbb6-a468-417a-be92-7db0669a84db.png)
![image](https://user-images.githubusercontent.com/115734437/215295896-a36786ea-1b1c-4874-b1da-107d543c369a.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/83a4f1fd827b40982582f35275e122585bfb7d2c

**Comment by JeroonBosch** [comment]
Tested with mix of huskeggs and huskeggsbasic, no problems found, closing
