### ISSUE TITLE
Tinkerer's 140% condition doesn't show on status monitor until next round

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11092]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.17.0.0
Server type: Steam P2P

### Issue Report
Fixing a device to 140% condition during a round will not reflect this on the status monitor until the round ends. I suspect this is a networking related issue.

![image](https://user-images.githubusercontent.com/105495756/215355629-3c0ab38d-e909-4b87-808f-5f00952fc302.png)
_Figure 1. Image showing Engine condition once repaired to 140% condition._

![image](https://user-images.githubusercontent.com/105495756/215355641-c3ecf0c2-9eee-4685-abbf-b581df813406.png)
_Figure 2. Image showing Engine condition once the round ends._

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb5c512120129b55d8b079c5279c72a45d0c1200

**Comment by Regalis11** [comment]
Tested, no issues found. Closing.
