### ISSUE TITLE
R-29 wiring components issues

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#11098]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The components related to the batteries, water detectors, even some wires can not be detached or disconnected. Water detector values can not be edited.

I have identified some wires that are marked "Hidden In Game".

These issues limit the extent of possible improvements that can be done on the R-29.
This is highly unusual and makes the R-29 a less desirable ship as a result.

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
This is how the submarine was designed by rav2n, so I don't think we'll be changing it.

I would also argue non-detachable and non-editable components can be a desirable feature in a sub. Not for someone who likes doing changes to the circuits in the sub, but for those who don't want anyone to touch or edit these systems.

**Comment by mygamingaccount** [comment]
All systems on every sub can be upgraded freely, with the R29 being the only exception.

The Barotramua server already has the option to limit this feature for those who have no ambition to fix the stock wiring of submarines.
