### ISSUE TITLE
Machines smoking above 100% condition 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11094]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you repair an engine with the Tinkerer talent to 140% condition, it starts smoking at around 110% (80% of 140)

![image](https://user-images.githubusercontent.com/73229309/215360002-070ea34f-06a1-4c1b-af95-ab1212c5f033.png)

```xml
      <ParticleEmitter particle="DarkSmoke" particleburstamount="3" particleburstinterval="0.5" particlespersecond="8" scalemin="1.8" scalemax="2.5" anglemin="0" anglemax="359" velocitymin="-50" velocitymax="50" mincondition="0.0" maxcondition="80.0" />
```

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c91e719925cccd7e3bcd826fd5adaa1319f5a12

**Comment by Regalis11** [comment]
Tested, no issues found. Closing.
