### ISSUE TITLE
Junction Box light shines through Guitar

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11093]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the guitar is held in front of the Junction Box light component, the light mask shines on top of the guitar.

![image](https://user-images.githubusercontent.com/105495756/215355761-d5130604-4b46-475f-8804-e7c5355ca38f.png)
![image](https://user-images.githubusercontent.com/105495756/215355765-9cd30979-18fe-443a-aa42-8c1518866728.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Applies to all items. I don't think we'll be addressing this though.
