### ISSUE TITLE
[Factions] Captain able to unlock every generic talent using one talent point, unable to progress specialist tree

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11095]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.17.0.0
Server type: Steam P2P

### Issue Report
Possibly caused by the changes to Affiliation? I'd check the talents that are unlisted but see #10813 for context.

Our Captain was absent for two sessions. They last played in 100.15.0.0 and then rejoined in 100.17.0.0. Upon rejoining and gaining a talent point, they were unable to continue unlocking talents from the Gunslinger tree as the tier 2 talents from the Politician tree had become unselected. Instead, the Captain was able to use one talent point to unlock every single generic talent.

![image](https://user-images.githubusercontent.com/105495756/215355611-7d585ced-0b31-446f-baec-d65d4ab6c2cd.png)
_Figure 1. Captain's talent menu before unlocking any new talents._

![image](https://user-images.githubusercontent.com/105495756/215355617-1827d336-9129-47bb-a055-d6e208c3d603.png)
_Figure 2. Captain's talent menu after unlocking all generic talents using one talent point._

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Yeah, it seems the talent missing from the middle of the tree messes up the talent progression. Since this is only concerns saves started in specific test builds, not any of the public ones, I don't think we'll be addressing this.
