### ISSUE TITLE
Quest Wreck logbooks no longer have an interesting story on them

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#11104]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've salvage multiple wrecks after the Holiday Update and in the recent unstable builds, and I've noticed that quest logbooks you get from wrecks no longer display any fun stories. It's a shame, since reading them was interesting and made the tension of salvaging feel worth it.

### Reproduction steps

1. Get a wreck salvage mission
2. Go to the indicated wreck (If it is, yknow, _regular_) and kill the enemies
3. Find the quest logbook, put it in your character's hotbar, and select it
4. Weird opening text saying password or something, but no story

### Bug prevalence

Happens every time I play

### Version

0.21.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional. There are other non-mission-specific logbooks in the wrecks that contain those stories, but the mission logbooks always contain "encrypted information" (which are actually hints for an ARG you presumably haven't found yet ;))
