### ISSUE TITLE
Safety Harness and Toolbelt conflict

### ISSUE THREAD

**Issue by PiatraAlatyr** [Regalis11/Barotrauma#11107]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you wear toolbelt and Safety Harness same time, toolbelt sprite disappear.
This does not happen with body armor, although it occupies the same slot.
![Снимок экрана (2023)](https://user-images.githubusercontent.com/36773134/215802647-e620ddbb-21f2-4a66-ab12-a68864704fe6.png)
![Снимок экрана (2022)](https://user-images.githubusercontent.com/36773134/215802657-9270e67a-0d39-4105-99dc-410ae4b84f9a.png)

### Reproduction steps

1. Spawn as Mechanic class (for example)
2. Wear Safety Harness
3. Watch on your naked belly)))

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a195d5a8b54360dfc2d300e502d96dfe9d517635

**Comment by JeroonBosch** [comment]
No issues found, closing
