### ISSUE TITLE
Junction box texture is glitched

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#11102]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you look at the junction box texture in the current unstable build, there's this weird green/neon texture on top of the part where the "electrical" sticker is located. Here is the normal, older junction box texture from the Barotrauma Wiki: 
![image](https://user-images.githubusercontent.com/81781733/215671084-afe4f383-391d-456f-b093-503c536a1045.png)
And here's the glitched one, with a barely visible electrical sticker:
![Barotrauma 2023-01-30 9_14_19 PM](https://user-images.githubusercontent.com/81781733/215671759-4f1b6f1f-c245-499c-89cc-b545098c095e.png)

### Reproduction steps

1. Look at a junction box texture

### Bug prevalence

Happens every time I play

### Version

0.21.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not a bug, it was the old texture that was glitched https://github.com/Regalis11/Barotrauma/issues/10900

**Comment by Ek-Videogames** [comment]
> Not a bug, it was the old texture that was glitched #10900

Image taken from the ticket in question seems to suggest that it's just the shader issue, also it refers to the junction box with the non-glowing sticker as "cool"
![image](https://user-images.githubusercontent.com/55356135/215871655-a39d534c-5792-48d6-b036-98c4995c98c6.png)

So ultimately up to the art team to decide now that light blending is 'fixed'/tweaked if they want the sticker to have a glow-through or if it should be opaque. Thought I definitely agree the non-lit sticker was good IMO.

**Comment by TheMinerBoy** [comment]
I definitely agree, the old one made more sense.
