### ISSUE TITLE
Gamemode randomization applies between campaign rounds

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11106]
@juanjp600 commented on [Tue Jan 31 2023](https://github.com/Regalis11/Barotrauma-development/issues/3928)

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] I'm using mods.

**Description**
Regalis11/Barotrauma-development#3788 appears to have exposed this bug.

When a round ends, the game looks at the highest voted mode, and if voting is disabled or otherwise no gamemode has been voted for, it falls back to the mode selected in NetLobbyScreen. GameServer.EndGame is called at the end of each round, including campaign rounds, and it calls NetLobbyScreen.RandomizeSettings, which changes the selected mode. Previously, this wasn't an issue, because the game would've just stuck to the currently loaded gamemode, but that's no longer the case.

**Steps To Reproduce**
- Set gamemode selection to Random
- Start or load a campaign
- Leave or enter an outpost

**Version**
v0.21.6.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/76812eb5e936e222d29fc6cce35e7f3b102eb88c

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be merged and closed.
