### ISSUE TITLE
Vitamin supplements wears off before the round ends

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11103]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Vitamin supplements wears off after 60 seconds. It was expected that it should last until the round ends.

The issue is caused by the `duration="60"` in its xml. Probably left over from bedside manner.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c0f286a3787a12c6975ad1d3e3f8a95a20928af

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
