### ISSUE TITLE
Pets don't eat at depth of 5000m or lower.

### ISSUE THREAD

**Issue by satyaFawcett** [Regalis11/Barotrauma#11101]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The pet will not eat pet food, even when owner is not nearby, when under the depth of 5000m. If the ship is later brought above 5000m they will go back to normal eating patterns. I have had 6 or so pets die of starvation because of this. I have found this issue with orange boy, psilotoad, and peanut, never tested on cthulhu. 

### Reproduction steps

1. Hatch pet at 4500m
2. Wait for hunger to show up
3. Take ship to 5500m
4. Put pet food on ground and leave so food takes top priority
5. Come back in a minute and they are still hungry. 

### Bug prevalence

Happens regularly

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9238062a7d969f57affdd7925499cbc37c747d52

**Comment by satyaFawcett** [comment]
Can't reproduce it, will test more to figure out what is cause the issue.

**Comment by NilanthAnimosus** [comment]
Tested against Fix/misc-fixes-jan31 commit https://github.com/Regalis11/Barotrauma-development/commit/5e25c0665733d39397254aa6178ad977a8152a6c, no issues found, closing.
