### ISSUE TITLE
Quickdraw affliction doesn't get removed by Alien Pistol

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11115]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While the Alien Pistol benefits from the damage increase from the talent Quickdraw, the affliction doesn't get removed after firing a shot.
Every subsequent shot has increased damage (10.5*1.25), Ready to Draw affliction remaining active after several shots:
![image](https://user-images.githubusercontent.com/115734437/216030416-eb1844ea-614a-4223-8345-fb8fad8c522b.png)
Most likely caused by the Alien Pistol not having the tag `pistolitem` in its xml

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Tested, damage bonus seems to be applied correctly and the quickdraw buff is being removed
