### ISSUE TITLE
Advanced Syringe Gun has different fabrication materials in-game than defined in the XML

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11116]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar to #11032, Advanced Syringe Gun fabrication materials in the xml and in-game have different amounts:
```
<Fabricate suitablefabricators="fabricator" requiredtime="10" requiresrecipe="true">
      <RequiredSkill identifier="medical" level="50" />
      <RequiredItem identifier="titaniumaluminiumalloy" />
      <RequiredItem identifier="aluminium" />
      <RequiredItem identifier="plastic" amount="2" />
</Fabricate>
```
![image](https://user-images.githubusercontent.com/115734437/216035060-1c52dda0-7c3d-4dfb-bf9f-3609ca68a85d.png)

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment]
Slipsuit materials also don't seem to match:
![image](https://user-images.githubusercontent.com/115734437/216099519-19eacf4c-8180-4169-9203-178c923766ac.png)
Slipsuit in securityofficer_talent_items.xml:
```
<Fabricate suitablefabricators="fabricator" requiredtime="45" requiresrecipe="true">
      <RequiredSkill identifier="mechanical" level="20" />
      <RequiredItem identifier="combatdivingsuit" />
      <RequiredItem identifier="rubber" />
</Fabricate>
```
Combat Diving Suit in divinggear.xml:
```
<Fabricate suitablefabricators="fabricator" requiredtime="45">
      <RequiredSkill identifier="mechanical" level="60" />
      <RequiredItem identifier="divingsuit" />
      <RequiredItem identifier="ballisticfiber" />
      <RequiredItem identifier="titaniumaluminiumalloy" />
      <RequiredItem identifier="rubber" />
</Fabricate>
```

**Comment by JeroonBosch** [comment]
Slipsuit is now free, moving back to Team 1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61b7d85

**Comment by JeroonBosch** [comment]
No issues found, closing
