### ISSUE TITLE
Unable to select to pickup a dropped artifact in the ocean

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1111]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During some gameplay a few days back, I was playing on the server (As server host) and another player got the artifact, they dropped it to check their sonar, but then neither the player nor the host could pick the artifact back up, failing the mission.

**Steps To Reproduce**
It was dropped into terrain similar to the image, but I'm not sure how reproducible it is, the seed is unknown now.

**Version**
Closed alpha 0.8.9.3 - Multiplayer as server host.

**Additional information**
The item could not be selected, and as host it wasn't a syncing issue, but just the inability to select it to pickup, its possible the particular terrain and angle made whatever code used to select objects think it was behind the collision of the terrain.

![test 22](https://user-images.githubusercontent.com/29177976/52538327-4ee5a680-2d69-11e9-899c-08bcacf367e5.png)

**Comment by rico6822** [comment]
This bug occurs randomly however increased lag potentially increases chance for it.

**Comment by Rokvach** [comment]
There's been multiple remedies to prevent this from happening so I doubt this is an issue anymore or on the upcoming patch. Moving to "Done" for further evaluation.
