### ISSUE TITLE
Europan Handshake doesn't apply enough Morbusine Poisoning

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11111]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Europan Handshake still only inflicts 1 Morbusine Poisoning meaning it would take a considerable amount of hits to actually poison a target with the new poison system.
![image](https://user-images.githubusercontent.com/115734437/215854597-ddbec9a4-6e52-4047-b086-68d13411c51e.png)

```
<Affliction identifier="lacerations" strength="10" />
<Affliction identifier="bleeding" strength="10" />
<Affliction identifier="stun" strength="0.2" />
<Affliction identifier="morbusinepoisoning" strength="1" />
```

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/commit/5086461ce83d22b8b6ad63c42253508253188e72, seems to be working nicely with the new values. Closing.
