### ISSUE TITLE
Voice activation doesn't appear to work for wifi components

### ISSUE THREAD

**Issue by chayleaf** [Regalis11/Barotrauma#11119]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/9590981/216107527-f3367c71-b553-4e07-a8a5-6421dd1b0f1d.png)
![image](https://user-images.githubusercontent.com/9590981/216107605-1f3a0f62-c0c5-47f6-8db6-8673482ffd59.png)
![image](https://user-images.githubusercontent.com/9590981/216107684-91d5be41-590f-4b41-aea4-01a318d43462.png)

This successfully reads text chat messages, but not voice chat messages. I also know voice chat works properly as other users can hear me. I learned about this feature from a loading screen tip, but couldn't actually get it to work. I tried both channel 0 and channel 1 to no avail, plus different combinations (speaking in channel 0 and receiving on channel 1 and vice versa).

### Reproduction steps

1. Start a multiplayer campaign game (haven't tested in other modes/in singleplayer)
2. Build the scheme displayed above
3. Try saying something in voice chat on the channel selected in the wifi component

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report!

The wifi components can only receive messages from the text chat. We unfortunately don't have a way for the wifi components to interpret actual voice chat messages, nor do I think implementing something like that is feasible.
