### ISSUE TITLE
Creatures focus and attack decorativs items

### ISSUE THREAD

**Issue by Pol-CHEVILLON** [Regalis11/Barotrauma#11118]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have make a ship with items in extinguisher holder for decoration, and during test, i have when Husk (or other hostil mob) walk around the decorativ extinguisher holder, he start to attack it.
i have find with the "DebugIa" command in the console that the husk focus the item in the extinguisher holder, specificely raffined minerals like copper or lead and not the decorativ thing with weapons or equipment.
Atracted by the item, the mob sometime don't care about the crew
![332fa590-b54f-4ef6-939f-216e1d6d0b46](https://user-images.githubusercontent.com/82041799/216068058-ac81694c-2f52-4a37-a7c9-e96f199f84a5.png)

### Reproduction steps

1. Start Sub Editor
2. Select a random submarine
3. Place a extinguisher holder somewhere and select "no interactible"
4. place a copper or lead item, add in his tag "extinguisher", and place the item in the extinguisher holder inventory
5. Spawn a husk close to the extinguisher holder with the decorativ item
6. The husk, if there is no other real target around it, will focus the copper or lead and attack it

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Pol-CHEVILLON** [comment]
EDIT:
If i delet the tag "Weapon" of the minerals, the creatures will not try to attack them.

**Comment by Regalis11** [comment]
Thank you for the report!

I was just about typing a message saying I couldn't find a way to reproduce this, as the husks didn't seem to be interested in the lead or copper. But the "weapon" tag explains why it happened. 

That isn't actually a bug: husks are configured to attack items that have the "weapon" tag. So it should be possible to fix the issue by leaving that tag out (as it's not needed to be able to place the item in the extinguisher bracket), or by making the mineral non-interactable.

**Comment by Pol-CHEVILLON** [comment]
Ho okey i see!
thanks a lot for your efficiency, and have a great day!
