### ISSUE TITLE
Miracle Worker negates kill command

### ISSUE THREAD

**Issue by DuckY-Y** [Regalis11/Barotrauma#11110]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

using `kill [character]` will only induce 1200% internal damage like it's coded to do.
However this means that having Miracle Worker in the vicinity of 6m will negate it and keep the affected character alive.
![image](https://user-images.githubusercontent.com/84920066/215831316-08a977f2-a15e-4bea-aebc-405c10b229d0.png)

### Reproduction steps

use `kill` on a character on the same team as the one with miracle worker.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3859ddedc3b44a8a950e538e7e955f0a3a7e393c

**Comment by NilanthAnimosus** [comment]
Tested against Fix/misc-fixes-jan31 commit https://github.com/Regalis11/Barotrauma-development/commit/97e99c225a92460269a4fc0937de649b36f450cb, no issues found, closing.

**Comment by Regalis11** [comment]
2nd attempt, looks like I missed the server-side implementation of this command https://github.com/Regalis11/Barotrauma-development/commit/8b40b37331130541c889aa339a8c79e123153eed

**Comment by 3e849f2e5c** [comment]
Tested, didn't notice any new oddities in multiplayer or singleplayer
