### ISSUE TITLE
[Factions] Uninhabited locations don't get marked as visited

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11128]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Uninhabited locations (= locations without an outpost) never get marked as "visited" in either the sp or mp campaign.

Seems to happen because we mark the location selected on the map (= the location you've selected as the next destination) as visited instead of the location you're at. See https://github.com/Regalis11/Barotrauma-development/commit/f8e6d64805cdbcacdd1dc87f3f330aedbd2aa652

### Reproduction steps

1. Travel through an empty location
2. Notice the icon stays white, instead of turning green

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9432931369022a9abbac4b3d66d7fb9b7b2f5e1c

**Comment by NilanthAnimosus** [comment]
Tested against Fix/wip-fixes-january commit https://github.com/Regalis11/Barotrauma-development/commit/a1f14c233cf50eb6f5b632d68103db2483f6f4ab, no issues found, closing.
