### ISSUE TITLE
Picking up active grenades puts them back into a stack

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11129]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Statuseffect on active grenades removes 100 condition after a delay.
`<StatusEffect type="OnSecondaryUse" target="This" Condition="-100.0" delay="3.0" disabledeltatime="true" checkconditionalalways="true" />`
This means if you have several grenades and pick up an active grenade, it goes back into the stack of 8 and you won't be able to throw it back

I changed it to lose condition over time (here 4 seconds) so it cannot be combined into a stack AND the "fuse" is visible:

```xml
    <Throwable slots="Any,RightHand,LeftHand" holdpos="0,0" handle1="0,0" throwforce="3.5" msg="ItemMsgPickUpSelect">
	  <StatusEffect type="OnUse" target="This" IsOn="true" Condition="-25" duration="4" />
      <StatusEffect type="OnSecondaryUse" target="This" IsOn="true" Condition="-25.0" duration="4" />
    </Throwable>
```
![image](https://user-images.githubusercontent.com/73229309/216396116-cbdbf3cd-8c96-44c7-816a-562d784da2a3.png)

------
As a bonus a blinking lighting for spotting the grenades more easily (replaces Itemcomponent with Lightcomponent):

```xml
    <LightComponent characterusable="false" range="50" castshadows="False" drawbehindsubs="False" IsOn="false" blinkfrequency="3" lightcolor="255,0,0,100">
      <!-- statuseffect that explodes the grenade when used by something else than a character (e.g. a detonator) -->
      <StatusEffect type="OnUse" target="This" Condition="-100.0" disabledeltatime="true" />
      <StatusEffect type="OnBroken" target="This">
        <sound file="Content/Items/Weapons/ExplosionMedium1.ogg" range="5000" />
        <sound file="Content/Items/Weapons/ExplosionMedium2.ogg" range="5000" />
        <sound file="Content/Items/Weapons/ExplosionMedium3.ogg" range="5000" />
        <sound file="Content/Items/Weapons/ExplosionDebris1.ogg" range="3500" />
        <sound file="Content/Items/Weapons/ExplosionDebris2.ogg" range="3500" />
        <Explosion range="750.0" ballastfloradamage="100" structuredamage="20" levelwalldamage="140" itemdamage="500" force="5" severlimbsprobability="0.5" decal="explosion" decalsize="0.5">
          <Affliction identifier="explosiondamage" strength="150" />
          <Affliction identifier="bleeding" strength="100" />
          <Affliction identifier="bleeding" strength="50" probability="0.1" dividebylimbcount="false" />
          <Affliction identifier="stun" strength="7" />
        </Explosion>
        <Remove />
      </StatusEffect>
	</LightComponent>
```

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I wouldn't really consider this a bug: don't put primed grenades pack in your pocket with a bunch of non-primed grenades. :) However, I do think [there is an issue that should be addressed here too](https://github.com/Regalis11/Barotrauma/issues/11030): the grenade should go "on top of" the stack and be easily throwable again.

**Comment by ubertpendragon** [comment]
I just thought it was a neat 2-birds-1-stone solution with visual fuse and no stacking
