### ISSUE TITLE
Unlimited Makeshift Shelves / Cargo slots for missions

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11131]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There's no limit on how many Makeshift Shelves you can place on a sub, thus eventually increasing sub cargo capacity by an infinite amount for transport missions (especially on non-transport subs)

![image](https://user-images.githubusercontent.com/73229309/216400499-5717a863-a549-4d82-8c72-43f63d79a7b3.png)

![image](https://user-images.githubusercontent.com/73229309/216401063-a5ff416e-e52a-4f55-9291-2b8c720324ab.png)

Suggest limiting the amount of placeable shelves to 2 (like portable pumps) 

` limitedattachable="true"`

and

`        <CharacterAbilityGivePermanentStat statidentifier="portablepump" stattype="MaxAttachableCount" value="2" />`

### Version

0.21.6.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e92594ae41fc778c68cd0b823c544ce417b37167

**Comment by 3e849f2e5c** [comment]
Tested, works correctly but we should probably mention the 3 shelf limit in the talent ![image.png](https://images.zenhubusercontent.com/5de4d481030f74679f3ed8b7/963fb8a8-9c90-47b7-a5b7-df936812c9fe)

**Comment by JeroonBosch** [comment]
Agreed ^

**Comment by 3e849f2e5c** [comment]
LGTM
