### ISSUE TITLE
Residual Waste works on Unidentified Genetic Material processing

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11130]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The doubling effect of Residual Waste can occur while processing Unidentified Genetic Materials, resulting in two genes.
![image](https://user-images.githubusercontent.com/115734437/216396469-3698c89f-b9da-4187-9b2b-ae42a072e369.png)
The gene is of the same type and same quality (both are Hunter genes at 50% quality):
![image](https://user-images.githubusercontent.com/115734437/216396679-251cb582-43a6-407e-8c82-5d7f93a815f1.png)

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ea4ba806e4238b37ab2f3ee5b22c026d6002e05

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
