### ISSUE TITLE
Dementonite Crowbar spawns in Hemulen respawn shuttle in mission mode

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11138]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Hemulen (and apparently every respawn shuttle though I haven't tested this) spawns a Dementonite Crowbar (as well as a Hardened Crowbar) in its storage if the game is set to mission mode. Considering the Dementonite Crowbar was removed from the game, as it can only be spawned using console commands, it doesn't make sense for it to still spawn in respawn shuttles. The Hardened Crowbar might also be an oversight since it's a talent item.

![image](https://user-images.githubusercontent.com/105495756/216467353-4b5e88f6-52fb-43a9-85e1-75655d926985.png)
_Figure 1. Image showing Dementonite Crowbar, Hardened Crowbar, and Regular Crowbar in storage._

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Dementonite crowbar no longer spawns but hardened crowbar still spawns

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bed1a60e1b50a2590dc42db0189e36bf06379a71

**Comment by 3e849f2e5c** [comment]
Re-tested, only spawns normal crowbars now
