### ISSUE TITLE
Dementonite Tool recipes still show up in the fabricator 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11139]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/105495756/216468920-b465c64d-d4f9-4796-af91-2a6e3f46edf2.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c85f843d76c46e683679c0a39fdfd379fd13ce18

**Comment by JeroonBosch** [comment]
The variantof="divingknife" seems to cause trouble: you can still construct dementonite tools but now it only costs iron.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a3c4482d430e390465a0dfd78aad446a625d546

**Comment by JeroonBosch** [comment]
All good now, closing
