### ISSUE TITLE
"Repair Items" service offered by upgrade sub merchant doesn't work in multiplayer

### ISSUE THREAD

**Issue by Wheatley1002** [Regalis11/Barotrauma#11135]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Fixing broken devices via the upgrade merchant at every outpost currently does not work. If you purchase the service and move to the next location, your submarine will not receive any repairs at the start of the next mission. Upon further testing, I can confirm the service still takes your money. You pay for a service that never comes.

### Reproduction steps

1. Start a multiplayer session in the campaign mode
2. Using the console, enable cheats via the "enablecheats" command
3. Give yourself as much money as you want ("money 999999999 {{PLAYERNAME}}") and as many EMP grenades that will fit your inventory ("spawnitem empgrenade 8", repeated forever)
4. Go through your submarine throwing EMP grenades in every single room
5. Go to the Submarine Upgrade merchant at the outpost and purchase item repairs
6. Using the campaign map, select a new location 
7. Once the round starts, observe your submarine still being completely destroyed due to EMP grenades

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f1d831acd550e293f0df2d9fce2a01b21c7b2476

**Comment by JeroonBosch** [comment]
Tested, now works correctly in MP. Closing
