### ISSUE TITLE
Flares, Alien Flares, and Glowsticks can be accidentally lit when trying to unequip it

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11134]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Basically identical to #11065, but with Flares, Alien Flares, and Glowsticks. 

Whilst testing, I found some weird behaviour specific to the Alien Flare. It seems to glow red when lit and inside a container, yet it emits no light? The Alien Flare produces a stark blue light which is absent as demonstrated in the images below. 

![image](https://user-images.githubusercontent.com/105495756/216437163-011074a6-54d5-4555-92b2-86e24902979f.png)
_Figure 1. Image showing lit Alien Flare inside the inventory of a player._

![image](https://user-images.githubusercontent.com/105495756/216437222-68d8e928-652e-420e-811a-e0049b5e9d3b.png)
_Figure 2. Image showing Alien Flare lit inside of Emergency Cabinet, lights on._

![image](https://user-images.githubusercontent.com/105495756/216437319-68568035-584d-4f26-a00e-d361518b0dc7.png)
_Figure 3. Image showing Alien Flare lit inside of Emergency Cabinet, lights off._

![image](https://user-images.githubusercontent.com/105495756/216437362-7cfb3bc6-4ebb-4d42-80d6-e715b4fcdd60.png)
_Figure 4. Image showing lighting around Emergency Cabinet to prove there is no lighting effect active._

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/29dc1d8e2f32cbfcec33938e70333d515392c4e9

**Comment by JeroonBosch** [comment]
This works as expected now imo, found no issues, closing

**Comment by JeroonBosch** [comment]
Ah woops, accidentally mixed this up with the Molotov ticket, didn't test these items yet.

**Comment by JeroonBosch** [comment]
![image](https://user-images.githubusercontent.com/8641689/216986721-4a09755d-74a7-4321-93a7-29b8518c8821.png)
Could only reproduce this with Alien Flare, moving back to team 1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3c7ba2268d4823a2f3e13be77f63669cb1ed319

**Comment by JeroonBosch** [comment]
Tested Alien Flares, they no longer emit their particles when stored, closing*

PR still has this comment to watch out for though, although I couldn't find any issues with it:

> Note for testing: Use, Select & Shoot inputs are now ignored if
> 
> 1. The key is bind to the primary mouse button
> 2. The cursor is on inventory and the inventory is visible
> This could potentially cause the inputs to not get registered in some situations where we would like them to. I couldn't think of any, but I could be overlooking something.
