### ISSUE TITLE
afflictiondescription.paralysis.low.self is missing punctuation in the EnglishVanilla.xml

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11141]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a really tiny nitpick, but I might as well point it out.

The description for low paralysis (self) lacks a period. Every other description has a period or question mark, so this one is out of place.
![image](https://user-images.githubusercontent.com/37850646/216479683-5119eabc-1d30-4c60-9670-aecada08fc79.png)

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c723dcc638f0d1ac962525dfaa6f55dab8a2bf72
