### ISSUE TITLE
Operate order category isn't highlighted in the campaign tutorial

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#11143]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The operate order category isn't highlighted during the Operate turret objective. 

![image](https://user-images.githubusercontent.com/7299826/216587994-1d22fa76-260c-49de-84df-c09ca90a0a88.png)

### Reproduction steps

1. Start singleplayer campaign with campaign tutorial enabled
2. Do starting objectives and leave outpost
3. During level transition follow the objectives and notice that the Operate category isn't highlighted

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b64ee617b17369eb1e2152469c8f7d8cc1e176f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
