### ISSUE TITLE
Mudraptors no longer play their ambient sound when they are close

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#11142]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was attacked multiple times by mudraptors in the first and third biome. They never made ambient noises even when they got into the sub. They used to make growling noises, which you could hear if they were right outside the hull (Like all the other creatures' ambient noises).

### Reproduction steps

1. Start a mission/ campaign round
2. Get attacked by mudraptors
3. No ambient sound

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I can't repro this. The sounds seem to work ok. Note that like with many monsters, the attack sounds don't necessarily play when the creature attacks. They play randomly with some delay when the creature is in the attack state. Do the sounds work differently for example on crawlers?

Also, could you please open the console with "F3", type "debudraw", close the console, and then press ctrl+s to see the sound debug info. Can you spot lines with MUDRAPTOR_attack? ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/5d2e593d-794e-4905-ad47-012d927912ac)

(protip: "enablecheats" -> "spawn mudraptor cursor")

**Comment by TheMinerBoy** [comment]
Yeah, no "MUDRAPTOR_attack".

**Comment by TheMinerBoy** [comment]
I could've sworn that monsters hordes that attacked you ship made some kind of ambient roaring noise when they aggroed.

**Comment by Wheatley1002** [comment]
I have noticed some weird audio-related issues recently, specifically the sounds of Pulse Lasers or Coilguns firing not being played at all. Typically this happens during crisis scenarios. It didn't happen often enough for me to justify a ticket and I also couldn't figure out repro steps. Could these be related?

**Comment by Regalis11** [comment]
> I have noticed some weird audio-related issues recently, specifically the sounds of Pulse Lasers or Coilguns firing not being played at all

There are some limits on how many sounds can be played at a time: 32 sounds in total, and 5 instances of the same sound clip. To me it seems like this could be caused by the former, but hard to say for sure. If you run into this, enabling that debug view itchyOwl mentioned above might give some more clues on what's causing this.
