### ISSUE TITLE
[Factions] Some old events which still have old reputation values

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11144]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mediator seems to still have a -10 Coalition rep alongside the -2 Location rep in the failed Helm skill check outcome. This seems to be a leftover when compared to the other possible outcomes which had their Coalition rep changes removed.

Explosive Mishap can occur on military outposts and colonies, but is not limited to either Coalition or Separatists. Surrendering the weapon to the authorities has +3 Coalition rep which imo wouldn't make much sense if it occurred on a Separatist controlled outpost/colony.
![image](https://user-images.githubusercontent.com/115734437/216600772-cedc1cb6-7876-42fd-9af5-15a6e2eaea31.png)
![image](https://user-images.githubusercontent.com/115734437/216600818-8dc9818d-7bb3-4fa1-bb76-dfeeb7f71570.png)
![image](https://user-images.githubusercontent.com/115734437/216600866-149416dc-5b83-4c6c-bdc0-23213d54ba96.png)

Similar to Explosive Mishap, Clown Relations 1 can occur on Separatist controlled outposts/colonies. Honking the horn has -5 Coalition rep which imo also doesn't make much sense if the outpost was under Separatist control.
![image](https://user-images.githubusercontent.com/115734437/216614661-af652f2e-74ee-4597-bebe-6d6d5d80306c.png)
![image](https://user-images.githubusercontent.com/115734437/216614718-7bfe5241-a84c-46a9-8e57-a82c078a0a8f.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a663e0dd42d4ec6bcce6d77483eab6af15749056

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a663e0dd42d4ec6bcce6d77483eab6af15749056

**Comment by JeroonBosch** [comment]
> Fixed in [Regalis11/Barotrauma-development@a663e0d](https://github.com/Regalis11/Barotrauma-development/commit/a663e0dd42d4ec6bcce6d77483eab6af15749056)

wrong reference, but I see it's fixed in [62712ec](https://github.com/Regalis11/Barotrauma-development/commit/62712ecc2025350d60ee63abd76fc624facb5eb4) :D

**Comment by JeroonBosch** [comment]
Closed, no issues found
