### ISSUE TITLE
Supercapacitor and Junction Box overlays still appear when lighting is disabled.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#11149]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**What happened:**
The lighting overlays for Junction Boxes and Supercapacitors are always visible in the Submarine Editor, even when lighting is turned off in the visibility menu.

**What I expected to happen:**
The lighting overlays should instead not be visible when lighting is disabled.

**Image of the issue:**
Problem areas are outlined in red.
![image](https://user-images.githubusercontent.com/67431770/216732257-47f3214c-39de-441b-8bd9-20190c6e494d.png)

**Notes:**
The overlays do not appear if the item's lights are turned off by default.

### Reproduction steps

**Submarine Editor:**
1. Open the Submarine Editor.
2. Load any submarine.

**In-game:**
1. Quickstart with any submarine.
2. Enter the commands `power` and `lights`.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not a bug, caused by the fix to address https://github.com/Regalis11/Barotrauma/issues/10900
