### ISSUE TITLE
Modded afflictions with "paralysis" type don't have the expected paralysis functionality

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#11147]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Prior to the 1.0 pre-patch, modded afflictions with the type "paralysis" were recognized by the game as an affliction which upon reaching max strength would immediately stun the character and allow them to "give in". This is no longer the case, and modded afflictions with this type no longer work as expected.

### Reproduction steps

- Create a modded affliction with the type "paralysis", or simply just copy-paste the paralysis affliction and give it a different identifier.
- Give yourself this affliction at maximum strength.
- Notice how you don't get the option to give in, and that the affliction doesn't stun you automatically unless there's a status effect that does it.

[Mod that contains modded copy-pasted paralysis](https://github.com/Regalis11/Barotrauma/files/10582036/Paralysistest.zip)

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a25bcfa412368f9011036f320ed1497ae73ad58a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
