### ISSUE TITLE
[dev] Mods can't be downloaded from workshop

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1115]
version of the game and is not 0.9 so workshop always says that mod is incompatible

**Comment by etet2** [comment]
subs somehow bypass this

**Comment by Regalis11** [comment]
Which version of the game are you playing? This should've been fixed in e0ca9ffe and patched in v0.8.9.3.

**Comment by etet2** [comment]
didn't realise this was fixed already
