### ISSUE TITLE
Submarine upgrade prices affected by tier

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11158]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The price of the same level of submarine upgrade seems to increase or decrease if the tier of the submarine is lower or higher than tier 3.

Since the Dugong is a Scout it is possible to purchase an Engine upgrade of one tier higher but the price is higher than intended (5,000 marks instead of 4,166) 
![image](https://user-images.githubusercontent.com/115734437/216822823-8b7adba7-125e-4b84-bd96-0aedb6f192cf.png)

Level 2 Hull Upgrade costing 6,000 marks for a Dugong (none of the crew members have Retrofit or Iron Storm):
![image](https://user-images.githubusercontent.com/115734437/216820968-206e6a97-0aaf-4fb0-b3e3-512e2d5d0f17.png)

Same Level 2 Hull Upgrade costing the intended 3,333 marks after giving a crew member Iron Storm:
![image](https://user-images.githubusercontent.com/115734437/216821324-f8d030ca-28c6-4621-94fd-b25a46ed8c4b.png)

Same Level 2 Hull Upgrade costing even less after giving a crew member Retrofit:
![image](https://user-images.githubusercontent.com/115734437/216821800-74c05bf3-ca45-448c-a7cc-5d937070e531.png)

Also note that Retrofit currently gives one additional level of hull upgrade, instead of its intended effect (Unlock hull upgrades as if your submarine is one tier higher.), which also goes past level 6: 
![image](https://user-images.githubusercontent.com/115734437/216820009-d5479588-14de-496b-a579-bc8af1ebfa07.png)

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/47e133e794fed9cc35ec99adafb5ea49ab97000e

**Comment by Regalis11** [comment]
Tested, no issues found. Merging & closing
