### ISSUE TITLE
Alien Blood no longer gives psychosis

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11150]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Alien Blood no longer gives psychosis, despite the fact that it should very clearly give psychosis (there's a medic talent that reduces psychosis from alien blood)

It also heals as much as a regular Blood Pack

```xml
      </StatusEffect>
      <StatusEffect tags="medical" type="OnSuccess" target="UseTarget, This" duration="15">
        <ReduceAffliction identifier="bloodloss" amount="8" />
      </StatusEffect>
      <StatusEffect tags="medical" type="OnFailure" target="UseTarget, This" duration="15">
        <ReduceAffliction identifier="bloodloss" amount="4" />
      </StatusEffect>
```

Consider reducing the amount healed and/or adding random side effects such as:
 
```
          <Affliction identifier="nausea" strength="30" probability="0.2" />
          <Affliction identifier="huskinfection" strength="5" probability="0.01" />
```
Think of it as getting space STDs from used syringes

### Version

0.21.6.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea1a026dcfff67f93afd7c4be5de05b0ccabed9d

**Comment by 3e849f2e5c** [comment]
Tested, psychosis is applied correctly now
