### ISSUE TITLE
Broken version of wrecked door sprites is messed up

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11152]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The sourcerect of the broken version of wrecked door sprites is incorrect

### Reproduction steps

1. Cut a wrecked door
2. Notice a weirdly offset version of the doors sprite appears
![image](https://user-images.githubusercontent.com/14351070/216762492-d2ef8430-977d-41be-99d1-45a9660b5551.png)

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Make sure to fix the sprite depth as well as the door seems to appear in front of the character
![image](https://user-images.githubusercontent.com/73229309/216764570-57a85f53-a4e1-4d22-8912-52257aba5b4a.png)

Reminds me of a certain  #10860 😏

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/485bf3a0aa3abf4d9aa23a756613f2f4c62dcb59

**Comment by itchyOwl** [comment]
Tested, didn't notice any issues. Only that the broken sprite is not that easy to notice. But I don't think that's a technical issue.
