### ISSUE TITLE
Unable to join a game: "Could not set the transform of a body (World was null - has the body been removed?)"

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11153]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![J5A4`7I10%(_@%4A6_9P)$F](https://user-images.githubusercontent.com/99462070/216772741-1b9f09fe-69b4-4cf6-b74e-7ca6001558ba.jpg)
In a dedicated server, after finishing a round, the client is kicked to the lobby with error shown above and could not rejoin the game. 
Even if rejoining the server, the error message will show and block from joining the game.
The only mod enabled is AnimEuropa.

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro, closing
