### ISSUE TITLE
Light Components inappropriately and randomly switch on and off or start blinking.

### ISSUE THREAD

**Issue by DrBanocanut** [Regalis11/Barotrauma#11156]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since the 1.0 Pre-patch the light components in my custom sub have been randomly flipping on and off as my character moves around inside the sub or changes facing or if I zoom in and out by moving the mouse pointer. Sometimes some of the lights start blinking in time with the navigation console despite not being configured to blink. I first saw this in the run mode of the sub editor but it also happens in game. I admittedly have a large number of light components with a short range that I use as indicator lights, but they didn't previously show this problem. I've been able to reproduce this problem in a vanilla submarine.

### Reproduction steps

1. Open the sub editor.
2. Load the Dugong vanilla sub.
3. Put down one Light Component.
4. Change the Light Component to be on and non-interactable. Set its range to 16.
5. Make about 30 copies of this Light Component and place them on any blank parts of the interior wall.
6. Start a test run. When ready, move the character backwards and forwards in the compartment and zoom in and out by moving the mouse pointer. The lights that were placed first are mostly likely to change as the point of view changes. It may take a few seconds before the effects start showing up.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I would suspect that this is the same issue as https://github.com/Regalis11/Barotrauma/issues/11041. What's the "visible light limit" set to in the game settings? Increasing it (or setting it to unlimited) would most likely get rid of this issue. Please let us know if that helped or not!

**Comment by DrBanocanut** [comment]
Thanks for the prompt response and apologies for not noticing the similarity to 11041.
The visible light limit was set to 50. My busiest view encompasses 110 lights of which only 18 are normally lit. I set the limit to 100 and the problem went away.
