### ISSUE TITLE
Pirate items considered as station items

### ISSUE THREAD

**Issue by C0d3Gam3r** [Regalis11/Barotrauma#11159]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In "Activate Beacon" missions, when encountering the pirate base variant, taking the pirate's loots when they are dead/knocked out results in a loss of reputation with a station, which doesn't make sense as in abandoned outposts doing the same thing doesn't have the same consequences.

### Reproduction steps

1. Start an "Activate Beacon" mission with the pirate base variant.
2. Kill/knock out some pirate and try to take their loot.
<img width="2048" alt="Captura de Tela 2023-02-05 às 10 41 40" src="https://user-images.githubusercontent.com/94804899/216823138-84af87ab-a804-47c3-a231-728545c07735.png">
As can be seen on the image, the pirate's items have the stealing icon on them.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2197df6ccef5f8b241d4e4c362d63b77ec0d0372

**Comment by JeroonBosch** [comment]
Tested on dev: got reputation loss when I killed one bandit, then looted him while his buddy watched. 
Tested on branch with fix: did not get reputation loss in same scenario + location.

Closing
