### ISSUE TITLE
Death in the Sub Editor no longer automatically changes your character to a living one

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11151]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In previous versions of the game, a player's death in the Sub Editor would automatically swap them to another living character on the sub. It also showed the dead player's name go red and taken from the character list, indicating that the character had died. As of 0.21.6.0, this no longer occurs. Players who die in the Sub Editor will remain motionless on the floor with an empty vitality bar, unknowingly lying dead. This is problematic as inexperienced players will not know what to do in this situation as there is no indication or hint that players can swap to another living character manually. 

Below includes some images of the perspective of a deceased player. 

![image](https://user-images.githubusercontent.com/105495756/216735163-fb188339-29cb-4fcd-93f3-f6121bf96293.png)
_Figure 1. Deceased player's screen after dying._

![image](https://user-images.githubusercontent.com/105495756/216735184-8e04289f-14e3-4c73-8765-a7692b0808e8.png)
_Figure 2. Deceased player's screen after dying._

![image](https://user-images.githubusercontent.com/105495756/216735190-689917f5-c6de-491f-aaec-d5e1db5faf4f.png)
_Figure 3. Deceased player's screen after dying._

![image](https://user-images.githubusercontent.com/105495756/216735196-6825b86d-18f9-444b-a8a3-396cfa0a8d8a.png)
_Figure 4. Player using the health UI to diagnose the character with death._

### Reproduction steps

1. Open the sub editor and load any sub (typhon 2 was used in this example)
2. Enter the test mode
3. Kill yourself
4. Observe how you get stuck in a death screen with no indication of what to do next

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
I don't recall switching to a new character happening before

**Comment by Regalis11** [comment]
To my knowledge, there's never been any automatic character switching.
