### ISSUE TITLE
When treating, the NPC doctor does not look for medicines in the patient's pockets.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11165]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When treating, the NPC doctor does not look for medicines in the patient's pockets. The patient may carry medicines in his pockets, on his belt or in the pockets of the doctor's uniform worn by the patient. It would be logical if the doctor searches for the medicines through patient's pockets, if necessary. Because the patient carry medicals to keeps own health.

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not really a bug, and I don't quite agree with this. Imo it doesn't make that much sense for the doctor to look for medicines in your pockets, neither from a gameplay perspective or realistically. If you have meds that you could use to heal yourself, you can use them instead of paying the doctor to treat you.

**Comment by pavel4win** [comment]
1. If I have meds but not have med skill call the doctor is the best choise.
2. In expedition if I am unconscious, and have full pockets of anaparalyzer, morphine and oxygenite, and the doctor screams that he has no drugs to treat me, this no good. And I die then with full pockets of meds.

**Comment by itchyOwl** [comment]
I think the medic could check the pockets of an unconcious target. But I agree with Regalis that otherwise I don't think it would be a good idea to make a bot to poke into your pockets.

**Comment by pavel4win** [comment]
I agreed that doctor must check only pocket unconcious (or incapacitated) man. But he must!

**Comment by Regalis11** [comment]
Ah, I think I misunderstood the issue. I somehow thought this was about the doctor in the medical clinic in outposts, not "normal" medical doctor bots.

I do agree it'd make sense for the medical doctors to check unconscious patients' inventories for the meds.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
