### ISSUE TITLE
Shuttles (and monsters) can spawn inside ice

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11162]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

We're using mods but maybe it's a vanilla issue. So far, I've seen seen a shuttle spawn inside ice twice. 

Also, sometimes monsters in caves spawn inside ice.

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

What do you mean by ice specifically? The static level walls? The destructible, floating, ice chunks? Ice spires?

**Comment by JaxMesa** [comment]
This happend to me too. Monsters and respawn shuttles sometimes spawned in ice that level generated as natural blocker that we, as players, have had to clear. (Floating ice peaces. Don't know the right name of it)

**Comment by JaxMesa** [comment]
Sometimes exactly monsters like crawlers and mudraptors spawned in the ice WALLS, the level border. They were stucked and couldn't move. We couldn't shoot them.

**Comment by Krzeszny** [comment]
Monsters can spawn in ice chunks in caves. 

Not sure about shuttles.

**Comment by Regalis11** [comment]
(Hopefully) finally fixed now https://github.com/Regalis11/Barotrauma-development/commit/4b8ffd06766f19c994f71b9f610a7ae07694b0cc & https://github.com/Regalis11/Barotrauma-development/commit/ee15d3187d729e44d254195a999b6989a9e839dd

**Comment by Regalis11** [comment]
Internal note: this can be tested more easily by doing the following:
- Force the commonness of Great Sea very high by adding something like `commonness="10000`" to TheGreatSea.xml (this biome has the largest number of floating ice chunks).
- Add the following block to RespawnManager (forces it to choose a position inside a wall if there are any available):
```
if (Level.Loaded.IsPositionInsideWall(potentialSpawnPos.Position.ToVector2()))
{
    potentialSpawnPositions.Clear();
    potentialSpawnPositions.Add(potentialSpawnPos);
    break;
}
```
![image](https://user-images.githubusercontent.com/14351070/217503162-1feccf99-9582-40ec-b116-fac30b373bcf.png)
- Kill your character and `respawnnow`, repeat a few times and the shuttle should eventually spawn inside ice (requires a floating ice chunk to be on one of the potential spawn positions)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
