### ISSUE TITLE
Cheaper Nuclear Depth Charge still uses Depth Charge Shell in its recipe

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11160]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Depth Charge Shells were changed to require UEX to make and the normal Nuclear Depth Charge materials were changed to require 2 Iron instead of one Depth Charge Shell but the cheaper recipe from the talent Nuclear Option still requires a Depth Charge Shell.
Depth Charge Shell required materials:
![image](https://user-images.githubusercontent.com/115734437/216836849-5553ed09-af7e-4d54-8c95-268c4dd2bcdc.png)

Standard Nuclear Depth Charge required materials:
![image](https://user-images.githubusercontent.com/115734437/216836885-6a33f59f-bed8-4695-a189-3536073e5529.png)

Cheaper Nuclear Depth Charge from the talent Nuclear Option:
![image](https://user-images.githubusercontent.com/115734437/216836905-19f8d057-d3bd-46c5-9173-63c92ee5262f.png)

 

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ae12e7b5b91805ab05e905f6e691384431703f85. Can't see any issues with the changes, moving to QA

**Comment by Regalis11** [comment]
Tested, couldn't find any issues. Closing.
