### ISSUE TITLE
In the "Biome" section of world map descriptions of outposts in the Aphotic Plateau, it says, "Europan Ridge"

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#11164]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I clicked on an outpost in the world map in the second biome and noticed that the part of the description which indicated its biome said, "Europan Ridge". It explains my initial confusion with biome names.
First Biome:
![Barotrauma 2023-02-05 4_19_39 PM](https://user-images.githubusercontent.com/81781733/216855162-53f0586a-cf1b-4a46-8983-d29800f1e2da.jpg)
Second Biome:
![Barotrauma 2023-02-05 4_19_44 PM](https://user-images.githubusercontent.com/81781733/216855188-73e1a3d5-51d0-4580-bfde-6ac6168cec7d.jpg)

### Reproduction steps

1. Start a Campaign
2. Go until you can see an outpost in the Aphotic Plateau on the world map
3. Click on an outpost in the Aphotic Plateau
4. Notice that the description says, "Europan Ridge"

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment]
But Europan ridge IS the second biome, only after which comes Aphotic Plateau. Biomes wiki for reference: https://barotraumagame.com/wiki/Biomes

**Comment by TheMinerBoy** [comment]
Dammit
