### ISSUE TITLE
Possible wiring fault in Researchmodule_02 containment door

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11169]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The door is wired incorrectly to act as a containment mode, presumably it was intended to be a single press on an or component (or use some other wiring logic here other than pressing two buttons at the same time). If you do pull it off I don't feel the behaviour is intended as you can hear the door open and close many times over.

![image](https://user-images.githubusercontent.com/29177976/216988430-db5f8617-692f-46aa-8703-465e7e1473a2.png)

I figure the buttons should act as a lockdown and/or release mechanism (Where either triggers the door to close), but the wiring is just two buttons tied to an and component (not switches or such, or components or other logic) which is then wired to the door's toggle state. meaning the mechanism is likely opening and closing the door repeatedly for as long as the signal from the buttons/and component lasts.

### Reproduction steps

Open subeditor
Load researchmodule_02
Check wiring of the door
enter test mode
keep pressing both buttons, recommend teleporting, notice the sound of the door activating multiple times within a second (Or well, sounding incredibly loud) before stopping in a potentially random state.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/408d818fc9d70e4057e0e5e87dc1358a217acd16

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
