### ISSUE TITLE
Fire extinguisher spray gets blocked by characters

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11178]
Leading to issues where e.g. bots are unable to put down a fire if you stand in the way (also affects player controlled characters):
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/bfc90d6c-c9a0-4abc-a939-194a10b7c744)

Fixed in Regalis11/Barotrauma-development@e1b5545.

On testing: try to extinguish a fire by standing behind a character. In the debugdraw mode, you can see whether the fire is being extinguished or not.

**Comment by JeroonBosch** [comment]
No longer an issue, closing
