### ISSUE TITLE
/givetalent tab-completion confuses "Mechanic" and "MECHanic" talents

### ISSUE THREAD

**Issue by xolophreny** [Regalis11/Barotrauma#11179]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unable to give Mechanic's "MECHanic" talent using `givetalent` tab-completion

### Reproduction steps

1. With console enabled, type `givetalent mech`
2. Try to tab-complete, observe two options - `Mechanic` for the Assistant job specialisation, and `MECHanic` for the intended Exosuit talent
3. Entering any of the two variants gives the Assistant talent
4. Optional: ponder if changing localisation to flavour the talent as `MECH-anic` would help

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
This can be worked around by using the identifiers of the talents instead of the names: the identifier of the "MECHanic" talent is "powerarmor" and the id of the assistant talent is "apprenticeship_mechanic".
