### ISSUE TITLE
You can quickly switch weapons to increase reload speed

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#11177]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

as the title said.

### Reproduction steps

1. set weapons skill to zero for obviously aware of the problem
2. use the rifle to shoot and you will wait 5s to reload
3. just quickly equip another weapon, such as revolver or boarding axe
4. and quickly re-equip back the rifle
5. the reload timer of rifle will be reset to about 1 second

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ddd7460e660d876d0aa2a95d35880d2bf551379

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
