### ISSUE TITLE
Error while reading a message from server (nullref exception in CharacterInfo.ClientRead)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11173]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I tried joining a server and got an error. It keeps repeating each time I try to join. Tested within a few minutes' period.

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment SyncIds at position 32.
Inner exception: Object reference not set to an instance of an object.
   at Barotrauma.CharacterInfo.ClientRead(Identifier speciesName, IReadMessage inc)
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg)
   at Barotrauma.Networking.GameClient.<ReadLobbyUpdate>b__114_0(ServerNetSegment segment, IReadMessage inc)
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler)
```

**Comment by Regalis11** [comment]
Thank you for the report!

Unfortunately the error message seems to be missing line numbers for some reason, so it's hard to tell what exactly caused the exception. What kinds of mods are you using? Something like Lua for Barotrauma might affect the error messages, and it could be the exception happens as a result of an error in a mod as well.

**Comment by esirprus** [comment]
i get the same error:
Error while reading a message from server. 
Exception thrown while reading segment SyncIds at position 32.
Inner exception: Object reference not set to an instance of an object.
   at Barotrauma.CharacterInfo.ClientRead(Identifier speciesName, IReadMessage inc)
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg)
   at Barotrauma.Networking.GameClient.<ReadLobbyUpdate>b__114_0(ServerNetSegment segment, IReadMessage inc)
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler)

**Comment by esirprus** [comment]
here's the server's modlist i tried to join:
[mod列表及其工坊编号.xlsx](https://github.com/Regalis11/Barotrauma/files/10685804/mod.xlsx)

**Comment by Krzeszny** [comment]
> Thank you for the report!
> 
> Unfortunately the error message seems to be missing line numbers for some reason, so it's hard to tell what exactly caused the exception. What kinds of mods are you using? Something like Lua for Barotrauma might affect the error messages, and it could be the exception happens as a result of an error in a mod as well.

Yes, we were using Lua among other mods.

**Comment by Godzillacb** [comment]
I got the same error while joining a server with the warden job while I had a warden character. I had to enable the Warden Job mod in the mods menu *before* joining for it to work. Try enabling the Blade Job mod or NT Surgery (which adds surgeon) before joining!

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
