### ISSUE TITLE
Upgrade materials are not accessible from sub storage

### ISSUE THREAD

**Issue by Arctomachine** [Regalis11/Barotrauma#11174]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to upgrade parts that require materials, if materials are stored somewhere in sub, upgrade is impossible due to "lack of" materials.
Expected result: use materials from sub storage for upgrades.

### Reproduction steps

1. Put 5 steel bars into storage
2. Visit upgrader
3. Try to upgrade first level of hull (costs 5 steel bars)
4. Bar indicator is red, upgrade is locked

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Yeah I found that personally odd too.
