### ISSUE TITLE
Unidentified genetic materials are 36x less likely to spawn

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11170]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

All 36 unidentified genetic materials got merged into one, but their spawn rate hasn't been updated, remaining at 2% on a single item which seems really low
This makes the unidentified genetic material very rare especially in ruins' incubation bubbles (geneticstorage)

```xml
    <PreferredContainer primary="medfabcab" spawnprobability="0"/>
    <PreferredContainer secondary="abandonedmedcab,wreckmedcab,outpostmedcab" spawnprobability="0.01"/>
    <PreferredContainer secondary="geneticstorage" spawnprobability="0.02" />
```

Note that not all spawn chances were 2%, higher quality genetic materials were probably rarer than that, so spawnprobability shouldn't be straight up multiplied by 36

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/128dd2f042e0fcec746d521d2e16b782a86c63aa

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
