### ISSUE TITLE
Left handedness is not fully implemented.

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#11184]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Left handedness is half implemented. Well in game you can fully change the keybinds to make left handed mouse work (aim with left click hold, fire with right click), with the menus (in game and at splash screen) it defaults to right handed mouse even with the OS set to left handed use. 

### Reproduction steps

1. start game with OS on right click being primary. (menus will still be left click primary.)
2. rebind keys to left handed mouse. (left click hold to aim, right click to shoot as example)
3. try to use menus with the same mouse style. (left click will still activate menu items.)

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/issues/3959, closing
