### ISSUE TITLE
"Greater Component" tooltips are incorrect when mousing over them.

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#11182]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When mousing over the "Greater Component", the tool tips make it appear as though it's an "Equals Component".
![greater_than](https://user-images.githubusercontent.com/547467/217384645-9267df11-92b0-436f-a2d3-33825fbfb790.png)

### Reproduction steps

1. Enter the sub editor.
2. Place down a "Greater Component", then click on it.
3. Mouse over the "Output" and "False Output" to see incorrect description.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad3247aa2e2bb261e3b9d189800cbb2403dc28dc

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
