### ISSUE TITLE
Strange behavior from RegEx Find component

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#11185]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm trying to build a 'min(a, b)' component (as that still doesn't exist in the game) with as few components & wires as possible.  I've managed to do so with two components (a `RegEx Find` and a `Greater` component), but this reveals some odd behavior of the `RegEx Find` that doesn't make much sense.

In short, the RegEx is looking for a zero-length or 'null' string.  Initially it will not be able to detect this.  However, *after* it receives a non-null string, it is then suddenly and inexplicably able to detect null strings.

### Reproduction steps

1. Load or start a new sub in the sub editor.
2. Add the attached item assembly to the sub: [weird_regex.zip](https://github.com/Regalis11/Barotrauma/files/10683715/weird_regex.zip).  Test the sub from the editor.
3. Notice how, initially, the value in the top `Memory` component is less than the lower one, and nothing is shown on the display.  It will remain this way until the value in the top is greater than or equal to the lower value.
4. Change the value in either of the `Memory` components such that the value in the top component is greater than or equal to the lower one.
5. Notice how the display is updated (in this case, by the `Greater` component, and *not* the `RegEx Find` component).  This is as expected.
6. Now change a value in either of the memory components such that the top value is less than the lower one.
7. Notice how now, the `RegEx Find` component suddenly seems to detect the null string from the `Greater` component and update the display.  It will continue to do so no matter what values are placed in the memory cells from now on (the display being updated by either the `RegEx Find` or the `Greater` component depending on the values in the `Memory` components).

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Tsunder** [comment]
this is incorrect, and due to poor wiring by the user. 

in the circuit posted, the text display is getting its text set by both the regex and the greater than component, both updating the text component in the same frame.

same circuit but attached to a terminal instead of a text display.

![image](https://user-images.githubusercontent.com/5103517/217492601-3f1a8291-070d-4409-b6bf-39ff7c623af3.png)


please use seperate text displays for different signal outputs, and use terminals to display no-signals.

**Comment by Regalis11** [comment]
> in the circuit posted, the text display is getting its text set by both the regex and the greater than component, both updating the text component in the same frame.

This seems to be the case. Sending multiple simultaneous signals to the same input leads to unpredictable behavior, and should be avoided.
