### ISSUE TITLE
Unidentified genetic material not appearing in research outposts

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11189]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using the blackmarket genes talent, I am finding UGM in cities but not research outposts. Checked 4 outposts and none of them had UGM for sale.

### Reproduction steps

1. start a campaign (tested on singleplayer campaign)
2. spawn a medical doctor and give them the blackmarket genes talent
3. traverse (or campaignteleport) to a research outpost
4. find that you cannot purchase any genes

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Even though this is not exactly the same issue as https://github.com/Regalis11/Barotrauma/issues/11190, I'll close it as a duplicate since they're essentially just symptoms of the same issue.
