### ISSUE TITLE
[Factions] Jailbreak Prisoners count as enemies, and promptly get killed by AI crewmates

### ISSUE THREAD

**Issue by AtobaAzul** [Regalis11/Barotrauma#11181]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Jailbreak prisioners get attacked by crewmates with the "Assault Enemy" (and possibly "Fight Intruders") orders.
NPCs also do the Intruder callout if they're on the sub.

### Reproduction steps

1. Set some NPCs to Assault Enemies
2. Free the prisioners
3. Watch as the NPCs kill everyone, prisioners included

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
![image](https://user-images.githubusercontent.com/8641689/218044493-a29322f8-c086-484f-8993-95b1f00543b6.png)
Still being shot at after the fix, moving back

**Comment by itchyOwl** [comment]
Probably need to adjust HumanAIController.DetermineCombatMode (inside RespondToAttack) in a similar manner that we handle instigators.

**Comment by JeroonBosch** [comment]
This works properly now - do suggest bumping rewards up a (fair) bit
