### ISSUE TITLE
artifact in screwdriver sprite

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11198]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the screwdriver has some sort of graphical artifact

here's a screwdriver set to black, scaled up to 2, screenshottted, and filled the area w/ paint bucket tool

![image](https://user-images.githubusercontent.com/5103517/217970557-70eb33ad-2599-474e-b388-874f7e5723ce.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
wrench has someone's signature on it and it seems to be sanded off on one end too 
![image](https://user-images.githubusercontent.com/5103517/217971767-30dd56d2-dc6e-4ffb-a08d-9e349cf57f0a.png)

**Comment by Tsunder** [comment]
putting weapons_new.png into paint and filling shows quite a few dots in the midair 
![image](https://user-images.githubusercontent.com/5103517/217973412-cfe0d8d5-a05c-4b98-b802-37df25e8be32.png)

**Comment by StruggleDuck** [comment]
![tools](https://user-images.githubusercontent.com/92034548/217999667-ad0149bd-f752-406e-b38d-39cb6975e213.png)

In the actual tools.png file, the artifacts are present.

**Comment by NamAnhLe** [comment]
Cleaned up these artifacts in 9fd59a6

**Comment by Regalis11** [comment]
No issues found, closing
