### ISSUE TITLE
Outposts affected by nonadjacent hunting grounds

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11191]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Outposts which aren't adjacent to hunting grounds have a chance to become abandoned if they are connected to a location which does have hunting grounds next to it. According to in-game text, hunting grounds are only supposed to affect adjacent locations.
![image](https://user-images.githubusercontent.com/115734437/217618329-75417d17-48b4-4d4d-bd5c-b2ec3fcbfa6a.png)
Example of Mining Outpost being abandoned despite not being next to hunting grounds:
![image](https://user-images.githubusercontent.com/115734437/217618505-78463856-0400-4e4c-bc6e-7c323a99c24c.png)
Another example where the outpost in the bottom left becomes abandoned, which is to be expected, but another outpost to the right also gets abandoned, even though it isn't next to any hunting grounds:
![image](https://user-images.githubusercontent.com/115734437/217618980-34b8a49f-72fc-4c80-801f-5174c777c3e4.png)

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
No more issues found (see PR for testing steps). Closing
