### ISSUE TITLE
Hitbox of rotated item doesn't rotate

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11199]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

rotated item doesn't change its hitbox, making them potentially hard to click, as it still only registers on the white box

example

45 degrees rotated

![image](https://user-images.githubusercontent.com/5103517/217976759-3a7e073f-4ea1-4b0f-819f-9725476bc14b.png)

### Reproduction steps

place a rotatable item, preferably long one for dramatic effect
rotate it

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/87db30677dfe62967f101544ec75e246250ef558.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed. 
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/d2e76fe1-6d97-4f3b-95ca-333c7d53711f)
