### ISSUE TITLE
[Factions/Endgame] Having notifications/text boxes on screen can cause the camera to lock up.

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11197]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Occasionally, having notifications/text boxes on screen can cause the camera to lock up. 

### Reproduction steps

1. Enter a dialog / have notifications present on screen
2. ??
3. The camera locks up and you are unable to move it.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by StruggleDuck** [comment]
Unsure, but could be related to this issue #6897

**Comment by itchyOwl** [comment]
Need to find the steps for this.

**Comment by Regalis11** [comment]
No known steps to repro, closing
