### ISSUE TITLE
Unidentified genetic materials are 36x less common in stores

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11190]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Essentially the same as #11170 but with Blackmarket Genes. Research stations only sell a single UGM (well, they currently don't sell anything but that is reported in #11189) and cities only sell 5. This affects the utility and balance of the talent very significantly.

Previously research stations sold 36 total UGM and cities sold 180. I personally don't think that those numbers should be brought back, but the numbers should be a little higher.

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Despite the code saying `minavailable="10" maxavailable="15"` the Research outpost only seems to sell one
![image](https://user-images.githubusercontent.com/8641689/217769072-40a980a8-9fa4-428e-a9eb-52ef6c6781ce.png)
