### ISSUE TITLE
Shuttle battery is not repairable + broken sprite

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11193]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The shuttle battery is still missing a repairable component, unlike the "normal" battery it cannot be damaged nor repaired (but can still be drained by EMP). 

 The power bar also overlaps the broken sprite
![image](https://user-images.githubusercontent.com/73229309/217696826-c00e2489-e885-4691-86b2-b6bf9a3a1b2c.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional: the shuttle batteries are non-repairable because they're often placed in spots where they can't be repaired.
