### ISSUE TITLE
[Factions/Endgame] Huskified Storage Container counts as enemy

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11196]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While in the same room as a Huskified Storage Container, the symbol for intruders in the bottom left of the screen begins flashing, as if there was a hostile intruder inside the ship.

### Reproduction steps

1. Obtain a huskified storage container
2. Be in the same room as it
3. look at the alert icons in the bottom left

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to have been addressed alongside https://github.com/Regalis11/Barotrauma/issues/11195
