### ISSUE TITLE
[Factions/Endgame] Huskified Storage Container produces Chitin Chunks. Gets attack by bots?

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11195]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Huskified Storage Container produces Chitin Chunks. Im 99% sure that this is not intended.

### Reproduction steps

1. Obtain a huskified storage container
2. Play with it and keep it fed.
3. Obtain Orange Boy Shells.

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This was actually intentional: the husk parasite's appendages are said to be "chitinous". But I agree that the orange boy's distinctly non-husk-like sprites don't seem fitting, so I think I'll tweak them a bit.

**Comment by StruggleDuck** [comment]
In that case, I would agree. Perhaps there could be a distinction between Chitin and Mantis shell pieces. It then also would provide a potential item for the Mantis to drop (when/if the mantis returns).

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/96b33b212551dd8136c7d2a354dbab4d0b8388e6

**Comment by JeroonBosch** [comment]
Tested, the item drops make more sense now, closing this

**Comment by JeroonBosch** [comment]
Actually reopening, as my Security Officer bot straight up killed it when I spawned it. Not related to the item spawns, but can reuse this ticket?

**Comment by JeroonBosch** [comment]
Fixed now
