### ISSUE TITLE
Depth Charge Shell still cost 30 marks

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11203]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Depth Charge Shells still have their base price set to 30 marks, making them a cheaper source of UEX (buying them from a merchant and deconstructing them)
![image](https://user-images.githubusercontent.com/115734437/218163038-bcff037f-0075-42ba-8db6-a49046ab0a95.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Closing as addressed.
