### ISSUE TITLE
Harpoon launching like 5 inches

### ISSUE THREAD

**Issue by DanielSaurusRex** [Regalis11/Barotrauma#11202]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Every time I shoot a harpoon gun it goes about 5 inches to 3 feet then loses all momentum, making it very hard to kill even crawlers unless they are charging at me or in my face

### Reproduction steps

shoot a harpoon gun
I don’t know if it’s a mod, I don’t think it is, I would test but I’m not home

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This doesn't seem to occur in the vanilla game, so I'm fairly sure it's one of the mods you're using.
