### ISSUE TITLE
Banana peels cannot be dropped without tripping on them

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11216]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems like an oversight, but banana peels can only be put down without slipping on them by throwing them, even immediatly making you slip if you drop them while running. Perhaps a cooldown is in order.

### Reproduction steps

1.Drop a banana at your feet
2.Try to move away

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not a bug: don't drop them under your feet when walking/running or wear clown gear that makes you immune to them. :)
