### ISSUE TITLE
Bananas arent held correctly

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11215]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/218285224-d4e4fd13-de6c-4512-91ff-7c76b639f6e1.png)
For some reason, the banana is held by the wrist

### Reproduction steps

1.Hold banan
2.Look at it

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/235b66075b7f57c5bf9ce6f363d88f1339223027

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
