### ISSUE TITLE
Suddenly cannot enter hatches anymore, horrible desync issue

### ISSUE THREAD

**Issue by cartarsauce34** [Regalis11/Barotrauma#11219]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So me and my friends have been running a campaign for the past month. I'm not sure if this is why our issue happened, but when we encountered a thalamus, we all got a bunch of error messages in the console, and immediately after this, i could not walk through any doors/hatches. I can open them but i just get rubber banded back through the door when trying to walk through. For my friends, it just looks like i'm walking into the door. I can't climb down ladders either, i just like teleport back up. here's the save if anyone can help fix it, we've been running this save for a while so it would really suck if it's just ruined, i haven't been able to find any fixes for this, i tried verifying my files and we loaded into the next outpost, but the issue still persists. I've seen some people with the same issue on reddit, but the posts never have any replies.
[baro save.zip](https://github.com/Regalis11/Barotrauma/files/10715076/baro.save.zip)

### Reproduction steps

I'm unsure if the issue can be reproduced, our sub got latched onto by a thalamus on a wreck, when we hit the wreck we got some error codes. not sure what actually caused it. i wasn't playing with any mods either. the game never crashed.

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

> we all got a bunch of error messages in the console

If you could post a screenshot of the error messages, it would most likely help us a lot in diagnosing this. Thank you and sorry for the inconvenience!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
