### ISSUE TITLE
When making pucs oxygen tank disappears from combat diving suit

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11212]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When making pucs in fabricator, if an oxygen tank was inserted into the combat diving suit used for crafting, the tank disappears.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. The tank seems to drop outside the fabricator when the fabrication finishes:
![image](https://user-images.githubusercontent.com/14351070/218815942-7167c9ac-26b6-4bac-b08c-de810774c340.png)

**Comment by pavel4win** [comment]
Oh, I didn't notice it. I assumed that tank would fall into the queue of fabricator materials. I didn't look at the ground. I think you are right, I close issue.
