### ISSUE TITLE
Husk Wears Double Diving Suit- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1122]
- [x] I have searched the issue tracker to check if the issue has already been reported (for real).

**Description**
Taking off husk's diving suit from his inventory will reveal texture of another one as his character's skin. Does not work with husks being spawned by commands since they spawn with no inventory.

**Steps To Reproduce**
1. Find a naturally spawned husk.
2. Stun, cuff or kill a husk. Best by using console command killmonsters.
3. Take diving suit off from a husk.

**Version**
0.8.2.3 and earlier. May occur in full alpha as well.

System: Windows, but I think it works on any.

**Additional information**
To fix this bug the way husk will still drop oxygen tank he should not spawn with suit equipped but instead oxygen tank should be already in his inventory pretending to be salvaged from his armor.

Also husk comes equipped with battery cell in his suit. Batteries are now useless inside diving suits. I thing battery cell should be removed from husk and size of diving suit's capacity reduced to 1.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this. Are you playing with some kind of mods? The vanilla husks don't spawn with diving suits (or even have a slot for a suit). The capacity of the diving suits is one, and batteries cannot be contained inside them.

**Comment by rico6822** [comment]
Than I have no idea. I really encountered a husk with diving suit.

**Comment by Regalis11** [comment]
Are you playing with some kind of mods? Did this happen in single player or multiplayer?

**Comment by rico6822** [comment]
Multiplayer on vellamo. A ocean husk attacked us.

**Comment by itchyOwl** [comment]
Could take a look, but I doubt this will happen on the current dev version.
