### ISSUE TITLE
Particles bursting from scrap cannon muzzle looks a little weird

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#11220]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![G@WRX3ZX$QFT)`N~J`WVVK1](https://user-images.githubusercontent.com/73634685/218290762-61af1f17-a2ef-430f-a6bf-4a94cee67c34.png)
The direction of the particles seems to be the opposite of what it really is

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6dcde5ad2c567930d8bb546e34f2c09d6ae23661

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
