### ISSUE TITLE
Using arc emitter causes asynchronous stun on yourself in multiplayer game mode

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#11222]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

as the title said
![image](https://user-images.githubusercontent.com/73634685/218293583-3935c711-bea8-4df7-8fe6-12a9971f7560.png)

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd1fa5124c68dfe0c6f7ec47bf430612d93019f5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
