### ISSUE TITLE
Mining minerals mission description has an error in reward percentage

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11221]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/47295383/218291294-082acdf9-6fcf-4662-9ace-2f8345a3ee35.png)

in the mission description it says that I will get one third, but I get two thirds

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by pavel4win** [comment]
это ошибка перевода
this is translation error
In english "you are axpected to hand over 33%"
правильно переводится на русский как 
Have right russian meaning:
"вы должны передать нам 33%"
можно в русской версии в фразе
"ваша доля - 33%"
заменить местоимение "ваша" на местоимение "наша"
тогда фраза будет такая:
"наша доля - 33%"
тогда смысл фразы будет верный.
Then translation will be ok.

**Comment by Regalis11** [comment]
Thank you for the report! I made a note to the localization team about this, should be fixed in the next translation batch (post-1.0).

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/dd4a233eaae815305763f50859fe2a0d0fa78a62 (commit in our private repo). The changes should be coming out in the next patch.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by pavel4win** [comment]
The error was fixed but reappeared again in the new version.

We receive 75% as a reward and 25% is taken from us.
It would be correct to write: "вы должны передать нам 25%" (you must give us 25%)
or "наша доля - 25%" (our share is 25%)
or "Мы заберем 25% добычи". (We'll take 25% of the mined minerals.)

![2023-10-31_14-27-29 (2)](https://github.com/Regalis11/Barotrauma/assets/47295383/abd2b4dd-2621-439f-b55e-70932daa7cb5)
