### ISSUE TITLE
Available Outpost Mission jailbreak_separatists crashes lobby

### ISSUE THREAD

**Issue by madolinn** [Regalis11/Barotrauma#11238]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When docking at an outpost that has the jailbreak_separatists mission available for accepting, the station fails to create and everyone is kicked back to the lobby/main menu.

### Reproduction steps

1. Dock at station offering jailbreak_separatists mission
2. Crash

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Object reference not set to an instance of an object.
at Barotrauma.AbandonedOutpostMission.LoadHuman(HumanPrefab humanPrefab, XElement element, Submarine submarine) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\AbandonedOutpostMission.cs:line 218

---
\Barotrauma\Content\Missions.xml incorrectly references
<Character identifier="separatists"
separatists is not included as a character; likely it's intended to be hostageseparatists.
```

**Comment by Rokvach** [comment]
Tested, working correctly. can be merged and closed.
