### ISSUE TITLE
[1.0] Bandits in Beacon Stations have their items marked as stolen

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11232]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Another title is description report, really got a lot of simple tickets from this session.
![image](https://user-images.githubusercontent.com/105495756/218347469-093d3e8e-004e-4268-968a-8ab1d645794a.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Not a bug
