### ISSUE TITLE
[1.0] Items that require recipes stop sorting alphabetically after "S"

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11231]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

See reproduction steps, title is description.

![image](https://user-images.githubusercontent.com/105495756/218346994-d65e6cf8-35e9-41a4-93d2-bbf40ae1971d.png)

### Reproduction steps

1. Open the fabricator
2. Scroll down to "Requires recipe to fabricate" marker
3. Observe how the list starts at Cigar, in C
4. Scroll down to the S section
5. Observe how the list resets and continues alphabetically from this point onward

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It seems the items you have the skills to fabricate were listed 1st, fixed in https://github.com/Regalis11/Barotrauma-development/commit/09473a833558c42275f722e916a3af2e7c462635

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
