### ISSUE TITLE
[1.0] Containers holding items can be broken to show more items than they actually contain

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11233]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue seems to be more overarching than I originally thought, forgive the multiple title rewrites.

Railgun Shells and Nuclear Railgun Shells are not showing up correctly within the Railgun Loader. Images below for reference.

![image](https://user-images.githubusercontent.com/105495756/218348230-ac7454ed-f7b2-46f7-89d1-fe582fc195ef.png)
_Figure 1. Image showing one nuclear railgun in the railgun loader._

![image](https://user-images.githubusercontent.com/105495756/218348240-632c8e85-a81d-4129-ac21-df29b64928f9.png)
_Figure 2. Image showing railgun loader sprite showing two nuclear railgun shells despite only having one._

![image](https://user-images.githubusercontent.com/105495756/218348258-e3a202f3-1c46-4929-b0b5-a0dd5cdd8eac.png)
_Figure 3. Image showing one nuclear railgun in the railgun loader._

![image](https://user-images.githubusercontent.com/105495756/218348263-28c8313f-c07f-4206-b034-02cf2df7da2f.png)
_Figure 4. Image showing railgun loader sprite showing zero nuclear railgun shells despite only having one._

Additionally, a similar issue occurs with Battery Charging Docks. 

![image](https://user-images.githubusercontent.com/105495756/218349454-9e9443c8-4a2a-44a6-a1d6-bcd8be620742.png)
_Figure 5. Image showing 5 battery cells in a charging dock which only holds 4 battery cells._

![image](https://user-images.githubusercontent.com/105495756/218349460-11b40be7-884d-463d-aad4-934e7a51e1d5.png)
_Figure 6. Image showing the contents of the charging dock._

Other storage units having this issue

![image](https://user-images.githubusercontent.com/105495756/218350153-2d0191a3-dce8-4ab1-bcb3-1b358ef688b6.png)
_Figure 7. Other storage units suffering from this issue._

### Reproduction steps

1. Place down railgun loader
2. Add 5 shells inside
3. Open inventory and swap shells really fast

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/20aedd859f4fada4ed36c9d9db9fb8cb7984b730

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
