### ISSUE TITLE
Votes to start a round are not sent to the server correctly

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#11249]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a round starts, the server prints the following errors:
![image](https://user-images.githubusercontent.com/8607119/218745558-e51a02a6-4258-45e3-ae58-b32a4fcfd05b.png)

### Reproduction steps

1. Start a server
2. Join
3. Start a round
4. Observe errors in the server window

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/78fbb135ca18868bd34972304b8bb470ba4aba91

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
