### ISSUE TITLE
AI struggles to repair remora top hatch

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11248]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the AI on fix leaks order struggles to repair the walls left/right of the top hatch, unable to path to it nor swim to it when flooded.

![image](https://user-images.githubusercontent.com/29177976/218743860-d3747e08-7e6c-433c-880e-ac18d6d96a9f.png)

### Reproduction steps

1. Start a game with the Remora submarine (quickstart, campaign, sub editor etc)
2. equip bot with a diving suit (IE. pucs + oxygen tank)
3. damage the wall near the hatch, I used explosion 100 0 0 1000 for this but some minor plasma cutting works too
4. order bot to fix leaks, find they will not path to it, partial or full flooding

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Stole this ticket because I did [some changes](https://github.com/regalis11/barotrauma/issues/11806) to Remora [in another branch](https://github.com/Regalis11/Barotrauma-development/pull/4121), and thought I could fix this there too: https://github.com/Regalis11/Barotrauma-development/commit/0e3cc4d547777afe23d8f8b0506af909fff7feff

**Comment by Rokvach** [comment]
Seems like the bots are having issues switching ladders to reach the leak
![image](https://user-images.githubusercontent.com/7299826/236765545-d2505fe7-1e21-4307-8c84-9c0da74e8c22.png)
![image](https://user-images.githubusercontent.com/7299826/236765887-f4264ed5-43dd-4cce-80e2-e05769b50b5f.png)
