### ISSUE TITLE
Research Station mentions non-existing queue, boxes not aligned nicely

### ISSUE THREAD

**Issue by JeroonBosch** [Regalis11/Barotrauma#11245]
![image](https://user-images.githubusercontent.com/8641689/218704929-09199b84-727d-48db-b092-d0dd636d2cb4.png)
There's two minor flaws in the Research Station:
1. The boxes aren't aligned
2. It says Queue on the top row, but there's no actual queue (it always takes 2 ingredients, and genetic material isn't stackable)

The Queue is there because it is basically a Deconstructor, and uses the same labels?

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
