### ISSUE TITLE
Probability on afflictions significantly lower than intended

### ISSUE THREAD

**Issue by Crabford** [Regalis11/Barotrauma#11240]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Probability on afflictions is much lower than expected. I encountered the bug while modding and ran a test. I made a custom item that inflicts amount="1" of a custom affliction to be used as a counter when used. The counter afflictions has no effect and has a strength change of 0. Running the test with probability="1.0", 100 samples : 100% proc rate, behaves as expected.
Running the test with probably="0.5", 10 trials of 100 samples each: Average result of all 10 samples was 25.5% proc rate, nowhere close to the expected 50%. After collecting more data and graphing it, I ended up with the formula 'y=x^(2)+0.01x', where 'x' was the intended probability and y was the observed probability.

### Reproduction steps

1. Load a sub in the sub editor and enter test mode.
2. Spawn in a reasonable sample size of energy drinks (80 in my case).
3. Drink all energy drinks while keeping track of how many times nausea is inflicted. Cure nausea with console commands as needed to keep better track.
4. Observe that number of times nausea is inflicted is significantly lower than the expected 25%.

### Bug prevalence

Happens whenever I work with probability on afflictions

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
