### ISSUE TITLE
Steady Tune shows outdated description

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11256]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Steady Tune shows the outdated description with the old effect, the actual effect is +100% Psychosis Resistance (Psychosis Immunity) for 60 seconds.
![image](https://user-images.githubusercontent.com/115734437/219004309-8b37abbc-f0f2-4d2f-929f-6d71c7e3af51.png)
Also, Psychosis Immunity uses the same name and description as Psychosis Resistance.
Psychosis Resistance:
![image](https://user-images.githubusercontent.com/115734437/219006420-bdda802c-33da-48e8-b210-595158f75d06.png)
Psychosis Immunity:
![image](https://user-images.githubusercontent.com/115734437/219006467-ae392452-9171-4ae0-b2ab-4d256afed897.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ddddcc6b83df31c9aacd32e2b69b15c07bc5f56

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
