### ISSUE TITLE
The localization of the CustomInterface in the editor is ignored

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#11257]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

All labels on the left side of the gui frame do not display localized text
![image](https://user-images.githubusercontent.com/73634685/219023175-c85a631e-a99d-48aa-a576-1dba89c7c943.png)
![image](https://user-images.githubusercontent.com/73634685/219023288-d91de378-e77f-40bb-8f5a-d5dd9f48cc31.png)

not only happening on my modding items
![image](https://user-images.githubusercontent.com/73634685/219023685-be1eb2f1-deaf-4678-bde9-a88d3416cbfe.png)
The labels on the left are "sonarbeacon.beaconactive" and "sonarbeacon.beaconsignal"

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Would you mind posting the xml of the item? Localization seems to be working in the vanilla items at least, so I suspect there might be some issue in the way your custom item is configured.

**Comment by zhu-rengong** [comment]
I have verified integrity of game files and disable all mods
The Label in the CustomInterface still cannot be localized in the **Submarine Editor**
Yes, right, it works fine in game but not sub-editor

**Comment by Regalis11** [comment]
Ahh, thank you for the clarification! I clearly read the report a bit too hastily and misunderstood the issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bef55d4c188cbcb772b997c2f6f839076358b234.

Internal note for testing: make sure changing the language doesn't permanently change the texts. I.e. if you save the sub in let's say German, then switch to English and reload the sub, the labels should be in English.
