### ISSUE TITLE
Night Vision- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1125]
Console command, which allows it's user to see in the dark as if it was lit by a close up lamp with no trouble. By default player has to be at least moderator to use this command on self and at least administrator to use it on others.

nightvision- Gives night vision to yourself when it's disabled and disables when it's enabled.

nightvision [player]- Same as above but with specified player.

nightvision off- Always disables night vision on self.

nightvision off [player]- Same as above but with specified player.

nightvision on- Always enables night vision on self.

nightvision on [player]- Same as above but with specified player.

**Comment by Regalis11** [comment]
How would this differ from the lighting command?

**Comment by rico6822** [comment]
Wait, there is already a command allowing to see in dark areas? My fail.
