### ISSUE TITLE
[Factions] Swarms spawning right next to pirate submarines in the middle of a fight

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11269]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After triggering a pirate submarine, a tiger thresher swarm spawned right next to it
In the previous session (we restarted the round after dying), a crawler swarm also spawned near the pirate sub, and proceeded to kill all of the pirates while our sub sank. Pirate AI was unable to deal with the swarm or even repair the sub on its own. Note that only 2 of 3 guns are manned in the clip

Swarm spawn / event manager should be paused if a pirate sub is triggered to avoid interference

https://user-images.githubusercontent.com/73229309/219797038-81dad3e6-5650-4fa0-ad3b-c79b408e8372.mp4

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Here you can see an inordinate amount of enemies in the fight:
Giant spinelings, 2 Molochs, Bone Thresher...

https://user-images.githubusercontent.com/73229309/219882686-587e9a79-0e1c-4c6c-aefa-839028e6f8e3.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cf404222438d39cf6e0e07a734f8088e071e7e1e (also included in the latest unstable now)
