### ISSUE TITLE
[Dev Version] Riot Shield Unavailability

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1126]
Alright I've been excited to test out the shield, but the first thing to be clear with is that it cannot be found on any default sub. Now this is where the bug part comes in. When I try to purchase the riot shield (haven't tried purchasing anything else yet) it does not get delivered to the submarine. I've checked all ballasts, airlocks, outposts, and the such. I simply did not get my riot shield. In addition when I try to spawn it through console commands (I've tried "giveitem riotshield inventory", "giveitem riot shield inventory", "givetime riot_shield inventory") none of them work. I simply cannot get my hands on it.

To reproduce the bug, try spawning the riot shield through console commands, buying it from the store, or searching for it in the default submarines.

Version: Closed Beta.

**Comment by NilanthAnimosus** [comment]
I have had additional cargo on the server correctly spawn riot shields fine. are you sure you have located the submarines cargo spawn? its at the very top left for the typoon, and in the outer airlock of one or two other default submarines.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this either, so my guess would be that you didn't look in the correct room. The cargo spawnpoints are admittedly not communicated very well in the vanilla submarines, I think we should add some labels to make them more obvious.

You should use "spawnitem "Riot Shield" inventory" to spawn it using the console.
