### ISSUE TITLE
[Factions/Endgame] Rescued Jacov Subra and then he disappears 

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11263]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In multiplayer campaign, immediately after rescuing Jacob Subra and leaving the abandoned outpost, I was forced to restart the server to allow for a friend to join (there was some issue with steam). After restarting the server, and loading back into the campaign, I was surprised to discover that Jacov Subra had vanished. After making it to an outpost with husk cultists, nothing happened. I believe that restarting likely messed up the progression of the husk ascension line.

### Reproduction steps

1. Rescue Subra from the abandoned outpost in a multiplayer campaign
2. leave the abandoned outpost
3. upon loading into the next level, return to lobby and shutdown the server
4. after starting the server back up and loading the campaign, Subra should have disappeared

(note: I have not attempted to recreate this error yet, but I am fairly confident that this should recreate the issue)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by StruggleDuck** [comment]
Below is the multiplayer campaign save data. I did attempt to use the triggerevent command to resolve the issue, but to no avail. as a result, it may have messed up some of the save info, but I am unsure. Hope this info helps.
[UNSTABLE GAMERS 1.zip](https://github.com/Regalis11/Barotrauma/files/10751957/UNSTABLE.GAMERS.1.zip)

**Comment by StruggleDuck** [comment]
Also one other thing, if there is any way for me to fix this issue in my current campaign using console or even editing the save I would love to know. I'd like to be able to continue playing this save with my friends and get to experience the husk ascention stuff without having to restart.

**Comment by Regalis11** [comment]
It seems this is actually how it's "supposed" to work: there is no mission to escort Subra to anywhere, completing the outpost mission is enough. You should be able to continue the event chain by talking to an Ecclesiast when you come across when.

This does seem very much like a bug though, so I think we'll need to add an escort mission after the rescue mission.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f6e81e8b6d6d9957b568064df6e56ab61233499b
