### ISSUE TITLE
Client error when loading game with custom sub: failed to start campaign round (campaign map not loaded yet)

### ISSUE THREAD

**Issue by ACMonkey** [Regalis11/Barotrauma#11261]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm running a dedicated Linux server (Ubuntu 22.04) which works fine for save files with standard ships, but when trying to load a save which includes a custom ship, the server starts the round but no-one is able to connect to it - the console pops up and says:
> Failed to start campaign round (campaign map not loaded yet).
Coroutine "Barotrauma.Networking.GameClient+\<StartGame\>d__109" has failed

(screenshot of issue)
![Barotrauma server connection failure 2023-02-15 222735](https://user-images.githubusercontent.com/62522497/219205810-891b1685-4650-49b5-80c9-c577f588b68b.png)

Running the same save files and mod files on my Windows laptop and hosting the server through the game works fine, so it's not clear exactly what's different between the two. The custom sub is a simple modification of a standard in-game sub (the Orca2) so I'm doubtful that the mod file is doing anything strange here.

Looking at the server logs, there's no indication that it's failed to load the save, all of the error messages are on the client. Interestingly, the client appears to repeatedly try and download the save file, ie the green bar in the screenshot below keeps filling up, disappearing then downloading again.
![Barotrauma repeated save download 2023-02-15 222802](https://user-images.githubusercontent.com/62522497/219206475-d39cb513-6304-42e9-bc2c-578d07359158.png)

I've attached the save files and the custom sub (Orca2.1) files [here](https://github.com/Regalis11/Barotrauma/files/10748813/Barotrauma.server.bug.zip), which should reproduce the issue

### Reproduction steps

1.) Install a custom sub
2.) Start a new multiplayer campaign
3.) Buy and switch to the custom sub in the campaign
4.) Install the save file + custom sub on a dedicated Linux server
5.) Try to connect to the server and load the campaign save file from a Windows PC

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Failed to start campaign round (campaign map not loaded yet).
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__109" has failed
```

**Comment by Regalis11** [comment]
Thank you for the report! 

It's hard to say for certain what caused this, but it seems like it could occur if sending the save file to the client takes too long. I was able to reproduce it by delaying the campaign save file transfers using console commands. Steps to repro for internal use:
1. Start a dedicated server, join it as a client
2. Enter `stallfiletransfers 2` (or more if that's not enough) in the server console
3. Try to start a new campaign. The client should throw the error message in a moment.
