### ISSUE TITLE
Bananas are eaten wierdly

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11274]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the newest of banana issues, apparently you eat bananas by holding them to your chest, that is news to me, so im reporting it, 
![image](https://user-images.githubusercontent.com/104232152/219805036-89fd3da7-3cc3-42cc-ba54-fc65f5131bdc.png)

### Reproduction steps

1.Eat that banana

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cbbd68ea8181f69599c2ae6bdb9baa8c1b730a16

**Comment by Rehexr** [comment]
Honestly not sure if this was fixed, still looks silly tbh
![image](https://user-images.githubusercontent.com/104232152/222904075-b6b19b16-1656-4e34-8d3f-eeac3373f4e4.png)

**Comment by Regalis11** [comment]
The fix is not included in any public build yet.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
