### ISSUE TITLE
Some material items missing OnBroken removal

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11276]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The following items won't remove themselves when broken like other items.
magnesium, organicfiber, fpgacircuit

While this does not affect vanilla gameplay, some mods relying on this feature needs to override them to function properly which may cause compatibility issue with other mods.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed magnesium and FPGA circuit in https://github.com/Regalis11/Barotrauma-development/commit/0b4309c56749d8bae058a9addeb3c84bd05c438f. Organic fiber seems to already have an OnBroken effect  that removes it though?

**Comment by BiffW** [comment]
Not on my side.
Here's its definition:
```
  <Item name="" identifier="organicfiber" category="Material" maxstacksize="8" Tags="smallitem" canbepicked="true" cargocontaineridentifier="metalcrate" scale="0.5" impactsoundtag="impact_soft">
    <PreferredContainer secondary="wreckstorage,abandonedstoragecab" minamount="1" maxamount="2" spawnprobability="0.05" />
    <PreferredContainer primary="medfabcab" />
    <Price baseprice="30">
      <Price storeidentifier="merchantoutpost" multiplier="1.3" minavailable="4" />
      <Price storeidentifier="merchantcity" multiplier="1.25" minavailable="8" />
      <Price storeidentifier="merchantresearch" minavailable="7" />
      <Price storeidentifier="merchantmilitary" multiplier="0.9" minavailable="3" />
      <Price storeidentifier="merchantmine" multiplier="0.9" minavailable="2" />
    </Price>
    <InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="64,768,64,64" />
    <Sprite texture="minerals.png" sourcerect="178,8,42,45" depth="0.55" origin="0.5,0.5" />
    <Body width="45" height="45" density="15" />
    <Holdable canBeCombined="true" removeOnCombined="true" slots="Any,RightHand,LeftHand" handle1="0,0" />
  </Item>
```

**Comment by Regalis11** [comment]
Ah, sorry, I think I must've been looking at _ballistic_ fiber instead, which for some reason does have the OnBroken effect. Added to organic fiber too in https://github.com/Regalis11/Barotrauma-development/commit/4496da65160c20a8e83326ca60edb99cf8c9c67e

**Comment by BiffW** [comment]
Incendium is missing OnBroken removal too.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8942f105e4133c7b135a5ab2c228266a57a0c230

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
