### ISSUE TITLE
Issues on monster encounters in the alien ruins

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11275]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Husks/Crawlers can spawn in ruins along guardians, this leads to situations where the guardian AI has problems:

Stuck, not moving

https://user-images.githubusercontent.com/73229309/219810996-80f2afa6-dc6f-433d-86e0-afcb7706e390.mp4

Another case was a husk chasing a guardian all the way outside the ruins, and the guardian failing to shoot at the husk. The guardian kept swimming back and forth trying to shoot the husk, the husk chased it, and both ended up 200m away from the ruin:

![image](https://user-images.githubusercontent.com/73229309/219811311-b7ff2bfa-3af0-48d8-b5e9-5a2245de8b44.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
It's intentional that they can confront each other. Actually there's specific events that set them up. But the issues should be fixed. Seems that in the first picture the harpoon is stuck somewhere outside the ruins. Seeing how the crawler moves, I'd say it's somehow stuck to it too. Can be tricky one. The second issue might be easier to repro (and fix).

**Comment by ubertpendragon** [comment]
> Seeing how the crawler moves, I'd say it's somehow stuck to it too. 

You're probably right. The rope has `snaponcollision="true"`, but it doesnt seem to work, at least not in ruins
![image](https://user-images.githubusercontent.com/73229309/220491828-1264d012-8b3a-4318-8c4e-83173ebcad2d.png)

I assume the extended rope in the OP is just a visual bug
