### ISSUE TITLE
[Factions] The game warns you of ambushes before encountering enemy subs

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11271]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At the start of the session, the game warns you about the ambush, which makes it not an ambush
This wasn't a mission and separatists appear on radar so this is definitely supposed to be a surprise, given away by the prompt at the start

![image](https://user-images.githubusercontent.com/73229309/219797847-d58c9e54-b9c7-4c10-8b0f-4d54b134fd2b.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb513e8369430c9288b4eae0efee846a996db079

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
