### ISSUE TITLE
[Factions] Pirates fail to repair leaks

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11273]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pirates just swim around failing to repair leaks around the submarine

Could be caused by fear of crush depth; one of the pirates died in engine room from crush depth

Excuse the poor video quality:

https://user-images.githubusercontent.com/73229309/219804973-3ddfbff0-1528-45a2-aca9-942a7ab08df1.mp4

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Potentially addressed by https://github.com/Regalis11/Barotrauma-development/pull/3990 (spawns abyss suits in the sub instead of normal ones in later levels)

**Comment by Regalis11** [comment]
Tested & merged
