### ISSUE TITLE
Editor - remap Use to Mouse 3/4/5 does not work

### ISSUE THREAD

**Issue by DarKcyde0** [Regalis11/Barotrauma#11270]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Remap the use key to a mouse button.  E.g. Mouse 3, 4, or 5.

In campaign, this works fine.

In the sub editor, the mouse is unable to Use anything.  Remapping back to a keyboard key (E) works fine in the editor.

### Reproduction steps

1.  Remap Use key to a mouse key.
2. Attempt to use items in Sub editor.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aeb0e27835817ec8d6f8b37c3d29ca88e7f6b94e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
