### ISSUE TITLE
[1.0.2.0] Double clicking the Beacon Active button on a Sonar Beacon causes it to rapidly enable and disable itself

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11285]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This issue occurred on a multiplayer P2P save. I do not recall what game version this save was made in.

See video and reproduction steps for details. 

https://user-images.githubusercontent.com/105495756/219979346-c10705d5-968c-4b51-b5ca-9ef1c1ab4751.mp4

_Figure 1. Litho's perspective encountering this bug (video ends 15 seconds in, ignore extended video playback)._

### Reproduction steps

1. Hold a sonar monitor
2. Rapidly double click the "Beacon Active" button
3. If steps fail, repeat
4. Observe how the active state turns itself on and off at a rapid speed

### Bug prevalence

Happens regularly

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7e1dac3c2bc0fdfe3e7f3332ebfe64c680b3876

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
