### ISSUE TITLE
[1.0] Welding Tool visual bug

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11284]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon using the welding tool, a strange light materialises from the welding fuel tank area. Additionally, two welding flames are produced by the gun. The two flames form into one large flame, however one of the flames appears below the welding tool's nozzle (which doesn't make sense as to why it appears here).

![image](https://user-images.githubusercontent.com/105495756/219978858-b3a422a8-d0fa-4484-b29a-2612c4d4894f.png)
_Figure 1. Image of weird light and double welding tool flame._

https://user-images.githubusercontent.com/105495756/219978918-5484609e-886b-402b-9b20-980413b1be90.mp4

_Figure 2. Video of visual bug in action._

### Bug prevalence

Happens regularly

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
>Additionally, two welding flames are produced by the gun

It's just one flame, the particle is just shaped like that.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/060ea1494c2bbb238431e95206340ecf8fbe9cec

**Comment by Regalis11** [comment]
Plasma cutter also had a similarly strange-looking light component, addressed in https://github.com/Regalis11/Barotrauma-development/commit/d45367097ad0e9ace85168e8f837f329292f0414

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
