### ISSUE TITLE
[Factions] Husk Symbiote Still consuming oxygen while using diving suit

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11288]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After completing the husk missions and getting the husk symbiote, I noticed that I was still using oxygen in diving suits. Note I only tested with exosuit and slipsuit.

### Reproduction steps

1. Get husk symbiote
2. Out on diving suit with oxygen tank
3. Watch as you slowly consume air

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I wouldn't consider this a bug: there's no indication in the game that you don't need to breathe when you get a husk infection, just that you don't need `air`.
