### ISSUE TITLE
Sub editor Ctrl+A does not select wires

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11291]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the sub editor, hitting ctrl + A to select all selects everything except the wires, even if they are visible. The only way to properly select everything including wires is to zoom all the way out and draw a selection box around the entire sub, which is quite inconvenient.

### Reproduction steps

1. Load submarine file in sub editor
2. Press Ctrl + A 
3. Look at wires to see if they are selected.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f50a124ca53938f54c682bb2227b0046620b2cc2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
