### ISSUE TITLE
Spamming the spacebar nearby walls and shells as client will phase the player through it.

### ISSUE THREAD

**Issue by DuckY-Y** [Regalis11/Barotrauma#11295]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've noticed on the current campaign I'm in that spamming spacebar launches the character in certain direction in relation to the rotation of the player with some force. Using this force while submerged will result in a speed comparable to swimming normally in a Combat Diving Suit, but in a hull with air it will result in erratic movements in random directions.
Abusing this "feature" nearby a outerhull results in the player teleporting through it and being placed outside the submarine.

This has been reproduced by multiple people in the campaign.
So far I've only noticed this placing characters above the original room.

Being under the influence of movement enhancing afflictions and/or talents may have an increasing effect on the likeliness of this happening to the character.

If needed I'll make a video.

### Reproduction steps

1. Join a server.
2. Enter a relatively small room, which is on the outerpart of the top of the submarine.
3. Spam the spacebar ((while holding down a certain directional movement key)(not sure if this increases the likeliness of it happening as it has been done without on multiple occasions).
4. Be crushed by pressure.

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thanks for the report. A video would make it easier to repro, as the steps are not that exact.

**Comment by DuckY-Y** [comment]
https://user-images.githubusercontent.com/84920066/221359445-571a1883-bef5-4a5b-a698-06d101ad1107.mp4
