### ISSUE TITLE
Putting away a harpoon before it reels in briefly causes a floating rope

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11298]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While a minor issue, its a bit of an odd issue for sure, shooting a harpoon, and immediately putting away the harpoon gun, the rope will simply float and then dissapear infront of your face, probably because it continues to get drawn after putting away the harpoon gun

https://user-images.githubusercontent.com/104232152/220170830-89a488ad-ec57-4960-b052-f0c396a49b5d.mp4

Lets hope the compression doesnt make it too hard to see

### Reproduction steps

1.Shoot a harpoon
2.Unequip the harpoon gun immedialely (best to use numbered hotkeys)
3.Notice the quickly dissapearing floating rope in front of your face

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Hmm, I don't actually quite see the problem here. I agree it looks somewhat odd, but what would the alternative be? Making the rope vanish into thin air, as opposed to "reeling in" like this?

**Comment by Rehexr** [comment]
I suppose there isnt really any intuitive solutions to this, so fair enough
