### ISSUE TITLE
Plants have become very unbalanced since rework.

### ISSUE THREAD

**Issue by DuckY-Y** [Regalis11/Barotrauma#11296]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since the removal of plants from caves, they've become somewhat impossible to come by in your normal campaign.
Due to the inability to locate the plants using talents and/or equipment combined with their scarcity results in next to no incounters with the entities.
(In fact I've yet to come across a single one of the fuckers out in the wild.)

Before the rework we players could get a reliable supply of medical items, but now I as a medic often find myself having to spawn in items in order to even function as one, the low availability of morphine and opium on stations also contributes to a lack of resources.

On the higher difficulties and dangerous missions such as for example:
.>50% difficulty together with the clearing of a ruin and a nest. 
This combination will often deplete the medical supplies (even with the usage of Tonic Liquid to make the most of em) faster than we can resupply them.

### Reproduction steps

1. Play the game.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Some cave screenshots:

Only mushrooms spawn in caves, not other plants which is why they seem scarce. 
On the other hand there is a LOT of them, enough ethanol for the entire campaign in a single cave

![image](https://user-images.githubusercontent.com/73229309/220161518-a4c4453f-0250-416d-ba8d-9c8cac7bf179.png)

**Comment by DuckY-Y** [comment]
Yeah ok there is definitely a bit too much ethanol, now in the endgame of the campaign I'm in we've got like 2 and half crates of ethanol because we've got nothing to spend it on besides selling it.
The others on the other hand are far to scarce.

**Comment by Vykn** [comment]
> "Before the rework we players could get a reliable supply of medical items, but now I as a medic often find myself having to spawn in items in order to even function as one, the low availability of morphine and opium on stations also contributes to a lack of resources."

Barotrauma is a resource management game. You cannot expect to have every resource easily available to you without effort.

I think plants should be brought back to caves (albeit with a lower spawn rate than previously) but this is not a case of medicine being too difficult to come by. There are most definitely enough medicines in the stores to keep well stocked. You can acquire 12 morphine from literally every single station. If a crew is burning through medicine faster than they can purchase it, then that isn't an issue of the game's balance; it's an indication that the crew should be using their resources more efficiently and sparingly.

As an aside, shrooms only spawn in caves in the aphotic plateau, not in other biomes. So the over-abundance isn't exactly as much of a problem.

**Comment by DuckY-Y** [comment]
Ok, my fault for not including a certain part, the campaign I'm currently in includes Dynamic Europa, meaning that medical items are never for sale considering that we never come across hospitals....

Otherwise like you said, it would be easy to stock up on medical supplies.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
