### ISSUE TITLE
map UI opens at end of campaign

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11299]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when reaching the end of the final level, the map UI opens for a few moments

https://user-images.githubusercontent.com/5103517/220171345-9c2e4e5f-73c6-4c27-841b-456c3d5ed6a1.mp4

### Reproduction steps

1. reach the end of the final level 

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment]
The map opening part is intentional, although it should not be skippable and meant to show your entire way

**Comment by Regalis11** [comment]
Since the whole ending will be redone in the next update in a way that this can't happen, we won't be addressing this.
