### ISSUE TITLE
Captain's pipe and Cigar usage is inconsistent from the other consumables

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#11304]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Both Captain's pipe and Cigar requires both LMB and RMB to be pressed in order to use them while the rest of the consumables only requires RMB. 

### Reproduction steps

1. Equip Captain's pipe
2. Place Pipe tobacco into the pipe
3. Notice that only pressing RMB doesn't use up the Pipe tobacco

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7a258547a1659d228cf16fc40acba9ee84ddb4ba

**Comment by itchyOwl** [comment]
Tested: works consistently now.

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing.
