### ISSUE TITLE
[Dev] Husk Infection works on all creatures, including husks

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1130]
I've being doing tests with husks and I noticed the husk affliction will apply on all creatures. This causes the infected creature to eventually be killed and the game failing to spawn a proper humanhusk from it and removing the corpse from existence. This happens with all creatures but humanhuks, who will raise again after dying while infected.

**Comment by ChikoEduardo** [comment]
Oh, I'd like to add another issue with husks. They attack humanhusks since they are kinda like a different species, code-wise. Adding them to the targetpriority table and set them to ignore them fixed it for me.

**Comment by itchyOwl** [comment]
Fixed in 225cff0 and 6898345 (husk-refactor branch).
