### ISSUE TITLE
Hammerheads, Endworm and Charybdis stun is way shorter than it should

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11302]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hammerheads, Endworm and Charybdis structure attack has a statuseffect creates an explosion that inflicts stun

However all of them are missing `disabledeltatime="true"` (which the Moloch is using) on their statuseffect, which means they only stun for a fraction of what they should. 
Both Moloch and Endworm have 7.5 stun (which may or may not be 7.5 seconds), but Moloch has disabledeltatime whild Endworm doesnt.

Discovered while talking big creatures in https://github.com/Regalis11/Barotrauma/discussions/11301

```xml

     <StatusEffect type="OnUse" target="This">
        <Explosion ignorecover="true" onlyinside="true" range="900" force="1" flames="false" smoke="false" shockwave="false" sparks="false" flash="false" underwaterbubble="false" camerashake="0" playtinnitus="false" structuredamage="600" itemdamage="0" applyFireEffects="false">
          <Affliction identifier="stun" strength="7.5" probability="1" />
        </Explosion>
        <sound file="Content/Characters/Endworm/ENDWORM_attack2.ogg" range="30000" volume="1" dontmuffle="True" selectionmode="random"/>
        <sound file="Content/Characters/Endworm/ENDWORM_attack3.ogg" range="30000" volume="1" dontmuffle="True" />
      </StatusEffect>
      
```

### Version

0.21.6.0

**Comment by itchyOwl** [comment]
I don't think any of those definitions should have disabledeltatime="true". Moloch only seems to have it in the effect of an attack that targets the sub, and it doesn't have any effect on the stun duration, which is defined inside the explosion block. It's probably just a leftover, but doesn't seem to matter there. All the stun durations are based on testing, so they should be what was intended: a fraction, not 7.5 seconds.

**Comment by ubertpendragon** [comment]
Understood, I was mislead by the deceitful wiki team

Although you might want to take a second look at these enemies considering how they're simply not capable of hurting let alone killing a crew
