### ISSUE TITLE
Bots can pick up non-pickable items

### ISSUE THREAD

**Issue by gausebeck** [Regalis11/Barotrauma#11316]
When marking an item as non-pickable (uncheck "Can Be Picked") in the editor, bots can still pick it up, and in fact will automatically clean it up like other items.  To reproduce, add any item to a sub with "Can Be Picked" disabled, enter test mode, and then direct a bot to clean up the item.

The use case where this matters for me is that I was trying to make a wall-mounted logbook that can be interacted with but not removed.  However, bots pick it up off the wall and spoil that plan.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
