### ISSUE TITLE
Alarm buzzer activates without a signal.

### ISSUE THREAD

**Issue by Rothlan284** [Regalis11/Barotrauma#11318]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The alarm buzzer buzzes endlessly without a wire being connected to it in either slot. It continues to buzz regardless of having a signal of 1 or 0 as well.

The expected result is that the buzzer will activate if "Set_State" is on a signal of 1, which gets sent when the reactor is less than or equal to 11% of fuel.

![image](https://user-images.githubusercontent.com/112382871/220921735-10cf2731-815e-47a7-a483-5d9eee1b0e3a.png)

### Reproduction steps

1. Start a campaign
2. Wire a memory components "Signal_out" on a value of 11 to the greater components "Signal_in_1"
3. Wire the reactors "Fuel_percentage_left" to the Greater Components "Signal_in_2"
4. Wire the Greater components "Signal_out" output at a value of 1 to the buzzers "Set_state"
5. Test that the Greater Component sends a signal of 1 when the reactor is at or below 11% fuel percentage.
6. If it works, save and quit the game.
7. Go back into the same save and see an indefinitely buzzing buzzer
8. Remove the cable to the buzzer and it buzzes forever unless you remove it and re-wire it.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I would suspect that the issue is the false outpost of the greater component. If it's not set to 0, the component will send out nothing when the reactor is above 11%, meaning all this circuit does is turning the alarm on when low on fuel, but never turning it off.
