### ISSUE TITLE
Can grab ladder while in bed

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11310]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While in a bed it is possible to grab onto ladders, which results in some very odd behaviour.

### Reproduction steps

1. In the submarine editor, place a ladder on top of a bed
2. Lie down in the bed and then use w/s as if you were trying to move up and down the ladder

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a1df0d49590df0927bf842f716dd5a3e4bfe21b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
