### ISSUE TITLE
[1.0] Mudraptor Egg in the recipe for the Petraptor Egg has repeated name

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11323]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When hovering over the Mudraptor Egg in the Petraptor Egg crafting recipe, it states "Mudraptor Egg, Mudraptor Egg, Mudraptor Egg".

![image](https://user-images.githubusercontent.com/105495756/221019927-d3cc49c0-f61d-479d-b73a-c1b400ff1001.png)

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.3.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
https://github.com/Regalis11/Barotrauma/issues/10794

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/450ab49d4697ad3139d53776bf889c8c3e103691

**Comment by ubertpendragon** [comment]
`450ab49d46: Fabricator input slot tooltips don't show duplicate item names when the item can be crafted from multiple different items with the same name (e.g. petraptor egg can be crafted from 3 different egg items, all called "mudraptor egg"). Regalis11/Barotrauma#11323`

Is there any way to prioritize which sprite/name is displayed in the fabrication recipe?

It would allow to recycle any coilgun box into any other, unfortunately the UI looks like this:

![image](https://user-images.githubusercontent.com/73229309/221189284-58d10e67-3df4-41a3-a131-0f319661bfca.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
