### ISSUE TITLE
Enabling freecam in a multiplayer lobby with one player force returns the session to the menu

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11324]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the freecam command is used in a multiplayer lobby with only 1 player, the session will automatically close and return the player to the lobby menu.

This is problematic as many tests are done in 1 person multiplayer lobbies to see what the issue is in a real game setting. Personally, ~98% of my testing and reporting is done through this method, and the freecam tool is a wonderful way of capturing birds-eye screenshots of potential issues. This existing issue makes this impossible without another player.

### Reproduction steps

1. Host a server
2. Start a campaign save
3. Open the console (F3 on windows, Fn + F3 on Mac) and type "enablecheats" followed by "freecam"
4. Observe how after a short delay, the session ends and returns to the lobby

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/72b60ce4f4c28b6631ec3e35decbd4556859b672

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
