### ISSUE TITLE
[1.0] Revenge Squad triggers on player disconnect

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11321]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a player with the Revenge Squad talent disconnects from the lobby, the effect triggers. This is problematic as the player is not physically dead, they've left the server. The talent perk showing for disconnected players may lead other players still in the server to believe the player has died (which is not the case). 

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
