### ISSUE TITLE
[1.0] Researcher Transport Event mission's location is an abandoned outpost

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11328]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Could be intentional, but the event civilian transport mission allows the destination to be an abandoned outpost instead of exclusively an outpost which isn't abandoned, despite the mission description specifying an outpost. Additionally, a coalition outpost is available (though difficult to identify in the screenshot provided). 

![image](https://user-images.githubusercontent.com/105495756/221034289-7f79e658-27de-4fdc-a1a5-c80c0d82cbf7.png)

### Bug prevalence

Just once

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/959ae640560e01f6a0c3a4a61c28bc4035565490

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
