### ISSUE TITLE
Bots fail to go up the ladder, instead dropping down before reaching the next floor

### ISSUE THREAD

**Issue by NaturalBornCamper** [Regalis11/Barotrauma#11327]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots jump off ladder before reaching the waypoint, falling back all the way down. [Submarine file here](https://www.dropbox.com/s/qql78vxz5ualevv/Humpback_bots_fall_down_ladder.sub?dl=0), here are the waypoints:
![image](https://user-images.githubusercontent.com/1697306/221034231-72543835-3ee6-4c3e-8eda-1484281e6c07.png)

Here are the waypoints I tried in the extremes (next waypoint all the way up to the ceiling, hoping they would release the ladder up there but they don't):
![image](https://user-images.githubusercontent.com/1697306/221034427-543dc0f5-acbb-4ae5-b9f5-fdbba392154b.png)

Some things I tried:

- Setting a waypoint on the trapdoor
- Put a platform so they can drop on it, but it's pointless as they let go when their knee hits the top of the hatch
- Setting the top waypoint even higher, but then they get stuck in the ceiling.. no halfway: drop or get in the ceiling
- Making the hulls overlap each other
- Removing all background objects just in case
- Removing all wiring from the hatches
- Regenerating waypoints
- Removing the hatch (just a platform there)
- Making the had opening tighter (so characters can only fit tightly)

Here is a video of the issue happening:

https://user-images.githubusercontent.com/1697306/221034891-d3e5eaa9-4a3c-4c28-ba5a-abe8a35daa44.mp4

Not sure if it counts as "Happened while using mods" as the game is vanilla, just customized the Humpback for singleplayer gaming.

### Reproduction steps

1. Load my humpback extracted from my game campaign in the sub editor
2. Control bots and make them go at the bottom of the ladder where the bottom airlock is
3. EDIT: Make sure they have no orders (Idle)
5. Bots will soon try to get out of the "no stay zone" by moving left or going up the ladder
6. If they go up the ladder, they drop back down instead of going up

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I gave this a try in our latest dev build, and it seems the bots can use the ladders with no issues. So I think we might have fixed this issue, but the fixes aren't yet out in the public version (couldn't find a relevant ticket/fix on a quick look, but maybe @itchyOwl knows more)? 

But until the next update is out, I think it might also be possible to work around the issue by making the ladders extend a bit further up.

**Comment by NaturalBornCamper** [comment]
Yeah if you look on my second screenshot, I tried extending the ladders all the way to the ceiling ;)

That is good news however, can't wait for the next release now as I can't play my campaign anymore since bots are useless. No idea what change you guys made that fixed it but good work! Can't wait!!!

**Comment by itchyOwl** [comment]
I don't think anything has been done to it, because it's something that happens occasionally. I've now encountered similar issues a couple of times, but haven't been debugging them. Will be looking into them later. Adjusting the waypoints helps. For example haven't had the issue on Humpback, but Herja seems to suffer from it.

**Comment by itchyOwl** [comment]
Couldn't repro the issue using the sub provided above in the latest version of the game. Need to test an older version.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
