### ISSUE TITLE
[1.0] Reputation and Radiation Sickness: How specific DOT damage tanks your status with a faction

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11326]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I will use Bleeding as my example as to why Radiation Sickness' current behaviour is problematic.

If a player stabs an outpost NPC and causes bleeding, they will lose reputation and get attacked by guards. Returning to the submarine resets this behaviour and everyone moves on with their lives. 

Radiation sickness, however, does not do this. If a player causes radiation sickness to an outpost NPC using the RFA, there will be the same initial reputation loss but that reputation loss is now permanent. As in, it continues to tick down in -1 increments until the NPC dies. Additionally, outpost guards will perma-lock focus on the player who attacked the NPC. Outpost medics cannot heal radiation sickness.

This is an issue as a single misfire of the RFA can cause serious reputational harm, the loss of NPC life, and prevent the player from interacting with shops or guards due to ongoing "situations". Whilst I recognise misfiring a charged weapon is quite unlikely, I would like to add that this issue only came to my attention **because** of a misfired RFA.

### Reproduction steps

1. Start a new campaign
2. Enable cheats using the console (F3 for windows, Fn + F3 for Mac) and spawn in a Rapid Fissile Accelerator with fuel rods
3. Shoot an outpost NPC and retreat into your submarine
4. Observe how your reputation continues to decrease even though you are not doing anything

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d0e559cbbd6a7c125a82cf7338fd25e0de813b92

**Comment by Rokvach** [comment]
This doesn't seem to be working or I'm misunderstanding something, there doesn't seem to be any cap to the reputation loss as seen on the first screenshot

On the second screenshot the reputation seems to have reset when I left the outpost

![image](https://user-images.githubusercontent.com/7299826/235042291-f4a02d48-19c5-47ee-9e7d-2656091cd190.png)

![image](https://user-images.githubusercontent.com/7299826/235042406-a669bb70-0684-4424-b34f-0b75b7538d78.png)

**Comment by Regalis11** [comment]
To me it looks like it's working correctly in the screenshots: the limit is 20, and the reputation doesn't seem to have reset in the pic (it's -5 in both)?

**Comment by Rokvach** [comment]
Nvm misunderstood couple of this, working correctly. Can be merged and closed.
