### ISSUE TITLE
[1.0] Separatist Captain Hat layering issues with PUCS suit

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11335]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The issue here is very subtle, so I did my best to take the same image with the same dimensions. It's clearly highlighted when flashing the images together (having them side by side and clicking an arrow to move to the next image). The discord message link attached will bring you to my first report of this issue in the factions test chat on the Undertow Discord server. Here you will be able to quickly compare the two images to see the issue. https://discord.com/channels/103209684680323072/540532000860143616/1076259173337153586

The Separatist Captain Hat causes layering issues when worn with a PUCS suit and presumably all other diving suits. Not only does it cause incorrect masking (which creates a "halo" above the player), the bandana comes out of the neck piece of the diving suit helmet. This whole issue is difficult to identify in an image, so I attempted to place my character against a solid white background to highlight the "halo".

![image](https://user-images.githubusercontent.com/105495756/221044732-9b21db97-87e3-4c29-881f-fe4e9a6e28dc.png)
_Figure 1. PUCS + Separatist Captain Hat._

![image](https://user-images.githubusercontent.com/105495756/221044759-ca0c89e5-1d8f-4968-80b4-50f5a5cda9d6.png)
_Figure 2. PUCS without Separatist Captain Hat._

![image](https://user-images.githubusercontent.com/105495756/221045370-421cd2fc-ee11-4b43-b5e1-a609243a2790.png)
_Figure 3. My (poor) attempt to highlight the specific areas of issue. Notice the floating object above the player's head and the abnormally dark "collar" around the diving suit helmet._

### Reproduction steps

1. Equip the Separatist Captain Hat
2. Equip a PUCS suit
3. Observe how the hat partially clips through the diving suit helmet, whilst also giving you a "halo" of missing sprite.

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/25ee626c50349cdc6df2dd990d59dd84a9d86fbe

**Comment by Jasontti** [comment]
Tested.
Otherwise fixed, but there seems to be small sliver from back of the head visible.
Issue not present in other diving suits, they are tiny bit taller than PUCS.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/939d4c7a-e8f8-4ab8-ba0c-326e5766aa1b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/31b1a8aead0ac05d205599f5c4ff08b3050cd04a

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
