### ISSUE TITLE
[1.0] Pets trigger "Hostiles in x!" command 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11334]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The only creature in the room with me here is the Psilotoad. Despite this, the intruders quick command (accessible via the headset) is prompting me to use it. This implies that there is a hostile creature in the same hull as me, which is impossible as the only creature with me is the Psilotoad (a non-hostile creature unless the owner is attacked, which they were not).

![image](https://user-images.githubusercontent.com/105495756/221044122-89af5bf5-d950-46dd-bdc9-03e1a926cf0d.png)

### Reproduction steps

1. Hatch a pet
2. Observe how the "intruders" command is now flashing

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by StruggleDuck** [comment]
Probably related to this: #11196

**Comment by Regalis11** [comment]
I unfortunately could not get this to happen at my end. :/ Tested in single player and multiplayer, and with psilotoads hatched from and egg and directly with the console command "`spawn psilotoad`".
![image](https://user-images.githubusercontent.com/14351070/221209094-63c264dc-cdda-4865-8d94-59f5c57d4435.png)
![image](https://user-images.githubusercontent.com/14351070/221209492-a201b10c-934f-4a3a-9674-8bc68ea9f4c7.png)

**Comment by Wheatley1001** [comment]
Reproduced the issue with the Petraptor. I have a theory as to what the issue is:
When a player attacks the owner of a pet, the pet is coded to be hostile towards the aggressor. Whilst I never personally witnessed any pets attacking players, I did witness players attacking players a _lot_. This could potentially trigger the "Intruders in x!" command as the pet is now a hostile creature, albeit temporarily. I imagine since the command likely only checks to see if the hostile creature is alive or not (rather than if it's still aggressive or not), it ends up never clearing the command once the pet returns to a peaceful state. 
![image](https://user-images.githubusercontent.com/105495756/222258543-5181cd5e-2315-46b2-9952-4cc326a3f030.png)

**Comment by Regalis11** [comment]
If that is the case, I wouldn't consider this a bug. If the pet has turned hostile, I think the report should flash.

**Comment by Wheatley1002** [comment]
Even after the pet is no longer hostile? The report flash doesn't go away once the pet stops being hostile, which can lead to players walking into hulls containing perfectly peaceful Psilotoads and being told there's an intruder (that's how I first discovered the issue).
