### ISSUE TITLE
[1.0] Separatists and Coalition both claim the same outpost node

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11331]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The image below shows the event text next to the outpost node stating the Coalition has claimed the location and established a habitation outpost, whilst the outpost itself is a Separatist Habitation Outpost.

![image](https://user-images.githubusercontent.com/105495756/221037468-efb57647-8311-4c25-9c05-76cbeb01ae96.png)

### Bug prevalence

Just once

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I still could not reproduce the issue 
![image](https://user-images.githubusercontent.com/14351070/231128821-ad6ed305-dc2c-4967-b4bf-98bc861025b6.png)

**Comment by Regalis11** [comment]
Insufficient information to diagnose the issue.
