### ISSUE TITLE
Large weapons clip bed sprite when worn on back and player is in a bed

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11332]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a player enters a bed with a large weapon on their back (in the toolbelt slot), the gun will clip in front of the bed frame whilst the rest of the body is behind it. 

Images below detail this issue.

NOTE: Whilst this issue was discovered on a custom sub, I tested it again on the Typhon 2 and found the same results. 

![image](https://user-images.githubusercontent.com/105495756/221039668-681988d1-cba2-4961-8469-03e316e7ae66.png)
_Figure 1. Player with an AutoShotgun on their back whilst holding a riot shield sleeping in a bed._

![image](https://user-images.githubusercontent.com/105495756/221039678-2adb7c32-f634-48c0-b5f8-c9d8ef14fa8e.png)
_Figure 2. Player with an Assault Rifle on their back whilst sleeping in a bed._

![image](https://user-images.githubusercontent.com/105495756/221039695-8a70f150-aa38-49aa-b331-300f0c818e22.png)
_Figure 3. Player with an Assault Rifle on their back for reference._

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f95d5784944fb039fd682f5fae4fd30b688300b9

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
