### ISSUE TITLE
[1.0] Coalition prisoner transport sends separatist prisoners to a separatist outpost

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11338]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Coalition outposts can give prisoner transport missions with the destination of separatist outposts. This is problematic as the coalition are sending their separatist prisoners to the separatists, with the text implying that the coalition own a high-security prison in separatist controlled territory.

![image](https://user-images.githubusercontent.com/105495756/221049691-87669e6f-abf6-4916-aecd-57f3185bab82.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Part of the "not very coherent" transport missions: 

https://github.com/Regalis11/Barotrauma/issues/7497

https://github.com/Regalis11/Barotrauma/issues/11132

**Comment by Regalis11** [comment]
Yeah, this is essentially the same issue as https://github.com/Regalis11/Barotrauma/issues/7497: if there's not suitable location available, the destination can end up being something that doesn't make that much sense. Closing as a duplicate.
