### ISSUE TITLE
[1.0] Outpost missions prevent regular missions from showing at the end round screen

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11346]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you visit an outpost which has an outpost specific mission, such as Jailbreak, completing the mission will prevent any chosen missions for the next round to show at the end of round screen. It will only show the completed missions rather than the missions you have chosen to play in the next round. 

![image](https://user-images.githubusercontent.com/105495756/221049470-b76ec525-391e-419a-a01e-2dcd4edce713.png)
_Figure 1. Image showing end of round screen. Note the completed jailbreak mission being the only icon present on screen._

![image](https://user-images.githubusercontent.com/105495756/221049480-e7df87e0-7234-4f79-a821-3d297d84b738.png)
_Figure 2. Image showing selected missions for the current round. These were hidden in the previous menu._

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.0.3.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f79ac83ede13991862ee399ceb85943e86b3f79

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
