### ISSUE TITLE
[1.0] Faction-specific passageway spawned missing a lock

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11341]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

We noticed that one of the faction controlled passageways didn't spawn with a lock icon, meaning we were able to transit through it without speaking with a watchman NPC to unlock the gateway. To make matters worse, the faction who owned this gateway had an openly hostile reputation status with us, meaning they attacked us the moment we entered their outpost.

SAVE FILES:

[Season 3 Episode 2 Save.zip](https://github.com/Regalis11/Barotrauma/files/10819858/Season.3.Episode.2.Save.zip) - The previous session, possibly could be useful in diagnosing the issue before it gets uncovered.

[Season 3 Episode 3 Save.zip](https://github.com/Regalis11/Barotrauma/files/10819853/Season.3.Episode.3.Save.zip) - Roughly when the issue was first encountered.

[Season 3 Episode 4 Save.zip](https://github.com/Regalis11/Barotrauma/files/10819867/Season.3.Episode.4.Save.zip) - The session after this issue was reported, unsure if this is necessary but attaching it to ensure a save which has us passed the point is included.

![image](https://user-images.githubusercontent.com/105495756/221033229-0c068232-f50b-4c42-a58f-0fec24242c06.png)
_Figure 1. Image showing Separatist controlled gateway segment missing a lock, despite players being physically unable to ever interact with the outpost to remove the lock._

![image](https://user-images.githubusercontent.com/105495756/221033280-74254524-860f-4fd1-96aa-c1ac91e820c0.png)
_Figure 2. Image showing reputation with Separatists to prove that even if the crew wanted to, they would be unable to unlock the passageway._

![image](https://user-images.githubusercontent.com/105495756/221033292-ec75a74e-4251-4bf3-8602-5d927620d3b9.png)
_Figure 3. Image showing players at the connecting outpost able to transport themselves through the gateway and complete missions at the same time._

For reference, yes. We were successful in crossing the gateway and did not experience any errors, crashes, or issues during, before, or after the journey.

### Bug prevalence

Just once

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
For testing: the map seed is IpMXLtvr

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7c4fa91bb8b134f857afa4dc65b7c964fd9e33d9

**Comment by Rokvach** [comment]
Tested, working correctly. Need to do a checkup once 1.1 gets merged to this PR as its couple months old now
![image](https://user-images.githubusercontent.com/7299826/235038649-2acc6570-bcd3-43d8-a5ab-cb986ff56476.png)
