### ISSUE TITLE
Mission pings on the navigation terminal lie to you

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11345]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is not a new issue and has, in fact, existed for as long as I can remember. If a ticket already exists, I could not find it.

This issue typically occurs in multiplayer settings in P2P hosted servers. I do not know if this can be reproduced in singleplayer.

In any mission which has a ping on the navigation terminal, the distance shown blatantly lies to you. Missions which include creature targets, such as hunting grounds or swarm missions, are particularly prone to this issue. However, I have seen Clear Ruins missions suffer from this issue severely; the navigation terminal ping stated the ruins were 1400 meters away from the submarine's current position, before suddenly deciding that they were actually 345 meters away hidden within a wall. 

Below are images which capture the blatant lies fed to captains and observers by the navigation terminal. This lie led to the death of a crewmate who was unable to prepare for the oncoming Endworm, as everyone involved believed it was a considerable distance away. It is important to note that the handheld sonar monitor apparently does not suffer this issue.

![image](https://user-images.githubusercontent.com/105495756/221050234-1275b1cb-8a63-43f6-9fff-a4a1fecf0ab4.png)
_Figure 1. Image showing the reported distance between the player's submarine and the target of the Hunting Grounds mission. Note that the submarine is travelling at a constant speed._

![image](https://user-images.githubusercontent.com/105495756/221050244-226a89d3-151f-4309-903c-84ddb3117d97.png)
_Figure 2. Image showing the distance between the player's submarine and the target of the Hunting Grounds mission having increased at the same speed the submarine is travelling. Note that if the abyssal creature was moving away from the submarine, it would do so at a reduced speed as it needs to account for the movement of the submarine in addition to the abyssal creature. Instead, the target is a static ping on the navigation terminal which increases in distance as the submarine gets closer._

### Bug prevalence

Happens regularly

### Version

Other

### -

1.0.3.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

When it comes to monster missions, this is intentional. Until you get close to the monster, it only shows an approximate position (or rather, a position randomly offset from the monster). The idea is specifically to allow surprises and to make it a little more difficult to prepare for the fight.

> However, I have seen Clear Ruins missions suffer from this issue severely; the navigation terminal ping stated the ruins were 1400 meters away from the submarine's current position, before suddenly deciding that they were actually 345 meters away hidden within a wall.

This seems like a bug though. The distance is calculated by finding the shortest path through the level, and it sounds like there was some issue in the pathfinding that prevented it from finding an optimal route until you got close to the ruin. I think we need a save file or a seed to be able to reproduce this though.

**Comment by Wheatley1001** [comment]
I have several varying instances of this happening which I'll be providing as much detail, images, and save files as humanly possible. This is going to be big, so I apologise in advance for the wall of text.

### Hunting Grounds Target Simply Didn't Exist
We had a Hunting Grounds mission and for the most part everything was normal. We started rapidly approaching the target marked by the navigation terminal, until the moment we approached it. The ping stated the target was 23m away from us but nothing large showed up on sonar. Sending a dive team out also showed nothing in the water. Interestingly, the sonar ping actually registered a human-like ping directly on the target.

![image](https://user-images.githubusercontent.com/105495756/222234287-d535a573-16eb-486c-a89c-a5aa40bbf503.png)
_Figure 1. Navigation Terminal showing target ping, no creature in sight._

![image](https://user-images.githubusercontent.com/105495756/222234303-dd6b7f29-a0b0-47a2-868a-249ef78e4934.png)
_Figure 2. Mysterious human ping on exact target location._

![image](https://user-images.githubusercontent.com/105495756/222234323-e871cecb-1a6b-4ae5-9e93-dbbf20204cc6.png)
_Figure 3. Active sonar not picking up any signatures on target location._

![image](https://user-images.githubusercontent.com/105495756/222234334-1e304437-0750-4bcb-93fe-2bf6a1402092.png)
_Figure 4. Freecam + Lighting screenshot of submarine and target location, showing no physical entity within target's supposed range._

![image](https://user-images.githubusercontent.com/105495756/222234368-6f35a0e4-aa4d-468c-a2b2-e1e618bb5098.png)
_Figure 5. The Endworm (target) blissfully unaware of the chaos unfolding 800m away._

![image](https://user-images.githubusercontent.com/105495756/222234395-bb414cb8-0be8-4841-b734-9b3a3e2d1ace.png)
_Figure 6. Freecam + Lighting + Debugdraw screenshot of submarine, drone, and target location, showing absolutely nothing going on which could prompt this issue._

![image](https://user-images.githubusercontent.com/105495756/222234416-b91e9f3e-c03d-4201-ae99-573bd4776141.png)
_Figure 7. Screenshot showing the exact location of the submarine (marked by the submarine) relative to the target (endworm, marked by my silly little red pen)._

Below is the save file I took during the mission in the hopes that it can aid the debugging of this issue.

[Hunting Grounds Mission Ping Lies.zip](https://github.com/Regalis11/Barotrauma/files/10864335/Hunting.Grounds.Mission.Ping.Lies.zip)
(Save file during the mission)

After identifying the true location of the target, I moved the submarine towards it. The navigation terminal then decided it wanted to give us precise location tracking complete with the real distance, so frankly I have no idea what was going on.

![image](https://user-images.githubusercontent.com/105495756/222234619-9bcd0e12-e593-4056-8e3e-218ebe3bb41c.png)
_Figure 8. Navigation Terminal suddenly showing the correct target location complete with real time location tracking and distance measurements._

Just to be safe, I have also included the save file of the game state directly _after_ we completed the mission.

[Same save but directly after the mission ended.zip](https://github.com/Regalis11/Barotrauma/files/10864345/Same.save.but.directly.after.the.mission.ended.zip)

### The Navigation Terminal Making Up Distances
Here are two major instances of the navigation terminal blatantly lying about positions. We do have video footage of the markers increasing or decreasing distance in real time according to the submarine's movement, but in order to get this comment posted quicker I'll skip out on that for the moment. It might not even be necessary given the other evidence in the ticket, but feel free to yell at me and/or calmly request the video footage.


![image](https://user-images.githubusercontent.com/105495756/222235441-133d6db8-3672-41ea-a8b9-eb1e486ac7a8.png)
_Figure 9. Submarine close to outpost docking port (pay attention to the rock formation to the left, this is important)._

![image](https://user-images.githubusercontent.com/105495756/222235453-9318ad77-9184-416f-8ad1-4e9d0aa97c56.png)
_Figure 10. Submarine about 20m below Figure 9, reporting a distance difference of ~400m (pay attention to the rock formation; it's the underside of the same rock formation seen in Figure 9)._

![image](https://user-images.githubusercontent.com/105495756/222236017-75e004d9-7508-4a2c-9690-2a4cec1f1a0e.png)
_Figure 11. Submarine reportedly ~200m from the drone, taken from outside of the map (from pushing final boss bug). The drone is presently disabled and cannot move._

![image](https://user-images.githubusercontent.com/105495756/222236103-8a47c2da-e561-4e5e-adb6-7b8d324b55a8.png)
_Figure 12. Submarine suddenly 98m from the drone despite barely moving as evident by the maintain position icon. The drone did not move closer to the sub as it is still disabled._

### Monster Pings Lying in Situations it Really Shouldn't (bonus issue, monsters spawn in giant mega-clumps?)
At this stage in the mission, you, the captain, should know exactly where the enemy locations are. The positions are actively changing in relation to your submarine's movement and you have their rough positioning. The navigation terminal, however, pings the targets as within sonar range (they are not) whilst also actively swimming towards your sub (they are not). This leads to overall confusing and muddy engagements in which the captain isn't sure what's alive, what's dead, where the enemies are (because the red mission ping overlaps with the sonar monster ping and creates an unclear image of the engagement (and not in a fun way)), and how many targets remain. 

![image](https://user-images.githubusercontent.com/105495756/222235753-01f3bedc-aee3-4b90-a601-dc931f0cfb2e.png)
_Figure 13. Navigation Terminal showing monster pings inaccurately reported (notice the red markers showing on sonar without any physical ping associated with it)._

Additionally, it seems that monster swarms spawn in giant clumps as demonstrated on the sonar. It looks like a moloch ping but that's the tiger thresher swarm.

**Comment by Regalis11** [comment]
Sorry for taking so long to get back to this. It does sound like most of the behavior you described is intentional: as said, the nav terminal only shows an approximate position when you're far away from the target. There does seem to be something off here though - the endworm should've appeared when you got close to the sonar marker.

**Comment by Regalis11** [comment]
I gave the provided saves a test, but unfortunately still couldn't get the issue to occur. :/ The marker seems to gradually move to the correct position when approaching it.
