### ISSUE TITLE
[1.0] Separatist Relations event occurs within Separatist controlled outposts

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11340]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Separatist Relations event can trigger at separatist outposts. It doesn't make sense as to why:
A) You would confront them in their own territory about them vandalising a trash can with the separatist logo.
B) They would be vandalising the trash can in the first place.
C) You engaging with these people would give you a reputational boost.
D) You would help them vandalise their _own property_.

![image](https://user-images.githubusercontent.com/105495756/221032571-5706d9e9-53b2-4f72-a41e-e21b3562e022.png)
_Figure 1. Event text start._

![image](https://user-images.githubusercontent.com/105495756/221032581-6589a187-903b-4fe9-84dd-bf4267311f49.png)
_Figure 2. Image showing current outpost is separatist owned._

### Bug prevalence

Just once

### Version

Other

### -

1.0.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c8ea1764e421836232b400c866446a7c1a472004

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
