### ISSUE TITLE
Husk infection stinger attack doesn't heal the user

### ISSUE THREAD

**Issue by demiurgeQuantified** [Regalis11/Barotrauma#11349]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a player with late-stage husk infection attacks with the stinger attack they aren't actually healed. This happens because the StatusEffect for the healing targets This (the stinger) instead of Parent (the character).

### Reproduction steps

1. Have the husk infection and some damage
2. Attack another character
3. You will not be healed

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report and the help in debugging this! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d321a51f11c7110d5dfe8695df3c158c001abbba

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
