### ISSUE TITLE
Explosions dealing damage to walls for no apparent reasons

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11343]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Explosions with 0 / no structuredamage defined can deal damage to structures

Using the #11342 projectile, hulls take 7% damage (repaired the hull beforehand) after the discharge triggers

![image](https://user-images.githubusercontent.com/73229309/221071527-851b4b52-7102-4de0-8b7f-5b47b7f3a1f1.png)

It doesnt seem to be related to the item being a projectile either

![image](https://user-images.githubusercontent.com/73229309/221071672-bd35e6d2-21d3-4ce3-9e98-a5d41400c78a.png)

Will run more tests tomorrow when I'm not as sleepy

### Version

0.21.6.0

**Comment by Regalis11** [comment]
Could not reproduce:

https://user-images.githubusercontent.com/14351070/221132127-eb7ffdfe-df97-42bb-9820-3972957ef38b.mp4

**Comment by ubertpendragon** [comment]
Once again sorry for the wrong version, this is happening on the factions branch

The harpoon on the right is damaging the wall on zap; it might be because the projectile gets dislodged a little and hits the wall a second time
The harpoon on the left doesnt and is firmly stuck

![image](https://user-images.githubusercontent.com/73229309/221183995-c3471c54-e1e9-415f-a2f5-dbeb3b6bd448.png)


This doesn't explain what happened on Udrakan's side though

**Comment by Regalis11** [comment]
Thanks, got this to happen in the faction build! It seems the explosion is not what's damaging the walls here, it's the impact of the projectile.

I'm not entirely sure yet why it's happening with a delay, but I think it has something to do with how the StatusEffects activate/deactivate the item, and impacts are only processed when the Projectile component is active.
