### ISSUE TITLE
Outpost canteen module starts with lights turned off

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#11356]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This minor issue has been bugging me for a long time.
![image](https://user-images.githubusercontent.com/59519434/221312529-b2ae8b11-bfb9-4b04-b1c7-8c7c4cc9842b.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/148c72f6f1188934030925e675224265dccbbeb3

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
