### ISSUE TITLE
Reactor overloading at a round start

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11352]
Version: release/1.0 (1.0.3, Regalis11/Barotrauma-development@5f789c1)

I've now encountered this issue a couple of times: using Barsuk, when I undock from an outpost, the power load at the very beginning of the round is enormous. Turning the reactor off as quickly as possible and fixing the junction boxes saves me, but you'll have to be quick with it, or all the boxes will be on fire.

There's two things that confuse me:

1. Why is the power load so high in the first place? It does drop rapidly, but not quickly enough. Could it be that the power levels of the outpost affect what the starting level is? I noticed that both power output and the load are on a higher level when the sub is attached to an outpost.
2. The reactor is powered, but not auto-controlled. Shouldn't the reactor start disabled when the round starts? And if it starts enabled, it should also be auto-controlled. Also made sure that none of my bots poke the reactor by disabling the crewai at the round start. So it shouldn't be an issue with the AI.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b3b21e32-4ed1-41fd-99e7-88402bb5d4eb)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/17008c1b-4423-4f42-bfbc-6c5f0e25e49e)

Save file: [https://app.zenhub.com/files/93301055/908aa6a3-0674-4c33-a6c0-afeed7989088/download](https://app.zenhub.com/files/93301055/908aa6a3-0674-4c33-a6c0-afeed7989088/download)

**Comment by itchyOwl** [comment]
Seems that the reactor is on at the round start, and my engineer goes to switch the auto-control on.

**Comment by Regalis11** [comment]
The submarine is connected to the outpost's electrical grid through the docking port. Normally that means the sub gets powered by the outpost's reactor without having to run it's own reactor, but it seems something's gone wrong here: the reactor is already running at a very high output at the start of the round. 

One potential explanation I can think of is that something happened to the outpost reactor during the previous round, and the outpost started leeching of the sub's electrical grid, causing the sub's reactor to crank the output all the way up. Then after undocking, when the load from the outpost suddenly disappears, the output is way too high and overvoltage occurs.

Hard to say for sure if that's what happened here: this doesn't seem to happen again if I redock to the outpost and undock again in that save.

But I think I could probably implement some kind of a safeguard against this, even if we can't figure out what caused it here. For example making the reactor adjust the fission rate and turbine output very fast for x seconds after a round starts.

> Shouldn't the reactor start disabled when the round starts? And if it starts enabled, it should also be auto-controlled.

It should start in the same state that it was in at the end of the previous round, so you don't need to wait for the sub to power up at the start of every round.

**Comment by mygamingaccount** [comment]
*Who turned off reactor auto?*

*What happened to the station reactor?*

This has never happened to me before!
If the sub reactor is on auto, it will output much less power than the station. At start it takes a few seconds for it to spin up to power the sub.

**Comment by Regalis11** [comment]
> This has never happened to me before!

If you're saying this stuff happens regularly, do you have any idea what kind of situations it occurs in or what can cause it? It's worth noting that in itchyOwl's case this happened in a single player campaign, in which he hadn't touched either the outpost or the submarine reactor.

**Comment by Regalis11** [comment]
Possibly related: it seems that shutting the reactor off (either by pressing the power button manually or with signals) turns of automatic control. Changed that in https://github.com/Regalis11/Barotrauma-development/commit/82967d0c8f7eb76da0fa1b066d77cd74a7228987

**Comment by mygamingaccount** [comment]
> Possibly related: it seems that shutting the reactor off (either by pressing the power button manually or with signals) turns of automatic control. Changed that in https://github.com/Regalis11/Barotrauma-development/commit/82967d0c8f7eb76da0fa1b066d77cd74a7228987

Oh no! That isn't right.
Reactors aren't supposed to be started with automatic on. That is very hazardous! Much safer to leave it on manual.

**Comment by Regalis11** [comment]
I'm still not sure what you're trying to say under all those layers of sarcasm?

**Comment by mygamingaccount** [comment]
You are imagining sarcasm where there is none.

Currently in 1.0 it is correct: the reactor turns off automatic when someone shuts it down.

Turning on the reactor requires the fission rate be set to the correct value before automatic can be enabled. So the procedure is:
- turn on reactor
- set turbine to the correct value
- manually adjust fission rate until heat is correct
- switch on automatic control

If the reactor does not switch off the automatic mode by itself, that only means that it has to be done every time you turn it on.
Anyone first operating the reactor will have a much less chance of realizing that the reactor must be initially controlled manually.

**Comment by mygamingaccount** [comment]
It also has to be said that the reactor remains on throughout the entire campaign and it being switched off is not normal.

**Comment by Regalis11** [comment]
> Turning on the reactor requires the fission rate be set to the correct value before automatic can be enabled. 

It doesn't: you can just turn the reactor on, and assuming automatic was left on, it'll slowly ramp up to the correct fission rate. 

> Anyone first operating the reactor will have a much less chance of realizing that the reactor must be initially controlled manually.

It doesn't need to be though? I'd argue that for someone new it's safer that the reactor is on automatic when they turn it on.

**Comment by mygamingaccount** [comment]
> It doesn't: you can just turn the reactor on, and assuming automatic was left on, it'll slowly ramp up to the correct fission rate.
Is that really how you intended it to be working? That's not how it works. It overshoots and catches fire. Which is why the procedure in my previous comment is necessary for a safe and fast reactor startup.

**Comment by Regalis11** [comment]
@mygamingaccount Yeah, the automatic control shouldn't overshoot (at least if the load is stable). Giving this a test, it doesn't seem to overshoot at all:


https://user-images.githubusercontent.com/14351070/235637733-d03d9c64-c3a9-40bf-a9ac-a5609304e7fa.mp4

**Comment by mygamingaccount** [comment]
Are you aware of these slots here? They are normally filled with fuel rods. Redo the test: join any server, shut down the reactor, start it up like you do in this video. You will be banned in 20s
![barodev](https://user-images.githubusercontent.com/68995233/235726264-2f3f9b63-d317-45b0-af32-ccb7c1ded7d9.jpg)

**Comment by Regalis11** [comment]
Yes, I'm aware of those slots. :) 

The reactor normally should not be run with more than one rod, much less with the maximum amount of rods (even though I know that's how many of the more experienced players use the reactor). The reactors in the vanilla subs are designed to barely meet the power requirements of the devices in the sub, so you need to be careful with power management. You _can_ generate more by placing in more than one slot, but that requires extra caution. You definitely shouldn't be running the reactor on auto with 4 rods.

**Comment by mygamingaccount** [comment]
I never would have guessed that any of the original subs were intended to be used with only one rod. This is very interesting.

Looking forward for the results of this experiment!

**Comment by Regalis11** [comment]
> I never would have guessed that any of the original subs were intended to be used with only one rod.

Have you played the tutorials by any chance?

**Comment by mygamingaccount** [comment]
> Have you played the tutorials by any chance?

A few thousand hours ago, I suppose. I understand much has changed and it was improved recently so I'll check it out.

I tested playing a mission on one fuel rod and oh boy, the sub did not feel seaworthy at all. If that's to be made a viable option then testers should be asked to focus on single-rod operation and provide feedback on how to tune the subs.

**Comment by mygamingaccount** [comment]
> The reactor normally should not be run with more than one rod, much less with the maximum amount of rods (even though I know that's how many of the more experienced players use the reactor). The reactors in the vanilla subs are designed to barely meet the power requirements of the devices in the sub, so you need to be careful with power management. You _can_ generate more by placing in more than one slot, but that requires extra caution. You definitely shouldn't be running the reactor on auto with 4 rods.

In a game with experienced testers I managed to keep the reactor running on a single rod by setting it up to not crash due to under-temperature (manually limiting the tubine to 80 and keeping it there, rewiring the batteries so both relays stayed on)
When I handed off the control to the rest of the crew we quickly ran out of power due to the automatic control making the output power crash due to power demand. The sub was unseaworthy.
I was unable to convince the crew (specifically someone one on the dev team) to to keep running the reactor on a single uranium rod.

**Comment by giists** [comment]
Tested this issue and everything connected to the PR. Closing.
