### ISSUE TITLE
sprite depth too deep for battery cells and some wiring

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11354]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the battery cell and fulgurium battery cell have very deep sprite depths, of 0.8.

Additionally, dropped but not yet placed wiring components, wires are also 0.8.

this causes them to sometimes be hidden behind furniture/things that would otherwise not hide dropped items.

Inventory items generally have 0.55-0.6 depth. 

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
> Additionally, dropped but not yet placed wiring components, wires are also 0.8.

Are you sure this is actually the case? [It seems you've already reported this before](https://github.com/Regalis11/Barotrauma/issues/8073), and back then we fixed it by overriding the components' sprite depths when they're not attached to a wall. If you look at these items in the sub editor, their depths are shown as 0.8, but they seems to correctly render at the overridden depth (0.55).

**Comment by Anarengon** [comment]
>  but they seems to correctly render at the overridden depth (0.55).

the battery cell doesn't seem to be rendering at depth .55 here 

![image](https://user-images.githubusercontent.com/97921339/221683079-56674f57-0e7c-4773-a8f8-70054a50c52d.png)

**Comment by Regalis11** [comment]
Yeah, the battery cell seems to be broken, but unless I'm missing something, the wiring components seem to be working correctly.

**Comment by Tsunder** [comment]
> Are you sure this is actually the case?

sorry, I have not actually tested, it was a quick check over suspect item definition.

**Comment by Regalis11** [comment]
Fixed battery cells in https://github.com/Regalis11/Barotrauma-development/commit/945e9d8a8e26a2d2f8e95f42aed4aac3ae072ad9
