### ISSUE TITLE
Dropped Battery Cell wrong sprite depth 

### ISSUE THREAD

**Issue by Anarengon** [Regalis11/Barotrauma#11355]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A dropped on the floor Battery Cell item has a sprite depth of .800 instead of the .600 standard to every other dropped item. This causes it to be visually behind things that it shouldn't be visually behind.  
![image](https://user-images.githubusercontent.com/97921339/221287733-79a2797f-a5be-460d-a4fa-0cd73ccaf906.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/11354
