### ISSUE TITLE
After the translation some things and inscriptions were lost.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1136]
**Description**
Missing wires from rewire mode.
![image](https://user-images.githubusercontent.com/33912761/52687559-99327780-2f63-11e9-9eef-f4c15734db3d.png)
Character traits are missing.
![image](https://user-images.githubusercontent.com/33912761/52687619-d434ab00-2f63-11e9-9527-96025bdf7268.png)

**Version**
Steam.

**Comment by Regalis11** [comment]
The first issue should be fixed now. I'm not sure what's causing the second one, could you maybe send me the translation file so I can try to reproduce it?
