### ISSUE TITLE
Orca2 Fabricator not linked to nearby cabinet

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#11360]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Orca2 Fabricator not linked to nearby cabinet. It makes crafting in bulk a pain in the butt.

### Reproduction steps

1. Choose the Orca2
2. Go to the fabricator
3. Realize you have to put all your raw materials into the fabricator every time you want to craft something
4. Get mad and use the Humpback instead

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
I'd love it if this got traction, so all of the subs get modernized to support the features that were added to the game after they were designed.

**Comment by mygamingaccount** [comment]
As seen on:

* Azimuth
* Berilia
* Kastrull
* Orca
* Orca2
* Typhon
* Typhon2
* Winterhalter

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/cba1b0c4663e05bf2a07d5b3c83b5abdb2502cc6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
