### ISSUE TITLE
Pet name tags float in place when equipped

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11365]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/221369909-71b888a3-ee74-4465-a317-2cfd2f1ad163.png)
Seems when you put a name tag on a defense bot, it will appear floating in the place it was inserted in, here, infront of the cabinet, it does not fall

### Reproduction steps

1.Put a name tag on a defense bot
2.Notice the floating nametag

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7e7f8c6292b9ce7dd34c57bce2421684e8e360b1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
