### ISSUE TITLE
FB3000 allows you to infinitely generate potassium

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11369]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Very simply. The bananas shot by the funbringer 3000 can be deconstructed before they dissapear, giving 1 potassium each. This lets you generate infinite potassium

### Reproduction steps

1.Equip the FB3000 
2.Shoot a couple banana shells
3.Pick them up and deconstruct them immediately
4.Congrats

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment]
Should note that Deconstructor upgrades or the "Oiled Machinery" talent allow this to happen.
Also wanted to add that it's possible to move while using the Funbringer 3000 without a fuel rod if the player has any buffs that increase movement speed.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7bd34a3f3f74b0d4645d22a821c0042248a02656

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
