### ISSUE TITLE
Pulse Laser sprite is misaligned

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11364]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The two moving sprites on either side are not properly aligned

![image](https://user-images.githubusercontent.com/73229309/221362644-2db06291-e847-4ba9-8fe3-643e6e5714aa.png)

Fixed:
```xml
      <ChargeSprite chargetarget="25, 15" texture="Content/Items/Weapons/Turrets.png" depth="0.01"  sourcerect="570,692,59,150" origin="1, 1.6" />
      <ChargeSprite chargetarget="-25, 15" texture="Content/Items/Weapons/Turrets.png" depth="0.01"  sourcerect="642,692,59,150" origin="0, 1.6" />
```
![image](https://user-images.githubusercontent.com/73229309/221362659-c2b901b9-edaa-4acc-b044-52955e12501f.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4dfe137d2bb6cf83885b2c27d3beef17a4413031

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
