### ISSUE TITLE
[1.0] 0% condition grenades (stun grenade and fixfoam) will detonate if a player has one in their inventory on mission start

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11366]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Type: Multiplayer P2P
Mode: Campaign

### Issue Report
If a player loads into a mission with a 0% condition non-lethal grenade (frag grenades do not suffer from this issue, according to tests), the grenade will detonate once the player loads in. This causes the fixfoam grenade to spew foam everywhere and the stun grenade to explode and play the tinnitus sound. It is important to note that the effects do not do anything in practice; the stun grenade will not stun players once it detonates.

We have not tested the EMP or Incendium grenades. The only throwables we have tested are the Stun Grenade, Fixfoam Grenade, and Frag Grenade.

### Reproduction steps

1. Use a stun grenade (or fixfoam)
2. Pick up the used stun grenade
3. Start the next multiplayer mission
4. Observe the explosion sound and effect playing once you load in

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
