### ISSUE TITLE
Husk Container eats Exosuits

### ISSUE THREAD

**Issue by brayjack** [Regalis11/Barotrauma#11367]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a player is wearing an exosuit while dead, and a huskified storage container is nearby, the husk container will eat the players body and destory the exosuit along with it. This does not happen if the player is wearing the clown exosuit however. 

### Reproduction steps

1. Spawn huskified storage container nearby
2. Wear exosuit and die while wearing (can also be achieved if player dies as a husk while wearing the exosuit)
3. Watch in awe as the pet rips the exosuit piece by piece and eats the metal suit in its entirety 

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I gave this a quick test, and it doesn't seem like they're actually eating the suit, but the character. Once they finish eating the character fully, the suit drops out of the character's inventory.

The type of suit (or whatever other items the character is wearing) doesn't seem to make a difference: I suspect they just weren't hungry enough to start eating the corpse inside the clown exosuit.
