### ISSUE TITLE
Treatment shown for husk infection while wearing zealot robes

### ISSUE THREAD

**Issue by demiurgeQuantified** [Regalis11/Barotrauma#11362]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While having husk genetic material equipped, treatment for the husk infection is hidden from the health panel as it's no longer a threat to the host and removing it accidentally would be a pain - but when wearing the zealot robes (and not using the genetic material), the treatment is still shown despite having similar immunity, and having even greater benefit from the symbiote.
This can be resolved by adding husktransformimmunitytemporary to the husk infection's IgnoreTreatmentIfAfflictedBy.

### Reproduction steps

1. Have the husk infection and some calyxanide on hand
2. Open health panel - calyxanide is offered as treatment
3. Equip husk genetic material - the treatment options are now gone
4. Unequip the genetic material, and equip the zealot robes
5. The treatment options are shown again

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6783493026227517127d97c79a0d8c5f61dd2c4a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
