### ISSUE TITLE
Exosuits still have their light on if the player inside is dead

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11379]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems that even after the player inside dying, the light doesnt turn off, like it normally does with other suits, same goes for the FB3000 
![image](https://user-images.githubusercontent.com/104232152/221422197-f91b6332-2490-427b-8751-4dfba43bd415.png)

### Reproduction steps

1.Equip an exosuit
2.Die in it
3.Notice the light continuing to stay on

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e109530eb4ffeecedcd6325ce9d79f80e8dc17d5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
