### ISSUE TITLE
Diving suits are missing acid resistance

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11370]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?
EDIT:Seems all the dive suits, exept for the exosuit, do not have acid resistance, not anymore at least.
(Unlike the exosuit, the funbringer shares all stats with the exosuit but the acid resistance, which seems like an oversight)

### Reproduction steps

1.View the stats of each of them seperately
2.They are identical, aside from missing acid resistance

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
In fact, they do. They have a "burn" type resistance which also protects character from "acidburn".

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
