### ISSUE TITLE
Only non-Nuclear Depth Charges can have quality

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11375]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems that when using a fabricatior and the sufficient skill, depth and decoy charges can be made with higher quality and better stats, this, however, doesnt translate over to their nuclear variants, always being stuck at the regular quality
![image](https://user-images.githubusercontent.com/104232152/221385723-9e4fb9d9-2022-467b-a6f4-1ea8e27f31be.png)

### Reproduction steps

1.Give yourself 100 weapon skill for testing purpose
2.Craft a depth charge, it will end up with excellent quality
3.Craft a nuclear depth charge, no quality will be given

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7deae6b8c9f2ea930ad9fd39a50b8da85c77227b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
