### ISSUE TITLE
All crates float

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11374]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/221384898-7605090d-4a14-41cd-852b-630331b05a12.png)
Very simply, no crate or box besides the clown crate actually has a hitbox where the sprite touches the floor, leaving them all to be floating centimeters off of the ground.

### Reproduction steps

1.Set a crate or box down on a flat surface
2.Notice its slightly floating, the ammo boxes more so than the crates, with exeption of the clown crate

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3803c2107531f928c20b7c7a4308451c133d203

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
