### ISSUE TITLE
Special hires bonus talents not appearing until the following round

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11384]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After getting a special hire (sootman for example), the bonus talents do not appear until the round after you hire them.

### Reproduction steps

1. Get a special hire that comes with bonus talents
2. Look at their character info
3. You cannot see the bonus talents
4. Start next round
5. You should be able to see their bonus talents

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to only happen in multiplayer. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c41c2e8ec5c645f74de177a1455bc04fdb70cf3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
