### ISSUE TITLE
[1.0] Floating light in end level mid

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11386]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Alien light at 0.900 sprite depth going through the sub in the end level

![image](https://user-images.githubusercontent.com/73229309/221655757-cba75460-e73a-4157-98c1-32913573e9f9.png)

![image](https://user-images.githubusercontent.com/73229309/221656032-cbc96e92-b21d-402a-8e83-462cac37bef3.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0eb1bcb72c8ade530f61559282a2ec8d4ecabb56

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
