### ISSUE TITLE
Infinite/Massive Amount of Welding Fuel

### ISSUE THREAD

**Issue by RussischBrot** [Regalis11/Barotrauma#11382]
### Disclaimers

- [X] My issue happened while using mods.
- [X] I have searched the issue tracker to check if the issue has already been reported.

### What happened?

I shot some holes in a station wall (in my case a Research Station, layout in screenshots) and npcs started dropping welding fuel like crazy.
After some testing i just used the welding tool to lock a door, used the ship weapon to punch some holes in the station wall and watched npcs (at least researcher and engineer, dont know if there are more) dropping welding fuel.
you can easily pick up the welding fuel, its not marked as stolen.
I ended up with 486 welding fuel in about 15min (edit: in the first attempt, when I encountered the bug).
Tested five times, worked every time.

The mods I'm using just add some new items, like a Status PDA (used for the statioon layout screenshot) so they shouldn't be the reason why this bug happened.
Screenshots from different tries.

![station damaged](https://user-images.githubusercontent.com/74217127/221557843-6fa008aa-abd0-4332-a276-80800d99b328.png)
![station](https://user-images.githubusercontent.com/74217127/221557847-8bc2292a-45e2-49d4-8689-8cc283b1eff0.png)
![welding fuel 2](https://user-images.githubusercontent.com/74217127/221557851-d57959d2-4416-4682-9214-b276c09a5fb6.png)
![welding fuel](https://user-images.githubusercontent.com/74217127/221557852-6bfb0756-2d3a-4934-99e8-3cd823896f4a.png)
![npc dropping welding fuel](https://user-images.githubusercontent.com/74217127/221557853-fdd0143c-cf43-46d8-ae4a-2713ba31ac45.png)

### Reproduction steps

1. Start (Multiplayer)Campaign
2. Dock at Station
3. use welding tool to lock station doors (better results if engineers and researcher are outside the flood area
4. use ship weapon to punch holes in the station and flood the locked area
5. take big chest, search for engineers and researcher and pick up the welding fuel they're dropping.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by StruggleDuck** [comment]
If you have your save file, you should probably provide it as it might make identifying the issue easier for the devs

**Comment by Regalis11** [comment]
The outpost NPCs can spawn some basic supplies "out of thin air" if they have no other means to access them, but it seems that has gone wrong here somehow. Not sure what exactly, or whether we have addressed this recently (I vaguely recall there being some fixes to bots swapping/containing items recently) - maybe @itchyOwl knows more?
