### ISSUE TITLE
Enemy faction vendors still have greatly increased vitality

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#11385]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Enemy faction vendors still have greatly increased vitality than regular outpost dwellers, which makes them extremely frustrating and annoying to kill/fight.

### Reproduction steps

1. Enter enemy outpost
2. Attempt to fight enemy vendors
3. Run out of ammo and die

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Related ticket: [you can interact with hostile outposts as if they were friendly](https://github.com/Regalis11/Barotrauma/issues/11062)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/988231a18104080aeaf6bf44e7dc999b2258c0d7

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
