### ISSUE TITLE
Exosuits placed in the sub editor get autofilled incorrectly

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11380]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems when placing an Exosuit in the editor, it gets autofilled with an oxygen tank in the correct slot, and a battery in a spare inventory slot, without a fuel rod. Im assuming this is an oversight since the change from battery to fuel rod in the exosuit. Same as the Funbringer, missing a fuel rod when placed, though that may be intentional.
![image](https://user-images.githubusercontent.com/104232152/221423030-88a51909-a789-408a-902a-072ea633cf67.png)

### Reproduction steps

1.Place an exosuit on a sub in the editor
2.Make sure autofill is enabled
3.Go into the game on said sub, the suit will get autofilled with a spare battery

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
