### ISSUE TITLE
Kastrull issues 

### ISSUE THREAD

**Issue by Fentanyl1984** [Regalis11/Barotrauma#11393]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While playing on kastrull sub during Wheatley testing sessions, we found some issues which i believe are worth reporting.

1. biggest issue currently present - the infamous unhulled cube.
Because its not hulled , clueless players may accidentally fall in this area and die from pressure/flood the sub.
![Kastrull(1)](https://user-images.githubusercontent.com/123274797/221786981-fd04fb74-2279-4b52-bdf6-3eae5fb7728d.png)
![image-24(1)](https://user-images.githubusercontent.com/123274797/221786987-2eda0d26-a2e7-4c8f-866f-99eb2c2ac270.png)
2. Sprite depth issues.
Vast majority of fin patches used under labels have wrong sprite depths and are hidden behind back walls; inside walls are also not adjusted, showing on top of outer shell pieces. and thats  only what we managed to find - kastrull needs a big inspection in this regard.
![Kastrull(3)](https://user-images.githubusercontent.com/123274797/221788594-b0ef0260-d4eb-4b10-a0e4-4aa89253ccf4.png)
![image](https://user-images.githubusercontent.com/123274797/221788612-aef6dc21-6575-4e3b-a9d9-c947f000f8d8.png)
3. Also infamous wall between gunnery and engineering. 
This may sound like a suggestion, but i think at this point its an issue because of how easily and consistently players decide to just work around it.
![Kastrull(2)](https://user-images.githubusercontent.com/123274797/221789674-4823404e-c1fe-4b66-8410-31767b8101a7.png)
this is what happends in actual multiplayer games:

https://user-images.githubusercontent.com/123274797/221790132-21a03b9f-a459-469a-8e74-e5382148daa4.mp4

And the fact that kastrull wreck actually does have this door is truly comical:

![Kastrull_Wrecked(1)](https://user-images.githubusercontent.com/123274797/221790749-ca7359ea-d92d-49d5-a9bc-6113817cdbeb.png)

4. Ballast pumps particles.
Unique internal ballast tanks result in visual bug which occurs when pumps pump water in - water particles go trough ballast floor. Especially noticable when moving at max velocity.

https://user-images.githubusercontent.com/123274797/221791736-bf9d7735-a1b6-4016-b3c5-4dc438f31c55.mp4

 

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/466d75c0203d2aada210873d51ea42b7ee9cd839

**Comment by Wheatley1001** [comment]
Unsure if this goes here or if it's its own ticket, but the status monitor reporting of the Kastrull drone appears to be inconsistent. 

As demonstrated in the image below, the status monitor reports the Kastrull's drone to be on the left docking hatch, whilst the drone was actually on the right docking hatch. This issue occurred in a multiplayer campaign save on a P2P server.
![image](https://user-images.githubusercontent.com/105495756/222256668-0c012e23-4059-4cd8-9ebd-7520478c40ed.png)

**Comment by Rokvach** [comment]
Fixed in wrong way, should have the Fin Patch 1 behind the labels like elsewhere in the sub
![image](https://user-images.githubusercontent.com/7299826/230337519-dac3d3bc-bc29-49d2-8b5f-eb48254f5519.png)
![image](https://user-images.githubusercontent.com/7299826/230337599-2bb60b42-fee6-4993-a922-12726d9bf624.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
