### ISSUE TITLE
"Non-Threatening" talent broken?

### ISSUE THREAD

**Issue by MarkCringan** [Regalis11/Barotrauma#11391]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the talent description for "Non-Threatening", it states that "Enemies will ignore you if you have been ragdolled for longer than 2 seconds," which is simply not true. Whilst ragdolling, enemies will not ATTACK you, however, they will continue to swarm you relentlessly. Examples of this include hammerheads continuing to repetitively charge you and not hit you, as well as spinelings continuing to circle around you. 

If this is how the talent is supposed to work, then I believe the description should be reworded in order to not mislead people. Preferably, however, it would be really nice if it would make the AI truly ignore you.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@f4eb52.

**Comment by Regalis11** [comment]
Tested, could not spot any issues. Closing.
