### ISSUE TITLE
the game didnt give us mission

### ISSUE THREAD

**Issue by rickscorp** [Regalis11/Barotrauma#11397]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

we were stuck on some passage after mission (cant go anywhere)and use teleport so we can save the game but after that the game didnt give us anymore mission

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Would it be possible to send us the save file? I think it might be hard or impossible for us to reproduce the issue otherwise, especially without knowing which mods you are using. And by teleport, do you mean you used the "togglecampaignteleport" console command? Thanks and sorry for the inconvenience!

**Comment by rickscorp** [comment]
i cant provide savefile from the server but i can give you the logs frm 27 till 28th of feb 
[Xlegion - dedicated server_2023-02-28_2328.txt](https://github.com/Regalis11/Barotrauma/files/10861416/Xlegion.-.dedicated.server_2023-02-28_2328.txt)
[Xlegion - dedicated server_2023-02-28_2331.txt](https://github.com/Regalis11/Barotrauma/files/10861420/Xlegion.-.dedicated.server_2023-02-28_2331.txt)
[Xlegion - dedicated server_2023-02-28_2336.txt](https://github.com/Regalis11/Barotrauma/files/10861421/Xlegion.-.dedicated.server_2023-02-28_2336.txt)
[Xlegion - dedicated server_2023-02-28_2344.txt](https://github.com/Regalis11/Barotrauma/files/10861422/Xlegion.-.dedicated.server_2023-02-28_2344.txt)
[Xlegion - dedicated server_2023-02-28_2349.txt](https://github.com/Regalis11/Barotrauma/files/10861423/Xlegion.-.dedicated.server_2023-02-28_2349.txt)
[Xlegion - dedicated server_2023-02-28_2353.txt](https://github.com/Regalis11/Barotrauma/files/10861424/Xlegion.-.dedicated.server_2023-02-28_2353.txt)
[Xlegion - dedicated server_2023-03-01_0003.txt](https://github.com/Regalis11/Barotrauma/files/10861426/Xlegion.-.dedicated.server_2023-03-01_0003.txt)
[Xlegion - dedicated server_2023-03-01_0010.txt](https://github.com/Regalis11/Barotrauma/files/10861427/Xlegion.-.dedicated.server_2023-03-01_0010.txt)
[Xlegion - dedicated server_2023-03-01_0018.txt](https://github.com/Regalis11/Barotrauma/files/10861428/Xlegion.-.dedicated.server_2023-03-01_0018.txt)
[Xlegion - dedicated server_2023-03-01_0036.txt](https://github.com/Regalis11/Barotrauma/files/10861429/Xlegion.-.dedicated.server_2023-03-01_0036.txt)
[Xlegion - dedicated server_2023-03-01_0042.txt](https://github.com/Regalis11/Barotrauma/files/10861430/Xlegion.-.dedicated.server_2023-03-01_0042.txt)
[Xlegion - dedicated server_2023-03-01_0045.txt](https://github.com/Regalis11/Barotrauma/files/10861431/Xlegion.-.dedicated.server_2023-03-01_0045.txt)
[Xlegion - dedicated server_2023-03-01_0049.txt](https://github.com/Regalis11/Barotrauma/files/10861432/Xlegion.-.dedicated.server_2023-03-01_0049.txt)
[Xlegion - dedicated server_2023-03-01_0054.txt](https://github.com/Regalis11/Barotrauma/files/10861433/Xlegion.-.dedicated.server_2023-03-01_0054.txt)
[Xlegion - dedicated server_2023-03-01_0056.txt](https://github.com/Regalis11/Barotrauma/files/10861434/Xlegion.-.dedicated.server_2023-03-01_0056.txt)
[Xlegion - dedicated server_2023-02-27_2226.txt](https://github.com/Regalis11/Barotrauma/files/10861435/Xlegion.-.dedicated.server_2023-02-27_2226.txt)
[Xlegion - dedicated server_2023-02-27_2230.txt](https://github.com/Regalis11/Barotrauma/files/10861436/Xlegion.-.dedicated.server_2023-02-27_2230.txt)
[Xlegion - dedicated server_2023-02-27_2233.txt](https://github.com/Regalis11/Barotrauma/files/10861437/Xlegion.-.dedicated.server_2023-02-27_2233.txt)
[Xlegion - dedicated server_2023-02-27_2236.txt](https://github.com/Regalis11/Barotrauma/files/10861438/Xlegion.-.dedicated.server_2023-02-27_2236.txt)
[Xlegion - dedicated server_2023-02-27_2244.txt](https://github.com/Regalis11/Barotrauma/files/10861439/Xlegion.-.dedicated.server_2023-02-27_2244.txt)
[Xlegion - dedicated server_2023-02-27_2259.txt](https://github.com/Regalis11/Barotrauma/files/10861440/Xlegion.-.dedicated.server_2023-02-27_2259.txt)
[Xlegion - dedicated server_2023-02-27_2303.txt](https://github.com/Regalis11/Barotrauma/files/10861441/Xlegion.-.dedicated.server_2023-02-27_2303.txt)
[Xlegion - dedicated server_2023-02-27_2308.txt](https://github.com/Regalis11/Barotrauma/files/10861442/Xlegion.-.dedicated.server_2023-02-27_2308.txt)
[Xlegion - dedicated server_2023-02-27_2312.txt](https://github.com/Regalis11/Barotrauma/files/10861443/Xlegion.-.dedicated.server_2023-02-27_2312.txt)
[Xlegion - dedicated server_2023-02-27_2316.txt](https://github.com/Regalis11/Barotrauma/files/10861444/Xlegion.-.dedicated.server_2023-02-27_2316.txt)
[Xlegion - dedicated server_2023-02-27_2326.txt](https://github.com/Regalis11/Barotrauma/files/10861445/Xlegion.-.dedicated.server_2023-02-27_2326.txt)
[Xlegion - dedicated server_2023-02-27_2339.txt](https://github.com/Regalis11/Barotrauma/files/10861446/Xlegion.-.dedicated.server_2023-02-27_2339.txt)
[Xlegion - dedicated server_2023-02-27_2354.txt](https://github.com/Regalis11/Barotrauma/files/10861448/Xlegion.-.dedicated.server_2023-02-27_2354.txt)
[Xlegion - dedicated server_2023-02-27_2355.txt](https://github.com/Regalis11/Barotrauma/files/10861449/Xlegion.-.dedicated.server_2023-02-27_2355.txt)
[Xlegion - dedicated server_2023-02-27_2356.txt](https://github.com/Regalis11/Barotrauma/files/10861450/Xlegion.-.dedicated.server_2023-02-27_2356.txt)
[Xlegion - dedicated server_2023-02-28_2219.txt](https://github.com/Regalis11/Barotrauma/files/10861451/Xlegion.-.dedicated.server_2023-02-28_2219.txt)
[Xlegion - dedicated server_2023-02-28_2245.txt](https://github.com/Regalis11/Barotrauma/files/10861452/Xlegion.-.dedicated.server_2023-02-28_2245.txt)
[Xlegion - dedicated server_2023-02-28_2247.txt](https://github.com/Regalis11/Barotrauma/files/10861453/Xlegion.-.dedicated.server_2023-02-28_2247.txt)
[Xlegion - dedicated server_2023-02-28_2254.txt](https://github.com/Regalis11/Barotrauma/files/10861455/Xlegion.-.dedicated.server_2023-02-28_2254.txt)
[Xlegion - dedicated server_2023-02-28_2258.txt](https://github.com/Regalis11/Barotrauma/files/10861456/Xlegion.-.dedicated.server_2023-02-28_2258.txt)
[Xlegion - dedicated server_2023-02-28_2301.txt](https://github.com/Regalis11/Barotrauma/files/10861457/Xlegion.-.dedicated.server_2023-02-28_2301.txt)
[Xlegion - dedicated server_2023-02-28_2306.txt](https://github.com/Regalis11/Barotrauma/files/10861458/Xlegion.-.dedicated.server_2023-02-28_2306.txt)
[Xlegion - dedicated server_2023-02-28_2315.txt](https://github.com/Regalis11/Barotrauma/files/10861459/Xlegion.-.dedicated.server_2023-02-28_2315.txt)
[Xlegion - dedicated server_2023-02-28_2318.txt](https://github.com/Regalis11/Barotrauma/files/10861460/Xlegion.-.dedicated.server_2023-02-28_2318.txt)
[Xlegion - dedicated server_2023-02-28_2321.txt](https://github.com/Regalis11/Barotrauma/files/10861461/Xlegion.-.dedicated.server_2023-02-28_2321.txt)
[config_player.txt](https://github.com/Regalis11/Barotrauma/files/10861487/config_player.txt)

**Comment by rickscorp** [comment]
> Thank you for the report!
> 
> Would it be possible to send us the save file? I think it might be hard or impossible for us to reproduce the issue otherwise, especially without knowing which mods you are using. And by teleport, do you mean you used the "togglecampaignteleport" console command? Thanks and sorry for the inconvenience!

Yes I mean togglecampaignteleport

**Comment by Regalis11** [comment]
No known steps to repro, closing
