### ISSUE TITLE
RangedWeapon have regular spread

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11392]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When firing an automatic weapon, it feels like there are only 2 pre-defined angles of spread for bullets in each magazine.
Sometimes the 2 angles are so close to each other that player can let all bullets hit a single point.

### Reproduction steps

1. "spawnitem hmg inventory" and "spawnitem hmgmagazine inventory 10"
2. "setskill weapons 75"
3. keep firing the hmg and see the bullet trace swap between 2 regular spread angles

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.
