### ISSUE TITLE
CJK font doesn't support Japanese symbols

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11395]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Apparently NotoSansCJKsc doesn't properly support Japanese symbols, using roughly similar Chinese symbols instead.

https://heistak.github.io/your-code-displays-japanese-wrong/

https://steamcommunity.com/sharedfiles/filedetails/?id=2741236606

### Reproduction steps

1. Change the language to Japanese

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against fix/japanese-font-fix commit https://github.com/Regalis11/Barotrauma-development/commit/b8e24a229b693ce3ea8e3c8538ad6b409bab612f

Tested by changing language to Japanese and comparing each language (simplified Chinese, traditional Chinese and Japanese) for the same characters and they were correct to the selected language.

However noticed a duplicate override for traditional chinese in the styles that should probably be changed, probably harmless though:
![image](https://user-images.githubusercontent.com/29177976/230051200-c0a912d0-a672-41d5-a5b6-a0c96c639fb7.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4032/commits/965416661b25a87c27d077140ca8a42c56b446a9

**Comment by NilanthAnimosus** [comment]
Tested against fix/japanese-font-fix commit https://github.com/Regalis11/Barotrauma-development/commit/965416661b25a87c27d077140ca8a42c56b446a9, no issues found, can be merged.
