### ISSUE TITLE
Talent bonus modifiers not added to new crewmates

### ISSUE THREAD

**Issue by Prolbo** [Regalis11/Barotrauma#11398]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1st of all I didn't know if it is intended or not and I did not have the opportunity to test it in the multuplayer, but here it is:

When one of your crewmates takes talent with bonus modifiers which applyed to all crew, such as "Travelling Tradesman", "Family", "Blackmarket Genes", "Tool Maintenance", etc they applyed immidietly and only to currently present crew. I.e. if you hire someone after the fact of taking such talent, those characters wouldn't recive any bonuses.

Also if you will look into save file you will notice difference inside the "savedstatvalues" block.

![0000](https://user-images.githubusercontent.com/54717422/221944163-eff79477-5fcf-489b-9aa1-a03440c42112.png)

### Reproduction steps

1. Start campaign and level up your crew untill you will be able to pick one of the talents listed above
2. Take the talent, save the game, look at it. You'll find this bonus value in character list of all crewmates
3. Hire new crewmate, save the game, check for bonus values in the "savedstatvalues" block or in the "Character" header. There is none.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Prolbo** [comment]
Maybe you can create a new instance which will affect (share "buffs") whole crew and write such buffs there?

**Comment by Regalis11** [comment]
I don't think this is a bug. The "Family" talent says it gives a level to every character in the crew `on unlock`, not that everyone who joins the crew later always gets an extra level. The rest of the talents also should not apply if there's no-one in the crew with that talent (but if there is, it does affect the whole crew regardless if you have the talent or not).
