### ISSUE TITLE
"spawnmonster" command uses file path to check for monsters, which makes it ignore content packs

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#114]
Due to this custom monsters via content packs cannot be spawned since they're missing from the "main" content pack.
Perhaps remake "spawnmonster" to be more like "spawnitem" and make it more content pack-friendly?

**Comment by NilanthAnimosus** [comment]
This is one I recall from the code itself some time ago - but the monster events takes (and syncs) the path to where the creature exists, but the spawn command via the console does not have any method to determine or check alternate paths - Barotrauma Extended is a good example of this.

Can't say I tested it personally but was told of it months ago and looked into potentially integrating such but it would be hacky at best without a definition for creature folder locations added to the XMLs itself or as crystalwarrior has suggested remaking the entire system into prefabs.

I don't think the entire content system for creatures needs reworking into a prefab style - this can be resolved with 1 additional line to the XML for defining one (Or more) alternate paths to check for creatures.

This even allows the potential of say, having several content packs and another to combine them - and use content from all the separate content packages if the reference is included, finally referencing their character files of any other content pack potentially at just a path reference.

**Comment by Regalis11** [comment]
Fixed in e4664b3
