### ISSUE TITLE
Mechanic's Engine Engineer talent stacks (it shouldnt)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11400]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mechanic's Engine Engineer talent stacks despite the description
![image](https://user-images.githubusercontent.com/73229309/221969015-99408c87-eda6-45fc-9d3c-e764d6fb3b94.png)

### Reproduction steps

1. Give the talent to the whole crew and some levels
2. Go really fast

**Comment by 3e849f2e5c** [comment]
This is actually other way around, the "does not stack" part is an arbitrary restriction created by a bad item stat system that I eventually ended up fixing.

**Comment by Regalis11** [comment]
Even if it wasn't a part of the original spec, I don't think they should stack. 17 talent points * 16 players * 2.5% = 680% boost, which is way too much.

**Comment by ubertpendragon** [comment]
In the latest faction campaign, running a Kastrull with:
+24% speed from upgrades
+20% (actually 1.1*1.1) from captain talent
+20% from mechanic(s?)

We were going faster than most creatures. Only hammerheads really managed to scratch the paint of the engine room.

25 km/h seems to be the critical velocity at which most creatures won't be able to chase the submarine

**Comment by Regalis11** [comment]
The captain's Helmsman(?) talent also seem to stack: https://github.com/Regalis11/Barotrauma/issues/11715

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b793e51e5c0ee28e0a86f63ba11c1ecb45d14167

**Comment by Regalis11** [comment]
Tested in both SP and MP, could not spot any issues. Closing.
