### ISSUE TITLE
Client hosting and playing another game results in nobody able to connect to server

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1140]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was hosting a server for closed alpha, and found I get very few connections. turns out it appears impossible to connect to a client server if they run another game on steam - despite the IP, port and server information appears correct.

**Version**
Windows 7 64bit, Closed alpha 0.8.9.3 client server

**Additional information**
I was playing a different game that utilizes steamworks for some multiplayer functionality (IE. friends quick joining) named Deep Rock Galactic (Though any game showing as playing will likely cause this). I prefer to host a client based server over a dedicated myself. 

The server list shows the correct IP when making a join attempt but does not appear to even attempt a connection, I even tried manually typing 127.0.0.1 as well to find this does not connect.

I tried going to the main menu (Closing the server) and rehosting which didn't fix it. I even restarted the game fully and rehosted which also didn't but had 2 copies of barotrauma running (My steam copy to direct-connect to myself, which normally works fine). It wasn't until I reached "Playing Barotrauma" as my steam status was anyone able to connect at all.

debugging it, I saw no code triggered in any of the servers packet read / new connection auth or steam auth areas of code, I even tried some breakpoints in the networking library, so I think it may be on the clients side in some form and not even attempting the connection.

It seems the client connecting to a server via IP with steam enabled just cannot initiate a connection to the server, I don't know why this is the case - but it is effectively meaning if I host via a client (And not the dedicated) I am unnecessarily unable to play anything else in my library.

The expected behaviour is for steam friends to be unable to connect using the friends list, but able to connect using the server list, The client server should act like the dedicated server checking steam auth with friends joining as an extra for clients.

**Comment by Regalis11** [comment]
The client-server-separation branch (which was merged to dev in 49f5a9c) most likely fixes this. Now you can only host servers using the dedicated server, which doesn't initialize a Steam client or register as "Playing Barotrauma" on Steam.

**Comment by NilanthAnimosus** [comment]
I'm thinking that too, but I won't have an easy time testing it until the next update or compiling it myself where nobody could play on it given the scope of changes so i'm going to wait off on hosting myself until then.

**Comment by NilanthAnimosus** [comment]
I believe this is likely indeed fixed with version 0.8.9.4/0.8.9.5, I have had what appears to be a successful connection now while steam thinks I am running a different game started after barotrauma.
