### ISSUE TITLE
[1.0] Kastrull caught clipping through Military Armoury module

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11408]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar to #10644. 
The Kastrull clipped into a military outpost's armoury module. Unsure if the AI behaviour seen in Figure 1 is caused by this, or if it's unrelated. Save file attached.
[Kastrull x Outpost.zip](https://github.com/Regalis11/Barotrauma/files/10865624/Kastrull.x.Outpost.zip)

![image](https://user-images.githubusercontent.com/105495756/222274353-248a61df-415b-4a80-b4fd-444d55863493.png)
_Figure 1. Military Merchant displaying odd behaviour as Kastrull's fin clips through the floor._

![image](https://user-images.githubusercontent.com/105495756/222274375-dfe8e7cf-0fe5-43ef-8cff-7fa6d94c1d11.png)
_Figure 2. Status Monitor showing outpost modules._

![image](https://user-images.githubusercontent.com/105495756/222274389-0cf86d1c-88f5-4498-b033-3ad20d6d45cb.png)
_Figure 3. Level seed._

![image](https://user-images.githubusercontent.com/105495756/222274496-4fdd9f3e-b71c-4eb5-8cb8-88eba3baea28.png)
_Figure 4. Kastrull gun looking at the outpost wall. Notice the submarine hull merging with the outpost wall._

### Bug prevalence

Just once

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
The AI behavior is probably unrelated.

**Comment by Regalis11** [comment]
Does not seem to occur in the latest unstable, closing
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/95b50736-a015-4362-8ba8-76115f359fe4)
