### ISSUE TITLE
[1.0] Chlorine can be thrown

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11409]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar to #11049.

Chlorine can be thrown. It doesn't do anything when thrown, it's just an object players can throw. As far as I know, this and Sulphurite are the only items which have no effect when thrown but _can_ be thrown. Whilst this doesn't cause any issues (that we know of), I'm reporting it for the sake of consistency as I reported Sulphurite being thrown. 

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c569b3f3f062991a5d16234dac33d2654a1af230

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
