### ISSUE TITLE
[1.0] PUCS Suit Shoulder Cap Clipping Issue

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11403]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a very minor bug; the shoulder cap near the helmet of the PUCS suit has a clipping issue which causes it to flicker above and behind the helmet. Images below to try and help detail the problem.

![image](https://user-images.githubusercontent.com/105495756/222257832-fbfa7c23-a112-4910-aac7-6ef01e9e3e01.png)
_Figure 1. PUCS suit with shoulder cap hidden behind helmet._

![image](https://user-images.githubusercontent.com/105495756/222257868-82be2beb-6c63-44af-bea9-86202a2f8732.png)
_Figure 2. PUCS suit with shoulder cap in front of helmet._

### Bug prevalence

Happens regularly

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Couldn't repro

**Comment by Wheatley1002** [comment]
The issue happened in a multiplayer P2P environment, perhaps it's related to desync or a multiplayer issue?

**Comment by Regalis11** [comment]
No known steps to repro, closing
