### ISSUE TITLE
Artifact holder depth and position 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11402]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The artifacts seem misaligned and appear in front of the holder

Change these in Itemcontainer:
` itempos="130,-180" containedspritedepth="0.81"`

Before
![image](https://user-images.githubusercontent.com/73229309/222208169-d6092f58-b018-45ea-a3ef-b0dcc6525ea8.png)

After
![image](https://user-images.githubusercontent.com/73229309/222207978-8d2502f1-0612-4d28-a62a-e4399c14c2a3.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5c3a3356e3c76e56ce4e5303654b7b15cbee713c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
