### ISSUE TITLE
Reputation carries over into NG+

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11401]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After finishing the ending, your reputation carries over into New game plus, which doesnt make much sense lore  wise and gamplay wise, which is why im reporting it. 

### Reproduction steps

1.Finish the game and get sent back to the beginning
2.Refer your reputations, all of them will be the same as they previously were

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fc31737eacbb9c22ae45d265cb05825506a061be

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
