### ISSUE TITLE
[1.0] Ready Checks are ultra wide

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11407]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm going to be honest, I thought this was intentional. It was only flagged as an issue when Hex joined the test session temporarily and immediately noticed the ready check was much wider than it is in the current stable. 

![image](https://user-images.githubusercontent.com/105495756/222262896-f47a5258-1b0b-44a1-a4b2-e1ffe2159786.png)

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3db802c18133804e16da19237fdd9a618c6dc69f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
