### ISSUE TITLE
Exosuit does not muffle sounds when worn

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11406]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the player wears any diving suit, local chat around them is muffled. When the player wears the Exosuit, this does not happen. 
It is expected that the largest suit in the game as of writing would muffle the local chat of other players when the suit is worn. 

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/446dec546f258474f4b26591fdd6b4066c6d8045

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
