### ISSUE TITLE
[1.0] Diving Suit and FB3K lights still show when inside the clown crate

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11413]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a player wearing a diving suit or FB3K enters a clown crate, their lights still work as if they were not inside the crate. Diving suits can even move their head lights around as demonstrated in the images below.

![image](https://user-images.githubusercontent.com/105495756/222258398-2d024d06-7c39-4311-9f3f-0b5de7830e0e.png)
_Figure 1. Diving suit light pointing down._

![image](https://user-images.githubusercontent.com/105495756/222258404-d58ffe92-163f-472c-885c-e8765f3a61ff.png)
_Figure 2. Diving suit light pointing right._

![image](https://user-images.githubusercontent.com/105495756/222258414-a54538b3-f407-46e2-8ece-67f5c986a2e7.png)
_Figure 3. Diving suit light pointing up._

![image](https://user-images.githubusercontent.com/105495756/222258431-0e519bc5-61c2-4c58-b25c-e290979d1146.png)
_Figure 4. Crate without a player inside (to show the lack of lighting)._

![image](https://user-images.githubusercontent.com/105495756/222280800-64172ec2-a1d9-4488-a2d9-889e8f19efb9.png)
_Figure 5. FB3K's lighting shown over the clown crate._

![image](https://user-images.githubusercontent.com/105495756/222280818-1510b38f-21ae-4c01-96f8-31da3a8712e8.png)
_Figure 6. FB3K's lighting shown over the clown crate (highlighted with red pen to show lighting areas)._

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3dbece9bf67c71ee87740695ed37fbb462884ed0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
