### ISSUE TITLE
[1.0] FB3K fabrication recipe is incredibly specific

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11412]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The FB3K can only be crafted in one very specific method shown in Figure 1. This is problematic as it is not immediately apparent to players how to fit 50 bananas into the fabrication unit, as for literally every other item in the game you have to put the ingredients in the fabricator's slots. One of the methods players use to get 50 bananas into the fabrication slots is to put a metal crate in one of the slots that contains all the ingredients. This does not work however, and causes the ingredients to drop onto the floor.

This can cause issues as players assume you cannot craft the FB3K due to the unconventional and unique crafting method you need to utilise in order to make it. Additionally, had it not been for Hawkins (word of mouth from another player), we would not have been able to make the FB3K at all.

![image](https://user-images.githubusercontent.com/105495756/222280392-85600a83-2fd2-41f7-b610-3990393794dd.png)
_Figure 1. Only known crafting method for the FB3K._

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6f8fd3c7fa7873eaa19d46ce51f2667176a2fb68

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
