### ISSUE TITLE
[1.0] Emergency Transmission spawned nearly 1k beyond the map's border

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11411]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the final level entrance, an Emergency Transmission ping appeared on the navigation terminal pointing the submarine nearly 1,000m beyond the map's boundaries. Examining the issue in freecam showed nothing on the target's supposed location. I took a screenshot of the whole map to show nothing of importance being included.

![image](https://user-images.githubusercontent.com/105495756/222279731-17bb59c7-cf70-42ca-b059-cd1d8c90ce10.png)
_Figure 1. Navigation Terminal showing Emergency Transmission ping._

![image](https://user-images.githubusercontent.com/105495756/222279769-b0f7c8b2-92a7-42eb-840a-db0f7ead2295.png)
_Figure 2. Freecam screenshot of entire map._

### Bug prevalence

Just once

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/940bb8e0785c39b57450d8b16fdd3e15b9157701

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
