### ISSUE TITLE
[1.0] Abyss Mining mission spawned 166m away from the start location

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11418]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon starting an abyssal mining mission, I was shocked to realise that the target marker was only 166m away from our current location. Assuming this was another instance of #11345, I went towards it expecting the marker to change. To my continued shock, it did not. The mission objective was right on the side of the wall outside of a cave.

This happened in a multiplayer campaign hosted over P2P steam connection. Save attached:
[Abyss Mining I think I downloaded the saves an hour ago and honestly I forgot.zip](https://github.com/Regalis11/Barotrauma/files/10866012/Abyss.Mining.I.think.I.downloaded.the.saves.an.hour.ago.and.honestly.I.forgot.zip)

![image](https://user-images.githubusercontent.com/105495756/222276789-aeeafd07-95aa-4754-9f38-a70cbd785495.png)
_Figure 1. Image showing abyssal mining mission._

![image](https://user-images.githubusercontent.com/105495756/222276804-15149f94-c91a-4e86-bfad-b0777b45fe42.png)
_Figure 2. Navigation showing the mission ping only 166m away._

![image](https://user-images.githubusercontent.com/105495756/222276821-c53f034f-54bc-430b-8730-01a98f97e23e.png)
_Figure 3. Submarine next to mission ping showing it was, in fact, 166m away from the start location._

![image](https://user-images.githubusercontent.com/105495756/222276838-8c8635c1-d285-4d69-837d-90e59a6b4001.png)
_Figure 4. Level seed._

### Bug prevalence

Just once

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0e41dc51553d53883093aadd4ec629a5b3bec3b7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
