### ISSUE TITLE
[1.0] Pylons act as physical barriers but do not show up on the sonar once destroyed

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11417]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The pylon does not show up as a physical object on the navigation terminal once it is destroyed, yet it prevents the submarine from moving. Every other physical object which prevents movement in the game shows up on the navigation terminal or sonar monitor; as far as I know this is the only exception. 

This was problematic for our situation as our Kastrull drone had been disabled in front of the pylon and we were unable to retrieve it due to the pylon blocking our way, despite no feedback from the navigation terminal to hint as to why the ship was unable to move.

![image](https://user-images.githubusercontent.com/105495756/222282576-9291b83b-7837-4a07-b779-79040f5af218.png)
_Figure 1. The ship trying to move from the Navigation Terminal's perspective._ 

![image](https://user-images.githubusercontent.com/105495756/222282586-3fd3156c-ec1d-4d5b-b9c9-74bbff0a6b9f.png)
_Figure 2. The ship trying to move from a freecam perspective._

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0237e4f48c23c419e00e719f9447c14b973e2a5a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
