### ISSUE TITLE
[1.0] The Navigation Console is the only sonar that works in the final area (impacts drones and handheld sonar)

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11414]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Navigation Console is the only device which can register the final area's walls. The handheld sonar and drone control station (idk the official name) both show absolutely nothing on sonar. This makes navigation using them impossible.

![image](https://user-images.githubusercontent.com/105495756/222282178-efbf64e2-55b1-4f50-af80-57b66ce8a568.png)
_Figure 1. End location from the Drone controller's perspective._

![image](https://user-images.githubusercontent.com/105495756/222282223-9b4db32e-cd5a-47ab-8389-795cb72f2110.png)
_Figure 2. End location from the Navigation Console's perspective._

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6d9348a9f6fa380ac9b465c444f58ae5edcd579a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
