### ISSUE TITLE
Minerals using the wrong sprites

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11421]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As you can see some minerals are using the wrong sprites:

![image](https://user-images.githubusercontent.com/73229309/222296716-b286b400-f25b-4f98-9884-14eecc880e6f.png)

![image](https://user-images.githubusercontent.com/73229309/222296012-4cea848e-cb70-4935-acc9-e961e88a53b7.png)

Also, you cannot distinguish TRIPHYLITE TITANITE CRYOLITE
CASSIERITE and SYLVITE seem to also be using the same sprite

There are 2 unused mineral sprites (yellow) and two lookalikes (red/purple)

### Version

Faction/endgame test branch

**Comment by ubertpendragon** [comment]
Forgot to mention that CASSIERITE and SYLVITE seem to also be using the same sprite

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/a34eff07794e027e5e84910b50eed79ea2135411

Tested and couldn't find any issues, closing.
