### ISSUE TITLE
[1.0] [Spoilers] Unobtainable achievements

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11426]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

First off - I am not certain that this is unintentional, but considering that all but 2 achievements are obtainable, I thought it best to at least bring it up.

Of the new achievements added recently, some are obtainable in the current 0.21 stable version (monster and some other misc missions), and some are obtainable only by using the 1.0 build (mostly just the hireable NPCs). These all work fine and award the steam achievements as expected, with the exception of the "Ascension" and "The Grandest of Jesters" achievements (at least as far as I can tell).

The description for these achievements seem to imply that they should be awarded for completing the Church of Husk and Clown questlines, however I am unable to obtain the achievements when doing so.

If this isn't an oversight, and the achievements just haven't been implemented yet, then this ticket can be ignored.

### Reproduction steps

1. start a singleplayer campaign
2. enable cheats, and use command `setcampaignmetadata waytoascension 8`
3. travel between outposts until you find the ascension event (don't do the event yet)
4. alt+F4 the game
5. load up the campaign again (so cheats are no longer enabled)
6. **Ascend**
7. observe that you have not received the achievement for ascending

Similar methodology for the clown achievement

This could alternatively be done by completing the entire questline with no cheats (like I did the first time around) but I wouldn't recommend it, it took like 10 hours.

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
> enable cheats, and use command setcampaignmetadata waytoascension 8

You can't get achievements if you enable cheats.

**Comment by Vykn** [comment]
![image](https://user-images.githubusercontent.com/37850646/222417032-f27cc48f-9891-461d-a429-8513700a5949.png)
I used cheats all throughout my singleplayer campaign and was able to get all the other achievements just by closing and reopening the game before triggering the events that gave the achievements.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d15041bc24b087eff1545601f3bc4b6c10c6cac

**Comment by Rokvach** [comment]
Working correctly, closing.
