### ISSUE TITLE
Z-fighting in some outpost modules

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11428]
Schematic:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/7478eaf0-3216-47e8-a465-b759a5f1e3a2)

Plant:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/50dd1d5a-dfad-4df6-a6ea-fc748908bea7)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9161c70dc17c7ca028e0d44de220f56c42c26ea2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
