### ISSUE TITLE
Hidden in game parameter hidden for gaps

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11422]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

hiddeningame property isn't exposed for gaps - no checkbox in editor (and not editable w/ setentityproperties)

it should be because hidden in game gaps do not show as breach for purpose of status monitor integrity

### Reproduction steps

1. place a gap
2. look for "hidden in game" checkbox 

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/5539221af8e85c43073347b0149d8e4712977b06

**Comment by NilanthAnimosus** [comment]
Tested against Dev commit https://github.com/Regalis11/Barotrauma-development/commit/b43dc09824df214625111f73211fc2873cf2ddc8, no issues found, closing.
