### ISSUE TITLE
Thermal Goggles don't register a signature with Tiger Thresher Hatchlings

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11420]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Tiger Thresher Hatchling appears to be the only hatchling variant without a thermal signature on thermal goggles. Additionally, all the adult variants of the hatchling creatures have thermal signatures _including_ the Tiger Thresher. It is not apparent as to why the Tiger Thresher Hatchling is missing the thermal signature. 

The XML for the Tiger Thresher Hatchling does not include any parameters which would prevent the signature from registering (see figure 4).

![image](https://user-images.githubusercontent.com/105495756/222289865-58d37008-ae91-4754-a284-096de9b5eee8.png)
_Figure 1. The Tiger Thresher Hatchling without a thermal signature, next to a Crawler Hatchling which has a thermal signature._

![image](https://user-images.githubusercontent.com/105495756/222289921-83d13bc3-bc04-4134-aaf0-7f4a792527a0.png)
_Figure 2. Tiger Thresher having a thermal signature._

![image](https://user-images.githubusercontent.com/105495756/222289948-6b014d7e-5310-497c-90fa-7ca4d46d2439.png)
_Figure 3. Mudraptor Hatchling having a thermal signature._

![image](https://user-images.githubusercontent.com/105495756/222290293-9589c729-6418-42b3-8d8f-cc28c9055e69.png)
_Figure 4. Tiger Thresher Hatchling XML code._

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b6081115e183ed0844ef485ac1979cab0bac151

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
