### ISSUE TITLE
Minor flooding on entering a city with DockingModule_01_Colony

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11433]
Seems to happen always when entering a city with Herja (if you can't repro, I can give a save file): at the beginning, there's always some water on the floor, not so much that it would be an issue, but it's still a bit weird.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b7b6637d-b589-4b36-bbd9-0675c007e12d)

**Comment by Regalis11** [comment]
It seems this is an issue with the module itself, there's a bit of water in the bottom-most hull. No idea how that could've happened though

**Comment by Regalis11** [comment]
Seemed to apply to both colony docking modules, fixed in https://github.com/Regalis11/Barotrauma-development/commit/e8ea480c4f53bb5a18884df34327db41d71f9544

**Comment by Rokvach** [comment]
There seems to still be a very small amount of water when you load into the colony, but not enough that the water stays in the module like previously
![image](https://user-images.githubusercontent.com/7299826/231721259-5a3d683a-39f7-4560-b352-e3279126e71e.png)

**Comment by Regalis11** [comment]
Looks like I missed one small hull, fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd9d1adb4556f6dc9f8b14e273ecebaa0730af1a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
