### ISSUE TITLE
Bots may fail to reach items just behind a closed door

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11435]
Bots fail to reach items if the last node is at a closed door (?). They should open the door, but for some reason fail to do that and keep walking towards it:

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/91f32a82-d60f-413b-a07f-bc973d27b208)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/5e6f30f8-cac5-43aa-ab38-6955c9e69e30)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9592
