### ISSUE TITLE
Herja: missing waypoint link from the inner airlock door

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11432]
A tiny detail -> a huge issue in practice, as the bots can't fix the pump or the outer door when the inner door is closed.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/bc9e21f6-9a57-4964-b46a-f621bd2f50a1)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c42c438d41033ca51419caeb04853a50fd42c9b
