### ISSUE TITLE
Fabricator and a linked container windows overlap badly by default

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11430]
At least in Herja (using 2560x1440), this what I get when I select the container linked to the fabricator:

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/afab936a-fa1b-46a2-8dc8-049c570f8908)

Resetting the windows via the button fixes it.

**Comment by itchyOwl** [comment]
The issue is made worse by the fact that you can interact with the items in the container through the overlapping fabricator ui.

**Comment by Onyvox** [comment]
Whats interesting is that when I noticed it on Camel, I've tested it with and without mods - still present.
Verified files - 6 were out of sync - tested issue after fixing files - still present.

If you follow two paths of opening the Fabricator (Fab) and the linked Large Cabinet (LC) - the issue would appear or not.
For example:
1. Open Fab - shows Fab UI
2. Open LC - shows both Fab and LC UIspaced out correctly
3. Open Fab - shows Fab UI
4. Open LC - shows both Fab and LC UIspaced out correctly

Or example 2:
1. Open LC - shows both Fab and LC UI spaced out correctly
2. Open Fab - shows Fab UI
3. Open LC - shows overlapping Fab and LC UI
4. Open Fab - shows Fab UI
5. Open LC - shows overlapping Fab and LC UI

Resetting position fixes the issue.
The LC doesn't have 'Display Side by Side When Linked' (DSSWL) enabled.
If DSSWL is enabled for both - everything works correctly all the time.
If the DSSWL applied in reverse - both examples above would reflect that change accordingly.

**Comment by Regalis11** [comment]
The changes in https://github.com/Regalis11/Barotrauma-development/commit/bf896fa601c3790b430a6f5f4b1060b66312c868 seem to have fixed this.

**Comment by Jasontti** [comment]
Tested.
Camels and remoras medical fabs cabinet is not set "Display Side by Side When Linked"
No other issues found.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c78cf57fd87cd827365f27edcf2d6a8830a32074 and https://github.com/Regalis11/Barotrauma-development/commit/7071a1b9e7e89db22677ca3b32109733f2fe742e

**Comment by Jasontti** [comment]
Tested.
No further issues found.
Closing ticket.
