### ISSUE TITLE
Bots stuck with operate item/fix leak objective

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11440]
Noticed that it's possible for the bots to stuck when they are _not_ in range (but for some reason cannot get closer). The target gap here was at the top left from the character. I think the same happened when operating turrets and possibly getting dragged away by water.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/341dba2b-35c2-4009-a8ac-c9154c2fd15e)

**Comment by Regalis11** [comment]
No known steps to repro, closing
