### ISSUE TITLE
Achievements can be obtained by using cheats

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11447]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Mentioned briefly in [#11426](https://github.com/Regalis11/Barotrauma/issues/11426), but players can use cheats to unlock prerequisites of achievements, restart the game, and then obtain the achievement.

Examples include setting questline metadata to the second last position, or spawning in powerful ammunition before hunting an abyss creature. 

Additionally, achievements are even available in the sub editor, with no need to restart the game. For example: spawning in an endworm, disabling enemy AI, and shooting it to death will grant the achievement.

### Reproduction steps

1. load up a campaign
2. enable cheats and spawn in any items you want/set campaign metadata/set reputation
3. save
4. restart Barotrauma
5. load up the campaign, and achievements will be available again

### Bug prevalence

Just once

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ca86412d744b3a7cb37a3cdefdb51b6173ff2d65 and https://github.com/Regalis11/Barotrauma-development/commit/fd3a6e0b390336a88089a1e7b3bd5bf8255b2eaf
