### ISSUE TITLE
Door desync causing getting stuck on a side

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#11448]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've had this problem for a while just never felt like reporting it because it just seemed like usual multiplayer desync, but it doesn't hurt to report it.
When I'm walking through a door and as I am the door closes, sometimes i think the client thinks I'm on the other side, but the server says I'm on the side I started. If I continue walking, on my side, it looks like I'm stuck to the opposite side of the door.

### Reproduction steps

1. start multiplayer game
2. try to close it at the same time you're under it
3. if it doesn't happen, repeat and try varying timing

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3a44f1a5e995155ac4c09d470679788d9b65139e

**Comment by evilfactory** [comment]
Tested this on the 1.1.1.0 build, can't tell if it's better, but the desync still seems to happen.

https://user-images.githubusercontent.com/36804725/225036633-f5d64f5d-4295-4827-9acf-80da62eac3c2.mp4

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
