### ISSUE TITLE
can't copy paste wire items in editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11443]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

placing a loose wire in regular editing mode (i.e., not in wiring mode) and trying to copy-paste it doesn't work

was able to copy-paste everything but the loose wire

search yielded #2669

### Reproduction steps

1. place a loose wire (i.e., green wire) 
2. select loose wire
3.ctrl + c / ctrl + drag + drop
4. ctrl + v 
5. no loose wire

left is some random items being copy pasted all together to the right.

![image](https://user-images.githubusercontent.com/5103517/222595793-81f57996-0300-4516-b6f7-7610f860ee89.png)

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c61558a718be98531c9ca4764e332de12d9ee1ab

**Comment by Jasontti** [comment]
Tested. Wires cut, copy and paste. Closing
