### ISSUE TITLE
Flamer doesn't damage mudraptor eggs.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11441]
Noticed during an abandoned outpost mission. Not sure if it's just mudraptor eggs, and whether it's just the flamer or fire in general.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/2d693386-49e7-4eaa-ba3f-e0f9db9f89e6)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/82f5430f168ed16eb696c8d2f0e017ade75a2485

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Except you can damage multiple doors with the flamer, overall using fire to damage a steel door doesn't make much sense either
![image](https://user-images.githubusercontent.com/7299826/231714940-5263ab28-7ba9-430e-b706-2c2df3733dd7.png)
