### ISSUE TITLE
Alien power cells can't be deconstructed, which feels inconsistent.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11442]

**Comment by cshingle** [comment]
I ran into this issue long ago and addressed in a mod. This is what I did. 
If you think Fulgurium is a bit too much for a full cell then maybe have go with Thorium.
```
      <Deconstruct time="20">
        <Item identifier="dementonite" />
        <Item identifier="fulgurium" mincondition="0.90" />
      </Deconstruct>
```

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/60dbfca91dad8009a4edfd8d309c9e13e7d5c669. Tested & merged, closing.
