### ISSUE TITLE
Crossing hulls with ladder will sometimes stop you from doing so.

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#11449]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/12504812/222760381-b96e5df7-6324-4e6a-b0ec-ea05524c28b5.mp4

When attempting to climb a ladder sometimes you will get stuck on it, not able to move up it (might be down as well but have not experienced it), to resolve it you have to drop off the ladder for a second or two and then climb again. Just letting go quickly and grabbing again will not work. Seems to only happen between hull changes as in a long ladder in a single hull will not cause this issue.

Does not matter if it is a door you are going through either, cause I have had this happen when climbing through a room with two hulls stacked.

Also with the version it seems to be both unstable and stable.

### Reproduction steps

1. No real simple way to recreate the issue, just pops up on occasion well playing.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Ive recently actually had this issue aswell, no clue what causes it

**Comment by Rehexr** [comment]
Singleplayer is where i had the issue

**Comment by itchyOwl** [comment]
Ok, it's possible the same issue as #11219, to which there might be a fix implemented already.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
