### ISSUE TITLE
Put All Translation Files Into One Folder- Feature Request 

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1144]
Purpose:
Makes translating the game easier.

P.S.: Where I can find current translation files for English language?

**Comment by Regalis11** [comment]
They are already in one place, Content/Texts.

**Comment by rico6822** [comment]
Oh ok.

**Comment by rico6822** [comment]
> They are already in one place, Content/Texts.

Ok but what about files with conversations and devices.

**Comment by Regalis11** [comment]
Ah right, NPC conversations are one exception. They're in Content/NPCConversations. There are no translation files for the devices in the vanilla game, but if you want to translate them, you can include them in the same text file as the rest of the text (see the instructions in the comments on top of EnglishVanilla.xml).

**Comment by rico6822** [comment]
> Ah right, NPC conversations are one exception. They're in Content/NPCConversations. There are no translation files for the devices in the vanilla game, but if you want to translate them, you can include them in the same text file as the rest of the text (see the instructions in the comments at the beginning of EnglishVanilla.xml).

Thank you. I also have I question: Will my Polish translation of the game become official steam translation once I complete it?

**Comment by Regalis11** [comment]
Sorry, but I don't think we'll be using fan-made translations in the official game. We're planning on getting the localization done by professional translators to make sure they're high quality. And I don't mean to dismiss your Polish writing skills, it's just that we don't speak Polish or any of the other languages the game is going to be localized to, so it's very hard for us to verify that a fan-made translation is good (not just grammatically correct, but well written and similar in tone to the English texts).

**Comment by rico6822** [comment]
> Sorry, but I don't think we'll be using fan-made translations in the official game. We're planning on getting the localization done by professional translators to make sure they're high quality. And I don't mean to dismiss your Polish writing skills, it's just that we don't speak Polish or any of the other languages the game is going to be localized to, so it's very hard for us to verify that a fan-made translation is good (not just grammatically correct, but well written and similar in tone to the English texts).

Will mods have ability to take forms of translations?

**Comment by Regalis11** [comment]
We're going to have built-in translation files for vanilla content, but those will be moddable and it's possible to add your own translations for modded content or vanilla content. So you can still share your translations in the Steam Workshop, and translate mods that don't have an official translation available.

And I'm sorry but we've already decided to use professional translators.
