### ISSUE TITLE
Wrecked lights/sprites are incorrectly scaled relative to eachother

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11451]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems that the lights are scaled incorrectly on wrecked lamps, making them always smaller than the lamp.
![image](https://user-images.githubusercontent.com/104232152/222905184-5a2c266f-a3e4-4ad7-8a5e-b08e4906f4de.png)
This relative scale stays even when changing the scale of the lamp.

### Reproduction steps

1.Try putting down some wrecked lamps in the editor
2.Turn them on
3.Notice the light is incorrectly scaled

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/deee7956aeed54630187862d47b91a1ddabbd928

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
