### ISSUE TITLE
"New Supplies" window doesn't close when closing the shop with right click

### ISSUE THREAD

**Issue by JaydenCallan** [Regalis11/Barotrauma#11455]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Buying supplies and closing the shop window using right click without closing the "New Supplies" tab will allow you to move and interact with the game while the window is still up.

### Reproduction steps

1. Open any shop and purchase any item
2. Right click beside the "New Supplies" tab
3. Walk around freely without clicking "Ok"

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I wouldn't necessarily consider this a bug: it doesn't apply to just the "new supplies" message box, but all message boxes, which never prevent you from moving. That was an intentional choice, as otherwise message boxes could immobilize you even in dangerous situations. Have you noticed it causing some kind of concrete issues or did you just find it weird?

**Comment by JaydenCallan** [comment]
> Thank you for the report!
> 
> I wouldn't necessarily consider this a bug: it doesn't apply to just the "new supplies" message box, but all message boxes, which never prevent you from moving. That was an intentional choice, as otherwise message boxes could immobilize you even in dangerous situations. It is also intentional that message boxes need to be closed by clicking "ok" instead of right clicking: otherwise you might accidentally dismiss message boxes if one happens to pop up when you're using RMB for something else.
> 
> Have you noticed it causing some kind of concrete issues or did you just find it weird?

I had assumed it was a bug since the screen was dark, and it allows you to close the shop, I didn't think it was intentional. Sorry!
