### ISSUE TITLE
AI 'overwhelmed' and ineffective when too many repair orders are queued up

### ISSUE THREAD

**Issue by Lynkzz** [Regalis11/Barotrauma#1145]
**Description**
AI seems to get 'overwhelmed' when there are too many repair jobs to do. They either get stuck in place trying to repair something (but not actually doing it) or  pathing back and forth (seemingly) between jobs (but never reaching either). When they don't get stuck they seem to repair only the minimum amount possible, causing them to have to return to the item a couple of seconds later to repair it again, thus making no progress on the overall repairs.

**Steps To Reproduce**
- Load up game with any sub and simply do nothing (allow multiple things to break down)
- Set the AI to repair (either job-specific or not, they seemingly can handle neither)

Here's a video demonstrating the issue (read description):
https://www.youtube.com/watch?v=h0MOk-UC7-I

**Version**
0.8.9.3 (Steam Closed Alpha)

**Additional information**
The issue is more prevalent on the Orca, as it seems to break down too quickly for the AI to manage by itself (so the problem happens by itself even if you set everyone to repairs from the start). The problem might be exacerbated by the fact that the AI seems to get stuck next to the engine by default on the Orca. The AI seems to be able to manage the Humpback well (if you set everyone to repair form the start) until something happens which queues up too many repair jobs.

**Comment by itchyOwl** [comment]
Should be fixed in the human-ai branch, but let's keep it open until properly tested.
