### ISSUE TITLE
Lamps sprite light is always fully bright, despite the strength of alpha

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11452]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This seems to be the last major issue related to the lights being changed, and its pretty conclusive. It seems, that the sprite that the lamp uses to look "lit up" (not the actual light illuminating the area) is always fully bright when enabled (with the exeption of the light components, as they look normal), even at alpha of 5, as is seen here: 
![image](https://user-images.githubusercontent.com/104232152/222905622-974b76ea-840e-4e7d-af77-8c50158bd0c2.png)
This is notably distracting, especially on the workshop lamp, as the effect is usually subtle. (alpha of 111 usually, yet it looks like 255)
This has been the main cause of people complaining about issues when it comes to using lamps in a custom way, as the lamps used for custom interfaces, for example, would always show up at full brightness, causing them to bleed painfully through what would usually be subtle effects, especially if the light is put below the depth of an item.
Therefore, this is quite the issue in some uses and it seems to be a side effect of how lights were changed in https://github.com/Regalis11/Barotrauma/issues/10900

And in conclusion: The alpha of a lamp does not affect the brightness of the lamp itself, only its surrounding brightness

### Reproduction steps

1.Put down a lamp (any other besides the light components)
2.Enable it, and set the alpha to anything lower than 255
3.Notice that the "lit" sprite on the lamp itself, does not get affected by alpha strenght, only the surrounding light

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Neatly adressed. However a couple of decorative lamps were seemingly not adressed with this, and still shine fully bright at any alpha, most notably the workshop bench, medical monitor and light tower 
![image](https://user-images.githubusercontent.com/104232152/225046381-146db44c-5939-4d7e-b5a1-ccf80e8e44c3.png)

**Comment by Rehexr** [comment]
Alright, coming around here one more time to make sure i got everything, so heres the comprehensive list of everything still having this issue: 
![image](https://user-images.githubusercontent.com/104232152/226135005-db1e5ca1-c26f-4257-9375-bd0f81beb30b.png)
1.Junction boxes
2.Light Tower
3.Heater
4.Research Station
5. All 3 X-ray  screens
6. Research Table
7. All 3 Research Containment Tanks
8. Status Monitor
9. All neon light letters, symbols and numbers
10. Deconstructor
(Special issues with these couple, they all have an odd single light in the middle when at alpha 255)
![image](https://user-images.githubusercontent.com/104232152/226135191-ca044dd9-1f3e-4bf5-9ae2-76d16bf85e31.png)
11. Navigation Terminal
12. Status monitor
13. Fabricator
14. Medical Fabricator
And at last, theres a very specific issue with the Advertisment, specifically the shipyard service one, as atm its light is broken, since it doesnt spawn with any range, which it needs at least 1 for in order for the light to work
![image](https://user-images.githubusercontent.com/104232152/226135262-d3a1844d-dc77-4477-8f1b-f51858908533.png)
Hope this is comprehensive enough

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by 1170991249** [comment]
Is this issue really solved? still got this issue happens.
![QQ图片20230717060017](https://github.com/Regalis11/Barotrauma/assets/25667549/367060c5-5ed3-4262-9dfc-094e3735e357)
