### ISSUE TITLE
Alien Syndicate never plays

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11467]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Alien Syndicate, one of the music tracks, is not present in the sounds.xml file, and never plays during the game.

Checked in both 0.21 & 1.0 - not present in either.

### Reproduction steps

1. Play the game
2. Notice that alien syndicate never plays

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
![image](https://user-images.githubusercontent.com/14351070/223360528-d5fd2632-b560-4402-b67f-db7b30721a65.png)
???

**Comment by Vykn** [comment]
I genuinely have no idea how I missed this. Maybe I made a mistake while searching for it. Apologies for the error.

Closing because this isn't an issue, I'm just blind.
