### ISSUE TITLE
Submarines do not activate LevelTrigger StatusEffects

### ISSUE THREAD

**Issue by dakkhuza** [Regalis11/Barotrauma#11461]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

LevelTriggers can be used to activate StatusEffects, as you can see [here](https://github.com/Regalis11/Barotrauma/blob/48c66adcdcb50d28d1b735218f5dbc10b9a971da/Barotrauma/BarotraumaShared/SharedSource/Map/Levels/LevelObjects/LevelTrigger.cs#L635)

However, if the triggerer is a submarine. none of the status effects will activate as the game only checks for Characters or Items.

This makes it impossible to create, for example, a stalactite that drops off the ceiling onto the submarine when it gets close.

### Reproduction steps

1. Create a LevelTrigger that is triggered by a submarine that has status effects
2. Set a break point [here](https://github.com/Regalis11/Barotrauma/blob/48c66adcdcb50d28d1b735218f5dbc10b9a971da/Barotrauma/BarotraumaShared/SharedSource/Map/Levels/LevelObjects/LevelTrigger.cs#L638)
3. Load into a level and teleport the submarine into the LevelTrigger
4. Observe the fact that none of the status effects get triggered 

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2897e52548e1db07c35c231b2e38d3e5ea382eb

**Comment by Regalis11** [comment]
For testing: you can use this modified XML to make the "web" levelobjects in the ridge and aphotic plateau emit particles when triggered by a sub. 
[CommonLevelObjects.txt](https://github.com/Regalis11/Barotrauma/files/10921606/CommonLevelObjects.txt)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
