### ISSUE TITLE
What is The "Swarm" Mission About?

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1147]
From what I see in xml files only 1 crawler has to be killed to win.

I have decided to refer in my translated version of the game to a creature which has to be killed as "specific".

**Comment by Regalis11** [comment]
It's an upcoming mission that hasn't been fully implemented yet (which is why it's been commented out for now). The idea is to make it a monster mission, but instead of one big target, you'll have to kill a big swarm of crawlers.
