### ISSUE TITLE
Clown masks prevent you from slipping on banana peels, but not suits

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11472]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Having a full clown outfit on gives you immunity from slipping on bananas, which  is neat. Issue is, for some reason this immunity is given to you when wearing just the clown mask, while wearing just the clothes doesnt, which kinda doesnt make much sense.
I dont see how a clown mask gives you slipping resistance, unless this is intended to allow people who just wear the mask to bear the benefits.

Itd make sense if either both or just the clown outfit would give you the resistance, since the clownly shoes.

### Reproduction steps

1.Equip a clown mask
2.Walk over a banana peel
3.Note not tripping

1.1 Equip just a clown outfit
2.1. Walk over a banana peel
2.2 Note that you do infact trip

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/25e480bc7e78d6941ab4095cfa26235a5185015c

**Comment by Jasontti** [comment]
Tested, Wearing clown outfit or clown mask character doesn't slip on banana peel. Closing.
