### ISSUE TITLE
Medical Expertise has no effect on Bandage strength

### ISSUE THREAD

**Issue by Pyzaaa** [Regalis11/Barotrauma#11475]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Medical Expertise Talent description says "...Your Bandages are more effective.". However, it seems it has no effect on amount of burn/bleed status removed.
It also doesn't change the speed or duration of the healing effect

### Reproduction steps

1. Damage a character with over 30 burn/bleed status
2. Use a bandage on the damaged character by a doctor without Medical Expertise talent
3. Observe that the character is healed for 30 burn/bleed status

2.a Use a bandage on the damaged character by a doctor with Medical Expertise talent
3a. Observe that the character is still healed for 30 burn/bleed status

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c0a1336a4d64888d12e44e71376094a2f98ce40

**Comment by Jasontti** [comment]
Tested. Medical expertise correctly applies healing boost to bandages.
