### ISSUE TITLE
Thalamus wires cannot be hidden after death

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11470]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

For some reason thalamus wires will appear after the brain is killed, even if they have 0 alpha. 
It is my understanding that Thalamus unhides automatically the thalamus items, and I assume the sprite color/alpha also changes after death. Setting wires to be immune to damage does not prevent this

Here I'm connecting turrets using an invisible wire (hidden and 0 alpha) to activate the lights if a thalamus is alive:

![image](https://user-images.githubusercontent.com/73229309/223573448-49b556be-6a75-465c-93b3-9caec963122d.png)

After the brain is destroyed, the wire appears:

![image](https://user-images.githubusercontent.com/73229309/223573358-949ba94d-9953-4183-bc0c-5ba90ad38f53.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3f0cb938b5038a08e2ab2e32d4d050bb30dde3b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
