### ISSUE TITLE
NULL signal causes door activation

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#11473]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

basically null signal from memory component causes door to be constantly open and i think it shouldnt, cause you know, it is literally nothing?

Is that how it supposed to work?
[door with mem.zip](https://github.com/Regalis11/Barotrauma/files/10924546/door.with.mem.zip)

### Reproduction steps

1. get in editor
2. place memory component and door + text display
3. hook up door and text display to mem
4. start testing
5. ????
6. profit

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I asked about this on the sub building channel in Discord, and it seems there are valid uses for the empty strings: you can use them to e.g. set the outputs of components or empty a text display. So I don't think we'll be addressing this.

**Comment by PanmanS** [comment]
Oh well, let it be then. (I wish i could ask around sub building chat too)
