### ISSUE TITLE
Monsters can still spawn inside walls during nest missions

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11476]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/14351070/224039950-b01653dd-616a-4266-904f-fbf2bcb7b36e.png)

### Reproduction steps

Multiplayer mission mode, nest, seed appears to be SI5NCX1y. submarine barsuk. Version 1.0.7.0

![image](https://user-images.githubusercontent.com/14351070/224039982-968e9339-71f6-4bef-ab21-72ad0f3e1b02.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
