### ISSUE TITLE
Sealed Supply Crates do not exist in Vanilla

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#11481]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sealed Supply Crates cannot be found anywhere in the Vanilla game.

They are not sold in shops, and cannot be added to custom creations via the sub editor as they have the property ``hideinmenus="true"``

Additionally, they cannot be found in any wrecks as their preferred container is ``wreckstoragecab``  and their tag is ``crate`` and only Wreck1 has a crate shelf (but the crateshelf does not have the ``wreckstoragecab`` tag)

From containers.xml:
``
<Item name="" identifier="sealedsupplycrate" tags="crate" scale="0.5" linkable="true" pickdistance="150" showcontentsintooltip="true" impactsoundtag="impact_metal_heavy" hideinmenus="true">
    <PreferredContainer secondary="wreckstoragecab" spawnprobability="0.02"/>
    <Price baseprice="1250" sold="false" canbespecial="false" />
    
    <Sprite texture="containers.png" depth="0.54" sourcerect="562,563,147,86" origin="0.5,0.5" />
    <Body width="150" height="80" density="25" />
    <Holdable slots="RightHand+LeftHand" holdpos="0,-80" handle1="-30,14" handle2="30,14" aimable="false" msg="ItemMsgPickUpSelect" />
    ``

### Reproduction steps

1. Look for Sealed Supply Crates
2. They can't exist

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Wanted to elaborate. None of the wrecks have crate shelves beside the one in wreck1, even replacing the spot on the normal equivalent with cabinets for not much reason and they probably should have some, especially with a 2% spawn rate, but yeah thats all.

**Comment by aeondez** [comment]
Also, mathematically, assuming that Wreck1 is the only wreck with a crate shelf with the tag ``wreckstoragecab`` ,there's a 1 in 200 chance that a single Sealed Supply Crate would be encountered.

The spawn rate and/or the payout should be increased significantly because it feels petty to have to go through 200 wrecks just to find a crate worth 1250 marks.

**Comment by Regalis11** [comment]
Imo it's a good thing they no longer exist. I'd argue they are confusing: it's not clear what they are for, and we used to get lots of questions about how to open or use them (which isn't possible).
