### ISSUE TITLE
Cant do anything with out crashing! (Access to the path 'config_player.xml' is denied)

### ISSUE THREAD

**Issue by DeafeningDragon** [Regalis11/Barotrauma#11489]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

[crashreport (16).log](https://github.com/Regalis11/Barotrauma/files/10953031/crashreport.16.log)
i get this no matter what kind of audio i use  ie
[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/10953032/crashreport.15.log)
  common thing in both is that it is trying to "Attempting to open ALC device "OpenAL Soft on (dosen't matter what device)"  version of the game is 
![barotrama verion](https://user-images.githubusercontent.com/71092799/224597241-b2439fb6-8bc9-48ed-9c36-78235d305619.png)

### Reproduction steps

start the game 
 then click anywhere
 then click on any of the option in the menu 
then watch the game crash 

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The error seems to imply that your game is for some reason failing to access the config_player.xml file inside the game folder. I'm not entirely sure what could be causing this - could it somehow be the game folder is protected, preventing the game from modifying the files in it? Sorry for the inconvenience!

**Comment by DeafeningDragon** [comment]
windows 10 pro

**Comment by DeafeningDragon** [comment]
where would i go to see if that is the case

**Comment by DeafeningDragon** [comment]
i use steam to launch the game btw.

**Comment by DeafeningDragon** [comment]
sorry don't understand what I'm looking at as its in Russian and I read English and the the game is installed via steam
so is it the same process

**Comment by Elpatov** [comment]
> sorry don't understand what I'm looking at as its in Russian and I read English and the the game is installed via steam so is it the same process
We have indeed found a solution to this problem.  You need to grant full access to the root folder of the game. Do this as follows:
1) Right-click on the folder E:\SteamLibrary\steamapps\common\Barotrauma <—;
2) Select the "Security" section - change permissions - Change
3) Check the box for "Full access" for your user (preferably for both the user and the administrator);
4) Wait for the settings to be applied and close this window;
5) Select the "Security" section - advanced;
6) Check the box at the bottom "Replace all entries ..." at the very bottom of the window that opens;
7) Remove the "Read-only" attribute for this folder

After that, you need to delete the file E:\SteamLibrary\steamapps\common\Barotrauma\config_player.xml .  

Unsubscribe if it helped you.

**Comment by DeafeningDragon** [comment]
that worked thanks
