### ISSUE TITLE
Affiliation talent's effect stacks

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11494]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Apparently the affiliation talent is stackable, meaning you can gain ridiculous amounts of rep from a single mission (might affect the money reward too)? Report from Discord, haven't tried reproducing this myself yet.
![image](https://user-images.githubusercontent.com/14351070/224716107-05b0d0f7-fa45-4f14-af15-17e72baa1d35.png)

### Reproduction steps

Presumably:
1. Hire multiple captains, unlock affiliation on all of them?
2. Complete a mission for your affiliated faction

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6de0be66ff32e23e51cdeee80769061c406c0982 and https://github.com/Regalis11/Barotrauma-development/commit/929d3c3b3f3bd1cb00a87807660e4ccddfbd8f03

**Comment by Regalis11** [comment]
Tested in both SP and MP, could not spot any issues. Closing.
