### ISSUE TITLE
Problem With Translating PvP Mission to Polish- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1149]
How to translate second description, names of teams and other stuff like that?

**Comment by Regalis11** [comment]
You should use the following (missionidentifier being "pvpmission" in the case of the vanilla PvP mission):

MissionDescriptionNeutral.missionidentifier
MissionDescription1.missionidentifier
MissionDescription2.missionidentifier
MissionTeam1.missionidentifier
MissionTeam2.missionidentifier

Thanks for pointing this out, it should definitely be mentioned in the translation instructions!

**Comment by rico6822** [comment]
> You should use the following (missionidentifier being "pvpmission" in the case of the vanilla PvP mission):
> 
> MissionDescriptionNeutral.missionidentifier
> MissionDescription1.missionidentifier
> MissionDescription2.missionidentifier
> MissionTeam1.missionidentifier
> MissionTeam2.missionidentifier
> 
> Thanks for pointing this out, it should definitely be mentioned in the translation instructions!

Thank you.
