### ISSUE TITLE
You can make progress on the final clown mission in any outpost

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11493]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using FB3000 increases the value of clownhaven_peopleannoyed regardless of where you are, meaning you can annoy people in any outpost, and then insta-complete the clownhaven mission when you enter the correct location.

### Reproduction steps

1. Play the clown mission until you get FB3000 (or `setcampaignmetadata pathofthebikehorn 4`, `triggerevent pathofthebikehorn4`)
2. Use the weapons on outpost NPCs
3. Check campaign metadata with debugdraw + Ctrl+M, notice clownhaven_peopleannoyed increases
4. Get the value above 40 and you'll be able to complete the mission without doing anything in the outpost the mission actually takes place in.

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
