### ISSUE TITLE
No way to control what to display for which faction on custom outpost modules

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [Regalis11/Barotrauma#11491]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When creating a new outpost module, there is no way to tell the game what decoration/item belongs to which faction. So even saving a default module exactly how it is as a new module will cause you to see every decoration piece during campaign on that module no matter which faction is present on that outpost.

### Reproduction steps

1. Build an outpost module and decorate it with both coalition and separatist decorations
2. Group the separatists items and save the group as Separatists like the default modules.
3. Visit an outpost with your new module in campaign. All decorations for every faction will be visible.

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. Tested by creating a copy of a vanilla docking module, and the items seem to get hidden with no issues:
![image](https://user-images.githubusercontent.com/14351070/224659460-9f884974-de47-44c6-87a3-5465e9e74d49.png)

I wonder if there's some issue in the way you've configured the module (although I'm not sure what it could be - grouping the items using the faction's identifier should work)?

**Comment by Regalis11** [comment]
Would it be possible to share the module file here so I can give it a test myself and see if I can repro the issue? Thanks!

**Comment by UnhappyWithMyUsername** [comment]
The modules are now available in the latest version of DynamicEuropa:
https://steamcommunity.com/sharedfiles/filedetails/?id=2532991202

**Comment by UnhappyWithMyUsername** [comment]
Closing this as it was pretty much me just being absolutely blind I guess. I revisited all the modules just to notice that the groups were pretty much gone from all modules. It seems like they just didn't transfer over correctly when saving the vanilla module as a new module to edit it. After setting the groups up again with their correct names, it seems to work just fine now.
