### ISSUE TITLE
Multiplayer game death lags on the intermission screen after getting out of station

### ISSUE THREAD

**Issue by Muz1kash1** [Regalis11/Barotrauma#11498]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After getting missions and getting out of post we got stuck on the loading screen before the mission, players cannot connect and host cursor not moving, only restarting the game and server fixes this issue

### Reproduction steps

1.Start a multiplayer campaign
2.Complete mission
3.Get any missions to do at station
4.Try to get out of station and start round

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by rotas99** [comment]
I am having the same issue.
I was using mods prior to the 1.0 update , but disabling all mods and then reinstalling the game files did not solve the problem.

**Comment by Muz1kash1** [comment]
> I am having the same issue. I was using mods prior to the 1.0 update , but disabling all mods and then reinstalling the game files did not solve the problem.

We had literally get this error after installing amogus accordeon. Ironic.
