### ISSUE TITLE
The optimization

### ISSUE THREAD

**Issue by alextbw** [Regalis11/Barotrauma#115]
Hello. I know I have a potato PC (Athlon 5600+ 2 cores 2 threads 2.9 GHz, 6Gb of DDR2, GeForce GT630).
I noticed that when I respawn in a shuttle FPS drops from nearly-playable 20-30 to 10, 5 and even 1! Although neither the CPU, neither the graphics card are fully loaded. I don't know why is this happening, maybe the game draws the objects that are not visible? This happens on big subs also.
P.S. My friend with Xeon X5660 (6C/12T) and GTX770 experiences the same problems, but his minimum fps is around 15-20.
P.P.S Yes, I am planning to upgrade in the near future
P.P.P.S War Thunder runs on my machine on ultra low, and FPS is like 20-30
Example of FPS and card load:
![image](https://user-images.githubusercontent.com/29841078/33797915-9fe2e342-dd18-11e7-9991-9d7ec024b799.png)
![image](https://user-images.githubusercontent.com/29841078/33798638-d405fe8c-dd24-11e7-8c5c-3cbed36dcc48.png)
![image](https://user-images.githubusercontent.com/29841078/33799415-db62a1da-dd33-11e7-9712-125ccc5d31fc.png)

**Comment by NilanthAnimosus** [comment]
The issue of the frame rate drop is actually down to the CPU usage usually, and not the GPU usage.

The game has a few optimizations needed in the main update loop, it runs a lot of its update code on a single core. This would normally perform alright but the game does have a few areas to optimize.

The reason for the frame rate drops is how Monogame's timing works, if the update loop takes too long it begins skipping draw calls, the further behind it gets the more this compounds in an effort to catch up. draw calls don't really take almost any amount of cpu however but this behaviour isn't something I think can be overridden with any ease.

eventually it reaches a minimum draws / second, which is your lowest FPS you will reach.

Once it has fallen behind it takes time to "Catch back up" so the FPS loss feels like a wind-up and unwind. you can look up XNA or Monogame timing on how this really works if you wish.

Last time I examined performance, it was a lot of raycasting and map entity updates, Beyond this I don't really know much more.

**Comment by alextbw** [comment]
So turns out that single-core performance is more important for this game?

**Comment by Cyprex** [comment]
I can confirm large fps issues as well ~2 fps. Note that this is on Linux. I remember the game being very playable on Windows ~2 years ago

**Comment by Cyprex** [comment]
Situations with large amounts of crew members seem to tank fps the most, the game runs fine(30-50fps) for the most part in simpler situations

**Comment by Regalis11** [comment]
I think this can be closed. Even though we still have lots of work ahead with optimization, it's not really something that's ever fully "done", and I don't know if it makes sense to keep an issue open for a continuous process like this.
