### ISSUE TITLE
Pre-existing character in a bugged lobby forces spawning as random character (female instead of male)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11509]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This is the second time this has happened. The game forced me to play as a female character even though I chose a male character. When I rejoined, it deleted that female character.

So far, 2 times when I joined a server for the first time, the lobby showed me a pre-existing female character of my chosen class (Medic). The first time it happened, I didn't try to create a new character and was able to play as that random female character. However, this time I clicked Create New Character before joining from the lobby. 

Despite creating a new male character in the lobby, I still spawned as a female character. Then, I left the server to the main menu and rejoined. I spawned as a new character (and lost my previous inventory).
![Barotrauma_ROk8szMkbs](https://user-images.githubusercontent.com/10529134/225012129-e4d41f27-0036-4e98-b554-02cbba0864bf.png)
![Barotrauma_K9blRnXoBT](https://user-images.githubusercontent.com/10529134/225012137-db81615f-cc92-43fa-8cf2-8d3d74bc536b.png)

### Reproduction steps

1. Join a bugged lobby where you're shown a pre-existing female character even though you haven't played there
2. Create new character
3. You'll still spawn as that female character 
![Barotrauma_HDTVtnZkxS](https://user-images.githubusercontent.com/10529134/225018362-7f6f79d5-21ab-4236-a1d4-b8147a8c6477.png)
4. Leave the server
5. Rejoin the game
![Barotrauma_HuIvUCnM2o](https://user-images.githubusercontent.com/10529134/225018505-4055505b-f8ad-42ca-b055-5a299f9f7258.png)
7. You'll spawn as a new character and lose your previous inventory

### Bug prevalence

Happens every now and then

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by Krzeszny** [comment]
> Thanks for the report. How do you perform this step: "Join a bugged lobby where you're shown a pre-existing female character even though you haven't played there"? Is it just random, or can you cause it somehow?

It's random.

**Comment by Regalis11** [comment]
Potentially related: https://github.com/Regalis11/Barotrauma/issues/12515

**Comment by Rokvach** [comment]
I wasn't able to reproduce this issue in the appearance reset PR and couldn't think of any way how it could still reset after those fixes, if this still happens we can re-open this ticket but for now as there are new changes to the character saving I can only mark this as working correctly. Closing.
