### ISSUE TITLE
Auto operate turret option doesn´t consume power.

### ISSUE THREAD

**Issue by CptJohn22** [Regalis11/Barotrauma#11507]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing a new auto operate function in the sub editor I had noticed that the turret doesn´t consume power from the supercapacitor while shooting on the enemy. This is making the auto turrets having infinite amount of power. This bug works on every type of turret.

### Reproduction steps

1) Enter to the sub editor.
2) Enable auto operate on some turret.
3) Enter testing 
4) Charge the supercapacitor.
5) Spawn monster via command.
6) Check the supercapacitor power.

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by war3scv** [comment]
can this be fiexd can't shut down my auto turret

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@5ca9ec8.

**Comment by Jasontti** [comment]
Tested.
No issues found.
