### ISSUE TITLE
Loading process gets stuck, when your game language is SChinese/TChinese/Japanese/Korean

### ISSUE THREAD

**Issue by Goostave** [Regalis11/Barotrauma#11504]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When your game language is SChinese/TChinese/Japanese/Korean, every time you leave/enter a waypoint/outpost, the loading process gets stuck. You have to use Task Manager to force shut down the game, restart it, when you finish loading, you are finally in the round.

If you set the language to English, you won't have this problem.

No mod enabled nor Lua installed, This happens in 100% vanilla game environment.

It's not game crash, so no crash report. 

I can still recall this same problem about these 3 East Asia language, which happened once after the Rising Tide update, and finally got fixed by a hotfix.

### Reproduction steps

1. set your language to Simplified Chinese/Traditional Chinese/Japanese/Korean
2. start a new single-player campaign
3. follow the shopping guide or not, leave the outpost
4. you have loading screen, few seconds after, it gets stuck
5. have to use Task Manager to shut the game down, restart game, load your save
6. then you're finally out in the water

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by chickenck** [comment]
the same error happened to my friends and me,XD.

**Comment by just-a-passenger** [comment]
get same issue here, but my friend who use Chinese too is fine, weird.

**Comment by AzureNocte** [comment]
same issue here

**Comment by Regalis11** [comment]
Thank you for the report!

We've gotten several reports about this, so something's clearly amiss here, but unfortunately we haven't been able to reproduce the issue at our end yet. We're wondering if it could have something to do with specific hardware for example - would it be possible to post your specs here so we could try figuring out if this is something that only effects some systems?

I'm sorry for the inconvenience, I hope we can diagnose the issue soon and push a hotfix. :/

**Comment by AzureNocte** [comment]
I made two tests, both of them with lua mod on,
one has language sets to english, and the problem does not occur,
the other has language sets to chinese(simplified), and it gets stuck.

**Comment by AzureNocte** [comment]
Then I uninstalled lua and verified my local files, made the same two tests, it shows the same result.
I think the problem might be linked to some special characters within these languages.

**Comment by Goostave** [comment]
> One potentially common factor in the reports we've gotten might be Lua for Barotrauma: some people have mentioned that they've had it installed, but have disabled/uninstalled it to try get the game working again. I'm wondering if it could somehow be that Lua modifies something in the vanilla folder, or leaves something behind when disabled, which might be interfering with the vanilla game in some way?

About this, I've verified file integrity before my test, and I did it again just now, and all 2829 files are verified, so I guess it should be 100% vanilla. As for whether Lua leaving something behind, I'm not sure.

**Comment by Goostave** [comment]
> Thank you for the report!
> 
> We've gotten several reports about this, so something's clearly amiss here, but unfortunately we haven't been able to reproduce the issue at our end yet. We're wondering if it could have something to do with specific hardware for example - would it be possible to post your specs here so we could try figuring out if this is something that only effects some systems?
> 
> If you open the task manager when the game is stuck, do you see anything unusual there? Abnormal or increasing memory usage, CPU usage being stuck at 100%, or anything along those lines?
> 
> I'm sorry for the inconvenience, I hope we can diagnose the issue soon and push a hotfix. :/

I tested with my Surface Pro 6,
CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz
RAM: 8GB
64-bit operating system
Windows 10 pro, version 22H2

My PC is not around so I have to use my poor Surface to play 1.0, and yes the RAM was at 90~95% during the game, but it can still handle vanilla as long as it's running on English. At the loading point, I notice that the CPU goes up from like 10% to 20%(baro only), RAM increases from 1400+mb to 1500mb, then CPU goes down quickly as the screen gets stuck. I hope these could help.

**Comment by Raven-233486** [comment]
I met the same problem

**Comment by just-a-passenger** [comment]
I have tried re-install without Lua, still stuck in Chinese, but fine in English
Nothing special shown in task manager

CPU:AMD 5600X
GPU:AMD 5700XT
RAM:32G
OS:Windows10 21H2

**Comment by Goostave** [comment]
This problem happened once, after Rising Tide update, issues are here: 
https://github.com/Regalis11/Barotrauma/issues/8365
https://github.com/Regalis11/Barotrauma/issues/8367

**Comment by kuriyamamiraiowo** [comment]
Tested on both stable version and unstable version (v1.1.2.0):
Stable version: this issue can be reproduced even after unsubscribe all workshop mods and reinstall the game
Unstable version: no problem on this issue, can finish loading normally
CPU: Intel Core i5 4690K
GPU: GTX1070
RAM: 16G
OS: Win10 22H2 (Lang: Simplified Chinese)

**Comment by Hokury** [comment]
Have the same problem with Russian. Endless loading  
Last debug messages:
[03/15/2023 12:38:06] Generating an outpost for the start of the level...
I switched to English and problem dissapeared

**Comment by AzureNocte** [comment]
After I tried enabling V-sync and display mode to windowed (without setting language to english), the problem disappeared, if it helps.

**Comment by Hokury** [comment]
> After I tried enabling V-sync and display mode to windowed (without setting language to english), the problem disappeared, if it helps.

it helped me too!

**Comment by AzureNocte** [comment]
YES!!! Thank you Regalis and all the devs, I love this game, hope it's getting better and better!

**Comment by Goostave** [comment]
Great news! Thank you all guys coming to help reporting, and good luck to you devs!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
