### ISSUE TITLE
Can't Translate Monsters

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1150]
I can't find anything in instruction saying anything about monsters.

**Comment by Regalis11** [comment]
What exactly do you want to translate? I don't think the names of the monsters are mentioned anywhere else than in the mission descriptions and loading screens, which can be translated according to the instructions in the vanilla text file. The species names in the creature xmls are sort of like the item identifiers, something that's used to refer to them "under the hood" but not shown to the player.

**Comment by NilanthAnimosus** [comment]
I don't know why one would want to translate species names, but they are all used on the server hosting screen for enabled/disabled creatures, and perhaps one or two other locations.

But its a creatures name, how would one translate the name given to a fish to identify it by?

**Comment by rico6822** [comment]
Species names are displayed in server's menu when selecting who spawns. Not everyone speaks English. Is there going to be away of translating names of monsters?

Example:
Tiger Tresher- Młocarz Tygrysi

**Comment by Regalis11** [comment]
Ah, you're right, I think we'll need to add a way to translate them after all.

**Comment by NilanthAnimosus** [comment]
Their also used in commands, though that is more for grabbing the XML species name, would probably take quite a bit of work to get around how all that is handled, plus if you can translate the names used in those areas - they would still need to be compatible with different translations of the game (IE. server commands).

**Comment by rico6822** [comment]
> Their also used in commands, though that is more for grabbing the XML species name, would probably take quite a bit of work to get around how all that is handled, plus if you can translate the names used in those areas - they would still need to be compatible with different translations of the game (IE. server commands).

We can always give them identifiers.

**Comment by itchyOwl** [comment]
I'd use the current system where the species names are de facto indentifiers and add display name property/attribute, which then could be translated. Doing it the other way around would require much more refactoring.

**Comment by rico6822** [comment]
> I'd use the current system where the species names are de facto indentifiers and add display name property/attribute, which then could be translated. Doing it the other way around would require much more refactoring.

Good.

**Comment by Regalis11** [comment]
Fixed in 10975ae

**Comment by NilanthAnimosus** [comment]
Just curious, lets say someone wanted to use the spawn command for creatures, would they be able to use translated names in the console? Not even sure if you can directly spawn via translated item names either but if one translates the visible names for them - then some may never know/learn what to use for the console (?) or what they'd represent when translated.
