### ISSUE TITLE
Error With Husk Questline

### ISSUE THREAD

**Issue by Ludicro** [Regalis11/Barotrauma#11502]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the Ecclesiast asks for the second metamorphosis of the spirit, when answering with "Emerging from the cocoon of your human body", it sends the line "EventText.waytoascension1.o1.c1" as a response. Looking into the file EnglishVanillaFactions.xml, there's a response that just doesn't seem to trigger. 
![barobugimg1](https://user-images.githubusercontent.com/65253062/224876699-c3f240f0-15f0-4292-a7f3-e55d584c829d.png)
![barobugim2](https://user-images.githubusercontent.com/65253062/224876824-c4ab08da-58d0-4713-938b-e92acd55ac9b.JPG)

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b9c8f2b71cc58e9c4bf884dc5dd56b195e832857

**Comment by Ludicro** [comment]
That leads to a 404 page.

**Comment by Regalis11** [comment]
> That leads to a 404 page

That's a link to a commit in our private repository, just intended for our internal use so we can check where the fix was committed to. And yes, you're right, the event is using an incorrect text tag: it should have been "`EventText.waytoascension1.o5.o1.o1.o1.o1.c1`".

**Comment by BottomFeedingRat** [comment]
I am also having this problem

**Comment by Jasontti** [comment]
Tested. All dialog options work.
