### ISSUE TITLE
Harpoons only reel in as youre facing the character

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11516]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So, it seems that when using a harpoon gun on someone, they only get dragged along as youre facing them, which makes it a bit annoying as you cant quite literally draw someone along as you run off to somewhere.

https://user-images.githubusercontent.com/104232152/225041759-6814c83e-5570-4a04-90ce-00060970b385.mp4

### Reproduction steps

1.Harpoon someone (preferably a ragdolled body, for demonstration sake) and keep it reeled
2.Look away and get some distance for demonstration
3.Look in the direction of the reel, it will now be pulled toward you with excessive speed, as it didnt drag along as you walked away

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.2.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@71bc221.

**Comment by Regalis11** [comment]
Tested, could not spot any issues. Closing.
