### ISSUE TITLE
The flashing Water

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11518]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While you are already aware of this, id still make a report to write down the extent of this.
Unstabler outside water seems to flash quite a bit with the colors of nearby lamps and mixes between the couple. 

https://user-images.githubusercontent.com/104232152/225047356-2b3a201a-b90e-4087-b5ca-cee171f13172.mp4

Now this is not the only water affected, but the water inside the sub is aswell

https://user-images.githubusercontent.com/104232152/225048054-50a35902-5b8b-4e82-8218-1e2b42e98147.mp4

Most commonly loosing all transparency and having some odd issues surrounding water behaviour between hulls, especially as it comes to splashes, though im not sure this is a new issue if not just a result of non transparently visible water.

### Reproduction steps

1.Look into the water flickering both onsub and outside of it

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.2.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by aeondez** [comment]
I don't have any issues with flashing lights on any subs I tested, but water appears to have lost all its transparency for me.
