### ISSUE TITLE
Periscope camera doesn't lock onto laser turret in case of periscope with a switch

### ISSUE THREAD

**Issue by Renario910** [Regalis11/Barotrauma#11512]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

While using a periscope with a switch mechanism to switch between two turrets, if a laser turret specifically has a memory component preceding it, the camera will stay at the other turret (coilgun in this case.)

### Reproduction steps

1. Launch sandbox with barsuk
2. enablecheats; get wires, relay components and memory components
3. Wire up the following diagram: 
![image](https://user-images.githubusercontent.com/17196651/225025426-d0ad5437-1c10-4e02-9ff7-5ff354104539.png)
4. The camera stays on the disabled coilgun. (the laser turret is still controled by the periscope, player)
5. if the memory component before the laser turret gets bypassed, the system works as intended.

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I don't think this is actually a bug. There's no way to pass signals through a memory component, so this should not work. Why do you need the memory component?
