### ISSUE TITLE
[Unstable] Doors have weird LOS

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11519]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/225049405-d6c094bd-6d37-4ad9-bb42-396634bfb200.png)
As you can see, doors for some reason seem to have either too small windows as far as LOS goes (on the left) or too large ones (on the right). No clue what causes this, as they seem to randomly swap between the two every load.

### Reproduction steps

1.Look at a collection of some doors, pay attention to the odd LOS on them

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.2.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I couldn't find a way to reproduce the issue. Does this happen in some specific submarine?

**Comment by Rehexr** [comment]
Odd, this never happens on any vanilla subs or newly placed doors, only ever on pre-1.0 made custom subs. Possibly related to those new custom sub errors? Either way ive attached the custom sub where i have these issues, on the lower floor mostly.
[[RH] Tynler.zip](https://github.com/Regalis11/Barotrauma/files/10985521/RH.Tynler.zip)

**Comment by Regalis11** [comment]
Most likely caused by https://github.com/regalis11/barotrauma/issues/11520, as fixing that seems to have resolved this one too.
