### ISSUE TITLE
Give All Crew Members Helm Skills- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1151]
Captain is the only vanilla person with helm skills, no other character.

**Comment by thegrb93** [comment]
Isn't that the point of captain?

**Comment by NilanthAnimosus** [comment]
I feel its almost too punishing on servers for shuttle pilots in respawns to have absolutely no helm, given the distance of the submarine and limited time of the shuttle.

I do like, and want the captain to have various bonuses, especially for control of the submarine - and feel it is far too punishing for battery duration + resistance of shuttle + distance to traverse and creature speeds for low helm skill in multiplayer.

But security is already a half-doctor, so the only other person available is assistants that'd make some sense balance wise...not that they would exactly be trained in it anyways or make sense to their job.

when hosting for closed alpha, the vanilla respawns never made the distance at the best speed they could operate.

I strongly disagree with all crew having helm skills. that is about the same as saying just don't have helm skills. I also think its too penalizing in multiplayer for respawn's or what should be simpler to operate.

**Comment by thegrb93** [comment]
Assistant having some helm skill makes sense. Kinda like a copilot.

**Comment by BillCombs** [comment]
It seems that other jobs can't even level up helm skill because it is not mentioned in their settings(didn't really test it much, just noticed how the captain occasionally gets exp, while other jobs don't get anything for the same amount of time spent on helming).
Perhaps they should at least have that skill mentioned, even if they will be at 0.

**Comment by NilanthAnimosus** [comment]
That is correct, it is impossible to earn a skill if it does not exist in the dictionary for the loaded job. I just checked the code and found this:

```csharp
public void IncreaseSkillLevel(string skillIdentifier, float increase)
        {
            if (skills.TryGetValue(skillIdentifier, out Skill skill))
            {
                skill.Level += increase;
            }
        }
```

if no skill is returned a new one is not created for the skill, resulting in undefined skills never incrementing.

**Comment by rico6822** [comment]
> That is correct, it is impossible to earn a skill if it does not exist in the dictionary for the loaded job. I just checked the code and found this:
> 
> ```cs
> public void IncreaseSkillLevel(string skillIdentifier, float increase)
>         {
>             if (skills.TryGetValue(skillIdentifier, out Skill skill))
>             {
>                 skill.Level += increase;
>             }
>         }
> ```
> 
> if no skill is returned a new one is not created for the skill, resulting in undefined skills never incrementing.

And that is what I mean. Everyone deserves to have some helm skills. It would be weird if everyone was equally skilled. I believe most people should have it randomized between 10-20.
