### ISSUE TITLE
Newest unstable build immediately breaks 

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11511]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So, that one experimental build rn is utterly broken, as probably expected, so ill just start:
1.All wires are broken and simply spawn unwired, causing plenty of errors
2.All containers are broken and the items previously contained in them are dropped to the floor
3.Loading into the proper game (for example: Starting a test in the sub editor) will immediately crash your game, ive attached the error below

Dont have much else to add, since i cant really access anything, but there you go
![image](https://user-images.githubusercontent.com/104232152/225022593-e7d1a418-58e9-4137-9cc6-52376cb9350a.png)
[crashreport (46).log](https://github.com/Regalis11/Barotrauma/files/10969406/crashreport.46.log)

### Reproduction steps

1.Open the sub editor
2.View any container or wire
3.Load into the proper game, crash immediately

### Bug prevalence

Just once

### Version

v1.0.7.0

### -

V.0.1.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f8151c22cb23ed5c0875e11218be16a2fb7c40d
