### ISSUE TITLE
Mining mission spawned way too deep

### ISSUE THREAD

**Issue by Xayrlen** [Regalis11/Barotrauma#11528]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Second voyage after a new game, picked a mission to collect galena from a cave. That thing spawned almost at the bottom of the sea. I had to get to the edge of a map, and deep dive into the abyss to reach the destination, since there was no entrance anywhere during traveling. Took about 10 minutes to reach down, and then 10 more to get up. 
![123](https://user-images.githubusercontent.com/86978521/225124731-1b112476-24cf-4724-ad65-f05f092aee2b.png)

Also, some minerals were misplaced.
![1234](https://user-images.githubusercontent.com/86978521/225124808-17468957-24f9-4915-806e-8ebb20fac868.png)

### Reproduction steps

This happened only once to me since the 1.0 release, however that happened randomly for a galena mining mission for Separatists. Not sure if there could be reproduction steps.

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro, closing
