### ISSUE TITLE
Error while connecting to master server (BadGateway: Bad Gateway)

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#11526]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On startup, I recieve the error `Error while connecting to master server (BadGateway: Bad Gateway)`.

Additionally, I am unable to connect to any servers through the server browser.
I have not testing joining through Steam or using Direct Join.

Hosting works perfectly fine, however.

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jade-Harleyy** [comment]
Update: Attemping to browse any pages under the https://barotraumagame.com is proving to be very slow, and I had to wait up to a minute for page content to load.

Other websites do not have this issue.

**Comment by Regalis11** [comment]
Thank you for the report!

This seems to be a server-side error (at Steam's end), so unfortunately I don't think there's much we can do about this. :/ Is this a persistent issue or did it just happen once?
