### ISSUE TITLE
[Unstable] Loading custom subs causes an error (collection was modified in ConvexHull.Remove)

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11520]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Mind that i tried doing this with both my own and a few other peoples custom subs, but they all seem to often cause an error when loaded in related to shells, though they will still work as normal past that. Heres said error: 
![image](https://user-images.githubusercontent.com/104232152/225051410-661ce6d7-f839-487c-a1ae-5d6f4aa3576b.png)
Ive tried doing this with creating a new custom sub, but this only ever seems to be an issue with old files.
![image](https://user-images.githubusercontent.com/104232152/225053266-3d706540-c94f-4299-9e74-1b8a57ef3129.png)
Heres more errors for other custom subs, seemingly these are often related to scale and lights, yet theres not always the same error.
### Reproduction steps

1.Load in a custom sub (campaign or sub editor)
2.Recieve an Error message (seemingly related to the Shell?)

### Bug prevalence

Every once in a while

### Version

Unstable (v1.1.2.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
Seems even the camel is affected with this, funnily enough 
![image](https://user-images.githubusercontent.com/104232152/227355448-79d3b247-b026-41f0-ae5e-2cddcf14cfd5.png)

**Comment by Quink-Fix** [comment]
Probably important to note that this is not strictly limited to molded campaigns or custom subs; it can occur in vanilla.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f469874478a8d3ed90ea583fa3121f88480b6aa (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
