### ISSUE TITLE
After 1.0 Update Shuttles don't take on water when hulls are damaged or missing all together

### ISSUE THREAD

**Issue by dirigonaut** [Regalis11/Barotrauma#11527]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was in the sub editor playing with some of the new guns when I noticed after shooting through the hull of my little custom shuttle it did not flood. So I opened it up in the editor as well and found that I could even just remove the hull of the sub and it would not flood then either.

Original:
![Screenshot 2023-03-14 Baro_2](https://user-images.githubusercontent.com/35875808/225120776-49176f3d-768f-4a14-bf18-6f3461af08be.png)

Walls Removed:
![Screenshot 2023-03-14 Baro_3](https://user-images.githubusercontent.com/35875808/225120819-fde5b6d1-a542-4204-beb4-2adc8cc80e2d.png)

Play testing without Walls:
![Screenshot 2023-03-14 Baro](https://user-images.githubusercontent.com/35875808/225120867-1562964c-49c9-483f-8c60-b9d236b8aea3.png)

### Reproduction steps

1. Open the sub editor
2. Load up any of the shuttles (I used the remoradrone)
3. Delete the walls
4. Add a spawnpoint for your character
5. Click Test

![Capture](https://user-images.githubusercontent.com/35875808/225120444-44692a1a-26e1-41b7-8b40-ac3e04255117.JPG)

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
There are no error messages or crashes and I unloaded all mods from the mod menu and it still happens.

To note I already verified the game file integrity after the update.
```

**Comment by dirigonaut** [comment]
After some further investigation part of this might not be fully specific to shuttles. I can delete walls from bigger subs and they will not flood either. Though they will still take on water when their walls are damaged unlike my custom shuttle.

To note about deleting the walls you can walk through them but once you are on the water side I have found it won't let you back through.

Example of deleting walls on larger ships:
![Capture_4](https://user-images.githubusercontent.com/35875808/225126320-05396fc1-354b-4761-b6f3-1d610d3e8033.JPG)

Standing in shuttle after shooting a hole in it:
![Capture_3](https://user-images.githubusercontent.com/35875808/225125921-3c2bf731-b767-4e02-9836-17f1e1ec2d40.JPG)

**Comment by dirigonaut** [comment]
So I also just tested with the Kastrull and having it's drone still attached and shooting it and it has the expected outcome of taking on water when the walls are damaged.

I will also add that the main sub I am using and it's shuttle are from previous versions of baro were I personally modded the herja with some extra things.

**Comment by dirigonaut** [comment]
So I am not sure I reported the right bug tbh but I think I fixed my issue. I think it has something to do with the wall hitboxes. I reset each corner to the prefab which moved them a little and put them back to a scale of .5 instead of .45. After all this they started acting like normal again. This is some black magic right here.

**Comment by Nikas36** [comment]
Not a dev, but I'm pretty sure that hulls not taking on water when walls are missing is intended behavior or at least a side effect of the way the game handles flooding. Water can only come in through gaps which are automatically created when a wall is damaged, so if there is no wall, there can also be no gaps.
