### ISSUE TITLE
Stains cleaned by the sprayer reappear next round.

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#11525]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Title.

https://user-images.githubusercontent.com/51425624/225081615-74ca0f0a-1d7e-47d8-8011-9e00e6293dac.mp4
Here is me cleaning it during the round.

![post-round](https://user-images.githubusercontent.com/51425624/225081847-ccf2917b-f53d-461f-8bef-6b3b8355999f.png)
After the round when we've docked at the outpost.

I first noticed this while playing yesterday. Initially it would reappear immediately after cleaning it, then it would stay removed until the next round began.

### Reproduction steps

Refer to title.

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
olaf dog :DDDDD
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/02401cdd8b4a263d331e715839da9a36d4d03c80

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
