### ISSUE TITLE
Medical Doctor cannot access R-29 toxin cabinet due to missing ID card tag.

### ISSUE THREAD

**Issue by TheTorukMakto** [Regalis11/Barotrauma#11521]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The toxin cabinet on the R-29 has "id_medic,id_captain" under "Picked required". This suggests that the Medical Doctor should be able to open the Toxin Cabinet, but only the Captain is able to open the cabinet. 

The Medical Doctor spawnpoint does not have "id_medic" listed under "ID Card tags", which means that the Medical Doctor's ID card does not receive the correct tags.

### Reproduction steps

1. Host a server and select the R-29 as the submarine.
2. Select "Medical Doctor" as your occupation.
3. Attempt to open the toxin cabinet when the round starts.

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78c37a09f078c03e67884a3ef2b3461a8c779ceb
