### ISSUE TITLE
Missing gap for water flow between hulls on outpost (SecurityModule_02)

### ISSUE THREAD

**Issue by ApolloDraxium** [Regalis11/Barotrauma#11529]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While deciding to flood the outpost for the laugh of it. I came across a room in the outpost armory that has a missing "gap" feature. To connect two hulls. One side has no water where the other has high pressure water.

Clip of myself climbing into the room with water and pressure.

https://user-images.githubusercontent.com/127894743/225125429-00416423-e0a8-4161-a81d-96511c4918fd.mp4

### Reproduction steps

1. Find specfic armory room.
2. Flood the room by any means.
3. Observe how the water doesn't flow from the ladder into the control room.

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ApolloDraxium** [comment]
![image](https://user-images.githubusercontent.com/127894743/225126460-903e1287-94df-48ff-a9fa-77b2b835b88e.png)
To help further I just went into the submarine editor and opened SecurityModule_02. The gap is indeed missing between these two hulls. I'll fix it myself no problem.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d41a285095a5b2e2914e22e2814e3aed15ca0f6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
