### ISSUE TITLE
Tormsdale Report mission not completing

### ISSUE THREAD

**Issue by GaoDong64** [Regalis11/Barotrauma#11533]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Leaving the outpost with Tormsdale report still gave the mission failed upon leaving outpost. This was in the unstable faction test.

### Reproduction steps

1. Get Tormsdale Report quest in Singleplayer Campaign
2. Go to selected station
3. Kill outpost manager, take report.
4. Run to sub while security chases
5. As soon as you can select map and travel to new location

### Bug prevalence

Just once

### Version

Other

### -

Unstable faction Test build

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

It seems the issue here was that the mission required you to bring to the documents to the sub for it to be considered "completed". Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57e92afd6eaab4e738a872029473d99ef53d5794
