### ISSUE TITLE
One of the Custom Door in the Shuttle Venture Is Broken

### ISSUE THREAD

**Issue by MBthegod** [Regalis11/Barotrauma#11537]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The custom door cannot be repair by wrench. Instead, I can use a welding tool to "fix" the door. 
![image](https://user-images.githubusercontent.com/127932776/225245964-d54d7587-d0bf-416f-88da-2662caec3a7e.png)
Also, when the door is fully destoried, trying to fix it with a wrench will result in "opening" the door.
![image](https://user-images.githubusercontent.com/127932776/225247097-0f776a3c-993f-4f76-8c8e-ca599a668423.png)

### Reproduction steps

In the Repairable section, the "equipped required" block is filling "weldingtool"
![image](https://user-images.githubusercontent.com/127932776/225245964-d54d7587-d0bf-416f-88da-2662caec3a7e.png)

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78c37a09f078c03e67884a3ef2b3461a8c779ceb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
