### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by EchoCharly21** [Regalis11/Barotrauma#11534]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Barotrauma doesn't seem to want to have audio, I can't pick an input/output in the audio settings as there is nothing there
gives me this error: "Error after assigning ALC context: Invalid device. Disabling audio playback..."
Barotrauma has worked just fine for the past like 2 years I've had it, I've done nothing new to my pc to change anything. Ever since this new update I have been having this issue
Also I get the error when I try to go into settings "Alc.GetStringList failed: AL error Invalid operation"

### Reproduction steps

Start the game

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error after assigning ALC context: Invalid device. Disabling audio playback...

also

Alc.GetStringList failed: AL error Invalid operation
```

**Comment by itchyOwl** [comment]
There's been similar issues before, see #1605. So it's most likely related to the [OpenAL drivers](https://www.openal.org/downloads/). Try reinstalling the drivers. Might have to uninstall them first.![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/6269fe92-67f4-45cb-bb19-f7ff32486cc5)

I don't know if there's been any changes in the code that could affect it, but it's possible. Please let us know, whether reinstalling OpenAL fixes it or not!

**Comment by EchoCharly21** [comment]
It worked! Thank you so much
