### ISSUE TITLE
[1.0.7] Bots stilll dont support crafting

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#11542]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

BT got released and bots dont support crafting. 
Thats a broken bot-functionality, because its definately important for singleplayer.

Yes, its kinda easy to implement:
- use any crafting station and queue up recipes
- add the crafting job to the bot
- bot gathers the stuff 
- recipe gets crafted or recipe gets skipped if theres no materials
- bot removes the finished product
- rinse and repeat.

Bots can already gather and store specific stuff, so most of the needed code is already there.
You only need an option to manage the queues on crafting stations.

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is a feature request, not a bug report.
