### ISSUE TITLE
Inconsistent sprite handling during scaling/offsets

### ISSUE THREAD

**Issue by karaolidis** [Regalis11/Barotrauma#11540]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game handles sprite scaling and offsets in an inconsistent way, leading to warped textures and broken decorations. See the following example of "Shuttle Shell A Glass C":

![image](https://user-images.githubusercontent.com/46189100/225269467-276f7364-1c13-4a12-bf17-f98990c2bfb2.png)

This is especially noticeable in the PvP mode in highly-decorated custom subs on the separatists' side:

![image](https://user-images.githubusercontent.com/46189100/225270081-5e5a35b8-2a01-4a93-9369-0bf9a60760b5.png)
![image](https://user-images.githubusercontent.com/46189100/225269997-a646f140-330f-43bd-bbeb-cf0b23f11dd9.png)

(Note: the above submarine is slightly modded, containing 3 custom walls with different hitboxes. The problem is, however, reproducible in completely vanilla subs too.)

Sub files: [Aegir.zip](https://github.com/Regalis11/Barotrauma/files/10978213/Aegir.zip)

### Reproduction steps

1. Open submarine editor
2. Place a flippable sprite down
3. Offset by 10 or -10 pts
4. Copy the sprite and flip
5. ???
6. Profit

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### -

Bug has existed for a while :)

### Which operating system did you encounter this bug on?

Linux

**Comment by Nikas36** [comment]
I understand that this is a low-priority issue, but would love to know if it is actually a bug or intended behavior. Congrats on 1.0 btw :)

**Comment by itchyOwl** [comment]
So, did I understand it correctly: the issue is that the offset works differently (wrong) on structures that have been flipped _and_ scaled? I don't think it's intentional, labeling as a bug.
