### ISSUE TITLE
Placeholder Dialogue For Hostile Outpost Vendor NPCs

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#11543]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Interacting with NPCs that give services in Outposts while your reputation is at a hostile level gives a placeholder dialogue of "dialoglowerrepcampaigninteraction"
![Barotrauma_ONipl8i1kz](https://user-images.githubusercontent.com/60911734/225321908-58a7506b-d8a9-4277-b671-0f6bd735bfbc.png)

### Reproduction steps

1. Start a campaign as normal
2. Lower a faction's reputation naturally or use `setreputation` to the point of the faction being Hostile
3. Enter the now hostile outpost and interact with a Vendor NPC
4. NPC should give placeholder dialogue

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.2.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7795303f264cccfe7c30520ec455569fbeb44938
