### ISSUE TITLE
Does Personality Traits Affect Character's Behaviour or Just Dialogues?

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1154]
If just dialogues will it affect their behaviour in the future? I believe traits should have description featuring content of the trait.

**Comment by Regalis11** [comment]
At the moment they only affect dialogue, but we've been thinking of making them have some kind of an effect on the behavior or stats of the characters as well. It's a pretty low priority feature at the moment, but perhaps after we've got some of the more important stuff out of the way first.
