### ISSUE TITLE
Sucked inside the walls of a wreck

### ISSUE THREAD

**Issue by gibbyest** [Regalis11/Barotrauma#11557]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I got sucked in the walls in a wreck while fighting a mudraptor not sure what happened but it seemed like it was missing the background in the place where i was sucked in, i had to plasma cut the wall to be free.
![image](https://user-images.githubusercontent.com/128039059/225584699-c73f070c-b3fd-4d6e-9cab-7858283da908.png)
this was the wreck i got stuck on where i marked it.
the only mods that i were using at the time were these 
![image](https://user-images.githubusercontent.com/128039059/225585439-dc4dbf13-2ea3-4f7a-84da-9a29d4c51592.png)

### Reproduction steps

Wrecks or maybe subs 

### Bug prevalence

Just once

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
![image](https://user-images.githubusercontent.com/104232152/225716775-95014d97-08ca-4435-bbe3-959e95875c6c.png)
This little hole is the issue

**Comment by Rehexr** [comment]
![image](https://user-images.githubusercontent.com/104232152/225716940-f43c8382-e0da-4474-a660-56a89472955c.png)
Theres also one on the opposite side, so its not forgotten

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab65578a11278155729a4b042c0fe44b009e4489

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
