### ISSUE TITLE
Hosting multiplayer server corrupts two files

### ISSUE THREAD

**Issue by LumaraFeleine** [Regalis11/Barotrauma#11556]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I verified my files on barotrauma and had it fix two corrupted files. I thought it was mods, but after trouble shooting I found it happens when I host a multi-player server regardless of mods. (no file corruption if I simply launch and close barotrauma, and no file corruption if a host a single player game.) Wish I knew which files were being corrupted and fixed, but I don't know how to find that out.

I don't know if this is or can be causing issues in the game, but it seems a bit concerning that any files are getting corrupted for simply hosting a game.

### Reproduction steps

1. Verify files
2. Host a multiplayer game/start a campaign
3. You should find that two files have to be fixed after closing out the game.

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a actually a bug: it doesn't mean the files are corrupted, they have simply been modified by the server and Steam reacquires the non-modified ones when verifying file integrity.
