### ISSUE TITLE
clown shops are selling only fertilizers and nothing else after updating the old save into new update

### ISSUE THREAD

**Issue by ReiTheTrap** [Regalis11/Barotrauma#11555]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

we have old save and updated the game to recent version.
Every clown shop we met sold nothing but fertilizers. And we met like 3-4 of those shops.
We cant buy new clown costumes from them. Cant buy bananas. 
We have 70 reputation
no mod that we use can change something in shops
![image](https://user-images.githubusercontent.com/112313823/225514646-5a8a65f1-f6b1-4de1-9ed7-5da4171eeb97.png)
![image](https://user-images.githubusercontent.com/112313823/225514680-35ce6da0-2e8e-41c3-b6eb-960f5b4d8cea.png)
upd. This happens to some all new stuff. The map is not updated so you wont get final boss or 2nd paths.

and here the mods that we had before the update (but i dont think that they could cause the problem)
![image](https://user-images.githubusercontent.com/112313823/225520077-48648d9a-3e26-49cb-8301-f896180fd027.png)

### Reproduction steps

1. we just used our old save where we began playing the game 1 day before the update.
2. did some progress but still was in first zone and bought some clown costumes and other stuff when it was in shops + got some reputation with clowns.
3. updated the game.
4. tried to buy something from clowns when we met their shop, but there was only fertilizers.
this is our save file where clown shop sells fertilizers only to us.
[Multiplayer save.zip](https://github.com/Regalis11/Barotrauma/files/10986628/Multiplayer.save.zip)

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75a8bd6907c97f2775ae0f51fb7b6eb4dfb41091
