### ISSUE TITLE
I Made an Interesting Discovery About Real Life's Europa Gravitation Strength

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1155]
It's only 1,315 m/s² as it is only slightly smaller than our moon. Crew members shouldn't fall that fast.

Just to compare:
Earth- 9,807 m/s²
Our Moon- 1,62 m/s²

Please do not panic. We can always fix this by explaining that Barotrauma takes place in alternate history where it has different gravity as well as it is larger. We can make ocean being same depth but rocky interior under it will have to expand.

**Comment by Regalis11** [comment]
I'm well aware of this, luckily it doesn't seem to occur to most players. ;)

I don't see it as a major issue though - considering how unrealistic the game is in general, I don't think it takes much more suspension of disbelief to ignore this little detail. However, we do have an idea of how it can be explained in a semi-believable way, but you'll have to wait for the campaign to be a little more finished until you'll found out what it is.

**Comment by rico6822** [comment]
> I'm well aware of this, luckily it doesn't seem to occur to most players. ;)
> 
> I don't see it as a major issue though - considering how unrealistic the game is in general, I don't think it takes much more suspension of disbelief to ignore this little detail. However, we do have an idea of how it can be explained in a semi-believable way, but you'll have to wait for the campaign to be a little more finished until you'll found out what it is.

Seems legit.
