### ISSUE TITLE
Welding Tanks randomly go from Full to low percentage

### ISSUE THREAD

**Issue by PureHeartfilia** [Regalis11/Barotrauma#11554]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While playing barotrauma occasionally the welding tanks in the ship or inventory will go from 100% to a random low usage number  like 13% even if they are not in my inventory this can happen.

Example:
I had welding tanks in a storage cabinet in reactor room of ship which were 100% I used my welding tool or flamer as normal around the ship, and occasionally on rare occasion the welding tanks in the cabinet go from 100% to low usage numbers.

This issue isn't very frequent but does happen and can be inconvenient.

### Reproduction steps

1. Start Multiplayer and join steam friend lobby in game
2. Play Game as usual using welding tool and Flamer as engineer
3. Store welding tanks in storage cabinet on ship e.g. reactor room or inventory
4. Randomly usage from goes from not used to like 10% for no reason, its as if it copies the usage of the welding tool or flamer I am using.

### Bug prevalence

Happens every now and then

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment]
Could there be any case of explosions or fires happening near you/in the room where tanks are stored? Fuel/O2 tanks are depleted by those

**Comment by PureHeartfilia** [comment]
Hi Yes,

Thanks for the quick reply.

Me and my friends did have a reactor fire where the tanks where stored, so this seems like the most likely suspect as to why the Fuel tanks depleted.

**Comment by Regalis11** [comment]
Yeah, nearby fires cause tanks to deplete (or in more severe cases, explode), so this is most likely not a bug.
