### ISSUE TITLE
Game ending bugging out when using cheats.

### ISSUE THREAD

**Issue by c0nstyw0nsty** [Regalis11/Barotrauma#11567]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Im not to sure if its intentional or not, but during the endgame, i destroyed the pillars and used the command "fixitems" because the explosion from one of them destroyed some of the devices in the submarine, however after using the fix items command, it restored all the pillars however the boss was still able to be killed, after killing the boss however i had to go back to all the pillars and re destroy them again, and i didnt realize that was a thing, so it took me like 30 min to realize what the problem was.

### Reproduction steps

1. Go into the final bossfight in the campaign
2. Destroy all(I believe its still the same if you only destroy one) the pillars.
3. use the command fixitems.
4. The boss should still be killable however all of the pillars are back up and the game doesnt end.

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
This is not a bug: the "fixitems" command repairs all items in the level, including the pylons.
