### ISSUE TITLE
Cannot hide the whole head when using hidelimb and hidewearablesoftype

### ISSUE THREAD

**Issue by lin2945** [Regalis11/Barotrauma#11562]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I made a mod that contains  a costume that when equipped (in innerclothes slot) by a character, the limb "head" should be hidden and showing only the sprite of the costume. It worked well in previous versions, but after the recent 1.0 update there seems to be a bug about this. Or perhaps I did not notice it in the previous versions whatever.

If I get it right, setting hidelimb="true" for a limb in wearable items simply means that when wearing said item, the sprite of the limb will not be shown at all. But although I set hidelimb="true" for head, after testing for a few times, I found that although the face is indeed hiddden, the other "natural" wearables, hair, beard, etc. are not hidden.

Of course, it seems that this can be solved by setting hidewearablesoftype="moustache,beard,hair,faceattachment,husk,herpes"
But the problem is that there seems to be some kind of a default hair sprite that can not be hidden even in this way, and requiring setting hideotherwearables="true" to be hidden, but this means it will also hide hats and helmets. 

Luckily in vanilla game this is not really a problem, as the default hair I mentioned above is relatively unnoticeable. But when I use other mods that changes this sprite, the problem becomes obvious. 

I guess I should provide pictures to make it more clearly. Picture 1 and 2 is the vannilla case, with I setting the costume‘s head sprite to a transparent version to made the unhidden hair more clearly. Picture 3 is the thing happen when use another mod.

Picture 1. vanilla,(apart from the costume), hidelimb="true", hideotherwearables="false", not using hidewearablesoftype
![Barotrauma 2023_3_16 23_12_39](https://user-images.githubusercontent.com/128059423/225661966-d01571b9-9765-4219-86e7-f22c9d8e7fe6.png)

Picture 2. vanilla,(apart from the costume), hidelimb="true", hideotherwearables="false", hidewearablesoftype="moustache,beard,hair,faceattachment,husk,herpes".
I guess you can notice the thin layer of hair there.

![Barotrauma 2023_3_16 23_18_02](https://user-images.githubusercontent.com/128059423/225663534-3915af4a-9111-44b8-be97-86f2a29c62d9.png)

Picture 2.5, the ui shows that a part of the hair is hidden.

![Barotrauma 2023_3_16 23_18_02 - 副本](https://user-images.githubusercontent.com/128059423/225663820-5b6e1a8f-ad25-4a97-8ee8-68cec49a9f89.png)

Picture 3.not vanilla, hidelimb="true", hideotherwearables="false", hidewearablesoftype="moustache,beard,hair,faceattachment,husk,herpes".
Now the default hair sprite is much more noticeable. Sad.
![Barotrauma 2023_3_16 23_22_53](https://user-images.githubusercontent.com/128059423/225664944-094590b2-8c94-423d-af1c-778351b380ac.png)

Note: The pictures above is taken in v1.0.7.0, and when I was writing this the game updated.  But as I tested in v1.0.8.0, the problem is not fixed.

I'm not quite sure if it is really a bug about the setting hidelimb, and it seems that this has no effect for original gameplay. But it would be quite nice if there is a way to solve it. And after all, despite the bug, the 1.0 version is very nice.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thanks for the bug report! Might be related to the transparent visors that we added in 1.0. Afaik `hidelimb="true"` should be enough. We'll look into it.

**Comment by Regalis11** [comment]
Thank you for the report! It seems the issue here was how we replace the character's hair with a short version when wearing a hat. The short version was always drawn even if the whole limb has been hidden, and it seems that's the way it's worked [since it was implemented over a year ago](https://github.com/Regalis11/Barotrauma/issues/8105). Fixed it now in https://github.com/Regalis11/Barotrauma-development/commit/83b93b489b9c880ed0913c5640a17425f3bb04ad (commit in our private repo). Sorry for the inconvenience!
