### ISSUE TITLE
Deconstructing Advanced Gene Splicer yields too many materials

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11569]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Deconstructing the item gives more materials than it's supposed to:
![image](https://user-images.githubusercontent.com/115734437/225760163-4ba38ea0-d104-462f-8a31-5a4c7fa09bfc.png)
The listed materials in the xml are:
```
<Deconstruct time="10">
  <RequiredItem identifier="fulgurium" />
  <RequiredItem identifier="copper" amount="2" />
  <RequiredItem identifier="rubber" />
  <RequiredItem identifier="silicon" />
</Deconstruct>
```

Changing the xml to this seems to fix it:
```
<Deconstruct time="10">
  <Item identifier="fulgurium" amount="1" />
  <Item identifier="copper" amount="2" />
  <Item identifier="rubber" />
  <Item identifier="silicon" />
</Deconstruct>
```
![image](https://user-images.githubusercontent.com/115734437/225761969-8e63c25c-d7ee-4349-a520-e16515c08d00.png)

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e178d1a2dd1f799170e145fca54de6210f03c29

**Comment by Jasontti** [comment]
Deconstruction still gives extra items.

>     <Deconstruct time="10">
>       <RequiredItem identifier="fulgurium" amount="1" />
>       <RequiredItem identifier="copper" amount="2" />
>       <RequiredItem identifier="rubber" />
>       <RequiredItem identifier="silicon" />
>     </Deconstruct>

What works:

>     <Deconstruct time="10">
>       <Item identifier="fulgurium" amount="1" />
>       <Item identifier="copper" amount="2" />
>       <Item identifier="rubber" />
>       <Item identifier="silicon" />
>     </Deconstruct>

**Comment by Regalis11** [comment]
@Jasontti fixed in https://github.com/Regalis11/Barotrauma-development/pull/4084/commits/bc49609c9f9b474e03a3f30e23031c4d2e126a7c

**Comment by Jasontti** [comment]
Tested. Deconstruction now yields correct materials. Other items with "variantof=" work correctly. Fabricator material and talent requirements work.
