### ISSUE TITLE
[Unstable] Cannot move in the exosuit

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11561]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Even when the exosuit is fuelled it cannot be moved, with regular fuel rods and all in the correct slots, though this is unstable-specific

https://user-images.githubusercontent.com/104232152/225659094-616c2fad-2640-4a5d-8a44-602c00d99bbc.mp4

### Reproduction steps

1.Equip an exosuit
2.Fuel it correctly
3.Note that you wont be able to move still

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
I made a mod that allows fulgurium fuel rods to set the voltage of exosuits to 2. And when the voltage is higher than 1.5, the exosuit gives the wearer a little speed boost. But it seems all ```conditional``` about ```voltage``` are considered true as long as the voltage is higher than 0, causing immobility.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e0bc890bb4da42538162661cbd5c2fd7606c4a2

**Comment by Regalis11** [comment]
Tested, seems to be working now
