### ISSUE TITLE
[Unstable] Funbringer can have any item in the Fuel rod slot

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11568]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Yeah literally any item can be put in the fuel rod slot on the funbringer, though only fuel rods in that slot will count for allowing you to move. 
![image](https://user-images.githubusercontent.com/104232152/225761221-b2aa27be-51f1-46a4-b831-36d5700aee19.png)

### Reproduction steps

1.Spawn a Funbringer 3000
2.Put any item you wish in the fuel rod slot

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9eb225c30a526f391b3401f97af7b761881878ab
