### ISSUE TITLE
Third Honkmotherian Scriptures doesn't seem obtainable

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11560]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Honkmotherian Scriptures: The Nine Pillars of Fun (VII-IX) or `honkmotherianscriptures3` isn't sold by clown merchants as it is supposed to be available from events, according to the comment in the .xml, but it doesn't look like any of the clown related events spawn it at any point.
`honkmotherianscriptures1` is given during the event `pathofthebikehorn1` and `honkmotherianscriptures2` is given during `pathofthebikehorn2` but there doesn't seem to be any mention of `honkmotherianscriptures3` anywhere.

### Bug prevalence

Happens regularly

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0467b65df78eb0983bd65b36dd9baaecd66f4580
