### ISSUE TITLE
Biome transition passageways are sometimes both controlled by Coalition

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11577]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sometimes both of the passageways to the next biome are controlled by the Coalition, example save (created on unstable build):
[sep test.zip](https://github.com/Regalis11/Barotrauma/files/11003914/sep.test.zip)

![20230317175354_1](https://user-images.githubusercontent.com/115734437/225971172-248a6f0d-37d8-454d-8f2d-9a9bcf5c47e5.jpg)
![20230317175356_1](https://user-images.githubusercontent.com/115734437/225971178-c8142d56-2dd4-4a26-911f-cf93610b39a9.jpg)

### Bug prevalence

Happens every now and then

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I tested starting a new campaign with the same map seed (VVGXc578), but unfortunately that didn't seem to result in the same map. I'm not quite sure how that's possible - the same seed should result in the same map (and without being able to generate the map, it's quite difficult to try to diagnose how it generated like this). To be sure, you weren't using any mods when creating this save? And it was created in the latest unstable version, v1.1.3.0?

**Comment by Regalis11** [comment]
> I think there is a minor typo in the seed you posted there (number 5 instead of the letter S)

Ah, yes, that was the issue. 🤦‍♂️ Thank you!

**Comment by Jasontti** [comment]
Tested. Works on bunch of different seed, including VVGXcS78. Closing

**Comment by RooneyRoll** [comment]
Is the fix applied to the latest version "1.0.13.2" ?

**Comment by Regalis11** [comment]
Unfortunately not, we just got it tested internally 3 days ago so it isn't included in any public build yet. But hopefully in the next patch!

**Comment by RooneyRoll** [comment]
> Unfortunately not, we just got it tested internally 3 days ago so it isn't included in any public build yet. But hopefully in the next patch!

Thank you for the information!
