### ISSUE TITLE
Text Display incorrect behaviour with reduced font size (multiplayer only)

### ISSUE THREAD

**Issue by TerminatorTM** [Regalis11/Barotrauma#11572]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For reduced text size - any text than is not long enough to be scrolled, but long enough to occupy all text space will disappear after map reload (start\finish mission in campaing, save&load the game). Text is still stored in display properties, but will not show again until it is changed to different (using wires and memory component for example).
For example: if we set text size to 0.7 and use some text that will be longer that 70% of text display width (but not long enough not to fit) - it will disappear as said above.

Not using mods, just a custom build submarine. Screen shots with stock Dugong (added some displays, reduced font scale with editor).
![Bt01](https://user-images.githubusercontent.com/71139345/225885153-a4c908b8-dd69-418e-a912-453581adea82.png)
![Bt02](https://user-images.githubusercontent.com/71139345/225885182-050c5ad0-91b2-4150-b85d-5fc43b2c8ad5.png)

### Reproduction steps

1. Use editor to add 4 text displays on any submarine.
2. Reduce text size to 0.8 for first 2 displays, and to 0.7 for last 2 displays.
3. Set text for displays from first to last:
Longtext
Short
Airlock1
Test
4. Save the submarine.

5. Start a multiplayer campaign with saved submarine.
6. Depart from station.
7. Look at displays - 1 and 3 will show no text.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
So, it doesn't happen in single player?

**Comment by TerminatorTM** [comment]
Yes - only in multiplayer.

With different Text Display size - it is still working as described.

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately could not find a way to reproduce the issue. The texts seem to show up correctly on all the displays:
![image](https://user-images.githubusercontent.com/14351070/229528270-cc9df217-25dd-4208-9c88-0fd1350b15f5.png)

Would it be possible to send us the sub file you encountered this issue in so we can give it a test?

**Comment by TerminatorTM** [comment]
Thank you for your time. I see that your text is shorter somehow (maybe different font).
You still can reproduce this issue if you put any text in display long enough. For 0.7 - more the 70% lenght, 0.8 - more that 80% and e.t.c.
![Bt03](https://user-images.githubusercontent.com/71139345/229579822-6bdf29dc-ce30-40e7-9ed2-30bbaac01b60.png)

Here is the sub from screen above - https://disk.yandex.ru/d/5J8X4BrCjTa4sA

I play with 3 friends and they all have this problem. We playing with Russian Localizations if it matters somehow.

**Comment by TerminatorTM** [comment]
Oh, i got it why your text is shorter that mine. I have 125% font size in settings. But the issue is still there.
Just change 1 and 3 display to "Longtext12" and "Airlock111".

![bt04](https://user-images.githubusercontent.com/71139345/229585923-de11fce1-b253-4482-a117-6202a0f0a5ce.png)

**Comment by Regalis11** [comment]
Thank you for the extra info, I was able to reproduce and (hopefully) fix the issue now. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ea1cca47b566e8cf320936e3f967b0f334a9d59 (commit in our private repo)

**Comment by KrusteDE** [comment]
got the same problem for my sub here

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
