### ISSUE TITLE
mineral scanner upgrade doesnt work for mission ore

### ISSUE THREAD

**Issue by deltanedas** [Regalis11/Barotrauma#11575]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

playing multiplayer, bought mineral scanner upgrade on dugong for first mission
with it an active sonar on, never showed any minerals including the mining mission ore

also think it happened before where never saw any minerals but didnt have a mission to confirm it

host is on windows if it matters

### Reproduction steps

1. dugong gaming
2. buy mineral scanner
3. get mining mission
4. never shows any minerals anywhere

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

**Comment by deltanedas** [comment]
yes i have the switch on, doesnt work when off either

**Comment by TerminatorTM** [comment]
Is it the same without mods?

**Comment by deltanedas** [comment]
no idea havent tested

**Comment by TerminatorTM** [comment]
If there is no such behaviour without mods - you need to search for fault mod. It will be no bug of the game itself.

**Comment by deltanedas** [comment]
![17:48:26](https://user-images.githubusercontent.com/39013340/225982527-1d24f570-7b5e-4205-9ee2-561ed09bae8d.png)

funny scanner finds cave ore but not mission ore

**Comment by TerminatorTM** [comment]
Mission ore is more to the right - and you have mission mark for it already. Just go there and mine.

**Comment by deltanedas** [comment]
the positioning was accurate and of course i can find it, the point is that it should show on the scanner since its a mineral

**Comment by TerminatorTM** [comment]
I'm not sure, but it was that way all the time before. It is not plain minerals - it is specially spawned chunks.

Let's hear DEVs - is it intentional or a bug.

**Comment by Regalis11** [comment]
Yeah, the minerals in mineral missions are indicated using the sonar marker instead of the "normal" mineral indicators.
