### ISSUE TITLE
Selling using the submarine tab crashes your game

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11578]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Id assume this is unstable specific, but every time i try to sell from the submarine, my game will immedialtely crash, though note that i was using mods.
![image](https://user-images.githubusercontent.com/104232152/225987405-ca18275f-23f2-4d99-b9ea-db842759c208.png)
[crashreport (53).log](https://github.com/Regalis11/Barotrauma/files/11004493/crashreport.53.log)

### Reproduction steps

1.Go to a merchant
2.Try selling some items, usually large quantities

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to be the same error as https://github.com/Regalis11/Barotrauma/issues/11565, closing as a duplicate
