### ISSUE TITLE
Fractalguardian3 spawns in ruins

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11574]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Fractalguardian3 (variant of 2) can spawn in ruins

It can spawn on the "fractalguardian" tagged spawn point
`      <MonsterEvent characterfile="Fractalguardian3" amount="1" spawntype="ruin" probability="0.2" spawnpointtag="fractalguardian"/>`

I'm not sure this enemy is supposed to be indoors considering it has a weapon made for cutting hulls, and its AI has circle/sweep elements which might not work in ruins

### Version

Unstable

**Comment by ubertpendragon** [comment]
Initial post saw the guardian having trouble opening doors but that's mostly a quirk of having shorter hallways, where doors can be very close to eachother and mess with AI/ragdoll

![image](https://user-images.githubusercontent.com/73229309/225974807-84bfc8f4-7463-4dc5-8c28-f35c8b6e4094.png)

**Comment by itchyOwl** [comment]
It's intentional, but maybe problematic. Haven't actually tested it much. Does it cause issues in your opinion?

**Comment by ubertpendragon** [comment]
I thought circling AI would cause problems

The only issue I see is that 2 out of 3 guardians use burn damage, and PUCS with its 90% resistant trivializes those encounters (and many other things in the game)

To touch on guardians in general:

I've observed guardians being quite inconsistent in behavior and attack power, sometimes stunlocking you with melee, sometimes failing to use their ranged weapons. Their biggest enemy is their size as they thend to be quite big for the average room size. Some examples below



Guardian not doing much and dying:

https://user-images.githubusercontent.com/73229309/228393706-733f2a9d-7ca6-4272-9593-2fd1fc581edd.mp4

Guardian subjugated by a single glowstick:

https://user-images.githubusercontent.com/73229309/228393776-af460393-8a6a-42d1-aebb-7e89ae918686.mp4
