### ISSUE TITLE
[Unstable] Networking talent discount only applies to faction items

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11582]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The talent Networking doesn't apply the 20% discount to affiliated faction shops, only the faction-unique items get discounted by 20% (Instead of the intended 20% for all items, doubled for faction-unique items)
On the left are the husk merchants prices with no talent, on the right are the prices after taking the talent and setting huskcult rep to become the highest. The faction-unique items are discounted by 20% but everything else is unaffected:
![image](https://user-images.githubusercontent.com/115734437/226071231-343c3087-ad84-4d75-ba12-fa8ab5000ff2.png)

Another example using an outpost merchant on a separatist military outpost, on the left are the prices while networking isnt in effect, on the right its in effect:
![image](https://user-images.githubusercontent.com/115734437/226071735-06234076-dde8-4de9-a358-18d8319c16b4.png)
 

### Bug prevalence

Happens regularly

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by HawkinsThe71st** [comment]
Also tested Figurehead and while the shipyard discount works, the store discount doesn't seem to work as merchant prices are unchanged after taking the talent.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5eda80df0990df598bfa4ee49f02aadd37ef426f and https://github.com/Regalis11/Barotrauma-development/commit/c4995206535dbb66ff44cca29141517e26ea7e84

**Comment by Regalis11** [comment]
Tested, no issues found. Closing.
