### ISSUE TITLE
quirky new crash softlocks me out of my campaign save

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#11587]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

started a mission in the europan ridge, clear ruin and thresher nest, dugong, 3 crew. game crashed, trying to re-enter the save shows an error and kicks me back to the main menu
[destroy them.zip](https://github.com/Regalis11/Barotrauma/files/11009194/destroy.them.zip)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/11009195/crashreport.log)
![image](https://user-images.githubusercontent.com/55637865/226123400-9d99632a-707e-49e1-934c-0c6679400dbc.png)
![image](https://user-images.githubusercontent.com/55637865/226123420-b9915c07-cf1b-4879-9e73-871236184346.png)

### Reproduction steps

use the attached save and see if it does the error

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to be the same error as https://github.com/Regalis11/Barotrauma/issues/11520, closing as a duplicate
