### ISSUE TITLE
Enemy Corpse Rapid Despawn

### ISSUE THREAD

**Issue by Payne5** [Regalis11/Barotrauma#11586]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While in a game with 8 people on a sub all the bodies where despawning in a minute or less after kill so fast they could not be looted.

*We did have the mod let me choose! on*

### Reproduction steps

0.Have the mod Let me choose!
1.have 8 people
2.Kill crawlers/threshers
3.watch them despawn

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Normally the game shouldn't start despawning any corpses unless there's more than 5 of them inside the submarine, and even then, there should be a lot more than that for them to spawn this rapidly. I wonder if there was just a very large number of corpses inside the sub? Or if any of the mods you're using might be modifying the despawn settings?

**Comment by Payne5** [comment]
There were 2 crawler corpses onboard the sub.

**Comment by Regalis11** [comment]
No known steps to repro, closing
