### ISSUE TITLE
Wifi component linked to chat stops working in specific channel

### ISSUE THREAD

**Issue by Andargor** [Regalis11/Barotrauma#11585]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using a Wifi component linked to chat, on channel 0. Connected to a text display to see what is typed. After a few dozen tests, the Wifi component stops working for channel 0. Changing to another channel, for example 1, makes it work again.

Tested in submarine editor, not in game.

EDIT: Additional info, detaching the Wifi component and reinstalling does not fix the issue. Taking a brand new Wifi component and attaching it makes it work again.

### Reproduction steps

1. Install Wifi component
2. Set linked to chat
3. Set Channel to 0
4. Install Text Display
5. Connect output of Wifi to Text Display
6. Input a few dozen messages until it stops working
7. Change channel to 1
8. Test again, should work once more

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce the issue though. To be sure, you're not using any mods that might be modifying the wifi components or the chat in some way? And you don't for example have other wifi components using the same channel that might be interfering with your tests?

https://user-images.githubusercontent.com/14351070/230126563-131c3474-6a0b-4de5-be79-fe77bd5de95a.mp4

**Comment by Andargor** [comment]
I set up a video and script to demonstrate it, but now I can't reproduce it either. I will close for now and if it crops up again, I will open another issue with a video and reference this issue. Sorry for the bother.
