### ISSUE TITLE
Add an option to scroll through text in items' settings in sub editor

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1158]
Not sure if "scrolling" is the right term. What i mean is moving your text cursor to one side of the text to make the text move to the other, so you could see parts of the text that were hidden.

Right now it's pretty inconvenient to edit any setting that can have a big amount of text, like description or tags, because you cannot scroll to the part of the text that you cannot see. You are able to move the text cursor to the hidden part and edit it blindly, but you can't see the result.
![-2019-feb-16-005](https://user-images.githubusercontent.com/38168249/52897299-6d362100-3205-11e9-9c83-9c8a90a037e3.jpg)

You can work around this by cutting and pasting the text into notepad or some other program to edit and then pasting the edited one into the setting, so this feature is not really urgently needed, but rather something to consider at later stages.

**Comment by Regalis11** [comment]
Fixed in 63f7449
