### ISSUE TITLE
Alien Turret causes a hard/ instant crash when fired

### ISSUE THREAD

**Issue by xAtea** [Regalis11/Barotrauma#11583]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Something about Alien Turrets causes an instant crash upon activation (The issue was originally found when testing modded items with similar code, only to find that the Alien Turret caused the same crash unmodded). 

The source of the issue appears to be this line of code:

<StatusEffect type="OnUse" target="Contained">
        <SpawnItem identifier="alienturretammo" spawnposition="ThisInventory" />
</StatusEffect>

### Reproduction steps

1. Open Sub Editor. Pick any sub of your choosing.
2. add Alien Turret. set auto operate off, power consumption & voltage to 0.
3. Wire turret trigger to any button, terminal, etc.
4. Start test, and attempt to fire turret. 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by xAtea** [comment]
Apparently the report removed the code... 

     <StatusEffect type="OnUse" target="This">
        <SpawnItem identifier="alienturretammo" spawnposition="ThisInventory" />
      </StatusEffect>

**Comment by ubertpendragon** [comment]
This is more important than it seems because it prevents modding turrets that shoot independently without being linked to loaders

**Comment by xAtea** [comment]
> This is more important than it seems because it prevents modding turrets that shoot independently without being linked to loaders

Indeed, and the specific mod that I found this originally on was EK Dockyard's Fixed Thrusters, which use a turret system to induce thrust. Needless to say, those systems are broken right now as a result of this basegame functionality loss.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4097/commits/8415b81f5be442326ce56d0ee05682976e952800

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
