### ISSUE TITLE
Autodocking setting I rigged up works differently betwen SP and MP

### ISSUE THREAD

**Issue by Wyald88** [Regalis11/Barotrauma#11599]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have a wired up system for turning on an automatic docking feature for both upper and lower docking ports, so I can just dock as soon as either docking port is in range rather than aiming for the button myself or selecting that yes I am sure etc.

In single player it'll work perfectly between rounds and everything like that. In multiplayer however for some reason I can't understand it wont activate even though I am certain that the relay that's attached is being switched on. I've toyed with it for hours and cannot for the life of me get it to work in multiplayer only single player.

Here is my sub.

https://steamcommunity.com/sharedfiles/filedetails/?id=2848402324

### Reproduction steps

1. start a campaign in SP
2. note that there is a button physically on top of the navigation console.
3. start the next round like a mission, press the button and see the AUTOHATCH lit up in blue.
4. Get in range of the dock from the start and it will auto dock.

Then try the same in MP, you cannot reproduce it.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This is actually intentional: docking automatically without the prompt caused issues in multiplayer, since a griefer (or accidental faulty wiring) could otherwise essentially softlock the game by making the sub automatically dock/undock at the start of the round.
