### ISSUE TITLE
Regular husk and clown hires have swapped npc identifiers

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11598]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the factions.xml the npc identifiers seem to be swapped, causing hired clowns to come with the husk cultists item set and hired cultists to come with the clowns item set:
```
<Faction identifier="huskcult" initialreputation="-5" minreputation="-100" maxreputation="100" menuorder="2" secondarycontrolledoutpostpercentage="40">
    <Icon name="HuskCultIcon" texture="Content/UI/CampaignUIAtlas2.png" sourcerect="402,523,96,113" color="58,165,121,255"/>
    <Portrait name="HuskCultPortrait" texture="Content/UI/Server/ServerAtlas2.png" sourcerect="0,342,852,340"/>
    <Hireable npcsetidentifier="outpostnpcs1" npcidentifier="hireableclown" minreputation="20" />
</Faction>
<Faction identifier="clowns" initialreputation="-5" minreputation="-100" maxreputation="100" menuorder="3" secondarycontrolledoutpostpercentage="40">
    <Icon name="ClownIcon" texture="Content/UI/CampaignUIAtlas2.png" sourcerect="0,523,118,113" color="206,62,62,255"/>
    <Portrait name="ClownPortrait" texture="Content/UI/Server/ServerAtlas2.png" sourcerect="0,0,852,340"/>
    <Hireable npcsetidentifier="outpostnpcs1" npcidentifier="hireablehuskcultist" minreputation="20" />
</Faction>
  ```
  
  Example at an outpost with clowns as the secondary faction:
![20230319132037_1](https://user-images.githubusercontent.com/115734437/226175472-d131a254-83a5-4caa-82b7-9de5561a4238.jpg)
Hiring the clown:
![20230319132105_1](https://user-images.githubusercontent.com/115734437/226175497-9b5884dd-e1f9-480d-8509-d2a71231fcd6.jpg)
![20230319132116_1](https://user-images.githubusercontent.com/115734437/226175543-344c3bc0-23a6-4a3d-a6ce-6252ed0178a2.jpg)
The clown hire "Margeret James" after undocking:
![20230319132404_1](https://user-images.githubusercontent.com/115734437/226175667-835f6258-c0fc-4ad0-a394-7d375ceb8e73.jpg)
The bot on the left "Frances Maynes" is a hired cultist from a previous outpost.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9f436fe582f22440e86dab0b557183a114c96539

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
