### ISSUE TITLE
Syringe gun to shoot some syringes!

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#116]
Have a syringe gun that can be put into subs in the sub editor and craftable or purchaseable.
Doctors could become a force to be reckoned with due to it - put a syringe of morbusine in the gun and shoot it at your target.
However, it should only accept a single syringe per shot and have a 3-secon "reload" cooldown that comes with a sound and a player animation.
Example for design: ![sgun](https://user-images.githubusercontent.com/3470436/33797647-dd360824-dd1c-11e7-87f4-89c237706f1f.png)

**Comment by G234i** [comment]
Humm, I wonder if we can take some of those suggestions (this one in particulat) to the forums for debate as to see what the community has to say about it :thinking:

**Comment by Crystalwarrior** [comment]
https://github.com/Regalis11/Barotrauma/commit/7ce93d2e1ff69395f99eb686839413393a713dac
YES
