### ISSUE TITLE
No output on CONDITION_OUT pin on "Shuttle Battery"

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#11604]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I connected a `CONDITION_OUT` pin directly to a `SIGNAL_IN` on a `Terminal`, and saw nothing.

### Reproduction steps

1. Enter the sub editor.
2. Load a sub or make a basic one for testing.
3. Add in a `Shuttle Battery`, and a `Terminal`.
4. Wire the `CONDITION_OUT` on the `Shuttle Battery` to the `SIGNAL_IN` on the Terminal.
5. Test the sub from the editor.
6. Observe no output on the `Terminal`.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9633

**Comment by Orum** [comment]
This only leaves me with more questions than answers.  Why do they have a CONDITION_OUT pin at all then?  Why is "Invulnerable to damage" not checked?  Why is this so inconsistent when compared to other ship batteries?
