### ISSUE TITLE
AI Crew refuse to self preserve and make "dumb" decisions under stress

### ISSUE THREAD

**Issue by Eri4474** [Regalis11/Barotrauma#11609]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

AI will, rather humorfully, ignore their self preservation and repair equipment / man guns until they die of oxygen loss.
They will not replace the oxygen in their suits if preoccupied by a job like repairing/gunning and will continue said job until their death.  
It's rather annoying having to micromanage my gunners oxygen since that's where it's most obvious.
-This happens even with oxygen present in their inventory or in a nearby container

A separate issue is that AI, when a suit is needed, will path find to the nearest suit locker and ignore suits on the ground often leading to their death from prolong exposure to pressure such as in the Humpback where the suit lockers are far from the gunnery stations and AI will path find to it instead of the suit left on the ground in near to them.

### Reproduction steps

1. Play with bots
2. Set some bots to gun as priority
3. Flood submarine
3.5 The bots will ignore suits on the ground near them and instead go to a Suit Locker even if said suit locker would kill them due to distance
5. The bots will remain on the gun until their death of lack of oxygen.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by metakot** [comment]
Yep, happens often after the release.
However, that's not affecting the bot logic about changing welding fuel in tools.

**Comment by itchyOwl** [comment]
The suffocation issue is described in #11652 and should be fixed in Regalis11/Barotrauma-development@a8979dc.

**Comment by itchyOwl** [comment]
> The bots will ignore suits on the ground near them and instead go to a Suit Locker even if said suit locker would kill them due to distance

Fixed in Regalis11/Barotrauma-development@4c9d11d.
