### ISSUE TITLE
Player-Controlled Monsters with SimplePhysicsEnabled Set to True Stay That Way

### ISSUE THREAD

**Issue by IndieanaJones** [Regalis11/Barotrauma#11608]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In AICharacter's shared update function, the value of SimplePhysicsEnabled is never changed once a player begins controlling a creature. If the player was given control of a creature via admin commands who had SimplePhysicsEnabled set to true, they will stay that way, resulting in extremely buggy behavior for other clients (this usually manifests itself as the monster being invisible).

Ideally, any player-controlled creature would have simplephysicsenabled set to false for everyone, resulting in everyone seeing the monster as intended.

### Reproduction steps

1. Start a multiplayer game
2. Spawn in a monster far away from the sub so SimplePhysicsEnabled is set to true
3. Give control of said monster to a player
4. The controlling player will see the monster as normal, but nobody else will.

### Bug prevalence

Happens every now and then

### Version

Other

### -

Modded Barotrauma with a mod that gives dead players control over monsters

### Which operating system did you encounter this bug on?

Windows

**Comment by IndieanaJones** [comment]
This is always reproducible, so long as you can guarantee SimplePhysicsEnabled is currently enabled (get the monster in question far away from the other players). If you can do that, it is always consistent.

You can trigger it in vanilla with the control command.

I confirmed it by modifying the code to set player-controlled anything's SimplePhysicsEnabled to false, which resolved the issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/163006b5205e5d4428db199221237154734c40a2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
