### ISSUE TITLE
Purchased Ammunition spawning in wall on Orca 2

### ISSUE THREAD

**Issue by GaoDong64** [Regalis11/Barotrauma#11602]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When purchasing large amounts of ammunition, ammo will spawn within the wall between stowage and the ballast tank underneath the command room. 

### Reproduction steps

1. Start Singleplayer campaign/ start with Orca 2
2. Purchase at least 10 boxes of ammunition for the Orca 2 
3. When starting next level, purchased ammo will be stuck in the wall on the left side of stowage, requiring a plasma cutter to cut it out and move them.

### Bug prevalence

Happens every now and then

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Would help to confirm the repro steps before a programmer takes the ticket.

**Comment by Regalis11** [comment]
Thank you for the report! I wasn't fully able to reproduce the issue, although I did get the cargo to spawn partially inside the floor. Fixed that in https://github.com/Regalis11/Barotrauma-development/commit/e519fd78c160a64169180c73b8b7768f75b82626

**Comment by SolarWraith** [comment]
Had this bug happen to me, bought a lot of ammo and crated items and 2 crates are now permanently stuck between the walls.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
