### ISSUE TITLE
Nuclear reactor blew up without any blast effects when I was spectating

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#11607]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was spectating, someone was doing the funny, the reactor was set to blow up and since the crew didn't react in time it did. 

It was very anti-climactic, there was no flash, no explosion effect, the hull just disappeared.
_Reporting on a singular occurrence_

Keywords I searched for: missing explosion. No detonation. Explosion effect while spectate, spectator, spectating.

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment]
Thanks for the report! So it only happened once, not consistently or often?

**Comment by Ek-Videogames** [comment]
Can confirm explosions sometimes have no particles, glow, or their default "underwaterexplosion" - can happen both in SP & MP, and not exclusive to spectator cam.

**Comment by giists** [comment]
Seems like this only happens on some subs when playing multiplayer. I was able to repro this on Azimuth, Barsuk, Kastrull and Typhon by overheating the reactor

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4e1bd05b88d46bd43faef8ec1a250674e06e86a

> Fixed nuclear reactor's explosion effects sometimes not being visible client-side. 
> The issue might've caused inconsistent behavior in other situations too: the problem here was the items didn't necessarily break in the same order client-side as they did server-side, because the server only marked the items as needing a condition update, and then sent those condition updates in Item.Update, meaning the creation order of the items affected the order in which the client receives the updates. In the case of the reactor, the issue was that it only created the explosion if there was fuel inside it when it breaks, and then set the rods to 0% condition. If a client broke the rods before the reactor, the explosion effect wouldn't get executed.

**Comment by giists** [comment]
Didn't encounter this anymore after testing, closing.
