### ISSUE TITLE
SPOILERS: Some custom submarines that include shuttles/drones cannot enter Eye of Europa

### ISSUE THREAD

**Issue by Nikas36** [Regalis11/Barotrauma#11611]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I just got to the final area of the campaign, I talked to the beacon station guy and pressed the alien button, and my sub is unable to enter the anomaly at the end of the structure. I am hoping that I haven't missed something and that this is a bug?

There's also an unreachable "Emergency Transmission" on the sonar but I'm assuming this should be separate bug report. 

The sub in question: 
[Aegir.zip](https://github.com/Regalis11/Barotrauma/files/11017286/Aegir.zip)

### Reproduction steps

1. Play a campaign with a custom sub
2. Reach the Eye
3. Be sad because you cannot progress the story 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

**Comment by war3scv** [comment]
is your sub carry a drone? that's seem what the problem came from.

**Comment by Nikas36** [comment]
It does! I'll test without it in a couple of hours.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c9a89e81089c5d58e1b96d47488363926bf8423

> Fixed inability to leave levels through outpost exit points (which are used in the final levels) on some subs that include shuttles/drones. Happened because we checked if the sub closest to the exit point was inside the rectangular "exit area", which may not be the case if the closest sub happens to be e.g. a drone just outside the exit area. Now we check the docked borders instead of just the borders of the closest sub.

**Comment by Nikas36** [comment]
Cheers 🙏

**Comment by Rokvach** [comment]
Tested, with the provided sub, working correctly. Can be merged and closed.
