### ISSUE TITLE
Dementonite tools unobtainable

### ISSUE THREAD

**Issue by Dwal32s** [Regalis11/Barotrauma#11610]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Dementonite tools cannot be obtained through crafting or trading, despite remaining in the game and being fully functional, as well as being seemingly intended for use after hardened tools are unlocked.

### Reproduction steps

1. Try to craft dementonite tools
2. Requires recipe
3. Recipe is only unlocked from a removed talent
4. Weep

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
🤔 
https://github.com/Regalis11/Barotrauma/issues/11139

**Comment by Regalis11** [comment]
Thank you for the report!

Dementonite tools are intentionally unobtainable - we decided to remove the related talents, but left the actual prefabs in for backwards compatibility reasons. Having them show up in the fabricator is a bug though, which we have [a separate report about](https://github.com/Regalis11/Barotrauma/issues/11139).
