### ISSUE TITLE
Ballad for Whales is mispelled in the Soundtrack

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11614]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the soundtrack uploaded seperately on steam "Ballad for Whales" is misspelled as "Ballas for Whales" for some reason, bit funny but unintended.
![image](https://user-images.githubusercontent.com/104232152/226475967-59bd87ff-a84c-44fc-8b59-e76b343ec76e.png)

### Reproduction steps

1.Open the games soundtrack in steam
2.Look for Ballad for Whales

### Bug prevalence

Happens every time I play

### Version

Other

### -

Baro Steam Soundtrack

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Should be fixed now.
