### ISSUE TITLE
Lighting downgrade

### ISSUE THREAD

**Issue by Magos-crawler** [Regalis11/Barotrauma#11613]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Before 1.0:
![before](https://user-images.githubusercontent.com/78676550/226188643-757d3ba7-096a-4d55-88c4-f7df3624cd32.png)
After 1.0:
![after](https://user-images.githubusercontent.com/78676550/226188648-9df14d35-6a86-455d-ba32-2b24b6620eea.png)

### Reproduction steps

1. Start the game
2. Use quickstart command
3. Use power command
4. Open your eyes

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug - this is how the lights are intended to look (see https://github.com/Regalis11/Barotrauma/issues/10900)
