### ISSUE TITLE
Sonar disruption is invisible while in Sub-Editor test mode

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#11616]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In submarine editor you can't see sonar disruption from Black Molochs, Nuclear Railgun/Depth Charge Emitters, Dirty Bomb Emitter etc.
Issue is that it prevents testing strength of a sonar disruption (for modding), for which you have to start MP or SP round.

(Tested using Dugong with active sonar ON)
_(I am using Real Sonar mod which can be seen on images bellow. It is not related to the issue as the issue can be reproduced in a 100% vanilla game.)_

`nuclearaftereffectemitter` in the Sub-Editor test mode:
![image](https://user-images.githubusercontent.com/62324831/226509396-51c2bdad-d802-463a-b223-f8730ed9bb00.png)

`nuclearaftereffectemitter` in the SP campaign:
![image](https://user-images.githubusercontent.com/62324831/226509079-4182ea0e-1a2a-48d6-86b9-1e05ecf68eef.png)

### Reproduction steps

1. Start Sub-Editor's test mod with any submarine.
2. Turn active sonar ON.
3. Using console (F3) enter `spawnitem nuclearaftereffectemitter cursor` command somewhere near submarine.
4. Observe the issue.
-----------------------
5. Start SP campaign or MP round using any submarine.
6. Enable cheats.
7. Turn active sonar ON.
8. Using console (F3) enter `spawnitem nuclearaftereffectemitter cursor` command somewhere near submarine.
9. Observe normally working sonar disruption.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5231ba11efc16d9c90171bba05783c62dec309de
