### ISSUE TITLE
Purchased items appearing inside cargo mission crate

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11628]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Purchased items appearing inside cargo mission crate. 
Happened in a steam I was watching

![image](https://user-images.githubusercontent.com/73229309/226746142-617f55d2-0a1b-4646-9648-10a219976661.png)

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Wasn't able to repro this.

**Comment by ubertpendragon** [comment]
I only witnessed it happening in a Barotrauma stream, haven't experienced it myself

Perhaps chemical shipment uses a different type of crate, and those items only spawn in regular metal crates?
Maybe it only happens on this particular transport mission?

**Comment by Regalis11** [comment]
No known steps to repro, closing
