### ISSUE TITLE
[dev] a way to adjust speed of vitality loss for afflictions

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1162]
right now morbusine and sufforin are basically identical

**Comment by Regalis11** [comment]
The speed of vitality loss can be adjusted either by making the strength of the affliction increase faster (by changing the "strengthchange" attribute), or by changing how much the affliction affects vitality (the "minvitalitydecrease" and "maxvitalitydecrease" attributes).

**Comment by etet2** [comment]
wait, does strenght also affect speed of vitality loss? 
it does not really make sense to have speed of vitality loss and stage of the disease be increase by the same thing

**Comment by Regalis11** [comment]
It depends entirely on how you configure the afflictions. Morbusine poisoning for example increases in strength from 0 to 100, and the vitality decrease is relative to the strength (i.e. if the strength is 30%, your vitality drops by 30).
