### ISSUE TITLE
indestructible eggs

### ISSUE THREAD

**Issue by MitsukoKaori** [Regalis11/Barotrauma#11624]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Any type of eggs can't be damage or destroyed either using gun, flamer, or also sub weapons

### Reproduction steps

1. find any type of egg
2. just murder it with any type of weapon (my suggestion using nuclear weapon for better result)
3. look if it damaged or not

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not reproduce the issue. Tested damaging strange eggs and mudraptor eggs using grenades and revolvers, and all seemed to work as expected. 
![image](https://user-images.githubusercontent.com/14351070/227002392-9b0095a0-8749-4acf-a6eb-8068c3d44b29.png)

Flamers did not work though, but [we've got a separate ticket about that specific issue](https://github.com/Regalis11/Barotrauma/issues/11441).

What kind of eggs (ones you need to destroy in a nest mission? Pet eggs? Purchased/looted monster eggs?) and weapons did you try specifically?
