### ISSUE TITLE
master-quality(+900% attack) stun gun can stun the target for 60 seconds

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#11622]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

It's so powerful!

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This should not be the case. The stun gun darts only do 0.1 units of stun and 10 units of progressive stun, so a +900% increase doesn't lead to 60 seconds of stun. I also gave this a quick test, and the stun didn't last anywhere near 60 seconds.

I wonder if some of the mods you're using might be modifying the stun afflictions or the items in some way?

**Comment by zhu-rengong** [comment]
In the vanilla, there are two kinds of stungun darts. One of them(i
 forgot how to spell) can directly cause stun to the target, and when launched by a master-quality stun gun, it can deal with 9 times the stun time.

**Comment by zhu-rengong** [comment]
![U7{(Y1ZAU(HE18{4RZ08A%W](https://user-images.githubusercontent.com/73634685/227214184-7ffbbd58-9dca-4230-bb71-445e05cd6762.png)
I wonder if this is a design fault, in pvp and traitor mode, I was stunned for 60 points by someone using a fulgurium dart 
launched by master-quality stun gun, just now.

**Comment by BiffW** [comment]
In my opinion. Reducing the quality damage bonus to 25% per level and increasing progressive stun of normal darts to 34 can be a better solution.

**Comment by Jasontti** [comment]
Related to https://github.com/Regalis11/Barotrauma/issues/11795
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/019e66326ec670a31dcb9db771f165db3b78035e
Closing ticket
