### ISSUE TITLE
Spelling Mistake in autofill tags in wreck

### ISSUE THREAD

**Issue by qwerdo123** [Regalis11/Barotrauma#11630]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the bottom left module of the wreck named "Wreck1", the right ammo shelf contains the misspelled tag "wrechcoilgun" which should be "wreckcoilgun" like the other ammo shelf.
I'm assuming this affects loot spawning on this shelf
![Untitled](https://user-images.githubusercontent.com/24210103/226758624-5f798b0d-4b4b-4ba4-8f8a-38c57d7359da.png)

### Reproduction steps

1. Open the submarine editor and load "wreck1" under the wrecks section.
2. Click the right ammo shelf in the bottom left module of the wreck.
3. At the tags, you can see the spelling mistake. 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e0d485f0bb78bc676fb6630844d031cb4b83884f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
