### ISSUE TITLE
In DUGONG, the hatch is still flooded and the alarm goes on

### ISSUE THREAD

**Issue by zaczekradom** [Regalis11/Barotrauma#11636]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While dogging, the hatch is still flooded and the alarm buzzer goes on. Even after mooring to the station, it shows that part of the station is flooded. But there is no water there

Screen https://i.imgur.com/6ZSbwDP.jpeg

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not quite sure I understand the issue correctly: what exactly is flooded? The small hull below the hatch? The airlock? Aside from the ballast tanks, I cannot see any flooded rooms (either in the sub or the outpost) in the screenshot you posted. What buzzer do you mean? The flood alarm?

I also gave this a quick test, but could not spot anything unusual myself.

**Comment by Regalis11** [comment]
No known steps to repro, closing
