### ISSUE TITLE
Sub editor crashed and submarine can't be loaded

### ISSUE THREAD

**Issue by NenaTheSilent** [Regalis11/Barotrauma#11639]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

[Big Belly Barsuk.zip](https://github.com/Regalis11/Barotrauma/files/11019221/Big.Belly.Barsuk.zip)

I disabled the local mod for a bit, then when I re-enabled it and opened it in the editor it seemed fine at first. As I tried to save it warned me about objects being placed far away, then took me to a single abyss diving suit locker in the middle of nowhere before corrupting the save.

I'd really like my sub back :(

### Reproduction steps

Load the sub in the sub editor

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NenaTheSilent** [comment]
It doesn't crash the game, just the sub editor back to the main menu. You can load up my included sub, it should give you the same error log.

**Comment by Regalis11** [comment]
@NenaTheSilent It seems that mysterious diving suit locker far away from the sub had the same ID as one of the walls in the sub, causing this error. I removed that locker to get the sub to load again:
[Big Belly Barsuk.zip](https://github.com/Regalis11/Barotrauma/files/11110583/Big.Belly.Barsuk.zip)

However, I still don't know what caused that locker to appear there. This seems to be the same mystery bug as in this earlier report https://github.com/Regalis11/Barotrauma/issues/10591, so I'll close this one.
