### ISSUE TITLE
FractalGuardian flies in hull without water.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1163]
**Description**
https://media.discordapp.net/attachments/417766063477096459/546433647960653830/unknown.png?width=1082&height=677
The screenshot is not mine.

**Version**
Steam

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9539a5297a0862d5df7c25215a02c85877ab6dd2 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly.  Closing.
