### ISSUE TITLE
Unable to give crew member nickname

### ISSUE THREAD

**Issue by GeneralRechs** [Regalis11/Barotrauma#11634]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When attempting to nickname the crew the the crew member windows pop-up keeps flashing and no matter how often I left click I do not get a prompt for change the nickname.

### Reproduction steps

1. Go to crew management
2. Attempt to give crew member a nickname.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report, and sorry for taking so long to get back to this!

I unfortunately couldn't find a way to reproduce the issue, renaming seems to work with no issues:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/5d8df460-4e08-495c-82f3-8a9fe6f7bd41)

What do you mean by the "windows popup that keeps flashing"? Did the issue occur in single player or multiplayer?

**Comment by pavel4win** [comment]
One time I've encountered the inability to rename the bots that were originally given at the time when the game starts. But I can't to give exactly preproduction steps

**Comment by Regalis11** [comment]
Most likely a duplicate of https://github.com/Regalis11/Barotrauma/issues/12090
