### ISSUE TITLE
Errors in text.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1164]
**Description**
Creatureist
Strings 28, 48. Europan - Europ**e**an
137. contructed - con**s**tructed 

minerals
20. brockite - Br**oo**kite

medical
146. adviced - advi**s**ed
936. Radiotoxin - **Neurotoxin**?

**Comment by Regalis11** [comment]
Europan, brockite and radiotoxin are actually not errors: the game takes place in Europa (not Europe), brockite is an actual mineral and radiotoxin is a radioactive toxin.
