### ISSUE TITLE
Its possible to get sucked into the Berilia gunnery walls

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11644]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similarily to that wreck issue, on the berilia the player can swim into  a gap between hulls and shells and get stuck in the gunnery room, as you can see here
![image](https://user-images.githubusercontent.com/104232152/227339677-609e8d84-3edd-4306-8812-38cf5915e2ec.png)
![image](https://user-images.githubusercontent.com/104232152/227339694-f93641f1-729d-4846-94fd-2a691b92e98b.png)

### Reproduction steps

1.Check the hulls vs shells by the wall on the berilia

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Which wreck issue are you referring to? The steps to repro the issue are not quite clear: I guess you'll have to flood the room? But I can't see that on those pictures. The collider is a bit off yes (related to xx), which I guess means the character will go "inside" the wall. But does it cause some other issues?

**Comment by Regalis11** [comment]
@itchyOwl Here's the wreck issue Rehexr is referring to: https://github.com/Regalis11/Barotrauma/issues/11557

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75138a240c97489d00b7aba7c60a6aec2b5dee09

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
