### ISSUE TITLE
Steam cloud save does not work for server (multiplayer) saves

### ISSUE THREAD

**Issue by RJahnke** [Regalis11/Barotrauma#11651]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After a series of unfortunate events deleted the contents of my AppData/Local folder, I noticed my multiplayer campaign had disappeared.
Checking the steam cloud showed no saves for Barotrauma (despite being activated in Steam). After making a new MP save and checking again, still nothing uploaded. This is consistent across multiple attempts.
Single player campaigns are uploaded without a problem, I would expect multiplayer saves to behave the same way.

_RIP, crew, it has been an honour_

### Reproduction steps

1. Enable cloud saves
2. Start MP campaign
3. Save campaign and exit game
4. Check Steam cloud browser

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Someone from QA should test if this can be confirmed. If the saves stored in the cloud don't work, I'd say it's pretty severe issue.

**Comment by NilanthAnimosus** [comment]
Tested on steam, new changes now correctly sync both multiplayer and singleplayer saves (as well as multiplayer crew data). and when removing the folder it goes back to the correct location, closing as fixed without issues.
