### ISSUE TITLE
Line of sight is from torso rather from the eyes

### ISSUE THREAD

**Issue by TerminatorTM** [Regalis11/Barotrauma#11655]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There was such ticket long ago ( https://github.com/Regalis11/Barotrauma/issues/6405 ) with verdict: "we most likely won't be addressing at least for the game's full release."
Since release already happened - maybe it is time to respawn this ticket again? Actually it is very important feature for survival, not just cosmetic change.

There is a mod that fix it, but it is incompatible with many others. Can it help?
https://steamcommunity.com/sharedfiles/filedetails/?id=2893794930

### Reproduction steps

Look at the door with glass. Notice shadows. Crouch and repeat.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by CurePindal** [comment]
After a couple of years this is finally fixed in current Unstable.

**Comment by Regalis11** [comment]
This has been addressed in the upcoming LOS rework (PR in our private repo https://github.com/Regalis11/Barotrauma-development/pull/4030)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
