### ISSUE TITLE
Server Log stops updating at random

### ISSUE THREAD

**Issue by scouscous** [Regalis11/Barotrauma#11659]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While moderating for Trusted Seas, the server log will stop updating automatically. I have to close and reopen the log for it to update which makes it harder to catch griefers and other unwelcome behaviour harder.

### Reproduction steps

In multiplayer game, log stops updating. I have a feeling alt tabbing contributes to it but it has also stopped when I have not alt tabbed.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thanks for the report!

When you wrote that the log stops updating randomly and automatically, what do you mean by that? Does it sometimes stop updating or always after some ("random") time? You also wrote that the bug prevalence is regular, which I find a bit conflicting with the previous statement. What I'm after here is: how can we reproduce the issue and debug it?

**Comment by scouscous** [comment]
Hiya,

I would have the log open to view what people are doing to stop griefers
and after a certain amount of time (haven't timed so that's why I wrote
"random") it would stop automatically updating.

By regular I mean it would happen *a lot*. The only way I can think of
replicating this bug is hosting a session, giving someone you trust access
to the logs, and letting them see if it stops working as intended.

**Comment by Regalis11** [comment]
Seems easy to reproduce with the debug command "spamchatmessages" (using it just once makes the server log stuck like this).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e42106dba32dc92eac5bd0543288df54ecd7ec1

**Comment by Jasontti** [comment]
Tested. Server log works host, client and dedicated server window removes oldest messages correctly. Closing.
