### ISSUE TITLE
Wiring component can't override the reactor's fission rate auto control

### ISSUE THREAD

**Issue by RoggeOhta** [Regalis11/Barotrauma#11664]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Just as the title, I'm trying to use a wiring component to control the reactor, if my components send out a signal then it should override the auto control, if there is no signal the reactor should be in auto control mode.
Now the problem is, I can use the wiring component to override the turbine output, but not fission rate. So I think this might be a bug.

### Reproduction steps

In sub editor.
1. reactor*1, mem component * 2, random power load appliance * 1
2. add fuel to reactor, open auto control, open power load appliance
3. write mem component, set turbine output to 100, set fission rate to 0

the result is, turbine output can be overridden, but the fission rate seems like in a fight with auto control.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This is actually intentional: adjusting the reactor with signals doesn't automatically disable autocontrol. You should disable it yourself if you want to control the reactor with signals.
