### ISSUE TITLE
Way to Ascension can be started if Asssassination of Jacov Subra has been completed

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11669]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Completing the Asssassination of Jacov Subra leaves the subraevent_state at 2 which makes it possible to begin Way to Ascension since this check won't fail:
```
<ScriptedEvent identifier="waytoascension1">
      <CheckDataAction identifier="subraevent_state" condition="lt 3">
        <Failure>
          <!-- cannot start the way to ascension if the Subra assassination chain has been completed -->
        </Failure>
```

### Reproduction steps

1. Complete Asssassination of Jacov Subra (any outcome) while ignoring husk cult event chain
2. Find ecclesiast and begin Way to Ascension

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f239b3e068507edbabe7fc51ba1306e9f4a7fa5b

**Comment by Regalis11** [comment]
Actually, [I decided to revert the fix](https://github.com/Regalis11/Barotrauma-development/commit/88842f2fc41a12e4df9374353674ae40f8e9c704). I don't think there's really an issue here: the state is only left at 2 if you decide to let Subra live, in which case I don't see a reason to lock the players out of the Way to Ascension chain.
