### ISSUE TITLE
Round ends when Player(s) are uncouncious

### ISSUE THREAD

**Issue by LawnchairLarry** [Regalis11/Barotrauma#11660]
Even if it's just a short knockout or when there are Bot's around that could rescue you.

**Comment by Regalis11** [comment]
This is intentional: the round ends when all players are unconscious or dead. While we could keep the round running and wait for bots to revive the players, it could easily lead to extremely long wait times if the bots take a long time (or are unable to) revive them.

**Comment by LawnchairLarry** [comment]
Well i thought this is where the "give up" button is for...

**Comment by Altrentorae** [comment]
Is there any reason why this can't simply be a toggleable option in the server settings, seems rather limiting in it's current implementation when it comes to player agency. I understand that for a lot of larger crews eg (6 humans/2 bots) this might be the correct setting, but it makes absolutely no sense that when playing as 2 humans / 5 bots that if one of us dies, the instant the other is knocked out the game ends.

I've had multiple situations where as the last human player alive a crawler kills me and is left with one hit left. If the game continued another bot could easily finish them off and then the medic could heal me up before I bleed out. 
Even if the human players completely die, my team would be completely fine with seeing if the bots can recover from the state we're in and hold it long enough for us to arrive in the respawn shuttle.
