### ISSUE TITLE
Load Screen displays strange symbols in note text

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11663]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Single player, modded campaign. Language russian. Text note on Load screen shows strange symbols.

![image](https://user-images.githubusercontent.com/47295383/227775779-a3da2e11-5cde-4648-8908-815d15c45259.png)

### Reproduction steps

Just load modded campaign save.

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by pavel4win** [comment]
sorry for screenshot both my dysplays. Issue is in right display of course

**Comment by Regalis11** [comment]
Thank you for the report!

Which mods are you using? My guess would be that one of the mods is causing the issue, as we haven't gotten any reports of this from a vanilla game.

**Comment by pavel4win** [comment]
Used mod is in my config_player
[config_player.zip](https://github.com/Regalis11/Barotrauma/files/11112737/config_player.zip)

**Comment by Regalis11** [comment]
Thanks! That's a pretty huge list of mods - I don't think we have the resources to go install and go through every single one of those and try to find which of them might modify the loading screen texts, at least for the time being, but if anyone has any clues on which mods could be causing this (or if this can happen in the vanilla game), please let us know!

**Comment by pavel4win** [comment]
Ok, I will.
Mods which defenitely modify the loading screen texts is:
  <Workshop name="DynamicEuropa" id="2532991202" />
  <Workshop name="Dynamic Europa RU" id="2914269148" />
  <Workshop name="More Artifacts (AOCS)" id="2776026770" />
Mods which may be modify the loading screen texts but I not sure:
  <Workshop name="BaroTraumatic" id="2518816103" />
  <Workshop name="Barotraumatic Creature Pack" id="2831987252" />

My clues on which mods could be causing this
  <Workshop name="Dynamic Europa RU" id="2914269148" />
I think my be something wrong with codepage.

Other mods in my list almost certainly do not change the loading screen texts.

**Comment by pavel4win** [comment]
New information 
In this campaign less mods. No Dynamic Europa
main mess candidate is "More Artifacts (AOCS)" id="2776026770"

![2023-04-05_10-19-15](https://user-images.githubusercontent.com/47295383/230009477-b937a23b-90c1-411b-8954-4225daed4333.png)

[config_player.xml.txt](https://github.com/Regalis11/Barotrauma/files/11156191/config_player.xml.txt)

**Comment by Regalis11** [comment]
This seems to be a feature of the More Artifacts (AOCS) mod. Possibly some kind of a secret code?

From Text_Russian.xml:
<loadingscreentip>...ZCj*]^O_aETf#hu&gt;yi4al#E77kp:=ssw6owG]s]oz32B=YT}AwSH|NT~+2l:T1E=y0g{u{(|ECc^Omb9TF%Stm;ZU/sqOw*"v%G~.NiORB6Zw)...</loadingscreentip>
