### ISSUE TITLE
[Unstable] Crash when attempting to start a 'clear ruin' mission in the Europan Ridge

### ISSUE THREAD

**Issue by Quink-Fix** [Regalis11/Barotrauma#11667]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During my Unstable Campaign play-through, I attempted to start a clear ruin mission through a route that I had already traveled once before. The game crashed at that point, and all further attempts to load the save were met through failure.
(The save file has been rendered playable again by editing the currentlocation - the original save file will be provided.)
[Save 20.zip](https://github.com/Regalis11/Barotrauma/files/11073818/Save.20.zip)

### Reproduction steps

1. Attempt to load the save
2. Console throws an error upon attempting to load the mission and boots to main menu

### Bug prevalence

Just once

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to be the same error as https://github.com/Regalis11/Barotrauma/issues/11520
