### ISSUE TITLE
Focused flak shell have 50% penetration instead of 10% as other types flak ammo

### ISSUE THREAD

**Issue by jcx1991911** [Regalis11/Barotrauma#11661]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

<Item name="" identifier="flakshrapneldirectional" category="Weapon" scale="0.6" sonarsize="1" hideinmenus="true">
<Sprite texture="weapons_new.png" sourcerect="143,414,113,9" depth="0.55"/>
<Body width="170" height="10" density="20"/>
<Holdable slots="RightHand+LeftHand" holdpos="0,-50" handle1="-10,0" handle2="10,0" aimable="false"/>
<Projectile characterusable="false" launchimpulse="42.0" impulsespread="0.2" damagedoors="true">
<Attack structuredamage="40" itemdamage="50" severlimbsprobability="0.3" penetration="0.5">
<Affliction identifier="lacerations" strength="30"/>
<Affliction identifier="bleeding" strength="20"/>
<Affliction identifier="stun" strength="1.5"/>
<Affliction identifier="stun" strength="5" probability="0.1"/>
</Attack>

penetration="0.5" mean 50% penetration for every shrapnel if I understand correctly right?
This renders other types completely worthless.
Or this is some kind of "balance"?

### Reproduction steps

just check flakcannon.xml

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
focused flak bolt only spawn 5 shrapnels. I think it's fair to keep it high-penetration.

**Comment by jcx1991911** [comment]
> focused flak bolt only spawn 5 shrapnels. I think it's fair to keep it high-penetration.

Flak shell should be aimed at unarmored rather than armored targets, or at least it should not be high as railgun shell.
Both physically and in terms of game design this does not make sense.

**Comment by BiffW** [comment]
> > focused flak bolt only spawn 5 shrapnels. I think it's fair to keep it high-penetration.
> 
> Flak shell should be aimed at unarmored rather than armored targets, or at least it should not be high as railgun shell. Both physically and in terms of game design this does not make sense.

Disagreed. Every turret should have something to deal with armored targets. Coilgun has piercing, Chaingun has shredder, Pulse Laser's both ammo does have high penetration and Railgun has alienshell that has 80% penetration.
The Focused Flak Shells are designed to do the penetration work, so I don't think its penetration should be reduced.

**Comment by jcx1991911** [comment]
> 

Nah,considering the balance of ammunition efficiency we can enhance the armor penetration of Physicorium shell a bit to deal with armored targets, I will keep my point about Focused shell.

**Comment by JeroonBosch** [comment]
> This renders other types completely worthless.
Other types have their own uses, the spreader ammo deals much more damage overall.

> Every turret should have something to deal with armored targets.
> The Focused Flak Shells are designed to do the penetration work, so I don't think its penetration should be reduced.
This has indeed been the design intention, although an argument can be made that it should be slightly less than what it is now, like 35 or 40%. The penetration of focused flak shells should definitely be above the spreader ammo though, as that's the whole point of them.

**Comment by BiffW** [comment]
I don't think there's anything wrong with ammo efficiency. The focused flak shell has the lowest total damage per shot in exchange for more stable hits. It costs 2 leads. Not 1.
2 leads converted into coilgun standard ammo can deal 6000 damage.
2 leads converted into focused shells can deal only 3750 damage. (Ignore the impact because the bolt always explode before it hits the target.)
If there's not 50% penetration, its efficiency can be worse than a coilgun.

**Comment by jcx1991911** [comment]
> I don't think there's anything wrong with ammo efficiency. The focused flak shell has the lowest total damage per shot in exchange for more stable hits. It costs 2 leads. Not 1. 2 leads converted into coilgun standard ammo can deal 6000 damage. 2 leads converted into focused shells can deal only 3750 damage. (Ignore the impact because the bolt always explode before it hits the target.) If there's not 50% penetration, its efficiency can be worse than a coilgun.

You are ignore bleeding damage from every shrapnel right??
And In fact, the bolt does not always detonate before hit, if there is no miss shoot, at last half of the shots are able to hit directly,especially for medium and large targets.

**Comment by Ek-Videogames** [comment]
You say flak ammo is for small unarmored targets, but isn't using a flak cannon shell 200x less economical than using a coilgun at that point. It's like the same problem as shooting crawlers with canister shells, the larger ammos are never going to be cost effective - and maybe that's a good thing? Considering the heavy weapons should be meant for large armored targets, flak cannon is in a weird sort of space where it seems to fit neither niche: ammo too expensive to waste on soft targets, but not strong enough damage to kill hard targets.

> You are ignore bleeding damage from every shrapnel right?? And In fact, the bolt does not always detonate before hit, if there is no miss shoot, at last half of the shots are able to hit directly,especially for medium and large targets.

Bleed damage against non-human-entities is a joke, always has been.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c811a498950e67b5c67b6cdbfed0958495fb2ea7.
