### ISSUE TITLE
my friend can't join the server because keep getting p2p or time out

### ISSUE THREAD

**Issue by Ghaleman** [Regalis11/Barotrauma#11671]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

my party there are around 5-6 players but there a person keep getting steam p2p or connection time out when try to join game
at first he can play normally but it keep getting this error often and when we get the winterhalter and enter the great sea now he can't even join the game anymore

### Reproduction steps

1.host the server
2.wait friends
3.load campaign
4.wait till it finish load
5.and my friend can't join and getting p2p or connection time out

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Attempting to open ALC device "OpenAL Soft on Speakers (UBS Audio Device)"
Level identifier: greatseabasic
Generating an outpost for the start of the level... (Location: Gope Habitation Outpost, level type: LocationConnection)
Generating an outpost for the end of the level... (Location: Argiope Linea, level type: LocationConnection)
Coroutine "MultiplayerCampaign.DolnitialCameraTransition" has failed

i write from the picture my friend sent me

and at center of the screen is show
CONNECTION LOST
SteamP2P connection could not be established.
```

**Comment by itchyOwl** [comment]
I'm not sure if we can debug this based on the information, as there's no information about why the connection couldn't be established, but maybe someone else knows better.

**Comment by fkw11** [comment]
I get this same issue no matter what server I join. Fresh Windows 11 install. Fresh Barotrauma install. No mods.
![Barotrauma_GkAJHzuTXl](https://user-images.githubusercontent.com/131559772/233808573-e0cabc7f-7ab6-4f99-9fe0-91f5c0579603.png)
