### ISSUE TITLE
Handcuffed enemies are killed by turrets

### ISSUE THREAD

**Issue by VladMasarik** [Regalis11/Barotrauma#11673]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to enable beacon in a random level, I encounter beacons with enemy humans inside. I guess those are bandits. I stun them with baton, handcuff them, and try to get them onto my ship for an XP bonus. I keep stunning them so that they ragdoll, and I can pull them onto a ladder. I put a diving suit on them, and start dragging the in the water. They dont need to be ragdolled / stunned again, until I need to put them into the airlock, which for some reason refuses to accept them when they are conscious.

The "bug" happens when swimming around the sub, bots that are controlling the guns start shooting that the handcuffed bandits. Of course this kills me, and the bandit as well. So every time I handcuff the enemies, I have to remember to stop bots from manning the guns so that they don't blow me to pieces.

### Reproduction steps

1. Start mission with bandit? beacon
2. Stun and handcuff the enemies.
3. Have bots man the guns
4. Try to get the handcuffed enemies onto the ship
5. Die while swimming around a gun that is manned by a bot because they start shooting the bandit

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment]
I think in this case we could just tell the bots to ignore handcuffed targets. What do you mean by the XP bonus?

**Comment by metakot** [comment]
The author means "[By the Book](https://barotraumagame.com/wiki/By_the_Book)" talent of security officer role.

**Comment by VladMasarik** [comment]
> I think in this case we could just tell the bots to ignore handcuffed targets.

I could swear I saw in the code like `ignoreTargets` variable or whatever in the XML files, but I never found something relevant again. The best I could find was `IgnoreIncapacitated` and similar variables in `Content/Characters/<any creature>`, but I doubt that is relevant. I am not sure it would help even if that would be the case because I think that a turret and a person are treated differently, but I am not sure at all.

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@30eefd8.

> I could swear I saw in the code like ignoreTargets variable or whatever in the XML files, but I never found something relevant again. The best I could find was IgnoreIncapacitated and similar variables in Content/Characters/<any creature>, but I doubt that is relevant. I am not sure it would help even if that would be the case because I think that a turret and a person are treated differently, but I am not sure at all.

You are right: it's not relevant here. That's AI logic used by the monster AI. There's a separate logic for operating turrets. Also, we can't and shouldn't define this in the item level, because it's something that affects targeting regardless of the turret used for shooting.

**Comment by itchyOwl** [comment]
> Bots manning turrets are apparently firing at DECEASED enemies as well.

This shouldn't happen and I couldn't repro it. If it happens, could you post another ticket with the steps to repro it?

**Comment by Agent-Delta** [comment]
> This shouldn't happen and I couldn't repro it. If it happens, could you post another ticket with the steps to repro it?

For sure.
We haven't had anything like it happen again since; I'll post it as a new issue if it ever does make a reappearance.

**Comment by Regalis11** [comment]
Tested, could not spot any issues.
