### ISSUE TITLE
Azimuth water generating inside wall

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#11676]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Azimuth has a spot without hulls under the command room window in the inside wall, which will generate water if damaged despite being an inside wall with no water behind it.

![Näyttökuva 2023-03-27 173726](https://user-images.githubusercontent.com/86321358/227986969-d40e48a5-c68d-4b99-b570-6cea4c7e80ad.png)

### Reproduction steps

Damage the inside wall under the command room window

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Regalis11** [comment]
The fix needs to be reimplemented because of [conflicting changes done in another branch](https://github.com/Regalis11/Barotrauma/issues/11675), I'll reopen the ticket

**Comment by Jallu** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4147
