### ISSUE TITLE
[1.0] civilian transport giving 20 rep

### ISSUE THREAD

**Issue by 10mart10** [Regalis11/Barotrauma#11670]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the transport reputation for the event that gives the quest civilian transport still gives the old 20 rep boost in singleplayer instead of an adjusted for the 1.0 release

### Reproduction steps

single player
get civilian transport event
profit

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Radiation escape and eye researcher escort mission now give correctly +3 reputation each. Closing ticket.
