### ISSUE TITLE
Information leaked in stack traces

### ISSUE THREAD

**Issue by mlooney** [Regalis11/Barotrauma#11677]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When stack dumps occurr, information about the developer/development environment is leaked in the logs:

```
C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\StatusEffects\StatusEffect.cs
```

I'm gueessing joona doesn't like that, or maybe they don't care, just a heads-up.

### Reproduction steps

1. cause an unhandled exception when running from terminal 
2. look at the stacktrace

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by itchyOwl** [comment]
What's the context of this? Crash logs only show the local paths, not full paths. Also just tested that this is the case. Is it different when a server crashes? Was that what you meant?

Anyway, as long as it's not the player's data, it's not that big issue, but might still need addressing. Also don't know where "joona" comes, because there's nobody with that name in the dev team.

**Comment by itchyOwl** [comment]
Actually it seems that the stack traces that come from the third party libraries use the full path, as seen in #11684.

@Regalis11 have you intentionally/accidentally misspelled your name? :D

**Comment by Regalis11** [comment]
> @Regalis11 have you intentionally/accidentally misspelled your name? :D

This seems like a weird Windows bug - on every machine I use the username "joonas", the user directory gets named "joona".

I think the issue here is the path doesn't get cleaned up properly on Mac, seems to work properly on Windows and Linux.

**Comment by mlooney** [comment]
i'm just running the client from the terminal, i think you can trigger an exception by ctrl-c interrupt
