### ISSUE TITLE
Bots Fail to Switch to Available Oxygen Tanks and Consume Oxygen from Both Diving Mask and Suit Simultaneously

### ISSUE THREAD

**Issue by NPC-17** [Regalis11/Barotrauma#11680]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the game Barotrauma, there is a bug that causes bots to ignore the empty oxygen tanks in their diving suits and not replace them with new ones from the oxygen generator or full tanks available on a shelf. As a result, bots continue to work until they suffocate when the sub is filled with water. Additionally, bots equip both a diving suit and a diving mask simultaneously, causing oxygen to be consumed from both sources at the same time.

### Reproduction steps

1. Start a single player campaign.
2. Ensure that there is available oxygen on the sub.
3. Submerge the sub so that it sinks.
4. Wait for the bots' oxygen to run out.

This sequence of events has occurred multiple times, but it's not entirely clear what's causing the bug. During this time, it's also possible to observe that the bots will equip both a suit and a diving mask, causing them to consume oxygen from both sources.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I have been provided no bug errors or crash reports.
```

**Comment by itchyOwl** [comment]
The suffocation issue is probably the same as in #11680. Fixed the mask in Regalis11/Barotrauma-development@a8979dc. Closing this ticket as a duplicate.
