### ISSUE TITLE
Periodic Effects do not factor minvalue to apply their effects

### ISSUE THREAD

**Issue by Yoshbie** [Regalis11/Barotrauma#11682]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever you apply Morbusine, Sufforin, Paralysis and it's Slow counterpart to a human, their Periodic Effects do not wait to hit the minimum value threshold before they start applying their effects.

    <PeriodicEffect mininterval="1" maxinterval="3" minstrength="60" maxstrength="100">
      <StatusEffect target="Character" multiplybymaxvitality="true">
        <Affliction identifier="nausea" amount="50" probability="0.25" />
      </StatusEffect>
    </PeriodicEffect>
According to the code, the Nausea effects of Sufforin Poisoning should only apply between 60-100 strength, but this is not the case.

### Reproduction steps

1. Apply Sufforin Poisoning (most noticeable for this bug) to a Human
2. They get 50 Nausea before Sufforin Poisoning has reached a strength of 60 consistently.

https://user-images.githubusercontent.com/30814255/228048280-61c0adae-0065-4a36-ba19-22c792305404.mp4

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Looks like they ignored the max value too, fixed in https://github.com/Regalis11/Barotrauma-development/commit/4d8f3c48dee6297841ad1c566d068527ee57c395

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
