### ISSUE TITLE
Supplies were not delivered after retrieving Tormsdale Report

### ISSUE THREAD

**Issue by demiurgeQuantified** [Regalis11/Barotrauma#11683]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After retrieving the Tormsdale Report from a coalition station, the supplies we purchased there were not delivered to the submarine, but the money was deducted and the station's supplies of the items we purchased were exhausted.

### Reproduction steps

1. Get the Tormsdale Report mission, and go to the outpost for it
2. Retrieve the Tormsdale Report
3. Purchase supplies
4. Leave the outpost
5. Your supplies will not be delivered when the next round starts

### Bug prevalence

Just once

### Version

Other

### -

v1.0.8.0 LuaCs server, vanilla clients

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.0-patch-2 commit https://github.com/Regalis11/Barotrauma-development/commit/baf2d4b71b05a365354ecbeab42db0287ad329d5.

unable to replicate in single player or multiplayer, doesn't seem to be an issue (or is not tied to tormsdale report). Could be related to #10645 and both used mods that change the server and ran a server.

If there is any more information (A save file or mods list perhaps?) that would help.

**Comment by demiurgeQuantified** [comment]
Unfortunately, it was too long ago for me to have the save file still. The only mod we were running at the time was my [Reworked Respawn Penalty](https://steamcommunity.com/sharedfiles/filedetails/?id=2917485074), and the server was running LuaCs.
It did reoccur some time afterwards seemingly randomly (so the Tormsdale Report might not be related), but that time we received the items after a restart, which did not work the first time when I reported the issue.

**Comment by Regalis11** [comment]
No known steps to repro, closing
