### ISSUE TITLE
if you add any mod that adds new items to shops into campaign - they never appear in already existing save

### ISSUE THREAD

**Issue by ReiTheTrap** [Regalis11/Barotrauma#11687]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

if you add any mod that adds new items to shops into campaign - they never appear in already existing save
is this how it supposed to work? Because i dont remember it working like that before 1.0
this is the same issue just like the other one i reported ("clown shops are selling only fertilizers and nothing else after updating the old save into new update"). The shops in campaign never update. The only way to get new items from updates or from new mods /new mod updates - recreate whole savefile in new campaign or spawn them from console. 

i tested it with just one mod (More Unique Weapons and other mods to confirm that its not just this mod) on fresh no mod save.

![image](https://user-images.githubusercontent.com/112313823/228211139-aca2e52c-93ef-4317-a0a3-3565532d6905.png)
this is clown merchant shop. Before and after installing the mod. It didnt changed. 

this is after i created new campaign while having the mod (only the new items)
![image](https://user-images.githubusercontent.com/112313823/228212599-62eaec63-9504-40c8-9175-0f401aff7ca1.png)
![image](https://user-images.githubusercontent.com/112313823/228212639-b1c0c8b8-3969-4a4c-867c-74c46036b008.png)

the issues i mentioned happen to other people aswell.
didnt tested on newly generated outposts.

### Reproduction steps

1. start a multiplayer campaign
2. check shop. Save game.
3. install mod that adds new items to shops (like More Unique Weapons)
4. check the shop for the new items. 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Hey, thanks for the report! I don't think it's intentional. Could be bugged or just not implemented.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75a8bd6907c97f2775ae0f51fb7b6eb4dfb41091
