### ISSUE TITLE
Bananas pick up issue

### ISSUE THREAD

**Issue by Xahannist** [Regalis11/Barotrauma#11685]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

There are bananas on the floor not come from plant. Those bananas for some reason can't be picked up by the other crew members other than the captain. I've tried crouching and trying to pick it up but it did not work either. I was able to pick up the first couple of bananas from the tree but now I can't pick up any.

![image](https://user-images.githubusercontent.com/43429104/228129888-fc463b1b-268c-4439-8b6b-a2bcce295a87.png)

### Reproduction steps

1. Start campaign.
2. Plant banana tree
3. Eventually will get to a point where the bananas can't be picked up when they spawn

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Need confirming the repro steps: does it happen always when planting a banana tree?

**Comment by Xahannist** [comment]
Yeah this always happens when I plant a banana tree

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not find a way to get this to happen at my end. 

https://user-images.githubusercontent.com/14351070/228810564-0dc56fbf-d212-4ab0-a4b5-cba89c6ccaf9.mp4

I seem to have no issues picking up the bananas, so this most likely requires some more specific circumstances to occur. Perhaps something to do with the placement of the planter box? I don't see the planter or the tree in the screenshot, so I wonder how the bananas ended up there in the first place. 

If you happen to have a save file where this occurs consistently (or even better, a save with those unpickable bananas on the floor), could you send it here so we can give it a test? Thanks and sorry for the inconvenience!

**Comment by 1Zynx1** [comment]
has there been any progression with this bug at all as myself and a few friends keep facing it

**Comment by Regalis11** [comment]
> has there been any progression with this bug at all as myself and a few friends keep facing it

Unfortunately not, I still haven't been able to find a way to reproduce it. A save file where this occurs would most likely help us a lot in diagnosing it. Sorry for the inconvenience!

**Comment by ksmsergei** [comment]
Hi! I'm facing the same problem as you. As I see it, you used mods, just like me. I decided to look for problems in the mod files, and I think I understood what was going on. In the modification of Dynamic Europa, in this file:

`DynamicEuropa\Integrations\Hungry Europans\Content\Items\Food\Food.xml`

On line 77, I found override of the banana item, which starts like this

`<Item name="Banana" identifier="banana" category="Misc" maxstacksize="8" cargocontaineridentifier="metalcrate" description="" Tags="smallitem,seed,plantitem,fooditem,ingredient,petfood1,petfood2,petfood3" useinhealthinterface="false" scale="0.5" impactsoundtag="impact_soft" isshootable="True" requireaimtouse="True">`

I just commented whole _Item_ tag, restarted the game and now I can pick up bananas! I believe this is a bug of the mod itself. Of course, I don't think it's right that I just removed something from the mod, but the creator of the mod should deal with the problem. You can write him a bug report if you wish.

I also want to clarify that I play a single-player campaign, unlike you. And also, if you don't have a Dynamic Europa mod, I can assume that it's about another mod changing the banana code.

**Comment by Regalis11** [comment]
@ksmsergei I'm glad you spotted this! It does seem that Hungry Europans mod (and Dynamic Europa, which includes the items from that mod) causes this. The banana override in that mod includes the following line in the `Holdable` component
`<RequiredItem items="diving" type="Picked" requireempty="True" />`
Which in practice means you cannot pick up a banana if you're wearing diving gear. I think that line was intended to go in the OnUse status effects, which would've prevented eating the banana while wearing diving gear.
