### ISSUE TITLE
Input lag 

### ISSUE THREAD

**Issue by ZupperZane** [Regalis11/Barotrauma#11696]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

started while I was using mods, it seems to happen consistently yet randomly even in vanilla after a reinstallation, campaign and multiplayer. 
-no crashes
-possible important info
 -windows 11
 -NOHI 01 CyberpowerPC (keyboard)

### Reproduction steps

sadly this is very very random, but often, it most effects my inputs of "WASD" but when typing in the ingame chat it seems to appear there too. 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro, closing
