### ISSUE TITLE
Impossible to buy PUCS despite fulfilled requirements

### ISSUE THREAD

**Issue by madmoizo** [Regalis11/Barotrauma#11691]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The requirement is misleading, the game says you need 70, in fact you need 71
![image](https://user-images.githubusercontent.com/11896237/228310559-ef747983-6fe1-4e59-b38a-55c81cbf6477.png)
![image](https://user-images.githubusercontent.com/11896237/228310463-68a03fbf-131b-4631-8268-d10e57b1b0f2.png)

### Reproduction steps

1. Get exactly 70 reputation with Europa coalition
2. Go to a station which sells PUCS, you can't buy it
3. Do one more mission to get 71
4. Go back to the station, you can buy PUCS

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f12c43f8284c81f57050f8336f63b4d2e07a252

> Use rounded reputation values to determine whether you can buy/hire something. All menus display rounded values, making it seem like you can't buy something despite having enough rep if e.g. your reputation is 49.8 and the requirement is 50.

**Comment by Regalis11** [comment]
They're actually all floats, even though they're displayed using rounded integer values. For example, hurting an outpost NPC causes a reputation loss of 0.05 per unit of damage done, and a 20% bonus to reputation gains means 1 unit of rep becomes 1.2.

**Comment by Regalis11** [comment]
> I guess these micro loss are not displayed which is quite unfair to the player if consequences of his actions are hidden.

They are not really hidden - you get a notification whenever your reputation has changed by 1 or more. So the end result is basically the same as it would be if you got a penalty of 1 after doing a specific amount of damage.

**Comment by Jasontti** [comment]
Tested. If user sees correct number in reputation tab, they can purchase reputation locked items and crew.
