### ISSUE TITLE
[dev] when updating mod on workshop the game does not check main content pack xml for updates and uses old one

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1170]

**Comment by Regalis11** [comment]
I'm not sure if I understand what you mean, are you talking about publishing updates to your own mods or downloading updates to ones you've installed from the workshop? What do you mean by the main content pack?

**Comment by etet2** [comment]
pushing updates. by main content pack i mean the main file of content pack that specifies files that are used in the mod
