### ISSUE TITLE
Scavenger yields more wreck scrap than Scrap savant

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#11701]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Security gets close to 2x the amount of scrap per talent trigger than mechanic and thats on top of the rest of the loot they get. How about either increasing the chance for scrap savant trigger, changing condition to looting specific machines/cabs, or increasing scrap found? Maybe a combo of these things?

### Reproduction steps

1. start round, givetalent scrap savant
2. check wreck cabinets
3. givetalent scavenger
4. check wreck cabinets yet again

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
This talent is absurdly overpowered.

It works in wrecks, beacons, ruins and abandoned outposts (Weirdly testing didnt regenerated loot on pirates)

It has no conditional, so it can regenerate loot on EVERYTHING:

_Regenerated an extinguisher in a bracket from one of the level docking modules_
![image](https://user-images.githubusercontent.com/73229309/228994703-8e779d58-d76d-42c1-aefc-b33750400e2f.png)

Hit it with the nerf bat it deserves

```xml
    <AbilityGroupEffect abilityeffecttype="OnOpenItemContainer">
      <Conditions>
        <AbilityConditionItemInSubmarine submarinetype="Player" invert="true"/>
        <AbilityConditionItem tags="securecontainer"/>
      </Conditions>
      <Abilities>
        <CharacterAbilityRegenerateLoot />
      </Abilities>
    </AbilityGroupEffect>
```

It would only regenerate items from Secure steel cabinets. Can possibly add all variations of `secarmcab` if not good enough

**Comment by BiffW** [comment]
Limiting it to trigger only on "securecontainer" can make it a great loss of excitement when exploring the wrecks/abandoned outposts.
Firstly, it doesn't always trigger(Only 25% chance).
Secondly, player don't always meet with a wreck/abandoned outpost.
Thirdly, there's not always a "securecontainer" in the wreck.

In my opinion, this talent is just fine in competition with its opponent talent "slayer".
If this got nerfed like said, you might push everyone to pick the "slayer" and create a new balance issue.

**Comment by ubertpendragon** [comment]
Increased 25% loot on everything isn't balanced. 
Wrecks and ruins have a 100% chance of spawning starting biome 3+, abandoned outposts are extremely common in biome 4+

It also works on multiple security
Give it the `secarmcab,wrecksecarmcab,abandonedsecarmcab` tags if secure cabinet isnt enough but it needs the nerf bat

**Comment by BiffW** [comment]
> Increased 25% loot on everything isn't balanced. Wrecks and ruins have a 100% chance of spawning starting biome 3+, abandoned outposts are extremely common in biome 4+
> 
> It also works on multiple security Give it the `secarmcab,wrecksecarmcab,abandonedsecarmcab` tags if secure cabinet isnt enough but it needs the nerf bat

Yes, this makes more sense. The most important design of this talent I think is it always gives the player something to expect which is a great encouragement for player to explore.

**Comment by BiffW** [comment]
> Increased 25% loot on everything isn't balanced.
This is incorrect. There are many ways that player can get resources:
1.mining
2.ruin/wreck/abandoned outpost salvage
3.buying from merchants
4.creature loot

> It also works on multiple security
I agree this feature needs to go. Not much to say

> Wrecks and ruins have a 100% chance of spawning starting biome 3+, abandoned outposts are extremely common in biome 4+

There are also always some caves. The mechanic job have the ability to increase loot(mainly minerals) from caves by 20% and ability to increase deconstrution yields by 20% overall. I think it is fair for security to have salvage loot increased by 25%.

> Give it the ```secarmcab,wrecksecarmcab,abandonedsecarmcab``` tags

Limiting it to only trigger on secure are cabinets can turn it into another joke talent because secure arm cabinets only spawn a few weapons and ammunitions that can be fabricated in a few minutes. That's definately not balanced compared to mechanic's miner talent.

The original design I think is to encourage the player to do the salvage more actively.
I really enjoy the process to find every container and open them, thinking there might be extra loot.
Before 0.20, security did only have loot regeneration in wrecks and medic had the ability to regenerate loot in ruins.
Now that regeneration ability in ruins is moved to security, turing it into an attractive job for diving leaders.
If the ability roll back to only on wrecks, it might fail to encourage player to do ruins salvage which is part of intention ot design.

**Comment by ubertpendragon** [comment]
If we're talking about resource balance in particular:

In theory, vital resources such as fuel, ammunition or meds can be depleted/consumed, which pushes you to scavenge, mine or buy to replenish your stocks and not get a game over from a lack of dealing with hazards

In practice the talents trivialize many aspects of the game. Fuel for example; the levels are supposed to be longer, but your engine is faster. The bigger subs supposedly have worse fuel consumption (set manually...), but upgrades and quality cancel this out. Talents give you many extra free resources.

The difficulty curve ends up breaking, the game can be harder on the first biome than on the last, where you have fast submarines, powerful weapons, resource stockpiles and super soldiers.

A balanced version of both Scavenger vs Slayer wouldn't be +25% all loot vs +50% damage per harpoon. It'd be closer to 10% and 20%. But these numbers can be seen as boring, unfortunately that's the cost of having multiplicative bonuses cumulating.

Slayer is a good example of cumulated multipliers:
A harpoon coil rifle has a 1.7x damage multiplier, quality can add another 1.3x multiplier, and add the 1.5x multiplier of slayer. Then you've got the Spec Ops talent that adds a 2x damage multiplier against full life enemies. As a result you'll be one-shotting Bone Threshers using a single basic harpoon that uses 1/6th of a steel bar.

**Comment by Udrakan** [comment]
I think a guaranteed loot addition to secure cabinets in wrecks, abandoned outposts and pirate subs is more exciting than getting a chance to increase loot for every category. On the other hand, I wouldn't mind finding a knife, revolver, revolver ammo or SMG magazine in a beacon cabinet thanks to this perk.
