### ISSUE TITLE
Character customization menu squeeze when there are many initial characters

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11705]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

As the picture shows.
![customization menu all together](https://user-images.githubusercontent.com/99462070/229288208-664914f3-a0c9-4cb6-a7d4-0f31ffb06a7a.jpg)

### Reproduction steps

1. Install and enable many job extention mods (Acolyte, Harlyquin, Blade and whatever you can find)
2. Start a singleplayer campaign

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
