### ISSUE TITLE
The periscope control drone will be forced to move to the upper left if the drone is deeper than the submarine by more than 150 meters

### ISSUE THREAD

**Issue by jcx1991911** [Regalis11/Barotrauma#11703]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/116519004/229092775-1ae19965-14b2-45ae-b077-63147870e92c.mp4
I've tested multiple drones of the same type and all have had this bug, so it can't be a circuit design problem, and this bug has appeared 3 years ago.

and I think this may be related to this issue, but I have not reproduced the wrong angle output bug.
https://github.com/Regalis11/Barotrauma/issues/4796

### Reproduction steps

1.Host an online game session.
2.Remote control your drone until it's 150 meters deeper than your submarine.
3.If you want to dive deeper then shit happen.

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by jcx1991911** [comment]
https://user-images.githubusercontent.com/116519004/229097739-e3ac551e-7e64-406c-ac0d-360bc990bb90.mp4

It looks like the angle output is correct in the text but it is not actually, and it also matches the actual output of 193° in this issues
https://github.com/Regalis11/Barotrauma/issues/4796

**Comment by Regalis11** [comment]
Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/4796 (the periscope outputting an incorrect angle, even though it's used to control a sub instead of a turret in this case).
