### ISSUE TITLE
Inconsistency/Inconvenience Between Handheld Monitors

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#11709]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon entering an outpost, the Handheld Status Monitor behaves differently from the Handheld Electrical Monitor and Handheld Itemfinder. The Status Monitor shows the outpost as well as the submarine, while the Electrical Monitor & Itemfinder only shows the station.
![Status Monitor Outpost](https://user-images.githubusercontent.com/60911734/229309291-a466dd54-d9d5-4051-a38f-7cae42d4f8d3.png)
![Electrical Monitor Outpost](https://user-images.githubusercontent.com/60911734/229309301-31154012-dd85-49a5-96ba-ac2d782e8fbd.png)
- Handheld Itemfinder is not shown in these images but function the same as the Handheld Electrical Monitor in terms of only showing the outpost

The only way that I have found for the Monitors to display the submarine by itself when in an outpost level is to go outside into the water (out of any hulls) and then enter the submarine's hull through the airlock.

https://user-images.githubusercontent.com/60911734/229314446-45bb8798-d3a8-4d15-a6d5-27e20a426a79.mp4

However, the Monitors only switch to the submarine if they are being held/displayed. If they are just in the inventory they will not update.

https://user-images.githubusercontent.com/60911734/229314421-08577c07-6f10-440b-ab50-69d9a0549103.mp4

- The Electrical Monitor changes to the submarine, while the Sonar Monitor continues to show both the outpost and submarine.

It would make sense for the Handheld Monitors to show both the outpost and submarine when in an outpost or as an alternative, show the outpost but automatically switch to the submarine when coming from the outpost to the submarine.

### Reproduction steps

1. Start a round inside of the outpost
2. Equip any of the three Handheld Monitors. 
3. The Monitor should show the outpost, and if it is a Handheld Status Monitor, the submarine as well
4. Head down into the submarine, Monitors stay displaying the outpost
5. Leave the submarine, far enough for the Monitors to go blank, then return to the submarine
6. The Monitors will stop displaying the outpost and instead display the submarine

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/A
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f0cf069ee18a43f02cce02fa6b7bbd0a50342154

**Comment by Jasontti** [comment]
Tested. Status and electrical monitor works correctly when exiting or entering subs, outposts, wrecks and beacon outposts. Closing.
