### ISSUE TITLE
line of sight error

### ISSUE THREAD

**Issue by NomCarver01** [Regalis11/Barotrauma#11710]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

line of sight effect isn't working. i can see everything due to no line of sight effect even though i have it set to opaque.

![image](https://user-images.githubusercontent.com/115100377/229326876-9c6335e8-1a57-4ea0-92a9-d01b44b86827.png)

![image](https://user-images.githubusercontent.com/115100377/229327753-ef5a5649-2c83-4c49-bd00-eba7c6f061b1.png)

### Reproduction steps

start a solo or multiplayer match
load into the game
see everything

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I could not reproduce the issue though. In multiplayer, the server decides what kind of LOS settings to use, could it be that the server has disabled the LOS (overriding what you've set it to)?

**Comment by NomCarver01** [comment]
thanks for responding, I do not know what LOS settings means. but every time I host I have this issue. only on multiplayer. and all my friends who play with me experience this. I wouldn't be surprised if its one of my mods I  use that may of broke since the 1.0.0 update.
