### ISSUE TITLE
Auto Operate (turrets) cannot be shut down by any means

### ISSUE THREAD

**Issue by Agent-Delta** [Regalis11/Barotrauma#11711]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a design-related issue, rather than a bug.

Turrets with Auto Operate enabled cannot be forced to stop shooting by any "normal" means. Since the auto function is completely self-contained within the turret itself, wiring components (like relay switches) cannot be used to interrupt this functionality in any way. Similarly, relays cannot even be used to interrupt power to the turret since turrets must be hard-wired directly to supercapacitors in order to receive power. Furthermore, even if a player (or bot?) takes manual control of the turret, they can control the turret's position and fire at will, but the Auto Operate _can also still pull the trigger at any time_. Currently, the ONLY way to stop an Auto Operate turret from shooting at whatever it considers a target is to take away its ammo (or to let it run out of ammo).

Use cases for a kill-switch like this are not exactly abundant, but still present and valuable, such as:
1) "Stop wasting ammo on those ice spires that aren't in my way"
2) "Stop wasting ammo on that enemy you can't quite hit"
3) "Stop shooting at that thing I don't want dead" as in #11673

To me, it seems the simplest solution would be to add a pin to every turret's connection panel allowing Auto Operate to be toggled on and off via wire signal. If this is undesirable, given that it would affect all vanilla subs and allow players to activate Auto Operate on any of them, then changing something regarding the turret-relay-supercapacitor relationship might be the next best approach.

### Reproduction steps

For Auto Operate trigger control demonstration:
1) As a player, take manual control of any Auto Operate-enabled turret
2) Spawn any enemy within range of the controlled turret
3) Notice how player can operate turret normally but Auto Operate can and will immediately fire at any valid target the turret happens to be lined up with

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
It's not just about allowing to cut off turret power via relays, Auto-turrets can fire without any power somehow

![image](https://user-images.githubusercontent.com/73229309/229588284-04265c59-f2a7-493e-9fa8-6aa98202b02d.png)

**Comment by Agent-Delta** [comment]
Based on my own suggestion about making giving turrets a pin for turning Auto Operate off and on, I made [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2961643561) a couple weeks ago to address this issue.
I've decided to post it here to give the devs an idea of what I meant and to offer it as a solution for anyone else that wants this fixed at least temporarily.

**Comment by itchyOwl** [comment]
Added a "shutdown" input for supercapacitors that can be used for toggling it on and off in Regalis11/Barotrauma-development@aa55c5b:

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/e3835cae-7216-4b4e-afb0-19787aaeb99c)

Toggling the shutdown disables the power, so that turrets using it can't access the power, but it doesn't discharge the power from the supercapacitor.

**Comment by Jasontti** [comment]
Tested.
Connecting lever to disable_output or taking manual control stops auto operate.
Closing ticket.
