### ISSUE TITLE
Fight intruders command

### ISSUE THREAD

**Issue by gibbyest** [Regalis11/Barotrauma#11716]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While doing outpost assassination's every time I start the game if a bot has the fight intruders command the bots will just rush the outpost and die trying to kill every enemy.

While i do have mods enabled, The mods that I'm using doesn't change anything about the bots.

### Reproduction steps

1. Start the game while doing the mission.
2. After the moment you start it the bots will just rush the outpost.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7750
