### ISSUE TITLE
Fractal guardian  spawns outside of ruin, as well as invisible wall around ruins.

### ISSUE THREAD

**Issue by 20kbar** [Regalis11/Barotrauma#11714]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

As title says. I tried to get the ship closer to the ruin but unable to, and divers hit invisible section of walls before making contact with ruin, everything else is as normal. 
1 fractal guardian spawns 200m below ruin, out in open water. 

### Reproduction steps

Single player, seed same as campaign name: ZetaSP
![image](https://user-images.githubusercontent.com/129645270/229333933-7e0e8dda-878b-4caf-a8f6-2dcef0b90ec8.png)

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by duarm** [comment]
I've encountered countless invisible wall during my campaign with 4 people, always near alien ruins/wrecks/beacon stations

**Comment by Regalis11** [comment]
The invisible wall issue seems to be the same as this one: https://github.com/Regalis11/Barotrauma/issues/10458

I couldn't reproduce the guardian spawning outside the ruin though, despite testing the same level in a map generated with the same seed. It could perhaps be that I was just unlucky with the RNG. If you still have the save file available though, if you could send it here it might help us reproduce the problem!

**Comment by 20kbar** [comment]
I have tried to replicate this issue but it seems to be an only one time thing for now. I will keep you posted if things changes.
