### ISSUE TITLE
Game still runs after Steam is closed with broken steam functionality

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1171]
Minor non-breaking bug On Linux; the game seems to ignore the steam client. When "Exit Steam" is selected, the "Waiting for Barotrauma to shut down..." prompt is displayed indefinately, and BT still plays normally, apparently ignoring Steam's shutdown prompt. 

If Steam is forcefully exited either by killing the process or pressing "Exit Now", Barotrauma continues to run normally regardless of Steam being present. When pressing any of the non-dummied options in the menu such as workshop, join/host server, etc (since steam was open when the game checked for it so the steam options are available), the game crashes since the client resources are no longer available.

Not tested on Windows but I imagine it's the same.

**Comment by BillCombs** [comment]
Could be somehow related to #996. Though i tested it on Windows 7, and the steam version is closing properly for me. Perhaps it's different for Linux?
Check your config.xml file. If you have senduserstatistics setting set to True, set it to false and check how the game works after that.

**Comment by EdusFF** [comment]
Seems to be happening on Windows as well:

Subject: Game keeps running after I close it on steam

Operating System:
Windows

Hardware:
Windows 10, 16GB RAM, Nvidia GTX 1070 Ti, Intel i5 9th gen k series

Message Body:
Whenever I close the game it says running and I cant find its process in steam, so I have to close steam from task manager. This makes it hard to re launch the game and it is annoying.

**Comment by Rokvach** [comment]
This was an issue when the new Steam library was still in beta, this can also sometimes occur when leaving the crash report notepad open, but I haven't heard anyone having this issue for a while now, so I will be moving this to "Done" for further evaluation.
