### ISSUE TITLE
[Unstable] Macrodosing and Super Soldiers talents use invalid stat type

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11718]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The talents Macrodosing and Super Soldiers cause this error message on unlock and at the start of every round:
```
Invalid stat type type "MedicalItemDurationMultiplier" in CharacterTalent (supersoldiers)
Invalid stat type type "MedicalItemDurationMultiplier" in CharacterTalent (macrodosing)
```

### Reproduction steps

1. Use `giveexperience 18000` as a medic or `givetalent Macrodosing` and `givetalent "Super Soldiers"` to unlock the talents
2. Debug console should open with error message

### Bug prevalence

Happens regularly

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b2ea15e7d144f299a60bb3b17e7d85b568668306

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
