### ISSUE TITLE
Xor does not work as it should.

### ISSUE THREAD

**Issue by Gast9ra** [Regalis11/Barotrauma#11719]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Xor element treats NULL or 0 as 1.

![image](https://user-images.githubusercontent.com/22022942/229361373-e73f7520-9f27-4532-aac4-ee38f5eefe92.png)
![image](https://user-images.githubusercontent.com/22022942/229361402-a4f5205c-1398-4e86-a10a-d3e2f7460279.png)
![image](https://user-images.githubusercontent.com/22022942/229361412-07474f91-ecf6-408f-9d11-9f098d49d098.png)
![image](https://user-images.githubusercontent.com/22022942/229361455-7adab6fa-c713-4b02-97bc-71f7b51e4ddd.png)

### Reproduction steps

Null xor 0 = 1
0 xor Null = 1

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The circuits aren't sending "null" to the component, they're sending an empty string. Anything other than a signal of "0" (or nothing) is treated as true by all the signal components.
