### ISSUE TITLE
Text Display text does not rotate along with sprite

### ISSUE THREAD

**Issue by Agent-Delta** [Regalis11/Barotrauma#11712]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Just as title explains, the actual text does not rotate correctly when sprite is rotated.
Very similar to #9848.

![20230401221538_1](https://user-images.githubusercontent.com/126107030/229331161-f41cf605-4d23-49b8-904d-83077ddd196b.jpg)
![20230401221514_1](https://user-images.githubusercontent.com/126107030/229331164-9bc37036-4dce-4a2d-843e-c5284353713e.jpg)

### Reproduction steps

1) Place any Text Display in subeditor
2) Rotate Text Display to any orientation besides 0.0
3) Give Text Display any valid text
4) Observe how text does not align correctly with Text Display sprite (remains at 0.0 rotation)

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/ed1335e4c5682089be79f6c35e2be983c9501fbd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
