### ISSUE TITLE
PUCS has no aitarget

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11729]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Related to #11728 (since PUCS wasn't targeted by enemies, I figured it lacked the provocative tag) but the cause is that unlike every other suit which has `<aitarget maxsightrange="1500" />`, the PUCS does not have an aitarget defined.

### Reproduction steps

1. Wear PUCS while disguised as a husk
2. observe that husked creatures will not attack, despite the PUCS having the provocative tag

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ab51929144a3b11d504f9b3224340897a5cce61
