### ISSUE TITLE
 "stattype="RangedAttackMultiplier"" is not a valid StatTypes value

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11721]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It seems that RangedAttackMultiplier isn't defined, despite being listed as a Stattype

![image](https://user-images.githubusercontent.com/73229309/229384629-689b8096-0540-414e-8bfc-433629e7d125.png)

https://github.com/Regalis11/Barotrauma/blob/66a7822f9ad8362b9a2be9900cfdcf546aa3a6d9/Barotrauma/BarotraumaShared/SharedSource/Enums.cs#L110

### Reproduction steps

Use this affliction effect

```xml
    <Effect minstrength="0" maxstrength="60" strengthchange="-1" 
            resistancefor="damage" 
            minresistance="0.7" 
            maxresistance="0.7">
      <StatValue stattype="MeleeAttackMultiplier" minvalue="0.3" maxvalue="0.3" />
      <StatValue stattype="RangedAttackMultiplier" minvalue="0.3" maxvalue="0.3" />
    </Effect>
  </Affliction>  
```

### Version

Unstable (v1.1.4.0)

**Comment by Regalis11** [comment]
> despite being listed as a Stattype

Listed where? There's no such stat type in the Enums.cs file [nor the modding documentation](https://regalis11.github.io/BaroModDoc/Misc/StatTypes.html).

**Comment by ubertpendragon** [comment]
![image](https://user-images.githubusercontent.com/73229309/229490768-cd1c9fb1-5dff-4b43-af01-455ea410b512.png)


🤔

**Comment by Regalis11** [comment]
You seem to be looking at the master version of the code, that enum has been removed in v1.1.4.0: https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Enums.cs

**Comment by ubertpendragon** [comment]
I merely used the github search function 😩 

Oh well, closing
