### ISSUE TITLE
Projectiles don't stick to ragdolls properly in multiplayer

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11726]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Projectiles detach from ragdolls they're stuck to client-side, even though they're still attached server-side.

Seems to happen due to the changes in https://github.com/Regalis11/Barotrauma-development/commit/508ba0993400c0566baadb54859d368bcb6833e0: Using Ragdoll.SetPosition seems to automatically detach the projectiles, and that method's used to sync the ragdoll's position in MP.

### Reproduction steps

1. Fire a harpoon at a monster (may be easier to see what's happening if the monster is dead)
2. Notice the harpoon gets detached, but keeps teleporting back to the "stuck" position as the client keeps trying to correct it's position.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/de39146332a3d46a1f1671df64d2d2b949590e30

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
