### ISSUE TITLE
Can't fabricate depleted fuel with the "military applications" talent

### ISSUE THREAD

**Issue by Xahannist** [Regalis11/Barotrauma#11724]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I am trying to make depleted fuel using the recipe but its saying that I cannot make it even though I still have the additional skill of it.

![image](https://user-images.githubusercontent.com/43429104/229407470-ca794273-5a2d-4fa8-978b-2ac3d2c19c2a.png)

![image](https://user-images.githubusercontent.com/43429104/229407489-3cad98a2-0c50-438e-892b-fd45039f3f91.png)

### Reproduction steps

1. Be an assistant.
2. Go down the apprentice skill tree line.
3. Hopefully RNG gives you the "Military Applications" skill.
4. Recipe says I have the skill for it but cannot make it with items in fabricator. 

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I tried reproducing this, but unfortunately couldn't get it to happen at my end. It's worth noting that there are 2 depleted fuel recipes: one for thorium fuel rods and another for normal ones. It seems the one you have selected is the thorium one, although for some reason it's displaying the inventory icon of the normal rod in the input slots. I wonder if it could be that some of the mods you're using are modifying the crafting recipes in some way?
![image](https://user-images.githubusercontent.com/14351070/229439877-4a8bd3d0-a628-477d-bfb8-6d353b838ca9.png)

**Comment by BiffW** [comment]
I see you have 3 "2x recipe" in your picture. There are only 2 in the vanilla game. Could it be an issue caused by mods that you installed?

**Comment by Xahannist** [comment]
The recipe I chose was the uranium fuel rod that I could confirm whenever I hovered over the required items. It could be a mod issue but not too sure as the only mod we have installed which affects the reactor is Hazardous Reactors.

**Comment by Regalis11** [comment]
The Hazardous Reactors mod overrides all fuel rod items (and adds a bunch of new ones, some of which look identical to normal fuel rods), so I'm fairly sure this is an issue with the mod.

**Comment by Aranak** [comment]
It just happened to me right now with a normal assistant i was able to craft 2 recycle rod and then the crafting stopped when i asked for 4 rod. I'm playing vanilla and even after a save/restart it's still wont work again. Once it bug its dosent want to work on any character assistant or not.

![Image](https://github.com/user-attachments/assets/7cd3ecf5-2bfc-4953-ba22-5c243d59882c)

![Image](https://github.com/user-attachments/assets/6a43f345-208c-4ba9-8577-07e65d38f970)

![Image](https://github.com/user-attachments/assets/46de9ab3-47be-4fc5-a5fe-85a3ebe91243)

![Image](https://github.com/user-attachments/assets/e006d6de-bd37-4aa7-8a1d-8ed294455a3f)
