### ISSUE TITLE
Give Alien Devices Limited Power- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1173]
If alien guns have limited power why do alien devices not? Also if they had limited power they would be less handvanium.

**Comment by Regalis11** [comment]
>If alien guns have limited power why do alien devices not?

Because we want to ensure they're running when the player is exploring the ruins. It would be quite boring to find all the puzzles inside the ruins non-functional, or even more boring if the optimal tactic for ruin expeditions would be to first wait for the devices to run out of power.

**Comment by rico6822** [comment]
> Because we want to ensure they're running when the player is exploring the ruins. It would be quite boring to find all the puzzles inside the ruins non-functional, or even more boring if the optimal tactic for ruin expeditions would be to first wait for the devices to run out of power.

But devices can always have a lot of power, right? Even if they have none player can always use his tools in advantage.
