### ISSUE TITLE
Bots have trouble using Harpoon Coil-Rifles and coilguns

### ISSUE THREAD

**Issue by Lakey-Wings** [Regalis11/Barotrauma#11735]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've played the game extensively in singleplayer campaign and here are all the issues I VERY REGULARLY experience (8 or 9 out of 10 missions) about the AI (some may not be bugs, but a few definitely are):

1. AI doesn't fire Harpoon Coil-Rifle MOST of the time (they fire it only SOMETIMES, this issue killed my 50-minute run when I first encountered it)
~~2. AI suffocates by themselves in the sub with a diving suit that ran out of oxygen, but has full tanks in toolbelt + throughout the sub (the AI stands still on the spot)~~
~~3. AI swims to oblivion when outside of sub (usually swims towards upwards direction, but I had it happen downwards once)~~
4. AI targets (and sometimes fires) badly with coilgun (they should notice enemies much sooner, and they should also fire as if they are holding down LMB not occasionally tapping it while tracking the enemy)
~~5. AI does not go for nearest diving suit in a flood (they prioritise the locker while they should just pick up the ones on the ground nearest to them)~~

### Reproduction steps

To reproduce the bugs:

1. Just have them equip a Harpoon Coil-Rifle with harpoons + battery (the rifle is masterwork quality if that helps, and yes their batteries were full)
2. It happened twice, AI has maintenance orders and it happens after the sub was repaired after a flood, not sure how to reproduce this
3. It happened while I have my mechanic follow my captain (main guy), swim out for mining, then have my captain follow my mechanic. This does not happen 100% of the time but that's how it happened. Sometimes it happens when the sub is under attack and my security officer has Fight Intruders as top priority, while the creatures were outside of the sub (the sub is sinking, the officer somehow swam out and keeps swimming away from the sub with diving suit equipped)
4. I had a husk chasing me and I was swimming past a manned coilgun, the AI does not really use it well. The turret tracked the husk, but the AI was just occasionally firing once periodically. Also happens when enemies approaching the sub, the AI won't respond until the sub is damaged, then they start shooting
5. Place diving suit right on the feet of an AI manning turret, and flood the sub (ensure the diving suit lockers are full)

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
