### ISSUE TITLE
Protein bars heal nearly nothing when eaten

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11736]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When holding protein bars to consume them, the healing effects are almost zero. It should be healing 7.5 `damage`, but it seems to be healing much less than 1.

Energy drinks seem to be working normally, but they give such a tiny amount of hyperactivity that I can't say that for certain.

Protein bars used to work perfectly fine, but they stopped working after the 0.21 update when consumable items were changed slightly.

https://user-images.githubusercontent.com/37850646/229573660-70c4634c-13d6-44d3-b0c4-71dc161a303c.mp4

### Reproduction steps

1. be injured
2. equip a protein bar and hold right click
3. be disappointed by the amount that is healed

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0dc9ad30b2b649f3b5ef6a19f02ca2835c4459c0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
