### ISSUE TITLE
Some talents don't seem to have the right icon

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11738]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Just a small visual gripe but some talents seem to have the incorrect icon displayed:
La Resistance uses the same icon as Rifleman when there's a better fitting icon next to it (shield with syringe):
![image](https://user-images.githubusercontent.com/115734437/229579242-85bf065e-0834-49ac-b39a-8e67c2e1779a.png)
![image](https://user-images.githubusercontent.com/115734437/229579302-bc61c636-b673-4a6b-ae17-d8f8dcb8f8d5.png)
Journeyman uses the same icon as Weaponsmith, judging by the affliction icon I think the itentional icon is supposed to be the one below it?
![image](https://user-images.githubusercontent.com/115734437/229579833-2753a362-6043-457d-9b0f-22ae554adee4.png)
![image](https://user-images.githubusercontent.com/115734437/229579706-a435ab0d-2a4b-41c4-a555-1f66cb457092.png)
![image](https://user-images.githubusercontent.com/115734437/229579745-6d051573-fea3-41eb-9dbf-dd3399e5d15d.png)
Medical Assistance I'm not 100% sure on, since it does reference assistants, but maybe the icon below it could be used instead?
![image](https://user-images.githubusercontent.com/115734437/229580243-3ef761a4-b681-42d6-9e30-98255336dad6.png)
![image](https://user-images.githubusercontent.com/115734437/229580315-483c8f06-efb1-4157-a124-a818fdb7c559.png)

### Reproduction steps

1. Compare La Resistance and Rifleman icons
2. Compare Journeyman and Weaponsmith icons

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0c24af7050539c64015406e7b06edb4805183f92

**Comment by ubertpendragon** [comment]
![image](https://user-images.githubusercontent.com/73229309/229638075-f525ad55-e0fa-4eea-8342-f4a1323157ac.png)

![image](https://user-images.githubusercontent.com/73229309/229638090-f3241171-a091-4952-8298-cf6169daed46.png)


Probably would be more sustainable to have a system for icons to "crop" an outline using alpha blend/clipping mask directly into the base icon so you don't have to replicate each icon twice for afflictions and use less atlases

**Comment by HawkinsThe71st** [comment]
Cruisin' as well?
![image](https://user-images.githubusercontent.com/115734437/230426893-49b6140b-13ae-4783-858c-643c6fd93e2c.png)
![image](https://user-images.githubusercontent.com/115734437/230426977-23475476-2227-47bc-bbe7-4f7eb2bb1908.png)

**Comment by Rokvach** [comment]
Moved to ToDo because of the newer comments

**Comment by Regalis11** [comment]
Fixed the rest in https://github.com/Regalis11/Barotrauma-development/commit/ac0a0ebc3a49003bef93bd8898226255031a22d9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
