### ISSUE TITLE
Outpost docking modules allow flooding and killing the security AI 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11749]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Outpost docking modules easy allow players to bait security into the airlock, and spamming H to heal-grab the NPCs allows you to drown them. There was the issue of AI swimming outside the airlock and dying to pressure but it seems to have been fixed.

#11746

Moreover, airlock modules have very outdated wiring.
It's possible to make the wiring much simpler and also add a little cooldown to the doors so you cannot flood the outpost faster than water can be pumped in, which doesn't block security with auto-closing mechanisms

Before:
![image](https://user-images.githubusercontent.com/73229309/229909879-6b624616-d888-4c1a-8ed9-fc833d1b3091.png)

After:
![image](https://user-images.githubusercontent.com/73229309/229930911-f8e4c457-38df-4491-9fca-70a5a059923a.png)

[DockingModule_01.zip](https://github.com/Regalis11/Barotrauma/files/11153531/DockingModule_01.zip)

I can't tell if the waypoints leading to the outside are necessary or not 

### Version

v1.0.8.0

**Comment by Regalis11** [comment]
We've also got a fix coming up that should prevent dragging the bots around by making them break free if you grab them for too long: https://github.com/Regalis11/Barotrauma-development/pull/3997 (PR in our private repo). That should take care of this issue as well.

**Comment by ubertpendragon** [comment]
For the wiring, you've got button signals going into NOTs going into Relays into SET_STATE, as well as Doors + Buttons (and not buttoned door) and things being wired twice. 

Not game breaking as the module works, just a minor nitpick as you can replace all of it with a single Delay component

**Comment by NilanthAnimosus** [comment]
Tested against fix/1.0 commit https://github.com/Regalis11/Barotrauma-development/commit/8b2bd438a5d1b526d5a9397202d4ac48f2bc176b

Seems to work well to prevent dragging as you cannot generally get them to the airlocks, tutorials still work too. Noticed the following issues however:

Upon using the fire command to check if they will find safety, return etc, they were unable to return once it was safe, spamming the console with the inability to do the goto order:
![image](https://user-images.githubusercontent.com/29177976/235141880-ee9eb559-276e-4263-b533-d3e3b3349304.png)

Escort missions passengers also trigger the anti-grab. Which may make treating their injuries awkward. assumedly this may effect many missions/faction events and outpost events.

**Comment by NilanthAnimosus** [comment]
Tested against fix/npcs-stay-where-they-belong commit https://github.com/Regalis11/Barotrauma-development/commit/67dcb6b6afdeb5c1c0f48a7506a8ee7f3059fe59, No more issues found, Merged.

Notes: Goto issues (With the unsafe hulls) are a separate issue that will be fixed in another PR.
