### ISSUE TITLE
components can not handle multiple Condition_out in multiplayer

### ISSUE THREAD

**Issue by ancientchina** [Regalis11/Barotrauma#11741]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

nothing seems to be able to handle more than one "condition_out" in multiplayer settings.
wiring works fine on subeditor.

the issue is that while this set-up works and has been tested extensively on sub builder, multiplayer doesnt seem to be reliable or work at all. i believe that there may be some sort of issue with regex handling multiple inputs on multiplayer

### Reproduction steps

here is a condition monitor that quickly reports whether or not anything is repairable in a given area: 
-place a regex find component - set the expression to ^[0-7]?[0-9]$
->the expression is basically looking for any number between 0-79
-place a relay component
-all the junction boxes/installations go to signal_in1&2 -> signal outs go to regex signal_in
-regex signal_out goes to a text screen or light with the true being set to FIX IT and the false being ALL GOOD
Junction -> Relay -> Regex -> Display

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
n/a
```

**Comment by Regalis11** [comment]
Thank you for the report!

The way you've described it, I don't think this circuit can be used to check if anything is repairable in the area. There's no "or" logic in the regex component, nor is it supposed to be able to handle multiple simultaneous incoming signals. If wired like this, what it does is essentially checking one of the incoming signals (to be more specific, the signal from whichever device happens to get updated last during the frame). In general, sending multiple simultaneous signals to the same input is not recommended: it often leads to unexpected/unreliable behavior.
