### ISSUE TITLE
Missing Translation In Outpost Event (german)

### ISSUE THREAD

**Issue by Inflitor** [Regalis11/Barotrauma#11747]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Played Campaign mode and got Chinese Text as German Translation for the Outpost event where they are planting a bomb somewhere.
![image](https://user-images.githubusercontent.com/112323815/229895679-cc70bb7d-82aa-4ce5-b11d-b45b19f8e46b.png)
after clicking the Text the Translation was Fine and i was able to complete the Event without further Problems!

i was Using the Needs mod and the improved husks mod. both mods shouldn't change anything whit the Translation of the Vanilla events so i don't think they caused the problem

pls Note this only happend once so far... i didn't got the event again so idk if this was just a one time bug or if this happens always!

### Reproduction steps

1. Change Language to German
2. start a Multiplayer Campaign
3. Play the game until you trigger the Bomb planting event by walking around a station!
4. Talk to the man planting the Bomb
5. the translation should be in Chinese...

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/501a8e013d1f755a68439527d60f118af791c3ef (commit in our private repository)
