### ISSUE TITLE
MacOS version of the game can't join Dedicated Server hosted on a VM

### ISSUE THREAD

**Issue by BebopSpikeSpiegel** [Regalis11/Barotrauma#11748]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I hosted a dedicated server on an Azure VM, Debian 9 64bit.
When I was trying to connect it with my Macbook Pro(m1), it says connection timeout. I tried so many times and always the same result, I even tried to using Windows Server to host the server, but still timeout. But when I use windows laptop for reproduction, I joined the server instantly.

But p2p multiplayer seems fine. I tried join a random public server, it worked. Players said they are using P2P. Another server with 24/7 on the title shows timeout.

### Reproduction steps

-Use arm architecture of Mac
-Latest version of MacOS (Ventura)
-Latest Dedicated Server (on Windows or Linux, doesn't matter)
-Latest Stable build of game
1. Direct join that server you created
2. Displays timeout info
3. Try again with format of  ip:27015
4. Same result
5. Join a P2P server
6. Works

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Connection timeout
```

**Comment by super-cooper** [comment]
We're encountering this issue right now. Running a dedicated server on bare metal (docker container) and everyone can join except for our one friend on a mac. Can't direct connect or join from Steam.

**Comment by my-drea-ms** [comment]
+1. We can not connect from Mac to Win dedicated server.
Tested with g-portal.com and pingperfect.com dedicated servers.
"Connection timed out"

**Comment by Regalis11** [comment]
Most likely related to https://github.com/Regalis11/Barotrauma/issues/6190, we'll need to check and verify whether the fix implemented for that one takes care of this issue too. Sorry for the inconvenience!

**Comment by Regalis11** [comment]
Seems to have been fixed by the same fix we implemented for https://github.com/Regalis11/Barotrauma/issues/6190.
