### ISSUE TITLE
Pet Cthulhu performs worse than other pets

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11740]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've noticed during my game that among all the pets, cthulhu performs way worse than other pet: 
1.tend to fall from vertical passage in sub and "bounce" to its death
2.eating food recovers significantly less hunger compared to other pets
3.produce nothing expect poop and egg

I would think that first two points be obviously bugs, I guess it could be caused by low density of limbs(cthulhu only has 3 limbs, while other pets generally have 4 limbs), and low number in petbehavior configuration.

### Reproduction steps

1. start a campaign, and hatch a pet cthulhu
2. observe its behavior

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c4860cbf26589b41f94aef56245f3171fe5c4023

**Comment by Jasontti** [comment]
CThulhu is throwing an error:
"Character "Balloon" failed to eat a target (No head limb defined)"

**Comment by Jasontti** [comment]
It doesn't want to eat "petfood2" items, it did eat "dead".
Observed dropping poop and dementonite cluster. 👍

**Comment by Jasontti** [comment]
Tested.
Eats all of their preferred food and excretes what they should be.
Closing ticket.
