### ISSUE TITLE
Mods that add items with the same identifier causes error

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11744]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

As the title says, if you try to enable 2 mods that add items with the same identifier, one of them will be automatically disabled and marked red.
There should be a way to avoid this.
For example, make items that have the same identifier do override by default. Let the mod order decide which to use instead of causing an error and disabling one of the mods automatically. 

### Reproduction steps

Try to enable 2 mods that contain items with the same identifier.
Here are 2 mods that matches this condition
https://steamcommunity.com/sharedfiles/filedetails/?id=2809175631
https://steamcommunity.com/sharedfiles/filedetails/?id=2655395672

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I don't think this is a good idea. Allowing mods with conflicting identifiers to be enabled could lead to various hard-to-diagnose issues: if mod A relies on some content to work in a certain way, but mod B replaces that content with something else, it could lead to various problems. For instance, a mod might make the players spawn with some item, but another mod could use that same identifier for let's say a decorative structure.

**Comment by BiffW** [comment]
Letting out a strong warning in the console should be better than just disallowing.

**Comment by Regalis11** [comment]
I can see the reasoning, but I somewhat disagree. I think this is a similar issue as allowing players to enable mods that include errors (which we recently disallowed): even though the mod _might_ work without noticeable issues, it may also not, which leads to hard-to-diagnose issues and players thinking the game is bugged when a mod is causing the issue. It also doesn't encourage modders to fix the issues in their mods.

The same applies here: we can't assume the average player can figure out the appropriate load order for mods with conflicting IDs (if there even is an appropriate order that works without issues), nor to be able to determine if the mods can work together despite the conflicting IDs.
