### ISSUE TITLE
NPC removes diving suit when relieved control of in open water

### ISSUE THREAD

**Issue by EmeraldDolphin13** [Regalis11/Barotrauma#11753]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Happening once is unfortunate, this happens on occasion. Afterwards, I tried recreating the issue, but to no affect.

What's happening is, when I relieve my medic's control, and as they become an NPC, they seem to choose to take off the diving suit in the open water. Which is frustrating, but confusing. I'm trying to recreate the issue, but he's swimming back. So, I killed some creatures first, and had the medic  look for material. He grabbed some, I switched to the captain, and heard the diving suit clank on my ship, as his name disappeared from my roster.

His orders are, from left to right, Medical aid, recharge batteries, clean up.

I don't know if it's something I'm doing wrong, or if it's an issue with the game, but I just wish the only man with a degree would stop challenging physics.

### Reproduction steps

1. Start a singleplayer campaign
2. Have a full crew, it doesn't matter what ship
3. Have the medic wear a diving suit, it doesn't matter which type
4.Have the medic swim out of the ship to check some bodies for genetic material (maybe it's when he finds some[so far, I think it's when he retrieves genetic material])
5. Switch to a different character that's on the ship while the medic is out in the open water
6. The medic will take off their diving suit, and die

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thanks for the report! I don't think I've ever encountered this issue. More precise steps for reproducing the issue would be appreciated, hence the labels (for QA).

**Comment by EmeraldDolphin13** [comment]
> Thanks for the report! I don't think I've ever encountered this issue. More precise steps for reproducing it would be appreciated, hence the labels (for QA).

I tried being more detailed in the steps, I'll try and test to see how I could better understand what variables are needed to be satisfied for others to easily recreate this issue.

**Comment by itchyOwl** [comment]
Thanks for clarifying it. However, there's still questions that I'd like to have an answer before jumping into trying to repro it:
- You wrote that it happens every now and then, but can you try following the steps there and see if there's anything specific that you do when it happens, in contrast to when it doesn't?
- What items the medic has in the inventory when this happens? (A screenshot would be nice)
- Was the inventory full?
- What orders did the bot have, and in which order? (A screenshot would be good)
- If you can make it happen, could you open the console by pressing F3, type "enablecheats" and "debugai" and "freecam". Take a screenshot that shows the NPC.

Thank you for your time!

**Comment by EmeraldDolphin13** [comment]
> Thanks for clarifying it. However, there's still questions that I'd like to have an answer before jumping into trying to repro it:
> 
> * You wrote that it happens every now and then, but can you try following the steps there and see if there's anything specific that you do when it happens, in contrast to when it doesn't?
> * What items the medic has in the inventory when this happens? (A screenshot would be nice)
> * Was the inventory full?
> * What orders did the character have, and in which order? (A screenshot would be good)
> * If you can make it happen, could you open the console by pressing F3, type "enablecheats" and "debugai" and "freecam". Take a screenshot that shows the character.
> 
> Thank you for your time!

Thank you for this information. I'll do this ASAP. I gave the orders and the priorities, but I'll also try to include screenshots. I'll try to respond after collecting the information that is asked for

**Comment by Regalis11** [comment]
There have been various fixes to AI issues related to this in the latest update, I think it's very likely this has been addressed. Hard to say for sure though without reliable repro steps.
