### ISSUE TITLE
Too much Karma Leads to Gamecrash

### ISSUE THREAD

**Issue by Inflitor** [Regalis11/Barotrauma#11752]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was playing a Vanilla game online. we hade Griefers on the Server and i was Secruity Guard so i hitted them whit a Baton. what i didnt know was that Karma Was turned on. so i hited the Griefer 3 times (he had a diving suit on) and then evrything crashed(?) 
idk what happend didnt got a crash report and didnt recived a message the game just closed itself.

### Reproduction steps

1. join a game.
2. let the host turn on Karma
3. start a campaign
4. hit someone 3 times whit a stunbaton
5. the game now should have closed itself.

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not reproduce the issue though: hitting others with the stun baton doesn't seem to cause any errors. So I suspect the crash(?) was caused by something else, but hard to say what.

**Comment by Inflitor** [comment]
Allright. Still thanks for helping out. Ima tell you when i run into the Problem again.
