### ISSUE TITLE
Selling seeds removes the grown plants

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11756]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Selling seeds at outpost will remove the corresponding grown plants.

### Reproduction steps

1. start a campaign
2. grow some plants like salt vine
3. sell all the seeds 
4. find that plants also being removed

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e2288181222c210dd24ec081ae3827cceca52feb (commit in our private repo)

**Comment by Jasontti** [comment]
Tested. Planted seeds stay in their planter boxes and cannot be sold. Closing.
