### ISSUE TITLE
Genetic material afflictions that are `afflictionhusk` does not correspond to the actual genetic material condition when character have health multiplers.

### ISSUE THREAD

**Issue by shangjiaxuan** [Regalis11/Barotrauma#11769]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Genetic materials that are implemented with `AfflictionHusk` (`geneticmaterialmudraptor` and `geneticmaterialspineling` in vanilla) cannot set correct affliction strength when character has more than 100 total health (possible with vanilla talents).

The reason is as follows:
1. `GeneticMaterial.Equip()` sets new affliction strength to be 100 correctly, and applies on character health.
2. character health's apply affliction has the following line that modifies this value to be smaller:
```
var copyAffliction = newAffliction.Prefab.Instantiate(
    Math.Min(newAffliction.Prefab.MaxStrength, newAffliction.Strength * (100.0f / MaxVitality) * (1f - GetResistance(newAffliction.Prefab))),
    newAffliction.Source);
```
3. The previous is also true on other affliction types, but this gets corrected in normal afflictions with the line in `GeneticMaterial.Equip()`:
```
if (affliction != null) { affliction.Strength = selectedEffectStrength; }
```
4. However, `Strength` property is overridden in `AfflictionHusk`:
```
public override float Strength
{
    get { return _strength; }
    set
     {
         // Don't allow to set the strength too high (from outside) to avoid rapid transformation into husk when taking lots of damage from husks.
         float previousValue = _strength;
         float threshold = _strength > ActiveThreshold ? ActiveThreshold + 1 : DormantThreshold - 1;
         float max = Math.Max(threshold, previousValue);
         _strength = Math.Clamp(value, 0, max);
         stun = GameMain.GameSession?.IsRunning ?? true;
         if (previousValue > 0.0f && value <= 0.0f)
        {
            DeactivateHusk();
            highestStrength = 0;
        }
        activeEffectDirty = true;
    }
}
```
5. The threshold line, if I'm understanding correctly, shouldn't set the maximum to `ActiveThreshold + 1` when current strength is already over active threshold, but instead the actual maximum for the affliction. Reducing husk infection affliction, I believe, shouldn't need a threshold anyway? Or should it be that `GeneticMaterial.Equip` premultiply the factor (there may be rounding errors, though)? Or should it be that use `transitionthreshold > maxstrength` to signify no transition happens?

### Reproduction steps

1. Open sub editor
2. unlock max vitality boosting talents.
3. equip corresponding genes.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No crash.
I believe my response in "What happened?" is enough to locate the reason.
```

**Comment by Jasontti** [comment]
Tested. Closing.
