### ISSUE TITLE
Server doesnt know who dropped item

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#11766]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Aight it might be not bug, but here it is anyways. When you use this [mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2958875961) in singleplayer - it works just fine:
1. you grab someone and drop item like on gif below
![1](https://user-images.githubusercontent.com/42521948/230650424-7152e2dc-cd9a-4714-8cbe-87e4a90704a3.gif)
2. they get item
![2](https://user-images.githubusercontent.com/42521948/230650570-560a5669-6c15-49c9-b8a6-75374d97365e.gif)

Seems pretty good, right?

But as soon as I launch MP, it seems like for some reason the server doesn't know who dropped the item...
It will do all the same stuff above but then item will drop out on floor.
barotrauma has the Drop() method on the server and it can specify a character but its always nil on the server....

### Reproduction steps

1. Get client side lua using instructions from [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2559634234) or [here](https://github.com/evilfactory/LuaCsForBarotrauma/) 

2. use this archive or code because authors code now remade to be run only on server to compile your own copy, just make sure to change it's type from `.txt` to `.lua`
(damn author changes code fast bruj)
[Handover.zip](https://github.com/Regalis11/Barotrauma/files/11180870/Handover.zip)
[handover.txt](https://github.com/Regalis11/Barotrauma/files/11180871/handover.txt)

3. Launch Local Server where mod is enabled only on your server (for example using `DedicatedServer.exe` or friend's in-game hosted one

4. try to repeat same procedure
![1](https://user-images.githubusercontent.com/42521948/230651930-0957c305-19c0-4ef2-8807-2ddb6011fd87.gif)

5. observe the result

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! To me it seems like this is an issue in the mod. If the server needs knowledge of the client who dropped the item for the mod to work correctly, the creator of the mod should implement that.
