### ISSUE TITLE
PUC suit autoinject tag on Itemcontainer instead of Subcontainer

### ISSUE THREAD

**Issue by Draconis13** [Regalis11/Barotrauma#11764]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

PUC suit in unmodded is not injecting chems or medical items into the player when at low health. Checked XML files and found the Autoinjector headset which works is using it on the Itemcontainer and containable items are medical and chem items which is correct. The PUC suit however has the Autoinject="true" on the Item container set to oxygen/fuelsource which is causing a bug where it uses the subcontainer medical/chem item without actually applying the medical item effect to the player. 

 •Autojector code, correct 
 
   <ItemContainer capacity="1" maxstacksize="1" autoinject="true">
   <SlotIcon slotindex="0" texture="Content/UI/StatusMonitorUI.png" sourcerect="384,448,64,64" origin="0.5,0.5" />
  <Containable items="chem,medical" /> 

•PUC container code incorrect
    <ItemContainer capacity="0" maxstacksize="0" hideitems="true" containedstateindicatorstyle="tank" containedstateindicatorslot="0" autoinject="true"  > 
      <Containable items="none" />
      <SlotIcon slotindex="0" texture="Content/UI/StatusMonitorUI.png" sourcerect="64,448,64,64" origin="0.5,0.5" />
      <SlotIcon slotindex="1" texture="Content/UI/StatusMonitorUI.png" sourcerect="384,448,64,64" origin="0.5,0.5" />
      <SubContainer capacity="1" maxstacksize="1">
        <Containable items="oxygensource,weldingtoolfuel" excludeditems="oxygenitetank" />
        <Containable items="oxygenitetank">
          <StatusEffect type="OnContaining" target="Character" SpeedMultiplier="1.3" setvalue="true" comparison="And" targetslot="0">
            <Conditional IsDead="false" />
            <Conditional HullOxygenPercentage="lt 50" />
            <Conditional InWater="false" />
          </StatusEffect>
        </Containable>
      </SubContainer>
      <SubContainer capacity="1" maxstacksize="1"   >
        <Containable items="chem,medical" />
      </SubContainer>

### Reproduction steps

Enter any sort of game mode and place medical item in PUC suit and receive damage to trigger autoinject, item is removed from PUC suit but does apply to player. Putting any item in PUC suit while at low health triggers autoinject but due to being on Itemcontainer it does not apply to character and needs to be on subcontainer. 

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The XML is actually correct: autoinjection is a feature of the ItemComponent, and should be defined in the ItemComponent element. We've got an existing ticket about the autoinjection functionality being broken: https://github.com/Regalis11/Barotrauma/issues/10389
