### ISSUE TITLE
EMP light flicker barely noticeable

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11762]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Light flicker duration scales with EMP strength
Above 1 `empstrength`, the explosion will almost instantly disable JBs, shutting down lights. 
Below 1 EMP, the duration is too short, and you can barely see it

An EMP grenade is 10 EMP, instantly frying every junction box so you will not see any flicker
A black Moloch attack is 0.5 EMP

https://github.com/Regalis11/Barotrauma/blob/66a7822f9ad8362b9a2be9900cfdcf546aa3a6d9/Barotrauma/BarotraumaShared/SharedSource/Map/Explosion.cs#L199

Flicker probably should not scale and use a fixed duration instead

empstrength="1"
![image](https://user-images.githubusercontent.com/73229309/230611584-efd9e08c-ab8e-407f-82ad-3450fdca58d9.png)

#10913

### Reproduction steps

Use command `explosion 500 0 0 0 0 1`  to trigger a 1 EMP explosion on top of a lamp

Compare with 0.25

### Version

v1.0.8.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/3a67b8fb9e1cf30105e31a706138735c3897b0a7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
