### ISSUE TITLE
AI's problem with Typhon 1 top docking hatch repair

### ISSUE THREAD

**Issue by ooohsenpai** [Regalis11/Barotrauma#11781]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots cannot repair Typhon 1 top docking hatchet and walls around it, telling that they can't reach it. Same problem with Typhon 2 already got fixed, seems like his little brother is a poor forgotten fella...
It makes it pretty annoying ship to use, especially since we have lost ability to buy Typhon 2 in early game.

### Reproduction steps

1. Start a mission with a Typhon 1
2. Break top docking hatchet and/or walls around it
3. Watch bots running around and screaming about their inability to climb ladders.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Merged, closing
