### ISSUE TITLE
Hospital/Prison bed draw characters in front 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11784]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hospital/Prison beds don't have `drawuserbehind="true"` in their controller, unlike other beds:

![image](https://user-images.githubusercontent.com/73229309/230747807-4868939c-2aea-4ef0-a920-b2fa215e7caa.png)

### Reproduction steps

a

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0c0c11ac569f1f8cccf0aa9421c4a864afca3b6b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
