### ISSUE TITLE
[Unstable] Decoy depth charges have a broken OnImpact status effect

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#11786]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Both normal decoys and nuclear decoys behave rather strangely. They have an OnImpact -> -100 health status effect, which should lead to an OnBroken effect that triggers an explosion, but at the same time, they have health=200.

I have tested them both with this setup:

![image](https://user-images.githubusercontent.com/59519434/230783403-385333c3-4b9f-4356-8ce9-585ea0e62f8a.png)

1) Herja, disableenemyai, spawn a line of creatures below the sub
2) Use decoy and a nuclear decoy on them
3) Catch the decoy via teleport and see how much health it has

Result:
-it falls through all of the targets
-it has 100, as the OnImpact SE suggests
-also, the OnImpact SE only triggers for the first target (bringing down the health to 100)
     -the target does a ragdoll impact sound and the decoy slightly slows down
![image](https://user-images.githubusercontent.com/59519434/230783516-58d4ad91-f211-49a7-bc8f-1554afb75b00.png)
-something funky is going on with the decoys...

Another thing - this might be a related, or a different bug

1) Sub editor, Herja (has decoy already loaded in tube)
2) Spawn moloch below, it does not see the sub
3) Drop the decoy
4) Watch the molochs behavior

Expected: Moloch is driven away by the decoy depth charge
What we got: Moloch is drawn closer to the submarine

![image](https://user-images.githubusercontent.com/59519434/230783643-b2525624-6e70-4b56-aed9-5cb99b6225be.png)

The depth charge spends more time above the moloch than below it (due to accelerating), drawing the creature closer towards the sub, which is the exact opposite of the intended effect. This is likely caused by the decoy falling too quickly.

### Reproduction steps

above

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment]
Moloch stuff
https://user-images.githubusercontent.com/59519434/230784944-ac6eb63d-451c-4b23-b8fc-8d32b5bc58b5.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/65b30a91967993171325455d0e75ee9734e5dfec

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
