### ISSUE TITLE
Typhon submarine is outdated + rework

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11783]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Typhon has been refreshed a little but is still very outdated.

A non-exhaustive list of issues:
-8 pixel offset (present on many old subs, makes resizing hulls a pain)
-Many Waypoint issues
-Legacy pumps (different stats)
-Legacy walls
-Double walled floors between gunnery 
-Huge combined engine + fabrication room
-Lots of small rooms in the central passage (lots of doors to open)
-Batteries plugged directly into the grid, charging and discharging simultaneously (stabilizes grid with no downside)
-Lots of minor visual issues, sprite depth conflict...
-LOS issues (some see-through walls)
-Very dark lighting, lights bleeding through walls

**Proposing a Typhon refresh:**

[TyphonRework.zip](https://github.com/Regalis11/Barotrauma/files/11184494/TyphonRework.zip)

![wikiimage](https://user-images.githubusercontent.com/73229309/230747435-0626c985-8493-4093-b9eb-9beda5682830.png)

Main changes:
-Corrected the 8 pixel offset
-LOTS of visual adjustments
-Improved lighting a bit (less shadow casting, better visibility)
-Fixed LOS holes
-Replaced all legacy pumps, all legacy walls (except docking port)
-Removed almost all doors in the bottom hallway
-Replaced top left crew compartment with a restroom
-Added a small brig (empty space + no vanilla sub had a brig)
-Minor ballast resize so all 3 have the same size (0.7 => 0.68 NBL)
-Changed Armory access layout
-Battery in and out going through relays, can be toggled
-Engine power consumption -500, Reactor max power -500 (compensates battery change)
-Adjusted JB overvolting to 1.5 from 1.7 (to match battery change)
-Increased Railgun angle; at 90° it was even more restrictive than that of Typhon2

I've taken some liberties with some changes, but the sub is so outdated and unpopular it was worth a significant refresh. It still has most of its old quirks (notable the bad speed/descent). Item count went up slightly but remains reasonable.
Tested on unstable with players and bots.

![image](https://user-images.githubusercontent.com/73229309/230747477-11fd87d2-fdaa-4b22-8bab-506d36dba791.png)
New item count
![image](https://user-images.githubusercontent.com/73229309/230747635-c02e6698-5ae6-4684-a4a0-72864561f10b.png)
Old item count
![image](https://user-images.githubusercontent.com/73229309/230747677-fc98a045-b56f-4ce3-a4b5-11725815bac9.png)

### Version

v1.0.8.0

**Comment by ClayGale** [comment]
Gorgeous! Even if it doesn't make it in please put it on the workshop

**Comment by Regalis11** [comment]
Thank you, this seems like a huge improvement! Created a PR in our private repo: https://github.com/Regalis11/Barotrauma-development/pull/4120

**Comment by ubertpendragon** [comment]
Updated after several hours of unstable testing

[TyphonRework.zip](https://github.com/Regalis11/Barotrauma/files/11237245/TyphonRework.zip)

Corrected some LOS issues, minor visuals as well as hulls having a 1 pixel offset almost everywhere. 
This should be the final version

**Comment by Regalis11** [comment]
I take it you've never tested the sub with bots? ;)

**Comment by ubertpendragon** [comment]
> I take it you've never tested the sub with bots? ;)

We did but nobody noticed any game breaking waypoints 😨

**Comment by Regalis11** [comment]
Merged, closing
