### ISSUE TITLE
FUEL_OUT on reactors no longer displays the current fuel value, instead displays fuel value if all rods were at 100%

### ISSUE THREAD

**Issue by goder5555** [Regalis11/Barotrauma#11796]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I discovered while using a text display to see the amount of fuel left in my reactor that it no longer shows the current amount of fuel and instead the maximum amount of fuel those rods can hold

### Reproduction steps

1. Put a fuel rod into a reactor
2. Wire up a text display to fuel_out
3. Notice that the text display does not change with the condition of the rods

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This is not a bug: the fuel_out connection does not (and afaik never has) output the condition of the rods, but the amount of "available fuel" in the sense of how much fuel the reactor can utilize at the moment. It won't start dropping until the rod is too empty to keep the fission going. If you want the percentage of fuel available, you should use the "fuel_percentage_left" output instead.
