### ISSUE TITLE
Dropping a cargo scooter in the sea near an already dropped cargo scooter may cause one cargo scooter to disappear

### ISSUE THREAD

**Issue by tramon** [Regalis11/Barotrauma#11799]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Scenario: Cargo scooter dropped near another cargo scooter in the sea disappeared
Given a player is in the open sea
And There is an already dropped cargo scooter near
When you drop a cargo scooter via drag n drop
Then cargo scooter that you are  dropping is visually transited to a cargo scooter that is already dropped near
And one of cargo scooters disappear

### Reproduction steps

Scenario: Cargo scooter dropped near another cargo scooter in the sea disappeared
Given a player is in the open sea
And There is an already dropped cargo scooter near
When you drop a cargo scooter via drag n drop
Then cargo scooter that you are  dropping is visually transited to a cargo scooter that is already dropped near
And one of cargo scooters disappear

Video Attachment:
https://user-images.githubusercontent.com/18694482/231178773-d0d45f8a-60fc-404b-8d8f-187a1cf726b5.mp4

No errors were raised during the game.

We didn't use mods or cheats.
Multiplayer campaign
A player that dropped the second cargo scooter was client while the first cargo scooter dropped by server player

Cargo scooters were created by the bot.
Cargo scooter was dropped in the alien ruins.

It is visible that cargo scooter transits to another place from the place where client player dropped it.

Severity: low

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
There were no crash reports.
```

**Comment by tramon** [comment]
Unfortunately I was not able to reproduce it in Submarine editor. But the video attached at second 7 shows how it actually jumps into second cargo scooter.

**Comment by AzureNocte** [comment]
I think it is a problem related to desync of multiplayer, it happened twice for me too, with metal crate dropping on ground disappeared.
