### ISSUE TITLE
Some Missions Prevent Selecting Other Missions- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1179]
I believe in campaign some mission in barotrauma should prevent selecting other missions.

### Example:
Beast from The Abyss disallows all cargo missions from being selected but player can still see them available.

**Comment by rico6822** [comment]
> I believe in campaign some mission in barotrauma should prevent selecting other missions.
> 
> ### Example:
> Beast from The Abyss disallows all cargo missions from being selected but player can still see them available.

What I mean is that player cannot take cargo with self on a mission if there is an verified endworm.

**Comment by Regalis11** [comment]
Tbh I don't see any need for that. 

As a general suggestion, your feature requests would be much more helpful (and more likely to be added) if you tried to explain why you feel the feature would be useful. With these sort of 1 sentence requests it's often difficult to figure out what problem you're trying to solve with the feature, or even to discuss about the idea.

**Comment by rico6822** [comment]
> Tbh I don't see any need for that.
> 
> As a general suggestion, your feature requests would be much more helpful (and more likely to be added) if you tried to explain why you feel the feature would be useful. With these sort of 1 sentence requests it's often difficult to figure out what problem you're trying to solve with the feature, or even to discuss about the idea.

During briefing of "Beast From The Abyss" the player can learn all transports have been cancelled.

**Comment by Regalis11** [comment]
That won't prevent the player's crew from venturing through the level - I'd imagine that the people in the outpost would be even more eager to pay you for transporting the cargo if you're willing to do it.

**Comment by rico6822** [comment]
> That won't prevent the player's crew from venturing through the level - I'd imagine that the people in the outpost would be even more eager to pay you for transporting the cargo if you're willing to do it.

Lol, ok.
