### ISSUE TITLE
Reactor meltdown warning creates smoke when it receives a signal

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11798]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It is possible to send signals to a reactor meltdown_warning, making it possible to create a false alarm. If intentional, I don't think it should create smoke as there isn't anything actually overheating:

https://user-images.githubusercontent.com/115734437/231152528-c2323dc0-a71f-435a-9db7-551c1798b7ce.mp4

### Reproduction steps

1. Wire lever signal_out to reactor meltdown_warning
2. Flip lever

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested. Works.
