### ISSUE TITLE
mysterious letter "d" occur in chaingun.xml

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11797]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

chaingun.xml, line 295
`    <Sprite texture="Content/Items/Containers/containers.png" depth="0.54" sourcerect="747,602,95,78" origin="0.5,0.5" />d`

Doesn't seem to affect gameplay. But it bothers me when debugging my mod.

### Reproduction steps

see chaingun.xml, line 295

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f82f33337e06f20e77b3a28e0294246a2e973815
