### ISSUE TITLE
Barotrauma Doesn't Count as an Application Process

### ISSUE THREAD

**Issue by AlyMar1994** [Regalis11/Barotrauma#118]
I've noticed with Barotrauma that the game doesn't, to Windows, count as an application process, only a background process.

It doesn't say it's a program on things like the Taskbar or Task Manager, so tabbing out/in is impossible, and other tasks and implications.

Tabbing out also forces the desktop to be white until you shut it off with Task Manager.

Tested 3 times on a Windows 10 computer, fullscreen @ 1600x900.

EDIT: This happens when using both Barotrauma.exe or BarotraumaLauncher.exe.

EDIT 2: Image:
![capture](https://user-images.githubusercontent.com/20891893/33799942-299c4430-dd04-11e7-9968-e5be32d4745e.PNG)

**Comment by G234i** [comment]
Not sure how Win10 handles background and application proceses differently but tabbing out and then having a white screen can be fixed by starting in borderless window and it would seem that this is a problem of the game engine beeing used :smiley_cat:

**Comment by AlyMar1994** [comment]
> but tabbing out and then having a white screen can be fixed by starting in borderless window and it would seem that this is a problem of the game engine beeing used

That would be a nice solution, but I AM using Borderless Windowed mode; the game essentially forces me to use it, whether I select Windowed or normal Fullscreen.

**Comment by Regalis11** [comment]
I don't think this occurs in the latest versions anymore. If it does, let me know and I'll reopen this.
