### ISSUE TITLE
Clown quest chain not completing

### ISSUE THREAD

**Issue by Gsanbz** [Regalis11/Barotrauma#11803]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello, I want to address the issue of the clown quest chain. Our team completed the first two tasks - namely, to get a clown mask and hit a monster from the abyss with a hammer. For the third mission, we went to defend an outpost in a clown exo-suit. As a result, we completed eleven out of forty points for the assignment, and the outpost immediately surrendered. No new points were added, and the task was marked as failed.

### Reproduction steps

1. Launch multiplayer campaign.
2. Complete the first two clown quests.
3. Start the third one.
4. Observe.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This could potentially be related to https://github.com/Regalis11/Barotrauma/issues/11493, we need to give it a test and see if that fix resolves this issue as well.

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.
