### ISSUE TITLE
One issue about plants

### ISSUE THREAD

**Issue by Raven-233486** [Regalis11/Barotrauma#11801]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The water needs of plants will be filled once I finish my turn (after entering another map), so I can never water my plants if I finish my turn fast enough.
I don't know if it is designed to be that.

### Reproduction steps

1. have a plant, whose water need is low
2. go to another map
3. you plant's water need become full

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not find a way to reproduce the issue. The need for water does not seem to change between rounds: 

https://user-images.githubusercontent.com/14351070/231379480-eb5d276d-bf24-474e-857e-41ad2d06cd34.mp4

I tested in both single player and multiplayer. I wonder if the issue happens with some specific type of plant or when the plant is in some specific state at the end of the round?

**Comment by TerminatorTM** [comment]
I too noticed this behaviors recently at multiplayer (not sure about singleplayer)
To replicate this issue: 
1) Plant anything and wait for 20-30 minutes.
2) Try to sprinkle this plant to notice it's need for water have some level (not fully watered), but **do not fill** this need completely.
3) Dock to station or start a mission (if already at station).
4) Try to sprinkle plant again and you will see it's water level already at full (but it was NOT just before map change).

**Comment by Regalis11** [comment]
Oh, I think I misunderstood the issue then. I thought "water need is low" meant the bar is not full (the bar indicates how watered the plant is, not how much water it needs). I'll give it another test!

**Comment by Raven-233486** [comment]
Thank you!

**Comment by Jasontti** [comment]
Tested. Plants stay as water as they were between rounds. Closing.
