### ISSUE TITLE
containedidentifier progress bar issue

### ISSUE THREAD

**Issue by KH1973** [Regalis11/Barotrauma#11809]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

so im writing a mod for guns. wrote a mag with 2 slots and add a bullet progress bar at the end. while i put the mag into the gun, the progress bar for the gun only have two state - full for the mag is in and empty for nothing inside. I talked to a modder in the official discord and it thinks this might be a bug. so far i tried every possible code related to identifier. here is a link of the screenshot about the issue. (https://discord.com/channels/103209684680323072/426913209602146315/1095828126208098435)

and here's the xml code about the itemcontainer entity:
`<ItemContainer capacity="1" maxstacksize="1" hideitems="false" itempos="5,-30" ShowTotalStackCapacityInContainedStateIndicator="true" containedstateindicatorstyle="bullet"  ContainedStateIndicatorSlot="0" containedspritedepth="0.56">`

### Reproduction steps

1.code a gun
2.code a mag with 2 slot (or more)
3.add containeridentifier to both of them
4.drag mag to gun

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! 

It does seem that this is a bug (or maybe rather a limitation): there doesn't seem to be a way to display the "contained state indicator" of the magazine on the weapon, except in the case where the indicator shows the condition of the item (like on vanilla SMG magazines).

Fixed the issue in https://github.com/Regalis11/Barotrauma-development/commit/2ef96683ecf86364debbc57da2ad73226083f610 (commit in our private repository)

**Comment by Jasontti** [comment]
Tested with modded smg and vanilla weapons/tools.
No issues found.
