### ISSUE TITLE
Remora airlock cannot drain water

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11806]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Remora airlock has no pump at the bottom and cannot drain water

![image](https://user-images.githubusercontent.com/73229309/231527805-b6047243-ff94-404d-9927-258e24a38b02.png)

![image](https://user-images.githubusercontent.com/73229309/231527656-f19e7175-a9c5-4cd8-b53a-3e37251c22ff.png)

### Version

v1.0.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1704886f42db13d5d7d4a067ea33da6493c7d26a

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4121/commits/fa18069b67c79c44b85045a834a4ac4d42b9285d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
