### ISSUE TITLE
Some special characters cannot be displayed after switching languages

### ISSUE THREAD

**Issue by Labrador52** [Regalis11/Barotrauma#11805]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My game is in Simplified Chinese. After I made a UI display with some special characters, I wanted to allow English and Russian players to use this UI display, so I switched to English and Russian mode. But after switching, I found that all special characters cannot be displayed in English and Russian, which directly caused the UI display I made to be used only in Simplified Chinese.
The following are the display pictures in different language environments (only the game language has been switched, without any other modifications)

When the game language is switched to Simplified Chinese:
![D2F3XHE HW1F3%I{`DZA@DE](https://user-images.githubusercontent.com/60187621/231509123-9bc0776b-3bf2-4fbb-8600-b07573c8740a.png)

When the game language is switched to English:
![$3T}W_H9}F~V5TVQSKW_ CN](https://user-images.githubusercontent.com/60187621/231509153-cf888b5a-723a-4ddc-bee0-8bb0eb43a35b.png)

### Reproduction steps

1. Enter the editor
2. Create a Label
3. Enter the character "▄"
4. Other special characters cannot be displayed, including other squares and triangles

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Labrador52** [comment]
By the way, in Chinese, some other special characters I want to input are not displayed

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/85c517c17661008f82cf36787442965f436b9c65 (commit in our private repository)

**Comment by Labrador52** [comment]
I would like to understand the reason for this problem, I am also developing my own game now, hoping to learn how to avoid similar problems by the way. Thanks!

**Comment by Regalis11** [comment]
@Labrador52 In our case the issue was that we use different fonts depending on the language, and these symbols weren't present in the fonts used when playing in English. We had some logic in place for making the game automatically switch to the Chinese font if a text contains Chinese symbols, but these block symbols weren't considered "Chinese symbols".

**Comment by Labrador52** [comment]
@Regalis11 I see, thank you! I really didn't expect fonts to cause such bugs before.

**Comment by Jasontti** [comment]
Tested. Special characters are displayed when no translation is found. Closing
![CJK test 2](https://github.com/Regalis11/Barotrauma/assets/8488224/8f1400ca-ff89-4a49-91f7-94df40c2f0f0)
