### ISSUE TITLE
Even if Player Doesn't Select A Monster/Artifact Mission he Can Still Complete Them- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1180]
I believe monsters should not show up only if player selects to hunt them same thing comes with artifacts. I'm talking here about campaign.

**Comment by Regalis11** [comment]
Then what would be the point of selecting the missions in the first place?

**Comment by rico6822** [comment]
> Then what would be the point of selecting the missions in the first place?

We could make it possible for the player to accept several cargo missions or none. If cargo gets damaged player will lose credits. If player has none it's game over screen.

**Comment by Regalis11** [comment]
In the case of the cargo missions it makes sense, but what about monster/artifact missions? If the monster/artifact spawns in the level in any case, what difference does it make if you accept the mission or not?

**Comment by Regalis11** [comment]
Then why would you ever _not_ accept them?

**Comment by rico6822** [comment]
> Then why would you ever _not_ accept them?

It's not for me but for people who believe they can do only 1 thing at once so they don't spam labels to won't get confused.

**Comment by Regalis11** [comment]
I'd argue that most people would find the extra label warning them about a monster or pinpointing the position of an artifact so beneficial that the slightly more crowded sonar display wouldn't matter much. And the end result would be that you should always select the monster/artifact missions before starting a round - and in that case, why have those checkboxes in the menu in the first place?

**Comment by rico6822** [comment]
> I'd argue that most people would find the extra label warning them about a monster or pinpointing the position of an artifact so beneficial that the slightly more crowded sonar display wouldn't matter much. And the end result would be that you should always select the monster/artifact missions before starting a round - and in that case, why have those checkboxes in the menu in the first place?

Actually I have a better idea. The player can do all missions at once if he wants to.

**Comment by Regalis11** [comment]
That's actually something we already have on our todo list. :)
