### ISSUE TITLE
Humpback issues

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11804]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

- [x] Overlapping hulls near armory
![image](https://user-images.githubusercontent.com/73229309/231492532-23ac37c0-890b-445b-b148-f8d5b7be4abe.png)

- [ ] Airlock can't be drained
The airlock is separated into 2 parts for no particular reason, getting back on the sub leaves the room on the right flooded unless you rewire the whole thing to keep the middle door opened at all times. 
_Move the pump on the right and get rid of the intermediary room_
![image](https://user-images.githubusercontent.com/73229309/231493287-23f01762-5a59-4790-980a-dfc02cc6cd59.png)

- [ ] Clown "room" messes with NBL, can't be drained
If you keep the door open, the right ballast can't adjust the proper water level. If you close the door after water gets in, you can't drain it. It makes the submarine naturally sink 
_Get rid of it or move the clown space left of the battery room?_
![image](https://user-images.githubusercontent.com/73229309/231495411-fae9d757-0de7-4385-a481-fc145fe3a41a.png)

- [x] Clown hull goes outside the sub
![image](https://user-images.githubusercontent.com/73229309/231496012-9cd93e3b-7b1e-4ce4-9a8b-aac8d079d48d.png)

### Version

v1.0.9.0

**Comment by Regalis11** [comment]
Thank you for the report!

> If you keep the door open, the right ballast can't adjust the proper water level. If you close the door after water gets in, you can't drain it. It makes the submarine naturally sink

I don't quite see the issue here. If you leave the door open, you can make the sub descend faster. If you don't want to use the room, you can pump the water out.

>The airlock is separated into 2 parts for no particular reason, getting back on the sub leaves the room on the right flooded unless you rewire the whole thing to keep the middle door opened at all times.

You're supposed to wait for the room to drain before leaving the "intermediary room".

**Comment by Regalis11** [comment]
Fixed the rest of the issues in https://github.com/Regalis11/Barotrauma-development/commit/6bcafb5414f616e9f79d3735e703f3a0cf437b82

**Comment by ubertpendragon** [comment]
> > If you keep the door open, the right ballast can't adjust the proper water level. If you close the door after water gets in, you can't drain it. It makes the submarine naturally sink
> 
> I don't quite see the issue here. If you leave the door open, you can make the sub descend faster. If you don't want to use the room, you can pump the water out.

Having some kind of extra ballast system is fine but since clown room can't pump out you have to pull the steering all the way to drain it fully and then close the door, repeat every time the door is open or a breach occurs.

> > The airlock is separated into 2 parts for no particular reason, getting back on the sub leaves the room on the right flooded unless you rewire the whole thing to keep the middle door opened at all times.
> 
> You're supposed to wait for the room to drain before leaving the "intermediary room".

What usually happens is:

1. Diver comes back to the sub
2. Presses the button that opens the middle door (but doesnt close the outer hatch)
3. Immediately presses the button that opens the inner door, with all the water pouring inside
4. Captain yells that the hatch is still open and full of water 
5. Do the whole thing in reverse to close the airlock while taking in more water

The Berilia has the same airlock problem where divers will casually forget to "properly" close the airlock not only when leaving but also entering and it'll always be flooded at some point
![image](https://user-images.githubusercontent.com/73229309/231525040-c7b7094e-bc48-45a7-adad-3b85045744d6.png)
![image](https://user-images.githubusercontent.com/73229309/231525414-578cee5b-816f-4d3b-973f-08674ac5e1a3.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
