### ISSUE TITLE
 flak shell explode at loader(when enemy near loader)( ̶w̶h̶e̶n̶ ̶l̶o̶w̶ ̶o̶n̶ ̶p̶o̶w̶e̶r̶)

### ISSUE THREAD

**Issue by war3scv** [Regalis11/Barotrauma#11813]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.
(my eye, it betrayed me agian...)
### What happened?

mostly happen when power just reach the need for flakgun to fire.
it noticeably happen more to the flakgun which have more than one loader link on.(I accidentally give a flakgun two loader and that's the one kill most the bots in campaign)
it actually occur less when I use mod(performance fix) I guess is because it reduce updates?
from what I ask around, it been here since that update which introduce the flakgun.

[2023-04-14 04-23-35.zip](https://github.com/Regalis11/Barotrauma/files/11226308/2023-04-14.04-23-35.zip)
too,,big, 15mb is too big have to cut it.... sad, test done in full vanilla well "mechanically" full vanilla environment

https://user-images.githubusercontent.com/95470279/231880061-2bdc3b2b-c1dc-4b98-8fa1-6b181d46203e.mp4

### Reproduction steps

have a bot shot a flak gun, til power drop just below the threshold the flak gun need to fire.

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Probably an explosive sub-projectile that spawned inside the sub

**Comment by war3scv** [comment]
just notice I check using mods bar, I thought it was not using mods bar... woe with me.

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not find a way to reproduce this. Tested by linking two loaders to the same flak cannon and firing it with various levels of power.

**Comment by war3scv** [comment]
> Thank you for the report!
> 
> I unfortunately could not find a way to reproduce this. Tested by linking two loaders to the same flak cannon and firing it with various levels of power.

regalis noticed me blessed:)
I was wrong it nothing to do with power, it happen because when flak gun fire there enemies near the loader, I just ask someone more experience on this, he posted a video about it,

https://user-images.githubusercontent.com/95470279/233690120-5239893d-a063-4a6c-8833-6b1e82a5a89d.mp4

**Comment by war3scv** [comment]
I can find a delete line...that's best I can do...

**Comment by ubertpendragon** [comment]
I think what happens is it spawns a flak bolt in the ammo box, and the motiondetector is triggered if an enemy is next to the loader

**Comment by Regalis11** [comment]
@ubertpendragon Yep, that seemed to be it, thanks for the debugging help! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0b23e5719d8fc2750764f12d57d77717fa9ac4f7

**Comment by Rokvach** [comment]
Tested by @NilanthAnimosus working correctly, closing.
