### ISSUE TITLE
Orca - "Steering" power consumption is higher than every other ships

### ISSUE THREAD

**Issue by chappuir** [Regalis11/Barotrauma#11810]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I noticed that the Orca has a "Steering" power consumption of 100kW, despite every other submarines of the game having a Sterring power consumption of 10kW.

This looks like a typo and it feels odd that this is the only submarine that has a different value. If this value was intentional and is part of the ship balancing, then my apologies for this bug report that is not a bug.

### Reproduction steps

1. Go into the submarine editor
2. Open the "Orca" file
3. Select the "navigation terminal" of the ship
4. Scroll down to the "Steering" section
5. The "Power consumption" parameter is set to "100.0", whereas every other ships is has it set to "10.0"

![image](https://user-images.githubusercontent.com/40195081/231835774-64c677df-71c0-47a0-8394-2522213be75f.png)

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
Is this a problem? Does the Orca have a too stable power grid that needs to be nerfed? Constant loads increase stability while dynamic loads lead to power issues. This is more like a feature than a bug.

**Comment by Regalis11** [comment]
> Is this a problem? Does the Orca have a too stable power grid that needs to be nerfed? Constant loads increase stability while dynamic loads lead to power issues. This is more like a feature than a bug.

Agreed, closing.
