### ISSUE TITLE
Progressive Stun visual effects abruptly reset when affliction passes 9 strength

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11811]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the affliction passes from the 0-9 range to the 9-99 range the visual effects reset due to both of the ranges having the same screen effect values:

https://user-images.githubusercontent.com/115734437/231856506-f322a838-c8d8-4ede-b452-f03f13eca277.mp4

```
<Effect minstrength="0" maxstrength="9"
  minscreendistort="0.0"
  maxscreendistort="0.6"
  minscreenblur="0"
  maxscreenblur="1.0"
  strengthchange="2"
  minradialdistort="0"
  maxradialdistort="0.2"
  minspeedmultiplier="1.0"
  maxspeedmultiplier="0.3">
</Effect>
<Effect minstrength="9" maxstrength="99"
  minscreendistort="0.0"
  maxscreendistort="0.6"
  minscreenblur="0"
  maxscreenblur="1.0"
  strengthchange="18"
  minradialdistort="0"
  maxradialdistort="0.2"
  minspeedmultiplier="1.0"
  maxspeedmultiplier="0.3">
</Effect>
```

### Reproduction steps

1. `giveaffliction ProgressiveStun 1` or get shot by stun gun dart
2. Observe visual effects

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested. Works and closed.
