### ISSUE TITLE
Bots freeze when wearing an InnerClothes-slot diving suit.

### ISSUE THREAD

**Issue by iridescent-lightning** [Regalis11/Barotrauma#11815]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If mod a diving suit that can be worn in the InnerClothes slot, bots will freeze when wearing them, either when tried to follow the character outside the hull or have been in the water (hull flooded). Bots will also not be able to put on diving suits when ordered to follow the player, despite the fact that the player has equipped a diving suit.

### Reproduction steps

1. Change divingsuit <Wearable slots="InnerClothes";
2. Go to the SubEditor;
3.1 Go outside the hull and order a bot to follow. Bot will put on a suit and freeze there.
3.2 Or put on a suit and order a bot to follow. Bot will follow but without putting a suit on.
3.3 Or Open the door let the hull flooded. Bots will put on suits but will freeze there right after the equipment of the suits.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None.
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ccba5eefddbf8fc8211b4d0449f5cb576de25df (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
Bots will use InnerClothes diving suits when needed and put on normal clothes if they are present in their inventory.
Even double wearing Outer and Inner diving suits is not a problem.
Closing ticket.
