### ISSUE TITLE
[unstable] Something's wrong with "OnContaining" type Status Effect

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11822]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I created a mod that override the helmet to allow player to attach health scanner or thermal goggles to it to enable the corresponding effect.
It somehow can cause oxygen generator to fill oxygen tanks extremely slow.
After some testing, I find it to be specific to unstable.
[Helmet Mod.zip](https://github.com/Regalis11/Barotrauma/files/11234979/Helmet.Mod.zip)

### Reproduction steps

0. enable the mod I uploaded above
1. get an empty oxygen tank, a ballastic helmet and health scanner/thermal goggles
2. insert the empty oxygen tank into an oxygen generator or oxygen shelf that is powered
3. insert the health scanner/thermal goggles into the helmet
4. observe the oxygen refilling rate being extremely slow

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
The only thing these items have in common is that they all have an `<ItemContainer />` and `StatusEffect` of which type is `OnContaining`.
I suspect this type of status effect is changed for optimization purpose, but it somehow is interfering amoung different items.

**Comment by Regalis11** [comment]
Seems to be caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/11561

**Comment by Regalis11** [comment]
Tested, seems to be working now
