### ISSUE TITLE
Alien_Storage1L has visible wires

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11824]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In Alien_Storage1L the wires to the Alien Terminals are visible and connected to the doors, not hidden unlike other wires.
![image](https://user-images.githubusercontent.com/104232152/232158050-9363e04e-fa02-4c0d-abe6-442e52948e09.png)

### Reproduction steps

1.Have a look at the wiring in Alien_Storage1L

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I don't see why this is an issue

**Comment by Rehexr** [comment]
Eh, considering the wiring one every other alien module is hidden, i just found it to be a wierd inconsistency, vut fair enough
