### ISSUE TITLE
Clear ruin/Artifact Recovery mission missing payout in starting round description

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11829]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When we as the wheatley gaming crew picked Clear Ruin and Artifact Recovery neither of them had pricing in their description after starting a round, though they do when selecting them from the map menu. 
![image](https://user-images.githubusercontent.com/104232152/232160883-8a371ada-53b1-4914-83dc-f16d7a5555e0.png)
![image](https://user-images.githubusercontent.com/104232152/232160898-8e0ea289-6a63-4000-96b9-6d94aa3f2d1f.png)

### Reproduction steps

1.Recieve one or both of these missions
2.Start a round with them
3.Notice the mid-round description is missing the payout 

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
