### ISSUE TITLE
Periscope sight range Upgrade is bigger than should

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11825]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The periscope range upgrade gives you +4% vision range per level, up to +16%
![image](https://user-images.githubusercontent.com/73229309/232156959-4fa32e86-dad7-4c43-83a0-14fb0727c818.png)

In reality it's actually closer to +50%:

![image](https://user-images.githubusercontent.com/73229309/232157492-0bd61bf5-554c-429c-b4b6-30b8e64d7e1f.png)

I measured and resized using photoshop on a 1920x1080 monitor to compare the difference.
Not sure how the formula works but it did feel much bigger than it says. 

+50% increase isnt a problem itself but it lets you see past the edges of the map (like the abyss floor)

### Version

v1.0.9.0

**Comment by Regalis11** [comment]
Not a bug, the range is intentionally this long.
