### ISSUE TITLE
Leaving after voting causes a console error 

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11827]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/104232152/232160222-c4fa77c6-629f-4dc3-a420-72c62f0c478f.png)
After a player leaving after voting on a ready check, it caused a console error once the ready check concluded.

### Reproduction steps

1.Start a ready check
2.Vote and Leave
3.Anyone else on the server will now get an error after the vote

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested, no issues found.
