### ISSUE TITLE
[Unstable] Psychosis artifact does not need a battery cell while stored in a transport case

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11838]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

With the changes to transport cases, every artifact type requires a battery cell to disable its effects, with the exception of the psychosis artifact.
The effects of the Psychosis Artifact are absolutely trivial to combat. Simply dropping it on the ground completely stops it from affecting crew members, and when it is placed inside a transport case, it doesn't even require a battery.

The artifact should require a battery when placed in a transport case, and probably shouldn't be trivialised by just dropping it on the floor.

### Reproduction steps

1. place a psychosis artifact inside a transport case without a battery
2. observe that despite the transport case lacking a battery, the psychosis artifact does not affect the holder

### Bug prevalence

Just once

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/305518eada22332283eb80717cdba20a17e3a613
