### ISSUE TITLE
Ready check counts are inconsistent 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11836]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Could be related to the issues found in #10929.

Ready check counts might be client side, or there may be a communication error between the client and the server. Ready checks that are not started by the player have incredibly weird results ranging from not showing the votes of other players, to not showing the votes of players who have already voted. 

These issues do not persist if the ready check is started by the player.

I am the host of the server being used. It's a P2P server established using standard Steam connection. Players were able to join using the server browser and direct join via steam. 

![image](https://user-images.githubusercontent.com/105495756/232173181-78939453-30d3-43e5-91fe-49bce99855cd.png)
_Figure 1. Ready check stating 12/13 players ready, but the ready check box only showing a single vote._

### Reproduction steps

1. Have another player start a ready check (more players in the lobby are preferable)
2. Wait for the ready check to make some progress, around 50% of the total time
3. Vote in the ready check
4. Observe how the votes are not shown to you

### Bug prevalence

Happens regularly

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested, no issues found.
