### ISSUE TITLE
[Unstable] Disposable Diving Suits constantly make the leaking oxygen sound 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11835]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a player wears the Disposable Diving Suit, it will constantly make the sound of leaking oxygen. In theory this makes sense as the suit is constantly decaying until it can no longer be used. In practice this is incredibly irritating and gives the impression the suit isn't safe to use, despite this not being the case.

### Reproduction steps

1. Spawn a Disposable Diving Suit
2. Equip Disposable Diving Suit
3. Listen to the audio 

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to be caused by the same underlying issue as https://github.com/regalis11/barotrauma/issues/11561
