### ISSUE TITLE
Fabricator search function has no text limit

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11839]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The fabricator search function has no text limit which allows you to enter text outside of the fabricator UI.

![image](https://user-images.githubusercontent.com/105495756/232174192-0b147c60-5b4c-450c-ad09-8d86f9718ee9.png)

### Reproduction steps

1. Open the fabricator UI
2. Enter the text field
3. Hold down v
4. Observe the text leave the UI

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/4eda226eedcd500f73c95357e358d998c75ef266

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
