### ISSUE TITLE
[Unstable] Guitar doesn't play audio 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11837]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The guitar won't play any sound for many players in a multiplayer setting. However, this issue seems to change between rounds and depending on the player. Some rounds has the guitar playing audio as normal, other rounds has it being non-functional. Some players will be able to play the guitar whilst others won't. The conditions for this issue seem to be incredibly inconsistent.

Interestingly, the clown guitar track seems to play without issue.

I have yet to discern a cause or theorised cause for this bug. 

### Reproduction steps

1. Grab a guitar
2. Try to play it
3. Observe how it doesn't play audio 

### Bug prevalence

Happens regularly

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd4bf841cee986faade50edd439aa8592ac9e36b

**Comment by Regalis11** [comment]
Tested, seems to be working now
