### ISSUE TITLE
A.I failing to store items in like marked containers.

### ISSUE THREAD

**Issue by DarklyChimera** [Regalis11/Barotrauma#11849]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The A.I are failing to store like objects in predetermined locations when they have such locations already existing, instead throwing items into non specific locations all over the ship at random, this excludes the medical locker due to it being the only unique locker registry in the game.

### Reproduction steps

Set A.I to clean up, buy some items or store them in a similar container, the A.I will just run items to the potential nearest non related storage location.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TerminatorTM** [comment]
Do containers have appropriate tags for items need storing?

**Comment by DarklyChimera** [comment]
Cant tag the containers but if it has like items the A.I used to store them
appropriately

**Comment by Regalis11** [comment]
Thank you for the report! I think we're going to need more information on the issue to be able to diagnose it. Which submarine does this happen in? If it's a custom one, have the cabinets been properly tagged? Can you give some specific examples of what kind of items get contained in what type of containers?

**Comment by DarklyChimera** [comment]
The issues have happened in the orca2 and the dugong, ive ended up with non
tools in a cabinet set primarily for tools in both as well as finding just
weapons stored in wall emergency lockers, which usually have repair tools
and oxygen masks in them.

**Comment by Regalis11** [comment]
Thanks for the clarification! Those examples sound like they might not actually be bugs: there aren't any cabinets specifically for tools, and it could be the weapons were put in the supplies cabinets by a bot who doesn't have access to the armory (which is the only place with cabinets specifically for weapons in Orca 2 and Dugong).

**Comment by DarklyChimera** [comment]
Armories opened to anyone with an i.d card, which is why assistants can
access the weapons locker but not the secure locker, that said, wouldn't
the locker being filled with tools determine it being designated for tools?

**Comment by itchyOwl** [comment]
> wouldn't the locker being filled with tools determine it being designated for tools

The system uses predefined tags that can be defined in the subeditor. And the tag has to match with the tag given in the item definition (xml). Unfortunately, there's currently no way to edit the tags outside of the sub editor.

These two lockers in Orca2 are tagged as "engcab", which means they are used primarily for tools:

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/827e4272-cc0c-4d27-88d0-6ceb085e7538)

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/8d42769a-6202-4b46-af75-1b325118bc29)

And this is "armcab", which is the primary or secondary container for weapons:
![image](https://github.com/Regalis11/Barotrauma/assets/5370738/d9ac1216-cfa3-49e9-83d7-294f624b612d)

The bots should only place the items in other places if they can't find a better place for them. Just tested it and the bots place the items in the lockers correctly. So maybe the primary and secondary containers were full? Or maybe you didn't know which one is the supposed locked for the tools/weapons? It's been on the talks that we should allow the player to do tagging in game, but so far the feature is unimplemented.

Let's keep the ticket open for a while still and close it if there's no further info about what exactly is the issue.

**Comment by DarklyChimera** [comment]
Ok, thanks for the clarification.

**Comment by Regalis11** [comment]
No known steps to repro, closing
