### ISSUE TITLE
[Unstable]NPCs can get rid of player's draggin even if they are handcuffed

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11847]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I tried to catch hostile npcs in abandoned outposts for extra reward with the security talent.
I successfully stunned and handcuffed a npc and took his items. But they will get rid of player's dragging when the player holds them for a period of time.

### Reproduction steps

1. goto abandoned outpost
2. capture a npc with stunning weapon and handcuff them
3. hold their hands for a period of time
4. observe they get rid of player's dragging

### Bug prevalence

Happens every time I play

### Version

v1.1.4.0 Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by TerminatorTM** [comment]
Maybe related to fix from this ticket
[On outpost there is a "feature"](https://github.com/Regalis11/Barotrauma/issues/11749)

**Comment by BiffW** [comment]
Expected behavior: npcs should be unable to break free from player's dragging when they are handcuffed.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a9c5e19b35fe6a3f3a519156d0ee18c84d6aac48
