### ISSUE TITLE
Ai doing unassigned work

### ISSUE THREAD

**Issue by DarklyChimera** [Regalis11/Barotrauma#11848]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The A.i are constantly doing unassigned work or over healing minuscule damage themselves when they aren't assigned to it.

### Reproduction steps

It happens in multiplayer and non multiplayer games, more so in multiplayer, just having an A.I set to not do their class job appropriately and they will move to do it on their own aimlessly with the task removed.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TerminatorTM** [comment]
It is normal for bots. Еngineer will repair badly damaged circuits from time to time, mechanic will do the same for mechanical stuff. Medic will heal crewmembers with <50% hp and so on. Orders just tell them to do something with high priority.

**Comment by DarklyChimera** [comment]
Happens when my crew and I are at minor damage from falling down stairs.

**Comment by Regalis11** [comment]
Yep, it's intentional that the bots do tasks on their own (unless ordered to do something specific). We also have an existing ticket about the medic bots' overeagerness to treat minor injuries: https://github.com/Regalis11/Barotrauma/issues/11477
