### ISSUE TITLE
Zealot Robes + Diving Suits = Ghost Players

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11840]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wearing Zealot Robes and then equipping a diving suit will cause the player's face to disappear.

![image](https://user-images.githubusercontent.com/105495756/232174344-aa4554cd-6f23-4135-aca4-810911d732b2.png)

### Reproduction steps

1. Wear Zealot Robes
2. Wear a diving suit (any with a transparent visor will work)
3. Notice your lack of a face

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
is it possible to let the diving suit force show limbs even if the inner clothes is hiding them?

**Comment by Regalis11** [comment]
> is it possible to let the diving suit force show limbs even if the inner clothes is hiding them?

It isn't, but that's not required in this case - the limb should still be hidden, but the hood should be showing through the diving helmet's visor.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa8639a737aec278fef9d0bdf542f775766bdf0f
