### ISSUE TITLE
Players with Husk Symbiosis who die become Husks

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11842]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar issue to #10999. 

If a player has Husk Symbiosis and disconnects from the server, they will become a Husk once brain death sets in. This is problematic as death by other means does not causes players to become a Husk.

### Reproduction steps

1. Have Husk Symbiosis
2. Disconnect from the server
3. Have someone else observe your transformation into a Husk once brain death sets in

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to happen regardless of how/why the character dies. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54c97ea7a17b422957c2e9500174f4fc78823cb6

**Comment by Jasontti** [comment]
Tested.
Characters with husk symbiosis stay dead in singleplayer and server, Player controlled or not.
Closing ticket.
