### ISSUE TITLE
Bots jump off the balcony in Colony outpost repeatedly

### ISSUE THREAD

**Issue by DamnedTaube** [Regalis11/Barotrauma#11844]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In the Colony outpost, in the layout where Merchant is in a room with an empty platform above it, my bots would just endlessly climb up to that platform and then jump off, hurting themselves, endlessly.
![image](https://user-images.githubusercontent.com/25986192/232187247-67106be1-4d8c-4637-9357-deb3098af726.png)

Bot would climb up to the platform, walk off it and get blunt force trauma and then climb back up to it and repeat.

Not sure if this has happened every time in Colony Outpost, I've noticed it only once so far.

### Reproduction steps

1. Enter colony outpost where the Merchants room has an open platform above it (one where you can just walk off it) with a crew of bots
2. Go hang around the Merchant and observe the bots "entertain" themselves

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/761e60f0d6bb5f2c98c6613e0ed64c36e35f6db7 (commit in our private repo).

> Fixed bots falling off the ledge in DockingModule_02_Colony (again). This seems to have been fixed before too (https://github.com/Regalis11/Barotrauma/issues/9896), but I'd guess the changes got overwritten when the faction-specific outposts were merged.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
