### ISSUE TITLE
[Unstable] Consumable items, such as skill books, are consumed instantly

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11841]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Any item which can be consumed, such as skill books or Velonaceps Calyx Eggs, will be consumed immediately. If the item exists in a stack, the stack will be immediately consumed as well. This allows players to accidentally use an entire stack of skill books by pressing right click for any period of time.

### Reproduction steps

1. Grab a skill book
2. Right click
3. Observe how you immediately read the book
4. Grab Velonaceps Calyx Eggs
5. Right click
6. Observe how you immediately eat the eggs

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to be caused by the same underlying issue as https://github.com/Regalis11/Barotrauma/issues/11561
