### ISSUE TITLE
Ai don't look through storage containers in lockers

### ISSUE THREAD

**Issue by BlueDovah** [Regalis11/Barotrauma#11850]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If items are placed in storage containers, the ai don't register the item's existance

### Reproduction steps

1. place item in storage container (ex. Medical supplies)
2. set ai to use item (ex. Treat wounds)
3. The ai cant find the item.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TerminatorTM** [comment]
Do containers have appropriate tags for stored items?

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not find a way to reproduce this. I'd suspect the storage containers aren't the issue, but that something else is preventing the bots from being able to find the items.

https://user-images.githubusercontent.com/14351070/232246540-89f36cbc-3534-4b07-85fc-3e37ab1366ad.mp4

**Comment by Regalis11** [comment]
No known steps to repro, closing
