### ISSUE TITLE
Fabricator text implies that failing to meet skill requirement means it is impossible to fabricate

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#11856]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the fabricator, the text "Insufficient skills to fabricate" directly implies that without meeting the skill requirement for an item, it is impossible to create, which is untrue.

![image](https://user-images.githubusercontent.com/37850646/232299421-d3836495-1eae-49b3-854f-808027b5a38c.png)

In general, newer players are given very little indication that being under the skill requirement still allows fabricating items. The "Skills required to calibrate" doesn't help much, since "calibration" has no meaning in this context.
Many players in the discord ask how to grind skills so they can craft an item with high requirements, only to be surprised when told that they can craft it without meeting the requirements. This implies to me that it is not conveyed clearly enough.

### Reproduction steps

1. Have low skills and look at the fabricator
2. See the list of items that you have "insufficient skills to fabricate"

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/58feed8f2c80205bb559c371f41bd2652f64844e

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
