### ISSUE TITLE
Can't Launch Steam Version of Barotrauma- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1186]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Steam told me there is a missing launcher of the game in the steam folder of barotrauma in "commons" of "SteamApps". The folder is empty.

**Additional Information**

I received legally steam key from Dynamoon for I am one of the github contributors.

**Comment by Regalis11** [comment]
If SteamApps/common is empty, it could be that you don't have any games installed on Steam. Were you previously able to play the Steam version? Did this happen after doing something specific (updating the game, switching to another computer, reinstalling Steam...?)

**Comment by rico6822** [comment]
> If SteamApps/common is empty, it would seem to imply that you haven't installed the game or have changed the install location to somewhere else. Were you previously able to play the Steam version? Did this happen after doing something specific (updating the game, switching to another computer, reinstalling Steam...?)

I refused to create shortcuts on desktop and in start menu.

**Comment by Regalis11** [comment]
Were you previously able to play the Steam version? Did this happen after doing something specific (updating the game, switching to another computer, reinstalling Steam...?)

**Comment by rico6822** [comment]
> Were you previously able to play the Steam version? Did this happen after doing something specific (updating the game, switching to another computer, reinstalling Steam...?)

I have used the steam key 15 minutes before posting this issue.

I have refused to create shortcuts both in start menu and desktop.

**Comment by Regalis11** [comment]
What operating system are you trying to install the game on?

**Comment by rico6822** [comment]
> What operating system are you trying to install the game on?

Windows 7    32-bit

**Comment by Regalis11** [comment]
Ah, that's the problem. Unfortunately the Steam build is only available for 64-bit operating systems at the moment.

**Comment by rico6822** [comment]
> Ah, that's the problem. Unfortunately the Steam build is only available for 64-bit operating systems at the moment.

Will it support 32 bit?

**Comment by Regalis11** [comment]
Given that less than 2% of the players on Steam still use a 32-bit OS, I'm not sure if it's worth the effort to make a 32-bit version. But it's a possibility, I think I'll look into it in the following weeks.

**Comment by rico6822** [comment]
> Given that less than 2% of the players on Steam still use a 32-bit OS, I'm not sure if it's worth the effort to make a 32-bit version. But it's a possibility, I think I'll look into it in the following weeks.

Ok.
