### ISSUE TITLE
Oxygenite Tank has no recyle recipe

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11865]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Title says it all

### Reproduction steps

check fabricator and try to find recycle recipe for oxygenite tank

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
since its design is similar to incendium fuel can. it should have a recycle recipe too.
1 non-full oxygenite tank + 2 liquid oxygenite = 1 oxygenite tank

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/4dedf9d53c9b446d2b7a88944cb6bcde137aa131

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
