### ISSUE TITLE
`MatchOnEmpty` on `RequiredItem` does not take `TargetSlot` into account

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11861]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For a multi-slot item container:
<RequiredItem items="something" targetslot="0" matchonempty="true />

Actual behavior:
It is considered true only when the item container is empty.

Expected behavior:
It should be true as long as there's no item on slot 0 regardless of items on other slots.

### Reproduction steps

https://github.com/Regalis11/Barotrauma/blob/f223f774b9a818ad3762b9ced711d52be4c3b5ff/Barotrauma/BarotraumaShared/SharedSource/Items/RelatedItem.cs#L194

The related function is here.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
This does not affect any vanilla content. But it prevents modders from checking if a specific slot is empty.

**Comment by Jasontti** [comment]
Tested.
Made stun baton that has 2 slots and has:
```
      <StatusEffect type="Always" target="Contained" targetslot="0" >
        <RequiredItem items="mobilebattery" type="Contained" targetslot="0" matchonempty="true" />
        <Conditional condition="lte 50.0" />
        <Sound file="Content/Items/WarningBeep.ogg" range="500" loop="true"/>
      </StatusEffect>
```
Effect activates when battery in slot 0 is below 50% or slot is empty. Having item in slot 1 doesn't not affect this behaviour.

If i understood this correctly it works now. Closing ticket.
