### ISSUE TITLE
"Engineers are special" event doesn't have an npc to talk to

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11860]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When triggered, the event "Engineers are special" doesn't mark any npc for the conversation, making the event uncompleteable.
![image](https://user-images.githubusercontent.com/115734437/232438813-50ccb7e3-c4d7-4c34-a5d1-37a1157ab29d.png)

### Reproduction steps

1. In an outpost: `triggerevent Engineers_are_special`
2. Check outpost for npc with mission marker

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d83f61af751982773f64be943076bd784ec0819a

**Comment by Jasontti** [comment]
Tested.
Event triggers correctly, as long as there is living repairnpc in the outpost.
Closing ticket.
