### ISSUE TITLE
Lobby/rename bug - character customization triggers "Wait X seconds until you can rename again"

### ISSUE THREAD

**Issue by JeroonBosch** [Regalis11/Barotrauma#11864]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When in a multiplayer lobby, changing your character (appearance/class) also blocks you from renaming your character afterwards. Even when you don't touch your name at all, it will say "Wait X seconds until you can rename again"

### Reproduction steps

1. Join a multiplayer lobby
2. Change your character class and/or appearance
3. See how the chat gets spammed with warnings that you're not allowed to rename yourself yet, despite not renaming

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4152/commits/60644e7c50c8ad42d351b81314516841ce3d8496

**Comment by NilanthAnimosus** [comment]
Tested against Fix/name-change-cooldown commit https://github.com/Regalis11/Barotrauma-development/commit/31d343c2e6ec57e35b5969ddf0dc244a06390eb9

The fix works correctly but there is one caveat:

The client when failing to do a name change does not revert to the previous name (keeping the attempted name over the existing). If renaming to that same name (IE, Nilanth2 -> Nilanth3 fails, Nilanth3 -> Nilanth3 again) makes no attempt to tell the server as the client sees it as being the same name (despite they are actually a different name server-side, IE. Nilanth2).

However, any job change or appearance change will send that name over and fail to change anything during this cooldown, making it more of a problem if you fail a name change then attempt to change jobs or appearance.

The client will not revert job changes or appearance changes, but start the right as the wrong job if this is done and the message to change name cooldown ignored without further changes to name/job/appearance to correctly update it.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e26b9183126b18e44f821b76756960815641df12

**Comment by NilanthAnimosus** [comment]
Tested against Fix/name-change-cooldown commit https://github.com/Regalis11/Barotrauma-development/commit/39ab4eca1786dfcdcd73834820d3a8a9cf58112e, no issues found, ready to merge
