### ISSUE TITLE
Shuttles attached to beacons (and wrecks?) do not have any crush depth resistance

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11868]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you have a shuttle attached to a beacon, and possibly a wreck and outpost module, they will not have any crush depth resistance.

In the later biomes, those shuttles crush instantly, even detaching from their docking port

Example: [BeaconUBER01.zip](https://github.com/Regalis11/Barotrauma/files/11273339/BeaconUBER01.zip)
UBER03_bandit
![image](https://user-images.githubusercontent.com/73229309/233082980-b9cba1db-a674-4b69-8db6-d48d4e7a3a11.png)

![image](https://user-images.githubusercontent.com/73229309/233082428-1e2a5a22-513f-4b8d-8526-21da8f8744de.png)

![image](https://user-images.githubusercontent.com/73229309/233082401-61fdbe53-07aa-4381-9720-264ad169bef7.png)

The small pirate shuttle was sinking as soon as the level loaded
Save file:
[crates.zip](https://github.com/Regalis11/Barotrauma/files/11273355/crates.zip)

**Comment by ubertpendragon** [comment]
I'm not sure why but it also fails to start docked properly 

https://user-images.githubusercontent.com/73229309/233086384-41428738-ab38-4093-9045-d46b418bdf44.mp4

**Comment by giists** [comment]
Everything seems fixed, closing.
