### ISSUE TITLE
Crashreports after trying to continue company in multiplayer

### ISSUE THREAD

**Issue by AnatolyIV** [Regalis11/Barotrauma#11873]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

[crashreport (39).log](https://github.com/Regalis11/Barotrauma/files/11276995/crashreport.39.log)

### Reproduction steps

1. Join my friend's server.
2. Start loading into comapny
3. Ooops! Barotrauma just crashed!

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Help pls
```

**Comment by Regalis11** [comment]
Seems to be the same error as https://github.com/Regalis11/Barotrauma/issues/9947, closing as a duplicate
