### ISSUE TITLE
Being unable to place portable pump

### ISSUE THREAD

**Issue by Altysta** [Regalis11/Barotrauma#11872]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In a multiplayer session, while playing any other class than mechanic and having mechanic-bot who unlock "Let it Drain" talent.
You can produce a portable pump using bot talent, but afterward (after use of two precious demonite cluster) turns out only a player mechanic can place the pump. Any other class cannot place the pump and receive "Special training required to place this item" message.
There are also no command to place pump for bot.

Solutions (from best to worst):
a) unlock possibility to place pump if you can craft them using bot talent (while playing as different class)
b) adding command for bot to place pump. 
c) adding explicitly clear description of item that only player mechanic can place the pump. :( 

### Reproduction steps

1. Start mupliplayer campain and plaing any other class than mechanic
2. Having mechanic bot with  "Let it Drain" talent unlock.
3. Producing portable pump in fabricator.
4. Trying to place pump anywhere.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

We actually just recently implemented the 1st solution you suggested while addressing [a similar issue with the makeshift shelves](https://github.com/Regalis11/Barotrauma/issues/11767). The fix isn't publicly out yet, but is coming in the next patch. Sorry for the inconvenience!

**Comment by Altysta** [comment]
Just to be sure:
in new [post ](https://barotraumagame.com/announcements/post-launch-greetings-and-patch-v1-1/) you mention update of makeshift shelves but not portable pump. Are they surely will be corected as well? Maybe it worth to mention them as well?
