### ISSUE TITLE
[Unstable] Typhon Rework issues

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11883]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Typhon rework still has a few issues, some major some minor that I already fixed in the previous installement 
https://github.com/Regalis11/Barotrauma/issues/11783#issuecomment-1509305461
I cleaned up, copied and refreshed all the waypoints, but since this is using the previous version as a basis I still can't find what the mysterious _"Floating Fence"_ refers to

**Fixes:**
[TyphonReworkRework.zip](https://github.com/Regalis11/Barotrauma/files/11297301/TyphonReworkRework.zip)

Waypoints
![image](https://user-images.githubusercontent.com/73229309/233675551-ecba1c0d-4287-4006-ac05-423544e0b65c.png)

LOS (had to make some walls overlap to prevent this)
![image](https://user-images.githubusercontent.com/73229309/233668672-b077031b-b2ff-48c5-8615-b7aa717943c0.png)

Gap
![image](https://user-images.githubusercontent.com/73229309/233675974-b6189393-e724-4291-8fac-831eec03413e.png)

Invisible Platform
![image](https://user-images.githubusercontent.com/73229309/233675903-02942cb5-2140-4532-8bbf-c68767070154.png)

Hull offsets (a LOT of them are overlapping by 1 or 2 pixels)
![image](https://user-images.githubusercontent.com/73229309/233676027-848f34a1-425f-4475-8241-8903c528d28b.png)

Caps inexplicably using old size and not responding to reset to prefab
![image](https://user-images.githubusercontent.com/73229309/233676249-b87d60a9-3af1-4bbd-b940-dcdfd0b04e78.png)

Holes
![image](https://user-images.githubusercontent.com/73229309/233676571-afe14a82-e755-4b91-bd6c-466ac8d776ff.png)

### Version

Unstable (v1.0.10.0)

**Comment by BiffW** [comment]
The secured weapon room can be accessed from the bottom hatch by characters who are not security or captain. Is it intentional?

**Comment by ubertpendragon** [comment]
Yes but now I'm not so sure if it's a good idea or not to ID lock it. 

There's still some room for circuits to lock the bottom door

**Comment by BiffW** [comment]
>There's still some room for circuits to lock the bottom door if the captain wants to restrict acces

You can add 2 switches or buttons(1 inside and 1 outside) to toggle lock the arms room. Only security or captain can operate it. So that players can decide wether to restrict it or not.

**Comment by JeroonBosch** [comment]
![image](https://user-images.githubusercontent.com/8641689/234250922-f33abaa9-a88b-4758-93c5-5c85a9f1a9cd.png)
The bottom hatch buttons do not appear to do anything atm

**Comment by Regalis11** [comment]
Tested & merged
