### ISSUE TITLE
Event badvibrations3 doesn't occur and is repeatable

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11882]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The third part of the Bad Vibrations event chain `badvibrations3` (option to recruit the artifact victim after recovering the artifact in part 2) isn't listed in any event set and cannot occur during normal gameplay. Additionally, while the event seems to work fine when manually triggered, it doesn't check if the event was already completed which makes it possible to repeat the event multiple times.
Events such as At Wit's End and Heart of Gold (Artie Dolittle and the abandoned outpost drug dealer) check if they were already completed:
```
<!--"At Wit's End"-->
<ScriptedEvent identifier="atwitsend" commonness="70">
  <CheckDataAction identifier="atwitsend_complete" condition="eq true">
    <Success>
      <!--Don't repeat event-->
    </Success>
    <Failure>
```
```
<!--Heart of gold-->
<ScriptedEvent identifier="heartofgold" commonness="50">
  <CheckDataAction identifier="heartofgold_complete" condition="eq true">
    <Success>
      <!--Don't repeat-->
    </Success>
    <Failure>
```
Part 3 of Bad Vibrations only checks if the artifact was recovered:
```
<!--PART 3-->
<ScriptedEvent identifier="badvibrations3" commonness="0">
  <CheckDataAction identifier="badvibrations_artifactfound" condition="eq true">
    <Success>
```

### Reproduction steps

1. Complete `badvibrations2`
2. Manually trigger `badvibrations3` and complete it, then trigger it again

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d852935a2fd07b196da54ad6f4a8281d9ac43d25

**Comment by Jasontti** [comment]
Tested.
Did the event 2 times, first i got artifact spawn twice in same ruins, second time i had no issues, could not trigger badvibrations3 again.
Could not get artifact to spawn twice again, maybe not related to this issue.
Closing ticket for now.

![2023-08-08_09-00.png](https://images.zenhubusercontent.com/6463874172183936f90966a8/6fc2b57b-5c1f-4f8e-a02c-ae1362fbd92e).
