### ISSUE TITLE
Greater Than component inherit property description from Equals component

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11880]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![gt_desc](https://user-images.githubusercontent.com/99462070/233549586-117445d1-825d-4d74-9208-87bff7fab66f.jpg)
![eq_desc](https://user-images.githubusercontent.com/99462070/233549601-cbcad4d7-ede0-47f5-83f6-ec81dc6c3e6a.jpg)

### Reproduction steps

see their property description in the sub editor

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
Similar issue occurs on OR component and AND component. When you fix this, you should check other components' inheritance too.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f22bd78468554368e856a9bb1244bed4bff576ab. OR and AND seemed to be correct ("The signal sent when the condition is met").

**Comment by BiffW** [comment]
> OR and AND seemed to be correct ("The signal sent when the condition is met").
I'm sorry for not checking that by myself. Actually, someone is working on a Simplified Chinese localization overhaul. Because the official Chinese localization has too many mistakes. The inheritance prevents modders from making distinct description for OR and AND components.

**Comment by BiffW** [comment]
It might be inappropriate to discuss about localizations' issues here. 
Here's a discussion to allow the community modders to make patch for localizations by themselves.
https://github.com/Regalis11/Barotrauma/discussions/11851

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
