### ISSUE TITLE
[Unstable] No change is done to pressure stabilizer

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11886]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

`- Fixed pressure stabilizer only affecting the player for 100 seconds, instead of the intended 1000 seconds (16 mins).`
I compared file changes and find nothing related to pressure stabilizer is changed.
The change is done to `pressure resistance` which has nothing to do with pressure stabilizer.

### Reproduction steps

try to find changes to pressure stabilizer in your content repository

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.0.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I decided to reopen [the old ticket in which we intended to address this issue](https://github.com/regalis11/barotrauma/issues/11737). I'll close this one.
