### ISSUE TITLE
Doesstick="true" doesn't work on the SERVER side and is desync with client side.

### ISSUE THREAD

**Issue by iridescent-lightning** [Regalis11/Barotrauma#11888]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![20230422224246_1](https://user-images.githubusercontent.com/94741028/233791325-171b2bd6-9e88-4389-8c69-55ad9292d4b6.jpg)

*There are two grapples in this picture. One was already caught by the player and another one is falling and sticking in a loop.

When enable a projectile to stick to a level wall, this feature can only work in the single player mode. In multiplayer, the projectile will both stick to the wall and keep falling from the wall. When the projectile falls, it blinks to it's sticking point and fall again (it will take quite a while, maybe 20s, and it's better to use a bigger item for better observation). Until you catch the projectile using a character.

### Reproduction steps

1.  Set a projectile like this. "<Projectile characterusable="false" launchimpulse="10.0"  doesstick="true" stickpermanently="true"     The only thing matter is the doesstick. The rest is not relevant.
2. Start a multiplayer game. 
3. Shoot this projectile to a level wall. (Possibly a cliff)
4. Watch the item keeps falling and sticking.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

![20230422230106_1](https://user-images.githubusercontent.com/94741028/233792273-e1a8183c-bd3d-43cc-85f9-744c132c9ce5.jpg)

**Comment by iridescent-lightning** [comment]
This is the bug report.
![Uploading 20230422230106_1.jpg…]()

**Comment by itchyOwl** [comment]
Possibly related to #11726.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fe1902ade0c9d588978e5a7e77c4693576bbf605 (commit in our private repo)

**Comment by iridescent-lightning** [comment]
Thanks for the fix up.

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll keep it open until we've tested it internally and verified the fix is working properly. :)

**Comment by Jasontti** [comment]
Tested.
Spears don't stick to walls in MP or SP. Sometimes they go trough enemies.
Do they have need pass some armor check? I found that they will stick to unarmored humans better than ie. mudraptors.

Sometimes spears got really confused about their location. Included a video.


https://github.com/Regalis11/Barotrauma-development/assets/8488224/b4af79ad-6662-4fd9-bd4f-22d1b701b802

**Comment by Jasontti** [comment]
Tested again.
No issues found.
Closing
