### ISSUE TITLE
I work hard the mission for three hours and at the very end the game crashed. I'm sending a crash report. Also note: names of characters don't display at all, when I using AMD Eyefinity. It happens when I used 3 1920*1080 monitors to get a single 5760*1080 screen resolution.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11899]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

1. Game crashed
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/11311530/crashreport.11.log)

2. Characters names not displayed
![2023-04-24_14-26-29](https://user-images.githubusercontent.com/47295383/234029815-f3011b4d-c80d-4162-a3ce-5f8e0bf9170c.png)

### Reproduction steps

For the game crash I have no ideas why. I think you will find the reason in the attached crash report.
This happened when I was dragging an item from my character's inventory into the bot's backpack.

For names of characters don't display.
1. Buy 3 monitors 1920*1080 resolution each.
2. Buy AMD Radeon RX 580 8Gb videocard.
3. Attach all 3 monitors to videocard digital ports.
4. Install latest AND display drivers and use AMD Eyefinity to get a single 5760*1080 screen resolution.
5. Launch barotrauma the game.
6. You got it! The names of the characters don't display.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The crash seems to be the same as [this one](https://github.com/Regalis11/Barotrauma/issues/11626), caused by a handheld item finder or status monitor.

We've also got [an existing report about the issues on ultrawide resolutions](https://github.com/Regalis11/Barotrauma/issues/10679).

Sorry for the inconvenience!
