### ISSUE TITLE
Cannot select vanilla submarine with core package mod in multiplayer

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11892]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/99462070/233818810-f3972db4-6769-4c1e-a9bd-86af83370197.mp4

Related mod: Simplifed Chinese Localization Overhaul
https://steamcommunity.com/sharedfiles/filedetails/?id=2965506707
Description: This mod is created as a core package mod in order to override Simplifide Chinese Localizations to fix many incorrect translations.
Issue: When enabled this mod, in multiplayer lobby, player cannot select a vanilla sub even if they tap "yes" to the mismatch core package warning. The only way to select a vanilla sub is to hide all other submarines.

### Reproduction steps

1. Enable the related mod
2. Go to a multiplayer lobby
3. Try to select a vanilla sub

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/637c14b51e16fe4ba60499d263f48b629b7872b8

**Comment by giists** [comment]
No issues found, closing.
