### ISSUE TITLE
Rock with piezo crystals blocking the path

### ISSUE THREAD

**Issue by BGURGEWR** [Regalis11/Barotrauma#11894]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

i was on the humpback in the great sea our mission was killing hammerheads but when we made it to the end of the level there was a rock with the crystals on it blocking the end of the stage

### Reproduction steps

I think it was just a freak world gen bug 

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid we can't diagnose this unless we can find the level this happened in - do you still happen to have the save file where this occurred?

**Comment by BGURGEWR** [comment]
[full game campaign by th en on chool shjoldayus.zip](https://github.com/Regalis11/Barotrauma/files/11308192/full.game.campaign.by.th.en.on.chool.shjoldayus.zip)


that should be what you need we did finsh the campaign so im not sure if thats bad or anything

**Comment by Regalis11** [comment]
Thank you! I think I would need to know the exact level this happened in to be able to diagnose it, you don't happen to remember where it happened?

**Comment by BGURGEWR** [comment]
im so sorry for this late response only just saw the message but i THINK it was on the great sea transition

**Comment by BGURGEWR** [comment]
like the one from hydrothermal to the great sea?

**Comment by Regalis11** [comment]
No known steps to repro, closing
