### ISSUE TITLE
There is a bug that crashes the game

### ISSUE THREAD

**Issue by fartox** [Regalis11/Barotrauma#11901]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While changing light colors with screwdriver, if pressing tab to switch from R to G to B and finally to the Brightness box, the game crashes if you press tab on the Brightness box.

### Reproduction steps

While changing light colors with screwdriver, if pressing tab to switch from R to G to B and finally to the Brightness box, the game crashes if you press tab on the Brightness box.

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TerminatorTM** [comment]
You really should search for your bug for good before posting. And give it appropriate name.
https://github.com/Regalis11/Barotrauma/issues/11591

**Comment by fartox** [comment]
> You should really search for same bug before posting. And use an appropriate title. It will save time for devs to fix more bugs :) #11591

too lazy

**Comment by Regalis11** [comment]
This does seem to be the same issue as https://github.com/Regalis11/Barotrauma/issues/11563, but the issue should've been fixed in the v1.0.9.0 patch. Are you sure your game is up-to-date? Could you post the crash report? Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
Insufficient information to diagnose the issue.
