### ISSUE TITLE
Is it supposed to be impossible to undock from outposts?

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1190]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I can not undock from the outpost at the start of the campaign.

**Steps To Reproduce**
Try and undock, I found no buttons, nothing, no single thing to undock with.

**Version**
Windows 10

**Additional information**
Was playing on the aegir mark III remastered sub.

**Comment by Regalis11** [comment]
In the vanilla submarines you can undock by clicking the "docking clamp" button in the navigation terminal. I don't know about "aegir mark III remastered", but I would suggest asking the creator of the submarine.

**Comment by NilanthAnimosus** [comment]
Some submarine creators had actually wired up the ability to undock without even renaming the button on a nav terminal, but if a sub has not given you the basic functionality to do this - perhaps you could wire up the docking port to a button or do it in the sub editor fast.

There doesn't seem to be any way to "Force" yourself off without some kind of wiring to do so though, you can't really tear yourself off a docking port.
