### ISSUE TITLE
Contained sprites are showing in the wrong location

### ISSUE THREAD

**Issue by SquidingTin** [Regalis11/Barotrauma#11900]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When trying to use itempos on a rail gun shell, it displays correctly in the hands but once put on a container breaks in a few ways, one way is it flips the contained item upside down, another way it can break is having the contained item be shifted off to the side of the normal location. The attached file is an example of this happening to understand it better as this is better then a 30 page step by step.
(While i only tested this on the railgun, its likely this is a bug elsewhere)

![20230424210551_1](https://user-images.githubusercontent.com/33539475/234172018-2ebbb7db-ea5b-400a-87dd-aa7923c4e571.jpg)

[railgun bug.zip](https://github.com/Regalis11/Barotrauma/files/11316364/railgun.bug.zip)

### Reproduction steps

1. make a railgun shell have have a displayed item (in my case its the head of the shell)
2. Hold it in your hands
3. Put it in a storage container such as a loader or rack
4. Railgun head displays in the wrong location

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/29a532f8b49d953294d425a73e97b622d4dd2afd

**Comment by Jasontti** [comment]
Tested with provided mod.

If you take shell from full rack, one is displayed incorrectly.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/b5653a91-61bc-47e7-a340-9d9edda797f0)

**Comment by Jasontti** [comment]
No issues found.
Closing.
