### ISSUE TITLE
RegEx do not output captured group if it's a empty string

### ISSUE THREAD

**Issue by Instant2116** [Regalis11/Barotrauma#11919]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When RegEx should return empty string "", it returns nothing, so when you use concatenation component it also return nothing, because one of inputs is empty (RegEx do not return empty string). That is essential when used with Concatenation component, memory component provide a empty string, but RegEx do not.

### Reproduction steps

1. Open submarine editor
2. Load any submarine 
3. Place terminal and connect outputs and inputs to RegEx component inputs and outputs in accordance
4. Place RegEx component with expression `.*(?<name>.?)`  , that expression should return empty captured group from any input
5. Input anything in terminal and RegEx won't return empty string

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Instant2116** [comment]
as example empty memory-component will return empty string "", instead of nothing.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3db48e484002db4c9d66cc0a15d96f9d25f023a5 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested with and without conc component.
No issues found.
Closing ticket.
