### ISSUE TITLE
[Unstable] Unable to see mouse/HUD/escape menu after failing to access campaign save on new campaign

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11916]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Started a new game with two clients (from the same folder) connected to a dedicated server on a debug build, couldn't overwrite/transfer the save file and it resulted in one of the clients losing mouse and GUI visibility in game.

### Reproduction steps

1. Launch 2 clients on a debug build on 1.1 or above
2. Start a dedicated server
3. connect two (or more) clients to the dedicated server running from the same folder
4. launch a new campaign (to get the intro cinematic)
5. One of the clients will likely fail, you can increase the odds with more clients if not reproducing reliably.
6. Client should be booted out to server list. mouse will disappear. Joining the server again will result in no HUD elements visible and the escape menu will not appear.

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.1 (Voting-n-purchase-fixes) - https://github.com/Regalis11/Barotrauma-development/commit/8b6e0f2e730ac601115ccd8303ff24f947bb83e2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/558e13512f084c45851bb4745bf459a911bf5055

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.0-patch-1 commit https://github.com/Regalis11/Barotrauma-development/commit/0dd87adb08fc7813de80c0a091681a48f93790fc, no issues found.
