### ISSUE TITLE
Husked bots seek diving suit when I order them to follow with me to dive

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11913]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm playing with zealot robes and husk infection in singleplayer campaign.
I want to play some tactics by setting up a squad of 2 characters for diving, one normal diver and one husked with body armor.
I equipped a bot with the robes and get him infected with husk(90%).
Then, I equipped my current character with a diving suit and ordered the bot to follow me.
The bot tries to seek a diving suit even if I managed to drag it out the hull.

### Reproduction steps

1. equip yourself with a diving suit
2. give husk to a bot with zealot robes and make sure the infection reached the threshold for pressure protection
3. order the bot to follow

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Should test if this happens in the lastest unstable.

**Comment by NilanthAnimosus** [comment]
Tested on 0.13.2.0 - no issues found with the AI and husk infection/symbiosis and cultist/zealot robes (With following into the oceazn).
