### ISSUE TITLE
Loss of a symbiote after finishing campaign

### ISSUE THREAD

**Issue by DreadZen** [Regalis11/Barotrauma#11918]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello, I've encountered some troubles that I believe were caused by in-game bug. Some of my crew members had an husk symbiosis (Acsension story line). When I've reached the end, beaten jove and watched credits - I got teleported back to very first outpost but amongst all buffs I had for my characters with symbiosis I haven't noticed the symbiosis one. I've tried to see if it's just a visual bug but nope - it was just gone and so did console didn't say anything about it. That's kinda it. Honorable mention: Every other character with normal husk infection (+Genetics, that allowed to pervent full transformation) also did lose the husk infection.
If you need save files or anything else please contact me via my gmail (Skeletondead72@gmail.com).
Thanks. 

### Reproduction steps

1. Complete acsension quest
2. Get atleast 6(I did get it for 6 of my crewmates) crewmates with symbiosis
3. Defeat jove
4. Watch credits
5. Get teleported to first outpost
6. Save and quit and then load into save file
7. Check health condition (H)

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Unable to find the file or file doesn't exist.
```

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8ff73c5bbefaa3af813fc64f07b3deae0f9c29c0 (commit in our private repo). This seemed to apply to all afflictions, including buffs and effects from genetic materials.

**Comment by Regalis11** [comment]
Internal note for testing: you can simulate finishing the campaign without having to play through the end levels by modifying SinglePlayerCampaign/MultiplayerCampaign.DoLevelTransition as follows (forcing ending the campaign regardless of the type of level transition):
![image](https://user-images.githubusercontent.com/14351070/235091240-1a59e45d-36e7-44c2-a22f-085c89afa597.png)

**Comment by Jasontti** [comment]
Tested.
No issues found. Psychosis was removed, but husk symbiosis and genetic splicer, with genes, stayed to new game.
Closing ticket.
