### ISSUE TITLE
clownspecialhire1 event seemingly halted by pathofthebikehorn5

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11927]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It seems like the event pathofthebikehorn5 can still trigger after acquiring Clown Haven and speaking to the Jestmaster. This can lead to the event seemingly blocking the hire event from progressing:
![602960_20230429204234_1](https://user-images.githubusercontent.com/115734437/235319808-0dd08af4-a2c8-49b8-bf01-667118351d9b.png)
![602960_20230429210211_1](https://user-images.githubusercontent.com/115734437/235319864-c88abcd4-3118-403b-a999-5544b6fe7ef7.png) 

### Reproduction steps

1. Complete Clown event chain
2. Travel to outpost in search of Jestmaster hire

### Bug prevalence

Happens every now and then

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I wouldn't consider this a bug: it's intentional that after completing the event chain you can either get the event where you can ask him for more advice (pathofthebikehorn5) or the one where he can be hired (clownspecialhire1). If both happen to get selected in the same outpost, one will take priority over the other.

Does this actually cause some kind of strange behavior or issues?

**Comment by HawkinsThe71st** [comment]
I thought it might have made the hire event rarer than it's supposed to be.
I don't think both of them occurring should have any issues then, but I didn't know asking for advice is supposed to be possible even after completing pathofthebikehorn5 for the first time. If pathofthebikehorn5 occurs again on a different outpost after already completing it once, it spawns the Jestmaster with no option of asking him for more advice:
![image](https://user-images.githubusercontent.com/115734437/235365081-db5274ed-64be-4ccb-8be0-5c24ef1e098c.png)

**Comment by Regalis11** [comment]
No known steps to repro, closing. Probably also affected/addressed by the commonness changes to the events in the latest patch.
