### ISSUE TITLE
[Unstable] Dr. Submarine only works on buffs now

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11922]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dr. Submarine was changed from using `MedicalItemApplyingMultiplier` to `BuffItemApplyingMultiplier` so now it will only boost buff afflictions but the description is still "Medical items you apply are 25% more potent." Considering there are already two other medic talents which increase buff duration (Super Soldiers and Macrodosing) I'm unsure whether this was an intentional change.

### Reproduction steps

Morphine applied to character with 99 blunt force trauma heals for the same amount both with and without the talent Dr. Submarine (description implies it should be 25% more potent):
![image](https://user-images.githubusercontent.com/115734437/235150535-7cd53321-1870-4898-96dc-95d502a3888b.png)

### Bug prevalence

Happens regularly

### Version

Unstable (v1.0.11.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
