### ISSUE TITLE
[Unstable] No inital diving suit spawned

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11921]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you start a campaign, no diving suit is spawned on your sub.
Probably caused by change to divinggear.xml, line 64
```<PreferredContainer primary="divingsuitcontainer" spawnprobability="1"/>```
↓
```<PreferredContainer primary="divingsuitcontainer" />```

### Reproduction steps

start a campaign with dugong

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.0.11.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@a818bc5.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
