### ISSUE TITLE
Prisoner in jailbreak stuck

### ISSUE THREAD

**Issue by ll826** [Regalis11/Barotrauma#11929]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While doing a jailbreak mission on xinzou colony, the prisoner cannot leave their cell after the handcuffs have been taken off 

### Reproduction steps

1, start solo campaign
2. work up until mission is prompted from a separatist manager to free prisoners in Xinzou colony 
3. begin mission and remove handcuffs from prisoners 
4. watch as one gets stuck trying to leave

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This sounds like a waypoint issue of some sort, but since the outposts are randomly generated, I think we need a save file (or at the very least a screenshot of the place the bots got stuck) to be able to diagnose the issue. Sorry for the inconvenience!

**Comment by Regalis11** [comment]
Insufficient information to diagnose the issue
