### ISSUE TITLE
Outpost NPCs don't return to the room they're supposed to stay in if it becomes unsafe

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11925]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some of the outpost NPCs who offer services are set to stay where they spawn. If they escape the room due to it becoming unsafe (e.g. because of a fire, flood or hostile in the room), they'll never return to it. In debug builds, it also causes constant "ORDER go to CANNOT BE COMPLETED" console spam.

Seems to happen because AIObjectiveGoTo abandons the objective if there's unsafe hulls in the path, but it won't be removed because it's a forced order. A trivial fix would be to not abandon the objective if it's set to repeat (I gave it a test and it seemed to work), but I'm not sure if that'd cause some kind of side-effects.

### Reproduction steps

1. Go to the HR Manager, a doctor or a sub sales NPC
2. Start a fire in the room, wait for the bot to run out
3. Put out the fire
4. Notice the bot won't return, and the console will spam "ORDER go to CANNOT BE COMPLETED"

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/tree/fix/npc-return-to-wait-target. Didn't create a PR yet, as we should target this for the second patch. The changes are a bit volatile.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
