### ISSUE TITLE
[Unstable] Some issues with reworked Typhon

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11923]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**Path issue 1: Mysterious ladder waypoint near reactor**
![typhon_path_issue_1](https://user-images.githubusercontent.com/99462070/235160594-d50058cf-5c9b-4fc6-ae96-a957de93dfd6.png)

**Path issue 2/3: Duplicate hatch waypoint and missing hatch waypoint in armory**
![typhon_path_issue_2n3](https://user-images.githubusercontent.com/99462070/235160608-57bc4251-2d6e-4e67-bec2-1858e9a9e0b8.png)

The rest are no issues but rather suggestions, if you want to challenge players with limited fire angle, you don't have to fix them.
**Fire angle of rear bottom turret can be improved**
![typhon_fire_angle](https://user-images.githubusercontent.com/99462070/235161630-ac829e1b-7bc1-4444-b0d1-b5f309c67823.png)

**Fire angle of bottom large turret can be improved**
![typhon_fire_angle_2](https://user-images.githubusercontent.com/99462070/235161819-e968b3be-b49d-41e5-b336-2db826c04081.png)

A reference from typhon 2:
![typhon2_fire_angle](https://user-images.githubusercontent.com/99462070/235161926-07f2c147-1e99-49a0-9e5f-848f7b9529a9.png)

**Fire angle of front top large turret can be improved**
![typhon_fire_angle_3](https://user-images.githubusercontent.com/99462070/235162219-4b1933d5-0080-4123-8c31-298f699912bf.png)

### Reproduction steps

open typhon in sub editor 

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.0.11.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
