### ISSUE TITLE
Make Corpses of Monsters Spawn Randomly Around Levels- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1192]
I believe not all corpses of monsters end up being eaten. Some monsters die due to explosions from railguns, some simply bleed out or lose health entirely due to regular bullets. Health Scanner HUD can read causes of deaths being randomly given. Corpses can sometimes be torned apart and are often laying on the ground.

**Comment by Regalis11** [comment]
I don't think this is necessary. It would be very unlikely for you to even stumble upon those corpses unless there's a huge number of them in each level - which comes with a performance cost and extra bandwidth usage in multiplayer.
