### ISSUE TITLE
"Failed to read component state" - Error while reading a message from server.

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#11930]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Can't connect to a server.
Two friends got the same error message.
1:
![MT1](https://user-images.githubusercontent.com/10529134/235354343-18902334-a291-46b2-96fc-08e98d52fe1d.png)
2:
![MT2](https://user-images.githubusercontent.com/10529134/235354387-73dbdf31-dcb9-404e-9067-77d605d2a9a8.png)

### Reproduction steps

Not sure, but try loading Mechtrauma without Modding Toolkit. For some reason, the mod Modding Toolkit doesn't get loaded automatically. I suspect this is the cause.

### Bug prevalence

Happens every now and then (2 times)

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server.
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: Failed to read component state - Barotrauma.Items.Components.ItemContainer is not IServerSerializable.
```

**Comment by Regalis11** [comment]
Thank you for the report!

It seems probable that this is an issue caused by some of the mods (as the vanilla game shouldn't be trying to create entity events for an ItemContainer). Clear steps to repro the issue would help us in diagnosing the issue.

I personally could not find a way to reproduce it - Mechtrauma seems to include some errors that prevent it from being enabled.

**Comment by Krzeszny** [comment]
I can't reproduce it. All I know is that it was definitely caused by Mechtrauma UNSTABLE. 
But if you _really_ want to give it another try, here's my **guess**:

1. Install Mechtrauma UNSTABLE and all 3 of its dependencies: clientside Lua, C# and Modding Toolkit.
2. Host a server with a T3 submarine from https://steamcommunity.com/sharedfiles/filedetails/?id=2933544027 (because T3 subs use all the machines)
3. Start a mission
4. Get a client to join. That client must have clientside Lua and Cs installed, but _not_ have Modding Toolkit installed before joining... 
well, I'm assuming those 2 friends had clientside Lua enabled. Maybe they didn't.

I don't have anyone to test it with. Also, both Mechtrauma versions normally work with clientside Lua and its dependencies without causing any errors so I don't know what's causing errors on your side.

Also, the host got mad and... yeeted Mechtrauma, so I haven't heard of anyone getting that exception after this report.

**Comment by Regalis11** [comment]
Thank you for the extra info!

> well, I'm assuming those 2 friends had clientside Lua enabled. Maybe they didn't.

This could be a potential explanation - if the modded item requires the ability to create network events for ItemContainers, and adding this functionality requires Lua/C# modifications, it could be that not having those installed would lead to this exception.

But regardless, it seems unlikely that this is an issue in the vanilla game, so I think I'll close the ticket.
