### ISSUE TITLE
Moving Submarines With Railguns- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1193]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can push railguns with your body.

**Steps To Reproduce**
1. Go outside submarine.
2. Go to nearest railgun.
3. Try to move it's base with your body by swimming into it.

**Version**
Any but I was playing on 0.8.2.3.

**Comment by Regalis11** [comment]
I just tried this and didn't notice anything unusual. What exactly happens when you push the railgun? Does the submarine move, or does the railgun move relative to the submarine?

**Comment by rico6822** [comment]
> I just tried this and didn't notice anything unusual. What exactly happens when you push the railgun? Does the submarine move, or does the railgun move relative to the submarine?

I swear I had it moving like I was super strong. Submarine was larger than default aegir.

**Comment by Regalis11** [comment]
What exactly was moving? The railgun or the entire submarine?

**Comment by thegrb93** [comment]
Probably something strange going on with that specific submarine.

**Comment by rico6822** [comment]
> What exactly was moving? The railgun or the entire submarine?

Entire submarine. Try to launch nuclear reactor and set autopilot to maintain position. Maybe that's it.

**Comment by rico6822** [comment]
> What exactly was moving? The railgun or the entire submarine?

Alright, I think I have  potentially figured out the thing:

It happens when combat music is playing possibly because normally players cannot move submarine with railguns. For the need of combat the game assumes it is the monster who moves the railgun since the music is playing. It was always happening to me when music was playing. There was an alive fractual guardian inside ruins and I was going inside submarine with artifact.

**Comment by Regalis11** [comment]
The only explanation I've been able to come up for this is that the character is simply pushing the submarine, which can happen if the submarine is light enough. If so, b99c0ef should make this much harder to do.
