### ISSUE TITLE
Brightness [Steam Version]

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1194]
Anybody else thinking that the outside of the sub is much too bright? Especially as seen in the trailer. The same could even be said for the inside of the submarine as well as the alien ruins. I'd suggest lowering the brightness if you want to keep the horror-like atmosphere.

**Comment by Regalis11** [comment]
We had increased the brightness when recording the trailer, the game isn't normally that bright.

**Comment by Flarix1** [comment]
How do you up the brightness/gamma? It's too dark for me. I'd really appreciate the help :)

**Comment by Flarix1** [comment]
> We had increased the brightness when recording the trailer, the game isn't normally that bright.
