### ISSUE TITLE
Can't melee attack doors that are PART of a submarine while outside the submarine

### ISSUE THREAD

**Issue by pantherpusher** [Regalis11/Barotrauma#11943]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As stated in the title, I tried to attack the various doors and hatches that I had placed used the submarine editor outside of any kind of hull, I did this in response to noticing I couldn't seem to use the boarding axe to breach hatches all of a sudden after one of the hotfix patches. While it took awhile for me to sit down and test it I'm certain that this is the problem. It may even impact 

### Reproduction steps

1. Acquire a submarine and a melee weapon
2. travel outside the submarine's hull
3. Try to attack the hatches/doors
Failing that:
1. take a barsuk and set up the various doors and hatches outside of it's normal bounds in the submarine editor
2. attack the doors and hatches with a melee weapon

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by pantherpusher** [comment]
Have you been able to reproduce this or do I need to provide more info?

**Comment by Regalis11** [comment]
@pantherpusher we haven't had time to look into this yet, but I'm fairly sure this is easy to reproduce with the information you've provided. Thank you for the report and sorry for the inconvenience!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/401053b5569c9df2cf97207cb1b52b65f93b2ceb (commit in our private repo)

**Comment by AdamH-Daedalic** [comment]
Tested against [Regalis11/Barotrauma-development#4266](https://github.com/Regalis11/Barotrauma-development/issues/4266). Player was able to attack and destroy a variety of doors and hatches attached to the outside of the submarine using various melee weapons.
Closing as fixed
