### ISSUE TITLE
"Sleight of Hand" first option doesn't give Alien Trinket

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11949]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the event `sleightofhand`, picking the first option and passing the rng check doesn't spawn the Alien Trinket in the player's inventory:
![image](https://user-images.githubusercontent.com/115734437/235769663-d845d98b-63af-4b73-a97a-bbed502ee6b0.png)
Changing this part of the xml from
```
<Option text="EventText.sleightofhand.o1">
  <RNGAction chance="0.125">
    <Success>
      <ConversationAction targettag="triggerer_player" text="EventText.sleightofhand.o1.c1">
        <SpawnAction itemidentifier="alientrinket1" targetinventory="triggerer_player" />
      </ConversationAction>
    </Success>

```
to
```
<Option text="EventText.sleightofhand.o1">
  <RNGAction chance="0.125">
    <Success>
      <ConversationAction targettag="triggerer_player" text="EventText.sleightofhand.o1.c1" />
      <SpawnAction itemidentifier="alientrinket1" targetinventory="triggerer_player" />
    </Success>
```
seems to fix it.

### Reproduction steps

1. `triggerevent sleightofhand`
2. Pick the 1st option "Join the game"

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad32f7bc26af8d2c1c6ba5d0002f10872d8665d1

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
