### ISSUE TITLE
Thalamus tendon is not able to stick to humans when modded to do so

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#11940]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Disclaimer: it should be a duplicate of my old report but it is gone and I never seen a reaponse on it, so I created a new one

Problem: thalamus tendon is not able to stick to humans when modded to do so, while any other (modded or vanilla) projectile is able to do that

Note: It can hook creatures tho
![unknown](https://user-images.githubusercontent.com/42521948/235604084-67855987-c22f-4be2-ac68-bcb5310aed3e.png)

### Reproduction steps

1. copy guardian/harpoon spear settings on thalamus tendon and add harpoon/depth charge ammo tag for ease of testing.
2. put thalamus tendon into harpoon gun/depth charge loader via d3bug menu or spawning it in editor
3. load into test and shoot human and then shoot creatures like mudraptors (it will not stick to humans)
4. repeat 1-3 steps with any other projectile of your liking (make sure it doesnt break on impact), for example grapple item from movable and sellable wrecks

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by PanmanS** [comment]
UPD: iirc there might a code check specific for thalami

**Comment by PanmanS** [comment]
Will do as soon as im home but all I did is copy and paste alien spear xml onto tendon

**Comment by Regalis11** [comment]
Thanks! Based on the screenshot, it seems there's some other changes too, since that's not the rope sprite used by the alien sprite.

**Comment by PanmanS** [comment]
Correct, i'd put back thalami rope back with with, but i doubt sprite can interact with world? Anyways I will be home to send you 1 to 1 version of my edit at GMT+3 19:00 but trust me, it is just alien spear put onto tendon!

**Comment by PanmanS** [comment]
Aight, just a little more, got into traffic jam (pls dont slap wont fix or i will kill @LePiromano)

**Comment by PanmanS** [comment]
[New Wrecks For Barotrauma (With sellable wrecks).zip](https://github.com/Regalis11/Barotrauma/files/11375884/New.Wrecks.For.Barotrauma.With.sellable.wrecks.zip)
(sorry for bloat, i was in a hurry, but it should contain tendon that you can see in editor)

![Barotrauma_Qa8pEdetaQ](https://user-images.githubusercontent.com/42521948/235737631-e7c39cad-1de1-4e12-a3aa-7f64890e5de2.png)

just run this mod, spawn tendon in editor, give it harpoon ammo tag, put it inside harpoon gun, copy 5 of those and then just boot up in test and fire both at humans and creatures

So while humans fail to stick, Mudraptor veteran for example works just fine!

**Comment by Regalis11** [comment]
As I suspected, the issue seems to be that StickToLightTargets is set to false. "Light target" in this context means a physics body whose mass is less than half of the mass of the projectile, and since the tendon projectile is much more massive than the spear, it'll behave differently from spears.

**Comment by PanmanS** [comment]
StickToLightTargets? Where it should be defined?

**Comment by Regalis11** [comment]
https://regalis11.github.io/BaroModDoc/ItemComponents/Projectile.html

It's a property of the Projectile component, defined the same way as the rest of the "StickTo..." properties.

**Comment by PanmanS** [comment]
Thanks!

**Comment by PanmanS** [comment]
Aight, tested it in controlled enviroment - this bool has no effect or I do something wrong! It still fails to properly stick to human even with that bool! So can we re-open issue?


  `<Projectile characterusable="false" launchimpulse="50.0" StickToLightTargets="true" sticktocharacters="true" sticktoitems="false" sticktostructures="true" sticktodoors="false" sticktodeflective="true" maxjointtranslation="100">
      <Attack structuredamage="300" itemdamage="100" targetforce="10" severlimbsprobability="0">
        <Affliction identifier="bleeding" strength="30" />
        <Affliction identifier="lacerations" strength="30" />
        <Affliction identifier="stun" strength="0.3" />
      </Attack>
      <StatusEffect type="OnImpact" target="This">
        <Sound file="Content/Map/Thalamus/Sounds/CARRIER_harpoonHit1.ogg" range="1000" selectionmode="Random" />
        <Sound file="Content/Map/Thalamus/Sounds/CARRIER_harpoonHit2.ogg" range="1000" />
        <ParticleEmitter particle="gib" anglemin="0" anglemax="360" particleamount="15" velocitymin="100" velocitymax="2000" scalemin="0.5" scalemax="1.0" />
        <ParticleEmitter particle="heavygib" anglemin="0" anglemax="360" particleamount="15" velocitymin="100" velocitymax="500" scalemin="0.5" scalemax="1.0" />
      </StatusEffect>
	  <StatusEffect type="OnActive" target="UseTarget,This" comparison="And">
        <Conditional Snapped="false" />
        <Conditional mass="lt 50" />
        <Affliction identifier="drag" strength="1" />
      </StatusEffect>
    </Projectile>`

**Comment by Regalis11** [comment]
Could you please post the full xml of the item, with all the modifications you've done to it?

**Comment by PanmanS** [comment]
[New Wrecks For Barotrauma (With sellable wrecks).zip](https://github.com/Regalis11/Barotrauma/files/11425308/New.Wrecks.For.Barotrauma.With.sellable.wrecks.zip)
ugh, sorry for long response, but it is literally same as previous version but with `StickToLightTargets` slapped on

**Comment by Regalis11** [comment]
> Hmm, could i ask for a fixed version

I don't have it anymore, but I just removed the StatusEffects from the projectile and added a tag to make it containable in a harpoon. 

> Also is there anyway around or i will need to create seperate tendon for my thalamus traps? Whole concept was that if thalami fleshguns didnt find submarine, they would aim and hook humans instead.

I think you might need to have 2 separate items, because there's no way to set different kinds of forces for different types of targets.

In any case, I think I'll close the ticket, as there isn't enough information here to address the issue. To verify whether this is an issue in the game or an issue with the modded item, we'd need the full xml of the item and steps to reproduce the issue.
