### ISSUE TITLE
One strange egg spawns two pets

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#11941]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Had to obtain some pets for testing so I spawned a strange egg and fed it saline and noticed that two Orange boys spawned

### Reproduction steps

1. Spawn a strange egg using the spawnitem command
2. Spawn saline
3. Feed Saline to egg
4. Notice that two pets spawned

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.0.12.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This seemed to be a bigger issue: ItemContainer applied all its status effects twice. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9183167e97c45193a9d737179c8005643eb9d466

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
