### ISSUE TITLE
Few Changes to Walls- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1195]
- [ ] Increase amount of durability to all walls. If the submarines are being developed to fight monsters it makes sense if they are being well durable. 

- [ ] Make welding tool repair slower so it won't be so unnaturally fast and deadly. 

- [ ] Make players and husks (the only monster making exception here) cross the walls below 20% of durability instead of having them being equal zero for it. I'm pretty sure they can fit. Maybe crawlers should cross it as well but when it's 10% or less.

**Comment by Regalis11** [comment]
Is there a specific reason why you want these changes, other than realism? We've done quite a lot of balancing to get the durability of the walls to a suitable level: they need to be durable enough that a minor collision or a brief encounter with one of the smaller monsters doesn't immediately cause a flood, but not too durable or the game becomes too easy. The welding speed is also balanced to a level where repairing larger breaches isn't a too time-consuming chore. I feel the current wall durabilities and the welding speed are working pretty well.

**Comment by rico6822** [comment]
> Is there a specific reason why you want these changes, other than realism? We've done quite a lot of balancing to get the durability of the walls to a suitable level: they need to be durable enough that a minor collision or a brief encounter with one of the smaller monsters doesn't immediately cause a flood, but not too durable or the game becomes too easy. The welding speed is also balanced to a level where repairing larger breaches isn't a too time-consuming chore. I feel the current wall durabilities and the welding speed are working pretty well.

If you say so than let it be but will players be able to cross through walls with less than 20% of hull?
