### ISSUE TITLE
Basics tutorial - can move too fast for the open locker / pickup screwdriver section to register

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11958]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you sprint through the basics tutorial completing every objective as fast as you can, it is possible go grab the screwdriver before it highlights the cabinet. Then it will highlight while you can repair, and progress up until being unable to weld the wall.

Opening the locker again will still work, then requiring you to again equip the screwdriver if not already equipped - but if already done (having the screwdriver on you) this step should probably be completed progressing the tutorial properly.

### Reproduction steps

1. Start basics tutorial
2. sprint through it grabbing the screwdriver without dismissing/reading.
3. Find once you close the UI that the objective will appear without being completed.

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.0.13.0 (RC build / unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66bb2c1ad2fccb06c01b8aeabc495ec599074a21

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Draylynn** [comment]
Just run into the same issue...
