### ISSUE TITLE
Azimuth "Silent Running" prevents it from going up

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#11954]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/73229309/236272570-e453458b-d16a-4f21-9421-2845c9b4a4c5.png)

Don't clamp targetlevel to 20/-20

### Reproduction steps

Activate silent running
Try to go up
Can't go up

### Version

Unstable (v1.0.12.0)

**Comment by pantherpusher** [comment]
SAVE MEEEEEEEEEE

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0dd87adb08fc7813de80c0a091681a48f93790fc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
