### ISSUE TITLE
High Morale is not upgarding to Excellent Morale. 

### ISSUE THREAD

**Issue by 8on8er** [Regalis11/Barotrauma#11955]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I am on a singleplayer campaign in the third biome using the Barsuk. I have the NPC bot Ignatius May who has the Leading by Example talent and a captain who has just unlocked the final Skipper tree talent, Family.

Despite all my crewmembers being alive for several rounds of missions High Morale has not changed to Excellent Morale.

My theory is it has something to do with a conflict of multiple talents active at the same time between my captain and Ignatius May potentially.

### Reproduction steps

1. Start a singleplayer campaign.
2. Buy/select the Barsuk.
3. Hire Ignatius May.
4. Unlock the Family talent with your first/main captain in the third biome.
5. Complete a mission with none of your crewmembers dying.
6. Observe High Morale not changing to Excellent Morale and the bonus's not subsequently doubling.

Below are the relevant screenshots:
![20230504183428_1](https://user-images.githubusercontent.com/115426153/236285803-44fb9cae-8f78-4dc0-a482-227ad399fc93.jpg)
![20230504183438_1](https://user-images.githubusercontent.com/115426153/236285808-b472a2b8-980f-4e01-8269-57c4c0e5cc33.jpg)
![20230504183452_1](https://user-images.githubusercontent.com/115426153/236285811-6db37836-d7c7-4c9d-bd57-700c5f0aad8c.jpg)
![20230504183506_1](https://user-images.githubusercontent.com/115426153/236285816-a46d57dc-d2af-47b1-8985-66dbbff1ebff.jpg)
![20230504183519_1](https://user-images.githubusercontent.com/115426153/236285820-75f382db-8f5e-4ad0-875c-6a06b62390e3.jpg)

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/79c3f5a2e3dbfd852be65649a84ec093f15d3ded

**Comment by Jasontti** [comment]
Tested.
Started new campaign and gave original captain "Leading by example" and "Family". Buff upgraded immediately to "Excellent morale".
Traveled to next outpost and spawned in next captain, gave "Leading by example". Buff was still "Excellent morale".
Killed one crew member on next round.
In the next outpost had both buffs for a while, but "Excellent morale" stayed.

![2023-06-08_11-57](https://github.com/Regalis11/Barotrauma/assets/8488224/cda94f59-eff9-46df-bcb7-bbdf2823db50)

Next round only had "Excellent morale", despite having one fatality last round.

**Comment by 8on8er** [comment]
> Fixed in https://github.com/Regalis11/Barotrauma-development/commit/79c3f5a2e3dbfd852be65649a84ec093f15d3ded

Giving me error 404 sadly.

**Comment by 8on8er** [comment]
Just wanted to clarify if I have any deaths will my high morale never upgrade to excellent if any of my crewmembers have died?

My captain still only shows high morale. This is some 10 locations x missions later with no one dying. Apologies if it's my lack of understanding.

**Comment by Jasontti** [comment]
Thank you for commenting.

>Giving me error 404 sadly.

That is in development repository, which is private.
No need to apologize. I tested made changes in dev build and noted some still witholding issues.
It seems that "excellent morale" is now applied bit too agresively now. :)

**Comment by Regalis11** [comment]
I'm not sure I see the issue here

>Traveled to next outpost and spawned in next captain, gave "Leading by example". Buff was still "Excellent morale".

This seems correct, as long as there's one captain with the "Family" talent you should get "Excellent morale" regardless of your second captain's talents.

>Killed one crew member on next round.
>In the next outpost had both buffs for a while, but "Excellent morale" stayed.

This also doesn't seem like a bug. If anyone dies, the "Excellent morale" gets downgraded to "High morale" for the rest of the round, but it should reset the next round (which seemed to work?).

**Comment by 8on8er** [comment]
My issue is still persisting where I cannot get excellent morale despite no one dying in-between rounds I'm not sure how to replicate beyond what I've already described.

**Comment by Regalis11** [comment]
> My issue is still persisting where I cannot get excellent morale despite no one dying in-between rounds I'm not sure how to replicate beyond what I've already described.

The fix we're working on is not publicly available yet, we're still testing it internally. We managed to replicate the initial issue you described, so no need for any further info, I was just asking Jasontti for more details on the further issues he found when testing my fix. :)

**Comment by 8on8er** [comment]
> > My issue is still persisting where I cannot get excellent morale despite no one dying in-between rounds I'm not sure how to replicate beyond what I've already described.
> 
> The fix we're working on is not publicly available yet, we're still testing it internally. We managed to replicate the initial issue you described, so no need for any further info, I was just asking Jasontti for more details on the further issues he found when testing my fix. :)

Ah sorry I understand now, thanks.

**Comment by Jasontti** [comment]
I misunderstood how it should've been working.
Closing ticket.
