### ISSUE TITLE
Using <Stateffect  target="character" empvulnerability="1"> causes errors.

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11953]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm writing a xml file that changes some properties of human using Affliction, but it could not work.
```
    <AfflictionHusk name="Cyborg Effects" identifier="cyborgeffects" type="alieninfection" healableinmedicalclinic="false" targets="human" 
                    huskedspeciesname="cyborg" limbspecific="false" indicatorlimb="Torso" hideiconafterdelay="true" showiconthreshold="0" needsair="true" 
					causespeechimpediment="false" treatmentthreshold="1000" dormantthreshold="0" activethreshold="0" transitionthreshold="1000" 
					transformthresholdondeath="1000" sendmessages="false" maxstrength="100" iconcolors="94,54,95;163,73,164;200,191,231" > 
   <Effect minstrength="80" maxstrength="100" resistancefor="bleeding,poison" minresistance="0.4" maxresistance="0.5">
       <StatusEffect type="Always" target="Character" PressureProtection="4800.0" BleedParticleAir="spark" BleedParticleWater="spark" setvalue="true" EmpVulnerability="1"/>
    </Effect>
    <icon texture="Content/UI/TalentsIcons3.png" sheetindex="4,0" sheetelementsize="128,128" color="163,73,764,255" origin="0,0" />
    </AfflictionHusk>
```

I guess this property of human can not be changed?

### Reproduction steps

1.Add the XML code above to an localmod.
2.Apply the affliction using console command.
3.Errors occur.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error in SerializableProperty.TrySetValue {Property set method not found.}
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Barotrauma.SerializableProperty.TrySetValue(Object parentObject, Single value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\SerializableProperty.cs:line 442
```

**Comment by Regalis11** [comment]
Thank you for the report! Characters don't have an editable property called EmpVulnerability, so I'm afraid this effect won't work.

**Comment by AzureNocte** [comment]
OK, I got it. But if I want to change something to make human vulnerable to emp, what should I do?

**Comment by Regalis11** [comment]
Unfortunately I don't think that's possible at the moment. :/

**Comment by AzureNocte** [comment]
Thank you for the reply! Hope more properties would be editable in the future.
