### ISSUE TITLE
Roles Tutorial - Able to use up all coilgun ammunition on security tutorial

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11961]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

No new ammunition spawns if you run out, although difficult to do, if time is spent shooting other things or while not seeing the target, it is possible to run out of ammo.

### Reproduction steps

1. start roles tutorial
2. do security tutorial up to coilgun
3. shoot anything except mud raptor until out of ammunition.
4. find tutorial doesn't end and no new ammunition spawns.

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.0.13.0 (RC build / unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a573045f77e1a592221eecc70ff77e55f04cc872

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
