### ISSUE TITLE
Eye of Europa "Switch"-stage 

### ISSUE THREAD

**Issue by Caius-the-Dark** [Regalis11/Barotrauma#11966]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm doing the endgame, and on the second stage I've come to the giant door and found the log mentioning the "shadow on the sonar". Other than my sonar not functioning in the gate structure, I couldn't figure out if it meant anything significant. However, the objective is pointing me to a Switch that is several hundred meters behind the gate it's supposed to open. I've loaded my save in the hopes of generating a new map, but no luck.
![screenshot](https://user-images.githubusercontent.com/132873465/236740817-69166856-e51f-446b-81ab-244fe6d6bf74.jpg)

### Reproduction steps

[Space Water Trucking.zip](https://github.com/Regalis11/Barotrauma/files/11418133/Space.Water.Trucking.zip)

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! The switch is not behind the gate, you need to move further into the structure to get to it:
![image](https://user-images.githubusercontent.com/14351070/236757358-68b54fcc-85a1-4126-9cdd-640e4b915f35.png)

**Comment by Caius-the-Dark** [comment]
Thank you so much, I felt like my save was ruined. I guess my eyes were looking down on the sonar in both attempts, and didn't notice a path up.

Love the game and am eager to finish the campaign tomorrow!

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
