### ISSUE TITLE
Make Traitors More Tasked in PvP- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1196]
I believe both sides of conflict need as many sailors as possible on both of their side. PvP is where one of the crews is supposed to fully perish. I believe traitor should have an objective to terminate entire crew (kill as many personally as he can) instead of just a single person and than he should dock with submarine to enemy controlled outpost if possible so they can have additional submarine. Traitors who go for it don't care about their families and will not become depressed if the side they betray will decide to murder them in revenge.

If traitors show up the crew who has a traitor from the enemy by their side will be informed who is he. They will also see nickname of him as white instead of red. The crew will be told to spare that person or even let that person dock enemy submarine to their outpost. If that's impossible the traitor can enter the submarine of his former enemy he now works for.

**Comment by Regalis11** [comment]
I think this might make the PvP rounds much less entertaining. Having a traitor kill the entire crew is generally not very fun even on normal rounds, and in the PvP missions it would sort of ruin the round for both teams. Imagine a traitor blowing up the reactor and killing the crew: the opposing team gets a "you won" popup without even having encountered the other sub.

**Comment by rico6822** [comment]
> I think this might make the PvP rounds much less entertaining. Having a traitor kill the entire crew is generally not very fun even on normal rounds, and in the PvP missions it would sort of ruin the round for both teams. Imagine a traitor blowing up the reactor and killing the crew: the opposing team gets a "you won" popup without even having encountered the other sub.

Yea, that would be ridiculous. We can task the traitor to just pretend to fight the enemy without really harming them.
