### ISSUE TITLE
Collapsed affliction indicator doesn't resize/position correctly on resolution change

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11960]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Changing resolution mid-round with a collapsed affliction indicator causes it to become squashed or stretched, indicating it is not resizing properly (if at all) on resolution change.

This is a case of it being lower to larger resolution:
![image](https://user-images.githubusercontent.com/29177976/236446773-bf0fd5ff-3c0f-4c15-81df-f7113133f263.png)

and this is a case of larger resolution to smaller resolution:
![image](https://user-images.githubusercontent.com/29177976/236447131-e167241d-ab06-446c-8797-b754deed8739.png)

### Reproduction steps

1. change to a high or low resolution
2. Start a round
3. Unlock all talents (to have buffs that collapse)
4. Give self an affliction such as blunt force trauma for comparison in size
5. Change to a larger or smaller resolution than the previous
6. Observe the shape of the collapsed afflictions indicator

### Bug prevalence

Happens every now and then

### Version

Other

### -

1.0.13.0 (RC build / unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d12431ad93d6aeb2dfc2a74b450eb9a926d50f28

**Comment by Jasontti** [comment]
Tested with smallest to biggest resolution i could fit on screen.
Indicator scales accordingly to resolution.
Closing ticket.
