### ISSUE TITLE
Defense Bot will attack husk container in sight.

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11969]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I believe it is a bug, in fact other pets tend to attack it too(although they could not), judging from their ai target attackpattern.

I think the issue is related to husk container's group="husk", where other pets'  group="human", which sets them hostile to it. However AI crew will ignore this because of the pet tag.

### Reproduction steps

1.go into sub editor
2.spawn a huskcontainer, then spawn a defensebot
3.the latter instantly attack the former

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Tested (in a couple of different scenarios: with the husk extremists, in an abandoned outpost, in the player sub, with other pets present), couldn't spot any issues.
