### ISSUE TITLE
[Unstable] Hanging vine level decoration ("web") can block submarine

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11967]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![level_deco_blocks_sub_0](https://user-images.githubusercontent.com/99462070/236852859-bab833a5-7185-4b36-aeea-924cad05027e.png)

The decoration within the red rectangle can block submarine like a wall.
Picture taken in 1.0.12. Not sure if it still exists in 1.0.13.1. 
I suppose it does since I haven't found any fix about this in the changelog

### Reproduction steps

1. start a campaign
2. use free cam to find level deco like this
3. teleport your sub and try move toward it

### Bug prevalence

Happens regularly

### Version

Unstable (v1.0.12.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
![602960_20230508230006_1](https://user-images.githubusercontent.com/99462070/236859206-41ba7d7d-31ef-46fd-b447-a406659c2541.png)
Additional info: Submarine can move toward them but very slowly.
Version:1.0.13.1

**Comment by Regalis11** [comment]
These hanging "vines" actually intentionally slow down the submarine. There should be a visual effect (the vines sort of stretch with the sub's movement) and it shouldn't block the movement entirely, so it seems something might be bugged here. We'll need to take a closer look. Thanks for the report!

**Comment by BiffW** [comment]
>These hanging "vines" actually intentionally slow down the submarine

Imagine you were steering typhon at full-speed and got instantly stopped by something that is not visible on your sonar monitor. What form of power is this? It makes no sense.

**Comment by Regalis11** [comment]
>What form of power is this? It makes no sense.

The idea was that they're some kind of sticky, stretchy vines that stick to the submarine. Getting instantly stopped by them isn't intentional though.

**Comment by Regalis11** [comment]
Looks like the visual effect was broken, fixed in https://github.com/Regalis11/Barotrauma-development/commit/432acaea6c18d2a1618992ad0b56e7d027f7a2c6 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, whenever sub comes in contact with the vines they start popping in and out of existence. 

Video:
https://www.youtube.com/watch?v=pLedYDOu2Bs

**Comment by Regalis11** [comment]
@Rokvach fixed in https://github.com/Regalis11/Barotrauma-development/commit/0dd74288133ebc312730b9dbb9b65e1f03d65988

@BiffW Personally I think it's better that they're not visible on sonar (the same as sonar flora), otherwise they'd be trivial to avoid.

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.
