### ISSUE TITLE
Doors make no sounds when attacked with melee weapons

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11962]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using melee weapons such as crowbars, knives, screwdrivers, wrenches, ceremonial swords and such on doors no sounds are made while the door does take damage, essentially allowing for the silent breaking of a door.

### Reproduction steps

1. start a round
2. attack any door with any kind of melee weapon component
3. find no sound is made on damage/hit.

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.13.0 (RC build / unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0e87c47d7624e43695a87374335edf05540d241c

**Comment by Jasontti** [comment]
Tested.
Doors and hatches make sounds when damaged with melee or otherwise.
Closing ticket
