### ISSUE TITLE
Can not check afflictions by type in a status effect in an item

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11963]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I want to make a wearable item. 
When a player wearing it receives any form of physical damage, it consumes the item on slot 0 and does healing.
The following status effect will never be applied.
```
<StatusEffect type="OnWearing" target="Character,Contained" condition="-3.125" targetslot="0">
    <ReduceAffliction type="damage" amount="25" />
    <Conditional damage="gt 0" />
</StatusEffect>
```

### Reproduction steps

see code above

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
I've tried using `<requiredAfflictions />` instead. But it only works for `OnDamage`. It only triggers when the item itself is damaged, not the character wearing it.

**Comment by AzureNocte** [comment]
I think you it shoule be:
`<StatusEffect type="OnDamaged" target="Character" >
    <requiredAfflictions  type="damage" amount="0"/>
    <ReduceAffliction type="damage" amount="25" />
   <StatusEffect type="OnWearing" target="This" condition="-3.125" >
   </StatusEffect>
   <StatusEffect type="OnWearing" target="Contained"  targetslot="0">
       <Use />
   </StatusEffect>
</StatusEffect>`

**Comment by Regalis11** [comment]
The conditional checks the properties of the entities the status effect targets, in this case the character and the contained item. Neither of them have a property called "damage", so the conditional is never met, and the effect never executes.
