### ISSUE TITLE
End level location can generate with outpost docks - Causing issues with level generation.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11974]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

An outpost on the previous connection to the eye caused a submarine to spawn within the walls as the outpost dock:

![image](https://github.com/Regalis11/Barotrauma/assets/29177976/65ea5570-d7ac-413e-a49b-c80902c54235)

Note this image is the bottom left corner about 200 meters from the anomaly, and not the top-left corner of the map.

Save file:
[BrokenEnd.zip](https://github.com/Regalis11/Barotrauma/files/11433218/BrokenEnd.zip)

Additional notes:
The save has a few edits via a save editor on the submarines used, However I believe the actual issue here is the outpost placement on the map

### Reproduction steps

Use the provided save and go to the eye.

### Bug prevalence

Happens every now and then

### Version

Unstable (v1.0.12.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested with attached save and independent save last outpost was not claimed between several rounds.
No Issues found.
