### ISSUE TITLE
Voice / Radio chat when using different channels causes radio static when within local voice range

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11972]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Two players on a server with different radio channels (IE, 0007 and 0009) using radio voice within different (but close by) rooms on the edge of local voice range will hear static and the radio effects, despite what they should be hearing being local voice chat (As they are not in the same channel). 

This is the approximate distance of static before any further you get silence instead (So about local voice range):
![image](https://user-images.githubusercontent.com/29177976/237043077-ff2c18ec-2f6d-44b7-b72b-ab432fbb6843.png)

### Reproduction steps

1. Use two clients
2. Start a multiplayer round IE. sandbox.
3. move to different rooms, about the range of local voice
4. have both clients on a different channel (IE, one on 7, one on 9)
5. Have one use radio voice
6. make sure second client can actually hear it.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54b67d565f61a99fa9bc39201ef523c46f9bc426

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
