### ISSUE TITLE
Transferring items to a submarine with less containers/space may result in too many uncontained items, causing performance issues

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#11976]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

A player managed to have a fair quantity of items (Over 4000 potentially) on their submarine, mostly contained in lockers and containers that should have been able to handle them.

Noting that certain items that were thought to be in crates (Such as Moloch bones) appeared to leave the crates on changing submarines, alongside items in lockers were on the ground despite there being unused locker space available (Probably due to containable tags).

There is no warnings for when a submarine may be unable to contain the amount of items there is when switching, which can easily lead to severe performance issues when their all ejected onto the submarines floor after switching - and upon switching back they are not placed into containers either nor placed into existing crates that can handle them.

This save (which has 3 mods loaded, one is LUA but doesn't need it to run) is the aftermath of switching to a new submarine and then back with such an item count but not the most useful save for testing this:
[Too many items.zip](https://github.com/Regalis11/Barotrauma/files/11439425/Too.many.items.zip)

Though mods were active, I don't think the 2 item mods strictly caused the problem for this (As they appeared to add containers for sorting and then override those containers/a few items and tweak items to be stored in the containers, it didn't look out of date but is worth mention).

### Reproduction steps

1. start with a decent sized submarine for storage (IE. camel)
2. Have a considerable amount of items, crates and such (Such as a fairly full camel in every container) that is varied beyond what the containable tags on another submarine may have (IE, have too many oxygen tanks and diving equipment that the diving containers on a specific submarine cannot handle, or too much medical).
3. add a few other items such as a crate with moloch bones inside.
4. Buy and switch to a new submarine
5. Find most items may be on the ground (due to lack of containable space or tags)
6. Switch back (IE. camel had an empty locker on this), find they are not stored in containers/lockers as you would expect despite available space.

### Bug prevalence

Happens every now and then

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@ed05ddf by changing the default value of CargoContainerIdentifier from an empty string to "metalcrate".

The items should be thrown on the floor only when a) there's no valid _primary_ container found and b) when they can't be placed inside a crate. We haven't defined cargo containers for all items (that can't be bought), which was at least one cause for the issue.

Let's see if it's enough.

**Comment by Jasontti** [comment]
Tested.
All seems to be working. Didn't find anything out of place. No item's were dropped on floor, if there was space in containers.
Closing ticket.
