### ISSUE TITLE
Headset channel resets to 0 between multiplayer rounds

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11971]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Headset channel resets to 0 between multiplayer rounds

### Reproduction steps

1. Start a multiplayer campaign
2. Set radio channel to something else than 0
3. Leave from the outpost (or enter the next outpost)
4. Notice the channel has gone back to 0

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f640dd6afc92a8f26d6b3beb59f76e7d689d7597

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
