### ISSUE TITLE
Can't save a sub file that contains more than one other sub, duplicate IDs

### ISSUE THREAD

**Issue by soeinfach** [Regalis11/Barotrauma#11986]
Steps to reproduce:
1. In the editor, create two different subs that are just a docking port
2. Create a third file (can be empty)
3. Save the file
4. Open the file again. An error message appears:
"The submarine contains entities with duplicate IDs ((-1),(-1)) - the file may be corrupted. Do you want to attempt to fix the issue by deleting (-1)?"

By clicking yes, one of the subs gets deleted. Loading without getting an error message is only possible if the main sub was saved with only a single sub added.
Edit: No items are needed to reproduce, all 3 files can be empty.

**Comment by Regalis11** [comment]
Thank you for the report!

I was able to reproduce the error message, but I couldn't see any issues with _saving_ the sub. The submarine seems to get saved and loads normally as long as I answer "no" to the error message.

**Comment by Regalis11** [comment]
Fixed the error message in https://github.com/Regalis11/Barotrauma-development/commit/02898242bcea2356b9837fde698f6125aa55c3f8 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
