### ISSUE TITLE
Attached shuttles/drones are irreparable after being damaged and retrieved in multiplayer until you reload the save

### ISSUE THREAD

**Issue by Metallix203** [Regalis11/Barotrauma#11988]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Retrieving a drone after it has been damaged makes any damage taken irrepairable until you reload the save. Hulls cannot be repaired with the welding tool, but devices can. Noticed with a modded submarine and tested in vanilla with the Kastrull. 

### Reproduction steps

1. Start a multiplayer campaign with the Kastrull or any submarine with a drone
2. Leave the first outpost
3. Damage and then release your drone
4. Return to the outpost, pay to replace your shuttles
5. Enter a mission and attempt to repair your drone
6. Fail to repair your drone, then reload the save
7. Successfully repair your drone

### Bug prevalence

Happens regularly

### Version

v1.0.13.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The drone should get automatically repaired when you opt to replace it. I suspect the issue here is that the clients aren't aware the drone is actually fully repaired, and when they try to repair it, nothing happens (because the server thinks the client is welding an already repaired wall). I'll look into addressing it!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cf73338076d1e51b1f0219bb8296cae8b5d61369 (commit in our private repository)

**Comment by Jasontti** [comment]
Tested and works.
Replacing drones give fully repaired one.
Closing ticket.
