### ISSUE TITLE
AI gets stuck trying to operate gun on Herja

### ISSUE THREAD

**Issue by carmph342** [Regalis11/Barotrauma#11983]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On the Herja, I have an AI crew member set to operate a Coilgun which I bought from a hardpoint that is on the bottom right of the submarine. However, this ai gets stuck walking in place in the room next to the gun, and I have to fix it by controlling him and moving him into the gun room. 
Ignatius May is the stuck crewmember in this photo:
![image](https://github.com/Regalis11/Barotrauma/assets/131488247/d1f95a0c-3a35-4847-9fac-296e2116691b)

### Reproduction steps

1. Go into solo campaign
2. Buy herja
3. Buy a gun for the hardpoint
4. Ask a crew member to man said gun
5. Keep undocking from outpost until they spawn in the bottom of lower mid
6. Observe 

### Bug prevalence

Happens every now and then

### Version

v1.0.13.1

### -

This has happened in both the newest version, and the one before that.

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't get this to occur at my end; the bot seems to have no trouble navigating to the periscope. Is this a save file you started in some previous version (i.e. before yesterday's patch) by any chance? If that's the case, the sub file might be outdated, and missing some of the waypoint fixes we did in the patch.

**Comment by carmph342** [comment]
The save file was started in the previous version to the newest one, but it has happened in the new version too.

**Comment by Regalis11** [comment]
In that case it seems likely the issue is due to the submarine being outdated. Unfortunately the changes to submarine files don't carry over to existing campaign saves (a problem we need to figure out some solution to). :/
