### ISSUE TITLE
Solo Mode- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1198]
Solo Mode is a optional single player option granting player the ability to start the game with just 1 character without firing everyone else upon start. The player can set the following things for his character:

* Role

* Gender

* Face

* Name

* Trait

The player can also optionally select for his character a option to start the game with maximum values of randomly set skills possible for a character so he doesn't have to count for an (in this case) annoying  RNG feature to assist him. Captain would have 80 helm skills while other jobs would have 20. 

Orders are disabled since there is no need for them but player still starts the game with headset.

Lastly hiring crew members in this mode is disabled for good.

The main purpose of all of it is to increase immersion level for challengers who prefer to finish the game completely alone by creating protagonists they consider to be charismatic.

Characters for solo mode can be shared on steam workshop with their own bio.

#542 I know I reported it here already but in this thread (you currently read) it is much more expanded.

**Comment by Regalis11** [comment]
I don't really see the need for this. The game is designed around cooperation between multiple crew members, so I doubt the solo mode would be played by that many players. And those players who do want to challenge themselves by playing with one character can already do so by firing the rest of the crew.
