### ISSUE TITLE
Invalid ID tag or spawn point on Herja

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#11996]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Invalid ID tag or spawn point on Herja. Guess the editor stared at medcab and forgot what he want to do.
Spawn point type must be medic.
ID tag must be id_medic instead of id_doctor. Otherwise players can face with access troubles on other vanilla subs.

![image](https://github.com/Regalis11/Barotrauma/assets/17722887/b054decb-7480-4077-9758-ec3d37624698)

### Reproduction steps

1. Open sub editor
2. Check the Herja

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

> Otherwise players can face with access troubles on other vanilla subs.

This shouldn't be the case - when you switch subs, you get the ID card tags for that sub. But I fixed this regardless, it's better to be consistent. Commit in our private repo: https://github.com/Regalis11/Barotrauma-development/commit/3bc16992a033d28ccebda840ab635ca4a8fdb109

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
