### ISSUE TITLE
Oxygen Tank Drains When Used by Dead People- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1199]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dead characters are still draining oxygen tanks inside equipped diving suits and diving masks.

**Steps To Reproduce**
1. Have a person take diving suit.
2. Have a person equip welding fuel tank (drains welding fuel even when dead).
3. Wait for person to die.
4. Change welding fuel tank to oxygen tank.
5. Change oxygen tank to oxygenite tank to notice it works with both.

**Version**
0.8.2.3

**Additional information**
Affect also unconscious characters.

**Comment by rico6822** [comment]
It is also important to note that in real life some people breath while being unconscious and some not.

**Comment by rico6822** [comment]
It is also important to note that in real life some people breath while being unconscious and some not. Those who not breath are closer to death.

**Comment by Regalis11** [comment]
Fixed in the dev version (not visible in the public repo because the changes are in the Content folder).
