### ISSUE TITLE
OnBroken Conditional does not apply to dead plants, what other options are there?

### ISSUE THREAD

**Issue by phillipinman** [Regalis11/Barotrauma#11995]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Hi, 

First love your game, I've had tremendous fun with it.

While creating a mod, but not using any other mods, I am trying to do a status effect conditional to check if a planted plant in a vanilla planter is dead or not.

Essentially what I am trying to do is this on the custom plant seed with a vanilla planter:

      <StatusEffect type="OnBroken">
        <Remove/>
      </StatusEffect>

Unfortunately the dead plant is not removed when it is dead/broken.

Tweaking the planter to show it's inventory I can see the seed remains after the plant has died and assume this is by design for the dead branch sprites to show.

My Question: Is the dead plant meant to trigger an "OnBroken" event or is this by design?

If this is not a bug per say feel free to close it straight away, but I am unsure how I would detect if a plant is dead if the item inside never breaks.

Many Thanks!

### Reproduction steps

1. Setup a Vanilla Planter
2. Create a custom Seed with:      
 <StatusEffect type="OnBroken">
   <Remove/>
</StatusEffect>

3. There appears to be no way to detect if the plant is dead or alive for conditional checks.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

"OnBroken" effects can't be used for this purpose because the plant isn't technically "broken" (at 0 condition) when it's dead. It should be possible to use a Conditional instead:

```
<StatusEffect type="OnActive" target="this">
  <Conditional Decayed="true"/>
  <Remove/>
</StatusEffect>
```

**Comment by phillipinman** [comment]
Thanks heaps :D

**Comment by phillipinman** [comment]
For the record this conditional didn't work in my case, the wilted plant remained and doesn't get removed but I found another work around that doesn't use <Conditional Decayed="true"/>.

Instead I have the <ProducedItem> do the action I need and while less than ideal it works. It means the plant does not continue to do its StatusEffect which is triggered "OnContained", hence why I was hoping to remove the wilted plant from the planter, to stop the effect from continuing to trigger when it's dead.

I removed everything but the <Growable> and <StatusEffect> tags to confirm it wasn't related to conflicting <StatusEffect> tags.

Just leaving notes for others that might be interested in this, I'm happy to leave this closed, again thank you for your time :)

**Comment by Regalis11** [comment]
Ah, you're right, should've tested my example snippet before posting it. 😅 It seems "Decayed" isn't a public property that could be checked by Conditionals. There's no reason for it to not be though, so I'll go ahead and change that for the next patch.

**Comment by phillipinman** [comment]
Amazing, Thank you. :D
