### ISSUE TITLE
Uploading a git-initialized mod prevents you from uploading other mods unless WorkshopStaging is cleared

### ISSUE THREAD

**Issue by arden-arteles** [Regalis11/Barotrauma#11997]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Attempting to upload a mod that is being developed with `git` will work fine initially, but trying to upload any mod after that will fail with the below error log.

Resolving this was possible by using `rm -rf .git` (MinGW) from the WorkshopStaging directory.

Short-term workarounds:
* Remove the .git directory before uploading. Either move it to the LocalMods folder and return it, or delete it and re-clone the repository, after uploading.
* Remove the .git directory from WorkshopStaging after uploading. This would still mean that end users get a .git directory with their mod, so it's not the optimal solution.

Long-term solutions:
* Ignore any directory or file in the mod folder starting with a `.`. This would line up with common naming conventions.
* Account for git, and not upload the .git folder, while also supporting .gitignore in the upload process, ignoring the selected files.

### Reproduction steps

1. Initialize a git repository in a local mod folder. Add an initial commit.
2. Upload the local mod to the workshop.
3. Attempt to upload another local mod to the workshop. This will fail with the below message.

### Bug prevalence

Every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to create staging copy: Access to the path 'insert commit here' is denied.
  at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
  at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
  at System.IO.Directory.Delete(String path, Boolean recursive)
  at Barotrauma.IO.Directory.Delete(String path, Boolean recursive)
    in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SafeIO.cs: line 315
  at Barotrauma.Steam.SteamManager.Workshop.DeletePublishStagingCopy()
    in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Steam/Workshop.cs: line 158
  at Barotrauma.Steam.SteamManager.Workshop.CreatePublishStagingCopy()
    in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Steam/Workshop.cs: line 175
  at Barotrauma.Steam.MutableWorkshopMenu.PublishItem(GUITextBlock currentStepText, GUIMessageBox messageBox, String modVersion, Editor editor, ContentPackage localPackage)+MoveNext()
    in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Steam/WorkshopMenu/Mutable/PublishTab.cs: line 492
  at Barotrauma.Steam.MutableWorkshopMenu.MessageBoxCoroutine(Func`3 coroutine)+MoveNext()
    in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Steam/WorkshopMenu/Mutable/PublishTab.cs: line 408
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/10b38755a98d4dd9e8369e66d5431c0c0b23e07b (commit in our private repo) by making the game ignore files/folders starting with a `.`.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/53079d7e0b8fe282eb2f288916fb5605f3dc39a6

**Comment by Jasontti** [comment]
Tested.
Publishing to workshop ignores . prefixed files and folders, even in sub folder.
Closing ticket.
