### ISSUE TITLE
Game screen goes completely black at start of round, but game itself is still responsive.

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11994]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After this patch, when I start a new round, sometimes strangely the game screen would go completely black, but I can still see my inventory, job icon, crew list etc. and I'm still in my sub, being able to use items, move my character and behave normally, it is only that I can not visually see what is happening in the game.

I play heavily modded game, I am not sure if it's a mod problem, it never happened before.
![20230511124022_1](https://github.com/Regalis11/Barotrauma/assets/44329789/a38a1381-6e33-40ac-8e3d-8cbde539d453)
![20230511124021_1](https://github.com/Regalis11/Barotrauma/assets/44329789/8babc3b4-c355-4885-853b-2a5dce18b2fb)

The .save file is here, I use Dynamic europa, Robo-trauma, Lua and many other mods.
[New Hope_CharacterData.zip](https://github.com/Regalis11/Barotrauma/files/11456297/New.Hope_CharacterData.zip)

### Reproduction steps

1. start a campaign
2. dock the sub
3. start of round, game screen go black but game itself is still responsive

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by AzureNocte** [comment]
I varified my game file, problem solved. Could be that it is caused by corrupted files.

**Comment by AzureNocte** [comment]
This issue happened again, I uninstalled all the mods, it's still there, video here.
[https://youtu.be/zOlomNB2hhU](url)
Multiple saves occur this issue, so probably not relating to map seeds.

**Comment by AzureNocte** [comment]
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Simplified Chinese

System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

**Comment by AzureNocte** [comment]
Error while reading a message from server. 
Exception thrown while reading segment EntityPosition at position 4328. Previous segments: Segment { Identifier = SyncIds, Pointer = 32 }, Segment { Identifier = EntityPosition, Pointer = 185 }, Segment { Identifier = EntityPosition, Pointer = 424 }, Segment { Identifier = EntityPosition, Pointer = 656 }, Segment { Identifier = EntityPosition, Pointer = 840 }, Segment { Identifier = EntityPosition, Pointer = 1024 }, Segment { Identifier = EntityPosition, Pointer = 1208 }, Segment { Identifier = EntityPosition, Pointer = 1392 }, Segment { Identifier = EntityPosition, Pointer = 1576 }, Segment { Identifier = EntityPosition, Pointer = 1752 }, Segment { Identifier = EntityPosition, Pointer = 1936 }, Segment { Identifier = EntityPosition, Pointer = 2120 }, Segment { Identifier = EntityPosition, Pointer = 2304 }, Segment { Identifier = EntityPosition, Pointer = 2488 }, Segment { Identifier = EntityPosition, Pointer = 2672 }, Segment { Identifier = EntityPosition, Pointer = 2856 }, Segment { Identifier = EntityPosition, Pointer = 3040 }, Segment { Identifier = EntityPosition, Pointer = 3224 }, Segment { Identifier = EntityPosition, Pointer = 3408 }, Segment { Identifier = EntityPosition, Pointer = 3592 }, Segment { Identifier = EntityPosition, Pointer = 3776 }, Segment { Identifier = EntityPosition, Pointer = 3960 }, Segment { Identifier = EntityPosition, Pointer = 4144 }
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 162
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.ReadRangedSingle(Single min, Single max, Int32 bitCount) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 211
   at Barotrauma.PetBehavior.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\PetBehavior.cs:line 469
   at Barotrauma.Character.ClientReadPosition(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 273
   at Barotrauma.Networking.GameClient.<>c__DisplayClass119_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2140
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296

**Comment by AzureNocte** [comment]
I can not even use console command at the start of round, it says invalid cursor position.
![20230514180715_1](https://github.com/Regalis11/Barotrauma/assets/44329789/a8a41173-682e-4a38-8d18-2690b6fb0ebb)

**Comment by AzureNocte** [comment]
I tried reinstall the game, and change language to english, one of the saves did return normal, but others are still in this black fog...

**Comment by AzureNocte** [comment]
I finally figured it out!!!!!
This is caused by some explosions near the character at the start of the round, if the explosion is defined as showeffects="false" or abilityexplosion="true", preventing the character from seeing anything.

**Comment by Jasontti** [comment]
Thank you for the report, but i can't reproduce this.
Tried with different explosions and modifying explosives.xml to UEX to have showeffects="false", but to no effect.

If you have any saves or pictures that might help, please post them here.

My test setup was like this. Detonator triggered instantly when sub was loaded.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/0a926373-6347-4743-92d4-8dab32fe7baf)

**Comment by Regalis11** [comment]
No known steps to repro
