### ISSUE TITLE
Home screen patch notes button shows incorrect version

### ISSUE THREAD

**Issue by RooneyRoll** [Regalis11/Barotrauma#12009]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Home screen patch notes button shows different version (1.0.13.1) than the current (1.0.13.2).

![1](https://github.com/Regalis11/Barotrauma/assets/26443214/aa81829b-8126-4ab2-85cd-1c7344af8975)
![2](https://github.com/Regalis11/Barotrauma/assets/26443214/84a29dc4-70cd-4d4b-9384-793cb44c06a0)

### Reproduction steps

Visit the home menu.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional: we generally display the changelog for the last major patch/update, not the latest hotfix (which is usually just one or two fixes that aren't really as useful or interesting to know about than the list of recent major changes).
