### ISSUE TITLE
UGM loot chance without Gene harvester talent

### ISSUE THREAD

**Issue by RooneyRoll** [Regalis11/Barotrauma#12007]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unidentified genetic material (UGM) is not dropped from creatures upon death without "Gene harvester" talent. I know that the talent gives 20% additional chance of UGM loot drops. Without the talent I've fought lots of creatures and haven't seen a single UGM. Maybe there is something with the loot chance.

### Reproduction steps

Kill lots of crawlers.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by goder5555** [comment]
This is how it is intended. You will not be able to harvest genes without the talent. It doesn't add a 20% _additional_ chance, it adds a 20% chance to harvest them.

**Comment by RooneyRoll** [comment]
Ohh... Sorry and thank you for the info!
