### ISSUE TITLE
Bots attempt, but unable to heal minor wounds

### ISSUE THREAD

**Issue by Arctomachine** [Regalis11/Barotrauma#12005]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After recent update bots now have opposite problem of #11477 
When player controlled character has minor wounds, medic bots attempt to apply healing. But they stop at just reporting their intention and never heal, just standing near player and keep reporting.
If player switches to another character, medic loses any interest in wounded and goes elsewhere.
![image](https://github.com/Regalis11/Barotrauma/assets/29041820/fe0e4596-6967-4170-99c0-6c29c138e50c)

Possible solutions to this problem:
1. Make them ignore minor wounds on player controlled character
2. Make them use the least potent of available medicines if they insist on healing scratches and bruises

### Reproduction steps

1. Give bot a medic task
2. Take slightly wounded character under control
3. Medic bot now follows controlled character everywhere, repeatedly reports intention to heal, task icon is highlighted (active)
4. Switch to another fully healthy character
5. Medic bot stops following wounded character, task icon returns to normal state

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This doesn't actually seem to be a new issue (we didn't do changes to this logic in the latest patch - https://github.com/Regalis11/Barotrauma/issues/11477 didn't make it in).

Addressed the issue in https://github.com/Regalis11/Barotrauma-development/commit/4e83b367a11eb08612d329e929e53950a29595e4 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
