### ISSUE TITLE
AI reload ammo command ignores containable restrictions

### ISSUE THREAD

**Issue by Veylyn** [Regalis11/Barotrauma#12004]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing a sub from the sub editor and trying to get AI to only fill a railgun loader with canister shells, giving one of the crew the Reload Ammo order had them refilling railgun loaders with any railgun ammo, despite the Containable Restrictions field being only "railguncanistershell" and canister shells being available. In testing, the AI seemed to use railgun shells exclusively until none were available before loading the canister shells as wanted

### Reproduction steps

1. Load a sub with a railgun in the sub editor
2. Set the containable restrictions field for the railgun to loader to the identifier for one specific railgun shell type (nuclearshell, railgunshell, or railguncanistershell), this seems to happen reliably at least with railguncanistershell
3. Have a mix of shells available on the sub
4. Open test mode, and give one crew member the Reload Ammo order. Railgun loader will be loaded with any valid railgun ammo, and not just according to the containable restrictions (or even prioritizing the containable restrictions tags)

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/eb4f3f2f77843b9cfc2c11d78f68f5eba7d10afb (commit in our private repo)

**Comment by Jasontti** [comment]
Tested. containershell and railguncanistershell tags in containable will cause AI crew to prioritize those first, but not exclusively only those, to be loaded. Tested with container shells on racks with mix of shells and scattered around the sub.
