### ISSUE TITLE
Flashlight requires a specific kind of light component for its fabrication recipe

### ISSUE THREAD

**Issue by goder5555** [Regalis11/Barotrauma#12006]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The flashlight's fabricator recipe requires the horizontal light component instead of being able to use all three types. See attached image
![flashlight](https://github.com/Regalis11/Barotrauma/assets/112526059/87170c41-7210-452b-93ec-648f34ff153d)

### Reproduction steps

1. Try to fabricate a flashlight with any kind of light component other than the horizontal one
2. Fail

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f0b9dbee20caef250a7d543291e939f2b5d31871 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
