### ISSUE TITLE
Lights shine through the items characters are holding

### ISSUE THREAD

**Issue by Attackmelon** [Regalis11/Barotrauma#12014]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Accordion item was translucent while I was playing the game.

### Reproduction steps

![20230515203926_1](https://github.com/Regalis11/Barotrauma/assets/133721906/debfbb46-72f2-47d9-83d4-91ae18a91e2c)
![20230515203938_1](https://github.com/Regalis11/Barotrauma/assets/133721906/f079b70f-24b8-400b-86f2-6cde8a147070)
![20230515203942_1](https://github.com/Regalis11/Barotrauma/assets/133721906/70246553-f61a-48cd-b39f-5a3ee1d1fb83)
Some photos showing the Accordion translucent

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Addressed in https://github.com/Regalis11/Barotrauma-development/commit/981741a54abd2627ab6d4aec0a0b97df52e36636 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
Working and closing ticket.

**Comment by Regalis11** [comment]
Causes contained items (e.g. tanks in tools) to glow, reopening
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/1d1615be-11c8-4409-acbb-b2a07422a1fd)

**Comment by giists** [comment]
No issues found, closing.
