### ISSUE TITLE
Talent "Rifleman" does not increase the damage of assault rifle as intended.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12015]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Due to the tag `riflemanbonus` being defined on `Assault Rifle Magazine`, the talent won't affact damage of assault rifle.
It should be defined on `Assault Rifle Round` instead.

### Reproduction steps

1. shoot something with an AR
2. give yourself `rifleman` talent
3. shoot with the AR again and notice the damage not being increased

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/commit/06f6b81ff7f606ab159cfbc5af76560ab3231973, seems to be fixed now.
