### ISSUE TITLE
Abandoned stations have a block with no ambient lighting, and it sticks out

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12016]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Going off memory here, no screenshots. Walked through an abandoned station and there was a narrow horizontal block that was unusually dark.

Checking the station modules in the editor I think it's `hallmodulehorizontal_abandoned`, the hull's ambient level is unset.

A quick check on every hull in the Content/Map/Outposts directory, these modules have hulls with no ambient. Probably not all of them are as ugly:

```
     10 AdminModule_01_Colony.sub:
      8 AdminModule_02_Colony.sub:
      6 ArmoryModule_01_Colony.sub:
      1 DockingModule_02_Colony.sub:
      3 DockingModule_02.sub:
      7 EngineeringModule_01_Colony.sub:
      6 EngineeringModule_02_Colony.sub:
      1 HallModuleHorizontal_Abandoned.sub:
      3 HuskDistrict_Colony_01.sub:
      5 MedicalModule_01_Colony.sub:
      5 MedicalModule_02_Colony.sub:
      3 ResearchModule_01.sub:
      3 ResearchModule_02_Colony.sub:
      3 ResearchModule_02.sub:
     21 ResidentialModule_01_Colony.sub:
      2 SecurityModule_01_Colony.sub:
      4 SecurityModule_02.sub:
```

### Reproduction steps

Walk around an abandoned station until you come across an unusually dark square that swallows all light.

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/68995233/ff1f241f-e7ec-4326-a61c-720e3b695b11)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/664226db1c3fa78b116aa23a63bafc341f586413
