### ISSUE TITLE
[Unstable] Fabrication filters missing items

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#12025]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a bit of a larger report of overall items being in the wrong filters, or just missing from appropriate ones, so heres a list of the ones i noticed:

**Medical Fabricator:** 

_Weapons:_
-Sulphuric Acid Syringe should almost certainly be in the "Weapons" category
-Europabrew could probably also profit from being part of the weapons category
-(Not necissarily needed, but poisons should probably considered weapons aswell, though thats up to you)

**Fabricator:**

_Machines:_
-Machine tab is missing the Defense bot, only has the portable pump
-(Possibly could use the Makeshift shelves here? Since their use as being installed in the ship is like the portable pump) 

_Materials:_
-Rum is part of the material tab for some reason, not like it can be used for other recipes
-Depleted fuel is not considered as part of the material tab

_Fuel:_
-Depleted fuel is considered fuel in the fuel tab, though its never used as actual fuel

_Diving:_
-Diving tab doesnt have the Funbringer 3k
-Diving tab doesnt have the Slipsuit
-Diving tab doesnt have the Handheld sonar
-Diving tab doesnt have the Sonar beacon

_Weapons:_
-Defense bot ammunition is not part of the weapons tab (or the Machine Tab) unlike all other ammo

Incase anyone else notices missing items in categories, it probably helps to comment it here, i guess

### Reproduction steps

1.Refer to the new tab categories in the fabricator (or the sub editor for that matter)

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1f9e017a380db0c17f23f0985cf951eb8465bbe
