### ISSUE TITLE
Buying toolbelts forces empty metal crates to spawn

### ISSUE THREAD

**Issue by TheUnluckyMedic** [Regalis11/Barotrauma#12029]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While buying some toolbelts for my crew, I discovered that buying toolbelts spawned a metal crate for each toolbelt bought, probably to store it inside, even though toolbelts cannot be stored inside them.

### Reproduction steps

1. Go to an outpost that sells toolbelts (even better if on sale);
2. Buy them;
3. Enter a mission so that your supplies spawn at cargo;
4. Go to cargo;
5. Metal Crate party.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ca203b7f2733c149b37964803b70e731d743b55c

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
