### ISSUE TITLE
The game close when I click main menu in Submarines-editor

### ISSUE THREAD

**Issue by zelda0079** [Regalis11/Barotrauma#12021]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game close when I click main menu in Submarines-editor.

### Reproduction steps

1. Lanuch game, go to Submarines-editor. (Sorry I use chinese version, so maybe it is not called Submarines-editor)
2. Click upper left corner "Back" or ESC-> main menu.
3. The game sometimes close.
4. If the game is not close, I click Submarines-editor again, it close.

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Cannot find crush report.
```

**Comment by zelda0079** [comment]
MOD LIST

<regularpackages>
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2559634234/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2795927223/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2701251094/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2807158602/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2811300302/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2592748017/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2920200449/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891181800/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2950383008/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2251324465/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2916504564/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2799051561/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2893818941/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2641013166/filelist.xml" />
    </regularpackages>

**Comment by zelda0079** [comment]
<package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2559634234/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2795927223/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2701251094/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2807158602/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2811300302/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2592748017/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2920200449/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2891181800/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2950383008/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2251324465/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2916504564/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2799051561/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2893818941/filelist.xml" />
      
      <package
        path="C:/Users/wengleong/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2641013166/filelist.xml" />

**Comment by Regalis11** [comment]
Thank you for the report!

I haven't heard of this happening before and haven't encountered it in the vanilla game, so I would suspect it's caused by some of the mods. We'll keep an eye out for the issue though and see if we encounter it or find a way to reproduce it. Sorry for the inconvenience!

**Comment by zelda0079** [comment]
> Thank you for the report!
> 
> I haven't heard of this happening before and haven't encountered it in the vanilla game, so I would suspect it's caused by some of the mods. We'll keep an eye out for the issue though and see if we encounter it or find a way to reproduce it. Sorry for the inconvenience!

I am not confirm, maybe some mod which is not enable but it affect the game, beacuse I try these 2 mods
https://steamcommunity.com/sharedfiles/filedetails/?id=2887170458
https://steamcommunity.com/sharedfiles/filedetails/?id=2905375979
and then I disable these 2 mods, I still can use "R" key to reload ammo, some mods which are disable but affect the game.

**Comment by zelda0079** [comment]
> Thank you for the report!
> 
> I haven't heard of this happening before and haven't encountered it in the vanilla game, so I would suspect it's caused by some of the mods. We'll keep an eye out for the issue though and see if we encounter it or find a way to reproduce it. Sorry for the inconvenience!

How I find the crash report? I try to search and it shows this is output.log in game folder, but I cannot find it, so it is not crash, right?

**Comment by zelda0079** [comment]
I installed both client and server LUA,
https://github.com/evilfactory/LuaCsForBarotrauma/releases/tag/latest
[luacsforbarotrauma_build_windows.zip](https://github.com/evilfactory/LuaCsForBarotrauma/releases/download/latest/luacsforbarotrauma_build_windows.zip)

**Comment by zelda0079** [comment]
I

> Thank you for the report!
> 
> I haven't heard of this happening before and haven't encountered it in the vanilla game, so I would suspect it's caused by some of the mods. We'll keep an eye out for the issue though and see if we encounter it or find a way to reproduce it. Sorry for the inconvenience!

I know the reason, I verify the game file, do the above step->no crash
install server LUA, [luacsforbarotrauma_build_windows.zip](https://github.com/evilfactory/LuaCsForBarotrauma/releases/download/latest/luacsforbarotrauma_build_windows.zip), do the above step->no crash
https://steamcommunity.com/workshop/filedetails/?id=2559634234
install client-side LUA, do install_cl_lua, do the above step->crash

**Comment by zelda0079** [comment]
Finally, I find the reason, bug from this mod.
https://steamcommunity.com/sharedfiles/filedetails/?id=2950383008

**Comment by shangjiaxuan** [comment]
@zelda0079 I have updated comment on that issue. It crashes on `clrjit.dll` which is part of the .net runtime. It looks like a bug in harmony (c# mod loading framework used in luacsforbarotrauma), or a bug in .net runtime. I don't know if I could fix that as a modder. The crash does not happen if you have entered the game for at least once.
