### ISSUE TITLE
[Unstable] Lights sometimes shine through doors

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12026]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Lights can sometimes shine through the bottom of a door, as if the door was still slightly open:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/e517fa5a-e05f-42a3-9d6b-6fbb271c2925)

### Reproduction steps

1. Drop a flashlight on the floor pointing at a door
2. Repeatedly open and close the door until the issue occurs (usually doesn't take that many tries)

### Bug prevalence

Happens regularly

### Version

Other

### -

v1.0.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
