### ISSUE TITLE
[Unstable] mining no worky

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#12028]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

trying to mine with plasma cutter/ancient weapon doesn't work in the unstable version

### Reproduction steps

go to ore, equip plasma cutter, use plasma cutter on ore, it don't mine.

### Bug prevalence

Happens every time I play

### Version

v1.0.15.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e0a7f31c9b137001044cbbffcb7b51395c569d77

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
