### ISSUE TITLE
Penetration set in RangedWeapon doesn't seem to have any effect

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#12027]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The SMG has `penetration=0.15` set in its RangedWeapon segment but this doesn't seem to have any effect as changing the value doesn't make a difference in the inflicted affliction amount on armored characters.
One SMG shot with penetration increased to 1:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/37affcb0-a494-48df-85f5-71a2f08eae1c)

### Reproduction steps

1. Compare affliction amount before and after increasing the SMG penetration

### Bug prevalence

Happens regularly

### Version

v1.0.15.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/01e9beb1b63053a6c499868b6ff462cc1228378e

**Comment by Jasontti** [comment]
Tested.
Changing penetration value works correctly.
Closing ticket
