### ISSUE TITLE
Some issues with Chinese localization

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12023]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Issue 1: Emergency Maneuvers description won't display duration because the localization text is `[duration]`, but the talent defines `[seconds]`
![issue_evasive_maneuvers](https://github.com/Regalis11/Barotrauma/assets/99462070/69881f54-b5fa-4216-8da8-c3eb55381468)

Issue 2: Mailman description says it grants you 150% money bonus(should be 150 mk instead)
![issue_mailman](https://github.com/Regalis11/Barotrauma/assets/99462070/27dfc48f-a4de-4fdb-9b7e-6ffbd8f0dfa9)

Issue 3: Buzzing and Cruising the description says they buff your engine. (should be reactor)
![issue_buzzing](https://github.com/Regalis11/Barotrauma/assets/99462070/097c0114-47f9-4110-a3b5-76f51b76216b)
![issue_cruising](https://github.com/Regalis11/Barotrauma/assets/99462070/ced8db4f-6289-4677-abc0-30a44e3135c7)

Issue 4: `Arc Emitter`, `Stun Gun` and `Stun Gun Dart` have exactly the same name. (should be "电弧发生器"，“电击枪” and “电击枪飞镖” instead)
![issue_same_names](https://github.com/Regalis11/Barotrauma/assets/99462070/470b79df-235f-493e-8857-61801032c4b2)

Issue 5: `Harpoon Gun` has weird name which literally means `Harpoon Gun Used for Harpoong Gun`
![issue_harpoongun_name](https://github.com/Regalis11/Barotrauma/assets/99462070/4d3eedac-a149-4b10-bc96-fbbdb8658d17)

Issue 6: `Cargo Scooter` has wrong translation name which literally means `Cargo Skating Board`
![issue_cargo_skating_board](https://github.com/Regalis11/Barotrauma/assets/99462070/8797e9e0-0b22-48d3-8280-0413bc3808f0)

### Reproduction steps

1. use Simplified Chinese

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you! I passed the report to the localization team.

**Comment by Regalis11** [comment]
These don't seem to have been addressed in the latest localization batch. :/ I'll poke the translators again when we submit the next batch.

**Comment by Regalis11** [comment]
These should now be fixed in the Treacherous Tides update.
