### ISSUE TITLE
"Nuclear blast survivor" Achievement is broken

### ISSUE THREAD

**Issue by zelda0079** [Regalis11/Barotrauma#12038]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Nuclear blast survivor
Complete a round after a nuclear meltdown.
Not Working.

### Reproduction steps

A
1. open a sandbox mode.
2. close my auto control, let fission rate to be max.
3. go outlside, the reactor melt down.
4. go back fix all things.
5. go to end.

B
1. Go to a beacon.
2. put fuel rod and let fission rate to be max.
3. go outlside, the reactor melt down.
4. go back fix all things, turn the beacon
5. go to end.

C
1. get a mission "Pirate Vessel"
2. break the enemy submarine and kill a enemy.
3. put fuel rod and let fission rate to be max.
4. go outlside, the reactor melt down.
5. go to end.

Cannot get the achievement "Nuclear blast survivor"

video
B https://youtu.be/V4gnoWlNYEI
1:54:26 let reactor burn
1:56:20 melt down
2:00:25 fixing
2:06:30 go to end

C https://www.youtube.com/watch?v=vcc_SI9MGns
51:25 let reactor burn
53:00 melt down
1:01:52 go to end

my profile
https://steamcommunity.com/id/zelda0079/stats/602960/achievements/

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no crash report
```

**Comment by Regalis11** [comment]
Thank you for the report!

This actually seems like a more severe issue, it seems achievements can't be unlocked at all on SteamP2P servers. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0832d5d8c52ee8ffd46041c07e7a4c1353ebbfb (commit in our private repo)

**Comment by zelda0079** [comment]
> Thank you for the report!
> 
> This actually seems like a more severe issue, it seems achievements can't be unlocked at all on SteamP2P servers. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0832d5d8c52ee8ffd46041c07e7a4c1353ebbfb (commit in our private repo)

For case b, I play solo, for case C, I play with my friend and I am not host.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
