### ISSUE TITLE
Custom Pirate Vessels wouldn't used in a campaign or in a mission

### ISSUE THREAD

**Issue by KrusteDE** [Regalis11/Barotrauma#12035]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I redesigned my custom sub (tier 3) to an pirate vessel for more variations. But it wouldn't shown up in the campaign in missions or on servers with just the mission "Pirate". I tried it multiple times and always got the Typhon 2 as a pirate vessel. I know the choice of the game for the submarine as a pirate vessel depends on the difficulty (i have set it on 100% (hellish)) and tried it over and over again. I spawned in and activated freecam to see the other submarine, but its always the Typhon 2. I want to try the next time to add also a wreck of my sub, but i'm also scared it wouldn't work too. I hope it get fixed or i get an better explanation why it wouldn't spawn. 

### Reproduction steps

[Big Kruste Pirate.zip](https://github.com/Regalis11/Barotrauma/files/11519574/Big.Kruste.Pirate.zip)
1. Start a private server
2. select mission
3. select pirate
4. set on hellish (100%) difficulty
5. enablecheats
6. start round 
7. command "freecam"
8. watch which pirate vessel is spawned
9. if typhon 2 end round
10. repeat at step 6 

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! The pirate subs used in a missions are defined in the mission itself, so you need to add a custom mission too if you want your custom sub to be used.

**Comment by KrusteDE** [comment]
thank you for your reply :)

**Comment by KrusteDE** [comment]
how do i create custom missions?
