### ISSUE TITLE
Characters let go of the character they're dragging when moving out of the sub

### ISSUE THREAD

**Issue by zelda0079** [Regalis11/Barotrauma#12039]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

1. bot try to kill terrorist who are under controlled.
2. locked terrorist does not want to go outside.
3. locked terrorist is hard to control.

### Reproduction steps

1. go to a beacon.
2. let terrorists stun, lock them.
3. bring a terrorist go to outside.
4. bot use cannon attack us.

I also have other question.
1. (bug or design?) locked terrorist does not want to go outside, it hard to bring them go out from beacon.
2. (bug or design?) locked terrorist is hard to control, I need to keep them sturn to bring team to my submarine.

video https://youtu.be/V4gnoWlNYEI
2:30:16 bot try to kill locked terrorist
2:31:05 locked terrorist does not want to go out side
2:33:47 It is hard to control locked terrorist expect you let him/her stun.

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The first issue has already been reported, and the third one is not a bug. Fixed the 2nd issue in https://github.com/Regalis11/Barotrauma-development/commit/79e507a14b1bd343ca13bf4dcfc5fbddcee8a3fd (commit in our private repository).

**Comment by Jasontti** [comment]
Tested.
Dragged conscious and paralyzed crewmember between sub - ocean, sub - outpost, outpust - ocean and shuttle - sub.
No issues found.
