### ISSUE TITLE
Black market seller didn't give me the item I bought

### ISSUE THREAD

**Issue by JerryDelsey** [Regalis11/Barotrauma#12042]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I bought a black market item for 1000 marks, that should have been some kind of alien artifact but it won't appear in my inventory nor on the floor

### Reproduction steps

Have an NPC sell a mysterious alien thing for 1000 marks

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

There's two possible outcomes to this event: there's a 1/3 chance you get an alien pistol, and a 2/3 chance you get nothing. 

![image](https://github.com/Regalis11/Barotrauma/assets/14351070/40832190-4995-4457-bdd1-5c510be49e31)

Do you by any chance remember what the event text said when you agreed to pay? Did it say you got a genuine alien pistol?

**Comment by JerryDelsey** [comment]
I don't remember since I skipped text maybe a bit quickly. That could be the answer, thanks for you very quick answer and sorry for the inconvenience
