### ISSUE TITLE
Hull is 'transparent' if crossing the wall.

### ISSUE THREAD

**Issue by Isamylov** [Regalis11/Barotrauma#12048]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the wall crossing hull part - the player can see content inside submarine, including the wall.

The hull shouldn't allow player to 'see' through it.

How it looks in the editor:

![Screenshot_1](https://github.com/Regalis11/Barotrauma/assets/109140990/6786cb6a-2947-4111-9fb9-57d9280b29a5)

How it looks in the game:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/ecb4711b-dc80-4e73-9cd4-e05643363c1e)
![image](https://github.com/Regalis11/Barotrauma/assets/109140990/62236ca9-3112-4776-87c5-b7d52c6c5d54)

If you hide the wall behind the hull, everything becomes great. The sprite depth settings don't solve the problem.

### Reproduction steps

1. Open submarine editor.
2. Place the wall and the hull together:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/336a91dc-56b9-4c82-b88e-05ddf70179c9)

3. Launch simulation.
4. You'll be able to see through the hull.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Most likely fixed by the upcoming LOS rework, but we'll give it a test and verify that's the case

**Comment by war3scv** [comment]
> Most likely fixed by the upcoming LOS rework, but we'll give it a test and verify that's the case

this is always the case mostly you even see through the wall, we just try to aviod this by adjust the wall, which usually cause that piece of shell harder to repair

![image](https://github.com/Regalis11/Barotrauma/assets/95470279/88f43c0f-a362-43e8-bd53-e3a21930d9dc)

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.0-patch-2 commit https://github.com/Regalis11/Barotrauma-development/commit/baf2d4b71b05a365354ecbeab42db0287ad329d5 (the upcoming patch / unstable)

Seems the upcoming LOS changes have fixed this issue, but there could be caveats that without testing on specific submarines will be difficult to know in advance, but may require some small adjustments to a submarine after the LOS rework is out (which I believe can be tested on unstable currently).

green lines are where the LOS stops you seeing further:
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/2099a82d-1d58-4553-85d3-6a6a2b46015b)
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/3f842607-d767-43b1-b962-c660ce56377a)
