### ISSUE TITLE
Applying a medal generated by the figurehead talent to a character while you do not have the Figurehead talent does not boost them to level 5

### ISSUE THREAD

**Issue by Dja303** [Regalis11/Barotrauma#12047]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have an assistant that got the figurehead talent using the graduation ceremony talent.
I took the medal off of him and tried to apply it to a freshly hired mechanic.
Instead of bringing the mechanic up to level 5 it merely granted them 550xp.

Still not quite sure if this is intentional or not, but it's still annoying because there''s no way to get the bot to apply the medal to another character and boost them to level 5, even if they have the figurehead talent.

### Reproduction steps

1. Start a multiplayer campaign.
2. Spawn an assistant
3. Grant the assistant the Graduation Ceremony talent using console commands
4. Restart from the previous save if the assistant did not receive the figurehead talent. Repeat step 3
5. Complete a mission to generate a medal on the assistant
6. Spawn a level 0 bot
7. Grab the assistant and retrieve the medal
8. Apply the medal to the second bot
9. Under the manage talents section of the tab menu you will notice the bot has only gained 550xp

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I would not really consider this a bug, it's intentional that the level boost is only gained if the character with the talent applies the medal.
