### ISSUE TITLE
You can fly by quickly clicking the ragdoll key multiple times in multiplayer

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12059]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some maps, this problem can easily breaks the rules of the game.
Our pvp server has 20+ players together to paly daily, but everyone learned to fly lol.
![fly](https://github.com/Regalis11/Barotrauma/assets/73634685/aff68d90-f597-4071-a8e3-167624140ec5)

### Reproduction steps

1. Levitate your body (there're many ways to do this, the easist way is stand on a platform and repeatly clicking the ragdoll key)
2. Quickly constantly click the ragdoll key
3. Your body will fly

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Seems like easily reproducible, but it's not: couldn't repro it while testing on a locally hosted game. We need to identify when this happens and if it's something we should and can fix. Moving to QA Investigates.

**Comment by zhu-rengong** [comment]
Maybe try to reproduce the problem in this way：1）join a dedicated server which only vanilla package enabled. 2）Try holding the rifle, aiming upwards, standing on the platform, holding down the s key, and then quickly repeatedly clicking the space key.

**Comment by Rokvach** [comment]
This was really simple to repro
1. Download the reprosub and unzip the flying room mod to LocalMods, or just build a big empty room with a platform.
[reprosub.zip](https://github.com/Regalis11/Barotrauma/files/12454545/reprosub.zip)
2. Host a server
3. Choose the flying room as your sub and start a round
4. Turn on godmode (so you don't suffocate as the sub doesn't have any air)
5. Stand on top of the platform and spam spacebar notice that your character starts levitating (using a rifle and aiming up seemed to make it easier to levitate but not necessary as it can be done even without it)

**Comment by Jasontti** [comment]
Tested.
Learned how to fly without the fix, could not find a way to do it again with the fix.
No issues found.
Closing ticket.
