### ISSUE TITLE
drunknodebuffs does not decay below 20

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12053]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Another affliction that doesn't decay, similar to #10045, and #10197, and also #12031 (also happened with Bloodloss but I don't know if there was a ticket for it.)

drunknodebuffs does not have any strengthchange defined for 0-20, so it'll stay at 19%. Interestingly, since no medical items reduce it and clinics can't treat hidden afflictions, drunknodebuffs literally cannot ever be removed.

Doesn't actually cause the effects of Drunken Sailor to persist forever (as in the case of #10045) because it needs to be above 20 to apply, but it does cause captains who have previously drunk ethanol or rum to more easily become drunk again.

### Reproduction steps

1. Edit the drunknodebuffs affliction so that it can be seen at all strengths
2. Give a character the ~25 affliction strength
3. Observe the affliction decay to 19.9983333333 (rounded down to 19 on the health scanner HUD) and not decay any further

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1ee0df88e6f16b264c9f023cdf16a30d64477a5

**Comment by Jasontti** [comment]
Tested and works properly.
Closing ticket.
