### ISSUE TITLE
Serious Mode- Feature Request [#1178]

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#1205]
Written by rico6822 in #1178

I'm aware that I already requested handicaps for increasing challenge level of barotrauma but recently I decided they are being pretty irregular and weird as well as I began to wander if they are being worth the effort.

This time I have decided that logisticians who want this game to be more challenging in the way making more sense deserve their own separate gamemode which I simply named "Serious Mode" being a hard mode for the game. It only has 1 weakness: Needs a lot of work and perhaps would delay development of the game if it had to be added before steam release of the game. It's better to pick on it after barotrauma gets released on steam and add it in the future update.

- [ ] Players can only see in front of themselves (direction their head is facing).

- [ ] Unconscious characters cannot see or hear as well as even their entire HUD is invisible to them. They will only be informed of their own personal deaths.

- [ ] Headshot instakills humans giving only 1,5% lucky chance to survive attack at default damage value.

- [ ] [Optional] Characters can suffer brain damage caused by shaking and head injury. It leads to psychosis.

- [ ] Eyes of humans upon injuring may cause sight issues.

- [ ] Vitality bars (both in healing HUD and above characters) are invisible unless Health Scanner HUD is equipped.

- [ ] [Optional] [Multiplayer] It cannot be said if someone passed out unless adequate medically person checks it or Health Scanner HUD is used. 

- [ ] No items can be taken orally while wearing diving suit or diving mask (can be edited in xml files).

- [ ] Too severe psychosis causes humans to lose health and eventually die.

- [ ] Wires may break if attached to them device needs fixing. They can be fixed.

- [ ] Hitting icy crust on top of the map is no longer non-destructive.

- [ ] [Multiplayer] Spectating players cannot see, hear or even see chat of the living. Spectating is only here for players to wait for respawn.

- [ ] [Multiplayer] Only players who haven't played a round yet (no in-game character is presented yet) can respawn giving every person just one chance.

- [ ] Music doesn't change when there is a monster nearby or when generator is out.

- [ ] [Optional] Music doesn't change in the abyss.

- [ ] Wearable items take some time to equip.

- [ ] Craftable items requiring skills to craft need adequate person to stay with them all the time during crafting.

- [ ] Crafting cannot be aborted.

- [ ] Crafting forcefully stopped by lack of power or person to operate results in items being dumped or exploding.

- [ ] Repairing devices takes some time.

- [ ] Water in the background of docking submarines floods inside.

- [ ] Mission label doesn't update the location of the objective.

- [ ] Mission labels are invisible on unpowered radar devices (sonar monitors and handheld sonars).

- [ ] There is no message on chat whenever mission artifact is on board or mission monster has been killed.

- [ ] [Optional] Humans need to eat. Passively they need to wait 8 hours before it happens but sprinting all the time makes it only take 40 minutes for a need to eat something.

- [ ] [Optional] Humans need to sleep. Passively they need to wait 12 hours before it happens but sprinting all the time makes it only take 1 hour for a need to sleep. Sleeping in the bed makes sleeping being satisfied faster meaning beds are interactable objects.

- [ ] A steam achievement for completing the game in Serious Mode.

- [ ] (If that was not enough) A steam achievement for completing the game in Serious Mode using unmodified in any way vanilla submarine and no mods. 

Yes, I know sleep and hunger are not being very well seen in here but if it is being featured in a optional gamemode why shouldn't it be given a try? 

#542

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
