### ISSUE TITLE
Old fabricator text still shows up

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12054]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After #11856 was fixed, the old fabricator texts just weren't removed from the game, so when opening the fabricator, the old and new texts can both show up.

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/361a0563-ec05-4c25-aee0-c8cfe4469300)

Affects `fabricatorsufficientskills` and `fabricatorinsufficientskills`.

### Reproduction steps

1. Open fabricator
2. See that old or new texts can show up

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9614ffad5d8b70ce23e1c471020aab6b5a9e8d2e
