### ISSUE TITLE
Duplicate implacable description text

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12066]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Similar to #12054, the `talentdescription.maxtriggeruntildeath` has two different texts, leading to the description sometimes being blatantly incorrect.

Seems to affect all languages.

### Reproduction steps

1. Read the description of implacable
2. Read it again on a different occasion and observe that it is sometimes not the same description

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b826f72c82ed616ae3a933e9fd3c8e8a1659a46f
