### ISSUE TITLE
[Unstable] Can't mine mission minerals

### ISSUE THREAD

**Issue by zeroinformatique** [Regalis11/Barotrauma#12060]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Testing the unstable version (very nice new light system!).

Everything seemed to work fine, until I wanted to mine minerals for a mission.
I took my Plasma cutter, swim to the shining minerals, blasted the cutter... but nothing happens.
Tried to switch it on and off, moved inventory slot, tried the Welder instead... nope! Can't mine minerals. It's broken.

This bug only occurs with **mission minerals**; not normal minerals.

### Reproduction steps

1. Start a campain
2. Take a "Mine something" mission
3. Try to mine it
4. No profit :<

### Bug prevalence

Happens every time I play

### Version

v1.0.15.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No error, it just does nothing, as if the minerals were not acknowledging the plasma cutter beam.
```

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
