### ISSUE TITLE
Can not add a new hair style that doesn't inherit origin, sourcerect from limb head

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12068]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While developing new content for [EA-HI]Animated Barotrauma, I encountered a problem that the hair sprite's sourcerect exceeded head limb of human. I tried defining a new hair style as the following:
```
<Wearable type="Hair" tags="female">
    <sprite name="Hair 38" texture="%ModDir:2809175631%/Content/Characters/Human/Human_female_hair_ark_1.png" inheritorigin="false" inheritsourcerect="false" origin="0.6083,0.3112" sourcerect="0,0,256,480 />
</Wearable>
```

The game seem to ignore the properties defiend here. I think this behavior is related to these code:
https://github.com/Regalis11/Barotrauma/blob/9470edead3ffebbcc3bef2e3a189793f9577c62b/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Wearable.cs#LL127C14-L127C14

### Reproduction steps

1. try creating a mod that adds a hair style that exceeded sourcerect of limb head of human

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/70be1a4251545ae13b3910114e72a809eb9d73fc

**Comment by BiffW** [comment]
Thanks for fix. It means a lot for developing this mod.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
