### ISSUE TITLE
Outpost module pathing broken on double door generation + unnecessary ladder in module deadend

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12079]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A city outpost generated with the following that had broken waypoints and oddly placed doors on the left side:
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/213f83d2-9f0c-476c-a1ac-3bfecbcef589)

The same city generates (very top left) a section with a ladder going nowhere, that I assume should only appear if there was a vertical hallway/room above generated:
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/162eb97b-fdfb-4409-b6af-a3a85c817d1c)

### Reproduction steps

1. use the level editor
2. Submarine: camel
3. Seed: Fi14Txkb
4. Outpost type to city
5. biome: coldcavernsoutpost

### Bug prevalence

Happens every now and then

### Version

v1.0.15.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f04b887df9a1e0db460b4100c0f40272e40aee0e and https://github.com/Regalis11/Barotrauma-development/commit/44f64e3c230fb7fc6dd61aba85a2a5aa9e407251

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4952863
