### ISSUE TITLE
Buff duration talents' descriptions aren't clear

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12073]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There are 3 talents that "increase the duration" of buffs - Buff, Super Soldiers, and Macrodosing.

The description of Buff says "Gain an additional 50% Buff Duration."
The descriptions of Super Soldiers and Macro dosing both say "Buffs you apply last 25% longer."

Now, while both of these are technically worded differently, they mean the exact same thing; if the duration of a buff is increased, then it lasts longer, and vice versa.

This can cause confusion to new players, since the descriptions do not accurately convey what the talents do. I've seen many people misunderstand the talents on the discord, so I take that as evidence that they should be reworded.

The problem is that "buffs lasting longer" can be caused by either increasing the initial strength, or decreasing the rate of change. These effects are not effectively the same thing, since a) higher strengths have stronger effects in most cases, and b) hitting the max strength means that increased application strength means that increased initial strength is not useful.

Since the Buff talent does the same thing as tonic liquid (i.e. reduces the strengthchange of buffs), the wording should be something along the lines of "Buffs decay 50% slower". This wording is unambiguous, it tells the player that buffs aren't stronger, but do last longer.

Super Soldiers and Macrodosing should probably be worded similarly to Dr. Submarine; something like "Buffs you apply are 25% more potent".

### Reproduction steps

1. See the English descriptions of Buff, Super Soldiers and Macrodosing, and observe that they do not accurately describe what the talents do.

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! We had a brief discussion about this, and even though we agree the descriptions are somewhat ambiguous, we decided to leave them as-is. The way we see it, it's not that important for the average player to know about the distinction - but those experienced players who are aware of it and know the mechanics of buff strength/duration can potentially use it to their advantage.
