### ISSUE TITLE
Moloch has not enough inventory space for extra alien blood and genetic material to spawn

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12071]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Both moloch and black moloch have not enough inventory space for alien blood, genetic material generated by doctor's talents to spawn.

### Reproduction steps

1. give your self talents "bloodybusiness" and "geneharvester"
2. loot moloch or black moloch

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This also seemed to affect crawler broodmother and giant spineling. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e3b9706a496e57313426287e6d29f7b84927af99 (+ added a console error to make issues like this easier to spot in the future)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
