### ISSUE TITLE
Sprite depth on diving suit arms is incorrect

### ISSUE THREAD

**Issue by arnoldh2** [Regalis11/Barotrauma#12070]
While using diving suits the lower arm sprite draws on top of the upper arm sprite, covering the joint. This extends to all of the diving suits I've tested, including modded ones. And while using no mods at all.

**Comment by itchyOwl** [comment]
I don't think there's anything incorrect with the depth: the forearm is supposed to be drawn in front of the upper arm. It's the same with the other clothing and also without any clothing:

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/00ad466c-57a2-433b-868d-2ef18769a7cf)

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/f73d8f6d-da0b-4f51-b954-e5c18ec6052e)

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/6613540b-e17a-409f-b77c-3042cf08220e)

What exactly do you think is wrong here?

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@78c12b1.

**Comment by itchyOwl** [comment]
You were right: it was incorrect. Just couldn't notice it at first..

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.

**Comment by Regalis11** [comment]
These changes seemed to cause some issues, see [Suit sprite depth not changing with character sprite depth.](https://github.com/Regalis11/Barotrauma/issues/12674#top)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/208e0d54c050b57df3dbd9cad3f65938c44645c2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
