### ISSUE TITLE
Mining Mission Inconsistency

### ISSUE THREAD

**Issue by Chef-Boyardeee** [Regalis11/Barotrauma#12075]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At the end of a Mining Mission, I failed it, despite having the required minerals. The Mining Mission asked to mine 6 Thorianite, but only asked for 33%, 2 Thorianite, to be brought back. I deconstructed 1, leaving me with 5, and ended the mission, only to fail. I was expecting that, since I had 5 Thorianite, I was above the 33% threshold and would succeed in the mission.

### Reproduction steps

1. Start a mining mission, can be in a campaign or just a multiplayer mission.
2. Mine all the required minerals.
3. Put the minerals in a container.
4. Take 1 from the stack and deconstruct it.
5. End the mission.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The mission descriptions says you need to bring back 6 samples, and you get to keep a third of them. You only brough 5, so the mission failed.
