### ISSUE TITLE
Missions count

### ISSUE THREAD

**Issue by RooneyRoll** [Regalis11/Barotrauma#12078]
I apologize because this is probably not the place for my questions, but I can't find enough information so I thought maybe here I would. I am wondering about two things. 
1. I just red in the Wiki that there is one additional mission different from the three given from the outpost manager. "_An Outpost can provide a maximum of 4 missions per visit, 5 with certain special Events. One NPC, the manager of the station, will give out 3 missions. Another random NPC will give another mission, typically a Cargo or Monster mission_." I've been playing for a long time but I can't remember ever getting a fourth mission (aside from outposts with clown/husk compartments). Is this an inaccuracy in the description or I am missing something?
2. I noticed that when I have acquired all missions in an outpost and then save, quit and load in singleplayer there are no additional missions. It happened before. Some people say it's been a bug some say feature. I'm just curious if it's possible to do it anymore or it's removed.
Thank you in advance!

**Comment by Vykn** [comment]
The line from the wiki is accurate. They aren't particularly exciting events (just a speech bubble over a random outpost dweller who will say “I posted about an assignment earlier. Sent the details to your onboard navigation system too, in case you're interested.” and give a kill monster, cargo, or salvage mission). The “If interested, imitate your favorite bird.” event is also one of these. They definitely still occur in the game.

**Comment by RooneyRoll** [comment]
Thank you!
