### ISSUE TITLE
Bots should stop cleaning up items if there are no suitable cabinets left

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12081]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Currently bots keep cleaning up items even if all the suitable cabinets are full, this causes the bots to pickup items from crates and then run next to a full cabinet and dropping the item next to the cabinet, which then later causes another bot to try to cleanup that dropped item and trying to bring it to another full cabinet dropping it next to that cabinet, so you end up with multiple piles of dropped items across the submarine. 

### Reproduction steps

1. Use the "Too many items" save from this ticket https://github.com/Regalis11/Barotrauma/issues/11976
2. Undock from the outpost and just wait for the bots to clean enough of the items that all the cabinets on board the sub are full. 

### Bug prevalence

Happens every time I play

### Version

v1.0.15.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I can't repro this. There's so many items on that sub that it takes quite a long time for them to get to the idle state, but eventually they will. There are items piling up next to the lockers, because the bots drop the item they are trying to clean up when the objective fails, which happens e.g. when someone else has just filled the target container, so that it can't fit the item anymore. Also tested with non-stackable items, where it's easier to confirm that the AI logic works as supposed: the containers that are full are properly ignored while seeking a valid place dor the items.

**Comment by Rokvach** [comment]
There seems to be couple of things happening here which causes the items to pile up, again tested with the too many items save mentioned on the repro steps

1. In the save there's more items than what there is cabinet space for from the bots point of view as the bots can only cleanup items to specific cabinets with a specific tag, so even though medical and storage cabinets still has empty space for items the bots wont utilize those empty spaces as they follow the tag system. 
2. If there's a lot of bots cleaning up items they tend to target the same cabinet if there is a empty space, but as there is multiple bots doing cleanup at the same time, but only one empty slot left in a cabinet, all the bots will target that same empty slot and whoever is fastest to get to the slot gets to place their item in the slot while the rest of the bots still in the middle of running to the cabinet with their item will just drop that item next to the cabinet.

In the image there was still a empty slot inside the cabinet when the bots picked up those items but as the empty slot was filled while the bots were running towards the cabinet, the bots just dropped their items next to the cabinet and forgot the items there until someone else later on notices them and cleans them up. 
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/f253ca80-81a9-4392-a54f-84e1a4d2c69e)
