### ISSUE TITLE
Cleanup order shouldn't be active in outposts

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12080]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As bots doesn't travel to the submarine during outpost levels they shouldn't have the cleanup order active if there is something to cleanup in the submarine while the bot is in a outpost, unless we want to allow bots to travel to the submarine. 

### Reproduction steps

1. While in a outpost level order a bot to cleanup
2. Run into the submarine and drop a item
3. Notice that the bots cleanup order highlights

### Bug prevalence

Happens every time I play

### Version

v1.0.15.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@440d9d6.

**Comment by AdamH-Daedalic** [comment]
Bots in the players crew do not perform cleanup actions when the sub is docked at an outpost. They resume normal behaviours upon leaving the outposts and correctly respond to the cleanup request.
