### ISSUE TITLE
Attempting to use occupied turret hides UI elements

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12082]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If somebody (Bot or player) is using turret periscope and you use click to use it also, Some UI elements are hidden as if you would be actually using it.
Happens in solo and multiplayer games.

![Turret UI issue not using](https://github.com/Regalis11/Barotrauma/assets/8488224/0020aac1-cf73-412e-bf9f-bd24ba3be0c2)
Turret used by a bot. Not clicked.

![Turret UI issue trying to use](https://github.com/Regalis11/Barotrauma/assets/8488224/c94a5237-9117-4e5d-b792-7c36de7f9a73)
After clicking. Top cornered UI elements fade away, as if actually using periscope. (not actually using it until clicking out and back into periscope.)

Issue was discovered alongside with:
https://github.com/Regalis11/Barotrauma/issues/11419

### Reproduction steps

1. Have bot or a friend use turret periscope
2. Click same periscope, while they are using it
3. UI elements fade away from top of the screen
4. If last user was bot, you won't start using it until clicked "out of the periscope" and clicked to use it again

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad0ff77b678eb187012b55bd514661636010f944

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
