### ISSUE TITLE
An exception was thrown when attempting to copy

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#12099]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I clicked the arrow that updates mods in the main menu. After Steam finishing verifying files (apparently that's a new time-wasting feature), the mods started updating. But after the first progress bar filled, updating progress stopped and I found this error in the console:
![Barotrauma_yops5QmOLJ](https://github.com/Regalis11/Barotrauma/assets/10529134/1ee574cd-b70c-4275-adc9-0d9e982a80b0)

Update list:
![Barotrauma_62b90XCKNv](https://github.com/Regalis11/Barotrauma/assets/10529134/0035a382-c0f3-464f-a3f7-3f203428eff3)

### Reproduction steps

1. Click the update button (while Steam is downloading workshop mods in the background)
2. Mods won't update
Not sure if reproducible.

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! The console warning seems to be an issue with the Barotrauma 40K mod (that file is empty, so it can't be loaded). The update list issue you've already reported.
