### ISSUE TITLE
bot teammates cannot be renamed if it requires reputation to hire

### ISSUE THREAD

**Issue by zelda0079** [Regalis11/Barotrauma#12090]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

bot teammates cannot be renamed if it require RP to hire

### Reproduction steps

1. I have a bot teammate which require RP to hire.
2. see picture https://i.imgur.com/lOAD3O3.png
3. I cannot left click to rename it.
(special NPCs have no this issue)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately could not find a way to reproduce the issue:

https://github.com/Regalis11/Barotrauma/assets/14351070/be7045de-9717-4bc5-be5a-5e54b46385a8

You seem to have some mods enabled, I wonder if those might have something to do with it? Have you tried if the issue occurs in the vanilla game as well? When you left-click the name, does anything happen?

**Comment by Regalis11** [comment]
Repro steps provided in: https://github.com/Regalis11/Barotrauma/issues/12198

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8ef181a9f10c1dafbd872273ff102705f9295511

**Comment by AdamH-Daedalic** [comment]
Tested against release/traitor-update

Player was able to correctly rename crewmates that required an RP check to be hired, before and after a save has been made, with the reputation requirement remaining visible upon the save-load (a symptom mentioned in [#12198](https://github.com/Regalis11/Barotrauma/issues/12198#issue-1764248811)). Closing
