### ISSUE TITLE
LOS doesn't extend all the way to the sides of the screen

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12094]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Really noticeable when you equip a diving suit, but doesn't seem to be bound to resolution. 
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/cf19aeb6-b57f-4a30-b42d-628097f5308e)

### Reproduction steps

1. Boot up the game on 1.0 Patch 2 PR
2. Load a sub in sub editor
3. Take a look at the left and right side of the screen while walking around the submarine

### Bug prevalence

Happens every time I play

### Version

v1.0.15.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6e89583f97c0931019d35cc4ec15d29a70bd3003
