### ISSUE TITLE
Mineral Scanner - setting not remembered?

### ISSUE THREAD

**Issue by lewri** [Regalis11/Barotrauma#12101]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This may be more of a feature request but after installing the mineral scanner I have to turn it on for every mission. Is it meant to turn off? And if so, would it be reasonable to allow that setting to be remembered? I'm not entirely sure why you'd want to turn that scanner off (unless it affects things I don't know about yet 🙃 )

### Reproduction steps

Start a mission with the mineral scanner upgrade
Go to the navigation panel and notice the mineral scanner is off. Turn it on.
Finish a mission, then do another mission and notice the scanner is off again.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/db4d3df356e0306bbfba4861e016429820a9c82a

**Comment by lewri** [comment]
That's amazing :) Thanks! ❤️

**Comment by Rokvach** [comment]
Tested, the mineral scanner still seems to get turned off in level transitions
