### ISSUE TITLE
Voice chat settings crash

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#1210]
- *[x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Voice chat settings allow to toggle on both voice activity and push-to-talk which crashes the game.
**Steps To Reproduce**
Tick both the voice activity box  and push-to talk in the audio settings menu. Voila! Your game just crashed.

**Version**
Current steam version. Windows 7 OS.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this, do you happen to have the crash report?

**Comment by Waagher** [comment]
No were no messages of crash reports being created, and there are none in the game folder, sorry.

**Comment by Waagher** [comment]
Now crashes when clicking on the voice activity box alone, and just before crashing it shows the whole sound indicator being coloured green, as if I'm screaming my lungs out at the microfone. However the crash does not happen if I switch the sound device to something else and then back to the microphone before ticking any boxes. Might be just a hardware problem on my end.
