### ISSUE TITLE
wikiimage_sub shows "hidden in game" items

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#12105]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

i placed a coilgun and set it as "hidden in game"

wikiimage_sub created an image with a coilgun

![wikiimage](https://github.com/Regalis11/Barotrauma/assets/5103517/ba5125fb-a99c-4ec2-87dc-8c4c5c9aa579)

### Reproduction steps

set something as hidden in game
make wikiimage
something is not hidden in game

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86a523fd1ea0852f05b16615f82884f647dfcb5a

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
