### ISSUE TITLE
wikiimage_sub shows propeller circle of engine

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#12106]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

engine damage circle is shown for wikiimage

![wikiimage](https://github.com/Regalis11/Barotrauma/assets/5103517/207388c6-5d8e-43c8-a2d8-1ef3301287ab)

### Reproduction steps

place engine
take wikiimage_sub co,,and

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86a523fd1ea0852f05b16615f82884f647dfcb5a

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
