### ISSUE TITLE
a2s protocol soft crashes when the server modlist is too long

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#12108]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When the modlist is too long, the *a2s* protocol stops working.
In consequence, anything that depends on it does not function. Namely: **server discovery** (the server no longer appears in the multiplayer server lobby and a direct connection is needed); and custom discord bots used in server monitoring.

The solution is as easy as limiting the number of the `contentpackageN`s or the size of the string within each `contentpackageN` in the `rules`  dictionary of the *a2s* protocol handler.

Note that this bug probably existed since the handler's creation, and only as of the recent rework of the content package reporting has it become visible due to the added verbosity.

Note as well that this might be relevant to all the other values of the `rules` dictionary (see: `message` - that is the lobby description), but I have not tested it.

### Reproduction steps

1. Start a dedicated server. Might be relevant to p2p servers as well but I have not tested it so.
2. Add 10-15 mods.
3. The server disappears from the lobby.
You can further prove this by using an *a2s* connection to the query port (default 27016), for example with python3 and the python-a2s library: if the petition is about `a2s.info` or `a2s.players` then the information is received. When the petition is about `a2s.rules` then the answer is dropped because the resulting packet is too big (exceeding 65536).

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/f433a8c6bf8727462e41eb7571d799a31d2398ba

This issue does still exist in the current latest code, Noting that I am not sure how many mods need to be added, but simply adding too many will cause a server to not correctly appear on the serverlist for queries (In my case I probably exceeded 50 mods, but it is indeed likely the amount and length of text of the mods combined exceeding some limit).

Quick notes:

- Exceeding a text length of mods (Say, 20-50 mods) will cause servers to not appear in the list
- Will not show even if hosted from the same machine via dedicated and public.
- Server is still joinable, just does not appear in the serverlist.
- Issue is likely related to SteamManager.cs lines 62-69 (Server project code) having no limit to the length/count of said contentpackage keys.

Tested with two servers, one with 4-8 mods and one with likely 30-60. same files, changed port (all forwarded) to confirm.

**Comment by NotAlwaysTrue** [comment]
Devs could you please check this issue once more?
You have fixed this in v1.2.6.0 but related code was removed in v1.3.0.1, recent tests(within 24hrs) on Dedicated Servers shows this still a problem.

**Comment by NotAlwaysTrue** [comment]
I think the problem is likely from v1.3.0.1.
[MaxPackagesToList](https://github.com/FakeFishGames/Barotrauma/commit/3791670c42bdd80ba3a2c7c0f6d6131efb20c841#diff-6d1edf7b7605a66b71c711a8faab0b1a16b7977f494b3cba0e316baad3b14c9dL64) was removed but somehow in [ContentPackage](https://github.com/FakeFishGames/Barotrauma/blob/ffccd25ebd360f2d2776d4e553a7e526ef8cf0ed/Barotrauma/BarotraumaServer/ServerSource/Steam/SteamManager.cs#L66) you didn't add this back in

**Comment by Regalis11** [comment]
@NotAlwaysTrue Thank you for pointing that out! You're right, the old fix seems to have gotten lost along the way due to some of the refactoring we did to the networking code for the Epic Store release. I've restored the fix in out private repo now, the issue should be addressed in the next unstable build and the upcoming release.
