### ISSUE TITLE
Unable to adjust engine thrust manually

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12119]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Manually setting the engine thrust makes it jump to the previous value, even if there was no control signal from any component or terminal.

https://github.com/Regalis11/Barotrauma/assets/68995233/a1bac466-50d3-4705-98ed-b6978ac5f2b4

### Reproduction steps

`quickstart humpback`

1. Try adjusting the engine thrust by hand, you can't
2. Disconnect wire from nav terminal, still not possible
3. Shut down reactor, still can't adjust
4. Delete all wires in the editor, still can't control the thrust manually

### Bug prevalence

Happens every time I play

### Version

v1.0.18.0 (unstable)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/baf2d4b71b05a365354ecbeab42db0287ad329d5
