### ISSUE TITLE
Broken wires in engineeringmodule_01_abandoned

### ISSUE THREAD

**Issue by bananaman6213** [Regalis11/Barotrauma#12117]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/119143410/fb03ce03-b801-4402-aaed-4fd2b32f2fb8)
The 4 wires that connect the junction boxes to each other in engineeringmodule_01_abandoned have 0 condition by default.
This causes minor visual issues and prevents them from being stacked with normal wires.
I checked nearly every other wire in this module, as well as many from other outpost modules, and it seems to be only these 4 affected.

This was also the reason behind #11000 

### Reproduction steps

1. Visit an abandoned outpost, or open the relevant module in the sub editor
2. Detach any wire connecting the junctions in engineeringmodule_01_abandoned to each other
3. Note that the wire has 0 condition

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fb4288a27838cb0c24980b06c7ca41c10b017a6e

**Comment by Jasontti** [comment]
One more 0 condition funny wire was still found.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/679a08a4-78be-4de5-baab-dd82d686f6f3)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa280567a958cbe596348694589221a10f19d104

**Comment by Jasontti** [comment]
Tested, working and closing ticket.
