### ISSUE TITLE
Can't rename bot Artie Dolittle

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12127]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I tried to rename Artie Dolittle, I succeeded, but only until the end of the round in the next round, his name was restored

### Reproduction steps

1. Rename bot  "Artie Dolittle" using station personal manager.
2. End round
3. In next round his name restored

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by pavel4win** [comment]
After renaming Artie Dolittle's ID card has new name but crew list is not.

**Comment by Regalis11** [comment]
This isn't intentional: it should be possible to give him a nickname. Gave this a test and couldn't repro the issue:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/6bc37c8b-32e1-4b90-b7b4-831051a06158)

Did it happen in single player or multiplayer?

**Comment by Regalis11** [comment]
No known steps to repro, closing
