### ISSUE TITLE
Chaingun chage up sound does not follow the sub

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12126]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Firing the chaingun will make the spinny sound fade into the distance though the dakka remains.

https://github.com/Regalis11/Barotrauma/assets/68995233/574f4488-7195-40d3-82b1-7a43fef6ccdb

### Reproduction steps

`quickstart orca2`

1. Make sub move reverse at full speed (AI do not touch nav terminal)
2. Fire the chaingun

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment]
Can repro, and I think it's because the charge sound does not update position when it's already playing. On a quick glance it's the same issue with RangedWeapon, though it probably doesn't cause any issues with the vanilla content.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4db6b4dee17faf7f5e979925fec9a979cdb29eb9

**Comment by Regalis11** [comment]
Also fixed RangedWeapon in https://github.com/Regalis11/Barotrauma-development/commit/af8c2d1bd6cbc6e99e30095bc6d9d2ec2ac1afd2

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
