### ISSUE TITLE
Bandages are consumed but do nothing in auto-injectors

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12125]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Placing bandages, plastiseal or anti-biotic glue inside an autoinjector will consume the medical item, but heal no afflictions.

It would make more sense if either: a) bandages cannot be placed inside autoinjectors (via restricting the ItemContainer to only chem items perhaps), or b) they target the head limb (or maybe a different limb? but head makes most sense to me)

Of course, not many people are putting bandages in autoinjectors, so it's not a big issue or anything, but it's a big odd that it'll just consume the item without doing anything.

### Reproduction steps

1. Get nice and crispy in a fire
2. put on an autoinjector and place bandages/plastiseal/antibiotic glue inside
3. observe that the item is consumed, but there is no healing

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
Kudos for thinking outside the box! What should happen when instead of gauze, we try to inject copper wires into our bloodstream?

**Comment by Jasontti** [comment]
Tested,
Protein bars have "chem" tag and so can be used in auto injector.
No further issues found.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/6fb093cd-65b0-4b22-92ad-bc7c566ffd9b)

**Comment by Jasontti** [comment]
No issues found.
Closing.
