### ISSUE TITLE
Hidden walls in the game now ignore collision [Unstable]

### ISSUE THREAD

**Issue by Isamylov** [Regalis11/Barotrauma#12132]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing the sub in the editor, I found that in the unstable game version character can now pass through the wall, which is set to "Hidden in the game". On the stable version, everything works correctly.

The wall component:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/ce2d5097-c491-486c-827e-110196948cec)

Unstable:
![image](https://github.com/Regalis11/Barotrauma/assets/109140990/3fe172c1-b0c6-43c6-86b4-4ec398426b9b)
![image](https://github.com/Regalis11/Barotrauma/assets/109140990/699c5315-75f0-41ce-af2a-a466064d537d)

Stable:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/bd49a5b4-30d6-4f10-b9e4-047709b97928)

### Reproduction steps

1. Open sub editor.
2. Create a similar hull configuration.
3. Try to walk inside the wall. Stable game version - no issues. Unstable - pass through.

### Bug prevalence

Happens every time I play

### Version

v1.0.18.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Oh, actually I don't think we should do that: hidden walls are used e.g. for walls in the Thalamus layer. So if those would collide, the player would collide with "air" or nothing. I don't think we should change this.

**Comment by itchyOwl** [comment]
Actually it seems like an oversight. That's a very old commit. What caused it to change the behavior now? Pushing a fix on a separate branch.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development#4291, targeting the second patch. Added you as a reviewer.

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.
