### ISSUE TITLE
Abuse for new hired crew and new bought equipment in outpost.

### ISSUE THREAD

**Issue by KnockaboutRain** [Regalis11/Barotrauma#12139]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

New recruits and new bought equipment arrive to the submarine  before I start mission, if I reload save. 

### Reproduction steps

1. I start the campaign and arrive to the outpost.
2. I bought needful goodies and hired crew
3. I reload save before entering mission 
4. Goodies appeared in submarine and crew joined me

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional.
