### ISSUE TITLE
Bug: Steam Update for Linux Downgrades Game to 0.8.9.1 instead of upgrading to 0.8.9.4

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1213]
Title. Additionally, steam authentication is now broken too, but that's probably a side effect of the downgrade.

This is in fact the most recent "update", and there are noticable gameplay differences that do indicate it's 0.8.9.1, such as outposts without airlocks.
![2019-03-04-071654_1366x768_scrot](https://user-images.githubusercontent.com/47284081/53735848-b5805080-3e4d-11e9-9349-f3d9b9170ea3.png)

**Comment by Regalis11** [comment]
Should be fixed now!
