### ISSUE TITLE
AI sometimes fall off of ladders in outposts, hurting themselves

### ISSUE THREAD

**Issue by Next-Door-Tech** [Regalis11/Barotrauma#12138]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

NPCs who are climbing up ladders sometimes fall off and hurt themselves. I'm not 100% certain this is correct, but anecdotally this _seems_ to happen when the pathing AI is climbing upwards, wants to get off at an intermediate platform, and attempts to do so slightly too low, causing the NPC to fall back down due to not having a floor platform beneath them. I've only seen this happen maybe three times over the last couple days, so I don't have much to go off of.

Here are some things I think may be relevant:

- This only happens occasionally, not every time an NPC climbs a ladder
- This has happened to both outpost NPCs and AI-controlled crewmates
- Every instance seems to have been where the NPC is doing a slow, idle walk (not running to perform a job, etc.)
- In one instance, the same NPC proceeded to climb and then fall off the same ladder at the same platform several times in a row, losing about 40% of their health

### Reproduction steps

Unfortunately I don't know _exactly_ what conditions cause this to happen in the wild, but I doubt you want to walk around outposts for hours hoping you happen to see this happen anyway. Assuming you have some sort of dev tool that lets you instruct AI where to path to, here are my best guesses for suggestions:

1. Construct an environment with a ladder that has multiple intermediate platforms
2. Instruct an NPC to perform an idle walk which takes them up the ladder, getting off at an intermediate platform
3. Repeat until the issue occurs.
4. Perhaps experiment with environmental factors like other NPCs nearby or at the top of the ladder, background decorations/interactables, the type of platform, etc. Your guess here is as good as mine.

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We haven't been able to reliably reproduce this, but there have been several fixes to issues regarding pathfinding and navigation on ladders that are most likely related to this. Possibly fixed, but let's reopen this if the issue reappears.
