### ISSUE TITLE
Events that are triggered by speaking to the station manager cause the "missions available" speech bubble to be hidden

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12148]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Normally, when arriving at a station, there is an icon that indicates to players that there are missions available (the speech bubble with an ellipsis).
However, if there is an event associated with the station manager that causes the yellow exclamation mark icon, then the speech bubble will be hidden. This means that it looks like there are no missions available, since there's no speech bubble on the HUD from elsewhere on the station.
Players don't often just explore the entire station, (rather opting to just follow the shop and speech bubble icons) so they may leave without realising that there were missions available.

This does not happen often; I decided to manually trigger an event to test it, since it occurs in I'd estimate 1 in 100 stations, but it can confuse players who don't explore the entire station and do not know of this bug.

https://github.com/Regalis11/Barotrauma/assets/37850646/25b5deeb-0560-4565-9b88-38b3e5dc7229

### Reproduction steps

This bug occurs whenever an event puts the yellow exclamation mark icon over the station manager (i.e. talking with them starts an event). It occurs randomly, but here is how I triggered it manually (I don't know enough about event spawning mechanics, so some of these steps might be redundant)

1. Arrive at a station in campaign (there must be missions available)
2. if there is no speech bubble icon pointing to the station manager, then find the station manager and observe that there is no speech bubble.
3. If there is a speech bubble, then kill every npc except for the station manager
4. trigger an event (I used `triggerevent foreshadowing`)
5. observe that the speech bubble disappears, and it is now impossible to tell that there are missions available unless you find and speak to the station manager

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d703bb7d8c81f2704b2075573adf5794ac0115f

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.

**Comment by Jasontti** [comment]
Tested this, but forgot to close it 2 weeks ago.
No issues found.
