### ISSUE TITLE
Electrician's goggles UI speed depends on screen refresh rate

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12141]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Faster screen refresh makes the bits march faster, and the power wires pulse faster.

60Hz

https://github.com/Regalis11/Barotrauma/assets/68995233/9290870c-3f80-4e7c-a875-b730684bf7dc

144Hz

https://github.com/Regalis11/Barotrauma/assets/68995233/c0ab3644-b028-48db-add3-82ed299f5137

155Hz

https://github.com/Regalis11/Barotrauma/assets/68995233/d09689b4-4832-4509-a3af-4bfc752157aa

VSync off 250fps

https://github.com/Regalis11/Barotrauma/assets/68995233/9802e2c6-5936-4290-b88e-afaf5dc62a06

### Reproduction steps

1. Have a 155Hz monitor
2. Put on electrician's goggles

This can't be intentional :)

### Bug prevalence

Happens every time I play

### Version

v1.0.18.0 (unstable)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4292/commits/ada55d8dc792a69d00ba9cc0759d3309c6261c3c

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged after review if nothing comes up during review.
