### ISSUE TITLE
Tiger thresher genes do not affect oxygen in suits

### ISSUE THREAD

**Issue by Totalblazing** [Regalis11/Barotrauma#12143]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Either the description of Tiger thresher genes is misleading, or something is broken. I did some testing with 2 characters in suits, 1 with 100% thresher genes, the other with none. Both suits ran out of oxygen at the same time. Tested with all diving suits. The same occurs with husk infection/symbiosis. 

### Reproduction steps

1. Start a multilayer game
2. Spawn tiger thresher genes 100%
3. Use said genes
4. Exit the submarine in a suit of your choice
5. Observe oxygen still draining from suit

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The genes only make the "oxygen low" affliction increase in severity more slowly, meaning you take longer to suffocate in low-oxygen conditions. It doesn't affect the rate at which you consume oxygen from oxygen tanks. I can see how the description can be confusing though, so I think we could consider rewording it.

**Comment by Totalblazing** [comment]
Would it at least be possible to disable the oxygen low alarm in suits if the character is incapable of suffocating. Or after a sufficient amount of time has passed?

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7edf9adc4c795031478290fa410ec7e1ff8da57d

**Comment by Jasontti** [comment]
Testing notes in private repo: https://github.com/Regalis11/Barotrauma-development/issues/4528

No issues found
Closing ticket
