### ISSUE TITLE
A cloud of acid has a collision

### ISSUE THREAD

**Issue by Arti-Strelkov** [Regalis11/Barotrauma#12157]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The problem lies in the acid cloud from the explosion of an acid grenade, this cloud completely stops the boat when it comes into contact with the compartment. That is, if you surround the boat with detonators with endless acid grenades, and activate them, you simply will not be able to swim, as if the acid cloud has a collision. Just beg! Do not remove the possibility of acid grenades exploding endlessly in detonators if the "invulnerable" checkbox is checked! You can do a lot of things with them... Only the incomprehensible collision of the cloud of acid itself interferes. I would like the collision of the acid cloud to be ultralight, so that the boat can move it and not brake on it

![Barotrauma_NBozmZdOGU](https://github.com/Regalis11/Barotrauma/assets/127675569/9c9feca4-5dab-4f89-a87a-b6f97618c3a9)

### Reproduction steps

Take any boat, put a detonator under the hull in the water (outside the compartments), put an invulnerable acid grenade there, and tie the activation to the control panel for any signal. Everyone, sit down at the remote control and direct the boat down, sometimes click on the detonator signal, you will see that the boat slows down sharply

![Barotrauma_dVdMUHj2rr](https://github.com/Regalis11/Barotrauma/assets/127675569/79651174-5819-4923-b4c0-57e843fb0855)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66ffa11f5cf063aca5b029584c3ab9919edc267d

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll keep it open until we've tested the fix internally and made sure it doesn't cause any side-effects. :)

**Comment by Jasontti** [comment]
Tested.
Same lifting effect could be produced, even with invulnerable acid grenade quite far away from the sub, also secondary smoke was observed away from exploding acid grenade.


![2023-07-26_09-59](https://github.com/Regalis11/Barotrauma/assets/8488224/3d9072aa-94c2-4b73-87e4-23dcb3ca3012)

https://github.com/Regalis11/Barotrauma/assets/8488224/90e335bd-f061-4d9f-865d-0b9a7cb541dc
