### ISSUE TITLE
Errors found in the source code of Barotrauma

### ISSUE THREAD

**Issue by AndreyMoskalev565** [Regalis11/Barotrauma#12155]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello! I found several errors in your code with the help of the PVS-Studio analyzer.

**Issue 1**

```
public void RecreateSprites()
{
  ....
  if (_deformSprite != null)
  {
    _deformSprite.Remove();

    var source = _deformSprite.Sprite.SourceElement;

    _deformSprite = new DeformableSprite(source, ....);            
  }
  ....
  for (int i = 0; i < DecorativeSprites.Count; i++)
  {
    var decorativeSprite = DecorativeSprites[i];

    decorativeSprite.Remove();

    var source = decorativeSprite.Sprite.SourceElement;

    DecorativeSprites[i] = new DecorativeSprite(source, ....);          
  }
}
```
[Here's the link to the code fragment with the error.](https://github.com/Regalis11/Barotrauma/blob/6acac1d143d647ef10250364fe1e71039142539c/Barotrauma/BarotraumaClient/ClientSource/Characters/Limb.cs#L442)
Take a look at how the 'Remove' methods are implemented in the code above. They assign the 'null' value to the 'Sprite' properties. The subsequent dereference of these properties when initializing the 'source' variable will result in 'NullReferenceException'. 

**Issue 2**

```
private void UpdateAttack(float deltaTime)
{
  ....
  if (....) { .... }
  else
  {
    ....
    if (pathSteering != null) // line 1551
    {
      ....
    }
    else
    {
      ....
      if (....)
      {
        ....
        else if (....)
        {
          if (pathSteering != null) // line 1954
          {
            pathSteering.SteeringSeek(....);
          }
          else
          {
            SteeringManager.SteeringSeek(....);
          }
        }
        ....
      }
    }
  }
  ....
}
```
[Here's the link to the code fragment with the error.](https://github.com/Regalis11/Barotrauma/blob/6acac1d143d647ef10250364fe1e71039142539c/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/EnemyAIController.cs#L1954)
Here, the 'pathSteering != null' check is performed twice, and the second check is in the else block of the first check. Since the value of the 'pathSteering' variable does not change, the second check will always return false. As a result, the code in the if block of this check will never be performed.

**Issue 3**

```
public class Contact
{
  ....
  public Fixture FixtureA { get; internal set; }
  public Fixture FixtureB { get; internal set; }
  ....
  internal void Update(ContactManager contactManager)
  {
    Body bodyA = FixtureA.Body;
    Body bodyB = FixtureB.Body;

    if (FixtureA == null || FixtureB == null) //<=V3095
      return;
    ....  
    if (sensor)
    {
      Shape shapeA = FixtureA.Shape;
      Shape shapeB = FixtureB.Shape;                
      touching = Collision.Collision.TestOverlap(...., 
                                                 ref bodyA._xf, 
                                                 ref bodyB._xf);
      ....
    }
  }
}
```
[Here's the link to the code fragment with the error.](https://github.com/Regalis11/Barotrauma/blob/6acac1d143d647ef10250364fe1e71039142539c/Libraries/Farseer%20Physics%20Engine%203.5/Dynamics/Contacts/Contact.cs#L252)
The code above contains the FixtureA == null || FixtureB == null check. It indicates that FixtureA and FixtureB can potentially have a null value. However, it won't help here, because we will get an exception even earlier:

```
Body bodyA = FixtureA.Body; // possible NullReferenceException
Body bodyB = FixtureB.Body; // possible NullReferenceException

if (FixtureA == null || FixtureB == null)
  return;
```

**Issue 4**

```
public override void Update(float deltaTime, Camera cam)
{
  ....
  if (picker == null && !picker.HeldItems.Contains(item))
  {
    ....
  }
  ....
}
```
[Here's the link to the code fragment with the error.](https://github.com/Regalis11/Barotrauma/blob/6acac1d143d647ef10250364fe1e71039142539c/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/MeleeWeapon.cs#L192)
If the 'picker == null' condition is true, then an exception of the 'NullReferenceException' type will be thrown when performing '!picker.HeldItems.Contains(item)'. There is a typo here: the '&&' operator is written instead of '||'.

**Issue 5**

```
public void AddEntityToRemoveQueue(Entity entity)
{
  ....
  if (   removeQueue.Contains(entity) || entity.Removed || entity == null 
      || entity.IdFreed) { return; }
  ....
}
```

[Here's the link to the code fragment with the error.](https://github.com/Regalis11/Barotrauma/blob/6acac1d143d647ef10250364fe1e71039142539c/Barotrauma/BarotraumaShared/SharedSource/Networking/EntitySpawner.cs#L353)
Perhaps the 'entity == null' check is redundant here. In any case, it is still meaningless. If 'entity' is 'null', an exception of the 'NullReferenceException' type will be thrown while checking 'entity.Removed'.

### Reproduction steps

-

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I doubt any of these cause any actual issues in practice, but I think I'll address them regardless. I've got one question though:

> Issue 1: Take a look at how the 'Remove' methods are implemented in the code above. They assign the 'null' value to the 'Sprite' properties. The subsequent dereference of these properties when initializing the 'source' variable will result in 'NullReferenceException'.

I'm not sure what you mean by this. What properties are set to null? As far as I can see, there can be no NullReferenceException here: the only thing that could throw that exception when initializing the 'source' variable is if `Sprite` was null, and it can never be null here,

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1d0b7fc82d741ed6dc998dc3c3f02981195ca298

**Comment by Jasontti** [comment]
Tested.
No issues found during testing.
Closing ticket.
