### ISSUE TITLE
VIP Escorts aggro on player when curing husk infection on NPC

### ISSUE THREAD

**Issue by Cthegoalie** [Regalis11/Barotrauma#12152]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Accepted VIP and cultist transport missions. Once Infected cultist is Identified, when injecteing them with Calyxanide the escorts for the VIP accro on the player character.

### Reproduction steps

1. Playing A single player campaign 
2. Accept VIP transport and cultist transport missions
3. Find and cure infected cultist
4. Have VIP guards kill offending player character

### Bug prevalence

Happens every now and then

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Can't repro. In which state the infection of the cultist was? Was it twitching on the ground, walking around normally, or had it turned already? I tried applying the antidote in all of the states. The only way I was able to make the NPCs aggro/flee on me was when I shot the infected that was turning and lying on the ground, then revived him with cheats. Applying calyxanide on targets that are past treating, will damage them and make them turn quicker. I suspect this organ damage could cause the NPCs to react, but as I said, can't repro the issue.

**Comment by Cthegoalie** [comment]
I injected the cultist directly (without the syringe gun) as soon as I noticed the infection (around 30 to 35% progression) with the health scan HUD. He was walking around normally. I retried the mission 3 or 4 times with the same result before I just sprinted the sub to the next station so I wouldn't have to deal with the infection. I also had a mining mission and was in an abyssal hunting grounds leg when this happened.

**Comment by Cthegoalie** [comment]
In case it helps here are the addons I have installed. The only one I could imagine possibly generating abnormal NPC behavior is Robo Trauma, but I didn't actually have any Robo personnel in my crew or as passengers at the time.
![Installed BT mods](https://github.com/Regalis11/Barotrauma/assets/52898254/2b062c3f-6ed8-4b4b-8d1e-ec21c5799504)

**Comment by itchyOwl** [comment]
Ok, thanks for the further info. I'll try reproducing it again.

**Comment by itchyOwl** [comment]
I still can't repro it. I guess you can't test it again without the mods? If you can, sending the save file here (zipped) could help too. Moving to QA investigates.

**Comment by Regalis11** [comment]
No known steps to repro, closing
