### ISSUE TITLE
[CLIENTSIDE MOD] Vanilla Content Mismatch involving Lua For Barotrauma

### ISSUE THREAD

**Issue by Vizoplez** [Regalis11/Barotrauma#12161]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Lua for Barotrauma once installed now causes a clientside vanilla content package issue; where the server will reject connection attempts despite registering the client as 'compatible' with said server. This can be seen as the 'Vanilla' content package appears to be unticked.

This is pretty significant, since a lot of client performance mods relied on this being 'active and installed'. Moreover it doesn't actually modify the vanilla content pack in any major manner; and has severely reduced the ability to run lag-free on your client without having to beg the server owner to follow the same steps (and thus preventing normal users from playing).

As far as I'm aware, this is a recent issue.

### Reproduction steps

1) Install https://steamcommunity.com/sharedfiles/filedetails/?id=2559634234 as per their guide.
```
Installing Client-side Lua

Open hosting menu
Select LuaForBarotrauma in ServerExecutable and host a server
While hosting, open the console window (most commonly 'F3')
Type in or copy, then execute the console command:
install_cl_lua
Restart the game
```
2) Restart game as it asks, attempt to join a server so your performance mod works and you don't lag
3) Get a 'Local hash differs' error message.
4) Be confused.

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
https://prnt.sc/HapFDfPuHdvv
https://prnt.sc/jrezaVrEVwz3

https://prnt.sc/4s5jX2YYlXJZ - NOTE THAT THIS SERVER HAS THE MOD INSTALLED and CAN be connected to.

Error while reading a message from server. 
Error in ModDownloadScreen: mismatched Vanilla package: local hash is 07FDF38745AC83D58224340FF738F8E1, remote hash is E7A137BE888802B359A750545C92E195. Content package list received: True
   at Barotrauma.ModDownloadScreen.LogAndThrowException(String errorMsg, String analyticsId) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 48
   at Barotrauma.ModDownloadScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 125
   at Barotrauma.Networking.GameClient.OnConnectionInitializationComplete() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1130
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 261
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 505

https://prnt.sc/d7yXbcgorgG7
```

**Comment by Regalis11** [comment]
Thank you for the report! I'm not entirely sure if this is actually something we can fix. If the modified executable reports a non-vanilla package to the server, the (vanilla) server should report an incompatibility. It could be that this is something the developer of the mod needs to address (perhaps reporting a vanilla hash to the server despite not using a vanilla package?).
