### ISSUE TITLE
Consistent Systemwide Freeze/Crash

### ISSUE THREAD

**Issue by Dauntingnut2** [Regalis11/Barotrauma#12169]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Joining a game and playing normally for 30 minutes to an hour will cause the game and my entire computer to freeze indefinitely; until forcibly turning off the entire computer

### Reproduction steps

1. Join any online game 
2. Play for 30-60 minutes 
3. Entire game/computer crashes/freezes forcing hard reset

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Could you post your PC's specs here? I wonder if this could be a hardware-related issue, such as your GPU overheating or perhaps your system running out of memory. Do you have VSync enabled? If you've disabled VSync in the game settings, the game tries to render at the highest framerate it can, which could potentially lead to e.g. overheating issues.

**Comment by Regalis11** [comment]
Insufficient information to diagnose the issue, closing
