### ISSUE TITLE
Slipsuit missing from diving category in sub builder. 

### ISSUE THREAD

**Issue by the255smiler** [Regalis11/Barotrauma#12163]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When checking the diving tab in the sub builder the Slipsuit cannot be found.

### Reproduction steps

![image](https://github.com/Regalis11/Barotrauma/assets/136734031/420a18a7-7055-4317-a617-a374f5b07e4f)
1. Open the sub builder
2. Open the diving tab

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing.
