### ISSUE TITLE
Electrician goggles show wires that are hidden

### ISSUE THREAD

**Issue by Padex98** [Regalis11/Barotrauma#12160]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The engineer goggles show the signals and the connections of hidden wires. Not sure if it's something intentional or overlooked, but I think hidden wires should remain so even for the goggles. This is because certain circuits are too big to fit inside the submarine in the editor, and the goggles as of now show them all outside the hull.

### Reproduction steps

1. place a wire and make it hiddden
2. use the goggles. you should see the connections still

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eb3ec3297e96273cd88ca26753ebab47679fb9c2 (commit in our private repo)

**Comment by mygamingaccount** [comment]
R29 has a bunch of hidden wires
#11098

**Comment by Jasontti** [comment]
Tested and works.
Closing ticket.
