### ISSUE TITLE
Crew list is too wide on certain resolutions

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12164]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The crew list is unnecessarily wide on certain resolutions, such as 3440x1440.

### Reproduction steps

1. Switch to a resolution like 3440x1440 (aspect ratio > 2). If you don't have a monitor this big, you can also edit the properties `GameMain.GraphicsWidth` and `GameMain.GraphicsHeight` to return 2440 and 1440 respectively.
2. Start a round, behold the enormous crew list

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Roc25** [comment]
Same issue, waiting for fix 🥲

**Comment by SirClarke** [comment]
Same problem myself so hopefully it's fixed soon.

**Comment by Jasontti** [comment]
Tested and above issues are fixed.
