### ISSUE TITLE
Lighting issue: light not illuminating the entire room

### ISSUE THREAD

**Issue by Isamylov** [Regalis11/Barotrauma#12162]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After the patch I don't understand why there's the shadow when lamp light component is on. If I move a lamp in the editor - it's fixed until I start simulation, then the issue appear once again. Even if I delete all objects - the light still bugged. Can attach .sub file if needed.

![Screenshot_1](https://github.com/Regalis11/Barotrauma/assets/109140990/f937d8fe-a024-4b19-92ad-c579cf7df718)
![Screenshot_2](https://github.com/Regalis11/Barotrauma/assets/109140990/117f1ce8-c9be-44d1-9abe-f37dce89fc3b)
![Screenshot_3](https://github.com/Regalis11/Barotrauma/assets/109140990/58a08a13-8ff0-4fac-9b14-877f9d1f1e03)
![Screenshot_4](https://github.com/Regalis11/Barotrauma/assets/109140990/5b635b41-f72f-4898-a711-cd52c052a1fa)

### Reproduction steps

1. Open sub editor.
2. Recreate room conditions.
3. Check the shadow issue.

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Could you please send us the sub file so we can give this a test?

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
