### ISSUE TITLE
Trojan in barotrauma files after downloading a Lua mod

### ISSUE THREAD

**Issue by FFFiliPPP** [Regalis11/Barotrauma#12174]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

Windows Defender finds a trojan virus in barotrauma files, idk why
![image](https://github.com/Regalis11/Barotrauma/assets/71973340/4cefb3ea-e9be-46d4-94d1-fdb0f4b28a02)

### Reproduction steps

when opening game on steam windows defender just showing me a trojan in files
![image](https://github.com/Regalis11/Barotrauma/assets/71973340/d73a84c2-334c-468b-a92b-7eddefa6fc6c)

### Bug prevalence

Happens every now and then

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm fairly sure this is a false positive, and there isn't actually anything malicious in that file. But regardless, this is a file the Lua mod replaces in the vanilla game, so if there is some issue with the file, it needs to be addressed by the creator of the mod.
