### ISSUE TITLE
Not a real bug: VoIP after update

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#12176]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Starting from 1.020.1 an additional check was added into VoipClient.cs
We have widely use a server mod for our dedicated server when additional sounds or other channels where sent to clients by the server.

Unfortunately, in a current version an additional check of a sender and a receiver radio channels are added into the client code on top of the server checks. 
string 123 in VoipClient.cs:
`senderRadio.CanReceive(recipientRadio)`
This check blocks all the additional sounds sent to client.

Is it possible to leave this check only on a server side or disable it by a server settings for clients?
It was a wonderful experience to play on servers with this sound systems. 

### Reproduction steps

not required

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This check is necessary to allow the clients to play the audio without the radio effect if they can't hear the message through the radio, but are close enough to hear the character speak.

Would it be possible for you to work around this by making the server send the audio as if it was sent by the client itself (in which case this CanReceive check should always succeed)?
