### ISSUE TITLE
Level not mirrored when travelling through it backwards

### ISSUE THREAD

**Issue by RodionDraryri** [Regalis11/Barotrauma#12189]
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

(A - first base, B - second base) I sailed from point A to point B, after I had to swim back from point B to point A, but the path did not start from the place where I ended, but again, like if I were to swim from point A to point B instead of the other way around, the map just starts over instead of being mirrored.

### Reproduction steps

1. Swim from first base to second. 2. From second base, swim back to first. 3. Watch how the map does not start from the end, but again from the beginning, which is not logical.

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not find a way to reproduce this. The level seems to get mirrored correctly when travelling through it "backwards".

Do you mean you're expecting the submarine to start from the end of the level, and that you'd have to navigate through it backwards? We actually mirror the whole level instead, so you don't have to go through it in reverse or play on a submarine that's mirrored to face to the left.

**Comment by Regalis11** [comment]
No known steps to repro, closing
