### ISSUE TITLE
Server crash "Tried to read too much data from segment"

### ISSUE THREAD

**Issue by CiteReh666** [Regalis11/Barotrauma#12184]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was playing MP campaign for quite some time with three of my friends. We just got a new sub, Typhon 2 and entered Hydrothermal Wastes. But at the start of the mission server crashes, giving me a console with error in it. Reinstalling, running as administrator, save editing didn't help. Another weird thing - when it happens it removes two files from the game, which I check by verifying the game files. They are loaded back, this bug happens and verifying tells me that these files are missing again. I do not know which files these are.
![image](https://github.com/Regalis11/Barotrauma/assets/136854720/01594995-b287-48fa-8847-2f51d4062e33)

### Reproduction steps

1. Start a multiplayer campaign with three bots alongside players (We also picked a mission from Hognose, so maybe include him too)
2. Use Typhon 2 with a lot of stuff in it. Resources, medical supplies, fuel, ammo. Some of the ammo (Railgun shells) are lying around on the armory floor. 
3. Leave from colony and enter Hydrothermal Wastes through having 100 rep with coalition.
4. Enjoy the crash.

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment EntityPosition at position 5872. Previous segments: Segment { Identifier = SyncIds, Pointer = 32 }, Segment { Identifier = ChatMessage, Pointer = 185 }, Segment { Identifier = ChatMessage, Pointer = 448 }, Segment { Identifier = ChatMessage, Pointer = 1128 }, Segment { Identifier = ChatMessage, Pointer = 1696 }, Segment { Identifier = ChatMessage, Pointer = 2264 }, Segment { Identifier = ChatMessage, Pointer = 2640 }, Segment { Identifier = ChatMessage, Pointer = 3488 }, Segment { Identifier = ChatMessage, Pointer = 4368 }, Segment { Identifier = EntityPosition, Pointer = 5048 }, Segment { Identifier = EntityPosition, Pointer = 5224 }, Segment { Identifier = EntityPosition, Pointer = 5408 }, Segment { Identifier = EntityPosition, Pointer = 5640 }
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 162
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.ReadSingle() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 195
   at Barotrauma.Character.ClientReadPosition(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 262
   at Barotrauma.Networking.GameClient.<>c__DisplayClass119_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2146
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 2966
```

**Comment by Regalis11** [comment]
Thank you for the report!

Would it be possible to send us the save file this occurs in? That'd most likely help us a lot in diagnosing the bug. Note that you need to .zip it first, because github doesn't allow attaching files with the .save extension. Thanks and sorry for the inconvenience! :/

**Comment by CiteReh666** [comment]
Sure! Here it is.
[Трое в лодке, не считая клоуна.zip](https://github.com/Regalis11/Barotrauma/files/11781911/default.zip)
