### ISSUE TITLE
Component wire inferface is cut off at the top

### ISSUE THREAD

**Issue by Boolean-Buckeye** [Regalis11/Barotrauma#12180]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever I open a wiring interface for a component, the top is cut off to the point where I cant mess with the wires connected to the top input/outputs. This is annoying especially for power since all those lines are usually at the top.

### Reproduction steps

This happens in any game for me, whether in multiplayer or singleplayer so it is not related to save file, and happens also no matter how many restarts, so its not a temporary glitch, it is consistently always a problem for whatever reason in my environment.

![image](https://github.com/Regalis11/Barotrauma/assets/36829021/37e75a89-3359-4e5e-af7a-1de6701cefca)
In this particular screenshot it doesnt look so bad as many other cases but you can see that the signal_in words are cut off and these signals at the top are so high up that I cannot hover over the wires and therefore cannot detach these wires except by detaching the component from the wall which is very annoying, and impossible in the case of junction boxes and other installations.

![image](https://github.com/Regalis11/Barotrauma/assets/36829021/45f7ebdb-978f-4489-9664-0df21077513f)
Here is another example for a relay component, but pretty much all components interfaces have this problem

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

Also, I just started playing in the last week after a long time and this was an issue before the latest update too during the last week

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! This seems like a resolution-dependent issue, which resolution are you using?

**Comment by Boolean-Buckeye** [comment]
> Thank you for the report! This seems like a resolution-dependent issue, which resolution are you using?

3840x2160, also there is another issue related this that I have: 
![resolution_bad](https://github.com/Regalis11/Barotrauma/assets/36829021/e137e5aa-0c71-4e41-813f-1e8c818a88a9)

You can see that when I load the game it does not use the whole screen, I found that the way for me to get around this issue will be to go to the graphic settings of the  game and change the resolution to *any* other value, which will cause everything to re-render and then fill the whole screen..... and reset the resolution back to 3840x2160... which is a 3rd issue: I can't change the resolution to anything other than 3840x2160, I click the dropdown, then click apply and then the game just changes it back to 3840x2160.

And just for clarity, that trick of how I got the screen to fill correctly does *not* fix the junction box / component wiring UI display issue

So there are 3 observable issues here from my end and I guess I dont know if they are all related or not

**Comment by Regalis11** [comment]
Thank you for the extra info! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2b23f1430f9f48de16193e948a196dc5389e6eaa (commit in our private repository)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by mizvekov** [comment]
For reference, I independently made a small mod that fixes this issue for current versions of the game:

https://steamcommunity.com/workshop/filedetails/?id=3018718619

But I am glad this is fixed upstream and I won't have to maintain this any further.
