### ISSUE TITLE
BOTs clean-up food items whilst being consumed by pets 

### ISSUE THREAD

**Issue by logan-six** [Regalis11/Barotrauma#12182]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Any BOT currently executing the order Clean Up items will remove dropped food items whilst being consumed by a pet.

### Reproduction steps

1. Drop food item next to pet
2. Wait for pet to start feeding
3. Assign order Clean Up Item to a BOT
4. BOT will remove and store partially eaten food item  from pet

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0fd9791268f49e946ad80b6f01d7ab4c94c0440f (commit in our private repo).

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing.
