### ISSUE TITLE
40mm Mini Nukes inside Nuclear Shells don't work

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#12196]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There is no noticeable difference in damage when firing empty Nuclear Shells and Nuclear Shells loaded with 40mm Mini Nukes.
Damage done with empty Nuclear Shell: 
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/f537bb7c-eb7c-454f-ab7f-4ba138aca0ae)
Damage done with Nuclear Shell loaded with 40mm Mini Nuke:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/54255a73-4844-447e-87df-9436279dd04b)
Noticed that nuclearshell uses `<StatusEffect type="OnImpact" target="Contained" allowwhenbroken="true">` while the regular railgunshell uses `<StatusEffect type="OnBroken" target="Contained" >` to trigger contained items.
Tried changing from "OnImpact" to "OnBroken" and it seems to make a difference as that makes Nuclear Shells loaded with 40mm Mini Nukes deal noticeably more damage than empty ones.
Damage done with empty Nuclear Shell:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/bf3ddf68-fb13-42e5-8c5a-64a500fab045)
Damage done with Nuclear Shell loaded with 40mm Mini Nuke:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/a08d666b-be98-4e5b-9a4a-48a219fe1962)

### Reproduction steps

1. Shoot abyss creature with empty Nuclear Shell (with disableenemyai)
2. Heal abyss creature and shoot it in the same spot with a Nuclear Shell loaded with a 40mm Mini Nuke and compare damage

### Bug prevalence

Happens regularly

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d84fef37a0fa6520493d7f83e0515a519c77d8e1

**Comment by Jasontti** [comment]
Tested.
No issues found.
Clolsing.
