### ISSUE TITLE
Bots abandon operate orders when the target is unsafe (e.g. when the room floods)

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#12192]
They should get out of the unsafe room but not abandon the objective.

Steps to repro:
- Occurs reliably at least with operate turrets and then spawning an explosion to flood the room
- Doesn't seem to trigger as easily when spawning monsters and couldn't repro at all by spawning fires, but it should also affect those conditions. The priority system just triggers the other objectives more aggressively in those conditions, which doesn't let the operate objective run

Fixed in Regalis11/Barotrauma-development#4306.

**Comment by Jasontti** [comment]
https://github.com/Regalis11/Barotrauma/issues/11925 Tested again, no issues.

Couple rounds of flooding, fire and creature attacks did not cause bots to completely abandon their orders.
