### ISSUE TITLE
Pets added by mods cause crash in campaigns if mod is removed.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12199]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Fairly simple issue involving custom pets, if the mod is not loaded (the creature doesn't exist) the game will crash instead of not spawning the pet. seems simple to fix, crash didn't occur when I added null checks:

SharedSource\Characters\AI\PetBehaviour.cs line 454:
![image](https://github.com/Regalis11/Barotrauma/assets/29177976/66532722-45fb-4385-8f16-52bbfb8b0359)

### Reproduction steps

1. Create or use a mod containing a custom pet
2. Start a campaign.
3. Spawn custom pet in the campaign
4. Remove mod adding said pet.
5. attempt to load campaign.

### Bug prevalence

Happens every time I play

### Version

Other

### -

Branch Traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/2acd9585e23d2d9f8cd24a927fd3c41c556f77d8

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75a5f80e363968bb8022798e3ad5e0a03fa662c9. Pushed straight to to https://github.com/Regalis11/Barotrauma-development/pull/4307 (which has already been reviewed and in QA atm) - this is a simple null check, not necessary to review imo.

**Comment by Regalis11** [comment]
Merged
