### ISSUE TITLE
being on ladder makes it difficult to press buttons

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#12197]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It's very hard/impossible to click on anything nearby the player when on a ladder

* the character flips to the far side as soon as the cursor goes on "this" side of the ladder
* the distance seems to be further than the max interact distance when standing?

https://github.com/Regalis11/Barotrauma/assets/5103517/acaf6d4c-c73e-41b9-9ee4-81a6913770bb

### Reproduction steps

1. button near ladder
2. get on ladder
3. cursor over button
4. character goes away from button and button is not selected

### Bug prevalence

Happens regularly

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
I remember this issue has been here since the update that allows player to flip their characters on ladders. Don't know why this isn't mentioned by anyone then. The interaction range is too short when player is climbing a ladder.

**Comment by Rokvach** [comment]
Tested working correctly, can be merged and closed.
