### ISSUE TITLE
Projectiles/items with high enough velocity phase through walls, doors, hatches, etc.

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#122]
Seems like projectiles or just items in general with high enough velocity will be able to phase through the ship's hull, doors and hatches. Is there a solution for this?

Here's a webm: https://puu.sh/yDudt/dad32d4a54.webm

**Comment by alextbw** [comment]
uh-huh, the revolver round can completely destroy the wall
