### ISSUE TITLE
Engine propeller damage reduced by a lot

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12205]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I do not know if you are aware, but the propeller damage is very small in the current version. The changelog does not list this alteration which makes me believe it is unintentional.

### Reproduction steps

* Prop strike a year ago: knocks you out and you bleed to death
* Prop strike now: a gentle caress

### Bug prevalence

Happens every time I play

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
This was intentionally changed a couple of years ago, it generally just lead to frustration to get instakilled by the propeller with no advance warning.
