### ISSUE TITLE
horizontal shell invert and incorrect texture bug in editor

### ISSUE THREAD

**Issue by DudeOfSheep** [Regalis11/Barotrauma#12204]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After playing through singleplayer campaign enough to unlock my custon built sub, I discovered I had made an error in building it and went to the editor to fix it. However, upon opening it, all Shell A 0 Degrees structures were flipped on the y axis, and had some kind of odd texture on them. Reseting the sprite did nothing, nor did placing a new shell. Restarting the game did normalize the texture again and revert the shells to their previous state.

The top of my sub featuring the inverted shell and texture glitch:
![image](https://github.com/Regalis11/Barotrauma/assets/106273903/451cd0bd-e20a-497f-ad49-bba1de3b9c34)

Closeup on the texture:
![image](https://github.com/Regalis11/Barotrauma/assets/106273903/9f6eebaa-6aca-4dc7-b0d8-b576131c178a)

A newly placed Shell:
![image](https://github.com/Regalis11/Barotrauma/assets/106273903/f7fbc430-cc07-4d72-93eb-6ecd19c29907)

### Reproduction steps

After retracing my steps I was unable to re-create the bug or find out why it happened.

### Bug prevalence

Just once

### Version

v1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by giists** [comment]
Could you provide the file for the sub please?

**Comment by Regalis11** [comment]
No know steps to repro, closing. The submarine file might give us some more clues for diagnosing this though, let's reopen this if we get a hold of one.

**Comment by DudeOfSheep** [comment]
I'm so sorry, I was not notified when I got the email, here's the file.
