### ISSUE TITLE
"Spectate" button failed to work after host tried to take a break

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12216]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Host tried to become a spectator so he could take a break. Save & quit -> Spectate didn't work as expected.

### Reproduction steps

1. Ongoing campaign
2. Save & quit
3. Click "Spectate"
4. **Click "Quit"**
5. Load the campaign to continue

Expected that the player who selected "Spectate" would be a spectator. Instead they appeared as players.

### Bug prevalence

Every time

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this, the host seems to spawn as a spectator when the "spectate" checkbox is checked:
https://github.com/Regalis11/Barotrauma/assets/14351070/a7f8bc56-b427-4df1-84d1-e052b9552a47

**Comment by mygamingaccount** [comment]
I remember for a moment the game mode switched to sandbox. It was probably unintentionally done by the host.
By doing that, I am able to reproduce the issue. Looks like it's more of an edge case than I though. Editing repro steps...


https://github.com/Regalis11/Barotrauma/assets/68995233/106a0bc3-6f47-4fb3-8237-c01f2d95ad30

**Comment by Regalis11** [comment]
Thanks, I was able to repro it now! Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/03651e344dfb942a8e1ec63c499d98c9f54e28c6

**Comment by giists** [comment]
No issues found, closing.
