### ISSUE TITLE
Toxins Cabinet is a very long run from the Medbay on the Orca 2

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12219]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Toxins Cabinet on the Orca 2 is located far away from the Medbay, all the way up in the Armory. This makes it very annoying to regularly use or store resources in there, and with the upcoming Storage Container removal wherein every storage slot will be more precious than ever, having a large amount of the Medic's personal storage be essentially inaccessible to them is frustrating.

There is a spot above the news stand in the Medbay where the Toxins Cabinet could be placed instead. Although the news stand may have to be swapped out for a smaller loose panel/vent sprite to make everything fit.

**Note:** All other vanilla Submarines in the game have a Toxins cabinet located either inside the Medbay or right next to it, never more than a few meters on any of them.

**Example:**
![Orca2_Toxins](https://github.com/Regalis11/Barotrauma/assets/5988156/782b5943-0ab9-4258-9fd7-e0084e03b1af)

### Reproduction steps

1. Start a Multiplayer Campaign, or enter the Sub Editor
2. Get on the Orca 2 Submarine
3. Proceed from Medbay to the Toxins Cabinet in the Armory
4. Return to the Medbay
5. Compare the time taken to do this versus other submarines

### Bug prevalence

Happens regularly

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/fcb0273b383384c96c8344d0fcbfe4b07c2a80cd (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing.
