### ISSUE TITLE
Traitor mission fails immediately after starting

### ISSUE THREAD

**Issue by HyperB1** [Regalis11/Barotrauma#12217]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I got the traitor's mission "Acid Party" it instantaneously failed and I was given another mission. I still found the deliriumine in the vent, even after the mission has "failed".

### Reproduction steps

1. Start a regular mission with the "Acid Party" traitor mission in the latest unstable version
2. Watch it immediately fail

### Bug prevalence

Just once

### Version

Other

### -

[Unstable] version

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The next update is going to include a major rework of the traitor system, and this mission will be removed, so we shouldn't spend time fixing this.
