### ISSUE TITLE
Mutated Raptor's Bane Explosion affecting Oxygen Tanks and Welding Fuel Tanks

### ISSUE THREAD

**Issue by sullivas67** [Regalis11/Barotrauma#12210]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Dropped or thrown Mutated Raptor's Bane reduces the durability of oxygen tanks and welding fuel tanks.

### Reproduction steps

1. Grow Raptor's Bane near cabinet with filled tanks in them
2. Wait for mutated version to drop
3. Throw or wait for fruit to pop
4. Observe tank durability

### Bug prevalence

Happens regularly

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Lepestochek** [comment]
Can you clarify what's this about? Tanks (oxygen and welding) lose durability when close to a fire, and explosions are basically a fire source

**Comment by TerminatorTM** [comment]
It is not a bug as said previous author. Same effect you can see with tanks in your inventory then you caught in explosion or with oxygen tanks in oxygen tank shelf during fire or explosion near them.

**Comment by Regalis11** [comment]
Yeah, this is intentional: fire and explosions damage oxygen and welding fuel tanks.
