### ISSUE TITLE
Crashing when reaching a point without an outpost

### ISSUE THREAD

**Issue by TheSauceMan-6a4632** [Regalis11/Barotrauma#12218]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game freezes on the end-round screen for a few seconds before crashing without an error message, seemingly only when the sub arrives at a point without an outpost.

### Reproduction steps

1. Start singleplayer campaign
2. Acquire the vanilla Orca 2 (unclear if the vessel matters)
3. Acquire aprox. 8 AI crew members (unclear if crew matter)
4. Get to The Aphotic Plateau
6. Start any mission (unclear if mission matters)
7. Reach a point without an outpost
8. Freeze on end-round screen for a few seconds before closing out

It's only happened to me a few times so it's hard to tell exactly what's causing it, but it has only ever happened when arriving at a point without an outpost.

### Bug prevalence

Happens every now and then

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
No crash report generated :(
```

**Comment by Regalis11** [comment]
Thank you for the report!

This could potentially be related to https://github.com/Regalis11/Barotrauma/issues/12045, although this is the first time I've heard of the issue crashing the game. If you happen to have a save file in which this occurs consistently, it'd help us a lot in diagnosing this. Thanks and sorry for the inconvenience! :/

**Comment by TheSauceMan-6a4632** [comment]
Thanks for the reply!

I've been trying to reproduce it using the console in a new save cloned from my original, but unfortunately haven't had any luck. I'll post the save in this thread if I manage to get the circumstances nailed.

Thanks again, duderino!

**Comment by Regalis11** [comment]
No known steps to repro, closing
