### ISSUE TITLE
Servers don't end round when all players are dead/unconcious.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1222]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Before, if all net players were unconcious the round would end. Now even if every human player is dead, a game will continue. it even continues when all the AI humans have died too so there is 0 living crew.

This was occuring in mission as an additional note.

![image](https://user-images.githubusercontent.com/29177976/53788051-884ca480-3f18-11e9-8e68-9b2c7bc0468e.png)

**Steps To Reproduce**
Host a server as host via client, spectate, have everyone die including AI's (I had 4 on fill)

**Version**
0.8.9.5 Closed alpha

**Comment by Regalis11** [comment]
The round doesn't automatically end if autorestart is not enabled, I'm guessing that's the issue?

**Comment by NilanthAnimosus** [comment]
that is probably it, I was disabling autostart due to having issues with it as players would join an always in progress round with my character just standing there.
