### ISSUE TITLE
[Unstable] A few leftover storage containers

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#12225]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While storage containers are being made unobtainable, there are still a few ways of acquiring them. I do not think it is a huge issue considering the intent of the removal was to balance cabinet capacity as well as how unlikely it would be to obtain one or more of them in a single campaign but I still felt it might be good to point these out.

1. The event clownrelations1
The event spawns a storage container which the player can keep after finishing the event:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/b9df465c-0c1e-45df-bf62-96d0a1ea4453)
2. The Berilia
There is a preplaced storage container above ballast tank B:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/e750bfe4-9e59-4a55-9f15-32f284666c60)
3. Wreck corpses
The assistantcorpse1 has two item sets which have a storage container, making it possible to find one in wrecks (albeit incredibly rarely)
```
<ItemSet commonness="0.2">
  <Item identifier="commonerclothes4" equip="true"/>
  <Item identifier="toolbox" equip="true"/>
</ItemSet>

<ItemSet commonness="0.1">
  <Item identifier="commonerclothes4" equip="true"/>
  <Item identifier="toolbox" equip="true">
    <Item identifier="divingknifeunique"/>
  </Item>
</ItemSet>
```

### Reproduction steps

1. `triggerevent clownrelations1`
2. Open Berilia in sub editor
3. assistantcorpse1 item sets in Corpses.xml

### Bug prevalence

Happens regularly

### Version

Other

### -

v1.1.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7649096d81f353837af174dc61c9978577a3118e and https://github.com/Regalis11/Barotrauma-development/commit/27a150d0f51e9d8bf0d604fec4f219cd42ff2da4
