### ISSUE TITLE
Explosives detonate at railgun loader when the railgun shell containing it hits something.

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12223]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you load a railgun shell with explosives like C4 Block, the C4 will detonate at the loader after you launch the shell containing it and hit something.

### Reproduction steps

1. fill a railgun shell with a C4 Block.
2. fire the railgun shell and make sure it hits something.
3. observe the C4 creates an explosion at the railgun loader instead of where railgun shell hits.

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.1.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/47c5f9f574f646011af4a4fa6eb98dff75a3777b
