### ISSUE TITLE
Turret Auto Operate does not fire if placed inside a hull

### ISSUE THREAD

**Issue by Faryzal2020** [Regalis11/Barotrauma#12233]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Any turrets with Auto Operate on does not fire at targets if they're placed inside a hull, they're still tracking the enemy and still able to fire if controlled with a periscope, but does not fire by itself.

### Reproduction steps

(tested in vanilla game sub editor)
1. load a vanilla sub then copy one of the existing turrets to the side of it
2. wire only the power and turn on Auto operate
3. test out and spawn an enemy in front of it, the auto turret will shoot at it normally
4. back to editing then add a hull big enough to cover around the auto turret and add gaps on every side of the hull to let water in
5. test the sub, spawn an enemy inside that new hull right in front of the turret
6. the auto turret only targets and track the enemy, it does not fire at it

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by giists** [comment]
Reproduction steps confirmed.

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6764fc6ca89aa55b2acdc6ce8560eb03eaef6070 (commit in our private repo)

**Comment by giists** [comment]
Everything seems fixed, closing.
