### ISSUE TITLE
[Unstable] Traitor mode issues

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#12236]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Heres some more issues which weve encountered during our test session of the traitor mode regarding the mode specifically:
1: When using the accusation and correctly identifying a traitor, the mission end screen will still use the icon as if the crew failed to do so, showing the crossed out mask 
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/20b5ee74-fc2a-45e0-916a-4cb5eb88ceed)
2: While this was mentioned before on the discord, ill mention again that traitor missions regarding swapping oxygen tanks for welding tanks and vice versa dont work well as they require you to swap them on tools people are wielding aswell, so probably need some rethinking
3: Unsure what caused this, but at some point after a few level transitions traitor missions no longer displayed after finishing a round, though people were still selected as traitor and recieving missions
4: Blood samples part 2 incorrectly displays for the traitor in the mission log
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/c8cbd78a-2914-400b-bf18-8e1e4abafe38)
5: Blood samples part 2 caused some crashes![image](https://github.com/Regalis11/Barotrauma/assets/104232152/f1007102-3e41-4656-9f79-2d6c0dafc845)
6: At some point the crew inexplicably recieved a whole lot of xp after finishing a round, some major lag happened as it was happening
[Very_sus_unstable_gaming_2023-06-27_1927_2.txt](https://github.com/Regalis11/Barotrauma/files/11887707/Very_sus_unstable_gaming_2023-06-27_1927_2.txt)

(7: Mining sabotage seems to be using placeholder text or is just missing a space)
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/b4d183c0-63f1-4e97-be34-a94999716304)

### Reproduction steps

1: Accuse a traitor correctly, the mission icon on level transition will still be crossed out, as if it was failed
2: Finishing the mission to swap Plasma cutter tanks is practically impossbile/quite unrealistic
3: Dont know what caused this
4: Recieve blood samples part 2 as a traitor mission, the targeted player isnt correctly displayed (happened once)
5: Blood samples part 2 caused a crash, possibly related to issue 4, otherwise unknown
6: Unknown but log is attached underneath the issue above

### Bug prevalence

Happens regularly

### Version

Other

### -

v1.1.1.0 (Unstable Traitors)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
It didnt record the sound sadly but here is the XP bug in 6.
Docking is very slow

https://github.com/Regalis11/Barotrauma/assets/73229309/ea1e7dd9-3111-4e08-8387-39d95cb8ea00


![image](https://github.com/Regalis11/Barotrauma/assets/73229309/7dde3b48-3783-4f46-a687-e8912e430e62)

**Comment by ubertpendragon** [comment]
On the Deepdiver Ducks mission, it was early in the campaign so we didn't have enough Rubber/Lead, it was not possible to complete the objective


![image](https://github.com/Regalis11/Barotrauma/assets/73229309/5c6726c5-3131-4467-8359-797f5ad3e3d2)

**Comment by ubertpendragon** [comment]
showofstrength crashes the server

[servercrashreport (5).log](https://github.com/Regalis11/Barotrauma/files/11890933/servercrashreport.5.log)

**Comment by ubertpendragon** [comment]
`undercover`
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6cc24a2f-5142-4300-b36f-dd4388c26b94)

**Comment by ubertpendragon** [comment]
`deadoralive`
Sootman id card doesn't have the Sootman name

**Comment by ubertpendragon** [comment]
`bloodsamples` crashes the server
[servercrashreport (6).log](https://github.com/Regalis11/Barotrauma/files/11891169/servercrashreport.6.log)

**Comment by Jasontti** [comment]
Tested.
>1: When using the accusation and correctly identifying a traitor, the mission end screen will still use the icon as if the crew failed to do so, showing the crossed out mask

Feedback from suspection is displayed now at the crew window.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/0e424401-bd67-41dc-8280-40a811be8d8f)

>2: While this was mentioned before on the discord, ill mention again that traitor missions regarding swapping oxygen tanks for welding tanks and vice versa dont work well as they require you to swap them on tools people are wielding aswell, so probably need some rethinking

No changes to test yet.

> 3: Unsure what caused this, but at some point after a few level transitions traitor missions no longer displayed after finishing a round, though people were still selected as traitor and recieving missions

Could not reproduce or has been resolved.

>4: Blood samples part 2 incorrectly displays for the traitor in the mission log
>5: Blood samples part 2 caused some crashes

Working correctly

>6: At some point the crew inexplicably recieved a whole lot of xp after finishing a round, some major lag happened as it was happening

No issues found

> (7: Mining sabotage seems to be using placeholder text or is just missing a space)
> showofstrength crashes the server
> undercover
> Sootman id card doesn't have the Sootman name
> bloodsamples crashes the server

Fixed
