### ISSUE TITLE
[Unstable] Couple of UI issues

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#12237]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1: Level transition mission logs tend to be written out twice after a couple of levels, not sure what causes this 
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/beeab15b-e891-42fc-aa4a-fac8f7b784d3)

2: Pause menu buttons are spaced quite oddly now, having a lot of space between each button
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/80ee8dd5-8222-4bcf-8ee1-2d403c7987a9)
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/6105bf94-2921-40c5-a09a-833f17a031f3)

(3: The suspicious activity report button is the same colour as the report monster button, either an issue or a placeholder, maybe...)

4: Minor overlapping between vc activity and accusation button 
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/6ef1e432-b5ee-4403-ac8a-f2924d6a4b10)

### Reproduction steps

1: Unsure of the cause
2: Try just accessing the pause menu ingame, the spacing is off
3: The color between the monster report and traitor report is identical and they could be mistaken for another 
4:Watch another players vc actvivity while using the traitor mode

### Bug prevalence

Happens every time I play

### Version

Other

### -

v1.1.1.0 (Unstable Traitors)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rehexr** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/bfb24c18-2003-4bd0-bb07-b2a2a2da6caf)
Menu Ui is being wierd in a different way now

**Comment by Regalis11** [comment]
@Rehexr In what way would you expect it to work?

**Comment by Rehexr** [comment]
Ill just keep it short and say that the new menu has a lot of empty space, which both me and pretty much everyone testing the traitor build has noticed.
I think its best demonstrated when you can see the old and new menu spacing side by side. 
Previously 
![unknown-249](https://github.com/Regalis11/Barotrauma/assets/104232152/f732863b-3379-4e87-8fb5-b11f0fb14677)

**Comment by Rehexr** [comment]
misclick, but point still stands

**Comment by Jasontti** [comment]
Tested,
No issues found.
Closing.
