### ISSUE TITLE
Bots get stunned near fabricator in Camel

### ISSUE THREAD

**Issue by Arctomachine** [Regalis11/Barotrauma#12230]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

From time to time I find bots kneeling near fabricator. Medical glasses show that bot is stunned, but medical interface shows no signs of stun on any body part. Bots keep doing it until manually taken control of, and there is no stun then too.
![image](https://github.com/Regalis11/Barotrauma/assets/29041820/4d4ac265-ea7d-4f23-b055-ac312a17006c)

### Reproduction steps

Happens randomly.

### Bug prevalence

Happens every now and then

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AdamH-Daedalic** [comment]
Tested on v1.0.21.0

Tested this for a while and couldn't get it to reproduce. I watched the fabricator area like a hawk and even had bots idling around it a lot but never encountered this. Is it possible that it was from a botched repair attempt?

**Comment by Arctomachine** [comment]
I doubt it has anything to do with repairs, but it is possible. However they spend too much time in this position, usually unless manually selected and moved away, as they resist simply dragging them away and not move on their own.
I also encountered something similar with controlled character. Got ragdolled in this exact spot without any reason while simply walking by, but it only happened once so far and very briefly.

**Comment by AdamH-Daedalic** [comment]
Tried some more to reproduce it, damaging the various equipment around it to see if that had any impact on it, ran player controlled characters through the spot, tried running around the sub to see if it happened anywhere else...all to no avail. No ragdoll, no stun. 

I did notice that bots would frequently stop and stand in the exact spot shown in your picture, however would not get stunned, just stand there idle for a while. Maybe the devs can shine some light on this as I can't seem to figure out what is going on here.

**Comment by itchyOwl** [comment]
I'd suspect the bot gets stunned because of a failed attempt to repair the fabricator, which can happen when a low-level engineer repairs the item. If that's what happens here, it's a feature and not a bug, though it's up to debate whether the fabricator is defined with to high skill requirement for the repairs.

**Comment by Regalis11** [comment]
No known steps to repro - it's likely that this was caused by a failed repair.
