### ISSUE TITLE
[Unstable] Item stacking inconsistencies

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#12235]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Excuse the length of this one, just went and checked most items for their stacking sizes, so ill get started

**Ammo**
1: 40mm Grenades all have a stack size of 32, which seems a bit much, with the exeption of 40 mm nukes, which still have a stack size limit of 8
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/7871f6ce-f6a0-4a09-aa93-aec90caadab3)
2: All throwables have a stack size of 32, with the exeptions of nitroglycerin, which has a stack size of 8 and molotov cocktails, which inexplicably have a stack size of 12, whichever of these is intended i dont know but it seems oddly inconsistent
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/82defffe-d0ee-4774-a15b-69831896cc4b)
3:All magazines have a stack size of 8, which seems fine, until you realize that this also applies to inventory stack size, meaning you can now carry 8 mags in one inventory slot, instead of 2 like before 
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/906e8dc1-878b-4bfa-8fe9-5613b9aa588e)
Edit:
4:All single bullets and shells now have a max stack size of 8 within the players inventory. previously it was 12. Same goes for putting bullets in a toolbelt
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/1c2e91aa-eef9-49c6-af98-e4289a0f9a7f)
**Meds**
1: All syringes have a stack size of 32, including most stimulants like combat stimulant, but the three specific stimulants of Steroids, Hyperzine and Meth have a stack size of just 8
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/d96878d0-bf4c-4ff0-b077-498489bd6041)
2: The energy drink only has a stack size of 8, unlike the protein bar and tonic liquid which have a stack size of 32 
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/e2fef0a7-de26-4ef1-b8f8-5220bf28f2bf)
3: Unlike all other syringes and materials, which have 32, the husk extract only has 8 stack size and the eggs 4 stack size, though i suppose this could be intentional
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/a8c0f11a-64d6-4bb8-9b10-2714e67b1cf9)

**Materials**
1:The alien materials of Sulphurite and Oxygenite shards only have a stack size of 8, unlike all the other alien materials, which have a stack size of 32
![image](https://github.com/Regalis11/Barotrauma/assets/104232152/219f0237-31b0-45b2-9682-24e2fb667f3a)

### Reproduction steps

I wrote it all down above

### Bug prevalence

Happens every time I play

### Version

Other

### -

v1.1.1.0 (Unstable Traitors)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c36276b2fa38d6ff7f19648f8735838a82e810b6

**Comment by AdamH-Daedalic** [comment]
Checked the stack limits of all of the items mentioned above along with other items in the same categories that have been changed and they are now consistent with one another in those groups. Closing
