### ISSUE TITLE
faultyrobes traitor event is too complicated

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12243]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You need to

1. Find the crate that contains robes and husk caller, which can spawn anywhere on the ship and found by someone else
2. Call husks
3. Have the husks interact with the crew, so you somehow need to let husks inside or spawn them when the crew is outside
4. Test each robe (or give robes to the crew which is an immediate giveaway)
5. Dump the faulty robes

Summoning husks is fun but the whole process is too complicated.

Hiding the husk caller in a vent, summoning husks and getting rid of antibiotics/calyxanide would probably be easier, or replacing calyxanide syringes with placebos...

### Version

Unstable

**Comment by Regalis11** [comment]
The event has been made much easier by reducing the number of robes to 3 now, so it's easy to test them yourself as long as you can make contact with the husks somehow.

**Comment by Jasontti** [comment]
Tested and no issues found.
