### ISSUE TITLE
Great Sea biome doesn't have its own visuals

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12246]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Besides Piezo Crystals, the Great Sea biome is still using Cold Caverns assets and lighting.

Great Sea wall textures but also rock chunks are all cold caverns'.

Example of visuals from [changes I made](https://steamcommunity.com/sharedfiles/filedetails/?id=2995945084)
Not the finest sprite work but it looks different

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ad4a10da-a1b8-49dd-8fda-382f9722180f)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/89166841-c3b7-4ab6-a388-9e0b2f4f1def)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/c6c82ef9-f164-4eea-810f-113e9ac17d00)

Examples from [Friths Biomes](https://steamcommunity.com/sharedfiles/filedetails/?id=2020332046)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/d3f097a9-5523-49be-8ffe-c6358405f5b0)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/8de64d89-874c-4953-bb1e-d5392ad6d7dc)

**Comment by Regalis11** [comment]
This isn't a bug: I think a pull requests or discussions would be a more appropriate place for improvement suggestions. :)
