### ISSUE TITLE
Traitor events require preplaced Loose Vents

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12242]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some traitor events require Loose Vents to function. 
Sub builders don't always thing about placing loose vents around the submarine. 

`      <TagAction criteria="itemtag:hidden" tag="loosevent" chooserandom="true" />`

Consider making regular vents behave as loose vents (1 inventory slot), make them non-interactable by default, and somehow make them all interactable if traitor mode is on? Or have traitor exclusively interact with vents (using traitor ID tag?)

### Version

Unstable

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8a7084d0ec62e4de4a399efe6d03e12c59af3700 by making the sub editor display a warning if there are no loose vents or panels in the sub.

I don't think we can rely on using normal vents, because they may not always be placed in a position reachable by players.

**Comment by ubertpendragon** [comment]
> I don't think we can rely on using normal vents, because they may not always be placed in a position reachable by players.

One problem we've run into is that the game gives you traitor missions that use loose vents in subs that don't have loose vents. 

Many workshop subs (and vanilla?) probably don't have loose vents, so that means after the update many subs will be excluded from parts of the traitor update unless manually updated, but in the meantime some of the authors might have stopped playing entirely and won't update them. 

You'd also need to notify very clearly the fact that those subs don't have loose vents either in the update notes or in the submarine selection. 

Converting vents to loose vents despite the risk of being unreachable still feels like a necessary solution

**Comment by Jasontti** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/commit/8a7084d0ec62e4de4a399efe6d03e12c59af3700
No issues found with loose vent/panel/panel and "hidden" tag added to current inventories.

**Comment by Regalis11** [comment]
I think ubertpendragon has a valid point though, we probably should convert some of the vents to loose vents in subs that don't have any. Otherwise it could cause some confusion when people start playing with the new traitor system on custom subs (and just have most of the events not work with no warning or explanation on why).

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/9edd58aeecb3236290c2ba0012eabda827f88ee3: if there are no loose vents or panels, some of the normal vents are replaced with loose vents.

**Comment by AdamH-Daedalic** [comment]
Tested against fix/traitor-fixes

All vanilla subs spawn with loose vents/panels that function correctly when utilised in conjunction with traitor events that use the hidden locations. 

Player is also given a warning in the submarine editor when their vessel does not have any hidden compartment items and that it will prevent them from fully experiencing the traitor events.

Closing

**Comment by Regalis11** [comment]
> All vanilla subs spawn with loose vents/panels that function correctly when utilised in conjunction with traitor events that use the hidden locations.

All vanilla subs should already have pre-placed loose vents or panels: this should be tested on subs that don't.

**Comment by Jasontti** [comment]
Vanilla subs show notification about not having vents in console at the start of the round.
(Barsuk)
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/a1792925-6a32-4e10-9fe1-a88d4948575d)
Sometimes subs with no loose vents can force one to be in not reachable location, ie. behind a fabricator, so i think that strongly suggesting to have one in sub editor is good.
No other issues found.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4357/commits/9ab1ab0a9351482d31242deca94c84f3d207ddf5

**Comment by Jasontti** [comment]
No issues found.
Closing ticket.
