### ISSUE TITLE
File "serversettings.xml" not found

### ISSUE THREAD

**Issue by ZXJSY** [Regalis11/Barotrauma#12252]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After the new version update, every time the server is added, an error will be reported. Only when the server owner ends the tour can the problem be solved (and since you can know that the player disconnected due to network issues, why do offline players still suffer from brain death)

### Reproduction steps

After the new version update, every time the server is added, an error will be reported. Only when the server owner ends the tour can the problem be solved (and since you can know that the player disconnected due to network issues, why do offline players still suffer from brain death)

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
06/10/2023 00:07:39 - [06/10/2023 00:07:39]
  Saving banlist
   06/10/2023 00:07:39 - [06/10/2023 00:07:39]
  Saving banlist
   06/10/2023 00:06:42 - [06/10/2023 00:06:42]
  子小金石页 is causing the server to slow down.
   06/10/2023 00:06:42 - [06/10/2023 00:06:42]
  子小金石页 is causing the server to slow down.
   06/10/2023 00:06:41 - [06/10/2023 00:06:41]
  Saving client permissions
   06/10/2023 00:06:41 - [06/10/2023 00:06:41]
  Saving client permissions
   06/10/2023 00:06:41 - [06/10/2023 00:06:41]
  子小金石页已加入服务器
   06/10/2023 00:06:40 - [06/10/2023 00:06:40]
  Server started
   06/10/2023 00:06:40 - [06/10/2023 00:06:40]
  Using SteamP2P networking.
   06/10/2023 00:06:40 - [06/10/2023 00:06:40]
  Starting the server...
   06/10/2023 00:06:40 - WARNING: File "serversettings.xml" not found. Starting the server with default settings.
   06/10/2023 00:06:40 - Couldn't load xml document "serversettings.xml"! {Could not find file 'D:\steam\steam\steamapps\common\Barotrauma\serversettings.xml'.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 400
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 109
   06/10/2023 00:06:40 - Selected shuttle: Hemulen [JE]
   06/10/2023 00:06:40 - Selected sub: # TestingSpace JobsExtended
```

**Comment by Regalis11** [comment]
Thank you for the report! It seems there is no server settings file in the game folder. The game should create one automatically when you start a server though - does that not happen?

**Comment by Regalis11** [comment]
No known steps to repro, closing
