### ISSUE TITLE
Toxins Cabinet lacks ID requirements on the Camel

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12263]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Camel's Toxins Cabinet has no special ID requirements, having only **idcard** which allows anyone to access it.

Ideally, it would have **id_medic,id_captain** to restrict it, of which the Medic and Captain spawn points already have on this submarine.

![camel_toxins_id](https://github.com/Regalis11/Barotrauma/assets/5988156/9c822f0e-2e52-482e-9be6-0013d3d3a4cd)
![camel_toxins_example](https://github.com/Regalis11/Barotrauma/assets/5988156/7c221950-6950-4736-ade7-4a40e1a3abd4)

### Reproduction steps

1. Start a Campaign or enter the Submarine Editor
2. Enter the Camel Submarine
3. Attempt to access the Toxins Cabinet as any non-Medic or non-Captain role

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### -

Also occurs on v1.1.2.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ee3b7cabbee40c0600112b3c0849a284340a40ca (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
Toxin cabinet has "idcard" with id_medical and id_captain, so everybody can access it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c78cf57fd87cd827365f27edcf2d6a8830a32074

**Comment by Jasontti** [comment]
No further issues found.
Closing ticket.
