### ISSUE TITLE
shuttle/main sub sonar POI markers do not show in sub editor test mode

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#12261]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

detached shuttles do not show their location on the main sub nav and vice versa in editor's test mode

### Reproduction steps

1. load kastrull in editor
2. test mode
3. detach shuttle
4. check main nav - no sonar POIs for the drone (or main sub)

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf055a9077ac71ec5381c9f71946e3f33fcbed30

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
