### ISSUE TITLE
Liquid Oxygenite simultaneously explodes and injects on human impact when fired from a Syringe Gun

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12267]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Liquid Oxygenite will both cause an explosion on direct impact with someone, as well as inject a dose of itself in them (causing further Organ Damage).

Relates to issue #10910 

![explode](https://github.com/Regalis11/Barotrauma/assets/5988156/e3ba2b5f-53cd-4fc9-8e8f-c2fb78bf305c)
![organ_damage](https://github.com/Regalis11/Barotrauma/assets/5988156/691e59f4-94ff-44d4-88e5-a5c5b8cbc82a)

### Reproduction steps

1. Start a campaign
2. Acquire a Syringe Gun and Liquid Oxygenite
3. Fire the Liquid Oxygenite directly at a crewmember with the Syringe Gun
4. Observe the explosion and Organ Damage accumulation

### Bug prevalence

Happens every now and then

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I don't think this is a bug though, just a side-effect of liquid oxygenite exploding on impact. If you want to inject it "safely", it should be done by hand through the health interface.
