### ISSUE TITLE
[UNSTABLE] Arc Emitter refuses to fire

### ISSUE THREAD

**Issue by Quink-Fix** [Regalis11/Barotrauma#12269]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Arc Emitter does nothing when aiming and 'firing' using left click; the crosshair greys out to indicate cooldown, but battery charge is not used and there is no effect.

### Reproduction steps

I'm unsure how it occurred, so I'm attaching the save file to this bug report. 
1. Load save
2. Select engineer
3. Equip the Arc Emitter on her belt slot
4. Attempt to fire Arc Emitter
[Save_20_Fixt.zip](https://github.com/Regalis11/Barotrauma/files/11928754/Save_20_Fixt.zip)

### Bug prevalence

Just once

### Version

Other

### -

Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/df905b44574ec9f8777355f9d99b28c74e619667 (commit in our private repo)

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll keep the ticket open until we've verified the fix is working internally. Just testing the arc emitter works is not enough: we also need to verify the changes don't affect other kinds of EDCs.
