### ISSUE TITLE
Attaching motion detector, detonator, etc. outside the sub made the item disappear

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12268]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Attached a detonator and a motion detector to the fin just outside the lower airlock of the Orca 2, and they disappeared immediately

https://github.com/Regalis11/Barotrauma/assets/68995233/eaec11b5-9c0e-4e08-88c2-4e7c108b1b51

### Reproduction steps

Attach item to wall outside the submarine (fins and masts allow you to attach)
Item disappears

### Bug prevalence

Just _twice_

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
There was a case when a ruin scanner got lost this way, so the mission failed.

**Comment by giists** [comment]
Reproduction steps confirmed, but seems like it only happens in multiplayer.

**Comment by giists** [comment]
No more issues, closing.
