### ISSUE TITLE
Floating alien weapon in the abyss (round 2)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12277]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You might remember #10565

This time, it's a scripted event spawning the floating alien weapon in the abyss:

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6ce9ab01-2cb0-4f56-9591-cb1498a93fa4)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/c693b2b4-98fc-4c38-a643-7f33be91fe2d)

outpostevents.xml
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/39cf5327-129d-4641-9175-0a556999927f)

### Reproduction steps

Generate a Plateaubasic level in leveleditor and chances are the event will be there (seems to spawn with ruins)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/42e1ba9f35242ba0ad963a45a8f2294cb0071c18

> Fixed mysterious floating fractal guardian weapons at the origin of the level. Happened because we disabled the characters after preloading them, but not the weapons they're holding.

**Comment by giists** [comment]
No more issues found, closing.
