### ISSUE TITLE
Diving Scooter Light Component tied to propulsion

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12270]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Diving scooters have had their light component tied to Propulsion for the longest time and it's safe to say it's neither very practical nor does it look good when the light cuts off as soon as you stop moving forward

Moving the light component to holdable so it's active by aiming (holding RMB) instead of propulsion (holding LMB):

https://github.com/Regalis11/Barotrauma/assets/73229309/c4d9deb8-1bc4-43cc-b45b-919c395d570d

```xml
    <Holdable slots="Any,RightHand+LeftHand" aimpos="90,0" handle1="-35,32" handle2="-27,34" msg="ItemMsgPickUpSelect" holdangle="-10">
      <LightComponent LightColor="220,255,150,200" range="500" powerconsumption="10" IsOn="true">
        <LightTexture texture="Content/Lights/lightcone.png" origin="-0.01, 0.5" size="1.0,1.0" />
      </LightComponent>	
	  <!-- activates the light when holding aim -->
      <StatusEffect type="OnSecondaryUse" target="This" voltage="1.0" setvalue="true">
        <RequiredItem items="mobilebattery" type="Contained" />
      </StatusEffect>
	  <!-- Battery drain when using the light, adds up with propulsion -->
      <StatusEffect type="OnSecondaryUse" target="Contained" Condition="-0.10" />
	</Holdable>
    <Propulsion force="150" usablein="water" particles="bubbles">
      <RequiredItems items="mobilebattery" type="Contained" msg="ItemMsgBatteryCellRequired" />
      <StatusEffect type="OnUse" target="Contained" Condition="-0.15" />
      <sound file="Content/Items/Diving/ScooterLoop.ogg" type="OnUse" range="500.0" loop="true" />
    </Propulsion>
```

Might need to add an <`update`> to refresh existing scooters

**Comment by Regalis11** [comment]
It'd be preferable if you posted these feature requests as PRs instead of disguising them as bug reports. ;) Addressed in https://github.com/Regalis11/Barotrauma-development/commit/16664fa52fc81b7f2b3ef5f9e1f590718f488c62

**Comment by ubertpendragon** [comment]
Sorry 😓  I thought PRs werent suited for xml

**Comment by mygamingaccount** [comment]
> Sorry 😓 I thought PRs werent suited for xml

https://github.com/Regalis11/Barotrauma/blob/master/CONTRIBUTING.md#building-the-game

(4th paragraph in the #building-the-game section)

> The BarotraumaShared/Content folder, which contains Barotrauma's art, item XMLs, sounds, and other assets, is not included in the GitHub repository. If you have a legal copy of the game, you can copy the Content folder from the game's files to BarotraumaShared/Content.

PR's will not be possible since there's nothing to compare these files against.
This still tells us where they expect the files - so copy the Content files to BarotraumaShared/, edit your `.gitignore`, and commit it to your own branch (remember, no pushing allowed to Github)

Then you can conveniently create the diffs in this format using `git diff`:
```diff
diff --git a/Barotrauma/BarotraumaShared/Content/Items/SearchLight/searchlight.xml b/Barotrauma/BarotraumaShared/Content/Items/SearchLight/searchlight.xml
index b1619e91e..6da527e9a 100755
--- a/Barotrauma/BarotraumaShared/Content/Items/SearchLight/searchlight.xml
+++ b/Barotrauma/BarotraumaShared/Content/Items/SearchLight/searchlight.xml
@@ -29,7 +29,7 @@
         <LightTexture texture="Content/Lights/lightcone.png" origin="0.0, 0.5" size="1.0,1.0"/>
       </LightComponent>
     </Turret>
-
+    <aitarget maxsightrange="3000"/>
     <ConnectionPanel selectkey="Action" canbeselected = "true" msg="ItemMsgRewireScrewdriver" hudpriority="10">
       <GuiFrame relativesize="0.2,0.32" minsize="400,350" maxsize="480,420" anchor="Center" style="ConnectionPanel"/>
       <RequiredItem items="screwdriver" type="Equipped"/>
```

**Comment by Regalis11** [comment]
> PR's will not be possible since there's nothing to compare these files against.

You could just put them somewhere outside the Content folder

**Comment by Rokvach** [comment]
On older saves the scooter light is always on

Tested using the Too many items save, run to the bottom right diving suit room there should be a cargo scooter and a regular scooter in the large cabinet.

[scooterlight.zip](https://github.com/Regalis11/Barotrauma/files/12258007/scooterlight.zip)

**Comment by Rokvach** [comment]
Forgot to specify that you need to be holding the items

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e452a0e4637cebc1d4f75f442e79a8f6fea8da0

**Comment by Rokvach** [comment]
Tested, working correcly. Can be merged and closed.
