### ISSUE TITLE
"Terrorist stakeout" mission fails if the terrorists are captured alive

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12278]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Terrorists were dealt with non-lethally in order to give us a bonus by doing it **By the book**. This caused the mission to fail.

![image](https://github.com/Regalis11/Barotrauma/assets/68995233/c875dbd2-2f9c-435f-8114-d6d69cb451ad)

The By the book bonus was granted, by the way.

### Reproduction steps

- Take the Terrorist Takeout mission
- After they attack you, handcuff them
- Instead of getting a reward the mission fails

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/91fe3f2ca1adcceeedad255f6640f68af63760fc

**Comment by giists** [comment]
No issues found, closing.
