### ISSUE TITLE
It's impossible to die from monster/terrain impacts?

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12272]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Impact damage when getting attacked by monsters seems to be very limited. It's essentially impossible take significant damage from getting rammed by an Endworm/Charybdis/Hammerheads/Molochs.

Not just dying, but health rarely goes under 95%+ from getting rammed by large creatures for several minutes.

Discussion on Discord:
https://discord.com/channels/103209684680323072/668819422919524352/1111073865284722708

Related: #11301

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/0212e8bc-d29f-43e7-a30d-5d73e16129be)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/57c5cfd2-3071-4745-b7e7-37f2bda8fdea)

### Reproduction steps

1. Spawn many large creatures around your submarine
2. Get attacked
3. Barely take any damage
4. This can go on for 10 minutes, health will be stable

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6b45ae754a87e5b918ebf1963dc4abb738deedd1

**Comment by giists** [comment]
No issues found, closing.
