### ISSUE TITLE
[Unstable] Nature vs Nurture failed to count a recovered egg

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#12282]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During testing i recieved the mission to recover a mudraptor egg from the nest mission into the sub as a traitor. I did as asked, however i picked up one egg, which i dropped, then picked up another which i brought into the sub. 
The mission itself was marked as complete once the eggs outside were destroyed, but the traitor mission inside was never counted, even though the egg was recovered.
I assume this issue is caused by having the first egg you pick up being the only one which counts toward the traitor mission, but i wouldnt know for sure.

### Reproduction steps

1.Get the traitor mission related to recovering a mudraptor egg into the sub from the cave (Nature vs Nurture)
2.Pick up 2 eggs, leave one outside, take the second one in
3.The egg you are taking with you is not needed to finish the mudraptor nest mission itself, nor will be counted toward finishing your traitor mission 

### Bug prevalence

Just once

### Version

Other

### -

v1.1.2.0 (Unstable Traitors)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3608c30b4c2cc88e754046a21fbbbe57af232f81

**Comment by NilanthAnimosus** [comment]
Fix/traitor-fixes commit https://github.com/Regalis11/Barotrauma-development/commit/b9d715b20c33e51455843420daad0944adae4de7, no issues found.

Notes: tested both the event (Works fine, regardless of dropping the first egg and using a different one) and the error checking on not finding a matching label in the events.
