### ISSUE TITLE
Shooting endocrine booster at wall causes error

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#12289]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Shooting endocrine booster with syringe gun at wall causes error.

### Reproduction steps

1.Shoot endocrine booster at wall

### Bug prevalence

Happens every now and then

### Version

Other

### -

v1.1.2.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Failed to set the value of the property "Tags" of "Large Vertical Inside Wall" to medical (Type "ImmutableHashSet`1" not supported)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d9525b9920aee794c111ae87c19057c96869e16c
