### ISSUE TITLE
Rapid firing a Rifle can have every second shot not play the cocking sound due to Weapon Skill.

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12283]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Depending on the weapon skill, when trying to fire a Rifle as fast as possible by spamming M1 the second shot will not play the cocking sound as the first shot's cocking sound didn't finish.

Weapon Skill
0 to 13 - Works as intended.
14 to 19 - You are able to fire before the cocking sound finishes, making the second shot's cocking sound not play.
20 to 29 - Works as intended.
30 to 49 - You are able to fire before the cocking sound finishes, making the second shot's cocking sound not play.
50 onwards - Works as intended.

_Note:
From 0 to 19 weapon skill, cocking sound consists out of 3 clangs.
From 20 to 49 weapon skill, cocking sound consists out of 2 clangs.
From 50 weapon skill onwards, cocking sound consists out of 1 clang._

### Reproduction steps

1. Open submarine editor.
2. Load camel.
3. Put a Rifle and spare ammo in a locker.
4. Playtest the submarine.
5. Grab Rifle and ammo.
6. Use "setskill weapons number" command to set your weapon skill to the aforementioned values.
7. Make sure you aren't wearing any weapon skill boosting gear such as the Gunner's helmet or bandolier.
8. Spam M1 while holding M2 to fire the Rifle as fast as possible (With one of the aforementioned weapon skills)

_Unrelated: Also, I did "setskill JoeMama 60" and it gave the character +60 points of JoeMama I presume._

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
I did some fix to this issue with my mod. One possible workaround is to use these instead of 3 separated status effects. You might want to move this into `<Holdable />` so it plays even if player is not aiming with the rifle.
```
      <StatusEffect type="OnSecondaryUse" target="This" comparison="and" disabledeltatime="true">
        <Conditional ReloadTimer="lte 0.5" />
        <Conditional ReloadTimer="gt 0.4" />
        <Sound file="Content/Items/Weapons/WEAPON_rifleReload50-_1.ogg" type="OnUse" range="500" selectionmode="Random" />
        <Sound file="Content/Items/Weapons/WEAPON_rifleReload50-_2.ogg" type="OnUse" range="500" />
      </StatusEffect>
```

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/983f102a2790cc7048e930a4b47374a0495eab9d

**Comment by giists** [comment]
No issues found, closing.
