### ISSUE TITLE
"Your Crew" Gets Implemented Inside Section for "Hireable People"- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1228]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you hire someone your crew goes into section for hiring but you can only fire them.

**Steps To Reproduce**
1. Start new campaign.
2. Hire someone.
3. Notice your crew got teleported to "Hireable People".

**Version**
0.9.0.0 (debug build) further versions may have same thing. I don't know on which operational system it may occur as it may on any.

**Additional information**
I found it on youtube but I don't know if I have permission to share a link.

**Comment by Regalis11** [comment]
Yes, you can share the link. If you mean [this video](https://www.youtube.com/watch?v=nS5GFIhgfVo), it's from an older version and the issue has since been fixed.

**Comment by rico6822** [comment]
> Yes, you can share the link. If you mean [this video](https://www.youtube.com/watch?v=nS5GFIhgfVo), it's from an older version and the issue has since been fixed.

It's exactly this video. Good to know it's already been fixed.
