### ISSUE TITLE
Make Items with Holdable Component not pickable when on outpost

### ISSUE THREAD

**Issue by ricky122122** [Regalis11/Barotrauma#12287]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Conneciton Panels are locked on outposts by default but Holdable is still pickable this is more of a feature request than a bug report. I could be wrong that connection panels are locked on outposts by default but Im fairly certain.

### Reproduction steps

1. Make something like a cabinet holdable/detachable
2. start a campaign in singleplayer or multiplayer and go and try to detach a cabinet

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Since there aren't really any vanilla items where this'd be relevant, I think it's up to the modder who adds these detachable items to make them non-pickable in outposts.
