### ISSUE TITLE
Orca 2 ballast level indicator lights are not visible due to Alpha = 25

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12280]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![level lights](https://github.com/Regalis11/Barotrauma/assets/68995233/4a7f3512-acea-4f62-ac83-abb86e7ee401)

### Reproduction steps

- `quickstart orca2`
- observe "emergency lights" above ballasts that are supposed to show you the level

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2d7ebaa64b84ede645b93981587cfb18304e6090

**Comment by Jasontti** [comment]
Tested.
No issues found.
Not related to ticket, there is some water inside the periscope room.
![image.png](https://images.zenhubusercontent.com/6463874172183936f90966a8/dfbe3380-96ad-4ae0-8960-74f66137c538)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6aa14a44cbb633220f06ef1bbca4041e86a0b34

**Comment by Jasontti** [comment]
Now there is some water in the room with the ballast level indicators. :upside_down_face:

**Comment by Regalis11** [comment]
Hopefully fixed for good now https://github.com/Regalis11/Barotrauma-development/commit/c8eaf44aa0b1a5f6b2a589388c2fe36538d4454d

**Comment by Jasontti** [comment]
No further issues.
Closing.
