### ISSUE TITLE
"Placing" a crate inside an unmounted crate shelf desyncs the player

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12292]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If there's an Assistant placeable crate shelf dropped on the ground (not mounted), and you drag a crate on it, the game will show you the option to store the crate inside. 
It will look like you've placed the crate inside the shelf, but you're actually holding the crate in your hands, and other players see you holding it

Not gamebreaking since you can just swap items and you will drop the crate but worth reporting

My perspective (I'm actually holding said crate)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/846a156a-6280-4cfe-97a9-1620a7606179)

### Reproduction steps

1. Drop a placeable shelf on the ground (don't mount it)
2. Hold a crate
3. Drag the crate onto the shelf
4. Crate looks like it's in the shelf but it's not

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/252f297b44c1886336f7f2ce0a223b776fcffe1f

**Comment by Jasontti** [comment]
Tested.
No issues found in SP or MP.
Closing ticket.
