### ISSUE TITLE
[Unstable] R-29 Bots can't enter the sub from bottom airlock + fabcab is not viewing side-by-side with fab

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#12299]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/59519434/359fca53-a341-4bbc-a19f-2ca4b233b6b8)

### Reproduction steps

1. Move a bot outside the sub near the bottom airlock
2. Let them go back to the sub on their own
-they get stuck on the hatch unable to open it

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed the pathfinding issue in https://github.com/Regalis11/Barotrauma-development/commit/e2d15939017a46d7b47ef62bbaf4f65d5140c50c. The fabricator linking has already been reported and fixed https://github.com/Regalis11/Barotrauma/issues/12212

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing
