### ISSUE TITLE
Piezo crystals cause zero damage to either divers or the submarine

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12295]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Is this intentional? The sparks are menacing but have no effect other than the additional load on power grids.

### Reproduction steps

Go near piezo crystals.
Electrical lightning covers the place but does no damage.
Be confused.
Carry on.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by ubertpendragon** [comment]
Probably because it would passively kill monsters if it did damage

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/634a35aeca19c3a9aec19e2977b951596c7fe038

**Comment by giists** [comment]
No issues found, closing.
