### ISSUE TITLE
[Dev] Bug introduced with the lastest updates regarding damage modifiers.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1230]
While editing the diving suit, I noticed something weird going on when editing their armor values:

```
<damagemodifier armorsector="0.0,360.0" afflictiontypes="damage" damagemultiplier="0.8" damagesound="LimbArmor" deflectprojectiles="true" />
<damagemodifier armorsector="0.0,360.0" afflictiontypes="bleeding" damagemultiplier="0.3" damagesound="LimbArmor" deflectprojectiles="true" />
<damagemodifier armorsector="0.0,360.0" afflictiontypes="burn" damagemultiplier="0.1" damagesound="LimbArmor" deflectprojectiles="true" />
```

In the example above, all 3 modifiers seem to work with the lowest value, so it appears all 3 use the 0.1 modifier. I did some tests and it's definetely happening.

**Comment by rico6822** [comment]
So telling the game to reduce damage by 20% reduces it by 90%. Why haven't it happened before?

**Comment by ChikoEduardo** [comment]
I guess they didn't edited armor values the same way they did in the last patches?

**Comment by itchyOwl** [comment]
Caused by 68366a4. Not sure what the affliction identifiers are for, so let @Regalis11 fix this.
