### ISSUE TITLE
[UNSTABLE] Minor ui bug in the Macrodosing talent description

### ISSUE THREAD

**Issue by Quink-Fix** [Regalis11/Barotrauma#12306]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Screenshot (88)](https://github.com/Regalis11/Barotrauma/assets/88389357/f9e4c72a-5128-4cb4-8bdc-4511c514f88d)

### Reproduction steps

1. Control a medical doctor
2. Mouse over the Macrodosing talent

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eed75ffcf96c7a6576effe7ec6a9f87c4c6794ca (commit in our private repo).
