### ISSUE TITLE
Traitor sabotage triggers deterioration timers 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12307]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sabotaging some machines will trigger their deterioration delay, even if said deterioration delay is never supposed to activate (railgun loader)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/1a90cd48-9560-4b5f-8fa3-b1caf9f42239)

Railgun loaders (normal and legacy) deterioration delay is very short too

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/039cd249-1874-4ce3-88a1-c416e29e5eab)

Compare to coilgun
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/c44d27f1-5cf6-47a2-83c5-8fe4abec991e)

### Reproduction steps

1. Be traitor
2. Sabotage a railgun loader to 0
3. Repair it
4. Deterioration starts a few seconds later

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/caf2c35521ec772162f815a3e6e4b2121d6cf84f

**Comment by AdamH-Daedalic** [comment]
Tested this against fix/traitor-fixes

Sabotaged items do not appear to be deteriorating for the 60s mentioned in the fix and remain at whatever repair state that they are repaired to, with the exception of the railgun loader which will deteriorate after sabotage for up to 120s.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/71794b1017b9a060f9ece506ce46047d719298f2 and https://github.com/Regalis11/Barotrauma-development/commit/8eb2c0f8c2898e840b96c1ae0ca1c96886489b81. Also added a hint about the item being sabotaged in https://github.com/Regalis11/Barotrauma-development/commit/b31670cb788bc4433efcf76ec7976da6a4eaeba9

**Comment by AdamH-Daedalic** [comment]
This still seems to be behaving in an undesired way. The deterioration delay gets triggered by the sabotage after being fully repaired after sabotage, however they all appear to end up being set far higher than the 60s, so they never actually kick in.

Perfect, untouched items when hovered over with debugdraw on show the deterioration delay info in blue with [PAUSED] on them, not actively deteriorating. Once you sabotage and repair something that text turns green and has a random value chosen by the item configuration and starts counting down in the background, for example the railgun is usually between 5-15s, and then after that time is up it starts the rapid breakdown. Most other items when sabotaged throw out values of 100+ seconds so the deterioration wont kick in until the 60s of forced breakdown has long finished

**Comment by Regalis11** [comment]
Hopefully fixed for good now: https://github.com/Regalis11/Barotrauma-development/commit/20c936d3d45a3f85af846b31157330231f2090be

**Comment by AdamH-Daedalic** [comment]
Issue appears to be resolved now. After sabotage, items given a 60s timer where they deteriorate back down to 0hp, even after being fully repaired, adding more impact to the sub/team after a sabotage action. 

Closing
