### ISSUE TITLE
Fractalguardian_emp causing softlocks in the final level

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12300]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During the Jove fights, Fractalguardian_emp kept breaking multiple supercapacitors and junction boxes. It was impossible to gather enough power to even shoot the guns as the EMP drained the supercaps. 

Even by dedicating 3 players to constantly repair the critical JBs/caps, we somehow could not fight back

The guardian kept firing at the same room; in the case of winterhalter the engine room where supercapacitors are. Depending on your sub layout, this may result in a "softlock"

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/263191d6-bab5-4c5f-b80a-fbb5947db61b)

The EMP attack value might just be too high, or the attack too consistent (lack of spread)

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8c5596936fca38d78fbb542a83f9fb016f1ce3be

**Comment by giists** [comment]
No issues found, closing.
