### ISSUE TITLE
Stimulants are less durable when applied to characters whose max vitality is higher than 100

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12303]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Stimulants(like meth, steroids, combat stimulant and pressure stabilizer) are less durable when applied to characters whose max vitality is higher than 100

### Reproduction steps

1. inject stimulants to characters who have different max vitality like captain and security
2. observe buff being less durable on characters who have higher max vitality

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Vykn** [comment]
This isn't really a bug - that's just how afflictions work. All applied affliction strength is multiplied by 100/vitality. I'd also argue that it makes logical sense; larger creatures have higher max vit, and so drugs would be less effective on them. e.g. Imagine giving an endworm a tiny syringe of meth and it becoming 20% faster.

**Comment by Regalis11** [comment]
I agree with Vykn. This could be changed by using `MultiplyByMaxVitality`, but in that case I think we'd need to make sure it only affects humans with slightly increased vitality, not larger creatures. And personally I don't feel that's worth the trouble: the effect doesn't make much difference in practice, and imo it makes sense that a character with more vitality (implying they're more buff or in a better physical condition) needs more stimulants to get the same effect as a weaker character.
