### ISSUE TITLE
Error when pets is killed (Received invalid SetAttackTarget message)

### ISSUE THREAD

**Issue by Ukiestudmfn** [Regalis11/Barotrauma#12302]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When Psilotoad is killed by Tiger thresher error pops up. I'm unsure if this happens when other pets are killed or if other creatures kill pets, I know crawler dose not. 

### Reproduction steps

1. Start sandbox
2. Spawn Psilotoad
3. Spawn Tiger Thresher (If it wont attack Psilotoad spawn human near to cause aggro)
4. Let Tiger Thresher kill Psilotoad 
5. Error "Received invalid SetAttackTarget message. Target entity not found (ID 0)" Pops up.

### Bug prevalence

Happens regularly

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Received invalid SetAttackTarget message. Target entity not found (ID 0)
```

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e541aece019d2b07491945c5e7943503121746d (commit in our private repo)

**Comment by giists** [comment]
Issue fixed, closing.
