### ISSUE TITLE
[UNSTABLE] Winterhalter ventral medicine cabinet isn't connected to the adjacent medical fabricator

### ISSUE THREAD

**Issue by Quink-Fix** [Regalis11/Barotrauma#12305]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Despite being directly adjacent, the medical fabricator and medicine cabinet aren't linked in the Winterhalter.

As an added bonus, the research station and the medium steel cabinet adjacent to it aren't linked either.

### Reproduction steps

1. Load up the Winterhalter
2. Use the medical fabricator or research station

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1dbf569dee2afca9ed6075515abcf8e0b81c3a27 (commit in our private repo)

**Comment by HawkinsThe71st** [comment]
Some more subs that don't have linked med fabs: Kastrull, Orca, Orca 2, Remora, Typhon, Typhon 2. The Humpback one is unlinked as well but the medicine cabinet is a bit further away from the med fab than the others.

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing.
