### ISSUE TITLE
[UNSTABLE] Item tooltips obscure stack sizes in the hotbar

### ISSUE THREAD

**Issue by Quink-Fix** [Regalis11/Barotrauma#12304]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When mousing over an item, the description renders to the right of the cursor, inconveniently obscuring the stack size number which makes it more difficult to transfer a specific number of an item to or from a container.

### Reproduction steps

1. Obtain multiple of stack-able item
2. Mouse over it

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/bba9054ec370b64ca48e048012c8eb0ba9190fc7 (commit in our private repo)
