### ISSUE TITLE
Double Nuclear Railgun Shells and Nuclear Depth Charges in editor entity menu

### ISSUE THREAD

**Issue by Fachoj** [Regalis11/Barotrauma#12310]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Capture](https://github.com/Regalis11/Barotrauma/assets/95565216/e93cd16c-0cae-4edc-96cd-ba958bfd1c5a)

### Reproduction steps

Enter editor and search for nuclear charges.

### Bug prevalence

Happens every now and then

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Fachoj** [comment]
literally unplayable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e82a480b8e5553fdffa8fbf1270dabb896dcd29 (commit in our private repo)

**Comment by giists** [comment]
Fixed, closing.
