### ISSUE TITLE
Files sorting is bonkers in Linux client file manager (spotted at Workshop mod icon menu)

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#12319]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Expectation: big massives of data, like file/folder lists to page through, are reasonably sorted.

Reality:
![20230709194812_1](https://github.com/Regalis11/Barotrauma/assets/81986452/dc035c4e-f151-4a2c-86fd-13527da5de02)
Half of file names starts with L, half with C. But it's not sorted alphabetically.
I'm fairly certain that I've created fresh copies of these files in that folder in sequential order - but neither creation nor modification date is being used for sorting.
Cannot comprehend.

Minor. May or may not help with something bigger.

### Reproduction steps

Make some mod.
Open Workshop Uploader in the game.
Start filling in mod-to-upload details.
Open 'select mod picture' menu, as example.
Navigate to some folder with huge amount of differently named files.
Get lost in assorted non-sorted files.

### Bug prevalence

Happens regularly

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Interesting! I can reproduce this.
Does the Windows API automatically sort directory contents for you? Or can this also be reproduced on Windows?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
