### ISSUE TITLE
(improvement?) avoid redundant server list building

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#12317]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It's probably either improvement or feature request. But who knows...

It coincided that I've opened the console right after we've finished another mission in multiplayer (campaign mode so we were transitioning straight from game map to outpost. No lobby screen nor server browser).
Despite me being nowhere even close to server browser, it seems like game client did fetched extra list of servers for some reason.
Notice that level change message in console is being followed up by some Chinese servers. Which simply shouldn't be fetched by my server browser config.

Assuming that the fix is easy, it might squeeze few extra drips of PERFORMANCE for end users - invaluable players :)
Because if a client run in Europe asks few Chinese servers for intel and awaits for some data from these - it's bound to slow things down.

![20230710032636_1](https://github.com/Regalis11/Barotrauma/assets/81986452/8753e4cb-2f2e-4bd7-acc3-44946781d408)

### Reproduction steps

Launch the game.
Configure some very specific set of options in server browser.
Join some already-running Campaign session.
Wait until level change (mission <-> outpost).
Open console, see mentions of servers which shouldn't be there.

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
>Notice that level change message in console is being followed up by some Chinese servers. Which simply shouldn't be fetched by my server browser config.

There is no way in the Steam API to only fetch information for servers in some specific area, nor by language. We need to query all the servers and filter them by language afterwards.

>Assuming that the fix is easy, it might squeeze few extra drips of PERFORMANCE for end users - invaluable players :)
Because if a client run in Europe asks few Chinese servers for intel and awaits for some data from these - it's bound to slow things down.

It doesn't really, the queries are done asynchronously and the performance cost of processing the queries is negligible.
