### ISSUE TITLE
When copying text displays in the editor, the lightcomponent turns off

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12323]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The light component which is part of the text display gets turned off when it is copied. Emergency light gets turned off too.  Some other light components, like the gun turret light, stay on. 

No other properties seems to have changed.

### Reproduction steps

Load your favorite sub in the editor (the Dugong)

Make a copy of a text display by Ctrl+grabbing it (copy & paste works too)

Inspect the text display: the background light is off

### Bug prevalence

Happens every time I play

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Tested with v1.0 and this does not happen.

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.

**Comment by Jasontti** [comment]
@mygamingaccount Correct. There is some issues still with this branch (multiple issues are sometimes grouped) that prevent merging to current unstable.
