### ISSUE TITLE
Empty filter button in sub editor doesn't work when inventory of certain items is open

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12325]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The empty filter button (?) doesn't empty the filter when you open the inventory of Exosuit, Bandolier and Cargo Scooter 
(There probably are more)

![Garbago](https://github.com/Regalis11/Barotrauma/assets/104994469/e7d7b0c9-ce5d-400c-8bcf-938555b649a5)

### Reproduction steps

1, Start Submarine Editor.
2. Place Exosuit.
3. Open the Exosuit inventory.
4. Put something as filter.
5. Try pressing the x button to empty the filter.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e3452744aad02093c285a663767bb82fcef643e (commit in our private repo)

**Comment by giists** [comment]
No more issues found, closing.
