### ISSUE TITLE
Feature Request: Search Store Items

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1232]
Didn't find this request anywhere else but it would be extremely useful if the store either were presented so that more was visible per page or we could search available items with a searchbar (or both). Quality of life improvement.

**Comment by rico6822** [comment]
Requests like it and bug reports on github can be missing for months or years because a lot of people think the issue is so noticeable somebody already reported it. I had the same thing with oxygen draining corpses. I thought somebody mentioned it already but I was wrong.

#1199

**Comment by Regalis11** [comment]
Added in aa0466a
