### ISSUE TITLE
Damage from structure damage "shrapnel explosions" is inconsistent

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12320]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There have been some reports on Discord about the structure damage "shrapnel explosions" sometimes doing enormous amounts of damage (even enough to instakill a character). Other times, it seems to be completely negligible.

I haven't found a way to reproduce this, but I think I found out what's causing it. The explosion damage is affected by obstacles between the character and the explosion: leaking wall sections multiply the damage by 0.1, non-leaking ones by 0.01. In practice, the damage can be wildly different depending on the exact position of the gap and whether its origin is at the same side of the wall as the character.

### Reproduction steps

Unknown, could possibly happen with certain curved wall pieces that might generate the gaps in a way that their origin isn't necessary at the center of the wall's physics body?

### Bug prevalence

Happens every now and then

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/316d63a1062f5b6e577bb4eb91ffa62aa3ba8589

**Comment by ubertpendragon** [comment]
Noticeable on this submarine:

[Possum.zip](https://github.com/Regalis11/Barotrauma/files/12001264/Possum.zip)


![image](https://github.com/Regalis11/Barotrauma/assets/73229309/075fbce6-d70f-4334-b4bb-2c559ec9e5e3)
