### ISSUE TITLE
Physical Conditioning and Oxygenite Tank Effect don't stack

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12327]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Oxygenite tank increases movement speed by 20% (According to wiki)
Physical Conditioning increases movement speed by 10%

MECHanic and Oxygenite mask speed bonus also don't appear to stack, or the bonus is negligible.

I used a stopwatch and did the reproduction steps, testing was prone to human error but it gives a good approximate.

Without Diving Suit:
 6.30 - No talents or items
 **5.75 - Physical Conditioning
 5.75 - Oxygenite Diving Mask
 5.75 - Physical Conditioning, Oxygenite Diving Mask**
 5.10 - Gun Runner
 4.75 - Physical Conditioning, Gun Runner
 4.75 - Physical Conditioning, Oxygenite Diving Mask, Gun Runner

 
Exosuit Inside:
16.00 - No talents or items.
12.30 - Physical Conditioning
10.50 - Heavy Lifting
10.30 - Physical Conditioning. Oxygenite Diving Mask
10.30 - Oxygenite Diving Mask
10.30 - Gun Runner
 9.70 - MECHanic
 9.53 - MECHanic, Oxygenite Diving Mask
 8.90 - Physical Conditioning, Gun Runner
 8.90 - Physical Conditioning, Gun Runner, Oxygenite Diving Mask
 7.30 - MECHanic, Heavy Lifting
 7.30 - MECHanic, Heavy Lifting, Oxygenite Diving Mask
 (Again the diving mask does nothing.)
 
 Exosuit Diving:
 35.45 - No talents or items.
 28.50 - Physical Conditioning
 24,40 - Gun Runner, Oxygenite Diving Mask
 24.30 - Physical Conditioning, Oxygenite Diving Mask
 24.30 - Oxygenite Diving Mask
 24.20 - Gun Runner
 22.57 - Daring Dolphin, Physical Conditioning, Oxygenite Mask
 22.45 - Daring Dolphin
 22.45 - MECHanic
 22.36 - MECHanic, Oxygenite Diving mask
 22.41 - Daring Dolphin, Gun Runner
 22.40 - Daring Dolphin, Physical Conditioning
 22.36 - Daring Dolphin, Oxygenite Diving Mask
 21.30 - Physical Conditioning, Gun Runner
 21.10 - Physical Conditioning, Gun Runner, Oxygenite Diving Mask
 21.00 - Physical Conditioning, Gun Runner, Daring Dolphin
 21.00 - Physical Conditioning, Gun Runner, Daring Dolphin, Oxygenite Mask
 17.70 - MECHanic, Heavy Lifter
 
 
1.) Physical conditioning and Oxygenite Mask don't appear to stack, or if they do it's negligible.
2.) Without a suit these two are identical.
3.) With a Exosuit the Diving Mask is superior.
4.) Again it's shown that they don't stack.
5.) There may be more conflicting thing, kinda like stacking all those speed bonuses barely does anything on the Exosuit diving.

### Reproduction steps

1. Open Sub Editor.
2. Load Camel.
3. Place a diving mask and a Oxygenite Tank Inside it in a locker.
4. Test play the submarine.
5. Open doors from armoury to the reactor, and order bots not to interact with them.
6. Use "spawncharacter SecurityOfficer inside" command.
7. Switch to the spawned security officer.
8. Give yourself experience using the "giveexperience" command.
9. Unlock physical conditioning.
10. Go to the armoury's wall, face in the direction of the reactor.
11. Hold Shift.
12. Open a stopwatch on phone.
13. Press start on stopwatch in the same time as you press A to move in the direction of the reactor.
14. After hitting the wall immediatly stop the stopwatch.
15. Repeat the same but with the Oxygenite Mask.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! They are not supposed to stack: generally multiple speed buffs do not stack to avoid the character's movement speed from getting too high.
