### ISSUE TITLE
Sprite not found bug

### ISSUE THREAD

**Issue by kleiner-sentry** [Regalis11/Barotrauma#12337]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While modding for barotrauma, My local mod would occasionally spit at me errors saying `Sprite %ModDir%/Characters/Human_Cocoon/Human_Cocoon.png" not found!`, among other sprites, at the beginning of every round. This would happen even if none of the monsters listed are even spawned, and it would always give me this error on a random selection of characters from my local mod. I haven't found this issue at all from other mods. It will always gradually begin with one modded character, then the more I play the list grows for some reason. when the modded character with the "missing sprites" is spawned, it will never give me errors saying that the sprite is missing, like it's supposed to. Infact, the sprites appear in-game and behave like normal. I can certainly say that this isn't my mods problem, as I've double checked, triple checked, and even looked at other modded/official character files, and they're practically the same as mine. I shouldn't be getting any errors. This only happens on characters.

This error only started appearing recently, Probably sometime around your most recent hotfix update.
I'm a little nervous sharing the modded file, as it's my personal mod that i don't want to share.

### Reproduction steps

1. load a savefile
2. as the game loads, you'll get red error messages saying sprite not found.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
%ModDir%/Characters/Human_Cocoon/Human_Cocoon.png" not found!
```

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid it might be impossible for us to diagnose the issue unless we have access to the file and can check whether there's some issue in it. I suspect this has something to do with the way the game "preloads" the textures of the characters that can spawn in the level, but this error doesn't seem to occur with vanilla monsters or most modded monsters, so it most likely has something to do with the way the character has been configured. Sorry for the inconvenience!

**Comment by DrinkFromTheCup** [comment]
@kleiner-sentry , you should probably make sure that all paths to the file which causes errors are 100% correct in mod's xml files.
(which, by extent, includes 100% match with your OS file paths handling. No, not everything is case-independant by default in the wonderful world of file systems)
Plus.
If your mod replace entities (including entities from other mods) and these entity replacers contain references for sprites - These Sprite Files Should Be Included Into Referring Mod Too.
No exceptions.

If you're lazy or just don't want extra junk on disk - consider symlinks to donor mod's files. Especially since it's personal mod.

**Comment by Regalis11** [comment]
No known steps to repro, closing. Could be an issue with the way the mod's been configured, but impossible to say without more info.
