### ISSUE TITLE
[Documentation Request] Randomevents.xml documentation missing?

### ISSUE THREAD

**Issue by VaelophisNyx** [Regalis11/Barotrauma#12336]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Not so much a bug but the github pages guide does not touch on randomevent structure *at all* leaving newer modders somewhat blind (and older modders seem unwilling to help). Even following vanilla XML structure can yield no results with no feedback as to why something is not working

hate needing to drop it here in a bug report form but it's my only real option I think

### Reproduction steps

not a bug.

### Bug prevalence

Just once

### Version

Other

### -

not a bug.

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment]
Monsterevents was the bit I needed in particular, but thank you for the quick work either way!

**Comment by Regalis11** [comment]
I generated documentation for MonsterEvents now too. :)

**Comment by VaelophisNyx** [comment]
Thank you!

**Comment by VaelophisNyx** [comment]
This should be finished for now actually, feel free to close it!
