### ISSUE TITLE
Navigation Terminal Pointer Offset

### ISSUE THREAD

**Issue by jcx1991911** [Regalis11/Barotrauma#12346]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The actual angle of the navigation terminal pointer is not the same as the angle derived by sending the X/Y velocity to the ATAN component.
![20230713132143_1](https://github.com/Regalis11/Barotrauma/assets/116519004/9a68be96-2920-4973-9b11-f11d02cefcb8)
![20230713135228](https://github.com/Regalis11/Barotrauma/assets/116519004/5e7b26fb-2ed4-41b9-83d2-a21aaddafc3f)
the correct angle at navigation terminal is -68.8
but it output as -62.9 if direct wire to ATAN
I dig it from the code and made this workshop item to prove it:https://steamcommunity.com/sharedfiles/filedetails/?id=2972742119

Although we've already discussed this in Discord and I personally don't think it's a bug, just in case I sent this issue for confirmation

### Reproduction steps

https://steamcommunity.com/sharedfiles/filedetails/?id=2972742119
download it and read the description then try it in subeditor.

### Bug prevalence

Happens every now and then

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
The error at multiples of 45° is zero, it becomes more between these angles.

Removing the mapping to the circle of the input vector in the ClientSource/../Steering.cs highlights the error:

https://github.com/Regalis11/Barotrauma/assets/68995233/5d7ba67a-1c9f-46a7-aa90-561b6d34501b

**Comment by mygamingaccount** [comment]
Different angle appears when the input is dragged to maximum length
![atan](https://github.com/Regalis11/Barotrauma/assets/68995233/c00f133e-9788-4a3b-9667-ad8c1628993f)
When it is less than full length, the error isn't as much:
![atan2](https://github.com/Regalis11/Barotrauma/assets/68995233/47fff8d9-322f-4457-9a09-1a04d3a723c9)

**Comment by Regalis11** [comment]
I don't think this is actually a bug.

The "velocity_x_out" and "velocity_y_out" outputs don't output the direction you're steering towards, but essentially "what the outputs should be to get the submarine to move in this direction, taking the neutral ballast level into account".

**Comment by mygamingaccount** [comment]
> The "velocity_x_out" and "velocity_y_out" outputs don't output the direction you're steering towards, but essentially "what the outputs should be to get the submarine to move in this direction, taking the neutral ballast level into account".

That doesn't seem to be the case anyway.

What's unexpected is that the arrow points in a different direction from both the input from the mouse, and the output that the terminal generates (which is the same as the mouse input)

https://github.com/Regalis11/Barotrauma/assets/68995233/30ce018c-80e6-4d19-9362-447616988ad1

When the mapping from rectangle to a circle is removed then the angle is correct, so the terminal has better support for turrets, and it is closer to how driving works: at 45° angle both X and Y velocities are at maximum, and the speed is that much greater:

https://github.com/Regalis11/Barotrauma/assets/68995233/d97b34b3-5d78-48de-a25f-e3bbda362c86

If the arrow must stay inside a circle, then by using a radial mapping it is possible to keep the correct angles where the arctangent of the signal vector points in the same direction as the terminal:

https://github.com/Regalis11/Barotrauma/assets/68995233/bc9fc3aa-5e5a-4d8a-abc6-3c9d6e87bc9d

**Comment by mygamingaccount** [comment]
67.5°, halfway between 45° and 90°. Angle is correct:

![image](https://github.com/Regalis11/Barotrauma/assets/68995233/0a80fdf4-7c93-464d-897e-4c2aabf9dcdc)
