### ISSUE TITLE
Riot shields can be shot inside containers

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12340]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Riot shields, moloch shell fragments and other shield like items can get hit inside containers by projectiles and melee alike

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/683ca565-2bfb-4c86-9a45-32b1b11d2af8)

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c32cf88c29a1522e2fd541ecee1e4184fe1c891

**Comment by Jasontti** [comment]
Tested.
No issues Found.
Closing ticket.
