### ISSUE TITLE
Subs do not travel in the direction set by the navigation terminal

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12347]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Related to #12346

https://github.com/Regalis11/Barotrauma/issues/12346#issuecomment-1633728807

> The "velocity_x_out" and "velocity_y_out" outputs don't output the direction you're steering towards, but essentially "what the outputs should be to get the submarine to move in this direction, taking the neutral ballast level into account".

Since the navigation terminal is inaccurate for use with turrets even when NBL is set to 0.5, it should be accurate for driving.

There is a large error between the ordered direction and the actual angle of the velocity

Tested once all speeds settled
Experiment 1:
Ordered: 50 ahead, 50 up

Arrow points to -47°
Sub actual heading: -33.42°
![image](https://github.com/Regalis11/Barotrauma/assets/68995233/12bff6b2-afea-482e-92eb-b435973bde18)
(ignore the -45.3° display which is the signal vector angle)

Experiment 2:
Arrow points at -72°
Sub actual heading: -44.2°
![image](https://github.com/Regalis11/Barotrauma/assets/68995233/291918c9-dee6-4f1b-8bed-d547838ecc77)

### Reproduction steps

Expected: sub drives in the ordered direction

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
> There is a large error between the ordered direction and the actual angle of the velocity

That's because the velocity is also affected by things like drag, engine force and ballast size.
