### ISSUE TITLE
Make Multiplayer Campaign Save Player's Inventory- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1234]
The inventory of the player should be saved for that many players don't know it resets. Hosts of servers can disable this feature. Once a person gets banned it's inventory will spawn at cargo spawn point if not salvaged from the corpse at the start of next level (exception is when corpse was at the time of return outside the hull).

**Comment by Regalis11** [comment]
Already implemented in the dev version. :)
