### ISSUE TITLE
beacon station spawned above the starting point

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#12341]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A beacon station spawned above the starting point, I didn't save the campaign save it happened in but it was europan ridge, natural formation to outpost mission, ~25% difficulty, ~1100m level length.

### Reproduction steps

I guess the only way to force it would be to start a new campaign and check every beacon sidequest individually with togglecampaignteleport

### Bug prevalence

Just once

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid there isn't enough information here to reproduce the issue.
