### ISSUE TITLE
[Sub Editor] Frequent Inability To Open Containers?

### ISSUE THREAD

**Issue by VaelophisNyx** [Regalis11/Barotrauma#12353]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Important notes: using LUA for Barotrauma, and C# for Barotrauma, and Performance Fix
However PF doesn't touch the sub editor itself, and LFB/CFB don't do anything to it either

The issue at hand, is that while editing I randomly lose the ability to open a container when right clicking. I can drag items in still, but I cannot open *anything*. Saving & reloading the editor (not the whole game) fixes this temporarily. No errors are logged when this occurs. As of posting, no testing has been done in a purely vanilla environment, as performance fix (which depends on LFB) is a requirement for my ability to play the game

### Reproduction steps

Entirely unsure, sorry. I'm as lost as you all probably will be here.

### Bug prevalence

Happens regularly

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment]
Rough duration is at least 1-4 hours of editing without closing the editor at all, or testing the sub. Another friend of mine has bumped into it with mods. I didn't know about the keybind to open items at the time so that was untested, but if I run into that I'll be sure to document it here.

**Comment by VaelophisNyx** [comment]
Update: While this bug is active, the E keybind to open a selected object still functions

**Comment by NilanthAnimosus** [comment]
Does the right click no longer appear, or do you get different options entirely when using right clicks? Does the option gray out? How does this bug manifest? Or is it available - but functionally does nothing when clicked?

**Comment by VaelophisNyx** [comment]
right clicks continue to function, but the Open option is greyed out and unable to be clicked. Everything else in the right click, and shift-right click menus still works

**Comment by VaelophisNyx** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/1534478/b8b3279a-0e63-4cfa-ba4b-4f93aa89deab)
here, caught a screenshot of the bugged menu

**Comment by Regalis11** [comment]
It seems that's a makeshift shelf(?) - have you noticed this affecting other items than those? I'm wondering if it could be the shelf isn't attached to a wall.

**Comment by VaelophisNyx** [comment]
That's a crate rack rotated 90°
It affects literally any item with a storage when it kicks in. Even diving suits/weapons/tools.

**Comment by Regalis11** [comment]
I think I found a way to reproduce this. Looking at the code, it seems the "Open" option gets grayed out if you've selected more than 1 entity, and we just fixed an issue some time ago that caused some entities to be considered "selected" even though they don't appear to be selected:

https://github.com/Regalis11/Barotrauma/issues/11538

This can be reproduced the same way as that issue:

> It's hard to reproduce reliably, but it's possible to get it to happen by doing the following:
> 
> 1. Put some resizeable structure (like a background wall) in a position where it's corner is behind with some item
> 2. Move your cursor to that corner, which should highlight the item
> 3. Resize the structure
> 4. The item should now appear to become unhighlighted, but it's actually still in a list of highlighted entities, and will get removed if you delete selected items using the context menu.

When you get to the 4th step, it'll be impossible to open the containers through the right-click context menu.

**Comment by VaelophisNyx** [comment]
Aha! That'd make sense, I do frequently select groups of objects to move around

**Comment by Rokvach** [comment]
The ticket https://github.com/Regalis11/Barotrauma/issues/11538 has been tested and confirmed working correctly, so I don't see the need to keep this one open. Closing.
