### ISSUE TITLE
Oddities From Equipping Deepdiver Ducks

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#12355]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Oddity 1: Deepdiver Ducks can be held with both hands.

![Barotrauma_xcCqKJGOEN](https://github.com/Regalis11/Barotrauma/assets/60911734/0c2a5784-90b5-41df-9222-10fbc59e16d3) ![Barotrauma_HIKDJPKLHo](https://github.com/Regalis11/Barotrauma/assets/60911734/13bd9ea6-df5b-45a9-a2e5-14493624f798)

When aiming to throw, both hands go into the air with one hand empty. In a stack of Deepdiver Ducks, only one Duck is thrown.

Oddity 2: Deepdiver Ducks cannot simply be unequipped.

A singular Deepdiver Duck cannot be unequipped as it cycles between using one hand and two hands. It can only be unequipped by throwing it, dropping it, equipping two other items, or changing the inventory slot of the Deepdiver Duck.

https://github.com/Regalis11/Barotrauma/assets/60911734/76807c2a-d5ac-4310-896e-f6fd9fbf038c

A stack of Deepdiver Ducks cycles between holding with one hand, holding with two hands, and the item being unequipped. However. while it looks like the item is unequipped, one Deepdiver duck is still held. The way to unequip the stack is the same as before.

https://github.com/Regalis11/Barotrauma/assets/60911734/50585010-6c14-4614-a1c0-49b8d26b4524

Also, if a Deepdiver Duck is equipped to the right of another Deepdiver Duck in the inventory, trying to unequip if after holding it in two hands will lead to the Ducks being stacked, while still holding one of the Ducks. Doing this procedure to the left of another Deepdiver Duck just does the same thing as mentioned before with the singular Deepdiver Duck.

![Barotrauma_z06QelKtz3](https://github.com/Regalis11/Barotrauma/assets/60911734/bb51b7a4-15fc-4e0f-8bea-4a2cfc634b6c) ![Barotrauma_uHXIw7dUHL](https://github.com/Regalis11/Barotrauma/assets/60911734/5eb68301-ea3d-4c5e-9c29-0bac78d83e0e) ![Barotrauma_oj7ulhPMMZ](https://github.com/Regalis11/Barotrauma/assets/60911734/8c2b862b-cbb0-45b7-b5a3-b223ee0acbd1)

### Reproduction steps

1. Start a round or use Submarine Editor
2. Spawn Deepdiver Ducks using console commands
3. Attempt to equip and unequip the Deepdiver Ducks, singular and in a stack.
4. The Ducks should be held in two hands and unable to be unequipped unless thrown, dropped, moved to a different slot in the inventory, or other items are equipped.

### Bug prevalence

Happens every time I play

### Version

Other

### -

Unstable (V1.1.4.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/48d99afa57a3b228fda1c1f77e417b3f55d428f9

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing.
