### ISSUE TITLE
[Unstable] Beacon bandit event doesn't work - beacon is empty

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#12361]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/59519434/4d70435a-3f95-4028-ad28-4aefda69f37a)
It was a bit strange that the beacon is empty. I think some bandits are supposed to spawn in there. I'm including a save where this happened. I was hoping to mod in some NPCs for the beacons so hopefully this issue isn't too big of a deal/gets resolved :)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/12062919/Save.zip)

### Reproduction steps

Load save, get to beacon, observe no bandits in it.

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This is not a bug - the event only spawns bandits if there are spawnpoints with the tag "beacon_bandit", which there aren't in this one.
