### ISSUE TITLE
Motion detector Minimum Velocity is not 0 by default

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12363]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The motion detector has a Minimum Velocity parameter and I don't believe that this has a legitimate use case. It only leads to glitches: frequent 0-1-0-1-0-1 noise when standing near an unedited detector.

The parameter is not in-game editable, so in a campaign it is not possible to fabricate a preferred detector, one which has a Minimum Velocity of 0. Due to this, high quality motion detectors can only be obtained by salvaging them off downed enemy ships.

### Reproduction steps

Camel campaign

Fabricate a motion detector.
Set up a simple motion activated door, like on the Humpback.
The detector glitches every time you stand near.

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Related to https://github.com/Regalis11/Barotrauma/issues/11146

In my opinion, it should not be 0 by default. In that case, anything that's ever-so-slightly moving, including a character that seems to be standing perfectly still, would trigger the detector, because the limbs are practically always never perfectly at rest. That would most likely seem like a bug: the detector would trigger even though there's no perceptible movement.

However, I think we might need to lower the default further to prevent the flickering, and maybe also make the setting editable.

**Comment by mygamingaccount** [comment]
Characters are never still. Standing near the door will cause it to flicker. If you try t to detect when a character is _almost_ motionless, it will only make it worse.

In [SmartDoor](https://steamcommunity.com/sharedfiles/filedetails/?id=2307950318) I use two motion detectors to achieve [hysteresis](https://en.wikipedia.org/wiki/Hysteresis#Electronic_circuits). The door opens when the player is up close, but closes at a slightly greater distance. As a result it has no flicker.

MotionSensor.cs could implement this in a much more simpler fashion than it does the velocity-based debouncing. Just make the X and Y ranges expand by 10% for a 0.1 setting of hysteresis!

**Comment by mygamingaccount** [comment]
Let's separate this discussion to two parts, one bug report and one suggestion:

1) please give us a way to make motion detectors with a minimum velocity = 0 setting!
2) if minimum velocity was introduced to make flickering better, then unfortunately it made things worse. In the #baro-sub-building forum this comes up often: _why do my doors flicker_ and the answer is always: you forgot to set minimum velocity to 0! I propose hysteresis because it results in a very pleasing action.

**Comment by Regalis11** [comment]
> if minimum velocity was introduced to make flickering better, then unfortunately it made things worse

It wasn't, the point was to make it ignore things that aren't moving. The velocity of a physics body is practically never exactly zero, so if we used a minimum velocity of 0, it wouldn't be a motion detector but a thing that detects when there are characters within range.

**Comment by mygamingaccount** [comment]
> It wasn't, the point was to make it ignore things that aren't moving. The velocity of a physics body is practically never exactly zero, so if we used a minimum velocity of 0, it wouldn't be a motion detector but a thing that detects when there are characters within range.

That is merely an academic problem. Just because it is called _motion_ detector it is not necessary that it detects motion. In all of its use cases it performs better when it doesn't, and instead relies on proximity alone.

> This is an interesting suggestion, although I have a feeling it could get quite complex and lead to unintuitive behavior (why is this detector still triggering even though the sub / the monster is no longer moving?). And how would the distance be calculated if the thing moving is the detector itself?

Monsters never stop moving. Even when dead they twitch, so I don't know when this theoretical scenario would be even possible. So when that happens, The motion detector will keep triggering intermittently while a monster is in its vicinity. Why is that preferable to having it on or off depending on presence?

Every single vanilla sub's motion detector is set to min. velocity = 0 and there are no cases of unintuitiveness. Only when you fabricate one and min.velocity is not 0 is where it becomes frustrating. I have yet to see a single use case where min.velocity > 0 is preferable.
I've seen engineers rip motion detectors from coalition / renegade submarine doors on more than one occasion.

**Comment by mygamingaccount** [comment]
List of motion detector use cases:
- long range detection of aliens that are alive that lights up a periscope: minimum veloctity makes no difference
- intruder alert: same as above, why would limiting velocity make a difference?
- door automatic opening: 0 is the only acceptable value, nonzero causes glitching
- drone autopilot follower: a velocity vector output would be amazing, but if using multiple detectors, all must have min.velocity set to 0 otherwise the drone will lose the target

*I'll try to expand this list as I look for more use cases of motion detectors in search for why anyone would ever want a minimum velocity comparison*

**Comment by mygamingaccount** [comment]
@Regalis11 if you don't believe me, search the forums for the term: "minimum velocity". You will only find frustrated players who are upset that the motion detectors that they fabricate don't work as well as the ones that are already on the sub.

**Comment by Regalis11** [comment]
I think you're overlooking the fact that without the minimum velocity, the detectors will react to dead bodies, which makes them hard to use for detecting monsters. In vanilla subs the detectors are only used to open doors when a human is near, in which case the velocity doesn't matter.

**Comment by mygamingaccount** [comment]
I just turn on the "ignore dead" switch when I want a motion detector to only detect live creatures.

**Comment by Regalis11** [comment]
...I didn't even remember that was a thing. I think that makes most of my arguments moot, addressed this in https://github.com/Regalis11/Barotrauma-development/commit/2ea4ade8b4d6bfb1ff30a2e6a7a081f9f6e2b3e6
