### ISSUE TITLE
40mm Acid grenade explosion desync

### ISSUE THREAD

**Issue by AbyssalCrow** [Regalis11/Barotrauma#12365]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Doing some testing with the acid grenades in water because a friend claimed the AOE smoke didn't work in water, I found that sometimes the 40mm acid grenades both indoors and outdoors have a random tendency to show the explosion on the player that shot it and it runs damage as if they were hit only for it to all be healed as the game proper checks. This fake explosion still applies stun and the ear ring effect as if you were hit and the seemingly random nature makes it very iffy to use the 40mm acid grenade reliably. I shot the grenades in multiple directions to confirm it wasn't submarine jank and caused it to happen indoors and outdoors, it did the issue even when it was exploding in empty water and in-ship. 

I did this in a multiplayer server, however I was the only one in it.

Mid explosion, you can see the proper acid area to the bottom right.
![Barotrauma_wgorvWpAUb](https://github.com/Regalis11/Barotrauma/assets/50751414/26fda19d-9b2e-4fe8-b61a-ef84345ea0db)

My health a moment afterwards, game properly resets it to the intended uninjured values.
![Barotrauma_P7aL6Agh6R](https://github.com/Regalis11/Barotrauma/assets/50751414/8c9e31bb-bf26-428e-b47d-dcfb377ac2d5)

### Reproduction steps

1. Started multiplayer up
2. Got the 40mm GL and acid rounds
3. Started firing it. Issue happened at seemingly random as even firing at the same spot caused it.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in current stable and traitor-update branch.
Issue is as described and only in acid grenades.
Happens reliably in multiplayer. Not present in singleplayer.

**Comment by giists** [comment]
Fixed, closing.

**Comment by Regalis11** [comment]
The fix seems to have caused another issue: when you launch a non-hitscan projectile (such as harpoon), other clients will launch one harpoon and drop another one.

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
