### ISSUE TITLE
Beacons can be activated without actually fixing them

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12367]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Beacon stations are made invulnerable after being turned on.

This is because players would fail beacon repair missions after activating them, The beacons would take damage and break.
https://github.com/Regalis11/Barotrauma/issues/8339

**Now, there is the opposite problem: you can activate a beacon without fixing it. 
The only "repair" a beacon needs is a (>=1%) fuel rod and power to the sonar.** 

This is as simple as drawing a single wire from reactor to sonar
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/01c7705d-7bab-4ba5-af57-062579da189c)

Every single deterioration delay is paused
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/9f366166-95ec-4375-888a-fa2b98e0b6ab)

Deterioration speed is 0
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/9925e33f-da78-492a-948c-0389455e7f0c)

Devices do not seem to take damage from water either.

# Suggested changes: 

- Water should damage devices like it normally does

- Activate deterioration for beacons but keep a minimum deterioration condition on all items so they dont naturally _break_ and fail the mission, but still lose enough condition to be easily broken by water
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/d0f07902-8ada-44df-b6d1-b1955ca98637)

- Instead of making the beacon itself immune to damage, turn off its AI target
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/8898c989-f2e7-4fa1-bf91-f7a311154e06)

**Beacons will have to _actually_ be repaired, the water drained, the junction boxes fixed.**

### Version

v1.0.21.0

**Comment by UnhappyWithMyUsername** [comment]
Another approach would be adding the "invulnerable" attribute to structures which would then be set to "true" once the player turns on the beacon.

A bonus with this attribute added would be that outpost builders would gain more control over what can and can not be destroyed on an outpost without having to set ridiculous high HP for the structures which then could still be damaged with overpowered modded item.

I always wondered why items can be made invulnerable but structures can not tbh...

**Comment by Regalis11** [comment]
> I always wondered why items can be made invulnerable but structures can not tbh...

They can, the property is just called "Indestructible".

**Comment by UnhappyWithMyUsername** [comment]
> They can, the property is just called "Indestructible".

Ok I assume it's just not accessible through the editor then and purely configured in the xml files for structures?
![image](https://github.com/Regalis11/Barotrauma/assets/74098498/cb2507d0-e474-426a-a912-9275f1de02ee)

**Comment by ubertpendragon** [comment]
> I'm not sure what'd be a good way to address this. If we went with your suggestion, it would still allow the players to activate the beacon without emptying it of water, and again leading to the mission failing for "no apparent reason" later when the junction boxes break.
> 
> And if you just wire the reactor directly to the nav terminal, it doesn't matter if the junction boxes are broken or not.

Draining the beacon so water doesn't damage electrical is implied.
You could communicate to players if a repaired beacon breaks down, but if you _properly_ repair the beacon before leaving it, it should remain functional

The fix to the single wire thing is that by doing so, the rest of the beacon (pumps) will not be powered, and the sonar monitor will take damage from water and break


Sorry if this seems like of one those "meta-gaming" issues but players learn _fast_

**Comment by dakkhuza** [comment]
Isn't the easiest solution to disable random deterioration and then display a message when the beacon gets disabled after it's been turned on?

**Comment by Regalis11** [comment]
> Isn't the easiest solution to disable random deterioration and then display a message when the beacon gets disabled after it's been turned on?

Possibly, but I think it'd be frustrating to have to return to the beacon to repair it again (potentially multiple times) if it happens to break down again for reasons that are outside your control.
