### ISSUE TITLE
Lamps sprite light despite the strength of alpha

### ISSUE THREAD

**Issue by 1170991249** [Regalis11/Barotrauma#12366]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The light sprite despite the strength of alpha, it happend few months ago but seems to be fixed, but it still happens for me, tried reinstalling game and clear the game folder, does not work, possiblly language problem if not happen in English version, issue confirmed happen at Chinese language

### Reproduction steps

1.Put a lamp just like the workbench light.
2.Try to adjust the alpha of the light but didn't seems to change the alpha of light sprite.

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by 1170991249** [comment]
![QQ图片20230717060017](https://github.com/Regalis11/Barotrauma/assets/25667549/4eaac0de-c137-4e93-bc8c-6077d2caaed8)
![20230717055812_1](https://github.com/Regalis11/Barotrauma/assets/25667549/921d83ff-5530-4c83-b252-24ec940491c5)

**Comment by Regalis11** [comment]
It seems these specific sprites have been configured to render at full opacity regardless of the alpha value of the light.
