### ISSUE TITLE
Incorrect airlock module sometimes generated in LocationConnections

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12379]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the levels between outpost, the airlock module chosen for the end/beginning of the level sometimes doesn't match the type of the location. E.g. a colony airlock module can sometimes be chosen, even though the location is a normal outpost.

### Reproduction steps

1. Load the attached save:

[Save 29.zip](https://github.com/Regalis11/Barotrauma/files/12096038/Save.29.zip)

2. Notice the airlock module at the beginning of the level is a colony one, despite the outpost being a normal one.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
