### ISSUE TITLE
Cultist robes don't work if you're wearing a diving suit

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12377]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Cultist robes won't prevent husks from attacking you when wearing a diving suit. While this makes some sense (the "pheromones" the robes are said to be imbued with probably wouldn't get through the suit), it severely limits the usefulness of the robes and makes the new "faulty robes" traitor event extremely difficult to complete. 

Seems to happen because the "provocative" tag on the suit makes the husks target the character, despite the character itself being ignored.

### Reproduction steps

1. Wear cultist robes and a diving suit
2. Spawn a husk
3. The husk will attack you

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/52f2851cb2da991144a8cf4fe5d0008efa5837bd

**Comment by giists** [comment]
No issues, closing.
