### ISSUE TITLE
Often, tiny amounts of water stops calculating or moving to different hulls

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12375]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Water draining from a submarine hull with no Pump or Duct Block in it can often be left with a tiny amount remaining, just barely enough to continuously trigger a Water Detector lined up with the floor which can be annoying for players working on these rooms.

This is particularly noticeable with Water Detectors placed in the Fabricator Room of the Remora, as well as the Stowage Room of the R-29 (to the right of the Oxygen Generator), though other submarines are likely affected.

https://github.com/Regalis11/Barotrauma/assets/5988156/cb3ee83b-d637-4afb-ad82-c88e8c20e0a6

Note how the hull water level refuses to move any further at 1.49, despite the nearby open hull leading to a lower value of 0.65. Water Detectors only need a hull water level above 1 to send a signal.

### Reproduction steps

1. Start a new game or open the Sub Editor
2. Enter the Remora Submarine
3. Enable DebugDraw
4. Create a small hull breach in the Fabricator Room floor with a Plasma Cutter
5. Seal the breach
6. Drain the water to either the left or right rooms with pumps
7. Observe the hull water level stop transferring while still above 1

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested with R-29, Remora and Dugong.
Water is still left after and water detector reads 0%.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/82688588-c875-4135-953b-b43689bf9278)

**Comment by Regalis11** [comment]
That's intentional: the water detectors ignore the water if there's less than 1% water in the hull or if the surface of the water is less than one pixel deep.
