### ISSUE TITLE
Loss of Oxygen lowered stats and took away my money

### ISSUE THREAD

**Issue by Jakeyboi0880** [Regalis11/Barotrauma#12372]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was playing Baro with some friends and died with the power turned off on the ship unaware that turning the power off reduced oxygen. While my friends were busy fighting I died and respawned with no money and lowered skill points, and I have never run into this issue before. If this is part of the game then it has never happened until now, but regardless I am just super mad I lost my money right before a colony :(.

### Reproduction steps

Loss of oxygen death took my money away and reduced my skill points.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This is a normal part of Barotrauma: if you die you lose skills and money. And turning off power shuts down the oxygen generator, eventually leading to suffocation if you don't find a diving mask, suit, or some other way of getting yourself oxygen.
