### ISSUE TITLE
Allow Players to Set Their Job Preferences In In-Game Screen- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1237]
It can be done in the info menu right next to "Mission" label. The purpose of it is to allow player while spectating or even during game to change role without quitting so it would be faster. Job changes once respawning of players starts.

**Comment by NilanthAnimosus** [comment]
Could we perhaps just add the respawn preferences to the info menu as a sort of player options tab? while also ensuring this is accessible to spectators (I'm sure it is already though) - that should be quick to migrate the job preferences I think.

in the back of my head I felt we could already change our roles as spectators (Least in latest dev) but not during a round, and the new logic on bringing up the info screen via key better suits having it as a tab in that menu.

**Comment by Regalis11** [comment]
Implemented in 0589ecd
