### ISSUE TITLE
Camel bottom Coilgun can see into engine room

### ISSUE THREAD

**Issue by JoshuaLC07** [Regalis11/Barotrauma#12378]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The bottom Coilgun on the camel can see into engine room.

### Reproduction steps

Go to sub editor / campaign then go to the periscope that controls bottom Coilgun, you should see into the engine room from there.

![image](https://github.com/Regalis11/Barotrauma/assets/139966207/6b90e1ed-0f4f-4482-926f-69d2cd3bcc36)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
