### ISSUE TITLE
sub editor can't save subs to lowercase relative path moddir 

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#12376]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

sub editor can't save to files that have their filepath set to %moddir% (lowercase), despite game reading the path fine otherwise/ when loading subs.

### Reproduction steps

1. make a sub
2. add the sub to a mod with structure /%moddir%/subname.sub
3. open sub in editor
4. save the sub
5. error
![image](https://github.com/Regalis11/Barotrauma/assets/5103517/be71bb29-3dee-496e-9e75-ebb1dbb63cd2)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
workaround:
1. save to a new content package
2. close barotrauma
3. change filelist.xml of original package to use camelcase
4. replace original sub with new one.
5. remove new content package
```

**Comment by Tsunder** [comment]
bug prevalence is 100% reliable

workshop example: https://steamcommunity.com/sharedfiles/filedetails/?id=2665347062

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1216f5058aaa6a45ba9676889a7f07c9c94cedb7

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
