### ISSUE TITLE
oxygen tanks and Welding Fuel Tank don't stack 

### ISSUE THREAD

**Issue by Venus-Flytrap** [Regalis11/Barotrauma#12382]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the beta update branch 1.1.4.0 gave the ability to stack items in a quantity of 32, but tanks can not stack in the player's inventory, I think it was not intended that way. 

### Reproduction steps

turn on beta branch 1.1.4.0 and try to get tanks

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Other

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/596442ed-a5ff-421c-90d4-9932b19f2661)
