### ISSUE TITLE
[Unstable] floating minerals inside submarine

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#12387]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Today's latest Unstable, Linux variant.
Save included.

Apparently, these few pieces of Quartz are as dense as oxygen so these are levitating...
![20230721153149_1](https://github.com/Regalis11/Barotrauma/assets/81986452/9d877401-b6b3-46d4-95df-ec6ee96bbbdd)

[the Save.zip](https://github.com/Regalis11/Barotrauma/files/12123657/the.Save.zip)

### Reproduction steps

General steps:
Mine some Quartz from novice grade mining mission.
Dump it into some cabinet.
Prior to docking, dump that Quartz from the cabinet right onto the floor.
Dock.
Check where your Quartz is.

Synthetic steps:
Load the save.
Enter the sub.
Look for anomalies near diving suit lockers.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.4.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/024b39b03041c3a880f5a51b88f1788a664fe2b9

**Comment by itchyOwl** [comment]
This has been merged already. And I guess it was tested by the QA, but the ticket was not linked to the[ PR](https://github.com/Regalis11/Barotrauma-development/pull/4383). Moved to QA, please close when you have confirmed that it's fixed.
