### ISSUE TITLE
New Monster: Siren- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1238]
Health: 5000
Armor: None
Speed: 3.5 (can only swim)
Aggression: Hostile to all monsters but watcher, fractual guardians and endworm. If she hypnoses some monsters they will attack watcher for her but endworm and guardians are ignored.
Enters Submarine: No
Sight: 0.5
Hearing: 2
Bleeds: Yes
Eats Corpses: Yes

Siren is a larger than moloch, medusa-like, durable monster capable of hypnosing monsters around her in order to make them submit to her and become eaten in the process. She is best known for her ability to cause psychosis in humans which can lead to their death by brain damage if it doesn't get threated. 

The signal emitted by Siren has a range of 100 meters, it's constant and becomes stronger the closer the crew is to her. In result of closer range humans are going into state of psychosis faster and monsters are becoming more addicted to her. Wearing equipped headsets can apply negative effect of her signal faster.

**With Active Headset:**
Psychosis after 30 seconds, assuming distance from siren is 20 meters.
Death after 5 minutes assuming distance from siren is 20 meters.

**With disabled Headset:**
Psychosis after 120 seconds, assuming distance from siren is 20 meters.
Death after 20 minutes assuming distance from siren is 20 meters.

During combat all monsters controlled by siren will attack submarine and siren herself will ignore monsters in order to deal with player's crew she considers as a large threat to her territory. Siren deals moderate damage to the hull but nearby monsters controlled by her can deal additional damage. She kills in just one bite any human wearing diving suit.

Siren has low priority of eating corpses so she will always be focused on combat. Once she decides to eat a corpse however she will regenerate health.

Siren has higher priority of killing crew members outside submarine rather than target hulls.

Watchers are immune to siren's hypnosis due to their lack of hearing stuff. They will not become attacked by siren herself but nearby monsters controlled by her. Watchers are neutral to sirens and are not smart enough to notice monster who attacked them were controlled by her.

Fractual guardian are ignored both by her and her controlled monsters since they are uneatable to her.

Sirens have powerful relationships with endworms who are being loyal to them. Siren will often spawn near endworm who she considers her personal bodyguard. Siren never kills alive endworm but will eat his corpse. It takes a lot of time to do so.

During "Beast From The Abyss" mission a siren will always be presented near mission's endworm to make combat more challenging. The coalition tasks player to kill only those endworms controlled by sirens hoping for bonus removal of both of them at once.

Siren can also spawn alone for herself for same chance as natural carrier. Carriers are also immune to her hypnosis. Siren will personally alongside her servants (if there are any) attack carrier.

The best strategy to deal with a siren is to either nuke her of shot a lot of bullets from coilgun. She has no armor.

Siren no longer emits any signals upon death. Examining her inventory results in dropping a substance which can be used to craft a healing item also used for crafting calyxanide.

That's it. If the design of my monster is being too complex to implement her into the game she can always become simplified. I hope adding her into the game will finally make endworm more serious threat during "Beast From The Abyss" mission. Unfortunately my artistic skills are so terrible I cannot create a concept art of this monster. I would like to apologise for it.

**Comment by AbominationBanisher** [comment]
I dislike this idea, I do not find monsters with minions to be fun. This is my personal opinion, ask if you want me to elaborate.

**Comment by rico6822** [comment]
> I dislike this idea, I do not find monsters with minions to be fun. This is my personal opinion, ask if you want me to elaborate. And I do not like psychosis inducing monsters either, I feel that stuff should be left up to medicine and the such.

Don't you always wanted a monster with unique unrepeatable abilities to exist in this game? Humans in Barotrauma are having their brains strong enough to resist hypnosis for that they are being complex. In result of constantly failed siren's attempts to take over you you're brain will die at some point.

**Comment by AbominationBanisher** [comment]
I think although the siren isn't that good overall in that hypnosis region, the only compromise I see is some sort of parasite than once inside of your body gives you psychosis, some kind of underwater leech.

**Comment by AbominationBanisher** [comment]
Or maybe the siren could be a bit smaller and simply inside the ruins where she controls the guardians and such, that's another compromise.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
