### ISSUE TITLE
error with a return objective: no suitable return target found

### ISSUE THREAD

**Issue by Venus-Flytrap** [Regalis11/Barotrauma#12391]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

 While clearing an outpost from Satanists and Huskies, the console opened with the error "error with a return objective: no suitable return target found" and after closing it plays again

### Reproduction steps

I don't know.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Other

### -

unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
There's probably some non-critical issue there, but it should be safe to not throw that error in the release builds. Addressed in Regalis11/Barotrauma-development@3909ca4.

**Comment by Jasontti** [comment]
Tested.
Played different outpost reclamation levels and didn't encounter the error.
Closing ticket.
