### ISSUE TITLE
Or-Component has no "False Output" set by default (Sub Editor)

### ISSUE THREAD

**Issue by Medice0** [Regalis11/Barotrauma#12411]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello,
As the title says, me and a friend just spent a good two hours messing around with the Or-Component, trying to figure out what exactly it was messing up and how, only to eventually find the field for "False Output" to be empty and the source of the problems.
Please look into it and possibly set it to 0 by default like all other components.
![image](https://github.com/Regalis11/Barotrauma/assets/96693339/6baea483-9e92-4070-9fcc-e89b6cf8cb68)
Other than that, great game you made!
~Medice

### Reproduction steps

1. Open Sub editor
2. Place Or-Component
3. Scroll down to "False Output"

### Bug prevalence

Happened once

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
#12321 dealt with this

**Comment by Medice0** [comment]
So if I understand this correctly, this was changed intentionally make newbies learn?

You know what, I don't even think this is that bad of an idea, but I do find it more than irritating that the _official_ Wiki, which should act as a documentation of sorts, lists outputs as "0" and "1" instead of "True" and "False", and doesn't mention that those outputs can be changed. If it were, I would have probably found this problem within 10 mins of experimenting.
![Barotrauma](https://github.com/Regalis11/Barotrauma/assets/96693339/b63aef03-80c2-4bdf-85db-197dbdbdc689)
I hope you consider correcting this. Noone needs to know how the logic of an OR-Gate works, there are more than enough resources online to find that out. What people _actually_ need to know from the documentation is details about in-game specifics.
Thank you for your consideration.

**Comment by mygamingaccount** [comment]
The wiki isn't maintained through this repository, if you want to contribute you should check out the #baro-wiki-editing on the Barotrauma Discord.
