### ISSUE TITLE
Nuclear Depth Decoy not created from from Nuclear Depth Charge made from a fuel rod with the help of an electrician's talent

### ISSUE THREAD

**Issue by Venus-Flytrap** [Regalis11/Barotrauma#12416]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Nuclear Depth Decoy not created from from Nuclear Depth Charge made from a fuel rod with the help of an electrician's talent, only usual Nuclear Depth Charge

### Reproduction steps

go to the fabricator and try to create  Nuclear Depth Charge from fuel rod and try create Nuclear Depth Decoy

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by G-M-twostay** [comment]
works fine for me.

**Comment by Venus-Flytrap** [comment]
> отлично работает для меня.

![image](https://github.com/Regalis11/Barotrauma/assets/140067399/c6ea892d-15c0-410a-9804-99a0e19f4ff1)

**Comment by Venus-Flytrap** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/140067399/537ff7b2-7c40-4406-9301-59d1451fc868)

**Comment by itchyOwl** [comment]
The issue was that you couldn't fabricate nuclear depth decoys with the cheaper nuclear charge variant (recipe from the "Nuclear option" talent), because the recipe required the normal nuclear depth charge, which is technicall a different item. Fixed in Regalis11/Barotrauma-development@da9bb1a.

**Comment by AdamH-Daedalic** [comment]
Tested against feature/ammobox-recycling

Player could create the Depth Charge Decoy with both the Standard type of Nuclear Depth Charge and the cheaper version that is unlocked with the talent. 

Closing as fixed
