### ISSUE TITLE
Bots wont cleanup certain items (wires, buttons, switches and levers)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12413]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Noticed that after buying a lot of items from a outpost store and then ordering bots to cleanup the bought items that they ignored certain items during cleanup

### Reproduction steps

1. Buy wires, buttons, switches or levers from outpost store
2. Undock and order bots to cleanup
3. Notice that they wont touch those specific items

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@8a93c77 and Regalis11/Barotrauma-development@5b417da.

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
