### ISSUE TITLE
Inconsistency in bot cleanup after the Dropped stacks PR

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12414]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the PR makes dropped stacks act as a single item it allows bots to cleanup entire stacks at once if those items are on the floor, but if those items are inside a crate they will still clean them one item at a time.

So for consistency we should allow bots to cleanup entire stacks from crates as well, as otherwise it is more convenient to drop bought items from crates before ordering bots to cleanup. 

### Reproduction steps

1. Buy couple stacks of items from a outpost store
2. Drop all the stacks on the floor
3. Order bot to cleanup and notice that they will clean the entire stacks that were dropped
4. Reset the round
5. Don't drop stacks on the floor
6. Notice that bots only clean one item at a time from the crates

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
This seems to have reversed at some point, now bots cleanup entire stacks from crates but only one item at a time from the floor. 

I also noticed that when a bot cleans up a item from a newly dropped stack of items which hasn't been on the floor previously the stack seems to drop through the submarine, the bot can still access the stack to clean up the rest of the items but for the player the stack isn't there. I wonder if this has something to do with as to why the logic has changed in terms of not cleaning up entire stacks anymore from floor. 

This issue wasn't present when I first wrote this ticket, on the time of writing this ticket the bots behaved the same as players where a stack of item is just considered 1 item when picking it up from the floor.

**Comment by Rokvach** [comment]
I've kinda tested this already, but it doesn't hurt to have another pass on it

**Comment by Jasontti** [comment]
Bots having cleaning order does make them work correctly from trader crates or from the floor.

One issue that was found that if bot does passive cleanup they will deposit only one item from the stack and leave rest of them in their inventory.

1. Drop stack of ethanol near idling bot
2. They will take whole stack
3. Observer that they only deposited 1 item from the stack in cabinet

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
