### ISSUE TITLE
Veteran Talent description has odd phrasing

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12428]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The captain's veteran talent has the following description:
_Gain a one-time bonus of 20 Helm and 5 to all other skills._

The effect of the talent is +20 helm and +5 to all others _permanently_.

There are many other talents that give bonus skill, however they are all worded like "get 20 Helm", "Boosts your Helm skill by 30", "Gain a bonus of 15 to Medical", "their Medical skill boosted by 30", "Gain a bonus of 10 to Electrical Engineering" etc.

The unique phrasing of the Veteran talent has caused quite a few players to be confused as to what it actually does (often coming to the erroneous conclusion that the bonus disappears on death) when it actually does the same thing as all the other skill boosting talents.

The wording should probably be something like "Boost your Helm skill by 30 and all other skills by 5." Or something like that to be in line with all the other talent phrasing.

### Reproduction steps

Read the Veteran talent description and see that it has completely different wording compared to all other talents

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AdamH-Daedalic** [comment]
Tested against fix/talent-description-consistency

New text changes appear to match the rest of the skill wording and I cannot spot any other issues/errors in any of the skill descriptions.

Closing
