### ISSUE TITLE
Gigantic Iceberg-Cave

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12427]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing things, I witnessed across a gigantic iceberg-cave.
The ice covered the entirety of the cave

The cave isnt accessible so you can only see it with freecam

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/edf88587-b823-4202-a8ec-396ad05823d4)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/a6e3be9f-3696-468b-8eb7-1969cb4c541e)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/525b3d2a-9031-4936-aa34-974af8bb8c3a)

### Reproduction steps

Hosted multiplayer cargo mission on unstable

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/b5e9d73d-9265-4ef0-9302-5ebb878b1e0a)

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by DrinkFromTheCup** [comment]
To be honest, we with boiz were playing a plenty of missions last weekend - and noticed obnoxious amount of inaccessible caverns.
I. e. radar locates minerals, we grope around landmass where minerals were detected for half an hour looking for entrance - and find the only potential entry point is blocked by non-destructible ice (or we've failed to cause enough damage to break it).
Something probably went wrong with level generation. No idea how to test it as player (i. e. without implementing some warnings and probably debug minimap markers in case of especially blatant terrain overlaps then rebuilding the client) though.

**Comment by itchyOwl** [comment]
Possibly a bug or a symptom of one. Assigned to @Regalis11 to evaluate if it's worth looking into.

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/9bb93cdd2370c14a53e103ccf06e14354a06b881

Tried with steps and seed provided.
Looked at some levels in MP with random seed.
Generated many levels in leveleditor.
No issues found
