### ISSUE TITLE
On older saves you can store any items in the new container slots on cabinets

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12424]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I think there should be some restrictions as to which items can be stored there as well as we shouldn't autosort those slots either because what happens is that it will pull all the storage containers out of those slots every time you sort the cabinet. 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/7ae97217-eb12-420c-8b83-5091429b7f50)

### Reproduction steps

1. Load up a older save, I was using the "Too many items" save which we've used for performance benchmarking previously
2. Notice that you can put any item on the container slots even though it only takes one of those items
3. Place storage containers on the container slots and press auto sort, notice that the storage containers gets moved out of the slots into the main cabinet slots. Also if you have a cabinet full of items and you auto sort it will populate the container slots with a random item from the cabinet.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/ffedca373c81af8821f9b6b85f8b7968f06ee496

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
