### ISSUE TITLE
Submarine got stuck permanently

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1243]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Submarine does not move at all, in fact it got stuck permanently. Fixing the engine did not change anything, fixing up the junction boxes for the navigation terminal didn't do anything, fixing the outer hull and junk didn't do anything, fixing up the reactor didn't do anything, nothing could move this submarine.

**Steps To Reproduce**
I do not know for it is quite random. I encountered it near 300m away from the outpost in the first campaign level. A cool detail is that it's as if the sub was glued to the wall, even though it was only really close to it and never clipped into the wall nor touched the wall.

**Version**
Windows 10 64 bit, rx 580 4 gb, r5 2600, 8 gb ram, steam version.

**Additional information**
Ask me in the comments for any further information, can't think up of any at the moment.

**Comment by rico6822** [comment]
It happened to me once. After I killed a monster and saved my crew from landing in the abyss by removing water from the ship it stopped in once place. There were no walls in the range of at least 120 meters.

**Comment by rico6822** [comment]
It happened to me once. After I killed a monster and saved my crew from landing in the abyss by removing water from the ship it stopped in once place. There were no walls in a range of at least 120 meters.

**Comment by AbominationBanisher** [comment]
Happened to me again, yesterday. The submarine got stuck and would not move up, but could float down. This is game breaking. Campaign singleplayer btw.

**Comment by OverwatchVoice** [comment]
I heard people saying this. Maybe try using the "lock" command to undo it?

**Comment by Regalis11** [comment]
Haven't found a way to reproduce this and we haven't gotten any additional reports about this, may have been fixed.

**Comment by FearsomeCrow** [comment]
having the same issue, singleplayer campaign- fixing engine did nothing, fixing up the junction boxes for the navigation terminal did nothing, fixing the outer hull etc didn't do anything, fixing the reactor didn't do anything. this all happened after being simultaneously attacked by a moloch and hammerhead. sank all the way to the depths and can't go up :/ f
