### ISSUE TITLE
Problem in Multiplayer: NPCs get stuck to the floor while crouched

### ISSUE THREAD

**Issue by DeusVult300** [Regalis11/Barotrauma#12435]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The issue only occurs in multiplayer when trying to host a game. NPCs get stuck to the floor while crouched, preventing them from moving or interacting with them. Additionally, players randomly enter ragdoll mode and cannot deactivate it, so the game has to be restarted every time this happens.
This happens in the vanilla version.

### Reproduction steps

It happens every time I host a game in multiplayer mode

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment]
Was this on a custom sub?

**Comment by itchyOwl** [comment]
Reiterating the above: was it on a custom sub or does it happen on any subs? Does it only happen when you host or also when joining a server? QA: Need to confirm the issue and the repro steps.

**Comment by RDR2PCWHEN** [comment]
I have also been experiencing this bug, happens both on vanilla and custom subs, and also affects some outpost NPCs. Tested on both vanilla and modded multiplayer lobbies that I hosted.
