### ISSUE TITLE
items with condition values cause event/message spam.

### ISSUE THREAD

**Issue by TheChosenEvilOne** [Regalis11/Barotrauma#12431]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

most items with a condition value (for example: fuel rods, welding fuel tanks, and oxygen tanks) spam events/messages:
![image](https://github.com/Regalis11/Barotrauma/assets/34602646/becc5c43-abad-4a33-88a9-544458a8b143)
![image](https://github.com/Regalis11/Barotrauma/assets/34602646/9a902f0f-1fdf-4653-a9c1-c0cd2447e67a)
and with large enough amount of these items all clients on the server get kicked after a moment, including the host on listen servers.

### Reproduction steps

I have been consistently able to reproduce the issue with the following submarine (extracted from a campaign save):
[Typhon2.gz](https://github.com/Regalis11/Barotrauma/files/12198000/Typhon2.gz)
(change the .gz extension to .sub, had to change it due to GitHub)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Happens on dedicated and listen servers, have not tested single player.

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5413e3595ed2723d93d22d688918d6d65985991d (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, can be merged and closed.
