### ISSUE TITLE
Bullets lifting characters into the ceiling

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12438]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you shoot someone in the legs, especially with high fire rate weapons, they tend to lift up into the ceiling which can result in stunlocking

Maybe targetforce is too high for the fire rate?

https://github.com/Regalis11/Barotrauma/assets/73229309/4f4e1e18-4381-4371-8b51-20b88e0ea873

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/74c340d6-35d2-430a-8ba1-a60a82014804)

Modded example:

https://cdn.discordapp.com/attachments/426913209602146315/1135217977596325969/wtf_security_cum.mp4

https://cdn.discordapp.com/attachments/426913209602146315/1135236019264950292/556.mp4

### Reproduction steps

Shoot legs

### Version

v1.0.21.0

**Comment by itchyOwl** [comment]
The push forces might require a bit of tweaking. Did you have any active talents that boost the attack power?

**Comment by ubertpendragon** [comment]
No damage buff

There's some kind of break point where the rate of the shots and stun inflicted triggers this

If you shoot faster (bandolier) or stunlock, the character ragdolls and falls to the floor. If you shoot at a certain rate with micro stuns and enough force, you achieve liftoff.

Not sure how or if this is worth fixing in particular, or weapon stunlock in general

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2d03fb328191cbabdae238d488e5e468ef2c6895

> Fixes to projectiles applying impulses in an incorrect direction. The impulse was always applied in the direction from the projectile to the limb it hits, which may not always be appropriate: a fast-moving projectile can have gone "past" the character when the hit registers, or it may have for example hit the limb at the very bottom, causing the impulse to be applied upwards. 

> Now we instead apply the impulse in the direction the source of the attack (e.g. projectile) is travelling, or if it's not moving, the direction it points towards. Fixes https://github.com/Regalis11/Barotrauma/issues/12438, https://github.com/Regalis11/Barotrauma/issues/12530, https://github.com/Regalis11/Barotrauma/issues/12531

**Comment by Jasontti** [comment]
Tested with different skill levels and items.
No issues found in SP or MP.
Closing ticket.
