### ISSUE TITLE
Flare duration was not adjusted

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12430]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since monsters are allowed to damage flares and glowsticks, their health was reduced to 10

The flare condition degradation however wasnt changed:

Glowstick
`<StatusEffect type="OnActive" targettype="This" Condition="-0.0625" />`

Flare
`<StatusEffect type="OnActive" targettype="This" Condition="-0.25" />`

Flares only last 40 seconds as a result

### Reproduction steps

💩 

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@42eb9b8.
