### ISSUE TITLE
R-29 Update

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#12437]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

One way or another, all the changes are related to various complaints from players.

**Changelist:**
- Unlocked for editing and dismantling all logic components and bulbs.
- Auto-closing time for external hatches in airlocks has been changed from 5 to 7 seconds.
- Added closing of the upper hatch in the lower airlock when opening the external hatch.
- Toxin Container has been moved to Medbay.
- Added light switch in crew quarters.
- Changed the lighting of the cargo compartment (added lighting for the upper tier).
- Changed background walls in the medbay, central passage, stowage, engineering compartment, lower airlock.
- Minor decorative changes (engine exterior, bridge, ballasts).
- Added a chair on the captain's bridge and a trash can in the engineering compartment.
- Changed the position of the lockers next to the top airlock.

[R-29-dev-2.zip](https://github.com/Regalis11/Barotrauma/files/12208249/R-29-dev-2.zip)

![wikiimage_01](https://github.com/Regalis11/Barotrauma/assets/29980468/19902d25-ac64-474d-91d1-5deafa5110a5)

### Reproduction steps

1. Play any mode on the R-29.
2. Pick up a wrench.
3. Enjoy the fact that everything can now be unscrewed (Hey buddy! I was fixing the pump and now I have a water detector in my hand, where should I put it?).

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Played with it couple rounds and gave it a once over in sub editor.
Only thing that stood out was that doors were sometimes agressive to close and hard to open afterwards. Motion detector maybe not working correctly?
No other glaring issues found.

**Comment by JeroonBosch** [comment]
Is that an issue that wasn't in the previous R-29?

**Comment by Jasontti** [comment]
It was i not an issue with old one, but wiring and settings are identical, so i don't know why there is different behaviour.

On the right is new and left is from old, saved as assembly.

https://github.com/Regalis11/Barotrauma/assets/8488224/1b1b44e5-0945-42fd-a19a-447041ba0cde
