### ISSUE TITLE
Items with the controller component may now be unintentionally in-game editable

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#12440]
Bunks and possibly some other items using the controller component are now unintentionally in-game editable.

Caused by Regalis11/Barotrauma-development@33f9baa, which turns the `Output` (that defaults to "1") property from `Editable` to `InGameEditable`. Changing the `AllowInGameEditing` on bunks and similar items that shouldn't be edited fixes it, but I'm not sure if it's the best fix to this.  Shouldn't the limb positions be hidden in-game in any case? And should we default the controller's `Output` to 1 in the first place?

Tested in v1.1.5.0 (unstable), not present in the current release.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
