### ISSUE TITLE
"Control" console command selected an incorrect character

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1245]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alright, bear with me. I spawned a charybdis and killed it (hoping to recreate that charybdis crash bug). It dies normally and ladalada. I spawn an endworm. I spawn another charybdis. I type in chat "kill endworm" to see if it crashes when I kill an endworm. Type "control endworm" to check. Instead of controlling the endworm the game makes me control the already did charybdis (the first one).

**Steps To Reproduce**
I pretty much layed it out in the description.

**Version**
Windows 10 64 bit, rx 580 4gb, latest drivers, r5 2600, 8 gb ram

**Additional information**
big fat steamy chunky chungus

**Comment by Regalis11** [comment]
Unfortunately I haven't been able to find a way to reproduce this.
