### ISSUE TITLE
Sometimes Cargo Theft traitor event will give the success message, but fail at round end.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12459]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This should have been fixed (Such as with deconstruction/item removal), but it appears in some cases it can still occur. In my case I had it occur with a chemical shipment mission where I moved the contents of every crate I could fit into another crate, Then threw that out of the airlock with a success message. At mission end however the traitor had failed.

### Reproduction steps

1. Start a multiplayer campaign with at least 3 players
2. Pick the Typhon 2 submarine (8 slots for cargo)
3. make sure a cargo mission is in play (Such as chemical shipment)
4. Trigger the traitor event cargo theft
5. Using one crate to deposit in, empty the contents of as many crates as you can into it.
6. Dispose of that one crate outside the submarine.
7. Get the success message, Dock at a station (back or forwards) and receive a failiure message despite in theory achieving 50%+ of cargo removed.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Very Unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm not sure I understand the issue correctly. The title is about the mining sabotage event, but the description is about a chemical cargo mission, so I assume the event in question is the "cargo theft" one?

I noticed an issue in "cargo theft", but couldn't see anything wrong with the others. https://github.com/Regalis11/Barotrauma-development/commit/db1d80c3673b9b901229792a529da53a2d122980

**Comment by NilanthAnimosus** [comment]
Not sure what made me use the name Mining sabotarge, this was indeed meant to be a ticket for Cargo Theft failing to complete properly.

**Comment by Jasontti** [comment]
Tested.
Mission game mode with cargo mission fails after successfully getting rid of the cargo.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/3852047a-e92a-42c3-b5e2-ffd34d7e0f91)

Success and fail states seems to be reversed for this event

``` xml
      <Label name="waitforitemsdisposed" />
      <WaitAction time="1.0" />
      <CheckItemAction targettag="targetitem" RequiredConditionalMatchPercentage="50" CompareToInitialAmount="true">
        <Conditional InPlayerSubmarine="true"/>
        <Success>
          <!-- 50% items in player sub, not completed yet-->
          <GoTo name="waitforitemsdisposed" />
        </Success>
        <Failure>
          <SetTraitorEventStateAction state="Completed" />          
          <ConversationAction targettag="traitor" text="You've disposed of the cargo." eventsprite="Silhouette" />
          <EventLogAction targettag="traitor" id="status" text="The cargo is no longer found on the submarine. Looks like you're getting paid while your crew is getting played." />
          <EventObjectiveAction targettag="traitor" type="complete" id="traitorobjective.cargotheft.missingcargo" />
        </Failure>
      </CheckItemAction>
      <Label name="itemsstillgone" />
      <WaitAction time="1.0" />
      <CheckItemAction targettag="targetitem" RequiredConditionalMatchPercentage="50" CompareToInitialAmount="true">
        <Conditional InPlayerSubmarine="true"/>
        <Success>
          <EventObjectiveAction targettag="traitor" type="Fail" id="traitorobjective.cargotheft.missingcargo" />
          <SetTraitorEventStateAction state="Failed" />
          <!-- 50% items in player sub, not completed yet-->
          <GoTo name="waitforitemsdisposed" />
        </Success>
        <Failure>
          <SetTraitorEventStateAction state="Completed" />
          <GoTo name="itemsstillgone" />
        </Failure>
      </CheckItemAction>
```

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d230555edc5b824479c4148946967c117deed201

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
