### ISSUE TITLE
Duffelbag traitor events spawn the bag potentially in view of players.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12453]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Given traitor events can be delayed and start mid round / at round start when players are able to see, The spawning of these bags can often be seen when the related event starts, Making it obvious a traitor is active (As well as what their target is). it is even possible to take the bag and its contents before the traitor can reach it for some events which do not spawn the contents on bag pickup but instead on its initial spawning.

### Reproduction steps

1. Start a dedicated server with 3 or more clients.
2. Start any duffelbag event, find sometimes it will spawn in the same hull as a player is in.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Very Unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7d6aeadd58b11202e653fd7d99520b925a887f6b

**Comment by Jasontti** [comment]
Tested.
Duffelbags spawn out of sight on reasonable places.
Closing ticket.
