### ISSUE TITLE
In the duffelbag events, giving the bag to an AI character counts as looking in the bag with no penalties.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12458]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Giving an AI Character the duffelbag (Such as with the bombs) will immediately trigger the bombs, with no penalty to the player for the AI having been given the bag from the traitor directly, allowing the traitor to forcibly initiate (And thus successfully complete) their objectives.

### Reproduction steps

1. Start a multiplayer campaign with at least 3 clients
2. Trigger the traitor event Duffelbagbomb
3. Take the bomb out to place anywhere and hand the empty bag to an AI (Who will proceed to clean it up)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Very Unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ca86d106d682167ed52f234b7f3d38d6ca703d65

**Comment by Jasontti** [comment]
Tested.
Gave bag to NPC crew mate with and without the bomb.
No issues found.
Closing ticket.
