### ISSUE TITLE
In traitor duffelbag bomb events, if the traitor does not advance conversation messages the bombs cannot be disarmed.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12457]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As a traitor, it is possible to stop the defusal by simply not progressing the conversation actions, this may actually effect many events in ways that are beneficial to the traitor as well by abusing this caveat.

### Reproduction steps

1. Start a multiplayer campaign with 3 or more clients
2. Trigger the Duffelbagbomb or duffelbagbomb2 events
3. When the first dufusal stage is attempted (Screwdriver), as traitor do not progress the messages
4. Find the bombs do not rename their descriptions and continue ticking down even if correctly disarmed
5. Alternatively, do this on the last defusal stage, to find it still ticks down and does not disarm.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Very Unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/770492556060e5749a64b52a5619c387d7a6a83e

**Comment by Jasontti** [comment]
Tested.
Traitor can still just not close dialog box at any stage of defusal progress and bombs could not be defused in both events.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/472e0be39ad3012749bf82939429402d5fef23ca

**Comment by Jasontti** [comment]
Tested.
theduffelbagbomb works.
theduffelbagbomb2 stalls at this.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/735dde8f-df7e-4f48-9b39-4c8aa8c57906)
`ContinueAutomatically` missing from traitors dialogue

**Comment by Jasontti** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/pull/4393/commits/ddcb776f3d89ea949bb9da83f776555499df3d81

No issues found.
Closing ticket.
