### ISSUE TITLE
Traitor Duffelbag bomb events spawn the bomb(s) before the traitor has found the bag.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12454]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The duffelbags when spawned will spawn the bomb(s) in either event before the traitor has picked them up.

The events however were not written to trigger/do anything if found weith the bombs, or the bombs having been removed if a none traiter finds the bag first. It will instead remotely arm even after the bombs are removed or tossed out of the submarine.

In either case, the traitor wins if they pickup the bag, regardless of the state of the bombs - So either the event needs some tweaks to support failiure on the bag being found first, or the bombs should likely not spawn initially to make the duffelbag blend in.

### Reproduction steps

1. Start a dedicated server with 3 or more clients
2. start a campaign
3. trigger the traitor event Duffelbagbomb or Duffelbagbomb2
4. Find the bag as a none traitor before a traitor can.
5. Find there is no update to the event/description that it has been found/noticed (For traitor or none traitors).

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Very Unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in configuration stated in ticket.
Bombs are now spawned correctly after examining the bags.
Events don't seem to progress after finding the duffels.
No tick tick message to non traitors.
Battery in theduffelbagbomb2 doesn't degrade and there is no harm on removing the battery from the bomb.
