### ISSUE TITLE
In the duffelbag traitor events, not progressing messages does not arm the bombs.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12455]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It is possible in the duffelbag bomb traitor events to avoid arming the bombs after someone finds the bag, or you find the bag. Simply not progressing the conversation messages received will do this.

### Reproduction steps

1. Start a multiplayer campaign with 3 or more clients.
2. Trigger the traitor event Duffelbagbomb or Duffelbagbomb2 events.
3. Pickup the bag but dont progress the message for "Someone looked inside the bag and the time bombs have been activated"  or before it.
4. Nobody will receive the Tick Tick Tick messages, the bombs could be removed from the bag and not armed until the traitor progresses messages before or after the bag is found.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Very Unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a3d770064b9ecc112c6800e42d06a4d625b2fa1.

I couldn't see anything wrong with the "theduffelbagbomb" event, only "theduffelbagbomb2" seemed to be broken. Are you sure the 1st one had the same issue?

**Comment by NilanthAnimosus** [comment]
Its possible there wasn't any issue with the other event, I recall reordering my notes and trying to reduce duplication in what I was creating issues with and could have just mixed things up in that regard as one or two applied to multiple events. Can check for it in both events on testing the fixes though.

**Comment by Jasontti** [comment]
Tested.
Events don't seem to progress after finding the duffels, examining and confirming the dialog.
Doesn't matter if non-traitor looks in the bag.
No tick tick message to non traitors.
Battery in theduffelbagbomb2 doesn't degrade and there is no harm on removing the battery from the bomb.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a2cf51811a3b6e811ef70517ce00314d79a2c844

**Comment by Jasontti** [comment]
Tested.
Bomb is armed when when non-traitor picks up the duffel bag.
Closing ticket.
