### ISSUE TITLE
In the traitor event Duffelbagbomb2 defusing one bomb defuses all bombs (Even if not in inventory or found)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#12456]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The way the events are written if you defuse one of the bombs, all bombs are defused at the same time even if not in the inventory.

### Reproduction steps

1. Start a multiplayer campaign with at least 3 players.
2. trigger the traitor event Duffelbagbomb2
3. Defuse one of the bombs, ending the event and both bombs from exploding.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Very Unstable 1.1.5.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3095bc52d1c78ca56f35da85fdbf7f76a8a30d1

**Comment by Jasontti** [comment]
Tested.
Only one bomb is spawned and it can be defused.
No issues found.
Closing ticket.
