### ISSUE TITLE
Fabricator ammunition box recipes show quality indicator (remove tag or implement ammo box quality)

### ISSUE THREAD

**Issue by Next-Door-Tech** [Regalis11/Barotrauma#12460]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the fabricator, all ammo box recipes show the "Normal Quality" tag at the end of their name despite higher quality ammo boxes not being implemented. This may mislead new players into thinking higher quality ammo boxes _are_ possible to create, leading to confusion/frustration when high weapons skill crew members still only craft "normal quality" boxes.

Either:
1. The "normal quality" tag should be hidden for ammo boxes if ammo box quality is not a planned feature
2. Ammo box quality should be implemented as a new feature. Higher quality ammo boxes should probably have boosted capacity, and potentially damage.

![20230802121606_1](https://github.com/Regalis11/Barotrauma/assets/5867663/e2b608a8-ddef-405f-9fb5-fdfc7d3e2273)

### Reproduction steps

1. Go to a fabricator
2. Select any ammo box recipe (new or recycle)
3. Recipe name will show `(NORMAL QUALITY)` at the end despite ammo boxes not being able to be constructed with higher quality (crafter's weapon's skill does not matter).

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by VaelophisNyx** [comment]
I'd *love* to see quality ammo boxes that either have more uses or somehow do more damage or something
it'd be a nice reward for getting up to high weapons skill

you'd probably need to also do that to railgun shells, though, which would be difficult probably

**Comment by Herbalicious** [comment]
Not sure if this commit has been pushed to live yet, as I still see this issue (and this hasn't been closed).
In the off chance it helps, I've found the issue has to do with the visual length (or font-size/scaling) of item names; ammo boxes just tend to have very long names.
If the whole thing has already been addressed and just isn't live yet, ignore me. 🙃
