### ISSUE TITLE
General Item Sprite Oversights/Inconsistencies

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12462]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Clown masked when dropped uses the inventory icon instead of the in-game sprite like the diving mask.
![20230803152132_1](https://github.com/Regalis11/Barotrauma/assets/104994469/80f7ca2e-04d6-4507-aa1b-4fb16dd66b18)

The in-game sprite it should use to be consistent.
![Clown_Diving_Mask_sprite](https://github.com/Regalis11/Barotrauma/assets/104994469/6c7b0b73-3793-4fdc-8617-5811d98d4b88)

### Most of the others are completely unnoticeable in-game due to the zoom:

Top of the auto-injector headset in-game sprite has a floating bit from the bandolier, additionally the auto-injector headset has the same issue where it can be placed over hats as #11474.
![Joojooma](https://github.com/Regalis11/Barotrauma/assets/104994469/99c43d2f-5b35-4f19-9954-b9a9b7ae157d)

Flashlight sprite has a weird semi-translucent line.
![20230803162649_1](https://github.com/Regalis11/Barotrauma/assets/104994469/f8083468-518e-4051-8ca0-6ed5026df218)

Ceremonial Sword sprite's bottom is cut.
![20230803160614_1](https://github.com/Regalis11/Barotrauma/assets/104994469/73d15a8b-b4b6-440c-9b44-6974b37c9897)

![Ceremonial_Sword](https://github.com/Regalis11/Barotrauma/assets/104994469/a701ee09-d59e-446c-a996-d1577364ecdc)

Scrap cannon's stock? is cut at the bottom, as can be seen inside the MS Paint Red™ circle.
![Joojaoma](https://github.com/Regalis11/Barotrauma/assets/104994469/fbde5704-6d5c-4c3e-be1f-de58e990e4aa)

Also surely the scrap cannon is supposed to have a stock here? Making the thing that looks like a stock, actually a stock?
![Scrap kannonen 2](https://github.com/Regalis11/Barotrauma/assets/104994469/de13f01d-3a6f-4903-9953-c493865f4a82)

Instead of having the mechanic wackadoodle squeeze the sides of the weapon to hold it?
![Wackadoodle](https://github.com/Regalis11/Barotrauma/assets/104994469/e74878e0-3581-4bb3-9d82-431d9e296fc0)

Copy of #11227 which was transformed into #11241 both of the acid grenades don't have a inventory icon and instead use their in-game sprites, meaning that both grenades are the only outliers that aren't slanted inside inventories, looking cheap.
![20230803154330_1](https://github.com/Regalis11/Barotrauma/assets/104994469/31e1dbdb-e03c-4b8a-a314-cea3e2b76f56)
What makes both of them look even cheaper is the fact that they don't even have a unique texture, and are instead recolours of existing grenades, like why does a 40mm acid grenade that only does acid burn damage have a fragmentation sleeve? A redesign of both acid grenades to make them unique would be appreciated.

### Reproduction steps

1. Load up the camel in sub editor.
2. Place the items in question.
3. Stare intently at the items in question.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Arctodites** [comment]
Other sprites with similar issues (misalignments / cropping artefacts) include:

•	‘Shell A 0 Degrees’ (noticeable black lines)
•	‘Shell A 4 Degrees’ (noticeable black lines)
•	'Submarine Bow C' (a faint dot and line pattern to the right of the sprite)
•	'Shuttle Lights A' (black spots / artefacts)
•	'Shuttle Shell A15B' (minor black spots)

•	‘Office Desk’
•	‘Large Shelf’
•	‘Trash Can’
•	'Armchair' (thin lines at top and bottom left and top right corners of sprite)
•	'Office Chair' (minor artefacts)
•	‘Large Diving Suit Locker’ (Legacy)
•	‘Camera’
•	‘Auto-Injector Headset’
•	‘Thorium Fuel Rod’


This list isn't exhaustive, but the above are amongst the most noticeable.  The dark lines from the miscropping of the Shell A pieces are only noticeable once lighting layer visibility has been turned on in the sub editor.

**Comment by CRedinger** [comment]
There seems to be an issue with sprite depth of dive suit shoulder pieces. Specifically when the character is at a higher sprite depth than usual, the shoulder portion of a dive suit does not seem to have its sprite depth adjusted with the rest of the suit. 
Here I have a ladder at sprite depth .900 and fins at depth .501.
![image](https://github.com/Regalis11/Barotrauma/assets/49667563/1d9a0560-04a2-4a90-b3bf-c58de79fe084)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/ad8a00975de30dcd281146ac3b1684e0272bc421

Some sprite bleeding is still present in:
Flaslight
Auto-injector headset
Bandolier
Crawler mask

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/080c0307-dccc-447d-a98a-2db8764c9dbe)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a3033bb918d4886c885a3ae862aa995718798ba

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/07c2f9f79ade033617fd8ea955e3aee3caf4b5fa

No issues found
Closing ticket
