### ISSUE TITLE
General Syringe Sprite Inconsistency (Mostly for Pomegrenade Extract)

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12461]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Syringe ~hitboxes~ spritebox(?) vary from syringe to syringe.
Example: Chloral Hydrate's ~hitbox~ is taller, while Cyanide's ~hitbox~ is wider.

![20230803144315_1](https://github.com/Regalis11/Barotrauma/assets/104994469/481acf75-5fba-4cec-9712-affe673c448f)

There are too many examples to list and there isn't a pattern.
![20230803144800_1](https://github.com/Regalis11/Barotrauma/assets/104994469/2011ac95-fa0d-4c8a-a28e-ead54da71092)

The biggest outlier of this is the Pomegrenade Extract, which causes the sprite to be misaligned both in hands and syringe guns.
Additionally the sprite has the very bottom part chipped off.
![20230718194145_1](https://github.com/Regalis11/Barotrauma/assets/104994469/1933ab71-8132-4a7a-94e3-35f98f53b793)

Most syringes don't have any text/symbols on the in-game sprite, but some outliers do.
![20230803145832_1](https://github.com/Regalis11/Barotrauma/assets/104994469/3187ee55-00a1-4051-b141-24be74406ae0)

Off-topic, an overhaul of syringe sprites to make syringes easier to discern on lower resolutions would be appreciated.
![20230803151255_1](https://github.com/Regalis11/Barotrauma/assets/104994469/ef48d026-9f20-4bcd-9ffd-429d3c7fffa6)

### Reproduction steps

1. Open camel in submarine editor.
2. Place the aforementioned items.
3. Stare intently at the items in question.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed some of the worst offenders in https://github.com/Regalis11/Barotrauma-development/commit/5868b736959aa119f7de44b02a6e4904ebe4cd8b (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
