### ISSUE TITLE
CPR can revive players, even with no oxygen source available

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12468]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

CPR can reduce `oxygenlow` even if the target has no available oxygen.
Drowning in a submerged room or breathing from an empty O2 bottle does not stop CPR from reviving humans. 

Liquid Oxygenite and (emergency) Diving Masks have no real purpose since CPR can cure low oxygen in all circumstances.

No suit in a flooded room before and after CPR
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/2e518a7a-2679-4ed0-add1-2a1208d72669)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/201c8a4b-e91b-49c1-bc0a-4bbd35a2604d)

Empty O2 bottle
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/52bd8aac-f236-429a-a710-4b32e4f5b6aa)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/f846fd3c-7596-4753-bbb2-b36e96659122)

### Reproduction steps

1. Flood a room
2. Make a bot go unconscious by drowning
3. Set medical skill to 100
4. CPR the bot
5. oxygenlow goes down
6. Bot regains consciousness

### Version

v1.0.21.0

**Comment by ubertpendragon** [comment]
Other CPR observations:

The "Revive" component of the CPR will often result in instant revives, occuring on the very first pump(s) of CPR. 
It's excessively generous to the point of not actually seeing CPR being performed.

The "Stabilization" part of CPR is completely bypassed by "Revive"

_Freshly spawned medic instantly reviving:_

https://github.com/Regalis11/Barotrauma/assets/73229309/bbd015b0-8b50-4538-8c4a-93376db625f0

Every class but Captain spawns with enough medical skill to completely ignore the organ damage aspect of CPR, which stops at 20 according to the formula

Mechanic, Engineer and Security spawn with 15-25
Assistant spawns with 20+

wiki for clarity
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ccc5c235-8ef8-44d1-aa45-11094ff384f7)

**Comment by Regalis11** [comment]
> CPR can reduce oxygenlow even if the target has no available oxygen.

This is intentional. That's kind of the point of the mouth-to-mouth part of CPR, to provide oxygen to a person who's not breathing.

> Liquid Oxygenite and (emergency) Diving Masks have no real purpose since CPR can cure low oxygen in all circumstances.

I don't quite agree with this: they're useful for preventing _yourself_ from suffocating and for treating oxygenlow if your medical skill isn't high enough to effectively do it via CPR.

**Comment by ubertpendragon** [comment]
Take a look at the comment and issue above, CPR is broken in a few ways:

- Revive is WAY too good and completely invalidates stabilization. 
- Stabilization only works for mouth-to-mouth (2 seconds every 15 seconds)
- Organ damage almost never happens due to formula

I would get rid of revive entirely, refill O2 slowly with chest compressions (with a source of oxygen),  remove mouth to mouth (the animation is hardly visible) and tweak the formula for organ damage

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/76b43e387fbe0ece3b1d0a71091ea4764b09272b
