### ISSUE TITLE
Jestmaster questline issues

### ISSUE THREAD

**Issue by FaIIanor** [Regalis11/Barotrauma#12464]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I just wanted to say that the honkmotherian questline is broken, and jestmaster doesnt appear after you bonk an abyss creature dead or alive. People say that after some patch it was broken because of the faction quest spawn rates, i really hope you will be able to patch it.

### Reproduction steps

1. The Jestmaster appears, on a random clown outpost. He asks you to bring him a clown mask that he has on.
2. You bring it to him
3. He asks you to bonk an abyss creature with a toy hammer, if you do it you get Children of the Honkmother reputation, but he doesn't spawn on any clown outposts.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Hamburgian** [comment]
i got this bug too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a19caa4e464f4aa01e7828f870ca1c996f36e6e5 (commit in our private repo)

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll keep it open until we've tested the fix internally. :)

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
