### ISSUE TITLE
Item name overlapping with the sort buttons in a container interface

### ISSUE THREAD

**Issue by guy123213** [Regalis11/Barotrauma#12472]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

i was playing barotrauma with russian language and found this in oxygen tank shelf  
![Снимок экрана_20230805_182428](https://github.com/Regalis11/Barotrauma/assets/141508704/42c5df72-cb6d-4d54-90ec-00d68ee9a1c7)
![Снимок экрана_20230805_182332](https://github.com/Regalis11/Barotrauma/assets/141508704/8f2054f7-65da-450f-87da-094db98aee36)

### Reproduction steps

just open oxygen tank shelf with russian translation 

### Bug prevalence

Just once

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

unstable (1.1.6.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
So is the issue that the text overlaps the UI elements or is the translation incorrect in your opinion?

**Comment by guy123213** [comment]
first. translation is correct

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5889698507bfb3167132712ee61fcd327ec97767 (commit in our private repo)

**Comment by guy123213** [comment]
thanks (:

**Comment by Jasontti** [comment]
Tested.
Found another overlapping text in junction box.
No other issues found.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/2e8ec296-e96d-45ff-975a-1fc94e99338b)

**Comment by Jasontti** [comment]
Some more findings with sort buttons with english.

1440x900 windowed
![2023-08-31_16-06](https://github.com/Regalis11/Barotrauma/assets/8488224/c6805aa3-2b52-489b-a691-363801a653e5)
1920x1080 Borderles fullscreen
![2023-08-31_16-07](https://github.com/Regalis11/Barotrauma/assets/8488224/e463e53d-b7c6-438b-b224-b77346fd74e4)

Text in general likes to overlap with top of the header element if there's 2 lines of text
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/a06bacca-1e60-4659-85e3-d335f8a498aa)

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
