### ISSUE TITLE
Refine taint chance is sometimes incorrect in the research station

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12477]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When refining genes, unless the character has >197 medical skill, there is going to be a non-zero chance that the output is tainted. The chance that the output is tainted is given by `0.99 * [highest input gene quality] * [1 - 0.00375 * ([Medical Skill] + 70)]`. (Found by diving through the code and a lot of testing).

The research station however does not output the correct percentage all the time. It presents the chance as `0.99 * [left slot gene quality] * [1 - 0.00375 * ([Medical Skill] + 70)]`

This leads to the behaviour that swapping the positions of the genes in the research station will change the taint chance that is told to the player, whereas the taint chance is irrespective of gene position. e.g. having a 10% gene in the left slot and a 90% gene in the right slot will read out an incredibly low chance of tainting, but when refining the output is almost certain to be tainted due to the presence of the 90% gene. This means that 50% of the time players are being told that the taint chance is  lower than the true chance. Ideally the taint chance shown to the player should be the actual chance.

https://github.com/Regalis11/Barotrauma/assets/37850646/ca169d8b-53c8-4977-b2c3-25e161e22f0b

### Reproduction steps

1. put a very high strength gene in the right slot and a very low strength gene in the left slot of a research station
2. observe that the purported taint chance is very low
3. refine
4. observe that the output is very likely tainted
5. repeat the experiment until you are statistically confident that the taint chance is incorrect

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66666dd6b950369e3d41f7b4354cd494e557a017
