### ISSUE TITLE
Outposts catching fire and subs pretending to flood

### ISSUE THREAD

**Issue by beargoesshid** [Regalis11/Barotrauma#12474]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Towards the end of a long mission, my sub was attacked by a few hammerheads and subsequently flooded. However, after the holes were patched and the sub was dry, the texture(?) of the water still filled the sub, and was even slowly rising. My character was not drowning, and I could walk through it as if it was air, leading me to believe that its just the texture alone.

When I made it to the outpost, I was greeted by a fire that popped out of the middle of nowhere in the sub bay. Electrical panels were breaking down, the camera was rocking as if something crashed into the outpost, and NPCs despawned without notice.

### Reproduction steps

1. Completed every (4) mission and proceeded to the next outpost
2. Attacked by a hammerhead encounter
3. Used captain
4. Switched from captain to another crew, looted the hammerheads
5. Switched back to captain
6. Sub "flooded"
7. Proceed to next outpost,
8. Fire & Death

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

Other

### -

Unstable V1.1.6.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
This is caused by [psychosis](https://barotraumagame.com/wiki/Psychosis).
