### ISSUE TITLE
[SPOILER] a hidden id card can't open the secure cabinet as intended

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12487]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In "SecurityModuel_01_Abandoned" there's a hidden id card which was a key to the secure cabinet nearby. But after 1.0.20.0, it isn't anymore due to this change: `- Fixed secure steel cabinet in abandoned outposts being openable with a randomly selected bandit's ID card, not the bandit leader's card as intended.`
![idcard](https://github.com/Regalis11/Barotrauma/assets/99462070/a00d42d4-3303-4c86-8b2c-2cdd8a5e1029)

### Reproduction steps

1. Open "SecurityModuel_01_Abandoned". 
2. Check the id card's tag and the secure cabinet's required items.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
