### ISSUE TITLE
Performance Issues on High End Computers caused by Bots

### ISSUE THREAD

**Issue by Tagael** [Regalis11/Barotrauma#12482]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Greetings dear Barotrauma team. 

My friends and I (5 people) have been playing Barotrauma since the beta phase. We never had any serious problems. 
We also started playing with mods early on after playing through the campaign without mods. 
We also haven't had any problems with mods until a few weeks ago. The performance has dropped drastically. Since the performance problems are already known, we have tried to narrow down the problem more precisely. 
For information: All 5 people in our group use high-end computers. We all have the latest I7 processors and NVIDIA RTX 3000 series graphics cards and lots of RAM. 
So we first completely turned down all the settings in the game (especially the light settings). interestingly, this had no effect on the performance at all. Even when all 5 people had the light settings set to 10%, nothing changed in performance. 

We then noticed that the performance always drops rapidly when we are docked at a station where there are a lot of bots. 
While traveling between stations, we have no issues even with 25 active mods. If we dock at a small station, only small issues occur. At larger stations with a lot of bots, however, we can hardly move. I hope that this information will help you to improve this wonderful game. Thank you!

### Reproduction steps

1.Start a Multiplayer game with 5 Players
2. dock a station with high amounts of NPCs
3. observe performance drop

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Hi, thanks for the report! Some further questions:

1. Does it happen in the single player campaign too, or multiplayer only?
2. Does it happen always when you dock a city (=larger station)?

Moving to QA investicate and pinning as high prio: need more precise steps to repro (unless it just happens always, which would be weird).

**Comment by Tagael** [comment]
Hey,

 

we are only playing multiplayer, never tried in in singleplayer. 

 

It happens always when we dock onto a larger city, yes. We observed that it correlates to the numbers of NPC but thats just our observation. There are some security outposts (military) which a very high number of NPCs thats where we had the most lags. 

 

Maybe thats a cause for the performance issues that got reported. 

 

Greetings

 

Alexander

 

Von: Lauri Härkänen ***@***.***> 
Gesendet: Freitag, 11. August 2023 08:34
An: Regalis11/Barotrauma ***@***.***>
Cc: Tagael ***@***.***>; Author ***@***.***>
Betreff: Re: [Regalis11/Barotrauma] Performance Issues on High End Computers caused by Bots (Issue #12482)

 

Hi, thanks for the report! Some further questions:

1.	Does it happen in the single player campaign too, or multiplayer only?
2.	Does it happen always when you dock a city (=larger station)?

Moving to QA investicate and pinning as high prio: need more precise steps to repro (unless it just happens always, which would be weird).

**Comment by Tagael** [comment]
I just had another Idea that came to my mind, when I found a performance Issue report from Isyprus from 2022. 
He reported memory usage issues. 

I just startet our gaming server without beeing docked at a larger station and without my friends being only. Just me and our bots: 

![RAM](https://github.com/Regalis11/Barotrauma/assets/141837082/5427f146-8686-4abe-9024-2bda1b9930df)

I have 16GB of RAM and Barotrauma uses 4,3GB RAM on a smaller station without my friends beeing online. 
The CPU is is at 22% and the NVIDIA at 3%.

Then I just drove back to a station with a lot of NPC.
As you can see the RAM usage went up to over 5GB but CPU is still at 23% abd GPU at 3%. And the lags started again. I'm not sure if that's the cause of the lag cause 82% memory usage is not 100% but maybe it contributes. 
The Legs occured even if I was the only human player on the server just playing with bots but on a multiplayer dedicated server. 

![RAM 2](https://github.com/Regalis11/Barotrauma/assets/141837082/d020fe6c-5ee0-4344-aba5-dea9011ecc71)

**Comment by Ricky2235** [comment]
do showperf in the console when your lagging and take a picture of it and take a picture of it after the lag goes away this will give them alot more info

**Comment by Regalis11** [comment]
Thank you for the extra info! As Ricky2235 commented, entering "showperf" in the console and taking a screenshot of the view would give us a lot more clues for diagnosing this. A save file might also help.

This could also be the same issue or (related to) https://github.com/Regalis11/Barotrauma/issues/12482

**Comment by Tagael** [comment]
Actually we all deinstalled the game, reinstalled it and had no further issues. 
I will test it in the upcoming weeks and will report if the issue reocurres.
