### ISSUE TITLE
Throwing pose raises the arm too high, items hit the ceiling

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12481]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The throwing pose lifts the arm of the character so high, items tend to hit the ceiling as they are thrown
The arm should be lower and not fully extended

Size reference: door-height hallway

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6fc1a7e4-ce1b-4255-943d-32f38d5ff3c4)

Combined size of item + arm extension puts the collision box of the item inside the wall
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/e45acff8-6e4b-418f-87fa-6e3db6ab5839)

### Reproduction steps

Throw deepdiver ducks in a Barsuk, hit yourself or the ceiling half of the time

**Comment by Hamburgian** [comment]
https://github.com/Regalis11/Barotrauma/assets/141864587/5b015aed-8d55-422c-905b-c4bb00158f88

this does seem like a bad thing but it can be easily avoided by crouching or not using the barsuk for traitor mode

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/743866b8e12ef89657f6640fc98fa3b487ed5cae

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4488/commits/2b575c97307f8d5c9de8d14e5e9b1142e4f17ed5

Threw around different objects

No issues found.
Closing ticket
