### ISSUE TITLE
Nuclear depth decoy bug (Wrong icon)

### ISSUE THREAD

**Issue by KingKaijuTJ** [Regalis11/Barotrauma#12484]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

It was a long time since I noticed that Nuclear Depth Decoy had wrong Icon. (The icon was showing diving suit)
Bug does no harm to my playthrough, but it pisses me off a bit.
So, I'm waiting for the bug to get fixed, thank you.

### Reproduction steps

1. Use the crafting table
2. Search for Depth Decoy Charge
3. The icon is showing diving suit icon instead

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Can't repro: both the nuclear depth decoy and the nuclear depth charge seem to have the correct icons:

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/fc8eb1d4-d5e7-473d-8a3b-26223371139e)


![image](https://github.com/Regalis11/Barotrauma/assets/5370738/7d2f83e6-54d9-44d7-954c-ae7af7839f01)

![image](https://github.com/Regalis11/Barotrauma/assets/5370738/1ab11da2-b900-4aa6-a300-de6bb4f8bf07)

**Comment by Regalis11** [comment]
No known steps to repro, but could be related to some mod.
