### ISSUE TITLE
Using cigars underwater while wearing divingsuits

### ISSUE THREAD

**Issue by G-M-twostay** [Regalis11/Barotrauma#12499]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can smoke cigars underwater in a divingsuit. However, the cigar appears to also be underwater and outside of the diving suit. You simply put the cigar to the area near your mouth to smoke it, even though it's outside the diving suit.

This is quite weird because 1. cigars probably can't burn underwater 2. the smoke probably can't go through the divingsuit that blocks water.

I don't know if this is an intended behavior, but given that in a previous version equipping a flashlight will make it looks like that the flashlight is sticking out of player's mouth was considered a bug, I would consider underwater divingsuit-penetrating smoking to also be a bug.

### Reproduction steps

1. Get a cigar or pipe tobacco.
2. Get a diving suit.
3. Put on the diving suit and go out of the sub.
4. smoke the cigar/pipe tobacco

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Prevented smoking pipes and cigars underwater in https://github.com/Regalis11/Barotrauma-development/commit/cbfb529d62ef4c25bafa4bbb1ef6de6a8bda4e31.

While it's definitely weird you can smoke them with a diving suit on, I'd maybe not change that. If we did that, I think it'd raise the question of why you can drink, eat and use syringes while wearing a suit, and it'd either mean introducing logical inconsistencies in which items can be used, or changes that'd have enormous gameplay implications if we prevented using any of them.

**Comment by ubertpendragon** [comment]
> While it's definitely weird you can smoke them with a diving suit on, I'd maybe not change that. If we did that, I think it'd raise the question of why you can drink, eat and use syringes while wearing a suit, and it'd either mean introducing logical inconsistencies in which items can be used, or changes that'd have enormous gameplay implications if we prevented using any of them.

Protein bars and Energy drinks can be injected in the bloodstream via medical interface and make a syringe injection sound, if it's supposed to simulate feeding someone it should at least make a gulp sound (both of them lack sounds). It doesn't even sound or look like you're eating or drinking. 

https://github.com/Regalis11/Barotrauma/assets/73229309/9b8f90f3-d398-425f-8b23-f1ab7d1be9d0



As for the pipe I loved the in-universe silliness of smoking underwater; replace the smoke by bubbles. 
After all this is what the pipe valve is for

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/37c19680-98d1-483b-9abd-f5d8ec97cc0a)

**Comment by Regalis11** [comment]
> As for the pipe I loved the in-universe silliness of smoking underwater; replace the smoke by bubbles.

This is a good point. Decided to backtrack on this and just switched to bubble particles in https://github.com/Regalis11/Barotrauma-development/commit/48fbbc6c204d6ca0f1d64c40e466e6348d1ce840

> Protein bars and Energy drinks can be injected in the bloodstream via medical interface and make a syringe injection sound, if it's supposed to simulate feeding someone it should at least make a gulp sound (both of them lack sounds).

The intention was actually that using things through the medical interface just means using the item in whichever way it's used (you don't inject bandages or antibiotic glue either). But yeah, a gulping sound would make that intention a lot clearer.

**Comment by DrinkFromTheCup** [comment]
> After all this is what the pipe valve is for

Exactly this.
Poul Anderson described something like that in Margin of Profit.

From engineer's point of view, smoking in a diving suit is just a temporary switch from internal gas storage to external intake. If intake conditions allow smoking - why not?
Same goes for drinks.
Solid food is a problem - although HOPEFULLY it's solved somehow in Year 206X (or otherwise future-which-is-not-so-far). Since it's not zero-gravity environment, the hardest task is cleaning all leftovers up from the helmet. And everything else is manageable with even modern-day technology, if done right.

**Comment by Jasontti** [comment]
Tested.
Smoked in the sub and outside the sub, normally and upside down.
Pipes particles work, smoke in the air, bubbles in water.
Cigar doesn't emit smoke or bubbles. It has pipetobacco as RequiredItem. Removing these lines makes particles work.
```xml
      <StatusEffect type="OnSecondaryUse" target="This">
        <Conditional InWater="false" />
        <ParticleEmitter particle="swirlysmoke" particlespersecond="1" scalemin="1" scalemax="2" anglemin="0" anglemax="360" velocitymin="0" velocitymax="10"/>
        <RequiredItem items="pipetobacco" type="Contained" />
      </StatusEffect>
      <StatusEffect type="OnSecondaryUse" target="This">
        <Conditional InWater="true" />
        <ParticleEmitter particle="bubbles" particlespersecond="3" scalemin="0.3" scalemax="0.5" anglemin="0" anglemax="360" velocitymin="0" velocitymax="10"/>
        <RequiredItem items="pipetobacco" type="Contained" /> 
      </StatusEffect>
```

Also upside down smoking animation is not working. Maybe needs to be separated on it's own ticket?
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/cd39fcbb-f468-4282-97e5-6c23514d7b6d)

**Comment by Jasontti** [comment]
Tested.
Issue was fixed in: https://github.com/Regalis11/Barotrauma-development/commit/10ee146e054b4e68c6cd97aba68784e63c4b9a95
PR: https://github.com/Regalis11/Barotrauma-development/pull/4455
Animation work properly with pipe and cigar.

> Cigar doesn't emit smoke or bubbles. It has pipetobacco as RequiredItem. Removing these lines makes particles work.

Was not yet addressed

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/69f45e81f209dd97c542413a8466f1a632d4b37e

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
