### ISSUE TITLE
Submarine shells sourcerects  are 1 pixel too long

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12491]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On Shell A 0 and 90 degrees, you can see a little gap when the texture loops.

_OCD triggered_
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/7a955aa4-337b-4b29-b822-1b75e99b26a2)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/915f1c50-bed8-45f1-b82b-d52d07d34d5f)

**Comment by SomeRandomNoobKekeke** [comment]
especially annoying when the color of the sprite is dark

**Comment by DuckY-Y** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/84920066/88b47040-8443-4302-b262-4410dd36233b)
I try to ignore them..... how the textures almost never line up.
![image](https://github.com/Regalis11/Barotrauma/assets/84920066/5e239c93-546e-4285-90c2-357c0582262b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a82dcc8f82435ad51fd4796cc85d72f6aa8c6b5

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4488/commits/2b575c97307f8d5c9de8d14e5e9b1142e4f17ed5

No issues found
Closing ticket
