### ISSUE TITLE
[UNSTABLE] still able to buy and fabricate storage containers

### ISSUE THREAD

**Issue by Hamburgian** [Regalis11/Barotrauma#12492]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have noticed while campaigning in the unstable version that purchasing storage containers and fabricating them is still able to happen, even though they are no longer accessible in the sub editor menu.

### Reproduction steps

1. load up camel in sub editor
2. look in the editor menu for storage containers
3. gone
4. go into test mode with a couple steel bars
5. go to fabricator and look for storage container
6. there it is

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/5c06b4f4bf11416f05c465878c391718b0c3c680 (commit in our private repo)

**Comment by AdamH-Daedalic** [comment]
Tested against release/traitor-update

Storage containers are now re-enabled in the sub editor as per the change above. Closing
