### ISSUE TITLE
Unable to place items inside linked container in editor

### ISSUE THREAD

**Issue by DuckY-Y** [Regalis11/Barotrauma#12506]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

See title and reproduction steps.

Possibly linked to #5008  

See image
![image](https://github.com/Regalis11/Barotrauma/assets/84920066/fe991ea7-43ea-480a-8274-8d4737f6e4db)
(unable to place the Carbon inside the Large Steel Cabinet linked to the Fabricator (cursor gone))

### Reproduction steps

1. open editor
2. place 2 objects down with inventories that can be linked with one another
3. select Display Side by Side When Linked on container 1 and open container 2
4. proceed to try and place items inside container 1 through container 2

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
low priority
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c9d13b07fd333a8fad48140b61c76d130d897e54

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4483/commits/c9d13b07fd333a8fad48140b61c76d130d897e54

Tried linking and unlinking cabinets and other items.
Placing items in game and in editor.

No issues found.
