### ISSUE TITLE
[Unstable] Animation jank when running past interactable items

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12504]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When interacting with cabinets and other items, the player character reaches out and "grabs" the item, some animation jank is observed. Specifically when walking away from the item, which causes a very unnatural bend in the arms.

https://github.com/Regalis11/Barotrauma/assets/37850646/5f1c80be-c346-4357-ba5c-1e2bccec67a5

**Feedback:** In my opinion this feature looks nice, (and has its uses in seeing who is looking in cabinets) but feels a little weird to play with. When out of arm's reach, the cabinet opens instantly, and the character is forcibly moved closer without input from the player. This might be something to just get used to, but especially going from the previous system, it feels odd to have the character move without being told to, and feels like they're being pulled into the cabinet, rather than walking to it. This could potentially be addressed by making the radius of interaction the same as the arms' length, though that might be even less popular.

Additionally, when interacting with items low to the ground, it forces the character into a crouch, which slows movement speed quite a bit. This can be a little annoying when running past items and checking if they're damaged enough with a screwdriver/wrench.

### Reproduction steps

1. walk past and look inside an interactable item
2. watch your arms dislocate

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### -

1.1.7.0, not 1.1.3.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
One thing is that the character helds on to the item a bit too long after you've already closed the interface, imo character should let go as soon as the interface is closed.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b7087ff085b4027a2bcb4765c9c1e375a75dceb6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
