### ISSUE TITLE
AI medics waste stabilozine on deliriumine poisoning

### ISSUE THREAD

**Issue by Hamburgian** [Regalis11/Barotrauma#12507]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

basically what the title says, ai medics give stabilozine to people with the deliriumine poisoning affliction, probably to cure the psychosis it gives, however the psychosis doesn't go away because of the deliriumine.

### Reproduction steps

1. go into sub editor
2. aquire max deliriumine poisoning through some means
3. spawn AI medic with stabilozine
4. watch as the medic slowly uses up all of your stabilozine only for it to do nothing at all.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It was not actually the psychosis they're try to treat, but the deliriumine poisoning. Stabilozine only prevents the poisoning from progressing further though, which is kind of pointless in this case. Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e0194283376c78d76f4a931f72a24b99880eb994

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
