### ISSUE TITLE
[Unstable] Only level 1 traitor events can trigger outside the campaign mode

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12509]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Only level 1 traitor events can trigger outside the campaign mode

### Reproduction steps

1. Start a sandbox/mission round with traitors enabled
2. `starttraitoreventimmediately`
3. Notice you'll always get "harmless" lvl 1 events

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ee1b24dd4ed68ae4fd9b6843a8ca8a9b0514eafb

**Comment by Jasontti** [comment]
Tested by starting many rounds.
No issues found.
Closing ticket.
