### ISSUE TITLE
Player appearance resets in multiplayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12515]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Changing player appearance before starting a round resets the changes you've made when returning back to lobby from playing a round in single mission mode

### Reproduction steps

1. Host a server
2. Change player appearance, for example picking the very last options of hair, beard and skin colors
3. Start a single mission round
4. End round once it has loaded
5. Returning back to lobby notice that your appearance has reset to how it was before you made the changes

Can also happen in campaign mode, happens when you quit the campaign. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@d4d593c.

**Comment by Rokvach** [comment]
Selecting PvP right after you have done changes to your appearance seems to reset all the changes you've made, seems to work fine in all the other game modes. Moving back to ToDo.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@484b01b.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
