### ISSUE TITLE
[QoL] Close storage container/crate inventories when dragging them out of the inventory slot + visual improvement suggestion

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12517]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to place a storage container inside a linked cabinet you either have to move the storage container UI out of the way or move the linked cabinet in order to be able to drag the storage container into the container slots. 

Additionally, could we also use the new draggable frame UI art for the container inventories? 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/2eedb891-9145-4aa5-8ba8-e5c66271c725)

### Reproduction steps

1. Load up humpback in sub test mode
2. Spawn a storage container
3. Try to place it into the fabricator cabinet by dragging
4. Notice that the container inventory gets in the way

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/aeba139838d5b8f9d57c579ea470f138bd078962 and https://github.com/Regalis11/Barotrauma-development/commit/f8d44894da4f38802749f2a785844a48d765b474

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by Rokvach** [comment]
Testesd again, working correctly. Can be merged and closed.
