### ISSUE TITLE
Diving suit tooltip renders on top of the diving suit slot in certain resolutions

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12514]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Noticed this during play testing, when I tried to drag a new oxygen tank into my suit I couldn't see the diving suit

Tested in 1440p resolution
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/ce4e5183-0c91-4a0a-84f7-0c72db956e5b)

### Reproduction steps

1. Play on 1440p+ resolution
2. Equip a diving suit
3. Hover mouse over the diving suit slot
4. Notice that the tooltip opens on top of the slot, covering it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0643ccd51cc0285358b8b845f982451adf505612

**Comment by Jasontti** [comment]
Tested with different resolutions and screen modes.
No issues found with any diving suits or exos.
Closing ticket.

**Comment by Rokvach** [comment]
Tested, still found some issues

Item tooltip going off screen
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/23b6f9f5-d8c4-4cc7-963a-37f78b3c1f61)

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/7365274e-b381-4ebf-8c36-902a760a86a4)

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/e73b559d-2297-4ca9-9cc2-549cc814bcdb)

Tooltip being displayed under health UI
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/bad46d00-a1b9-4093-9eae-6633e68ec17b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4599/commits/ab7112e09c37697929dcfef1fcd90dba4d546e74

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
