### ISSUE TITLE
Crawler nest spawned on top of a ruin

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12516]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Happened during play testing, no proper steps to repro other than just load multiple nest missions and see where the eggs are placed? 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/89a62c05-6567-46d7-96af-b1df0764061e)

### Reproduction steps

1. No proper steps other than just loading multiple nest missions and seeing if it happens

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Possibly related, but also the oxygen draining vents can be found inside ruins. It seems cave features / traps and ruins overlap, and probably in this case the cave's nest overlaps as possibly there's no code to prevent any overlaps?

**Comment by Regalis11** [comment]
No known steps to repro. I might be able to dig up the seed from the server logs on Monday though.

**Comment by Rokvach** [comment]
> but also the oxygen draining vents can be found inside ruins
IIRC this is intentional the vents either spawns the small blood sucking creatures or then the gas

**Comment by Regalis11** [comment]
Seed from the test session:

```
  Mission: Destroy a Crawler nest
  Game mode: Mission
  Submarine: Humpback
  Level seed: BWhYOit8
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/faf48b43aaa9ac256952c16c91e7871277bf5a3b

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4415/commits/9bb93cdd2370c14a53e103ccf06e14354a06b881

Played in SP mostly and generated some rounds with both missions active.
Got couple of times caves and ruins really close by, but didn't see any issues.

Closing ticket.
