### ISSUE TITLE
Modding issue: Custom abandoned outposts appear as biome gates

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [Regalis11/Barotrauma#12512]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So, as mod developer I time to time get reports when people see mod's custom abandoned outposts on biome gates. I saw that too but I not find anything in outpost config, location type and map generation xml files that defines which location type can be as biome gate and which can't.
![image](https://github.com/Regalis11/Barotrauma/assets/60311003/d39b1817-5fee-4786-8ffb-39f52d2605f8)

### Reproduction steps

1. Start any type of campaign
2. Get (un)lucky to see it

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

It seems that this feature is unfortunately hard-coded: any location type with an outpost, excluding the vanilla abandoned outpost (i.e. a location of the type "abandoned") is allowed as the biome gate, and there is no way to configure this in XML.

I added a property called AllowAsBiomeGate to locations now (commit in our private repo: https://github.com/Regalis11/Barotrauma-development/commit/107e90a60a982d34ef0a60b1755c8ae69ee1b78e). When we get that change to the public release, it should be possible to prevent this from happening by adding AllowAsBiomeGate="false" to your custom location type. Sorry for the inconvenience!

**Comment by Jasontti** [comment]
Tested.
Made "Barotrauma 40k" into a local mod and with campaign seed of "diJOSkjL" i got abandoned forge as biome gate:
![2023-09-08_09-50](https://github.com/Regalis11/Barotrauma/assets/8488224/32ba1c0c-5a06-4c64-be0d-7c2905ca31dc)

After adding AllowAsBiomeGate="false" to locationTypes.xml for the abandoned forge issue is fixed:
![2023-09-08_09-53](https://github.com/Regalis11/Barotrauma/assets/8488224/0a8c64d6-bff2-4a32-bf35-43ce969bb838)

No issues found in vanilla.
Closing ticket.
