### ISSUE TITLE
Linux: Monogame window icon displays instead of custom icon

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1251]
Couldn't find a duplicate issue. On Linux, the MonoGame default icon displays as the Window/App Icon instead of the blue Barotrauma sub-under-water icon like it does on Windows.
![2019-03-03-173938_1366x768_scrot](https://user-images.githubusercontent.com/47284081/54072822-94e93980-4245-11e9-8b33-9e71c9700c34.png)
In the picture, pay attention to the app tray at the bottom and the top left corner of the baro window.

**Comment by Regalis11** [comment]
Fixed in v0.8.9.6
