### ISSUE TITLE
[Unstable] Loader visual issues

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12520]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

- Loader lights are shadow casting

- Loader lights shine through items. 
All light components do this but the floor can be a little crowded around loaders with empty boxes being dropped so it's more noticeable
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ff131d21-14a8-4220-94e6-496d1a2bb29d)

- Some signals break visuals
I wired a lever for continuous fire to the flak and it broke the lights and animation. Periscope works fine.

https://github.com/Regalis11/Barotrauma/assets/73229309/d29da0bc-0a3a-4658-a79c-d62f8b4fe8fe

- Flak loader?
I assume it's not finished, the back panel is vibrating really fast not sure what the animation is supposed to be

- Railgun loaders missing one shell
Vanilla submarines are still loaded with 5 shells, not a big deal since autofill will fill the 6th shell

### Version

Unstable (v1.1.3.0)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7f38ae0720a0c44b6246d69ce7d63eefd63fc0f1

**Comment by Jasontti** [comment]
Tested

Status lights shine trough objects.
No other issues found.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/7dec72b0-b4f8-46fc-9056-d29f1239d1c1)

**Comment by Regalis11** [comment]
Ah, yeah, I didn't actually do anything about that, forgot to mention it in the comment/PR. That's an issue that applies to all lights and items. Addressing it would be quite complex, and I think it's outside the scope of this ticket.
