### ISSUE TITLE
[Unstable] Issue with turrets

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12528]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Turrets except railgun consumes ammo 2 times as fast as before.
Double Coilgun fires projectiles in a pattern of "1-2-1".

### Reproduction steps

1. quick start with orca 2
2. fire turrets

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Happens in sub-editor, not sure in multiplayer.

### Version

Unstable (v1.1.8.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f38ae0720a0c44b6246d69ce7d63eefd63fc0f1

**Comment by Jasontti** [comment]
Tested.
No issues found with different configurations and turrets.
Closing ticket.
