### ISSUE TITLE
Mudraptor genes damage reduction doesn't work

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12525]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

See https://github.com/Regalis11/Barotrauma/pull/12483

Mudraptor genes supposedly reduce damage, but the collider of the beak limb is smaller than the collider of the human head. The head gets hit instead of the beak.

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/66bfade1-1681-4c7b-9d01-a42b533f4ce3)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/04df9ce5-307a-4ddd-a59a-7f274a126830)

### Version

v1.0.21.0

**Comment by Hamburgian** [comment]
question, would the extra "limb" from the mudraptor genes make you take more damage if somebody were to fire an armor piercing round of their choice into your skull?

**Comment by Regalis11** [comment]
> Mudraptor genes supposedly reduce damage

Do they? I don't see anything about this in the description.

**Comment by ubertpendragon** [comment]
It doesnt say it, but it's in the xml

**Comment by Vykn** [comment]
Isn't this just the same as the husk appendage? It has limb resistance just so it's not a liability.

**Comment by Regalis11** [comment]
> Isn't this just the same as the husk appendage? It has limb resistance just so it's not a liability.

I am not entirely sure, but I would suspect that's the case.
