### ISSUE TITLE
Double trashcan 'encounters' causes lockup

### ISSUE THREAD

**Issue by xiddin** [Regalis11/Barotrauma#12527]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have two of those trashcan encounters going on at the same time (bomb and unknown liquids, respectively). As can be seen from the ss, both show up in the dialogue options with the latter one grey'ed out. Clicking "investigate" on the bomb locks the dialogue box, stopping any progress. The game is still "running" kind of, as I can issue commands to bots, see the "break news" thingy flicker. I just can't move or change character and have to retry. Playing around with it, I can get it to happen again sometimes depending on eventspawns. If I click "not my problem", I can then access the 2nd event with the liquids, which now works as intended. Furthermore, after doing some shopping etc, I came back to a firefilled corridor and dead Marc Green, which I presume means that the bomb went off as intended as well.

![Screenshot_2023-08-19_12-22-50](https://github.com/Regalis11/Barotrauma/assets/142663735/063dc08d-e585-402f-ac64-dcd7cfbe0004)

### Reproduction steps

1. Get into Huro Biomed Rnd
2. Hope for "!" on trashcan
3. If one encounter is present, the 2nd one is also there and will lockup

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/58882e7081f18a71200cf533de8591baa33681de (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
Events trigger now one after another from the same trash can, when triggered manually.
Both events can be completed, no matter wich one is triggered first.
Closing ticket.
