### ISSUE TITLE
Make Every Player Per Multiplayer Campaign Unable to Change Job- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1252]
The reason is simple: They would keep respawning with new inventory upon changing their job spamming someone's gear for free. Also makes the game stricter.

**Comment by Regalis11** [comment]
This is pretty much how it works in the dev version. You are locked to one job and character until that character dies (or until you decide to drop that character and generate a new one).

**Comment by rico6822** [comment]
> This is pretty much how it works in the dev version. You are locked to one job and character until that character dies (or until you decide to drop that character and generate a new one).

Oh ok.
