### ISSUE TITLE
random toolbelt appearing in berilia

### ISSUE THREAD

**Issue by Hamburgian** [Regalis11/Barotrauma#12526]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

in the berilia, there is a random toolbelt in the middle section of the bilge. I don't think this does much at all, but I figured I'd report it since nobody else has noticed it.
the toolbelt contains a welding torch with fuel, a wrench, and a screwdriver.

### Reproduction steps

1. go into sub editor
2. select berilia
3. observer middle section of the bilge
4. ooh
5. toolbelt
6. that shouldn't be there

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

sub-editor

### Version

Unstable (v1.1.3.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against Feature/berilia-refresh commit https://github.com/Regalis11/Barotrauma-development/commit/3f4f5185500dd35256e26d881372b93e05520125, No issues found.

Notes: Both checked the area it should spawn and the item finder, and couldn't find a toolbelt on the berilia refresh during my first look for the berilia refresh ticket.
