### ISSUE TITLE
[Modding] AllowSelectingWhenSelectedByBot doesn't do anything

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#12537]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

title, AllowSelectingWhenSelectedByOther seems to not do anything either.

### Reproduction steps

Add AllowSelectingWhenSelectedByBot="false" to a chair item
Sit in the chair with a bot
Try using the chair as a player
-> you can still kick the bot out of the chair, whether the setting is true or false

### Bug prevalence

Just once

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.8.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. Interacting with the chair seems to do nothing:

https://github.com/Regalis11/Barotrauma/assets/14351070/da0d227e-3df4-4228-9398-268514ddcbc6

Here's the modified item I used:
```
  <Item name="" identifier="op_cafeteriachair" width="152" height="240" scale="0.5" noninteractable="false" category="Decorative" canflipy="false">
    <sprite texture="Content/Map/Outposts/Art/CafeteriaGardenAssets.png" sourcerect="197,778,152,240" depth="0.97" premultiplyalpha="false" origin="0.5,0.5" />
    <Controller UserPos="10,30" direction="Right" hidehud="false" canbeselected="true" issecondaryitem="true" drawuserbehind="true" AllowSelectingWhenSelectedByBot="false">
      <limbposition limb="Head" position="45,40" />
      <limbposition limb="Torso" position="50,-30" />
      <limbposition limb="Waist" position="50,-80" />
      <limbposition limb="RightLeg" position="165,-140" />
      <limbposition limb="LeftLeg" position="165,-140" />
      <limbposition limb="RightHand" position="120,-80" allowusinglimb="true" />
      <limbposition limb="LeftHand" position="120,-80" allowusinglimb="true" />
    </Controller>
  </Item>
```

I wonder if there could be something wrong with the way you've configured the chair? Did you add `AllowSelectingWhenSelectedByBot` to the `Controller` element, or the `Item` element? It should be the former, because it's a property of the `Controller` specifically.

**Comment by Udrakan** [comment]
You've hit the nail on the head! Sorry for wasting your time. Closing.
