### ISSUE TITLE
[Feature Request & Bug] "X" buttons on menu tabs, more lower resolution compatibility

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1253]
This game scales extremely well. I'm surprised there's support for some of the resolution it offers.
But some things are still broken, mostly buttons that are offscreen.
This could be fixed in the main menu revamp, but some parts of the game are impossible to navigate one the lowest resolution. Some menus are un-exitable since buttons to close dialogue tabs are outside of menus (like on the main menu).
![2019-03-09-115615_1366x768_scrot](https://user-images.githubusercontent.com/47284081/54075247-b73d8000-4262-11e9-9a44-4b8430b2ab20.png)
In other areas, text is understandably cutoff. This could be fixed with an extremely low res font for lower resolutions.
![2019-03-09-115715_1366x768_scrot](https://user-images.githubusercontent.com/47284081/54075260-e3f19780-4262-11e9-8fbb-b3139cdd219d.png)
Finally, the videos in even the not-so-low resolutions don't properly scale, sometimes partially cutting off "continue" buttons.
![2019-03-09-115729_1366x768_scrot](https://user-images.githubusercontent.com/47284081/54075272-01befc80-4263-11e9-925e-a0d5874eacb9.png)

**Comment by EdusFF** [comment]
Fixed tutorial element (Image 2, ca08b80) & video player (Image 3, 6f919a4) scaling issues on lower resolutions.

**Comment by hubismal** [comment]
Nobody is going to be playing this on their raspberry pi as the game requirements pretty much require you have a powerful enough computer that's using something with a greater resolution than the ridiculously small ones.
Not to mention resolution scaling is pretty much perfect by now. Closing.
