### ISSUE TITLE
Invisible walls all over level

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#12535]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There are tons of invisible walls in each biome what blocks at least lasers, maybe also bullets
I found a way to see them, behold, absolute unit of testing:
![lts](https://github.com/Regalis11/Barotrauma/assets/122838333/185d43a5-ffd0-438b-bd50-3f8a434282bf)
[link to workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=3023426493) do whatever you want with sub, I don't care
![20230821043036_1](https://github.com/Regalis11/Barotrauma/assets/122838333/224d046d-5bba-4512-86ef-bd5c569d1d23)
some videos:
[test1](https://www.youtube.com/watch?v=RDpPBBQhmPQ)
[test2](https://www.youtube.com/watch?v=2YgQjY8Akz4)
[test3](https://www.youtube.com/watch?v=PdJd4UjGSqw)
[test4](https://www.youtube.com/watch?v=c6S4uXI144c)
excuse me for quality

### Reproduction steps

1. subscribe to the sub
2. quickstart "laser test sub"
3. enablecheats
4. debugai
5. freecam
6. bindkey "some key" teleportsub 

teleport sub around the map and watch

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b6418e03493286364e876d3615b5f0a0e590e023 (commit in our private repo).

**Comment by Jasontti** [comment]
Tested.
What an amazingly terrifying test sub!

No problems with invisible walls found.

In instances when laser doesn't find valid target at the end point, it will terminate laser early and won't "travel" to infinity. Most notable in sub editor, but really rare to have so long corridors in normal game play and doesn't affect it in anyway (Termination point is way beyond radar and sight range), if there is a target beyond this termination point, laser will behave normally

Closing ticket.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/eca3525d-20a7-4f06-99db-449764e6320c)

**Comment by SomeRandomNoobKekeke** [comment]
No, it's not that
![20230831115808_1](https://github.com/Regalis11/Barotrauma/assets/122838333/07ca16e4-3b8b-4f4d-b6fe-7b9bdacade2a)
![20230831115845_1](https://github.com/Regalis11/Barotrauma/assets/122838333/91628e39-9fb8-4010-a2ac-df6deecebecd)
Way beyond radar and sight range? Or not a valid target

**Comment by Jasontti** [comment]
This is testing the fix.
you can just see it with maximum view distance in freecam, wich is about 150m according to my testing.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/a931b54e-a577-401a-9987-14d01f8703f3)

**Comment by SomeRandomNoobKekeke** [comment]
ok, cool
