### ISSUE TITLE
The direction of the target force of the Projectile Attack is not the direction of motion of the Projectile

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12530]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Sometimes when a projectile hits a character at high speed, the character is pushed in the opposite direction of the projectile.
![2023-08-20 09-35-38 00_00_42-00_00_44 00_00_00-00_00_30](https://github.com/Regalis11/Barotrauma/assets/73634685/16eab6f6-8599-44bb-98af-cf279b4beea5)

### Reproduction steps

1. Multiply the spear's launchimpulse by 10
2. launch spear and hit a character
2. sometimes character is not being pushed by target force toward expected direction

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2d03fb328191cbabdae238d488e5e468ef2c6895

> Fixes to projectiles applying impulses in an incorrect direction. The impulse was always applied in the direction from the projectile to the limb it hits, which may not always be appropriate: a fast-moving projectile can have gone "past" the character when the hit registers, or it may have for example hit the limb at the very bottom, causing the impulse to be applied upwards. 

> Now we instead apply the impulse in the direction the source of the attack (e.g. projectile) is travelling, or if it's not moving, the direction it points towards. Fixes https://github.com/Regalis11/Barotrauma/issues/12438, https://github.com/Regalis11/Barotrauma/issues/12530, https://github.com/Regalis11/Barotrauma/issues/12531

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
