### ISSUE TITLE
[Unstable] Gunners 100 weapon skill completely miss a target under perfect conditions

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#12539]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Gunners seem to have lost the ability to lead their shots or it's not working properly, which resulted in a frustrating event in SP where I observed them shooting (I used Orca searchlight). I went ahead and tested it in sub editor with Orca and Typhon 2. Vids:

https://github.com/Regalis11/Barotrauma/assets/59519434/ef5b34d3-f522-48a6-b876-2513555492b2

https://github.com/Regalis11/Barotrauma/assets/59519434/bdb00cef-0760-4c8f-b079-6346e3de2935

This does not feel good or intentional. Should an elite coalition/separatist hiree miss every shot on a double coilgun + upgraded turret against a crawler? Every single shot until it reaches the sub?

### Reproduction steps

1. have 100 gunner man a gun
2. turn on sonar
3. spawn a crawler close beyond max range
4. observe

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.8.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Checked against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/bfc61bdccee7567cee8afe3a0a471d562c2d1196

Easy to repro, Appears there is no code in the turret component for tracking ahead of a moving target, only aiming at the position of the closest limb.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/20fdb19e7a318eb6472f683e9d143fdf14a0798a
