### ISSUE TITLE
Hit-Scan Projectile's force is always to the right after hitting a character 

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12531]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Projectile is spawned in the same way as FlakBolt Sharpnel, but it is Hit-Scan.
In this case, projectile will always pushes the hitted character to right.
![格式工厂混流 2023-08-20 09-43-55+2023-08-20 09-44-22+2023-08-20 09-44-37~1 00_00_00-00_00_30](https://github.com/Regalis11/Barotrauma/assets/73634685/5664f18f-b1cc-419c-ab4d-0cb2df945466)

My xml:
```xml
<Item identifier="otfx_flintlockbullet" category="Weapon" tags="" hideinmenus="true">
    <InventoryIcon texture="%ModDir%/OTFX/Items/Weapons/ammo.png" sourcerect="192,384,64,64" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="0,0,2,2" depth="0.55" origin="0.5,0.5" />
    <Body width="10" height="10" density="30" />
    <Projectile characterusable="false" launchimpulse="infinity">
      <StatusEffect type="OnNotContained" target="This" delay="3.0" stackable="false">
        <Remove />
      </StatusEffect>
      <StatusEffect type="OnUse" target="This" delay="0" hiddeningame="true">
        <SpawnItem identifier="otfx_flintlockbulletprojectile" spawnposition="This" count="1" aimspread="0" rotationtype="Collider" rotation="0" />
      </StatusEffect>
    </Projectile>
  </Item>
  <Item identifier="otfx_flintlockbulletprojectile" category="Weapon" tags="" noninteractable="false" hideinmenus="true">
    <InventoryIcon texture="%ModDir%/OTFX/Items/Weapons/ammo.png" sourcerect="192,384,64,64" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="0,0,2,2" depth="0.55" origin="0.5,0.5" />
    <Body width="10" height="10" density="30" />
    <Projectile characterusable="false" hitscan="true" removeonhit="true">
      <Attack structuredamage="45" targetforce="40" itemdamage="45" severlimbsprobability="0.9" penetration="0.55">
        <Affliction identifier="gunshotwound" strength="92" />
        <Affliction identifier="bleeding" strength="55" />
        <Affliction identifier="bloodloss" strength="5" />
        <Affliction identifier="stun" strength="1.5" />
      </Attack>
      <StatusEffect type="OnImpact" target="UseTarget" duration="1.5" setvalue="true">
        <Affliction identifier="otfx_hindered" strength="200" />
        <Conditional entitytype="Character" />
      </StatusEffect>
      <StatusEffect type="OnImpact" target="UseTarget">
        <ParticleEmitter particle="impactfirearm" particleamount="10" scalemin="1.4" scalemax="2.8" velocitymin="0" scalemultiplier="0.65,0.65" colormultiplier="255,200,200,80" />
      </StatusEffect>
      <StatusEffect type="OnImpact" target="UseTarget">
        <Conditional entitytype="eq Structure" />
        <Conditional hastag="eq door" />
        <ParticleEmitter particle="spark" copyentityangle="true" anglemin="-10" anglemax="10" particleamount="5" velocitymin="-10" velocitymax="-200" scalemin="0.5" scalemax="1" />
      </StatusEffect>
      <StatusEffect type="OnNotContained" target="This">
        <Remove />
      </StatusEffect>
    </Projectile>
  </Item>
```

1. The ranged weapon luanches a `otfx_flintlockbullet`, the `otfx_flintlockbullet` will spawns a `otfx_flintlockbulletprojectile`.
2. But the `otfx_flintlockbulletprojectile` does not push the hitted character in the direction its motion

### Reproduction steps

Sorry for that I may not have much time to make a Demo specifically to reproduce the problem:
1. Subscribe mod [OTFX](https://steamcommunity.com/sharedfiles/filedetails/?id=2986787106) or Download 
[OTFX.zip ModVersion:1.1.9](https://github.com/Regalis11/Barotrauma/files/12387489/OTFX.zip)
2. spawnitem otfx_flintlockrifle inventory
3. spawnitem otfx_flintlockramrod inventory
4. spawnitem otfx_flintlockammo inventory
5. Put ammo and rifle in ramrod
6. Long press the ramrod to reload the rifle
7. Equip the rifle and double click right mouse button to cock the hammer
8. Shoot at a character from any direction and he will be pushed to right by hit-scan projectile

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Other

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
