### ISSUE TITLE
Spineling spikes transfer damage to the head instead of torso

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12547]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When Huskappendage limbs take damage, they always transfer it to the head

It makes sense in the case of husk/mudraptor genes, but not for spineling spikes.

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/e46ed4e0-ce63-433f-b1ff-6f4ad12f6cd8)

Part of the issues in #12383

### Reproduction steps

Swing any weapon at the tip of the spike

Burn a spineling person with steam canon 

Damage goes on head

### Version

v1.0.21.0

**Comment by ubertpendragon** [comment]
nvm you can change healthindex to 1 

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6b315a60-b944-4d74-b0a2-6435e31a207d)

It turns out it was editable after all

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f0aa08363785132c8b0acbf140bf07dd30c977a0

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/ad8a00975de30dcd281146ac3b1684e0272bc421

Spines don't take damage anymore with the changes in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/bab4794c1d288b97d0962737e73e045c79fed643

This might cause issue that human characters are not damaged from spikes from genes.

https://github.com/Regalis11/Barotrauma/assets/8488224/4cc610cf-7f61-447b-b741-881f9e66c86e

No other issues found

**Comment by Regalis11** [comment]
@Jasontti The spikes were intentionally made invulnerable to damage after this ticket was made (see https://github.com/Regalis11/Barotrauma/issues/12550). So testing this now removing the damage modifiers from the spikes.

**Comment by Jasontti** [comment]
Is it then intentional that human characters are not damaged by other human launching spikes anymore?

**Comment by Jasontti** [comment]
Retested

Spineling spikes don't damage humans
Damage is still applied to structures and enemies
Friendly fire was not enabled, could damage with revolver
