### ISSUE TITLE
Ignorecollisions="true" prevents limbs from being hidden

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12548]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ignorecollisions="true" prevents limbs from being hidden via statuseffects 

Currently Ignorecollisions="true" is the only way to make a limb not be hit by projectiles and melee attacks. 
This is useful for preventing limbs for adding an additional hitbox, like spineling spines added from genes.

### Reproduction steps

1. Change `ignorecollisions="False"` to True in spinelingspine.xml 
2. Shoot 
3. Spikes don't disappear

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c3c6e68172851a052c73d2006fa6eab5e25af4f

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/ad8a00975de30dcd281146ac3b1684e0272bc421

Used steps above

No issues found
Closing ticket
