### ISSUE TITLE
Weird C-4 blocks that don't stack with other C-4 blocks

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12543]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

These C-4 blocks appeared randomly in the Humpback armory when testing in the editor.
They don't have a description and they don't stack with the other pair of C-4 blocks which do have a description.

![c-4](https://github.com/Regalis11/Barotrauma/assets/68995233/a92bfb6c-7c79-4071-9f4f-a078b2fff867)

### Reproduction steps

Editor, humpback, test.

If you spot the C-4 block with no description you can spawn the regular ones with the `spawnitem "C-4 Block` command.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.8.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by AdamH-Daedalic** [comment]
Tested against fix/traitor-fixes-august3

Not seeing any of these special traitor variant C-4 Blocks spawning in any vanilla subs when testing in the editor or in singleplayer.

Closing
