### ISSUE TITLE
[Dev Version] Grabbing monsters

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1254]
So I thought of some little thing and feature that could be quite helpful. So when crawlers break into your sub or the raptors, you usually kill them right? Well when they're dead they become an obstructing useless ragdoll. I suggest two things. First, we should be able to grab and drag the monsters, so they won't obstruct the view, just like we already can with humans. The second thing would be some way to utilize the corpse or a thing like that. My idea is, since there's a "launch decoy" button near the navigation terminal, maybe we could load a corpse of a monster (or even a human corpse) into the decoy to make it viable, just some food for thought. This idea is basic, so let's see what you all have to say in the comments below!

**Comment by hubismal** [comment]
A way to rid the waters of larger corpses would also be nice too. It's really a pain in the behind to get rid of huge heavy moloch corpses that usually fall on your ship or obstruct a small passageway.

**Comment by AbominationBanisher** [comment]
Hubismal, maybe the larger corpses could be removed via the railgun? Just shoot the corpses until the gib, think that'd be a neato feature.

**Comment by Waagher** [comment]
Another way to make dealing with bodies easier could be to allow cutting them apart with plasma cutters or knives and then move the body parts out of the way. Though having a lot of gibs on the screen could negatively affect performance, so, perhaps, some parts could just disappear, when cut off? I think that's how dismemberment works already.

**Comment by AbominationBanisher** [comment]
Parts disappearing is dumb, but I don't think it'll be too bad in terms of performance, albeit I recommend skipping the entire cutting apart process and just lugging the entire monster as it is. Although it could give the diving knives an actual purpose (currently they suck more than plasma cutters in terms of murdering things), so I really don't know at this point.

**Comment by LightningBloom** [comment]
> just some food for thought
hehehehehe

Would be nice though, to expand the grab keybind on G to work for all ragdolls/more physics objects.

**Comment by Regalis11** [comment]
I agree that there needs to be more way to get rid of corpses, and using them as ammunition would be a really fun way to do that. I think this issue can be closed though: grabbing monsters is already implemented and we already have a feature request about using bodies as ammo (#753).
