### ISSUE TITLE
You can noclip through colliders when leaving a bed/chair in a specific way

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12542]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/assets/7299826/4fa42d7e-5e8c-43a2-b817-54ab70d402cb

### Reproduction steps

1. Load up Typhon in sub test mode and navigate into the prison
2. Sleep on the bed
3. Click on bed to leave it
4. Walk towards door and press crouch
5. Notice that your character noclips through the door

Doesn't happen if you right click or ragdoll to leave the bed/chair, only when you select the item. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.8.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8ee9e96406c7dc67f7e4ba256cfa564f8be354e3. This was a weird one. :D

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
