### ISSUE TITLE
[Unstable] Event editor lines look broken, but they work

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#12544]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/59519434/37c5b04b-cfc7-4efb-bdfb-20b5df867409)

### Reproduction steps

eventeditor in console
connect any two nodes

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.8.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4343/commits/d38ee3f97fdf6de9c4cb5424ba44a717f5aa1b46

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
