### ISSUE TITLE
Husk eggs take damage from explosions, can't be used for crafting

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12556]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Husk eggs take (very little?) damage from explosions and can't be used for crafting.
Even a mini nuke only does 5% damage to eggs

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/a4976ae1-2dc8-48a7-92d7-5dae7520a49d)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/d7fa6021-a2c7-46e3-b758-a81c710a132e)

Weirdly enough they don't have `damagedbyexplosions="true"` 

Disable explosion damage?
Set them at 1 hp?
Hide condition bar and change recipe to use any min condition?

      <RequiredItem identifier="huskeggsbasic" mincondition="0.0" usecondition="false"/>

### Reproduction steps

Use explosives near eggs.

### Version

Unstable

**Comment by abemaden** [comment]
I believe you can combine the eggs, so if you have one at 99 and another at 97, you can combine them so one has 100 and the other has 96. This should help you while it's being looked into.

**Comment by Regalis11** [comment]
This seems to be essentially the same issue as https://github.com/Regalis11/Barotrauma/issues/12557: the explosions trigger the OnFire effects of the eggs, which reduces their condition. To me this does not seem necessary to address: it makes sense that explosions damage the eggs.

**Comment by ubertpendragon** [comment]
The issue was that those 95% eggs cant be used for the one thing they are supposed to be used for: crafting
