### ISSUE TITLE
[unstable] endoutpostmid crashes the game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12551]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Loading endoutpostmid  (the second end level) crashes the game, both in campaign and leveleditor

[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/12433210/crashreport.9.log)

[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/12433211/crashreport.10.log)

### Version

v1.1.8.0  (unstable)

**Comment by Regalis11** [comment]
Could not reproduce. Steps to repro pls?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/edd44ede0dbf1add7d24d17cbc72349820a3cf2b

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
