### ISSUE TITLE
Item stack turns intangible after pet eats from it

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12558]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you drop a stack of food on the ground and pet finishes eating it, stacks sprite drops trough the floor and rest of the stack turns invisible and uniteractable.
Bots can still clean them up.

Happens in SP, MP and sub editor.
Tested in traitor-update branch

### Reproduction steps

1. Drop a stack of food from inventory. Any food seems to work.
2. Let pet eat it fully. Tested with Orange boy
3. Sprite drops and stack turns intangible
4. Issue cleaning command to bots and watch them conjure items from thin air

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

1.1.2.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
No errors
```

**Comment by Regalis11** [comment]
Most likely the same issue that Rokvach reported here https://github.com/Regalis11/Barotrauma/issues/12414#issuecomment-1691405608, should be fixed in https://github.com/Regalis11/Barotrauma-development/pull/4424. Moving to QA
