### ISSUE TITLE
huskappendage limbs are extra vulnerable to Explosion/Repairtool damage

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12550]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Explosion damage is divided across all limbs, so that it remains consistent no matter the amount of limbs.

However, limbs added via huskappendage (spineling spine, mudraptor beak, husk tentacles) seem to take damage on top of the human limbs.

_Normal human has most health followed by spineling followed by husk+spineling_

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/7e6f6d61-2a7e-4754-81ba-ef276f2808dd)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/fdc542ee-7058-4163-80c8-54c11d573b57)

Repair tools also seem to have the same issue, steam cannon used against normal human vs spineling genes

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/3ce0931b-fc58-4bc5-898b-5700ab47d246)

Those limbs also don't benefit from wearable modifiers which makes them extra vulnerable

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/31957ddb-ca6e-4bf5-8494-2f924185b322)

Huskappendage limbs in general should not take damage (damagemodifiers to 0) nor interact with melee/projectiles (ignorecollisions="true") to prevent turning those limbs into armor.

### Reproduction steps

1. Stack humans on the same spot
2. `giveaffliction "Spineling Genes" 100` to one of them
3. Type in console `explosion 1000 0 10`
4. Compare health on Head limb (where spineling damage goes) 
5. Do the same with steam canon

### Version

v1.0.21.0

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/ad8a00975de30dcd281146ac3b1684e0272bc421

With spineling spikes modified, stinger and beak doesn't seem to take abnormal amounts of damage

No issues found
Closing ticket
