### ISSUE TITLE
Explosions trigger "OnFire" statuseffects

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12557]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Explosions trigger "OnFire" statuseffects once. 

Here with pomegrenade, a single explosion would bring the item's condition to 50%

`<StatusEffect type="OnFire" target="This" Condition="-50.0" />`

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/c3bf7c24-5ed6-4879-8b30-a095fd6a8f01)

Related #12556

### Reproduction steps

1. Spawn items that take damage "OnFire" (husk eggs, oxygen tanks, fruits)
2. Shoot a mini-nuke
3. Observe condition going down

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.9.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional: explosions that create flames cause OnFire effects to trigger.
