### ISSUE TITLE
Turrets connected with multiple loaders will consume extra ammo

### ISSUE THREAD

**Issue by DarkWimd** [Regalis11/Barotrauma#12567]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If 3(or more) turrets connect to multiple same loaders, they consume extra ammos from other loaders per shot.

In submarine editor, I was trying to make a row of turret(Pulse laser) to fire at the same time, and I connected each turrets with every loader(1st turret connect with 5 loaders, 2nd turret connect with the same 5 loaders, etc. ) with the same number of turrets and loaders, they should fire about 56 secs before run out of ammo, but they only used 29 secs to fire all of them. This can be avoided by separating the loaders and the turrets.

I have only tested it with Pulse Lasers, not sure how it works with other turrets.

This could be the problem of my computer, and it can be avoided by designing. It's not a big problem, but a problem is a problem.

### Reproduction steps

1.Open submarine editor.
2.Create or open a submarine that functions normally (to test the submarine).
3.Place 3 pulse laser turrets, and place 3 pulse laser loaders filled with fuel boxes.
4.Link each turrets with every loaders. Should be 9 connections in this case.
5.Wire the turrets to let them function.
6.Test the submarine and fire the turrets at the same time until run out of ammo. No need to be the same trigger.
7.Each fuel box contains 45 shots, by default each turret fire 48 shots per minute, should take about 56 seconds. But in game, it only takes about 29 or 24 seconds, same amount of 6 or 7 turrets. The more turrets, the more it consumes.
8.This happens in submarine editor, campaign mode and multiplayer sand box mode. Haven't test it with other players yet.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested.
There something wrong with consumption of ammo.
One shot of pulselaser uses 2,25 durability from ammo box, so ~45 shots per box.
One shot takes ~1s, so in general you get less shots even with single turret and loader.
3 turret and 3 loaders setup is not consistent. 2 lasers seemed to fire simultaneously and 1 would get out of sync easily.

Shooting run times:
1 turret, 1 loader: 29s
2 turrets, 1 loader: 15s
2 turrets, 2 loaders: 29s
3 turrets, 3 loaders: 19s

**Comment by Jasontti** [comment]
https://github.com/Regalis11/Barotrauma/issues/12528 Related.
Tested and 1 turret, 1 loader and 3 turrets, 3 loaders have same run time of 56s in fixed branch.
