### ISSUE TITLE
One strange egg spawns multiple pets

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#12563]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

It is caused by performancefix
One strange egg spawns multiple pets, or rather SpawnCharacter speciesname="something" will spawn multiple creatures

### Reproduction steps

1. install lua for barotrauma
2. enable performancefix
3. change config of performancefix (for example 50 7 7 7 7 7) and save config
4. put saline into strange egg
5. multiple pets are spawned if not try again

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is most likely an issue with the performance fix mod - as far as I know, it modifies the rate at which status effects are executed, which could cause issues like this. That's essentially the reason why we haven't used a similar approach for optimizing the vanilla game: there's a lot of logic in the items that has been designed to run every frame, and modifying that can lead to unexpected consequences.
