### ISSUE TITLE
Different subcontainers that has the same containable item restriction share "itempos"

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12574]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm trying to create an item that can have 2 batteries attached and the batteries are drawn when installed. But they share the first item pos resulting in 2 batteries overlapping. The second itempos is ignored.
```
      <SubContainer capacity="1" maxstacksize="1">
        <Containable items="mobilebattery" hide="false" itempos="25,0" setactive="true" />
      </SubContainer>
      <SubContainer capacity="1" maxstacksize="1">
        <Containable items="mobilebattery" hide="false" itempos="-25,0" setactive="true" />
      </SubContainer>
```

### Reproduction steps

1. try mod a welding tool that can have 2 tanks installed and make sure the 2 slots have different itempos
2. observe items in 2 slots share itempos

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.9.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by bobingabout** [comment]
I've been trying to do something like this. 2 subcontainers with different item positions.
The issue still persists in the current public unstable release.

**Comment by Regalis11** [comment]
@bobingabout The fix hasn't made it to the unstable version yet I'm afraid. Sorry for the inconvenience!
