### ISSUE TITLE
Very long stuns from creature attacks after swinging melee weapons

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12577]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Some creatures can inflict very long stuns after attacking.

Crawler has 3 attacks, 2 of those underwater.

The stun value of those two underwater attacks is rather small:

<Affliction identifier="stun" strength="0.1" probability="0.5" />
<Affliction identifier="stun" strength="0.25" probability="1" />

Yet it's not uncommon for a single crawler to stun for several seconds after an attack.
You can clearly see it on the video; **this seems to happen a lot more when using melee weapons**

_Swinging modified wrenches that don't deal damage to not interrupt the crawler:_

https://github.com/Regalis11/Barotrauma/assets/73229309/336ff537-ce5f-4f3d-92e0-de2e370bef4c

This seems very consistent in testing

### Reproduction steps

1. Spawn a bunch of crawlers in water
2. Do nothing
3. Get attacked a lot, no long stun
4. Pull out a melee weapon (easier if you remove the damage from xml entirely)
5. Start attacking
6. Get stunned for a very long time

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.9.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/023a5dc9d381fb363b743688f22ad30ed96b3f46

**Comment by Jasontti** [comment]
Tested.
Fought against multiple enemies unarmed and with melee weapon.
No issues found.
Closing ticket.
