### ISSUE TITLE
Ruin generation (wall between ruin modules, no path from module to another)

### ISSUE THREAD

**Issue by DominO570** [Regalis11/Barotrauma#12570]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The rather strange generation of the ruins makes the entrance module to them blocked. This is not a big problem, but remembering the breakdowns of old ruins before version 0.15, I would not want to layer ruin modules on top of each other.

### Reproduction steps

1. Started the round.
2. I swam to the ruins.
3. While examining them, I noticed the absence of a module with an open wall for passage.
4.I explored the ruins on the mission and found it, in front of it was another module blocking the passage.
![image](https://github.com/Regalis11/Barotrauma/assets/64869248/1460d369-4026-46c6-9028-29a11478e944)
Most likely I was not lucky with the seed. But it seems to me that this is a layering error.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
It's intentional that some ruins later in the game don't have the entrance module, meaning you _might_ need to break the walls to get inside. That shouldn't be too common though. So without knowing the difficulty level (or the point in the campaign), it's difficult to say if this is a bug or not.

**Comment by Regalis11** [comment]
@itchyOwl this seems to be from the stable version of the game, in which the ruins should always have an entrance module. I'm not sure I understand the issue though, there does seem to be an entrance here:
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/4d975193-b2d9-45fb-bf5e-188ee9f0bc8a)

**Comment by DominO570** [comment]
this is a hole from the cutter, the problem is that the module with the missing wall, which is a horizontal passage, is missing due to generation error and layering 2 modules due to different sizes, which could not be taken into account.

**Comment by DominO570** [comment]
I made this hole with a cutter

> @itchyOwl this seems to be from the stable version of the game, in which the ruins should always have an entrance module. I'm not sure I understand the issue though, there does seem to be an entrance here: ![image](https://user-images.githubusercontent.com/14351070/263621586-4d975193-b2d9-45fb-bf5e-188ee9f0bc8a.png)

**Comment by DominO570** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/64869248/fd3e12a7-0569-4b3d-b4bc-35ee3162f2d5)
the problem is that the layers scare me, given the lack of mods and the stable version.

**Comment by Regalis11** [comment]
No known steps to repro, closing
