### ISSUE TITLE
All of the host server playstyle banners have a 1 pixel bleed

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12579]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/51845968-2372-47a6-8eca-6db6c50aece8)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/922d056f-7709-46b0-9a95-dd700bb5eb27)

### Reproduction steps

Check host server menu

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

Unstable (v1.1.9.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/03c2cf6fd72f05cb564e715e7dd7a8f05f8db30c

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/ad8a00975de30dcd281146ac3b1684e0272bc421

Looked at host server and server browser banners

No issues found
Closing ticket
