### ISSUE TITLE
Recycler- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1258]
Recycler is a specific fabricator capable of turning any item put inside of it into items requiring same resources to craft it.

Input slots: 1

Output slots: 5

Upon putting an item into recycler screen will display all possible items it can be exchanged into. The time required to do so will always be half as short as time required to create it in normal fabricator. Turning wires into wires of other colors will take 2,5 second while turning components into other components will take 5 seconds.

If an item in recycler requires certain skills to create it they will always be lowered by 10 points and won't go below 0 but I'm not sure if it wouldn't make recycler too useful.

The main purpose of recycler is to implement a device making turning one item into another less annoying and taking shorter time. If it is not going to be used on vanilla submarines I'm pretty sure creators of custom submarines would use them in their vanilla submarines.

Lastly recycler consumes 800 power by default. 60% more than regular fabricator.

**Comment by VelonacepsCalyxEggs** [comment]
Deconstructor is  already in game xd

**Comment by AbominationBanisher** [comment]
Basically what the husk guy said. I dislike your idea, it seems pretty useless atm.

**Comment by Regalis11** [comment]
Yeah, I don't think this is necessary. Even if it was slightly faster/better than using a deconstructor and fabricator, adding a completely new device just to get rid of that extra deconstruction step seems overkill.
