### ISSUE TITLE
Storing the Сargo Scooter in the character's inventory

### ISSUE THREAD

**Issue by 0n1ime** [Regalis11/Barotrauma#12589]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I don't know is this a new feature or a bug, I haven't seen this in the changelogs, but now it is possible to store the Cargo Scooter in the character's inventory in Unstable 1.1.10.0. This can be used to significantly increase of the character's inventory, and now the Toolbelt is not as useful as before. Maybe it was planned to store the Cargo Scooter in a toolbelt slot?
![Cargo scooter](https://github.com/Regalis11/Barotrauma/assets/143577687/bbd868eb-fcf6-4738-924e-67edf4f4f2b0)

### Reproduction steps

1. Start submarine editor
2. Open eny submarine and put the Cargo Scoter on the floor
3. start submarine testing
4. take a scooter with any character
5.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e66a52bbacd12b89f87e3d5697e9c3c63bb90cb (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
