### ISSUE TITLE
Wrecked diving suit lockers can't contain all suits, look weird

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12595]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wrecked diving suit lockers are using item identifiers for containables instead of broader item tags

`      <Containable items="divingsuit,abyssdivingsuit,combatdivingsuit" />`

This means they cannot contain modded suits or even Disposable diving suits
They should be using the same line as regular lockers:

`      <Containable items="deepdiving" excludeditems="deepdivinglarge" />`

Also when containing a suit, the lockers look completely different, the suit's contained sprite overriding the dirty window:

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6d1eff91-e29a-46eb-a570-e200fd5a7fbc)

This can be solved by
1. Using the regular diving locker sprite as a base Sprite,
2. Change the Wrecked Locker sprite's opacity to 70% / 180 alpha (in the spritesheet)
3. Add the wrecked locker sprite as a Decorativesprite with less depth

_Left to Right: Empty locker, Filled locker, Vanilla wrecked empty locker_
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/7100eb3d-2677-4e16-92c9-341bf5430197)

```xml
  <Item name="" identifier="divingsuitlockerwrecked" nameidentifier="divingsuitlocker" tags="divingsuitcontainerwindow,wreckdivingsuitcontainer" pickdistance="50" scale="0.5" category="Wrecked">
    <!-- regular locker sprite -->
    <Sprite name="Diving Suit Locker Vertical" texture="Content/Items/Containers/containers.png" depth="0.84" sourcerect="714,1,99,256" origin="0.5,0.5" />
    <!-- 70% opacity wrecked locker sprite on top -->
    <DecorativeSprite texture="Content/Items/Shipwrecks/MiscWrecked.png" depth="0.83" sourcerect="1126,1710,99,254" origin="0.5,0.5" />    
    <ItemContainer hideitems="false" drawinventory="true" capacity="1" slotsperrow="1" itempos="0,0" iteminterval="0,0" canbeselected="true" msg="ItemMsgInteractSelect">
      <GuiFrame relativesize="0.2,0.25" anchor="Center" minsize="140,170" maxsize="280,280" style="ItemUI" />
      <SlotIcon slotindex="0" texture="Content/Map/LabelIcons.png" sourcerect="512,0,256,256" origin="0.5,0.5" />
      <Containable items="deepdiving" excludeditems="deepdivinglarge" />
    </ItemContainer>
  </Item>
```

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c4af79f211b9850a3fc4391a2c60ec86cb38e060

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4456/commits/583af8944170dd17273c1f825662c724110a1459

Set up all suits in wrecked lockers.
No issues found.

Closing ticket.
