### ISSUE TITLE
Husks and husk related things are outdated

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12602]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

_Posting this until I can submit a proper PR_

Husks feel weirdly outdated

# **Visuals:**

The husk sprite itself is using a legacy diving suit sprite as well as an old ragdoll

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/7658d444-f29c-4036-8826-cfe4116c8b06)

Compare this to the currently unused "broken" diving suit

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/1631f4a3-6931-4cfe-ab6c-2c2aa8ed648f)

(sprites added by me)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/483bc8d0-3c7e-4180-91d1-f4bb5326b2e9)

More diving suits variations would be achievable via masking the helmet glass and apply hue changes to the different suits

The huskappendage limbs are low res and the joints break easily. They look worse than the old husk tentacles

https://github.com/Regalis11/Barotrauma/assets/73229309/8d13197e-f4cf-4b21-bcd1-98f46d89ef84

# Functionality

Husks only have one version of themselves (with the suit on), when humanhusk can handle the entire inventory and equipment system. 

More variants of inventories can be defined and spawned

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/f925930b-4358-40de-9627-9a1a692619d8)

Husk "parity" could be achieved between Humanhusk and Husk 
Mods have tried achieving more husk functionalities like shooting guns or using equipment (Improved Husks) 

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
I agree they could use some polishing, but this is not really a bug, so I'll close the ticket.
