### ISSUE TITLE
Fireman's Carry Acts Weird

### ISSUE THREAD

**Issue by RikuTheKiller** [Regalis11/Barotrauma#12603]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Grabbing people who aren't ragdolled still applies the lack of movement speed debuff from the Fireman's Carry perk.
This causes you to be way, way too fast for the grab to keep up and your characters to separate until it unlatches, looking extremely weird and buggy in the process.

### Reproduction steps

1. Get the perk.
2. Grab someone who isn't ragdolled.
3. Sprint.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e04af8657e6ce184e77d72ed635c5560f74097fd (commit in our private repo)
