### ISSUE TITLE
client crash when pick up a circuit box

### ISSUE THREAD

**Issue by Fachoj** [Regalis11/Barotrauma#12600]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

my friend try to pick up circuit box (rookie mistake)

### Reproduction steps

try to pick up circuit box on server

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Do you happen to have the crash report still?

**Comment by Fachoj** [comment]
ui of circuit box is flickering when picked. idk maybe just prevent ui appearing when box in inventory

**Comment by Regalis11** [comment]
Could you post the crash report if you still have it? Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
No known steps to repro or information of what the crash was. We've fixed a couple of crashes and errors that causes disconnects though, so it's likely this has been addressed already.
