### ISSUE TITLE
Alien door puzzle has missing wiring

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12609]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the alien module Chasm3, the 3rd door on the top has no wiring connecting it to the buttons, which means that it's impossible to open it.

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/500587d3-7d93-4340-a405-8bbc07d62b2d)

As an aside, most players don't even bother engaging with the buttons. You can't even see whether some of the doors are open or not, so it's rather generous to call it a puzzle; it's more a "hit random buttons until they're all open" thing. Or just break through the doors with a plasma cutter. If the intention was for it to be a puzzle, then it might need some reworking.

### Reproduction steps

1. Load the Alien_Chasm3 module in the sub editor
2. Open the wiring and observe that the 3rd door on the top is not wired

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b2213d0625c647dcb99385cb6eea6758a445dea

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4488/commits/2b575c97307f8d5c9de8d14e5e9b1142e4f17ed5

No issues found
Closing ticket
