### ISSUE TITLE
Can't exit sub near islands with caves

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#12613]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is abyss island with a cave, debuai on
![island](https://github.com/Regalis11/Barotrauma/assets/122838333/8e49afe0-01ea-492e-a76a-0877ea526ab2)
It's made of cells. Red cells is empty, i guess it's cave

 So, when you park your sub so airlock hatch/door is inside one of the red cells you can't pass through it, like there is invisible wall

![in](https://github.com/Regalis11/Barotrauma/assets/122838333/2869437a-8904-4f26-8727-c498b96f63e2)
![out](https://github.com/Regalis11/Barotrauma/assets/122838333/daff9d3b-3eb7-43fd-81cb-c73520019441)

It works with hatches and doors in all directions
You can test it with this [gem of clown engineering](https://steamcommunity.com/sharedfiles/filedetails/?id=3030524486)
![20230903235316_1](https://github.com/Regalis11/Barotrauma/assets/122838333/95d06ba8-ca96-487e-8a86-46ff2d3a59dd)

[pow: you went mining into abyss, and can't get back because sub moved 1px down](https://drive.google.com/file/d/136PGw9mQ6nZV0BIjkDlg4ENiDdKcgYYc/view)

### Reproduction steps

1. Subscribe to [the sub](https://steamcommunity.com/sharedfiles/filedetails/?id=3030524486) (or don't)
2. quickstart 4doorsub (or any other, orca 2 for example have bottom hatch)
3. f3, enablecheats, freecam, debugai
4. find abyss island with big open cave
5. teleportsub there and park it so your hatch/door is inside one of the red cells
6. try exit/enter the sub through that hatch/door

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Potentially fixed by https://github.com/Regalis11/Barotrauma-development/pull/4394/commits/b005e29528dc75c9fb7141b1f3bb74dc94a5ca3c (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4394/commits/71c79dd994576ebf42f1cc68a0f424d5e05e6b6b
Used sub and steps provided.
Abyss caves generated as they would normally.
No issues found.
Closing ticket.
