### ISSUE TITLE
Incendium fuel tanks can still be stacked in player inventory

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12616]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmxqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ea0f5896467dccf35783ef5f69ce9899ed2b7419/image.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9ba288c82cf29a45c6387c90d590dc812871d76a. Pushed straight to `release/traitor-update`, imo this is such a trivial change it doesn't need a separate PR and review.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
