### ISSUE TITLE
[Unstable] Circuit box eats component when full

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#12612]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you try to put a component in the circuit box while it already has max components, it makes a console message and doesn't put the component in but removes it from your inventory.

![image](https://github.com/Regalis11/Barotrauma/assets/42877449/ea6e3219-5fda-4219-936c-ba4b8df8ace8)

### Reproduction steps

1. Spawn a circuit box and put it down
2. Spawn 5 stacks of components and attempt to put all of them into the circuit box
3. Notice how once it's full, it still removes the items.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.11.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fbbc7242d499c6a9eb358734bf9fe5e123ee0559

**Comment by AdamH-Daedalic** [comment]
Tested against feature/circuit-box-prototype

The components get greyed out upon filling the maximum number of inserted components, preventing the player from adding more. 

However, when attempting to remove installed components from the box at full capacity, the first one does not get removed from the total installed figure and the available installation options do not become active to allow for selection until a second one has been removed, at which point the total number of installed items is off by one until the player exits and enters the circuit box menu again. 

https://github.com/Regalis11/Barotrauma/assets/135589009/8416ee50-cfdc-4110-a7f0-465b86633cf6

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f87891e4ad582f76a1d18547ca586dde276ff57

**Comment by AdamH-Daedalic** [comment]
Tested again with the new changes. 

All looking good now, the item count decreases correctly upon removal of installed components and the option to place new ones become available when space is made. 

Closing
