### ISSUE TITLE
Recipes with <RequiredItem tag="" /> can heavily drain performance

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [Regalis11/Barotrauma#12624]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If a fabricator features multiple recipes which make use of <RequiredItem tag="" /> instead of <RequiredItem identifier="" /> will cause the update time shown with "showperf" command to increase.
The more recipes with it and the more it is used within one recipe can impact performance significantly depending on the amount of mods installed when the fabricator UI is displayed on screen.
Only the person with the fabricator UI open will experience the performance impact.

In this example I use Hungry Europans - Testing Branch and compare the update time while idle with the stove UI open and the cutting board UI open.

While idle, the update time sits around 3.69.
![updateidle](https://github.com/Regalis11/Barotrauma/assets/74098498/c39fedb0-9647-4a05-8d57-c83a8bb78e11)

While using the stove, the update time barely changes as it barely has any recipe which makes use of the tags.
![updatestove](https://github.com/Regalis11/Barotrauma/assets/74098498/9587672b-3a7f-46f3-b92d-742a31c01a83)

While using the cutting board, the update time doubles.
![updatecuttingboard](https://github.com/Regalis11/Barotrauma/assets/74098498/3c0033d2-fa0d-468a-a7f2-35d48a23b49d)

It seems to be consistent in % of performance impact. Meaning the cutting board will always double the update time value.
So in a heavily modded playthrough where the update time is already at 6 to 8 it will be at 12 to 16 when interacting with the cutting board which leads to massive framerate drops to below 10fps.

A solution for modders would be to refrain from using tag based recipes and clutter the fabricators with a ton of recipe variants instead, but this is obviously an absolute mess for users to go through 5-6 recipe alternatives for a single item to craft.

### Reproduction steps

1. Create multiple recipes which make use of RequiredItem tag="" (possibly with varying condition requirements as well and some recipes with multiple required items with tags)
2. Play the game and interact with your configured fabricator for the recipes and watch the update time increase with "showper" command.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

Both unstable and stable version

### Which operating system did you encounter this bug on?

Windows

**Comment by PanmanS** [comment]
Mod is hungry europans (if you need it for reproduction of issue)

**Comment by Regalis11** [comment]
Nvm, I found the testing branch now, and was able to repro the issue there!

**Comment by Rokvach** [comment]
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/6bc9e08d262c6d2b52310065f6cfafd39fbac095 noticed a performance increase.

Tested with the mod Hungry Europans - Testing Branch

- Stove avg update 0.61ms
- Cutting board avg update 0.62ms

While on the current Unstable build

- Stove avg update 0.65ms
- Cutting board avg update 1.40ms

This ticket can be merged and closed.
