### ISSUE TITLE
Sprite issue on Depleted Fuel SMG Round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12629]
Spawning one using `spawnitem "Depleted Fuel SMG Round" cursor` shows the entire spritesheet

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazEyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f88e77605da6a2b22519de838ca89c02c737f15c/image.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56f50591930559a9ea4e7bb0f14d6a5dddcec7e3

**Comment by NilanthAnimosus** [comment]
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/0f8681877844076d8f8a0bc4cab574e6712c16e8, no issues found, closing.

Notes: also checked other items for any cases of a sprite being defined as 0,0,0,0 sourcerect or other potentially odd definition, found nothing however.
