### ISSUE TITLE
"Merge stacks" and "Sort alphabetically" icons aren't properly aligned to the header in 1440p resolution

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12631]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGQyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--46cfbe09cc8bf7fa340a179de4b4a369c3b69b2e/image.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/92d7f58c95cc359b07b4349fe5f90dabf59a34e0

**Comment by Regalis11** [comment]
Doesn't seem to work correctly on some resolutions(?), screenshot from @Rokvach  
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/88038d5f-dfa7-44fb-8fc6-deb26f7dd02a)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/abf5ee5f6b8d915358b44f16e2b8e63f750a4489

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
