### ISSUE TITLE
[Unstable] Circuit box not grabbed by player when editing the circuit

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#12635]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When editing the external wiring of a circuit box, you grab it to indicate you're editing it like usual, but when you are editing the components you don't grab it.

![image](https://github.com/Regalis11/Barotrauma/assets/42877449/b60076c6-c7da-4852-a131-0e495294cbbf)
![image](https://github.com/Regalis11/Barotrauma/assets/42877449/01345c24-79f4-4014-9143-66d081b264e0)

### Reproduction steps

1. Get a circuit box
2. Edit the internal circuit and look at your player behind the panel, or try to walk away and notice no resistance.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.11.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3eb87334a480279dde4bf0f97f910814376f99c8
