### ISSUE TITLE
Camaraderie talent bug

### ISSUE THREAD

**Issue by Randy624** [Regalis11/Barotrauma#12639]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The camaraderie talent should give your team an extra 20% experience. There is a bug, and it gives twice as much: 44%. (exp * 1.2 * 1.2)
https://barotraumagame.com/wiki/Camaraderie

### Reproduction steps

1. take a tallent
2. have fun with extra exp

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AdamH-Daedalic** [comment]
Tested this on v1.0.21.0

Definitely seeing a 1.4x boost to the amount of xp gained when using the talent. I completed the same mission at the same difficulty level and reward with and without the talent, receiving 99xp as a base without it and then 141xp with the talent active, an increase of about 43%

Moving to ToDo for fixes

**Comment by Regalis11** [comment]
Seems to have been accidentally fixed when I was refactoring the xp logic for the traitor xp steal feature: https://github.com/Regalis11/Barotrauma-development/commit/1f0ccceee204b50052d3ee47c696cd7988924675

**Comment by NilanthAnimosus** [comment]
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/d0c9ef0d76fa75491433efc3138cae3a3fde7011, no issues found, closing.

Notes:

The talent correctly multiplies by 20% once, however it is capable of stacking with itself and other talents multiplicatively if others have the same talent.
