### ISSUE TITLE
Wrecked variants of cabinets don't have the new Storage Container limitations

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12630]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFIyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7f7313f6c9f42c84e53969f0798e85997c22a72c/image.png)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1c1d452a72777704319f2247c650d79ddb03694d. Note that the commit changes all containers in wrecks, not just cabinets.

**Comment by Jasontti** [comment]
Tested.
Tried to put storage containers in all of the wrecked cabinets and that variantof works on secure cabinets.
No issues found.
Closing ticket.
