### ISSUE TITLE
[Feature Request] Easy texture rotation\flip

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [Regalis11/Barotrauma#1263]
The texture offset is difficult to use, can you add a texture rotation function and flip the texture function?

**Comment by Regalis11** [comment]
You can flip the texture by flipping the entire structure: Ctrl+N to flip horizontally and Ctrl+M to flip vertically. I'm not sure if rotating the texture is something worth implementing though, I can't really think of many situations where you'd need it and it'd require quite a lot of changes to the way structures are rendered.
