### ISSUE TITLE
Crash on attacking outpost bandits

### ISSUE THREAD

**Issue by Dathomerian554** [Regalis11/Barotrauma#12641]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have not had a full client crash until just now, and thought I should report it as it happened in kind of a weird way (see Reproduction steps).  

### Reproduction steps

I entered a separatist outpost (I am friendly, but not revered with them), and decided I wanted to steal some of the winnings in a game that some of the NPC's were playing.  Well, that turned out to be a bad idea and they brought out their full auto guns...  Anyway, it was right when the NPC started firing the gun that the game crashed, and it looked like it had something to do with the sound file (I don't know code either, so I could be wrong).  I shot the other guy before he brought out his gun, and there was no issue (I also had my security guards beating him up with stun batons and stuff), but when I got close to him (to the point where he could directly shoot me (and if I recall, he fired one shot that never hit)), then the game crashed.  

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/12557147/crashreport.log)
```

**Comment by Regalis11** [comment]
Thank you for the report! Based on the error message, this seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/9581. Closing as a duplicate.
