### ISSUE TITLE
Shift-drag (fine) resizing hulls, grab the left side makes the right side move

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#12646]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever fine-adjusting hulls (the rectangles, not the wall pieces) in the editor, the hull constricts from the right.

### Reproduction steps

1. Start the editor
2. Add a hull to an empty design
3. Grab the top left or bottom left corner
4. Hold shift
5. Drag
The right edge will slowly crawl towards the left

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Editor

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
I'm clicking shift here
[2023-09-09 12-06-28.webm](https://github.com/Regalis11/Barotrauma/assets/68995233/a346f601-d9a2-4e88-be0d-afb8ff19ecf9)

**Comment by mygamingaccount** [comment]
Not reproducible on stable v1.0.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/38f5a8293b9dd0c9dfdc3d9a3d19897ab85ca234

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
