### ISSUE TITLE
Figurehead talent bug

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12640]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using a medal on a character with 4 levels while having the figurehead talent does not boost them up to level 5.

https://github.com/Regalis11/Barotrauma/assets/37850646/df58fe22-12ea-472c-82f2-8589dcb7d131

### Reproduction steps

1. Get a character to level 4
2. Give that character a medal using a character with the figurehead talent
3. Observe that the medal does not give extra experience to boost to level 5

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It seems the "levels" start from 1, so the character here is actually level 5. I think this is very confusing though, and I generally don't even like using the term "level" in any of the talent descriptions because the character's levels aren't communicated to the players in any way anywhere. We'll need to think a bit about how to address this (changing the description, or changing the levels so they start from 0)?

**Comment by Vykn** [comment]
That's a strange inconsistency then, since if a character has 3 or fewer talents (i.e. is "level 4" from what you've said), they will be given enough experience to allow them to take 5 total talents - bringing them to "level 6".

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0b0c764b451ca572b72d346469e600981f34577e

**Comment by Jasontti** [comment]
Tested.
Made save in not-fixed branch that had 4 characters:
Captain with figurehead
Mechanic 750/2950 xp and 5 talent points
Engi 550/950 xp and 1 talent point
Security 0 xp and 0 talent points

Switched to fixed branch and loaded the save. Medals boost everybody to 0/2950 xp and 5 talent points, except Mechanic that got 550xp

Spawned in fresh assistant and medal worked as excepted on it.

No issues found. Closing ticket.
