### ISSUE TITLE
Can't detach portable pump behind duct block

### ISSUE THREAD

**Issue by EmunW** [Regalis11/Barotrauma#12649]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I accidentally placed a portable pump behind a duct block and now I can't remove it. I've tested this with a lever and it is able to be removed when placing behind a duct block.

### Reproduction steps

1. Place portable pump on duct block on the winterhalter.
2. Attempt to detach it with a wrench.
3. Wrench can only interact with duct block.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AdamH-Daedalic** [comment]
Reproduced on v1.0.21.0

I managed to reproduce it immediately in most ducts of the winterhalter, the player had the option to place the pump behind the block (placement shows the pump 50% covered up) and then was unable to detach it or even select it. I also encountered the same issue when testing it with a lever, however that was not always 100% reproduceable as I could remove it sometimes.

I also reproduced it on several other Vanilla subs when testing, most of them were fine but some had one vent where it occurred: 
Barsuk (Next to the console)
Camel (in front of the gun loaders)
Herja (topmost duct)
Typhon (most ducts)

https://github.com/Regalis11/Barotrauma/assets/135589009/b692eb76-2704-4cbd-9418-42931bd5a8df

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/04377f006fb53a29ad8e0d4e2e05a33b92f2e011

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/583af8944170dd17273c1f825662c724110a1459

Portable pumps are always interactable even if not visible.

Some items have visual issues.
Junction box and reactor have same sprite depth, but reactor completely obscures PP and junction boxes lightcomponent also odes this.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/713fa277-d4b7-497e-b282-174f32e561ab)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/14bf28f021d6727f22f62dae02ae09231a9fbb25

**Comment by Jasontti** [comment]
Sprite depth was adjusted in wrong direction.
depth="0.79" works.

**Comment by Jasontti** [comment]
It was intentionally moved backward.
You can still detach it perfectly fine from behind objects.
Closing ticket.
