### ISSUE TITLE
[Unstable] Shadow-casting lights for Gun loaders

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#12645]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

New indicator bulbs cast shadows by default, although their light range is 0. 
1 loader adds +6 shadow-casting lights.

### Reproduction steps

1. Open any submarine in the editor.
2. Add any loader and look at the number of shadow-casting lights.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This was mentioned in https://github.com/Regalis11/Barotrauma/issues/12520, and will be fixed in the next unstable version.
