### ISSUE TITLE
ItemSpawnInfo.SpawnPositionType.ContainedInventory cannot be applied to the next item

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12658]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

**break** should comes after the **AddItemToSpawnQueue**, otherwise it will only iterate once
https://github.com/Regalis11/Barotrauma/blob/0294a78afe66ddc22062e14123aa8d083f6215af/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs#L2168-L2200

### Reproduction steps

1. Add a SpawnItem Element(SpawnPositionType.ContainedInventory) to an item container(A) with 2 slots
2. Put a container in second slot of container(A)
3. Trigger spawn
4. Nothing spawn

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eced70dcb0c0360b2394e0eebc2b1818bef9db3d
