### ISSUE TITLE
Server crash with custom submarine file

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1265]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have a submarine a player had created (Capelin_Mkv, sub file enclosed in archive) which when starting the server, crashes in startgame() for the textmanager trying to handle server messages.

**Steps To Reproduce**
I am only able to reproduce this on my system, the creator of the submarine (who even resent me the same submarine) has no issues hosting with it, yet for me it crashes the server.

I am unable to work out a method to reproduce it. the only things of note is it is not a workshop item, other none workshop items do not have this issue (IE. very old out of date submarines).

**Version**
Windows, 0.8.9.5 steam closed alpha, Initially had issues on my server (Modified code, mainly some future commit fixes minus workshop fixes and ), but found it also occurs on my unmodified steam copy.

**Additional information**
I cannot provide reproduction, so instead will just hope it either fails from the submarine file or show the code where it is breaking and call stack information, I know its an easy fix for myself to just patch but the actual cause or reasoning is unknown and its still a crash.

Sub file:
[Capelin_MkV.zip](https://github.com/Regalis11/Barotrauma/files/2950337/Capelin_MkV.zip)

In shared - Source - TextManager under GetServerMessage(string serverMessage):

![image](https://user-images.githubusercontent.com/29177976/54094831-84e36e00-439b-11e9-8277-ba6787c269eb.png)

Call stack:

```
>	DedicatedServer.exe!Barotrauma.TextManager.GetServerMessage(string serverMessage = "Submarine: Capelin_MkV") Line 179	C#
 	DedicatedServer.exe!Barotrauma.Networking.ServerLog.LogMessage.LogMessage(string text = "Submarine: Capelin_MkV", Barotrauma.Networking.ServerLog.MessageType type = ServerMessage) Line 18	C#
 	DedicatedServer.exe!Barotrauma.Networking.ServerLog.WriteLine(string line = "Submarine: Capelin_MkV", Barotrauma.Networking.ServerLog.MessageType messageType = ServerMessage) Line 93	C#
 	DedicatedServer.exe!Barotrauma.Networking.GameServer.Log(string line = "Submarine: Capelin_MkV", Barotrauma.Networking.ServerLog.MessageType messageType = ServerMessage) Line 2759	C#
 	DedicatedServer.exe!Barotrauma.Networking.GameServer.StartGame(Barotrauma.Submarine selectedSub = {Barotrauma.Submarine}, Barotrauma.Submarine selectedShuttle = {Barotrauma.Submarine}, bool usingShuttle = true, Barotrauma.GameModePreset selectedMode = {Barotrauma.GameModePreset}) Line 1597	C#
 	DedicatedServer.exe!Barotrauma.CoroutineManager.IsDone(Barotrauma.CoroutineHandle handle = {Barotrauma.CoroutineHandle}) Line 159	C#
 	DedicatedServer.exe!Barotrauma.CoroutineManager.Update(float unscaledDeltaTime = 0.0166666675, float deltaTime = 0.0166666675) Line 191	C#
 	DedicatedServer.exe!Barotrauma.GameMain.Run() Line 264	C#
 	DedicatedServer.exe!Barotrauma.Program.Main(string[] args = {string[0]}) Line 36	C#
```

Information related to debugging for textmanager:
serverMessage = "Submarine: Capelin_MkV"
MessageWithVariables[0] = "Submarine: Capelin"
MessageWithVariables[1] =  "MkV"
msg = null
j = 1, string array "variableAndValue" only goes up to 0
variableAndValue[0] = "MkV"

**Comment by EdusFF** [comment]
Fixed in: 95169f5
