### ISSUE TITLE
Players die a while after leaving server

### ISSUE THREAD

**Issue by Junoticiwi** [Regalis11/Barotrauma#12656]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a non-host player is kicked or leaves the server when docked, after a period of time they will die. This resulted in no bag being dropped after saving and leaving.

### Reproduction steps

1. start multiplayer server with at least 1 person joined
2. non-host player leaves
3. wait until player dies

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
n/a
```

**Comment by Regalis11** [comment]
Thank you for the report!

This is actually intentional, the character will eventually go "braindead" after the client has disconnected. They should not get any penalties from dying this way: when they rejoin, they'll spawn with their items and skills in tact.
