### ISSUE TITLE
theduffelbag traitor objective not straight-forward

### ISSUE THREAD

**Issue by GoodDays13** [Regalis11/Barotrauma#12651]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The traitor objective theduffelbag is a bit confusing to start and seems messed up. You need to press e on it then click it shortly after, or else it won't start the mission. It is likely supposed to start after pressing E, but it doesn't.

https://github.com/Regalis11/Barotrauma/assets/42877449/dc7b1379-8d88-4ad4-9e58-7d17e0a44325

### Reproduction steps

1. Start a multiplayer server.
2. Open the console and do `starttraitoreventimmediately theduffelbag`
3. Fine the bag after the popup.
4. Press E on it and wait
5. Click it
6. Press E then click immediately after

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
This was addressed in: https://github.com/Regalis11/Barotrauma-development/commit/efff3078651bedbed3da9499cfb3fe904dae2af4
No actual ticket, as it was reported in observations. https://github.com/Regalis11/Barotrauma-development/pull/4393#issuecomment-1706074813
Closing as fixed.
