### ISSUE TITLE
Top left gun's Periscope wires are disconnected on the reworked Berilia

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12659]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The new Berilia on Unstable has the wires hanging out of the Periscope, preventing players from firing out of it. Players cannot easily fix this themselves in game, as the wires will not appear in the Periscope's interface for them.

This can be easily fixed in the editor by double clicking the ends of the wires and hooking them up to the Periscope.

Issue does **not** affect release build v1.0.21.0, as the reworked Berilia is not present there.

![image](https://github.com/Regalis11/Barotrauma/assets/5988156/3d3f8fb2-b0e0-4cf8-b793-afd03e878c19)

### Reproduction steps

1. Launch the game on Unstable v1.1.10.0
2. Load the Berilia through the Submarine Editor
3. Observe the wiring of the furthest-left Periscope in the Gunnery using Wiring Mode
4. Attempt to use the Periscope in-game

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by MarkCringan** [comment]
Glad somebody else noticed too lol.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7899031343cd679258c4c117fe5d8e30efec9ee4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
