### ISSUE TITLE
"Handcuff Shortage" mission will trigger on ships that do not have a fabricator

### ISSUE THREAD

**Issue by MarkCringan** [Regalis11/Barotrauma#12664]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Got the Traitor Objective to Craft 8 handcuffs on a dugong.
![image](https://github.com/Regalis11/Barotrauma/assets/115203569/46e30f4f-8f3b-4733-be33-f0117e00508f)

### Reproduction steps

1. Start a multiplayer lobby
2. Select Dugong
3. Select Cargo Missions
4. Add 4 bots
5. Start Round
6. Receive Objective
7. Cannot craft items due to lack of fabricator (as well as the ship not having the sufficient materials to craft the items in the first place. 

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

Unstable V1.1.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b1434b07181441b5e10334bce1ed14cd3059d4e9 (commit in our private repo). The events "deepdiver ducks" and "divine labor" seemed to have the same issue.

**Comment by Jasontti** [comment]
This was already fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ea0516e1c67ab35bafdf7ed0e664d57d5f73631
Tested similarly.
No issues found.
Closing ticket.
