### ISSUE TITLE
Server prevents picking up two-handed items in ItemContainer with RequiredItem

### ISSUE THREAD

**Issue by aoyamajia** [Regalis11/Barotrauma#12669]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In multiplayer only, you are unable to pick up items from an itemcontainer that has a requireditem to interact with, if picking up the item requires unequipping the requireditem (e.g., picking up a `RightHand+LeftHand` or `RightHand,LeftHand` item while needing a crowbar `RightHand+LeftHand,Any` to be equipped). The item container still appears to be selected after doing so, despite the UI not being drawn until you re-equip the requireditem. Dragging the item out of the container and onto the floor is not affected. Happens in both stable/unstable.

from unhappywithmyusername on the Discord server:
> I assume client gets the item, thus unequipping the crowbar/wrench, but server was still checking for the required item and since client no longer uses the item, it prevents the server from giving you the item and reverts the client change. Or something along those lines probably

The test xml (included in the mod in the attached zip file below):
```xml
    <Item name="adcrate" identifier="adcrate" tags="crate" scale="0.5" linkable="true" pickdistance="150" impactsoundtag="impact_metal_heavy">
        <Deconstruct time="0.5" />
        <PreferredContainer primary="adcrateshelf" amount="4" spawnProbability="1" />
        <Sprite texture="Content/Items/Containers/containers.png" depth="0.54" sourcerect="407,376,152,89" origin="0.5,0.5" />
        <Body width="150" height="75" density="25" />
        <Holdable slots="RightHand+LeftHand" holdpos="0,-80" handle1="-30,14" handle2="30,14" aimable="false" msg="ItemMsgPickUpSelect" />
    </Item>

    <Item name="require twohand" identifier="adcrateshelf" tags="adcrateshelf,container,cargocontainer" linkable="true" canflipx="false" pickdistance="150" scale="0.5">
        <Sprite texture="Content/Items/Containers/containers.png" depth="0.84" sourcerect="1,657,185,366" origin="0.5,0.5" />
        <ItemContainer capacity="4" maxstacksize="1" canbeselected="true" hideitems="false" itempos="92,-48" iteminterval="0,-92" msg="ItemMsgInteractSelect">
            <GuiFrame relativeSize="0.2,0.25" anchor="Center" style="ItemUI" />
            <Containable items="adcrate" />
            <RequiredItem items="crowbar" type="Equipped" />
        </ItemContainer>
    </Item>
```

https://github.com/Regalis11/Barotrauma/assets/39614559/161c53a9-7f9f-461d-a959-9ddbbe8b81b0

### Reproduction steps

1. Download and enable the [test mod adtest.zip](https://github.com/Regalis11/Barotrauma/files/12616128/adtest.zip) (contains modded shelves, crate, and test sub with the former two set up already).
2. Start a multiplayer session with the adtestsub submarine.
3. Equip a crowbar and attempt to open the shelf and pick up a crate.
4. Notice how you are holding the modded crate briefly before it teleports back into the shelf.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by aoyamajia** [comment]
Adding `autointeractwithcontained="true"` to the ItemContainer will automatically pick up the item, but it briefly appears as if it's been dropped, and does nothing with `SelectKey="Action"`.

[adtest.zip](https://github.com/Regalis11/Barotrauma/files/12616128/adtest.zip)

https://github.com/Regalis11/Barotrauma/assets/39614559/6f697090-7405-417f-92bb-121fcd8acaec

**Comment by Regalis11** [comment]
Thank you for a very thorough report! 

> I assume client gets the item, thus unequipping the crowbar/wrench, but server was still checking for the required item and since client no longer uses the item, it prevents the server from giving you the item and reverts the client change. Or something along those lines probably

This was exactly what was causing it: the server took the crowbar out from your hand slots, and then attempted to take the crate, which was inaccessible at that point. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/537fba577a2766d8ce1e8834bd44cca8f9c7364a

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
