### ISSUE TITLE
"Compound Nowhere" auto-completes despite not completing objective.

### ISSUE THREAD

**Issue by MarkCringan** [Regalis11/Barotrauma#12662]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Started a server with me and 11 bots on a Berilia doing a single cargo mission. Upon receiving the transmission from the coalition to get rid of the explosives, the mission automatically completes despite me not doing anything. Have not tried in any other game versions yet. 

![image](https://github.com/Regalis11/Barotrauma/assets/115203569/41e7b9ed-c4b3-42c4-930c-4d83eef287ed)

### Reproduction steps

1. Start a server
2. Chose Single Mission
3. Select Cargo Missions
4. Turn Traitor Difficulty to Lethal
5. Set Probability of Traitor to 100%
6. Add 11 bots 
7. Start game
8. Receive Transmission from Coalition about disposing of the Explosive Cargo
9. Get a mission success, the explosive cargo had not been touched. 

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b224516342ee1e32ec123f053eba715a6512855 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
Completed and failed mission successfully.
No issues found.
Closing ticket.
