### ISSUE TITLE
Herja medic spawnpoint assigned the wrong job

### ISSUE THREAD

**Issue by godsdrunkestsailor** [Regalis11/Barotrauma#12661]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

spawn point in the oxygen generator room has id_medic tag but is set as an engineer spawn
![image](https://github.com/Regalis11/Barotrauma/assets/144774074/d7edb086-2144-4c78-a700-bed51aecfae0)
next to a medicine cabinet and no other medic spawnpoint exists

### Reproduction steps

1. open the submarine editor
2. load the herja
3. enable spawnpoint visibility
4. observe

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

found in submarine editor; unsure if it makes any difference during gameplay

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by godsdrunkestsailor** [comment]
i didn't know what would happen if i pressed that button

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e60363231ce4a4dddc3454fb3e24f67102475aa2 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
