### ISSUE TITLE
Implement a method to determine and avoid friendly fire for IDamagable / damage methods or in weapons/tools/items themselves

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1266]
**Description**
Time for a little story for why I would even suggest a mechanism for friendly fire prevention. I was working on AI in the master/dev branch for my server for laughs and giggles, and with one or two mistakes even once ended up with a free for all between the AI and human players the moment you walked into the same room as them.

Amusingly enough though, giving AI's the option to run or fight, fixing their issues with melee weapons, allowing them to use other weapon types (Welders/cutters/crowbars etc) and getting them to approach and run at the target and stay within range but not inside, then in range use their weapons appropriately (Even correcting problems with melee weapon code and body picking code on the AI requiring the angle to face them when the weapon is held high or picking up the ragdoll collider at the position which isn't a limb so they don't attack, which both should be exempt from the checks) alongside adding combat objectives if a hostile is in the same room to preemptively flee/fight in the main human AI controller - In general just making AIObjectiveCombat work.

The AI would often hit each other and then after the deed is done begin a free for all between each other perhaps or any players that slightly harmed them, or attack each other after welding some walls or something, even to attack the player the moment the character is changed if single player if they even got grazed by other AI.

It got so bad I ended up adding an exclusion to effectively finish the objective immediately if the damage dealer was human in species, and feel the game could benefit somewhat from a friendly fire implementation (At least between AI even) to ignore certain types of targets for certain things.

Though it is funny to be shot to death by an AI captain because a mudraptor was on the other side of you and it recognized its existance, without bothering to check if you were between it.

If friendly fire prevention existed, you could perhaps even implement it as a server option, I don't know if disabling friendly fire would be that great of an idea for the average server, and I really feel this is more for the AI shooting you in the back because of a fish or welding your face off desperate to reach a wall.

side note to AI combat in case it interests - I still need to handle the steeringmanager far better, but I did have some fun with this just to show how it could look and easily get insane:

![Fleeing from the AI horror](https://media.discordapp.net/attachments/540532000860143616/554350186864836622/unknown.png)

![mass combat on the AI](https://cdn.discordapp.com/attachments/540532000860143616/554353275508359169/unknown.png)

(They use melee fairly well):
https://i.gyazo.com/97e659f3d4eb880cf82476a2e891368d.mp4

(Those without weapons fled):
https://i.gyazo.com/2098c5016cdd401b0768bf569e657768.mp4

(Can see how AI in a group can be an issue fast without much brains to them):
https://i.gyazo.com/5b5748ed1c44b43fed895948de6b5206.mp4

**Comment by itchyOwl** [comment]
All AI related issues mentioned here should be fixed in the next patch.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
