### ISSUE TITLE
[Unstable 1.1.11.0] Storing the Сargo Scooter in cabinets

### ISSUE THREAD

**Issue by 0n1ime** [Regalis11/Barotrauma#12666]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the new container storage solution, a special slot for Storage Containers and Toolbelts was added, but the Cargo Scooter bypassed this restriction, which violates the new concept of storing items. Game version Unstable 1.1.11.0.

### Reproduction steps

1. Start submarine editor
2. Open eny submarine and put a Cargo Scoter on the floor
3. Start submarine testing
4. Take a scooter with any character
5. Drag a Cargo Scooter into a Steel Cabinet
![Cargoscooter in large cabinet](https://github.com/Regalis11/Barotrauma/assets/143577687/1c0c27f9-7a55-4839-9e3d-35a42b442340)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

Unstable 1.1.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
