### ISSUE TITLE
Backpack's movement speed reduction doesn't work when wearing a diving suit

### ISSUE THREAD

**Issue by N1ght-Raven** [Regalis11/Barotrauma#12673]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ifd you wear backpack and any suit together the speed reduction seems to doesnt match. So there is no differences to not use backpack as long as you vear any suit. Except the combat one or PUCS.

https://github.com/Regalis11/Barotrauma/assets/92939058/40e25ea1-3e34-41ba-84fa-1c330aa2f2f8

### Reproduction steps

1. Just wear backpack and suit together lol

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

Unstable V1.1.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bc14e01f542ac5f2b1697ff551c89dbeb073a232 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/ba9d41abb2da0257d2aa4fb96beb86fd0aad9443 working correctly, closing.
