### ISSUE TITLE
Turret crashing

### ISSUE THREAD

**Issue by gabbigamers** [Regalis11/Barotrauma#12670]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Whenever i enter the periscope and shoot, my lobby hard crashes and puts me in server menu and gets rid of all of our progress.

### Reproduction steps

1. Start multiplayer game
2. Man the periscope
3. Shoot
4. If nothing happens then im confused

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Cant send it exactly right now, will do when im home.
```

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid this might be difficult for us to diagnose without the crash report and/or the list of mods you're using. I suspect this has something to do with the mods, since we haven't gotten any reports about this happening in an unmodded game.

**Comment by gabbigamers** [comment]
I have fixed the issue, i had to remove a few mods. I dont remember precisely which ones i got rid of.
