### ISSUE TITLE
Bots ignore Spinelings when using the railgun

### ISSUE THREAD

**Issue by 0n1ime** [Regalis11/Barotrauma#12676]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If  bots uses the railgun, it will ignore Spinelings, allowing them to attack the submarine with impunity. They also ignore Leucocytes, Swarm Feeders and Terminal Cells, but maybe it's intentional.

### Reproduction steps

1. Start submarine editor
2. Open eny submarine with railgun
3. Start submarine testing
4. Order bot to operate the railgun
5. Create the listed creatures next to the railgun with the console command
6. Bot will ignore them

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

Unstable 1.1.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
It's intentional, but the decision was tentative. The intention behind was that it's not reasonable to shoot spinelings with a railgun and the bots don't cope well with it. Maybe we'll reconsider this.
