### ISSUE TITLE
Suit sprite depth not changing with character sprite depth. 

### ISSUE THREAD

**Issue by CRedinger** [Regalis11/Barotrauma#12674]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There seems to be a few issues with suits sprite depth:

- All dive suits - When the character is at a higher sprite depth than usual due to using a ladder, periscope, etc. the shoulder portion of the suit does not have its sprite depth adjusted with the rest of the suit.

- Exosuit and funbringer - When the character is at a higher sprite depth than usual due to using a ladder, periscope, etc. the entire suit doesn't change sprite depth.

- Exosuit - Held 2-handed items appear between its legs. 

### Reproduction steps

Here I have a ladder at sprite depth .900 and fins at depth .501.

![image](https://github.com/Regalis11/Barotrauma/assets/49667563/cbe41273-4ea6-4b02-862a-3359d6f19df7)

Wear an exosuit and pick up a crate. 

![image](https://github.com/Regalis11/Barotrauma/assets/49667563/d0af1dec-692a-4046-b393-40a338c589de)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.13.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/208e0d54c050b57df3dbd9cad3f65938c44645c2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
