### ISSUE TITLE
Selecting abandoned outpost as a mission type sometimes starts a jailbreak mission which causes a level equality check failed error

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12672]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/5842f0bd-ac9d-4839-a800-cff9ed459f3d)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/51315fee-abf3-416c-b0aa-76a8ccfe5906)

### Reproduction steps

1. Host a server (I used two clients in this test)
2. Only select abandoned outpost as a mission type
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/1592d66c-3799-4f27-9762-2470b6689002)
3. Start a round, if it spawns you inside a normal abandoned outpost mission then retry

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Other

### -

Branch: feature/circuit-box-prototype

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value TopAndBottom: 38BD6330, server value TopAndBottom: 915E4F7, level value count: 17, seed: Cu4d4d8n, sub: Dugong (326CAC5), mirrored: False). Round init status: WaitingForStartGameFinalize.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 942
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 747
   at Barotrauma.Networking.LidgrenClientPeer.HandleDataMessage(NetIncomingMessage lidgrenMsg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\LidgrenClientPeer.cs:line 162
   at Barotrauma.Networking.LidgrenClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\LidgrenClientPeer.cs:line 124
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 505
```

**Comment by Regalis11** [comment]
Could not reproduce. Tested by setting the commonness of jailbreak_coalition to 100000 to ensure it gets selected, and started an abandoned outpost mission round. Didn't encounter any errors.

But I guess it's not intended that these missions can get selected as "abandoned outpost missions".

**Comment by Regalis11** [comment]
It seems this is hard to repro reliably: it depends on which order the game happens to load the location types in, so you may need some restarts to get it to occur.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05e8d637c3c4b9550f962fb82e72a47b0201a8b4

**Comment by Rokvach** [comment]
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/5f3c10b3023bc9982aebe22ec05e88dbcf000159 by using the original repro steps, didn't ran into issues, I was successfully able to load 5 different jailbreak levels. 

Working correctly, can be merged and closed.
