### ISSUE TITLE
Missing tags in steam workshop

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#12682]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When publishing a mod to workshop you can add "Environment" and "Art" tags
But you can't browse by them in workshop
Could you add them?
![tags](https://github.com/Regalis11/Barotrauma/assets/122838333/36909c64-213d-4871-a1f3-36c1ca0daeb7)

### Reproduction steps

[just go here and check ](https://steamcommunity.com/app/602960/workshop/)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

In steam workshop

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Should be fixed now.
