### ISSUE TITLE
Traitor selection isn't random enough

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12689]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During community testing I noticed that I was always picked as the traitor even though I didn't complete any of the traitor objectives. This was an issue with the older traitor system as well where the system would constantly just pick the same player round after another. Maybe some stricter rules are required to make sure this doesn't happen as often.

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

Unstable V1.1.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d2bb69a14990985327639e729233f55619b186a

**Comment by Rokvach** [comment]
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/f82f7fcccc52c88d47e2c93813ce6949f720e47c traitors are now more random. 

Used verboselogging on debug server and noticed the percentages listed on the ingame server log.
