### ISSUE TITLE
Bots interact incorrectly with large-size firearms (can't put it in the toolbelt slot)

### ISSUE THREAD

**Issue by 0n1ime** [Regalis11/Barotrauma#12684]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots do not remove a large-size firearms (autoshotgun, HMG) from their hands back into the Tollbelt Slot while swimming in the water, ignoring scooters in their inventory. They also drop large-size firearms out of their hands when they urgently need to repair damaged systems on a submarine, instead of removing it into the Tollbelt Slot.
I have combined these two issues into one report because I am sure they have the same reason.

### Reproduction steps

1. Start submarine editor
2. Open any submarine and put HMG in any cabinet
3. Start submarine testing
4. Give the HMG and a scooter to a bot
5. Order a bot to follow the player and go outside a submarine
6. when the bot is holding the HMG in the water, it cannot switch to the scooter

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### -

Unstable 1.1.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d671ec414bb96e50bd530f298a7907baa8226834 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
