### ISSUE TITLE
Fabricator scroll resets to top whenever another player accesses it or if you re-select it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12687]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Title

### Reproduction steps

1. Play multiplayer
2. Have one client using fabricator scrolled down on the list
3. Another client then selects the fabricator
4. Scrolling should reset for the first one

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

Unstable V1.1.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f3fa38ccc83d99469be902c22655c68cadcf5f9f

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/583af8944170dd17273c1f825662c724110a1459

Hosted multiplayer session.
Used fabricator, also linked containers, as a host and client.
Tested normal fabricator behaviour.

No issues found.
Closing ticket.
