### ISSUE TITLE
Ready checks immediately complete with 1/max votes

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12688]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During community testing whenever someone started a ready check it just immediately completed

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

Unstable V1.1.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Couldn't find a way to reproduce this :/

**Comment by Regalis11** [comment]
Me, @Rokvach & @Jasontti tried debugging this and the only way we could get something like this to happen was by starting the ready check immediately when the round starts. The clients who were still loading into the round got excluded from the check.

Implemented a quick workaround to this in https://github.com/Regalis11/Barotrauma-development/commit/100700d1c9312164b4097a11bc60241a442cb56d

**Comment by Rokvach** [comment]
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/8e8d67906d96d362b2ff2d30629ca843f1e47b10 there is now a 10 second wait until the ready check shows up, which I think is fine for slower hardware, I was still able to get 1/1 votes but I am also running the game on the fastest possible m.2 drive you can get right now. 

So working to some extend and players can always redo the vote. Closing.
