### ISSUE TITLE
Bandolier still doesn't seem to increase pulse laser fire rate

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#12695]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

is this also wontfix or you just forgot? it's been a year ago
https://github.com/Regalis11/Barotrauma/issues/9663#issuecomment-1712945987

i noticed this too, but found out that this has already been reported

### Reproduction steps

shoot laser with and without bandolier
compare amount of shots for some period of time

or any other testing method you like

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

As mentioned in the previous ticket, we weren't planning on addressing this. Although, since we've been getting several reports about it and it's a simple thing to change, I suppose we could fix it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d3046c64dcb9e58a8ec553d28ac38a6eb888f50 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4456/commits/14bf28f021d6727f22f62dae02ae09231a9fbb25

Measured charge up time for pulse laser with bandolier 0,75s
No issues with other turrets found.

Closing ticket
