### ISSUE TITLE
"Party Banner" shows collapsed version when attaching

### ISSUE THREAD

**Issue by JeroonBosch** [Regalis11/Barotrauma#12691]
Would be nicer if it showed the full banner, to give a better impression of what it will look like

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d4807f573c8bd9be18e61f0879b136ee73142728

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
