### ISSUE TITLE
Several container windows have become difficult to drag around

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#12693]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/69410159/506a4644-f7f2-4dcd-a50d-21942168b222)

There is only a tiny line able to be clicked and dragged on the top part of container windows, it's not all containers however, it works fine for engines, deconstructors, fabricators., and pumps.

![image](https://github.com/Regalis11/Barotrauma/assets/69410159/69a0ca47-014b-488b-9184-ddeb8e22381b)

The sides and bottom work fine for dragging however, it seems like it's just the top part of the containers that have been misaligned or the size of the grabbable area has been changed inadvertently.  

### Reproduction steps

1. Create a Coilgun- and Rail Loader, and several types of cabinets / storage types.
2. Create a few machines like pumps, fabricators, deconstructors, and so on.
3a. Compare the top draggable area between things in point 1 to things in point 2.
3b. Also make sure the sides and bottom draggable areas work as intended.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4479/commits/a9c9a77e5e49f94052b7797dc9ab4868a67a3ab2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
