### ISSUE TITLE
[unstable] water pressure crush while hatch open inside submarine

### ISSUE THREAD

**Issue by 1stLtv2** [Regalis11/Barotrauma#12692]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

character crush by water pressure while welding hull in leaking ballast 
The water does not flood over the hatch

### Reproduction steps

water trapped inside ballast and crush player

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

To me, this doesn't seem like it's necessary a bug. If the water is flowing inside faster than it can flow out the hatch, pressure will build up and you'll get crushed.

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
