### ISSUE TITLE
Keybind Prompts Do Not Update On Already Selected Devices

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#12709]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hovering over an interactable object, like a junction box or cabinet, and then going into the settings to change the keybinds, will not update the keybind prompts on the same object. Any other objects that are hovered over for the first time in the round will show the proper keybindings. The keybinds of a prompt on an object will not change until the next round, meaning that if keybinds are changed multiple times throughout the round, many objects could all have different keys. For clarification the difference in keybinds is visual only, the actions on the prompts only function on the current keys that they are set to.

https://github.com/Regalis11/Barotrauma/assets/60911734/30036fa0-5e93-4294-b5bc-6c1f55c61fa2

This video shows the Interact, Rewire, and Repair key prompts changing for every junction box. This was done by hovering over a junction box, going into the settings to change keybinds, and then selecting the next junction box. Incrementing numbers/letters are just for demonstration of the changing keybinds. All prompts did not change until the end of the round.

The keybinds not changing could easily confuse players (especially new players) changing their keybinds mid-round and seeing how their updated keys are only shown on some of the objects that they hover over of.

### Reproduction steps

1. Start a round
2. Hover over an object, like a door or cabinet
3. Change the keybinds that the object used, like "Select" for the Interact prompt or "Use" for the Repair prompt.
4. Hover over another object, another of the same object for the sake of simplicity
5. Observe how the updated keybinds show on the second object, but the old keybinds still show on the first object.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/375be2635e545409c651d5d727a8287651ea6ecf

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4488/commits/ec35ad89af9ca8f209d85b3d700e5b9c6b6dd9e4

Changed keybindings and didn't spot any issues.
Keys worked and tooltips updated when hovering again components.

Closing ticket
