### ISSUE TITLE
Circuit box: component gets deleted when deleting text from the properties box

### ISSUE THREAD

**Issue by CRedinger** [Regalis11/Barotrauma#12708]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When in a circuit box, in the editor, if you select a component, and attempt to edit one of the properties fields, it's easy to accidently delete the component. When focused and editing a properties field, if your cursor is inside the boundaries of the properties box, delete will edit the focused field as expected. But if your cursor drifts outside the boundaries of the properties box, then pressing delete will instead delete the component, even if you are still focused on the properties field and any other keystroke would still edit that field. 
If this was intended, I would recommend changing this behavior to make it so delete only deletes a component when you are not focused on a property field. 

### Reproduction steps

Attempt to use delete to edit the values of a circuit box component when your cursor is outside the properties box.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Sub Editor

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/24163be5529ba6f0eb63a73618a301d67502b39d, using del while your cursor is inside the properties box or you have something selected in the properties box doesn't delete the component anymore. Working correctly, can be merged and closed.
