### ISSUE TITLE
(Server) Allowed monster spawns setting is not saved to file.

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12700]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Currently "Monster spawns" setting is not saved to file and doesn't persist between server restarts.
Also monster list is not sorted in anyway.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/4a7cb9ab-8c17-44ac-97be-578fd0c2d5c8)

### Reproduction steps

1. Start server
2. Set some monster disabled in Settings -> Gameplay -> Monster spawns
3. Start server (optional)
4. shutdown server
5. start server again
6. Notice that previously set filter was reset.
7. Notice that list of monster is not ordered 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Dedicated and hosted server

### Version

Other

### -

1.1.13.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Not aplicable
```

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/e460265be2370d6f2fd830b9a218be92e1145193

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
