### ISSUE TITLE
"Stunned" pets when grabbed and pet behavior

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12701]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When a pet is grabbed by a player, it is "stunned"

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ed078db5-4cae-4b44-bb32-05e1924c4449)

This "thalamus scooter" pet flees the player
The goal here is to change the pet AI behavior from "Avoid" (Escape) to "Idle" when grabbed so it stops fleeing
This uses a conditional that checks for Stun to change the AI in _Underwaterscooterpet.xml_

```xml
  <StatusEffect type="OnActive" target="this">
    <Conditional stun="gt 0" />
    <AITrigger state="Idle" duration="5" allowtobeoverridden="false" allowtooverride="true" />
    <Sound file="Content/Characters/Fractalguardian/ALIEN_fractalGuardianPanicLoop.ogg" loop="true" range="3000" />    
  </StatusEffect>  
```

The sound is for debugging.
When using a console command `giveaffliction Stun 0.1 Underwaterscooterpet`, the statuseffect triggers, but not when you manually grab the scooter

Two observations:

1. The stun applied when grabbing doesnt trigger the statuseffect/conditional

2. AI states cannot change when stunned. The statuseffect triggers but the AI state will only changed after the pet is released and the "stun" disappears

Grabbing Pets should apply a "real" stun? 
AITrigger should work even if a character is stunned?
Or something simpler like using OnPicked when a character is grabbed

### Reproduction steps

Enable Thalamooter mod
[Underwaterscooterpet.zip](https://github.com/Regalis11/Barotrauma/files/12684446/Underwaterscooterpet.zip)

---

1. Spawn the scooter in water

2. Grab it and release it

3. Nothing happens

---

1. Spawn the scooter in water

2. Grab it

3. Use the console command `giveaffliction Stun 0.1 Underwaterscooterpet`

4. Release it

5. It changes behavior (after a short delay)

**Comment by Regalis11** [comment]
This fake stun is actually just the pet ragdolling, try checking IsRagdolled instead. :)

**Comment by ubertpendragon** [comment]
No luck

**Comment by Regalis11** [comment]
Ah, sorry, it seems `IsRagdolled` is not a property exposed to status effects. Another way to go about this would be to check `SelectedBy="neq null"`. But regardless, it's starting to feel like this is more of a modding support question or a feature request than a bug report, since the original issue is not an actual bug (the conditional should not work because the pet isn't actually stunned).

**Comment by ubertpendragon** [comment]
It does work with SelectedBy, but the issue of AI state not changing while the creature is held/stunned remains :(

**Comment by Regalis11** [comment]
The way I see it, that makes sense, if the character is "stunned" (or in this case, not doing anything), imo it shouldn't be changing the state. Or to put it another way, it wouldn't make any difference even if the state changed immediately, because the character won't be doing anything regardless of the AI state. 

How are you trying to make it behave, do you want it to break away from the character and start idling immediately?

**Comment by ubertpendragon** [comment]
I was mostly trying to stop it from making scooter bubbles and sounds in the ragdoll when grabbed by changing the AI state to "Idle"

```xml
    <StatusEffect type="OnActive" target="This" comparison="And" >
      <Conditional AIState="Escape" />
      <Conditional Inwater="true" />
      <Sound file="Content/Items/Diving/ScooterLoop.ogg" loop="true" range="1000" volume="1"  />    
      <ParticleEmitter particle="bubbles" anglemin="80" anglemax="90" distancemin="0" distancemax="0" particlespersecond="20" scalemin="1" scalemax="1" copyentityangle="False" velocitymin="50" velocitymax="100" colormultiplier="255,255,255,150" lifetimemultiplier="1" />
    </StatusEffect>
```

I don't think it's possible to generate the particles on the character.xml directly so that's why I'm using the ragdoll

I'll try again, thanks for the help

**Comment by ubertpendragon** [comment]
Put these in creature.xml and fixed it 👍 
The AI state switch still has a small delay but otherwise it's perfect

```xml
  <StatusEffect type="OnActive" target="this">
    <Conditional SelectedBy="neq null" />
    <AITrigger state="Idle" duration="5" allowtobeoverridden="false" allowtooverride="true" />
    <Sound file="Content/Characters/Fractalguardian/ALIEN_fractalGuardianPanicLoop.ogg" loop="true" range="3000" />    
  </StatusEffect>
  <StatusEffect type="OnActive" target="This" comparison="And" >
    <Conditional SelectedBy="eq null" />
    <Conditional AIState="Escape" />      
    <Conditional Inwater="true" />
    <Sound file="Content/Items/Diving/ScooterLoop.ogg" loop="true" range="1000" volume="1"  />    
    <ParticleEmitter particle="bubbles" anglemin="80" anglemax="90" distancemin="0" distancemax="0" particlespersecond="20" scalemin="1" scalemax="1" copyentityangle="False" velocitymin="50" velocitymax="100" colormultiplier="255,255,255,150" lifetimemultiplier="1" />
  </StatusEffect>
```
