### ISSUE TITLE
Talent Points Not Giving Option to Apply

### ISSUE THREAD

**Issue by Dathomerian554** [Regalis11/Barotrauma#12705]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I don't recall this issue happening before I started using the unstable version, but basically I can't apply talents to one of my crew (only the one though).  View screen recording below.  

https://github.com/Regalis11/Barotrauma/assets/144430175/24c3b7bd-9566-4fa9-b537-5dae9aed84ae

### Reproduction steps

Normal function of the game (i.e. select Info Tab; Character, and apply talents).  

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

v1.1.13.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Thank you for the report! Would it be possible to send us the save file? Not that you need to .zip it first, because GitHub doesn't allow attaching files with the .save file extension. Thanks and sorry for the inconvenience!

**Comment by Dathomerian554** [comment]
Let me know if this is correct:  
[My First Mission.save.zip](https://github.com/Regalis11/Barotrauma/files/12699550/My.First.Mission.save.zip)

**Comment by Regalis11** [comment]
That works, thank you!

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a33f1bdbdbf1a7941c477f732ef983c62045ed86 (commit in our private repository)
