### ISSUE TITLE
[Unstable] Skitter and Mollusc genes cite incorrect affliction values

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12706]
### What happened?

The description of Skitter and Mollusc still range from 0-10, but the values now range from 0-60

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/c8f6694f-2eca-4343-95db-e07ae3b67924)

### Version
v1.1.14.0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
