### ISSUE TITLE
[Dev Version] Auto Aim set to 0% doesn't let you click anything

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1270]
Alright, been playing just now, I hate auto aim and how it makes me click fire extinguishers when I clearly specify a button at times. So, I had set it to 0%. I put my cursor on the button, press e, and it does nothing. Can't interact with anything when it's set to 0%. Thought that was pretty much as buggy as a bug gets. Please fix.

**Comment by Regalis11** [comment]
Fixed in v0.8.9.6
