### ISSUE TITLE
[Dev Version] Mic popup error doesn't go away when clicking "ok"

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1271]
I click host server, the mic error message shows up. I don't care, so I click "ok" to get rid of it. It doesn't go away. That's the bug, in all practicality.

**Comment by NilanthAnimosus** [comment]
this sounds like a duplicate of #1262 perhaps? is this different in any specific way?

As a note, the host is still effectively a client, connecting to a second instance of barotrauma (the dedicated) locally.

**Comment by Regalis11** [comment]
Duplicate of #1262
