### ISSUE TITLE
Ceiling webbing has no visual indication to navigator

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12726]
### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/25fec417-60dd-4e56-8358-598241c6c3fc)

Webbing hangs off the ceiling and are able to dramatically slow down the submarine. To a captain who has little to no visual information from outside, this behaviour appears extremely odd; the submarine just rapidly decelerates for seemingly no reason. The webbing often is mistaken as background decoration (much like the other rocks and plants that line the cavern walls) and most players aren't aware of its existence, so are very likely to be confused if their submarine gets caught in it.

There should probably be some visual indicator on the sonar that there is webbing (something akin to ballast spores perhaps), so a captain can identify it and avoid it, and not be confused when the sub is slowed to a crawl.

**Comment by SomeRandomNoobKekeke** [comment]
The real problem is that a boat capable of doing 1000 km/h get slowed down to 5km/h and can't tear up this piece of grass

**Comment by Vykn** [comment]
That was a different issue that has already been addressed.

I read through it again and found that Regalis had already mentioned in a comment that they didn't want to make it visible on sonar, so I'll close this ticket.
