### ISSUE TITLE
Alternately quickly taking out and putting in inventory will cause other clients to be crashed

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12727]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Other clients crash when you take item(A) out from item(B) and continue to quickly put item(B) into item(A)

https://github.com/Regalis11/Barotrauma/assets/73634685/1c72059a-98c3-4d2a-aa73-3f710951c147

### Reproduction steps

1. place two artifacttransportcase in the sub editor and give both of them tag "alienartifact" for to put them into each others
2. put one in another one
3. take out it from the inventory
4. and then quickly put the previous container into the last taken one
5. other clients will be crashed

Here're the sub i used for testing:
[Training Ground.zip](https://github.com/Regalis11/Barotrauma/files/12749903/Training.Ground.zip)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Other

### -

Multiplayer Hosted from in-game and hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by zhu-rengong** [comment]
There are no crashes reported, the game is stuck and the window is unresponsive until you manually close the game.

**Comment by Regalis11** [comment]
Ah, I see! In that case I guess it's probably an infinite loop of some sort.

I gave this a test but unfortunately couldn't find a way to reproduce it though:

https://github.com/Regalis11/Barotrauma/assets/14351070/e8272a4a-0ad7-4ebb-8127-9a997c50234b

**Comment by zhu-rengong** [comment]
The operation speed needs to be very, very fast, and the operations must be completed almost at the same time.

**Comment by Regalis11** [comment]
Do you have any tips on how one can do it that quickly? Are you using some combination of hotkeys?

**Comment by zhu-rengong** [comment]
reserve a slot(binding to shotkey:num1) and fill with other slots
take one out from the another one to the hand slot
and then just press num1

**Comment by Regalis11** [comment]
Thanks, that did the trick and I was able to repro it now! :)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/464bf9ff1a7f99a5a23ff0ce8e6707f6e97cc258

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4505/commits/80460ea422873cd1370199b642c2948dfab495f6

Tried same methods that crashed in 1.0.21.0 and could not get game to crash anymore.
No other issues found.

Closing ticket.

**Comment by zhu-rengong** [comment]
@Jasontti Hello, sorry for ping here, a quick question, has the bug fixed in the latest update (v1.1.18.1)? Whether it's fixed or not, it still happens in v1.1.18.1
I know there's some fixes not mentioned in changelog, so I reserve a guess that the "fix" for the bug may not has been mentioned yet in the most recent version.
Therefore I think i should continue to ask.

**Comment by Jasontti** [comment]
@zhu-rengong Hi, don't worry for pinging.
This fix is not in current stable release.
