### ISSUE TITLE
[Dev Version] Grabbing monsters not implemented despite Regalis saying they were

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1272]
Might be a bug or something unintentional, but despite saying so in the image I linked, grabbing monsters is still not implemented. This is quite confusing, as I've just tested it out. The [g] key, the [h] key, none work.
![liar liar nigger liar](https://user-images.githubusercontent.com/41457828/54248286-2eb62c80-454d-11e9-9169-1d8eb0ba3e5c.PNG)

**Comment by NilanthAnimosus** [comment]
Only specific creatures can be grabbed as far as I know. I recall dragging one down a corridoor a few versions ago actually, have you tried with all the indoors capable creatures?

**Comment by Regalis11** [comment]
Yeah, only specific (small) monsters can be grabbed.
