### ISSUE TITLE
Error while reading a message | could not find a job prefab with the identifier

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#12737]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I couldn't connect to a game. I restarted Barotrauma and the host went back to the lobby but I still couldn't connect.
Then the host changed the lobby to sandbox mode and I could connect.

After a while of playing in campaign mode, we went to the lobby (still campaign mode) and I left and tried joining (to test it). The error message started appearing again.

To fix it, the host switched to Sandbox mode in the lobby and again, I could connect. This is reproducible but I'm not sure to what extent.

### Reproduction steps

Have custom jobs in the campaign, using the mod Jobs Extended. Load a campaign in the lobby or just start a game in campaign mode with custom jobs. Have a client connect (I think the client must have a custom job character).

Workaround:
Change the server to sandbox mode. The client can connect to the lobby.

### Bug prevalence

Infinitely on two occasions

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment SyncIds at position 32.
Inner exception: Error while reading CharacterInfo received from the server: could not find a job prefab with the identifier "308391353".
   at Barotrauma.CharacterInfo.ClientRead(Identifier speciesName, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterInfo.cs:line 560
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 827
   at Barotrauma.Networking.GameClient.<ReadLobbyUpdate>b__117_0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2066
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by Krzeszny** [comment]
It's most likely because of Jobs Extended and problems with Steam Workshop.

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/29b338b8bb7709f84395391d2babd06e8c184651

Note for QA: it seems this only occurs if the client who's joining doesn't have the mod enabled.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4513/commits/36860afbacc12b154ee6242d57d283f899a6bd9b

Tested vanilla and modded variations of game modes and joining in late.

No issues found
Closing ticket
