### ISSUE TITLE
Circuit Box: signal_in only passes signal to first signal_out when directly wired to multiple

### ISSUE THREAD

**Issue by CRedinger** [Regalis11/Barotrauma#12739]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you are wiring directly from a circuit box's input panel to it's output panel, and you wire one input to multiple outputs, only the first output it is wired to will forward the signal.  

### Reproduction steps

![image](https://github.com/Regalis11/Barotrauma/assets/49667563/63293dc4-5ab5-4601-bd14-723128c49927)
![image](https://github.com/Regalis11/Barotrauma/assets/49667563/53ab9faa-dc2c-48fa-a3d9-b8dbdb6088fb)
![image](https://github.com/Regalis11/Barotrauma/assets/49667563/29befce6-c6dd-4857-8e56-e4af64f8aea1)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ef94d18d77432223585c04732e494e5f5091ef0 ignore the ticket I tagged in the commit I copy pasted the wrong one

**Comment by Rokvach** [comment]
Tested all the 8 pins in singleplayer and multiplayer, working correctly. Can be merged and closed.
