### ISSUE TITLE
Depth charge does not inherit subs velocity

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12735]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When firing a depth charge, it does not start using the ships velocity. If you are moving down quickly you'll impact it as its launched.

### Reproduction steps

1. Move sub down quickly
2. Launch depth charge
3. Watch it collide with your own sub instantly as it spawns without enough velocity. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BlackMoons** [comment]
PS: I understand that depth charges do have their own density and drag. I would expect correct behavior would be: Depth charge is launched at ship speed + impulse speed (in direction of launcher turret aim), and *maybe* collides a few seconds later if submarine is sinking fast enough and not moving forward/reverse fast enough as the depth charge slows down to its own natural sink rate. (Assuming a low enough density on the depth charge)

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce the issue. The loader does seem to add the velocity of the submarine to the depth charge as expected.

If you're testing this using the modified depth charge you mentioned in https://github.com/Regalis11/Barotrauma/issues/12734, I wonder if it could just be that the low density combined with the drag of the water makes the shell slow down so rapidly it seems like it didn't inherit the sub's velocity?

**Comment by BlackMoons** [comment]
Iv seen it happen with regular depth charges too. Try it in the sub editor, Sink at max rate and fire a standard depth charge. 

Maybe its a frame behind the sub and hence at fast speeds the sub is being updated first and colliding?

**Comment by BlackMoons** [comment]
Nevermind.. Bug also due to performance fix mod causing depth charges not to update as frequently. Really wish I could play without it but mid game is low FPS and city stations are unplayable without it.
