### ISSUE TITLE
Depth charges placed in loader via sub editor do not obey density

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12734]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When putting a depth charge into a loader via the sub editor, if the depth charge has a non standard density, it is ignored by the launcher. Removing and reinserting the depth charge or inserting it ingame the depth charge behaves as expected.

### Reproduction steps

1. Make a custom depth charge with 10 density
2. Fire it backwards out the sub after placing it via sub editor. It fires off in an arch and rapidly sinks like a standard depth charge.
3. Manually place one in ingame
4. Fire it backwards out the sub editor. Trajector path is now straight. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I couldn't reproduce the issue. The custom depth charge shells seem to behave exactly the same regardless if I place them in the editor or in-game:

https://github.com/Regalis11/Barotrauma/assets/14351070/9a1fed1f-89af-41c4-bb0d-f80c148e69a6

I wonder if this could have something to do with how your custom depth charge shell has been configured? Could you post the xml or the mod here? Thanks and sorry for the inconvenience!

**Comment by BlackMoons** [comment]
Sure. Here is the XML

https://cdn.discordapp.com/attachments/1156353413559373954/1157899952186478802/turrets_thog.xml

altered from the mod https://steamcommunity.com/sharedfiles/filedetails/?id=3036314567

Its the 'Depth Charge Proximity Decoy Shell' item. 

I'll also note I have 2 loaders linked to my depth charger launcher though I dunno if they has any effect. 

Currently the density is set to 10.2 but that should still be easy to see the difference in sink rate.

**Comment by BlackMoons** [comment]
Just double checked. Loaded dugong, placed one loader, linked loader to launcher, button just as you had.

the Depth Charge Proximity Decoy Shell loaded in via the editor droped to like 45 degrees by time it left the reasonably zoomed out screen.

The one manually placed (dropped into the sub via the sub editor, but not in the launcher) and then loaded ingame, was nearly vertical (10.2 density) 

Using stable release version of barotrauma.

**Comment by BlackMoons** [comment]
Also tested: seems to fall at the exact same rate as a normal 'depth charge' does if loaded in the subeditor.

Did you edit the default depth charge object? I am wondering if the launcher somehow defaults to 'depth charge' density if an object was in the loader.

**Comment by BlackMoons** [comment]
Sorry, just found the bug is due to performance fix mod. My bad.
