### ISSUE TITLE
[Dev Version] On request of the other developer, ai even after the patch of regalis, gets stuck on ladders

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1273]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Even after the patch, ai still gets stuck on ladders. They can now use the reactor and are more responsive but still, ladder bug. As seen in the picture I linked, marcy can't climb up the ballast ladder even when commanded to. Albeit she could climb out when I spawned a mudraptor inside there, then she ran out. Otherwise despite all commands, she did not budge.

**Steps To Reproduce**
Random yet often, just fiddle around in game I guess

**Additional information**
steamy chunky slimy snotty liquid diarrhea crunchy chungus poo

And yeah, here's the screenshot.

![20190313050504_1](https://user-images.githubusercontent.com/41457828/54249337-d123df00-4550-11e9-8b7b-a89f1f868daa.jpg)

**Comment by itchyOwl** [comment]
Would be more helpful if debugdraw was enabled. But have to run more tests.

**Comment by Regalis11** [comment]
We just merged the human-ai branch earlier this week, and the patch has not been released yet. And in any case this is pretty much covered by #1034.
