### ISSUE TITLE
Swarms with a watcher cause some lag

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#12744]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

not really a bug, rather a suggestion

Watchers, accompanied by a swarm, cause too much lag for 1 creature
Once the watcher is dead, lags passes

naturally you encounter this in lategame on laggy t3 sub with big crew, but i don't have such save file, sorry

https://github.com/Regalis11/Barotrauma/assets/122838333/aaa562d4-a8d5-4296-acdd-6f63c0ad2a73

I believe this is happening because watcher casting its gaze onActive without interval
![watcher gaze](https://github.com/Regalis11/Barotrauma/assets/122838333/ed676f6f-23f2-483d-a6b2-baf5ca8dd71d)

So, i suggest adding interval to this status effect

### Reproduction steps

~~take potato pc, go to hydrothermal wastes and find crawler swarm with a watcher~~
~~watch your fps drops from 60 to 40, and goes back to 60 after watcher is dead~~

1. quicktart any sub
2. lock and godmode your sub
3. spawn some crawlers (idk what max number of crawlers can be in a swarm, let's say 20)
4. spawn some crew, let's say up to 9 (recommended for typhon 2)
5. remember fps
6. spawn a watcher in the swarm and watch how fps drops
7. kill the watcher and watch fps goes back

i'm not sure if this would work on good pc
and i can't say what is too much fps drop, but i think watcher shouldn't eat as much cpu as an entire swarm

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/411c12a28ae45342fc68eae3344306ce7b2618b0 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4488/commits/ec35ad89af9ca8f209d85b3d700e5b9c6b6dd9e4

FPS was stable and watchers gaze is applied correctly.

No issues found
Closing ticket
