### ISSUE TITLE
Duplicate Commando talent name

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12749]
### What happened?

Similar to #12066, in the [Language]vanilla.xml, there exists two versions of <talentname.commando>. In English there are "Commando" and "Expert Commando", presumably left over from the talent rework (0.20.14.0). This means that either names can appear randomly. I am guessing that the intended name is "Commando", since the identifier is now `commando`, and the "Commando" name was added to the text file after the talent update.

Seems to affect all languages.

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/278dd971d00a3da8f958aab81fcbf2c5493c5c66
