### ISSUE TITLE
Pump particle effects leave ballast tank at high speeds

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12742]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When descending quickly (constant speed, no acceleration), particle effects from pumps seem to be displayed streaking 'back' from the pump and will end up leaving the ballast compartment completely.

### Reproduction steps

1. Fill sub ballasts and descend quickly
2. Activate pump to add more water and watch particle effects streak away. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/c19bdcffd7706b4b7b2805824d3933a9fc21c35b

Tested with steps above.
Next room need to be flooded for the bubble s to be visible.

https://github.com/Regalis11/Barotrauma/assets/8488224/a5209b0e-57f5-46e7-9498-52680e649bef

**Comment by Regalis11** [comment]
I'm not entirely sure if that's the same issue @BlackMoon meant. To me it looks like the particles aren't leaving the hull, they just partially clip through the walls (they might have a too small collision radius?). It also seems like the particles behave that way regardless if the sub is moving or not, and the report was specifically about diving fast.

**Comment by Regalis11** [comment]
But anyway, I increased the collision radius in https://github.com/Regalis11/Barotrauma-development/commit/5af91152f75b3253a02f3ede182bd2c0ae280666 to fix that specific issue, regardless if it's the same one the report is about.

**Comment by BlackMoons** [comment]
Maybe the pump bubbles should just inherit the ships velocity, then they would only move normally (a tiny bit up) regardless of sub speed?

**Comment by Regalis11** [comment]
They do inherit the velocity of the sub, just like all particles emitted by things inside the sub.

It just occurred to me that this sounds similar to your earlier report [about depth charges not inheriting the velocity](https://github.com/Regalis11/Barotrauma/issues/12735) - you don't happen to be using the "performance fix" mod still? It's known to cause quite a lot of problems, including things not inheriting the sub's velocity properly, so it could explain why you're experiencing this.

**Comment by BlackMoons** [comment]
Yea. Sorry, Still using performance fix because the game is literally unplayable on my 3.5ghz cpu with 1060GTX video card without it. Especially when a city/colony outpost is loaded. (Or doing any ship-vs-ship combat. And by that I mean the other ship just existing = consistent <10fps without performance fix)

Really wish there was an option just to make city's.. Not exist, or smaller, or not have unneeded NPC's

Arn't the particles moving in the video you posted though? or is that due to particles having 'drag'?

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

No issues found
Closing ticket
