### ISSUE TITLE
Circuit Box: Error When Deleting a Circuit Box and Undoing it.

### ISSUE THREAD

**Issue by CRedinger** [Regalis11/Barotrauma#12751]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you delete a circuit box with components wired inside, then hit ctrl+z or the undo button, you will get an error. Instead of getting your circuit box back, it will be replaced with a new one with nothing in it. If you then run the sub in test mode, the contents of the previous circuit box will spill out into a pile. Back in the editor, you will find some of your components. If you delete them all, more will appear. If you keep deleting them all, eventually they will have all appeared and it will stop. 

### Reproduction steps

1 - Wire up a circuit box with several internal components.
2 - Delete the circuit box
3 - Say "Oh no, that's not what I mean to do!"
4 - Hit ctrl+z
5 - Uh oh, error!
6 - Hit that big triangle test button and watch your hard work spill out onto the ground. 😢

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Sub Editor

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Cloning entity "Circuit Box" failed. {The given key '49' was not present in the dictionary.}
   at Barotrauma.Items.Components.CircuitBox.CloneFrom(CircuitBox original, Dictionary`2 clonedContainedItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 0
   at Barotrauma.Item.Clone() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1332
   at Barotrauma.MapEntity.Clone(List`1 entitiesToClone) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 421
```

**Comment by Rokvach** [comment]
Tested, the workaround works correctly, can be merged and closed.
