### ISSUE TITLE
Broken shadows (lighting artifacts)

### ISSUE THREAD

**Issue by AlterMoonsy** [Regalis11/Barotrauma#12757]
I started noticing these visual bugs after the last update. I've never seen this before. Do I have something with the settings, or is it a bug? Has anyone ever met with such a thing?

![photo_2023-10-04_16-35-40](https://github.com/Regalis11/Barotrauma/assets/146962537/480553f8-cc6e-485c-bdb3-979ae64db9b8)
![photo_2023-10-04_16-44-06](https://github.com/Regalis11/Barotrauma/assets/146962537/5f76ca64-5543-4b59-a004-b41e00ae9bf8)
![photo_2023-10-04_16-45-29](https://github.com/Regalis11/Barotrauma/assets/146962537/a4a0f142-b39c-4921-8e98-9e860f3232e8)
![photo_2023-10-04_16-47-37](https://github.com/Regalis11/Barotrauma/assets/146962537/68b5df10-66db-40b1-9e27-f50e1745fd27)
![photo_2023-10-04_16-46-52](https://github.com/Regalis11/Barotrauma/assets/146962537/5ac83589-c33c-4d15-806f-ab76a59dfa57)
![photo_2023-10-04_16-46-12](https://github.com/Regalis11/Barotrauma/assets/146962537/20493e0c-bcce-42a7-ba69-2624bf0304f4)

**Comment by BlackMoons** [comment]
Can confirm seeing these as well. One of the things that seems to trigger it is when a light can see a duct block. The artifacts also change as duct blocks open/close. The bright ultra narrow lines on my ship all go from light sources to duct blocks. Moving the light a few pixels makes the error move with the light, moving any duct blocks cause the error to change slightly and sometimes disappear/reappear.

**Comment by Rokvach** [comment]
Tested most of the subs and places I've previously seen these, all seem to be fixed now. Working correctly, can be merged.
