### ISSUE TITLE
Vanilla monsters' OnDamaged effects don't work

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12754]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Many of the vanilla monsters have StatusEffects that make something happen when a specific limb takes damage: charybdis should flee when taking enough damage to the mouth/head and fractal guardians, molochs and latchers should emit particles and play sounds when hit on vulnerable parts.

This seems to have been broken since https://github.com/Regalis11/Barotrauma-development/commit/b68cf8038c91fc006ed04d511c58ed4124d9b597: the effects don't configure a target type, and that commit changed the logic so that Character's status effects now don't execute if they don't target anything.

### Reproduction steps

- Shoot a railgun shell or a nuke at the charybdis's mouth, notice it doesn't escape
- Shoot at the fleshy part under moloch's shell, notice lack of sounds and special particle effects.
- Same with latcher's abdomen and fractal guardian's head.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested
Testing notes in: https://github.com/Regalis11/Barotrauma-development/pull/4519
No issues found
Closing ticket
