### ISSUE TITLE
Even if the container is inaccessible, players or BOTs can still drop items from inside

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12756]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I made a mod for testing, look into the following xml:
```xml
<Item identifier="smg2" variantof="smg">
  <ItemContainer DrawInventory="false" AllowAccess="false" AllowSwappingContainedItems="false" AllowDragAndDrop="false" SpawnWithId="smgmagazine" />
</Item>
```
When a bot empties an inside magazine by firing, the bot will drop the inside magazine although container is inaccessible.

Not only that, some hackers can force the execution of 'drop' on the client-side and drop all pellets from a canister shell.
https://github.com/Regalis11/Barotrauma/assets/73634685/ee56e76b-3e5d-4caa-ae29-1e61b3be6372

The following lua code is what "luat droppellets" did in the video.
```lua
local item = Character.Controlled.Inventory.FindItemByIdentifier("railguncanistershellpellet", true)
if item then
    item.Drop(Character.Controlled)
end
```

### Reproduction steps

1. Enable the mod:  [Bug test.zip](https://github.com/Regalis11/Barotrauma/files/12803657/Bug.test.zip)
2. Host a server
3. Gve the bot a "smg2"
4. Spawn some crawlers and command the bot to defense
5. When bot launches the last round with smg2, it will drop the inside smg magazine

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4520/commits/af084fa81dbebe9eb9d1ad64565b0587063073b0

Used test mod provided.
Tested bots using different inventories.

No issues found
Closing ticket
