### ISSUE TITLE
[Unstable] Murder mystery weapon variants spawn in containers

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12758]
### What happened?

In unstable, the murder mystery weapons are variants of normal items. They have the <price> and <fabricate> parts removed, but the preferred container isn't removed, so these items can spawn naturally

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/121aa9e6-b410-402f-afd0-537c919273f9)

### Reproduction steps
1. Play campaign and loot wrecks/outposts, eventually find one of the murder mystery weapons

### Version
1.1.14.0 (Unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4504/commits/5dbdcc2a687a8a233f63c6ef88a97016b3a5de18
