### ISSUE TITLE
"Received a traitor update when not controlling a character." when ending a round in freecamera

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12763]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ending a round in freecamera after receiving traitor objectives throws a "Received a traitor update when not controlling a character."

### Reproduction steps

1. Play on multiplayer campaign with traitor probability at 100%
2. Wait until you receive the traitor mission
3. Hit Esc and return to lobby
4. Notice console error

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/004f60b8b8c0b0b6458edcb3217e65705475316e by changing this to a warning in release builds.

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/eab0497fe9d11477c4b3afb3134ffe0d3eb56eb1

No issues found
Closing ticket
