### ISSUE TITLE
Set camera shake from status effects which targeting a character will cause all players' cam shaking.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12765]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

There's a workaround that add a conditional with IsLocalPlayer="true" to StatusEffect

### Reproduction steps

1. Make a mod and test

### Bug prevalence

Just once

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

Tested in MP with 2 clients
Cymballs apply screen shake on  characters within 5m radius

No issues found
Closing ticket
