### ISSUE TITLE
Respawn shuttle spotlight shines through level roof

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12762]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The spotlight of the respawn shuttle shines through the roof of the level and you can even hear the engine humming

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/fe77a998-88db-43ef-9d3e-5a058d343e76)

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d795799b243720d2e3c0420a96196e49647cb2a

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

Respawned couple times with different shuttles

No issues found
Closing ticket
