### ISSUE TITLE
Selfkills of mobs (hull shrapnel)

### ISSUE THREAD

**Issue by PlasmaUwU** [Regalis11/Barotrauma#12767]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Recently, the shrapnel from the hull was fixed (Thanks), but this was followed by mistakes: If the monster is inside the submarine and bites the hull hard, then it will be hit with shrapnel, and hard, half to death...

### Reproduction steps

1)Quick start
2)Spawn madraptor veteran / another strong mob inside the submarine
3)Go to another room and turn on "Freecamera"
4) Watch as the monster gnaws at the hull and hits it with shrapnel, again and again, and then kills it and tears it to pieces

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, this can happen if they attack inner walls which are connected to a space which doesn't have a hull i.e. areas which throws shrapnels when attacked. 
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/659670ff-e084-4835-aa96-be2f307cd74b)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/54fd5ce073da81a90edb892b13b46ce5a8ce4586

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/eab0497fe9d11477c4b3afb3134ffe0d3eb56eb1

Used steps provided.
Enemies didn't get damaged, characters did.
No issues found.
Closing ticket.
