### ISSUE TITLE
 Stun Baton doesnt currently accept modded batteries. 

### ISSUE THREAD

**Issue by SquidingTin** [Regalis11/Barotrauma#12761]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

TCurrently some battery powered weapons such as the stun baton doesn't work with modded batteries (though can hold them in their inventory), this is due to the weapon not using the mobilebattery tag but instead the two battery identifiers. This issue most likely came about from fulgurium doing more damage and them not thinking about item exclusions (excludedidentifiers), this is a simple fix and wouldn't cause any issues, just a lot of testing on what items have this issue. 
(This issue might happen with a lot more then just the stun baton)

### Reproduction steps

1. put modded battery into stun baton
2. hit enemies with stun baton
3. not stun happens

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/806a1d07e2a390553afaa31a782807517f5151e6 (commit in our private repo)

**Comment by Ek-Videogames** [comment]
With the addition of custom 'max-hp' amounts quite some time ago, I would say the method of targeting contained item by unique-ID is entirely obsolete (other than being possibly kept for reverse compatibility reasons) so there's not really any reason not to move to using the 'unified' tag for everything, other than certain status-effects that change how an item behaves based on the unique item. (IE stronger attacks from fulgurium batteries in stun baton, or the health benefits from oxygenite tanks in suits)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

No issues found
Closing ticket
