### ISSUE TITLE
Flashlight in weapons is pointing wrong way and visual glitch

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12778]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Flashlight is pointing wrong way first when holding a weapon and facing left.
Resets after turning right.

~~Some visual issues when crossing characters turning point while aiming.~~

https://github.com/Regalis11/Barotrauma/assets/8488224/7aafc0e7-4eba-487b-b5f0-9362498e9ed5

### Reproduction steps

1. Quickstart
2. Get a weapon with flashlight slot, i used shotgun
3. Get a flashlight
4. Equip weapon and face left
5. Attach flashlight to weapon, easiest was with number key
6. ~~Visual glitch can be seen if you move mouse slowly over characters turning point while aiming (Flashlight and crosshair is on opposite side)~~

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.15.0)

### Which operating system did you encounter this bug on?

Windows/Linux

**Comment by Jasontti** [comment]
Backwards pointing does not happen in current steam stable, but those small glitches do.

**Comment by Regalis11** [comment]
Fixed the mirrored flashlight in https://github.com/Regalis11/Barotrauma-development/commit/72105c9c67e50b699f7717aeb217f253e233fd2b. Didn't address the issue of the light and the crosshair being off for one frame when turning, that's a separate (lower-prio) issue imo.

**Comment by Jasontti** [comment]
Separated visual glitch to https://github.com/Regalis11/Barotrauma/issues/12782

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4526/commits/eab0497fe9d11477c4b3afb3134ffe0d3eb56eb1

Used steps above.
No issues found.
Closing ticket
