### ISSUE TITLE
"Glass crack" Sprite changed

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12776]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The sprite for the "glass crack" changed recently, and now it has a big hole in it
It was used because it didnt have a big hole in it

`Barotrauma/Content/Map/Outposts/AbandonedOutpost/HumanEnemyA.png`

![HumanEnemyA](https://github.com/Regalis11/Barotrauma/assets/73229309/1729dc22-3154-404e-817a-974861fe7a2b)

How it was
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/3cef43f2-09bb-4f86-9ac4-dbaab3ac86ed)
How it is now
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/e35643b2-0a5f-45f0-aabb-c2fda907e96f)

### Version

v1.0.21.0

**Comment by Rokvach** [comment]
Iirc it was changed because we didn't own rights to use the old crack texture, but that change was done ages ago and not recently 🤔

**Comment by Regalis11** [comment]
Not a bug, it was intentionally changed back in February.

**Comment by Regalis11** [comment]
Although, on a second though, I think we might want to adjust this because the hole makes this sprite pretty difficult to use anywhere.

**Comment by ubertpendragon** [comment]
There was a sprite with hole and a sprite without hole, both got used the problem is that they swapped positions

**Comment by NamAnhLe** [comment]
Replaced with a new cracked glass sprite in 01a0cb0

**Comment by Regalis11** [comment]
The sprite still has a hole on it, moving back to ToDo

**Comment by NamAnhLe** [comment]
Patched the hole in 7a583d8

**Comment by Regalis11** [comment]
Tested, couldn't spot any issues
