### ISSUE TITLE
Crouching on ladders misaligns firearms

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12773]
### What happened?

When aiming guns while holding on a ladder, pressing the crouch key causes the weapon to aim a bit above the mouse reticle.

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/21d6f1d2-da1e-46b8-b029-632811a1bc01)

(I don't know whether this is an unstable-only issue, but I suspect it is)

### Version

1.1.15.0

**Comment by Regalis11** [comment]
Seems to happen in the stable version as well, removed [unstable] from the title

**Comment by Regalis11** [comment]
It seems this has been fixed with the changes in https://github.com/Regalis11/Barotrauma-development/pull/4418 (PR in out private repo)
