### ISSUE TITLE
[Question] How to mirror the walls?

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1277]
**Description**
On vanilla submarines there are walls that are inverted or mirrored. How to do?
At the bottom of the wall with the submarine "Humpback", and on top of the standard.
![image](https://user-images.githubusercontent.com/33912761/54353755-e4749e80-4665-11e9-8b76-bf8ba83da676.png)

**Comment by Regalis11** [comment]
Ctrl+N to mirror horizontally, and Ctrl+M to mirror vertically. We really need to add a button for flipping the entities into the editing panel, as now there's really no way to know how it is done...

**Comment by Regalis11** [comment]
The editing panel now has buttons for flipping structures/items, and the hotkeys are mentioned in the tooltips for those buttons.
