### ISSUE TITLE
[Unstable] Latcher's tongue attack doesn't work

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12783]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Latcher's tongue attack gets interrupted immediately after it fires the tongue.

### Reproduction steps

1. Teleport to the abyss
2. Spawn a latcher
3. Wait for it to do the tongue attack

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4530/commits/39e6eab20fd66cdd8d080923a08319473a8d0f40

Latcher attacks work properly.
Got couple times where it missed a moving sub and one where it just licked the hull lol.

Tested also that this worked https://github.com/Regalis11/Barotrauma-development/pull/4368

No issues found.
Closing ticket.

**Comment by Jasontti** [comment]
Mistakenly tested in SP when i thought was in MP
Spineling genes don't spawn visible projectile if character is in hull, but target is out.
It still does damage when it contacts another surface
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/f9c5b6d3-4a69-4f35-a29e-45df7a379e49)

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4533/commits/cc5bce577710810814b0f7871ed14a64d929bada

No issues found.
Closing ticket.
