### ISSUE TITLE
Spamming ragdoll key bind causes the collider to ascend.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#1278]
Best way to reproduce this is to bind the ragdoll key to mousewheel and go nuts, though I've managed to replicate it with the spacebar if I spam fast enough. Seems to also let you clip through walls.

**Comment by Regalis11** [comment]
Most likely caused by #904

**Comment by Regalis11** [comment]
Fixed in v0.8.9.6
