### ISSUE TITLE
WARNING: Tried to restore enabled packages multiple times/without performing a backup

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#12780]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This is related to, or perhaps this _causes_ #11325
I think every time the mod download progress bar freezes, the console shows the same warning. The second part of the warning, where it says "an exception was thrown then attempting to copy" doesn't always appear.

On subsequent connection attempts, the server either asks the client to subscribe again (not 100% sure about this one), download a mod/mods directly or just allows the client to connect. It's random.

Note: I even verified the integrity of game files before trying to join that server. There's literally no way to prevent this, as far as I know.

![Barotrauma_XqSZRCZsfa](https://github.com/Regalis11/Barotrauma/assets/10529134/a441c682-e723-4047-b69f-bb7d6008003f)

There seem to be 2 different issues caused by this warning, whether related or not:
The first one is when mods never finish downloading.
The second one is when the server asks you to download mods directly, which often happens after the previous one, but not always.

### Reproduction steps

1. Connect to a server with lots of mods
2. Click "Subscribe" when asked to download mods
3. The downloads will never finish, resulting in the aforementioned warning.

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This warning shouldn't actually cause any issues in this situation: it just means the game tried to restore the content packages that were enabled before you started joining the server, but that had already been done successfully. In some situations, such as when something goes wrong when joining a server, it may "double-check" that the previous packages have been restored, but if they are, it does nothing.
