### ISSUE TITLE
Energy drink grants negligible hyperactivity

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12786]
### What happened?

Energy drinks, which are available in vending machines, have the description

>Mantis Energy keeps you skittering from dawn till dusk!

However, the amount of hyperactivity the item grants is extremely small. 7.5 hyperactivity is a movement speed boost of 0.4375%. Consuming multiple energy drinks is an option, though to even reach 25% of the strength of one dose of meth would require 14 energy drinks. Not only is this super expensive, but because energy drinks have a chance to grant nausea, ironically, taking multiple energy drinks is more than likely to slow you down.

Energy drinks would be more interesting to use if they actually had a noticeable positive effect. Currently it's basically just nausea in a can.

**Comment by BlackMoons** [comment]
It gets worse, since 7.5% also wears off in 7.5 seconds yet it takes 3.3 seconds to drink it.

**Comment by Vykn** [comment]
You can use the health gui to consume it instantly, but yeah

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/fa72e1780a8696cf11be143008770c4b15aa13e1
