### ISSUE TITLE
Genes are not destroyed upon death if character does not respawn mid-round

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12784]
### What happened?

When dying, genes usually are destroyed. However, in multiplayer, if a character with genes dies mid-round, then chooses not to respawn, their gene splicer will be placed in their duffle bag upon level transition, with the genetic material still intact. It was expected that genetic material would be destroyed upon being placed into the duffle bag.
Genes are destroyed as expected if the character respawns mid-round.

### Reproduction steps

1. Load a multiplayer campaign game
2. Give a player a gene splicer with genes
3. Make that player deceased
4. Transition levels (dock or undock)
5. Observe that their duffel bag contains their intact genetic material

### Version

1.0.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/32c9df0da546b01a4e2be8d8b8b45200a0165bd5

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

Tested in different gamemodes
Normal in round respawning and after round respawn

No issues found
Closing ticket
