### ISSUE TITLE
Some hackers and bots can drop the non interactable item

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12787]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I had a non interactable item in the container, but there was a hacker appeared in my server, he dropped the inside item and broke the game rule.
I found bots also can do that.

### Reproduction steps

1. select sub editor
2. place a non-interactable smg magazine and put it inside the smg
3. start the game
4. give a bot the smg
5. let the bot to fire and empty the magazine
6. the bot will drop down the smg magazine

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ccdc656c438cafaf3bbdf315ca37fc0a5c0380d4

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/af084fa81dbebe9eb9d1ad64565b0587063073b0

Used test mod provided.
Tested bots using different inventories.

No issues found
Closing ticket
