### ISSUE TITLE
Crosshairs one frame visual glitch

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12782]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a separation ticket for https://github.com/Regalis11/Barotrauma/issues/12778

Visual issues when crossing characters turning point while aiming.
Ticket above has video.

### Reproduction steps

1. Quickstart
2. Get a weapon with flashlight slot, i used shotgun
3. Get a flashlight
4. Visual glitch can be seen if you move mouse slowly over characters turning point while aiming (Flashlight and crosshair is on opposite side)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

1.1.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ba210f4cad922e61227b0fbcd45fa1d5fc48d94

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

Much better and there is no stutter when crossing the turning point.
However there still is small blip on the opposite side.


https://github.com/Regalis11/Barotrauma/assets/8488224/44170f0f-98e9-44e1-82e6-8fcbcbb9a301

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/f2801dfd908f7b4b5906daf654164e0f3f5b287e. Kind of a hacky workaround, the crosshair is just briefly hidden when turning around. I think it works well enough though, it's very hard to notice compared to the crosshair jumping to a different spot.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/f2801dfd908f7b4b5906daf654164e0f3f5b287e

Yes, it works well enough. Hardly noticeable when paying attention and not when there is action going on.

No issues found
Closing ticket
