### ISSUE TITLE
Harbringer of Honks event can't be completed

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12791]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The objectives don't complete no matter what you do. Seems to have been caused by the changes in https://github.com/Regalis11/Barotrauma-development/commit/7315fb8235830f6fe779ce4dec06e19e56e38584

### Reproduction steps

1. Start an mp round
2. `triggertraitorevent harbringerofhonks`
3. Try to complete the objectives

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
