### ISSUE TITLE
Backpacks can be placed in cargoscooter

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12796]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Many backpacks can be placed in side cargoscooter.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/4ddf05a7-50d5-4972-9936-68ed4b5a6c26)

### Reproduction steps

1. Get cargoscooter
2. Get backpacks
3. put backpacks in cargoscooter

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

1.1.15.0 dev

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/88d5b069d60135c3dc0f96d83f55709cfe433788

**Comment by Alpharius-30-milenium** [comment]
![image](https://github.com/Regalis11/Barotrauma/assets/60311003/8f2d03aa-bf72-43d7-8d71-d4db5e19bb7f)
Backpacks can be also put in cabinets

**Comment by Alpharius-30-milenium** [comment]
Medical compartments aswell
![image](https://github.com/Regalis11/Barotrauma/assets/60311003/366e48d6-a302-4023-b35c-3473dca24c4a)
![image](https://github.com/Regalis11/Barotrauma/assets/60311003/97acced6-9107-4dc4-8afb-4936efc14bab)
![image](https://github.com/Regalis11/Barotrauma/assets/60311003/0eca7e2b-ec6d-4241-b090-42b9ba78360a)

**Comment by Jasontti** [comment]
Located /content/map/outposts/OutpostItems.xml
opdeco_medcompartment1
opdeco_medcompartment2
opdeco_medcompartment3
opdeco_cabinetsdorm

Also opdeco_trashcan, but that could be argued to be left as is

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4546/commits/c160750f9ba9bc68072e35bd925aa2741429902a

Medical cabinets and loose vents were decided to be left as is

No issues found
Closing ticket
