### ISSUE TITLE
Sufforin bug?

### ISSUE THREAD

**Issue by Zolejj** [Regalis11/Barotrauma#1279]
Okay, i just realised that if i inject sufforin into myself, i can be saved by equipping a mask and a suit(with oxy in them). It stops the oxy draining effect, and if i took only one sting i can even regenerate my oxy bar.
v0.8.2.3

**Comment by AbominationBanisher** [comment]
Replicated this bug in the alpha version, it does not work.

Keep in mind that Regalis is no longer updating the legacy version, which makes reporting legacy bugs obsolete. Have a good day.

**Comment by Regalis11** [comment]
This was actually intentional: it's possible to counteract the effects of sufforin by using some additional source of oxygen (liquid oxygenite, an oxygen mask, etc).

**Comment by NilanthAnimosus** [comment]
its actually because sufforins oxygen drain is based on availableoxygen for its drain, which you can reverse by equipping both of those at once, an oxygen mask on its own will not stop it, nor will a diving suit, its literally the requirement of both at the same time.
