### ISSUE TITLE
No outpost security in Jailbreak in mission mode 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12792]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Jailbreak in mission mode (under "Outpost") is broken

AI doesnt react to prisoners escaping

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ebeb6db7-3f17-40f9-ba9e-af2fd00e680d)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ae718f79-1702-490e-9d8f-7fd052fdb5bb)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ccdadcf9-b477-430e-a814-60b4b0c64660)
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/767dc036-a326-4d7e-8697-cc166c8f4b79)

Also outposts don't have a faction assigned so all the decorations are missing
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/6edb15be-d089-4ba8-8078-505d760b6908)

### Version

Unstable (v1.1.14.0)

**Comment by ubertpendragon** [comment]
Modded Jailbreak (with Husk prisoner), but despite the alarm going off and security being hostile, they do not react

https://github.com/Regalis11/Barotrauma/assets/73229309/752c3eac-ed0c-4555-a2e2-763ff857eb67

**Comment by ubertpendragon** [comment]
Tested on vanilla Jailbreak in campaign, guards still flee

**Comment by Regalis11** [comment]
Yep, I noticed that too after I fixed security not spawning. Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4539

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/9672b64ba4b3a96e9eb9950f7bc41d148816e3c4

Testing procedures noted in https://github.com/Regalis11/Barotrauma-development/pull/4539

No issues found
Closing ticket
