### ISSUE TITLE
[Unstable] Alienwriting conditionals bug

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12808]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Barotrauma_JUy8GzWRhZ](https://github.com/Regalis11/Barotrauma/assets/42521948/36d3d46d-6904-45f4-a9cb-d594d5c4d702)

So while running tests via `quickstart` command for my submarine I encountered this weird bug complaining about alien writing on walls (prb ones ya can interact with too). I tried to get it to happen again with multiplayer ruin missions and `leveleditor` but I couldnt get it to reproduce it.

### Reproduction steps

1. start level with `quickstart`
2. roll ruins
3. get bug in console
(Once again I could reproduce it in multiplayer missions with ruins or `leveleditor` for some reasons but it might be good idea to try em too)

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### -

quickstart command

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61b5fa4b03cd66dfafaf858a8045dd089a3b9763

**Comment by Rokvach** [comment]
Tested in commit https://github.com/Regalis11/Barotrauma-development/commit/61b5fa4b03cd66dfafaf858a8045dd089a3b9763, didn't encounter this error message. Tested in quickstart, leveleditor and ruin mission mode. 

Can be merged and closed.

**Comment by Rokvach** [comment]
Also made sure that the error messages still works in areas they should work
