### ISSUE TITLE
[Unstable] Cabinets weren't affected by storage rework

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12800]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

basically it still acts as in unstable, doesnt have special slot and allows putting storage containers in it!
![image](https://github.com/Regalis11/Barotrauma/assets/42521948/20917997-e9b8-4cc1-bad2-6b8934826f06)

### Reproduction steps

1. go into sub editor
2. place cabinets item
3. open it
4. put storage container in it

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by SquidingTin** [comment]
this also goes for wrecked versions of those items last i checked

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1fd764f07177a3a0b18d06189e4c225c86010771

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/c160750f9ba9bc68072e35bd925aa2741429902a

Medical cabinets and loose vents were decided to be left as is

No issues found
Closing ticket
