### ISSUE TITLE
You can reduce the cooldown to 1 second for a melee weapon by equipping it quickly and repeatedly if the weapon has a reload of more than 1 second.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12804]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title says.

### Reproduction steps

1. set reload of boarding axe from 1.2s to 5.0s
2. attack with the boarding axe
3. unequip and then equip it
4. notice reload is far less then 5.0s because it has been reset to 1s

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6a3c7526eefc0d05b44c1b70cdce51b8be0bb21

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

Tested with modification above, dual wielding smaller melee weapons and other weapons.
Everything seemed to work well together.

No issues found
Closing ticket
