### ISSUE TITLE
Camel hulls issue

### ISSUE THREAD

**Issue by Maks300091** [Regalis11/Barotrauma#12805]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The walls of the camel's hump do not allow water to pass through when ruptured

### Reproduction steps

1. Start new single game
2. Buy camel
3. Found this issue
4. Check it in submarine editor

https://github.com/Regalis11/Barotrauma/assets/105166144/aca5a119-3b16-4618-9bd4-3a4e8dfe7915

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b0d3f8c3c3b493d68a69a33733eaeb738036d729 (commit in our private repo)
