### ISSUE TITLE
[Unstable] Outpost junction boxes deteriorate and can be fried with ciruits 

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12809]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The old bug of deteriorating junction boxes on outposts is back! Now with forced overvoltage! Any output boosting circuit now can afford to fry electronics of outpost!

my mods (although it is easily reproducable without em):
![Barotrauma_9yVGqlGrJ2](https://github.com/Regalis11/Barotrauma/assets/42521948/1e9386f3-7b56-4fde-a178-d851f9909fcc)
save file:
[Save.zip](https://github.com/Regalis11/Barotrauma/files/12906719/Save.zip)

### Reproduction steps

1. install all mods from previous section for correct launch and load save file (launching without shouldnt affect bug tho)
2. go to outpost
3. observe deterioration of junction boxes
optionally: wait till 1 junction box breaks and will cause chained overvoltage because of player submarine with custom circuit!

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This seems to happen because the reactor is set to manual operation in the save, and the output is way too high relative to the load.

**Comment by PanmanS** [comment]
Well if we talking about player submarine - yes inderd, because it uses overvoltage automatic control system


But whole point was that before junction boxes on outposts while not being invincible - were much-much more resistant - now even a slight whif enough to kill junction boxes

**Comment by Regalis11** [comment]
As far as I know, there's never been any special resistances on junction boxes in outposts. They just don't deteriorate spontaneously, but if I'm not mistaken, overvoltage has always damaged them.
