### ISSUE TITLE
Suits with multiple, unrestricted inventory slots allow for infinite oxygen

### ISSUE THREAD

**Issue by drunken-dwarf** [Regalis11/Barotrauma#12801]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Given the following XML:
`<StatusEffect type="OnWearing" target="Contained,Character" UseHullOxygen="false" OxygenAvailable="1000.0" Condition="-0.3" comparison="And" targetslot="0">`
`  <Conditional InWater="true" />`
`  <RequiredItem items="oxygensource" type="Contained" />`
`</StatusEffect>`

**RequiredItem** checks the entire inventory while **Condition="-0.3"** only affects the item in the **targetslot**.
If you then put an oxygen tank in e.g. slot 1, **OxygenAvailable** will still work as the condition is met.

### Reproduction steps

1. Copy PUCS XML
2. Remove `<Containable items="chem,medical" />` from subcontainer
3. Wear PUCS and put oxygen tank in the slot normally designated for chem/medical
4. Infinite oxygen (and beeping)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux

**Comment by PanmanS** [comment]
There is easier way to reproduce it

1. download and install [EHA](https://steamcommunity.com/sharedfiles/filedetails/?id=2764968387) and [EHA FUEL FOR FIRE](https://steamcommunity.com/sharedfiles/filedetails/?id=2976013863) mods
2. load azimuth, spawn CBRN suit and put 1 oxygen tank in it via sub editor
3. equip CBRN suit, let it consume some oxygen % and then put it free slot above
4. start fires with `fire` command in same room and wait till oxygen equals 0
5. observe issue


![Barotrauma_rtu3tOsUId](https://github.com/Regalis11/Barotrauma/assets/42521948/d8bef628-0dfe-44e8-93c6-5fc40663b18e)
![Barotrauma_4Ml81edA3H](https://github.com/Regalis11/Barotrauma/assets/42521948/223cb714-1369-47c7-b661-5fb750370715)

**Comment by Regalis11** [comment]
Thank you for the report! This is not a bug: if the RequiredItem doesn't specify a slot, it checks all contained items. If you want to check a specific slot, you need to specify the target slot:

`<RequiredItem items="oxygensource" type="Contained" targetslot="0" />`
