### ISSUE TITLE
Azimuth's spotlight periscope is too high

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12819]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Azimuth's spotlight periscope is too high, causing characters to levitate when using it.
![20231015130642_1](https://github.com/Regalis11/Barotrauma/assets/104994469/b935e0a9-fb56-4f29-9597-60f0d7d3aa3f)

### Reproduction steps

1. Open azimuth in submarine editor.
2. Order bot to man the searchlight (as it's possible rn)
3. Observe it levitate.

Alternatively tell your character to not move and make them man the spotlight.
Switch to another character and observe the character levitate.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b6dfcc1426120414cdd31a3b8555b1a68929a8c1 (commit in our private repo)
