### ISSUE TITLE
You can order bots to man the searchlights

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12818]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can order bots to man the searchlights, whether or not it has a periscope does not matter, they will also inform you that they are incapable of loading more ammo into the searchlight.
Additionally spotlight will be referred to as a gun in the order voiceline, if it is for whatever reason intentional.

![20231015130702_1](https://github.com/Regalis11/Barotrauma/assets/104994469/a8f7279e-6c26-463f-a589-fcc77639d085)
![20231015130648_1](https://github.com/Regalis11/Barotrauma/assets/104994469/1ff6f8d0-89ce-46f6-8d01-51964dc5332d)

### Reproduction steps

1. Open Azimuth in submarine editor.
2. Order bot to man the lower spotlight.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/415786524d0b7ca7cf076468ca2b5ec4186616ec

**Comment by Rokvach** [comment]
Tested on commit https://github.com/Regalis11/Barotrauma-development/commit/a0c183f969f1feb5fa639198d1a1b79721442c83

I was still able to order bots to man the searchlights
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/8c794852-ad08-44db-92f9-8a256c8b32e6)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
