### ISSUE TITLE
[Unstable] Foreshadowing event is too rare

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12810]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've noticed this "bug" after the urban expanses update but never decided to report it because I thought I wasnt lucky enough but after long enough observation I can safely say it is busted. In Pre-Urban Expanses this event was popping up here and there which was amazing since it leads to ARG you guys created but now it is almost impossible to meet it if possible at all.

### Reproduction steps

1. Start campaign
2. Hug every single trashcan on outpost (because that's usually when it triggered before me even though event itself doesnt have correlation to it)
3. Pray and hope to get it
4. Go to next outpost
5. Repeat previous steps

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This event has been intentionally disabled because the ARG has ended.

**Comment by PanmanS** [comment]
But while ARG is over, it is still possible to get role in discord, so why not turn it on again?

**Comment by PanmanS** [comment]
Lmao okay, got it!
