### ISSUE TITLE
Navterminal not recognising docking ports when wired through Wi-Fi in Circuit Boxes

### ISSUE THREAD

**Issue by xolophreny** [Regalis11/Barotrauma#12812]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Navterminal doesn't bring up docking aids and the dock button when connected to the port using Wi-Fi Components inside Circuit Boxes, though signals pass through and docking happens

### Reproduction steps

1. Connect a navterminal's toggle_docking to a Wi-Fi Component in a Circuit box
2. On a shuttle, connect a docking port to a corresponding Wi-Fi Component in a Circuit Box
3. Observe inability to dock/undock in the navterminal
4. Send a button signal down that chain and behold docking and undocking

![image](https://github.com/Regalis11/Barotrauma/assets/41170402/b461a279-9a7b-46ec-b0e2-acaf33727252)
![image](https://github.com/Regalis11/Barotrauma/assets/41170402/faf07543-fc3a-410f-91b6-f7dc1dc3b318)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/170512ca6f2c627e75c3c34273d7a516160d9d6a

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4549/commits/470e11f8e102269c229a54d80a8c85ab43c15563

Wired kastruls drone to go only through circuitboxes with wifi in them.
Same with turret controls.
Different circuitbox wirings: straight through, with components and wifi in and outside of CB.
Wired in game and in editor.

No issues found.
Closing ticket
