### ISSUE TITLE
Non percentage based ammunition stacks to just 8 inside the belt/back slot containers

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12813]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ammunition such as Revolver Rounds stack to 32 inside the cabinet and 12 inside the hotbar. Weirdly they stack to just 8 inside containers such as the Backpack. If we take into account that SMG magazines stack to 8 inside the Backpack, then revolver rounds should stack to 32 inside the Backpack to match their cabinet stack size.

On the complete other hand, you are capable of carrying up to 800 rounds of HMG ammunition inside a single Backpack slot, more on that later.

![20231015004739_1](https://github.com/Regalis11/Barotrauma/assets/104994469/b3afb0a3-01f0-4743-89c3-79f3e45d8dfd)

### Reproduction steps

1. Load Camel in sub editor.
2. Place Rifle Rounds inside a cabinet.
3. Put Rifle Rounds inside the mechanic's toolbelt.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7341fd3568ac8554b045fe761c78002ce4e533f1

**Comment by Rokvach** [comment]
Tested the stack sizes of ammunition are the same everywhere now, i.e. revolver ammo is 12 in cabinet, inventory and container. I guess this is the intended fix so working correctly. Closing.

**Comment by Rokvach** [comment]
Looks like the above comment isn't intentional, moving back to todo.

**Comment by Rokvach** [comment]
Tested again, I went through all the different ammo types and they stack properly now

i.e. Revolver rounds in player inventory or container is 12 and inside cabinets 32. 

Working correctly, closing.
