### ISSUE TITLE
Storage container GUI constantly dropping when holding two containers

### ISSUE THREAD

**Issue by Smrtonosan** [Regalis11/Barotrauma#12817]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When first equipping two storage containers, when hovering over them immediately they will overlap and the one in the right slot will constantly be trying to get down off the screen. (First as in if you do it again in the same mission? it won't happen)
![1](https://github.com/Regalis11/Barotrauma/assets/104994469/353aa44c-525d-428f-8921-36c54923beba)

When holding two storage containers, when you hover over the storage container icon, the GUI will again try to get off your screen constantly, doesn't matter whether it's the left or right one.
![2](https://github.com/Regalis11/Barotrauma/assets/104994469/9fdc1086-33ad-4cd9-a5d4-f61a58394a2f)

### Reproduction steps

1. Open submarine editor.
2. Load dugong.
3. Place two storage containers inside a cabinet. (Or just place two on the floor)
4. Equip both storage containers one after the other.
5. Hover over the storage container icons in the hud.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Easy to repro with steps provided

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c8ac918bc900a5d2b767e44f7e364beca40ae9ee

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4619/commits/c8ac918bc900a5d2b767e44f7e364beca40ae9ee

Tested case in original message.
Storage containers with different cabinets and inventory objects.
Equipping them in different order.
Movable frame hides when other inventory frames open on top of it.

No issues found
Closing ticket
