### ISSUE TITLE
Husk faction quest bug: "rescue subra" mission interrupted because the outpost changed its type

### ISSUE THREAD

**Issue by ZockerYT** [Regalis11/Barotrauma#12825]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My friends and I were playing through the campaign, then when we had almost reached ~60% of the difficulty of the location, and this is already more than half of the game, therefore outposts should not appear further without intervention. Here we began to complete quests from husks fraq, we were given a quest to free Jacob Subra, but the place where we needed to swim was located behind our location, while we were sailing to it the location disappeared due to the fact that there was an abyss monster nearby, and as a result the quest line was interrupted, It is impossible to complete the task, and it is also impossible to obtain symbiosis. The bug apparently only happened to me, due to the fact that usually up to this point the quest chain is completed, however, due to the interaction of the abyss monster with the filling of the location with an outpost after killing the monster, such strange interactions occur. Please check the interaction of the monsters of the abyss with the quest chain of the Husk Church.
Sorry for bad english, i used google translate.

### Reproduction steps

1) Start compaign
2) reach "dead wasteland", where outposts do not appear (~60-70% difficulty)
3) Do some quest from husks
4) Get quest to escape Jacob Subra from abandoned outpost
5) Outpost spawns near by Monster of abyss hunting grounds
6) 2-3 times swim arround
7) outpost die

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Did not saved
```

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/133836c9352eda92ac4bbef9ad467d4b621914a8 (commit in our private repository)

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/133836c9352eda92ac4bbef9ad467d4b621914a8

Unlocked rescuesubra mission in abandoned outpost, through the event waytoascension4
Set outpost change probability to 100% from abandoned to anything
Moved around the map many times

No issues found
Closing ticket
