### ISSUE TITLE
NPCs from creatures don't have propper ai

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [Regalis11/Barotrauma#12822]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Earlier I requested feature for NPCs that are not humans to have their ragdoll properties instead of human's, it was made but now there is new issue: these npcs lost ability to use items. On stable version npcs that are made from humanoids can use their inventory but they will lost all properties from their config file and from ragdoll file (except graphic), in unstable version they have all stuff from config and ragdoll but can't use inventory.
https://youtu.be/S4QtPQw_QOk

### Reproduction steps

1. Create custom npc
2. Add it to outpost npc list
3. Launch level editor
4. Run debugai

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Thanks for your report.

Creatures and humans use mostly different AI systems. There's been some progress in migrating features to a common base AI, which both share, but fundamentally they will always be different. The creature AI can also use items to a point (use weapons and open doors, and use ladders if they are humanoids), but they don't have the same AI objectives as humans (like extinguish fire etc).

We should allow non-humans to use the human AI though, but doing that would require refactoring and solving some presumptions in the code. And they would still have to be humanoids.

**Comment by Regalis11** [comment]
> We should allow non-humans to use the human AI though, but doing that would require refactoring and solving some presumptions in the code. And they would still have to be humanoids.

It used to work before, now it doesn't. This is a bug, moving out of the icebox.

**Comment by itchyOwl** [comment]
Ok, maybe I don't completely understand what used to work and how's that changed. However, we've assumed that player characters and NPCs are humans. Just check out all the references to CharacterPrefab.HumanSpeciesName. Especially SpawnAction. Changing that has been in my mind, but I've never had time for it.

**Comment by Alpharius-30-milenium** [comment]
> Ok, maybe I don't completely understand what used to work and how's that changed. However, we've assumed that player characters and NPCs are humans. Just check out all the references to CharacterPrefab.HumanSpeciesName. Especially SpawnAction. Changing that has been in my mind, but I've never had time for it.

Originally npcs that was made not from exactly humans but from humanoids had human ai in everything but these npcs had from their config only graphics, ragdoll parameters, pressure protection and other things was taken from human. It was changed so that humanoid npcs (not human npcs) now inherit all parameters from their ragdoll and config but they lost human ai so instead of shooting you they will try to attack you with their bodies

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e4efe401e2031294824e4986c8d942e288fe4d12

> Allow non-humans to use human AI by adding usehumanai="true" to the character config. While this hasn't been an "officially" supported feature, in previous versions it was possible to have human AIs on non-humans due to the issue #12533, and seemed to work fine. When that issue was fixed, as a side-effect it became impossible to use human AIs on non-humans
