### ISSUE TITLE
Maxupgrades cheat command does not upgrade hulls because it checks for resources

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12824]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/9dacc196-890c-4dc3-b2d4-a9646e4894b3)

### Version

v1.0.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f278a3436cc684eb1d2d16185b6e9e60c7775ad1
