### ISSUE TITLE
[Dev Version] Thicc Hat

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1282]
Is it just me, or is this hat that I took off my head and dropped onto the floor as captain, very thicc? Probably a bug.

![hat](https://user-images.githubusercontent.com/41457828/54465782-fd786f00-478d-11e9-9cd1-dd06e07f30a8.PNG)

**Comment by Regalis11** [comment]
Fixed in v0.8.9.6
