### ISSUE TITLE
Circuit Box pins aren't translated + missing translation on Supercapacitor pin

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12839]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/a7c64353-05fc-4435-8f13-3c67104670cb)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/76ef37ba-ef51-412f-a862-e536877af03d)

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

1.1.18.0 Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/667ceaf830edee7b47317da73078317ec62ff683

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/af328406-02f2-4d47-bca6-1c24ecd97c9f)
