### ISSUE TITLE
[UNSTABLE] VIP separatists will attack player for taking items off bandits from beacons

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12835]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/42521948/05166180-82fc-4055-8fa5-ed00a8c7b509)
Well guess bandits are allies of seperatists.... They do treat all items as stolen and attack you for stealing from bandits

### Reproduction steps

1. download [Save.zip](https://github.com/Regalis11/Barotrauma/files/13034280/Save.zip) and mods
![Barotrauma_9yVGqlGrJ2](https://github.com/Regalis11/Barotrauma/assets/42521948/9a833faf-303b-43fa-8403-567dea039790)
2. launch save and proceed to bandit beacon
3. take em prisoners and bring to submarine
4. attempt to steal items while near VIP protection team of seperatist figure

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0ddac7298c24b612f6d904aaa66222c815552f48.

Vanilla save for testing this:
[Save 17.zip](https://github.com/Regalis11/Barotrauma/files/13039525/Save.17.zip)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

Had to recreate save for this. Somehow example from Regalis got corrupted and didn't spawn bandits.
Could not get reaction out of VIP or their guards when stealing from bandits.

No issues found
Closing ticket
