### ISSUE TITLE
OnSuccess doesn't trigger even when it technically should

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [Regalis11/Barotrauma#12837]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I noticed that OnSuccess refuses to do anything even when copy-pasting a working OnFailure StatusEffect and just making it OnSuccess.

I'm trying to deal damage to a reactor and spawn an item inside it in an invisible slot that deals constant damage for 30 seconds if the reactor was repaired while its temperature was greater than 1 and the repair was done by a player.

The issue now is that OnSuccess, despite doing the exact same as the OnFailure, doesn't trigger at all and simply lets you repair the reactor normally. My previous method was just to set the condition of the reactor to 0 to blow it up if a repair was attempted while it is on and this worked for both OnFailure and OnSuccess.
But I wanted to change that to the new method with a critical state of needing to constantly repair it for 30sec to not blow up.

### **Here you can see the new StatusEffects used for this. The OnSuccess simply does nothing while OnFailure works fine despite both being identical.**
`        <!-- set reactor condition to 30 and spawn an item inside it which damages it every second if repaired while active -->`
`        <StatusEffect type="OnSuccess" target="This,Character" condition="30.0" setvalue="true" comparison="And">`
`          <Conditional temperature="gt 1" />`
`          <Conditional condition="gte 30" />`
`          <Conditional isPlayer="eq true" />`
`        </StatusEffect>`
`        <StatusEffect type="OnSuccess" target="This,Character" comparison="And">`
`          <Conditional temperature="gt 1" />`
`          <Conditional isPlayer="eq true" />`
`          <SpawnItem identifier="effect_reactorcritical" spawnposition="ThisInventory" spawnifinventoryfull="false" spawnifcantbecontained="true" />`
`        </StatusEffect>`
`        <StatusEffect type="OnFailure" target="This,Character" condition="30.0" setvalue="true" comparison="And">`
`          <Conditional temperature="gt 1" />`
`          <Conditional condition="gte 30" />`
`          <Conditional isPlayer="eq true" />`
`        </StatusEffect>`
`        <StatusEffect type="OnFailure" target="This,Character" comparison="And">`
`          <Conditional temperature="gt 1" />`
`          <Conditional isPlayer="eq true" />`
`          <SpawnItem identifier="effect_reactorcritical" spawnposition="ThisInventory" spawnifinventoryfull="false" spawnifcantbecontained="true" />`
`        </StatusEffect>`

### **Here you can see the previous StatusEffects that simply blew up the reactor. In this case both worked perfectly fine.**
`        <!-- explode if reactor is still outputting energy while trying to repair -->`
`        <StatusEffect type="OnSuccess" target="This,Character" condition="0.0" setvalue="true" comparison="And">`
`          <Conditional temperature="gt 1" />`
`          <Conditional isPlayer="eq true" />`
`        </StatusEffect>`
`        <StatusEffect type="OnFailure" target="This,Character" condition="0.0" setvalue="true" comparison="And">`
`          <Conditional temperature="gt 1" />`
`          <Conditional isPlayer="eq true" />`
`        </StatusEffect>`

You can playtest with these in my Enhanced Reactors mod attached to this report. I always use the Azimuth as a testing playground for this

**Here's the mod:**
[Enhanced Reactors.zip](https://github.com/Regalis11/Barotrauma/files/13039323/Enhanced.Reactors.zip)

### Reproduction steps

1. Create a OnFailure StatusEffect inside a <Repairable> component, make it set a condition other than 0 and perhaps play a sound and make sure it works.
2. Copy-Paste the exact same StatusEffect and change its type to OnSuccess.
3. The OnSuccess variant will not trigger.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.16.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It seems OnSuccess isn't implemented for Repairables at all. I would argue that technically it's working as intended - according to the documentation, OnSuccess should trigger when using some item succeeds, which isn't the case here (you're not using the item). But it'd be very useful to be able to trigger effects even when the skill check succeeds, so I went ahead and implement that in https://github.com/Regalis11/Barotrauma-development/commit/326f11fe528e388c34220fa06efa96529a52b613. It's also possible to use OnUse effects if you want to execute the same effect regardless if the skill check fails or succeeds.
