### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by alifeee** [Regalis11/Barotrauma#12830]
Tried loading the website on WiFi and on cellular data. Both tries it ended up at this cloud tunnel problem.

![image](https://github.com/Regalis11/Barotrauma/assets/13833017/ee01aee2-b2bf-4edc-b0ee-399200b6cae5)

**Comment by SoNickRND** [comment]
Last few days I have had the same problem, sometimes works okay, but sometimes I see this "you are suspicious".

**Comment by Regalis11** [comment]
Should be fixed now (although there are still some minor issues remaining with the wiki, such as missing images, but we are working on them atm!).
