### ISSUE TITLE
assassinationofjacovsubra2 has repeated text

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12842]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/c5a620c3-5aad-4f3f-98e7-83e94ed188af)

In Englishvanilla.xml

```xml

<eventtext.assassinationofjacovsubra2.o1.c1>“Jacov Subra. He's a weird guy who put together these—how should I put it—'themed' festivals.” The person rolls their eyes. “Full of husks. Multiple fatalities. He had a high profile trial a while back. You might have read about it on the Europan. Anyway.”</eventtext.assassinationofjacovsubra2.o1.c1>

<eventtext.assassinationofjacovsubra2.o1.o1.o1>“Jacov Subra. He's a weird guy who put together these—how should I put it—'themed' festivals.” The person rolls their eyes. “Full of husks. Multiple fatalities. He had a high profile trial a while back. You might have read about it on the Europan. Anyway.”</eventtext.assassinationofjacovsubra2.o1.o1.o1>
```

### Reproduction steps

`triggerevent assassinationofjacovsubra2`

### Version

Unstable (v1.1.16.0)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ed1497336b89ff817979d491282944a68d4c24e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
