### ISSUE TITLE
Flak cannon's shell shrapnel is broken!

### ISSUE THREAD

**Issue by hello-world114514** [Regalis11/Barotrauma#12844]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![屏幕截图 2023-10-19 172310](https://github.com/Regalis11/Barotrauma/assets/116760209/da7830fe-3e13-480d-a1aa-21c8ed2065b7)

shrapnel's angle is ever up, they don't inherit shell's angle  

### Reproduction steps

shoot with flack cannon
you can see, your shells go up

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a0a59243831cec1405469396e75eafdebd378cd (commit in our private repo).

**Comment by hello-world114514** [comment]
> Thank you for the report!
> 
> Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a0a59243831cec1405469396e75eafdebd378cd (commit in our private repo).

when fix    :  (

**Comment by Regalis11** [comment]
I can't say for sure yet, but I'm hopeful we can get a patch out next week.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by hello-world114514** [comment]
> I can't say for sure yet, but I'm hopeful we can get a patch out next week.

we ve been waiting for a week, but there' s no patch

**Comment by hello-world114514** [comment]
> I can't say for sure yet, but I'm hopeful we can get a patch out next week.

we ve been wainting for a week,

**Comment by Regalis11** [comment]
Yes, we unfortunately could not get the patch out last week. Hopefully this week though. Sorry for the inconvenience!
