### ISSUE TITLE
The stun baton can still cause a powerful stun effect with a battery cell that is only in 0.0001 condition.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12843]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Maybe use open/closed intervals instead of excluding 'broken/full condition' for the RelatedItem would be better?

Before:
```xml
<RequiredItem items="mobilebattery" type="Contained" ExcludeBroken="true" ExcludeFullCondition="false" msg="ItemMsgBatteryCellRequired" />
<!-- 4 usages with normal battery -->
<StatusEffect type="OnUse" target="Contained,UseTarget" Condition="-25.0" disabledeltatime="true">
    <RequiredItem items="mobilebattery" type="Contained" msg="ItemMsgBatteryCellRequired" />
    <Conditional entitytype="eq Character" />
</StatusEffect>
```

After:
```xml
<RequiredItem items="mobilebattery" type="Contained" Intervals="(0,100]" msg="ItemMsgBatteryCellRequired" />
<!-- 4 usages with normal battery -->
<StatusEffect type="OnUse" target="Contained,UseTarget" Condition="-25.0" disabledeltatime="true">
    <RequiredItem items="mobilebattery" type="Contained" msg="ItemMsgBatteryCellRequired" />
    <Conditional entitytype="eq Character" />
</StatusEffect>
```

Fix:
```xml
<RequiredItem items="mobilebattery" type="Contained" Intervals="[25,100]" msg="ItemMsgBatteryCellRequired" />
<!-- 4 usages with normal battery -->
<StatusEffect type="OnUse" target="Contained,UseTarget" Condition="-25.0" disabledeltatime="true">
    <RequiredItem items="mobilebattery" type="Contained" msg="ItemMsgBatteryCellRequired" />
    <Conditional entitytype="eq Character" />
</StatusEffect>
```

Also you can add more ranges of condition to limit requirements:
`<RequiredItem items="mobilebattery" type="Contained" Intervals="(0,20],[50,70],[80,100)" msg="ItemMsgBatteryCellRequired" />`

I think it's very needed as for many mods.

### Reproduction steps

1. place a battery cell that is in 0.01% condition.
2. use a stun baton to attack with the battery equipped.
3. trigger status effects which generates more stun effectiveness.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I feel like this is such a rare edge case, that doesn't really cause any real issues, that I don't think we'll be adding any extra complexity to RelatedItem to address this.
