### ISSUE TITLE
Slight UI overlap on PvP round summary

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12840]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/1a91b1cb-73f8-4a8e-a7a1-d84b282c6841)

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

1.1.18.0 Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9c52288f095d836862481bfc065c9749cd88cedf
