### ISSUE TITLE
Nav terminal units are displayed on the language the round was started with

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12841]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Starting the round in English and switching to Chinese
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/45063ae0-f47b-40a9-bd9b-bda2eb036bf2)

Starting the round in Chinese and switching to English
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/cea83a53-93d2-4cd2-b975-56a002b811d5)

 Only happens on the round where you changed the language

### Reproduction steps

1. Start singleplayer with English
2. Undock from outpost
3. Switch language to Chinese on the next round
4. Notice that the units are displayed in English

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Other

### -

1.1.18.0 Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07dd1163af4cef22a472edac7222085145ae2357

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

Checked how units behave in different devices, nav terminal, junction box, reactor.

Noticed that containers don't update their translation on the fly anymore.
This happens in current stable also. Created new ticket for this.
https://github.com/Regalis11/Barotrauma/issues/13309

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/22641992-98dd-41b1-9a08-7d843fb8ebc0)

No issues found with units
Closing ticket
