### ISSUE TITLE
MaxStackSizeHoldableOrWearableInventory shouldint affect items that are attachable

### ISSUE THREAD

**Issue by ricky122122** [Regalis11/Barotrauma#12847]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I updated my mod Barocraftables+ to the latest storage changes and got a bug report about oxygen tanks only stacking to 1 in storage cabinets. I looked and this is due to oxygen tanks using MaxStackSizeHoldableOrWearableInventory="1" and my cabinets being detachable and moveable I could "fix" this by overriding any item that uses "MaxStackSizeHoldableOrWearableInventory" but then they could stack in storage containers and thats just not a good solution to override everything that uses it. I dont see a negative for it to make a secound check if it has holdable it also checks if attachable="false". There is probably other better ways to do this and their might even be away around my problem but I have not seen one.

This might be more of a feature request but I feel like this is more of an oversight and makes it require me to override commonly overridden items just to loose features like it not stacking in storage containers and other holdables.

### Reproduction steps

Subscribe to Barocraftables+ or you can make a storage Cabinet holdable/detachable
Enable said mod if you installed barocraftables+
start sub editor and open a sub and try to place more then 1 oxygen tank into a slot

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, I was able to stack oxygen tanks inside a cabinet in the Barocraftables+ mod, working correctly. Closing.

**Comment by Regalis11** [comment]
The fix did not work correctly, it caused MaxStackSizeHoldableOrWearableInventory to be used for all non-holdable containers (including cabinets). Reopening

**Comment by Rokvach** [comment]
Tested again, no issues after the latest changes. Closing.
