### ISSUE TITLE
Circuit boxes consume components

### ISSUE THREAD

**Issue by cam4021** [Regalis11/Barotrauma#12848]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Circuit box consumed components by holding the circuit box and tapping the hotkey the component is attached to

component is not on grid and cannot be searched for with cogwheel, but the capacity still fills

### Reproduction steps

Enter sub
enablecheats
spawn circuit box
spawn adder component
hold circuit box
tap the hotbar key that the component is on
circuit box eats component like a suitcase but cannot be retrieved

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
This hasn't been completely fixed yet, I found two more ways of causing this to happen.

- You can still drag and drop components into the circuit box if your inventory is full. Setting `AllowSwappingContainedItems="false"` on the circuit box's ItemContainers seems to fix this.
- If you quip a circuit box in one hand, and a different item in the other, pressing hotbar shortcuts or clicking on the equip button of other components will put them into the circuit box.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4670/commits/df6368338ada284cd7a611d62019c18baaaa58e0

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/af084fa81dbebe9eb9d1ad64565b0587063073b0

Could not insert components into circuitbox anymore.
Circuitbox functions as expected

No issues found
Closing ticket
