### ISSUE TITLE
Fabricating something that doesn't need 100% condition of required item will consume conditions of the whole stack

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#12855]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![QQ截图20231020200318](https://github.com/Regalis11/Barotrauma/assets/64390906/786789cb-d45a-4e96-ace4-e4d000ee2666)
![QQ截图20231020200256](https://github.com/Regalis11/Barotrauma/assets/64390906/03a220f4-7fa0-4e3b-b532-265b8b6691dc)
![QQ截图20231020200414](https://github.com/Regalis11/Barotrauma/assets/64390906/5e25aa12-bc72-44c8-9a83-597805202f6a)

### Reproduction steps

1. enable mod that has this kind of recipe (I use neurotrauma)
2. go to sub editor
3. make sure the number of fabrication required items is more than 1 then start to fabricate
4. all conditions of materials are decreased

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Thr3d** [comment]
This is closed, but no feedback or commit was provided. When might this fix be released?

**Comment by Regalis11** [comment]
Ah, I forgot to comment on this! This was fixed in https://github.com/Regalis11/Barotrauma-development/commit/533e4e3eddce9987efcca5eba790a7b63cfe4204 (commit in our private repo). We're hoping to release a hotfix this week. Sorry for the inconvenience!
