### ISSUE TITLE
"Error saving gamesession" when swapping submarines whilst a circuit box is present.

### ISSUE THREAD

**Issue by DownloadableContent5021** [Regalis11/Barotrauma#12856]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If there's a circuit box with any component inside it, anywhere on your current submarine, if you try to swap to a new submarine with "transfer items" turned ON, the game will give an "Error saving gamesession" in dev console.

### Reproduction steps

1. In submarine editor, place a circuit box with any component inside on a submarine.
<img width="1680" alt="Screenshot 2023-10-20 at 10 13 03 pm" src="https://github.com/Regalis11/Barotrauma/assets/148298589/e7551db0-3606-47f7-a469-e884106df3c5">

2. start a new campaign with that submarine and attempt to purchase and swap to any new submarine with "transfer items" turned ON.
<img width="1680" alt="Screenshot 2023-10-20 at 10 13 55 pm" src="https://github.com/Regalis11/Barotrauma/assets/148298589/a2b1ebec-5b0a-4529-9ec6-db333ffc6b02">

3. observe as the game gives an error in the dev console; doesn't swap to the new submarine; and the game doesn't save anything that happened after swapping to the new sub.
<img width="1680" alt="Screenshot 2023-10-20 at 10 14 24 pm" src="https://github.com/Regalis11/Barotrauma/assets/148298589/2d436d64-04ea-40b9-9854-2b1e309ed11b">

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

MacOS

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4574/commits/d514a767f951c1068170c950bdcf360a1a4c84ac

Error when starting a new campaign or any other game mode, SP or MP.
All containers report this.
```
Failed to set the value of the property "WaterProof" of "Medium Steel Cabinet (ID: 1284)" to true {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Barotrauma.SerializableProperty.TrySetValue(Object parentObject, String value) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Serialization/SerializableProperty.cs:line 283

Inner exception: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Barotrauma.Item.set_WaterProof(Boolean value) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 790
```

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4574/commits/c090496ebd039b5694cb9197d2efb295a9f33489

Testing details in: https://github.com/Regalis11/Barotrauma-development/pull/4574

No issues found
Closing ticket
