### ISSUE TITLE
Trigger radius is too small in both soundinthevent and goblincooking1 events

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12868]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The trigger radius for both soundinthevent and goblincooking1 events Triggeraction is too small, a standing player cant reach certain vents, which makes the event very rare

      <TriggerAction target1tag="psychosisvent" target2tag="player" applytotarget1="selectedpsychosisvent" applytotarget2="triggerer_player" radius="50" />

I had to teleport my character to reach these two vents, make it a little bigger

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/78a54f78-d943-4b28-8189-1e656139826b)

### Version

v1.1.18.1 (Treacherous Tides)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

No issues found
Closing ticket
