### ISSUE TITLE
Text error in stowaway2 event

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12865]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/78563e63-4230-472c-9952-2ca7d7c0b6f2)

I assume you were supposed to use [location1] here

### Reproduction steps

Leave outpost
`triggerevent stowaway2`

v1.1.18.1 (Treacherous Tides)

**Comment by ubertpendragon** [comment]
Just noticed the event was disabled in eventset


Since I'm reworking a few events I might take a look at it 
It's broken in a few ways:

- the event triggers as soon as the level loads, it should have a Waitaction

- clown part of it is disabled

- "bringing back" the stowaway has the same mission as "next stop" option, which leads to the mission not disappearing 
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/874ba2b4-ee18-4060-b1eb-2e414db4bc08)

- you can drop off the stowaway in the middle of nowhere (the event doesnt check if you're going from or to a linea)

- If you dock back to the previous outpost despite picking "bring back" option, the mission is still here
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/fea64c8f-eb6f-4a3a-a750-bbe5c7a6930c)

**Comment by Regalis11** [comment]
This event can't trigger, so this isn't an issue in the vanilla game.

**Comment by ubertpendragon** [comment]
I'll fix it I swear
