### ISSUE TITLE
[Dev Version] Clown achievement not plausible

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1286]
What's quite annoying is that none of the default subs house the famed clown suit. This makes getting that clown achievement impossible without specifically making a custom sub. I find this to be quite dumb, as all achievements should be obtainable by default. I suggest you place the clown suit somewhere, on the orca.

**Comment by AbominationBanisher** [comment]
nevermind

**Comment by hubismal** [comment]
lmao
