### ISSUE TITLE
Circuit box doesn't work with multiple component connections

### ISSUE THREAD

**Issue by Isamylov** [Regalis11/Barotrauma#12862]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm trying to copy one of my schemes into the circuit box using the following outputs:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/4efdeeb9-5644-4440-8923-5d35d48ffe77)

Inside the circuit box weapons attached to SIGNAL_OUT and periscopes to SIGNAL_IN:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/f87e31a7-244f-4f8f-a1c4-f6dcb0ce3470)
![image](https://github.com/Regalis11/Barotrauma/assets/109140990/dcd62025-c137-4c0e-a3dd-b08aad994f14)

The scheme itself is a complex one:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/fa096b00-f195-4e14-89b3-327331b81d33)

I'm  sure I've reproduced the scheme correctly inside the box, but the periscope/weapons doesn't work as intended.

The default scheme is the following:

TOP periscope:
![image](https://github.com/Regalis11/Barotrauma/assets/109140990/eb4699e7-dcc1-4c53-a4b3-476be22c5d17)

DECK periscope:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/5bfeb6d0-a6a0-4c88-bd38-6329e92881c6)

All weapons and periscopes connected at least to three different components, but using the curcuit box only one connection is needed. Example:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/8a31ed6d-727b-4e11-bc82-3ef5d5c4447e)

Without box:

![image](https://github.com/Regalis11/Barotrauma/assets/109140990/f5d641af-f8fb-404c-9977-3794f6134240)

So:

**The intended result:**

_Using one of the periscopes allow you

1. Shoot laser with LMB.
2. Shoot railgun with double LMB click.
3. Change camera between railguns simply with mouse hover._

**Current result:**

1. Only shoot laser with LMB, nothing else.

---

I think the issue (bug?) is that circuit box **can't sent** multiple signals from different components throught SIGNAL_IN and SIGNAL_OUT.

Questions are:

1. Am I doing something wrong or it's a bug?
2. Any plans to allow ctrl+c > ctrl+v components INTO the circuit box in order to save time and don't rebuild component scheme from scratch? It'll be the huge QoL for submarine builders.

P.S also it's hard to copy the schemes inside the circuit box, cause each time I need to swich between edit mode and wiring mode to check (copy/transfer) connections. Any plans to QoL this?

Thanks!

### Reproduction steps

---

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by LobaDK** [comment]
My issue is likely related to this as well. I have a multi-turret circuit that allows me to cycle forward with a single click, cycle backwards with a double click, and send a trigger_input signal when holding left click. This works perfectly fine on it's own, but when replicated inside a Circuit Box, the double click function fails, and it instead cycles forward as if it was a single click, albeit with the delay of a double click.

Testing it with a simple circuit, seems to reveal that the state_out of relays don't seem to change, or the entire state of relays in general is unable to change.

I've [included a zip file](https://github.com/Regalis11/Barotrauma/files/13063976/Double.Click.switch.zip), which contains two item assemblies. The first should work fine, and would swap the two lights on each double click. The second, which to my knowledge is a replica of the first, but inside a Circuit Box, does not swap between the lights, no matter how I click.

**Comment by LobaDK** [comment]
Thanks to a bunch of help from the Discord server, turns out my issue is actually related to how the game treats and prioritizes components and connections in the order they're placed/changed/wired and seemingly causes the signals to be ever so slightly delayed in an otherwise very timing-sensitive circuit. Wiring it in any other order does change the outcome drastically. For example, re-wiring the double-click detection in my circuit (the connections and values are the exact same, but the order of it was different) now completely broke it, and it only now cycles backwards regardless of how I click or even hold it.

As I can see @Isamylov also use delays and relays in their circuit, I can't help but wonder if that is actually what's causing it as well
