### ISSUE TITLE
Badvibrations2 event blocks you from closing dialog box

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12869]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Picking the "Sleep" Badvibrations2 paralyzes you, which prevents selecting the next dialog option

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/a9830176-e65d-4748-bf1c-3351031fea22)

Change this:

```xml
                <Option text="EventText.badvibrations2.o1.o1.o1">
                  <AfflictionAction affliction="paralysis" strength="100" targettag="triggerer_player" />
                  <ConversationAction text="EventText.badvibrations2.o1.o1.o1.c1" targettag="triggerer_player"/>
                  <!--END-->
                </Option>
```
                
To this (also added a fade to black effect for sleeping)

```xml
                <Option text="EventText.badvibrations2.o1.o1.o1">
                  <ConversationAction text="EventText.badvibrations2.o1.o1.o1.c1" targettag="triggerer_player" fadetoblack="true"/>
                  <AfflictionAction affliction="paralysis" strength="100" targettag="triggerer_player" />                  
                  <!--END-->
                </Option>
```

I'm working on event improvements so I'll probably change more

### Reproduction steps

1. `spawnitem psychosisartifact_event cursor`
2. grab the artifact (you're supposed to grab it from an artifact holder directly)
3. `triggerevent badvibrations2`
4. pick 1st dialogue option until "Sleep" 
5. stuck

_No response_

### Version

v1.1.18.1 (Treacherous Tides)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/566f4933e4b3d61ff698e56ec454ce14f11849a7

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
