### ISSUE TITLE
Psychosis artifact generates a huge amount of particles

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12876]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I think a Particleemitter line got copied mistakenly in the psychosis artifact and added on top of the existing effect, generating a ton of particles passively. 

`        <ParticleEmitter particle="psychosisfx" anglemax="360" particlespersecond="12" />`

It's really hard to distinguish the active and passive phases
There probably shouldnt be 2 emitters here, tweak the first one if necessary

```xml
      <StatusEffect type="Always" target="This">
        <Conditional hastag="neq artifactcontainer" targetcontainer="true" />
        <Conditional Voltage="0.0" targetcontainer="true" />
        <sound file="Content/Items/Alien/AlienArtifactLoop1.ogg" range="500.0" loop="true" volume="0.5"/>
        <ParticleEmitter particle="psychosisfx" scalemultiplier="0.7,0.7" anglemax="360" emitinterval="1.1" particleamount="1" particlespersecond="1" />
        <ParticleEmitter particle="psychosisfx" anglemax="360" particlespersecond="12" />
      </StatusEffect>
```

Red is from my mod Green is from update
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/492d0867-30ff-4661-9806-1a0e61e3b0d9)

### Version

v1.1.18.1 (Treacherous Tides)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/54a59127cf13a3027791bee7b1684740fa8597e2

**Comment by Rokvach** [comment]
Tested, compared to the current stable build and the amount of particles are indeed less in comparison. 

Current passive state: 16-20 particles
Fixed passive  state: 6-15 particles

Current active state: 650 particles
Fixed active state: 450 particles
