### ISSUE TITLE
Bots grab too many oxygen tanks with the "Prepare for expedition" order

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#12878]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Now that oxygen tanks no longer stack, ordering the bots to prepare for an expedition will make them grab 5 oxygen tanks which seems a little excessive.
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/a13f6fd9-4d49-4a57-909a-b88e0906632f)

### Reproduction steps

1. Order a bot to prepare for expedition
2. Observe them fill half their inventory with ~55 minutes worth of oxygen

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f59d920e588d90560c433b218762b28f06499389

**Comment by Rokvach** [comment]
Tested, bots now only grab 2 oxygen tanks, working correctly. Closing.
