### ISSUE TITLE
"Note2" eventsprite using wrong sourcerect

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12874]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In Traitorevents.xml, Note2 has the same sourcerect as Magazine

    <Sprite identifier="Magazine" texture="Content/Map/Outposts/Art/Event_pic4.png" sourcerect="0,768,256,256" />
    <Sprite identifier="Note2" texture="Content/Map/Outposts/Art/Event_pic4.png" sourcerect="0,768,256,256" />
    
 
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/7f0d0112-987e-4ce7-8a43-a6e87661e34b)

### Version

v1.1.18.1 (Treacherous Tides)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/663ef65b932ed3cf2fa7af6465272410a6c06fd0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
