### ISSUE TITLE
Projectiles launched by status effect have incorrect rotation

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12872]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Projectiles spawned by status effect seem to have fixed rotation angle instead of inheriting the parent.
Affected are flak cannon bolts which makes flak cannon unplayble now.

### Reproduction steps

fire flak cannon with any type of ammunition

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/12844
