### ISSUE TITLE
items inside Diving Locker, oxygen tanks, ammo holders do not scale

### ISSUE THREAD

**Issue by Regulus4** [Regalis11/Barotrauma#12885]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![obraz](https://github.com/Regalis11/Barotrauma/assets/148685850/e06ee4fb-2f12-4cfb-aa94-b8aa817eeae9)

### Reproduction steps

1. Start Sub Editor
2. Add diving locker
3. Add suit to diving locker
4. Try to scale down diving locker

same thing with oxygen tank shelf/oxygen generator,  ammo loaders

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### -

SubEditor

### Version

Other

### -

1.0.20.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regulus4** [comment]
![obraz](https://github.com/Regalis11/Barotrauma/assets/148685850/2a92d53e-e3e2-4a45-a166-f947b4a5d350)
they also don't hide when you set them to transparent

**Comment by Regalis11** [comment]
Thank you for the report! In my opinion this doesn't feel like a bug. Why would making the container smaller shrink the items inside it too? Same with making it invisible. I also think many sub builders use invisible containers (weapon holders example) to "attach" items to walls.

**Comment by Regulus4** [comment]
ohh, you are right about weapon holders.
I also agree about invisibility, but I remember that in previous versions I made smaller diving lockers and the item inside also got smaller (0.4)

**Comment by Regalis11** [comment]
I gave a test at versions 0.9 and 1.0, and the items inside didn't seem to scale there either. While I can see the use for scaling the contained items, I could also imagine it seeming like a bug in some cases. Someone could for example want to scale some kind of a shelf, and then find it odd that items on it magically shrink. Changing this now would also most likely cause issues in existing custom subs that rely on the current behavior.
