### ISSUE TITLE
WeldedSprite does not show up in the sprite editor

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12881]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/42521948/8f12af60-ba5f-4e33-859e-5130d878d0d7)

When I was trying to do a variant override for wrecked items, I was struck with <WeldedSprite> not working at all, neither showing up in `spriteditor` while other options worked weirdly, like buttons from normal doors showing up on wrecked doors which I assume variants trying to inherit from these lines:

`<DecorativeSprite texture="Content/Items/Button/button.png" sourcerect="28,70,34,51" depth="0.75" origin="1.65,0.76" />
<DecorativeSprite texture="Content/Items/Button/button.png" sourcerect="28,70,34,51" depth="0.75" origin="-0.65,0.76" />`

So yeah would be nice to know why <WeldedSprite> does not show up and how to prevent buttons from being inherited!

### Reproduction steps

1. Download [New Wrecks For Barotrauma (With sellable wrecks).zip (https://github.com/Regalis11/Barotrauma/files/13061626/New.Wrecks.For.Barotrauma.With.sellable.wrecks.zip) mod and [All_Doors_Welded.zip](https://github.com/Regalis11/Barotrauma/files/13061631/All_Doors_Welded.zip) item assembly
2. put em in local mods folder and then activate in-game
3. go to sub editor and find item assembly using key words `All Doors`
4. place it and observe issue (all wrecked doors should appear to be welded but because of bug they wont + you will see buttons on buttoned doors)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
To me it seems like this is an issue with the mod: the welded sprites appear to render fine, they're just set to use an empty portion of the MiscWrecked.png atlas as the welded sprite.

>how to prevent buttons from being inherited!

Variants inherit everything from the base item, if you want to disable some element altogether you can do that by emptying it, i.e. just changing it to
```
<DecorativeSprite />
```

**Comment by PanmanS** [comment]
Doesnt appear on my end + thank you for decorative sprite fix!
![image](https://github.com/Regalis11/Barotrauma/assets/42521948/006bb9ce-e4a3-47ec-8936-b90effc98793)

**Comment by PanmanS** [comment]
Neither I see outline selecting empty space
![image](https://github.com/Regalis11/Barotrauma/assets/42521948/459e6a15-b3b2-44e8-94f3-f9bf81ad1d23)

**Comment by Regalis11** [comment]
Yeah, it doesn't seem to show up in the sprite editor, but if you look at "doorwrecked" for example, the sourcerect is set to "957,1,65,377" which is an empty area in the atlas.

**Comment by PanmanS** [comment]
Aight, I just was relying on spriteeditor to do my work, so guess I gotta learn gimp


Still, it would be nice if sprite editor was working with welding stuff!!!

**Comment by Regalis11** [comment]
Fixed WeldedSprites not appearing in the sprite editor: https://github.com/Regalis11/Barotrauma-development/commit/b11c29e210475815bd7593c9d41e2c918226bc7d

>so guess I gotta learn gimp

You don't need gimp for this, even mspaint will do if you just need to check the position of the sprite. :)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/0a79b8149bb207a9c71b6350a4c3dfd67ab0ebf3

Welded sprite spaces for wrecked variants can now be found in spriteeditor.
hatchwrecked.welded is erroneously placed on a fin piece, even tho you can't weld wrecked pieces in game.


![image](https://github.com/Regalis11/Barotrauma/assets/8488224/b1200fe6-21e8-49db-9816-c7f0b3fe726e)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/5902dc58a8ad78641d4914bf33b359c77b2963a4

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4582/commits/f2801dfd908f7b4b5906daf654164e0f3f5b287e

No issues found
Closing ticket
