### ISSUE TITLE
AI won't walk through custom Autodoor

### ISSUE THREAD

**Issue by UrstMcRedHead** [Regalis11/Barotrauma#12889]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing a sub with a custom emergency door I found that they can't path find through the door when it's closed.

How the door works: 
The default state is open, unless it detects water on either side.
When the water detectors trip, the door closes, and defaults to a motion detector to temporarily open for crew.

How it breaks:
The AI can walk through the open door, but when it closes they either stop at the closest waypoint, or ignore the task. 
This seems to only happen when the door's closed because they will access it before, or after it gets tripped once.

Example Video:
https://youtu.be/QvY2tMnmcq0

Test Sub:
[Kodiak.zip](https://github.com/Regalis11/Barotrauma/files/13063832/Kodiak.zip)

Other Notes:
I'm not entirely sure, but I think it has something to do with the auto generated waypoints. I'm definitely not experienced enough to speculate.

### Reproduction steps

1: Load the Kodiak test ship in the editor
2: Test ship, and grab a plasma cutter from the aft engine storage locker
3: Set the AI to fix hull breaches
4: Cause a breach in one of the following rooms (Engine, Reactor, or forward Electrical rooms)
5: Observe the safety door close
6: Observe AI stop in front of the safety doors.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report!

@itchyOwl posted a comment in https://github.com/Regalis11/Barotrauma/issues/12888 that was meant for this report:
> Thanks for a detailed bug report and an illustrative video about it. However, I don't think there's a bug there. The bots don't have knowledge about the automatic mechanics. And since there's no buttons connected to the door that they could interact to open it, they think they don't have access to it. Instead of just running into the door, they stop, as intended. In this particular case it's not the optimal behavior, but I don't think we should change the AI logic in trying to "fix" it. Instead, you could add buttons to the door for overriding the automatic mechanic, so that the bots could use them for opening the door.
