### ISSUE TITLE
WIfi inside circuit boxes still broken

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12883]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

same as always, it works only periodically in our mp campaign with Gears and most of times doesnt transmit signal

If you wouldnt be able to reproduce issue, I will build exact system this bug happend with, but I dont think it should matter

### Reproduction steps

1.  place a circuit box and put wifi component inside of it
2.  place button outside, connect it to `first input` of circuit box, then place wifi comp inside and set it on channel for example 9814 and connect to `1st input`
3. place wifi component outside and wire it to relay (important) `set_state` 
4. wire lamp to `state_out` of relay
5. observe issue

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
More accurate repro steps in [Wifi placed in game in circuitbox doesn't work](https://github.com/Regalis11/Barotrauma/issues/12912), closing as a duplicate

**Comment by Max112358** [comment]
This seems like its still broken. Wifi components effect other wifi components inside the same circuit box, but not wifi components set to the same channel placed outside the circuit box
