### ISSUE TITLE
Smoking cigar underwater gives no affliction

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#12884]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

smoking cigar underwater doesn't have any benefit but decreases its condition
not sure if it's intended

### Reproduction steps

1. Spawn a cigar with console commands
2. Use the cigar underwater
3. Observe 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0aabf2fbfc5d7e8cf9129ba18c5fb79a194b89e0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
