### ISSUE TITLE
spawnpoint tags aren't applied to IDcards on bought/transferred new sub

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#12899]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

buying a new sub and transferring to it doesn't apply the new sub's tags. Players can't open locked cabinets (secure/toxin).

testing in sub editor reported OK (current and previous stable version)

possible related: #12546

moreinfo later

### Reproduction steps

1. start campaign
2. buy new sub that has spawnpoint tags (i.e., captain = poop ) (reported was players buying the Iroh)
3. switch to new sub
4. try opening pickedrequired w/ spawnpoint tag

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/28d2361bf48d65da237d3a65b0a1e007007eb37e

Tested in SP and MP.
Created new sub with wrongly configured spawnpoints (could not open secure cabinets when started with that).

No issues found
Closing ticket
