### ISSUE TITLE
[Dev Version] Security Guard AI immune to poison

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1289]
Read the title.

**Comment by NilanthAnimosus** [comment]
AI as in watchman or fellow security guard on your own crew? the watchman in outposts are designed and intended to be immortal to everything as well as armed, if you mean standard crew - then perhaps this is a bug.

**Comment by AbominationBanisher** [comment]
The security guard, not the watchman.

**Comment by Regalis11** [comment]
If possible, could you give some more details on how to reproduce this or how it happened? Do you remember which poison was it? Does it happen consistently or was it a one-time incident? Was this in multiplayer or singleplayer?

**Comment by AbominationBanisher** [comment]
Sufforin, Cyanide, Morbusine, in fact, no drugs worked on the security guard. I have played about seven campaign games and each game the guard is in fact immune. I can probably get some screenshots right now. Singleplayer campaign. Happened on the orca sub too.

**Comment by Regalis11** [comment]
Sorry but I still wasn't able to reproduce this. How exactly are you administering the poisons, via the health interface or by stabbing the security officer with the syringe?

**Comment by NilanthAnimosus** [comment]
for the sake of saying it...you say on the security guard. campaign games do not start with them for saying the least.

Can you provide a save file or something to work with on this? it still sounds like to me it might be the watcher which is the guy standing in the initial dock you start at and the level end dock. hes immortal to all poisons and damage.

**Comment by AbominationBanisher** [comment]
> for the sake of saying it...you say on the security guard. campaign games do not start with them for saying the least.
> 
> Can you provide a save file or something to work with on this? it still sounds like to me it might be the watcher which is the guy standing in the initial dock you start at and the level end dock. hes immortal to all poisons and damage.

It is in fact 100% not the watchman. 

As for regalis, it was using the health interface. I don't even know how to obtain syringes in the orca.

**Comment by AbominationBanisher** [comment]
bug has gone away by itself, closing this topic.
