### ISSUE TITLE
Outpost security confiscates more than just weapons

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#12898]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After a successful arrest, outpost guards will confiscate any stolen goods and weapons the arrested player has on them. Some items that are not weapons and pose no threat may also be confiscated by the guards if they have the MeleeWeapon or RangedWeapon component.
Instruments, bananas, storage containers, commendations, medals, skill books, medicinal items are all able to be confiscated.
Tools like screwdrivers, wrenches, crowbars can be confiscated and while they can be used as weapons, their primary purpose isn't being a weapon in most cases.
Poisons may be confiscated which does make sense. 
While bike horns, toy hammers and cymbals aren't weapons, guards confiscating them wouldn't be as surprising since the event which involves a crate of confiscated bike horns features a security guard describing them as "highly dangerous implements of terror".

https://github.com/Regalis11/Barotrauma/assets/115734437/3ae759d6-9120-4b84-89a8-c958185d8214

### Reproduction steps

1. Get caught stealing on an outpost with some of these items in your inventory
2. Get arrested by a security guard and notice how they confiscate (or just drop on the floor if they don't have the inventory space) the listed items

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/47a58b8abb22c733a1c3acec6c9c7b159c3c245b

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4612/commits/47a58b8abb22c733a1c3acec6c9c7b159c3c245b

Tested with different items.

No real issues found and code works as it should.

Closing ticket
