### ISSUE TITLE
Несколько багов. / A few bugs.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#129]
1. Невозможно выбрать пятый сервер в списке. Нужно обязательно сдвинуть его, но у меня были моменты когда и это не помогало.
It is impossible to choose the fifth server in the list. We definitely need to move him, but I had moments when it did not help.
![4server](https://user-images.githubusercontent.com/33912761/33869776-be538692-df1b-11e7-9600-45cd01ef8a99.gif)

2. Игроки не видят через стену с дырой, но у некоторых с этим всё в порядке.
Some players can't see through the wall hole, but some this is all right.
![bandicam 2017-12-12 08-41-56-567](https://user-images.githubusercontent.com/33912761/33870028-ff69adb8-df1c-11e7-9076-28531020469a.jpg)

3. Некоторые выданные права нельзя увидеть из-за кнопки. Возможно, это из-за данного разрешения экрана.
Some issued rights cannot be seen because of the buttons. Perhaps this is due to the screen resolution.
![bandicam 2017-12-12 08-45-44-745](https://user-images.githubusercontent.com/33912761/33870079-3838a068-df1d-11e7-9c43-13b30ef01690.jpg)

4. Вот об этом кто-то уже писал, если мне не изменяет память, но, думаю, это будет нелишним.
Игрок подключился к игре с самого начала. Возможно, это проблема того, что я ввёл команду. Короче, у него иначе отображаются некоторые вещи, даже его положение. (за качество гиф извиняюсь)
That's about it someone already wrote, if I remember correctly, but I think it will be useful.
The player joined the game from the beginning. Maybe it's a problem that I've entered the command. In short, he otherwise displays some things even his position. (Bad quality sorry.)
![husk -iloveimg-compressed](https://user-images.githubusercontent.com/33912761/33870069-2dff1fa0-df1d-11e7-9c76-36fec5823b7a.gif) 

Добавил 13.12.2017
Added 13.12.2017

1. Игрок может нависать над поверхностью, выйти из бага легко - просто присесть.
The player can hover over the surface, to get out of the bug is easy - simply sit down.
![elvis](https://user-images.githubusercontent.com/33912761/33943528-79d1f520-e02a-11e7-88d9-c3e9e80223a7.gif)

2. Про револьвер уже писали, скорее всего.
About the gun already wrote, most likely.
![gg](https://user-images.githubusercontent.com/33912761/33943583-944e8b02-e02a-11e7-8856-4968caf9bd85.gif)

3. Был момент, когда описание не соответствовало заданию. Я бы сделал скриншот, но у меня возникли проблемы именно в тот момент... Удача на моей стороне...
There was a time when the description did not match the instructions. I would do a screenshot but I'm having problems at the moment... Luck was on my side...

P.S. если что-то из этого уже было на GitHub, то извините.
if some of it was already on GitHub, then I'm sorry.

**Comment by NilanthAnimosus** [comment]
The first issue has been fixed for next version.
The original issue is #70 (But thank you for reporting!)

It may have been better to split this into multiple issues however, most of  them are not strictly related to the others - and the title is for an issue that has already been fixed.

(На английском я надеюсь, что это имеет смысл)
Первая проблема исправлена для следующей версии.
Исходная проблема - # 70 (Но спасибо за сообщение!)

Возможно, в будущем было бы лучше разделить его на отдельные отчеты об ошибках, но большинство из них не имеют строгого отношения к остальному - и заголовок - это проблема, которая уже исправлена, поэтому это может быть не замечено при первом взгляде.
