### ISSUE TITLE
Welding tanks replaced by only one when bought in vending machine.

### ISSUE THREAD

**Issue by Well-to-doGaming** [Regalis11/Barotrauma#12909]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When buying Welding tanks from the vending machine, if you buy more than 1 at once, you will get only one when dragging it into the inventory.

### Reproduction steps

1. Open vending machine.
2. Buy Welding tank x2+
3. Leave the tanks in the same slot before dragging into inventory.
4. Drag tanks into inventory.
5. Game replaces all with only one.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### -

-

### Version

v1.1.18.1 (Treacherous Tides)

### -

-

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/A
```

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. I was able to take both of the tanks out of the machine with no issues in both single player and multiplayer. Are you using some kind of mods by any chance?

https://github.com/Regalis11/Barotrauma/assets/14351070/2e7f567b-778d-447d-a7fa-745e8013c8f6

**Comment by Well-to-doGaming** [comment]
I was playing with my friends and it randomly happened.
We had no mods installed, pure vanilla. I can't recreate the bug, so I guess it fixed itself?
