### ISSUE TITLE
Lightning Wizard can stun the user for a prolonged period of time

### ISSUE THREAD

**Issue by N-Komaeda** [Regalis11/Barotrauma#12905]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When using Lightning Wizard trait (Engineer - Electrician 4), you get a 'Guarded' buff that reduces the next melee attack's damage and stuns the assailant every so often. You're able to proc this on yourself, stunning yourself for a ludicrously long time. From my experience, this happens most often when using the Boarding Axe to destroy walls of submarines or ruin walls.

[This](https://www.youtube.com/watch?v=uhs311S_gek) video shows the bug in action. Lightning Wizard stunning yourself can be funny, but it happens for such a long time that it can genuinely get you killed in the wrong situation.

As a sidenote, I have only really seen this happen with the Boarding Axe, though other melee weapons might not be exempt for this.

### Reproduction steps

1. Be an Engineer with Lightning Wizard (Electrician Tree, last trait);
2. Swim out to a ruin and start going at the walls with a boarding axe (best done while inside a cramped corridor);
3. Inevitably hit yourself;
4. Get stunned for a long time.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
You hit the wall which created shrapnel and shrapnel triggered the talent on yourself

**Comment by Regalis11** [comment]
> You hit the wall which created shrapnel and shrapnel triggered the talent on yourself

Yep, that seemed to be the case. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9960709f88ac6d67e6b52ce89a9a23b13293d1de (lightning wizard now ignores any damage you do to yourself).
