### ISSUE TITLE
Traitor mission given Radio Jammer spawns without a battery

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12913]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On traitor missions where you receive a radio jammer the radio jammer spawns without a battery 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/b7fff0fe-4968-496b-8cad-c112fc9c7152)

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/52547f7e4da2946745af67f92e17f7d684a1d723

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
