### ISSUE TITLE
entity menu has a memory leak

### ISSUE THREAD

**Issue by deltanedas** [Regalis11/Barotrauma#12919]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

entity menu leaks memory when clicking a tab

### Reproduction steps

0. be in sub editor
1. maybe unimportant, set filter to something (i used bow)
2. open htop
3. spam click all
4. see memory usage rise

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
no
```

**Comment by SomeRandomNoobKekeke** [comment]
Did you mean open entity menu -> click random tabs?
I tried, after i clicked all tabs memory stopped rising

**Comment by deltanedas** [comment]
click the same tab (all)

**Comment by SomeRandomNoobKekeke** [comment]
clicked tab (all) many times, memory usage stopped rising at 2250MB, i guess because all sprites loaded
what mods do you use?

**Comment by deltanedas** [comment]
quite a few, all mods contain 39mb of textures total :trollface:

**Comment by SomeRandomNoobKekeke** [comment]
ye i meant no c# mods that also can leak or change loading method
![barodev small](https://github.com/Regalis11/Barotrauma/assets/122838333/f86787d7-cbe5-4b91-8076-b88ce24f8aa6)

**Comment by deltanedas** [comment]
luacsforbarotrauma :trollface:

**Comment by Regalis11** [comment]
I could not reproduce this. The memory usage does seem to stop rising after all the sprites have been loaded. I think it might have something to do with the mods too.
