### ISSUE TITLE
Everyone got revived on the outpost

### ISSUE THREAD

**Issue by timofeja19** [Regalis11/Barotrauma#12915]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

in singleplayer at the very first outpost, after killing everyone on the outpost and relaunching game, everyone got revived and leader of the outpost gave mission from church of husk even though originally outpost was controlled by europe coalition

### Reproduction steps

1.Start a singleplayer campaing
2.Clear first outpost entirely from NPC's
3.Relaunch the game
4.Find outpost leader
5.He gives a mission from different fraction

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by timofeja19** [comment]
I used mods Improved Husks from The ninja scout and Husk mod missions from Hypes
The mission was Biohazard
Manager said: Need work? We have it. Lets say that... Neighbouring outpost very need research samples. Deliver them, and we will pay. Just don't ask any questions
![Screenshot_718](https://github.com/Regalis11/Barotrauma/assets/102463239/c5cc81d7-fc58-4815-9d25-e55e86609cd9)

**Comment by Regalis11** [comment]
It seems that mod adds husk missions to the outpost manager, so this seems to be an intentional feature of that mod.
