### ISSUE TITLE
Can't recover from being braindead after taking even a little damage while stunned after disconnect

### ISSUE THREAD

**Issue by legser4** [Regalis11/Barotrauma#12914]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Don't think this exact issue was reported, but we were unable to recover from being braindead if you took even very little damage while stunned from disconnecting. 

### Reproduction steps

Host a server and have a friend connect to your server

What should happen: Friend leaves, becomes stunned and even if he takes some damage, hit vitality stays above 0, several minutes pass, he becomes braindead, joins server, his character is revived with the damage he took before braindead and all is good 

What's happening: If your friend leaves, you harm them (burn them with a welder, hit with a screwdriver, etc), they are unable to comeback and can only start spectating, but they had over 0 vitality and should have been revived according to patch notes.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by BlackMoons** [comment]
I don't even get why braindeath is a state in barotrauma. 

I find the game play with friends much better with the kill disconnect timer set to hours, such that if you 'protect' the unconscious body (read as: keep it from drowning in a puddle or being eaten by mudraptors) till the end of round, they don't 'die' and lose skills/items/etc.

Only downside I can see is not getting their wallet/items restored to the ships if they never come back.

**Comment by Regalis11** [comment]
> I don't even get why braindeath is a state in barotrauma.

It's just to visualize that the player is no longer there.

> I find the game play with friends much better with the kill disconnect timer set to hours, such that if you 'protect' the unconscious body (read as: keep it from drowning in a puddle or being eaten by mudraptors) till the end of round, they don't 'die' and lose skills/items/etc.

I think you're misunderstanding how the braindeath works. In a sense, it does that "protection" for you - once the character goes braindead, they're safe: they won't lose any skills or items. If they _didn't_ go braindead, they would lose skills and items if they got killed by something else when the player is away.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a1f4d2cea90137ae1e97f10cd9f53e847628c75

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4589/commits/7a1f4d2cea90137ae1e97f10cd9f53e847628c75

Tested in listen and dedicated.
Tried rejoining unharmed, harmed (little), harmed (unconscious) and dead
While dead no skill loss was observed

No issues found
Closing ticket

**Comment by Regalis11** [comment]
Reopening. It seems that the server keeps repeatedly giving the player control of the character, and then removing it, if the client is in the lobby or has opted to spectate.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4593/commits/6bdd32cd308286098d8b719ca42cd4cc73e6f6cd

Tested same things as previously.
Joining with spectating turned on.
Also this:
> Particularly problematic if the KillDisconnectTime was low: if it was 0

Player only gained control when he truly joined the game and character was not revived unnessecarily

No issues found
Closing ticket
