### ISSUE TITLE
+25 skill after repairing something with 0 skill

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#12924]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you have absolute 0 skill without boosts to them(like from assisstant's clothes), then repairing something like junction boxes or pumps gives you straight up +25 skill to electrical/mechanical.

### Reproduction steps

1.setskill all 0
2.Repair something
3.+25 Electrical/Mechanical Engineering

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Linux

**Comment by Abkim27** [comment]
> minimum skill without cheats is 5 (artie) so is this really an issue

Well, modding is a thing, so easly there can be professions with 0 skill if someone would want it

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4503/commits/23b966af6f3b7f485eded902ec8f4638244e56e7

Tested with other skill related changes in: https://github.com/Regalis11/Barotrauma-development/pull/4503

No issues found
Closing ticket
