### ISSUE TITLE
Periscope(legacy) isn't work correctly

### ISSUE THREAD

**Issue by SpartaT300** [Regalis11/Barotrauma#12926]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The legacy periscope must additionaly holding RMB to switch to turret vision and able to control turret when interacting. Release RMB will instantly exit periscope(legacy).

### Reproduction steps

1.Open the submarine editor.
2.Place any turret and a periscope(legacy).
3.Connect periscope(legacy)'s "position_out" to turret's"position_in".
4.Connect periscope(legacy)'s "trigger_out" to turret's"trigger_in".
5.Click "Test" to test the submarine.
6.Control character to interact with periscope(legacy), then hold RMB.
7.Release RMB.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! This is not a bug, the legacy periscopes used to intentionally work like this (and we generally don't update legacy items, they're just kept there for backwards compatibility reasons, and in case someone for some reason wants to still use the old behavior).
