### ISSUE TITLE
Culling could be tighter

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12922]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Culling of objects in the game could be a little tighter to the object bounds. 

For example, labels, If you put 1000 labels in a cluster, you can observe a pronounced increase in render time when they are on screen. But it seems they still cause that loss when they are nearly half a screen past the edge of view. Only when you get really far away does the game cull them (render time drops back down to baseline) 

### Reproduction steps

Place many labels on a new blank submarine to cause a pronounced increase in rendertime when they are rendered, as shown by showperf.

enable 'test' mode and use freecam to scroll till the objects go off screen, observe how far offscreen they need to be before render time drops back down. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
I've made a [mod ](https://steamcommunity.com/sharedfiles/filedetails/?id=3043340865) where you can play with culling setting
come be my test subject

**Comment by Regalis11** [comment]
I think it could be there was some reason there's quite a bit of margin to the culling (some visual elements might extend beyond the extents that determine whether an entity is on the screen?), but I feel that might have been decorative sprites which nowadays are taken into account in the culling. So I think we can probably reduce the margin, although we need to make sure it doesn't cause any unintended side-effects.

**Comment by BlackMoons** [comment]
Thus far the only time iv seen culling screw up, is when you stick a stack of items in an ammo holder/railgun holder, it displays each item in the stack individually and can extend way out of the parent object, yet the culling is based on the size of the parent object. 

But generally sticking 'stacks' of ammo into things only designed to hold individual items is only doable by making custom tagged items or using custom 'stackable coilgun ammo' etc mods, so Id consider the solution to that is just 'Don't stick stacks of items in things only designed to hold a finite number'

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c8707735daf08b68076fa686973a2cffc6c19b24

**Comment by BlackMoons** [comment]
Thanks! Looking forward to the change.

**Comment by BlackMoons** [comment]
Seeing some very minor flickering/early culling of NPC's at the far left edge of the screen on the latest update, if culling change made it to the latest update. Could maybe be performance fix mod causing the flickering. (Seems like they disappear when their left edge goes offscreen?)

**Comment by SomeRandomNoobKekeke** [comment]
[they didn't change culling constants or method ](https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaClient/ClientSource/Map/Submarine.cs#L24)
and performance fix doesn't change culling

**Comment by Regalis11** [comment]
@BlackMoons 

The culling changes are still being tested internally, so they're not in the latest update (nor unstable yet). Thanks for the note though, I think we need to pay attention to the NPC culling when testing these changes.

**Comment by Rokvach** [comment]
Tested, I didn't notice any issues in culling, tested in various ways on colonies with mods etc, viewing from player pov, turret pov and freecamera zooming in/out to see if there's any popping. Also tested the mentioned NPC's. Didn't encounter any issues, can be merged and closed.

**Comment by Rokvach** [comment]
Also extended my test a bit from the previous comment to actually see what exactly was culled outside of the screenview by pausing the culling and moving around to see that the culling was correct.

**Comment by BlackMoons** [comment]
@Rokvach Please make sure ice spires are culled too.tests (see #12986 ) seem to suggest they where not or where very poorly culled.
