### ISSUE TITLE
Plasma cutter for ores in the map desync

### ISSUE THREAD

**Issue by JJRcop** [Regalis11/Barotrauma#1292]
**Description**
The client side progress bar for plasma cutters doesn't sync well with the server when mining for ores on the ice. I have filled my client's health bar of the ore and still can't pick it up, I have to continue cutting and spamming E to pick it up.

**Steps To Reproduce**
If you use a plasma cutter to cut an ore on the ice, you will eventually fill up your client's "cut" bar, but you can't pick up the ore. The client's bar will stay filled and won't sync with the server, so you have to keep cutting and spamming E on the ore until it gets picked up.

**Version**
v0.8.9.6 Windows 10 1809

**Additional information**
I think the client should check with the server every second when actively cutting. The way I believe it should work is when you start cutting it queues a sync for 1 second later, which syncs even if you're not cutting when the sync occurs. So, if you just tap a rock with the cutter and don't keep cutting, it will still sync the progress with the server anyway after 1 second.

Some ores don't have this problem because they don't have a lot of health.
I haven't tested, but this might be a symptom of a larger problem with syncing.

**Comment by NilanthAnimosus** [comment]
I feel this is an issue, but on top of that they also appear to be quite hard to hit sometimes - I feel the physics body size might want to be increased as well as the syncing of their health / ability to pick up (Though I feel somehow its related to their health value not seeming correctly synced as well).

**Comment by Regalis11** [comment]
Fixed in b9574dd
