### ISSUE TITLE
ticking time bomb can be requested by traders

### ISSUE THREAD

**Issue by deltanedas** [Regalis11/Barotrauma#12934]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

in special offers traders can ask for ticking time bombs...

while it might be ok for deepdiver ducks i guess a time bomb is something that probably shouldnt be requested

also it shouldnt request traitor items at all on singleplayer since its not possible to get them in vanilla

![15:15:09](https://github.com/Regalis11/Barotrauma/assets/39013340/a46470cc-d64c-432f-8e13-2d5b08c3c373)

### Reproduction steps

its rng

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/baa6b63d3c349e2ab96044d1a58c2f3b2ae0b3a1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
