### ISSUE TITLE
item Assembly doesnt apply impassable="false" parameter of door component 

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12935]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Well I wanted to make ducts passable via item assembly alteration but it turns out it doesnt work, even though stuff like welding works fine!

### Reproduction steps

1. Download [Barsuk_Wrecked.zip](https://github.com/Regalis11/Barotrauma/files/13196086/Barsuk_Wrecked.zip) Item assembly
2. Place it in sub editor
3. load in sub editor
4. open and try to pass through any ducts

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Impassable is not a property you can edit per-item.

**Comment by PanmanS** [comment]
Aw cmooon, more item assembly freedom

**Comment by Regalis11** [comment]
I'm not opposed to changing this to true, but I still don't think the issue tracker is an appropriate place for these kinds of requests. :)
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/6723dc1b-7dee-4730-a520-74bbfec1dfe1)
