### ISSUE TITLE
Crash: Exception: Unable to cast object of type 'Barotrauma.RectTransform' to type 'Barotrauma.ItemPrefab'.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#12932]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The submarine was docked and I was putting things in order and sorting out the loot. I used a deconstructor. Then the game crashed.

### Reproduction steps

I do not know how to reproduce

[crashreport (26).log](https://github.com/Regalis11/Barotrauma/files/13193677/crashreport.26.log)

[config_player_xml.txt](https://github.com/Regalis11/Barotrauma/files/13193680/config_player_xml.txt)

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by pavel4win** [comment]
The crash occurs when I open the search tab in the navigation terminal and enter any letter.
config_player I sent in previous comment.

Here is save file:
[november2023noCreaturePack.zip](https://github.com/Regalis11/Barotrauma/files/13193862/november2023noCreaturePack.zip)

**Comment by Regalis11** [comment]
It does seem like the error is coming from the "Item Finder Count" mod. The error occurs in a method called `UpdateNameText` in the class `ItemFinderCountMain`, and since that doesn't exist in the vanilla game, there's nothing we can do about it I'm afraid.
