### ISSUE TITLE
Reactor doesn't output expected power from Turbine slider position

### ISSUE THREAD

**Issue by NaturalBornCamper** [Regalis11/Barotrauma#12931]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Turbine power is supposed to be linear from the [wiki](https://barotraumagame.com/wiki/Nuclear_Reactor#Mathematics):
![image](https://github.com/Regalis11/Barotrauma/assets/1697306/028a699b-105c-4829-93ca-0af10655cf69)

So if you max reactor output is 100 kW, then setting `SET_TURBINEOUTPUT` to 45% should output 45 kW yet it seems broken and outputs less.

You can see here my reactor's max Output is 3345 kW (manually sliding the turbine all the way to 100%):
![image](https://github.com/Regalis11/Barotrauma/assets/1697306/0153a14f-7814-4a1c-87b5-8393357936f2)

Then if if my reactor controller sets the turbine to 20%
![image](https://github.com/Regalis11/Barotrauma/assets/1697306/86b5438a-3479-4696-bf16-4fca4b057a09)

It gives only 578kW instead of 669kW:
![image](https://github.com/Regalis11/Barotrauma/assets/1697306/1868b5bb-83c0-40f4-b4da-2b3a8c89c73c)

I tried with another value just in case:
![image](https://github.com/Regalis11/Barotrauma/assets/1697306/9ccd175f-08ea-4292-9d2b-673d22e8edc2)
![image](https://github.com/Regalis11/Barotrauma/assets/1697306/b56209ac-bd8f-4400-8333-e970175e55b4)

So this is really messing up my calculations for my overclock and battery charge controller.

Is it because the Turbine output is not linear anymore but the wiki wasn't updated?

### Reproduction steps

1. Load included savegame
2. Use captain that has electrician goggles
3. Compare turbine slider and `power_out` to see it doesn't match the formula (Slide turbine at the max before to verify max output if needed)
[reactor_not_expected_power_output.zip](https://github.com/Regalis11/Barotrauma/files/13192330/reactor_not_expected_power_output.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The turbine output is linear, but you need a certain minimum amount of heat to run the reactor at a given turbine output rate, as mentioned in the wiki. In this case, with the fission rate set this low and the turbine output at max, you aren't generating enough heat, so the reactor cools down and can't reach the maximum output.

**Comment by Regalis11** [comment]
Hard to say what's going on there without seeing where the fission rate is, but to me it seems like you're still trying to run the reactor at a very low fission rate relative to the turbine output (see the green area on the fission rate gauge - you're supposed to stay within those limits). You're also using an excessive number of fuel rods, which makes it more difficult to keep it from overheating the reactor.

**Comment by Ek-Videogames** [comment]
> Hard to say what's going on there without seeing where the fission rate is, but to me it seems like you're still trying to run the reactor at a very low fission rate relative to the turbine output (see the green area on the fission rate gauge - you're supposed to stay within those limits). You're also using an excessive number of fuel rods, which makes it more difficult to keep it from overheating the reactor.

Maybe there is a bug/mistranslation/outdated with how the 'pies' are drawn, because from my experience (even 'vanilla' automatic control) always runs the reactor at the "critically low temp" warning level and manually increasing the fission rate to what the dials claims is "optimal" (middle of the green on both) will actually overheat the reactor if left that way.

**Comment by Regalis11** [comment]
@Ek-Videogames 
That does seem like a bug. The "optimal" area on the fission rate gauge is kind of arbitrary, but the rate should generally be above  the lowest optimal range. I gave a quick test at a couple of vanilla subs, and I could find a single one that would've run the reactor at a "critically low temperature" - in all of them, the autopilot shoots for the green areas and generates an appropriate amount of power.
