### ISSUE TITLE
Campaign desync in steam on round start, entity not found (Save file desync or level/mission gen problem?)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1293]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The campaign works remarkably well, and went through several missions quite successfully and was pretty fun. I even had the glory of getting killed due to another syncing problem and suffocating with a mask on my face.

**Steps To Reproduce**
No known reproduction steps as theres too little information, I did request from the host a copy of the saves directory which he happily provided, but its unknown if this is tied to the save as of yet.

We were trying to heat towards the infested area, through a natural formation.

Taking a different path did appear to work, but we had tried different things (such as moving out / deleting save files or attempting to rehost completely perhaps), this is the save file after ending round and thus not saving progress, we had also lost a multiplayer character or two when it had worked.

**Version**
0.8.9.6 steam closed alpha. Server host unknown operating system, client of the host was however desyncing with himself as well.

**Additional information**
Unknown to any other information as of yet, I'll see if I Can host more campaigns or dig into this, I will leave the save file directory here though for now as well:

[Saves.zip](https://github.com/Regalis11/Barotrauma/files/2982197/Saves.zip)

Clients saw in their consoles the following, in 3 attempts, we had 6111, 6124, 6111 as entity not found:

![](https://cdn.discordapp.com/attachments/540532000860143616/557463147955486721/unknown.png)

![](https://cdn.discordapp.com/attachments/540532000860143616/557463435261116416/unknown.png)

![](https://cdn.discordapp.com/attachments/540532000860143616/557465126584844300/unknown.png)

**Comment by NilanthAnimosus** [comment]
Additionally going to include my own Multiplayer saves folder from my own client, I no longer appear to have the same submarine in the temp folder, only the multiplayer save folder:

[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/2982522/Multiplayer.zip)

**Comment by thegrb93** [comment]
Sparky here, I can give more files if needed.

**Comment by Regalis11** [comment]
@thegrb93 If you have the server-side save files I think they could be very useful in diagnosing this!

**Comment by NilanthAnimosus** [comment]
actually the first files I Gave were the ones sparky handed to me. in theory, those were the server-side save files unless they were actually his clients and his servers are in a different directory somewhere.

**Comment by thegrb93** [comment]
@Regalis11 let me know which file. I can get them when I get off work.

**Comment by NilanthAnimosus** [comment]
sort of like sending a netmessage of imminent disconnection, and its reason. and the client decides if it should respond to the server or simply disconnect. and from there build up a more useful case to debug or theorize on why these issues occur, their honestly quite hard or annoying to fix with what we have regalis

**Comment by Regalis11** [comment]
@thegrb93 Actually I can't think of any additional files we'd need since the ones Nilanth sent are from the server.

@NilanthAnimosus Actually juan has already implemented something similar to than in ef9afed, but I just noticed handling the error reports isn't present in GameServer.cs anymore. I think we've messed up a merge somewhere along the line (either when working on client-server-separation or when merging dev to the old "legacy master" branch). I'm re-enabling it atm and adding some extra debug information to help us get to the bottom of this.

I have a hunch that this could be caused by the level generator not creating the same level client-side as server-side (see #848). I tried to remedy the issue in dd33af0 but it might be that it wasn't enough, and that we need to implement a more robust system to ensure the results of the procedural generation are always the same on every system.

**Comment by NilanthAnimosus** [comment]
not just the level equality if the level is equal, but I mean the specific list of entities and well, how different it is. but I was thinking in general, in case its mission or spawning related, the sub is different, player inventories...any random chaotic possible reason as the ID's may have given more information.

Of course, we definately need that level equality check readded. thats a pretty good way to determine if the level generated is the same, but if there was a different in another way (IE. campaignID and save files had gone out of sync somehow, or something else caused the ID's to missmatch in the code somehow out of the direct level gen) it would have been nice to have, was just an idea since the network dumps we did have before were...not very helpful to say the least.

**Comment by Regalis11** [comment]
The report logic in ef9afed should help figuring out the cause even if it's something else than the levels being different, because the clients report the ID of the missing entity to the server and the server sends back an error message with a bit more details about what went wrong.

**Comment by NilanthAnimosus** [comment]
oh I see, alright :+1:

**Comment by thegrb93** [comment]
@Regalis11 also in that save, the docking is completely broken, cant detach from the city. Can you fix that too?

**Comment by thegrb93** [comment]
We repaired the ship and then realized it was stuck forever x<

**Comment by thegrb93** [comment]
I'll make a new issue

**Comment by NilanthAnimosus** [comment]
another set of saves where my game just utterly smashed itself.
 comparing dedicated console using dumpids, alongside the characterdata.xml, found the ID is contained within in this case.

its a flashlight I picked up from the sub, not store bought, not equipped at level end (never was equipped) - I do not know why, but a random item in my characterdata apparently does not exist for the client.

I do not have the same players in this game, it was me alone. I even tried copy pasting over to my client directory the exact same save files, characterdata xml and temp folders and such, to no avail on game restarts and rejoins. nothing lets me join this round anymore with myself.

Here is my dedicated server saves folder (Save is "sparky 0") - no location was changed. just start with no mission without buying a single item.

final note - multiple campaign starts were done by my clients, its possible they made a new campaign with the same submarine as a previous campaign, I do not know if this is key info for this issue so im including it.

you may need to tweak my character data steamid and/or IP to get the same situation reproduced:

[Saves dedicated.zip](https://github.com/Regalis11/Barotrauma/files/2986507/Saves.dedicated.zip)

[Saves - steam client.zip](https://github.com/Regalis11/Barotrauma/files/2986510/Saves.-.steam.client.zip)


![image](https://user-images.githubusercontent.com/29177976/54658790-1f902b00-4ac7-11e9-954b-8ab4b5d7eeb6.png)

**Comment by Regalis11** [comment]
Thank you so much, I was able to reproduce it now and figured out what's causing it (and potentially many other disconnection bugs as well). The IsOn-property of the LightComponent creates a network event when the value changes, and if it's done while loading the item, the clients will not be able to read the event because the event that spawns the item isn't created until the item has been loaded (i.e. the clients will attempt to turn on the light before knowing the light exists).

**Comment by NilanthAnimosus** [comment]
oh good, something I never would have suspected lol

**Comment by Regalis11** [comment]
I think 81fafaf should fix this.

**Comment by NilanthAnimosus** [comment]
Do you think the changes in code between the current and then will cause syncing issues? I feel most of its server-side with the exception of the level check as I imagine that'd cause significant desync to implement early.
