### ISSUE TITLE
You can still see who is destroying even if your view is blocked by obstacles

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12949]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/73634685/a504fb1b-1d48-4f5f-a384-6e1a83b5ceb8)
![image](https://github.com/Regalis11/Barotrauma/assets/73634685/8c1e0294-759e-4611-8d1e-a09eaf66b9d2)

This is not a bug, but to the traitors, their actions are easily exposed.
The same goes for using a wrench to remove the button

### Reproduction steps

1. use crowbar to open a door
2. other players can see the state of the door even if they can't see the door.

### Bug prevalence

Just once

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
