### ISSUE TITLE
In "deadoralive" traitor event, the traitor cannot be seen through glass by other characters.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12947]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/73634685/a2925670-a9bb-4911-b545-6d2c13ef6447)
![image](https://github.com/Regalis11/Barotrauma/assets/73634685/d7eaf1af-5362-4c7a-b8b4-3fc74f044104)
I completed the first objective although they actually indeed "saw" me through glass.
In the picture, "证据已安放 - 现在就等人发现了…" is the Chinese translation of "The evidence is planted—now someone needs to discover it…"

### Reproduction steps

1. trigger traitor event "deadoralive"

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/11e288f4e5a557e557e4d0852ce3df2926478897

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
