### ISSUE TITLE
Beneficial medical drugs side effects are extremely lethal even to full vitality characters

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1294]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using beneficial drugs, it appears the side effects of the medicine is incredibly amplified, perhaps due to bug fixes related to applying afflictions to multiple limbs, this has caused drugs like fentanyl (-10% oxygen per second for 5 seconds as a doctor) to kill a full health character in about 2-4 seconds to suffocation.

This has become so much more lethal than any intentionally lethal drug, be it radiotoxin or sufforin, that I to much shameful amusement assassinated rokvach with it as a traitor, this does however need looking into or fixing.

**Steps To Reproduce**
Inject self or fellow comrade with fentanyl, drugs like morphene have less of (but a very noticable instant) kick, until they become overdose, which is almost a straight knockout to oxygen if not again lethal at 25-30% overdose. best to test fentanyl for the cause of this.

**Version**
0.8.9.6 steam closed alpha.

**Additional information**
I am not sure as I have not even read this code or tested, but perhaps this is somehow related to the commit ebf01c610d3b13c61178c4ba3b2d8a5bce2c7bad but its applying oxygen to every limb or something (just hypothesizing, or even it is multiplying the drain by the count of limbs on a character) - which could explain the rapid oxygen deprivation well beyond what it appears to be intended to drain.

**Comment by Regalis11** [comment]
Fixed in 7feceab
