### ISSUE TITLE
In "deadoralive" traitor event, the traitor will be seen no matter how far away it is from other characters, as long as there are no obstacles between them.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12948]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/73634685/1df0cec1-c3cf-4215-88f4-66597a8f224c)
![image](https://github.com/Regalis11/Barotrauma/assets/73634685/637bd4c7-8716-4798-b8c0-43ce789ed551)

### Reproduction steps

1. trigger traitor event "deadoralive"

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
