### ISSUE TITLE
The console command traitorlist cannot tell us who the secondary traitors are

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12946]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In traitor event "murder mystery", there are total 3 traitors (murderer, knows weapon, knows victim). By using console command "traitorlist", we only know who's the murderer.
If the other two traitors are unwilling to disclose their identities during the review, we will never know which players are the traitors.

### Reproduction steps

1. trigger the traitor events "murdermystery"
2. type console command "traitorlist"

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/78d0df637e879f81703dce6271bc834d84e2b44e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
