### ISSUE TITLE
Circuit Box: Cant connect to most recently placed component until it is moved

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#12953]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When editing a circuit box, I am unable to connect any wires to the most recently placed component until either a newer component is placed (which just transfers the problem to the newer component) or until I pick up and move the component slightly. 

If I attempt to drag a wire onto the component pins, nothing happens. If I attempt to drag a wire from the component to somewhere else, it picks up and drags the component instead of creating a wire.

This issue is easy to reproduce.

https://github.com/Regalis11/Barotrauma/assets/16128947/5ae24871-3a7d-46ff-9b66-359b52753e58

### Reproduction steps

1. Place a circuit box
2. Place a component inside it
3. Without moving the component, attempt to drag a wire to it. Notice it does not connect.
4. Attempt to drag a wire from the component. Notice it will drag the component instead of creating a wire.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4606/commits/25607c7d222ed848ca60028c79a5d04fca1650bf

Setup some circuitboxes in SP, MP (listen and dedicated) and sub editor.

No issues found
Closing ticket
