### ISSUE TITLE
[Bug]: The shrapnel still launching upwards when it was spawned in "OnImpact"

### ISSUE THREAD

**Issue by MJJJJN11** [Regalis11/Barotrauma#12956]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

      <StatusEffect type="OnImpact" target="This" Condition="-100.0" allowwhenbroken="true">
        <SpawnItem identifier="testshrapnel" spawnposition="This" count="5" aimspread="4" rotationtype="Collider" rotation="0" />
      </StatusEffect>
      <StatusEffect type="OnBroken" target="This">
        <Remove />
      </StatusEffect>

### Reproduction steps

1. When the shrapnel launcher is spawn the shrapnel in "OnImpact"
2. In the same time, the shrapnel launcher will be removed
3. The spawned shrapnel will launching upwards everytimes

https://github.com/Regalis11/Barotrauma/assets/149501175/4db1b1f4-d75f-4483-846e-5a21240b34aa

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I believe the issue here is that the projectile gets removed first, before spawning the shrapnel. The first status effect sets the condition to 0, which removes the item, and the shrapnel is spawned after that. You can probably fix this by changing the effects to

```
<StatusEffect type="OnImpact" target="This">
  <SpawnItem identifier="testshrapnel" spawnposition="This" count="5" aimspread="4" rotationtype="Collider" rotation="0" />
  <Remove />
</StatusEffect>
```

We do need to look into this regardless though, it's very unintuitive that the order of the effects causes these kinds of issues.

**Comment by MJJJJN11** [comment]
Thanks for this answer,it is indeed this issue caused by the order.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/39d9cf229868b6b1853d173f63f6d8723ba87171
