### ISSUE TITLE
Hotfix v1.1.19.3 broke "maxstacksize" attribute

### ISSUE THREAD

**Issue by DodoBirb1248** [Regalis11/Barotrauma#12954]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

<ItemContainer> "maxstacksize" attribute does not function, as setting it to anything above 8 has no impact, even with vanilla items such as the Medic Crate (and any other crate for that matter) where it is explicitly stated in the xml (highlighted in red) that it should stack to 32 (as it did prior to this hotfix).
![image_2023-10-31_082218847](https://github.com/Regalis11/Barotrauma/assets/149466807/51ef5fe7-6aa6-4181-b36f-5204e898aa6a)

![image_2023-10-31_082349384](https://github.com/Regalis11/Barotrauma/assets/149466807/8cb16578-78ce-47df-8807-ba2e6e66c4f5)

### Reproduction steps

1. Start campaign/submarine editor/multiplayer game
2. Spawn 32 morphine with console commands
3. Spawn medic crate
4. Observe how the morphine only stacks to 8 in the crate,

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The hotfix didn't change the behavior of `MaxStackSize` in any way. The only thing we did was making `MaxStackSizeHoldableOrWearableInventory` default to the same value as `MaxStackSizeCharacterInventory`. Morphine's `MaxStackSizeCharacterInventory` is 8, and it doesn't define a different stack size for holdable/wearable inventories, which means it stacks up to 8 in crates too.
