### ISSUE TITLE
reactor autotemp sometimes operates below the necessary requirement and stays at that level

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1295]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have noticed on some submarines autotemp does an awkward or bad job of managing the reactor - and by extention at times the AI as they use the same code (just at a faster rate).

For instance, the load can be 2000, and the reactor outputs 900-1000 or so, and just sits at a value without attempting to raise the fission rate or turbine output, this is an extreme example with fabricated numbers, but this does sometimes occur but as the more extreme example.

**Steps To Reproduce**
I believe it might have been the orca (Not 100% sure) that sometimes suffers from a bad reactor that refuses to turn itself on sometimes.

0.8.9.4 - 0.8.9.6 steam closed alpha (as far as I recall, still appears to be a thing but was never sure to report this or not)

**Additional information**
I am not sure exactly what the conditions are, but I believe it could be that the rods at lesser condition yield less fission, and the autotemp might not be factoring this in whatsoever.

If this is not the case, I am not sure why the reactor's autotemp will often  sit below the needed power requirement despite a higher fission would in fact yield the necessary energy (and on manual, always does).

**Comment by Regalis11** [comment]
I think this might be caused by the low maximum output of the reactors on some of the vanilla subs (for example on Orca the load is sometimes higher than the maximum output of the reactor). Although it could also be a separate issue, because the same problem should also occur when operating the reactor manually. Have you actually tried switching to manual and been able to fix the problem that way?

But in any case, I did some changes in 1561fa4 that might fix this, or at least communicate it more clearly when the reactor cannot be pushed any further.

**Comment by NilanthAnimosus** [comment]
I recall several times where I stared in confusion at an AI or autotemp blissfully keeping the reactor at a certain level, while simply tweaking it myself all I needed to do was drag the fission rate bar along a bit and perhaps the turbine output. I had caught this a few times but never actually took pictures of it, and it came back to my mind and I figured I would report it.

I'll have to catch it again and show the AI sitting at what I consider to be an unusual power level, its typically at an idle state and other times it has been fine.

**Comment by NilanthAnimosus** [comment]
using the fixes I had some clients comment on how smooth the reactor runs on my server, as well as seeing the autotemp often has it exactly at halfway between the ideal range on the lower right side and seems to operate pretty well, even though my client doesn't have these changes itself (Only the server) it seems an overall improvement thus far.
