### ISSUE TITLE
Empty job in role selection screen

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12960]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There is empty job in multiplayer role selection screen.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/c2c953fb-66f5-4820-9c0b-141e6c034790)

itchyOwls comments for possible reason:
"Pretty sure it's because we added a dedicated job for the outpost security officers. Should have hiddenjob="true", but doesn't."
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/9fd8290d-4ae0-4627-bade-5dd41509c8b8)

### Reproduction steps

1. Start multiplayer
2. Pick job role
3. Observe spooky ghost job

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

winter-update

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a12bbc5331c32debadd21abee3e51ea8de722709

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/a12bbc5331c32debadd21abee3e51ea8de722709

Job was still visible on role selection and bots could select it for their job on multiplayer.
Modifying <Job> line to contain `minnumber="0" maxnumber="0" initialcount="0"` Fixed it.
```xml
<Job identifier="outpostsecurityofficer" vitalitymodifier="10" idlebehavior="Patrol" minnumber="0" maxnumber="0" initialcount="0" hiddenjob="true">
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bdc9f35c1a7155bf4f42f17b420a42431dc7e4ab

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/bdc9f35c1a7155bf4f42f17b420a42431dc7e4ab

vipsecurityofficer is not visible anymore in role selection.
However bots can still pick it multiplayer.
![2023-11-09_09-58](https://github.com/Regalis11/Barotrauma/assets/8488224/5f5ba613-bb42-4c21-a977-9760ef44eac1)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fc130e

**Comment by Rokvach** [comment]
Tested, seems to be finally working correctly. Closing.
