### ISSUE TITLE
turret aim is predicted differently clientside than serverside

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1296]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This may be nothing / standard for the networking, but I noticed the turret would reach the aim faster client side than on the server side, or the bullets just figured in a different direction somewhat. often I would be firing straight up with my turret straight left despite I could move fairly normally.

**Steps To Reproduce**
I was using a none-weaponry class (IE. medical, engineer or mechanic) with a low (20 or below roughly, maybe even 12-15) weapons skill. swirling a coilgun and firing showed my turn locally was much faster than the servers, yet I didn't feel too laggy in actual movement.

**Version**
0.8.9.6 steam closed alpha

**Comment by Rokvach** [comment]
There's been allot of improvements relating this issue so I am safe to bet that it has been improved by now, closing.
