### ISSUE TITLE
Deepdiverduck typo in item definition

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12961]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Deepdiverduck has miss spelled frquencymultiplier in Misc/traitor_items.xml
```xml
<StatusEffect type="OnImpact">
  <sound file="Content/Sounds/Damage/StructureBlunt1.ogg" range="500" frquencymultiplier="1.2" />
  <Explosion range="50.0" showeffects="false" structuredamage="10" decal="" />
</StatusEffect>
```

Should be frequencymultiplier

### Reproduction steps

Open Misc/traitor_items.xml
Look at line 23

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2c9c197d240850275fa5467d8bda2c3958829869

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
