### ISSUE TITLE
You can craft masterpiece item, if there is 2 or more skills needed to craft that item

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#12963]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If there is an item, which can have qualty, and also has a need of multiple skills to craft, it can be made masterpiece even without talents. To do that, you would need to have those multiple skills at 100 or more.

### Reproduction steps

1.Need to make custom item, due to vanilla lacking items with description given above
2.setskill all max
3.Craft

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Linux

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4464/commits/662b33f214548ffcbc7345bb29e82e20cd7099a8 (Commit in private repo)

Multiple skill requirements boosts only 1 level of quality.

Testing notes in: https://github.com/Regalis11/Barotrauma-development/pull/4464

No issues found
Closing ticket
