### ISSUE TITLE
Components can be sold from inside Circuit Boxes

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12968]
Credit to bananaman (festive) for testing and writing the ticket

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/c8dedf9b-799b-4d8e-9d6f-6705fef1bb54)

### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After a component is placed inside a circuit box, it can be sold to outpost merchants which will cause a console error at round end and prevent the next round from starting

Interestingly, the component will remain in the box's UI but will not function (note how the door is no longer locked open after selling the component in the video)

https://github.com/Regalis11/Barotrauma/assets/37850646/2571740d-1679-42f4-b650-f479fd7e5a15

Relevant error:

### Reproduction steps

1. place a circuit box
2. put components in the box
3. sell components off the submarine
4. try to start next round and observe the perpetual loading screen

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/ef2a9f7c-6748-4888-a7b4-533ee3f53e7f)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4617/commits/eca42e63107ce543a28917587d18528aa56775e7.

Tested & merged into the next unstable, closing the ticket.
