### ISSUE TITLE
ragdoll key no longer appears to sync or function correctly

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1297]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
in multiplayer, holding the ragdoll key makes it look like you or others ragdolling via key are crouching, though you can still grab a player who is ragdolling in this crouch-like way, it is as if the ragdoll or collider is being kept held high, even perhaps by the collider itself (which iirc, floats off the ground).

**Steps To Reproduce**
use ragdoll key as a client on a server.

**Version**
0.8.9.6 steam closed alpha

**Comment by NilanthAnimosus** [comment]
just a small note that came to my memory but I don't think disconnected players are properly ragdolled/stunned either, don't recall fully now, but might be the case.

**Comment by NilanthAnimosus** [comment]
This is even stranger - but the ragdoll button is fine for myself if I am connecting to my dedicated server via 127.0.0.1 - while its broken if I am on anothers server.

Additionally if ragdolling has issues, so does players whom disconnect from the server but are alive due to a killdisconnected timer.

**Comment by Rokvach** [comment]
This has been fixed, tested and working properly now, closing.
