### ISSUE TITLE
Bioluminescent caves might be too heavily culled

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12976]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While swimming around in a bioluminescent cave you can see the background sprites popping in and out of existence

Video:
https://www.youtube.com/watch?v=UNqjFwDGqI4

### Reproduction steps

1. Swim around in a bioluminescent cave

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4723/commits/56a353914997745aaf4c1ea4dbd37850585ff3d1

Used leveleditor to generate some caves and tested them by diving and in freecam.

No issues found
Closing ticket
