### ISSUE TITLE
Culling of lights occurs too soon with upgrades that increase light range

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12972]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using upgrades that allows for longer range turret lights cull before you leave the visibly lit area

### Reproduction steps

Start a single player campaign with a dugong altered to tier 3

Do console command maxupgrades

Start a new round by leaving the outpost, then grab a diving suit and swim down from the sub. When you get kinda far away but still are lit up by a turret light, the turret light will disappear

https://cdn.discordapp.com/attachments/427654262453960724/1170535672331894954/image.png?ex=6559654b&is=6546f04b&hm=6a04682f2019bdce6dca0764f131e425a32762b455ba969ebd29f48f260b9b71&

Shows how far you get before the turret light disappears if you swim out.

With debugdraw on, your character will still be within the square zone of the 'light' when the light suddenly goes out. 

If you use free cam, you can zoom in and make the light disappear if your far away enough:

https://cdn.discordapp.com/attachments/427654262453960724/1170535726757183569/image.png?ex=65596558&is=6546f058&hm=8e55d11e3d4de34ada1fd296e51992a0de73c2504efabfea35e35ba817cfb54c&

Zoom in a tiny bit:

https://cdn.discordapp.com/attachments/427654262453960724/1170535749137993748/image.png?ex=6559655e&is=6546f05e&hm=5e0b4c00f04e28c5df57cddcafdcbfd8d68cf76e22d1709d8d669f6f032946b9&

Appears to be the further you zoom out, the further you can pan away from the ship before the light disappears. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b71c9d72a66803addab54d1ce3a2e5a626e11232 (commit in our private repo)

**Comment by BlackMoons** [comment]
Yay. I am really looking forward to the light not suddenly disappearing when using turret guns for diving lights.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
