### ISSUE TITLE
Turret/RangedWeapon which have high rate of fire can cause significant performance issue in multiplayer

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12974]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While it appears to be ok in singleplayer, high RoF weapons can cause significant performance issue in multiplayer.
For example, you can create a mod that doubles hmg's fire rate. When you shoot it in a multiplayer game, everyone in the server will start to lag.

### Reproduction steps

1. create a mod that doubles hmg's fire rate
2. shoot it in a multiplayer game

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
Same could happen even without mod. Just get 2 chainguns firing at the same time.

**Comment by SomeRandomNoobKekeke** [comment]
Hi @BiffW, could you type "showperf" in console, fire chaingun and take a screenshot?

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this with either a modified HMG or 2 chainguns:


https://github.com/Regalis11/Barotrauma/assets/14351070/a5e560e8-aff1-4ad5-b082-6dfb9cd03d0c

https://github.com/Regalis11/Barotrauma/assets/14351070/8ebd5cb4-bc6d-49ed-a313-3f4f031ee489

**Comment by DrBruhman** [comment]
problem with overdraw, if you zoom out draw is fast, zoom in - particles is occupating more screen space - more draw time. You can see it even on your graph. problem with particle system or overuse of them in chaingun.

https://github.com/FakeFishGames/Barotrauma/assets/95565216/b4f11680-3c00-4d13-b272-ece45d2ed0e6

**Comment by SomeRandomNoobKekeke** [comment]
no xd, dude, it's the rest of the sub

**Comment by A2ur3** [comment]
This issue exists, and I believe it’s caused by high-rate-of-fire weapons or turrets continuously spawning a large number of items. This becomes especially noticeable later in the game, when the number of items, talents, characters and structures increases

In a heavy modded environment, even just one chaingun firing in the late game is enough to cause server lag and rubberbanding

@Regalis11
