### ISSUE TITLE
Engines are visible from an extremely long range when above 1% throttle.

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#12971]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When using debugdraw and AI targets, I found that by far the most visible thing on my ship was... the engines. 

For some reason, they are extremely visible even at low throttle:

https://cdn.discordapp.com/attachments/427654262453960724/1170515918154121317/image.png?ex=655952e6&is=6546dde6&hm=c537451c265849acc0ede41d47b3c6b31c5b590e192097a87a6ace14ac4e4068&

Same visibility at high throttle, the orange sphere has increased but the blue has not (had to zoom out a bit)

https://cdn.discordapp.com/attachments/427654262453960724/1170516046168457348/image.png?ex=65595304&is=6546de04&hm=bc47483b859d17d8f57adddec611d46f8ce1b615154cfe243f9bee771b204416&

(the two blue spheres target my engines)

To confirm they where engines, I turned their throttle to 0% and got:

https://cdn.discordapp.com/attachments/427654262453960724/1170516155170050129/image.png?ex=6559531e&is=6546de1e&hm=1ccee010a79726fb521092c2dcac6d3839c3dc0be7468a29d36b077aebe50337&

For scale, the front large visible sphere is a turret light, meaning even at the lowest throttle setting an engine is 50% more visible then a turret light. 

Seems weird that an engine at <10% throttle would be brighter then a spot light. 

### Reproduction steps

Enable debugdraw and aitargets

Enable engine, set throttle to 10% or 100% and view visibility distance, same distance regardless of throttle setting. 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by BlackMoons** [comment]
@nicklo6649 (Nicklo6649 / LobaDK) on the barotrauma discord reports that by comparing his screenshots of his ship, this did not occur in August, but does now for his ship as well.

My ship uses engine, his uses large engine. both are affected.

**Comment by Regalis11** [comment]
Does this cause some kind of issues with the creature behaviors? To me it doesn't seem unreasonable that one of the largest devices in the game, with lots of bright lights on it, is visible from quite far away.

**Comment by SomeRandomNoobKekeke** [comment]
I don't think it causes any behavior issues, just annoying blue circles

https://github.com/Regalis11/Barotrauma/assets/122838333/3a44e45c-0908-413b-b221-3b7c7d90b4c0

**Comment by BlackMoons** [comment]
> Does this cause some kind of issues with the creature behaviors? To me it doesn't seem unreasonable that one of the largest devices in the game, with lots of bright lights on it, is visible from quite far away. And why would the amount of throttle affect the visibility in the first place?

Hu, are AI's unable to 'see' it through shell walls? I assumed they would use it to attack the sub but SomeRandomNoobKekeke's video seems to show otherwise. 

maybe having a window in the rear of my sub was a bad idea...

**Comment by SomeRandomNoobKekeke** [comment]
actually monsters don't seem to react to this circle at all, even if the engine is outside the sub, or monsters are inside sub and in the same hull

**Comment by Regalis11** [comment]
I don't think any monster is set to target the engine specifically. 

But in any case, I don't think we're going to do any changes to this if it doesn't cause any actual issues other than the debug view maybe looking different from what you'd expect.

**Comment by BlackMoons** [comment]
Ah k, no problem, I assumed it meant AI monsters would use it to see my sub and chase it, like engine/reactor/sonar noise does.
