### ISSUE TITLE
The gravity sphere and anomaly does not attract regdolls 

### ISSUE THREAD

**Issue by PlasmaUwU** [Regalis11/Barotrauma#12982]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The gravity sphere and anomaly do not attract characters into a "regdoll" state. This makes it easy to avoid the damage of the gravity sphere and the inevitable death from the anomaly, as well as looks extremely un-logical and strange.

### Reproduction steps

1) Open sub edito / Quick start
2) Load the ruins module with gravity sphere / Find the ruins module with gravity sphere
3) Ragdoll near the gravity sphere and notice that it does not attract you.
4) Repeat this with the anomaly 

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62175a3e02c2473b305e33a77dfeae483ebe6586 and https://github.com/Regalis11/Barotrauma-development/commit/e1f9877123071d0da67b82045564cf9f15f1198c (commits in our private repo)

**Comment by ubertpendragon** [comment]
Also might add that gravity spheres do not work outside of hulls

**Comment by Rokvach** [comment]
Tested on singleplayer and multiplayer, using gravity spheres and currents. Working correctly. Can be merged and closed.
