### ISSUE TITLE
Several containers with the parameter "keep open when equipped="true" movable frame="true"" work poorly

### ISSUE THREAD

**Issue by PlasmaUwU** [Regalis11/Barotrauma#12983]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

`Item Container` has the parameter `keepopenwhenequipped` and `movableframe`

Which allow you to see the container interface and 
move it, even when the cursor is not pointed at the object.

However, if several items with these parameters are equipped (Not found in vanilla, but causes problems with mods), the containers interface begins to work crookedly, lag, disappear, and so **on.**
[Test_mod.zip](https://github.com/Regalis11/Barotrauma/files/13284903/Test_mod.zip)

https://github.com/Regalis11/Barotrauma/assets/101663742/2d7e987c-a226-4e66-84c3-c60cf6856c8e

### Reproduction steps

1) Download the attached mod for the test
2) Quick start with the test mod
3) Spawn a few items with an container interface  (an exo suit, a medic's uniform, and a belt with tools, for example)
4) Equip them all on and observe that the container interface work bad

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This is most likely related to https://github.com/Regalis11/Barotrauma/issues/12817, but we'll need to give it a test and verify.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4619/commits/c8ac918bc900a5d2b767e44f7e364beca40ae9ee

movableframe=true in equipment slots makes things unstable. Inventory frame wants to snap back to its default position.
No issues with vanilla content ie. 2 storage containers in hands.
With test mod:

https://github.com/Regalis11/Barotrauma/assets/8488224/8d282332-aac8-4f97-ab7f-e2e51852c52f

Vanilla:

https://github.com/Regalis11/Barotrauma/assets/8488224/8175a7b7-94dd-4c0e-b095-2fbb5f708c40

**Comment by Jasontti** [comment]
Tested again with fixes in: https://github.com/Regalis11/Barotrauma-development/pull/4619/commits/c7815d4c8f52b0cb3e4abfe27704bac3e6c1b4d0

Frames now behave well and don't jerk around.

Couple issues found.
* All movable frames are collapsed when 2 storage containers are equipped
* Mouse drag event is registered on all movable frames, not just active one
* Movable frame fails to spawn when another movable frame is overlapping or close by it

https://github.com/Regalis11/Barotrauma/assets/8488224/cfd409e2-8a35-45bf-a1c8-7381813f0502

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4619/commits/c4a3c184b4e44fa59d6dccb73ce09b1ab75de6cc

Movable frames don't interfere with each other
They remember locations and frames spawn when overlapping

No issues found
Closing ticket.
