### ISSUE TITLE
CustomInterface not getting properly displayed

### ISSUE THREAD

**Issue by G-M-twostay** [Regalis11/Barotrauma#12984]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I have a mod item that incldue the following component:
```
        <CustomInterface canbeselected="true" drawhudwhenequipped="true" allowuioverlap="true">
          <GuiFrame relativesize="0.16,0.3" anchor="CenterLeft" pivot="TopLeft" relativeoffset="0.1125,0.001"  style="ItemUI" />
          <Button text="scalpel.incise" connection="incise"/>
          <Button text="scalpel.lung" connection="lung"/>
          <Button text="scalpel.liver" connection="liver"/>
          <Button text="scalpel.heart" connection="heart"/>
          <TextBox text="scalpel.action" propertyname="note" maxtextlength="20"/>
        </CustomInterface>
```
However, only the textbox gets drawn in game, the buttons appears at first when I first equip the item, then disappears after a flash. If I remove the textbox, then when I first equip the item, the GUI will appear for a flash then disappear. By first I mean first time in complete load. 

The mods I have are my work in progress mod with this item, Lua For Baro. I don't think both of these mods interfere with displaying custominterface in any ways.

Resolution is 3840*2160, HUD scale is 120%, Inventory scale is 120%, Text scale is 125%.

### Reproduction steps

The complete xml for this item is here(based on diving knife):
```      <Item identifier="scalpel" category="Weapon" Tags="smallitem,weapon,surgery" cargocontaineridentifier="metalcrate" useinhealthinterface="true" scale="0.5" impactsoundtag="impact_metal_light" RequireAimToUse="True">
        <PreferredContainer secondary="wreckarmcab,abandonedarmcab" amount="1" spawnprobability="0.25" />
        <PreferredContainer secondary="abandonedstoragecab" amount="1" spawnprobability="0.05" />
        <PreferredContainer secondary="beaconsupplycab" amount="1" spawnprobability="0.05" />
        <PreferredContainer primary="secarmcab" secondary="armcab" />
        <Price baseprice="29">
          <Price storeidentifier="merchantoutpost" multiplier="1.5" minavailable="6" />
          <Price storeidentifier="merchantcity" multiplier="1.25" minavailable="8" />
          <Price storeidentifier="merchantresearch" multiplier="1.25" minavailable="2" />
          <Price storeidentifier="merchantmilitary" multiplier="0.9" minavailable="15" />
          <Price storeidentifier="merchantmine" multiplier="1.25" minavailable="2" />
          <Price storeidentifier="merchantarmory" multiplier="0.9" minavailable="15" />
          <Price storeidentifier="merchanthusk" minavailable="0" maxavailable="2"/>
        </Price>
        <Deconstruct time="10">
          <Item identifier="iron" />
        </Deconstruct>
        <Fabricate suitablefabricators="fabricator" requiredtime="10">
          <RequiredSkill identifier="weapons" level="30" />
          <RequiredItem identifier="iron" amount="2" />
        </Fabricate>
        <InventoryIcon texture="%ModDir%/Images/InventoryItemIconAtlas.png" sheetindex="0,0" sheetelementsize="64,64" origin="0.5,0.5" />
        <Sprite texture="%ModDir%/Images/InGameItemIconAtlas.png" sheetindex="1,1" sheetelementsize="128,128" depth="0.6" origin="0.5,0.5" />
        <Body width="65" height="15" density="25" />
        <MeleeWeapon slots="Any,RightHand,LeftHand" aimpos="50,0" handle1="-10,0" holdangle="30" reload="0.75" range="50" combatPriority="25" msg="ItemMsgPickUpSelect">
          <Attack targetimpulse="2" severlimbsprobability="0.1" itemdamage="3" structuredamage="2" structuresoundtype="StructureSlash">
            <Affliction identifier="lacerations" strength="5" />
            <Affliction identifier="pierce" strength="2.5" />
            <Affliction identifier="bleeding" strength="5" />
            <Affliction identifier="stun" strength="0.2" />
            <StatusEffect type="OnUse" target="UseTarget">
              <Conditional entitytype="eq Character" />
              <Sound file="Content/Sounds/Damage/LimbSlash1.ogg" selectionmode="random" range="500" />
              <Sound file="Content/Sounds/Damage/LimbSlash2.ogg" range="500" />
              <Sound file="Content/Sounds/Damage/LimbSlash3.ogg" range="500" />
              <Sound file="Content/Sounds/Damage/LimbSlash4.ogg" range="500" />
              <Sound file="Content/Sounds/Damage/LimbSlash5.ogg" range="500" />
              <Sound file="Content/Sounds/Damage/LimbSlash6.ogg" range="500" />
            </StatusEffect>
          </Attack>
        </MeleeWeapon>
        <aitarget sightrange="500" soundrange="250" fadeouttime="1" />
        <Quality>
          <QualityStat stattype="StrikingPowerMultiplier" value="0.1" />
        </Quality>
        <Choose canbeselected="true" drawhudwhenequipped="true" allowuioverlap="true">
          <GuiFrame relativesize="0.16,0.3" anchor="CenterLeft" pivot="TopLeft" relativeoffset="0.1125,0.001"  style="ItemUI" />
          <Button text="scalpel.incise" connection="incise"/>
          <Button text="scalpel.lung" connection="lung"/>
          <Button text="scalpel.liver" connection="liver"/>
          <Button text="scalpel.heart" connection="heart"/>
          <TextBox text="scalpel.action" propertyname="note" maxtextlength="20"/>
        </Choose>
      </Item>
```
1. Create a mod with this item.
2. Replace the textures with any vanilla textures.
3. Load this mod and start a new game.
4. Give this item via command.
5. Equip it. 
6. See that the ui isn't properly displayed

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Enabling Verbose Logging showed no error.
```

**Comment by ricky122122** [comment]
custominferface be working quite weirdly and for some reason if you want it to display all of this correctly you must use statuseffects. I have no clue why but its they way I have been doing it in your case it might look something like
`        <CustomInterface canbeselected="true" drawhudwhenequipped="true" allowuioverlap="true">
          <GuiFrame relativesize="0.16,0.3" anchor="CenterLeft" pivot="TopLeft" relativeoffset="0.1125,0.001"  style="ItemUI" />
          <Button text="scalpel.incise" connection="incise">
		      <StatusEffect type="OnUse" targettype="This" />
		  </Button>
          <Button text="scalpel.lung" connection="lung">
		      <StatusEffect type="OnUse" targettype="This" />
		  </Button>
          <Button text="scalpel.liver" connection="liver">
		      <StatusEffect type="OnUse" targettype="This" />
		  </Button>
          <Button text="scalpel.heart" connection="heart">
		      <StatusEffect type="OnUse" targettype="This" />
		  </Button>
          <TextBox text="scalpel.action" propertyname="note" maxtextlength="20"/>
        </CustomInterface>`

**Comment by G-M-twostay** [comment]
> custominferface be working quite weirdly and for some reason if you want it to display all of this correctly you must use statuseffects. I have no clue why but its they way I have been doing it in your case it might look something like ` <CustomInterface canbeselected="true" drawhudwhenequipped="true" allowuioverlap="true"> <GuiFrame relativesize="0.16,0.3" anchor="CenterLeft" pivot="TopLeft" relativeoffset="0.1125,0.001" style="ItemUI" /> <Button text="scalpel.incise" connection="incise"> <StatusEffect type="OnUse" targettype="This" /> </Button> <Button text="scalpel.lung" connection="lung"> <StatusEffect type="OnUse" targettype="This" /> </Button> <Button text="scalpel.liver" connection="liver"> <StatusEffect type="OnUse" targettype="This" /> </Button> <Button text="scalpel.heart" connection="heart"> <StatusEffect type="OnUse" targettype="This" /> </Button> <TextBox text="scalpel.action" propertyname="note" maxtextlength="20"/> </CustomInterface>`

Yeah the buttons only gets displayed if there is some status effect in it.

**Comment by Regalis11** [comment]
The buttons are automatically hidden if they have none of the following:
- Some status effect that's executed when the button is pressed.
- Set to modify the value of some property of the item.
- A wire in the corresponding connection.

If a button doesn't have any of these, it does nothing and there's no point in displaying it. What are you trying to do with the buttons? It seems you've configured a connection for them, but the item doesn't have any connections.

**Comment by G-M-twostay** [comment]
Makes sense, but can we have a documentation saying that buttons get automatically hidden when it doesn't do anything? The current auto hiding is kind of confusing.

In my case I defined a new ItemComponent that uses these buttons, since my task wasn't quite achievable using statuseffects. So these buttons are actually placeholders and the actual behaviors are defined in code.
