### ISSUE TITLE
Game fails to load - Maximum amount of entities exceeded

### ISSUE THREAD

**Issue by Ohjelmointipolku** [Regalis11/Barotrauma#12980]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While using the Typhoon 2 with friends online we fail to start a round with the following issue shown in the screenshot. 
![crash](https://github.com/Regalis11/Barotrauma/assets/148005067/ccd4d5b7-c677-42c5-ac35-5738832bd1e2)

This was after we reset a game after having a bit of fun in the sub between waypoints.

### Reproduction steps

 Unsure of reproducability, but the save file is attached.
[Bugged savefile.zip](https://github.com/Regalis11/Barotrauma/files/13271841/Bugged.savefile.zip)

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Kiitos raportista! :)

This seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/10944, which we'd incorrectly assumed to have been fixed. It seems that in some rare cases, certain seeds lead to broken level generation, and an absurd number of waypoints being generated in the level. We need to look into this more closely, but for now, I modified the save file you've provided (just change the seed of the level) so it should load again and you can continue the campaign: 
[Bugged.savefile.fixed.zip](https://github.com/Regalis11/Barotrauma/files/13294324/Bugged.savefile.fixed.zip). Sorry for the inconvenience!

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but I think we still need to look into what's causing this level generation issue to happen, so I'll reopen the ticket!

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
