### ISSUE TITLE
"Dead or alive" traitor event fails if target respawns

### ISSUE THREAD

**Issue by rekterakathom** [Regalis11/Barotrauma#12990]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dead or alive traitor event failed because the victim's body despawned due to respawn. The duffel bag was untouched.
At mission completion the name of the target is replaced with ``[target "victim" not found]`` and the event is a failure.

Expected behaviour:
1. The victim body does not despawn even if the victim respawns
OR
2. The duffel bag that replaces the body is sufficient to complete the mission

### Reproduction steps

1. Kill the target in "Dead or alive" and plant the evidence
2. Target respawns
3. Mission fails
![20231108203650_1](https://github.com/Regalis11/Barotrauma/assets/30532050/4901f093-f48c-4b2e-bdbb-a6fe54953364)

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/9d5142bc9e3d0925f324253ba784b03dd24997ac (commit in our private repo)

**Comment by Regalis11** [comment]
Internal note: referenced incorrect issue in https://github.com/Regalis11/Barotrauma-development/commit/9d5142bc9e3d0925f324253ba784b03dd24997ac (commit in our private repo), should've been https://github.com/Regalis11/Barotrauma/issues/12991

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06f1b9f7b355c80c242104ff29980f8a66d1b52f

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
