### ISSUE TITLE
Artifacts can despawn in "Salvaging an artifact" missions

### ISSUE THREAD

**Issue by rekterakathom** [Regalis11/Barotrauma#12991]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Nasonov artifact despawned during "Salvaging an artifact" mission, which resulted in console errors when arriving at an outpost (``Attempting to remove an already removed item (Nasonov Alien Artifact)``)

### Reproduction steps

1. Retrieve artifact (we placed it in the artifact case)
2. Drop the artifact (in our case the artifact case)
3. Go far away from the artifact (artifact carrier died, sub sank down to abyss, closest player was prob ~300 meters away)
4. Artifact has now despawned
5. Finish the mission
6. Console errors
![20231101195813_1](https://github.com/Regalis11/Barotrauma/assets/30532050/0525a915-fe3d-47e0-92f5-884266342e0f)

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9d5142bc9e3d0925f324253ba784b03dd24997ac (commit in our private repo, referenced incorrect ticket in the commit message)

**Comment by 3e849f2e5c** [comment]
Tested, wasn't able to get the error anymore when leaving the artifact behind far away. Closing
