### ISSUE TITLE
Ancient weapon uses its own condition bar to fire (Yet has slots for tanks)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#130]
A detail I have been curious about for sometime, but the ancient weapon does not require any form of fuel inserted to be used (It drains the condition of the ancient weapon itself).

This makes them unable to be refueled sure, but it also has a contained slot for taking an oxygen tank or a welding fuel tank (Though it cannot accept Oxygenite shards).

I am pointing this out solely to check if this is an unintended bug in the content package, and this was really meant to accept a form of fuel - or even alternate between itself or fuel. (Though I don't know of a method to check for the lack of an item and trigger a status effect based off not-contained).

**Comment by Crystalwarrior** [comment]
Honestly it'd be really cool if it used oxygenite shards as fuel instead of destroying itself.
And what about sulphurite? I find them to be insanely useless in their current state.

**Comment by Regalis11** [comment]
I'm pretty sure this is an oversight caused by copypasting and modifying the plasma cutter config. Refueling them with oxygenite or sulphurite shards is a cool idea though, I think I'll look into it!
