### ISSUE TITLE
Bot doctors do not let go of their patients' hands

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#13006]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When bots heal someone they take his hand
But sometimes after healing they don't want to let go of each other and get stuck until you bonk them with a toy hammer
I don't remember this issue before updates

![20231110221042_1](https://github.com/Regalis11/Barotrauma/assets/122838333/162857da-92fc-477c-a1ea-05a3f0e344cc)
![20231110221134_1](https://github.com/Regalis11/Barotrauma/assets/122838333/c4fe8ed2-55d6-4bc2-a324-2e6d9e3d3a4b)

### Reproduction steps

take [this sub](https://steamcommunity.com/sharedfiles/filedetails/?id=3078753473)
open it in sub editor
spawn a captain (spawncharacter captain cursor)
order one of them to repair, and other one to heal and man some turret
type freecamera and watch
eventually they will get stuck

you can spawn more captains to speed up the process, but then they could change healing target and unstuck

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6299f93967e6d4a9b959ab2252f2d9b066f2229b
