### ISSUE TITLE
Movement issues on rotated structures

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#13009]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing rotatable structures, I noticed some oddities that popped up concerning movement on them:
1. Characters don't align their feet properly on sloped walls when walking down them.
2. Characters lean unnaturally far forwards when walking up sloped walls, especially when running.
3. Characters can climb and stick to unreasonably steep angled walls with relative ease.

https://github.com/Regalis11/Barotrauma/assets/67431770/d174df90-3eac-420f-99c4-c4b4e90ee8c8

### Reproduction steps

1. Load [this submarine](https://github.com/Regalis11/Barotrauma/files/13323372/rotatable.structures.test.zip) (rename .zip to .sub) in the Submarine Editor.
2. Enter testing mode, and move around the test area.
3. Observe odd animations when walking up/down slopes, as well as being able to climb at unrealistic angles.

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### -

Submarine Editor

### Version

v1.2.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Partially addressed in https://github.com/Regalis11/Barotrauma-development/commit/08dee08af6e283daaef7cd6a424c24c87032f302.

**Comment by juanjp600** [comment]
Significantly improved in https://github.com/Regalis11/Barotrauma-development/commit/2d8a6a4214470cc48f7ad3d440eaec595c5d1343
