### ISSUE TITLE
Rotated structures still have original selection boundaries with area select

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#13007]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When attempting to area select a 45 degree rotated "Large Horizontal Inside Wall", I noticed the selection boundary was still the same as an unrotated (0 degree) wall.

Non-area selection still has the correct selection boundaries.

![image](https://github.com/Regalis11/Barotrauma/assets/67431770/3bae9b12-87c6-4c96-8efd-edb2a00fe648)

### Reproduction steps

1. Place a rotatable structure in the Submarine Editor.
2. Rotate it an arbitrary amount.
3. Using area select, select different sections.
4. Observe how the selection boundary is still the same as if the structure was unrotated.

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### -

Submarine Editor

### Version

v1.2.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c9e62f1a795d827b5a6f0955f4537780860be7d7.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/3eeee532-d00b-4dd6-89bd-edf6c49dfa2d)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/adb1d822-7ef2-44f3-9acd-c9f0a1c7da60)
