### ISSUE TITLE
"refreshrect" command not found

### ISSUE THREAD

**Issue by TheDarkBox** [Regalis11/Barotrauma#13013]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The `refreshrect` command is listed as not found when trying to use it.

### Reproduction steps

1. Open the submarine editor.
2. Load any submarine.
3. (Optional) Select any/all entities on the submarine.
4. Open the debug console.
5. Type "refreshrect" and press Enter.
6. Observe the result (`Command "refreshrect" not found.`)
![image](https://github.com/Regalis11/Barotrauma/assets/17528986/0b619196-2571-4aec-9c71-317e6b87b466)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Submarine Editor

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
isn't that Debug Version Command?
