### ISSUE TITLE
[Steam version] There is still a bug with items disappearing at the end of the round

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1301]
Tested in singleplayer.
Seems to somehow be related to items being held in hands. Does not happen if you are not holding any items in your hands.
Does not matter if you are controlling the character or not. All characters that have any items in their hands will get that effect.

Before ending the round:
![-2019-mar-19-006](https://user-images.githubusercontent.com/38168249/54598490-2b4e0400-4a6b-11e9-9dbc-a53ca25ea711.jpg)
After ending the round:
![-2019-mar-19-008](https://user-images.githubusercontent.com/38168249/54598493-2c7f3100-4a6b-11e9-8b69-36c60987995d.jpg)
Before:
![-2019-mar-19-010](https://user-images.githubusercontent.com/38168249/54598497-2db05e00-4a6b-11e9-9f9a-755c33cf4335.jpg)
After:
![-2019-mar-19-012](https://user-images.githubusercontent.com/38168249/54598499-2ee18b00-4a6b-11e9-8114-24806a75e4f2.jpg)
Before:
![-2019-mar-19-014](https://user-images.githubusercontent.com/38168249/54598503-3012b800-4a6b-11e9-8af0-770a2672f7d2.jpg)
After:
![-2019-mar-19-016](https://user-images.githubusercontent.com/38168249/54598504-31dc7b80-4a6b-11e9-9398-715e455b2be2.jpg)
Before:
![-2019-mar-19-018](https://user-images.githubusercontent.com/38168249/54598510-330da880-4a6b-11e9-9dd6-5d17cd094954.jpg)
After:
![-2019-mar-19-020](https://user-images.githubusercontent.com/38168249/54598512-343ed580-4a6b-11e9-9b6e-cb1bcaeb2b8c.jpg)

**Comment by Regalis11** [comment]
Fixed in 3b402cf
