### ISSUE TITLE
Add bundles of resources or change the quantities of them to better suit their space usage vs their unrefined source

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1302]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

In a multiplayer or singleplayer campaign it becomes very apparent resource management is awkward and storage is at a premium, we cannot yet sell excess resources, discarding them is often a pain and hassle and often players are resorting to the shipment crates the store bought items appear in as a method to store.

Many resources even tend to spit out quantities of iron that has no real use that I can think of easily for how much you can obtain.

simply put, submarines have very little space for lockers, which most designers sacrifice aesthetics due to or something else to try to fit them. if there was a way to compress/store say, 2/3/4/5 units of iron/steel/saline or other such items as a singular item in say, a bundle of it (Even just to stack the icon 2/3/4/5 times over itself in the item picture) and have a method to "unpack" the bundle as well as create it, it would be very nice and welcome.

An alternative to this would be to change the quantities you get to be condition (aka percentage) based, and allowing these resources to be properly combined. if I take an ore, and I smelt the ore, I expect to have equal or less space from the now refined metal with impurities removed, same goes for extracted goods and most goods in general. instead an ore expands out like a flatpack where 1 typically converts to 3-5 squares of space.

I don't expect this to be added mind you, given barotrauma is about scarcity and this is quality of life that may feel to reduce that scarcity, though there is a limited storage space this doesn't really impact how much you gain in a game but instead how simple it may be to store the refined version of these which still takes time and power, and often some submarines, even the vanilla ones now, are packing a lot of starting materials that if taken apart well...fit many more times their space and make it quite awkward.

Crafting can already support percentage based crafting, and this would feel like a godsend if I am honest for anyone attempting gathering and crafting as a team or with the AI.

just a peak at the average orca's starting materials, most of which expands into 2-4 items:

![image](https://user-images.githubusercontent.com/29177976/54601742-bca38300-4a37-11e9-837e-56758ed2aa34.png)

![image](https://user-images.githubusercontent.com/29177976/54601782-dcd34200-4a37-11e9-845b-0e06e45a5a3d.png)

![image](https://user-images.githubusercontent.com/29177976/54601816-f1afd580-4a37-11e9-90be-b531b1d5b361.png)

![image](https://user-images.githubusercontent.com/29177976/54601841-fd030100-4a37-11e9-9fd9-b465318f9fdb.png)

![image](https://user-images.githubusercontent.com/29177976/54602148-c1b50200-4a38-11e9-95dd-720941f0ba63.png)

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
