### ISSUE TITLE
NPC attacks through walls

### ISSUE THREAD

**Issue by IgorParshukov** [Regalis11/Barotrauma#13027]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The NPC attacks through walls, and when a monster collides with a submarine, too much damage is caused to the crew, from which they die very quickly

### Reproduction steps

1. Start a single player game with any difficulty settings (not tested multiplayer)
2. Sail away from the outpost
3. Spawn the NPC (in my case there was a hammerhead and a mudraptor)
4. The NPC begins to cause a lot of damage (namely lacerations) and the player is thrown around the entire room

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional, when something breaches a wall it throws out shrapnel that can cause lacerations.

**Comment by IgorParshukov** [comment]
But how to play with such an innovation in a single player game with bots? They die very quickly, especially in passenger transport missions

**Comment by IgorParshukov** [comment]
> This is intentional, when something breaches a wall it throws out shrapnel that can cause lacerations.

But how to play with such an innovation in a single player game with bots? They die very quickly, especially in passenger transport missions
