### ISSUE TITLE
Exhibitionism event can't be completed

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#13029]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

- [ ] Can't complete
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/0038d23b-4758-4076-9305-8ef2c3406fac)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/afa4161c-9ca9-44b6-8c85-be977355e038)
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/f12891f6-dbaa-468e-8169-430b59fc25ad)

### Reproduction steps

-

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Fixed and tested once, managed to complete it succesfully

**Comment by Rokvach** [comment]
Tested and working correctly, I don't think ticket needs to go through review as I've switched to commenting tickets to the doc.
