### ISSUE TITLE
Shooting anything causes immense lags in GameSession

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#13028]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/assets/122838333/650da774-366e-44d2-bfbe-95335dd33d17

Note how 1 pack of lag spikes appears when you fire and 2 pack appears when bullets impact

https://github.com/Regalis11/Barotrauma/assets/122838333/dda37b5b-3ddb-4c23-872e-e7c89e0f5b63

This seems to be dependant on difficulty: 
-   on "quickstart Orca2 100 wastesbasic" lags are immense, 
-   on "quickstart Orca2 0 wastesbasic" there's no lags at all

this is probably related or equal to https://github.com/Regalis11/Barotrauma/issues/12974

### Reproduction steps

quickstart Orca2 100 wastesbasic
try shooting turrets and guns from armory

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested quickly in stable 1.1.19.3 and current dev version of: https://github.com/Regalis11/Barotrauma-development/commit/070075dc02efb775ab00749119fbe313da0b9a68

Could repro easily, but it's not 100% quaranteed to happen.
Event sets of ruin_encounters and entrance1 seems to cause it, could be others also, but these popped up in testing.
