### ISSUE TITLE
Items cannot be combined in multiplayer, single player flash powder combine exploads in your face gloriously

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1303]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I deconstructed some flares, wanting to combine the sheer amount of plastic quarters and flash powder quarters.

It detonated in my face. when I was just trying to determine if you can truely combine in single player but not multiplayer (the rumour I have heard, and I have been unable to combine anything in the game in multiplayer).

the expected behaviour is to be able to combine odds and ends like ingredients, perhaps partial fuel tanks or partially used medicines in multiplayer and single player (in multiplayer, apparently nothing can be combined?, in single player, it can trigger onremoved status effects though when its only a combine and not strictly used up).

I don't know if you cant combine in multiplayer, but this seems to be what everyone thinks and I have found nothing you can actually combine.

If there is almost nothing that can be combined, there are a great many items that make sense to be able to do so, and should be a considerably more used feature.

**Version**
0.8.9.6 Steam closed alpha

**Additional information**

This doesn't do it justice:
[clip of having my face blown off in basic chemistry](https://i.gyazo.com/89187f3d9ce648ea5e50232caa2c2bb7.mp4)

**Comment by Regalis11** [comment]
This seems to be an issue in single player as well, and apparently almost none of the new items are combinable.

**Comment by NilanthAnimosus** [comment]
I believe a certain attribute is used to allow combination but those that are combinable are just a few of the old ingredients. I know flash powder combines or attempts to, but of course that expload's on combine.

**Comment by Regalis11** [comment]
Fixed in 
66af346
