### ISSUE TITLE
Electrical discharge not working.

### ISSUE THREAD

**Issue by coderyemre** [Regalis11/Barotrauma#13038]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Electrical discharge not working.

### Reproduction steps

Open Submarine Editor
Add a reactor, button and electrical discharge
Try to use electrical discharge
Anything happen (electrical discharge not working)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

In Submarine Editor

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
Electrical Discharge Coils must be wired to supercapacitors
They require short bursts of high energy, which only supercapacitors can provide

**Comment by coderyemre** [comment]
Thanks. Just now I understand with trying. But I have another question. Before this update I use electrical discharge with reactors. But now It dont work. Now we **only** use with Electrical Discharge withsupercapacitors. Did I understand correctly?

> Electrical Discharge Coils must be wired to supercapacitors They require short bursts of high energy, which only supercapacitors can provide

**Comment by SomeRandomNoobKekeke** [comment]
I don't think EDC behavior was changed
What do you mean by "with reactors"? 
I don't think wiring EDC directly to reactor has ever worked
You need some capacity, either supercapacitor or battery
Default batteries can't store enough power to provide EDC discharge

**Comment by coderyemre** [comment]
Yes Only reactor and batteries. I had automatic EDC system. After some edits like change working Voltage 10000 to 5000 . It works. But in the long fights or EDC shield mode after sometimes the electric system is harms. Thats bad side. But after this update It don’t  work anyway with reactor. It work with supercapacitors. However Its not important. I had a question and you answered. Thanks and Good luck and fair sea in The Barotrauma
