### ISSUE TITLE
Attack.RequiredAngleToShoot="2" makes DefenseBot's ranged attack frequently jammed randomly.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#13034]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

What happened:
https://github.com/Regalis11/Barotrauma/assets/73634685/6cef23db-34fe-49da-87bd-5c170ffa4d42

Look into DefensebotDefaultRagdoll.xml:

If I change RequiredAngleToShoot from 2 to 5, then looks like everything work fine
https://github.com/Regalis11/Barotrauma/assets/73634685/66f9aa43-71d9-44f5-8238-a592c2e9fe7c

### Reproduction steps

1. Spawn Defensebot
2. Spawn some monsters
3. Observe

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
To me it doesn't look like there's a bug here. 2 degrees is so little that it's just difficult for the bot to get the limb pointing at the target with that kind of accuracy.

**Comment by zhu-rengong** [comment]
Sometimes the robot will almost not fire when it encounters some monsters. If you keep observing at it, you will feel that its behavior on land is very strange and abnormal but it's very stable in water.

**Comment by zhu-rengong** [comment]
https://github.com/Regalis11/Barotrauma/assets/73634685/6c236fc8-1177-4f22-9a2f-9b3bb1cee715
Such as the behaives of it shown in the video

**Comment by zhu-rengong** [comment]
If set RequiredAngleToShoot from 2 to 3 or 4, it will works.
