### ISSUE TITLE
Update broke our campaign save (savefile upload)

### ISSUE THREAD

**Issue by SkywardSoul117** [Regalis11/Barotrauma#13032]
Hello, just uploading our multiplayer save file at your request (from steam forums). A quick summary of the issue would be the latest major update caused the performance to take a huge hit, making the save unplayable. Some weird loading behaviour occurred when loading into a level, such as a random rescue sub with no items appearing near the start. No lua mods were used, only fairly basic mods. I assume the save file has a modlist built in due to the warnings when modlists don't match, but let me know if it's needed. 
The issue isn't present on new saves with the same modlist. 

Github won't let me upload the save file due to the file type, so I've changed it to a ".pdf". Changing it back to a .save should work. 

[problematic performance.pdf](https://github.com/Regalis11/Barotrauma/files/13367067/problematic.performance.pdf)

Apologies if this is poorly formatted, I couldn't find the bug report template.

**Comment by SomeRandomNoobKekeke** [comment]
you can just wrap it in zip
