### ISSUE TITLE
Psychosis artifact and Watcher's Gaze affliction

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#13033]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Psychosis artifact is supposed to inflict Psychosis and Watcher's Gaze periodically however the inflicted amount of Watcher's Gaze isn't enough for it to reach the 50-60 strength threshold, which has the chance to inflict Nausea and Psychosis, due to it immediately losing 4 affliction strength per second. Instead it only reaches 40% and then continues to decay until it's gone.

https://github.com/Regalis11/Barotrauma/assets/115734437/07dd0b37-dd79-4ef0-b946-c450a539eb41

```
<!-- Releases a burst of watchers gaze in a 1500 radius periodically -->
<StatusEffect type="Always" target="This,NearbyCharacters" range="1500" Delay="30" Duration="5" stackable="false" setvalue="true" checkconditionalalways="true">
  <Conditional hastag="neq artifactcontainer" targetcontainer="true" />
  <Conditional Voltage="0.0" targetcontainer="true" />
  <Affliction identifier="watchersgaze" strength="0.20"/>
  <Affliction identifier="psychosis" strength="0.02" />
  <ParticleEmitter particle="psychosisfx" anglemax="360" particlespersecond="12" />
  <sound file="Content/Items/Alien/Alienpump.ogg" range="500.0" loop="true" volume="1" />
</StatusEffect>
```
Increasing the inflicted amount to account for the immediate strength loss would allow the affliction to reach the threshold where it has a chance to inflict Nausea and Psychosis. A value between 0.24 or 0.30 would leave the player at 52% or 70% Watcher's Gaze strength.

### Reproduction steps

1. Stand next to Psychosis Artifact
2. Notice while it does cause visual effects it never causes nausea or psychosis

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
Spoiler alert!

On the other hand this is what happens when you visit Dr. af Grann in the end for one second (very cool actually)

https://github.com/Regalis11/Barotrauma/assets/122838333/4ffa7189-d8d5-4ea4-8cd8-c8253beb05ac

**Comment by Regalis11** [comment]
I don't see this as an issue really, imo the main point of the watcher's gaze here is to buff monsters.

**Comment by ubertpendragon** [comment]
Are you sure about that 👀
