### ISSUE TITLE
The robot tries to attack the closest limb, but will not ignore the limbs blocked by obstacles, this caused the robot to be stuck.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#13043]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm making an auto coilgun but happened a weird problem:
https://github.com/Regalis11/Barotrauma/assets/73634685/ea3ec746-ba6b-45de-8612-c00bedffcb95

### Reproduction steps

1. Spawn a defense bot
2. Let your limb closest to the robot be blocked by an obstacle
3. Defense bot is stuck

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Would it be possible to send us the xml for autocoilgun you're making? I gave this a test with the vanilla defense bot, but couldn't reproduce the issue. The bot seems to always aim at the origin of the character (not a limb):
![image](https://github.com/Regalis11/Barotrauma/assets/14351070/9b3c9afc-64e2-44aa-8e6b-0423d743f8f6)

**Comment by zhu-rengong** [comment]
I'm not sure, I think this is related to https://github.com/Regalis11/Barotrauma/issues/13044

**Comment by zhu-rengong** [comment]
You can subscribe to OTFX(https://steamcommunity.com/sharedfiles/filedetails/?id=2986787106) for testing auto coilgun
Their ids: otfx_securityautocoilgun, otfx_securityautocoilgunteam1threatteam2, otfx_securityautocoilgunteam2threatteam1

**Comment by zhu-rengong** [comment]
It seems that the character only detects the distance when looking for the target, but not the obstacles.
https://github.com/Regalis11/Barotrauma/blob/71b710641b6b3df60d03adf0dab772b6f5def528/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/EnemyAIController.cs#L4012
But it detects obstacles when attacking a found target, so it won't fire at the target.

**Comment by zhu-rengong** [comment]
I adjusted again and again, now it looks like no problems now.
