### ISSUE TITLE
Invisible ballast flora spores

### ISSUE THREAD

**Issue by aoyamajia** [Regalis11/Barotrauma#13048]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The ballast flora spores are only visible on sonar. The spore/toxinmistlargefade particles are invisible, the `<Trigger />` radius does not show up in debugdraw when it used to, but the spores still behave normally; the sub will still get infected when driven through.

It likely isn't just limited to the leveleditor because I spent hours looking for spores in campaign/sandbox to no avail before doing the steps listed below. At first I thought I messed up my mod that overrides the spores, but it persists after disabling all mods + verifying files, and at least two others confirmed they can't see the particles either.
![1](https://github.com/Regalis11/Barotrauma/assets/39614559/212709ec-33d8-470a-8d8e-e62a39734ce8)
![2](https://github.com/Regalis11/Barotrauma/assets/39614559/6b7337b7-bf72-471d-8c21-e51c1153d029)

### Reproduction steps

1. Open level editor, select ridgebasic
2. Select ballastfloraspores from level objects, set commonness to something high, and spawnpos to LevelStart for ease of checking
3. Generate and Test
4. Notice how the ballast flora spores are only visible on sonar.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.1.0 (Unstable)

### -

Both stable/unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6933739b68c49a528b2b52af0e4972dcb42bf263 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
