### ISSUE TITLE
Affliction icon flickers rapidly in single player when using broad spectrum antibiotics

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1304]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure what to say about this, was trying to find bugs by getting a partial-usage medical and found other oddities instead - the below clip is pretty much all you need to see:

[clip of broad spectrum antibiotics icons after use in singleplayer](https://i.gyazo.com/13e3614a75a2a8d8430a26d55175b3a2.mp4)

**Steps To Reproduce**
use broad spectrum antibiotics on yourself via the medical hud, I didn't apply it to any particular body part and just used the general medicate button.

**Version**
0.8.9.6 steam closed alpha

**Comment by Regalis11** [comment]
Fixed in cb6dcd4
