### ISSUE TITLE
Custom husk appendage or affliction makes character immune to pressure and suffocation even if in husked species config these things are not set

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [Regalis11/Barotrauma#13051]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

So, if you have custom husk appendage for whatever you needed that this thing or affliction that provides it makes character immune to suffocation and pressure for some reason. In husked species config needsair was set to true and crush depth was set to normal human's crush depth and character with affliction was still immune to pressure and was not suffocating without oxygen.

### Reproduction steps

1. Create custom husk/change needsair to true and crushdepth to human's in normal humanhusk
2. Start game and launch sub
3. Give husk symbiosis so you can control yourself
4. Teleport yourself outside the sub
5. Swim around and think about life
I will also send humanhusk with everything prepared
[Humanhusk.zip](https://github.com/Regalis11/Barotrauma/files/13393294/Humanhusk.zip)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The affliction is what determines whether the character is immune to pressure or needs oxygen. It seems both of the afflictions in the zip don't define NeedsAir, which makes it default to false. Try adding `needsair="true"` to the afflictions and it should fix this! :)

**Comment by Alpharius-30-milenium** [comment]
Ah, so it just by default set to false in that type of affliction?

**Comment by Regalis11** [comment]
Yep, and actually that property only exists in the husk afflictions: https://regalis11.github.io/BaroModDoc/ContentTypes/Afflictions.html

**Comment by Alpharius-30-milenium** [comment]
Guess I was blind enough to not see it in documentation earlier
