### ISSUE TITLE
Fabricator should have a search bar function

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1305]
![-2019-mar-19-021](https://user-images.githubusercontent.com/38168249/54603491-06f82480-4a77-11e9-886a-ff17fe3d0681.jpg)
Having to scroll through about 80(or even more, if playing with mods) craftable items seems like an unnecessary waste of time, especially considering that the items already have their set craft times.
If you already know what you want to make, it would be a lot more convenient and would take a lot less time, if you were able to just type in the name and get the item you need.

**Comment by NilanthAnimosus** [comment]
maybe not just a search function, but a category or search function and categorized lists.

**Comment by Regalis11** [comment]
Added in 2290645
