### ISSUE TITLE
It still feels like welders area of effect repairs don't quite hit difficult hulls in multiplayer over single

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1306]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have been using the welder for some time on a number of submarines and damaged areas of them, and although you can usually stop the flooding now with a little effort, its quite often still very difficult to hit certain walls with a welding tool on multiplayer. 

Often the health bar of a wall will be visible, but it won't actually be hitting said wall, likely hitting one above or below as its virtually inside the same rough space and damaged. These often don't cause leaks, but I have witnessed many use a lot of welding fuel attempting to repair these and eventually managing to do so.

it is as if a nearby wall absorbs it and no matter where you aim this generally is the case except for a small .2-.3 of a degree where it may pass and hit the damaged part. it is otherwise perfect on single player, but on single player you can pretty much Guarantee your rotation, aim and distance are all correct, in multiplayer it seems enough to make it difficult to repair in some cases still.

I feel the new welding changes might not quite help with these walls.

**Version**
version 0.8.9.6 steam closed alpha

**Additional information**

Me trying to weld on multiplayer the PAX (And I am unfortunate enough to be near OCD on my damage):

[Clip A of PAX](https://i.gyazo.com/ad5ab1f30e893aca055aa5fb59c3e1a7.mp4)

[Clip B of PAX](https://i.gyazo.com/39ab197ef2962dcd22078d998e65cd01.mp4)

Lets look at this same situation in single player, where even though awkward its a lot simpler to do and get through:

[Clip C of PAX](https://i.gyazo.com/0d56f125559c99e3af92773baea962d1.mp4)

**Comment by Regalis11** [comment]
I think the problem might be that the raycasts don't hit the walls when the tool is inside the wall (and it looks like that's happening in those clips). I think I'll change the repair logic so that the raycasts can hit even if the start of the ray is inside the wall section.
