### ISSUE TITLE
flares do not ignite or trigger when thrown, making them worthless paperweights

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1307]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Left clicking, throwing, seemingly doing anything will not ignite a flare, I cannot discern any method to actually use these and I am leaning towards them perhaps being bugged.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.8.9.6 steam closed alpha

**Additional information**

[Clip of a flare not activating](https://i.gyazo.com/4783eac6ad128701e58ae795e4281d38.mp4)

**Comment by Regalis11** [comment]
Fixed in 2c17675

**Comment by Regalis11** [comment]
Still not fixed, it seems that the TargetItemComponentName comparison in PropertyConditionals is bugged
