### ISSUE TITLE
Large Engine Thrust % Slider Error

### ISSUE THREAD

**Issue by Arctodites** [Regalis11/Barotrauma#13076]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The UI slider for the [*_[edit] 'Engine'_*] and the 'Large Engine' thrust has an inconsistency in its adjustment intervals, whereby instead of sliding to -40% thrust when adjusted manually, it slides to -39%.  So far as I can tell, this is a problem with both the 'Engine' and the 'Large Engine,' but only at the -40% interval.

![Barotrauma_Large_Engine_Kastrull](https://github.com/Regalis11/Barotrauma/assets/110938168/520bb84a-a198-4d3b-b840-db24ab957873)

### Reproduction steps

1.) Load any sub with [*_[edit] an 'Engine' (e.g. the Herja) or_*] the 'Large Engine' (e.g. the Kastrull) into the sub editor.
2.) Unwire any wires attached to the SET_FORCE pin of the engine's connection panel.
3.) Press the play button to enter 'test' mode.
4.) Power up the reactor.
5.) Manually adjust the UI slider of the engine's thrust backwards to -40% (negative forty percent).
6.) Notice that instead of reading "-40%", the slider reads "-39%".

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/A.
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1fa3a566e4e3cf442aedb856ddad67cdf5b97212 (commit in our private repo)
