### ISSUE TITLE
[UNSTABLE] Indentured servitude stacking allows for 0mk assistant purchases

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#13078]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Unpaid labor using indentured servitude.
![image](https://github.com/Regalis11/Barotrauma/assets/86113712/203bd679-b5c8-40df-9045-19ca126e4fe1)

### Reproduction steps

Buy an assistant. Buy another assistant. Buy another assistant. Buy another assistant. (Buy 4 assistants)
Give every assistant indentured servitude.
Dock to an outpost.
Look at the HR manager's available crewmembers.
Unpaid interns.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional
