### ISSUE TITLE
Medic Bot Item Usage Priority 

### ISSUE THREAD

**Issue by Character-Note** [Regalis11/Barotrauma#13073]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the Medic Bot always heals all of my symptoms except for heavy bleeding. Which brings my health back down low enough that the bot uses even more medical items to restore my health again, but it still doesn’t use bandages to stop the heavy bleeding. I had to manually use bandages myself since the bot was prioritizing using everything else except for bandages to stop the heavy bleeding. 

I personally think it’s alright for the bot to prioritize healing the most severe wounds you have first, but it should use bandages immediately after applying anything else like morphine if it detects that you are bleeding.

In addition, I’d like to suggest that perhaps a small timer could be added so that the bot lets what it injected you with take effect and heal you before continuing to inject more morphine, opium, and so on as needed to minimize medical supply wastage by the bots. Perhaps at a certain medical skill level?

### Reproduction steps

1. Start a mission with a medic bot.
2. Get heavily wounded and make sure you’re bleeding.
3. Watch as the bot heals every symptom except for bleeding, and watch as it continues to use everything else except for bandages, plastiseal, or antibiotic glue.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
looks fine to me

https://github.com/Regalis11/Barotrauma/assets/122838333/2311d540-2ca2-49c7-8606-13db7a36518b
