### ISSUE TITLE
Auto operate turrets cannot target crew

### ISSUE THREAD

**Issue by rkcf** [Regalis11/Barotrauma#13088]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A turret set to auto operate will not fire upon crew. Not sure if this is intended to be this way, but this functionality would be greatly appreciated as someone who is attempting to make a trap on a custom beacon station. Would be nice to have a separate editor toggle to enable friendly targeting.

I believe this is the relevant code section.

https://github.com/Regalis11/Barotrauma/blob/8aa4257331110900dca074ad4a62f2d513f700fe/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs#L1645-L1667

### Reproduction steps

1. Open Sub editor
2. Place hulls, supercap etc. to make a test room
3. Place turret
4. Enable Auto Operate on turret
5. Connect power to turret
6. Link ammo loader to turret
7. Test sub
8. Walk in turret range. Will not target or fire upon crew

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! It should be possible for the autoturrets to target the crew. You need to make sure TargetHumans is enabled. As seen in that code snippet you linked, the turret doesn't shoot at characters who belong to the same team the submarine it's in belongs to. In the submarine editor, the sub/station you're testing is always considered to belong to you, so the turret will consider your crew friendly characters, but that won't be the case when the beacon station is actually spawned in the level.
