### ISSUE TITLE
Steam Will open Dark Souls 2, but 

### ISSUE THREAD

**Issue by Bender91** [Regalis11/Barotrauma#13084]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dark Souls 2 on Steam will try to start up, and a black window will come up but then immediately crash. I am able to play Wolfenstein Enemy Territory the same way, but I'm not sure what's the problem. I'm new to this so I'm not sure what to do. 

### Reproduction steps

1. I open Steam through Whisky
2. I hit play on Dark Souls 2
3. Black Screen Appears and then immediately closes

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: winecfg -v win10 

Launched Wine (79145)
msync: bootstrapped mach port on wine-108fa6f-msync.
msync: up and running.
00f0: thread_get_state failed on Apple Silicon - faking zero debug registers
00f8: thread_get_state failed on Apple Silicon - faking zero debug registers
0110:err:module:open_builtin_so_file failed to load .so lib 

Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0110:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
002c:err:setupapi:SetupDiInstallDevice Failed to start service L"wineusb" for device L"ROOT\\WINE\\WINEUSB", error 1114.
002c:err:setupapi:SetupDiInstallDevice Failed to control service L"wineusb" for device L"ROOT\\WINE\\WINEUSB", error 1062.
```

**Comment by Regalis11** [comment]
Thank you for the report! This issue tracker is for issues in the game Barotrauma, unfortunately there's not anything we can do about issues in Steam, Dark Souls 2 or Wolfenstein Enemy Territory.
