### ISSUE TITLE
Medic tutorial: unable to progress 'administer morphine to doctor' task

### ISSUE THREAD

**Issue by favogiuseppo** [Regalis11/Barotrauma#13085]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In the medic role tutorial, doctor James Been asks to administer him some morphine. Doing so doesn't mark the task as completed.
Looking online, I found that he's supposed to have a head concussion, but that doesn't happen.

### Reproduction steps

1. Start roles tutorial
2. Select medic role
3. Get the morphine from the medicine cabinet
4. Administer morphine to doctor Been doesn't mark the task as completed

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't reproduce the issue: the doctor seems to have a concussion and treating him with morphine seems complete the objective with no issues. You mentioned that you're using mods, which kinds of mods? It could be that if they e.g. modify afflictions or treatments in some way, they could be interfering with the tutorial.

**Comment by favogiuseppo** [comment]
My bad, apparently it was Neurotrauma causing the lack of concussion on the doctor. Or at least, disabling the Neurotrauma mod made the tutorial possible to complete without a hitch.
