### ISSUE TITLE
Items in equipped items get flipped vertically when facing left

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#13083]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://files.slack.com/files-pri/T0D058T4P-F067K35L1G9/image.png

### Reproduction steps

1. Equip a welding tool with a tank in it
2. Face left

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4693/commits/44d619617966520fc532a8352ea82c8aac1ee63d

Tested welders, guns, crates, medical items.
While being held and flipping through sub-editor

No issues found
Closing ticket
