### ISSUE TITLE
[Unstable] Looping sounds won't stop playing on stations

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#13081]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sounds should have stopped playing after use, but they keep looping. Looping sounds like welding tool, plasma cutter, low o2 warning, underwater scooter continue to play at the coordinates where the player was. Sounds only stop when the player is far enough away to stop them. Tools should make sounds, but stop making sounds once too many looping sounds from the tool are playing elsewhere.
![baro many sounds](https://github.com/Regalis11/Barotrauma/assets/39156231/efd18712-a8f2-4ffe-a8cb-3035a75203fd)

### Reproduction steps

1. Start multiplayer campaign
2. Create many leaks across a station from within the station (ideally with plasma cutter across a long area) until you detect a sound continuing to play where you were for no reason.
3. Make sounds with tools such as welding tool, plasma cutter, and underwater scooter

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Other

### -

v1.2.2.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested by causing a large explosion on one of the modules in outpost and then using a plasma cutter after, in Unstable the plasma cutter sound kept playing after use while on the PR it didn't. So working correctly. Can be merged and closed.
