### ISSUE TITLE
All Player-Produced Lighting Unseen Outside of Sub

### ISSUE THREAD

**Issue by Dathomerian554** [Regalis11/Barotrauma#13089]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It seems that all forms of light-producing devices do not work while one is outside of the sub.  This goes from a gun mounted light, glowsticks, and even all kinds of pressure suits for going outside.  The only visible light I am able to see while outside of the sub is either from the sub itself, or natural light located in the level.  View screenshot of this occurring below (note there is a flashlight in the harpoon coil-rifle).  
<img width="1312" alt="Light Outside Sub Not Working IMG" src="https://github.com/Regalis11/Barotrauma/assets/144430175/36c99126-f51d-4bc9-bd99-91b052de6e60">

I have not tested this in multiplayer, so I couldn't say if it happens there.  

### Reproduction steps

1. Start single player campaign.  
2. Equip any form of light producing device, such as an exosuit, glowstick, or flashlight.  
3. Leave the sub.  
4. Note how no light is seen from devices outside of the sub.  

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

MacOS

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/564e0d02a33ab9d30964c38088febb65330e39ba

Tested with all light producing items in and out of the sub

No issues found
Closing ticket

**Comment by mrjpjr** [comment]
From my testing there seems to be an issue with lighting when passing between hull and non-hull locations.
See video attached below:
https://github.com/Regalis11/Barotrauma/assets/58775950/46b2393b-57e8-454a-977c-dd26e2b92ff4

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/af5fcd27-898f-43e0-8da0-05d34d5ff3de)
