### ISSUE TITLE
[Unstable] Flashlight placed in unequipped guns giving light

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#13082]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Flashlight cone appearing from player's torso when flashlight is placed in an unequipped gun's flashlight slot
![flashlight in guns](https://github.com/Regalis11/Barotrauma/assets/39156231/b0fefb07-dbef-4ee8-a80d-303f94546a9c)

### Reproduction steps

1. Start campaign
2. Have an unequipped gun in inventory that has a flashlight slot (works with harpoon gun, smg, rifle, shotgun, autoshotgun, hmg)
3. Place flashlight (with battery) inside
4. Enjoy 0 degree light cone

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

### -

v1.2.2.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4694/commits/564e0d02a33ab9d30964c38088febb65330e39ba

Generally holstering weapons with lights work
Tested with weapons holstering to back slot and normal inventory
Different order of putting flashlight in gun and holstering

One issue found
Light is visible inside of containers when light and gun is inserted in certain order
1. Insert gun into a container, Cabinet, crate or storage container.
2. Insert light into the gun by dragging it
3. Light turns on and is visible
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/aed5ed6b-37a6-4fd3-a822-f192ee453583)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4694/commits/ce748dcc11eb6e5dfa0c333ebe62d8e5d3c89c62

No issues found
Closing ticket
