### ISSUE TITLE
Modifications with using `RadioJam` do not work

### ISSUE THREAD

**Issue by PlasmaUwU** [Regalis11/Barotrauma#13095]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm making a mod that uses the new "RadioJam" feature, but it's not modifiable.
In the example below, I showed that I tried to replace `<hint.radiojammed>` and `<radiojammedwarning>`, but nothing changed.
And I also tried to make it so that when the character is stunned, Radio Jam is used on the headset, but it also didn't work

https://github.com/Regalis11/Barotrauma/assets/101663742/a93521b2-7726-44a0-927a-21ad6899e799

### Reproduction steps

1) Try to Modify something with radionjam
2) Be disappointed

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

The override element seems to be configured incorrectly. You need to put the text elements inside the override element, i.e.
```
<override>
    <hint.radiojammed>Custom text here</hint.radiojammed>
</override>
```

> And I also tried to make it so that when the character is stunned, Radio Jam is used on the headset, but it also didn't work

I'm afraid there's not much we can do to diagnose this without more info on how exactly you tried to implement it.

**Comment by PlasmaUwU** [comment]
And a month later, I remembered about that unfortunate mod that I had problems with...

Alas, after the current test, it turned out that the error was making by me, both there and there.

I apologize for the time spent :<
