### ISSUE TITLE
Fabrication recipe hash error when enabling certain mods

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#13098]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Some mods throw an error about identical fabrication recipes when trying to enable them. While this is intentional, the error sometimes says the problem is in the vanilla package instead of the mod.

### Reproduction steps

1. Try to enable the Sounds of Europa mod

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed. 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/b1b02522-a72b-475a-83f1-b3e0936e85bb)
