### ISSUE TITLE
CanBeCombined="True" no longer working for all types of items

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [Regalis11/Barotrauma#13107]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In the current unstable build, the canbecombined="true" no longer works on ammo boxes while it works perfectly in the current stable release. I used my "Immersive Ammunition Boxes" mod as a test subject in both versions.
The mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=3089776991

I've prepared short clips to quickly show the issue:
On stable release:

https://github.com/Regalis11/Barotrauma/assets/74098498/35281341-077b-4cb7-99a5-3e9ad3a61aa1

On unstable build:

https://github.com/Regalis11/Barotrauma/assets/74098498/14d1aa7b-70c8-44e9-a770-4c4a10c5f33a

### Reproduction steps

1. Modify ammunition boxes to be combinable.
2. Load stable release - you can combine them.
3. Load unstable build - you can no longer combine them.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
What about SMG ammo and welding fuel?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7907f47c93e66601f046a30955ea0066cd99d9f
