### ISSUE TITLE
[Unstable] Crafting in MP temporarily drops items out of the fabricator when crafting completes

### ISSUE THREAD

**Issue by JeroonBosch** [Regalis11/Barotrauma#13105]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In our play session whenever something was crafting, there would be a "Clang" sound of items falling on the ground. It seemed like it temporarily spawned items outside the fabricator and then removed them.
These items were visible and hit the floor (to make the sound) before disappearing.

### Reproduction steps

1. Start multiplayer campaign
2. Craft some Combat Diving Suits for example (have the items in inventory or linked cabinet)
3. Notice the sound and visual appearance of items upon crafting completion (might require a ping over 10?)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Couldn't find a way to reproduce this

**Comment by Jasontti** [comment]
Video of this happening with deconstructor

https://github.com/Regalis11/Barotrauma/assets/8488224/7cf37e07-3ecd-4ef9-aff9-1626ceb0a208
