### ISSUE TITLE
New StatusEffect type combining error. 1.1.19.3

### ISSUE THREAD

**Issue by SydWad** [Regalis11/Barotrauma#13102]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In the past logic i had combining type="OnImpact,OnBroken" on projectiles worked but doesnt seem to now. The projectile explodes on impact but when broken nothing happens and it just becomes inert.
I have tried adding this to working items like the frag grenade and the issue still occurs.
The point of the logic was to avoid having a duplicate of the explosion logic for impacting a surface as well as expiring.

Additional issue, if i add allowwhenbroken="true" the projectile still doesnt explode on impact after expiring.

### Reproduction steps

Here is the simplified logic where the issue occurs.
```
<!-- Explode after 3 seconds -->
<StatusEffect type="OnUse" target="this" Condition="-100" delay="3.0" disabledeltatime="true" />

<StatusEffect type="OnImpact,OnBroken" target="this" forceplaysounds="true" allowwhenbroken="true" >
  <Remove />
</StatusEffect>
```

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I wasn't aware StatusEffects have supported multiple types like this in the past. Looking at the code and the version history, I can't find any indication that the game has ever been able to handle effects with multiple types. Do you recall which version this used to work in or how long ago it was?

> Additional issue, if i add allowwhenbroken="true" the projectile still doesnt explode on impact after expiring.

This seems like a clear bug though, and easily reproducible, we'll look into it!

**Comment by SydWad** [comment]
i can provide the modded item in question that did work previously if you like.
I dont see any way that it could have worked previously when the explosion+removal of the item was all in one status effect.

I have uploaded a test item [https://steamcommunity.com/sharedfiles/filedetails/?id=3107835025](url)

**Comment by SydWad** [comment]
> I decided to give the v1.0 version a test, and it doesn't seem like using multiple types worked there either. The type of the effect gets set to the first type (in this case OnImpact), so I'm fairly sure the effects just happened to work as expected despite the second type being ignored.

i can provide the modded item in question that did work previously if you like.
I dont see any way that it could have worked previously when the explosion+removal of the item was all in one status effect.

[I have uploaded a test item ](https://steamcommunity.com/sharedfiles/filedetails/?id=3107835025)
