### ISSUE TITLE
Lightcomponent's IsActive cannot check for TargetContainer

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#13101]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

IsActive  can be used in a light component to determine whether the component is active or not

However using TargetContainer does not seem to work as seen in

```xml
    <!-- backlit suit -->
    <LightComponent range="0.0" lightcolor="0,255,130,255" IsOn="false" allowingameediting="false" alphablend="false" castshadows="false" >
        <IsActive voltage="gt 0.01" targetcontainer="true" targetitemcomponent="Powered"  />
        <sprite texture="%Moddir%/SuitlockerLighting.png" depth="0.83" sourcerect="0,0,99,256" origin="0.5,0.5" alpha="1.0" />
    </LightComponent>
```

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/30ea913d-040f-4caa-8193-3776ea656777)

The light rectangle won't turn _OFF_, unless the suit is worn (why?)

You can target contained items but not containers as seen with loader lights
`<IsActiveConditional targetcontaineditem="true" conditionpercentage="gt 0"/>`

https://github.com/Regalis11/Barotrauma/blob/8aa4257331110900dca074ad4a62f2d513f700fe/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/PropertyConditional.cs#L245C33-L245C33

I have tried many permutations between IsActive, IsActiveConditional, Conditional, used different types of conditions like checking the suit locker's condition, but nothing happens.

This issue is the key to backlit suit lockers 😨 

### Reproduction steps

1. Download [Leakysuit.zip](https://github.com/Regalis11/Barotrauma/files/13513613/Leakysuit.zip)
2. Load any sub in sub editor
3. Take diving suit outside of suit locker
4. Hold the suit
5. Green rectangle

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/330ed9e667caec91b260cbd02991d29e6d30d6c6

**Comment by ubertpendragon** [comment]
Putting this here in case you're interested in backlit suits

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/8901406f-70f1-4b76-9356-124246b647de)

**Comment by Rokvach** [comment]
Tested with the provided mod, seems to be working correctly. Can be merged and closed.
