### ISSUE TITLE
campaign save sync issue when switching to a new campaign + Submarine location error or only sync problem?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1311]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I believe this might be a problem or cascade problem with file sending or campaign sync IDs or the submarine folder location disparity between client and server as they attempt to select it for campaign (Thus nothing to actually send).

essentially players have problems by being riddled with errors by creating a new campaign and switching submarine to a different one without having started a match or after a campaign match had been done and doing it once or twice.

everyone had errors after having switched campaign again and again (I am not sure if these were different errors!) after it had initially broke, a complete wipe of the steam clients saves (multiplayer and temp) corrects the issue when a valid submarine is selected.

**Version**
0.8.9.6 steam closed alpha with some minor edits+

**Additional information**
Dedicated server console - this shows a statement that a sub does not exist, the submarines are in the base folder (Submarines) and not (Submarines/Downloads) - I believe the client downloaded it and it is in their downloads folder. steam added subs go to the base folder, yet clients don't require them and this can easily cause the below errors perhaps:

![image](https://user-images.githubusercontent.com/29177976/54657693-5c0d5800-4ac2-11e9-9190-0ddd3b730ee4.png)

My clients view:

![image](https://user-images.githubusercontent.com/29177976/54657738-90811400-4ac2-11e9-9d93-b6aabb2b42cf.png)

**Comment by NilanthAnimosus** [comment]
I noticed the reading for clients - the clients themselves send the submarine file location as a string from their side and very literally causes problems from that point on in one way (though there may be multiple issues here, as we kept having bugs when starting multiple campaigns as if the save files were not transferring properly after having caused it to break at first)

in Gameserver under the method ReadDataMessage(NetIncomingMessage inc)
the switch case ClientPacketHeader.CAMPAIGN_SETUP_INFO: has a string value named subname.
subname is actually the full file path to the submarine, I think this (or in the sub load method itself) would be a good place to check if it exists and if not, swap it from the downloads folder to the main submarine folder and try again, otherwise cancelling it with some kind of more controlled error than beginning a campaign without a submarine basically.

multiplayer campaigns amusingly will still begin the game session even when  the submarine is basically null or improperly loaded, I think that needs to be fixed at least.

**Comment by NilanthAnimosus** [comment]
so I spent a ridiculously long time (way too ridiculously at that) trying to get File.Exists() to work, turns out the file didn't actually exist anyways.

My client was trying to use a submarine file that wasn't even on the server.

attempting to load the file path of "Submarines\\Capelin MkV.sub"
Even though my server only had the file Capelin_MkV.sub
where my client had Capelin_MkV.sub and Capelin MkV.sub

I feel potentially like I wasted an epic level of time now, but at least I know i'm not going insane by failing to use File.Exists.

**Comment by NilanthAnimosus** [comment]
I know this is no fix, but I did simply tweak the code (I did it in submarine loading methods then migrated it to where your fix was) to switch the file path of the submarine where the common location a client typically has it downloaded to once receiving from a server.

the only reason I have it switch the path back again is so it sends the likely original path back to the client, though its not a good fix. I am sure paths other than submarines/downloads (I dunno, mods/submarines) would convert to having downloads at the end.

in the short term this generally let any server on my submarine be used for playing though and I have yet to see any issues myself.

```csharp
case ClientPacketHeader.CAMPAIGN_SETUP_INFO:
                    bool isNew = inc.ReadBoolean(); inc.ReadPadBits();
                    if (isNew)
                    {
                        string savePath = inc.ReadString();
                        string seed = inc.ReadString();
                        string subPath = inc.ReadString();

                        if(!File.Exists(subPath))
                        {
                            if (subPath.Contains("Submarines\\Downloaded\\")) subPath = subPath.Replace("Submarines\\Downloaded\\", "Submarines\\");
                            else if (subPath.Contains("Submarines\\")) subPath = subPath.Replace("Submarines\\", "Submarines\\Downloaded\\");

                            if (!File.Exists(subPath))
                            {
                                //If it fails again, then its not in Downloaded or Submarines folder, thus the server does not have it.
                                if (subPath.Contains("Submarines\\Downloaded\\")) subPath = subPath.Replace("Submarines\\Downloaded\\", "Submarines\\");
                                else if (subPath.Contains("Submarines\\")) subPath = subPath.Replace("Submarines\\", "Submarines\\Downloaded\\");
                            }
                        }

                        if (!File.Exists(subPath))
                        {
                            SendDirectChatMessage(
                                TextManager.Get("CampaignStartFailedSubNotFound").Replace("[subpath]", subPath),
                                connectedClient, ChatMessageType.MessageBox);
                        }
                        else
                        {
                            if (connectedClient.HasPermission(ClientPermissions.SelectMode)) MultiPlayerCampaign.StartNewCampaign(savePath, subPath, seed);
                        }
                    }
                    else
                    {
                        string saveName = inc.ReadString();

                        if (connectedClient.HasPermission(ClientPermissions.SelectMode)) MultiPlayerCampaign.LoadCampaign(saveName);
                    }
                    break;
```

**Comment by Regalis11** [comment]
I'm not sure if the above fixes are needed after c78546b (although there might still be some bug that causes the file paths to get messed up, and that code may in some cases be able to resolve the problem). The client should only display the submarines the server has in the campaign setup UI, and use their file paths, so there should be no need for the server to "guess" where the file might be at their end.

**Comment by NilanthAnimosus** [comment]
Yeah I wasn't sure how far that extended, if it was just the campaign menu or all instances of the sub list. but since I couldn't really use it as of current (no way it would sync without updates : P ) my little hotfix will work for me for now to make starting campaigns less awkward : >

**Comment by Rokvach** [comment]
Haven't seen this happen while hosting a server for the testers, which would indicate it working properly now, so closing this.
