### ISSUE TITLE
Submarine failed to dock to outpost, ended round, next round it was stuck to outpost

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1312]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Submarine failed to dock to outpost, ended round by talking to outpost guy, next round it was stuck to outpost

**Steps To Reproduce**
The save file here https://github.com/Regalis11/Barotrauma/issues/1293 starts the submarine stuck in this state.

**Version**
Steam closed dev

**Additional information**
An alien busted the docking hatch earlier and we repaired it, maybe that's why.

**Comment by NilanthAnimosus** [comment]
I was actually writing #1313 which pertains to this issue, I was the host of this game and endroundatlevelend="False" which is the reason the level did not end.

The level ended when I (the host with "All" permissions and commands) spoke to the watchman correctly. the round was not ended but was docked and used the watchman.

As for the next round it being stuck - I am not actually sure if it was stuck or not.
Examining the first campaign save file the docking clamp releases the submarine correctly.

**Comment by thegrb93** [comment]
This issue pertains to when I was hosting earlier. I don't think you had joined yet.

**Comment by NilanthAnimosus** [comment]
alright, I kind of want to find one of these games where the sub gets stuck at an outpost. it is strange that it gets stuck

**Comment by thegrb93** [comment]
If I'm right, all you have to do is break the docking hatch and repair it.

**Comment by Regalis11** [comment]
Does not seem to occur anymore in the save file provided by Nilanth. I think this may have been fixed by either the fix to the way the game determines the orientation of the docking ports or the way it makes room for the sub around the outpost.
