### ISSUE TITLE
High Pressure behavior is inconsistent and lacks feedback

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#13121]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a room fills with water, it can be viewed using `debugai` in the console commands. This shows the gradual increase in pressure until it reaches a lethal threshold, shown when the red bar reaches about 80% capacity.

However, between the time of the room being full of water and it being lethally pressurized, there is absolutely no warning that the room you are in is on its way to *becoming* lethally pressurized. Originally, the screen used to zoom in gradually to clue the user in that the area was becoming dangerous. This no longer seems to be the case, it jumps from "You are completely safe" to "Full zoom, danger, it's *extremely* pressurized, you will die in 5 seconds, massive organ damage."

Here is an extreme example, with a small breach taking a full 15 seconds to go from the room being full of water to becoming lethally pressured, and once lethally pressured, killing in only 5. *No organ damage even occurs up to that point.*
https://github.com/Regalis11/Barotrauma/assets/5988156/4a20347d-9a6e-4295-ae8b-ed2c293fec60

There is also an inconsistent behavior with Ballasts and their pumps. Ordinarily these pumps are able to fight off huge breaches through sheer flow rate, but an unusual behavior occurs: Like the small breach, the room takes a long time to fill up with water, but unlike them, it suddenly becomes very lethal, very fast once it does fill completely.
https://github.com/Regalis11/Barotrauma/assets/5988156/47a70661-74a6-4303-b6aa-5b2f59ae3181
Note how the pressure number struggles to reach 0 for most of the video, but once it does, it shoots past it in the hundreds.

This leads to pressure still feeling inconsistent in its lethality and mechanics. Ideally, the return of the gradual zoom would help greatly, but also for pumps to help stave off lethal pressure for a little while even in fully flooded environments, effectively making the second video's huge breach behave more closely to the first video's small breach.

**Notes:**
Issue occurs on v1.1.19.3 (Treacherous Tides Hotfix 2) and v1.2.3.0 (Unstable)

### Reproduction steps

Prerequisites:
1. Ensure `debugai` is enabled in the command console during the test

Repro Steps:
1. Launch the title
3. Enter the Submarine Editor
4. Start Test in the R-29 Submarine
5. Cause a small breach in the crew quarters
6. Observe whether pressure gradually or suddenly increases in lethality

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, no issues. Can be merged and closed.
