### ISSUE TITLE
Assistant can't pick all the tier 1 and 2 talents

### ISSUE THREAD

**Issue by 1stLtv2** [Regalis11/Barotrauma#13138]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

assistant need higher level cap to unlock all talents
![未命名](https://github.com/Regalis11/Barotrauma/assets/65464699/0646d01d-8f14-4d74-9c96-b326f818e067)

### Reproduction steps

Self explained

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not sure I understand the issue here, you seem to have already unlocked all the available talents in the screenshot?

**Comment by Kokhirus** [comment]
Seems like an assistant lacks 4 more levels to get all the talents from 2 basic talent rows.

**Comment by HawkinsThe71st** [comment]
The `maxchosentalents` value wasn't increased from 4 to 6 to allow the player to unlock all of the t1 and t2 talents as is the case with other jobs
From TalentTrees.xml:
```
  <TalentTree jobidentifier="assistant">
    <SubTree identifier="assistant_primary" nameidentifier="talenttree.primary" type="primary">
      <TalentOptions requiredtalents="2" maxchosentalents="4">
        <TalentOption identifier="playingcatchup"/>
        <TalentOption identifier="mailman"/>
        <TalentOption identifier="skedaddle"/>
        <TalentOption identifier="crewlayabout"/>
        <TalentOption identifier="starterquest"/>
        <TalentOption identifier="mule"/>
      </TalentOptions>
      <TalentOptions requiredtalents="2" maxchosentalents="4">
        <TalentOption identifier="revengesquad"/>
        <TalentOption identifier="inspiringtunes"/>
        <TalentOption identifier="bagitup"/>
        <TalentOption identifier="peerlearning"/>
        <TalentOption identifier="indenturedservitude"/>
        <TalentOption identifier="jengamaster"/>
      </TalentOptions>
    </SubTree>
```

**Comment by Regalis11** [comment]
Ah, I didn't remember we'd made it possible to unlock all the T1 and T2 talents! Yeah, it does seem that `maxchosentalents` is the issue here.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4753/commits/58b7fa9944115cf88d343646246179747a8b9d6b

Made a new save in SP and MP
Loaded old save
Picked different configurations of talents

No issues found
Closing ticket
