### ISSUE TITLE
Outpost guards don't swap batteries in their stun batons

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#13131]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

They carry like 8 batteries just to lick them i guess

https://github.com/Regalis11/Barotrauma/assets/122838333/d6eb6a65-9967-4ed3-9341-82e3b2c9636f

### Reproduction steps

1. steal something
2. discharge guards batons with your body (or someone else's)
3. control the guards and see that they were beating you with discharged batons

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I'd say this is a bug.

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4751/commits/f9b5085ada8e35f4e208454055c6efb37d38b7d1

Testing by getting repeatedly assaulted for petty crimes.

Outpost security now properly swaps their batteries.

No issues found
Closing ticket
