### ISSUE TITLE
Makeshift armor sprite Foreground/Background reversed Arms, Legs and Feet

### ISSUE THREAD

**Issue by Draconis13** [Regalis11/Barotrauma#13134]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wearing makeshift armor the left and right legs are reversed on the .png is very noticeable once you see it the first time. The darker background leg and arm are in the foreground and vice versa causing a weird lighting issue with the armor.  

Was using the .png as a base for custom armor sprite and testing how it looked without any mods on. Noticed foreground and background were reversed on base game image except for hands. 

### Reproduction steps

craft or spawn makeshift armor and put it on, foreground and background for arms, legs, feet but not hands are reversed due to placement on sprite sheet.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf709a57abe883a41ccad4f27a79e9549c1373af

**Comment by NilanthAnimosus** [comment]
Tested against release/winter-update-hotfix-1 commit https://github.com/Regalis11/Barotrauma-development/commit/6e28b695e3382595cbd574a45f91c7bb9d54c6c9 (Changes only visible in private repo)

Functionally this seems fine. but im curious to something, would it not be better/more compatible to do what other items (IE. the diving suit) does by using depthlimb="RightForearm" and depthlimb="RightArm" over inheritlimbdepth="false" depth="0.05" ?

**Comment by NilanthAnimosus** [comment]
Tested against release/winter-update-hotfix-1 commit https://github.com/Regalis11/Barotrauma-development/commit/1d08609848051527d19d36a56315fcd2b7b45920(Changes only visible in private repo)

works fine and now uses the same method as diving suits do.
