### ISSUE TITLE
[Unstable] The pump in Engineeringmodule_02 can be used to flood the outpost

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#13149]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can interact with the exposed Signal Check component in Engineeringmodule_02 to easily flood the outpost and grief or kill the AI

There might be more modules with this issue, I didnt check

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/24cee66e-ebfc-47c0-a9d7-0a28e9d29d76)

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/e94b3622-13d5-42d8-b805-dcb4e78251af)

### Reproduction steps

1. Change signal check true/false to 100 100 
2. Change water detector output to 1 1

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ed186d85dd829e9cf3b59a965fcab5b7f73324c

**Comment by JeroonBosch** [comment]
Assigned @Alkumursu for testing

**Comment by Alkumursu** [comment]
**REVIEW**

**CrewModule_02**
Needs more work: 
Water pumping out works. Water detector and signal check attached to right side pump aren't disabled for the player.

**CrewModule_03**
Needs more work: 
Water pumping out works. Water detector and signal check attached to left side pump aren't disabled for the player.

**EngineeringModule_01** 
Needs more work: 
Water pumping out works. Water detector and signal check attached to 2nd floor pump aren't disabled for the player.

**EngineeringModule_01_Colony** 
Needs more work:
Neither of the two pumps on this module get rid of the water automatically. Water detector and signal check attached to left side pump aren't disabled for the player.

**EngineeringModule_02**
Everything works!

**EngineeringModule_02_Colony**
Needs more work:
Water pumping out works. Water detector and signal check attached to pump in the reactor room aren't disabled for the player.

**MedicalModule_01**
Everything works!

**MedicalModule_02**
Everything works!

**SecurityModule_01_Colony**
Everything works!

**Comment by Regalis11** [comment]
All of those should be now addressed: https://github.com/Regalis11/Barotrauma-development/commit/b10b43b4b7dfef1ef670b9ba785993ce46293888
