### ISSUE TITLE
Error in Russian localization in Color Component interface

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#13141]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![2023-12-10_21-27-09](https://github.com/Regalis11/Barotrauma/assets/47295383/b4ca7e77-528a-4b0b-b1a9-0b563a089b0e)

"СИНГАЛ" is written instead of "СИГНАЛ"

### Reproduction steps

Just switch to russian localization, and open Color Component interface

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! I've fixed this in our localization kit now, but unfortunately the changes won't be making it to the next update yet.
