### ISSUE TITLE
[Feature Request] Mass Hull Repairs, Mass Item Repairs at outposts for a price

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1314]
Similar to FTL, it would be nice if you could pay a fee to get the damage done to your ship completely fixed up at stores, for perhaps 2000 credits for a full ship repair (cheaper depending on how much damage is done to ship). As of right now everything STILL degrades even when docked to an outpost so throughout the whole campaign you never get a mint condition ship like what you got when starting the campaign.

**Comment by NilanthAnimosus** [comment]
I like this idea naturally, I'm just going to point out an old issue I made a long time ago that I feel is similar to this and also still a beneficial extension of the campaign menus and capabilities: #245
