### ISSUE TITLE
Mission killcrawlerswarmlarge2 missing description

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#13153]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The mission `killcrawlerswarmlarge2` is missing a description when displayed in the mission list:
![image](https://github.com/Regalis11/Barotrauma/assets/115734437/e4d58ca4-6e3e-4bf7-aec4-de46d5cf2ebc)
Occurs in stable and unstable.

### Reproduction steps

1. Start new campaign
2. `enablecheats`
3. `unlockmission killcrawlerswarmlarge2`
4. Check mission when selecting destination

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd18871522c9040c1297e427ab003960f3d50e67
