### ISSUE TITLE
R-29 has shadow casting lights on coilgun loaders

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#13150]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

R-29 has shadow casting lights on coilgun loaders, bringing the shadow-casting total to 32 lights instead of 20

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/5ff624c1-f4ed-457d-a3f7-813eeae53879)

### Reproduction steps

.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2d518d691c93c5e6c257dbb9205e270c5b2c7863
