### ISSUE TITLE
Missing selection box of  some items in sub editor  and maybe scale issue bug.

### ISSUE THREAD

**Issue by Psyduckdeluxe** [Regalis11/Barotrauma#13155]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/78105038/5e7bae18-7ea2-43a5-9368-62d8da5187f8)

Some items seems to missing their item selection box in the sub editor.  Neon light frame and heater as example.
all the neon lights. 
Seems to be most of the stuff that had rotation before 

Also not sure if this is a bug or as intended but before unstable  You could scale down items below 0.100 
This is not possible anymore.....i assume this is a limitation of getting rotation for most stuff.
But still sucks! Since it ruins the ability to use turrets as  analog dials  as an example
![image](https://github.com/Regalis11/Barotrauma/assets/78105038/0273c5cf-fab1-4507-8138-179173c8d40f)
and now 
![image](https://github.com/Regalis11/Barotrauma/assets/78105038/74ebffca-7dbb-4641-979d-a343b10b7c34)
But i imagine some visual stuff broken on quite a few that might have used items sizes below 0.100

If i need to make this a separate bug let me know.

### Reproduction steps

Start Sub editor put heater in the world and try and select it.

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### -

Sub Editor issue.

### Version

v1.2.5.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment]
- Selection boxes for some items disappearing has something to do with zoom level I think, 

as for scaling items below 0.100 that has never been a thing so that 'bug' isn't new.

**Comment by Psyduckdeluxe** [comment]
Im sorry EK but that just isent true.....everything that could be rotated before could be scaled to under 0.100 its literally in the picture.....

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
