### ISSUE TITLE
an extra water detector for a dugong

### ISSUE THREAD

**Issue by LilPuj** [Regalis11/Barotrauma#13163]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On the dugong submarine, there is a water detector in the oxygen compartment to the right of the pump, which is not connected to anything. Perhaps the creator of the submarine did not see him in the dark and left him like that. I thought it would be removed after the update, but it's still there. Of course, this is not a bug, but I do not know where to report it.

### Reproduction steps

1. Launch the Submarine Editor (or start the game)
2. Select the Dugong submarine
3. Enter the oxygen generator compartment
4. There is a water detector to the right of the pump
5. Unscrew it and disassemble it :)

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Even though this is probably unintentional, I don't think it seems necessary to address. Imo it does no harm that there's one kind-of-hidden component in the sub that you can harvest for materials or repurpose for something.
