### ISSUE TITLE
Game freezes when you try to update your mod which you're not subscribed to

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#13166]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Mod is actually gets updated but barotrauma freezes on this screen and you have to kill the process
![20231215065341_1](https://github.com/Regalis11/Barotrauma/assets/122838333/bdce343b-1150-4609-bae5-e543a99d454b)
If you was subscribed to your mod then it works just fine

### Reproduction steps

Have a mod which hasn't been updated to "winter update" yet
make sure you're not subscribed to it
try to update it

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this. :/ Tested updating a bunch of old mods I've published on the Workshop, which I'm no longer subscribed to, and all of them seemed to update with no issues.

I suspect this requires some more specific circumstances to occur. Do you see any errors or warnings in the debug console when this happens?

**Comment by SomeRandomNoobKekeke** [comment]
Hmm... I did some more testing

This only happens once, when you update some mod from "1.1.19.3" to "1.2.6.0"
This doesn't happen when updating from "1.2.6.0" to "1.2.6.0"
This also doesn't happen when updating older mods e.g. "1.0.21.0" to "1.2.6.0"
It won't happen if you try to revert version in steam workshop and update again
You can open console and even "quickstart", but this message box will still hang

I still have some "1.1.19.3" mods, if you want i probably can add you as co-author, so you could try to update them yourself, but it seems that there's only one shot per mod
![barodev small](https://github.com/Regalis11/Barotrauma/assets/122838333/3f5be283-2955-4d07-9563-074aaaf0e3e6)


https://github.com/Regalis11/Barotrauma/assets/122838333/a3277b59-f124-433c-998a-c61e95809ee5


https://github.com/Regalis11/Barotrauma/assets/122838333/eacaa43b-53c4-4ee4-8b8b-445a814b5f2c


https://github.com/Regalis11/Barotrauma/assets/122838333/e39831a2-1726-4ada-bc8f-710381e1d948

**Comment by SomeRandomNoobKekeke** [comment]
I tried updating one mod from "1.2.6.0" to "1.2.7.0"
Updated without problems
Was the problem in the combination of versions "1.1.19.3" and "1.2.6.0"?
Let's hope this doesn't happen again
