### ISSUE TITLE
Structures that define sprites with fliphorizontal="true" are rotated incorrectly

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#13168]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Reported on Discord
![image](https://github.com/Regalis11/Barotrauma/assets/8607119/90f8e11e-e4f8-4388-a338-92a12dacc660)

This bug affects Legacy's Basic Left Wall so you don't need to install mods to observe it

### Reproduction steps

1. Open submarine editor
2. Place Basic Wall Left
3. Rotate it
4. Observe how the collision box's rotation doesn't match the sprite's rotation

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9f83edaeb936912979116912ff79b77e430c3ff

**Comment by Rokvach** [comment]
Tested seems to be working correctly, can be merged and closed. 
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/e44ebf21-f0e6-4b6e-810e-81267a4ed664)
