### ISSUE TITLE
Orca 1 lower docking port does not flood at all

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#13171]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This unusual hull arrangement causes water not to flood the sub when the hatch is open to the outside.
![orca](https://github.com/Regalis11/Barotrauma/assets/68995233/aa127f38-5f72-4f66-9858-035b6b579931)

The lower docking port is very often converted to an airlock so this is not an edge case.

[hatch.webm](https://github.com/Regalis11/Barotrauma/assets/68995233/9bd95bd1-3e25-4c7b-9d8a-f380e4ece389)

### Reproduction steps

Submarine editor, Orca
Add a button to the lower docking hatch, disconnect the docking port wire
test, click the button

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Suggestion for the lower docking port hulling. Be careful not to extend the hull below the lower edge of the water detector, that will cause water to remain.
![fix](https://github.com/Regalis11/Barotrauma/assets/68995233/b45a96f3-761a-4a2f-8d11-f91241df49f2)

**Comment by SomeRandomNoobKekeke** [comment]
vanilla moonpools confirmed

**Comment by mygamingaccount** [comment]
Not really since there _is_ a gap, instead it's the water that rises really really slowly. (#9544)

**Comment by BlackMoons** [comment]
Yea, Flow through a gap into a hull above is EXTREMELY slow compared to all other gap flows.

Especially the flooded hull is tiny

**Comment by mygamingaccount** [comment]
You're commenting on #9544. The fix for the Orca is trivial.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/919f891951ab967ee5801a3ca728425c93401c4e

> Adjusted hulls in Orca's lower airlock. The small in-between hull with the pump prevented the sub from flooding, because water couldn't flow out from that small hull fast enough to counter the rate of the pump. We've got a separate ticket about that (Regalis11/Barotrauma#9544), but it's a bit more complex to solve so I think it makes sense to implement a workaround for Orca before we get to fixing the underlying issue. Regalis11/Barotrauma#13171

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
