### ISSUE TITLE
Implement shrapnel affliction for hand grenades + tone down their structural damage

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1317]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Realistically, a hand grenade typically kills from the shrapnel it inflicts, leaving no grenade behind to recover (the grenade is oddly left behind at 0 condition after usage). It usually also doesn't do too much damage to metal surroundings given most of the metal shrapnel will usually not piece solid metal walls.

shrapnel wounds should be like gunshot wounds, but only causing bleeding if above a small threshold (so walls can basically protect from it). perhaps later they could require tools (re-usable or not) to remove the affliction but generally it makes more sense this way.

the structure damage of a hand grenade is enough that if you toss it down the hall in the orca - it literally removes the top and bottom walls of the entire sub and even the right side, its large enough to be virtually unfeasible to target intruders and is more of a wall remover.

A separate, more high explosive orientated grenade could be implemented instead for the sake of wall based destruction but would likely cause less to little shrapnel and more burn/explosive related trauma.

**Comment by Regalis11** [comment]
Fixed in 065173f. I used the existing bleeding affliction though - I'd imagine the shrapnel wounds would've worked pretty much the same way, at least for the time being when we don't have any special items for treating shrapnel wounds.
