### ISSUE TITLE
Bots will try to use broken diving suits and die

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#13175]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots will try to use broken diving suits like a regular suit against pressure, then look for another diving suit and sometimes die to pressure

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/b92e1281-4244-417b-9c97-45828e0f8ac7)

### Reproduction steps

1. Dugong
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/ddb4dd44-0c30-4958-83a4-98d8400241ad)

2. Spawn a bunch of mechanics

3. Spawn a bone thresher

4. Order to fix leaks

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/80708d009468a3cc9c2ef5684aa2f0d0ddc25b82
