### ISSUE TITLE
Max condition of incendium fuel tank doesn't get an increase

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#13170]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![weldingfueltank](https://github.com/Regalis11/Barotrauma/assets/64390906/162e4623-33a8-4f57-8490-2b1fea9583d7)
![incendiumfueltank](https://github.com/Regalis11/Barotrauma/assets/64390906/e8c25671-20c6-44e2-853b-e94ee2ea0c99)

### Reproduction steps

1. Open submarine Editor
2. Compare max condition between welding fuel tank and incendium fuel tank

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d08609848051527d19d36a56315fcd2b7b45920 (commit in our private repo)
