### ISSUE TITLE
Object's ghost image does not inherit the rotation of the item.

### ISSUE THREAD

**Issue by Ydrec** [Regalis11/Barotrauma#13185]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Ghost image of objects seem to default to 0.  Happens when placing attachable items in game (i used modified vanilla detonator so its placed upright)  as well as when pasting item assemblies in editor.
![1](https://github.com/Regalis11/Barotrauma/assets/53411693/afda69ec-7e5c-4692-8dc0-ae3a90b1dbb9)
![2](https://github.com/Regalis11/Barotrauma/assets/53411693/c9253013-37c0-451f-aa82-937368f3fd35)

### Reproduction steps

Open subeditor
Place an item and rotate it
Make item assembly from the item
When placing item assembly preview of objects would default to 0 rotation
Once placed items would show with proper angles

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
