### ISSUE TITLE
particles freeze when particle limit decreases

### ISSUE THREAD

**Issue by Fachoj** [Regalis11/Barotrauma#13180]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

particles freeze when the particle limit decreases
![изображение](https://github.com/Regalis11/Barotrauma/assets/95565216/f01af3bd-9141-44d9-bf03-c65c89ce4f47)

### Reproduction steps

shoot gun, weld or etc. and decrease particle count in options

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Fachoj** [comment]
![изображение](https://github.com/Regalis11/Barotrauma/assets/95565216/1cfbe2ea-36dc-4bf2-8937-4bd051bc687d)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/12eab76ff9feda223d73852163cbcb23f00fea40
