### ISSUE TITLE
 useless components on a submarine

### ISSUE THREAD

**Issue by LilPuj** [Regalis11/Barotrauma#13206]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Continuing the topic of useless components on a submarine, I want to show you this piece on the Remora. Yes, these components were here initially and yes, they are not connected to anything, they just exist.
![Снимок экрана (19)](https://github.com/Regalis11/Barotrauma/assets/153860450/de020940-e05d-4ef6-b51a-ae71938f55d8)
![Снимок экрана (20)](https://github.com/Regalis11/Barotrauma/assets/153860450/c1b3c8b3-5920-4e1e-8d8c-c66a79b6eea0)

Sorry that the screenshots are in Russian, but I think you got the gist.

### Reproduction steps

1. Open the editor or start the game
2. Select the Remora submarine
3. Inspect the wiring in the rector
4. under the steel cabinet to the left of the reactor, in the wall, two components
5. Unscrew them and disassemble them :)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I feel like this is similar to https://github.com/Regalis11/Barotrauma/issues/13163 - even though this is most likely unintentional, I don't think this causes any problems. Just a (fun?) little extra thing and a source of free components for those who happen to know about it.

**Comment by LilPuj** [comment]
I was hoping it would be fixed after the rework, but it's still here XD

![Image](https://github.com/user-attachments/assets/e069c9d3-81ce-4206-b446-02c22cbee778)

**Comment by LilPuj** [comment]
And someone definitely noticed it, but decided not to change anything, which makes it even funnier.
