### ISSUE TITLE
Buoyancy calculations seem off w/ docked submarines / shuttles

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#13200]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

With the new 1.2.6 ballast calculations, shuttles still seem to be off.

With 2 docked shuttles, the max ascent speed (0% water in any hulls) was only 17, and descent was 14.

Expected ascent is 19.

Detaching the shuttles had ascent to 19. 

Replacing the shuttles with "docked" version of the sub had descent to 15 (and ascent 19)

Other players have offhandedly reported damped max ascent with docked shuttles.

### Reproduction steps

1. 2 shuttles that are "ballast"
2. go max up/down in test mode. compare speeds to detaching shuttles / installed version

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Ship is Mooncrusher from workshop
 https://steamcommunity.com/sharedfiles/filedetails/?id=2519315532
```

**Comment by Regalis11** [comment]
Thank you for the report! Since it seems like the original issue was never fully fixed, I'll [open the old ticket](https://github.com/Regalis11/Barotrauma/issues/5974) instead to keep the info in one place.
