### ISSUE TITLE
Broken diving suits get swapped when diving

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#13205]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Kind of funny, kind of frustrating. Click on a broken diving suit while salvaging a wreck and you'll put it on, giving you 3 seconds to find your normal suit before you die from pressure. Is this intentional?

### Reproduction steps

`quickstart azimuth`
`enablecheats`
Go to the airlock
`spawnitem "Broken Diving Suit" cursor`
put on a normal diving suit and enter the airlock
cycle the airlock
click on the broken diving suit

Expected: suit is picked up into the hands of the player
Instead the suit is equipped and the player dies

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.6.0 (Winter Update)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eb7a4999413c13db9b9e69888a09a83b3acedda7

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/commit/2f4a16d4bc5f0f9adc460be5186048fdbcaee4c5

Tried to put on broken suit when wearing normal suits, diving mask or exosuit.

No issues found
Closing ticket
