### ISSUE TITLE
Sorting/moving partially broken `huskeggbasic` is annoying

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#13207]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![husk_egg_basic](https://github.com/Regalis11/Barotrauma/assets/99462070/7299e8d9-acfe-43a4-b66d-f065fb96637e)
I know it's been like this for a while and maybe it is intentional, but seriously I wish this gets fixed.
If you still want to keep it, maybe you should add a button to quick combine broken items(if they are combinable) just like that quick stack button or merge this functionality into that button.

### Reproduction steps

1. store a lot of `huskeggbasic` in a container
2. crate some fire or explosions to damage the eggs
3. enjoy sorting/moving these broken eggs one by one

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
It's not just husk eggs

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/993c5d20-cd2f-4856-8f49-366858aa4548)

Fruits still take 50% damage on an explosion (from the fire tick), can't be stacked back together

The simplest solution is to give them all 1 health so there wont partial/damaged fruits. It won't really make a difference if the fruit dies in one second of fire or two

I've also considered changing the mincondition in the recipe and hide the condition of the item itself but the stacking issue persists.

**Comment by pavel4win** [comment]
It is your own fault.
Why you do not keep flammable items in fireproof containers as  "Storage Container" or "Toolbelt".

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/47c92406fb3bdfe7243c76f03cc3a5c7c364776b

> It is your own fault.
> Why do you not keep flammable items in fireproof containers as "Storage Container" or "Toolbelt"?

Arguably yes, but in my opinion this behavior doesn't add anything interesting to the game. It's just an annoyance to deal with these partially broken items. And if the player was expected to store these items in fireproof containers, it should be communicated in some way; it's not at all obvious that items like these need to be protected from fire, when many other items that should logically be flammable don't need to be.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
