### ISSUE TITLE
Talent "Residual Waste" makes it possible to get infinite FPGA circuit

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#13219]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

you can duplicate FPGA circuit with certain talent
![talent](https://github.com/Regalis11/Barotrauma/assets/64390906/95a1caf4-fd5f-4c40-b1cc-bb520aaa2e74)
![fabrication](https://github.com/Regalis11/Barotrauma/assets/64390906/d59d4ace-6f5c-422b-acf0-e2e99b1f51c4)
![deconstruction](https://github.com/Regalis11/Barotrauma/assets/64390906/4bfc80ce-1ca7-4423-8b9e-baef8e7d185d)

### Reproduction steps

1. go to submarine editor
2. load any sub with fabricator and deconstructor
3. increase their fabrication and deconstruction speed for better test
4. givetalent "Residual Waste"
5. repeat fabricating and deconstucting any signal component
6. you will get more and more FPGA circuit

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Thanks for your report, we'll be addressing this by excluding these signal items from the talent

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/82abb11e81a9498b18b2db2c0dc6f76f3efee365 (commit in our private repo)
