### ISSUE TITLE
Incorrect saving of item assembly (wires get misaligned)

### ISSUE THREAD

**Issue by Forch115** [Regalis11/Barotrauma#13216]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you try to save the assembly of an item, upon further use of this assembly the wires end up in a completely different place
![Снимок экрана (543)](https://github.com/Regalis11/Barotrauma/assets/154619147/775d3146-c81a-472f-b27a-751d70ed7822)

### Reproduction steps

1 Open the submarine editor.
2 Place any objects and connect them with wires.
3 Select them and save them as an item assembly.
4 Insert this item assembly.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

 Submarine editor

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by estebanthebad** [comment]
Please prioritize a fix for this bug. This already worked properly in previous versions of the game. And currently it is impossible to create item assemblies with wires without editing the xml in a text editor (and doing a lot of trial and error about what the incorrect offset ist).

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/234f5f10dc2bb642e776fa5b4c37dd41b3493820 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested by using the repro steps of wiring multiple items together and also creating new item assemblies from the existing vanilla ones and the wires are positioned correctly now whem placing down the assemblies. Working correctly, can be merged and closed.
