### ISSUE TITLE
Dedicated server crash when typing into the server console

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1321]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was typing in response to not intending to host using the console as I was not connected. after a couple of messages this crashed the server completely in the servers debugconsole code.

**Steps To Reproduce**
It appears to be caused by entering too many characters into the dedicated server console.

**Version**
0.8.9.6 closed steam alpha Windows 7 64bit.

**Additional information**

![image](https://user-images.githubusercontent.com/29177976/54704113-0f616580-4b32-11e9-970a-02c7f92d8095.png)

Call stack information:
```csharp
 	[External Code]	
>	DedicatedServer.exe!Barotrauma.DebugConsole.RewriteInputToCommandLine(string input = "say I wasnt really actively hosting im trying to fix the campaign up with whats ") Line 195	C#
 	DedicatedServer.exe!Barotrauma.DebugConsole.UpdateCommandLine() Line 166	C#
 	[External Code]	
```

CursorLeft value is 0, input.Length value is 80, console.WindowWidth is also 80.
Input (for the method RewriteInputToCommandLine) was:
"say I wasnt really actively hosting im trying to fix the campaign up with whats "

**Comment by Regalis11** [comment]
Fixed in 2ef3184
