### ISSUE TITLE
The Pressure Stabilizer does not inject automatically if it is inserted into a Auto-Injector Headset.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#13225]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It would be logical for the pressure stabilizer placed in Auto-Injector Headset to auto inject if there is pressure is'nt it?

### Reproduction steps

1. Place pressure stabilizer in Auto-Injector Headset
2. Go out of sub without diving suit
3. Die

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The autoinjector simply injects whatever meds are inside it when your health is low. While I could see it being useful for it to inject the pressure stabilizer in high pressure, I think that raises a lot of new questions: which items should that apply to? Should it inject antidotes when you're poisoned, and if so, how severely poisoned do you need to be? Should it inject calyxanide when you've got a husk infection? Items that improve your damage resistance when you're taking damage? Items that reduce your need for oxygen when you're in a low-oxygen environment, and if so, how low does it need to be?

I think this would easily blow up to the point where the autoinjector needs basically an AI more advanced than what the medic bots have to determine what it should inject and when. And I could easily imagine this making the autoinjector feel unpredictable and harder to use. In my opinion it's better just to keep things simple, and leave it as is.

**Comment by pavel4win** [comment]
Currently, pressure kills instantly if you are under pressure for more than 5 seconds.
Is not it?
In my humble opinion, the mechanism of pressure action needs to be reconsidered. Pressure does not kill instantly, so the standard of living of a person subjected to pressure should decrease, although quickly, but gradually. In this case, the APS inserted into the auto-injector will work normally.
One of the most common reasons for the death of bots (and people) is that they walk around without a diving suit and do not have time to reach it if there is a large hole. Because of this, I always wear a diving suit. If the autoinjector had worked, it would have been possible to walk without a diving suit but with APS in the autoinjector.
A not needed, if the stabilizer is wasted it’s not so bad, but I will stay alive in case of real danger.
Without redesign mechanism of pressure, just make the APS in the auto-injector work if the pressure is life-threatening and lasts more than 3 seconds, it’s not difficult.
Now in the second half of the game we all have to wear a diving suits all the time.
APS in the autoinjector will open up the prospect of wearing different beautiful costumes.

**Comment by pavel4win** [comment]
I add this theme in discussions
https://github.com/Regalis11/Barotrauma/discussions/13239
