### ISSUE TITLE
Empty Broken Diving Suit Spawns with an Autofilled Oxygen Tank

### ISSUE THREAD

**Issue by Arctodites** [Regalis11/Barotrauma#13221]
If you place an empty Broken Diving Suit into a Diving Suit Locker, making sure to deselect 'Auto Fill' in the 'ITEMCONTAINER' panel of the Object Properties editor for both the Broken Diving Suit and the Diving Suit Locker that holds it, the Broken Diving Suit will nevertheless spawn autofilled with an oxygen tank.

Disclaimer: I've only tested this in the sub editor, not an actual game session.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8eff8d49a1eae9b8c023029e0e3b2b8f157d11dd (commit in our private repo)
