### ISSUE TITLE
Failed to properly die after fire damage

### ISSUE THREAD

**Issue by lewri** [Regalis11/Barotrauma#13228]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was fighting ballast flora on the Humpback and accidentally got consumed by fire. When my body fell unconscious and everything faded out I failed to actually die after a minute. Bots would come down to the ballast and do nothing. I disappeared from the crew list but was still not dead.
(Just to note -- I could still click on someone else and change character, but I didn't get any message to say I was dead)

### Reproduction steps

Not sure if it'll be replicable but:
1. Take a flamer, screwdriver, plasma cutter and wear a diving suit.
2. Enter a ballast infected with flora
3. Empty the ballast by manually pumping out the water. After that, disconnect power from the ballast.
4. Use the flamer to destroy the ballast flora, get consumed by fire and fall unconscious.
5. After some time disappear from the crew list but do not die.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No logs generated in game folder
```

**Comment by SomeRandomNoobKekeke** [comment]
cause of death doesn't matter
just enablecheats, kill also works

by "properly die" you mean able to freecam after death? I think this is a multi player only feature
You actually die: you can't be revived, give orders, switch back, so why is this a problem?

**Comment by Regalis11** [comment]
Thank you for the report!

To me it doesn't sound like there's a bug here. The chat message about dying (and chatting with other dead players) is only shown in multiplayer, and you don't switch to the spectator mode in single player.
