### ISSUE TITLE
If you put something into the fabricator/deconstructor at a station, and then save and restore the game, the item disappears.

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#13235]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you put something into the fabricator/deconstructor at a station, and then save and restore the game, the item disappears. 
Is this how it was intended?

### Reproduction steps

Place something into the fabricator/deconstructor at a station, and then save and restore the game.
The item disappears.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug: the changes that happen to the submarine mid-round are never saved when you quit.

**Comment by pavel4win** [comment]
I think if I save the game, then my items should be preserved.
Today I lost 2 PUCS again.
Because the bots abandoned them at the station, and I saved and exit instead of dock off.
What is the point of saving then? If the items left at the station disappear?
