### ISSUE TITLE
Suitable treatments do not get listed if non-limbspecific affliction has leg as indicatorlimb

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#13231]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?
![suitabletreatment](https://github.com/Regalis11/Barotrauma/assets/64390906/da97d3b3-88af-4c53-8e16-54e4ac199374)

![nosuitabletreatment](https://github.com/Regalis11/Barotrauma/assets/64390906/5d575716-ebab-4b81-a64a-f5a3ee6a4d4c)

### Reproduction steps

1. download 
[overrideBloodloss.zip](https://githubfast.com/Regalis11/Barotrauma/files/13771715/overrideBloodloss.zip) and enable local mod legbloodloss which makes bloodloss indicatorlimb="RightLeg"
2. get control of a human character
3. giveaffliction "Blood loss" 50
4. open the health interface
5. look at suitable treatments list

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
