### ISSUE TITLE
Medications that have negative suitability appear in health interface

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#13230]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![notquitesuitable](https://github.com/Regalis11/Barotrauma/assets/64390906/bd178673-1b84-44f0-8909-180966e4c91d)
opium, morphine, fentanyl and tonic liquid are listed as suitable treatments for Opiate Overdose even though they have negative suitability

### Reproduction steps

1. get control of a human character
2. giveaffliction "Opiate overdose" 70
3. open the health interface
4. look at suitable treatments list

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f81d0fd04cf4749a12e6c479324b7b225a57a55
