### ISSUE TITLE
Sub editor: Entity menu disregards selected category

### ISSUE THREAD

**Issue by estebanthebad** [Regalis11/Barotrauma#13252]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sub editor.

In some cases the entity menu filter "ItemAssembly" is not regarded, when the contents of the entity menu are (re)loaded.

The following screenshot shows an active filter for "ItemAssembly" but all the entities are listed in the menu.
![image](https://github.com/Regalis11/Barotrauma/assets/52369117/5a44b4ec-d2d8-471b-828b-e9f13580c8f6)

I observed this bug in the following cases:
* When activating filter "ItemAssembly" then leaving the sub editor, then reentering the sub editor
* When filter "ItemAssembly" is active and an item assembly is created. Then the contents of the entity menu are reloaded but although the filter is still active, all entities are shown, not just item assemblies.

### Reproduction steps

1. Sub editor
2. Select filter "ItemAssembly"
3. Leave sub editor to main menu
4. Enter sub editor. Observed result: Entity menu filter "ItemAssembly" is active but all entities are listed, not just item assemblies.
5. Click filter "ItemAssembly". Observed result: Only item assemblies are listed.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Sub editor

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad6e1505d4a9ae8b402b3a7a3df839657278de81 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4805/commits/ad6e1505d4a9ae8b402b3a7a3df839657278de81

Used steps above.
No issues found with other categories.

Closing ticket
