### ISSUE TITLE
How does one harvest plants (IE. Elastin) in multiplayer - or is this a bug?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1325]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when I reach elastin plants, I can grab them, which displays a progress bar that never actually progresses. it does not have any text stating to use a plasma cutter on it however.

**Steps To Reproduce**
Attempt to gather a plant like elastin.

**Version**
0.8.9.6 closed steam alpha - windows.

**Comment by NilanthAnimosus** [comment]
ah, level resource detach timer is ONLY incremented in the repair tool code, it is not implemented anywhere else - so even if it does not state to require one, it must be gathered with one.

Guess the next time I see a medical plant I am just going to try out my welding tool on it.

the shared code (for server writing of the level resource component) also does not utilize the get/set version of the detach timer variable, if it would ever be negative the server would in fact send a negative value (or attempt to).

I think either grab-based selection should be implemented if it does not need required items, or at least updating the tooltip to require any kind of repair tool item to gather it.

**Comment by Regalis11** [comment]
Fixed in b9574dd
