### ISSUE TITLE
cannot change sprite colour of some items parts in sub editor + sub editor does not save inv/container colour.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1326]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have been setting the sprite colours of some items and objects, and I have found certain items have parts which appear to not react to the sprite colour changes:

- Turrets rotated part does not change sprite colour.
- the inside moving component of doors does not change sprite colour (Only its background part)

- it appears inventory icon colour and container colour do not save at all, they may be modified in the editor but are lost on save or load. - in the source these serializables have the Editable tag but savable = false.

**Version**
0.8.9.6 steam closed alpha

**Comment by Regalis11** [comment]
Fixed in ca279d4
