### ISSUE TITLE
Orca 2 submarine name doesn't appear on purchase in Russian

### ISSUE THREAD

**Issue by DieOrsons** [Regalis11/Barotrauma#13268]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Singleplayer campaign, when buying at an outpost, the Orca 2
![Screenshot_1](https://github.com/Regalis11/Barotrauma/assets/155447308/a3071ff9-ebc6-4897-8f24-d9e0510e118a)
 name does not appear in Russian, instead it is "[submarinename]"

### Reproduction steps

1. Start campaign
2. Buy new sub (choose buy and switch)
3. There is no name of it in text

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/70bde28f159c82ff013a9e2243fd3e68b926e106 (commit in our private repo).
