### ISSUE TITLE
[Modding] Can't load Ragdoll/Animation for variants of variants 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#13271]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When making a variant of a creature, the game doesn't load the original ragdoll/animation of the base creature even when specified.
It always tries to load a ragdoll/animation using the exact creature name from within the mod folder

From what I understand:
1. If not specified, it will try to use ragdoll/animation.xml file using the name of the modded variant creature in default folder (and fail to find it)
2. If specified, it will still look for the vanilla file in vanilla folder?

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/b2c5bde3-a013-4170-8757-a219db1103f9)
Specified path
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/d4025f20-2cc4-4613-b138-20b109c965a2)

Refuses to load the character entirely
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/8597c374-3ccf-4401-a4be-7573ba812885)

### Reproduction steps

1. Make a creature variant of Crawler_hatchling using `variantof="crawler_hatchling"`
2. Delete ragdoll/animation lines
3. Game will be angry

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
Actually this seems to be modded variants in general? 

```xml
<Character inherit="Tigerthresher" speciesname="DE-LairTigerthresher" pathfinderpriority="1" usepathfinding="True">
  <ragdolls folder="Content/Characters/Bonethresher/Ragdolls/" />
  <animations folder="Content/Characters/Bonethresher/Animations/" />
  <ai targetinnerwalls="False" targetouterwalls="false">
    <target tag="decoy" state="Attack" priority="100" ignoreifnotinsamesub="True" />
    <target tag="provocative" state="Attack" priority="100" ignoreifnotinsamesub="True"/>
    <target tag="weapon" state="Attack" priority="100" ignoreifnotinsamesub="True"/>
    <target tag="tool" state="Aggressive" priority="50" reactdistance="1000" attackdistance="0" timer="0" ignorecontained="False" ignoreifnotinsamesub="True"/>
    <target tag="human" state="Attack" priority="60" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" ignoreifnotinsamesub="True"/>
    <target tag="weaker" state="Attack" priority="50" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="equal" state="Attack" priority="50" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="stronger" state="Aggressive" priority="50" reactdistance="2000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="leucocyte" state="Avoid" priority="50" reactdistance="1000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="dead" state="Eat" priority="20" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="bonethresher" state="Protect" priority="2" reactdistance="1000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="turret" state="Attack" priority="1" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" ignoreinside="true"/>
    <target tag="watcher" state="Protect" priority="1" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" ignoreinside="true"/>
    <target tag="monsterfood" state="Eat" priority="1" />
    <target tag="terminalcell" state="Idle" priority="0" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" />
    <SwarmBehavior mindistfromclosest="400" maxdistfromcenter="2000" cohesion="0.5" />
  </ai>
</Character>
```

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/04e2fe56-ca0a-4449-9459-ef6ed6e80f09)

**Comment by ubertpendragon** [comment]
I think that's mostly the error message being annoying; if the variant doesn't modify the ragdoll or animation (and therefore doesnt need to contain the file), an error will be thrown and use default anyway

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/2408c2c8-a910-422b-a9be-45585d9c3149)


```xml
<Character inherit="Bonethresher" speciesname="DE-LairBonethresher" pathfinderpriority="1" usepathfinding="True">
  <ragdolls folder="Content/Characters/Bonethresher/Ragdolls/" />
  <animations folder="Content/Characters/Bonethresher/Animations/" />
  <ai targetinnerwalls="False" targetouterwalls="false">
    <target tag="decoy" state="Attack" priority="100" ignoreifnotinsamesub="True" />
    <target tag="provocative" state="Attack" priority="100" ignoreifnotinsamesub="True"/>
    <target tag="weapon" state="Attack" priority="100" ignoreifnotinsamesub="True"/>
    <target tag="stronger" state="Aggressive" priority="80" reactdistance="2000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="equal" state="Aggressive" priority="80" reactdistance="2000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="leucocyte" state="Avoid" priority="50" reactdistance="1000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="human" state="Aggressive" priority="50" reactdistance="1000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="tool" state="Aggressive" priority="30" reactdistance="1000" attackdistance="0" timer="0" ignorecontained="False" ignoreifnotinsamesub="True"/>
    <target tag="weaker" state="Aggressive" priority="10" reactdistance="2000" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="terminalcell" state="Idle" priority="1" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" />
    <target tag="watcher" state="Protect" priority="1" reactdistance="0" attackdistance="0" timer="0" ignorecontained="False" />
    <SwarmBehavior mindistfromclosest="400" maxdistfromcenter="2000" cohesion="0.25" />
  </ai>
</Character>
```

**Comment by ubertpendragon** [comment]
Note that straight up variants don't need ragdoll or animation specified. 
In both cases we tried a simple override for these variants to use pathfinding.

This works: 

```xml
<Character inherit="Bonethresher" speciesname="DE-LairBonethresher" pathfinderpriority="1" usepathfinding="True">
  <ai targetinnerwalls="False" targetouterwalls="false">
    <target tag="decoy" state="Attack" priority="100" ignoreifnotinsamesub="True" />
    <target tag="provocative" state="Attack" priority="100" ignoreifnotinsamesub="True"/>
  </ai>
</Character>
```

This sends an error:

```xml
<Charactervariant inherit="Crawler_hatchling" speciesname="DE-LairCrawler_hatchling" speciestranslationoverride="Crawler" >
  <ai combatstrength="50" targetinnerwalls="False" targetouterwalls="false">
    <target tag="DE-Lairbroodmother" state="Protect" priority="10" reactdistance="500" ignoreinside="true" />
    <target tag="DE-LairCrawler_large" state="Protect" priority="5" reactdistance="500" ignoreinside="true" />
    <target tag="DE-LairCrawler" state="Protect" priority="2" reactdistance="500" ignoreinside="true" />
  </ai>
  <inventory />
</Charactervariant>
```

**Comment by NilanthAnimosus** [comment]
Tested against release/spring-update commit https://github.com/FakeFishGames/Barotrauma-development/commit/92aefbc12d1c1df5c104c4f7385d4600c6082aea

The issue here seems to be on the creation of a none humanoid (that is anything through the fishanimcontroller) it does not pass along any filename, only the characters species (So defining it manually will not work at all here) - FishRagdollParams.cs line 25.

As a further potential issue, It will check if the prefab to spawn has a variant of, then switch the ragdoll/animation species to that variant - however it does not check if that has a variant to check either (And which actually has ragdolls/animations) in RagdollParams.cs line 151. - Once it fails to find a file it attempts the default file, which checks based on the content package the character is in, which still doesn't exist in the case of most variants usually.

The logic essentially needs looking at (both perhaps to pass alone custom ragdoll/animation paths, and the logic related to checking variants if they have derived something else like a recursive check until a ragdoll/animation is found unless an explicit path is given.

Mod used to test (probably not correct, in debug will crash):
[aaaTestVariantVariant.zip](https://github.com/FakeFishGames/Barotrauma/files/14239566/aaaTestVariantVariant.zip)

**Comment by itchyOwl** [comment]
Fixed in FakeFishGames/Barotrauma-development@b73c74f. Note that variants of variants is not really a supported feature. There might be some other issues too. And variants of variants of variants will definitely not work.

**Comment by NilanthAnimosus** [comment]
Full description of the fix for you: Add support for loading animations and ragdolls for variants of variants. Addresses https://github.com/FakeFishGames/Barotrauma/issues/13271. Also allow defining the ragdoll by path, which means it's no longer required for the ragdolls to conform to the default naming convention. They can also be located outside of the Ragdoll folder now.

It should be possible to define it yourself, or have it get the base character's species for the ragdoll's/animations. it has yet to be tested so its not in the next version yet though.

**Comment by itchyOwl** [comment]
> And variants of variants of variants will definitely not work.

Previously there was only support for variants, not variants of variants (grandparents). I added some support for it here and couldn't spot any issues, but there might be some still. If it's trivial to fix, we can do that but it's not something that I'd use much resources on. Deeper variance inheritance than that will not currently work, because the methods of checking the parents are not recursive.

**Comment by itchyOwl** [comment]
And in practice you should now be able to do this:

`<ragdoll path="Content/Characters/Mudraptor/Ragdolls/MudraptorDefaultRagdoll.xml"/>`
or
`<ragdolls folder="Content/Characters/Mudraptor/Ragdolls/"/>`

and:    
`<animations folder="%ModDir%/Animations/"/>`
or:
`<animations folder="Content/Characters/Crawler/Animations/"/>`

**Comment by Jasontti** [comment]
Tried to test this as part of: https://github.com/FakeFishGames/Barotrauma-development/pull/4930

Test mods seems to error out still, maybe @NilanthAnimosus could take another look?

```
Failed to spawn the character "True_Mudraptor_veteran". {[RagdollParams] Failed to load ragdoll True_mudraptor_veteran Default Ragdoll from LocalMods/aaaTestVariantVariant/True_Mudraptor_veteran/Ragdolls/True_mudraptor_veteranDefaultRagdoll.xml for the character True_Mudraptor_veteran.}
   at Barotrauma.RagdollParams.GetRagdollParams[T](Identifier speciesName, Either`2 file) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 254
   at Barotrauma.RagdollParams.GetDefaultRagdollParams[T](Identifier speciesName, XElement characterRootElement) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 163
   at Barotrauma.RagdollParams.GetDefaultRagdollParams[T](Identifier speciesName, CharacterParams characterParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 135
   at Barotrauma.RagdollParams.GetDefaultRagdollParams[T](Character character) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 130
   at Barotrauma.FishRagdollParams.GetDefaultRagdollParams(Character character) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 24
   at Barotrauma.FishAnimController.get_FishRagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/FishAnimController.cs:line 25
   at Barotrauma.FishAnimController.get_RagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/FishAnimController.cs:line 14
   at Barotrauma.Ragdoll..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 461
   at Barotrauma.AnimController..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/AnimController.cs:line 225
   at Barotrauma.FishAnimController..ctor(Character character, String seed, FishRagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/FishAnimController.cs:line 134
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1464
   at Barotrauma.AICharacter..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isNetworkPlayer, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AICharacter.cs:line 15
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1256
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean throwErrorIfNotFound, Boolean spawnInitialItems) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1248
   at Barotrauma.CharacterEditor.CharacterEditorScreen.SpawnCharacter(Identifier speciesName, RagdollParams ragdoll) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/CharacterEditor/CharacterEditorScreen.cs:line 1554
   at Barotrauma.CharacterEditor.CharacterEditorScreen.<CreateCharacterSelectionPanel>b__179_0(GUIComponent component, Object data) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/CharacterEditor/CharacterEditorScreen.cs:line 2728
```

**Comment by itchyOwl** [comment]
> Deeper variance inheritance than that will not currently work, because the methods of checking the parents are not recursive.

This is outdated. It's recursive now.
