### ISSUE TITLE
[Unstable] Entering Eye of Europa crashes the game, failing to load Portal Guardian ragdoll

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#13274]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I crashed after loading the Eye of Europa level for the first time and now I cannot finish the campaign.
Singleplayer, no mods etc. 
Here's the log:
[crashreport (22).log](https://github.com/Regalis11/Barotrauma/files/13850619/crashreport.22.log)
Here's the save:
[Save 17.zip](https://github.com/Regalis11/Barotrauma/files/13850620/Save.17.zip)

### Reproduction steps

1. Load the save, it should crash immediately

or

1. Start a new campaign
2. Togglecampaignteleport and debugdraw, teleport to second-to-last node
3. Select eye of europa as destination, embark from the outpost
4. Witness the crash

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

very-unstable-unstable-dec23

### Which operating system did you encounter this bug on?

Windows

**Comment by Udrakan** [comment]
Loading portal guardian in character editor pointed me to this error in the character's ragdoll
![image](https://github.com/Regalis11/Barotrauma/assets/59519434/d127eeb7-cc41-4535-bad8-b9d29b4c818c)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad1ad41165d3de55c2ebceb89caaee68fcb491b3
