### ISSUE TITLE
server crash when changing gamemode during/after round start.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1327]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have no idea who did it, but since they did now I get to report it!

the game crashed with map = null in shared campaignmode.cs where it should never be null normally, I don't know how this was achieved nor if its even reproducable because my server is currently in active running (And the players demand their restarts lol) which also gives me little time to log too much useful information.

**Steps To Reproduce**
Unknown but it looks like the gamemode changed from campaign -> mission, while the campaign was still checking 

**Version**
0.8.9.6 closed steam alpha (None-beta branch) - windows.

**Additional information**
Server had crashed in the following location:
shared->campaignmode.cs -> public override Mission Mission()
Crashed on return Map.CurrentLocation?.SelectedMission;
Map was null.

serverconsole shows evidence of changing gamemode, perhaps during the round even (This is just a picture of the now-frozen console btw):
![image](https://user-images.githubusercontent.com/29177976/54781083-4491b480-4c13-11e9-900d-50e004291220.png)

stacktrace:
```csharp
>	DedicatedServer.exe!Barotrauma.CampaignMode.Mission.get() Line 33	C#
 	DedicatedServer.exe!Barotrauma.Networking.GameServer.StartGame(Barotrauma.Submarine selectedSub = {Barotrauma.Submarine}, Barotrauma.Submarine selectedShuttle = {Barotrauma.Submarine}, bool usingShuttle = true, Barotrauma.GameModePreset selectedMode = {Barotrauma.GameModePreset}) Line 1628	C#
 	DedicatedServer.exe!Barotrauma.CoroutineManager.IsDone(Barotrauma.CoroutineHandle handle = {Barotrauma.CoroutineHandle}) Line 159	C#
 	DedicatedServer.exe!Barotrauma.CoroutineManager.Update(float unscaledDeltaTime = 0.0166666675, float deltaTime = 0.0166666675) Line 191	C#
 	DedicatedServer.exe!Barotrauma.GameMain.Run() Line 264	C#
 	DedicatedServer.exe!Barotrauma.Program.Main(string[] args = {string[0]}) Line 36	C#
```

**Comment by Regalis11** [comment]
Should be fixed now
