### ISSUE TITLE
Electrical discharge coil power draw is always active and not relevent for activation

### ISSUE THREAD

**Issue by ChaosRifle** [Regalis11/Barotrauma#13284]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when hooking up an EDC (electric discharge coil) to a supercap, the power draw is permanently on, even when sent a nil or 0 Trigger signal. This draws the full power draw permanently, at all times. Sending the trigger signal does not actually require the power to fire the device, and instead fires it even with no energy remaining in capacitors.

### Reproduction steps

open editor
place reactor setup
connect EDC to power

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Editor

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
[works fine for me](https://steamcommunity.com/sharedfiles/filedetails/?id=3135382916)
draws power only when you press the button
triggers only when there's enough power

default eds have "Min voltage" 0.5 so i guess it can strike even when there's 0.5 of required power

**Comment by ChaosRifle** [comment]
I think you are correct on a specific setup causing it, as I can not fully get it to reproduce today, as yesterday I had an entirely different setup for power delivery.

I can get the power drain aspect to happen by hooking up the EDC through a relay, but am unable to reproduce any other aspect of it at this time.

For now, I will close the report and if I encounter this (or other bugs in future) I will be sure to include a sub file with the report, as not to loose it in the future.
