### ISSUE TITLE
Can move without fuel in Funbringer 3000 with speed buffs

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#13289]
### What happened?

Same issue as #10769, and was also mentioned in the comments #11369 but was not fixed.

### Reproduction steps

1. Wear FB3k without fuel rod
2. Take a dose of meth
3. Observe that movement is possible

### Version

Stable (v1.2.7.0)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6b8e9259fcee132b5b53c42ea7442ca7948e7041
