### ISSUE TITLE
it would be nice if we could select, edit and recolour/rename the visible connection of wires

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1329]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I know I am fairly insane for suggesting it, but when one has been going through a submarine recolouring items and modifying the generalized items and structure ripping out every wire or going through the submarines XML to edit said wires is by far more insane.

I feel there should be a way to select wires, despite them being actively connected. and modify them individually - such as being able to set their colour.

**Comment by Regalis11** [comment]
Fixed in 6fd4d14
