### ISSUE TITLE
Incorrect display of text in the Logbook in Russian

### ISSUE THREAD

**Issue by DieOrsons** [Regalis11/Barotrauma#13296]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On the mission with the Wrecked Dugong you need to find 2 Logbook, they both seem to be incorrectly displayed. In the first one the text is repeated 15 times in English, only 16 text in Russian. I don't know if the second Logbook is supposed to look like this, but it looks like a bug or something.

### Reproduction steps

1. Start singlplayer campaign
2. Start Wrecked Dugong mission 
3. Go find some Logbooks
4. They displayed incorrectly
![Screenshot_1](https://github.com/Regalis11/Barotrauma/assets/155447308/c8d0dd9c-a507-4e7c-ba4f-9832c00eb107)
![Screenshot_2](https://github.com/Regalis11/Barotrauma/assets/155447308/db588dd4-ea56-4eff-bc18-0732d314ed03)
![Screenshot_3](https://github.com/Regalis11/Barotrauma/assets/155447308/750ca096-1900-423f-90b1-33966e6bb3ab)

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf666b8ac51cc52a07c87e67b1bc5f92015bcb92
