### ISSUE TITLE
Husk infection + ABX, tonic liquid doesn't provide healing bonus anymore.

### ISSUE THREAD

**Issue by IrLED** [Regalis11/Barotrauma#13308]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Maybe it's intended design because here is no such buff as "Husk -30", only "Husk infection resistance" (which is meh buff)
Anyway until recently it was possible to cure husk infection up to 74% (before terminal stage) with 1x Tonic liquid + 2x ABX
Now presence of "Slow metabolism" does nothing regarding curing husk infection.

### Reproduction steps

1. Summon bot/use partner player
2. Infect the subject, wait till chosen infection level (e.g. 60%)
3. Apply ABX at 60%
4. Observe (with Health HUD) the infection declining until it stops declining. 60% - X% = Y%. Where Y% is the curing power of the single ABX shot.

5. repeat steps 1-3 but with Tonic liquid applied before 60% (e.g. at 55%)
6. repeat step 4. You will have almost the same curing power Y%(+/-1%) as in step 4. Presence of "slow metabolism" does nothing for curing power

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This does not seem like a bug to me. Tonic liquid increases the duration of buffs, so I don't see why it should make ABX better at healing the husk infection.
