### ISSUE TITLE
Separatist Typhon 2 airlock has no interlocking

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#13304]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It just floods their ship

![typhon](https://github.com/Regalis11/Barotrauma/assets/68995233/32a58585-3824-4d0c-97a9-79dbeb6484dc)

### Reproduction steps

Observe a separatist Typhon 2 while spectating

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Unable to reproduce in the editor

**Comment by mygamingaccount** [comment]
Is the signal network running at all on the pirate subs? Must be otherwise they'd be stranded, I think!

**Comment by Regalis11** [comment]
Thank you for the report!

I gave this a quick test but unfortunately couldn't find a way to get it to occur. The airlock circuit seems to work as expected.

https://github.com/Regalis11/Barotrauma/assets/14351070/c7e9ef6c-b14b-4856-9d30-c34dc67cb5e8

https://github.com/Regalis11/Barotrauma/assets/14351070/1ddd7514-a081-497d-93b9-22fddc3fdb10

**Comment by mygamingaccount** [comment]
I could not reproduce it either.
The ship was being attacked by a hammerhead. The airlock door was being repaired but it was not broken when I noticed that both sides were open.

I'll just close this ticket until I can somehow reproduce it, or if it appears again.
