### ISSUE TITLE
Submarine stuck between a beacon station and a rock

### ISSUE THREAD

**Issue by Makiatto** [Regalis11/Barotrauma#13307]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After a Thrasher/Spineling attack, my Humpback sank all the way down into a beacon station, and got stuck between it and a rock. It was a hydroelectric power beacon station, going up with the submarine didn't move it at all. It seemed it was the beacon's antenna that stopped it from going up, the beacon's wall and the rock only stopped it from leaving sideways.

### Reproduction steps

1. Lodge a humpback between a beacon station antenna and a wall on the back
2. The submarine will be completely stuck aside from restarting/ console commands

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! Seems likely to be the same issue as https://github.com/Regalis11/Barotrauma/issues/10257
