### ISSUE TITLE
Paralysis Resistance works differently between normal paralysis and slow paralysis

### ISSUE THREAD

**Issue by A2ur3** [Regalis11/Barotrauma#13303]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

you need more Paralysis Resistance to completely cure slow paralysis compared to normal paralysis
this makes one anaparalyzant unable to cure 100% slow paralysis, if character has enough bonus max hp (from talent or talent affliction)

### Reproduction steps

1. find a human character with 100 max hp
2. giveaffliction "paralysis" 100 and "paralysis resistance" 400 then observe
3. giveaffliction "slowparalysis" 100 and "paralysis resistance" 400 then observe

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Even though this is unintentional, to me it doesn't seem like it causes any clear issues. In my opinion it doesn't seem like a problem that you may need a bigger dose to heal a 100% severity affliction on a character with higher-than-normal health.
