### ISSUE TITLE
Sorting/moving partially broken fruits is annoying

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#13314]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![292288087-993c5d20-cd2f-4856-8f49-366858aa4548](https://github.com/Regalis11/Barotrauma/assets/73229309/124df179-c70c-430f-a0b8-9d7a58ae4826)

I know it's been like this for a while and maybe it is intentional, but seriously I wish this gets fixed.
If you still want to keep it, maybe you should add a button to quick combine broken items(if they are combinable) just like that quick stack button or merge this functionality into that button.

### Reproduction steps

1.    store a lot of `creepingorange` in a container
2.    crate some fire or explosions to damage the fruits
3.    enjoy sorting/moving these broken fruits one by one

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by ubertpendragon** [comment]
https://github.com/Regalis11/Barotrauma/issues/13207

**Comment by Regalis11** [comment]
Should be fixed now (https://github.com/Regalis11/Barotrauma-development/pull/4864)
