### ISSUE TITLE
[Suggestion] instead of saying "this is still in the development" when player reaches the centre say "good job, the prize is the friends you made along the way"

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1331]

**Comment by thegrb93** [comment]
Have it say that if you complete every mission

**Comment by CommanderMark** [comment]
Maybe the friendship was the friends we ma-

**Comment by hubismal** [comment]
did you seriously turn my discord comment into a real feature request lmao

**Comment by etet2** [comment]
yes

**Comment by Regalis11** [comment]
Actually at the moment it's not even possible to reach the center - there's no connections leading to the location at the center, and it's basically just a button that creates the popup. :smile:
