### ISSUE TITLE
Issues with linux campaign hosting

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1332]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Linux servers cannot seem to host campaign games at all as none of the submarines can be found when chosen - there may be a problem with the capitalization of the files after the server has communicated the submarine lists to the client somewhere then sends it back somewhere if I had to hazard a guess to this problem since even the vanilla submarines are not found.

**Version**
0.8.9.7 steam closed alpha - linux server (I was not host / client mind you)

**Comment by NilanthAnimosus** [comment]
thought I saw an issue and went to test it again moments ago to find it was probably just me having a brainfart or something, so don't mind the edited title.

**Comment by Regalis11** [comment]
Fixed in c3b5c41
