### ISSUE TITLE
[Unstable] Infinite oxygenite tank speed buff for characters who don't need to breathe

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#13324]
### What happened?

Characters who have 100% thresher genes or husk do not consume oxygenite tanks, leading to an infinite duration speed boost. Does not occur in diving masks, which do not give any speed boost if the character isn't breathing (which makes sense - if they're not breathing then they shouldn't receive the effects of oxygenite).

### Reproduction steps

1. Give a character 100% thresher genes
2. wear a diving mask with oxygenite tank and observe no speed buff
3. wear a diving suit with oxygenite tank and observe infinite speed buff

### Version

v1.2.9.0 (unstable)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4874/commits/9a0500d27718c119142a72178cab988ac7b79982

Tested with tresher genes, husk symbioisis and normal characters
Normal, abyss, combat diving suits and PUCS

No issues found
Closing ticket
