### ISSUE TITLE
welding fuel not being consumed correctly?

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#13328]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I managed to kill 3 outpost security with a single welding fuel tank by putting it on their mask while cuffed, and it still had over 80% fuel left, so with 1 tank you can deal around 10.000  total damage to people by draining oxygen which seems excessive

### Reproduction steps

put a welding fuel tank on a diving mask and put that mask on someone

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.2.9.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I don't think it really makes much sense comparing the "kills per mark" in this case. With welding fuel tanks, the cost of the item is not what restricts you from killing people with it (there's practically always enough tanks in the sub to kill the whole crew many times over).

**Comment by LePiromano** [comment]
i guess i care about cost efficiency too much, in reality killing security npcs with welding fuel wouldn't really even be posible without stun grenades which are another issue i'll make a ticket about in a minute
