### ISSUE TITLE
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#13329]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I don't know why the game crashed. 
I sent to you the game save files and crash report.

[20240120.zip](https://github.com/Regalis11/Barotrauma/files/13999131/20240120.zip)

[crashreport (37).log](https://github.com/Regalis11/Barotrauma/files/13999129/crashreport.37.log)

### Reproduction steps

I don't know the steps of reproduction. 
At the moment of crash I was using an external camera of my orca boat.
I found a similar error just once in
https://github.com/Regalis11/Barotrauma/issues/1817
it was corrected in 2019.

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by SomeRandomNoobKekeke** [comment]
This happened to me when Thalamid rammed my sub
That's why i don't play with Barotraumatic
![barodev small](https://github.com/Regalis11/Barotrauma/assets/122838333/14120c35-b62a-457f-9a0f-a20c5d95a3be)

**Comment by Regalis11** [comment]
Thank you for the report!

There does not seem to be anything on that line that could be throwing an exception in the vanilla game, and you seem to be using mods that modify the source code, so it seems likely this is caused by some of those.
