### ISSUE TITLE
Supreme Feature Request: Clowns play Entrance of the Gladiator on instruments

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1333]
I'm almost tempted to report this as a bug because it's such a fundamental idea for a clown that's not in the game: People dressed in clown outfits should play the main part of Entrance of the Gladiators (aka circus theme) on instruments.
[Here's the song](https://www.youtube.com/watch?v=zjedLeVGcfE&t=11s)
The song is easily public domain by now, no copyright issues but you might wanna credit it anyway if you do implement it.

It's just such a shitty clown thing to do. It fits the clown perfectly.

**Comment by NilanthAnimosus** [comment]
I'd love it if we could get a guitar-instrumental equivalent to this, one that is legal to use. the song is royalty free but I don't know/think that works for peoples recreations of said music. but this would still be nice to have if one is wearing clown items : >

I also know this is perfectly possible without any code using tags and conditional logic to perhaps achieve. I'm no lawyer or even game designer, so I don't know anything of the laws on it all - it would however be well fitting to the atmosphere even if it was a guitar-tune.

**Comment by Regalis11** [comment]
:clown_face: c244b33

**Comment by hubismal** [comment]
The absolute madman/madmen.
