### ISSUE TITLE
Talking to NPCs keybind can not be set.

### ISSUE THREAD

**Issue by Archoran** [Regalis11/Barotrauma#13331]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Well, like the title says - the keybind of interacting with doors, objects and NPCs does not work for NPCs anymore. It also can't be set individually, it just defaults to left mouse button. This isn't really a bug which leads to a crash or sth but it can get kind of annoying if you are used to other controls.

### Reproduction steps

(1. Default your keybinds)
2. Set every key that is Left Mouse to an other key
3. See that the key for Trading or Talking/Examining NPCs is still Left Mouse

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Client-side issue

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not find a way to reproduce this. The default key to interact with NPCs is E (the "Use" keybind), and switching the keybind seems to work with no issues. Are you using some kind of mods?

**Comment by Archoran** [comment]
I had this issue without any mods. I think I have found the issue. The game does not load keybinds after loading the save so I was confused about the keybinds did not change. So I think the issue can be closed with a [feature request] to dynamically load keybinds in-game if changed, but that's a minor thing.

**Comment by Regalis11** [comment]
That should not be the case, the keybinds should take effect immediately. When I tested it, it seemed to work correctly. The only issue was that the hovering text next to the NPC didn't update, which we have an existing bug report about: https://github.com/Regalis11/Barotrauma/issues/13169
