### ISSUE TITLE
Minor request on skill syncing

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1335]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is not really a bug but a request in regards to skill syncing logic.

Modifying information server-side (Which I know is not intended, but I've always liked to be able to do this without requiring the distribution of modified files as no mechanism exists for this and some things are normally fine to do this with)

one thing that does not handle this well is skills, the skills can be modified and it does work fine, but until the first skill increase is made the skills are received by the client in the wrong order at round start which does not correct itself until after said first gains. 

IE. on the server-side I give the assistant a different set of skills, with a decent weapons, medical and helm skill, like a second captain but more focused towards medical, with a very low (around 5) mechanic/engineering skill since those skills are almost too easy to earn and I want them to be without such for as long as possible.

Initially, it will say they have instead of 35 medical, 35 engineering or mechanical - because they seem to order the received skills differently. once it increases it says something silly (IE. gained 1000XP+" and skips straight to the correct level, so it corrects-itself on any gains.

The syncing logic on skillgain uses its string identifier, but the skills on the clientside are sorted by skilllevel that they estimate first, it would be nice if on receive/send they were sorted by identifiername.

In theory, this could effect the vanilla game as well, but is very unlikely unless two ranges intersect resulting in potential different orders on the client/server side, but I don't think any job has intersecting ranges by default.

**Comment by Regalis11** [comment]
Implemented in 11f2bf4
