### ISSUE TITLE
Feature Request: Character on ladders should autograb onto vertical ladders

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1337]
As it is right now, many new players of the closed alpha are very confused as the two docking ladders require you to press E again to get onto the upper ladder. It would be extremely helpful to everyone to just make adjacent ladders get autoclimbed onto when the player reaches the top or bottom of the current ladder.

**Comment by Regalis11** [comment]
Fixed in c3b5c41
