### ISSUE TITLE
Suggestion to math on repairable skillgains

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1338]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Warning - this feature suggestion contains a lot of -math-

**Description**
In the current code, skillgain for repairables is entirely based on your current skill, with no regard to how easy or difficult something is to repair or how long it takes due to being over the skill.

***Small sidenote to point out first***
~~I'll be the first to say as a sidenote however as this feels almost buglike or perplexing to me, fixduration makes zero sense code wise and even less sense XML wise (if I wanted my repair to be between 10 seconds to 120 what values to use?, 10 divided by maxcondition would be 10 per second, yet 10 / 100 = 0.1. while 5 / 100 = 0.05, dividing 0.05 by 0.02 of a second is 2.5 condition added and doing this for 0.1 is 5, I cant make sense of this math at all. will test/edit later.~~

~~Ok, junction box has an XML defined fixdurationlowskill of 10f, yet in the game code its 100f - its default value if it is not present. the XML values appear to maybe be ignored.~~

The game does not appear to be reading fixdurationlowskill or fixdurationhighskill - their capitalized in the XML and not capitalized in the game code if that makes a difference, items have values like 5 - 20 and 5 - 10 though, so if it was reading them everything would be fixed rediculously fast, as it currently stands though they are not set at all in vanilla.

[With the XML loading fixed](https://i.gyazo.com/470a5cc80a5e82e82a3211eb407eb803.mp4)

```csharp
            float fixDuration = MathHelper.Lerp(fixDurationLowSkill, fixDurationHighSkill, successFactor);
            if (fixDuration <= 0.0f)
            {
                item.Condition = item.MaxCondition;
            }
            else
            {
                item.Condition += deltaTime / (fixDuration / item.MaxCondition);
            }
```

***Ok so onto the feature suggestion on changing repairable skillgains***

By default if you have 40 skill, it is dividing the gains by 40, if you have 80 skill, it divides it by 80. Say your fixing electricals, it is twice as fast at 20 skill than 40 skill, regardless if your above or below the target object or even how long it takes to repair.

If you have above skill, that severely diminishes the time (IE. 1-2 minutes to 5-10 seconds = immensely fractional gains). this also means once you hit 40 electrical, it is nearly impossible to raise because of how fractional a time you repair for - it also means 1 - 40 is fast no matter how far off you are and almost too easy to gain.

I made changes to the repair skillgain rate for repairable.cs, I was going to go through and over the other aspects. This is the math I came up with so far and still needs balancing but the math is more or less fine:

```csharp
            float successFactor = requiredSkills.Count == 0 ? 1.0f : 0.0f;
            foreach (Skill skill in requiredSkills)
            {
                if (CurrentFixer.GetSkillLevel(skill.Identifier) >= skill.Level) successFactor += 1.0f / requiredSkills.Count;
            }
            foreach (Skill skill in requiredSkills)
            {
                //Default divider of gains, lower values are faster.
                float skillgaindivider = 20f;

                //Difference in character skill
                float skilldifference = CurrentFixer.GetSkillLevel(skill.Identifier) - skill.Level;

                //It is too easy to repair now, decrease the speed by the difference in skill
                if (skilldifference > 10f) skillgaindivider = skillgaindivider * (skilldifference / 4f);

                //It is too difficult to repair, decrease the speed of gains by the difference in skill
                if (skilldifference < -10f) skillgaindivider = skillgaindivider * (-skilldifference / 10f);

                //This will be repaired very fast that almost no gain would be had, so decrease the divider
                //by up to 3/4, so shorter repairs are still worth something decent unless too easy.
                skillgaindivider = skillgaindivider - ((0.75f * skillgaindivider) * ((1f - (fixDurationHighSkill / fixDurationLowSkill)) * successFactor));

                CurrentFixer.Info.IncreaseSkillLevel(skill.Identifier,
                    SkillIncreaseMultiplier * deltaTime / skillgaindivider,
                     CurrentFixer.WorldPosition + Vector2.UnitY * 100.0f);
            }
```

The idea of the above math is simple, using a base divider for the skillgain (Which can be adjusted much like a server/single/XML mod setting), certain conditions being met modify it.

If your within 10 points above/below a repair requirement, it is as if you have 20 skill in the current version and is fairly fast to earn it.

Lets take a battery (40 skill, with a 20 lowfixduration and a 5 highfixduration) as an example.

if you go below a 10 skill difference - then every 10 points below will multiply the divider by an extra 1, so at 20 skill for a 40 required object is (20/10) = 2, so divider of 20 + divider * 2 for a divider of 40.

conversely, if your trying to earn skill by doing something you are already good at, the difference is every 4 points adds to the divider a multiplication of 1 (0.40 every point of difference). if repairing 40 device and you have 60 skill, this is equal to a divider of 20 * 5 aka 100, 5 times the effort from standard. this divider is greatly reduced by speed.

Finally if you are very fast at repairing, you gain up to 3/4th's decrease on the divider, so quick to repair objects give most of the gain it would have if it was an extremely slow repair, making them still worth doing to get the gain - though the reduction is smaller the less difference in time (the complexity difference) and essentially equivalent to the speed. 5/20 would be 0.25 the time, so were reducing by 0.75, we take 75% of this reduction multiplied by the skill divider and subtract it to reduce it due to the fast repair speed.

for that 60 skill example (for a 40 object), it would yield a 100 divider - then reduce it by 56.25 to a final divider of 43.75, if you had 70 skill this would be a 150 divider, reduced to 65.625. Scaling very fast as it increases, 90 would be 109.375.

This all of course is easy enough to balance out and my values are not exactly truely balanced. a divider of 100 is equal to the current skill gain at maximum skill (100). the closer you are to the requirement the faster the gain, the further removed the more exponentially slower it gets, with it less exponential if your below but far more exponential if above.

If you want to give it all a test using just the refresh key, I've prepared a link to a c# testing site:
[Link to test the code quickly](https://dotnetfiddle.net/mvp5b3)

**Comment by Regalis11** [comment]
The fixduration value issue was fixed in 27917ee, but the we haven't done anything to the skill gain logic yet. Your suggestion seems very good though, I'll put it to a test soon!

**Comment by NilanthAnimosus** [comment]
alright, I included a link to work out the divider and its effects on skill gain per second, just enter some values and refresh the page and it'l show you the results. as a note, 50 in the divider is equal to 50 skill gains in the current version, but it does sort of equal more skill instead of less due to the fact the fix duration were so disparate.

But almost every item in the XMLs is a 5,20. so i'm not sure their balanced to begin with as timers - now everything without skill honestly feels too fast to repair - I know as I tried it myself yesterday but it felt an important note to make regardless to the fixduration issue.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
