### ISSUE TITLE
merge issues with 1473f77...ece6ead in the public repo 

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1339]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The latest code does not compile in debug, and I have been having various connection issues on my server code and I am not sure I am 100% using the same code anymore as the private repo as I cannot properly confirm its integrity, though i'm not sure if those connection issues are due to any edits I've made, I believe nothing I've changed effects anything to change networking personally.

The thing that tipped this off was discovering the latest code doesn't compile, due to lines added in client's debugconsole.cs. rokvach sent me a copy and it was indeed just the 2 extra lines, but this problem could be somewhere more serious and I'd have no way to spot it if it actually compiles and runs fine (IE. event logic).

since I have had players on join have level equality check failiures, entities not exist, and other issues, I cannot properly debug/distinguish if these issues are caused by merge problems or vanilla. it appears to possibly be vanilla, but in other cases it could have been my network such as mass disconnects I've been having that are not the above issues (and don't have anything other than a timed out).

what is certain is that merge conflicts can and will occur when using the scripts to sync the private repo to the public repo.

**Version**
0.8.9.6 steam closed alpha - windows 7 64bit.

**Additional information**
![](https://cdn.discordapp.com/attachments/540532000860143616/559166293790425135/unknown.png)

![](https://cdn.discordapp.com/attachments/540532000860143616/559166908163686421/unknown.png)

**Comment by Regalis11** [comment]
Should be fixed in 7d68679
