### ISSUE TITLE
New Suggestion for handling of bought cargo

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#134]
We all know it is a little bit of a pain to handle bought cargo if not potentially a nightmare, so I have a new suggestion regarding this.

Currently we have the Cargo Spawn point and the Metal Crate which is a 20 slot storage that - although a little tricky sometimes in the character GUI to use and thus is best accessed on the floor while having an item in hand to deny pickup - Is mostly part of the system I'm thinking of.

Basically, Add tags handling to the cargo spawn. Mission cargo and Cargo Type Tags (An Example would be: mission then general/medical/weaponry/supply - These could be defined inside the XMLs to allow anyone to create their own tags for their own content packages or to simply use a Hard coded list). There needs to be some method for sub designers to know what tags actually do exist for selection (Series of check boxes, drop down to add with removal methods or later as part of the tutorial and to simply be a feature for sub designers to include optionally!).

Now once this is in place, Have these 'tagged' cargo spawns spawn boxes (These may be different items or for now simply Metal Crates that are renamed to be identifiable and tagged for their type) - If no such tag exists, find the next Tagless/Mission/Any cargo spawn.

Have a Cargo spawn Type for each item in the XML (IE, Fuel is just 'small item' for tags purposes) - If none is defined it will go to the Tagless/Mission/Any cargo spawn, this cargo type isn't meant for the item itself or as a tag in-game but simply for the prefab and its spawning/buying purposes.

Finally spawn as many temporary boxes as required for the new cargo, the boxes themselves having a tag for automatic removal (Such as tag "autoremove" or such) for campaign purposes (Single or multiplayer) - which should spill the cargo out or remove it (Whichever of the two) before saving the submarine.

This could allow the medical supplies to spawn at the medical room, the fuel and engineering supplies near a reactor, the security or captains supplies to spawn on the bridge (And the mission cargo specifically for the bridge or such too) - all up to a sub designer, while not breaking the existing submarines that do not have such cargo definitions but still keeping cargo neat and transportable.

Since they would be inside boxes, this would be much, much less messier to handle, These boxes could be allowed to store harpoons or other general items that are too large, and perhaps give them a movement speed debuff for being carried if creating new items for this and using placeholder graphics.

**Comment by Crystalwarrior** [comment]
https://github.com/Regalis11/Barotrauma/issues/58
All of this would make buying cargo a lot better

**Comment by Regalis11** [comment]
Most of this was implemented in 9f58d1b and 7bbab35, but I still keep this open because there's a few more ideas that could still be added. Making the cargo spawn in appropriate places (meds in the medical room, etc) in particular would be an useful addition.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
