### ISSUE TITLE
Unable to revive dead character - appears to have thrown an error instead.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1341]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I tried to use the revive command on a dead character in debug mode, got the below error without the game freezing:
![image](https://user-images.githubusercontent.com/29177976/54874371-eff06400-4de1-11e9-966b-1305ecc19f7b.png)

Revive -> heal -> revive worked however.

**Steps To Reproduce**
Revive a dead character who is no longer on the crew list.

**Version**
0.8.9.7 steam closed alpha - windows 7 - singleplayer.

**Comment by Regalis11** [comment]
Fixed in 27917ee
