### ISSUE TITLE
AI fails to repair if the location to repair causes them to use a ladder (and not get off)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1342]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
if the AI is tasked with repairing leaks, and the leak is say, a damaged structure up a ladder (IE. near a hatch) - it will not detach itself from the ladder even if its flooded and can swim - simply repairing with its hands stuck to the ladder. end result is it welds a hatch until it runs out of fuel.

**Steps To Reproduce**
Damage a section above a ladder (Ie, on the vertical sides near a hatch on the top of a submarine, I believe the humpback or orca has such a design).

**Version**
0.8.9.7 steam closed alpha - singleplayer.

**Comment by itchyOwl** [comment]
This should be fixed already.
