### ISSUE TITLE
AI is incapable of repairing inaccessible areas of the Humpback (Ballast) - ending up repairing nothing instead as the sub floods.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1343]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the humpback is very difficult if not impossible for the AI to fix, because of its very design has no access to the lower ballast, the AI do not even attempt to repair through the walls (Which is possible I might add to repair its entire ballast without exiting) - though for the AI to fix this submarine it would have to swim outside into possible danger.

Either way, the AI cannot repair this submarine at all. and if it cannot reach a leak it will not attempt to choose another target, instead getting stuck until player intervention or perhaps death.

**Steps To Reproduce**
damage the ballast of the humpback then order the AI to fixleaks.

**Version**
0.8.9.7 steam closed alpha.

**Comment by Regalis11** [comment]
Partially fixed in fe10fde - the bilge is now reachable, although we should also modify the AI so that it doesn't get stuck if it can't find a way to fix a leak.

**Comment by itchyOwl** [comment]
The ai should already ignore the leaks (or other targets) that cannot be reached. If it does not, it's a bug. How exactly was the bot stuck? Need to try reproducing this.

**Comment by NilanthAnimosus** [comment]
it seemed to target and then cancel his target, only to go back to trying the same target. they were surrounded by lesser leaks flooding the submarine and ignore them favoring the worser leaks - but they cant reach them so it seemed like they cancelled it. they just appeared to eternally repeat a cycle to me and thus do nothing at all.

the most you saw was a very confused looking bot who either didn't move/attempt to path and just stayed that way. or maybe move a little and stop. I guess with a few explosion commands I Could get the AI to repeat this perhaps.

**Comment by NilanthAnimosus** [comment]
Right, heres a few clips I made fairly quickly with the old (current steam version) of the humpback:

[Clip A](https://i.gyazo.com/a7e15e7c3b457d94d4a3aa0078538012.mp4

[Clip B](https://i.gyazo.com/b28a50c3df1f6b8cf8950b8b1a24517d.mp4)

[Clip C](https://i.gyazo.com/820f5bb179ea4d16f7f6d4d58a8c2d1b.mp4)

There was some AI pathing errors I noticed in the console later, but from when I used the water command (Not in clip A/B) was when I finally decided to breach the floor and make an opening into the ballast - which actually stopped him moving left and right where instead it gave those errors into the console for no end node. so this is not related to the first two clips as it was clip C when they first appeared.

Ok so the clips are in order, Clip A represents damage to the lower ballast of humpback, they cant possibly reach it but they still path find pretty close (and eternally for that matter). They don't crouch to get closer, even though they should given that distance. but even if swimming its still too far to repair (Visible in clip C with him wasting welding fuel).

Clip B is when I added damage to the very reachable ballast tank on the left, before the damage was on the top/right/lower right and left side of the submarine when I first pointed this out and the AI really wanted the lower central ballast in that case too.

Clip C (and the pathing errors) is after I blew a hole in the top left of the ballast tank, meeting into the room he is walking in, he then stated he cannot reach it, freezes momentarily then swims over as the room fills with water giving those no end node console pathing errors while fixing the new breach I made.

With the room containing water, he swam back and you can still see in clip C where I made the blast that he fixed, he then swims trying to weld, much to no avail on fixing it.

the exact path find error was btw: "Pathfinding error, couldn't find an end node. (Character: Antony Whitely) and one case without the character (of about 17 cases)

**Comment by itchyOwl** [comment]
Thanks, very helpful! I'll get back to it soon ;)

**Comment by itchyOwl** [comment]
Should be fixed now.
