### ISSUE TITLE
Join server, spectate mission (.bin attached)

### ISSUE THREAD

**Issue by RedkiteR** [Regalis11/Barotrauma#1345]
Joined a mission in progress, roughly 5 players

This was after the initial attempts to do the campaign failed with 10+ players
Re-attempted joining and it worked fine for the remainder of the round.

Joined, entered lobby of match in progress clicked spectate and was returned to menu with following screenshot and bin report included:

[Join server spectate in progress.zip](https://github.com/Regalis11/Barotrauma/files/3000044/Join.server.spectate.in.progress.zip)

**Comment by Rokvach** [comment]
This has been fixed already, closing.
