### ISSUE TITLE
After starting (or having played) a campaign round - changing gamemode does not restore the job preferences

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1346]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon switching from campaign to mission due to a fairly buggy server experience, I recall that my character and character skills list was not wiped clean and set to a job preferences - it instead kept the character data despite it being on mission. did not check if this had any actual impact It probably shouldn't as I simply rejoined then left for the day.

**Steps To Reproduce**
I believe this may require you to play a campaign game and then end round or finish a round - then to change to mission.

**Version**
0.8.9.7 steam closed alpha

**Comment by Regalis11** [comment]
Fixed in 237f164
