### ISSUE TITLE
switching a newly created character's animation to swimslow or swimfast crashes the game

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1349]

**Comment by itchyOwl** [comment]
Crash log would be helpful. Steps to repro would be appreciated.

**Comment by Regalis11** [comment]
Create a new character -> switch to swimslow/swimfast -> attempt to move

![3567fdh](https://user-images.githubusercontent.com/14351070/54992015-e70cb780-4fc6-11e9-88fb-a5992613674c.png)

**Comment by itchyOwl** [comment]
Fixed.
