### ISSUE TITLE
How are relays intended in terms of power transfer? or is burnout of junctions unintended behaviour here?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1350]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I cant tell if their bugged or broken or what, so I would like to know the information on how their meant to be used. I know I have brought up relays before numerous times, but decided to make a new report.

I was wiring up batteries to separate the charge/discharge of them into power switches using relay components - they are wired to their own junctions as well.

to give a quick rundown I'll try to explain my setup:
![image](https://user-images.githubusercontent.com/29177976/54962265-0ae6e380-4f5c-11e9-8d36-80f300aaa331.png)

Top left junction (Same as grid):
![image](https://user-images.githubusercontent.com/29177976/54963402-9b272780-4f60-11e9-980d-24990053e8d8.png)

Bottom left junction:
![image](https://user-images.githubusercontent.com/29177976/54963438-bdb94080-4f60-11e9-853e-1f3a3c723caf.png)

Bottom relay (is for discharging the batteries- is fed power from batteries to junctions):
![image](https://user-images.githubusercontent.com/29177976/54963508-f48f5680-4f60-11e9-863f-f839d41cde77.png)

top relay (For charging the batteries - is fed power from junctions into batteries)
![image](https://user-images.githubusercontent.com/29177976/54963565-1e487d80-4f61-11e9-8213-2877aaf8dd7a.png)

The three relays near the top left junction are simply going to battery charging stations and recharge docks for shuttles. the relays with lights, text displays near the switches are for batteries.

So I had taken 4 batteries, their power charge and power out pins are connected to separate junctions and then to relays to allow for charging/discharging.

I figured slapping everything onto a single relay pin wasn't the brightest things, so I used a junction instead.

What I expected is for each separate "Network" to have a load/output value, and for the relays to count only as the power they needed and take that value across networks (IE. I have a charge of 200 on batteries, then those 4 would be around 800~ power wanted. so I would expect the relay to add 800 to the requirement on the other side and set the voltage accordingly).

What I actually get is broken components and fires everywhere, not to mention my other components connected to rechargedocks and such set on fire and their straight junction -> relay -> device unlike the above image.

how exactly are these used - without creating fires or disabling overload's all over the place. or is this unintended behaviour?

If needed, I'm including the submarine file - the batteries are not actually balanced mind you so ignore how long they seem to last, may need tweaking the recharge rates and fire rates are only around 15%-20% but should still break its junction, fair warning a dozen fixitems will cause a massive inferno at the docking hatch near the underside of the sub:
[Incomplete -RS- Typhon retrofit.zip](https://github.com/Regalis11/Barotrauma/files/3006038/-RS-.Typhon.retrofit.zip)

**Version**
0.8.9.7 steam closed alpha - windows, singleplayer.

**Comment by Regalis11** [comment]
This looks like a bug.

The junction boxes distribute the same amount of power all across the grid. In this case the grid is supplying 3700 kW of power to the box that's charging the batteries, even though the batteries are consuming less than 2000 kW. There seems to be something wrong with the upper relay, it shouldn't be pushing out that much when the load on the junction box connected to the batteries is only 2000kW.

**Comment by Regalis11** [comment]
Fixed in f4b85b3

**Comment by NilanthAnimosus** [comment]
Hurray! Now my submarines can spontaniously combust less! now for me to check something else out of confusion later.

I had the bottom half of my submarine in flames but canbeoverloaded is by default off for those docking ports. makes me wonder why it was on fire somehow down there. but maybe the fire somehow migrated through walls in a locked movement sub, that'd be funny actually.
