### ISSUE TITLE
AI find safety (perhaps other objectives for navigating) do not factor in door access

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1351]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

I had on the submarine design "id_medical" on the door button, and had intended to limit access to the room via access cards for medic spawns.
As a side note, the button opposite the door has no id_medical requirements.

The character attempting to enter was a mechanic, who had zero access tags on his ID.

This clip below shows the AI attempting to find safety (I had power off awhile, thus low oxygen):
[Clip of AI going against an access-restricted door for safety, properly until he snuffs it at that](https://i.gyazo.com/65bd7109ab7f1a8f4702903012078c2c.mp4)

**Version**
0.8.9.7 steam closed alpha - Windows, Singleplayer

**Comment by itchyOwl** [comment]
Fixed in a future patch.
