### ISSUE TITLE
Allow the sub editor to attach new components to items + Expand on the editable range of components

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1355]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I know its outside of the scope compared to content packages and such, but I know we can do this using other means and I wish we could simply have sub editor support for more freedom.

*what do I want and why do I want it. ok so:*
I want to use shuttle batteries in place of regular batteries as they look nicer in certain positions, such as a submarine they relays power from the main junctions to a single junction in case power fails - the submarine has a little control left before complete failure. sadly these do not have Repairable components, and thus no deterioration. I additionally wish I could have a sonar transducer with a slightly larger range (due to being in the rear of the submarine) that has a repairable component too.

In other areas, I wish I could change the max condition  of an entity, such as one or two doors having a different resilience to direct damage (Ie. reinforcing a restricted access armoury door), to perhaps make certain electronics more resistant to EMP strikes or water - given they'll decay at the same rate even with higher conditions.

We cannot even modify the FixDuration of items at high/low or skill repaired to repair them.

One could use this to make long lasting tanks or something sure, but ultimately that is just up to the submarine designer. there are plenty of other ways to do this if someone wanted to do it locally or share a modified content pack to achieve the same changes so why can't the sub editor?

Perhaps even the ability to select a different lighttexture for a light fixture and such.

I am not asking to expose things as crazy as having editable/configurable statuseffects or something, and turn the submarine editor into a full fledged item editor (Though amusingly - submarine files are quite capable of adding additional statuseffects and other custom content as-is for existing items, the editor simply doesn't support it directly).

I know I can just extract a sub file with any gzip capable tool (IE. 7zip) and simply modify the .xml of the submarine file, but editors are there to give us freedom and choice.

The more freedom and modability a game has, the more fun and use we can get out of it with more range of mechanics, I would love to see extended capabilities of the editor. I just wish we had access to more.

**Version**
0.8.9.7 steam closed alpha

**Comment by NilanthAnimosus** [comment]
I wanted to add power cables to my emergency lights, and I couldn't even when I directly edited the submarines XML data - it didn't even create them, felt odd as the old behaviour used to appear to support this in legacy.

so either I'd have to create my own content mod and give that to everyone just to do this with a submarine using a fairly identical item - or I would have to use other lighting and have my emergency lights look like generic lights because I cant actually use the emergency ones (Which look so much better in various areas).

Or end up asking for power pins to be added on devices that do not need them, and repairables added to objects that don't need repair - etc. I would love if we had the freedom to add none-default features to objects inside submarine files.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
