### ISSUE TITLE
Batteries have mincondition on deconstruction for their materials - I don't see why however.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1356]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Battery cells and fulgurium battery cells have a mincondition = 0.5 on their ingredients for deconstruction. I don't see why as the composition of the item wouldn't change depending on its charge, a depleted or full battery should deconstruct into the same items in this case.

A fulgurium battery takes a full fulgurium and zinc to craft. and a battery cell takes a full zinc and lithium to craft. so I don't think these were meant to be out conditions either.

**Version**
0.8.9.7 steam closed alpha

**Comment by Regalis11** [comment]
Fixed in 0c15748
