### ISSUE TITLE
Exiting sub editor with save dialogue will keep the dialog but not the sub - saving destroys the sub file

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1357]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I spent over 20-30 hours working on a submarine and I just completely destroyed the file. I went to save but then realized I had already saved, so I simply quit out and did not finish the save attempt.

Fast forward ahead - I went to make some other tweaks after a quick submarine test, I saw the dialogue and without thinking hit a button, then I saw it stated save but the screen was blank and I realized I just wiped my submarine file clean. loading the sub file resulted in a no hulls error and the file was around 460 odd bytes.

I recovered my submarine back, but this would still qualify as a bug perhaps.

**Version**
0.8.9.7 steam closed alpha

**Comment by Regalis11** [comment]
Fixed in fd56875
