### ISSUE TITLE
Text display flashes really fast from battery charge - battery outputs 6+ decimal value

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1358]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Battery charge values flash very fast in text displays, and clearly show a high number of decimal places.

I think for the output of charge signal and charge percent signal, it should be a rounded value, at most 1 decimal places if even that.

**Steps To Reproduce**
Wire up a depleting submarine battery (I used a shuttle battery for reference) to a text display, using the "charge" pin.

**Version**
0.8.9.7 steam closed alpha

**Additional information**
[Clip of the display](https://i.gyazo.com/5ad081110d47bc170e5994ab5831a066.mp4)

**Comment by Regalis11** [comment]
Fixed in 26a3f86
