### ISSUE TITLE
A New Creature

### ISSUE THREAD

**Issue by Emmett1Brown** [Regalis11/Barotrauma#1364]
What about this creature in the background of loading screen and main menu? Will it be in the game?

**Comment by Regalis11** [comment]
Probably not (and it's actually no longer in the main menu in the latest version, and will probably be removed from the loading screen as well). We've got tons of ideas for interesting new monsters, both from the players and from the dev team, but I don't honestly see anything special about this monster silhouette that'd make it worth implementing.
