### ISSUE TITLE
Diving suits in containers emit their light in the sub editor

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1365]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When looking at the lighting of a submarine in the sub editor, be it on load or when you create the suit, the light will appear from the diving suit.

Additionally, newly created flashlights that I pop a battery into then move / drop will show their light in a fixed position, never moving again later. (I think it actually does this without the battery, but I don't remember now)

I feel items inside containers should not have their lights visible in the sub editor. I'm sure this may be a consequence of not updating items in the submarine editor but it is fairly visible.

**Version**
0.8.9.7 steam closed alpha

**Comment by Regalis11** [comment]
Fixed in 45e33bc
