### ISSUE TITLE
[Tester's Version] Double Molochs are annoying

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1367]
So I frequently encounter molochs right, the molochs being spawned in doubles. They spawn 1 m beside each other, most of the time, and it's hard to know which one you are shooting. I suggest we remove the feature in which the moloch's spawn in doubles all the time, if you want more molochs, space them farther apart. Or atleast spawn one moloch and one charybdis or something.

**Comment by NilanthAnimosus** [comment]
It is worth stating when this occurs its in the very high difficulty ranges. if it is a server, to state what the difficulty slider is at (and if its at mission mode) - which I can see in my console output you played on in the last 1-2 days.

Given its very likely this (I've almost never seen issues with campaigns as they use their own difficulty for each mission though the same system) - my dedicated servers difficulty was set to "70"

**Comment by Regalis11** [comment]
2ed2982 should fix them spawning exactly at the same position.
