### ISSUE TITLE
Thorium fuel rods don't seem implemented, fulgurium fuel doesn't seem worth it to craft

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1370]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reactors cannot contain thorium fuel rods, nor do they give any kind of benefit to the reactor (they have no containable/available fuel amounts), making this a useless item. it is not craftable however so I assume its just not implemented.

Additionally, fulgurium rods offer just 25% more additional fuel over uranium (80 -> 100), though this does not use uranium as an ingredient, by comparison fulgurium battery cells are worth so much more charge and effectiveness than regular ones.

Personally I would have preferred this to be a higher available fuel (Only to last longer) or reduced condition usage but less max power or something (IE. make it a 200-400 health item for 30-60 available fuel).

As it stands its almost a complete waste to fabricate a fulgurium fuel rod over a standard one, unless you just have little to no fuel. but there is typically plenty of ore or funds for fuel purposes to get by without resorting to this making it a likely unused item as well.

**Version**
0.8.9.7 steam closed alpha

**Comment by Regalis11** [comment]
Fixed for the next patch (not visible in the repo because the files are in the Content folder).

Now fulgurium rods give 150 units of fuel and last 50% longer than normal fuel rods, while thorium rods give 100 and last twice as long.
