### ISSUE TITLE
[Steam version] There still seems to be an issue with the grid load and relay components

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1372]
Video: https://streamable.com/ztvid
 
If there is some power consuming item on the second part of the grid, the battery connected to the first part of the grid load is charging without increasing the grid load. The battery on the second part of the grid only increases the load on that part, so the reactor connected to the first part of the grid does not give the amount required on the second part.
At least that's what i got from the few tests i have done. I can't really tell what causes it, or give any other information, because i don't really fully understand how the whole grid load system works.

In case you need it, here is a sub file with the setup i have in the video:
[Relay Test.zip](https://github.com/Regalis11/Barotrauma/files/3025389/Relay.Test.zip)

**Comment by Regalis11** [comment]
I don't actually see anything wrong in the clip. The relay can only pass 1000 units of power through it (see the MaxPower property), so it doesn't make a difference if the battery is charging or not, the load will only be 1000. Even though the load is at 1499 and the amount of power the relay can supply is 1000, the batteries should still be able to recharge (although a little slower), and the oxygen generator should still work but generate a little less oxygen.

**Comment by BillCombs** [comment]
Yeah, that seems to be the case. I forgot about that property. Sorry for the inconvenience.

---
There is another problem with the grid load that i have on my submarine. I have no idea if this is a bug or my own fault, but i have tried a lot of different things and couldn't find the cause of this.

I have set MaxPower to 100000, yet there still seems to be a big difference between grid load and power.
This is a relay component that is taking power from two batteries. They are fully charged and definitely don't have a max output set to anything as low as 20-40.
![-2019-mar-30-001](https://user-images.githubusercontent.com/38168249/55277091-c62dc480-532e-11e9-84f9-5e3eb257906c.jpg)
The grid has multiple relay components in it. Not sure if that could affect it.

If it's not too time consuming, can you take a look please?
[Sub File.zip](https://github.com/Regalis11/Barotrauma/files/3025508/Sub.File.zip)

**Comment by BillCombs** [comment]
Rebuilding the entire system from scratch has fixed the problem.
Perhaps when the game updates it does not actually fully update the submarines? Not sure.

Since i don't have the problem any more, there is probably no need to keep this issue open.
