### ISSUE TITLE
[Tester's Version] Bad Grammar

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1373]
So when you get infected by a husk, one of the messages (something along the likes of "you are feeling fevirish") contains a spelling mistake, the mistake being "yours". Forgot the specifics of which message it was in, but there's a spelling error there. Might want to get that fixed.

**Comment by Regalis11** [comment]
Fixed for the next patch (not visible in the repo because the files are in the Content folder).
