### ISSUE TITLE
[Steam Version] Crash when a Player-controlled monster attempts to send text

### ISSUE THREAD

**Issue by Splaxiom** [Regalis11/Barotrauma#1374]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description:**
The game will crash to desktop when a player controlling any non-human creature attempts to chat

**Steps to Reproduce:**
This can be replicated by:
-Enable cheat mode
-(Optional) Spawn a monster
-Take control of any monster with the "control" command
-Open the chat with "t"
-Send any message, or at least try to do so (the game will crash when you try to send the message)

**Version:**
v0.8.9.8, the most recent Steam release
Windows 10 OS

**Additional information:**
This has been tested with Husks, Crawlers and Molochs in a Single Player campaign. 
This has not been tested in Multiplayer, this has also not been tested in the various voice channel
I have not attached a crash report due to how easy it is to replicate, and because of different system language

**Comment by Regalis11** [comment]
Fixed in 54ad370
