### ISSUE TITLE
Console spam when attaching items to walls

### ISSUE THREAD

**Issue by Weebyxanide** [Regalis11/Barotrauma#1376]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Objects that can be attached to walls in-game, such as logic components, buttons and light components, spam the console at regular intervals with the error "received a position update for an item with no physics body" if they're placed. This does not occur if they're placed in the editor. However, removing an item that was placed in the editor and reattaching it somewhere else causes the errors to appear.

**Steps To Reproduce**
Start a multiplayer game and place a logic component or button.

**Version**
Alpha v0.8.9.8
Windows

**Additional information**
This does not occur in singleplayer.

**Comment by Regalis11** [comment]
Fixed in 
9e1a4d8
