### ISSUE TITLE
Clientside glitching when going through the docking hatch connecting a shuttle to sub

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#138]
When you are going through docking hatches (e.g. The Nibbler in Aegir) it's pretty likely you will be "teleported" way outside the sub and far into the water, causing the game to freak out slightly on the clientside (pressure warning, etc.). However, this is completely harmless as the serverside knows exactly what's going on it seems.

getting stuck between two hatches in the docking port means you're kinda screwed and constantly teleporting to the "nether realm" though which is pretty spooky.

Might be a multiplayer-only issue.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma/commit/c4e894cb2e2b5ea844fbbac3edd267933d00d8f4
