### ISSUE TITLE
[Tester's Version] Syringe gun can't work because there are no syringes?

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#1382]
Checked the fabricator, medical fabricator, they don't make syringes. They aren't even on the sub by default. How are you even supposed to use that thing, if you can only load syringes into the syringe gun. and there are none of em on the sub?

**Comment by hubismal** [comment]
Is it april fools where you live?

**Comment by ChikoEduardo** [comment]
Have you tried like, loading the chemicals that are shaped like a syringe in them?

**Comment by AbominationBanisher** [comment]
> Have you tried like, loading the chemicals that are shaped like a syringe in it?

ain't working my dude

**Comment by AbominationBanisher** [comment]
reloaded game, it works now. strange.

**Comment by NilanthAnimosus** [comment]
Can't tell if a joke but, in the last version in the closed alpha most medical items were not syringe gun loadable, along with a good number of items not being able to be combined (IE. materials).

Most chemicals should fit into a syringe gun but I would not be surprised if there is a valid reason for this to not work.

My first thoughts would be the submarine choice, if an item had different tags its very possible the medicals stored in a submarines inventory will not actually fit into a container, least I believe that could be the case.

It may be a specific submarine does have a problem close to this, spawned medicals (and bought/crafted) should most definately work in a syringe gun however.

**Comment by NilanthAnimosus** [comment]
I have tested this and found myself unable to fire calyxanide as a projectile out of the syringe gun - the sound is made but the calyxanide stays inside the syringe gun without spawning a projectile too.

all other medicals (effectively all of them) fit and work, you obviously also cannot use blood bags / alien blood / bandages etc, items that don't visibly have a syringe built in do not work but that is what I would expect.

you finally cannot use ingredients like flash powder, though I'd find it funny if you could as that'd be like shooting an explosive stun jar.

**Comment by AbominationBanisher** [comment]
funny thing is, chemicals now loaded into the syringe do no damage to ai (not the buzzing outpost guy, your literal crew, engineers, captain, doctors, mechanics). reopening?

**Comment by Regalis11** [comment]
Fixed in baadd60
