### ISSUE TITLE
[Dev] Allow outposts to power vessels.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1385]
Maybe outposts could offer a low amount of power to docked ships, Enough to keep basics like Life Support running. This will help ppl using ships that start with the power offline and might prevent suffocation, which is a bit common in people new to the game at the start of a mission.

This used to be possible with custom made outposts but the latest dev build patch prevents this for some reason.

**Comment by NilanthAnimosus** [comment]
If this is to be a thing, I would suggest changing the logic of the game itself or not having it handled this way, for instance - have being docked at the start of the round differ to being undocked, such as free distributed oxygen from oxygen components, reactors do not consume their fuel to power a sub and batteries do not lower in stored charge if used. all of which is easily possible for the game to keep track of the submarine having left the start or not. one could even add XML attributes to status effects to not have them function when docked at outpost or just handle this in the components themselves IE. charging docks.

One could say, move around items but not be able to craft until having left. alternatively have the sub consume its resources and don't give it power for free, but listed down below have it purchasable before round start and still freeze event logic, more on that below.

Any game that spends time charging at an outpost or sorting cargo and such in-round is subject to ticking up the event time on creature and other event spawning, which means any submarine utilizing this is bound to have issues in difficulty that it shouldn't given it hasn't even moved or left yet.

I think we need some method to recharge our none-reactor submarines which does -not- utilize in-round time however (or time does not change while docked in a round, and only begins once undocked from an outpost while the outpost itself pauses time flow for event logic IE creature spawns and malfunction events).

One option would be to allow charging the batteries in game menus, just a simple check of power capacity or battery count and their power levels as part of the gamesession/saves extra data, and the option to buy units of power to them in one of the store pages as added GUI, oxygen should be replenished for free and water removed for free and be down to the sub crew to get that all functioning.

The game could finally store the total damage of the submarine as a count of walls part of the submarine, and offer a price to perform the equivalent of a fixwalls command on the submarine priced by damage to the submarine. this information only really needs to be stored in the extra data on campaigns. not sure how you would scale the pricing of such a repair though.

anything to reduce time spent at a level through a menu is probably going to be a welcome change. pre-round setup could be improved so it is less of an issue to have a suffocating crew or out of power submarine.

Free power is free power, and subject to being abused, personally I think making it less of an issue in other means than granting free power would be a better option, be it changes to logic in small or large ways, or just give us the option to buy that power and refill our oxygen : >

**Comment by ChikoEduardo** [comment]
Err... I think batteries not recharging thru docking ports is a bug introduced in the last update... It happens with all ships with 2 docking ports. I just tried with a vessel with only 1 docking port and it's recharging in my custom outpost. I'll do more testing.

**Comment by NilanthAnimosus** [comment]
I thought they did charge? News to me. though I found the vanilla ones were not even connected - my retrofit of the venture recharged iirc but that was an update or two ago.

I havn't tested, so Its quite possible it is bugged then. my initial response was more just thinking what we could do to alleviate the above by different means, if that exists it does need fixing though : >

**Comment by hubismal** [comment]
If I could add my two cents it would be nice if oxygen generator of the outpost connected to the sub vents. I'd like to turn off the reactor while I organize my sub but I don't want to suffocate.

**Comment by ChikoEduardo** [comment]
Well, if outpost provide enough power, then oxygen generators should work without having to turn on yout ship's reactor.

**Comment by Regalis11** [comment]
I tried to reproduce this by adding extra docking ports to Remora's drone, but it still seemed to get power from the sub normally. Could you please send me a sub where the problem occurs (or let me know if there's some sub in the workshop that I could try)?

**Comment by ChikoEduardo** [comment]
Here's an example:
https://www.dropbox.com/s/sddopf3oqar6gdl/Submarines.rar?dl=0

Hmm... after I took a look at the Remora's drone, I noticed mine use relay components... maybe they are still causing issues.

**Comment by Regalis11** [comment]
Thank you, I'll take a closer look at his tomorrow!

**Comment by Regalis11** [comment]
Fixed in be96afc
