### ISSUE TITLE
[Dev][Feature request] Let server hosts enforce a line of sight setting

### ISSUE THREAD

**Issue by ButteredCats** [Regalis11/Barotrauma#1388]
Server hosts should be able to force the line of sight setting, or let players choose between specific ones well locking one out. This could be used for servers that always have traitors enabled to make sure the traitor can hide their actions and not be spotted through the wall. Even if the host simply wants the players to have a harder time this would be useful. Possibly even subs can have these settings applied when they are created, such as having the challenge for a sub not being able to see outside because there aren't any windows.

**Comment by hubismal** [comment]
Isn't this alredy a thing?

**Comment by PicolasCage** [comment]
Even better, would be to let users set their sight settings midgame and have it change midgame, unless the hosts specifically make sure that they don't want that happening.

**Comment by Regalis11** [comment]
Already implemented
