### ISSUE TITLE
Occasional hangs when saving/loading submarine preview images

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1389]
Seems to happen in TextureLoader.FromStream which tries to read the image from a Base64 encoded string in the submarine xml. Started occurring after the size of the preview images was increased.

**Comment by juanjp600** [comment]
Submitted a fix to MonoGame
https://github.com/MonoGame/MonoGame/issues/6703
https://github.com/MonoGame/MonoGame/pull/6704
