### ISSUE TITLE
[Nitpick] Entry of Gladiators doesn't loop properly because ogg file is too long

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1390]
The .ogg file goes on a little bit long with a bunch of silence at the end. The actual notes played make it sound like it's intended to be a loop, but as it is ingame, it doesn't loop very well at all. Really nitpicky, I know.
All a fix would require would just be clipping off the silence at the end.

**Comment by PicolasCage** [comment]
From my experience, the clown song looped well and I had no problems with it. Strange that the error happened on your computer. Hmmm.

**Comment by Regalis11** [comment]
Fixed in the private repo, not visible here because it only modifies the audio asset that's not included in the public repo.
