### ISSUE TITLE
[Bug/Lack of Polish] Multiplayer game still sensitive to various inputs while in menus (pause, settings, etc)

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1391]
What the title says. WASD are still usable for walking in the pause menus, so is LMB or RMB for aiming and firing (which is more of a problem). This is probably because the game is still technically running in a multiplayer game unlike in singleplayer (where most of the testing for this stuff is probably done). For instance, if you are in the railgun/coilgun interface and you pause the game, every time you left click on an option in the menu, you will fire ingame. I assume a simple input fix will fix this.

**Comment by Regalis11** [comment]
Fixed in 63971c9
