### ISSUE TITLE
Guitar Song_2.ogg should be removed

### ISSUE THREAD

**Issue by PicolasCage** [Regalis11/Barotrauma#1393]
I must say, the song is unpleasant to listen to. Same for the first harmonica song. They could be replaced with something a bit smoother in my opinion.

**Comment by hubismal** [comment]
Did you just like your own suggestion?

**Comment by PicolasCage** [comment]
> Did you just like your own suggestion?

Of course. As sad as it may be, it only makes sense.

**Comment by PicolasCage** [comment]
Closing because nobody likes the idea.
