### ISSUE TITLE
[Feature Request] Round starting splash screen when round is starting

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1396]
In the current build, once everyone has checked "ready to start" the game enters a kind of limbo for a few seconds where chat messages don't send and voice communication cuts off. After the game is done loading/lagging like this, the game goes to the BAROTRAUMA: LOADING...XX% splash screen.
It would be nice if there were some kind of indicator that everyone had voted and the freezed lobby had a "round starting..." message or something. or it could just immediately jump to LOADING...

**Comment by Regalis11** [comment]
Added in 33b8c37
