### ISSUE TITLE
[Bug] Campaign lacks content towards innner rings

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1398]
As you go towards the center of the map, missions become so rare that they sometimes just stop appearing outright in most mapgen seeds. 
Additionally, a lot of maps have zero settlement establishment/depopulation activity towards the center of the map.
Here is an example of one:
LffGF4Bo

This makes it impossible to earn money towards the center of the map.

**Comment by Regalis11** [comment]
This is actually intentional. The idea is that as you get closer to the center, you will have to start relying more on supplies you've brought with you and/or resources collected from the environment.
