### ISSUE TITLE
[Feature Request] Generate new random seed in seed field when opening NG dialogue

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1399]
It would be nice if every time you opened the "New Game" dialogue, a new random seed was generated in the seed field instead of there always being the same one until you restart the game.

Alternatively there could be a "generate new seed" button next to the field just in case.

As it is right now you have to manually edit numbers/chars in the field if you want to play a unique new game in the same session.

**Comment by Regalis11** [comment]
Added in 2479493
