### ISSUE TITLE
stacking stuns is bullshit and needs to be looked into

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#140]
Technically you can stun someone for a ***LONG ASS TIME*** if you dual-wield stun batons and completely discharge them on someone. I think if someone is stunned, every subsequent stun hit should only add another .5 seconds to the stun MAX.

**Comment by NilanthAnimosus** [comment]
Stuns cap at 60 seconds, instead add a flag / option in the XMLs so stun attacks / effects to be additive or up to - making it up to the content pack and item type instead.

.5 seconds is honestly nothing, if a stun baton strike dealt a 15 second stun .5 seconds isn't even comparatively worth hitting them again. Perhaps add a "Stun resistance" instead to prevent stun-locking where each increase causes a separate resistance to stun to increase (So every X seconds of stun results in X percentage stun reductions which reduces like the bleeding mechanic with time).

Of course, I actually like the current stun, I would personally not want the Ahem "Long ass time" stuns removed, I often find it useful if I have anywhere from 1 - 3 players I need to subdue hitting each player twice gives me more time to deal with the situation / drag the bodies and other such.

Sometimes dragging that prisoner all the way to a brig takes a minute of dragging, so I wouldn't want to lose the ability to force my prisoners by the ankles proverbially (Or the shoulders/chest with the new code added) 

if we could have full XML flexability, having a value for the resistance change itself on top of whether the stun increase can be reduced by additional stuns so some attacks can never be resisted/effected by any resistance mechanic would be nice.

**Comment by Crystalwarrior** [comment]
I warmed up to the current stun system tbh, though maybe still there should be some kinda cap or reducement
