### ISSUE TITLE
[Bad Bug] [Possible Linux] File selection dialogue window does not close correctly on Linux (maybe windows?)

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1401]
After pressing "select" when you choose the file you'd like to use as the preview image, the game accepts the image and everything goes normally except for one small detail: instead of closing, the file explorer window just hangs and stops refreshing instead of properly closing.
![2019-04-07-142707_1366x768_scrot](https://user-images.githubusercontent.com/47284081/55688829-f125a300-5942-11e9-815f-f75e95f14114.png)
In this picture you can see the correct file has already been chosen but the selection window stops updating.
To note, this is graphical effect is a very frequent thing on my linux computer because the display manager just starts not updating the windows when something like firefox crashes, leading to the drag effect you see.

I haven't tested windows because I'm lazy.

**Comment by Regalis11** [comment]
Fixed in 304db98

**Comment by Rokvach** [comment]
Confirmed working, closing.
