### ISSUE TITLE
[Dev] Changes in code for ElectricalDischarger?

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1402]
ElectricalDischarger could be used in a number of applications in mods, including as payload for grenade and railgun shells.

There's a couple of things that happen when using that piece of code in handheld items, though.

-The first one is it can be discharged when held and pressing the use button. Currently, this can be prevented by using Pickable instead of Holdable or Throwable.

-The second issue is this piece of code, or the graphical part of it, is not designed to stop once the item it is attached breaks. Here's a video showing an example:
https://cdn.discordapp.com/attachments/405014318892056577/564774398754553866/JDbyA9AJo1.mp4

**Comment by Regalis11** [comment]
Fixed in 488fded
