### ISSUE TITLE
[Feature Request (Small)] "You are no longer a traitor" notification upon respawn

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1409]
A lot of legacy players don't know that you don't respawn as a traitor. It would be nice if a dialogue box popped up upon respawning in the respawn shuttle saying "You are no longer a traitor! Now try and assist the crew" or something like that.

**Comment by PicolasCage** [comment]
I'm Mcloving your idea. Even I get confused whether or not I should still kill the person after dying. :D

**Comment by ZealanL** [comment]
Agreed. I hate the idea of traitors respawning and still being a traitor. I think the NLR (new life rule) should apply to Barotrauma, where your previous targets and enemies are just neutral once you respawn, and you "forget" about your previous life.

**Comment by Regalis11** [comment]
Added in b5cc008
