### ISSUE TITLE
[Minor Issue] [Graphical] Sonar Beacon Sprite smaller than the battery that you put in it

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1410]
The overworld sprite for the sonar beacon is smaller than the overworld sprite for the battery cell. It would seem in the grand scheme of things that the sonar beacon is just too small; it's also ridiculously small for character hands.
![2019-04-08-105536_1366x768_scrot](https://user-images.githubusercontent.com/47284081/55749498-aa00e600-5a06-11e9-9a08-6e7cde4cebbd.png)

**Comment by Regalis11** [comment]
Fixed in the private repo, not visible here because the commit only modifies files in the Content folder.
