### ISSUE TITLE
[Bug] [Feature Request] [Graphical...?] "Downloading the [Submarine]" progress bar no longer appears

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1412]
When being prompted to download a sub, there is the usual dialogue box:

>You seem to be missing the blah blah, would you like to download the "Aegir With Lots of Colored Lights Mk II?"

But unlike in legacy, the download bar on the bottom that states stuff like filesize and shows the green bar to indicate progress of the download doesn't appear anymore.
A little while later (2-9 seconds) it says.

>The "Aegir With Lots of Colored Lights Mk II" was successfully downloaded.

And it works normally (just without the progress bar), but the little bar in the bottom was nice for long downloads of annoyingly large subs. 
When you are eventually downloading things like larger characters or maybe even packs from the workshop, it would be nice to have some kind of progress indicator like this so you know how big the file is and how long you're gonna wait.

**Comment by Regalis11** [comment]
Fixed in 40d0a49
