### ISSUE TITLE
[Bug][Linux] Attacking station attendant with stun baton/revolver causes heavy lag on them regaining consciousness

### ISSUE THREAD

**Issue by bdeyoun1** [Regalis11/Barotrauma#1417]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game slows down to less than a frame per second for around 10 seconds

**Steps To Reproduce**
With a stun baton, attack the station attendant and let them attack you. When they regain consciousness and attack you the game should slow down. I have had this happen when attacking them with the revolver as well, but it wasn't as consistent.

**Version**
Barotrauma V0.8.9.10
Kubuntu 18.10

**Additional information**
This was done in the single player campaign. Was able to duplicate across multiple subs

**Comment by itchyOwl** [comment]
Fixed in the next patch.
