### ISSUE TITLE
[Dev] Diving suits have 2 lights.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1418]
I noticed this while I was comparing them with the ones in my mod. This explains why their lights are so bright.

The second light could be deleted but I've got a suggestion for it:

```
        <LightComponent range="200" lightcolor="250,224,165,255" powerconsumption="10" minvoltage="1.0" IsOn="true">
          <StatusEffect type="OnWearing" target="This,Character" Voltage="0.8" setvalue="true" comparison="Or">
            <Conditional IsDead="true" />
          </StatusEffect>
          <LightTexture texture="Content/Lights/lightcone.png" origin="0.05, 0.5" size="1.0,1.0" />
        </LightComponent>
```

These changes will make it so when the user dies, the lights will start to flicker instead of just turning off, making it a lot more spooky. Here's an example:
https://cdn.discordapp.com/attachments/405014318892056577/566292498960482337/0QqP4OOUX2.mp4

**Comment by Regalis11** [comment]
This is actually intentional, the idea was to make the lights brighter than what's possible with one light source.
