### ISSUE TITLE
[Dev] Heads in humans are not aligned with each other.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1419]
This means headgear look better on some heads and bad in others. There are cases where they look like it's clipping. Maybe also add a piece of code that hide hair styles since some of them are big enough to clip thru hats and the like.

**Comment by itchyOwl** [comment]
Related request regarding the hair: #1161.

**Comment by Rokvach** [comment]
Seems to be aligned correctly now. Closing.
