### ISSUE TITLE
Bundle content for macOS into a .app using MonoKickstart.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#1422]
[I.E. do the thing Linux and Celeste do](https://user-images.githubusercontent.com/21148093/56224058-f2d72100-603c-11e9-956b-e11ff39df895.png).

Since I don't see any clean way of making the MacClient project copy files directly into the .app bundle it'll probably take a few extra steps to ship out macOS releases now. If needed you can probably just create a script to automate these steps.

I'll get around to implementing this soon.

**Comment by CommanderMark** [comment]
Doesn't seem to be working out.

**Comment by hubismal** [comment]
major rip
