### ISSUE TITLE
[Linux] [Crash] Tutorial Videos, Intro video on Linux not working.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1435]
The intro video has technically never played, I just never noticed it. It plays fine on windows, but not on Linux. juanjp suggests that it may be VLC related and he seems to have self-assigned this as a todo at some point.
In addition, the tutorial videos availabe in the new (very cool) tutorials instantly result in a game crash.
[crashreport (16).log](https://github.com/Regalis11/Barotrauma/files/3118994/crashreport.16.log)

**Comment by hubismal** [comment]
This was fixed by juanjp suggesting I do
`sudo cp /usr/lib/x86_64-linux-gnu/libvlc.so.5.6.0 ~/.steam/steam/steamapps/common/Barotrauma/libvlc.so`
as in copying libvlc.so.5.6.0 from the x86_64 gnu libraries and putting it in barotrauma's main directory. I won't close the issue until it's pushed in the next update in order to prevent duplicates.

**Comment by Regalis11** [comment]
Should be fixed now. Uploaded as a separate patch for Linux without incrementing the version number, so it doesn't break compatibility with the current Windows/Mac versions.
