### ISSUE TITLE
Sessile Organisms

### ISSUE THREAD

**Issue by Geevies** [Regalis11/Barotrauma#144]
How about some harmful sessile organisms? Like we often see large coral like structures. Make coral that releases an electrical shockwave when something swims or passes through it, destroying all junction boxes in it kind of like an EMP, but would be very visible on radar.

Coral/algae that entangles players if they come into contact with it, they have to cut it with a cutter to get free or frown after some time.

--Wolvered Suggested, posted for him--

**Comment by Regalis11** [comment]
We've got some of these in the dev branch now! :)
