### ISSUE TITLE
[Linux] Crash when trying to connect to BT Public

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1443]
Nothing much else to say. Here's the crashlog.
[crashreport (26).log](https://github.com/Regalis11/Barotrauma/files/3124666/crashreport.26.log)

**Comment by juanjp600** [comment]
See https://github.com/Regalis11/Barotrauma/commit/0b1b39d70a8ce969b233c457f34bda1d20771083

**Comment by hubismal** [comment]
This is no longer an issue. Closing.
