### ISSUE TITLE
[Unstable] Separatist medic uniforms have swapped inventory icons

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#14452]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14443

<div type='discussions-op-text'>

<sup>Originally posted by **HawkinsThe71st** August 17, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The medicseparatistsuniform1 (brown) has the green uniform icon while medicseparatistsuniform2 (green) has the brown uniform icon
![image](https://github.com/user-attachments/assets/55e318c8-2c85-4b21-b03f-469292bafed0)

### Reproduction steps

Compare medicseparatistsuniform1 and medicseparatistsuniform2 sprites and inventory icons

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

Other

### -

v1.6.2.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by dinhtuananhfakefish** [comment]
Pushed in 3bd7e845d9a157bf92681b63a042d92623bc1228

**Comment by Regalis11** [comment]
It seems to me that something's still off here, the dropped items don't look the same as the inventory icon or the worn sprites
![image](https://github.com/user-attachments/assets/d83de40a-d265-4f2c-85d2-b3187c658edc)

The inventory icons are also now unused, I guess they could be removed?
![image](https://github.com/user-attachments/assets/013418f6-e1ba-45b8-9bc3-8caf76ceb26c)
