### ISSUE TITLE
Weird grid load behaviour

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1445]
Can't really describe it properly, or tell what causes it.

What it seems to be: Grid load stops being equal between items either after starting a new game, or after loading the save of the sub. 
Seems to somehow depend on the relay component(does not happen if you use a junction box for connections)

Sometimes after you save the sub in the sub editor, it is fine when starting a new game, but breaks after restarting.
At other times after you save it, the grid breaks when starting a new game, but becomes fine after restarting.

Videos:
https://www.youtube.com/watch?v=bfFzw01YZhQ
https://www.youtube.com/watch?v=O1xcEl5XG4w

Doesn't seem to be dependant on the amount of relay components or batteries.

It's hard to distinguish between correlation and causation relative to this bug due to its nature, so don't take any of the information above as 100% accurate.

Sub files, in case you need them:
[Sub files.zip](https://github.com/Regalis11/Barotrauma/files/3131593/Sub.files.zip)

**Comment by HalfdeadKiller** [comment]
Here is a demo submarine I made to give some examples of weirdness regarding relays.

[a.PowerTesting.sub.zip](https://github.com/Regalis11/Barotrauma/files/3308617/a.PowerTesting.sub.zip)

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
