### ISSUE TITLE
Relay component's power input seems to leak when power is being transferred through the component.

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1446]
I am assuming this is not intended behaviour, since the grid load is different on each side

Video:
https://www.youtube.com/watch?v=lipYJLPLqhA

Sub file, in case you need it:
[Junction box test.zip](https://github.com/Regalis11/Barotrauma/files/3131586/Junction.box.test.zip)

**Comment by BillCombs** [comment]
Not sure if i understand what you mean by "the relay can only pass through 1000 units of power". Does that mean that the game's limit is only 1000 and setting max power to any bigger value won't work? I have set it to 100000 in the example sub, and it seems to be working fine.

The main issue in the example is that one of the lamps is being powered by the relay's power_in connection. The relay component has power_in and power_out connections, so i am assuming the power_in is supposed to only take power, and the power_out is supposed to only give the power away. But in this case, the lamp is being powered even though it's only connected to the battery through the relay's power_in. So some systems designed to only send power in specific directions might also be sending power in unintended directions.

**Comment by Regalis11** [comment]
Ah, I assumed the power got capped because of the default max power value of 1000, and didn't notice the other junction box was getting power through the relay's power_in connection. That's definitely a bug, so I'm going to take a closer look at this. Thanks for the clarification!

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
