### ISSUE TITLE
Suggestion On Class System

### ISSUE THREAD

**Issue by TheLaughingDead** [Regalis11/Barotrauma#1447]
From what I can tell, [the class system] is like spectrum, from (Specialized Class System) to (No Class System). Hard skills serve specialized class system well, because they create the demand for every kind of job. Soft skills are still part of "Class System" because they still differentiate between player choices, but they are a lot closer to the (No Class System) side, because you can still do any job with any character, just perhaps less efficiently.
As it is right now in Barotrauma, they seem split on choosing where on the spectrum they want to land, and as such have split their classes between (Specialized Class System) and (Soft Skill Class System). Half the characters (looking specifically at Mechanic and Engineer) have hard skills that are practically required to pass a mission, or at least far outrank the abilities of Security, Captain, Assistant, and Medic. The latter four mentioned all have soft skills that make them part of a Class System, but none of them have skills nearly as specialized as Mech/Eng. You can still shoot railguns and harpoon guns, handcuff people, and stun-baton folks even if you aren't security personnel. You can still pilot the ship and give orders even if you aren't the captain. One might argue that medic is almost as useful as Mech/Eng because they can do a lot more with medicine than anyone else, but you can still patch a wound, inject someone with drugs, and in general maintain the health of the crew even if you aren't a medic. We don't talk about assistant. I would argue the primary benefit of most of those classes (fuck you Assistant) is their ID cards, but that could be player-based instead of class-based just as well. Choose a "role" that gives no in-game benefits beyond a specific ID card, and you basically have those four classes.
What I suggest is that for the classes to have more worth in their respective roles, you need to give them something that is around as important as fixing junction boxes and the engine. Captain could perhaps have unique ability to repair or use the nav and status terminals. Security could be the only people able to use guns on the sub, whether that be handheld weapons like harpoon guns (any other class would be too dumb with the weapon and shoot themself in the foot?) or actual railguns/coilguns, or both. That would cement them as almost required for most missions. Medic could be pretty much the same, except if you aren't a medic, then medicine can potentially harm the person you are trying to effect rather than help them. This could be chalked up to ODs, wrong vein/artery, or whatever medic jargon you wish to implement. Still, it shouldn't take a rocket scientist to use a bandage, so at least a crewmember can get by if they hit their head on a door lmao (though  that alone could drastically reduce medic pick rate, because bandages at least stop most health problems in the game right now. Maybe change bandages so they just slow it down enough, rather than stopping completely? Is that a thing already?). Assistant... why tf does this class exist lmao. Maybe they could do any and all of these things, but super poorly. Barely heals with medicine, totally inaccurate and low damage with weapons, can pilot but can't fix status/nav terminals? Who knows.
Or, if we were to follow a more generalized class system or no class system at all (closer along Blue's line of thinking), it would instead be one to three stats (one stat is no class system, 2/3 is very general class system) that could be applied all across the ship in multiple ways, whether those be hard skills or soft skills.
Maybe you need dexterity to use weapons or pilot the ship, intelligence to do mech/eng/medic jobs? Maybe you don't even need them, but they grant minor buffs for having a higher skill of a certain kind.
Maybe all the skills apply some form of buff onto what action you are doing no matter the action, and then the question is less so "Can I do it?" and more so "How do I want to do it?" Dex pilot can move quickly and maneuver faster, Int pilot can use sonar to better effect. Dex in general increases run/swim speed, Int decreases O2 or Welding Fuel usage. A dex engineer could deal with power changes quicker, and an Int engineer could... ah... I'm running out of ideas lmao. You guys get the point.

Either way, this is purely theory-crafting and I have no idea on the practicalities of implementing something like this, so please take my suggestion with a grain of salt. Good luck on the development!

**Comment by Regalis11** [comment]
This actually sounds very much like the changes we've been doing to the skill system in the upcoming Steam version. Basically now all classes can do anything regardless of their skills, but having the appropriate skills allows you to perform tasks faster and more reliably. Pretty much what you suggested here, for example medical items may not work as well (or can cause more harmful side-effects) if you administer them as a non-medic. There's still some more balancing work to do - the skills should have a very noticeable effect, but not so much that completing a round becomes almost impossible if you're lacking a specific class.

And as for the assistants, they're basically "supposed to be" a class that's not particularly useful at anything. It's mostly intended as a class that allows new players to see how the game works without being assigned any important responsibilities. 

Anyway, as this is pretty much what we've already implemented (+ a couple of additional ideas we'll definitely take into consideration), I think this issue can be closed. Thanks for the very well thought-out suggestion!
