### ISSUE TITLE
[Dev] Lighting issue in outposts.

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1449]
It appears lighting in either the starting or the destination outpost will go fully lit. Also, I think it only happens with the large fluorecent lights because I noticed small lamps don't do this in my custom outpost.

Here's an example pic taken in the same map of both outposts in it:
https://cdn.discordapp.com/attachments/405014318892056577/573520601965133824/LightingIssue.png

**Comment by Rokvach** [comment]
Fixed today, was caused by background lights bleeding through background walls that can only be resized on one axis.
