### ISSUE TITLE
Cave System Maps

### ISSUE THREAD

**Issue by Geevies** [Regalis11/Barotrauma#145]
Small cave systems, that you have to explore with a diving suit, and no sub. Or if you do have a sub, it's small, and only used for carrying items.

The entire map is a small cave system, illuminated by bio-luminescent plants, so you dive into them with a scuba suit.

--Suggested by DumpsterFire, posted on their behalf--

**Comment by Regalis11** [comment]
Making the entire map a small cave system would need a lot of rethinking on how navigating the map and completing missions works. IMO having small caves in the levels in addition to the path that's large enough for the sub to pass through is the preferable way to go, and those are already implemented. What should be changed however is making it more common that a mission requires the player to go inside those.
