### ISSUE TITLE
[Dev] Character limb depth issue

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1451]
So I'm making a new creature, a husked crawler but I have been unable to edit the appendage's depth so it appears behind the head. I've tried using the editor or manually editing the depth value in the xml file and it's still the same:

https://cdn.discordapp.com/attachments/426913209602146315/573736724782514176/Barotrauma_qrCBhBuhkn.png

I've actually tried to edit the depth value of the other bodyparts too and none of them are affected, also.

**Comment by Regalis11** [comment]
Currently depth sorting does not work correctly between deformable and non-deformable sprites. The crawler's body is deformable, while I'm guessing the appendage isn't. For now you could try working around this by making the appendage deformable as well (it doesn't need to have any deform animations though).

**Comment by juanjp600** [comment]
Self-assigning since it's an issue that will become more prominent in #161
