### ISSUE TITLE
[Unstable] Graveyard sub-biome bad for performance

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#14527]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14139

<div type='discussions-op-text'>

<sup>Originally posted by **ubertpendragon** June 15, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The WastesGraveyard sub-biome is not very performance friendly
It has:

- 3 to 4 wrecks
- 1 very large ruin
- 5 Abyss islands
- 2 Caves
- Most likely a beacon
- Dozens of hours of accumulated late-game resources

Suggest trying to cut down to 3 wrecks, 0 ruins, 1 cave 1 abyss island (for mission support) 

### Version

Unstable</div>

**Comment by JeroonBosch** [comment]
This biome variant was removed, closing ticket
