### ISSUE TITLE
[0.8.10.0] The game crashes on Windows 7 x64.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1453]
**Description**
I understand that there are three such issues on github, but they are all a year old. In addition, this is a beta version and the bug may already have another way out.
Two of the three people were unable to run the game on windows 7 x64. Everyone has the same crashreports.
They managed to play 0.8.9.6, but the version above does not run with them.
[crashreport_3 (2).log](https://github.com/Regalis11/Barotrauma/files/3147786/crashreport_3.2.log)

**Version**
Windows 7x64. 0.8.10.0.

**Comment by itchyOwl** [comment]
Duplicate: #1515.

**Comment by Nevol2110** [comment]
Well, actually a duplicate of discussion, not me, but him. I don't really care anymore. Fix bugs.

**Comment by itchyOwl** [comment]
Yeah, this had gone unnoticed/unhandled. The issue is the same. No offence, you found the bug before the others!
