### ISSUE TITLE
[0.8.10.0] Error while using mute.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1454]
**Description**
![image](https://user-images.githubusercontent.com/33912761/57289117-71b2fd00-70c3-11e9-8853-c215918507d2.png)

**Version**
0.8.10.0. Windows 10x64.

**UPD**
Even when the engineer repairs the shields, sometimes there is a "CannotRepair".

**UPD**
                 Error
VoipCaptureDeviceNotFound

**Comment by Regalis11** [comment]
Fixed in 0.9.0.0
