### ISSUE TITLE
[Issue] [Music] [Feature Request] Layer 0 - Basic is overpowering to the point any other layers aren't audible

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1456]
Layer 0 - Basic plays at maximum volume while things like Layer 12 - Objective Complete are barely audible at all. I didn't even know Layer 12 actually played until I really paid attention in the outposts.
![2019-05-10-094116_1298x588_scrot](https://user-images.githubusercontent.com/47284081/57535411-c9da4100-7307-11e9-92f5-69f6f18f896f.png)

The 16 minutes of Layer 0 gets really really grating after playing multiple rounds. The other layers provide much needed change in sound, but they're too quiet.
I understand this might be a balancing/mastering choice to make sure the layers don't get too loud when stacked, but I really think basic should be made quieter since you're going to hear it always, while the unique tracks that describe the situation should be given more focus.

**Comment by fabevil** [comment]
I have to agree with Hubismal here, most music audio files get drowned out by the default sounds or the basic layer, which is a shame, since these music audio files really fit the tone of Barotrauma

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2596a6c0d9a3b586d6af37c2cc3f594f70beb8a6 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
