### ISSUE TITLE
Radiation Detector- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1457]
Sends out a signal equal to a value of the current radiation amount that touches it.

Appearance:
Has a standard casing of a detector in the game and it's yellow colored inside not like water or motion detector which are blue or green.

Usage:
Could be combined with regular alert trigger to ring any time radiation value hits 1 or above and "RegEx Find Component" connected to a loud siren o send out even louder alert sound in case if radiation had to become even higher.

**Comment by Regalis11** [comment]
We don't have a radiation mechanic in the game so this isn't necessary (at least for the time being ;))
