### ISSUE TITLE
Books- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1461]
- Leveling takes long time.

- Depending on the type of a book one of 5 skills increases.

- Books prevent farming exp at some point once certain level is reached.

Having to be an engineer trying to learn medical stuff by making constant mistakes on healing others would be a real flustration.

**Comment by Regalis11** [comment]
I think this would lead to pretty uninteresting gameplay: waiting a long time doing nothing to get your skills up sounds like an extremely boring way to level up, and IMO would not really be fitting for a fast-paced game like Baro.

**Comment by rico6822** [comment]
> I think this would lead to pretty uninteresting gameplay: waiting a long time doing nothing to get your skills up sounds like an extremely boring way to level up, and IMO would not really be fitting for a fast-paced game like Baro.

Yes, but between fights some characters are being most likely idle in the mean time doing nothing productive. Books are to make them grow slowly stronger so time won't go wasted.

**Comment by Regalis11** [comment]
Still, holding a book in your hand would not make those idle moments any more interesting. We do need to make sure there's always something worthwhile to do, but I don't feel books are the best way to do it.
