### ISSUE TITLE
[Bug] [Polish] Credits will start from where you left off

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1463]
If you hit "back" while viewing the credits, and then hit credits again at any point after (assuming it's the same play session), credits will pick up from where you left off. This could be intentional but it feels like it lacks polish and is a little jarring in the least jarring way possible, if that makes any sense. It takes a second to realize why the credits are starting from the halfway point.

**Comment by Regalis11** [comment]
Added in 0.9.0.0
