### ISSUE TITLE
Make Light Components Require Battery Cells to Work- Slightly Crazy Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1465]
Yes, I know how it sounds but I always wondered how do light components work without a power source at all.

I believe they should drain power 4, 5 or even 8 times slower than headset does as some of them are outside submarine and drain it only when activated. All light components on vanilla submarines should have battery cells inside on start.

P.S. About the fact diving suits only generate light when they have a living human inside I always wandered if it could be explained by that humans do use their own brainpower to supply the light.

**Comment by thegrb93** [comment]
Totally unnessesary

**Comment by hubismal** [comment]
Do you mean for items or every single lightbulb on the sub?

**Comment by rico6822** [comment]
> Do you mean for items or every single lightbulb on the sub?

Items.

**Comment by Regalis11** [comment]
Even though it'd be more realistic, I feel it'd be extremely tedious to both submarine creators and the players to have to manage batteries in them or wire every single one of them to a power source.
