### ISSUE TITLE
[Bad Bug] [Multiplayer] Switches don't "Flip" properly

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1471]
Flipping on on/off lever on pumps (applies to reactors too I think) in multiplayer makes it flip back to off regardless of what you do. Should be easy to reproduce.

**Comment by Regalis11** [comment]
I haven't found a way to reproduce this. Does it happen consistently on some specific subs/pumps? Could it be that the pump/reactor is being automatically shut down by some kind of a circuit?

**Comment by hubismal** [comment]
I will try to test this further the next time a server is available for testing. It happened on database's test server

**Comment by hubismal** [comment]
Unable to reproduce no matter which lever I try on BT Public myself now. I will assume it was some weird freak desync issue on database's server (it had been happening for a while before that).

If it happens again I will reopen this issue (probably post-EA release though).
