### ISSUE TITLE
[Bug] Directional sonar cone is not visible

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#1472]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Poof, It's gone, now you can only aim it by looking at your ping direction, which is hardly useful.
The bug is present both in single- and multiplayer.

**Comment by rico6822** [comment]
Do you know how to potentially reproduce it?

**Comment by Waagher** [comment]
Start any round in version 0.9.0.1 and you will see that the cone is gone from the navigational terminals. The steps to reproduce the bug were not specified due to the fact, that it doesn't require any specific actions to be observed. A visual element of nav terminals is simply absent.
