### ISSUE TITLE
[Animations] Dislike animations

### ISSUE THREAD

**Issue by PicolasCage** [Regalis11/Barotrauma#1473]
animations too rigid, too structured, too soulless. I preffered old character procedural walking animations.

**Comment by PicolasCage** [comment]
Great response from the devs, keep it up!

**Comment by Regalis11** [comment]
It's a matter of taste, many people (the dev team included) prefer the more realistic animations and feel they fit the new artstyle better. I can definitely see the appeal of the old wonky animations too, but unfortunately we can't please everybody. Although, I wouldn't be surprised if after the Steam release someone created a mod that makes the animations more similar to the legacy animations (which would be quite easy to do with the new character editor).
