### ISSUE TITLE
More Detailed NPC Dialogues- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1475]
I have created a new conversation line myself to experiment with how much it can be detailed and I wonder if more conversations like it can be added to the game.

https://jumpshare.com/v/o48X78w2kbDad7c5Coq4

Jumpshare have converted this file the way it seems glitched but once you download it it will turn out that all the issues with how the strings are being set are removed and conversation works normally.

Edit: I just noticed I haven't used `</conversation>` enough but it's just a draft.

Here's an updated one: https://jumpshare.com/v/8DPo6myG0wvrLYwE89sF

**Comment by Regalis11** [comment]
Yep, we will definitely add more conversations, including longer ones. There's so few at the moment that it quickly becomes very repetitive. The example dialog you shared is alright, but to be honest it doesn't sound that natural (which is to be expected when not written by a native speaker, the dialog written by me needed quite a lot of proofreading too). We could add some similar traitor-related conversations in the future, but I think we'll go with ones written (or at least proofread) by the native English speakers of our team. Thanks anyway :)
