### ISSUE TITLE
Create NPC Dialogues Said Only By Characters With Specified Gender- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1476]
So they could say things like:

**Person 1 After Killing Mudraptor:** You fight like a woman. **Must be tough or rude to say it.**

**Person 2:** What the fuck you just said you little bitch?! **Must be a female captain to say it. Person 1 must be male. Occurs regardless of tension. Must be rude or tough.**

**Person 2:** No, you. **Must be a female captain to say it. Person 1 must be male. Occurs regardless of tension. Must not be rude or tough.**

**Person 2:** No, you. **Must be a female captain to say it. Person 1 must be male. Tension must be below 0.6 points. Must be professional to say it.**

**Person 2:** But you are a woman as well. **Must be both rude and male to say it. Person 1 must be female. Tension must be below 0.6 points.**

**Person 2:** I fell offended. **Must be female and person 1 must be male. Tension must be below 0.6 points.**

**Person 2:** Well this is ironical. **Must be female and person 1 must be female as well. Does not have to be rude. Tension must be below 0.6 points.**

**Comment by rico6822** [comment]
To all those confused about the bold text:

It is not a part of dialogue. It simply describes condition required to trigger a dialogue line.

**Comment by rico6822** [comment]
To all those confused about the bold text:

It is not a part of dialogue. It simply describes condition required to trigger a dialogue line. I put mudraptor in there as an example of a monster to be killed in order to make it occur.

**Comment by hubismal** [comment]
The dialogue you proposed seems a little bit rough, to put it lightly. I don't think we need gender based dialogue so that people can insult eachother. I think we could put slightly more casual seeming dialogue in the game with gender related subjects, but that being said, I'm having trouble thinking of any that aren't weird and/or out of place for the game. There's really no reason to bring up details about personal traits since the dialogue flows pretty nicely without it. 
The most sane usage of personal traits I can think of offhand would be using a character's race to have them talk about what country/culture they potentially came from back on earth and how they miss it, or the memories they have, but that also seems a little bit iffy because you might hear the same 8 origin stories over and over.
The only usage I can think of for gender based dialogue is using gender based descriptions of someone, like "that engineer jumpsuit is really pretty, it suits you nicely" or "that engineer jumpsuit looks really handsome", or really just pronoun extensions like calling someone a guy, or calling someone a gal, etc.

**Comment by rico6822** [comment]
> The dialogue you proposed seems a little bit rough, to put it lightly. I don't think we need gender based dialogue so that people can insult eachother. I think we could put slightly more casual seeming dialogue in the game with gender related subjects, but that being said, I'm having trouble thinking of any that aren't weird and/or out of place for the game. There's really no reason to bring up details about personal traits since the dialogue flows pretty nicely without it.
> The most sane usage of personal traits I can think of offhand would be using a character's race to have them talk about what country/culture they potentially came from back on earth and how they miss it, or the memories they have, but that also seems a little bit iffy because you might hear the same 8 origin stories over and over.
> The only usage I can think of for gender based dialogue is using gender based descriptions of someone, like "that engineer jumpsuit is really pretty, it suits you nicely" or "that engineer jumpsuit looks really handsome", or really just pronoun extensions like calling someone a guy, or calling someone a gal, etc.

The harsh example I gave is an example of what they possibly could say. They would also say thing like:

**Person 1:** I have a wife you know! **Said by a fearful male character when tension is above 0.5 points.**

**Person 2:** No one cares, we deal here with certain death right now! **Response by any professional or rude character.**

**Comment by rico6822** [comment]
> The dialogue you proposed seems a little bit rough, to put it lightly. I don't think we need gender based dialogue so that people can insult eachother. I think we could put slightly more casual seeming dialogue in the game with gender related subjects, but that being said, I'm having trouble thinking of any that aren't weird and/or out of place for the game. There's really no reason to bring up details about personal traits since the dialogue flows pretty nicely without it.
> The most sane usage of personal traits I can think of offhand would be using a character's race to have them talk about what country/culture they potentially came from back on earth and how they miss it, or the memories they have, but that also seems a little bit iffy because you might hear the same 8 origin stories over and over.
> The only usage I can think of for gender based dialogue is using gender based descriptions of someone, like "that engineer jumpsuit is really pretty, it suits you nicely" or "that engineer jumpsuit looks really handsome", or really just pronoun extensions like calling someone a guy, or calling someone a gal, etc.

The harsh example I gave is an example of what they possibly could say. They would also say thing like:

**Person 1:** I have a wife you know! **Said by a fearful male character when tension is above 0.5 points.**

**Person 2:** No one cares, we deal here with certain death right now! **Response by any professional, tough or rude character.**

**Comment by Regalis11** [comment]
I honestly don't see the need for this - I can't really think of why we would _need_ gender-specific lines. Sure, it's easy to come up with examples like characters talking about their wifes or calling someone handsome, but it's just as easy to word those lines in a way that gender makes no difference.
