### ISSUE TITLE
Achievement bug general

### ISSUE THREAD

**Issue by PicolasCage** [Regalis11/Barotrauma#1478]
Honkmother achievement is not unlocking despite wearing clown mask, clothes, and honking a horn in my hand.

Hilarious edit: After commiting suicide after fury by entering the ocean wearing a clown costume, I got the "No fun allowed" achievement. Commited suicide and got the achievement, lol.

Edit #2: Extravehicular activity achievement not obtained despite being 500m and more away from the sub

**Comment by Regalis11** [comment]
Fixed in eed0666

**Comment by Luckz** [comment]
Still does not work in MP, only SP.
