### ISSUE TITLE
[Audio] Weird Silence in loop of "Objective Complete.ogg"

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1479]
I meant to make this report a while ago but didn't. There's dead noise at the end of 12 - Objective Complete's ogg file, ruining the loop. It would be nice if it continually played as it's very akward right now hearing it pick up, go away, pick up, etc. because of some dead noise that could be trimmed.

**Comment by Regalis11** [comment]
You did make a report (#1460), and it was fixed in ac92260. :)

**Comment by hubismal** [comment]
bleaugh
