### ISSUE TITLE
Добавить ограничение частоты кадров в секунду. / Add rate limit in frames per second.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#148]
Мне, как пользователю который запускает сервер, хотелось бы ограничить ФПС в игре, чтобы вся мощность шла не на неё. В SCP эта функция есть. / Me, as user who starts the server, I would like to limit the FPS in the game, so all the power was not on it.  In the SCP, this feature is very useful.

**Comment by Regalis11** [comment]
This is not really possible in the same way as in SCP-CB, because the game uses fixed timesteps (and changing that would cause major problems with the physics and network syncing).
