### ISSUE TITLE
[Audio] [Composition Required] [Feature Request] More Music, and Make It Scarier

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1480]
This is a lot to ask, and the feasability of this might vary based on how AudireSound is being paid, but it would be nice if there were variations of the layers (like two different versions of leaving start location for example), as well as new layers for different situations. As I said in https://github.com/Regalis11/Barotrauma/issues/1456, the game sounds very samey at the moment, with the same songs playing for a situation every time, and the same tension songs taking up most of the playtime.
It would be nice if there were slightly different variations of "In The Ruins" based on whether you were under attack or not, or if your scooter battery is dying. It would also be nice if there were different alterations of "Objective Complete" or "Arriving at Destination" based on the type of outpost you're arriving at (this would be more relevant later when outposts actually look different based on a theme). Also, different monsters could use slightly different "Monsters Outside" variations, as right now only the endworm really have any audio cues just because high tension themes usually play.
Finally, some new situational tracks could be used. I assume because you've made the game, you know how nerve-wracking it is being trapped out in the middle of the ocean when the sub crew has forgotten you or sunk away without you, and your radio is dead and the scooter battery is dying. There should (imo) be a music track for being out in the water in a suit. You're tiny in the grand scale of things, and everything is pitch black. Getting lost in the ruins with [controlled chaos](https://www.youtube.com/watch?v=7_i840sJnMc) playing in legacy is what scarred one of my friends from ever going outside of the sub again (he said it was legitimately the most scared he's ever been in a video game). If AudireSound can pull of something like the creepy breathing noises and the really eerie droning that comes from slowing down controlled chaos percussion, you will have the disturbing "i'm-stuck-at-the-bottom-of-a-pitch-black-ocean" thalassaphobic edge that barotrauma really, really needs.
I hope this is really one of the feature requests you consider long after it has gone down to the bottom of the issue list.

**Comment by rico6822** [comment]
Regalis said that he wants Barotrauma not to be a horror game however he wants it to feature few horror elements such as music but not too scary as it would make some players quit playing the game or even make others stop playing the game as well.

**Comment by rico6822** [comment]
Regalis said that he wants Barotrauma not to be a horror game however he wants it to feature few horror elements such as spooky music but not too scary as it would make some players quit playing the game or even make others stop playing the game as well.

**Comment by hubismal** [comment]
I think having certain aspects of the game be scary is very appropriate. There should be very obvious "safe" zones where things are okay, but undesired situations (like being lost, in the ruins, etc) should require mental fortitude and not just be challenging gameplay wise, but psychologically as well.

**Comment by fabevil** [comment]
I have to agree with Hubismal here, while Barotrauma isn’t supposed to be a horror game, many aspects of it invoke fear in me, such as being in the pitch black ocean, being chased by monsters in the sub and in the pitch black ocean, seeing an Endworm or a Moloch (or a Charydbids or anything else), and being in the ruins. These are terrifying moments. The sub being breached by Monsters or a Husk Outbreak don’t invoke the same kind of fear as being in the Ruins or in the Ocean, far away from your Sub

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
