### ISSUE TITLE
Human Head issue

### ISSUE THREAD

**Issue by fabevil** [Regalis11/Barotrauma#1481]
So I was in the Character Editor and I saw this
![20190519195907_1](https://user-images.githubusercontent.com/50795742/57986129-358f7d00-7a71-11e9-9f33-fa276be69c16.jpg)

**Comment by rico6822** [comment]
Are you sure you haven't changed his head position accidentally?

**Comment by fabevil** [comment]
Nope

**Comment by hubismal** [comment]
Just FYI, in the same vein as https://github.com/Regalis11/Barotrauma/issues/1419.

**Comment by Regalis11** [comment]
Duplicate of #1419
