### ISSUE TITLE
Make It Possible To Create NPC Dialogues Speaking Out A Crew Member's Name- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1482]
So they could say things like:

**Person 1:** I used to be an captain like you but then I took a spear into the knee. **Randomly said by any moderately drunk joker character when tension is below 0.2 points.**

**Person 2:** Um Albert you should do something about yourself. **Response occurs only when Person 1 is already a captain. Tension below 0.2 points.**

**Person 1:** Know a joke. **Response to above Person's 2 response. Tension below 0.2 points.**

**Person 2:** Bullshit Albert, don't force me to fine you! **Response occurs only when Person 1 is not a captain. Tension below 0.2 points. Person 2 must be a captain.**

**Person 1:** Know a joke. **Response to above Person's 2 response. Tension below 0.2 points.**

**Person 2:** Good one! **Response occurs only when Person 1 is not a captain. Tension below 0.2 points. Person 2 must be a joker captain.**

**Person 2:** No, you. **Response occurs only after any "Know a joke." response. Tension below 0.2 points. Person 2 must be a captain.**

**Comment by Regalis11** [comment]
I have a similar stance on this as the gender-specific line issue (#1476) - I honestly don't see the need for this when lines like this could easily be reworded without including the name. And actually in this case including the names might potentially complicate things a lot. It'd be very easy to accidentally create sentences that are very hard to translate into other languages: for instance in French the gender of the character may change the rest of the sentence, and in many languages the name might have to be converted to a different grammatical case depending on the context in which it is used.
