### ISSUE TITLE
[Mac] [Translation/Text] [Issue] Mention all instances of F# key should have Fn+F#

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1485]
Mostly applies to the little message in the console that says "press f3 to toggle console". Confused mac users will open console press f3 (which won't work). If they've been using mac for more than a day they will use fn+f3, but it would be nice to just add this little detail as what currently displays is technically incorrect as fn is required for mac function keys.

**Comment by Regalis11** [comment]
This depends on how you've configured your function keys to work (not just on Mac but also on e.g. laptops), and I don't think there's a way for us to automatically detect how they're configured.
