### ISSUE TITLE
[Bug] Weld doors shut through walls

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1486]
Because of the increased range of the welding tools, players can weld doors shut through walls, as well as cut them open by the same reasoning. Not sure if this is intentional or not, if it's intentional you can just close the issue.
edit: if it is a feature i'd argue it's a little unfair to trap someone in a room through a wall without them even knowing

**Comment by Regalis11** [comment]
Welding through walls is intentional (the intention was to make it easier to repair walls in spots where walls overlap), but now that the range of the welding tool has been increased, it had this unfortunate side effect. Will take a look at fixing this.
