### ISSUE TITLE
Добавить разделение чата для хоста. Add split chat host.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#149]
Можно добавить разделение чата для хоста, но, возможно, появятся у Вас какие-нибудь идеи для обычных пользователей? Просто мне постоянно приходится отвечать на некоторые вопросы мёртвых. Иногда это касается игрового процесса и мешает живым.
You can add split chat to host, but might You have any ideas for the average user? I just constantly have to answer some questions of the dead. Sometimes it goes for the gameplay and prevents alive.
![image](https://user-images.githubusercontent.com/33912761/33957305-50380ccc-e052-11e7-827d-9c702b68de8b.png)

Можно добавить это как дополнительное право для выдачи игрокам.
You can add it as an additional right to issue players.

**Comment by Crystalwarrior** [comment]
There's already pming in the game actually.
If you do (nickname) ; (msg) it will send a pm to them.

**Comment by NilanthAnimosus** [comment]
r; radio; = radio
d; death; = death chat
name here; = Private Message (Clients may use this during the lobby).

clients have private messaging disabled while in-game, and do not have a method to private message the host, I suppose a method to PM the host from a client (Regardless of a round running) would be nice though, if I am understanding this correctly.

**Comment by CryIz** [comment]
Я не знал об этих командах. Может тогда добавить какую-нибудь подсказку об этом в игре? Честно, впервые вижу это. Спасибо.
I didn't know about these commands. Then maybe add some hint about this in the game? Honestly, I've never seen these team. Thank you.
