### ISSUE TITLE
[Text/Translation] Killing a swarm mission uses a bad fill-in-the-blank

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1490]
Mission description at round start: Instead of saying "A swarm of Crawlers" killing a swarm says "A swarm of [monster]"

**Comment by Regalis11** [comment]
Which version/language is this? That line is not present in any of the texts in the swarm mission in the latest version. The English description is "A small swarm of crawlers has been terrorizing vessels traveling between [location1] and [location2]. A reward of [reward] credits has been promised to any crew who can neutralize it."

**Comment by Regalis11** [comment]
Nvm, found the issue. We had the mission description included twice in the texts, and only the second line had this error.

**Comment by Regalis11** [comment]
Fixed in v0.9.0.3
