### ISSUE TITLE
[Scaling/Resolution] [Bug] Wiring Interfaces don't scale properly with resolutions.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1492]
A picture is worth a thousand words:
![2019-05-20-201036_440x376_scrot](https://user-images.githubusercontent.com/47284081/58061391-91263d00-7b3b-11e9-8d9f-4ca43608ac41.png)
not so severe when on higher resolutions. this particular scrshot is of the lower resolutions.
sorry for the rushed nature of these reports, I'm trying to get as many bad bugs in before release.

**Comment by Rokvach** [comment]
Tested between 2k and the lowest possible resolution and seems to be displaying correctly now, closing.
