### ISSUE TITLE
Was That Intended For Welding Tool To Deal So Much Damage?

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1495]
The crew member in this video killing molochs with welding tool is the ship's captain so his weapons skill is high but mechanical is pretty low.

https://www.youtube.com/watch?v=5mE2JEiAjLQ

Skip to 8:33 and 10:38.

**Comment by Rokvach** [comment]
Recent nerf fixed this issue. Tested, closing.
