### ISSUE TITLE
Minor Mistake In The Game's Credits

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1496]
My username is written with capital number while it is not.

Don't get me wrong, besides of everything I still enjoy the fact that I was being mentioned for my github activity in here for Barotrauma.

**Comment by Regalis11** [comment]
Just to make sure, it should be "redeloper “rico6822”" instead of "Redeloper “rico6822”"?

**Comment by rico6822** [comment]
> Just to make sure, it should be "redeloper “rico6822”" instead of "Redeloper “rico6822”"?

Write:
rico6822 (Redeloper)

**Comment by rico6822** [comment]
> Just to make sure, it should be "redeloper “rico6822”" instead of "Redeloper “rico6822”"?

Write:
Redeloper (rico6822)

**Comment by Regalis11** [comment]
Fixed in 0.9.0.1
