### ISSUE TITLE
Stun Baton Allows You To Teleport Crew Members One Floor Below- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1497]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stun Batons in Barotrauma can make other crew members glitch out into another place.

**Steps To Reproduce**
0:22 https://www.youtube.com/watch?v=ytTmid_J9qY

**Version**
Video was uploaded on April 8 2019.

**Comment by Regalis11** [comment]
Could not reproduce in the latest version, I think the ragdoll syncing fixes in the past few versions took care of this.
