### ISSUE TITLE
Добавить выносливость. / Add endurance.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#150]
По субмарине постоянно бегают какие-то дурачки. Можно добавить выносливость.
As the submarine can continue to run some fools. You can add endurance.
P.S. я не видел на гитхабе такой идеи. Заранее извиняюсь, если уже было предложено что-то такое.
I saw on github this idea. I apologize in advance if it was already proposed something.

**Comment by Regalis11** [comment]
I don't really see the benefit of this, it'd just make movement more cumbersome.
