### ISSUE TITLE
Condition Composer- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1500]
Condition composer is a device allowing the player to compose same items with different condition into 1. Composing 2 items with 25% of condition will result in same item but with 50% condition. This could be used to make morbusine antidote whole.

**Comment by hubismal** [comment]
I'm a little skeptical about this. The only real use this would have is putting together 2-dose medicines like what you mentioned for the sake of inventory space, as well as batteries, which already have recharging stations, and tanks, which already have respective refillers.

**Comment by Regalis11** [comment]
I agree with hubismal, I don't think we should implement a completely new device for such a niche purpose. Even more so when the only practical use for this would be to combine partially used medical items and crafting materials, which can already be combined by simply dragging them into the same slot.

**Comment by rico6822** [comment]
> ...which can already be combined by simply dragging them into the same slot.

I didn't knew that.
