### ISSUE TITLE
[Bug] Sonar transducers do not work on the main submarine.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#1504]
- [x] I have searched the issue tracker to check if the issue has already been reported.

I took a stock Humpback, placed a sonar transducer outside it's hull and a shuttle nav terminal inside, everything was powered and connected correctly in my estimation and the nav was set to "Use transducers" as well. However, when used, the shuttle terminal still showed the middle of the submarine hull at the centre of the screen, instead of the transducer's position, as I imagine it should. This was not the case in previous versions, where the transducer's location was at the 0,0 coordinates, when connected to a terminal. 
It still works correctly, for the Remora's shuttle, but I see no reason why transducers shouldn't work with the main submarine.

**Comment by Regalis11** [comment]
This is intentional. The sonar display always focuses on the center of the submarine the signals are coming from, regardless of the actual position of the transducer.
