### ISSUE TITLE
[Steam Version][BUG] AI Bots ignore the "lockHands" parameter

### ISSUE THREAD

**Issue by Splaxiom** [Regalis11/Barotrauma#1505]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The AI can freely ignore the "lockHands" parameter. Mostly, it allows AIs to Houdini their way out of Handcuffs.

**Steps To Reproduce**
Stun an AI bot, and Handcuff it. Then anger it by hitting it (may require the bot to have a suitable weapon eg. Crowbar). The angry bot will remove it's Handcuffs to beat you up 

**Version**
Windows 10. On the latest Steam version, 0.8.10? in the latest version of the development branch.

**Additional information**
No idea about possible further implications of this bug, it doesn't disturb normal gameplay since bots are very good boys

**Comment by itchyOwl** [comment]
Already fixed? Probably need to ensure that works in all cases.

**Comment by Splaxiom** [comment]
I just tested it in the newly deployed Update (and the [development] beta), AI bots still ignore Handcuffs, and they outright unequip them as soon as they recover from stunning

**Comment by Regalis11** [comment]
@Splaxiom The changes weren't been included in the recent patch yet (v0.9.0.6), but will most likely be in the next one.

**Comment by Rokvach** [comment]
Tested by handcuffing all my AI crew in a singleplayer mission and tried to drown them/order them around to operate different devices. None of them were able to leave the handcuffs no matter what I did to them. So seems to be working correctly, closing.
