### ISSUE TITLE
Game doesn't load during splash screens on linux

### ISSUE THREAD

**Issue by JJRcop** [Regalis11/Barotrauma#1507]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Launching the game on Linux does not load the game in the background while the splash screens are playing.

**Steps To Reproduce**
Prerequisites: Linux version.

1. Launch the game
2. Wait for splash screens to finish, or skip at any point.
3. Loading will start at 0%

**Version**
v0.9.0.4 Linux

**Additional information**
This does not happen on v0.9.0.4 Windows, only the Linux version. Observing my Linux equivalent to Task Manager reveals that disk and memory usage for the process rise only after the splash screens are complete.
On Windows the memory and disk usage rises similarly while the splash screens are playing, indicating loading.

**Comment by hubismal** [comment]
It used to do this during the splash screens on linux but I think because of the nature of the way linux loading works on OpenGL, the videos would stutter pretty badly. They probably removed this to make the videos play smoothly due to threading.

**Comment by JJRcop** [comment]
After taking a look it seems this is intentional
https://github.com/Regalis11/Barotrauma/blob/405cdf63a308f4339bdf7fbbbebab3266c983a66/Barotrauma/BarotraumaClient/Source/GameMain.cs#L279-L281
