### ISSUE TITLE
Don't allow putting handcuffs on yourself

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1509]
Funny for the first time it happens, but way too easy to do by accident

**Comment by thegrb93** [comment]
I like it. The more freedom the better and could be useful when RPing

**Comment by thegrb93** [comment]
I think the gun should also be able to shoot yourself in the head. Go down with the ship style

**Comment by thegrb93** [comment]
I just realized with the current inventory, it is probably too easy miss the number key you're aiming for. I'm still used to the alpha style one.

**Comment by thegrb93** [comment]
Perhaps holding the cuffs doesn't actually put them on unless you use them? Idk, you decide.

**Comment by hubismal** [comment]
I strongly disagree with this request. It shouldn't require a buddy for you to handcuff yourself. What would be better is some kind of prompt or just making it harder to do.

**Comment by ZealanL** [comment]
Cuffing yourself is often intentional and definitely vital to RP as thegrb93 said. If you're playing legacy, picking them up with an almost-full inventory will cause them to go onto your hands, but this isn't a problem in the Steam alpha.

**Comment by itchyOwl** [comment]
Not sure about the necessity of being able to handcuff yourself. Why is it so important? At least we'll need to make it harder to do so by mistake. Need to redesign and implement the whole handcuffing thing anyway. Maybe equip the handcuffs and then click a target to use them? And if we really want to enable handcuffing yourself, let's add an extra key/button for it.

**Comment by thegrb93** [comment]
@Regalis11 @itchyOwl 

For my idea of revolver suicide.
![Untitled](https://user-images.githubusercontent.com/6713261/59154623-5fbad600-8a44-11e9-8611-d3ccd48b0493.png)

**Comment by thegrb93** [comment]
Wrong pic at first, edited

**Comment by ezjamsen** [comment]
Let's do it as itchyowl suggests: Equip the handcuffs in one of your hands, and then use on a target to cuff them, target may include self.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1489](https://github.com/Regalis11/Barotrauma-development/issues/1489) via [**ZenHub**](https://www.zenhub.com/)
