### ISSUE TITLE
Баг со спавном чудовищь. / Bug with the creation of the monster.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#151]
Moloch? Carrier? Может бать Charybdis? Ну честно, игра только началась, а эти существа уже уничтожают субмарину. Я не знаю о том, было ли это сделано специально или это ошибка.
Moloch? Carrier? Can be Charybdis? Well, honestly, the game has just begun, and these creatures have already destroyed the submarine. I don't know whether this was done deliberately or it was a mistake.
![image](https://user-images.githubusercontent.com/33912761/33959986-46fb042c-e05a-11e7-9e39-105883dafaaa.png)

**Comment by Regalis11** [comment]
There should be some logic in place to prevent this from happening, but apparently it's bugged. If you (or anyone else) have a seed where this happens please post it!

**Comment by CryIz** [comment]
CwOTsUR7 or Cw0TsUR.

**Comment by Regalis11** [comment]
Ah, I need to also know the submarine you were using with those seeds because the size of the submarine affects the layout of the level (and the placement of monster spawnpoints). If it's the one in the screenshots, do you know where I could download it?

**Comment by CryIz** [comment]
Это "Aegir Mark X", который я немного изменил. This "Aegir Mark X", which I slightly changed.
Скачать/Download: https://drive.google.com/open?id=10Wv7DsdKFETTnKY1R2Ckgmei0_s8Zc8G

**Comment by Crystalwarrior** [comment]
This is a duplicate issue but: https://github.com/Regalis11/Barotrauma/issues/62
Been happening for a while now
