### ISSUE TITLE
[0.9.0.2] Unable to start server.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1510]
**Description**
I tried to run the server through "Dedicated_Server" and the game itself, but to no avail. 
CrashReport is not created.
![oh shit here we go again](https://user-images.githubusercontent.com/33912761/58764655-85426e00-8572-11e9-968f-36229f92f0ab.png)

**Version**
0.9.0.2. Steam. Windows 10.

**Comment by 0ArturkA** [comment]
Try start with admin rights
