### ISSUE TITLE
[Balancing] Ancient Weapon is the Opposite of a weapon. Alien guns are somewhat broken.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1512]
The ancient weapon tears through hulls at light speed, while it does less damage than a welder to actual monsters.
The alien pistols are beyond useless, they're like weird single fire welders.

**Comment by Regalis11** [comment]
Rebalanced ancient weapon in https://github.com/Regalis11/Barotrauma-development/commit/fc3c772d02bc2664fec4d3cb4f9ebc60cba36411 (private repo)

**Comment by Rokvach** [comment]
Tested, don't see any issues with this. Closing.
