### ISSUE TITLE
Max player dosent count

### ISSUE THREAD

**Issue by NortonDK** [Regalis11/Barotrauma#1514]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When hosting a server as a client, the max numbers of players can be exeeded

**Steps To Reproduce**
Create a regular server with the client(not dedicated) and set the max players to something like 5, but more than that number can join

**Version**
Latest steam at this date and time

**Additional information**
People on discord have also noticed this bug

**Comment by jsomm** [comment]
Having this same issue.
