### ISSUE TITLE
Just bought Barotrauma on steam. Crashes on launch.

### ISSUE THREAD

**Issue by Tpaypp** [Regalis11/Barotrauma#1515]
I have searched the issue tracker to check if the issue has already been reported.

Just bought the game and it crashed instantly. Error window tells me that game crashed and report was made and sent. I think that bug/crush code is 
84D97A22415E79CF8C19BAAC1D6B11B5 

I tried to reinstall a game and launch with different compatibility modes and in windowed mode.

Full text of my second crush report  here on in file: 

Barotrauma Client crash report (generated on 05.06.2019 22:16:47)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

84D97A22415E79CF8C19BAAC1D6B11B5

Game version 0.9.0.4
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    Game not initialized

Exception: Ссылка на объект не указывает на экземпляр объекта.
Target site: Void Dispose(Boolean)
Stack trace: 
   в Microsoft.Xna.Framework.Graphics.Effect.Dispose(Boolean disposing)
   в Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose()
   в Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(Boolean disposing)
   в Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(Boolean disposing)
   в Microsoft.Xna.Framework.Game.Dispose(Boolean disposing)
   в Microsoft.Xna.Framework.Game.Dispose()
   в Barotrauma.Program.Main() в E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:строка 84

Last debug messages:
[05.06.2019 22:16:16] Unknown SharpDX exception code (887A0005)
[05.06.2019 22:16:16] SharpDX exception caught. (HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown, 887A0005). Attempting to fix...
[05.06.2019 22:16:16] Loading texture "Content/Effects/waterbump.png" failed! {HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown}
   в SharpDX.Result.CheckError()
   в SharpDX.Direct3D11.DeviceContext.MapSubresource(Resource resourceRef, Int32 subresource, MapMode mapType, MapFlags mapFlags)
   в SharpDX.Direct3D11.DeviceContext.MapSubresource(Texture2D resource, Int32 mipSlice, Int32 arraySlice, MapMode mode, MapFlags flags, DataStream& stream)
   в SharpDX.Direct3D11.DeviceContext.MapSubresource(Resource resource, Int32 subresource, MapMode mode, MapFlags flags, DataStream& stream)
   в Microsoft.Xna.Framework.Graphics.Texture2D.PlatformGetData[T](Int32 level, Int32 arraySlice, Rectangle rect, T[] data, Int32 startIndex, Int32 elementCount)
   в Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](T[] data)
   в Barotrauma.TextureLoader.PreMultiplyAlpha(Texture2D& texture) в E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\TextureLoader.cs:строка 102
   в Barotrauma.TextureLoader.FromFile(String path, Boolean preMultiplyAlpha) в E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\TextureLoader.cs:строка 68

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/3258813/crashreport.2.log)

**Comment by thegrb93** [comment]
Probably your graphics device doesn't meet minimum requirements, or bad drivers.

**Comment by LittleOrangeBottle** [comment]
https://www.microsoft.com/en-ca/download/details.aspx?id=36805

Try installing this if you're using Windows 7

**Comment by itchyOwl** [comment]
Here's another one: [crashreport_23.log](https://github.com/Regalis11/Barotrauma/files/3267349/crashreport_23.log)

Also found an older crash log (pre release): https://pastebin.com/pegdWBBW

Similar issues (with the same error code) in other projects:

https://github.com/CnCNet/xna-cncnet-client/issues/27

http://community.monogame.net/t/dxgi-error-device-removed-error-solved/7737

Could be helpful: https://docs.microsoft.com/en-us/windows/desktop/direct3ddxgi/dxgi-error

It seems that reinstalling drivers, directx or .net doesn't solve the issue.

**Comment by itchyOwl** [comment]
I think a bad gpu/drivers could cause it, but as we see from the other logs, the issue manifests also on relatively good gpus.

**Comment by Regalis11** [comment]
Related: https://github.com/MonoGame/MonoGame/issues/6265

**Comment by Rokvach** [comment]
This issue is caused because your Windows 7 doesn't fully support all the DirectX 11 features, you would need to update your Windows 7 to a later version. 

You can find a guide on how to do it from our known issues section of the roadmap found here

https://trello.com/c/zFFUsENK/163-crashing-on-launch-when-trying-to-start-the-game-using-windows-7-workaround-included

Closing this issue as it would require us to go back to supporting DirectX 9 in order for this to be fixed.

**Comment by extremecodetv** [comment]
Same problem in Windows 10 and RTX 2060 GPU.
GPU Driver version: 436.48
Windows 10 version: 1903

Game in main menu loads gpu in 100%, then game crash and also it can crash all soft or operating system

log files included:
crashreport.log
https://gist.github.com/extremecodetv/eb0532acdf83a62a25be259c1773d0d1

crashreport (2).log
https://gist.github.com/extremecodetv/618688d4ba77293403613d449e6398e1

there are no problems with hardware. problem exists only with this game
reinstallation of windows or gpu driver did not give any results.
