### ISSUE TITLE
The round end screen doesn't get displayed

### ISSUE THREAD

**Issue by v5844** [Regalis11/Barotrauma#1518]
**Description**
I get this error every time a round ends:
![image](https://user-images.githubusercontent.com/46109571/58993090-d3fb3c80-87ec-11e9-9070-1d7e34ccf8e0.png)

**Steps To Reproduce**
Wait for the round to end.

**Version**
Linux

**Comment by NilanthAnimosus** [comment]
I've had this twice (or very similar to it) as a windows client on some servers, I do not know why and it occurs rarely. I would say 5-10% of games.

I believe its when husked players die and convert in my case however, which causes a different bug where a character doesn't exist. I'll quickly enclose it here:

![image](https://user-images.githubusercontent.com/29177976/59087679-48bd9c00-88fd-11e9-9f21-717fbeceed34.png)


It then never goes to the lobby screen as additional information, so I can only assume I actually got disconnected (Yet I still hear the lobby chat - its quite odd, like stuck being in game).

**Comment by itchyOwl** [comment]
Should be fixed in the dev repo?

**Comment by v5844** [comment]
@NilanthAnimosus You're probably right about it being related to husks, + A couple players on my server told me it happens when people are messing around with husk eggs

**Comment by Regalis11** [comment]
Fixed in bea7b58 (the changes in RoundSummary.cs)

**Comment by Rokvach** [comment]
This issue has already been tested and proven to be working correctly, closing.
