### ISSUE TITLE
[bug]? maybe intentional? dead players(which includes ADMINS) can't hear voice chat of living players

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1519]

**Comment by Kei-Shin** [comment]
This is annoying since admins can't truly spectate the game and get a better idea of whats going on since they lack a whole level of communication that can only be can be gained by being alive.

**Comment by Regalis11** [comment]
Fixed in dd92074

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
