### ISSUE TITLE
"Прыгающая" субмарина. / "Jumping" submarine.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#152]
Субмарина может "подпрыгивать" на шаттле или трупах существ.
The submarine can "bounce" on the Shuttle or the corpses of the creatures.
![bounce](https://user-images.githubusercontent.com/33912761/33961237-5ded2706-e05e-11e7-9528-6045a3915808.gif)

**Comment by IDPixel** [comment]
Бедный шаттл) / Suffering shuttle)
