### ISSUE TITLE
Can't use FIPS compliant algorithms setting (Windows Local Security Policy) when hosting.

### ISSUE THREAD

**Issue by DARKDEAD** [Regalis11/Barotrauma#1520]
Game version 0.9.0.4
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit

Exception: Адресат вызова создал исключение.
Target site: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
Stack trace: 
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   в System.Security.Cryptography.MD5.Create()
   в Barotrauma.GameAnalyticsManager.Init() в E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\GameAnalyticsManager.cs:строка 34
   в Barotrauma.GameMain..ctor(String[] args) в E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\GameMain.cs:строка 90
   в Barotrauma.Program.Main(String[] args) в E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Program.cs:строка 33

**Comment by DARKDEAD** [comment]
![image](https://user-images.githubusercontent.com/1481677/59012659-1ce0de80-8849-11e9-800a-e949c5ef8b50.png)

**Comment by DARKDEAD** [comment]
fix error:
 “go to Local Security Policy (Start -> Run -> secpol.msc) and then go to “Security Settings -> Local Policies -> Security Options” and on the right-side windows you should see the policies in that please look for the Policy “System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing” and checked the security thing and it should be Enabled.”

**Comment by itchyOwl** [comment]
Yes, it seems that you have to disable FIPS compliant algorithm setting if you want to host a server for now, because we are using System.Security.Cryptography.MD5 hash.

We might make a custom implementation for it at some point. Thanks, for the testing and the working fix for it, DARK :D I quess you'd have to manually enable that setting or have an application to enable it for you. By default, it should be disabled (I think).

So if anyone has this issue, follow the steps given above.

**Comment by itchyOwl** [comment]
Removed bug and crash tags, because it's not a crash, since the exception is handled and because it's not a bug, but a limitation.
