### ISSUE TITLE
Campaign issues

### ISSUE THREAD

**Issue by v5844** [Regalis11/Barotrauma#1521]
**Description**
Every time I set up a new campaign on my server I get this error:
![image](https://user-images.githubusercontent.com/46109571/59038300-1bc4a700-8873-11e9-9a94-e0a6f445a361.png)
The server is trying to create save files in .local/share/Daedalic Entertainment GmbH/Barotrauma, even though it doesn't exist.

**Steps To Reproduce**
Run a server from a machine with no .local/share/Daedalic Entertainment GmbH folder

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by igormusinov** [comment]
How was it resolved ?

**Comment by v5844** [comment]
I thought it wasn't a problem with the game, just my setup, closed it. Someone made the issue again in #1564 though.
