### ISSUE TITLE
[bug] Voice chat volume resetting on launch

### ISSUE THREAD

**Issue by Nimowa** [Regalis11/Barotrauma#1523]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you change the voice chat volume and then close the game, the volume level resets.

**Steps To Reproduce**
Open the game, change the voice chat volume, close the game and then open again.

**Version**
v0.9.0.4

**Additional information**
I tried adding configs to try and fix it, but that didn't work. You should also really raise the default voice volume, since even sonar pings can drown people out.

**Comment by itchyOwl** [comment]
Couldn't reproduce this. Did you press apply? We should probably add a popup if you have unsaved settings when you exit the settings.

**Comment by Nimowa** [comment]
I'm absolutely sure I pressed apply, since every other setting has stayed where I set it. I mentioned earlier that I tried to add configs to fix it, since there wasn't any for voice volume when I checked it. This was the case for both config files. I'm guessing this is the reason why it's not saving that setting.

**Comment by itchyOwl** [comment]
Oh yes, sorry. I tested on another build where it's fixed already.
