### ISSUE TITLE
Extremely Loud when starting game

### ISSUE THREAD

**Issue by spicybabe** [Regalis11/Barotrauma#1525]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The music when starting up the game for the first time was so loud it made me partially deaf. 

**Steps To Reproduce**
Please don't do this to your new gamers.

**Version**
irrelevant 

**Additional information**
Please, I don't want to be perma deaf for the rest of my life over things like this. I had to throw off my headphones to save myself.

**Comment by OverwatchVoice** [comment]
Does this happen with other software? Maybe your overall volume is set too high, and you compensate for that by lowering the volume in the applications themselves.
You're better off with a lower overall volume.

**Comment by Regalis11** [comment]
@OverwatchVoice I believe this refers to the splash screens, which are too loud compared to the rest of the audio (the Daedalic one in particular). Should be fixed in 39a9e1c
