### ISSUE TITLE
Odd syncing issues and timing issues with deconstructor (And possibly fabricators)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1526]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I was trying out the game in multiplayer, didn't encounter too many critical bugs in mission mode but I did notice an irregularity when crafting and started getting paranoid of it pretty fast.

Lets say two people run to the deconstructor - one adds a carbon rock, the other a poppy plant. and then another player runs it (Say, the first) perhaps before the plant was added, or during/slightly after starting im not too sure.

It appears as if both go through the GUI input, yet you get only the outputs of one of the two items, the other isn't on the floor, or visibly anywhere and just seems to have ceased to exist. I saw this with the above and when two poppy plants were added as well and have started only using a deconstructor one input at a time. 

Additionally, the deconstructor has a tendancy to instant-craft after its first craft and appears to have unusual timing issues.

**Steps To Reproduce**
deconstruct multiple items, possibly added by multiple players at similar times.

Deconstruct multiple items one at a time in sequence for 'instance deconstruction) - typically medical plants or certain rocks.

**Version**
0.9.0.4 - Windows 7 64bit - client connected to server.

**Comment by Rokvach** [comment]
Tested, this is working correctly now. Closing.
