### ISSUE TITLE
Containing jumpsuits in jumpsuits, access cards can't be contained in doctor's clothes

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#153]
1. Можно создать бесконечный инвентарь таким образом. Я уже знаю как это исправить, но лучше этим займётесь Вы :). 
You can create endless inventory that way. I already know how to fix it, but let me handle You :).
![endless](https://user-images.githubusercontent.com/33912761/33961533-7b2dab1e-e05f-11e7-9b79-51257c5d8dd5.gif)
P.S. на скриншоте виден ник игрока, которого я, по сути, не вижу. Это можно приписать к недоработке?
in the screenshot see the nick of the player I, in fact, do not see. This can be attributed to the defect?

2. В штаны медика нельзя положить карту доступа. Согласитесь, это немного глупо.
In the pants of a doctor can not put an access card. Agree, this is a bit silly.

**Comment by NilanthAnimosus** [comment]
Fixing this (In the immediately simple method of removing the tag smallitem) would prevent this item from ever being stored in any cabinets, and modifying how it currently won't effect most existing submarines I believe as their tags would already be set and saved into the submarine file.

**Comment by Regalis11** [comment]
Fixed in the dev branch
