### ISSUE TITLE
Balance inconsistency of antibleed items "plastiseal" and "antibiotic glue"

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1530]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The tier 2 and tier 3 anti bleed are completely imbalanced now and could use some tweaking.

**Tier 2 anti bleed "Plastiseal" (20 medical skill):**
- you get 4 uses when successful for 35 bleed/burn, on 4 limbs, over 5 seconds for a total of 140.
- on failure, the repercussions are none existent, and the low skill makes it hard to fail, bleed/burn heal to 30, for a total heal of either 60 or 90 points (2/3 uses if you fail only once, even if the last use is a fail at 25% condition).
- Quite simple and cheap to craft, just a bandage (1 fiber) and elastin, each plant giving 3 each. at least.

**Tier 3 anti bleed "Antibiotic glue" (70 medical skill):**
- Doctors can fail with this at their typical starting skill levels, making it one of the most difficult medicals to use.
- you get 2 uses when successful for 60 bleed/burn, on 2 limbs, over 8 seconds for a total of 120.
- On failure you only get a single of use for 30 bleed/burn, on 1 limb, over 8 seconds.
- Failure additionally damages the target for 15 internal damage.
- it is complicated to craft, and by that logic quite expensive to craft, since it also takes elastin along with 2 other ingredients it is definitely costlier than plastiseal.

I think to balance this well, personally I would have glue take 5 or 6 uses (20% condition) where failure doubles or triples the usage, given the comparable cost and danger. failure should better seal the wounds slightly.

Personally I would modify it to this:
- 5/6 uses for 40 bleed/burn, thus up to 5/6 limbs, over 10/16/20 seconds. this may heal 200/240 total, though is slower and can be better spread and more guaranteed to single-use heal an injury. or double/triple used to heal a critical injury faster.
- Increase the penalty of failure to 20-25 internal damage, but keep the gain at 30 for bleed/burn.
- Modify usage % penalty to 2x-3x (40% / 60% equal to 2-3 usage costs) on failure.
- Keep crafting requirements at 70, but decrease usage medical skill to 60 or 55 so its usable by doctors, a little risky for security, and a total bad idea for everyone else.

**Version**
0.9.0.4 steam

**Comment by Regalis11** [comment]
Ping @ezjamsen

**Comment by ezjamsen** [comment]
Correct you are. The numbers in general for most medical items will be iterated when time allows since it can often feel a bit flimsy as things stand now. As a stopgap solution, I will test your suggestion (which looks basically right) and see how it works in practice, the med skill requirement especially is something to be dropped.

**Comment by ezjamsen** [comment]
Rebalanced. @Rokvach I tested it myself, but can you validate that I've not screwed it up somehow...

**Comment by Rokvach** [comment]
I don't see any further issues in this, closing.
