### ISSUE TITLE
Making copy of item

### ISSUE THREAD

**Issue by KnightRUS** [Regalis11/Barotrauma#1532]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is some conditions to copy item

**Steps To Reproduce**
When i look at reactor control screen (2 urans in it) i take uran element with mouse1 and do not put it. Then an explosion of reactor hapend. i fall on the floor (reactor screen disapeared). so i have uran in hand and i have uran in reactor

**Version**
windows 9.0.4

**Additional information**

**Comment by Regalis11** [comment]
Sorry but I don't quite understand what the problem is. There were two fuel rods in the reactor, you took one out, and the result was that there was 1 rod in the reactor, 1 in your hand?

**Comment by KnightRUS** [comment]
Sorry I messed up. Here is how it was. 2 rods were in the reactor. While I was getting one rod, an explosion occurred. I fell and left 2 rods in the reactor and 1 in hand.


>Понедельник, 10 июня 2019, 13:57 +05:00 от Joonas Rikkonen <notifications@github.com>:
>
>Sorry but I don't quite understand what the problem is. There were two fuel rods in the reactor, you took one out, and the result was that there was 1 rod in the reactor, 1 in your hand?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Евгений Загребельный
pc-sux@mail.ru

**Comment by KnightRUS** [comment]
i cant repeat the error in 9.0.5. Now the reactor explodes very much and kills a person. The number of rods remains correct
