### ISSUE TITLE
Motion sickness camera

### ISSUE THREAD

**Issue by Themodem** [Regalis11/Barotrauma#1535]
**Feature Request**

Having the ability to turn the bobby follow camera off so that the camera is mostly static would go a long way in helping people with motion sickness be able to play the game.

The current camera is too close into the character and bobs around with the character ragdoll.

**Comment by Regalis11** [comment]
You can turn off the camera movement by unchecking "Enable mouse look" in the game settings.

**Comment by joseph-zhong** [comment]
Thanks for the awesome game!

This really should be default -- the movement is pretty disorienting just upon opening the game
