### ISSUE TITLE
The two submarines in combat gamemode have their respective docking ports highlighted no matter what.

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1536]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The docking ports on each other's submarines in the combat gamemode (PvP) are fully visible, highlighted in green, even with the sonars off!

**Steps To Reproduce**
Simply play the gamemode, get two of the subs close together, turn off the sonar.
**Version**
Windows 10.   Game ver. 0.9.0.4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
