### ISSUE TITLE
It is impossible to enter the server because of the ban list.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1538]
**Description**
On the server it is impossible to go, if the ban list is the player with the lock. We have to remove, and then they come back and spoil the game...
![image](https://user-images.githubusercontent.com/33912761/59146702-19d92000-89fa-11e9-8478-098e9582d98b.png)

OS: Windows Server 2016 (RUS)

**Comment by Nevol2110** [comment]
Also constantly players can not connect because of the "Timed out". Even in the queue you can not get up, but even funnier is that there are still two free slots.
https://cdn.discordapp.com/attachments/534702210240479233/586881712827531284/unknown.png

**Comment by databasetd** [comment]
Can confirm this, banning does not input the players' SteamID.
https://i.imgur.com/m4YJVgo.png

**Comment by Regalis11** [comment]
Fixed in 4465394
