### ISSUE TITLE
Баг с Carrier. / Bug with Carrier.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#154]
Этот баг давний, но его так и не починили. Когда он умирает, его "фонарь" ведёт себя странно.
This bug is old, but it was never fixed. When he dies, his "light" behaves strange.

![carrier](https://user-images.githubusercontent.com/33912761/34013002-eb2583e8-e126-11e7-9094-4f3792158a85.gif)

**Comment by Regalis11** [comment]
Could not reproduce

**Comment by CryIz** [comment]
Ближе к вечеру постараюсь гиф сделать. Я только с пар пришёл. Toward evening I will try to do GIF. I only came in pairs.

**Comment by CryIz** [comment]
![carrier](https://user-images.githubusercontent.com/33912761/34012965-c6a2c274-e126-11e7-990e-4d7375394115.gif)

**Comment by CryIz** [comment]
Обновил.
Updated.

**Comment by Regalis11** [comment]
Thanks for the gif, now I think I know what's causing it. The light is attached to a separate "dummy limb", and killing the carrier with the railgun severs the limb and causes it to fly off. Should be quick and easy to fix.
