### ISSUE TITLE
Cannot host a server (port-forwarding was set)

### ISSUE THREAD

**Issue by igormusinov** [Regalis11/Barotrauma#1541]
I read all manuals about hosting a server (on github/steam and official site). I tried these things:

- port-forwarding (for 27015 and 27016 ports, for TCP/UDP, for my true local ip)
- enable UPnP on my router and in the server config
- checked firewall for accessing barotrauma packages. And even tried to disable it.

I can see barotrauma service in NAT traversal table of my router. I can join my own server with local ip 192.168.1.64, but **I can't connect with my public ip**. 

OS - Windows 10
Game Version v0.9.0.4

**Comment by v5844** [comment]
Can other people use the public IP to connect?

**Comment by igormusinov** [comment]
for 1 hour nobody connected me. I think , no.

**Comment by v5844** [comment]
You can always check on https://canyouseeme.org

**Comment by igormusinov** [comment]
Nice site. I can't see my service on 27015 or 27016. Can you see yours ?

**Comment by Nevol2110** [comment]
Как я понял, ты русский. 
Значит это уже с провайдера про порты спрашивай. Некоторые их закрывают специально и могут открыть бесплатно по заявку, а некоторые денежку просят. 

So it is with the ISP about ports ask. Some of them are especially close and you can access free of charge on request, and some money please.

**Comment by igormusinov** [comment]
@Nevol2110 yes. Good idea about ISP problem. I forwarded TCP/UDP.

**Comment by igormusinov** [comment]
My ISP told me that I can set it myself without a problem \

**Comment by Nevol2110** [comment]
Personally I do a host on Windows Server 2016. It was enough for me to open the necessary ports.
![image](https://user-images.githubusercontent.com/33912761/59149999-89b0d000-8a25-11e9-9abc-e9cd084f81c0.png)

**Comment by igormusinov** [comment]
![image](https://user-images.githubusercontent.com/11311889/59150025-c8468a80-8a25-11e9-91c6-06e24d91c0e3.png)

**Comment by igormusinov** [comment]
![image](https://user-images.githubusercontent.com/11311889/59150034-e57b5900-8a25-11e9-86a9-e471bb3c5a50.png)

**Comment by igormusinov** [comment]
![image](https://user-images.githubusercontent.com/11311889/59150044-fcba4680-8a25-11e9-93f3-983d11f092f8.png)

**Comment by igormusinov** [comment]
@Nevol2110  I have Windows 10 Home Edition (
btw, I ran simple python http server on <public-ip>:27015 and I still can't see the site. It seems that the problem with my PC or router (

**Comment by Nevol2110** [comment]
I don't know what's wrong with you... wait for an answer from the developers.

**Comment by igormusinov** [comment]
@Nevol2110  Talked with ISP. They sad the only option is to buy public IP-address ( , seems there are another routers in this topology that I cannot set
