### ISSUE TITLE
Other players are culled based on distance in multiplayer after dying and spectating

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1544]
Once a player dies outside the submarine and his corpse is left behind, the dead player cannot see the other players while spectating once the distance between the submarine and his corpse gets great enough

**Comment by hubismal** [comment]
This previously was reported and (supposedly) fixed in https://github.com/Regalis11/Barotrauma/issues/1421.
However, it just happened to me last night again.
![2019-06-09-022233_947x510_scrot](https://user-images.githubusercontent.com/47284081/59162114-4d2ab600-8ab1-11e9-85e6-807b700afe0a.png)

**Comment by thegrb93** [comment]
Same here. Died about 1000m from the main sub and can't see any players inside.

**Comment by Rokvach** [comment]
This has been fixed for the next patch, closing the issue.
