### ISSUE TITLE
Banned from own server after mistyping password 4 times

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1545]
There was a bug, the password from my server was not accepted, and after 4 inputs the game banned me on the server, and now I can not host the server

**Comment by NilanthAnimosus** [comment]
although intended behavior for external clients - you need to delete the ban from the bannedplayers.txt

This would be a bug if it did not accept the password when you hosted from in-client, but its not strictly a bug if you got it wrong 4 times when connecting via the client to a dedicated server instance, though could probably use an exception to even bothering with the password on 127.0.0.1 (Maybe) or just not counting failed attempts.

**Comment by Regalis11** [comment]
Haven't been able to reproduce this when hosting directly from the client. When hosting a separate dedicated server instance and trying to join it from the same machine, this is intentional.
