### ISSUE TITLE
 High frequency whistle after sound-related error

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1546]
Operating System:
Windows

Hardware:
Windows 10, 32GB RAM, Nvidia GTX 1070, i5-4570, Z87 Extreme3, Creative SB X-Fi

Message Body:
After first starting game, intro-sounds are a little crispy sound and when starting a new game at once as i start moving around my "sound crashes" and there is only a high frenquency whistle. I tried lots of different settings but nothing works. When i start game with that sound issue again it gets stuck at 39% loading, and in windows task manger, process isn't endable anymore. I have to restart the whole machine to fix sound issue. Also sound is very lound even on 1%. Also i think 0% setting doesn't turn off music or sound in game, maybe would avoid that aweful sound issue. Never had any issues with other games.

**Comment by Rokvach** [comment]
I haven't heard anyone else having any similar issues, can only suspect that the issue is caused by the users pc configuration being outdated. Closing this for now, we can re-open it if something similar is reported.
