### ISSUE TITLE
Weird behaviour after leaving the game paused for a long time

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1548]
Operating System:
Windows

Hardware:
windows 7

Message Body:
I was playing solo campaign. I had just started a mission and I had to leave outside so I left the game paused (with esc/inmenu). After around 3-4 hours I came back to "continue" my mission/gameplay I noticed everything around me (pumps/junction boxes) having the "fix/maintenance" gear logo displayed. I quickly clicked the closest one and just saw my "hp bar" deplete very fast rate. Needlessly to say to all seemed to happen everywhere in ship- started fires -> damaged structures -> leaks -> basically the end.

**Comment by itchyOwl** [comment]
So some of the timers ignore the game being paused?

**Comment by rico6822** [comment]
> So some of the timers ignore the game being paused?

It seems so.

**Comment by itchyOwl** [comment]
So is this fixed or not? If we still can repro it, in my opinion it's a bug that should be fixed.

**Comment by Regalis11** [comment]
> If we still can repro it

Has someone been able to reproduce this? I tried it a few times back when this ticket was added, and couldn't find a way to repro.

**Comment by Regalis11** [comment]
No known steps to reproduce, closing for now
