### ISSUE TITLE
End Round not always working in multiplayer as an admin

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1550]
Operating System:
Windows

Hardware:
Windows 10, GTX 1070

Message Body:
In a server with admin permissions, forcing an "end round" with the end round button sometimes does not end the round and instead brings up the console with this error.

![bt.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/63a31041-e0b5-4fd4-b13f-dcabd6a113c6)

**Comment by v5844** [comment]
The same as #1518
