### ISSUE TITLE
Workshop item not found in game, does exist on filesystem

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1551]
Operating System:
Linux

Hardware:
Well specced, not relevant here

Message Body:
Hey team, possibly a drama with in game relative filesystem pathing in linux?
Once subscribed to a submarine (in this case Sweet Pea) i see the option to be enabled in game. When ticking box i get:

  "Enabling the workshop item 'Sweet Pea' failed. File "Submarines\Sweet Pea.sub" not found.

Yet it appears to be present:

   HOST:\~/.steam$ find . |grep -i sweet |grep -i pea
   ./steam/steamapps/workshop/content/602960/1722213203/Submarines/Sweet Pea.sub
   HOST:\~/.steam$

**Comment by EdusFF** [comment]
Could be similar to the problem we had on MacOS where the forward / backward slashes were not read correctly.

**Comment by Regalis11** [comment]
Should be fixed by fa5b6ea

**Comment by Rokvach** [comment]
Working correctly. Closing.
