### ISSUE TITLE
An object can be repaired indefinitely for experience

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1554]
On three separate occasions, I have experienced the same bug. When repairing an object the progress bar will fill but the screen will not close and I will continue to gain XP as if I were still mid repair. Upon closing the screen with a right click, the object is operational as normal.

Bug Notes:
- All three instances occurred in singleplayer. (I haven't played multiplayer yet, so I don't know if it happens there too.)
 - All three instances of the bug were in a partially or fully flooded room. I have not experienced the bug in a room with no water.
- It's happened twice on the Dugong, and once on the Remora.
- The items repaired were: (One the Dugong) The navigation console, and the engine. (On the Remora) One of the junction boxes in the room connected to the rail gun room.
- I was able to level up by just sitting there and collecting extra XP.
- I experienced no lag, stuttering, or crashes whilst, before, or after, the bug was occurring.

**Comment by Rokvach** [comment]
Tested, this issue has been resolved in 0729f9f. Closing.
