### ISSUE TITLE
Add more animations for different situations to increase immersion

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1555]
The biggest issue for me has been the animations, I just think they could be improved in certain ways. It isn't that the existing animations are bad, it's that there isn't ENOUGH animation. Like when you are underwater, but not moving, you just fall over as if dead or unconscious. Why don't you stand? Or float in place? Or the melee animations where you just sort of flail your arm. It's just that it is very immersion breaking to see someone start moving in a way that doesn't make any realistic sense. Especially since the game is otherwise very immersive and atmospheric.

**Comment by ezjamsen** [comment]
@EdusFF can you add this to the character improvement epic? I don't seem to be able to.

**Comment by itchyOwl** [comment]
Agree. Let's see if we have time to address this at some point.

**Comment by ezjamsen** [comment]
This one hurts to drop... is there any way it could be squeezed in?

**Comment by Regalis11** [comment]
Things like making the characters move their their limbs around a bit when underwater wouldn't be that hard to implement. I think we can keep this, but the ticket needs to be made more specific (what kinds of animations for what situations)

**Comment by Rokvach** [comment]
At least one animation would be idle swimming, to keep your character in the same position when a character is underwater

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1490](https://github.com/Regalis11/Barotrauma-development/issues/1490) via [**ZenHub**](https://www.zenhub.com/)
