### ISSUE TITLE
Add a manual operation option to pumps that can be used in an emergency

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1558]
Most electronic items should become a lost cause once submerged completely. The aforementioned issue could be solved by adding in manual versions or functions of existing objects. Like a manually operated or battery powered pump.

**Comment by OverwatchVoice** [comment]
You can do that. Simply unwired it from whatever is controlling it (a water detector, for example.)

**Comment by Regalis11** [comment]
@OverwatchVoice I think the request meant pumps that can be operated even when the submarine has no power (for example, some kind of a hand-operated pump).

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1493](https://github.com/Regalis11/Barotrauma-development/issues/1493) via [**ZenHub**](https://www.zenhub.com/)
