### ISSUE TITLE
Chat messages overlap

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#156]
Иногда одно-два слова перемещаются на следующую строку, но этого не видно, пока кто-нибудь не напишет. Это не происходит на некоторых разрешениях экрана. У меня стоит 1024x768.
Sometimes one or two words move to the next line, but this is not visible until someone does not write. It's not happening on some screen resolutions. I have is 1024x768.
![image](https://user-images.githubusercontent.com/33912761/34001094-20067620-e100-11e7-875e-e9d9852fc324.png)

**Comment by Regalis11** [comment]
Fixed in the dev branch
