### ISSUE TITLE
Incomplete sub downloads break game

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1561]
Bug: Had a sub file which download didnt complete. Next client restart the console threw lots of errors.  

Expected: Client gives info about corrupt/incomplete files and skips them.

Also:
Bug: While preparing a sub for a workshop upload I left a jpg in the submarine subfolder. After restarting the client the console threw errors and the client didnt work properly any longer.

Expected: Game only checks for files that are important for the task (in this case the .sub files) while skipping others.

Version
v0.9.0.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/442db444e1d3254edd9c2e59e2ae9faff1ec53e3 (private repo)

**Comment by Rokvach** [comment]
Tested, this is working correctly on the currently live version and further improvements coming to it on the next update. Closing.
