### ISSUE TITLE
MP campaign mission broke: Missing alien pump

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1562]
Bug: We tried to pick a mission that crashed our game with "missing alien pump".  Tried 3 times. 100% crashs.

Workaround: Picking a different mission worked fine.

Version
v0.9.0.4

(Sorry, couldnt grab more info. Was not my server, admin refused to report issue)

**Comment by Regalis11** [comment]
Most likely the same issue as #1603
