### ISSUE TITLE
Sprite Layering for subwall and shell interaction is funky.

### ISSUE THREAD

**Issue by ColdOova** [Regalis11/Barotrauma#1563]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In trying to make a submarine, placing walls overlapping with shells ALWAYS has the wall over the BACKGROUND SPRITE of the shell unless the shell is using a value of over at least 0.850
The catch here is that it will look fine in the editor, and then in-game it is entirely wrong.

**Steps To Reproduce**
Just try to place a wall underneath a shell piece, layer it to be under the shell in the editor, and then load the sub in a game round. Try this with values for each valuing both under and over 0.850 for sprite layering to see the difference.

**Version**
Windows 10, latest version as of 6/8/2019 (v. 0.9.0.4)

**Additional information**

**Comment by Rokvach** [comment]
Moving this to QA as there is a similar ticket regarding the same issue.

**Comment by Rokvach** [comment]
Moving this to Done as it has been tested and found working correctly on our private ticket.
