### ISSUE TITLE
Cannot run multiplayer campaign in dedicated server

### ISSUE THREAD

**Issue by gustavlasko** [Regalis11/Barotrauma#1564]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to join campaign on a dedicated server, exception is thrown on client

**Steps To Reproduce**
**Unhappy path 1: Client already connected to server when campaign is started**
1 Start dedicated server
2 Connect to server from baro client
3 In server console, set game mode to campaign: `gamemode Campaign`
4 Reply to `>>Do you want to start a new campaign? Y/N` prompt: `Y`
5 Reply to `>>Enter a save name for the campaign:` prompt: `NewCampaign`

Results:
Server: `Campaign Started!`
[UnhappyPath1ServerLog.txt](https://github.com/Regalis11/Barotrauma/files/3268991/UnhappyPath1ServerLog.txt)
Client: `File transfer error: received data without a transfer initiation message`
`File transfer failed(Wrong file extension ""!(Expected .save))`

**Unhappy path 2: Client connects to server with campaign in progress**
1 Start dedicated server
3 In server consolge, set game mode to campaign: `gamemode Campaign`
4 Connect to server from baro client
5 Note same errors in the console re: file extension and transfer initiation

**Version**
v0.9.0.4 
Server OS: Windows Server 2019 Datacenter 1809
Client OS: Windows 10 Home 1809

**Additional information**

**Comment by igormusinov** [comment]
The Same bug

![image](https://user-images.githubusercontent.com/11311889/59165421-0d50e680-8b24-11e9-9973-cc16b2f4da91.png)

**Comment by Regalis11** [comment]
Implemented a workaround to this in 3cfef3c

**Comment by igormusinov** [comment]
We have to wait for update in steam ? Or we can simply fix this file and recompile the whole game ?

**Comment by Regalis11** [comment]
You could either compile the game yourself (which can be a bit tricky if you're not familiar with the usage of git, visual studio and programming in general) or wait for the next patch. I can't give you an exact date on when the patch will be released, but we're trying to get it out asap.

**Comment by akosipc** [comment]
@Regalis11 is the implemented workaround for this bug applies for Linux servers as well? I have encountered the same bug as well in Debian 9 and v0.9.0.4 of Barotrauma

**Comment by YannKr** [comment]
+1 for this issue being on Linux dedicated as well. It raises illegal character errors on clients with the savegame path.
Happy to provide more details or raise a separate issue if you need.

**Comment by Regalis11** [comment]
Fixed in v0.9.0.7

**Comment by Neouni** [comment]
Unresolved
