### ISSUE TITLE
Conditional AND comparison doesn't work

### ISSUE THREAD

**Issue by RusChosen** [Regalis11/Barotrauma#1566]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Setting comparison="And" in item's XML on status effect disables the comparison at all.

**Steps To Reproduce**
Let's try divinggear.xml, like I did. Find a status effect that gives the wearer oxygen.
Now we have 2 conditions to do so:
1) Conditional IsDead="false"  .Target is not dead . Which will always be true in the following tests).
2) RequiredItem identifier="oxygentank" type="Contained" . Status effect requires an oxygen tank contained inside a suit. Again, in the following tests this will always be true.

Now in the definition of status effect we have this: comparison="Or" which, I assume, means that if either one of the conditions are true will apply the effect.
I don't want my dead bodies breathing, so I will change it to comparison="And" (changing to "and" or "AND" spits an error, so I assume "And" is a proper spelling).
If I start the game and wear a diving suit now - it will not give me any oxygen from the tank, despite being alive and having the tank in the storage.

I've discovered the problem when adding the third condition Conditional Oxygen="lt 100" , that used to work in Alpha, when comparisons defaulted to AND, not OR. But now, no matter what I add, I can only add it as Or condition, which is not ideal.

**Version**
Windows 0.9.0.4

**Additional information**
Just want to reiterate, that I had it working in alpha, before steam release. Can't tell if it was the latest alpha, though. I've checked my condition spelling here on Git, and as far as I can see - character.cs still has "Oxygen" stat, clamped at 100.
I've also tried the first described option, without including any new conditions - just the vanilla "Tank present" and "Not dead", as soon as I switch it to "And" it stops working.

**Comment by Regalis11** [comment]
I would guess that this is caused by the status effect targeting multiple entities. For example, if you have a status effect that targets "Contained,Character" and use an AND comparison, the conditions have to be true for _all_ targets of the effect. If you want to do an AND comparison, you should split the status effects into multiple ones that only target the entity you're interested in.
