### ISSUE TITLE
[Tutorial][Feature request] New players can weld themselfs in a room

### ISSUE THREAD

**Issue by TheGoo-ooo** [Regalis11/Barotrauma#1569]
**Description**
During the first tutorial, mechancic's tutorial, players can weld the door leading to the breach, preventing them to continue on with the tutorial. 

**Steps To Reproduce**

- Start the first tutorial (engineer)
- Take the welder and tools as required by the tutorial
- Go to the next room, next to the one with the flooding
- Read the information on the upper right corner of the screen. NB: There are no mentions of "putting on the gas mask" or "equiping the welder".
- Miss the orange overlay over the gas mask.
- Try to open the door by any means
- Use the welder
- Fail to understand that you just welded yourself out of continuing the tutorial
- Notice the orange overlay on the gas mask, equip it
- Notice the orange overlay on the welder, equip it
- Notice the door light (red) changing to green
- Try to open the door
- Understand what you just did
- Despair
- Go to the github to file a bug report
- Look into the opened issues to see if a report about this issue already exist
- Notice that there already is a bug report about it
- Remember that you are the dev and that you already read this bug report
- Prevent newbies from welding doors during this first part of the tutorial
- Make the orange overlay flash to ensure people don't miss it
- Add a line of text from "Captain Huskinson" mentioning the fact that you should equip the gas mask
- Feel happy about the fact that you made the game a little bit better

**Version**
Vanilla 0.9, Windows

**Additional information**
- When you want to highlight something, make it flash. The human eye is made to notice movement. Simply surrounding a given object with orange can, will and has been missed, leading new players to weld themself in a room or do other stupid things.
- New players just don't know better.

**Comment by Regalis11** [comment]
Fixed in 8e65bd6
