### ISSUE TITLE
Unable to connect to server.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1570]
**Description**
The screenshot and the error were not caused by me, but we have already done everything we could. The error has not disappeared. Have him all server have "the other" Vanilla 0.9. What to do and how to fix I do not know.
![image](https://user-images.githubusercontent.com/33912761/59162671-c9e38180-8afd-11e9-91e5-45e0fa0cd122.png)

Windows 10x64. Steam

**Comment by Regalis11** [comment]
The error in the image should be fixed by bea7b58 (will be included in the next patch). 

Could you please elaborate a bit what happened? The title says you were unable to join a server, but the screenshot seems to imply that a round was started and an error thrown when the round ended?
