### ISSUE TITLE
Barotrauma wont start :C on steam 

### ISSUE THREAD

**Issue by jesusofgaming** [Regalis11/Barotrauma#1571]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by jesusofgaming** [comment]
I bought the game paid 20 $ and the game dont starts at all it gives me a warning and leaves a note in the gamecode everytime i try to start the game

**Comment by Regalis11** [comment]
Sorry for the trouble. :/ Unfortunately it's hard for us to help without more information on the issue. Have you read the pinned posts on the "[Help & Technical Support](https://steamcommunity.com/app/602960/discussions/1/)" board on Steam? Which operating system are you playing on? What is the warning and the note you're getting?

**Comment by Nevol2110** [comment]
https://www.microsoft.com/en-ca/download/details.aspx?id=36805
If you have Windows 7 or 8, it should help.

**Comment by Regalis11** [comment]
I'm afraid we cannot fix this without more information on the problem (operating system, error message, crash report). Closing
