### ISSUE TITLE
Pump wire syncing/pump targetlevel logic getting stuck after wires removed

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1573]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was playing public multiplayer and noticed a very unusual issue, the server was being constantly sabotarged by someone rewiring half the submarines systems with traitors off - fine, so I went about correcting the wiring battling them out by reconnecting all the pumps/ballasts/engines/airlock and door wiring and anything else that was damaged by them.

I could correct everything with the exception of a small pump that kept flooding a room, it only had a power wire but a wire was in the set target level pin which I promptly ripped out. turning the pump off and on or trying to adjust the pumping speed always ramped it back to 100%.

I eventually tried placing a 0-output signal source into the pump, then ripped the wire back out and it eternally stayed at 50% room water level - needless to say I ended up having to cut my losses and turn the pump off permanently (and this was an airlock pump) since I wasn't sure where and how I could generate a consistent -100 signal source.

either a wire was connected that I couldn't see, or perhaps pumps after the wires are removed do not reset their target level, constantly overriding the speed its set at.

**Steps To Reproduce**
Unknown, not attempted to reproduce yet.

**Version**
0.9.0.4 steam - windows 7 64bit, Client connected to server.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b9203ac9dbf046acc98f4efedb0bc6f0ee38cbf (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
