### ISSUE TITLE
Shuttle / Submarine docking is impossible

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1574]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When docking a shuttle to the submarine, the console will print out a message reading that there's too much distance between the two hulls, and that the water between them cannot be removed. When people try to pass through, they will get stuck and get crushed shortly after.
**There is no way to avoid this; No matter how close you get before docking, the issue still persists.**

**Steps To Reproduce**
Just try to dock.

**Version**
9.0.4, Windows 10

**Comment by NilanthAnimosus** [comment]
I've seen in multiplayer plenty of cases of successful docking - is their any specific submarine this occurs on or specific shuttle combination, as well as specific docking ports on them?

**Comment by OverwatchVoice** [comment]
I just a successful dock with the shuttle. Whats weird is that it happened to the submarine that was having the most problems with it. It's not really that big of a problem, since the shuttle doesn't usually make it very far...
