### ISSUE TITLE
Multi-Coilgun constructions don't focus onto the reticle, instead fire in parallel

### ISSUE THREAD

**Issue by Frostdemon727** [Regalis11/Barotrauma#1575]
- [x] I have searched the issue tracker to check if the issue has already been reported.
There seem to be many issues about coilguns, but I havent found any about multiguns, atleast when I typed down the title

**Description**
As far as I can remember, multiple turrets (mostly railguns) hooked up to a single periscope usually focused onto the reticle, provided their rotation limits allow it, allowing focused fire against everything. However, it seems that as of now, at the very least Coilgunturrets (I have not tested this on railguns) fire in parallel if hooked up to the same controller. 

To illustrate what it looks like: The camera is focused onto a single (mostly the first gun hooked up) turret, which becomes the point of view (it is to note that it completely ignored the camera I hooked up prior for the purpose of being my eyes and ears between the guns). This turret will follow and fire at the cursor as usual.

In legacy, so did the other guns, all of them followed the same cursor and focused in on it, now however, the other gun did not follow the visible cursor, but once said cursor was moved, the other gun did rotate as well, by the same degrees as the main gun. The two guns were in parallel.

I personally assume that the game messed up somehow and treated every gun with its own cursor, visible from its own "aiming screen", but since multiple guns were controlled by the same periscope, only one of those screens was shown, while all the aiming screens were active, with all their cursors being moved identically, resulting in the guns firing in parallel.

**Steps To Reproduce**
the sub in which this occured is the "EF Ambition", my very own submarine (https://steamcommunity.com/sharedfiles/filedetails/?id=1765800160) just in other constructions do not yield the same result)

1. Build 2 coilguns (perhaps railguns too) nearby
2. Camera inbetween
3. Hook camera up to position_out of periscope
4. Hook up both guns to the periscope (I deem it unlikely that the order in which what is done here is relevant, but in my case I first did the individual triggers, then the individual positions, perhaps this caused something)
5. Try aiming the weapon, the guns should rotate in parallel and not focus onto the reticle.

**Version**
Using Windows, version 0,9,0,4

**Additional information**
If I may add, I actually deem is very interesting (and potentially fun) to have weapons fire in parallel, so I suggest actually turning this (assumed) bug into a feature, and allow one to choose between a focussing or a parallel constellation of multiple guns. (And perhaps also, allow us to designate a "lead" rifle, on which the camera is based one)

Also, on a related note, it seems that crewmen are unable to properly fire multi-gun constellations, though they attempt to follow it, might be because I assigned him to the non-lead gun, keeping him from aiming properly, havent tested that thoroughly

Thanks, Frostdemon727

**Comment by NilanthAnimosus** [comment]
the guns if I recall send a rotation to allow for wiring to effect them (and no longer send or use worldspace coordinates), and given that the rotation is based on your aim in relation to the camera having an unmodified signal input from one camera will give all coilguns the same angle of aim (even if that is not where your aiming specifically but just the same direction in relation to what your aiming from).

This would be a logical challenge with the current components to somehow devise a method to translate the aim of two separate coilgun rotations to be closer to the aim, especially given you could be aiming far away or close and you cant know that from logic either on how much to change the rotation by.

The reason for these changes allows for raw signal inputs to work, so you could for instance wire a navigation terminal or such into a coilgun and aim it that way (Or though any other wired means such as buttons and such).

**Comment by Regalis11** [comment]
Nilanth is correct, we made the periscopes send out the rotation instead of the cursor position because it makes it much easier to manipulate the angle with signal components, to control the turrets using some signal logic instead of a periscope, and is in general much simpler than sending the coordinates of the cursor. I'm sorry but I don't think we should change it to support a rare use case like this.
