### ISSUE TITLE
Include a dummy mod with no/commented out content to remove some confusion

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1577]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have seen some cases where mods are broken because the content types are incorrect (Such as adding <None> instead of <ItemAssembly>) and also some cases where the mods data is dumped into the root mods folder all of its files, instead of ../Mods/Modname/contenttype/fileshere.xml

could in the next patch a super quick mock-up of the usual mod style and format be included into the mods folder, one that doesn't actually have or add any content if even having an renamed file list or other such to not be registered/picked up by the game directly.

it just needs to detail how to add a piece of content (A copy of vanilla item commented out as example, like a piece of clothing or a job)

It also just needs a list of the content types available (and which ones are checked) - can just be copied from ContentPackage.cs but most players won't be checking the source.

A steam guide might make sense but the amount to explain that could just be shown and lack of simple code highlighting (for XMLs) I feel it may be simpler to just provide an example mod that does nothing.

**Comment by Regalis11** [comment]
Implemented in v0.9.2.1
