### ISSUE TITLE
"File Transfer too large" and "File transfer error: Received information without request"

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1578]
Operating System:
Windows

Hardware:
Was using Hamachi (but otherwise all else is irrelevant)

Message Body:
Joined my friend's server and got repeated error in console "File Transfer too large" and "File transfer error: Received information without request" and it wouldn't let me load into Campaign gamemode, but did allow single missions

**Comment by Regalis11** [comment]
Fixed in a336a31

**Comment by Regalis11** [comment]
Fixed in a336a31
