### ISSUE TITLE
Nametag visibility issues

### ISSUE THREAD

**Issue by DifferentLevelDan** [Regalis11/Barotrauma#158]
Nametag visibility seems to check if you can see where the nametag is, not if you can see the player themselves.

This results in two issues.
1) If you are in a room above a player that you cannot see, you can sometimes see their nametag.
2) If you are in a room with a low ceiling, you cannot see the nametag of the person next to you.

I suggest the nametag visibility be linked to the player's visibility.

**Comment by Crystalwarrior** [comment]
Fixed in https://github.com/Regalis11/Barotrauma/pull/160

**Comment by Crystalwarrior** [comment]
Oh yeah I didn't fix the name being too high into the ceiling
