### ISSUE TITLE
Server list improvements

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1580]
Operating System:
Windows

Hardware:
Windows 8

Message Body:
It would help greatly if the server list could be sorted by name, amount of players and ping. Also if you copy-paste an IP into the Server IP field, the join button sometimes stays greyed out and you need to give the Server IP input field another input before the Join button enables.

**Comment by Regalis11** [comment]
Closing this, we have separate tickets for this in the private repo and most of this has been already implemented.
