### ISSUE TITLE
Resolution changing mid-game

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1581]
Operating System:
Windows

Hardware:
Windows 10, 16GB RAM, Nvidia GTX 1050Ti

Message Body:
So, for some reason my friend's game suddenly changed it's resolution mid-game on 2 attempts of multiplayer games. It couldn't be fixed manually cause the window was too zoomed in to even access the settings. The window's resolution was just big enough for the 4 crew info to fill the screen.
No crash report cause it didn't crash or send any problem detection message, he had to close the game with Alt+F4.

**Comment by Heldex** [comment]
its after you tab out, switch to borderless windowed and it'll be fixed (atleast unti its patched)

**Comment by Rokvach** [comment]
I don't think this is a issue anymore with the new SDL2 implementation, closing.
