### ISSUE TITLE
I can't connect to any server

### ISSUE THREAD

**Issue by dalover** [Regalis11/Barotrauma#1582]
When I try to connect to any server I get an error "Connecting failed. Could not to reconnect to the server". Also writes me if i open the command prompt "Received a disconnect message (Failed to establish connection - no response from remote host). Do no attempt reconnect (not allowed)". In addition, any information about servers is unknown (game version, game mode, contect packages, etc.). "Coudn't determine compatibility".

**Comment by Regalis11** [comment]
Since this might've been caused by so many different things (firewall, antivirus, something at the user's end), and since the report is so old, I don't think there's much we can do about this.
