### ISSUE TITLE
cant launch the game

### ISSUE THREAD

**Issue by fifcio99** [Regalis11/Barotrauma#1583]
The game wont launch it just gives me the crash message, crash log attached. All frameworks updated, running on win 7 dx11 
[crashreport (26).log](https://github.com/Regalis11/Barotrauma/files/3271783/crashreport.26.log)

**Comment by itchyOwl** [comment]
Duplicate of #1515. Try these steps: https://steamcommunity.com/app/602960/discussions/1/1642039362990436647/
