### ISSUE TITLE
Empty coilgun ammo boxes cant be recycled

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1586]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Empty coilgun ammo boxes cant be deconstructed or refilled.

**Expected** 
Deconstruction of empty ammo boxes and/or recipe to refill them in the fabricator.

**Comment by Regalis11** [comment]
Fixed for the next patch, the changes are not visible in this repository because the Content folder and the item configuration files are not included here.

**Comment by d3x0r** [comment]
This has been working.  (although you get 2 Aluminum, 1 Steel, and you only need 1Alumnum and 1 Steel

**Comment by Rokvach** [comment]
Tested, this has been fixed in 54b6fe9, closing.
