### ISSUE TITLE
New editor features

### ISSUE THREAD

**Issue by armadillosloth** [Regalis11/Barotrauma#1587]
I'm having a lot of trouble with the new sub editor features.
Scale and texture scaling seem to reset randomly, and I can't change some object's scale I.E. the secure cabinet. Additionally, most shell pieces are incredibly glitchy when using these features on them.

These problems usually fix if I delete the piece and replace it, but this can be annoying with cabinets and other storage items i've already placed a lot of things in.

**Comment by Regalis11** [comment]
Should be fixed by 667564f and 7684c5e

**Comment by Rokvach** [comment]
This has been confirmed to be working correctly, Closing.
