### ISSUE TITLE
Crashes related to PhysicsBody.Enabled

### ISSUE THREAD

**Issue by DifferentLevelDan** [Regalis11/Barotrauma#159]
Crash report is from my live server. I have git cherry-pick'd commit 72e42bd257cb612896d0dea4fb1f420829536595

Reading the crash report, may be related to husk spawning or enabling physics on bodies that have been disposed.

Exact codebase my server is running: https://github.com/DifferentLevelDan/Barotrauma/tree/Dystopian

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1560379/crashreport.txt)

**Comment by juanjp600** [comment]
`   12/14/2017 12:49:40 PM - FixtureList is null!`
This is what I was hoping we would see, thanks for testing this out. It seems likely that it had to do with husk spawning, I'll be looking into it.

**Comment by DifferentLevelDan** [comment]
Another crash.

Round started, I noticed the debug console was up, scrolled up and found the try-catch's, saw some additional debug info I added, and went to control a mantis.

Game crashed right away.

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1563799/crashreport.txt)


`                    if (body.FixtureList == null)
                    {
                        DebugConsole.NewMessage("FixtureList is null!", Color.Red);
                        if (UserData is Limb limb)
                        {
                            DebugConsole.NewMessage($"Limb belongs to {limb.character.Name}", Color.Red);
                        }
                    }`

**Comment by DifferentLevelDan** [comment]
Another crash, different stack trace from either of the previous. May be related to the ragdoll issue you found earlier.

Anacdotally, the server was up for 7 hours while I was at work. I came home, connected through another client (I was Jervis Clayton) and it crashed two rounds later. It seems like crashes are more common when I'm in-game on another client.

Maybe it's in my head. This is a terrible bug for reproducibility. I restarted the server and used the same level seed, ran through the mission, and it completed fine.

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1564476/crashreport.txt)

**Comment by DifferentLevelDan** [comment]
I've been getting more crashes, and I've noticed most of them appear to be related to manti limbs. I donno, maybe it's a lead.

   12/16/2017 6:47:04 AM - Limb belongs to mantis
   12/16/2017 6:47:04 AM - FixtureList is null!
   12/16/2017 6:47:04 AM - PhysicsBody UserData: Barotrauma.Limb
   12/16/2017 6:47:04 AM - Exception in PhysicsBody.Enabled = False (True) {Object reference not set to an instance of an object.}
   at FarseerPhysics.Dynamics.Body.set_Enabled(Boolean value)
   at Barotrauma.PhysicsBody.set_Enabled(Boolean value) in D:\GitHub\Barotrauma\Barotrauma\BarotraumaShared\Source\Physics\PhysicsBody.cs:line 177

**Comment by DifferentLevelDan** [comment]
Crash can happen to players.

I noticed the log errors, so I ended the round to try to prevent a crash, as soon as the next round started it went down.

This time, it was a player, (Which may rule out the FishAnimController) so I'll include the crash log, since it was new.

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1569416/crashreport.txt)

**Comment by DifferentLevelDan** [comment]
Running with fixes from @juanjp600 server seems more stable. Got this crash twice now however.

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1573200/crashreport.txt)

**Comment by DifferentLevelDan** [comment]
Another crash related to Character.AnimController.Limbs being null.

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1577804/crashreport.txt)

**Comment by DifferentLevelDan** [comment]
Another crash related to Limbs being null

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1577979/crashreport.txt)

**Comment by Regalis11** [comment]
Most likely related to ceaba2f

**Comment by Regalis11** [comment]
I haven't encountered this problem since ceaba2f, so I'm pretty confident it's fixed now.
