### ISSUE TITLE
Backspace kicks me out of fullscreen

### ISSUE THREAD

**Issue by spacekitty76** [Regalis11/Barotrauma#1590]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I start a new campaign > click into the save name box > hit backspace to delete the word 'save' (so i can rename it) > it kicks me out of full screen mode

**Steps To Reproduce**
See the description

**Version**
0.9.0.4
Windows 10

**Comment by will2234** [comment]
every time is hit backspace to communicate or to change name it kicks me out of full screen

**Comment by Rokvach** [comment]
This shouldn't be an issue with the new SDL2 window implementation.

@Regalis11

**Comment by Regalis11** [comment]
Yeah, I believe this may have been fixed by switching to SDL. 

I'm closing this for now, but @spacekitty76 and @will2234, please do let us know if the issue still persists in the latest version.
