### ISSUE TITLE
Checking version and downloading of a sub at the start of a game does not always trigger

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1591]
Operating System:
Windows

Hardware:
Win 10, 32gb, 1080, i7-6700k, ssd

Message Body:
Dedicated Server

Modified Typhon, saved as Typhon Mk2.  Played for a day.  Next day, edited ship, changed aft bottom docking hatch .  Loaded in single player to problem.  On server start mission, all players disconnected because item hatch missing.  

Loaded Mk2, Saved as Mk3.  Continued no problems.  Seems a md5 check may be in order on custom subs for download.

**Comment by Regalis11** [comment]
There is already an MD5 check in place, and I couldn't find any issues with it nor reproduce this issue.

**Comment by Rokvach** [comment]
Tested, this issue has been fixed. Closing.
