### ISSUE TITLE
Background Layer Glitch- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1595]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just look.

**Steps To Reproduce**
Occurs randomly I guess. 13:50 of the following video https://www.youtube.com/watch?v=godhI9qiE7A.
**Version**
Video was uploaded on January 9.
**Additional Info:**
Bonus glitch about flooding submarine at 21:29.

**Comment by Rokvach** [comment]
Tested, displays correctly now. Closing.
