### ISSUE TITLE
AI: Switch and recharge batteries

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#1596]
When a battery of any item the bot uses is out of charge, the bot should switch in new batteries and put the empty batteries into the charging dock.

**Comment by Kaillera** [comment]
I think this one should be implemented soon due to the recent change in level size. It's been annoying me in the cold labyrinth biome because all of a sudden I will not be able to send any orders to them in critical moments unless I am next to them or stun them to replace their batteries.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1492](https://github.com/Regalis11/Barotrauma-development/issues/1492) via [**ZenHub**](https://www.zenhub.com/)
