### ISSUE TITLE
Improve the feedback for the player when a character cannot hear your command.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#1597]
Also the order button shouldn't be toggled on if the character cannot hear the command.

**Comment by danielasteljoki** [comment]
I'd sidestep this issue altogether by greying out any characters in the UI that are out of range or unconscious.

**Comment by Regalis11** [comment]
The characters are now crossed out in the command UI when out of range.

**Comment by Rokvach** [comment]
No issues, closing.
