### ISSUE TITLE
Game crashes when trying to boot up. version 0.8.2.3

### ISSUE THREAD

**Issue by martcraft** [Regalis11/Barotrauma#1598]
(Yes, I know someone reported it but it was on Linux, not windows..)
Hello, I run windows 10 home version 1803. I use barotrauma for a LONG time, and I tried to play it. But... it crashed. launcher works but when I try to boot it, it just doesn't work. BTE or other modded version ain't working. God, I hope I'm not wasting anybody's time but anyway.. here is the file.

PS: the crash report is in dutch for some reason so, sorry for that,... also I have two graphics cards but it worked without a problem earlier so... just so that you know it.
[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/3277941/crashreport.txt)
Barotrauma Client crash report (generated on 11-6-2019 20:23:42)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

Game version 0.8.2.3
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Intel(R) UHD Graphics 620
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,777778}
    GPU status: Normal

Exception: Unable to load file or assembly OpenTK, Version=2.0.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4 or one of its dependencies. The system cannot find the specified file.
Target site: Void Init()
Stack trace: 
   bij Barotrauma.Sounds.SoundManager.Init()
   bij Barotrauma.GameMain.LoadContent()
   bij Microsoft.Xna.Framework.Game.Initialize()
   bij Barotrauma.GameMain.Initialize()
   bij Microsoft.Xna.Framework.Game.DoInitialize()
   bij Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   bij Barotrauma.Program.Main()

Last debug messages:

**Comment by databasetd** [comment]
You are using a legacy version of Barotrauma which is not supported. Barotrauma has been released on Steam and is available for purchase on https://store.steampowered.com/app/602960/Barotrauma/

**Comment by martcraft** [comment]
ok
