### ISSUE TITLE
Event: Underwater Quakes?

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1599]
Are there more randomized events planned? If so, whats in the pipeline?

How about random underwater quakes? Would be awesome to deal with, right?

**Comment by Regalis11** [comment]
We have talked about the idea of "icequakes" and falling chunks of ice, but we're not yet sure if it's going to be a feature or not. However, there will most likely be more environmental hazards and random events, even if it wasn't necessarily quakes.

But in any case, the collaboration section in the official forums is a better place for feature requests and ideas. The issue tracker should generally be used for bug reports, pointing out design flaws, balance issues and so on. We used to allow feature requests here as well, but the tracker ended up getting cluttered to the point where it was very hard for us to find the more critical issues when they were mixed in with hundreds of ideas and feature requests.
