### ISSUE TITLE
Defining Ragdoll panes overlapping

### ISSUE THREAD

**Issue by Guiorgy** [Regalis11/Barotrauma#1600]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the character creation window, under Defining Ragdoll, the bottom pane (Joints) covers dropdown options of the pane above (Limbs). Because of that, some of those options are unselectable. See the image below:

![rep](https://user-images.githubusercontent.com/27736965/59304444-57170980-8ca9-11e9-82ec-e09fd86f8255.png)

**Version**
v0.9.0.4
Windows 10

A workaround is to add and then remove another limb, which will allow for further scrolling.

**Comment by Regalis11** [comment]
Should be fixed in e9c8103

**Comment by Rokvach** [comment]
Tested, this has been fixed and more improvements are coming with the new editor overhaul. Closing.
