### ISSUE TITLE
Crash while repairing ship airlock door while wire is dropped outside of sub

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1604]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash during multiplayer game.

**Steps To Reproduce**
The title says it, but I don't know if that's the real cause or not.

**Version**
Windows 10 x64 Latest steam version.

**Additional information**
Attached crash report
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/3279841/crashreport.log)

**Comment by Regalis11** [comment]
Should be fixed in 942b8a8

**Comment by thegrb93** [comment]
Found the crash dump. Might help find the root of the cause

**Comment by thegrb93** [comment]
https://www.dropbox.com/s/kb5bwtbx88fj0jh/Barotrauma.exe.10764.dmp?dl=1
