### ISSUE TITLE
Error initializing ALC device: InvalidDevice. Disabling Audio playback...

### ISSUE THREAD

**Issue by BradleyRasic** [Regalis11/Barotrauma#1605]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I recently downloaded the new Barotrauma game, and first thing when I open it, is that I have no sound at all? I have tried changing the microphone to a working device in settings, AND going tthrough my sound drivers and making sure the correct devices are set to default.

**Steps To Reproduce**
Unknown.

**Version**
Barotrauma v0.9.0.4 -- Windows 10

**Additional information**
Screenshot of issue:
![](https://i.imgur.com/GfhSdj1.png)

**Comment by BradleyRasic** [comment]
I've even tried going into SoundMaster.cs to backtrack the cause of the error, but I can't find anything at all.  My audio drivers are up to date, I even tried re-installing my audio drivers, with no success. A fresh re-install didn't help either 😢

**Comment by Regalis11** [comment]
If reinstalling OpenAL didn't help, I'm unfortunately not sure if there's a way to work around this issue. :/ We've got a patch coming up very soon though with OpenAL fixes that I think should resolve this.

**Comment by BradleyRasic** [comment]
:( Thanks anyways
I'll see what else I can do in the meantime
