### ISSUE TITLE
Subs editor issues

### ISSUE THREAD

**Issue by igormusinov** [Regalis11/Barotrauma#1606]
-Ctrl+c and ctrl+v works buggy in the subs editor (only when mouse under the target)

-Cannot paste walls

-ctrl+z have to work ?

**Comment by itchyOwl** [comment]
Undo and redo (ctrl+z and ctrl+r) work only for the currently selected items and the functionality is limited to movement only. Better undo implementation is on the todo list, but it's time consuming to implement afterwards, so cannot give any ETA.

What do you mean by ctrl+c and ctrl+v working buggy?

**Comment by igormusinov** [comment]
@itchyOwl  it works only when my cursor over the item I want to copy. But it somehow works.
What is more important, I can't paste walls from the editor menu below
