### ISSUE TITLE
Single player can end round in outpost

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1608]
Operating System:
Windows

Hardware:
Win 10, 32gb, 1080, i7-6700k, ssd

Message Body:
Dedicated Server

Any player can end the round by going into the outpost and talking to the npc instead of voting to end round or having admin do it.  Can lead to failed missions if sub is having docking piloting issues.

**Comment by Regalis11** [comment]
Not relevant anymore, because the logic for ending campaign rounds is going to change as a part of the campaign changes.
