### ISSUE TITLE
Make a new highlight color for wiring in the server log and add a new category to filter it

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1609]
The most dangerous sabotage can be identified by checking it.

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/89ec188d (private repo)

**Comment by Rokvach** [comment]
Inventory Usage and Wiring has the same color, ofc you can filter the output but I think Wiring of its own is so important that it should have its own color as thats what the server staff would mostly be looking at.

**Comment by Rokvach** [comment]
Moving this back to To Do @Regalis11

**Comment by Regalis11** [comment]
Fixed in 77e96bd

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
