### ISSUE TITLE
Hosting dedicated servers on your own PC and adjusting player count does not apply

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1610]
Operating System:
Windows

Hardware:
W10, 16GB Ram, 1080ti, Ryzen 1700

Message Body:
When you host a server yourself using the "Host Server" button in the main menu there seems to be an issue where the size of the server that is to say how many people can join it automatically goes to 10 and is seemingly unchangeable with basic measures.

![HostingServer.jpg](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/f19b4ba4-6c04-40e7-ab6d-1c3e46d4c0e2)
![ServerList.jpg](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/6ce61f88-d4c1-4b02-b8b7-28ddffb23359)

**Comment by Regalis11** [comment]
Fixed in 45e05f7
