### ISSUE TITLE
Water detector only outputs 0 when water is pumped out, and not when flowing out

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1611]
Operating System:
Windows

Hardware:
10

Message Body:
Hello,
The water detector only outputs 0 when water is being pumped out of a room and not when the water flows out of a room.

**Comment by thegrb93** [comment]
So if water flows out of a room without a pump, the room's water detector stays 1?

**Comment by Regalis11** [comment]
Haven't found a way to reproduce this

**Comment by Regalis11** [comment]
Unfortunately I don't think we can fix this without more information on the issue. The detectors shouldn't be affected at all by how the water is flowing into or out from the room, they only check whether the detector submerged or not, and based on the testing I've done it seems to be working correctly.
