### ISSUE TITLE
Minor mistake in Physicorium Shell description

### ISSUE THREAD

**Issue by Lordician** [Regalis11/Barotrauma#1613]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The description of the Physicorium Shell mentions that it is for the coilgun.
Of course this is false since it is ammo for the railgun.

**Steps To Reproduce**
Look at description of Phycorium Shell.

**Version**
Version 0.9 (Vanilla)
Windows 10 OS

**Additional information**
None

**Comment by Rokvach** [comment]
Tested, displays the correct info now. Closing.
