### ISSUE TITLE
Couldnt craft deep decoy charges

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1615]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During our campaign missions we couldnt craft deep decoy charges. 
All items had been added to the fabricator, but we couldnt crate it.
Rough guess is that the sonar-item didnt work in the recipe. We tried with or without full battery charges, no dice. 

**Steps To Reproduce**
Put the needed items for the deep decoy charges into the fab, recipe stays greyed out, create button not working.

**Version**
9.0.4, dedicated server on campaign, Win10pro, 3 players online

**Comment by Regalis11** [comment]
Could be related to #1526

**Comment by Rokvach** [comment]
There's been improvements on this issue, closing.
