### ISSUE TITLE
Autocomplete console command arguments

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#162]
Hitting tab when entering a command argument should autocomplete the argument when possible. At least in the character & item spawning commands and commands that take the name of a character or a client as an argument.

**Comment by CryIz** [comment]
Это будет очень хорошо, к примеру, для меня. Как камень с плеч. Столько времени сэкономлю :).
It will be very good, for example, for me. As the stone from shoulders. How much time will it save :).

**Comment by CryIz** [comment]
![1454578607117185091](https://user-images.githubusercontent.com/33912761/34456753-587b22b4-edb0-11e7-834c-88ff49551d01.png)
