### ISSUE TITLE
The console and the game client have different commands.

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1620]
**Description**
![234](https://user-images.githubusercontent.com/33912761/59387359-a32d8100-8d71-11e9-91f2-ace8d31753dc.png)
The console has the command "SetPassword", but in the game client this is not. Also, the command "Gender" is not in the console, but in the game client.

**Version**
Windows Server 2016. I do a server host through "Dedicated Server".

**Comment by Regalis11** [comment]
Both of these are intentional. Setpassword is a server-side command and can only be used if the client has been given the permission to use it. Gender is a client-side debug command that isn't implemented for multiplayer sessions.
