### ISSUE TITLE
Another crash report. Syringe gun dart crash?

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1622]
Was in a multiplayer game with >10 people. The stack trace looks like a syringe gun dart maybe caused it.

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/3283930/crashreport.2.log)

**Comment by thegrb93** [comment]
Found the crash dumps in my AppData/Local folder
https://www.dropbox.com/s/njwks4ql3coy3e1/Barotrauma.exe.11532.dmp?dl=1

**Comment by Regalis11** [comment]
Fixed in b598459
