### ISSUE TITLE
Custom ship shell becoming unmirrored after second mission start

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1624]
Operating System:
Windows

Hardware:
Windows 10, 16GB RAM, Nvidia GTX 1060, Intel Core i7-4770

Message Body:
I am using a Y Mirrored "Shell A 38 Degrees" on the lower rear of my submarine. A normal campaign starts up with no errors, and the first mission can be completed normally. After selecting and starting the second mission from the map, that shell piece becomes unmirrored and shows errors in the debug console.

Normal:
![normal.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/0d7b9a64-1967-4550-9621-9cd752419db1)

Errors at start of second mission:
![errors-at-start-of-second-mission.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/37bafee2-d1e7-4f56-8f30-f1b941c0d8c1)

Visuals after starting second mission:
![after-starting-second-mission.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/63683811-f1af-4b08-b6fa-530618120c9a)

**Comment by Regalis11** [comment]
Wasn't able to reproduce this, if anyone has any info on how to do it please let me know

**Comment by Regalis11** [comment]
Potentially fixed by https://github.com/Regalis11/Barotrauma-development/commit/f856a199f420da4c17cc3d9bf1631ef1258bee28 (private repo)

**Comment by Rokvach** [comment]
I haven't seen or heard of anyone having this issue in a while now. Closing.
