### ISSUE TITLE
AIs in idle state do not find their path properly

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1627]
This behaviour is most prominent in training where once dismissed AIs enter the idle state and instead of pathing inside a room they end up colliding with the wall / door. When viewed in debugdraw it's noticable that the AIs path does not update properly.

**Comment by itchyOwl** [comment]
It's not necessarily a path finding issue. In the debug draw, it shows the previous path also when it's not active. It can be though. An image with debugdraw enabled would be helpful.

**Comment by itchyOwl** [comment]
I'm quite sure this is not a pathfinding issue. It's most likely due to a logic error in the state transitions. Let's evaluate this again when the human ai branch is ready for review.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
