### ISSUE TITLE
selecting a content pack and then deleting it out of game causes the game to crash on startup

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#1628]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Comment by Regalis11** [comment]
Could not reproduce. I tried installing and enabling BTE, deleting it (just the content package xml first, then both the xml and the content files) and relaunching, but the game seems to switch to the Vanilla content package automatically on launch.

Could you please give some more info on how the crash happened, and/or send the crash report?

**Comment by etet2** [comment]
hmm, i think this crashg might actually have something to do with  #1629 and the weird bugs that caused, i'll close this
