### ISSUE TITLE
Don’t fire Husk eggs out of a railgun

### ISSUE THREAD

**Issue by Rebelord01** [Regalis11/Barotrauma#1632]
Description:
As the title says do not launch Husk eggs out of a Railgun by putting it in a shell or it will crash your game and crash the server your are on

**Steps To Reproduce**
I haven’t tested this really so here’s how it happens for me. It happens on a consistent basis, I suggest trying this with other items, as I have not considering that it crashes my game
1. I select Typhon sub because it’s the only one with eggs
2. Grab husk eggs from Ned bay and load into a shell
3. Pull trigger

**Version**
The latest steam version as of June 13 2019 on the latest version of windows

I have only done this on Sodium.me because it’s the primary server I play on and I figured out that this was crashing my game so I stopped

**Comment by CurePindal** [comment]
Lol, nice find! I wonder, but is it even intended that you can stuff them into the railgun shells??

**Comment by Rebelord01** [comment]
I think it is intended considering you can only put meds in a medic uniform, so they could of done the same for the shell if they wanted.

I’m pretty sure if you put a stun gernade in it will stun a monster but I’m not sure

**Comment by Rebelord01** [comment]
I forgot to mention not only does it crash your game and the server but it also crashes everyone on the servers game so you may want to patch this soon

**Comment by thegrb93** [comment]
They've been actively patching crashes. Did you really need to advertise that?

**Comment by Regalis11** [comment]
Fixed in b598459
