### ISSUE TITLE
Server browser: scrolling with keys ignores filter settings

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1634]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When filters are activated in the server browser using up/down cursor keys to scroll through the server list also scrolls over servers that arent listed because of the filter settings.

**Steps To Reproduce**
-Open server browser
- set filter for e.g. not empty, not full, not passworded 
- use the cursor up/down keys to scroll through the list. 
- servers get selected that are not shown due to filter settings

Expected: Keys only scroll through the list of visible servers when filters are active.

**Version**
9.0.4 Win10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad85f1fc60647002b6b535494e7f5eb70005a17f (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
