### ISSUE TITLE
Reactor crash when melt-downing it

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1636]
After a long journey, we couldn't dock, so and I put in two rods, set fission to max, and set turbine to 0 and it crashed before it caught on fire.

[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/3288890/crashreport.3.log)

https://www.dropbox.com/s/435etsnhmpuorgv/Barotrauma.exe.7900.dmp?dl=1

**Comment by Rokvach** [comment]
Tested, this issue has been fixed. Closing.
