### ISSUE TITLE
Placement of a water sensor (or other components) during gameplay

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1638]
When placing a water sensor, there is no way to place it back on the floor of the sub. When your character is crouched, the water sensor can be placed slightly above the ground, but not on it.

This is an issue because water will still remain if the pump is triggered by a water sensor.

**Comment by Regalis11** [comment]
The item placement improvements in https://github.com/Regalis11/Barotrauma-development/tree/feature/item-grid-placement gets rid of this issue

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
