### ISSUE TITLE
Status Monitor does not require power even though it claims it does

### ISSUE THREAD

**Issue by mGuv** [Regalis11/Barotrauma#1639]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Status Monitor terminal seems to ignore the power requirements defined in the sub editor. Even when totally disconnected from everything, the status monitor still works - allowing you to see water and oxygen levels in your entire sub for free.

**Steps To Reproduce**
- Place a status monitor somewhere inside of a sub, do not link or connect it to anything
- Load that sub in to a sandbox mission
- Flood a couple rooms for fun
- Use the status monitor
- Observe that it correctly shows the sub's state, even though it has no power

**Version**
v0.9.0.4 on Windows 10 64-bit

**Additional information**
Short video: https://streamable.com/xz8yj

**Comment by Regalis11** [comment]
Ping @ezjamsen 

We could make the status monitor shut down when it doesn't have power, but that would make breaches way more difficult to locate and repair when a flood powers down the sub. Maybe we should instead remove the power requirement or make the status monitor somehow perform worse when there's no power?

**Comment by mGuv** [comment]
That reminds me, I forgot to mention but it will drain power if you wire it up.

**Comment by lostinplace** [comment]
what about adding a redundant battery power supply that only drains when the main power supply is down

**Comment by ezjamsen** [comment]
Let's shut it down when it's unpowered to start with, and if it creates too much frustration or difficulty, we'll react accordingly.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8683ac9d5f5cdb03b4178b3de090031f5896e449 (private repo)

**Comment by Rokvach** [comment]
Tested, status monitor turns off correctly now when there isn't power to keep it on. Closing.
