### ISSUE TITLE
A small issue with reactor's sliders

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#1642]
Holding the left mouse button does not prevent you from switching from one slider to another, making it possible to accidentally change the fission rate to unwanted values.

Since you are mostly watching the display, you may easily miss your mouse moving away from the slider you are working with.

Video example: https://www.youtube.com/watch?v=eZ6fe5CYwwA

**Comment by Rokvach** [comment]
Tested, this issue has been fixed in 3b58491, closing.
