### ISSUE TITLE
New Update broke dedicated

### ISSUE THREAD

**Issue by Dekkar1218** [Regalis11/Barotrauma#1644]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since new update, dedicated is kinda broken. clientlist in server console dosn't work anymore, as well as logs of players doing things isn't kept like attacking, etc. and it dosn't show players names when they connet just shows "Successfully autehnticated client via steam steamid:125-9105981" . Also as the host, host cannot connect to own server anymore.

**Steps To Reproduce**
host a dedicated

**Version**
latest release 

**Additional information**
just started happening today

**Comment by Dekkar1218** [comment]
Barotrauma Dedicated Server crash report (generated on 6/14/2019 12:07:45 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.9.0.6
Selected content packages: Vanilla 0.9, The Iron Gear, General Purpose Submarine., Eel, The Hammer, Bullshark V2, S(ub)Long Mk4, Aegir Mk. III (0.9 Remake 1.4, Updated!), The Syger VI, Type VIIS, Capelin MkV, Sweet Pea, 3_Tigerfish_UCN, Ghal Maraz, The Pill. EDS Mark Ib, The Coffin, RU-46 , Cyclops, Orca MK3, Dugong MKII Super Super, Ocean Glider, Slavetown MK2, Nautilus X, HeeYaiSSS, Kaguya MK I, Mercury III, Razorback, EK Coseus Mk-II, U-251 NOVUS, GliderStation. ( Prot. by Vepr ), DeathCrow, Ulysses, EK_Spritely_Mk-I, Mini Submarini, The Infiltrator 2.2, Type VIIS - Lite English , Duntless 2b, Parallax, Orca (Retrofit), Barracuda V1, Nautilus, Typhon 2.0, Twin Tails, SCS Kraken, Union Mk1, Polaris, SCS Barracuda, Humpback DMW V4, KuyYaiMak, The Iron Tomb, Ageir MK XVII, Union Mk1.3
Level seed: NVrdu3Xc
Loaded submarine: Ageir MK XVII (CE714BE53068CD716B4B52E7F70D9A13)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object.
Target site: Single GetGarbleAmount(Barotrauma.Entity, Barotrauma.Entity, Single, Single)
Stack trace: 
   at Barotrauma.Networking.ChatMessage.GetGarbleAmount(Entity listener, Entity sender, Single range, Single obstructionmult) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Networking\ChatMessage.cs:line 129
   at Barotrauma.Networking.VoipServer.CanReceive(Client sender, Client recipient) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\Voip\VoipServer.cs:line 86
   at Barotrauma.Networking.VoipServer.SendToClients(List`1 clients) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\Voip\VoipServer.cs:line 55
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\GameServer.cs:line 353
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\GameMain.cs:line 283
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Program.cs:line 36


Last debug messages:

**Comment by Regalis11** [comment]
>clientlist in server console dosn't work anymore
Unfortunately I wasn't able to reproduce this. What happens when you enter the command, does it output anything at all? Is there an error message?

>as well as logs of players doing things isn't kept like attacking, etc. 
Wasn't able to reproduce this either. Does it not save the server logs? Or do you mean you can't see them when looking at the "server log" menu as a client? Are you sure your client has permissions to view the logs?

>and it dosn't show players names when they connet just shows "Successfully autehnticated client via steam steamid:125-9105981" . 
There should be a "someplayer joined the server" message after the authentication messages (assuming the client can join and is not rejected because of, for example, the whitelist or banlists).

>Also as the host, host cannot connect to own server anymore.
Do you have whitelists or banlists enabled? What kind of an error message are you getting when trying to connect? How are you trying to join the server (i.e. through the server list or directly based on IP)?

As for the crash log, we pushed a hotfix just now that should resolve the issue. Sorry for the trouble. :/

**Comment by Dekkar1218** [comment]
I reinstalled barotrauma and it seemed to have fixed the issues. However when I enable VOIP it causes server to crash.

**Comment by Dekkar1218** [comment]
Also after server is running for 5 to 10 minutes, wont allow new players to connect, players receive "Unable to connect to server" and in the console all I see when they try to connect is Sucessfully authenticated client via steam (id). then it later says failed to authenticate client via steam

**Comment by Dekkar1218** [comment]
https://ibb.co/8mQLqJ6

**Comment by Dekkar1218** [comment]
Annnnd now hosting won't work at all. I can boot it up fine, but no one can connect. 
They get this ---> https://ibb.co/pJhBLZK and I receive this on my end.---> https://ibb.co/yR4dBTx

**Comment by Dekkar1218** [comment]
https://ibb.co/2ycnqM4  <-- enabled verbose logging in console that has more infor that may help?

**Comment by Dekkar1218** [comment]
completely deleting the barotrauma server, downloaded submarines, as well as completely unsubscribing from everything seems to have fixed it for now.

**Comment by Dekkar1218** [comment]
Found part of the issue. Something to do with the banlist, I had rebanned a trouble player, then got the same issue as above people not able to connect. I deleted the bannedplayers.txt in data and server magically works again.
