### ISSUE TITLE
Need higher difficulty settings

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#1646]
Experienced players need higher difficulty settings.

We finished 5 MP-campaign runs ( ~10-15 missions each, 100 difficutly, vanilla subs, start to center ring). Even with just 4 somewhat experienced players the missions are mostly challengeless cakewalks. There were a few surprises but not often enough to pose a real problem.
Once a solid crew has 6 (or even more) players we couldnt find any kind of challenge besides the endworm. Sad Panda.

We need a way to be allowed to unlock the difficulty settings and put difficulty into overdrive. No problem if we have accept to a popup warning that difficutly might be cranked even into absurd levels, but we need to be able to do that at least. We want to be allowed to set a higher challenge than the current difficutly slider allows. Please.

(Yes, we are aware that most public servers might barely finish missions on available difficulty settings, but thats not what this report is about. This is not a request to change those.)

**Comment by thegrb93** [comment]
The campaign is supposed to start easy. Yeah, it's a bit slow to begin with. Would be nice to have the option to start at full difficulty maybe.

**Comment by CurePindal** [comment]
"The campaign is supposed to start easy"? Sorry, but your comment makes no sense?!  I clearly stated that we ran campaigns 10-15 missions in. Usually we started a new campaign when we reached the center.
At no point I was talking about the start of a campaign.

**Comment by thegrb93** [comment]
Oh, 5 MP-campaign runs sounded like you just did 5 missions. Didn't see the ~10-15 missions each

**Comment by CurePindal** [comment]
Ah ok, that makes sense! But no, I think challenge-wise we turned the game completly upside down again, hehe.

**Comment by Regalis11** [comment]
I think this is a good idea (and in general having more options to adjust the difficult in general)! The issue tracker is not for feature requests though, so I'll close this, but in any case I believe we'll be looking into this in the near future.
