### ISSUE TITLE
Server selection screen clipped in windowed mode

### ISSUE THREAD

**Issue by mlooney** [Regalis11/Barotrauma#1648]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
in windowed mode, at any resolution, the multiplayer server selection screen is positioned off the edge of the window, and unusable. Also strange text rendering bug on "SERVER", S is smaller than other characters.

**Steps To Reproduce**
select a multiplayer server in windowed mode

**Version**
macOS 10.14.6

game version 0.9.06

![image](https://user-images.githubusercontent.com/3905/59534588-556d6180-8eb4-11e9-99e2-4546c8cf977f.png)

**Comment by mlooney** [comment]
i should point out that screenshot is of the entire game window (you can see a bit of background text on the left edge).

**Comment by mlooney** [comment]
restarted the game, issue disappeared.

**Comment by thegrb93** [comment]
So it's only when you switch to windowed mode the problem happens. After restarting it is fixed.

**Comment by Rokvach** [comment]
This has been fixed, closing.
