### ISSUE TITLE
Cannot run the game on Linux

### ISSUE THREAD

**Issue by Inhumanthree1** [Regalis11/Barotrauma#165]
I am using the operating System Solus. However, after installing the packages listed in install.sh and running Launch_Barotrauma, I receive these errors.

AL lib: (WW) FreeContext: (0x2639510) Deleting 16 Sources
AL lib: (WW) FreeDevice: (0x2b33780) Deleting 1 Filter

The game opens for about half a second and then proceeds to crash.

**Comment by Inhumanthree1** [comment]
Whoops, forgot to post the crashlog.txt

https://pastebin.com/4zbJq8Rb

**Comment by Rokvach** [comment]
I don't think this is a issue anymore, closing.
