### ISSUE TITLE
Traitors have opposing goals

### ISSUE THREAD

**Issue by gustavlasko** [Regalis11/Barotrauma#1652]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When there is more than one traitor, the traitors can have opposing goals, yet the same code words

**Steps To Reproduce**
1 Started multiplayer campaign
2 Had 4 people join
3 Started round
4 Two of them were traitors. One had the mission to kill the captain, the second had the mission to kill the first traitor

They both had the same code words. While two teams of traitors on different missions would make sense, having the same code words would not, as they would both assume they are on the same mission.

**Version**
0.9.04

**Additional information**

**Comment by BillCombs** [comment]
Perhaps it could make sense if we assumed that one of the traitors was some kind of a double agent?

**Comment by gustavlasko** [comment]
Checked in with my friends, turns out the traitors actually had different code words, I think this is WAD.
