### ISSUE TITLE
[Uncommon] Block length does not match with it's complement error when joining servers

### ISSUE THREAD

**Issue by databasetd** [Regalis11/Barotrauma#1654]
- [*] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I join a select few servers it kicks me out immediately with an error stating that the block length does not match with it's complement.

**Steps To Reproduce**
1. Join a server
2. Hope it kicks you out? Not sure, you'll need to look into this further as this issue only happens on a few servers (some full, some empty) and varying ping.

**Version**
v0.9.0.6

**Additional information**
![image](https://user-images.githubusercontent.com/28366123/59553897-d20e4780-8f69-11e9-9acd-4cd5d471c18b.png)

**Comment by databasetd** [comment]
Updating this issue since this is still occurring with another error.
![image](https://user-images.githubusercontent.com/28366123/61645492-b4bd4f00-ac74-11e9-97fd-0f664a39b33b.png)

**Comment by Rokvach** [comment]
I haven't seen anyone else having this issue, has it occurred since the last report?

**Comment by databasetd** [comment]
Not since this version. Will close this issue.

**Comment by ekqvist** [comment]
Thank you for taking the time to reply and close this issue. We'll still keep it open until we have reviewed it on our end.
