### ISSUE TITLE
Character name cannot be accessed if the character's ragdoll is deleted

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#166]
This is a well-known issue, but shrimps eating someone's body causes multitude of issues. One of those issues is that the player's chat name in dead chat is invisible.

I am not sure of all the issues related to this but it honestly seems like the problem could be solved by accessing Character.GetName(); method or something similar.

**Comment by juanjp600** [comment]
Did https://github.com/Regalis11/Barotrauma/commit/e323e9dc71855b2dc2dc3480ab892fcba100e4e0 not fix this?

**Comment by Crystalwarrior** [comment]
Oh right, this is a 7.0.1 issue. No idea if it's fixed in the latest release.
