### ISSUE TITLE
VOIP issue when joining a server

### ISSUE THREAD

**Issue by MysteryMan21333** [Regalis11/Barotrauma#1663]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bug iv been having is when I join a server even when it has VOIP enabled telling me, "Could not start voice capture; Suitable capture device not found".

**Steps To Reproduce**
There is really no steps have your Voip enabled and join a server.

**Version**
Barotruama vanillia v0.9.0.6. Windows.

**Additional information**
Iv made sure everything was good in my end testing my headset a few times to make sure Iv been speaking with a few other players typing and they have also had this happen some saying it only happened once and when rejoining it began to work. Im using a wireless Turtlebeach 420x headset it was working fine when I first played the game but after the patch it just stopped allowing me to connect with my headset.

**Comment by Rokvach** [comment]
A bit late for an answer but I've seen similar issues and in some cases turning off "Allow applications to take exclusive control of this device" in the headset sound settings has helped, it seems like Barotrauma doesn't have a high priority by default over the device so having another application open which has rights for the mic might block its usability from Barotrauma

**Comment by Rokvach** [comment]
This shouldn't be a issue anymore as there's been multiple improvements to the VOIP handling
