### ISSUE TITLE
Game crashes when setting limb scale to 0

### ISSUE THREAD

**Issue by Arlojmikk** [Regalis11/Barotrauma#1665]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenevr limb scale on anything is set to 0 or below, thegame crashes

**Steps To Reproduce**
Go into console, enable cheats, set limbscale to 0.

**Version**
0.9.0.6
**Additional information**

**Comment by itchyOwl** [comment]
Fixed.

**Comment by Arlojmikk** [comment]
Good Job
