### ISSUE TITLE
Large ships can't dock with small one

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1669]
I use orca's top docking hatch docking with selkie's bottom docking hatch
Error occurred
Creating hulls between docking ports failed,the upper hull seems to be very far from the lower hull.
But the small ship can dock with any hatch normally

Version
v0.9.0.6 (Win 10 Steam)

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
