### ISSUE TITLE
If you control a mantis/husk/etc. you won't speak as them :(

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#167]
e.g. control Husk, say something - no speech bubble above husk, message simply comes out in global chat or somewhere else completely.

**Comment by CryIz** [comment]
Если дать управление ботом обычному игроку без прав, то он будет говорить, но только в чат, который никто не увидит кроме тех, кто также управляет ботом. При этом их ник измениться на имя того существа, которого им выдали.
If you give control of the bot normal player without rights, he will speak, but only in the chat no one will see except those who also manages the bot. However, their nickname changed to the name of the creatures, which they were given.
![image](https://user-images.githubusercontent.com/33912761/34074737-db14c3a0-e2c6-11e7-9857-114dfe41d746.png)

**Comment by Regalis11** [comment]
Fixed in 7d7c950
