### ISSUE TITLE
Bots don't hang up diving suits

### ISSUE THREAD

**Issue by gustavlasko** [Regalis11/Barotrauma#1670]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are slobs and leave their diving suits on the floor wherever they come out of water when they are done with them. They should prioritize hanging up their suit unless there is some sort of life threatening emergency (in which case they probably should de-prioritize taking off their suit). Furthermore, they should probably prioritize switching out the oxygen tank so the suit is fresh, maybe based upon a competence or safety conscious rating. 

**Steps To Reproduce**
1) Play a game with a bot
2) Wait for them to don a diving suit
3) Wait for them to finish their task and emerge from the water
4) Pick up their suit and hang it up and make sure it's got a full tank if O2 so that you don't die during the next crisis.

**Version**
0.9.0.4

**Comment by itchyOwl** [comment]
Unimplemented. On the todo list.

**Comment by Rokvach** [comment]
Tested on multiplayer, the AI doesn't fully prioritize returning the suits once the leak has been fixed, instead they can enter in to idle state or take another task before returning the suit. Only 2 out of 6 bots placed the diving suits back in to the lockers, 3 tossed the diving suits on the ground next to the locker (Inside the top docking hatch airlock in Typhon) and 1 is still walking around with the suit on. 

Also noticed that all of the mechanics went to repair the single leak (not ordered to do so) where only one of them would of been enough.

**Comment by itchyOwl** [comment]
On the team work see #1124.

**Comment by Rokvach** [comment]
Haven't spotted any issues with this. Moving to Done.

**Comment by Graftax** [comment]
This was moved to done but I still have bots dropping diving suits all over the ship. I end the round with my lockers empty and suits strewn about.

v0.16.6.1 using Kastrull

**Comment by VineFynn** [comment]
Same problem, unmodded using Typhon 2.

**Comment by itchyOwl** [comment]
It's intentional that they drop the suits when they are doing something more important. The bots that are not busy, should clean them up.

Bots dropping suits in airlocks should be fixed in Unstable. See #8471.
