### ISSUE TITLE
Publishing Workshop item failed. Error publishing changes: Limit Exceeded (False)

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#1671]
Couldn't publish a mod in the workshop. I've also received a lot of raports with the same error message. Not sure if this is occurs occasionally or always. Need to give it some testing.

![image](https://user-images.githubusercontent.com/5370738/59654515-264e3d00-919f-11e9-9783-a8e6f745db01.png)

The item is visible, on Steam, but lacks the content:
![image](https://user-images.githubusercontent.com/5370738/59654542-53025480-919f-11e9-99dd-bef584b7d287.png)

It's possible that there are many reasons for this error.

One possible reason is that the thumbnail for the mod is too big. Apparently it should be less than 1mb (https://steamcommunity.com/app/346010/discussions/2/527274088402272832/).

Another reason for the issue could be that there is not enough space in the Steam Cloud or that the Cloud is disabled.

In my case, however, none of these apply: the Cloud is enabled with 500mb of free space and I'm using the default thumbnail.

**Version**
0.9.0.6 Windows

**Comment by itchyOwl** [comment]
The same issue on Kerbal Space Program: https://bugs.kerbalspaceprogram.com/issues/19289. Can't find a solution there.

**Comment by itchyOwl** [comment]
Doesn't seem the matter on which computer you are. Clean install doesn't work either. So it's somehow related to the account?

**Comment by itchyOwl** [comment]
This workaround seems to work: https://steamcommunity.com/app/602960/discussions/1/1646544161771479822/

**Comment by itchyOwl** [comment]
Remember to relog into Steam or you can't use the Steam Cloud or see your new mod in-game.

**Comment by littlewolf120** [comment]
I've also had this issue even when trying to publish new items, somehow after about 8-12 publish cycles it locks you out completely.

I had no thumbnail when doing such

**Comment by FamiliarBreakfast** [comment]
After an hour of dealing with it still not working even though I used the workaround and had a small preview image size, I found that uploading without a preview image let me do it.

**Comment by FamiliarBreakfast** [comment]
So it seems that sometimes SteamCMD requires you to run is admin/root when uploading a preview image.

**Comment by BogdanWOOP** [comment]
One of the users suggested a solution and **I successfully tested it!**
![kSTI51w](https://user-images.githubusercontent.com/50588328/67633653-75317f00-f8c3-11e9-9930-4c48db30a579.png)
> "In the system folder C (Not in the game directory) there is a duplicate folder Daedalic 
> Entertainment, which stored more than 700 save files. After their removal the problem with Steam 
> Cloud no longer appeared"
[Discussion](https://steamcommunity.com/app/602960/discussions/1/1646544161771479822)

I decided to test it myself, and recorded a video about it.
https://drive.google.com/file/d/1tyXRhiHGJK-dg5CbslbVVctwwFmpYj13/view?usp=sharing

Text instructions:
1. Navigate to the folder: C:\Users\User\AppData\Local\Daedalic Entertainment GmbH\Barotrauma
2. Delete all ".save" the files (In the video I deleted everything, DON'T DO IT!)
3. Restart Barotrauma
4. Publish your mod in Steam Workshop!

Also, make sure that Steam Cloud has not recovered these files
I hope this will help...

**Comment by Rokvach** [comment]
There's been some remedies to prevent this from happening by limiting the amount of save files, by not saving campaign saves to clients for example.

**Comment by Rokvach** [comment]
This is always caused by a excessive amount of save files, I don't think we can fix this easily without somehow limiting the amount of save files players accumulate during their time playing

**Comment by tony-pitchblack** [comment]
I am having exactly the same problem with uploading an item to steam workshop, but with a different game (KovaaK's). Can someone explain what the proposed solution does on a lower level? Is it applicable in my case?
![err2](https://user-images.githubusercontent.com/36202157/206259686-3cfcde4a-76b1-4c50-8ed6-b5101232cf24.png)
![err1](https://user-images.githubusercontent.com/36202157/206259693-d3f8ed35-9b41-45c0-bdf4-60aede963dc7.png)
