### ISSUE TITLE
[Crash][Bug] Minning limenite crashes the game

### ISSUE THREAD

**Issue by TheGoo-ooo** [Regalis11/Barotrauma#1673]
**Description**

**Steps To Reproduce**
- Start a campaign, multiplayer
- Mine Ilmenite
- You get kicked out of the game because of a missing object

**Version**
Vanilla 0.9

**Additional information**
![limenite_hell](https://user-images.githubusercontent.com/23033543/59713522-ebd0b880-920f-11e9-8420-60347d9de363.png)

**Comment by Regalis11** [comment]
I'm pretty sure this is a duplicate of #1603. We have implemented a fix for it, so it should be resolved in the next patch.
