### ISSUE TITLE
Russian server name

### ISSUE THREAD

**Issue by Morb0** [Regalis11/Barotrauma#1677]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When write russian server name in config file (serversettings.xml), it look like:
![image](https://user-images.githubusercontent.com/14136326/59878885-1d818500-93b2-11e9-93b5-1f270910546e.png)

**Steps To Reproduce**
Write russian server name in config file.

**Version**
v0.9.0.6
Debian 9

**Additional information**
File encoding from Notepad++ set to UTF-8

**Comment by 0ArturkA** [comment]
Perhaps you need to put the correct encoding, but I have already tried many and it does not work.

**Comment by Morb0** [comment]
Found answer
![image](https://user-images.githubusercontent.com/14136326/59922286-236e7900-9439-11e9-89b6-33775f6049df.png)
