### ISSUE TITLE
Server gamemode config

### ISSUE THREAD

**Issue by Morb0** [Regalis11/Barotrauma#1678]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Default generated config file have `GameMode="SandBox"` param, but if change it, gamemode will still remain `SandBox`. For changing gamemode need to set another param `gamemodeidentifier="mission"`.

**Version**
v0.9.0.6
Debian 9

**Comment by 0ArturkA** [comment]
Also:
`SubSelection` => `subselectionmode`
`ModeSelection` => `modeselectionmode`

**Comment by Regalis11** [comment]
Fixed in 76d4d55
