### ISSUE TITLE
Display the name previously used by a player if they rejoin a server with a different name

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1679]
Seriously, griefers keep using this to get away.

**Comment by thegrb93** [comment]
Or just ban players who have more than one votekick vote and leave.

**Comment by littlewolf120** [comment]
BanID via console bans steam ID and you can find such in the server logs when checking who did what.
I use this often to find griefers who leave after adding welding fuel to all the tanks

**Comment by thegrb93** [comment]
I'm talking about the times when there's no admin and the only solution is votekick.

**Comment by hubismal** [comment]
it would probably be better to just tempban the IDs upon votekick, and to have the timeout increase as more violations occur. Seems contrived to display the old name, I would even settle for just being able to see the person's steam username in the lobby.

**Comment by thegrb93** [comment]
@hubismal the problem is they leave before the votekick, change their name, return to continue griefing, repeat.

**Comment by hubismal** [comment]
> @hubismal the problem is they leave before the votekick gets enough votes, change their name, return to continue griefing, repeat.

Having actual steam names in the lobbies would help identify them quicker, and votekicks could be stored as a value per player on servers? so that they would be saved upon the player rejoining.

**Comment by thegrb93** [comment]
That wouldn't help because they can just change their steam name too. Storing the votekicks in addition to displaying their previous name on join would help too.

**Comment by littlewolf120** [comment]
If noticed with the game that no matter what every new player has a new id number on clientlist, thus the game does store such or at least only increments. This may also mean that users rejoining may be listed back under their old number

**Comment by thegrb93** [comment]
How do you see their number?

**Comment by thegrb93** [comment]
That doesn't help unless you write their number down before they leave and can convince everyone else its the same guy still.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
