### ISSUE TITLE
Terrain Generation and Submarine Size

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1681]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not every submarine's dock port is in the center of the submarine,Or the highest point.We need more space at the beginning and at the end., 2.5 times the length of the submarine, to be exact.
I used editlevels.But I didn't find out how to adjust the initial width.Some people say that the width of the passage will take care of the size of the submarine.But the wall on the left is a diagonal line to the right down.The lower left corner of the submarine was embedded in rocks from the beginning.

**Steps To Reproduce**
Build a submarine 200 meters long and 50 meters high
Start the game

**Version**
9.0.6

**Comment by SaulApostle** [comment]
![1TMGD%(5O_QP2OXJ3@F0@@L](https://user-images.githubusercontent.com/11502419/60123759-c8cb7900-97ba-11e9-9535-550042891acb.png)
![`2{OO9Z_Y4_$} 85`EZFH7D](https://user-images.githubusercontent.com/11502419/60123764-cb2dd300-97ba-11e9-81a7-e3720fd43b78.jpg)
![7C7RN4V4`7~}PRJ} Y19U%V](https://user-images.githubusercontent.com/11502419/60123773-cec15a00-97ba-11e9-8cbf-5b3e0c32698f.jpg)

**Comment by Regalis11** [comment]
Found an issue - the position of the submarine's docking port is taken into account when determining where to place the outpost, but the position of the outpost's docking port isn't. This caused large submarines to clip with the walls when the outpost's docking port is offset from the center. We've fixed the problem now, so this should be resolved in upcoming updates.

The game does try to compensate for the size of the sub when generating the level, but if the submarine is excessively large (such as the thing in your second post), it may not be able to fit through the level. I think we need to add a warning about this to the sub editor.

**Comment by SaulApostle** [comment]
> And as a side note, you don't actually have to dock with the outpost at the end of the level to proceed. You can also stop the submarine close to it and swim the rest of the way.

I docked the outpost with my attached submarine, then docked the attached submarine with my mother ship.So I found that bug the big ship could not dock the small ship.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/64451b0 (private repo)

**Comment by SaulApostle** [comment]
![314000-fa89ee605637a7fa3ed1d79c8c0d208b](https://user-images.githubusercontent.com/11502419/60344522-542a5180-99e9-11e9-96a3-447ea9d6bbb1.jpg)
