### ISSUE TITLE
Ladders blocking wiring in editor

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1685]
While trying to wire up relays close to a ladder, it doesn't allow me cause the ladder hitbox is always in the way, items that don't have any wiring interaction should probably be unselectable while holding a screwdriver. Also the red box around such terminals that cause it to not be selectable when clicked is somewhat hard to work with.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cec5c4adf4a5c1bf3bce7a3f322e3c35b9e0a759 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
