### ISSUE TITLE
Make items expandable

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1688]
I had an idea for battery chargers to be expandable so you guys could have it so you put in a number and it'd basically replicate the image like a photoshop copy / paste job to expand such items so battery holders could be a single cell dotted around the ship or a multi cell with 8+ on it depending on the number put in.

This could also be extended to the GUI so a single charger case may show in game but the inventory for such could be 20 batteries on the GUI so that less image work is needed in terms of scale or size to adapt it to such things. 

Another thing chad husk kinda mentioned was possibly making it expanding like the walls so it's a repeating texture that can be placed with such usability but less effort needed for design.

**Comment by Regalis11** [comment]
The issue tracker is not for feature requests. But a nice idea in any case, we'll consider it!
