### ISSUE TITLE
Allow picking up diving suits

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1689]
As like the other items you pick up, i feel that diving suits should allow picking up like crates then equipping as all other items require. Diving masks, armour, wearables all require the person to pick them up before putting such on.

Unless in a O2 warning is showing on screen, this should be a thing that requires a second click to put on.

**Comment by hubismal** [comment]
I think they should still be autoequip, but you should have the option to double click them to put them in your hands in order to not waste oxygen.

**Comment by BlueTheKing** [comment]
G to grab, E to equip.

**Comment by hubismal** [comment]
> G to grab, E to equip.

based blue with the best obvious ideas i didn't think of

**Comment by littlewolf120** [comment]
while yes G / E would be good, it doesn't fit with the already designed scuba / armour and such else which requires picking up before putting on, as such following the current norm with the other worn items would be better. This would stop it feeling different when even crates use a click to pick.

I'd rather the system be straightforward than changing for 1 item, only real difference would be a suit would be in the large items crate style slot. you wouldn't be able to hold it with other things inside the inventory.
