### ISSUE TITLE
Баг с рацией. / A bug with the radio.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#169]
Рацией можно пользоваться даже когда она не экипирована. При этом не тратится батарейка.
The radio can be used even when not equipped. It does not spend battery.
![radio](https://user-images.githubusercontent.com/33912761/34074835-f3204b2a-e2c8-11e7-9c1c-4f6599e28b6f.gif)

**Comment by Crystalwarrior** [comment]
Perhaps the radio should just consume battery the entire time its on, and you should be able to enable/disable it?

**Comment by Regalis11** [comment]
Fixed in 671f59e
