### ISSUE TITLE
Torpedo / nuke terrain clearing

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1690]
It'd be kinda nice if a torpedo / nuke could clear a path for the sub to get through, this would allow subs that are large to clear a hole and also make some alien ruins accessible as sometimes they spawn in areas where there's no entry to such at all.

Sometimes alien ruins spawn a good 400 meters up a small crevasse which would require an entire toolbox of oxygen bottles to full explore alone somewhat.

**Comment by hubismal** [comment]
Making the terrain deformable is a pretty big task. It's not impossible, but I'm not exactly optimistic this will be added, especially with an actual planned rewrite of the mapgen.

**Comment by NoManColonies** [comment]
instead make some ice chunk pushable or movable that would be nice.
