### ISSUE TITLE
Oxy / welding tank mixing

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1691]
Please make a warning UI element when a welding tank is installed into a suit / mask, even if it's above the worn item boxes, it'd be nice to have a little red ! icon in a white box when such happens so people can tell without having to go to read what's wrong.

Doing such will allow conveyance of what's going on instantly without having to use words. It may also be good to include something for colour blind modes so they can tell the diff as well when such are in racks.

**Comment by hubismal** [comment]
Once as it happens once you should be pretty knowledgable when you see your health bar rapidly going down and your character suffocating. It's not exactly subtle at the moment.
I can see either regalis doing something about this, or players actually having to learn to pay attention when they do things in public matches like everyone had to do in legacy.
