### ISSUE TITLE
Tiny drone's hull bugs out after undocking

### ISSUE THREAD

**Issue by madmax3004** [Regalis11/Barotrauma#1692]
- [Y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I created a tiny drone with a single hull-ballast inside of the drone's walls, upon undocking from the station, the drone drops like a brick. Inside of the submarine editor it doesn't mention any issues with buoyancy control. If I use editsubs in game after I undock the drone, however, it says the hull is inadequate for buoyancy control.

**Steps To Reproduce**
I have attached my drone and the test box to which it is docked in my tests. Simply undock the drone from the station using the button. If it doesn't immediately fall, swim past it to activate its motion controlled following logic, the moment the ballast tries to anything about the hull, it will fall like a brick instantly. The nav station on the test box can be used to control the drone and is linked by wifi to its engine & ballast; activate the remote controls using signal #1.

**Version**
V0.9.0.6 Windows
**Additional information**
/

[Troubled Subs.zip](https://github.com/Regalis11/Barotrauma/files/3315889/Troubled.Subs.zip)

**Comment by Regalis11** [comment]
The problem is that you've wired the motion detectors to the "set_targetlevel" connection of the pump. The connection expects a signal between -100 and 100 (that generally comes from a nav terminal), -100 being "pump all the water out" and 100 "pump the room full of water". When it receives a "1" signal from the detectors, it pumps the entire drone half-full of water, causing it to sink like a brick.

**Comment by madmax3004** [comment]
@Regalis11 are you sure that's the only issue with it? It also did that when I had it set to 0, and when opened in the editor via console (after undocking) it said "inadequate ... for buoyancy control".

**Comment by Regalis11** [comment]
That's to be expected, 0 means "neutral buoyancy" which in this case would mean the entire sub fills up with water half-way (because the entire hull space of the drone is used as ballast).

**Comment by madmax3004** [comment]
So depending on the % of hull filled with water, a hull can show up as inadequate for buoyancy control? Thanks!
