### ISSUE TITLE
Allow content packages to download to clients like subs do?

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1693]
Just an idea, title basically says it all tho.

It'd be nice for such to self enable when joining a server and disable back to the clients settings when not on such. I wouldn't guess it's too much work to add a soft reload of the game that doesn't require a full restart but keeps you on that server?

**Comment by hubismal** [comment]
It's actually a lot of work to make the game load content packages on the fly. As it is right now, everything is loaded at startup, so a lot of things would have to be restructured. It's not leviathan, but it's not a small task like you describe it. Also note that feature requests should go anywhere except github.

**Comment by Regalis11** [comment]
We've been thinking of implementing this as well, so there's a high chance it'll become a thing in future versions. But as said by hubismal, the issue tracker is not for feature requests.
