### ISSUE TITLE
Unknown error, most wires were locked on the ship to important stuff

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1694]
No other info can be supplied, no mission selected, using modded typhon with only base game package
![{6DB7FB82-7D67-421A-B0D8-61CAC2D97CB5} png](https://user-images.githubusercontent.com/49542992/59962890-c8b74900-952e-11e9-9bd2-0682ce5cb8b5.jpg)

**Comment by Regalis11** [comment]
Do you remember which game mode you were playing when this happened? If it was the campaign mode, this is most likely caused by #1603 (which has been fixed for the next patch).

**Comment by littlewolf120** [comment]
Yes, was campaign, alao ask chad / rok about the issue I found, I gave them direct info, too important for here.

**Comment by Regalis11** [comment]
I made a new issue report with some more information and details about these errors, lets try to compile information about the problem there from now on: #1815
