### ISSUE TITLE
Fix wiring / reset components

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1695]
While fix hull / fix items are nice for dev console, it'd be nice to have a way to fix wiring / components without cheat enable, thus if anyone changes something that could only be fixed by starting an entirely new campaign it could be reverted as an anti grief measure in games without traitors. Then again it'd also be nice if turning traitors off locked such things as well as suits from having welding fuel or such.

Basically giving a safety for people who run co-op servers, even if such co-op mode caused such fixes to be enabled to stop said grief. The only thing the person could do then would be trying to drop everything off the ship in crates or in their body. Even have like a recovery fee to have the station return a listing of items that were dropped off the ship. 200 credits to return all crates / shells / items as a recovery fee.

**Comment by hubismal** [comment]
you're supposed to put feature requests on anywhere except github, github is for actual issues. The reason this is a policy is so devs can prioritize actual crashes and issues and so people don't flood the github with massive amounts of feature requests just like you did.
I'm not saying it's a bad idea, just make a forum account and put your ideas on the UTG forums.

**Comment by littlewolf120** [comment]
On the discord, people suggest dropping things on github quite a bit, as such this is why i dropped such here, also this github also does have labels of feature request being seen on it. With both bits of information i felt it wasn't bad to put such here.

**Comment by hubismal** [comment]
>also this github does have labels of feature request being seen on it
as far as I know, the label is really just there so that the devs themselves can put up their own "feature requests" or ideas that they want to implement immediately. Stuff like faster ways to kick people, quality of life improvements, stuff that's critical and while not technically a bug needs to be added asap.
