### ISSUE TITLE
[Feature Request] Depth charge corpse filling

### ISSUE THREAD

**Issue by Chocobro** [Regalis11/Barotrauma#1697]
Playing this with some friends the other day, we put some UEX in a depth charge, and it got me thinking.
Could a corpse (alien or otherwise) be stuffed into one of these things? Sure, you'd need to probably chop it up a bit to fit in, but that's fine - especially for traitors that need to get rid of any evidence about their targets.
As an extra thing, you could make the depth charge also trail blood. That way, it'd attract the wildlife (or certain wildlife) a little more than a regular decoy depth charge would.

**Comment by hubismal** [comment]
for future reference, I don't think you're supposed to put feature requests on github atm, but great idea.

**Comment by Chocobro** [comment]
Oh, my bad. Saw another issue with the same tag, is all...I'll google around. Thanks!
