### ISSUE TITLE
Random crash while in respawn shuttle

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#1701]
I think this might be the same as one i've already reported before, but reporting just in case.

https://www.dropbox.com/s/gaktyit4cxl5sd7/Barotrauma.exe.7540.dmp?dl=1

[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/3317453/crashreport.4.log)

**Comment by Regalis11** [comment]
Yep, it seems to be the same issue as #1622
