### ISSUE TITLE
moloch mission outside the map

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1702]
- [x] I have searched the issue tracker to check if the issue has already been reported.
![T BAX3$MAQ97QML` 1P)AIN](https://user-images.githubusercontent.com/11502419/59975750-1a72d880-95ee-11e9-9457-45fc006bbf65.png)

moloch mission outside the map

**Version**
9.0.6

[save 126.zip](https://github.com/Regalis11/Barotrauma/files/3317796/save.126.zip)

**Comment by Regalis11** [comment]
The spawnposition logic fixes in v0.9.0.7 should fix this.
