### ISSUE TITLE
Can't join server with my  own subs enabled

### ISSUE THREAD

**Issue by yaelatletl** [Regalis11/Barotrauma#1703]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You should be able to join a server that doesn't have the same subs as you, without requiring you to disable them

**Steps To Reproduce**
Make a server with workshop content enabled, then make someone join the server with more subs than the server. 

I must clarify that the subs and workshop content are not core packages, just normal submarines

**Version**
Latest Steam Release 23/06/19

**Additional information**

**Comment by Regalis11** [comment]
Fixed for the next patch!

**Comment by Rokvach** [comment]
This is working correctly, closing.
