### ISSUE TITLE
The reason for the ban... Broken?

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#1704]
**Description**
Really? I, like many others, do not have the strength to deal with a huge number of bugs when hosting a dedicated server.
Ban/kick admins can not give: they break the game, and the server will stop letting players. Constantly I am asked to give even BANAL kick to the offender did not interfere with the game.
Sometimes it happens that the administration kick one player, but actually KICKED out of the OTHER!
It is impossible to change the game mode through the console
I understand that this is early access, but I, like others, already just a fire at the fifth point of this "situation".

**With regards to bug:**
![image](https://user-images.githubusercontent.com/33912761/60043660-41520d00-96c9-11e9-886a-ef769814dbd7.png)

**Version**
Latest in steam.

**Additional information**
Windows Server 2016 (RUS). Hosting through a dedicated server. Without SteamCMD.

**Comment by Regalis11** [comment]
It appears you've disabled Steam authentication? I would recommend keeping it on to prevent issues like this.

**Comment by Nevol2110** [comment]
"**Version**
Latest in steam." Namely: 0.9.0.6.

Unban does not work. You have to turn off the server, and manually delete the desired lines.
![image](https://user-images.githubusercontent.com/33912761/60103974-38b11380-9769-11e9-8ebc-896afcb1217e.png)

Steam authentication is not touched, the settings are standard. I use the installed steam client to connect. With SteamCMD did not understand how to work.
![image](https://user-images.githubusercontent.com/33912761/60104087-6c8c3900-9769-11e9-80dd-f8fbcdd811d2.png)

If to issue ban in lobby, then all in order. However now no one can connect to the server because of the ban on IP.
![image](https://user-images.githubusercontent.com/33912761/60104844-ee309680-976a-11e9-8196-0d3c546218e2.png)

If you give a ban during the round, the game is closed. Violator ban is not issued.
![ez_ban_Regalis_top_number_one_in_the_world_not_sarcasm](https://user-images.githubusercontent.com/33912761/60106025-1c16da80-976d-11e9-8329-88f2e6fa8842.gif)
![image](https://user-images.githubusercontent.com/33912761/60105101-626b3a00-976b-11e9-9846-511d1f8c997e.png)

I can't write anything about kick yet.

**Comment by littlewolf120** [comment]
Use clientlist then BanID

You'll never need type a name

**Comment by Nevol2110** [comment]
I know about this. :/

**Comment by Rokvach** [comment]
This seems to be working without issues now, closing this ticket.
