### ISSUE TITLE
[Bug][Graphical][Scaling][0.9.1.0 Testing]Serverlist UI scales poorly on lowest resolution.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1706]
![2019-06-24-231715_523x284_scrot](https://user-images.githubusercontent.com/47284081/60069358-102d0900-96d8-11e9-90d6-78c9b1488251.png)
The newly added sort texts don't seem to scale well (or too well, depending on how you put it). Barely readable on screens like mine.

**Comment by Regalis11** [comment]
Since v0.9.1.0 wasn't released yet, this version of the server list won't be released to the public, and we have since improved the layout so this shouldn't be a problem anymore.
