### ISSUE TITLE
[Feature Request for Usability][Issue][0.9.1.0] Character editor should probably prompt "choose a file" for spritesheet

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1708]
As it is right now, the character creation wizard still requires you to manually navigate to a not-yet-created mod folder for your character and place a spiresheet png there.
![2019-06-25-000152_515x328_scrot](https://user-images.githubusercontent.com/47284081/60070571-c98ddd80-96dc-11e9-884a-3576f6670cff.png)

Now that file uploading works on every platform as of 0.9.1.0 (I tested it), you might as well take advantage of the file upload working, and instead just ask the user to upload a file from their computer that the game will then place as [Charactername].png in the folder or something. Would really make character editing a lot easier and would be the cherry on top of the new character editor overhaul.

**Comment by itchyOwl** [comment]
Implemented.
