### ISSUE TITLE
[Bug report] A bug about coilgun!Only multiplayer mode.

### ISSUE THREAD

**Issue by JettLand** [Regalis11/Barotrauma#1709]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The coilgun shooting angle isn't controllable, when I set the coilgun on my UAV and control it by WIFI.
You can still control coilgun's angle, but not shooting angle.
It happens only in multiplayer mode, singleplayer mode is fine.
![QQ图片20190625204650](https://user-images.githubusercontent.com/52204365/60099974-568f7000-978b-11e9-9908-ffec20734b81.jpg)
![QQ图片20190625204703](https://user-images.githubusercontent.com/52204365/60099978-58f1ca00-978b-11e9-97df-5e9534ac9fe9.png)
![QQ图片20190625204714](https://user-images.githubusercontent.com/52204365/60100006-6ad36d00-978b-11e9-87e6-25613e8b547b.jpg)
This issue also happened to RemoraDrone . @Regalis11 

**Steps To Reproduce**
Choose Remora and play it in multiplayer game, you will see.

**Version**
Barotrauma v0.9.0.6, Windows 7 Ultimate edition.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0091e591ddd59727e0e79568a5bcbbe6cbc56718 (private repo)

**Comment by Rokvach** [comment]
Tested, shooting angle now updates correctly in multiplayer. Closing.
