### ISSUE TITLE
Corrupted save file - while hosting dedicated via exe and joining it

### ISSUE THREAD

**Issue by littlewolf120** [Regalis11/Barotrauma#1710]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description** / **Steps To Reproduce**

Campaign won't save cause save file is in use while running dedicated server beside the game.
I loaded the server from the local save file inside the game dir instead of the appdata and played for a few rounds before it corrupted. Causes it to glitch while it's trying to download itself from the temp server as an update.

I backup the save at the end of the mission, this could also be a cause but it usually isn't copied until just before next round.

Issue says it's failing to compress or such

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Latest at 26/06/19

--------------------------

Possible fix to such issue would be to copy the save to the appdata folder and run it from there, then download it to the exe directory as needed for backup at end / start of rounds.

**Comment by littlewolf120** [comment]
Save file that's broken.
[Lockdown.zip](https://github.com/Regalis11/Barotrauma/files/3325949/Lockdown.zip)

**Comment by Regalis11** [comment]
This shouldn't occur anymore after v0.9.0.7
