### ISSUE TITLE
Save Server Port in Host Server dialog

### ISSUE THREAD

**Issue by d3x0r** [Regalis11/Barotrauma#1711]
I have a home network I manage,and have various things ports on my firewall go to.  I can't seem to find a uPnP provider for Linux, but I have a range of ports like 55000-55999 to this computer, so when I select new server and query ports, it would be nice if they would be remembered for next time I start a server.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/829d599f47d5d1dbdb9e572d5310626059a32cbe (private repo)

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
