### ISSUE TITLE
xml error after uninstalling BTE with character assets?

### ISSUE THREAD

**Issue by IsaacDedman** [Regalis11/Barotrauma#1712]
- [ Yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I cant load into any multiplayer matches or even single player campaigns because it gives me a large amount of errors with XML files due to BTE even though i uninstalled it due to large amount if issues with multiplayer compatibility
  
**Steps To Reproduce**
Literally just loading my game makes it produce errors and when i click on character creation i get the crash and crash report posted below

**Version**
latest version 0.9.0.6

**Additional information**
Uninstalled BTE due to issues and since then have had to edit some submarines due to incompatibility
[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/3333443/crashreport.13.log)
 until today where i cant load anything

**Comment by Regalis11** [comment]
It seems that you haven't fully uninstalled BTE, the content package file is still present in Data/ContentPackages. Remove that and the problem should be fixed!
