### ISSUE TITLE
Unable to adjust manually placed gaps.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1716]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You are unable to adjust manually placed gaps without deleting them in the sub editor, after placing, sizing, and then deselecting.

**Steps To Reproduce**
Select Gap, size gap to intended size, attempt to resize gap after selecting another object in the sub editor.

**Version**
Barotrauma 0.9.0.7 Windows 10

**Additional information**
None.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/93c3bd793a18e2a3ee0b1d2f6af2e9b89b3abef3 (private repo)

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
