### ISSUE TITLE
Component GUI In-game doesn't work properly.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1717]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clicking on logic components to open the configuration GUI seems to work for one component ingame, or none of them, at random. 

**Steps To Reproduce**
Unsure how to reliably reproduce. The GUI simply works for one component sometimes at random, or none of them at all.

**Version**
Barotrauma v0.9.0.7 Windows 10

**Additional information**
None
[Component GUI Test.zip](https://github.com/Regalis11/Barotrauma/files/3339246/Component.GUI.Test.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26714d8f1f954a5c85c1605f40a0eca8b91513b4 (private repo)
