### ISSUE TITLE
[0.9.0.7][Bug][Polish] Scary console output if attempting to spectate before campaign sub is downloaded

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1718]
In 0.9.0.7, pressing "Spectate" when joining someone's campaign and not having completed the download results in this harmless popup:
![2019-06-28-043428_517x294_scrot](https://user-images.githubusercontent.com/47284081/60351844-3f6ba080-998c-11e9-9cdd-81df4343063a.png)
Not exactly harmful, but less than pleasing and not very polished. Once as the sub is finished downloading, everything works normally. Could probably be fixed by greying out the button briefly or having an actual in game dialogue popup.
The real issue here is just scaring users or looking unpolished.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/835da7cb6a33ea5fae6896294f48c7e3729681f3 (private repo)

**Comment by Rokvach** [comment]
Tested, more fixes coming up on the next hotfix, but I wasn't able to reproduce this any further so this one is fixed. Closing.
