### ISSUE TITLE
Chinese bug

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1719]
![8$MXMV3(~I{Z4%DZR8TQ0{A](https://user-images.githubusercontent.com/11502419/60359270-2eae3f80-9a0b-11e9-9f2a-9df74b0ff0b7.png)
Delimiter Bug

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/76dff95c7209ea0819d066ac9fd3103f8b85d092 (private repo)
