### ISSUE TITLE
Идея для "бесполезного" фонарика. / The idea for "useless" flashlight.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#172]
Фонариком никто в игре не пользуется. По крайней мере, чтобы его ДЕЙСТВИТЕЛЬНО использовать по назначению. Вот Вам идея:
Есть комната. В ней нет источников света. Давайте просто это место "спрячем" также как и то, что мы не видим через стены. Вот тогда фонарик действительно станет полезным. Он будет освещать только ту область, которую может. При этом можно замедлить передвижение персонажа и запретить использование интерактивных вещей когда нет света. 
Я могу сделать набросок того, как это будет выглядеть, но это ближе к ночи.
Flashlight they don't use it. At least if it is to be used. Here's an idea:
There is a room. There are no light sources. Let's just this place "hide" as well as the fact that we do not see through walls. That's when a flashlight will actually be useful. It will illuminate only the area you can. It is possible to slow down the movement of the character and to prohibit the use of interactive things when there is no light.
I can make a sketch of how it will look, but it's closer to night.

**Comment by Regalis11** [comment]
Added in 3b9d51e
