### ISSUE TITLE
Horizontal dock port Oxygen does not circulate

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1720]
Horizontal dock port Oxygen does not circulate
9.0.6

**Comment by Regalis11** [comment]
Oxygen does not circulate through docking ports, you need a gap between to hulls.

**Comment by SaulApostle** [comment]
> Oxygen does not circulate through docking ports, you need a gap between to hulls.
Isn't gap automatically added?Vertical dock port is normal.check the remoraDrone.Water can flow through, but oxygen can't.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ac72ce0f160fdf167e3ed42f8ff9ed4cbadd8f3c (private repo)

**Comment by Rokvach** [comment]
Tested on Remora's drone, air circulates correctly now, tested with 5 AI character in a multiplayer round and the air quality stayed at 98% with all of us inside the drone and the drone door open. Closing.
