### ISSUE TITLE
Some Labels do not save their resized state.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1723]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some labels do not save their size after being resized. Upon reloading the labels revert to their single grid segment height.

**Steps To Reproduce**
Unknown how to reliably reproduce. For the labels in the attached submarine, I build them in resized form in another submarine, selected them, Ctrl+C to copy. Exited the sub editor, re-entered the sub editor. Ctrl+V to paste them into a blank submarine. The labels if I recall correctly were not expanded anymore, so I resized them with the mouse and saved. Upon reloading the labels reverted to their single grid segment size. I asked others to perform the same steps and they failed to produce the same bug.

One other user reported they had labels with the same bug, but I do not know what steps they did to cause it to happen.

**Version**
Barotrauma v0.9.0.7 - Windows 10

**Additional information**
I've included a submarine, set to not show in menu, with the bugged labels.
[Railgun Degrees.zip](https://github.com/Regalis11/Barotrauma/files/3341636/Railgun.Degrees.zip)

**Comment by Rokvach** [comment]
This has been confirmed to work, closing.
