### ISSUE TITLE
Inventories not in sync

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1724]
Different players see different contents in the same box
![C 5CF{Q8QN}2GYY3AH$MIVT](https://user-images.githubusercontent.com/11502419/60382207-817f0a00-9a92-11e9-84e8-569392c88058.png)
This is a transportation task. The real content of the box is nitroglycerin.

9.0.7

**Comment by Regalis11** [comment]
Could have been caused by #2042, lets move this to Review/QA and close it if the issue no longer resurfaces

**Comment by Rokvach** [comment]
Seems to be working, Closing.
