### ISSUE TITLE
v0.9.0.7 Extended ladders no longer saving in submarine editor

### ISSUE THREAD

**Issue by Essemecks** [Regalis11/Barotrauma#1727]
As of the 0.9.0.7 update, a ladder that is is dragged to extend its length will revert to its default size when the sub is saved and loaded back into the editor or played in game.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ee2357c1e1fbb309a01f8915fa2cc8b313c62ed (private repo)

**Comment by Urso357** [comment]
This is also happening to Labels. If you dont create each label individually (copy paste some), they will resize and change position by themselves.

**Comment by Rokvach** [comment]
This has been confirmed to work, closing.
