### ISSUE TITLE
New Wifi module - cannot set channel.

### ISSUE THREAD

**Issue by GrumpyPhysicist** [Regalis11/Barotrauma#1731]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A newly-made wifi component cannot open the edit channel window.
Attempting to open the wifi channel window seems to break that window for existing wifi modules for the rest of the sub.

**Steps To Reproduce**
* Click on a wifi module made in the ship editor. Notice that the channel select window opens.
* Craft a wifi module. Place it on the wall.
* Click on the new wifi module. Notice that no channel select window opens.
* Marvel at how no wifi channel select window will open for the rest of the mission.
* Get killed by a moloch.

**Version**
Which version of the game did the bug happen in. You can see the version number at the bottom left corner of the main menu, and in a file called "Version.txt" inside the game folder.
Also, please include the operating system you're using (Windows/Linux/Mac).

v0.9.0.7 
Windows, Steam

**Additional information**
Have a really nice day!
Also, my money is on a null pointer exception. If it isn't some form of null value problem, have a beer or preferred beverage and pretend I paid for it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26714d8f1f954a5c85c1605f40a0eca8b91513b4 (private repo)
