### ISSUE TITLE
Turret angles not working properly with a forward facing arc

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1735]
Forward facing firing arcs cause the game to force turrets into full 360 mode. Any arc that crosses the 360/0 line, which is required for a forward facing arc, turns the guns into a full 360 turret. Since the rear of the subs commonly have engines and not guns, starting the arcs on the opposite side would mitigate, but not solve the problem, as backward firing arcs would then be impossible.

**Comment by Regalis11** [comment]
I don't think this is a bug, you just need to use negative angles if the turret needs to cross the 0/360 line (e.g. -90 and 90).
