### ISSUE TITLE
Microphone permissions not requested in catalina

### ISSUE THREAD

**Issue by mlooney** [Regalis11/Barotrauma#1738]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Barotruma does not appear to request microphone permissions on catalina beta

**Steps To Reproduce**
reset microphone permissions with tccutil, and restart the game, try to use in-game voice chat. no permission dialog appears

**Version**
game 0.9.0.7

macos catalina 10.15 Beta (19A487m)

**Additional information**

**Comment by mlooney** [comment]
(presumably this is an api change in the beta, but figured you'd like a heads-up)

**Comment by mlooney** [comment]
relevant log entry: 

``2019-08-23 21:44:56.689766-0500 0xcb606    Default     0x3e30d              332    0    tccd: [com.apple.TCC:access] Policy disallows prompt for RESP:{ID: com.apple.bash, PID[11080], auid: 501, euid: 501, responsible path: '/bin/bash', binary path: '/bin/bash'}, ACC:{ID: DedicatedServer.bin, PID[11084], auid: 501, euid: 501, binary path: '/Users/x/Library/Application Support/Steam/steamapps/common/Barotrauma/Barotrauma.app/Contents/MacOS/Barotrauma.bin.osx'}, REQ:{ID: com.apple.tccd, PID[183], auid: 0, euid: 0, binary path: '/System/Library/PrivateFrameworks/TCC.framework/Versions/A/Resources/tccd'}; access to kTCCServiceMicrophone denied``

**Comment by mlooney** [comment]
Oof, looks pretty involved. Code needs to be signed, notarized, hardened runtime enabled, capabilities added & all stapled before distributing. naturally, this all requires Xcode too.

Yikes.

Light doco:
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by mlooney** [comment]
for other Mac users, workaround is to run the client from terminal (via the linux wrapper), which will request permission & pass along to bt client.

**Comment by durandal** [comment]
This prompts correctly on Catalina 10.15.7, didn't repro.

**Comment by mlooney** [comment]
Seems to work now, closing
