### ISSUE TITLE
Incorrect use of battery for all vanilla submarine.

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1739]
I noticed that the power_out and power_in of the battery were connected together.This creates an infinite loop.And battery power is decreasing.When I built my own submarine, I never connected like that.Power_in should be connected to the reactor.Power_out Connecting Electrical Appliances.Make the battery a branch of the grid, and the branch is unidirectional.
I don't know how to fix this with code.Making the battery detect whether the load comes from itself may require a lot of change.for example,In the editor, I added myself as an additional submarine.Start the game and crash.

**Comment by Regalis11** [comment]
This is intentional. The point is that the grid can be powered by the reactor, the batteries or both at the same time.

**Comment by SaulApostle** [comment]
As I said, power will decrease. At any time, power will affect things. It will make electrical appliances work or make junction boxes burn down. It should not disappear from nowhere.

**Comment by SaulApostle** [comment]
> This is intentional. The point is that the grid can be powered by the reactor, the batteries or both at the same time.

As I said, power will decrease. At any time, power will affect things. It will make electrical appliances work or make junction boxes burn down. It should not disappear from nowhere.

My method still powers both the battery and the reactor, but the battery will not recharge itself. Compared with vanilla, my method of connection will not cause the battery to lose power because of bugs.

**Comment by Regalis11** [comment]
I'm not sure if I understand what you mean. Do you mean that the problem in vanilla submarines is that the batteries recharge from and supply power to the same electrical grid? What do you mean by the battery losing power because of bugs?

**Comment by originalWiFiN** [comment]
> I'm not sure if I understand what you mean. Do you mean that the problem in vanilla submarines is that the batteries recharge from and supply power to the same electrical grid? What do you mean by the battery losing power because of bugs?

I think he means the following:
If input and output of the battery are connected to the same grid - the batteries lose power even if nothing else is consuming power.
The only workaround he found - is to never connect battery input and battery output to the same grid. 

I'm not sure if it works this way in real life, but it's not intuitive from the gameplay standpoint.

**Comment by SaulApostle** [comment]
check Video of attachment
yes like originalWiFiN said
Sorry, I use translation software. I should send more pictures and talk less.
[bug1.zip](https://github.com/Regalis11/Barotrauma/files/3359561/bug1.zip)

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
