### ISSUE TITLE
Workaround for the ladder bug

### ISSUE THREAD

**Issue by madmax3004** [Regalis11/Barotrauma#1741]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ladders resize after reloading a sub.

**Steps To Reproduce**
Place a ladder, resize it, save & load a sub.

**Version**
0.9.0.7

**Additional information**
A workaround for this is to properly size your ladder as you're placing it, the ladder seems to retain its placed properties after a save & load.

**Comment by Regalis11** [comment]
Duplicate of #1727
