### ISSUE TITLE
vanilla automated docking hatch assembly Water leaks in multiplayer mode

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1743]
![KH9SLWJEP{0~8IOLJ%DPB~R](https://user-images.githubusercontent.com/11502419/60665715-d6a68b80-9e97-11e9-8aa4-c1b8250ccac3.png)

orca undocking

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6e3245836313f2b3aca544c60da9290332569c63 (private repo)

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
