### ISSUE TITLE
Items being dropped below player

### ISSUE THREAD

**Issue by Landona24** [Regalis11/Barotrauma#1744]
Possibly related to Issue #1614
Items during a multiplayer session continued to disappear when being dropped, the location where they ended up being under whatever floor the player was on. This was confirmed by myself during spectating as I could see the items, both inside the ship and in an ancient ruin in water had this issue. Only the oxygen tank could be confirmed in the time I was spectating potentially being the most common item to have this issue.

The session had a total of 4 players, 2 AI, ship being the Humpback, dedicated server, 1st mission in the campaign being Salvaging an artifact.
Other notable aspects are the level had a majority of holes along the bottom of the cave opening into empty space far off the map.

v0.9.0.7 Windows 10

![Annotation 2019-07-06 040913](https://user-images.githubusercontent.com/6334873/60755387-e14e4700-9fa3-11e9-8713-dcb445d009d8.png)
![unknown](https://user-images.githubusercontent.com/6334873/60755388-e3b0a100-9fa3-11e9-8a88-09b5a6771585.png)

**Comment by Regalis11** [comment]
Potentially fixed by https://github.com/Regalis11/Barotrauma-development/commit/c6c1354bc6ee6da581da51b53d069e183b2bc57e (private repo)

**Comment by Rokvach** [comment]
This issue hasn't come up during our testing rounds, closing this.
