### ISSUE TITLE
Can no longer select wires in editor to edit color or hidden status

### ISSUE THREAD

**Issue by SeverianVoid** [Regalis11/Barotrauma#1746]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wire properties cannot be changed in the submarine editor since the object properties window for wires does not open when clicking on wires in wiring mode

**Steps To Reproduce**
1. Start a new file in the submarine editor
2. Put down two objects that can be wired far enough apart to make sure you arent selecting the objects
3. Wire the two objects together to place a wire
4. Try to select the wire to edit its color or other properties

**Version**
v0.9.0.7 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/04d713f049a599ceb2703d13571b05225eebe00a (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
