### ISSUE TITLE
"showperm" command crashes Dedicated Server

### ISSUE THREAD

**Issue by Urso357** [Regalis11/Barotrauma#1748]
- [X ] I have searched the issue tracker to check if the issue has already been reported.
(I couldn' find open issues for this one in particular, not for this version of the game)

**Description**
When using the showperm command in the console of a dedicated server, the server will briefly show a number of error messages and then quit to desktop.

**Steps To Reproduce**
Just open up a dedicated server, have someone login, and use the command to check that person's ID.

**Version**
I am away from my main computer, it's happening on the version deployed today (2019-07-10).

**Additional information**
Unrelated: Latest patch fixed a number of issues, campaign is relatively more stable. Keep up the awesome job Baro team!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a92c52d9f0596a25ce9e8a3c36b05b732758760 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
