### ISSUE TITLE
Random items are now the "new" Missing Alien Pump

### ISSUE THREAD

**Issue by Urso357** [Regalis11/Barotrauma#1749]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As of the version deployed yesterday, my Campaigns server is still getting crashes (albeit less frequent) reading "Missing" error messages, it goes from "toolbox" to "riot shield".

**Steps To Reproduce**
It's hard to reproduce quickly as it is inconsistent - you will have to run a couple campaign missions in order to start getting it. Often everyone is kicked but I've seen cases on which only 1-3 people crash on level load.

**Version**
Version deployed on the 2019-07-10.

**Additional information**
Unrelated: Campaign servers are more stable now, my crew wants to see if we can develop colonies around the center - more bugs are bound to be found in the next days/weekend.

**Comment by Regalis11** [comment]
Do you mean the clients actually crash, instead of just getting kicked with that error message? Is there any chance you could get access to the crash reports and send them here?

Also, if you have a save file where the error happens consistently when trying to travel to some specific location, sharing those files would help us a lot in diagnosing and fixing the issue.

**Comment by Urso357** [comment]
Barotrauma Dedicated Server crash report (generated on 15/07/2019 02:54:49)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.9.1.0
Selected content packages: Vanilla 0.9, SSN Charybdis, SSN Moloch, Hammerhead, Crawler, Harpoon, SSN B. Moloch
Level seed: MildaAlphesiboea Linea
Loaded submarine: SSN Moloch (DA18A8D79524AB5E0691ACD38E0E9BB0)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Referência de objeto não definida para uma instância de um objeto.
Target site: Barotrauma.Limb GetAttackLimb(Microsoft.Xna.Framework.Vector2, Barotrauma.Limb)
Stack trace: 
   em Barotrauma.EnemyAIController.GetAttackLimb(Vector2 attackWorldPos, Limb ignoredLimb) na D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\EnemyAIController.cs:linha 844
   em Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) na D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\EnemyAIController.cs:linha 723
   em Barotrauma.EnemyAIController.Update(Single deltaTime) na D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AI\EnemyAIController.cs:linha 359
   em Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) na D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\AICharacter.cs:linha 90
   em Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) na D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:linha 1928
   em Barotrauma.GameScreen.Update(Double deltaTime) na D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:linha 117
   em Barotrauma.GameMain.Run() na D:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\GameMain.cs:linha 281
   em Barotrauma.Program.Main(String[] args) na D:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Program.cs:linha 36


Last debug messages:

**Comment by Urso357** [comment]
Got this one, not about the missing items again. (I could only play tonite, sorry for the delay, as soon as I get another item missing I will post it too)

**Comment by Urso357** [comment]
![image](https://user-images.githubusercontent.com/52521234/61198644-47784f80-a6b1-11e9-8240-8dbcb677d411.png)

[15/07/2019 03:33:20] Client "JE" started the round.
[15/07/2019 03:33:20] Starting a new round...
[15/07/2019 03:33:29] Game mode: Campaign
[15/07/2019 03:33:29] Submarine: SSN Moloch
[15/07/2019 03:33:29] Level seed: Alphesiboea LineaSkaani
[15/07/2019 03:33:29] Round started.
[15/07/2019 03:33:29] WarChaserz has reported an error: Missing item Harpoon Gun (event id 200, entity id 374).
[15/07/2019 03:33:29] WarChaserz has been kicked from the server. Reason: Missing item Harpoon Gun (event id 200, entity id 374).
[15/07/2019 03:33:29] Successfully authenticated client via Steam (Steam ID: 76561198107655629).

**Comment by Urso357** [comment]
https://cdn.discordapp.com/attachments/595359025130897420/600213146619084800/unknown.png

**Comment by Urso357** [comment]
@Regalis11 I hope these are useful ;)

**Comment by Rokvach** [comment]
There's been a lot of improvements to this issue, it can still occure on long campaign rounds sometimes but even that is a rarity at this point. Closing.
