### ISSUE TITLE
Limb position invalid

### ISSUE THREAD

**Issue by LandonGam3r** [Regalis11/Barotrauma#1753]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bug causes the server to disconnect every player and end up in a freezing state. There are no indiciations in the serverlogs nor there is a crashlog being created.

**Steps To Reproduce**
To help reproduce the problem, the following video recorded by a community member might be useful: https://youtu.be/Qf6aeD2ubo4

I also have a printscreen of the error:
![lim_position_invalid](https://user-images.githubusercontent.com/35223068/61139058-e5f58c80-a4c8-11e9-961b-75c0aedd97f0.png)

**Version**
v0.9.1.0 Windows 10

**Additional information**
Same bug occurred shortly after updating to v0.9.1.0 this Wednesday on BT Public 3. Today it occurred on BT Public 1. In a timespan of around 2 days, it occurred twice so far.

**Comment by Rokvach** [comment]
I've had the same exact thing happen couple times before with Mudraptors, where they just glitch out and pushes the submarine to move in high speeds, I have also posted an issue relating to this in the private repo but with much less evidence.

**Comment by itchyOwl** [comment]
Does this still happen?

**Comment by Rokvach** [comment]
Nope, this has been fixed, there was a duplicate ticket of Mudraptors causing the same issue on the tutorial which has already been closed. Moving this to Done.
