### ISSUE TITLE
Extreme lag when reactor meltdown_warning wired to toggle_state on Alarms, and possibly other components that use toggle_state.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1754]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pretty much the title. Wiring meltdown_warning to an Alarm, and possible other components, toggle_state eventually causes extreme stuttering and lag. Unwiring of any alarms immediately fixes the stuttering.

**Steps To Reproduce**
Wire meltdown_warning on the Reactor to toggle_state on an Alarm.

**Version**
Windows 10. Barotrauma v0.9.1.0

**Additional information**
I haven't done any testing, but I'm willing to bet meltdown_warning will cause lag to any other components toggle_state. Other than that, the only time I've encountered this bug is when users have wired alarms to meltdown_warning.

**Comment by Regalis11** [comment]
Potentially fixed by https://github.com/Regalis11/Barotrauma-development/commit/868f277638ff771b3c8c573a4b1c5f2e58e18ecf (private repo)

**Comment by Rokvach** [comment]
Tested this as Udrakan from Discord pointed out that hes getting massive lag while using Humpback on self hosted server by himself, seems like it has been fixed now as I couldn't get any type of stutter while running or using the railguns to shoot around etc, which Udrakan reported of causing issues. Closing as it is now working correctly.
