### ISSUE TITLE
Crash report moving flash powder between deconstructor slots

### ISSUE THREAD

**Issue by Landona24** [Regalis11/Barotrauma#1755]
Deconstructed two flares attempting to fill the amount of material per item, then attempted to move one flash powder over the other within the deconstructor output slots which resulted in an immediate crash.

Windows 10, game version 0.9.1.0
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/3388616/crashreport.log)

**Comment by Rokvach** [comment]
Tested on bugfixes branch, it seems combining the items while they are inside the deconstuctor does indeed crash the game.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c3990d1231376c4b0840ff7ec2bd6f4a5fddc657 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly now. Closing.
