### ISSUE TITLE
Crash report, can't open the game no idea why :(

### ISSUE THREAD

**Issue by 6wax9** [Regalis11/Barotrauma#1756]
game doesn't open :( 
i try to run it and i get this crash report
It used to run just fine on this computer, i tryed reinstaling the game and the problem remained

quick foot note here: i really love the game guys, ty for making it <3

It apears i can't copy the file, so i'll paste it here. :D
----------------------------------------------------------------------------------------------
Barotrauma Client crash report (generated on 15/07/2019 22:39:41)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

752C75DF67AE693C26C6B0BE9DF5D74B

Game version 0.9.1.0
Graphics mode: 1680x1050 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: AMD Radeon HD 5450
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1,6}
    GPU status: Normal

Exception: Loading was interrupted due to an error: A referência de objecto não foi definida como uma instância de um objecto.
   em Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) em D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 185
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   em Barotrauma.GameMain.Update(GameTime gameTime) em D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 595
   em Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) em C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   em Microsoft.Xna.Framework.Game.Tick() em C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   em Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() em C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   em Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) em C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   em Barotrauma.Program.Main(String[] args) em D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 61

Last debug messages:
[15/07/2019 22:39:41] Coroutine Load threw an exception: A referência de objecto não foi definida como uma instância de um objecto.
   em Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) em D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 185
[15/07/2019 22:39:40] Coroutine "Load" has thrown an exception {Foi efetuada uma tentativa de carregar um programa com um formato incorreto. (Excepção de HRESULT: 0x8007000B)}
   em OpenAL.Alc.OpenDevice(String deviceName)
   em Barotrauma.Sounds.SoundManager..ctor() em D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Sounds\SoundManager.cs:line 121
   em Barotrauma.GameMain.<Load>d__87.MoveNext() em D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 357
   em Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) em D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 136

**Comment by juanjp600** [comment]
This error appears to be related to a change we made to OpenAL Soft, for now the solution would be to install the Microsoft Visual C++ 2017 redistributable: https://aka.ms/vs/15/release/VC_redist.x64.exe

**Comment by 6wax9** [comment]
juan, thank you very much 
luv you <3
it solved the issue ^^

**Comment by Rokvach** [comment]
Closing this as the issue has already been identified and fixed for the upcoming patch.
