### ISSUE TITLE
Detonator Oddities

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1757]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sub editors are unable to put detonators in their submarines. Placing a detonator, unwrenching it in character mode, and placing it into a container causes the detonator to require nothing to unwrench it from the wall.

**Steps To Reproduce**
Spawn detonator in editor, unwrench it in character mode, place it in container, save, load up submarine, select detonator, place it on wall, and then press Mouse1 (Legacy Controls) to unattach the detonator without a wrench. 

**Version**
Barotrauma 0.9.1.0 Windows 10

**Additional information**
This is an image of a detonator that was unwrenched in the editor, and placed into a toolbox on the cyclops.
[Cyclops Mk-II - v3.9 - Det Test.sub.zip](https://github.com/Regalis11/Barotrauma/files/3399031/Cyclops.Mk-II.-.v3.9.-.Det.Test.sub.zip)

![image](https://user-images.githubusercontent.com/16188887/61327846-7a206600-a7df-11e9-996b-4bf9322e6eb0.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a54f103388e4802512a7d753602e5670854e3fe (private repo)

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.

**Comment by Pacek-Pacek** [comment]
I have a similiar problem in 0.9.1.0. (Windows)
When playing on Atolla ship, i am going upstairs to the clown toolbox. The detonator taken from the toolbox cannot be rewired properly when attached to wall. Instead, it is scooped right into the inventory.
