### ISSUE TITLE
You can heal third stage of husk infection(Bug or Feature?)

### ISSUE THREAD

**Issue by GhostGamerr** [Regalis11/Barotrauma#1759]
- [ √ ] I have searched the issue tracker to check if the issue has already been reported

**Description**
You can heal third stage of husk infection(Im not sure, bug or feature, so i writing about that on github)

**Steps To Reproduce**
Use 2 stabilozine, to not die.Then use 3 broad-spectrum antibiotics for husk infection resistance.When it will be 100%, use 2 calyxanide.Than use morphine to not dying.((sorry for my english))
I have video with steps.

**Version**
0.9.1.0

**Additional information**
Video with this steps ------> https://drive.google.com/file/d/1AML79wpwOX5guAzxbwcY-KS-NttV_jYz/view?usp=sharing
((sorry for my english))

**Comment by GhostGamerr** [comment]
And yeah, you can heal it easer:just use 3 antibiotics, 3 morphine and one dose of calyxanide.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commits/feature/bugfixes (private repo)

**Comment by NilanthAnimosus** [comment]
I always considered this a feature given its immense cost in items that are quite easy to run out of without being knowledgable and preparing accordingly - typically requiring a doctor and cooperation from the infected player before their additionally dead (A long list of needed items skills, situational awareness and the likes). its remarkably rare to see anyone healed from a full husk in multiplayer given the conditions.

You need to heal the internal injuries, the husk damage, build up the resistance until the small decrease works then finally have to inject 1-2 doses of Calyxanide, depending on the level of antibiotics used. the resistance is also very short-lived in my opinion wearing off very fast.

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
