### ISSUE TITLE
The Game crashes on start

### ISSUE THREAD

**Issue by Tuzik1234** [Regalis11/Barotrauma#1760]
So, i have just bought the game and tried to launch it but failed. I have already installed OpenAL and Microsoft Framework, also i have reinstalled Barotrauma four times and it crashes on load up giving the following message:
Barotrauma Client crash report (generated on 19.07.2019 17:50:28)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

752C75DF67AE693C26C6B0BE9DF5D74B

Game version 0.9.1.0
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce GTX 750
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error: Ссылка на объект не указывает на экземпляр объекта.
   в Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) в D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:строка 185
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   в Barotrauma.GameMain.Update(GameTime gameTime) в D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:строка 595
   в Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) в C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:строка 651
   в Microsoft.Xna.Framework.Game.Tick() в C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:строка 504
   в Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() в C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:строка 94
   в Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) в C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:строка 398
   в Barotrauma.Program.Main(String[] args) в D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:строка 61

Last debug messages:
[19.07.2019 17:50:26] Coroutine Load threw an exception: Ссылка на объект не указывает на экземпляр объекта.
   в Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) в D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:строка 185
[19.07.2019 17:50:26] Coroutine "Load" has thrown an exception {Не удается загрузить DLL "soft_oal_x64.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)}
   в OpenAL.Alc.OpenDevice(String deviceName)
   в Barotrauma.Sounds.SoundManager..ctor() в D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Sounds\SoundManager.cs:строка 121
   в Barotrauma.GameMain.<Load>d__87.MoveNext() в D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:строка 357
   в Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) в D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:строка 136

Help me please(

**Comment by Rokvach** [comment]
I wrote a workaround for the issue in our known issues section of the roadmap, here's a direct link to it.

https://trello.com/c/hR6h94Fi/221-game-crashes-on-start-workaround-included

**Comment by Rokvach** [comment]
Closing this as the issue has already been identified and fixed for the upcoming patch.
