### ISSUE TITLE
Cannot create client with "argument out of range"

### ISSUE THREAD

**Issue by NatLee** [Regalis11/Barotrauma#1761]
**Description**
I encounter this exception when I create a server.

**Steps To Reproduce**
I click the button to create a server and it says "Cannot connect the server".
It always show the error **Argument out of range** on command window.

**Version**
v0.9.1.0 
Windows 10 x64 Build 1903

**Additional information**
![image](https://user-images.githubusercontent.com/10178964/61560410-c9e08500-aa9e-11e9-8e76-9c0d4da5f7a4.png)

**Comment by Regalis11** [comment]
Could be fixed by https://github.com/Regalis11/Barotrauma-development/commit/8faaf67d802fd244fd4f07d33ecb20793fffd272 (private repo)

**Comment by NatLee** [comment]
Hope you fix it on next release version. Thanks! : )
