### ISSUE TITLE
An object causes the interface to enter water

### ISSUE THREAD

**Issue by Zeroexx** [Regalis11/Barotrauma#1765]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An object causes the interface to enter water.

**Steps To Reproduce**

Very strange bugs 
Delete items that seem irrelevant

No water will enter the hatch's interface with the spacecraft.

![{0F(QGYPPJ0X S{G@HMQD)D](https://user-images.githubusercontent.com/49086211/61735951-a3309000-adb7-11e9-8b68-df6d352abed1.png)

![$DSF}%6O_HB{3N2`)L14 Q](https://user-images.githubusercontent.com/49086211/61736169-10442580-adb8-11e9-8659-d36d2a44e74d.png)

![GOYI(VV)X(%PCU@{KVTKC0S](https://user-images.githubusercontent.com/49086211/61736311-61541980-adb8-11e9-8aad-9e388048ffa6.png)

**Version**
0.9.1.0

**Additional information**

txt → sub 
Subfile of the Problem Vessel

[Unnamed2.txt](https://github.com/Regalis11/Barotrauma/files/3423477/Unnamed2.txt)

You can use other ships to dock submarines and the results are the same.

**Comment by Regalis11** [comment]
This doesn't seem like a bug. The extra wall prevents the shuttle from getting close enough to the submarine to properly dock. The placement of the upper coilgun might also cause issues.
