### ISSUE TITLE
Linked fabricator and container windows not placed properly

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1766]
Invalid placement of the UI elements causes overlapping of windows

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.

**Comment by ralfbiedert** [comment]
I seem to have a similar issue. In the same sub

Fabricator:
![image](https://user-images.githubusercontent.com/301288/86515363-a2520c00-be18-11ea-91d9-024af10da072.png)

Medical Fabricator:
![image](https://user-images.githubusercontent.com/301288/86515387-cf062380-be18-11ea-8f4f-dc01f228bf3f.png)

Version `0.9.10.0`
