### ISSUE TITLE
Kicked out from the server

### ISSUE THREAD

**Issue by qaz075115961** [Regalis11/Barotrauma#1767]
- [√] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I and my friend played the campaign mode in the server and made 4 to 5 rounds, they were kicked out of the server and displayed this prompt：
BunbunMaru has been kicked from the server. Reason: Received an update for an entity that doesn't exist (event id 149, entity id 14394). 
Other players have also been kicked out.

**Steps To Reproduce**
Multiplayer games, two players and above, have been doing monster missions after several rounds.

**Version**
v0.9.1.0
my pc windows 8.1
server pc centos 7

**Comment by Regalis11** [comment]
There's been several fixes to bugs that cause these kind of ID errors and disconnections, so there's a high chance this has been fixed. There are multiple causes for these errors, so it's hard to verify whether the bug that caused this specific one has been fixed, but I think we can close this and reopen a new one if the problem resurfaces.
