### ISSUE TITLE
Failed campaign mid-round sync due to "Barotrauma.structure" index out of bounds

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1768]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was joining a mid round campaign match to spectate it (and thus decide what job to play etc) - but got a fairly standard connection lost and kicked from server for having an update for an entity that does not exist.

![image](https://user-images.githubusercontent.com/29177976/61926242-b5513080-af67-11e9-814c-087bd4003bc3.png)
 examining the console however revealed this at the very top before the stated disconnect reason:

![image](https://user-images.githubusercontent.com/29177976/61926284-db76d080-af67-11e9-92d5-89e38e82728b.png)
![image](https://user-images.githubusercontent.com/29177976/61926265-c8fc9700-af67-11e9-8ce6-080d89c37726.png)

**Steps To Reproduce**
Unknown. was not the host, was connecting as client, was a mid round sync.

**Version**
0.9.1.0 Windows 64bit, Client.

**Comment by Regalis11** [comment]
Should be fixed by https://github.com/Regalis11/Barotrauma-development/commit/f856a199f420da4c17cc3d9bf1631ef1258bee28 (private repo)

**Comment by Rokvach** [comment]
There's been improvements to this issue, closing.

**Comment by Regalis11** [comment]
Not fixed, we're getting reports of this happening through GameAnalytics

**Comment by Rokvach** [comment]
We haven't encountered any reports of this happening since the latest patch, nor during our own testing sessions. Seems that the issue has been fixed. Closing.
