### ISSUE TITLE
Attempted to add an order with no target entity to crewmanager

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1769]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unknown, a console error upon joining an in-progress campaign match. presumably giving out orders while a client is in the lobby before mid round sync.

**Steps To Reproduce**
Unknown. likely by joining an in-progress campaign match and trying out orders to players/AI without the client spectating.

**Version**
0.9.1.0

**Additional information**
![image](https://user-images.githubusercontent.com/29177976/61926620-3a891500-af69-11e9-8416-b4f83d835e40.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
