### ISSUE TITLE
Karma decreases in lobby during active round

### ISSUE THREAD

**Issue by JJRcop** [Regalis11/Barotrauma#1771]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Idling in the lobby while a round is in progress will passively decrease karma.
I only expect this to happen if you are playing a round.
This also happens while spectating.

**Steps To Reproduce**
Enter game server when a round is in progress.
Your karma will passively decrease.

**Version**
v0.9.2.0 Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3745bdaa84630ff7ae929c4d9fcb1ca384c8cfaa (private repo)
