### ISSUE TITLE
Clicking doors in the editor causes a crash

### ISSUE THREAD

**Issue by Weebyxanide** [Regalis11/Barotrauma#1772]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clicking a door in the submarine editor causes an immediate crash. I've tested this on the stock Orca and Typhon and by placing doors in a blank file. Happens consistently.

**Steps To Reproduce**
Open the sub editor and either place a door or hatch then select it, or load a file and select one there.

**Version**
0.9.200.0 on Windows 10

**Additional information**
None.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07acdf0ff596796de3c1aba087c6c3c1cb1eba44 (private repo)

**Comment by rico6822** [comment]
Very strange because in legacy version it's not happening.

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
