### ISSUE TITLE
ChineseTexts

### ISSUE THREAD

**Issue by SaulApostle** [Regalis11/Barotrauma#1773]
There are some minor mistakes in the Chinese text. You can replace it after I proofread it. SimplifiedChineseVanilla.xml I'll give you this document.OK?

9.1.0

**Comment by Regalis11** [comment]
Thank you for the offer! If you want to help us improve the localization I think a better way to go about this would be to send us a list of issues (and suggested fixes) that we can pass to the translators.

**Comment by Regalis11** [comment]
Without further info I'm afraid there's not much we can do about this.
