### ISSUE TITLE
Chosen job of character changed (Kept inventory) during campaign without removing previous or dying.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1775]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was playing campaign on the test version, I had rejoined in the middle of the match, I don't know why exactly but I had started the campaign and played 2 if not 3 rounds as a medic and thus had a well established inventory.

upon the next round from this rejoin (I had no reason to, I just wanted to see if I would fail to sync in a match for a laugh in the testing) - I had changed role to captain skills and job title, yet we already had a living captain in that round. it took me a good half round before I had realized I was a captain (was at the very bottom of the order list).

In short between two rounds of campaign:
- Job and skills did not carry over.
- Inventory carried over.
- We went over the maximum of a job (Captain).

**Steps To Reproduce**
Unknown, possibly through rejoining a round with a saved character messes up the clients character infos?

**Version**
0.9.2.0 (Test version), Windows 64bit

**Additional information**
This is my info screen showing my characters skills and job title:
![image](https://user-images.githubusercontent.com/29177976/62027170-ebdfb300-b1d4-11e9-9be6-ca9bc89d5722.png)

This is my characters ID from his inventory, showing what my previous job truely was, can also see my medical uniform still being worn as well:
![image](https://user-images.githubusercontent.com/29177976/62027213-06b22780-b1d5-11e9-9354-aa3c25dbf570.png)

**Comment by rico6822** [comment]
What does initiative do?

**Comment by Regalis11** [comment]
The campaign logic has changed so much since this ticket that I doubt this ticket is relevant anymore
