### ISSUE TITLE
Workshop mods not being insatlled

### ISSUE THREAD

**Issue by Cyborgcr** [Regalis11/Barotrauma#1776]
I decided to subscribe to a creature mod on Steam workshop but when I launched the game and tried to spawn it in, nothing happened. I looked for it in content package checkbox in settings but there was only the vanilla content package. No results were found in local files either. I tried resubscribing to the mod and restarting Steam but it didn't work. I thought it happened only to the one mod I installed and tried it with several of other
creature mods but they didn't download either.

It happened on the new 0.9.1.0 version but I didn't know if it only happens on this version as I didn't subscribe to any mods until this one. I use Windows 10 as an operative system.
![subscribes](https://user-images.githubusercontent.com/46865336/62072597-a4ded580-b247-11e9-9c15-4cbabc9e785c.PNG)
![no_mods](https://user-images.githubusercontent.com/46865336/62072611-a90af300-b247-11e9-8efe-389e6d452688.PNG)
![no_cp](https://user-images.githubusercontent.com/46865336/62072614-aad4b680-b247-11e9-899f-8906eea2eedc.PNG)

**Comment by Regalis11** [comment]
You need to go to the in-game Workshop menu to enable the mod.

**Comment by Cyborgcr** [comment]
Sorry for wasting your time as I have never installed a mod before in this game.
