### ISSUE TITLE
You can stun ANY creature with Stun Baton

### ISSUE THREAD

**Issue by GhostGamerr** [Regalis11/Barotrauma#1777]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can stun ANY creature with stun baton, including moloch, charybdis, endworm
EDIT:using syringe gun with Chloral Hydrate you can stun any creature too

**Steps To Reproduce**
Just use stun baton on them
EDIT:Or use syringe gun with Chloral Hydrate

**Version**
0.9.1.0

**Additional information**

**Comment by JJRcop** [comment]
Which creatures do you expect to be able to stun? Where's the limit?

**Comment by GhostGamerr** [comment]
Leave stunnable only husk and crawler, maybe mudraptor and fractal guardians.Another creatures too big, stun baton should dont work on then

**Comment by GhostGamerr** [comment]
Ok, few minuts ago i checked chloral hydrate on creatures.Using syringe gun with chloral hydrate, you can stun ANY creature too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/43f587060260ff70c1c8c8457dbc6e85f593a76d (private repo)

**Comment by rico6822** [comment]
> 
> 
> Fixed in [Regalis11/Barotrauma-development@43f5870](https://github.com/Regalis11/Barotrauma-development/commit/43f587060260ff70c1c8c8457dbc6e85f593a76d) (private repo)

Which creatures are gonna be unstunnable?

**Comment by Regalis11** [comment]
Anything with a mass larger than 60 (so basically anything larger than a mud raptor)

**Comment by rico6822** [comment]
> 
> 
> Anything with a mass larger than 60 (so basically anything larger than a mud raptor)

What are the masses of monsters in Barotrauma?

**Comment by rico6822** [comment]
> 
> 
> Anything with a mass larger than 60 (so basically anything larger than a mud raptor)

How much mass do each monster in Barotrauma has?

**Comment by Regalis11** [comment]
It's determined automatically based on the sizes of the limbs, and there's no way to check it in-game. It doesn't correspond to any real-world unit either, so the values are pretty meaningless by themselves; but for example, the humans are about 11 units, tiger threshers 90, molochs 4000.

**Comment by rico6822** [comment]
Ok.

**Comment by rico6822** [comment]
I actually believe there should be some sort of stun power determined in each item. If it is the same or higher than the mass of a creature than stun will occur. Stun baton would have 59 stun power with regular battery while fulgurium one doubles it (making stunning Tiger Tresher possible).

**Comment by rico6822** [comment]
I actually believe there should be some sort of stun power determined in each item. If it is the same or higher than the mass of a creature than stun will occur. Stun baton would have 59 stun power with regular battery while fulgurium one doubles it (making stunning Tiger Tresher possible).

Makeshift example:

`[if ; a.stunpower ⩾ b.mass ; b.applystun ; b.applydamage ; else ; b.applydamage]`

Where "a" is considered to be the one who uses stun item and "b" is the target. If the scecified condition hasn't been met than only damage will be applied.

**Comment by Regalis11** [comment]
Tbh I don't see the need for a special setting just for that purpose, because you can already do that (and more) with conditionals. The way we implemented it in the private repo was by simply adding conditionals (mass > x) to the status effects, with a different limit depending on whether you're using a fulgurium battery or a normal one.

**Comment by rico6822** [comment]
Ok.

**Comment by Rokvach** [comment]
Tested, you can now only stun creatures smaller than a Mudraptor. Closing.
