### ISSUE TITLE
[Suggestion] Close the opening 

### ISSUE THREAD

**Issue by NatLee** [Regalis11/Barotrauma#1778]
Hello!
Thank you for developing this awesome game.
I have a suggestion below.
When we enter the game always play the opening, it sometimes make crash or something and its volume is very loud.
So, can we close the opening in the setting after the second entering the game?
Thank you!

**Comment by NilanthAnimosus** [comment]
I assume this refers to the splash intro's played when starting up the game.

You can actually disable these already by editing the config.xml or config_player.xml found in the games base directory (Checking the player one first, and if its not in there, then the first file).

you can quickly reach these by going to the games properties in steam, local files then browse. and text editor should suffice (IE. notepad) but may be easier to read with notepad++ or ultraedit and such.

you want to change enablesplashscreen="true" to false, then save and launch your game as normal.

**Comment by NatLee** [comment]
Yes, that's what I mean. Thank you!
This works, but I think it can be added in the settings instead of we manually change the file.
