### ISSUE TITLE
Submarine got stuck by monster bodies.

### ISSUE THREAD

**Issue by WenShihKen** [Regalis11/Barotrauma#1779]
* [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Submarine is stuck on by dead monster bodies, I'm trying to using any weapon break bodies into part but not work.

I have posted image [here](https://imgur.com/a/PQ8cppf).
Red circle part is monster bodies.

I find related issue but it's not going to fix.
[https://github.com/Regalis11/Barotrauma/issues/1527](https://github.com/Regalis11/Barotrauma/issues/1527)

**Version**
v0.9.1.0

**Comment by rico6822** [comment]
Have you tried to point navigation terminal to left more.

**Comment by rico6822** [comment]
Have you tried to point navigation terminal to left more?

**Comment by WenShihKen** [comment]
Sure, the submarine can't move. The first image shows that.
I have tried to point to other directions.

**Comment by hubismal** [comment]
bodies should be escapable if you push against them hard enough and long enough. Pretty sure regalis or some other member of the crew said they were considering better ways to have players get rid of huge corpses.

**Comment by Regalis11** [comment]
I think we could close this: it only happened very rarely with some of the largest enemies, and now it's not a gamebreaker anymore as the body will eventually despawn and free the sub.
