### ISSUE TITLE
Add a delay to syringe usage

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#178]
1. Добавить определённое время на использование шприца на игроках. Сделать это также, как и с гаечным ключом, что снимает компоненты и прочее.

2. Если же игрок в гидрокостюме, то на это понадобится намного больше времени. Насколько я помню, у некоторых имеются специальные... Клапаны для шприцов?.. Не помню уже.

1). Add some time to use the syringe on the players. To do this as well as with a wrench, which removes components, and so on.

2) If a player in a wetsuit, then it will take much more time. As I recall, some have special... Valves for syringes?.. I do not remember.

**Comment by T-rexsuper1** [comment]
Valves from Space station 13 ! "You are started hunting for injection port on Unkown's suit"

**Comment by Regalis11** [comment]
Duplicate of #195
