### ISSUE TITLE
[Bug] [AI] Steering AI does not undock from stations when navigating to next one

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1781]
Minor bug: Players cannot start a round telling a captain bot to immediately begin navigating to the destination by themselves, as the AI will not undock from outposts and as a result will be stuck.

**Comment by itchyOwl** [comment]
Implemented. Moving to Done.

**Comment by Rokvach** [comment]
Tested, couldn't find any issues on single/multiplayer. Moving to Done.
