### ISSUE TITLE
permission presets are duplicated in GUI when joining a server multiple times.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1782]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was setting up a test server due to a lack of servers available at certain times of the day, and decided to setup custom permission presets with the names None, Campaigner, Moderator, Admin, God.

I had decided to copy the same presets file to my client folder as well as the server in case that makes any difference.

Each time I joined the server, the list would get longer, so it seems as if the previous list is not cleared in some form.

Order appeared as:
None, Campaigner, Moderator, Admin, God, None, Campaigner, Moderator, Admin, God (Repeat indefinitely to count of times joining the server).

**Version**
0.9.202.0 steam testing version, windows 7 64bit. client connected to dedicated server (Not using GUI to host) via separate copied folder on same machine.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f379c3313db2fd53ff9a9614606ab4afa05327b5 (private repo)

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
