### ISSUE TITLE
[Softlock] Cannot leave an outpost after entering it (without docking)

### ISSUE THREAD

**Issue by Ozoneraxi** [Regalis11/Barotrauma#1784]
Tested on v0.9.1.0 - single player campaign.

It is currently possible to skip the sub navigation altogether and enter the outpost after the player swam a long way with a diving suit and enough oxygen. When prompted to talk to the NPC he will be unable to enter the sub, as he is told to bring the sub problem.

However the player then will be unable to leave the outpost itself. There is no button to open the hatch from inside (yet there is one outside). The hatch also cannot be rewired or even breached using a crowbar. This means if this is the last character alive the only option is to quit to menu or retry. 

Proposed solutions:
1) add a button to the outposts so the player can leave it without needed someone else to open the door for them. I also suggest making the oxygen generator available so that he can refill the oxygen tanks.
2) allow the hatch to be forced open with a crowbar; add crowbars or materials around the facility so the player can craft them into a crowbar (in case he didnt bring one with him)
3) just disallow players to enter the outposts altogether without docking

**Comment by Regalis11** [comment]
Ping @ezjamsen, this is still a problem in the latest version

**Comment by Rokvach** [comment]
@ezjamsen Should this get some attention?

**Comment by Regalis11** [comment]
@ezjamsen This is still an issue in the new outpost modules

**Comment by Rokvach** [comment]
You aren't able to get to your submarine either in the outpost level if your submarine doesn't have a docking port.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/15d7080dcf3f0d1ce19f84af9c1c17c0af26db28

**Comment by Rokvach** [comment]
No issues, you will flood your submarine by doing so but there should be enough pumps to make sure it doesn't cause too much harm. Closing.
