### ISSUE TITLE
Crash on pressing 'Play' on steam

### ISSUE THREAD

**Issue by lukemac58** [Regalis11/Barotrauma#1785]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash on pressing 'Play' on steam

[crashreport (28).log](https://github.com/Regalis11/Barotrauma/files/3513159/crashreport.28.log)

Newest version of barotrauma

**Comment by Rokvach** [comment]
The crash is caused by one of the content packages you have enabled, I would recommend disabling or even deleting the ones you aren't using and see if that fixes it.

**Comment by Regalis11** [comment]
@Rokvach I can't think of how it could be caused by the content packages, because the Vanilla content package is also selected so there should be English text packs available.

**Comment by Regalis11** [comment]
This might've happened if the vanilla content package was corrupted somehow (missing files, invalid XMLs). If that was the case, https://github.com/Regalis11/Barotrauma-development/commit/59e61f11c974f6cfc2be58b5a2d944833b7932bc should fix this.

**Comment by Regalis11** [comment]
The fix will be included in the next update, will be keeping this open until then

**Comment by Rokvach** [comment]
This seems to be working correctly as there hasn't been any further reports regarding the issue. Moving to Done.
