### ISSUE TITLE
Parsing order of input signals along a single pin.

### ISSUE THREAD

**Issue by Malidictus** [Regalis11/Barotrauma#1786]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In single player, multiple signals arriving to a single input pin of a single item will be executed in the order in which the items sending the signals were created in the sub file. Items created first will always have their signals parsed first, objects created last will have their signals parsed last and almost always override previous signals. In multiplayer, this ordering is inconsistent, causing logic circuits to behave unpredictably.

**Steps To Reproduce**
Create two Switches (Switch 1 and Switch 2) and one Lamp, in that order. Wire Switch 1 and Switch 2 to the Lamp. When Switch 2 is off, the light is off regardless of what Switch 1 is set to, and changing the position of Switch 1 does nothing. When Switch 2 is on, Switch 1 has brief effect. Turning Switch 1 off causes the Lamp to "flicker," turning off but then turning back on again with in the same frame and triggering its light-up animation. Turning Switch 1 on causes the light's sprite to become slightly brighter, but the actual light source does not change.

If the above setup is copied and pasted, or saved as a Subassembly and reimported, the order in which objects are created could change, causing the behaviour of the circuit to change. This creates an inconsistency that players in an active game have NO means to control or determine and sub creators in the editor have only limited, crude methods of controlling. The only way I've found to "reorder" items is to delete all of them and ensure all of the important items are created in the order in which I want their signals to be parsed.

**Version**
v0.9.1.0

**Additional information**
Parsing multiple signals to the same object along the same pin needs to be controlled by structured logic exposed to and controlled by the player. I suggest parsing signals received in the order of the wires attached to the pin in the wiring panel, from top to bottom (i.e. the order in which the wires are attached). I know this is not trivial to solve and may require multiple update iterations per frame, but it would give players to ability to both determine and control signal priority.

**Comment by Malidictus** [comment]
I ran into a new example of this issue. At initial map load, some signals may execute out of order, I suspect depending on the order in which electrical components are spawned into the instance. Here are the Reproduction Steps:

1. Create two Memory Components (Memory 1 and Memory 2), both set to hold a value of 1.
2. Create a Greater Than component (Greater), set it to output 0 if true, 1 if false.
3. Wire the signal_out pins of Memory 1 and Memory 2 to the signal_1 and signal_2 pins of the Greater Than component, in that order.
4. Wire the signal_out pin of Greater to the signal_in pin of Memory 1.
5. Note that roughly half the time, Memory 1 will have a value of 0 by the time the map has finished loading.

My suspicion as to why this is happening is as follows: The Greater Than component executes before one of the Memory Components has actually been spawned, or has had a chance to Update. Consequently, the Greater Than component returns False, even though the signals it's getting should produce True. There appears to be no explicit check to see if objects have updated at least once before signals from them are used, causing on-map-load behaviour to be inconsistent.

**Comment by Regalis11** [comment]
Personally I don't see the current behavior as something that should necessarily be changed. The way I see your example of two switches controlling the same light component is that the light is receiving two conflicting signals _at the same_ time, which leads to an unpredictable result. Even though in reality the signals do not arrive at the same time, but in a certain (unpredictable) order within a frame, that's in my opinion not something the players should assume or even be aware of; electrical signals don't move in discreet steps through a circuit, and there's no such thing as frames.

The memory component example is in my opinion a similar example of a circuit that _should_ behave unpredictably. What it's doing is essentially checking if A > B when the value of A is the result of that check, which to me doesn't make much sense.

So in a sense, what you're describing is the intended behavior. Feeding multiple conflicting signals to the same input can produce unpredictable results, and if you want it to behave predictably, you need to explicitly define how you want the signals to be handled by using additional components (e.g. an AND/OR/XOR/relay component or something similar in the case of the 2 switches).

That being said, I can definitely see there being cases where you'd just want signals from a specific source to override the other signals, and in those cases it would be handy to be able to do that without any additional components. What I'm not sure about though if it's worth it to rework the entire signal logic to make that possible; to me it feels like a somewhat rare situation that can be easily worked around with one or two extra logic components.

**Comment by Malidictus** [comment]
See, the thing is that the signal logic isn't literally unpredictable. Signals will always arrive in the same order as long as components are always placed on the map in the same order. It's "unpredictable" from the perspective of a player who isn't aware of this behaviour and doesn't know the order of devices placed. There are ways to game this system, and your own Vanilla airlock assembly does so already - it relies on signal priority and tends to break if signals arrive out of sequence.

I don't know if it's worth re-writing the signal logic from scratch just to solve this issue, of course. I realise it's not as simple as just sorting inputs, considering it's the inputs themselves which trigger actions on signal-capable device. Different instances of the same method handle calls from different other devices, so there's no easy way to cross-check them. That's fair enough. However, I speak from experience when I say that trying to entirely avoid signal race conditions causes significant bloat to my circuits.

As a compromise - is it possible to implement some kind of gate/sync module with multiple input pins and a single output pin which would always broadcast signals in the order of the pins? You could probably store signals in an array inside the object, wait until everything has updated, then update those components in the order in which they were created. It could get around needing major signal system re-works, leave a certain amount of ambiguity and yet allow players to determine signal priority for sure in instances where that's important. It adds a bit of extra complexity, yes, but it would cut out 3-4 logic elements out of my larger circuits which exist solely to control signal priority and thus cut down on overall complexity.

Either way, thank you for having a look :)

**Comment by Ecchi-Ki-Senpai** [comment]
[WORKAROUND]
Adding this comment as a work around to the mentioned issue, the object order can be maintained via assemblies or copied circuits by carefully selecting the objects to save as assembly/copy in the same order you want the copies to be.
