### ISSUE TITLE
Power calculations are wrong in multiple cases

### ISSUE THREAD

**Issue by Malidictus** [Regalis11/Barotrauma#1787]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Connecting multiple Batteries/Capacitors to the same power_in pin will draw power from all of them but only use power from the last one created. The same goes for connecting multiple Relay Components's power_out pins to a single Junction Box's power pin. The order in which Relays and a Reactor are created determines how much of a reactor's power is used.

**Steps To Reproduce**
Example 1: Create a Nuclear Reactor, a Junction Box, Two Batteries (Battery 1 and Battery 2), a Relay ("Is On") and a Lamp which draws 1500KW/m. Wire the Nuclear Reactor into the Junction Box, the two Batteries into the Relay, the Relay into the Junction Box and the Junction Box into the Lamp. Run the game and watch the Load. Both batteries will drain at their default maximum (1000 KW/m) while the Relay receives only 1000 KW/m Power and 1500 KW/m load. The Reactor will balance to produce 500 KW/m Power. Lamp will turn on.

Example 2: Recreate Example 1, but ensure that the reactor was created AFTER the Relay component. Wire as above and run the game. Both batteries will drain at 1000 KW/m while the relay only receives 1000 KW/m Power. The Reactor will balance to produce 1500 KW/m. Lamp will turn on.

Example 3: Create 5 Supercapacitors (500 Capacity each). Create an Electrical Discharge Coil (1.0 duration) at default values. Create a button. Wire all 5 Supercapacitors to the Electrical Discharge Coil's power pin. Wire the button to its trigger_in pin. Discharge the coil, causing it to pull 10 000 KW/m for 1s, or 166.(6) KW/s. During this time, ALL five Supercapacitors will lose 166.(6) Capacity. Repeat two more times until Supercapacitors are drained.

Example 4: Recreate Example 3, but wire only ONE of the Supercapacitors to the Discharge Coil. Discharge the coil, causing it to pull 166.(6) KW/s. The single Supercapacitor connected to the Discharge Coil will lose 166.(6) KW/s capacity

**Version**
v0.9.1.0

**Additional information**
There's something wrong with the PowerTransfer and PowerContainer classes' ability to properly calculate power when RelayComponent and Powered objects are involved. RelayComponent objects feeding power to a PowerTransfer object suffer the same priority issues as signals, in that only the power provided from the last-created RelayComponent is actually used, as it overrides (rather than adding to) the power provided by all previous ones. This includes the Generator, which will override and disregard RelayComponent objects linked to the same network if it was created after them.

Similarly, Powered objects don't power-balance correctly, either. They'll send their full load to all PowerContainer objects they're linked to, causing all of them to expend that amount, but the Powered object will only actually use power from the last-created PowerContainer. The previous PowerContainers' power will be overridden by subsequent ones.

Something is seriously wrong with the functions used to calculate power load.

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.

**Comment by Malidictus** [comment]
As far as I could tell, yes - the power priority issues listed here have been fixed. I was not able to replicate any of the issues I posted above on the current Development build.
