### ISSUE TITLE
Duplicated Light Component entries.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1790]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Various objects seem to have duplicate light component entries. The first example I noticed was the Diving Suit. It's XML seems to have two identical Light Component definitions. Another example is the current Junction Boxes and Reactor light components.

**Steps To Reproduce**
Examine either the object's XML or look at the object in the Sub Editor

**Version**
Barotrauma 0.9.2.1 - Windows 10 x64

**Additional information**
None.

**Comment by Regalis11** [comment]
These are actually intentional. Due to the way the game's lighting algorithm works, there's a limit to how bright a light source can be made, and the duplicate lights in the diving suit are intended to make the light look more bright than what could be done with a single light source.
