### ISSUE TITLE
Tutorial Junction box showing up in Sub Editor seems unnecessary.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1791]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Tutorial junction box does not inherit the new junction box light components, and also shows no difference in name in the sub editor. This may cause confusion and inconsistencies between submarines.

**Steps To Reproduce**
Examine the two Junction Boxes placeable in the sub editor.

**Version**
Barotrauma 0.9.2.1 - Windows 10 x64

**Additional information**
Sorry that this isn't really a proper bug report, but I'm not sure if it's quite a suggestion either. I was trying to figure out why one junction box on my submarine wasn't lighting up like the others, and turns out it's a tutorial junction box I accidentally placed.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/811f51605c92f0ed1128f15912468b84b00306b0 (private repo)

**Comment by Rokvach** [comment]
This is working correctly. Closing.
