### ISSUE TITLE
[Suggestion] If on-board respawn is enabled, players should not be allowed to respawn when one or more rooms where the players respawn is flooded.

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1794]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Title says it all. Most of the time, if a flood takes too long, players will end up spawning in a completely flooded area, and instantly get crushed. Is there something that can be done about this?

**Comment by OverwatchVoice** [comment]
Removed the asshole-ish remarks

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1497](https://github.com/Regalis11/Barotrauma-development/issues/1497) via [**ZenHub**](https://www.zenhub.com/)
