### ISSUE TITLE
Battery charge rate can desync from its charge rate slider

### ISSUE THREAD

**Issue by Malidictus** [Regalis11/Barotrauma#1795]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When battery charge rate is changed via the set_charge_rate pin, the battery charge rate slider is not updated to match the new setting, causing it to fall out of sync with the actual charge rate.

**Steps To Reproduce**
1. Spawn a battery with default settings.
2. Spawn a Memory component holding any value other than 50 (say 75).
3. Wire the signal_out pin of the memory component to the set_charge_rate pin of the battery.
4. Load into the game and interact with the battery.

After the above, the battery's charge rate slider (the visual sliding knob when interacting with it) will stay at 50%, while the battery will actually charge at 75% rate. Change the numbers in the memory component and note that the knob does not move, but the charge rate changes.

**Version**
v0.9.2.1

**Additional information**
This bug allows battery charge rate to desync from the actual slider knob partially or completely, both misleading players as to the actual charge rate and potentially misleading them into thinking they've changed the charge rate when they haven't. If a constant signal is being pushed into the set_charge_rate pin on a batter, players can still approach it and manipulate the slider as normal. This appears to have changed the battery's charge rate, but has had no effect.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ba695b34010e353ff9952195ce99ef49bc7551c3

**Comment by Rokvach** [comment]
Tested, confirmed working. Closing.
