### ISSUE TITLE
UI resets when users interact with it in multiplayer

### ISSUE THREAD

**Issue by Ruvalian** [Regalis11/Barotrauma#1797]
- [X] I have searched the issue tracker to check if the issue has already been reported.
Searched "UI" "Reset" "Interface" and "Revert" and combinations of all, apologies if this is saved under another issue name. 

**Description**
While in the multiplayer lobby, users changing settings, checking radial boxes, interacting with the store, and joining/leaving will reset the UI for all other players within the screen they are on. 

Symptoms very between scroll boxes reverting to default positions, name boxes reverting while being edited, etc depending on the screen the client is on.

**Steps To Reproduce**

Nickname box:
1. Join a multiplayer lobby with at least one other user.
2. Select the nickname changer and edit it (do not save.)
3. Have the other player in the lobby disconnect.
4. The nickname box will revert to its default state but preserve selection.

Shop UI:
1. Join a multiplayer campaign lobby with at least one other user.
2. Navigate to the shop screen.
3. Scroll in the shop menu as if browsing for items to purchase.
4. Have the other user add an item to the shopping cart.
5. Scroll box on all other clients will revert to the default state, even while held with the mouse button.

**Version**
v0.9.2.2 on Windows 7 Ultimate x64.

**Additional information**
No further information.

**Comment by Regalis11** [comment]
Fixed in the private repo

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
