### ISSUE TITLE
Publishing in the Steam Worshop failed. Error publishing changes: Fail(false)

### ISSUE THREAD

**Issue by Malidictus** [Regalis11/Barotrauma#1798]
[Aquanaut Project.zip](https://github.com/Regalis11/Barotrauma/files/3563524/Aquanaut.Project.zip)
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempting to update a v0.9.0.0 mod on the Workshop with a v0.9.2.2 version of itself failes with the message in the title.

**Steps To Reproduce**
I'll attach a zip with the files I'm trying to push to the Workshop. The Workshop item I'm trying to update is this:
https://steamcommunity.com/sharedfiles/filedetails/?id=1835787434

**Version**
Windows 7 Pro x64, v0.9.2.2

**Additional information**
Currently, the Workshop Upload tool has extreme trouble working with old v0.9.0.0 mods and consistently fails to attach the correct file paths to files added, or to properly update their versioning number. For this reason, I started the mod upload process but manually edited the filelist.xml file to fix the broken folders, change the version to v0.9.2.2 and change the mod's name while I'm at it (the Steam Workshop name for the mod is different).

After all of the above changes, the game successfully finds all of its necessary files, but then fails to upload them, with an ambiguous error message.

**Comment by itchyOwl** [comment]
I also got a report about this.

**Comment by HalfdeadKiller** [comment]
I'm also getting this error, I haven't found any workarounds yet. I haven't attempted the manual Steam console method yet, however.

**Comment by Regalis11** [comment]
@HalfdeadKiller There are some potential workarounds listed in this Trello card: https://trello.com/c/EySEVqNb/209-limit-exceeded-error-when-trying-to-publish-update-workshop-items-workaround-included. Even though the error message is slightly different, some of those steps seem to work on this error as well. The first thing I would check is that you don't have an excessive number of save file in your save folder, "C:\Users[username]\AppData\Local\Daedalic Entertainment GmbH\Barotrauma".

**Comment by HalfdeadKiller** [comment]
No worries on the delay, my friend group isn't actively playing Barotrauma currently so I'm not modding it super hardcore right now.

The Steam Cloud was turned off when I was trying to upload a change to the mod. I deleted all saves, attempted upload and the upload gave me the Fail(false) error. I turned on steam cloud, deleted the 21+ saves that steam cloud synced to my computer, and tried uploading. Same Fail(false) error. Steam reports "0 bytes stored / 476.84 MB available" for Barotrauma Steam Cloud.

I have eight published mods, with the combined Steam reported size on each workshop item being ~50 Megabytes. I have not tried reinstalling Steam. The preview image is 256x128 with a size of 48.0 KB. I currently have Steam Guard and Family View active.

**Comment by Malidictus** [comment]
I can attest that Steam CMD fixed the issue for me. I had to do a manual upload only once to bring the mod up to modern standards, then updates past that point have worked through the game. Another person I recall had a lot of trouble with this but eventually got it working as well. I don't know what this error entails and I recall Valve's documentation offering little clarity on the matter, but it does seem consistent with some kind of file overwriting issue. That manually overwriting ALL files fixes it suggests as much, as well.

I'd say try SteamCMD and see if that helps. Do note that it'll kill your currently active Steam Client session without any obvious cues, so it'll force a full Steam Guard relog.

**Comment by HalfdeadKiller** [comment]
SteamCMD method outlined in this thread https://steamcommunity.com/app/602960/discussions/1/1646544161771479822/ solved the issue and the workshop appears to allow me to update through the ingame menus again.

**Comment by Regalis11** [comment]
I don't think we've gotten any reports about this in a long time: most likely fixed by increasing the Steam Cloud Quota.
