### ISSUE TITLE
Allow submarines to define required content pack

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#180]
So subs compatible with Chiko can't be used in vanilla and vice versa

**Comment by NilanthAnimosus** [comment]
I believe this is (At least partially) solved by commit 09e4687cd0d2bca7f84d71fcf3cab0139acb207c with the new submarine information at defining what content package it was created in and giving some warnings, perhaps submarines should be able to define on saving in the editor if the content package is a requirement (Although this is bad if a content package updates and changes its name, perhaps use a tag structure for required content packs as part of the information saved which can be included in the content packs definition itself?)

sort of like a submarine requires tag "Vanilla" inside the content pack file and was made in "Vanilla 0.6".

A modification could include, or exclude, the "Vanilla" tag, any sub without a tag is always listed. and another mods submarine could be "Vanilla, MyModTag" (Allowing it to loaded by either) or "MyModTag" (Not being shown in the list as its not part of Vanilla).

This allows a submarine to define it was created for certain content packages in mind, what content packages it should not be displayed on, and for a content mod to define which submarine tags are compatible with their modification while having unique ones for itself.

**Comment by Regalis11** [comment]
Added in 09e4687 and 633dc1f
