### ISSUE TITLE
cant connect to any server 

### ISSUE THREAD

**Issue by WildSobhan** [Regalis11/Barotrauma#1801]
v 0.9.2.2
win 10 64bit build 1903

1-its about 3 days that i get disconnected from any server i join by getting massage "could not connect to the server " i reinstalled the game but it is still the same . 
2-also after i lunch the game there is a few errors in console that says "Map entity prefabs "the name" and "the name" have the same identifier 
3-some time after joining i get the massage "level equality check failed"

**Comment by Regalis11** [comment]
The error messages seem to imply that some of your files differ from the vanilla game. Are you using any mods? Could you send a screenshot of the "prefabs have the same identifier" errors?

Doing the following steps could potentially help with his issue:
1. Delete the folders called "Content" and "Mods" inside the game folder.
2. Open Steam, right click the game and go to Properties -> Local files
3. Click "Verify integrity of game files"

**Comment by WildSobhan** [comment]
okay i disabled all modes (not the vanilla0.9) and multiplayer works fine now (but without modes and steamworks enabled) 
......
alright these are the errors appear in console when i enable all the modes and steam works 
![1](https://user-images.githubusercontent.com/54770262/64115263-6091a880-cda4-11e9-9a81-caa7995bf00b.png)
![2](https://user-images.githubusercontent.com/54770262/64115264-612a3f00-cda4-11e9-9b9a-6f97e0ed1dd9.png)
![3](https://user-images.githubusercontent.com/54770262/64115265-612a3f00-cda4-11e9-8b19-99d6341bb4fb.png)
![4](https://user-images.githubusercontent.com/54770262/64115266-612a3f00-cda4-11e9-8f8f-c951c7811554.png)
![5](https://user-images.githubusercontent.com/54770262/64115267-61c2d580-cda4-11e9-8fa6-3dc59f242d85.png)
![6](https://user-images.githubusercontent.com/54770262/64115272-62f40280-cda4-11e9-9c6b-15d07fd5c19d.png)
![7](https://user-images.githubusercontent.com/54770262/64115273-62f40280-cda4-11e9-929c-4e7b4291b716.png)
![8](https://user-images.githubusercontent.com/54770262/64115274-638c9900-cda4-11e9-8ef0-146bc9e4fa4b.png)
![9](https://user-images.githubusercontent.com/54770262/64115275-64252f80-cda4-11e9-9fb1-95e858c27123.png)
![10](https://user-images.githubusercontent.com/54770262/64115276-64252f80-cda4-11e9-93cc-cc4c08d2db89.png)

thanks for your reply

**Comment by Regalis11** [comment]
Glad you managed to fix it! It seems that some of the mods you had enabled have several issues that cause them to throw errors (invalid XML syntax, incorrectly configured sounds). 

We added some more error checks to prevent this from happening in the future: if the mod can't be loaded, there will be a more readable message box and the mod gets automatically disabled. We'll also warn about the errors when someone is attempting to upload a mod to the Workshop.
