### ISSUE TITLE
Mirrorred ships have misaligned glow effects

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1803]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When playing in Combat mode, the renegade ship's items with glow effects when powered (eg. Active reactors, junction boxes) won't be inverted with the item's sprite.

I only tested this when playing as a spectator, connecting AFTER, the game had started, I'm not sure if that affects it in some way.

**Steps To Reproduce**
Simply load up a combat mission, and play on the renegade vessel.

**Version**
v.0.9.2.2.

**Additional information**
This seems to apply to shuttles that spawn in larger submarines on start, but I'm not sure what causes this.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b95a703eef6efd86c84c9ddad6a36a06b05d1c77 (private repo)
