### ISSUE TITLE
Combat mission imbalance with spectating players

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1804]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a combat round starts and one of the players in the game lobby is spectating (Play yourself is unchecked}, the amount of players on each side might be unbalanced.

**Example**
A lobby with 9 players starts. One of the players is spectating.

Coalition starts with three crewmen, and Renegades with five.

**Steps To Reproduce**
Don't participate in a combat mission lobby when the round starts (Have "play yourself" unchecked)

**Version**
0.9.2.2.  Win10

**Comment by Regalis11** [comment]
Fixed in 0054a26
