### ISSUE TITLE
Mirroring (flipx) in combat missions doesn't work for some objects

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#1805]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Motion detectors do not change the scope of the mirrored sub. Compound text is not displayed correctly. The status monitor doesn't flip the rooms map, only the borders of the ship. The light from the searchlights in a fixed position is directed in the opposite direction. The jet from the engines is directed inside the ship when the engine room is flooded.

**Steps To Reproduce**
Launch a combat mission. Try to get through the hatches on the vanilla ships of the red team. View ship map on status monitor. If the ship has compound inscriptions (not signs), inspect them in observer mode. Flood the engine room on ship of red team .

**Version**
v.0.9.2.2.

**Additional information**
If most of the problem is aesthetic, then the problem with the mirroring of motion sensors directly interferes with the gameplay.

Motion Sensor Area on fliped vanilla Typhon:
![001](https://user-images.githubusercontent.com/29980468/64263599-91a2e200-cf38-11e9-865f-7b9ea53fb883.jpg)

Inverted text:
![003](https://user-images.githubusercontent.com/29980468/64263645-a8493900-cf38-11e9-8dea-11f24f1387f3.jpg)

Status monitor:
![004](https://user-images.githubusercontent.com/29980468/64263695-bf882680-cf38-11e9-9b1d-28527e43bc0c.jpg)

Flooded Engine room:
![006](https://user-images.githubusercontent.com/29980468/64263729-cd3dac00-cf38-11e9-9fc7-42bebb50836f.jpg)

**Comment by Regalis11** [comment]
Partially fixed in the private repo, the only thing missing are the labels on the wall. They're a bit more problematic, because to mirror a series of numbers/letters or an actual word just mirroring the individual labels isn't enough. I think we might need to somehow group the labels, either manually or automatically if that's possible.

**Comment by rav2n** [comment]
Yes, I thought about it. I wish you success in working on this wonderful game.
