### ISSUE TITLE
Too many workshop items prevents server hosting

### ISSUE THREAD

**Issue by hydraphobic** [Regalis11/Barotrauma#1808]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If I have too many active workshop items I'll get a Connecting Failed when trying to host and join my own server.

**Steps To Reproduce**
For me, if I have too many workshop items active I will not be able to join my own server.  This happens both through the game & with dedicated server.

**Version**
9.2.2, Windows 7

**Additional information**
This didn't appear to be a problem prior to the 9.2.0 update.

**Comment by Regalis11** [comment]
Potentially fixed by https://github.com/Regalis11/Barotrauma-development/commit/c3bf3cfe (private repo)

**Comment by Rokvach** [comment]
I haven't heard of anyone having this issue in a while now, closing.

**Comment by Rokvach** [comment]
I was too hasty, this issue seems to still be a thing on Mac

**Comment by EdusFF** [comment]
Tested on MacOS with the current dev build and using 24 mods. Couldn't reproduce  -> closing
