### ISSUE TITLE
выдает ошибку што не видит подлодки

### ISSUE THREAD

**Issue by segey98** [Regalis11/Barotrauma#1812]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. You can see the version number at the bottom left corner of the main menu, and in a file called "Version.txt" inside the game folder.
Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Please post a description of the issue when posting an issue report, we unfortunately cannot do anything about this without more information.
