### ISSUE TITLE
Bots ordered to "Fire at Will" shoot at players

### ISSUE THREAD

**Issue by Malidictus** [Regalis11/Barotrauma#1816]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A bot ordered to man a Coilgun and "Fire At Will" will take shots at player characters who swim past the Coilgun's line of fire. The bot won't track the player, just fire if the player is in the sights.

**Steps To Reproduce**
1. Order a bot to man a Coilgun and "Fire At Will"
2. Don a diving suit and leave the sub.
3. Swim in front of the Coilgun, at almost any distance.
4. Get shot multiple times as the bot opens fire on their own crew.

**Version**
Game Version: v0.9.2.2
Windows 7 x64 Pro

**Additional information**
There appears to be a glitch with the AI's decision to shoot. The AI will not track a player character with their Coilgun aim, as they don't recognise friendlies as valid targets. However, if the player is in line with the Coilgun's line of fire (where the Coilgun Bolts will go), the AI will fire regardless. This leads me to suspect that the AI checks for target type when aiming, but only checks for "target" when deciding to shoot.

Logically, a crew with AI bots may want to leave a bot on the Coilguns when going EVA to provide cover for the away team. Doing this can be deadly, as depending on where the Coilgun was last aimed, it could deal serious friendly fire to the away team.

**Comment by Malidictus** [comment]
I checked referenced issue (must have missed it before). The information there seems accurate. In all instances where bots have shot me with Coilguns, they had been shooting at monsters prior. Monsters have not been present (that I know of) in all instances where I've been shot. This behaviour persists even after I order a bot to leave the Turret and order them to "Fire At Will" again afterwards, having not shot at monsters since manning the Turret.

**Comment by itchyOwl** [comment]
I was able to repro the issue and it should be fixed now (going to be released in some future update/patch).

There was no check for friendlies blocking the line of sight. It's also possible that in an odd case the character collider would block the limb colliders and thus the bot would refuse to shoot. This should be fixed too. The same issue was previosly present in the ai combat inside the sub. 

Thanks for reporting and investigating and sorry that I didn't have time to look into this earlier!

**Comment by Malidictus** [comment]
That's good to hear, and glad I could help. I knew there was something odd with the decision to shoot :) Thank you for the fix, looking forward to it.
