### ISSUE TITLE
Similar name checks can be easily bypassed and illegal characters are not filtered.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#182]
Its something I have had no idea yet on how to tackle without restricting the languages that may be used.

Essentially though:

One can type an A in English characters or an А in Cyrillic characters, and they may look identical but have completely different codes for string comparisons - there is a lot of characters that are different values but visually are identical which allow players to impersonate other players (In order to confuse on whom to ban) as well as impersonate server hosts (had this around 5 times myself over a few months eventually showing how they were doing it).

Additionally player names may have illegal characters as noted in issue: #171 

The illegal characters should be simple enough to strip out, and hopefully there is a method for checking similarity in names.

**Comment by juanjp600** [comment]
Didn't we already fix this with https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaShared/Source/Utils/Homoglyphs.cs?

**Comment by Regalis11** [comment]
Looking into the logs was pretty difficult due to all the project structure reorganization and filename changes but if I'm reading this correctly I think it got removed in commit 5bdb57b. So apparently it was caused by me messing up a merge. :/ Should be easy to readd though.
