### ISSUE TITLE
Japanese text does not render in a uniform size with the large font

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1820]
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/deb532e9-cdd2-424c-b9b5-95723ff66547) (Loading screen)

![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/bf7db1ba-1871-47b1-b542-e32179c818fb) (Server browser)

Japanese override font for GUI.LargeFont (NotoSansCJKsc-Bold.otf) does not render all text with the same size

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d7b923e19a8c0c0ba246009035b23f7a6e4af3da (private repo)

**Comment by Rokvach** [comment]
Tested, looks to be correct. Closing.
