### ISSUE TITLE
The game is crashing with NZXT Cam enabled

### ISSUE THREAD

**Issue by NewererGuy** [Regalis11/Barotrauma#1823]
- [x] I have searched the issue tracker to check if the issue has already been reported.

The game keeps crashing  each time i try to play it with the NZXT Cam software running in the backround. The game doesn't create a bug report and usually brings Steam down with it.
It only gives this error messege : 
Exeption Procesing Message 0x0000005 Parameters
0x7ffe859f2d58 0x7ffe859f2d58 0x7ffe859f2d58
0x7ffe859f2d58

It works with Cam closed

**Comment by CommanderMark** [comment]
Games crashing with NZXT Cam seems to be a common issue. I don't think this is an issue with barotrauma.
NZXT has their own support page for this issue: https://support.nzxt.com/hc/en-us/articles/360023064754-Why-are-my-games-crashing-when-CAM-is-on-
