### ISSUE TITLE
Error instead of 'download' prompt given when submarine (client does not have) is selected by vote

### ISSUE THREAD

**Issue by LandonGam3r** [Regalis11/Barotrauma#1824]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clients at BT Public aren't prompted to download a submarine they do not have, when it's selected by vote. When randomly selected, players are prompted to download, right after the end of a round. When selected by vote, it results in a round starting without players who do not have this submarine that got selected. When alone in the server and selecting a sub I do not have, it's impossible to retrieve the submarine as relogging resets the round.

**Steps To Reproduce**
Join a server that has submarines you do not have, wait till a new round starts and vote for a submarine you do not have. You will receive an error when the round starts (see below). After relogging, clicking 'spectate' will fix the problem.

Printscreen of errors:
![submarine_download_error](https://user-images.githubusercontent.com/35223068/66248164-d54d5f00-e723-11e9-9364-5feed1e24c26.png)

**Version**
v0.9.3.3 Windows 10

**Additional information**
- Submarines are retrieved via workshop on a client and then shared to all servers, placed manually in the 'submarines' folder
- Changelog of v0.9.3.3 states that this problem should have been fixed

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ac62097812d3d7abca3fa774270142576ca6d2b0 (private repo)

**Comment by Rokvach** [comment]
This issue seems to be fixed, at least we didn't run on any issues during our testing rounds with custom submarines selected, closing.
