### ISSUE TITLE
Suggestion: Phrasing for <AIManualOrder> in jobs.xml

### ISSUE THREAD

**Issue by MystLeissa** [Regalis11/Barotrauma#1827]
The Idea is a simple one - right now if we create custom classes regardless of what we set for `<AutonomousObjectives>` the Single-player Custom Jobs receive only the "quick" command buttons for an assistant (that is to say they have to expand the interface to access anything other than Fires, Wait and Follow). I would like to be able to finish my overrides of the combat medic and technician merges by adding the remaining "Quick" orders to the non-expanded GUI for Medics/Sec to Combat Medic and Engineers/Mechanics to Techs - I cannot currently do this as far as I know because the Orders GUI is hardcoded by the Vanilla Files...

**Comment by Regalis11** [comment]
The orders that appear in the non-expanded GUI depend on the "appropriatejobs" attribute in the Orders.xml file, so for now you could fix this by adding the identifiers of your custom jobs there and overriding the file. 

But you're right, it would make more sense for these to be configured in the job xml instead; I think we'll change it for the next update.

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/8ca1b0d6d5f719f583fc885744dd0f99b740447c (private repo)

**Comment by Regalis11** [comment]
Implemented in v0.9.4.0
