### ISSUE TITLE
No way to check mic input level if voice mode is set to Push-to-Talk

### ISSUE THREAD

**Issue by mlooney** [Regalis11/Barotrauma#1829]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Voice activated option displays mic input levels, but push to talk does not, making it hard/impossible to determine if configured properly.

**Steps To Reproduce**
Go to settings, use PTT option, no input meter.

**Version**
v0.9.3.3

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@6547982 (private repo)

**Comment by ekqvist** [comment]
Additional changes to accomodate different localizations in Regalis11/Barotrauma-development@115870f (private repo)

**Comment by Rokvach** [comment]
Lock the dropdown/grey it out if a player doesn't have a capture device plugged in

Another style edit, change the font color of "No audio capture devices found" to red, to make it clearer to the player if they are trying to find a issue why their mic isn't working.

**Comment by ekqvist** [comment]
Suggestions implemented with Regalis11/Barotrauma-development@3045e81 and Regalis11/Barotrauma-development@1cc81eb

Fixed some information visibility issues with Regalis11/Barotrauma-development@183e140

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
