### ISSUE TITLE
Illegal characters in Steam name preventing play

### ISSUE THREAD

**Issue by Lynkzz** [Regalis11/Barotrauma#1830]
My steam name BónBón which I assume contains the banned character ó since from looking at other issue here all non-standard characters have been banned, however, that's not what this is about. I don't really mind not being able to use special characters in BT since it's easily changeable and doesn't affect much. The problem comes from the fact that even when I set my player name in the server browser to something else the game still doesn't let me join games because my Steam name has those special characters.

That's still not too hard to change but I like my Steam name and don't wanna have to change it for a single game just because that game is overzealous in banning characters without any sort of care for context. I would understand banning stuff such as Mótherfùcker, but blanket banning ó and ù thus rendering innocuous stuff like Bùlbasaur unplayable seems like a bad idea. Hell, banning your Stem name from having any special characters when the game uses its own player name anyways isn't great.

Can something be done to still ban inappropriate names without just blanket-banning every single Steam name that don't just contain the alphabet and numbers (bonus if special character player names are allowed too as long as they're appropriate)? It's pretty lame to have to choose between my name for **all** of Steam or playing Barotrauma; especially so when my Steam name isn't offensive *and not even one used in-game.*

**Comment by Regalis11** [comment]
Hello and thanks for the report!

The set of allowed symbols in player names is configured by the server host. Normally you should be able to work around the issue by selecting another name in the server lobby, but unfortunately in the current public version the feature is bugged, and the server doesn't let you join if your Steam username contains disallowed symbols. We've got a fix coming up in the next patch: https://trello.com/c/9zGxiJAe/243-steamp2p-servers-only-use-steam-name-doesnt-allow-switching-to-a-custom-name 
Sorry for the trouble!

**Comment by Regalis11** [comment]
Fixed in v0.9.4.0
