### ISSUE TITLE
Exploding Ammunition Box exploding after deconstruction

### ISSUE THREAD

**Issue by sztyr** [Regalis11/Barotrauma#1834]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you deconstruct the used up "Exploding Ammunition Box" it explodes due to the fact that it creates UEX with 0% health.

**Steps To Reproduce**
Put a depleted "Exploding Ammunition Box" inside the deconstructor and start it.

**Version**
v0.9.3.3 - Windows

**Additional information**
Not really sure if it was intended to work this way, as it takes some time to figure out what exactly exploded on the sub.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c9ad2123f6aace1b60c88200b779b5876a547466 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
