### ISSUE TITLE
alien ruins walls dont appear in sub editor

### ISSUE THREAD

**Issue by mc-oofy** [Regalis11/Barotrauma#1837]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the alien ruins wall does not appear on the screen but can be selected and you can also only see 2 dots

**Steps To Reproduce**
place the alien ruins wall in the sub editor

**Version**
v0.9.3.3 Windows 10

**Comment by Regalis11** [comment]
Fixed in v0.9.4.0
