### ISSUE TITLE
Some alien ruins are impossible to complete

### ISSUE THREAD

**Issue by chessmaster42** [Regalis11/Barotrauma#1841]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some variations of the alien ruins either have an artifact that can't be reached or an entrance that is broken.

I have encountered several alien ruins where the artifact is in a 1-block high vault room that is impossible to get the character into:
![20191026183336_1](https://user-images.githubusercontent.com/1146884/67630130-90af7200-f850-11e9-9869-aca17c6bc6cb.jpg)

I have also encountered several alien ruins where the entrance is on the bottom and starts out open. This bugs the water flow as something still think the door is closed. As such no amount of re-opening or closing fixes the problem and it is impossible to traverse any further into the ruin:
![20191026234034_1](https://user-images.githubusercontent.com/1146884/67630161-fdc30780-f850-11e9-96d7-0ae81f263e28.jpg)

**Steps To Reproduce**
The best suggestion I can make here is to run through artifact missions using the map seed 5r8xW0pu. Unfortunately I don't have the state of the save game during which the bugs were encountered but that's the map seed for the most recent game where I ran into these problems.

**Version**
Game - 0.9.4.0
OS - Windows 10

**Additional information**
Encountered in single player but I don't see why MP would be any different given that this is down to the ruin room generation. I did also look through RuinConfig.xml to see if anything in there jumped out at me as out-of-place but no dice. My guess for the teeny tiny vault is the overall size of the ruin was constrained and so that room got squashed down as far as possible. As for the entrance corridor I'm guessing it's a bug with the alien door more than anything else.

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/0fdbe351e56c8397a375a6a181cb01b82ebbdb53 and https://github.com/Regalis11/Barotrauma-development/commit/aa465e8771f3a2c58be44cc4bcb2305ad563b865 (private repo)

**Comment by Rokvach** [comment]
Ruin layout looks a lot more consistent now, so I doubt this issue will come up. Closing.
