### ISSUE TITLE
Velonaceps Calyx Eggs does not give husk infection

### ISSUE THREAD

**Issue by Sabbasn** [Regalis11/Barotrauma#1842]
When I try to inject myself or others with Velonaceps Calyx Eggs, nothing happens; there is no infection. I've tried to inject several doses, but still the husk infection never appears.

**Comment by Regalis11** [comment]
The husk eggs are unfortunately broken in the current public version due to changes in the way husk infections are handled. The issue has been fixed in our private repo and the fix will be included in the next patch.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
