### ISSUE TITLE
Bad connecting system to server with mods.

### ISSUE THREAD

**Issue by IGROLIKE** [Regalis11/Barotrauma#1843]
Hello,i want to tell you about strange mods server downloading system.
I mean when plr join game,game won't automaticly download mod
Like it happen with steam workshop sub,when you have not it will download (sub)
But mod downloading system works by other way
If you want join for example:xeno mod server,you must download it by your self
So that's why those servers with mods have low ofline
online
And that actually mean community online too
Just make it automaticly (mod downloading when you join server)

**Comment by Regalis11** [comment]
We got a newer ticket about the same issue (#1996), closing this one because it has more details
