### ISSUE TITLE
Secure Cabinet can not be picked using Crowbar

### ISSUE THREAD

**Issue by GeorgeGhost** [Regalis11/Barotrauma#1844]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unlike doors which can be locked by defining an id_card required for it to be open, and an item like crowbar can be defined in editor and used ingame to open it, lockable cabinet while being able to be locked using id_card, there is no way for it to be hacked.

**Version**
v0.9.4.0

**Comment by GeorgeGhost** [comment]
I would say this more of a bug than a feature request, as doors share the same funcionality of using id_card, but are also pickable.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1498](https://github.com/Regalis11/Barotrauma-development/issues/1498) via [**ZenHub**](https://www.zenhub.com/)
