### ISSUE TITLE
AI Bug

### ISSUE THREAD

**Issue by Bo0g1eMaN** [Regalis11/Barotrauma#1845]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI crewmember communicates a apparent need for a suit then proceeded to come from their stationed gun and picked up a suit on the ground, then would drop and pick up the suit over and over again slightly moving forward each time and would keep communicating they need a diving suit, the suit in question had oxygen in it, after picking up the suit the crewmember ran over to the suit rack and now is proceeding to do the same thing but running 

**Steps To Reproduce**
it wasn't anything I had attempted to do, it just happened, the sub was breached by crawlers and hit the floor hard, the AI crewmember ran away to get a suit from the rack after I picked up the suit they were messing with

**Version**
Dev build as of 10/28/19, Windows 10

**Additional information**
None

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
