### ISSUE TITLE
The Sonar Transducer not working

### ISSUE THREAD

**Issue by martin1194** [Regalis11/Barotrauma#1851]
I make a submarine and a drone connects with WIFI component. The Sonar Transducer is connected correctly and have power. Why it doesn't work?

I have research solution and find this website.
Both of submarine and drone are meet the conditions.
Title: How can I make a remote controlled drone/sub?
https://www.reddit.com/r/Barotrauma/comments/c35ebj/how_can_i_make_a_remote_controlled_dronesub/?ref=readnext

 

Submarine: https://drive.google.com/file/d/1vjO1AotHaqstCmlVlo6eA0-eVViP8Cf7/view?usp=sharing

Drone: 
https://drive.google.com/file/d/106cZWPBtD2AEVswNpQwIlGXGpR6UpbtR/view?usp=sharing

Remark:
The submarine has a switch to switch on the power.
The drone can be manual/remote.

**Comment by Regalis11** [comment]
There's 2 issues here: the shuttle navigation terminal is not powered (because the relays passing power to the grid are not active), and the "use transducers" setting is toggled off on the nav terminal.
