### ISSUE TITLE
Navigation terminal's NeutralBalastLevel using wrong equation

### ISSUE THREAD

**Issue by Confodore** [Regalis11/Barotrauma#1853]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The formula for converting the neutralBallastLevel to the targetLevel for pumps, isn't working as intended.  As it currently stands, the only time it converts correctly is at neutral ballast levels 1.00, 0.50 and 0.00. At any other values, the results are skewed.

_Barotrauma/BarotraumaShared/Source/Items/Components/Machines/Steering.cs line:253_

> `targetLevel += (neutralBallastLevel - 0.5f) * 100.0f;`

If you want to convert the values **0.00** ->**1.00** into the values **-100** -> **100** the correct equation is:  

> ~~`targetLevel +=(neutralBallastLevel * 2f) - 100.0f;`~~
> `targetLevel +=(neutralBallastLevel * 200f) - 100.0f;`

**Steps To Reproduce**

- Set the **_navigation terminal's_** optimal ballast levels in the submarine editor to **0.10** (meaning that the sub should be neutrally buoyant when the ballasts are 10% full of water). 

- Connect the Navigation terminal's **velocity_y** to a pumps **targetLevel**.

- Connect the Navigation terminal's velocity_y to a display. (it's just to see the signal)

- Test the sub.

- Observe that the ballast pumps receive will targetLevel signal of **-40** (meaning 30% flooded). 

- The correct signal should be -80 (10% flooded)

**Version**
Observed in 0.9.4.0
Appears to have been added in 0.5.3.0
commit 6c57c1270cffbbade16b999308d29203a77fd629
decribed as:

> neutralballastlevel option in steering

**Additional information**
As an option or default mechanic, you could try and make the Nav terminal's automatically calculate the optimal ballast levels by using the hulls with the "ballast" tag's as reference.

Made git account for this.
Love the game! Keep it up and good luck!

**Comment by Regalis11** [comment]
Thanks for a very detailed report! This has been fixed for the next update, https://github.com/Regalis11/Barotrauma-development/commit/81a40b66 (private repo)

**Comment by Confodore** [comment]
Ehh.. made a mistake in my issue. You guys probably caught it, but just for reference.  My recommendation for the fix should actually have been: 

> `targetLevel +=(neutralBallastLevel * 200f) - 100.0f;`

It's not multiplied by 2f, but rather by 200f
Will edit issue
