### ISSUE TITLE
Crash when opening steam workshop with multiple mods enabled

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#1854]
Had a lot of mods enabled and went to disable some and had the following crash on MacOS:

System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

Stacktrace:
[https://app.zenhub.com/files/93301055/c2d261c9-9212-416b-b136-9d3d950a2198/download](https://app.zenhub.com/files/93301055/c2d261c9-9212-416b-b136-9d3d950a2198/download)

**Comment by Regalis11** [comment]
fc14f48 should fix this

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
