### ISSUE TITLE
Gibbing

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#186]
Make characters explode into bits when shot with the railgun, killed by a strong enough explosion or crushed between a sub and the ice walls. Severing limbs also needs some additional gore particle effects.

**Comment by Crystalwarrior** [comment]
Perhaps never despawn limbs and other gore effects? Might warrant a new item like soap to clean things up, but that would also allow people to use blood decals on hull as evidence of shenanigans going on.
