### ISSUE TITLE
[Feature Request?] [Issue?] [Code] Legacy-Like Inventory Interaction Menu

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1870]
This is technically a feature request, but it's honestly more of an "issue" because I think it used to be in the game, until it was removed and things became worse.

One of the few downgrades I can think of in Barotrauma Steam's mechanics is the lack of in-inventory item interactibility. Items can essentially be aimed and shot (weapons), looked at when selected (handheld sonar), used for storage (containers), and equipped (clothing, obviously). This much is clear, and is also pretty much the extent of item interaction at the moment.

Considering that you guys seemingly think of everything, this is probably not a very new idea, but **inventory items should have drop-down menus with buttons when moused over the same way that standard container items do (eg gas masks, revolvers, etc). These buttons should appear next to the container slots if the item is also a container, making it effectively one big "interaction" menu for both buttons and container slots.** It almost goes without saying that I think these menus, like everything else in the game, should be moddable in what they do (the same way item menus in legacy were if I'm not mistaken).

Some of the issues the *lack* of this has caused are:

- Players who use voicechat can't effectively use proximity chat without having to completely remove the headset or battery. It's pretty much a given that this isn't great usability design, and also requires a spare slot for the battery or headset. Having a button menu would allow people to simply turn it on and off.
- Barotrauma Extended (which was essentially a big part of barotrauma, despite being a mod) has been functionally neutered because many of its items were interactive in this way, which iirc is one of the reasons chiko had to make a bunch of it from the ground up instead of being able to port over much existing content.
- Flares, Flashlights, and Sonar Beacons can't be disabled, making them extremely annoying in their own unique ways. Flares are a griefers choice of annoyance thanks to their unending noise, Sonar Beacons will always appear on your sonar (unless the batteries are removed, which is really impractical and requires another storage slot similar to, etc.
- It goes without saying that there is also a large amount of untapped potential in items that could use this, such as inventory radio buttons for changing the existing yet unusable channels, turning the stun feature of the baton off to deliver a manual beatdown, and a bunch of other stuff that mods could utilize as well.

Assuming you've read this far, thanks for reading. It's possible that this might be on a to-do list somewhere, but it feels as though the game has moved past the "implement fundamental features" stage of the alpha, and that this was unfortunately left out.

**Comment by itchyOwl** [comment]
Thanks for the feedback, hub! We are currently re-evaluating the UI and UX and we'll take this insight into account ;)

**Comment by Regalis11** [comment]
You could use the new CustomInterface component to implement most of the features you mentioned. It's much more flexible than the "Use" button in the lefacy version: you can have an arbitrary number of buttons and tickboxes and make them apply arbitrary effects on the item, and customize the look of the interface. To see an example of how it can be used, you can take a look at the sonar beacon config in "Items/Tools/tools.xml".

CustomInterface does have it's limitations (having it be always visible being maybe the most major one), so dropdown menus are still something we definitely should consider.

**Comment by OverwatchVoice** [comment]
Wouldn't it be easier to have two voip keybinds? One for radio, the other for local.
What if you missed an announcement while your radio was out?

**Comment by hubismal** [comment]
> Wouldn't it be easier to have two voip keybinds? One for radio, the other for local.
> What if you missed an announcement while your radio was out?

that's only relevant to the voip example i gave. things like flashlights flares etc still need buttons imo.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
