### ISSUE TITLE
[0.9.5.1] [Issue] [Linux] Creating a SteamP2P server enforces mystery password for some reason

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1871]
On linux, when you create a server using the "host server" option in the main menu and leave the password field blank, everyone who joins is prompted for some mysterious unknown password. this can be fixed by typing `password` into the console to clear the server password, but this is still definitely unoptimal, and confusing for normal linux players who aren't familiar with all the commands. Also just generally shouldn't happen lol.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0571167e57bbd120582951c4e59cba7ee9a9a6d7 (private repo)

**Comment by hubismal** [comment]
As of 0.9.5.1's 11/13/19 build, this has not been fixed, although I doubt this is really that high priority. Posting for the sake of clarity.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
