### ISSUE TITLE
[0.9.5.1] [Issue] [Graphics] Suit Variants Don't Match Inventory Sprite

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1872]
Suit variants don't match their inventory sprites; All of the variants have the same sprite making them indistinguishable in the inventory. This is troublesome if you are trying to disguise as someone but don't know which suit in your inventory matches theirs.

**Comment by itchyOwl** [comment]
It's a known issue. We just didn't have enough time to do them. Anyway, thanks for pointing out and creating a ticket about it!

**Comment by ekqvist** [comment]
Should be fixed in the `feature/job-gear` branch now

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
