### ISSUE TITLE
SpeedMultiplier issue

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1874]
So, when the SpeedMultiplier in an statuseffect is negative, it reverts the controls. This is something known since legacy but it seems to have an issue now. Even when the affliction using this kind of status effect is gone, the controls remain inverted. This didn't happen before so I believe it's a bug.

Also, there's a vanilla affliction that does indeed reverts controls called Disoriented, but there's a mistake in it that prevents the affliction from removing itself. It will lower itself until 49 or 50 and stay there.

**Comment by Regalis11** [comment]
Thanks for pointing this out! I don't think I've tried using a negative SpeedMultiplier value, so this has completely slipped past me.

The second issue you mentioned is not actually a bug however; the vanilla "disoriented" affliction is designed to work in tandem with the space herpes affliction which toggles the disorientation on and off. The disorientation will never go away by itself unless something else disables it.

If you want to implement a similar affliction that goes away by itself (or want to modify the existing one), you can change the "minstrength" value in the affliction config file from 50 to 0.

**Comment by ChikoEduardo** [comment]
Oh, I had no idea it was tied to the space herpes one. It makes sense now.

Also, I did implemented a similar affliction but as I mentioned, it keeps the controls inverted even when the affliction has been removed. D:

**Comment by Regalis11** [comment]
What I meant was using a copy of the "disoriented" affliction, not inverting the controls by using a negative SpeedMultiplier. Just tested it with a custom affliction and couldn't spot any issues: as soon as the affliction is removed, the controls return back to normal.

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce the issue with the negative SpeedMultiplier. I made a quick custom affliction to test it out, and it seems to return the speed back to normal as soon as the affliction is gone:

  ` ` `<Affliction`
    name="Brain damage"
    identifier="braindamage"
    description=""
    type="braindamage"
    limbspecific="false"
    indicatorlimb="Head"
    causeofdeathdescription=""
    selfcauseofdeathdescription=""
    showiconthreshold="1"
    maxstrength="100">
    <Effect minstrength="0" maxstrength="100"
      minscreendistort="0.0"
      maxscreendistort="0.5"
      minradialdistort="0.0"
      maxradialdistort="0.5"
      strengthchange="-1.0">
      <StatusEffect target="Character" SpeedMultiplier="-0.5" setvalue="true"/>
      <icon texture="Content/UI/IconAtlas.png" sourcerect="256,640,128,128" color="150,26,26,255" origin="0,0"/>
    </Effect>
  </Affliction>` ` `

**Comment by ChikoEduardo** [comment]
Yeah, it doesn't seem to happen anymore for some reason and I haven't done any changes to the affliction using that feature.
