### ISSUE TITLE
[Feature Request] [Code] Low med skill should misdiagnose instead of suggest wrong treatment

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1875]
Another feature request, I know, I'm sorry. This is a generally pretty agreeable one, though, and there's no other real place to put suggestions. It's also not something massive, and something I might suggest while you're in the middle of redoing the UI, too.

Currently in the game, players with low medical skill are shown incorrect treatments for diagnoses they can see in their medical HUD. Nobody falls for the mistreatments after the first or second time playing, making med skill one of the more useless skills unless you want to succeed in opiate skillchecks. My proposal is that it would be much better if low med skill showed the wrong symptoms/diagnoses instead of suggesting the wrong treatments. Additionally, players with low medical skill could get more vague and unhelpful observations of their symptoms in place of actual diagnoses of diseases or conditions, or just not have more subtle conditions appear in the affliction list at all if they aren't severe.

**Comment by ezjamsen** [comment]
I'd discussed this with Daniel last week and think it's a good idea. Let's add misdiagnosis as additional to bad treatment suggestions.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1499](https://github.com/Regalis11/Barotrauma-development/issues/1499) via [**ZenHub**](https://www.zenhub.com/)
