### ISSUE TITLE
Pump signal gets lost if there's a junction box between a relay and a navigation terminal.

### ISSUE THREAD

**Issue by Boggart** [Regalis11/Barotrauma#1876]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have a navigation terminal hooked up to a pump by a relay and have it passing through any junction boxes along the way the signal never reaches the pump, if you don't have any junction boxes in between it works properly.

**Steps To Reproduce**
Connect a navigation terminal to a pump via a relay with one or more junction boxes in between.
[RelayTestSub.zip](https://github.com/Regalis11/Barotrauma/files/3838969/RelayTestSub.zip)

**Version**
v0.9.4.0

**Comment by Regalis11** [comment]
Fixed with the upcoming electricity overhaul: https://trello.com/c/U7XqLh8V/246-electricity-overhaul

**Comment by Rokvach** [comment]
Moving this to Done as it has already been covered
