### ISSUE TITLE
[0.9.5.1] [Linux?] [Bug] Server names shortened to one word when hosting through steamp2p

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1877]
When creating a room via the "host server" menu, when you create a room, the room name will be shortened to just the first word of your string you inputted earlier in the host server menu. Funnily enough, your username is actually the "full" server name you inputted earlier in the host server menu. It seems that the game shortens the server name automatically for some reason.

Ex: Inputting "Hubismal Awesome Dance Party" gets shortened to "Hubismal". Username of host is "Hubismal Awesome Da" (cut off because of character limit).

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/73255633e7d8113ec6b0328ded074680d96a5921 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
