### ISSUE TITLE
Bot shooting player swiming by a coilgun.

### ISSUE THREAD

**Issue by RustyNeuron** [Regalis11/Barotrauma#1880]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bot ordered to "fire at will" shoots the coilgun when I'm swimming by. Bot do not track me, just shoot when I'm crossing line of sight.

**Steps To Reproduce**
1. Take a dugong.
2. Order a bot to handle a bottom railgun and "fire at will".
3. Take a diving suit.
4. Swim by his line of sight.
5. He will react and shoot.

**Version**
v0.9.4.0 (Steam)
Windows 10 x64 Pro

**Additional information**
It is the same issue as in report #1816, but it still exist. I've made video how to reproduce this bug, also it's not very consistent, but I think you need to shoot from coilgun and exit with rmb to make it possible. [link to a video](https://youtu.be/VFelgjAx8Ag)

**Comment by OverwatchVoice** [comment]
I've tried this, but the bots never opened fire. I know they can fight back after you attack them, maybe you attacked them earlier and shot you because of that?

**Comment by Rokvach** [comment]
This issue has already been fixed with the new 0.9.5.1 patch, closing.
