### ISSUE TITLE
[Feature Request] Make text chat more noticable

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1883]
Make bots stop talking in multiplayer rounds unless it's really really important. Give sending a message in chat a much more noticable sound that that pathetic blip it makes, and that pathetic bleeep it makes when you have the radio on. Give it something ear piercing, something that really gets everyone's attention, maybe even have it have that compression effect that the VOIP already has.

You will not believe how good some people who use VOIP are at ignoring the text chat.

EDIT: I labelled this as an issue because I was admittedly a little bit pissed off after a round of being completely ignored, but it basically makes the game unplayable if you don't have a mic.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1708](https://github.com/Regalis11/Barotrauma-development/issues/1708) via [**ZenHub**](https://www.zenhub.com/)
