### ISSUE TITLE
Player teleports when entering Orca while docked

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1884]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When attempting to embark/disembark via the airlock, the player get teleported into a piece of geometry and can get stuck.

[**Video demonstration**](https://www.youtube.com/watch?v=08ZL2EDkMTc)

**Version 0.9.4.0**

**Comment by OverwatchVoice** [comment]
I had encountered the same layout as shown in the video, but I've been unable to replicate the bug, so I have no clue what could cause this.

**Comment by Regalis11** [comment]
Haven't been able to reproduce this either. We've done a couple of fixes to the teleportation and collision prevention logic when leaving/entering a sub, so I think this may have been inadvertently fixed somewhere along the way.

**Comment by Rokvach** [comment]
I believe this has already been fixed, closing.
