### ISSUE TITLE
[Modding] [Issue] [Low Prio] Players can still crouch while locked into <Control> tag

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1887]
When locked into a <Control> tag that forces the players bodies to match limbpositions (like the periscope), players can still crouch. While this isn't an issue for the periscope specifically, it makes things like chairs hard to mod in as players can just crouch "below" the chair seat.

Additionally the "waist" limb in the human ragdoll doesn't seem to obey the <limbposition> tag (it won't go to the specified coordinates).

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1707](https://github.com/Regalis11/Barotrauma-development/issues/1707) via [**ZenHub**](https://www.zenhub.com/)
