### ISSUE TITLE
Bots don't take into account opiate overdose

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1888]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots try to hear others with opiates, they don't prepare naloxone to compensate for the overdose and may  kill their patients.

**Version**
0.9.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/84cd548d (private repo), fix coming up in the next update :)
