### ISSUE TITLE
[Feature Request] [Server Administration] Easier, user friendly ways to ban/kick users

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1889]
As it stands right now Admins/Moderators don't know what someone's steamID is without looking into the console and scrolling a long ways back, potentially past the console history (which would mean they couldn't find the ID period).
This is _extremely_ user unfriendly, and most regular players who are hosting have no way of understanding how to ban someone, especially after the person has left. Bans right now are very easily circumvented by just leaving before a person bans you, and returning a long time later.

It would be nice if admins could see a users steamID in the little user popup menu (the one with mute, kick, ban, view profile, etc). Maybe the ID could be displayed in a color based off the number to make it more memorable (the way some imageboards do with IDs to make each ID more memorable)?

Personally, I would also suggest some sort of user history button that shows a list of all players who have joined the server during this session, with the same interactivity of the current userlist (see their steam profile, ban, etc). But as always, this is just a simple idea and if you have a better implementation I'd love to see it. Either way, moderation is still pretty clumsy as it stands, and most average users are left without a clue on how to effectively ban when hosting. Thanks for reading.

**Comment by Regalis11** [comment]
I think the recent tab menu improvements address most of this, moving to Review/QA

**Comment by Rokvach** [comment]
Only thing missing is managing the history, as of right now you can't ban users who only visited the server caused harm and left which the joined/left info on the tab menu should of handled but doesn't seem to handle right now, same with trying to manage them from the server log doesn't show the option to ban them.  @Regalis11

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1709](https://github.com/Regalis11/Barotrauma-development/issues/1709) via [**ZenHub**](https://www.zenhub.com/)
