### ISSUE TITLE
[Modding] [Low Prio] Non-humanoids cannot be neutral

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1890]
Another low-prio modding ticket, I know.
There is currently no way to make a creature for this game and not have it be considered hostile by the AI (AI will attack or report any creatures), or considered a "monster" by the game. Essentially, all non-humanoids are considered hostiles by the game. It would be nice if there was a simple property that let the game treat non-humanoids as neutral creatures, especially now that the AI actively attempts to combat these creatures instead of just run away.

**Comment by ChikoEduardo** [comment]
wait, I have humanoid creatures and they are still treated as monsters too. D_D

**Comment by itchyOwl** [comment]
Implemented. After the next update it should work when you add the same group for the both species. This already works for monsters, but in the current release version it doesn't work for humans (bots).

**Comment by Rokvach** [comment]
Closing this as it is so niche of an issue, if something does come up there's bound to be a new ticket about it anyway and as this doesn't affect the core gameplay.
