### ISSUE TITLE
[Networking] [Low Priority] Game shadow disconnects

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1891]
The game seems to shadow disconnect on timing out instead of properly giving a timeout notice like it should. Every single player disappears, the client seems to go fully clientside, and all monsters disappear. Your radio also stops working, or saying anything stops working.

The game should probably give a notice that you've timed out instead of doing this confusing song and dance, but it's not like this feature is really that high priority since it's not hard to figure out.

Also sorry if this issue already exists, I couldn't find it anywhere.

**Comment by Regalis11** [comment]
This has been fixed in the private repo https://github.com/Regalis11/Barotrauma-development/issues/1162, will most likely be included in one of the patches released soon after v0.9.5.1

**Comment by Rokvach** [comment]
Moving this to Done as its being addressed on another ticket.
