### ISSUE TITLE
[Feature Request] [Item] [Low Priority] Crate Racks

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1892]
A relatively small but common sense item that hasn't been added by now. Crate racks would give us some place to store the ever-sliding crates that we are constantly showered with by outposts. Could work like Railgun-Shell racks or something; They would visibly stack crates on one another in a tidy shelf. Surprising this hasn't been added in the ever-present quest to eliminate unsecured (in the movement sense) items from the game.

**Comment by hubismal** [comment]
For the record, crates racks should probably hold something like 5 crates each, just because of the sheer amount of crates the game usually gives you (since every item has its own "crate category").

**Comment by Rokvach** [comment]
This has been implemented and is working correctly. Moving to Done.
