### ISSUE TITLE
Make the pressure logic of Barotrauma affliction fully moddable

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1893]
I have questions with this affliction. Is it hardcoded? Is there a way to edit how it works?

I've been working on some new afflictions. I've splitted internal damage into head trauma, chest trauma and left internal damage for the other 4 limbs. I've also made organ damage afflictions and made all of these affect each other and other afflictions in some way or another.

With all of this in mind, I'd like to edit the afflictions that barotrauma applies when it happens. Or make it so it slowly applies these afflictions while barotrauma is active.

**Comment by Regalis11** [comment]
Killing the character after the pressure gets too high is unfortunately hard-coded. It is possible to make the Barotrauma affliction apply additional afflictions, for example:

`  <Pressure
    name="Barotrauma"
    identifier="pressure"
    description="There is obvious massive organ damage and the blood vessels of the eye have burst, creating an unnerving red gaze."
    type="pressure"
    causeofdeathdescription="Crushed by water pressure"
    selfcauseofdeathdescription="You have been crushed by water pressure."
    limbspecific="false"
    maxstrength="1"
    showiconthreshold="10"
    damageoverlayalpha="1">
    <Effect minstrength="0" maxstrength="1" multiplybymaxvitality="true"
      minvitalitydecrease="0"
      maxvitalitydecrease="0">
      <StatusEffect target="Character">
        <Affliction identifier="internaldamage" strength="1.0"/>
      </StatusEffect>
    </Effect>
    <icon texture="Content/UI/IconAtlas.png" sourcerect="768,768,128,128" color="143,111,160,255" origin="0,0"/>
  </Pressure>`

This unfortunately won't stop the affliction from killing you: the dead character will simply have some extra internal damage in addition to the barotrauma affliction. This would be very easy to change though, I think we can make it more customizable in the upcoming patches!

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1710](https://github.com/Regalis11/Barotrauma-development/issues/1710) via [**ZenHub**](https://www.zenhub.com/)
