### ISSUE TITLE
AI no dialog when charging battery.

### ISSUE THREAD

**Issue by diebaeterz** [Regalis11/Barotrauma#1894]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When instructed an AI to charge battery. Debug error shows there is no dialog for charging battery

**Steps To Reproduce**
Started in a humpback sub.
Drain its battery.
Put battery to 0 percent charging.
Order AI to charge battery.
Error appears.

**Version**
Latest Version 0.9.4.0
0.9 Vanilla

**Additional information**
Disrupts gameplay when debug error occurs.

**Comment by Rokvach** [comment]
This has been fixed, waiting for the next patch. Moving to Done.
