### ISSUE TITLE
[0.9.5.1] [Issue] [Graphics] Volume Icons on crewlist don't indicate volume.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1895]
Right now the new voice chat VOIP volume icon is a dot that extends into a bunch of curved lines to indicate volume. While it properly works in the lobby, only the dot shows up in the ingame crew list in the top left. Someone probably just forgot to port over the new system.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a6f400e18b7ec5a0f6cee8a3818916714b081e1a (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
