### ISSUE TITLE
[Feature Request] [Chat] [Code] pop-out chat messages should stack instead of slide out.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1896]
As it currently stands, chat messages that are popping out of the side of the screen (when the chatbox is closed) are immediately slid back and "overwritten" when a new chat message is sent very soon afterwards.
It would probably take some more coding but it would be much better if instead the first chat message slid up to make room for the second chat message to slide in below it.

(think of the way half life 2 manages its subtitles.)

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1712](https://github.com/Regalis11/Barotrauma-development/issues/1712) via [**ZenHub**](https://www.zenhub.com/)
