### ISSUE TITLE
Signals lost after junction box and relay

### ISSUE THREAD

**Issue by FlufflesTheDog** [Regalis11/Barotrauma#1897]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a signal goes through a junction box followed by a relay, it's lost after the relay. 
Same/similar to #355 & #1876
*Apologies if a comment on said issues would have been ideal*

**Steps To Reproduce**
Bring a signal from a button to a junction box, then to an active relay, to something like a light component. Button has no effect.

**Version**
0.9.5.1 on Win10

**Additional information**
Included [test sub](https://github.com/Regalis11/Barotrauma/files/3877883/Relay.Test2.zip) to demonstrate; buttons toggle relays, switches make the signal that is passed along.

Bringing a signal through a relay *then* through a junction box works as intended.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/308d2f23bbaef8b45f574fbd2c2e031d9325df98 (private repo)

**Comment by ekqvist** [comment]
Tested with the provided sub and its premade wiring as well as a custom-wired system. Seems to be working correctly now. Moving this to Done.

**Comment by ekqvist** [comment]
We'll keep this open until we have reviewed it in a weekly meeting
