### ISSUE TITLE
[0.9.5.1] [Issue] [Networking] Welded doors/hatches open and close instantly when opened

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1898]
Visually, they appear welded, but briefly open and close. Makes things very confusing. Should be fairly easy to reproduce, weld a door shut and attempt to open it.

**Comment by Regalis11** [comment]
I unfortunately wasn't able to reproduce this, the door stays closed no matter what I do (tested with the buttoned door variants and the ones with separate buttons).

**Comment by hubismal** [comment]
I attempted with a welded hatch and a welded door at one point, I will try to see what produces this a little further

**Comment by FamiliarBreakfast** [comment]
I decided to do some testing, and it only seems to affect me when someone joins a multiplayer round that is currently running, one of the doors on the sub is welded, it isn't a custom door, they had to download the sub, and then had to go into spectate mode and wait for respawn. Which while it sounds unlikely, happens to me surprisingly often. Tested using a linux dedicated server (the one with the game, not steamcmd), but I've seen it in the wild on servers I don't think are Linux dedicated.

**Comment by Regalis11** [comment]
Still haven't been able to repro this, but I took a wild guess at what could be causing this (floating point inaccuracies causing the stuck-value to be set slightly below 100 client-side) and attempted to fix in https://github.com/Regalis11/Barotrauma-development/commit/91bba1c36258477599ec49dfb6ec2270a49ba0f4.

**Comment by Rokvach** [comment]
I haven't seen this issue happening for a while now, but there isn't any issues, so closing.
