### ISSUE TITLE
[0.9.5.1] [Networking] [Lobby] "Stuck" rooms in server browser after shutdown

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1899]
Stuck Lobbies (Lobbies that are shutdown but still persist on the server list) seem to be slightly more frequent in this update. Essentially, the host shuts the server down, users are kicked out. Despite this, the server still appears on the list and attempting to join gives red console output. Repeated attempts to join are met with the join button flat out not working. Refreshing doesn't make them disappear.
Note that this server doesn't seem to disappear when pressing "scan servers", meaning this is probably an issue with the new browser UI instead of the servers/serverlist themselves. Maybe it has to do with recent servers?

Relevant console output is as follows:
```
Recieved a disconnect message (ServerShutdown)
Do not attempt to reconnect (DisconnectReason doesn't allow reconnection)
Failed to join Steam lobby: 107...<lobby id of server i was in>
Failed to join Steam lobby: 107...<lobby id>
Failed to join Steam lobby: 107...<lobby id>
```
...etc, repeat with every attempt to join until it stops working.

**Comment by Regalis11** [comment]
@juanjp600 fixed by https://github.com/Regalis11/Barotrauma-development/pull/1247? Should this be moved to Review/QA?

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
