### ISSUE TITLE
Game crash after "Browsing for game"

### ISSUE THREAD

**Issue by DavidGNS** [Regalis11/Barotrauma#1900]
The game crashes after I click the online sever button
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/3881318/crashreport.6.log)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1110aab0e47c44015adafed62642e493926f3489 (private repo)

**Comment by Rokvach** [comment]
I have no idea how this could be tested, but judging by the code it does capture the exception just fine and won't cause a crash to occur. Moving to Done.
