### ISSUE TITLE
Low Multiplayer Count Forces Captain Job

### ISSUE THREAD

**Issue by Shido513** [Regalis11/Barotrauma#1902]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After the 0.9.5.1 update, multiplayer games with low player counts (in my case, 2 or 1) and adding bots forces the host to be captain instead of any of their preferred jobs. 

**Steps To Reproduce**
1. Go into a multiplayer game with a low number of players or host a server alone/with a low number of players.
2. Have everyone prefer other jobs over captain (captain should not be on their preferences list at all).
3. Star the game and the host should be forced into playing captain regardless of their preferences.

**Version**
v0.9.5.1

**Additional information**
https://github.com/Regalis11/Barotrauma/issues/1549 This is the previous time that this issue came up, and it was resolved to where no job was required. I do not know why captain is being forced again.

**Comment by OverwatchVoice** [comment]
Could it be intentional?

**Comment by Shido513** [comment]
I saw an old issue from an older patch from when they revamped the jobs and they made it so that anyone could be any job and that forced jobs were no longer needed. So, this could be intentional, but I don't know why it would be intentional.

And, to give play information on how my friend and I play (or when I play solo on a multiplayer server and host alone so I can have a "personal character") to the devs, I play as a doctor and they play as a mechanic. With how this currently works, depending who is hosting, one of us is forced into playing as a captain, which neither of us want to play or enjoy playing as.

**Comment by Regalis11** [comment]
Should no longer happen
