### ISSUE TITLE
Poweritems issue

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1904]
The latest update is causing issues with relays or custom items using Power_in and Power_out outlets.

I tried looking for a changelog or something to see if there were any changes to power grid related code but I couldn't find anything.
I had a custom power box with the power, power_in and power_out outlets that worked just fine before the update. I tried editing it but the item starts working again only if I leave just the power outlet in it. 
Signals from relays are also being weird. I got a bte ship with lighting-fast ballast tanks that can go from 0 to 100% almost instantly. I'm still doing some tests to see if I can identify more issues but it seems it's the same issue that plagued relays a while ago.

**Comment by Tor-del** [comment]
Same problem.
More than one relay in a circuit creates problems. Especially with overvoltage.

![2019-11-23-19-33-55](https://user-images.githubusercontent.com/4242684/69482801-8325e180-0e28-11ea-8971-3e1848777692.gif)

https://youtu.be/5O6w-fOPxas

**Comment by Regalis11** [comment]
From the changelog:
> Rewrote power distribution logic to resolve several issues and oddities in the way power was distributed across electrical grids, particularly when relays were used. The new system is also less performance intensive, so submarines that had performance issues due to large and complex power grids should now run better.

This was most likely caused by the rewrite. Could you please send the config file you're using for the custom power box so I can give it a test to see if the issue is related to the way it's configured or an error in the game?

**Comment by ChikoEduardo** [comment]
Here. The item that is no longer working is called "Power Distribution Unit" or "pdubox" as its ID.
I use these next to junction boxes to wire everything in a room to the extra power slots. :p
https://cdn.discordapp.com/attachments/405014318892056577/648181624617304074/poweritems.xml

**Comment by Regalis11** [comment]
Thank you! I think I see what the issue is: I'm afraid the new system is more strict about how the power inputs and outputs are configured. Junction boxes must have a power output that you connect all the wires to (like the vanilla junction box), while relays have separate in and out connections. Having two power outputs and one input like in your power distribution unit is unfortunately not supported, but you could get the device working by removing the extra "power" output and changing the generic PowerTransfer component to a RelayComponent.

**Comment by rav2n** [comment]
This is a very unpleasant moment for me, given that I prefer to power drainage pumps directly from batteries. In my opinion, it is logical to have a fault-tolerant system on the ship. And the number of switchboards takes up less space, which gives more freedom in the construction of the submarine. Now it does not work. But this is all the lyrics.

I want to add: 1) the bunch of batteries now does not work correctly when connected in series. energy does not flow from the battery to the battery or is flow incorrectly (I watched how the “receiving” battery lost energy while the “giving” battery was connected to it)
2) the discharge coils do not work directly from the capacitor. When connected via a relay, they do not always work.
3) the control terminal does not send the control signal correctly to several devices
4) the switches do not work properly with bulbs. Possibly related to paragraph 3

If you want to take a closer look, you will find all these problems on this ship: https://steamcommunity.com/sharedfiles/filedetails/?id=1862739075

**Comment by Regalis11** [comment]
@rav2n That appears to be unrelated, because this issue seems to be about custom power transfer components that have non-standard input and output connections.
