### ISSUE TITLE
[0.9.5.1] [Issue] [UI] Sub editor unusable on lower resolutions

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1905]
The sub editor is nigh unusable on lower resolutions. This is because the bottom checkboxes are cut off by the "previously used items" box. Somehow, the scaling was removed for the checkboxes in 0.9.5.0, which is weird because the sub editor works just fine in 0.9.4.0.
You can't view hulls or gaps anymore, which makes things much, much harder, and essentially impossible.

**Comment by Rokvach** [comment]
Just fixed it an hour ago, fix should arrive in the next patch. Moving this to Done.

**Comment by hubismal** [comment]
fastest fix ever?
