### ISSUE TITLE
[0.9.5.1] Battery no longer outputting power without a relay since major update. Bug or feature?

### ISSUE THREAD

**Issue by Demonchipmunk** [Regalis11/Barotrauma#1908]
**Description**
I noticed a super simple custom sub I made stopped working after the recent major update. I quickly figured out that the one battery on the sub was no longer successfully powering the navigation terminal and three lights (despite the fact that the battery was charging fine). Tried adding an active relay in between, which fixed the issue, but wasn't sure if this was an intentional change or a bug.

**Steps To Reproduce**
A battery with it's power output connected to a machine's power input won't power that machine, but a battery with it's power output connected to an active relay component connected to that machine will.

**Version**
0.9.5.1 in Windows, but hadn't played since before the major update, so I assume it has something to do with the changes to the power distribution logic in 0.9.5.0

**Additional information**
Like I said, I'm not really sure if this is a bug or a feature, and I already figured out how to fix it in the editor, but I thought I'd post a bug report since it was super obvious what changed when I was troubleshooting, and I figured it couldn't hurt to mention. :)

**Comment by rav2n** [comment]
https://github.com/Regalis11/Barotrauma/issues/1904

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e03d056488f0f737360192f39f340f783d401c9a (private repo). Will be included in the next patch!

**Comment by danielasteljoki** [comment]
Tested. Batteries are indeed able to power devices directly.

**Comment by Rokvach** [comment]
Moving to Done.
