### ISSUE TITLE
Monster respawning makes it a very bad idea to kill monsters

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#191]
Basically, the more monsters you kill, more of them will spawn.
This can rack up to about 3 shrimps every goddamn minute relentlessly chewing your ship, making it near damn impossible to keep up with them. You will waste all your ammo in no time and it becomes an instant game over.

...perhaps monster respawning should be turned off entirely??? :V :V

**Comment by Crystalwarrior** [comment]
Alternatively, have a "population" variable for specific monster types so you can basically "genocide" their population after a few kills.

**Comment by NilanthAnimosus** [comment]
The reason this is such an issue is there is no delay whatsoever on respawns. 

If you follow the code from a Monster event update to Scripted Event update to the Game session Update and such, this is effectively called every update.

This does mean the replacement monsters spawn immediately upon death, there is no cap as well so if a submarine sinks near the monster event, something like 3 crawlers will result in 4..5...6..7 and so on, the instant they die, for eternity.

This behaviour is further confirmed by killing the last monster event spawned fish that could be found (Such as kill crawler 10 of 0-10) using commands then checking for the next highest number (Such as 11).

**Comment by Regalis11** [comment]
Monster respawning has been disabled in the dev branch, considering this fixed
