### ISSUE TITLE
[Issue] [Bot AI] Bots report for neighboring rooms from their own

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1910]
If something happens in a neighboring room and a bot "sees" it (such as an item needing fixing) they will say "Broken devices/Monster in (Room that they're in)" instead of "Broken devices in (Room that issue is in).
Ex: A bot in the reactor room seeing a fried junction in the junction room through an open door will say "Broken devices in Reactor Room!"

**Comment by itchyOwl** [comment]
Fixed.

**Comment by Rokvach** [comment]
Working correctly, moving to Done.
