### ISSUE TITLE
[Feature Request for an Issue] Give dock indicators black outlines

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1911]
Relatively small feature request for usability. The current green docking port indicators blend in way too much with the current blue sonar noise. Docking is already really annoying without the visibility issues, so it would be nice if these dark outlines were added to help them stick out.

**Comment by hubismal** [comment]
![gimpvisualization](https://user-images.githubusercontent.com/47284081/69774548-d74c0100-115b-11ea-9abc-4f3c9f11c3f7.png)
i am now upgrading my feature requests with awesome visuals for fans of picture books

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/0b051e6be60b9f7ec4346393abde4f208bff9e46 (private repo)

**Comment by Rokvach** [comment]
Tested, seems fine. Moving to Done.
