### ISSUE TITLE
Discharge Coil not works

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#1912]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Discharge coils consume energy, but do not shock.

**Steps To Reproduce**
Swim nearby to the discharge coil and activate it.

**Version**
0.9.5.1

**Additional information**
This problem is really not related to user devices, just like the problem with light bulbs, relays, and batteries. But this is still a problem!

**Comment by Rokvach** [comment]
This issue has already been fixed, fix should come with the next patch. Moving to Done.
