### ISSUE TITLE
[Feature Request] [Design] Nametag Opacity/Alpha based on Character Lighting

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1914]
Thanks for implementing lower ambient lighting. Now that it's in, how about giving it a purpose?

It would be cool if a character's nametag/health opacity was based on how well lit they are. I originally suggested having lower lighting because it would hide more of the monsters, but also because it would hide the players. Unfortunately, the nametags are essentially a dead giveaway because they will always be bright white beacons (or grey ones, either way you get what I mean). **This should also probably apply to their "talking" speech bubble indicators**. You could make the case that their talking indicators standing out in the dark is like hearing them, but we already have a dedicated hearing system that is the proximity chat.
![2019-11-27-220412_130x203_scrot](https://user-images.githubusercontent.com/47284081/69776458-ecc42980-1161-11ea-83d5-91763c979434.png)
Here is what a character currently looks like in total darkness when your mouse isn't hovering over them. Note the fact that the nametag is very visible despite the character themself being virtually invisible.
![nameOpacity](https://user-images.githubusercontent.com/47284081/69776547-53e1de00-1162-11ea-8f3e-0ac30dc1b3e0.png)
The benefits to this are obvious, but I will say them anyway. Characters could be hidden more effectively, both alive and dead. If you're on the run, dewire a light and hide in the supply closet. If you just killed/cuffed the security officer and need to hide his body, throw him in a dark room and nobody will spot him. And of course, ambush an unsuspecting captain in a dark hallway. The possibilities are endless.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1713](https://github.com/Regalis11/Barotrauma-development/issues/1713) via [**ZenHub**](https://www.zenhub.com/)
