### ISSUE TITLE
Oxygenite shard explodes in inventory

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1916]
@Regalis11 commented on [Thu Nov 28 2019](https://github.com/Regalis11/Barotrauma-development/issues/1207)

https://steamcommunity.com/app/602960/discussions/1/3356799628321284248/

> It seems as if oxygenite shards are not only exploding when you use a stair up- or downwards crossing a (large) plattform, but too, when the ship is under water and you cross said plattforms SWIMMING...
> 
> I've had a game, just some moments ago, where I wanted to leave the ship (Humpback) through the lower airlock to throw away the three shards, we were getting by deconstructing a looted sky artifact, because we had several ships blown about because of nothing, because of that stuff... and suddenly BOOM. Again. I was not hurt because the three shards were not in my inventory but in a toolbox, which was in my inventory... lol.
> 
> And yes, the airlock was completely flooded (completely under water) BEFORE I was trying to leave the ship.
> 
> Please, take care of that stuff. It is fine that it is volatile, but it should not be unfair and completely unforseeable...

They should only explode when they receive a high enough impact

**Comment by Regalis11** [comment]
Haven't found a way to reproduce this, if anyone has any idea how to make it happen please let us know!

**Comment by Ek-Videogames** [comment]
For reference, the only times I've seen oxygenite shards and liquid oxygenite explode when in inventory have been when climbing up and down ladders through hatches or when going up and down stairs.

However unknown if it is being triggered by interaction with the ladder/stairs, interaction with moving from one hull to another vertically, or interaction with platform hitboxes.

**Comment by Regalis11** [comment]
Unfortunately we still haven't found a way to reproduce this, so we'll be closing this ticket for now.
