### ISSUE TITLE
[Feature Request] Optional Everyone can Sabotage

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#1918]
Just a small little request to have a server option where everyone can sabotage anything right from the start, traitor or not.

**Comment by OverwatchVoice** [comment]
Why would anyone but the trolls use it?

**Comment by thegrb93** [comment]
That's how the pre-alpha was all the time no admins were on. Had a lot of fun back then because it was basically a war between ppl who wanted to survive and ppl who wanted to kill everyone.

**Comment by NilanthAnimosus** [comment]
This would actually make a really good server option. Default off perhaps, but servers wanting for chaos can manually turn it on.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1714](https://github.com/Regalis11/Barotrauma-development/issues/1714) via [**ZenHub**](https://www.zenhub.com/)
