### ISSUE TITLE
VOIP volume settings don't work at all

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#1919]
_- [x] I have searched the issue tracker to check if the issue has already been reported._

### **Description**
The VOIP volume settings for both input and output do not work. 

### **Steps To Reproduce**
Setting the transmission volume (the one that goes to 1000%) causes it to revert to either 1000% or 801.10%
Setting the volume of other peoples voice chat does not actually change the volume, except when set to 0%, in which case it successfully mutes it. However, 5% to 100% output at the same volume.

### **Version**
v0.9.5.1 Linux

**OS Specifics:**
OS: Manjaro Linux x86_64 
Kernel: 5.3.7-2-MANJARO 
Shell: zsh 5.7.1 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 
WM: KWin 
CPU: Intel i3-6100 (4) @ 3.700GHz 
GPU: NVIDIA GeForce GTX 950 
Memory: 15959MiB

**Steam System Info:**
https://pastebin.com/zzY9LppV

### **Additional information**
This is not clientside only. Other players complain about the volume. It also seems to affect them, so I'm not sure if it's OS specific. However, just in case it is hardware related, I have included extra details.

**Comment by Regalis11** [comment]
Fixed in 5fe13ba

**Comment by Rokvach** [comment]
Waiting for a Unstable build so this can be fully tested

**Comment by Regalis11** [comment]
Moving back to the Backlog, Juan spotted an issue in the way I implemented this that needs to be resolved (multiplying the PCM by a constant value can cause clipping that cannot be remedied no matter what you set the volume to).

**Comment by juanjp600** [comment]
Reimplemented PCM amplification in https://github.com/Regalis11/Barotrauma-development/compare/48f5ef34cd...c69cfefa05, this time avoiding the clipping issues.

**Comment by Regalis11** [comment]
Tested this locally and couldn't find any issues.

**Comment by Rokvach** [comment]
Closing, I will take another look at this once its included on a Unstable.
