### ISSUE TITLE
Maintain the wiki so it is up to date with the game's mechanics

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#192]
http://barotrauma.gamepedia.com/

The game has several unexplained mechanics stumping the players, like chemical effects, reactor operations, and especially wiring.

We need to update and maintain the wiki to be up to date, perhaps even providing relevant links in-game? Job specific greeting messages could help as well.

But this also feeds into the tutorial issue that still needs resolving: https://github.com/Regalis11/Barotrauma/issues/8

**Comment by juanjp600** [comment]
Perhaps we should automatically dump the contents of the XML files so we have a baseline?

**Comment by Regalis11** [comment]
This doesn't really belong on the issue tracker imo (but still something we need to look into).
