### ISSUE TITLE
[Feature Request] Remove/Shrink the beacon of light emanating from the player

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#1920]
I _love_ that you made the darkness darker (though it could be a bit darker). What I _do not_ love is that the circle of light that emanates from the player, has gotten bigger.

I mentioned this previously in [this](https://steamcommunity.com/app/602960/discussions/2/1636418037460783756/) thread. Back then, the default ambient light was so bright you could not see this circle of light. But now, you can see it. Back then, I was also using cheats to make ambient light darker. And I'm pretty sure the circle is brighter.

To illustrate my point, I've attached some screenshots of player mode and freecam mode, some with normal ambient, and some with ambientlight 0 0 0 0, to exaggerate the issue. In all images, there are no lights. The reactor is off and no emergency lights have been placed that are active.
I've drawn red lines at the apparent cutoff point, and ignore the blue light, it has a range of zero.

![Default ambientlight playercam](https://user-images.githubusercontent.com/48958412/69846150-2cae0e00-1241-11ea-8f4c-cf56315b3776.png)
![Default ambientlight freecam](https://user-images.githubusercontent.com/48958412/69846151-2cae0e00-1241-11ea-9454-c1a6b9deeb2d.png)
![0 0 0 0 ambientlight playercam](https://user-images.githubusercontent.com/48958412/69846152-2d46a480-1241-11ea-8edf-2849cfade9c3.png)
![0 0 0 0 ambientlight freecam](https://user-images.githubusercontent.com/48958412/69846154-2d46a480-1241-11ea-9ce7-1ea515873ec9.png)
_Btw, those are standard size bed decor, just fancied up a bit._

**Comment by hubismal** [comment]
here is a pre-update screenshot with the ambientlight set to 0 0 0 0 as part of the argument I made on the discord server (that helped make the ambientlight removal official). make of this what you will. it seems to be mostly the same though
![nowYouSeeMe0](https://user-images.githubusercontent.com/47284081/69848039-78ab8380-123e-11ea-9d8d-9af5508718dc.png)

**Comment by Regalis11** [comment]
Decreased the range and brightness in https://github.com/Regalis11/Barotrauma-development/commit/fb380bcdaf23956fa9fff223c8a34766c2e9b925 (private repo)

**Comment by Rokvach** [comment]
Tested, looks great. Moving to Done.
