### ISSUE TITLE
Inverted mouse buttons not recognized

### ISSUE THREAD

**Issue by blackdragonTOW** [Regalis11/Barotrauma#1921]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Inverted mouse buttons in the system settings is not reflected in game

**Steps To Reproduce**
Install a left handed mouse
In the mouse settings in Windows change it from Right to Left
Start game to main menu
---> Using the left mouse button does not select any options (right click works)

**Version**
v0.9.5.1 

**Additional information**
Left-Handed death adder is my current mouse.

**Comment by FamiliarBreakfast** [comment]
I can confirm this does not happen on Manjaro Linux 5.3.7-2-MANJARO when using the built in settings menu. I am not, however, using a special left-handed mouse, though I am using a deathadder chroma which _should_ have similar (if not identical, barring lighting) drivers to the essential.

One issue I did notice, was that when using left handed mode, I couldn't click with the mouse buttons to get past the initial "Press any button to start." Then again, I'm not sure if mouse works normally.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.

**Comment by juanjp600** [comment]
This issue was accidentally reintroduced in v0.20.10.0 with the upgrade to SDL 2.24.2. [SDL changed the way mouse button swapping is handled in 2.0.14](https://github.com/libsdl-org/SDL/commit/72379ba510cb6229f65c92d34709264e417448e6), the version we were using was older than this up until recently.

**Comment by juanjp600** [comment]
See #11184
