### ISSUE TITLE
No localization strings for missions in all language files

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#1926]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There are no localization strings for the new  mission "Terminate a swarm of threshers", the text is only in the file Missions.xml

**Steps To Reproduce**
Open any localization file and search by id "killthresherswarm1".

**Version**
0.9.5.1

**Additional information**
There are also no strings for the mission id "killhammerheadgold", but I have not seen it in the game, maybe the mission has not yet been added to the game.

**Comment by Regalis11** [comment]
Added for localization in https://github.com/Regalis11/Barotrauma-development/commit/238e155bbb702d5724dd12f30d26995228a961ac (private repo), coming up in the next major update

**Comment by Rokvach** [comment]
They have been added, closing.
