### ISSUE TITLE
Creatures will prefer chewing/ramming alien ruins if they are closer than sub structures

### ISSUE THREAD

**Issue by ChuckoKokos** [Regalis11/Barotrauma#193]

**Comment by Regalis11** [comment]
The only way I've been able to reproduce this is to have something inside the ruins the creatures want to attack (e.g. an edible creature, nasonov artifact).

**Comment by Regalis11** [comment]
Still haven't been able to reproduce this, without further info I'd assume it was caused by some target inside the ruins.
