### ISSUE TITLE
'Door with Buttons' only reads first ID card in inventory when checking their tags

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#1932]
### Issue:
When holding multiple ID cards in inventory, attempting to open a door using built-in buttons only checks the first ID card in inventory encountered when determining if it fails the picking tag check.

This issue arises in gameplay primarily when using a second ID card stolen from someone to gain access to a locked door. It is usually worked around by equipping the ID, or otherwise replacing the ID in your ID slot _(as the slot is read by the door picking check before the hotbar is)_ to then pass the check and open the door.

**Steps to reproduce:**

- Load into a sub with ID restricted doors with buttons
- Spawn as someone other than captain & sec
- Spawn a captain or security officer bot and steal their IDs
- Attempt to open any restricted doors first having the correct ID in your hotbar,
 and again with the ID equipped replacing your own. 
_(Or with one in front of the other on the hotbar)_

**Additional info:**
This bug appears to effect doors with buttons specifically. When trying to open secure lockers, secure crates, or activating buttons, the game seems to accept any number of IDs in any position of the inventory.

Moving your ID from the ID slot to the hotbar with other ID cards and then rearranging their order is a straightforward demonstration of the "only checking first ID" behavior.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e26059a2c0a161c9b81921148a444f718dc0246f (private repo).

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
