### ISSUE TITLE
[Feature Request] Expansion of wireless elements for pvp.

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#1933]
Is it possible to implement the following things in the game: add a "assign channel" contact to the wireless element, add several data transfer contacts to the dock port (in addition to the electricity transfer contact), add the "only animals" option to the motion sensor.

**Comment by NicolaruS** [comment]
In pvp mode, the rebel submarine has the same channels of operation of the Wi-Fi modules, which is why the use of Wi-Fi modules in the management of the sub and drones can cause problems. Therefore, it is important to have an additional contact in the Wi-Fi module to change the control channel. The introduction of a contact for changing the range of the wifi module will help to realize the new position of acoustics on custom submarines.

**Comment by NicolaruS** [comment]
If the developers add a contact for the range and channel of the wi-fi module, players will be able to make their own sonars. This will create a new profession for acting out the role.
When this happens, I’m ready to provide my version of custom sonar.

**Comment by Regalis11** [comment]
Added the "set_channel" input in https://github.com/Regalis11/Barotrauma-development/commit/7e0f8200b747b1703762b4b53912c467c58a6a46

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1716](https://github.com/Regalis11/Barotrauma-development/issues/1716) via [**ZenHub**](https://www.zenhub.com/)

**Comment by NicolaruS** [comment]
Is it possible to add another set_range contact?

**Comment by Regalis11** [comment]
It'd be possible, but personally I'm not sure if that's a good idea. I see the maximum range of a wifi component as an inherent property of the item, sort of like the maximum output of a reactor or the maximum capacity of a battery. Allowing it to be modified at-will would for example make it possible to communicate with characters on a ruin expedition regardless of the distance.

**Comment by NicolaruS** [comment]
if I understand everything correctly, now the distance of the wifi module is 20,000 conventional units corresponding to the size of the submarine as 40 to 1, that is, 500 meters, with a boat size of 50 meters, 10 submarine hulls are obtained, which therefore covers most game situations. Sorry for the complicated sentence. I use an online translator.

**Comment by NicolaruS** [comment]
I think the ability to change the range will not greatly affect the usual gameplay. If this position is fundamental, is it possible to add set _range as an identifier property so that it is possible to do this at least in the form of a user mode, since a contact without editing the identifier can also be registered in the user mode.

**Comment by NicolaruS** [comment]
Practice has shown that creating a sonar in the game is real. The presented sonar works at ranges up to 1500 meters and determines the direction to the enemy with an error of up to 1 hour and range with an error of 50 meters. The entire sonar occupies about 300 parts, and its subsequent modernization entails a constant increase in the number of parts. If I give the wifi module contact set_range, I can not only significantly reduce the number of parts, but also can determine the range with an accuracy of 1 meter and the speed of the enemy.
https://cloud.mail.ru/public/4kdH/4UPzd7NXN

**Comment by NicolaruS** [comment]
Alternatively, you can give the contact set_range and limit the maximum range value to the max range parameter. Then players will be able to dynamically change the range of Wi-Fi and will not exceed the threshold set by the developers.

**Comment by NicolaruS** [comment]
> I see the maximum range of a wifi component as an inherent property of the item, sort of like the maximum output of a reactor or the maximum capacity of a battery.

Alternatively, you can give the contact set_range and limit the maximum range value to the max range parameter. Then players will be able to dynamically change the range of Wi-Fi and will not exceed the threshold set by the developers.
