### ISSUE TITLE
Wrong room name is called by AI

### ISSUE THREAD

**Issue by SvenDaedalicS** [Regalis11/Barotrauma#1935]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When order an AI to extinguish a fire in the reactor room, it calls the "roomname.reactorroom".   

**Steps To Reproduce**
1. Order AI to extinguish fires 
2. Overheat reactor
3. Observer AI comment in Chat

**Version**
Windows/MAC/Linux 0.9.6.0

**Additional information**
![20191212165815_1](https://user-images.githubusercontent.com/58743689/70733659-08573480-1d0b-11ea-919e-7c3c00ea752e.jpg)

**Comment by ekqvist** [comment]
This issue seems to be related specifically to extinguishing fires

**Comment by ekqvist** [comment]
The issue should be fixed with Regalis11/Barotrauma-development@0e97943 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
