### ISSUE TITLE
[Simple Feature Request] [Moderation] Show traitor objectives as seperate categories in serverlogs

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1936]
~~there's no way (assuming I'm correct about this) for hosts to verify that what someone did was in fact a part of their traitor objecting and not just them rdming. It would be hugely beneficial to show in the serverlogs what a player has been tasked with doing.~~

~~There is the popup at the end of the round but it doesn't stay for long and also doesn't display all of their tasks. This feature request is more or less for newer hosts who don't know what all the traitor objectives are in this game.~~

This is a mistake. There is a way, but there isn't its own message category. It would be nice if a category was added to make it more obvious.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1717](https://github.com/Regalis11/Barotrauma-development/issues/1717) via [**ZenHub**](https://www.zenhub.com/)
