### ISSUE TITLE
[Issue] Watchman doesn't spawn for individual missions

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1938]
What the title says. seems to be an issue where if you set the rounds to not end immediately once docked, the watchman isn't in the outpost so normal players can't end the round (the host can via end round obviously).

**Comment by FamiliarBreakfast** [comment]
TIL this is a bug. Regardless, it's mega annoying. Some servers seem to have scripts to fix this, but it should be in the base game.
