### ISSUE TITLE
Crash when hosting server/Failing to connect when hosting

### ISSUE THREAD

**Issue by Athenades** [Regalis11/Barotrauma#1939]
Trying to host a server from the main menu. After I've gone through the initial settings, and start, either it tries to connect for some good seconds, and then fails. Or I'm able to get the server up, but it 'unexpectedly crashes' back to menu after a good seconds in the lobby. Settings were Public (even from the txt. file).

Reproduce;
Main Menu --> Host Server --> Start

Version 0.9.5.1
MacBook Pro

**Comment by Regalis11** [comment]
We have a newer ticket about this with a bit more info (#3666), closing this one
