### ISSUE TITLE
Typhon crew quarters loose vent cannot be open. This ruins some traitor rounds.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#1941]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. You can see the version number at the bottom left corner of the main menu, and in a file called "Version.txt" inside the game folder.
Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by danielasteljoki** [comment]
The vent was placed a bit too high to be in interact range. Fixed in 44d43d5 in private repo.

**Comment by Regalis11** [comment]
Instead of adjusting the position of the panel, could we make the interact range of the panels larger? 10 pixels is such a small range that it's very easy to accidentally place them so high/low that they become impossible to interact with. Another way to go would be to add a trigger to them, so standing close enough to the panel/vent is not required but having the cursor on the item is enough.

**Comment by danielasteljoki** [comment]
We would want to keep the hiding places unnoticeable, unless you're looking for them. In that case having a short interact range makes sense.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.

**Comment by Regalis11** [comment]
I thought it would be possible to make the vents interactable when you're cursor is on the trigger while the interact range is kept small, but looks like that isn't supported (you can't interact unless you're within interact range or inside the trigger). Going to have to implement that.

**Comment by HalfdeadKiller** [comment]
The short interaction range may explain why I can't ever find traitor items on my custom submarine. I didn't know the interaction range was physically so small. I just figured that only traitors could interact with the vents or something. Any documentation on how to make custom submarines more traitor compatible would be very appreciated.

**Comment by Regalis11** [comment]
Added "RequireCursorInsideTrigger" property in https://github.com/Regalis11/Barotrauma-development/commit/7eeadb4d36bc8156eeead0219b9100dc3f553931 and configured the panels/vents with a larger interact range but a small trigger area the cursor has to be inside.

**Comment by Rokvach** [comment]
No issues, closing.
