### ISSUE TITLE
[BUG] Lamps and lights change the sprite color of their lightbulbs, after getting activated with a colored light signal.

### ISSUE THREAD

**Issue by DerEchteSpatz** [Regalis11/Barotrauma#1942]
**Description**
When you do activate a neutral (white) sprite colored "lamp" or "light component" which has been set to colored light, it (or better the sprite of the LIGHTBULB) seems to get changed in its sprite color setting, fitting to the color of the light which was activated. You can see this change of (lightbulb) sprite color, after turning OFF the lamp/light again.

**Steps To Reproduce**
I included a link to a test-ship I created for reproducing the bug. Further, more detailed information are inserted there (including a step to step instruction).

**Version**
v.0.9.6.0 on a Windows 7 (64bit) system

**Additional information**
The link to the Workshop-"submarine", I created for reproduce the bug:
https://steamcommunity.com/sharedfiles/filedetails/?id=1939061480

**Comment by Regalis11** [comment]
Thank you for a very informative bug report again! Managed to fix this in the private repo (https://github.com/Regalis11/Barotrauma-development/commit/e0e572438fcd190445f9c92112d7732834aade1e)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
