### ISSUE TITLE
Improved headsets (more usable channels at the same time)

### ISSUE THREAD

**Issue by DerEchteSpatz** [Regalis11/Barotrauma#1944]
Actually, you can enter different channels into the current headsets to be able to use different Radio-channels, which is a really good feature.

But there are some problems with it:

1.) You can not change the channel of the headsets when ingame. Either the headset gets changed in full submarine-editor-mode or it is not adjustable anymore after the start of the campaign/round...
At least there should be an option to buy different adjusted headsets in the shops, since you can not change them, otherwise.

2.) Currently, the headsets cannot receive signals in more than one channel. When you take a look at actual real life radio, used by fire departments for example, this is quite realistic. But in real life, you can have more than one walkie talkie lying beside you and react to them as soon as one receives a signal. This is not possible in Baro because you can hear only the radio signal of the single headset you are wearing...
So I propose to give headsets way more adjustability. I want them to be able to RECEIVE multiple channels at once. And to give them different SENDING-buttons (located directly on the keyboard of the player), representing the push-to-talk-buttons for the different channels.

So the question may rise, what all this is needed for. Let me give you an example. When we send out a diving team, I would like to have some headsets with a channel, only for the divers to communicate with each other, without having to worry to spam the ship channel with their stuff. Regarding this, the leader has the choice of either taking the headset off when leading his team and only occasionally taking it on to send informations to the ship, or to let it equipped and spamming the channel with his orders... The problems are not hard to see, are they? If he chooses to take it off, in that time, the ship may run into trouble and want to withdraw the team, which would not be noticed by the team under the current communication system.
If they choose to use specifically customized headsets (other channels) the captain does not hear his crew, as long as he tries to hear or speak to the diving team, so that would be the worst solution (possibly not overhearing cries for help from the divers, when he changes headsets to check the ship channel, from time to time)...

With customizable channels, he would adjust the headsets of his dive men to only receive and send on diving channel. His own headset would be set to diving channel and commanding channel, so he could send his commands to his divers, without worry, but still be able to receive commanding channel on the ship and send messages to it, too, when necessary.

I think the concept of one global radio channel is not useful. It is completely irrelevant for the engineers to hear that the security has ordered the security men to meet at the security room. This is only spams their concentration (and the global channel)...

If I would be able to customize the channels to my liking, I would rename global channel into
 _"emergency channel"_ (which gets only used, when there are emergency situations - like intruders onboard or a heavily damaged and sinking ship),
_"diving channel"_ (only for the diving crew) 
_engineer & mechanic channel_ (which does get used when it is around damage reports or giving orders to repair crew) 
_command channel_ (which gets only used by the leaders of their compartment - i.e. Captain/Officers, Chief Engineer/Mechanic, Chief of medics, Security Chief), 
_security channel_ 
and possibly _medical channel_.
Under this configuration the regular standard VOIP mode would be **local, not global** radio.

The local chat would be the standard means of communication on this system.
Using radio channels would be used only when there is some ship- or crew- concerning information...

Of course, the standard configuration on the headsets would remain as it is, now, so until someone chooses to adjust the crew headsets (per example the captain orders his crew to adjust them at the beginning of the mission) they would work as they do, now.

PS: And if you are at it, would it be possible to reduce the hearing range of local VOIP drastically? Like only the half or even a quarter of the range of the current setting? It would be perfect if you could only hear local, when are in the same room (aka in sight), but not outside of a room (unless speaker really shouts into the mic)...

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1721](https://github.com/Regalis11/Barotrauma-development/issues/1721) via [**ZenHub**](https://www.zenhub.com/)

**Comment by IngvarJackal** [comment]
@Regalis11 any update on that?
