### ISSUE TITLE
[Issue] Problem with the source code. And server stops working? Idk how to add labels

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#1946]
so I downloaded the source code from 6.0. But I see around 20 errors mostly about names not existing in the current context. Is this the reason my server does not work and the console says the packet size limit is exceeded?

**Comment by Regalis11** [comment]
Could you please paste the errors here or take a screenshot?

I don't think the errors are related to your server not working - if you're getting compiler errors, I'm assuming you haven't been able to compile the game.

**Comment by MrTeco** [comment]
My server did not fail until the update.

**Comment by MrTeco** [comment]
Might be missing something

**Comment by MrTeco** [comment]
I don't know how but I fixed it by first compiling every single asset

**Comment by MrTeco** [comment]
![image](https://user-images.githubusercontent.com/59005337/71106922-6e870000-21c0-11ea-8b6d-0e9715199796.png)

**Comment by MrTeco** [comment]
Lots of errors

**Comment by Regalis11** [comment]
I'm sorry, I'm afraid we cannot help you without more details on the issue. 

To be clear, do you mean the server installed from Steam does not work, or that a server you've compiled yourself from the source code does not work? If the latter, have you done your own modifications to the code? I'm also a bit confused what you mean by the console saying "packet size limit is exceeded" if you haven't been able to compile the game.

**Comment by MrTeco** [comment]
I did succeed to compile, but the dedicated server console says the packet size is too big, something like that.
And I wonder why all of these 'namespaces' can't be found.
Basically there's a bunch of errors that were already there.

**Comment by Regalis11** [comment]
Have you done any modifications to the source code, did you pull and compile the code as-is from the repository?

**Comment by MrTeco** [comment]
No, I just got the source code from the repository and the errors were there.
I have the same exact modification as in the last version and that one worked when there were no errors so I am sure its not because of my modifications.

**Comment by MrTeco** [comment]
Also, sorry for the late responses. I am not used to github really.

**Comment by juanjp600** [comment]
See https://github.com/Regalis11/Barotrauma/commit/ace358631e3ef847e54842a85a012c74c000da3d and https://github.com/Regalis11/Barotrauma/commit/3c50efa5c9d17f4df2a90ddd3e46a9d06ffdf9df

It seems that there was a mishap updating the public repo. These commits should address some of the issues when trying to build.
