### ISSUE TITLE
Rail Gun Light Toggle

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#1947]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the coil gun these is a node to toggle lights, on the rail gun there is not, but they both are lit.

**Steps To Reproduce**
access the rail gun panel to see that it does not have a light toggle node.

**Version**
Beasts within first hotfix 1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f3462ac3cffa29ddba862cccb9bfa4fff03e00b (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
