### ISSUE TITLE
[BUG] [Urgent] Linux Crash on server browser open (It's different this time)

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#1948]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon clicking the server browser button, the game crashes. Notably, this only happens when launching with steam. Launching the executable directly avoids this issue. (at least, it did, but with recent updates it is impossible to get past the launch screen when launching from executable). Because of this, it is currently impossible for me to play multiplayer.

Yes, I am aware reports like this already exist. But this one doesn't appear to be related to mono, and it never 'fixes itself' like the last one did. Furthermore, this is a much harder crash as steam rarely recognizes the program even closed (specifically steam's watcher process doesn't get killed), though it now does create a crash report.

**Steps To Reproduce**
1. Open the game
2. Hit server browser
3. ???
4. Game crashes

**Version**
v0.9.6.0, Linux Version. Specifically, I'm using the Steam Native Runtime.
Neofetch: https://pastebin.com/RARfmrgh
Steam System Info: https://pastebin.com/zzY9LppV

**Additional information**
Crash Log: https://pastebin.com/fntRWXJ1
Crash Log 2: https://pastebin.com/chdFee0E

**Comment by Rokvach** [comment]
Confirmed to be working correctly now, moving to Done.
