### ISSUE TITLE
[Polish] [Character Animation] Mudraptor walk cycle is slightly slower than actual speed

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1949]
You will see this pretty clearly in the character editor. which causes it to "slide" along. Doesn't apply to the run cycle. The fix is literally just changing the Cycle Speed property.
0.45 seems to be the best value. 0.50 looks slightly more accurate but it looks and sounds way too hurried for a walk cycle.

**Comment by itchyOwl** [comment]
Fixed

**Comment by Rokvach** [comment]
Tested, looks better. Moving to Done.
