### ISSUE TITLE
Add a cooldown to GUI Use

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#195]
Come to think about it - there is no cooldown for the GUI Use functionality on the HUD, you could have say, a bandage which can only be applied on another X times per second (Such as once or maybe twice) - however self-using does not have any such restriction and can simply be spammed very fast.

Could we either get the GUI restricted to a certain rate for this specific button, or have this as an XML attribute for the use function if it comes from the GUI Use?

**Comment by Regalis11** [comment]
Not needed anymore because the use button has been removed.
