### ISSUE TITLE
[Small Feature Suggestion] Change default playstyle in server creation menu to Casual

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1950]
Most people who are just creating a quick game and can't be bothered to change the playstyle are infact casual players. People who play serious are competent enough to change the playstyle to serious correctly.
Right now it's a bit difficult to tell where to actually get a serious round because many games are just players who can't be bothered to change the playstyle for some reason.

**Comment by V1kingGit** [comment]
Indeed, the playstyle changes to _serious_ as default every time you host your server, instead of remembering your last, and it can be tedious to scroll through and select yours if you do a lot of rehosts.

**Comment by Regalis11** [comment]
Changed in v0.9.7.0

**Comment by Rokvach** [comment]
Tested, working  correctly. Moving to Done.

**Comment by hubismal** [comment]
was this done in a seperate branch from the ones testers were given out? it still seems to have serious selected by default for me.

**Comment by Rokvach** [comment]
Seems like it has reverted back to Serious, might just happened during a merge. @Regalis11

**Comment by Rokvach** [comment]
Fixed, moving to Done.

**Comment by hubismal** [comment]
this is *still* not fixed as of the latest unstable build. does the latest unstable build just not have the branch merged?

**Comment by ekqvist** [comment]
It seems to have been fixed with Regalis11/Barotrauma-development@6966ca9ee which is on a branch that has not been merged yet
