### ISSUE TITLE
[Issue] [0.9.7.0] Clothing Variant Items Should Have Different Names

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1953]
Right now, clothing variant items all having the same name (eg there being three "Captains Cap"s in existence) makes things pretty messy. **You can't spawn in any of the variants since they're all named the same thing**; The game will just spawn in the first one. Despite this, the autocomplete in the console still acts like there are three variants.

Having them identically named also forces players to refer to them as "that one orange engineer suit" or "that one greyish engineer suit".

It would be ideal if they were given names like "Technical Engineer Jumpsuit" or "Belted Engineer Safetywear". Anything that still conveys what roles they're for in their description or name, while also describing what they look like.

**Comment by Ek-Videogames** [comment]
+1
It would help avoid conflicts with how the game sometimes uses item names instead of identifiers in some situations.

**Comment by danielasteljoki** [comment]
New item names (along with different starting item sets) have been implemented in a branch in the development repo.

**Comment by Rokvach** [comment]
I didn't notice the different variants having a different name, for example the security helmets all had the same name even tho they were from different variants @danielasteljoki

**Comment by danielasteljoki** [comment]
![image.png](https://images.zenhubusercontent.com/5c9240ccd06a4e6d359ee49a/b148d837-9819-4c5f-b792-d17520daac20)
They're in 'new-starting-gear' branch

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
