### ISSUE TITLE
Crash upon entering multiplayer servers

### ISSUE THREAD

**Issue by urban-rural12** [Regalis11/Barotrauma#1957]
**Description**
Upon entering multiplayer games (and sometimes in the middle of a multiplayer game) the game will freeze up and I will get an error message saying that it crashed. I can still hear the ambient noises in the back. This has happened countless times now so I am submitting a report in the hopes of it getting fixed.

**Version**
Latest version of the game upon posting (12/28/19).

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4007581/crashreport.log)

**Comment by Regalis11** [comment]
Seems to be a duplicate of #1951
