### ISSUE TITLE
[Bug] Mission markers for target remain after death

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1958]
Could be a duplicate because this is a pretty obvious and common issue, but I didn't see it anywhere.
The red mission markers for creatures (I.E. Hammerhead 246m, Swarm 689m, etc) stay after you shoot them dead. There will always be one marker left over for the last creature in a swarm, even though the other markers disappear correctly for other swarm members. For individual targets (such as hammerheads and infrasonic signals) the markers will remain afterwards. Very confusing for people trying to complete a mission, especially if you missed "the hammerhead is dead" popup.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4107d0d35bd5cc4114b0243fd312389d52a6a8a (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
