### ISSUE TITLE
[Feature Request] Forbid players from loading campaigns with different mods applied

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1959]
Self explanatory title. Campaigns that previously used different "mod loadouts" are still loadable, and this probably shouldn't be a thing assuming campaigns are eventually made more serious in the future (I assume you guys want explorable outposts to be consistent in the future, having different mods be loaded will obviously break that.)

**Comment by HalfdeadKiller** [comment]
Why not have a warning about loading an older campaign with a different mod load order? I personally don't like having hard restrictions on things, and prefer to let the game have me do stuff and then deal with the consequences myself. What if I just want to add a mod that gives some weapons I forgot to turn on when I'm halfway through a really good campaign?

**Comment by Regalis11** [comment]
Implemented a warning in https://github.com/Regalis11/Barotrauma-development/commit/e40feccecfc29078e8c0566bf132e0d8b2055f29 and https://github.com/Regalis11/Barotrauma-development/commit/1e8adcbbc9e0976d0484bb363c5b3e66fd3ebe51 (private repo).

**Comment by hubismal** [comment]
was this actually implemented? not happening in the latest unstable build.

**Comment by hubismal** [comment]
nevermind, i see it. i thought it would be like a full fledged popup, not just a tooltip.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
