### ISSUE TITLE
Fabricator/Deconstructor Ideas, Item Combination component and inconsistency issues

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#196]
All of this is based of 0.7.0.1:

Some of this is a little related to #132 perhaps but also different.

I figure its worth throwing up but I feel the fabricator system can use a few improvements in its flexibility even if not immediately used in the base game (This would still be very nice for Content mods in general):

----------------------------------------------

Condition (Item Health) based crafting:
- Minimum condition to craft with (Deconstruction or Fabrication)
- % Condition usage of items (Either consuming or leaving empty - preferably as a tag in case a mod needs an item as a refillable ingredient in crafts)
- Allow new items to have variable condition from XML config
- Allow Deconstruction to place condition-based results from an item (Such as a percentage of uranium), this may need some extra thought for configuration on XMLs.
- Allow Condition values over 100% as well as Item Quantities to make (Multi-steel usage such as 150% condition needed, as well as multiple output)

----------------------------------------------

Item Combination (New item component):
- Instead of having stacks of item counts or ever increasing container sizes, the condition can be reused to give a feel of combining items and more proportionate weights.
- new Item Component for combinable items, this component could have the relevant tags to behaviour for combining items
- Could have it self-remove if the item runs out of condition or not (Such as combining steel vs moving welding fuel from one tank to another)
- Could add other types of item that the component may combine to or weights per item at a later date, such as moving steel into 'large steel' (Just an example, not saying add a large steel).

----------------------------------------------

There is an issue where multiple items of the same type in a fabricator can potentially be consumed (It is possible for a recipe taking 1 steel and 1 uranium to take multiple of either, I have seen fuel rods eat 2 steel at times), it should only take what it requires, this doesn't seem fully consistent however.

If condition based crafting is implemented this could simply be done as loops per-ingredient needed in an item to be checked and deducted with breaks if enough is found, ensuring just the right amount of material is satisfied in requirement before removal.

----------------------------------------------

There is currently an issue (Which won't be too relevant if condition-based crafting is implemented, but is relevant in the short-term) Where crafting with empty medicals or other empty items is no different than crafting with undamaged ones, you can save 0% condition items such as Corrigodone and Ethyrosine for later crafting into re-using these spent resources.

----------------------------------------------

There is an additional issue where Deconstructors can delete any item regardless of there being any gain from it, this includes mission cargo and even diving suits. Anything and everything can effectively be "Black holed" despite the lack of any recipe gain for destroying items this way.

----------------------------------------------

Possibly Improve the slot counts from 5/5 to 8/5, 8/8, 10,5, 10/8 for fabricators, Allowing for costlier and/or more complex outcomes.

----------------------------------------------

All Artifacts give steel (This should be polycarbonate or other more useful substances given the dangers these often give, steel even rusts in water)

Camera can be deconstructed but is not a Holdable item to detach.

----------------------------------------------

Item Inconsistencies in crafting:

For these recipes in particular, First line is costs, second line is deconstruction.

Button: (Converts Steel Bar to Polycarbonate Bar)
Steel Bar, FPGA Circuit
Polycarbonate Bar, FPGA Circuit

Underwater Scooter: (The only recipe that is extremely lossy, FPGA is none-craftable)
Steel Bar, 2 Polycarbonate Bar, FPGA Circuit
Steel Bar, 1 Polycarbonate Bar, 1 Copper Bar

Battery Cell: (Creates a FPGA circuit out of Sulphuric)
Steel Bar, Copper Bar, Sulphuric Acid
Steel Bar, Copper Bar, FPGA Circuit

Fulgurium Battery Cell: (Creates a FPGA circuit out of Sulphuric)
Steel Bar, Fulgurium Bar, Sulphuric Acid
Steel Bar, Fulgurium Bar, FPGA Circuit

Flare: (These can be repaired with decon and fabrication!)
Phosphorus, Aluminium
Phosphorus, Aluminium

Stun Grenade: (left ingame on use but has no decon value)
Steel Bar, Flash Powder, Chloral Hydrate
Nothing

Incendium Grenade (left ingame on use but has no decon value)
Stun Grenade, Incendium Bar
Nothing

Oxygen Tank:
Cannot be crafted
Steel Bar

Welding Fuel Tank:
Cannot be crafted
Steel Bar

Diving Mask:
Cannot be crafted
Polycarbonate Bar

Fire Extinguisher:
Cannot be crafted
Polycarbonate Bar, Steel bar

Flashlight:
Cannot be crafted
Copper Bar, Polycarbonate Bar

Depth Charge Shell:
Cannot be crafted
2 Steel Bar

Nuclear Depth Charge Shell:
Cannot be crafted
2 Steel Bar, Uranium Bar

Revolver:
Cannot be crafted
Steel Bar, Aluminium, Polycarbonate

Stun Baton:
Cannot be crafted
Steel Bar, Polycarbonate Bar

Relay Component: (These can actually be wrenched, deconed, but not replaced)
Cannot be crafted
Steel Bar, FPGA Circuit

Items not above or below appear to have fairly consistent/normal fabrication and deconstruction recipes.

Items that have no creation/deconstruction recipes (Comprehensive List, some are pointless its more of a reference at this point):
FPGA Circuit
Diving Suit
Revolver Round
Screwdriver
Wrench
Handheld Sonar
Heat Absorber
Bandage
Stabilosine
Body Armor
Ballistic Helmet
Handcuffs
Headset
Metal Crate
Explosive Crate
Chemical Crate
Clown Mask
Clown Costume
Health Scanner HUD
Doctor's Coat
Doctor's Trousers
Captain's Cap
Captain's Jacket
Captain's Trousers
Bike Horn

**Comment by NilanthAnimosus** [comment]
Additional note - if crafting with an item like "Wire", and there are alternatives that are just recolours of the same item such as "Red Wire" and "Orange Wire" - these will not match the crafting requirements, perhaps tag based crafting could be implemented as well such as Tag: Wire.

**Comment by Crystalwarrior** [comment]
Tag-based crafting has a problem where it can't really be listed as an ingredient without either listing *everything* with that tag or passing a "base item".

**Comment by NilanthAnimosus** [comment]
Makes sense. the only alternative is to add something to the XML of the items themselves like what material it counts as in crafting or such, Honestly not too sure how to go about it but its such a small issue you can more or less safely ignore it for now.

**Comment by NilanthAnimosus** [comment]
I'm not sure if this needs to stay open or still contains a few good ideas as a lot of this has been implemented at this point.

Although there are still items that cannot be crafted, or have unusual to no returns on deconstructing them with balance issues etc, I believe there was an issue for this.

I suppose the ability to destroy mission cargo (And I think you can deconstruct a container that contains items which in of itself seems odd). perhaps one or two other small points, but i feel this could be closed at this point.
