### ISSUE TITLE
[Feature Request] [0.9.7.0] Give docking port icon a more accurate shape

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1960]
it can be pretty misleading to see the docking port "icon" (which is just a green rectangle/line) as a new player because it doesn't really give a good idea of what the dockin port's shape is actually like. It would be extremely helpful for everyone involved if the docking port icon accurately displayed the collisions of the docking port.
![dockports](https://user-images.githubusercontent.com/47284081/71601155-e4bc2880-2b17-11ea-956c-d0cd78036fbd.png)

**Comment by Regalis11** [comment]
The docking ports don't actually have collisions. It is possible to slide them the way you described as long as the sub doesn't have any extra walls/colliders next to the ports that would prevent it.
