### ISSUE TITLE
[Feature Request] [0.9.7.0] Force server hosts to check against workshop mods

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1961]
Before hosting, it would be ideal to force server hosts to check if their game is up to date by using a hash or something to compare the content packages the host has with the ones available on workshop. This has been the biggest problem so far, hosts having weird non-workshop-identical content packages that cause confusing mismatches when the server browser compares hashes.

**Comment by hubismal** [comment]
And also give clients the option to redownload from workshop if possible. Why do workshop downloads even corrupt in the first place???

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1722](https://github.com/Regalis11/Barotrauma-development/issues/1722) via [**ZenHub**](https://www.zenhub.com/)
