### ISSUE TITLE
[Bug] [Code] [Dev Branch] Plasma cutters with repairthroughholes="true" can't mine ores!

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#1962]
**v0.9.7.0**

### Issue:
Plasma cutter beams no longer seem to interact with ores in the latest development build.
It is impossible to mine any ores.

**Steps to reproduce:**

- Load up any mission and grab a plasma cutter
- Jump outside the sub and try to cut ores

**Additional info:** (Important!)
This appears to be a result of the new feature `repairthroughholes="true"` as this does not affect the plasma cutters in the current stable version without this component. 

In addition; if I overwrite the plasma cutter with the same exact code but `repairthroughholes` removed it acts normally once again.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c7d1a01a06f2cf6307f812cadaad5199a5d5890 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
