### ISSUE TITLE
Hitscan projectiles don't work inside ruins.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#1963]
**v0.9.6.0**
(Bug persists on dev branch v0.9.7.0)

### Issue:
All hitscan-projectile weapons (Revolver, SMG, Shotgun) hit detection becomes unreliable/unusable when inside the hull volume of an alien ruin.

**Steps to reproduce:**

- Go inside a randomly generated ruin or artifact mission ruin
- Try to shoot a monster or another player with any of the weapons mentioned above

**Additional info:**
Projectiles only seem to connect if the barrel of the weapon is directly on the character you hit.

The 'spark' effects associated with these projectiles appears at the barrel of the gun, which implies that something must be stopping the projectile's hit-detection before it can go any further.

This happens regardless of if the room is filled with water or not.
(There is no issue of firing weapons outside the submarine, inside outposts, inside PVP combat mission submarines, or any other extraneous hull conditions. Only ruins as far as I can tell)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b249c63231a219c9774bf948c046cb5730449678 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
