### ISSUE TITLE
[Feature Request] Make messagebox command work in multiplayer

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1964]
Would be extremely nice if `messagebox`'s functionality were extended to work in multiplayer. a way to send a message to all players, or just one.

**Comment by NilanthAnimosus** [comment]
If this is going to be a thing, please could there also be support for rudimentary Icons much like the traitor system's message box usage, I know they currently use loaded icons via a prefab and not an identifier/preset loaded set of icons - but it is already supported by message box's to have them, Though a server sending these (IE. modded) cannot add or invoke an icon clientside.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1723](https://github.com/Regalis11/Barotrauma-development/issues/1723) via [**ZenHub**](https://www.zenhub.com/)
