### ISSUE TITLE
[Issue] Traitors are assigned to one-man teams

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1965]
Obviously the one person can just choose not to do the objectives that harm themselves, but self sabotoge obviously doesn't make much sense.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/25c7416c7418d29707b11d5bc87bd051245748ab (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
