### ISSUE TITLE
[Bug] [0.9.6.0] Docking port docks on the wrong side in certain applications.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#1966]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In campaign, after the first mission, subsequent missions will have shuttle docked on the wrong side of the docking port. This seems to happen when the docking port is recessed into the main body of the submarine.

**Steps To Reproduce**
Have a docking port inside a recessed area of the submarine with shuttle attached. Start campaign, play through the first mission. Select the next mission and inspect the docking port.

**Version**
Windows 1903
Barotrauma 0.9.6.0

**Additional information**
Imgur links showing the issue, it's easier shown than explained in words.
https://i.imgur.com/BsylDpX.png
https://i.imgur.com/FvGXxZV.png

Attached is a zip of the submarines used in testing, along with the campaign save files the bug happened on for those submarines.
[Docking Port Bug.zip](https://github.com/Regalis11/Barotrauma/files/4014428/Docking.Port.Bug.zip)

**Comment by HalfdeadKiller** [comment]
By sheer luck, one of my friends found out that the door in the docking port subassembly seemed to be an old version that required a welder to fix. Replacing that door fixed the bug for some reason. I don't understand why.

**Comment by Udrakan** [comment]
It's enough to just Retry the mission immediately after you spawn. The bug will appear. It is well noticable on Kastrull drone.
STR
-New singleplayer campaign, Kastrull sub
-Run to the drone, see what it looks like (top pic situation)
-Esc, Retry mission
-Run to the drone, see what it looks like (bot pic situation)
![unknown](https://user-images.githubusercontent.com/59519434/71773802-14c65a00-2f64-11ea-8321-2d1d386dc913.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9e6faa182fc41b4d0b433dc8f00f0d1b51594ae6 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
