### ISSUE TITLE
Make the CPR damage fully moddable

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#1967]
The affliction applied by CPR is currently hardcoded. Maybe the affliction should be externalized and be part of the CPRSettings so modders can customize CPR even further. :p

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/c4f4eda105152aacf1167a4cc3eb89e365fd44db (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
