### ISSUE TITLE
[Bug] First bullet from a firearm that uses a magazine/clip does no damage/does nothing at all

### ISSUE THREAD

**Issue by nakedcrook** [Regalis11/Barotrauma#1968]
**Description**
This has been verified in Vanilla, with no mods enabled, on the most recent version of BT. Any gun that is fed ammo via a magazine/clip (tested with the SMG) has the odd behavior of the first bullet doing absolutely nothing.

**Steps To Reproduce**
1. Locate a magazine fed weapon, namely, the SMG
2. Load an SMG magazine into the SMG
3. Locate a fellow crewmember and click the left mouse button just enough to only fire a single shot. You will notice that there is no damage done to the crew member. You can also fire the first shot at a wall, and you will notice that no particle effect displays.
4. All subsequent shots will have a noticeable and immediate effect; either doing damage to a crewmember, or generating the appropriate particles.

EXTRA INFO:

If you have two used clips, and combine them to create a clip that is back to 100% condition (full) this bug does not reproduce and the first shot has an immediate effect (it does damage and generates particles)

**Version**
BT version 0.9.6.0

**Comment by Ek-Videogames** [comment]
_(I don't know if this has any extraneous side-effects, but it seems to work fine to just spawn bullets inside the magazine with an "always" condition and a conditional if the item is not broken. Would a dev care to weight in on this?)_

**Comment by EdusFF** [comment]
Fixed SMG in: https://github.com/Regalis11/Barotrauma-development/commit/b4af9ebcbfb10cc642c2f632f055211b615b7a6a

**Comment by Rokvach** [comment]
No issues, closing.
