### ISSUE TITLE
[Bug] [0.9.6.0] Remora depth charge tube is not linked to loader

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#1969]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Remora depth charge tube is not linked to depth charge loader.
(discord Senhor pointed me to this bug)

**Steps To Reproduce**
Open Remora in editor and behold - no link between the loader and tube.
Because of this, in mission depth charge doesn't respond to terminal (tested).

**Version**
Windows 0.9.6.0

**Additional information**
Just link them, no biggie.
![remora depth charge](https://user-images.githubusercontent.com/59519434/71774269-3592ad80-2f6c-11ea-92ee-0252d96e6349.png)

**Comment by ezjamsen** [comment]
Fixed

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
