### ISSUE TITLE
Dragging tiny monsters (crawlers/mantis), monster inventories, etc.

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#197]
as Chiko suggested:

> Chemicals are currently really limited so being able to make cures for specific effects could really expand the "medical" part of the game.
> 
> Also, something that I would really like added in the game would be more creature related xml things. Stuff like being able to add more character files in a single monster event so that more than one type of monster spawns when the event is triggered. Or inventory for monsters so players can get items from their corpses.
> 
> Another thing that would be interesting would be some kind of Shipwreck random event. It could work by loading a submarine file instead of a monster xml file and then destroy part of the hull in random locations so it sinks. Or maybe shipwrecks could be created in the submarine editor and be specified like such with a checkbox like how we do with shuttles.

also, personally, I'd love to implement a some sort of conditional/if-statement/switch system and add tags for status effects so you could, for example, make a chemical that cures or counteracts poisons like morbusine by checking their tag.

Being able to create items from the status effects could be stellar too, e.g. onuse -> new bikehorn, or when shooting, create a new projectile itemprefab and decrease the condition of whatever's inside for things like pistols. In addition to this it should be possible to delete itself or target - so, projectile onImpact -> self -> delete.

**Comment by Regalis11** [comment]
Added in 7bfea70, 050b1a8 & cd8bd79
