### ISSUE TITLE
My Ideas of Expanding The Game's Plot- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1971]
[*] Humanity had already achieved the state of being biologically immortal long ago.

[*] A brillaint genetic engineering team of doctors had invented a way for humans to have no need for sleep or eating at the cost of that they need more oxygen to function, explaining faster rate of oxygen deprivation inside of rooms than in real life. They do also suffer no fatigue, explaining unlimited sprint.

[*] A device was planted into the center of the moon to change the force of the moon's gravity field. It caused the water pressure to suddenly rise and now it is inaccessible. The robot that planted the device got crushed and most of the passive underwater creatures became extinct.

[*] NASA has no idea that humans on europa teached themselves to live without food or sleep. The leader took an account for that and decided to make he's secretary sometimes answer the call from earth for him, lying that the leader was having a nap while the call was taken and that he had to wait before he would wake up, explaining a few hour delay of receiving an answer phone by NASA. He even ordered to keep gardens functional to send NASA movies with workers consuming food.

[*] A psychotic leader of the coalition secretly makes flawful submarines for he's own workers so being biologically immortal won't be too boring for him. He tells everyone that this is being caused by water pressure outside and that's why devices break like it when submarine is activated.

[*] Europa became pulled by Jupiter's gravity stronger after activating the device. The coalition is not going to turn it of as no one enjoys low gravity. The leader is also not mentioning at all collision with Jupiter in the future and plans to escape the moon if things would go wrong.

[*] Coalition's best ranking engineers are being blackmailed not to reveal a secret formula for a correctly working submarine devices without intentional, random malfunctions. Same thing with other personel for other subjects.

[*] About 90% of the coalition secretly suspects that there is something wrong with they're leader. Those who publically say a lot of things against him later die in mysterious circumstances, most often during the april fool's day so the leader indirectly tells everyone not to mess with him. 

[*] Renegades are terrorists who simply enjoy selling drugs and guns to regular citizens for personal benefit. After the leader decided that being biologically immortal is boring he decided to improve renegades by giving them submarines.

[*] The coalition claims that fruits are for those who are missing eating regular food. This is actually true.

[*] The clown consortium was made two weeks after the first flawed fruits were eaten during experiments. Long term observation proven that the patients became sociopathic and the side effects of lacking free will wre gone. Mental illnesses done by new genetically modified apples were impossible to cure. The clowns act as entertainment to the entire Europa. The formula for "psycho fruits" became top secret after that.

[*] The first wife of coalition's leader (who worked as a scientist) after believing that those fruits are capable of weakening the will of it's host decided to give a sample of it to her husband in secret so she would blackmail him for her personal needs that will remain unknown to the player. She didn't knew that one week after giving it the victim will became mentally ill for the rest of it's existance and the lack of free will would vanish. When it was too late to realize it she tried to join renegades in order to find safety but died during the storm on they're hideout.

[*] After doing all the things against the coalition he's first wife commited the leader made a speech in which he explained that NASA cannot be trusted anymore and declared himself an autocratic ruler of the Coalition. The speech was so charismatic that he managed to bring the coalition morally back in time (Hitler-like style). The scientists had noticed that the leader could had been poisoned with psycho fruits judging by the time he ordered he's troops to chase he's wife but were unable to do anything about it until a wonderful cure against any types of mental illnesses was developed. The leader however noticed the existance of cure and did everything he could not to get cured.

[*] The leader of coalition became paranoid after he realized that the woman he loved was the one who wanted to use him to her own desires against he's will. He send he's two sons and a daughter far away from the central linea where he resided so they wouldn't assasinate him if they wanted to.

[*] The second and current wife of the leader is he's former high school buddy who also joined the military whre she became a captain for her merits. She was promoted to coalition's security chief through nepotism after the marriage. She is known to be very strict and sometimes merciless.

**Comment by Regalis11** [comment]
Thanks for taking the time to write this, it was an interesting read! However, we already have the broad strokes of the backstory pretty well planned (although not included in the game yet). Even though your ideas have some similarities to ours, we're planning on going on a slightly different direction. ;)

**Comment by rico6822** [comment]
> 
> 
> Thanks for taking the time to write this, it was an interesting read! However, we already have the broad strokes of the backstory pretty well planned (although not included in the game yet). Even though your ideas have some similarities to ours, we're planning on going on a slightly different direction. ;)

Great, does it mean some of my tropes will be included?

**Comment by Regalis11** [comment]
Not exactly in this form, but some of your ideas have similarities to the plot we have planned.
