### ISSUE TITLE
[Bug] Kastrull – Pump in command-room never disables.

### ISSUE THREAD

**Issue by roidal** [Regalis11/Barotrauma#1973]
After the command-room get flooded for the first time the pump doesn't disable anymore, since the sensor keeps sending "1" even if all water (reachable by the pump) was removed.

**Comment by ezjamsen** [comment]
Could not reproduce, regardless, whole pump setup has been replaced with a simpler system.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
