### ISSUE TITLE
[Bug] flipx command desyncs

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1974]
not sure how urgent this is since this is just a command online not really meant to be used online.

at least for hosts online, flipx command desyncs the host client pretty bad. the client appears to have the sub flipped but the game (aka server logic) acts like the sub is still normally facing forward meaning the command registers clientside but not hostside.
you could just disable this outright, but honestly it would be much nicer if you gave hosts a little more freedom with round commands so that more interesting sandboxy stuff could be performed in "something different" servers.

**Comment by hubismal** [comment]
note: it looks like this is just because flipx is in BarotraumaClient's DebugConsole.cs and not in BarotraumaServer's or BarotraumaShared's.

**Comment by NilanthAnimosus** [comment]
In legacy this was an ill-wise command to use, A single flip is usually fine, however repeated flipping resulted in very minor accuracy errors which, given enough flips, effectively causes walls and entities inside the submarine to slowly move inwards towards the centre, compacting the hull and shifting doors/interior and exterior walls inwards on the X axis.

I once tried spamming the command before the separation of the code to test it out. I feel (In its current state) its a very unusual command to allow in a server in general - but may be worth at least having synced to the client despite its previous issues if they are still there.

**Comment by Regalis11** [comment]
The flipx command can't be used in multiplayer anymore in the private repository.

While I could see there being some use for the command in multiplayer, making it work reliably in multiplayer and fixing the issue mentioned by Nilanth (which is caused by floating point round errors) would probably be a bit too much trouble for such a niche feature.
