### ISSUE TITLE
Feature Request [code]: Mirror which 'direction' a door opens

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#1975]
Ability in editor (and mods) to have hatches open to the left or right, and doors open upwards or downwards.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1724](https://github.com/Regalis11/Barotrauma-development/issues/1724) via [**ZenHub**](https://www.zenhub.com/)
