### ISSUE TITLE
Little to None Vigor from Hyperzine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#1978]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When injecting Hyperzine, Vigor shows up for a split second, and disappears completely.

**Steps To Reproduce**
Wear Health Scanner HUD and inject anyone with Hyperzine to observe the buff.

**Version**
0.9.6

**Additional information**
This makes keeping Anabolic Steroids and Methamphetamine seperate better than crafting them into Hyperzine.

**Comment by Regalis11** [comment]
If I'm not mistaken, hyperzine is not supposed to give any Vigor, rather it gives you Hyperactivity for one minute. @danielasteljoki @ezjamsen ?

**Comment by danielasteljoki** [comment]
The issue was that vigor wears out faster than it's gained from Hyperzine. Fixed in ddd151d in dev repo.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
