### ISSUE TITLE
[Bug] netstat debug-screen broken

### ISSUE THREAD

**Issue by roidal** [Regalis11/Barotrauma#1979]
In the actual version the netstats debug-screen doesn't show any values other than 0.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d6e193abdc5dd7679b336309258baa4f027ce80a

**Comment by Rokvach** [comment]
Should netstats everything be at 0 for the host? @Regalis11

**Comment by Regalis11** [comment]
If there's no-one else connected to the server, everything should be 0. The client hosting the server doesn't communicate with the server over the network, so those messages aren't included in the statistics.

**Comment by Rokvach** [comment]
No issues, closing.
