### ISSUE TITLE
[0.9.7.0] Linux clients and Windows clients have different content packages

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1981]
So this makes them unable to join eachother.
~~in the .net core update linux clients were given new executables just called `Barotrauma` and `DedicatedServer` respectively. I believe that the Vanilla 0.9.xml for windows is different than the new one for linux, since windows probably has the "executable" tag assigned to "Barotrauma.exe" while linux just has it assigned to "Barotrauma". this is just a suspicion though.~~
this is all wrong, lel, but there are still occasional vanilla 0.9 content package mismatches between users for no discernable reason. verifying files doesn't help.

**Comment by jamiebidelia** [comment]
Please confirm this?  I am playing on Ubuntu 18.04.03 and am able to join Windows hosts and play with other windows clients.

**Comment by rico6822** [comment]
> 
> 
> Please confirm this? I am playing on Ubuntu 18.04.03 and am able to join Windows hosts and play with other windows clients.

If it is true than hubismal's theory is being invalid.

**Comment by hubismal** [comment]
> Please confirm this? I am playing on Ubuntu 18.04.03 and am able to join Windows hosts and play with other windows clients.

are you using 0.9.7.0?

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7db7854eeebd3f5f44efebdcc62f079fae33f8bf (private repo)

**Comment by Rokvach** [comment]
Confirmed working, moving to Done.
