### ISSUE TITLE
Replace Main Menu Theme With Submarine Editor Theme- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1984]
I heard it on youtube and decided that it is truly a good background ambience that sound friendlier than in case of main menu's theme. Replacing it would help the players relax more easily while waiting for a round to start.

Maybe those are all just my personal preferences.

Potential bug to avoid: Entering submarine editor shouldn't reset this theme and cause it to play from start. Same comes with returning to main menu.

**Comment by hubismal** [comment]
I disagree that it should replace the main menu theme. The main menu theme is fine for the main menu and the server browser. What I think is the real grating effect of the main menu theme is hearing it every time you go back to the lobby in a multiplayer round (which is 90% of the time it's heard anyway). More music is still being introduced, so I'm sure something will be composed for lobbies.

I do agree that it should start from a different "movement" in the symphony every time you open the editor after the first.

**Comment by Regalis11** [comment]
I disagree with this as well, I think we'll keep the main menu theme in the main menu.
