### ISSUE TITLE
Feature Request - Toggling free heals on End Round OFF.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#1985]
**Description**
I would like to ask for the ability to be able to turn off the free healing that the entire crew gets when ending the round in campaign.

**Additional information**
In the current state of the game, there are not enough threats that deals damage to players that aren't players themselves. Even then, when they do take damage, the damages are generally too great to be able to cure in time most of the times. Small damage gets left alone because players know they can heal it off when docking to any stations. My Medbay cabinets have been stocked to the brim, and are constantly gaining more supplies. There is almost no usage of those supplies. When there is, players generally overheal themselves because they can't stand not being at 100% HP and wastes the medical items when the station is just 100m away.

**Comment by Regalis11** [comment]
Healing characters between rounds has been removed in https://github.com/Regalis11/Barotrauma-development/tree/feature/campaign-groundwork now. At the moment it's not optional though: the characters will always keep their afflictions between campaign rounds unless you heal them.

Moving to Review/QA

**Comment by ekqvist** [comment]
I added the Waiting label to this for now, as this should probably be kept open until the branch is at least merged into dev

**Comment by Rokvach** [comment]
No issues, closing.
