### ISSUE TITLE
Spawning a human without specific job crashes the game

### ISSUE THREAD

**Issue by Weebyxanide** [Regalis11/Barotrauma#1989]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to spawn a human with an unspecified job causes a crash. Specifying their job, as in "spawn assistant cursor", does not.

**Steps To Reproduce**
In a singleplayer game (untested with multiplayer), use the command "spawn human inside".

**Version**
0.9.7.0, Windows

**Additional information**
Untested in multiplayer, but confirmed it happens in the tutorial and a campaign.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4051430/crashreport.log)

**Comment by ekqvist** [comment]
Fixed with Regalis11/Barotrauma-development@628e528 (private repo)

**Comment by Rokvach** [comment]
Tested, working, moving to Done.
