### ISSUE TITLE
Submarines can enter ruins (Feature or bug? + background depth issues)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#199]
Submarines (And their linked shuttles / respawn shuttles) can enter ruins if all the walls are damaged enough to be passable, this may or may not be considered a cool feature or a bug - but there are a number of visual artifacts and perhaps bugs that could occur from this that may need checking.

- The background wall of a ruin tends to have a higher depth (Or due to draw order) than submarine backgrounds.
- what happens if a player swims outside of the submarine and welds an intersecting wall?
- Additionally can the repairtool.cs raycasts actually hit the ruin walls from inside the submarine (IE. welding a ruin wall halfway into a shuttle or submarine) as this could cause issues.

I think this may either need preventing or looking into potential unusual behaviour not likely tested for, there could be a number of bugs and issues regarding this.

Although not my image this is how it more or less looks:
http://puu.sh/yMiHP/1ac5d52c14.png

**Comment by Crystalwarrior** [comment]
holy shit this is actually really cool
I kinda want this to have its kinks ironed out and become a legit strategy
