### ISSUE TITLE
[Issue] showseed doesn't work

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1990]
Self explanatory. Happens online, not really sure what else there is to say. nothing appears in the console.

**Comment by ekqvist** [comment]
This seems to be strictly a multiplayer issue. It works fine in singleplayer. And in multiplayer the level seed is logged in the window which is automatically opened when starting a server. However, it is not logged in the in-game debug console, like in singleplayer, or in the in-game server log.

**Comment by Regalis11** [comment]
>And in multiplayer the level seed is logged in the window which is automatically opened when starting a server.

Do note that the server console only opens in debug builds, in release builds it's hidden. But in any case, I think we should make the command show the seed to the client who executes the command.

**Comment by ekqvist** [comment]
Should be fixed with Regalis11/Barotrauma-development@cecce7f

**Comment by hubismal** [comment]
was this implemented as a "clientside" command that doesn't require permissions (like fpscounter)? it doesn't seem to be something that should really be restricted from a client. just curious.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.

**Comment by ekqvist** [comment]
@hubismal The command is still relayed to the server, as before, so the server knows a client is executing the command. However, now we also print the level seed for the client when they execute the command.
