### ISSUE TITLE
players can use other players names in lobby

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1991]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At first they were playing it off as a bug, then I thought perhaps its special characters, but then I saw "X has changed their name to Nilanth" which was already taken by myself.

**Steps To Reproduce**
Unknown, name was changed in-lobby from another name but specific characters (If different) are not known.

**Version**
0.9.6.0

**Additional information**
![image](https://user-images.githubusercontent.com/29177976/72248022-15a75d80-35ee-11ea-8a48-b425a9bba2d4.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/126e363

**Comment by Rokvach** [comment]
Couldn't spot any issues, closing.
