### ISSUE TITLE
Darker Aspects of The Lore- Feature Requests

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#1992]
Barotrauma is a game without any interesting plot features, it is a game designed for players who just want to relax however some video games nowadays also gain popularity through conspiracy theories, urban legends but most importantly deep lore within them. I wander if they could be implemented into the game somehow. Here's my idea for an example:

**Moloch's Lullaby:**
This is the story about why Molochs are being named Molochs. "Moloch's Lullaby" is a name of an very infamous incident that shocked many humans from the entire world to the bone. During the first days of Europa's exploration the security measures against human stupidity were poor. Those were the times before Renegades were not yet present or cities were being established. It was being assumed that all the crews were going to be made out of strict professionals who know they're place. An experimental scouting shuttle named "The Blind Carp" was on a special testing mission to check if a submarine that lacks windows is capable of descending deeper into the ocean without having it's hull being cracked by water pressure. The same shuttle didn't came back from it's mission in a discussed amount of time. While exploring the area in search for it they eventually found it ruined lying on the ocean's floor about 1760 meters underwater. The black box recording had revealed a shocking transcript between 2 crew members who were assistant Wanda Smith and captain Hans Smith.

Hans Smith: Thank fuck, we can finally rest from those losers.
Wanda Smith: They are just like you.
Hans Smith: Don't!
Wanda Smith: What?
Hans Smith: We aren't even halfway through.
Wanda Smith: My preg-
Hans Smith: Shut up! It's gonna...
(*there is silence for few seconds*)
Hans Smith: Good. 
(*there is silence for about 10 seconds*)
Hans Smith: Springcharger!
(*confirmed sound of a moloch*)
Wanda Smith: (*yelling in pain*)
Hans Smith: Endure this!
(*Moloch most likely gets temporarily outrunned*)
Hans Smith: I put on autpilot! (*enables autopilot*)
Wanda Smith: (*various sounds of suffering*)
Hans Smith: Our child! Breath easily!
Wanda Smith: (*fails to tame agony*)
Hans Smith: Our child! Breath easily!
(*Moloch is heard again*)
Hans Smith: I must take control! Do you hear me?! (*turns off autopilot and takes manual control*)
(*Moloch is being heard louder*)
Hans Smith: Wrong, wrong, god, fuck of!
(*an extremely loud sound of collision is being heard before recording does an emergency cut*)

Almost everyone who heard this recording agree that Wanda Smith was being pregnant at the time of the experiment which was heavily prohibited. No one had expected the couple to act so extremely irresponsibly. The recording from the black box had turned into the evidence of a national tragedy. The bodies of the couple and the infant were never found. Experts claim that they were most likely eaten by sea creatures such as crawlers. 

The coalition had decided to avenge the deceased infant who was put into this situation agaisnt it's will by killing the same moloch who crashed the shuttle but the creature was never found. One of the investigators had refered to that springcharger (former name of a moloch) as "Moloch", biblical god of child sacrifice. The Coalition may not had found the beast but they found alternate solution to pay tribute to a deceased infant: Springchargers were to be mandatorily called Molochs from that moment onwards to remind of the tragedy more easily. Security officers began to be hired on boards of regular submarines by some captains to prevent similair incidents from occuring. They are being given most basic medical training. 

Further research on molochs confirmed that all of they're species are being in fact female. A rude politician who offered to change names of molochs to some another because of that discovery received a social backlash and lose a lot of support in the upcoming election for the ministry of scientific research.

Some people believe that the same moloch who crashed the shuttle had descended into the abyss and never returned but that last part is just a legend.

**Comment by hubismal** [comment]
this game probably doesn't have any plot points because plot and story are way out of the focus of first just making sure this game doesn't hiccup and crash. you might want to write this down somewhere, in a google doc or something, and not in a issue tracker where it will inviteably get closed and forgotten about the next time there is a mass feature request closure.

**Comment by rico6822** [comment]
> 
> 
> this game probably doesn't have any plot points because plot and story are way out of the focus of first just making sure this game doesn't hiccup and crash. you might want to write this down somewhere, in a google doc or something, and not in a issue tracker where it will inviteably get closed and forgotten about the next time there is a mass feature request closure.

Ok, but I have a question: Was that an interesting read?

**Comment by Regalis11** [comment]
> this game probably doesn't have any plot points because plot and story are way out of the focus of first just making sure this game doesn't hiccup and crash

Pretty much this. The lack of plot points is not a design choice; we've only just recently started moving into expanding the single player campaign (and along with it, a background story).

This is definitely an interesting idea on how they might've ended up giving such a weird name to the molochs. But still, I don't think the issue tracker is an appropriate place for feature requests such as this. While we allow _some_ very specific feature requests to stay here (despite it being intended for bug reports), broad ideas like this don't quite fit the format of the tracker - it's hard to determine or test whether "darker aspects of the lore" has been implemented or not. So please post this kind of ideas to the forums or Discord. Even if you might not always get a response from a dev, we do read everything that goes on on both!

**Comment by rico6822** [comment]
> 
> 
> > this game probably doesn't have any plot points because plot and story are way out of the focus of first just making sure this game doesn't hiccup and crash
> 
> Pretty much this. The lack of plot points is not a design choice; we've only just recently started moving into expanding the single player campaign (and along with it, a background story).
> 
> This is definitely an interesting idea on how they might've ended up giving such a weird name to the molochs. But still, I don't think the issue tracker is an appropriate place for feature requests such as this. While we allow _some_ very specific feature requests to stay here (despite it being intended for bug reports), broad ideas like this don't quite fit the format of the tracker - it's hard to determine or test whether "darker aspects of the lore" has been implemented or not. So please post this kind of ideas to the forums or Discord. Even if you might not always get a response from a dev, we do read everything that goes on on both!

Understood.
