### ISSUE TITLE
[Feature Request] [0.9.7.0] One-Click Join Modded Servers

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1996]
Another feature request. I'm sure you don't have enough of them, so I made you another. 

The new mod hotloading is cool but it's still kind of a drag to have to go to the settings and enable all the ones that need to be enabled. it gets really tiring to navigate back to the settings menu and reapply everything every time.

Basically I think this should be streamlined so that people aren't too intimidated by modded servers. A confirmation screen should pop up and basically say "hey this is a modded server. these are the mods used. wanna download and enable them?" and then the user can confirm or deny. If it's something the hotloading can't handle, the game can restart automatically using the same feature that joins you into a server once as it starts (from the steam Join Lobby implementation).

just an idea, not high prio.

**Comment by hubismal** [comment]
now that hash calculations have (apparently) been made more accurate and there aren't inconsistencies between linux and windows, i would also like to request that if something like this is implemented (it really should, else there's honestly not much point in the whole modding rework), the server browser should offer to wipe and redownload the package from the workshop if the client has a package with an identical workshop link to the host's with a mismatching md5 hash. really tired of these constant package mismatches and they'd probably hurt usability.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1728](https://github.com/Regalis11/Barotrauma-development/issues/1728) via [**ZenHub**](https://www.zenhub.com/)
