### ISSUE TITLE
[Issue?] [Feature Request?] [Hotloading] Display "Applying Mods" message when applying mods

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1998]
small issue/feature request, the game currently just freezes when it's applying mods. when it applies bigger mods, like BTE, it takes a pretty long time (around 10 seconds for me). It would be nice if the game displayed a dialogue box that just said "Applying..." so that users don't get freaked out by the freeze.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1729](https://github.com/Regalis11/Barotrauma-development/issues/1729) via [**ZenHub**](https://www.zenhub.com/)
