### ISSUE TITLE
[Bug] [Modding] <Override> UIStyle doesn't work

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1999]
Get a strange error when trying to override styles, it would seem the UIStyles tag in filelist.xml doesn't work with overriding despite the game telling you to use a style override tag when it detects multiple uistyles.

**Comment by Regalis11** [comment]
@juanjp600 Addresses in https://github.com/Regalis11/Barotrauma-development/pull/1672?

**Comment by Regalis11** [comment]
@juanjp600 what's the status on this?

**Comment by juanjp600** [comment]
Haven't been able to replicate this on current dev. @hubismal Is this still a thing on your end?
