### ISSUE TITLE
Nitroglycerin deals no damage to players & creatures

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2000]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Nitroglycerin deals no damage to players & creatures when thrown and exploded. It still deals damages to walls though.

**Steps To Reproduce**
Throw Nitroglycerin at anyone or aliens.

**Version**
0.9.6

**Additional information**
N/A

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6adde4

**Comment by Rokvach** [comment]
No issues, closing.
