### ISSUE TITLE
Problems when joining a campaign server

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2001]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not quite sure how to explain it, Most of the lobby information was missing (Submarines, description, name, etc). Before this mind you I had tried to join and had a steam authentication error (I was signed in on steam and it was working chat wise etc) so I restarted the game, joining again and I got this couplied with perpetually downloading the save file:

![image](https://user-images.githubusercontent.com/29177976/72513741-58af3e00-3845-11ea-93c3-ce35bb3633f1.png)

It took around 3 joins to finally join the server and show the submarine list and such.
There was also a small amount of console output regarding the save file, I have lost the console output yet it looked like it was stating not having been initialized issues with the save transfer.

**Steps To Reproduce**
Unknown - joined as client and do not have server list.

**Version**
0.9.6.0
Windows 7 64bit

**Comment by BlueTheKing** [comment]
Same issue, same specs, happens randomly on mission gamemodes too.

**Comment by Regalis11** [comment]
Most likely the same issue as https://github.com/Regalis11/Barotrauma/issues/4137, closing
