### ISSUE TITLE
[Feature Request] [Balance] Add single-limb damage for welders & cutters

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2007]
Add increased single-limb damage to welding tools and plasma cutters, rather than applying a small amount of damage to every limb.

**Additional info:**
To my knowledge a bug caused by the implementation of the new medical system in steam release mean't that the full amount of welder damage was being applied to every limb of a creature, causing damage from welders to be multiplied by the amount of limbs a creature had. Damage from welders was greatly reduced to compensate for this.

Because it is now possible to target limbs using <RepairTool/> status effects, they can be tweaked to only damage the limb they hit.
`      <StatusEffect type="OnUse" target="Limb">
        <Conditional EntityType="eq Limb"/>
        <Affliction identifier="burn" amount="0.5" />
      </StatusEffect>`

**Comment by Regalis11** [comment]
Ping @danielasteljoki

**Comment by Rokvach** [comment]
No issues, closing.
