### ISSUE TITLE
[UI] [Feature Request] Add Sub Filter to Lobby

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2008]
saw the ui for the server lobby rework. looks pretty good so far, but one thing it could use (and has been needing) is a search filter for submarines. Some people have 50ish subs and they insist on finding the right one. They're also generally out of alphabetical order so you can't just scroll to the right letter.

**Comment by Regalis11** [comment]
Moved to the private repo https://github.com/Regalis11/Barotrauma-development/issues/1731
