### ISSUE TITLE
[Feature Request] Show variant "names", loadout descriptions on mouseover

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2022]
each <ItemSet> should have a "name" property given to it that can be seen on hover-tooltip in the server lobby when mousing over the variants (gunner, riot enforcer, veteran, coalition admiral, etc). They should probably also have a brief description of the starting gear. Now that variations have different loadouts, people should actually know what the h*ck they're getting when they choose a variant since they're not just fancy visual changes anymore.

**Comment by ekqvist** [comment]
We do intend to convey the information to the players better in the future. At the moment, you can at least see the item list in the lobby, but we intend to improve this.

**Comment by Regalis11** [comment]
Implemented in the dev branch

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
