### ISSUE TITLE
[Bug] [Modding] ParticleEmitter "flipped" over x axis for turret.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2023]
when using a particle-emitter on a turret, the direction of the particle is mysteriously flipped. I am trying to shoot a particle until it hits a wall (mostly just for show) that originates from a turret. using `copyentityangle=true` with a turret only seems to work for "static" particles (particles without a velocity) so I'm leaving that out. The result is that particles fire in an "opposite" direction than intended as though the turret rotation were mirrored.
![2020-01-20-041736_1366x768_scrot](https://user-images.githubusercontent.com/47284081/72748869-0724ed00-3b7e-11ea-8c06-b9e3db4f8b46.png)
![2020-01-20-041729_1366x768_scrot](https://user-images.githubusercontent.com/47284081/72748870-0724ed00-3b7e-11ea-9566-532c0f12b65d.png)
nilanth found a snippet of code that seems to address this for the lightcomponents on the turrets...?
```
                if (lightComponent != null) 
                {
                    lightComponent.Parent = null;
                    lightComponent.Rotation = rotation;
                    lightComponent.Light.Rotation = -rotation;
                }
```
it would seem that an identical snippet of code with particleEmitter might do the trick.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1a61741bbd0ea1fe70e496415eba05623817e59 (private repo)

**Comment by hubismal** [comment]
confirmed working

**Comment by Rokvach** [comment]
Moving to Done.
