### ISSUE TITLE
Clients disconnecting with an "entity not found" error in multiplayer

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2025]
https://trello.com/c/jw4XTxUA/258-players-disconnecting-with-an-entity-not-found-error-in-multiplayer

This issue can occur in the multiplayer mode if the server for example assigns some entity (item, structure) a different ID number than a client. If the entity has a different/incorrect ID client-side, the client will fail to read network events from the server and disconnect. It can also happen if the client, for some reason, receives an event for an entity that has already been removed.

There are several potential causes for this issue, some of which we have fixed, but it can still occur in some cases.

**Comment by Regalis11** [comment]
Found and fixed another bug that was causing this error: https://github.com/Regalis11/Barotrauma-development/commit/8df6a21ea66a2daf85d52cc843384b349769ef1b (private repo).

Can be reproduced (pretty unreliably) by playing the game for a while (to create a decent amount of events), and then joining while another player fires a coilgun towards some enemies.

When a client joins mid-round, the servers sends them all the "unique" events created during the round (for example entity spawn/removal messages), and after those have received, continues normally from the events that were created after the client joined.

That system was bugged, and the server would also send the unique events created after the client joined before switching to the "normal" event syncing. So the clients could potentially receive some events twice: in this case it received unique events about a bolt being spawned and removed, then switched to normal syncing and received some more events about that bolt (which no longer exists).

There could still be other causes for this bug, so I wouldn't call it fixed just yet, but lets see if we still encounter it during testing.

**Comment by NilanthAnimosus** [comment]
Encountered at round start testing unstable 0.9.701.0 and comparing it, its SO heavily desynced though at the start somehow.

This was a campaign I think. he was the only one kicked as well. May or may not have been his first round (Do not recall now, it has been hours).

so far in fact, you would think they loaded two completely different submarines and games, however their both event ID 2, entity ID 8452. Just Beyond the outpost I can't see much of anything that matches.

Dedicated server on left, Client on right: - I recall for a heartbeat "Too many events" (some 400-500+) but no strict issues. Had several clients then, here is my difference checking tool to compare partway down:

I believe the client actually re-established their connection (and may have not crashed, somehow) - and synced successfully, or they forgot, disconnected and crashed. but rejoined fine (Even had a 5 minute reconnect timer for killdisconnected).

![image](https://user-images.githubusercontent.com/29177976/73128766-35665a80-3fcc-11ea-80be-2fc53d87f164.png)

This is after the fix, but I think before 2042's potential fixes.

Dedicated servers side:
[event_error_log_server_nadir_1835.log](https://github.com/Regalis11/Barotrauma/files/4113034/event_error_log_server_nadir_1835.log)

Clients side:
[event_error_log_client_nadir_1828.log](https://github.com/Regalis11/Barotrauma/files/4113035/event_error_log_client_nadir_1828.log)

despite a different in the number (I assume that is an hour and minute timestamp?) it is the same entity ID and event ID.

Additionally confirmed they had no other event error log files and that it was timestamped from today.

**Comment by Regalis11** [comment]
It looks like the client loaded the wrong submarine for some reason:
![189472kihnjaswf](https://user-images.githubusercontent.com/14351070/73136089-56718e80-4052-11ea-8200-fb8b5fffb9e2.png)

That explains why basically all of the IDs are completely mixed up. I'll try to figure out a way to repro and fix this, thank you so much for the logs!

**Comment by NilanthAnimosus** [comment]
I seem to have lost / deleted the server-side logs of this, but my barotrauma client in steam (Who was also connected to said campaign) I found the log that recorded this (As my client received serverlogs)

[Nils debug server_2020-01-25_1851.txt](https://github.com/Regalis11/Barotrauma/files/4113615/Nils.debug.server_2020-01-25_1851.txt)

The client who disconnected is "Nadir" and before that the server had crashed (I remember the "Got the band got together following a crash). we loaded a campaign save I believe from memory, the logs do confirm it is a campaign, and the submarine typhon2.

**Comment by Rokvach** [comment]
This issue wasn't encountered in yesterdays testing, will keep it open for couple more days just to make sure.

**Comment by Rokvach** [comment]
There hasn't been any newer encounters with this issue on the latest Unstable version, moving to Done.

**Comment by NilanthAnimosus** [comment]
not sure if this is technically done.

In the unstable discord channel I saw this, have yet to get any logs though or information.

"sorry for a crappy description but yesterday our campaign mission crashed after firing a railgun shell into a thresher. A popup message showed up (That I of course forgot to take screenshot of) that said something about "failed thresher event". After that the mission ended instantly and it kicked us all back into the lobby"

it says crashed, but they say kicked to lobby - I thought they would be disconnected, not a server still up. hence why I will mention it here.

**Comment by Rokvach** [comment]
Moved back to To Do as a new issue relating to the ID issue was found

**Comment by Rokvach** [comment]
@Regalis11 ping

**Comment by Regalis11** [comment]
I think I figured out what was causing that specific error.

The clients and the server would both randomize the number of monsters per mission when instantiating the mission, and spawn the monsters by themselves in Mission.Start. This isn't a problem in the single missions, because the missions are instantiated at the same point of the round initialization process, and the synced RNG will give both the same number of monsters.

In campaign, the situation is different: the missions are not instantiated in any consistent order, so the clients may end up spawning a different amount of monsters, which leads to the "entity not found" errors as the entity IDs get mixed up.

I reworked the initialization logic of all the mission types; now the clients aren't allowed to spawn _anything_ for the mission unless the server tells them to: https://github.com/Regalis11/Barotrauma-development/commit/b3fa4d650d6b2c9dc06877d54fb9a35d0aaab085

One more "entity not found" bug squashed hopefully, lets hope there aren't that many left. :)

**Comment by NilanthAnimosus** [comment]
Can we just finally have all monsters done server side and not have this be a problem while maximising modding? I would love you to death.

Joking aside though, That does sound like an awkward problem. I am not sure if you mean the server sends all the entity spawn events - which if it does at this rate we may begin to need pacing or start of round pausing til everyone syncs up (and bonus syncing time) as I find it quite common to see "Too many events to send" errors at round starts and I can only imagine it getting worse with modded content.

**Comment by Regalis11** [comment]
>Can we just finally have all monsters done server side and not have this be a problem while maximising modding? I would love you to death.
That's exactly what I just did. :)

>I am not sure if you mean the server sends all the entity spawn events - which if it does at this rate we may begin to need pacing or start of round pausing til everyone syncs up (and bonus syncing time) as I find it quite common to see "Too many events to send" errors at round starts and I can only imagine it getting worse with modded content.
That won't be a problem; the server doesn't use the usual entity spawn events, but writes the data needed to spawn the monsters in the STARTGAME packet that's sent reliably at the start of the round (before any events go out).

**Comment by Rokvach** [comment]
No entity issues spotted on the 704 version, so far.

**Comment by NilanthAnimosus** [comment]
Not only did we have no issues to report with entities on the 705 version, we did a multiplayer campaign game from the outside of the map to the centre (in a good 5+ hours) with no in game or mission start entity issues other than one case of excessive desync at round start (Which was minor, and quickly the game reconnected more or less flawlessly) - when tons of items were bought I believe.

**Comment by Rokvach** [comment]
Closing this again, hopefully for the last time.
