### ISSUE TITLE
[feature request] add command "outfitdebug" to toggle console item list

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2028]
the dynamic outfitting list of items that appears in the menu can get extremely long and can push important things off the screen depending on the amount of dynamic containers. it would be nice if there were a bug to toggle it on and off with something like `outfitdebug`, with it being off by default. this way sub makers would still have an option to debug without everyone else getting their consoles effectively wiped every time a round started.

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/fb3885527633a270d763854bca5109a26729adc5

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
