### ISSUE TITLE
[Bug] Linux – Regex-component not working

### ISSUE THREAD

**Issue by roidal** [Regalis11/Barotrauma#2029]
In the linux-version the regex-component seem to be bugged, it triggers always (on each radio-message) undepended what expression is entered.

**Comment by Regalis11** [comment]
Haven't been able to reproduce this. I suspect that it was an issue in the circuit or the expressions used; if regex components in general were broken on Linux it would affect many of the vanilla and custom subs, and I think we would've gotten reports about it.
