### ISSUE TITLE
Баг с маской клоуна. / The bug with the clown mask.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#203]
Иногда, при крушении, маска выпадает из субмарины, но при этом "левитирует" в воде. Просто стоит на месте. Сейчас скриншот сделать не смогу.
Sometimes, in the crash, the mask falls out of the submarine, but "levitates" in the water. Just standing still. Now the screenshot can not do.
Добавил 20.01.2018:
Как оказалось, этот баг не только с маской клоуна работает. С чем связано - не знаю. 
Added 20.01.2018:
As it turned out, this bug is not only with a clown mask is running. What is the reason - I don't know.

**Comment by Regalis11** [comment]
Haven't seen this happen, and without further info I don't think this is reproducible.
