### ISSUE TITLE
Crash while starting a round (Unstable.)

### ISSUE THREAD

**Issue by DerpiHerpy** [Regalis11/Barotrauma#2030]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just fixed the Hash problem, Now when we tried to go into a round, the entire thing just desynced and my barotrauma just crashed.
**Steps To Reproduce**
No clue..
**Version**
Unstable 6.700 i think it was.
**Additional information**

**Comment by Regalis11** [comment]
We unfortunately cannot reproduce this as it happened with a modified build and there's no crash report.
