### ISSUE TITLE
Bots doesn't use Alien Pistol as a weapon.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2031]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots do not use Alien Pistols as weapons, even if it's their only weapon.

**Steps To Reproduce**
Give a Alien Pistol with a Alien Power Cell to any Bots. Don't let them have any other weapons including plasma cutters/welding tools.

**Version**
0.9.6 ~ 0.9.7

**Additional information**
N/A

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61c568ccb2e0a4dfb33491fa3c39f423e00a1c8f (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
