### ISSUE TITLE
Bots doesn't know how to repair hatches and doors

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2032]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots doesn't know how to repair hatches and doors.
0.9.6 - Bots stand near them and prevents players from repairing by canceling and spamming open/close.
0.9.7 - Bots checks them and then leaves.

**Steps To Reproduce**
Break doors by controlling a Mudraptor.

**Version**
0.9.6 + 0.9.7
Windows

**Additional information**
Also to add, when there's damages to the floor or shell of a submarine, and a duct block infront of it, and as well as a ladder, bots will try to repair the damage from infront of the duct block while on the ladder, but will be unable to and will weld the duct block and permanently spray at it, instead of welding it from a different floor/angle.

**Comment by itchyOwl** [comment]
They do, but there was a bug that prevented them to interact with doors. Should be fixed now.

Using the welding tool has always been a bit difficult for the bots. Let's see if we can get them better (still) with it. Would help if you could make another ticket with an example or steps to repro (with image).

**Comment by Kaillera** [comment]
Already included it into #2239.

**Comment by Kaillera** [comment]
Continued into #2436
