### ISSUE TITLE
[Feature Request] Customizable Passive Sonar Range?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2034]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can we please ask for a configuration in navigation terminals and/or transducers to change the detection range for passive sonar? It seems like bigger subs have a harder time seeing what's next to in front of them than smaller subs do. I also find that the frontal range is horrendous (on my sub you can't even see a wall you're grinding against on the right), where as you can see the rear quite a bit.

**Comment by Regalis11** [comment]
There is not really a "detection range" for the passive sonar: it detects noises emitted anywhere within the display, or sounds made by your submarine reflected from the ice walls. If nothing is making noise, you won't see anything.

**Comment by NicolaruS** [comment]
If the developers add a contact for the range and channel of the wi-fi module, players will be able to make their own sonars. This will create a new profession for acting out the role.

**Comment by NicolaruS** [comment]
When this happens, I’m ready to provide my version of custom sonar.
