### ISSUE TITLE
Unstable - Sprite Depth having issues

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2038]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sub Editor's Sprite Depth input seems to get reset during gameplay to default values.

**Steps To Reproduce**
You can see it everywhere, even on Vanilla subs. Wires especially sticks out.

**Version**
0.9.7
Windows

**Additional information**
N/A

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ee9d9d680df5a9bda615df09f992042ec28eebba

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
