### ISSUE TITLE
Hull names reset when editing localization files

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#2040]
It doesn't always happen but when it does, other stuff seems to reset in submarines, aswell. I've had submarine objets double in size. Again, not always but I always find that weird. Even names given without using localization file ones get resetted.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/129e1c77cfe5d31d5c1f90913fd72b9ac155e0c2

**Comment by Rokvach** [comment]
Working correctly. Closing.
