### ISSUE TITLE
Unstable - Bug - Strange decimal values in game's audio settings

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2045]
![bug1 sliders](https://user-images.githubusercontent.com/59519434/73090027-ce677980-3ed7-11ea-99bc-1c68fe16be69.png)

**Description**
In volume settings, instead of sliders locking on 15%, 30%, 60% they lock on 15.000002%, 30.000002% as shown on the picture.

**Steps To Reproduce**
Open game volume settings and slide the sliders.

**Version**
Unstable

**Comment by Rokvach** [comment]
This has already been fixed and coming with the new UI, closing.
