### ISSUE TITLE
Thoughts about hull flooding (Volume + Max Compress) and gap logic

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2046]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is not strictly a bug nor a feature request, but something I am pointing out with the game logic itself that is unusual and if it is preferred to keep it this way in the future.

The current game logic uses the rect's width and length of a hull for maximum volume - which makes perfect sense. However the maximum compression of water for a hull is a flat 10000 added. so a volume of 59904 has a maximum of 69904 water volume.

Where does this cause problems and why? Well - in none standard hull shapes which are now far more common due to the new curved and diagonal hull pieces.

Below is a more typical hull, tweaked from the second to use less hull pieces for the rough same space:
![image](https://user-images.githubusercontent.com/29177976/73092545-be01cf80-3ed4-11ea-965f-f69e1df8662c.png)

And a none typical hull design that is perfectly valid for almost the same space as above:
![image](https://user-images.githubusercontent.com/29177976/73092556-c22ded00-3ed4-11ea-9d9e-9b4ca4138632.png)

the top image has a total volume of 59904+8192 with 2 hulls, this gives it 68096 volume with a max compression volume of 88096.

The bottom image with a more complex design has a total volume of 35328+16128+14592+8704 (Last bit unknown as its too small to read) across 4 hulls.

This has a maximum volume of 74752 (Very similar!) - with a max compression volume of 114752 (YIKES!)

since a submarine has a fixed neutral buoyancy level of 7% of total volume, more complicated hull designs very heavily penalize a submarine. which this may want looking at if better math is available to get this closer to a standardized difference less based on the hull shape but more on the actual volume, without effectively instantly crushing people (such as flow rates).

Though I don't think it would be unrealistic for near instant crunch times in super tiny, rapidly flooded and compressed spaces from comparatively giant holes to the hull size - It would feel weird if it was between several other connected hulls to flow water through that hadn't fully compressed much to suddenly crush whom was inside.

**Comment by HalfdeadKiller** [comment]
I personally think some sort of percentage of the hull should be the maxcompress. So maybe have the max compress be 50 percent of the hull volume. So like 2000 volume would have 1000 added to it as the maxcompress, for a total hull of 3000. 

However that would make large rooms like 70,000 volume hull be 105,000 with that system. Testing would be have to be done to figure out what a balanced percentage of hull volume would be.

**Comment by Regalis11** [comment]
Submitted a PR, needs testing: https://github.com/Regalis11/Barotrauma-development/pull/1450

**Comment by Regalis11** [comment]
Fixed in the private repo now https://github.com/Regalis11/Barotrauma-development/commit/1a85497d8137a169f07f6d45482bf377f0712cac

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
