### ISSUE TITLE
[Unstable - bug / mod feature request] Clients do not send commands they do not know

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2048]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Version**
Unstable - 0.9.7.0

Not really a bug since it doesn't effect the base game but I was implementing a custom command on the server-side, to find the client would not send it for the server to check.

My client was repeatedly stating (Inc. quotes):
Command "commandname" not found.

regardless of the combination I used, 
the command appears in my dedicated servers autocomplete, and on the dedicated servers side I cannot see a reason for it to skip the command using breakpoints anywhere that text appears in the entire solution, so I feel this is a client problem.

If a mod has server-side only commands, despite all they really need is the command, a string, and perhaps the cursor position without the client having modified files - it limits ones options. the client appears meant to be able to send a command even if it does not have it, yet it appears not to be doing that.

Could support for sending console commands/strings that do not exist clientside (But perhaps server side) be implemented or reimplemented if its a bug? It already would support sending the screen coordinates and other information, its just not letting them through.

Additionally, the command had been listed in the clients permissions, though naturally does not appear in the list of given permissions for the client (Perhaps there would be a way to amend this to include commands a client does not have?)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ebfef3594b3d94eeba68a354b9da221286abf55a (private repo)

**Comment by Rokvach** [comment]
Waiting for confirmation from Nilanth

**Comment by NilanthAnimosus** [comment]
Tested, working correctly in 0.9.703.0 using a custom command on the server, that was not present in my unmodified steam unstable build.

**Comment by Rokvach** [comment]
Confirmed working, closing.
