### ISSUE TITLE
AI quirks: doesn't equip oxy/welding fuel tanks, tries to fix ruins

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#205]
I recall giving a mechanic a Fix Leaks command, so he dons a diving suit, picks up an empty welding tool despite having a full one in his jumpsuit, and runs out of the airlock to then idle and do nothing. Ruins were nearby so I suspect he was trying to reach the ruins to fix them.

He also frequently picks up empty diving suits despite there being A: ones with oxygenite shards around, B: an oxygen tank in his inventory and C: oxygenite shards in his inventory, none of which he put in the diving suit.

The reactor operator task is also pretty useless as they don't keep track of the fuel rod condition and will never replace fuel rods when needed. They also won't put three fuel rods in case of a leak.

I think what should be the focus right now is a crew AI system robust enough to control the entire submarine without any player input should the tasks be assigned carefully, as that would also prove the AI to be good enough for PvE missions against enemy subs in multpilayer.

Later on I'd imagine the single-player camapign crew to have traits or stress levels you'd have to manage as the captain as well, giving it a more Dwarf Fortress-y vibe and to counter-act their OP sub-operating powers.

**Comment by Regalis11** [comment]
The oxy, leak & reactor problems should now be fixed, so I'll consider this done. The crew AI definitely still needs a lot more work, but we could use a new issue for that.
