### ISSUE TITLE
[feature request] push notification bubble for "favorite servers" tab

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2050]
favorite servers tab is kind of useless at the moment. It would be nice if there were a notification icon like [this](https://images.contentful.com/3cttzl4i3k1h/56XGwqoTaMQwiaCwUUwqMM/10643ae83b775cbf163d73f734acdbfc/icon_push-notifications.png) so people can see when their favorite servers are online. the push notification bubble could also be viewable from the main menu above "server browser" or whatever. just another suggestion, taking up another slot.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1732](https://github.com/Regalis11/Barotrauma-development/issues/1732) via [**ZenHub**](https://www.zenhub.com/)
