### ISSUE TITLE
[bug] [AI] Bot attempts to operate door that it can't

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2051]
![2020-01-25-120609_372x375_scrot](https://user-images.githubusercontent.com/47284081/73125317-24d1c800-3f6b-11ea-94b6-6158ce3b049f.png)
bot in this picture is trying to open hatch door while being physically restricted by the upper-right door. not sure if there's a solution for this, not a common occurence but one nonetheless. happened on a server, might have to do with that, but it keeps opening and closing the hatch while being stuck behind the door.

**Comment by itchyOwl** [comment]
Can be a bit difficult to repro this. What the sub was?

**Comment by itchyOwl** [comment]
I think we should close the ticket, as there's not enough information to solve it.
