### ISSUE TITLE
Berilia missing storagecab or engcab tag in fabrication room

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2052]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Berilia has no random materials to craft with. It has engfabcab which nothing uses that tag I believe.

**Version**
0.9.700 ~ 0.9.701

**Comment by danielasteljoki** [comment]
Changed 'engfabcab' to 'storagecab' in 92078f4.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
