### ISSUE TITLE
Berilia sub.topright's pump missing wire to Signal Check Component

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2053]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Missing wire to signal check component in sub.topright's pump. Though the component is unnecessary anyways, but all the other pump has it.

**Version**
0.9.700~0.9.701
Windows

**Comment by danielasteljoki** [comment]
Fixed in dev branch.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
