### ISSUE TITLE
Unstable - Debug mode in project writes crash reports

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2055]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash reports are written as the code appears to ignore #IF DEBUG and other such statements, this was with the dedicated server but may effect the client too.

This does mean I do not get to step through the code, see where it broke specifically and such due to the exception being handled then killing the process. It isn't hard for me to comment these out - but is a thing.

Appears to be due to || TRUE which Is a very odd thing to have.

**Steps To Reproduce**
I suppose crash. While debugging on windows.

**Version**
Unstable - 0.9.701.0 - Dedicated server debug windows

**Additional information**

Top snippit of a crash log indicating it is in DebugWindows:

```csharp
Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.9.701.0 (DebugWindows, branch GIT_UNAVAILABLE, revision GIT_UNAVAILABLE)
Selected content packages: Vanilla 0.9
Level seed: BathakonVellamo's Crevasse
Loaded submarine: Typhon2 (B5923876FBD7E67F506B1335D0396688)
Selected screen: Barotrauma.GameScreen
Server (Round had started)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6875de2a9756a70bd1d7ecda2665d8bec6f158b (private repo)

**Comment by Rokvach** [comment]
Confirmed working, moving to Done

**Comment by NilanthAnimosus** [comment]
closing issue as this is now fixed.

**Comment by Rokvach** [comment]
We keep the tickets open until they are fully reviewed
