### ISSUE TITLE
Windows dedicated server output replaces itself (?) gravitating to 1 line

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2056]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Ok leaving the original description below, I found a (Weird) solution, if not perhaps what caused it, by raising the TOP of my dedicated servers box and then raising the bottom, reveals the ...messages. Which is weird. I don't remember resizing the bottom then downsizing from the top repeatedly, but this "got the messages back".

**Description**
I could not possibly be clear or for this, New messages remove previous messages. there can be messages below that say there forever (As if moving up a pointer without removing whats below) when typing.

When multi-line messages appear, these "Create" lines then slowly fade away one at a time until only one remains.

At first I thought it was because I dared to attempt increasing the max console size (from 300 to 1000 because I kept using dumpids a lot) but it wasn't that.

![image](https://user-images.githubusercontent.com/29177976/73127101-51113700-3fb3-11ea-9143-68f03d0c81f5.png)

here is me typing about 1+ minutes ago with it still there:

**Steps To Reproduce**
Host a dedicated server using windows. Attempt to actually use it.

**Version**
Unstable - 0.9.701.0 - windows dedicated server (visual studio debug)

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4cac3ed9f4c91ede57d1919badfa368defb53fbe

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Rokvach** [comment]
Nvm, found a issue while testing latest dev

Typing anything fetches the command the word you are typing is closest to, hitting backspace while there isn't anything on the input just sends a empty new line.

Video:
https://streamable.com/zcv23x

@juanjp600

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3477bc9e09137ffb1cbd87232507ef001143a74

**Comment by Rokvach** [comment]
Tested, no issues. closing.
