### ISSUE TITLE
Unstable - AI Medic not letting go or treating.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2057]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I swam to a ruin, for an artifact. Got attacked by some 3 or 4 fractals as a mechanic and killed them with just a crowbar and a few medicals (Probably halfway to an addiction with 2 fentanyl uses as mechanic, plus bandages and blood). and returned to the sub around half.

the AI, left in "Rescue" mode. Sprinted after all, and kept on grabbing me yet not doing much. Saying he needs X/Y/Z item yet not running off to find some.

the AI, then continued this as the room started to flood, hilariously meaning I would suffocate, and be unable to quite swim out of the grab very well before an immediate instant grab.

As a note I'm sure I could "Break away" but the AI always immediately chased, grabbed again - then did nothing.

AI constantly grabbing + his speach:
https://i.gyazo.com/660459e02c6a053a71ad8d9b361fecf6.mp4

AI Literally trying to drown me after 30 seconds to a minute of amusing me:
https://i.gyazo.com/72abd36097200172b281826ce8f0050c.mp4

**Steps To Reproduce**
Unknown, I am sure the submarine will have had medicals available, definitely was saline and blood, and perhaps a few morphine's so I don't think it was a lack of inventory.

I had 1 morphine on me in medical clothing I found and a saline in a separate toolbox, using my morphine up made the AI go away, perhaps the AI was trying to use the morphine from my clothing (?)

**Version**
Unstable - 0.9.701.0

**Comment by itchyOwl** [comment]
Feature or bug? :D

**Comment by itchyOwl** [comment]
There were several issues in medic ai that prevented treatment in some situations. Should be fixed now. But the medics still hold on to you if you need treatment. Not sure how or if we should solve that.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
