### ISSUE TITLE
[Issue] [Hitscan] [Sorta modding] Turrets using hitscan can't damage subs from the outside.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2058]
Easiest way to reproduce this would just be to give the coilgun bolt projectiles hitscan property.

Using hitscan projectiles with turrets seems to not properly damage subs or structures if shot... from the outside(?).
![2020-01-25-172846_684x407_scrot](https://user-images.githubusercontent.com/47284081/73128703-f0750080-3f98-11ea-9c63-48b2d520ccad.png)
Here is a hitscan turret shooting at a sub from the outside of TestSub at the Dugong. note the lack of structure damage on the dugong.
![2020-01-25-172929_703x418_scrot](https://user-images.githubusercontent.com/47284081/73128711-0edafc00-3f99-11ea-8697-cc676a1f7f35.png)
I spawned the dugong so that it really glitchily overlapped with Testsub. when the turret fires from the inside of the dugong, it notably shreds the walls instantly the way it's supposed to. No idea why this happens, but it's a bug. I imagine this is in the same ballpark as the ruins hitscan bug.

**Comment by Tsunder** [comment]
@Regalis11 i think this is fixed
