### ISSUE TITLE
Physics error when characters latched onto the sub take damage

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2059]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
EnemyAIController tries to remove joints in the OnAttacked callback, which is not allowed during a physics step.

**Steps To Reproduce**
Wait for a crawler to attach to the hull and shoot at it

**Version**
v0.9.700.0, v0.9.701.0

![73128504-5167fd00-3fc8-11ea-81d9-e3a126b820ce](https://user-images.githubusercontent.com/14351070/73134967-9bdb8f00-4045-11ea-9522-9c4a28ae933a.png)

Originally mentioned in #2054, but I decided to make a new ticket because it seems to be a separate issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/31eac8e1249eb13c31f11fcb180125911e92ad7c (private repo)

**Comment by Rokvach** [comment]
This issue wasn't encountered in yesterdays testing, will keep it open for couple more days just to make sure.

**Comment by Regalis11** [comment]
As the steps to reproduce this are known, it would be better to test if it occurs than waiting for it to happen by chance

**Comment by Rokvach** [comment]
If its that simple then I can already confirm that it is working because of yesterdays testing results, I thought there was a bit more to it than that. Moving to Done.
