### ISSUE TITLE
Bots abandons coilgun/railgun periscopes if the room has water

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2060]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will abandon manning coilgun and railgun in favour of searching for a diving suit when the room is flooded. Although when they do find a diving suit, they do not return to the scope with the suit. They enter a loop between trying to put back the suit before getting on the scopes and going to find a diving suit because the room has water.

**Steps To Reproduce**
Flood the gunnery room of any sub while not repairing breaches or draining the water.

**Version**
0.9.6~0.9.701

**Comment by Kaillera** [comment]
https://youtu.be/Pj6a5eDnlNk

**Comment by NilanthAnimosus** [comment]
sounds like an issue with findsafety then considered themselves safe, despite their destination would hardly be considered "Safe". Abandoning the suit somehow, not read the code but usually find safety seeks diving suits. and is also the objective to probably take them back off.

**Comment by itchyOwl** [comment]
Thanks for posting the issue and especially the video. When debugging bots videos, especially with debug mode enabled (type "debugai" in the console), are more important than words. We've had similar issues before, but I thought they have been fixed. I'll try to repro and fix it.

**Comment by itchyOwl** [comment]
Was able to repro. Seems to be very similar to the previous issues.

**Comment by Kaillera** [comment]
I didn't even knew debugai existed

**Comment by itchyOwl** [comment]
It's just debugdraw + los + lights + freecam.

I think I got the issue fixed. Although I can't be sure for certain that there's only one issue there.

**Comment by Rokvach** [comment]
Couldn't see any issues, closing.
