### ISSUE TITLE
Feature request - Allow hosts to selectively hide or remove vanilla/downloaded submarines from servers

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2061]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Removing submarines from servers cause package errors to be listed (But does not break the MD5), though it is definitely to be considered a basic feature to have the choice of which submarines to host with, including vanilla ones. Perhaps add a blacklist to not load / not send certain submarines on server load.

This way, we wont have to delete vanilla shuttles / submarines to not use them, and not have errors in the console for not wishing to use them and instead provide our own.

**Comment by Regalis11** [comment]
Setting this as high prio, because it has been suggested so many times and seems pretty simple to implement.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1733](https://github.com/Regalis11/Barotrauma-development/issues/1733) via [**ZenHub**](https://www.zenhub.com/)
