### ISSUE TITLE
Typhon2's "intentional" needed reconfiguration improvements required

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2063]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So while I understand that the Typhon2 has the intentional design for players to reconfigure some of the components properly, I have 2 problems with it.

1. The broken/missing components are all congregated to the bottom left. I feel that other section's of the sub should as well.

2. The relay component that runs the battery has a misconfigured wire from the Nav terminal to the relay component is on set state rather than toggle state. The problem is that the component should either be missing or visible to interact with from the outset. Having to cut the floor to access it raises suspicion unless everyone knows about the current defects.

**Version**
0.9.701

**Comment by ezjamsen** [comment]
fixed in dev

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
