### ISSUE TITLE
Nasanov Artifact are too rare and doesnt spawn outside naturally like the other artifacts

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2064]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've picked up many many artifacts over the course of playing the game for 600+ hours, and I can safely say that Nasanov artifact doesn't spawn outside naturally (backed up by randomevents.xml), and doesn't really spawn in ruins either. I think I've only handled that artifact specifically 6 times to date.

**Version**
0.9.5~0.9.700

**Additional information**
To be fair, it's pretty easy to find several alien ornaments already, as well as buying the materials at a research station. I don't think balancing the weight for Nasanov to spawn lIke the rest will hurt anything.

**Comment by Regalis11** [comment]
The spawn rates of nasonov artifacts were increased in 0.9.701.0: in the higher-difficulty levels they're as common as any other type of artifact.

**Comment by Rokvach** [comment]
Working correctly. Closing.
