### ISSUE TITLE
Placing down components on the outside of an exterior hatch/door during gameplay stays invisible/uninteractable

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2065]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you place down components outside next to the submarine's exterior hatches or doors, the components will be invisible and uninteractable until you reach the next station and start the next round during 0.9.6. This makes rigging subs with a docking hatch below for shuttles into a airlock a 2 rounds step before it's fully functional. It's no longer possible to attach anything outside in 0.9.701

0.9.6 - In singleplayer, the buttons are placed down fine. In multiplayer, the issue above is present until next round.
0.9.701 - Issue exists in both single and multiplayer, components stays invisible and uninteractable.

**Steps To Reproduce**
What I usually do:
Play any submarine with a docking hatch below it, in both single and multiplayer. Unwire the docking port wire to the hatch's set state. Install a button inside to toggle the docking hatch. Install a button outside while the hatch is opened (can't place anything outside without a background or the hatch is closed) to toggle the docking hatch. The button will be invisible and cannot be interacted until you reach the next station and start a round there to finish wiring it in 0.9.6. Impossible to complete in 0.9.701

**Version**
0.9.6~0.9.701

**Additional information**
N/A

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6b6639c316906575eedfecd8af5edfd04fc0be1

**Comment by Rokvach** [comment]
Placing items on the submarine walls outside of submarine works now.

But, if you place a item outside of a submarine in the water the placed item just vanishes entirely, I think on those cases there needs to be a warning that a item can't be placed there similar when trying to interact with doors you don't have access to and just cancel the action. @Regalis11 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4a2805c5-1c0e-4a18-a14c-09a921406270)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7e81460541c1ea884737e30937f7766c25ae3d89

**Comment by Rokvach** [comment]
It is still possible to place an item outside the submarine, but not as far as previously as some part of your body has to be inside the submarine, so when your body fully passes the airlock door you can't place anything down.

Maybe allow placing components at that point as it is close enough or don't allow the items to fully vanish but rather get unselected. As I can see it being quite annoying if you place an item just a unit away from where it is allowed to be placed you lose it entirely @Regalis11 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a4de1ebf-5467-4b1c-8727-e7e95157110d)

**Comment by Regalis11** [comment]
Attempt 2: https://github.com/Regalis11/Barotrauma-development/commit/820e3c3336cdc327cd6c4134125140c92a25c199

**Comment by Rokvach** [comment]
Tested on bugfixes branch, if I try to place a button anywhere in the red area the item just vanishes @Regalis11 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1e6eed5a-81da-44b0-8b37-8ff44944d2a3)

**Comment by Regalis11** [comment]
Attempt 3: https://github.com/Regalis11/Barotrauma-development/commit/358331bf01cf48ee5ac6c34c5a08a075f5b137c9

This should also be tested in multiplayer because it affects how the server places the item when a client attaches it. Gave it a quick try myself and couldn't spot any issues, but it'd be good to double-check.

**Comment by Rokvach** [comment]
I am unable to detach the item in multiplayer once it has been placed outside the sub, the whole detach contextual entry is missing from the viable actions. Detaching works fine inside the sub. @Regalis11

**Comment by Regalis11** [comment]
That was done to prevent players from deattaching items outside the sub which back then couldn't be reattached. But now that they can I think we can allow it as long as the item is attached to a position where it can be reattached.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6160feccfd3efe2b0a54c9b85f45759424ce2c6a

**Comment by Rokvach** [comment]
Finally working correctly, closing.
