### ISSUE TITLE
Unstable - Dedicated server crash (EventManager settings is null at campaign start?)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2066]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No idea how this could happen, but my server crashed to shared's / events / EventManager.Update (Line 310) for settings being null at the start of a campaign round.

**Steps To Reproduce**
Unknown. I was literally asleep.

**Version**
Unstable - 0.9.701.0 windows dedicated server.

**Additional information**

![image](https://user-images.githubusercontent.com/29177976/73324910-82546600-4244-11ea-8153-5c3ac88d2f1a.png)

Really not sure what to say ,the roundduration is literally a few miliseconds (The first update?) and the same as the deltatime.

Somehow the first update into a round its managed to reach this code before it was set in the roundstart code. I assume this is some form of multithreaded problem.

**Comment by NilanthAnimosus** [comment]
Had a second crash for this, again I think it was a campaign. And I have not had that many players (I've had around 6 or 7 server logs for my hosting of the unstable at most) since the update.

**Comment by Regalis11** [comment]
Added some extra safeguards to prevent this from happening in https://github.com/Regalis11/Barotrauma-development/commit/819ce7f897fc0217420eccaca433c243d47d9022.

Now if it occurs, EventManager tries to select the settings again, and if no settings are still selected, it disables itself for the rest of the round. Also added some extra error logging.

**Comment by Rokvach** [comment]
There hasn't been any sightings of this since 701, just going to close this.
