### ISSUE TITLE
[Bug] [Typo] Particle editor uses Water drag's description again for collision radius

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2070]
extremely minor issue, the text for the Collision Radius tooltip in the particle editor is identical to the Water Drag's tooltip.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6e54f49df2ab0c8eec440804a3af4b0fed87bd86

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
