### ISSUE TITLE
Unstable - crash in MonsterMission Update

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2071]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The server (and it seems client) crashed close to a missions start.
Reloading the save crashed it again, but on the third time it did not.

**Steps To Reproduce**
Unknown/untested, including save file of the campaign:

[Monster Mission crash.zip](https://github.com/Regalis11/Barotrauma/files/4130612/Monster.Mission.crash.zip)

Mission was against a hammerheadgold. I dont know the specific mission that might be causing this, or if this causes it to repro

**Version**
Unstable - 0.9.701.0 windows dedicated server (debug)

**Additional information**

```csharp
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
DedicatedServer.dll!Barotrauma.MonsterMission.Update(float deltaTime) Line 111
	at F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MonsterMission.cs(111)
DedicatedServer.dll!Barotrauma.GameSession.Update(float deltaTime) Line 312
	at F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs(312)
DedicatedServer.dll!Barotrauma.GameScreen.Update(double deltaTime) Line 129
	at F:\Github Sources\BT-FA\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs(129)
DedicatedServer.dll!Barotrauma.GameMain.Run() Line 340
	at F:\Github Sources\BT-FA\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs(340)
DedicatedServer.dll!Barotrauma.Program.Main(string[] args) Line 38
	at F:\Github Sources\BT-FA\Barotrauma\BarotraumaServer\ServerSource\Program.cs(38)
```

Monsterfile = "Hammerheadgold"
MonsterCount = 1
Monsters = 2 * Hammerheadgold
Monsterfiles count = 0

There were three tempSonarPositions

It looks to be the mission for killing a single hammerheadgold, yet there are two of them.

There is no mission that has 2 hammerheadgold's except the one for a matriarch, yet monstercount is 1.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2937968b1205ef7f3f5f732a320e6078f7f61334 (private repo)

**Comment by Rokvach** [comment]
There hasn't been any newer encounters of this issue, closing. We can re-open if it appears again.
