### ISSUE TITLE
Big submarine undocks into the ceiling.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2072]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My big submarine spawned practically in the cave walls at the start. When undocking the sub, it gets dislodged through the ceiling.

**Steps To Reproduce**
Go to Skaani natural formation in this save file. Undock the sub. You will be in the ceiling like so:
![](https://cdn.discordapp.com/attachments/671491079010385980/672421115301199872/Capture.PNG)
![](https://cdn.discordapp.com/attachments/671491079010385980/672421219605282816/Capture.PNG)

**Version**
0.9.701
[Windows]
[Stuck in Ceiling.zip](https://github.com/Regalis11/Barotrauma/files/4134043/Stuck.in.Ceiling.zip)

**Comment by NilanthAnimosus** [comment]
I had joined with him to see one issue, but instead experienced this one as a client.

it was...interesting to witness.

![](https://cdn.discordapp.com/attachments/671491079010385980/672421026814230528/unknown.png)

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/75101059-e993da80-55a4-11ea-81bb-b332988356b7.PNG)
Although not the ceiling this time, but stuck in the walls on the side. Can't drive the sub.

**Comment by Regalis11** [comment]
@juanjp600 Addressed in 24589a37?

**Comment by juanjp600** [comment]
Should be, marked as Review/QA

**Comment by Rokvach** [comment]
Confirmed working, closing.

**Comment by Kaillera** [comment]
Haven't seen it since 0.9.8,
