### ISSUE TITLE
Bots that has Body Armor and Helmet does not equip them after replacing them with diving masks and suits

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2075]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots that has Body Armors and Helmets in their inventory will not put them back on after having to use other equippables in those slots like diving masks and suits.

**Version**
0.9.6~0.9.701

**Additional information**
I feel like they should try to keep those slots equipped in case of mudraptor breaches or something for maximum protections.

**Comment by itchyOwl** [comment]
Not implemented, so it's not a bug but a feature request.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1734](https://github.com/Regalis11/Barotrauma-development/issues/1734) via [**ZenHub**](https://www.zenhub.com/)
