### ISSUE TITLE
Multiple players that were using the fabricators can cancel each others crafting

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2077]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When multiple players are using the fabricator at the same time, they can cancel the crafting of the other players. They cannot cancel the crafting if they weren't there at the time of the craft.

**Steps To Reproduce**
Put 2 people on the same fabricator and craft something. The other person can cancel it.

**Version**
~0.9.701

**Additional information**
I'm not sure if preventing the fabrication cancellation by other players or giving everyone access to cancel it would be better here.

**Comment by Regalis11** [comment]
It's intentional that anyone can stop the fabrication process, but this sounds like a bug:
>They cannot cancel the crafting if they weren't there at the time of the craft.

**Comment by Kaillera** [comment]
Now it seems like no one can cancel any ongoing fabrications.
