### ISSUE TITLE
[0.9.702] No Report Leak/Fire/Damaged Buttons

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2079]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No buttons for the Report Leak/Fire/Damaged.

**Version**
0.9.702
Windows

**Comment by Regalis11** [comment]
Looks like we accidentally reverted the texture to an older version without those sprites when merging UI-related branches, fixed in https://github.com/Regalis11/Barotrauma-development/commit/57152ce6d95dff979c9c578bdf90d3b3ac648678 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
