### ISSUE TITLE
[0.9.703] Chat Box randomly disappears/reappears during gameplay.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2080]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Chat Box randomly disappears completely during gameplay. Does not respond to R and T chats. Randomly reappears as well, but will flicker on and off after a range of intervals.

**Version**
0.9.703
Windows

**Comment by NilanthAnimosus** [comment]
I've seen this myself in single player (not local hosting), Im not sure what causes it. Additionally it mostly occured while I was in freecam and the AI was dying left right and center (I spawned a bunch of AI, gave them orders. they all started being eaten/drowning etc and sometimes the UI would vanish).

**Comment by Kaillera** [comment]
Still happening in 0.9.703
![](https://user-images.githubusercontent.com/5086682/73778595-780cfd00-4759-11ea-9d6e-e46a7fbfe445.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b9900b190f7f9d425ecd7584b4a0f695ee8c646f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
