### ISSUE TITLE
[0.9.702] Sonar Beacon - Enable Beacon overlaps with Chat Box

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2081]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to activate a sonar beacon, the interface for it is overlapped with the Chat Box.

**Version**
0.9.702
Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d86b214b9b3864524af2a0e553565214464a39a3 (private repo)

**Comment by Regalis11** [comment]
Broken again due to sonar interface overlaps being temporarily ignored as of 99c596f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
