### ISSUE TITLE
[0.9.702] Shuttle/Drone Terminal Signal Button overlaps with Inventory Hot Bar

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2082]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The shuttle/drone terminal signal buttons overlaps with the inventory hotbar, making it hard to press the signal button and not your inventory.

**Version**
0.9.702

**Comment by Regalis11** [comment]
Should be fixed now in the dev branch, moving to Review/QA

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
