### ISSUE TITLE
[0.9.702] Campaign Shop Filter does not work correctly

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2083]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When typing items into the filter, it does not refresh the list of items to match the filter. Once you actually purchase something random, or another player with manage campaign does, the list then refreshes with the filter.

**Version**
0.9.702

**Comment by Kaillera** [comment]
Singleplayer, the filter for the shop doesn't work at all.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/346560dffa9ddd806bca5a06b434f78bbe34a192 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
