### ISSUE TITLE
[0.9.702] Command Interface (Middle Mouse) does not work in multiplayer

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2084]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot bring up the Command Interface during multiplayer via middle mouse.

**Version**
0.9.702
Windows

**Comment by Kaillera** [comment]
According to @NilanthAnimosus it seems like servers must enablecheats to order AI around.

**Comment by ekqvist** [comment]
Fixed with Regalis11/Barotrauma-development@0a8ce87

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
