### ISSUE TITLE
[0.9.702] Start round loop error

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2085]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to start a campaign round on dedicated server, this happened at one point.

**Version**
0.9.702
Windows

**Additional information**
![](https://media.discordapp.net/attachments/668819422919524352/672532270178893854/Capture.PNG?width=922&height=463)

**Comment by Regalis11** [comment]
The line number points to the first line in the code block below. I would suspect SelectedConnection was null, as none of the other values should change after the campain has been instantiated. Need to look into this in more detail to figure out how this can happen.

`GameMain.GameSession.StartRound(campaign.Map.SelectedConnection.Level,
	reloadSub: true,
	loadSecondSub: teamCount > 1,
	mirrorLevel: campaign.Map.CurrentLocation != campaign.Map.SelectedConnection.Locations[0]);`

**Comment by Regalis11** [comment]
Added some safeguards to hopefully prevent this from happening in https://github.com/Regalis11/Barotrauma-development/commit/b8e0b4ce18d1e880eb8e53329eef95f05b369595. Now the server should choose a random location if no location is selected when starting the round.

**Comment by Rokvach** [comment]
This issue hasn't been spotted in 3 builds now, considering this working, closing.
