### ISSUE TITLE
[0.9.702] Affliction icons overlaps with portrait. Affliction tooltip when hovering over them overlaps with health bar

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2087]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have afflictions, the icons are drawn over the portrait of the player. This makes it hard to recognize you have afflictions immediately. When you mouse over these afflictions, the name tooltip is behind the health bar of the player, making it hard to decipher.

**Version**
0.9.702
Windows

**Additional information**
![](https://user-images.githubusercontent.com/5086682/73496351-60fb9300-4386-11ea-9b3f-cdc034254476.PNG)

**Comment by Regalis11** [comment]
Fixed in the ui-merge branch, moving to Review/QA

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
