### ISSUE TITLE
[Bug] [New UI] Automatic Control Light turns off on mouseover

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2088]
If you mouseover the automatic control light in the reactor, it turns off for some reason (just the light, not the actual automatic control). small visual bug.
![2020-01-30-164811_377x190_scrot](https://user-images.githubusercontent.com/47284081/73497401-550cd280-4380-11ea-9f18-0449cbf840c7.png)
(the picture has it slightly turned on becuase of some weird screen capture selection shenanigans, but you can see for yourself ingame that it's fully turned off).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b511e30dd376ed9c43733231a6d399866078fe08 (private repo)

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
