### ISSUE TITLE
[0.9.702] Sub Editor - Toggle Visibility icon, doesn't really look like an icon.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2089]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unless you stare really hard next to the generate waypoint button, the toggle visibility button doesn't really look like it existed. Make it an eye icon?

**Version**
0.9.702

**Comment by Regalis11** [comment]
It is actually an eye icon, but there's something wrong with the scaling. Will take a look and fix! :)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6aaf80af968d6d87a92334012e11a524ce05031 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
