### ISSUE TITLE
[Feature Request] [New UI] [Issue?] Atlases aren't scaled relative to resolutions

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2090]
The game looks significantly better on higher resolutions because the UI atlases aren't scaled relative to the resolution.
![2020-01-30-165629_1366x768_scrot](https://user-images.githubusercontent.com/47284081/73497946-95b91b80-4381-11ea-95ba-95546c3e385c.png)
here is 1366x768. lookin pretty good.
![2020-01-30-165807_1021x573_scrot](https://user-images.githubusercontent.com/47284081/73498008-b4b7ad80-4381-11ea-91de-32a28ebe7b12.png)
here is the 8-bit esque resolution i usually play with (i like windows, okay). the UI looks chunky and doesn't evenly scale with the resolution so things like padding are basically nonexistent. looks significantly worse in some areas of the game.

**Comment by Regalis11** [comment]
Scaling the borders according to resolution implemented in https://github.com/Regalis11/Barotrauma-development/commit/397ef864f1ea40ae354d68be588476082c6227e9 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.

**Comment by hubismal** [comment]
This doesn't just apply to borders, I think the healthbar background stain might still be too big on lower resolutions.
