### ISSUE TITLE
Unstable - Organic Fiber is part of the storagecab tag

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2091]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if it's intentional, but I see Organic Fiber in storagecab outfitting. The weight for them is pretty high as well. It's not unnatural to see 3~4 of them in almost every cabinet with the tag.

**Version**
~0.9.702

**Comment by Regalis11** [comment]
Ping @ezjamsen, is this intentional?

**Comment by ezjamsen** [comment]
Not only was it assigned to the wrong cabinet, but it was assigned incorrectly twice. wtf. Fixed in dev.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
