### ISSUE TITLE
Bots are confused on reloading coilguns with two or more loaders linked

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2092]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are unable to reload coilguns that are linked to two or more loaders, and if both loaders have emptied ammo box in them. If you remove the boxes out of the loader for them, they will be able to, but not just "any" loader. It has to be the one they were targeting.

**Steps To Reproduce**
Link coilgun to two or more loaders.
Fire all the rounds from the boxes
Watch bots try to reload the loaders.

**Version**
0.9.700~0.9.702

**Additional information**
In 0.9.6, they are able to reload just fine, even if it's one of two of the loaders.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@3a833a7

**Comment by Rokvach** [comment]
Didn't notice any issues, closing.
