### ISSUE TITLE
[Unstable][Feedback] UI Feedback, suggestions, issues

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2093]
Im very pleased with the new UI, however I would suggest rearranging pieces of it so they dont encircle the game space, decreasing the immersion and a few tweaks.

**Crew and Command**
I suggest merging the Crew and Command interface into 1 because they seem similiar and the Crew window can do the same task easily, so there is less icons on the screen. Most people on servers most of the time do not give out orders or do not need to know all the time which orders are assigned to everyone else - all of this can be in the Crew window. Less icons would also mean less stuff on screen and that helps with immersion and clarity. Also, everybody is used to having crew on the left side of the screen so the new UI would be more welcoming.

**Reactor**
The fuel rod inventory for reactor seems very small and one has to squint to see the specific rods in there. Would it hurt something to make them normal size (as big as inventory squares?)
![ui suggestion 2 reactor](https://user-images.githubusercontent.com/59519434/73500874-2f092180-43c4-11ea-97b4-5a03b8893328.png)

**Inventory icons**
The usage bars of how full an item is are also not very well readable (look at the toolbox bar below). Also, did the medicine get smaller? It is much harder to distinguish between syringes of all types and again one has to squint to read them. Finding particular medicine in cargo is literally physically painful.
![ui suggestion 3 bar](https://user-images.githubusercontent.com/59519434/73501060-c2daed80-43c4-11ea-8b45-836fc419b651.png)

**Health bar and portrait**
This is a mess.
![ui suggestion 4 health bar](https://user-images.githubusercontent.com/59519434/73501071-cec6af80-43c4-11ea-8bd5-235d68f17e03.png)
You can't properly see how healthy you are because there is no way to tell where the bar ends. I like minimalism and especially minimalistic UI, but this is a necessary information for a health bar. Afflictions are shown over the character's portrait, so the icons are not properly readable and worse - when you mouse over them, the character's portrait gets highlighted and the description of affliction is hidden behind the healthbar. This entire group of UI is located top left on the screen, further encircling the game space and making the game less immersive. I suggest putting it on the bottom right for 2 reasons
1) The UI elements wont encircle the game space
2) Players are used to seeing their health and afflictions bottom right

**My suggestion for rearranging the UI**
![ui suggestion 1](https://user-images.githubusercontent.com/59519434/73502189-7396bc00-43c8-11ea-8460-be84e41eceec.png)

**EDIT1:ALTERNATIVE TO CREW AND COMMAND**
There already is a large easily accessible window for what Crew and Command icons want to achieve - the TAB window! You can easily and clearly see the crew, there is enough space for everything, even specific info of each crew member and everybody is used to pressing tab in multiplayer games to see the team.
![ui suggestion 6 tab](https://user-images.githubusercontent.com/59519434/73502078-21ee3180-43c8-11ea-9cb4-cf26642178f2.png)
The Command function would be called with a different hotkey (Q is usually used for menus like the command menu in other games), further decreasing the cluttered UI all over the screen. To easily switch between characters in singleplayer, just Tab&Click.

EDIT2: It's cool to see people's faces popping from the side of screen when they talk. It feels like story NPC avatars from other games when they talk to you over radio. I would keep this and place it above the chat window (next to, or above the Command icon).

**Comment by Rokvach** [comment]
All of these has been addressed, closing.
