### ISSUE TITLE
Double clicking an unconnected end on a loose wire in the Sub Editor crashes the game

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2095]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I double-click on the unconnected end of a loose wire in the Sub Editor, it crashes the game.

**Steps To Reproduce**
Video: https://www.dropbox.com/s/x5i3gqk2a8i7ui1/Barotrauma%202020-01-31%2000-10-21.mp4?dl=0
1) Wire a pump to a relay, then delete the pump
2) In the relay's wiring UI, loosen the wire that was connected to the deleted pump (I was unable to completely remove the wire)
3) Exit the Relay's wiring UI and click on the unconnected end of the wire, then click on it again.

**Version**
Barotrauma Unstable version 0.9.702.0
Operating System: Windows 10
.

**Additional information**
[crashreport_18.log](https://github.com/Regalis11/Barotrauma/files/4137676/crashreport_18.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddc61ad2d446a14721cd0a9689db8e57664ada56 (private repo)

**Comment by Rokvach** [comment]
This issue hasn't been tested yet, so can't close it just yet.

**Comment by mrjpjr** [comment]
Oh, ok. Sorry.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
