### ISSUE TITLE
Unable to pull bodies through Alien Ruin hulls

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2096]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When grabbing anyone or creatures, your character will let go of them when passing through each hull of an Alien Ruin. The body will not travel through to the next hull while grabbed. This makes it hard to retrieve dead players or moving bodies away to prevent them from shielding attacks to other enemies.

**Version**
~0.9.702
Windows

**Additional information**
At the moment the only way to retrieve bodies is to push the bodies by attacking them with various tools so that they aren't in rooms with reinforced alien walls, and cut the floor under them to let them sink out.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/17817ad81de59874f40026f52b6fa6599f364193 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
