### ISSUE TITLE
Multiple assignments of autoitemplacer on containers only picks one - is it intended or should be expanded?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2099]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if to be considered a bug, feature suggestion, design choice, or just a question.

As I recall, I tried adding multiple tags to a container to spawn a wider variety, Such as mineralcab (which spawns like 2-3 items) and storagecab (which spawns a ton of material items usually).

I wanted more minerals, yet less storagecab materials in a locker. as extremely few minerals actually spawn.

Due to the nature of how the autoitemplace code works however, once it adds items to a container, that container is no longer a valid source to add items to, regardless of it has more valid tags to do so, So instead of 2-5 minerals with the rest being materials, I got only 2-5 minerals and a big empty locker.

Should multiple tags on a single container be considered a valid spawning? thus allowing you to multiple the level of spawning (IE. storagefab, storagefab - if duplicate tags is allowed as a thing) or say, "Medicalcab, toxincab", not sure if that's accurate tagging but is an example.

Why would you want or expect this to be a thing, which may not seem obvious to anyone, well - if your a modder or a sub designer, you may have either custom categories for these tags with far less items and want to mix/match them, as well as having perhaps far greater quantities of the same category that actually spawns very little.

**Version**
0.9.701.0 (Last tested version)

**Comment by Kaillera** [comment]
That's weird,  I use double item fill tags for lots of mine, and they do mix.

**Comment by NilanthAnimosus** [comment]
I'll have to test it later, and if thats the case I'll just close this c :

**Comment by NilanthAnimosus** [comment]
Closing this, does seem to use multiple tags at once, so I can only assume in the previous version I must have made a typo with some of the labels a few times.
