### ISSUE TITLE
[Bug] [Polish] Character "Stain" in Character Mode

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2101]
In the sub editor, the "Character stain" in the top left of the screen (usually behind the health bar) is visible when in Character mode. Noticeably obscures some of the screen.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/565042a29c01b1312fbcaf125c9d93df3980fada

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
