### ISSUE TITLE
[Bug] [New UI] Character Editor borked on lower resolutions

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2102]
Essentially the top-right tab that lets you select the characters is broken as it goes offscreen on 1024x576.
![2020-01-31-121726_323x347_scrot](https://user-images.githubusercontent.com/47284081/73563718-a8842c80-4423-11ea-83f1-b8b84be042a2.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/173642a7418dac428a26eb47df0cc25555e88f8e

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
