### ISSUE TITLE
[Feature Request] Auto-Outfit Crate Containers with crates

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2103]
It would be nice if instead of spawning so many crates at the cargo spawnpoint, crate containers could have a "cargo" tag that let them be outfitted with as many containers from shops as possible. if there are too many crates, the crates could just be spawned at the normal cargo point.

**Comment by ezjamsen** [comment]
Duplicate issue: 1340 in barotrauma-development
