### ISSUE TITLE
[UI] [Bug] [Low Res] Word wrapping errors for tooltips

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2104]
On lowest resolution, if a tooltip wraps by one word in the bottom-most line, the box height will not account for it, and the text will go out of bounds
![2020-01-31-211830_261x88_scrot](https://user-images.githubusercontent.com/47284081/73586208-67b20500-446f-11ea-9312-b6d442a1b838.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c679e512c1536cd1750b220b68450ef38ac2475a

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
