### ISSUE TITLE
[Polish] [New UI] Sub Editor Category Header should have a "Filter" header, Switch to "All" when clearing filter

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2105]
![2020-01-31-213443_1010x316_scrot](https://user-images.githubusercontent.com/47284081/73586355-98933980-4471-11ea-98dc-d4298462bcfd.png)
Extremely nitpicky, but currently the sub editor's header can be innacurate in that the header will say "equipment" or any other category when things are actually being filtered by the filter bar. It would be nice if there were just a header that said "filter".
Really minor but i can imagine maybe new players forgetting that they typed something into filter, and then wondering why electrical has so few items that aren't electrical.

**Comment by hubismal** [comment]
![2020-01-31-214052_1003x259_scrot](https://user-images.githubusercontent.com/47284081/73586417-6209ee80-4472-11ea-936e-4b19891a07cc.png)
This is further emphasized by the fact that when you delete whatever you typed in, the header stays there when what's being displayed is literally the "All" category, so i'll add having "all" show up as a header when backspacing as part of the feature request.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c0a40101f4d173a7bd8b3b9f6bbab1a455313c11

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.

**Comment by Rokvach** [comment]
Pulled this back to ToDo as I noticed the selected state of a category is bugged

If you select anything  else than All it will highlight all the categories as if they were selected.
![selectedstatebugged.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/31465e80-1947-4964-a22d-75f405574509)

@Regalis11

**Comment by Regalis11** [comment]
Should be fixed now https://github.com/Regalis11/Barotrauma-development/commit/7bacb1bcc3937249a57bc579f5110471683639a7

**Comment by Rokvach** [comment]
Tested, working. Moving to Done.
