### ISSUE TITLE
[Feature Request] Make Structure items gray, but have them colored by default

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2106]
The ability for every item in this game to be colored is currently wasted on the fact that most items like shells and walls have colors already a part of their texture.
This is not a new idea (and might even be a duplicate, sorry if it is), but it would allow much more creative freedom if items like sub walls, shells, and were actually greyscale sprites colored in with the game's texture color feature, which would allow sub builders greater customization than constantly having the same blue-shell brown walls over and over. The white legacy walls are sort of like this but they're pretty plain looking.
There might be something i'm overlooking, so please do comment if you have any qualms. jesus did i really just use the word qualms?

**Comment by Regalis11** [comment]
The problem with making all the structures gray and coloring them by tinting the whole texture is that the entire structure will have the same tint. This isn't a problem with some of the structures (like the shuttle pieces or the legacy walls, which are close to one-colored anyway), but for instance the bluish exterior wall pieces wouldn't look as good in my opinion:

![TINT](https://user-images.githubusercontent.com/14351070/73610017-d57b3f80-45db-11ea-89c9-48e70da49ac6.png)

We could consider making some of the structures grayscale or closer to grayscale, but probably shouldn't do this on all the structures. @IiroEnges any thoughts on this?

**Comment by NilanthAnimosus** [comment]
If this was done however, I'd probably be sailing singing "We all live in a yellow submarine, yellow submarine..." for half my journey, much to everyone else's irritation for recolouring submarines to such bad taste.

Jokes aside though, existing item colours do harm our capability to recolour them as stated, and I do often try to recolour items to find most of the time only a very small range of colour changes works well for them.

Perhaps it could be somehow possible to convert a sprite into greyscale as an option (?) through code somehow? I probably sound like a lunatic for suggesting such but I don't know what the limitations would be to do that even if it loses the more specific and subtle changes in detail.

or...if it is reasonably possible we could use multiple separate sprites, then colour each sprite individually (?), such as one hull piece being made of 1 to (insert number) tintable zones (as to have  separate sprites overlayed to each other to allow better colour changes) - Now that, would be almost more amazing while retaining more details and I am not sure that would make the draw part of most items more intensive or memory consuming spritebatch wise, but if it wasn't a huge hit that'd be my thoughts on this.

I think the latter may be a way around multi-coloured objects though, though probably far more difficult to achieve, as an option though it seems nice on paper with limited understanding. plus those making custom wall pieces could use said system before the main game implemented any texture changes at all, if it seems to be a reasonable concept for this.

**Comment by hubismal** [comment]
Agreed with Nilanth. Have you considered using palletes reg? everything in this game is colored in a way where it only uses at most 4 distinct colors.

**Comment by Regalis11** [comment]
We're are closing feature requests from the issue tracker, moving some of the feature requests to our private repository. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line.

From now on, please post your feature requests on Discord, the Collaboration section on the Barotrauma forums or the Steam discussion board.
