### ISSUE TITLE
[Feature Request] [Sub Editor] Recovery/Temp Sub File

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2107]
probably a duplicate but i can't risk this feature not at least being requested. just lost like 2 hours of work to a wiring-related crash. something like "barotruama detected abnormal termination, would you like to recover your work?". you know, what GIMP does. maybe an option to also just load the temp file from the load menu in the sub editor too just for people who somehow accidentally quit.

**Comment by hubismal** [comment]
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/4142194/crashreport.10.log)
oh and uh here's the crashreport, i was just wiring and deleted all the nodes on the wire by right clicking them.

**Comment by Regalis11** [comment]
Fixed the crash in https://github.com/Regalis11/Barotrauma-development/commit/ddc61ad2d446a14721cd0a9689db8e57664ada56 (not yet included in the unstable build), but autosaving or at least saving when the game crashes is still something we should definitely implement.

**Comment by 3e849f2e5c** [comment]
Auto saving implemented in https://github.com/Regalis11/Barotrauma-development/commit/fc4c92f3c8c82f80b784da242e71446dbc383277 which should provide the desired functionality.

The sub editor now automatically saves the submarine into a temporary file every 5 minutes which can be recovered in the "open" menu.
![](https://kosblue.com/e/lvxtab.png)

Referencing issue https://github.com/Regalis11/Barotrauma-development/issues/1069 "Auto save"

**Comment by Rokvach** [comment]
No issues, closing.
