### ISSUE TITLE
[Sub Editor] [Bug] Submarine name can get cut off

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2108]
Self explanatory
![2020-02-01-013829_266x51_scrot](https://user-images.githubusercontent.com/47284081/73588838-9e9a1200-4493-11ea-8a1a-d561e24f4939.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7931c3b2557f1058d9874033a38502060ef65a45 (private repo)

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
