### ISSUE TITLE
[Bug] [New UI] Make Pencil in textbox darker

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2109]
almost self explanatory:
![2020-02-01-133058_68x29_scrot](https://user-images.githubusercontent.com/47284081/73597928-3846db00-44f7-11ea-914e-511bb152dac3.png)
the pencil should be darker here so that it doesn't make the text hard to read in any situation.

**Comment by Regalis11** [comment]
Imo we should instead make sure the text doesn't overlap with the icon (by either restricting the length of the text or by making it scroll if it exceeds the width of the box).
