### ISSUE TITLE
Ошибка при запуске раунда. / Error starting the round.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#211]
В журнале сервера нет ничего об этом. Произошло после чего? Я сам не знаю. Сервер спокойно работал и в один момент произошло это: 
In the server log there is nothing about this. Happened then? I don't know. The server worked quietly and in a moment it happened:
![unknown](https://user-images.githubusercontent.com/33912761/34422190-f9bff024-ec24-11e7-976e-ada9a34e170b.png)

**Comment by Crystalwarrior** [comment]
Index out of bounds error it seems.
