### ISSUE TITLE
[Bug] [New UI] Editor Text field sizes borked

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2110]
![2020-02-01-133334_279x72_scrot](https://user-images.githubusercontent.com/47284081/73597948-80fe9400-44f7-11ea-8b8e-7f9aee1d9533.png)
in some places, the text field is way too small for some reason. It seems like an atlas issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d03ec051e2038418544f2d97f6457fd1a40217d

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
