### ISSUE TITLE
Tonic Liquid floats above the ground

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2111]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Tonic Liquid item floats above the ground

**Steps To Reproduce**
Drop a Tonic Liquid.

**Version**
~0.9.702

**Additional information**
![](https://cdn.discordapp.com/attachments/427654262453960724/673371928198905856/Capture.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5fe4536f20b49890e433f99ac4bf7ef2b2eb52c (private repo)

**Comment by Rokvach** [comment]
Tested, fixed. Moving to Done.
