### ISSUE TITLE
Implement a custodian job order, tweak assistants priorities to be the strongest at it.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2113]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a feature request that is essentially a means to cleanup a submarine where the AI otherwise generally doesn't, without disrupting other AI's too hard or adding tons of complexity to existing orders.

Now that we have items spawning categorically to certain containers, as well as containers marked for certain types of items like oxygen tanks, the next logical step to this is for a means on AI to replenish/recharge oxygen tanks / batteries and such, then to place them at a relevant container.

Generally I've found the AI loves to leave items around the floor of the submarine and at times, you don't want an AI to trek halfway across a submarine just to replenish one tank at a time over fixing a wide array of leaks or gunning fish down. the AI doesn't tend to prepare for anything in advance right now.

If every AI had such an order though as part of their idle orders, with AI's getting a 3 - 4 times multiplier to their multiplier for this type of order. I specify 3 to 4 times because assistants have exactly half the initiative range to other jobs. honestly you would think of these as eager young recruits, whom do not possess wide skills yet and the older seasoned veterans being a but more lazy / leaving it to said assistants.

These objectives could have a single wide-scope objective with several sub objectives which can be expanded and added to with time, much like rescue all and fix leaks having rescue and fix leak.

The difference being the broad objective can be assigned like any order, while at random they may say, trigger an objective to recharge / replace an oxygen tank they carry, or to organize items on the floor like security body armour or empty welding fuel to better locations.

Finally, perhaps consider adding the ability for an AI with this order, to instruct another AI to swap items with them (Both drop and pickup), such as finding one with a half empty oxygen tank and swapping it so their diving mask is full, assuming their own objective does not get it replenished.

I don't think players would mind having their tanks and batteries swapped by helpful assistant AI's either to be recharged.

**Comment by Udrakan** [comment]
This would be really good for singleplayer, removing much of the annoying micromanagement of putting everything back in it's place which is not fun. Having AI use dialogue for this would be great. I spent a significant portion of my singleplayer time just sorting, instead of piloting the submarine and enjoying the game.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1735](https://github.com/Regalis11/Barotrauma-development/issues/1735) via [**ZenHub**](https://www.zenhub.com/)
