### ISSUE TITLE
Unstable - Icon lighting for materials used for crafting when the item exist in your inventory or linked storage looks as if the items were already placed in the fabricator

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2114]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm annoyed by the ghost icons of materials being fully lit up as if the materials already exists on the fabricator when you own it in your inventory or linked cabinets especially when you're already stacking a bunch of material for bulk crafting.

**Version**
0.9.702
Windows

**Additional information**
My feedback would be to highlight and bold the slot border of the ghost materials.

**Comment by Udrakan** [comment]
I agree that it's confusing when Im doing my crafting runs.

**Comment by Rokvach** [comment]
The reason the icon does look like fully lit up is because you can craft items directly from your inventory or the cabinet linked to the fabricator without having to manually move those items in the fabricators input fields. 

Maybe some type of highlight effect around the items which were moved to the fabricator (like in the tutorial) would make it easier for players to understand why it is happening.

**Comment by Kaillera** [comment]
It just looks weird when I have 5 steel on me, but I want to make 4 toolboxes. It looks as if I put in 5, when there was only 4.

**Comment by Rokvach** [comment]
That sounds like a oversight, I don't think it should add the items in automatically if you don't have all the necessary items, so when moving from an item which you can craft to an item which you don't have all the materials to craft the fields should be emptied of the previous items.

**Comment by Regalis11** [comment]
It doesn't actually add anything to the inventory manually, it simply highlights the slot as if the item was there. But in any case, it is definitely confusing, and tbh I don't even feel it's a necessary feature. We should either get rid of it or change the effect so it doesn't look as if the item was actually in the slot.

**Comment by Kaillera** [comment]
Lets get rid of it please.
![](https://user-images.githubusercontent.com/5086682/73767707-cadcb980-4745-11ea-9266-a4e854f4b3c5.PNG)

**Comment by Regalis11** [comment]
Changed this in https://github.com/Regalis11/Barotrauma-development/commit/a85a1d91746a42cdb49b51cde92a87b1802a741f. Now the slot is just highlighted and animated (simultaneously with the inventory slot where the available item is).

**Comment by Rokvach** [comment]
I don't think scaling the input slots is necessary to indicate that you have an item which would go in there.

I also think that highlighting both the slots suggests that the player needs to move the item in to the slot, which the player doesn't need to do as the player only needs to select what he wants to craft from the list and then press "Create", which is why it was previously shown the way it was because the player doesn't need to move items in to the inputs if they have those items in their inventory, so I think the previous way of displaying the input slots was correct, but it shouldn't color the items which aren't necessary for that specific item to be crafted with (Which was the case on the screenshot above, where it should of only colored one of the steel bars with the aluminium). 

@Regalis11

**Comment by Regalis11** [comment]
>I think the previous way of displaying the input slots was correct, but it shouldn't color the items which aren't necessary for that specific item to be crafted with

I have to disagree on this. Anywhere else in the game, if an item is draw on a slot, it means that item is in that slot. These changes break that logic and make the interface more confusing (as illustrated by this issue report); items are drawn on the slots even if they're not actually there. Same goes the other way around, if we don't color the items that aren't needed to fabricate the item, it would seem as if those items aren't in the slots (even though they actually are). Lets say in that pic above you had five grayed out steel bars in the slots - how would you tell if they're actual items in the slots or ingredients required to fabricate the item?

>We could even show it in an animation -- to showcase it more clearly that the item is already in there

My point is, it is not actually there, and this method of highlighting the slots makes it look as if they were. If we did actually move the items from the inventory to the slots automatically, that'd be a different situation, but that's a whole new can of worms: having items magically disappear from your inventory into the fabricator while your browsing through the list would be even more confusing.

That being said, I don't think the new highlight effect is perfect either, as it doesn't make clear you don't need to manually move the items into the slots. That's still in my opinion less bad than an interface where you can't tell if there's an item in a slot or not. But lets see if we can find some better alternative, maybe @ezjamsen  or @danielasteljoki have some ideas?

**Comment by Rokvach** [comment]
Another way would be to switch entirely in to a ingredients based system, where you don't need to have input slots for items, so it would query the ingredients the player has either in hes inventory or in the linked cabinet and display the information to the player without the player needing to move things around

![ingredientfrabricator.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d2205b27-6559-4949-b566-f4337781b2a4)

**Comment by Rokvach** [comment]
One thing to also take in to consideration is when a fabricator is linked to a cabinet which the player doesn't have access to, the highlight effect then doesn't make any sense to the player as he can't see why the slots are being highlighted. Which again my suggestion above wouldn't have a issue with.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1736](https://github.com/Regalis11/Barotrauma-development/issues/1736) via [**ZenHub**](https://www.zenhub.com/)
