### ISSUE TITLE
Reactor on/off state in sub editor is not saving or loading when starting games with it.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2115]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Noticed by hubismal, one seems unable to save the reactor in the ON state with the sub editor. the indication it is on in character mode is by having the autotemp light up when hitting the red button for on/off. he is saving the submarine with the auto temp light on (thus reactor on) - and it is not transferring to in game, either due to save/load failure or serializable property issues.

**Steps To Reproduce**
use character mode to turn on a reactor then save the submarine, start a campaign or server using the submarine. Reactor will start off.

**Version**
0.9.702.0 - LINUX client (Presumably).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a134abd0ad4095dbb52ebb6bc2042328479a952a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
