### ISSUE TITLE
Unstable - Sub Editor: Visibility of Node Points of Wires is affected by Sprite Depth

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2118]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whether or not you can see the node points of wires is affected by sprite depth of either the wire or the object it's running through.

**Version**
0.9.702

**Additional information**
Makes it hard to clean up wiring after the fact.
![](https://user-images.githubusercontent.com/5086682/73616134-8504e180-45dd-11ea-9eec-9914b8ebe806.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4beb30ed906d1632438a50531b3cd81837250c5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
