### ISSUE TITLE
Баг с редактором субмарин. / A bug with the editor submarines.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#212]
1. Когда я копирую стену или задний фон с изменённым цветом, то на выходе получаю такую же структуру, но со стандартным цветом.
2. Стены имеют стандартный цвет во время игры.
1) When I copy the wall or the background with its color changed, then the output is the same structure, but with a standard color.
2) The walls are standard color during the game.

**Comment by Regalis11** [comment]
Could not reproduce the second issue.

**Comment by CryIz** [comment]
В редакторе / In the editor: 
![image](https://user-images.githubusercontent.com/33912761/34444505-ae7c0fe2-ecdf-11e7-8ce6-623f471649ad.png)
В игре / In the game: 
![image](https://user-images.githubusercontent.com/33912761/34444523-c8b08e38-ecdf-11e7-83bc-096d7105bafb.png)

**Comment by Regalis11** [comment]
Ah yes, I only tested this with the background walls. Seems that the problem is the shader used for rendering damageable walls.
