### ISSUE TITLE
[Feature Request, Unstable] Make random item spawning toggleable serverside.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2120]
Subs can be edited to remove item placement tags, but some option to turn the behavior on and off entirely serverside would be good for the sake of convenience. 
In some situations item spawns might break the intended gameplay of the server, particularly spawning of weapons on the sub or mudraptor eggs.

**Comment by Kaillera** [comment]
The problem currently with that is that all the containers in vanilla sub are almost completely empty. The moment you turn it off, the sub will have nothing to work with on them.

**Comment by NilanthAnimosus** [comment]
I don't see that as a problem, Imagine this as an option on a server that could say, remove the vanilla submarines as an option yet uses prestocked submarines created by players.

or as a more hardcore campaign. in the end of a day its an option for a players choice and is a thing I want or would implement myself as a mod feature anyways if it wasn't in the vanilla game.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1737](https://github.com/Regalis11/Barotrauma-development/issues/1737) via [**ZenHub**](https://www.zenhub.com/)
