### ISSUE TITLE
[bug] Label items mysteriously override depth of specific decorative wall items

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2122]
very odd issue. it would appear that icons don't show up when you're looking directly at them.
![2020-02-02-184451_230x236_scrot](https://user-images.githubusercontent.com/47284081/73632916-d97e8000-4622-11ea-9925-4f6fc969ef99.png)
look very closely at this image. the "preview" that appears in transparent LOS mode actually does show the engineering icon, but for some reason it cuts off when it goes into my characters "real" FOV. there isn't anything wrong with the sprite depth, and the icon appears properly in the editor. the icon is in front of a stretched out label.

**Comment by hubismal** [comment]
nevermind, it looks like there's just some weird depth jazz going on. looks like labels go in front of very specific decorative "wall" objects all of the time. here's an example:
![2020-02-03-012655_349x326_scrot](https://user-images.githubusercontent.com/47284081/73633452-6118be80-4624-11ea-9c0c-b130bad26b02.png)
here's in the subeditor
![2020-02-03-012705_394x334_scrot](https://user-images.githubusercontent.com/47284081/73633453-6118be80-4624-11ea-9e85-907adb84d299.png)
here's in the game. label was set to depth of 0.999.

**Comment by Kaillera** [comment]
#2038

**Comment by Regalis11** [comment]
This is not really a bug, but a side-effect of items not being visible through the FOV effect. There seems to be something wrong with the render order though, as some of the entities aren't rendered in the same order in-game and in the sub editor. #2038 addresses that specific issue though, so I think we can close this one.
