### ISSUE TITLE
[Bug] Unable to switch to Opaque LOS mode

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2123]
opaque line of sight doesn't work, and instead uses transparent, at least for me. Platform is linux, build is the latest unstable.

**Comment by Regalis11** [comment]
Doesn't seem to happen on Windows, so this seems to be a Linux (and maybe Mac) specific issue

**Comment by Regalis11** [comment]
I unfortunately wasn't able to reproduce this, all of the LOS modes seem to work on Win and Linux

**Comment by Regalis11** [comment]
No known steps to reproduce, closing this for now
