### ISSUE TITLE
Unstable - Sub Editor: Copy Pasting, Mirroring, and Flipping group of items issues

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2125]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. When using Ctrl+M, or Ctrl+N to Flip and Mirror or Copy Pasting a group of items in sub editor, the items gets moved to an unknown place in the editor. For Flip and Mirror, Flip or Mirror again will bring it back to it's original location. Sometimes it's unknown where Pasting ends up.

2. When Mirroring or Flipping group of items, the wires will be displaced from the object. You can find the wires if you try real hard in order to bring it back to the objects they belong to, but it's tedious and easier to just delete the components and remake the entire logic.

**Steps To Reproduce**
Copy Pasting, Ctrl+M, or Ctrl+N on group of objects, preferably with wires attached to them too.

**Version**
0.9.702

**Additional Informations**
I think I would prefer if pasting ends up where the cursor is?

**Comment by hubismal** [comment]
to clarify, i've had the first issue before and i'm pretty sure they're inter-related. if i'm not mistaken when the wire gets massively displaced it screws up the origin of the rotation and makes it much bigger than it actually is. that's kind of just a theory but there's something that screws up the origin and i wouldn't be surprised if it were the wire.

**Comment by Kaillera** [comment]
Pasting a singular item may also be placed somewhere far away from the screen.

**Comment by Regalis11** [comment]
Issue 1 fixed in https://github.com/Regalis11/Barotrauma-development/commit/e59694a2a752aab93e1c6c7a17817936e082e550
Issue 2 fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d8f671597bd85635d9b579df69693830e08bc4a

**Comment by Kaillera** [comment]
Wow these fixes! this made paste flip and mirror so much better!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
