### ISSUE TITLE
[Feature Request] - Unstable Sub Editor

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2127]
**Description**
As I am making a submarine right now in Unstable build, there's 2 things that really bothered me in comparison to 0.9.6.

1. This one is an easy one: When pressing the Character Mode or Wiring Mode button to activate the mode, pressing it again will bring it back to Edit Mode. People who are used to the old toggle buttons will instinctively press these again trying to go back. I've done this many time, and I feel the pencil button is kind of just there to go back from those two other buttons anyways.

2. This one is probably because I am very used to the old editor, but as a person that likes to press the Visibility buttons a lot, I feel like the Visibility toggles should stay on the left side of the screen like 0.9.6 instead of just hanging from the top center currently (Which does get in my way).

**Version**
0.9.702

**Comment by Regalis11** [comment]
Request 1 implemented in https://github.com/Regalis11/Barotrauma-development/commit/bdb3eaf33232536094a9d57f3cb2148d9737f115

**Comment by Kaillera** [comment]
#1 implementation definitely made workflow easier.
