### ISSUE TITLE
Unstable - Orca's shell piece misalignment

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2129]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This shell piece is lower than the other ones.
![](https://user-images.githubusercontent.com/5086682/73684508-50069680-4692-11ea-97e1-1e19d14e2a8b.PNG)

**Version**
0.9.702

**Additional information**
I DON'T EVEN KNOW WHY I AM NITPICKING THIS!

**Comment by ezjamsen** [comment]
fixed on dev.

**Comment by Rokvach** [comment]
Tested, Moving to Done.
