### ISSUE TITLE
Unstable - Automated Docking Hatch Assembly misalignment

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2130]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One pixel offset
![Capture](https://user-images.githubusercontent.com/5086682/73685146-9c9ea180-4693-11ea-906a-5dd1a1445ec6.PNG)

**Version**
0.9.702

**Additional Information**
Any vanilla sub that has used the assembly is also affected, as well as old custom ones.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/37bf7a615ff1acc3f7cdb0f517f7be94643a58bc

**Comment by Rokvach** [comment]
No issues, closing.
