### ISSUE TITLE
Crash in AIObjectiveFindSafety

### ISSUE THREAD

**Issue by jembit** [Regalis11/Barotrauma#2131]
-- Just trying to play game with my own shuttle . i'm at the engine room checking load on my junction box . It's the fifth time happened to me with the same shuttle

------------------------------------------------------------

Barotrauma Client crash report (generated on 04-Feb-20 5:15:43 AM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

82D5F98C9FFDE58E64CF140A88952446

Game version 0.9.6.0
Graphics mode: 1600x900 (Fullscreen)
Selected content packages: Vanilla 0.9
Level seed: VortaHarmonia Linea
Loaded submarine: matamata (66373CAA2D6AFDA868A02566962105D8)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Radeon RX Vega
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object.
Target site: Void <Act>b__5()
Stack trace: 
   at Barotrauma.AIObjectiveFindSafety.<>c__DisplayClass28_0.<Act>b__5()
   at Barotrauma.AIObjectiveGoTo.Act(Single deltaTime)
   at Barotrauma.AIObjective.TryComplete(Single deltaTime)
   at Barotrauma.HumanAIController.Update(Single deltaTime)
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam)
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[04-Feb-20 4:19:12 AM] Logged in as matarabun (SteamID STEAM_1:0:37998400)

**Comment by Kaillera** [comment]
From my point of view, you may not have any waypoints for the starting crew members in campaign to go around in?

**Comment by jembit** [comment]
I have all it needed, i have waypoints, spawn, cargo etc

**Comment by itchyOwl** [comment]
It shouldn't crash in any case.

**Comment by itchyOwl** [comment]
I went through AIObjectiveFindSafety class and added some safety checks, but I'm unable to point out any single line that could lead to a null reference exception. It's a pity that the exact line is missing from the log (which happens quite often, not sure why).

Would help a lot if you could provide the exact steps to reproduce this, if there are any. Else I just have to trust that my attempted fixes work or that we or someone elses faces the same issue and we can get more info about it.

**Comment by NilanthAnimosus** [comment]
Its strange its missing from a windows version on top, as I always thought the missing line numbers was more of a linux / mac thing at times (But im noting an NT version there).

The real shame is he reproduced it 5 times using a shuttle. which makes me wish we had the submarine file for reproduction.

**Comment by itchyOwl** [comment]
Yeah that could help too.

**Comment by jembit** [comment]
Unfortunately the original sub file has been modified quite a lot since crashed. Every time i saved the file and played it works fine, but today it happened again, but different situation, this time the shuttle stopped at the left (ceiling?) of the destination because i set it to autopilot, i didn't do nothing because i fell asleep, when i awake the game crashed. After that i try to reproduce it, autopilot mode and go to destination without doing anything but this time it didn't happen, so i shot all the crews, they're bleeding, i try to make them to follow me and get out of the hatch to the ocean then it crashed...and

Short answer: I can't reproduce it with the same situation like the one i've posted, set to autopilot, checking the load of the junction box and connecting the cables

I'll let you know if i can reproduce it over and over

**Comment by jembit** [comment]
How to reproduce:

1. Start **new game** Campaign
2. Choose **matamata-bugfind** shuttle
3. Choose '**no mission**'
4. **Open the custom hatch** that connected to the dock
5. Choose '**power on**' from navigation terminal to start the engine
6. Now force **undock**
7. **Crash**

[matamata-bugfind.zip](https://github.com/Regalis11/Barotrauma/files/4156924/matamata-bugfind.zip)

**Comment by itchyOwl** [comment]
Excellent! Was able to reproduce the issue and confirmed that it's already fixed in the current dev version by Regalis11/Barotrauma-development@7140d0a. Thank you jembit!

**Comment by Rokvach** [comment]
Closing as the fix has been confirmed to be working.
