### ISSUE TITLE
No crafting timer when fabricator is powered from a relay.

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#2133]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a fabricator or deconstructor is receiving its power from a relay, the fabricator will produce (deconstructor will deconstruct) the items without any crafting delay

**Steps To Reproduce**
connect a fabricator & deconstructor to a relay and supply the relay with power.

**Version**
0.9.6.0 Windows

**Additional information**
Theory is that the junction boxes will reserve power for the relays set "max power" in the grid and even if the fabricators is not in use, the power is reserved in the grid and will instantly be supplied as long as it is available on the grid. Why it affects crafting timers, I don't know, perhaps the speed in which the fabricator can be replenished with power it consumed may boost or nerf its crafting time?

**Comment by NilanthAnimosus** [comment]
I believe crafting timers are multiplied by voltage, perhaps a relay is doing something weird with voltage values in your setup..

**Comment by FLundin** [comment]
Would you care to have a look on my build?

**Comment by FLundin** [comment]
Or could you try it in a build of your own and see if it can be reproduced?

**Comment by FLundin** [comment]
> I believe crafting timers are multiplied by voltage, perhaps a relay is doing something weird with voltage values in your setup..
> 
> They do not store power, or have an X out of Y power requirement to craft, but go off voltage to effect crafting speeds.

Could you try it in a build of your own and see if it can be reproduced?

**Comment by FLundin** [comment]
I havent really messed around with the voltage on the fabricator, deconstructor nor relay. They should have the default settings.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e014824069cc2d44d1506f12e2b2eb2d1e4dfaa

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
