### ISSUE TITLE
Unable to specify which of the top multiple docking hatches on the sub as the "main" one

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2134]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players are unable to specify which top docking hatches should be used by the game when there's multiple of them to start off docked to the station with.

**Steps To Reproduce**
Have multiple top hatches on a submarine. Load a round with it.

**Version**
~0.9.702

**Additional information**
I have an irregular shape submarine in the works, and was hoping if there was some way to specify which one they should always use to start the round with at the station (hopefully being able to specify multiple as well). The reason why I have multiple ones is because I have a shuttle that I would like to be able to shift around.
![](https://user-images.githubusercontent.com/5086682/73707782-7a744600-46ca-11ea-8fa3-b526303f0a87.PNG)

**Comment by Kaillera** [comment]
![](https://media.discordapp.net/attachments/427654262453960724/674077521825890304/Capture.PNG)

Though I can trick the game by occupying the hatches, I wanted them to start at the bottom.

**Comment by Regalis11** [comment]
Added a "MainDockingPort" property to docking ports in https://github.com/Regalis11/Barotrauma-development/commit/a2bd00339686f3246ffe11115ebfa89e0f21a41a, moving this to Review/QA

**Comment by Rokvach** [comment]
No issues, closing.
