### ISSUE TITLE
Going through walls.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2135]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you rub yourself against particular thin walls of say basic walls or shuttle shells, you may be able to phase through them.

**Steps To Reproduce**
Three most infamous spots are the Station angle brackets next to the docking port (Especially the left brackets), The ceiling of the Humpback reactor room when it's flooded, the floor of the Orca's crew cabin or the right wall of Ballast C. I've seen players get stuck in these spots (Myself included, Humpback in unstable recently) occasionally.

**Version**
~0.9.702

**Additional information**
F to those who get stuck in those places.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/886a5474d2ebe37695e897d7dacac2f202374b56

**Comment by Rokvach** [comment]
Couldn't find any issues with this, closing.
