### ISSUE TITLE
[0.9.703] Sub Editor: Having to name your sub every save when it already has a name.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2136]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When saving sub with the sub editor, you have to rename your sub because the name bar is blank every time in the save interface.

**Version**
0.9.703
Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/081c347f57745f16a9a0e43bcc34122d9f6c7b5f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
