### ISSUE TITLE
[0.9.703] Server Settings changed in game is not saving to serversettings.xml

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2137]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Server Settings that were changed with the in-game hosting doesn't save back to serversettings.xml. Will default back to serversettings.xml every time the server is hosted in the game.

**Version**
0.9.703
Windows

**Comment by Regalis11** [comment]
I unfortunately wasn't able to reproduce this, the settings seem to be saved when the server is shut down. Could it be that the server crashed or was forcibly closed?

But in any case, I think we should make the server save the settings more often than just when quitting.

**Comment by Kaillera** [comment]
On that day:

I've changed settings and disconnected from the bottom left button of the lobby. Host again and everything was reset back.

I've changed the settings and went back to the main menu from the ESC menu, didn't saved it either.

I've started a round with the new settings, ended the round and disconnected from the bottom left button of the lobby again. Hosted again and it didn't save.

In the end I just ended up modifying the serversettings.xml afterward

**Comment by 3e849f2e5c** [comment]
This only happens when the client is connected to Steam and by the looks of it the entire disconnect function is not being called. Either the the server is being killed too harshly when running SteamP2P or the closing event is not being handled. Lidgren servers have the expected behavior and save settings when the server closes.

**Comment by 3e849f2e5c** [comment]
I have fixed the initial issue for now in https://github.com/Regalis11/Barotrauma-development/commit/2ba05c7194f0fd76465567023e6d9ed270cc6c79 by saving settings to a file as soon as they are changed but it's probably better to look into why the shutdown function isn't being called on SteamP2P servers.

**Comment by Kaillera** [comment]
Seems to be working. Closing.

**Comment by Rokvach** [comment]
I think the issue @3e849f2e5c pointed out might still need some attention, re-opening the ticket

**Comment by Regalis11** [comment]
Created another ticket about Disconnect not being called in our private repo https://github.com/Regalis11/Barotrauma-development/issues/1667, this one can be closed.
