### ISSUE TITLE
[Feature Request] Assign Commands to Characters from the Character List

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2138]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So now that we have a player list back in 0.9.703, there should be a shortcut to assign commands quickly to that character by clicking or Mmbing their name.

**Version**
0.9.703

**Comment by ekqvist** [comment]
Great minds think alike! I suggested this very same thing a few days ago and we're looking to implement it for the next unstable build!

**Comment by ekqvist** [comment]
Implemented in Regalis11/Barotrauma-development@bb1ef4d

**Comment by Rokvach** [comment]
Pointed out some UX issues with this on a separate ticket, moving this along as the functionality does work correctly. Closing.
