### ISSUE TITLE
Идея для редактора субмарин. / The idea for the editor submarines.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#214]
Есть предметы, провода, тот же самый задний фон, которые стоят не так, как хотелось. Можно добавить функцию для каждого предмета, которая будет определять положение, к примеру, шкафа. Что будет находиться за ним, а что перед ним. Временами пытаюсь выкручиваться как только угодно, лишь бы добиться желаемого.
There are items, wires, the same background, which are not as desirable. You can add a function for each subject, which will determine the position of, for example, of the Cabinet. That will be for him and that before him. Sometimes trying to get out as soon as anything just to get what you want.
![barotrauma niledit 2017-12-29 12-35-26-192](https://user-images.githubusercontent.com/33912761/34434096-cf3ef5aa-ec94-11e7-8fa3-a9d44e752db1.jpg)

**Comment by CryIz** [comment]
Добавил/added 03.01.2018:
![image](https://user-images.githubusercontent.com/33912761/34502763-1acde280-f026-11e7-8c03-06fa7be90444.png)

**Comment by Regalis11** [comment]
Closing this due to #249
