### ISSUE TITLE
[0.9.703] Can dismiss a dismissed character, plus no icon.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2140]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can dismiss a dismissed character. Also there's no icon for it.

**Steps To Reproduce**
Dismiss a character from an action. A new button should be next to it that is invisible.

**Version**
0.9.703
Windows

**Additional information**
![](https://user-images.githubusercontent.com/5086682/73770033-b8647f00-4749-11ea-9c6e-f794254b584f.PNG)

**Comment by ekqvist** [comment]
Thanks for the report! This happened in multiplayer, right? Do you have a reliable way of reproducing this? I managed to reproduce it once in multiplayer, but haven't managed to reproduce it again yet.

**Comment by Kaillera** [comment]
Yes it was multiplayer

**Comment by ekqvist** [comment]
Thanks, I've managed to reproduce it multiple times now so I'll look into it

**Comment by ekqvist** [comment]
Should be fixed in `dev` as of Regalis11/Barotrauma-development@c9bc363

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
