### ISSUE TITLE
[0.9.703] Custom Subs - Downloading a new version of the same sub from previous version causes download loop.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2141]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players with an older version of a custom sub, downloading a new version of it in 0.9.703 causes a loop where the server keeps asking the player to download the sub.

Hosting a server with the custom sub, and then editing it, and rehosting a server with the new version of the custom sub also causes the host to get this loop.

**Version**
Sub 0.9.702 going to 0.9.703. I doubt it mattered tho.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e041771d75b4e0c98f2c494c319684fe704302bd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
