### ISSUE TITLE
[0.9.703] Typhon2.airlock Bottom Left Pump still missing a wire to Water Detector.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2142]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bottom Left Airlock in Typhon 2 is still missing a wire to Set State from the Water Detector behind it.

**Version**
0.9.703

**Comment by ezjamsen** [comment]
Fixed in dev.

**Comment by Regalis11** [comment]
Not fixed yet

**Comment by ezjamsen** [comment]
Fixed now.

**Comment by Rokvach** [comment]
No issues, closing.
