### ISSUE TITLE
Unstable - No Max HP indicator for the health bar

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2143]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players are unable to tell what level their health really is other than the color at the top left of the screen without pressing H.

**Version**
0.9.703

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a8975a88865bfb7fa8cde849830a16d61ef647d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
