### ISSUE TITLE
[9.0.703] Store Category Button's Text are clipped in multiplayer lobby.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2144]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![](https://user-images.githubusercontent.com/5086682/73785986-68e07c00-4766-11ea-8d73-5dc95748fa79.PNG)

**Version**
0.9.703

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/93704eb15da1bc55a432c6114ff0a77c20536d70

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
