### ISSUE TITLE
Unstable - Fentanyl in auto spawner supplycabinet is common

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2145]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fentanyl is pretty common in the auto spawner supplycabinet that it's easy to get enough to OD anyone.

**Version**
0.9.703

**Comment by Udrakan** [comment]
It should definetly get nerfed imo. It's very dangerous drug and anybody can kill with it within seconds, either intentionaly or not. I suggest replacing opiate-based drugs with raw opium for supply cabinets. Leave morphine and fentanyl in medical for safety, clarity and ballance.

**Comment by ezjamsen** [comment]
fixed in dev. reduced spawn rates for fent and morphine, increased spawn rates for crafting materials to compensate.

**Comment by Rokvach** [comment]
Tested, no issues. Closing
