### ISSUE TITLE
[Issue] [Bug] Some important lines don't show up on lowest resolution

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2147]
![2020-02-04-163142_209x418_scrot](https://user-images.githubusercontent.com/47284081/73793465-10ac7880-476c-11ea-8b01-12dbba75849f.png)
![2020-02-04-163133_617x478_scrot](https://user-images.githubusercontent.com/47284081/73793466-10ac7880-476c-11ea-8b7d-d030cd762d1d.png)
looks like the atlas line thickness was decreased? everything was fine in the previous scaling update that juan slipped me for linux.

**Comment by Regalis11** [comment]
Yeah, the problem was that we made the outlines of the sprites a little thinner in the atlas, and on such a low resolution scaling them down makes them disappear completely.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e7cc3078c090f584d08836a2bf87c2c3809db74

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
