### ISSUE TITLE
[Issue] [Bug] Chatbox doesn't recollapse 

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2148]
When the chatbox is collapsed, it used to be you pressed r to type your message with it open and pressing escape or sending a message would recollapse it. Functionality seems to have been lost.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e4c42ee47eb6eb1e9aec6d9674d029c15487353e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
