### ISSUE TITLE
[Bug] [Lowres] Lowres fonts unreadable

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2149]
![2020-02-04-164513_231x248_scrot](https://user-images.githubusercontent.com/47284081/73794321-cb894600-476d-11ea-8060-56ffaee8d163.png)
this will be updated with other things i find that are borked

**Comment by itchyOwl** [comment]
Should be better in the next update (1280x720):
![image](https://user-images.githubusercontent.com/5370738/73837339-ec0eda00-4819-11ea-862a-05d8d3e693a1.png)

**Comment by Rokvach** [comment]
No issues here, closing.
