### ISSUE TITLE
[Unstable 0.9.703.0] Weird shadows on Humpback's railgun obscure view

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2151]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An incorrect shadow is obscuring view from Humpback's railgun periscope.
**Steps To Reproduce**
Start a level in humpback, use the railgun periscope, observe the bad shadow.

**Version**
0.9.703.0

**Additional information**
Same issue could be on other submarines as well, we just played on Humpback tonight.

**Comment by Kaillera** [comment]
The humpback's railgun is embedded inbetween 2 brackets which obscures the LOS.

**Comment by Regalis11** [comment]
I think this is by design to limit the range of the railgun, @danielasteljoki?

**Comment by danielasteljoki** [comment]
I agree that it looks a bit weird. Adjusted the railgun a bit to get rid of incorrect-looking shadow.

**Comment by Rokvach** [comment]
No issues here, closing.
