### ISSUE TITLE
[Unstable 0.9.703.0] Entire shopping cart get's highlighted when single item gets changed

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2152]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When somebody changes amount of items bought, instead of that particular line getting highlighted, the entire list gets highlighted, as seen on the picture.
![bug3 list highlight](https://user-images.githubusercontent.com/59519434/73904302-e78b0580-489b-11ea-8b61-34519f6689a0.png)

**Steps To Reproduce**
Start campaign, go to store, select multiple items to buy, change amount of items bought in the left side of the screen, observe what gets highlighted. I was watching the list as Kai was changing the amounts, maybe the one doing the shopping will see it correctly, not sure.

**Version**
Unstable 0.9.703.0

**Additional information**
Not sure what shopping will look like in the new version, this bug might be irrelevant.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d07fc0dafe09eb59a008dc8804937dba2812005e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
