### ISSUE TITLE
[0.9.703] Deconstructor Interface and Items with subinventory

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2153]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The deconstructor needs a bit more space between the input and output slots to account for the subinventory bar.
![Capture](https://user-images.githubusercontent.com/5086682/73904388-e50fb800-4869-11ea-9d80-ce41a14fb03a.PNG)

**Version**
0.9.703

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/664902c3bfba110d21dc40a068b6d69833e916a2
![](https://kosblue.com/e/dhetp.png)

**Comment by Rokvach** [comment]
No issues here, closing.
