### ISSUE TITLE
[0.9.703] Dragging subinventory window also drags items behind it.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2154]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're dragging the subinventory window to reposition, it will also drag items from other inventory like cabinets if they overlapped.

**Version**
0.9.703

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c1cc2e232396bca1b1e68cfd0c685ef9b0c38f5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
