### ISSUE TITLE
[Unstable 0.9.703.0] Significant FPS drop when using diving suit

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2155]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
FPS drops significantly when I get into a diving suit and returns to normal when I exit the suit.

**Steps To Reproduce**
Monitor performance when you enter a suit in a match.

**Version**
Unstable 0.9.703.0

**Comment by Regalis11** [comment]
Seems to have been fixed by https://github.com/Regalis11/Barotrauma-development/commit/c5bb538

**Comment by Rokvach** [comment]
Tested, there hasn't been any sudden FPS drops in the 704 unstable version. Closing.
