### ISSUE TITLE
[0.9.703] Hammerheads likes to flee a lot.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2156]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hammerheads tends to flee and rub themselves against the map walls instead of ramming the sub. They will generally try to find their way through every small crevices to run out of the map so that it makes it pretty hard to hunt them down for during missions related to them.

**Steps To Reproduce**
Select Hammerhead related missions.

**Version**
0.9.703

**Additional Informations**
I'm not sure if it was intentional for them to act like this, but it does make it the second case of ever having to exit the sub to complete a mission (first being ruins). Having to hunt them down by swimming and gunning. They're pretty easy to kill with military guns 1 vs 1.

**Comment by Udrakan** [comment]
Can confirm.

**Comment by itchyOwl** [comment]
If this only happened in the unstable version, could you check if it's still an issue? There was a bug that made all the creatures flee when they were damaged. But it's fixed already.

**Comment by Kaillera** [comment]
This is still happening in 0.9.7 5adfe9a82. They keep running out of the map when we try to hunt them down.

**Comment by itchyOwl** [comment]
It seems that the latest (late) fix was made after that. It's included in the build that we sent for QA.

**Comment by Kaillera** [comment]
Aside from the Matriarch, mission based enemies don't run away like they used to.

Matriarch can still run out of the map and reach the "Hyper Current" which prevents submarines from following after.

**Comment by Rokvach** [comment]
For Matriarch I think its a design based issue rather than code. Closing ticket as the original issue has been fixed.
