### ISSUE TITLE
Exploding and Piercing bolts

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2157]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When firing Exploding Coilgun rounds, the bolts stops short on bigger enemies like moloch and charybdis, which results in no damage of internal or burn, but just stun.

When firing Piercing rounds, the bolts doesn't damage multiple enemies that it runs through, but bounces off them when hit. Also can't damage molochs when you shoot at their shells with it (Which should be a thing honestly, even for half the damage would be nice).

**Additional Information**
When I was extensively testing these rounds with a friend to see what was the better ammunition choice, we found the regular rounds being the most cost effective, and reliable one, with 2:3 ratio of exploding box to make it easier to kill small targets, and regular one for very big targets. We ruled out piercing ammunition to just be for attacking subs and ruins to maybe hit someone/thing behind it (which you can't tell what's behind a wall to aim with anyways).

**Version**
0.9.703

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f6b64c5:
The damage done by the explosive bolts has been buffed (does direct damage on impact, and additional damage with the explosion). Piercing bolts can go through characters and hit up to 3 targets per shot.

**Comment by Rokvach** [comment]
No issues, closing.
