### ISSUE TITLE
[Feature Request] Physicorium Shell / Ammunition Box / Harpoon

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2158]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
See #2157 about exploding coilgun bolts first.

So Physicorium Shell explodes for awesome amount of damage for 1 bar, which is great! Probably requires nerfing to the recipe though.

Physicorium Ammmunition box deals 15 damage vs 10 from regular coil ammo is their only difference. Shouldn't it also explode a bit like Exploding box?

Physicorium Harpoon deals 20 more damage than regular harpoon, which also kinda sucks for the same amount of materials you can get out of the physicorium railgun shell. Add explosive element to it too perhaps?

Don't forget to nerf the price of Physicorium bar if you're going to buff the products, because they're at a pretty low 200 credit each.

**Comment by danielasteljoki** [comment]
Physicorium shells actually shouldn't explode by themselves, that's an error. Fixed now in dev repo. Buffed the damage a bit to compensate.

**Comment by Rokvach** [comment]
No issues here, closing.
