### ISSUE TITLE
[0.9.703] Running + Opening Doors = Duct Block Noise

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2160]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When running and opening doors, sometimes it makes a duct block opening noise instead of the normal door noise.

**Version**
0.9.703

**Comment by Regalis11** [comment]
This might not be a bug; If someone has just opened/closed the door, it can't be toggled by other players for 1 second. If you try to do so, it will play the duct block noise.

This was added to prevent situations where multiple people are trying to open/close a door at the same time and end up slamming them on each other's faces. Might still need some more work, as it isn't obvious enough what's going on when this happens.

**Comment by Kaillera** [comment]
Ah, I didn't think it was that. It always felt random.
