### ISSUE TITLE
[0.9.703] Status Terminal information tooltip runs off the screen

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2161]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The tooltip for displaying room information can run off the screen.
![](https://user-images.githubusercontent.com/5086682/73933982-98e56780-48ab-11ea-8e50-ee3c4e514501.PNG)

**Version**
0.9.703

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f8ead6919fe8d79994f00450a27e63998e21ae7d

**Comment by Rokvach** [comment]
Putting this here as it is about the same tooltip @Regalis11 

![statustooltip.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b10aaee3-65d8-4710-9e7a-db00f16f2ef7)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/132785bcd77b2ad2b6826da09207ce78e9e10341

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
