### ISSUE TITLE
[0.9.703] Unable to change the color of Sonar Beacon lights + FPS Drop holding it

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2163]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you pick up an enabled sonar beacon, you cannot change the color of the light (Can't change number and doesn't react to +/-). Also there's a FPS drop when holding it with the light interfance up.

**Version**
0.9.703

**Comment by Regalis11** [comment]
Fixed in Regalis11/Barotrauma-development@c5bb538

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
