### ISSUE TITLE
Prevent the use of medical supplies when the patient is wearing a diving suit

### ISSUE THREAD

**Issue by danielasteljoki** [Regalis11/Barotrauma#2166]
A diving suit should prevent all first aid and protect the wearer from syringe projectiles. Whoever is administering first aid should also be able to take the diving suit off to allow for medical care.

EDIT: Diving suits should offer more protection (especially against burn and bleeding) to balance it out.

**Comment by Kaillera** [comment]
On the outside of the sub and in ruins, People will die to water pressure before you can save them.

Can we just go with: There's a injection hole for diving suit somewhere on it and anyone can just stab a syringe to inject through it?

**Comment by Udrakan** [comment]
"People will die to water pressure before you can save them if they do that." - Good
Use rare dry rooms in ruins or drag injured divers back into submarine.
I would this either in the base game or in some kind of hardcore mode.

**Comment by hubismal** [comment]
If there are ever diving suit variants in the future (like what has been teased in the outpost store images), it might be more appropriate to apply this to some kind of diving suit variant. 
(Ex: a diving suit that has 2x the armor and all sorts of damage resistance, but you can't be healed while you're inside.)

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1726](https://github.com/Regalis11/Barotrauma-development/issues/1726) via [**ZenHub**](https://www.zenhub.com/)
