### ISSUE TITLE
[0.9.703] When toolbox is equipped, trying to switch to other items in hotbar gets put into the toolbox.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2169]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to switch item being equipped in your hotbar when a toolbox is equipped will put that item into the toolbox. This makes it very easy to mess up your inventory when you left your toolbox open.

**Version**
0.9.703

**Comment by Kaillera** [comment]
Seems to be a feature to allow guns and tools to equip their ammo/fuel. Although it's annoying for toolboxes.

**Comment by Rokvach** [comment]
Opening this back up as a reminder to handle this correctly with the new inventory.

**Comment by ekqvist** [comment]
Tested to be working correctly now
