### ISSUE TITLE
Bring back Crawler Pounce

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#217]
![2017-12-29_15-03-09](https://user-images.githubusercontent.com/3470436/34453558-026adfa0-ed69-11e7-8814-fb447e1bb854.gif)
I can't believe all they do is just bite your face off. Personally, I feel that crawlers pouncing you down with a minor stun has a lot more of an impact than just a bite that makes your screen red.

Also the damage overlay is wayyy too over the top and ruins your visibility imho.

**Comment by Regalis11** [comment]
The new crawlers can jump again. :)

**Comment by AbominationBanisher** [comment]
our hero
