### ISSUE TITLE
Shopping in Campaign, editting quantity behaviour

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2171]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A lot of people are annoyed by this one, but say you purchase 12 Steel Bars. Suddenly, you want to buy 24 Steel Bars. Normally you would highlight the digits entirely and just press 24, it would still comes out as 12. If you were buying 3, highlighting the digit, and wanted to buy 4 instead, you get 14.

24 > want 3, turns into 13.

It always add the first digit the player wants after resetting the quantity to 1, and after that number.

Now if you want to change the digits in the tenths:
24, you highlight 2 and wanted 34, you would press 3. You get 43.

It will remove the first digit entirely, shift the second digit into the first place, and add on the digit the player wants after the second digit.

**Version**
~0.9.703

**Comment by Udrakan** [comment]
Perhaps clicking into the number field should remove all numbers so you can just input your desired item amount. If you leave it without editing, it should return to original value.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d07fc0dafe09eb59a008dc8804937dba2812005e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
