### ISSUE TITLE
[0.9.703] Singleplayer Campaign - Dismissing/Assigning "Previous Order" from the Crew List makes you control them

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2172]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clicking to Dismiss or Assigning the previous order button will make the player control the crew member.

**Version**
0.9.703

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
