### ISSUE TITLE
[0.9.703] Unable to assign Crews to Operate X in a Shuttle when Shuttle is not attached to Sub.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2175]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have a crew inside a shuttle that came with a submarine, you are not able to assign them to Operate equipments in the shuttle when the shuttle is no longer docked to the submarine (The shuttle is no longer on the operate interface)

You have to assign everything beforehand when they are docked, and there's still limitations after that, like being unable to tell them to return hold or steer ahead afterward.

**Version**
0.9.703

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1725](https://github.com/Regalis11/Barotrauma-development/issues/1725) via [**ZenHub**](https://www.zenhub.com/)
