### ISSUE TITLE
[0.9.703] Bots cannot reach O2 generator on Orca for repairs, running back and forth

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2179]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bot's can't reach the O2 gen. They can get to it and repair it when I help them by holding them with H and they can leave the area afterwards without issues, but when they want to go in, they start running back and forth indefinetly.
![bug4 orca o2](https://user-images.githubusercontent.com/59519434/73967147-a5070e80-4917-11ea-936c-1b7ddeb6e35d.png)

**Steps To Reproduce**
Start any match on Orca with bots.
Damage O2 generator in any way possible.
Have bot repair the generator.
Observe their behaviour.
**Version**
0.9.703 Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4184deb10eca697e5f2d5d28788e908777d9067b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
