### ISSUE TITLE
Идея с именами игроков. / The idea with the names of the players.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#218]
Сегодня я увидел в одной игре такую фишку, что когда ты смотришь, к примеру, на бота, то его имя только при приближении начинает показываться. Я и мои друзья РП-игроки, для нас было бы очень круто это видеть в Barotrauma.
Today I saw in one game a piece that when you look, for example, at the bot, his name only at the approach begins to seem. Me and my friends RP-players, for us it would be very cool to see this in Barotrauma.
![name](https://user-images.githubusercontent.com/33912761/34455046-721f593e-ed87-11e7-92a6-fd3186eb18a9.gif)

**Comment by Crystalwarrior** [comment]
Perhaps it should always be visible but a bit more transparent if you don't mouse over?

**Comment by Crystalwarrior** [comment]
Oh yeah, same could be done for health to reduce screen clutter
