### ISSUE TITLE
[0.9.703] Bots have difficulty using periscope near ladder on Orca

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2180]
**Description**
When bot is in mid deck in right side of the submarine and you order him to man the right gun, it cannot exit the ladder and step onto the platform, falling and grabbing the ladder again indefinetly as can be seen in the gif.
![bug7 orcabotpath2](https://user-images.githubusercontent.com/59519434/73967841-f794fa80-4918-11ea-903b-e8c6039e246d.gif)

**Steps To Reproduce**
Start any round with bots on Orca
Have one of the bots be anywhere middeck right side of the submarine.
Order that bot to man the right gun.
Observe his behaviour.

**Version**
0.9.703 Unstable

**Additional information**
Ordering that same bot in the same situation to man the other gun or do something else results in the bot successfully leaving the ladder and works as intended.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fb10c97af69051ec42ef93e5efd128e969779a1c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
