### ISSUE TITLE
[0.9.6] Crash - ApplyProjSpecific

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2181]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I was playing on a server and got desynced.
Tried to rejoin and spectate and I got this crash.
![crashreport.log](https://github.com/Regalis11/Barotrauma/files/4167356/crashreport.log)

**Version**
0.9.6

**Comment by Regalis11** [comment]
This seems to be a duplicate of an issue we had in the private repo. That one has a bit more details on the bug, so I moved it here: #2182. Should be fixed for the next update!
