### ISSUE TITLE
Battery/Junction box/Supercapacitor indicator bar does not follow when placing upside-down

### ISSUE THREAD

**Issue by jembit** [Regalis11/Barotrauma#2185]
Battery/Junction box/Supercapacitor indicator bar does not follow when placing upside-down (mirror y)

![indicator](https://user-images.githubusercontent.com/13626273/73980253-706c7480-4962-11ea-8463-2c04ebc2a9e2.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/90c20eb982bc6b78831be686297ce1bf7395ff0b

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
