### ISSUE TITLE
Multiplayer campaign is very much bugged

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#219]
It seems like it's very hit or miss, sometimes it works okay enough, other times it just boots everyone but the host from the server due to desync issues or something similar.
![](https://cdn.discordapp.com/attachments/378941943595401228/396669760391348224/barotrauma.PNG)

**Comment by Crystalwarrior** [comment]
This happened on a default submarine, Vellamo if I recall. We also had a few (read: two) rounds where things actually worked, including persistance, save for the whole character inventory issue.

**Comment by NilanthAnimosus** [comment]
I Detail issues with this more on #315 having attempted to mod and use the code, and then testing in vanilla the issues I was having. the above could be due to saves not matching and different submarines in use (And thus different ID's for everything if the players even managed to gain control).

**Comment by Regalis11** [comment]
This is essentially the same issue as #315 but with less details, closing this one.
