### ISSUE TITLE
[0.9.703] Antibiotic glue is recommended wrongly in H menu

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2190]
**Description**
Antibiotic glue is recommended for laceration wounds and gunshot wounds, despite not doing anything to these types of wounds.

**Steps To Reproduce**
-Cause laceration or gunshot wounds
-Use H menu and view damaged limb.
(bleeding often accompanies these wounds, so be sure to check limb thats not bleeding but still has lacerations/gunshot wounds)
-Observe recommended medicine

**Version**
0.9.703 Unstable

**Additional information**
![bug8 glue](https://user-images.githubusercontent.com/59519434/73992374-38a80180-494f-11ea-948f-c57b05546ec2.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3254427aaf323dc807b2179f2546f70cdf00cb07

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
