### ISSUE TITLE
[0.9.703] Deusizine doesn't cause burns anymore

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2191]
**Description**
Deusizine doesn't cause mild burns side effect as advertised in the item description.

**Steps To Reproduce**
-get deusizine
-absolutely mash your body full of deusizine needles
-no side effects at all

**Version**
[0.9.703] Unstable

**Comment by Regalis11** [comment]
Ping @ezjamsen

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d9a149a02ca3eb0d087ffc1b523ef0aecf22388c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
