### ISSUE TITLE
The docking hatch for every Sub and Shuttle cannot be interacted

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2192]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think I phrased #2188 wrong or dev read it wrong.

The top docking hatch that every submarine and shuttle should have cannot be interacted with even though the can't interact toggle is not enabled.

This causes a problem when people uses the Docking Hatch assembly where other players can still wrench out the components and there's no longer a way to set or toggle state the docking hatch.

**Steps To Reproduce**
Wrench out the components for submarines docking hatches to destroy docking.

**Version**
~0.9.703

**Comment by Kaillera** [comment]
Same goes for Vertical Docking Hatch, like for Remora Drone.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3015cd8f094da3757af1e8331bea712d5c6f95d

**Comment by Rokvach** [comment]
No issues, closing.
