### ISSUE TITLE
Unstable - Typhon2 missing bottom airlock ladder

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2193]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When docking a shuttle to Typhon2, there is no ladder to ascend up into the sub. Most shuttle's ladder are too short to reach the floor of the Typhon2

**Version**
0.9.704

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
