### ISSUE TITLE
[0.9.703~704] Crew List Hotkey "C" does not work in spectator/freecam

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2198]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pressing C to open/close crew list doesn't work in spectator/freecam, but you can still open it up manually by button with mouse click.

**Version**
~0.9.704

**Comment by ekqvist** [comment]
This issue seems to exist in the stable version as well. Fixed with Regalis11/Barotrauma-development@dc1fd49.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
