### ISSUE TITLE
Unstable - Command Interface Button is visible when spectating/freecam

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2200]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The command interface button is visible (At least after death? I don't know about if from the beginning) when you're spectating/freecam. Pressing it does nothing, which is right.

**Version**
~0.9.704

**Comment by ekqvist** [comment]
Yes, we could probably just hide it when it's disabled

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
