### ISSUE TITLE
EventManager crash ('Barotrauma.ScriptedEventSet' was not present in the dictionary.)

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2201]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Server crashed due to a pending event set not being present in the list of selected event sets.

**Steps To Reproduce**
Unknown

**Version**
v0.9.704.0, may be present in earlier builds as well

**Additional information**
[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/4172553/servercrashreport.log)

**Comment by Regalis11** [comment]
Added some safeguards against this in https://github.com/Regalis11/Barotrauma-development/commit/4d4bc3f26626cff66e7d9bb57455b7d971a3386e. Not sure what caused it to happen, the only explanation I can think of is that the previous round was ended ungracefully and EventManager.EndRound didn't get called, causing event sets from the previous round to be still be pending. 

Now the events should always get cleared at the start of the round, and if this still occurs, EventManager just skips the event set and logs an error.

**Comment by Rokvach** [comment]
Working correctly. Closing.
