### ISSUE TITLE
[0.9.704] Duffel Bag slots doesn't equal to New maximum inventory

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2202]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Item overflow due to Duffel Bag size not equaling to new max inventory count goes to Narnia.

**Version**
0.9.704

**Comment by Kaillera** [comment]
in 0.9.707, human inventory size is still larger than the duffel bag.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f59d4d65f0a21d4d59f4ca8a1fc9122744b950d1

**Comment by Rokvach** [comment]
Working correctly. Closing.
