### ISSUE TITLE
[0.9.704] Clicking the [ ^    Q ] button doesn't bring up toggleable inventory

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2204]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clicking the [ ^    Q ] button doesn't bring up toggleable inventory, but [ v    Q ] works.

**Version**
0.9.704

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f8e7f47d7a33274251c8e18289e2f1668d7006b2

**Comment by Rokvach** [comment]
The clickable area of the toggle doesn't extend the full width of the button @Regalis11 

![clickablearea.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e53232b7-5913-4eef-9d6c-5b4746ea461d)
