### ISSUE TITLE
[0.9.704] Report Leak button is lit up when you're outside of the submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2206]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Report Leak button is lit up when you're outside of the submarine

**Version**
0.9.704

**Comment by Regalis11** [comment]
Does not seem to happen anymore (the report buttons are hidden when outside the sub).

**Comment by Rokvach** [comment]
No issues, closing.
