### ISSUE TITLE
[0.9.704] When picking up Body Bags, it switches from Left to Right after a small delay automatically.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2208]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When picking up a Body Bag, it's picked up to the Left Hand. After a small moment, it goes to the Right Hand.

**Version**
0.9.704

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/47b3afd9abaf4f4079bfedd4a2e66f1dbc21fbd3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
