### ISSUE TITLE
UTG splash screen stuttering

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#221]
Вроде бы я догадываюсь, что игра начинает загружаться сразу же при открытии. Я не знаю как у остальных отображается начальное видео, но у меня жутко тормозит оно.
Like, I guess, that the game starts to load immediately upon opening. I don't know about the rest of the home video, but I have terribly slow it is.
![load](https://user-images.githubusercontent.com/33912761/34461243-97bbbe94-ee36-11e7-92f2-5895ce64d581.gif)

**Comment by Regalis11** [comment]
Fixed in d7a46d7 and 49f5a9c
