### ISSUE TITLE
[0.9.704] Subinventory Slot & Inventory or Cabinet Slots are highlighted simultaneous when dragging items over subinventory

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2210]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/74071367-af85de80-49d1-11ea-92c3-4bc4c0b5428d.PNG)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ee1b0b234c354231c1fb4924274c3b4d66a9b11

**Comment by Rokvach** [comment]
Working correctly, closing.
