### ISSUE TITLE
[0.9.704] One round can take over an hour due to map generation

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2215]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So 2 things about the new map generation and it's possible max length:

1. One round of Barotrauma can take over an hour with auto pilot driving the entire way and not getting stuck.

2. The distance to next station is no longer an accurate gauge due to the map generation and it's series of ups and downs throughout the level. We found a map that was on the high end of 4km distance. It turned out more like 11km after going up and down a bunch of times.

**Additional Information**
Factoring in the possibility of players wanting to explore ruins, this could extend the gameplay for one round much longer. Lots of players would fall asleep in campaign if they were killed early on. Mission mode is fine with the respawn, but I think Campaign will need at least one respawn somewhere in the level too. Or dead players needs to be given something else to do instead of watch for the whole hour+.

**Comment by rav2n** [comment]
The problem of waiting for the end of the round in the campaign was before. The campaign has one important resource - money. How about the possibility of invoking a revival shuttle for money?

**Comment by Udrakan** [comment]
Shuttle for credits sounds good. Personally I dont mind long mission from time to time, but not every mission in campaign. Half an hour or 40 minutes of unobstructed autopilot mission time seems to me like a good standard time for a level, with 20min short levels and 60min long levels.

**Comment by Ek-Videogames** [comment]
_(You will go through alot more ammo and fuel over the course of a mission, potentially requires the mission reward amounts being rebalanced)_

**Comment by Regalis11** [comment]
The level sizes have been reduced in the latest unstable builds, this can be closed
