### ISSUE TITLE
Base killdisconnecttime is too short (Also no way to change it when hosting within the game)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2216]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I see a player get kick or disappear due to desync, I think the base default killdisconnecttime of 30 seconds in serversettings.xml in almost every server is way too short for players to notice or find the server again to rejoin in time before their body becomes brain dead.

Along with that, there's also no way to change the killdisconnecttime nor kickafktime when you're hosting a server from within the game. I can't just tell hosts to change the time on these 2 because it's not in Settings, and some players may be too suspicious/scared to touch the serversettings.xml.

**Version**
~0.9.704

**Comment by Regalis11** [comment]
Increased default time to 2 minutes in https://github.com/Regalis11/Barotrauma-development/commit/c4484493a6312d0ee43394ccef7eb2d746ad2ba7 and added a command for modifying the value in https://github.com/Regalis11/Barotrauma-development/commit/1095742397d060ed90d275fa1a33caa323971ae4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
