### ISSUE TITLE
Alarm Buzzer sounds like Sonar Beacon

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2219]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using Alarm Buzzer for like the Reactor warning, it's not possible to differentiate it between a Sonar Beacon when there is one active near the alarm. I've had some players dropped a sonar beacon nearby to prevent captains from reacting to use the Reactor Shutdown from the helm.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce74cfae69c86f4610a044ca5bf9ab30335276c0

**Comment by Rokvach** [comment]
No issues, closing.
