### ISSUE TITLE
Crash when no audio device available

### ISSUE THREAD

**Issue by TacticalBacon8** [Regalis11/Barotrauma#2220]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I started up the game over steam and immediately on booting I get an error message [The file is attached to the report].

**Steps To Reproduce**
Disconnect the speakers, headset... any other Audio output from your PC and try to start the game.

**Version**
Game version 0.9.6.0
Operating system: Microsoft Windows NT 10.0.17763.0 64 bit
No Mod Packages activated

**Additional information**
I have already fixed the problem on my machine by turning on my headset (it's a wireless one so I usually have turned it off when I don't need it). I'm not sure if this is supposed to happen but I  just wanted to let you know. [https://pastebin.com/Vn4AWPRB](url)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/45187f9ec3e29412905074cf4b6e2978cdc1ac34

**Comment by Rokvach** [comment]
Working correctly. Closing.
