### ISSUE TITLE
[Feature Request] [Design] Make a server option to lock all default wires

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2228]
Mentioned this on Discord, people said it was a good idea.
The new engineer class that specializes in wiring is going to be useless on most servers, where wiring is entirely disabled.
Basically, make a server option that locks all the wiring that comes with the sub. **People should still be able to put down new wires, and remove wires that were put down after the round started.** This will remove much of the headache that comes with wiring involving people disabling critical systems, but also allow the creative side of wiring to flourish.
I wouldn't imagine this would be too hard to implement. Whenever a new submarine is initialized, just lock all the wires and then be done with it.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1727](https://github.com/Regalis11/Barotrauma-development/issues/1727) via [**ZenHub**](https://www.zenhub.com/)
