### ISSUE TITLE
[Feature Request] Purchasable Toolboxes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2229]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Let us buy Toolboxes.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/157c0d452df791d62ac7423a05f9d1eb31f0a1f0

**Comment by Rokvach** [comment]
No issues, closing.
