### ISSUE TITLE
[0.7.0.1] Starting the game with a content package that doesn't exist crashes the game (But with a windows generic crash dialogue).

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#223]
Tested on 0.7.0.1

This sort of makes sense as normally you go through the launcher but the game neither finds an alternative or details as to why it crashes.

For some clients however the launcher crashes but the game will run if you give them a config file (This is why this could be considered something worth looking into).

If you start the game with an older config file or in general a config file that does not point to an existing content package definition the game will not generate a crash log, no error message - or anything else to describe why it crashed or any attempt to resolve itself by finding another valid content package definition.

Examples (Where 0.7 exists but 0.6 no longer exists):
<contentpackage path="Data/ContentPackages/Vanilla 0.7.xml" /> will boot the game correctly.

<contentpackage path="Data/ContentPackages/Vanilla 0.6.xml" /> will result in the game failing to load, without a crashlog or error message, just a general windows crash dialogue.

**Comment by Regalis11** [comment]
Could not reproduce with the latest version of the code, assuming this is fixed.
