### ISSUE TITLE
[0.9.705] SteamP2P - killdisconnectedtimer console command?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2230]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using killdisconnectedtimer on dedicated server, I get a message saying that the timer was changed, but not when used on SteamP2P server. I can't tell if it was changed since it doesn't save to xml either.

**Version**
0.9.705
Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/affe0395f023b3f327ee712dcb22ad57e16b22b0. The same applied to botcount, botspawnmode and togglekarma, which should now be fixed as well.

**Comment by Rokvach** [comment]
Can the feedback text on killdisconnectedtimer be converted to minutes? @Regalis11

**Comment by Regalis11** [comment]
Good idea, implemented in 364c2a8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
