### ISSUE TITLE
[Feature Request] Deconstruct Duffel Bag/Clothings to destroy them

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2231]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After a long 7 hours series to the center in 0.9.705, we racked up quite a lot of Duffel Bags and Clothings that were in them. I would like to ask to be able to deconstruct these items to destroy them to help with the cleaning up process. Though we can already yeet them out the airlock or drop them off at the station...

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/cceb791be88c2d0875fcdcf2cc7caf8116f3f40e

**Comment by Rokvach** [comment]
No issues, closing.
