### ISSUE TITLE
Exceeding a certain limit on the number of drawing details.

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#2233]
When you load your drawing with a size of about 3,500 parts, the game crashes.
In this case, submarines of size 7000 or more load normally.
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/4176889/crashreport.14.log)
A drawing file was created on the same day.
[sonar_2.zip](https://github.com/Regalis11/Barotrauma/files/4176899/sonar_2.zip)

**Comment by NicolaruS** [comment]
In the version of the game Barotrauma unstable departure is not observed.

**Comment by Regalis11** [comment]
Looks like the contraption you've built has so many physics bodies that it causes the physics engine to run out of memory. 

We've done some optimizations to the physics that prevent this from happening (specifically, the changes in https://github.com/Regalis11/Barotrauma-development/commit/531308c0), but nevertheless I think you are pushing the boundaries of what the game can handle, and you may run into all sorts of issues with this many items (especially if you try to actually make the circuit run in-game).

If you don't mind me asking, I'm really curious as to what you're building here. What's the circuit supposed to do, or is it just a "drawing" with no actual functionality?

**Comment by Regalis11** [comment]
In any case, as the issue has been fixed for the next update, I think this can be closed.

**Comment by NicolaruS** [comment]
Here I make a sonar to play in pvp mode. Experiments suggest that this will work.
Due to the fact that there are no contacts in the Wi-Fi module for changing the radius and channel, the number of components had to be increased several dozen times.

**Comment by NicolaruS** [comment]
The sonar will consist of two parts of the signal emitter and its receiver. The emitter consists of a Wi-Fi module with an unlimited range and a range of dedicated channels changing with the help of an already well-developed counter. The receiver consists of a wi-fi module whose range depends on two operating modes: search for submarine (unlimited range) and determine the range (range changes 1,2, 3 ..... 20,000 with the possibility of increasing the step for rough determination of range). Since in pvp, submarines are a reflection of each other on each submarine will be on the receiver and emitter. For example, the channel of your submarine’s emitter is 10 enemy acoustics first iterates through all available channels in the search mode after detecting the submarine, selects channel 10 on the receiver and switches to the range determination mode, roughly determines the range, and then accurately determines the range with a smaller step. The direction to the submarine is determined by the spacing of these sensors in a circle around the submarine (the sensors closest to it will determine the distance to the enemy before everyone else).
To hide your submarine from observing the enemy, you will need to make your own submarine radiation frequency the same as that of the enemy submarine, but then you will not be able to accurately detect the enemy
I have already conducted several experiments with a simple sonar, and I got encouraging results.
All interactions between the speakers and the sonar will occur with a minimum of buttons without the need to change anything manually in the modules. (if developers introduce additional contacts)
So everyone can become an acoustics even if he does not understand anything in the logical elements of the game.

**Comment by Regalis11** [comment]
Oh wow, that's one of the most ambitious things I've seen anyone build with the signal components! However, I'm sorry to say this, but unless I'm misunderstanding something, it might not work: the wifi components cannot communicate between the opposing subs in the combat mode regardless of the channel. And even if it did work, I think you will have severe performance issues with such an enormous and complicated circuit.

**Comment by NicolaruS** [comment]
"the wifi components cannot communicate between the opposing subs in the combat mode regardless of the channel." is this a bug?
The sonar circuit (using the modified Wi-Fi module) contains about 150 parts.

**Comment by hubismal** [comment]
The wifi components not communicating is an intentional feature so that wifi signals don't get mixed up between subs and mess with one another's functions.
