### ISSUE TITLE
[Reinforced Alien Room + Coil Trap] Hall Connector makes external entry to [Artifact Room] impossible

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2234]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So another Alien room that gives trouble is the [Reinforced Alien Room + Coil Trap]. Normally you would go around it by cutting outside to get to the next room. The problem is when the next room is the [Artifact Room] and when the hallway that connects the two are very short. Due to the high range of the coil and sensors, there's no way to get into the [Artifact Room]. It's also highly difficult to breach the Reinforced Walls anyways.

**Version**
~0.9.705

**Additional Information**
Perhaps we can give the ancient weapon an upgrade to be able to cut reinforced walls easier?

**Comment by Regalis11** [comment]
Do you mean the same trap setup as the one in #2211?

**Comment by Kaillera** [comment]
> Do you mean the same trap setup as the one in #2211?

It's very similar, but no maze-like halls in it. It's an open room with a coil trap and 3 sensors littered inside.

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/74105829-4b792c80-4b2f-11ea-8203-785e00cc722b.PNG)

**Comment by Regalis11** [comment]
Are you aware that you can deactivate the coil by taking out the power cell from the generator (the round thing in the left-side room)? It looks like in this case it'd be possible to enter the room and take the cell out without being zapped if you're careful enough.

**Comment by Kaillera** [comment]
There's no way to even get close to that power cell.

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/74107061-4c638b80-4b3a-11ea-821b-03b107aac6b7.PNG)

**Comment by Kaillera** [comment]
![](https://www.youtube.com/watch?v=EXqoqe7_e88)

**Comment by Regalis11** [comment]
Oh, I wasn't aware the range of the sensors was that large. That does seem to be either a design flaw or a bug in the sensor's range. We'll look into this, thank you for the report and extra info!

**Comment by Kaillera** [comment]
You guys can turn it into a pretty good puzzle if: The sensors weren't as large, the cell is impossible to take out, and the connecting hall is also reinforced walls. Players would have to swim very carefully to the artifact room.

**Comment by danielasteljoki** [comment]
Nerfed this configuration a bit in 192a064 in dev repo.

**Comment by Rokvach** [comment]
There's a new ticket about ruin feedback based on the latest changes so I'm going to close this one.
