### ISSUE TITLE
[0.9.705] Characters Noclips through map walls when you "freecam"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2236]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This was happening in multiplayer.

When you're outside of the submarine next to the map walls that generates throughout the level, your character can noclip through them if you "freecam". Upon "control" the character will have phased through. You will be unable to move if you're in the wall. Repeat until you think you're out of the walls.

**Steps To Reproduce**
Head downward until you found a floor. enter "freecam". Give it a moment. You may see your character phase through clientsided as well. enter "control" to regain your body, and you should see where you really ended up.

**Version**
0.9.705

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
