### ISSUE TITLE
[0.9.705] Ordering Bots with Number Hotkeys equips Hotbar items.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2240]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're ordering bots via number hotkey, when it reaches the part where you select Who you want to order, pressing the corresponding number of 1~5 will send the order and equip items that are on those slot.

**Version**
0.9.705

**Comment by ekqvist** [comment]
This was reported on the private repo (Regalis11/Barotrauma-development#1367) as well, and has been fixed! Closing.
