### ISSUE TITLE
erro de código com monogame

### ISSUE THREAD

**Issue by leh-maker** [Regalis11/Barotrauma#2241]
erro de código com monogame.

 ..Descrição..
Eu sou novato em programação, e estou começando com o c# (monogame) no visual studio 2012.

 ..Problema..
 Meu problema é quando eu crio um novo projeto com o monogame, o monogame já vem com os códigos iniciais e é com eles que esta dando erro, é só eu clicar em ¨start¨ que aparece isto que esta na imagem
![Sem título](https://user-images.githubusercontent.com/60860792/74114332-4a281e00-4b88-11ea-9ada-d027aa907320.png)

Bom não sei o que poderia ser, preciso de ajuda

**Comment by Regalis11** [comment]
This is not the correct place for reports on MonoGame in general, you might want to post it on MonoGame's issue tracker: https://github.com/MonoGame/MonoGame
