### ISSUE TITLE
[Feature Request] Name above of crew icons

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2243]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This crew icon web can get pretty confusing on who you want to order. Since there can also be twins, it'd be great if we can have the names over their icons as well.

(Size of font is excessive, but you get the point)
![Capture](https://user-images.githubusercontent.com/5086682/74164421-bd19af00-4bf1-11ea-9e12-455bbf450a9a.PNG)

**Comment by Regalis11** [comment]
Implemented in f443964

**Comment by ekqvist** [comment]
We're currently testing some additional improvements to the assignment nodes to better convey the important information0, including the name labels

**Comment by Rokvach** [comment]
No issues, closing.
