### ISSUE TITLE
[0.9.705] Opening Crew List interrupts other UIs temporarily

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2248]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Opening the crew list temporarily interrupts other UI like Repairs and Fabricators

**Version**
0.9.705

**Comment by ekqvist** [comment]
Thanks for the report! Can you elaborate on the issue? I tried accessing the Fabricator and a repair interface, but I cannot see the crew list affecting them in any way, even with the relevant action in progress.

**Comment by ekqvist** [comment]
Is the issue that the other interfaces are disabled when you open the crew list? If that's the case, I can inform you that the behavior has been changed for the next build, and other interfaces should not be disabled anymore when you open the crew list.

**Comment by Kaillera** [comment]
Yep that was the case.

**Comment by ekqvist** [comment]
Okay, good to know. I will go ahead and close this then as the change has already been made for the next build!
