### ISSUE TITLE
[0.9.705] Hyperzine is still worst than Anabolic Steroid and Methamphetamine seperately 

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2249]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hyperzine gives 360% of Vigor and Strengthen in one use, or 600% in two use.
Anabolic Steroid gives 600% of Vigor in one use.
Methamphetamine gives 600% of Strengthen one use.

I think these numbers are backward? There doesn't seem to be a reason to turn Steroid and Meth into Hyperzine.

**Version**
0.9.705

**Comment by Regalis11** [comment]
Ping @ezjamsen

**Comment by ezjamsen** [comment]
Agreed. Retuned by increasing negative side effects of steroids and meth slightly, decreasing their vigor and strength gains, and then increased slightly the vigor and strength gains of hyperzine (irrespective of skillcheck fail or pass), as well as adding greater negative consequences for failing med skillcheck.

**Comment by Rokvach** [comment]
No complaints about the changes, so no issues. Closing.
