### ISSUE TITLE
[Feature Request] Delete button to delete saves

### ISSUE THREAD

**Issue by box-admiral** [Regalis11/Barotrauma#2250]
In the single player Load Game screen, one has to select a save from the list and then use the mouse to delete the save. This can be a tiring process for a large number of saves, such as those created by testing small iterative design changes on submarines. Using the delete button on the keyboard would make this easier.

**Comment by Rokvach** [comment]
Another way would be to place the delete button directly on to the list item instead of having it hidden behind a selection, could even use an icon for deletion rather than a button.

**Comment by box-admiral** [comment]
![save_button_rough_idea](https://user-images.githubusercontent.com/60837946/74219221-546d2800-4d00-11ea-97b6-b364744f0ed0.png)
a potential solution - though I'm sure the design team will come up with something cleaner

**Comment by Regalis11** [comment]
I added a "show in folder" button to the "load game" menu mainly for this purpose; you can go to the folder and mass-delete the files manually, so it's a little bit easier now. We could also consider allowing deletion with the delete key or with a button integrated directly in the list, although the latter might make it too easy to accidentally delete files.

**Comment by box-admiral** [comment]
Maybe a checkbox, "quick delete mode" so it requires multiple inputs to enable but once it's checked the delete button works. The show folder button is cool too.

**Comment by Rokvach** [comment]
Needs to be improved somehow, maybe open the next save when hitting the delete button. Current method of deleting ingame is a bit too slow

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1742](https://github.com/Regalis11/Barotrauma-development/issues/1742) via [**ZenHub**](https://www.zenhub.com/)
