### ISSUE TITLE
[Feature Request] Better charge rate settings

### ISSUE THREAD

**Issue by box-admiral** [Regalis11/Barotrauma#2251]
As it stands supercapacitors cannot have their charge rate altered by wiring and even if a wire can change charge rate it has somewhat large step of 10%. The ability to change charge rate on supercapacitors through a set_charge_rate, for charge rate settings to be adjusted in smaller increments of 5% or even 1%, and the ability to change maximum output of batteries through wiring (set_max_output maybe) would be greatly appreciated.

Edit new point and I forgot to actually check the charge rate increment.

**Comment by Regalis11** [comment]
I agree with everything else, but in my opinion it should be a way to set the max output. I see it as a restriction of the item itself, sort of like the maximum output of the reactor.

**Comment by box-admiral** [comment]
I was thinking along the lines of avoiding power load spikes and cliffs. Take for example a supercapacitor at full charge. As soon as I fire a weapon or a discharge coil, the supercapacitor requests its full recharge rate. This can cause undervoltage in the power grid. And when the supercapacitor is fully charged, it requests zero power. This can cause potentially damaging overvoltage. A set_charge_rate pin on the supercapacitor could prevent this by smoothly scaling the charge rate. Batteries have the pin, so I thought supercapacitors should too. But if this is not in line with the intended behaviour of the supercapacitor, then my mistake.

**Comment by Regalis11** [comment]
I fully agree, we should add a set_charge_rate connection to the supercapacitors as well. I just have my doubts about whether we should add a set_max_output connection as well, to me that would seem like a way to magically modify the inherent properties of the battery (sort of like being able to adjust the maximum output of a reactor or the power consumption of devices at will).

**Comment by box-admiral** [comment]
I think my reasoning for the max_output pin was the lack of a set_charge_rate pin on the supercapacitor, so that sounds good.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/11236f20083d93183bdf199c722353b5a5adc548

**Comment by Rokvach** [comment]
No issues, closing.
