### ISSUE TITLE
Tooltip for outputs on greater component is wrong

### ISSUE THREAD

**Issue by box-admiral** [Regalis11/Barotrauma#2253]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not a major issue at all. Just something that should be noted.

The tooltip for when you hover over the output field names for the greater than component (and maybe others I don't know) is wrong, it says that the true output is when both signals are equal and the false output for when both inputs are not equal.

**Steps To Reproduce**
Place a greater than component in the editor
Hover the mouse over Output or False Output
Read tooltip

**Version**
0.9.6.0

**Additional information**
Thankfully the description of the item itself is correct

**Comment by ekqvist** [comment]
Thanks for reporting it, we have a ticket for it on the private repo as well, Regalis11/Barotrauma-development#1291.

**Comment by box-admiral** [comment]
didn't mean to do that

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f5f263caa65e9c669326ed8f5fb9c81fb828270a

**Comment by Rokvach** [comment]
No issues, closing.
