### ISSUE TITLE
[Feature Request] Manupulate "sonarlabel" via statusEffects

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2255]
Allow sonar label's message _(and/or icon in the case of unstable)_ to be changed ingame with status effects.
Something like:
`<StatusEffect type="OnUse" targettype="This" targetitemcomponent="AiTarget" sonarlabel="Sonar Beacon" disabledeltatime="true" />`

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/4c368fe

**Comment by Rokvach** [comment]
No issues, closing.
