### ISSUE TITLE
[0.9.707] Singleplayer - Crew members that were spawned in with "spawn" command, headset teamid is incorrect the round after.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2259]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crew that were spawned in using the "spawn" command in Singleplayer will have an incorrect teamid headset in the next round after they spawned in. The weird thing is when you end the round to save the game and start another round, this is fixed afterward.

**Version**
0.9.707

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd11600

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
