### ISSUE TITLE
Inconsistency between Missions.xml and Explosives.xml - "Nitroglycerin" removed.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#226]
Currently visible in the current github code on GMT 01:00 12/01/2018:

Nitroglycerin has been removed in the game from pull request #188 But its relevant mission has not been removed.

I'm not sure if it was intended to remove nitroglycerin from the game and it was missed/not checked from the Pull request before it was merged.

If it was intended, the mission "Handle with care" currently spawns 2 boxes of an item that no longer exists, and should be changed or removed (Or nitroglycerin re-added).

**Comment by Regalis11** [comment]
Nitroglycerin was not removed, it was only moved to the medical.xml item config. The "Handle with care" mission also seems to be working fine.

**Comment by NilanthAnimosus** [comment]
Nevermind, appears going through the commits (One at a time) I saw the removal without finding it re-added anywhere, 

Turns out my Git client (That I use for viewing the changes) decided to break it apart and make it extremely hard to read. Nitroglycerin is fine.

Apologies on this, Stared at it a good while without spotting the obvious.
