### ISSUE TITLE
[0.9.707] Singleplayer - Crash at SetTransformIgnoreContacts

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2260]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was salvaging an artifact, came back and found that my sub was attacked by a large wave of mudraptors. My crew was able to fend them off but 3 of them suffocated. Upon starting the next round, I was trying to deal with #2259 on one of my bot I spawned in last round. After giving him a new headset, and dropping the duffel bag that had a headset for me to swap with, I crashed into this:
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4189209/crashreport.2.log)

**Version**
0.9.707

**Comment by Regalis11** [comment]
Duplicate of #2252
