### ISSUE TITLE
[0.9.707] Singleplayer - Dead crew members from crash #2260 were magically put back into the roster and revived

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2261]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon loading my save from the crash of #2260, the 3 dead crew members mentioned in that issue were put back into the crew roster and was revived in the round after they died. Their duffel bags were still on the sub.

**Version**
0.9.707

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/8a7c56e039662a90c03ddf35be81f127cc261777. This would only happen if the bots had despawned during the previous round.

**Comment by Rokvach** [comment]
Working correctly, closing.
