### ISSUE TITLE
[0.9.707] Multiplayer - No Melee animation by Bots when they attack.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2262]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots in Multiplayer who are using melee attacks have no animations when attacking.

**Steps To Reproduce**
Attack a bot that has a melee weapon in multiplayer and allow them to retaliate. You will take damage despite not seeing them swing.

**Version**
0.9.707

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef12d7f68c5244c523851f4304f36cd22040be18

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
