### ISSUE TITLE
[0.9.707] Non-medic bots aren't very interested in healing anyone/themselves

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2263]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots that were spawned in using "spawn" command aren't very interested in healing anyone or even themselves when given the heal order. Spawned bots with heal order seems to ignore Gunshot Wound and Bleeding as well?

**Version**
0.9.707

**Comment by itchyOwl** [comment]
There were several issues in the medic ai treating and medic ai priority calculations, but it didin't matter whether the characters were spawned "naturally" or via the "spawn" command. Should be fixed now.

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
