### ISSUE TITLE
[0.9.707] SMG doesn't have SMG Magazine on Autofill

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2264]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
SMG that Commando start with or ones that were spawned by auto fill starts with no magazine.

**Version**
0.9.707

**Comment by Regalis11** [comment]
Fixed the commando in https://github.com/Regalis11/Barotrauma-development/commit/13a9e1a996d1fe89c8e9992e9333451c7345964b, still need to modify the autofill settings

**Comment by Regalis11** [comment]
Seems to be fixed in the latest Unstable

**Comment by Rokvach** [comment]
No issues, closing.
