### ISSUE TITLE
[0.9.707] Diving Suits on Dead Humans goes to Narnia when Duffelmogrified

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2265]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a dead human becomes a duffel bag, diving suits are taken to Narnia with them.

Also a reminder to #2202.

**Version**
0.9.707

**Comment by Regalis11** [comment]
I think we should solve this by making the despawning characters drop anything that cannot be put inside the duffel bag.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1db34df53fe625700460532e9a7f3c7265322e90

**Comment by Rokvach** [comment]
No issues, closing.
