### ISSUE TITLE
[0.9.707] Multiplayer Campaign - "money" cheat doesn't work

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2266]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using "money" cheat in multiplayer campaign, the credit will revert back to legit values when trying to purchase/unpurchase stuff.

**Version**
0.9.707

**Comment by Kaillera** [comment]
Money cheat command doesn't exist on the server's end when inputting money into server console.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d459cbb99628aca37dfd09ab59cb821b1d8b005

**Comment by Rokvach** [comment]
No issues, closing.
