### ISSUE TITLE
[0.9.707] New Level Generations...

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2267]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was still able to find levels like this despite the new level generation were supposedly reverted.

Map 1, part 1
![](https://cdn.discordapp.com/attachments/668819422919524352/676903187789250570/Capture.PNG)
Map 1, part 2
![](https://cdn.discordapp.com/attachments/668819422919524352/676903300121231360/Capture.PNG)

**Version**
0.9.707

**Comment by ezjamsen** [comment]
Not a bug. Cold caverns and cold caverns labyrinth biomes. The reversion was regarding the implementation of longer levels for the remainder of the biome types.
