### ISSUE TITLE
Campaign - Spawning is more aggressive in Singleplayer than Multiplayer?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2269]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I'm not sure if it's just me, but I feel like the spawning events for Multiplayer is reduced in comparison to Singleplayer by a large amount (even on Hellish 100%).

Every time I exit my sub to go into ruins which can take over 10 minutes if I happen to see maybe another ruin nearby or switching to mining for a while, I've noticed that my sub is always heavily under attacked and sinks in Singleplayer. In Multiplayer I could park the sub and wait for my team to finish ruins and mining without being attacked by aliens from the timer based spawning events over the course of 20 minutes?

**Version**
~0.9.707

**Additional Informations**
If this issue is indeed true, I'll just say that I prefer the aggressive spawning in Singleplayer, and should be put into Multiplayer.

**Comment by Regalis11** [comment]
Oh, spotted the issue now! Looks like the server calculates the "intensity value" (that's used to delay additional events if the situation is already bad) incorrectly, causing it to be a little too high server-side. Will fix for the next build, I'm glad you spotted this!

**Comment by Kaillera** [comment]
After playing singleplayer and multiplayer very often, I found this weird disconenct in spawn rate. I wasn't sure to bring it up or not until it started bugging me in singleplayer: "Why isn't multiplayer like this hard?".

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78f6ff6adf704004d6d00a7a75b94f2a338eff4f

**Comment by Rokvach** [comment]
No issues here, closing.
