### ISSUE TITLE
Humans and Shuttles do not trigger alien spawning events

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2270]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Humans and Shuttles (When a main submarine exists) do not trigger alien spawning events when passing distance thresholds.

**Version**
~0.9.707

**Additional information**
If it takes very long for the main submarine to start moving/get far, I found it's better to take the shuttle that a submarine comes with or scooter from one station to the other is the safest option when I can get a large distance ahead of them. No alien threat spawns. Even if they do, it's always near the main submarine.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/83e8600a0d1e9ae7e1023e4ddadb34a6745e70d1

**Comment by Kaillera** [comment]
Submarines and Shuttles prevents wreckevent triggers

**Comment by jeffercize** [comment]
I believe my supposed fix in #2761 addresses the same issue that is being seen here

**Comment by Kaillera** [comment]
[0.9.10.0] Events are still being held back by the main submarine. I saw 2 mudraptors spawned for some reasons though.
![Capture](https://user-images.githubusercontent.com/5086682/82654966-7c1d3780-9bef-11ea-9197-d8cd001d6b6e.PNG)

**Comment by Regalis11** [comment]
The submarine the controlled character is inside (or in multiplayer, the sub with human players inside that's made it furthest) is used to calculate the distance traveled. If you tested this in freecam, that's the expected result.

While debugging this, I noticed the "distance traveled" values in the debug view are wrong (it just shows the distance the main sub has traveled, even if that's not actually used by the event logic), but other than that, couldn't repro the issue. Fixed the debug info in https://github.com/Regalis11/Barotrauma-development/commit/1ac40ed4f34923fe6c1f630fdf85e0e3f3463be7

**Comment by Kaillera** [comment]
[0.9.10.0 RC1] Tested this again with my Aeche III sub. When I used shuttles to travel through the map, all of the mainpath events spawned next to the main submarine at the start of the level instead of near the vessel that is ahead.

**Comment by Regalis11** [comment]
Ah, thanks for the clarification! I thought the issue was monsters not spawning, not that they spawn at an incorrect position. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9d2cf1d8cb75fb2799ad6a5777191f4c4972a7ef

**Comment by Rokvach** [comment]
No issues, closing.
