### ISSUE TITLE
Ladders eating wiring mode

### ISSUE THREAD

**Issue by box-admiral** [Regalis11/Barotrauma#2276]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
#1685 but worse

**Steps To Reproduce**
Place a ladder
Place a relay, signal check, color component, some type of logic component just next to or behind the ladder
Enter wiring mode
Attempt to wire the component by pressing E
Attempt to select something or deselect the ladder without exiting wiring mode

**Version**
Stable 0.9.6.0

**Additional information**
Even if the component is set to a sprite depth of 0.025, shallower than the ladder's 0.050, the wiring mode still targets the ladder. Probably because the ladder doesn't have a wiring panel, the wiring mode gets stuck. Cursor cannot do anything, can't deselect the ladder, only way out is to disable wiring mode. For whatever reason this does not happen with hatches, or pumps, or junction boxes, or probably many other things. It happens for light components and logic components for sure. It seems to happen when the green rectangle is drawn around the ladder. This includes when attempting to wire only the ladder itself.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c71fd446064a9aaa86c17124ae6195547b281e6a

Any item without a connection panel cannot be interacted with in wiring mode anymore, including ladders.

![](https://kosblue.com/e/ytcubr.png)

**Comment by Rokvach** [comment]
No issues, closing.
