### ISSUE TITLE
[Unstable] Possible content hash issues with core content mods

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#2277]
We tried to play a core content mod several times but the game wouldn't recognize us having the same content package even though we got it from the same link and after clean installs.

After a while we noticed everytime we tried, 1 to 3 files would fail to pass the "verify intergrity of game files" thing in steam. This also happened while using the vanilla content package too but we could play multiplayer in vanilla without issues.

**Comment by ChikoEduardo** [comment]
Here, the player I was trying to run the mod with provided more info about it, step by step:

Start game
Close the game
Verify integrity
Everything should validate correctly
Start game
Start a server
Close the game
Verify integrity
3 files should fail file validation leading to a 1.3 Kb download

**Comment by Regalis11** [comment]
If possible, could you run the "calculatehashes" command when the mod is enabled? That outputs a list of the MD5 hashes of the individual files into the console, which should make it easier to pinpoint which files exactly are causing the problem. (As a side note, I think we really need to add the option to save the output to a file, so people could more easily send the results to us...)

If you don't mind sharing the link with me (either here or via PM on Discord if you don't want it to be publicly visible here), I could also take a look myself and see if I can spot the issue.

**Comment by juanjp600** [comment]
We do have the `dumptofile [filename]` command to retrieve the console output, and `calculatehashes` typically fits in 300 lines.

**Comment by Regalis11** [comment]
Oh, true! Thanks for pointing that out. So running "calculatehashes" and something like "dumptofile hashes.txt" on both the server and the client, and sending the results to us would be extremely helpful to us in fixing this!

**Comment by Regalis11** [comment]
I may have found out a potential cause for this. Related to #2311, there seem to be several flaws in the way the game caches the MD5 hashes of the files (meaning that it saves the calculated hashes into a file so it only has to recalculate the hash if the file has been changed).

The system doesn't seem to be working correctly in all cases at the moment, but until we release a fix, you may be able to work around the issue by going to the Data folder inside the game folder and deleting a file called "hashcache.txt".

**Comment by Rokvach** [comment]
There hasn't been any issues with this after the "fix", should I still close this even tho the functionality of caching(afaik) was taken out to temporary fix this? @Regalis11

**Comment by Rokvach** [comment]
I'm just going to close this as in the current setup for the next patch it does work correctly.
