### ISSUE TITLE
Ruins that spawn next to the beginning of the map has no aliens

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2278]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ruins that spawns next to the beginning of the map have no aliens. That is until the sub actually move far enough from the station, then the ruin populates. This applies to ruins further away as well, bit that is related closer to #2270

I noticed a lot of time when I sneak out to go into ruins next to the beginning station and when the sub starts moving, aliens would spawn around or on me as I'm salvaging the ruins.

**Version**
~0.9.707

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/72ee820465f8db9dcb97b438faedfca31a0666f0

**Comment by Rokvach** [comment]
Ruins aren't populating when the submarine is docked at the outpost, I think its fine but I think we need a way for creatures to spawn when player is near the ruins and not just when the submarine is near them. As many players will just check the ruins while they are docked or explore around the outposts while still being docked and not spawning in creatures would just make it easy to raid the starting ruins. 

Similar player triggered events could be utilized elsewhere as well, for example when mining we could spawn some smaller creatures near the players, so events wouldn't just be submarine oriented.

**Comment by Kaillera** [comment]
Whether or not an artifact is in the artifact holder is also tied to this.

**Comment by Regalis11** [comment]
>Ruins aren't populating when the submarine is docked at the outpost
>we need a way for creatures to spawn when player is near the ruins and not just when the submarine is near them.

Both of these were supposed to be fixed in https://github.com/Regalis11/Barotrauma-development/commit/72ee820465f8db9dcb97b438faedfca31a0666f0: the ruins are populated as soon as there's a player or a submarine near them, regardless if the sub is docked to the outpost or not. Are you sure you tested this on the correct branch? The change is not included in the current Unstable build.

**Comment by Rokvach** [comment]
Aa I thought this was on the Unstable (asked community to test it out), so haven't been tested then yet.

**Comment by Rokvach** [comment]
Reported that the ruins are still empty when sub is docked at the starting outpost, 0.9.9.0 Unstable build.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/04bce8f. The changes got reverted when the carrier branch was merged to dev.

**Comment by Rokvach** [comment]
No issues, closing.
