### ISSUE TITLE
[Feature Request] Allow Command Interface from Self Portrait via MMB

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2280]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Allow usage of Middle Mouse Button on Self Portrait to give order to self.

**Additional Informations**
Useful for telling self to wait in campaign when you wanted to teleport them with a diving suit on.

**Comment by Udrakan** [comment]
It would also be usefull for letting everybody know what task you are going to do.

**Comment by Rokvach** [comment]
No issues, closing.
