### ISSUE TITLE
[0.9.708] [Ballance] Fixing electrical items in mission as engineer takes annoying amount of time

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2281]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fixing electroitems even with sufficient skill takes annoying amount of time in mission, where you don't have the time to level it up over multiple rounds.

**Steps To Reproduce**
Play engineer in a mission
**Version**
Unstable [0.9.708]

**Additional information**
I suspect the bug where everybody repairs at the same rate is back, but I could be wrong (could be the skill tweaking)

**Comment by Regalis11** [comment]
Currently it should take 5 seconds for characters with sufficient skills, and up to 10 for low-skilled characters. Tested this a bit and it seemed to be working as intended. I personally think those values are pretty reasonable, and the low-skill duration could perhaps even be a little longer.

**Comment by Rokvach** [comment]
I actually enjoyed the lower speed of repairing, it did lead to some comical situation where when there was overvoltage to grid and it blew all the junction boxes we had to have the whole crew fixing them in order to get the situation sorted out without the whole place burning down.

**Comment by Udrakan** [comment]
I was there too Rok and it was cool. Also, captain's engine thrust management skill can prevent a lot of junction repairs, which was apparent when we changed cap, so I've changed my view.
