### ISSUE TITLE
[0.9.708] "Voice volume" in sound options doesn't do anything

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2282]
**Description**
What title says. Everybody sounds the same when changing the Voice volume in options.
**Steps To Reproduce**
-Get into MP lobby with buddy who has voice chat
-Change Voice volume in options
-Notice that there is no changes to his voice volume

**Version**
Unstable [0.9.708]

**Comment by ekqvist** [comment]
I believe this has been already reported back in 0.9.5 (#1919) so probably be nice to give it some attention when we can. I'll close this as a duplicate.
