### ISSUE TITLE
[0.9.708] Tutorial - medic doesn't follow the captain when ordered to follow in Captain's tutorial

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2283]
**Description**
Title says it all.
**Steps To Reproduce**
-Start the Captain tutorial
-Get to the medic part
-Order him to follow you
-Observe his behaviour
**Version**
[0.9.708] Unstable
**Additional information**
Mission can still be finished, but medic stays at the station.

![bug13tutmedfollowcap](https://user-images.githubusercontent.com/59519434/74379494-2c58f400-4de8-11ea-9a72-3737057830b8.gif)

**Comment by ekqvist** [comment]
I seem to be able to get the medic to follow the captain like they should, but it seems that they have a problem entering the sub itself, with console gettings spammed with "Bennie Deloney: Cannot reach the target: Dewey James".

![image](https://user-images.githubusercontent.com/16864465/74442163-b43b0e80-4e79-11ea-9453-784725ebc5ca.png)

**Comment by ekqvist** [comment]
It seems that I managed to get them stuck inside the station as well, with the console getting spammed with the same message.

![image](https://user-images.githubusercontent.com/16864465/74442540-578c2380-4e7a-11ea-8a83-77d294e81879.png)

**Comment by Regalis11** [comment]
Probably related to #2174

**Comment by ekqvist** [comment]
This seems like it's working now

**Comment by Rokvach** [comment]
No issues, closing.
