### ISSUE TITLE
[0.9.708] Weird ligthing and shadows, most noticable in tutorials

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2284]
**Description**
Shadows and interaction of light sources is very weird in some situations. I have made some gifs that show you what I mean. Look at the left side of the characters:
![bug12shadowgif](https://user-images.githubusercontent.com/59519434/74379662-848ff600-4de8-11ea-903c-505340214095.gif)
![bug12shadowgif2](https://user-images.githubusercontent.com/59519434/74379676-8954aa00-4de8-11ea-9877-a0cbc92d785e.gif)

**Steps To Reproduce**
-Play engineer or security tutorials
-Pay attention to shadows and lights when you open/close doors

**Version**
[0.9.708]Unstable
**Additional information**
When this lighting works, it's fantastic, but there are situations where it looks wrong and weird.

**Comment by SenhorPatolino** [comment]
Happens in sub editor, apparently doors create this shadows, i suggest removing them, i think the penumbra effect already does the job
