### ISSUE TITLE
[0.9.708] Tutorial - Wrong sprite depth in Engineer tutorial

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2285]
**Description**
1 decorative item that you walk past in engi tutorial is at wrong sprite depth.

![bug11 tutorial sprite](https://user-images.githubusercontent.com/59519434/74380056-24e61a80-4de9-11ea-81cb-688bc2acadb6.png)

**Steps To Reproduce**
-Start Engineer tutorial
-Walk past the radiation symbol on the picture
-Observe wrong sprite depths
**Version**
[0.9.708]Unstable

**Additional information**
I've checked around the outpost and this one seems to be the only one. You never know though...

**Comment by Regalis11** [comment]
Also in the officer tutorial:
![officertuto](https://user-images.githubusercontent.com/14351070/74453661-5adbdb00-4e8b-11ea-985b-3ae663238264.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2b35add9ee3bfad0d51a6cd34ef7c92eef90379c

**Comment by Rokvach** [comment]
No issues, closing.
