### ISSUE TITLE
[0.9.708] Bots - O2 generator in Typhon2 is unreachable for bot repairs

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2286]
**Description**
Bots have difficulty reaching the O2 gen for repairs and they often end up below it.

**Steps To Reproduce**
-Start a singleplayer campaign on Typhon2
-Have the O2 generator broken by any means
-Order a bot to repair it
-Observe behaviour

**Version**
[0.9.708] Unstable
**Additional information**
![bug14typhonO2repair](https://user-images.githubusercontent.com/59519434/74384606-f02a9100-4df1-11ea-97ee-e47cca4556eb.png)

**Comment by itchyOwl** [comment]
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b929cbee-842a-4290-b30b-60a1df551f61)

Seems that the waypoints are missing there. I'll fix it.

**Comment by Rokvach** [comment]
No issues, closing.
