### ISSUE TITLE
Exterior Docking Clamp For Shuttles

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2289]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I wanted to do something like this in the picture below, but this error message force opens the console every time a shuttle docks to it.

"Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine"

![](https://cdn.discordapp.com/attachments/427654262453960724/677328414620778543/Capture.PNG)

As far as trying it as is, there's no difficulty in getting in and out of the shuttle from the top. Players are expected to have a diving suit to get there. Water doesn't drain into the shuttle.

**Version**
~0.9.707

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b0027e8624d0caf42363528e91dcd533d587d6de

**Comment by Rokvach** [comment]
No issues, closing.
