### ISSUE TITLE
[Feature Request] One more Previous Order

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2291]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm not sure if anyone is all for having a second previous order button or not, but I think there's space for it still. It would be nice to implement.

![Capture](https://user-images.githubusercontent.com/5086682/74427481-3220fa80-4e25-11ea-9a17-ac46272fd7af.PNG)

**Comment by Udrakan** [comment]
That would be very useful when dealing with crisis or sudden situations, then returning back to normal. Anything to make bot gameplay more fluent.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1741](https://github.com/Regalis11/Barotrauma-development/issues/1741) via [**ZenHub**](https://www.zenhub.com/)
