### ISSUE TITLE
Unstable - Humpback Battery Array Relay Component not toggling with 'on' or 'off'

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2294]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using the terminals to input on/off/'on'/'off'/On/Off/ON/OFF/"On"/"Off" nothing happens to the relay component that they are attached to.

**Version**
~0.9.708

**Comment by Regalis11** [comment]
Not sure if this is a code or a design bug, so I added both tags for now until we have time to take a closer look into this.

**Comment by Regalis11** [comment]
Seemed to only happen in multiplayer, fixed in https://github.com/Regalis11/Barotrauma-development/commit/78c3d5ff027f00776ccea3363594a7013fdc4728

**Comment by Rokvach** [comment]
No issues, closing.
