### ISSUE TITLE
Slow Metabolism does nothing

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2295]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Slow Metabolism does nothing

**Steps To Reproduce**
Case 1:
giveaffliction burn 50 self
Inject Tonic Liquid (Supposedly x1.5 duration according to Chad)
Inject Stabilozine (-10 burn)
Burn is at 40, instead of 35.

Case 2:
Inject Tonic Liquid on one character
Inject Hyperzine on two characters
Watch deterioration rate.
Exactly the same for both characters.

**Version**
~0.9.708

**Additional Informations**
Had never worked in 0.9.6 either.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3a82d6ed837d462e8ccc78b45bddf4bded5cb96

**Comment by Rokvach** [comment]
Doesn't seem to be any issues, closing.
