### ISSUE TITLE
Ragdoll stuck on Corners

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2296]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When going down, it's easy to get caught on the corners of walls and blocks and get stuck, even by players. Ragdoll button helps get off it.
![Capture](https://user-images.githubusercontent.com/5086682/74476380-37a73080-4e77-11ea-9016-54f502c0d732.PNG)

**Version**
~0.9.7.1

**Comment by Kaillera** [comment]
Edited: Confirmed, It can happen on any subs.

**Comment by itchyOwl** [comment]
An easy way to repro this is to run from left to right and hold down at the stairs. The character should "jump" over the stairs and get stuck in that corner.

**Comment by CodeHatchling** [comment]
A possible fix to this is to perform multiple checks for character groundedness.

For example, in addition to tracing down from the character's center of mass, you could trace down from the character's feet (the corners of their heels and toes). A "thick" trace (equivalent to a Spherecast in UnityEngine) could prevent issues with very narrow platforms.

**Comment by JoneKone** [comment]
https://youtu.be/-DfHhIHXPo4

**Comment by JoneKone** [comment]
now wondering if this is related to #7176

**Comment by itchyOwl** [comment]
Seems to happen quite often here (Barsuk):

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/613f7576-e3d0-4d69-85a2-b07d2fba1910)

**Comment by itchyOwl** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4005.

**Comment by itchyOwl** [comment]
Repro steps: Teleport the character at the places depicted above. It can take a couple of attempts, but can be caused quite easily.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by itchyOwl** [comment]
The fix didn't seem to work on bots. Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4265/commits/5e1dffe2acef1bf25df1e49a784c9bff6a9e53db.
