### ISSUE TITLE
Underwater facilities

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#23]

**Comment by yaelatletl** [comment]
I might have something that fits the title.
It was a station (completely static) until some friends requested it as an actual sub. 
[MFB-Athenea.zip](https://github.com/Regalis11/Barotrauma/files/1522866/MFB-Athenea.zip)

**Comment by Regalis11** [comment]
Thanks for the file, might be useful when we start adding stations! It's still not clear how exactly the stations will be implemented though; one option I've been thinking of is generating them semi-procedurally from a set of pre-made "modules". There could, for example, be a set of airlock modules, hallways, command rooms, cabins, etc, and the game creates the stations by combining them in a semi-random way. In any case, that file could come in handy. :)

**Comment by yaelatletl** [comment]
Then this may be useful too, this are submarines made out of modules (The DS-** ones) I Actually wanted to place even more together, but it seems that if you add as shuttle a sub that already has a shuttle that last one doesn't load. 

[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/1523949/Submarines.zip)
