### ISSUE TITLE
В обучении не соединена лампа с щитком. / The training is not connected the lamp with the shield.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#230]
Можно, конечно же, добавить то, что не ожидают игроки соединив лампу с щитком. Казалось бы, это баг, но бац! Тут появляется текст, в котором написано: "Вау, это было неожиданно. Ты настоящий молодец!". Знаю, это банально, но некоторым понравилось бы.
А так можно просто исправить недочёт.
You can, of course, add that don't expect the players by connecting the lamp with the shield. It would seem that this is a bug, but BAM! Then there is the text, which says: "Wow, that was unexpected. You're a real man!". You know, it's corny, but some would have liked.
And you can just fix the defect.
![image](https://user-images.githubusercontent.com/33912761/35010672-b1e4c8a2-fb14-11e7-9fd8-41bd4be2cd52.png)

**Comment by Regalis11** [comment]
The tutorial (and tutorial sub) will be completely redesigned so I think we can close this. The issue with the "fix" text has been fixed.
