### ISSUE TITLE
[0.9.708] Strange desync of Reactor and Docking Hatch state

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2301]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you leave a server and come back (Dedicated Server & Humpback in this case) before your killdisconnect, the reactor will be on a maxed out overheating state and the docking hatch is no longer docked and will look like the sub is sinking on the nav terminal. I'm not sure if the reactor state was real server side wise or not (I always rushed to turn it off in case of explosion), but the docking hatch state is definitely docked server side.

If the client side pressed the faux docking button, the sub will undock and resync the client on the sub real position and state (as long as the sub still looked as if it was next to a station dock, you will have a button. Otherwise you can't undock or move the sub if it got too far on the client's end).

**Version**
0.9.708

**Comment by Regalis11** [comment]
I don't think this ticket is relevant any longer: I suspect this could've been caused by the "warm start" logic we used to use to start up the reactor at the start of the round.
