### ISSUE TITLE
[0.9.708] No current/previous order in crew list when rejoining server

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2304]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon rejoining server all current orders/previous order given to crew are not in the crew list.

**Steps To Reproduce**
Tell a crew to do something. Then to do something else.
Rejoin server
Look at the crew list

**Version**
0.9.708

**Comment by ekqvist** [comment]
Syncing of current orders has been implemented with Regalis11/Barotrauma-development#1439.Resolve (partially) Regalis11/Barotrauma#2304. However, as I stated in the pull request, this does not sync previous orders for clients, as they are still determined and shown completely client-side. However, I'm not sure that syncing them absolutely needs to be implemented.

**Comment by Rokvach** [comment]
Couldn't find any issues, closing.
