### ISSUE TITLE
(Unstable) Mobile Scooter has incorrect RequiredItems Field

### ISSUE THREAD

**Issue by MystLeissa** [Regalis11/Barotrauma#2306]
- [No ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The divinggear.xml file defines the RequiredItem tag on the MobileScooter as identifier="mobilebattery" instead of items="mobilebattery" causing modded batteries (and possibly even Battery Cells in Vanilla as they aren't defined by this identifier) to not work for powering the device.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Use Unstable, Load a battery cell (modded/thorium) into the Underwater Scooter and attempt to drive it.
**Version**
Which version of the game did the bug happen in. You can see the version number at the bottom left corner of the main menu, and in a file called "Version.txt" inside the game folder.
Also, please include the operating system you're using (Windows/Linux/Mac).
0.8.7.0
Windows 10

**Additional information**
Seems to be a bug with the XML Definitions not any core code.

**Comment by Regalis11** [comment]
Actually, the attributes "items" and "identifier" are functionally identical, so this shouldn't cause any issues. Tested with a fulgurium battery and a custom battery just now (identifier="testbattery" tags="smallitem,loadable,mobilebattery"), and both seem to be working as expected.

**Comment by Rokvach** [comment]
No issues, closing.
