### ISSUE TITLE
(Unstable) Game freeze on steam-hosted server

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2307]
**Description**
Game froze for me when I was hosting a steam server and I had to end it through task manager. It was not a mem leak.

**Server log**
[Unstable evening missions_2020-02-15_0141.txt](https://github.com/Regalis11/Barotrauma/files/4207516/Unstable.evening.missions_2020-02-15_0141.txt)

**Version**
Unstable

**Additional information**
Other players on server had connection time-out message, not freezing.

**Comment by Regalis11** [comment]
Potential duplicate of #2531, moving to Review/QA

**Comment by Rokvach** [comment]
There hasn't been any reported cases of this happening, closing for now.
