### ISSUE TITLE
[Feature Request] Add unshaded option for particles

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2314]
It would be nice if there were an option for particles to have them be unshaded (draw them in front of the lighting or something) so that they properly look "lit up" (for things like sparks, lasers, explosions, etc). Right now particles are affected by lighting and they look really awkward.

**Comment by hubismal** [comment]
as a sidenote, especially necessary now that the game is so dark.

**Comment by Regalis11** [comment]
Not sure if this is necessary, I think the current additive blending works pretty well for things like sparks, lasers and explosions:

![9aw8fuiwanf](https://user-images.githubusercontent.com/14351070/74596756-47339e80-505c-11ea-9d4f-0fd36256f763.png)

Alpha blended sprites that aren't affected by lighting would actually probably look worse for this type of things: for example, a dim particle on top of a bright one would still look dim, as opposed to the brightness being added up.

**Comment by hubismal** [comment]
Oh yeah, additive. huh.
