### ISSUE TITLE
Disconnect after Starting Multiplayer Campaign Mission

### ISSUE THREAD

**Issue by coitur** [Regalis11/Barotrauma#2318]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Host of multiplayer server crashes to main menu either immediately after starting the round, or seemingly at random during the mission. This has happened to me twice consecutively, and the second crash happened during the mission, with no discernible trigger. Both times I had to restart the server.

**Steps To Reproduce**
None that I could find.

**Version**
Version 0.9.6.0

**Additional information**
Screencap of error message and console:

![image](https://user-images.githubusercontent.com/61126010/74614198-104c9f80-50d3-11ea-8c8c-4e372104fc0f.png)
_NOTE: This was the screencap I got after the first crash._

**Comment by Regalis11** [comment]
Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/3019, closing this one because the newer ticket has more info
