### ISSUE TITLE
[0.9.7] Crash on SoundChannel

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2319]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players were all phasing through the floors and walls and rubberbanding back continuously. My shuttle was also wedged between ice on all sides and being forced into the ceiling. Then this occured.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4211289/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4211290/crashreport.2.log)
Second one seems to have a lot of other stuff erroring out there too.

**Version**
0.9.7

**Comment by JCLA3114** [comment]
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/4211297/crashreport.14.log)

Same round as crashreport (2).log above, but I was only spectating, and apparently do not have the additional errors, only the one that made it crash

**Comment by juanjp600** [comment]
Additional diagnostics added in https://github.com/Regalis11/Barotrauma-development/commit/b219d417d9455f8824071167b615c9cf742e9a0f, https://github.com/Regalis11/Barotrauma-development/commit/cdff1a4d4fce40554f43c3d4e28cfc327559bca2, https://github.com/Regalis11/Barotrauma-development/commit/e34822f70849f725a1c0fb96ff895499b69e7a1f

**Comment by Regalis11** [comment]
Seems there haven't been any more reports about this, I think we can close this and reopen if it reoccurs
