### ISSUE TITLE
[Feedback] Berilia ballast pumps sucks Monstrously Bad.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2320]
The ballast pumps sucks Monstrously Bad. The ballast pumps has a max flow of 100, which is equal to all the small pumps that are around the sub. I even went as far having the crew rewire the bilges to help with the affecting the ascent/descent.

The bottom engine room is also bad for Bots as well since there's lack of waypoint connection there.

**Version**
~0.9.7 - 630ff935f

**Comment by danielasteljoki** [comment]
Pumps are slow mostly by design, a sub that size shouldn't handle very well. That being said, I buffed the pumps a little to make it hopefully less frustrating to operate. Connected the waypoints too (in dev repo).

**Comment by Rokvach** [comment]
No issues, closing.
