### ISSUE TITLE
[0.9.6.0 - 0.9.7.0] suggestion about respawn shuttles

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2321]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In these versions of the game, the following problem exists: shuttles save the state of devices and doors from a previous appearance.

1) Control terminal. Since the state of the terminal is preserved, the next shuttle has every chance of breaking on the rocks immediately after its appearance. For example, if in its first appearance for docking it was necessary to send the shuttle down, then when the next shuttle appears, it will also immediately move down.

2) Doors and  griefers. Recently, I often observe cases when a character with welding brews a door or hatch, which makes it impossible to leave the next shuttle on his own.

**Version**
0.9.6.0 - 0.9.7.0

**Additional information**
It would be ideal if each subsequent shuttle was subject to change only in items that were taken away or left in storage. Since in addition to the terminal and doors, there are still pumps that players can probably turn off, various switches (although they may be redundant) whose state will also be preserved when switching.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1487](https://github.com/Regalis11/Barotrauma-development/issues/1487) via [**ZenHub**](https://www.zenhub.com/)
