### ISSUE TITLE
[0.9.6.0 - 0.9.7.0] suggestion about server logs

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2322]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As far as I was told, before it was possible to track the player's Steam ID throughout the whole round. Then you refused it for some reason. Is it possible to return the display of identifiers at least during the connection of the player to the server or during the start of the round. Because there is a situation when a  griefer comes to the server and before it can be banned, it manages to leave the server and it is not possible to get its Steam ID. Or are there any other ways that I don’t know about?

**Version**
0.9.6.0 - 0.9.7.0

**Additional information**
And sometimes there are several griefers and they come together as soon as one sees that his accomplice was banned immediately leaves the server.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1739](https://github.com/Regalis11/Barotrauma-development/issues/1739) via [**ZenHub**](https://www.zenhub.com/)
