### ISSUE TITLE
Ultrawide UI issues

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#2323]
Horizontal spacing on inventoryslots is too big:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/4e5463c6-9490-44cc-a248-b55401e0bd84)

Diving suit locker text wraps for no reason, could be wider to match the 16:9 layout
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/75fe6b0e-aac6-4599-bb00-b3a6a073aa3e)

Same issue with the fire extinguisher bracket, seems that fonts are too big
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/66c4d3f7-64aa-4da7-ab8b-fe80fef41357)

Sonar view is too big, text below it can't be displayed properly in 21:9:
![sonar.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/3ce52e37-f452-4cd5-90b3-406243b609b1)

16:9 for comparison:
![sonar_169.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/a1d16011-1122-4a95-9bae-5c733ef41301)

Popup dialogs are too narrow:
![dialog.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/0615c53d-b57e-4ea9-a10e-42b26a3736b5)

Hotkey fonts too big:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/f4d0d7d7-a23c-49a1-90ad-d7b7236e9423)

Healthbar misaligned:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/9feca1ce-0b11-4c54-a67f-ac174bffef66)

Crewlist lines on top of names:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/bae46aca-a799-4b45-880c-2f1ff32a3b5f)

Chat fonts are pretty massive:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/c5809cf9-ba82-42b6-9002-01219cc27cd8)

Selected crewmembers in tab-menu has overlapping text:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/57f9eab4-cc00-467d-9a45-270319d2b878)

Host server fields are overlapping:
![serverhost.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/0bf6e120-63fd-407d-bd13-205b5bafc1aa)

Workshop item description is not fully visible:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/49b345c0-ea35-4d17-9703-04e118d33141)

Bottom left revision text is out of bounds:
![image.png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/e029fcb9-7a9d-4fc1-8f43-21d3fbee8794)

**Comment by itchyOwl** [comment]
The navigation interface should be fixed. It takes the aspect ratio into account, but apparently it overshoots for some reason. I made the whole interface just a bit smaller. We might want to adjust it further when the restricted areas in the hud are final.

**Comment by Rokvach** [comment]
No issues, closing.
