### ISSUE TITLE
Button wired to discharge coil will cause only client side visible shock.

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#2324]
**Description**
Pressing a button wired to the 'trigger in' on a discharge will cause the shock to only be visible client side.

**Steps To Reproduce**
Refer to above.

**Version**
0.9.7.0

**Additional information**
May also apply to toggle lights as well, and logic, though no concrete evidence.

**Comment by Udrakan** [comment]
It's always been like this since release.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/406725ca0caeb3d683cbad578202f27ebd5fa7f5

**Comment by Rokvach** [comment]
Confirmed working, closing.
