### ISSUE TITLE
Unable To Load Server Selection

### ISSUE THREAD

**Issue by Oblisk234** [Regalis11/Barotrauma#2325]
When I Load The Game, I Click On Multiplayer And Then Immediately Says It Crashed From Some Out Of Parameter Thing, Not Sure What But It Has.
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/4214102/crashreport.11.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57bc712, coming up in the next update

**Comment by Rokvach** [comment]
This hasn't come up since the fix and we've had quite a good number of players playing the Unstable. So I'm just going to close this.

**Comment by Oblisk234** [comment]
Thank You.
