### ISSUE TITLE
Slow Metabolism still does nothing

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2327]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Slow Metabolism still does nothing

**Steps To Reproduce**
Case 1:
giveaffliction burn 50 self
Inject Tonic Liquid
Inject Stabilozine (-10 burn)
Burn is at 40, instead of 35.

Case 2:
Inject Tonic Liquid on one character
Inject Hyperzine on two characters
Watch deterioration rate.
Exactly the same for both characters.

**Version**
~0.9.7

**Comment by Kaillera** [comment]
https://cdn.discordapp.com/attachments/668819422919524352/678987522314862599/Metabolism_Test.gif

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e6038977ee31946a8e27a23fd5f5f0bd984792e

**Comment by Rokvach** [comment]
No issues, closing.
