### ISSUE TITLE
Medical item effects are being stolen by the next person injected

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2328]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When injecting medical items to two or more different people, the later person gets the effect transferred to them

**Steps To Reproduce**
giveaffliction burn 50 to two or more different people
inject stabilozine to each person.
observe

the earlier person will transfer whatever effect they had left to the next person.

**Version**
0.9.7

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67f3413794fac388aeae4aba9abcc8064edad71c

**Comment by ekqvist** [comment]
Tested to be working correctly now
