### ISSUE TITLE
Error in EventManager.Update

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2329]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shortly after undocking and driving a bit from the station, this error came up in my console.
![Capture](https://user-images.githubusercontent.com/5086682/74677020-59f5c280-5185-11ea-9ca3-87a8c4e1414c.PNG)

**Version**
0.9.7

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b5c254e5ec386364d438434b758a2c5917217c2

**Comment by Rokvach** [comment]
No issues, closing.
