### ISSUE TITLE
Disconnect during hosted server campaign mission (defeat the swarm)

### ISSUE THREAD

**Issue by CaptainCandle** [Regalis11/Barotrauma#2330]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The server crashed (With myself as host, private host), 

**Steps To Reproduce**
During a particular save, after beginning the Mission "Defeat a Swarm", the players direct the ship out of dock, and after around 45 seconds the save will crash. This is reproduce-able in every instance (see attached Screen Shot for the error and debug on-screen). 

**Version**
Windows 10 x64, Version V0.9.6.0

**Additional information**
![Untitled](https://user-images.githubusercontent.com/61185151/74724180-f99f7780-528f-11ea-840e-f7121c1d2126.png)

**Comment by Rokvach** [comment]
I am quite positive this has already been fixed in Unstable

**Comment by Rokvach** [comment]
Closing as this issue hasn't come up in Unstable

**Comment by CaptainCandle** [comment]
Hi Roni,
So sorry I never replied to you. You are correct, this issue appears to be fixed. Thanks for nontheless looking into it.
Kind regards,
Scott

Sent from Yahoo7 Mail on Android 
 
  On Mon, 2 Mar. 2020 at 19:34, Roni Kovaniemi<notifications@github.com> wrote:   
Closing as this issue hasn't come up in Unstable
