### ISSUE TITLE
[Feature Request] Allow MMB Command Interface when hovering mouse over Crew

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2331]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Allow MMB Command Interface when hovering mouse over Crew. It would be nice to send a order to the person next to you without having to open the crew list or searching for them through the crew Web (Especially since you can tell if they're busy or not).

Thanks for implementing my previous request #2280, I think that this addition will make it even more fluid.

**Comment by ekqvist** [comment]
Thanks for the request again! We're definitely looking to take the command interface further with new functionalities in future updates! I have personally been thinking about this same possibility, but we'll have to see where we want to take the interface functionality once the first version of the interface hits the stable version of the game first!

**Comment by ezjamsen** [comment]
This seems like a cool idea. I guess the more ways we can allow players to do the things they want the better, let's add this to the backlog and see how much sense it makes in a month or so.

**Comment by ekqvist** [comment]
Implemented in the most recent Unstable

**Comment by Rokvach** [comment]
No issues, closing.
