### ISSUE TITLE
[Feature Request] Faster way to Reporting and Enemies on Sonar for Non-mic players

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2334]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So some of the challenges players without mic are facing is the ability to report leaks because they have to type. Occasionally we may run into foreign captains as well that can't speak the common language in the round. This leads to players usually outing players from the Captain role.

I propose that anyone that are at a status terminal or navigation terminal linked with status terminal, to be able to just double click a room to report leak (even if there is no leak). And/Or allow right click drop down menu to report all the other things like broken devices, hostiles, and fires as well without being there.

I am also wondering if we can give players at the helm the same ability as a Bot Captain to report "# of sonar signals at direction" somehow as well? Maybe right clicking inside the sonar circle below the sub to "Sonar signal at 6 oclock!".

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1740](https://github.com/Regalis11/Barotrauma-development/issues/1740) via [**ZenHub**](https://www.zenhub.com/)
