### ISSUE TITLE
[0.9.7] Crate Racks renamed to Medium Steel Cabinet

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2335]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crate Racks had been renamed to Medium Steel Cabinet.

**Version**
0.9.7

**Comment by Regalis11** [comment]
This was done because "crate rack" didn't make it to the batch of texts translated for the next update, so we had to replace it with another name until we do the next batch of translations.

**Comment by Regalis11** [comment]
Looks like we forgot it from this batch as well. 😅 Added to EnglishVanilla in 5398dba, ready for the next batch

**Comment by Regalis11** [comment]
The corrected name has now been included in the text files, waiting for the new batch of translations.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/235690e, coming up in the next patch
