### ISSUE TITLE
[Feature Request] Sub Editor - Hotkey to Pan to Object/Bring Object Position

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2336]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes whenever I copy and paste items in the sub editors, I do not know where they end up. Would be nice to have a button to pan the camera to the object position or have the object be brought to where you're looking / pointing the mouse.

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/6de12d2b9cc420add792c017dd9f2c8236e87444

Pressing "F" in the sub editor now focuses your selection, if multiple items are selected it will focus the center point of the selection. Pasted items are automatically selected so this should provide the desired functionality.

**Comment by Kaillera** [comment]
Love you hex code guy!

**Comment by Rokvach** [comment]
No issues, closing.
