### ISSUE TITLE
[0.9.7] Sub Editor - Wires are drawn behind walls.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2337]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Eh](https://user-images.githubusercontent.com/5086682/74975198-adba1300-53f4-11ea-8af5-1936506b1862.gif)

**Version**
0.9.7

**Comment by Regalis11** [comment]
This is intentional
