### ISSUE TITLE
[0.9.7] Diving Suit Limits Periscope Vision

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2338]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Looking through a periscope with a diving suit on reduces the distance you can see, when compared to looking through one without a diving suit on.

**Steps To Reproduce**
Equip a diving suit and look through a gun-linked periscope.

**Version**
9.7
Windows

**Additional information**
I have been told a similar thing happens when using a diving mask, but I have not experienced it myself.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2174117fa8d933092e39fc645d21026eaea28e5

**Comment by thegrb93** [comment]
I thought this was an intentional hindrance of the diving suit.

**Comment by Regalis11** [comment]
It is an intentional hindrance, but making it obstruct the vision when aiming with a turret was not intended. The character is peering through a periscope, and I don't think it should make much difference to their field of view whether they're wearing a diving suit or not.

**Comment by thegrb93** [comment]
I see

**Comment by mrjpjr** [comment]
Kaillera reminded me that the same thing happens when you have a diving mask on.

**Comment by Rokvach** [comment]
This also covers the diving mask, no issues. Closing.
