### ISSUE TITLE
[Bug] [Unstable] Level Editor does not properly save LevelGenerationParameters

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2340]
When pressing "Save All", the level editor will not properly save the level generation parameters to LevelGenerationParameters.xml in my mod. This should be fairly easy to reproduce. In this case, I increased the amount of small tunnels to 2 and pressed "Save All". This button seems to work for levelobjects but not the biome/level params.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0844d085a070dc6f0353c75d56fa87523d37a9ae. The issue was that the override elements were not taken into account when saving, so the saving logic wasn't able to find the correct parameter element to replace in the config file.

**Comment by Rokvach** [comment]
No issues, closing.
