### ISSUE TITLE
[Feature Request] Allow modders to define items for sale in LocationTypes.xml

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2341]
This has already been requested and probably heard, I'm making a ticket for it just for the sake of there being a ticket.
It would be more than nice if there were something like a <Store> tag in LocationTypes.xml for each location type that allowed you to override the default settings of what is sold in a location so you could quickly make stores that sold specific things instead of having to redefine the <price> tag in every single item (which involves making your mod *extremely* incompatible).

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1755](https://github.com/Regalis11/Barotrauma-development/issues/1755) via [**ZenHub**](https://www.zenhub.com/)
