### ISSUE TITLE
[Feature Request] Biome Conditional in randomevents.xml

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2343]
It would be neat if we could restrict certain random events to biomes. This would give biomes much more unique senses of self.

**Comment by Regalis11** [comment]
You can sort of do this already by changing the commonness per level type, so for example something like like
```
<Commonness commonness="5">
  <Override leveltype="RidgeBasic" commonness="0" />
  <Override leveltype="WastesBasic" commonness="0" />
</Commonness>
```

This would make the event set somewhat common in all types of levels, except in the basic Europan Ridge and Hydrothermal Wastes levels.

I agree that configuring them per-biome would be useful too though, especially if modding levels becomes more of a thing in the future (you cannot set the commonness for the level generation parameters of another mod, but could do so if the mod uses the same biomes).

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1747](https://github.com/Regalis11/Barotrauma-development/issues/1747) via [**ZenHub**](https://www.zenhub.com/)
