### ISSUE TITLE
[Feature Rq] Allow Vignette replacement/modding

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2347]
Self explanatory title. Currently there is no way to replace the vignette in the main menu. Very inconvenient if you want your mod to have its own distinct look.

**Comment by Udrakan** [comment]
This would make me very happy!

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1744](https://github.com/Regalis11/Barotrauma-development/issues/1744) via [**ZenHub**](https://www.zenhub.com/)
