### ISSUE TITLE
[0.9.7] Map generation is just barely wide enough for big submarines

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2348]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When driving around in my new big sub, one of the biggest problem I run into consistently is how narrow the map is. I am really hoping for a bit more leeway here.

![Capture](https://user-images.githubusercontent.com/5086682/75087146-bbfa5300-550a-11ea-9ae6-96f66cab6bdf.PNG)

**Version**
0.9.7

**Comment by hubismal** [comment]
to add onto this, while you're revamping the mapgen, could we get a mapgen parameter that scales the tunnel width relative to the "diameter" of the ship? (eg 2.0 to make a cave with space for the width of 2 ships from all directions, 4.0 to make a tunnel generate four times the size of all ships that enter it)

**Comment by Regalis11** [comment]
@juanjp600 Addressed in https://github.com/Regalis11/Barotrauma-development/commit/24589a3?

**Comment by juanjp600** [comment]
> @juanjp600 Addressed in [Regalis11/Barotrauma-development@24589a3](https://github.com/Regalis11/Barotrauma-development/commit/24589a3)?

I doubt it, this commit simply fixes cases where the actual position of the shuttles doesn't match up with their intended position when generating the level; no further to the mapgen were made.

**Comment by Kaillera** [comment]
Consider me a bit greedy, but I think another 5%~10% would be good? I've ran into a few times where I couldn't dock on The Aeche III using all of the ports. Occasionally the map generation generates the destination outpost a bit too close to the left wall, and/or a ruin spawn on the right side of the station, which prevents docking because I don't have any ports that can align.

**Comment by thegrb93** [comment]
The width of the submarine should be calculated from its maximum diameter. I get the feeling it's just using the X-width and that would lead to this issue. Could be wrong though.

**Comment by Regalis11** [comment]
Increased the minimum size of the path in https://github.com/Regalis11/Barotrauma-development/commit/e9521c8781084d1869d0d4127c45d46e6f43b3ce (at least 15% wider than the diameter of the sub)

**Comment by Rokvach** [comment]
No issues, closing.
