### ISSUE TITLE
[UI] [0.9.7.0] User Menu Misaligment

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2350]
minor ui misalignment to set off ocd everywhere
![2020-02-22-111738_566x148_scrot](https://user-images.githubusercontent.com/47284081/75096418-09a3a980-5565-11ea-8b09-3abcb1b352ae.png)

**Comment by KuzyXD** [comment]
<details>
<summary>img 1024x768</summary>

![изображение](https://user-images.githubusercontent.com/64238958/80174688-d3d67c00-860c-11ea-8342-db365ded68fc.png)

</details>

<details>
<summary>1680x1050</summary>

![изображение](https://user-images.githubusercontent.com/64238958/80174756-15ffbd80-860d-11ea-9cb9-46e5f38c586d.png)

</details>

In version 0.9.9.0 all is fine.

**Comment by EdusFF** [comment]
Seems to be resolved by the UX update

**Comment by Rokvach** [comment]
No issues, closing.
