### ISSUE TITLE
Sub Editor - Linked Submarines file path are always forgotten on loading Main Submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2351]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Always having place down the new version of a linked submarines or reinputting the file path after modifying the linked submarine is annoying because it is always blank after load up your sub again.
![Capture](https://user-images.githubusercontent.com/5086682/75096639-981d2880-556f-11ea-8d28-44634bead0e9.PNG)

**Version**
~0.9.7

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e41e858c2d35bfcc53ca5aa792e9b1b01d0f38f7
Linked submarines now remember the file path when saving and loading the submarine

**Comment by Rokvach** [comment]
No issues, closing.
