### ISSUE TITLE
Sonar Terminal (Not Navigation) doesn't have Transducer_In

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2352]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Sonar Terminal (Not Navigation Terminal) doesn't have a Transducer_In port despite having the option to "Use Transducers"

**Version**
~0.9.7

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8435be2b8034108103c6a14cf251a55cb1d4f7d

**Comment by Rokvach** [comment]
No issues, closing.
