### ISSUE TITLE
[Unstable] [Modding] Overriding default signalitems.xml file with mod breaks signal items

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2355]
[A different mod.zip](https://github.com/Regalis11/Barotrauma/files/4241411/A.different.mod.zip)

**Description**
Overriding this file, for example in order to change item prices, breakes the game in a weird way. Everything that the file relates to gets turned to it's default state, so signal components stop working as intended when you load a sub (you cannot undock on vanilla subs, thats the most noticable one). Same with pump.xml and electricity.xml.

**Steps To Reproduce**
-Create a new mod folder in /Mods the usual way, non-core package
-Get signalitems.xml and all it's relevant files in there and refer to it in filelist.xml
-Override signalitems.xml with classic override start  and override end tags
-Start the game, enable the mod and start any match
-Open Nav terminal and press Undock
-The submarine will not undock

**Version**
Unstable

**Additional information**
Just the act of overriding the, in other ways completely vanilla item, sets everything else to default.

**Comment by Udrakan** [comment]
I've investigate the issue some more and it seems that changing more of the item xmls resets their respective devices to default!
Modifying and overriding parts of
-pump.xml
-poweritems.xml

Makes all pumps and sub batteries having default settings, even reverting their size to default.

**Comment by Kaillera** [comment]
Overriding anything related to stuff that would appear on submarines to make them run and/or functions makes any submarines that has custom values on any of them causes them to reset to default vanilla numbers.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/30dc3882673fe4016409c85a5eef490be3198c3a

**Comment by Rokvach** [comment]
Confirmed working, closing
