### ISSUE TITLE
[0.9.7] Bots - AI will try to pick up/use Items that are set on "Non Interactable"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2357]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will try to pick up/use items that are set on "Non Interactable".

**Version**
~0.9.7

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@aa6d32f. Requires testing.

**Comment by Rokvach** [comment]
The AI still tries to use the devices set to non-interactable when specifically ordered to do so.

**Comment by Rokvach** [comment]
Forgot to ping @itchyOwl

**Comment by Rokvach** [comment]
Forgot to add that they will try, but fails to do so, leaving them just standing next to the device rather than ignoring it entirely.

**Comment by Rokvach** [comment]
Seems to be working correctly with items, but not with devices.

**Comment by itchyOwl** [comment]
For some reason the pings don't work for me, so don't bother. I'll look into it.

**Comment by Rokvach** [comment]
No issues, closing.
