### ISSUE TITLE
[0.9.7] Multiplayer - Headsets spawned via Auto Fill have incorrect team ID

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2360]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Welcome back incorrect Team ID issues for the Headset. Now for headsets that were spawned in by Auto Fill in Multiplayer.

**Version**
0.9.7 5adfe9a82

**Comment by Udrakan** [comment]
Consider maybe removing them from spawn pools.

**Comment by Kaillera** [comment]
> Consider maybe removing them from spawn pools.

I actually like the random headset spawns though. It's free circuit board and plastic.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/863aa4db6b97fd89575884c0cce27a2d01e58a15

**Comment by Rokvach** [comment]
No issues, closing.
