### ISSUE TITLE
[Feature Request] Visual Range Feedback when editting Motion Detectors during gameplay

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2361]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Allow players that are editting motion detectors during gameplay to see the range box like we do in sub editors.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1743](https://github.com/Regalis11/Barotrauma-development/issues/1743) via [**ZenHub**](https://www.zenhub.com/)
