### ISSUE TITLE
[0.9.7] Secured Metal Crates does not display it's contents on mouse over.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2363]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mousing over Secured Metal Crates does not display it's content.

**Version**
0.9.7 5adfe9a82

**Comment by Regalis11** [comment]
I wouldn't consider this a bug or something we should change: I think it makes sense that you need to open the _secure_ crates to be able to see their contents.
