### ISSUE TITLE
[Feature Request] [Clarity] Apply outward velocity to limbs on dismemberment

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2364]
This is one of many feature request ideas I've had to make gore more satisfying, and should be relatively easy to implement. It's also just to make it more clear when something has died.

Right now when you shoot things dead and they dismember, they just kind of fall apart slowly with their severed limbs remaining in place. Often players waste a few rounds because the health bar is a little hard to see and dismemberment is pretty lame looking.

When limbs seperate (when you shoot or excessively damage something post-mortem), it would be nice if there was velocity (both directional and rotational for that spinning-off-effect) applied to the limb and maybe a little bit to the body that sent the smaller limb flying. This would make shooting things much more satisfying (assuming there would be a sound effect), and also make it more obvious when something is dead. Dismemberment is really static looking right now, and this is a ragdoll game with a physics engine for chrissake!

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d174cb747edfd6c54d4fabd2b38128a738b2f664

**Comment by Rokvach** [comment]
No issues, closing.
