### ISSUE TITLE
Unstable - Changing Server Name doesn't change it in the server list

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2366]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Changing Server Name doesn't change it in the server list without a restart.

**Version**
~0.9.7.1

**Comment by Kaillera** [comment]
If you use the servername command it does change it in the server browser but if any clients simply rewrites the name in the lobby, it does not.

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.0 commit https://github.com/Regalis11/Barotrauma-development/commit/c81ad82458d0f6e3570943db493ed7bacba2c5e7

Dedicated servers never updated their name on the server list (Hosted on the same machine I was checking from mind you).
SteamP2P servers do appear to change their name however.

**Comment by Regalis11** [comment]
Necro-fix incoming: fixed in https://github.com/Regalis11/Barotrauma-development/commit/db97b068b64a950672c5b468f1895f52f319ad11
