### ISSUE TITLE
HUD disappearing, cannot interact with anything

### ISSUE THREAD

**Issue by Rowanthepreacher** [Regalis11/Barotrauma#2367]
- I have searched the issue tracker to check if the issue has already been reported.

**Description**
I played one round with some friends, not as host.  No mods.  Played one round, all was well, then repeatedly tried to play another but before I could run across the hallway my HUD disappears, I have access to the chat and little jobs thingy in the top left, nothing else.  Typing number buttons to access my inventory slots does nothing.  I cannot click to interact with anything, so I'm trapped in whatever room I started in.  THe only buttons I've pressed are shift and A or D, to run to another room.
![20200225235036_1](https://user-images.githubusercontent.com/698392/75299452-fcb8db80-582c-11ea-976e-67874fbc4f11.jpg)

**Steps To Reproduce**
I'm just joining a game, and then attempting to run to the armoury or up to the shop.  EDIT: I have now tried on two different servers, it happened twice while running, and twice while swapping to handcuffs.

**Version**
0.9.6.0

**Additional information**

**Comment by Kaillera** [comment]
You handcuffed yourself.

**Comment by Rowanthepreacher** [comment]
> 
> 
> You handcuffed yourself.

I didn't even touch the handcuffs on two of the occasions.  I was just running.

**Comment by Regalis11** [comment]
Equipping handcuffs is the same as putting them on, so if you press the hotkey of the slot the handcuffs are in or double-click them, you will put them on yourself. This is definitely not intuitive and something we need to change (we have a pending ticket about it here: #1509).

If it did happen without you equipping the handcuffs, or someone else putting them on you, this might be a bug, but without having even encountered such issue and no steps to reproduce it, I'm afraid there's not much we can do to diagnose it. :/
