### ISSUE TITLE
Operate Weapon/Reactor UI is messy with submarines with large amount of guns/reactors.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2368]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At the moment both Operate Weapon and Reactor uses this kind of UI. The problem with this is that the button interfaces are unnecessarily large. It is hard to tell which button control which equipment, and it doesn't show if the equipments were on shuttles.
![1](https://user-images.githubusercontent.com/5086682/75399929-a6e74080-58cb-11ea-8710-dd6d3253d523.PNG)

I also feel that the Hold Fire command seems pretty pointless. I've never used it, and I think we should probably just get rid of it. There's usually not enough time to tell crew members to switch from Hold Fire to Fire at Will and vice versa.

I like the image that is drawn on the status terminal, and this is my revamp idea.
![idea](https://user-images.githubusercontent.com/5086682/75400070-1fe69800-58cc-11ea-89e6-0a9a30f81e5b.png)

Edit: (Maybe the word Operate in each button is too excessive as well)

Alternatively, instead of text buttons, we could probably use coilgun or railgun sprite as buttons instead?

**Version**
~0.9.7.1

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1748](https://github.com/Regalis11/Barotrauma-development/issues/1748) via [**ZenHub**](https://www.zenhub.com/)
