### ISSUE TITLE
[Unstable] No explosion animation with railgun shells

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2371]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When firing railgun shells with explosives in them, no explosion animation is played.

**Version**
~0.9.7.1

**Comment by Regalis11** [comment]
I unfortunately wasn't able to reproduce this (tested in single player and multiplayer). Do you recall which explosives this happened with?

**Comment by Kaillera** [comment]
All of the grenades.

**Comment by Regalis11** [comment]
Could not reproduce in either single player or multiplayer. Moving to Review/QA.
![rggrenade](https://user-images.githubusercontent.com/14351070/79331655-33090200-7f24-11ea-80a9-e79ccf1d6fe2.png)

**Comment by Rokvach** [comment]
Didn't the nuclear railgun have a similar issue of no explosion showing up around the patch this was reported in? I have a feeling that this was fixed at that point @Regalis11

**Comment by Regalis11** [comment]
Yeah, that was https://github.com/Regalis11/Barotrauma-development/issues/1425

It only affected projectiles that hit a submarine, so if that's where this issue occurs, it should be fixed.

**Comment by Rokvach** [comment]
Closing this as I really think that this has already been resolved.
