### ISSUE TITLE
Multiplayer Campaign - Player Name Color in server lobby does not match existing character when forced into a different role

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2374]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Player Name Color in server lobby does not match existing character when forced into a different role.

**Version**
~0.9.7.1

**Comment by Regalis11** [comment]
Seems to have been fixed as a side-effect of https://github.com/Regalis11/Barotrauma-development/commit/af91b9cb5f87b9d1668b529a6f3a9b8b51aafbde (see #3407)

**Comment by Rokvach** [comment]
No issues, closing.
