### ISSUE TITLE
[Crash] [Bug] [Modding] Selecting items in handheld fabricators crash the game.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2377]
[crashreport (22).log](https://github.com/Regalis11/Barotrauma/files/4269597/crashreport.22.log)
Attempting to make a fabricator handheld crashes the game. The itemcontainer slots also don't seem to display correctly in the fabricator hud. This should be testable/reproducable if you just make the fabricator holdable

**Comment by hubismal** [comment]
On further inspection it just seems all normal Machines are broken so that their slots don't properly display in their UIs.

**Comment by hubismal** [comment]
Specifically, whenever you interact with a fabricator in such a way that the itemcontainer slots are in your inventory's drop-up menu and not the actual fabricator HUD, pressing an item in the fabrication menu to see its ingredients will crash the game, presumably because the fabricator slots aren't where they're supposed to be. Notably, this crash won't happen if the slots are "preselected", that is if you previously selected an item when it was on the wall. Funnily enough, you can detatch a fabricator from a wall and it will continue to fabricate in your inventory, with the slots highlighted with the progress shading and greyed out inaccessibility in the drop-up slots.

**Comment by Regalis11** [comment]
Necro-fix: https://github.com/Regalis11/Barotrauma-development/pull/4256/commits/9b7835bfc05324e3f4868edbe4e10aefab5a8fe3 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
