### ISSUE TITLE
[Feature Rq] [Modding] Allow Fabricatable Items list in Fabricators, not vice versa

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2378]
Self explanatory title. Within the xml of the fabricator item, it would be nice to have a way to define a list of fabricatable items from the fabricator instead of having to refer to the fabricator from every, single, one of the items that it fabricates. Would really help compatibility with mods since there wouldn't be 200 overwrites to change trivial things like fabricator compatibility.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1749](https://github.com/Regalis11/Barotrauma-development/issues/1749) via [**ZenHub**](https://www.zenhub.com/)
