### ISSUE TITLE
[Modding] Particleemitter copyentityangle, Lightcomponent doesn't work for meleeweapons.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2380]
![2020-03-01-000222_217x190_scrot](https://user-images.githubusercontent.com/47284081/75620573-f6d63980-5b4f-11ea-99be-70622f717dd5.png)
Copyentityangle and just general Lightcomponent matching rotation doesn't seem to work for held items in StatusEffects that are a part of "components" such as MeleeWeapon, etc the way they do with repair tool, wearable, holdable. Really limits a lot of potential. for lightsabers obviously.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/20e42812bf31fd10836a1b5d069a33e92781f911

**Comment by Rokvach** [comment]
Confirmed working, closing.
