### ISSUE TITLE
When abandoning sub and beating the level with shuttle instead, recovering vessel will make sub and shuttle stuck in eachother

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2381]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When abandoning sub and beating the level with shuttle instead, recovering vessel will make sub and shuttle stuck in eachother. This makes it impossible to play any further.

Pretty sure this is caused by the shuttle not having a link to the submarine, so this will confuse where the sub should start and dock.

**Version**
~0.9 7.1

**Comment by Rokvach** [comment]
This behavior isn't present in the game anymore, if you beat a round with a shuttle the shuttle becomes your main sub now (which is still a bit strange)

**Comment by Kaillera** [comment]
> This behavior isn't present in the game anymore, if you beat a round with a shuttle the shuttle becomes your main sub now (which is still a bit strange)

The good part is you can switch back to the main sub via outpost terminal, but you will run into #4611.
