### ISSUE TITLE
[Bug] [Modding] Using Override tags on <TraitorMissions> does not work

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2384]
Self explanatory. Old missions still show up, and there is no message in the console about overriding the missions. Basically, no way to remove traitor missions even if you can selectively edit them by individually using override on the individual missions.

**Comment by Regalis11** [comment]
Finally addressed in https://github.com/Regalis11/Barotrauma-development/tree/feature/traitor-overhaul (the traitor missions are now events, and should be possible to override)
