### ISSUE TITLE
[Modding] [Feature Rq] Make TraitorMissions.xml Hotload compatible

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2385]
Not sure about the technical side of this but having the traitor missions be hotloadable without requiring a restart would be immensely helpful. I can't think of why this wouldn't work.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c8e955022a0aba44ddc061bc4c28921c10fa7ec

**Comment by Rokvach** [comment]
No issues, closing.
