### ISSUE TITLE
[Issue] Hammerhead Spawn's Fear of Coilguns Makes them ineffective

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2386]
Hammerhead spawns should be tweaked to be less afraid of coilguns. When a matriarch hits the ship, the hammerhead spawns are basically suspended in one place because they keep getting scared back and forth by the coilgun, preventing them from boarding like they're supposed to.

**Comment by itchyOwl** [comment]
I'll take a look into this at some point.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@631df49.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
