### ISSUE TITLE
[Bug] [Modding] ParticeEmitters in Affliction StatusEffects do not obey particlespersecond

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2387]
The particlespersecond in affliction status effect particle-emitters do not work. This leads to massive amounts of particles, presumably because the game is emitting a particle every frame the affliction is active. It would be nice if the particlespersecond applied to afflictions.

**Comment by Regalis11** [comment]
Could not reproduce. I think it may be an issue in the way you've configured the status effect (is disabledeltatime set to true?).

**Comment by hubismal** [comment]
sorry for the extremely late response
I somehow get a crash whenever i try to load up afflictions with particle emitters in them for some reason. notably, it seems to only happen for smoke related particles, and worked fine with the spark particle.
[crashreport (65).log](https://github.com/Regalis11/Barotrauma/files/4610975/crashreport.65.log)
[crashreport (66).log](https://github.com/Regalis11/Barotrauma/files/4610976/crashreport.66.log)
[crashreport (67).log](https://github.com/Regalis11/Barotrauma/files/4610977/crashreport.67.log)
[crashreport (68).log](https://github.com/Regalis11/Barotrauma/files/4610978/crashreport.68.log)

**Comment by hubismal** [comment]
here's also a relevant section of my xml
```xml
<Effect minstrength="30" maxstrength="69"
      minscreendistort="0.0"
      maxscreendistort="0.5"
      minradialdistort="0.0"
      maxradialdistort="0.5">
      
      <StatusEffect target="NearbyCharacters" range="300" SpeedMultiplier="0.9" setvalue="true">
		  
      
      <Affliction identifier="burn" strength="0.03" />
      </StatusEffect>
      <StatusEffect target="Character" setvalue="true">
      <ReduceAffliction identifier="burn" strength="10" />
      <sound file="Mods/Thalassophobia/Items/Jobgear/RadiationGear/geigerLight.ogg" range="500.0" loop="true" />
      <ParticleEmitter particle="smoke" particleburstamount="2" particleburstinterval="2.0" particlespersecond="2" scalemin="0.5" scalemax="1.5" anglemin="0" anglemax="359" />
      </StatusEffect>
      
		</Effect>
```

**Comment by Regalis11** [comment]
Still no luck in reproducing this. I added the particle-emitting StatusEffect from the example XML to internal damage, and it seems to emit the expected number of particles. So I think either the issue must've been fixed somewhere along the line, or the issue is somewhere else in the modded affliction.

https://user-images.githubusercontent.com/14351070/219493237-c3dc0cff-cdab-43fb-b9a3-bcfe4451a48d.mp4
