### ISSUE TITLE
[Bug] [Cheating] Enablecheats is purely clientside for some reason

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2390]
You can type enablecheats in a multiplayer round and get the rejection message from the server, but typing in something like lighting right after allows you to disable lighting anyway. Kind of a big deal!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e4fb5964eeb0e59de5ad3d85f30a134470739f4c

**Comment by Rokvach** [comment]
I am still able to use client side cheats even tho I revoked all my permissions @Regalis11

**Comment by Rokvach** [comment]
No issues, closing.
