### ISSUE TITLE
[Bug][Networking] Fabricator Desyncs

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2392]
Occasionally players will be unable to interact with the fabricator properly, including being unable to properly take things out of them and put things in (items will teleport back to original locations). Needs further investigation.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/926f46ab and https://github.com/Regalis11/Barotrauma-development/commit/e3fac1c79dd8c7dd931baa1daf822f1da0482d53, needs testing

**Comment by Rokvach** [comment]
Confirmed working correctly on the Unstable, closing.
