### ISSUE TITLE
Pumps working (sometimes) with no power.

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#2397]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the pumps are unwired from the network during gameplay some of them will still run as tho they are still being powered. 

**Steps To Reproduce**
During a match unwire the pumps, then try and use them for their intended purpose.

**Version**
The Silky Smooth Update.

**Comment by JettLand** [comment]
Yep,I've seen several times.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e890592d0c4afc101b331a62db0bec1cbc5e0ec2

**Comment by Rokvach** [comment]
Confirmed working, closing.
