### ISSUE TITLE
Problems regarding changes in the source code.

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#2399]
1. IEnumerable<string> characterFiles = GameMain.Instance.GetFilesOfType(ContentType.Character);
Can no longer convert Barotrauma.ContentFile to String, how do I go around this?

2. Character.SpeedMultiplier is now read only, how do I make it set-able?

**Comment by Regalis11** [comment]
1. Why do you need to convert the content file to a string, and what's the expected result? If you need the path of the file, you should use ContentFile.Path.
2. You should use the method Character.StackSpeedMultiplier.

**Comment by MrTeco** [comment]
1. To get the file name

**Comment by Regalis11** [comment]
To get the filename, you can use `System.IO.Path.GetFileName(contentFile.Path)`

**Comment by MrTeco** [comment]
So the purpose was to create a list containing all character files
and I found a possible solution:

```
            List<String> characterFiles = new List<string>();

            foreach(ContentFile f in GameMain.Instance.GetFilesOfType(ContentType.Character))
            {
                characterFiles.Add(f.ToString());
            }
```
