### ISSUE TITLE
Game logic inside Draw method.

### ISSUE THREAD

**Issue by shoter** [Regalis11/Barotrauma#240]
Well. Hello o/. I am actually trying to get some updates to the Barotrauma to be able to play it with my friends with some modifications. I encountered something bizarre in the code which should be refactored in my opinion.

## Actual Behavior
![](https://i.imgur.com/3fjrWOj.png)

Connect method of wire is being called inside drawing functions. I still do not understand it fully but it is also creating network events for wiring.

Some logic is propably connected with drawing and it should stay there maybe? It needs to be analyzed properly.

## Expected Behavior

This code be inside Update method of GameMain class. If it will remain here it will be harder and harder to maintain this code over time.

Also drawing of cable connections is inside drawHUD method which is confusing.

**Comment by Regalis11** [comment]
The connection panel interface uses an immediate mode GUI, so basically all the update logic happens in the same place as drawing. Personally I don't find it a major issue, but if we want to do something more complex with the interface in the future it might be better to separate them.

And honestly I don't see how drawing the connections inside DrawHUD is confusing - DrawHUD renders the connection panel interface, and the connections are a part of the interface so I think it's the most logical place.
