### ISSUE TITLE
Multiplayer - Alive characters are not saved when player is not in the game at the end of round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2400]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alive characters are not saved when player is not in the game at the end of round. Killed by desyncs and missing entities lots of times like this and people ending the round thinking it would rescue the character.

**Version**
0.9.7.1

**Comment by Regalis11** [comment]
Should be fixed in v0.10.3.0

**Comment by Kaillera** [comment]
Seems like there's no issue since 0.10.4

**Comment by Rokvach** [comment]
Closing.
