### ISSUE TITLE
[Issue] Follow-up issue about event controller(#2395)

### ISSUE THREAD

**Issue by JettLand** [Regalis11/Barotrauma#2402]
- [x] I have searched the issue tracker to check if the issue has already been reported.

I have to create a new issue because the #2395 issue is closed.

**Description**
@Regalis11 Hey,dude.I've been tried your way.
It works,but...there still have some problems,that makes me even more confused...

- When if I set the 'chooserandom=true',and there is more than one event in the set,a strange phenomenon will occur:**Only the bottom line event will take effect.**
Such as:
```
    <EventSet chooserandom="true" mindistancetraveled="0.18" minmissiontime="420" minintensity="0.0" maxintensity="1.0">
      <MonsterEvent characterfile="Husk" minamount="1" maxamount="6" spawntype="mainpath" musictype="monster" />
      <MonsterEvent characterfile="Mantis" minamount="2" maxamount="4" spawntype="mainpath" musictype="monster" />
      <MonsterEvent characterfile="Mudraptor" minamount="3" maxamount="6" spawntype="mainpath" musictype="monster" />
    </EventSet>
```

- At the same time,some eventsets didn't work which one's 'chooserandom=false'(I tested many times to confirm that).
Such as:
```
    <EventSet chooserandom="true" mindistancetraveled="0.23" minmissiontime="840" minintensity="0.0" maxintensity="1.0">
      <EventSet chooserandom="false">
        <MonsterEvent characterfile="Hammerhead"  minamount="2" maxamount="6" spawntype="mainpath" musictype="monster" />
        <MonsterEvent characterfile="Hammerheadgold" minamount="1" maxamount="3" spawntype="mainpath" musictype="monster" />
      </EventSet>
      <EventSet chooserandom="false">
        <MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="6" spawntype="mainpath" musictype="monster" />
        <MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="3" spawntype="mainpath" musictype="monster" />
      </EventSet>
      <EventSet chooserandom="false">
        <MonsterEvent characterfile="Hammerheadmatriarch" minamount="1" maxamount="1" spawntype="mainpath" musictype="monster" />
        <MonsterEvent characterfile="Hammerhead" minamount="2" maxamount="5" spawntype="mainpath" musictype="monster" />
      </EventSet>
```

- I tried to insert a 'commonness' function into the eventset,syntax correct,but it didn't work.

- And then,I tried to nest an evenset in a evenset,and set 'chooserandom=true',still only bottom line event takes effect.**(Mantis and Mudraptor will work at same time without random process)**
Such as:
```
    <EventSet chooserandom="true" mindistancetraveled="0.28" minmissiontime="1020" minintensity="0.0" maxintensity="1.0">
      <EventSet chooserandom="true">
      	<MonsterEvent characterfile="Husk" minamount="1" maxamount="8" spawntype="mainpath" musictype="monster" />
      	<MonsterEvent characterfile="Mantis" minamount="2" maxamount="4" spawntype="mainpath" musictype="monster" />
      </EventSet>
      <MonsterEvent characterfile="Mudraptor" minamount="3" maxamount="6" spawntype="mainpath" musictype="monster" />
    </EventSet>
```

Is the algorithm of the event controller wrong?

**Steps To Reproduce**
Null

**Version**
Barotrauma v0.9.7.1, Windows 7 Ultimate edition.

**Additional information**
[EnhanceRandomevents.txt](https://github.com/Regalis11/Barotrauma/files/4301566/EnhanceRandomevents.txt)

**Comment by Regalis11** [comment]
Do you mean the last event _always_ takes effect regardless of the level? I tried testing this a bit, and it does seem to behave as expected; a random event gets selected, sometimes spawning husks, sometimes mantises and sometimes mud raptors. Do note that the randomization uses the seed of the level, so if you're testing the events in the same level, you'll always get the same events.

**Comment by JettLand** [comment]
I'm prety sure the seeds random everytime.
Did you make this test base on editing vanilla xml file?
Becaue I did this through mod mechanism.

**Comment by Regalis11** [comment]
I did the previous test by modifying the vanilla file, but tried overriding it with a mod now and unfortunately wasn't able to reproduce the issue.

So, to be clear, this event set always spawns 3-6 mudraptors, but never mantises or husks? 
```
   <EventSet chooserandom="true" mindistancetraveled="0.18" minmissiontime="420" minintensity="0.0" maxintensity="1.0">
      <MonsterEvent characterfile="Husk" minamount="1" maxamount="6" spawntype="mainpath" musictype="monster" />
      <MonsterEvent characterfile="Mantis" minamount="2" maxamount="4" spawntype="mainpath" musictype="monster" />
      <MonsterEvent characterfile="Mudraptor" minamount="3" maxamount="6" spawntype="mainpath" musictype="monster" />
    </EventSet>
```

What about this one? It should randomly spawn hammerheads and hammerheadgolds, OR threshers and bone threshers, OR a matriarch and hammerheads. Does it always spawn the matriarch and 2-5 hammerheads?
```
    <EventSet chooserandom="true" mindistancetraveled="0.23" minmissiontime="840" minintensity="0.0" maxintensity="1.0">
      <EventSet chooserandom="false">
        <MonsterEvent characterfile="Hammerhead"  minamount="2" maxamount="6" spawntype="mainpath" musictype="monster" />
        <MonsterEvent characterfile="Hammerheadgold" minamount="1" maxamount="3" spawntype="mainpath" musictype="monster" />
      </EventSet>
      <EventSet chooserandom="false">
        <MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="6" spawntype="mainpath" musictype="monster" />
        <MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="3" spawntype="mainpath" musictype="monster" />
      </EventSet>
      <EventSet chooserandom="false">
        <MonsterEvent characterfile="Hammerheadmatriarch" minamount="1" maxamount="1" spawntype="mainpath" musictype="monster" />
        <MonsterEvent characterfile="Hammerhead" minamount="2" maxamount="5" spawntype="mainpath" musictype="monster" />
      </EventSet>
```

How exactly are you testing the events? Do you start a new campaign, load a previous campaign save, start a sandbox round...?

**Comment by JettLand** [comment]
Yep,that 1st event set you did mention always spawns 3-6 mudraptors,never mantises or husks.
The 2nd event set spawns nothing every time.
I always testing at mission and sandbox mode both,because campaign mode's couple rounds at  periphery can't reach the difficulty what I set to trigger spawns.

**Comment by JettLand** [comment]
I've been try testing again with my mod 'Level Difficulty Enhance 2.0'.
Still only mudraptors spawned.
Randomevent.xml is here:
[EnhanceRandomevents.txt](https://github.com/Regalis11/Barotrauma/files/4307629/EnhanceRandomevents.txt)
I inserted some 'commonness' functions into the event sets.
