### ISSUE TITLE
[0.9.7.1] Unable to get through docking port

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2404]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The problem occurs in the following situations:
1. Attempt to enter outside
2. Attempt to cross the shuttle to the submarine
3. Attempt to get out of the shuttle when the access hatch is broken

Tested on submarines: Svarog, Sever, Catfish, Indra.
Below is attached a screenshot and video.

**Steps To Reproduce**
Try to get in the submarine through the docking port.

**Version**
0.9.7.1 Silky Smooth

**Additional information**
Svarog: https://www.youtube.com/watch?v=LCx_HcRELZc
Sever: ![2324](https://user-images.githubusercontent.com/29980468/76147674-f558c400-60af-11ea-9986-ec98a668c2a5.png)

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a9adc7f6507c884b4d76ba982533f44e909f63de

**Comment by Kaillera** [comment]
Had sighting of this happening in 0.9.1001.0 on my custom sub Corsair. Just wasn't able to climb into the outpost from my submarine at one point.

**Comment by Rokvach** [comment]
If the outpost door was closed that would be a different issue to this, I think this issue is most commonly seen when trying to enter the submarine from a respawn shuttle and while the door appears to be open you aren't actually able to go through it, I haven't seen this happening in a while but we mainly do play only campaign during community testing sessions now days.

**Comment by Rokvach** [comment]
Because its so hard to determine if this is fixed or not as the issue was quite rare to begin with and there hasn't been any sightings of this happening during Unstable testing, I think its better to just close the ticket and re-open it if the issue does come up later on.

**Comment by Kaillera** [comment]
Pretty sure I said it happened in 0.9.1001.0
