### ISSUE TITLE
[Issue] [UI] Extra Jobs go Offscreen

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2405]
More modded-in jobs now go offscreen as opposed to when they used to wrap down. Proably happened during the UI update.
![2020-03-07-151106_296x139_scrot](https://user-images.githubusercontent.com/47284081/76152562-756a3400-6086-11ea-8a15-ef549404941f.png)
Might be a duplicate, was unable to find a similar issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8452a2e5701258eb9f1eb7bb369a08830f6cc6ed

**Comment by Rokvach** [comment]
Confirmed working, closing.
