### ISSUE TITLE
[0.9.7.1] Infinity electric experience.

### ISSUE THREAD

**Issue by MyNameIsEpic** [Regalis11/Barotrauma#2406]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The shuttle navigator is infinitely broken when flooded. Because of what you can repair it endlessly.

Tested on submarine: Typhon.

**Steps To Reproduce**
Just flood shuttle and open/close repairing menu when progress is underway.

**Version**
Windows
Game version: 0.9.7.1 Silky Smooth

**Additional information**
Video: https://www.youtube.com/watch?v=xlPeQT7auqk

**Comment by Regalis11** [comment]
Duplicate of #2389
