### ISSUE TITLE
Submarine editor components/sensors false =______ and cannot edit value

### ISSUE THREAD

**Issue by Juicins** [Regalis11/Barotrauma#2408]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the components and some sensors have no output when false, this has wasted a lot of my time and would easily cause most people to lose interest in the editor
**Steps To Reproduce**
PLEASE ADD EDITTING CAPABILITIES SO WE CAN FIX OURSELVES IF NECESSARY, ALSO WITH LABELS
-------ALSO THERE SHOULD BE A SIM MODE INT SUB EDITOR.. I HAVE TO SAVE START A NEW GAME EVERYTIME I WANT TO TEST, FFS

**Version**
windows, silky smooth

**Additional information**

**Comment by Regalis11** [comment]
> the components and some sensors have no output when false
This is intentional. In many cases you only need an output when the sensor is detecting something, but if you also need something to be sent when nothing is detected, you can modify the "false output" value of the component.

> ALSO THERE SHOULD BE A SIM MODE INT SUB EDITOR.. I HAVE TO SAVE START A NEW GAME EVERYTIME I WANT TO TEST, FFS
We've actually just recently implemented this in our private repository, so it's coming soon. :) In the meanwhile, you can use the console commands to test the submarine faster: the command "game" switches to the game screen, and the command "editsubs" switches back to the sub editor.

**Comment by Juicins** [comment]
how? I try to change the values and nothing happens

**Comment by Juicins** [comment]
the issue is that the writeable values aren't changing, that's awesome though

**Comment by Juicins** [comment]
also the gate styles (or, and, ect) are listed on the wiki as 0 or 1 outputs which are not their standard setups this is counter intuitive and will discourage most knew to the editor (like me, but I am stubborn as f#$%). I believe in most scenarios you would want on and off and in the rare youd only want just one condition (door/pump/light/disconnect controls mostly want 2 states, most sensors you want to know active and clear).

**Comment by Juicins** [comment]
Writeable values also includes labels. You an only select from the list, not make your own.

**Comment by Regalis11** [comment]
You need to press enter after you've entered a new value (also applies to labels).

**Comment by Juicins** [comment]
not required for editing other values like motion detector ranges, again counter intuitive

**Comment by Juicins** [comment]
though thank you for that, just saying if things aren't straight forwards and go against what seems logical then people will give up on it. if it works in one instant then it should work in all similar instances. at the very least there should be pointers like use spacebar to merge hull points or a save button which is the equivallent of hitting enter... suggestions. also heavily suggest having the gates be 1 and 0 as their basic setup as this is how they work in real life and how they're listed on the wiki. that's all, thank you for the support, hope you consider the suggestions

**Comment by Juicins** [comment]
sorry... not components only have 1 output and cannot be edited, smoke detectors the same.. bangs head off desk

**Comment by Regalis11** [comment]
I fully agree, there are tons of things in the sub editor (and in the game in general) that aren't as intuitive as they should be, or not communicated to the player clearly enough or at all. Making the text fields update the value without having to press enter (just like the number fields) is definitely something we should make consistent. I'm not sure if we should change the behavior of the logic gates though, as changing it now might cause issues in older subs and make it equally unintuitive to those sub builders who've gotten used to the previous default behavior over the years. Something we need to consider though.

>not components only have 1 output and cannot be edited
Not components flip a 1 signal to 0 and vice versa, what kind of behavior are you expecting? If you want to output an arbitrary signal, you might want to use the signal check component instead.

>smoke detectors the same
That's a good catch, it should definitely be customizable like the other sensors!

**Comment by Juicins** [comment]
it should, definitely but its description states : sends a signal when the input is not receiving a signal
as you cannot see what is going on without testing it would be assumed that like all the other gates it would be missing its false state.. sorry if it works the way it should.. just not expecting with the other gates working counter intuitive and its description lol, why would that work standard and not the others?

**Comment by Juicins** [comment]
if the gates were changed in the editor how would that affect already built subs? wouldn't the values be saved in the finished/in progress vessels? and the people who already build subs would know how to edit the states in their future builds if they so chose. list it in patch notes as well, they'll figure it out. its about not discouraging new players that I would worry about, just my thought on that

**Comment by Regalis11** [comment]
I see your point. I'm sure you're not the first person who's been confused about the behavior of the logic components, but I have to say I personally haven't seen many complaints about it this particular issue during all the years we've used the current behavior. Aside from the not component, the logic gates work as described in the tooltip, sending a signal only when the condition is filled. So I'm not fully convinced the empty false output is _that_ discouraging or counter-intuitive to most players.

But in any case, we do definitely need to make the descriptions more accurate and make sure the behaviors are consistent between the components.

**Comment by Juicins** [comment]
most people don't complain they just give up, maybe don't even realize the issue to report it. ive never done a bug report before this, for any game, but I like your game a lot and would like to help you improve it. also, I do controls for a living lol

**Comment by Juicins** [comment]
Not gates are false=1 true= ____ , tested, there is no desk left to bang head off of (small loop crashes once "not" is satisfied)
also door outputs ect should have editable states.

**Comment by Juicins** [comment]
sorry, water sensors were the issue after they have gotten damp they don't always reset.. changed state in game and worked intermittently after

**Comment by Regalis11** [comment]
Pressing enter to set the string values is no longer required as of https://github.com/Regalis11/Barotrauma-development/commit/73763ce8

**Comment by Rokvach** [comment]
No issues, closing.
