### ISSUE TITLE
[0.9.7.1] Multiplayer - Fabricator overflow green crafting bar when hooked up to Battery/Relay and never finishes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2409]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In Multiplayer, when battery is directly connected to Fabricator or using a Crafted/Engineer Spawned Relay Component and is crafting, Item will never finish crafting with an overflowing green crafting bar.

When you move the charge rate slider on the battery, the charged % on the battery reset back to whatever it was before as if power was never drawn from the battery for the crafting.

Singleplayer works just fine.

**Version**
0.9.7.1

**Comment by Kaillera** [comment]
After watching the relays for a bit, I think it has something to do with the fact that the batteries are trying to output half of the power necessary to run the fabricator.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/926f46ab and https://github.com/Regalis11/Barotrauma-development/commit/e3fac1c79dd8c7dd931baa1daf822f1da0482d53, needs testing

**Comment by Kaillera** [comment]
[0.9.801] So now in Multiplayer when I connect fabricators directly to battery, it won't draw any power to craft with.

When I wire up the battery to a relay to the fabricator in Multiplayer, the relay claims there's a power and load of 500 to the fabricator but it still says insufficient power. When I disconnect the relay from the fabricator and hook it back on to the power in pin a second time, it will now be able to craft.

**Comment by Rokvach** [comment]
There hasn't been any sightings of this happening for a while now, save to say that its working correctly. Closing.
