### ISSUE TITLE
[0.9.7.1] Wiring - When opening doors/hatches, wire points are placed. When Climbing Ladders, unable to remove wire points.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2410]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When running around to wire two ends of a wire, opening doors/hatches places down wire points. When climbing ladders, you're unable to remove wire points with right click.

**Version**
0.9.7.1

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1750](https://github.com/Regalis11/Barotrauma-development/issues/1750) via [**ZenHub**](https://www.zenhub.com/)
