### ISSUE TITLE
[0.9.7.1] When electrocuted for adding wire to pin, wire is not connected to pin, but the character has wire coming out of the item as if it was

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2411]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you attach a new wire to a connection pin and get electrocuted, the pin isn't connected, but the wire is still drawing between the object and the character as if the connection was made to the pin when it isn't.

**Version**
0.9.7.1

**Comment by Regalis11** [comment]
I was only able to reproduce this in multiplayer. Not sure if there's some situation where this can also occur in single player, but if not, this should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1fa8bd65cd93ace5a36716800bbb99fe34ad0bd8

**Comment by Kaillera** [comment]
Yeah this was during Multiplayer as well.

**Comment by Rokvach** [comment]
No issues, closing.
