### ISSUE TITLE
[Modding] [Crash] Turrets crash game upon launching item without physicsbody

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2412]
A simple way to reproduce this would just be to remove the <Body> tag from the coilgunbolt.

**Comment by hubismal** [comment]
[crashreport (36).log](https://github.com/Regalis11/Barotrauma/files/4308218/crashreport.36.log)
appropriate crashlog

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/20036ddcb29039a21d290d7357bff65550dfa560

**Comment by Rokvach** [comment]
Cornfirmed working, closing.
