### ISSUE TITLE
Sub Editor - Crash when adding a Additional Submarine .sub that is completely blank

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2413]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Adding a additional submarine .sub file that was saved with nothing in it causes a crash.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4308247/crashreport.log)

**Steps To Reproduce**
Enter Sub Editor
Don't place down anything
Save it (Blank.sub)
Open a different sub
Add Additional Submarine (Blank.sub)
Crash

**Version**
~0.9.7.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d40419eaead09243ca35a54a6f7066507a60b251

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
