### ISSUE TITLE
[Modding] [Issue] Item desnity doesn't affect in-air items

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2416]
It's annoying that we can't affect in-air items to create things like helium balloons using density. This is a feature you would expect in the game so I am pretty sure this qualifies as an issue since irl density would definitely affect the fallspeed the way density in the game currently affects underwater bouyancy.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1759](https://github.com/Regalis11/Barotrauma-development/issues/1759) via [**ZenHub**](https://www.zenhub.com/)
