### ISSUE TITLE
[Bug] Sub editor ambientlight is not representative of actual ingame ambientlight now

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2419]
Self explanatory. This gives sub builders the wrong impression of how their subs will look in actual gameplay.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3b55f84b287942e14a4878e4de54a4ea164772a

**Comment by Rokvach** [comment]
Ticking on lighting in toggle visibility doesn't seem to be doing anything @Regalis11

**Comment by Rokvach** [comment]
Nvm had light cheat enabled from prior testing which carried over to the editor. No issues. Closing.
