### ISSUE TITLE
Traitor "oxygen experiment" 2nd obective is impossible

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#2420]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The traitor mission in which a player is required to sabotage the oxygen generator for 120 seconds is impossible, as the objective following it is broken and displays variables instead of defined objectives

https://imgur.com/a/t3ew5LN

**Version**
0.9.7.1

**Comment by OverwatchVoice** [comment]
Update: The mission CAN be completed, but the game doesn't show you what the requirement is.

**Comment by Regalis11** [comment]
This mission has been removed, so the issue is no longer relevant
