### ISSUE TITLE
Game crashes, but server is now full so can't rejoin

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2421]
- [x] I have searched the issue tracker to check if the issue has already been reported.

You shouldn't lose your slot until your player dies.

**Comment by thegrb93** [comment]
Would also be nice if you didn't get stunned during this time as well. People tend to jack your stuff.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1751](https://github.com/Regalis11/Barotrauma-development/issues/1751) via [**ZenHub**](https://www.zenhub.com/)
