### ISSUE TITLE
Two crashes around same area of the ship

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2422]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crashes

**Steps To Reproduce**

**Version**
0.9.7.1
Windows

**Additional information**
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/4316197/crashreport.6.log)
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/4316198/crashreport.5.log)

**Comment by ekqvist** [comment]
Your crash reports indicate that you're still playing on 0.9.6.0. Based on the crash reports extreme similarity, this should be fixed for 0.9.7.1, see #2182.

**Comment by thegrb93** [comment]
No, I'm definitely running the silky smooth update. Pretty sure you just failed to fully fix the crash.

**Comment by thegrb93** [comment]
Maybe it didn't dump a crash logs, the date on those are old, but there's no new crash logs. Did they get changed?

**Comment by ekqvist** [comment]
You should still receive crash reports if the game crashes. If it's another issues, crash reports or some steps to reproduce the issue are needed.

**Comment by thegrb93** [comment]
If I get new reports I'll open another issue. Otherwise, I'll open an issue about dumps not being saved.

**Comment by thegrb93** [comment]
Can confirm I'm not getting crash reports anymore.
