### ISSUE TITLE
"Door/Hatch with Buttons" are hard to click on from outside the sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2424]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using "Door/Hatch with Buttons" for entering and exiting subs, players outside has a hard time highlighting them to click to toggle and enter the sub.

**Version**
~0.9.7.1

**Comment by JettLand** [comment]
You have to get pretty close to open the "Door/Hatch with Buttons" when you at the outside of sub.
It's been a long time with this issue.

**Comment by hubismal** [comment]
It looks like the game requires you to be registered as "inside" of the sub (synced with the subs movement) in order to operate the door, at least from what I can tell.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3015cd8f094da3757af1e8331bea712d5c6f95d

**Comment by Rokvach** [comment]
No issues, closing.
