### ISSUE TITLE
Human/Humanhusk Characters change modded limb graphics on death.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#243]
I still need to test what/why or even if this is truely an issue, but the creator of BTE had an issue regarding this in the past and found he needed to replace the original content folders assets to prevent it.

I cannot see a root cause of this issue which could change the sprite, but I have been provided an image for this from BTE's author:
https://cdn.discordapp.com/attachments/405758115808673802/405763898713571339/lepants.png

Essentially the detached leg is the modded legs (Which have no pants) while the still attached leg has suddenly swapped to the unmodified human characters leg from the Vanilla content package.

This could be caused either by dismemberment or death, the characters have the correct graphic on creation.

**Comment by Regalis11** [comment]
I'm pretty sure this happens because the game instantiates the humanhusk characters from the vanilla config file. Should be easy to fix, I'll remove the hard-coded path and make the game search for the correct config based on the name of the character.
