### ISSUE TITLE
[0.9.8.0] Pink blocks on Additional Submarines in Sub Editor

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2430]
![](https://cdn.discordapp.com/attachments/668819422919524352/688060992961511549/Capture.PNG)

Don't know what those pink block on additional submarines are.

**Additional Informations**
My shuttles aren't supposed to be loaded up in this position either. I don't know what forced them far left and into the middle of the sub.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e719958d7b1f36678a7f9f6d9995e4d16718c8a

**Comment by Rokvach** [comment]
No issues, closing.
