### ISSUE TITLE
[0.9.8.0] !!!Very Frequent Crash!!! - Barotrauma.AttackResult ApplyAttack

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2432]
Something was attack my submarine's shell. Was going to investigate but it crashed.

[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4330680/crashreport.3.log)

**Comment by Kaillera** [comment]
Got it again, but this time immediately after I got shocked from a alien coil. I'm not sure if it's a coincidence, or it was from a creature attacking the sub while I was in the ruins.

[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4330823/crashreport.4.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4fe9f70ef4837ea73e33c1969aa289e184961bf4

**Comment by Rokvach** [comment]
Wasn't able to reproduce after the fix, closing.
