### ISSUE TITLE
Unable to cut through double layered walls with Ancient Weapons

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2434]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When cutting a double layered walls, Ancient Weapons cannot damage the wall behind the front one even though it's completely destroyed. Plasma Cutter is not affected.

**Version**
~0.9.7.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/772be3269da6901945270220e1becd1e294b2676

**Comment by Rokvach** [comment]
No issues, closing.
