### ISSUE TITLE
Characters are interrupted from from fixing broken doors and hatches once they have reached 50% repaired ([0.9.8.0] Bots are confused by this too)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2436]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When characters are repairing doors and hatches from a broken state, they are interrupted at 50%, kicking them off from grabbing the door.

In Multiplayer, there may be a desync between the server and client whether or not the door is actually fixed enough when it reached 50%, and it's pretty hard to grab onto the door/hatch during the desync. Welding the door a split second to bring it up past 50% solves this for now.

Lastly, in 0.9.8.0, the Bots can only repair up to 50% due to the problem above. They are also standing next to these 50% doors/hatches from a previous repair wondering if they should fix it or not (they don't, they just stay there).

**Version**
~0.9.8.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c223085df05ddbe621256dcf743d399bea29fb59

**Comment by Rokvach** [comment]
No issues, closing.
