### ISSUE TITLE
Internal Wall Spontaneously Leaks when Damaged

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2438]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An internal wall with an orientation perpendicular to the hull section it covers spontaneously leaks when damaged.

**Steps To Reproduce**
- Create 2 rooms (vertically) with walls and hulls.
- Place a vertical wall piece in the center of the central horizontal wall section, making sure it only covers a horizontal section of the hull. (see attached reference image "malaco mid aft_e")
- Cut into the vertical wall piece

NOTE: This also happens with horizontal wall pieces covering vertical hull sections.
See reference image "spontaneous wall leak illustration" for a summary of the issue as an image

**Version**
0.9.7.1 revision 6ec75fa2a
Windows 10

**Additional information**
Reference image:
![malaco mid aft_e](https://user-images.githubusercontent.com/58775950/76691135-fe9ce000-661d-11ea-8003-c0a7f29dac42.jpg)
Issue Summary in one image:
![spontaneous wall leak illustration](https://user-images.githubusercontent.com/58775950/76691136-0066a380-661e-11ea-9ed7-df74222e3046.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5692d27f0df565bd250c6c5f2d85ab24623e9f6b#diff-4b35e1ed73a9a29223ec17467417e398

**Comment by Rokvach** [comment]
No issues, closing.
