### ISSUE TITLE
When two docked ships experience a collision, players can be clipped through one into the other

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2440]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://streamable.com/xnfj1

**Steps To Reproduce**
Two docked ships crash and the impact direction is one ship into the other

**Version**
0.9.7.1

**Comment by Kaillera** [comment]
There's a possibility that the admin/host teleported you.

**Comment by thegrb93** [comment]
It happened at exact time of impact so I hightly doubt that.

**Comment by thegrb93** [comment]
Reviewing the footage I see another player also teleported in shortly after so you're probably right.
