### ISSUE TITLE
Crashing while opening the game.

### ISSUE THREAD

**Issue by martcraft** [Regalis11/Barotrauma#2442]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The loading was interrupted by something unknown.

**Steps To Reproduce**
It happens while I open the game and I'm not doing anything.

**Version**
0.9.7.1 on windows 10

**Additional information**
After crashing steam stated that the game was still running. It was fixed by force closing steam.
it also happend three times, with the EXACT same error.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4334543/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4334558/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4334559/crashreport.3.log)

**Comment by Regalis11** [comment]
The crash report seems to imply that you're missing some files that are required for the game to run (at least "Data\ContentPackages\Vanilla 0.9.xml"). 

You might want to try right-clicking the game in your Steam library, and selecting Properties -> Local files -> Verify integrity of game files. That should restore the missing files.

I'm not sure how the file could've gone missing though. Were you using any mods?

**Comment by martcraft** [comment]
I validated the files and indeed some files were missing, maybe this happend because I removed some mods via the mod manager? Anyway, my game doesn't crash anymore... thank you!
