### ISSUE TITLE
Ladder Sprite Depth

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2443]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ladders accept custom sprite depth values in editor and seem to reflect the proper depth in editor.  In-game or after loading in editor, ladders go back to default sprite depth of 0.510.

**Steps To Reproduce**
Place ladder in editor and modify sprite depth.  Save and load the editor file or test in-game.

**Version**
v0.9.7.0
Windows 10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/daea9d815a1e835c1b6758c6068a3ad94bfab91d

**Comment by Rokvach** [comment]
No issues, closing.
