### ISSUE TITLE
Command Menu and Non-Interactable Items

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2444]
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items can be non-interactive, which greatly adds sub creators capability to make decorative static objects.  Making something non-interactive does not remove it from the command menu, however.

Some objects such as engines/nav terminals (including legacy) can make for great static decorative objects and have stats changed to not be interactive/wired so are static.  When using Command menu, these non-interactive objects show as possible options for commands, cluttering the screen with objects meant to be static/decorative.

**Steps To Reproduce**
Add an additional Nav terminal; make non-interactive then in-game, issue a steer command.  Multiple Nav terminals will show.

**Version**
9.7.x
Windows 10

**Comment by rav2n** [comment]
I also want to add that there are cases of breakdown of non-interactive objects, which causes the display of the breakdown icon, which can confuse players and is simply annoying visually.

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by ekqvist** [comment]
Even though this was closed a while back, I would like to note that repair icons being drawn on noninteractable items should now be disabled with Regalis11/Barotrauma-development@8284f3c
