### ISSUE TITLE
[0.9.801] Radio Chat key stops functioning

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2447]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During one of the round in campaign, all of the sudden the Radio Chat key does not work. Pressing Chat key and manually inputting r; to radio chat still works.

Rebinding doesn't fix it.

**Version**
0.9.801

**Comment by 3e849f2e5c** [comment]
Fixed in [6741256](https://github.com/Regalis11/Barotrauma-development/commit/3506dba993330a3d68691128492fc14d4d8bd5d1)

Code was checking if the character's speech impediment was below 0 when it should have checked if it was below 100

**Comment by Rokvach** [comment]
No issues, closing.
