### ISSUE TITLE
[Modding] itemdamage <Attack> property doesn't work for meleeweapons

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2448]
Self explanatory. While itemdamage works for creature attacks like mudraptors in order to break down doors, the one damage of itemdamage that things like stun batons have don't work at all.

**Comment by Regalis11** [comment]
Melee weapons don't collide with any items by default. If you want to make an item damageable by other items, you need to add a "damagedbymeleeweapons" attribute to it (you can see an example of how it's used in the mudraptor egg config in creatureloot.xml)

**Comment by hubismal** [comment]
Oh, I assumed that doors were a type of structure or something seperate of an item, I didn't know the isdamagedbymeleeweapons or whatever would work for them.
