### ISSUE TITLE
High DPI awareness not set on Windows

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#2450]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When DPI is raised through the settings on Windows, the entire window is scaled up, which breaks the game when attempting to render at native resolution.

**Steps To Reproduce**
- Set "Make everything bigger" setting to 125% or 150%
- Set the ingame resolution to the highest it can go
- Set the game to fullscreen

**Version**
v0.9.7.1, Windows 10 x64

**Additional information**
N/A

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9fa950374a60f32cdc4355c8dfbd913bda588931

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
