### ISSUE TITLE
[Rokvach Approved Feature Request] [Modding] Allow projectiles to not have physicsbodies

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2451]
![2020-03-17-150916_568x70_scrot](https://user-images.githubusercontent.com/47284081/76898144-2335c980-6863-11ea-88b1-13879151d8df.png)

I know you just fixed the crashing related to this for 0.9.801, but it would be nice if projectiles without physicsbodies could be fired from turrets so that they wouldn't be affected by physics or collisions. You could spawn stationary things in the air or something like the current `nuclearaftereffectemitter` to apply effects to nearby people with the turret, or other things that aren't necessarily designed to be shot at something. Turrets are pretty much the only way you can load something in another item and have it spawn at another, so I think extension of functionality is pretty important. 

Ulterior motive:
I want to make a "gas turret" that essentially fires an invisible emitter object that removes itself after a bit. You will be able to load gas canisters into the loader and have gas come out of the "vent", which is really just a turret that fires "gasemitters" (invisible projectiles that emit gas particles and affect people around it). Obviously the problem here is that the projectiles are affected by forces like gravity. It would be enormously helpful to have this not just for my gas emitter but for other things people want to spawn at turrets that can't be affected by gravity or movability.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1752](https://github.com/Regalis11/Barotrauma-development/issues/1752) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Regalis11** [comment]
Also, as a note, you can create items that aren't affected by gravity (or any other external forces) by making their physics bodies kinematic. For example: 
`<Body width="100" height="100" bodytype="Kinematic"/>`

**Comment by hubismal** [comment]
thank you so much you madlad

**Comment by Regalis11** [comment]
It should spawn at the position of the turret just like a normal projectile.
