### ISSUE TITLE
[0.9.801] Gaps on Selkie

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2453]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There are no gaps on the bow of the shuttle, and also the compartments are not linked.
![Selkie](https://user-images.githubusercontent.com/29980468/76918856-56ff0680-68d8-11ea-97f7-24526fe8a741.jpg)

**Version**
0.9.7-0.9.8

**Comment by danielasteljoki** [comment]
Oops. Fixed in f83e235.

**Comment by Rokvach** [comment]
No issues, closing.
