### ISSUE TITLE
[0.9.801] [not important] Incorrect display of layers

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2454]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After the last update, the depth of the layers began to work better, but also because of this, many submarines need to be updated, this also applies to vanilla submarines. For example, on the Kastrull in the subtopcenterthey began to overlap the inscriptions, and this is noticeable only in the game, in the editor the order of the layers can be correct. I suggest that the signs and wires have the same layer depth and preference is given to wires.

Typhon2
![Typhon2](https://user-images.githubusercontent.com/29980468/76920543-c971e580-68dc-11ea-9d25-65cfa65b7ed8.jpg)

Kastrull
![Kastrull 01](https://user-images.githubusercontent.com/29980468/76920547-ce369980-68dc-11ea-98c5-734bec16f2b0.jpg)

Kastrull
![Kastrull 02](https://user-images.githubusercontent.com/29980468/76920552-d0005d00-68dc-11ea-9b3f-204aec192059.jpg)

**Steps To Reproduce**
Check the correct display of layers on vanilla submarines in the game

**Version**
0.9.7-0.9.8

**Additional information**
Also on Typhon there is a non-standard view of drain valves. Perhaps the sprite capture area from the image has been changed.
![Typhon 02](https://user-images.githubusercontent.com/29980468/76920777-66348300-68dd-11ea-94e8-32bf5aa2281b.jpg)
![Typhon](https://user-images.githubusercontent.com/29980468/76920786-69c80a00-68dd-11ea-948f-58b9178439ae.jpg)

**Comment by Rokvach** [comment]
No issues, closing.
