### ISSUE TITLE
Component Values does not changes until you press Enter on each line that were changed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2455]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When editting Component Values during gameplay, unless you press Enter on each lines that were changed, those values do not take effect if you click off of the component. When you check what's wrong with the values, you'll see the player input value even though it's using the old values. This may confuse players trying to debug their logic circuits when they keep forgetting to press Enter.

**Version**
~0.9.801

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/73763ce83065b2587325ce3ec05355139b14b3ad

**Comment by Rokvach** [comment]
Tested, changed value and closed the interface and my client crashed with this error @Regalis11 

![valueissue.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/47a41a77-1d2b-4fde-acc6-4e4fca428cca)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/acb243fec80502b8a40b6951e9778e2ab2abceb2

**Comment by Rokvach** [comment]
No issues, closing.
