### ISSUE TITLE
[0.9.801] Loose Panels are not translated

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2456]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The name of these items is not translated into other languages, even if there are translation lines in the localization file. Checked in Russian and Deutsch.

**Steps To Reproduce**
Check translation "Loose Panel" in other languages.

**Version**
0.9.7-0.9.8

**Comment by Regalis11** [comment]
https://github.com/Regalis11/Barotrauma-development/commit/aad011d7299a653d25386897141d949462ce9450

**Comment by Rokvach** [comment]
No issues, closing.
