### ISSUE TITLE
Thermal Artifact creates fire effect on the floor when suspended in the air

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2457]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Especially when a thermal Artifact is in a artifact holder, you see flames on the ground when the holder is several feets in the air.

**Version**
~0.9.801

**Comment by Regalis11** [comment]
This is not a bug, the fire spreads to the bottom of the hull.
