### ISSUE TITLE
[0.9.7.1] Player Profile Window in lobby

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2458]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The inscriptions on the buttons do not fit, in languages where the word length is different from English. Regarding Russian, I thought about how to shorten the words and realized that nothing good would come of it. Players simply may not understand the purpose of the buttons. Checked in Russian and Deutsch.
![332](https://user-images.githubusercontent.com/29980468/76922427-b31a5880-68e1-11ea-9310-e8561d2a58e3.jpg)
![333](https://user-images.githubusercontent.com/29980468/76922429-b57cb280-68e1-11ea-8764-3f9340787de6.jpg)
![331](https://user-images.githubusercontent.com/29980468/76922434-b7df0c80-68e1-11ea-9310-03b732c2c4e5.jpg)

**Steps To Reproduce**
Open a player profile in the lobby with a language setting other than English.

**Version**
0.9.7-0.9.8

**Additional information**
Although I wrote the 0.9.7.1 version, I think it is also acceptable for an unstable build. I could not check.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7314b72b84a9033c2a6e0f7a85bf4fc84419f03e

**Comment by Rokvach** [comment]
No issues, closing.
