### ISSUE TITLE
"Toggle visibility" panel gets in the way

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2459]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Well, since the whole progressive society is silent, then I will say: new menu "toggle visibilty"  is uncomfortable. I honestly tried to get used to it, but it causes nothing but irritation. Three button clicks against one click in the old interface: 1) Open the drop-down menu. 2) Turn on the desired view 3) Close the drop-down menu so that it does not hang in the middle of the screen.

The third point that causes the most inconvenience.

If you decide to keep the menu looking that way, please make this window self-closing by analogy with the item parameters window (which appears on the right).

**Version**
0.9.7-0.9.8

**Additional information**
What would you correctly understand this is not the whining of a single player, I heard about the same from other sub-builders spending enough time in the editor.

**Comment by HalfdeadKiller** [comment]
Please, move it somewhere. Here is an MS Paint example. Bonus points if it closes when you click on an item and the item properties menu pops up, and then re-opens when you click off of the item.

![MenuExample](https://user-images.githubusercontent.com/16188887/76924945-e808ba00-68a5-11ea-98b5-0564b2346bd2.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/76ca495db1174ee41886502a3c0f1fc1ab290d81

**Comment by Rokvach** [comment]
No issues, closing.
