### ISSUE TITLE
Looting a player to slots 9 and 0 causes health menu to pop up

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2460]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dragging an item from a body to slot 9 or 0 will pop up the health menu

**Version**
Windows 0.9.7.1

**Additional information**
https://streamable.com/g6nd1

**Comment by Regalis11** [comment]
Fixed in the Unstable version, fix coming up in the next patch!

**Comment by Rokvach** [comment]
No issues, closing.
