### ISSUE TITLE
Multiplayer - Hard to open Auto Doors with low frame rates

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2461]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For some reasons in Multiplayer and when your frames are dipping below 20fps, it's pretty hard to open Doors with Auto Close Logic that uses Motion Sensors. The doors would shut after opening multiple times before the door would stay open.

**Version**
~0.9.801

**Comment by civilCornball** [comment]
Is this in vanilla ships?

Because what you're describing is an improperly-wired autodoor, where a signal is **output** to the delay component.
