### ISSUE TITLE
Unable to swim into hull from outside that aren't at least 7x7

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2463]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When players make hulls like so:
![Capture](https://user-images.githubusercontent.com/5086682/77008040-c9550280-693b-11ea-9f16-384f61136de4.PNG)

They aren't able to swim into the hull from the outside. Unless the hull is at least 7x7, This seems to be what shuttles with small airlocks experiences as well, being unable to enter and exit.

Practical usage: Prevents the instant flood of the hulls behind in a split second of a door opening or hull breach.

**Version**
~0.9.7.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/18d2af2f6bc04693a38ac09ceba681797020a689

**Comment by Rokvach** [comment]
Reported to still be an issue, was this included in the 0.9.9.0 Unstable build?

**Comment by Rokvach** [comment]
Reported being fixed, closing.
