### ISSUE TITLE
[0.9.801] Bots - Gunners don't react to pressure fast enough / stops shooting when hull is flooding

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2466]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Small gun rooms like the ones that exist on the Remora when breached by threshers and hammerheads, bots doesn't react fast enough to pressure, and will stop shooting targets when it's flooding.

https://cdn.discordapp.com/attachments/668819422919524352/689968021745303558/Giffy.gif

The volume of the hull in this GIF is slightly bigger than the Remora by a bit, but they still didn't try to get out of there fast enough.

**Version**
0.9.801

**Comment by itchyOwl** [comment]
I don't think it's related to operating turrets, but I found that the bots prioritized finding the diving suit when they should just get somewhere safe. Should be fixed in Regalis11/Barotrauma-development@bf5aabe.

**Comment by Kaillera** [comment]
It seems like the bots react to pressure in due time now. The problem is now bots keeps wanting to repair stuff when they should be staying on the gun shooting.

**Comment by Rokvach** [comment]
I didn't spot any issues with this. Closing.
