### ISSUE TITLE
Wet Hull despite 0 Water. Causes Potassium/Magnesium to explode.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2467]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have hulls that claims to have 0 water, but walking around I hear wet footsteps. Crossing through these hulls causes Potassium and Magnesium to explode.

![Capture](https://user-images.githubusercontent.com/5086682/77069859-90f70800-69bf-11ea-9b8c-fc8d88595a8e.PNG)

[The Aeche (III).zip](https://github.com/Regalis11/Barotrauma/files/4354612/The.Aeche.III.zip)

**Version**
0,9.801

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a84674a84c60b629129c151847aa11170423fb76

**Comment by Rokvach** [comment]
No issues, closing.
