### ISSUE TITLE
Ice getting stuck on Submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2468]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to progress through a level, and two sets of ice somehow wedged themselves inside my submarine shell, searchlight, cargo shell. They rubberband back into those spots even if I was able to drift away from them. Unable to finish the levels because the map isn't big enough for me to drive around with these pieces of ice extending my sub size.

First Round
![Capture2](https://user-images.githubusercontent.com/5086682/77069679-42e20480-69bf-11ea-8517-e5da41219b37.PNG)
Second Round
![Capture3](https://user-images.githubusercontent.com/5086682/77069682-44abc800-69bf-11ea-9aae-858f93fb8f23.PNG)

**Version**
0.9.801

**Comment by Regalis11** [comment]
I think we can close this: even if this still occurs, it can be worked around now that the ice chunks are destructible.
