### ISSUE TITLE
Searchlight toggle_state possibly not functioning as intended

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2471]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Searchlight wire input "toggle_state" is not functioning as expected for a toggle state light.  Does not appear to toggle light on/off in any way that resembles other lights.  Only can get it to turn off by holding down left click with periscope trigger out -- and it is only temporarily off.

**Steps To Reproduce**
Power searchlight, turn on, and test different signals to the toggle_state.  
--An oscillator with Pulse setting does not seem to toggle the on/off status of the light.  
--An oscillator with square setting likewise does not affect it.  
--A mem with output of 1 or 0 does not seem to affect it.  
--A button with or without toggle function does not affect it.  
--Only thing that I could find to affect it is a periscope trigger_out and only if the searchlight was toggled ON in the editor, and stays on, but only goes off when left click is held (trigger is outputting constant 1s).

**Version**
9.7.x
Windows 10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fdf5e6fa259e3ac00dbed63ddcfdf114cc578d4

**Comment by Rokvach** [comment]
No issues, closing.
