### ISSUE TITLE
[Bug] [Modding] Can't seem to set mass for normal item <body>

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2475]
Self explanatory. Can't seem to edit the mass property the way you can edit other properties in PhysicsBody.cs.
```<Body width="100" height="50" density="30" friction="0.8" restitution="0.01" mass="30000"/>```
and
```<Body width="100" height="50" density="30" friction="0.8" restitution="0.01" mass="3"/>```
will not show any difference in falling speed.

**Comment by Regalis11** [comment]
The mass of the object is determined based on its density and size, so you should edit the density-attribute instead.
