### ISSUE TITLE
[0.9.6.0-0.9.8.0] Still having some problems with relay components and their grid load

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#2479]
- [x] I have searched the issue tracker to check if the issue has already been reported.

The main problem is that, when you are using relay components in power systems, the grid load seems to split. Some parts of the sub might get too much power, while other parts might get not enough power.

Hopefully the video will give enough information on the issue. In case something is not clear enough in the video, feel free to ask any questions or request additional information. I will try my best to provide it.

The video:
https://www.youtube.com/watch?v=Cn3lhaLZD1A

The sub file:
[Relay grid load test.zip](https://github.com/Regalis11/Barotrauma/files/4364857/Relay.grid.load.test.zip)

**Version**
0.9.6.0-0.9.8.0 and probably earlier versions

**Comment by Regalis11** [comment]
This is intentional: the relays only account for the load of the items after the relay.

**Comment by BillCombs** [comment]
In that case, could you consider adding some kind of a power switch component?
Something that could be toggled, and would only transfer power if it was toggled on, but without any limitations of the relay component. Basically, a toggleable junction box/wire.
I tried using relay components and batteries to make toggleable power systems, but using either of them for toggling power is causing problems.
Unless i'm missing something, right now it seems that there is no easy way to make complex toggleable power systems.
