### ISSUE TITLE
Expand the Character Death Handler to status effects + Add additional handles for status effects.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#248]
At the moment, characters have a handler that is checked once a character has been killed, which is usually used for the husk code.

What I propose (Primarily for modding but this could be cool for the base game) is to add triggers for taking damage (And not by status effects) and other character-based events that could be triggered - and allowing status effects to go off once they occur. of course they should likely have a timer between how often they could trigger and other restrictions but this would be a cool feature.

Right off the bat it could add explosions / noxious gas effect clouds and other such to dying creatures, EMP blasts and the likes.

It could poison characters within range that attack a creature too.

**Comment by Regalis11** [comment]
Added in 73b2ce8
