### ISSUE TITLE
[Bug] [Modding] Wearables with inheretdepth mess with wearables with non-inhereted depths

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2480]
It would seem that there are some issues with sprite depth using wearables. Specifically I'm unable to get the head of a full body wearable to cooperate depthwise with the head wearables of other wearable items. Specifically the hood (head limb wearable) on my costume is prone to completely ignoring the sprite depth relative to other head wearables such as the hat slot. Worth looking into.

**Comment by hubismal** [comment]
![2020-03-23-234054_165x136_scrot](https://user-images.githubusercontent.com/47284081/77388994-c3a65500-6d5f-11ea-8e1d-625f16c7fa97.png)
here is a screenshot of the issue although it depends on the order you put them on in. Usually putting the costume on last results in it looking okay. Even setting the spritedepth of the hood sprite to 0 didn't affect it.

**Comment by Regalis11** [comment]
I think this has been fixed since this ticket was created, we do have functional hoods that are rendered on top of hats now.
