### ISSUE TITLE
[Issue] Bots still make conversation during multiplayer rounds

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2481]
Reporting this as an issue because it definitely, sure-firely, is one. As the lag gets better more players put many, many bots in their rounds so this has become an "issue" now the way I see it.

Bots *still* make conversation in multiplayer for some reason **almost a year later** (more than a year after closed beta), significantly impacting the usability of text chat not only because there are more messages but most voice chat players assume that text in the text chat is just another bot rambling by default. 
The fact that they do this only makes life worse for everyone, not only as an annoyance problem but a communication problem. Actual player conversations/cries for help should obviously be prioritized over bot scripted conversations.

**Comment by Regalis11** [comment]
Made the bots less chatty by default in https://github.com/Regalis11/Barotrauma-development/commit/7c415cabdfc606c50125f71e220c01dc216cdf58 and added an option to disable the conversations in https://github.com/Regalis11/Barotrauma-development/commit/2b7a78d3e980eb48130497830a0ca75e074e06e7

**Comment by Rokvach** [comment]
A lot less unnecessary chatter, no issues. Closing.
