### ISSUE TITLE
Shuttle appeared in glitched location in next campaign mission after being abandoned

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2483]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We lost our shuttle and ended the mission; decided to go back and see if we could recover it and found it here. https://streamable.com/dujlc

We then decided to leave it and go to next mission and the shuttle appeared there too, but in the abyss.

**Steps To Reproduce**
Play campaign and abandon a shuttle, then in next mission go back for it.

**Version**
Windows 0.9.7.1

**Comment by Rokvach** [comment]
This behavior isn't in the game anymore or rather there's been quite a bit of improvements on it

**Comment by thegrb93** [comment]
Yeah. Really old issue
