### ISSUE TITLE
[Bug] [Modding] <Remove>ing a wearable while equipped leaves the sprite there

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2485]
Self explanatory. If you remove a wearable while it's still equipped through xml (specifically i did it by doing a Remove in an OnBroken) the sprite stays on the body. 
reproduction:
This is easily seeable if you enable ingamemodswap in the console and disable a package while you're wearing something from that package, but you could also modify the cap or something to break OnWearing and see for yourself

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57d970334a7dcbb1f70ad823c490b1662b7d055f

**Comment by Rokvach** [comment]
No issues,closing.
