### ISSUE TITLE
[0.9.7-0.9.8] The antibiotic does not work when shot from a syringe

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2486]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When shot from a syringe, the antibiotic does not impose a Husk resistance buff, only related internal damage.

**Steps To Reproduce**
Pour a cup of coffee. To relax. Get your syringe loaded with antibiotics and go shoot your mates from the syringe. Enjoy the sight of torment from internal injuries while drinking coffee.

**Version**
0.9.7-0.9.8

**Additional information**
When used from the hands, everything works.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/53faec80a71a0b6793b50d9a62825cbd5e4bfa49

**Comment by EdusFF** [comment]
A husk resistance buff was correctly applied both from shooting and manually applying broad-spectrum antibiotics after the fix
