### ISSUE TITLE
Very hard to repair hull breaches in the Kastrull Armoury

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#2487]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The kastrull armoury is somehow very tedious to repair hull breaches from when using a welding tool. 

**Steps To Reproduce**
I have highlighted the problem area.  If creatures damage this part and cause a breach, it will make the armoury very hard to repair. 

**Version**
v0.9.7.1

**Additional information**

![602960_20200325092538_1](https://user-images.githubusercontent.com/62313026/77529013-cd76a800-6e86-11ea-9af9-5a80c71a4b53.png)

**Comment by ezjamsen** [comment]
Fixed in dev

**Comment by Rokvach** [comment]
No issues, closing.
