### ISSUE TITLE
Charging Dock won't use custom Power Consumption values

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2488]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Charging Dock has a field for entering custom power consumption values like most other assets, but when plugged into power grid, still seems to draw the default level of power  ~200kW instead of using the custom setting.

**Steps To Reproduce**
Place charging dock, connect to power grid, set at a custom value that you can differentiate from default settings and observe the load on the grid.

**Version**
9.7.x
Windows 10

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a2347e6754cf616140980b55d4c5346be624a1ae

**Comment by Rokvach** [comment]
No issues, closing.
