### ISSUE TITLE
Allow editing sprite depth in the sub editor.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#249]
This is a bit of an  odd feature request, but I have noted the code controlling the depth of structures and such appears to be tied down to ItemID

For example in clients structure:
float depth = prefab.sprite.Depth;
depth -= (ID % 255) * 0.000001f;

I imagine there are quite a few sub makers whom have wished they could tuck one item behind another (Such as the base of a door and a floor), the ability for the sub editor to "Swap" ID's could make this a reality potentially, if handled correctly, or at least a saved depth offset (?) if changing the item ID could cause too many problems.

I imagine such a feature shouldn't be down to placing various doors and objects before you start building the walls of a submarine, so this feels like even if hard to do a good feature request to improve the game (And the ease of the sub editor).

**Comment by Regalis11** [comment]
Implemented in fc02b57
