### ISSUE TITLE
[0.9.8.0] Driving through Water Currents causes FPS drop

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2490]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Driving through Water Currents causes FPS drop. About 10 Frames.

**Version**
0.9.8.0

**Comment by Regalis11** [comment]
I wasn't able to measure any sort of performance impact when driving through currents (tested with Dugong and Aeche III), so I suspect this was caused by something else when you happened to be inside a current.
