### ISSUE TITLE
Bots - ID Cards of "spawn"ed Bots does not contain their names

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2491]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots spawned via "spawn" command spawns with ID Cards that doesn't contain their names. This makes them show up as "?" when they wear masks and suits.

**Version**
~0.9.8.0

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
