### ISSUE TITLE
[0.9.8.0] Bots - Does not fight back intruders when attacked despite carrying weapons

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2493]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots does not fight back intruders when attacked despite carrying weapons on their inventory for self defense. They will flee from them even if they were continuously bitten until death.

**Version**
0.9.8.0

**Comment by itchyOwl** [comment]
Can't reproduce. Which weapons did the bots have? Did they have any orders?

**Comment by Kaillera** [comment]
Any orders other than fight hostiles. I usually have them a stun baton and any military weapons. This was during 0.9.8 though.

**Comment by itchyOwl** [comment]
Ah, probably doesn't apply on the current version. There was a bad issue that was slipped in the release build of 0.9.8.0. Please inform us if this happens in the unstable/next release.

**Comment by Rokvach** [comment]
I haven't noticed any issues of bots not fighting back in my tests, closing.
