### ISSUE TITLE
[0.9.8.0] Bots - Bots under Fight Intruder Order flees when Intruder breaches into Sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2494]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will not fight intruders that breaches into the sub when already under order. They will only do it when the order is given/given again when the intruders is in the sub.

https://www.youtube.com/watch?v=wjqG-mwSPPc

**Version**
0.9.8.0

**Comment by itchyOwl** [comment]
Can reproduce the issue in the released version and cannot reproduce it in Regalis11/Barotrauma-development@7ee8dbc, which is the commit that was accidentally dropped from 0.9.8.0. So this should be fixed.

**Comment by Rokvach** [comment]
I haven't noticed any issues of bots not fighting back in my tests, closing.
