### ISSUE TITLE
Bots - Yeeting themselves out the window to Fix Leaks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2495]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For whatever reason, Bots Yeet themselves out the window trying to repair this leak at the window.

https://youtu.be/t4Ug5UFzbvo

**Version**
~0.9.8.0

**Comment by itchyOwl** [comment]
Bot now know how to get back inside the sub through the gaps, which should fix this. They shouldn't go outside intentionally.

Implemented in Regalis11/Barotrauma-development@7112915.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
