### ISSUE TITLE
[Unstable] Crashlog during mission

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2497]
**Description**
A simple game crash.
**Steps To Reproduce**
No clue what caused it. I was in freecam.
**Version**
Unstable
**Additional information**
Two crashlogs were generated at the same time, sending both.
[crashreport (103).log](https://github.com/Regalis11/Barotrauma/files/4395705/crashreport.103.log)
[crashreport (104).log](https://github.com/Regalis11/Barotrauma/files/4395706/crashreport.104.log)

**Comment by Regalis11** [comment]
We've got 2 separate newer tickets about this: #2511 and #2512, closing this one
