### ISSUE TITLE
Radio Keybind Does Not Work

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#2498]
- [✓ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Keybind for Radio does not work. I have tried rebinding Radio but it still does not work.

**Steps To Reproduce**
Start a round and try to use the Radio through the Radio Keybind

**Version**
0.9.9.0 on Windows

**Comment by 3e849f2e5c** [comment]
Duplicate of #2447
