### ISSUE TITLE
Some additions for the reactor.

### ISSUE THREAD

**Issue by SanecMan** [Regalis11/Barotrauma#250]
**Wrong translator translated, but I did not write that!**

I had several ideas for the reactor:
1. The temperature display will show the temperature not on the reactor itself, but on the display (useful for the Captain).
Enabled (2900 degrees):<a href="https://imgur.com/VgUY3tx"><img src="https://i.imgur.com/VgUY3tx.png" title="2900 degrees" /></a>
Disabled: (nothing):<a href="https://imgur.com/JRsXWVQ"><img src="https://i.imgur.com/JRsXWVQ.png" title="Off display" /></a>
The texture of the temperature display:<a href="https://imgur.com/7yR7Us6"><img src="https://i.imgur.com/7yR7Us6.png" title="Display" /></a>
The texture of the dial:<a href="https://imgur.com/XX9hCtl"><img src="https://i.imgur.com/XX9hCtl.png" title="Dial" /></a>

2. During the explosion of the reactor, radiation will appear next to it. Full pod will emit radiation. Radiation will cause damage. Against radiation can save:
Diving suits and gas masks.
The texture of the gas mask on the head:<a href="https://imgur.com/iyM0AeO"><img src="https://i.imgur.com/iyM0AeO.png" title="Gas mask on the head" /></a>
The texture of the gas mask:<a href="https://imgur.com/uIcCGQr"><img src="https://i.imgur.com/uIcCGQr.png" title="Gas mask" /></a>
Forum: https://undertowgames.com/forum/viewtopic.php?f=19&t=7943&p=118655#p118655

**Comment by Regalis11** [comment]
The display is now implemented, but atm radiation is not a planned feature.
