### ISSUE TITLE
[0.9.9.0] Multiplayer - Excessive Desync Kick at Round Start / Mid Round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2500]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've been experiencing a lot of round start desync in multiplayer when other players with better CPU joins. Also I've been seeing lots of players getting ExcessiveDesyncOldEvent & ExcessiveDesyncRemovedEvent randomly mid round.

**Version**
0.9.9.0

**Comment by Kaillera** [comment]
Still happening in 0.9.901.

I have a 2.6GHz CPU and no SSD, so I'm falling behind fairly often.

**Comment by Regalis11** [comment]
Should be fixed or at least made much less common in https://github.com/Regalis11/Barotrauma-development/commit/2090d8c3

**Comment by Rokvach** [comment]
Haven't noticed this happening in latest Unstable(904?) yet, seems to be working correctly. Closing.
