### ISSUE TITLE
[0.9.9.0] Multiplayer(?) - Defeated aliens in sub does not despawn after a long while

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2504]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Defeated aliens does not despawn in sub, even after a long while.

**Version**
0.9.9.0

**Comment by Kaillera** [comment]
Also to humans. At least the duffel bag is left behind at the end of round.

**Comment by Regalis11** [comment]
Could not reproduce. We did some changes to make the despawning a little less aggressive: there can be 5 corpses in a sub before they start to despawn, and the default despawn delay is 10 minutes. I wonder if it could be that the bodies just didn't have enough time to despawn, or that despawns were disabled on the server?

**Comment by Kaillera** [comment]
we can disable despawning?

**Comment by Rokvach** [comment]
I don't see any issues here, closing.
