### ISSUE TITLE
[0.9.9.0] Alien Pistol does not work on Carrier's innards and cells

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2505]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alien Pistol does not work on Carrier's innards. Cells takes almost no damage from it.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
This is by design. The alien pistol only causes psychosis, stun and a very small amount of burn damage, which makes it ineffective against most monsters.
