### ISSUE TITLE
[0.9.9.0] All creatures are rendered on the map

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2506]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All creatures (including humans) on the map are rendered no matter where they are from the sub, Not sure if it's an intentional change from <0.9.8.0 and earlier.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
This is intentional: the creatures are enabled if there's a spectator looking at them.
