### ISSUE TITLE
Game Freeze - Reason: SteamAuthenticationFailed Steam authentication status changed: AuthTicketCanceled

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2508]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a player's game freezes, the server kicks them for Reason: SteamAuthenticationFailed Steam authentication status changed: AuthTicketCanceled.

**Version**
~0.9.9.0
(Had it happened to Jerry on 0.9.9.0)

**Comment by Regalis11** [comment]
I don't think this is a bug. If the game freezes or crashes, Steam _should_ cancel the client's authentication ticket.
