### ISSUE TITLE
[0.9.9.0] Battery & Charging Dock aren't recharging battery cells

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2509]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Battery & Charging Dock aren't recharging batteries

**Version**
0.9.9.0

**Comment by mrjpjr** [comment]
Confirmed.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/49d173fa28bd230c754da3b1e2f2e1f8aeea2540

**Comment by Rokvach** [comment]
No issues, closing.
