### ISSUE TITLE
[0.9.9.0] Cells are spawning randomly inside Carrier Wrecks even though Cell Spawn Organ are destroyed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2510]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cells are spawning randomly inside Carrier Wrecks even though Cell Spawn Organ are destroyed. Sometimes they spawn on top of me as well while I'm salvaging the wreck, giving them an instant paralysis hit on me.

**Version**
0.9.9.0

**Comment by mrjpjr** [comment]
I can confirm this as well for Multiplayer Missions

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea7d6ca20af8ad046ad56ab3bbd56f0571d86940

**Comment by Rokvach** [comment]
No issues, closing.
