### ISSUE TITLE
[0.9.9.0] Crash - Void ThrowArgumentOutOfRange_IndexException()

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2512]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4396262/crashreport.3.log)

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e170e9ba9b3f3866b8fa506a868fda4b4dee58a6

**Comment by Rokvach** [comment]
No reported cases of the same crash happening since it was fixed on Unstable builds. Closing.
