### ISSUE TITLE
[0.9.9.0] Vanilla Subs - Lack of Dock Toggle to bottom Ports

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2513]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So with the implementation of Wrecks/Carriers, the bottom docking ports for vanilla subs are lacking docking functions at the start to dock with them.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
I'm assuming this is intentional, I guess the bottom docking ports in vanilla subs are only intended for docking a respawn shuttle into the sub, not for docking the sub to another one?

**Comment by ezjamsen** [comment]
This is intentional. Carriers cannot be docked with anyhow, using our conventional docking port setup since they're flooded and would end up flooding the docked sub.

**Comment by Kaillera** [comment]
> This is intentional. Carriers cannot be docked with anyhow, using our conventional docking port setup since they're flooded and would end up flooding the docked sub.

I was able to dock with them with any docking port that has a toggle at the bottom.
