### ISSUE TITLE
[0.9.9.0] Crash - Leaving the submarine with characters in Sub Editor's Test Level causes crash

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2514]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Leaving the submarine with characters in Sub Editor's Test Level causes crash
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4396304/crashreport.2.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4396306/crashreport.log)

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05b593b51206c42a9f3f235efda71b1d976baa61

**Comment by Rokvach** [comment]
Wasn't able to reproduce, seems to be working. Closing.
