### ISSUE TITLE
[0.9.7.1] Hull fails to flood in a specific configuration involving a docking port.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#2515]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hull fails to flood when a door is opened, if a docking port is in a certain configuration in relation to the hull and door in question. Deleting the docking port and hull to the right of the selected hull in the picture, seems to fix it.

**Steps To Reproduce**
I'm including two submarines for comparison. Bomber_HDK should work fine, the original one should fail to flood when the door is opened. The hull in question is the one by the diving suits. I'll post a picture of it as well.

**Version**
Windows 10 build 1903. Barotrauma 0.9.7.1

**Additional information**
None besides the zip and picture.

![image](https://user-images.githubusercontent.com/16188887/77809517-f8ffbb00-705d-11ea-869d-434d03852bab.png)

[The Bomber Bulk.zip](https://github.com/Regalis11/Barotrauma/files/4396375/The.Bomber.Bulk.zip)

**Comment by HalfdeadKiller** [comment]
The issue persists in 0.9.9.0 Unstable. Revision 4a9fd6d77.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ba8e1d69af5948a451c9e54e30806dcb1ec3a23

**Comment by Rokvach** [comment]
No issues, closing.
