### ISSUE TITLE
[0.9.9.0] Sub Editor - Submarines in Mods/ keeps on unlinking Additional Submarines from main submarines when updated

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2516]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I was constantly editting my sub and publishing the changes. When I open the sub file again, my Additional Submarines starts off unlinked to any docking ports after it gets refreshed automatically by steam workshop.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97c23b9ec6fba6d049107c328767e98a7613bca1

**Comment by Rokvach** [comment]
No issues, closing.
