### ISSUE TITLE
[0.9.9.0] Bots - Heal Injury order using medical supplies on characters with literally no injuries

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2517]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Heal Injury order using medical supplies on characters with literally no injuries. I had a Medic walking around injecting me and other crews with blood, saline, morphine, etc.

**Version**
0.9.9.0

**Additional Informations**
Bots are also randomly calling for Medic at full HPl

**Comment by itchyOwl** [comment]
I don't find this easy to reproduce. Is there any specific condition where this could happen? Or is it continous or random?

**Comment by Kaillera** [comment]
It was pretty random but this was during the first build of unstable. I haven't seen them waste med on no injuries since.

**Comment by Rokvach** [comment]
I haven't seen this happening during my tests, as Kaillera mentioned he noticed this happening during the first Unstable build of 0.9.9.0 (there were quite a few builds) so most likely something we have already fixed. Closing.
