### ISSUE TITLE
[0.9.9.0] Campaign - Wreck Salvage mission pays too little for Thalamus Carrier Wrecks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2518]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think the payout from salvaging Thalamus Carrier Wrecks are too low for it's difficulty. Somewhere between 2500~4000 seems good.

**Version**
0.9.9.0

**Comment by ezjamsen** [comment]
pushed up to 2800

**Comment by Rokvach** [comment]
No issues, closing.
