### ISSUE TITLE
Latest github has a few wiring issues in multiplayer

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#252]
There seems to be a few syncing issues with rewiring:

- If a client changes the pin from POWER to SIGNAL (Or other such, just as an example) causes the wire to be dropped.

- If a host changes the pin it changes correctly for the client and host (No issue here) but if a host changes it from Power -> Signal and then from Signal -> Power it will drop for the client (?) but still remain connected and powered for the host.

- You cannot grab/disconnect a wire another is currently holding on one side to rewire (I suppose this is a non-issue or could be considered normal behaviour)

- One time I clicked a light and somehow the wire had disconnected on the other side of the connection of its own accord as the host (I simply clicked the light, but the wire removed itself on the junction side and dropped in world). - Perhaps reproduced from host changing pin twice.

- I was rewiring the pins between POWER and TOGGLE with a light and realized the client and host had desynced the toggle state of the lamp. I noticed whenever it desynced this again (I decided to wire the lamps toggle to a door) the door would immediately close/open itself again (To the correct state server-side) - but the light would continue its toggle change.

**Comment by Regalis11** [comment]
The light syncing is still not fixed, but we have a new issue about that (#434) so I'm closing this one.
