### ISSUE TITLE
Difficulty swimming into "Shuttle Shell A Glass A" from the outside

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2520]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Originally I thought the hulls inside being less than 7x7 was the real problem, but it turns out it's just plainly hard to swim into the sub through "Shuttle Shell A Glass A" from the outside.
![Capture](https://user-images.githubusercontent.com/5086682/77812547-530d7a00-7078-11ea-816c-6fbe1725fed7.PNG)

**Version**
~0.9.9.0

**Comment by itchyOwl** [comment]
Related?: https://github.com/Regalis11/Barotrauma-development/issues/2031

**Comment by Regalis11** [comment]
We have a newer ticket about the general issues with these sloped walls https://github.com/Regalis11/Barotrauma/issues/7154, closing this one
