### ISSUE TITLE
Character Editor crashing on 0.9.9.0

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2521]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Try to go to character editor instantly cause a crash report

**Steps To Reproduce**
Click on character editor on menu

**Version**
Unstable 0.9.9.0 on Windows

[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/4396980/crashreport.15.log)
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/4396981/crashreport.14.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6bb35f5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
