### ISSUE TITLE
New save shortcut cause crash report

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2522]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After using the shortcut "Ctrl+Shift+S" it caused a crash report.

**Steps To Reproduce**
Used the shortcut 4 times, but it can be random.
**Version**
0.9.8.0 Unstable on Windows.

[crashreport (16).log](https://github.com/Regalis11/Barotrauma/files/4396982/crashreport.16.log)

**Comment by 3e849f2e5c** [comment]
Should be fixed in [cb24106](https://github.com/Regalis11/Barotrauma-development/commit/cb24106cfcc91db7038a06a74426250351877b49)

**Comment by Rokvach** [comment]
I wasn't able to reproduce, working correctly. Closing.
