### ISSUE TITLE
Bots - Gunners are able to see through alien walls, wreck shells, map walls. Constantly firing at hostiles it shouldn't be able to see

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2523]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bot gunners are able to see through alien walls, wreck shells, map walls, which makes them constantly firing at hostiles it shouldn't be able to see and wasting ammunitions.

**Version**
~0.9.9.0

**Comment by itchyOwl** [comment]
I didn't notice bots shooting through level walls, but they did target through wrecks and alien ruins. Fixed in Regalis11/Barotrauma-development@b526245.

**Comment by Rokvach** [comment]
I didn't notice any issues, closing.
