### ISSUE TITLE
[0.9.9.0] Hemulen Wreck contains no loot

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2524]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Raided several Hemulen Wrecks. Didn't contained loots.

**Version**
0.9.9.0

**Comment by Kaillera** [comment]
[0.9.901] The Storage Cabinet has loots now, but Supply Cabinets have no loots.

**Comment by Kaillera** [comment]
Also there's no Logbook to complete the mission with.

**Comment by Regalis11** [comment]
Tested, the supply cabinets seem to be filling up correctly now.
