### ISSUE TITLE
[0.9.9.0] Carrier - Failed to write an event for the entity "Fleshgun Tendon (ID: ####)"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2526]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![](https://media.discordapp.net/attachments/668819422919524352/693544771029041202/Capture.PNG)

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4039471cb60657f5e8f54c2ca70228757adf99ab

**Comment by Rokvach** [comment]
No issues, closing.
