### ISSUE TITLE
[0.9.9.0] Carrier - Failed to read a projectile update from the server....

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2527]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Failed to read a projectile update from the server.
-Limb Index out of bounds (255, character; Leucocyte)
-Invalid stick target (null, 555)

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ba8e1d69af5948a451c9e54e30806dcb1ec3a23

**Comment by Rokvach** [comment]
Wasn't able to reproduce this issue, closing.
