### ISSUE TITLE
[0.9.9.0] Multiplayer Crash & Missing Entity Lock Up near the end of round.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2528]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hexcode Guy and me finished salvaging a carrier (Not a mission) and was heading to the next station. 3/4 of the way there we ran into a few crawlers and molochs, both we killed. When nearly 300m of the station, Hexcode Guy crashed and got:
[crashreport_object.zip](https://github.com/Regalis11/Barotrauma/files/4397824/crashreport_object.zip)

At the same time I also got kicked out of the round for Missing Entity. Niether of us was able to get back into the round due to persistant missing entities, and thus the crew wiped out.
[ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/4397825/ServerLogs.zip)

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Could be related to https://github.com/Regalis11/Barotrauma-development/commit/9f007da, moving to Review/QA

**Comment by Rokvach** [comment]
No reported cases of this happening during latest Unstable testing. Closing for now.
