### ISSUE TITLE
[0.9.9.0] Calyxanide, Antibiotics, Blood Pack, Saline does not work

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2529]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Calyxanide, Antibiotics does not reduce husk infection. Blood Pack, Saline does not recover blood loss. I think more may be broken as well.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a6f6eee38a6608ec8f769c0960b340bee27f7d32

**Comment by Rokvach** [comment]
No issues, closing.
