### ISSUE TITLE
Expand Damage Modifiers coverage to explosions, repair tools and structures + Specified wearable limbs.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#253]
I had a few thoughts about the current damage modifiers and the current damage system in general and figured it could have a few changes made for modding and more specific coverage.

- Add the new damage types "Explosive" and "All" (Covers every type including "None", unlike "Any" which excludes "None",
- Possibly add structure-specific damage types (Pressure/Depth and Impact/collision)
- Allow explosives and repair tools to have a specified damage type to characters and structures,
- Allow Structure Prefabs to specify damage modifiers.
- Give explosives a new damage type (default "Explosive")
- Give repair tools the default damage type "Burn" or "None" if Character or Structure

- Possibly reintroduce damage modifiers to wearable limb-specific (I believe as of now they are currently global to the worn item, without an ability to choose between global, limb-specific or both?)

**Comment by Regalis11** [comment]
The health system is being overhauled atm (7b7dcc3) and after the changes are done I don't think most of these will be necessary. The concept of damage types will be removed altogether; instead characters can receive arbitrary "afflictions" which could be anything from bursted eardrums or plasma cutter burn marks.

**Comment by NilanthAnimosus** [comment]
I did not even know these brilliant changes were in the works - I was hoping for more customization and flexibility for modders by expanding the current system but that seems pretty sweet.
