### ISSUE TITLE
Game froze when starting up a reactor (Dump attached)

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2531]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Started the reactor, I dont know if it was coincidence or not but the game froze. Dump is here http://sparkysandbox.org/Barotrauma.7z

Also video.
https://streamable.com/wiwvy

**Version**
0.9.7.1

**Comment by juanjp600** [comment]
This is now my favorite bug report

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2fd6d27057f2c5dd5c6625fbaa044462ff30a07f

**Comment by Rokvach** [comment]
Freezing hasn't been sighted on the Unstable builds. Closing.
