### ISSUE TITLE
[0.9.9.0] Hard to differentiate between Cell Spawn Organ live and death state

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2532]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hard to differentiate between Cell Spawn Organ live and death state.

**Version**
0.9.9.0

**Comment by itchyOwl** [comment]
Doesn't necessarily require new art. The plan was to use colors for this. But it's not yet implemented.

**Comment by Rokvach** [comment]
No issues, closing.
