### ISSUE TITLE
[Bug] [Issue] Certain Wearables don't work with SpeedMultiplier statuseffects

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2534]
A good example of this is the diving mask with oxygenite tanks not properly modifying the speed. Seems to happen to almost everything wearable that's not a diving suit. Also the diving suit notably walks and normal speed and only limits your running.

**Comment by itchyOwl** [comment]
So the issue was in the release, not in the unstable, right? It should be fixed in the unstable. Although I noticed that the speed multipliers for the diving suit and the mask were cumulative instead of being set only once.

**Comment by hubismal** [comment]
This is confirmed working and no longer an issue as of the release build.
