### ISSUE TITLE
New quick save shortcut doesn't create new thumbnail

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2536]
**Description**
It is either a bug or something that isn't implemented, when you use the Ctrl+Shift+S, it only saves the sub, but doesn't create a new thumbnail.

**Comment by Regalis11** [comment]
I think it's a good thing quicksaving doesn't update the preview image. If you for example have a submarine with a custom preview image, or don't want the sub to have the image (if it's for example a shuttle or a wreck that's hidden from the menus), having to manually replace the image after quicksaving would be really tedious.
