### ISSUE TITLE
Extra options for combat

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2538]
- It is a feature request.

**Description**
Extra options such as "No creatures", "Same sub", etc. And random objectives like overload the enemy reactor, kill everyone and traitors completing mission will cause victory to the opposite team, and traitors could have connection for both teams.

Also extra options on sub editor such as Coaliation spawnpoint or Renegade spawnpoint.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1758](https://github.com/Regalis11/Barotrauma-development/issues/1758) via [**ZenHub**](https://www.zenhub.com/)
