### ISSUE TITLE
Add to the server lobby screen additional server information

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#254]
It's something I think would be nice to have, I feel like it would have been suggested/stated before but I couldn't find a related issue.

We have the submarine information now, and I figure it would be nice if the server list had its information expanded or even a preview window for that server.

Some ideas for what information to display:
- Version (If you add this, don't make clients unable to join - it would be really nice to show a server is running a particular code modification and instead to let the server itself decide perhaps if this is a string, if not then it would be nice to have another field for code modifications themselves that unmodified can see/recognize too without issues)
- Is Using Whitelist (Perhaps make this a filter like password is)
- content package
- Is in lobby
- Gamemode in use
- Traitor setting
- Approximate round length
- Voting enabled on gamemodes or submarines
- respawns enabled and respawn ratios
- Allows spectating
- Allows submarine downloads

It should be possible to handle these by having an additional state for updating the masterserver, where on round starts it sends the related information (And the masterserver could get the round length for instance from that without having to include it every update and other details that only need to be sent once per round).

**Comment by Regalis11** [comment]
Added in a159d75, 78f8add & cdb389d
