### ISSUE TITLE
Campaign - No missions at Natural Formations and Breeding Grounds

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2540]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I feel like the lack of missions when at Natural Formations and Breeding Grounds creates a lack of interests in going closer to the center. At the moment, going to the center itself is a self given achievement. Roaming around Natural Formations and Breeding Grounds doesn't provide reasons to linger around other than to get to the end of the map as soon as possible. Players need incentives. At least getting paid to do missions at the center makes the movement feels worth while, even if we can't buy anything. This is what makes Mission Mode on Hellish more fun than Campaign Center because they actually had something to do.

When Udrakan made the early versions of Into The Abyss mod, while he did removed a majority of the outposts, he had missions for Natural Formations and Breeding Grounds (Although almost entirely removed now), I felt good about making a couple thousands here and there, and that led me closer to the center in itself.

**Version**
~0.9.9.0

**Comment by thegrb93** [comment]
Isn't there a higher rate of alien ruins/mining sites? I'd say that's incentive enough.

**Comment by Kaillera** [comment]
> Isn't there a higher rate of alien ruins/mining sites? I'd say that's good incentive.

It's actually just the same maps with no missions.

**Comment by Ant1V1RU5** [comment]
Do we know if the devs have any plans about breeding grounds ? To me they sound like a very dangerous place to be with a lot of carnivorous wildlife, but it's not the case. Maybe a special mission about them could make some incentive to go there ?

I'm thinking about an "Exterminate all" where the players should destroy some "eggs" or queen monster or something like that. Or completly annihilate all threats on the level (Search and Destroy)

**Comment by Regalis11** [comment]
The campaign map, particularly the center, will be reworked in the campaign update.
