### ISSUE TITLE
[0.9.9.0] Carrier - Firing Explosives Railgun / Depth Charge displaces Carrier Organs

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2545]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When firing Railgun or depth charge at carriers, stuff like brains and flesh sacks will fall out of the carrier, with no damage dealt to them. This make them still operable and potentially undefeatable when the organs falls out into the abyss.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4bbf084aab74191e418ef05fcb1027de898b714b

**Comment by Rokvach** [comment]
No issues, closing.
