### ISSUE TITLE
[0.9.901] Bots - Heal Injury Order does not treat Paralysis

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2548]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots when told to Heal Injuries, does not treat Paralysis.

**Version**
0.9.901

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/020bbeec5663d32ea45e6dcc2fe7013c5462d979

**Comment by Rokvach** [comment]
No issues, closing.
