### ISSUE TITLE
[0.9.901] Multiplayer - Paralysis % number doesn't show past 100%

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2549]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In Singleplayer with a health hud scanner, you can read the number for paralysis go over 100%.
In Multiplayer with a health hud scanner, you can read the number for paraylsis get stuck at 99%~100% once it goes past.

This made some players believed there was no way to cure paralysis past 100%.

**Version**
0.9.901

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/82538acfd71f5b347ac1c362377a998aa778e61a

**Comment by Rokvach** [comment]
No issues, closing.
