### ISSUE TITLE
[0.9.901] Missing Logbook for Missions

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2550]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hemulus Wreck and Wreck1 doesn't contain a logbook for the mission anywhere. That or I'm blind. I've checked every cabinets and corpses I believed.

**Version**
0.9.901

**Comment by hubismal** [comment]
The logbook seems to be placeheld right now, you should actually be looking for a clown mask in a locker according to the code.
```xml
spawntype="wreck"
    showmessagewhenpickedup="true"
    existingitemtag="salvagetarget"
    itemidentifier="clownmask"
    containertag="locker">
```

**Comment by danielasteljoki** [comment]
Logbooks used as mission targets now are soon going to be for flavor only. We're going to spawn different logbooks in for the missions. And yeah, clown masks are the fallback item for now.

**Comment by Rokvach** [comment]
No issues, closing.
