### ISSUE TITLE
[Design] [Bug] Azimuth missing Gap

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2551]
![2020-03-31-210836_138x311_scrot](https://user-images.githubusercontent.com/47284081/78091931-e2c26980-7393-11ea-87ae-a88a16e71d4f.png)
water gets trapped.

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/78093393-669b4680-73d2-11ea-8eff-0091da32cca4.png)

**Comment by danielasteljoki** [comment]
Fixed in ec08ff9

**Comment by Rokvach** [comment]
No issues, closing.
