### ISSUE TITLE
[Issue] [Wrecks] Fractal Guardians spawn at enemy points in wrecks

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2553]
This probably isn't intentional. I'm assuming the game just recycles the ruin spawntable for wrecks. It looks like since fractalguardians aren't technically counted as able to enter the sub, they'll glitch out through the sub's (the wreck's) physicsbody and end up outside of the wreck in somewhat unusual fashions, where they are free to chase the sub around which is the cause of the strange fractal guardians chasing the sub in our recent games.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f781d8f50615716450fcfbb65bc0c9e41baaba8

**Comment by Rokvach** [comment]
I haven't noticed any fractals being in places they shouldn't, closing for now.
