### ISSUE TITLE
[Design] [Wrecks] Wrecks ID Card reusable throughout multiple wrecks

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2554]
The idea of taking an ID card off of crewmembers in order to access their ship is very cool, but the way the wrecked_idcard system works right now just looting one crewmember is a ticket to unlimited wreck  access. To put this in terms of how boring and overpowered it is, this is the "omnicard" of shipwrecks and sort of oversimplifies wrecks in campaign. 

I'm reporting this because I assume this isn't intentional? The ID card implies that it's not since it says that the ID card only works on "the" wreck.

IMO the game should just use the normal tag-id-assignment system instead of a unique wreck_id item (or just have the wreck id behave identically to idcards, whichever one) and use normal spawnpoint-assigned tags like *id_wreck_berillia3* or something to give them each unique tags that will only work with the specific shipwreck type. i'm just spitballing though.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3ba68b86d472a911a4ab00c2d9d12b6e93e3c13

**Comment by Rokvach** [comment]
No issues, closing.
