### ISSUE TITLE
Radio key stops working for many players

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2555]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Something is causing the radio keybind to stop working. Manually typing 'r;' works, but pressing r doesn't. We noticed many players in the campaign have this bug trigger.

Rejoining doesn't help. Didn't try restarting the game.

**Steps To Reproduce**
Not sure

**Version**
0.9.8.0

**Comment by Regalis11** [comment]
https://trello.com/c/a04ZCHiq/292-radio-keybind-doesnt-work-workaround-included

Fixed in the private repo, fix coming up in the next release

**Comment by Rokvach** [comment]
This issue has already been resolved, just needs a hotfix. Closing.

**Comment by Regalis11** [comment]
I think it might be a good idea to keep this open for now, so people will see it's already been reported

**Comment by Rokvach** [comment]
I don't see a reason to keep this up anymore, closing.
