### ISSUE TITLE
Cargo Spawnpoint spawns items halfway through submarine shell

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2556]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you purchase items or cargo missions, submarines that uses submarine shell for the room's floor (Azimuth and Remora are affected by this), the crates may spawn into the shell instead of ontop of it. This prevents players from picking them up.

**Version**
~0.9.901

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b720771

**Comment by Rokvach** [comment]
No issues, closing.
