### ISSUE TITLE
[0.9.901] Repair Electrical/Mechanical order button doesn't have the confirmation sound when pressed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2557]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Repair Electrical/Mechanical order button doesn't have the confirmation sound when pressed

**Version**
0.9.901

**Comment by ekqvist** [comment]
The missing sound is related to the chat messages. There is no order dialog texts for the new skill-specific repair orders in the current Unstable build so there are no chat messages displayed. I added new dialog texts in Regalis11/Barotrauma-development@98319bb.

**Comment by Rokvach** [comment]
No issues, closing.
