### ISSUE TITLE
Barotrauma Crash System.NullReferenceException

### ISSUE THREAD

**Issue by bajetelu** [Regalis11/Barotrauma#2559]
- [x] I have searched the issue tracker to check if the issue has already been reported.
[crashreport (18).log](https://github.com/Regalis11/Barotrauma/files/4417971/crashreport.18.log)
v0.9.8.0

**Comment by oBlissing** [comment]
Just got the same issue (I think).
I wonder if it's sound output settings that causes this.
The game worked fined until I alt tabbed and changed what sound channel barotrauma should use. After that I can join a game fine but it keeps crashing seconds in.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4418097/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/339c322

**Comment by Rokvach** [comment]
No issues, closing.
