### ISSUE TITLE
Recolour syringes sprite colour to sprite colour of contained medical

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#256]
Perhaps (For mods or items that you do not wish to have recoloured) this could be a configurable setting in the XMLs to recolour the item based on its contained items, but as an image to how nice this actually can look:

![image](http://puu.sh/zq5sr/181b5d70a8.png)

**Comment by CryIz** [comment]
I have long wanted to suggest this but was too lazy.
