### ISSUE TITLE
[Issue] The "ENTER" cannot be use to open chat (radio or local)

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2560]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description and Step to reproduce**
When binding the "ENTER" Key to the radio or local chat, the chat window open then close immediately, preventing any way or writing.

**Version**
If i trust my memory, this issue is still there from the legacy version of the game.

**Additional information**
The numpad "ENTER" Key seems to have the same issue aswell.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f976caa6370a9986e40f6660fabf7cffb007e4fd

Enter key should now work for both radio and normal chat keybind

**Comment by Rokvach** [comment]
No issues, closing.
