### ISSUE TITLE
[Bug] Handheld sonar's "onUse" causes battery to drain quickly upon pressing left-click

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2561]
### Issue:

When active, the handheld sonar's 'onUse' statusEffect seems to stack onto itself, draining the battery extremely quickly whenever mouse1 is pressed.

**Steps to reproduce:**

Equip a handheld sonar with battery
Enable active sonar
Hold mouse1 as if 'using' an item (like lighting flares for instance)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6282635

**Comment by Rokvach** [comment]
Couldn't reproduce, seems to be working. Closing.

**Comment by Ek-Videogames** [comment]
(Reminder need to reopen this, unless it has been again-fixed since we talked in discord)
