### ISSUE TITLE
[Issue][Campaign] Players can buy at store without admin / management rights

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2562]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a (non-modded) campaign, peoples can sometimes use the outpost stores and buy / select items without having campaign management or any rights.

**Steps To Reproduce**
This issue happen only in campaign and seems to occurs really frequently, and sometime at each outpost.

**Version**
Current and latest version [0.9.8.0]

**Additional information**
Their is also a small issue when buying more than 100 items of the same type (ex: 150 Fentanyl) the ship cargo only receive 100 items and nothing more.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8eee4b

**Comment by Rokvach** [comment]
I am still able to change the item quantity if I revoke my manage campaign permission, not sure if its because I was the one who originally selected the items before revoking. Tested on dev. @Regalis11

**Comment by Regalis11** [comment]
Should be fixed now: https://github.com/Regalis11/Barotrauma-development/commit/8406df6

**Comment by Rokvach** [comment]
No issues, closing.
