### ISSUE TITLE
[Issue..?] Tab Menu Mission Tab doesn't display location name

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2564]
Unsure if this is an issue but I *think* this is unintentional, the mission section in the tab-key menu ingame shows the location portrait for the destination but not the actual name of the outpost, which I assume is not intentional since it's kind of counterintuitive, unless you're a player who has all of the outpost names associated with the location portraits.
![2020-04-03-000741_360x409_scrot](https://user-images.githubusercontent.com/47284081/78326190-5fde1200-753f-11ea-8e54-55ba4407db7c.png)
EDIT: This is a bad example because the description contains the city name, but there are a bunch of missions descriptions that don't obviously.

**Comment by ekqvist** [comment]
Tested in the campaign and it's showing up correctly now
