### ISSUE TITLE
[Sub] [Design] Typhon's Mechanical Eng. Room Water Duct

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2565]
I know the typhon isn't hip or cool anymore ever since the newest hottest typhon2 came out but there's an error that i'm pretty sure has been around for a long time and i always noticed sorta but only just bothered to track it down.
![2020-04-03-001925_376x256_scrot](https://user-images.githubusercontent.com/47284081/78326842-f8c15d00-7540-11ea-946b-28449e9f6387.png)
it looks like the duct that is supposed to drain water from engineering doesn't work for some reason. the water detector opens the duct correctly but there's that wall in the way or something. the solution is probably just to move the gap to the right or something, or make space for it. either way it doesn't actually drain water correctly and you can test it for yourself.

**Comment by danielasteljoki** [comment]
The duct block's placement caused its gap to be generated the wrong way round. Moved it a bit to the right in 498465b.

**Comment by Regalis11** [comment]
Tested, no issues
