### ISSUE TITLE
Repair tools don't damage items

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2566]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Repair tools don't do any damage to damageable items (mudraptor eggs, thalamus organs)

**Version**
v0.9.9.0 or later, might also be present in older versions

**Comment by Regalis11** [comment]
Fixed in 64ee8bd

**Comment by ekqvist** [comment]
Tested to be working correctly now by spawning a mudraptor egg and destroying it with a welding tool
