### ISSUE TITLE
[Bug] [Dev Branch 0.9.902.0] Plasma cutters can't mine ores

### ISSUE THREAD

**Issue by LordFrith** [Regalis11/Barotrauma#2567]
- [x] I have searched the issue tracker to check if the issue has already been reported. Found previous ticket marked closed in January

**Description**
When trying to mine resources with the plasma cutter there is no progress bar and resource item never breaks down

**Steps To Reproduce**
start campaign, leave sub and try to mine with plasma cutter.

**Version**
Unstable V0.9.902.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e44e405c4e4002246ab77b33f41fad3012340288

**Comment by Rokvach** [comment]
No issues, closing.
