### ISSUE TITLE
[Issue][Sprite Color] The single Diving Suit Locker does not render color properly

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#2569]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The (single) Diving suit locker cannot be colored correctly via the sprite color editor RGB in the submarine editor when a suit is stored inside. But change to the correct color when the suit is removed.

**Steps To Reproduce**
Step 1 : Place a diving suit in a (single) Diving Suit Locker
Step 2 : Try to change the sprite color of said Locker (The color doesn't change)
Step 3 : Remove the diving suit inside (The color is applied)
Step 4 : Place any diving suit again in the now empty Locker and the color get defaulted again.

**Version**
The current 0.9.8.0 version on Windows 10 updated

**Additional information**
This issue doesn't happen with the bigger 5 Diving Suit locker.

![Issue Diving Suit Locker 01](https://user-images.githubusercontent.com/62913364/78418326-71a4df80-763b-11ea-8c8d-17cb48dbeff6.png)
![Issue Diving Suit Locker 02](https://user-images.githubusercontent.com/62913364/78418329-72d60c80-763b-11ea-8d0e-b0e6b082f8e4.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1143523e6f34fb1ec2c9887368db2506ade02ddd

**Comment by ekqvist** [comment]
Tested to be working correctly now

**Comment by Regalis11** [comment]
Seems to have reappeared in art unification

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/970d3aff59f676d8f579048e7750c0d62843f046

**Comment by Rokvach** [comment]
No issues, closing.
