### ISSUE TITLE
There are still a number of hard coded paths for modding.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#257]
Instead of stating what can't be modified, I'm going to note the line of code (as of commit "Change log update": fa52c66788cc7b4a8414e664200f747da01ea319 and the hard coded path it reads from.

I've tried to avoid listing any default path definitions when a file of a type is not found.

I went through and checked these because I've talked to several people trying to modify or actively making modifications for the game via the XML system.

They found themselves unable to change aspects - Some I heard are feasible to modify and others not such like the noise effect for unconscious characters, the ruins config file and the background texture for the level.

Some may make less sense to edit such as the water bump texture, but if a modder thinks they could make a better looking bump map and wishes to edit it I don't see it as a bad thing.

Consider this more of a reference to the current state of "Hard coded" values that could potentially be opened up.

### Configuration files

- [x] Shared - Game Server Settings (This one effects the server creature disable list on its settings and is a bug)
- 353: Content/Characters

- [x] Shared - Ruin Structure:
- 16: Content/Map/RuinConfig.xml

- [x] Client - Game Main:
- 316: Content/Particles/ParticlePrefabs.xml
- 317: Content/Particles/DecalPrefabs.xml

- [x] Shared - Location:
- 59: Content/Map/locationNames.txt

### Sounds

- [x] Client - Sound Player

As an additional note there is a maximum of 2 water ambiances, 3 flow sounds and 10 splash sounds.
- 95: Content/Sounds/sounds.xml
- 100: Content/Sounds/startDrone.ogg
- 105: Content/Sounds/Water/WaterAmbience1.ogg
- 107: Content/Sounds/Water/WaterAmbience2.ogg
- 109: Content/Sounds/Water/FlowSmall.ogg
- 111: Content/Sounds/Water/FlowMedium.ogg
- 113: Content/Sounds/Water/FlowLarge.ogg

- [x] Shared - Powered:
- 69: Content/Items/Electricity/powerOn.ogg
- 77: Content/Items/Electricity/zap" + (i + 1) + ".ogg"

- [x] Shared - Connection:
- 77: Content/Items/connectionpanel.png

- [x] Shared - Wire:
- 53: Content/Items/wireHorizontal.png

- [x] Shared - Fire Source:
- 87: Content/Sounds/fire.ogg
- 88: Content/Sounds/firelarge.ogg

### Game Textures

- [x] shared - Map:
- 80: Content/Map/iceSurface.png
- 81: Content/Map/iceCraters.png
- 82: Content/Map/iceCrack.png

- [x] Client - Level Renderer:
- 27: Content/Map/background2.png
- 36: Content/Map/background.png
- 43: Content/Map/iceWall.png
- 45: Content/Map/background2.png
- 46: Content/Map/background.png
- 47: Content/Map/dustparticles.png

- [ ] Client - Water Renderer:
- 42: Content/waterbump.png

### GUI Files

- [x] Client - Launcher Main:
- 107: Content/UI/titleBackground.png
- 108: Content/UI/titleText.png

- [x] Client - Loading Screen:
- 78: Content/UI/titleBackground.png
- 79: Content/UI/titleMonster.png
- 80: Content/UI/titleText.png

- [x] Client - Character HUD:
- 138: Content/UI/statusIcons.png
- 143: Content/UI/noise.png (Not sure if its used anymore)
- 148: Content/UI/damageOverlay.png

- [x] Client - Character Inventory:
- 21: Content/UI/inventoryIcons.png

- [ ] Shared - Way Point:
- 109: Content/Map/waypointIcons.png

- [x] Client - GUI:
- 74: Content/Exo2-Medium.otf
- 75: Content/Exo2-Light.otf
- 76: Content/Code Pro Bold.otf
- 78: Content/UI/cursor.png
- 80: Content/UI/style.xml

### Excluded hard-coded files

Although hard-coded its not something that makes sense to edit the files of. (Lighting/damage textures)
- Client - Convex Hull 
- Client - Light Manager
- Client - Light source
- Client - Game Screen

**Comment by etet2** [comment]
adding splashscreen would be a good idea too

**Comment by Regalis11** [comment]
Everything except the waypoint/spawnpoint sprites and waterbump.png has now been moved to xml, I think this can be closed.
