### ISSUE TITLE
[Issue] [Feature Request] Add option for self-published items to NOT UPDATE!

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2570]
once again i have lost like 3 hours worth of work to steam workshop regressively updating my indev mod to the workshop version. 
so long as the game outright DELETES your original mod folder when you upload your mod for the first time, it would be **EXTREMELY** appreciated if there were an option to disable updating the mods that you've published yourself so that you don't lose hour after hour of texture painting and all that. high prio!!! i may be slightly peeved.

**Comment by Regalis11** [comment]
@juanjp600 Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2862314?

**Comment by juanjp600** [comment]
Moving to Review/QA

**Comment by Rokvach** [comment]
This should be a toggleable option in the Publishing tab, as currently you can't update your mod as it doesn't allow you to do so. This does work for subs fine as they aren't originally located in the mods folder, but prevents from mods updating, or if you want to update a submarine which is located in the mods folder. Also turning the mods name red when the update doesn't go thru looks as if there was a bigger issue.
 @juanjp600

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/09b754d2dbe8eeb3275655678f4daccecb4a59fe

**Comment by Rokvach** [comment]
I'm unable to test this fully as I get the notorious limit exceeded error and workarounds doesn't seem to work anymore for me. @Regalis11 do you have time to test this?

**Comment by hubismal** [comment]
this works well enough in the latest versions, but I agree it should be toggleable in case you want to see what people are downloading on their end for some reason.

**Comment by Regalis11** [comment]
Found 2 bugs (not strictly related to this): https://github.com/Regalis11/Barotrauma-development/commit/2289d86 and https://github.com/Regalis11/Barotrauma-development/commit/9e3da266cf51da08aac1b56a9d4f2f31d967a6aa, but other than those can't spot any issues with the fix

**Comment by Rokvach** [comment]
I didn't spot any issues, closing.

**Comment by hubismal** [comment]
This has somehow been reverted, probably in a fix. My mod updates every single time whenever it has changes and I seem to no longer be able to update my mod at all due to the fact that whatever I have loaded when I start up the game is always immediately overwritten with the message [Mod updated successfully].

**Comment by Rokvach** [comment]
Re-opening and moving back to todo

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f768d3b34ff8bc38049c09a5346ec9981b937c60

**Comment by Regalis11** [comment]
@juanjp600 This seems to still be happening #2748

**Comment by juanjp600** [comment]
New issue appears to be different from this one, moving back to Review/QA

**Comment by Rokvach** [comment]
Confirmed working correctly. Closing.
