### ISSUE TITLE
Sending a Component's constant signal to gun's Trigger_In destroys Gun Loader super fast

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2571]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sending a Component's constant signal to gun's Trigger_In destroys Gun Loader super fast (after min/max deterioration immunity)

**Version**
0.9.902

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/180afc247deda3b7189d79de52d2d42e262b1b2d

**Comment by Rokvach** [comment]
No issues, closing.
