### ISSUE TITLE
Crash -- Command Operate Weapon with no Weapon

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#2572]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes when issuing an AI bot command:  Command > Operate > Weapons > Fire at Will -- when there is no weapon to operate.

**Steps To Reproduce**
Create a vessel with no exterior weapon system.  It can have periscopes but no coilguns/railguns.  Order an AI to operate the weapons with Fire at Will.  Game crashes.

**Version**
Windows 10
9.8.0

**Additional information**
Attached crash log.
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/4432912/crashreport.10.log)

**Comment by ekqvist** [comment]
Regalis11/Barotrauma-development@83d71c4 should fix the crash, but it might be a good idea not to display an 'operate' order at all if there's no target available.

**Comment by Rokvach** [comment]
No issues, closing.
