### ISSUE TITLE
Re-Issuing orders (using the re-issue icon) from a previous round causes the game to crash

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2573]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cancelling and Re-Issuing an order (using the Re-Issue Icon/Button) from a previous round causes the game to crash.

**Steps To Reproduce**

In Single Player Campaign:
- Issue orders in a round. Complete the round. 
When you start a new round, the orders from the previous round will still be there (but the bots will act as if they have no orders). 
- Cancel the order and Re-Issue the order using the re-issue icon/button.
- Game will crash.

**Version**
Version .9.902.0 Unstable Windows, branch dev, revision e78dccc24
 
**Additional information**
If you quit the campaign and load the campaign, there will be no orders from the previous round.

Crash Report: 
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/4432913/crashreport.11.log)

**Comment by Rokvach** [comment]
No issues, closing.
