### ISSUE TITLE
Can't mute other players in the lobby

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2574]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to mute players but I still hear them. I think this also extends to in-game as well.

**Steps To Reproduce**
https://streamable.com/pu7sdo

**Version**
Windows 0.9.8.0

**Comment by Regalis11** [comment]
Cannot reproduce in the unstable version, might've been (accidentally?) fixed in the tab menu or voip branch

**Comment by Regalis11** [comment]
Was able to repro now with the steps described in #2579. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66f53ed9acc45b614510c318766e4b4ba25d107c

**Comment by Rokvach** [comment]
No issues, closing.
