### ISSUE TITLE
Putting lots of items inside a toolbox inside a cabinet/crate too fast causes toolbox to come out of them

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2576]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Putting lots of items inside a toolbox inside a cabinet/crate too fast causes toolbox to come out of them and into your inventory.

**Version**
~0.9.902

**Comment by ekqvist** [comment]
Tested to be working correctly after Regalis11/Barotrauma-development@a558784. Dragging and dropping an item into the toolbox was counted as the first click of a double click so the toolbox would be moved into your inventory with just a single click on it after that.
