### ISSUE TITLE
Multiplayer - Reactor sliders moves one tick down after finishing adjusting the sliders via mouse

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2577]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For some reason when you're manually controlling the reactor in multiplayer and need to adjust the sliders, the sliders will move one tick down after adjustments via mouse. When you need to adjust the slider by one tick up for min maxing purposes, you actually need to go two ticks up instead.

**Version**
~0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d173b22236aa5a12b7429c85d5ffbb8106d3fc5

**Comment by ekqvist** [comment]
Tested in MP before and after the fix. Seems to be working correctly now.
