### ISSUE TITLE
Reactor - Clicking on the sliders isn't equal on either side

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2578]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you click on the sliders to increment the fission/turbine (maximum click range. Like going from 40% to 50%), and then click to decrease the fission/turbine (maximum click range again. Like going from 50% to 40%), the numbers doesn't return back to the prior adjustment. I think the decrease click is reducing it more than the increase click (I think it went from 50% to 39%)

That or it could possible this is happening because of #2577 

**Version**
~0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d173b22236aa5a12b7429c85d5ffbb8106d3fc5

**Comment by ekqvist** [comment]
Flicking between two values seems to be working correctly now, the two values remain the same
