### ISSUE TITLE
Abandoned Shuttle Cannot Be Replaced

### ISSUE THREAD

**Issue by Cory-Corrigodone** [Regalis11/Barotrauma#2581]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Abandoning shuttle in previous mission causes the shuttle to be unable to be replaced.
![image](https://user-images.githubusercontent.com/63321012/78724282-f749b900-78e1-11ea-8a56-12032832971b.png)
Shuttle bay
![image](https://user-images.githubusercontent.com/63321012/78724333-134d5a80-78e2-11ea-9089-ce01f1bfd81d.png)

**Version**
~0.9.902.0 (unstable)

**Additional information**
Sub used: Halfdeadkiller's Cyclops Mk II 5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/877c1d422e74791aad3f83129f93eace6e794714

**Comment by Rokvach** [comment]
No issues, closing.
