### ISSUE TITLE
[Bug] Radio headsets range do not scale properly

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2582]
Changing the range of a radio headset's wificomponent range will not properly extend the range for some reason.

**Comment by Regalis11** [comment]
Could not reproduce. I wonder if this could have something to do with the way you're modifying the range? If you're for example using an existing campaign save to test this, the headsets the characters already have will not be affected.

**Comment by hubismal** [comment]
this seems to be a non-issue. cannot reproduce (and i'm actually making this report for someone anyway)
