### ISSUE TITLE
Vertical docking port bugs

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#2585]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have a shuttle docked to your sub using the vertical docking port, its hard and buggy to drag bodies into the shuttle or out of it. Also, you cant shoot bullets through it, but medicine such as Morphine works. 

**Version**
![grafik](https://user-images.githubusercontent.com/63376072/78840100-323f1000-79fa-11ea-89b4-9c25e7f20488.png)

**Additional Information**
https://www.youtube.com/watch?v=Vf683jTu49o&feature=youtu.be

**Comment by Melolatius** [comment]
Accidentally wrote horizontal, whoops

**Comment by Regalis11** [comment]
Fixed the dragging issue in https://github.com/Regalis11/Barotrauma-development/commit/29a0995

**Comment by Regalis11** [comment]
Ranged weapons fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d546a7

**Comment by ekqvist** [comment]
Tested to be working correctly now
