### ISSUE TITLE
[0.9.902] Bots - Cancelling idle activities too soon

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2586]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Orders like Operate Reactor and Operate Weapon allows bots to do Idle activities for some reasons. They may try to repair stuff but will run back to Operate after a short moment of trying to repair, and then back to idle. They are running back and forth between the two objectives now.

**Version**
0.9.902

**Comment by itchyOwl** [comment]
It's intentional that bots can do things autonomously, when they don't have any order. Apparently there were issues in the priority system that caused the idle to launch too easily. Should be fixed now in the dev, but requires testing @Rokvach .

**Comment by itchyOwl** [comment]
I change the idle priority so that it's always 1, which should make this impossible. Let's test how this plays.

**Comment by Rokvach** [comment]
I haven't noticed any issues with this, closing.
