### ISSUE TITLE
[0.9.902] Crash - Void Update(Single)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2588]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Single Player Campaign - Started a Wreck Salvage mission. Crashed into this:
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4456040/crashreport.log)

Didn't persist after the game restarted.

**Version**
0.9.902

**Comment by Regalis11** [comment]
Wasn't able to reproduce this, but I added some null checks to hopefully prevent the game from crashing when this occurs https://github.com/Regalis11/Barotrauma-development/commit/3dc246c.

**Comment by Rokvach** [comment]
No reported cases of this happening since 902 and we've mainly been testing the wreck salvage missions. So closing.
