### ISSUE TITLE
When climbing ladders underwater, character automatically moves upward

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2589]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When climbing ladders underwater, character automatically moves upward

**Version**
~0.9.902

**Comment by Regalis11** [comment]
Fixed in Regalis11/Barotrauma-development@951e636

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
