### ISSUE TITLE
[0.9.902] debugdraw is super laggy

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2590]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
debugdraw is super laggy - Multiplayer(?)

**Version**
0.9.902

**Comment by itchyOwl** [comment]
It is super laggy and unoptimized. But does it matter, much? ;)

**Comment by Kaillera** [comment]
Compared to previous versions it got pretty bad.
