### ISSUE TITLE
[0.9.903] Ruin enemies spawning outside of ruins

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2592]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![](https://cdn.discordapp.com/attachments/668819422919524352/697879004216164423/Capture.PNG)
![](https://media.discordapp.net/attachments/668819422919524352/697879252871152301/Capture.PNG)

**Version**
~0.9.903

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bcfc9ce1d2c5b3f7963ef6e909dbabfff138beba

**Comment by Rokvach** [comment]
No issues, closing.
