### ISSUE TITLE
[0.9.903] Artifacts for Salvage Artifact Mission could appear in cave networks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2593]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seen this several times in 0.9.9xx, not always.
![](https://cdn.discordapp.com/attachments/668819422919524352/697876198260211822/Capture.PNG)
![](https://cdn.discordapp.com/attachments/668819422919524352/697876379005616229/Capture.PNG)

**Version**
0.9.9.0~0.9.903

**Additional information**
This is however a good feature even if unintended. Please make it a thing!

**Comment by Udrakan** [comment]
With some monster spawns in the tunnels, this could be really nice addition.

**Comment by Regalis11** [comment]
I agree, we could and will do more with the caves in the levels. :) We have a ticket about improving the caves in our private repo, and this issue tracker is not intended for feature requests, so I'll close this one.
