### ISSUE TITLE
[0.9.903] Shuttles are all named after the Main Submarine on Radar

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2594]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My Shuttles: Cargo 01, Cargo 02, Zerida, Mashu are all called The Aeche (III) on radar.
![Capture](https://user-images.githubusercontent.com/5086682/78930904-dd8bab80-7a72-11ea-9e23-26f1fd08ca29.PNG)

**Version**
0.9.903

**Comment by 3e849f2e5c** [comment]
Linked submarines now show their correct name in the sonar in [fded2cc](https://github.com/Regalis11/Barotrauma-development/commit/fded2cc8d43cdcec0b73a678365afc0c26d10378)

**Comment by Rokvach** [comment]
No issues, closing.
