### ISSUE TITLE
[Issue][Crowbar] "Disable Wiring" prevent crowbar use.

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2596]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description & Step to reproduce**
If a server host enable the "Disable Wiring" option, then crowbars cannot be used anymore on doors, hatch, ducts block. Sometime a progress bar show up but interactable cannot be opened / closed with.

**Version**
Current 0.9.8.0 version / Windows 10 updated

**Additional information**
I don't know if this is a real bug or if this was intented to prevent griefing at some point. But this "issue" prevent player to "fix" airlock when the door aren't synchronised anymore.

![Sans titre](https://user-images.githubusercontent.com/62913364/78934526-60c8f380-7aab-11ea-922e-c0091e6537d5.png)

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this issue, the crowbars seem to be working with no issues in both single player and multiplayer:
![4taewf](https://user-images.githubusercontent.com/14351070/79347809-c9492200-7f3c-11ea-813a-9e73b1d2053b.png)

**Comment by Ant1V1RU5** [comment]
Strange, maybe there is something else interrupting crowbar use when this option is enabled. I will look into it and let you know.

**Comment by Ant1V1RU5** [comment]
Ok, i maybe know why you cannot reproduce the issue. The real problem was server desync / low quality internet.

I did retry all the step listed above and indeed, this is an "Internet Connection issue rather than the "disable wiring" option in the host"s panel.

I apologize for the confusion.
