### ISSUE TITLE
When hosting dedicated, can't see own's server in game on the same system

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2597]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When hosting dedicated server on a system, you cannot see your own server when you play the game and check the server list on the same system, For now the alternative is to direct join and/or favourite loopback address.

**Version**
~0.9.903

**Comment by thegrb93** [comment]
This works fine for me in 0.9.8.0. It could be that your network is preventing you from connecting to your own external ip address. https://docs.connectwise.com/ConnectWise_Control_Documentation/On-premises/On-premises_knowledge_base/Cannot_access_external_IP_address_from_LAN

**Comment by Regalis11** [comment]
I wasn't able to repro this either. By hosting dedicated, do you mean that you're launching DedicatedServer.exe directly from the game directory? If so, the server will not show up in the server list. To use any Steam networking features (including the server list), the server needs to authenticate via Steam, meaning that you either need to host it through an authenticated client or [using SteamCMD](https://steamcommunity.com/app/602960/discussions/1/1642039363008968297/).

**Comment by Kaillera** [comment]
>By hosting dedicated, do you mean that you're launching DedicatedServer.exe directly from the game directory?

Yes.

**Comment by Rokvach** [comment]
If your ports aren't forwarded or if you don't have upnp enabled in the settings the server won't show up. I need to turn upnp on before I can see mine.
