### ISSUE TITLE
[0.9.903] Missing Entities

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2599]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Happens anywhere from round start. spectating mid round, kicked mid round, and rejoining mid round.
[Serverlogs.zip](https://github.com/Regalis11/Barotrauma/files/4459186/Serverlogs.zip)

**Version**
0.9.903

**Comment by Regalis11** [comment]
Duplicate of #2382
