### ISSUE TITLE
[0.9.903] Wreck1 Cargo Bay 2 Problems

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2600]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Missing gap going into the loose vent hull.
2. Motion Sensor Door going into loose vent hull is on toggle_state

**Version**
0.9.903

**Comment by danielasteljoki** [comment]
Gap fixed in bfaecfa. Motion sensor being wired to toggle is intentional, wiring being visible ingame wasn't.

**Comment by Regalis11** [comment]
Tested, no issues
