### ISSUE TITLE
[0.9.903] Berilia Cargo Bay Lamps aren't "Is On" by default

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2601]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Berilia Cargo Bay Lamps aren't "Is On" by default. Pressing the buttons to toggle doesn't turn them on.

**Version**
0.9.903

**Comment by Regalis11** [comment]
https://github.com/Regalis11/Barotrauma-development/commit/4496146

**Comment by Rokvach** [comment]
No issues, closing
