### ISSUE TITLE
[0.9.903] Wrecks Lamps aren't "Is On" by default

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2602]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Many of the Wrecks Lamps aren't "Is On" by default, making them all pitch dark and you must bring your own light sources.

**Version**
0.9.903

**Comment by Regalis11** [comment]
@danielasteljoki bug or a feature?

**Comment by danielasteljoki** [comment]
Feature. That said, we're in the process of adding more ambient light to wrecks, making them not as dark.
