### ISSUE TITLE
[0.9.903] Wrecks Loot Issues

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2603]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Berilia_Wrecked1 - Reactor Room: Cabinet Mispelled "wreckreactorgcab"
2. Dugong_Wrecked - Medbay: Missing "supplycab" tag
3. Dugong_Wrecked - Engine Room: Non-mission Logbook
4. Kastrull_Wrecked - Engine Room: Missing "supplycab" tag
5. Kastrull_Wrecked - Engine Room: Non-mission Logbook
6. Kastrull_Wrecked - Engineering: Missing "supplycab" tag
7. Kastrull_Wrecked - Medbay: Toxic Cabinet no loot tag
8. Kastrull_Wrecked - Medbay: Missing "supplycab" tag
9. Wreck1 - Lack of Supply Cabinets for medicine loots
10. Hemulen_Wrecked - Lack of reasons to enter Ballast/Oxygen area except for Thalamus Brain > Corpse loot kinda sucks.
11. Corpses - Loots kinda sucks. Needs some rare loot varieties or some varieties that still have ammo.
12. Corpses - Missing Clowns. Praise the Honkmother!

**Version**
0.9.903

**Comment by danielasteljoki** [comment]
Non-mission logbooks are for flavor. Tagged a bunch of supply cabinets and added clown corpses too. Praise.

**Comment by Rokvach** [comment]
I didn't spot any issues, closing.
