### ISSUE TITLE
[0.9.903] Orca Water Alarm never turns off

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2604]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Orca water Alarm never turns off. I assume there's a blank false output somewhere.

**Version**
0.9.903

**Comment by Kaillera** [comment]
Tested again, no issues.

**Comment by thegrb93** [comment]
Could be an intermittent networking issue. I've had this happen on a few ships, but assumed it was bad wiring.

**Comment by thegrb93** [comment]
This happens with other ships too. Seems to be a rare intermittent networking issue.

**Comment by thegrb93** [comment]
Even removing the alarm with wrench won't make the sound go away.
