### ISSUE TITLE
Default screen selection:

### ISSUE THREAD

**Issue by rgb55** [Regalis11/Barotrauma#2605]
Hello, 
V0.9.8.0
It would be nice selecting the default start screen for the game without to have to select each time in the setting windowed and the moving the screen to the desired display.
Regards, Roland

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1753](https://github.com/Regalis11/Barotrauma-development/issues/1753) via [**ZenHub**](https://www.zenhub.com/)
