### ISSUE TITLE
[0.9.903] When adjusting Siren and Alarm Light Component Range higher, Light is displaced

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2606]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When adjusting Siren and Alarm Light Component Range higher, Light is displaced by shifting downward.

![Capture](https://user-images.githubusercontent.com/5086682/78983120-8f69bd00-7af1-11ea-9ddb-feb1b22d1600.PNG)

**Version**
0.9.903

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddbf2cf8ddb6ebdd2fd684c295057cfe7ebedb41

**Comment by Rokvach** [comment]
No issues, closing.
