### ISSUE TITLE
[0.9.903] Wreck failed to spawn 

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2608]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Going to Oshan Outpost on this save file, the wreck failed to spawn. Can't complete Wreck Salvage mission.
![Capture](https://user-images.githubusercontent.com/5086682/78985633-4b79b680-7af7-11ea-8c9d-a78c25336ca9.PNG)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/4461182/Save.zip)

**Version**
0.9.903

**Comment by Regalis11** [comment]
This no longer seems to occur in the latest versions, probably because of the changes to the level generation parameters.
