### ISSUE TITLE
Big sprite of Logbook

### ISSUE THREAD

**Issue by Pod-vodnik** [Regalis11/Barotrauma#2609]
**Description**
Large item sprite

**Steps To Reproduce**
Pick up

**Version**
0.9.903.0 

![photo_2020-04-10_23-21-40](https://user-images.githubusercontent.com/63470746/79013390-123a5880-7b82-11ea-906a-9922dec64223.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/704c24217771e68070ed04299414555514b8b0ca

**Comment by Rokvach** [comment]
No issues, closing.
