### ISSUE TITLE
[Bug] [Fabricator] Fabricator does not show the condition of an item needed to fabricate

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2612]
Self explanatory. If something only requires 1/4 of an item for fabrication, it will show the item in the fabricator without a bar to represent its condition. Misleading for things like wires that only require a fraction of an item.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4081016

**Comment by Rokvach** [comment]
No issues, closing.
