### ISSUE TITLE
Character Editor Test Pose Crash

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#2613]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes when a character goes into Swim Mode while Test Pose is enabled.

**Steps To Reproduce**
Go into the Character Editor, Select a human/humanoid character, enable Test Pose, then press E to swim.

**Version**
v0.9.903.0 , Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6b140b5

**Comment by Rokvach** [comment]
Wasn't able to reproduce, working correctly. Closing.
