### ISSUE TITLE
Game crashes on startup (Linux)

### ISSUE THREAD

**Issue by orynus** [Regalis11/Barotrauma#2614]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to start the game over the steam platform, it shows a black screen and a popup, that the game has crashed. 

**Steps To Reproduce**
Maybe trying to start the game over a similar linux system could help reproducing this bug.

**Version**
System: Unix 4.10.0.38 64 bit (Mint 18.3)
Game: 0.9.8.0 (ReleaseLinux, branch release, revision edb4de8c31)

**Additional information**
Generated crashreport: [crashreport.log](https://github.com/Regalis11/Barotrauma/files/4464410/crashreport.log)

I have the mentioned library _freetype6_ installed and it should be accessible.
As it seems, the game is trying to access some files in the developer's home directory:

> at SharpFont.Library..ctor() in /home/joonas/Barotrauma/Libraries/SharpFont/Source/SharpFontShared/Library.cs:line 77

**Comment by Regalis11** [comment]
The paths in the crash report don't actually mean the game is trying to access that file, it's just where the source files were located when we compiled the game. 

As for the error, I unfortunately can't think off the bat what could be causing it. Need to take a closer look into this next week, sorry for the inconvenience! :/

**Comment by danieldresser** [comment]
For reference if someone else runs into this, I ran into this, and was able to get the game running by copying my system libfreetype overtop of the libfreetype that ships with the game ( eg: `cp /usr/lib/x86_64-linux-gnu/libfreetype.so.6 /home/daniel/.steam/steam/steamapps/common/Barotrauma/libfreetype6.so` ).

This is on a rather dated Ubuntu 16.04.6 LTS install - I guess something about the libfreetype you supply is incompatible with this system.  I was rather surprised that just copying the system libfreetype overtop worked, but after doing that, the game appears to all be working perfectly.

**Comment by orynus** [comment]
@danieldresser That actually worked for me too. The game seems to work now without problems. Thanks!
