### ISSUE TITLE
Liquid Oxygenite requires a Oxygenite Shard in the recipe to craft

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2616]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Liquid Oxygenite requires a Oxygenite Shard in the recipe to craft. When you can clearly just deconstruct the shards for more.

**Version**
~0.9.903

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/860356f0417b05183f57099997d3613168c166f7

**Comment by Kaillera** [comment]
In my opinion, I think it should've been the other way around. This makes sky alien artifact pretty useless as the way to make deusizine is already pretty harsh.

**Comment by Regalis11** [comment]
Moving this back to backlog, I assumed the deconstruct products were a leftover that shouldn't be there without putting any more thought into the fabrication recipes.

I think @ezjamsen or @danielasteljoki should take a look at this

**Comment by danielasteljoki** [comment]
There was a bit of a discrepancy with liquid oxygenite being both a product of deconstructing oxygenite shards and also a fabricated solution. Removed fabrication and deconstruction recipes from liquid oxygenite now.

**Comment by Rokvach** [comment]
No issues, closing.
