### ISSUE TITLE
Healing doesn't give Medical EXP

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2617]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Healing doesn't give Medical EXP. Only way to get better at medical is to craft.

**Version**
~0.9.903

**Additional information**
Maybe for every point of vitality healed, the healer gets 1 EXP. Poisoning aliens and enemies should give 1 EXP for every vitality drained?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a90b3cd

**Comment by Rokvach** [comment]
No issues, closing.
