### ISSUE TITLE
[Feature Request] CPR Button On/Off State

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2618]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In many situations, it's really hard to tell if the character is actually performing CPR on someone. Sometimes I end up pressing the button again thinking it was off, only to turn it off.

**Version**
~0.9.903

**Comment by Regalis11** [comment]
The CPR button does have different sprites for the on/off states (different icon and a glowing green light in the "on" state). Were those not working in some situation or do you mean the state should be indicated even more clearly?

**Comment by Kaillera** [comment]
> The CPR button does have different sprites for the on/off states (different icon and a glowing green light in the "on" state). Were those not working in some situation or do you mean the state should be indicated even more clearly?

Ah so it is. I guess it looked almost the same in both state. I think the whole button should probably be a different color.

**Comment by Kaillera** [comment]
Actually I found a bug: The button sprite looks like same initially and after the first press.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7038d6b

**Comment by Rokvach** [comment]
Wasn't able to reproduce, working correctly. closing.
