### ISSUE TITLE
unable to join password protected lobbies

### ISSUE THREAD

**Issue by cantthink** [Regalis11/Barotrauma#2619]
![Untitled](https://user-images.githubusercontent.com/63523850/79057530-920b1480-7ca1-11ea-9ffc-0ae7b92f4a8a.png)
![Untitled]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
unable to press ok for server password as text box is sitting over the ok button

**Steps To Reproduce**
suspect it is to do with my resolution which is 3440x1440 if i change it to a wrong resolution i can partially see the ok button

**Version**
v0.9.8.0   windows 10 version 1909

**Additional information**
i7 7700k
asus strix z270h gaming
gtx 1080ti aorus extreme 
x34 predator

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a67f20

**Comment by Rokvach** [comment]
No issues, closing.
