### ISSUE TITLE
Repair of any equipment requires skill of mechanics \ electricians 50-55

### ISSUE THREAD

**Issue by Pod-vodnik** [Regalis11/Barotrauma#2622]
I have searched the issue tracker to check if the issue has already been reported.

**Description**
Repair of any equipment requires skill of mechanics \ electricians 50-55. But an engineer or mechanic has only a 40-44 skill level. Because of what they very often receive electric shock, not to mention a character with a lower skill level.

**Steps To Reproduce**
Try to repair any equipment on unstable version

**Version**
0.9.903.03

**Comment by Regalis11** [comment]
@ezjamsen Is this intentional?

**Comment by ezjamsen** [comment]
It is. with a 50 engineering or mechanical skill requirement a baseline mechanic/engineer has around an 80% chance of success performing a repair, which gives them some room to grow as their skill level increases, but at the same time has a small space for mishaps to occur.

**Comment by ezjamsen** [comment]
What I would suggest is that the threshold at which crew call for a medic be increased. Currently it's low enough that a repair mishap which is fairly trivial seems more serious with the bots calling for help. Similarly the explosion effect should be swapped out, it's too dramatic.

**Comment by Pod-vodnik** [comment]
Then can issue a medic player to the team? (single game mode)

**Comment by mrjpjr** [comment]
I like the feature.
1) It gives the medic a more active role early on, whether it is crafting bandages or treating people
2) It "encourages" those with the correct jobs to do them. 
3) It is an excellent tool for getting the players invested into a character, which will (hopefully) cause them to play more seriously.
