### ISSUE TITLE
Periscope Position_Out cannot go trough Junction Boxes.

### ISSUE THREAD

**Issue by sas41** [Regalis11/Barotrauma#2623]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Position Out from a Periscope only works if connected directly to a Position In.

**Steps To Reproduce**

1. Create Periscope.
2. Create Junction Box.
3. Create Rail/Coil Gun.
4. Connect Position Out from Periscope to Signal_2 on Junction Box.
5. Connect  Signal_2 from Junction Box  to Position in Rail/Coil Gun.

**Version**
Windows 10 x64, both 0.9.903.0 and 0.9.8.0 (Windows/Linux/Mac).

**Additional information**
I wanted to create a ship where information and energy flows from one J.Box to another, so that a potential traitor can mess with things, but ran in to this.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ffc8d01d44c47ddad069b9e4bae99c9651f6d8f0

**Comment by Rokvach** [comment]
No issues, closing.
