### ISSUE TITLE
[Bug] [Networking] Serverside, players cannot use customgui/hud during lockhands

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2624]
Self explanatory. In singleplayer campaign I have a variant of handcuffs that allow you to press a "struggle" button to reduce the condition of the cuffs. In multiplayer this doesn't work though. It appears lockhands restricts the usage of buttons serverside but not clientside.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e0b510b1be4f019487bb936195deb784c3a2fea

**Comment by Rokvach** [comment]
Working correctly, closing.
