### ISSUE TITLE
Can't open chat while dragging a body

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2625]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to open and type in chat while dragging a body will not work

**Version**
Windows 0.9.8.0 (and earlier versions)

**Comment by Rokvach** [comment]
This was a temporary decision until we transition to the new inventory UI, but I think we should do something about this as the inventory UI was pushed back.

**Comment by EdusFF** [comment]
Added a quick repositioning of the lower inventory UI area for the current inventory layout due to the revision probably being pushed due to campaign update

**Comment by Rokvach** [comment]
Only issue I noticed was when changing resolution mid-game the grab inventory breaks @EdusFF 

Starting the game in small resolution
![smallresolutiongrab2.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/851c4698-54e0-43a7-af50-db0c0cab40eb)

Changing resolution mid-game
![smallresolutiongrab.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a7c647ae-da68-4eeb-b8f3-dd35490e5613)

**Comment by Rokvach** [comment]
No issues, closing.
