### ISSUE TITLE
Getting Electrocuted in Submarine Editor

### ISSUE THREAD

**Issue by BlueSkyOfEarth** [Regalis11/Barotrauma#2628]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When rewiring items in the submarine editor, you can get electrocuted, stunning you and preventing you from wiring any further unless you switch modes.

**Steps To Reproduce**
You can try it on my submarine. My best guess is that it can happen if you have the reactor turned on and/or with batteries connected to the grid.

**Version**
0.9.8.0

**Additional information**
I have a video showing it, and I can send you my submarine file too. I would upload them here but it seems you can only upload certain types of files.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0abe85ad46e576ec527d958356f3ee81c05ac334

**Comment by Rokvach** [comment]
Wasn't able to reproduce, looks to be working correctly. Closing.
