### ISSUE TITLE
Voice chat quality doesn't diminish over range, but text chat does.

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2629]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I don't remember if radio static was planned or not, but this is something that's been on my mind and currently you can voice chat reliably much greater range than text chat.

**Comment by thegrb93** [comment]
Another tidbit of info, water attenuates radio waves much greater than air, so you would expect the range in water to be much lower.

**Comment by Regalis11** [comment]
Related to #2648

**Comment by JoneKone** [comment]
> Another tidbit of info, water attenuates radio waves much greater than air, so you would expect the range in water to be lower.

Well it actually depends on the radio (read wave length) that is being used. Ironically Text should have much longer range, with acoustic communication networks and multi hopping (ad hock) capabilities.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3679/commits/62d9346d5975da5102b0c9eff8942f77755a0f7d

**Comment by Krzeszny** [comment]
I hope the ranges will be equal, otherwise players who don't use microphones are at a huge disadvantage.
