### ISSUE TITLE
[Bug] Holdables (and its derivatives) don't properly mirror a sprite's origin

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2630]
![2020-04-14-011950_326x222_scrot](https://user-images.githubusercontent.com/47284081/79237275-96673700-7e33-11ea-8681-515a2c0e3785.png)
in the image above, the origin is set to the handle of the lightsaber. it seems that when mirroring a meleeweapon (and by extension holdables iirc) the origin is not properly horizontally flipped to the other side of the item.

**Comment by Regalis11** [comment]
Seems to be working correctly in vanilla items (plasma cutter, firearms, etc), so I think it has something to do with the way you've configured the item.

**Comment by hubismal** [comment]
The plasma cutter and firearms all have sprite origins of 0.5, 0.5 where the mirroring isn't obvious because the origin is in the center. eg:
```xml
<InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="704,0,64,64" origin="0.5,0.5" />
    <Sprite texture="tools_new.png" sourcerect="0,358,248,136" depth="0.55" origin="0.5,0.5" />
    <Body radius="50" width="180" density="40" />
```
For clarification I don't mean the holdpos doesn't mirror properly, because it does, I mean the origin of the sprite.

**Comment by Regalis11** [comment]
Looks like we had attempted to fix this in https://github.com/Regalis11/Barotrauma-development/commit/d14fb5dc15a861fd2e1580cc1b78658933b0b1dc, but that made the issue worse. Hopefully fixed it properly now https://github.com/Regalis11/Barotrauma-development/commit/0429363b38ce08371c5127d01276a2bca0b02e26

**Comment by Jasontti** [comment]
Tested and no issues found.
Closing ticket.
