### ISSUE TITLE
Fields Mislabeled in Turret Interface Form (Submarine Editor)

### ISSUE THREAD

**Issue by BlueSkyOfEarth** [Regalis11/Barotrauma#2631]
The fields that store the minimum and maximum angle for Turrets are mislabeled 'x' and 'y', which causes confusion for some when trying to manually set the angle. 'X' and 'Y' are more for Cartesian coordinates; recommend labeling the fields "Min. Angle" and "Max. Angle".

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/edb74f635692858f5172171f0f4ada389eea7ee4

**Comment by Rokvach** [comment]
No issues,closing.
