### ISSUE TITLE
Components may be removed with wrench despite 'no wiring' setting.

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2632]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If wiring is disabled, a player can still remove components with the wrench and essentially render a ship unusable in some cases.

**Version**
Windows 0.9.8.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f59770f1131f4d307c2e27ade12e26f3d330c730

**Comment by Rokvach** [comment]
No issues, closing.
