### ISSUE TITLE
Infinite husk eggs

### ISSUE THREAD

**Issue by Silenttttttt** [Regalis11/Barotrauma#2639]
You can make infinite husk eggs with a single Calyxanide, a deconstructor, and a medical fabricator.
All you need to do is deconstruct the Calyxanide and craft it again in the medical fabricator. This, instead of giving you 1/4 of a husk egg, it gives you a full one, making you able to repeat that process getting an extra husk egg each time.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cfe88511234ed6aef1e8139be87857fdfd4aea2a

**Comment by Rokvach** [comment]
No issues, closing.
