### ISSUE TITLE
Moving an item to a Toolbox when your Health UI is open, uses the item instead

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2640]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the player's Medical User Interface is open, if you transfer an item into a toolbox (in your inventory), the item will be used instead of being placed inside the toolbox.

**Steps To Reproduce**
1) Have a toolbox in an inventory slot, and a medical item in another slot.
2) Open your own Medical UI.
3) Try to drag the item into the toolbox.
Item will be used instead of placed in the toolbox.

**Version**
Barotrauma 0.9.9.0 branch release, revision a6a459d78
Windows 10

**Additional information**
![unstable health menu toolbox bug](https://user-images.githubusercontent.com/58775950/79518500-3cc36000-801f-11ea-9410-556648349d24.gif)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f7b0ea300c501a9d085e84cfdb12494061a8753

**Comment by Rokvach** [comment]
No issues, closing.
