### ISSUE TITLE
[0.9.9.0] Bots - Electrocuted out of existence

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2641]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Bots get electrocuted for repairing things, rarely their entire body disappears where they were electrocuted. They're frozen in place with only the tools on hand visible, and unable to move or get up.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Haven't been able to reproduce this or seen this occur: have you seen it happen in multiplayer, single player or both?

**Comment by Kaillera** [comment]
Singleplayer

**Comment by Regalis11** [comment]
Alright, thanks for the clarification! It may have been caused by simple physics, so I think we can close this and reopen if the issue resurfaces.
