### ISSUE TITLE
Bots - Getting stuck and then killed in weird places (Near Hatch/Doors/Corners)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2644]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I'm not sure what it is, but I always find bots stuck inside walls near doors/hatches and sometimes on corners (Players can get stuck on corners too). I have never been able to see themselves get stuck on screen as it happens, seems to always happen offscreen.

https://youtu.be/FLVHnNII2ic

Usually whenever they get stuck in places like these, they either suffocate or receives a lot of internal damage to death.

**Version**
~0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c00740fc891e3d78532b488ac6e1fe6222832c8

**Comment by Rokvach** [comment]
No issues, closing.
