### ISSUE TITLE
Workshop sub list fails to show everything

### ISSUE THREAD

**Issue by storm37000** [Regalis11/Barotrauma#2646]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am subscribed to 58 subs, only 49 are showing up in the list and thus only those can be enabled and show up in mods folder.  I have tried any/all combinations of deleting things and reinstalling to no avail.

**Steps To Reproduce**
subscribe to over 49 subs i guess.

**Version**
0.9.8.0 on Windows 10

**Comment by Regalis11** [comment]
@juanjp600 Was this addressed in some of the Steamworks-related changes you did?

**Comment by juanjp600** [comment]
Probably fixed in https://github.com/Regalis11/Barotrauma-development/commit/eaa1e910b8db977c869d5c00600d056336341d76, it's been live for a while. Closing.
