### ISSUE TITLE
Special message for traitor does not show up

### ISSUE THREAD

**Issue by ClaytonKelly** [Regalis11/Barotrauma#2647]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was testing the [EMS] Narwhal by myself with the traitor mode set to Yes. I got a Cult of the Husk Mission that told me to search for a special message under a spare oxygen tank in the storage lockers. The ship is pretty small and not hard to search for everything. I cannot find any message at all. I even checked the face masks and pressure suits.

**Steps To Reproduce**
Use map [EMS] Narwhal (ORIGINAL)
Be Captain
Get Cult of the Husk Mission to search for a special message under a spare oxygen tank in a storage locker.

**Version**
Windows 10 64 bit
Game version 9.8.0

**Additional information**

**Comment by Regalis11** [comment]
You might already be aware, but just to be sure, you need to pick up the oxygen tank to see the message: just looking inside the cabinet isn't enough.

But regardless of whether this is a bug in the game or an user error, we've reworked the traitor missions for the upcoming Rusted Remnants update, and this stage of the mission has been removed. So this shouldn't occur anymore after the next update.
