### ISSUE TITLE
Why is the crew so expensive? 

### ISSUE THREAD

**Issue by Pod-vodnik** [Regalis11/Barotrauma#2650]
Will this price be all the time, or will there be changes in future updates?

**Comment by Regalis11** [comment]
Ping @ezjamsen

**Comment by ezjamsen** [comment]
This will be tuned with the campaign update, with different location types offering specialized crew members for substantially more or less. For now it's just defaulting to a fairly difficult price level simply to keep the campaign for what it is now, challenging.

**Comment by Pod-vodnik** [comment]
Thanks for your answer. @ezjamsen
