### ISSUE TITLE
Editor: Mass deleting wires gives an error

### ISSUE THREAD

**Issue by Digdugxx** [Regalis11/Barotrauma#2651]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Editor: Mass deleting wires gives the error: 'Attempting to remove an already removed item (Blue wire)

**Steps To Reproduce**
I place down the 'Automated docking hatch' for instance and try to delete it again (selecting all the components at once and hitting delete button). 

**Version**
Not sure, the unstable just before 'Rusted Remnants' release. I am running Windows 8.1.

![error](https://user-images.githubusercontent.com/14318297/79616447-fc3a1400-80fc-11ea-9090-9b47da221beb.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9e8df00

**Comment by Rokvach** [comment]
No issues, closing.
