### ISSUE TITLE
The game crashes at the start of the mission

### ISSUE THREAD

**Issue by Bosson56** [Regalis11/Barotrauma#2653]
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4496034/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/4496035/crashreport.3.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4496036/crashreport.log)

**Comment by Regalis11** [comment]
Duplicate of #2620
