### ISSUE TITLE
[0.9.9.0] Remora - Bots unable to enter/exit Ballast

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2655]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are not able to open the hatch to enter/exit from the ballast. The waypoint "looks" correct, but without being able to precisely see the third waypoint type, I can't tell.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/609294ffb2f327f343a86d357dbfed8b56544ac7

**Comment by Rokvach** [comment]
Didn't notice any issues, closing.
