### ISSUE TITLE
Server Lobby - No Ready Button

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2657]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When players joins a server and does not spectate and waits in the lobby, the room does not give those players a ready button even after the round has ended.

**Version**
~0.9.9.0

**Comment by Regalis11** [comment]
Could not reproduce

**Comment by Kaillera** [comment]
It usually happens when they recently get into the server as it is ending round.
