### ISSUE TITLE
[0.9.9.0] Spectator causing server to kick players in the round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2658]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crew was in the middle of a campaign round, a player came in and pressed Spectate. Everyone was kicked for this:
![](https://cdn.discordapp.com/attachments/668819422919524352/700787867462533150/buggy_bug.jpg)
![](https://cdn.discordapp.com/attachments/668819422919524352/700787918205222922/1.PNG)

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0acfaa85a95d1c96e82ea4d015a44e6c5d885345

**Comment by Rokvach** [comment]
I believe this specific issue has been resolved, there's still some spectating issues on the build but I doubt they have anything to do with this. Closing.
