### ISSUE TITLE
Round end text causes overflow due to traitor results

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#266]
Version 0.8.0.0

In the image below, you can see a traitor round had occured, but given there is now multi-traitor support this text can get really long, my resolution is 1920x1080 and this window is much smaller than my screen size but given the potential volume of information there needs to be a GUI component for listing and displaying larger bodies of text.

![image](https://puu.sh/zt1fe/747883acf0.jpg)

**Comment by Regalis11** [comment]
Closed in 375e135
