### ISSUE TITLE
doctorsuniform2 has no resistance against any affliction

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2661]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
doctorsuniform2 has no resistance against any affliction

**Version**
~0.9.9.0

**Comment by Regalis11** [comment]
This is intentional: only the "First Responder" variant gets an uniform with extra protection, but the "Medical Doctor" variant spawns with more medical supplies.
