### ISSUE TITLE
Cannot deconstruct Plastic

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2663]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot deconstruct Plastic back into Silicon and Carbon.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9fb776df28727cccb3ad338f5ece7eeea488b84c

**Comment by Rokvach** [comment]
No issues, closing.
