### ISSUE TITLE
Remora has no, 0, nil batteries installed.

### ISSUE THREAD

**Issue by megawidget** [Regalis11/Barotrauma#2664]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Either the clown got their hands on the syringe gun again or the Remora comes with no batteries whatsoever, making it impossible to recharge things.  Though of course fresh batteries can be crafted.
If the Remora is not intended to have batteries that really should be in the sub description.

**Steps To Reproduce**
Couldn't locate any batteries neither during play nor in the editor.

**Version**
0.9.8, 0.9.9, Mac and Windows.

**Comment by Kaillera** [comment]
The battery charger is in the drone

**Comment by megawidget** [comment]
-_______________________________-

**Comment by Regalis11** [comment]
Added 2 charging docks in https://github.com/Regalis11/Barotrauma-development/commit/609294ffb2f327f343a86d357dbfed8b56544ac7

**Comment by Rokvach** [comment]
No issues, closing.
