### ISSUE TITLE
Only trigger detonators when receiving a non-zero signal

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2666]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Title says it. https://streamable.com/ehllge

**Version**
0.9.9.0

**Comment by Kaillera** [comment]
Sending any signal even 0 causes it to detonate

**Comment by thegrb93** [comment]
Is it fixed?

**Comment by thegrb93** [comment]
@Regalis11 ?

**Comment by Regalis11** [comment]
No, because this is not a bug: the detonator is triggered by any signal.

**Comment by Kaillera** [comment]
install a component that checks the state of the door and output when true, *null* when false

**Comment by thegrb93** [comment]
I'll test that, but that'll be another thing to give away the presence of something suspicious. Maybe I'll just stick to motion detector

**Comment by thegrb93** [comment]
Is there any reason not to make it explode only on non-zero?

**Comment by thegrb93** [comment]
@Rokvach @Regalis11 @danielasteljoki ?

**Comment by thegrb93** [comment]
@Rokvach @Regalis11 @danielasteljoki ?

**Comment by Regalis11** [comment]
The intention behind the logic was that you could trigger the detonator by feeding it any sort of signal from any source, and as Kaillera mentioned, it's possible to make it trigger on non-zero signals with an additional signal check component.

I do agree that in many cases it would be useful to be able to only trigger it on a non-zero signal, so I guess we could consider changing the behavior.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1756](https://github.com/Regalis11/Barotrauma-development/issues/1756) via [**ZenHub**](https://www.zenhub.com/)
