### ISSUE TITLE
On round start, players' voice chat may be muffled. It corrects itself later.

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2667]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When round starts, the player's voice is muffled despite wearing a radio.

https://streamable.com/4q8w1j

**Version**
Windows 0.9.9.0

**Comment by Rokvach** [comment]
I haven't seen this behavior in a while now

**Comment by thegrb93** [comment]
Might be another old issue. Haven't played in a while.
