### ISSUE TITLE
On the new ship when the layout monitor or nav terminal are badly damaged my mechanic me and the engineer got electrocuted trying to fix it but when i got the engineer to repair something else first then it the engineer wouldn't get electroucuted.

### ISSUE THREAD

**Issue by bumpmc81** [Regalis11/Barotrauma#2668]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by thegrb93** [comment]
It's random whether or not you get shocked.

**Comment by ekqvist** [comment]
As already commented, the probability of electrocution depends of the skill requirement for the repair and the corresponding skill of the repairing character. Engineers are usually better at repairing electrical devices and mechanics are better at repairing mechanical devices.
