### ISSUE TITLE
Problem with copying wires.

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#2669]
When copying wires (laid out from inventory and not connected at all), you cannot interact with copies of wires in any way.

**Comment by Regalis11** [comment]
Sorry for the super late reply: what exactly do you mean by copying wires? Copypasting them in the sub editor?

**Comment by NicolaruS** [comment]
Error repetition algorithm:
1.In the submarine editor I put any wire "on the field"
2. I select this wire and use either the ctrl + c key combination or press on the wire with the right mouse button copy to clipboard
3. I use the key combination ctrl + v or press the right mouse button paste
4.A new wire is allocated in place of the old
5. I remove the new wire and in its place the old wire remains with which it is impossible to interact in any way.
Game version unstable 0.10.4.0

**Comment by NicolaruS** [comment]
It is necessary to copy wires, for example, to assign the property "hidden in game" to a set of wires

**Comment by Regalis11** [comment]
Thank you for the clarification, I was able to repro it now!

Seems to have been caused by the same bug as #3403, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/42890db6ff8474f55a3763e486a6c5da2aaf4029

**Comment by Rokvach** [comment]
No issues, closing.
