### ISSUE TITLE
Failed to decode Opus buffer

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2671]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/79796312-59afaa00-8323-11ea-92a2-e51408b1a168.PNG)

**Version**
0.9.9.0 2a82f

**Additional information**
Happened randomly during a round. There wasn't anything going on other than chatting and repariing.

**Comment by juanjp600** [comment]
Duplicate of #2533
