### ISSUE TITLE
Relays don't properly adjust to load.

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#2672]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Relays fail to stabilize their power output in a timely fashion, usually causing overvolting or weird power grid fluctuations. On the included test sub, junction boxes powered by a relay will fluctuate repeatedly, before eventually settling to around the load. However the relay will occasionally increase the power even though the load hasn't changed. 

This problem is easily seen if you turn the reactor off, and then turn it on and quickly examine a junction box powered by a relay. The load will raise to around 2000, overvolting the junction box since the junction box has a 1000 kw load from one oxygen generator, but the grid is pulling a total 2000 kw load from the two oxygen generators. Eventually the relay will lower the power output to proper levels, but fluctuate between 1010 - 1050, at seemingly random amounts. This is probably why I see a lot of user subs with flickering lights, especially when including batteries into the mix.

**Steps To Reproduce**
1. Ensure grid load is 0.
2. Turn on Reactor.
3. Examine a junction box's load when that junction box is powered by a relay.

**Version**
Barotrauma Unstable 0.9.9.0 revision 2a82f4780 - Windows 10

**Additional information**
Included is a sub.zip with a few example use cases of relays. The junction boxes wired directly after relays exhibit weird behavior regarding load, if the junction box is powered by the relay.
[A.RelayDemo.sub.zip](https://github.com/Regalis11/Barotrauma/files/4507590/A.RelayDemo.sub.zip)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
