### ISSUE TITLE
[Question] [XML Modding] Is there a way to hide the condition bar?

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2674]
hey reg/itchyowl or whoever this applies to
is there a way to hide the condition bar via XML modding? i couldn't find anything in the code about it for some reason (although i could be looking in the wrong file).
if not, could you add it? this would allow modders to do creative stuff with damagesprites without having the conditions be so obvious.

thanks.

**Comment by Regalis11** [comment]
Unfortunately this is not possible at the moment, but it'd be very easy to add. Moving this to backlog!

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/57c6f0ab3f5cc2bb26a960cf8d9bcf8c29bfbd0a

**Comment by Rokvach** [comment]
No issues, closing.
