### ISSUE TITLE
[EDITOR][KEY MAPPING] The "Q" key on a AZERTY keyboard cause issue

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2676]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description + Steps to Reproduce**
Using an AZERTY keyboard, when one try to move the camera around in the submarine editor using ZQSD, it open/close the items selection menu. This make the use of the editor tedious for non QWERTY keyboard user.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Wrecks update / Windows 10 updated + Using an AZERTY keyboard

**Comment by 3e849f2e5c** [comment]
[ff17c35](https://github.com/Regalis11/Barotrauma-development/commit/ff17c357de576f532d61905a3e31e84d5f66da05) -> Set the keybind for toggling the catalog to the unused "toggle inventory" keybind setting like it was supposed to so it can be rebound but I had forgotten to.

**Comment by Rokvach** [comment]
No issues, closing.
