### ISSUE TITLE
Low Performance on MacOS on version 0.9.9.0

### ISSUE THREAD

**Issue by BurykinNikolay** [Regalis11/Barotrauma#2679]
I have searched the issue tracker to check if the issue has already been reported.

**Description**
Version 0.9.9.0 have problem with performance on MacOS
After last update game have a low performance on macOS with integrated GPU (with eGPU everything it'OK);

**Steps To Reproduce**
Install version 0.9.9.0 from Steam and launch game. 
Start mission;

**Version**
0.9.9.0

**Additional information**
My mac setup:
macOS Catalina 10.15.3
1,4 Quad-Core i5
8 gb Memory
integrated GPU Intel Iris Plus 645
EGPU: RX 480 4gb

Prev. version of game work very well on integrated GPU;

**Comment by Rokvach** [comment]
Related: https://steamcommunity.com/app/602960/discussions/0/2265817017314755347/

**Comment by Regalis11** [comment]
Unfortunately the integrated GPU doesn't meet the minimum requirements of the game. We have been doing some optimizations to make it run better on low-end GPUs, and will be including those optimizations in future patches, but I'm afraid we can't guarantee you'll be able to run the game properly with an integrated GPU.

**Comment by BurykinNikolay** [comment]
@Regalis11  Sound like a joke. 
Sounds like a joke.
In previous versions, everything was fine. I can also say that a drop in performance can be seen on serious video adapters.

**Comment by jaberkow** [comment]
I am having a similar problem where the previous version before the most recent update ran perfectly, but now I can't get above 10 FPS after the update.

**System Information:**
macOS Catalina 10.15.3
1,4 Quad-Core 2.8 GHz Intel Core i7
16 gb Memory
Intel Iris Plus Graphics 655 1536 MB
EGPU: RX 480 4gb

**Comment by Regalis11** [comment]
@jaberkow I'm afraid your GPU doesn't meet the minimum requirements of the game either.

@BurykinNikolay It's not a joke; the game now needs to load more textures to render the wrecks, and the increase in the video memory the game uses may have caused it to go over what your GPU can handle, even if in previous versions it wasn't an issue.

I know this is a disappointing answer, but as mentioned, we will be doing some memory optimization in further patches that _may_ help with the performance. Unfortunately, low-end integrated GPUs with a small amount of video memory still don't necessarily run the game that well.

**Comment by BurykinNikolay** [comment]
@Regalis11 
I explored the changes of the last commit all day and managed to find the reason for the performance drop.
Memory leak occurs after last update of SpriteBatcher.cs (Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/SpriteBatcher.cs)
This is critical for small amounts of video memory.
If you roll back the file changes, then the performance will again be at a high level. Well, in any case, add the possibility of setting this parameter for weak graphics cards.
