### ISSUE TITLE
0.9.9.0 Double clicking to move items sometimes fails

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2680]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Double click items in menus now sometimes fails.
https://streamable.com/1rzads

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fe4e98f760a8aacb3be5600db7cdd78f04836e4c

**Comment by thegrb93** [comment]
0.9.9.1 still a little jank sometimes. https://streamable.com/px50g0

**Comment by thegrb93** [comment]
Nvm it's behaving the same as before the patch so I'm assuming it's not in it.

**Comment by Rokvach** [comment]
Wasn't able to reproduce, seems to be working correctly. Closing.

**Comment by thegrb93** [comment]
@Rokvach what version? It's definitely not working in 0.9.9.1. Seems to get worse the more players are in the server.

**Comment by Rokvach** [comment]
Coming with the next patch, no ETA.

**Comment by thegrb93** [comment]
Ok cool
