### ISSUE TITLE
Incorrect render order while holding more than your inventory

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2681]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game seems to think the flash powder is in my other hand, but switching items and messing around does weird stuff.
https://streamable.com/52mbjg

**Version**
0.9.9.0

**Comment by thegrb93** [comment]
Haven't ever seen this again so probably closable.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f7ad42e11972dfeccdcec5d0b666465071e34921

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
