### ISSUE TITLE
Teleportsub changelog description not matching gameplay.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#2682]
- [x] I have searched the issue tracker to check if the issue has already been reported.

![image](https://user-images.githubusercontent.com/41012467/80167329-cad3b380-85e8-11ea-98e3-069adff6d022.png)
![image](https://user-images.githubusercontent.com/41012467/80167336-d030fe00-85e8-11ea-8932-92169cdc5df8.png)

Can't resist saying, that the incorrect changelog version sounds much more interesting than being able to teleport the sub only to the beginning or the end of the map.

**Comment by Regalis11** [comment]
Actually, the changelog is correct, the in-game description has just not been updated. You can teleport the sub to the position of the cursor by using "teleportsub cursor".

**Comment by Regalis11** [comment]
Fixed the incorrect help text in https://github.com/Regalis11/Barotrauma-development/commit/2d8665f

**Comment by Rokvach** [comment]
No issues, closing.
