### ISSUE TITLE
Docking hatch physics and external button detection still attrocious

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2684]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying frantically to get in while O2 is depleting.
https://streamable.com/5v3vqe

**Version**
0.9.9.0

**Comment by thegrb93** [comment]
Keep watching later to see my ragdoll interact with the hatch

**Comment by Regalis11** [comment]
Related: https://github.com/Regalis11/Barotrauma/issues/2866

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6b763a7d8ead7992a8ba31562a90f91c9b23c93

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
