### ISSUE TITLE
[0.9.9.0] Husks attack human husks wearing diving suits

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#2687]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon dying after reaching the last stage of infection as a human, you are revived as an AI human husk, which is normally not attacked by things like normal husks and crawler husks, however, if you were wearing a diving suit, the husks will attack "you".

**Steps To Reproduce**
1) Control a human
2) Give yourself the huskinfection affliction using console commands or be infected by a husk / manually infect yourself with husk eggs.
3) Wear a diving suit.
4) Wait until you reach the final stage and die.
5) Spawn a husk and/or a crawler husk in the room.
6) Watch how your human husk is attacked by the other husks.

**Version**
0.9.9.0
OS: Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@8659f00.

**Comment by Emanthealmighty** [comment]
Fixed / Working properly as of v0.9.10.0

**Comment by Rokvach** [comment]
Closing
