### ISSUE TITLE
Doors show water inside the door itself (Is this a rendering bug?)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#269]
Version 0.8.0.0

It seems (This is new to 0.8.0.0 and was not present in 0.7.0.1) water can overlay on top of a closed door if the room / area behind it is flooded (So I'm told)

Example of this:
![image](https://cdn.discordapp.com/attachments/234751018787799040/416168851185729537/DoorWater.png)

**Comment by juanjp600** [comment]
This was most likely introduced in https://github.com/Regalis11/Barotrauma/commit/7a413aee933d60ed747253183854eb987c5f6c0c, since items are now rendered in fewer passes, so this door ended up in the water. I don't personally see this as a problem though.
