### ISSUE TITLE
Crash - Void FilterServers()

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2692]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Tried to set some filters on server lobby.
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4530140/crashreport.2.log)

**Version**
0.9.9.0

**Additional Informations**
Specifically Sandbox, Mission, Campaign filter button.

**Comment by Rokvach** [comment]
This issue has already been fixed in Unstable, closing.
