### ISSUE TITLE
Make salvage artifact and salvage wreck missions spawn ruins and wrecks, if not available

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2693]
Currently, the salvage missions use existing ruins and  wrecks. This prevents us from making biomes without any ruins or wrecks in them, because the missions will spawn the item out of the map.

Suggestion: If no ruin or wreck is available, spawn one for the mission. This will ensure that these missions will work properly in all situations and allow us greater creative freedom with the biomes.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1760](https://github.com/Regalis11/Barotrauma-development/issues/1760) via [**ZenHub**](https://www.zenhub.com/)
