### ISSUE TITLE
[Issue] Legacy Carrier Missing

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2694]
Unsure if this was reported already, couldn't find anything like it. For some reason the legacycarrier seems to be missing from the game and you are unable to spawn it in and can't see it in the charactereditor. Obviously inconsistent with the legacy treatment of every other monster.

**Comment by Regalis11** [comment]
Readded in https://github.com/Regalis11/Barotrauma-development/commit/7f1db79b6ce9a227da471e0beef3271ea4694169

**Comment by Rokvach** [comment]
Should the Carrier have a legacy prefix like the other legacy creatures has? @Regalis11

**Comment by Regalis11** [comment]
I don't think that's necessary since we don't have a non-legacy version of the carrier (mantis is also called just "mantis" because there's no other version of it). If we changed the name/identifier now, it might cause issues with mods that use the carrier.

**Comment by Rokvach** [comment]
No issues, closing.
