### ISSUE TITLE
Traitor mission, 'dispose of item', fails if you toss them out the airlock instead of deconstructing

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2697]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Got all the oxygen masks in a crate and chucked them out of the ship, but that wasn't enough to complete the traitor mission.

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
I wasn't able to reproduce this, throwing the masks out in a crate completed the objective as expected. I wonder if there were still some additional diving masks somewhere in the sub?

**Comment by thegrb93** [comment]
Maybe it was still counting masks in player's inventory? Or maybe dead players?

**Comment by thegrb93** [comment]
It was [EMS] Black Bass, a really simple ship very hard to miss any masks. I count 15 total in it. Is there a command to assign myself the mission? I want to try reproducing it.

**Comment by thegrb93** [comment]
I reproduced it and found the problem. You have to be holding it outside of the ship to work; what I did was flush it down the garbage hatch.

**Comment by Regalis11** [comment]
Thanks for the extra info! I only tried taking the masks out by carrying the crate outside, but will give it another try with that method.

**Comment by Regalis11** [comment]
Managed to repro this now. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4444bc05855ed1314ccd4362ab7fe176c0125932 and https://github.com/Regalis11/Barotrauma-development/commit/5b4b9d162f43fb66c293c38b8ab172e0d31e77a0

**Comment by Rokvach** [comment]
No issues, closing.
