### ISSUE TITLE
Tab menu crash

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2699]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Opened scoreboard and crashed in a multiplayer game.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4532518/crashreport.log)

**Version**
0.9.9.0

**Comment by Mirotworez** [comment]
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/4533777/crashreport.5.log)

to have that trouble

**Comment by EdusFF** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f69704ad172c84131d6048622ebb10874b6aa52c

**Comment by Rokvach** [comment]
No issues, closing.
