### ISSUE TITLE
Railgun/Depth charge ammunition does not detonate contents on impacts/collisions/creature hits

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#270]
Version 0.8.0.0

I used the projectile code earlier in version 0.7.0.1 and players were telling me that railguns did very little, and I began to think they were not exploading.

Having finally gotten around to testing this using the 0.8.0.0 code (I didn't test if it was the case when I gave parts of the code a try in my mod on 0.7.0.1) it turns out this is indeed a problem.

Here are 5 rounds shot straight up all filled with C-4 Block's, they did not hit terrain while rising and when picked up they contain full health C-4 Block's.
![image](https://puu.sh/ztcEF/0d2873a944.jpg)

**Comment by NilanthAnimosus** [comment]
I've been told its possible the explosion from a nuclear shell might also not be Occuring but I've not tested it.

**Comment by Regalis11** [comment]
The railgun shells should be fixed by b7bb78b. The depth charges nuclear shell explosions seemed to be working correctly though - if there's indeed something wrong with them I think I need more details on how to reproduce the issue.

**Comment by NilanthAnimosus** [comment]
I cant seem to reproduce the issues that I've been told from nuclear shells so I'm going to close this issue.
