### ISSUE TITLE
Killed by invisible fire

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2701]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://streamable.com/4x8cel

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
It seems you were killed by the heat from the huge fire in the room next to you.

**Comment by thegrb93** [comment]
Could you at least make the update rate of the health bar better? I passed out even though I had 30% health left.

**Comment by thegrb93** [comment]
Guessing this is still a problem https://github.com/Regalis11/Barotrauma/issues/721

**Comment by thegrb93** [comment]
Actually the issue seems weirder than that. Look at what happens to this guy on the right:
https://streamable.com/w505o1

**Comment by thegrb93** [comment]
I think there's something wrong with fire position calculation when the fire is in another room.

**Comment by thegrb93** [comment]
I'm happy this is better, but you guys nerfed fire too hard. I just saw someone laying in a reactor inferno for 10 seconds survive with 50% health after being extinguished.
