### ISSUE TITLE
WIFI component not producing a signal readable in the chat box.

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#2703]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
WIFI component will not seem to produce any text in the chat box.

**Steps To Reproduce**
Wire a terminal to the 'Signal In' of a Wifi Component that has the 'Linked to chat' property enabled. Ensure the channel is 1 and you'll notice that anything you type does not seem to pop up in chat. 

**Version**
v0.9.9.0

**Additional information**
tell hex i said hi

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/470e3763d95e060d7b60cfa2c3fe005d21d0a38a and https://github.com/Regalis11/Barotrauma-development/commit/10081abdae79abd2f5c72d17de79a3cf6d18b15e

**Comment by Rokvach** [comment]
Tested using the steps provided and its working correctly. Closing.
