### ISSUE TITLE
[Feature Request] Search/Filter for content packages

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2706]
As all workshop packages are force installed now, a method of more-quickly finding and enabling/disabling the ones you need would be useful.

(A search-bar in steam workshop would also be appreciated by anyone who uses the ingame GUI to browse and re-install/uninstall instead of steam overlay)

**Comment by hubismal** [comment]
Seconding this, a lot of things in this game need search bars in general, especially mods, the additional cargo option, and submarines in your lobby.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1757](https://github.com/Regalis11/Barotrauma-development/issues/1757) via [**ZenHub**](https://www.zenhub.com/)
