### ISSUE TITLE
Components can be placed within the hull and then can't be interacted with without plasma cutting the hull

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2708]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Components can be placed within the hull and then can't be interacted with without plasma cutting the hull
https://streamable.com/b9wcb8

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
This is intentional, it allows hiding the signal components inside walls the same way as in the sub editor.

**Comment by thegrb93** [comment]
It doesn't make sense to allow characters to do this because you can't even wire them afterward.

**Comment by thegrb93** [comment]
@Regalis11

**Comment by Regalis11** [comment]
You can, by cutting a hole in the wall (the same way as components placed inside the walls in the sub editor). I do know that's a very niche use case and that accidentally placing items inside walls is probably more likely to happen, personally I find this such a low-prio issue that we should be focusing on more urgent tickets.
