### ISSUE TITLE
Can't deconstruct flash powder to seperate components

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2709]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It just passes through the flash powder

**Version**
0.9.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ff77e0da6ccb32bbb1d3544e3e894b2fa9c4a52

**Comment by Rokvach** [comment]
No issues, closing.
