### ISSUE TITLE
Saving game settings failed. {", hexadecimal value 0x1C, is an invalid character.}

### ISSUE THREAD

**Issue by SgtLion** [Regalis11/Barotrauma#2710]
Hi,

Just having this issue whenever I'm in game, it doesn't seem to go away whatever I do. Reinstall/etc hasn't fixed it, really not sure where to start.

![Untitled](https://user-images.githubusercontent.com/9379526/80292687-fa510000-874f-11ea-8522-62fb95c15eec.png)

**Comment by Regalis11** [comment]
It seems your config file has gotten corrupted somehow. There should be a file called "config_player.xml" inside the game folder: if you delete this file, the game automatically recreates it, which should get rid of this error. Note that this will reset all your game settings (resolution, keybinds, selected mods, etc)!

If possible, would you mind sending us that file here? It might help us figure out what was causing this to happen in the first place. The error message suggest that there's an invalid symbol somewhere in the file, and knowing where exactly it is could be useful in diagnosing this issue.

**Comment by SgtLion** [comment]
Hey, thanks for the reply. I deleted the file, but the issue is still the same as above. It's real odd, as I haven't been able to save anything from the very start.

The file seems to end right at 'voicecapturedevice', so I tried changing the chosen input device on the audio settings to the microphone array (you can see my options in the screenshot above). That seems to have fixed the issue.. Please find the config file attached.
[config_player.txt](https://github.com/Regalis11/Barotrauma/files/4536422/config_player.txt)

**Comment by Regalis11** [comment]
I'm glad you were able to work around the problem! I think the name of that capture device might have contained a symbol that isn't allowed in XML files. I'll look into fixing this, thank you for the extra info!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60d33f71cec23e400fba0f413ae38b662fe38d03

**Comment by Rokvach** [comment]
No issues, closing.
