### ISSUE TITLE
Red Cells do not die after defeating Brain

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2712]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if it's intended or not. These cells tend to get stuck in places in the sub that players have a hard time getting to as well. Killing the brain doesn't stop them from tearing the sub apart though.

**Version**
~0.9.9.1

**Comment by itchyOwl** [comment]
It's a known thing. Not really intentional, nor a feature either. Since the spawning is handled via status effects, I'm not sure what's the best way to handle it. Perhaps we could just kill _all_ terminal cells because in normal case there is just one Thalamus active at the same time.

**Comment by ezjamsen** [comment]
It's one of those things where ideally they would all die when the brain gets taken out, but it's within tolerance if they don't. Any solution has to be really simple and painless otherwise I tend to think it's not the best investment of effort for this sprint at least.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@5648b1e. It now kills all terminal cells that are nearby. In practice no cells of other Thalamus organisms should be killed if they happen to be spawned.

**Comment by Rokvach** [comment]
No issues, closing.
