### ISSUE TITLE
the game keeps crashing every time i try to launch it

### ISSUE THREAD

**Issue by boykin1** [Regalis11/Barotrauma#2713]
before i started crashing i didn't have any mods installed i only played on vanilla servers or with friends.
[crashreport .log](https://github.com/Regalis11/Barotrauma/files/4534602/crashreport.log)

**Comment by Regalis11** [comment]
It seems you're missing the vanilla content package (Barotrauma\Data\ContentPackages\Vanilla 0.9.xml) for some reason. You should be able to fix this by right-clicking the game in your Steam library, going to Properties -> Local files and clicking "verify integrity of game files".
