### ISSUE TITLE
Music Volume is still pretty loud at 5%

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2714]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My computer always has a 100% master volume, so whenever I launch Barotrauma, I feel like the Music volume is still pretty loud at even at 5% in game. I usually modify the config_player.xml to 0.02. It works, until I open the settings menu which pushes it to 0% or 5%. Not sure if it's just me.

**Version**
~0.9.9.1

**Comment by HeatedWafflez** [comment]
honestly should max it and see how loud it gets

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1761](https://github.com/Regalis11/Barotrauma-development/issues/1761) via [**ZenHub**](https://www.zenhub.com/)
