### ISSUE TITLE
Reactor resetting to previous value after setting state via wiring

### ISSUE THREAD

**Issue by kevin-lindsay-1** [Regalis11/Barotrauma#2719]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This appears to be a bug, or maybe some missing feedback somewhere, but setting the reactor fission rate/turbine output via a terminal seems to cause it to reset on the next tick. I've tried making sure of lots of little things, but it just keeps resetting.

**Steps To Reproduce**
In sub editor (haven't tried outside):
Wire up a terminal directly to the reactor's `set_fissionrate` and `set_turbineoutput` connection inputs, type in an integer between 1 and 100, and watch it increase, and then immediately decrease.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows 0.9.9.0

**Comment by kevin-lindsay-1** [comment]
Update: i've confirmed this by loading up the azimuth and doing only 2 things:

1. wire terminal `out` to reactor `set_fissionrate`
2. enter test
3. turn off autotemp
4. enter a number that parses to float
5. watch as the reactor slightly changes, and then adjusts back to previous value

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/58c5293bc6a8b8a84563a2bf25a74f686a777cdc

**Comment by Rokvach** [comment]
No issues, closing.
