### ISSUE TITLE
[Question] [Modding] What is the usage of id in <Role> in traitormissions?

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2721]
another question, sorry. 
According to the code there is the option to have a <Role> element in a <TraitorMission> element. It can have the checkers of "id" (Required) and "jobs" (Optional). I *assume* jobs is for restricting the traitor missions to certain jobs, but what is the id parameter for?

**Comment by OverwatchVoice** [comment]
I think the ID value is stored and "imprinted" onto the ID card, so specific characters can have different permissions. But github should be used to report issues, not ask questions, use the forum for that.

**Comment by Regalis11** [comment]
The roles are used by multi-traitor missions: each traitor gets assigned a "role", and each role can be given individual or shared objectives. The id-attribute is simply some arbitrary name given to the role that can be referenced in the objectives, and the job-attribute can be used to restrict the role to certain jobs. 

Here's an example of a two-traitor mission that uses roles:

```
<TraitorMission identifier="flood2">

	<Role id="t1" />
	<Role id="t2" />

	<StartInfoText id="flood_2_traitormissionStartInfoText"/>

	<Objective roles="t1,t2">
	  <EndMessageFailure id="traitormissionfailuremessage"/>
	  <EndMessageSuccess id="flood_2_objectiveSuccessMessage1"/>
	  <StartMessage id="flood_2_traitorobjectivestartmessage1"/>
	  <Goal type="finditem" identifier="divingmask" preferNew="false" allowNew="true" allowExisting="true" allowedContainers="suppliescabinet">
		<InfoText id="flood_2_GoalInfoText_1"/>
	  </Goal>
	</Objective>

	<Objective roles="t1">
	  <EndMessageFailure id="traitormissionfailuremessage"/>
	  <EndMessageSuccess id="flood_2_objectiveSuccessMessage2"/>
	  <StartMessage id="flood_2_traitorobjectivestartmessage2"/>
	  <Goal type="destroyitems" tag="oxygentank" percentage="50">
		<InfoText id="traitorgoaldestroyitems" />
	  </Goal>
	</Objective>

	<Objective roles="t2">
	  <EndMessageFailure id="traitormissionfailuremessage"/>
	  <EndMessageSuccess id="flood_2_objectiveSuccessMessage3"/>
	  <StartMessage id="flood_2_traitorobjectivestartmessage3"/>
	  <Goal type="floodsub" percentage="25">
		<InfoText id="traitorgoalfloodpercentofsub"/>
	  </Goal>
	</Objective>

	<Objective>
	  <EndMessageFailure id="traitormissionfailuremessage"/>
	  <EndMessageSuccess id="flood_2_objectiveSuccessMessage4" />
	  <StartMessage id="flood_2_traitorobjectivestartmessage4"/>
	  <Goal type="killtarget">
		<InfoText id="traitorgoalkilltargetinfo" />
	  </Goal>
	</Objective>

</TraitorMission>
```

**Comment by hubismal** [comment]
this is sick as hell, thanks

**Comment by Regalis11** [comment]
Didn't test it, but looking at the code, it should be possible to use them by including the tags [codewords] and [coderesponse] in the start info text.
