### ISSUE TITLE
Desync Issue

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#2725]
Almost every time I host my modded server it "freezes" completely after a while, usually when rounds end.
This doesn't happen on regular servers.
What can possibly cause this?

**Comment by thegrb93** [comment]
Your mod

**Comment by MrTeco** [comment]
Not helpful

**Comment by Regalis11** [comment]
Since we haven't seen this occur or haven't gotten any reports about it happening in the vanilla game, I would also suspect that it has something to do with your mod. Is the mod available in the Workshop so we could give it a test and see if we can repro the issue?

**Comment by MrTeco** [comment]
It's not on the workshop, as it's not a content package.
It's a mod of the server source code.
But it worked in version 0.8.

**Comment by thegrb93** [comment]
You have to ask the mod maker to fix the mod. It's no longer compatible.

**Comment by Regalis11** [comment]
Yeah, I'm afraid thegrb93 is right, unfortunately there's not much we can do to help you with this.
