### ISSUE TITLE
Ice can spawn over roaming Artifacts

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2731]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ice can spawn over Artifacts, usually failing to grab it due to being deep in the ice.
![](https://cdn.discordapp.com/attachments/157565009726144513/704307304878702662/Capture.PNG)
![](https://cdn.discordapp.com/attachments/587647684794515468/704705284693819392/unknown.png)

**Version**
~0.9.9.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/927ce066679c8164ba18a2b0cac05d2631a8ab71

**Comment by Regalis11** [comment]
Accidentally pushed to Release, cherry-picked the commit to bugfixes now

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore. Working correctly, closing.
