### ISSUE TITLE
[Feature Request] "View Steam Profile" option from in-round tab menu

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2733]
At the moment, it is only possible to view someone's steam profile from the game lobby, it would be useful for moderation & chat to be able to open steam profile while in a round.

**Comment by Rokvach** [comment]
You can already view players profiles and otherwise manage them by either left clicking or right clicking their name in either the chat or in the server log. But I agree Tab menu should also display the profile button for consistency @EdusFF

**Comment by Ek-Videogames** [comment]
I wasn't aware it worked in chat, good to know.
Yeah generally more options for non-admins to easily reach profile is nice.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1702](https://github.com/Regalis11/Barotrauma-development/issues/1702) via [**ZenHub**](https://www.zenhub.com/)
