### ISSUE TITLE
Choose what job bots spawn as in multiplayer / MP campaign?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2735]
Its annoying when playing campaign with a low-population and using 1 or 2 bots to supplement the crew as their random generation sometimes chooses redundant or unneeded jobs. 
(IE, spawning as a security officer or medic when the ship doesn't have any engineers and already has a player medic)

It would be great allowing the host an advanced option to chose what job each bot spawns with, and/or just changing the bot filling behavior to more closely match the way player job quotas are filled so 'required' jobs take higher priority, and overfilled jobs take lower priority.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1762](https://github.com/Regalis11/Barotrauma-development/issues/1762) via [**ZenHub**](https://www.zenhub.com/)
