### ISSUE TITLE
Oxygen Tank Shelf (Wrecked) no loot?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2736]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No chance for even 1 oxygen bottle?

**Version**
~0.9.9.1

**Comment by OverwatchVoice** [comment]
It might as well be intentional?

**Comment by Kaillera** [comment]
Would be funny to mix in welding fuel in there.
