### ISSUE TITLE
[Design] Engine particle trails very unoptimized.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2739]
Running an engine normally for a few seconds seems to almost completely use up the game's limited amount of particles it can draw. The stream of bubbles from a continuously firing engine seems to cut out even when there are no other objects producing particles nearby.

This is most noticeable when using the ship's railguns and coilguns as their muzzle flashes, projectile trails, and explosions occasionally stop rendering.

Thought it has no effect on gameplay obviously, the game's particles cutting out due to being overloaded by engine bubble particles is bad. Yes? I don't really know how else to put this.
Simply reducing the intensity of the emitter would help.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a72ce818f077bcd631c502548473d5801913be7c

**Comment by Rokvach** [comment]
No issues, closing.
