### ISSUE TITLE
Stun Darts are too steel expensive to make

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2741]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
People don't really like to fabricate Stun darts because it requires a full piece of steel to make one. One piece of Steel is generally more useful in other recipes.

**Version**
~0.9.9.1

**Comment by thegrb93** [comment]
How much chloral hydrate do they use?

**Comment by Ek-Videogames** [comment]
It takes 1 chloral per dart, which is technically fair since its same as using a syringe gun.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1701](https://github.com/Regalis11/Barotrauma-development/issues/1701) via [**ZenHub**](https://www.zenhub.com/)
