### ISSUE TITLE
Make submarine move vertically in the sub test mode

### ISSUE THREAD

**Issue by Connorisgameing** [Regalis11/Barotrauma#2742]
**Description**
In the sub editor I've made a sub, when testing it the the editor the decent velocity never changed making me think my sub needed a bigger ballast. But after building a bigger and bigger ballast it still didn't seem to descend. So I decided to try it in campaign and it worked just find showing me decent velocity and actually descending.

So the short of it is, the editor should show decent velocity and let you descend so you can test your ballast and see if they are a good size to use.

**Steps To Reproduce**
Load any sub in the editor and go into the testing mode go to the navigation monitor and try to move down, it won't seem like you do or can. 
Then load any sub or the same one in campaign and it will work just fine of course.

**Version**
Windows 7 
Game v0.9.9.0

**Additional information**
I don't know if this is a full on bug, but it is some thing that would help make the game feel more polished, plus not confuse new sub makers like me and not have to go back and forth from editor to campaign in order to see how well the ballast work.

Capture1 is in the editor
Capture2 is in a campaign 
Capture is my sub I'm testing with
![Capture1](https://user-images.githubusercontent.com/41496469/80674908-5bd6de80-8a70-11ea-8c67-bcb5b3b995e9.PNG)
![Capture2](https://user-images.githubusercontent.com/41496469/80674914-6002fc00-8a70-11ea-847d-ef3524992b35.PNG)
![Capture](https://user-images.githubusercontent.com/41496469/80674917-61ccbf80-8a70-11ea-8680-3e47d416594e.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2646e8a32c2dd60cfb731ee08eb377257da1837c

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Connorisgameing** [comment]
@Rokvach 
But my issues is not seeing decent velocity in the testing mode. 
It's made for testing but how can I test my decent velocity if it won't show me, it's a small gripe but something that I think needs fixing to help the sub making community better test their subs.

@Regalis11 
I'm making a sub RN and nope it's not fixed/working, I'm on steam using the latest update and no mods.

**Comment by Regalis11** [comment]
This fix hasn't been included in the public version yet.
