### ISSUE TITLE
{Feature Request} Power_Out] Reactor

### ISSUE THREAD

**Issue by RamblinMan101** [Regalis11/Barotrauma#2746]
A signal from the reactor which gives how  much power it is putting out.

**Comment by thegrb93** [comment]
Maybe a power sensor component that you can connect to any power output and it outputs the power output/load.

**Comment by RamblinMan101** [comment]
The main use would be to automatically turn on backup power.

**Comment by thegrb93** [comment]
The only issue I think is it leads to the gameplay problem of if you automate the ship, it makes things boring. Engineers have nothing to do.

**Comment by RusChosen** [comment]
Automation as such is already quite doable (with a battery with 1kw capacity and a lamp, if you're curious) and up for players to decide whether they want it or not, a power meter will be just a convenient thing to have, not a game changer.

**Comment by Regalis11** [comment]
Issue moved to [Regalis11/Barotrauma-development #1703](https://github.com/Regalis11/Barotrauma-development/issues/1703) via [**ZenHub**](https://www.zenhub.com/)
