### ISSUE TITLE
[0.8.0.1]Linux dedicated server wrong content pack md5

### ISSUE THREAD

**Issue by storm37000** [Regalis11/Barotrauma#275]
version 0.8.0.1 Linux dedicated server wrong content pack md5 even though its same game release as client.  I even copied the content pack over to the server and it still errors, i'm assuming the md5 is being calculated differently on Linux (maybe you should switch to sha2 instead?).

**Comment by NilanthAnimosus** [comment]
This could be related to commits d36dab42f8907013c285e9fa3f02a9b68c36c83e and 9feb5b694da0ff8d31b15d46062a1094b718f693
