### ISSUE TITLE
Supporter pack doesn't contain latest soundtracks

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#2751]
![hiregalis](https://user-images.githubusercontent.com/51425624/80826213-1664ff00-8b9f-11ea-8a0c-289c7e42ea31.png)

Basically doesn't contain songs like the sub editor theme, unsure if this is intentional.

**Comment by Regalis11** [comment]
We're planning on updating the songs in the supporter pack in the near future when we've got a couple of new ones implemented in the game.
