### ISSUE TITLE
Bots - AI ignores these waypoints

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2752]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are not able to navigate to my engine room when there's a leak right at the engine.
[Corsair.zip](https://github.com/Regalis11/Barotrauma/files/4565561/Corsair.zip)

**Steps To Reproduce**
Set bots on Fix Leaks.
Make sure they aren't in the Engine room already.
Use a Plasma Cutter/Ancient Weapon and cut the left wall of the Engine Room.
Watch them try to repair.

**Version**
~0.9.9.1

**Additional information**
For some reason the waypoints on the ladder and doors here are invisible to the bots.

![Capture](https://user-images.githubusercontent.com/5086682/80827161-795f9180-8bb1-11ea-9744-018c151dccb9.PNG)

They won't climb the ladder. I've tried placing extra platform to help then skip the ladder, but they won't open the door even if they get there. I have to open the door manually for them. If it's for any other tasks in the room, they are able to get there just fine. Alterntively they'll exit the airlock and get loop between in and outside.

**Comment by Kaillera** [comment]
Seems to have been something with the Tail Fin piece. I decided to pull the basic wall and hull inside the sub more to avoid the Tail Fin causing the leak. The bot doesn't have issue getting there now.

![Capture](https://user-images.githubusercontent.com/5086682/80833827-6488fb00-8bbd-11ea-8bdb-223db487c581.PNG)

**Comment by Kaillera** [comment]
I have a similar issue with the front of the submarine when the hood gets damaged. The bots want to fix it from the outside.

**Comment by itchyOwl** [comment]
I tried to reproduce this with your sub, but couldn't. Do you still have the same issue?

**Comment by Kaillera** [comment]
I've skirt around the issue by making the tail fin and nose pieces not cause leaks a long time ago. 

As for the .sub file uploaded in the zip above, if damaging the tail fin and nose from the outside doesn't causes the bot to freak out, I'd guess it'd be fixed.

**Comment by Rokvach** [comment]
There's been a lot of changes to the waypoint logic, I would assume that this was fixed during those other fixes. Closing.
