### ISSUE TITLE
Dangling wires don't display their connections when hovered over

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#2754]
Basically this can be replicated by hovering over a wire in the submarine editor that has at least one end disconnected/dangling. This can be extremely disorientating as on submarines with a ton of wire and other systems, it makes finding the other end of the wire connection sometimes very time consuming.

P.S You might ask that wires can already be unwired by simply dragging them into your inventory from one end as that's what the submarine editor lets you do. This is true, however this happens when you delete the machine itself with a wire connected, as to sub builders this seems like a faster alternative.

v0.9.9.1

**Comment by Regalis11** [comment]
I'm not sure I understand what you mean by this. Do you mean you should be able to see what the item is connected to when hovering the cursor over the wire running on the sub's walls like this:

![4567sdfg](https://user-images.githubusercontent.com/14351070/91294961-005cf900-e7a3-11ea-9e4b-096938d8d1bc.png)

Or that you should see what it's connected to when hovering over it in the wiring interface?

![eeeeeee3456](https://user-images.githubusercontent.com/14351070/91295024-14a0f600-e7a3-11ea-9409-8d64e34cd610.png)

**Comment by HeatedWafflez** [comment]
> I'm not sure I understand what you mean by this. Do you mean you should be able to see what the item is connected to when hovering the cursor over the wire running on the sub's walls like this:
> 
> ![4567sdfg](https://user-images.githubusercontent.com/14351070/91294961-005cf900-e7a3-11ea-9e4b-096938d8d1bc.png)
> 
> Or that you should see what it's connected to when hovering over it in the wiring interface?
> 
> ![eeeeeee3456](https://user-images.githubusercontent.com/14351070/91295024-14a0f600-e7a3-11ea-9409-8d64e34cd610.png)

The first image, when you're in the junction menu.

**Comment by HeatedWafflez** [comment]
In all honesty this is a quality of life suggestion that with second thought isn't that big of an issue. I submitted it awhile back and I'd rather just have it closed.
