### ISSUE TITLE
Bots - AI won't aim with Drone guns

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2755]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When telling bots to operate Drone's coilgun or railgun, they won't turn the gun to aim targets, but will only shoot when hostiles are infront of the gun's line of fire.

[Corsair.zip](https://github.com/Regalis11/Barotrauma/files/4566076/Corsair.zip)

**Version**
~0.9.9.1

**Additional information**
~~The periscope that operates the guns can switch between using either the railgun or coilgun, so I don't know if that had interfered with the bots aiming or not.~~

Is present in the Remora too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fbe58fc43d02250db35a12af707384494d93d9e5

**Comment by Rokvach** [comment]
Worked perfectly with Remora, but when I tested with Corsair, on both the drone railgun and coilgun the AI wouldn't shoot anything, it did aim properly. @Regalis11

**Comment by Kaillera** [comment]
On the Corsair, the periscope that operates the guns can switch between using either the railgun or coilgun, so I don't know if that had interfered with the bots aiming/shooting.

**Comment by Kaillera** [comment]
[0.9.10.0]
Seems fixed.

**Comment by Rokvach** [comment]
Closing.
