### ISSUE TITLE
[Bug] Explosive harpoons detonate when hitting open doorways.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2756]
### Issue:
When trying to fire explosive harpoons through an open door the harpoon bolts just explode on impacting the door frame.

**Steps to reproduce:**

- Load harpoon gun with explosive harpoons
- Open a door on the ship
- Try to shoot through the door with explosive vs normal harpoons

**Comment by Regalis11** [comment]
I wasn't able to reproduce this.
![aeswtetg](https://user-images.githubusercontent.com/14351070/80915455-27f30600-8d5b-11ea-8470-bd920a053f5e.png)

Does this happen in some specific submarine?

**Comment by Regalis11** [comment]
Closing this, will reopen if we figure out the steps to repro
