### ISSUE TITLE
Can't get item from weapon rack after previously getting one from another weapon rack

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#2757]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you grab a weapon from a weapon rack, you can't get another from another weapon rack until you open another container.
https://streamable.com/qiltna

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
Note to whoever ends up working on this: this seems to happen if the cursor is kept on the position of the inventory slot, because the selectedSlot field doesn't get reset until you move the cursor away from it (even if the inventory is no longer visible).

**Comment by thegrb93** [comment]
This also happens with coilgun ammo racks.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e4a81d1c66ee9ebede91506428562b316a79630e

**Comment by Xeavas** [comment]
[0.1200.0.0] - Unable to replicate 👍 
Tested by replicating it in 11.0.9 then attempting to replicate in 12.0.0

Steps I've used :
1. have a container filled with items side by side
2. double click to take item from inventory
3. close inventory UI while not moving the cursor
4. walk till cursor is on another container and open it
5. attempt to double click again with the cursor still in the same spot

**Comment by Rokvach** [comment]
Closing
