### ISSUE TITLE
[0.9.9.1] Sub Editor - Items being replaced by wrecked versions

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2758]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When editting submarines, I am not exactly sure what triggers it, but sometimes the editor will replace some of the submarine's item with wrecked version.

Bunks and Vertical Backs commonly.

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
Haven't been able to reproduce this

**Comment by Regalis11** [comment]
No known steps to repro and no additional reports about this, closing

**Comment by Kaillera** [comment]
It still happens in 0.10.4, but it seems to just happens on it's own.

**Comment by Kaillera** [comment]
using "reloadcorepackage" command and maybe changing mods is the cause of this.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eebf03569cf757b20ba43654a5e08ba9ecbd11ec

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
