### ISSUE TITLE
You can shoot through doors with a harpoon gun? BUG

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#2759]
https://gyazo.com/7990f8a9f5f38d6b12a9a4cb2546401e

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/db212e4009ced96329f4e4e1c878f73c8520d520

**Comment by Rokvach** [comment]
No issues, closing.
