### ISSUE TITLE
Crowbars don't work

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#276]
Crowbars don't seem to do anything. I try the select button, they don't do anything to doors. They still make noise when hitting walls.

**Comment by NilanthAnimosus** [comment]
This is due to 1fe2a1916f200ee66ad1b6e40447cf1b74f192a0 where "Canbepicked" is used by crowbars

A better fix would be to explicitly specify for the ruin door itself that it cannot be picked (Rather than set it as a default for all doors) and any other certain doors to not be using a crowbar on.
