### ISSUE TITLE
Issue with husk infection regarding inventories/loot.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#2764]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![error](https://user-images.githubusercontent.com/9964331/80917504-9b971200-8d5f-11ea-94e4-8e289cfe8f3b.png)
When a creature is turned into another creature through a husk infection, the game will throw in 
[this](https://user-images.githubusercontent.com/9964331/80917504-9b971200-8d5f-11ea-94e4-8e289cfe8f3b.png) error if the original creature doesn't have an inventory, or if the original creature has an inventory and the new one doesn't. The only time this error does not happen is when both the original creature and the new creature have inventories.

**Steps To Reproduce**
1) Make a copy of a bonethresher. The only change we will make is call it "bonethresherhusk". Add "bonethresher" to the huskinfection's affliction targets.
2) Go in-game, spawn a bonethresher and give it the husk infection with a very high affliction strenght, then kill it and watch it turn into the "husk" we made earlier.
3) Notice how the game's console will open up with this [this](https://user-images.githubusercontent.com/9964331/80917504-9b971200-8d5f-11ea-94e4-8e289cfe8f3b.png) error in it. This is due to the fact that neither of the creatures have inventories. This would also happen if the bonethresher had an inventory and the husk one did not, and viceversa.

**Version**
v0.9.9.1

**Comment by itchyOwl** [comment]
Thanks for reporting. Fixed in Regalis11/Barotrauma-development@2e872b2

Detailed steps for repro:
- Remove the inventory from Crawler.xml
- Remove the inventory from Humanhusk.xml
- Control a character
- Type "giveaffliction huskinfection 100" in the console
- Type "kill" in the console
- Spawn and control a crawler and do the same. Either should crash before the fix and not after it.

**Comment by Emanthealmighty** [comment]
Fixed / Working properly as of v0.9.10.0

**Comment by Rokvach** [comment]
Closing.
