### ISSUE TITLE
This live crawler is invisible and unkillable

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2767]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I picked terminate a swarm, and these swarm happen to spawn ontop of a Thalamus Wreck. I thought this crawler was stuck inside the wreck shell, but cutting it reveals nothing. This crawler doesn't have a physical body for me to kill.

![Capture](https://user-images.githubusercontent.com/5086682/80976973-1d378000-8df2-11ea-883f-ad2111e2b1ba.PNG)

**Version**
0.9.9.1

**Comment by Kaillera** [comment]
Using Explosives works.

**Comment by Regalis11** [comment]
Did this happen in multiplayer or single player?

**Comment by Kaillera** [comment]
Singleplayer

**Comment by Regalis11** [comment]
Happened to stumble upon this while debugging another issue. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/dc3d755e713a1b91709485e76ba168485893c6eb

**Comment by Rokvach** [comment]
This fix hasn't caused any other issues, considering how rare the issue is I will just close the ticket, we can re-open if it resurfaces. Closing.
