### ISSUE TITLE
Loading an ongoing multiplayer campaign sub in editor, found something interesting

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2769]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I decided to open up one of my ongoing multiplayer campaign submarine save in the editor to clean up a bit, and I found something interesting that are showing up on the submarine. I am not sure if this will help against missing entity.

[Corsair.zip](https://github.com/Regalis11/Barotrauma/files/4577191/Corsair.zip)

I've already deleted most of it, but if you look far top right of the submarine and use Select All (CTRL+A), you can find black wires, signal check and other components you would find from an Alien Ruin.

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
Couldn't repro this or come up with an explanation as to why they got saved in the submarine file, but https://github.com/Regalis11/Barotrauma-development/commit/ced221a7bc65d9eaa323d1a36314910eb56d395c should prevent this from happening again

**Comment by Kaillera** [comment]
I was playing singleplayer for the last few days and so I've racked up quite a huge amount of these components and wires from alien ruins. I didn't entered much, but there's plenty around in this .sub file to look at.

[Corsair.zip](https://github.com/Regalis11/Barotrauma/files/4600872/Corsair.zip)

**Comment by Kaillera** [comment]
Ran several rounds, don't see ruin wiring and components show up on .sub anymore.

**Comment by Rokvach** [comment]
Closing.
