### ISSUE TITLE
[0.9.9.1] Offset Docking Ports make submarine control difficult in the Nav Terminal

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#2770]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the docking port is not near the center of the sub, the view will zoom in on the docking port, and change the direction the submarine was moving. It isn't easily explained in words, but this is fixed by either removing the docking port camera reorientation, or moving the control origin to where-ever the nav terminal is zoomed in on. I'll include my Atlas sub to showcase this issue.

**Steps To Reproduce**
Undock the sub from an outpost, and observe where the control arrow goes relative to the origin of the arrow.

**Version**
Barotrauma 0.9.9.1

**Additional information**
The .zip contains a .mp4 and a .sub file to view the issue.

[Atlas.zip](https://github.com/Regalis11/Barotrauma/files/4577282/Atlas.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6593fc228e1d45daf41c2a73daab4add4e7eb9e

**Comment by Rokvach** [comment]
No issues, closing.
