### ISSUE TITLE
Hammerheads still tend to be scared away in monster missions

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2771]
This has probably already been reported in the past, but as of the latest update hammerheads are once again becoming scared of the ship for some reason, making them extremely difficult to chase down properly.
It's possible my crew is just extremely unlucky and maybe there was something scaring the hammerhead (like a previous coilgun shot or low health), but regardless, I don't believe that your targets should ever run away from you considering they're always described as "particularly aggressive" or "terrorizing vessels" in the mission briefings, and it can make some missions nearly impossible.

**Comment by Kaillera** [comment]
Threshers part of the mission do too.

**Comment by itchyOwl** [comment]
I have missed this ticket: is it still an issue? There's been some changes that could have affected this during the past half a year this ticket has been lying here unnoticed :F

**Comment by itchyOwl** [comment]
I haven't been able to repro this anymore.

**Comment by Rokvach** [comment]
I haven't seen this happening in a while now, with the new level gen they don't have a way to really escape the players reach as easily as they did previously as well, which eases this issue if it still exists even more. 

Will close this, can be re-opened if the behavior is spotted to happen. Closing.

**Comment by itchyOwl** [comment]
And we also force the aggressive behavior for the mission spawns, so that they shouldn't avoid or escape. Can't remember when the changes were done (and won't take the time to look up), but I think it was during the spring. So if it happens, it's definitely a bug. IIRC only Hammerhead Matriarch should try to avoid the sub when it's a mission target, but she too will attack the sub if the player shoots her.

**Comment by Wheatley1001** [comment]
Hey everyone! We recently spotted this issue resurfacing in modern builds of the game. As of 100.8.0.0, this bug still persists as evident in the following screenshot:
![image](https://user-images.githubusercontent.com/105495756/205415549-2df49cca-790d-4c8a-9352-94790a39ecbf.png)
The hammerheads also seem to want to merge with the ceiling of the map. They've left the generated area (through the gaping hole to the right of every map end) and continued to flee in that direction.

There were also reports of this issue in 0.19 builds, though I'm unsure if it ever got reported.

I'm hoping this ticket can get reopened so it can be addressed.

**Comment by itchyOwl** [comment]
If you encounter the issue again, could you check their state with the "debugai" command. A screenshot with debugai enabled would be helpful. Also see #10072.
