### ISSUE TITLE
Bots - Using old waypoints to Drone when Drone is docked to a new place

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2773]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are using old waypoints to Drone when Drone has multiple valid docking places and uses the non-original docking spots.
![Capture](https://user-images.githubusercontent.com/5086682/81100397-77ac0b80-8eda-11ea-9365-fccb27cac896.PNG)

Normally that hall would be the right place to go into the drone, when the drone is docked in the drone bay of course. When they're tasked to do other stuff on the main sub when in the drone, they'll try to run out the right side of the drone into pressured water instead.

**Version**
0.9.9.1

**Additional Informations**
They seem to be able to navigate between everything just fine in Idle, oddly enough. Even climb out on their own. They don't know how to climb out when they're tasked though.

**Comment by itchyOwl** [comment]
Does it still happen? I did some fixes to the waypoint disabling/enabling in Regalis11/Barotrauma-development@680935a and in Regalis11/Barotrauma-development@3c68936 that might have fixed this issue.

**Comment by Kaillera** [comment]
Yes this still happens on 0.1100.0.6.

**Comment by itchyOwl** [comment]
Possibly related #7274.

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
