### ISSUE TITLE
Shuttle Ballast [9.9.1]

### ISSUE THREAD

**Issue by AisuTistoto223** [Regalis11/Barotrauma#2774]
I build my shuttle. Wire and power everything. Ballast fills and unfills. Ship doesn't go up or down at all. What the hell is wrong? I can't find a similar issue anywhere.

**Comment by VenipedeGaming** [comment]
Are you testing it out in the editor? If so, I might have a similar issue. I don't know though.

**Comment by AisuTistoto223** [comment]
It was in the editor  but also main game. I'm confused and stressed.

**Comment by Regalis11** [comment]
Hard to say; if the ballast is filling up, large enough to make the sub dive and the shuttle isn't docked to anything, it should be moving. Could you send us the submarine file so we see if we can spot the problem?

**Comment by HeatedWafflez** [comment]
If testing the submarine in the editor, submarines can't ascend or descend.

**Comment by Regalis11** [comment]
Yeah, the submarine not moving in the test mode is a known issue (#2742) that we've since fixed (although the fix is not included in the public build yet), but since @AisuTistoto223 mentioned this also happens in-game, it could be a separate issue.

**Comment by Regalis11** [comment]
I guess this might've been happening in the test mode, closing until we get more info
