### ISSUE TITLE
Ai discards empty o2 diving suits (usually in ballast tanks)

### ISSUE THREAD

**Issue by Lordawesome001** [Regalis11/Barotrauma#2776]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The ai will not refill the diving suits with oxygen and toss them. You will eventually see empty diving racks filled with 02 cans but no suits. 

**Steps To Reproduce**
leave near empty oxy suits in the rack for ai to use.

**Version**
windows 9.9.1

**Additional information**
I wouldn't mind discarded 02 tanks on the floor but i don't want my suits sitting in the ballast tanks.

**Comment by Regalis11** [comment]
Thanks for the report! I'd actually consider this a feature request more than a bug, as it's something we haven't yet implemented. We do have a ticket about this in our private repository (https://github.com/Regalis11/Barotrauma-development/issues/1636), and generally avoid having feature requests in the public issue tracker, so I'll close this one.
