### ISSUE TITLE
Targetitemcomponent Parameter for StatusEffects

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2777]
I know you loathe feature requests but this is a good one that I think will absolve a lot of potential future feature requests, at least related to modding.
It would be really nice if there were a `targetitemcomponent` parameter in statuseffects, like how there is for statuseffect conditionals, mostly for the sake of remotely setting values. What the parameter would allow you to do is adjust the scope of your statuseffect to grant you access to setvalues as though the statuseffect were a child element of the itemcomponent in question.
That was a mouthful, so here's an example where we want to set the value of a door component to open, but the statuseffect is within a neighboring lightcomponent, so we use targetitemcomponent to change our "scope" of what values `setvalues` can change (so we can access isOpen, openState, etc).
```
<LightComponent IsOn="true >
<StatusEffect type="OnUse" target="This" targetitemcomponent="Door" setvalue="true" isOpen="true" />
</LightComponent>

<Door>
<blah blah what's here is irrelevant, the important part is that the above statuseffect will have access to the precious door properties as though it were right here />
</Door>
```
This would be extremely useful for remotely accessing items via NearbyItems and changing the properties of components within them, allowing you to remotely open doors, fire repairtools, disable sonar beacons, etc.
I don't think this would be too hard to implement since <Conditional> already has a version of it for reading properties, right?

**Comment by Regalis11** [comment]
Finally got around to implementing this, commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/c464ccfaff09868c5308423c5305cdcea798efa6

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
