### ISSUE TITLE
Wreck1 Cargo Buttons requires id_card to press

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2778]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wreck1 Cargo Buttons requires id_card to press

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
Not sure if this is by design or an oversight, but added the bug tag for now.

Ping @daniaste

**Comment by danielasteljoki** [comment]
Not a bug, except if they don't work with the cards found on the wreck.

**Comment by Kaillera** [comment]
@daniaste they don't work with wreck_id

**Comment by danielasteljoki** [comment]
Ok, sounds like an oversight. I'll take a look.

**Comment by danielasteljoki** [comment]
Should work with idcards found on board the wreck now.

**Comment by Rokvach** [comment]
No issues, closing.
