### ISSUE TITLE
Unable to hit this alien at this spot. Projectile disappears before it.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2779]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Saw a mudraptor grinding against the doors of Wreck1. Was shooting Piercing ammunition at it, but the projectile disappears before it even hits the mudraptor here.

![Capture](https://user-images.githubusercontent.com/5086682/81294128-6aa72d80-903c-11ea-99ef-58b628dfa951.PNG)

**Version**
0.9.9.1

**Additional Informations**
SMG seems to have been able to hit it from a distance.
It was a Thalamus Wreck1.
There was a Cell Spawner behind the door, dead. Which might've absorbed the projectile.

**Comment by Regalis11** [comment]
>There was a Cell Spawner behind the door, dead. Which might've absorbed the projectile.

I think this was the issue (the same as in #2827): non-hitscan projectiles like the coilgun bolts and harpoons would still hit the destroyed thalamus organs, while hitscan weapons like the SMG would still work correctly. Moving to Review/QA.

**Comment by Rokvach** [comment]
Related tickets to this one has already been closed, working correctly now. Closing.
