### ISSUE TITLE
Unable to melee targets outside the sub from inside the sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2780]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to melee targets outside the sub from inside the sub. Had to wait until they entered the hull to get the hit.
![Capture](https://user-images.githubusercontent.com/5086682/81294453-ed2fed00-903c-11ea-9846-bb8d680eabae.PNG)

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe.
