### ISSUE TITLE
Odysseus design flaw

### ISSUE THREAD

**Issue by Lion-JK** [Regalis11/Barotrauma#2781]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have been working on the Odysseus quite a while and now I have seen a design flaw. The depht charge loader has a button above it but the button is nowhere attached and the depth charge tube isn't linked with the depth charge loader.

**Steps To Reproduce**
just load the Odysseus
**Version**
0.9.9.1 Windows
![Anmerkung 2020-05-07 150410](https://user-images.githubusercontent.com/53709213/81297758-0a33e280-9074-11ea-960e-c9a93bac1c80.jpg)
![Anmerkung 2020-05-07 150321](https://user-images.githubusercontent.com/53709213/81297777-115af080-9074-11ea-9ddb-299797543cc2.jpg)

**Additional information**

**Comment by Kaillera** [comment]
That's not a vanilla submarine.

**Comment by ekqvist** [comment]
You'll have to contact the person who made the mod if there's an issue which is caused entirely by the sub's design
