### ISSUE TITLE
Submarine Test Mode - Bots does not do any initiative activities.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2782]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots does not do any initiative activities in test mode.

**Version**
0.9.9.1

**Comment by itchyOwl** [comment]
I don't think this is an issue anymore. I doubt it ever was: I recall there was an issue with autonomous objectives working at some point. Let's just close this one.
