### ISSUE TITLE
Bots - "Unable to find medicine" from a dead character/corpse

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2783]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Had two medics in a room. One dead, one live. There's no morphine left on the sub, except on the dead medic. Other crew member needed healing. Live medic keeps running over the dead medic's body trying to get the Morphine from it.

**Version**
0.9.9.1

**Comment by Kaillera** [comment]
Add Fire Extinguisher to a list of things bots try to get from another body.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3880600b684703d4cfe674da97ec80dc092a5b7

**Comment by Kaillera** [comment]
[0.9.10.0]
Seems good. Bot even grabbed alien blood from a dead crawler inside the submarine to treat it's own blood loss.

**Comment by Rokvach** [comment]
Working better than expected, closing.
