### ISSUE TITLE
Bots - Doesn't uses Diving Knife as weapons

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2785]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots doesn't uses Diving Knife as weapons. Affects Commandos.

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
Could not reproduce. 

The diving knives do have a low combat priority value, which prevents the bots from going to the offensive mode (= going to attack the enemy with the knife), but they do switch to a defensive mode (= trying to move away from the enemy, and using the weapon if the enemy gets close).

**Comment by Kaillera** [comment]
Ah I was hoping they'd be an offensive weapon.

**Comment by Regalis11** [comment]
We made it non-offensive because attacking a monster with just a diving knife tends to be so dangerous that the bots would usually get themselves killed if they tried to do so.

But anyway, since this is an intentional design choice I think we can close the ticket.
