### ISSUE TITLE
Flamer's Fuel Tank implodes itself by the fire it creates when it spawns next to the character

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2787]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Flamer's Fuel Tank implodes itself by the fire it creates when it spawns next to the character.

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d715982b70f6e01a98489a443b0242a4533c57b9

**Comment by Rokvach** [comment]
No issues, closing.
