### ISSUE TITLE
Missing textures - no textures of walls at all

### ISSUE THREAD

**Issue by koralovsky** [Regalis11/Barotrauma#2789]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I don't have any wall textures, they're either transparent or non-existent.

**Version**
PC, Windows 10, version 1.3.11

**Additional information**
I can't find any information about it. I tried everything. I runned B3D RoomMesh Conversion and it didn't work. LightMapPNG keeps crashing everytime I run it. I don't know what to do.

**Comment by Regalis11** [comment]
> B3D RoomMesh Conversion 
> LightMapPNG 

I'm assuming you're talking about SCP - Containment Breach? This issue tracker is for issues regarding Barotrauma.
