### ISSUE TITLE
UseItem doesn't work with RepairTools

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2790]
(Bug, Modding)
The fact that this doesn't work has been brought up by EK Videogames before, but I don't think an actual issue was made as much as it was just complained about. If this is a duplicate, I couldn't find the original, sorry.
Title is pretty self-explanatory, putting the `<UseItem />` statuseffect element in the statuseffect of a repairtool item does not trigger the repairtools repairing-range, or any of the "OnUse" statuseffects, which is definitely a bug since UseItem works with plenty of other components.
This essentially restricts modders from using many of the repairtool exclusive features without a player holding it (e.g. extinguishing fires, mining minerals, repairing segments of hulls, using area damage, etc.) 
Would open up a world of possibilities if this minor bug were fixed.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/421a5969bc09521d729fca689807fb388f0d9fdd

Requires adding `requireaimtouse="false"` to the item config

**Comment by Rokvach** [comment]
Confirmed working, closing.

**Comment by hubismal** [comment]
would be nice if there were a way to rotate the barrel of a repairtool
