### ISSUE TITLE
Flamer harms the user when being used.

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#2791]
When using the flamer, the flame projectiles produced seem to harm the user. Unsure if this is intentional but it can be a nuisance given that this weapon causes supposedly unnecessary harm to the user, especially when it causes a fire that immediately blows up the welding fuel tank inside of the flamer itself. This in itself is even more dangerous as you end up burning to death stunned in the fire you created.

v.0.9.9.1

**Comment by Regalis11** [comment]
This is intentional: the flamer is a pretty destructive weapon and we wanted there to be risks to using it.
