### ISSUE TITLE
Smoke detector is inaccurate

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2792]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Smoke detectors detect fire sources in the hull, and ignore fire sources smaller than 50 units. They should be able to detect fires in nearby hulls as well, and the size threshold could depend on the distance.

**Steps To Reproduce**
- Create a fire in a multi-hull room: detectors in different hulls won't trigger until the fire has spread inside them.
- Create a fire right next to a smoke detector: the detector won't trigger until the fire is more than 50 pixels wide. 
![5467346](https://user-images.githubusercontent.com/14351070/81403994-3cf5dd80-913d-11ea-9308-3958a6179a82.png)

**Version**
Any

**Comment by Diffle** [comment]
And it lacks "Output" & "False Output" fields for some reason. Though water detector have these. 
![image](https://user-images.githubusercontent.com/25946304/81405250-53556680-9148-11ea-86c2-9fbd7c2575ef.png) 
![image](https://user-images.githubusercontent.com/25946304/81405259-594b4780-9148-11ea-8220-003a7312352e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07c03b15791dc88d8527d6d1f2edfd9f3ee3826c

**Comment by Rokvach** [comment]
Confirmed being accurate, closing.
