### ISSUE TITLE
Players not getting the loadout they wanted

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2795]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When starting a round, the game decides to give players other loadouts of the role they picked. Lots of time I wanted to be signal engineer, but get nuclear engineer for instance.

**Version**
0.9.9.1

**Comment by thegrb93** [comment]
Maybe related https://github.com/Regalis11/Barotrauma/issues/2584

**Comment by Rokvach** [comment]
I don't think this is a issue anymore, players are getting the class variants which they choose after the recent class fixes that were done on the comment above this one. Closing.
