### ISSUE TITLE
Opening the Tab menu after controlling Aliens crashes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2796]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Opening the Tab menu after controlling Aliens crashes
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4604125/crashreport.log)

**Version**
0.9.9.1

**Comment by Regalis11** [comment]
Duplicate of #2699
