### ISSUE TITLE
Custom sprite colors revert back to the original value in campaign

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#2799]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So say you modify body armor in the sub editor to have a barely visible sprite, like an 'A' of 50 and all the RGB values being 0 so that it appears barely visible and it looks like it's concealed under your clothing when worn for role-play sake. If you're wearing this body armor during campaign and you end the mission, then start another mission, it'll revert back to its original sprite and it'll be fully visible.

**Version**
v.0.9.9.1

**Comment by Regalis11** [comment]
I was only able to reproduce this in the multiplayer campaign, where this is to be expected: client-side changes in the submarine editor don't get sent to the server, so any changes will be reverted when a new round starts.

Syncing changes done in the sub editor mid-round would take so much work that I don't think it's worth the effort for a niche use-case like this.
