### ISSUE TITLE
Bots - Confused on reloading Railguns with two or more loaders linked

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2801]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are confused on reloading railguns with two or more loaders linked.

Original Thread: https://steamcommunity.com/app/602960/discussions/1/2250055685739259422/

**Version**
0.9.9.1

**Comment by Jasontti** [comment]
Tested.
Doesn't seem to be an issue anymore.
