### ISSUE TITLE
Bots - Multiple Security Officer causing interference with Operate Weapons with Idle activities

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2802]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have security officers even if they aren't ordered to operate weapons, will climb onto periscopes on their own. They don't shoot when they take over these guns in idle anyways, and prevents other characters that were ordered to operate guns from getting on the periscope to shoot the hostiles outside.

I have 3 securities on my sub, and I always have to make sure the periscopes are manned by the right officers because I have one that is dedicated to dealing with intruders that get on the sub. He would always run up to a scope first thing at the start of the round preventing the correct officers from getting on.

**Version**
0.9.9.1

**Comment by itchyOwl** [comment]
The security officers shouldn't operate turrets autonomously anymore in the latest unstable (0.9.1000.0). Closing.

**Comment by Kaillera** [comment]
Officers don't climb on guns any more. Probably for the best.

**Comment by Rokvach** [comment]
Closing
