### ISSUE TITLE
Save Bricked - An item with the same key has already been added. Key: 65535

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2804]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just finished a level. Started a new level. Parked my shuttle in a new spot. Replaced oxygen tanks on my crew members and ended the round. Starting the next round my save bricked and I cannot progress anymore. I was trying to end-round scum to colonize outposts to where I am.
![Capture](https://user-images.githubusercontent.com/5086682/81563862-deab4380-9364-11ea-9251-360e9985ae3f.PNG)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/4609654/Save.zip)

**Version**
0.9.9.1

**Comment by Kaillera** [comment]
Turns out #2769 is one of the cause of this. Thanks to Jlobblet's save decompressor/compressor, I was able to unbrick the save for the time being.

**Comment by Kaillera** [comment]
Nevermind it came back shortly after a few end rounds.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b446fac10b59e076bb06d9e4b2ceb565e9a975af

**Comment by Kaillera** [comment]
Bricked save was able to load.
