### ISSUE TITLE
Spawnsub command not working

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2808]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Im not being able to use the "spawnsub" command, i always get a kinda object not set to reference or something. At first i thought i was putting the name incorrectly but it seems to not be the problem,

**Version**
Stable Windows 10 (Windows/Linux/Mac).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9974a49ed497d1d1b006f777279fcdda464893d7

**Comment by Rokvach** [comment]
Couldn't find any issues, closing.
