### ISSUE TITLE
Azimuth uses tutorial junction boxes?

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2810]
Azimuth uses the tutorial junction boxes which lack any of the pins that the normal junctions have for signal transfer.
Is this intentional? Missing pins kind of nerfs the Azimuth even more than not having fabricators does.

**Comment by Regalis11** [comment]
This was an oversight that we've since fixed in the dev repo

**Comment by Rokvach** [comment]
Already fixed, no issues. closing.
