### ISSUE TITLE
[Workaround found] Turrets show weird behavior when overrided

### ISSUE THREAD

**Issue by Ant1V1RU5** [Regalis11/Barotrauma#2811]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Coilguns, Railguns and Searchlight will automatically keep the editor's default position when overrided in their respective .xml files.

This prevent the proper use of modded and vanilla submarines with the mod, since players should edit the ship again everytime they launch the mod.

**Steps To Reproduce**

**Step 1:** Make a mod using a modified coilgun.xml (or railgun.xml) and override it.

**Step 2:** Upload you mod

**Step 3:** Launch any game with any submarines

**Version**
Barotrauma stable version 0.9.9.1 / Windows 10 updated

**Comment by Regalis11** [comment]
Related: #2355

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/30dc3882673fe4016409c85a5eef490be3198c3a

**Comment by Ant1V1RU5** [comment]
As suggested by Udrakan, removing the <Items> and </Items> parents tag then Overriding it properly (as usual) fix that issue completly. Turrets keep their saved position !

**Comment by Udrakan** [comment]
Removing the <Items> </Items> tag fixes this. Exactly same situation is with signalitems here: https://github.com/Regalis11/Barotrauma/issues/2355. Signalitems modding is absolutely fine when I remove the <Items></Items>.

**Comment by Rokvach** [comment]
Confirmed working, closing
