### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Niuimi** [Regalis11/Barotrauma#2812]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In label option "label.letwaterdrain" 
traditional chinese translation should be "離開前將水排乾"(Drain the water before exiting).

btw the current one is 離開前將水排幹"(Drain the Sh*t out of the water before exiting).

**Steps To Reproduce**
N/A

**Version**
Windows 7.  0.9.9.1

**Additional information**
N/A

**Comment by Regalis11** [comment]
Thank you for the report! I forwarded this to the translators, waiting for the new batch of localized texts.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/235690e, fix coming up in the next patch
