### ISSUE TITLE
Cargo mission with the Volatile Compound N is nearly impossible to complete

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2814]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "Explosive Cargo" mission that includes a block of Volatile Compound N requires 100% of the cargo to be delivered to be completed, which is practically impossible to do because there's not enough time to make it to the destination before the Volatile Compound N spontaneously explodes.

**Version**
Any

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d3eef6daf68351200e821ea7b0571252e87cbca, delivering the volatile compound n is no longer required

**Comment by thegrb93** [comment]
So you can just throw it out the airlock and complete the mission?

**Comment by Regalis11** [comment]
Yeah, that was the intention.

**Comment by Kaillera** [comment]
[0.9.1001.0] Was able to chuck out volatile compound n at the station and still completed the mission.

**Comment by Rokvach** [comment]
Closing
