### ISSUE TITLE
Welding tools no longer repair doors properly

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2815]
Specifically, welding a partially damaged door will not repair it anymore but immediately begin to fill up its stuck meter. If a door is completely broken, attempting to weld it will play the door broken sound every frame (with brief pauses when the game is all out of audio streams i think). Wrenches still work for repairing.
Plasma cutting the stuck door still unsticks it though.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4f8ba2c712505598140231d8fb461ed094b4487

**Comment by Rokvach** [comment]
Welding tool shouldn't repair doors, this will be changed so only a wrench will be able to repair doors. Closing.
