### ISSUE TITLE
[0.9.10.0] Wifi Components from ~0.9.9.1 Submarines had their Wires moved from Signal_Out to Set_Channel

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2816]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Any submarines/shuttles that uses Wifi Components in 0.9.9.1 and earlier had their wires went from Signal_Out to the new Set_Channel pin.

**Steps To Reproduce**
Load a remote control submarine using Wifi Components from 0.9.9.1 or earlier.

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16146a7805995fb5db7332f4533338d8f9d858cf

**Comment by Kaillera** [comment]
Subs and Saves that were made in 0.9.1000.0 had their wires changed from Signal_Out to Set_Channel. Otherwise working for versions earlier than that.

**Comment by Rokvach** [comment]
Closing.
