### ISSUE TITLE
[0.9.10.0] Saving a submarine that was opened from the /Downloaded/ folder saves it into /Submarines/ folder instead.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2817]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Saving a submarine that was opened from the /Downloaded/ folder saves it into /Submarines/ folder instead.

**Version**
0.9.10.0

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/379817aa5734c3e35616fe8fe9681988480fe2f1

**Comment by Rokvach** [comment]
No issues, closing.
