### ISSUE TITLE
[0.9.10.0] Bots forgotten how to take tools out of their toolbox to handle tasks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2818]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots forgotten how to take tools out of their toolbox to handle tasks. I had a fresh Mechanic struggling to fix a leak, but my engineer who was free found a welding tool and fixed the leak instead. The engineer struggles to repair things because his wrench and screwdrivers are left in the toolbox.

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
Could not reproduce

**Comment by Kaillera** [comment]
Hmm I can't repro the wrench screwdriver anymore either

**Comment by Kaillera** [comment]
[0.9.1001.0] Haven't had any issues since.

**Comment by Rokvach** [comment]
Closing
