### ISSUE TITLE
[0.9.10.0] Items doesn't regain deterioration immunity after it expires first time

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2819]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items are constantly breaking down because there is no longer an immunity timer after repair after the first immunity timer expires.

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
I wasn't able to reproduce this. Does it happen with some specific device(s) or in some specific submarine? This would happen if the item's DeterioriationDelay values have been set to 0, but they seem to be non-zero in all vanilla subs and behaving as expected.

As a not for testing: you can see the deterioration delay and state by enabling debugdraw and highlighting the item.

**Comment by Regalis11** [comment]
Nvm, found a way to repro this now. It happened if you started repairing the item before it's condition has dropped below the AI repair threshold. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/473b236e3a5d86bfbdf4e43a2b498d71487442fb

**Comment by Kaillera** [comment]
Bots are also fixing items before it reaches a lower threshold, so they're constantly cutting/burning themselves on 99% items.

**Comment by Kaillera** [comment]
Seems to be working, but players are being annoyed that they're allowed to repair the items, but gains no EXP until the items shows a repair icon.

**Comment by Rokvach** [comment]
Closing.
