### ISSUE TITLE
[0.9.10.0] Camera  vigorously vibrates when submarine hugging flat surfaces that ain't below

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2820]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Submarine vigorously vibrates when hugging flat surfaces that ain't below to anchor the sub, generally for excursions.

**Version**
0.9.10.0

**Comment by thegrb93** [comment]
I've noticed this in previous versions as well with iceburgs.

**Comment by thegrb93** [comment]
It probably depends on what sub was used, so you might want to provide that info.

**Comment by Kaillera** [comment]
My sub Corsair. Only seen it happen in this build for it.

**Comment by Regalis11** [comment]
Tested this in a bunch of places with Corsair, but couldn't find a way to get it to happen.
![4567fshfthth](https://user-images.githubusercontent.com/14351070/81923484-6d7ac300-95e6-11ea-8e9d-480a752305fd.png)

**Comment by Kaillera** [comment]
Try it in multiplayer. We had it happen just by grinding against the map ceiling (not the path ceiling) and ruin walls

**Comment by Regalis11** [comment]
I had a feeling it could be related to the positional syncing of the sub, so I did all of the tests above in multiplayer. I only tested normal level walls though, will give it another go with ruins and the ceiling!

**Comment by Regalis11** [comment]
No dice unfortunately, couldn't get it to happen with ruins or the ceiling either. Do you remember if there were any floating ice chunks around? How exactly was it vibrating, was it the camera shake effect you get when the sub hits something, or the whole submarine moving around?

**Comment by Kaillera** [comment]
There was no floating ice chunks. The camera was just shaking consistently. Not sure if it was shaking the submarine too.

**Comment by Regalis11** [comment]
No known steps to repro and no other reports/sightings of this, closing
