### ISSUE TITLE
[0.9.10.0] Bought Toolboxes are not stuffed into a crate (MP: Additional Cargo as well)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2821]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bought Toolboxes are not stuffed into a crate. In Multiplayer, Additional Cargo is the same.

**Steps To Reproduce**
Buy Toolboxes

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5b5aa69e50af358f1a347a01fc9414732b2eb549

**Comment by Kaillera** [comment]
[0.9.1001.0] Toolboxes are now purchased into crates.

**Comment by Rokvach** [comment]
Closing
