### ISSUE TITLE
When shooting a alien latched onto sub, it's limbs spread all apart and slingshots submarine 80+ km/h

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2822]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When shooting a alien latched onto sub, it's limbs spread all apart and slingshots submarine 80+ km/h.

Seem to usually happen with Harpoons?

![Capture](https://user-images.githubusercontent.com/5086682/81868385-449ff280-9540-11ea-8453-5aa655a1b32d.PNG)

**Version**
0.9.9.1
0.9.10.0

**Comment by Regalis11** [comment]
That seems to be a mudraptor, which can't latch onto subs, so I don't think it's related to the latching.

**Comment by itchyOwl** [comment]
Actually they do latch on the latest unstable, by a mistake. I'll change that now.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/49ff57fa77d9b0dbcb22e2336af52d72b184f0c6 and https://github.com/Regalis11/Barotrauma-development/commit/df97e7874a5ff9916b693fc1a2ab6808fe934b0c

**Comment by Rokvach** [comment]
Mudraptors doesn't latch on to the submarine anymore and I haven't noticed this happening while shooting them in a while now (Since the colliders were removed way back). The added ways to prevent this hasn't caused any additional issues either. Closing.
