### ISSUE TITLE
[0.9.10.0] Effects of psychosis do not disappear when switching crew members

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2824]
Self explanatory. In a singleplayer campaign, the broken items will not revert to normal when switching to someone without psychosis.

**Comment by hubismal** [comment]
Same applies to taking haloperidol

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f3cac70104a3bc3a53edb70f3f3540c2f5e51491

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
