### ISSUE TITLE
[0.9.10.0] Bots can't Shutdown Reactor

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2825]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots can't Shutdown Reactor

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
Could not reproduce

**Comment by Kaillera** [comment]
I can't get my bot to shutdown the reactor on Corsair

**Comment by Kaillera** [comment]
https://www.youtube.com/watch?v=NlGSKsQeUgw

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@24c18df

**Comment by Rokvach** [comment]
No issues, closing.
