### ISSUE TITLE
[0.9.10.0] Unable to deconstruct Oxygenite Shards for Liquid Oxygenite to make Deusizine/Oxygenite Tanks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2826]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to deconstruct Oxygenite Shards for Liquid Oxygenite to make Deusizine/Oxygenite Tanks. Sky Alien Artifacts are mostly useless now except to be shot out of railgun shells.

**Version**
0.9.10.0

**Comment by madamunkey** [comment]
In fact, Liquid Oxygenite is entirely unacquireable. Making oxygenite mostly useless with liquid oxygenite unacquireable in a normal playthrough outside of finding it on destroyed subs.

**Comment by Kaillera** [comment]
This issue comes up very often in game chat.

**Comment by danielasteljoki** [comment]
Fixed in d416cb6.

**Comment by Rokvach** [comment]
No issues, closing.
