### ISSUE TITLE
Power_Value_Out/Load_Value_Out Pin for Junction Boxes too!

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2831]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Power_Value_Out/Load_Value_Out Pin for JBs too please!

**Version**
~0.9.10.0

**Comment by Regalis11** [comment]
You mean actually splitting the power pin to an input and output like in relays, or a pin that outputs how much power the box is getting (like the new output in the reactor)?

**Comment by Kaillera** [comment]
> You mean actually splitting the power pin to an input and output like in relays, or a pin that outputs how much power the box is getting (like the new output in the reactor)?

Sorry yes, the power value out and load value out like the one on reactor this build.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
