### ISSUE TITLE
Alien Assemblies outside of Ruin or in Ruin Walls

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2832]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Had a rare sight where the trap and chest were outside the ruins.

![Capture](https://user-images.githubusercontent.com/5086682/81971252-ce0dfe00-95ee-11ea-9b64-b652c2b041e9.PNG)

**Version**
0.9.10.0

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/82204694-5a603f80-98d3-11ea-9e09-ba972272e6df.PNG)

Having to cut these floors pretty often to get the chest now.

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/82700828-fa53fb00-9c3c-11ea-8275-abee7bfb7bb7.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6bbc1beb2fad14e9f0d291db4019e9c345673ad5

Can be tested pretty easily in the level editor: these seemed to happen so frequently that it only took a couple of tries to find a seed with these issues.
