### ISSUE TITLE
Strange error on picking up logbook, mission mysteriously failed

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2833]
[consoleOutput.txt](https://github.com/Regalis11/Barotrauma/files/4630421/consoleOutput.txt)
Got this error when I attempted to pick up a logbook from a wreck with an already full inventory.
When I arrived at the outpost it said that the mission was failed.

**Comment by Regalis11** [comment]
Is that the file you meant to upload? I don't see any errors in that log

**Comment by hubismal** [comment]
guess dumptofile didn't work as intended. which is weird because the timestamp matched up to when i used it.
maybe this can help? sorry i don't have the error output anymore obviously
![2020-05-14-141644_446x179_scrot](https://user-images.githubusercontent.com/47284081/82072602-97db8780-969d-11ea-85e5-001161ea570d.png)
took a screenshot before i remembered i could use dumptofile.

**Comment by Regalis11** [comment]
Possibly related to https://github.com/Regalis11/Barotrauma-development/commit/7c921f2a96c1853ef96817c8ab16dbcbd0571833

**Comment by Regalis11** [comment]
Also seems to be the same issue as #2727
