### ISSUE TITLE
Monsters ignore Decoys when latched on to the Submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2835]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Aliens aren't interested in Depth Decoys when they're already right next to Submarine.

![Capture](https://user-images.githubusercontent.com/5086682/81979897-b5581500-95fb-11ea-9fb0-7f2960c3a495.PNG)

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
I think in this case it's caused by the mudraptor being latched on to the sub. Couldn't find another way to reproduced.

**Comment by Kaillera** [comment]
Crawlers was behaving the same. Should latching ignore decoys entirely?

**Comment by itchyOwl** [comment]
No, I'll look into it later.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@becbdb8.

**Comment by Rokvach** [comment]
Tested, latched on crawlers wont even try to target the decoy.

Repro steps:
- Pick Typhon
- Spawn 4 crawlers at the bottom of the sub near where the decoy drops
- Wait until some of them latches on
- Drop the decoy and see that only the crawlers which aren't latched on starts to target it

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@1b46766 (the original fix wasn't sufficient).

**Comment by Rokvach** [comment]
No issues, closing.
