### ISSUE TITLE
Wrecks can block the path in some cases -> fix the logic

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2836]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Well to be fair, this one is really tight.
![Capture](https://user-images.githubusercontent.com/5086682/81980204-2bf51280-95fc-11ea-8c19-72fb141bbe55.PNG)

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
Not sure if we should do anything about this, I think it's fine if the autopilot won't try to squeeze through gaps this tight and leaves it to the player.

**Comment by Rokvach** [comment]
With the new level generation there are also times when the submarine can't get past the wrecks so some parameters would need to be adjusted in order to commodate the new level generation @Regalis11

**Comment by itchyOwl** [comment]
There are cases where the wreck placement logic fails, like this:
https://steamcommunity.com/app/602960/discussions/1/2266943550321348255/

I think this case is related to that, because if the wreck wasn't allowed to place that close to the wall on the left, there would be more space there.

**Comment by itchyOwl** [comment]
https://steamcommunity.com/app/602960/discussions/1/4224884861038816051/

**Comment by itchyOwl** [comment]
Added some horizontal padding in Regalis11/Barotrauma-development@f3348fb. Let's see if it's enough.

**Comment by Rokvach** [comment]
I haven't noticed any too tight spots anymore, also we haven't gotten any reports from testers either of this happening. Closing.
