### ISSUE TITLE
Lidgren Dedicated/SteamP2P - Some players cannot connect to/find server, others can. Switching server type reverses those that can...?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2840]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There's a strange thing with Lidgren Dedicated and SteamP2P servers. I have some players that can see and connect to my SteamP2P, but some of them can't. On the other hand, when I host Lidgren Dedicated, the players that can't are now able to, but the ones that could join SteamP2P now can't join Lidgren Dedicated. Then there are some players that aren't affected by either. This has been going on since 0.9.7.0, and was happening in 0.9.10.0 today.

**Version**
0.9.10.0

**Additional information**
My ports 27015~27016 are opened. upnp is enabled.

I'm in Canada - Ontario - Toronto. I had a player from Canada - Quebec - Montreal unable to connect to my Lidgren Dedicated, but was able to through SteamP2P. I had someone from Italy unable to join my SteamP2P, but was able to through Lidgren Dedicated.

Edit: Montreal guy's computer was Mac OSX. States that he can't join any Dedicated actually.

Edit 2: Those that are unable to find my server when I host dedicated are able to connect to it when they join the game by another player that is in my server from their friend list, minus the host.

**Comment by Rokvach** [comment]
There's been some improvements on this, for example the recent steam query fixes where it couldn't fetch more than 50 p2p servers

**Comment by ryanalexmartin** [comment]
I still have the same issue, perhaps this should be re-opened
