### ISSUE TITLE
[0.9.10.0] Sub Editor - Able to hit Crush Depth in Test Level

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2841]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So after about 10+ minutes of letting my sub drift sinking, my sub suddenly imploded by crush depth in the test level!

![Capture](https://user-images.githubusercontent.com/5086682/82045659-75397680-967d-11ea-94c3-49a4d22b5f6b.PNG)

**Version**
0.9.10.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/415349f7d789122a94bb34ae4812229fec813801

**Comment by Rokvach** [comment]
No issues, closing.
