### ISSUE TITLE
Can't save item assemblies

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#2846]
[0.9.10.0]unstable. When you create a drawing (assembly), the console opens with an error.

**Comment by NicolaruS** [comment]
Even from one detail.

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/82125131-22a6aa00-97a4-11ea-9889-c30f8208c19e.png)
 I got this error when trying to save an assembly.

**Comment by Udrakan** [comment]
STR:
-go to sumbarine editor
-place anything
-try to save it as assembly
-error should popup and the assembly doesn't save

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c8b711290acdb8510fc3a7fd294eec4bfddf345

**Comment by Rokvach** [comment]
Couldn't reproduce, working correctly. Closing.
