### ISSUE TITLE
Overrided projectile weaponry play a firing sound only for the user.

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#2847]
_Issue related to ticket #2355_

**Description**
Grenade launcher / Syringue gun / Harpoon gun and Stun gun - when overrided in the weapon.xml - does not play any sound for other players. Only the shooter will hear the firing sound.

**Steps To Reproduce**

**Requirement :** 2 players

**Step 1 :** Override a projectile weapon (for instance the Harpoon gun) in a mod

**Step 2 :** Activate your mod

**Step 3 :** The shooter will fire the weapon while the other player will hear nothing.

**Version**
Barotrauma release 0.9.9.1 - Windows 10 updated

**Additional information**
Projectile hitsound (when impacting a wall or creature) are unaffected and are working properly.

**Comment by Regalis11** [comment]
Possibly caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/2388, moving to testing

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
