### ISSUE TITLE
[0.9.1001.0] Reactor - Wires on Meltdown_Warning was shifted to Set_Fission

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2848]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wires on Meltdown_Warning was shifted to Set_Fission on the reactor from 0.9.9.1 to 0.9.1000.0 and 0.9.1001.0.

**Version**
~0.9.1001.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea152739261a704e585e1662c30d70e14efe53ba

**Comment by Rokvach** [comment]
No issues, closing.
