### ISSUE TITLE
[0.9.1001.0] Radar on terminal destroys FPS when target blips exists.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2849]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Radar on terminal destroys FPS when target blips exists.

**Version**
0.9.1001.0

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/91f666c4e04657908870d9a85d8f427a7152894f

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue, working correctly. Closing.
