### ISSUE TITLE
Sub Editor - When Wiring components, wires doesn't start from the origin of the components. Also no way to move node points by pixels.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2852]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Wiring components, wires doesn't start from the origin of the components. Also no way to move node points by pixels.

![Capture](https://user-images.githubusercontent.com/5086682/82152763-7b705400-9831-11ea-8a2e-4523a1df0494.PNG)

Having to readjust the wires every time is annoying.

**Version**
<0.9.1001.0

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/fdc23688bca3b8209a71349c20cf211ca4291461

Steps to repro: 
1. Move the components so that they're not aligned with the grid (for example 5 pixels in any direction)
2. Connect a wire

**Comment by Rokvach** [comment]
Wasn't able to reproduce, working correctly. Closing.
