### ISSUE TITLE
Bots don't gain Helm because AutoPilot doesn't give EXP.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2853]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots don't gain Helm because AutoPilot doesn't give EXP when they Navigate. I am unable to train crew members to level up Helm until I need it (For when I lose my Captain for instance).

**Version**
<0.9.1001.0

**Comment by Kaillera** [comment]
Or well players that like to pilot with Maintain Position doesn't get EXP either.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f3a6cbf30630d7dfbcd30bffb8469120b6cf9ef1

**Comment by Rokvach** [comment]
Maintain position doesn't give any XP to the player, which I believe is intentionally left out. Otherwise works correctly. Closing.
