### ISSUE TITLE
Railgun Shells/Physicorium Shells are terrible against Bone Threshers / Molochs

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2857]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The reduction modifier zones for Bone Threshers and Molochs makes Shells shot out of Railguns tend to do miniscule damage to them most of the time unless aimed very precisely (The underside of Bone Thresher, or the Sack on the Moloch).

**Version**
<0.9.1001.0

**Comment by itchyOwl** [comment]
This ticket is probably out of date, due to the fixes in explosion and railgun shell damages. Moving to the QA.

**Comment by Rokvach** [comment]
Not a issue anymore, closing.
