### ISSUE TITLE
[0.9.1001.0] Bots don't gain EXP when healing others

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2858]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots don't gain EXP when healing others. My current medic has had level 48 Medical since the start of the campaign.

**Version**
0.9.1001.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bbbeee98724b016aec3a90ca29de515df682a506

**Comment by Rokvach** [comment]
No issues, closing.
