### ISSUE TITLE
Вылетела игра при попытке выдать права Игроку. / The game took off when trying to grant the right to the Player.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#286]
Я выдал права Игроку и игра вылетела. Не знаю, связано ли это с модом или нет. Пытался выдать новый пресет, который сам создал.

I gave the rights to the Player and the game took off. I do not know whether it is connected with fashion or not. Tried to give out a new preset, which he created.

============================================
Barotrauma Client crash report (generated on 25.02.2018 23:18:55)

Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.

Game version 0.8.0.4 NILMOD SERVER MODIFICATION
Graphics mode: 1280x720 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: dOqogKHO
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
Server (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce 940MX
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,777778}
    GPU status: Normal

This was running NilMod Code!

Exception: Ссылка на объект не указывает на экземпляр объекта.
Target site: Boolean SelectPlayer(Barotrauma.GUIComponent, System.Object)
Stack trace: 
   в Barotrauma.NetLobbyScreen.SelectPlayer(GUIComponent component, Object obj) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Screens\NetLobbyScreen.cs:строка 1196
   в Barotrauma.NetLobbyScreen.<SelectPlayer>b__100_3(GUIComponent c, Object userdata) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Screens\NetLobbyScreen.cs:строка 1242
   в Barotrauma.GUIDropDown.SelectItem(GUIComponent component, Object obj) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GUI\GUIDropDown.cs:строка 147
   в Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GUI\GUIListBox.cs:строка 322
   в Barotrauma.GUIListBox.UpdateChildrenRect(Single deltaTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GUI\GUIListBox.cs:строка 254
   в Barotrauma.GUIListBox.Update(Single deltaTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GUI\GUIListBox.cs:строка 310
   в Barotrauma.GUIDropDown.Update(Single deltaTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GUI\GUIDropDown.cs:строка 218
   в Barotrauma.GUIComponent.Update(Single deltaTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GUI\GUIComponent.cs:строка 475
   в Barotrauma.GUIComponent.Update(Single deltaTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GUI\GUIComponent.cs:строка 475
   в Barotrauma.NetLobbyScreen.Update(Double deltaTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Screens\NetLobbyScreen.cs:строка 1436
   в Barotrauma.GameMain.Update(GameTime gameTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GameMain.cs:строка 471
   в Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   в Microsoft.Xna.Framework.Game.Tick()
   в MonoGame.Framework.WinFormsGameWindow.RunLoop()
   в MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   в Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   в Barotrauma.Program.Main() в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Program.cs:строка 47

Last debug messages:
   [25.02.2018 23:17:50] New Player Никита (195.91.243.97) has joined.
   [25.02.2018 23:15:31] RandomRands (85.76.82.75) has joined.
   [25.02.2018 23:15:27] New Player Winland (88.195.39.103) has joined.
   [25.02.2018 23:14:58] New Player 1 (85.76.82.75) has joined.
   [25.02.2018 23:12:37] fixitems
   [25.02.2018 23:10:56] New Player Alokin (95.55.61.141) has joined.
   [25.02.2018 23:09:25] RandomRands (85.76.82.75) couldn't join the server (wrong game version) - CLVersion: 0.8.0.1 vs servers 0.8.0.4
   [25.02.2018 23:05:37] New Player Sgt John Brown (62.122.128.68) has joined.
   [25.02.2018 23:05:27] New Player suave (74.98.184.77) has joined.
   [25.02.2018 23:05:21] Line of sight effect disabled
   [25.02.2018 23:05:21] lOS
   [25.02.2018 23:04:49] Barotrauma.Submarine (Aegir Mark III) Voted by: Marllo Rigitini
   [25.02.2018 23:04:19] New Player Marllo Rigitini (128.82.19.221) has joined.
   [25.02.2018 23:01:07] Enter "help" for a list of available console commands

**Comment by CryIz** [comment]
By the way, and the rights of the Player still stood out.

**Comment by NilanthAnimosus** [comment]
My line numbers do not match the source, I don't feel this is too helpful without stating I have heavily modified these files such as adding host names, team selection GUI to the player list and such.

line number 1196 corresponds to a section of code in my modification that is not in vanilla Barotrauma where I return on SelectPlayer() because there are button children to select a players preferred team (Coalition/Regenades/Random) so I needed to block that function. not sure why its bugged out but this can be closed.
