### ISSUE TITLE
[0.9.1001.0] Psychosis Broken Device State does not recover when affliction is gone

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2860]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Psychosis Broken Device State does not recover when affliction is gone

**Version**
0.9.1001.0

**Comment by Regalis11** [comment]
Duplicate of #2824

**Comment by Regalis11** [comment]
Nvm, not a duplicate, although I thought I already fixed this in https://github.com/Regalis11/Barotrauma-development/commit/f3cac70104a3bc3a53edb70f3f3540c2f5e51491. Will take another look

**Comment by Regalis11** [comment]
Attempt 2: https://github.com/Regalis11/Barotrauma-development/commit/78a348b2c8bf3ffd0e02a1d7d3c5f27dbbe452e6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
