### ISSUE TITLE
[0.9.1001.0] Alien Pistol Inventory Icon stuck in "Cooldown State"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2861]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alien Pistol Inventory Icon stuck in "Cooldown State" after firing. Not sure when it happened, but it's ongoing.

![Capture](https://user-images.githubusercontent.com/5086682/82243284-4e916f00-990d-11ea-9d54-8dc61fcab2d8.PNG)

**Version**
0.9.1001.0

**Comment by Regalis11** [comment]
Probably related: 2611

**Comment by Kaillera** [comment]
Since this is singleplayer it doesn't behave the same way as #2611.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dadb7081b0b055c60cc8414db5ee226e46ef87cf

**Comment by Rokvach** [comment]
Confirmed working correctly, closing.
