### ISSUE TITLE
[0.9.1001.0] Damaged Small pumps are smoking before they require repair

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2863]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Damaged Small pumps (legacy) are smoking before they require repair. The smoke is annoying.

**Version**
0.9.1001.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c544a8a474eca38f47ca721294e01da1fe620919

**Comment by Rokvach** [comment]
Didn't notice any issues with this while doing bot repairing tests, closing.
