### ISSUE TITLE
Adjustable Motion Detector's Offset during round.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2864]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I would like to request for Motion Detector's Offset to be adjustable during rounds. I would like to be able to install logics that only triggers from external means.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/0c1ff15e8eb44ede7a565895b4323379e65dd388

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
