### ISSUE TITLE
Unable to rewire hatches/doors/ports when you're outside the submarine when the origin is behind the hull

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2866]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to rewire hatches/doors/ports when you're outside the submarine when the origin is behind the hull.

Can't rewire:
![Capture](https://user-images.githubusercontent.com/5086682/82386101-b1fcc900-9a01-11ea-8688-8cdc455d66db.PNG)

Can Rewire:
![Capture](https://user-images.githubusercontent.com/5086682/82386220-dbb5f000-9a01-11ea-8e47-04f32e2dd528.PNG)

Sometimes I'm trying to rewire a dysfunctional hatch/doors/ports when someone messed with it, but it's not possible from the outside

**Version**
<0.9.1001.0

**Comment by Ek-Videogames** [comment]
**+ In addition, this can cause hatches to be unopenable from the outside on certain submarine designs**

**Comment by Rokvach** [comment]
Is this still an issue?

**Comment by Kaillera** [comment]
Yep still an issue to date.

**Comment by Rokvach** [comment]
Moving back to full release backlog

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6b763a7d8ead7992a8ba31562a90f91c9b23c93

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
