### ISSUE TITLE
Bots with Diving Knives prioritizes defending itself against aliens with Welding Tool

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2868]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I still think this is silly. So the bot had a empty SMG, got chomped by an alien, Instead of using the diving knife it has, went to collect a welding tool to weld it to death (not a good idea). I would've fought to the death with a knife.

![Capture](https://user-images.githubusercontent.com/5086682/82387459-18371b00-9a05-11ea-834f-c245f2730b7a.PNG)

**Version**
0.9.1001.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/cdb0682

**Comment by itchyOwl** [comment]
Already fixed in Regalis11/Barotrauma-development@cdb0682. Combat priorities were not changed after nerfing the repair tools.

**Comment by Rokvach** [comment]
No issues, closing.
