### ISSUE TITLE
SpawnItem не работает. / SpawnItem does not work.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#287]
![image](https://user-images.githubusercontent.com/33912761/36646070-8a6d57d8-1a83-11e8-98dd-49be5fb2fd6c.png)

**Comment by Regalis11** [comment]
![56783457](https://user-images.githubusercontent.com/14351070/36646118-e3797116-1a7b-11e8-9884-cafd86570706.png)
Couldn't reproduce the issue, perhaps it's caused by the server mod you're using?

**Comment by CryIz** [comment]
I'm sorry, I guess it's a fashion mistake I'm using.

**Comment by NilanthAnimosus** [comment]
I fixed this issue (At least for inventory, I probably should have checked inside and such too) and edited the thread on the forums for my mod and download link about two hours before this was reported on git.

Perhaps some form of template/rules for the github issues would be nice for giving details such as if a modification is used, I'm still busy sorting out the issues from having so many changes occur from 0.7.0.1 to 0.8.0.0+.

It perhaps does not help the forums do not show date edited, only when there is a new post which makes it hard to notice when I patch these.
