### ISSUE TITLE
Wearables with light-components become editable when a custom-interface component is added.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2871]
**v0.9.9.1 - v0.9.1000.0**

### Issue:
Wearables (In this case diving suits) with LightComponents that are normally not editable in-game suddenly appear editable on the GUI when the item also contains a CustomInterface.

This occurs when said uniform or diving suit is picked up off the ground.

**Additional info:**

Same issue occurs using the vanilla diving suit as base, simply adding a custominterface

[overwrite_suit.txt](https://github.com/Regalis11/Barotrauma/files/4658429/overwrite_suit.txt)

![customui_lightbug](https://user-images.githubusercontent.com/55356135/82477724-db6b3280-9a9d-11ea-84b0-43009c982d04.PNG)

**Comment by hubismal** [comment]
have you tried adding 
`allowingameediting="false"`
into the lightcomponent? that's what is required for other items with GUIs that use lightcomponents.

**Comment by Ek-Videogames** [comment]
As is already set, canbeselected="false" AllowInGameEditing="false" does nothing

**Comment by hubismal** [comment]
Strange because this does not occur on my enforcer helmet in my mod despite seeming to be the same kind of item that yours is (a wearable with a colored lightcomponent and a custom interface to toggle it on/off).

**Comment by Ek-Videogames** [comment]
I believe this is most likely because the enforcer helmet is a Pickable 'Any' and goes in the head slot rather than the uniform & suit slot.

**Comment by Ek-Videogames** [comment]
I believe this is most likely because the enforcer helmet is a Pickable 'Any' and goes in the head slot rather than the uniform & suit slot.

- I assume it would work fine if you were to talk the vanilla flashlight and equip it in the head slot aswell

**Comment by Regalis11** [comment]
Adding `AllowInGameEditing="false"` seems to fix the issue.
