### ISSUE TITLE
Windowed Mode - Mouse stuff annoyance

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2873]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I'm not sure if I'm the only one that is annoyed by these few things regarding the mouse when you're playing the game in Windowed mode:

1. When you move the mouse off the game's screen, another mouse shows up in the game mirroring the movement of your mouse. Sometimes I confuse these thinking my mouse is still in the game.

2. When Barotrauma isn't the active window and you move the mouse back into the game. you can't see where the mouse is until you click into the game.

3. When you click on Barotrauma from unactive window to active window, the mouse click is sent into the game as well. That left click may toggle something. Right clicking into the window will immediately cancel interaction with items.

**Version**
<0.9.1001.0

**Comment by cshingle** [comment]
I always play games in borderless windowed mode because I have multiple screens. These are all OS related issues that exist for every game. It is unlikely the developer can do anything about any of these items.
I suggest closing this issue as not much can be done to resolve it.
