### ISSUE TITLE
Singleplayer - When docking shuttle to shuttle to station and leaving Main Sub behind, you lose the second shuttle next round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2874]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Singleplayer - When docking shuttle to shuttle to station and leaving Main Sub behind, you lose the second shuttle next round

**Version**
<0.9.1001.0

**Comment by Rokvach** [comment]
There's been quite a bit of changes in this area

**Comment by Kaillera** [comment]
New issues from the new changes described in #4610
