### ISSUE TITLE
[0.9.10.0 Release Candidate 1] Reactor Missing SET_FISSION & SET_TURBINE pins

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2875]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reactor Missing SET_FISSION & SET_TURBINE pins

**Version**
0.9.10.0 Release Canidate 1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd3079f80f213bf88816aad1c8933e09f9902349

**Comment by Rokvach** [comment]
No issues, closing.
