### ISSUE TITLE
[0.9.10.0 RC1] Multiplayer? - Main Docking Port had solid hull above when undocked and hatch was closed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2879]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In multiplayer I forced opened the main docking port hatch with wire to open from the inside, and then closed it on my way out with wiring too. When I came back to get ready to force it open with wiring again from the outside, I wasn't able to get close to the docking port hatch. The hull that the docking port created was creating a solid barrier right above it.

**Version**
0.9.10.0 RC1

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce this. What exactly do you mean by opening the hatch with a wire? What did you connect the other end of the wire to? And what do you mean by "the hull that the docking port created"?

**Comment by Kaillera** [comment]
So I opened the hatch on the docking port using a wire to set or toggle state it. Closed the hatch on my way out. In this example I used the delay component wire that was on set state, moved it to toggle state, and then unplug the wire when the state is opened.

You know the hull that is created for the docking ports when they are docked right? For some reason that hull existed ontop of the port despite not being docked when you force your way out of the docking hatch from the inside.

As for the last part, if that hull didn't existed, I would've been able to interacted with the hatch and wire myself in again.

**Comment by Kaillera** [comment]
I don't know if this problem still exist or not though. I haven't forced open top docking hatch lately.

**Comment by Kaillera** [comment]
Haven't seen this happened in 0.10.x

**Comment by Regalis11** [comment]
I guess we could close this, might've been unintentionally fixed as a side-effect of some other change.
