### ISSUE TITLE
Wreck Salvage Mission - Logbook could be placed in a non-interactable "locker"?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2880]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Had a concern for the Wreck Competition the community is hosting. Is it possible that Wreck Salvage mission can place mission Logbook into non-interactable lockers? Some contestant might use non-interactable ones for aesthetic.

**Version**
<0.9.10.0 RC1

**Comment by juanjp600** [comment]
It would appear that it was possible, this should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/dba3a512ed7446c6ed6a731cccae58d8e3e9d4df

**Comment by Rokvach** [comment]
Tested using the steps above, working correctly. Closing.
