### ISSUE TITLE
[0.9.10.0 RC1] Multiplayer - Invalid order message - Order index out of bound

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2882]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Came back from getting desynced in multiplayer. Gave bots order. Tried to cancel order. This ended up spamming the dedicated server console. Order wouldn't cancel from the bot.

![Capture](https://user-images.githubusercontent.com/5086682/82719205-8c2c2a00-9c76-11ea-8201-ae53fb78b357.PNG)

**Version**
0.9.10.0 RC1

**Comment by Regalis11** [comment]
Potentially fixed alongside #3680.

Moving to QA backlog, let's see if we run into this again.

**Comment by Rokvach** [comment]
There hasn't been any sightings of this issue since the fix, quite safe to say that its been fixed. Closing.
