### ISSUE TITLE
[0.9.10.0 Release] [Linux+Mac] lightsource for molochblack filepath uncapitalized

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2883]
This results in an extremely annoying error whenever the black moloch spawns in Linux and Mac, where capitalization matters.
Specifically on line 25 of Content/Characters/Molochblack/Ragdolls/Molochblackdefaultragdoll.xml
```xml
<lightsource color="255,255,255,0" range="150">
      <deformablesprite texture="Content/Characters/Molochblack/molochblack.png" sourcerect="864,384,864,832" origin="0.48274615,0.40562853" size="1,1" alpha="1" />
    </lightsource>
```
The filepath here should be `Content/Characters/Molochblack/Molochblack.png` instead of what's used above.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e9a11912710d3e730496c105c99da33921ae3878

**Comment by Rokvach** [comment]
No issues, closing.
