### ISSUE TITLE
Hidden/Non-interactible steel cabinets in Multiplayer

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#2884]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In multiplayer, linked steel cabinets that are hidden/non interactable cannot be used. When linked to a fabricator/deconstructor, items will either be stuck in the cabinet or will be ejected by the cabinet. They work fine in the sub editor tester/SP.

**Steps To Reproduce**
Link steel cabinet and select hidden/non-interactable. Load in multiplayer.

**Version**
0.9.9.1 Windows 10/Debian 10

**Additional information**
I don't know if this is intentional, especially for the "non-interactable mode", but it seems like this should at least work when "hidden" is checked.

**Comment by Regalis11** [comment]
Made non-interactable containers non-interactable in single player in 
https://github.com/Regalis11/Barotrauma-development/commit/51617c268b79ee5535e90cfde98c27032277e3c7

Made it possible to interact with hidden linked containers in https://github.com/Regalis11/Barotrauma-development/commit/51617c268b79ee5535e90cfde98c27032277e3c7

**Comment by Rokvach** [comment]
No issues, closing.
