### ISSUE TITLE
[0.9.10.0 RC1] Unable to harvest plants.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2886]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Plants have no interact prompt. Cannot harvest any plants in the level.

**Version**
0.9.10.0 RC1

**Comment by Regalis11** [comment]
Seemed to have happened as a side-effect of the fix for #2065.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fc75dbaf0cfc08b99bbb5b3f251e8a72d4067460

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
