### ISSUE TITLE
[0.9.10.0 RC1] Singleplayer - Can't get Medical EXP

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2887]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have a Medical Doctor crew in Singleplayer that is also maintaining position/navigating the Submarine for me. When I control him and heal other crew members, I was not gaining any Medical EXP.

**Steps to Reproduce**
1. Put Crew A on Maintain Position/Navigate to Destination.
2. Receive damage on Crew B.
3. Control Crew A and heal Crew B.

**Version**
0.9.10.0 RC1

**Additional Informations**
If Crew A heals as a Bot instead, he does gain EXP.

**Comment by Regalis11** [comment]
Could not reproduce, the character seems to be gaining XP the same way regardless if it's controlled by a player or a bot.

**Comment by Kaillera** [comment]
This cannot be produced at the beginning of the round. It seems to happen later in the middle of the round.

**Comment by Regalis11** [comment]
I suspect this was caused by the same bug as #3777: the server would only notify the clients about the changed skill/XP if the gained XP was above a certain threshold. This would explain why it only happened later during a round, because a high-skilled medic's level increases more slowly.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
