### ISSUE TITLE
[0.9.10.0 RC1] Welding Doors also Damages them.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2888]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Welding Doors also Damages them.

**Version**
0.9.10.0 RC1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef07a27b102e863d33d0f9e85e8bbb04760fe885

**Comment by Rokvach** [comment]
I noticed couple other oddities while testing this. @Regalis11 

- You can open a partially (or almost fully) welded door which then sets the welding process back for 10-20% from where it was at. Only when the door is fully welded it can't be opened, door can only be opened once the weld is fully gone. 

- When using a plasma cutter on a fully welded door the doors damage sprite acts as if the door is getting damage even tho only the weld is being removed. So after getting the welding off the door will look more damaged than it actually is.

**Comment by Regalis11** [comment]
Both of those are intentional, closing
