### ISSUE TITLE
Not able to put custom name to hulls.

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2889]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just cant rename the room name because it keeps auto-renaming, i think this auto rename should be a option like auto-fill.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/129e1c77cfe5d31d5c1f90913fd72b9ac155e0c2

Related: #2040

**Comment by Rokvach** [comment]
Working correctly, closing.
