### ISSUE TITLE
Dugong Thalamus Coilgun seems to have trouble aiming Humans

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2890]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was swimming around a Dugong Thalamus, and the coilgun only shot me if I was practically hugging the barrel.

**Version**
0.9.10.0 RC1

**Comment by ezjamsen** [comment]
Fixed in dev.

**Comment by Rokvach** [comment]
No issues, closing.
