### ISSUE TITLE
[0.9.10.0 RC1] Bots - Doesn't repair doors and hatches anymore

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2891]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots in 0.9.10.0 RC1 doesn't repair doors and hatches anymore. Had lots of damaged one from a Terminal Cell swarming in my sub.

**Version**
0.9.10.0 RC1

**Additional information**
Corsair in Singleplayer

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3a2eb5288e7e614c035660871948eaed85330ebc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
