### ISSUE TITLE
Items with editor-applied color & inventoryicon lose their settings between rounds if held in player inventory

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2892]
Version **- Current Stable**

Items which have had sprite color and inventory icon color settings applied in editor revert back to their prefab defaults when a new campaign round starts if the item is being held within' a character's inventory.

**Additional Information:**

I have not tested with many items, I just have noticed it has been happening to items during campaigns such as: toolboxes, harpoon guns, logic components

**Comment by Regalis11** [comment]
Duplicate of #2799
