### ISSUE TITLE
Text-displays with modified scale&text-size appear different in-game than in editor after a new campaign round starts

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2893]
Version **- Current Stable**

The apparent alignment of text displays' text changes from its position it appears in-editor and in-game once a campaign round has finished and all rounds subsequent.

**Text position in editor and in sandbox**

![image](https://user-images.githubusercontent.com/55356135/82820342-fa880c80-9e6f-11ea-80f7-3867ce74b775.png)

![image](https://user-images.githubusercontent.com/55356135/82820428-23100680-9e70-11ea-834f-534e69b691bf.png)

**incorrect text position after a campaign round**

![image](https://user-images.githubusercontent.com/55356135/82820553-6d918300-9e70-11ea-93b7-dbcb33030f38.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa79e25445ea2814b89e85629334150d7df569b4

**Comment by Rokvach** [comment]
No issues, closing.
