### ISSUE TITLE
Desync: Supercapacitors appear fully charged, yet do not allow ship's guns to fire as if empty.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2894]
**( REQUIRES ADDITIONAL TESTING )**
I figured I would throw this up if anyone has additional knowledge regarding this bug happening in multiplayer.

- Supercapacitor seemed to be broken due to deterioration

- Supercap repaired and _appeared_ to start charging to full again

- Supercap appears full on gun UI, but is unable to fire for some reason

- Interacting with the supercap and changing its charge rate suddenly caused the server to try to re-sync it possibly, because the charge suddenly shot down to 0 and started charging again, yet the gun wired to the capacitor was still not able to fire.

- This persisted until the end of the round, and upon the start of the next mission the capacitor was suddenly working fine with no further investigation needed.

**Comment by AnunnakiNibiru** [comment]
The same experience here in MP (I don't play SP). But not sure if that was problem with capacitators (tehere were 8 capacitator, and 4 coilguns, and every coilgun was connected to 2 capacitators. All capacitator were fully repaired, fully charged. Bude one coilgun was not working at all.

**Comment by Ek-Videogames** [comment]
(Possibly this means that the desync is occurring at the wire-connection level rather than the capacitor?)

**Comment by Regalis11** [comment]
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/0059175a6b264fa17ed31e59db653b52c5b45e0d

**Comment by Rokvach** [comment]
No issues, closing.
