### ISSUE TITLE
[0.9.10.0] Swimming-in-place animation is barely noticiable

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#2895]
- [✔ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a character stops to swim in place, there is supposed to be an animation, but it is barely noticiable and looks like as the character has just frozen in place.

**Steps To Reproduce**
Really easy to reproduce! Go swimming and just stop somewhere.

**Version**
Windows 10 OS

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/33e0e3b28ecba6ecbf2aa6c34c200d35a62a18e3

**Comment by Rokvach** [comment]
The movement looks a bit robotic where the leg just sometimes happens to move, so the movement isn't really constant or fluid, maybe increasing the timing would make it look a bit better @Regalis11

**Comment by Regalis11** [comment]
Sped up the leg movement in https://github.com/Regalis11/Barotrauma-development/commit/8a4502c

**Comment by Rokvach** [comment]
Looks good, closing.
