### ISSUE TITLE
[Feature Request] Contact set_range for the wifi module.

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#2896]
It'd be possible, but personally I'm not sure if that's a good idea. I see the maximum range of a wifi component as an inherent property of the item, sort of like the maximum output of a reactor or the maximum capacity of a battery. Allowing it to be modified at-will would for example make it possible to communicate with characters on a ruin expedition regardless of the distance.

_Originally posted by @Regalis11 in https://github.com/Regalis11/Barotrauma/issues/1933#issuecomment-623349025_

Can you give the contact set_range and limit the maximum range value to the "max range" parameter? Then players will be able to dynamically change the range of Wi-Fi and will not exceed the threshold set by the developers.

**Comment by Regalis11** [comment]
What you're trying to do with the wifi component is a very rare use case, and I personally don't see the need to add these to the vanilla item.

But in any case, I added the support for a "set_range" input in https://github.com/Regalis11/Barotrauma-development/commit/b2151359ea9c19958fd2b3090d61cfdbe2531a8b. Not used in vanilla items but can be used by a modded wifi component.

**Comment by NicolaruS** [comment]
Thank you very much for your reply.
P.S. Will this line be enough?
 <input name="set_range" displayname="connection.setrange" />

**Comment by Regalis11** [comment]
Yep, that would work as soon as this change is included in a public build.

**Comment by Rokvach** [comment]
This doesn't really affect normal gameplay and hasn't caused any issues for normal gameplay, haven't got any modders to test this so I will just close this, we can re-open if something comes up. Closing.
