### ISSUE TITLE
Camera moves like crazy when sub start moving

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#2897]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It may not be a bug, maybe its something like ping, but its quite annoying, specially when you are trying to click on something like a button near a cabinet, if the camera was static like the spectator view it would be much nicer, and if it is for realism i think it should be smoother.

Just a little question for me is, if it is ping why on spectator mode the camera follows the sub just  fine?

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.

Although, we do have some plans to improve the camera movement, so there's a chance this will be addressed.
