### ISSUE TITLE
0.1000.0.0 (Unstable): Health bar is rendered over campaign interfaces

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2901]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![45684567](https://user-images.githubusercontent.com/14351070/83275062-54be0000-a1d7-11ea-85e6-250a0ea8a3bb.png)

**Version**
v0.1000.0.0 (Unstable)

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@6dd7c4c. The inventory and portrait area UI elements are now disabled when the campaign UI is displayed.

**Comment by ekqvist** [comment]
The same issue was also reported as a part of another ticket: #2907

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
