### ISSUE TITLE
0.1000.0.0 (Unstable): Switching Submarines Does Not Change Current Submarine on the Submarine Delivery Service

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2903]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Switching to a new submarine does not change "current submarine" on the Submarine Delivery Service terminal, nor does it tell you which submarine will be used next round.
Furthermore, when you purchase a new submarine at a station, the Submarine Delivery Service terminal still has the previous submarine listed as the current submarine. However, once you start a round it is properly updated.

**Steps To Reproduce**
*by purchasing a new submarine*
1. Start a new campaign with any submarine.  
2. Purchase a new submarine. Select "yes".  
3. Check the Submarine Delivery Service terminal.

*with a second submarine already available*
1. On the Submarine Delivery Service terminal, switch to a different submarine.

**Version**
Version 0.1000.0.0 (Unstable).
Windows 10 version 1903.

**Additional information**
Upon docking the correct submarine (new one) will be the current submarine.

**Comment by Rokvach** [comment]
No issues, closing.
