### ISSUE TITLE
[v0.1000.0.0 Unstable] Error while trying to load a save

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#2904]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A previously saved game won't load. Error message starts with:
```
Loading save <path> failed (Object reference not set to an instance of an object.)
at Barotrauma.Job..ctor(Xelement element) in
C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Jobs\Job.cs:line 74
```

**Steps To Reproduce**

1. Start a campaign.
2. Hire or spawn a character with the job Assistant or any other (custom) job with no skill defined as primary in the xml.
3. Save the game.
4. Try to load it again.

**Version**
0.1000.0.0 Unstable

**Comment by Rokvach** [comment]
Looks to be working correctly, closing.
