### ISSUE TITLE
v0.1000.0.0 (Unstable): Clients disconnect if the server has non-vanilla subs installed

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2905]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Try to join a server that has any non-vanilla subs installed (to be more exact, any sub that doesn't have a submarine class defined).

**Version**
v0.1000.0.0

**Additional information**
![unknown](https://user-images.githubusercontent.com/14351070/83281868-699f9100-a1e1-11ea-9988-edae3976c43e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/028fe7332759e78f7e491e7b53d5c5b56e594383

**Comment by Rokvach** [comment]
Tested by deleting all of my custom submarines, working correctly. Closing.
