### ISSUE TITLE
0.1000.0.0 (Unstable): Hall4wayModule_01 Sometimes Has Loose Wires

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2906]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At some outposts, there are loose wires on the ground or at doors. They appear to all be Hall4WayModule_01, so far, and ones with no bottom hatch.
![bFn3DT9U](https://user-images.githubusercontent.com/37539527/83280915-35bb7000-a1cf-11ea-8d07-c2c3a402450c.png)
*Campaign seed: `bFn3DT9U`. Outpost level seed: `Salthole`. Save file: `Save 3.save`.*
![AfvifnkH](https://user-images.githubusercontent.com/37539527/83281544-2688f200-a1d0-11ea-82d9-9a6b53d1a241.png)
*Campaign seed: `AfvifnkH`. Outpost level seed: `Sermilik`. Save file: `Save 7.save`.*
![o2U7dX9a](https://user-images.githubusercontent.com/37539527/83283043-75378b80-a1d2-11ea-8622-6c93c38366fb.png)
*Campaign seed: `o2U7dX9a`. Outpost level seed: `Moulin`. Save file: `Save 8.save`.*

**Steps To Reproduce**
Find yourself in an outpost that uses Hall4wayModule_01, with no bottom hatch. There should be a loose wire on the floor.

**Version**
Version 0.1000.0.0 (Unstable).
Windows 10 version 1903.

**Additional Information**
Saves referenced above: [Saves.zip](https://github.com/Regalis11/Barotrauma/files/4703020/Saves.zip).

**Comment by Regalis11** [comment]
Not sure if this is an issue in the modules or the outpost generation, so I added both code and design tags. Need to take a closer look into this.

**Comment by Regalis11** [comment]
Turns out it was a code bug: the generator would remove unused doors/hatches from the module, but not the wires connected to the door, causing them to drop down when the door is removed. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ecfc998661ec26ed1cc153291232e1d3645a82f5

**Comment by Rokvach** [comment]
Working correctly, closing.
