### ISSUE TITLE
[0.1000.0.0] New menus interferences with HUD

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2907]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some HUD overlaps the new menus. Clicking through the new menus also registers clicks with the HUD.
1. Validate Hires opens up Player's Health Menu.
2. Purchase (items) opens up Player's Health Menu
3. Player's Vitality Bar overlaps new Menus.

**Version**
0.1000.0.0

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@6dd7c4c. The inventory and portrait area UI elements are now disabled when the campaign UI is displayed.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
