### ISSUE TITLE
[0.1000.0.0] Unable to upgrade modules that exists on Shuttles but not Main Submarine.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2908]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My custom sub Corsair comes with Battery, but it's on the shuttle. I am unable to upgrade it.

**Version**
0.1000.0.0

**Comment by 3e849f2e5c** [comment]
Upgrading shuttles / linked submarines has now been implemented in https://github.com/Regalis11/Barotrauma-development/commit/c7b21ca0d3159cbb7030cd80471f321ca1ba5ebb and https://github.com/Regalis11/Barotrauma-development/commit/7ee8b9388528e7eac5a0c704f002b212a0bf4e50

**Comment by Rokvach** [comment]
No issues, closing.
