### ISSUE TITLE
[0.1000.0.0] Upgrades to Submarines does not apply to Shuttles attached.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2909]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upgrades to Submarines does not apply to Shuttles attached. Some submarines uses shuttles as an extension of the Submarine. Would be nice if the upgrades applies to the Shuttle or allow us to upgrade the Shuttle individually.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment]
Duplicate of #2908
