### ISSUE TITLE
[0.1000.0.0] Need hotkeys for upgrading. Mass upgrades are tedious.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2910]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Need hotkeys for upgrading. Mass upgrades are tedious. I'm risking carpal tunnel dragging back and forth between button and prompts.

**Version**
0.1000.0.0

**Comment by hubismal** [comment]
Might be a good idea to give it the crewlist and shop treatment where you select all the upgrades you want and then press a "apply" button to apply it all at once with a confirmation screen.

**Comment by 3e849f2e5c** [comment]
Added ability to press enter to accept the confirmation prompts in upgrade UI in https://github.com/Regalis11/Barotrauma-development/commit/0619c63f2bff7e5b690f9455dc8d7fb6312f2eca

**Comment by Rokvach** [comment]
It is still a bit tedious if you want to buy a lot of upgrades, but the enter key does help up a bit. Might be good to check out a batch purchase option at some point if it still feels tedious on normal play. Closing.
