### ISSUE TITLE
[0.1000.0.0] Outposts drains oxygens too easily.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2911]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My team got suffocated at the station due to the lack of Oxygen provided by the outpost. It also interrupts the vendors and merchants, displacing them around the outpost, All the NPC got knocked out in the outpost too.

**Version**
0.1000.0.0

**Comment by hubismal** [comment]
NPCs seem to have an extremely difficult time actually keeping things repaired. why do things in the outpost modules deteriorate anyway?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/465675471146dd6c63ffd692cdfea81a5143c996

**Comment by Rokvach** [comment]
Working correctly, closing.
