### ISSUE TITLE
[0.1000.0.0] Outpost Items deteriorates

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2912]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items on the outposts deteriorates like the junction boxes.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/842769aeea25a363a85523439ad0e8693e3783ea

**Comment by Rokvach** [comment]
No issues, closing.
