### ISSUE TITLE
[0.1000.0.0] Newly hired crew status are Unknown at the end of round display.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2913]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Newly hired crew status are Unknown at the end of round display.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ee704e1a17f48ecfc99622300cf9be496f9d153

**Comment by Rokvach** [comment]
No issues, closing.
