### ISSUE TITLE
[0.1000.0.0] Please allow same sub class purchases

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2914]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bummed that I can't buy my Corsair sub when I'm driving a Dugong. Both classed as Scout.

**Version**
0.1000.0.0

**Comment by ezjamsen** [comment]
![image.png](https://images.zenhubusercontent.com/5ca744290102ad60918e894b/170d6211-c73f-4383-9b7a-3d8c7eb3bd2c)

Let's remove the classes from the sub management terminal as above and turn it into a scrolling ribbon if more than 4 subs are purchased by the player. Player will then be able to purchase as many subs of a given class as they wish. We can add a 'garage' limit later on if need be, to keep players from having  30 different subs on standby and creating design/balance/gameplay issues as a result.

**Comment by Kaillera** [comment]
I'm in favour of that.

**Comment by Rokvach** [comment]
No issues, closing.
