### ISSUE TITLE
[0.1000.0.0] Crews suffering from Oxygen Loss previous round suffers from permanent Oxygen Loss damage

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2915]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crews suffering from Oxygen Loss previous round suffers from permanent Oxygen Loss damage the rounds after. Can't be cured with CPR.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f78a57745bf2df0afe6a776fd15e3e18c856ae1

**Comment by Rokvach** [comment]
No issues, closing.
