### ISSUE TITLE
[0.1000.0.0] Purchased submarine comes with preplaced items, but no auto-fill items

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2916]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Purchased submarine comes with preplaced items, but no auto-fill items. It should be yes to both, or no to both IMO.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/144ce564863d9d4ca1a1f6d8ba1a088b591c9255

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
