### ISSUE TITLE
[0.1000.0.0] Outpost's Reactor can be readjusted and fuel rod stolen.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2917]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost's Reactor can be readjusted and fuel rod stolen.

**Version**
0.1000.0.0

**Comment by mrjpjr** [comment]
Yeah, it is too easy to access the reactor (and kill the entire outpost that way). Maybe have it ID locked (so you would have to steal an ID from the Outpost bots or crowbar/plasma cut in) so if you do break in, it's on purpose...
...or a Security bot guarding the door (that you can bribe for entry)

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@326ea17. The reactor can now only be accessed with a valid id card.

**Comment by Rokvach** [comment]
No issues, closing.
