### ISSUE TITLE
[0.1000.0.0] Top Scroll Text still displays insufficient pre-upgraded skill requirement level to operate/repair.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2919]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Top Scroll Text still displays insufficient pre-upgraded skill requirement level to operate/repair.

**Version**
0.1000.0.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b1f13174f5ca20583b64271a806a214f5941c119 the text now shows the post-upgrade level

**Comment by Rokvach** [comment]
Confirmed working, closing.
