### ISSUE TITLE
[0.1000.0.0] Crews spawned via "spawn" command are in the wrong team

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2920]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crews spawned via "spawn" command are in the wrong team. They'll be placed into your roster next round, but still with the incorrect headset.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cdea51e613660ae6fdfb044d6cb79f67db8cd01b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
