### ISSUE TITLE
[0.1000.0.0] Aliens are phasing through submarine's exterior doors and hatches

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2922]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Aliens are phasing through submarine's exterior doors and hatches. Generally when the submarine is on the move.

**Version**
0.1000.0.0

**Additional information**
Try it with Corsair or any sub with lots of exterior hatches and doors.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ecfc998661ec26ed1cc153291232e1d3645a82f5

**Comment by Rokvach** [comment]
Working correctly. Closing.
