### ISSUE TITLE
[0.1000.0.0] Merchant will not remove Opium/Morphine/Fentanyl from inventory after Player sold it to them.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2923]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Merchant will not remove Opium/Morphine/Fentanyl from inventory after Player sold it to them.

**Version**
0.1000.0.0

**Comment by ekqvist** [comment]
Seems to be working just fine now as of Regalis11/Barotrauma-development@7882dea. Probably got fixed as a side effect of some other fix.

**Comment by Rokvach** [comment]
Confirmed working, closing.
