### ISSUE TITLE
[0.1000.0.0] Bots are constantly healing themselves from minuscule/no damages again

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2927]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are constantly healing themselves from minuscule/no damages again, even if they are not medic.

**Version**
0.1000.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f3b5056021731dee7275176a541a358714640c55

**Comment by Rokvach** [comment]
No issues, closing.
