### ISSUE TITLE
[Campaign Update] LOS not reapplied when intro animation finishes

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2928]
the establishing animation that disables line of sight does not re-enable it once as you control your character. this gives you no-los for outposts or ships, depending on which one you load into.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e756b827e4a5022d4f53d3735cfe2d0d43de995f

**Comment by mrjpjr** [comment]
A bit more details. 
It happens everytime you get that zoom in animation. So if you load a saved game, it also happens.

**Comment by rav2n** [comment]
sorry for the wrong branch

**Comment by Rokvach** [comment]
No issues, closing.
