### ISSUE TITLE
Most wires on a sub suddenly spawning in as disconnected wire 'item' form in a new campaign round

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#2930]
**(Additional testing required)**

Playing a normal campaign server when suddenly upon starting the round most of the ship's wires seemed to pop off their pins and drop onto the ground as items.
Although a few random power wires and buttons were still connected, for the most part the sub was completely inoperable from that point on.

No errors showed in the console and server log of that session, the mission simply spawned in and instantly broke the wires off.

**Comment by hubismal** [comment]
This seems to happen in campaign as well, there are a lot of random wires on the ground in certain parts of the outpost under junction boxes.

**Comment by rav2n** [comment]
Also, I came across this situation as far as I understand this is due to the modification of junction boxes

**Comment by Regalis11** [comment]
Probably fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e0c58af0f6b9fb8a6f372aaa0689dcef81f0735

**Comment by Rokvach** [comment]
Other tickets relating to this issue has been closed, so closing this one as well. Closing.
