### ISSUE TITLE
0.1000.0.0 (Unstable): Aiming does not work in multiplayer

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2932]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The server and other players always see you aiming directly to the left/right, regardless of which direction you're actually aiming. Seems to affect all aimable items (turrets, welding tools, ranged weapons, etc).

**Version**
v0.1000.0.0

**Additional information**
![34576rtdh](https://user-images.githubusercontent.com/14351070/83325422-c1d3a300-a274-11ea-92e4-59f1e913f5f6.png)

**Comment by Rokvach** [comment]
Working correctly, closing.
