### ISSUE TITLE
0.1000.0.0 (Unstable): Can't get items from events when inventory is full

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2933]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If an event gives you an item when your inventory is full, the item won't appear. We should probably drop the item next to the player instead.

**Version**
v0.1000.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6cf8de002f646125a84c38a022cced0ddaddd5d1

**Comment by Rokvach** [comment]
No issues, closing.
