### ISSUE TITLE
[Campaign Update] Subaq. Symphony doesn't play in EventEditor

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2935]
very minor issue, but subaquatic symphony for hammer and metal doesn't play in the event editor the way it does for all the others, even the invisible ones like particleeditor and spriteeditor

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56f969a5a33ad1ea48117e8ba3aa1c559476bd68

**Comment by Rokvach** [comment]
No issues, closing.
