### ISSUE TITLE
Saveing over a subamine in the editor sets the required version of the sub to 0.0.0.0. The first save works fine, just subsquent ones.

### ISSUE THREAD

**Issue by MiniBen** [Regalis11/Barotrauma#2936]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
Make a custom sub, save it, make an edit and resave it, try to load it when hosting a server
**Version**
Windows version 0.9.9.1

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6c9838f9f5776fe6b865cefda2360abdfb99623

**Comment by Rokvach** [comment]
Confirmed working, closing.
