### ISSUE TITLE
[0.1000.0.0]  flipped Shuttle Shell A Glass A doesn't pass water

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#2937]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When flipping on y axis glass does not pass water when broken

**Steps To Reproduce**
A test file is attached below. Need to break the bottom glass.
[Test Shuttle Shell A Glass A.zip](https://github.com/Regalis11/Barotrauma/files/4707067/Test.Shuttle.Shell.A.Glass.A.zip)

**Version**
0.1000.0.0

**Additional information**
This is a very problematic subject. Besides a mistake with water, its side of the wall eats up too much space and makes it useless.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7014cd2b4536639ddcda9605eae8d13989df80f4

**Comment by Rokvach** [comment]
Working correctly, closing.
