### ISSUE TITLE
[0.1000.0.0] (Unstable) Cannot zoom in character editor

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#2940]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Scrolling the mouse wheel should zoom the view in the character editor either in or out. This does not happen anymore as of version 0.1000.0.0.

**Steps To Reproduce**
1) Open the character editor
2) Attempt to zoom in or out.

**Version**
Version: 0.1000.0.0 (Unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd29f4abcfe1a1c0077f6519e161c4bd95997a01

**Comment by Rokvach** [comment]
No issues, closing.
