### ISSUE TITLE
0.1000.0.0 (Unstable): Ladders On New Docking Modules Are Too Short

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2941]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ladders on the new docking modules terminate significantly higher up than older counterparts. See the following comparison:
![LadderHeights](https://user-images.githubusercontent.com/37539527/83353190-b05bcb00-a348-11ea-9373-ecbdb68d8a8b.png)
This is problematic for existing submarines since their ladders on top docking hatches may not be tall enough to reach the outpost ladder. This means when docked with some submarines, it is not possible to use the ladder to climb onto the outpost after visiting the submarine. 
I think the outpost ladders should be extended further down - outposts (in particular their exteriors) are visible for significantly less of the game so the aesthetic choices to submarine designers should take priority, including making their top ladders shorter. Obviously if the submarine's ladder is longer than necessary, there is no issue.

**Version**
Version 0.1000.0.0 (Unstable).
Windows 10 version 1903.

**Comment by danielasteljoki** [comment]
Fixed in 9143e47.

**Comment by Rokvach** [comment]
No issues, closing.
