### ISSUE TITLE
0.1000.0.0 (Unstable) Holding 1 coilgun ammo box allows selling 2 of them at the trader

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2944]
**Description**
Title.

**Steps To Reproduce**
-grab coilgun ammo box
-go to trader
-open sell window
-observe quantity = 2 instead of =1

**Version**
0.1000.0.0 (Unstable)

**Additional information**
Could be problem with large items held with 2 hands in general.
![2 coil ammo](https://user-images.githubusercontent.com/59519434/83363977-ed05e180-a39d-11ea-96aa-ddab4685a4a0.png)

**Comment by Jlobblet** [comment]
Can confirm this also works with railgun shells.

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@f5f854f. Happened because "two-handed" items occupy two slots in the inventory.

**Note**. This fix will not yet be included in the next Unstable (v0.1001.0.0) build.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
