### ISSUE TITLE
0.1000.0.0 (Unstable): Exiting Singleplayer Campaign During Transisition Causes Cursor to Become Invisible

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2946]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you exit the singleplayer campaign to the main menu during the transition before the start of the round, the cursor becomes invisible and does not reappear.

**Steps To Reproduce**
1. Start a new campaign.
2. Select a destination and undock.
3. Whilst the transition is playing, hit ESC to open the pause menu. Note the cursor is not visible here, either.
4. Select Main Menu and confirm. The cursor is still invisible.

**Version**
Version 0.1000.0.0 (Unstable).
Windows 10 version 1903.

**Additional information**
I have not tested whether going through one of these transitions again makes the cursor reappear at the end.
EDIT: Starting a new multiplayer round or loading a campaign causes the cursor to reappear.

**Comment by Regalis11** [comment]
TODO note: Were going to need to have the cursor visible in the redesigned round summary, so let's not do anything to this issue yet.

**Comment by Regalis11** [comment]
Fixed now that async-roundsummary has been merged

**Comment by Rokvach** [comment]
No issues, closing
