### ISSUE TITLE
0.1000.0.0 (Unstable): The Leave Outpost Button is Weird

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2947]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/37539527/83414453-7a384d00-a415-11ea-8534-c48f0d278cb1.png)
I'll be referring to this as the leave outpost button.
Firstly, it only appears when you arrive at an outpost, rather than loading into a campaign.
Its usage is also suspect. Clicking it leaves the navigation console without a destination.
![image](https://user-images.githubusercontent.com/37539527/83414772-f599fe80-a415-11ea-8a5b-5c377172b894.png)
Upon reaching the destination, this reason becomes obvious:
![image](https://user-images.githubusercontent.com/37539527/83414818-02b6ed80-a416-11ea-84cf-63aee593270c.png)
![image](https://user-images.githubusercontent.com/37539527/83414834-0b0f2880-a416-11ea-8434-1bffde9a9d9b.png)
Attempting to enter produces the following crash report:
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/4711565/crashreport.14.log)
Presumably because this location does not exist.

**Steps To Reproduce**
*to demonstrate the button not appearing all the time*
1. Start a new campaign. The button should not be visible.
2. Travel to any destination and dock at the outpost. The button should be visible.
3. Save and quit.
4. Load the campaign. The button should not be visible.

*to cause the crash*
1. Start a new campaign.
2. Travel to any destination and dock.
3. Click the button.
4. Travel to the destination outpost.

**Version**
Version 0.1000.0.0 (Unstable).
Windows 10 Version 1903.

**Additional information**
My solution would be to have clicking this button bring up the same map as undocking.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf5555be7dedbf83a4008ca57bc564240b07e6ab

**Comment by Rokvach** [comment]
Found some issues with the buttons but commended them in 

https://github.com/Regalis11/Barotrauma-development/issues/1469

**Comment by Rokvach** [comment]
Haven't seen any further issues with the buttons, closing.
