### ISSUE TITLE
Security shouldn't start shooting immediately when entering an outpost with low reputation

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2949]
This is sort of a feature request, but I think this is pretty common sense. Crews shouldn't start in outposts not only because it seems more natural to start them in subs, but because hostile outposts that the crew has low reputation with will presumably immediately start shooting them.

**Comment by ezjamsen** [comment]
Let's treat the docking modules (and by extension, the sub) as special areas in which players are warned to proceed no further if their repuation is too low, but they won't be attacked until they leave that module.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/e9233a131d09fd7a54e0bcbd604c81ee47673e27

**Comment by Rokvach** [comment]
Confirmed working, closing.
