### ISSUE TITLE
[Campaign Update] Performance gets noticeably worse with every active event

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2951]
What the title says. Very easy to reproduce this by repeatedly using `triggerevent` and watching the framerate dip by 5 FPS or so with every usage. This is probably one of the reasons why outposts don't run that well.
I don't mean to act like an expert in game performance but events definitely don't feel like they should be this hard on performance, they are just triggers and conversation actions with a few variable checks after all. I assume this is unintended.

**Comment by Regalis11** [comment]
Probably related to NPC AI. There's some AI optimizations coming in the next unstable build, let's see if that improves the situation.

**Comment by 3e849f2e5c** [comment]
Did some performance debugging and found that TriggerAction was very expensive for calling ScriptedEvent.GetTargets() every Update(). I've significantly reduced the amount of enumeration done by it in https://github.com/Regalis11/Barotrauma-development/commit/d62190545101e79595900e4345f9fe5c4723765f and noticed a big FPS improvement with 20~ events loaded. Not sure if other actions are as problematic so I haven't touched the others.

**Comment by Regalis11** [comment]
Optimized the GetTargets method further in https://github.com/Regalis11/Barotrauma-development/commit/a8e04a0ec1f0eaf56741c25bfc87cdf6bb330c58: it no longer keeps going through the targets every frame when a valid target is not found, and doesn't create new lists constantly. Let's see if this is enough to get the events to run smoothly.

**Comment by Rokvach** [comment]
I'm not noticing any performance loss when triggering multiple events, seems to be improved. Closing.
