### ISSUE TITLE
[v0.1001.0.0 Unstable] Selling an item of a same type as previously sold item won't remove the item from inventory

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#2953]
**Description**

Selling an item of a same type as previously sold item won't remove the item from inventory. Tested at least with Coilgun Ammunition Box and Veteran's Cap so it's likely an universal issue. You still receive the money for selling the item, but it won't get removed from your inventory.

**Steps To Reproduce**

1. Start a new campaign.
2. While controlling your Captain, go to the store of the outpost and sell your hat.
3. See that you gain money for selling it and the item is removed from your inventory.
4. Spawn another one using the `spawnitem` console command.
5. Sell the second copy.
6. See that you gain money for selling it, but it doesn't get removed from your inventory.

**Version**

v0.1001.0.0

**Additional information**

I also tried it by spawning a Coilgun Ammunition Boxes using the console command. The first one was sold and removed correctly. The second box wasn't removed when sold. So, it's likely at least not an issue with the use of the console command.

**Comment by ekqvist** [comment]
Should be fixed with Regalis11/Barotrauma-development@d2b1e35. Should be tested in both singleplayer and multiplayer.

The issue was that the item spawned after the first item was sold had the same ID (which was freed up when the first item was removed) and there was a comparison in the code to make sure that already sold items aren't sold again, but I hadn't considered that the ID can be assigned to a different item after the first one is removed, preventing the new item with the ID of a sold item from being removed.

**Comment by Rokvach** [comment]
Working correctly, closing.
