### ISSUE TITLE
Can't pick up mined ores in mining outpost modules

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2954]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![res5n567](https://user-images.githubusercontent.com/14351070/83650450-08046b80-a5c1-11ea-8040-2e43a5c9c76c.png)

**Steps To Reproduce**
Unknown

**Version**
v0.1001.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ff868b69642659bf69bf36491c529a0173375bb

**Comment by Rokvach** [comment]
No issues, closing.
