### ISSUE TITLE
0.1001.0.0 (Unstable) Outpost NPCs can be poisoned without retribution

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2955]
**Description**
Title
I used H menu to apply all the poisons, ethanol, deadly dose of fentanyl... no reaction.
Applying poisons with syringe gun also doesn't seem to make NPCs react in any way.
**Version**
0.1001.0.0 (Unstable)

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/789c442b3f62276bf30e84884f8d8ec03830e053

**Comment by Rokvach** [comment]
Working correctly, closing.
