### ISSUE TITLE
[Outpost Update] You can escape events by switching characters

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2957]
self explanatory title. press C or use the crew menu in SP to get out of an event with no consequences. This is notably "cheaty" for events that only have bad outcomes or force you to make a decision.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7e10a1e2c87bf72b5b545dc3d13a3c5760388f58

**Comment by Rokvach** [comment]
Working correctly, closing.
