### ISSUE TITLE
[Outpost Update] Bots have trouble on ladders in big reactor room

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2958]
another self explanatory title. The "big reactor" room module with the huge reactor in it features two ladders that bots will constantly go up to the almost-top and then slide/fall down. Probably a waypoint issue.

**Comment by Camper125Lv** [comment]
I also would like to add that i have seen bots get stuck in Hall4WayModule_02 right door (couldn't open door) and in somekinda long vertical shafts bottom exit (running in and out), but it was 0.1000.0.0 version.

**Comment by Rokvach** [comment]
I've noticed this happen as well (if we talk about the same reactor room)

The bots ignores the waypoint above the ladders (X) and directly goes to the waypoint located next to the reactor at the bottom, so when their target switches to the waypoint at the bottom they let go of the ladder and fall down. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bfc6bb54-b313-4180-b703-f69e89260add)

**Comment by Rokvach** [comment]
But I don't think this is a issue anymore, the bots seems to be able to get inside the room quite well now. Closing.
