### ISSUE TITLE
[Campaign Update] Events can trigger while another is going on.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2959]
A pretty glaring issue. This can notably happen if an NPC required to trigger an event (E.G. The captain with the map, a clown for clown relations, etc) walks by you while another event is going on. The dialogue will become "intertwined" and go event1conversation1 > event2conversation1 > event1conversation2 > event2conversation2
If events are actually supposed to trigger at the same time it would probably be beneficial to have the conversations for event 2 play after the conversations for event 1.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f858864755d63f08d68adb5ee2b84141f9dcb6d2

**Comment by Rokvach** [comment]
Wasn't able to reproduce, working correctly. Closing.
