### ISSUE TITLE
Missions can carry over to outpost levels

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2960]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When returning back from a level where a mission was active to the previous outpost, the mission will appear in the outpost.

**Steps To Reproduce**
1. Unlock some mission in an outpost
2. Select the mission and enter the next level
3. Return back to the outpost
4. The mission will reactivate (for example, spawning monsters in the outpost level)

**Version**
v0.1001.0.0

**Comment by Rokvach** [comment]
No issues, closing.
