### ISSUE TITLE
Tab menu crew list ordering is displayed wrong at the start of a round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#2961]
Only noticed on Multiplayer so far

Seems to fix itself after a while but while its messed up you can't click anything on the list.

![messyroundstart.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f5303a85-6d03-4de2-be7b-afc936371d59)

**Comment by ekqvist** [comment]
Do you know if this is still an issue? I tried reproducing this on my end with two clients, but couldn't do it. I tried to open the tab menu instantly at the round start with both clients in both sandbox and campaign modes, but the menu appeared to behave correctly for both clients.

Maybe something to keep in mind for this week's testing session if this issue still persists?

**Comment by Rokvach** [comment]
It seems to depend on the amount of players, when we only had 3 players it showed wrong only briefly but now with more players it stays in the wrong order longer

**Comment by Regalis11** [comment]
My first guess would be that the client is for some reason refreshing the contents of the menu constantly, something may be causing the server to keep sending the crew list or smth to the clients repeatedly.

**Comment by JoneKone** [comment]
This also happens on 0.13.0.11

**Comment by Regalis11** [comment]
Possibly addressed in https://github.com/Regalis11/Barotrauma-development/commit/6e612202b1514b6faa1ff118f0d0f2db73f69778

> Still no clear steps to repro, but looking at the code, I think this has something to do with how we instantiate the client elements with data about whether the client was controlling an (alive) character or not. I suspect in some situation this data was instantiated incorrectly, forcing the list to refresh constantly. I simplified the logic now and added some extra logging to diagnose the problem if we run into it again: if you notice the tab menu breaking, please enable verbose logging and check what the debug console says.

**Comment by Rokvach** [comment]
Haven't yet seen this happen in the Unstable community test sessions, adding a waiting label

**Comment by Rokvach** [comment]
I didn't see the crewlist breaking at all while community testing the latest build, I did see some duplicate entries on the list when players joined the server and spawned in

They were shown correctly as their class once they had spawned in but they also had the "... Playername" listed on the crewlist too ("..." is used when player is still in lobby before spectating), IIRC it only showed the "..." name for the latest player who joined the server and that list entry was only removed once we moved to a different round.
