### ISSUE TITLE
Undocking the sub from an outpost without campaign management permissions softlocks the game

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2962]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Undocking the sub from an outpost without campaign management permissions softlocks the game

**Steps To Reproduce**
1. Join a server, make sure you don't have campaign/round management permissions
2. Start a new campaign
3. Attempt to undock from the outpost 

**Version**
v0.1000.0.0 and later

**Comment by Regalis11** [comment]
Fixed in 9fd3c7d and c36efb2

**Comment by Rokvach** [comment]
We tested this on Unstable 0.1002.0.0 by removing campaign management permissions from every player and it still softlocked us

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b00c179740f7948f9d1edfcfa10f89d3a0ccd43b

**Comment by Rokvach** [comment]
Tested, I was able to do everything without campaign management permissions when playing alone. Working correctly, closing.
