### ISSUE TITLE
Opening the tab menu can sometimes crash the game in MP

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#2966]
**Description**

Opening the tab menu can sometimes crash the game in MP

**Steps To Reproduce**

Unknown

**Version**

0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)

**Additional information**

Reported by Solbusaur on Discord. 

[crashreport_10.log](https://github.com/Regalis11/Barotrauma/files/4728245/crashreport_10.log)

**Comment by Regalis11** [comment]
No known steps to repro and we haven't encountered this in later versions, so I think we can close this
