### ISSUE TITLE
[Shipyard interface] Clients subs are displayed as part of the purchasable submarines in multiplayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#2967]
Unstable 0.1001.0.0

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/286455dd-a98f-4708-b88b-3c92102be450)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c9bead90-992e-4b88-ab41-220ff5de85c2)

**Comment by Rokvach** [comment]
Apparently this is still broken on Unstable 0.1002.0.0, still displays client subs on the list when a client is viewing it.

**Comment by EdusFF** [comment]
Should be fixed, accidentally left the sub fetching to use SavedSubmarines list instead of the ServerSubmarines list

**Comment by Rokvach** [comment]
Confirmed working, closing.
