### ISSUE TITLE
0.1001.0.0 (Unstable): You Can Sell Items With Zero Condition For Full Price

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#2968]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can sell an item that depletes its condition over time - like a fuel rod - for full price, regardless of what the condition of the item is. 

**Steps To Reproduce**
1. Start a new campaign. I recommend you use a modified submarine with the reactor's Fuel Consumption Rate set to A Very Large Number, e.g. 1000.
2. Deplete the condition of the fuel rod to minimum.
3. Sell the rod to the trader on the station for full price (150 Mk).

**Version**
Version 0.1001.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Rokvach** [comment]
Might be good to not being able to sell used items, changing price like that sounds a bit risky.

**Comment by Jlobblet** [comment]
I agree - should an empty fuel rod sell for the price of 1 steel bar + 1 lead? Or should it cost slightly more because it has to be deconstructed etc.?

**Comment by ekqvist** [comment]
Disallowed selling items not at full condition in Regalis11/Barotrauma-development@7882dea

**Comment by Rokvach** [comment]
Confirmed working, closing.
