### ISSUE TITLE
Remora additions/improvements

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#2971]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Suggestions**
- There's a searchlight on the lower nose that has been unpowered for a few versions. There's spare room on some of the junction boxes for it to be wired to. Could also re-add the periscope behind the helm room so it can be wired to it.
- The drone's navigation terminal, now that a warning light has been added, could use its signal_1_out pin for toggling the door's state if wired into the relay given that there is now direct feedback if it's open or not. Wouldn't have to climb down/up the entire passage to close the doors.
- Opening up the drone's ballast and engine for easier repairs. Possibly combining the engine and ballast into one room, assuming the shuttle engine is waterproof. Also ideal for a way to drain the engine if it crashed.
- Leaving spare room in the supply cabinets so autofill can do its thing. I would keep the mask and battery at the least.
- More hallway labels, specifically for directing players to the gun rooms. I've ran into a number of players who couldn't find the coilgun room since it was at the very back of the cabins.

**Version**
0.9.10.0

**Comment by Udrakan** [comment]
Shuttle engine shell can be repaired from interior, however, it cannot be drained. It should either have a pump or at least a duct, though that wouldn't be ideal, because ballast next to it is rarely empty. Making the engine waterproof doesn't sound like a good solution, that's cheating ;). Complete redesign of the drone would be more fitting imo.

**Comment by danielasteljoki** [comment]
Made some changes to Remora, took these suggestions into account too.

**Comment by Rokvach** [comment]
Only found couple really minor details which I reported directly to Daniel, other than those there wasn't any major issues so closing this.
