### ISSUE TITLE
Afflictions aren't showing up above healthbar anymore

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#2972]
Noticed on singleplayer, but I remember testers pointing it out on multiplayer as well while testing Unstable. 

Repro steps:
1. Get hurt

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/217084a4-2fa6-4820-aa79-9d9a9fa73970)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/faaf0e27-7cd4-4f48-a5b3-582306803aab)

**Comment by thegrb93** [comment]
How it should be for non-medics imo.

**Comment by hubismal** [comment]
More like how it should be for people without health scanners... imo too

**Comment by Udrakan** [comment]
I agree with the comments. It would be nice for people to just see "Hurt" or some other simple affliction without health scanner.

**Comment by Regalis11** [comment]
Does not seem to occur in single player

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/df63a0f60efbc4577bf983bb59f62a4b3a6cb1be

**Comment by Rokvach** [comment]
No issues, closing.
