### ISSUE TITLE
Coloured log output of dedicated server is unmanageable on Linux/Unix

### ISSUE THREAD

**Issue by Laura7089** [Regalis11/Barotrauma#2973]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Coloured log output from the dedicated server (that is, the logs from the game session, clients disconnecting etc) will only appear in an unblemished tty on unix.

**Steps To Reproduce**
```bash
./DedicatedServer 2>&1 > test.log
./DedicatedServer > test.log
./DedicatedServer 2> test.log
./DedicatedServer 2>&1 | tee test.log
```
None of these commands produce the same output in the expected place as simply `./DedicatedServer` does.

**Version**
Server reports `0.9.9.1`. Reproduced  on:

- arch linux, kernel 5.6.13
- ubuntu, kernel 4.15.0

**Comment by Laura7089** [comment]
See [here](https://i.imgur.com/3cRzZIm.png) for a screenshot example.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d585d8285fa227ab45e1503dd813e89eab77086c
