### ISSUE TITLE
[Campaign Update] [Feature Request] Some way to buy items on the spot from vendors

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2975]
Currently you have to buy items from vendors that get shipped to your cargo bay and you have to undock and start a whole new round in order to access them. This is extremely annoying if you're all out of supplies and someone is bleeding out, or there is a mudraptor in the outpost and you need something to defend yourself with quickly.
Either the things should instantly appear in the current submarine's cargo bay, or there should be an option to just buy things for yourself when you need them quickly

**Comment by Udrakan** [comment]
I agree that this would be good addition. It was also my first intuition when I first visited the trader, that I would buy stuff immediately, but at the same time, I would appreciate keeping the option to send purchased goods to cargo on submarine. Maybe another purchase button? The immediately purchased stuff could be dropped at the trader's feet.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/pull/4496

**Comment by Rokvach** [comment]
Tested, didn't encounter any issues, commented a bit more thoroughly on the PR. Can be merged and closed.
