### ISSUE TITLE
Value stored in a memory component not synced

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#2977]
There is a circuit in which the outgoing signal from the memory module is added to the button signal, after which the amount overwrites the value to the memory module.
During the game in multiplayer, one player sees a change in the memory module, while the other does not.

**Comment by NicolaruS** [comment]
Here is an example of a data change scheme that is visible only to the player who interacts with it.
https://cdn.discordapp.com/attachments/598095304050606090/718108041328721950/Alkonostcrusian_sonar_test.sub

**Comment by Regalis11** [comment]
Sorry for the super late reply. The value stored in a memory component is not synced in any way at the moment. In some cases that's not a problem: if the signal is coming from something that _is_ kept in sync between the clients, there's no need to sync the value of the memory component separately. In this case however that doesn't work, so I think we'll need to implement syncing the value.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a10028472ed6d482eb19edd108f429fc9b530cbe

**Comment by Rokvach** [comment]
Working correctly, closing.
