### ISSUE TITLE
The last battery life of Stun Baton hit does not Stun

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2978]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The last battery life of Stun Baton hit does not Stun

**Version**
<0.1001.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/827c15500670496adf295ae6ef8247c0968f596b

**Comment by Rokvach** [comment]
No issues, closing.
