### ISSUE TITLE
[0.1001.0] When putting Discharge Coils on Junction Grid instead of Supercapaciter, It compels Engineers bots to put in more fuel rods

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2981]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When putting Discharge Coils on Junction Grid instead of Supercapaciter, It compels Engineers bots to put in more fuel rods when you spam discharge.

**Version**
0.1001.0

**Comment by Regalis11** [comment]
I wouldn't consider this a bug. Discharge coils require huge amounts of power, so if you're trying to power them from the main grid, you do need to put more than one rod in the reactor.

**Comment by Kaillera** [comment]
Didn't we had a discussion before whether or not the bots should throw in multiple rods when the submarine doesn't have enough power? I thought that ended with them shouldn't do it, so why do they do it now for this very particular occasion?

**Comment by Regalis11** [comment]
In normal circumstances they shouldn't load more than one: to be exact, they only load more if the load is more than twice than what the reactor can output with one rod (which generally shouldn't happen unless you're doing something unusual).

Discharge coils briefly draw 10 000 kW of power, which puts such an enormous load on the reactor that the bots have no other choice than to load more rods.
