### ISSUE TITLE
[0.1001.0] Upgrades don't affect legacy items

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2982]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pump upgrades don't affect Non-Ballast Pump (According to the HUD)?. I would like to be able to upgrade decrease repair skill requirement or repair speed for all the smaller pumps around the subs.

**Version**
0.1001.0

**Comment by 3e849f2e5c** [comment]
They do but not the legacy pump as they lack tags that the upgrade system relies on

**Comment by 3e849f2e5c** [comment]
Added support for legacy items in https://github.com/Regalis11/Barotrauma-development/commit/37ded30c91deaef45d27f1c77896a5b6d113ad49 also improved the "allowedupgrades" attribute for items so modders can add their own items into upgrade categories without having to override upgrades.

**Comment by Rokvach** [comment]
Tested, I was able to successfully upgrade legacy pumps, closing.
