### ISSUE TITLE
Debugging error - could not find suitable position of interest

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#299]
Version 0.8.0.4
code was running on github commit: 9e298c98abfe242f5f39ba7bd139133b2c20e09c

Reproduction:
Run using debugwindows
Hosted on a server
Submarine: Aegir Mark III
Level seed: 0xvHtgNN
Gamemode: Mission, Random.

![image](http://puu.sh/zydfD/b344c4314e.png)

Not sure if this needs to be looked into so I threw it up.

**Comment by Regalis11** [comment]
Whoops referenced wrong issue in 6ddcd65

**Comment by NilanthAnimosus** [comment]
Got this again on 0.8.0.5 Debugmode with:
Submarine: Aegir Mark III
Game mode: SandBox
Level seed: 5yayodJQ

**Comment by Regalis11** [comment]
This should be fixed in the dev branch.
