### ISSUE TITLE
0.1001.0.0 (Unstable) Supplies and mission disappear after hitting Retry during campaign round

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2993]
**Description**
Title.
**Steps To Reproduce**
-purchase supplies, accept mission and embark.
-after undocking, press Esc and Retry
-missions and supplies are gone after load
**Version**
0.1001.0.0 (Unstable)

**Comment by SandPoot** [comment]
Can confirm that this also happens on stable (0.9.10.0) and on every way that you end the round.

**Comment by ekqvist** [comment]
Purchased supplies not being created after reload should be fixed in Regalis11/Barotrauma-development@12d5ae8. This fix is on the `campaign-groundwork` branch and applies to the Unstable version.

**Comment by ekqvist** [comment]
Available and selected missions should now be saved with the location after changes in Regalis11/Barotrauma-development@f376d75 and Regalis11/Barotrauma-development@c1b1de3. The previously started mission should now be selected correctly when reloading a save.

However, I did notice an issue with the previously started mission not being selected correctly when reloading a MP save. But there was a recently reported bug (#3039) with selected mission not always starting so there could still be another related issue, too.

**Comment by Rokvach** [comment]
Couldn't reproduce the issue, seems to be working correctly. Closing.

**Comment by rcoltonclark** [comment]
this is an issue again please fix

**Comment by ekqvist** [comment]
It seems that the issue might be happening again in some form as reported in #7853. If this is the case, it should be fixed in Regalis11/Barotrauma-development@48f7d39.
