### ISSUE TITLE
Crashes when attempting to edit long names

### ISSUE THREAD

**Issue by remnny** [Regalis11/Barotrauma#2999]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My current username on Steam is "is false when preceded by itself". It's 32 characters long - the maximum length of a Steam username. In-game it's truncated to 20 characters ("is false when preced"), but all text-boxes containing my username have the full thing as their initial value, and the game crashes when I try to highlight or edit them.

**Steps to Reproduce**
Change your name on Steam to something more than 20 characters. Then try to edit the username box in the server browser or the in-game Tab menu.

**Additional Information**
I'm no game-development expert, but I think the root cause of the crash is the mismatch between the max length of a Steam name (32 characters) and the max length of an in-game name (20 characters) - the game panics when it sees that the text-box's text is longer than it should be. Two likely fixes:

* Increase the max length of an in-game name to 32 characters.
* Add a check to the game's text boxes so that they can't be initialized with a value longer than the max length.

EDIT: Changed my name to "summary execution" (17 characters). The issue went away.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ca755b347185f8dd38817af643a726cc4688e14

**Comment by Rokvach** [comment]
No issues, closing.
