### ISSUE TITLE
Why UDP ?

### ISSUE THREAD

**Issue by sheychen290** [Regalis11/Barotrauma#30]
Why use UDP, when you have a master server who can setup TCP connections with players ?

**Comment by Regalis11** [comment]
I was under the impression that using TCP in a fast-paced multiplayer game was generally considered a bad idea. A lot of the data passed between the server and the clients is time-critical and doesn't necessarily have to be sent in reliably or in order, so I think UDP (with some custom logic for the data that DOES need to be reliable and ordered) is a more appropriate choice.
