### ISSUE TITLE
NPC's getting stuck in front of a ladder

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3002]
@Rokvach commented on [Mon Jun 01 2020](https://github.com/Regalis11/Barotrauma-development/issues/1903)

Repro steps:
1. Startup the save
2. Press retry until it happens

Looks like the NPC's are trying to climb up the ladder but somehow fail to do so.

Save:
[https://app.zenhub.com/files/175046454/a864ebcc-9f92-4f2f-8b37-f7b5b59ebf30/download](https://app.zenhub.com/files/175046454/a864ebcc-9f92-4f2f-8b37-f7b5b59ebf30/download)

(Bottom left ladder, 3 bots stacked on top of each other not moving)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/26bf5036-94df-42a3-8cea-78a22002492f)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b7b59a39-58e8-48a4-b305-8f1ccdbff7c3)

---

@Rokvach commented on [Tue Jun 02 2020](https://github.com/Regalis11/Barotrauma-development/issues/1903#issuecomment-637354214)

This looks to be really common, seeing it in almost any outpost if I just hang around for a bit, so the save might not be necessary in order to test this.

---

@Regalis11 commented on [Wed Jun 03 2020](https://github.com/Regalis11/Barotrauma-development/issues/1903#issuecomment-638127565)

Did a bunch of fixes to waypoints and pathfinding in the campaign-groundwork branch (e62c669, b1cac6e, 8eb5c01, 04318ae, 33e01df), let's see if those help.

**Comment by Rokvach** [comment]
Haven't noticed any issues with this specific configuration, bots seems to still get stuck on some certain areas but not in here anymore, I've made some new tickets for those, closing this one.
