### ISSUE TITLE
[0.1001.0] EngineeringModule_02 missing platform for bottom entrance.

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3007]
**Description** 
For some reason EngineeringModule_02 is missing bottom hatch platform in game.

**Steps To Reproduce**
Start game [0.1001.0] with XVsxAOqr map seed, then go up, up until you gonna see reactor room and there you gonna see that it's hatch doesn't have a platform.

**Pciture Of Bug**
![bug](https://user-images.githubusercontent.com/32136089/83979330-4928b280-a916-11ea-927a-0a0d160e4a55.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/41da16cbad246e8abdc63e1b4fdbfc28cab08502
