### ISSUE TITLE
[0.1001.0.0] Bots don't take off their diving masks or diving suits when situatuion has cleard out.

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3011]
**Description**
Bots don't take off their diving masks or diving suits when situatuion has cleard out. Also they wear diving masks with diving suits.

**Steps To Reproduce**
Flood the sub with bots then unflud it.

**Additional information**
Would be nice if they put on their gear back on when after removing diving gear.

**Comment by Regalis11** [comment]
Duplicate of #2859
