### ISSUE TITLE
Dugong's airlock won't drain fully

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3012]
Tested on commit: https://github.com/Regalis11/Barotrauma-development/commit/6f7342763324072d32afbad99b48c7e285d7398c
Mode: Multiplayer campaign (But also noticed on singleplayer)
Branch: campaign-groundwork
Submarine: Dugong

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/dd282207-1d41-42a2-a57d-45d317035263)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4b7c855d-b133-4473-926e-654dbd66fec4)

**Comment by Kaillera** [comment]
Normally this is due to the fact that water detector is still above the water, thus not telling the pump to drain.

**Comment by Regalis11** [comment]
Kaillera is right, there is actually water in the room, but the pump fails to drain it because the water detector is placed above the bottom of the hull.

**Comment by Rokvach** [comment]
I don't think the issue only extends to Dugongs airlock

**Comment by HeatedWafflez** [comment]
This is pretty much a universal problem with every submarine unfortunately. I would be very grateful if the water detectors were reworked to maybe have a setting to detect any amount of water inside of the hull it is in.

**Comment by danielasteljoki** [comment]
Adjusted hulls on submarines so that this shouldn't be a problem anymore. (464abfc)

**Comment by Rokvach** [comment]
No issues, closing.
