### ISSUE TITLE
Buzzing Sound at Start of Game

### ISSUE THREAD

**Issue by bendemont** [Regalis11/Barotrauma#3013]
- [ No ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
3 minute buzzing sound across gameplay.  Only happens once

**Steps To Reproduce**
Press start new game

**Version**
Vanilla 0.9 Mac Catalina

**Additional information**
You can still hear game sound behind the buzz.

**Comment by bunnybones1** [comment]
Same issue
