### ISSUE TITLE
detonator bug

### ISSUE THREAD

**Issue by Testasticles** [Regalis11/Barotrauma#3017]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I try to drag the wire in the detonator wiring panel, it closes the window.

**Steps To Reproduce**
1. place detonator on the wall
2.equip screwdriver + wire
3. press E on detonator
4. try to select wire
**Version**
v0.9.10.0 windows 10

**Comment by EdusFF** [comment]
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/da0a4d985e3bed8707beed73cd09e28a00cad2e7

**Comment by Rokvach** [comment]
Didn't spot any issues, closing.
