### ISSUE TITLE
[0.9.10.0] Diving suit view area jittery when in menu or when mouse hovers over character

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#3018]
- [x] I have searched the issue tracker to check if the issue has already been reported.

https://streamable.com/pwd7f1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5bb0ec308de1db9c1edee8c86b7e96a3401ca654

**Comment by Rokvach** [comment]
No issues, closing.
