### ISSUE TITLE
Fixtools ignore character torso/waist regions (Collider is targetbody?)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#302]
Version 0.8.0.4 (Reportedly effecting vanilla, tested it myself with my code though)

The repair tool when targetting a characters chest-region (In this case, an AI character I spawned) did no damage, upon breaking in the code to debug, whatever body it hit was not classed as a structure, limb or item and skipped all three checks in the repair tool.

It appears to be hitting the players collider (Cat2 - Collision.Character) instead of a limb then checks if the collider is a limb (It is not), shielding any limbs beneath it by hitting the ragdoll collider first.

**Comment by Regalis11** [comment]
Fixed in 6ddcd65
