### ISSUE TITLE
[0.1001.0] Unable to cancel accidental undocking from outpost.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3021]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to cancel accidental undocking from outpost.

**Version**
0.1001.0

**Comment by Regalis11** [comment]
Leaving an outpost is now done by pressing a button at the top-right corner of the screen instead of undocking, I don't think this needs to be addressed any more
