### ISSUE TITLE
[0.1001.0] Multiplayer Campaign - All players can select and start missions, and spend Marks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3022]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All players can select and start missions, and spend Marks in Multiplayer Campaign.

**Version**
0.1001.0

**Comment by Kaillera** [comment]
I think it's time to experiment with personal wallets. Items sold in the outpost should probably cost  10-20 times more than before with a few exceptions to items like shotguns with already high price.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9fd3c7df

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
