### ISSUE TITLE
[0.1001.0] Multiplayer Azimuth - Purchased items spawns mostly inside of submarine shell of the sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3023]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Purchased items spawns mostly inside of submarine shell of the Azimuth in multiplayer.

**Version**
0.1001.0

**Comment by Udrakan** [comment]
Can confirm.

**Comment by Regalis11** [comment]
https://github.com/Regalis11/Barotrauma-development/commit/5ed034eb7b6871cbf73f6c9b6fd7e02be8e0090b

**Comment by Rokvach** [comment]
No issues, closing.
