### ISSUE TITLE
[0.1001.0] Azimuth labels

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3024]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For labels "Fire" and "Oxygen levels" are not used prepared labels. The inscriptions are in plain text.

**Steps To Reproduce**
Open the Azimuth submarine in the editor and look at the inscriptions next to the command terminal.

**Version**
0.1001.0

**Comment by danielasteljoki** [comment]
Fixed in 44f3d99.

**Comment by Rokvach** [comment]
No issues, closing.
