### ISSUE TITLE
[0.1001.0] Incorrect lighting of the fins using the "draw behind sub".

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3025]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
These fins are not illuminated when this option is enabled: 
Tail Fin D2 p1
Tail Fin D2 p2
Tail Fin D2 p3
Tail Fin D
Tail Fin D3 p1
Tail Fin D3 p2
Tail Fin D3 p3
Tail Fin F1
Tail Fin F2
Tail Fin F3
Tail Fin F4

**Steps To Reproduce**
In the test mode of the editor, try to spotlight these fins with the "draw behind sub" option turned on.

**Version**
0.1001.0

**Additional information**
For some reason, when shifting the sprite depth, this problem may disappear. So I had a fin consisting of two parts. One part had a sprite depth of 890, the other was not illuminated - 900 by default. When aligning both parts to a depth of 890 received the correct lighting. But at the same time, some fins still remain darkened, although by default they have a sprite depth of 010.
![01](https://user-images.githubusercontent.com/29980468/84154257-8b193c00-aa6f-11ea-9ad6-88b9bb392cfb.jpg)
![03](https://user-images.githubusercontent.com/29980468/84154262-8c4a6900-aa6f-11ea-80a4-14e2f85610ff.jpg)
![05](https://user-images.githubusercontent.com/29980468/84154336-a421ed00-aa6f-11ea-9904-3ee90c4f325c.jpg)

**Comment by Rokvach** [comment]
This sounds like something that has been fixed
