### ISSUE TITLE
The scale of shell parts and various items is forced to 0.5

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3026]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shuttle shell parts, interior walls and many items can't be scaled: they revert back to 0.5 when reloading the sub.

This happened because the scales of the sprites were doubled, and we had to halve the scales of the entities to compensate. The item/structure configs are now set to force the scales to 0.5 in all unstable builds, but once we set the version number to the final one, we can change it to multiply the scales by 0.5 on all subs saved with an earlier version than 0.10.0.0 (= allowing them to be freely edited, while still making sure entities in old subs don't appear in 2x scale).

**Version**
v0.1002.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/03cec9c39db0162738d50781f73bdb5f091aa511

I set it to multiply the scales of the shuttle pieces by 0.5 in subs saved with a version earlier than 0.1002.0.0 (current unstable build). We need to change that to v0.10.0.0 before we release the campaign update.

**Comment by rav2n** [comment]
Many elements ceased to scale. Lamps, containers, inside walls.

**Comment by FamiliarBreakfast** [comment]
So, just to be clear, does this happen when the ship is saved or when it is loaded?

**Comment by Regalis11** [comment]
The scales of the items/structures are upgraded when loading the sub. But if you save at that point, they will get saved with the new scales.

**Comment by FamiliarBreakfast** [comment]
I've made a temporary workaround for those who want to build with the new outpost pieces:
https://steamcommunity.com/sharedfiles/filedetails/?id=2127355312

This will probably screw up some important gameplay elements, so don't use it in normal gameplay.
It overrides every item or structure to remove the version scaling. This also means ships from older versions won't load right, however ships made in 0.1002.0.0 work fine.

**Comment by Kaillera** [comment]
0.1003.0

Happening to Railgun and this Lamp.
![Capture](https://user-images.githubusercontent.com/5086682/84826077-6a616100-aff0-11ea-82ee-cf43f3aba041.PNG)

**Comment by mrjpjr** [comment]
Scale reset happening with shuttle pieces as well

**Version**
Unstable 0.1003.0.0 revision 7b3c34c2a
Windows 10, 64 bit

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/396b8be1dc0855beeb07644a38c818650c296812

**Comment by Rokvach** [comment]
Didn't notice any issues, closing.
