### ISSUE TITLE
[0.1002.0.0] Crate shelf has coil gun ammonition shelf graphics

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3028]
**Description**
Crate shelf has coil gun ammonition shelf graphics.

**Steps To Reproduce**
Open a game and start any kind of mission with submarine that has crate shelf or alternativly open submarine that has crate shelf in submarine editor.

**Version**
0.1002.0.0

**Additional information**
Plz fix.

**Comment by Rokvach** [comment]
Working correctly, closing.
