### ISSUE TITLE
Error connecting to campaign server during voting

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#3030]
**Description**
Connected to Jlobblet's dedicated server, running campaign. According to Jlobblet, I connected during a submarine vote when I got the error

**Version**
v0.1002.0.0

Here's an image of the debug log
![image](https://user-images.githubusercontent.com/63509011/84171578-e13bae80-aa72-11ea-8dff-2510ca8d40fd.png)

**Comment by Rokvach** [comment]
The issue highlighted on this ticket has been fixed but there seems to be couple new ones, but closing this ticket as the specific issue this fixes is working correctly, closing.
