### ISSUE TITLE
Move cursor shows up at the upper part of this specific slot

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3032]
Tested on Unstable 0.1002.0.0
Sub: Remora

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6657cb49-83d3-41f1-a821-30d5b6ed07d0)

Cabinet:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b97b16af-0457-4765-93fc-c1064f120b0b)

**Comment by Regalis11** [comment]
Could not reproduce

**Comment by Regalis11** [comment]
No known steps to repro, closing for now
