### ISSUE TITLE
Speech icon doesn't disappear when NPC dies

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3034]
Tested on Unstable 0.1002.0.0

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5ff206d3-9f4f-45b8-ba9c-61cf0b71a280)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddeadacf9e90cd34d495117a3ceaca7e2bd9e592

**Comment by Rokvach** [comment]
No issues, closing.
