### ISSUE TITLE
0.1002.0.0 (Unstable): Killing Outpost Member With Medicine Doesn't Reduce Reputation

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3036]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you kill an outpost member with medicine or poisons, reputation does not decrease.

**Steps To Reproduce**
1. Start a new campaign.
2. Use a fentanyl overdose to kill an AI.

1. Start a new campaign.
2. Use cyanide to kill an AI.

**Version**
0.1002.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Rokvach** [comment]
Also guards aren't alarmed by this either

**Comment by Regalis11** [comment]
Duplicate of #2955
