### ISSUE TITLE
0.1002.0.0 (Unstable): Cannot Rewire Near NPCs With Conversations

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3037]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When there is a nearby NPC with a conversation option (example: submarine upgrade), you cannot rewire a hatch. This occurs whether they are dead or alive.

**Steps To Reproduce**
1. Start a new campaign.
2. Kidnap one of the NPCs with a conversation and take them next to a door or hatch on your sub.
3. Attempt to rewire the door or hatch.
4. Kill the NPC.
5. Attempt to rewire the door or hatch.

**Version**
Version 0.1002.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Regalis11** [comment]
Partially fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddeadacf9e90cd34d495117a3ceaca7e2bd9e592 (disabled campaign interactions with dead characters)

**Comment by Regalis11** [comment]
I think we can close this: changing the interact key or the whole interaction logic for a rare edge case like this is probably not worth it.
