### ISSUE TITLE
0.1002.0.0 (Unstable): Selecting a Mission Does Not Always Give the Mission in the Round

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3039]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After selecting a mission when choosing next destination and undocking, the mission is not always active in the round. Observed with an artifact salvage mission.

**Steps To Reproduce**
1. Get a mission from an outpost.
2. Select the mission when you undock.

**Version**
Version 0.1002.0.0 (Unstable).
Windows 10 version 1903.

**Comment by ekqvist** [comment]
Did this only happen in MP? Or did you notice it in SP as well?

**Comment by Rokvach** [comment]
Happened in multiplayer during yesterdays community testing session, I haven't seen issues on singleplayer but I haven't taken a close look at it either @ekqvist

**Comment by ekqvist** [comment]
Okay, good to know. As I commented, I noticed the same issue while fixing #2993. Only faced it in multiplayer, so this **might** be a multiplayer-specific issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ac46a5

**Comment by Rokvach** [comment]
Considering how common this issue was on the previous build and yet there hasn't been any sightings of it yet, I feel quite confident that its working correctly now, will keep the entry open on the testers homework a bit longer but will just close this ticket. Closing.
