### ISSUE TITLE
0.9.10.0: Reactor Melts Down With No Fuel

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3042]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the reactor's condition hits 0, it melts down. This happens regardless of whether there is any fuel in the reactor or not.

I think the reactor should check that is has fuel inside it before it causes an explosion - what is exploding in the reactor when it's empty?

**Steps To Reproduce**
1. Start a new game.
2. Remove any fuel rods from the reactor.
3. Flood the reactor room.
4. Wait for the reactor to exploded.

**Version**
Version 0.9.10.0.
Windows 10 version 1903.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9e944fd796fdc24b68c66ecfe7164c48827ef5a8

**Comment by Rokvach** [comment]
No issues, closing.
