### ISSUE TITLE
Can't damage outpost walls in multiplayer, no way to get through ice walls in mining outposts

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3043]
Tested on Unstable 0.1002.0.0

It's mainly a issue with the mine ice walls as you should be able to cut them in order to fully explore the mine. 

Repro steps:
1. Load up a multiplayer campaign
2. Try to plasma cut walls
3. Notice that the progress bar doesn't change

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54a7479e3918aa21de8356f517a7b77ea94c726f

**Comment by Rokvach** [comment]
Confirmed working, closing.
