### ISSUE TITLE
0.1002.0.0 (Unstable): Sometimes Destination Image is Wrongly Placed

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3044]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes the image showing destination is wrongly placed.
![image](https://user-images.githubusercontent.com/37539527/84180703-d89da500-aa7f-11ea-94ed-d5747340764d.png)

**Steps To Reproduce**
Afraid I haven't been able to reproduce it consistently. 

**Version**
0.1002.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Regalis11** [comment]
The map screen is going to go through a major overhaul, so we're not going to touch the current layout atm
