### ISSUE TITLE
0.1002.0.0 (Unstable): Moloch Shell doesnt appear on character

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#3047]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![20200609202016_1](https://user-images.githubusercontent.com/60567270/84187459-bfeeb880-aa9a-11ea-8d49-ed7423b9fdd0.jpg)
![20200609202017_1](https://user-images.githubusercontent.com/60567270/84187466-c3823f80-aa9a-11ea-8d8e-d7acd0c86b56.jpg)

**Steps To Reproduce**
1) Unequip your clothes
2)Equip shell

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26e012898a3099e2720b9e80daaa41403b086f80

**Comment by Rokvach** [comment]
No issues, closing.
