### ISSUE TITLE
Unstable - Same mission and events spawn at outpost after finishing the mission and docking back

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3050]
**Description**
When you finish an event and accept a mission, undock, finish the mission and return to the same outpost, you get the exact same event and the exact same mission from the same NPC.

**Steps To Reproduce**
-accept mission
-finish the mission
-dock back at the outpost on the start of the map
-check if the same mission is there

**Version**
Unstable

**Comment by Regalis11** [comment]
(Just a note for us: there's a ticket about this in the private repo, close both when this is implemented https://github.com/Regalis11/Barotrauma-development/issues/1881)

**Comment by Rokvach** [comment]
Tested, did a wreck salvage mission and returned back to the starting outpost, got a salvage mission next. Working correctly. closing.
