### ISSUE TITLE
0.1002.0.0 (Unstable): Attempting to Save an Outpost Module Causes Crash

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3055]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When attempting to save an outpost module in the submarine editor, the game crashes to desktop.
This occurs when creating a new module or using an existing one.
See attached:
[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/4758034/crashreport.15.log)
[crashreport (16).log](https://github.com/Regalis11/Barotrauma/files/4758031/crashreport.16.log)
[crashreport (17).log](https://github.com/Regalis11/Barotrauma/files/4758032/crashreport.17.log)
[crashreport (18).log](https://github.com/Regalis11/Barotrauma/files/4758033/crashreport.18.log)

**Steps To Reproduce**
1. Open the submarine editor.
2. Load an outpost module.
3. Attempt to save it under a new name.

**Version**
0.1002.0.0 (Unstable).
Windows 10 version 1903.

**Comment by Jlobblet** [comment]
Verbose log output.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/4758078/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4b85b2a271e6f3bb6bda5599c56c07546b202fd

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue, looks to be working correctly. Closing.
