### ISSUE TITLE
0.1002.0.0 (Unstable): Undefined-Class Submarines Show Up on New Campaign Screen

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3056]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Undefined subs show up on the "Selected Submarine list".
![My venerable collection of Dugong variants for testing wiring.](https://user-images.githubusercontent.com/37539527/84262769-1a792a80-ab16-11ea-9990-a0aea1942ddc.png)
![image](https://user-images.githubusercontent.com/37539527/84262812-367ccc00-ab16-11ea-8ca1-6546240bbec0.png)

**Steps To Reproduce**
1. Save a submarine with undefined type.
2. Look at the new game screen.

**Version**
Game version 0.1002.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision 07ef298dd).

**Comment by EdusFF** [comment]
Intended as of now
