### ISSUE TITLE
0.1002.0.0 (Unstable): Event sleightofhand Does Not Give Reward on Success

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3057]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The event `sleightofhand` has an issue with the outcome `sleightofhand.o2.c1` - the `alientrinket1` is not given to the player.
![image](https://user-images.githubusercontent.com/37539527/84265764-3f23d100-ab1b-11ea-9f26-58a04eca6e94.png)

**Steps To Reproduce**
1. Start a new campaign.
2. Use `triggerevent sleightofhand` to start the event.
3. Choose option 2 ("Create a distraction and try to snatch it without anyone noticing.")
4. If the outcome is c1 ("You start yelling “Fire!, Fire!” and quickly grab the item in the ensuing chaos. You hide it deep in your pocket. It’s time to go before they’re any wiser."), check inventory for `alientrinket1`.

**Version**
Game version 0.1002.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision 07ef298dd).
Windows 10 version 1903.

**Comment by Rokvach** [comment]
No issues, closing.
