### ISSUE TITLE
Graphical glitch in charge bar on Supercapacitors

### ISSUE THREAD

**Issue by MrDj200** [Regalis11/Barotrauma#3059]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Temporary graphical glitch when configuring supercapacitor in Sub Editor.
Glitch will disappear once Test is started.

**Steps To Reproduce**
1. Open Editor and select Supercapacitor
2. Set Capacity to 20
3. Set Charge to 20
4. Close Menu
5. Select Supercapacitor
6. Set Capacity to something less than Charge

**Version**
Unstable V0.1002.0.0 (Windows)

**Additional information**
![image](https://user-images.githubusercontent.com/5685500/84322095-b3d72980-ab74-11ea-88cb-8adee5d7673c.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4aac3ea3b3629806e18e943dede410335e5bcd6

**Comment by Rokvach** [comment]
Working correctly, closing.
