### ISSUE TITLE
Selecting Item Assembly directly spawns it

### ISSUE THREAD

**Issue by MrDj200** [Regalis11/Barotrauma#3060]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When selecting any Item Assembly, it is spawned when clicking it.

**Steps To Reproduce**
1. Open Editor and select any Item Assembly

**Version**
Unstable V0.1002.0.0 (Windows)

**Additional information**
Bug in Action:
https://youtu.be/3b4CRMyTk_4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cde15f2927d7fb478892f95db8294d0ca9b73b9e

**Comment by Rokvach** [comment]
Working correctly, closing.
