### ISSUE TITLE
Killed by wires

### ISSUE THREAD

**Issue by MoscowRaccoon** [Regalis11/Barotrauma#3062]
If you begin wiring and put wires on the walls and ragdoll the ragdoll starts to fly around uncontrollably moving your mouse also makes it worse and you can die from hitting walls the roof or the floor

**Comment by MoscowRaccoon** [comment]
its also pretty epic

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce this issue: the character ragdolls normally even when rewiring. Did this happen in single player or multiplayer? Which version of the game did it happen in?

**Comment by HeatedWafflez** [comment]
> I'm afraid I wasn't able to reproduce this issue: the character ragdolls normally even when rewiring. Did this happen in single player or multiplayer? Which version of the game did it happen in?

I think it can be replicated if you place too many wire connections/joints/bends. I remember something like this happening to me a long time ago, don't take my word on it.

**Comment by Camper125Lv** [comment]
Managed to replicate, just start wiring and spam click bends on the wall and after a while it gonna happen.
Proof: https://youtu.be/on59zUb6IXs?t=86

**Comment by HeatedWafflez** [comment]
> Managed to replicate, just start wiring and spam click bends on the wall and after a while it gonna happen.
> Proof: https://youtu.be/on59zUb6IXs?t=86

Awww yeeeahhh, called it!

**Comment by Regalis11** [comment]
Thanks for the extra info! It's intentional that the character gets pulled back when trying to run a wire very far, but throwing the character around like that was obviously not the intention.

I improved the logic a bit in https://github.com/Regalis11/Barotrauma-development/commit/484612416a14ee6e104c047a1faae31dadb4516f, now the behavior should be much less erratic. Moving the ticket to QA

**Comment by Rokvach** [comment]
Your character still seems to slide around a bit, but nothing as bad as shown on the video. Closing.
