### ISSUE TITLE
[0.1002.0] The pump in this module is not at -100% pump speed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3063]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The pump in this module is not at -100% pump speed
![Capture](https://user-images.githubusercontent.com/5086682/84380325-27992680-abb5-11ea-9d49-2990c0c4920a.PNG)

**Version**
0.1002.0

**Comment by Rokvach** [comment]
No issues, closing.
