### ISSUE TITLE
GoTo not working correctly under certain circumstances

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#3064]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a label is found within a binary condition action (CheckItemAction, CheckDataAction, etc), GoTo will not work correctly when referencing this label. Bug reported by hubismal on Discord.

**Steps To Reproduce**
- Replace gototest in OutpostEvents.xml with the following:
```xml
<ScriptedEvent identifier="gototest" commonness="0">
  <CheckDataAction identifier="mydata" condition="eq 2">
    <Success>
      <Label name="success" />
      <ConversationAction text="success" />
      <GoTo name="end" />
    </Success>
    <Failure>
      <Label name="failure" />
      <ConversationAction text="failure" />
    </Failure>
  </CheckDataAction>
  <GoTo name="success" />
  <Label name="end" />
</ScriptedEvent>
```

- Start any kind of outpost level.
- Run the command `triggerevent gototest`
- The correct behavior would be a message that says "failure", followed by one that says "success". Instead, what's observed is an infinite chain of messages saying "failure".

**Version**
v0.1002.0.0, all platforms

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/30cee019c96b558090be87da491c6906f65c3fc8

**Comment by Rokvach** [comment]
No issues, closing.
