### ISSUE TITLE
[0.1002.0] Question - Is there guarunteed 1 mission giver per outpost?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3065]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Is there guarunteed 1 mission giver per outpost? I've been to two outposts in a row and haven't seen them.

Edit: 4 Outposts in a row, still no mission giver.

![Capture](https://user-images.githubusercontent.com/5086682/84388489-af396200-abc2-11ea-9ae7-be1ff6b3dd55.PNG)

**Version**
0.1002.0

**Comment by Kaillera** [comment]
Turns out my save file in 0.1001.0 didn't give me any base rep to any of the locations.

**Comment by Regalis11** [comment]
The outpost manager (the NPC with the clown mask who hangs around in the admin module) should always offer missions. I did a bit of testing and couldn't find an outpost without available missions - if you have a save file that'd be very helpful in diagnosing this.

**Comment by Kaillera** [comment]
https://github.com/Regalis11/Barotrauma/files/4765441/Save.zip

If you go to any outposts on this save, there aren't any mission giver. I think sub I haven't seen a submarine seller as well.

**Comment by Regalis11** [comment]
Thanks! Looks like the issue was that the mining outpost events were configured using an incorrect location type, so events would not appear at all in mining outposts. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0c2a60d400a7a92a1c7bedff9279b3cced805db7

**Comment by Rokvach** [comment]
No issues, closing.
