### ISSUE TITLE
[0.1002.0] Ores are too high to mine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3066]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The ores in this module is too high to mine from the ground.

![Capture](https://user-images.githubusercontent.com/5086682/84388709-06d7cd80-abc3-11ea-979a-751214fc5e9a.PNG)

**Version**
0.1002.0

**Comment by Regalis11** [comment]
This is intentional. There are ways to get those ores: flood the room, use explosives, mine it from the other side of the wall...

**Comment by Kaillera** [comment]
I tried cutting from above, but the floor was rock solid despite 0 HP. I tried cutting the sides, but no water was getting in.
