### ISSUE TITLE
[Unstable 0.1002.0.0] Handheld Sonar bugs

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3067]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Three issues:
1) Pressing (and holding) interact (E) drains the battery of a Handheld Sonar when set to "active sonar"
2) When the battery is drained or there is no battery in the Handheld Sonar, "passive sonar" still works
3) A Handheld Sonar that has never been set to "active sonar" will show "passive sonar" when set to "active sonar" when the battery is removed.

**Steps To Reproduce**
For issue 1:
Turn on Active Sonar on a Handheld Sonar
Press (interact) E

For issue 2:
Drain the battery or place an empty battery in the Handheld Sonar
Set to Passive Sonar

For Issue 3:
Take a Handheld Sonar that has never been set to "active sonar"
Remove the battery
Set to "active sonar"

**Version**
Unstable 0.1002.0.0 revision 07ef298dd
Windows 10 64-bit

**Additional information**
See attached videos (videos were recorded in a Multiplayer mission)

Issues 1 and 2:
https://www.dropbox.com/s/vx9t232q9qbkcqk/Handheld%20Sonar_battery%20drain_working%20passive%20sonar.mp4?dl=0

Issues 2 and 3:
https://www.dropbox.com/s/1323w13m8pug3dl/Handheld%20Sonar_no%20battery_passive%20works_both%20modes.mp4?dl=0

**Comment by Regalis11** [comment]
The last 2 are intentional, issue 1 fixed in https://github.com/Regalis11/Barotrauma-development/commit/33ab57fe507f927e8bc3491c2f74cf1ee15d3f8d

**Comment by Rokvach** [comment]
No issues, closing.
