### ISSUE TITLE
[0.1002.0.0] Saving preview image of the submarine failed

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3068]
**Description**
This thing poped up when i tried to save Berilia submarine edit.

**Steps To Reproduce**
1. Open Game
2. Click on "Submarine editor"
3. Click on "Open..."
4. Select "Berilia"
5. Click on "Save"
6. Rename submarine to something else
7. Click Save

**Version**
0.1002.0.0 Windows (The unstable one).

**Image of Error**
![sub image failed](https://user-images.githubusercontent.com/32136089/84393563-6904f280-ac04-11ea-8b77-98569893f990.png)

**Comment by Regalis11** [comment]
Unfortunately I wasn't able to reproduce this.

**Comment by Camper125Lv** [comment]
Odd, i tried it a few times and it did it every time. Later, when i get home gonna try again. This wasn't anything game breaking of course, just extra f3 i needed to press.

**Comment by Camper125Lv** [comment]
Now it doesn't happen to me too...
