### ISSUE TITLE
Water Physics Teleportation via Ruin

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3069]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you put your airlock door against a ruin entrance and have a character open the door and swim through it, several weird flush/teleportation things happen with the character.

![Capture](https://user-images.githubusercontent.com/5086682/84394268-b5334100-abca-11ea-8193-909a50fa8820.PNG)
![](https://cdn.discordapp.com/attachments/668819422919524352/720640152145363014/Capture.PNG)

The water pushed me out and past the ruin wall towards my coil gun for one instance. Another instance, my character was teleported 4000m away from the sub.

**Version**
0.1002.0

**Comment by Kaillera** [comment]
Erm. So I teleported my character back to the ruins. This happened:

https://youtu.be/oHM_Owg7m-Q

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/970f393a19073969824ab9f18eaddb6c37bc04d8

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, looks to be working correctly. Closing.
