### ISSUE TITLE
[0.1002.0] Failed to generate an outpost without overlapping modules

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3070]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

![Capture](https://user-images.githubusercontent.com/5086682/84398643-34764400-abce-11ea-9bde-f224c567ef89.PNG)

[Save.zip](https://github.com/Regalis11/Barotrauma/files/4765441/Save.zip)

**Version**
0.1002.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a049cff861c218211c69adeaa6c532314942885

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Regalis11** [comment]
Broken again in 7ad81b2

**Comment by Jlobblet** [comment]
Error present in this save, at Phocis Flexus [Mining Claim] (saved location).
Level seed: `Phocis Flexus`.
Campaign seed: `Rhbx3tEb`.
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/4781277/Save.0.zip)

**Comment by Regalis11** [comment]
Did some fixes to the mine modules (https://github.com/Regalis11/Barotrauma-development/commit/bac6e85cf2429b2a0263b41892b80ba302a15cad) and couldn't get this to happen anymore, let's see if the problem still reappears

**Comment by Rokvach** [comment]
No reports of this happening during 1004 build, looks to be working correctly, closing.
