### ISSUE TITLE
When generating submarine preview for saving, item highlighted by mouse is also included

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3071]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When generating submarine preview for saving, item highlighted by mouse is also included

**Version**
<0.1002.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/94d463a81e54d453796a0d8efbbcd6e12adf113a

**Comment by Rokvach** [comment]
No issues, closing.
