### ISSUE TITLE
[0.1002.0] Did not get Clown Relation Increase in "Clown Relations 1" Event

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3075]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I ran into "Clown relations 1" event and chose the options to increase Clowns reputation. I got the reduction hit in the outpost but did not get increase for Honkmother (Ran through the event 3 times, still at -5).

Option text="EventText.clownrelations1.o1.o2"
SpawnAction itemidentifier="bikehorn" targetinventory="triggerer_player" 
**ReputationAction targettype="Faction" targetidentifier="clowns" increase="30"** (Didn't get this)
ReputationAction targettype="Location" increase="-20"
ConversationAction text="EventText.clownrelations1.o1.o2.c1" 

**Version**
0.1002.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ae934a0

**Comment by Rokvach** [comment]
No issues, closing.
