### ISSUE TITLE
[0.1002.0] Multiplayer - Reputation should be unique to each player

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3078]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Out of the concerns of griefers, I think it's easy for them to crash the reputation of the entire crew when the innocent crew aren't involved. Reputation should be unique to each player.

I believe that in Multiplayers, players should each get their own reputation event at the outpost as well. Events such as "Clown Relations 1" or Vent Breaches would be first come first serve.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.1002.0

**Comment by Regalis11** [comment]
Imo this would pretty much defeat the purpose of reputation: it'd be possible to for example coordinate the events in a way that each player has a high reputation in a different faction, so the crew could essentially have a high reputation among all factions.

**Comment by ezjamsen** [comment]
Yep. Agreed. I'd like to revisit this topic in the future, perhaps, but the system as it stands is what we'll most likely need to take to 1.0
