### ISSUE TITLE
Railgun Controller implemented power_in but has no components that utilize power

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#308]
Version 0.8.0.4

The railgun controller has no PowerTransfer components, Of the components it does have:

- Controller (Does not implement any Power_In and is of type ItemComponent)
- ConnectionPanel (Also of itself does not implement Power_In and is also of type ItemComponent)

ItemComponents do not implement power_in either, making this a redundant connection.

**Comment by Regalis11** [comment]
Unfortunately this is pretty hard to fix without breaking the wiring on existing subs, but we've now replaced the railgun controlled with a general-purpose periscope item that doesn't have the unnecessary power connection. The old railgun controller will be kept as a legacy option to keep backwards compatibility with older sub files.
