### ISSUE TITLE
[0.1002.0] ID Cards tag issues between switching Submarines

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3083]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Example: Starting out with the Typhon2, the Captain and Security are assigned "idcaptain" and "idsecurity". Switching over to the Humpback, the Captain and Security are not able to open the armoury because it now requires "id_captain" or "id_security".

**Version**
0.1002.0

**Additional information**
The tags for each member should probably be forced to refresh when switching sub (Although you'll need to keep track of their original ID card), or given a new ID Card.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4897bd92cb4863e16d4b025d048643ceb0aa0db

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
