### ISSUE TITLE
[Feature Request] Allow these items to fit into Toolboxes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3084]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I would like to request allowing these items to fit into Toolboxes:

-Harpoon Gun
-Harpoon/Physicorium Harpoon/Explosive Harpoon
-Syringe Gun
-40mm Grenade/40mm Stun Grenade
-Riot Shotgun

Been finding it annoying to loot these items from wrecks to bring back to sell.

**Version**
<0.1002.0

**Additional Informations**
Please at least let us put the syringe gun, 40mm grenade, and harpoons into them.

**Comment by MrTeco** [comment]
harpoon guns, harpoons and shotguns make no sense though

**Comment by Regalis11** [comment]
Tagged grenades and syringe guns as small items in https://github.com/Regalis11/Barotrauma-development/commit/f16f72e5ca4e07998d2fa75eb83f4229983d5496. I agree with MrTeco though: harpoon guns, harpoons and shotguns are so much bigger than a toolbox that I don't think it'd make sense to be able to put them inside one.

**Comment by MrTeco** [comment]
This is great then, we will be able to store more grenades.

**Comment by Rokvach** [comment]
No issues, closing.
