### ISSUE TITLE
Whenever headset gets disconncted the game sound breaks and I can't hear it anymore

### ISSUE THREAD

**Issue by boykin1** [Regalis11/Barotrauma#3087]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When my headset gets unplugged/disconnected while barotrauma is running the sound of the game will be permanently muted until I restart the game, and is there a Console command I can use to reload my audio device until you can fix this?

**Steps To Reproduce**
Try unplugging your audio device while the game is running.
**Version**
Most recent version and I use windows 10.

**Additional information**

**Comment by Regalis11** [comment]
@juanjp600 has this been addressed in https://github.com/Regalis11/Barotrauma-development/compare/feature/audio-output-selection?

**Comment by juanjp600** [comment]
Should be, moving to QA

**Comment by Rokvach** [comment]
Yeah already tested, working correctly. Closing.
