### ISSUE TITLE
Push to talk problem / error 40961

### ISSUE THREAD

**Issue by Yerko304** [Regalis11/Barotrauma#3088]
**Description**
does not allow voice chat to be activated
[](https://i.imgur.com/RxDLr22.png)
** Steps to reproduce **
I click to speak and the console appears saying errors and identifies it as error 40961
 
**Version**
v0.9.10.0 / window

**Comment by Regalis11** [comment]
@juanjp600 I'm assuming https://github.com/Regalis11/Barotrauma-development/tree/feature/openal-soft-diagnostics is related to this? Should this ticket be moved to "in progress"?

**Comment by juanjp600** [comment]
Moving to QA Todo, I'm expecting more thorough error reports as the most I've done has been add some logging

**Comment by Rokvach** [comment]
Closing as there hasn't been any reports about this for a while now
