### ISSUE TITLE
[0.1003.0] After purchasing many different items. When adding those same items into cart to buy more, the item removes itself from the cart.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3097]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This was during Multiplayer (Dedicated):
After purchasing many different items (Paid already). When adding those same items again into cart to buy more, the item removes itself from the cart. There was still a stock of 3.

Workaround: If you click fast enough to add into cart, it will add the amount you wanted but minus one.

**Version**
0.1003.0

**Comment by Kaillera** [comment]
In relation to this. Everytime I added the affected item, The merchant's balance keeps reducing by 4k, and then past 0, it goes to 65535 - whatever leftover from the previous subtraction.

**Comment by Kaillera** [comment]
Also my money increases by 4k everytime

**Comment by ekqvist** [comment]
Inability to purchase more of already purchased items should be fixed with Regalis/Barotrauma-development@69e89e7

**Comment by ekqvist** [comment]
I believe that the latter issue is the same as #3085 and should be fixed in Regalis11/Barotrauma-development@416f7bd

**Comment by Rokvach** [comment]
No issues, closing.
