### ISSUE TITLE
[0.1003.0] This outpost module's uses incorrect waypoint.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3099]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The two top waypoints on the ladder for this module isn't Ladder Waypoints.
![Capture](https://user-images.githubusercontent.com/5086682/84669076-6d762780-aef2-11ea-9b4d-5045e1563930.PNG)

**Version**
0.1003.0

**Comment by Regalis11** [comment]
It doesn't need to be because there's no ladder to the module above it.
