### ISSUE TITLE
 A toggle gate with output

### ISSUE THREAD

**Issue by dangranos** [Regalis11/Barotrauma#31]
Currently, only way to have a toggle function in wiring mechanisms is to use a door, or tons of elements, and neither solutions are acceptable when working with a small space on sub. What I would like to propose it to add another output for state on toggleable gates like light and relay gates, and perhaps a dedicated gate with only `toggle`, `reset` and `state` inputs and output.

**Comment by Regalis11** [comment]
The relay gate was mainly intended for this exact purpose, but now that you pointed it out the lack of a state output does make them quite a lot harder to use. And actually now that I checked, outputting the state has already been programmed, but for some reason the config file of the relay component is missing an output connection for the state (so it's just a matter of adding <output name="state_out"/> to the config).

The light component (and possibly some other toggleable items) could definitely use a state output too, thanks for the suggestion!

**Comment by dangranos** [comment]
Noticed that there is already a commit resolving this. Should this issue be closed?
