### ISSUE TITLE
Vellamo Flooding can flood gaps on the opposite side of the submarine from the breach.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#310]
Version 0.8.0.4

![image](http://puu.sh/zAjzO/bdb4881a0d.jpg)

This looks amusing to try to find, I was testing melee damage against walls and windows, cracking some glass using a wrench with damagerange and range added.

The note about this image is that the damage is to the top left of the top central corridor (At a small window, slightly breached), there is a stairwell directly down (And a gap, its the vanilla vellamo) - but its chosen to flood via the other gap first down the corridor. I imagine this just means changing the top corridor into three hulls instead of one but it felt worth pointing out it does this.

**Comment by CommanderMark** [comment]
Is it possible it's because the pump at the bottom-left of the sub is running while the ones at the bottom-right aren't?

**Comment by Regalis11** [comment]
I think this happens because the gaps work independently of each other - the gap on the right is most likely updated before the one on the left, causing it to drop all the water from the topmost room, leaving no water for the gap on the left. I think I've got to rework the gap logic quite a bit to solve this.

**Comment by NilanthAnimosus** [comment]
It's pretty much as regalis described, the pumps wouldn't be able to hold back that level of water if I had set them up. there is no logic to choose a gap "Closer to a breach" on the same hull, the water is simply inside the hull then a gap update likely empties the hull before the other gap can also cause this to flow, so once the update reaches the closer gap to the top left there is no water left in the hull.

Although not game breaking I just figured it was worth pointing out it had this behavior if larger hulls are used with multiple gaps.

**Comment by Rokvach** [comment]
There's been allot of improvements made for this so I don't see the point of keeping this open, closing.

**Comment by Regalis11** [comment]
This is still an issue even in the latest version, reopening

**Comment by Regalis11** [comment]
Fixed in v0.9.3.0
