### ISSUE TITLE
No audio output when using a USB connected audio device.

### ISSUE THREAD

**Issue by MikeBurnsDev** [Regalis11/Barotrauma#3101]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game has no audio output when using a USB connected audio device.

**Steps To Reproduce**
Plug in USB-3 Powered Audio Interface and attempt to run game. No audio is played at any point.
Once device is unplugged audio works ok.

**Version**
Windows 10
Dell G7 17 Laptop

**Additional information**
Tried disabling audio devices other than the USB one in sound manager. Updated driver. All other programs work w this device.

**Comment by juanjp600** [comment]
Potentially addressed in https://github.com/Regalis11/Barotrauma-development/commit/fe0c6a8e3409cd345a3b902734e2e3d71b18a7a9

**Comment by XT3RM1N8R** [comment]
What USB device is it?
I currently use a USB 2.0 Scarlett Focusrite 6i6 and do not experience any issues.
There may be some packaged audio software that runs on your PC that could be suspect here.
Additionally, if your USB audio device uses any software, please mention that, too!

**Comment by MikeBurnsDev** [comment]
It's a Behringer U-Phoria UMC404HD audio interface. It appears that the game is never finding the sound device because in the Windows audio mixer there is no displayed output from the game. When the audio interface is disconnected the audio plays on the internal speakers ok. I'll try to test on another machine in the future to help debug.

**Comment by Rokvach** [comment]
Tested with a headset I've always had difficulties for Baro to recognize and there wasn't any issues recognizing it. Closing.
