### ISSUE TITLE
0.1003.0.0 (Unstable): Missing Platforms from Mining Modules

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3102]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes platforms are missing modules. In this image, at the top of the ladder and on the hatch platforms are missing.
![image](https://user-images.githubusercontent.com/37539527/84677718-0a52b800-af27-11ea-8cf2-44dd312e7fcf.png)
Attached is the save:
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/4781421/Save.0.zip)
Level seed: `Falga`.
Campaign seed: `Rhbx3tEb`.

**Version**
Game version 0.1003.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision 7b3c34c2a).
Windows 10 version 1903.

**Comment by Jlobblet** [comment]
Having encountered this again, it appears to be to do with how `Mine_V_tunnel_01` joins with e.g. `mine_H_tunnel_01` - neither has a platform at the join. Probably the same for other instances of this.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bac6e85cf2429b2a0263b41892b80ba302a15cad

**Comment by Rokvach** [comment]
No issues, closing.
