### ISSUE TITLE
Multiple Locations Can Have the Same Base Name

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3103]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Locations can sometimes share their name with other locations.
Attached is an example save, which has no less than 3 locations with base name `Falga`.
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/4781446/Save.0.zip)

**Version**
Game version 0.1003.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision 7b3c34c2a).
Windows 10 version 1903.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/242d6023a6b5ea59411b73e3b14f9d847cb6853e

**Comment by Rokvach** [comment]
Tested, I did find two Milda named outpost, then a Milda Outpost and a Milda Station, but they were really spread out of each other and considering as the new map wont have as many outposts as the current map does I think it will be even less likely that you will ran in to a similar named outpost, also if this keeps to be a issue on the new map we should just add new location names then, closing as I think the distribution of same named outposts is now so spread out that you won't run in to another one in a single play through, closing.
