### ISSUE TITLE
0.1003.0.0 (Unstable): Very Hard to Read Outpost Conversations

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3105]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On outposts, conversations are frequently nigh impossible to read because of range.
For example: after stealing a fuel rod from a reactor:
![image](https://user-images.githubusercontent.com/37539527/84681936-ce225600-af2c-11ea-9725-037dec4fa5d4.png)
![image](https://user-images.githubusercontent.com/37539527/84681964-d67a9100-af2c-11ea-9121-436b7acab60a.png)
*all the NPCs are on the bottom floor in this engineering module 02*
Level seed: `Alkonost`.
Campaign seed: `SLQ3JLd7`.
Attached is the (multiplayer) save file.
[1003.3.save.zip](https://github.com/Regalis11/Barotrauma/files/4781609/1003.3.save.zip)

**Steps To Reproduce**
1. Go to an outpost.
2. Trigger an NPC conversation of any type from a different hull.
3. Attempt to read what they said without consulting the localisation and matching what you can.

**Version**
Game version 0.1003.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision 7b3c34c2a).
Windows 10 version 1903.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b3ecf5a490d4c24d8ab9499087e76283dcf8182a: having no direct line of sight doesn't garble the messages if the characters are in nearby hulls connected by open doors/gaps (which appears to be the situation in the screenshot).

Let's give this a test and see if it's enough or if we should take some additional measures (increased speaking range, making the NPCs communicate via radio)?

**Comment by Rokvach** [comment]
I think this is fine now, closing.
