### ISSUE TITLE
[Unstable, 0.1003.0.0] Cannot aim on ladders.

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#3106]
- [✔ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't aim on ladders

**Steps To Reproduce**
Simple, climb on a ladder, and aim with a weapon.
![4bOUVEYgfC](https://user-images.githubusercontent.com/65787528/84683573-43216b80-aeec-11ea-8ce7-23ccb70b0c5f.gif)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b7b40a2804e28e0fab9e779224696d764be4775e

**Comment by Rokvach** [comment]
No issues, closing.
