### ISSUE TITLE
Organ damage should probably only be displayed in the torso

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3107]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c4260695-ac3b-4ab9-a909-d248de8f7152)

**Comment by Jlobblet** [comment]
Potentially head as well? Brain damage seems a bit severe to treat with morphine, though.

**Comment by danielasteljoki** [comment]
Fixed in a97a2ae.

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by FamiliarBreakfast** [comment]
Skin is technically an organ, though brain trauma should really have it's own status effect
