### ISSUE TITLE
[0.1003.0] Unable to interact with Loose Vents

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3109]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to interact with Loose Vents.

**Version**
0.1003.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d99c7487b4204d459c8c7be2b0c200eeb86c0edf

**Comment by Rokvach** [comment]
No issues, closing.
