### ISSUE TITLE
Obscure Debug.assert with the physics library due to an area too small while loading a new multiplayer campaign

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#311]
Version 0.8.0.4

![image](http://puu.sh/zAl0e/9d4d6eefd0.png)

I don't even know about this one. its occurring in the cave generator. going to attach the save file but given the nature of my code I've no idea if this is reproducible on vanilla.

[Multiplayer Save.zip](https://github.com/Regalis11/Barotrauma/files/1778472/Multiplayer.Save.zip)

~~Sadly I've no idea to the seed / location picked etc, the server will have chosen at random.~~

Ok - It looks like it is the lower node (THE CITY OF YELLAND LINEA) causing the error in the cave generator.

The code in question (In cave generator) is:
```csharp
    if (Vector2.Distance(triangles[i][0], triangles[i][1]) < 0.05f ||
    Vector2.Distance(triangles[i][0], triangles[i][2]) < 0.05f ||
    Vector2.Distance(triangles[i][1], triangles[i][2]) < 0.05f) continue;
                    
    Vertices bodyVertices = new Vertices(triangles[i]);
    FixtureFactory.AttachPolygon(bodyVertices, 5.0f, cellBody);   // This is the line specified in the image above.
```

**Comment by Regalis11** [comment]
Seems that 756278b fixed this.
