### ISSUE TITLE
Can't use radio/text chat during map selection popup in MP campaign

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3111]
You can't discuss where to go. self explanatory. unsure if this happens with vc.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/952a80bd4d5ecb3fbcf3cd7aa5a3170265327d4c

**Comment by Rokvach** [comment]
Tested, no issues, closing.
