### ISSUE TITLE
[Unstable 0.1003.0.0] Crouching is broken after the implemention of the chair

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3112]
As you can see the hips are dislocated from the lower torso, might also be a good time to finally improve the crouching stance.
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/38044525-3bd8-4621-b5bb-a660dfa3d974)

**Comment by MrAsbestos** [comment]
Don't make them tip-toe btw
just sayin'

**Comment by Regalis11** [comment]
Improved the pose in https://github.com/Regalis11/Barotrauma-development/commit/1d1a303e07143aad71f1f277bbb086538a0431a8

**Comment by Rokvach** [comment]
Is it possible to move the behind leg down more when crouching so it touches the floor? @Regalis11 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e81e4bfc-04ef-4e00-8f18-6e9e5a7f50d8)

**Comment by itchyOwl** [comment]
It's possible to move the character down a bit. Perhaps we revisit this when we do another pass on the human animations?
