### ISSUE TITLE
Experience Gain doesn't appear in multiplayer

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3113]
Unsure if this is intentional, it's been a thing for quite a while. In singleplayer, you see the experience gain numbers show up whenever you gain experience at all in any way (like fixing things, shooting things, steering for a certian amount of time, etc). In multiplayer, it only shows up when you increase a level in experience.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d920d53d14b779e6174cd2ff6857cce3d4806370

**Comment by Rokvach** [comment]
No issues, closing.
