### ISSUE TITLE
[v0.9.10.0] Folder case-sensitivity issues for Workshop and Server/Client hashing.

### ISSUE THREAD

**Issue by naelstrof** [Regalis11/Barotrauma#3114]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
First off, Windows is case-insensitive to the point where tools like the Steam Workshop, and Git (with certain settings) can't detect if the folder name has updated casing, and doesn't update it. This prevents mod creators from updating folder casing since it won't actually propagate to users unless they delete their entire mod folder.

However, Barotrauma is case-sensitive in the Hash function, so even if their mod is working perfectly fine (due to not caring about case-sensitivity), the server will kick them for not having the correct hash.

**Steps To Reproduce**
Change the casing of a folder in a mod on the Steam Workshop, notice it doesn't update the casing for clients!
Barotrauma, and Linux is sensitive to these changes though, so a Linux server downloading the mod will have the correct folder casing, and kick all clients with the wrong casing out.

Any clients with the wrong folder case will get kicked with the error message `Missing content package. You need the content package "x". (hash XXXXXX)`

**Version**
v0.9.10.0, Steam, Windows (Client) and Linux (Dedicated server).

**Additional information**
Had a hard time figuring out why some of my friends could join the server, and others couldn't. Finally pinned it down on one of the mods updating the casing of a folder so that it works on Linux.
I'm sure this problem will happen again since it's pretty common for a mod creator to accidentally use the wrong casing, then updating it to work on Linux after people complain.

Not sure if this should actually be fixed, though it does cause a lot of mysterious issues for mod developers using typical version control systems (Steam workshop, git on windows).

**Comment by naelstrof** [comment]
Ugh, the github desktop app's config also has this setting as a default:
`git config core.ignorecase true`
Which made it even harder to debug. Darn windows for being case-insensitive!

**Comment by Regalis11** [comment]
Thank you for the very informative report and the pull request! We implemented a similar fix (although with a culture invariant conversion to lower case) in our private repo, and generally don't merge pull requests to our public repository because we do all the work in the private one, so I'll close the PR.
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a67a84aa5ee16431817596557e2ceb6eb78e46f

**Comment by Rokvach** [comment]
No issues, closing.
