### ISSUE TITLE
Available submarine syncing & setup UI for multiplayer campaign

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#3115]
Currently the server host's submarines are only shared if it's voted as an active submarine, and that is not exactly valid for how the campaign is supposed to work. Thus an available submarine selection UI is needed for the server lobby that is to be used together with the campaign to determine which submarines the clients need to download for the campaign to work properly.

Syncing also needs to be done when loading a campaign save for clients that don't have all the selected submarines

**Comment by Rokvach** [comment]
No issues, closing.
