### ISSUE TITLE
Logbooks arent detected by mission when placed inside a toolbox

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3116]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the logbook is placed inside a toolbox from the wreck cabinet the 'Data Retrieved' prompt that you collected the logbook does not happen.

**Steps To Reproduce**
Place the mission logbook from the cabinet in the wreck into a toolbox. 
No 'Data Retrieved' prompt will occur.
(If you move the logbook from the toolbox to your inventory, the prompt will occur.)

**Version**
Unstable 0.1003.0.0 revision 7b3c34c2a
Windows 10, 64 bit

**Additional information**
Video evidence link below:
https://www.dropbox.com/s/g8q1imc2ma5ly9w/Barotrauma%20Logbook%20Bug.mp4?dl=0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aaecd7b3d02484b3100de1931b7e21d062f72bca

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
