### ISSUE TITLE
[0.1003.0] No submarine seller outside of Colony?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3118]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if it's intentional that the submarine seller doesn't exist anywhere else but colony.

**Version**
0.1003.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2f06b6c

**Comment by Rokvach** [comment]
No issues, closing.
