### ISSUE TITLE
[0.1003.0] You can buy a sub you already owned. Doesn't give it a new .sub file

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3119]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can buy a sub you already owned. You can view the submarine terminal that there's two same sub, but It didn't gave it a new .sub file.

**Version**
0.1003.0

**Comment by EdusFF** [comment]
Should be fixed by other improvements to submarine syncing and equality check errors

**Comment by Rokvach** [comment]
No issues, closing.
