### ISSUE TITLE
Multiplayer - Battery-Relay-Item Power Desync

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3121]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During a multiplayer round, if you put down a relay, wire it up to draw power from battery,  turn on the relay, wire particular things up to them and remove the power wire from the old junction boxes. Certain items will desync and act as if there was no power, or it doesn't work as if there was no power:

Fabricator - Will complain there is no power ~~until you unhook the power wire from itself and rehook it back on.~~
Deconstructor - Will complain there is no power ~~until you unhook the power wire from itself and rehook it back on.~~
Navigation Terminal - Will not be able to move the sub. Ballast pumps water level will fluctuate on client end, but doesn't actually affect buoyancy.

**Version**
~0.10.5.1

**Additional information**
If you're able to transition to another level after wiring them up to relay, they will sync properly from then on.

**Comment by Kaillera** [comment]
Pumps are also affected. You will see water rise and fall rapidly.

**Comment by Kaillera** [comment]
Still exists

**Comment by Regalis11** [comment]
Possibly fixed in Regalis11/Barotrauma-development@0059175

**Comment by Kaillera** [comment]
Tested and Working in 0.1100.0.4

**Comment by Rokvach** [comment]
Closing.
