### ISSUE TITLE
Instruments Clash Terribly

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3124]
[Issue, Thinly Veiled Feature Request]
Now that the background music is actual music, the ingame instruments clash terribly against the background music. It would be nice if there were a tag you could add to a sound like
<Sound path="blahblah" suppressbgm="true" range="500" ...>
that would significantly lower the volume of the background music for anyone within the sound range.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
