### ISSUE TITLE
Unstable - Still getting duplicate missions and duplicate events at outposts

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3126]
**Description**
I have done an event and mission and returned to outpost only to encounter the exact same event and mission.
**Steps To Reproduce**
Dock back at the same outpost after finishing or failing your mission. Failing the mission gave me duplicate mission. Event was exactly the same in the same spot.

**Version**
Unstable

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/03e8c26a9b204b46f2238fbe68178961c7a7daca

**Comment by Rokvach** [comment]
Tested, wasn't able to get duplicate events and duplicate missions after finishing a mission and returning to the same outpost. Closing.
