### ISSUE TITLE
Unstable - Performance significantly worse in levels

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3127]
**Description**
I have 60FPS in outposts and while docked during mission. It suddenly drops to about 15 after traveling some distance and mostly stays there. I suspect it's monster events. Performance gets even worse near wrecks, where it drops to about 8FPS.

**Specs**
W7
AMD FX-4300
R7 370
16GB Ram
After silky smooth update the game ran at about 40-60 FPS, even when swarmed.
**Version**
Unstable

**Additional information**
Probably related to
https://github.com/Regalis11/Barotrauma/issues/2951
https://github.com/Regalis11/Barotrauma/issues/2985

**Comment by Regalis11** [comment]
Performance seems to be much better in the latest unstable build, closing
