### ISSUE TITLE
Unstable - Husk eggs break economy

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3128]
**Description**
Husk eggs are very easy to come by (2x per husk) and each sells for 1200! marks. Killing and looting 2 or 3 husks means you can get all Mks of an outpost.

**Steps To Reproduce**
Hunt husks, get stonks

**Version**
Unstable

**Comment by danielasteljoki** [comment]
Fixed in 099701d and 2861e12. No more egg based economy.

**Comment by Rokvach** [comment]
No issues, closing.
