### ISSUE TITLE
Unstable - Crash due to ragdoll

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3130]
**Description**
Game crashed after shooting a crawler with a shotgun. Ancient bug.
**Steps To Reproduce**
Shoot enough crawlers until it happens

**Version**
Unstable

**Additional information**
Crash log
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/4795350/crashreport.4.log)

**Comment by Regalis11** [comment]
Are you sure this is the correct crash report? It seems that the crash happened when trying to place a character with no feet on ladders. Not sure how exactly that can happen; I guess the feet got severed off, but at that point the character should've been dead and not climbing the ladder.

But in any case, I added some checks in https://github.com/Regalis11/Barotrauma-development/commit/0383ec6d6e90333721324bd7e08743b705e1c6bd that should prevent this from happening again.

**Comment by Udrakan** [comment]
I've doublechecked if it's the correct crashreport and yes, it should definetly be it. Now that I recall, I was shooting a shotgun at crawler while climbing a ladder in orca cargo room. I thought it's one of the crashes that occur at random while shooting crawlers or mudraptors with anything.

**Comment by Rokvach** [comment]
No issues, closing.
