### ISSUE TITLE
Pump - Option: "Is On"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3135]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Probably one of the biggest issue with sub building is when a majority of new sub makers does not know why their pumps aren't working. They all believe that pumps are on by default, and not have to "E" the pump and toggle it on from the interaction menu rather than the parameter menu.

**Version**
<0.1003.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/27a8d1157e92253b348c9cfe2d1f0d50d9305422

**Comment by Rokvach** [comment]
No issues, closing.
