### ISSUE TITLE
Adrenaline Gland is not placed inside a crate like other purchased supplies

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3137]
When you buy an Adrenaline Gland from the store at an outpost and leave the outpost, the Gland will be placed on the floor at the waypoint instead of being placed inside the Crate like other purchased items.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7778392877783c5ab5fd309fe6eb44e52c8c43a7

**Comment by Rokvach** [comment]
No issues, closing.
