### ISSUE TITLE
[Unstable 0.1004.0.0] Dugong ballast pumps aren't set to automatic

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3138]
Tested on 0.1004.0.0 Unstable

The automatic control light is on but you can still press power to turn the pump off

**Comment by danielasteljoki** [comment]
That's how it's supposed to work as far as I'm aware. Automatic control lights are on if 'set_speed' or 'set_targetlevel' on the pump are receiving a signal. Note that some other pumps (bilge pumps on vanilla subs at least) also receive a signal that turns them on if water is detected. This makes it seem that you can't turn them off if they're set to work automatically.

**Comment by Rokvach** [comment]
Apparently this isn't a issue, closing.
