### ISSUE TITLE
[Unstable 0.1004.0.0] Undocking from Outpost disconnects everyone

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3139]
Tested on Unstable 0.1004.0.0

Repro steps: 
1. Startup a multiplayer campaign
2. Unlock a mission by talking with a NPC
3. Undock from the outpost by either using the button on top right or directly from nav terminal
4. Select a mission
5. Start round
6. Mass disconnection

Doesn't seem to happen when no mission is selected

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/780268f4-4d72-4e50-9827-85c6e3a3e4e7)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1096a334629556cca2f903c019233f671030fa72

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore, working correctly. Closing.
