### ISSUE TITLE
[Unstable 0.1004.0.0] Red hand icon + red tooltip is missing from autofill items in the first multiplayer outpost

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3140]
Issue only happens in multiplayer

Repro steps:
1. Start up a multiplayer campaign
2. Walk to the nearest crew quarters
3. See that the items contained in the cabinets are missing the red hand icon and red tooltip

The red hand icon + red tooltip does appear in the next outpost

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a8228eaa-35a5-4c9c-8f41-6fc08f859dff)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bac5eac8fa67a7f67bbc94ad0eb05bd2758b2b79

**Comment by Rokvach** [comment]
No issues, closing.
