### ISSUE TITLE
Missions without a defined icon crash the tab menu

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#3142]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reported by Dorf#1234 on Discord.

**Steps To Reproduce**
- Install a mod that adds mission types without icons (ALIEN - Xenomorph-Fix meets this criteria)
- Start a Monster mission that's defined in the mod
- Open the tab menu and try looking at the mission details

**Version**
v0.9.10.0

**Additional information**
User's game failed to generate a crash report due to a bug fixed in https://github.com/Regalis11/Barotrauma-development/commit/06c83deb1f511a2c7645e35d611a024c67ec6587.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/149832530685d770a603f9d69523aa5df7cb561c

**Comment by Rokvach** [comment]
No issues, closing.
