### ISSUE TITLE
Failed to connect waypoints between outpost modules.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3145]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/85072534-44ba9000-b187-11ea-8741-17d892fb54b4.PNG)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/4801197/Save.zip)

**Version**
0.1004.0

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/85091814-56675c00-b1b6-11ea-8e52-3815148a0f39.PNG)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/4802216/Save.zip)

**Comment by Rokvach** [comment]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0537d0ac-9ba7-4713-bd14-c198889a9be0)

**Comment by danielasteljoki** [comment]
Can't find the problem anymore. Probably resolved in an earlier commit somewhere.

**Comment by Rokvach** [comment]
Found one of these in a mining outpost

1. Open up level editor
2. Select outpostlevel
3. Select miningoutpost
4. Use seed srewt34df

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/32a9e045-3268-4054-becd-c9cbce6fdb19)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@ae329e1.

**Comment by Rokvach** [comment]
Looks like that was all of them, closing.
