### ISSUE TITLE
Multiplayer Campaign syncing issues + A few other issues.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#315]
There seems to be a lot of issues with multiplayer campaign syncing issues beyond the normal syncing issues of the game.

Upon trying to host and manage a server using my mod, I was having a lot of problems with this.

And after investigating I do not think the server properly syncs its save files with the clients (Or at least register new campaigns or campaign switching perhaps).

If one exits an existing campaign and starts a new campaign using the same savename on vanilla copies of the game, it will load the incorrect submarine for the clients - a rejoin will also result in disconnect from excessive desync.

![image](http://puu.sh/zBgbN/ca3328f9ef.jpg)

I believe this could be due to this code in GameClient Filetransfertype.CampaignSave but I barely understand where most of this is handled:
```
if (GameMain.GameSession.Submarine == null)
                    {
                        var gameSessionDoc = SaveUtil.LoadGameSessionDoc(GameMain.GameSession.SavePath);
                        string subPath = Path.Combine(SaveUtil.TempPath, gameSessionDoc.Root.GetAttributeString("submarine", "")) + ".sub";  
                        GameMain.GameSession.Submarine = new Submarine(subPath, "");
                    }
```

If changing the submarine with the above, if it still has the previous listed then the submarine loaded is incorrect, This does need to also compare that the submarine is of a different name than the received at least. the above is at the very least responsible for the save utilities cleaning of the save folder for a given submarine type on the client side.

Changing to sandbox/mission does not remove the "Campaign View" button (That might be part of a larger issue too) which continues to work showing the features of campaign (Such as the buy menu or the map)

When a submarine on campaign is not for the current content package - its popup for whether to use it or not will appear behind the campaign UI

**Comment by Regalis11** [comment]
Probably still more campaign syncing bugs to go but I think these specific ones are now fixed.

**Comment by NilanthAnimosus** [comment]
I was creating code that automatically changed the campaign (By switching the game mode then switching back), increment save files to perform a reload and ensure a client was sent the save file despite not being a new save (I found campaign carried over failed games submarines) while also auto repairing and automatically buying new items for new and existing campaigns with all the settings and logic to go with it, took me a good 800 lines of code (I'm so making that shorter next time).

In the next version I'll adapt my code for the new campaign syncing logic. then I'll see if there's more syncing issues and examine the vanilla code of those issues.

Be nice if we get a version when possible with a number of these changes in the current github, Assuming the current github code is stable (I've not been playtesting it),

In public multiplayer for 0.8.0.4 on vanilla, many submarines have no lights internally or externally (Relays) or even move properly with low-power relay engines (IE. respawn shuttles). dedicated have containers you cant open and railguns that fire incorrectly, object header issues, LOS performance problems, voting problems, crashes giving few error details.

As I understand it though, linux might be incompatible on LOS right now?

**Comment by Regalis11** [comment]
I'll do some more testing today and if I don't spot any major issues I'll upload a patch in the evening.

I hadn't compiled the game on Linux yet and hadn't noticed the errors before, but those were easy to fix so the should be no problem with the Linux build.
