### ISSUE TITLE
[0.9.10.0] Bad desync trying to unweld a door while being attacked.

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#3151]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://streamable.com/hxm0ss

**Comment by Regalis11** [comment]
I think what happened here is that the door was stuck server-side, but usable at your end. I did some improvements to the way the stuck-state of the door is synced; https://github.com/Regalis11/Barotrauma-development/commit/3a00045f9a695a4d28b3aad9da8cc679ec4d7764 should fix this.

**Comment by thegrb93** [comment]
@Regalis11 and idea that crossed my mind is maybe after being attacked and getting knocked back from the attack, the cutting tool doesn't activate again serverside unless you click the mouse again despite it showing as working in clientside. Could be wrong though/

**Comment by Rokvach** [comment]
There hasn't been any encounters to this during Unstable testing, seems to be working correctly. Closing.
