### ISSUE TITLE
Feature Request: Hide Psychosis Affliction From Affected Player

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3152]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hiding the psychosis affliction from the affected player would help make psychosis a more interesting (and realistic*) affliction. This would mean that players would rely on either working out they are suffering from psychosis or another player diagnosing it, rather than just reading it off the affliction list.

**Comment by itchyOwl** [comment]
Closing the ticket, as it's done.
