### ISSUE TITLE
[0.1004.0] Selling items price inaccurate when sold

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3154]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I just arrived to a Military Outpost and decided to sell some items.

Here I should've gotten 2,023 Marks for these items.
![Capture](https://user-images.githubusercontent.com/5086682/85178366-4e59fb80-b24c-11ea-9f25-929a96017178.PNG)

![Capture](https://user-images.githubusercontent.com/5086682/85178427-747f9b80-b24c-11ea-8fbf-f3495e2ca2c2.PNG)

I only got 1,185 from them instead. Every transactions did the same.

**Version**
0.1004.0

**Additional Informations**
I did helped some Seperatist before I sold stuff.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@c1d73f3. The amount of items being sold wasn't taken into account on the client's end (or at all in singleplayer) when calculating the total sell value so you would only get the money for 1 of each item, even if you sold multiple at a time.

**Comment by Rokvach** [comment]
No issues, closing.
