### ISSUE TITLE
[Unstable 0.1004.0.0] Refreshing server list throws an error

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3156]
Repro steps:
1. Open up server browser
2. See that there's a server on the list, if you don't see any then toggle the "Same version" filter off
3. Press "Scan servers" and the error should come up

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1e1935c5-cf22-4279-b4c8-10ec621b9e36)

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9d5d3390fdd05a483420fcc31b917a3c732e6551

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Looks to be working correctly, closing.
