### ISSUE TITLE
1004: Fadetoblack doesn't seem to work during multiplayer

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3163]
[Bug]
In addition to being able to run around during events, fadetoblack doesn't seem to work in the husk communion event in 1004. (The screen does not fade to black) should be easy to reproduce

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07d02b765f5d4da4a93e1bca54dc56d2b4236cf1

**Comment by Rokvach** [comment]
No issues, closing.
