### ISSUE TITLE
[Unstable 1004] Water does not slow you down

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#3164]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No matter the level of the water, it doesn't slow you down.

**Steps To Reproduce**
Have a room filled with water that you are able to walk in.

**Additional information**
I made a video comparison here, water is at the highest level where you are able to walk (You can even see the character drowning when he starts to run), If I am not wrong I made it almost frame perfect, this issue is in every version of the game (Steam Release).
![video0](https://user-images.githubusercontent.com/65787528/85208855-71d28400-b2e8-11ea-819c-9470a4411cfb.gif)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/397a6f9f3bd84e8596c265821c32e67aab6fd4dd

**Comment by Rokvach** [comment]
No issues, closing.
