### ISSUE TITLE
[Unstable 0.1004.0.0] If you join a server when map is open you will have access to select missions

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3165]
Its either when you join a server when the map is open or when playing as a spectator

**Comment by Regalis11** [comment]
Steps to repro? Couldn't get this to happen by doing the following:
1. Host a campaign, undock the sub to force the map to open
2. Start another client with no permissions, join the server as a spectator
3. The map pops up, and the mission selection and the start button are disabled

**Comment by Regalis11** [comment]
No known steps to repro and no other reports about this, closing for now
