### ISSUE TITLE
[Unstable 0.1004.0.0] Wreck door keeps constantly opening/closing

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3167]
Noticed on the wreck which resembles Remora

Not sure if this is intentional design but I bet it can't be good for server to keep track on the doors state constantly

Video:
https://streamable.com/r95olt

**Comment by danielasteljoki** [comment]
Fixed in c09541f.

**Comment by Rokvach** [comment]
No issues, closing.
