### ISSUE TITLE
[Unstable 0.1004.0.0] Mission related items aren't removed after entering a outpost

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3169]
Noticed on multiplayer campaign

So far seen comments on Discord about artifacts and explosive cargo not being removed after completing a mission

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/685f9f1d2f30edfce46b9e36a77dfcfbce2dafa9

**Comment by Rokvach** [comment]
No issues, closing.
