### ISSUE TITLE
Lithium does not explode in water, despite being an alkali metal

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#3170]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Lithium, along with all alkali metals, reacts violently in water. However, unlike all other alkali metals in this game, it does not react with water at all.

**Steps To Reproduce**
1. Put lithium in water
2. Notice how it doesn't explode

**Version**
v0.9.10.0 Linux, though it affects all OSes
- Have not tested on unstable, though I see no reason why it would be different

**Additional information**
https://en.wikipedia.org/wiki/Lithium#Chemistry_and_compounds
In small amounts, lithium will violently bubble away, though in large quantities the heat will ignite the hydrogen gas and explode.

**Comment by Solbusaur** [comment]
Same applies for calcium, being a group 2 element. Not as reactive (I don't think it should combust at all, but rather just disappear with some smoke effects following it for gameplay reasons) but is affected all the same by water.

**Comment by FamiliarBreakfast** [comment]
Which is interesting, because magnesium in this game explodes in water, and, despite being a group two element, it reacts slowly enough that it's almost invisible to the naked eye: https://www.youtube.com/watch?v=u_1uLP30uxY

Notice how in the video it barely bubbles, though I suspect this is at least partially due to an oxide layer forming from storage in air.

**Comment by ezjamsen** [comment]
For some reason sodium also doesn't react with water. How embarrassing. Sodium and lithium now explode in water, magnesium causes less burn damage to compensate for it not being all that reactive.

**Comment by Rokvach** [comment]
No issues, closing.
