### ISSUE TITLE
[Unstable 1004] Cutscene getting skipped

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#3171]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you hang out too much in the loading screen the cutscene is skipped.

**Steps To Reproduce**
Wait for the game to load and when it says "Press any button to continue" wait for some seconds, around 10 or 15, then hit any button and the cutscene is skipped.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1309be8cf59b3a7a57f0f8f0bceff61c7be57ca2

**Comment by Rokvach** [comment]
No issues, closing.
