### ISSUE TITLE
Shell A 42 sprite is not correct

### ISSUE THREAD

**Issue by AndrewDawnbringer** [Regalis11/Barotrauma#3173]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shell A 42's sprite is not correct, because the player is not able to align it with other shell pieces.

**Steps To Reproduce**
Launch title, launch submarine editor, place a Shell A 42 piece and try to line it up with other Shell A pieces.

**Version**
v 0.9.10.0

**Additional information**
Check the attached screenshot
![a42](https://user-images.githubusercontent.com/14193735/85228505-0077fb80-b3e4-11ea-8d92-59767727b219.PNG)

**Comment by Regalis11** [comment]
I don't think we should change this wall piece at this point, because it'd cause it to get misaligned in older subs and cause alignment issues with other wall pieces. It's possible to nudge the pieces with arrow keys, I wouldn't consider this is a big issue.
