### ISSUE TITLE
[0.9.10.0] The ability to see the contents of the secure metal crate, which requires a special pass

### ISSUE THREAD

**Issue by pabimuri** [Regalis11/Barotrauma#3178]
I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you use crate shelf, you can see what inside of the closed secure metal crates by swapping it with opened

**Steps To Reproduce**
1) Put in the crate shelf one random metal crate that you can open
2) Put in the same shelf secure metal crate, that you cant open because you have no speciall pass
3) Grab the crate №1
4) Swap it with the crate №2

**Version**
[0.9.10.0], Win

**Additional information**
1) https://steamuserimages-a.akamaihd.net/ugc/1245757231527963124/7D957B843B44248BFB73BE05F4D1F5C0978043CE/
2) https://steamuserimages-a.akamaihd.net/ugc/1245757231527963800/405BF2519117C4625EFBE5747FD52EAB8F60A106/
3) https://steamuserimages-a.akamaihd.net/ugc/1245757231527964093/9950F98820E620D20DE78E9434A68ACB4C003F2E/

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d81dbbb9aeaa23d9f50d69161837b375a737165a

**Comment by Xeavas** [comment]
[0.1200.0.2] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing.
