### ISSUE TITLE
[0.9.10.0] Limbs "OnSever" StatusEffect only applies randomly.

### ISSUE THREAD

**Issue by naelstrof** [Regalis11/Barotrauma#3180]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a limb gets severed, characters only sometimes get their Limb's OnSever StatusEffect applied. 

**Steps To Reproduce**
I've determined that it's because it only ApplyEffects on one of the two possible limbs after sever. An already-severed limb doesn't apply the effect to the character. So it's a coinflip if a character gets a devastating amputation affliction or they just shrug it off.

**Version**
0.9.10.0

**Additional information**
My naive fix can be found here: https://github.com/naelstrof/Barotrauma/commit/5c545ec5074f157e5fda8abe93f3b492d89fb673

**Comment by naelstrof** [comment]
My naive fix didn't work in some cases, moving the ApplyStatusEffects to before the limb was disabled in Ragdoll.cs seems to have fixed the issue.

Just the two lines here was all that was needed:
https://github.com/naelstrof/Barotrauma/commit/5e56c6e54b2fa1b347b97a3050233acd2075aee9#diff-90880f40a3b6b2a7ec65307c6c3ab163R812

**Comment by Regalis11** [comment]
Thank you for an exceptionally informative bug report. :) Fixed in https://github.com/Regalis11/Barotrauma-development/commit/40ab83185558915ee1a54180f56cec4d34af41fb

**Comment by Rokvach** [comment]
No issues, closing.
