### ISSUE TITLE
Crash when traveling from a natural formation in to a breeding ground

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3181]
Tested on multiplayer campaign

I was testing the issue related to entering natural formations with a mission and came across this, there was a line of 2 natural formations and a breeding ground at the end. I traveled through the natural formations with teleportsub end command and once I entered the breeding ground my game crashed.

Save: https://app.zenhub.com/files/175046454/a0aa5d41-391d-49d2-8808-e640ef7ae692/download

On the save travel this path using teleport sub and the game should crash when you click the breeding grounds

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9605d939-6b8e-41cc-a926-382ae8addc23)

To breeding grounds
> ![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/eefb0f04-0908-4932-b065-aba3daa38271)
> 
> ```
> Barotrauma Client crash report (generated on 22.6.2020 12:34:10)
> 
> 
> Barotrauma seems to have crashed. Sorry for the inconvenience! 
> 
> 
> 9346DF122A863831AC895B82C3AB72F4
> 
> 
> Game version 0.1004.0.0 (ReleaseWindows, branch feature/campaign-groundwork, revision 9f6b28b89)
> Graphics mode: 2560x1440 (BorderlessWindowed)
> VSync OFF
> Language: English
> Selected content packages: Vanilla 0.9
> Level seed: Rhadamanthys LineaMehen Linea
> Loaded submarine: Dugong (3902A7EF0B6B99694D71EDE338221228)
> Selected screen: Barotrauma.GameScreen
> SteamManager initialized
> Client (Round had started)
> 
> 
> System info:
>     Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
>     GPU name: NVIDIA GeForce GTX 980 Ti
>     Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
>     GPU status: Normal
> 
> 
> Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
> Target site: TransitionType GetAvailableTransition(Barotrauma.LevelData ByRef, Barotrauma.Submarine ByRef)
> Stack trace: 
>    at Barotrauma.CampaignMode.GetAvailableTransition(LevelData& nextLevel, Submarine& leavingSub) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 233
>    at Barotrauma.CampaignMode.get_CurrentDisplayLocation() in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 110
>    at Barotrauma.Map.Update(Single deltaTime, GUICustomComponent mapContainer) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 342
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at Barotrauma.GUI.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 0
>    at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 981
>    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
>    at Microsoft.Xna.Framework.Game.Tick() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
>    at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
>    at Microsoft.Xna.Framework.Game.Run() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
>    at Barotrauma.Program.Main(String[] args) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
> 
> 
> Last debug messages:
> [22.6.2020 12:34:07] Server command: teleportsub end
> [22.6.2020 12:34:07] teleportsub end
> [22.6.2020 12:34:04] test
> [22.6.2020 12:33:53] test
> [22.6.2020 12:33:43] Server command: teleportsub end
> [22.6.2020 12:33:43] teleportsub end
> [22.6.2020 12:33:38] test
> [22.6.2020 12:33:35] Generating an outpost for the start of the level... (Location: Mehen Linea, level type: LocationConnection)
> [22.6.2020 12:33:30] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:33:30] (Msg) Ping location: sto2=15+1,sto=16+1/15+1,fra=42+4/34+1,ams=39+3/35+1,waw=59+5/36+1,lux=48+4/38+1,lhr=47+4/39+1,par=53+5/44+1,vie=50+5/46+1,iad=131+13/120+1,sgp=211+21/212+21,gru=243+24/263+1
> [22.6.2020 12:33:30] (Msg) Ping measurement completed
> [22.6.2020 12:33:25] test
> [22.6.2020 12:33:25] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:33:25] (Msg) Refreshing ping measurements
> [22.6.2020 12:32:27] test
> [22.6.2020 12:32:25] Failed to connect waypoints between outpost modules. No waypoint in the right gap of the module "AdminModule_01R".
> [22.6.2020 12:32:25] Generating an outpost for the start of the level... (Location: Molovsk, level type: Outpost)
> [22.6.2020 12:32:21] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:32:21] (Msg) Ping location: sto=16+1,sto2=16+1,fra=43+4/35+1,ams=41+4/36+1,waw=59+5/37+1,lux=48+4/38+1,lhr=47+4/40+1,par=53+5/45+1,vie=50+5/47+1,iad=129+12/121+1,sgp=210+21/211+21,gru=244+24/264+1
> [22.6.2020 12:32:21] (Msg) Ping measurement completed
> [22.6.2020 12:32:16] test
> [22.6.2020 12:32:16] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:32:16] (Msg) Refreshing ping measurements
> [22.6.2020 12:31:35] Server command: teleportsub cursor
> [22.6.2020 12:31:35] teleportsub cursor
> [22.6.2020 12:31:04] Server command: teleportsub end
> [22.6.2020 12:31:04] teleportsub end
> [22.6.2020 12:31:03] Server command: enablecheats
> [22.6.2020 12:31:03] enablecheats
> [22.6.2020 12:31:01] Enabling cheats will disable Steam achievements during this play session.
> [22.6.2020 12:31:01] You need to enable cheats using the command "enablecheats" before you can use the command "teleportsub".
> [22.6.2020 12:31:01] Server command: teleportsub end
> [22.6.2020 12:31:01] teleportsub end
> [22.6.2020 12:30:52] test
> [22.6.2020 12:30:50] Generating an outpost for the end of the level... (Location: Molovsk, level type: LocationConnection)
> [22.6.2020 12:30:50] Generating an outpost for the start of the level... (Location: The city of Binnsmouth, level type: LocationConnection)
> [22.6.2020 12:30:45] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:30:45] (Msg) Ping location: sto2=15+1,sto=16+1/15+1,fra=43+4/34+1,ams=40+4/35+1,waw=57+5/35+1,lux=47+4/38+1,lhr=47+4/39+1,par=52+5/44+1,vie=50+5/47+1,iad=128+12/120+1,sgp=210+21/211+21,gru=244+24/263+1
> [22.6.2020 12:30:45] (Msg) Ping measurement completed
> [22.6.2020 12:30:41] test
> [22.6.2020 12:30:40] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:30:40] (Msg) Refreshing ping measurements
> [22.6.2020 12:29:19] test
> [22.6.2020 12:29:17] Generating an outpost for the start of the level... (Location: The city of Binnsmouth, level type: Outpost)
> [22.6.2020 12:29:06] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:29:06] (Msg) Ping location: sto=15+1,sto2=15+1,fra=43+4/34+1,ams=39+3/35+1,waw=58+5/35+1,lux=48+4/38+1,lhr=47+4/39+1,par=53+5/44+1,vie=50+5/46+1,iad=130+13/120+1,sgp=210+21/211+21,gru=244+24/263+1
> [22.6.2020 12:29:06] (Msg) Ping measurement completed
> [22.6.2020 12:29:02] Lobby created!
> [22.6.2020 12:29:02] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:29:02] (Msg) Refreshing ping measurements
> [22.6.2020 12:27:42] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:27:42] (Msg) Ping location: sto2=14+1,sto=15+1/14+1,fra=43+4/33+1,ams=39+3/34+1,waw=58+5/34+1,lux=47+4/37+1,lhr=47+4/38+1,par=52+5/43+1,vie=49+4/45+1,iad=129+12/119+1,sgp=210+21/211+21,gru=245+24/263+1
> [22.6.2020 12:27:42] (Msg) Ping measurement completed
> [22.6.2020 12:27:37] test
> [22.6.2020 12:27:37] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:27:37] (Msg) Refreshing ping measurements
> [22.6.2020 12:27:07] Error when receiving campaign data from the server: connection index for mission "killmoloch" out of range (2).
> [22.6.2020 12:27:04] Error when receiving campaign data from the server: connection index for mission "killmoloch" out of range (2).
> [22.6.2020 12:26:57] Error when receiving campaign data from the server: connection index for mission "killmoloch" out of range (2).
> [22.6.2020 12:23:54] Error when receiving campaign data from the server: connection index for mission "killmoloch" out of range (2).
> [22.6.2020 12:23:01] test
> [22.6.2020 12:23:00] Generating an outpost for the start of the level... (Location: The city of Binnsmouth, level type: Outpost)
> [22.6.2020 12:22:51] test
> [22.6.2020 12:22:35] Server command: teleportsub end
> [22.6.2020 12:22:35] teleportsub end
> [22.6.2020 12:22:28] Server command: enablecheats
> [22.6.2020 12:22:28] enablecheats
> [22.6.2020 12:22:16] test
> [22.6.2020 12:22:13] Generating an outpost for the start of the level... (Location: The city of Binnsmouth, level type: LocationConnection)
> [22.6.2020 12:22:13] Generating an outpost for the end of the level... (Location: Molovsk, level type: LocationConnection)
> [22.6.2020 12:22:08] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:22:08] (Msg) Ping location: sto=15+1,sto2=15+1,fra=44+4/34+1,ams=40+4/35+1,waw=62+6/36+1,lux=48+4/38+1,lhr=48+4/39+1,par=53+5/44+1,vie=50+5/46+1,iad=130+13/120+1,sgp=210+21/211+21,gru=243+24/263+1
> [22.6.2020 12:22:08] (Msg) Ping measurement completed
> [22.6.2020 12:22:03] test
> [22.6.2020 12:22:03] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (Refreshing ping measurements)
> [22.6.2020 12:22:03] (Msg) Refreshing ping measurements
> [22.6.2020 12:20:23] test
> [22.6.2020 12:20:19] Failed to connect waypoints between outpost modules. No waypoint in the right gap of the module "AdminModule_01R".
> [22.6.2020 12:20:18] Generating an outpost for the start of the level... (Location: Molovsk, level type: Outpost)
> [22.6.2020 12:19:58] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
> [22.6.2020 12:19:58] (Msg) Ping location: sto2=17+1,sto=19+1/17+1,fra=42+4/36+1,ams=40+4/37+1,waw=57+5/38+1,lux=47+4/40+1,lhr=46+4/41+1,par=52+5/46+1,vie=48+4/48+1,iad=127+12/122+1,sgp=209+20/210+20,gru=244+24/265+1
> [22.6.2020 12:19:58] (Msg) Ping measurement completed
> [22.6.2020 12:19:55] (Verbose) Communications with routing cluster 'syd' established.
> [22.6.2020 12:19:55] (Verbose) Communications with routing cluster 'tyo' established.
> [22.6.2020 12:19:55] (Verbose) Communications with routing cluster 'tyo1' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'scl' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'sgp' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'sea' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'man' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'lim' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'maa' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'hkg' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'lax' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'okc' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'waw' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'vie' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'gru' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'ord' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'jnb' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'sto' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'sto2' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'eat' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'bom' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'mad' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'par' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'dxb' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'lux' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'lhr' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'atl' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'iad' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'fra' established.
> [22.6.2020 12:19:54] (Verbose) Communications with routing cluster 'ams' established.
> [22.6.2020 12:19:54] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
> [22.6.2020 12:19:54] (Msg) Performing ping measurement
> [22.6.2020 12:19:54] (Msg) Got SDR network config.  Loaded revision 276 OK
> [22.6.2020 12:19:54] Lobby created!
> [22.6.2020 12:19:54] (Verbose) Service thread running.
> [22.6.2020 12:19:54] (Msg) RelayNetWorkStatus:  avail=Attempting  config=Attempting  anyrelay=Waiting   (Attempt #1 to fetch config from https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=602960&partner=valve)
> [22.6.2020 12:19:54] (Msg) Pending ping measurement until network config is obtained.
> [22.6.2020 12:19:54] (Msg) Initialized low level socket/threading support.
> [22.6.2020 12:19:39] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
> [22.6.2020 12:19:39] Content package load order: Vanilla 0.9
> [22.6.2020 12:19:38] Content package load order: Vanilla 0.9
> [22.6.2020 12:19:36] Attempting to open ALC device "OpenAL Soft"
> [22.6.2020 12:19:35] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
> [22.6.2020 12:19:35] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
> ```

From breeding grounds back to the previous level

> ![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/69087fee-1cf6-49f6-a690-713752de5ec2)
> 
> ```
> Barotrauma Client crash report (generated on 22.6.2020 12:52:27)
> 
> 
> Barotrauma seems to have crashed. Sorry for the inconvenience! 
> 
> 
> 9346DF122A863831AC895B82C3AB72F4
> 
> 
> Game version 0.1004.0.0 (ReleaseWindows, branch feature/campaign-groundwork, revision 9f6b28b89)
> Graphics mode: 2560x1440 (BorderlessWindowed)
> VSync OFF
> Language: English
> Selected content packages: Vanilla 0.9
> Level seed: Rhadamanthys LineaMehen Linea
> Loaded submarine: Dugong (B4137909B5D168EC25EB828C63417F56)
> Selected screen: Barotrauma.GameScreen
> SteamManager initialized
> Client (Round had started)
> 
> 
> System info:
>     Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
>     GPU name: NVIDIA GeForce GTX 980 Ti
>     Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
>     GPU status: Normal
> 
> 
> Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
> Target site: Boolean <InitProjSpecific>b__33_0(Barotrauma.GUIButton, System.Object)
> Stack trace: 
>    at Barotrauma.MultiPlayerCampaign.<InitProjSpecific>b__33_0(GUIButton btn, Object userdata) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 124
>    at Barotrauma.GUIButton.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 234
>    at Barotrauma.GUIComponent.UpdateManually(Single deltaTime, Boolean alsoChildren, Boolean recursive) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 459
>    at Barotrauma.MultiPlayerCampaign.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 246
>    at Barotrauma.GameSession.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 466
>    at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 130
>    at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 953
>    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
>    at Microsoft.Xna.Framework.Game.Tick() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
>    at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
>    at Microsoft.Xna.Framework.Game.Run() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
>    at Barotrauma.Program.Main(String[] args) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
> 
> 
> Last debug messages:
> [22.6.2020 12:52:24] test
> [22.6.2020 12:52:07] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
> [22.6.2020 12:52:07] (Msg) Ping location: sto2=14+1,sto=18+1/14+1,fra=45+4/33+1,ams=40+4/34+1,waw=53+5/34+1,lux=48+4/37+1,lhr=47+4/38+1,par=52+5/43+1,vie=50+5/45+1,iad=129+12/119+1,sgp=212+21/213+21,gru=250+25/262+1
> [22.6.2020 12:52:07] (Msg) Ping measurement completed
> [22.6.2020 12:52:05] (Verbose) Communications with routing cluster 'sto2' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'syd' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'tyo1' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'tyo' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'scl' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'sgp' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'sea' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'man' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'hkg' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'lim' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'maa' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'lax' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'waw' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'okc' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'vie' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'gru' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'ord' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'sto' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'jnb' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'eat' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'bom' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'mad' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'dxb' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'par' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'lux' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'lhr' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'atl' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'iad' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'fra' established.
> [22.6.2020 12:52:03] (Verbose) Communications with routing cluster 'ams' established.
> [22.6.2020 12:52:03] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
> [22.6.2020 12:52:03] (Msg) Performing ping measurement
> [22.6.2020 12:52:03] (Msg) Got SDR network config.  Loaded revision 276 OK
> [22.6.2020 12:52:02] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
> [22.6.2020 12:52:02] Lobby created!
> [22.6.2020 12:52:02] (Verbose) Service thread running.
> [22.6.2020 12:52:02] (Msg) RelayNetWorkStatus:  avail=Attempting  config=Attempting  anyrelay=Waiting   (Attempt #1 to fetch config from https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=602960&partner=valve)
> [22.6.2020 12:52:02] (Msg) Pending ping measurement until network config is obtained.
> [22.6.2020 12:52:02] (Msg) Initialized low level socket/threading support.
> [22.6.2020 12:51:49] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
> [22.6.2020 12:51:49] Content package load order: Vanilla 0.9
> [22.6.2020 12:51:49] Content package load order: Vanilla 0.9
> [22.6.2020 12:51:47] Attempting to open ALC device "OpenAL Soft"
> [22.6.2020 12:51:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
> [22.6.2020 12:51:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
> ```

**Comment by Rokvach** [comment]
Update: Here's a earlier version of the save which I included to a separate ticket, if the included one is broken

https://app.zenhub.com/files/175046454/a0aa5d41-391d-49d2-8808-e640ef7ae692/download

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c90653bd91e917bf6321e0c0fa19ff7bae74688b

**Comment by Rokvach** [comment]
- [ ] You can't return from a breeding ground

Travel to the breeding grounds and when you enter the level try and leave back to the previous level you came from @Regalis11 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e9bf63e1-1460-418e-b14e-02a28be91e72)

**Comment by Rokvach** [comment]
Update: Nvm its just really disorientating, because you are already on the level therefore you can't select the destination even tho the map allows you to do so. So if I go to the end of this level I should arrive at the outpost. Just needs a indication that its the path you are currently on, which I assume should come with the new map. 

In this example I can't return to the outpost I came from in the map because I am already on my way to the outpost, so therefore I can't "Start" the round. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/198b1b94-0cb2-46df-9401-8b086afdfa3e)

**Comment by Rokvach** [comment]
Closing this ticket as the issue has been fixed, the issue pointed above should be something which should be handled more clearly on the new map, Closing.
