### ISSUE TITLE
0.1004.0.0 (Unstable): Broken Sprite for Pump is Broken

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3182]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As they say, a picture is worth a thousand words.
![image](https://user-images.githubusercontent.com/37539527/85290324-b8fb7900-b490-11ea-9de6-1fd7128124e1.png)

**Steps To Reproduce**
1. Open the sub editor
2. Place a pump
3. Set the pump condition to 0

**Version**
Game version 0.1004.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision 5a89e70b4).
Windows 10 version 1903.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/13941527058a1b686bfca93ad340f9c394f1b5cc

**Comment by Rokvach** [comment]
No issues, closing.
