### ISSUE TITLE
[Unstable 0.1004.0.0] You can disarm guards which makes them harmless

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3185]
You can stun a guard and disarm them while they are stunned, doing so will make the guard harmless towards the player

A single player can achieve this relatively easily, as you can drop all the guards items to the floor from their inventory and they wont pick them up.

**Comment by itchyOwl** [comment]
Is this still an issue? Using a stun baton or a stun gun should count as an aggression, which should make all the guards attack you.

**Comment by itchyOwl** [comment]
Closing this, as I don't think it's an issue anymore and no one has responded. Reopen if you disagree,
