### ISSUE TITLE
Dedicated Server Modifications

### ISSUE THREAD

**Issue by Daniel-w3** [Regalis11/Barotrauma#3186]
I am trying to allow respawn in campaign mode so people don't have to wait once they die.

I have managed to find where it checks with an if statement which I commented out.
`if (serverSettings.AllowRespawn/* && missionAllowRespawn*/) { respawnManager = new RespawnManager(this, usingShuttle ? selectedShuttle : null); }`
but when i die the server kicks me out. With an error
`ClientName has been kicked from the server. Reason: Missing entity Barotrauma.Networking.RespawnManager (event id 709, entity id 3760)`
From what I understood the client is missing the entity. Does anyone know how entity manager works or if you could put me in the right direction in fixing this. Thank you.

**Comment by Regalis11** [comment]
There's a similar client-side check in the method "StartGame" in GameClient.cs which you also need to modify to ensure the clients instantiate the RespawnManager. 

However, I suspect these changes won't be enough to get it working properly. You'll also probably need to modify how the server handles the clients' saved character data (i.e. metadata about characters: name, skills, job, etc): discarding the old data when a previous character dies, creating new data and such. There's most likely other things as well that need to be modified.

**Comment by Daniel-w3** [comment]
Got it working thx to you @Regalis11 Not sure about the character data will have to test it and see if that works. But for now its not giving any errors and working.
