### ISSUE TITLE
Submarine should start in maintain position state at the start of a level

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3191]
Especially an issue with subs that can't dock to the outpost, as you would have to turn the maintain position on every time you want to enter a outpost as otherwise your submarine will just drift away. 

But I think it shouldn't cause any harm having the maintain position on by default regardless of the submarine type.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/3c94cd28cc395100de8b4afc8c215a3d044fc72d

**Comment by Rokvach** [comment]
I was unable to get this to work with a customized Dugong where I removed the top docking hatch entirely, but works without any issues on the vanilla Dugong. @Regalis11

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4312e75b9e60036c3cafb6db90742d3278a897d

**Comment by Rokvach** [comment]
No issues, closing.
