### ISSUE TITLE
[Unstable 0.1004.0.0] Can see through walls on custom sub

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3192]
**Description**
Can see thrugh walls on my custom made sub, also windowed doors top part is missing shadow, i have no idea what is causing that, also in 2 lower rooms if you get super close to wall you can see through.

**Steps To Reproduce**
Open my sub and enjoy view of the fishes.

**Version**
0.1004.0.0 (Windows).

**Pictures Of The Bug**
![seethroughtwalls1](https://user-images.githubusercontent.com/32136089/85385441-fde3e600-b54a-11ea-8a12-c0775e42f379.png)
![seethroughtwalls3](https://user-images.githubusercontent.com/32136089/85385469-04725d80-b54b-11ea-965e-750d8ffc7f13.png)
![seethroughtwalls2](https://user-images.githubusercontent.com/32136089/85385450-00464000-b54b-11ea-8aa6-7e385441f4c2.png)

**Ship**
[-LVNS Scout SH.zip](https://github.com/Regalis11/Barotrauma/files/4818389/-LVNS.Scout.SH.zip)

**Comment by Regalis11** [comment]
@juanjp600 addressed in https://github.com/Regalis11/Barotrauma-development/pull/2136?

**Comment by juanjp600** [comment]
Most cases appear to have been fixed, the missing blocker at the back of the sub still needs work
![image](https://user-images.githubusercontent.com/8607119/91064505-b68adc00-e605-11ea-8d34-828e9f998cf7.png)
![image](https://user-images.githubusercontent.com/8607119/91064524-ba1e6300-e605-11ea-89aa-064ef9818e83.png)
