### ISSUE TITLE
[Feature request] Make husks and huskcrawlers neutral to the infected if he/she at the later infection stages

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#3193]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As said in the description, i suggest to add husk neutrality IF NOT PROVOKEN to the player at stinger and probably mute stages of the infection. Its more or less logical (according to Europan, looks like this thing is capable to really sophisticated activities), adds additional flavor to the game and can be used in emergency (i mean its REALLY bad situation if you forced to intentionally infect yoursef) if necessary.

**Comment by itchyOwl** [comment]
Yeah agree. Should be straightforward to do.

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-developmen@d2a805a.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
