### ISSUE TITLE
[Unstable 0.1005.0.0] Few terminal collision boxes are slightly higher then sprites.

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3195]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Collsion boxes for terminals are off.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.1005.0.0 (Windows).

**Pictures Of The Bug**
![image](https://user-images.githubusercontent.com/32136089/85424946-3bfbfc80-b581-11ea-9b61-47d40d6b32c2.png)

**Comment by Regalis11** [comment]
These are not actually colliders (the terminals don't have colliders), but the "dimensions" of the item that affect things such as the area in which you can interact with them. They were intentionally offset to get the sprites to look right after the art unification (the old sprites started from the floor while these are supposed to be placed above it).

**Comment by Camper125Lv** [comment]
Oh, I just thought it looks odd and no one specified it in discord so decided to report.
