### ISSUE TITLE
[Unstalbe 0.1005.0.0] Bots do not follow orders which were assigned to them in a previous round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3196]
Either clear orders between rounds or make sure that bots will follow them even on the next round

**Comment by ekqvist** [comment]
From what I remember, the orders **should** be cleared in between rounds because the AI is recreated as well. So, if the orders persist in between rounds, that sounds like a bug. I'll look into it tomorrow.

**Comment by ekqvist** [comment]
Orders seem to get cleared in between rounds in SP so this seems like a MP-specific issue

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@b7155c1. Likely wasn't done properly since we didn't have persistent bots in MP. Should now always be done when a campaign round ends.

**Comment by Rokvach** [comment]
No issues, closing.
