### ISSUE TITLE
[Unstable 0.1005.0.0] Rotating battery wont rotate their charge bar

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3199]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Rotating battery wont rotate their charge bar.

**Steps To Reproduce**
Rotate battery.

**Version**
0.1005.0.0 (Windows).

**Picture Of A Bug**
![image](https://user-images.githubusercontent.com/32136089/85437865-ee3cbf80-b593-11ea-9048-c2296178d617.png)

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
