### ISSUE TITLE
Barotrauma crashing on load up

### ISSUE THREAD

**Issue by andrew12314** [Regalis11/Barotrauma#320]
I attempted running this on the computers at school to see whether it would work. Upon loading it up the computers ram and CPU can handle it as I can see by task manager.
If anyone has any insight it would be much appreciated. 

Barotrauma Client crash report (generated on 06/03/2018 09:55:56)

Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.

Game version 0.8.0.4
Graphics mode: 1366x768 (BorderlessWindowed)
Selected content package: 
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: Intel(R) HD Graphics 4400
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.778646}
    GPU status: Normal

Exception: Object reference not set to an instance of an object.
Target site: Void Draw(Microsoft.Xna.Framework.Graphics.SpriteBatch, Microsoft.Xna.Framework.Graphics.GraphicsDevice, Single)
Stack trace: 
   at Barotrauma.LoadingScreen.Draw(SpriteBatch spriteBatch, GraphicsDevice graphics, Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GUI\LoadingScreen.cs:line 125
   at Barotrauma.GameMain.Draw(GameTime gameTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 447
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 41

Last debug messages:

**Comment by Cyprex** [comment]
note that this is the same exception as #165, unlike that person you are on windows, right?

**Comment by NilanthAnimosus** [comment]
As far as I can tell, the above issue shouldn't be causing a crash normally. whats actually happening (Now that I look at this) is an object reference not set. the only thing I can see that is likely to fail is the lack of a background texture for the loading screen.

This points that likely the content folder itself is damaged and missing the necessary background texture. the crash report also states what operating system it uses (It states windows NT 6.0 which is windows Vista.

The file Content/UI/titleBackground.png is missing in this case.

**Comment by andrew12314** [comment]
Im on Windows 7, I am going to try to reinstall the game to reacquire the missing file.

**Comment by Regalis11** [comment]
I'm guessing reinstalling did the trick? If not, please let me know and I'll reopen this.
