### ISSUE TITLE
[Unstable 0.1005.0.0] Rotation of interactive Items

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3200]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- does not affect the ladders
- critical for doors and hatches, gaps do not change their position
- it makes sense to add rotation to the stairs, which will allow them to be used for communication of non-standard height rooms

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/29980468/85448100-0534df00-b59f-11ea-92e1-c60616389307.png)

**Version**
0.1005.0.0

**Comment by Regalis11** [comment]
Disabled rotating ladders and doors in https://github.com/Regalis11/Barotrauma-development/commit/3ef7f6b9e4059202a7873130541f2f650c47a45e. Allowing them to be rotated would require such extensive changes (climbing animations, waypoint generation, door gap and collider logic) that I don't think it's worth implementing for such a niche use case, at least at the moment.

Fixing the positioning of the contained items should be fairly trivial though, I think that's something we should do.

**Comment by Regalis11** [comment]
The contained items should now rotate with the container: https://github.com/Regalis11/Barotrauma-development/commit/647e456d1e06e153fb176f41c5982dae11d24c54

**Comment by Rokvach** [comment]
Found some more items which had rotation issues, not specifically limited to contained items

- Oxygen tank self
- Large diving suit locker

Not sure if these would update to the correct rotation?
- Coilgun (barrel)
- Railgun (barrel)
- Searchlight (light)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/77d6efee-4064-4036-aa88-0a4b15be31bf)

**Comment by Rokvach** [comment]
No issues, closing.
