### ISSUE TITLE
[Unstable 0.1005.0.0] Railgun Shell Rack

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3201]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- In the unstable version, shells on the rack are shifted to the left, while before that they were located in the center of the rack.
- Not logical mirroring of shells on the rack.

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/29980468/85450684-b0469800-b5a1-11ea-8015-9f610175ac75.png)

**Version**
0.1005.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a79906a221e730367312bf5c6f5a11b6a2becf6

**Comment by Rokvach** [comment]
No issues, closing.
