### ISSUE TITLE
[Unstable 0.1005.0.0] No gaps on Hemulen

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3202]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/29980468/85451836-f3553b00-b5a2-11ea-95c3-cf64180fcb89.png)

**Version**
0.1005.0.0

**Comment by danielasteljoki** [comment]
Fixed in 82fa6e9

**Comment by Rokvach** [comment]
No issues, closing.
