### ISSUE TITLE
[Unstable 0.1005.0.0] Transducer on Kastrull Drone far from the hull

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3203]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/29980468/85453729-d91c5c80-b5a4-11ea-8475-79bd71a9def4.png)

**Version**
0.1005.0.0

**Comment by danielasteljoki** [comment]
Somebody's fixed this already.

**Comment by Rokvach** [comment]
No issues, closing.
