### ISSUE TITLE
[Unstable 0.1005.0.0] Holes in the background walls of Orca

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3204]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- Engine room, behind the cable holder
![image](https://user-images.githubusercontent.com/29980468/85456073-3fa27a00-b5a7-11ea-81d7-62cd87694bce.png)

- Front electric compartment, next to the door
![image](https://user-images.githubusercontent.com/29980468/85456154-5648d100-b5a7-11ea-8198-a7ff919a7bc8.png)

**Version**
0.1005.0.0

**Additional information**
There are still holes near the hatches in the center of the ship but they are not visible

**Comment by rav2n** [comment]
On Azimuth: hole in the airlock behind the cable holder.

**Comment by danielasteljoki** [comment]
Plugging these as we do additional visual passes.

**Comment by Rokvach** [comment]
No issues, closing.
