### ISSUE TITLE
[Question] What's the point of the purchase button?

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3210]
[Question, kind of an issue?]
Genuine question, not entirely sure why the purchase button exists in the store interface. 
This was originally going to be a feature request for a "receipt" so you can see what everyone else is buying, but it kind of already existed in the previous update. The purchase button in the store UI essentially just acts as a "clear receipt" button so that nobody knows what you bought, despite the fact that it's all going to the same big queue list anyway, just hidden. This makes coordination on what needs to be bought more difficult, which is ironically worse than 0.9.10.0 where there is at least a coordinated list of everything bought by everyone with purchasing permissions on the crew. It would be much better if it behaved like 0.9.10.0 where the list will just automatically be delivered to the ship when the outpost round ends.
But the purchase button was deliberately added and the system was changed from the previous update. So why was it added? Is it for something not implemented yet?

**Comment by Rokvach** [comment]
I don't think its fair to compare the old system with the new one, as the new store isn't as fair as the old one was. You can't just blindly purchase items which you want like you used to. You need to keep track of your balance before finalizing your purchasing or you will be cheated out of your money. The new system of validating your purchases also feels more like trading than the old as you aren't buying items one at a time anymore and selling them back if you selected a wrong item or too many.  

But I do think that some type of purchase history is necessary so others can also keep track as to what was bought, but I also think that there isn't a need for as much planning what to buy as there was with the old store, as now if you do buy a wrong item you can just re-dock to the outpost and go sell it, same with items you forgot to buy. As the outposts are so freely accessible now compared to before there isn't as much of a pressure to buy the correct items as there was before.

**Comment by hubismal** [comment]
Thanks for the response.
