### ISSUE TITLE
Some premade outposts are not suitable

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3211]
[Bug]
This is supposed to be a mine but the old placeholder outpost generated instead. I remember it being mentioned that there would be an option for premade outposts to appear, but this is obviously not intended to be a premade outpost (especially since every important npc spawns behind an impassable wall).
![2020-06-23-230607_856x486_scrot](https://user-images.githubusercontent.com/47284081/85499010-6a400300-b5a6-11ea-86fe-5705bacb5ee3.png)
Was this left in by mistake?

**Comment by Regalis11** [comment]
If the outpost generator fails to generate an outpost for some reason (e.g. can't generate a valid layout from the configured set of room modules), it falls back to one of these pre-made outpost. If you happen to have the level seed or a save file where this happens, it'd be very useful in diagnosing this!

**Comment by hubismal** [comment]
![2020-06-24-030628_457x101_scrot](https://user-images.githubusercontent.com/47284081/85520113-16461600-b5c8-11ea-9723-3979ac417ed4.png)

![2020-06-24-030738_568x399_scrot](https://user-images.githubusercontent.com/47284081/85519972-e565e100-b5c7-11ea-845b-de0658f0aeb6.png)

**Mapseed: rXi42i5z**

It's Oshan Mining Facility. Go to the natural formation, then oshan. Not providing the save because oshan apparently turned into a city according to "central command" (would be cooler if "central command" were replaced with some kind of news bulletin from The Europan just for the little tie-in bonus)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b4d4bb8a64d50894cd0bdd7656dcea5ef67834e8 and https://github.com/Regalis11/Barotrauma-development/commit/bdee52c8c20edb51d548e9a9889d777755822d77. The pre-built outpost no longer generates with this seed, and I also removed the inaccessible rooms in case the generation still fails in some level.

**Comment by Rokvach** [comment]
The issues pointed here are fixed, closing.
