### ISSUE TITLE
Play honk.ogg in Event clownrelations1

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3212]
[Extremely paramount feature request]
```xml
<StatusEffectAction targettag="triggerer_player">
    <StatusEffect>
        <Sound file="Content/Items/Weapons/honk.ogg" range="300" />
    </StatusEffect>
</StatusEffectAction>
```
It would be ideal if the above xml was added into the horn-squeeze dialogue path of clownrelations1 for obvious reasons.

**Comment by hubismal** [comment]
glad to see this is getting the attention it deserves......... on a more serious note, having sounds in general throughout more events might really "bring them to life", especially during fadetoblack events where your imagination does the work.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/515c4276d7ab371c6b1915f767bd5a848a188bfa

**Comment by Rokvach** [comment]
No issues, closing.
