### ISSUE TITLE
Syncing of owned submarines to joining clients

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#3213]
Currently the list of owned submarines is out of sync for players joining mid-campaign, thus making it impossible for these clients to initiate a vote or to see owned submarines in the submarine selection interface until they've been switched to by a vote initiated by another client.

**Comment by EdusFF** [comment]
Much more issues than I thought with equalitycheckvals seeming to mismatch occasionally, maybe something to do with submarines saved again during the campaigns

**Comment by Rokvach** [comment]
No issues, closing.
