### ISSUE TITLE
Chooserandom="true" does not work for EventSet if there is no MonsterEvent present in the list.

### ISSUE THREAD

**Issue by xAtea** [Regalis11/Barotrauma#3214]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Chooserandom="true" does not work for creating events with sub-events unless the base 'list' of the events inclused a regular monsterevent. 

IE:
```
<EventSet chooserandom="true" mindistancetraveled="0.60" minmissiontime="10000" minintensity="0.0" maxintensity="1.0">
      <MonsterEvent characterfile="Mudraptor" minamount="3" maxamount="4" spawntype="mainpath" musictype="monster" scatter="250" />
      <MonsterEvent characterfile="Crawler" minamount="4" maxamount="8" spawntype="mainpath" musictype="monster" />
      <EventSet chooserandom="false">
              <MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="1" spawntype="mainpath" musictype="monster" />
              <MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="3" spawntype="mainpath" musictype="monster" />
      </EventSet>
</EventSet>
```

This vanilla set works fine, and spawns crawlers, mudraptors, OR Threshers. However if you remove both crawlers and mudraptors (or add them to a second chooserandom="false" event) then the event as a whole spawns nothing.

```
<EventSet chooserandom="true" mindistancetraveled="0.60" minmissiontime="10000" minintensity="0.0" maxintensity="1.0">
       <EventSet chooserandom="false">
            <MonsterEvent characterfile="Mudraptor" minamount="3" maxamount="4" spawntype="mainpath" musictype="monster" scatter="250" />
            <MonsterEvent characterfile="Crawler" minamount="4" maxamount="8" spawntype="mainpath" musictype="monster" />
      </EventSet>
      <EventSet chooserandom="false">
              <MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="1" spawntype="mainpath" musictype="monster" />
              <MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="3" spawntype="mainpath" musictype="monster" />
      </EventSet>
</EventSet>
```

In this example, due to having two "sub-events" without a monsterevent in the chooserandom="true" list, this event will no longer spawn any creatures or even show up in the event tracker.

**Version**
0.9.10.0 Windows 7

**Additional information**
My original goal for such a set was to give the game more variety, creating multiple 'spawnsets' for the game to pick at random so that it wasn't the same creatures attacking every time in the same numbers. However despite being told this 'should' work, extensive attempts to make it function have proved unsuccessful.

**Comment by xAtea** [comment]
*Addon** to this issue:*

Chooserandom="true" also prefers MonsterEvents over EventSets in all cases. Even the above mentioned vanilla code has this issue. 

If you start a game with that code set to spawn at the beginning/ near the beginning, in all cases tested thus far (with a custom spawn code involving one monsterevent, two EventSets) The game always spawned the monsterevent FIRST. Then the EventSet that is at the top of the 'list' of events is selected second. The EventSet below the first is never used, and in fact upon the code attempting to run said chooserandom=True a third time, the event fails and ceases further attempts to spawn creatures.

`<EventSet chooserandom="true" mindistancetraveled="0.0" minmissiontime="10" minintensity="0.0" maxintensity="1.0">
		<EventSet chooserandom="false">
			<MonsterEvent characterfile="Husk" minamount="1" maxamount="2" spawntype="mainpath" musictype="monster" scatter="250" />
			<MonsterEvent characterfile="CrawlerHusk" minamount="0" maxamount="2" spawntype="mainpath" musictype="monster" scatter="250" />
		</EventSet>
		<EventSet chooserandom="false">
			<MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="1" spawntype="mainpath" musictype="monster" />
                        <MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="3" spawntype="mainpath" musictype="monster" />
		</EventSet>
		<MonsterEvent characterfile="Mudraptor" minamount="1" maxamount="2" spawntype="mainpath" musictype="monster" />		
	</EventSet>`

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6096246a7b32ad8602016bea2a5304ea6dd1ea5d

**Comment by Rokvach** [comment]
No issues, closing.
