### ISSUE TITLE
1005 CRASH: two of the same events in an eventset crash game

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3216]
[Crash, Modding]
Self explanatory. Put something like this:
```xml
<EventSet identifier="thal_coalitionMineRadioactive.easy" minleveldifficulty="0" maxleveldifficulty="50" allowatstart="true" chooserandom="true">
      <ScriptedEvent identifier="missionevent_killmonster"/>
      <ScriptedEvent identifier="missionevent_killmonster"/>
    </EventSet>
```
in a larger eventset to have the game crash when loading the mod.

**Comment by hubismal** [comment]
[crashreport (88).log](https://github.com/Regalis11/Barotrauma/files/4829095/crashreport.88.log)
crashlog

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/efb03d8be09dff168d9ad10cb5b2a92a561a9aab

**Comment by Rokvach** [comment]
Confirmed working, closing.
