### ISSUE TITLE
Coilgun ammo status when not using it

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#3218]
Seeing ammo status on coilguns would make it easier to stay on top of the current ammo situation. Right now using the coilgun is required to get an idea of how much ammo there is, whereas for example the railgun's current ammo state can be easily seen without using it. Could use a power bar type of a display that batteries use

**Comment by mLuby** [comment]
Adding a CoilgunLoader **ConnectionPanel** with an `ammo_out` (%) pin would solve this. Would be nice for railgun ammo loader too, though that's already visually different.

That way logic circuits can control whether to flash internal or gun-visible lights, trigger alarms, display "Ammo: 59%" messages, etc.

Likewise, Coilgun Loaders presumably need `power_in`, right? That'd be a breaking change for all subs though.

**Comment by Regalis11** [comment]
Implemented lights that indicate the ammo state https://github.com/Regalis11/Barotrauma-development/commit/124bbdb7cee9e16e155d79eaf4be1c4fe2443eb8

**Comment by giists** [comment]
The lights on a railgun loader only go down once the loader is completely empty instead of decreasing gradually like on a coilgun loader.

**Comment by Regalis11** [comment]
@giists Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4363/commits/7dfb0507c78f2f2cc17acc7e981cbc098c62c5f2

**Comment by giists** [comment]
Empty canister shells still make the light turn on even though you can't use them as ammo anymore.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4363/commits/76b8f41a3e170c07eee622a6b81483279477b502

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
