### ISSUE TITLE
1005 Bug: Players can pass money events without the money

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3219]
[Issue, Oversight, Feature Request]
We need a CheckMoneyAction or a Failure/Success outcome for MoneyAction. Currently it's possible to "buy" things from the black market alien tech guy for more marks than you have. And similar things in other events with moneyaction.
In an ideal world, we'd have both so that modders could have things happen and not happen if you have the right amount of credits (maybe increase your chance of being scammed, or have rich outpost managers take pity on you), but also just have a very straightforward you-don't-have-enough-money path.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d1c47eb0d007d4c5808d73a84efef529520b7616

**Comment by Rokvach** [comment]
No issues, closing.
