### ISSUE TITLE
Idea for Shells and Payloads

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#322]
With shells, I also mean grenades and depth charges. You could set them to "use" the contents instead of destroying them, allowing the use of new payloads that will otherwise not work when destroyed, like dye charges or poison gas, for instance. This also allows the payload to do a different thing depending on the container using them.

Here's an example for a customizable hand grenade:
`
<Item
    name="HTM Grenade"
	aliases="Stun Grenade,Nade"
    category="Equipment"
	tags="smallitem,weapon"
	description="HTM or Hand Thrown Munition, is an empty steel casing with a screw-off cap and a trigger mechanism that ignites the containing payload after a certain amount of time."
    canuseonself="true"
	impacttolerance="3"
	cargocontainername="Metal Crate"
	price="225">

    <Sprite texture="Mods/BTE/Items/Weapons/weapons.png" sourcerect="117,68,11,21" depth="0.55"/>

    <Body width="11" height="24" density="20" friction="0.95"/>
	
	<ItemContainer capacity="1" hideitems="true">
	  <Containable name="explosive"/>
    </ItemContainer>
	
	<ItemComponent>
	  <StatusEffect type="OnUse" target="This">
	    <sound file="Mods/BTE/Items/Weapons/GrenadePrimer.ogg"/>
	  </StatusEffect>
      <StatusEffect type="OnUse" target="Contained" delay="5">
	    <RequiredItem name="explosive" type="Contained"/>
		<Use/>
	  </StatusEffect>
    </ItemComponent>

    <Throwable slots="RightHand,LeftHand,Any" holdpos="0,0" handle1="0,0" throwforce="3" aimpos="35,-10">
	  <StatusEffect type="OnImpact" target="This">
	    <sound file="Mods/BTE/Items/Weapons/GrenadeHit.ogg"/>
	  </StatusEffect>
    </Throwable>
  </Item>
`

Here's an example of a payload that won't work when destroyed:
`
<Item
    name="Dye Charge"
    category="Equipment"
    Tags="smallitem,explosive"
	description="A non-lethal explosive designed to release clouds of particles that act like an octopus-like ink spray in water and a dense cloud in air."
    price="150">

    <Sprite texture="Mods/BTE/Items/Weapons/weapons.png" depth="0.8" sourcerect="112,174,16,8"/>

    <Body width="16" height="7"/>
	
	<ItemComponent characterusable="false">
	  <StatusEffect type="OnUse" target="This" IsOn="true"/>
    </ItemComponent>
	
	<LightComponent LightColor="0.2,0.1,0.1,0.1" Flicker="0.5" range="100" IsOn="false">
	  <StatusEffect type="OnActive" target="Hull" oxygen="-1000"/>
      <StatusEffect type="OnActive" target="This" Condition="-1">
		<ParticleEmitter particle="smokescreen" particlespersecond="30" velocitymin="10" velocitymax="500" anglemax="360"/>
      </StatusEffect>
      <StatusEffect type="OnBroken" target="This" IsOn="false"/>
      <sound file="Content/Items/Tools/flare.ogg" type="OnActive" range="800" loop="true"/>
    </LightComponent>

    <Pickable slots="Any">
	  <StatusEffect type="OnFire" target="This" IsOn="true" Condition="-5"/>
    </Pickable>
  </Item>
`

Using this system instead will also allow players to use other things as payload, for instance a handheld sonar turned on, which will act as a decoy to lure creatures towards it.

**Comment by Regalis11** [comment]
@JJRcop I know, I kept this open intentionally because it has a bunch of ideas that could still be implemented later on.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
