### ISSUE TITLE
1005 Bug: Security guards a bit too opportunistic

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3220]
Security guards will instantly take the opportunity to handcuff you whenever you receive the slightest stun damage. This means when you get hit by so much as knife or a screwdriver, the minor stun damage it does is enough for them to handcuff you in a split second. Security officers should probably only attempt to arrest at greater than 4 stun damage.

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@8fe616c.

**Comment by Rokvach** [comment]
No issues, closing.
