### ISSUE TITLE
1005 Bug: Hotloading broken for campaign types

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3221]
Hotloading is broken for a few campaign-related xmls. Will update this issue as I find more. **These errors specifically only appear when I turn a mod on and off in settings to refresh, not when restarting the game.**

- Specifying NPCs from a custom npcset in the `<npcs>` part of outpostconfigs results in error output
- Eventsets will be unable to find any modded locationtypes ie `<EventSet identifier="thal_coalitionMineRadioactiveEvents" leveltype="outpost" locationtype="Coalitionmineradioactive" allowatstart="true" chooserandom="false" ignorecooldown="true">` won't work
![2020-06-26-020945_484x93_scrot](https://user-images.githubusercontent.com/47284081/85832014-ea0bd000-b754-11ea-94dd-3020e5d1cf54.png)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/62231ebfb60e7f88dc85ef24e6f415911f96bc02.

**Comment by Rokvach** [comment]
Confirmed working, closing.
