### ISSUE TITLE
Experience gain when docked to an outpost

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#3223]
Experience is gained when the navigation terminal is selected while docked to an outpost

**Comment by ekqvist** [comment]
Disabled experience gain for Helm skill in outpost levels in Regalis11/Barotrauma-development@64f59f7

**Comment by ekqvist** [comment]
Also disabled for operating turrets in Regalis11/Barotrauma-development@1e69821

**Comment by Rokvach** [comment]
No issues, closing.
