### ISSUE TITLE
Font size on larger monitor / TVs with a lower pixels-per-inch is too small, add a font scaling multiplier to settings

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#3224]

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-development@600e90.

**Comment by Rokvach** [comment]
I had to restart before my text size was set

Tested on largest size possible
1. Battery charge overlaps with the charge amount
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/14107540-f4c7-4a30-a6ca-9caf1e5be83f)

2. Reputation titles overlap with description
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/71412609-7560-45cf-b070-5c4ff063ffcb)

3. Ready to start toggle text is hidden behind the start button
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5a75d5b3-b859-40bf-ad26-314893a0b0c9)

4. Slight overlap on Shipyard tabs
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1dffd3f5-b3ca-4059-8af9-2c4f3e593872)

5. Ready check Close button is rendered below the list field
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/75ce156e-44fb-482d-89e3-fa3277db4dd6)

6. A lot of overlapping in crew hiring
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ed3f8ca0-c5a0-4b1c-a595-5e9fb1fc4fe1)

7. Overflow when purchasing subs
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7a094bf3-b19e-46f8-a5ec-5e577b1e4a5f)

8. Slight overlap on single item inventories
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/85d04d68-5d2f-4c06-abcd-2c7d8136f4bc)

7. Hotbar numbers looks a bit broken, maybe the corner piece should adjust with the text size?
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/05d0e023-5b56-460c-9d61-d1f59396c406)

**Comment by itchyOwl** [comment]
I didn't intend 200% to fully work with every resolution. I'm not sure that we can fix those issues without a huge effort, but we should definitely test scaling on different resolutions (4k too) and on screens of different physical sizes. If 200% is clearly broken on most screens, we could perhaps restrict the scaling a bit.

Since Regalis11/Barotrauma-development@4bf9524 you shouldn't have to restart. Applying should be enough. Did it not work?

**Comment by Rokvach** [comment]
Yes the font size doesn't actually change when I change it and hit apply, only changes after a restart.

**Comment by itchyOwl** [comment]
Ok, let's make the max scale 150%, as it seems to work on those resolutions. With that the default 100% is neatly in the middle of the slider too.

If it's not enough, I'm sure we'll get reports about it.

Changed that and fixed the issue with the scale not applying without a reset.

**Comment by Rokvach** [comment]
Seems like only the crew management UI still struggles, could just be a issue on how its setup in the first place, as everything else works without any issues.
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b81565c0-8694-4cf8-b4de-18fc39def43d)

**Comment by Rokvach** [comment]
Made a separate issue to highlight some of the UI issues and text scaling in 4K, also covers the crew list above in there. I think this is safe to close as I didn't detect any technical issues with it. Closing.
