### ISSUE TITLE
[Unstable 0.1005.0.0] Store Item stock quantities reset after saving and quitting

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3228]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The stock quantities of items in the store revert to pre-purchase stock quantities after Saving and Quitting.

**Steps To Reproduce**
In Single Player Campaign
1. Buy out the stock of any item(s) in the store, so the quantity is 0
2. Save and Quit
3. Load saved game
4. try to buy the same item again
The quantities will be reset (more will be available for purchase)

**Version**
Unstable 0.1005.0.0, revision ce7ef3f2a

**Additional information**
seems a little similar to #2159 but for items instead of crew

**Comment by Udrakan** [comment]
Can confirm. Store's money gets saved properly, but stock quantities reset.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@9c7f712

**Comment by Rokvach** [comment]
No issues, closing.
