### ISSUE TITLE
Unstable - NPCs in outposts get stuck in these 2 spots and suffocate

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3229]
**Description**
When NPCs stay for some time in these spots, they slowly suffocate.
![image](https://user-images.githubusercontent.com/59519434/85926786-1b45e680-b8a2-11ea-9a14-228c1c42c454.png)
![image](https://user-images.githubusercontent.com/59519434/85926792-2d278980-b8a2-11ea-850f-d18450a37f11.png)

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed the 1st issue (ResearchModule_02) in https://github.com/Regalis11/Barotrauma-development/commit/ec11d31ad39b7d4d21e18e45912d75b753e27bee

**Comment by Rokvach** [comment]
Found another case where the vent is placed right outside of the door so the room doesn't get any air

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7dc9fc52-ceaf-457a-afef-15dac0c0920d)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f7f837b5758e418989412a2873d5694bb24700dc

**Comment by Rokvach** [comment]
No further issues, closing.
