### ISSUE TITLE
[Feature Request] Add a functional Deconstructor/Med Fabricator in a wreck for Azimuth/Dugong/Berilia plays to find.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3232]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While playing on subs like Azimuth, Dugong, and maybe Berilia, I find that there are some categories of items that these three subs will have issues with stock running out at some point. It would be nice to find a remote place for these three subs to make a pitstop at to recycle their loots.

Like for instance, UEX is quite hard to come by on these subs for instances to make exploding ammo boxes.

**Version**
0.1005.0

**Comment by Camper125Lv** [comment]
I personally would love if there was somekinda hand held variant that would eat up batteries and would have less options.

**Comment by Udrakan** [comment]
Outposts would be a better fit

**Comment by Regalis11** [comment]
Ping @ezjamsen
