### ISSUE TITLE
Shopping crate items are not cleared when moving to a new location

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3236]
**Description**
Affects items in both buy crate and sell crate.

**Version**
Unstable 0.1005
Windows

**Comment by ekqvist** [comment]
Fixed for sell crate items in Regalis11/Barotrauma-development@bc05de4

**Comment by ekqvist** [comment]
Fixed for buy crate items in Regalis11/Bartorauma-development@3fb33eb. Also, changed the way it's done to sell crate items in Regalis11/Bartorauma-development@12e85bd. Both are now cleared when the round ends.

**Comment by Rokvach** [comment]
No issues, closing.
