### ISSUE TITLE
[Unstable 1005] Messed up cutscene plays when clicking "Retry"

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#3239]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After the Initianal cutscene, if you click Retry on the outpost you just spawned, a messed up cutscene plays.

**Steps To Reproduce**
1. Start a Campaign.
2. Wait for it to load.
3. After the cutscene, go into the menu and click on "Retry".
4. Messed cutscene appears! 
See GIF below
![Cutscene bad](https://user-images.githubusercontent.com/65787528/85974153-a4841880-b989-11ea-83c4-e80acf98757f.gif)
This will only play on the initial outpost.
By the way on all cutscenes you can still move, not sure if this is intentional.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf1119db78ed689449cab7dda5e86cb046d48344

**Comment by Rokvach** [comment]
No issues, closing.
