### ISSUE TITLE
Quick-assigning an order can pick a character who can't hear the order giver

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3240]
The controlled character can be heard giving the order, but the other character won't receive the order. In manual assignment, characters who cannot hear the controlled character have a red cross displayed on top of their node and they cannot be chosen for the order.

Steps to reproduce:

1. Start a new SP campaign
2. Leave for a new destination
3. Take control of the Mechanic to remove their headset
4. Take control of the Captain and move far enough from the Mechanic that you can see the red cross displayed on their assignment node when you attempt to manually assign an order
5. Quick-assign a "Repair Mechanical Systems"
6. Observe as the Captain gives the order to the Mechanic, but the order icon isn't displayed in the crew list
7. Use `debugai` to confirm that the order wasn't assigned to the Mechanic

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@4ee9d49. Should test in a non-Debug build, as there are still some exceptions in the Debug build which allow easier order assignment (and which I should change later on).

**Comment by ekqvist** [comment]
Fixed ability to give orders to characters who can't hear the controlled character in Debug builds in Regalis11/Barotrauma-development@16d3782

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
