### ISSUE TITLE
You crash when you press tab as a monster.

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#3243]

**Comment by ekqvist** [comment]
Thanks for the report. Unfortunately, I cannot seem to reproduce this right now. What version and game mode were you playing when this happened?

**Comment by Rokvach** [comment]
This should already be fixed in Unstable, as it was caused if you played as something which didn't have a class icon. (or something similar)

**Comment by Rokvach** [comment]
Closing.
