### ISSUE TITLE
Source code question, what is world lock?

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#3244]
So I am trying to teleport subs on round start and it gives me an exception: "Cannot do - - - when the world is locked"
So when is the world not "locked"?

**Comment by Regalis11** [comment]
The world is locked when a physics update is running (specifically, during the World.Step() method). Basically that means you cannot modify the physics state in any callback from the physics engine (OnCollision, OnSeparation, etc) or run any physics code in parallel with World.Step.
