### ISSUE TITLE
Oscillator Desync

### ISSUE THREAD

**Issue by onein50million** [Regalis11/Barotrauma#3246]
-  [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The oscillator component doesn't seem to be synced up in multiplayer, leading to different players having different numbers. Have only tested with the sine wave parameter.

**Steps To Reproduce**
oscillator set to sine, connected to memory with button hooked up to signal_store. Number will be different between players after being pressed.
![image](https://user-images.githubusercontent.com/6622114/86076993-01daa100-ba40-11ea-931f-9bb8cebf9ee7.png)

**Version**
v0.9.10.0, Windows 10, build 18363
other player on Windows 7, Version 6.1 (Build 7601: Service Pack 1)

**Additional information**
[Test Sub](https://github.com/Regalis11/Barotrauma/files/4849147/oscillator.desync.test.sub.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/854da4049e76eef7c1baf1ad650d657323508293

**Comment by Rokvach** [comment]
Confirmed working correctly but there's a big delay even for local players, something we should look in to? @Regalis11

**Comment by Regalis11** [comment]
The delay happens because the server waits for the text to stay unchanged for 0.5 seconds before syncing it, decreased that to 0.1 s in 5ebbb70

**Comment by EtiamNullam** [comment]
Not sure what to test, its 0.1s and there is still obvious jump in the test sub provided. Works both for local and remote player.

**Comment by Rokvach** [comment]
Closing.
