### ISSUE TITLE
1006 Bug: Game still runs when map is selected

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3250]
This is a problem in Singleplayer because players are left with a situation where the sub starts flooding and there isn't anything they can do about it since they're stuck in the map, especially in natural formations where there is high danger. Having the map open should probably be one of those signature singleplayer-exclusive-pause-game scenarios, or there should be a way to exit the map.

**Comment by Rokvach** [comment]
You can close the map by either pressing RMB or Esc

**Comment by EdusFF** [comment]
Added pausing for singleplayer in: https://github.com/Regalis11/Barotrauma-development/commit/2e9a8d58b32b79bc30812a7d0c8b1415857fd72f

**Comment by Rokvach** [comment]
No issues, closing.
