### ISSUE TITLE
Audio does not work after OpenAL changes

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3252]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We've been getting some reports about game audio not working at all in the latest build (v0.10.0.0 RC 1)

> "ALC device creation failed to many times!"
> I have this bug only in last unstable version.
> In stable or previous unstable version sound work correctly.

**Steps To Reproduce**
Unknown

**Version**
v0.10.0.0 RC 1

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/922e0c21620270b05740779c280a33b0b8abdd97

**Comment by rav2n** [comment]
This problem is related to alphabets other than English. Simply renaming the speakers and the microphone cures the problem.

**Comment by Rokvach** [comment]
Confirmed to be working correctly, closing.
