### ISSUE TITLE
[Unstable 0.10.0.0] Wreck 1 - No platform on hatch in bottom left section

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3253]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is no platform on the hatch leading to the lowest level in the bottom left section of Wreck 1.
See attached image below.

**Version**
Unstable 0.10.0.0, branch dev, revision 954a95c221
Windows 10 64-bit

**Additional information**
https://cdn.discordapp.com/attachments/668819422919524352/727635893963456552/no_platform_wreck_1.jpg

**Comment by danielasteljoki** [comment]
Fixed in 5402ac3.

**Comment by Rokvach** [comment]
No issues, closing.
