### ISSUE TITLE
[0.10.0 RC1] Dugong Docking Hatch's Power Wire is a Docking Hatch instead of a wire.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3255]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Started a new campaign on Dugong and noticed it wasn't getting any power from the outposts. I went to rewire the Docking Hatch and found a white orphaned wire connected to the Power pin. Pulling this wire out gave me a Docking Hatch item.

**Version**
0.10.0 RC1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/184fd28d52c82d4bdd729cb70799899ad3eae7f1

**Comment by Kaillera** [comment]
Dugong is unable to sap power from the outpost by default. Players will question this since practically all the other subs usually has them connected.

**Comment by danielasteljoki** [comment]
Wired docking port in 4cd311b

**Comment by Rokvach** [comment]
No issues, closing.
