### ISSUE TITLE
[0.10.0 RC1] Dropped SMG is hovering above the floor by quite a bit

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3256]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dropped SMG is hovering above the floor by quite a bit.

**Version**
0.10.0 RC1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/79b9d4fb58330047ece2985830d662174baca115

**Comment by Rokvach** [comment]
No issues, closing.
