### ISSUE TITLE
Unstable - When bringing up command order interface, the camera lowers down.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3257]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bringing up command order interface, the camera lowers down.

**Version**
<0.10.0 RC1

**Comment by ekqvist** [comment]
When you open the command interface, we recenter the camera on the player, which is intentional. The same thing happens with the health interface and with conversations.

**Comment by Kaillera** [comment]
It doesn't seem "centered". Feels like an annoyance to me.
