### ISSUE TITLE
[0.10.0 RC1] Dugong's Pump in Oxygen Room missing Water Detector

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3259]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dugong's Pump in Oxygen Room missing Water Detector

**Version**
0.10.0 RC1

**Comment by ezjamsen** [comment]
Fixed in dev

**Comment by Rokvach** [comment]
No issues, closing.
