### ISSUE TITLE
Can't select custom subs as purchasable in MP campaign

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3262]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Install a custom sub from the workshop
2. Add a price and class (make sure you keep the sub in the Mods folder)
3. Start a dedicated server with that custom sub installed
4. Start a client from another folder with no custom subs installed
5. Join the server
6. Try to setup the campaign as the client, the custom sub doesn't show up in the list of purchasable subs

**Version**
v0.10.0.0 RC 1

**Additional information**
Probably happens because the class of the sub is Undefined client-side if the client doesn't have the file, causing it to think the sub is not campaign-compatible.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d70a82244b3bb31cf5371e8c74c2e734a64c2500

**Comment by Rokvach** [comment]
No issues, closing.
