### ISSUE TITLE
Unstable - "kill" console command can be used without enabling cheats

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3265]
**Description**
Doesn't seem like something intentional.

**Steps To Reproduce**
use kill command without enabling cheats

**Version**
Unstable and current stable too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/08695594cc140597f1f7492f26c1c606f92e70e3

**Comment by Rokvach** [comment]
No issues, closing.
