### ISSUE TITLE
[Unstable 0.10.0.0] Outpost medic is healing event NPC's that you are trying to kill in order to complete the event

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3268]
On the event huskcultambush where you get ambushed by couple of the NPC's, when you start attacking back at them the outpost medic will come and try to heal the NPC's, eventually getting in the way of the event. 

If you hurt the medic by accident the guards will come and attack you.

**Comment by itchyOwl** [comment]
Fixed in c54f5e2.

**Comment by Rokvach** [comment]
No issues, closing.
