### ISSUE TITLE
If you detach a Alarm that is currently on, the alarm sound will stay on even if you place the alarm in to your inventory

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3269]
Reported in Unstable 0.10.0.0 RC1 but apparently been around for a while now. 

Easy way to annoy other members of the crew

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61544070a2551f2c6bc182679b0c3e9f6bdc1b6d

**Comment by Rokvach** [comment]
No issues, closing.
