### ISSUE TITLE
Server console commands and permissions

### ISSUE THREAD

**Issue by dangranos** [Regalis11/Barotrauma#327]
It seems that there is a system of permissions made for "debug" console commands, but apparently it is only available from the server GUI. Obviously, when hosting using a dedicated server there is no GUI, so those permissions end up completely useless.

**Comment by NilanthAnimosus** [comment]
This is implemented already, however the main issue is that the Dedicated Server still has no way to assign console commands or assign a preset. if you use the client or manually edit the file you may assign console commands to clients.

**Comment by Cyprex** [comment]
in 0.8.0.5 you can edit Data/clientpermissions.xml like so:
<U+FEFF><?xml version="1.0" encoding="utf-8"?>
<ClientPermissions>
  <Client
    name="Cyprex"
    ip="10.11.12.13"
    permissions="EndRound, Kick, Ban, SelectSub, SelectMode, ManageCampaign, ConsoleCommands" 
    >
    <Command name="mission"/> 
    <Command name="clientlist"/>
    <Command name="fixhulls" />
  </Client>
</ClientPermissions>

Future versions will have the giverank command to assign preset ranks.
