### ISSUE TITLE
When stuck to the floor, water in parts of a sub or shuttle will constantly fill itself up with water.

### ISSUE THREAD

**Issue by Samsonite105** [Regalis11/Barotrauma#3270]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes when having a submarine or a shuttle on any sort of solid ground, the submarine or shuttle will constantly fill itself up with water. Even after fixing all the walls and pumps, the water will begin to empty only to flood itself back up again.

**Steps To Reproduce**
From what I've seen, the only times I've had this issue is when sunk into some sort of solid ground. So these are the steps I would attempt, though they aren't completely foolproof.
1. Grab a shuttle or submarine (shuttles are easier to do this with because of their relatively smaller size)
2. Crash the shuttle into the ground and make sure it floods.
3. There's no guarantee this works, but it's the best steps I can think of

**Version**
Barotrauma v0.9.10.0 (Release Windows, branch release, revision 2876b0a66). Running on Windows 10

**Additional information**
I've had this happen a few times, but not too often. However, this issue makes it impossible to move the submarine or shuttle due to the game believing it's flooded.

**Comment by Rokvach** [comment]
I haven't seen fluctuating water levels for a while now, I think this has been fixed
