### ISSUE TITLE
When too many NPC's occupy the same area, they start to spaz out as they are trying to keep their social distancing

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3271]
Video:
https://streamable.com/wpy0hh

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62ad3262702ae2d7eb584486455c8ca962bcd553

**Comment by Rokvach** [comment]
No issues, closing.
