### ISSUE TITLE
[Unstable 0.10.0.0] Event dialog closes if a mission dialog opens up in the middle of a event

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3273]

**Comment by Regalis11** [comment]
Did some testing in v0.10.1.0, and it seems at least now all the mission notification appears in the event dialog directly (on all characters, regardless which event they have active). Event dialogs from other events also just get placed in the currently active dialog.

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad54224911dab4efda4097d845600b447bbac6ed
Turned mission unlocked message into a popup notification and prevented mission unlock conversation from showing up for everyone

**Comment by Rokvach** [comment]
No issues, closing.
