### ISSUE TITLE
[Store Interface] Item can become unsellable if sold locally but refused by the server

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3274]
This can especially with high latency.

Steps to reproduce:

1. Start a game with two clients
2. Use `simulatedlatency` for both. Something like 1.5 seconds should be enough to make the testing easy.
3. Sell enough items to the store to bring the store balance down.
4. With both clients, place enough items in the sell crate so that if one client's items would be sold the merchant wouldn't be able to afford the other client's items anymore.
5. Sell the items with the first client, and before the second client receives the update, sell the items with the second client.
6. Notice that all the items the second client tried to sell have disappeared from the sell list and they won't be shown even after reopening the interface, but only some of them have been actually sold and have disappeared from the inventory.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@615a752

**Comment by Rokvach** [comment]
Haven't noticed any issues, seems to be working correctly. Closing.
