### ISSUE TITLE
Unstable - Rare FPS eating Thalamus breed caught on cam! (performance issue identified)

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3275]
**Description**
Thalamus flesh gun caused significant FPS drop for people on the server. The tentacle seems to be grabbing many times per second until it stabilises. As soon as it stops doing that, FPS gets back to normal, as can be seen in the clip.
Clip: https://streamable.com/p2xlp8
**Steps To Reproduce**
Get grabbed by Thalamus in the right way

**Version**
Unstable
**Additional information**
Game ran butter smooth otherwise on MP. Feels great.

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/1818e08c243a1523bc483b0f54cf70f5292f9115

**Comment by Rokvach** [comment]
Tested, didn't notice any issues. Seems to be working correctly. Closing.
