### ISSUE TITLE
[0.10.1.0] This module has no junction box connection

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3277]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/86422050-f8547180-bca9-11ea-8fb2-d9a3bccb4656.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd54891ea9e541279df76459dddd2c362749b4a4

**Comment by Rokvach** [comment]
No issues, closing.
