### ISSUE TITLE
Add methods to spawn/delete and use items / shoot projectiles via xmls

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#328]
The idea is simple, but essentially there is still no function to delete an item based on conditions for it (IE, if its condition hit 0 aka "OnBroken" but is meant to be a multi-use item)

In vanilla this could be used to say, delete a 0-condition bandage that has been applied.

Additionally the ability to spawn/use/fire items and their projectiles, allowing for magazines on guns, or essentially item conversion from conditions to a different kind of item.

Either as a new xml tag or a part of the status effects system itself, this would be a cool feature for the game to be able to handle for modding and a few vanilla mechanics.

**Comment by Regalis11** [comment]
Partially implemented in 9dd9425, items can be deleted by status effects now
