### ISSUE TITLE
[Unstable 0.10.1.0] Buttons found on wrecks are really small

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3282]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9bd7134f-f0cf-484a-affd-903fe09a8740)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c6f076d5-9d90-4452-bbc2-5b594f1fcd66)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9dad2772171b6e1ab71eecfa6d04e894ea04265a

**Comment by Rokvach** [comment]
No issues, closing.
