### ISSUE TITLE
Smoke detector's Output and FalseOutput properties do nothing

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3283]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Smoke detector always sends out 1 or 0 regardless of what the Output and FalseOutput properties are set to.

**Version**
Any

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c3ee62f19826d6efaabadf998c780511c8d1a692

**Comment by Rokvach** [comment]
No issues, closing.
