### ISSUE TITLE
Missing connection between map locations

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3285]
Noticed on Singleplayer

Tested on dev branch
Commit: https://github.com/Regalis11/Barotrauma-development/commit/7800bc37a5bb1cc1a3ef04abf8243da1bdfd9876

Save: [https://app.zenhub.com/files/93301055/ad4f1ef3-d8e7-4a34-b340-72f990953c8e/download](https://app.zenhub.com/files/93301055/ad4f1ef3-d8e7-4a34-b340-72f990953c8e/download)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fc91c34a-cc0f-46b6-bcf1-42e231bea507)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/70feb0864123a0ecfcc99b8204c537878c68c3e2

**Comment by Rokvach** [comment]
No issues, closing.
