### ISSUE TITLE
[0.10.2.0] Multiplayer - Player characters keeps being added into CharacterData instead of overwritten every level transition

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3287]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was playing multiplayer and was noticing my character inventory kept on reverting between 2-3 different sets of my inventory states. In one I had a grenade that I picked up. In the other one I have partially used bandages from another level. In the last, I don't have any bandages because I used them awhile ago. However these inventory kept on alternating everytime I transitioned.

**Version**
0.10.2.0

**Comment by Kaillera** [comment]
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/4870842/Multiplayer.zip)

You can see my character Kaillera and a few others are saved multiple times in the charactedata file instead of overwritten.

**Comment by Udrakan** [comment]
Thats got to be the reason for the ever shifting reputation I keep having on my MP save!

**Comment by Kaillera** [comment]
Save was from 0.10.1.0.

**Comment by Kaillera** [comment]
Issue seem to have stopped after I removed all 0.10.1.0 characters and duplicates.

**Comment by Kaillera** [comment]
Apparently this also happens in 0.10.2.0. You just have to keep playing the campaign with multiple people and it eventually happens.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/553913efd5b57f94337161803f751a1589b0d317

**Comment by Rokvach** [comment]
No issues, closing.
