### ISSUE TITLE
[Unstable 0.10.2.0] Azimuth bottom coilgun isn't properly restricted

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3289]
You can shoot at the hull in both ways

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8760db27-5af2-4f5b-a4f9-f453ac8b00a5)

**Comment by danielasteljoki** [comment]
Is this a griefing concern? I'd rather you be able to shoot at monsters latched on to the hull.

**Comment by Rokvach** [comment]
Yeah mostly griefing or accidents, wouldn't want to constantly go patch up the same area when someone tries to shoot at a crawler and accidentally just fires at the hull.

**Comment by danielasteljoki** [comment]
Adjusted in 464abfc.

**Comment by Rokvach** [comment]
You can still hit the hull if the sub is moving down, but I can see how restricting it even more might be difficult if there's some small creatures on the right  side of the sub.

**Comment by danielasteljoki** [comment]
I wouldn't restrict it any more, because we need to be able to hit monsters on the hull. Let's get back to this if it's a real griefing concern.

**Comment by Rokvach** [comment]
Closing.
