### ISSUE TITLE
Relays are causing issues again

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#329]
Some of these issues might be related to bad wiring as I'm still doing tests but there's one that is definitely a bug in the latest game update. I have a couple of submarines with ballasts connected to relays only for both power and signals and turning on the power causes them to flood the ship even if they have no actual power to work. They stop doing this as soon as there's enough power to make the pumps work. The only way I've found to stop this, is to make it so the relays are toggled off before starting the reactor.

The other minor issues is they are still burning or causing junction boxes wired to them to burn but I'm not sure those are bugs yet.

**Comment by ChikoEduardo** [comment]
I'd like to add they are also causing docking doors/hatches to break. I have a couple of docking hatches wired to a relay so I can turn them on/off and I noticed this since they now have breaking sounds.

**Comment by NilanthAnimosus** [comment]
That was one of the first things I noticed with the HSE Kullvero carrier when doing the testing, with the batteries set to 0% by default on those shuttles the charging docks more or less broke as if their voltage was far too high, though I never saw that issue on a HSE kullvero carrier before with its docks until the changes to the grid from 0.8.0.0+

**Comment by ChikoEduardo** [comment]
I guess I'll post this here, since this is still open. It seems power_in and power_out are not supposed to be working properly. You can wire two power_in and they would behave as if they were the power outlet in junction boxes. This causes power to leak where it's not supposed to, when you are trying to make more than one grid in a ship.

**Comment by Regalis11** [comment]
Fixed in f4b85b3
