### ISSUE TITLE
[Feature Request] Add a warning when deleting save files.

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#3295]
**Description**
Currently there is no warning when deleting a save file it's just instant, I recommend adding one, so we can avoid infuriating moments.

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/09a3eb153e665aba7c43d0e22108149d5d250166

**Comment by Rokvach** [comment]
No issues, closing.
