### ISSUE TITLE
[0.10.2.0] Right side Hypercurrent isn't strong enough against fully upgraded vanilla sub engines

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3299]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can go through the hypercurrent on the right side of the map with a fully upgraded vanilla sub engine.

**Comment by Regalis11** [comment]
The strength of the current should increase linearly the further you get from the level, so it should eventially stop the sub regardless of how powerful your engine is. Gave this a quick test with a fully upgraded Dugong and by setting the force of the engine to 10,000, and couldn't spot any issues.

**Comment by Kaillera** [comment]
Ah okay. Thought we can just keep pushing through it cause it wasn't a immediate push back.

**Comment by Kaillera** [comment]
I think there needs to be a flashing warning that you're exiting the map or something. I've been seeing games where the players kept driving right cause they can.
