### ISSUE TITLE
[Feature Request] <=== Spoiler ===>

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3300]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost Event of something like this with a senile old man held in a military outpost prison.
![Capture](https://user-images.githubusercontent.com/5086682/86516509-20012200-bdef-11ea-8a7a-0ed8e9a4de44.PNG)

Only after you been there once yourself, you can talk to the senile old man more sanely.

**Version**
0.10.2.0

**Comment by Regalis11** [comment]
That's a nice idea. :) More references to [the thing] are coming for sure in future updates when we flesh it out more.
