### ISSUE TITLE
[Unstable 0.10.2.0] Engineers try to turn on the reactor while docked to an outpost.

### ISSUE THREAD

**Issue by MrAsbestos** [Regalis11/Barotrauma#3301]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Engineers try to turn on the reactor while being docked, this action wastes fuel supplies and could potentially annoy new players, you can tell them to shut off the reactor to avoid this issue, but it would be better if they ignored the reactor while docked.

**Steps To Reproduce**
Really easy to reproduce.
1. Start Campaign
2. Engineer will try to turn on the reactor.

**Comment by Regalis11** [comment]
@itchyOwl Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e3425fc?

**Comment by itchyOwl** [comment]
Yeah. Should be fixed. The description of that commit was a bit misleading: the bots should _only_ do that when ordered. Not autonomously.

**Comment by Rokvach** [comment]
No issues, closing.
