### ISSUE TITLE
French localisation/transalation typo "rien da cassé" at start of medic training

### ISSUE THREAD

**Issue by Mohorelien** [Regalis11/Barotrauma#3303]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
French dialog translation typo. 

Displayed : "[...] rien **da** cassé ? [...] "
Should be : "[...] rien **de** cassé ? [...] "

**Steps To Reproduce**
Launch medic training mission, wait for the first transmitted message .

**Version**
Windows, vanilia 0.9

**Additional information**
Love your work, keep up !

**Comment by EdusFF** [comment]
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/ce74aff81e225d6db6b7abe2efa643780e365bda

**Comment by Rokvach** [comment]
No issues, closing.
