### ISSUE TITLE
[Feature Request] Add a delay before the dock/undock button can be pressed

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#3304]
It's rather annoying having two people press the button to dock only for it to immediately undock since no one coordinates. I suggest adding a half-second cooldown after a press where the button cannot be pressed again. To be clear, this is a suggestion for the UI of the nav terminal **only.** Changing docking port behaviour seems like a bad idea.

**Comment by hubismal** [comment]
the cooldown should probably only apply after pressing the button and successfully docking. else someone pressing the button too early could screw you over when you tried to dock while moving

**Comment by FamiliarBreakfast** [comment]
Yeah, that's probably a good idea. I can already see how it could be abused otherwise.
