### ISSUE TITLE
Thalamus can be very quickly killed from the exterior using piercing ammo

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3306]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shooting piercing ammunition precisely at organ location kills the thalamus in just a couple of shots. Since organs have some weapon exceptions to prevent this (depth charges, railgun shells...) piercing coilgun ammo should maybe get added on the list.

**Steps To Reproduce**
-find thalamus
-aim at the organ location
-shoot at that spot with piercing coilgun ammo
-organs get damaged and destroyed

**Version**
both stable and unstable

**Comment by ezjamsen** [comment]
This almost feels to me like a legitimate tactic, @itchyOwl  would removing the railgun protection for organs make sense? If so then this would then be consistent and not be a bug.

**Comment by RobertRoberts2020** [comment]
At the same time, I just dropped literally 5 boxes of exploding ammo and didn't even manage to break out of the fleshgun even though everything surrounding it was completelly gone.
