### ISSUE TITLE
Tutorial is buggy

### ISSUE THREAD

**Issue by Dropgunner** [Regalis11/Barotrauma#3307]
- [x] I have searched the issue tracker to check if the issue has already been reported.
yes
**Description**
When you are constructing a fire extinguisher before you get the next quest to :*FABRICATE A  FIRE EXTINGUISHER" you cant finish the tutorial 
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Play the tutorial and construct a fire extinguisher 

**Version**
Which version of the game did the bug happen in . Also, please include the operating system you're using (Windows/Linux/Mac).
Windows
**Additional information**
Lol

**Comment by ekqvist** [comment]
Steps to repro:

1. Start the Mechanic Tutorial
2. Play through the Tutorial until you get to the "Deconstruct an extra oxygen tank" objective
3. Only pick up the sodium from the highlighted cabinet
4. Deconstruct the oxygen tank inside your diving mask
5. Fabricate the fire extinguisher

You will still have the "Deconstruct an extra oxygen tank" objective active and cannot proceed to the next room.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@841ddf4

**Comment by Rokvach** [comment]
No issues, closing.
