### ISSUE TITLE
Depth Charge detonates inside launch tube if sub going down fast enough

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3309]
**Description**
Title
**Steps To Reproduce**
Select Orca
Do controled flooding to go down at >25km/h
Launch Depth Charge with explosives
Engineering room blows up instantly

**Version**
Unstable
**Additional information**
Could be because of the tube being too high.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6bc896174c9656f4be6115bf84b8be41efc8f900

**Comment by Rokvach** [comment]
No issues, closing.
