### ISSUE TITLE
BTE 5.1 causing a crash

### ISSUE THREAD

**Issue by monstered99** [Regalis11/Barotrauma#331]
My Barotrauma version is v0.8.0.5 and whenever I use the BTE content package and I open the airlock or the ship starts leaking I get an error message about crashreport.txt being saved. There is also a long list of errors in the console after starting the game. 
[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1799206/crashreport.txt)
![bez tytulu](https://user-images.githubusercontent.com/37237941/37240138-cd5e06d2-2447-11e8-92b8-a34a40e70065.png)

**Comment by NilanthAnimosus** [comment]
The reason this crashes is 5.1 does not define the sounds.xml properly. The mod needs to be updated. as I recall on their discord there is already a 5.2 in the works to fix this.

It's not strictly a game bug as it is the game not handling no sounds.xml to load. the author is working on (Or already has) an update for this.

**Comment by monstered99** [comment]
@NilanthAnimosus Thank you very much, I'm looking forward for the updated version.
