### ISSUE TITLE
[0.10.2.0] Typhon2's issue

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3312]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. The top airlock's pump has no power wire.
2. The alarm in the reactor room next to the door is not wired.
3. The floor where the engine is has a green wire item.

**Version**
<0.10.2.0

**Comment by ezjamsen** [comment]
Fixed in dev

**Comment by Rokvach** [comment]
No issues, closing.
