### ISSUE TITLE
No way to loot chemicals that explodes in water from wrecks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3313]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There are no ways to transfer chemicals that explodes in water from wrecks like sodium back to the submarine.

Suggestion: Chemical Crate

**Version**
<0.10.2.0

**Comment by Regalis11** [comment]
Made chemical and explosive crates waterproof in https://github.com/Regalis11/Barotrauma-development/commit/268ff62100defa1d0b36818af9660b10ac81f7e6

**Comment by Rokvach** [comment]
No issues, closing.
