### ISSUE TITLE
[0.10.2.0] Bots - Climbing the wrong ladder when there's two ladders next to eachother

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3314]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have two ladders and two sets of waypoints to go with them and they are near eachother with no regular movement waypoint in between, bots will climb the ladder that they run into first instead of the one after when they're trying to climb.

**Version**
0.10.2.0

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@e078026 and included in the next unstable. Please test it again. And @Rokvach too.

**Comment by Kaillera** [comment]
Haven't seen this issue since 0.10.4

**Comment by Rokvach** [comment]
Closing.
