### ISSUE TITLE
[Unstable 0.10.2.0] Unable to Close End of Round Summary Overlay while Mid-Round

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3318]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
End of Round Summary from the previous round is open during a new round, (blocking the entire screen), and there is no close button to close it, nor can any keys close it.

**Steps To Reproduce**
Not sure if this will allow you to reproduce it but what I did before it happened is as follows:
- Be In an Outpost (I think we were in a City)
- Just before we left I went AFK
- When I returned, it was a new round and the screen was as in the screenshot provided in additional information.

**Version**
0.10.2.0 revision 5544317655
Windows 10 64 bit.

**Additional information**
I don't know if this this of any consequence, but:
1) I had moderator permissions
2) The outpost had the husk infection event
3) The game crashed while I was selling stuff in the outpost
[crashreport (24).log](https://github.com/Regalis11/Barotrauma/files/4887229/crashreport.24.log)
Screenshot:
https://cdn.discordapp.com/attachments/668819422919524352/730165538319499384/20200707165456_1.jpg

**Comment by Regalis11** [comment]
Could not find a way to reproduce this, but I added some measures to hopefully fix this in https://github.com/Regalis11/Barotrauma-development/commit/a80c8f384949777c8de0d282107bbea7255b79ac. It's also now possible to close the summary with Esc even if the continue button is not visible.

**Comment by Rokvach** [comment]
No reported cases of this happening, considering how common it was previously I can tell that the issue has  been fixed. Closing.
