### ISSUE TITLE
Vent component does not update OnActive effects

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3319]
[relatively easy FR]
OnActive does not work in vent component probably because Vent.cs doesn't have UpdateOnActiveEffect() in its Update() function. Normally I would not care but the game also uses OnActive in vents to make it play sound so this might mislead some modders. Could have an impact on performance but I doubt it.

Edit: normally i would actually care because apparently conditionals don't forcefully get variables like i thought they would and absolutely everything goes through updateonactiveeffect. pls fix regalis!!!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61e3313f3eab81850e4c09391ed92dfb09b56867

**Comment by Rokvach** [comment]
No issues, closing.
