### ISSUE TITLE
Multiplayer Campaign is not syncing creatures correctly

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#332]
Version 0.8.0.5 Nilmod (Need to test vanilla, don't have the time so im writing this issue for now)

The save files appear to sync, no kick from desync, correct submarines load.

The creatures however were invisible to clients, I can't imagine why this is the case and I still need to do testing. I tried teleporting some crawlers and I couldn't see them on campaign seed 9tiDXWc6 using the submarine KSS-Adira-V2

spawning with debug commands had the fish show. and when I Tested my same mod code on the mission gamemode the fish also showed.

On a clients join, the seed when hitting back from the campaign GUI was indeed 9tiDXWc6 and they still couldn't see the creatures.

I need to get back and test this on vanilla using the same conditions, 

I just noticed something severely weird. but the submarine save is labled KSS-Flora-V5.sub and the gamesession.xml contains:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Gamesession savetime="12:27, 10/03/2018" submarine="KSS-Flora-V5" mapseed="aego3XZj">
  <MultiPlayerCampaign money="15000">
    <map currentlocation="46" seed="aego3XZj" size="1000" discovered="46" passed="" />
  </MultiPlayerCampaign>
</Gamesession>
```

Yet the serverlog contained:
[10/03/2018 12:38:05] Submarine: KSS-Adira-V2
[10/03/2018 12:38:05] Game mode: Campaign
[10/03/2018 12:38:05] Level seed: 9tiDXWc6
[10/03/2018 12:38:05] Press TAB to chat. Use "r;" to talk through the radio.

But the above could be an issue of my mod. If I can reproduce it in vanilla I'll add more information.

As in theory the game should sync campaigns from the seed.

**Comment by Regalis11** [comment]
Could be related to ceaba2f

**Comment by Regalis11** [comment]
Haven't encountered this bug since ceaba2f, so I think this can be closed.
