### ISSUE TITLE
[0.10.2.0] Very hard to tell which is a default or custom submarine in the menus

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#3320]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![602960_20200708064507_1](https://user-images.githubusercontent.com/62313026/86882023-7324ee80-c0e7-11ea-8c6f-accd6fa3a949.png)

Can you tell which is a default or which is a custom sub? To put it in perspective, the dugong is a default sub, but if you have lots of custom subs downloaded from servers it gets very confusing.   The Dugong in particular there are several custom versions of the dugong that I downloaded from servers which adds to the confusion, on top of that you need to scroll down the list of subs to find the default subs. 

I think it will be less confusing and better  if there is more distinction in the sub selection menus in both single player and Multiplayer server hosting between what is a DEFAULT sub and what is a CUSTOM sub.   Maybe have the default sub name title be in a different colour? So you can easily tell by text that its a default sub instead of a custom,  or maybe make a new menu category for custom subs/Default subs? 

**Version**
0.10.2.0

**Comment by EdusFF** [comment]
Added in: https://github.com/Regalis11/Barotrauma-development/commit/553c779ccdc77929ce3d45fa1c4576f6346427a2

**Comment by Rokvach** [comment]
No issues, closing.
