### ISSUE TITLE
Crash when trying to select an outpost terminal

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3321]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reported in #3318: the client seems to have crashed when trying to select an outpost terminal.

**Steps To Reproduce**
Unknown

**Version**
v0.10.2.0

**Additional information**
Crash report:
[crashreport.24.log](https://github.com/Regalis11/Barotrauma/files/4889245/crashreport.24.log)

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/97b37c6e142027ba8f8c3ca0f60cc93bb0ab25d8

**Comment by Rokvach** [comment]
Didn't encounter any issues with this, I did see a custom sub with no preview while hosting yesterday and nobody crashed when they interacted with the terminal. As there is no clear steps to reproduce I will just close this for now. Closing.
