### ISSUE TITLE
Connected docking ports are not updated for the Nav Terminal

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3323]
Connected docking ports are checked at the start, but never updated even though the code suggests that they should be updated at set intervals. Therefore, you can disconnect old docking ports after starting the game and the "Dock" and "Undock" prompts will still be there for the port, even though it won't receive the signal if the button is pressed. The docking mode also won't be enabled for docking ports connected mid-game if they were disconnected at the start.

Steps to repro:

1. Start a new campaign with the Dugong
2. Leave the starting outpost
3. Power up the reactor and set the sub on autopilot to maintain the position near the outpost docking port
4. Open the Nav Terminal interface to see the "Dock" button
5. Open the rewiring interface for the Nav Terminal and remove the wires from the "toggle_docking" connection
6. Open the Nav Terminal to still see the "Dock" button
7. Press the "Dock" button to see that nothing will happen

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@53911d7

**Comment by Rokvach** [comment]
No issues, closing.
