### ISSUE TITLE
Outpost light not wired

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3324]
**Description**
Its in the engineering section of the Milda Outpost. Sending a screen and save.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
![image](https://user-images.githubusercontent.com/59519434/86915344-21e62080-c122-11ea-8c76-65e983176dd4.png)

[Save 559.zip](https://github.com/Regalis11/Barotrauma/files/4890434/Save.559.zip)

**Comment by Rokvach** [comment]
No issues, closing.
