### ISSUE TITLE
[Unstable 0.10.3.0] Mission marker position doesn't update if the mission item is inside a toolbox

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3327]
If you loot a logbook from a wreck salvage mission in to a toolbox the mission marker will stay where you placed the item in to the toolbox, the marker will update if you take the logbook out of the toolbox and will again stop updating if you place it back in to the toolbox

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d241d69396b5b645e7b7fd7042baa255abb2abd

**Comment by Rokvach** [comment]
No issues, closing.
