### ISSUE TITLE
Texts overflow from labels in Typhon 2

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3329]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![w485thkjairf](https://user-images.githubusercontent.com/14351070/87024691-1f4b0000-c1e2-11ea-9748-f42850a3b742.png)

Texts overflow in German and probably some of the other languages as well.

**Version**
v0.10.0.0 and later

**Comment by ezjamsen** [comment]
Fixed in dev

**Comment by Rokvach** [comment]
No issues, closing.
