### ISSUE TITLE
Characters that don't need air (IE. husks) can be killed via status effects that deplete it (Welding fuel)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#333]
Version 0.8.0.5

Characters that have NeedsAir = false can still have their air depleted and be killed if using welding fuel with diving masks on them, they also cannot replenish air as they do not require it.

Technically this makes sufforin capable of being a gaurenteed kill to every species in the game, even an endworm in a single use, This cannot be intentional.

**Comment by Regalis11** [comment]
Fixed in d8b5bbc
