### ISSUE TITLE
Prevent selling items equipped on head/cloth/headset/armor slots

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3331]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can still sell items equipped on head/cloth/headset/armor slots.

**Version**
0.10.3.0 & 0.10.4.0

**Comment by Udrakan** [comment]
Diving suits should be sellable from armor slot

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@9973e59

**Comment by Rokvach** [comment]
No issues, closing.
