### ISSUE TITLE
Bots - Welding bots leave breaches partially welded, go to another breach, then return to the original one

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3335]
**Description**
Title.
In clip 1, at 0:20 you can see bots leaving a significant hole in the hull and go for another
In clip 2, at 0:28 same thing happens with the left bot
**Steps To Reproduce**
Cause multiple large hull breaches
Have bot fix leaks
Observe his behaviour

**Version**
Unstable

**Additional information**
Clip 1: https://medal.tv/clips/28202256/d1337B5bKft7
Clip 2: https://medal.tv/clips/28202705/d1337t4UmwTE

**Comment by itchyOwl** [comment]
It's a known issue, but not strictly a bug: The bots target leaks, not walls. When the wall does not leak anymore, the objective is completed.
