### ISSUE TITLE
Bots - Bots don't detect if other bots are trying to fix the same leak

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3336]
**Description**
As shown in 2 clips (same clips from https://github.com/Regalis11/Barotrauma/issues/3335)
Multiple bots will try to fix the exact same leak, hurting each other in the process.
It seems this isn't intentional, because with item repairs, bots can detect if somebody is already trying to fix the item.

**Steps To Reproduce**
Have multiple bots with Fix Leaks order
Cause multiple leaks
**Version**
Unstable

**Additional information**
Clip1: https://medal.tv/clips/28202256/d1337A6RQthY
Clip2: https://medal.tv/clips/28202705/d1337cPgxTk3

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@fb644dd.

**Comment by Kaillera** [comment]
[0.10.502]

Multiple Bots still run to the same leak and same item to repair. Also been noticing that if you have a Faraday artifact constantly EMPing a item you're fixing, the bot can override and steal your repair EXP. It's not just with the Faraday. If two bots are running to the same item and are very close in distance, the later one can steal the first bot repair EXP.

**Comment by itchyOwl** [comment]
That shouldn't happen though. Can you give more precise steps on how I can reproduce the issue? The simpler, the better.

**Comment by Kaillera** [comment]
Have two bots on fix leak. Just plasma cut a wall. I see both of them running towards the leak.

As for the repair stealing one, go on the humpback. Have three bots on fix items. try to deconstruct a Faraday artifact. Get a screwdriver and repair the junction box when it gets EMP. You'll see the bot somehow replace you from repairing the junction box.

**Comment by Kaillera** [comment]
Leak Video
[2020-09-07 06-45-25.zip](https://github.com/Regalis11/Barotrauma/files/5182658/2020-09-07.06-45-25.zip)

Repair Video
[2020-09-07 06-46-53.zip](https://github.com/Regalis11/Barotrauma/files/5182660/2020-09-07.06-46-53.zip)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@4abe66b and Regalis11/Barotrauma-development@5bdf1e4

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce either of the issues, working correctly. Closing.
