### ISSUE TITLE
[feature request] pets

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#3338]
Preferably those native to Europa, like trained mudraptors or ballast piranha. A glitch occured where a mudraptor wasn't attacking us and it was delightfully fun. Ideally, they'de occasionally have outbursts if you don't feed them well or something. You could have a pet dealer at the station who'll sell you pets and supplies for money, and pets could fight for you and eat corpses. You could also have other animals but I think pet mudraptors would be dope.

**Comment by Regalis11** [comment]
This is actually on our todo list, we'll start working on it after the campaign update is out. :) Closing the ticket as we generally avoid having feature requests in the public issue tracker
