### ISSUE TITLE
(Unstable) Husk station event bug

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#3339]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had a husk cult event where a guy asked me for eggs, I talked to him when i had 1 in my inventory, sold it free, and the eggs didnt dissapear.

**Steps To Reproduce**
I didnt have the eggs when the event appeared, i got them deconstructing calyxinade in my sub. then talked to him, gave it free, and its still on my inventory

**Version**
Windows

**Additional information**
This happened twice, the first time i had the eggs in my  toolbox and the NPC did not take them until i got them into my hotbar, they still didnt dissapear when "he took them".
Sorry for my english ;)

**Comment by rav2n** [comment]
Also faced with this.
1) The event does not take into account eggs lying in the toolbox
2) I had several of them. I received the award for only one (1000).
3) they also did not disappear from the inventory.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/14a3882b392d79b7fa5c4b7e647d96e4c6116f0c and https://github.com/Regalis11/Barotrauma-development/commit/a3d140216c2246001bb4b7c943fcd9fc50808939

**Comment by Rokvach** [comment]
No issues, closing.
