### ISSUE TITLE
End round sound loops sometimes.

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#334]
I've had this happen three times so far. The music that plays when the round ends just keeps playing over and over and won't stop, even if I leave the server. Don't know what causes it.

**Comment by Regalis11** [comment]
I think this is fixed now by juan's audio rewrite (f50c37d)

**Comment by juanjp600** [comment]
I wasn't able to replicate it after the rewrite, but I didn't change anything specific to the EndRound music, so I'm not absolutely sure that this was fixed.
