### ISSUE TITLE
Suggestion for voice communication: Headset channel switcher and PA system.

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#3342]
It would be cool if players could switch channels using a single headset while in game, so that each role can divide its communication. Maybe have secure channels only usable by id_card roles.

I think it would be useful to have a PA system that broadcasts voice across the ship interior/certain speakers?

**Comment by FamiliarBreakfast** [comment]
These are both features that me and others have been requesting for a long time. Additionally, the ability to play prerecorded messages over radio/PA would be nice. I could see how that could bloat filesize, tho.

**Comment by bavarianblacksmith** [comment]
Yeah, I've been experimenting with putting color coded sets of headsets in my subs that are all on different channels, and using a terminal to broadcast between them to the captain. It's a bit clunky though.

**Comment by Regalis11** [comment]
This is actually on our todo list (and has been for way too long!). Now that we're starting to be less busy with the campaign update, I'll bump it up in priority to get it finally implemented.

Closing this ticket as we generally avoid having feature requests in the issue tracker.

**Comment by bavarianblacksmith** [comment]
No worries, thank you for the update!
