### ISSUE TITLE
[Singleplayer] Newly bought sub reverts back to the previous sub when pressing "Retry" right after switching to the new sub

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3343]
Tested on dev branch
Commit https://github.com/Regalis11/Barotrauma-development/commit/45c27ef1a3ada475670fbf297433d5b45d05715f

Repro steps:
1. Buy a Remora
2. Switch to Remora
3. Leave outpost
4. Press "Retry"
5. You find yourself inside the started sub instead of the sub you switched to

I also got a error "Error while loading the map (Start location index out of bounds)" when I first noticed this issue, but haven't been able to reproduce the error since, but the error came up by doing the exact same steps so it might just depend on the level type.

**Comment by EdusFF** [comment]
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/09c5182fdb6925f9741819a992a2bce14161706a

**Comment by Rokvach** [comment]
Wasn't able to reproduce, working correctly. Closing.
