### ISSUE TITLE
Unable to rotate the 'lighting element' of any items.

### ISSUE THREAD

**Issue by DerTontaiLama** [Regalis11/Barotrauma#3344]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Rotating any items - lamps, machinery, objects - will only rotate the object itself, but not the underlying lighting that's associated with it. Any item in the game that includes a "lightcomponent" in its settings, basically.

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/3674854/87161225-7f19d780-c2c4-11ea-935f-f4adad1e23f2.png)

**Version**
0.10.4.0
Windows 10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8a55083496b400d3cbd4703952addff6d5a347f8

**Comment by Rokvach** [comment]
No issues, closing.
