### ISSUE TITLE
Hats should use hidelimbtype="hair"

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3345]
[Bug, Oversight]
What the title says.
![2020-07-10-104504_70x65_scrot](https://user-images.githubusercontent.com/47284081/87173014-becbc980-c29a-11ea-8f6a-228a2e35f985.png)
![2020-07-10-104607_68x71_scrot](https://user-images.githubusercontent.com/47284081/87173017-bf646000-c29a-11ea-805a-1f37d59a7918.png)
Either that or the ponytail has gotta go.

**Comment by Udrakan** [comment]
I've noticed this with a couple "smaller" hairstyles too.

**Comment by itchyOwl** [comment]
We have an internal ticket about this (#1175). So the issue is known, but all the proposed solutions require quite a lot of work. So it's on hold for now.
