### ISSUE TITLE
[0.10.4.0] Multiplayer - Newly Hired crew disappears if the level after resulted in game over and reloaded

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3346]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Newly Hired crew in multiplayer disappears if the level after resulted in game over and reloaded

**Version**
0.10.4.0

**Comment by Kaillera** [comment]
Seems like purchased sub on the round before game over deletes the purchased sub too.

**Comment by Rokvach** [comment]
Couple ways to reproduce this issue in multiplayer campaign

Tested on bugfixes branch

A)
1. Hire crew members
2. Leave outpost
3. Press "Server Lobby"
4. Press "Continue"
5. Notice that all the newly hired bots are gone

B)
1. Hire crew members
2. Leave outpost
3. Die
4. Let the round end
5. Press "Continue"
6. Notice that all the newly hired bots are gone

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/b63ea7cc1618bc352c71a6f93b2834dc211c59cc

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue, working correctly. Closing.

**Comment by Kaillera** [comment]
This also affects submarine upgrades apparently.
