### ISSUE TITLE
Lights not mirrored vertically

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3348]
[Bug, Inconsistency]
Using horizontal mirror will properly mirror all of an items lights, surprisingly. The same cannot be said for mirroring it vertically. Lightcomponents will not have their sprites properly mirrored upside-down.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b1f24aafaad83f58d474d1bbcc6b1c641b3a6013

**Comment by Rokvach** [comment]
I was still able to reproduce this in bugfixes branch

Steps:
1. Load Dugong in sub editor
2. Select Navigation terminal
3. Press Mirror Y
5. Turn on lights and see that the light doesn't match with the device

**Comment by Rokvach** [comment]
Was able to reproduce this

Steps: 
1. Select navigation terminal
2. Press Mirror X
3. Press Mirror Y
4. Tun on lights and now the light should be off again

**Comment by Rokvach** [comment]
No issues, closing.
