### ISSUE TITLE
Can't connect to servers

### ISSUE THREAD

**Issue by EmeraldNotAminer** [Regalis11/Barotrauma#3349]
- [x] I have searched the issue tracker to check if the issue has already been reported.
(I am new to GitHub so I couldn't find it)

**Description**
connection
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
how to reproduce: join a server
**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
0.9.6.0? (I had to check through a sub, it is before the new campaign update with sub editing) windows
**Additional information**
ok so, before we had the update about wrecks it was SUPER easy to join a server, now I have to try about 15 times in order to connect and sometimes it will connect you then automatically disconnect you, it just says "connection failed" and nothing about why, it just says it failed to connect

**Comment by EmeraldNotAminer** [comment]
*EDIT* it is game version, 0.9.10.0

**Comment by Jlobblet** [comment]
@EmeraldNotAminer if you have a lot of submarines in your Submarines/ folder that might affect it - it's worth clearing them out if you have a lot.
