### ISSUE TITLE
Linux Package for 0.8.0.5 contains 0.8.0.4 Server Executable

### ISSUE THREAD

**Issue by Cyprex** [Regalis11/Barotrauma#335]
md5sum Barotrauma\ v0.8.0.4/Barotrauma*.exe
389e11214416920c35ca2ce249d211db  Barotrauma v0.8.0.4/Barotrauma.exe
1460914e79fa91aec0db50d4697121b1  Barotrauma v0.8.0.4/BarotraumaServer.exe
md5sum Barotrauma\ v0.8.0.5/Barotrauma*.exe
c75b7e270f6e468e96dcc93d398ab906  Barotrauma v0.8.0.5/Barotrauma.exe
1460914e79fa91aec0db50d4697121b1  Barotrauma v0.8.0.5/BarotraumaServer.exe
Trying to connect to a started server gives an error message telling you that you need 0.8.0.4.

As a workaround the Windows Server Executable appears to work.

**Comment by Regalis11** [comment]
Should be fixed now!
