### ISSUE TITLE
StartGame error when returning to lobby either by Game Over or "Server Lobby"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3352]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you play multiplayer and get returned to the server lobby either by Game Over or "Server Lobby", pressing Continue may result in a StartGame error. Players will be all stuck in the server lobby until they rejoin and then hit Spectate. For some reason all the hired crew members gets deleted too.

**Version**
0.10.4.0

**Comment by Kaillera** [comment]
Seems like purchased sub on the round before game over deletes the purchased sub too.

**Comment by Regalis11** [comment]
The hired crew getting removed should be fixed now (#3346). Do you remember what the error you got was or do you happen to have any log files or screenshots of it?

**Comment by Regalis11** [comment]
I'm afraid we can't do much about this without knowing what the error was. Closing

**Comment by Kaillera** [comment]
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__82" has failed

I keep forgetting to dump the error when I got it before, but it's usually along the line of this

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/91618036-5f636f00-e957-11ea-8a1f-21aee932b9eb.PNG)

This is really all it gives when it happens.
