### ISSUE TITLE
[Unstable 0.10.4.0] Some campaign missions don't make much sense...

### ISSUE THREAD

**Issue by Dexo21** [Regalis11/Barotrauma#3353]
**Description**
For example, you want to do an artifact mission as you will be going to a natural formation (a place where there's no outpost). You get the artifact, and if you get to the natural formation's end and enter it, the artifact would just disappear and mission will be complete. Where does the artifact go? I think it would make more sense if the artifact would still remain until you reach an outpost or something like that.

There may be more missions like these, but I'm not 100% sure about that.

_EDIT: It looks like there is after all, if you do a cargo mission, the cargo would just disappear and you'll be given credits magically even though there's nobody to pick up the crates or give credits at the natural formation._

**Version**
Unstable v0.10.4.0

**Comment by Regalis11** [comment]
We're planning on implementing missions that span more than one round in the future, which will also take care of this oddity. Since this isn't strictly a bug and we avoid having feature requests in the public issue tracker, I'll close this.
