### ISSUE TITLE
[Unstable 0.10.4.0] Small mistake - one of the walls can be selected in researchmodule_02

### ISSUE THREAD

**Issue by Dexo21** [Regalis11/Barotrauma#3354]
**Description**
In researchmodule_02, the research table room wall doesn't have the Non-interactable option checked, so players can select it. It's basically nitpicking at this point, but I thought I'd report it.

![Capture](https://user-images.githubusercontent.com/65886873/87222614-c912c400-c37d-11ea-843a-d730e265fc42.PNG)

**Version**
Unstable v0.10.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7db28123053a2482acf4f90b62e5c6d4f4444b0e

**Comment by Rokvach** [comment]
No issues, closing.
