### ISSUE TITLE
Typo: Brian not Brain?

### ISSUE THREAD

**Issue by DranKof** [Regalis11/Barotrauma#3355]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think there's a typo, "Brain" random NPC name should probably be "Brian".
![image](https://user-images.githubusercontent.com/20900852/87221386-8e2e7300-c320-11ea-9c6d-b777288aeee9.png)

**Steps To Reproduce**
Generate lots of random NPCs till it appears.

**Version**
Windows; Public Beta (most recent as of today)

**Comment by Regalis11** [comment]
Apparently Brain is an actual name: http://www.thinkbabynames.com/meaning/1/Brain

**Comment by DranKof** [comment]
> Apparently Brain is an actual name: http://www.thinkbabynames.com/meaning/1/Brain

It also says it's an alternate spelling of the more common Brian, and if you scroll down, according to that website, it says that no one really uses it in or outside the US and everyone exclusively uses the more common spelling, Brian today.

Today, it is a [last name](https://en.wikipedia.org/wiki/Brain_(surname)) more often than it is a first name--those are harder to change.

In the end it's your choice if you want to reclaim that spelling, but the vast majority of users will not know this and will just think you have a typo.
