### ISSUE TITLE
0.10.x Lacking access to map for peons in MP campaign 

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3357]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Annoyance: Only the person who selects the next travel location/mission can ever see the map in multiplayer campaign.
Expected: Any way to open the map for any player at all times. (Want to see where we are and where we go)

**Version**
0.10.x win

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/8c19a00f6c1bb4e76302a5e5c2d8a8f5d13dab57

**Comment by Kaillera** [comment]
Working in 0.10.502

**Comment by Rokvach** [comment]
Closing.
