### ISSUE TITLE
[Unstable 0.10.4.0] Successfully completing Outpost Event - Unconscious Person gives you a second Medical Skill

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3358]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A second medical skill field is created and can be seen in the character profile UI. If you do the event again, the new medical skill field will be improved. 

**Steps To Reproduce**
1) Successfully complete the Unconscious Person Outpost Event
Prompt saying Medical Skill lvl 2 should scroll across the top of the screen
2) Open the character profile (TAB > click on the character)
You should see a new medical skill field at the bottom of the skill list 

**Version**
0.10.4.0, revision 20132d25fb
Windows 10 64 bit

**Additional information**
screenshot:
![extra med skill](https://user-images.githubusercontent.com/58775950/87232384-98865680-c38c-11ea-9c66-1afa75e5aa7d.jpg)

**Comment by EdusFF** [comment]
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/67fc5c35189e9a160c93bd16a91854f784293039

**Comment by Rokvach** [comment]
No issues, closing.
