### ISSUE TITLE
[Suggestion] Multiple editor autosave slots

### ISSUE THREAD

**Issue by GophTheGreat** [Regalis11/Barotrauma#3359]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It would be nice to have more than the single 5-minute autosave slot.

**Version**
0.9.10

**Additional information**
Story time: I will admit that this is entirely my fault. I was working on a wreck version of a sub and had accidentally saved it in two places because I have the Wreck Finalists content package installed. I worked on it a bit until I finally noticed and then I deleted the "clone" save and exited the editor, only to realize that I deleted the more up-to-date version and I went back into the editor to confirm. I paused editor and went digging through Windows to try to find if I could recover the file somehow and then I realized that the autosave should've captured it, but by the time I got back to the editor the autosave had been written over at least once.

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/c7b6c85d5bcb00df2c915dd6d72396c74538d132

Auto saves now have slots and 8 slots by default that is configurable in player config, the button has been replaced by a dropdown shoving the name of the submarine and a tooltip showing how old the auto save is.

**Comment by Rokvach** [comment]
Could the time information be displayed inline on the list rather than on the tooltip? Ofc would need to work on the smallest resolution as well

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d9c37640-925f-4ca3-8052-a39dbf8a1183)

**Comment by 3e849f2e5c** [comment]
Changed the entry to this a simplified time display in https://github.com/Regalis11/Barotrauma-development/commit/1e02f7a69101d8db866a2bf05105a5e2a1919d67 and kept the full detailed age in the tooltip

![](https://kosblue.com/e/xjrund.png)

**Comment by Rokvach** [comment]
No issues, closing.
