### ISSUE TITLE
[Question for Devs] Any way to rotate repairtool barrel?

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3360]
[Question, Feature Request]
Is there any way to rotate the "barrel" of the repair tool changing which direction the repairtool "fires" in? Normally repairtools are rotated by a players aim, but now that they're able to be "statically" used without a character holding them, things like water sprinklers and lava vents need to have their aim rotated. 
How do I do this? thanks.

**Comment by Regalis11** [comment]
Added BarrelRotation property in https://github.com/Regalis11/Barotrauma-development/commit/2770169e79aa378bc608fda246c4cdb4f4e4b3e8

**Comment by Rokvach** [comment]
This change hasn't affected the general gameplay in anyway, closing as if its broken its only broken on the modding side, in which case we can just re-open this ticket. Closing.
