### ISSUE TITLE
Error while loading the map (Start location out of bounds)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3361]
Branch: bugfixes
Commit: https://github.com/Regalis11/Barotrauma-development/commit/7db28123053a2482acf4f90b62e5c6d4f4444b0e

Repro steps: 
1. Start a multiplayer campaign using the save
2. Error should show up when round starts

Doesn't seem to be affecting gameplay in anyway

Save:
[https://app.zenhub.com/files/175046454/d0e9404e-6e1b-4797-b4bd-e94f81517f4c/download](https://app.zenhub.com/files/175046454/d0e9404e-6e1b-4797-b4bd-e94f81517f4c/download)

**Comment by Regalis11** [comment]
It seems the save file doesn't include the index of the start location for some reason. Not sure how that can happen, but I added some measures in https://github.com/Regalis11/Barotrauma-development/commit/429220356d21fa52d05fafd3c17b830e4ddc4ba3 that should prevent it from causing any issues (the game will just select the leftmost inhabited location as the start location if this happens).

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue by using the same save, looks to be working correctly. Closing.
