### ISSUE TITLE
Wiring Junctions to a power source in a certain way, multiplies power output

### ISSUE THREAD

**Issue by Mezzokoko** [Regalis11/Barotrauma#3363]
**Description**
Wiring two junctions in parallel to a power source and then having one of the junctions take on load, will make the other junction have the same amount of power, without increasing the output of the power source, effectively doubling the power output.

**Steps To Reproduce**
https://cdn.discordapp.com/attachments/220881718666723328/732256067316088832/out.mp4

1. Wire two junctions directly to a power output, such as a nuclear reactor.
2. Make one or both of them draw power. If one of the junction box has no device that can consume the power, it will burn out.

**Version**
Windows 10
Barotrauma v0.9.10.0 (ReleaseWindows, branch release, revision 2876b0a66)

**Comment by EtiamNullam** [comment]
Its the same problem as in #3238, possibly #3458 too. Though you named and described it better at its root.

If you connect multiple junctions/relays to output from a power producer (reactor or battery out) it will apply highest required power to every box/relay.

Maybe just allow only one wire out of `power_out` in reactor and battery?
