### ISSUE TITLE
[Unstable 0.10.4.0] Failed wreck mission, when logbook was in toolbox.

### ISSUE THREAD

**Issue by Altren** [Regalis11/Barotrauma#3365]
+ [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Failed to complete wreck mission. For some reason, even though I retrieved captains log and had popup about it being retrieved.

**Steps To Reproduce**
Play campaign in a single player mode, single character in a crew. Retrieve logboox and place it into toolbox on character and keep it there to the end of misson. 

**Version**
0.10.4.0

Game save right after docking. Captains log book in the slot 9 toolbox on character. Renamed .save to .gz, because github wasn't accepting it.
[Save.gz](https://github.com/Regalis11/Barotrauma/files/4915421/Save.gz)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7defc768f2f7d6106aaef73b50c87207fccaaef1

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue, looks to be working correctly. Closing.
