### ISSUE TITLE
[0.10.4.0] Reproducable Lighting Miscalculation with massive light occluder

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3366]
Magical shadows appear from edge of occluders. Reproduce:
1. Make a ridiculously long inner wall, put a lamp above it with enough range to reach the occluder, casting shadows.
![2020-07-14-174400_994x384_scrot](https://user-images.githubusercontent.com/47284081/87483714-ff5c7780-c5f9-11ea-8ea4-d5ad957def83.png)
2. Magical shadow seems to originate from the far corner of the occluder. A bit hard to see in the pictures provided, but move the lamp away and the shadow gets worse, move it closer and it gets better somewhat. Moving it left and right "tilts" the shadow, so it's definitely something wrong with the lighting calculation. Should be easy to experiment with.
![2020-07-14-174504_426x390_scrot](https://user-images.githubusercontent.com/47284081/87483716-fff50e00-c5f9-11ea-90f5-597c0a9b8fb4.png)
![2020-07-14-174513_572x349_scrot](https://user-images.githubusercontent.com/47284081/87483718-008da480-c5fa-11ea-978a-4b9cc66067e0.png)
It's extremely unlikely that anybody is going to make a sub with a single wall this long, and if they do they can just split it up into multiple walls. But apparently I was the first to ever find this so here it is.

**Comment by Ek-Videogames** [comment]
This is also a known issue with something to do with door occluders

**Comment by hubismal** [comment]
Note that this bug affects the tutorial level. Might make it more high priority.

**Comment by Jade-Harleyy** [comment]
Seems to be fixed, but the shadow randomly disappears when you move the light around.
![image](https://user-images.githubusercontent.com/67431770/121918767-fdb09d80-ccfb-11eb-864f-352084256322.png)
![image](https://user-images.githubusercontent.com/67431770/121918853-0bfeb980-ccfc-11eb-89f1-62fb705ca009.png)

**Comment by Regalis11** [comment]
Finally got around to fixing this: https://github.com/Regalis11/Barotrauma-development/commit/1d59daba5e6c9f1480b5dc06d32fd181e35e36ef

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
