### ISSUE TITLE
[Unstable 0.10.4.0] Dugong wire menu bug

### ISSUE THREAD

**Issue by MyNameIsEpic** [Regalis11/Barotrauma#3367]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have screwdriver in your hand wire menu in the oxygen generator does not open. And with a wrench open without problems.
 
**Steps To Reproduce**
^. Working only on Dugong

**Version**
Windows. Unstable 0.10.4.0

**Additional information**
Video of this - https://www.youtube.com/watch?v=WIGPLHkfEv8

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
