### ISSUE TITLE
[0.10.4.0] - No particle effects from mining ores?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3368]
Specifically the line of code in the vanilla plasma cutter
`<ParticleEmitterHitItem identifiers="ore" particle="iceshards" ...`
doesn't seem to actually work since it was added a few versions ago.

Seems to suggest that cutting ores is supposed to emit the rock gib effects.
Is ores producing particles intentional or was it just left in the code and forgot about?

**Steps to reproduce:**
Go mining.
![image](https://user-images.githubusercontent.com/55356135/87553772-52c5d880-c681-11ea-8312-c242eaa4cdc7.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54a82fed3fb8372cc727393a1b58f49aca19820d

**Comment by Rokvach** [comment]
No issues, closing.
