### ISSUE TITLE
[Unstable v0.10.4.0] Cannot unlink hulls in sub builder

### ISSUE THREAD

**Issue by Dexo21** [Regalis11/Barotrauma#3369]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The title says everything. If you link a hull with another hull, you can't unlink them. The usual workaround is just to delete one of the hulls and place a new one.

**Steps To Reproduce**
For example, place two hulls. Link each hull to each other.

**Additional information**
If you link a hull to whatever object, you also can't unlink them both without deleting the hull itself.

**Comment by Regalis11** [comment]
Looks like the only way to unlink hulls was to right-click the linked hull. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/db75e1df261abd73fb9372ac4febd79483e7ba69

**Comment by Rokvach** [comment]
No issues, closing.
