### ISSUE TITLE
v0.8.0.5 server claims wrong game verison

### ISSUE THREAD

**Issue by goofolph** [Regalis11/Barotrauma#337]
I'm hosting a barotrauma server on a linux box running v0.8.0.5 and when I try to join from another computer also running v0.8.0.5 the server reports

```couldn't join the server (wrong game version)```

The client shows the error message

```
Couldn't connect to the server
Version 0.8.0.4 required to connect to the server (Your version: 0.8.0.5)
```

This is using the download from the homepage.

**Comment by Regalis11** [comment]
Duplicate of #335
