### ISSUE TITLE
[0.10.4.0] Thalamus organs disappearing on load in the editor

### ISSUE THREAD

**Issue by GophTheGreat** [Regalis11/Barotrauma#3374]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon loading a wreck that I'm making, the organs, flesh gun ammo sacks, and cell spawn organs all disappear from the wreck. This is repeatable; I can replace them, save, and then immediately load the same file the organs will disappear.

**Steps To Reproduce**
Download this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2158340193

Open the Chasm_Wrecked wreck in the editor.

The organs will be missing. 

Place more organs and save, then load the sub again. The organs will be missing.

**Version**
v0.10.4.0, Windows 10 64-bit. 

**Additional Information**
Here's a gfycat of it happening: https://gfycat.com/bowedhardtofindgibbon

**Comment by Regalis11** [comment]
Looks like any item that's placed outside a hull doesn't get saved. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef8aa24e297eae0a6498145493edaaac0f4a7383

**Comment by Rokvach** [comment]
No issues, closing.
