### ISSUE TITLE
Persistent Mod load order needed

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3376]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Modders need a way to set/manipulate load orders of mods.
Manipulating the mod loadorder is important for modding, especially e.g. for mods that modify other mods (so called "modmods", also hofixing mods)

The mod load order cant be set in mods itself. 
Setting the load order in the settings menu isnt possible. The order how mods are listed is changed/re-sorted (e.g. a diffferent when loading a mission and returning to the main menu)

Expected:  Mod load order can be set on hosting clients and dedi. servers, where the client takes over the load order given by the server.
E.g. a simple tag system in mods, to prioritise load orders, is thinkable with an average default value if none is given.

**Comment by Rokvach** [comment]
Couldn't spot any issues while testing this, would need proper community testing to fully test it out.

**Comment by Rokvach** [comment]
Working correctly, closing.
