### ISSUE TITLE
Join-in-progress for MP campaigns needed

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3377]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Joining a MP campaign that's running is currently very clunky and could definatly need some love.
Right now players can only join from the lobby during transitions between station and mission.

Letting players join while being docked at a station would already be a great help.

**Comment by hubismal** [comment]
a simple solution for this would just be to enable standard in-submarine respawning while the players are docked

**Comment by Regalis11** [comment]
The players can now spawn in the sub mid-round in outpost levels: https://github.com/Regalis11/Barotrauma-development/commit/9731b844d373b1d56a628b95ff9955c7d1efdf6c

**Comment by hubismal** [comment]
only concern about this is now you technically have infinite manpower to fight outposts if your character spawns in as a security officer over and over. it might be advisable to have characters who die in outposts forced into spectate until the submarine undocks and they're spawned.

**Comment by Rokvach** [comment]
No issues, closing.
