### ISSUE TITLE
Dedicated - Submarines move noticeable wobbly.

### ISSUE THREAD

**Issue by LandonGam3r** [Regalis11/Barotrauma#338]
I am not sure how to describe it differently, but there is a noticeable lag when the sub is moving. I am currently testing a second server on a VPS and at the moment this remains the only boundary I see yet for running a dedicated version smoothly. Earlier bugs are gone and configurations are loaded correctly.

Very glad to see improvements on this end!

**Comment by Regalis11** [comment]
I believe this is finally fixed with the recent networking improvements
