### ISSUE TITLE
Selling batteries and oxygen tanks with slight condition

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3380]
Cannot sell to outposts oxygen tanks or batteries which have been slightly 'damaged' via being in a container.
What if outposts could still accept these items as long as they are above a minimum condition like 95%.

**Comment by hubismal** [comment]
even if it's not realistic i think a nice solution to this problem would be to make almost all consumable items combinable the way chemicals are, most notably batteries and oxygen tanks.

**Comment by ekqvist** [comment]
With Regalis11/Barotrauma-development@64c891b, items should now be sellable as long as their condition is over 90%. I agree that it can be frustrating that, for example, an Oxygen Tank can become unsellable if contained in a Diving Mask and the Mask is equipped even for just a few seconds.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
