### ISSUE TITLE
Unable to vote for submarines in the lobby

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3383]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to select a sub in the lobby to play in mission mode.

**Steps To Reproduce**
1. Start the server from the game menu.
2. Attempt to select any submarine other than the default set in the config file.
3. Start a round.

**Version**
0.10.4.0

**Additional information**
The sub can only be replaced by changing the server configuration file. In this case, you need to protect against overwriting the file. The shuttles get out without any problems.

**Comment by rico6822** [comment]
It already happened to me once as well but in a different manner https://www.youtube.com/watch?v=TJ8ZeteZLHE

This bug somehow was in the game already before the steam version.

If you watch the start carefully you will notice to the left how a different submarine is chosen.

**Comment by rav2n** [comment]
I will reformulate. Voting for boats does not work. Random selection and manual selection by moderators work.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/437af8e7ecdfdc344594eb60e84d5bca301f151a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
