### ISSUE TITLE
0.10.4 Health scan hud removes mouse hover info

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3384]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wearing Health scan hud  removes mouse hover info from other characters.
After Ive loaded a campaign and I was wearing the Health scan hud  mouse over no longer showed e.g. the "E to talk" info on NPCs. Taking the HUD off didnt restore the info.
I suspect its because it shows the health stats in its place.
Expected: hover info options not removed or at least restored when taking off the medi HUD.

**Steps To Reproduce**
My steps
1. load campaign where you already wear the Health scan hud 
2. mouse hover info about options  no longer shown

**Version**
win, 0.10.4, tested in SP campaign

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26ac7407677606fdff3b2414bd03e1379652502f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
