### ISSUE TITLE
0.10.4 Selecting mission and travel target when docking at a station

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3385]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I docked off a station with a mission I have the "enter xxx" button on top of the screen.
Pressing that opens the map, i can select a new target + mission, press start mission and get into the station Im in.
Its probably not intended to be like this, hehe

Expected: No "Enter xyz" button, but having to redock at the station when i want to return.
And a fail status when I redock while I actually had a mission? (Personally I think I should rather keep the selected mission)

**Steps To Reproduce**
1. Leave station
2. press button "Enter xyz" on the top screen
3. map screen opens, select travel target, mission, press start
4. Be docked at the station

**Version**
.10.4. Win, tested in SP campaign

**Comment by Regalis11** [comment]
No longer occurs in v0.10.500.0

**Comment by Rokvach** [comment]
No issues, closing.
