### ISSUE TITLE
0.10.x Cheesing Mission availability

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3388]
You can almost endlessly gain missions by undocking(without mission)-redocking and save-reload.
Everytime the outposts are loaded/initialised (?) mission givers are refreshed.
Feels cheesy and wrong. Maybe just QOL, but should be easy to fix.

**Comment by hubismal** [comment]
Might be beneficial to have a CheckMissionQueue event.... thingy. to just abort missionevents. for example missionevent_killmonster could check to see if there's already a monster killing event or something available to select from the map.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/84e212fb327fd944a43b8f081f5c4939cf96670f

**Comment by Rokvach** [comment]
Tested both singleplayer and multiplayer

Once you have picked up the initial events and missions you won't get another set of events when you re-dock, which is the correct behavior. I also tested that the new set of events does trigger once you've waited for 10 minutes and that also is working correctly. Closing.
