### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jkj32** [Regalis11/Barotrauma#339]
I was hosting a server and it involved controlling monsters, i kept getting console popups with this error over and over
"Attempted to access a potentially removed ragdoll. Character: crawler, id: 2119, removed: False"
Here is the full crash log
[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1839971/crashreport.txt)

**Comment by Regalis11** [comment]
Fixed in ceaba2f
