### ISSUE TITLE
Turrets receiving "NaN" will break their rotation

### ISSUE THREAD

**Issue by Mezzokoko** [Regalis11/Barotrauma#3390]
**Description**
A turret receiving "NaN" from an arithmetic node due to an illegal float operation, such as division by zero will completely break its rotation unrecoverably, even if valid signals are sent afterward.

https://cdn.discordapp.com/attachments/443885748064616459/734093259227398235/nanbug.mp4

**Steps To Reproduce**
Create a NaN signal by dividing by zero and feed it into **position_in** of a turret.

**Version**
Windows 10
Barotrauma v0.9.10.0 (ReleaseWindows, branch release, revision 2876b0a66)

**Comment by Rokvach** [comment]
I wasn't able to reproduce the issue by using the steps above, looks to be fixed and working correctly. Closing.

**Comment by Mezzokoko** [comment]
[Lucia Kalor - NaNBug.zip](https://github.com/Regalis11/Barotrauma/files/4981872/Lucia.Kalor.-.NaNBug.zip)

Uploaded the sub from the clip with the bug still present.

**Comment by Mezzokoko** [comment]
Turns out division by 0 only returns NaN in the specific case of the dividend being zero aswell, for any other input it maxes out at the limit of the node.

[nanbug.zip](https://github.com/Regalis11/Barotrauma/files/4981960/nanbug.zip)
https://cdn.discordapp.com/attachments/443885748064616459/737285365848604703/nanbug2.mp4

**Comment by Rokvach** [comment]
The fix isn't public yet
