### ISSUE TITLE
Multiplayer Campaign showing duplicate Save (and problem when playing wrong one)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3395]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Duplicate of #2313. Issue was never fixed even back during 0.9.9.0.

**Description**
While playing an ongoing multiplayer campaign, when you check the Load Save tab, you may see two duplicate saves of the same file. If you load the duplicate temporary save and play it, your campaign progres will not be saved after you finished playing, The temporary save file disappears when you close the server, taking the progress with it.

**Steps To Reproduce**
Start a multiplayer campaign. Play a few rounds, reload save at some point, play more. Check the Load Save tab.

**Version**
0.9.7~0.10.4.0

**Additional Informations**
Characterdata.xml does save properly.

**Comment by Regalis11** [comment]
Unfortunately I wasn't able to reproduce this.

Were you the owner of the server or had you joined it as a client? To be clear, by "check the load save tab", you mean returning back to the server lobby and opening the "load campaign" tab?

**Comment by Kaillera** [comment]
It happens on both P2P and Dedicated. Owner or Manager (Since they can access the save). Yes I do mean either returning to the lobby or failing a level, and opening the load campaign tab.

**Comment by Kaillera** [comment]
I think I may have caught onto what it is.

Apparently temporary server saves are also stored in the directory below shows up when loading saves:
C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Data\Saves\Multiplayer

**Comment by Regalis11** [comment]
Found a way to reproduce this now.

1. Host a dedicated server
2. Start a client from the same folder on the same machine and join the server
3. Start a campaign round, which will cause the server to send the save file to "Data/Saves/Multiplayer"
4. Go back to the "load save" tab and you should now see the duplicate save

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cf72eb1d7adb63fd77dc789ad991b317ca22bb7d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
