### ISSUE TITLE
0.10.4 Editior sub has multiple entries in campaign purchase screen

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3397]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A sub Ive edited shows up twice in the SP campaign sub purchase screen. 

First I thought that it was because of the editor autosave file, but no fix.
Theres also no multiple sub files to be found.

**Steps To Reproduce**
1. Create sub in the editor, save
2. Start/load campaign - sub shows up twice

**Version**
0.10.4, win, sp campaign, not tested in mp campaign

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce this. Tested it in a couple of different ways, and in all cases there's only one sub entry in the purchase menu:

1. Open Dugong in the sub editor
2. Save it, overwriting the old sub file
3. Start a new campaign with another sub
4. Only one Dugong entry in the menu

1. Create a new sub from scratch, save it as "subtest"
2. Start a new campaign with Dugong
3. Only one "subtest" entry

1. Open "subtest" again and save it
2. Start a new campaign with Dugong
3. Only one "subtest" entry

1. Open "subtest", save it as "subtest2"
2. Start a new campaign with Dugong
3. Only one "subtest" entry and one "subtest2" entry

Could it be that you had one copy of the sub in the Mods folder and one in the Submarines folder?
