### ISSUE TITLE
0.10.4 No more wreck generation in SP, corrupted savefile?

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3399]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Edit] After some hours of testing and finally decompressing the save file I noticed that the map data was corrupted. Somehow all connection type entries had been overwritten with generationparams="coldcavernstutorial". (details in the 4th post)
This cant be done by the involved mod, so this seems to be a game bug. 0.10.4 source was just released yesterday and I had not time to check for code that could have caused this. Also I dont know if this is related to the other save file breaking bug reports on unstable.

[Original]
After some days my SP campaign no longer generates wrecks (mods used EK Armory, EK Utilities, Wreck Finalists).
No wreck generation is confirmed - Even Salvage Wreck mission have no wrecks and just the target pad on the seabed.

Was working flawless before. Save file has the mods listed, console shows no errors. 
From my knowledge the Wreck Finalist mod is the only used mod that impacts level generation (wrecks + LevelGenerationParameters.xml overrides) 

Expected: An unchanged mod setup keeps working without issues. 
Removing and re-adding the wreck mod shouldnt impact newly generated levels. (Obvious that it will impact the actual, already generated level when changing the mod setup and loading)

**Steps To Reproduce**
Verification: 
1. Starting new sp campaign
2. taking salvage wreck misions
3. no issues, works as intended

Issue reproduction:
1. Start new campaign with the mod setup.
2. save in the starting outpost.
3. remove Wreck finalist mod.
4. Load save.
5. Take and start mission (easiest a Wreck Salvage mission)
6. No more wrecks generated.

Expected: Levels generate without issues with the actual loaded mod setup. A mod removed before the generation of a level should not impact the level generation.

**Version**
0.10.4, Win, SP campaign with  EK Armory, EK Utilities, Wreck Finalists mods.

**Additional**
Can provide the save file if needed!

**Comment by CurePindal** [comment]
Issue reproducable. Report edited.

**Comment by CurePindal** [comment]
I could boil down the issue to the LevelGenerationParameters.xml overrides in the Wreck finalist mod. Other mods are not involved.

Testsetup 1:
If a SP campaign gets saved with Wreck finalist mod and reloaded without the mod no more wrecks will be generated.

Testsetup 2: Removed LevelGenerationParameters.xml overrides  from the mod
If a SP campaign gets saved with Wreck finalist mod (without the level overrides) and reloaded without the mod wrecks will be generated as expected.

Problem is I dont know if this is a problem with the xml overrides or how the game handles said overrides (maybe something gets saved to the save file?)

For reference: Wreck competition finalists "LevelGenerationParameters.xml"
https://pastebin.com/7AzQXRZe

**Comment by CurePindal** [comment]
The latest tests also didnt reveal the cause of lack of generated spawns, so I dove into the decompressed savefile and found that all "generationparams" in the map data of all connections had been set to "coldcavernstutorial".
E.g.:
```
 <connection passed="false" difficulty="26.833336" biome="theaphoticplateau" locations="77,127">
        <Level seed="Sarpedon LineaMehen Linea" biome="theaphoticplateau" type="LocationConnection" difficulty="26.833336" size="242000,50000" generationparams="coldcavernstutorial" />
      </connection>
```

Testing a connection by setting it to anything else than coldcavernstutorial (which has per definition no wreck spawns) suddenly spawns wrecks again as expected. 
Somehow the save file got wrecked.

**Comment by Regalis11** [comment]
This is normal, due to the changes to the level and map generation logic the wreck finalists mod is not compatible with v0.10.4.0 or other unreleased versions of the campaign update.
