### ISSUE TITLE
Large Inside Wall Tie H1

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3400]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Incorrect capture of the sprite

![image](https://user-images.githubusercontent.com/29980468/87975615-84e99700-cad4-11ea-9446-692ce4e5c4e6.png)

Version
0.10.4.0

**Comment by Rokvach** [comment]
No issues, closing.
