### ISSUE TITLE
[Feature request] RoomName for Oxygen Generator 

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#3401]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Quite often, on submarines, a separate compartment is allocated for the oxygen generator, but there is no corresponding name for the room. Life support? Climate control?

**Version**
0.10.4.0

**Additional information**
![EPYhfnRXkAIw1xQ](https://user-images.githubusercontent.com/29980468/87979680-18be6180-cadb-11ea-8daa-6591d7923ffe.png)

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/8f8bd087f182249a555f5cde2afda50089dd63fe

**Comment by Rokvach** [comment]
No issues, closing.
