### ISSUE TITLE
[0.10.4.0] (Sub-builder) Copy-pasting a docking hatch will make it spawn at an unreachable distance

### ISSUE THREAD

**Issue by Dexo21** [Regalis11/Barotrauma#3403]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Everything explained in the title. (Also, if you press F to focus on the docking hatch, your camera will be softlocked, making you unable to return to your submarine and having to resort to reloading a previous save)

**Steps To Reproduce**
1. Place a docking hatch.
2. Ctrl+C and Ctrl+V
3. Docking hatch nowhere to be found.

**Version**
Unstable v0.10.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/42890db6ff8474f55a3763e486a6c5da2aaf4029

**Comment by Rokvach** [comment]
Looks to be working correctly, closing.
