### ISSUE TITLE
Unable to host a game on linux client

### ISSUE THREAD

**Issue by TBleader** [Regalis11/Barotrauma#3404]
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am unable to host a server on the linux client. After filling out the name, max players, password, etc, and hitting start I am met with "The server process has closed unexpectedly. A crash report may have been generated." and then a "Connection failed." This is easy to reproduce on my system, as any attempt to start a server in game results in this error message. But as is the nature of linux, it might not be an issue with the software specifically but a weird problem that arises from my current configuration.

**Steps To Reproduce**
Host Server->Fill in details as desired->Press Start
**Version**
v0.9.10.0 (ReleaseLinux, branch release, revision 2876b0a66)
System info: 
Arch Linux, Linux 5.7.5-arch1-1 x86_64, 
NVIDIA GTX 1080, nvidia 440.82-24,
i7-8700K
Steam package versions: 1594252496 

**Additional information**
Every server crash log has the same issue.
`Exception: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek. (System.InvalidOperationException)
Target site: Boolean get_KeyAvailable()
Stack trace: 
   at System.Console.get_KeyAvailable()
   at Barotrauma.DebugConsole.UpdateCommandLine(Int32 maxTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/DebugConsole.cs:line 121
   at Barotrauma.GameMain.Run() in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 360
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 49`

I have attached a copy of the crash log. All 8 attempts have the identical issue. This may be related to other issues, but the only linux server issues I have found were specific to dedicated servers, and not hosting a server through the game. Given the server crash log mentions "Dedicated server crash report" though makes me think the same server program is used regardless.
[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/4958758/servercrashreport.log)

**Comment by mygamingaccount** [comment]
I'm unable to reproduce this.

I've hosted many games on Linux on 0.9.10, it still works on 0.10.4

I believe this is a user configuration problem. How do you start the game, @TBleader?

**Comment by TBleader** [comment]
@mygamingaccount 
Always bad to hear when it works fine for others. Just tested on 0.10.4 and I have the same issue. I start the game through steam. No launch parameters, just hit play, then Play Barotrauma. Then hit host game and fill out the info. Press start, and it tells me it failed to connect and that it created a log.

Log from attempt on 0.10.4
`﻿Barotrauma Dedicated Server crash report (generated on 07/31/2020 19:30:50)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.10.4.0 (ReleaseLinux, branch release, revision 965c31410a)
Language: English
Selected content packages: Vanilla 0.9, Cyclops Mk-II
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
Server (Round hadn't been started)


System info:
    Operating system: Unix 5.7.5.1 64 bit


Exception: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek. (System.InvalidOperationException)
Target site: Boolean get_KeyAvailable()
Stack trace: 
   at System.Console.get_KeyAvailable()
   at Barotrauma.DebugConsole.UpdateCommandLine(Int32 maxTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/DebugConsole.cs:line 122
   at Barotrauma.GameMain.Run() in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 366
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 49


Last debug messages:
   07/31/2020 19:30:50 - [07/31/2020 19:30:50]
  Saving banlist
   07/31/2020 19:30:50 - Selected shuttle: Venture
   07/31/2020 19:30:50 - Selected sub: Berilia
   07/31/2020 19:30:49 - Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean`

**Comment by mygamingaccount** [comment]
The reason the server fails to start is becaue according to to Barotrauma, `/dev/pts/1` is not a typewriter.
If you run the game from a container or chroot, make sure the devptsfs is mounted.
If you installed Apparmor or SELinux, make sure Barotrauma has access to those paths.

**Comment by TBleader** [comment]
Hm interesting. I don't run the game from a container, or chroot, nor do I have SELinux or Apparmor. 
/dev/pts/ has 0-5 which are owned by my user account, with the group tty and are rw accessible to the owner. I haven't manually fiddled with anything in this regard. I would assume the dedicated server process the game spins up when using host server is running with the same owner as the game itself, which is my user account so it would be weird why it wouldn't have access.
I'll try to do some digging on why it isn't working. 
What distro do you use? Are you starting the game and the server any special way other than how I described?

**Comment by nerdbeard** [comment]
I have the same problem on Ubuntu, since the first time I started the game (installed and executed by Steam).

**Comment by StarrKiss** [comment]
I'm having this same issue on Manjaro Linux, even when running it directly.

**Comment by exezin** [comment]
I get the same issue on ubuntu 20.04 out of the box, running the binary directly from a terminal does indeed resolve the issue and allow me to host a server.

**Comment by MShrimp4** [comment]
I also have the same issue on Gentoo, but it works fine when i run steam (plain steam, not steamCMD) on terminal emulator
