### ISSUE TITLE
Server browser constantly crashing

### ISSUE THREAD

**Issue by SenhorPatolino** [Regalis11/Barotrauma#3406]
- [X] I have searched the issue tracker to check if the issue has already been reported.

Can't play Baro because the server browsers keeps crashing, and when it works ( it isn't and its my third time trying ), it takes ages to show the list.

**Version**
Stable, Windows 10.

**Comment by CurePindal** [comment]
Without more info, like the crashlog, this is pretty hopeless to fix. Also computer specs.

**Comment by SenhorPatolino** [comment]
Got no crash logs, the game just freezes and after clicking 3 times it gets that white look and saying "not responding, close or wait", note that i waited 5 minutes so it really wasnt working, specs 
CPU : Intel Core i3-6006U CPU 2.00GHz     8GB Ram      Intel HD Graphics 520

i did look at task manager, memory ram its not the problem, gpu wasnt being used and only the cpu was being used but at 20%

**Comment by Regalis11** [comment]
This should be fixed in the upcoming campaign update (or current unstable branch)
