### ISSUE TITLE
0.10.4 Running game lobby doesnt show player roles

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3407]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When  joining a MP lobby thats not started I can see the player names color-coded by their selected roles.
When joining e.g. a running campaign all players are shown in grey.

Expected: Player names color-coded by role persists. When joining a running game I might want to see what roles had been selected for my own selection.

**Version**
0.10.4, Win, MP

**Comment by Udrakan** [comment]
Thanks for reporting this. I got so used to this that I stopped treating it like a bug.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/af91b9cb5f87b9d1668b529a6f3a9b8b51aafbde

**Comment by Rokvach** [comment]
No issues, closing.
