### ISSUE TITLE
Add purchase 'medical treatment' from outposts.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3408]
As injuries will now carry over onto outposts, it would be neat if you are able to get treatment from the station's medical facilities. 
( Cost scaling with the amount & the 'complexity' of injury )
This would give an interesting dynamic to submarines which may be lacking a medical officer.
?

**Comment by Udrakan** [comment]
Would be cool tying this with the reputation system
-price
-not providing the service at all
-not healing fully (will only heal up to certain % of condition)
-suspicious side effects
-max reputation: full recovery from all afflictions

**Comment by Regalis11** [comment]
This is on our todo list, closing since we have a ticket about this in our private repo (https://github.com/Regalis11/Barotrauma-development/issues/2118) and we generally avoid having feature requests in the public issue tracker
