### ISSUE TITLE
0.10.4 Can't climb ladders or access menus after ending round handcuffed

### ISSUE THREAD

**Issue by benguiden** [Regalis11/Barotrauma#3409]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In multiplayer campaign, if the round ends while you're handcuffed, you'll spawn back in no longer handcuffed, but you can't longer climb ladders and any menu that you attempt to open is immediately closed.

**Steps To Reproduce**
1. In a multiplayer campaign game handcuff yourself, then enter the outpost to have the round end.
2. Once you spawn back in you'll have the climbing and menu issues despite no longer being handcuffed.

**Version**
0.10.4

**Additional information**
Didn't test if this happens in single player but I imagine it does.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fda0d764c43089ec179dbcfa7e24a15c31b85465

**Comment by Rokvach** [comment]
Working correctly, closing.
