### ISSUE TITLE
Crew orders: Custom 'MinimapIcon' for modded ship systems.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3411]
Modding feature request.

Ordering crew to operate reactors and weapons which are modded items defaults to the generic 'minimap' icons.
As the vanilla sprites are defined in Orders.xml there is no way to alter or add new sprites without overwriting the orders menu itself. What I suggest is some method of defining this item-side, for instance
```
    <MinimapIcon id="modded_machine">
      <Sprite name="Custom_Icon" texture="Mod/CustomCommandSprites.png" sourcerect="0,0,128,128"/>
    </MinimapIcon>
```
on an item.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/43a7b1b4bf1be7636cc1b7271ae255301ca40430. The icon is configured like this (specifying the ID of the item is not necessary): 

`<MinimapIcon texture="Mod/CustomCommandSprites.png" sourcerect="0,0,128,128"/>`

**Comment by Rokvach** [comment]
No issues, closing.
