### ISSUE TITLE
Game crashes when a coilgun recieves NaN in position_in.

### ISSUE THREAD

**Issue by Ngushurst** [Regalis11/Barotrauma#3412]
**Description**
Short Story: In making a formula to align coilgun aims, the formula would occasionally produce NaN for an unknown reason, which would then crash the game immediately when input into the coilgun.

More info in the additional info section.

**Steps To Reproduce**
This link goes to a google drive folder with the submarine([Teeny Ship Alpha .8](https://drive.google.com/file/d/14baSSvNc4N50Y_iCOC2xBLErAs2QwGyI/view?usp=sharing)), which can produce the issue quite consistently.
1. Open and test the submarine.
2. Move to and enter the right periscope (just left of captain's spawn)
3. Type in "Dual" into radio chat (or a terminal) to align the left gun by use of the formula.
4. Swing the cursor from left to right quickly. This generally crashes the game within a handful of seconds, and always in less than a minute. Slow movement does not cause an error.

**Version**
v0.9.10.0 (ReleaseWindows, branch release, revision 2876b0a66)

**Additional information**

The specific system takes the right coilgun's angle "A", the distance to an imaginary line "Y" units away, and the distance "X" units between the two coilguns and uses them to find "Alpha", the angle that makes the other coilgun's aim cross the right's on the imaginary line. This is the right cluster of modules above the submarine. X=43. Y=90 (max=999999 min=30)
The left is a system by which to quickly adjust "Y" in game, and functions normally.

Theta = A - 180
R = y/sin(Theta)
Theta'= acos( ( R-Xcos(Theta) ) / sqrt( X^2 + R^2 - 2XRcos(Theta)  ) )
Alpha = 180 + Theta + Theta'

There are two systems that I implemented to try to stop the error. The first is a few relays that restrict the angles that can be input into the formula, defining a range of 190-350 degrees (brown and green wires below formula). The second system can be spotted by its use of red wires, and tries to intercept NaN by the use of a Signal check for "NaN" and a delay to slow the signal so it could be blocked by a relay. While neither of these systems worked completely, the angle restriction stopped the guaranteed crash (angles <180 || >360 have no solution, and produce NaN) and helped reduce the general odds of it occurring the most. The Signal check was ineffective as far as I was able to tell.
I am unsure what in the system produces NaN (probably acos), though dividing by zero produces the maximum value of the component as opposed to infinity or NaN.

On a final note, exiting and re-entering the periscope with the dual formula active (the command toggles it) will sometimes cause the left coilgun to transcend reality. By that I mean to say that the barrel will irreversibly vanish and the shots fired from it will somehow hit the nose of the submarine despite there being numerous segments of hull separating it from the gun's base location.

**Comment by Rokvach** [comment]
I wasn't able to reproduce the issue by using the steps above, looks to be fixed and working correctly. Closing.
