### ISSUE TITLE
Fuel rods are buoyant - their density is 5

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3413]
**Description**
Title. Check "tools.xml". Fuel rods have density of 5, like oxygen tanks, which makes them rise up when underwater, which doesn't seem to make any sense. Maybe there is some cool fact about fuel rods that I don't know (sealed air maybe?). It doesn't seem intuitive that they should float.
![image](https://user-images.githubusercontent.com/59519434/88467147-193c6b00-ced4-11ea-86ee-4e69f10e3f1b.png)

**Steps To Reproduce**
Drop fuel rod of any kind into ballast
It will float

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9529162b5e32e87639bd084976e8d270a942f8bd

**Comment by Rokvach** [comment]
No issues, closing.
