### ISSUE TITLE
[MODDING] Inventory and Equipement slots are super-hardcoded

### ISSUE THREAD

**Issue by ModderSlayerOfVanilla** [Regalis11/Barotrauma#3415]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Request from Pico no Boku#5198 (Discord)

Actually, there is no way to change the number and pictures of inventory and equipement slots like "Headset" "Head" "Card" etc. Doing a .dll manipulation seems unlikely in performing just that.

Having the possibility to edit, using xml code, inventory and equipement slots could be a very strong feature for the modding community.

**Version**

Any version of Barotrauma on Steam.

**Comment by Udrakan** [comment]
I always yearn for more moddable stuff!

**Comment by MrWereWolph** [comment]
I am making a mod by editing the style.xml that changes the entirety of the UI for custom sprite sheets. Three years later and this is still hardcoded?

**Comment by Jasontti** [comment]
Tested.
Created simple localmod to see if icons could be loaded.
No issues found.
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/0a822ef7-475f-4eb2-8a1a-47957277154a)
[Icon-test.zip](https://github.com/Regalis11/Barotrauma/files/12616844/Icon-test.zip)
Closing ticket.
