### ISSUE TITLE
[0.10.4] Shuttle Terminals always starts in Auto Pilot - Maintain Position mode every round.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3416]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shuttle Terminals always starts in Auto Pilot - Maintain Position mode. This makes drones on subs like Remora and Kastrul continuously eat power when left unchecked at the beginning of each round, also slowing down the sub momentum because it's generally trying to go backwards.

**Version**
0.10.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67a92bc63bfc463f1dbf557aee91db45aa1970f5

**Comment by Rokvach** [comment]
No issues, closing.
