### ISSUE TITLE
Undefined arithmetic operations are inconsistent in their results

### ISSUE THREAD

**Issue by Mezzokoko** [Regalis11/Barotrauma#3417]
While encountering a bug related to an arithmetic node outputting a "NaN" signal as a result of an illegal operation, I discovered that the way those get handled seems to be not entirely consistent. Some of them put out NaN, others a valid signal, but a wrong result.

In addition to fixing the wrong results I would suggest not outputting a signal at all, when NaN would be the result, as there is nothing useful you can do with it in wiring (a non-signal would be much preferable and better to work with) and there is precedent for entities not being able to handle it properly all the time.

![ApplicationFrameHost_r3rty2jGr1](https://user-images.githubusercontent.com/5637889/88546250-63c8ff00-d01c-11ea-8cbf-7de5281adccf.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ead6094b1989a0d7aac82e96b9db7eb081c82983

**Comment by Rokvach** [comment]
No issues, closing.
