### ISSUE TITLE
Feature Request - Ability to toggle HUD in sub editor for best screenshots

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3419]
**Description**
Either a new button, or making the console command work in sub editor would be nice for screenshot purposes.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/b7b5d82ade88ad6165c0e3156d777d84ed6d172e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
