### ISSUE TITLE
Feature Request - Choose background for sub editor and character editor for screenshots

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3420]
**Description**
Ability to easily choose background for the editors would make sharing subs and creatures much better.
Backgrounds
-biome backgrounds
-vignettes
-plain colour (currently available)
-screenshots at much higher resolution than currently selected
(for example screenshot will be in 4k, making it possible to zoom on the picture on social media and admire each room)

**Comment by 3e849f2e5c** [comment]
I've added some behavior to submarine editor in https://github.com/Regalis11/Barotrauma-development/commit/6722c0ab6dec949725bdf2c60a00f6cfa9b59e2d that allows you to load custom background images that should satisfy some screenshot needs. Wouldn't consider this ticket complete yet however.

![](https://kosblue.com/e/wsvipb.png)
![](https://kosblue.com/e/aydmig.png)

**Comment by Rokvach** [comment]
Are character editor backgrounds necessary?
