### ISSUE TITLE
Bots are unable to repair leaks in Azimuth gunnery compartment

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3423]
Easy to reproduce 

1. Start a round in Azimuth, no matter if its singleplayer or multiplayer
2. Plasma cut the roof of the gunnery compartment
3. Order bot to fix leaks
4. Notice that even tho the bot runs to the room they wont try and reach the leak and fix it

I also tested without the platform, but that didn't make any difference. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/75551263-6a36-429f-a325-dc10435abf09)

**Comment by Kaillera** [comment]
Related to #2752. Bots are confused with leaks caused by walls behind another wall. This happens in Orca engine and crew cabin rooms too.

**Comment by itchyOwl** [comment]
I noticed that the upper left leak is unreachable for the bot unless the hull is flooding and the bot can swim. That's something I can probably fix, because it should be reachable.

The upper right leak was just barely reachable. It caused the bots to fumble a bit, but after a second they were able to fix it.

So, please give it another run on human-ai and dev when you have time.

**Comment by itchyOwl** [comment]
Should be fixed on human-ai.

**Comment by Rokvach** [comment]
The AI first tries to fix the leak in a wrong position, but will eventually fix it correctly. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b338bfb1-7a8d-4154-ac7c-e0c7be31a3af)

Tested if I can fix it as a player and only the progress bar shows up, but the progress doesn't go up when I weld it so its barely out of reach
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/cfc2e065-8f73-4324-9755-524b6d652568)

**Comment by Rokvach** [comment]
Just a small waypoint issue on Azimuth, otherwise works correctly once that waypoint has been re-adjusted. Closing as the primary issue has been fixed.
