### ISSUE TITLE
[Multiplayer] Newly bought upgrades reverts if you enter lobby by pressing Server Lobby in Esc menu or by dying

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3424]
Repro steps:
1. Start multiplayer campaign
2. Buy upgrades
3. Undock from the outpost
4. Press Esc -> Server Lobby OR die and wait for the round to end
5. Return back to the campaign from lobby
6. Re-dock to outpost and go check your upgrades

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9a507206ab54400ec3350392d8e9c9101df914e0

**Comment by Rokvach** [comment]
Working correctly, closing.
