### ISSUE TITLE
'Multiple-node' campaign missions.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3425]
With the new campaign map and the ability to persist missions between nodes.
Why not make it possible for certain long-distance cargo delivery or clearing of a nearby hive mission. 
Harder, due to travel requirements, but greater reward compared to a short cargo or combat mission.

**Comment by Udrakan** [comment]
This + simultaneous missions would be great.

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. We probably won't be implementing multi-node missions at this point, but event chains (which can include missions) kind of do the same thing. Closing.
