### ISSUE TITLE
Add clothing tag to all of the clothes items

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3426]
[Feature Request, Modding]
Would be nice if everything considered clothes in the game got a "clothing" tag or something added to their tags. 
This would allow for creation of wardrobes and stuff, but would also let status effects specifically target clothes. People could also make mods where clothing naturally wears down (although that sort of sounds like the worst thing ever) and need to be repaired with fabricators, or have dynamic clothing color changers.

Of course you could do this now by manually specifying every single identifier... but it would be nice to have this as a "standard" for compatibility sake.

Might be a little tedious but if you ever need to put off implementing something more complicated, consider this.

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/1fd47aa788bc28e1895e963131999922693aef71

**Comment by Rokvach** [comment]
No issues, closing.
