### ISSUE TITLE
0.10.4 Dedicted server public="false" not working

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#3427]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On my dedicated server the serversettings.xml setting public="false" isnt working. The server is shown in the server browser and random players could join. 
- None of them had been on that server before.
- Also a buddy who is new to the game could see the server listed

**Version**
0.10.4, Win, dedicated server

**Additional information**
Copy&Paste of the serversettings.xml
https://pastebin.com/JfdF8MR0

**Comment by Regalis11** [comment]
@juanjp600 Fixed in 51deb9344?

**Comment by juanjp600** [comment]
Potentially, needs to be tested

**Comment by Rokvach** [comment]
I assume I should see my own dedicated server on the list even if its set as being private? @juanjp600

**Comment by juanjp600** [comment]
No, that is actually incorrect behavior that's exposed by having the server in Favorites or Recent Servers. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/126a3c122eb874625e27b6f08e8601a3b03505c6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
