### ISSUE TITLE
Remove "End round when destination reached" setting

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3429]
I think we should be safe to just remove the setting entirely as its not necessary for Campaign any more and it causes issues on the other game modes.

**Comment by Regalis11** [comment]
If the setting is toggled off, you need to end the round manually by clicking the "end round" button, just like before. 

I do agree that it isn't really needed anymore though, so we could remove the setting.

**Comment by Rokvach** [comment]
No issues, closing.
