### ISSUE TITLE
Unstable - Booted to main menu when loading from Outpost to Mission

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#3430]
**Description:** I was booted to main menu immediately after loading into a multiplayer Campaign mission, after we left an Outpost.

**Version:** Latest unstable build as of 7/29/2020

[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/4997756/crashreport_object.log)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019
