### ISSUE TITLE
Reset creature despawn timer if player grabs the creature

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3431]
Could also just disable the timer for the duration of the creature being grabbed. 

To prevent the creature from just despawning when player is holding on to it and if a player wants to for example get a creature inside the submarine for some reason they can do so without worrying if the creature will immediately despawn when they are close to the sub. 

Just saw on a stream that the streamer tried to bring a Tiger Thresher they killed inside ruins to the submarine for funs and the Tiger Thresher just despawned on them while they tried to bring it in. 

Mainly just a immersion breaking issue so I will mark this as low prio.

**Comment by rav2n** [comment]
I also want to add that I came across situations when I wanted to pick up items from an already killed moloch-boss, but this was not possible due to small creatures scurrying around nearby. Even if they are destroyed very quickly, the corpse of moloch will already disappear.

**Comment by Rokvach** [comment]
No issues, closing.
