### ISSUE TITLE
Shuttle batteries can be destroyed by explosives, but they can't be fixed

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#3432]
**Description**
A shuttle battery will be permanently destroyed by explosions. This is quite annoying in a campaign, where you'll be dragging a damaged useless shuttle around you can no longer fix.

**Steps To Reproduce**
1. Use frag grenades, C4 detonator, depth charges etc. to destroy a shuttle battery
2. Try fixing it. You can't.

**Version**
stable 0.9.10
unstable 0.10.4

**Comment by mrTea1** [comment]
Problem appears to be in Items\Electricity\poweritems.xml where the shuttlebattery is not repairable but can be damagedbyexplosions:
  <Item name="" identifier="shuttlebattery" tags="battery" category="Electrical" Scale="0.5" description="" damagedbyexplosions="**true**" explosiondamagemultiplier="0.2">

**Comment by mygamingaccount** [comment]
An interesting addition:
When the shuttle battery was damaged, its scale reverted to 1.0
On the Selkie for example, where the batteries are shrunken, and damaging them even a little bit with explosives makes them inflate.

**Comment by Rokvach** [comment]
Tested this on 0.1.500.0 Unstable in multiplayer, tossed a frag grenade in front of the shuttle batteries and everything else inside the shuttle did break but not the shuttle batteries 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/22858b4a-0cf8-43cb-9563-487341fdad0a)

**Comment by Regalis11** [comment]
The batteries are not repairable, so they shouldn't get damaged by frag grenades (or anything else). Seems to be working as intended?

**Comment by pushytoxin** [comment]
@Regalis11 This has not yet been fixed, shuttle batteries can be destroyed by explosives in the v0.10.4 stable branch of the game.

@Rokvach the batteries don't show damage, they can't be fixed, but toss a few more grenades at them and they _will_ break.

![Check this selkie after a Compound-N in a detonator went off in the back
](https://user-images.githubusercontent.com/1923584/90391421-6a7fea80-e08d-11ea-9760-f7b93243c14e.png)

**Comment by mygamingaccount** [comment]
@Regalis11 This issue persists in the stable v0.10.4 version of the game.

@Rokvach the batteries don't show you the damage, but they are damaged. Toss a few more grenades at them and they _will_ break.

Exhibit A: Compound-N struck the rear of this selkie. Interacting with the batteries does not allow the crew to repair them:
![image](https://user-images.githubusercontent.com/68995233/90391785-001b7a00-e08e-11ea-9d8d-a039e6f7632d.png)

**Comment by Regalis11** [comment]
The fix is not present in the stable v0.10.4.0 version

**Comment by mygamingaccount** [comment]
@Regalis11 I confirm the unstable branch fixes this issue.

**Comment by EtiamNullam** [comment]
I was not able to break the shuttle batteries in 0.10.502.0 (unstable) after repeatedly detonating `Compound N` near batteries at `Selkie` anymore, while in 0.10.4.0 (stable) they broke after single detonation.

I think the issue is resolved.

**Comment by Rokvach** [comment]
Closing.
