### ISSUE TITLE
Was playing the New Frontiers update solo

### ISSUE THREAD

**Issue by Connorisgameing** [Regalis11/Barotrauma#3434]
- [ Yes there is not one that I can find ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was play the new update in a new solo campaign. It was working fine I got to I think three outposts with no issue but after buying some things form the fourth outpost and leaving it crashed. It was just like all the other times EXCEPT for me buying things. After loading it's as if we all died and the game came up with a fatal error.

**Steps To Reproduce**
Not sure, play for a bit in a solo campaign, going to a few outpost first and then try buying some cargo and see if the error happens

**Version**
0.10.4.0  windows 

**Additional information**
Cash-report 3 is the first one that i got when i was playing.
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5003314/crashreport.3.log)
Cash-report 4 is after trying to load the save of the crashed campaign.
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/5003317/crashreport.4.log)

**Comment by Connorisgameing** [comment]
Wanted to add I'm loving the update there is so much more you can do RP and casual wise.
Also, I LOVE that you can now see descent velocity in the submarine editor. It was something that messed me up for almost a hour when I made my first sub, and I thought it wasn't go up or down until I put it in a real game and it work almost to good.

Keep up the great work this is one of my most loved games of all time and will it always be install on my PC

**Comment by ekqvist** [comment]
Just to note: the two crash reports seem to be two separate issues

**Comment by Regalis11** [comment]
2nd issue should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/b6dd828dd894cbc3adc4af151af518c8ed4b03f2 and https://github.com/Regalis11/Barotrauma-development/commit/bf5561fffe26c6fc3743714763f95957f5526eb6

This seemed to happen because CargoManager fails to spawn cargo in a room that's less than 40 units wide, so it should be possible to work around the issue by making the hull larger or configuring some other hull as the cargo room.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/18f766616ec9cad3d46eca955590e2480b95b26f

**Comment by Connorisgameing** [comment]
Cool I'll give it a test, and open the sub in the editor to move some stuff around.

**Comment by Connorisgameing** [comment]
Yep all solved been playing for a bit now and it's going good. moved cargo spawn and it's working with no crashes.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
