### ISSUE TITLE
Issues overwriting UpgradeModules

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3439]
### It seems that somehow attempting to overwrite UpgradeModules is not being applied.

Mod filelist with the included content as per usual,
 ` <UpgradeModules file="Mods/Upgrade Mod/UpgradeModules.xml" />`

After seeing no effect with my initial values, I decided to increase the upgrade value 
massively for engines to test if it was actually being applied.

![image](https://user-images.githubusercontent.com/55356135/89005630-f1357900-d2d2-11ea-8233-c2a6e92e09b7.png)

Starting a new campaign with the mod enabled and then giving myself money, I go to the outpost sub manager and see that the engine upgrade still only has 15 levels, and the price is unchanged. Next I decide to max the upgrades anyways, and sure enough after departing the outpost, saving the campaign, and then unzipping the save file and the dugong.txt it shows a
` <Engine maxforce="344.596" ` - the normal value for a max-upgraded dugong.

**Comment by 3e849f2e5c** [comment]
Tried to reproduce with no luck with this configuration

filelist.xml
```XML
<?xml version="1.0" encoding="utf-8"?>
<contentpackage name="Test" path="Mods/Test/filelist.xml">
  <UpgradeModules file="Mods/Test/UpgradeModules.xml" />
</contentpackage>
```
UpgradeModules.xml
```XML
<?xml version="1.0" encoding="utf-8"?>
<Override>
  <UpgradeModules>
    <UpgradeModule identifier="increaseenginemaxforce" maxlevel="15" categories="engines">
      <Price baseprice="2500" increaselow="+15%" increasehigh="+20%"/>
      <Engine maxforce="+500%"/>
      <Sprite texture="Content/UI/CampaignUIAtlas2.png" sourcerect="896,640,128,128" origin="0.5,0.5"/>
    </UpgradeModule>
  </UpgradeModules>
</Override>
```

Tried with and without `<UpgradeModules>`. Bought one upgrade level, exited and re-entered the outpost and checked the save file and it seems to have increased the max force properly by 500%.

![](https://kosblue.com/e/lkmmtb.png)

**Comment by 3e849f2e5c** [comment]
Looks to be release build exclusive

**Comment by Ek-Videogames** [comment]
In previous unstable, the console was saying 'upgrade modules overwritten by blah blah.xml' so it was actually being loaded but not applied somehow. However the issue seems to have resolved itself in the current unstable.
