### ISSUE TITLE
Dialogue bug

### ISSUE THREAD

**Issue by XOILOD** [Regalis11/Barotrauma#3441]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is no way to close the dialog box on the station, when talking with the Prophet about clowns

**Steps To Reproduce**
You need to start a dialogue with Prophet -> Choose "Come in" -> Choose "Pay" -> Choose "What's wrong with clowns"

**Version**
Vanilla 0.9, Windows 10

**Additional information**
I hope I have explained everything clearly, because my English is very bad. Sorry.

**Comment by hubismal** [comment]
it would appear that every mike outcome doesn't have endconversation="true"

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ecfbccd9b47f8b7d152b78473b05288a660ef9f

**Comment by Rokvach** [comment]
No issues, closing.
