### ISSUE TITLE
Crash when deleting campaign save

### ISSUE THREAD

**Issue by CLONik** [Regalis11/Barotrauma#3448]
Itry delete campaing save. Game crashed.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5008719/crashreport.log)

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/78211409a116d8cdce8e5f72b1cb87d95bdde37c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
