### ISSUE TITLE
The ability to change the cursor, etc. / Возможность изменить курсор и т.д.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#345]
I would like to have the opportunity to change the "Noise", "Cursor" and other images for the game using mods.

Хотелось бы иметь возможность на изменение "Noise", "Cursor" и прочих изображений для игры при помощи модов.
![54](https://user-images.githubusercontent.com/33912761/37879260-becd4bd0-307e-11e8-940e-7bb7c363b354.png)

**Comment by Regalis11** [comment]
These are included in #257, I think we can close this.
