### ISSUE TITLE
[0.10.4.0] Can't sell ID Cards / Wrecked ID Cards

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3451]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't sell ID Cards / Wrecked ID Cards. They do pile up a lot. Just make sure we can't sell equipped key card first.

**Version**
0.10.4.0

**Comment by EtiamNullam** [comment]
I think ID cards should be not tradeable, especially the ID cards from wrecks. What would be the motivation for the outpost to buy a useless chunk of plastic from you? After all you can't produce or recycle it.

**Comment by ezjamsen** [comment]
I have no problems with allowing cards to be sold just to allow you to get rid of any surplus ones you might have (or mess with your fellow crew by selling their IDs).

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/deea827187a916f58db9e31bbf68affb790ea266

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
