### ISSUE TITLE
Sub file saved in new version creates massive lag, possibly corrupted.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3452]
This is not really a bug report more a bizzare edge case, but I am posting this here in the hopes it might be somewhat educational in figuring out exactly what had to have gone horribly wrong for this to happen.

I tried to re-save my sub file to work with campaign and despite relatively little changed it now lags horribly when entering the 
'game' state in a sandbox or campaign environment. It is an absolute mess of a submarine, that much is true, but nothing that should be causing performance issues such as this, and loading files which were saved in older versions does not have this issue either.

[EK_Reliant_Mk-V_Backup.zip](https://github.com/Regalis11/Barotrauma/files/5009875/EK_Reliant_Mk-V_Backup.zip)

**Comment by Regalis11** [comment]
I gave this a quick test in the sub test mode and SP campaign, and I'm afraid I couldn't spot anything unusual. The FPS was around 35 in the test mode and around 20 in the campaign, which seems normal with such an enormous sub with a huge number of dynamic, shadow-casting lights.

Nothing useful popped up in the profiler either: no single obvious cause for the low performance, just tons of small item updates adding up.
