### ISSUE TITLE
Initial NIL state for wiring. (battery_charge%_out)

### ISSUE THREAD

**Issue by Deathlymad** [Regalis11/Barotrauma#3454]
- [x] I have searched the issue tracker to check if the issue has already been reported.
>I checked all open issues and did not find a mention it might be in a closed issue tho. 2+k is a bit too much to sift through
**Description**
Batteries output nil as Charge% upon starting the game. Potentially similar issue with Signal Check Comparison

**Steps To Reproduce**
Take a battery do something with the Charge% output signal. Like wiring it to the Text display for example. It will disappear as soon as the battery gets a state update like getting charge or discharging. I remember doing a work around for that in the last version using a signal check. but that doesn't seem to match NIL properly either in the current version.

**Version**
0.10.4.0

**Additional information**
I am unsure if this is a bug since NIL is kind of a valid state. However its troublesome to deal with in most situations. In this particular case Batteries should always have a valid charge percentage so NIL complicates things. The current workaround is to use "greater" modules to clamp the value, forcing it in a valid state.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4b26cf741befe1ac8ec54c0873c220dd28940b4a. The issue seemed to be that the signal output logic didn't run when the battery was empty.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
