### ISSUE TITLE
I can't seem to rotate doors in the Submarine Editor

### ISSUE THREAD

**Issue by BizKwikTwist** [Regalis11/Barotrauma#3455]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When building a submarine, doors don't seem to rotate when a number is typed into the Rotation parameter. When I type a number in and hit enter, either nothing happens or it reverts to zero.

**Steps To Reproduce**
Changing the rotation parameter of doors in the submarine editor.

**Version**
v0.10.4.0 Windows Release

**Additional information**
![Screenshot (276)](https://user-images.githubusercontent.com/7574102/89103595-78204980-d3d8-11ea-881c-da3b83a16756.png)

**Comment by mygamingaccount** [comment]
use a hatch

**Comment by BizKwikTwist** [comment]
> use a hatch

Ahhh okay, I just assumed doors could be used as they had a spot for rotation (though it doesn't rotate) Thx!

**Comment by 3e849f2e5c** [comment]
Items that can be interacted with like doors and ladders cannot be rotated. Working as intended.
