### ISSUE TITLE
Turret view range affected by resolution

### ISSUE THREAD

**Issue by DjTeo** [Regalis11/Barotrauma#3456]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In 4k resolution 3840x2160 when inside turret, max distance viewed is smaller compared to 2560x1440 or 1920x1080.
But human view distance in 4k is bigger as it should be.
So the problem is in 4k resolution I can't see monsters far away but my teammates can.

**Steps To Reproduce**
Change resolution of game between 1920x1080 and 3840x2160 

**Version**
0.9.10.0 and in 0.10.4.0

**Comment by NeyahPeterson** [comment]
I ran into this issue recently as well.
Here's an image showing the difference in aiming ranges at 4k, 1440p, 1080p, and 720p.
720p has a view range of basically twice what 4k can see.  The reticle can go past the range of this gunlight.

![AimingRange](https://user-images.githubusercontent.com/5722580/91779600-fc6a1600-ebaa-11ea-8ee3-3dd263385d1b.png)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/828dd270b6a08805748fe4864b68f5e4b9e36de6. Ranges may need to be readjusted, might need input from design

**Comment by danielasteljoki** [comment]
Adjusted ranges in 93bb4bb.

**Comment by Rokvach** [comment]
The `camera-range-fix` branch hasn't been merged to dev yet, might be better to adjust them there

**Comment by danielasteljoki** [comment]
My mistake. In that branch, ranges are still a bit wonky though. In this picture I'm aiming as far as I can in the horizontal and vertical directions and I can aim way further on the horizontal axis:
![turretranges.jpg](https://images.zenhubusercontent.com/5c9240ccd06a4e6d359ee49a/e43bc9b6-8270-4740-949f-6b0a5700b13d)

**Comment by juanjp600** [comment]
@danielasteljoki This issue should be addressed in https://github.com/Regalis11/Barotrauma-development/commit/2a83e8e2c5282a26d42045e8dd40bed7d3a0f208. Please check ranges again, mainly what I'm looking for is whether the min and max ranges are not too far off from what they should be, as well on some feedback on the transition between low and high ranges, as that had to change.

**Comment by danielasteljoki** [comment]
Everything feels correct to me at least. There might be some minor differences, but nothing that jumps out negatively at least. Changed turret ranges back to original.

**Comment by Rokvach** [comment]
Looks like the change to camera also affected the camera you have when controlling a character, the camera zooms in when moved towards the borders of the screen. 

I also feel like the view ranges are very large right now on the turrets, its like they are by default set to max upgrades. 

Branch:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ee3d72a0-e520-4297-86f3-82b184a23693)

Dev:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fc1a9652-a409-4a30-9cdd-dbfa802537e8)

**Comment by juanjp600** [comment]
Most of these issues should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e472d53be58a867c5b96115c092abef7df2f503b. The meager upgrades seem like a separate design issue that has existed before this branch was made.

**Comment by Rokvach** [comment]
Tested, didn't find any issues. Can be merged. Closing.
