### ISSUE TITLE
Relay Power Draw

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#3458]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
5 relays only drawing 1kw power

**Steps To Reproduce**
reactor -> 2 junction boxes -> 5 relays each with 1 power_in connected to a junction box -> relays power out connect to an Electric Discharge Coil

spam discharge coil (suggest an oscillator with frequency 4hz to the EDC's trigger_in)

**Version**
0.10.4

**Additional information**
I set up an electrified fence.

**Comment by Tsunder** [comment]
[Dugong-ong-ong-ong.zip](https://github.com/Regalis11/Barotrauma/files/5011510/Dugong-ong-ong-ong.zip)

**Comment by Tsunder** [comment]
**Expected Behaviour**
5k power draw on power grid

**Observed Behaviour**
1k power draw on power grid

**Comment by Deathlymad** [comment]
**An immediate workaround would be to set the maximum throughput of a single relay to 5000 and remove the rest. or just leave them for aesthetics but not attached.**

Parallel systems for aesthetic reasons are... unfortunate. Batteries hjust generate massive fluctuations.

I am currently still working myself through the code.

But this is what i believe whats happening. There are essentially four kinds of power components. Junction (boxes), power provider, Power consumers, and power transferers. Those last ones being a bit of a problem. 
Junction boxes basically group all components, they are more or less neglible for power transfer logic.
Power providers and consumers however have an expectation that there is a path from a provider to a consumer.
That path can either be within a node or through directional edges. Those directional edges are the power transfer objects. Relays and Batteries. 

As far as i can tell they currently are trying to predict the next load in some way and drain accordingly. - In parallel that tends to lead to power spikes.

the following is my loose thinking on how to avoid the whole issue.

What this is, is a directional graph. Ideally for computing would be a outwards trees with a provider at the root and consumers as leaves. then the tree unique path would determine power flow and distribution.
But Parallel circuits are a thing so the requirement for a unique path is not given. Loops are also allowed. Loops can be eliminated using depth first search.
Now the path uniqueness needs to be solved. i propose that when a shared subtree is present its detached and a virtual node is put in place that has the sum off all power as maximum throughput, and drains by ratio upwards. Essentially an arbiter for parallel/competing paths.

Theoretically its possible to have logic deal with this issue by ways of tickwise switching between sources. but i have a feeling that it would be more inefficient and its also more complicated to design.

**Comment by Regalis11** [comment]
This is no longer possible because it's only possible to connect one wire to the reactor's power output, so I'll close the ticket. The issue still occurs with batteries though https://github.com/Regalis11/Barotrauma/issues/3238
