### ISSUE TITLE
OBS Video Capture Broken with Barotrauma

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3460]
> So this is a long standing problem, probably since the first ea release. Obs video capture breaks. One of my viewers nailed the problem, it happens reliably when you go into settings. Would be awesome to get fixed, I hate using monitor capture.

from lonkley in discord. i think this has happened with me too in the past. only full monitor capture seems to work. I'm no capture pro though so it may be advisable to ask him directly in the discord.

**Comment by 3e849f2e5c** [comment]
Closing as we already have a ticket of this in the private repo https://github.com/Regalis11/Barotrauma-development/issues/2092
