### ISSUE TITLE
Bug after Frontiers update. 

### ISSUE THREAD

**Issue by AnkerionInfidus** [Regalis11/Barotrauma#3461]
- [ *] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When game starts it crashes with log creating and after that just closes without any promport
Adding log file.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5011782/crashreport.log)

**Steps To Reproduce**
Starting game. Just after Frontiers update . When intro cinematic ends and main interface start to load it crashes. It started just after Frontiers update

**Version**
Latest steam version
**Additional information**
Thank your crew for all your dedication and work.

**Comment by mygamingaccount** [comment]
Try disabling all those mods and verify the local game files!

**Comment by AnkerionInfidus** [comment]
disabled all mods and checked file integrity. Worked. Some mods were manually removed beside being unsubscribed. Thank you.

**Comment by Regalis11** [comment]
Since this specific issue got solved and we have another ticket about this (#3500), I'll close this one.
