### ISSUE TITLE
Giveperm doesn't work when player has space in their names

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3463]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Giveperm Kaillera ManageCampaign - Works
Giveperm "Adam Smith" ManageCampaign - Does nothing.

**Version**
0.10.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c534067bf30f05f2ac3b15f8278452f91fa1e4e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
