### ISSUE TITLE
Sub stuck at wall

### ISSUE THREAD

**Issue by rl-elrond** [Regalis11/Barotrauma#3464]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I got some trouble with enemys and when I went back to navigation sub was stuck in a tunnel, just a little too small for my sub and I wasn´t able to get away.

**Steps To Reproduce**
I don´t know. I have´nt seen how the navigating AI got in that wall, because I was shooting from the top of my sub.

**Version**
0.10.4.0 Windows

**Comment by rico6822** [comment]
Can you handle a save file?

**Comment by rl-elrond** [comment]
Nope, sorry. Deleted the savefile afterwards...
