### ISSUE TITLE
When I saved, I was right next to a wreck. Saved, loaded and suddenly was back at station

### ISSUE THREAD

**Issue by rl-elrond** [Regalis11/Barotrauma#3465]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I saved, I was right next to a wreck. I geared my captain and saved. When I loaded I suddenly was at the starting station, but gear and stuff was exactly like it was when I saved.

**Steps To Reproduce
Gear up somewhere in the open water, save, go back to MainMenue, load savegame

**Version**
0.10.4.0 Windows

**Additional information**

**Comment by Regalis11** [comment]
Starting from the outpost is intentional: if you quit and reload, you always start from the beginning of the round regardless of where you saved. You shouldn't get to keep the items you've obtained mid-round though, so that part seems to be bugged.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91c3fad2bd037557eac013fb9ed8441a08832fbe

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
