### ISSUE TITLE
[0.10.4.0] Coilgun bolts clipping into ship after hitting a target

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#3472]
- [x] I have searched the issue tracker to check if the issue has already been reported.

They clip back inside the ship after hitting an alien so the ship gets filled with useless bolts that you can't deconstruct.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this, the bolts seem to disappear as soon as they hit anything, or in the case of piercing bolts, as soon as they've hit 2 targets (or after 5 seconds).

Does this happen consistently in some specific sub? Did it happen in single player or multiplayer? What kind of ammo are you using?

**Comment by thegrb93** [comment]
It was multiplayer and it was this ship https://steamcommunity.com/sharedfiles/filedetails/?id=1788008831 .

**Comment by thegrb93** [comment]
Maybe fixed in https://github.com/Regalis11/Barotrauma/issues/3581#issuecomment-675331016

**Comment by Rokvach** [comment]
Fixed already, closing.
