### ISSUE TITLE
Feature request: connecting to yourself when offline

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#3474]
I think it should be possible to connect to localhost even if you have steam disabled or no internet.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/d4e9526168379296917ea9338ee616617d66e39b

**Comment by MystLeissa** [comment]
Although it works as far as letting you connect, the real benefit of this (Connecting to local server with multiple clients for testing) is somewhat difficult to pull off, might I suggest an in-game toggle for "checksteamauthentication" and/or stop updating the Config File Values each time we launch the game/server? It would be nice if we could also do this while logged into Steam in addition to being logged out of stams. Finally and possibly unrelated I seem to be having trouble setting permissions on individual clients with the dedicated server software in these cases.

**Comment by Rokvach** [comment]
I also agree that this should work without needing to change settings in a file

Should the "Host Server" button be disabled when offline? You shouldn't be able to host a SteamP2P server

Received a error on main menu, tried to run the game without having Steam open in the background
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b3e7f9c4-8939-4bf5-bc49-4997dea47eed)
