### ISSUE TITLE
Mechanic's not reapiring subs in campaign single player

### ISSUE THREAD

**Issue by bghacha** [Regalis11/Barotrauma#3478]
I was just playing single player and enjoying the new stations when I noticed that my mechanic when sent to repair things like batteries and junction boxes seemed to not be doing his job what so ever yet the engineer and assistant (Who was on the guns) were doing their jobs very well. So I think this maybe a bug or something that needs fixing for this game thank you! Also really loving the game!

**Comment by itchyOwl** [comment]
It's possible that it's a bug. It's also possible that there was something preventing the bot to complete the task. Difficult to say with the given information.

**Comment by itchyOwl** [comment]
Could it be that the bot just couldn't find a wrench? If that's the case, it should yell "I can't find the item I need" (need to improve the feedback).

**Comment by itchyOwl** [comment]
Moved to QA, see #4171.

**Comment by Xeavas** [comment]
[0.1100.0.3] - Removing the tools required to do the job, bots convey said requirement and lacking in tool. Dropping required tool after that results in them picking it up and repairing machines. Tested with dugong + emp grenade + taking out all wrenches. 👍

**Comment by Rokvach** [comment]
Closing.
