### ISSUE TITLE
Mini Nuclear Reactors or Other On-Board Energy Source For Shuttles- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3480]
Now before you say that mini nuclear reactors can already be done via changing the size of the regular one please read this out.

There already are small pumps in the game.

I've been wandering about that if there is to be a way to recharge batteries inside of shuttles or even create an actual shuttle that doesn't need them there could be a mini nuclear reactor for it to not just occupy much space but to drain power rods at slower rate while also allowing only one at once. I think this reactor could be meant for low power output so it won't constantly prevent batteries from dropping down they're power supply. The reactor would also be able to work under water but at a faster rod drain.

Let's just assume that unupgraded mini nuclear reactor would generate at max 1000 power but 900 would already be dangerous.
Because of how inconvinient this idea seems to be this thing suffers malfunctions more often than regular reactor. I guess the cash given to someone who just started playing the campaign with shuttle as main vessel would be spent on something. Also every time malfunction occurs a fuel rod put inside would start draining faster due to some "strange errors". This occurs even when reactor is disabled. Two draining speeds would stack on each other (if reactor would be enabled). The reactor would also generate very small radiation around it that would damage someone trying to fix it but the harm caused is very small. The radiation also won't occur if there is no fuel rod inside or the fuel rod is empty.

An explosion caused by such mini reactor being overloaded occurs slower and has strongly less severe devastation.

I guess the coalition could had intentionally made those reactors that flawed to get more cash from it's people. An additional reason for renegades to be? Therefore they believe upgrading those things is more expensive than it should be and they might be right just maybe.

Mini nuclear reactors were inspired by Windows 10 S when it comes to economy and Windows Vista when it comes to stability.

Alright, the game would be too dependant on anti-rads this way. I think the radiation would start being generated about 30 seconds (perhaps randomized) if nothing would be done about it.

**Comment by EtiamNullam** [comment]
We already have a big nuclear reactor now and I don't like the idea of adding more stuff that does the same thing. Also most of the stuff you're talking about here can be achieved my modifying the regular reactor's settings in sub editor.

**Comment by Regalis11** [comment]
In my opinion it's a good thing that there are limitations on where you can put a nuclear reactor. If it was possible to fit one inside a shuttle/drone, battery-powered vessels would become obsolete. And if you really do want a self-powered shuttle, it's possible to build one from the existing reactor as EtiamNullam described.
