### ISSUE TITLE
[0.10.4.0] Alien Ruins blocking docking at colony

### ISSUE THREAD

**Issue by JetyWawoo** [Regalis11/Barotrauma#3483]
**Description**
I had to deliver explosive cargo to one colony to the next, and there's this alien ruin in the way.
![image](https://user-images.githubusercontent.com/69184142/89255090-d161c600-d5ee-11ea-82e0-beefea9f830e.png)

**Steps To Reproduce**
Unsure as the maps are randomly generated. I travelled from Alkonost Station to the City of Worm station on the campaign seed 
DxD4V7nS
**Version**
Version v.0.10.4.0, Windows 10.

**Comment by rico6822** [comment]
Would disabling vertical spawning of alien ruins 30 meters from icy crust fix the thing?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b854e192606b287ad9b38928d787d41867832267

**Comment by Kaillera** [comment]
Your sub might be close enough to count for entry if you swim into the outpost's airlock and then hit the usual Enter button at the top of the screen when in there.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
