### ISSUE TITLE
Allow Choosing Between Interface Styles From Option Menu- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3484]
I think some people may not be used or prefer the old interface style of using navigation terminal. The old interface could have add-ons to keep up with current game's content (directional pings and stuff).

**Comment by Regalis11** [comment]
I'm afraid we won't be reintroducing the old interface. I doubt there are many people who actually prefer it over the new interface, so the added overhead of maintaining 2 different interfaces and their logic would probably not be worth the effort.
