### ISSUE TITLE
Prisoner Mod (Error)

### ISSUE THREAD

**Issue by Teivellus** [Regalis11/Barotrauma#3485]
[*] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So, over the few days, I have been slaving away on a mod where you can start as a prisoner. It's an entirely new job role, with new textures, etc. Everything seems to work perfectly fine, even spawn points. The problem is when I want to leave the station you start on, start a mission, or start sandbox; I get the following message:

---

_Generating an outpost for the end of the level... (Location; Milda City, level type: LocationConnection._

_Error while starting the round (did not receive STARTGAME FINALIZE message from the server). Stopping the round..._

_TimedOut_

_Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__82" has failed._

---

Afterwards, the round crashes... Sometimes, It will still allow me, the host, to stay, but it kicks everyone else with that same error.

At first, I assumed it might have been because I didn't set the vendors at the outposts to be able to sell prisoner NPCs, but even after doing that, I've had no luck. Maybe it has something to do with having a new role included in the game, and not in an XML file which has both outpost information and spawning information in it. I can't seem to figure it out, though.

Someone has told me to access GameClient, but neither they nor I, know how to do that.

**Steps To Reproduce**
I can supply the mod to recreate the bug, if necessary. I've spent a good fifty or so hours making the mod and a submarine to go with it, so some help in fixing this would be appreciated.

**Version**
Current version. Windows 10 64 bit.

**Comment by Regalis11** [comment]
That error message could occur if the server crashes when starting the round. Is there a file called "crashreport_server.log" inside the game folder? If not, do you see another kind of an error message if you launch the dedicated server from the game folder and try to start a round with the command "start"?

**Comment by Regalis11** [comment]
I'm afraid there's not much we can do about this without further info, closing
