### ISSUE TITLE
Oxygen tanks (And perhaps other items with 2+ categories) are not categorized in the sub editor

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#3486]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Oxygen tank has the category in XML files of:
```xml
<Item name="" identifier="oxygentank" category="Equipment,Misc" Tags="oxygentank,smallitem,oxygensource"
```

But it cannot be found in either equipment or misc categories in the sub editor.
Oxygen tanks only appear in the "All" category.

I believe what might be occuring is anything with 2 or more categories will appear in none of them, this is a very old issue I remember from early steam versions.

**Version**
0.10.4.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cfa980fa18d948538afc7fded232dcdc90875d26

**Comment by Rokvach** [comment]
No issues, closing.
