### ISSUE TITLE
Issues noticed with endpoint/IP/SteamID ban command

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#3488]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
it appears intended that the banendpoint command is the sole/only way to ban a player whose disconnected via steamID.

But has both some confusion and some quirks with already banned players checking.

Although the route it takes is weird and does not compare things properly, it also technically sort of does work for getting the steamID banned (Sort of), even if only on the next banlist load at best.

**Version**
0.10.4.0

**Additional information**

It isn't clear from the command name this is its purpose but from its description.

```csharp
commands.Add(new Command("banendpoint|banip", "banendpoint [endpoint]: Ban the IP address/SteamID from the server.", null));
```

For that, I at least suggest a change "bansteamid|banendpoint|banip" as this even confused me looking for this command, or use a separate command.

Now, following the path of the code for this command is a little strange if what your supplying it is a steamID instead of an IP address.

It looks as if an endpoint-based ban will never find an existing ban via steamID (BanPlayer is provided a steamid of 0 and compares on Banned IPs to IP address which is actually the steamid in the IP field and IP is a string in this case) as it always uses this code (In order):

First off in the code:

```csharp
var clients = GameMain.Server.ConnectedClients.FindAll(c => c.EndpointMatches(args[0]));
```

EndpointMatches only examines IP, so this command would never find via steamID a connected player.

Picture Args[0] as a steamID supplied to this command.

```csharp
if (clients.Count == 0)
                    {
                        GameMain.Server.ServerSettings.BanList.BanPlayer("Unnamed", args[0], reason, duration);
                    }
```
With the above, we use this method:

```csharp
public void BanPlayer(string name, string ip, string reason, TimeSpan? duration)
        {
            BanPlayer(name, ip, 0, reason, duration);
        }
```
and from here:
```csharp
private void BanPlayer(string name, string ip, ulong steamID, string reason, TimeSpan? duration)
        {
            var existingBan = bannedPlayers.Find(bp => bp.IP == ip && bp.SteamID == steamID);
            if (existingBan != null)
            {
                if (!duration.HasValue) return;

                DebugConsole.Log("Set \"" + name + "\"'s ban duration to " + duration.Value);
                existingBan.ExpirationTime = DateTime.Now + duration.Value;
                Save();
                return;
            }
```

SteamID Is supplied as 0. So matching via the ban's SteamID doesn't work. Already allowing for multiple ban entries for one SteamID.

Additionally, this code does not allow for updating a ban length to infinite if the intended duration is forever, Instead of overwriting it (If thats intended) it will simply throw it away from the looks of it - If trying to set a ban length (IE. 1 days to permanent) shouldn't the client at least be notified instead of the canceled time change?

Finally:

```csharp
if (!string.IsNullOrEmpty(ip))
            {
                bannedPlayers.Add(new BannedPlayer(name, ip, reason, expirationTime));
            }
            else if (steamID > 0)
            {
                bannedPlayers.Add(new BannedPlayer(name, steamID, reason, expirationTime));
            }
```

This DOES correctly add (once saved, but not while the server is running) whatever is input into the arguments, so in theory...it can ban a steamID as the IP field and SteamID field are saved into the same column (So if its a steamID ban its saved where IP address would go)

However, if you enter a different steamID format than a ULong - won't this also break?

All of these are valid formats:
steamID STEAM_#:#:########
steamID3 [U:#:########]
steamID64 #################

I assume however, the game only uses one of these. though I don't see anything translating them from whats input (If that matters).

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/b7e4d2961d4f75a2d8e159872b368085ab95437b

**Comment by Regalis11** [comment]
LidgrenConnection.EndpointMatches doesn't seem to be working correctly now: it only returns true if the address is IPv4 mapped to IPv6. If you for example join a server on localhost, you can't control a character because your IP is ::1.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f92648ce5c2dc53a9ae795140f09c94d76c384b

**Comment by Rokvach** [comment]
No issues in banning, seems to be working correctly. Closing.
