### ISSUE TITLE
Minor XML error on alien vent and missing XML tags/msg for legacy items

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#3489]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While checking one issue out I noticed another minor oversight:

- [x] tags appear to be category instead, category should likely be alien, and tags alien,alienvent
```xml
<Item name="" identifier="alienvent" category="alien,alienvent" interactdistance="0" scale="0.5" linkable="true">
```

I know legacy items are generally not updated, but I feel they should at least be tagged correctly with the games current tags, some of which may be used for AI and such now/in the future or for cargo spawning / status effect targeting.

At the very least, it would help to have their behaviour be closer to their none-legacy counterparts, and have them behave the same with Mods/AI/newer content. Even if not retroactive, some new submarines will still use these components.

I have taken the effort of going through and comparing legacy items to none legacy for missing tags.
Tags are based on their none-legacy counterparts

- [x] Legacy Navigation Terminal
tags="command" allowedlinks="command"
Should likely be:
tags="command,navterminal" allowedlinks="statusmonitor"
missing - Steering - Msg - ItemMsgInteractSelect

- [x] Legacy Sonar Monitor
tags="command" allowedlinks="true" but no allowed links set.
Should likely be:
tags="command,sonarmonitor" linkable="false" / allowedlinks="statusmonitor"
missing - Sonar - Msg - ItemMsgInteractSelect

- [x] Legacy Status Monitor
tags="command" allowedlinks="command"
should likely be:
tags="command,statusmonitor" allowedlinks="navigationterminal"
missing - Minimap - Msg - ItemMsgInteractSelect

- [x] Legacy Engine
No tags
should likely be:
tags="engine"
missing - Engine - Msg - ItemMsgInteractSelect

- [x] Legacy Shuttle Engine
No tags
should likely be:
tags="engine"
missing - Engine - Msg - ItemMsgInteractSelect

- [x] Legacy Oxygen Generator
No tags
should likely be:
tags="oxygengenerator"
missing - Oxygengenerator - Msg - ItemMsgInteractSelect

 - [x] Legacy Pump
No tags
should likely be:
tags="pump"
missing - pump - Msg - ItemMsgInteractSelect

 - [x] Legacy Small Pump
No tags
should likely be:
tags="pump"
missing - pump - Msg - ItemMsgInteractSelect

 - [x] Legacy Junction box
No Tags
should likely be:
tags="junctionbox"
missing - powertransfer - Msg - ItemMsgInteractSelect

 - [x] Legacy Fabricator
Correct Tags
missing - connectionpanel - Msg - ItemMsgRewireScrewdriver
missing repairable

 - [x] Legacy Medical Fabricator
Correct Tags
missing - connectionpanel - Msg - ItemMsgRewireScrewdriver
missing repairable

 - [x] Legacy Deconstructor
No Tags
Should likely be:
tags="deconstructor"
missing - connectionpanel - Msg - ItemMsgRewireScrewdriver
missing repairable

- [x] Legacy Railgun Loader Left/Right
Correct Tags
Missing - Itemcontainer - Msg - ItemMsgInteractSelect
missing repairable

- [x] Legacy Searchlight
Tags="light"
Should likely be:
Tags="searchlight,light"

- [x] Legacy Periscope Left/Right
Tags="railgunequipment"
Should likely be:
Tags="periscope" (Vanilla's newer periscope does not include railgunequipment, unsure if intended given they can also be used for cameras)
Missing - Controller - Msg - ItemMsgInteractSelect

- [x] Legacy medicine cabinet
No Tags
Should likely be:
Tags="container,medcontainer"
Missing - itemcontainer - Msg - ItemMsgInteractSelect

- [x] Legacy toxin cabinet
No Tags
Should likely be:
Tags="container,toxcontainer"
Missing - itemcontainer - Msg - ItemMsgInteractSelect

- [x] Legacy steel cabinet
No Tags
Should likely be:
Tags="locker,container"
Missing - itemcontainer - Msg - ItemMsgInteractSelect

**Version**
0.10.4.0

**Comment by Regalis11** [comment]
Thanks for a very informative report again! :) Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3099010e5b78053fb8d89393c24c51a81bd8dc8 and https://github.com/Regalis11/Barotrauma-development/commit/49823af35860493dbdb7eafb0e53ffadc6a12b1f

**Comment by Rokvach** [comment]
No issues, closing.
