### ISSUE TITLE
Crash (SteamAchievementManager)

### ISSUE THREAD

**Issue by Icece2e** [Regalis11/Barotrauma#3494]
Game was crashed after wreckage mission completion (when i docked).

I have two journals founded on wreckage
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5024350/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in Regalis11/Barotrauma-development@a57a05d

**Comment by Rokvach** [comment]
No issues, closing.
