### ISSUE TITLE
Game is no longer owned - similar to Ticket #3496

### ISSUE THREAD

**Issue by dmkdmn** [Regalis11/Barotrauma#3497]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Steam states that I do not have a valid key to play barotrauma but that I still own it. This is similar to ticket #3496.  I uninstalled the game thinking I could reinstall, but now the game doesn't even show in the library, but does show as owned when navigating through steam to any point to buy it. 

**Steps To Reproduce**

Any attempts to launch the game immediately bring me to the Steam store page. I exited the game, restarted my computer and tried as well. The game still appears in the library, but all we can do is uninstall it or buy it.

**Version**
Most recent update, 8/4/2020 windows.

**Additional information**

**Comment by mygamingaccount** [comment]
It's more than similar, it's identical to #3496 
It happened to me too, Linux client this time.

**Comment by dmkdmn** [comment]
Fixed for me: I had to clear my Steam Download Cache twice.  It showed up back in my library and I was able to install and launch with no issues.
