### ISSUE TITLE
Steer Sub While Docked to Grind Helm Skill

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3501]
Just saying.

Also you can drag infinite oxygen by opening doors between outpost and rooms leading to your grinding spot. Systems on your sub can be shutdown unless you grind helm I guess.

**Comment by Kaillera** [comment]
Was playing in multiplayer for several hours, haven't seen my helm skill increased at all.

**Comment by Rokvach** [comment]
Moving this back to ToDo as there seems to be a issue with the skill @Regalis11

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/194bf8c24278699c06b9b4079294f686e2ccc1f0.

There was a bug in the calculations that caused the skill to increase as slowly as it would for a character with a nearly maxed skill level.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
