### ISSUE TITLE
Sound volume attribute in xml doesn't seem to affect volume in game.

### ISSUE THREAD

**Issue by PiotrWieczorek98** [Regalis11/Barotrauma#3507]
**Description**
I wanted to change volume of some sounds by editing value of attribute "volume" in .xml file but I didn't notice any change (even set to 0)

**Steps To Reproduce**
For example in oxygengenerator.xml:
`<sound file="Ventilation.ogg" type="OnActive" range="1000.0" volumeproperty="CurrFlow" volume="0.001f" loop="true"/>`
Changed `volume="0.001f"` to `volume="0.0f"` or `volume="1.0f"` and volume didn't change in game.
Restarted entire game each change.

**Version**
Windows v0.10.4.0

**Additional information**
Bypassed it by lowering .ogg volume level

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/09d2a09f6bc231156ea9dd4a1fce9ba1e3f6df6d
