### ISSUE TITLE
Explosion AOE damage ignores walls and doors, enjoy!

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3511]
For a long time, being able to harm people with light explosives such as grenades and exploding harpoons on the other side of walls or closed doors has been an issue. 
Stun grenades, frag grenades etc.

I think it stands to reason that explosions which are not powerful enough to destroy the walls should not damage creatures through walls and doors.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/037618d58cdad7ae80c3b793e726562beffce5ec

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
