### ISSUE TITLE
Pumps' water particles can go through walls

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3513]
Pumps were designed to launch water horizontally when filling rooms. I was wandering if the water shouldn't be launched vertically downwards instead, for a very short distance of the animation itself to prevent it going through the floors visually (the animation would cut after some distance, this doesn't make same amount of sense as in case of horizontal one as the distance between a wall and a pump varies). This may require changing the very textures of the pumps slightly.

**Comment by Rokvach** [comment]
Tested, some particles can be seen on the other side of the wall, especially when using the legacy walls like on the Typhon ballasts, but its nowhere near as bad as it was, closing as there were no issues.
