### ISSUE TITLE
Crash in SteamManager.GetServers

### ISSUE THREAD

**Issue by speven-hao** [Regalis11/Barotrauma#3520]
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5040659/crashreport.log)
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Seems to have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/38668419

**Comment by Rokvach** [comment]
There hasn't been any encounters to this issue, looks to be working correctly, closing.
