### ISSUE TITLE
`fuel_out` for Reactor

### ISSUE THREAD

**Issue by hinshun** [Regalis11/Barotrauma#3521]
I'd like to be able to access the `AvailableFuel` in the Reactor through wiring.

**Comment by Regalis11** [comment]
Thank you for the pull request! This has now been implemented in our private repo.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/fa901b406806cb75349bd4e6351ea67c25772d8c

**Comment by hinshun** [comment]
Awesome, thanks!

**Comment by Regalis11** [comment]
Thanks for taking the time to close the ticket, but we'll keep it open for now and close it when we've tested it internally and verified it's ready for release.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
