### ISSUE TITLE
Character appearance bug: Incorrect headspriteid value | Singleplayer

### ISSUE THREAD

**Issue by Ioraek** [Regalis11/Barotrauma#3522]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game loads the wrong head sprite for the primary character in singleplayer. It seems to load with a value of 1 for the character's headspriteid, regardless of what value is stored in the save file. 

(By primary character I mean the captain character the user is in control of when the save loads. The other characters appear to have the correct values for their head sprites.) 

This only occurs once per session, only on the first time loading any save. If I exit back to the main menu and then for a second time load any save (including the same one), it will load with the correct head sprite. 

As best I can tell, this bug only affects the variable for the headspriteid; the stored variables for hairindex, beardindex & mustacheindex seem to be loading correctly. 

Happy to provide more info if needed. 

**Steps To Reproduce**
1. Start a new game, ensure the character has **_not_** spawned with "head 1" for their race. 
1. Save and exit. 
1. Close game completely. 
1. Re-launch game. 
1. Load save.
1. Character will have loaded with "head 1" for their race. 
1. Exit to main menu.
1. Load save again.
1. This time character will have spawned with correct head sprite.

**Version**
v0.10.4.0. 
OS: Windows Pro 64bit
Platform: Steam

**Additional information**
I am not running any mods, and have verified game files.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7fbbd8fa39cedbca0eff714b174fcf20ac87f48a

**Comment by Rokvach** [comment]
No issues, closing.
