### ISSUE TITLE
end game crash

### ISSUE THREAD

**Issue by V1Htor** [Regalis11/Barotrauma#3525]
Three times in a row I passed the level, three times I had to spend a lot of time, three times I reached the last outpost. And three times the game is crashed when I clicked on the last station. 
[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/5045839/crashreport.15.log)
[crashreport (16).log](https://github.com/Regalis11/Barotrauma/files/5045840/crashreport.16.log)
[crashreport (17).log](https://github.com/Regalis11/Barotrauma/files/5045841/crashreport.17.log)
![SPOILER_unknown](https://user-images.githubusercontent.com/39983153/89716371-0b4b1780-d9b5-11ea-9f01-16f88fc2b39d.png)
[FFinally.zip](https://github.com/Regalis11/Barotrauma/files/5045846/FFinally.zip) - Save

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f30efe3b13528c2f7b557cc2167665aadd449e0

**Comment by Rokvach** [comment]
Tested while playing as a host on my own server, didn't encounter any crashes. So unless it needs multiple players to crash the game this seems to be working. Will need to test again when campaign teleporting fixes are on Unstable. Closing for now, will re-open if the test fails.
