### ISSUE TITLE
Game is crashing when reaching the end

### ISSUE THREAD

**Issue by V1Htor** [Regalis11/Barotrauma#3528]
![unknown](https://user-images.githubusercontent.com/39983153/89718502-c11f6180-d9c7-11ea-8079-18fbcc3089ab.png)
**Description**
game is crashing when you enter the fire (ashvini II, the end)

**Version**
0.10.4.0, win10

[FFinally.zip](https://github.com/Regalis11/Barotrauma/files/5046137/FFinally.zip) - savegame
[crashreport (20).log](https://github.com/Regalis11/Barotrauma/files/5046138/crashreport.20.log)
[crashreport (19).log](https://github.com/Regalis11/Barotrauma/files/5046139/crashreport.19.log)

**Comment by itchyOwl** [comment]
See #3525

**Comment by Regalis11** [comment]
Duplicate of #3525
