### ISSUE TITLE
Repeatable outpost event

### ISSUE THREAD

**Issue by Parktard** [Regalis11/Barotrauma#3539]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The 'Bug station crew' outpost event is repeatable and grants full 2k marks reward each time completed. We replicated this 4 times in a row.

**Steps To Reproduce**
Find a military outpost that grants the above event, complete the event, undock from station and redock, each time you redock the event triggers with the crew chief requested a representative to meet them.

**Version**
0.10.4.0 - Windows 10

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2256ea332dd2cede3f796c1a7a58759f4baea0f7

**Comment by Rokvach** [comment]
Wasn't able to reproduce, looks to be working correctly. Closing.
