### ISSUE TITLE
Modified options only take effect after restarting a round while in a game.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#354]

**Comment by Regalis11** [comment]
You mean the resolution setting? Everything else seems to be working correctly.

**Comment by juanjp600** [comment]
If you try changing your controls during a round, it'll fail to update the controls until the round ends.

**Comment by NilanthAnimosus** [comment]
I believe he means the server - specifically settings such as respawn  timers and the likes do not take effect mid-round, in fact most settings do not that I'm aware of, especially those sent to clients at round start being set in stone until the next round begins.
