### ISSUE TITLE
Replace "Difficulty" With "Attractiveness"- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3542]
Alright, I know how extremely odd it sounds but there has to be a reason behind how coalition knows exactly in percentages how dangerous is a zone and why even certain monsters below a percentage treshold can't show up.

I think the percentage could represent by the lore an amount of "thing" in the water (you can give it a name) that causes monsters to be attracted to it. Some won't even survive if it is insufficient. Monsters can still be encountered in regions without that "thing" or with low amount of it because some other monsters could had scared them off from it. Europea creatures are simply smart enough not to risk if it's not worth it at least when it comes to this "thing". They could had been developing they're genes for thousands of years to teach themselves to step aside from it if someone stronger blocks the path. Since humans are perhaps on Europa for not so long time it pretty much explains why weak monsters charging on submarines are so suicidal.

The coalition had developed a "way" capable of measuring this "thing" and all sailors are informed of it for free. I do also wander if values in decimal spaces could also be displayed up to 3 or something since it's supposted to be all chemistry and stuff.

I do not necessarily consider "difficulty" as the difficulty because more monster give greater amount of items upon killing for crafting or selling. It also means A.I. controlled crew would have more opportunities to train they're weaponry skills.

Even if gamers wouldn't know what does it mean they would very quickly realise after "easy", "hard", "hellish" or other stuff like that what it is for.

**Comment by Regalis11** [comment]
> I know how extremely odd it sounds but there has to be a reason behind how coalition knows exactly in percentages how dangerous is a zone and why even certain monsters below a percentage treshold can't show up.

I disagree with this. I don't see why the Coalition (or whoever does the difficulty estimations) couldn't determine how dangerous some passage is based on some factors like the surrounding environment, the size and shape of the passage, observations on the fauna/flora in the area and so on.
