### ISSUE TITLE
Shuttle placement breaks after going from 1st outpost -> 1st mission

### ISSUE THREAD

**Issue by ralfbiedert** [Regalis11/Barotrauma#3543]
- [x] I have searched the issue tracker to check if the issue has already been reported.

## Description

I created a submarine with an attached shuttle. In the editor, and during the staring base of the campaign, the sub works as expected. 

However, **when going on the first mission**, **the shuttle's location is shifted by about ~2m upwards** (as if it wants to dock to its sibling port from the wrong side), and the whole sub become unusable.

## Steps To Reproduce

1. Download sub, select use `Elysium V.b` as the main sub (`The Brave.b.1` is the connected shuttle)
1. Start new game while docked in base (or just load in Editor -> Test), walk into attached shuttle (should work)
1. Leave base and go on first mission, walk into shuttle again -> severe placement glitch 

[**Problem Subs.zip**](https://github.com/Regalis11/Barotrauma/files/5053394/Subs.zip)

**Distance between docking ports when OK** (Editor mode + docked to first campaign base):
![b2](https://user-images.githubusercontent.com/301288/89831785-af23f700-db5e-11ea-9b45-793a8158b0c7.png)

**Distance between docking ports when BROKEN** (once on mission) ... :
![a](https://user-images.githubusercontent.com/301288/89831776-acc19d00-db5e-11ea-80ef-e581d365108f.png)

Notice how the lower docking port reaches up and almost touches the fire extinguisher. 

**Version**
0.10.4.0

**Additional information**

**Comment by ralfbiedert** [comment]
Update, the bug seems to be related to a single "Hull" element in the shuttle:

If there is a hull (the blue "Hull" annotation) placed inside the shuttle's docking port, the shuttle placement is broken as described above. Once I remove the hull it works.

**Comment by Regalis11** [comment]
Glad you managed to solve it! You shouldn't put hulls outside the ports, because not only they prevent the vessels from docking properly, they also cause the area outside the port to be considered inside the sub, leading to weird behavior if some character ends up in that area when the shuttle isn't docked.

But in any case, I improved the logic for determining the orientation of the port, and the shuttle should now be placed correctly even if there are hulls at both sides of the port. https://github.com/Regalis11/Barotrauma-development/commit/4ed6ec34cf53fd079ccf3afcf8e71513ddb3d0d0

**Comment by ralfbiedert** [comment]
Hi, thanks for improving that! Turns out my solution didn't actually work. The visual placement got improved, but apparently some parts of the docking ports still matched on the wrong side(?), so that I effectively couldn't undock. 

For some reason that issue was primarily visible in MP and / or after a few rounds. In the editor things always worked perfectly. 

I think I still have a sub laying around somewhere that exhibits that extended issue, let me know if you want me to upload something.

**Comment by ralfbiedert** [comment]
> You shouldn't put hulls outside the ports, because not only they prevent the vessels from docking properly

IIRC, the reason I did this because there were constant "water" noises when the shuttle undocked in the editor that seemingly came from the between the docking ports that I just couldn't fix otherwise.

Semi-related, a few lines + screenshots how to shuttle docks are intended to be designed would be nice!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
