### ISSUE TITLE
Exception: Failed to set source's position: SoundChannel

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3545]
"Game just crashed for no reason, console was popping up everytime... it was horrible"

See the crashlog for further information:
[crashreport_2.log](https://github.com/Regalis11/Barotrauma/files/5056683/crashreport_2.log)

**Comment by Regalis11** [comment]
The changes in https://github.com/Regalis11/Barotrauma-development/commit/87499578 should prevent this from crashing the game. Not sure what exactly caused the position of the ragdoll to be NaN, but could be related to Regalis11/Barotrauma#4368 or Regalis11/Barotrauma#4344.
