### ISSUE TITLE
Automatic content-pack enabling for server browser.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3549]
Although automatic download and the addition of a working search-bar for mods has helped greatly,
it is generally a long process to join servers with 8 or more different mods when you must enable already installed mods manually.

A button similar to 'get missing packages from workshop' but for something such as 'enable required content packages' is what I am suggesting.

**Comment by juanjp600** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/tree/feature/modding-improvements

**Comment by Rokvach** [comment]
Working correctly, closing.
