### ISSUE TITLE
Mineral crate still exist after finished the "Mining outpost material transport" or Clown items in "Praise the Honkmother"

### ISSUE THREAD

**Issue by Nakajima-Kuro** [Regalis11/Barotrauma#3550]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I finish the "Mining outpost material transport" or "Praise the Honkmother" mission, those create suppose to disappear. But after the game transit me into the outpost, I go back to my sub and those create are still there, so I can sell them again to the shop for extra-money.

**Steps To Reproduce**
Just take a mission of this type and play until you finish the mission, most of the time the create not disappear and I can re-sell those create for extra money.

**Version**

v0.10.4.0 (Window, branch release, revision 20132d25fb)

**Additional information**
None

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce this. Tested it in a couple of different ways, and in all cases the crates disappeared.
- Traveled to the next destination
- Returned to the same outpost I just left from
- Took the items from the crate and dropped them outside the sub before travelling to the next destination
- Took the items from the crate and dropped them outside the sub before returning to the previous outpost

Do the contents of the crate persist after the round as well? Did this happen in single player or multiplayer?

**Comment by Regalis11** [comment]
I'm afraid we cannot do much about this without more info, closing at least for now
