### ISSUE TITLE
shutter-freeze because high ram usage 

### ISSUE THREAD

**Issue by SNAKEIX** [Regalis11/Barotrauma#3552]
Windows 10 Pro - V1909
Ram DD4 8Gb
GPU AMD R9 390
CPU i7-6700k
SSD hardDisk
Game version: 0.10.4.0

 after the last update the game took almost all my Ram space in very unstable way , and everyday it getting worse , this week every time i scan the server the game freeze for 30 sec sometimes less , this is wasn't happened until the new version of the game , and inside game the Ram usage rise to 95% !!! WTF , it's clearly there is something wrong here , my PC run all powerful games smoothly on high and many on ultra setting , barotrauma definitely don't require this amount of Ram capacity , looking for a fix , thanks.

![baro](https://user-images.githubusercontent.com/69602999/90062921-61cf9300-dce0-11ea-84eb-5166c6787898.jpg)

**Comment by SNAKEIX** [comment]
i found a fix for this , the core of this problem was a bad file inside the game

**Comment by itchyOwl** [comment]
Reference to the "fix": #3553. The game shouldn't use that much ram in any case, we'll need to look into it.

**Comment by alkaid7205** [comment]
After the new update (10.5.1) I experience the same problem.
Up to 7GB (out of 8) memory usage in the main screen.
![memory](https://user-images.githubusercontent.com/71730359/93938664-41104980-fd32-11ea-8421-dfec2d3b6cfe.png)

**Comment by Regalis11** [comment]
There's a newer ticket about this with a bit more info (https://github.com/Regalis11/Barotrauma/issues/4432), closing this one.
