### ISSUE TITLE
News to fix a lot of issues in the game

### ISSUE THREAD

**Issue by SNAKEIX** [Regalis11/Barotrauma#3553]
to those who freeze - shutters - lag - hosting servers - Ram usage and many other issues  , i FOUND OUT it's all have to do with submarines files and mods , it seems if players download a lot of new submarines and mods , the game start have issues depends on each players and especially of there is a corrupted submarines files , since the game it self not finished , just go to submarines files make a copy just in case and delete everything , it will make the game run very smooth.

**Comment by Zthespook** [comment]
how does one identify what causes a sub or file to become corrupted and or give other performance related issues.

iv seen the many item in one spot glitch which makes slow down to the point of a crawl but never had an idea as to why.

**Comment by Regalis11** [comment]
There's a newer ticket about this with a bit more info (https://github.com/Regalis11/Barotrauma/issues/4432), closing this one.
