### ISSUE TITLE
Moving a stolen item from one hotbat slot to another counts as stealing.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3556]
Steps to reproduce:
- Steal an item successfully.
- Move the item to another hotbar slot while in a room with npcs.

**Comment by itchyOwl** [comment]
This is a known issue. A workaround is to not handle the stolen items in front of NPCs.

**Comment by Regalis11** [comment]
Seems to have been fixed by https://github.com/Regalis11/Barotrauma-development/commit/167c35a3

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly. Closing.
