### ISSUE TITLE
Light emitter bug

### ISSUE THREAD

**Issue by TheDanSide** [Regalis11/Barotrauma#3557]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Emergency Light: emitter component of light does not rotate with the sprite.

**Steps To Reproduce**
Place a light in a the editor, and rotate it. Make sure it's on, and test.

**Version**
v0.10.4  Windows 10

**Additional information**
This may have been in the game prior, I just never noticed.
-edit-
This may affect other lights, I haven't just sat down and placed all the lights and rotated them.

![emitter_bug](https://user-images.githubusercontent.com/67638229/90194491-132c0280-dd8d-11ea-9170-e32257019873.jpg)

**Comment by Regalis11** [comment]
Duplicate of #3344
