### ISSUE TITLE
Sometimes items just dropping from the inventory.

### ISSUE THREAD

**Issue by TNines** [Regalis11/Barotrauma#356]
Иногда, не редко но и не часто, любой предмет который ты передвигаешь из инвентаря в другой контейнер ( или же в что-то на подобии этого ), или же из контейнера в инвентарь, просто выпадает на пол. Да, я знаю, возможно это проблема из-за пинга хоста, но когда у нас был отличный пинг ( проверили через дебаг-контроль ), вещи все равно выпадали. Это действительно неудобно, особенно в руинах или просто за бортом субмарины, потому что ты можешь перетаскивать какие-то вещи из одежды в инвентарь, а она просто упадет и исчезнет в бездне.

Sometimes, not rarely but not often, any item that you managing from inventory to another container (or something like this) or from container to inventory, just dropping on the ground. Yes, i know, probably it's a problem of the host ping, but when we got a really nice ping ( checked it on debug control ), items would still drop. It's really uncomfortably, specially in ruins or just behind the submarine, cause you can manage some item from the shirt to inventory, and it's gonna just fell down, and gone to abyss.

**Comment by chesse20** [comment]
agree i see this bug all time

**Comment by Regalis11** [comment]
Just noticed that #356 is a duplicate of this. The newer issue has more information so I'll close this one.
