### ISSUE TITLE
Prevent Paralyzant From Disabling Endworm- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3560]
https://www.reddit.com/r/Barotrauma/comments/i710m5/which_handheld_weapon_is_best_against_giant/

While we were discussing on the most powerful handheld weapons against giant enemies one of the participants Bloop_The_Immortal had figured out that paralyzant is same good against every creature. Stun always occurs after 100 seconds regardless of the creature's mass.

https://www.reddit.com/r/Barotrauma/comments/i7p9kj/can_paralyzant_completely_disable_endworm/

Note that moloch is as massive as it takes to resist a stun. Paralyzant simply overrides it. I'm pretty sure endworm is equally vulnerable to it.

**Comment by itchyOwl** [comment]
Paralyzant was introduced simply thinking the Leucocytes. This is an oversight. Thanks for reporting.

**Comment by rico6822** [comment]
> 
> 
> Paralyzant was introduced simply thinking the Leucocytes. This is an oversight. Thanks for reporting.

What about the radiotoxin and otehr chemicals without wearing out over time?

**Comment by Regalis11** [comment]
Note for implementation: an easy way to fix this would be to add a conditional that checks the mass of the target, similar to how we've done in the stun baton config.

`<Conditional mass="lt 60"/>`

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/062035eddee5dabf0ab774452836daddd3e58116

**Comment by Rokvach** [comment]
No issues, closing.
