### ISSUE TITLE
Allow Players to Create They're Own Simple NPCs That Could be Randomly Encountered Inside Outposts if There is Internet Connection- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3561]
If there is one thing I highly respect Barotrauma for is that it's story focuses on regular people and workers not powerful historical figures or "chosen ones".

I do also wander if players would respond positively to creating they're own NPC other players could encounter in single player campaigns if internet connection was enabled. The players could choose following things for they're avatars:

- Name.
- Gender.
- Appearance.
- Job and it's variants.
- Personality trait.
- Whenever they can be hired on board or not.
- Whenever they can participate as non-player's submarine members in random events or not and what those events could be.
- Whenever they could give player missions or not.
- Whenever they could buy stuff from player or not or maybe sell stuff instead.
- At what kind of outpost they could be encountered. There can be multiple.

By "internet connection" I mean that game during the generation of campaign would try to find on the internet if there could be any player avatars to download and where they could be encountered. If there is no internet connection than campaign would be without player avatars.

Players who would encounter those NPC would be also able to see who made them.

Multiple avatars can be made as they don't have to represent they're creators.

Those are all only cosmetic effects. Players wouldn't be able to create custom dialogues that would therefore contain strictly forbidden words.

**Comment by Regalis11** [comment]
This is actually possible by modding the NPC config files.

The modded NPCs won't appear automatically if you haven't installed the mod though, which is how it should be IMO: we don't want players' outposts to be filled with random player-made joke NPCs unless they opt-in for that.
