### ISSUE TITLE
Mining Outpost: Mine shaft leading to open water.

### ISSUE THREAD

**Issue by Potato-Masher** [Regalis11/Barotrauma#3567]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I encountered a mining outpost with a mineshaft leading to the outside. No water was flowing between the seemingly open gap, but I was still able to walk through it into the water. I was unable to swim back inside after exiting through it as if there was a wall. It looks as if something was meant to be there, but didn't appear correctly.

**Steps To Reproduce**
1. Start a new game with the seed set to LbJ8owtv
2. Travel to Pelorus Linea Mining Claim
3. Enter the mines to the right side of the outpost, and climb to the highest point in the mining area.
4. Head right and suddenly enter water; get crushed due to water pressure.

**Version**
Windows v0.10.4.0

**Additional information**
Images relevant.

![Barotrauma_LaQk7qBZVc](https://user-images.githubusercontent.com/33107541/90302626-61b4cc00-de75-11ea-8110-513b68e08c1f.png)

![Barotrauma_vU5JtuI5MT](https://user-images.githubusercontent.com/33107541/90302680-e869a900-de75-11ea-906f-4838b0144b7c.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1f7d77d913c88c8a7ab0cfeb69a5a8620f32cd02

**Comment by Rokvach** [comment]
No issues, closing.
