### ISSUE TITLE
Vanilla Sub water ducts require a Welding Tool to repair rather than a Wrench.

### ISSUE THREAD

**Issue by Potato-Masher** [Regalis11/Barotrauma#3568]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Noticed that while playing on the Dugong, one of the water ducts was somehow broken during a thalamus attack. The hover-over prompt said a wrench was required to repair it, but neither the bot or I could actually fix it with a wrench in hand. After viewing the sub editor, it seems that all the vanilla subs I checked have the required repair tool for ducts set to be a welding tool.

Using a welding tool in-game after pressing E allows repairs normally as if using a wrench.

**Steps To Reproduce**

1. Somehow break a water duct.
2. Attempt to fix using a wrench by pressing the E key on the duct.
3. Observe nothing happening.
4. Grab a welding tool in hand and press the E key on the duct.
5. Observe the repair HUD appearing.

**Version**
Windows v0.10.4.0

**Additional information**
Spawning a new duct in the sub editor can be repaired with a wrench normally.
Image from the Dugong in the sub editor.

![Barotrauma_OqIp1hMsdL](https://user-images.githubusercontent.com/33107541/90302822-0daae700-de77-11ea-973d-8e0327fcb073.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/330eb6543f0c8a4f43e125c23ef8a759c00dc80b

**Comment by Rokvach** [comment]
No issues, closing.
