### ISSUE TITLE
Sonar ping animation ends prematurely when sonar switched off

### ISSUE THREAD

**Issue by SeeJayDee** [Regalis11/Barotrauma#3569]
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The expanding circle in navigation view depicting the traveling sonar ping disappears immediately when sonar is switched from active to passive. It would be good if it persisted until the echoes have returned.

**Steps To Reproduce**
(Only tested in single player)
Have your sonar in passive mode. Flick the switch to active, then immediately back to passive.

**Version**
Windows 10. Whichever version was up on Steam at the time of this post. (Installed yesterday).

**Additional information**
Super low priority but it is mildly annoying. Just let me enjoy my individual pings!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ba930af387ac4c43589dbc3b8e5c6fd9837f023

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
