### ISSUE TITLE
Non-standard Device Upgrades- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3570]
I do actually wander if stores could upgrade features of submarines in the way that slightly changes the way they work.

Here are some of my ideas:

- For 5000 cash nuclear reactor can start draining fuel rods slower depending on they're amount. It's 75% speed reduction with four inside but regardless of they're amount, if this is switched ON reactor will work as if there was only 1 inside. This can be toggled OFF for free after purchase and ON also for free and acts as alternate mode for fuel rod usage.
- For 500 cash oxygen generator will receive a new wiring output "toggle". As it's name suggests the player can simply switch the generator off. By default is is always activated. For 500 same thing can be done but with "state_out" instead. For 500 same thing can be done but with "set_state" instead. All those upgrades can be purchased for 1500 in total.
- For 2000 cash oxygen generator can be manually set to refill oxygen tanks faster but it won't produce oxygen for rooms at the time. For another 2000 cash this can be upgraded to adjust with a bar the speed of refilling those tanks so oxygen production for rooms can be partially lowered instead of completely disabled. Additional wiring outputs for these features can be added also for cash.
- For 1000 cash navigation terminal can be set to send out weaker sonal pulses that travel much slower but won't travel further than the range of submarine if it was in place.
- For 2000 cash status monitor can give infromation about oxygen in rooms automatically without oxygen detectors. Won't be purchasable if it is already given to a monitor.
- For 5000 cash same thing could be done with hull integrity. Won't be purchasable if it is already given to a monitor.

**Comment by Regalis11** [comment]
The issue tracker is not intended for feature requests, but thank you for the ideas!
