### ISSUE TITLE
Overclocking electrical devices

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3573]
Several versions back there was a bug that could make a very cool feature - it allowed pumps to work faster when you given them more power. When I read that entry in the changelog I thought it was fixed by capping the the speed at 2x (by default):

```
- Fixed pumps and batteries operating/recharging faster when receiving overvoltage, with no upper limit, making it possible to for example operate pumps at 10x the speed by connecting them to a relay that's receiving 10x more power than is being drawn from it.
```

But it looks like its not the case. Pumps seem to be capped at 1x speed even at 2x the power. So does the fabricators.

Just like you can conserve energy by running reactor at half the required capacity - I think you should be able to run it at twice the power for increased speed but less efficiency. It would make perfect sense and give engineer job more use and make it more important. It would be completely optional if engineer doesn't have the skill or time to manage it.

Ultimately it should affect every possible electrical device - pumps to pump faster, fabricator/deconstructor to craft faster, batteries/supercapacitors to charge faster, engine for better acceleration and max speed (this is the most important in my opinion), etc. Maybe even sonar to ping at faster rate or stronger (penetrate walls more easily?).

Imagine a situation where in a critical sitation captain could order the engineer to overcharge the reactor for better mobility and more charge to the guns at the risk of breaking boxes or causing a fire if he goes too far.

![image](https://user-images.githubusercontent.com/10875340/90316933-07c00f00-df26-11ea-9364-c963034298c8.png)

If you think manually operating the reactor is too taxing - its not as long as the sub uses some batteries as buffer.

Later it could be expanded by allowing to route more power to certain systems somehow.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
