### ISSUE TITLE
Humpback Terminal Does Not Respond to Wired-In On/Off Commands

### ISSUE THREAD

**Issue by TankerD18** [Regalis11/Barotrauma#3574]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Figured out a fairly clever way (for my level) to wire an empty button on the Navigation Terminal into the Battery Array Terminal on the vanilla Humpback to switch the batteries "on" and "off" in Campaign mode. However, the Terminal doesn't seem to take the "on" and "off" inputs from a Signal Check Component as the same thing as literally typing "on" or "off" into the terminal and pressing enter.

**Steps To Reproduce**
Wire an unused button on the Humpback's Navigation Terminal to the input terminal on a Signal Check Component.

Set the Signal Check Component to output "on" (without parenthesis) for Target Signal = 1.

Wire the output of the Signal Check Component into the signal input for one or both of the Battery Array Terminals. 

Press the new button on the Navigation Terminal.

Check the Terminal for a value of "on".

Note that the batteries aren't draining.

Manually type "on" into the terminal.

Now the batteries should be draining.

**Version**
0.10.4.0

**Additional information**
I did this in a more complex manner using two Signal Check Components, an Adder Component, a Memory Component, a Cosine Component and an Absolute Value Component to alternate between an "on" or "off" output for every press of the button on the Navigation Terminal. 

However, performing it with just a single Signal Check Component wired from the Nav Terminal straight to the Battery Array Terminal to make an "on" signal does the same thing.

**Comment by mygamingaccount** [comment]
This is not a bug, you are merely misunderstanding how the terminal input works.

It is not supposed to forward packets from its input to its output.

**Comment by TankerD18** [comment]
Is there any way to work around that on the vanilla sub or is it type it in or try and bypass it completely?

**Comment by mygamingaccount** [comment]
You want the Humpback batteries to toggle, toggle the relays next to the batteries.

This is not the right place for these kinds of questions

**Comment by TankerD18** [comment]
Yeah cool, though it was a bug, don't be rude.

**Comment by mygamingaccount** [comment]
The statements I made were all expressed in a neutral tone.
