### ISSUE TITLE
Bots - Doesn't use CPR on characters suffering from Oxygen Loss.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3578]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I have my doctor bot on rescue duty, they don't seem to apply CPR on characters that suffers from Oxygen Loss. They seem to prefer curing all the other afflictions. When they inject morphine for those, it kills the characters sooner.

**Version**
0.10.4

**Comment by Kaillera** [comment]
Their priority also seems to be to run around looking for deusizine and liquid oxygenite even though it may be far from the body.

**Comment by itchyOwl** [comment]
Couldn't repro anymore.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce either, seems to have been fixed at some point. Closing.
