### ISSUE TITLE
Security Officers in Campaign spawns a SMG bullet at the start of every level

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3579]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Security Officers in Campaign spawns a SMG bullet at the start of every level

**Version**
0.10.4

**Comment by Regalis11** [comment]
Could not reproduce. Single player or multiplayer? Where exactly does the bullet spawn, in the character's inventory, on the floor, in the magazine...?

**Comment by Kaillera** [comment]
Both single and multiplayer. The bullet round spawns at the character's position and falls to the floor.

**Comment by Kaillera** [comment]
I tend to steal a lot of SMG and Magazines from stations, I am not sure if that's part of it

**Comment by Kaillera** [comment]
[Save.zip](https://github.com/Regalis11/Barotrauma/files/5103329/Save.zip)

You can see here a SMG round falls to the floor of characters that holds SMG.

**Comment by Regalis11** [comment]
> That SMG extra bullet is probably a remnant of some earlier gameplay development idea.

Actually it is still used: the magazine spawns bullets which get fired from the SMG. They should only spawn when the weapon is fired though, not when the magazine is destroyed.

>sees the dropping bullets because probably stolen items get replaced in the game code instead of having the "stolen" property changed.

This is not actually accurate: there is no "stolen" property, the game just stores the name of the outpost the item was taken from (and the value of that property never changes). The items don't get replaced either, the game just loads them from the save file the same way as any other item.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3801756d6d8294c4289cff8c7807d1f1e36f267
