### ISSUE TITLE
Double Coilgun Dropping Bolts Inside Sub

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#3581]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Coilgun loader drops their respective ammunition on the ground under it on each click. Problematic over multiple missions in campaign, as they accumulate and cause lag.

**Steps To Reproduce**
1. Periscope controls 2 coilguns
2. Those 2 coilguns are linked to 1 coilgun loader
3. Left click while using the periscope
4. A coilgun bolt drops under the loader

**Version**
Windows 10.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3a5648fa4db65a8a2d19c21403abe4ce862c69f7

**Comment by Rokvach** [comment]
Working correctly, closing.
