### ISSUE TITLE
Recicle "Traitor" Mission Mode From Old Barotrauma Legacy Versions Into A Steam Version Multiplayer Mission Type- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#3583]
https://www.youtube.com/watch?v=utb01pz6t4c

Formerely Barotrauma had featured a "traitor" mission in which the round was lost if the traitor had murdered they're target.

I believe that I know how to recicle this into steam version of the game.

Coalition knowing that there is a traitor among the crew decides to send the vessel into a nearby outpost as they don't posses at the current location stationary device, that would allow solving the mystery. Since the traitor is already doomed he decides to pick he's revenge on crew members.

The coalition has enough foresight to notice that if the captain was the traitor he would try anything to either delay or even sink submarine into the abyss as soon as possible to avenge himself being busted. That's why a replacement captain is on board. That's why captain cannot be selected as traitor. If everyone would undergo scans in the second base it would mean that original captain is the "bad guy" they seek or alternatively the "baddy" already perished on he's way. This can lead to multiple ending messages.

If selected mission type is "random" than this mode won't be selected until there are at least 6 players on the server but this can be set in the settings of the server.

Maybe it would be too hard with too many players on the board. I think there could be multiple traitors to do the job. For every 5 non-traitors there would be a bonus traitor. To prevent having to kill 9 people as a single traitor from being too hard the traitor would only have to kill 5 players. Similair thing goes for multiple traitors. 

Multiple traitors also know each other and know that they are traitors.

Once the kill counter gets exhausted the game doesn't end victoriously. It is possible to achieve a stalemate if:
1. Traitors died.
2. Kill counter got exhausted.
3. There is still at least one non-traitor alive.

To be honest the traitors only truly win when they're every foe dies.

The round also doesn't end automatically by having a traitor killed. When traitor dies there is no announcement. It only ends upon reaching end destination. So if a tragedy strikes post-mortem it would all count as kills by a traitor.

In case if submarine went into abyss range I think the traitor should automatically win. 

Winning as a traitor fully restores karma and players playing as them are informed of it. Traitors also won't lose they're karma at all in this mode.

**Comment by Regalis11** [comment]
I'm not sure I understand what you mean, isn't this basically how many of the traitor missions work now? Of course, the objective is not always to kill someone, but there are plenty of mission variants where that's the final step.
