### ISSUE TITLE
"Set state" input for external lights

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#3589]
It would be nice to to be able to set the lights on **coilguns**, **railguns**, **searchlights**, using a set_state input on top of the toggle_light input that are already present.

Neither vanilla nor workshop subs are stealthy, because it's hard to design them right. set_state could make it easier to have selective and global light logic in a sensible manner.

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/68f3ce4a16b8a9204640bdf55bed52f2b2d5afce

**Comment by Rokvach** [comment]
No issues, closing.
