### ISSUE TITLE
Rotation for more sprites

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#3590]
**Description**
We all need and want a rotation in this game 'cause it giving so much possibilities and opportunities.
for example - broken crane
![image](https://user-images.githubusercontent.com/42521948/90490306-26512080-e147-11ea-854c-9428a510b2fc.png)

**Steps To Add**
``Jlobblet#0621`` added rotation for every item in game via copy of rotation from `Items.cs` and modding `Sprite.cs` (Draw.Tiled)
and aside from walls it looking and working as intended, so if you need code for adding this - contact me ``(panman#3600)`` or ``Jlobblet#0621``

**Version**
Game version 0.10.4.0 (ReleaseWindows, branch DEV, revision 20132d25fb)

**Additional information**
This will be the best thing to add while waiting for massive updates
discord info:
creator of rotation - ``Jlobblet#0621``
just a madlad, who using this inovation rn - ``panman#3600``

**Comment by Regalis11** [comment]
I'm afraid allowing structures to be rotated isn't as simple as just rotating the sprite: the rotation would also have to be taken into account in things such as decals, the shadow-casting convex hulls on the structure, the physics bodies of the wall, the way damage to the wall is calculated and rendered, how the game checks if an item can be attached to a wall behind it, and probably many other places as well.

So I think this is out of scope; the amount of refactoring it'd take to properly implement it is probably not worth the effort at least at the moment.
