### ISSUE TITLE
Respawn shuttles spawn-in with huge upwards velocity.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3592]
Respawn shuttles, vanilla and custom, start with a substantial upwards velocity when they first appear.
This velocity is usually slowed down naturally by drag and by a crewmember beginning to maneuver the shuttle.

However in some situations that result in the respawn shuttle spawning very near the roof of the cavern, 
the shuttle smashes into the roof immediately after crew spawn with no time to react.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
