### ISSUE TITLE
Mirror X doesn't mirror green box on engines

### ISSUE THREAD

**Issue by Fatmice** [Regalis11/Barotrauma#3593]
Per title.
0.10.4
As reported by Rain Dreamer#7580 on discord.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/80b7a3c54b4a75dcdc7a45aeb3e77c94dec23c8d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
