### ISSUE TITLE
Wrong status in the aftermath interface

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3594]
Happened during a single player campaign that these two crew members actually died during the mission, but their status was shown incorrectly in the interface shown after the missions. They were new recruits before the mission, but it seems that their status wasn't properly updated.

Version: v0.10.4.0 (dev)

![wrong_status.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/5370cbee-7bf8-416c-938e-7ba8a321d3ca)

**Comment by Rokvach** [comment]
No issues, closing.
