### ISSUE TITLE
Overflowing health bar in higher resolutions

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3596]
2560x1440: ![healthbar.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/c6ffcfeb-d977-4cb1-95b2-09a9acfcd2d6)

**Comment by itchyOwl** [comment]
Seems to be fixed on the bugfixes branch.

**Comment by Regalis11** [comment]
Duplicate of Regalis11/Barotrauma-development#1653
