### ISSUE TITLE
Traitor mission 'Acid party' bug.

### ISSUE THREAD

**Issue by HADTerran** [Regalis11/Barotrauma#3598]
If the player is alone on the server and with the traitor mode performs the Acid party mission, then after picking up the deliriumine item, the server crashes.

v0.10.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dbe17eed3e022374fc8262894598ec3753dd6596

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
