### ISSUE TITLE
Fix Bots

### ISSUE THREAD

**Issue by FlyterV** [Regalis11/Barotrauma#360]
after the updates, the bots became stupid,and this is a problem in a single player game/

**Comment by JoaoVLA** [comment]
Agree. i order them to "FIX LEAKS" and then they are running from one side to another without clothes in the "Air Lock Room"

**Comment by BillCombs** [comment]
It also would be nice to make bots able to crouch, because some ships have rooms with a low ceiling and bots just get stuck in there.

**Comment by JJRcop** [comment]
I believe this is partially fixed already in the development branch
