### ISSUE TITLE
Bots don't fill the slots when the players are not present in multiplayer campaign

### ISSUE THREAD

**Issue by mario31274** [Regalis11/Barotrauma#3601]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game doesn't fill the slots of absent human players with bots anymore.
I hosted a 6 player game and enabled bots with fill mode up to 6 bots, but no new bots showed up after my friends left the server.
It seems the bots only fill in the empty slots at the beginning of a campaign. If you try to load a save, it will no longer fill bots for you. I remembered that it would always fill the empty slots in previous versions.

**Steps To Reproduce**
Add human players into a multiplayer game and turn on bots with fill mode, save and load the game with fewer human players

**Version**
v0.10.4.0 Windows 10 x64

**Comment by Kaillera** [comment]
Multiplayer Campaign bots have been reworked to be persistent instead of appearing for only one round in 0.10.x

You may only set the amount of bots you wanted before the start of the campaign or you must hire them during.

**Comment by Regalis11** [comment]
Yeah, this is not a bug: you only get "free" bots when starting the campaign, after that you need to hire them from the outposts.
