### ISSUE TITLE
Unable to deconstruct Ballistic Fiber for Titanium+Plastic

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3605]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to deconstruct Ballistic Fiber for Titanium+Plastic

**Version**
0.10.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3999cdad859d731411f5b40ee4ad5a318f7be676

**Comment by Rokvach** [comment]
No issues, closing.
