### ISSUE TITLE
Can't use some console commands in multiplayer

### ISSUE THREAD

**Issue by muskaeragon** [Regalis11/Barotrauma#3607]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Console command problem

**Version**
Windows.

**Additional information**
When I create a server for players, I can't use some console commands related to creating subs and other commands. Says I don't have enough rights. I can't give them to myself, you can fix it or tell me how to fix it

**Comment by Regalis11** [comment]
There are some commands (e.g. editsubs and spawnsub) that are intentionally disallowed because they're not designed to work in multiplayer - which commands in specific were you unable to use?

**Comment by Regalis11** [comment]
I'm afraid we can't do much about this without more info, closing

**Comment by muskaeragon** [comment]
I can`t use spawnsub.

**Comment by muskaeragon** [comment]
I understand that they can't be used. But we are already trying to use the commands to diversify the game while you are updating it
