### ISSUE TITLE
"Sonar Terminal" doesn't play sonar sound on Active Sonar

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3608]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Sonar Terminal" doesn't play sonar sound on Active Sonar.

**Version**
0.10.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5204b81b3a2428b9be89101ecfc914860d9534b4

**Comment by Kaillera** [comment]
Working

**Comment by Rokvach** [comment]
Closing.
