### ISSUE TITLE
Reconnecting box for a SteamP2P timeout has no cancel button.

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#3609]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you attempt to join a server but it fails, and causes a SteamP2P timout, the game will automatically try to reconnect you. However, unlike the normal connection box, it has no cancel button. Reconnect attempts often take just as long as the initial failed connection attempts, and in my experience rarely actually fixes the issue. 

**Steps To Reproduce**
1. Attempt to connect to a server, and fail due to a P2P timeout.
2. The game will attempt to reconnect you. There is no cancel button during this.

**Version**
v0.10.4.0 Windows/Linux

**Additional information**
I know this isn't an explicit bug, rather an oversight, but I thought it fit better in bugs rather than as a suggestion elsewhere.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fcc025bbf06bced0f80b2dedcd19f7d5a1e5f6f7

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
