### ISSUE TITLE
The "Fix Leaks" Order dont work for "AI PLAYERS" on Single Player.

### ISSUE THREAD

**Issue by JoaoVLA** [Regalis11/Barotrauma#361]
i order them to "FIX LEAKS" and then they are running from one side to another without clothes in the "Air Lock Room"

It is difficult to select one character for another all the time just to try to fix a hole in the hull or repair the Junction Boxes or even fight against strange beings.

And yes I already clicked on "Generate Waypoins" but it did not work.

**Comment by Regalis11** [comment]
Fixed in the dev branch
