### ISSUE TITLE
Items in duffel bags do not save in the sub editor

### ISSUE THREAD

**Issue by mario31274** [Regalis11/Barotrauma#3616]
**Description**
The items in the duffel bags didn't save in my submarine file. The items inside disappeared when I opened the submarine file.

**Steps To Reproduce**
I saved a duffel bag with items in it as assembly and put it inside my submarine and then saved. When I opened the file again, all the items inside were gone.

**Version**
v0.10.4.0 Windows x64

**Additional information**
The duffel bags saved as item assemblies don't have this issue.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by mario31274** [comment]
I found what the problem really is.
If you place the assembly outside hulls first, the items inside won't be saved. But if you place inside the hull first, they will.
This issue applies to not only duffel bags but also crates.
Here's a video showing how I reproduced the bug:
https://youtu.be/_z8dEI83bEM
