### ISSUE TITLE
Shells inside railgun loaders look wrong

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3620]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Railgun shells placed in railgun loaders look very out of place, especially on the single loaders.
Also mirroring the loaders is causing some weird behaviour, for example mirroring vertical single loader on X axis flips the shell inside on Y axis.

**Version**
v0.10.4.0 Windows

**Additional information**
A screenshot with all loaders using their default properties:
![image](https://user-images.githubusercontent.com/48099798/91029584-3f524980-e5ff-11ea-924a-8a9403889961.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddc11e300bb915db56a2930e354083e047e1c009 and https://github.com/Regalis11/Barotrauma-development/commit/22e2ab385af92cf7f872df23e751d20a6d839ce2

**Comment by Rokvach** [comment]
No issues, closing.
