### ISSUE TITLE
Crash on selecting Terminate Thresher Swarm Mission

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3621]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash on selecting Terminate Thresher Swarm Mission for the next level.
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5119225/crashreport.2.log)

**Version**
0.10.4

**Comment by Regalis11** [comment]
Duplicate of #3440
