### ISSUE TITLE
Syringe Gun Sucks. Always OnFailure syringe effects.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3622]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Syringe gun sucks for anything other than poison. It always give OnFailure effect on any syringe. Maybe higher medical skill level should reduce the chance of OnFailure? I always sell or deconstruct my syringe guns, even as a Medic.

**Version**
0.10.4

**Comment by thegrb93** [comment]
I remember it failing me in a PvP round. I thought it was a glitch but I guess this explains it.

**Comment by Regalis11** [comment]
Looks like it doesn't apply OnFailure effects; the Projectile component that applies the status effects doesn't even have those. The issue seems to be that the OnImpact effects of the Projectile are just configured to be similar to the OnFailure ones.

**Comment by ezjamsen** [comment]
It was configured this way, long long ago, for a good reason I no longer recall. It does feel clunky though, I think we can add the correct skillchecked effects, but always using 100% of the med per shot.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d1531004194897baf5fa0c663d0fe2eee22110c2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
