### ISSUE TITLE
Full Oxygenite tanks deconstruct into more liquid oxygenite(3) then it takes to make them(2).

### ISSUE THREAD

**Issue by mrTea1** [Regalis11/Barotrauma#3623]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deconstruction of oxygenite tanks give back 1 more liquid oxygenite than it takes to construct.

**Steps To Reproduce**
Deconstruct Full Oxygenite Tank
Construct new Oxygenite Tank with returned materials
1 liquid oxygenite surplus

**Version**
0.10.4.0

**Additional information**
should be a simple fix in the content xml file.

**Comment by danielasteljoki** [comment]
Fixed in f9f7ece.

**Comment by Rokvach** [comment]
No issues, closing.
