### ISSUE TITLE
Only Last Explosion in a StatusEffect is Used

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3627]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a StatusEffect contains multiple `Explosion` elements, only the last one is applied.  
This is because when the class is instantiated only the last explosion in the sub-elements is saved - the prior ones are overwritten.

https://github.com/Regalis11/Barotrauma/blob/4978af3d602730de2e2742af8541ef43b227efe9/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs#L354

**Version**
0.10.4.0
Windows 10 1903

**Additional information**
Feels like could affect vanilla design space as well as mods.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bece4153096541911b03522c1ee498f3e177d615

**Comment by Rokvach** [comment]
No issues, closing.
