### ISSUE TITLE
Stabbing with medicine skips skillcheck

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3629]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stabbing someone with medicine always results in a successful skillcheck (or skips it?) - as opposed to using health screen and dragging medicine over a limb.

**Steps To Reproduce**
1. Become the captain (starts with low medical skill).
2. Inject someone with fentanyl using (H)ealth screen (requires high medical skill).
3. Notice you will most likely fail a skillcheck - using full syringe, causing more opiate overdose and healing less internal damage.
4. Inject someone with fentanyl by stabbing someone just as you would use a knife.
5. Notice how it looks like you always pass a skillcheck - using only half of syringe and causing less opiate overdose.

**Version**
0.10.4.0, Windows 10

**Additional information**
This bug makes medical skill useless unless you heal yourself or have to apply medicine on certain limb (like antibiotic glue).

**Comment by EtiamNullam** [comment]
Seems to work as expected in 0.10.501.0 (unstable).

**Comment by Rokvach** [comment]
Closing.
