### ISSUE TITLE
Server Optimization

### ISSUE THREAD

**Issue by MoonEater916** [Regalis11/Barotrauma#363]
This is on a 1.2 quad core server running a lite Linux distro. Barotrauma picks a single random core and runs off that overtaxing the core at 102% while leaving the others at 0%. In game players on this experience mild desyncing and rubberbanding which greatly affect the gameplay experience.

I see multithreading is present in the source code but the screen shot below shows that a lot of optimization is still needed. Anything little bit will help!

![baro](https://user-images.githubusercontent.com/38194158/38474856-4d472bf4-3b58-11e8-95de-774103c8b92d.PNG)

**Comment by MoonEater916** [comment]
So we moved the server to a 2.2ghz Pentium 4 core. As expected the server handles betters. This means that Barotrauma runs best on the old AMD phenom II which would give 2x more power.

I would like to stress the importance and need for even the most basic process threading to move work to other processors and allow more modern server technology. I will look at the source later on to see if i can make some suggestions.

**Comment by storm37000** [comment]
My server is freezing up on a 3rd gen ivy bridge intel i7.  I have the latest stable mono package and Linux Debian 9 distro.  It is join able but says disconnected as soon as i join.  It also will not accept any console commands or takes extremely long time to process(many minutes).  This seem to happen after some time always.  It didn't happen on older Barotrauma versions like v7.

**Comment by Regalis11** [comment]
The changes in the latest version (v0.9.0.7) should remedy this to some extent.

There is still more work to do on optimization on both the server and client, but because optimization is a continuous process that's never fully "done", I think we can close this issue.
