### ISSUE TITLE
Some item assemblies place extra gaps

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3630]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When placing down some of the item assemblies, extra gaps are placed under doors. This bug happens with "Automatic Airlock Doors" default assembly, but also i've noticed it happening with some of my duct block assemblies. It's possible that hatches are also affected, but i haven't stumbled across a hatch wit extra gaps yet.

**Steps To Reproduce**
Place down *Automatic Airlock Doors* assembly and notice the blue gaps under the normal red gaps integrated with doors.

**Version**
v0.10.4.0

**Additional information**
*Automatic Airlock Doors* assembly right after placing it down:
![image](https://user-images.githubusercontent.com/48099798/91159440-6163ce80-e6c8-11ea-9aa1-08c5406c7938.png)
![image](https://user-images.githubusercontent.com/48099798/91160271-79881d80-e6c9-11ea-8611-4c08e8c06d52.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ba03d1e26ffba0f088329dbe0809820b0add7b19 and https://github.com/Regalis11/Barotrauma-development/commit/82a69676b4eafdd6993bc7310cfdf192aa9d8a7b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
