### ISSUE TITLE
Cannot See Dedicated Server Hosted Locally in Server Browser

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3631]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dedicated servers hosted on the same machine as the client do not appear in the server browser. Whilst they can still be connected to via direct join `127.0.0.1`, `localhost`, or `loopback`, they should also appear in the server browser.

**Steps To Reproduce**
1. Host a dedicated server on a computer. Make sure public is set to `true` in the configuration.
2. Start Barotrauma on the same computer.
3. Look in the server browser for the server.

**Version**
0.10.4.0

**Additional information**
I've been unable to see other dedicated servers (hosted on other machines) in the past but was unable to find a pattern.

**Comment by EtiamNullam** [comment]
I always see my dedicated server (hosted on the same machine) in the server browser, sometimes its listed twice - I guess one is reported from master server and other is found locally.

It might be something on your end. Check firewall and server browser filters.

Are you sure it appears on the server browser for others?

**Comment by Jlobblet** [comment]
Filters are fine, firewall settings are fine. I'm sure others can see it because I have tested it with them.  
Typically I use a different box for my server these days which I can see, but when I host it locally I cannot.

**Comment by Kaillera** [comment]
So I don't know if there was any fix to this recently, but I can now see my own dedicated server on the server lobby. It may however take me up to 5 refreshes to see it show up.

**Comment by Rokvach** [comment]
Yeah this was fixed on another ticket, closing this one as it is working correctly.
