### ISSUE TITLE
Regex as a toggle failure

### ISSUE THREAD

**Issue by nolegdai** [Regalis11/Barotrauma#3635]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Regexfind component accepts all comparisons and outputs a toggle function on any input received when registered as a toggle function.

**Steps To Reproduce**
Wire the output of a terminal to a Regex find component. Wire the output of the regex to a door toggle state. Set a qualifying expression. Type garbage(dsalkfjal). The door will open.

**Version**
v0.10.4.0 on windows

**Additional information**
It seemed to be working for some time, then began accepting all values. Tried everything from rebooting to reloading to rebuilding. Nothing worked. At this point I'm not even certain I wasn't fooling myself.

**Comment by Regalis11** [comment]
This seems to be a bug in the doors rather than the RegEx component: the door toggles when it receives _any_ signal to the toggle connection, even "0". 

For now it should be possible to work around this issue by deleting the "0" from the "false output" property of the RegEx component, so it doesn't send anything when the expression doesn't match.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a8bc4c54981dbc7f11d43c697f4f43bd935f677, sending "0" to the toggle connection no longer toggles the door.

**Comment by Jlobblet** [comment]
Is 0 not toggling standardised across all components after this commit? I don't know whether it is currently across other items.

**Comment by Regalis11** [comment]
Looks like there were other components as well that would toggle with "0" (docking port, lights, turret lights). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/576f50486751a19df46ae03db0aeada1c5584ef1

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
