### ISSUE TITLE
Outpost Event Mudraptor Vent requires "Security" skill to pass skill check instead of "Weapons"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3637]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost Event Mudraptor Vent requires "Security" skill to pass skill check instead of "Weapons"

**Version**
10.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/59dcbdda2bc679cff609d1c796ac0e4c4f12380e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
