### ISSUE TITLE
Skill Check Outpost Events needs a Wait option

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3638]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I get skill check events in outposts, it's almost always for another skill than the one my character I am getting it for is good at. There should be a Wait option for you to bring someone with the right skill or something.

**Version**
0.10.4

**Additional Informations**
I also think a lot of these events have such a high skill requirement to even pass.

Also maybe for multiplayer, if a player choose to ignore an event, another player should be able to pick that event up.

**Comment by ezjamsen** [comment]
@danielasteljoki thoughts?

**Comment by danielasteljoki** [comment]
The skill checks could be better. I'm not sure bringing in another character is the solution, though. Instead of treating the check as an automatic success/fail, we could change it into a %-chance of success based on skill level.

**Comment by ezjamsen** [comment]
@danielasteljoki feel free to move this to ice chest, full release backlog, todo, or close it, depending on how you want to tackle this.

**Comment by danielasteljoki** [comment]
Let's use a simple formula: char skill level / required skill level to determine the success for a skill check.
