### ISSUE TITLE
Crew size "1" appears as "0" in the sub editor save menu

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3641]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When opening save menu on submarine with recommended crew size set to "1" the field shows "0" at first. When adjusting number with "+" button it jumps to "2" and then it can no longer go lower than "1".

**Steps To Reproduce**
Save any submarine with minimal recommended crew size 1 and open the save menu again.

**Version**
v0.10.4.0 Windows

**Additional information**
![image](https://user-images.githubusercontent.com/48099798/91329855-f5b55a80-e7c8-11ea-8ed8-a5cfa18f104d.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb955b9fe2e7ab29c380aa6a4b488b3e4dfe545c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
