### ISSUE TITLE
Unclear Skill Requirements for Medical Items

### ISSUE THREAD

**Issue by S1lenos** [Regalis11/Barotrauma#3643]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

The skill requirements for medical items are unclear, and I failed to find them in-game. The official wiki (https://barotrauma.gamepedia.com/Medical_Fabricator) says that, e.g., blood packs require a medical skill of 72 to use. I started a new campaign were the captain (Med Skill 5) did not meet the requirement (only one use), but an engineer (Med skill 21) met the requirements (able to use a single blood pack twice). 
Playing a Medic in a multiplayer campaign, I also realised that the same issue is present with other medical items, e.g. calyxanide having 2 uses long before med lvl. 64

A depiction of skill requirements in-game (e.g. item tooltip) would be massively helpful.

By the way: the required skill for production at the medical fabricator is shown for all items in the medical fabricator menu, and for a few sanity-checked items, all skill values corresponded to the values in the wiki.

**Steps To Reproduce**
Start a new campaign with the Dugong and use a blood pack as the captain or the engineer.

**Version**
Win10, latest official Steam version

**Comment by Regalis11** [comment]
Whether you succeed in using a medical item is actually probability-based; you can use meds successfully even if you don't have sufficient skills (which is most likely what happened with your engineer).

I agree that displaying the skill requirements more prominently somewhere would be helpful though, I think we'll need to look into it.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
