### ISSUE TITLE
Armory and injuries system rework

### ISSUE THREAD

**Issue by un-hunt** [Regalis11/Barotrauma#3646]
The following mechanics should make the game more realistic. I understand that they can be difficult to realize and my ideas can be stupid. By the way, there they are:
1) New personal armor system:
- 3 new items: Armor Plate (has 150 durability and gives 80% damage reduction, slows character down by 20%), Heavy Armor Plate(has 200 durability and gives 90% damage reduction, slows down by 40%) and Ceramic Armor Plate (has 75 durability and gives 100% damage reduction, slows down by 10%). Armor plate can be manufactured with 1 titanium bar, Heavy armor plate - with 3 steel bar and Ceramic armor plate can only be purchased. 
- Body armor should give you only 10% damage reduction without any armor plates placed in it.
- Moloch shell fragment has 500 durability and slows down by 50%.
- Armor plates(and moloch shell fragment)'s durability will be lowered at the same value as the damage they blocked.
- Helmets have 125 durability and slow character down by 5%.
2) New injury and some welding mechanics changes:
- New gear: welding mask(protects from blinding while welding and plasma cutting; can be fabricated with 1 steel bar).
- New injury: blindness - achieves by welding(and plasma cutting) without welding mask(15%/sec) or by Blindizine poisoning. At 25% state vision becomes blurry and gets worse each 25%, resulting a black screen at 100%. Non-critical and dissapears over time(-1%/sec) or by using eyedrops. Diving suit also gives you protection from blindness while welding.
- 2 new items: Eyedrops(ReVision maybe?)(cure blindness by -15%/sec and give effect "Sharp Vision" for 1 minute, which increases visibility range at 1.25 times; lasts for 5 seconds, 2 uses; can be fabricated with 1 Stabilozine and 1 Broad Spectrum Antibiotics), Blindizine(afflicts blindness by 5%/sec, lasts for 20 seconds, 2 uses; can be neutralized with Stabilozine; can be manufactured with 1 Magnesium).
3) Weapons changes:
- Flamethrower should afflict at least five times more damage, because now it's the worst vanilla weapon in game, which kills extremly slowly(Yes, it can set installations to fire, but you will get killed thousand of times before you deal serious damage to them).
- 3 new items: Assault sight(can be placed on SMG; increases visibility range at 1.25 times as long while aiming), Optical sight(can be placed on Harpoon gun; increases visibility range at 2 times as long while aiming) and Silencer(can be placed on SMG and Riot Shotgun; makes shot sound 80% quiter, but increases spread at 2 times). All these items can be made with 1 steel bar.

**Comment by Regalis11** [comment]
Thanks, that's a lot of good ideas! However, we generally avoid having feature requests in the public issue tracker (although we do sometimes make exceptions if it's a small, very concrete request). I'll close this ticket, but we'll take these into consideration!

**Comment by un-hunt** [comment]
Thank you for your attention!
