### ISSUE TITLE
Aliens like Crawlers/Mudraptors/Husks have no cooldowns to their bites.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3647]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Witnessed this lots of times in both SP and MP, but Crawlers/Mudraptors/Husks which are able to get inside submarines can attack more than once or twice in under a second.

[Crawler Murder.zip](https://github.com/Regalis11/Barotrauma/files/5135798/Crawler.Murder.zip)

Watch the two characters to the left side.

**Version**
0.10.4

**Additional Informations**
Apparently characters equipped with just knives and stun gun won't be aggressive with Fight Intruder order against spawned in enemies.

**Comment by itchyOwl** [comment]
They do have cooldowns, but it's intentional that they in some cases can attack faster (using the secondary cooldown). This happens when they change the attack. I didn't spot any bugs in the attached video. Is there any particular issue with this behavior or was it just that you thought it's not intentional?

**Comment by Kaillera** [comment]
> They do have cooldowns, but it's intentional that they in some cases can attack faster (using the secondary cooldown). This happens when they change the attack. I didn't spot any bugs in the linked video. Is there any particular issue with this behavior or was it just that you thought it's not intentional?

The two characters at the left get killed practically instantly

**Comment by itchyOwl** [comment]
They seem to die relatively quickly, true. It could be that there's a bug. I'll try to repro it. If you can give more precies steps, it might help.

**Comment by Kaillera** [comment]
I was mostly spawning in enemies randomly and it happened. It doesn't take long before it starts happening after a few bouts

**Comment by itchyOwl** [comment]
Couldn't repro this. But let's keep the eyes open. If anyone can provide the steps with which I can reproduce the issue, it would be most welcome.

**Comment by Regalis11** [comment]
No known steps to repro, closing at least for now
