### ISSUE TITLE
Crew list state is not reset after exiting a turret

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3648]
The crew list is hidden when starting to operate turret, but it will remain hidden after exiting the turret even if it was open when entering the turret. The crew list state should be reset to what it was before operating the turret.

**Comment by Jlobblet** [comment]
Does this also occur with the chat box?

**Comment by ekqvist** [comment]
Not sure, but I'll check if it does.

**Comment by ekqvist** [comment]
Chat state seems to be reset correctly.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@27ce7a5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
