### ISSUE TITLE
Sub Editor - Turret/Searchlight Angles lines are visible without selecting them. Bad for screenshots.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3649]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Turret/Searchlight Angles lines are visible in the sub editor without selecting them. Bad for screenshots.

**Version**
0.10.4

**Comment by Jlobblet** [comment]
A button which takes a screenshot would be highly useful - effectively working the same as the preview image, just at a larger resolution. Having it respect whether the lighting layer is on or off would also help.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0dcb78cc800f02e506348ac34252587da3a208f2

**Comment by Rokvach** [comment]
No issues, closing.
