### ISSUE TITLE
Broken Junction Boxes will still transmit signal if it comes from another junction box.

### ISSUE THREAD

**Issue by cola98765** [Regalis11/Barotrauma#3650]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Broken Junction Boxes will still transmit signal if it comes from another junction box.

**Steps To Reproduce**
- Spawn 2 Junction Boxes [let's call them A and B] Oscillator, and Light Component
- Set condition of Junction Box B to 0
- Using nodes connect Oscillator -> Box A (Signal_0) -> Box B (Signal_0) -> Light (toggle)
- Light will blink even tho the Junction Box is broken

**Version**
v0.10.4.0 (Windows)

**Additional information**
If you put eg. OR between Junction Boxes it's gonna work as intended.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c388f1a49166b9bad5c2ba0cfa24e6d5e1382aa

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
