### ISSUE TITLE
Show currently-selected sub in server info.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3651]
**Feature-Request**
Sidebar where it displays server description, game mode, round started, and other settings;
a field to show the currently selected sub.

**Comment by Kaillera** [comment]
Personally I would love to know what sub is currently being played as well. I usually pick my servers based on the submarines.

**Comment by FamiliarBreakfast** [comment]
I think it would be best to just show the current sub and have an option to view all the buyable/downloadable subs.

**Comment by Regalis11** [comment]
Finally implemented in https://github.com/Regalis11/Barotrauma-development/commit/5d820710ba6119baab423a3842afab3c43211e76 (commit in our private repo)

**Comment by Rokvach** [comment]
Tested on both dedicated and ingame hosted server, as soon as I switch the sub the information gets properly updated. Working correctly, can be merged and closed.
