### ISSUE TITLE
Server Filters Should Use Ternary Switch System

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3652]
[Feature Request, Server Browser]
A good suggestion popped up on the discord, server filters should probably have YES, NO, and EITHER/DON'T CARE states. This would allow for the most filtering possible, and allow people to filter categories just the way they want, instead of the somewhat inconsistent negative and positive filters that the game currently uses.
![image](https://user-images.githubusercontent.com/47284081/91515730-6c2c8800-e8af-11ea-9dd5-aa35628fc16c.png)

**Comment by FamiliarBreakfast** [comment]
This definitely needs to be added. I hate that you can't filter to servers that only have VC

**Comment by Regalis11** [comment]
Implemented now that https://github.com/Regalis11/Barotrauma/pull/4917 has been merged

**Comment by Rokvach** [comment]
No issues here, closing.
