### ISSUE TITLE
Allow ignore dead and ignore human toggles for motion detector during rounds?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3653]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was wondering if we could put the toggles for ignore dead and humans on motion detector a for during rounds? It's hard to make neat traps without them and the sub editor.

**Version**
0.10.4

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/0c1ff15e8eb44ede7a565895b4323379e65dd388

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
