### ISSUE TITLE
Reactor Interface Should Show Tooltips

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3656]
[Feature Req]
![image](https://user-images.githubusercontent.com/47284081/91590086-64f19280-e920-11ea-9587-140a3551f55b.png)
Many players online admit to never playing the tutorial (albiet a minority). For the sake of overconfident players or players who are coming back to the game after a long time, it may be good to have things such as the status lights on the reactor interface show tooltips explaining what they mean when hovered over. Only a player who doesn't know what they're doing would move their mouse over the lights in the first place. Essentially, there is no reason not to do this.

**Comment by Rokvach** [comment]
Closing this one as there's another ticket which handles this. Closing.
