### ISSUE TITLE
Shuttle Shell A18 does not leak when placed only on the vertical hull line.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3657]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shuttle Shell A18 does not leak when placed only on the vertical hull line. It only leaks on the horizontal line. Affects Selkie that is using it as a vertical wall.

**Version**
0.10.4

**Comment by Regalis11** [comment]
We have a newer ticket about the general issues with these sloped walls https://github.com/Regalis11/Barotrauma/issues/7154, closing this one
