### ISSUE TITLE
Share server logs with moderators/admins

### ISSUE THREAD

**Issue by PeanutCultist** [Regalis11/Barotrauma#366]
I am a moderator of a Barotrauma server, and the owner attempted to give me the server logs access. It did not work. So I don't know if this is a bug, is not planned, or hasn't been implemented yet.

**Comment by Regalis11** [comment]
This has not (yet) been implemented, only the server logs events and the logs are not sent to clients.

**Comment by PeanutCultist** [comment]
We spent an hour trying to figure it out lol
Thanks for helping.

**Comment by CryIz** [comment]
When the Host is playing with the others, there is no log that It has not heard.

Example:
[12.04.2018 16:21:54] Red Shuhov: а как же без них?
[12.04.2018 16:21:55] Corvo Markov closed Windowed Door
[12.04.2018 16:21:55] Thomas Nines: Что----дним-в----------.-п--а-и----ол ---аб------т--н-ка.
[12.04.2018 16:21:56] Corvo Markov opened Hatch
[12.04.2018 16:21:58] Гоглачёв Илья: Никак.

**Comment by MoonEater916** [comment]
When we run our server we pipe the output to a file... we have complete logs. No log feature needed just some knowledge of commands.

**Comment by MoonEater916** [comment]
We pipe out logs from the server to a file using commands at launch. We put the logs on a repository for moderators. There are defiantly work around for this issue.
