### ISSUE TITLE
Faraday Artifact doesn't do EMP animation in Multiplayer

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3660]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Faraday Artifact doesn't do EMP animation in Multiplayer

**Version**
0.10.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b986167e26f99fbcd0fd347f1c9cb5ccb0dd37c0

**Comment by Rokvach** [comment]
No issues, closing.
