### ISSUE TITLE
Diving Suit deconstruction gives incorrect item

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3661]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Diving suits deconstructs into:
1 Titanium
1 Aluminum
1 Rubber

Expected:
1 Titanium Alloy
2 Rubbers

Like the original fabrication recipe.

**Version**
0.10.4

**Comment by danielasteljoki** [comment]
Fixed in 7f57166.

**Comment by Rokvach** [comment]
No issues, closing.
