### ISSUE TITLE
roomname.ballasttank4 shows as "Ballast tank E" instead of "Ballast tank D"

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3662]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/48099798/91662121-9f099280-eae0-11ea-953c-ccad1aeffe01.png)
When using built-in room names for ballast tanks the 4th ballast tanks is called "E" instead of "D"

**Version**
v0.10.4.0 Windows

**Comment by Kaillera** [comment]
I suggest adding D without removing E. Since we can send out 5 signals straights from the nav terminal, I think having 5 of them should be good enough.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b8876ca1b231f96a746e82b2de9c9b9b8b6f713f

**Comment by Rokvach** [comment]
No issues, closing.
