### ISSUE TITLE
Ruin's Alien Discharge Coil doesn't discharge shock from sensors.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3663]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ruin's Alien Discharge Coil doesn't discharge shock from sensors. Both in SP and MP.

**Version**
0.10.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a0186eafbd3784c14e8d45c394144b96e959ca7

**Comment by Rokvach** [comment]
No issues, closing.
