### ISSUE TITLE
Characters that became a husk is saved into the next round, Player forced to watch next round.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3668]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Characters that became a husk is saved into the next round, That Player is forced to sit and watch next round until someone kills the husked character.

**Version**
0.10.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d2496fc60780b3c0d3046eac464dc795cb305439

**Comment by Rokvach** [comment]
Works correctly for players and bots, Closing.
