### ISSUE TITLE
Research Station's medical compartments has no medicine to steal

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3669]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Research Station's medical compartments has no item to steal

**Version**
0.10.4

**Comment by Regalis11** [comment]
Not sure if this is a bug or intentional, so I added both tags

**Comment by danielasteljoki** [comment]
Added some items in 2d44ac0.

**Comment by Rokvach** [comment]
No issues, closing.
