### ISSUE TITLE
I cant play barotrauma on windows 7

### ISSUE THREAD

**Issue by LOLESIN** [Regalis11/Barotrauma#367]
[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1907890/crashreport.txt)
Ive got crash report. FIX THAT

**Comment by MoonEater916** [comment]
Works fine for me and many others on windows 7. I think its probably something other than windows 7.

**Comment by HetNeSS** [comment]
Win7x64, works fine too

**Comment by Regalis11** [comment]
Duplicate of #391. Closing this one because the newer one has more detailed info.
