### ISSUE TITLE
Military Station's Crew Quarter cabinets are kinda bare

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3670]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Military Station's Crew Quarter cabinets are kinda bare. Was expecting them to be tagged with outpostcrewcabinet.

**Version**
0.10.4

**Comment by Regalis11** [comment]
Not sure if this is a bug or intentional, so I added both tags

**Comment by danielasteljoki** [comment]
Seems to have been fixed already.

**Comment by Rokvach** [comment]
No issues, closing.
