### ISSUE TITLE
The Medium Steel Cabinets/Trash Can in Outposts always contain no items

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3671]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Medium Steel Cabinets/Trash Can in Outposts always contain no items. For the cabinets I was thinking at least screwdriver/wrench/crowbars/welding too/welding tanks/oxygen tanks should be randomly in them. Maybe 1~3 items in them at most.

For the Trash Cans, maybe we can have Soda Cans, Papers, or other stuff players can try to steal for very basic materials. Maybe a half used bottle of opium or ethanol can be randomly in there.

**Version**
0.10.4

**Comment by danielasteljoki** [comment]
Fixed in 2d44ac0.

**Comment by Rokvach** [comment]
No issues, closing.
