### ISSUE TITLE
Game crashes when I change to a submarine I brought.

### ISSUE THREAD

**Issue by Purplemadness987** [Regalis11/Barotrauma#3672]
I brought the Humpback attack class submarine, I changed to it and started doing a mission, shortly after that the sub blew up and my crew died, so I pressed retry to load my old save, I went to change my sub to the humpback submarine but when I did the class turned to undefined, the recommended crew experience turned to unknown and the game version for the sub to work turned to 0.0.0.0 and when I press the change button the game crashes, its stuck like this and I cant use that sub, anyone know how to fix it?

![20200831_150832](https://user-images.githubusercontent.com/39831216/91729795-fff6a080-eb9c-11ea-8b9d-6603c14451e6.jpg)

Its on game version 0.10.4.0 and I'm on windows.

**Comment by Kaillera** [comment]
It's a known bug. Purchased subs, upgrades, and Hired crew aren't saved into the file when you undock from the outpost. You have to redock or complete the next level. What's happening here is that there are certain things saved into the save file, and that is what sub you were using.

**Comment by Regalis11** [comment]
Yep, this seems to happen as a consequence of #3343. Should be fixed in the upcoming patch, sorry for the inconvenience!
