### ISSUE TITLE
Please seperate "Buy & Sell" and "Select Next Destinations" from ManageCampaign permission.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3675]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Been hosting my own server a lot, and I give everyone ManageCampaign by default because I like to let players select the next map/missions and buy/sell stuff on their own (In case I die for instance). The only problem I have is that they accidently misuse "Server Lobby" button to quit the session by themselves or players being able to Continue Campaign when people are Briefing/Debriefing in the lobby.

**Version**
0.10.4

**Additional Informations**
ManageMerchant and ManageMap permissions perhaps?

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0764d879fc9cc051bab9a1f4de8c801916dfac29

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
