### ISSUE TITLE
Clicking on job name or the area around it won't select the job preference

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3676]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clicking on job name or the area around it won't select the job preference. I think it matches the white area on the image below that is visible when you hold left mouse button on it.

![image](https://user-images.githubusercontent.com/10875340/91913588-50155600-ecb6-11ea-992f-6734afee46b7.png)

**Steps To Reproduce**
1. Enter server lobby.
2. Try changing desired role by clicking on its name.
3. Job doesn't change.

**Version**
0.10.4.0, Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6bbb01d948319860383b68f00f6b6b0b1fb36481

**Comment by EtiamNullam** [comment]
Works fine in 0.10.502.0 (unstable).

**Comment by Rokvach** [comment]
Closing.
