### ISSUE TITLE
"Killed a Moloch" achievement possibly unobtainable

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3677]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've been unable to get the achievement for killing a moloch for quite some time, but now i'm fairly certain its not working properly.
I've been playing a campaign with 4 other people, none of us had this achievement before and even though we killed a few of them, still none of us have it unlocked. Cheats were not enabled and other achievements were working fine during that session, there were no bots, so the final blow must have been delivered by one of us.

**Version**
v0.10.4.0

**Comment by Regalis11** [comment]
Looks like the achievement wouldn't unlocked if you killed a "boss variant" of the moloch (= a moloch that's the target of a mission). Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a11ed121e701f37c1790c9f1abc33bb0ca81d7f6

**Comment by Rokvach** [comment]
No issues, closing.
