### ISSUE TITLE
Wire nodes are mirrored when the rewiring character turns around

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3678]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wire nodes are mirrored when the rewiring character turns around

**Steps To Reproduce**
1. Start wiring something
2. Add some nodes on the wall
3. Turn around

**Version**
v0.10.501.0

**Comment by Kaillera** [comment]
Can confirmed. Wire node was doing janky teleportation when I turned around.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ece31832bb95723a18b339f5313fc8c38e4fb9d8

**Comment by EtiamNullam** [comment]
Seems like its no longer an issue in 0.10.502.0 (unstable).

**Comment by Rokvach** [comment]
Closing.
