### ISSUE TITLE
[0.10.501] Outpost NPC icons aren't visible if the NPC is in view range, but not in line of sight

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3682]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost NPC icons aren't visible if the NPC is in view range, but not in line of sight

**Version**
0.10.501

**Comment by Regalis11** [comment]
Got a new ticket about this https://github.com/Regalis11/Barotrauma/issues/5537, closing this one as the new one has a bit more info/ideas
