### ISSUE TITLE
Add Capture Group Output to Regex Find Component

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#3683]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a feature request, sorry.  

Add the ability for regex components to output a captured value. This feature makes numerous appearances in the Discord as a request.  
I envisage it with a checkbox to determine whether to output capture group value, and an integer field or dropdown - possible doing some analysis of the expression to determine group numbers/names - to specify which capture group to output.  
Adding this feature would allow players to construct circuits that are already being made, but much more compactly.

**Version**
0.10.4.0+

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/2e6c46a95f22248e1d1b4c4dc749b93a15324480

Added a checkbox that when selected will output a named capture group where the "Output" field is the name of the group

Example: 

![](https://kosblue.com/e/roqhtj.png)
![](https://kosblue.com/e/bwpnsk.png)

**Comment by Rokvach** [comment]
No issues, closing.
