### ISSUE TITLE
Crateshelf does not have containable items="crate" tag.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#3684]
Crate shelf still refers to items by their identifier
`<Containable items="metalcrate,securemetalcrate,explosivecrate,chemicalcrate" />`
instead of by their universal tag
identifier="metalcrate" tags="crate"
identifier="explosivecrate" tags="crate"
identifier="chemicalcrate" tags="crate"

Items tagged with 'crate' cannot be placed in crate holders as a result, unless they instead use the previous workaround method of including 'metalcrate' as a tag in the item.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/28b78cc86ea14b90feae80e28a82dd4203943710

**Comment by Rokvach** [comment]
No issues, closing.
