### ISSUE TITLE
[0.10.501] Bots seems to cause frame rate drops during decision makings

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3685]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots seems to cause frame rate drops during decision makings

**Version**
0.10.501

**Comment by itchyOwl** [comment]
It's possible, but in order to fix this, it would be helpful to get any further information: in what context does this happen? If you have steps to repro, that'd make it much easier to identify the issue.

**Comment by itchyOwl** [comment]
To confirm that it's an issue with the ai, you can use disablecrewai/enablecrewai commands and see if there's any difference. It's normal if there's a difference from 5-10fps (depending on how many characters there are), but more than that or periodical drops probably mean that we need to change something in the code.

**Comment by itchyOwl** [comment]
Does this issue still persist or was this actually caused by the LOS improvements? (same or different issue?)

**Comment by Kaillera** [comment]
I think this is due to bots opening lots of doors, especially in outposts when there's many of them. I think it's now more #3687 in 0.10.504

**Comment by itchyOwl** [comment]
Ok, I'll close this, since it seems unrelated to the AI.
