### ISSUE TITLE
Grenade launcher Self implodes when firing due to bug

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#3686]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 The grenade launcher self implodes in your face, when firing it when you have either an oxygen tank, or a welding fuel tank in your inventory.    

This also happens if you don't have a tank in your inventory, but you are firing the grenade launcher near storage cabinets where a tank is present in the cabinet, such as a diving mask with oxygen tank inside. 

**Steps To Reproduce**
![602960_20200902220250_1](https://user-images.githubusercontent.com/62313026/92036649-7a275080-ed68-11ea-8fd6-678a25ef0a51.png)
Just shoot the grenade launcher, when  you have an oxygen or welding fuel tank on you.   Note: If the tank is in the diving mask or plasma cutter, you will not self implode when firing the grenade launcher.

Another case is when the  tank is in the diving mask and in a cabinet, and you fire the grenade launcher near it, it will trigger the explosion. 
**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
Needs more testing, to see why it triggers the self implosion when firing the grenade launcher, but this is the basis.

**Comment by EtiamNullam** [comment]
Was it fixed already? Seems to work correctly in 0.10.502.0 (unstable) yet it still makes you explode in 0.10.4.0 (stable).

**Comment by Rokvach** [comment]
Closing
