### ISSUE TITLE
[0.10.504] Serious frame rate drops with "Cast Shadow" Lights outside of Submarine onto wrecks/outposts/drones/subs

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3687]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Serious frame rate drops with "Cast Shadow" Lights outside of Submarine onto wrecks/outposts/drones/subs.

This lag did not occured in 0.10.4

**Version**
~0.10.504

**Comment by Kaillera** [comment]
The funny thing is, when your submarine is actively touching wrecks or station, the frame rate stops dropping so much.

**Comment by Kaillera** [comment]
Seems like doors opening and closing affects frame rate.
Also turning off lighting with "lighting" command helps immensely.

**Comment by Kaillera** [comment]
[0.10.504]
Seems better than 0.10.503, but the frame dies whenever doors are opening and closing still. Turning on lighting cheat still helps against that.

**Comment by Kaillera** [comment]
Okay an update on this issue. I found what it is. I don't know what changed between 0.10.4 and 0.10.5 shadow logic, but it seems like any turret/searchlight/light that casts shadow frame lags heavily when you point them at outposts/wrecks/drones pointing at sub/sub pointing at drones.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/323fdd2. 

Although, shadow-casting lights with a very long range are still pretty performance intensive, which is why by default the turrets don't cast shadows.

**Comment by Rokvach** [comment]
Confirmed to working, closing.
