### ISSUE TITLE
Move Unstable version info higher to accommodate the new channel switching UI

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3690]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/eb7caf6e-3361-4c46-b2a8-c6c08f47ed6f)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cbdbbb5f818666dda566a7cd37f640aa14d4b8de

**Comment by Rokvach** [comment]
No issues, closing.
