### ISSUE TITLE
Unable to give the Operate Weapons order when there's only 1 turret

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3691]
**Description**

Instead of the Operate Weapons order being quick-assigned to a suitable crew member, the command interface tries (and fails) to show options for the order without any further nodes available.

**Steps To Reproduce**
1. Open the sub editor
2. Load Azimuth
3. Delete one of the two turrets
4. Enter test mode
5. Try to give an Operate Weapons order

**Version**

0.10.501 Windows

**Additional information**

Originally reported as a part of #3679

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
