### ISSUE TITLE
Debugdraw is broken

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3693]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image (12)](https://user-images.githubusercontent.com/14351070/92106471-1e52db00-eded-11ea-83e6-4f9d6b3f363b.png)

**Version**
v0.10.501.0

**Comment by itchyOwl** [comment]
GameScreen.cs:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/78e6ca2f-92a4-463d-8996-eb48a7892adc)

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cbd1f4c738ca8574fa321299479ffe6293c11c3d

**Comment by Rokvach** [comment]
No issues, closing.
