### ISSUE TITLE
Typhon 1, Remora, Berilia, and R-29 does not have power wire to top docking port

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3701]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Typhon 1, Remora, Berilia, and R-29 does not have power wire to top docking port

**Version**
~0.10.501

**Comment by danielasteljoki** [comment]
Fixed in a7b0ce2. Remora and R-29 were fixed earlier.

**Comment by Rokvach** [comment]
No issues, closing.
