### ISSUE TITLE
[0.10.501] Multiplayer - Breeding Ground turned into Outpost the moment I got there. Level Transition oddities.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3702]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I started this multiplayer save after I saved leaving from a City and restarted the server.

So I just played a level going from a City to a Breeding Ground. The moment I arrived to the Breeding Ground, selected my next destination and loaded into the next level. That next level ended immediately, and then it started a new level by itself. I ended up in a Habitational Outpost afterward.

[Server.log](https://github.com/Regalis11/Barotrauma/files/5169344/Server.log)
[Client.log](https://github.com/Regalis11/Barotrauma/files/5169346/Client.log)
![Capture](https://user-images.githubusercontent.com/5086682/92130670-01111300-edd3-11ea-83b6-2bc2ebb1cc03.PNG)

**Version**
0.10.501

**Additional Informations**
I also automatically took a -10 reputation hit to the location as it was automatically going to the outpost level by itself.

**Comment by Kaillera** [comment]
The save file in #3763
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5184886/Multiplayer.zip)

Apparently has a high chance of this happening if you reach the end of the level on it.

**Comment by Kaillera** [comment]
Seems like every natural formations are doing this.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ee3449d70b64bcaaefb0db2d557f3ee06d57268

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
