### ISSUE TITLE
Merchant's does not display the correct price when buying/selling when reputation changes during the level

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3703]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Merchant's does not display the correct price when buying/selling when reputation changes during the level

**Version**
0.10.4

**Additional information**
Makes it hard to juggle the merchant's wallet to completely 0 him out when you don't know how much things cost anymore. There were actually 2 moments in the last month where 1 mark was the difference for a new sub, and having to do 1 more level.

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@f86bf65

**Comment by Kaillera** [comment]
Currently it only refreshes the price when you start adding/removing things from carts
 It should also refresh right as you talk to the merchant.

**Comment by ekqvist** [comment]
Oh, it seems that the fix worked only for singleplayer. I'll do a bit more testing in multiplayer now.

**Comment by ekqvist** [comment]
Should be fixed for MP in Regalis11/Barotrauma-development@9b54709. Seemed like it worked correctly when the reputation changed as a result of an event, but incorrectly when the reputation changed as a result of a console command or stealing, for example. Now, the game should send campaign state update in MP campaign whenever any reputation changes.

**Comment by ekqvist** [comment]
Moving to the QA To-Do as the fix is going to the next build

**Comment by Rokvach** [comment]
Working correctly, closing.
