### ISSUE TITLE
[0.10.4.0] Used railgun shell collides with player when dropped

### ISSUE THREAD

**Issue by Coryf88** [Regalis11/Barotrauma#3705]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dropping a used railgun shell, that didn't detonate due to a collision, collides with the player.

**Steps To Reproduce**
1. Fire a railgun straight up.
2. Wait for the railgun shell to fall back down.
3. Pick it up.
4. Drop it.

**Version**
0.10.4.0
Windows

**Additional information**
N/A

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aca1410c4fc680038a9d5bd9262dd12f5cc4fa19

**Comment by Rokvach** [comment]
Working correctly, closing.
