### ISSUE TITLE
Husk faces not always visible (on the server side?)

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3706]
While testing some other husk related things on the bugfixes branch in a local multiplayer session, I encountered that after turning into husks, the husk faces didn't always appear properly on the server side.

I took a look in the code and gave it a bit more testing, but wasn't able to reproduce the issue anymore.

Here's two images that show the issue. In the images, there are two human husks. On the client side both look like husks, but on the server side one of the two doesn't have the husk face even though it should.

I haven't encountered the issue on single player.

![husk_client.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/d81094b9-f771-4b19-b114-ef4a00b95708)
![husk_server.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/da4225af-ede7-4015-b44d-b08a79a46239)

**Comment by Regalis11** [comment]
As a sidenote, the server is a command line application, so I assume by "server" you mean the client hosting the server

**Comment by itchyOwl** [comment]
Of course.

**Comment by itchyOwl** [comment]
Not sure about removing this: if it happens frequently, shouldn't we just try to fix it?

**Comment by Regalis11** [comment]
Does it happen frequently? I've personally never seen it happen, haven't been able to reproduce it and there have been no other reports about it afaik.

**Comment by Rokvach** [comment]
I haven't seen this happen as well, but it is a detail that is also very easy to miss and the issue can be easily thought to be a feature too where not all faces are overly beaten up. So if it still exists those would be why it hasn't been reported or noticed.

**Comment by itchyOwl** [comment]
Not sure, if it's very rare/unreproduceable, we could just close the ticket. Perhaps @Rokvach could give it a bit of testing before we decide?

**Comment by Rokvach** [comment]
Tested, everyone had the correct husk face after turning in a husk in multiplayer, tested in mission mode and campaign and for a large selection of bots.

**Comment by itchyOwl** [comment]
Ok, then it's probably some weird edge case that we can safely ignore for now.
