### ISSUE TITLE
Outpost Event - Giving Directions, no successful rewards

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3708]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There's no successful reward for working with the other captain to finding how to get out of the hell hole.

**Version**
~0.10.501

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7cae49afa0994d11f61ff5d252f7c5f003a849a7

**Comment by Rokvach** [comment]
No issues, closing.
