### ISSUE TITLE
Oxygen distribution logic doesn't work correctly in multi-hull rooms

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3709]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://steamcommunity.com/app/602960/discussions/0/2949250308627705158/

> - The amount of oxygen contained in a room is proportional to its size as oxygen level drops faster in small rooms.
> - Oxygen flows through gaps just fine.
> - The amount of oxygen produced by one vent is proportional to the size of the hull where the vent is located.
> - BUG: Multiple hulls with gapsinbetween are not considered as a single volume even when the hulls are linked together.

**Version**
Any

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f88fdc36262121a6641430ab5e0c758fb87917cb

**Comment by Regalis11** [comment]
Looks like my fix broke oxygen generators altogether, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/52d79b3280e38c45c3596672981d509a4e85e21c

**Comment by Rokvach** [comment]
No issues, closing.
