### ISSUE TITLE
Bots can undock the sub from outposts

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3710]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Apparently it's possible for AI captains (and presumably other characters ordered to steer the sub) to undock the sub from the outpost, triggering a level transition:
https://steamcommunity.com/app/602960/discussions/0/2919976282206806405/

**Steps To Reproduce**
Haven't tested this myself yet, but I think giving a bot an order to navigate to destination while in an outpost level should do it.

**Version**
v0.10.0.0 and later

**Comment by ekqvist** [comment]
> I think giving a bot an order to navigate to destination while in an outpost level should do it

Seems that it can be reproduced exactly like this. This will open the map interface.

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@84ad472

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
