### ISSUE TITLE
[0.10.502] Dedicated Server - Players cannot load into Campaign rounds. StartGame has failed!

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3711]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dedicated Server when campaign round starts will not load players in. StartGame has failed! error. Campaign specific it looks like.

![Capture](https://user-images.githubusercontent.com/5086682/92245826-e3a37e00-ee92-11ea-80ea-12458e305f85.PNG)

**Version**
0.10.502

**Comment by Rokvach** [comment]
Confirmed working, closing.
