### ISSUE TITLE
[0.10.502] Dedicated Server - Keeps prompting player to download custom submarine even though they have the exact version already

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3713]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dedicated Server keeps prompting player to download custom submarine even though they have the exact version already.

**Version**
0.10.502

**Additional Informations**
Exact version from the steam workshop that is.

**Comment by Rokvach** [comment]
Confirmed working, closing.
