### ISSUE TITLE
[0.10.502] P2P Server - Crashes when any players joins the server aside from Host

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3714]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
P2P Server crashes when any players joins the server aside from Host. Both during a round and in the lobby.

[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/5175311/servercrashreport.log)

**Version**
0.10.502

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ebe06025f52e716b60b8f311c8558ea1a51a421c and https://github.com/Regalis11/Barotrauma-development/commit/8e288660bf606eb95bb9bc2e719cfe42984fc90d

**Comment by Kaillera** [comment]
Haven't seen this happened since the second build of 0.10.502

**Comment by Rokvach** [comment]
Closing
