### ISSUE TITLE
[0.10.502] Multiplayer - Can't move sub vertically client-side.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3715]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You cannot move vertically in multiplayer with the submarine on client side. Server side moves around just fine. #3725 I guess is afflicted by this.

**Version**
0.10.502

**Comment by Kaillera** [comment]
This is currently making multiplayer unplayable for this version.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bfd3f08bae7b94ae9fdbb727e45592090ff540db

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
