### ISSUE TITLE
[0.10.502] No delay cooldown to placing down wire nodes during level?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3716]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems to me that just clicking with my mouse seems to put down wire nodes rapidly, sometimes even two.

![Capture](https://user-images.githubusercontent.com/5086682/92253503-9547ac80-ee9d-11ea-8900-b0f7a026b780.PNG)

**Version**
0.10.502

**Comment by Regalis11** [comment]
I don't think this is a bug, there is no cooldown to placing nodes.

**Comment by Kaillera** [comment]
Hmm. For some reason it's spilling extra nodes with one click for me then.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1dc3ad4e192f69b265dda304a5bc2cfef56d8e90

**Comment by Rokvach** [comment]
No issues, closing.
