### ISSUE TITLE
Crash Report upon quitting game after updating Steam Workshop Submarine.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3719]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure why this crash report was generated upon me quitting the game when I updated my submarine on the Steam Workshop.

[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5175788/crashreport.3.log)

**Steps To Reproduce**
1. Boot up the game.
2. Go to Steam Workshop.
3. Updated custom sub.
4. Quit game. Crash Report shows up.

**Version**
0.10.4

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/50801a8225eb8a61355acf09813f0440403f4b5a

**Comment by Xeavas** [comment]
[0.1100.0.6] - Unable to replicate issue with the instructed reproduction methods 👍

**Comment by Rokvach** [comment]
Closing.
