### ISSUE TITLE
[0.10.501] Piercing Coil Ammo can travel through the joints between level walls

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3720]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Piercing Coil Ammo can travel through the joints between level walls

![Capture](https://user-images.githubusercontent.com/5086682/92261302-371fc700-eea7-11ea-9534-7f37158ff5fc.PNG)

**Version**
~0.10.502

**Comment by mygamingaccount** [comment]
Is this really a bug? It's always been like that

**Comment by Rokvach** [comment]
Is this still an issue with the new level gen? There isn't much of anything on the other side of walls anymore.

**Comment by Regalis11** [comment]
This can still happen, although the projectile tends to get blocked by the solid cells at the other side of the joint. I think this is such a minor issue that I wouldn't spend time fixing it (could even be considered a feature imo).
