### ISSUE TITLE
Don't randomly choose an invalid sub in campaign init screen

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3721]
Currently in the main menu when you click "new campaign" the start screen chooses a sub randomly that may not actually be under 6000mks, or have a defined class. The menu should probably not do this as it will only serve to confuse players.

In general it might be good to completely grey out any of the subs that can't be selected entirely.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0f1c09e607bd4f569b4fdd2aee82990c901caf2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
