### ISSUE TITLE
Carry over reputation mouseover feature from debugdraw into main game.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3722]
[Feature Request]
![image](https://user-images.githubusercontent.com/47284081/92266841-73522800-eea5-11ea-989f-10d9b06ff15f.png)
This is a very nice feature in debugdraw and there doesn't seem to be a reason why this couldn't be polished up and put in the main game.

**Comment by ekqvist** [comment]
Implemented in Regalis11/Barotrauma-development@435b8bb. Only visible for locations that have been discovered and have an outpost.

**Comment by Rokvach** [comment]
I don't think its necessary to display the reputation in such precision @ekqvist 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b5dfe5ee-b6a8-4cf6-badd-371634b92eef)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f69de02f1520b3562447ff25a85a2d9d9507b2c6

**Comment by Rokvach** [comment]
No issues, closing.
