### ISSUE TITLE
[0.10.502] Can still dock to the bottom right docking port of Kastrul_Wrecked

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3723]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can still dock to the bottom right docking port of Kastrul_Wrecked

**Version**
~0.10.502

**Comment by mygamingaccount** [comment]
Kastrul_Wrecked sub has a dockingport instead of dockingport_wrecked on top

I think this is a feature. Exploring derelicts is fun when they are dry, it's a different experience.

I could imagine something like having to "hack" into a wrecked sub to initiate the docking protocol remotely :smiley:

**Comment by danielasteljoki** [comment]
Let's keep wreck docking ports uniform for now and add dockable wrecks as a possible feature later on. Fixed in 929f35c.

**Comment by Rokvach** [comment]
No issues, closing.
