### ISSUE TITLE
[0.10.502] Multiplayer - Text "moderationmenu.userinfo" not found

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3724]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Right click any players in Tab Menu or Crew List.
Error: Text "moderationmenu.userinfo" not found

**Version**
0.10.502

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0411a52beea8e8f2c1a80043f5394da135409f7c

**Comment by Rokvach** [comment]
No issues, closing.
