### ISSUE TITLE
[0.10.502] Mods in settings keeps turning off itself randomly

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3727]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mods in settings keeps turning off itself randomly after playing the game and reloading.

**Version**
0.10.502

**Additional Informations**
Was playing on Dedicated Server normally.

**Comment by Kaillera** [comment]
https://www.youtube.com/watch?v=r93I2GK2k04

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7c830d3b0ce342a9bf3d57bbc1d1aee62e1341b4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
