### ISSUE TITLE
[0.10.4.0] EMP grenades causing injury and triggering secondary explosions

### ISSUE THREAD

**Issue by Coryf88** [Regalis11/Barotrauma#3729]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
EMP grenades cause deep tissue injuries and Oxygen/Welding Fuel Tanks to explode.

**Steps To Reproduce**
Throw an EMP grenade at your feet and notice it caused "Deep Tissue Injury" afflictions.

Throw an EMP grenade near a container that contains Oxygen Tanks and/or Welding Fuel Tanks, and notice that they explode and are now empty.

**Version**
0.10.4.0
Windows

**Additional information**
N/A

**Comment by Regalis11** [comment]
The tiny amount of damage is intentional. Fixed the secondary explosions in https://github.com/Regalis11/Barotrauma-development/commit/50035bacddbdaabdd18f8497b4056221150033b6

**Comment by Rokvach** [comment]
No issues, closing.
