### ISSUE TITLE
Afflictions' Status Effects Loaded Incorrectly(?)

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3730]
[Bug, Modding]
When the game is first starting up, afflictions seem to load and have their status effects' references ro other identifiers "evaluated" before the game has the chance to "forward declare" any of the item/affliction identifiers (or whatever the properly named game equivalent is).
![image](https://user-images.githubusercontent.com/47284081/92300070-8e607e80-ef1d-11ea-8af7-2a3c559d508d.png)
in the above image the item is defined just fine and can be spawned in normally with the console.
Funnily enough, this doesn't happen when you turn a mod off and back on in settings, presumably because all of the items by that point are properly loaded/declared.
For all intents and purposes, it's impossible to spawn items from an affliction's status effect. It should also be noted that other features involving "forward declaration" or "identifier prototyping" in affliction status effects are broken, eg if an affliction status effect wants to refer to another status effect in the same file, the affliction must be defined after the affliction it's referencing (like in C languages) .
Writing this at 2:30 AM. might revise this tomorrow morning.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1f83ed5bffd0e63310caf827d65b2cd8a625e7b4

**Comment by Rokvach** [comment]
Confirmed working, closing.
