### ISSUE TITLE
[Unstable 0.10.502] - Hardline cutoff block of 'Fog of Visibility' when looking through guns

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#3731]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using coil/railguns there is a square shaped hardline visibility cutoff.

**Steps To Reproduce**
- Setup a coil or railgun
- Set the light settings to: 
- [x] Cast Shadows
- [ ] Draw Behind Subs
- [x] Is On

**Version**
Unstable 0.10.502, Windows 10 64-bit

**Additional information**
Effect can be observed on the guns of the Orca.
Pics:
![20200905072035_1](https://user-images.githubusercontent.com/58775950/92304326-fa0d1080-ef4a-11ea-98b4-21df58a15ac7.jpg)
![20200904143829_1](https://user-images.githubusercontent.com/58775950/92304329-fe392e00-ef4a-11ea-8d59-52b82bd26f96.jpg)

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/433e481047de71902062a33c368317d04d4bf1dc

**Comment by Regalis11** [comment]
The fix caused major performance issues, moving back to todo

**Comment by juanjp600** [comment]
Performance issues should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd97337be435b8ee4ecce706f83de7cbddbadb6c

**Comment by Rokvach** [comment]
Framerate issue has been fixed, this is working correctly now. Closing.
