### ISSUE TITLE
Aliens are unable to attack in Ruins

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3732]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Aliens are unable to attack in Ruins. Been noticing this for a while now.

**Version**
~0.10.502

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/21428b206eb7f9f34226c559f5c8283e73fda7b0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
