### ISSUE TITLE
Unable to scroll down the event manager to see the entire list of "Current events"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3733]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to scroll down the event manager to see the entire list of "Current events".

Was trying to debug #3350, but I can't see the entire list to make an accurate report.

**Version**
~0.10.502

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d585f5318fdd93f431f88b25d42a51dec2f54a0f

**Comment by Rokvach** [comment]
Tested, new approach seems to be to just add a new column to show more events rather than having to scroll. So this shouldn't be an issue anymore. Closing.
