### ISSUE TITLE
[0.10.502] crewmodule_03 is missing bracket for the fire extinguisher

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3734]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
crewmodule_03 is missing bracket for the fire extinguisher

**Version**
0.10.502

**Comment by danielasteljoki** [comment]
Fixed in 2d44ac0

**Comment by Rokvach** [comment]
No issues, closing.
