### ISSUE TITLE
securitymodule_01 and 02's Secure Steel Cabinet can be opened by anyone, and always has no items

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3735]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
securitymodule_01 and 02's Secure Steel Cabinet can be opened by anyone, and always has no items

**Version**
~0.10.502

**Comment by danielasteljoki** [comment]
Fixed in 2d44ac0. Note that the id required for opening secure cabinets doesn't exist yet. Need to spawn outpost security in with compatible id cards.

**Comment by Rokvach** [comment]
No issues, closing.
