### ISSUE TITLE
Changing your characters name resets votekicks against you

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#3736]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Basically, if you have say, 5/7 votes needed to kick someone, and they change their name, it will reset those votes, so then it will be 0/7 votes needed to kick, and people who already voted will have to do it again.

**Steps To Reproduce**
Start votekicking a person.
Have them change their character name.
They have reset their votes.

**Version**
v0.10.4.0 
I have no idea what the server was running. Bug was not limited to me, everyone else also lost their votes each time.

**Additional information**
This can and was being abused by trolls to avoid getting votekicked.

**Comment by EdusFF** [comment]
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/e7fb8a2e92c76717dfab26ca86c4b61000c4b70b

**Comment by Rokvach** [comment]
No issues, closing.
