### ISSUE TITLE
[0.10.4.0] Items in duffel bags/crates saved as item assembly do not save when first placed outside the hull

### ISSUE THREAD

**Issue by mario31274** [Regalis11/Barotrauma#3739]
Repost of #3616. I didn't describe the issue clearly enough, and the thread was closed but I'm not sure whether the problem is really solved, so I decided to create a new one.

**Description**
If you place the assembly outside hulls first, the items inside won't be saved. But if you place inside the hull first, they will.
This issue applies to not only duffel bags but also crates.

**Steps To Reproduce**
Here's a video showing how I reproduced the bug:
https://youtu.be/_z8dEI83bEM

**Version**
v0.10.4.0 Win 10 x64

_Originally posted by @mario31274 in https://github.com/Regalis11/Barotrauma/issues/3616#issuecomment-685391325_

**Comment by Regalis11** [comment]
Thanks for the extra info! It seems that the fix implemented for #3616 also resolved this issue. Note that the fix is not included in the public version yet, but will be in the next patch.
