### ISSUE TITLE
[Dev branch] Crash upon starting game

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#374]
On the current dev branch, this crash happens when starting the game.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/1926066/crashreport.log)

Doesn't seem to happen when starting the dedicated server, only the client.

Built with configuration ReleaseWindows if that matters.

**Comment by juanjp600** [comment]
See https://github.com/Regalis11/Barotrauma/commit/482a0b60d6986b266d4316f984c9a74fcd95fdf2

**Comment by Billsofat** [comment]
That didn't fix it. This time, the game didn't seem to get far enough to make a crash report. I got the standard windows "Barotrauma has stopped working" dialog instead of the game's popup, and no report in the folder.

**Comment by juanjp600** [comment]
Would you mind trying to run DebugWindows through Visual Studio's debugger? I can't seem to replicate this, so I'm a bit in the dark here.

**Comment by Billsofat** [comment]
Seems to be fixed now. When I posted my last comment, I had 482a0b6 but not 71aba76

I built it before you put 71aba76

**Comment by juanjp600** [comment]
Alright, thanks for your help.
