### ISSUE TITLE
Sonar visibility correlated to screen reslolution

### ISSUE THREAD

**Issue by NeyahPeterson** [Regalis11/Barotrauma#3741]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The viewable area while operating the helm is directly correlated to the screen resolution.  This is the inverse of the issue with the amount of view while on a gun.  https://github.com/Regalis11/Barotrauma/issues/3456

**Steps To Reproduce**
1. Set resolution to 4k
1. Operate Helm, activate Sonar, and make sore to zoom fully out
1. Observe viewable area
1. Change resolution to 1080p, observe viewable area
1. Change resolution to 720p, observe viewable area

**Version**
Windows v0.10.4.0

**Additional information**

![HelmViews](https://user-images.githubusercontent.com/5722580/92336342-72abc400-f054-11ea-9b1b-e700c495438e.png)

**Comment by Regalis11** [comment]
Looking at the screenshots, it seems to me they're all showing the exact same area, the "blips" on the screen are just smaller on larger resolutions. Something we should still fix, but I'm marking this as low prio since it shouldn't affect the usability of the sonar.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1d05510f303d255feb3de0ebf17901b6ebc1bc9

**Comment by Rokvach** [comment]
No issues, closing.
