### ISSUE TITLE
Sonar reception is misaligned in docking mode

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3743]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The sonar reception is misaligned when its in `docking mode` (when hatch on your sub is close to hatch on other sub). As you can see on the screenshots below: docking hatch is shown outside of the target sub.

Sounds signatures of engine and reactor are also shown outside the sub you're controlling (also visible on the images).

![image](https://user-images.githubusercontent.com/10875340/92336659-3e132900-f0a3-11ea-8c8a-8c58c1fb498e.png)

![image](https://user-images.githubusercontent.com/10875340/92336714-d4474f00-f0a3-11ea-9bae-9a170354024c.png)

![image](https://user-images.githubusercontent.com/10875340/92336736-0c4e9200-f0a4-11ea-88d3-0e12cfcac197.png)

It gets worse the further you are from the target hatch and gets better as you get close in position to dock.

Looks like the view origin is moved for the docking hatches positions and rest of overlay but not for the sonar reception.

**Steps To Reproduce**
1. Approach main sub with a shuttle.
2. Move close to the hatch on main sub so sonar switches to `docking mode`
3. Notice that view shifts for sonar overlay (hatches, current vehicle outline and icons) but not for sonar reception.
4. Notice that current vehicle's sound signature of engine and reactor is outside the shuttle.
5. Notice that target sub docking hatch is not aligned with sonar reception of the hull.

**Version**
0.10.4.0 (stable)

**Additional information**
Its easier to spot what's wrong when you first move close for the `docking mode` so the zoom is adjusted, then move away and approach again but focus on the transition this time.

Not a fan of all this `docking mode` but maybe this misalignment makes it that bad.

**Comment by Kaillera** [comment]
Using a big sub makes it easier to see this problem especially when you're at the start and trying to move away from the starting station. The level walls on the left right and/or bottom will appear closer to the sub than they should be.

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to repro this with the vanilla subs (tested Kastrull & Remora with their drones and R-29 & Berilia with Venture). Which submarine were you using when you took these screenshots?

**Comment by EtiamNullam** [comment]
Kastrull and Remora have complex shape so it might be a bit harder to notice. 

First screenshot was with my own sub - Blobfish. Second and third screenshots are made with Selkie over Azimuth.

This one is Venture over Berilia on 0.10.5.0 (unstable):
![image](https://user-images.githubusercontent.com/10875340/93355593-89190300-f83e-11ea-99de-1582e04d3b21.png)

**Comment by EtiamNullam** [comment]
Not sure but I feel like its much worse after latest unstable patch. Maybe due to fix to #3741?
![image](https://user-images.githubusercontent.com/10875340/93504698-21d08100-f91a-11ea-859b-b1565b478d65.png)

**Comment by EtiamNullam** [comment]
I don't understand why this issue got closed. It's still a problem in version `0.12.0.3`.
