### ISSUE TITLE
Multiplayer - Wire disappears/drops when getting shocked from attaching wire from one item to another item

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3744]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you are trying to attach a wire from one item to another item and you get shocked from the second item in multiplayer, the wire disappears from the inventory and your character will no longer be in node placing mode. The wire will reappear and drop from the player if you unequip the screwdriver. It makes it harder for players to wire items successfully to two shockable items.

**Version**
~0.10.502

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/59c946634b2632cd2c0eb863014d82a5d295df89

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
