### ISSUE TITLE
You can get shocked for rewiring items that aren't on

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3745]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can get shocked for rewiring items that aren't on, or power is not actively running in/out of them them.

**Version**
~0.10.502

**Comment by Regalis11** [comment]
I wouldn't necessarily consider this a bug, you get electrocuted when you rewire _powered_ devices (basically anything connected to a powered grid), even if the device is not running.

**Comment by Regalis11** [comment]
Also now that I think about it, if the players didn't get shocked when the device is off, it would pretty much defeat the purpose of the feature: you could always just turn off the device before rewiring. Closing

**Comment by Tsunder** [comment]
Logically, the power for electrocuting players has come from somewhere, I'm not sure it makes sense to get shocked (potentially repeatedly) from an unpowered device.

I think depowering a device to make rewiring safe(r) is a interesting interaction/tradeoff, as a unpowered device isn't in use and already punishes, especially for critical power systems like, batteries, reactors.
