### ISSUE TITLE
Failing to repair oxygen generator doesn't stun player

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3746]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Failing to repair oxygen generator doesn't stun player

**Version**
~0.10.502

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0194ff3b2c3e504e2fb9f29660313fcda762de7a

**Comment by Rokvach** [comment]
No issues, closing.
