### ISSUE TITLE
Bots - Shutdown Reactor order does not disable autonomous action of Power up Reactor.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3748]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots with autonomous action of powering on reactor will keep trying to turn reactor on when a bot walks away from the reactor with shutdown reactor order. This usually ends up with the autonomous bot Manning the reactor on even with an active shutdown order by another bot.

**Version**
~0.10.502

**Comment by ekqvist** [comment]
Can you confirm that this is still an issue for you on the latest Unstable? If so, can you provide additional steps to reproduce the issue? I have tried to reproduce this with two engineers on board, but as long as one of them has the shutdown order active the other one seems to ignore the reactor.

**Comment by Rokvach** [comment]
I wasn't able to reproduce this issue either yesterday while I was testing something else which required the reactor to be off, it did stay off and none of the bots touched it (played with 16) even when the bot who was ordered to shut it down wasn't attending to it.

**Comment by Kaillera** [comment]
Haven't seen this happen again in 0.10.503

**Comment by itchyOwl** [comment]
This was addressed in Regalis11/Barotrauma-development@2bfebb8 (20th August), which is included in the current unstable. So it should be fixed.

**Comment by Rokvach** [comment]
Working correctly, closing.
