### ISSUE TITLE
Handcuffing the outpost reactor guy and then releasing him, causes him to no longer fuel the outpost.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3749]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Handcuffing the outpost reactor guy, pulling him out of reactor room and then releasing him, causes him to no longer fuel the outpost.
Well actually it's not just handcuffing. It's just the easiest way. I've seen other particular interruptions just stops him from manning the reactor completely.

**Version**
~0.10.502

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
