### ISSUE TITLE
Thalamus Veins are pickable/rewireable

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3753]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Thalamus Vein cannot fit inside Toolboxes.

**Version**
~0.10.502

**Comment by Regalis11** [comment]
Is there a way to get a thalamus vein into your inventory in the vanilla game? If so, that's a bug

**Comment by Kaillera** [comment]
Yeah, usually you guys wired it up to two items in a wreck. You just pluck both end and put it into your inventory.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4edc7f7ee8cb7cc80f61ccde3576dd8b89d12764

**Comment by Rokvach** [comment]
No issues, closing.
