### ISSUE TITLE
3 Ores that feel like they deconstruct for so little

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3756]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I feel like Aragonite, Chalcopyrite, and Bornite gives too little of their materials. Calcium is pretty hard to get for instance.

**Version**
~0.10.502

**Comment by danielasteljoki** [comment]
Added a bit more material to deconstruct recipes for abovementioned minerals. (56250ec & 7c18f8a)

**Comment by Rokvach** [comment]
No issues, closing.
