### ISSUE TITLE
disablecrewai does not require cheats enabled

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3758]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
disablecrewai does not require cheats enabled, but enablecrewai does.

**Version**
0.10.503

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/88e337c2d566e4bb8099bba5ebe4ceed284deb28

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
