### ISSUE TITLE
Found basic fix to crash on startup

### ISSUE THREAD

**Issue by Keef25** [Regalis11/Barotrauma#3761]
Go to Library on steam, right click Barotrauma, Manage> Local Game Files Delete Barotruama File, uninstall, reinstall.

**Comment by Keef25** [comment]
Hopefully if others have problems like this you can tell them this as it helped me

**Comment by Regalis11** [comment]
Thank you for the tip, I added it to our Trello card about this issue https://trello.com/c/5RL4AQ8K/314-workaround-included-game-crashing-on-startup-after-update.
