### ISSUE TITLE
Multiplayer - Invalid docking port network event (can't dock to null)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3762]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Submarine redocked to station it left out of.

Error:
Invalid docking port network event (can't dock to null)

All of a sudden port keeps filling with glitchy water, Problem goes away when going to other stations.
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5184847/Multiplayer.zip)

**Version**
~0.10.503

**Additional information**
Saw this before in 0.10.4 as well.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f95ff3fd6f2dee24960d25b06e9955c9cdb11ab8

**Comment by Rokvach** [comment]
No sightings of this happening after extensive play, seems to be working correctly. Closing.

**Comment by MexMass** [comment]
I just had this multiple times this session.
