### ISSUE TITLE
[0.10.503] Alien Room Door Puzzle Broken

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3763]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing in my own dedicated server here. I found this puzzle to no longer react to the buttons being pushed.
![Capture](https://user-images.githubusercontent.com/5086682/92416152-19ae5f80-f12a-11ea-835c-c2543a2cbf7b.PNG)

[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5184886/Multiplayer.zip)
Some ruin not too far away from the start of the level.

**Version**
0.10.503

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fe2b229befe044ebba36fe7d99f949ad4081102

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
