### ISSUE TITLE
Restrict ammo types to be used in loaders

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#3766]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a feature request.
Allow in the editor to restrict what ammo can be loaded in the Depth Charge , Rail gun & coil gun loaders. You can create more interesting designs where you force the players to only use certain types of ammo, depending on what gun. Some DC loaders could for example only use Decoys an some railgun loaders could only use nuclear shells. It could add an extra level of difficulty to the submarine that is in use.

**Comment by ezjamsen** [comment]
Due to possible upcoming changes to guns, let's shelf this idea for now.
