### ISSUE TITLE
[0.10.503] Players are given a new character when spawning into outposts after the round already started, when they have a previous character already

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3767]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players that join into servers are given a new character when spawning into outposts with the new respawn feature after the round already has started, and when they already have a previous character already. Old character gets replaced completely.

**Steps To Reproduce**
1. Client A - Have a character on save file, do anything with it. Leave the server.
2. Client B - Enter/Reenter outpost.
3. Client A - Joins server while round is at outpost. After the respawn timer, they'll spawn in with a new character entirely instead of old character.

**Version**
~0.10.503

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a26bccd9cfd9f85debcca26d1cd90894b6bde335

**Comment by Rokvach** [comment]
Working correctly, closing.

**Comment by Kaillera** [comment]
This one needs reopening.

Apparently players are given a fresh skill level slate every time they spawn in.

**Comment by Kaillera** [comment]
Another Problem:

When a player leaves the game in the Outpost level and becomes Brain Dead, if the player comes back they will get an entirely new character with the old corpse still in game.

**Comment by Regalis11** [comment]
@Kaillera  What do you mean by becoming braindead?

**Comment by Kaillera** [comment]
Simply leaving the game and dying to killdisconnect

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/34b7149e8c3b52d9ab7dca7e13206e8290159281 and https://github.com/Regalis11/Barotrauma-development/commit/d69cd4c1384f812d9547b1ad695085a238728c34

**Comment by Kaillera** [comment]
Working since the first 0.10.5.0 build yesturday.

**Comment by Rokvach** [comment]
Closing
