### ISSUE TITLE
multi_bug_report, solo_freediving

### ISSUE THREAD

**Issue by Telariust** [Regalis11/Barotrauma#3769]
Hi, developers!  Thx, great game! 

**Version**
Barotrauma v0.10.4.0(ReleaseWindows, branch release, revision 20132d25fb)
MultiBagReport, solo_freediving
googletranslate (sry if fail)

**general**
 - beginning of the game; the dock is the only one; we take any peaceful task to deliver to the location "natural landscape"; we sail - there is no dock, there is nowhere to moor; here everyone starts dull - WHAT TO DO NEXT? Having sailed around all the surroundings, having spent all the fuel, from despair we open the map and press back to the starting dock; and lo and behold - the quest is completed (or not, because in 50% of the cases it was the delivery of medicines and the team ate half while you were trying to figure out what needs to be done); a completely unfriendly start for beginners; it is important to understand and fix it;
 - Dugong, a hidden room in the bow compartment (below, under the armory), sliders often get there and interfere with the horizontal movement of the boat; there was a case when two sliders got stuck and the boat had a negative stroke! I did not yet know and was really perplexed about what was happening;
 - Dugong, a mechanic on the auto-action "to fix mechanics" gets hung up on the aft ballast pump, forgetting about the repair of other systems, consumes all oxygen cylinders available on the submarine, can drown, therefore, auto repair of fur systems in Dugong is impossible, you have to repair periodically yourself;
 - switch to another submarine, leave the point, call up the menu, load the replay - we are again on the old submarine; at the same time, submarine improvements will be displayed and purchased for the new submarine; to get rid of you need to swim to any other dock;
 - Siphon-2, in the dock does not know how to use the dock's energy, always only from the reactor;
 - the shells of the railgun on the rack are displayed from right to left, and vice versa in aiming mode;
 - a canister made of oxygen / ignited explodes at a depth, not withstanding high pressure (is that intended?);
 - it is impossible to pick up a spacesuit, you cannot bring a trophy spacesuit from a sunken ship, unlike boxes and shells;
 - there is a simple box, there is a box for chemistry, there is a box for explosives .. there is no box for nuclear materials (this is a violation of safety regulations!);
 - it is desirable that the signal of the end of oxygen in the cylinder sounded also after the end of oxygen (10 sec or infinitely with an empty cylinder);

**fabricator/deconstructor**
 - there are no explosives in the materials of the depth charge;
 - the materials of the nuclear deep bait contain explosives (this is a bait, it does not explode);
 - the diver's knife is made of Fe, although in theory it should be of steel ingot;
 - usually "cyanide" means potassium cyanide, but the developer seems to be a fan of sodium cyanide?)
 - C-4 and C-4 + cannot be disassembled in the deconstructor;
 - shockproof fibers cannot be disassembled in a deconstructor (titanium + plastic, this makes titanium scarce);
 - you can disassemble the cartridge for submachine gun (used or whole) in a deconstructor and get cartridges for submachine gun, but they cannot be used or sold;
 - the antidote for morbuzine requires 1/4 of the materials and is synthesized in 1/4 of the syringe, while the antidote for parasites (calixanide) requires 1/4 of the material and is synthesized for a full syringe (was that intended?);
 - adrenaline has no effect when used (and, for example, opium - it has, is dishonest!);

**trade**
 - when buying a swim bladder, it is delivered on board without a box;
 - when buying plastic, it is delivered on board in an explosive box (what a dangerous plastic!);
 - no merchant in the game buys the submachine gun cartridge;
 - the price of the antidote of the paralyzer is much less than the price of the paralyzer itself, we buy the antidote, disassemble it, sell the poison and stabilocin;
 - in the store, the sorting button "other planets" hints that sulfur and oxygen are alien, and thunderstorm and dementonite and ignite - quite earthly minerals;
 - if you hold a box with items in your hands, then when communicating with a merchant, items from the box are visible in the list but they cannot be sold;

**best_trading_ ways_to earn_Sept_2020**
(balance correction may be required)
  - top1: buy x1_elocene_eggs (~ 600 $) + x4_stabilocin (~ 50 $) + x4_antibiotics (~ 50 $) -> synthesize x4_calixanide (~ 700 $) and sell (2800 $ -1000 $ = ~ 1800 $ profit);
  - top2: buy UEX explosives (~ $ 80) and a screwdriver / scrap / wrench (~ $ 10) -> synthesize a frag grenade and sell ($ 300 -90 $ = ~ $ 210 profit);
  - top3: buy antidote_paralyzer (~ $ 50) -> disassemble into a paralyzer (~ $ 200 profit) and stabilocin (~ $ 50) and sell (I suppose it will be fixed);

**local_RU**
Использование синонимов в названиях предметов приводит к неправильной группировке при сортировке списка по алфавиту.
Также такие предметы проблематично находить через поиск.
 - rename: обойма револьвера -> патрон для револьвера (как патрон для дробовика, это не обойма а один патрон); 
 - rename: противоядие для морбузина -> антидот для морбузина (как остальные антидоты, противоядие/антидот);
 - rename: беспроводной компонент -> компонент "беспроводной";
 - rename: пластическое волокно -> эластичный бинт (как бинт, это не волокно а улучшенный бинт);
 - rename: снаряд рельсотрона -> заряд рельсотрона (снаряд/заряд);
 - ~~rename: физикориевый стержень -> осколок физикория (как осколок кислородита или сернита);~~
 - ~~rename: грозовиевый стержень -> осколок грозовия (как осколок кислородита или сернита);~~
 - ~~rename: воспламенитовый стержень -> осколок воспламенита (как осколок кислородита или сернита);~~
 - rename: UEX -> взрывчатка UEX;
 - rename: блок С-4 -> взрывчатка С-4;
 - rename: блок С-4+ -> взрывчатка С-4+;
 - rename: соединение N -> взрывчатка соединение N
 - rename: нестабильное соединение N -> взрывчатка нестабильное соединение N
 - rename: топливный бак сварочного аппарата -> топливный баллон (бак/баллон/канистра);
 - rename: баллон с кислородитом -> кислородный баллон из кислородита;
 - rename: канистра топлива из воспламенита -> топливный баллон из воспламенита;
 - rename: плазменный резак -> плазменный аппарат (как сварочный аппарат);
 - rename: сплав титана и алюминия -> слиток из титана и алюминия (как стальный слиток);
При отображении списка название предметов усекается. 
Поэтому предлагаю в названиях поменять местами порядок прилагательное-существительное на обратный.
Тоесть не "грозовиевый топливный стержень", а "стержень топливный грозовиевый". 
Также предлагаю ко всем ядам добавить слово яд в названии, тоесть "морбузин"->"яд морбузин".

**Comment by Regalis11** [comment]
Thank you for a very extensive report! I'll create new bug tickets about the individual issues because it makes it easier for us to keep track of which bugs have been fixed. However, some of these are known issues we already have tickets for, and some are intentional.

>beginning of the game; the dock is the only one; we take any peaceful task to deliver to the location "natural landscape"; we sail - there is no dock, there is nowhere to moor; here everyone starts dull - WHAT TO DO NEXT?

I completely agree: the way natural formations work at the moment is very confusing, and we're planning on making it a little more intuitive in future versions.

>Dugong, a hidden room in the bow compartment (below, under the armory)
>Dugong, a mechanic on the auto-action "to fix mechanics" gets hung up on the aft ballast pump
>switch to another submarine, leave the point, call up the menu
>Siphon-2, in the dock does not know how to use the dock's energy
>shockproof fibers cannot be disassembled in a deconstructor
>the antidote for morbuzine requires 1/4 of the materials and is synthesized in 1/4 of the syringe, while the antidote for parasites (calixanide) requires 1/4 of the material and is synthesized for a full syringe

Known issues we have existing tickets for

>the shells of the railgun on the rack are displayed from right to left, and vice versa in aiming mode;

I'd consider this so low prio that we shouldn't fix it.

>a canister made of oxygen / ignited explodes at a depth, not withstanding high pressure (is that intended?);

This isn't intentional, and I wasn't able to reproduce this. The items do get removed if they end up very deep in the level (way deeper than what you could possibly reach on any sub), I wonder if that was what happened?

>it is impossible to pick up a spacesuit, you cannot bring a trophy spacesuit from a sunken ship, unlike boxes and shells;

Intentional

>there is no box for nuclear materials

This is also intentional; you rarely purchase so many fuel rods that they'd warrant an entirely new container. Also, unused uranium fuel rods are only mildly radioactive and can be handled without any shielding even in real life. https://www.google.com/search?q=are+nuclear+fuel+rods+radioactive

>it is desirable that the signal of the end of oxygen in the cylinder sounded also after the end of oxygen

That's a good idea, I'll create a new ticket.

>there are no explosives in the materials of the depth charge;

Intentional, the depth charges are not explosive by themselves (although you can put explosives inside them).

>the materials of the nuclear deep bait contain explosives (this is a bait, it does not explode);

The nuclear depth charges are supposed to explode, however that's bugged in the current version (fix coming up in the next patch).

>the diver's knife is made of Fe, although in theory it should be of steel ingot;

Good point, I'll create a new ticket.

>usually "cyanide" means potassium cyanide, but the developer seems to be a fan of sodium cyanide?)

Not necessarily, sodium cyanide is apparently used in fishing, to synthesize other chemicals, and also to kill people, so I think it's an appropriate choice in this case.

>in the store, the sorting button "other planets" hints that sulfur and oxygen are alien, and thunderstorm and dementonite and ignite - quite earthly minerals;

Sulfurite shards and oxygenite shards are not intended to be sulfur and oxygen, but alien minerals/materials that _mostly_ consist of sulfur and oxygen.

>rename: физикориевый стержень -> осколок физикория (как осколок кислородита или сернита);
>rename: грозовиевый стержень -> осколок грозовия (как осколок кислородита или сернита);
>rename: воспламенитовый стержень -> осколок воспламенита (как осколок кислородита или сернита);

If google translate serves me right, I assume you're suggesting renaming the fuel rods fabricated from alien materials as "shards". I don't think we should do this, because they are rods made of the alien material, not shards.
