### ISSUE TITLE
Attempting to repair a completely broken electrical device will never electrocute you

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3771]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You will never get shocked when you fail a skill check while repairing a completely broken electrical device. I think as long as it has power connected it should hurt you when you fail the skill check.

**Steps To Reproduce**
1. Try to repair completely broken junction box.
2. Notice you will never get shocked no matter the skill you have.

**Version**
0.10.4.0 (stable), 0.10.503.0 (unstable)

**Additional information**
I think it would be best fix this issue by implementing the approach I suggested in #3770.

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
