### ISSUE TITLE
Misc balance issues

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3773]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Miscellaneous issues relating to item prices and crafting recipes, collected from here:
https://github.com/Regalis11/Barotrauma/issues/3769

- [x] buy x1_elocene_eggs ( 600 $) + x4_stabilocin ( 50 $) + x4_antibiotics (~ 50 $) -> synthesize x4_calixanide ( 700 $) and sell (2800 $ -1000 $ =  1800 $ profit);
- [x] buy UEX explosives ( $ 80) and a screwdriver / scrap / wrench ( $ 10) -> synthesize a frag grenade and sell ($ 300 -90 $ =  $ 210 profit);
- [x] buy antidote_paralyzer ( $ 50) -> disassemble into a paralyzer ( $ 200 profit) and stabilocin ( $ 50) and sell (I suppose it will be fixed);
- [x] the antidote for morbuzine requires 1/4 of the materials and is synthesized in 1/4 of the syringe, while the antidote for parasites (calixanide) requires 1/4 of the material and is synthesized for a full syringe
- [x] the price of the antidote of the paralyzer is much less than the price of the paralyzer itself, we buy the antidote, disassemble it, sell the poison and stabilocin;

**Comment by danielasteljoki** [comment]
Fixed these along with some other antidote balance issues in c4cf0e2.

**Comment by Rokvach** [comment]
No issues, closing.
