### ISSUE TITLE
[Request] Shelf for complex component system

### ISSUE THREAD

**Issue by K7PPA** [Regalis11/Barotrauma#3775]
**Description**
The idea is that there will be shelf with node-based system when you put one component in it and wire with other ones that you put in, like a basic wiring but in more efficient way where you don't limit yourself with the space of your submarine/shuttle/etc. 

My acquaintance made a shuttle with a complex component system that eats the whole space in shuttle. And for example if you want specific shelf to act for a specific thing in the wire system then you can make it without getting confused with a lot of wires (you will deal with it, but it'll be slightly easier to understand.

_It's quite easy to operate inside the shelf with node-based type of stuff. For example like node-based material builder in UE4, blender, Houdini, etc. (dropping an image for you to understand what i mean by that)_
![image](https://user-images.githubusercontent.com/70966462/92500758-717ac280-f21f-11ea-8d16-106283409516.png)

**Additional information**
It will be awesome if you made it! :)

**Comment by Saevon** [comment]
I believe this is identical to my suggestion / design #4721 for "Circuit Enclosures"
