### ISSUE TITLE
[0.10.503] Multiplayer(?) - Cannot see Crew Members gain Helm

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3777]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot see Crew Members gain Helm. Not sure if it's specific to just bots and/or multiplayer.

**Version**
0.10.503

**Comment by Kaillera** [comment]
Hmm... I had this one bot driving an entire round stuck at 20 helm for the whole thing.
Another round after, I see him at 37 with no messages of leveling up.

**Comment by Kaillera** [comment]
Okay so helm level is not updating in the crew page.

Here is the number when he was piloting from start to finish. He's still at 37
![Capture](https://user-images.githubusercontent.com/5086682/92536311-569c5400-f207-11ea-869b-03124da780a1.PNG)

It's now at 45 after entering outpost:
![Capture](https://user-images.githubusercontent.com/5086682/92536380-84819880-f207-11ea-9e0f-6c673884659a.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a34ae4deff6bab812c7a6683286328b739fc9a6f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
