### ISSUE TITLE
[0.10.503] Handcuffing the outpost reactor guy + upgrade guy, turning off the outpost reactor, and then releasing them, causes them to no longer keep the reactor powered on.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3778]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Handcuffing the outpost reactor guy + upgrade guy, turning off the outpost reactor, and then releasing them, causes them to no longer keep the reactor powered on.

**Version**
0.10.503

**Additional Information**
Even if I pull and drop the fuel rod on to the floor, they don't seem to be concerned about having fuel in reactor either in that state.

Their AI seems to reset and do their properly again if they ended up doing something else... like finding safety from suffocation by their lack of power.

**Comment by itchyOwl** [comment]
Is this the same issue as #3749?

**Comment by Kaillera** [comment]
Not quite, this was after a change from 0.10.503

**Comment by itchyOwl** [comment]
Ok, so apparently the previous fix didn't fix everything.

**Comment by Xeavas** [comment]
@itchyOwl 
[0.1100.0.5] - I found this while testing, unsure if its a separate issue so I'll put it here, but can be done by just clicking the power off button in the reactor UI.

- Subeditor a id card into dugong, with the tag `id_reactor` , save.
- Start campaign with said sub and equip it
- Access outpost reactor and power it off (without taking the fuel rod out)

Result : They can't turn the reactor back on.

**Comment by itchyOwl** [comment]
So, did you insert an id card inside the sub with the tag id_reactor and then equpped it. Then you entered an outpost and powered the reactor off and the bots fail to power it back on? Correct?

**Comment by Xeavas** [comment]
Yes, the id card with `id_reactor` was edited in using the sub-editor, then rest is done in campaign outpost.

**Comment by itchyOwl** [comment]
It was the same issue. The bots just reacted like they would if they were on the same team: respect the player made decision to unpower the reactor. Fixed in Regalis11/Barotrauma-development@118e5b3. Thanks for the steps that were easy to repro!

**Comment by Rokvach** [comment]
No issues, closing.
