### ISSUE TITLE
Battery Output and Deterioration

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#3781]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Battery continues to output power without draining capacity when deterioration condition is at 0%.  

**Steps To Reproduce**
Simple circuit: Battery (out) -> Junction Box -> power consumer (oxygen generator for my test).
Let battery deteriorate to the point of breaking.  (I accelerated this by upping deterioration factor and lowering max time for deterioration).
Broken battery will still continue to provide power and it no longer drains capacity.

**Version**
Stable
Windows 10

**Additional information**
Attaching a testing file with this being observed.
[batt-test.zip](https://github.com/Regalis11/Barotrauma/files/5192561/batt-test.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ccc391fe4e8ae694df6d20233ecd06a799b534d

**Comment by Rokvach** [comment]
No issues, closing.
