### ISSUE TITLE
Can't interact with sonar map when there is popup message visible

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3784]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Its not possible to interact with sonar map in navigation terminal (set target for autopilot or heading for manual steering) when there is visible popup on screen - for example traitor or mission info message. 

**Steps To Reproduce**
1. Start mission.
2. Quickly go to navigation terminal.
3. Try clicking on the sonar map to select new target/heading.
4. Notice that you can't do that until you dismiss the popup message (or it disappears on its own).

**Version**
0.10.4.0 (stable) - 0.10.504.0 (unstable)

**Additional information**
~I feel like its regression from stable, will update soon.~
EDIT: Its exactly the same in stable.

**Comment by EtiamNullam** [comment]
I agree its not a high priority bug, but that does not make it a `Feature request`. 

I suspect you only looked at it through the prism of `Steps To Reproduce` I suggested - Its the quickest way to reproduce the bug but its not as annoying because its at the start of the match so the sub is not moving.

Consider this scenario:
- Mission with traitors.
- Captain is manually controlling the high speed sub.
- Security executes the traitor.
- Suddenly captain gets a bunch of notifications that he become the traitor and explaining what he has to do.
- Captain loses all control of the sub (other than possibly turning off the reactor that would make him suspicious) until he manages to skip (or wait) through all the popups.
- He crashes the sub possibly dying or bringing unwanted attention to him.

In my opinion its a bug especially because it affects only guy at the helm - You can still most likely operate other devices, walk, shoot, etc. I suggest that you reconsider the label.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4b7f1d4570ca55a0fc12f60e83d749836f9e714d

**Comment by Xeavas** [comment]
[0.1200.0.2] - Tested and working correctly. 👍

**Comment by Rokvach** [comment]
Closing.
