### ISSUE TITLE
Position of items is not updated when inside toolbox in player inventory

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3785]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Position of items is not updated when inside toolbox in player inventory. For example `sonar beacon` will show position and emit sound from the last position you interacted with `toolbox`. Active `flare` or `handheld sonar` will also update sound origin only when you touch the `toolbox` - also visible on sonar.

**Steps To Reproduce**
1. Get `sonar beacon`.
2. Enable it and insert a battery.
3. Place it in a `toolbox`.
4. Keep `toolbox` in inventory but not in hands.
5. Notice that sound origin and marker on sonar of  `sonar beacon` is locked to the position of last interaction with containing `toolbox`.
6. Notice that position will get updated only when you interact with `toolbox` that contain it - for example equip it, or put more items inside.

**Version**
0.10.4.0 - 0.10.504.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a058904326be9a1f75913a8acad54d13604275d

**Comment by EtiamNullam** [comment]
Seems like it works correctly now. Tested with sonar, flare and beacon.

**Comment by Rokvach** [comment]
Closing.
