### ISSUE TITLE
Sonar beacon is active even after it ran out of energy

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3786]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sonar beacon is active even after it ran out of energy until you interact with it.

**Steps To Reproduce**
1. Get `sonar beacon` with `battery cell` and some charge in it.
2. Activate `sonar beacon`.
3. Unequip `sonar beacon`.
6. Notice its still active and visible on sonar even after `battery cell` is completely empty.

**Version**
0.10.504.0

**Additional information**
Best way to get battery cell with a small amount of power for quick test:
1. Drain `battery cell` completely with stun baton and a "volunteer".
2. Charge `battery cell` for a second in charger.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce74cfae69c86f4610a044ca5bf9ab30335276c0

**Comment by Rokvach** [comment]
No issues,  closing.
