### ISSUE TITLE
Single sonar ping allows you to see clearly near volcano

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3787]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sonar ping then listen on passive allows to see through thermal vents.

**Steps To Reproduce**
1. Find a volcano.
2. Send single ping.
3. Quickly switch to passive.
4. Notice you can see everything clearly without any noise.

**Version**
0.10.4.0 - 0.10.504.0

**Additional information**
A bit similar to #2098

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ac1bdcecd6ecfeed9daf6ff57f7ce781aa0fa06

**Comment by Rokvach** [comment]
No issues, closing.
