### ISSUE TITLE
[0.10.504] Killing yourself as a traitor triggers the notification

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3788]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Killing yourself as a traitor triggers the notification. It might be quite confusing.

**Steps To Reproduce**
1. Become traitor.
2. Commit suicide.
3. Notice you receive killed by traitor notification.

**Version**
0.10.504.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2b111a347428be4240b1538b94187a97ca5bc307

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
