### ISSUE TITLE
You can still see icons leading to NPC's even if that NPC is dead

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3791]
Only a torso left but still the mission icon points at the NPC
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bf919368-76dc-4dd7-8ba6-4d48edbed672)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/110a33b5f504377db80c833bb5b3cce4ec9861bf

**Comment by Rokvach** [comment]
No issues, closing.
