### ISSUE TITLE
unknown object header 254

### ISSUE THREAD

**Issue by lokirulez** [Regalis11/Barotrauma#3792]
it asked me to send this - i was just shooting from drowning boat. alone  in multiplayer

[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5203467/crashreport_object.log)
[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/5203470/servercrashreport.log)

![ruin](https://user-images.githubusercontent.com/34145054/92767518-df4df800-f39f-11ea-9584-0675e678a899.png)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1815
