### ISSUE TITLE
Outpost Security does not have "id_outpostsecurity" on their ID card

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3793]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost Security does not have "id_outpostsecurity" on their ID card.

**Version**
0.10.504

**Comment by Regalis11** [comment]
Looks like we had a duplicate ticket about this in our private repo (https://github.com/Regalis11/Barotrauma-development/issues/2187) that we've since closed. Fix coming up in the next update (and already included in the latest unstable build).
