### ISSUE TITLE
Changes to the spawn point in sub editor are not saved

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3794]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Changes to the spawn point in the sub editor are not saved until you press `ENTER`

**Steps To Reproduce**
1. Launch sub editor.
2. Create spawn point.
3. Click on spawn point to open settings.
4. Change anything but don't touch the combo box.
5. Close settings by clicking somewhere else.
6. Click on spawn point again.
7. Notice that options were not saved.

**Version**
0.10.4.0

**Additional information**
I know there was similar issue in sub editor with all other objects.

**Comment by Regalis11** [comment]
Looks like the fields only updated if you pressed enter. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ffe75e70778a50c89c6acdd2dcbc06b6f7fbdea

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
