### ISSUE TITLE
Prevent selling items in sub inventory of equipped clothing

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3795]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items in sub inventory of equipped clothing shows up in Merchant Sell tab (ex. Medic's Fatigue)

**Version**
0.10.504

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@0b619da.

Items contained directly inside equipment in Head, OuterClotes, or Headset slot was already prevented, but now the behavior should be more consistent for all equipped equipment. It should now also be impossible to sell items in subinventories of the contained items, which could previously be technically possible for some modded items.

The selling logic has been discussed internally recently and it would be nice to improve it futher to make it more practical and more consistent.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
