### ISSUE TITLE
Hotkey to close mission dialogue prompts?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3796]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was wondering if you guys can add a hotkey to allow pressing E or Right Click when you pick up missions/missions completed in order to skip those mission prompts? Having to click those tiny arrows/big arrows can be a chore.

**Version**
~0.10.504

**Comment by ezjamsen** [comment]
Let's allow players to dismiss all dismissible dialog interfaces by pressing E, with a 0.5 - 1 second delay to prevent accidental dismissal.

**Comment by Kaillera** [comment]
Agree

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/95d02cf7963bf23deff08ecee4bbc438df32ecda

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
