### ISSUE TITLE
Bots are unable to kill enemies with coilgun when there are no players near or watching the submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3797]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've noticed that when I have to swim away from the submarine, and there's no players inside or near the submarine. Bots will infinitely shoot at targets that gets close to the submarine, but they will never kill them.

**Steps To Reproduce**
1. Swim about 50m-200m away from the submarine with a character.
2. Freecam and spawn some enemies not too far away from the submarine that will get into range of your submarine's gun.
3. Quickly go back to your character and listen on comms.
4. Freecam back to the submarine or switch to a character inside/near the submarine. They'll be able to kill it then.

**Version**
~0.10.504

**Comment by itchyOwl** [comment]
I guess this was fixed? Was it related to simple physics and/or disabling the bots?
