### ISSUE TITLE
[0.10.505] Seed Bag/Planter Box/Fertilizer cannot be placed into cabinets

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3799]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seed Bag/Planter Box/Fertilizer cannot be placed into cabinets.

**Version**
0.10.505

**Additional Information**
Found a couple of planter box just sitting infront of wrecked medical cabinets inside wrecks because they don't fit in there.

**Comment by danielasteljoki** [comment]
Fixed in fba784a.

**Comment by Rokvach** [comment]
No issues, closing.
