### ISSUE TITLE
[0.10.505] Multiplayer - Paint/Ethanol in Sprayer hardly runs out

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3801]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Paint/Ethanol in Sprayer hardly runs out in multiplayer. Both ethanol and paint were spawned in. Sprayer was crafted.

**Version**
0.10.505

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d34fdc13f6a74e74f78b9c72249828a716e4dee2

**Comment by Rokvach** [comment]
No issues, closing.
