### ISSUE TITLE
[0.10.505] You can still water dead vines

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3802]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can still water dead vines.

**Version**
0.10.505

**Comment by ezjamsen** [comment]
Agreed this is not ideal. Once a plant is dead, let's not allow it to be watered more.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fa76167e5eaf9b124d163ba81d9f8ee04511e851

**Comment by Rokvach** [comment]
No issues, closing.
