### ISSUE TITLE
[0.10.505] Seed will overflow?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3803]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just a prediction, but I think the amount of seeds on the floor should be capped per plant so that there isn't just hundreds of them at some point. If people don't pick them up, it's probably safe to say they won't be used and won't need more.

**Version**
0.10.505

**Comment by Kaillera** [comment]
I am thinking it's probably better to just keep the seeds to only come from deconstructed fruits.

**Comment by ezjamsen** [comment]
Seeds are now only obtained via fruit deconstruction

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Kaillera** [comment]
Was playing in my dedicated server today and I was growing a Salt Vine. I still keep getting seeds from it.
