### ISSUE TITLE
[0.10.505] Watering Can water comes from where?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3804]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Watering Can has infinite water. Should probably be refilled by submerging yourself in water when the item is equipped and being aimed.

**Version**
0.10.505

**Comment by Flotilla-zz** [comment]
I agree that the watering can being bottomless is strange, but submerging yourself in the ballasts to refill a watering can (with salt water?) sounds just about as strange. Shouldn't there be a sink or some other, more reasonable fixture to refill water from? That's getting into feature requests, but I wanted to give my two cents on your suggested fix.

**Comment by EtiamNullam** [comment]
Its better to assume water is accessible everywhere on a nuclear submarine, just like you don't have to gather water to craft saline. I think we need no more complexity here. The last thing we need is sink that is only used for watering can.

**Comment by Flotilla-zz** [comment]
There's no complexity at all in its current state, to the point where it's being reported as aberrant behavior by people like OP. Fabrication recipes are naturally going to be more simple than their IRL counterparts, but a watering can with infinite water sticks out like a sore thumb in a game with oxygen depletion, welding fuel depletion, battery depletion, etc.

**Comment by ezjamsen** [comment]
While it is inconsistent with the real world to have an endless watering can, I think we can suspend disbelief in this case given that the alternative does not introduce interesting or fun interactions for players. Therefore our watering can is actually an advanced futuristic model which condenses moisture right out of the atmosphere.
