### ISSUE TITLE
[0.10.505] Planter boxes default to 100% water saturation when planting a new seed

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#3806]
**Description**
After uprooting a dead plant and seeding another one, the planter box will default to 100% water saturation regardless of the amount of water left in the planter during uprooting.

**Version**
0.10.505

**Comment by 3e849f2e5c** [comment]
This is actually intended as the planter doesn't hold any water, the progress bar when watering is actually an indicator of the plants health rather than the planters water level.
