### ISSUE TITLE
[0.10.505] Heavily painted/dirtied surfaces display grid pattern

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#3807]
**Description**
Surfaces which have been thoroughly painted over/dirtied display an unsightly grid pattern, instead of a "uniform" coating. See:
![tile1](https://user-images.githubusercontent.com/3611705/92960537-c8f57a00-f43b-11ea-85d1-58ed4f6bd413.png)
![tile2](https://user-images.githubusercontent.com/3611705/92960967-7b2d4180-f43c-11ea-9036-31793c4189a9.png)

**Version**
0.10.505

**Comment by Regalis11** [comment]
Improved in https://github.com/Regalis11/Barotrauma-development/commit/ac1ad8aa14084f0b86acb702e1d0a2155af6e85f

**Comment by Rokvach** [comment]
Its really hard to draw things with the new offset, on the screenshot the line is a single grid column width, but it blends too much that it looks like it covers multiple columns @Regalis11 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5be8936d-4c48-4259-af92-d309aa760111)

**Comment by Rokvach** [comment]
Closing as the grid isn't displayed anymore, otherwise needs some slight improvements which can be handled outside of this ticket. Closing.
