### ISSUE TITLE
[0.10.505] Sprayer SFX are not synced in multiplayer

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#3809]
**Description**
Players in multiplayer sessions will not hear other players' sprayers.

**Version**
0.10.505

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/163949a34179eae5894599d768d95321e5398229

**Comment by Rokvach** [comment]
No issues, closing.
