### ISSUE TITLE
Optional gui for dedicated server

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#381]
I find the hosting gui within the client to be very useful, it makes it very quick and easy to change server settings, set sub, manage characters, talk with dead characters, etc.

The dedicated server is nice for hosting without the game open, but unless I'm missing something, I can't seem to do everything I can as easily with the gui with commands and giving permissions to my character.

I'm suggesting a simple, clean gui that you can toggle for the dedicated server. It would have a chat where you can talk either as a host or a dead character, a sub list, a menu similar to the server settings menu, player management, etc. Pretty much what you have ingame but a seperate window.

I understand the command prompt is useful for certain purposes too, so the gui would be optional.

Perhaps this could fit in with #380 somehow?

**Comment by CommanderMark** [comment]
I might be missing something here, but why exactly can't you use the in-game hosting exclusively if you need the GUI?
