### ISSUE TITLE
[0.10.505] Plant's Growth Delay is too fast

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3810]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Plant's Growth Delay feels too fast.

I hardly have time to do other stuff but rotate between 4 plants. If I am occupied for like 3~5 minutes the plants wither away. I have Growth Delay set at "4" to be comfortable out looting wrecks and artifact missions with the occasional check up. At least in singleplayer I can switch back to a character on the submarine, but even then it doesn't take long before I have to switch back and forth.

**Version**
0.10.505

**Comment by Flotilla-zz** [comment]
I'm not sure what "growth delay" does in its entirety, but I agree that water drains far too quickly in the current build. Any event which requires a protracted response from the player (Moloch, hull breach, Thalamus, scavenge mission, etc.) is almost invariably going to result in plants dying from dehydration.

As Barotrauma doesn't currently have a gardening-centric job, the amount of watering micromanagement expected out of gardening in its current form feels unreasonably high.

**Comment by ezjamsen** [comment]
Agreed. We'll slow it down.

**Comment by danielasteljoki** [comment]
Tuned values in de79d1d.

**Comment by dylanstrategie** [comment]
It's definitely slow, probably too slow this time. I've intentionally set a Raptorbane to grow in the Captain's Helm (Typhon 2). 5-10 minutes later, a single mob gnawed the top of the Captain's helm, causing it to trickle in water. My plant, which I had to water 3 times and only gave one fruit (which exploded on the floor) died instantly

**Comment by Rokvach** [comment]
No issues, closing.
