### ISSUE TITLE
[0.10.505] Unable to sell Fruits

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3813]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to sell fruits like Pomegrenade, Salt Bulb, Etc...

**Version**
0.10.505

**Comment by danielasteljoki** [comment]
Allowed selling plant products in f6f1e22, except for mutated versions.

**Comment by Rokvach** [comment]
No issues, closing.
