### ISSUE TITLE
[0.10.505] Too easy to accidently uproot planter boxes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3814]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Too easy to accidently uproot planter boxes. Should probably require a diving knife.

**Version**
0.10.505

**Comment by ezjamsen** [comment]
It is a little bit too easy to uproot your plants. We'll look into this.

**Comment by ezjamsen** [comment]
@3e849f2e5c can we get a longer uproot timer by any chance?

**Comment by Regalis11** [comment]
@ezjamsen "pickingtime" property in the Planter component (atm set to 3 seconds)

**Comment by ezjamsen** [comment]
increased picktime to 7 seconds.

**Comment by Rokvach** [comment]
No issues, closing.
