### ISSUE TITLE
Death desync after moving sub away from spawnpoint

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3815]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
~After respawning in a shuttle on a mission~ After moving away from spawnpoint there will be massive death-related desync. When you die server-side you will be locked in place instead. When you are knocked out you can't `give up` and spectate.

**Steps To Reproduce** (Original, see below for a non-shuttle related one, though this one works too)
1. Host server (dedicated or p2p).
2. Start mission.
3. Kill yourself (for example `kill` command).
4. Respawn in a shuttle (`respawnnow` command).
5. Kill yourself again (`kill` command).
6. Notice that you will die on the server, but you will still appear very alive for some time but can't move or give up.

**Version**
0.10.505.0 - 0.10.5

**Additional information**
I'm pretty sure it did not happen in the previous minor unstable version.

EDIT: Update description, version and steps to reproduce with newly found information.

**Comment by EtiamNullam** [comment]
Just reproduced it in campaign on 0.10.5 (unstable). It has nothing to do with shuttle.

Looks like moving 100m away from mission spawnpoint won't let you die client-side at all. Waiting idle where nothing happens and close to station won't trigger that desync.

It happens to every player on the server. If you are supposed to die others will drop on the floor for you. Sometimes you can move and interact with devices but server will "correct" everything you do (you're dead on the server so its fine).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea7f73a5aa359964156be338da88cb07f8c84fd5

**Comment by EtiamNullam** [comment]
In the latest update it works on the beginning after leaving the spawn but there is a big delay (about 2 seconds) before every death on client (compared to server). Killing yourself on the spawn is always instant.

After some time it happens again I think its when monsters spawn.

It looks like a different issue but I will continue here.

New **Steps to reproduce**:
1. Start multiplayer mission.
2. Meet monsters.
3. Kill yourself (for example `kill` command)
4. Notice you will appear dead to server and others but not for yourself.

**Comment by Regalis11** [comment]
Another attempt: https://github.com/Regalis11/Barotrauma-development/commit/231bc980554fadffc9cba402bfa2709507e053d1

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore after the latest fix, looks to be working correctly. Closing.
