### ISSUE TITLE
Can't control pump manually after unwiring SET_TARGETLEVEL

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3816]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't control pump manually after unwiring `SET_TARGETLEVEL` from it.

**Steps To Reproduce**
1. Host and join a server.
2. Unwire `SET_TARGETLEVEL` on pump from navigation terminal.
3. Try manually controlling the pump.
4. Notice the water level will change briefly then jump back to the original position.
5. Notice the water level will not change when you try to move the sub vertically - as expected but it means its been correctly unwired from the navigation terminal.

**Version**
0.10.4.0 - 0.10.505.0

**Additional information**
I had recently similar issue with ballast pumps behaving weird in 0.10.4.0 after rewiring. Sounds a bit similar to problem described in #3624.

**Comment by Kaillera** [comment]
#3742

**Comment by EtiamNullam** [comment]
@Kaillera Yeah that sounds like the same issue. The one you submitted is a bit misleading as I think it has nothing to do with wifi component. I see you are submitting a lot of them but I think you should work on their quality.

Anyway I managed to reproduce it on 0.10.4.0 every time also created a test bed for it: [pump-targetlevel-test.zip](https://github.com/Regalis11/Barotrauma/files/5213374/pump-targetlevel-test.zip)

Also I noticed the pump will become usable again after you send something to `SET_SPEED`. So looks like pump will remember last `TARGETLEVEL` until you send something to `SET_SPEED`, while manually setting speed will work only on client. This problem won't happen in sub editor.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b5614d08dd8639c77a2716cbceed4d06f3a6886

**Comment by EtiamNullam** [comment]
It works much better but just tried unwiring `SET_TARGETLEVEL` then failed to wire `SET_TARGETLEVEL` back, it resulted in pump being "desynced": I saw it unwired, other player saw it unwired but when controlling it manually it was going resetting to the original water level.

**Comment by Regalis11** [comment]
That could be a separate issue related to https://github.com/Regalis11/Barotrauma/issues/3744, but I'll keep this one open until we manage to diagnose this further.

**Comment by Regalis11** [comment]
#3477 should be fixed now, let's move this to QA and see if it affects this

**Comment by EtiamNullam** [comment]
@Regalis11 3744*

**Comment by Rokvach** [comment]
No issues, closing.
