### ISSUE TITLE
No sound.    (error no audio devices found disabling audio play back)

### ISSUE THREAD

**Issue by sadmeduk** [Regalis11/Barotrauma#382]
When I start barotrauma  at the main menu the debug menu shows up and says error no audio devices found disabling audio playback and I can't hear anything in the game I tried unplugging and replugging it my headphones it still won't work

**Comment by juanjp600** [comment]
Should be fixed by https://github.com/Regalis11/Barotrauma/commit/f50c37d515333dbc69cb40058a347b7a373650d3
