### ISSUE TITLE
[QoL] Allow swapping sub-inventory items by dropping the item directly on the parent item, even when the parent item already holds an item

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3822]
Currently if you drop an item which should go in to the parent items inventory on top of the parent item it will swap the items in the main inventory rather than swap the item with the sub-inventory item like it should.

Example 1: 
You are running low on oxygen and you try to drop a new oxygen bottle in by placing the item directly to the diving suit slot, you notice that the slot will flash red and inform the player that the item can't be placed, player is only able to place the item directly in the diving suits sub-inventory to swap with the empty oxygen bottle.

Example 2: 
You are using the Sprayer item to paint the walls and you want to swap the paint with a Ethanol when you want to erase something, so you drop the Ethanol directly to the Sprayer and instead of swapping the child items it swaps the Sprayers position on the inventory with Ethanols position. 

Additional request(if possible): Allow double clicking to swap items, so if you have a Sprayer selected and you want to change the color of the paint you would just double click the paint in your inventory and it would swap it with the paint on the Sprayer when the Sprayer is selected.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/b041f4a8aee3204d1a2affda8514d3fe5264f1f4

**Comment by Rokvach** [comment]
I'm unable to replace a oxygen tank in my diving suit, tested both dropping in to the parent slot and the hover slot and both returns as if the item isn't allowed to be placed in

**Comment by Regalis11** [comment]
Seemed to happen when you're dragging the tank from a stack, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6736ff952be95954590f8cd37923514ad35e4e01

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Nvm managed to find a crash

Repro steps:
1. Select Sprayer
2. Have 2 items that can go in to the Sprayer, I had Ethanol and Black Paint
3. Have Ethanol inside the Sprayer
4. Take Ethanol out of the Sprayer by dragging and drop it on to the the slot where Black Paint is
5. Game crashes when it tries to swap the Black Paint in to the Sprayer (I guess)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a961a50e-6583-4708-b51d-4b944313989c)

**Comment by Rokvach** [comment]
Tested, working correctly now. Closing.
