### ISSUE TITLE
Blue/Red/Green Paint not capitalized 

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3823]
[High Prio, Gamebreaking, Polish]
The word "paint" is not capitalized in "Blue paint".

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a915e48497253a43d53cb07466fcbc3d0610b698

**Comment by Rokvach** [comment]
No issues, closing.
