### ISSUE TITLE
Sprayer particles randomly make bonking noises when firing

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3827]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When firing the sprayer, every particle seems to spam out the same bonk noise you get when a NPC bonks into a wall in very quick succession.

**Steps To Reproduce**
Grab a Sprayer loaded with any liquid, fire it. It seems to happen extremely often if tap-fired but can still happen on first fire. This could maybe be the particles colliding with each other ?

**Version**
V0.10.5.0 Unstable Build. Windows 10

**Additional information**
This seems to happen even under water, though you can't fire the gun outside the ship. Nothing on the ship seems to especially trigger. This happens even in a ballast when aiming away from the hatch/ladder

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cceff1c3d4dcb5d07fa1c35d748118413461a1f1

**Comment by dylanstrategie** [comment]
This is fixed as of latest Unstable, cannot reproduce at all
