### ISSUE TITLE
Water dirt decal is way too intensely black

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3828]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The decal caused by water being in the ship (even in places like ballasts) builds up to being pure 100 % black extremely quickly, which makes it look like the entire ship was burned to a crisp, or as some people joke SCP-106. While it would be appropriate for a room that burned or exploded, it might probably be worth capping how much dirt can build up so it can't become straight up 100 % black, or discolor it so it tends to a more natural/gunky color like grey/pale green-blue. The ballasts often reach this state 1-2 mins into the round!

I guess the build-up could also be slowed. Right now any amount of flooding will cake the entire ship in deep black dirt within a minute, it's like the water of Europa is coffee!

**Steps To Reproduce**
Flood any part of the ship, or check the ballasts with a light

**Version**
V0.10.5.0 Unstable Build. Windows 10

**Additional information**
![image](https://user-images.githubusercontent.com/6137403/93231257-d5017480-f778-11ea-8486-3ffc87ff8ff5.png)
![image](https://user-images.githubusercontent.com/6137403/93231536-1e51c400-f779-11ea-8ba1-b56bb7f22c2f.png)

**Comment by EtiamNullam** [comment]
I'm pretty speed of it is just temporal for testing purposes, but it for sure should not be completely black no matter how long it says submerged.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/bd5fbf0a1dc2b6123a003623632cfd1dcaa77bff

**Comment by Rokvach** [comment]
No issues, closing.
