### ISSUE TITLE
Handles disjoint from sprayer

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3830]
[Bug, Graphical]
![image](https://user-images.githubusercontent.com/47284081/93241949-99b17680-f775-11ea-9772-05e0b3aeab40.png)
hands are not grabbing the handles on the sprayer. should be easily fixable.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9903fd4895fc0f05f2c33abc01c0ce8818b44307

**Comment by Rokvach** [comment]
No issues, closing.
