### ISSUE TITLE
Quitting to Main Menu during campaign mission transition does not stop mission loading and can crash

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3831]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you quit to Main Menu after triggering a level transition in Campaign, the game appears to keep loading in the next level despite returning to the main menu, causing a corrupted level to load in that needs to be quitted or even a hard crash.

**Steps To Reproduce**
- Enter a Campaign save (Singleplayer tested)
- Press to leave the station, choose a destination and lock it in to load the next level
- Immediately open the menu and quit to Main Menu (before and after "Please Wait..." loading text appears both lead to issues/crashes)
- The console will usually spit out a bunch of errors about unloaded assets, it might also load an incomplete level and put you in forcing you to quit again. Sometimes it also hard crashes to desktop, I got 3 crashes out of 9 attempts, and 2-3 bad level loads.

I assume that it's not stopping the level load when you quit to main menu, as I sometimes managed to quit cleanly to main menu and then got loaded into an incomplete level anyways.

**Version**
V0.10.5.0 Unstable Build. Windows 10

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5226631/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5226632/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5226633/crashreport.3.log)

**Comment by EdusFF** [comment]
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/a0f80011f4792d1d776c0050ee5243a1e166cc84

Prevented the use of the pause menu during level transitions in general

**Comment by Regalis11** [comment]
GUI.PreventPauseMenuToggle can get stuck true if the client doesn't start a new round or return to the lobby after ending a round. For example if the a disconnect or an exception occurs between the rounds.

**Comment by dylanstrategie** [comment]
I also imagine that if the menu is already open, this could cause issues

**Comment by EdusFF** [comment]
The menu is closed if it's open already. 

Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/12520c4383205c4b9d0d5a7ca9e2a2f0d1e0dad3 by adding a toggle prevention removal to mainmenu selection, which happens whenever an error occurs during multiplayer

**Comment by Rokvach** [comment]
Should the window unfocused pause menu also be prevented during loading?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
