### ISSUE TITLE
Enabled mods don't show up at the top of the list

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3832]
[Issue, Design]
This makes it extremely hard to find/figure out which mods you have enabled, which is a necessity for people with mods in the 50+. It would be nice if there were a filter of some sort that only showed enabled mods, or a separate list the way minecraft works.

**Comment by hubismal** [comment]
two lists idea seems to be better because nobody wants to drag their mod over 50 other mods in the list in order to change the load order.

**Comment by Rokvach** [comment]
It would need to be implemented in a way that the load order of even the disabled mods is intact, so whichever way to sort the list the load order should stay as is but rather the content would need to be hidden. So when you sort to only display enabled the disabled mods should still be holding their position on the list but just not be shown.

**Comment by juanjp600** [comment]
Fixed in modding refactor:
![image](https://user-images.githubusercontent.com/8607119/150966160-7beca1c0-1957-423e-b043-5ad0db1faac0.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
