### ISSUE TITLE
Explosive coilgun ammo is too strong and too easy to get

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3837]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As issue #3765 was refused I think complete lack of balance of explosive coilgun ammo has to be brought to attention:
**Its too strong and too easy to get**
- The only ingredient that differs in production of it compared to regular ammo box is UEX that is crafted from loot from mudraptor (`ore -> phosphor`) and 1/3 of hammerhead (`swim bladder -> saline -> sodium`)
- It obliterates almost every opponent - only molochs and bonethreshers are a able to survive more than a short burst and its probably the best weapon against bonethreshers despite they are supposed to be armored and piercing bolts should be more appropriate against them. Crawlers and mudraptors die from ~2 shots, hammerheads from ~8 shots and if they are bunched up you need even less
- Considering above it takes ~5 perfectly aimed explosive bolts to get materials back to recreate UEX for whole ammo box and I believe one box contains 200 bolts so it has enough damage output to kill up to 40 UEXes worth of enemies
- Its pretty strong against sub hull in pvp and of course works great against people too

I get that coilguns are supposed to be the most efficient way to deal with the monsters but the amount of explosive payload and bonus damage from single block of UEX is just way too much. Compare it to explosion of single UEX or other stuff you can make from it: frag grenade, 40mm grenade, C-4, explosive harpoon.

Maybe general coilgun nerf would be more appropriate as piercing ammo works a bit too well against molochs but at least titanium is harder to get.

**Steps To Reproduce**
1. Load explosive coilgun ammo.
2. Shoot stuff.
3. Notice how quickly everything dies.

**Version**
0.10.4 (stable) - 0.10.5 (unstable)

**Comment by danielasteljoki** [comment]
Modifed recipes in fd254a0.

**Comment by Rokvach** [comment]
No issues, closing.
