### ISSUE TITLE
In PvP right side gets all the monster spawns

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3838]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In PvP (sub vs sub) all the monsters spawn only around the sub of the right. It makes it very unfair to play PvP with anything other than 0% difficulty.

**Steps To Reproduce**
1. Start a combat mission with 2+ players and some difficulty.
2. Move away from spawn with both subs.
3. Notice right side is swarmed with monsters while left side gets exactly 0.

**Version**
0.10.4 (stable) - 0.10.5 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a7ac8ff86c9ac8501488fc41f2d9709c363f7363

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
