### ISSUE TITLE
[0.10.505~0.10.5.0] Railgun damage felt like it regressed to 0.10.4

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3839]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Railgun damage felt like it regressed to 0.10.4. Shooting Bonethresher main body instead of head deals very little damage. Moloch skirt and legs gets in the way a lot, heavily reducing damage when shot at. Those moloch limbs when severed seems to linger around for a while too, blocking all other incoming shots.

This was 2 direct hits with railgun shells with incendium grenade on a Bone Thresher. It didn't even die.
![](https://cdn.discordapp.com/attachments/668819422919524352/755569264072720384/Capture.PNG)

A Railgun Shell with Compound N main body direct hit.
![Capture](https://user-images.githubusercontent.com/5086682/93275645-7265a400-f78b-11ea-85f2-5c8b14bcfc3b.PNG)

**Version**
0.10.505~0.10.5.0

**Comment by Regalis11** [comment]
Couldn't repro, this is the result when I hit it with a railgun shell loaded with an incendium grenade:
![eas54yfdth](https://user-images.githubusercontent.com/14351070/93326856-287bcd00-f822-11ea-800f-66223e490dcf.png)

I think you probably hit the armor?

**Comment by Rokvach** [comment]
No issues, closing.
