### ISSUE TITLE
[0.10.5.0] Strange Welded and Uninteractable Door in Mining Outpost

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3841]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The door circled below started off welded in the level. Also for some reason the door was uninteractable even after I cut off the welding.

![Capture](https://user-images.githubusercontent.com/5086682/93278573-156dec00-f793-11ea-95e1-d1fc9eaf8568.PNG)

**Version**
0.10.5.0

**Additional information**
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5228872/Multiplayer.zip)

**Comment by Regalis11** [comment]
This is intentional. Doors that don't lead to anywhere are welded and made uninteractable during the outpost generation. However, I don't think these doors should be cuttable, will fix that.

**Comment by Rokvach** [comment]
No issues, closing.
