### ISSUE TITLE
Husk Cult NPC that offered me to eat eggs hanging around in mining module. No ventilation there and suffocated.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3842]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So the mining outpost in this level spawned a Husk Cult NPC that offered me to eat eggs. He spawned in the mining area of the outpost and eventually suffocated because there's no ventilation in there. He should've ran out of there for oxygen.

![Capture](https://user-images.githubusercontent.com/5086682/93278923-f2900780-f793-11ea-871d-89dcd238b7cd.PNG)

**Version**
0.10.5.0

**Additional Information**
Same Save from #3841.
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5228872/Multiplayer.zip)

**Comment by Kaillera** [comment]
Actually I don't remember what room he spawned in, but it might've been due to #3843.

**Comment by Regalis11** [comment]
It's intentional that some of the mine modules don't have ventilation. The NPC wasn't able to get out of the modules due to #3843, so I think this can be closed.
