### ISSUE TITLE
Unconnected Waypoints in these Mining Outpost Modules

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3843]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There's no waypoint connection here.
![Capture](https://user-images.githubusercontent.com/5086682/93279131-75b15d80-f794-11ea-915a-1d0e68867ca4.PNG)

**Version**
0.10.5.0

**Additional information**
Same Save from #3841.
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5228872/Multiplayer.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/76049923c5ea7378246782a31f34d2c6982b1f11

**Comment by Rokvach** [comment]
No issues, closing.
