### ISSUE TITLE
Human ragdoll in Character Editor has both a bugged pose and a hard crash pose

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3845]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using the default human ragdoll that you start with in the Character Editor, you can easily put yourself into a bugged pose that doesn't exist in normal gameplay by going into the Run pose and then crouching (in normal gameplay, crouching abords sprinting, so this stance is impossible)

If you put yourself into either Swim stance using the Animation tool and then attempt to crouch, the game will instantly crash. In normal gameplay, crouching while swimming makes your head look down a bit (easily noticeable with diving suit headlight)

All other human base mobs (Human, Human Husk, Husk) have the same issue. No other mobs feature it (I imagine because none of them can "crouch" per say)

**Steps To Reproduce**
- Enter Character Editor
- Put yourself into Run pose (or sprint key) and then crouch to witness the bugged pose (it will reset if you release crouch or sprint)
- Put yourself into SwimSlow or SwimFast pose with Animation tool and then crouch to witness hard crash

**Version**
V0.10.5.0 Unstable Build. Windows 10

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5232826/crashreport.log)

**Comment by Regalis11** [comment]
Fixed the crashing in https://github.com/Regalis11/Barotrauma-development/commit/2f6d08b2e5d7cdcb90986c494e906ef56d109575 and prevented crouching while running in https://github.com/Regalis11/Barotrauma-development/commit/d373f83ff7058e8e0f986f1ad5d50bd97722285f

**Comment by Rokvach** [comment]
Didn't notice any issues, closing.

**Comment by dylanstrategie** [comment]
This has definitely not been fixed as of today's release build + hotfix, see crash log. Might be fixed on private dev repo ?
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5263418/crashreport.log)

**Comment by itchyOwl** [comment]
It's fixed on the bugfixes branch, but the fix didn't make it to the current release build. Will be included in the next unstable. Please test that it works, when we release the new unstable.
