### ISSUE TITLE
Leaving Sub Behind With Drone To Natural Formation [Multiplayer]

### ISSUE THREAD

**Issue by ThePiggyPlane** [Regalis11/Barotrauma#3848]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After leaving a sub behind, in this case the [ATLAS] Tetrarch (https://steamcommunity.com/sharedfiles/filedetails/?id=2153626704&searchtext=), via a drone to a natural formation, the server crashes.
I'm unsure if the number of drones the submarine had equipped affected the issue.

**Steps To Reproduce**
1. Leave the sub via an external drone to a natural formation at the end of the level.
2. Leave the level at the natural formation endpoint.
3. Ensure that more users are inside the drone than inside the submarine.

**Version**
Barotrauma v0.10.5.0 (ReleaseWindows, branch release, revision 7d2e70ab36)

**Additional information**
Crash logs:
https://imgur.com/a/bRQXLz8

(Apologies if anything sounds weird or info is missing, first time writing a GitHub bug report.)

**Comment by Regalis11** [comment]
Removing the crash tag because this doesn't appear to be a crash, the client just disconnects and goes back to the main menu

**Comment by Regalis11** [comment]
It seems that the issue was also reported in #3330 and should be now fixed, closing
