### ISSUE TITLE
Spawnsub command doesn't work in multiplayer

### ISSUE THREAD

**Issue by MACMAN2003** [Regalis11/Barotrauma#3849]
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you go into single player campaign and spawn a sub in it spawns but if you host a multiplayer server and try to spawn in a sub it fails

**Steps To Reproduce**
host a server, type "enablecheats" into the console then type "spawnsub hemulen" into the console

**Version**
0.10.4.0 Windows

**Additional information**

![20200916151527_1](https://user-images.githubusercontent.com/20659419/93407589-6a6b3a00-f847-11ea-8951-b769f6e0cd79.jpg)

![20200916152744_1](https://user-images.githubusercontent.com/20659419/93407521-43ad0380-f847-11ea-9d5f-d45f864690ef.jpg)

**Comment by Regalis11** [comment]
This is intentional, implementing loading submarines mid-round in multiplayer wouldn't be a trivial task and we decided not to do it (messing with the networking for a niche use like this probably isn't worth the effort).
