### ISSUE TITLE
[0.10.5.0] Multiplayer Desync - Fully matured plants doesn't drain water on Client side, but does on Server side.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3851]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fully matured plants doesn't drain water on Client side, but does on Server side.

**Steps To Reproduce**
Easier and Faster if you put growth delay on like 0.1

1. Plant Seed
2. Keep watering plant.
3. Once plant is matured, keep watering it.
4. Note how water gauge never goes down after it matures.

**Version**
0.10.5.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/02066910cb07b6e5647915f3245f4e0a8f70d66f

**Comment by Rokvach** [comment]
No issues, closing.
