### ISSUE TITLE
[0.10.5.0] Uprooting Plant/Dead Vine produces a seed, but you do not see the seed until next round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3852]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Uprooting Plant/Dead Vine produces a seed, but you do not see the seed until next round at the planter box. Affects both Singleplayer and Multiplayer.

If you planted the seed that was produced at the planter box, it either creates a fully grown dead plant, or a fully grown healthy plant depending at what life cycle it was uprooted at.

**Version**
0.10.5.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b2052572424782bc71f1db120ca2d3053cd28fb

**Comment by Rokvach** [comment]
No issues, closing.
