### ISSUE TITLE
[0.10.5.0] Sprayed paint opacity is not saved to next round. Immediately becomes full opacity next round.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3853]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sprayed paint opacity is not saved to next round (Ex. A slight tap with the sprayer). The paint Immediately becomes full opacity next round.

**Version**
0.10.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78b8371d3137dcabd813f3064fdf0f95d2ccbbd9

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
