### ISSUE TITLE
Paint cans don't explode on initial impact

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3854]
[Issue]
Paint cans when thrown bounce once or twice before finally exploding when they reach the end of a room. Their impact tolerance probably is too high. Because of this you can only splatter paint cans near doors or vertical walls.

**Comment by Regalis11** [comment]
This is intentional, the cans need to hit something with enough force to explode. Dropping them or making them deflect/bounce off a ceiling/floor at a low angle shouldn't break them.
