### ISSUE TITLE
Can't haste respawn shuttle despawn after first one

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#3855]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't haste shuttle despawn after the first one with `respawnnow`.

**Steps To Reproduce**
1. Start a mission (not in campaign).
2. Get killed (`kill` command).
3. Respawn in a shuttle (`respawnnow` command).
4. Get killed (`kill` command).
5. Haste shuttle despawn (`respawnnow` command).
5. Respawn in a shuttle (`respawnnow` command).
6. Get killed (`kill` command).
7. Notice you can't haste shuttle despawn anymore from this point ('respawnnow' command) and have wait for timer to expire ('Leaving in...`) even when nobody is alive inside anymore.

**Version**
0.10.4 (stable) - 0.10.5 (unstable)

**Additional information**
Its annoying you can't do that as you often want to redeploy the shuttle for various reasons, for example when a new player just joined or half of the crew died and you don't want them to wait.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a046c9cfedce3bdf0a6db4c3f35d751834dd751

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
