### ISSUE TITLE
Supplies Cabinets in minemodule_01 and minetransition_01 has no items

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3857]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Supplies Cabinets in minemodule_01 and minetransition_01 has no items.

**Version**
0.10.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9c5b1c710aebab9af83b99623aa010d5a4d7ecdf

**Comment by Rokvach** [comment]
No issues, closing.
