### ISSUE TITLE
Pomegrenade Extract looks like Fentanyl

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3858]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pomegrenade Extract looks like Fentanyl

**Version**
0.10.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a765458

**Comment by Rokvach** [comment]
No issues, closing.
