### ISSUE TITLE
[0.10.5.1] Paint opacity is too low

### ISSUE THREAD

**Issue by Flotilla-zz** [Regalis11/Barotrauma#3860]
**Description:**
Spray paint decal opacity caps at an arbitrarily low value in the latest build, resulting in washed out colors that blend in with the background.

**Replication:**
1. Spawn a sprayer and white/black paint
2. Spraypaint the Big Rig's walls; with white paint, they'll hardly shift color at all, even after spraying for extended periods of time. With black paint, they'll take on an unsightly smokey appearance that looks more like water damage than paint.
3. Use the bug reported at #3853 to view the paint at full opacity; they'll appear much more vibrant, as they should be after spraying them down for minutes on end. I've attached before/after pictures showing the contrast.

**Version:**
[0.10.5.1]

![20200918092105_1](https://user-images.githubusercontent.com/3611705/93603315-d5c12300-f991-11ea-813f-917caa4e4db5.jpg)
![20200918092133_1](https://user-images.githubusercontent.com/3611705/93603335-dce83100-f991-11ea-9bad-e0f05885e305.jpg)

**Comment by Regalis11** [comment]
This is intentional: we felt the highly saturated, bright colors looked too out-of-place compared to the rest of the game's visuals.
