### ISSUE TITLE
Kastrull airlock warning light on bridge does not turn off

### ISSUE THREAD

**Issue by veborich** [Regalis11/Barotrauma#3862]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Airlock warning light on bridge on Kastrull turns on when airlock first opened but does not shut off once door is closed.

**Steps To Reproduce**
See above

**Version**
10.4

**Additional information**
Easy fix - the OR component attached to each airlock door should have False Output of 0 instead of current null output.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/931c70bf79f48a31145d3baa79a39c9dc420a822

**Comment by Rokvach** [comment]
No issues, closing.
