### ISSUE TITLE
[0.10.5.0] Faraday Artifacts are being damaged

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3863]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Faraday Artifacts are being damaged. I think they're vulnerable to EMP themselves. Also can't sell them.

**Version**
0.10.5.0

**Comment by Regalis11** [comment]
This is sort of intentional, the explosion effect works with 2 status effects that cycle the item's condition between 0 and 100. Need to look into why it isn't sellable though.

**Comment by Regalis11** [comment]
Could not reproduce, I was able to sell the artifact with no issues.

**Comment by Kaillera** [comment]
Not sure if it's a Multiplayer specific issue but:
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5258723/Multiplayer.zip)

I have a Faraday sitting in Crew Quqrters.

![Capture](https://user-images.githubusercontent.com/5086682/93833785-a3405000-fc47-11ea-826d-055552eab764.PNG)
![Capture](https://user-images.githubusercontent.com/5086682/93833810-b4895c80-fc47-11ea-9218-923f0d4ad240.PNG)

**Comment by Ewilhan** [comment]
Can confirm, have not been able to sell them, even tho I was able to sell other alien artifacts.
My campaign was multiplayer too, if this helps. 
If there's something I can do/send to help track this down, I'll gladly help

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/42c3e0a0262a47db39a1f860ca8f46d72f035362

**Comment by Rokvach** [comment]
No issues, closing.
