### ISSUE TITLE
Multiplayer - 2-3 NPC following players, but does not trigger outpost event. -10 Location Rep for no reasons usually.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3864]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So in Multiplayer servers, there are outpost events with 2-3 NPC following players but does not trigger. You will usually get -10 Rep after leaving the outpost. ~~I think this happens more often when you play with bots, or maybe when the server's been actually playing for several hours.~~

**Version**
0.10.4~0.10.5.0

**Comment by EtiamNullam** [comment]
I've seen it happen many times and I never play with bots. Did not notice the reputation hit. It happened to me as early as first stop in newly hosted campaign so I don't think it matters how long the server is up.

**Comment by Regalis11** [comment]
I'm not sure I understand this correctly: there are a couple of NPCs following the players, but what exactly does not trigger? Do you mean the dialog popups?

**Comment by Kaillera** [comment]
No dialogue pop up.

**Comment by Regalis11** [comment]
Haven't been able to repro the NPCs following the player, but the random reputation loss/gain when leaving the 1st outpost should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/86f2a282b5bc90ac66efec4d19b261699c2ed2a2

**Comment by Rokvach** [comment]
Tested, didn't notice any issues. Closing.
