### ISSUE TITLE
P2P Servers - Use defined Player Name in Server Browser as the Host's Character Name instead of Server Name for the Character when they host

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3868]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When hosting P2P Servers, hosts will have their character name as the server name, which is quite annoying, I think it'd be nice if it uses the defined Player Name in Server Browser as their character by default instead.

**Version**
~0.10.5

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/6c773472483bfe8fb322ab20c8a02ddf2b103723

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
