### ISSUE TITLE
Fill in P2P server settings with previously used settings from serversettings.xml

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3869]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I don't know why we have to fill in Server Name/Password/Public every time we host a P2P server when we launch the game. Can we have it auto fill in with what we previously had in serversettings.xml?

**Version**
~0.10.5

**Comment by juanjp600** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/1258e62b6e7f68fa03b079e14b39ad49bf151faa

**Comment by Rokvach** [comment]
Might be good to set the server public by default on the server settings, currently when the settings are created its set to false

Other than that I didn't find any issues

**Comment by juanjp600** [comment]
Changed default public setting in https://github.com/Regalis11/Barotrauma-development/commit/bd693ebbb9591b96e066a92df227ae51d595a1c4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
