### ISSUE TITLE
[0.10.5.0] You can stack damaged fruits, and it doesn't recover condition

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3870]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can stack damaged fruits, and it doesn't recover condition. Not sure if it affects seeds too.

**Version**
0.10.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d454b93ab9eefc238a80b140d008cfff6284da9e

**Comment by Rokvach** [comment]
No issues, closing.
