### ISSUE TITLE
[0.10.5.0] Pipe Tobacco sells for 1 mk. The Buds sells for more

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3871]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pipe Tobacco sells for 1 mk. The Buds sells for more. Not profitable :(

**Version**
0.10.5.0

**Comment by danielasteljoki** [comment]
Fixed in be5ce90.

**Comment by Rokvach** [comment]
No issues, closing.
