### ISSUE TITLE
[Suggestion] Customizing bots behavior

### ISSUE THREAD

**Issue by henrique2d** [Regalis11/Barotrauma#3872]
I don't know if suggestions are allowed or if i should do it here, so please correct me if i'm wrong

i know the main ideia of the game may be is the multiplayer and co-op but as a ~~antisocial sadboi~~ singleplayer fan i was thinking of making the bots in the game customizable(or programmable), instead of just trying to make the bots work better in general, let the player take some work in that, maybe with some block-based scripting idk

**Comment by itchyOwl** [comment]
It's a good suggestion, but implementing that would be a pretty huge task. I'd say, it's possible that we add more control for the player, but definitely not any kind of scripting. I'll close this, as your request is  now heard. Thank you for the feedback!
