### ISSUE TITLE
Cleaning a decal isn't synced between players

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3874]
Noticed while testing the Sprayer sound not being synced issue, that cleaning a fruit splash decal isn't synced between clients either.

So if a Client 1 throws a fruit and then cleans it, Client 2 will still see the splash until Client 2 cleans it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3078fe59bfb60fdb5955013bf6e8959119aab187 alongside a bunch of other issues I noticed while diagnosing this (see the commit message)

**Comment by jcdj** [comment]
> Fixed in [Regalis11/Barotrauma-development@3078fe5](https://github.com/Regalis11/Barotrauma-development/commit/3078fe59bfb60fdb5955013bf6e8959119aab187) alongside a bunch of other issues I noticed while diagnosing this (see the commit message)

Hi, can't see that post. "This is not the web page you are looking for" and I really want to solve this issue.

**Comment by Regalis11** [comment]
Hi! That's a link to a commit in our private repository. I'm not sure if the commit message is of any use of you, the comment was intended for our own internal testing. I'm afraid there's not much you can do to solve this issue at the moment, you'll have to wait for the fix to be released in the next patch. :/ Sorry for the trouble.

But in any case, here's the commit message if you're curious:
> Fixes to decal syncing:
> - Fixed clients creating decals themselves without an update from the server.
> - Fixed decal position being calculated incorrectly when receiving an update from the server.
> - Sync sprite index, otherwise decals may look different on different clients and change appearance when receiving an update.
> - Fixed server not sending a decal update when a client cleans decals (Regalis11/Barotrauma#3874).

**Comment by jcdj** [comment]
> Hi! That's a link to a commit in our private repository. I'm not sure if the commit message is of any use of you, the comment was intended for our own internal testing. I'm afraid there's not much you can do to solve this issue at the moment, you'll have to wait for the fix to be released in the next patch. :/ Sorry for the trouble.
> 
> But in any case, here's the commit message if you're curious:
> 
> > Fixes to decal syncing:
> > 
> > * Fixed clients creating decals themselves without an update from the server.
> > * Fixed decal position being calculated incorrectly when receiving an update from the server.
> > * Sync sprite index, otherwise decals may look different on different clients and change appearance when receiving an update.
> > * Fixed server not sending a decal update when a client cleans decals (#3874).

Oh ty! Good to know.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
