### ISSUE TITLE
[0.10.5.1] Game freezes when scanning for servers

### ISSUE THREAD

**Issue by alkaid7205** [Regalis11/Barotrauma#3881]
- [x]  I have searched the issue tracker to check if the issue has already been reported.

**Description:**
Since the latest update, after pressing the 'server browser' button - the game freezes and not responding anymore. It takes about 4 minutes to complete the scan and 'unstuck' (sometimes it takes way longer) 
Pressing 'scan servers' have the same freeze effect on the game.
During the game freeze cpu goes from 2-3% usage to 30% usage
Memory/Disk/Network usage remains the same.
![Frozen](https://user-images.githubusercontent.com/71730359/93936997-ac0c5100-fd2f-11ea-90c4-7a9d5fd7c46c.png)

After the servers are shown to me  I experience no problem connecting and playing afterwards.

**Things I've tried so far:**
Reinstall the game. (also deleting all custom/vanilla subs)
Unsubscribe from all mods.
Remove all friends on Steam.
Stick to simple English nick (in steam and in game).

p.s:
Nothing have changed on my side.
I am on a stable wired internet connection.

**Version**
0.10.5.1

**Operating System**
Windows

**Comment by alkaid7205** [comment]
**update:** 
Another freeze happens on display mode change, but this freeze comes with a huge memory usage.
![FreezeOnChange](https://user-images.githubusercontent.com/71730359/94037116-b2e9a100-fdcd-11ea-9885-d49d7c43bda6.jpg)

After more tests, I experience another freeze upon entering someone's lobby. 
![FreezeInLobby](https://user-images.githubusercontent.com/71730359/94039679-afa3e480-fdd0-11ea-87dc-e3ed36e088ff.png)

**Additional info:**
All those freezes came with the latest update.  

Microsoft Windows 10 Home
Processor Intel(R) Core(TM)  i5-3570K CPU @3.40Ghz, 4 Cores
RAM 8Gb
AMD Radeon HD 7850 (7800 Series) VRAM 2GB GDDR5

**Comment by alkaid7205** [comment]
**Update** Two hours ago, everything was still freezing.
But now, all the freezes are gone like a bad dream. No more freezes (any of the described above)
And no more huge fps drops during initial load at about ~68%.

Game version is still the same(0.10.5.1), branch release, revision is still 9e259b2148.
Can't tell what was source of the problem.
Thank you

**Comment by hubismal** [comment]
The cause of this was most likely recentservers.xml and favoriteservers.xml that juanjp discovered was the reason for the server browser freeze in my case.
