### ISSUE TITLE
Security attacks you when fighting NPCs in the "mediator" event

### ISSUE THREAD

**Issue by veborich** [Regalis11/Barotrauma#3882]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure event name but you get attacked by two NPCs with either dialog tree response. You either let them kill you or defend yourself and Outpost security kills you. I've tried running from them and killing them where there's no witnesses but security still attacks me.

**Steps To Reproduce**
Event triggers, reply with either tree, die by NPC no matter what.

**Version**
0.10.5.1

**Additional information**
Am I missing something?

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@96a139a

**Comment by Rokvach** [comment]
Tested by shooting both of the event NPC's in front of a guard, he didn't react in anyway. So working correctly. Closing.
