### ISSUE TITLE
Radio channel doesn't affect voice comms

### ISSUE THREAD

**Issue by veborich** [Regalis11/Barotrauma#3883]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since latest update 0.10.5.1, I have this strange behavior:
* When not wearing headset, I can still hear voice comms radio chat
* When wearing headset and changing channel, it does nothing: I hear all voice comms radio chat
* `r;` text chat **is** obeying the headset rules (i.e. if not wearing headset, cannot use or see `r;` text chat

**Steps To Reproduce**
See above.

**Version**
0.10.5.1

**Additional information**

**Comment by Regalis11** [comment]
You can also hear the voice comms if you're standing close to the speaker (i.e. in the same room or a room right next to you), could that have been the case?

**Comment by veborich** [comment]
It’s possible but it seemed I was hearing people from far beyond the nearby room. Also I was on EVA 200m from ship and could hear crewmates perfectly - wasn’t there interference at that distance before? At the time I forgot to try removing the headset...

**Comment by veborich** [comment]
Confirmed with further play: Voice comms over radio seems to disregard range.  At 250m+ from ship, I had perfect voice comms with crewmates, but typing `r;` in chat, they said they didn't see the communication.

**Comment by Regalis11** [comment]
Seems to have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/c4e4d538

**Comment by Rokvach** [comment]
Closing.
