### ISSUE TITLE
[fuel_out] output on the reactor does not work properly

### ISSUE THREAD

**Issue by Cryostasis** [Regalis11/Barotrauma#3884]
**Description**
[fuel_out] output on the reactor always outputs 100 x [number of fuel rods], not a percentage of remaining fuel

**Version**
0.10.5.1

**Comment by Kaillera** [comment]
It's not for displaying the percentage of remaining condition.

**Comment by Regalis11** [comment]
Yeah, this is intentional: the amount of available fuel is not a percentage of fuel remaining, but a value indicating how much heat you can get out from the rods.
