### ISSUE TITLE
Typhon #1 Capacitor room won't flood from above

### ISSUE THREAD

**Issue by Definitelylegit** [Regalis11/Barotrauma#3885]
**Description**
We plasma torched the roof of the capacitor room. The room is not flooding. We had a crewmember able to enter the room from the outside, and I could exist fine without a deep sea diving suit 

**Steps To Reproduce**
Picture attached
![barotrauma bug](https://user-images.githubusercontent.com/65861491/93949080-f1348100-fd37-11ea-99f6-2d1539799730.png)

**Version**
v0.10.5.0 Windows

**Additional information**
Only seems to be this room we couldnt recreate in another room. We tried the adjoining room and the navigation room

We tried repairing the hole and re-opening and we got the same

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bcb8f9c5a5d4f30f1d34a831cd284230111ff8f0

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue. Looks to be working correctly. Closing.
