### ISSUE TITLE
Crash after N Compound explosion during delivery - trying to put a suit

### ISSUE THREAD

**Issue by Huillam** [Regalis11/Barotrauma#3889]
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashed shortly after a big explosion during delivery of N Coumpound.
Last thing I remember is putting on a diving suit...

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5268024/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7d12f7e28f4fccd21c8854c290eb3e8c0b80332b

**Comment by Rokvach** [comment]
no issues, closing.
