### ISSUE TITLE
Rewiring switch in sub editor toggles its state

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3890]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Interacting with switch in submarine editor's wiring mode toggles its state (only the first interaction with given switch after entering Wiring Mode). 

**Steps To Reproduce**
1. Place down a switch is submarine editor and check its state.
2. Switch to Wiring Mode
3. Press E on the switch to open wiring menu
4. Notice that the state is different.
5. If you interact with the switch again without leaving Wiring Mode it will stay the same, but if you switch back and forth to Edit Mode the next interaction will toggle the state again.

**Version**
v0.10.5.1 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2c28ffc561d2aaffad4139f374272df97410dd2a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
