### ISSUE TITLE
Multiplayer - Dead bots are missing when restarting level with "start" command in the lobby

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3894]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When hosts tries to restart a level after bots have died using the "start" command in the lobby, those bots are missing when nothing else saves. It didn't behave like Server Lobby button or Gameover.

The dead bots returns if you back out into the server lobby and reload the save with the continue button, or becomes permanently loss if they proceed to the next level.

**Reproduce**
1. Load a save file that has bots.
2. Kill a bot.
3. Return to Server Lobby or End command.
4, Load the round with the "start" command instead of continue.

**Version**
0.10.5.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f7ed4b7ce7ddf8209e1c5561e888f60b85bdb7d7

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue. Working correctly. Closing.
