### ISSUE TITLE
Decontructing AntiToxins is broken

### ISSUE THREAD

**Issue by Aktheon** [Regalis11/Barotrauma#3898]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Expected: deconstruct antidotes (eg, Cyanide antidote) into Stabilozine and 0.5 Toxin syringe
Actually: after decontruction i get only Stabilozine and no Toxin

**Steps To Reproduce**
deconstruct anti toxin

**Version**
10.5.1

**Additional information**
None

**Comment by Regalis11** [comment]
This is intentional: none of the antidotes deconstruct back to the poison they're fabricated from anymore. The intention behind this change was to make the poisons harder to get than the antidotes.
