### ISSUE TITLE
Streaming - Game capture freezes whenever players open Barotrauma Setting menu

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3899]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever streamers streams Barotrauma and opens the game setting menu, the capture freezes for the viewers.

**Version**
~0.10.5.1

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d2820faf28a9075dc309e3ca88488f6b7a8e26cc and https://github.com/Regalis11/Barotrauma-development/commit/a9ce8d0321aae2cbc2bfd106b401ef8c0d5c064a

**Comment by Rokvach** [comment]
Tested, now only if you change the resolution or adjust text scale the OBS scene freezes, I think this is a good step forwards and we should later on see if we can somehow fully fix the freezing but for now I think this is fine so closing.
