### ISSUE TITLE
v0.8.1.2 alt+tab game crash - avast

### ISSUE THREAD

**Issue by HetNeSS** [Regalis11/Barotrauma#390]
Good day. Since the v0.8.1.2 came out for the avast antivirus free version users, it's possible for it to kill the game window with the "behavioral alert" included, if you alt+tab during the MP spectator mode from the borderless window to an another program window. Marks up as "IDP Generic", having troubles to push it to the quarantine, so i'm being offered to restart the computer. So if you'll hide the window screen, it will take like from 2 to 5 seconds before the game window will completely disappear from the Windows taskbar.

Win7 64x
A generic file scan shows nothing.

**Comment by Plotron** [comment]
I advise reporting a false positive to Avast. Avast AV is really pedantic as of late.
