### ISSUE TITLE
Inconsistent event dialogue scaling between resolutions

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3900]
[Issue, Modding]
higher resolutions seem to have scaling problems where less text can be fit into a box of event dialogue. annoyingly, any options are also cut off of dialogues that go on for too long. **this means that people are softlocked when the text pushes the options offscreen.**
![image](https://user-images.githubusercontent.com/47284081/94174708-2b5f6900-fe85-11ea-9b08-3aca5ff0ffcf.png)
this is at standard 720p resolution
![image](https://user-images.githubusercontent.com/47284081/94174932-78433f80-fe85-11ea-96c0-874498d09bdd.png)
and this is what it looks like on lower resolutions.
Presumably the game scales the text down more aggressively than it does the window. It would be preferable if the higher resolutions were made to fit as much text in as the lower resolutions do, there's hardly any harm in giving the text more space.

**Comment by EdusFF** [comment]
Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/fb36a6a61c4da44cc9bec0d3df8d4123a17c03f0

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, closing.
