### ISSUE TITLE
Idea to overhaul traitor mode to be acceptable for Campaign.

### ISSUE THREAD

**Issue by rivvion** [Regalis11/Barotrauma#3901]
Currently mostly nobody wants to enable traitors in campaigns because their objective usually involves killing people and wasting their skill grinds away on unneeded deaths.

However, i have an idea.
I've witnessed all sorts of fun and risky shenanigans in normal campaign servers.
Like throwing around harmless items like volleyballs or playing dodge-ball with a block of c-4 (without the explosion part)
or stunning / handcuffing each other along with some more extreme stuff that people tend to do 
just to pass the time while doing things like the boring cargo missions to increase reputations)

If you give game-play like this the same lore treatment as what's been done with the factions' (catering to each popular play style) then you'd have a traitor system where people can be working together 100% to complete missions' yet they'll try to do personal side-objectives like 1up'ing some other crew-member or sabotaging each other for shits-n'-giggles.

Here's a quick example.
As a clown you have to prank like 5 people without them finding out it was you'
like laying down (banana) fruit peels for people to slip on.
Or you have to fool some poor guy into grabbing a gun that has a "bang flag hidden in it" ect, ect, the list goes on...

On this basis you could have random events in outposts where people can whisper certain contracts into the ears of crew members or have their headset get contacted through an isolated frequency.
With these shady contracts' players can get PERSONAL rewards in the form of special items or skill-experience boosts (1-use tape-recording or a rare book or something, or just a boost of XP right away.)
These contracts could range from harmless pranks to harmful assaults depending on each contract & how much a faction hates your crew. but it is IMPORTANT that KILL-contracts should still be an option in the server lobby! just in case.
(option for traitors & option for kill contracts. two separate toggles.)
meaning that the Non-lethal contracts might still involve people getting hurt or messed with one way or another;
but killing them will end up ruining the Non-lethal contracts.

(example of non-lethal combat contract:)
"psst hey' i have a reward for tou if you can rough up that asshole crewmember you have, i still have grudges against them so i want you to beat them up! and send them a message. But!' if you end up  killing them' I'll make damn sure to ditch you with the cops." Reward "y/n"

**Comment by Regalis11** [comment]
This is a very good idea! We're actually planning on reimplementing the traitor system using the new scripted event system, and it'd be easy to add some less destructive missions to the campaign while we're at it. 

In any case, I'll close this ticket because we generally avoid having feature requests in the public repo, but I'll link this to our private ticket as a reminder for when we start redoing the traitor missions: https://github.com/Regalis11/Barotrauma-development/issues/2174
