### ISSUE TITLE
Suggestion: Water Volume Detection

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#3904]
Currently water detectors' signal_out is an output with a binary option of strings from whether the hitbox is in water or not.

Connecting this signal, however, to a status monitor provides the status monitor with percentage of flooding in containing hull.

It would be exceptionally useful for more creative circuits/logic functions if the water detectors had an additional signal node output for percentage of water volume in hull.  This would provide sub creators the ability to determine flood volume and introduce this variable into their custom circuits.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/d5e7f3e869dc375b28ae2826c8462197692fa98a

**Comment by Jlobblet** [comment]
Tested, working correctly.

**Comment by Rokvach** [comment]
Closing
