### ISSUE TITLE
Junction Boxes Signal nodes passing power/load information

### ISSUE THREAD

**Issue by Eskandaer** [Regalis11/Barotrauma#3905]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Connecting power wires (provider and user) to a signal node on a junction box results in unexpected behavior of power/load of those items being read in junction box summary. 

**Steps To Reproduce**
Connect power producer (battery in my test) power_out to junction box signal_1 node; connect power user (lamp in my test) to signal_1 node.  Observe the power/load of junction box.  

**Version**
stable release
windows 10

**Additional information**
Other users/producers cumulatively add to this power/load value.  Power does not seem to actual power the user item, however.

Attached testing file with this example in Batt > JB > lamp and Batt > JB > JB > lamp using signal nodes.
[Testing Vessel JB signal issue.zip](https://github.com/Regalis11/Barotrauma/files/5281476/Testing.Vessel.JB.signal.issue.zip)

**Comment by Eskandaer** [comment]
Additional testing; turns out that power provider connected to any JB signal node can still pass power to any using components connect to the JB power pin.
Batt power_out > JB signal_1  +   JB power > lamp power_in   = lamp is powered/on

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e874c19cfcbcadd1e7e869f5040f4b562d86966

**Comment by Rokvach** [comment]
Tested, working correctly. Coming in the next patch. Closing.
