### ISSUE TITLE
Multiplayer campaign save file corruption after docking

### ISSUE THREAD

**Issue by veborich** [Regalis11/Barotrauma#3907]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This appears to be duplicate/related to #3459 and #3510 but since those were closed as fixed Aug 18 and probably included in 10.5.1, I thought I should report again. In my case, I was hosting a campaign, only about 7 legs completed, finished a mission with nothing out of ordinary, docked at destination and was immediately booted back to Server Lobby with the debug console open with error. I didn't remember to save that error, but now trying to load the save after a full client reload always fails with error in console attached. Seems like at the moment of the crash, it failed to save that we arrived at the destination but is also trying to start us at that location?

Suggestion: Might be a good idea to automatically save rolling backups (e.g. last 3 saves), so campaigns can be recovered. 

![image](https://i.ibb.co/stRRr7J/crash-campaign.png)

**Steps To Reproduce**
Hard to replicate - finished a campaign leg as normal - there was no mission selected just traveling between destinations.

**Version**
0.10.5.1 Windows

**Additional information**
Attached debug output

**Comment by Kaillera** [comment]
Send the save file here.

**Comment by Regalis11** [comment]
Yep, the save file would be really helpful. Were you playing with a submarine that includes a drone/shuttle and did you leave a vessel in the previous level? https://trello.com/c/076rNmbm/318-level-equality-check-failed-error-due-to-undocking-attached-shuttle-and-leaving-it-behind

**Comment by YaMonJo** [comment]
Hello,

Got this game a week ago, and experiencing the same issue. 
Been playing with the biggest sub with full 16 man crew, all players.
We were doing missions just fine, decided to go to campaign.
We did 3 attempts, all resulted in same issue when finishing our run, docking to the next area.
We are using the sub Berilia, but we had it happen with another sub on another save.

![image](https://user-images.githubusercontent.com/72219233/94841556-3451bc80-03e8-11eb-88d8-7dbe4a7d9294.png)

I would like to attach save file, but I can't locate it in the game folders...
Found some error logs, don't know if it will help

[event_error_log_server_Jubal_405 AM.log](https://github.com/Regalis11/Barotrauma/files/5313919/event_error_log_server_Jubal_405.AM.log)

When trying to reload that save, I get this log
[event_error_log_client_YaMonJO_514 PM.log](https://github.com/Regalis11/Barotrauma/files/5313924/event_error_log_client_YaMonJO_514.PM.log)

**Comment by Regalis11** [comment]
@YaMonJo Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/3986 (a more thorough explanation in the ticket). Should be fixed in the next patch.
