### ISSUE TITLE
0.8.1.2 - Game launch fails sometimes (Win7-64x)

### ISSUE THREAD

**Issue by HetNeSS** [Regalis11/Barotrauma#391]
Barotrauma Client crash report (generated on 26.04.2018 18:09:06)

Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.

Game version 0.8.1.2
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GTX 950
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0022], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable], Message: Unknown
Target site: Void CheckError()
Stack trace: 
   в SharpDX.Result.CheckError()
   в SharpDX.DXGI.SwapChain.SetFullscreenState(Bool fullscreen, Output targetRef)
   в Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetHardwareFullscreen()
   в MonoGame.Framework.WinFormsGamePlatform.EnterFullScreen()
   в MonoGame.Framework.WinFormsGamePlatform.BeforeInitialize()
   в Microsoft.Xna.Framework.Game.DoInitialize()
   в Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   в Barotrauma.Program.Main() в E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:строка 41

Last debug messages:

**Comment by HetNeSS** [comment]
It's a semi-rare, like 1 crash in 10-15 launches. The second attemp is usually runs the game just fine.

**Comment by Jedi0n** [comment]
All info I find on this issue is related to using DVI instead of HDMI. Can you please say which type you are using for your monitor(s)?

**Comment by HetNeSS** [comment]
Uh.. I believe it's DisplayPort. Single monitor, AOC I2275PWQU.

**Comment by BreathTaken** [comment]
Are you using Fullscreen, windowed, or borderless for your configuration? Resolution too please :)

**Comment by HetNeSS** [comment]
![default](https://user-images.githubusercontent.com/18286472/39401398-b536543c-4b5d-11e8-867e-702ac624152b.png)

**Comment by Rokvach** [comment]
This shouldn't be an issue anymore or if it is its related to outdated Windows 7 version. Closing this.
