### ISSUE TITLE
Bots accidently welding doors when trying to fix leaks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3911]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots can accidently weld doors that are in front of leaks.

**Version**
~0.10.5.1

**Comment by Kaillera** [comment]
They should probably be able to detect when they're welding doors when they first attempt to fix leaks behind one. If they do they should open the door.

**Comment by LuCKySoZ** [comment]
A misplaced waypoint (no waypoint on the door itself) can cause this. The AI only sees a door if the waypoint tell's there's a door there

**Comment by Kaillera** [comment]
Nah it happens on subs like Dugong

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma-development/issues/2001

**Comment by Regalis11** [comment]
Nvm, noticed the earlier ticket is in our private repo, marking that as a duplicate instead

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@adf4a18.

**Comment by Rokvach** [comment]
No sightings of this happening, seems to be working correctly. Closing.
