### ISSUE TITLE
Sub Editor - "Select Matching Items" doesn't work on custom subs?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3914]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Tried to  use the "Select Matching Items" option on my [Kail Terra](https://steamcommunity.com/sharedfiles/filedetails/?id=2197390262), and it crashes on everything I've tried it on. Doesn't happen with vanilla sub like Orca.

**Steps To Reproduce**
1. Use Custom Sub. Ex. [Kail Terra](https://steamcommunity.com/sharedfiles/filedetails/?id=2197390262).
2. Select any of it's Junction Boxes.
3. Hold Shift and Right Click to get the "Select Matching Items" options and use the function.

**Version**
0.10.5.1

**Additional information**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5287136/crashreport.2.log)

**Comment by EdusFF** [comment]
Was actually caused by a linked submarine so vanilla Kaillera was crashing as well. Fixed in: https://github.com/Regalis11/Barotrauma-development/commit/153e4bdfd6c708744d73ade857b17959dbd204da

**Comment by Rokvach** [comment]
No issues, closing.
