### ISSUE TITLE
Wire reconnection problem. 

### ISSUE THREAD

**Issue by Torvald118** [Regalis11/Barotrauma#3915]
[✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When someone disconnects the wire from the module and then someone else attaches it back, the changes are not counted until the next mission starts or server restarts. (Google translate)

**Version**
v0.10.5.0+

**Comment by Regalis11** [comment]
Seems to be the same issue as #3121, fixed in Regalis11/Barotrauma-development@0059175
