### ISSUE TITLE
Can't connect to a server

### ISSUE THREAD

**Issue by NaichGarcia** [Regalis11/Barotrauma#3918]
**Description**
Some people can't connect to servers (console report the problem).

**Steps To Reproduce**
When a user have a "rare" character on their name (like a heart or something), he can't connect to any server.

**Version**
0.10.5.1

**Additional information**
You can fix this by removing that character from your steam user name.

**Comment by Regalis11** [comment]
This is not a bug: the servers can determine a range of symbols that are allowed in the client's names. By default this includes "normal" Latin, Cyrillic, Japanese, Chinese and Korean characters and some special symbols (spaces, commas, dashes, brackets, etc). 

You don't need to change your Steam name to work around the restrictions, you can simply choose another name in the "player name" field before joining, as instructed in the error message.
