### ISSUE TITLE
[0.10.5.1] Error reading message from server

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#3920]
- [x] I have searched the issue tracker to check if the issue has already been reported.

![image](https://user-images.githubusercontent.com/6713261/94354553-2e578680-004a-11eb-849d-d2a09c17f539.png)

[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5287649/crashreport_object.log)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3019
