### ISSUE TITLE
 when I'm playing and I'm about halfway through the map, it unexpectedly turns off the game

### ISSUE THREAD

**Issue by FFFiliPPP** [Regalis11/Barotrauma#3923]
-
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/5288322/crashreport.11.log)

when I'm playing and I'm about halfway through the map, it unexpectedly turns off the game

**Comment by ekqvist** [comment]
Hi, thanks for the report! Based on the crash report this seems like a duplicate of #3893. Another user with the same issue managed to avoid it by disabling the "GunLights" mod. Sorry for the inconvenience, I hope this helps until an update containing a fix is released!
