### ISSUE TITLE
Kastrull's drone oxygen transfer problem

### ISSUE THREAD

**Issue by alkaid7205** [Regalis11/Barotrauma#3925]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Oxygen doesn't replenish after it was consumed in the Kastrull's drone and the gunnery compartment.

**Steps To Reproduce**
1.Open Kastrull in the editor and press test.
2.Issue to turn on the reactor.
3.Issue a wait command to the mechanic.
4.Take control of the mechanic and move him into the drone.
5.Take control of the captain and watch drone's and gunnery compartment's oxygen levels drop.
6.When oxygen level drops in the drone, move the mechanic to the armory (you can leave armory door open).
7.Watch drone's and gunnery compartment's oxygen levels stay the same as before (depleted).

**Version**
0.10.5.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/13c1eb924f37446e4e923f35921d8d78579a6a64

**Comment by Rokvach** [comment]
No issues, closing.
