### ISSUE TITLE
Singleplayer - "Save and Quit" fully heals crew members on next load.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3926]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Save and Quit" in Singleplayer fully heals crew members on next load.

**Version**
0.10.5.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4ed313688f38180989b736d30cd07bcd5a50283

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
