### ISSUE TITLE
Game dosen't "install" -Linux

### ISSUE THREAD

**Issue by Mrampharos** [Regalis11/Barotrauma#393]
_Well_... im not that professional but:
in "linux readme.txt" it says that i should put this "chmod +740 Install.sh" in the script folder, i did and.... nothing happen, next i should put this "./Install.sh" great.... but next error occurs:
**./Install.sh: línea 1: ﻿sudo: orden no encontrada**  that will translate to:
**./Install.sh: Line 1: sudo: order not found** ,
to try something else i go to "Install.sh" and put the... only thing that is in it, "﻿sudo apt-get install libsdl2-dev libsdl2-mixer-2.0-0 libopenal-dev libsdl-mixer1.2 mono" , when i try it this happen:

**Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete mono** that will translate to:

**Reading list of packages... Done
Creating dependencies tree   
Reading state info... Done
E: The mono package was not found** _(well....  not :100: accurate)_

_Emh_... if that's not enough the next thing on "linux readme.txt" it's that in the "same folder of the game" i should put this "chmod +740 Launch_Barotrauma.sh" and then this "./Launch_Barotrauma.sh"

What's wrong? first "Launch_Barotrauma.sh" dosen't exist's however "Launch_Barotrauma"  it does, second, first command put a long line of text for do nothing, and then "./Lunch_Barotrauma" does this:

**bash: ./Lunch_Barotrauma: No existe el archivo o el directorio**
**bash: ./Lunch_Barotrauma: The archive or directory dosen't exist's**

_Aaand_... that's it (sorry for typos :+1: )

**Comment by Mrampharos** [comment]
it seems that had no effect...

**Comment by hubismal** [comment]
For anyone still viewing this open issue, the solution is to install mono-complete. For Linux Pre-Alpha (v0.8.2.3) specifically, you'll need to [install Mono 5.4](https://hubismal.neocities.org/barotrauma/).

**Comment by JJRcop** [comment]
I just confimed it earlier today. Installed `mono-complete` and it worked fine. I tested with `mono-runtime` installed only and got this error:
```shell
AL lib: (EE) AddFileEntry: Invalid header in /usr/share/openal/hrtf/default-44100.mhr: "MinPHR02"
AL lib: (EE) AddFileEntry: Failed to load /usr/share/openal/hrtf/default-44100.mhr
```

`mono-complete` and `mono-runtime` packages from debian buster
https://packages.debian.org/buster/mono-complete
https://packages.debian.org/buster/mono-runtime

**Comment by JJRcop** [comment]
By the way, would you consider adding the install scripts to the repo? scrubbed of secrets of course, if it has any.

**Comment by Regalis11** [comment]
The install scripts aren't used anymore, closing this
