### ISSUE TITLE
Crash and Corruption

### ISSUE THREAD

**Issue by DLCHL3** [Regalis11/Barotrauma#3930]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My game crashed right as a loading screen finished, corrupting my save file and causing my entire pc to crash and get stuck in an automatic repair loop.

**Steps To Reproduce**
I just beat the kill a Moloch quest and then bought a new submarine at the port. The game crashed after it finished loading leaving port after I had selected a mining supplies quest.

**Version**
v0.10.5.0 Windows 10

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid there's not much we can do about this without more info: how exactly did the crash happen, did you get a message box saying "barotrauma has crashed", did it just boot you to the desktop or did your whole PC crash with some error message? If the first option, is there a file called crashreport.log inside the game folder and could you post it here?
