### ISSUE TITLE
Make Text Displays craftable/attachable/detachable

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3931]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of the major struggle as a Wire Engineer in Barotrauma is when rewiring stuff outside of the sub editor is that there's no way to label or get easy visual outputs from our modifications. I believe converting Text Displays into craftable, attachable, and detachable would be great to have.

**Comment by FLundin** [comment]
I agree

**Comment by mLuby** [comment]
An alternative would be a multimeter tool for engineers: a one-hand device similar to a sonar beacon that when equipped (has a GUI window that) tells you the signal output of the wire you're hovering over.

In general, I support the idea of being able to craft in-game most things you can place from the sub editor.

**Comment by Prolbo** [comment]
yes please

**Comment by ScienceDiscoverer** [comment]
I would like to approve this feature too! It's doesn't make any sense that you can craft and install oxygen sensor, for example, but can't even display it output outside of sub editor! MB also add some different smaller/bigger/no-scroll types of text displays

**Comment by grandprixgp** [comment]
> Implemented in [Regalis11/Barotrauma-development@bf62d88](https://github.com/Regalis11/Barotrauma-development/commit/bf62d889a8285cc6ac9014a4d346b0f665fc75a5)

Since I can't view the commit, was the multimeter added or simply the text displays being craftable/etc?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
