### ISSUE TITLE
Metal and Secured Crates contents are water proof on Crate Shelves

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3933]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Metal and Secured Crates contents are water proof on Crate Shelves

**Version**
0.10.5.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/77247e6250f7504433af8d3c875dce12a866d0d2

**Comment by Rokvach** [comment]
No issues, closing.
