### ISSUE TITLE
Multiplayer - Can only query 50 servers

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3934]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We can only query 50 servers in the server list. Lots of times players can't find each other due to it.

**Version**
~0.10.5.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/2125

**Comment by Xeavas** [comment]
Noticed this issue too, sometimes a specific server just don't appear for awhile, [0.10.6.2]

**Comment by Rokvach** [comment]
Seems to be working correctly

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d86b3a9c-e7fd-42c6-a98f-553adef9a067)

**Comment by Xeavas** [comment]
Is there an option to requery them?  In hopes of it detecting the server you actually wanted to join?

**Comment by Rokvach** [comment]
Already merged and working correctly. Closing.
