### ISSUE TITLE
Allow People to Favorite Servers from the Lobby

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3935]
[Feature Request]
Kind of self explanatory. And it makes sense, you'd probably want to favorite a server from inside the lobby after you get to know it.

**Comment by juanjp600** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/bd693ebbb9591b96e066a92df227ae51d595a1c4

**Comment by Rokvach** [comment]
Tested, not sure if the position is the best. But didn't spot any issues with this. closing.
