### ISSUE TITLE
Monsters get into ship bypassing walls

### ISSUE THREAD

**Issue by Arthuriada** [Regalis11/Barotrauma#3938]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes monsters get into ship bypassing walls

**Steps To Reproduce**
N/A. It just happens from time to time since 0.10.5.1

**Version**
Windiws 10
Ver 0.10.5.1

**Additional information**
Seems it happens more often when we play international comany (Russia, German, Chile) due to lags

**Comment by itchyOwl** [comment]
It sometimes happens on single player too, but I believe the issue is more frequent on multiplayer if there's notable lag present.

**Comment by thegrb93** [comment]
I've noticed them moving very erratically in laggy servers including teleporting and moving extremely quickly.

**Comment by FLundin** [comment]
This happens all the time

**Comment by thegrb93** [comment]
Also note this didn't happen in earlier versions.

**Comment by itchyOwl** [comment]
Was there a fix to this issue or not? Or is it unfixable?

**Comment by Rokvach** [comment]
There's another ticket relating to this one #331 this does still happen but it's a lot rarer than what it was when this ticket was created.
