### ISSUE TITLE
SteamP2P clients don't get a proper error message when connecting to a server fails

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3939]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
SteamP2P clients don't get a proper error message when connecting to a server fails. Meaning that if they for example fail to connect due to an invalid name, mismatching content packages or a mismatching game version, the player can't see why they could not connect.

**Steps To Reproduce**
Set something like "/()#"¤%" as your name and try to join a SteamP2P server.
Try to join a SteamP2P server running a different version of the game.
Try to join a SteamP2P server running with a different set of content packages

**Version**
v0.10.5.1

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5163ab465f8943388c527cd6f604a3d64d3e9a41 and https://github.com/Regalis11/Barotrauma-development/commit/8ec10d967bf0679bb0f58d4e724dccc967de93ab

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Regalis11** [comment]
Some more things to test:
- [ ] Connecting to a server without required mods, and checking if the mods can be automatically installed
- [ ] Connecting to a password-protected server
- [ ] Connecting to a server you're banned from
- [ ] Connecting to a server using a name that someone else on the server is already using

**Comment by Rokvach** [comment]
Banning seems to be broken right now as the bannedplayers.txt doesn't save, so will test the last tick when that's fixed.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
