### ISSUE TITLE
Health Scanner HUD can see through disguise

### ISSUE THREAD

**Issue by alkaid7205** [Regalis11/Barotrauma#3942]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can see through disguise if you put on the health scanner and mouse over someone disguised.

**Version**
0.10.5.1

**Additional information**
![ISeeYou](https://user-images.githubusercontent.com/71730359/94482000-4d3c5100-01e1-11eb-8eb9-91f2b2e5e262.png)

**Comment by LuCKySoZ** [comment]
It's not a bug, it's supposed to do that AFAIK

**Comment by Regalis11** [comment]
This is intentional, not a bug
