### ISSUE TITLE
Feature Request: Local Voice Hot Mic

### ISSUE THREAD

**Issue by Blu3wolf** [Regalis11/Barotrauma#3944]
At present, users can select voice chat disabled, voice chat with push to talk, or voice chat with voice activation. In voice activated mode, voice is sent to the radio whenever detected. With the push to talk mode, two push to talk keys are set: one to use the radio, and one to use the local chat (voice heard only nearby the player, rather than using the radio). 

I propose a mode be added which allows the player to have a hot mic (always active) for local chat, and a push to talk to use the radio.

**Comment by ezjamsen** [comment]
This is a good idea, I think we should be able to support it pretty easily.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/bb872e9

**Comment by Rokvach** [comment]
Tested the UI side of the implementation, working correctly there. Rest needs to be tested in the next Unstable.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Blu3wolf** [comment]
Hi guys, coming back to Barotrauma after a break. Has this feature been removed from the game? There appears to no longer be a way to have voice activated local chat, and push-to-talk radio chat.
