### ISSUE TITLE
Dedicated server not using SteamID's for chardata if two players have the same IP.

### ISSUE THREAD

**Issue by Dankshaman** [Regalis11/Barotrauma#3948]
Using the dedicated server software. We have 2 players who are in the same household. Using the dedicated server, they cannot have separate save data as their IP matches, and the server isn't using SteamID as a secondary check, just showing up as 0.

From _CharacterData.xml(without IP and name of course.):

`<CharacterCampaignData name="Name" endpoint="XXX.XXX.XXX.XXX" steamid="0">`

**Comment by juanjp600** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/5689228981bc9da76db3dd23d7a9e789a858d5ef

**Comment by Rokvach** [comment]
Can't be reliably tested internally or with the community, the ticket about being able to view steam profiles in dedicated server however works, so I would assume this one does as well. Closing at least for now, lets see if something comes up when the patch released.
