### ISSUE TITLE
Some meds used with the syringe gun have unexpected effects

### ISSUE THREAD

**Issue by Thirty-Percent** [Regalis11/Barotrauma#3950]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Certain meds have unexpected (OP) effects when shot with a syringe gun.

- **Deusizine** heals burns (1.5/s for 30s) instead of inflicting them
- **Halorperidol** lasts 10 seconds instead of 1 and heals 25 psychosis per second, healing a total of 250 psychosis (against 100 when skill req. is met)
- **Morbusine Antidote** heals Morbusine Poisoning at a rate of 25/s for 30s, healing a total of 750 against 1/s for 30s when unskilled, 100/s for 1s when skilled
- **Liquid Oxygenite** deals internal damage at a rate of 0.5/s against 1/s when unskilled, matching the 0.5/s when skilled value

**Steps To Reproduce**
Use the aforementioned meds with a syringe gun on a character that has the corresponding affliction.

**Version**
0.10.5.1 (Windows)

**Comment by danielasteljoki** [comment]
Fixed in 347f2df.

**Comment by Xeavas** [comment]
[0.1200.0.1] - Tested, working correctly. 👍

**Comment by Rokvach** [comment]
Closing
