### ISSUE TITLE
Suggestion: make relays and pumps turned on by default

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3951]
A lot of players who are new to submarine editor are often asking for help in discord only to find out that their problem is caused by pump or relay being turned off, because they didn't even realise that those things are off by default.

Almost always when relays or pumps are used they are either meant to be permanently on or their state is controlled by other components, so i think it would save a lot of confusion for the new sub builders if those devices where turned on by default right after being placed. Apart from confusing new players, i think that not needing to turn on every pump/relay you place would also be a nice convenience for everyone.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/006a70f2b9fea97ccdd707ec0e4681ea3410e0f1

**Comment by Rokvach** [comment]
No issues, closing.
