### ISSUE TITLE
Vanilla itemassembly "Diving Suit Locker" has wrong scale on oxygen bottles

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3953]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All oxygen bottles placed with "Diving Suit Locker" assembly have 0.3 scale instead of 0.5.
**This includes the bottle inside the diving suit.**
![image](https://user-images.githubusercontent.com/48099798/94686026-83d1b300-032a-11eb-981e-47c57919d54b.png)

**Version**
v0.10.5.1 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/00180380401353eef146bf4be70608e34459ab29

**Comment by LuCKySoZ** [comment]
To be honest, I personally prefer the vanilla scale hahahaha, the 0.5 scale is kinda clipping on the textures of the holder

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
