### ISSUE TITLE
Cannot deconstruct UEX

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#3954]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot deconstruct UEX,  Checked patch notes and it wasn't in the changelog

**Steps To Reproduce**
Try  deconstructing UEX

**Version**
 v0.10.5.1 Release version

**Comment by Regalis11** [comment]
Not a bug, the explosives have never been deconstructable

**Comment by Erars** [comment]
But it was in the previous patch. Deconstructing UEX would get u sodium and phosphorus.
