### ISSUE TITLE
Bots don't place diving suits back in the locker

### ISSUE THREAD

**Issue by dion-perez** [Regalis11/Barotrauma#3956]
- [ x] I have searched the issue tracker to check if the issue has already been reported.
(It seems this was already cleared but it is definitely still an issue in all of the sessions I have tried)

**Description**
The bots don't typically replace diving suits after being ordered to fix a leak, and tend to leave them strewn about the sub. I'm not sure on the exact cause, but reading the previous bug report for this seemed to indicate that a new idle task takes over their task of replacing the suit, so they just drop it on the floor instead? But I'm not too sure.

**Steps To Reproduce**
With a hull breach, order a bot to fix leaks. They seem to end up leaving the suits around on the floor the majority of the time.

**Version**
Running on windows with the latest version of the game.

**Comment by itchyOwl** [comment]
There's some changes to this in the current unstable, but it's intentional that the bots don't spend time on placing the diving suits in lockers when there's something more important to do. With the new cleanup order they should, however, put the things on places when they are in the idle state.

**Comment by itchyOwl** [comment]
Moved the ticket on the QA pipeline for testing. If there's something wrong with it, place it back to the sprint pipeline.

**Comment by Rokvach** [comment]
Didn't find any issues with this, when bots finds diving suits laying around while on idle state they will place them in the correct places. Closing.
