### ISSUE TITLE
Paint loses its color immediately after being sprayed

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3959]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using a Paint Sprayer to spray paint on the walls, it will spray colored paint... until you release the trigger. Then a random amount of the paint nearby will immediately lose its color and go to greyscale

**Steps To Reproduce**
- Grab a Sprayer, put Paint into the Sprayer
- Spray on wall
- Stop spraying

**Version**
Barotrauma Unstable V0.10.600.0

**Additional information**
This happens with all colored paints I tested

![image](https://user-images.githubusercontent.com/6137403/94796697-67dc1900-03df-11eb-86ca-16e9afca71b7.png)
![image](https://user-images.githubusercontent.com/6137403/94796713-6d396380-03df-11eb-850a-aad096839006.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/396e47474089b30a7d86469aca3cdd8113241cef

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore, working correctly. Closing.
