### ISSUE TITLE
Watcher can watch you through walls and all other sight blockers

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3960]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Watcher's affliction Watcher's Gaze seems to apply through walls. The Captain warned me that a Watcher was near the ship (never saw it). Moments afterwards, in a fully enclosed room without windows in the belly of the ship not handling any periscope, my vision went into a big blurry mess

**Steps To Reproduce**
- Spawn Watcher near the ship
- Stay inside the ship without looking at the Watcher outside through windows or such

**Version**
Barotrauma Unstable V0.10.600.0

**Additional information**
I'd assume it would be best if the Watcher only dazed people who actually have it in their sight, natural or periscope, otherwise the Watcher can blind the entire crew and give them catastrophic psychosis by hiding near one of the submarine's walls

**Comment by itchyOwl** [comment]
Yeah, that's the way it's implemented. I don't think we should add visibility checks here, because otherwise you can easily ignore it. The gaze is significantly more effective closer to the watcher. If we wanted, we could add the visibility check there, but that would require a bit of work.

**Comment by dylanstrategie** [comment]
That's fair, I would say it can be pretty jarring though. Without the Captain's warning I would have been totally unable to guess what was happening to me. Hell, the Captain thought I griefed him and injected a toxin in him at first

**Comment by itchyOwl** [comment]
That's partially intentional and a reason why I decided that you can't self-diagnose the gaze either. There are cases where the major effects are applied on you even when you are inside a sub, and at least that's something I'd like to fix.

**Comment by itchyOwl** [comment]
Closing this, because I belive we are not going to do anything about this.
