### ISSUE TITLE
[0.10.600] Dual Wielding Storage Containers doesn't always display content of both containers

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3962]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Dual Wielding Storage Containers, sometimes you can't see both GUI inventory when you start unequipping or reequiping them.

![Capture](https://user-images.githubusercontent.com/5086682/94798579-cf7a7000-03af-11eb-808d-df03d362d11d.PNG)

Only after I dropped them both on the floor and then pick it up can I guarantee to get both to show up.

![Capture](https://user-images.githubusercontent.com/5086682/94798639-e325d680-03af-11eb-801c-347bfac72470.PNG)

**Version**
0.10.600

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a359efff3d346d5458c8e467236acf1caaf7ea3e

**Comment by Rokvach** [comment]
No issues, closing.
