### ISSUE TITLE
[0.10.600] Equipped Toolbelts shows up in the Merchant's sell list.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3963]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Equipped Toolbelts shows up in the Merchant's sell list.

**Version**
0.10.600

**Comment by ekqvist** [comment]
The issue that I see with this is that Toolbelt can only be placed in its own slot (and in hands with #3969). But even after the change, the Toolbelt is automatically placed in its own slot when picked up. So, if selling it from its own slot is prevented, it could not be sold at all unless you are wearing one in its own slot and carrying one in your hands to sell that one.

**Comment by Kaillera** [comment]
Hmm, after playing in this version for a while. I am pretty annoyed that the items in the toolbelts also shows up in the sell list. Having to unequip the toolbelt so that I wouldn't sell my own items is a bit tedious.

**Comment by ekqvist** [comment]
Well, disallowing the selling of items contained inside the toolbelt would make it work the same as other equipment slot items, as you cannot sell those contained items either. I'll have to discuss this a bit with the design, the selling could use some improvements overall, as I've stated before.

**Comment by ekqvist** [comment]
We discussed the issue and thought it would be best to retain the ability to sell items from the toolbelt, but rather try to solve toolbelt and shop related issues by improving the shop interface itself.

**Comment by NyarlathotepZERO** [comment]
I don't mind it so much giving the option to sell your equipped toolbelt. The issue I have, is that given the option of only selling 1 belt of any number higher in your inventory, it will sell your equipped toolbelt before it sells the one from your crate. Not sure if this deserves its own issue though, or if it would tie in with this one.
