### ISSUE TITLE
Mudraptor Ragdoll Crash

### ISSUE THREAD

**Issue by dylanstrategie** [Regalis11/Barotrauma#3965]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Something about the Mudraptor's new animation set is causing a hard crash ingame, which is obviously not great

**Steps To Reproduce**
- Spawn a Mudraptor near the ship
- Do something to cause it to do a specific animation. In that case it seems the Mudraptor had just breached the ship that was sinking downwards really fast, leaving it alone with the bots inside

**Version**
Barotrauma Unstable V0.10.600.0

**Additional information**
![image](https://user-images.githubusercontent.com/6137403/94800521-fef79f80-03e4-11eb-943c-e2cd23e86a90.png)
[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/5311337/servercrashreport.log)

**Comment by Regalis11** [comment]
Even though this was caused by a different monster than https://github.com/Regalis11/Barotrauma/issues/3964, the underlying cause seems to be the same, so I'll mark this as a duplicate
