### ISSUE TITLE
[~0.10.600] Stacking used UEX explodes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3966]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stacking used UEX causes an explosion. This is a common occurrence with the change in exploding ammo recipe consuming 90% instead of the whole item.

**Version**
~0.10.600

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/db3c741 (although technically we didn't fix this particular issue, just made the ammo recipes consume 100% of the item so it should be impossible to get a partially consumed UEX block)

**Comment by Kaillera** [comment]
Deconstructing used exploding ammo box will give you partial ones.

**Comment by Rokvach** [comment]
No issues, closing.
