### ISSUE TITLE
Outpost AI doesn't mind you starting fires

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#3968]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As long as you don't directly harm anyone with your fire weapon of choice, intentionally setting things on fire will not get any hostile reaction from the crew (though obviously they will rush to put the fire out). If you do it in the right spot, the infinite oxygen environment of the Outpost means it will turn into an inferno really fast. Sometimes the AI can't even put it out due to floor separators or an entire room being on fire until it becomes too dangerous to approach

They will also not patrol properly to find fires and ignore cues that are obvious to a real player like the sound of a fire, the glow through walls or it being visible through floors or doors when in a nearby enclosed room

**Steps To Reproduce**
- Start Campaign with Flamer
- Find a room without people in it and start a fire
- Start mor fires
- Watch the crew lose lives stopping it
- Leave with 0 reputation hit

**Version**
Barotrauma Unstable V0.10.600.0. Windows 10

**Additional information**
![image](https://user-images.githubusercontent.com/6137403/94802660-5cd9b680-03e8-11eb-8966-216c2ee84b69.png)

**Comment by juliencsharp** [comment]
I want to add this : Fires can also be started if your submarine is wired in a way that overloads the outpost power grid, which makes it even easier and safer to do.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c050c5442654b387711689171e2fdfb2aeed96e1

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/bc5b699c6ebc4d10587d36afc58160ae16827879

Test procedures detailed in https://github.com/Regalis11/Barotrauma-development/pull/4487

No issues found
Closing ticket
