### ISSUE TITLE
[0.10.600] Feature Request - Picking up Toolbelts with Hands

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3969]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When salvaging corpses, it's a bit annoying that you have to get rid of your own toolbelt to inspect a toolbelt thrown on the floor. At least let us pick it up with hands?

**Version**
0.10.600

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8eb2fbce0ea14b21ca1cda46238635b593a685ae

**Comment by Rokvach** [comment]
Picking up a toolbelt doesn't show your character carrying it in their hands

Also should you be able to access the toolbelts you've picked up? I don't think it makes much sense as your hands are occupied by carrying them. I think you should only be able to pick them up and if you want to access their inventory you would swap the toolbelts in the toolbelt slot.

**Comment by Regalis11** [comment]
Decided to revert the change for now: turns out allowing this is more complex than I thought, because atm the items only take the allowed slots of one Pickable into account, and equipping the item triggers the Equip method on all it's components (and we'd need to do it selectively for either Wearable or Holdable).

Moving back to backlog for now.

**Comment by FLundin** [comment]
I second this this request tho. Its really annoying to move items between belt<->belt and moving a belt into a container without having to take off your own.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/af698f6c0b547254406c4a44f6a1c629915cb4b4

**Comment by Regalis11** [comment]
Merged to dev now

**Comment by Rokvach** [comment]
Tested, only found couple usability issues which I noted down on the diving suit ticket. Closing as this is working correctly.
