### ISSUE TITLE
[0.10.600] Clothless characters are missing Torso when wearing Toolbelts

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3972]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clothless characters are missing Torso when wearing Toolbelts

**Version**
0.10.600

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7bcf914c1a9baf59497be99684dec1a481e87f55

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
