### ISSUE TITLE
[Unstable] Diving suit lights not working (StatusEffect that have multiple target types only check the "This" target in conditionals)

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3973]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have a status effect that targets This and some additional types of targets, the conditionals ignore the other targets.

**Steps To Reproduce**
Wear a diving suit: the light has a conditional that turns the light on when the wearer is alive, but it no longer works correctly. May affect other items as well.

**Version**
v0.10.600.0

**Additional information**
Caused by https://github.com/Regalis11/Barotrauma-development/commit/cc24a30

**Comment by hubismal** [comment]
this is going to be high prio for modders everywhere. half of the things don't work in my mod now.

**Comment by itchyOwl** [comment]
I'll revert it and look into other ways to fix this.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@e05b29e: Characters now trigger OnActive status effect when they are alive and conscious, and we use this for the Watcher's Gaze.

**Comment by Rokvach** [comment]
Not sure if its strictly related to this fix, but the diving suit oxygen low alarm doesn't follow the player but instead is world position based.

**Comment by Rokvach** [comment]
I didn't notice any issues, seems to be working correctly. Closing.
