### ISSUE TITLE
[0.10.600] Bots detaches placed electrical components for their Clean Up order/idle order

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3974]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will detach placed electrical components for their Clean Up order/idle order.

**Version**
0.10.600

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@c76b8a2

**Comment by Kaillera** [comment]
Also affects Planter Box.

**Comment by Rokvach** [comment]
Wasn't able to reproduce this issue anymore, working correctly. Closing.
