### ISSUE TITLE
Gaps to Ruin/Cave Artifact can be super tiny

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3975]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Gaps to Ruin/Cave Artifact can be super tiny. You need to use a scooter and ragdoll button to fit through these usually.
![](https://cdn.discordapp.com/attachments/668819422919524352/736276535484612648/Capture.PNG)

**Version**
~0.10.4

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/tree/feature/level-overhaul

**Comment by Rokvach** [comment]
Should be handled with the upcoming new level generation, but something to keep an eye out still during testing. Doubt it will be an issue anymore so closing this ticket.
