### ISSUE TITLE
Give ParticleEmitters Offset Values That Account For Rotation

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3980]
Self explanatory. Would be great if particleemitters were able to offset where they emitted particles from, relative to the origin of an item.

**Comment by itchyOwl** [comment]
Actually there is an offset for status effects, but if I remember correctly, it doesn't take rotation into account. See fleshspike1 in thalamusitems.xml.

**Comment by hubismal** [comment]
thanks, i'll check it out.

**Comment by itchyOwl** [comment]
I think we should consider changing the behavior so that it takes the item rotation into account, if it already doesn't. It's a low prio thing anyway, unless we need it for something.
