### ISSUE TITLE
Add Escape key as an option to skip the intro splash videos.

### ISSUE THREAD

**Issue by someone972** [Regalis11/Barotrauma#3982]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My burned-in habit for skipping the intro splash screens in games is to press the Escape key. I noticed that this game only supports space/enter/click for skipping. This seemed like a simple change for me to make as a first pull-request. That way I can fix my minor annoyance and get familiar with the dev/pull-request process.

**Steps To Reproduce**
Press escape during the intro splash videos. Video will not skip.

**Version**
v0.10.5.1 Windows

**Additional information**
N/A

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/592869cb29fb93dff987dfc353fcea125354cf4e

**Comment by Rokvach** [comment]
No issues, closing.
