### ISSUE TITLE
Outpost events can still trigger when everyone is unconscious/dead

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3984]
Was left as a comment on the community testing document.

Looks like its mainly events which doesn't require any NPC or Item to trigger. 
> If everyone is in a critical state or dead(untested) on an outpost, events such as a note being slipped into your pocket can still occur, as if the person was still conscious.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a064a123d0e0ea4962d474016271e0ba5f5de077

**Comment by Xeavas** [comment]
[0.1100.0.5] - Tested in singleplayer, unable to replicate 👍

![testtrigger](https://user-images.githubusercontent.com/72674994/98858333-651f1a00-249b-11eb-841b-394b60f7d273.jpg)

**Comment by Xeavas** [comment]
[0.1100.0.5] - Tested in singleplayer, unable to replicate 👍

![trigger_test](https://user-images.githubusercontent.com/72674994/98859058-8df3df00-249c-11eb-9baa-ad496fffd377.jpg)

**Comment by Rokvach** [comment]
Closing.
