### ISSUE TITLE
Crash when using VoiceMeter as audio device

### ISSUE THREAD

**Issue by ottoh-commits** [Regalis11/Barotrauma#3987]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes I stream my gameplay to my friends on my living room TV. I use VoiceMeter software so the sound will come from my headphones and from the TV. The game starts with a error report on the console. The game has switched the audio device to only for my headphones. After when I switch the audio device for VoiceMeter the audio works on the main menu. After that when I try to launch the game, the game crashes. Crash report as attachment. 

VoiceMeter software can be found here: https://vb-audio.com/Voicemeeter/

**Steps To Reproduce**
1. Start VoiceMeter
2. Start game
3. Change audio device back to VoiceMeter in game.
4. Launch any scenario (tutorial, campaign)

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
OS: Windows 
Version: 0.10.5.1
**Additional information**

Streaming to TV using Steam Link.

[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/5320121/crashreport.4.log)

Also I don't know who is Joonas, that name came up on my crash report :) 

   _at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23_

**Comment by Regalis11** [comment]
The following line seems to imply that your serversettings.xml file has gotten corrupted somehow:
> Couldn't load xml document "serversettings.xml"! {Root element is missing.}

You should try running "verify integrity of game files" to fix the file. In your Steam Library, right-click on Barotrauma on the list and select ’Properties’ from the menu. Select the Local files tab and click the ‘Verify integrity of game files…’ button.

I'm not 100% sure that'll fix the issue - it could be that the file failing to load prevented others things from being initialized as well, or it could be an unrelated issue. In any case, I added some additional checks in https://github.com/Regalis11/Barotrauma-development/commit/09b02e5d22a85d2fe48a0eca035b8567881c4514 that should prevent this from crashing the game when it occurs.

**Comment by Rokvach** [comment]
No issues, closing.
