### ISSUE TITLE
Revolver costs less than ammo for the revolver

### ISSUE THREAD

**Issue by flipflop-ok** [Regalis11/Barotrauma#3992]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by danielasteljoki** [comment]
Might be fixed already. Prices are correct for me.

**Comment by Rokvach** [comment]
It is intentional that 6 rounds costs more than a single revolver as the cost of ammo is meant to be high. Closing.
