### ISSUE TITLE
Replace Character functionality

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#3997]
While modding the game, I noticed that currently you cannot _properly_ replace a character in-game with another character, the most you can do is deleting a character and spawning another one in its place. This method _does_ do a good job for the most part, however it has one flaw in particular, which is the fact that the original character's inventory is entirely lost due to the original character being removed. This could be fixed by creating a new function that is neither `<SpawnCharacter/>` or `<RemoveCharacter/>`, but `<ReplaceCharacter/>`.

It should be a function that does exactly what the **[husk infection](https://github.com/Regalis11/Barotrauma/blob/20a69375ca605688ac68f26f82f2635930141d3b/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionHusk.cs)** _already does_ (replacing a character with another one), including the part where **[the previous character's inventory is moved to the new character's inventory](https://github.com/Regalis11/Barotrauma/blob/20a69375ca605688ac68f26f82f2635930141d3b/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionHusk.cs#L192)**.

The function would look something like this:
`      <ReplaceCharacter speciesname="NewCharacter" transferinventory="True"/>
`
It would remove the Character targeted by the Status Effect, and automatically spawn the Character defined in the "speciesname" variable in its place, as well as moving (or attempting to move) the inventory of the previous character to the new character if the "transferinventory" variable is set to true. 

In addition, there could be other variables tied to it, which could be implemented later on to expand the possibilities of the replace functionality:
- transfername="true"/"false" - Should the new character have the same name as the previous character?

- stuntime="0" - How long should the new character be stunned for after replacing the previous character?

- transferafflictions="true"/"false" - Should the new character have the same afflictions (such as damage, bleeding, etc) as the previous character?

- excessitemsmode = "delete"/"drop" - Should excess items (items that don't fit in the new character's inventory if "transferinventory" is set to true) be deleted or dropped on the ground?

- transfercontroller="true"/"false" - Should the player controlling the previous character be put in control of the new one?

- savecharacter="true"/"false" - If true, the new character will save an exact copy of the previous character, which includes its job, traits, skills, current afflictions, inventory, etc. 
If the previous character already had a saved character and this variable is set to false, the saved character's data will transfer over to the new character, else it will be overwrited with new data.

- loadcharacter="true"/"false" - If set to true, the entire function will ignore the "speciesname" variable and read the saved character's data contained in the current character and attempt to spawn it.

I believe it should be relatively easy to repurpose the husk infection's code to be usable as the new function described above that can be used in XML modding/coding, and having such a function would open up a lot of possibilities for interesting monsters, afflictions and items.

**Comment by hubismal** [comment]
> transfercontroller="true"/"false" - Should the player controlling the previous character be put in control of the new one?
this would be extremely powerful and a big boon to modding
