### ISSUE TITLE
Cannot unlink hulls

### ISSUE THREAD

**Issue by Phrosperatus** [Regalis11/Barotrauma#3999]
- [x] I have searched the issue tracker to check if the issue has already been reported. (all previous reports are closed)
Also asked in discord, someone tested, hes been unable to unlink hulls on unstable branch too.

**Description**
Cannot unlink hulls.

**Version**
v0.10.5.1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Phrosperatus** [comment]
Hi!
I'm sorry for bothering you again with this.

If it's working on stable branch v0.10.5.1 then may you please tell me how to unlink hulls?

I tried to unlink hulls by clicking on a linked hull's blue line to select it, then space + left mouse click on the other linked hull's blue line (same thing when linking them together).
I tried space + right click, it doesn't unlink, but the normal right click menu appear.

Thank you in advance.

**Comment by Rokvach** [comment]
This fix is part of the next upcoming patch 0.10.6.0.

**Comment by Phrosperatus** [comment]
Thank you for taking your time to respond, for the information and for developing Barotrauma.
