### ISSUE TITLE
Error when trying to load a singleplayer campaign save

### ISSUE THREAD

**Issue by OdinGameplays** [Regalis11/Barotrauma#4005]
[durantes.zip](https://github.com/Regalis11/Barotrauma/files/5332176/durantes.zip)

**Description**
Whenever I try to load a campaign save in singleplayer, the "Press any key" message pops up and after doing so, the main menu shows up with the console open and some red error lines explaining exceptions when loading the game had happened. This problem first started with my previous save, which I found odd since there was no other person with the same problem after doing some research on it, but I thought of it as a corrupted save and proceeded to create a new campaign. I could save and load normally for 2 days until this night I started Barotruma up, hit up my save and the error showed once more. I really wouldn't like loosing my save, so I'm looking for some help here. Thanks in advance!

**Version**
v0.10.5.1
![Console 1](https://user-images.githubusercontent.com/29028721/95053085-512b1000-06c6-11eb-91a3-671456e0e596.png)
![Console 2](https://user-images.githubusercontent.com/29028721/95053093-525c3d00-06c6-11eb-80e6-5e77b24989e9.png)
![Console 3](https://user-images.githubusercontent.com/29028721/95053095-52f4d380-06c6-11eb-9885-808f10832c43.png)
![Console 4](https://user-images.githubusercontent.com/29028721/95053097-538d6a00-06c6-11eb-8b49-e80b47f05bfb.png)

**Comment by Regalis11** [comment]
Hello and thank you for the report!

I can't think off the top off my head what could be causing this, although I suspect it could be related to leaving drones/shuttles behind if you were playing with a sub that includes a drone/shuttle (or some other detachable parts). Would it be possible to send us the save file so we could investigate this further?

Thanks and sorry for the trouble!

**Comment by OdinGameplays** [comment]
Sure! I'm new to Github though, so I really don't know how to, but if you could guide me a little I would!

**Comment by Regalis11** [comment]
GitHub only supports attaching certain types of files to posts, and unfortunately Barotrauma's save files are not one of them, so you need to .zip the file first and then click the "attach files by dragging and dropping, selecting or pasting them" text below the message field.

**Comment by OdinGameplays** [comment]
Firstly, I forgot to tell you the first time but I really appreciate the almost immediate responses. I've been loving every single bit of the game and I would love to keep doing so, so thank you! Now you should be able to see the zip file with the save named "durantes" in the top part of the post!

**Comment by Regalis11** [comment]
Looks like we already had another ticket about the same issue (https://github.com/Regalis11/Barotrauma/issues/3459), closing this one.
