### ISSUE TITLE
Suggestion: Better difficulty nomenclature

### ISSUE THREAD

**Issue by veborich** [Regalis11/Barotrauma#4011]
The "easy", "medium", "hard" nomenclature does not fit conventional norms in gaming and is likely turning many new players off the game very quickly.  A typical gamer will play a new game on "Normal" or "Medium" and expect it to be challenging but winnable with practice.  Many players go right into the game hosting and running 50% servers with vanilla Dugong and Humpback.  Even the high-end vanilla ships are not ready to survive at 50% with no upgrades.

I understand the % difficulty is mirroring the campaign difficulty, which starts at 0% and gradually increases as you delve deeper into the biomes.  But this is not clear at all in Multiplayer Mission lobbies.  Even explaining it just gets met with skepticism and unmoving pride at the idea of dropping to a lowly 0-10% difficulty.

I would recommend adding suggested difficulty levels for each of the vanilla ships, dropping the "easy" and "medium" labels altogether, and consider creating versions of the vanilla ships with simulated campaign hull and weapons upgrades to provide the appropriate challenge on higher Mission difficulty modes.

**Comment by itchyOwl** [comment]
I don't this ticket is relevant anymore.

Not sure when this was last changed, but currently:
0-24% is easy
25-49% is medium
50-74% is hard
75-100% is hellish

To me those are pretty descriptive and fairly accurate,  although the difficulty of the random monster spawns are a bit fine-graned than that (and some things are much more coarse).
