### ISSUE TITLE
Notice Board and Shop Cashier Desk Sprite issues

### ISSUE THREAD

**Issue by KeklMcgekl** [Regalis11/Barotrauma#4012]
- [✓ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Sprites for the Notice Board and Shop Cashier Desk have incorrect heights and widths causing other objects to bleed into them

**Steps To Reproduce**
Place the Notice Board and Shop Cashier Desk from the decorative tab in the sub editor

**Version**
v0.10.5.1 Stable Windows

**Additional information**
Verifying the integrity of the game files does nothing,
![Spriteissues](https://user-images.githubusercontent.com/72420953/95145520-08646d00-0741-11eb-8ccd-e005c35609dd.png)

**Comment by dinhtuananhfakefish** [comment]
Fixed

**Comment by ekqvist** [comment]
We'll keep the issue open until we've reviewed it internally, thanks!

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
