### ISSUE TITLE
Index was outside the bounds of the array / ENTITY_POSITION crash (following interaction with toolbox and crate during multiplayer combat)

### ISSUE THREAD

**Issue by CP44** [Regalis11/Barotrauma#4013]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description / Basic Steps To Reproduce**
Game crash in multiplayer, in combat, directly following the moment I picked up a toolbox from a metal crate.  Everyone except the host was disconnected.
Host was a player via Steam (not dedicated server); all other players joined through Steam as far as I know.
Sorry that's minimal, I know.

This text was found in crashreport_object.log while looking for crashreport_object.bin mentioned in the F3 log.

> Index was outside the bounds of the array.
> Message length: 3869 (483 bytes)
> Read position: 3869
> Header: ENTITY_POSITION
> Previous header: ENTITY_POSITION
> Previous object was 144 bits long (18 bytes)

Possible related tracked objects that did not appear to be duplicates:
#3927 references ENTITY_POSITION, but we did not have a drone in play.

ENTITY_POSITION is the header mentioned in #2382, Kaillera's attached crashreport_object.log from Jul 18, 2020; not the original topic.

**Version**
v.0.10.5.1 release 9e259b2148 via Steam
My client OS: Windows 7 x64, other users on Windows 10, host was a player in Steam using Windows 10 x64; and at least one other client was known to be Win 10 x64.

**Collected log files**
[crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5331395/crashreport_object.log)

[Sorta deep-sea crusade_2020-10-06_0002_fromPika.txt](https://github.com/Regalis11/Barotrauma/files/5331396/Sorta.deep-sea.crusade_2020-10-06_0002_fromPika.txt)
[Sorta_deep-sea_crusade_2020-10-06_0007_2_fromRah.txt](https://github.com/Regalis11/Barotrauma/files/5331397/Sorta_deep-sea_crusade_2020-10-06_0007_2_fromRah.txt)

**Campaign files that led to this adventure**
[Deepsea_Conquest.zip](https://github.com/Regalis11/Barotrauma/files/5331440/Deepsea_Conquest.zip)

**Additional information**
With the original player who was hosting, we would get failures to join/spectate, normally with an error for a missing entity and an alien artifact holder.  As a workaround and reliability test, we sent the files to Rah. 
Playing with the transferred campaign files has been mostly stable.  During tonight's game before the crash that kicked everyone but the host, someone who joined the game in progress was denied entry due to a missing entity: Pika  (my player name).

In case player permissions are relevant or change the console expectations:
> Host: Rah'Kalesh
> Admin: Pika
> Admin: Captain Z

Let me know if there are other files to round up or debug modes to use!

**Comment by CP44** [comment]
#3019 "Error while reading a message from the server (Index outside bounds of array)" might be the main tracker for the overall error text, but the header value and versions were initially different.  By the time of Coryf88's recent attachment, it looks about the same as tonight's error:
_Originally posted by @Coryf88 in https://github.com/Regalis11/Barotrauma/issues/3019#issuecomment-697025918_
v0.10.5.1 [crashreport_object.log](https://github.com/Regalis11/Barotrauma/files/5264427/crashreport_object.log)

Sorry if this is a duplicate or 3019 evolved into what we saw here

**Comment by Regalis11** [comment]
The underlying bug is most likely the same as #3019, and it's better to keep the information in one place, so I'll close this one as a duplicate. But in any case, thank you for a very descriptive report, this info and the logs should make the issue easier to diagnose!
