### ISSUE TITLE
Bots cleanup Mudraptor eggs while the egg is still in item form

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4015]
Mainly a issue if you want to hide a egg and a bot comes by and places it inside a cabinet.

**Comment by ekqvist** [comment]
Should be addressed with Regalis11/Barotrauma-development@7d1a081 and Regalis11/Barotrauma-development@0ca41a9. Bots should now always ignore mudraptor eggs.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
