### ISSUE TITLE
Spotted some Mudraptor egg issues

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4016]
Noticed couple issues while recording a new Mudraptor gif for the Steam page.

- [x] The egg resizes downwards on the second to last stage, so the egg gets bigger than it should in that stage and then scales down to the actual size when that stage has finished. 

- [ ] When a Mudraptor hatches from an egg all the surrounding walls around the egg breaks immediately upon hatching. Not sure if the Mudraptors just breaks the walls so fast or what exactly happens there.

**Comment by Regalis11** [comment]
Couldn't repro the second issue. Does it happen consistently or was it a one-time occurence?

**Comment by Rokvach** [comment]
I placed 4-5 eggs next to each other and let them hatch almost at the same time. I think its some new behavior of the Mudraptor itself as I didn't encounter it when I did the same with the old Mudraptor

You can briefly see it in this gif I recorded yesterday, you can also notice that the ballast wall gets broken through with a single hit from a Mudraptor as well towards the end of the gif, so doesn't seem to be related to the eggs themselves @Regalis11 
![MudraptorNew.gif](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0a9412a1-20fb-473f-a6db-fd2724cafd55)

**Comment by Regalis11** [comment]
Seems to happen because the mudraptors can attack the wall immediately after hatching, I wouldn't consider that a bug

**Comment by Rokvach** [comment]
No issues, closing.
