### ISSUE TITLE
[Request] Increase searchlight's max camera zoom/view range up to railgun's max camera zoom/view range

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#402]
I wanted to make railgun connected to a searchlight and control both of them with one railgun controller, like this:
![railgun range](https://user-images.githubusercontent.com/38168249/39755545-6ff293e6-52f0-11e8-88e1-e9189bdebd5f.png)
It looks nice and is really useful when you are playing alone and have nobody to control searchlights for you when you are using railguns.
But it appears that in some cases (for me it usually happens after loading a save) when you are controlling them, railgun controller decides to prioritise controlling the searchlight and that makes your max camera zoom/view range turn into this:
![searchlight range](https://user-images.githubusercontent.com/38168249/39755699-0b89ae70-52f1-11e8-9458-93aa197b06c3.png)
Which makes fighting dangerous creatures from long ranges harder.

Can you increase searchlight's max camera range if it's not too hard? I don't think it would harm anybody or make searchlights overpowered.
It's just a personal request so if you don't want to do that, i will have no problems with that and will just go back to using lamps.

**Comment by juanjp600** [comment]
Already implemented in https://github.com/Regalis11/Barotrauma/commit/d0c1d170f335fb7308a3a843f8c4a81dcde1bea2, it should be available in the next update.
