### ISSUE TITLE
Custom locationtypes with outposts cause crash during campaign

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4020]
[Modding, Crash]
[crashreport (119).log](https://github.com/Regalis11/Barotrauma/files/5336893/crashreport.119.log)
[crashreport (120).log](https://github.com/Regalis11/Barotrauma/files/5336894/crashreport.120.log)
[crashreport (121).log](https://github.com/Regalis11/Barotrauma/files/5336895/crashreport.121.log)
Unsure what i'm doing wrong. The outpost type generates fine in the level editor so it's probably not level generation. If you want to reproduce this yourself just download Thalassophobia on the workshop, start a campaign and use campaign teleport to teleport to a "classified site" (with a radioactive symbol).

**Comment by Regalis11** [comment]
This seemed to happen when there were no event sets configured for a specific location type (in this case the classified site). Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c50d3ce54e86e6556161016c6d0aae450df35441

**Comment by Rokvach** [comment]
Tested by using the steps provided above, didn't encounter any crashes. Works correctly. Closing.
