### ISSUE TITLE
Storage container issues

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4022]
- [x] When holding two storage containers and you swap them in your hands, the storage container you swapped is placed in-world and can't be interacted with

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/336098c6-d7a9-413e-af40-52d0c2b47ea9)

- [x] If you then drop the storage container after swapping and pick it up again, the storage container is going to be placed in the same hand as your other storage container.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/56d9c5c9-3d1e-44d6-ac8e-2d21a410fdc3)

- [x] The storage container in your back hand isn't positioned correctly to match with the arm position when walking or running (Issue might not be related to the storage container alone, but really noticeable with it)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b122f6a4-26d0-408f-b28e-73bc93a52fdf)

**Comment by Bozhdynsky** [comment]
In 0.10.601 if wielding both containers You still can't drag away the container inventory from one another, nor choose which containers' inventory to pop up.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
