### ISSUE TITLE
Can't loot a creature by double-clicking the item from their inventory, only allows dragging and dropping

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4024]
Tried to loot a Mudraptor by double-clicking the loot, only received a inventory warning sound.

**Comment by Regalis11** [comment]
Could not reproduce. What exactly were you trying to loot, and could it be the slots the items should've gone into were already taken?

**Comment by Rokvach** [comment]
I was trying to loot a Mudraptor during sandbox multiplayer session, I was a engineer so only had the items from the toolbelt in my first 3 inventory slots.

**Comment by Regalis11** [comment]
Couldn't repro in multiplayer either. Which item were you trying to loot?

**Comment by Rokvach** [comment]
The Mudraptor only had a Hydroxyapatite, but I'm not sure if someone else also had the Mudraptor grabbed as multiple players can grab the same creature and there were 3 players surrounding the Mudraptor at the time.

**Comment by Regalis11** [comment]
No known steps to repro, closing
