### ISSUE TITLE
Pet eating a corpse throws a error if the character they are eating is missing a head limb

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4025]
For example if a player dies and only their torso is left behind, it will show a error for each time the pet tries to eat it

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/292bee76-11e4-4f75-aba4-2cb26185e65d)

**Comment by Regalis11** [comment]
This doesn't seem to be related to the character they're eating, was caused by the pets not having a head limb defined. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/014b895

**Comment by Rokvach** [comment]
No issues, closing.
