### ISSUE TITLE
Unstable - Item recursion; toolbelts can be placed in duffel bags

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4028]
Unstable v0.10.601.0

Duffel bags do not have an excluded item filter, so toolbelts can be stacked inside of them for massive recursive item storage.

**Comment by Regalis11** [comment]
This also applies to all crates. We decided not to change it: it's a lot of trouble to stack toolbelts in a mobile container like this, and someone wants to go through all that trouble for some extra inventory space, we don't see it as a huge problem.
