### ISSUE TITLE
Unstable - Projectile impact particles appear in the center of walls & doors instead of point of impact.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4032]
**Unstable v0.10.601**
Hitscan projectiles - such as Revolver and SMG - create their impact spark particle effects at the centerpoint of whatever structure or door they hit rather than the actual point of impact.

Particles appearing in the center of door.
![image](https://user-images.githubusercontent.com/55356135/95423190-ace7da00-090e-11eb-90c0-e47ea9bd45cb.png)

Particles appearing in the 'center' of scalable structure wall.
![image](https://user-images.githubusercontent.com/55356135/95423280-d30d7a00-090e-11eb-99b0-727017c2de36.png)

May be related to recent changes to particle offset behavior?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa45ab89b0f05109037588609f4d711ef5bfda8a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
