### ISSUE TITLE
[Unstable 10.601] Sub Editor: Wiring Mode - No wire holding animation after connecting a wire to a node

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#4036]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is no wire holding animation after you connect a wire to a node.

**Steps To Reproduce**
- enter Sub Editor
- enter Wiring Mode
- select a wire and connect the end to a node
- close the item/component's wiring U.I.
There will be no wire holding animation indicating that you have connected 1 end of the wire

**Version**
0.10.601.0
Windows

**Additional information**
It seems to just be the holding the wire animation not activating, as you can complete the connection if you open another wiring UI....the other end of the wire appears as it should

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f2261023f2d7c125a9c7b91a37c0e66612d3529b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
