### ISSUE TITLE
AI bypass pick required

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#4037]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI/Bots can bypass pick required for secure steel cabinet (maybe other pick required containers like toxin cabinet too?)

**Steps To Reproduce**
place bandages/morphine in a secure steel cabinet. set pick required to be something different than default. Injure the AI and they will fetch the medical supplies they need from the locked container.

**Version**
Win10 v0.10.5.1

**Additional information**
None

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9db7150b8d5711822bab385d6404accf299c346c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing
