### ISSUE TITLE
Dugong cabinets contain useless items

### ISSUE THREAD

**Issue by Hawk777** [Regalis11/Barotrauma#4038]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Dugong has a medium steel cabinet amidships containing flash powder, phosphorus, steel bars, copper, plastic, sodium, and chlorine. However, neither the Dugong nor a city contains a fabricator, so these items are useful for nothing but selling (or perhaps painstakingly carrying to a new boat once you buy one).

**Version**
0.10.5.1 for Linux

**Comment by Kaillera** [comment]
Outposts occasionally do have only the fabricator.

**Comment by Hawk777** [comment]
OK. The three I have seen didn’t, so I assumed outputs in general didn’t. This can be closed if that’s not the case (although I won’t do so immediately in case someone things it’s still worth changing).

**Comment by danielasteljoki** [comment]
The plan is to make fabricators more common in outposts, which would make crafting materials more useful even when using subs that don't have fully fitted crafting compartments. Closing this one.
