### ISSUE TITLE
Make cheaper initial submarines leave you with more marks in your wallet

### ISSUE THREAD

**Issue by Hawk777** [Regalis11/Barotrauma#4039]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Starting the game, I always have 2500 marks. This is the case even if I choose to start with a cheaper submarine than the Dugong. It would make sense that if I spent less money buying my first boat, I should have more left over.

**Steps To Reproduce**
Create a custom submarine that costs less than 6000 marks. Start a single-player campaign and choose that submarine as the initial one. Visit a merchant and see that you still only have 2500 marks in your wallet.

**Version**
0.10.5.1 for Linux

**Comment by ezjamsen** [comment]
This sounds reasonable. Rather than a static starting wallet of 2500 marks, let's have a starting wallet of 8500 minus the price of the starting sub.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/35819ed97f1dcbba7bcc55843a9cfe17eead01d5

**Comment by Rokvach** [comment]
I think we need to display the starting balance to the player if they decide to pick a more expensive sub at the start

For example now that you can pick Humpback as your starting sub you are only left with 700 Mk and you can only see that when you start the game and go to one of the outpost services, which I think is a bit too late. 

Might even be good to display how much marks you actually do have at the start. 

Not a mockup
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b97d11c8-10c5-4a30-866a-a51b1d0ea70d)

**Comment by Rokvach** [comment]
Moving back to todo for further evaluation.

**Comment by Regalis11** [comment]
We have another ticket about communicating the balance/price (https://github.com/Regalis11/Barotrauma-development/issues/2259), I think this one can be closed

**Comment by Rokvach** [comment]
Closing as it otherwise works correctly.
