### ISSUE TITLE
Something is wrong with creatures' (primarily mantis) mass balance.

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#404]
First thing i noticed is that only human, human husk, husk and mantis have mass. Other creatures don't have it set for some reason. Probably planned to be set in the future?
But the main problem is that the way mass is being spread over ragdolls seems to be not working very well.
2 mantises lying on their shells on top of a sub are enough to make a sub of this size start going down slowly despite autopilot using full power to make it go up.
![mantises lying on their shells](https://user-images.githubusercontent.com/38168249/39815184-6d7cf38c-53c1-11e8-8b6c-2df4368dde51.png)
But, for some strange reason, when mantises are lying on their legs, the sub's autopilot has no problem holding the sub in place
![mantises lying on their legs](https://user-images.githubusercontent.com/38168249/39815745-425ba9ee-53c3-11e8-9793-a9e890ae7253.png)

**Comment by Regalis11** [comment]
I don't think this issue has anything to do with mass (all creatures do have mass), it's probably the collider of the character being corrected towards the position of the ragdoll, pushing the submarine down.

**Comment by BillCombs** [comment]
Oh, okay. I just did not see mass being mentioned in other creatures' code so i thought they did not have it.
