### ISSUE TITLE
Barotrauma 10.601.0 - Request to remove Peanuts.

### ISSUE THREAD

**Issue by TijuuanWit** [Regalis11/Barotrauma#4041]
Greetings. Straight to the point. Adding pets is an interesting idea. But with the addition of Peanuts, this is already too similar of SCP as if you wanted to link two different universes - Barotrauma and SCP. This creates the horror component of the game and the perception of it. Maybe you shouldn't do such a thing and remove this creature outside of Barotrauma?

**Comment by Regalis11** [comment]
>  But with the addition of Peanuts, this is already too similar of SCP as if you wanted to link two different universes - Barotrauma and SCP. 

This is precisely the point: it's a sort of easter egg referencing SCP. A lot of Barotrauma players have played SCP - Containment Breach and we thought it would be a fun little nod to our earlier game and it's fans.

> This creates the horror component of the game and the perception of it

I would argue the game already has a horror component, and that the cute little SCP slug doesn't really add much to the horror if you compare it to some of the other monsters in the game.

So I'm sorry to say but we'll keep Peanut, although it won't be a super common thing and you can simply not buy it's eggs if you don't want any in your sub.
