### ISSUE TITLE
Setting MaxPlayers does not apply the change.

### ISSUE THREAD

**Issue by ven** [Regalis11/Barotrauma#4045]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When setting the maxplayers key in serversettings.xml, or entering it as a console command after the server starts (`maxplayers 64`), the max player count does not change.

**Version**
Linux Dedicated Server - 0.10.4.0

**Comment by EdusFF** [comment]
The maximum amount of players a server can have is limited to 16. The command however doesn't inform you of that and tries to set the player amount to whatever you put in, just to be constrained to the limit by the server.

**Comment by EdusFF** [comment]
Added feedback messages in: https://github.com/Regalis11/Barotrauma-development/commit/2ae2a316c5c5ff27d743c48ce5a785e4bb9a04b3

**Comment by ven** [comment]
Thanks for letting me know. How is it possible then for some servers to go past 16 players? I still have this constraint on my own server.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

Some servers are able to go past the limit as they have bypassed the limitation by modding the game, as if you only mod the server side of the game clients doesn't need to download anything in order to play on the server.
