### ISSUE TITLE
[Bugs?] and other issues with some Traitor Missions

### ISSUE THREAD

**Issue by KennyNathan** [Regalis11/Barotrauma#4047]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I encountered bugs/issues regarding the 3 Traitor Missions. These were only found while playing in my own server with bots on. I haven't encountered all Traitor Missions in servers with actual other players and when I did, I died too early on to even notice anything weird, so idk if any of these apply to the actual Multiplayer aspect.
- Easter Bunny: this Mudraptor Egg Mission has a little typo, maybe. The goal says: "See to it by any means that the mudraptor survives for at least 3 minutes." when in the TraitorMissions.xml, the duration is 120. 
- Acid Party: this one where the Traitor looks for a Deliriumine (or a Toolbox of Deliriumine if there are 2 other players/bots besides the Traitor on board) in 3 possible locations (Loose Vent, Loose Panel, or Toxin Cabinet) to inject everyone on board has a strange bug. Because of the nature of this Mission where the number of Deliriumine given is equivalent to the number of submariners besides the Traitor, regardless of where the poison is located, if there are more than 6 other players/bots on board, only 1 Toolbox spawns. A Toolbox now only has 6 slots as of v0.10.5.0, so the result is all the extra Deliriumine will spawn outside of the container lying on the ground. At first I thought it was only because of Loose Vent and Loose Panel since they only have 1 slot, but when the Toolbox spawns in a Toxin Cabinet with many unoccupied slots, the issue persists. Imagine having maximum 16 bots in the game and 10 of those poisons are on the ground. Even if Toolbox still had 12 slots, that'd still be 4 extra on the ground.
- Trap (Crawler Liver): this one where the Traitor needs to sabotage the engine and then "supposedly" kill whoever comes to fix it, which would normally be a Mechanic. But in the xml, there's only the killtarget, but no job specified line. This means anyone can be a target. I tested many times, killed the Mechanic then it turned out the Guard was the target, ordered a random Guard bot to fix the engine, killed him and turned out the Doctor was the target, etc. idk if this one is intended or not since the final goal says: "Inspect the crew's livers. Find one that resembles a crawler's.", which I assume implies that the Traitor has to find the right one, meaning they gotta pretty much kill everyone until the right chosen target is eliminated.

**Steps To Reproduce**
- Easter Bunny: I guess just fix that line in the Text.xml, 3 to 2. I wouldn't suggest actually increasing the duration to 180. Sounds too rough.
- Acid Party: Maybe just spawn half of the poisons since each unit has 2 doses (I know you can use the Syringe Gun to shoot these, which uses up the whole poison, so this may make the Mission harder), so one Deliriumine is good for 2 players. That still leaves 2 extra on the floor. So maybe just change the goal type to injecting a maximum of 12 random people if there are more than 12 players (6 poisons in 1 Toolbox, each unit for 2 people). Or, number of poisons = number of players still, but somehow allow for spawning multiple Toolboxes if there are more than 6 people and so on, tho that means multiple Toolboxes will only spawn inside the Toxin Cabinet since Loose Vent and Panel only have 1 slot.
- Trap (Crawler Liver): I think the most optimal solution is to somehow tag whoever comes to repair the engine (either as soon as they interact with the engine through Repair action or they must finish repairing it) as the target to kill for the Traitor. Otherwise, having to randomly guess the correct target and kill them is a bit over the top.

**Version**
v0.10.5.1 Windows

**Additional information**
I'd like to mention, Easter Bunny seems to be the only Mission that can fail and be canceled (Egg destroyed, Mudraptor dies before 2 min mark) during the round and the Traitor will get assigned a different Mission (idk for sure, I only got these info from playing with bots mostly). Maybe the same should go for Acid Party (Deliriumine) and One of Us (Husk Eggs), basically Missions that spawn certain items, as in for Acid Party if the Traitor uses up all Deliriumine/gets them destroyed but hasn't injected everyone, and for One of Us if the Husk Eggs gets destroyed and no one is infected, the Mission gets canceled.

**Comment by ezjamsen** [comment]
Traitor system (and its missions) will be redone at some point this year. @Regalis11 should this be moved out of the backlog?
