### ISSUE TITLE
Docking Port and Docking Hatch Repair Issues

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#405]
Issue in doors.xml

The repair requirements for a Docking Port is construction 60 while repairing a Docking Hatch is construction 60 and electrical engineering 40. 

Engineering requirement likely missing from the Docking Port or extra on the Docking Hatch. 

60 construction requirement on both is excessive due to mechanics ranging 50-60.

**Comment by BlueTheKing** [comment]
Should be changed in #406

**Comment by Regalis11** [comment]
Fixed in cc594a5
