### ISSUE TITLE
Line of Sight setting should be serverside rather than personal

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#4065]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![602960_20201012142916_1](https://user-images.githubusercontent.com/62313026/95752273-aef7c300-0c97-11eb-8d7c-0ba55ed3fb04.png)
The Line of sight setting should be a serverside setting rather than a personal setting as it effects gameplay.  Setting the Line of Sight effect to None is kind of a cheat as it allows you to see through walls.   Also there is no difference between Transparent and Opaque.

**Comment by hubismal** [comment]
It is serverside. If you're a client online it ignores your preference and goes with whatever the server has set up. There is a slight difference between transparent and opaque but the ambientlighting is so low it's hardly noticable.

**Comment by Regalis11** [comment]
Yep, your personal settings should be overridden by whatever setting the server is using. Just gave this a test and it seems to be working as intended.
