### ISSUE TITLE
Getting stunned or [[unknown]] whilst talking to mission giver results in mission not appearing on the map

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4071]
Reproduction Steps:

**TESTED:**
1. Stand between doors in singleplayer
2. Talk to the mission giver
3. Get stunned by door-auto closing
4. Click right arrow and mission confirmation will not show up
5. Look at the map
![ezgif-3-23eb1fc86150](https://user-images.githubusercontent.com/72813628/95886182-43bbf880-0d4c-11eb-9d41-ff116be31207.gif)
[note, the last "glitched" box was not clicked]

**UNTESTED:**
1. Talk to mission giver in multiplayer
2. Get stunned by any means
3. Click right arrow when awoken and mission confirmation will not show up
4. Look at the map

**???:**
1. Talk to mission giver in singleplayer
2. Have an event(?) take place off screen
3. Mission does not show up on map (see below)
![bug2](https://user-images.githubusercontent.com/72813628/95885719-9a750280-0d4b-11eb-9319-c066608e4c90.gif)
[note, the last "glitched" box was not clicked]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6e4bd01dcc5ce42c6db875e396e03627eb5c6e1c

**Comment by Xeavas** [comment]
[0.1200.0.0] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
