### ISSUE TITLE
v0.10.6.0 (Unstable) Decapitating tigerthreshers on death plays "death wiggle" on head instead

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4072]
Description :
In the event a tiger thresher is decapitated on death, the head will usually spin and rotate rapidly as part of the death animation, rather than the main body.

Version :
v0.10.6.0 (Unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/68ad8217ac8663afcff82fb5972481f98de95d3e

**Comment by Rokvach** [comment]
No issues, closing.
