### ISSUE TITLE
v0.10.6.0 (Unstable) Chitin chunk is unpickable

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4074]
You can't pick it up and you can't hold it in your hands if you spawn one in your inventory.

**Comment by Regalis11** [comment]
Could not reproduce: picking the item seems to work as expected. Did this happen in single player or multiplayer? Does it happen every time or was it a one-time occurrence?

**Comment by SoobGorl** [comment]
@Regalis11 Similar thing happened to me - if you wait for the chunk to spawn/drop from orangeboy the item name is greyed out and you can't pick it up. Happened on a door for me, but I just thought you weren't able to pick the item up so I don't know how to recreate that.

**Comment by Xeavas** [comment]
@Regalis11 I spawned "Chitin Chunk" at cursor and one in my inventory, can't pick it up in SinglePlayer using either default or legacy controls. First discovered similar to what @SoobGorl mentioned

**Comment by mrjpjr** [comment]
Single player Campaign.
Also unable to pick up chitin chunk

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a5fd1f64a726d6142c73726e44a6caaa099d46ef

**Comment by Rokvach** [comment]
Working correctly, closing.
