### ISSUE TITLE
Flare and Alien Flare crash the unstable branch

### ISSUE THREAD

**Issue by KeklMcgekl** [Regalis11/Barotrauma#4076]
- [ ✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Flares cause the game to crash

**Steps To Reproduce**
Throw either flare type

**Version**
Unstable v0.10.6.0 Windows
branch dev, revision 7e28bcdef2
**Additional information**
[crashreport (30).log](https://github.com/Regalis11/Barotrauma/files/5373677/crashreport.30.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b7b496bb5861217fac7d2b19c54568bd54e822d6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
