### ISSUE TITLE
Part of the crew placed as spectators when starting an MP campaign mission

### ISSUE THREAD

**Issue by Zyraxes-afk** [Regalis11/Barotrauma#4081]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon starting a mission one of my crew members were put into spectator and when entering the server lobby, it wouldn't let us get back into the campaign (stuck in the server lobby), even though it was running (the bot was speaking in the chat). Its not game breaking. All it took is for us to reload the server lobby and get everyone back in.

**Steps To Reproduce**
Load up campaign and when at an outpost, start a mission, then go back to server lobby and hop back into campaign from there. (It happened twice)

**Version**
0.10.5.1 Windows (10)

**Additional information**
No additional information

**Comment by Listerofsmeg** [comment]
I've had a similar thing when using the kastrull.

We load into a fresh campaign and when first loading in people are put into the roles they select. When selecting the mission and loading into it 3 ouf of the 10 crew were put into the spectator view.

**Comment by Regalis11** [comment]
No known steps to repro, closing
