### ISSUE TITLE
Logbook Contents do not Save Between Departures in Campaign

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4082]
Recreation Steps:
1. Spawn in a blank logbook or find one spawned via the sub-editor
2. Write anything into it
3. Proceed to the next destination in the campaign and depart to said destination
4. Open up your logbook at the next location
5. Logbook is empty

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/829101f2076048ef52b01240a68a6bc3dab29c4d

**Comment by Rokvach** [comment]
Logbook doesn't save in Multiplayer, Terminal does. Logbook does save correctly in singleplayer.

**Comment by Regalis11** [comment]
The logbooks seem to save correctly as well, the issue seems to occur when the item is in a character's inventory during the level transition (because those items aren't loaded from XML client-side, but instead spawned via network messages).

**Comment by Regalis11** [comment]
Logbooks should work correctly now too: https://github.com/Regalis11/Barotrauma-development/commit/c37705ba772004b00334467f3e90f476dc150a6d

**Comment by Rokvach** [comment]
If you find a logbook in a wreck which isn't part of a mission should its contents also be saved between rounds? Currently the text it spawned with resets

Otherwise seems to be saving correctly if a player types on the logbook

**Comment by Regalis11** [comment]
Looks like that only happens in multiplayer when the logbook is in the character's inventory, and if the welcome message is longer than 200 characters. Marking this as low prio, will look into it when I get some more urgent issues out of the way first.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e070a23c82715fe660aa3a4120a0f3b4d425715. The server now splits large messages to multiple smaller messages, which causes the layout of the text to change a bit during the level transition, but I think it's such a minor issue that we can ignore it.

**Comment by Udrakan** [comment]
Tried 5 transitions in singleplayer, no issue.

**Comment by Xeavas** [comment]
Tested in singleplayer, cannot replicate, unsure about multiplayer.

**Comment by Rokvach** [comment]
Closing.
