### ISSUE TITLE
Unable to edit client permissions on Dedicated Server

### ISSUE THREAD

**Issue by Kadenaa** [Regalis11/Barotrauma#4084]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I don't have the necessary permissions to edit settings from server lobby, or to start a game on my dedicated server.
I have tried updating my client permissions by editing the clientpermissions.xml file and restarting the server, however this does not work.

**Version**
I am running a dedicated server from a docker container on my local network (Ubuntu 18.04.5 LTS).
Barotrauma Dedicated Server 0.10.5.1 (ReleaseLinux, branch release, revision 9e259b2148)

**Additional information**
Here is my clientpermissions.xml file:
```
<?xml version="1.0" encoding="utf-8"?>
<ClientPermissions>
  <Client
    name="Kadena"
    endpoint="127.0.0.1"
    permissions="All" />
</ClientPermissions>
```

**Comment by Regalis11** [comment]
Unless the server and the client are running on the same machine, the loopback address "127.0.0.1" won't work: if you're connecting to another machine in a local network, you should be using the IP address of the machine the client is running on.

Another option would be to give the client permissions from the dedicated server console (assuming you have access it), for example by using the command "giverank Kadena Admin"

**Comment by Kadenaa** [comment]
Using the dedicated server console command helped, and updated the clientpermissions.xml file perfectly. Thanks!

It's worth to note that I was having issues due to connecting to my server locally and publicly for testing.
This requires 2 entries in the clientpermissions.xml file (one for your internal IP, and one for your gateway)
