### ISSUE TITLE
Bots can steal items from outposts

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4088]
I've noticed that when playing singleplayer, the bots will steal whenever they're tasked to do something like repair hull, broken devices, or anything of the sort while docked to a station. Even when I've had a welder in their inventory and told them to repair hull, they tend to go up and steal from the station. I don't know if its an intended behavior

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7427ffb525d1f428fddc93510331f73abf4dff70

**Comment by Rokvach** [comment]
Looks like bots are still able to steal fire extinguishers from the outpost, my engineer bot was arrested when he tried to take one in order to put out a fire.

**Comment by Rokvach** [comment]
Are bots allowed to steal diving masks?
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bede9f61-1d3f-4c1c-bac1-717444dca827)

**Comment by Regalis11** [comment]
Should be fixed now https://github.com/Regalis11/Barotrauma-development/commit/2225d324e6bb5e0b09c1d09101269b63b2f6a5b1.

Allowing the bots to steal diving masks and suits is allowed when the outpost is flooding though, need to add an exception for that so the security doesn't try to arrest the bots for doing so.

**Comment by Rokvach** [comment]
If a bot steals a welding tool from a dead NPC that welding tool isn't marked as stolen

**Comment by Rokvach** [comment]
Tested, all the above issues has been fixed. Working correctly. Closing.
