### ISSUE TITLE
[QoL] Allow to only interact with dropped items when crouching

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4092]
Picking up items can get quite frustrating especially with the new pet feature, trying to pick up the dropped items they produce leads to you constantly selecting devices behind the items.

**Comment by ezjamsen** [comment]
I'm not convinced this is the best solution to the problem at hand, but if it's quick to test and feels natural, then I have no issues at least giving it a shot.

**Comment by Rokvach** [comment]
Another idea that came to mind would be to list all the items inside a hull when picking up a dropped item if there is more than 1 item on the ground, would help with things like picking up harpoons after shooting them and overall make it easier to cleanup rooms as you wouldn't need to try and find all of the items but rather just target one of them.
