### ISSUE TITLE
Can`t use spawnsub command

### ISSUE THREAD

**Issue by muskaeragon** [Regalis11/Barotrauma#4093]
Description: I understand that you are intentionally restricting certain commands in multiplayer. But I have a request to resolve them. As everyone already knows, players get tired of playing standard. For this reason, we can use these commands, for example (spawnsub) to diversify our game. We create our own maps, but we can't create them in multiplayer. Also, this is a very useful team for role-playing and without it it is difficult to engage in an interesting game.

**Comment by Regalis11** [comment]
Thank you for the request! Unfortunately loading submarines mid-round is a bit tricky: it'd require quite a lot of work to coordinate it in a way that doesn't cause any entity ID mismatches or other networking issues. So at least for the time being we have no plans to implement it for a niche use-case like this, but maybe in the future!
