### ISSUE TITLE
RNG and randomevents.xml

### ISSUE THREAD

**Issue by Speaker15071** [Regalis11/Barotrauma#4097]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I tried to make custom randomevents file, and used multiple eventsets like this:

```
<EventSet chooserandom="true" mindistancetraveled="0.50" minmissiontime="300" minintensity="0.0" maxintensity="1.0">
        <EventSet>
            <MonsterEvent characterfile="Molochbaby" minamount="4" maxamount="6" spawntype="MainPath" spawnprobability="0.95" />
            <MonsterEvent characterfile="Moloch" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
        </EventSet>
        <EventSet>
              <MonsterEvent characterfile="Hammerhead" minamount="1" maxamount="4" spawntype="MainPath" spawnprobability="0.95" />
              <MonsterEvent characterfile="Hammerheadmatriarch" minamount="0" maxamount="1" spawntype="MainPath" spawnprobability="0.95" />
        </EventSet>
        <EventSet>
             <MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="5" spawntype="MainPath" spawnprobability="0.95" />
             <MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
        </EventSet>
             <MonsterEvent characterfile="Mudraptor" minamount="2" maxamount="4" spawntype="MainPath" spawnprobability="0.95" />
             <MonsterEvent characterfile="Crawler" minamount="3" maxamount="8" spawntype="MainPath" spawnprobability="0.95" />
   </EventSet>
```

Im only altering misdistancetraveled and minmissiontime.
The problem is that every time it triggers it gives exactly same result, like in one game it always triggers crawler spawn, and another game it's hammerhead only spawning. I suppose that there's a problem with in-game RNG. Tested on both actual an unstable versions, got same result.

**Steps To Reproduce**
Create same type of eventset, use 'override' or commonness="1000", then launch a game.

**Version**
0.10.5.1 Windows

**Comment by Regalis11** [comment]
There's one potential issue in this event set: the last two events (the mudraptor and crawler spawns) aren't inside an event set, so the parent event set may either choose the mudraptor spawn, the crawler spawn or one of the child event sets.

Other than that I don't see anything wrong with the config. But you that said in one game it triggers a crawler spawn and in another one a hammerhead spawn: doesn't that mean it _doesn't_ always give the same result? Note that when you're playing the same level (or using the same level seed), the spawns are always the same.

**Comment by Speaker15071** [comment]
There's no problem in choice between eventset and monsterevent by chooserandom. The problem is that if you use same eventsets like i mentioned above multiple times, it gives same result in every parent event set (one game all eventsets trigger child eventset 
```
<EventSet>
             <MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="5" spawntype="MainPath" spawnprobability="0.95" />
             <MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
        </EventSet>
```
and other game randomevent always trigger 
'''
<MonsterEvent characterfile="Crawler" minamount="3" maxamount="8" spawntype="MainPath" spawnprobability="0.95" />
'''
Changing levelseed just changes which eventset or monsterevent all parent eventsets will trigger.

**Comment by Regalis11** [comment]
I'm still not sure if I understand this correctly. What do you mean by "one game"? One round/mission?

> Changing levelseed just changes which eventset or monsterevent all parent eventsets will trigger.

This sounds normal to me, with the same seed you should always get the same events.

**Comment by Speaker15071** [comment]
okay, i gonna try to illustrate this:

![SickRNG](https://user-images.githubusercontent.com/5286113/96443416-006af980-1226-11eb-8767-57d436c2e1ea.png)

There's no problem with level seed, it acts absolutely correct. The problem is that RNG generates random value only one time and use it for all random events.

**Comment by cminnow** [comment]
I think this explains the problem as it appears to the user perfectly. Every seed progresses in exactly the same way unless perhaps you restart Barotrauma. I suspect the random seed value is initialized sometime at the start of a session rather than based on mission start time. Either way, I also hope that this problem is fixed.

**Comment by Speaker15071** [comment]
It's not a seed problem. The problem is: if you call same event multiple times in one round, it gives same result for every try, like if you offer game to choose A, B, or C, it will always go for A in all tries, and if you change level seed, it could go for only B or only C paths in chooserandom, but never combine A and B, B and C, or ABC. For me as modder that means that I cannot use single eventset, which randomly spawn 1 of 10 kinds of creatures, multiple times, because every time this eventset will be triggered, it will go down the same path and spawn only one kind of creatures, no matter how many times I'll trigger same eventset. 
That's what im tried to illustrate above, that's what happens if you trigger same eventset like one I mentioned in first message multiple times in one round, altering only trigger conditions.

**Comment by Regalis11** [comment]
Ah I think I finally got what you mean now.

So what you mean is that for example with the following event set, during a given round it would always pick the bolded events?
```
<EventSet chooserandom="true" mindistancetraveled="0.50" minmissiontime="300" minintensity="0.0" maxintensity="1.0">
	<EventSet chooserandom="true">
		**<MonsterEvent characterfile="Molochbaby" minamount="4" maxamount="6" spawntype="MainPath" spawnprobability="0.95" />**
		<MonsterEvent characterfile="Moloch" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
	<EventSet chooserandom="true">
		  **<MonsterEvent characterfile="Hammerhead" minamount="1" maxamount="4" spawntype="MainPath" spawnprobability="0.95" />**
		  <MonsterEvent characterfile="Hammerheadmatriarch" minamount="0" maxamount="1" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
	<EventSet chooserandom="true">
		 **<MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="5" spawntype="MainPath" spawnprobability="0.95" />**
		 <MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
</EventSet>
```

**Comment by Speaker15071** [comment]
Yep, and parent eventset have same problem, it will act like this: 
```
<EventSet chooserandom="false" mindistancetraveled="0.25" minmissiontime="300" minintensity="0.0" maxintensity="1.0">
[This one gets selected]<EventSet chooserandom="true">
[This one gets selected] <MonsterEvent characterfile="Molochbaby" minamount="4" maxamount="6" spawntype="MainPath" spawnprobability="0.95" />
		<MonsterEvent characterfile="Moloch" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" /> [will never fire]
	</EventSet>
	<EventSet chooserandom="true">[will never fire in this round]
		<MonsterEvent characterfile="Hammerhead" minamount="1" maxamount="4" spawntype="MainPath" spawnprobability="0.95" />
		<MonsterEvent characterfile="Hammerheadmatriarch" minamount="0" maxamount="1" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
	<EventSet chooserandom="true">[will never fire in this round]
		<MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="5" spawntype="MainPath" spawnprobability="0.95" />
		<MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
</EventSet>

<EventSet chooserandom="false" mindistancetraveled="0.50" minmissiontime="300" minintensity="0.0" maxintensity="1.0">
[This one gets selected]<EventSet chooserandom="true">
[This one gets selected] <MonsterEvent characterfile="Molochbaby" minamount="4" maxamount="6" spawntype="MainPath" spawnprobability="0.95" />[Will always give same result as 0.25 event]
		<MonsterEvent characterfile="Moloch" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
	<EventSet chooserandom="true">
		<MonsterEvent characterfile="Hammerhead" minamount="1" maxamount="4" spawntype="MainPath" spawnprobability="0.95" />
		<MonsterEvent characterfile="Hammerheadmatriarch" minamount="0" maxamount="1" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
	<EventSet chooserandom="true">
		<MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="5" spawntype="MainPath" spawnprobability="0.95" />
		<MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
</EventSet>

<EventSet chooserandom="false" mindistancetraveled="0.75" minmissiontime="300" minintensity="0.0" maxintensity="1.0">
[This one gets selected]<EventSet chooserandom="true">
[This one gets selected] <MonsterEvent characterfile="Molochbaby" minamount="4" maxamount="6" spawntype="MainPath" spawnprobability="0.95" />[Will always give same result as 0.25 event]
		<MonsterEvent characterfile="Moloch" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
	<EventSet chooserandom="true">
		<MonsterEvent characterfile="Hammerhead" minamount="1" maxamount="4" spawntype="MainPath" spawnprobability="0.95" />
		<MonsterEvent characterfile="Hammerheadmatriarch" minamount="0" maxamount="1" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
	<EventSet chooserandom="true">
		<MonsterEvent characterfile="Tigerthresher" minamount="1" maxamount="5" spawntype="MainPath" spawnprobability="0.95" />
		<MonsterEvent characterfile="Bonethresher" minamount="1" maxamount="2" spawntype="MainPath" spawnprobability="0.95" />
	</EventSet>
</EventSet>
```

**Comment by Speaker15071** [comment]
RNG chooses random event only once, similar eventsets will always give same result.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/45156285d66c711fa3f93929278a73744c598452

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
