### ISSUE TITLE
Smoking the pipe while trying to use equipment.

### ISSUE THREAD

**Issue by EX0091** [Regalis11/Barotrauma#4100]
- [x] - I have searched the issue tracker to check if the issue has already been reported.

**Description**
Picking up a captain's pipe and then trying to use a tool will make the aiming not work and but the tool will be used a.k.a Will cause the guns to be fired at the ground (melee weapons wont be able to be swung at all). The animation will not play or will be bugged, if the pipe has tobbaco in it, the tobbaco will be smoked. The bug only works only once the pipe is picked up, using the tool the second time wont result in the bug but droping and picking up the pipe will repeat the bug.

**Steps To Reproduce**
-pick up a captain's pipe (with or without the tobbaco in it)
-pick up some tools/weapons (the item can be already in the inventory or hand)
-hold right click and then click/hold left click while holding a tool.
(the order of picking up does not matter, the bug appears anyway.) 

**Version**
v0.10.5.1, Windows

**Additional information**
none

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce this. Did the following and couldn't spot any issues:
- Equip a captain's pipe (is this what you meant by picking it up?)
- Equip a revolver to the other hand by pressing the inventory hotkey
- Hold RMB: the character starts aiming with the revolver and holding the pipe on the mouth
- Left click: the character fires the revolver

Also tested with a stun baton and by equipping the items using the buttons above the inventory slots, and everything seemed to work as expected.

**Comment by EX0091** [comment]
oops i guess i kinda forgot about this one, When i was doing this, having the pipe in the inventory (not holding it) caused the bug.

**Comment by Regalis11** [comment]
Ah, thank you for the clarification! Managed to repro and fix it now (https://github.com/Regalis11/Barotrauma-development/commit/d7b91abb602f5bb5d98ff160c888da1ca712c5b9)

**Comment by Rokvach** [comment]
No issues, closing.
