### ISSUE TITLE
Railgun/Coilgun Periscope UI Bugs [Release and Unstable]

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4109]
Bug 1: If holding a crate, dufflebag(s), storage container(s), or hovering over a toolbelt and switching over to a periscope, the UI elements will remain.
1. Hold/select any of the items
2. Use the periscope
![image](https://user-images.githubusercontent.com/72813628/96593783-e2e67000-12b7-11eb-8ee9-de0b235eeca3.png)

Bug 2: If the periscope cursor is held on any inventory element, when getting out of the periscope, the camera will be zoomed out.
1: Enter periscope and aim at bottom of the screen (or any UI inventory element)
2: Leave the periscope while the cursor is still on the UI elements (zoom will continue to be applied even when moving).
![image](https://user-images.githubusercontent.com/72813628/96593922-11644b00-12b8-11eb-9b16-03eaa8ad7bcd.png)

**Comment by EdusFF** [comment]
#1 fixed in: https://github.com/Regalis11/Barotrauma-development/commit/25d31f4b80af88274af862169d19565843c9d3ed
#2 fixed in: https://github.com/Regalis11/Barotrauma-development/commit/d2501f4244d8a0d46a10d5254ee15b79547d29d4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
