### ISSUE TITLE
Hammerhead's Spawn name appears as "hammerheadspawn"

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4110]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Hammerhead Spawn should be referred to as "Hammerhead Spawn". Instead, its "name" simply copies its speciesname, resulting in the name being "hammerheadspawn" across all languages.

**Steps To Reproduce**
1) Spawn Hammerhead Spawn
2) Hover over it to check what it's called
3) Read "hammerheadspawn"

**Version**
V0.10.6.2 Unstable. Also happens in the current public build of the game.

**Comment by Rokvach** [comment]
No issues, closing.
