### ISSUE TITLE
Have Items in Trashcans be Steal-able [Suggestion]

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4111]
Idk if this is intended or not but I find it kinda weird that when items at outposts spawn in trashcans, they are marked as un-stealable items and results in a possible arrest if taken in plain sight. I think that they should be fair game :)

**Comment by Xeavas** [comment]
Yeah rummaging trash cans shouldn't be considered stealing, its weird and will get some eyes on you, but not really stealing something that has been thrown away.

**Comment by NyarlathotepZERO** [comment]
Yeah, perhaps lore comes into play in that nothing is actually 'trashed' as we know it, it is in fact sorted and 'recycled'

**Comment by ezjamsen** [comment]
Agreed. Stuff in the trash should be up for grabs. We could apply a faction reputation penalty for doing it though, because frankly what sort of self respecting captain goes through station trash?

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8b7b7c0afdb6cfc5427cf16e4c995b6c9a3a65ec

**Comment by Jasontti** [comment]
Tested, Taking items from trashcans is not stealing and normal stealing still works.
