### ISSUE TITLE
Buff (affliction) icon to indicate whenever you are disguised

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#4113]
With the fixes to indicate disguising on the UI, an icon for being disguised is needed for the player to keep track whether a disguise is active or not on your character

**Comment by EdusFF** [comment]
Implemented in: https://github.com/Regalis11/Barotrauma-development/commit/628cfbc960e6768395383568c8c6af9d9e9520a6

**Comment by Rokvach** [comment]
No issues, closing.
