### ISSUE TITLE
"Deceased" text wrapping

### ISSUE THREAD

**Issue by RayTrace082** [Regalis11/Barotrauma#4116]
- [* ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In dead characters, the last "D" in "DECEASED" wraps around, taking up a separate line and messing up the text centering. See attached image

![D so big it takes a whole line](https://user-images.githubusercontent.com/47252286/96753189-ca697900-13cf-11eb-860a-e1de74349baf.png)

**Steps To Reproduce**
Kill a character, and examine their corpse with the [H]eal command

**Version**
Latest unstable version, no mods enabled, English localization, and on a Windows 10 OS

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c8674ee49325736ec4fdbf231f75eec64f6e3201

**Comment by Rokvach** [comment]
No issues, closing.
