### ISSUE TITLE
Steam workshop can filter "Assembly" tag, but the game uses "Item Assembly" tag instead

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4119]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When publishing a file to the steam workshop you can tag it as "Item Assembly", but the "Browse By Tag" page on steam workshop allows you to filter "Assembly" tag instead leading to 0 matches.

**Version**
V0.10.5.1

**Additional information**
File published as "Item Assembly"
![image](https://user-images.githubusercontent.com/48099798/96859319-a6567800-1461-11eb-8a38-4f75e1275d61.png)

Workshop's "Browse By Tag" page with 0 results for "Assembly" tag
![image](https://user-images.githubusercontent.com/48099798/96859469-d0a83580-1461-11eb-8cb2-ebb3899e806d.png)

**Comment by Regalis11** [comment]
Fixed on Steam's side now (renamed "Assembly" -> "Item Assembly")

**Comment by Rokvach** [comment]
No issues, closing.
