### ISSUE TITLE
[0.10.6.2] Pets Inventory and Stats doesn't save/carry over in campaign.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4123]
Description : 
Pets Hunger/(Happiness? and Item production stats? mentioned by Piro), and any item in their inventory (e.g. nametags) doesn't save/retain when you either transition from the current area to another area or when entering outposts, saving the game and reloading it at outpost also causes this to happen.

Steps to reproduce : 
Start campaign, spawn/buy pet eggs, once you've obtain them, hatch, feed and put some items in them. 
Try either ;
1) Saving and reloading from outpost
2) Undocking and leaving from outposts
3) Docking and entering to outposts

Version : [0.10.6.2]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f1f3a0cd88d9fde8a2e3505f3c3a2683124e092

**Comment by Rokvach** [comment]
Pet name tags doesn't save in multiplayer, I entered a natural formation and my pets name tags text field reset

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f70665a5934ab4db29a42cb7b615b75236ce937

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
