### ISSUE TITLE
Stored light components that are not shadow casting subtract from shadow casting light count.

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#4128]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items with a light component that is not shadow casting subtract from the shadow casting light count in the sub editor if stored in a container. 

This happens because there is no check on whether the stored lights are shadow casting when calculating the number of stored lightcomponents to subtract from the shadow casting light count:

https://github.com/Regalis11/Barotrauma/blob/20a69375ca605688ac68f26f82f2635930141d3b/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs#L574-L580

**Steps To Reproduce**
Open the sub editor. Place a container in the sub editor. Put light components in this container. The shadow-casting light counter now shows a negative number. 

**Version**
Barotrauma V0.10.601.0 (ReleaseWindows, branch dev, revision dbdfffbe6)

**Additional information**
Found by discord user IExploded

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e137219a6a260efa9866c04dfbcab60bb84d30e8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
