### ISSUE TITLE
Unstable - Typo in hallucinogenic bufotoxin

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4129]
Hallucinogenic Bufotoxin mistakenly uses the identifier "saline" instead of "antibloodloss1" in its deconstruction results.

![image](https://user-images.githubusercontent.com/55356135/97087064-4690d600-15f5-11eb-9eb4-dedbe8650553.png)

![image](https://user-images.githubusercontent.com/55356135/97087053-37118d00-15f5-11eb-885f-8de9b353d2b1.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6cadea2dcf4de75ceb4870bbf9c498b92503a335

**Comment by Rokvach** [comment]
No issues, closing.
