### ISSUE TITLE
Worn apparel hindering speach from players

### ISSUE THREAD

**Issue by TheGoldenGuardian** [Regalis11/Barotrauma#413]
My idea for this is to allow certain items (primarily worn over the face) to limit/muffle chat messages sent from the player wearing it, similar in the range cutoff of comms devices. Maybe call it something like "speachImpede".

This could be used for muffling speach coming from a user wearing a diving mask, or drastically muffling/completely muting somebody with a bag over their head.
```xml
<StatusEffect type="OnWearing" target="Character" speachImpede="100"/>
```
I belive 100 could be used to completely silence them, making them unable to chat, while everything from 1-99 will progressively add more dashes.

**Comment by chesse20** [comment]
No support chat has such a low range where it works 100% already

**Comment by TheGoldenGuardian** [comment]
They were just examples, the idea is for you to be able to gag others.

**Comment by acebud12** [comment]
I like this idea, as golden guardian said, could be used on items like gags or even added to existing items like BTE's restraint set.

**Comment by Weebyxanide** [comment]
Comms range is already an externalised value, so I don't see how adding this would hurt anything. And, hilariously, this could potentially make one _less_ likely to be killed by a traitor because you could be silenced without the more inflammatory solution of leaving a corpse behind.
