### ISSUE TITLE
[Stable/Unstable] Untouched Oxygenite Shards doesn't produce oxygen on the floor

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4131]
Description :
Is it intended that untouched Oxygenite Shards doesn't produce oxygen on the floor unless it's been equipped in hand by a person once?

Examples of "Untouched" Oxygenite Shards includes :
Product of deconstructed sky alien artifacts
Spawned in via sub editor
Spawned in via "spawnitem" command

Steps to reproduce : N/A in desc
Version : Tested in [0.10.5.1] and [0.10.6.2]

**Comment by Ek-Videogames** [comment]
This sounds like an issue of the item updating to realize it is non-contained status effect?

**Comment by Xeavas** [comment]
Sounds like it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67226eca8d5dcca8d2bb57f1987e63c6a00ad4bd

**Comment by Xeavas** [comment]
[v0.1100.0.0 (unstable)] - Retested, cannot replicate.

**Comment by Rokvach** [comment]
Closing
