### ISSUE TITLE
Reseting settings to default removes all items in level

### ISSUE THREAD

**Issue by Seven63** [Regalis11/Barotrauma#4132]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reseting to default settings whilst in-game will cause all items to be removed from the level and produce errors in the console.

**Steps To Reproduce**
1: Start new campaign.
2: once in-game, open settings from the escape menu.
3: press the reset button at the bottom of the menu and confirm

**Version**
V0.10.6.2, Windows

**Additional information**
"Items" in this case refers to the definition from the sub editor. Installations, cabinets, junction boxes as well as inventory items are all removed by the bug. Structures, walls, and characters are unaffected.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/778598e481db98398a50e921f344e1651f4e0909

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
