### ISSUE TITLE
Periscope with camera incorrect angle calculation.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4136]
**versions both v0.10.5.0 - v0.10.6.0**

When getting the output angle from a periscope connected to a camera, the angle is mistakenly measured **relative to the player/periscope** position rather than the camera position.
![image](https://user-images.githubusercontent.com/55356135/97120380-ef6e2c80-16ec-11eb-8ae4-0f9432bc3386.png)

![image](https://user-images.githubusercontent.com/55356135/97120465-80dd9e80-16ed-11eb-8bc9-55acc8ae9fa1.png)

**Coilgun turret shown working as intended:**
![image](https://user-images.githubusercontent.com/55356135/97120400-14fb3600-16ed-11eb-8ef2-e071b19579a5.png)

Possible this is due to the fact that the code looks for a turret specifically when determining the starting point of the vector, 
as camera does not have a turret component?
![image](https://user-images.githubusercontent.com/55356135/97120330-a6b67380-16ec-11eb-9a17-0009725a5f46.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3365a4e12f8c084d0cc60ca3860ba1e6b85536c3

**Comment by Rokvach** [comment]
No issues, closing.
