### ISSUE TITLE
[Feature Request] Concatenation component assets implementation

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#4140]
It's been a few months since Jlobblet's code for the string concatenation component has been merged with the repo, but we've yet to receive the item in game. Given that it's probably pretty low prio, I've made the assets and XMLs to do some testing with the component in game myself a while back. I thought I might as well [share them here](https://drive.google.com/drive/folders/1UwPmNhyJwxyPWDHof7xAgb9_2IVpV6f2?usp=sharing) in case it may save some time in the implementation, although I'm not sure this is the right place given that it's not code.

**Comment by Regalis11** [comment]
Thank you, these files made it really quick to add! :) Implemented in https://github.com/Regalis11/Barotrauma-development/commit/44ae999ab4bd42cb3bc703b903b61a40cecde246

**Comment by Working-Joe** [comment]
All seems to work as intended in V0.1100.0.1. Thanks for the addition!

**Comment by Rokvach** [comment]
Closing.
