### ISSUE TITLE
Monster loot is all the same when spawned in groups

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4141]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever monsters are spawned in sets, all their drops are the same. For instance you driving through the level and 4 mudraptors appears, if one of them has mudraptor egg, the rest of them will also drop mudraptor eggs. Same with husk.

**Version**
~0.10.6.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/01cd9217c3f4de19f4c0137672725b60e2310049

**Comment by Xeavas** [comment]
Done a small test with some crawlers, cannot replicate. More test probably needed.

**Comment by Kaillera** [comment]
Ran into two husk in a wreck. Both had eggs, but one had a stinger.

**Comment by Rokvach** [comment]
Closing.
