### ISSUE TITLE
Water in the Dugong's Oxygen Generator Room Don't Trigger the Flooding Alarm

### ISSUE THREAD

**Issue by soosgjr** [Regalis11/Barotrauma#4142]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The water detector in the Dugong's utility compartment hull is not wired to the OR component chain responsible for triggering the flooding alarm.

**Steps To Reproduce**
- Start a game on the Dugong submarine.
- Cause a major leak in the room with the oxygen generator.
- Close the room's door and make sure the other detectors are not affected by water.
- Go to the command room.
- Observe the leak not raising the flooding alarm.

**Version**
Both stable (v0.10.5.1) and unstable (v0.10.6.2) on Windows.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3125e427c7885a6ab1926a83a3fac281e340956 (referenced [incorrect ticket](https://github.com/regalis11/barotrauma/issues/11229) in the commit message)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
