### ISSUE TITLE
Batteries and Oxygen tanks do not appear in editor unless using search bar

### ISSUE THREAD

**Issue by CallsignApollo** [Regalis11/Barotrauma#4143]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
as title says, both variants of battery cells and oxygen tanks do not appear in the  sub editor menu under their respective tabs (all/electrical/equipment) unless using the searchbar to filter, at which point they appear in the menu as intended.

**Steps To Reproduce**
enter sub editor, open equipment tab, notice lack of battery cells. upon entering "bat" or "oxy" into filter searchbar, the missing items will appear in the menu

**Version**
[ver. 0.10.5.1 STABLE]

**Additional information**

before search
![image](https://user-images.githubusercontent.com/73565984/97378229-3f3d2700-1898-11eb-9f40-1d9598b3982c.png)

after searching
![image](https://user-images.githubusercontent.com/73565984/97378278-5da32280-1898-11eb-94cb-b1643c65d7fa.png)

**Comment by Momiro** [comment]
I've noticed this too, and it's been pretty confusing, I've wondered if there are other items that are hidden this way.

**Comment by Regalis11** [comment]
This seemed to apply to items that are included in multiple categories: the oxygen tanks are categorized as both Equipment and Misc, and the battery cells are Equipment and Electrical. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/879f0e8352b805722a46136fc9102ce6494901c9

**Comment by Working-Joe** [comment]
looks fixed in V0.1100.0.1 - tanks and batteries appear in both their listed categories, as do similar items such as fulgurium batteries.

**Comment by Rokvach** [comment]
Closing.
