### ISSUE TITLE
Multiplayer campaign unplayable without a host or a client with campaign management permissions

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#4144]
- [x]  I have searched to make sure this topic has not been submitted already

I am trying to set up a dedicated server for campaign play, but I am coming across a few frustrating issues.

First, the startwhenclientsready="True" and allowendvoting="True" do nothing when the gamemode is set to "multiplayercampaign" in the server settings. Players do not have a checkbox for "Ready" or for "End Round".

Second, if the gamemode is set to multiplayer campaign, and a new player joins an empty server, they cannot start a new campaign.

Third, if I set autorestart to true, the server will try to start a game, and then the client will get a bunch of errors, and the server will continue running a round, I can see bots opening doors and hatches on the from the server terminal.

Fourth, if a player joins an empty server and the gamemode is set to campaign, they cannot play a saved game either.

Fifth, if the gamemode selection type is set to Vote, you cannot select campaign, even if you are the host, or have been given ALL permissions.

It seems that the only way to get a functional campaign going is to be the host or a vetted player with ManageCampaign permission. Being one of those lets you start new games and load existing saves.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/0fd591115b69820ae4fdd32ac0514a40e563233f

Things I've noted when testing campaigns without a host (or one with permissions) present in the server (And most I don't strictly consider issues, but some are questionable or issues):

- No option to vote end round in a campaign level to return to lobby.
- cannot seem to start the server as a campaign automatically via XML, only by typing in dedicated commands after starting the server (If this is possible I could not figure it out).
- cannot vote campaign or change to it, even with full permissions if gamemode voting is active
- given the above, players cannot start campaigns anyways unless setup beforehand by a host/admin. Players without permissions also cannot (for obvious reasons) create a new campaign over using the existing.
- could not use bank funds to purchase goods, upgrade, buy submarines etc - only wallet funds.
- Can transfer bank funds to wallet (to do all the above purchasing that is wallet only) via a timed 0/0 vote that always succeeds
- cannot change salaries

Other aspects of this ticket (autorestart, start when clients ready) are fine, If the server allows for starting via ready votes then returning to lobby does not lock the server up either (The fourth). a dedicated server does not seem to be at any fully hostless stage as there are no options to (without input) host campaigns automatically on server start/restart.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/21409d99f2ce132d2eecf5449160621c859b882d

**Comment by Regalis11** [comment]
Copying the above issues to a checklist:
- [ ] No option to vote end round in a campaign level to return to lobby to retry a mission.
- [ ] cannot seem to start the server as a campaign automatically via XML, only by typing in dedicated commands after starting the server (If this is possible I could not figure it out).
- [ ] cannot vote campaign or change to it, even with full permissions if gamemode voting is active
- [ ] given the above, players cannot start campaigns anyways unless setup beforehand by a host/admin. Players without permissions also cannot (for obvious reasons) create a new campaign over using the existing.
- [ ] could not use bank funds to purchase goods, upgrade, buy submarines etc - only wallet funds.
- [ ] Can transfer bank funds to wallet (to do all the above purchasing that is wallet only) via a timed 0/0 vote that always succeeds
- [ ] cannot change salaries

**Comment by Rokvach** [comment]
- [ ] If you vote for a game mode the UI doesn't update to show the settings for that game mode, only if something happens which updates the lobby UI the settings show up, 

1. Toggle game mode voting on
2. Vote for campaign/mission mode (depends which one you have already selected)
3. Notice that you don't get access to the settings of that game mode
4. Update the UI somehow (If you have campaign selected then changing the difficulty preset or if you have mission mode selected then selecting one of the mission types)

**Comment by Rokvach** [comment]
Moved to Team1

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/3788/commits/93170212d31e83769aa873890c55579e2e7e9c2b

**Comment by Rokvach** [comment]
Tested, didn't spot any further issues. Can be merged and closed.
