### ISSUE TITLE
[v0.1100.0.0 (unstable)] - Flame particles sometimes phase through walls/doors

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4146]
**Description**
Using a flame thrower, flame particles tend to phase through walls if shot close enough or at just the right angle setting fire to things behind said wall.

**Version**
[v0.1100.0.0 (unstable)]

**Additional information**
![Clearerfirethruwall](https://user-images.githubusercontent.com/72674994/97461965-3708e880-1979-11eb-85f5-bdc85fe9f1b9.jpg)
![Flamethruwall1](https://user-images.githubusercontent.com/72674994/97452814-17b98d80-1970-11eb-84f5-ff2aed87c48e.jpg)
![Flamethrudoor1](https://user-images.githubusercontent.com/72674994/97452823-19835100-1970-11eb-9ca2-21b329b4734f.jpg)
![Flamethrudoor2](https://user-images.githubusercontent.com/72674994/97452827-1ab47e00-1970-11eb-92e0-04438e15edee.jpg)

**Comment by Regalis11** [comment]
Fixed a couple of issues in https://github.com/Regalis11/Barotrauma-development/commit/1592f2371eaf3e9cc4eec65499d98bd12255e2d2. There may still be some edge cases where the particles do go through walls, but I was no longer able to repro the issues in the screenshots.

**Comment by Xeavas** [comment]
[0.1100.0.1] - Retested, cannot replicate with my previously used methods. 👍

**Comment by Rokvach** [comment]
Closing.
