### ISSUE TITLE
[v0.1100.0.0 (unstable)] - Explosions damage devices through walls

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4147]
**Description**
When thrown into a corner or at a wall, the resulting detonation will damage devices behind walls, I am unsure if this is intended,

**Steps To Reproduce**
Chuck an incendium grenade into the aft ballast of the dugong, if its near enough the junction box and small pump on the other side of the wall will get damaged.

**Version**
[v0.1100.0.0 (unstable)]

**Additional information**
![incendg2](https://user-images.githubusercontent.com/72674994/97453272-8860aa00-1970-11eb-9027-11a7fbfbf84f.jpg)
![inceng1](https://user-images.githubusercontent.com/72674994/97453275-8991d700-1970-11eb-8c3b-2b345f7e3a6b.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fcf4e6a756a67d93b0411b1b9f913443dcfd5f2d

**Comment by Xeavas** [comment]
[0.1100.0.1] - Retested with same methods, cannot replicate issue 👍

**Comment by Rokvach** [comment]
Closing.
