### ISSUE TITLE
[v0.1100.0.0 (unstable)] - Unable to stand up after crouching under ballast flora

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4148]
**Description**
You're unable to stand up after crouching under ballast flora, suspecting it considers it as a solid object while having no collision with the player at the moment.

**Steps To Reproduce**
Crouch under ballast flora

**Version**
[v0.1100.0.0 (unstable)]

**Additional information**
![Crouchingproblem](https://user-images.githubusercontent.com/72674994/97455267-a29b8780-1972-11eb-9705-f10411d28bb3.jpg)

**Comment by Regalis11** [comment]
Note for fixing this: probably happens because the collision category of the branches seems to be CollisionWall

**Comment by 3e849f2e5c** [comment]
Fixed in Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9dc96756f9e4fbc23d0d1e3ea5a311931665f7b1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
