### ISSUE TITLE
[v0.1100.0.0 (unstable)] - Ballast flora branches absorb/stops all projectiles

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4149]
**Description**
Self explanatory.

**Steps To Reproduce**
Shoot ballast flora branch with a loaded syringe gun/ harpoon gun/ revolver

**Version**
[v0.1100.0.0 (unstable)]

**Additional information**
You can't manually inject ballast flora with equipped syringes but somehow can with syringe gun as stated above. (for syringes)

**Comment by Regalis11** [comment]
Note for fixing this: probably happens because the collision category of the branches seems to be CollisionWall

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9dc96756f9e4fbc23d0d1e3ea5a311931665f7b1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
