### ISSUE TITLE
Move-to-point autopilot mode

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#415]
Half autopilot, half manual control mode. When switched to this mode, the ship behaves like in the "maintain position" mode. But whenever you click somewhere else, the ship changes the position it's supposed to maintain to the point where you clicked.
![move-to-point](https://user-images.githubusercontent.com/38168249/40335722-6504ab3c-5d8f-11e8-91a6-347d41eade13.gif)
It's a more controllable version of manual control.
Not sure how hard or easy it is(if it's even possible) to implement a new kind of autopilot, but this one would really help with problems such as lagging submarine pilot(so many subs hit walls and sink because the server does not get pilot's input in time) and controlling the sub while doing other things such as using a railgun at same time in singleplayer(or multiplayer if you are the only one who is still alive).

**Comment by ClasticM** [comment]
This is a really good idea. Gives this mechanic another method of control. I can see this being really useful with shuttles too

**Comment by Weebyxanide** [comment]
Seconded. It would make things easier on the crew as a whole since the captain would have a much easier time of talking while driving, and at the same time this wouldn't trivialise the task of navigation.
