### ISSUE TITLE
Plasma cutting a welded door shows as "Welding"

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4150]
**Description**
Self explanatory

**Version**
[v0.1100.0.0 (unstable)]

**Additional information**
![Wrongactiondisplay](https://user-images.githubusercontent.com/72674994/97457249-8ac50300-1974-11eb-886d-69f700defbe6.jpg)

**Comment by Xeavas** [comment]
[0.1100.0.1] - Cannot replicate, working correctly now.

**Comment by Rokvach** [comment]
Closing.
