### ISSUE TITLE
[v0.1100.0.0 (unstable)] - Human Husks wearing something that hides their identity will crash the game

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4153]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A humanhusk created by a human reaching the final stage of the husk infection will "inherit" all of the items the human was carrying. If one of said items includes a mask that hides the human's identity in a clothing slot, the game will crash.

**Steps To Reproduce**
1) Spawn as a human
2) Wear a diving suit / diving mask / clown mask / etc. (Any clothing item that will conceal your identity)
3) Open console, type "giveaffliction huskinfection 100"
4) Type "kill"

**Version**
v0.1100.0.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab535e586acbcf5a459dc8dbffe71796d3080383

**Comment by Emanthealmighty** [comment]
No longer an issue in v0.10.6.2 (current public build) and v0.1100.0.1 (current unstable build).

**Comment by Rokvach** [comment]
Closing.
