### ISSUE TITLE
Hulls can't be unlinked

### ISSUE THREAD

**Issue by Zead456** [Regalis11/Barotrauma#4154]
**Description**
The hulls can be linked together but when linked it can't be unlinked and the only way to unlink is by recreating them.

**Steps To Reproduce**
Make Hulls unlinkable like any other linkable object.

**Version**
0.10.5.1 (Windows).

**Comment by Zead456** [comment]
really sorry!. didn't know i searched in open issues and not closed when checking if it's already reported.
it's already reported!

**Comment by ekqvist** [comment]
Duplicate of #3999
