### ISSUE TITLE
[IDEA] Sonar Beacon

### ISSUE THREAD

**Issue by Weebyxanide** [Regalis11/Barotrauma#416]
Basically, the notion here is a battery-powered item carried in one's inventory that places a marker on sonar displays in the same fashion as an outpost or shuttle as long as it remains powered. This could be useful for signalling, PVP and keeping tabs on a search party in alien ruins (to take the guesswork out of whether or not to move on or send someone else.)

Perhaps it would burn through battery power rather quickly as a balancing factor, ensuring that those carrying one only turn them on for short bursts to check in.

**Comment by TheGoldenGuardian** [comment]
This sounds like a pretty good idea, could also help locate somebody if they got lost while exploring or whatever and are possibly dead.
