### ISSUE TITLE
View Steam Profile not working on Dedicated Server

### ISSUE THREAD

**Issue by EricPfau** [Regalis11/Barotrauma#4164]
- [Y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When hosting a match locally you can press tab to pull up the player list, then right click someone's name to check their steam profile. This is very handy for tracking profiles for griefers etc.. On a dedicated server the option is greyed out and does not work.

**Version**
10.6.2

**Comment by Regalis11** [comment]
By dedicated server, do you mean the DedicatedServer.exe included with the game, or are you running the separate dedicated server application through SteamCMD (see https://steamcommunity.com/app/602960/discussions/1/2250056952644462246/)? If the former, this is normal: if you don't run the game through Steam, it can't use any Steam features, meaning that it can't verify the clients' Steam IDs or connect them to the Steam profiles.

**Comment by EricPfau** [comment]
The application through SteamCMD. Thank you for the clarification. That explains it.

**Comment by OverwatchVoice** [comment]
iirc, you can log in with your steam account with SteamCMD instead of using an anonymous account. Would that fix the problem?

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5689228981bc9da76db3dd23d7a9e789a858d5ef

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
