### ISSUE TITLE
Pyschosis sounds affecting all players in game

### ISSUE THREAD

**Issue by EricPfau** [Regalis11/Barotrauma#4165]
- [Y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As of the latest update random sounds appear to play. I hear reactor alarms randomly, random shotgun sounds, other random sound files playing etc.. Confirmed to not have pyschosis or any other medical condition. Running dedicated server.

**UPDATE**
Further testing revealed that when ANY player on the server has pyschosis, all other players in the lobby hear the sounds. This explains why healthy players were hearing random noises as well. We tested this using P2P as well as dedicated server.

**Steps To Reproduce**
Start a game. Give a different player pyschosis. Wait patiently and you will hear random sounds like a shotgun, bike horn, reactor meltdown etc.. Sounds appear to not be localized to just the pyschosis player.

**Version**
10.6.2

**Comment by KeklMcgekl** [comment]
I have experienced this too, random shotgun noises and alarms

**Comment by Momiro** [comment]
I've noticed this as well, hearing shotgun noises, alarms, and clown sounds, but not experiencing visual psychosis effects from other players.

**Comment by Xeavas** [comment]
[0.1100.0.1] - Tested using steam p2p with bots, cannot replicate. Unsure about players though.

**Comment by Xeavas** [comment]
[0.1100.0.1] - Update, tested again this time with Jlobblet, cannot replicate 👍

**Comment by Rokvach** [comment]
Closing.

**Comment by OverwatchVoice** [comment]
Whoops, my bad
