### ISSUE TITLE
New animated devices deteriorate faster than normal (Fabricator, Deconstructor, Large Pump)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4170]

**Comment by Rokvach** [comment]
Too tired still it seems, ofc its paused as its not wired.. Back to testing

**Comment by Regalis11** [comment]
Fixed fabricators and deconstructors in https://github.com/Regalis11/Barotrauma-development/commit/7a65def1266dc4013e2819274ef0f59b57344a7e. Couldn't repro the issue with the pumps

**Comment by Rokvach** [comment]
Tested, the devices only deteriorate now when they are in use (same as previously). Working correctly. Closing.
