### ISSUE TITLE
[0.10.6.2] - Hide offensive server names checkbox is inverted/misleading + suggestion

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4173]
**Description**
Hide offensive server names is inverted from what the description is trying to convey
It hides it while its unchecked and unhides it while checked.

**Additional information**
![InvertedHide](https://user-images.githubusercontent.com/72674994/97719632-42d3e680-1b02-11eb-9cb2-0fa440878efe.jpg)

**Suggestion**
A prompt that appears when you open up the server list for the first time, asking "Would you like to hide offensive server names?" followed by a yes or no answer to set it automatically the next time you open the server list. 

Further suggestion of a "preset" setting that saves your server list options to automatically use said preset every time you open the server list will be a good QoL.

**Version**
[0.10.6.2]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dc2c636

**Comment by Regalis11** [comment]
Implemented saving the filters in https://github.com/Regalis11/Barotrauma-development/commit/0abe1ff8b09a7f2e4d8b87453fc0d2015723b29b

**Comment by Regalis11** [comment]
Implemented the prompt in https://github.com/Regalis11/Barotrauma-development/commit/9496d8e9b2a79f8689e59109173486374646c2b7, moving to QA

**Comment by Xeavas** [comment]
[0.1200.0.0] - Working as intended (saves correctly, and had a prompt). 👍

**Comment by Rokvach** [comment]
Closing
