### ISSUE TITLE
Water Behavior - Doubt, possible feature request

### ISSUE THREAD

**Issue by LuCKySoZ** [Regalis11/Barotrauma#4175]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A flooded or semi-flooded wreck for example, when you open up unflooded space, the water from the area moves to flood the new opened up area. The thing is, sometimes the water level drops from the area moving the water from, to the new area that was empty, it's flowing faster than the ocean can push it back up again. The ocean, with its absurd pressure, is losing in flow speed, against a door/hatch/wall being open. I feel like water flow needs to be a lot quicker, more intense, possibly varying according to depth. A corridor height water column should push the character until it finds something to stop this movement (wall/door). The monsters shouldn't be main concern trying to keep them out of the sub. The Water should be the main concern.

**Version**
Newest 0.10.6.2 -  Windows 10 64

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
