### ISSUE TITLE
Unstable - Some Berillia shell pieces are misplaced

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#4177]
**Description**
Title

**Steps To Reproduce**
-Open Berillia in editor. Look at bottom engine room.

**Version**
Unstable
**Additional information**
![image](https://user-images.githubusercontent.com/59519434/97780303-224c7080-1b84-11eb-94f0-2a9437a0b1a8.png)

**Comment by danielasteljoki** [comment]
Fixed in 128666c.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
