### ISSUE TITLE
[Unstable] Wires of placed assembly do not appear in game until saved

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#4178]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wires of placed assemblies do not appear in game until the sub file is saved. (note: they do appear in the editor)

**Steps To Reproduce**
Open the sub editor. Place an assembly that contains wires. Press Test. While the components appear in game, the wires between them are invisible. Stop testing, save, press test. Now the wires do appear in game.

**Version**
V0.1100.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c784bd83de2b1f63ecbdeddc37751fa245a1b5c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
