### ISSUE TITLE
Prototype Steam Cannon particles phase through walls

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4180]
**Description**
PSC particles phases through walls, seems like a visual bug, doesn't damage entities behind said walls.

![PSCbug](https://user-images.githubusercontent.com/72674994/97783942-04a7f700-1bd6-11eb-8157-0ae366764d0b.jpg)

**Version**
[0.1100.0.1]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06f58e366cfc485f0c32584a4a8f6feeaf3f45d7

**Comment by Rokvach** [comment]
No issues, closing.
