### ISSUE TITLE
Others can hear psychosis sound effects from patients with psychosis 

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#4181]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Healthy players can hear psychosis affected players sound hallucinations (like shotgun shots, horns, crawler noise, siren)

**Steps To Reproduce**
Inject alien blood into another player (might work with AI too), stay near them and listen to the sound effects.

**Version**
v0.10.6.2 Win10

**Additional information**
None

**Comment by Xeavas** [comment]
@FLundin  #4165

**Comment by FLundin** [comment]
Merge or close this.. i missed it
