### ISSUE TITLE
Selling, or even just abandoning, submarines

### ISSUE THREAD

**Issue by Hawk777** [Regalis11/Barotrauma#4185]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is no way to sell or abandon a submarine (i.e. remove it from your list of owned submarines). #3110 touched on this a little bit, but there are other reasons than that why one might want to sell a submarine. The biggest one for me is if you’ve gone into the editor and made some more improvements to the submarine, you might want to sell the existing one (which is the old layout, since the submarine is copied into the save file) in order to buy the new one and get the improvements (which would otherwise be impossible since you can’t buy a second submarine with the same name as one you already own).

**Version**
0.10.6.2 for Linux

**Comment by ezjamsen** [comment]
We have no plans for allowing subs to be sold or abandoned at this point. A workaround is to treat modified subs as variants and name them accordingly so they can be differentiated in your sub inventory.
