### ISSUE TITLE
humanhusks can't deal damage to former crewmembers (and vice versa) if friendlyfire disabled

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#4186]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If friendly fire is disabled on a server, and someone from the sub crew turns into a husk, the husk and the remainning crew can't damage each other. I'm guessing this is because they're still technically part of the same crew?

**Steps To Reproduce**
Self-explanatory

**Version**
Win10, game ver. 0.10.6.2

**Additional information**
[Video](https://youtu.be/w_LSnrM0h9s)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26120046add90ebb8480fe50e2cad2939bc7a050
