### ISSUE TITLE
[0.1100.0.1] Ballast Flora needs a longer cooldown before they can weld doors again

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4190]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of the biggest struggle my crew had with Ballast Flora is when it's getting damage, it would repetitively weld doors we're trying to get through.

**Comment by 3e849f2e5c** [comment]
I've reworked how the ballast flora handles locking doors in https://github.com/Regalis11/Barotrauma-development/commit/f2aa35151657fd6b7b0186f9ddec433d56fcc8a0
It no longer uses welding logic and the ballast flora releases locked doors after its defense state ends which should make it less of a pain in the ass

**Comment by Rokvach** [comment]
No issues, closing.
