### ISSUE TITLE
[0.1100.0.1] Damaging Ballast Flora needs feedback indicator

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4191]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When fighting Ballast Flora, it's impossible to tell whether or not you're damaging it until it dies. Could either use health gauge, audio feedback, or visual feedback,

**Version**
0.1100.0.1

**Comment by 3e849f2e5c** [comment]
I've added particles when dealing damage to the branches in https://github.com/Regalis11/Barotrauma-development/commit/4ea19d8339b3b971092ceb205e6e2c81d6c25dac and darken the branches based on their health in https://github.com/Regalis11/Barotrauma-development/commit/365bfd06d35c60bb54fd9f3dd3fb6801cd29d86e

**Comment by Rokvach** [comment]
Just needs a damaging sound and a sound when the branch dies

**Comment by Rokvach** [comment]
Should already be on the todo list, closing as otherwise looks fine.
