### ISSUE TITLE
Texture issue with Stairs Right & Stairs Left

### ISSUE THREAD

**Issue by EricPfau** [Regalis11/Barotrauma#4193]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There appears to be a tiny bit of a different texture overlapping the stairs. See below for screenshot.

**Steps To Reproduce**
Place Stairs Left or Stairs Right into the Sub Editor and look beneath them for a small black square.

**Version**
0.10.6.2 Stable

![image](https://user-images.githubusercontent.com/73270156/97843242-f41b7d80-1cb6-11eb-99d9-46923167a85d.png)

**Comment by dinhtuananhfakefish** [comment]
Just fixed and pushed the new sprite

**Comment by Rokvach** [comment]
No issues, closing.
