### ISSUE TITLE
Submarine overlaps with an outpost

### ISSUE THREAD

**Issue by MaxJugger** [Regalis11/Barotrauma#4195]
Windows, v0.10.6.2.

It so happens that the structure of the boat is superimposed on the structure of the underwater base. The wish is to make the structures of the underwater bases so that the floors of the underwater base are slightly higher than the docking lock.
![20201102064158_1](https://user-images.githubusercontent.com/73727803/97853086-4f259280-1d00-11eb-974e-2f1d540eb73b.jpg)

**Comment by Regalis11** [comment]
Thank you for the report! We haven't seen this happen with vanilla subs, so I would guess it has something to do with the way the docking ports are setup in this custom sub. Which submarine is it? Is it available in the Steam Workshop, and if not, could you send it to us so we can give it a test and see if we can reproduce the bug?

**Comment by MaxJugger** [comment]
Yes, these are boats from the workshop, I faced this problem on several
boats. The link to the boat from which the screenshot was taken in the last
post
https://steamcommunity.com/sharedfiles/filedetails/?id=2121725686

пн, 2 нояб. 2020 г. в 18:23, Joonas Rikkonen <notifications@github.com>:
