### ISSUE TITLE
[Feature Request] Thermal artifacts should be more manageable with correct procedures

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4196]
### Why does this Feature request exist :
I felt that after observing plenty of interaction by players with thermal artifacts along with my general experience with it to submit this as a feature request on Github.

**Why is it a problem?**
- Relative to other artifacts, it is extremely "tedious" to manage, along with its yield not feeling rewarding for the effort spent. Thus generally when players identified the artifact as a thermal, they usually leave it behind as it is not "worth it" to deconstruct or bring onboard unless its for a mission (then in this case, chucking it in the airlock will do).

**Why is it a hassle to deal with thermal artifacts especially for the means of deconstruction or selling to stations?**
- Addressing the problems with attempting to deconstruct thermal artifacts.
Generally you don't have deconstructors in the airlock, case and point - vanilla submarines. Due to the nature of fire in an oxygen rich environment, because of how oxygen/welding tanks tend to spontaneously combust while in contact to even the slightest of fires and how little options you have on preventing the artifact from setting fire to the submarine constantly, it is generally not worth it to deconstruct said item for incendium bars. There is a way however currently, flooding engineering and submerging it in water, then deconstructing it. However in my opinion, this is not the ideal, for its relative reward and in the concern on singleplayer with bots (as they can't handle flooding that well).

- Addressing the problems with attempting to sell thermal artifacts to stations.
Attempting to sell thermal artifacts to stations is overly tedious, as it constantly set fires to your surroundings in open air, there's little way to prevent and/or find an option to sell the said artifact to shopkeepers. However, there's an overly convoluted solution, it is to flood the station to get to the shopkeeper. It is however, not ideal (you potentially can drown the people inhabiting the station, and effectively committing terrorism by flooding said station).

**Comparing the cost/effort and reward of thermal artifacts to other artifacts.**
- Faraday, can be managed by timing the movement between pulses, avoiding machinery. Yields valuable materials assisting in the fabrication of advanced batteries and fuel rods.
- Psychosis, relatively harmless and can be aided with haloperidol. Yields relatively useless materials in terms of fabrication, but offers decent rewards if able to be sold.
- Sky alien, drains oxygen rapidly, but can be transported safely with divesuits and masks. Yields valuable materials assisting in the fabrication of liquid oxygenite and oxygenite tanks
- Nasnov, relatively dangerous depending on environment, can be tackled with some preparation (Guns and ammo). Yields somewhat valuable materials assisting in the fabrication of better ammunition (railgun shells), however not as valuable for coilgun and harpoon ammunitions.
- Thermal, is extremely dangerous out of water and more time consuming than rest of the above, requiring submerging the area with the deconstructor in water to safely obtain the materials, either by cutting directly from outside the sub or by flooding a path right to it to obtain its yield. Incendium however does not offer an advantage given to warrant such effort. Incendium tanks are good, but due to the effort required, its much easier to just buy incendium bars from stations or get them from wrecks, rather than deal with given artifact, while selling it doesn't offer such a price that warrants the effort of currently flooding a path in the station to the shopkeeper.

### Proposed suggestions and goals of said proposal

**Goals of the proposal**
- To make the thermal artifact manageable with proper care and attention given, while not requiring it to be overly tedious relative to other artifacts for it to be rewarding.

**Proposed suggestions**
**1)** It should still give the person holding it burns, if its in open air.
**2)** It should not be setting fire to its surroundings constantly, but rather periodically.
**3)** It should be able to be suppressed for a short duration with fire extinguishers.

### Elaboration and reasoning behind the suggestions
**About :**

**1)** It offers a challenge to the person holding it, while separating it apart to the environmental hazard the artifact poses, this would require players to have some preparation against burns, i.e wearing dive suits, engineer clothing, while not being overwhelming due to it being separated from the environmental hazard in terms of damage/risk.

**2)** Fire produced by the thermal artifact should be controllable to an extent that it is still rewarding to warrant the risk of bringing said artifact onboard, this is intended to either randomly set fire to its surroundings at intervals, or periodically set fire after a specified amount of time akin to Faraday artifacts. That being, it will still pose a threat to an oblivious or underprepared crews, while still making it easier to bounce back in the event it becomes catastrophic.

**3)** There should be a preventable/manageable solution regarding the control of **2)** due to the nature of fire in this game, therefore it should be an option for any well prepared crew to be able to temporarily suppress the time for the intervals by 1 to 3 seconds, thus also giving some ability to safely sell thermal artifacts to shopkeepers. And with the advantage of this being more viable in singleplayer.

Thank you for reading this.
With best regards : Xeavas

**Comment by CallsignApollo** [comment]
I agree. One massive issue with getting an artifact to a deconstructor is the tendency for airlocks to be on the opposite side of the sub from the deconsructor. Engineering compartments are often at the bottom of a sub, and docking at outposts requires a topside hatch, if not a full on airlock.

**Comment by thegrb93** [comment]
It's simple. Power down ship. Fill with water. Security it in a closed room. Re-power ship.

**Comment by thegrb93** [comment]
I don't know the procedure for selling stuff though. If you have to take it to a store to sell it, I think you're kindof boned then.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/eef9ac2dd34e8cd65bbba4e70d4104e5bffc2762: the artifact now causes fires periodically, not continuously.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
