### ISSUE TITLE
New psychosis sounds play for all clients

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#4199]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players with psychosis play random sounds. These sounds, however, are audible by all clients, which shouldn't be a case.
Tested only on P2P, The effect could be different on dedicated servers.

**Version**
Win10, game build 0.10.6.2

**Comment by Xeavas** [comment]
Fixed in unstable, #4165
