### ISSUE TITLE
Don't kill the person on disconnect

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#42]
Basically, have the same "braindead" system SS13 has.
when someone disconnects out of a body, label them as (AFK). Once they reconnect they'll be back in their body like nothing happened.
Sometimes, I get force-reconnected for no reason and then have to sit out the entire rest of the round because of bugs. Desync issues can also be a huge pain in the ass.

**Comment by NilanthAnimosus** [comment]
I actually had successfully implemented this myself so its doable, but the client seems to have issues coping with it at times (Their inputs are ignored on the server side, though I attempted workarounds to this, or they crashed in the light manager during mid round sync, or other issues I had encountered over time)

My current method feels like more of a hack though, an official implementation of this would be nice (Mine simply keeps a list of the disconnected by name+IP, if both match and the characters still alive, give it back to them, both having a timer to auto-kill the character and keeps the character stunned for the duration).

but the bugs I currently get from characternetworking and clients still loading their games at times as it attempts to set the client character have made this a fairly awkward thing (I have even more bugs than I've listed with having done this server-side only).

I found quickly decrementing the characternetworkings "LastNetworkUpdateID" helps with control being frozen on reconnect yet I've had clients literally fail to control their character on set client character too.

Just figure I'd add my time "experimenting" with this over the last 8+ months.
