### ISSUE TITLE
Properly Compiled Dev Build Crashing 

### ISSUE THREAD

**Issue by acebud12** [Regalis11/Barotrauma#420]
Tried my hand at compiling the dev branch today, and found it wasn't working as intended. Assumed I did something wrong and reached out to the discord, but then it became prevalent that it probably wasn't a fuck up on my part, as I also tried a dev build that someone properly compiled themselves, and still it crashed. I have attached the crash report for reference. Just some extra information, I have compiled the master branch successfully and that has worked fine, and also vanilla works fine on my computer as well.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/2031230/crashreport.log)

**Comment by Regalis11** [comment]
Try installing the latest version of OpenAL from https://www.openal.org/downloads/

**Comment by acebud12** [comment]
Hey! That worked! Thanks man! I'll close this off now
