### ISSUE TITLE
New psychosis sounds are played server side

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#4200]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players with psychosis play random sounds. These sounds, however, are audible by all clients, which shouldn't be a case.
Tested only on P2P, The effect could be different on dedicated servers.

**Version**
Win10, game build 0.10.6.2

**Comment by Xeavas** [comment]
You submitted 2 identical issues #4199 

Its also a duplicate of #4165

**Comment by OverwatchVoice** [comment]
Posted twice by accident, my bad.
