### ISSUE TITLE
Coilgun Ammunition box condition indicator [feature request]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4201]
I feel that the game would benefit greatly if we could consolidate coilgun ammunition boxes that are partially empty, in the same way that SMG magazines can be combined. 

Also to add to this, it would be a great QOL addition to have a 'rounds remaining' indicator on the side of the case so we can see at a glance the current state of cases. Something similar to the battery/superconductor level indicator would be great, perhaps a clear window in the side showing the remaining rounds instead of a bright green LCD bar though.

As it stands we need to grab the case to check its remaining contents, then drop it again, which is laborious for anyone who is tasked to do this. 

As far as consolidating these boxes, it would be nice to be able to make it part of routine to replenish the coilguns with fresh ammunition at the beginning of a mission without having to dump partially empty cases, only to have to do the whole 'deconstruct/combine partial materials/reconstruct' thing.

**Comment by ezjamsen** [comment]
To be resolved later with another feature.
