### ISSUE TITLE
Can't use items if mouse cursor is over the crewlist area

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4204]
Noticed this issue on the level-overhaul branch, but should be the same on other branches as well

Repro steps:
1. Have crewlist open
2. Equip a weapon or a scooter (like on the picture)
3. Notice that you can't shoot with the weapon when mouse cursor is over the crewlist

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/af615f4d-f70d-4f08-bbf4-7fe7cfbcdc3d)

**Comment by OverwatchVoice** [comment]
Isn't this intentional? Same thing happens with all other hud elements

**Comment by Rokvach** [comment]
You are still able to use the item on other parts of the hud, only the crewlist fully blocks the usability of the item

**Comment by OverwatchVoice** [comment]
Didn't know that, probably unintentional then

**Comment by Udrakan** [comment]
Also, you cant click auto/manual switch on nav terminal while crew list is open I've noticed.

**Comment by ekqvist** [comment]
Fixed in 5610484

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
