### ISSUE TITLE
[level-overhaul] Level floor texture unloads depending on zoom

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4206]
Tested on dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/8f44a309a67abcab6c75945772099ee1a75a6cae

The level floor texture unloads if you zoom in to it in freecamera, its fully gone when viewing it as a character and allows you to go through it

Repro steps:
1. Generate a plateaubasic level on Level Editor and test it
2. Go to freecamera and travel all the way to the bottom left of the level, notice that the closer you get the more the floor texture unloads
3. Control a character and set godmode
4. Teleport character to the bottom left of the level
5. Notice that you can't see the floor texture at all when controlling the character, only visible if returning to freecam and zooming out

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/614007ec6b9e7e423cd8cf85224d7cd34862e879

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
