### ISSUE TITLE
[Unstable] Nest's sonar label is positioned incorrectly client-side

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#4208]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "monster nest" sonar label doesn't point to the actual position of the nest when playing a nest mission in multiplayer.

**Steps To Reproduce**
1. Start a nest mission
2. Follow the pointer on the sonar, notice that there's no nest/cave there

**Version**
v0.1100.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ca0601129cf10a00c9b660fa5aedd14463225d8

**Comment by OverwatchVoice** [comment]
Same thing kind of applies to monsters in monster missions - Players will have different distances shown on the sonar, with hosts having it displayed the closest (Maybe most accurately, too)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
