### ISSUE TITLE
[Unstable] Crashes in campaign when starting a mission.

### ISSUE THREAD

**Issue by pevifol** [Regalis11/Barotrauma#4209]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game sometimes crashes to desktop when starting the mission. Happened to me when doing a tigerthresher nest one.  Seems like the level generator is breaking itself trying to generate a cavern level. Crash seems to happen both on multiplayer and singleplayer.

**Steps To Reproduce**
It happens when starting a nest mission. 

**Version**
[0.1100.0.2]

**Additional information**
A log is attached.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5483326/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e7e39d3190a00cfa9517c5bc02e0497c3ae66e6

**Comment by Rokvach** [comment]
No issues, closing.
