### ISSUE TITLE
Holding 2 storage containers is glitching and combining graphics of the 2 containers [video attached]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4211]
Often when holding 2x storage containers the graphics glitch and show a combination of the 2 containers [shows 4x4 rows of items instead of the usual 3x4).

Items in the container underneath are able to be moved, whilst the ones that are showing are not able to be interacted with. The attached video[s] show exactly the steps that lead to this glitch. 

[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/5484735/Barotrauma.zip)

[Barotrauma 2.zip](https://github.com/Regalis11/Barotrauma/files/5485208/Barotrauma.2.zip)

**Comment by Regalis11** [comment]
Most likely fixed since the ticket was created, closing
