### ISSUE TITLE
Sub editor lighting uses one of the biomes light

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4213]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a83da9e2-6eaa-4281-92a4-61aac8a35e96)

**Comment by Regalis11** [comment]
This isn't really a bug, we've always used the ambient light value of the 1st level gen config to render the lights in the sub editor, now it's just different than before. But in any case, changed it back to 3,3,3,3 in 8750c98.

**Comment by Rokvach** [comment]
No issues, closing.
