### ISSUE TITLE
Overriding nav terminals in mods breaks custom interface buttons

### ISSUE THREAD

**Issue by Mezzokoko** [Regalis11/Barotrauma#4214]
**Description**
A mod overriding a navigation terminal will cause the labels for the custom buttons aswell as their signal output you can set in the sub editor to revert to default values.

**Steps To Reproduce**
1. Have a submarine use the customizable buttons on a nav terminal, using either or both a custom label aswell as a custom output signal.
2. Have a mod override the nav terminal.

Once ingame the buttons should read something like "SIGNAL #1" and always output a pulse of "1" when pressed.

**Version**
Barotrauma v0.10.6.2 (ReleaseWindows, branch release, revision d0702df35e)

**Additional information**
https://steamcommunity.com/sharedfiles/filedetails/?id=2236039375

I discovered this issue with this mod originally, but other mods in which I overrode nav terminals pretty much had an identical effect.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/baf32e6aa639b2e6098f6dc274bdb02b65dfe2e3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
