### ISSUE TITLE
Crash report (HumanAIController.HandleRelocation)

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4216]
Game crash when leaving alien structure site, report attached.

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5491463/crashreport.log)

**Comment by Regalis11** [comment]
Couldn't find a way to repro this, but added a null check that should prevent this from happening in https://github.com/Regalis11/Barotrauma-development/commit/028828fd985b4e130b577ce4a831ce82146817fa

**Comment by Rokvach** [comment]
There hasn't been any sightings of this since it was introduced to Unstable, closing for now.
