### ISSUE TITLE
Ruin spawned in level roof

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4218]
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/db7e3e5f06897972d635102bb70ed28c49e836ee

Screen: Level Editor
Level type: plateaubasic
Seed: 43terfge

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c4d05133-03ff-4b78-b670-51be3603c968)

Level type: ridgebasic
Seed: 43tgeg

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ab28131e-5852-4ee9-b57f-0816d851194b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/533fbbcad8f1dd3895c3ec892a8b90ed63626193

**Comment by Rokvach** [comment]
Tested, haven't been able to reproduce. Working correctly. Closing.
