### ISSUE TITLE
How To Use A Mod?

### ISSUE THREAD

**Issue by StoneHeartSteamUser** [Regalis11/Barotrauma#422]
So How Do I Make A Mod Work?

**Comment by StoneHeartSteamUser** [comment]
Also I Keep Losing The File After Downloading on Your Website :< I Wished it Would Atleast Appear When I Search it In My Files.

**Comment by BlueTheKing** [comment]
What shortcut? You can run the game from the .exe, screenshots would help.

Also no need to capitalize every word.

**Comment by StoneHeartSteamUser** [comment]
Well When I Download This Game and Then Scroll through  The Files I Have To Extract The Files Due To The Folder Being "Zipped" So Then After Extracting I Select the Launcher.Exe And
 Set it To my TaskBar
I Do The Same For BaroTrauma.Exe Then it Says That this Game Requires Another way To Open the Game When I Go to look For It In The Files I Can't Find  The File it Seems To Delete its Self From My Computer On My Second Time of Playing The Game, I Simply Reinstall it Every Time But It Keeps Saying That It Requires Another Way Of Launching Every Goddamned time.
-StoneHeartSteamUser.

**Comment by Regalis11** [comment]
What happens if you try to launch either of the exes directly instead of attaching them to your taskbar? Could you take a screenshot of the "Requires Another Way Of Launching" error? 

I would also like to restate that there's no need to capitalize every word, it makes you text much more difficult to read.

**Comment by StoneHeartSteamUser** [comment]
Like ive said the files seem to have a way of uninstalling on second use. Im typing away from my cp ill send a video on youtube in the next few days ill keep you posted though.

**Comment by BlueTheKing** [comment]
There is no way that files just delete themselves, what does "hard to find" mean? 
You install the game by extracting files from an archive and you pick where you want it installed.

**Comment by StoneHeartSteamUser** [comment]
Ill upload vids soon

**Comment by StoneHeartSteamUser** [comment]
Damn It Well I Tried to Find The Launcher in the Folder But Everything Was Empty I Found That odd.

**Comment by StoneHeartSteamUser** [comment]
Is  There Any Simple Way To Open The folder And Find A----- FUCK I can't make these 

Forget it ill just install the game everytime it doesn't launch ill just redownload
it only takes 3 mins anyway.

**Comment by BlueTheKing** [comment]
Files don't delete themselves, send a screenshot.

**Comment by StoneHeartSteamUser** [comment]
HOW?

**Comment by BlueTheKing** [comment]
https://www.take-a-screenshot.org/

**Comment by StoneHeartSteamUser** [comment]
Im not good at this sort of stuff!!!!
how to screenshot????????

**Comment by StoneHeartSteamUser** [comment]
uhm okay...

**Comment by StoneHeartSteamUser** [comment]
i don't need that i just need to know a simple way to keep track of all the files the way it is

**Comment by BlueTheKing** [comment]
What would that be? You extract the archive where you want the game to be, it doesn't go anywhere.

**Comment by StoneHeartSteamUser** [comment]
you know when you download it and then you extract it, after that you go to launcher or the actual game
well when i close that to go to sleep at night then come back i can't find it among my files 
any way to keep track of it?

**Comment by StoneHeartSteamUser** [comment]
also the BaroTrama launcher doesn't work on third use is that supposed to happen???

**Comment by StoneHeartSteamUser** [comment]
and yes the game won't work on third use either.

**Comment by BlueTheKing** [comment]
No, what is your OS, exact. Files don't move on their own so your antivirus or something else is messing with it.

**Comment by StoneHeartSteamUser** [comment]
OS?

**Comment by StoneHeartSteamUser** [comment]
im not very good at computers so i hope you don't mind.

**Comment by BlueTheKing** [comment]
Operating System

**Comment by StoneHeartSteamUser** [comment]
Like Windows?

**Comment by BlueTheKing** [comment]
Yes

**Comment by StoneHeartSteamUser** [comment]
Windows 10.

**Comment by StoneHeartSteamUser** [comment]
My Security On My Cp Is Avast Internet Security.

**Comment by BlueTheKing** [comment]
If your game keeps disappearing turn your antivirus off.

**Comment by StoneHeartSteamUser** [comment]
So Disable Avast, Alright.

**Comment by StoneHeartSteamUser** [comment]
can you make some sort of backup launcher for the game so if this happens again ill have a plan b?

**Comment by StoneHeartSteamUser** [comment]
also what scripts will launch the game?

**Comment by BlueTheKing** [comment]
What? Sending a single message is enough. What do you mean by scripts?

**Comment by StoneHeartSteamUser** [comment]
One Question, How Do You Use Mods That You Have Installed?

**Comment by StoneHeartSteamUser** [comment]
Also Ive Fixed This Issue Now Ill Close It When I Get This Mod To Work.

**Comment by StoneHeartSteamUser** [comment]
Sooooo How Do You Use Mods?

**Comment by StoneHeartSteamUser** [comment]
oooh no I screwed up.

**Comment by BlueTheKing** [comment]
Run the launcher and pick the content package you want to use.

**Comment by StoneHeartSteamUser** [comment]
oh okay.

**Comment by StoneHeartSteamUser** [comment]
it didn't work.

**Comment by StoneHeartSteamUser** [comment]
so again how do I make the mod work?

**Comment by BlueTheKing** [comment]
Im not sure what you could've done wrong but the github is used for **vanilla** bugs/problems. 
For mods you should go to the forums.

**Comment by StoneHeartSteamUser** [comment]
I can't log in there :P

**Comment by StoneHeartSteamUser** [comment]
i just need help with it.

**Comment by StoneHeartSteamUser** [comment]
anyway i installed this mod called ww2 mod

**Comment by StoneHeartSteamUser** [comment]
and it won't seem to work for the game.

**Comment by StoneHeartSteamUser** [comment]
is there anything to do that i may of missed?

**Comment by StoneHeartSteamUser** [comment]
nvm i fixed

**Comment by StoneHeartSteamUser** [comment]
gg
