### ISSUE TITLE
SMG Rounds spawning on every characters with SMG every round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4220]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
SMG Rounds spawning on every characters with SMG every round

**Version**
~0.1100.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd54cfd1e69bc99ac267235d010d6b458a894be0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
