### ISSUE TITLE
[0.1100.0.3] Linked Submarines to any Subs are failing to spawn in

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4221]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Could not find the method "Load" in Barotrauma.LinkedSubmarine.

**Version**
0.1100.0.3

**Info**
Both SP and MP.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f154b44c7b14c586e63db21d9c3d75fd2a715fb5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Nvm, noticed that linked subs aren't docked to the main subs now

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/085fe426-6463-4e4f-87da-94c5786b56eb)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/977d06e6b63a6786b79705c9b1a1dc1a8304d943

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
