### ISSUE TITLE
Brain Damage Affliction Nerf [FEATURE REQUEST]

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4222]
- [✔] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When disconnecting or crashing from a server, an (estimated) 30-second countdown is applied to the disconnected player, to which at the end of the countdown, they die due to Brain Damage Affliction, and are unable to control their character. Even if the player is in the lobby, their character will still die under the affliction due to not spectating their player in time because of the rather strict time restraints.

This is more of a suggestion than a bug, because as of now, the Brain Damage Affliction is working as intended towards players that disconnect after wrongdoings or simply want to leave, but leave players (such as myself) unable to start, load into, or were simple forced to stay inside the server due to a networking issue, are unable to continue playing.
![image](https://user-images.githubusercontent.com/72813628/98280514-82b72580-1f69-11eb-9738-6870fac95282.png)
Most crashes from my end result in level objects causing a large spike in GPU usage as the game loads in every scene piece at once, causing a GPU error. Though this is the result of faulty hardware and poor specs, a workaround for this would be appreciated as a to players that experience consistent disconnects because of networking issues, or as previously said, crashes, by either:

**A.** Nullifying the Affliction if the player is connected and inside the lobby, but not inside the game (i.e. spectating),

or:

**B.** Increase the time the affliction takes to kill the player. Maybe something like ~3 minutes? Past that point, the disconnected player would most likely not return (5 minutes is stretching it a bit too much, almost nullifying the buff, causing it to not appear as often, etc). Players can still loot and hurt the patient's body in this form, but it gives the afflicted player time to boot up their game, reconnect, or in extreme cases, restart their computer.

or **C.** if you guys come up with something 😳

**Steps To Reproduce**
1. Join a server, and start a game
2. Disconnect for a little over ~30 seconds to a minute, before rejoining (if re-joined in under this time period, stay in the lobby).
3. Spectate, and see that you are not forced back into the player's perspective, and rather, the spectator's.

**Version**
10.6.2, unstable, etc.

**Additional information**
ᵖˡᵉᵃˢᵉ ᶦᵐ ᵇᵉᵍᵍᶦⁿᵍ ʸᵒᵘ

**Edit:** Though this can be negated by enabling cheats, reviving the player, and setting the client character to the afflicted player, there comes a roadblock in communication when you are communicating via spectator chat in public games, so it is most likely the case that the affected player will have to wait upwards of 20 minutes to continue playing, or ironically, repeat the process all over again with another crash/disconnect in the next round.

**Comment by Regalis11** [comment]
Increased the time to 5 minutes in https://github.com/Regalis11/Barotrauma-development/commit/6b9c0005e62cd10d2c069247746647a671b5721d.

As a side note, there's no "brain damage affliction". :) There's no special affliction applied to the disconnected players, the character is just automatically killed if the player doesn't rejoin within a certain amount of time (which can be configured by the server host).

**Comment by Rokvach** [comment]
No issues, closing.
