### ISSUE TITLE
[0.1100.0.3] Multiplayer - Destructible environments are not destructible

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4223]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Destructible environments are not destructible in multiplayer.

**Version**
0.1100.0.3

**Comment by Xeavas** [comment]
I can confirm this can't be replicated in singleplayer.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0bd06ef7b946c0ffd0ea5370ea21bdd1619a02b3

**Comment by Rokvach** [comment]
No issues, closing.
