### ISSUE TITLE
Voice chat: annoying noises

### ISSUE THREAD

**Issue by Thanaen** [Regalis11/Barotrauma#4225]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

When using the in-game voice chat, and while speaking through the radio ( it doesn't happen with the local voice chat), there are annoying noises. It sounds like "clics clics clics clics". It's really to hard to explain. So I've just published a recording of a game we just made. 

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Simply use the in-game voice chat.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

0.10.6.2

**Additional information**

Here is the video mentioned earlier: https://www.youtube.com/watch?v=FJi9cpnry8I&feature=youtu.be
It's a bit long. But it sure happens at 7 seconds, 50 seconds, 2 minutes and 10 seconds,  3 minutes and 12 seconds, etc.
On this specific run, and for me, it wasn't happening a lot. But it happened a lot more frequently for some of my crew mates.

Playing on Windows 10, 2004, v19041.610.

Thanks for reading !

**Comment by Regalis11** [comment]
Thank you for the report! I'm closing this one since we have an existing ticket about the issue (#1683)

**Comment by Regalis11** [comment]
Didn't notice the existing ticket was in our private repository: I'll keep this open instead and close the existing one.

**Comment by Regalis11** [comment]
Added a console command ("togglevoicechatfilters") for disabling voice chat filters to help diagnose this: https://github.com/Regalis11/Barotrauma-development/commit/5b1ab120d98fe0b5f8003883b34ab1a337df6c9b

When it occurs, we should try disabling the filters and see if it affects the crackling.

**Comment by Rokvach** [comment]
Tested during a internal play session, the crackling does still exist in some form with the filters disabled but it doesn't get out of hand like it did previously nor happens as frequently. So you can only hear crackle when someone actually says something rather than when they have their mic on but aren't saying anything and even this doesn't happen as often. So the crackle is more confined when the filters are disabled but not fully fixed.

**Comment by Regalis11** [comment]
> had to give rights to use it per player even if I had given them all the command rights.

This should not be the case, it's a client-side command that should be possible to use without any permissions.

**Comment by Rokvach** [comment]
Issue seems to only exist in dedicated server
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4b9cb67b-a932-4a6c-8fc7-fc3b022ac39c)

**Comment by Rokvach** [comment]
Seems to also happen on SteamP2P server when playing as a client

**Comment by Rokvach** [comment]
Did a smoketest on this, the radio voice chat quality is a lot worse than the local voice chat. Everything I said in radio had crackling on the background whilst when using local the voice was a lot more clearer and there wasn't any type of crackling going on. I also tested with voice chat filters disabled but that didn't seem to make any difference, maybe the command is broken on this branch or the radio quality is just in general so bad.

**Comment by Rokvach** [comment]
Did a new test after some recent fixes and the crackling is mostly gone now, there can be couple crackles at times when starting to speak on voip when using local voice chat or when filters has been disabled.

**Comment by Rokvach** [comment]
Tested and didn't find any issues with this. Can be merged to dev

**Comment by Rokvach** [comment]
This can be closed when the merge is done

**Comment by Rokvach** [comment]
Just needs some small tweaks still but otherwise a major improvement to the voip so closing this already as its working

**Comment by Thanaen** [comment]
Hello ! I can't wait to test the VOIP again now that it's fixed. Do you know approximately when the update will be available on Steam?

**Comment by JoneKone** [comment]
Yeah it's not fixed.

**Comment by Rokvach** [comment]
Coming in the next update, already playable on Unstable
