### ISSUE TITLE
Searchlights misaligned when scaled.

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#4227]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Searchlights do not align to base when scaled down. Rotating them by one degree fixes the problem for me.

**Steps To Reproduce**
Spawn searchlight. Reduce scale.

**Version**
v0.10.6.2 Windows 10

**Additional information**
Other entities might be affected. I did not test them.

**Comment by Working-Joe** [comment]
fairly certain this also applies to other turrets such as coilguns and railguns.

**Comment by Regalis11** [comment]
@3e849f2e5c Addressed in https://github.com/Regalis11/Barotrauma-development/commit/64d5e6b0?

**Comment by 3e849f2e5c** [comment]
Yeah, this was fixed for coilguns so it fixed it for searchlights too since they use the same Turret component

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
