### ISSUE TITLE
[0.1100.0.3] Multiplayer Campaign - Selecting Mission Desync

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4230]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Half of the time the host selected a mission in campaign, it ended up being No Mission.

**Version**
0.1100.0.3

**Comment by Kaillera** [comment]
Some of the times players will receive the no mission dialogue when they are leaving the station, but will have the mission when the level load.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62d2957e2b9f8cb10e4f0794eef9babd64440f2c

**Comment by Rokvach** [comment]
Tested, looks to be working correctly now. Closing.
