### ISSUE TITLE
[0.1100.0.3] Multiplayer - Beacon Station items were desyncing

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4232]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was playing with a group, and after some levels in campaign we finally got the new beacon mission. We went to the station and fixed the whole outpost up. Problem was some items desyncing:

Oxygen Generator - For some reason when I wired the power to the junction box, we could hear the machine running, but the oxygen tanks we inserted wasn't filling up.

Large Pump - For some reason when I wired the power to the junction box and turned it on, the water level of the hull the pump is in drains, instantly refilll water, and drain. Repeat.

Lamps - The lamps all stayed off even though there were power.

This leads me to believe it could be possible that the mission completion could probably be affected by the sonar monitor not actually being powered server-sided.

**Steps To Reproduce**
Play with people for several rounds
Pick up Beacon mission
Fix station

**Version**
0.1100.0.3

**Additional Information**
Not sure if #3121 is related.

**Comment by Regalis11** [comment]
Possibly fixed in Regalis11/Barotrauma-development@0059175

**Comment by Rokvach** [comment]
No issues, closing.
