### ISSUE TITLE
Additional shortcut keys (and ideas) to help with navigation [feature request]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4235]
I propose that the availability of some shortcut keys be provided, to assist with piloting the sub through the navigation terminal.

1. A shortcut key for manual ping of sonar, or at least a key that can change the toggle state of the sonar switch.
**Reason:** This will save having to drag the mouse across the screen to double click the sonar every 10 seconds or so, just to make it pulse on/off. The toggle switch is there for those captains who want to light up their sub like a christmas tree, attracting the attention of everything within 100+ meters. But for those captains who are more inclined towards a stealthy approach, it provides a way of keeping the mouse cursor over more important things. To add to this, the ability to control the directional ping's 360 degree radius with something more tactile like the mousewheel could be a really pleasant way of implementing the directional ping feature in a way that is a little less 'clicky'.

2. A shortcut key to bring the submarine to a halt in the same way that flicking the toggle from manual control to autopilot does.
**Reason:** When manually piloting, it would be beneficial to be able to hit a key to recenter steering bringing the sub to a halt over its current position. The number of reasons for doing this are many as I'm sure you can guess, but to throw a few out there, a few may include; positioning the sub over a specific spot on a wreck, quickly jumping from a navigating char to a char of another profession or even just pulling up the sub hard due to the sudden appearance of an underwater structure, desired resource, nasty creature within perfect turret radius, shout from a fellow crewmember regarding the still missing diving suit as you leave the wreck, etc.

3. Shortcut keys to jump straight to NPC crewmen.
**Reason:** Oftentimes you need to jump from your current char to another NPC. Currently as it stands our crew are ordered in the way that they are purchased without any way of changing this order (which by the way, is also something I'd also love to see changed). It would benefit players greatly to have the option of being able to jump instantly from navigating, straight to a particular char without having to run down through the entire list to finally realize you jumped one or 2 over... and then need to jump back a couple. To add to this, it could be nice to see on the status monitor screen, where the crewmembers actually are. perhaps this could be some sort of 'status report' showing an icon that only updates upon request.

A couple of other ideas that I had in regards to managing NPC would be giving us the option to remove or clear entirely the job history shortcut buttons in the char navbar. Reason being, its frustrating to clear up problems when a char has been assigned to the wrong job (especially a wrong weapon) This could also probably be helped slightly by giving each gun a unique colour or number.

Also it'd be very stress relieving to have this job history assignment save on each char between docking/missions. This would mean we wouldn't have to reassign the exact same thing to each and every char EVERY time we jumped back in the sub for another dive.

Most people these days have mice/keyboards with a plethora of macro buttons just waiting to be assigned so that we can tailor our unique experience of games, provided we have the option in games to do so.

**Comment by Regalis11** [comment]
Thank you for the request!
We are only using the issue tracker for reports about bugs and issues. Please post feature requests and ideas on Barotrauma's [GitHub discussion board](https://github.com/Regalis11/Barotrauma/discussions).
