### ISSUE TITLE
[SUB Editor] Error when placing legacy medical fabricator

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#4236]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon placing legacy medical fabricator in sub editor error message pops-up
Error in item "Medical Fabricator": There is not enough room in the input inventory for the ingredients of "Pomegranate Extract"
- Old medfab has 4 input slots and new one has 5, but some new blueprints require 5 input positions.

**Steps To Reproduce**
Spawn legacy medical fabricator in sub editor

**Version**
From stable 0.10.6.2 to unstable 0.1100.0.3 (Windows 10 x64)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7fde8791e0572cd9f416ee3a3000357375c5c820

**Comment by Rokvach** [comment]
No issues, closing.
