### ISSUE TITLE
Battery Shadow Non-Gradient

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#4237]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Large battery shadow is solid and not gradient (like shelf shadows).
![battery](https://user-images.githubusercontent.com/52981993/98393387-d20b5d80-201e-11eb-90f3-a75e09071d51.png)

**Steps To Reproduce**
Spawn (large wall) battery.

**Version**
v0.10.6.2 Windows 10

**Additional information**
None.

**Comment by Regalis11** [comment]
This is not really a bug: it's not intended to be a shadow but a solid base of the battery.
