### ISSUE TITLE
[Request] Craftable Metal Crate/Duffel Bags

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4238]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Craftable Metal Crate/Duffel Bags. Mission mode has no access to crates.

**Version**
~0.1100.0.4

**Comment by Xeavas** [comment]
I agree on crafting metal crates, for campaign and mission mode, however I disagree on duffel bags being craftable, It is currently the most efficient at carrying things, while its original intention was for storing items of dead corpses once they despawn. I much rather have specialised storage crates/carts for looting/transporting things, or wait for the inventory overhaul.

**Comment by ezjamsen** [comment]
Thanks for the suggestion, we're likely to expand storage options in future updates, but craftable duffle bags are probably not on the agenda as far as things look for now
