### ISSUE TITLE
Don't play Leaving Start Location at outposts

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4239]
[Feature Request, Music]
Now that we're getting more custom music for individual locations, it would probably be an improvement in every way if "layer 3- leaving start location" didn't play a single time before playing the "main outpost track" (whether that be just normal calm music or a location specific track). leaving start location is already extremely overused (it literally plays in every gamescreen possible) and has a very "negative", "calm before the storm" aura that doesn't really make sense for outposts (which are supposed to be safe havens).

**Comment by Regalis11** [comment]
Changed in https://github.com/Regalis11/Barotrauma-development/commit/46fd17c376e75ab0d3ab189f4842ee52b5ecc9a8

**Comment by Rokvach** [comment]
No issues, closing.
