### ISSUE TITLE
Unstable - Autopilot not working properly with the new level generation

### ISSUE THREAD

**Issue by Mikolaj1900G** [Regalis11/Barotrauma#4242]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The autopilot seems to get confused often and tries to squeeze sub through passages that are way to small for it. Even when trying to go another way manually for a bit to try to set it to a "correct" course it will still try to go back and follow the previous, not big enough path if turned on again.

**Steps To Reproduce**
Start a mission in cold caverns and flip the autopilot switch on with the option to go to the next station.

**Version**
Unstable 0.1100.0.4 Windows

**Additional information**
![Autopilot1](https://user-images.githubusercontent.com/57800630/98421676-2a2b7980-208a-11eb-8003-a4fd457814fe.png)
![Autopilot2](https://user-images.githubusercontent.com/57800630/98421678-2b5ca680-208a-11eb-951f-640813ab50af.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e37495697ab8b15736013ae0c3888e882886ffda

**Comment by Rokvach** [comment]
- [ ] Looks like autopilot takes quite a long time to choose which path it should take, I tested on a plateaubasic biome and the sub just ram in to a wall when it needed to decide if it needed to go up or down, after 3-5 minutes it started to move down

Seed: DkY5GDFb

How I tested was to set captains helm skill (setskill) to 100 and let the bot operate the nav terminal set to travel to the destination and I just let it ran from the start

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7fcc0fa8-aa7e-4d8a-8f09-266be86741b5)

- [ ] Another issue, autopilot doesn't know how to navigate when the sub is already going through a side path, I think autopilot should adapt to the new path, having it to adapt to the closest path might however cause some decision issues on cross sections. 

How I tested, used the level generated with the seed above and teleported the sub inside the side path at the top, set it to autopilot and watched how it was just not moving anywhere

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6935a959bed7b74fffe3ef374e45b3c5da0f4b0

**Comment by Rokvach** [comment]
Seems to be struggling if there's a spier coming from top and bottom of the path, otherwise seems to be navigating really well

First level on this save:
[https://app.zenhub.com/files/93301055/25d82d3c-8dcc-4f22-a1f6-baa967912ab4/download](https://app.zenhub.com/files/93301055/25d82d3c-8dcc-4f22-a1f6-baa967912ab4/download)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5d6a0269-b109-438f-b060-3eda20b991a7)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/80d12697-f36e-4da9-a1d2-12fefc4d856d)

**Comment by Regalis11** [comment]
The autopilot is intentionally very cautious around spires, which sometimes leads to situations like this, but I think we can leave it as-is (it's fine if a human player has to sometimes step in to help the autopilot).
