### ISSUE TITLE
Switch "state" option changing when editing in "edit mode" and "wiring mode"

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#4243]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When in the sub editor (edit mode), a switch with the "state" option checked will deselect after editing the same switch in wiring mode.

**Steps To Reproduce**
Spawn switch. Check "state", so that the box is filled in. Switch to wiring mode. Edit the switch in wiring mode. Check "state" option again.

**Version**
v0.10.6.2 Windows 10

**Additional information**
None

**Comment by Regalis11** [comment]
Duplicate of #3890. Should be fixed in the latest unstable version, and the fix will be included in the next update.
