### ISSUE TITLE
French translation: problem with labels in reactor wiring

### ISSUE THREAD

**Issue by nenyx** [Regalis11/Barotrauma#4244]
This is about some translation errors in French for the reactor's wiring panel labels:
![reactor_panel](https://user-images.githubusercontent.com/16745801/98442928-5be32580-2108-11eb-8bca-8d771bcc8191.png)

Power out:
In French "Sotie_énergie". R is missing: "Sortie_énergie"

Load_Value_Out:
In French: "Charger valeur sortie" which is a word-by word translation with no meaning in French.

Suggestion: "Sortie_charge", since "charge" is already the word used in electric panels.

Fuel out:
In French "Fuel out" in a reactor's wiring pannel is translated as "Carburant épuisé", which means "Out of fuel". But "Fuel out" send the remaining fuel quantity.

Some suggestions:
Litteral translation: "Sortie carburant"
More explicit translation: "Quantité carburant"

Thanks :)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e774d6e
