### ISSUE TITLE
[0.1100.0.4] Cave missions are too far for WIFI drones to reach

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4245]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The vanilla 200m WIFI range on drones are too short for them to reach the destinations. I propose we change the default WIFI range to 500m (which is just enough in most cases). I tested this by using my custom sub with 400m range and it was only able to get half way into the caves.

Edit: How about we do Wifi Range upgrades that may triple or quadriple the range?

**Version**
0.1100.0.4

**Comment by ezjamsen** [comment]
@Regalis11 The cave placement is going to change, if it hasn't already, right?

**Comment by Regalis11** [comment]
They haven't been changed yet (and won't be for this update), but I'm planning on improving the placement logic to get the entrance closer to the main path and prevent situations where you have to swim hundreds of meters through a tunnel just to get to the entrance. But I think increasing the range is still worth considering, 200 m is very little and severely limits the usefulness of the drones even outside cave missions IMO.

**Comment by ezjamsen** [comment]
Alright. Let's push this out to 400m and test.

**Comment by Rokvach** [comment]
No issues, closing.
