### ISSUE TITLE
Poor handling of read-only save game files

### ISSUE THREAD

**Issue by Hawk777** [Regalis11/Barotrauma#4247]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a `.save` file is read-only, some very odd behaviour can occur, including loading fine but the mission selection screen Start button not doing anything, potential multiplayer desyncs, and crashes. It would be nice to catch I/O errors during file access and report a proper error message to the player.

**Steps To Reproduce**
Make a `.save` file read-only and then try to play it.

**Version**
0.10.6.2 for Linux

**Comment by Hawk777** [comment]
[test.zip](https://github.com/Regalis11/Barotrauma/files/5505314/test.zip)

**Comment by Hawk777** [comment]
I am uncertain if this might be related to #1312, but it seemed that that bug was different, that the mission would start but the submarine would remain unable to move, rather than that the mission would not even start.

**Comment by Hawk777** [comment]
Turns out this is caused by save files being read-only, and presumably errors being reported when the game tries to write to them. Would be nice to catch file access errors and report a proper error message to the player.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
