### ISSUE TITLE
[0.1100.0.4] - hitscan/stun weapons do not aggro outpost bots/security

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4249]
**Description**
Self-explanatory, using either SMG, Revolver, Shotgun, Stun Baton or Stun Gun shooting/attacking outpost bots/security will not aggravate them and thus not result in a proper response.

**Steps To Reproduce:** N/A in desc
**Version :** [0.1100.0.4]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97e22408b589c245780be2f0ff9fdd58dfe983fc and https://github.com/Regalis11/Barotrauma-development/commit/d232624f1631ee6adda8cda499973d9b20e5834d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
