### ISSUE TITLE
Weird behavior with mirroring coilguns (and possibly railguns)

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4251]
- [x]  I have searched the issue tracker to check if the issue has already been reported.

**Description**
Saving and reloading saves with mirrored coilguns results in them displaying in orientations not seen when you saved it, resulting them either flipping back to it's "default" orientation along with its angle being changed due to said adjustments. Saving and reloading it again results it in returning to the orientation and turret angles you previously set, thus you can keep flipping by saving and reloading.

**Steps To Reproduce**
Mirror a coilgun, leave one in its default, mirror one by x, mirror one with y, and mirror the last with x+y, save and reload for result.

**Version :** Tested in [0.1100.0.4], but heard from others than it's present in stable too.

**Additional information** (example subfile provided below)
![cgm1](https://user-images.githubusercontent.com/72674994/98454299-1e30dc00-219e-11eb-8fef-bcbe3d9f9566.jpg)
![cgm2](https://user-images.githubusercontent.com/72674994/98454301-1f620900-219e-11eb-9493-a1ac68e37d61.jpg)

**Example Subfile** _Note the setup with the red background_
[CGMTest.zip](https://github.com/Regalis11/Barotrauma/files/5505708/CGMTest.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8958e1e05d196eb8d794253f6ffc2f041961e3de

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
