### ISSUE TITLE
Crash when switching between bots from ruins to a bot using a coilgun

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#4252]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was exploring ruins in singleplayer. I switched to a bot who was still aboard a submarine, who was also controlling a coilgun.
As the camera was moving to the second bot, the game crashed. Crash log attached.

**Steps To Reproduce**
Unkown, I think?

**Version**
Win10, build 0.10.6.2

**Additional information**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5506313/crashreport.2.log)

**Comment by Regalis11** [comment]
Thank you for the report! We have an existing ticket about this (Regalis11/Barotrauma#4104), but the report in the ticket doesn't have line numbers, so this one should make it much easier to diagnose.
