### ISSUE TITLE
Toolbelt Z-fighting on characters wearing body armor

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#4253]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The toolbelt item sometimes flashes in and out of existence on characters who are using a periscope and wearing body armor.
This seems to happen only when the camera is being moved.

**Steps To Reproduce**
Self-explanatory

Version
Win10, build 0.10.6.2

[**Video**](https://youtu.be/zkqiS8LS5C0)

**Comment by Ek-Videogames** [comment]
This appears to also happen on custom-submarines with _weird_ sprite-depth settings, if you interact with a chair or ladder or periscope which forces your character into a sprite depth that ragdolls cannot feasibly reach, it 'squishes'  your character into all limbs having the same sprite depth.

**Comment by Rokvach** [comment]
Not a issue anymore, closing.
