### ISSUE TITLE
[Multiplayer only] Delayed Status Effects attempt to be executed even after the target is removed.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4254]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A status effect with a certain amount of delay should not work if a character is removed prior to end of the delay. This works perfectly fine in singleplayer, however in multiplayer the game will throw an error such as this:
![reeeeeeeeeeeeeeeeee](https://user-images.githubusercontent.com/9964331/98467020-63bbcc00-21d3-11eb-9e46-847230ba7ca3.png)
Caused by the status effect attempting to activate even after the character has been removed. Currently this issue is best observed through the use of mods.

Example of a simple status effect that will cause an error:
![reeeeh](https://user-images.githubusercontent.com/9964331/98467384-3cfe9500-21d5-11eb-95e1-b268c18fa710.PNG)

This status effect is meant to simply remove a character after the specified delay. This does not cause any issues in singleplayer, however in multiplayer, this will force the console to open displaying the error in the screenshot above, and depending on how many of these characters are present in the game, this would cause the console to constantly open each time the characters despawn, interrupting gameplay.

**Additional Information**
Don't know if this is worth opening a new issue for, however, looking at the same status effect above, you'll notice that it also includes two particle effects. These will work fine in singleplayer, however in multiplayer they are delayed by about 1.5 seconds. Due to this delay they will not be shown at all, since the character has already been removed by then. The same goes for sounds.

**Version**
v.0.10.6.2 (Stable)
v.0.1100.0.4 (Unstable)
Occurs in both.
Operating System: Windows 10.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f72085ed157d850dcc4e45324ebce8e5a08ee43f

**Comment by Emanthealmighty** [comment]
Does this address the issue described in "Additional Information" or shall I make a different report for that?

**Comment by Regalis11** [comment]
This only addresses the 1st issue. 

The 2nd issue occurs because the status effects runs 90 seconds _after the character has spawned_, and it always spawns a little later client-side than server-side (both due to latency and the extra time the client takes to load the textures and sounds). Because of this, the "always" effect may not have enough time to run before the server removes the character. It should however be possible to work around the problem by putting the particles in an OnDeath status effect and creating a delayed status effect that kills the character after 90 seconds.

**Comment by Emanthealmighty** [comment]
Fixed in version v.0.1100.0.5

**Comment by Rokvach** [comment]
Thanks! Closing.
