### ISSUE TITLE
Head is not focused when holding right mouse button

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#4255]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![602960_20201108154502_1](https://user-images.githubusercontent.com/62313026/98469885-15f69200-21da-11eb-90ea-1dd8f43e7104.png)
When holding the right mouse button on an equip-able weapon/tool, the head does not look at the crosshair.  Please fix it.

**Comment by Regalis11** [comment]
Thank you for the ticket! This is not really a bug though, just something that hasn't been implemented. We have a ticket about this in our private repository (Regalis11/Barotrauma-development#1677) and generally avoid having feature requests in the issue tracker, so I'll close this one.
