### ISSUE TITLE
Crash when wiring linked+sideUI fabricators/decons

### ISSUE THREAD

**Issue by MGZoltan** [Regalis11/Barotrauma#4256]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description & Reproduction**
The game crashes reliably when attempting to open the wire connection of a fabricator or deconstructor when they are linked, and their UIs marked to appear side-by-side. 
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/5506973/crashreport.3.log)

**Comment by Xeavas** [comment]
Duplicate of #4160
Fixed in unstable

**Comment by MGZoltan** [comment]
Ah, whoops. I did look and didn't see it, but I'm blind evidently. Cheers.
