### ISSUE TITLE
SMG Round is ejected when deconstructing an SMG magazine [bug]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4257]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deconstructing "smg magazine" spits an "smg round" out of the empty deconstructor onto the ground

**Steps To Reproduce**
Place [empty] smg magazine into an empty deconstructor, hit 'deconstruct' button.
_Expected Result:_ Plastic piece in the deconstruction output
_Result:_ smg round is ejected onto the ground beneath the machine, and no plastic 

**Version**
v0,1100,0,4 [unstable] - Windows 10 x64 [v19041.572]

**Additional information**
Nothing to add

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9ad88186a712bc829424d62e4621eb7eefdcfb27

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
