### ISSUE TITLE
Headsets never run out of power

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4259]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The battery in headsets do not drain or deplete, which takes away from part of the immersion.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

1. Start a game
2. Watch battery in headset over time

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Latest Steam Release, Linux

**Additional information**
N/A

**Comment by LePiromano** [comment]
It's a feature, not a bug

**Comment by LePiromano** [comment]
It was made so NPCs had less problems with it, because it was annoying having to recharge the NPC's battery each round.
It would be cool if it was up to the game's host via options tho.

**Comment by Regalis11** [comment]
@LePiromano That wasn't the main reason we did it. The problem was that many players found it confusing when the battery ran out, thinking the chat is bugged. We also felt having to change the battery didn't add much interesting gameplay or value to the game.

**Comment by Mikolaj1900G** [comment]
Now it seems it confuses people the other way around. Maybe the battery slot should be removed from the headset altogether as it is kinda redundant?

**Comment by Neko-LoverDisc** [comment]
I still feel like having to replace the battery adds a new sense of dread when exploring outside the sub, since if your playing with a team in a public game that isn't really aware, they could end up leaving you. But at the very least, maybe allow the host to toggle it on and off, as LePiromano suggested.

**Comment by ezjamsen** [comment]
Unfortunately we have to have it this way for now at least for the sake of bots. There was a sense of it not really adding meaningful fun to the overall experience too.

**Comment by MassCraxx** [comment]
> 
> 
> I still feel like having to replace the battery adds a new sense of dread when exploring outside the sub, since if your playing with a team in a public game that isn't really aware, they could end up leaving you. But at the very least, maybe allow the host to toggle it on and off, as LePiromano suggested.

Totally agree, I think this kind of "struggle" fits perfectly in the game. I would love to see this as an option to turn on when hosting a game. Luckily, there is a mod on steam workshop which allows this, but its currently being updated.

If there are no other plans to change it, I hope we can reopen this as a feature request.
