### ISSUE TITLE
Motion detector (2)  > Xor weird behavior

### ISSUE THREAD

**Issue by rdsl** [Regalis11/Barotrauma#4260]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm not sure if this is a bug or if I'm misunderstanding how motion detectors and logic gates work.
I'm playing a single player campaign.
I used two motion detectors to create a monster detector in each room of the sub. One is set to only humans, the other is not. They both cover exactly the same area. Their output True(1)/False(0) is connected to a Xor gate which outputs True(1)/False(0). So, if there is a monster Xor gets 1/0 and outputs True(1); Human 1/1 or no one (0/0), it outputs False(0).
This setup works well in the editor and in the campaign for a few missions, but after a while, inexplicably and always, it starts misbehaving, being triggered by humans, always in the same room. Whenever a character starts to move both MDs appear to output 1, but Xor outputs 1 for a very brief moment.
I think the following is happening:
When there is no movement both MDs are outputting 0. Then when a character moves both MDs change to 1, but not at the same time, thus for a brief moment Xor gets 1/0. The same happens when a character stops moving. I tried different values in the time frame property of the Xor gate but it doesn't solve the problem.
I isolated the circuit from the rest of the ship, and I have tried deleting everything and recreating again without success.
I added some text displays and a light to make it easy to diagnose.

**Steps To Reproduce**
Start the game with the sub setup described above, play for a while.
I could not figure out what triggers it.

**Version**
0.10.6.2 Linux.

**Additional information**
Save file and sub.
[save.zip](https://github.com/Regalis11/Barotrauma/files/5507787/save.zip)
[sub.zip](https://github.com/Regalis11/Barotrauma/files/5507828/sub.zip)

**Comment by rdsl** [comment]
I solved it by Anding the output of Xor with itself Delayed. But isn't it what the time frame property is supposed to accomplish?

**Comment by Regalis11** [comment]
Sorry for the late reply! Glad you managed to find a workaround for the issue.

The problem seems to be exactly what you described: if the sensors don't trigger exactly at the same time, the XOR component will output 1. Changing the time frame doesn't solve the issue, because what it does is make the component consider an input to be 1 if a non-zero signal was received within the time frame.

I suppose we could add an "only monsters" property to make circuits like this a little simpler to build.

**Comment by Regalis11** [comment]
Added an option to select the type of target (Any, Human, Monster) in https://github.com/Regalis11/Barotrauma-development/commit/95bca3e0113d898d539e22a921ef7cf7511f5200

**Comment by Jlobblet** [comment]
Tested all three modes, working correctly.

**Comment by Rokvach** [comment]
Closing
