### ISSUE TITLE
Server 

### ISSUE THREAD

**Issue by Sparkypop** [Regalis11/Barotrauma#4261]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
I'm afraid there's not much we can do without knowing what the issue is. :/
