### ISSUE TITLE
Beacon can try to spawn on a outpost level

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4263]
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/bbd4700f6df3e0461ee42cb0ea15bbcf7066ca52

Screen: Level editor
Level Type: outpostlevel
Seed: 3y4dhdfh

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ad807874-607a-47a5-a4b9-7799de3a46e9)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61fae6c698690f48c645cbddb689147f0b69e60e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
