### ISSUE TITLE
[0.1100.0.4] No loot in Beacon Station

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4264]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Beacon Stations have no loot D:

**Version**
0.1100.0.4

**Comment by danielasteljoki** [comment]
Added tags to station's containers but no items were spawned. Should tags work or does code need to synchronise a bool or reticulate some more splines? @Regalis11

**Comment by Regalis11** [comment]
@danielasteljoki Yeah, the splines were only reticulated for subs and wrecks. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9599029fcdee2d28c508e1c08e40f3760ee691ae

**Comment by Xeavas** [comment]
[0.1100.0.5] - Working correctly, loot spawns in beacon stations. 👍

**Comment by Rokvach** [comment]
Closing.
