### ISSUE TITLE
Physicorium Ammunition has no description

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4266]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mouseover tooltip for Physicorium Ammunition box is missing.

**Steps To Reproduce**
Open fabricator and hold mouse over Physicorium Ammunition box recipe
_Result:_ No tooltip presents its self
_Expected Result:_ A tooltip popup matching the other 2 ammunition boxes (exploding and standard)

**Version**
Experimental [v0.1100.0.4] 

**Additional information**
No additional information
![Screenshot (46)](https://user-images.githubusercontent.com/26475624/98603174-c2995680-2335-11eb-8e2a-e33fcbf87b86.png)

**Comment by danielasteljoki** [comment]
Added in 7cf1206.

**Comment by Rokvach** [comment]
No issues, closing.
