### ISSUE TITLE
Physicorium Ammo Box looks like same as regular Ammo Box

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4268]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Physicorium Ammo Box looks like same as regular Ammo Box

**Version**
~0.1100.0.4

**Comment by LePiromano** [comment]
also the nuclear depth decoy and the common decoy

**Comment by Prolbo** [comment]
Yeah, its very annoyng

**Comment by Rokvach** [comment]
No issues, closing.
