### ISSUE TITLE
Turret won't change position by more than ~180 degrees

### ISSUE THREAD

**Issue by rdsl** [Regalis11/Barotrauma#4270]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was trying to create a simple auto aiming turret with motion detectors but it got stuck at -177 and would not rotate to 20, and vice versa. So I tried to set the turret's position with a memory component and found out that it won't do large angle rotations > 180.

**Steps To Reproduce**
Use a memory component to control a turret with range (-180 to 20).
Set mem to 20 => change it to -180 => turret won't move. It will move if you change to -160.

**Version**
0.10.6.2 Linux

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c094c49c63e0e877d3477e3228640e0ca706b18a

**Comment by Xeavas** [comment]
[0.1100.0.7] - Can't replicate issue in said version, but said fix potentially caused a new issue. (Refer to #4342)

**Comment by Rokvach** [comment]
Closing as there's a ticket for the additional issue now.
