### ISSUE TITLE
Crush depth icons aren't cleared on the same outpost visit when you upgrade your hull

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4271]
Repro steps:
1. Buy all the hull upgrades
2. Use togglecampaignteleport command and move forward on the map
3. Notice that crush depth icons are still visible

This can mainly be confusing if you are next to a path with a crush depth warning and finish upgrading your hull

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7d4bb205086327ba9be84280bb77a76580b88cad

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
