### ISSUE TITLE
Tutorial level doesn't enclose the outposts anymore

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4273]
Main issues with this mainly are the Hammerhead fleeing outside of the reach of the periscope, or player navigating outside of the level and getting lost there.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ffc3f5d15cd6d33c69a447854397140905aec52

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
