### ISSUE TITLE
Proposal for some items/ideas to expand exploration gameplay

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4274]
Glowsticks: As exploration of wrecks and ruins evolve into more challenging environments, I propose some ideas for a couple of new items to aid in this, at the cost of some inventory space:

1. **Glowsticks.**
As an item, these are not meant to replace flares, but more of a less powerful 'I have been here' marker. 
Wrecks can be a bit of a knotwork to navigate around. With the addition of numerous wrecks in the workshop, and no doubt more that will be added in the future (official and non-official) Even seasoned veterans may find themselves at times in a, "have I explored that part yet?" situation, whether it's because they have been in that wreck type 50k times and cant remember if they have cleared that area 'this' time, or that they are exploring it for the first time.

To have a small lightweight visual reminder could be infinitely useful in a pinch. I see these as working well with flares, as I propose that glowsticks throw a soft light until the level ends, (but not enough light that they will light up a room), on the other hand, flares (which burn much brighter) burn for a limited time.

Obviously this idea would work much better in an environment where items were stackable, though perhaps a solution may be to have a section on the toolbelt that can hold a number of 'small' items only, glowsticks/flares in particular.

2. **Glow in the dark spraypaint.** 
I use spraypaint to mark lockers and areas of wrecks I have already been through, but have found pretty much every colour aside from green to be useless (and even then...)
I think the addition of a glow in the dark variety of paint could branch out its usefulness in a number of different areas of gameplay. To expand on this idea, perhaps an ultraviolet spray which could only be viewed with a specific visor. It would also be terrific to have the option of tightening the nozzle for a more concentrated spray to allow more effective writing/marking etc.

Whist I am on the idea of spraypainting wrecks, I have also noticed that there are a number of surfaces in them which the paint will not adhere to (I'm referring in particular to backgrounds, not lockers etc) It would be nice to have this fixed so that all 'wall surfaces' in wrecks will take paint readily. (perhaps even lockers etc eventually)

The attached screenshot is one of the particular wall types that I am referring to that will not take paint. (I just happened to be in this wreck when typing this)

![Screenshot (47)](https://user-images.githubusercontent.com/26475624/98724157-6c84eb80-23e7-11eb-9450-ddac00e049dc.png)

**Comment by Ek-Videogames** [comment]
Would give some purpose to sprayer to have glowing paint yeah.

**Comment by LePiromano** [comment]
with the new destructable enviroment they could also add some kind of new explosives

**Comment by ezjamsen** [comment]
Glow in the dark spraypaint especially is a pretty cool idea
