### ISSUE TITLE
Can't make a server with my friend

### ISSUE THREAD

**Issue by BillyBot1124** [Regalis11/Barotrauma#4275]
Me and my friend have our computers right next to each other, and we both have Barotrauma. We both love the game and play it all the time, and we like to play on servers together. This is where the problem comes in. Whenever one of us makes the server, one of 2 things happens

1. I simply can't join the server
2. Whenever we start the round, the person who isn't the server owner gets disconnected.

These issues happen regardless of who owns the server.

**Comment by mygamingaccount** [comment]
As a workaround, please try to connect directly using "Direct Join" in the server browser to the server's local [IP address](https://duckduckgo.com/?q=how+to+find+out+local+ip+address).

**Comment by Regalis11** [comment]
@juanjp600 Do you think this is related to https://github.com/Regalis11/Barotrauma-development/issues/2183?

**Comment by juanjp600** [comment]
Probably not, I'm guessing this was related to SteamP2P. #2183 only applies to Lidgren connections.
