### ISSUE TITLE
[0.1100.0.4] Beacon Mission - Power to the Transducer was optional

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4278]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The mission could be completed without providing power to the transducer.

**Version**
0.1100.0.4

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Even though this might be somewhat unintuitive, I think requiring the players to rewire the transducer would make the missions way too difficult to figure out, considering transducers are not used in any vanilla sub, and their function isn't explained to the player anywhere in the game.
