### ISSUE TITLE
[SUB Editor/Gameplay] Sonars and status monitors won't show shuttle/sub/module of another submarine that was docked, as part of a whole structure

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#4279]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Status monitor can't see and display hulls of submarine that was linked\docked to another submarine that was linked to the main submarine (e.g. module that linked to shuttle\drone that is also to main submarine)
Sonar also doesn't register linked submarine's module as a part of a submarine structure but as a separate object.

**Steps To Reproduce**
Link shuttle that already has another linked module to submarine and use sonar and\or status monitor.
Or spawn 3 or more submarines and dock them to each other and check sonar and\or statmon readings from the edge ones.

**Version**
Was noticed on unstable 0.1100.0.4 but same issue possibly will be on stable 0.10.6.2

**Additional information**
Images that show what submarine composition was used and how the problem looks:
General layout
![image](https://user-images.githubusercontent.com/62324831/98807080-3f2f5080-246e-11eb-97ba-a87fe33093ab.png)
View form main submarine's status monitor (module that docked to drone is invisible)
![image](https://user-images.githubusercontent.com/62324831/98806823-de077d00-246d-11eb-8e63-eb554ec4ab22.png)
View from module's status monitor (Main submarine is invisible here)
![image](https://user-images.githubusercontent.com/62324831/98806829-e069d700-246d-11eb-88cc-07b613da9a1c.png)
View from submarine's sonar (module that docked to drone is seen as a separate entity)
![image](https://user-images.githubusercontent.com/62324831/98806836-e2cc3100-246d-11eb-9c3f-95aa21aba211.png)

**Comment by Regalis11** [comment]
Related: https://github.com/regalis11/barotrauma/issues/3970

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cd0de8a28b2452bf6534568636fbc0c9a3949d94

**Comment by Xeavas** [comment]
[0.1200.0.0] - No issues observed, kastull's drone was visible 👍 

![testHBkastulldrone](https://user-images.githubusercontent.com/72674994/101931848-f1e10300-3c14-11eb-8b72-8e0cec87cecc.jpg)

**Comment by Rokvach** [comment]
Closing.
