### ISSUE TITLE
Lots of Lags in the New Second Biome

### ISSUE THREAD

**Issue by TijuuanWit** [Regalis11/Barotrauma#4284]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

The game lags in the New Second Biome that comes after the Ice Biome when Scanned with Active Sonar. 7 Fps. Please correct

Steps To Reproduce:
Try to enter Second Biome New and scan around the area

Version: v0.1100.0.5,Windows 10 Pro 20h2

Here are the screenshots provided so that you understand exactly where this is happening
![Barotrauma Lags](https://user-images.githubusercontent.com/72529525/98859596-7b18e480-2473-11eb-9ae9-4dd69a159719.jpg)
![Barotrauma Lags2](https://user-images.githubusercontent.com/72529525/98859603-7c4a1180-2473-11eb-801a-c89716aa6fc1.jpg)
![Barotrauma Lags3](https://user-images.githubusercontent.com/72529525/98859605-7ce2a800-2473-11eb-8b3a-ffa8f038d74f.jpg)
![Barotrauma Lags4](https://user-images.githubusercontent.com/72529525/98859843-d5b24080-2473-11eb-8705-df087ed10f34.jpg)

**Comment by TijuuanWit** [comment]
Swam to This Place for the first time. Lags when scanning the Terrain in Sonar, but if you turn it off, everything is fine. Impossible to play with Sonar.

**Comment by LePiromano** [comment]
Do you know the biome's name?
aphotic plateau maybe?

**Comment by TijuuanWit** [comment]
![Barotrauma Lags5](https://user-images.githubusercontent.com/72529525/98874512-72340d00-248b-11eb-8c73-cd2ffab9ec52.jpg)
I dont know. Is it correct that this is the European Ridge?

**Comment by Regalis11** [comment]
I think this is mainly caused by the high number of level objects that are visible on sonar in Europan Ridge (currents, ballast flora spore clouds, hydrothermal vents). Optimized the way those objects are displayed in https://github.com/Regalis11/Barotrauma-development/commit/c370a4886f1dfe98732aeb3a1f8d1c22d47f3350, let's see if this is enough to get it running smoothly.

**Comment by Xeavas** [comment]
[0.1100.0.6] - average fps 45-55, lowest fps(gpu throttled while the fans haven't fully spun up) 11.
![fpsavg](https://user-images.githubusercontent.com/72674994/99112196-4437ff80-2628-11eb-9a2d-8e00d1bcbe0f.jpg)
![fps11](https://user-images.githubusercontent.com/72674994/99112202-4601c300-2628-11eb-87d2-8f691417e453.jpg)

**Comment by Rokvach** [comment]
I think the above feedback is only a hardware issue on the users end, haven't heard of any complaints about the performance on this patch except the one encounter with spinelings.

**Comment by Rokvach** [comment]
I think this can be closed, haven't heard as many complaints about performance when comparing to the previous builds. Closing.
