### ISSUE TITLE
Crash when clicking "spectate" after a disconnection

### ISSUE THREAD

**Issue by BeholdtheImmolator** [Regalis11/Barotrauma#4286]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashed to desktop.

**Steps To Reproduce**
-

**Version**
v0.10.6.2 revision d0702df35e (Windows 10)

**Additional information**
Got a crash report.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5526947/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea1beaf46ee7e7d41a1c785b6a5fa4e1c67dadf7

**Comment by Rokvach** [comment]
There hasn't been any counters to this, seems to be working correctly. Closing.
