### ISSUE TITLE
Plants immediately dies after being planted (multiplayer)

### ISSUE THREAD

**Issue by Wun521** [Regalis11/Barotrauma#4289]
- [tick] I have searched the issue tracker to check if the issue has already been reported. (as far as I'm aware)

**Description**
Incident takes place in multiplayer campaign. After a catastrophic fire where the planter boxes were in version 0.10.5.1, our sub immediately went to dock without cleaning up, leaving all burn marks on the walls and #3874 happened. Upon continuing the campaign, plants started occasionally dying immediately after being planted, with the withered plant being full grown, or spontaneously after fully growing.

Issue increased in severity until all plants immediately dies after being planted. Issue also persisted through a change of subs and to game version 0.10.6.2.

**Steps to reproduce**
I have been unable to reproduce said issue in singleplayer thus far.

**Version**
Game version 0.10.6.2 on Windows

As far as I know, no mods should be affecting this. There is small chance that it might be save specific.

**Comment by 3e849f2e5c** [comment]
Most likely caused by #3852 there was a bug where if you uproot a plant it would not delete the seed properly and would spawn it on the planter the next round, the seed would retain the plants previous growth state and replanting it would instantly restore it

**Comment by Wun521** [comment]
Not with new seeds. It appears to be the issue you mentioned. Did not occur to me that it would be the same bug.
