### ISSUE TITLE
Feature request/Idea: More individuality with human characters

### ISSUE THREAD

**Issue by acebud12** [Regalis11/Barotrauma#429]
This is just a small thing I thought about. I was thinking with Human characters, some could be generated with prosthetic limbs, which I would totally see a lot of characters having in the dangerous world of europa. I saw in the XML that there was specified Left/right arms, so I thought this would be possible

**Comment by ClasticM** [comment]
Im sorry dude but after watching the Battlefield V reveal this last week I can't take prosthetic limbs seriously anymore

**Comment by acebud12** [comment]
Oooo that would be good, but I was thinking it more as another option for human characters to be randomised with

**Comment by BillCombs** [comment]
In my opinion, idividuality is good, but only as long as you don't overdo it. Adding more customisable options also means the game will have more things for your computer to work with. That can heavily affect ingame performance. Especially with player ragdolls. The respawn feature made having 30+ corpses on the sub possible, what also can make your game lag a lot. If you are going to add more individuality, then you will have to also add a way to deal with the lag that comes with it.
There should some way to get rid of the corpses. Some kind of an incinerator. Or maybe upon respawning of the corpse's owner make the corpse disappear and drop a backpack-like container that will have all stuff from the corpse and can only be held but not put in your inventory. Turning a ragdoll into a single item will most likely help to reduce the lag.

**Comment by BlueTheKing** [comment]
Corpses should deteriorate after being in the water for too long.

**Comment by acebud12** [comment]
As much as I like to talk about the incinerator idea, I feel like it's just getting off the topic of this post and it'll get nowhere, so I'm just gonna close this
