### ISSUE TITLE
Ready Check crashes if initialized while the player is still loading

### ISSUE THREAD

**Issue by 3e849f2e5c** [Regalis11/Barotrauma#4290]
Discovered during unstable testing

![image](https://user-images.githubusercontent.com/39580303/98902739-f3f15e00-24be-11eb-9a23-834e236adca9.png)

**Comment by 3e849f2e5c** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/b8b54463a4ae63cff195bc081247bd62bf5b3a5e

Happened because the "Start" network message was not received in loading screen and after the loading screen is done the ready check would broadcast "Update" network messages whenever a player responded to the ready check but because the ready check never existed on the client it crashes. Fixed by ignoring Update network messages if the ready check is null and make the client respond with "not ready" if they cannot start a ready check.

Repro steps:
- In campaign choose a destination
- Immediately after the loading screen is done execute the "readycheck" console command
- See if people who are still loading in start disconnecting

**Comment by Rokvach** [comment]
No issues, closing.
