### ISSUE TITLE
Shotgun and smg miss [Unstable]

### ISSUE THREAD

**Issue by muskaeragon** [Regalis11/Barotrauma#4291]
Hello. I`m test the unstable version and found a bug. The shotgun and smg miss underwater. They miss until the weapon is located in the monster's torso. But spear gun can hit monsters underwater without misses. In the submarine all weapons hits on monsters. Melee weapons work fine, but when shooting with a shotgun and a submachine gun, the creature is repelled, but no damage is done. The bug can affect all ranged weapons (no spear gun). This is bug, or should be.

**Comment by Regalis11** [comment]
Hello and thank you for the report!

I'm afraid I couldn't reproduce this, both the shotgun and the smg seem to damage the monsters as intended. Does this happen in single player, multiplayer or both? Are you using any mods?

![image](https://user-images.githubusercontent.com/14351070/98914894-e2fe1800-24d1-11eb-8efe-37d8da33ec15.png)

**Comment by muskaeragon** [comment]
This is singleplayer.

**Comment by muskaeragon** [comment]
Yeah. This is bug of the mission "Clear tigerthresher nest.". When spawn tigerthreshers in the nest, ranged weapons don`t damaged they. I can record a video or show it in discord. Or you can start this mission yourself and check it out

**Comment by muskaeragon** [comment]
On this video you can see this bug.
https://www.youtube.com/watch?v=7u-XY5jzQ7g&feature=youtu.be

**Comment by muskaeragon** [comment]
What information should I provide?This bug occurred even after restarting the game. This bug is not present in the previous version of the game, but it is in Unstable. I have no suspicion why this is happening. Hitboxes of NPCs are normal, but after spawning sharks from eggs, the damage stops passing.

**Comment by Regalis11** [comment]
I'm not sure if there is much further info you can give us; in this case the "need more info" tag just means I wasn't able to get it occur, and that we need to do more testing or hope that someone manages to figure out a way to get this to happen at our end.

> Hitboxes of NPCs are normal, but after spawning sharks from eggs, the damage stops passing.
This could be a valuable clue, I'll give it another try with threshers spawning from eggs. Thank you for the extra info and the video!

**Comment by Ek-Videogames** [comment]
This appears to be still happening (in stable) (in multiplayer)
shell-less raptors spawn from the eggs in a nest mission but become seemingly invulnerable to all projectiles

**Comment by Regalis11** [comment]
Happened to run into this just now, and I think I managed to fix it (https://github.com/Regalis11/Barotrauma-development/commit/5a503717bf5901aa3b49056082f882278377390c).

The issue was that the weapon did a raycast in the coordinate space of the sub(s) to see if it can hit some structure/item from outside the sub, and in some cases this raycast hit things in world space, most often level walls. I don't think there's an easy way to reproduce this, but it most frequently happens when there's lots of subs in the level (which includes beacon stations, outposts and wrecks) and the weapon is being fired at a position close to the bottom of the level.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
