### ISSUE TITLE
[0.1100.0.5] Level Generation started my Sub stuck in Wall

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4298]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/98996785-73a01c80-2501-11eb-944d-022a6a0a3e6b.PNG)
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/5533313/Save.0.zip)

**Version**
0.1100.0.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5da9336bf38255ea8012a863cab3dfb8092bb90b

**Comment by Xeavas** [comment]
[0.1100.0.6] - Can't replicate using save provided, sub not stuck. 👍
![substucktest](https://user-images.githubusercontent.com/72674994/99105995-7cd2db80-261e-11eb-9118-88e5210ac9f5.jpg)

**Comment by Rokvach** [comment]
Closing.
