### ISSUE TITLE
[0.1100.0.5] Artifacts spawning inside Ice Spikes

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4299]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Artifact spawned on the first ice spikes encountered on this level. Same save file from #4298.
[Save 0.zip](https://github.com/Regalis11/Barotrauma/files/5533313/Save.0.zip)

**Version**
0.1100.0.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/705551655fa5de8cad8db4b8089892112284a026

**Comment by Xeavas** [comment]
[0.1100.0.6] - Can't replicate using the save provided. 👍
![artispire](https://user-images.githubusercontent.com/72674994/99105932-6298fd80-261e-11eb-88f4-972dbc317194.jpg)

**Comment by Rokvach** [comment]
Closing.
