### ISSUE TITLE
[0.1100.0.5] Pet Food doesn't start in crates when purchased/additional cargo

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4300]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pet Food doesn't start in crates when purchased/additional cargo.

**Version**
0.1100.0.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60793d85054ea888505762147c14f601a77a3c24

**Comment by Rokvach** [comment]
No issues, closing.
