### ISSUE TITLE
Health Scanners prevents you from seeing press 'E' on pets to keep them happy

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4301]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was raising pets for the first time and my pet started making sad noises several level later despite feeding it properly and I didn't know why. I didn't even know I had to press "E" on the pet to keep it happy until someone else told me. Apparently the Health Scanner that I always have on my head slot prevented me from seeing the UI that tells me to press E to play with them.

![Capture](https://user-images.githubusercontent.com/5086682/99004761-9fc19a80-250d-11eb-9ce5-c461d3621821.PNG)
![Capture1](https://user-images.githubusercontent.com/5086682/99004762-a05a3100-250d-11eb-8764-89626bb589cb.PNG)

**Version**
~0.1100.0.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/21a2676d4fb19001bad8d8f6a18a5aee441868d4

**Comment by Rokvach** [comment]
It doesn't seem to show [H] Heal on characters when wearing the HUD, everything else seems to be shown
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/349d750d-bb41-4511-892d-91943e09994f)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7c95d19acc5f435f2f3870a409bd6d3147ac31b8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
