### ISSUE TITLE
When New Hires bots dies in the level they spawned in, the result screen shows New Hire instead of how they died

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4302]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Newly Hires bots dies in the level they spawned in, the result screen show the blue New Hire text instead of how they died.

**Version**
~0.1100.0.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c9d3770631e15e549ff1dd1273e38c29e4e3971

**Comment by Xeavas** [comment]
[0.1100.0.6] - Can't replicate 👍

**Comment by Rokvach** [comment]
Closing.
