### ISSUE TITLE
Crash when spawning NPC in Ruins

### ISSUE THREAD

**Issue by Aktheon** [Regalis11/Barotrauma#4304]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash when spawning crewmember-NPC via console in Alien Ruins.

**Steps To Reproduce**
Start any campaign. Find ruins using freecamera. Spawn NPC inside Ruins.

**Version**
Window 0.10.6.2

**Additional information**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5536397/crashreport.2.log)

**Comment by itchyOwl** [comment]
Duplicate of #4104. Fixed in the unstable.

Thanks for reporting!
