### ISSUE TITLE
[unstable] "Shuttle Navigation Terminal" and "Sonar Monitor" have broken UI

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4305]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
With the new navigation terminal UI, the custom button on shuttle navigation terminal block the sonar screen. Also when linked with a status monitor, the status monitor block the sonar screen even more.

**Version**
v0.1100.0.6 Windows

**Additional information**
I've checked a coupe subs with the similar result:
![image](https://user-images.githubusercontent.com/48099798/99094571-48d2c880-25d4-11eb-8e91-9458f207906d.png)
![image](https://user-images.githubusercontent.com/48099798/99095170-16759b00-25d5-11eb-9828-55622a71b146.png)

**Comment by Singularia** [comment]
Same problem with UI misalignment affects standalone sonar device
![image](https://user-images.githubusercontent.com/62324831/99144014-8ad43b00-26b6-11eb-89e0-1b4ab63c065e.png)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Braotrauma-development@5efb3d4.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
