### ISSUE TITLE
[V0.1100.0.6] Ranged attacks cannot be triggered inside a submarine.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4306]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A creature with a ranged attack inside a submarine cannot perform said ranged attack.

**Steps To Reproduce**
Spawn a creature that has a ranged attack inside the submarine. Observe how it will play sounds / particles tied to the attack, but not actually spawn any projectile. (Spineling is not applicable for this since it cannot be inside a submarine)

**Version**
V0.1100.0.6 (Unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d93031970017e4a484b8deefc5c27a20d0e84474

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
