### ISSUE TITLE
Changes to Terminal.cs?

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4307]
[Question]
As of unstable right now (10.6 or the halloween update) I have this item that's essentially a logbook that uses status effects to update its own welcome message and accordingly print text on the screen depending on what the player has inputted in a textbox.
![image](https://user-images.githubusercontent.com/47284081/99110481-58590e00-25e2-11eb-8dc8-df98e76a4893.png)
It uses a system like this:
```xml
<StatusEffect target="This" type="Always" setvalue="true" delay="0.1" stackable="false" displayedwelcomemessage="---\nWELCOME\n---\nWelcome to the Abridged Necronomicon!\n\nThis book is for cultists who don't have time to read the long, boring necronomicon, and teaches you the basics of occultism like how to summon scary stuff, talk to the dead, and the basics of blood rituals!\n\nThis electronic book is navigated by entering terms into the topmost box. Enter the term 'index' to view a list of available terms.">
        <Conditional OriginalOutpost="eq intro" />
      </StatusEffect>
```
...and so on for other "pages".
in the newest unstable this is broken, and in the git I see that there are a few changes to Terminal.cs that I would warrant broke this. In particular, this section, if i understand it correctly:
![image](https://user-images.githubusercontent.com/47284081/99110578-83436200-25e2-11eb-874c-6bc805c49291.png)
...probably broke it. The commit is in response to https://github.com/Regalis11/Barotrauma/issues/4082. Why was this section removed? Would it be possible to readd something like it except less broken?

**Comment by Regalis11** [comment]
This change was done because now the contents of the terminal are saved between rounds, so the welcome message only needs to be displayed once, not at the start of each round. I suppose we could add some alternative method to display messages using status effects.
