### ISSUE TITLE
Recently spawned moloch nests look like a ball in the sonar

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#4310]
**Description**
The babies and the moloch spawn almost inside eachother and makes them look like a ball in the sonar

**Version**
V0.1100.0.6

**Additional information**
maybe moving them away from eachother on spawn would fix it.

**Comment by Regalis11** [comment]
I'm not sure if this is something we should fix: I think it's in a sense a good thing you can't immediately tell what you're seeing on the sonar.

**Comment by LePiromano** [comment]
It's up to you! It's pretty noticeable anyways, it's the only thing that appears as a perfect circle in the sonar.
![20201113194521_1](https://user-images.githubusercontent.com/55637865/99187600-586a2280-2736-11eb-9e4c-6e64a1329913.jpg)
