### ISSUE TITLE
Inconsistency in alien material categorisation in stores

### ISSUE THREAD

**Issue by Mikolaj1900G** [Regalis11/Barotrauma#4312]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Oxygenite and Sulphurite shards are considered [Alien] in stores but dementonite, physicorium, incendium and fulgurium are considered [Materials] even though all of them are made from deconstructing alien artifacts. Might be just me but it seems kinda strange.

![alien minerals](https://user-images.githubusercontent.com/57800630/99149035-d6252400-268b-11eb-9372-e0fffc5553b4.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/df2fe5e6979ab2fe318b4730a89724096b341caf

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
