### ISSUE TITLE
Crash when rendering plant branches (texture was null)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4315]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Randomly crashed before reaching next station after we finished a mission.
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5541534/crashreport.2.log)

**Version**
0.1100.0.6

**Comment by 3e849f2e5c** [comment]
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/23a96eeb49af4585bda5f0ab8c25adcef402ff32

Likely caused by the game unloading sprites at the end of the round but somehow a draw call slipped thru causing the plant to attempt to draw a sprite that has been disposed of

**Comment by Rokvach** [comment]
Tested, looks to be working correctly. Closing.
