### ISSUE TITLE
[V0.1100.0.6] Remora and Kastrull Drone coilgun model upside down

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#4318]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![602960_20201115071853_1](https://user-images.githubusercontent.com/62313026/99179230-8d18b280-2713-11eb-9388-4afd6bfefce5.png)
![602960_20201115095446_1](https://user-images.githubusercontent.com/62313026/99181805-e5a67a80-2728-11eb-899e-ce0c2a9d00f8.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
V0.1100.0.6
**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a00de001cb906e50675508f4b9132f7781ef3bd4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
