### ISSUE TITLE
[Unstable V0.1100.0.6] Nest marker doesn't go away when completing one in multiplayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4319]
We were doing a tresher nest mission and after completing it the marker was still there

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4c7619b3e7ef800da208ae01c3b75d3331ee40f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
