### ISSUE TITLE
Massive background fish, bug or feature?

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#4321]
![20201115163054_1](https://user-images.githubusercontent.com/55637865/99194857-05f22b80-2761-11eb-9e8f-5874e93ec1f2.jpg)
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I found this head of a fish almost the size of a moloch, it looks really weird.
**Steps To Reproduce**
Spawned randomly in the void, maybe in other biomes too.

**Version**
V0.1100.0.6

**Additional information**
Maybe wrong scale?

**Comment by Regalis11** [comment]
This is intentional (although still WIP)
