### ISSUE TITLE
Aiming crosshair is enormous after loading an old save from before toolbelt slot existed

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4322]
**Description**
![Crosshair1](https://user-images.githubusercontent.com/72674994/99197172-b9900580-27cb-11eb-9e1e-4b0da10919e9.jpg)
(ignore the steroids, I shifted it to the last slot before I took this picture)

**Steps To Reproduce**
- Load up a save from a version before toolbelt slot existed that have a gun in the first slot of the hotbar
- Proceed to aim any aimable tool/weapon

**Workaround**
Seems to resolve by just taking the weapon out of said slot, but it may be confusing for some players.
![Crosshair2](https://user-images.githubusercontent.com/72674994/99197270-6cf8fa00-27cc-11eb-8f9e-61eb7d7f9641.jpg)

**Version**
0.10.6.2 & 0.1100.0.6

**Comment by Regalis11** [comment]
Since this only affects old save files, takes very specific circumstances to occur and is very easy to work around, I don't think we should implement any extra logic to fix it. By the time we get the fix I doubt there would be many people with an old save where this occurs anyway.
