### ISSUE TITLE
Multiplayer - Recover Shuttle > Lost Drone in Level > Server Lobby > Restarted Round > No Shuttle

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4323]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When paying to Recover Shuttle, start level, lost it in this level, returning back to the Server Lobby to Restart the Round, resulted in No Shuttle.

Recovered:
https://www.twitch.tv/videos/804257031?t=01h56m41s

We lost the drone in the level as we played, and then we decided to server lobby to save scum.

Server Lobbied:
https://www.twitch.tv/videos/804257031?t=02h49m26s
Restarted:
https://www.twitch.tv/videos/804257031?t=02h49m53s

Missing Shuttle:
https://www.twitch.tv/videos/804257031?t=02h50m21s

**Version**
0.1100.0.6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/32105d59ec210da12823a7ebe77b55cbb10f9901

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue. Working correctly. Closing.
