### ISSUE TITLE
Multiplayer - Paying to Recover Shuttle+Fix Items+Fix Hulls = Shuttle damage Desynced

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4325]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So we lost the drone 2 rounds ago. We paid to recover the drone, fix items, and fix hulls.
https://www.twitch.tv/videos/804257031?t=01h56m41s

Next round starts and the drone was recovered in the state we left it 2 rounds ago, but it was actually fixed with desynced breaches and water. Welding the breaches didn't do anything as the sub was healthy server sided.
https://www.twitch.tv/videos/804257031?t=02h04m31s

**Version**
~0.1100.0.6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/900086dc3ef26ce1ac52448ed4f4bfb0480f334c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
