### ISSUE TITLE
Event npc still gives said events while dead

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4329]
**Description :**
You still can trigger said mission when event npc is dead provided that outpost guards are not aggroed onto you.

**Steps To Reproduce :**
- Launch singleplayer campaign
- `triggerevent givingdirections` (also works for the event `huskcultist`
- `kill` associated npc with said event, and go near to trigger.

**Version :** Tested in [0.1100.0.6]

**Additional information**
![eventdead](https://user-images.githubusercontent.com/72674994/99212522-317b2180-2806-11eb-827b-528680569b4e.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4da071641edf94070ada8a437fc3e0f98e1b421c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
