### ISSUE TITLE
Ban a steam account from a server

### ISSUE THREAD

**Issue by JJRcop** [Regalis11/Barotrauma#433]
With the new steamworks integration, you should be able to additionally ban people by steam account, and have that ban also apply to the app owner if the game was shared.

This would be helpful to prevent ban evasion by changing your IP, so if someone wanted to evade, they would have to buy the game again on a new steam account on top of changing their IP.

**Comment by CryIz** [comment]
The same applies to the rights that are issued to the Player, and he has a dynamic IP.

**Comment by JJRcop** [comment]
The IP bans should stay as an option, they have their own value

**Comment by Regalis11** [comment]
Added in 51afefe
