### ISSUE TITLE
[Singleplayer] Stuck in event UI if character you're controlling dies midway into event.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4330]
**Description :**
Event UI doesn't auto close mid way into event when you die, nor can you close it either. Seems to only happen in Singleplayer as I can't replicate this in Multiplayer

**Steps To Reproduce :**
- Start a Singleplayer Campaign
- `triggerevent clownrelations1`
- Trigger said event and select the option "Inspect"
- `kill` your character that you're controlling for the event
- Attempt to select either choices

**Version :** Tested in [0.1100.0.6]

**Additional information**
It doesn't auto close and stays like that until you restart the round/save or quit to menu.
![eventuistuck](https://user-images.githubusercontent.com/72674994/99213119-ba468d00-2807-11eb-8d43-c8abbbaae62e.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e42671b9861ce93f8298055cac3fc28cda0471c

**Comment by Rokvach** [comment]
I was still able to reproduce this issue by using the kill command right after clicking inspect and not waiting for the other options to show up first, the dialog is now stuck on the screen and prevents me from switching characters in singleplayer.

This does work correctly if you wait for the clowns to get to you and you see the same dialog options as on the screenshot on the original post.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/cfa5ae4a-8e7a-4ce3-ae4e-c71ba399b7f3)

**Comment by Regalis11** [comment]
Nice catch! Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e42671b9861ce93f8298055cac3fc28cda0471c

**Comment by Xeavas** [comment]
[0.1200.0.0] - Retested, unable to replicate using mine and Rokvach's methods.

**Comment by Rokvach** [comment]
Closing
