### ISSUE TITLE
Few ideas surrounding crafting (and also an idea for unstable explosives)

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4331]
1. It would be useful to have an idea of what an item breaks down into.
This could be displayed as a mouseover tooltip which contains its material icons. This tooltip could be displayed when mousing over items in the inventory, or even better, perhaps in a special area visible only once the item is placed in the deconstructor input.

To extend further on this idea, the tooltips accuracy could be in accordance with the chars skill/experience, or even perhaps only showing the tooltip with 100% accuracy after completing the deconstruction of a given item.

2. Crafting recipes should be searchable away from a fabricator.
This would be useful especially for players that have no fabricators on board and need to run to/fro to use fabricators on bases, but also very useful just for grabbing required items for a recipe from remote storage. Having to tab out to check the wiki gets old pretty quickly.

3. A way to 'favorite' certain crafting recipes.
For those items we keep returning to the fabricator to craft all the time. Perhaps a small star that can be toggled on/off next to each recipe so they can be easily tailored to each players unique playstyle.

4. Show items craftable by searching from any given ingredient.
This is something that can also be done from the wiki, but much a more useful tool to have in-game. (the less we need to tab out, the better). This would be useful for savvy players that are looking at a surplus of materials on board and want to browse a 'profitable' way to burn them up. (also help to spare materials by rationing them in knowing at a glance that they are used in another recipe)

5. Railgun shells need to use more steel in their fabrication. (This is more of a balance gripe)
Whilst I love the idea of finding railgun shells in a wreck and carefully considering and weighing up the time involved in their recovery against my current need, as balance of the game currently stands, why would I bother when I can fit 12 VERY insignificant and common items such as plasma cutters/sprayers/stun gun darts etc into my toolbelt and fabricate railgun shells from them instead?

6. Crafting should be able to pull items from storage containers that are situated inside a cabinet.
I guess this one is probably part of a much bigger issue (being the inventory management system) but I think it needs no explanation whatsoever in regards to its usefulness.

7. We should be able to access items inside storage containers without having to hold them in our hands.
As above, I guess this is part of the Inventory management system as well, but I think something like double clicking on a container to open it (whilst it is inside a cabinet) to allow for interaction between it and the cabinet containing it/personal inventory/toolbelt/floor/crates on ground/nearby players etc would be infinitely useful and save a lot of excessive clicking.

8. Crafting explosives has a chance to create an 'unstable' explosive.
I loved the idea and practice of the unstable explosives from the 'transport explosives' missions ripping holes in subs piloted by the unwary. I propose an idea that crafting any explosive in a fabricator have a similar effect by creating a finished product that can cause similar types of 'fun'.

Crafting explosives could (and very much should) be a skill based thing with horrific results should the crafter 'fail' in their task. This failure of scientific prowess could be measured in both; a modification of the time it takes for the explosive to... well... explode, but also could be measured in the ferocity of the explosion its self.

I believe this could add a great risk/reward aspect to the game and could really make people weigh up the benefits vs the current need of producing explosives whilst travelling.

**Comment by Regalis11** [comment]
Feature requests should go in the [Discussions](https://github.com/Regalis11/Barotrauma/discussions), closing this one
