### ISSUE TITLE
Fabricator's UI is blocked by the linked cabinet

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4332]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have a fabricator, a deconstructor or a medical fabricator linked to a cabinet with "display side by side" enabled on the cabinet, the UI will get glitched if they are accessed in specific order.

**Steps To Reproduce**
Steps are the same for all 3 devices:
1. Have a fabricator linked to a cabinet, with "display side by side" enabled on the cabinet
2. Open the fabricator
3. Open the cabinet
4. Open the fabricator again - UI will now be broken

If the linked cabinet is accessed before the device, the bug won't happen.

**Version**
v0.1100.0.6 Windows

**Additional information**
Wasn't able to reproduce on current stable (v0.10.6.2).
Also might not be related, but UI with that setup is permanently broken when opened in submarine editor.
Screenshots of broken UIs:
![sc1](https://user-images.githubusercontent.com/48099798/99263144-17017200-281f-11eb-9437-874b0b193f28.png)
![sc2](https://user-images.githubusercontent.com/48099798/99263151-18cb3580-281f-11eb-8735-52e8b1ee97a9.png)
![sc3](https://user-images.githubusercontent.com/48099798/99263155-1b2d8f80-281f-11eb-9fde-fd2f6573f83d.png)

**Comment by Rokvach** [comment]
I think it would be wise to overhaul linked cabinets by either making them a simple list to list all the items available or implement it directly to the fabrication UI on the list of items to display how many of a certain item you can craft with what you have in the cabinet and your inventory. 

This example shows how many you can craft with the items you have: 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5d0c8677-2bbd-446b-b1b7-f8e9e2420b24)

I know we currently use that same area to display how many items you can craft in a single process, but I think that information could be moved elsewhere. 

Example to show how many items you can craft with a single process:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/98cec832-0d28-45c3-87d6-66d2fb1c6744)

Examples are from Wow but similar setup is quite common across many different games.

**Comment by SagaciousZed** [comment]
I've often experienced this during multiplayer when someone else interacts with the inventory or the fabricator

**Comment by Rokvach** [comment]
Only thing I spotted was when playing on the smallest resolution the UI's are vertically misaligned, but they aren't overlapping

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/578fe667-a27d-4cf6-be5d-ff10e324f611)

**Comment by llamerr** [comment]
I'm still seeing this problem
![20220523175031_1](https://user-images.githubusercontent.com/1281970/169848716-97f51a71-8ce1-408f-8d41-1b6efcb01bfd.jpg)

**Comment by HijackHornet** [comment]
I'm still having this issue as well
Resolutio: 3440 x 1440
Windows 10
Build : 0.17.16.0

Could you please reopen @Regalis11 / @Rokvach

**Comment by oneengineer** [comment]
same issue here. It doesn't always happen. When you open different cabinet several times, the problem will appear.
