### ISSUE TITLE
Bots - Heal Injury order treating Blood Loss item waste

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4333]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever bots are healing Blood Loss, they will use the entire Saline/Blood Pack/Alien Blood even though Blood Loss is either gone or very low. If they don't have immediate access to Bandages, they may end up using more Saline/Blood Pack/Alien Blood before they decide to go find Bandages.

**Version**
~0.1100.0.6

**Comment by Regalis11** [comment]
Partially addressed in https://github.com/Regalis11/Barotrauma-development/commit/76d794f3ada66b6dde24626a6c2e8cd74db4d6a2 by making the blood packs work a little faster. The bots wait a couple of seconds after applying a treatment (to wait for the effects and side-effects of the drug to manifest), which can cause them to use more drugs than necessary. Completely fixing this would take a bit more work, the bots could for example do some kind of a projection of the character's future health based on the change in the afflictions' strength or maybe the StatusEffects of the drug itself. Let's look into this in the future, moving this back to the backlog.

**Comment by Rokvach** [comment]
No issues, closing.
