### ISSUE TITLE
Mining Outpost Level Generation Leaves People and Places Inaccessible

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4335]
- [✔️] I have searched the issue tracker to check if the issue has already been reported.

**Description/Image**
![image](https://user-images.githubusercontent.com/72813628/99305576-f5ee5080-2821-11eb-9725-72bf61ab9465.png)

**Steps To Reproduce**
Save File Located Here:

[outpostglitch.zip](https://github.com/Regalis11/Barotrauma/files/5549543/LES.GO.zip)

Huskmod is enabled in this save, but I assume that has nothing to do with level generation, as it just edits dialogue and adds new creatures to the base-game. 

**Version**
Unstable (latest build), Windows.

**Comment by ubertpendragon** [comment]
![20210302010413_1](https://user-images.githubusercontent.com/73229309/111017266-9f011e00-83b2-11eb-9be7-58fad62ae96e.jpg)

NPCs can spawn in blocked-off mining areas and suffocate. This one was a quest giver

**Comment by Regalis11** [comment]
Should no longer occur, since we only use one mine module in the mining outposts
