### ISSUE TITLE
[Unstable 0.1100.0.6]  Please less clickfest on receiving mission

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#4338]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not exactly a bug, but the recent changes to the GUI when receiving missions on the outposts became a pretty annoying, unnessecary clickfest related to its previous implementation.
Please, please, less clicking, better ergonomics.
Thx.

**Version**
Unstable 0.1100.0.6

**Comment by Regalis11** [comment]
Related: Regalis11/Barotrauma#3796

**Comment by ezjamsen** [comment]
Will be resolved with #3796
