### ISSUE TITLE
[Unstable] Starting levels with ice spires literally next to the sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4339]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes it is possible for ice spires to be literally against/next to the sub right at the start when people load in, causing leaks right off the bat.

**Version**
0.1100.0.6

**Comment by Regalis11** [comment]
If you run into a level where this happens again, could you send us the seed or save file?

**Comment by Kaillera** [comment]
I believe these Ice used to be bigger in the previous versions, but they're still pretty close to the start.
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5562533/Multiplayer.zip)

**Comment by Regalis11** [comment]
Thanks! Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9f6670d12568e19001202032783450dbeac97c02

**Comment by Rokvach** [comment]
Haven't noticed any ice spires spawning near the spawn. Seems to be working correctly. Closing.
