### ISSUE TITLE
Bots don't run when ordered to clean.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4340]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots don't run when ordered to clean. I am fine if they walk around cleaning in idle, but they need to clean faster when we tell them to.

**Version**
~0.1100.0.6

**Comment by thegrb93** [comment]
I hope they mutiny you

**Comment by itchyOwl** [comment]
It's intentional. I just thought it would be weird if they did. One way to improve their speed would be to allow them to take more than one item at a time in their inventory. It's just something that would require code refactoring and might become problematic in some cases.

**Comment by itchyOwl** [comment]
Made them run in Regalis11/Barotrauma-development@a362dc0. Let's test it. There's another ticket regarding the multiple items in the inventory here: #4387 That one is a bit more complex.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
