### ISSUE TITLE
Characters' current orders aren't properly cleared in between rounds

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#4341]
**Description**
After starting a new multiplayer campaign round, some characters still had orders from the previous round.

![image (4)](https://user-images.githubusercontent.com/16864465/99558056-ffb3b780-29cb-11eb-9a90-e76d5748d923.png)

![unknown33](https://user-images.githubusercontent.com/16864465/99558883-da737900-29cc-11eb-84c1-8b7e33b3bfe2.png)

**Version**
v0.11.0.7 (unstable)
Windows

**Comment by ekqvist** [comment]
I'm not sure that this bug was even caused by the changes made for the latest unstable. I think it might have already been there but just hasn't been brought up until now.

For debugging, see `CharacterNetworking.ReadSpawnData()`.

The error message was caused by the order having a blue wire as the target entity and not being able to find the turret component from it.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@e866c06.

The current order would be reset for all the CharacterInfo instances found in CrewManager.CharacterInfos when CampaingMode.End() was called. But in multiplayer, there is a CharacterInfo instance stored within each Client instance which is used when spawning the character at the start of the round. The current order should now be reset for those as well whenever GameServer.StartGame() or GameServer.EndGame() is called.

**Comment by ekqvist** [comment]
It could be possible that the error was caused by something like changing the sub at an outpost which led to the order trying to target a different entity than it did originally. We need to take a proper look at this if we want to implement orders which persist through multiple rounds.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
