### ISSUE TITLE
[Unstable 0.11.0.7] Nest mission eggs are drawn behind ores and you aren't able to use a plasmacutter/welder to destroy the egg if its covered in dead creatures

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4343]
Doing a nest mission I had a really difficult time to complete the mission as I just couldn't find the last egg, I started mining the ores around the area and found the last missing egg behind one of the ores. It was completely hidden behind it.

On the egg mission the nest generated in a V shaped section of the cave and all the dead creatures piled at the bottom of it stacking on top of one of the eggs I needed to destroy. I had to move all the corpses one by one in order to finally reach to destroy the egg.

**Comment by Kaillera** [comment]
I can confirm this, The egg that I had saw was barely visible behind the ore.

**Comment by Regalis11** [comment]
Fixed the sprite depth in https://github.com/Regalis11/Barotrauma-development/commit/6680eae

Could not repro the 2nd issue with either the plasma cutter or the welding tool:
![image](https://user-images.githubusercontent.com/14351070/99642240-f1a97980-2a53-11eb-8325-c808fc989cb1.png)

**Comment by Rokvach** [comment]
I was testing this on multiplayer, looks like welder does work but plasmacutter doesn't. I assume the plasmacutter is targeting the creature because of the dismembering feature

**Comment by Rokvach** [comment]
If the above is the correct behavior for the plasma cutter then I think it might need to be further indicated what the plasma cutter is currently hitting, the effects for cutting a creature with it aren't clear enough to tell the player as to what they are currently cutting and why they can't cut the egg.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2bc80edc75d6def01adf7e5ff2685c674fe1ee82. Plasma cutters should now be able to cut multiple targets at once (with the exception of doors and walls, which block the beam).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
