### ISSUE TITLE
Multiplayer - Error/Desync? Crawler eating Wreck Corpse that I was grabbing onto into Sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4344]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I was dragging back corpses from a wreck with a diving suit that I put on it. Right as I am entering my Dugong's airlock, I see a crawler chewing on the corpse as I was grabbing onto it. Moments after, it spit out these errors.

Collider velocity invalid ({X:2512.7712 Y:-1334.9666}, character: Erich Rivera), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
Collider velocity invalid ({X:2516.89 Y:-1337.0377}, character: Erich Rivera), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
Collider velocity invalid ({X:2520.1055 Y:-1338.912}, character: Erich Rivera), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
Collider velocity invalid ({X:2523.3228 Y:-1340.7532}, character: Erich Rivera), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
Invalid ragdoll physics. Ragdoll frozen to prevent crashes.

The corpse entirely disappeared for my client, but the other 3 players were able to see the corpse doing this freaky stuff:

https://www.dropbox.com/s/uk059321fpeynxx/Barotrauma%202020-11-18%2021-04-54.mp4?dl=0

**Version**
~0.11.7

**Comment by LePiromano** [comment]
![20201118220849_1](https://user-images.githubusercontent.com/55637865/99616054-58e70f80-29fb-11eb-9cc8-dc39afba3711.jpg)
i was able to see it too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aaee43e54e0b00088487741c8fcc31d6d665b0b4

**Comment by Rokvach** [comment]
Tested, fed a crewmate to a crawler and grabbed the body whilst the crawler was eating it and went both ways through a docking port, no errors. Closing.
