### ISSUE TITLE
Bots can't find a path through the docking module.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#4345]
Ordering a bot from inside the sub to "wait" at the specified location (the pause with a circle to the right), results in them equipping the dive suit correctly, going out of the sub's airlock, but can't manage to path through the docking port module.
_(the bot had a scooter on it to make it more obvious its trying to swim)_
**[Sometimes they also get stuck by trying to swim through the corner of the dugong's airlock on the outside when attempting to path to the same "wait" location]**
![pathingthing](https://user-images.githubusercontent.com/72674994/98405987-20187380-20a8-11eb-89f1-414bc60432bd.jpg)

**Comment by itchyOwl** [comment]
Not sure if we'd even want to allow the bots to go through the airlock.

**Comment by itchyOwl** [comment]
QA: test if it's still an issue. If it is, let's just close the ticket as "not planned". If it's not, let's close as "completed". It's a very minor issue imo. Wouldn't use time for fixing it, if it still doesn't work (as I suspect it won't)

**Comment by itchyOwl** [comment]
If, however, the bots get stuck somewhere, it's something we should try to fix.

**Comment by NilanthAnimosus** [comment]
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/cd25531824ed25a6c9c237ce3357e07a2cb41542, Closing as completed.

Notes:

They don't get stuck on the door itself (and will head to the waypoint, open the doors and go inside just fine on follow command, and swim outside just fine too).

However, they do have a tendancy to follow the submarines waypoints and attempt another (even if not possible such as a hatch without buttons) entry despite a close distance to the door (As the submarines are almost always closer if its docked), but it seems like a fairly minor issue in this case.

![image](https://github.com/Regalis11/Barotrauma/assets/29177976/c1cb3d06-09d1-4782-ae15-d58b38a8a964)
