### ISSUE TITLE
Stealing using toolbelts doesn't register as stealing

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4346]
**Description & Steps To Reproduce**
Dragging and dropping outpost owned items into the toolbelt doesn't count as stealing to outpost dwellers, even though said object is marked in red (but they register when stealing said items from cabinet into hotbar)

**Version**
[0.1100.0.7]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eef524374558ce9d8c53d177e741cc4c374086f2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
