### ISSUE TITLE
Station medics heal injured pets

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4348]
**Description**
They attempt to heal pets when they're injured, often killing them as a result of opiate overdose.

**Steps To Reproduce**
- Have a station medic in sight
- Spawn a pet
- Obtain a SMG and hit the pet with a single shot

**Version**
[0.1100.0.7]

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@9c895bd. Bots should now ignore healing pets.

**Comment by Lithosagym** [comment]
Tested, medic bots no longer heal pets, working correctly.

**Comment by Rokvach** [comment]
Closing.
