### ISSUE TITLE
Weird plasma cutter and welding tool hitbox inside hulls

### ISSUE THREAD

**Issue by the1eyedduck** [Regalis11/Barotrauma#4350]
plasma cutter and welding tool's fire draw from center of the tool instead max range at the edge of 1 hull to another making bots unable to fix leak.
![hull](https://user-images.githubusercontent.com/74727878/99694204-bc864100-2abe-11eb-93db-b319fa107f9b.jpg)
![edge](https://user-images.githubusercontent.com/74727878/99694215-c019c800-2abe-11eb-842a-5ec09f219eed.jpg)
bot unable to fix leak
![problem](https://user-images.githubusercontent.com/74727878/99694228-c5771280-2abe-11eb-84ba-cd18d6e8d7bc.jpg)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
