### ISSUE TITLE
Cyanide is able to permanently stun molochs (possibly larger?) akin to paralyzant before adjustment

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4351]
**Description**
Cyanide is able to permanently stun molochs and keep it that way due to its attributes of applying stun in the later stages of cyanide poisoning.

Probably a conditional that checks the mass of targets similar to #3560 

**Version**
Tested in [0.1100.0.7] but possibly in earlier versions

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5b25292caaa264bfaddc797eb2b568a281426391

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
