### ISSUE TITLE
[0.11.0.7] Side Path is too small to travel through with the sub to get to the mission

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4354]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We chose a hammerhead swarm mission and this mission was placed in the middle of the side path of the level. The entrance to the side path on the left side were all too small for the sub to fit through. The exit of the side path had huge upward current that prevented us from getting into it. We had to exit the map on the right side and follow the walls underneath the level to get to the hammerhead swarm.

![Capture](https://user-images.githubusercontent.com/5086682/99745441-a5882480-2aa7-11eb-9eb1-5823e5999d41.PNG)
![Capture](https://user-images.githubusercontent.com/5086682/99747594-d6b52480-2aa8-11eb-9ef6-1c1d83fe52de.PNG)
[HoloTwitchSidePath.zip](https://github.com/Regalis11/Barotrauma/files/5570721/HoloTwitchSidePath.zip)
**Version**
0.11.0.7

**Comment by ezjamsen** [comment]
@Regalis11 What do you think? I personally consider it ok if side paths are occasionally too narrow for a sub to fit through, this just encourages a bit more exploration of the level beyond the most obvious path. If it's a consistent thing that's happening though, or if we end up with levels were the destination is unreachable by any path, then that's a more serious issue

**Comment by Regalis11** [comment]
Yeah I agree, I don't think it's a bad thing the sub can't always fit through the side paths. The main path should always be large enough, but the side paths have a random width that isn't affected by the size of the submarine (about 20 - 80 meters).

I do agree that this particular level had a very unfortunate layout, but there were still ways to complete the mission: for example using a smaller sub or a drone, getting to the side path from below or luring the monsters up to the main path. As long as these sort of levels aren't too common, I think we can keep it as-is.
