### ISSUE TITLE
Communicate to the player that you can switch characters in SP campaign

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#4355]
It seems some new players aren't aware that you can switch characters at will in the SP campaign.

We should probably indicate it somewhere (tutorials, start of the SP campaign, in the death screen https://github.com/Regalis11/Barotrauma-development/issues/1467).

**Comment by danielasteljoki** [comment]
One place we could teach that is in the planned outpost tutorial.

**Comment by ezjamsen** [comment]
Beyond the tutorial, we could add a quick flashing highlight around the portrait of the next living crewmember in the crew list (expanding the list if need be, should it be collapsed).

**Comment by ekqvist** [comment]
There are two hints now implemented that are related to this. If the player plays long enough without switching their character, they should get a reminder hint about it. If the player dies, they should get a hint about being able to switch to another character.

**Comment by Regalis11** [comment]
This is included in the new [role tutorial](https://github.com/Regalis11/Barotrauma-development/issues/3456), I think we can close this ticket
