### ISSUE TITLE
Custom Submarine will not move horizontally in Story Mode

### ISSUE THREAD

**Issue by TheFlyingSpaghettiMonster** [Regalis11/Barotrauma#4356]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have completed a custom submarine, with 10 versions, anything made after the 7th version refuses to move horizontally in only Story mode. In sub editor testing, and in mission mode, the submarine works great, and moves at over 115HM/HR, The issue occurs in both Single Player and Multiplayer

**Steps To Reproduce**
Via running specific version of my custom submarine.

**Version**
v0.10.6.2, Windows

**Additional information**

![20201120202236_1](https://user-images.githubusercontent.com/23041788/99784377-d469cd80-2b6f-11eb-8094-36fa95e0c257.jpg)
![20201120202247_1](https://user-images.githubusercontent.com/23041788/99784414-e0558f80-2b6f-11eb-9ee8-19e796f3ff03.jpg)

**Comment by Xeavas** [comment]
I don't think its powered

**Comment by ignis05** [comment]
You should probably attach the submarine file, otherwise it might be impossible to replicate.

**Comment by mrjpjr** [comment]
The power light for the engine is not on.
Is the engine getting power?

**Comment by Regalis11** [comment]
It does seem like the engine isn't receiving power. If you can provide us the sub file (you need to .zip it to use it as an attachment in GitHub), I can take a look and see if I can diagnose the issue.
