### ISSUE TITLE
[0.1100.0.7] - Ready Check persists when leaving an outpost and/or back to lobby.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4359]
**Description :**
Initiating ready check getting the result UI to show and then not closing it results in it persisting when backing into lobby and/or undocking from an outpost and going to a different area

![rdychk1](https://user-images.githubusercontent.com/72674994/99796245-20187900-2b68-11eb-94c8-614802234735.jpg)
![rdychk2](https://user-images.githubusercontent.com/72674994/99796250-20b10f80-2b68-11eb-97ca-af8c4ee0a403.jpg)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78dea2b263641899f903a578e81a2550cf8e4230

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/695e62f8bd07ab48bd493c271e4de912decf2717

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
