### ISSUE TITLE
Give item to specific player via commands

### ISSUE THREAD

**Issue by Tazial** [Regalis11/Barotrauma#436]
Currently, there is no way for an admin or a someone with access to the server CLI to give a specific player an item.  The closest thing that can be managed is using the `cursor` feature to drop the item at their feet, a solution which

 * Allows other players to intercept the item
 * Doesn't guarantee that the player will actually notice and pick up the item
 * Can't be done without visually seeing the player (i.e. needs to be done while logged in using the client and in sight of the player)

I propose that a command is added or modified to allow server operators to add an item directly to a player's inventory.  For example, if the `spawnitem` command were modified to take a clientid as an alternative to `inventory` or `cursor`, an admin could give an oxygen tank to a player with clientid 3 using the command `spawnitem oxygen tank 3`.  Of course, there are other ways of implementing this, such as adding a new command, or giving items based on name instead of ID, but this is just an example.

**Comment by Regalis11** [comment]
Added in 8543bf1
