### ISSUE TITLE
Ruins spawn with detached wiring

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4360]
Branch: dev
Also a issue on the latest Unstable

Screen: Level Editor (Test mode)
Level Type: coldcavernsbasic

Seed: kVOMrfEQ

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/90a570f5-b3b2-4059-bb68-e9363a82ff91)

Seed: 543y4

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9636d9f7-e7f0-4dbb-a7f7-14e7d7995b3e)

Seed: 43t634

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e10bc879-4b3a-45c7-9f5f-ca669bc63584)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cdd8427122608191f48d9632f87377a595c9d028

**Comment by Rokvach** [comment]
Tested, wasn't able to repro. Working correctly. Closing.
