### ISSUE TITLE
[Suggestion] Make replacing welding fuel tanks in welders lose karma

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4363]
I've seen enough times where someone just traps the entire sub by replacing welding fuel with oxygen tanks, and welding fuel in the diving suits. There'd be no reason to ever put them in, so maybe incur a small enough penalty that allows for accidents but punishes if someone does something like replace every welder on the fuel with oxygen tanks? Also, I don't know how plausible it would be, but I've had someone hand me a trapped welder and then when I stun baton them I got space herpes. Maybe there could be a way to prevent that?

(The only reason I see that there should be no karma loss is if the person is a traitor)

**Comment by ezjamsen** [comment]
This keeps coming up. Let's do it.

**Comment by Neko-LoverDisc** [comment]
if I have anything to say about it, I'd suggest maybe adding a small enough threshold to allow for accidents? Like, if I accidentally replace my diving suits oxygen tank with welding fuel, I'd rather not respawn with space herpes to add insult to injury

**Comment by Krzeszny** [comment]
> if I have anything to say about it, I'd suggest maybe adding a small enough threshold to allow for accidents? Like, if I accidentally replace my diving suits oxygen tank with welding fuel, I'd rather not respawn with space herpes to add insult to injury

One does not simply replace oxygen with welding fuel _by mistake_.

**Comment by ekqvist** [comment]
Made a few more improvements to this:

- the penalty being incremental is now optional, but enabled by default (Regalis11/Barotrauma-development@f64ef7b)
- it's now possible to define the max total penalty (Regalis11/Barotrauma-development@88c5ff8)
- added the new karma options to the server menu (Regalis11/Barotrauma-development@4ca677f)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
