### ISSUE TITLE
Relays connected in series don't share the same load

### ISSUE THREAD

**Issue by AudibleDruid** [Regalis11/Barotrauma#4366]
Transferring power between two or more relays doesn't work properly. Ex. Two relays connected in series don't share the same load even though two junction boxes in series do share the same load. Basically if two or more relays are connected in series specifically with power in and out lines then they won't work properly. This makes it hard for things like over voltage and -undervoltage protection circuits to work because in-between every relay connection I need to add a junction box.

**Comment by Regalis11** [comment]
Sorry for the late reply, I didn't have time to look into this until now.

I'm afraid I couldn't reproduce the issue. I built a simple circuit with 2 relays in series, connected to a lamp with power consumption set to 1000 kW, and both relays seem to display the load as 1000 kW. Here's the sub I did the testing with:
[Relay-series-test.zip](https://github.com/Regalis11/Barotrauma/files/5824146/Relay-series-test.zip)


I suspect the problem you're having is some kind of an edge case that only occurs in more complex circuits. Would it be possible to provide us the sub file where this issue occurs (note that you need to zip it first to attach it to a github post), or describe what kind of a circuit it happens in?

Thank you in advance!
