### ISSUE TITLE
Legacywatcher messed up textures

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4367]
[Bug, Texture]
![image](https://user-images.githubusercontent.com/47284081/99894491-108a5480-2c7c-11eb-8c92-fa0644a6126e.png)
"Legacy watcher had a ... rough transition to steam"

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56ebecf95cdac589a8c49abb1eed812c7b0aed01

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
