### ISSUE TITLE
[0.11.0.7] Crash during fight between two players one with harpoons and other with syringes.

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#4368]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was having a gunfight with a friend and it crashed

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5578975/crashreport.2.log)

**Comment by Regalis11** [comment]
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/35412240cc720c362a85a56a290c8b000b001dbb

**Comment by Rokvach** [comment]
The change is so small that it shouldn't cause any major issues. Closing.
