### ISSUE TITLE
[Unstable 0.11.0.7] Persistant Quartz Samples

### ISSUE THREAD

**Issue by lemonblazer** [Regalis11/Barotrauma#4369]
**Description**
During a Quartz Mining(?) quest, quartz samples persist after the quest is completed if the quartz is put into a Storage Container (what used to be the Toolbox.)

**Steps To Reproduce**
Accept a Quartz Mining quest, go to the cave and collect your samples, put the samples into a Storage Container, put the Storage Container into a cabinet in your sub, then navigate to the next outpost to complete your quest. On completion, the quartz samples will still be in the Storage Container in your cabinet aboard your sub.

**Version**
v0.11.0.7 ReleaseMac, revision 77e9304c7a

**Additional information**
Unsure if this is intentional, but since the log books disappear upon completion of a Salvage mission, I assume it is supposed to be the same here.

**Comment by Xeavas** [comment]
It is intended that you keep the samples, thematically you're helping them survey deposits in the area, there's much more of where that came from once its confirmed.
