### ISSUE TITLE
Thalamus threw my Drone back at the sub, and it glued onto us

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4374]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://www.twitch.tv/videos/812215208?t=03h12m20s
We found a wreck and sent the drone down to check it. I got close to it with the drone and discovered it was a Thalamus. I shot some leucocytes with Piercing ammo and then tried to pull my drone up upward to get away from the Thalamus as fast as I could, but the Thalamus fleshgun dragged my drone down. I shot the fleshgun sack like 2-3 times with Piercing Ammo (I doubt it was enough to kill it), and the fleshgun let go of the Drone. The drone got slingshotted upward and smashed into the sub, breaching the insides completely. Despite being filled with water, the drone did not sink, and remained attached and glued on the sub. I was not able to drive the drone at this point. It was possible to nudge the drone around by using the level wall to scrape the drone position around.

**Version**
0.11.0.7

**Comment by DreamerOfRain** [comment]
Was recommended by Rokvach to upload a video of this situation here:

https://user-images.githubusercontent.com/70696707/107384597-b1bed380-6b24-11eb-8375-daa9230061f2.mp4

Ver 0.1200.0.2

**Comment by Regalis11** [comment]
No known steps to repro, might have been fixed since the ticket was created since there have been several changes to the rope logic since.
