### ISSUE TITLE
Сrash when working with the fabricator/deconstructor

### ISSUE THREAD

**Issue by Vinogrrrr** [Regalis11/Barotrauma#4375]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes when choosing a fabricator/deconstructor.

**Steps To Reproduce**
In game or test submarine redactor , using the fabricator/deconstructor will crash

**Version**
Game version 0.10.6.2 (Windows).

[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/5581745/crashreport.4.log)

**Comment by ekqvist** [comment]
Duplicate of #4160. Fixed on Unstable and will be fixed with the next update on Stable. Sorry for the inconvenience!
