### ISSUE TITLE
[Feature Request]: Some form of life monitor to monitor diver health

### ISSUE THREAD

**Issue by ariffjeff** [Regalis11/Barotrauma#4376]
- [x]  I have searched the issue tracker to check if the issue has already been reported.

I believe there needs to be some form of a life monitor on the main sub, either as a control panel/handheld gizmo/etc..., that allows you to monitor the lifeline/health of a diver or many divers at once. Too many times I or other players have gone outside the sub to explore ruins and wrecks only to die and no one back on the sub to realize this turn of events. This often leads to painfully long periods where you wait in spectator mode for anyone still alive on the sub to realize the away-party has died and that they need to do something instead of just continuing to wait around. This is much, much worse when your game isn't respawn shuttle capable.

This problem is obviously not an issue when you're playing with friends as you can just notify them in Discord or something of your recent tragic passing, but purely public games tend to suffer from this in my experience. Of course this issue could be remedied mostly by having better teamwork but it's public games we're talking about here.

The key goal here is to prevent the issue of dead players having to agonizingly wait around when they're dead for everyone else to continue on with the mission.

**Comment by thegrb93** [comment]
That's what sonar beacons are for.

**Comment by ariffjeff** [comment]
I forgot about those lol. But even then it might not be immediately obvious that a diver with a handheld sonar on them has died. Someone watching the command sonar console could very well not realize a diver's death because they could misinterpret a diver not moving as them using a plasma cutter on an object or organizing their inventory or something else. It just feels to me that anyone not paying close attention will more than likely miss the signs of a dead diver. I think I'm really just trying to suggest a feature that _actively_ makes the death more obvious.

What about handheld sonars that just display a heart flat-line or a small description message saying that the diver wielding it is dead when someone looks at it on the sub's sonar console?

**Comment by thegrb93** [comment]
Nobody's going to sit still for longer than 20s. You'll know if they're dead.

**Comment by ariffjeff** [comment]
Fair. My only concern then is that in public games people usually don't frequently checking the sonar to check on divers. So the problem still exists that sucks out fun from those stuck in spectator as they have to wait around, hoping someone notices. That's been my experience anyways.

**Comment by Xeavas** [comment]
Agree on the utility on a life link sort of system, Something that gives a more expensive/high-tech approach for out of sub exploration, and might be potentially useful in submarines too. An alternative is a long tether system where radio communications could be established even at long distances, and potentially the health status of the dive crews (having some sort of device) too.

**Comment by thegrb93** [comment]
Not a fan of dumbing down the sonar beacon but up to devs.

**Comment by ariffjeff** [comment]
Some of us are unfortunately stuck playing in public games more often than not as we don't have a dedicated friend group to play Barotrauma with. Given the luck of the draw in getting good teammates in public games being something that I would define as "OK" at best, I believe a life monitor system or something similar would at least be beneficial to somewhat alleviate the issue of long wait times for dead divers.

Ultimately I think it just comes down to the balance of what is fun versus realism or "dumbing down" as you say. With this being a video game, focusing on the fun is probably more worth it.

**Comment by thegrb93** [comment]
Also I completely forgot, but can't you also see when someone dies in the crew list? Not sure if that was changed or not. (It should be if it hasn't)

**Comment by ariffjeff** [comment]
I don't know about that but hitting tab to display the player list will definitely tell you. Although I'm not confident that people check that very much either.

**Comment by ezjamsen** [comment]
Thanks for the suggestion. We have no short term plans for this sort of thing, but we are upgrading the status monitor and the information it provides, let's see where that redesign takes us, and if we end up with this sort of functionality as part of that upgrade.
