### ISSUE TITLE
Buff Ethanol & Tobacco psychosis resist

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4379]
Obviously they should still not be able to compare with antidote Haloperidol, but the amount you get from drinking a whole bottle (2 uses) or the amount gained from smoking 1 bag of pipe tobacco (after you spent so long growing it and crafting it for it to get used up in 5 seconds) is almost completely insubstantial when consumed in 'reasonable' quantities.

**Comment by JeroonBosch** [comment]
Haloperidol has following interaction:

      <StatusEffect tags="medical" type="OnUse" target="Limb, This" duration="1">
        <Sound file="Content/Items/Medical/Syringe.ogg" range="500" />
        <ReduceAffliction identifier="psychosis" amount="100" />
        <ReduceAffliction identifier="hallucinating" amount="100" />
      </StatusEffect>
      <StatusEffect tags="medical" type="OnFailure" target="Limb, This" duration="1">
        <Sound file="Content/Items/Medical/Syringe.ogg" range="500" />
        <ReduceAffliction identifier="psychosis" amount="25" />
        <ReduceAffliction identifier="hallucinating" amount="25" />
      </StatusEffect>

While Ethanol has 600 resistance:
      <StatusEffect type="OnUse" target="Character" disabledeltatime="true">
        <Affliction identifier="psychosisresistance" amount="600" />
      </StatusEffect>

and the pipe only has 10?
      <StatusEffect tags="medical" type="OnUse" target="Character">
        <Affliction identifier="psychosisresistance" amount="10" />
        <RequiredItem items="pipetobacco" type="Contained" />
      </StatusEffect>

Should the usage also reduce existing afflications by a small amount, or still only have the resistance?
Also not 100% sure how the resistance works. Is a value of 10 resistance:
- 10 seconds of 100% resistance? 
- a 10% resistance lasting for X(?) seconds
- Does this resistance stack?

**Comment by JeroonBosch** [comment]
Looking at the afflication code, it seems Ethanol is already at the max amount for the current effect:
`  <Affliction
    name="Psychosis Resistance"
    identifier="psychosisresistance"
    description="Psychosis be gone."
    type="resistance"
    isbuff="true"
    limbspecific="false"
    indicatorlimb="Head"
    maxstrength="600">
    <Effect minstrength="0" maxstrength="600"
      strengthchange="-1"
      resistancefor="psychosis"
      minresistance="0"
      maxresistance="0.75"/>
    <icon texture="Content/UI/MainIconsAtlas.png" sourcerect="640,896,128,128" color="10,193,114,255" origin="0,0"/>
  </Affliction>`

Increasing the '600' would then not do anything, so instead reducing current psychosis by f.e. 5% would be more useful.
Am I right for thinking that at 300 resistance, there would be a 0.5 * 75% (max resist) = 37,5 % resistance?
And so, smoking pipe only give a (10/600) * 75% resistance?

**Comment by JeroonBosch** [comment]
Note to self, on useful console commands:
spawnitem Deliriumine inventory 1
spawnitem Ethanol inventory 2
spawnitem "Captain's Pipe" inventory 1
spawnitem "Pipe Tobacco" inventory 5

**Comment by JeroonBosch** [comment]
Solution pushed to dev:
Ethanol now also reduces psychosis by 10s * 2% = 20% total in addition to giving drunkness.
Pipe Tobacco is a bit better at giving resistance (20 out of 600 given per second of using it, instead of 10)
It also reduces psychosis by 10. In playtesting using ~10% pipe tobacco would reduce ~20% of Psychosis which seems fair.

**Comment by Regalis11** [comment]
Implemented in the latest unstable (v0.17.6.0)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
