### ISSUE TITLE
[Unstable 0.11.0.8] Ruins can't be fully traversed if they spawn partially in walls

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4381]
Game Screen: Level Editor
Level Type: coldcavernbasic
Seed: y34y34y

In the image below I am unable to go past the white line highlighted by the yellow arrow. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1035986b-ed8e-42bd-aae9-9d1ec9ef4fda)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b400fef3709f442d1d4f2732fcea624b95711b3

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Kaillera** [comment]
![Capture](https://user-images.githubusercontent.com/5086682/103897502-aad61880-50c1-11eb-9035-733381882fe6.PNG)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/5781798/Save.zip)

**Comment by Rokvach** [comment]
Reopening

**Comment by Regalis11** [comment]
There seems to be something wrong with the save file, I'm getting an error message about it being corrupt when trying to load it.

**Comment by Kaillera** [comment]
I downloaded it from the same link and loaded it just fine?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/becaa3c8370123a6868e690dfa61fd1bcaaa67c4

**Comment by Rokvach** [comment]
Tested, didn't spot any issues with the provided save. Seems to be working correctly. Closing.
