### ISSUE TITLE
Show FlowerSprites in sprite editor

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4383]
[Modding, Feature Request]
Self explanatory. <Sprite>s and <BrokenSprite>s and a variety of other things are recognized by the sprite editor and given options to edit their sourcerects, but <FlowerSprite>s aren't, which is pretty inconvenient given there are usually a lot of them.
This applies to VineSprite and LeafSprite as well.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/24a1130d4c9be7a720edf7919327275c5578b399

**Comment by Rokvach** [comment]
No issues, closing.
