### ISSUE TITLE
Allow the bots to carry more than one item at a time, especially when cleaning up.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#4387]
Currently the bots can only take one item at a time, which makes cleaning up a slow process.

**Comment by itchyOwl** [comment]
Some things that we'd have to solve:
- How many items would be allowed to be carried at the same time? A fixed amount or a percentage of the remaining inventory space?
- How to handle different items? Perhaps only allow taking items that belong to the same place?

**Comment by Regalis11** [comment]
Looks like this has already been implemented (as far as stacks go at least). https://github.com/Regalis11/Barotrauma/issues/4958

Imo it doesn't seem necessary to make them clean up different items at the same time.
