### ISSUE TITLE
Unstable - Ballast flora branches instantly respawn every step during 'grow to target'

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4388]
**Unstable v0.11.0.8**

When ballast flora starts growing towards a target node, all of the branches that are part of the expansion growth instantly respawn each time it takes a new 'step' making it impossible to stop an expanding growth until it arrives at its destination and is no longer re-spawning, in addition to just looking weird and janky when a branch you just burned down to a stump suddenly 'teleports back' again.

The only way to destroy it being to wait until it reaches its destination and then immediately burn it off triggering the 'ignore for X steps' behavior.

**Steps to reproduce:**

Infect a pump and wait for it to begin expanding towards another item, or until you see growing red branches in debugdraw.
Partially or completely destroy the growing branch with a flamer, and it just fully re-appears a second later.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/214cad061e6d011239104a6476338bbf8426f3f6 ballast flora now cancels out GrowToTarget state if one of the branches it uses to grow towards it dies

**Comment by Xeavas** [comment]
[0.1200.0.0] Waited till ballast flora went into state `grow to target` and blasted it with a flamer, issue not observed, unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
