### ISSUE TITLE
You can use Flash Powder as a medical item (It detonates when used) + Suggestion

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4389]
### Issue

**Description**
You can use Flash Powder like a medical item, but when used, it explodes in your face.
(I am pretty sure it's not intended that it can be used as a medical item)

**Steps To Reproduce**
- Obtain Flash Powder
- Open health UI and use Flash Powder by dragging and dropping or hotbar quick use

**Version :** [0.11.0.8] (Unstable)

### Suggestion
While thinking about it, I would like to suggest the Flash Powder being an item with intended medical use. It would probably be one of the best anti bleeding due to rapid cauterization but will give burns to applied limb. It's condition used should depend on the amount of bleeding negated.

**Comment by Regalis11** [comment]
This is actually intentional.
