### ISSUE TITLE
Replace assets taken from BTE?

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#439]
I should've written this issue ages ago, but I keep forgetting to do it.

It's been brought to my attention some time ago that some of the assets introduced in pull request #188 may have sourced from another game.
```
they also added the sounds for doors and ducts when they break xD
I took those from another game, maybe we should tell them that D:
```
This chatlog suggests that the following file may need to be replaced:
https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaShared/Content/Items/Door/ductBreak.ogg

**Comment by ChikoEduardo** [comment]
Oh yeah, the breaking sounds were indeed from another source. Most of the sounds I use are from other sources so yeah.

**Comment by Regalis11** [comment]
Replaced in d1d5b86
