### ISSUE TITLE
Bots don't equip diving gear before suffocating if there's no water/leaks in the hull

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#4390]
Due to the incorrect calculations regarding the oxygen levels the bots have had hard time deciding whether or not to use the diving gear (in practice, masks, if there's any available).

v0.1100: The bots don't equip the diving gear if the oxygen levels drop. 

v0.10.6.2 and before: The bots equip the masks even when they don't actually need them.

To be clear: the earlier suffocation issues were not directly related to this issue.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@370bb6e.

Please test this thoroughly using the following tests, but also any other means that you can think of.

Steps to repro:
1. Edit a submarine in the editor so that oxygen generator is broken (set condition to 0).
2. Play either in test mode or using the saved sub in a campaign.
(3. Ignore the generator so that bots don't fix it.)
4. Spawn multiple bots in the sub and make them hold position in the same hull (spawn human cursor).
5. The bots should now equip masks when they need to and unequip them when they are not needed.
(6. Test how they react when you repair the generator).

**Comment by Rokvach** [comment]
Tested, when air quality dipped below 35-40 every bot on the sub put on a diving mask, repaired the oxygen generator and and when air quality went above 40 everyone took masks off. Working correctly. Closing.
