### ISSUE TITLE
Stuck in internal ceiling of sub

### ISSUE THREAD

**Issue by KelvallRogers** [Regalis11/Barotrauma#4392]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During a rapid decent (lost control) I became imbedded in the ceiling of the sub and was stuck. Had no major trauma, barely any damage. Upon striking the ground, remained stuck. 

**Steps To Reproduce**
Rapid descent on the basic starter scout sub (Azimuth) while in hull breached compartment full of water. Pressed against ceiling and stuck there. 

**Version**
Windows, 0.10.6.2

**Additional information**
2 Player with 1 bot, private game, no mods or other changes. First playthrough, random mission. Hull breached by crawlers, was in the pressurized suit. Was in battery compartment on the alien artifact hunt.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
