### ISSUE TITLE
Lights of coilgun/railgun are slightly misaligned

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4394]
**Description**
When rotating them (aiming and shooting, not sub editor) the lights of said weapons seem to pivot around a different point.
![CoilgunCenter](https://user-images.githubusercontent.com/72674994/100432172-2a8cc280-30d4-11eb-9516-3815a4546546.jpg)
![CoilgunLeft](https://user-images.githubusercontent.com/72674994/100432200-35475780-30d4-11eb-8fee-b1def6b7e3a4.jpg)
![CoilgunRight](https://user-images.githubusercontent.com/72674994/100432207-38424800-30d4-11eb-9234-c32412cf29c6.jpg)
![railgunBL](https://user-images.githubusercontent.com/72674994/100432212-3b3d3880-30d4-11eb-9012-6b05ed23702b.jpg)
![railgunBR](https://user-images.githubusercontent.com/72674994/100432215-3d06fc00-30d4-11eb-83a6-9c92f0f9393f.jpg)

**Version**
[0.11.0.8] (Unstable)

**Comment by itchyOwl** [comment]
Might not be directly related, but I'll post it here nevertheless, as I'm too lazy to investigate and I don't want to create separate ticket for it: the muzzle particle is a bit off too.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/dcc1adaf-2edf-4c0b-8362-dd3e2623a0fc)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/92fdafc8-b4c5-4be1-a53b-6ab12fc1237e)

**Comment by Regalis11** [comment]
Removing the art ticket, I'm pretty sure this is due to the origin of the item (as opposed to the origin of the barrel) being used to position the lights and particles.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6b9f89ec32a7dcbeb499e157a29d5c885cb7a6c3

**Comment by Xeavas** [comment]
[0.1200.0.0] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
