### ISSUE TITLE
Gun lights getting flipped

### ISSUE THREAD

**Issue by Ridicolaz** [Regalis11/Barotrauma#4395]
- [o] I have searched the issue tracker to check if the issue has already been reported.

Coilgun light is facing the opposite direction the coilgun is facing in a flipped sub in pvp. 

Have a coilgun and set it to dont draw behind sub. Then go into a combat mission and in the inverted sub the lights are flipped.

Windows Stable.

[Video of it happening](https://cdn.discordapp.com/attachments/427654262453960724/781804431682961458/Barotrauma_2020-11-27_00-51-26.mp4)

**Comment by Regalis11** [comment]
Should be fixed in the latest unstable

**Comment by Rokvach** [comment]
This has been fixed and tested already, closing.
