### ISSUE TITLE
Kastrull - Bots has troubles with the Ballast Tanks

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4396]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the Kastrull, bots have a hard time getting in, getting out, and repairing the pumps.

![Capture](https://user-images.githubusercontent.com/5086682/100468347-3cee0880-30a2-11eb-8196-8427164f5210.PNG)

When bots are trying to reach Ballast Tank A to repair from the bottom left side and having to climb the ladder, the bots will jump off the ladders at Section [B] prematurely. They may try to do this several times and then give up and get stuck rubbing their face against the wall on the left Section [A].

Alternatively if they got into the Tanks A/B/C coming from the top side, they don't know how to climb the ladder out and get stuck either swimming around in the right side Section A and/or B. They will usually stay near the ladder instead of going right to fix the pump. They will usually consume a lot of oxygen tanks and drop oxygen mask into the corner of the ballast tank at Section A if left unattended.

**Steps To Reproduce**
-Play on Kastrull Singleplayer/Multiplayer or load it on Sub Editor Test Mode.
-Wait for pumps to deteriorate or reduce the condition of the pumps.
-Ask a bot to go repair damaged systems.

**Version**
0.11.0.8

**Comment by itchyOwl** [comment]
I think it's the same issue as here: #4642. Should be fixed now in dev.

**Comment by Xeavas** [comment]
[0.1200.0.2] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
