### ISSUE TITLE
[0.11.0.8] Multiplayer - Server Entity Kicks by Ballast Flora

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4397]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://www.twitch.tv/videos/816829620?t=00h56m46s
[111.txt](https://github.com/Regalis11/Barotrauma/files/5608868/111.txt)

We were playing multiplayer campaign and we were infected by Ballast Flora in this twitch video at 0:56:46. I went into the ballast tank and verified that we have Ballast Flora. Once I was right next to the Ballast Flora I recieved the error at Line 144 in the dump txt above. I rejoined the server and the flora matured. I went unwire the set_targetlevel wire off the infected pump and pumped out the water. Then I unwired the Power_In. We dealt with the Flora with explosives, and fires. At 1:04:30, after we have dealt with the Flora, I went to rewire the pump wires back. The moment I touched the wire I was kicked by the error at Line 281, but there seem to have been lots of error before hand starting at Line 194. I was still able to rejoin and resume the session without being locked out.

**Version**
0.11.0.8

**Additional information**
[event_error_log_client_Kaillera_1203 AM.log](https://github.com/Regalis11/Barotrauma/files/5608906/event_error_log_client_Kaillera_1203.AM.log)
Pending Event Log from host. Not sure if I'll be able to get it any time soon.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eb7ed943204e29f7335f84205f0fac3890f59499

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue. Looks to be working correctly. Closing.
