### ISSUE TITLE
Issues building on Linux

### ISSUE THREAD

**Issue by Tazial** [Regalis11/Barotrauma#440]
I just started working with the C# part of the codebase, and I was having some troubles building the project on Linux.  I'm completely new to C#, so these might be problems with my environment, not with the code itself, but I didn't see my specific issues documented anywhere else, nor did I see any other issues, so I figure I'd at least be contributing that.  In particular, I had to make to changes in order to get the game to build on Linux:

* Move the file at `Barotrauma/BarotraumaShared/Source/GameSession/GameModes/MultiplayerCampaign.cs` to `Barotrauma/BarotraumaShared/Source/GameSession/GameModes/MultiPlayerCampaign.cs`
* Change the line `<Reference Include="System.XML" />` to `<Reference Include="System.Xml" />` in the .csproj files for both BarotraumaServer and BarotraumaClient.

Prior to making the former change, attempting to build either project `CSC : error CS2001: Source file '$BAROTRAUMA/Barotrauma/BarotraumaShared/Source/GameSession/GameModes/MultiPlayerCampaign.cs' could not be found.`

The latter fixes the error `error CS0012: The type 'XmlWriter' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'` and 17 other similar errors, all involving adding `System.Xml` as as reference.

I'm not sure if the two changes that I made are the "correct" fix for these issues, but I figured I'd make the issue known so that it can be fixed, or there's a little more documentation on how the C# environment should be set up to prevent this from happening.

**Comment by juanjp600** [comment]
Should be fixed now: https://github.com/Regalis11/Barotrauma/compare/1a84b6cae72a...f59db98188e7
