### ISSUE TITLE
Berilia Clowns

### ISSUE THREAD

**Issue by HypnoPants** [Regalis11/Barotrauma#4403]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Simply put, I 'love' the Berilia, the massive cargo bay and all the little stuff everyone has to take care of, amazing.
However, there is one door at the very top right, a tiny clown closet... problem is, no one can enter it, not even the captain. And so it remains closed, but then monsters attack that point and it causes a leak filling the closet, we then have to either go outside to fix the leak, or cut the door open and fix the leak from inside.
Problem then is, especially with AI crewmembers, they fix the door... and the problem then happens again.

I like the honkmother easter egg, but that door needs to be either unlocked or able to opened by at least the captain.
Or better yet, is there a way to set an object or door as 'don't fix'? Or while in-game, can I rewire it or something to be permanently unlocked?

**Steps To Reproduce**
Pretty simple, just load a game with the Berilia. That spot has no gun, so the monsters always go for it. Which is also why it's a huge pain in the ass to keep fixing the leaks in that tiny closet. Other than that, the Berilia is a fantastic beast that's fun to play around with.

**Version**
v0.10.6.2 Windows

**Additional information**
Edit: In response to LePiromano, crowbars didn't seem to work either.

**Comment by LePiromano** [comment]
use a crowbar

**Comment by HypnoPants** [comment]
> use a crowbar

You'd think it would be that simple :D crowbars didn't seem to work on it.

**Comment by HypnoPants** [comment]
> use a crowbar or wait until the next update wich adds the "ignore" order

oh neat, that's exactly what would work :P

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce the crowbar problem in either the current public version or the latest unstable version: I got the door to open with a crowbar with no issues.

**Comment by HypnoPants** [comment]
> I'm afraid I wasn't able to reproduce the crowbar problem in either the current public version or the latest unstable version: I got the door to open with a crowbar with no issues.

Weird, I just tried it again, holding crowbar, pressing E or holding E, neither is working.
![image](https://user-images.githubusercontent.com/22647132/100548218-6d5faf00-3228-11eb-8022-e9b2ca1d1523.png)

**Comment by HypnoPants** [comment]
Tried it again on a new save, new berilia.
It worked fine to open it this time.

Went back and tried that old save again, and it still won't open with a crowbar.
I really couldn't tell you why :D but at least it works on this new save.

**Comment by Regalis11** [comment]
That's strange. The only explanation I can think of is that you started that save with some earlier version of Berilia where that door was bugged. But anyhow, since we couldn't find a way to reproduce this and it doesn't seem to occur with a fresh save, I think the ticket can be closed.

Also, as a tip, there's a key card for that door hidden somewhere in the sub. ;)

**Comment by HypnoPants** [comment]
Sorry to reopen this, but it happened in a fresh save :P when I was playing multiplayer too.
neither I, nor my friend, could open with a crowbar...

However, now that I know there's a keycard hidden somewhere... hehehe. Thanks!
