### ISSUE TITLE
Manually set docking-port direction priority

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4406]
Feature Request:
Given the issues with docking position randomly changing between rounds, A useful QOL feature for sub builders would be to manually set what direction a port is allowed to dock in; 'top/left' 'bottom/right' 'any'

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/b63672ad5f8be04f0af6eb8eb6666e81ba2f7c58

**Comment by Rokvach** [comment]
The setting was missing on editor side, should be present now since
https://github.com/Regalis11/Barotrauma-development/commit/d6fe9c2b5a1f5dc09f1316225f852524ae54e842

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
