### ISSUE TITLE
Batteries can only recharge from junction boxes and relays / docking ports do not behave like junction boxes

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#4411]
**Description**
On one of my ships, I have a shuttle that has its battery array (Specifically, shuttle batteries) directly wired to the docking port's power pin in order to recharge. I went to test the ship in game, and found that the shuttle batteries were not charging. I disconnected each battery's output pin just to be sure it wasn't just a net loss of charge, yet the charge% was just static.
I then instead replaced the power connection with a port > relay > battery, something I know works for certain. I went into test mode and it worked fine. Batteries were recharging.
Something about docking ports is preventing power going through unless there's a form of junction at the other end. I've only ever tested this with batteries, I haven't tried this with, say, an engine or a pump

**Version**
v0.10.6.2

**Comment by ignis05** [comment]
When i tested it a while ago, its not only for batteries, it appears that the docking port can't power any devices directly, it needs a relay or a junction box in-between.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3a4cccf82d73eeedd7604f1ec9a9d2fae499b263

**Comment by Xeavas** [comment]
[0.1200.0.0] - Unable to replicate by connecting docking port directly to battery. 👍 

![dockingpower](https://user-images.githubusercontent.com/72674994/101947499-88202380-3c2b-11eb-918b-60980f56733c.jpg)

**Comment by Rokvach** [comment]
Closing
