### ISSUE TITLE
Backwards Velocity in Combat (sub vs sub / pvp) missions

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4415]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The nav display and engines show "negative" velocity and force for the separatists (right side spawn) team, despite their sub being Y-mirrored and thus moving "fowards".

**Steps To Reproduce**
Spawn on the separatists team.

**Version**
0.10.6.2

**Additional information**
This non-flip affects submarines that have asymmetric thrust (e.g., an auxiliary engine or systems that are locked to "forward thrust" or to "reverse thrust")

**Comment by ekqvist** [comment]
Made velocity show as positive for "flipped" subs when they move forward in Regalis11/Barotrauma-development@e0565cc.

> This non-flip affects submarines that have asymmetric thrust (e.g., an auxiliary engine or systems that are locked to "forward thrust" or to "reverse thrust")

@Tsunder Do you mean that there are subs for which the velocity shows as negative when moving forward, even in regular play when they are not "flipped"? Can you provide some example subs for me to test?

**Comment by Tsunder** [comment]
> @Tsunder Do you mean that there are subs for which the velocity shows as negative when moving forward, even in regular play when they are not "flipped"? Can you provide some example subs for me to test?

No effect for regular play, only for the flipped side in sub vs sub.

Some subs that have a set engine set_force for [reversing](https://steamcommunity.com/sharedfiles/filedetails/?id=2257154367) and [forwards speed](https://steamcommunity.com/sharedfiles/filedetails/?id=2244316895).

**Comment by ekqvist** [comment]
Thanks, I discussed this briefly with another developer as well, and I'll need to make some further changes to account for some other things as well. Thanks for the links, I'll check them out!

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@f9d03d3. I recommend testing the issue with the subs linked above.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
