### ISSUE TITLE
Dedicated Server Mass Ban when one person is banned

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4417]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever I ban someone on a dedicated server running linux, everyone gets banned mass wave, including the person who intiated the ban

**Steps To Reproduce**
Set up a linux dedicated server
Ban a person

**Version**
Stable, Linux
**Additional information**
Sadly, it doesn't seem that my server saved the logs
Though I do have this partial screenshot of the console
![image](https://user-images.githubusercontent.com/59514198/100672339-cd8d4880-332f-11eb-8e92-7763485d051b.png)

**Comment by Solbusaur** [comment]
I encountered this earlier with the votekick system too. We votekicked some griefer mechanic, and the whole dedicated server got wiped of players. I didn't attempt to rejoin afterwards, however. Not sure if I was actually autobanned or just kicked, 'disguised' as a ban

**Comment by EricPfau** [comment]
https://github.com/Regalis11/Barotrauma/issues/4163

**Comment by juanjp600** [comment]
To clarify, this fix is not yet available on the main branch on Steam. We've developed a fix that will be available in the next update (or if you don't want to wait for that, it's currently available on Unstable)

**Comment by Neko-LoverDisc** [comment]
Is there any way to stop people from joining in other ways? I've had griefer after griefer show up, and any form of permanent removal just disables the server. They keep rejoining because I can't ban them

**Comment by Neko-LoverDisc** [comment]
Or if not, is it possible to install unstable via steamcmd; if so, how?
