### ISSUE TITLE
Wrecked sub ID card claiming task/mission or just nice little price in marks for sell.

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#4419]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I suggest to add some kind of reward for finding dead crew IDs inside wrecked subs, because they are akin dogtags in Europe undersea world. A special task would be nice, but temporarily you can add some actual price to wreck ID cards.

**Comment by ezjamsen** [comment]
Nice idea. Let's see about creating some new mission objectives with this in mind.

**Comment by linax3-genuine** [comment]
i retrieve the bodies, too. i think someone cares for them(as it says on duffle bags). this should be true for non-mission wrecks, too. missions should pay rep+marks from the related factions. for non-mission - just reputation.
probably a bodybag item would be needed, as the game does not like to keep bodies around.

**Comment by Regalis11** [comment]
Duplicate of https://github.com/regalis11/barotrauma/issues/3451
