### ISSUE TITLE
Server crash when security chases thief onto ship

### ISSUE THREAD

**Issue by beenoc** [Regalis11/Barotrauma#4420]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When on a station, if a player steals an item, is caught, and is being chased by security, the security may follow them onto the ship. If the security crosses the threshold of the ship (in this case stock Kastrull), the game server crashes. In at least one case the host's game crashed to desktop as well (other players simply got the usual "Server has crashed" message.)

**Steps To Reproduce**
Steal any item from a station, get caught, and have a security guard chase you back to the ship. The server should crash when the guard enters the ship.

**Version**
Windows 0.10.6.2 (current main version as of this bug report.)

**Additional information**
No other mods were enabled, and the ship was completely stock Kastrull. Other ships haven't been tested,

**Comment by Regalis11** [comment]
Duplicate of Regalis11/Barotrauma#4125
