### ISSUE TITLE
Mod Load Orders Reverse

### ISSUE THREAD

**Issue by Kerrupt** [Regalis11/Barotrauma#4424]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When joining a modded host, no matter how the load order is manipulated, be it manually or by disabling all your own mods to hotload the hosts, your mods will be loaded in the exact reverse order of the host. Prevents you from crafting most if not all of the items in any mods.
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Host enable some mods, client either enable or don't. Client joins host, load order will be a perfect mirror opposite the host. 
i.e. 
HOST: EK Armory, XanMonsters, XanMonsters2
CLIENT: XanMonsters2, XanMonsters, EK Armory
**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Current as of 1 December 2020. (v0.10.6.2 (Windows Release, Branch Release, revision d0702df35e)).
**Additional information**
Seems to happen reliably no matter the list of mods or quantity of mods. (Excluding one, of course, as there is no way that a load order including only one mod can load backwards.)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4d7bcaa3607d9f14c090350bb37ce4d668b3b51d, will be available in the next update.

**Comment by Rokvach** [comment]
This issue has been tested already, working correctly. Closing.
