### ISSUE TITLE
Linking the entity to another entity failed. Could not find an entity

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4425]
Branch: dev
Build: Debug
Commit: https://github.com/Regalis11/Barotrauma-development/commit/0db39139889692124ad3404ae931e9ad5655ba32

I was testing shuttles by leaving a outpost, undocking the shuttle and then returning to the outpost, while back at the outpost I docked the shuttle back in to the main sub and left the outpost again and received these errors

Repro steps:
1. Start a multiplayer campaign with Remora selected
2. Leave the outpost
3. Undock Remora drone
4. Enter outpost
5. Dock Remora drone
6. Leave the outpost
7. Error should be shown now

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d5672bf9-9581-45dd-9b5b-64760d0633de)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9921c5f96f4382f8ad5b1359f5ef702e9077029f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
