### ISSUE TITLE
[Suggestion] Lower the Medical Skill Requirement For Treatments to be Accurate

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4426]
One of the things that's been bothering me about playing medical is that the suggested treatments is almost never accurate. Sure, I have things memorized in my head what treats what, but with the medical skill requirement that high, only players that survive that long (which tend to be players that know what they're doing) could rely on that. I think lowering the skill requirement so that newer players have a better chance to give the right treatment would be nice. After all, what's the point on using the suggested treatments at all if its inaccurate without a high skill level?

**Comment by Regalis11** [comment]
We're planning on overhauling the medical system in the near future (ticket in private repo https://github.com/Regalis11/Barotrauma-development/issues/2218), and will most likely get rid of the suggested treatments entirely.
