### ISSUE TITLE
Engine Propeller hitbox not matching the size in-game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4428]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you change the scale of Engines, the propeller (red square) hitbox remains at default size and is actually bigger in-game than it looks in editor. Prevents scaling down engines to avoid taking damage fromy propellers

**Steps To Reproduce**
1. Place an engine in editor
2. Scale it up/down considerably
3. Watch the red square
4. Swim around it 
5. Get hit from a distance

[https://cdn.discordapp.com/attachments/668819422919524352/784052560100589578/Desktop_2020.12.03_-_14.42.58.04.DVR.mp4](url)

**Version**
 v0.10.6.2 Windows 10

**Additional information**
Mostly an issue for _downsized_ engines and small shuttles/drones, prevents safely approaching them
_Alternatively_, give us the option to disable propeller damage

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0b6a13804fa6aa74060ff6976b32930659d4f42

**Comment by Xeavas** [comment]
[0.1200.0.0] - Tested using setup below, no issues. 👍 
![enginehitboxtest](https://user-images.githubusercontent.com/72674994/101987792-316d2500-3cd1-11eb-82a6-fc87418fc27d.jpg)

**Comment by Rokvach** [comment]
Closing
