### ISSUE TITLE
Scaled docking ports are misaligned

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#4429]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The height of hulls added between docking ports does not depend on the docking port size. As a result, scaled down docking ports have some distance between them when docked:

![docking_issue](https://user-images.githubusercontent.com/50582661/101026442-31ee1900-3577-11eb-877b-9d3878a42e32.png)

**Steps To Reproduce**
Add a scaled docking port to a submarine and a shuttle. Docking them results in the space as seen in the image.

**Version**
Barotrauma v0.11.0.8 (ReleaseWindows, branch release, revision b33722ad5b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e76d6dbaf0c717a3e06ad64585abcb96cb20b57b

**Comment by Xeavas** [comment]
[0.1200.0.0] - Unable to replicate, left `0.3` and right `0.7` scales. 👍 

![dockingspace](https://user-images.githubusercontent.com/72674994/101943559-45a81800-3c26-11eb-9f03-92264608ae06.jpg)

**Comment by Rokvach** [comment]
Closing
