### ISSUE TITLE
Bug with map generation

### ISSUE THREAD

**Issue by Nevol2110** [Regalis11/Barotrauma#443]
![image](https://user-images.githubusercontent.com/33912761/41194174-22c3ddde-6c20-11e8-93c1-162278681ee9.png)
1. The ruins were created near the beginning.
2. Autopilot goes through the ruins.

**Comment by Regalis11** [comment]
You don't happen to still have the map seed?

**Comment by CryIz** [comment]
Sorry, forgot. Seed: pjerdgXP

**Comment by Regalis11** [comment]
Should be fixed in the dev branch
