### ISSUE TITLE
Game starts in tiny window on first launch

### ISSUE THREAD

**Issue by folknor** [Regalis11/Barotrauma#4431]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I just bought and installed the game for the first time. On first launch (and all 3 - thus far - subsequent launches) it started in a tiny window that I can't resize, where I am unable to interact with the options to change the resolution.

**Version**
Linux X11 using Gnome Shell, latest Steam version as of bug report time.

**Additional information**
I have two monitors connected; one 1920x1200 and one 3840x2160. The game launches on the main monitor, which is the 4k one.

Possibly related to bug #1956 but there's a good chance it isn't - thus I filed this ticket instead.

In the below image you can see the game taking up approximately 1/5th of the screen, in the center. I've blacked out personal information in the screenshot.
![resolutionwtf](https://user-images.githubusercontent.com/233791/101215784-511fa000-3676-11eb-96b7-6a27b43aebd8.jpg)

**Comment by folknor** [comment]
I've tried adding `-fullscreen` to the launch options in Steam to no effect.

**Comment by hubismal** [comment]
lol this happened to me too during an update iirc. for now you can change it in Barotrauma/config_player.xml

**Comment by folknor** [comment]
I googled the config stuff and found out about `/home/foo/.local/share/Daedalic Entertainment GmbH/Barotrauma`, which is empty because I've not managed to actually start the campaign or anything.

I opened `config_player.xml` in the Barotrauma game directory for the first time ever now, and it contains this section:
```xml
  <graphicsmode
    width="3840"
    height="2160"
    vsync="true"
    compresstextures="true"
    framelimit="200"
    displaymode="BorderlessWindowed" />
```

I tried changing `BorderlessWindowed` to `Fullscreen` (which is just a guess, I have no idea what kind of strings I can put there), but that didn't make it better. What changed compared to `BorderlessWindowed` is:
1. The window now has window manager decorations
1. Keyboard and mouse input was captured globally

Otherwise it was identical in size to the screenshot.

**Comment by hubismal** [comment]
I meant home/foo/.steam/steam/steamapps/common/Barotrauma/config_player.xml. that is what i changed anyway

**Comment by folknor** [comment]
I think you misread/misunderstood my comment

**Comment by Regalis11** [comment]
I'm afraid I'm not sure what could be causing this, haven't heard of this occurring before. :/ Something that could be worth a try though is switching to windowed mode (displaymode="Windowed") or trying a smaller resolution (for example 2560x1440).

**Comment by 3e849f2e5c** [comment]
I've noticed it happening on my Linux setup when using Borderless but I use a tiling window manager and those disrespect the window rules. Seems that the window appears in 800x480 resolution which is the default size MonoGame sets the SDL window to (SDLGameWindow.cs:110 and GraphicsDeviceManager.cs:38). Probably happens on some window managers that handle borderless windows a bit differently, maybe they want you to explicitly define the window size when using fullscreen windows?

**Comment by 3e849f2e5c** [comment]
Some quick debugging shows that this is probably caused because SDL window ignores calls to SetWindowSize when in fullscreen. What happens is the game spawns in the default window that is 800x480 in size then after all initialization is done it applies the graphics settings and if fullscreen/borderless is one of those options then that gets applied first causing the calls to set the size to be ignored. So the window will be fullscreen but the window still says that it is only 800x480. The issue might be because some window managers actually use that size value for fullscreen programs.

**Comment by folknor** [comment]
I use the standard Gnome-Shell window manager, Mutter. This is the default window manager on Fedora, Ubuntu, and other major distributions of Linux.

If Mutter has this issue, and it happens on a new game install on any resolution above 800x480, then I can't be the only one who has seen this.

I tested setting `displaymode="Windowed"` in config_player.xml and that makes it work at full 4k resolution, in windowed mode.

**Comment by Jasontti** [comment]
Was not able to reproduce with fresh steam install (Debian 11 and Gnome 3.38.5)
