### ISSUE TITLE
I can't connect to any online 

### ISSUE THREAD

**Issue by Tuskact6** [Regalis11/Barotrauma#4433]
I haven't been able to connect to any multiplayer games over the past few months. I really love this game and want to play it again. I get an error in the console that goes along the lines of "X is not a multiple of four". Windows. Sometimes I can connect to servers but once I get to the loading screen the game freezes and boots me out of the server

**Comment by Regalis11** [comment]
Do you have any mods installed or have you downloaded a large number of submarines from servers (these are located in "Submarines/Downloaded/" inside the game folder)? There's a bug in the current version that may cause joining to servers take an excessive amount of time when you have tons of downloaded submarines (https://github.com/Regalis11/Barotrauma/issues/4432), which often leads to the connection timing out before you manage to join. 

Also, could you send a screenshot of the error messages you're getting? "... is not a multiple of four" is just a warning and shouldn't cause any issues, but if there's any red text in the console in addition to that warning, sending us that error message would be very helpful.

Sorry for the inconvenience!
