### ISSUE TITLE
[Feature Request] Expanding the functionality of the Wi-Fi module

### ISSUE THREAD

**Issue by NicolaruS** [Regalis11/Barotrauma#4434]
The Wi-Fi module, having received a constant signal from the Wi-Fi transmitting module, saves it even if it no longer falls within the range of the Wi-Fi transmitting module. Is this a bug or a feature?
Is it possible to make an option in which the range characteristic of the Wi-Fi module affected not only the range of signal transmission, but also the radius of signal reception?

**Comment by Regalis11** [comment]
> The Wi-Fi module, having received a constant signal from the Wi-Fi transmitting module, saves it even if it no longer falls within the range of the Wi-Fi transmitting module. Is this a bug or a feature?

That sounds like a bug: if the receiver stops receiving a signal, it should no longer output that signal. Although, I'm not sure what exactly you mean by "saves it" - do you mean the receiver still keeps outputting the signal? And are you sure it does still output it? For example, if you used the wifi component to set the text on a display, the text will stay on that display even if the wifi component stops outputting anything.

> Is it possible to make an option in which the range characteristic of the Wi-Fi module affected not only the range of signal transmission, but also the radius of signal reception?

Technically yes, although in my opinion it would be a little counterintuitive to have the range of the _receiver_ effect how far it can receive signals from. Also, I'm curious, what do you need this functionality for?

**Comment by NicolaruS** [comment]
Sorry, the Wi-Fi module seems to be working correctly, I did not set the experiment correctly. Repeated experiment showed this.    
![6545334242](https://user-images.githubusercontent.com/58271380/101282562-fce7fd80-37e6-11eb-96e1-11c335c8cdfc.png) 
![6545334242 — копия (3)](https://user-images.githubusercontent.com/58271380/101282574-0a04ec80-37e7-11eb-930c-f826ab34afcc.png) 
![6545334242 — копия (2)](https://user-images.githubusercontent.com/58271380/101282579-0ffacd80-37e7-11eb-8c41-be0706bba303.png)
![6545334242 — копия](https://user-images.githubusercontent.com/58271380/101282585-16894500-37e7-11eb-8e0c-8bce05a68043.png)  
    
> I'm curious, what do you need this functionality for
 
This will help further reduce the amount of detail in my custom sonar (but not yet popular).
The existing sonar is divided into 3 parts: a transmitter that sends a signal indicating the range to the target; a reflector that receives a signal and sets itself the set_range parameter equal to it; a receiver that receives a signal from a reflector and allows you to determine the range to the target.
If the reception range of the Wi-Fi module was equal to the transmission range, then I would be able to assign most of the reflector's functions to the transmitter. 

https://steamcommunity.com/sharedfiles/filedetails/?id=2114129689

https://steamcommunity.com/sharedfiles/filedetails/?id=2114051397
