### ISSUE TITLE
Profanity Filter Extremely Ineffective

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4441]
[Bug]
![image](https://user-images.githubusercontent.com/47284081/101291005-9ae6c280-37fd-11eb-9df8-0a9c34c4ad56.png)
Above picture is the same with filter toggled on and off
The profanity filter is largely ineffective because of a few simple things in its string detection:

- It's case sensitive, so it will only censor words as exactly written in forbiddenwords.xml 
- It ignores words that aren't separated by spaces which is noble for words like "assimilate" containing ass, but i can't think of any good words that contain "fuck" in them. It would probably be good to have the forbiddenwords.xml contain spaces around words that are part of other words (eg ass would be included as " ass " so that brass or assume aren't picked up) and just have the filter itself not care about spaces
- forbiddenwords.xml was written by someone with a limited imagination for cursing. it might just be good to look up a standard curseword list online and use that. notably a lot of british curses and some slurs are missing.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d59611af5db929abde5ce9deb41204f8e95d48d6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
