### ISSUE TITLE
Berilia Waypoints

### ISSUE THREAD

**Issue by HypnoPants** [Regalis11/Barotrauma#4442]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

Basically, my mechanics were running back and forth frantically around the reactor, because they couldn't get to the small pump below. Turns out, they have no waypoints to it.
![image](https://user-images.githubusercontent.com/22647132/101340814-790d3000-383d-11eb-9030-5412ac519f54.png)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@9b77795

**Comment by HypnoPants** [comment]
> Fixed in [Regalis11/Barotrauma-development@9b77795](https://github.com/Regalis11/Barotrauma-development/commit/9b77795)

I get a 404 error when I click on your link.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
