### ISSUE TITLE
VELOCITY_IN pin does nothing on Navigation Terminal

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4443]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Navigation Terminals have a VELOCITY_IN pin. No matter what signal you send, nothing happens as it doesn't seem to do anything. It doesn't change either X or Y velocity, nor the vector on the terminal. Confirmed by Hexcode

**Steps To Reproduce**
1. Wire a signal into VELOCITY_IN
2. Nothing happens?

**Version**
 Barotrauma v0.11.0.8 Windows 10

**Additional information**
Requesting a VELOCITY_RESET pin to reset velocity/vector to 0 on the navigation terminal. It's currently impossible without either:
-Switching to manual and back to automatic again (for autopilot)
-Awkwardly aiming at the "zero" manually (for manual)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0bb1e59c6dedd415d970c04db652701e25dfb16c

**Comment by Xeavas** [comment]
[0.1200.0.0] - No Issues, setting `100,100` will yield an effect 👍

**Comment by Rokvach** [comment]
Closing

**Comment by ubertpendragon** [comment]
@Regalis11 Reviving this ticket a bit because VELOCITY_IN doesn't actually replace the terminal "vector" with the last input value, it only overrides the velocity X,Y output while keeping the on-screen vector

In practice this means that as soon as the signal stops, it switches back to the previous vector on the terminal screen
if you were in auto-pilot, it'll use the position from back when you started using VELOCITY_IN
The moment you let go of the signal, the sub moves on its own, which is an issue if you're using a secondary navigation method (periscope) as you'll have to manually reset the terminal every time

Ideally it should control the vector itself, and not just the output
