### ISSUE TITLE
Crash when hovering cursor over friends

### ISSUE THREAD

**Issue by Aketits** [Regalis11/Barotrauma#4444]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Barotrauma goes "no respond" status whenever i hover mouse cursor over the friend on top right of the server browser. All i can do is to quit, and avoid touching that place at all costs.

**Steps To Reproduce**
1.Boot Barotrauma.
2. Click server browser.
3. hover mouse cursor over one of my friends.
4. whole Barotrauma freezes.

I used this feature a lot to decide which server i would go. now that i cannot. it used to work when i had 420ish friends on the exact same version. now it doesn't, maybe because now i got 434 friends.

**Version**
0.10.6.2, the current STABLE version as of now. I am running Windows10.

**Additional information**
Outside of the theory i proposed above, i don't have too much guesses.
---------------------
Just noticed that, it works as long as said friends are NOT running a game. When they are, however, does crash.

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce this, but I don't have anywhere near as many friends on Steam however.

**Comment by KimmoKari** [comment]
@Rokvach can you ask if someone from the testing community have a lot of friends and could repro this?

**Comment by Regalis11** [comment]
I think this should still be tested, could be done by adding some fake dummy users to the friends in the code

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
