### ISSUE TITLE
Sub Editor: Grid is offset from pre-update grid so items do not snap together. 

### ISSUE THREAD

**Issue by GorillaOne** [Regalis11/Barotrauma#4446]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the sub editor, all items are now snapping +8 pixels on the y axis from where they did pre-update. 

**Steps To Reproduce**
1) In the sub editor, load a sub that was saved prior to the Uncharted Depths update.  
2) Place a new item. 
3) Move the item and note how the grid it is snapping to does not align with the grid pre-existing items have been snapped to. 

Expected Result: Items should snap to the same grid and align with pre-existing items. 
Actual Result: Items snap on an offset from the pre-existing grid. 

**Version**
Windows 10  Build 19041
Exe version: 0.11.0.9
BuildID Listed on Steam: 5938401

**Additional information**
Pretty straight forward to find. Feel free to contact me if you need additional information or help.

**Comment by iank144** [comment]
oh so I'm not crazy. thought i did something wrong lol
