### ISSUE TITLE
"Genocide" achievement unobtainable

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4449]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've been trying to obtain the "genocide" achievement (kill 100 humans) for quite some time without any luck, I've tried in both single and multiplayer and killed what felt like hundreds of humans before I finally gave up. Today I've decided to take a look at what steam achievement manager has to say about that (since achievement is "hidden" there's no other way to see the progress for it) and it appears that all those human kills were counted correctly, its just the achievement that didn't get unlocked.
![genocide_broke](https://user-images.githubusercontent.com/48099798/101667244-636f5480-3a4f-11eb-809e-5b26985ac238.png)

**Comment by Regalis11** [comment]
Should be fixed now

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
