### ISSUE TITLE
UI Layering issue (Nav terminal)

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4450]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
linked status monitor UI shows on top of navigation area, particularly the labels, obstructing reading, especially the distance to target

![image](https://user-images.githubusercontent.com/5103517/101686609-49297c80-3a37-11eb-8f86-468cbdb60c52.png)

**Steps To Reproduce**
open a sonar monitor with a linked status monitor

**Version**
0.11.0.9

**Additional information**
only shows when clicking the sonar/nav. when opening a status monitor with linked sonar display, layer shows up "correctly" (nav area shows up in foreground)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f15e88ab4aa528319c3f0b656bdb9259cdfd1788

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
