### ISSUE TITLE
Sub Editor - Trying to save this shuttle without preview image gives error

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4452]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Dandelion Command.zip](https://github.com/Regalis11/Barotrauma/files/5669091/Dandelion.Command.zip)
Trying to save this shuttle without preview image gives error:
![Capture](https://user-images.githubusercontent.com/5086682/101696202-bf33e080-3a43-11eb-968b-d25118322eba.PNG)

**Steps To Reproduce**
1. Load the shuttle in the Zip.
2. Save file without generating preview image.

**Version**
0.11.0.9

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@6309c72. I don't think there was a ticket about this issue.

**Comment by Xeavas** [comment]
[0.1200.0.0] - Can't replicated with provided file and steps. 👍

**Comment by Rokvach** [comment]
Closing
