### ISSUE TITLE
Placing motion detector close to subs outer hull/hatch crashes game

### ISSUE THREAD

**Issue by SirGentlemanIV** [Regalis11/Barotrauma#4455]
Game crashes when you try placing a motion detector(screenshot attached of exact moment of crash)

Steps To Reproduce:
-Start editor
-Load standard Orca submarine
-Place wrench and motion detector next to where you spawn
-Click test button to test submarine
-Use wrench to detatch detector and bring it into the airlock
**crash**

Version: 0.11.0.9 Linux
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/5669905/crashreport.7.log)
![crash](https://user-images.githubusercontent.com/75766125/101713307-b240dc80-3a97-11eb-9799-cf28ccabe692.png)

**Comment by SirGentlemanIV** [comment]
After further testing it seems like the problem only exist when testing submarines in the editor and it can be reproduced with placeable wiring objects in general. This problems doesn't seem to exist in campaign or sandbox mode.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@ebc2f2d.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
