### ISSUE TITLE
Changing Cost of Submarine is Extremely Annoying

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#4456]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you want to change the cost of a submarine, the box enforces the minimum price at all times. Deleting characters can cause a value to be put into the box, and deleting digits sometimes has no effect. As a result, to set the price you want you typically have to type the whole number in before or after the current one in the box, then delete the old one.

The fix should be easy enough to do by only making the box enforce the value when focus is lost etc.

**Steps To Reproduce**
1. Open a submarine in the editor
2. Attempt to change its price to a smaller value

**Version**
v0.11.0.9

**Comment by Veritius** [comment]
This, please. It's infuriating and I came here specifically to ~~complain~~ put down an issue about this.

**Comment by Veritius** [comment]
Notably it also has a maximum (at least, for me) and it's almost impossible to sensibly write a number without all sorts of irritation.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cbcd69581ae1c0b1ea5287b80247c6923d74aec9

**Comment by Xeavas** [comment]
[0.1200.0.0] - No issues, thanks for the addition 👍

**Comment by Rokvach** [comment]
Closing
