### ISSUE TITLE
Sub editor crash with shuttles

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4458]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sub editor crashes when "select matching items" is clicked while ctrl (and shift?) is held and at least 1 additional shuttle is selected

**Steps To Reproduce**
1. select multiple ojbects, including at least 1 shuttle
2. right click new object
3. hold ctrl while clicking "select matching object"

**Version**
0.11.0.9

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/13766b299e038f0a844648967be2c9e0ef666267

**Comment by Xeavas** [comment]
[0.1200.0.0] - Unable to replicate, it no longer crashes if you click `select matching items` on shuttle while said shuttle is selected (Used this method to replicate in 0.11.0.9 to get a better understanding with the issue. 👍

**Comment by Rokvach** [comment]
Closing
