### ISSUE TITLE
Shut Down Reactor Command is broken?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4463]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm trying to tell my engineer bot to shut down the reactor on this save file, but he will do everything he can to keep the power running.

[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5673858/Multiplayer.zip)

**Version**
0.11.0.9

**Comment by itchyOwl** [comment]
An error in the AI logic fixed in Regalis11/Barotrauma-development@eaed2cb, but there seems to be a networking related issue too.

**Comment by Regalis11** [comment]
Fixed the networking issue in https://github.com/Regalis11/Barotrauma-development/commit/4da31c2b587a537df36a40eefa190bad9de9befb

**Comment by itchyOwl** [comment]
Tested, seems to work as it should.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
