### ISSUE TITLE
Can't play on servers

### ISSUE THREAD

**Issue by David2583** [Regalis11/Barotrauma#4464]
When I connect to a server there is no server name, server description, submarines list, difficulty level, bot count in server lobby. Also I can't join the round

This bug happened on version 0.10.0.6 and version 0.11.0.9 on Windows 10 OS

**Comment by Regalis11** [comment]
Thank you for the report! We've heard of this happening before (may be related to https://github.com/Regalis11/Barotrauma/issues/4137), but so far haven't found a way to reproduce the issue. Does it happen consistently every time you try to join any server? Do you have any mods installed? Do you have a large number of submarines in the "Submarines/Downloaded/" folder (if so, this could be related to https://github.com/Regalis11/Barotrauma/issues/4432 and deleting some of those subs might fix the problem)?

**Comment by Regalis11** [comment]
No known steps to repro, closing
