### ISSUE TITLE
Small pumps with 0 V minimum voltage show animation but don't pump

### ISSUE THREAD

**Issue by Zangdorx** [Regalis11/Barotrauma#4468]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When setting the minimum voltage of a small pump to 0 V, it does the pumping animation (water splashes), but it doesn't pump.

**Steps To Reproduce**
- Open the submarine editor
- Place a floor and a hull, and a light component that is set to ON
- Place a small pump inside that hull
- Set it's minimum voltage to zero
- Start testing mode
- Power on the pump and set the speed to 100% (max fill)
It now makes water splashes, but water doesn't fill up.

**Version**
Version: 0.11.0.9 rev c60afcc03b
OS: Windows

**Additional information**
The animation should only show if the pump is going to work. Else, it makes you think that it will work. If you're testing and you want a pump that does not require power, and set the minimum voltage to zero instead of the power consumption thinking that it will work, then the erroneous activation makes you wonder why it doesn't. Without the animation, you would try to figure it out within the pump itself and probably find the problem, instead of redrawing your hulls a couple of times.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/120412b17cf02ff723f9fa853e2f46fceda5c1b2

**Comment by Xeavas** [comment]
[0.1200.0.0] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
