### ISSUE TITLE
Beacon Mission - Unable to complete with rewire off

### ISSUE THREAD

**Issue by Pewkek** [Regalis11/Barotrauma#4469]
**Description**
When playing with rewire off (globally), you can't complete a Beacon mission, if the game requires you to provide power and place/altering wiring.

**Steps To Reproduce**
1. Start a campaign
2. Turn off rewiring
3. Start a beacon mission
4. When you are required to provide power to the corresponding junction box, you can't, because the rewiring is off.

**Version**
OS: Windows 10, ver. 2004
Game version: v0.11.0.9

**Additional information**
The rewiring setting should not affect mission-critical assets, such as junction boxes inside beacon stations.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d7eb73979194241a848be51612af08ed2aebace6
