### ISSUE TITLE
Gamecrash after activating main powerline of my shuttle

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#4470]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So, I have build in a main powerline in my shuttle. It is deactivated by default to avoid the shuttle draining its batteries 24/7 when not in use. However, the last two times I tried to activate it, the game crashed.

**Steps To Reproduce**
I am playing a singleplayer campaign game. The powerline is wired like this:
Batteries output to relays input
Relays toggle_state to a button on the navigation terminal
Relays output to junction box
Junction box distributes power to devices and other JBs
The shuttle was docked to my main sub, and I was in the middle of a mission.

**Version**
Windows 10
![grafik](https://user-images.githubusercontent.com/63376072/101909857-689ee180-3bbe-11eb-8867-fd5a10681dc9.png)

**Additional information**
Crashreports
[crashreport (34).log](https://github.com/Regalis11/Barotrauma/files/5679409/crashreport.34.log)
[crashreport (35).log](https://github.com/Regalis11/Barotrauma/files/5679410/crashreport.35.log)
[crashreport (31).log](https://github.com/Regalis11/Barotrauma/files/5679411/crashreport.31.log)
[crashreport (32).log](https://github.com/Regalis11/Barotrauma/files/5679412/crashreport.32.log)
[crashreport (33).log](https://github.com/Regalis11/Barotrauma/files/5679413/crashreport.33.log)

**Comment by Melolatius** [comment]
So, I completed a mission and went to another "outpost" (it was a natural formation). Now this is fixed and I can activate my powerline.

**Comment by Jlobblet** [comment]
Tested with this save from someone on the Discord. [The_REAL_maiden_voyage_SP.zip](https://github.com/Regalis11/Barotrauma/files/5683343/The_REAL_maiden_voyage_SP.zip). When undocking the shuttle, the circuitry powers up the pumps. On stable, [crashreport.log](https://github.com/Regalis11/Barotrauma/files/5683350/crashreport.8.log) is produced. No crash on unstable - I believe the fix is working correctly.

**Comment by Rokvach** [comment]
Closing
