### ISSUE TITLE
[Unstable] Can't select a sub when campaign setup is selected

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4471]
Will have to leave campaign setup in order to be able to select a submarine to use on the campaign

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/98c0bb3ed523d3434ff2fcf73c584b50faf656fc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
