### ISSUE TITLE
[0.1200.0.0] You can place multiple oxygen tanks in oxygen generator

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4478]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can place multiple oxygen tanks in oxygen generator. It also causes this:
![Capture](https://user-images.githubusercontent.com/5086682/101949286-5d00ea00-3bc1-11eb-8da3-d155d68cdb98.PNG)

**Version**
0.1200.0.0

**Comment by Regalis11** [comment]
Couldn't reproduce. Is there some specific way I need to place the tanks in the generator?

**Comment by Kaillera** [comment]
I think it's probably the outpost oxygen generator then. It can hold stacks.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2919c92

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
