### ISSUE TITLE
(dev) Contained items shown in health menu

### ISSUE THREAD

**Issue by JJRcop** [Regalis11/Barotrauma#448]
When you have a chemical inside a syringe, the chemical shows up in the health menu. You aren't able to use it directly, since it's inside the syringe, you must use the syringe itself. This is expected behavior, but the chemical should not show up in the health menu, only the syringe.

I haven't tested chemicals inside boxes yet, or other containables, so far only syringes

Tested on: 564aa963cc8ae951b6b0f059ef9074e8bafecaab

**Comment by Regalis11** [comment]
Items are used directly from the inventory now, closing this.
