### ISSUE TITLE
[0.1200.0.0] The merchant can buy your equipped items

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4481]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was selling things right at the start of a new campaign and I accidently sold my ID card and headset that I was equipping. Not sure if any other equipped items will suffer the same problem.

**Version**
0.1200.0.0

**Comment by ekqvist** [comment]
This should be fixed in Regalis11/Barotrauma-development@3e6dc0a. The same commit should also fix #4489 and #4490.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
