### ISSUE TITLE
[0.1200.0.0] Custom Submarines that uses the new Outpost Reactor has Non Player Team Interactable enabled by default

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4482]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The new Non Player Team Interactable option is enabled by default for the new Outpost Reactor, which affects any custom submarines that currently uses it.

**Version**
0.1200.0.0

**Comment by ekqvist** [comment]
This was definitely an oversight on my part.

I guess the option should be changed to always be disabled. Instead, the option should probably be enabled for the reactors in the vanilla engineering modules.

**Comment by ekqvist** [comment]
Should be addressed in Regalis11/Barotrauma-development@4a45654. The property should already be set to true for the reactors in the engineering modules so this change shouldn't affect them. I am not sure if this change is enough or if we should also set the property to true for any reactors found in outposts when we generate them.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
