### ISSUE TITLE
[0.1200.0.0] Wrenches and Screwdrivers are stackable

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4484]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wrenches and Screwdrivers are stackable.

**Version**
0.1200.0.0

**Comment by Rokvach** [comment]
I don't see why this is an issue

**Comment by Regalis11** [comment]
Yes, most small items are now stackable

**Comment by Jlobblet** [comment]
I suppose the idea of holding multiple screwdrivers at once to repair something doesn't make that much sense, but a character could just be holding one out of several they have.
