### ISSUE TITLE
Campaign - Docked shuttle's status monitor doesn't display the status of the main submarine it's docked to at the start of each level

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4485]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
In Campaign, docked shuttle's status monitor doesn't display the status of the main submarine it's docked to at the start of each level. We need to constantly redock the shuttle for it to display both.

**Version**
~0.1200.0.0

**Additional information**
My new submarine [Dandelion](https://steamcommunity.com/sharedfiles/filedetails/?id=2312353651) can showcase this problem easily.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ab64026626b1f522ed24287e76e027ed11f066b

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
