### ISSUE TITLE
[0.1200.0.0] Unequipping an item that has a sub slot on your hotbar moves the item to the most left unoccupied slot on your hotbar

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4486]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unequipping an item that has a sub slot on your hotbar moves the item to the most left unoccupied slot on your hotbar.

![Gif](https://cdn.discordapp.com/attachments/668819422919524352/787057554991349800/Giffy.gif)

**Version**
0.1200.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6b771a99645e6ea64d7ef3d85de332dcf2810e7

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
