### ISSUE TITLE
[0.1200.0.0] When opening a cabinet or grabbing a corpse/ragdoll, trying to equip items via hotkey puts the item into them instead of equipping the item

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4487]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
When opening a cabinet or grabbing a corpse/ragdoll, trying to equip items via hotkey puts the item into them instead of equipping the item.

**Version**
0.1200.0.0

**Additional information**
It just feels awkward. When holding a corpse it's even more awkward.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c12d174009c2a6c54eab2d6707512f68f6373014

**Comment by Xeavas** [comment]
[0.1200.0.1] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing.
