### ISSUE TITLE
Invisible wall blocking players from going through the docking hatch from a shuttle

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#4488]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Today we were docking the default Selkie shuttle to the default Dugong. We did this TWO times with the same results. We were blocked by an invisible wall placed where Dugong's top hatch was, so we couldn't go through the hatch (2 different players) even though the hatch appeared open. We tried being ragdolled. When I kept being ragdolled as the shuttle was leaving, I got stuck physically between the closed hatch on the shuttle and on the sub, but I disappeared anyway when the shuttle left.

**Mods:**
Meaningful CPR
Vertical Hatches (this one seems suspicious)
Rucksack 2.0
EK Armory
EK Utilities
AUG Tools
Alto Saxophone
Shipwrecks Extended

**Steps To Reproduce**
Dock a Selkie to a Dugong. Try to enter the submarine.

**Version**
v0.11.0.9 Windows

**Additional information**
I have a video of this incident. If you feel that it'll add to the report, ask me to upload it.

**Comment by ubertpendragon** [comment]
Can confirm: 
https://cdn.discordapp.com/attachments/587647684794515468/788205769228812338/Desktop_2020.12.14_-_20.31.05.05.DVR.mp4

**Comment by Regalis11** [comment]
I'm afraid I wasn't I able to reproduce this. I suppose it takes some special conditions to occur, and just docking Selkie to Dugong doesn't seem to be enough. Let's keep an eye out for this and see if we can figure out a way to get it to happen.

**Comment by Rokvach** [comment]
I remember Juan fixing something which sounded very close to this issue where a invisible collider just didn't let players pass, its quite a rare one but should be fixed in the next update, closing this ticket.
