### ISSUE TITLE
[0.1200.0.0] Storage Container/Toolbelt/Items with Sub Slots can be sold to Merchant even though there's items still in it. All the items inside goes to Narnia

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4489]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Storage Container/Toolbelt/Items with sub slots can be sold to Merchant even though there's items still in it. All the items inside goes to Narnia.

**Version**
0.1200.0.0

**Comment by ekqvist** [comment]
This should be fixed in Regalis11/Barotrauma-development@3e6dc0a. The same commit should also fix #4481 and #4490.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
