### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by FritzGessler** [Regalis11/Barotrauma#449]
Barotrauma has stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Barotrauma.exe
  Problem Signature 02:	0.8.1.2
  Problem Signature 03:	5ae0c526
  Problem Signature 04:	MonoGame.Framework
  Problem Signature 05:	3.6.0.1625
  Problem Signature 06:	58b6e340
  Problem Signature 07:	9f1
  Problem Signature 08:	a4
  Problem Signature 09:	AQRZ5UNGVPAAKLRWFFK35BWUV213BMTN
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	9242
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	5194
  Additional Information 4:	5194524dddc5b28b18423713442b8a9e

**Comment by CryIz** [comment]
Install the .net framework. Try to run the game not in full screen, and in BorderlessWindow.

**Comment by FritzGessler** [comment]
I am using Windows 8.1 and you haven't told me the version of .NET Framework,
Also also, I can't even open the launcher and the game.

**Comment by CryIz** [comment]
Try this. I'm not sure this will help, because I'm using Windows 10.
https://www.microsoft.com/en-us/download/details.aspx?id=56116

**Comment by FritzGessler** [comment]
I am downloading it. While it's downloading, let me tell you what I tried to fix this:

- [X] Run as administrator
- [X] Compatibility Mode

**Comment by FritzGessler** [comment]
Nope. It doesn't work as it says there is a later update installed.

**Comment by CryIz** [comment]
Since you don't even open the launcher, then you clearly have something not installed. You're, like, the first with the crash report on Windows 8.1. Try manually changing the "config.xml".
Find the line " displaymode= "and replace" FullScreen "with"BorderlessWindowed". This is the third line.
![image](https://user-images.githubusercontent.com/33912761/41528901-21c409c4-72f4-11e8-99ce-2dfcbef5fc3e.png)

**Comment by FritzGessler** [comment]
Nope, tried but still not working.

**Comment by CryIz** [comment]
Most likely a problem because of Windows 8.1. The game after some updates, even on Linux has ceased to run normally. You're the only one with an operating system like that.

PS the Problem with Linux I decided. Wait for a response from Regalis or Juanjp600.

**Comment by Regalis11** [comment]
Mono is not required on Windows, but you do need version .NET framework version 4.5 or later. If I understood correctly you have some version of .NET installed? Can you check which one?

**Comment by FritzGessler** [comment]
I'd say my computer is just garbage. I have new components except for a graphics card that is trash.

**Comment by FritzGessler** [comment]
Also, some technician installed this garbage Windows 8.1. I wouldn't have this operating system if he didn't install it.

**Comment by FritzGessler** [comment]
Also, I do not have an idea cause those were pre-installed with the OS.
