### ISSUE TITLE
[0.1200.0.0] Can no longer sell items inside crates/bags you're holding?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4490]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm not sure if this is intentional, but now you have to put the items on your hot bar or in any of the equipment slots to be able to sell them now. Items in crates/bags are no longer shown on the merchant sell tab.

**Version**
0.1200.0.0

**Comment by ekqvist** [comment]
This should be fixed in Regalis11/Barotrauma-development@3e6dc0a. The same commit should also fix #4481 and #4489.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
