### ISSUE TITLE
[0.1200.0.0] Disconnecting wires in the editor crashes the game

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#4491]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deleting any wire by dragging the connection off the connection box crashes the game. 

**Steps To Reproduce**
Place two components in the editor. Make a connection between them. Drag the connection off one of the components.

**Version**
Unstable 0.1200.0.0

**Comment by Working-Joe** [comment]
[crashreport (32).log](https://github.com/Regalis11/Barotrauma/files/5681782/crashreport.32.log)

**Comment by Marutzo** [comment]
Same for me, but dragging it into your inventory does not crash it (workaround for deleting wires by dragging)

**Comment by Working-Joe** [comment]
Very likely related to https://github.com/Regalis11/Barotrauma/issues/4502

**Comment by Regalis11** [comment]
Yep, seems to have been caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/4502. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5559cb0
