### ISSUE TITLE
[Unstable 0.12.0.0] Feedback: Depleting resources should only stack up to 3

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4492]
Depleting resources as in all the fuel rod types, oxygen tanks, welding fuel tanks, batteries should only be able to be stacked up to 3. 

As 3 is plenty to go with and wouldn't overly occupy the inventory slots when partially depleted.

**Comment by Marutzo** [comment]
Agree, 8 is a **bit** much!

**Comment by Rokvach** [comment]
After further playing with the new stacking, I don't think this limitation is necessary. Only place this could become an issue is with fuel rods  and other expensive fuel. But that can be limited later based on the player feedback. Closing.
