### ISSUE TITLE
Multiplayer - When standing at max-rangeish of a locker/battery/oxygen gen/etc and changing out sub slot item with the one in them, will cause the item transfering to you to drop

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4494]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When in Multiplayer and when standing at max-rangeish of a locker/battery/oxygen gen/etc and changing out sub slot item with the one in them, will cause the item transfering to you to drop.

**Reproduce**
You can most commonly reproduce this on [Dandelion](https://steamcommunity.com/sharedfiles/filedetails/?id=2312353651) for instance.

1. Put some battery cells in the submarine's battery charger.
2. Get a Scooter with a battery cell in it
3. Stand like right here:
![Capture](https://user-images.githubusercontent.com/5086682/101961386-a3614380-3bd7-11eb-8596-2ee559416e51.PNG)
4. Try exchanging the battery from the scooter with another battery cell from the battery charger.

The battery cell should fall onto the platform right underneath the battery.

**Version**
~0.1200.0.0

**Comment by Kaillera** [comment]
Actually sometimes even when you're exchanging oxygen tank from your toolbelt to plasma cutter/diving suit or exchanging toolbelts while holding a crate just drops when you're moving.

**Comment by Regalis11** [comment]
Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/6310, closing
