### ISSUE TITLE
[Unstable 0.12.0.0] All Scrap variants found in wrecks doesn't stack in to a single stack

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4495]
Might be better to differentiate the different types of scrap you can find in wrecks a bit more as it would feel a bit strange/like a bug that you can't stack all of them in the same pile even when they have the exact same name and description.

**Comment by danielasteljoki** [comment]
So let's go with the random deconstruct items option where we define in the xml a list of possible items and how many of them we can get from an item. Something like this:
```
<Deconstruct time="10" chooserandom="true" amount="2">
      <Item identifier="thorium" copycondition="true"/>
      <Item identifier="steel" copycondition="true"/>
      <Item identifier="aluminium" copycondition="true"/>
      <Item identifier="titaniumaluminiumalloy" copycondition="true"/>
      <Item identifier="iron" copycondition="true"/>
      <Item identifier="steel" copycondition="true"/>
</Deconstruct>
```

**Comment by ekqvist** [comment]
Added in Regalis11/Barotrauma-development@078beed and Regalis11/Barotrauma-development@660d9a9.

I used the attribute names used in the example. I also added support for "commonness" attribute for the Item elements. Both the "amount" attribute of the Deconstruct element and the "commonness" attribute of the Item elements will default to 1.

**Comment by danielasteljoki** [comment]
Combined in 52cc12b.

**Comment by Rokvach** [comment]
Tested, didn't find any issues. Closing.
