### ISSUE TITLE
Choosing a campaign name with illegal filename characters causes people on Windows to fail to connect

### ISSUE THREAD

**Issue by PJB3005** [Regalis11/Barotrauma#4496]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you make a campaign with a file name that is legal on Linux but illegal on Windows (such as ">") and host on Linux, people playing on Windows will not be able to connect. They'll get an error about being unable to save the downloaded save file or something. Linux clients are still able to connect just fine.

**Steps To Reproduce**
Host server on Linux, start a campaign with a filename like "foo > bar" and try to connect with a Windows client. 

**Version**
v0.11.0.9, Linux for server, Windows for client.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6fd5bc8ee3333f796f172e8a26f43d81ce1c3322

**Comment by Rokvach** [comment]
No issues, closing.
