### ISSUE TITLE
[Unstable 0.12.0.0] Reactor can hold stacked fuel rods

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4497]

**Comment by Regalis11** [comment]
Steps to repro?

**Comment by Kaillera** [comment]
Could be a multiplayer thing only? What I've noticed is when you put stacks into them, they get ejected at the start of the next level.

**Comment by Rokvach** [comment]
Was this with the Outpost reactor on your custom sub? I wasn't able to place a stack of fuel rods in to a slot in multiplayer

**Comment by Kaillera** [comment]
Yeah it's the outpost reactor.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c957925

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
