### ISSUE TITLE
Sliders Are All Locked to Values

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#4499]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every slider in the settings menu is locked to specific values: for example, sound values are at every 5%
![image](https://user-images.githubusercontent.com/37539527/101968272-38832d00-3c16-11eb-898a-22d47347f140.png)
This makes it hard to get the precise value you want. Technically it's possible by editing the setting xml directly, but then if you ever open setting it gets set back to the nearest allowed value.  
I think the easy solution to this is to have a typeset box which is linked to the slider - the slider can still go to the nearest 5%, but the box should allow the player to enter any (integer, between 0 and 100) value.

**Steps To Reproduce**
1. Open settings
2. Try to set your sound volume to 7%

**Version**
v0.11.9.0+

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/59bab494171e6ea6885d0d8d4ef2df1f9a0be370

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
