### ISSUE TITLE
Нужна помощь с ошибкой в игре. Need help with a bug in the game.

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#45]
Перевёл игру на 85%-90%. Все предметы корректно работают. Появилась проблема с руинами.
Translate the game on 85%-90%. All items work correctly. There was a problem with the ruins.
![image](https://user-images.githubusercontent.com/33912761/33182377-d1edce9c-d084-11e7-82cd-05361e333756.png)

**Comment by Regalis11** [comment]
You need to modify Content/Map/RuinConfig.xml to use the new names you've given to the items.
