### ISSUE TITLE
A non-correct map generation

### ISSUE THREAD

**Issue by SomeUselessGuy** [Regalis11/Barotrauma#450]
Seed: TmLAjF1a
Pic: 
1) https://media.discordapp.net/attachments/449924143652143104/458656076372639774/unknown.png?width=831&height=468
2) https://media.discordapp.net/attachments/449924143652143104/458656044483084288/unknown.png?width=831&height=468

**Comment by OriaOriginal** [comment]
Another strange seed. I'we just tried a SCP:CB seed.
Seed: DONOTBLINK
Pic: 1) https://cdn.discordapp.com/attachments/449924143652143104/458662511517106224/unknown.png
2) https://cdn.discordapp.com/attachments/449924143652143104/458662595218505738/unknown.png

**Comment by Regalis11** [comment]
Which submarine were you using? And which version of the game is this, based on the the Cyrillic characters in the UI it seems like you were using some type of mod(s)?

**Comment by OriaOriginal** [comment]
1) Ubertanker - https://mega.nz/#!DksTRCKR!wPOf8J8DTcKqvgQztARkcd7Z9cx6OZEo-0o7ngnR3VY
2) Just russification

**Comment by Regalis11** [comment]
Should be fixed in the dev branch
