### ISSUE TITLE
[Unstable 0.1200.0.0] Deleting inventory items in Sub Editor crashes the game

### ISSUE THREAD

**Issue by Bobbleton** [Regalis11/Barotrauma#4502]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While in the sub editor, deleting any storage that contains items, or items themselves while in the inventory form (taking something out of a crate and dropping it in the spawning menu) will cause the game to crash.

**Steps To Reproduce**
All one needs to do is delete an inventory with items in it, like a closet, or crate.

**Version**
The bug happens in unstable V0.1200.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5559cb0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
