### ISSUE TITLE
[Unstable V0.12.0.0]  Item Stacking bug in Training Mission

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4506]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the Security Officer training mission when you are introduced to ranged weaponry (the shotgun) and are tasked with filling it up with shotgun shells, the new stacking item system changes the shotgun shells somehow and prevents the mission script(?) from progressing. It doesn't recognize the stackable shells.

**Steps To Reproduce**
Play Security Officer Training as normal and follow all mission goals until you can no longer proceed any further.

**Version**
Unstable V0.12.0.0 on Windows 10 

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f672ebe90f2cd12844a1b4782bdff49419db48b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
