### ISSUE TITLE
Spineling spike physics causing extreme lag?

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4507]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Spineling projectiles seem to get stuck and cause the performance to drop down significantly

**Steps To Reproduce**
Spineling shoots a spike
Spike gets stuck in a bad place (whatever that is)
Game has a seizure until the spike despawns

**Version**
v0.11.0.9 Windows 10

**Additional information**
Clip: https://cdn.discordapp.com/attachments/587647684794515468/787468529133158400/Desktop_2020.12.13_-_00.48.09.03.DVR_1.mp4

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/1818e08c243a1523bc483b0f54cf70f5292f9115

**Comment by Rokvach** [comment]
Tested, didn't notice any issues. Seems to be working correctly. Closing.
