### ISSUE TITLE
Can't accept mod download - Buttons out of screen bounds on small resolutions

### ISSUE THREAD

**Issue by Pewkek** [Regalis11/Barotrauma#4508]
**Description**
When trying to join a modded server, if the mod list is long enough, the buttons to confirm download of the mods is out of screen bounds. This is especially true for smaller screens.

**Steps To Reproduce**
1. Find a server with long list of mods
2. Try to join
3. The button is not visible, thus not clickable

**Version**
OS: Windows 10, ver. 1909
Game: v0.11.0.9
Resolution: 1366x768

**Additional information**
Solution to the problem would be making the modlist scrollable. Also, the download progress should also be changed, as it is probably out of screen bounds too.

Screenshot of the problem, game running at 1366x768 (on laptop), I can't join a modded server, because I can't download the mods:
![mods](https://user-images.githubusercontent.com/43827200/102003048-dc4a0700-3d02-11eb-9f46-d41d4597aca9.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/044dd50f5130337d39f47428c33fd298584a0d09 and https://github.com/Regalis11/Barotrauma-development/commit/8f9d3eb

**Comment by Regalis11** [comment]
Note for QA: since it may be hard to find servers with this many mods installed, you may want to use the debug code in the commit  https://github.com/Regalis11/Barotrauma-development/commit/044dd50f5130337d39f47428c33fd298584a0d09 to test this.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
