### ISSUE TITLE
Servers that have shut down sometimes remain in the listing for large periods of times afterwards.

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#4509]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes, when a server shuts down, instead of disappearing, it will stay in the server browser, as if it were an active server, (showing player count ping etc). This effect can last for days.

**Steps To Reproduce**
I have no idea what causes it. It's not consistent between servers, either. A server that gets stuck might not get stuck the next time.

**Version**
I've noticed this for awhile now, though its definitely been a lot worse recently. v0.11.0.9 Linux.

**Additional information**
It always seems to happen at the worst of times.

**Comment by Regalis11** [comment]
No known steps to repro, it's possible this has been fixed since the ticket was created
