### ISSUE TITLE
Los effect

### ISSUE THREAD

**Issue by CryIz** [Regalis11/Barotrauma#451]
Los enabled.
![image](https://user-images.githubusercontent.com/33912761/41706369-57590056-7544-11e8-8367-d3d91015b9f2.png)
Los disabled.
![image](https://user-images.githubusercontent.com/33912761/41706399-6e0f4bb6-7544-11e8-954a-04cd1ca97115.png)
![image](https://user-images.githubusercontent.com/33912761/41706412-731aca2c-7544-11e8-82ea-79d6e1987373.png)

**Comment by juanjp600** [comment]
As far as I can tell, the first screenshot actually has the LOS effect enabled, while the other two have it disabled.

The issue I see here is that the blocked areas look brighter than the visible areas, but other than that it seems to be working correctly.

**Comment by CryIz** [comment]
The bottom line is that, in the opinion of many, much better looks just the same as in the last two screenshots. Nothing extra is evident. The game becomes more beautiful. If Your idea was to show the walls and the background, then you can make some switching.

**Comment by CryIz** [comment]
In the game "SubTerrain" you can change this effect. Make it barely noticeable, generally disable or make very bright.
![image](https://user-images.githubusercontent.com/33912761/41785902-a7b08480-764c-11e8-851b-fb85ef95eb53.png)

![image](https://user-images.githubusercontent.com/33912761/41785909-ab556916-764c-11e8-863b-100128839745.png)

**Comment by Regalis11** [comment]
Fixed in 87350fb0
