### ISSUE TITLE
Inventory related crash when interacting with a dead Husk

### ISSUE THREAD

**Issue by SumNutz** [Regalis11/Barotrauma#4513]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crashing when interacting with a dead husk inside alien ruins, specifically when tried to take eggs from the corpse

**Steps To Reproduce**
Kill a husk roaming inside a room in the ruins, grab its dead body, transfer eggs to inventory (in this case, toolbelt) and boom, crashed

**Version**
Unstable Windows, 0.1200.0.0

**Additional information**
No additional comments.

CRASH LOG: 
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5684978/crashreport.log)

**Comment by Rokvach** [comment]
Looks like grabbing any creature causes this crash

**Comment by itchyOwl** [comment]
Seems to be related to the stacking changes, perhaps it's best that @Regalis11 takes a look: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/9924565e-8070-4517-bed3-d6f926c7d8a5)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a677869eb9812a3b8972360d64a64c636508e3dd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
