### ISSUE TITLE
"hideconditionbar" property does not properly hide condition readout in item description

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4516]
[Bug] 
![image](https://user-images.githubusercontent.com/47284081/102052369-e7be3080-3ddd-11eb-97aa-57a8bfac621d.png)
Sort of self explanatory. Properly hides the condition bar but doesn't hide the percentage readout.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3548303a1a46f1f645bf97bc8437a8b04b0599c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
