### ISSUE TITLE
[0.1200.0.0] When crafting items that aren't stackable (ex. Railgun Shells) the fabricator doesn't eject the item for continuous crafting.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4519]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When crafting items that aren't stackable (ex. Railgun Shells) the fabricator doesn't eject the item for continuous crafting. For railgun shell case: it would craft the item once, leave the shell in the output slot, craft another one, then eject the old one, and stops after the second one is done (even though there were more steel for more shells).

**Version**
0.1200.0.0

**Comment by Regalis11** [comment]
Even though this would be easy to fix, we decided not to: if the fabricator kept fabricating for as long as there's materials available, it could lead to wasting a lot of materials if you forget to turn off the fabricator after you're done.
