### ISSUE TITLE
Squishing humans/aliens between the submarine and wrecks/beacon/shuttle doesn't hurt

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4520]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Squishing humans/aliens between the submarine and wrecks/beacon/shuttle doesn't hurt.

**Version**
Any

**Comment by Regalis11** [comment]
This doesn't seem to be an issue specific to v0.1200.0.0, looks like it was only implemented for cases where the character collides with the sub while in contact with the level. Edited the ticket.
