### ISSUE TITLE
Docking port state_out inconsistent behavior SP vs MP

### ISSUE THREAD

**Issue by Arokha** [Regalis11/Barotrauma#4522]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
`state_out` on docking ports has inconsistent behavior when comparing singleplayer and multiplayer. Singleplayer displays expected behavior, multiplayer displays erratic behavior with 'flickering' output.

The example sub starts with two docking ports (A, B). Dock A starts in use by a submarine that is docked, linked in editor. Dock B is unoccupied.

*Singleplayer*: 
`Dock A state_out = 1`, `Dock B state_out = 0`, as expected. Moving the docked submarine alters the state_out outputs.
`Dock A state_out = 0`, `Dock B state_out = 0` when the submarine is undocked, as expected.
`Dock A state_out = 0`, `Dock B state_out = 1` when the sub is moved to B and docked, as expected.
![P0uYherFId](https://user-images.githubusercontent.com/15028025/102122154-17d3f680-3e13-11eb-97fe-1a5b061a437d.gif)
(Lights 1 and 4 are directly connected to `state_out` on docking ports A and B respectively)

*Multiplayer*:
`Dock A state_out = 1`, `Dock B state_out = 0`, as expected. Moving the docked submarine alters the state_out outputs.
`Dock A state_out = 0`, `Dock B state_out = 0` when the submarine is undocked, as expected.
However, the inconsistency arises when the sub is moved and docked to B:
`Dock A state_out = 0`, `Dock B state_out = flickers between 1 and 0`
Moving the submarine back results in the same behavior with Dock A. The output flickers between 1 and 0 for about 1 tick at a time.
![goxsco8YEd](https://user-images.githubusercontent.com/15028025/102121942-c592d580-3e12-11eb-9eb2-74e8445e1f58.gif)
(Lights 1 and 4 are directly connected to `state_out` on docking ports A and B respectively)

**Steps To Reproduce**
[Demo Sub: EK Matriarch Mk IV.zip](https://github.com/Regalis11/Barotrauma/files/5690935/EK.Matriarch.Mk.IV.zip)
I've attached a submarine that has this issue present and. Performing the same actions in the editor in 'test' and in a multiplayer server results in different behavior and is easily reproduced. There are some debugging lights and a lever here:
![image](https://user-images.githubusercontent.com/15028025/102121109-6e403580-3e11-11eb-966d-63f5cace06c1.png)

Just use the lever, the problem is demonstrated after 5 seconds.

Flipping the lever causes a sub to move between these two docking ports. These are wired to the 1st and 4th light component right below the lever. You can see the inconsistent behavior between SP and MP there.

![image](https://user-images.githubusercontent.com/15028025/102121279-b8291b80-3e11-11eb-86fa-f643cb26eee9.png)

**Version**
0.11.0.9
Windows 10 x64 Pro

**Additional information**
Fairly confident this is a bug given the fact that it's inconsistent between the editor test mode and multiplayer. Performing the same actions, first thing after load, results in wildly different outputs.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/71f918ab68538f79ad12f9b48ab2a325994119f5

**Comment by Arokha** [comment]
Thank ye kindly!

**Comment by Rokvach** [comment]
Tested, got the same results between SP and MP. Working correctly. Closing.
