### ISSUE TITLE
Wiring: Using S-R and J-K latches causes multiplayer desynchronisation of wiring logic states.

### ISSUE THREAD

**Issue by Quilan** [Regalis11/Barotrauma#4525]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Real-world implementations of S-R and J-K latches (using NOR gates in a feedback loop) work clientside and in SP but their state does not correctly change for other players, which has knock-on effects for machinery controlled by these systems.

**Steps To Reproduce**
Submarine file attached. Airlock Test contains the two latches.
The OR gates in these examples have been converted to NOR gates by switching their "output" and "false output" values to 0 and 1 respectively.
![image](https://user-images.githubusercontent.com/1065204/102140665-80dd5d80-3e57-11eb-8041-9b6894467101.png)
https://cdn.discordapp.com/attachments/712852957745381376/788162494493360128/airlock_test.sub

The circuit on the left is a Set-Reset latch. Pressing the bottom button should switch on the top lamp and switch off the bottom lamp, pressing the top button should switch on the bottom lamp and switch off the top lamp.
The circuit on the right is a J-K latch. Pressing the button toggles which lamp is on and which lamp is off.

To reproduce:
1: Start a multiplayer server with at least two players.
2: Load the testbed above (or construct the relevant circuits).
3: One lamp in each circuit should already be illuminated; confirm that the same lamp is illuminated on both clients.
4: One player ("tester") should manipulate the circuits by pressing the buttons while the other ("observer") watches the results.
Expected: When the tester presses a button to change a circuit state, the observer and tester should both see the lamps change state.
Actual: When the tester presses a button to change state, they observe a change. The observer sees no change.
Additional: When the client and observer disagree on circuit state, the lamps may or may not flicker rapidly, suggesting the server is sending state updates that are then overridden locally. This is more obvious when machinery is connected to the circuit, resulting in e.g. players phasing through closed doors, rooms flooding and then emptying with no visible cause, etc.

**Version**
v0.11.0.9 ReleaseWindows, revision c60afcc03b
OS: Windows 7

**Additional information**
The following submarine implements a J-K latch and two S-R latches in each airlock to cycle the airlock, which causes the airlock state to desynchronise in multiplayer:
https://cdn.discordapp.com/attachments/712852957745381376/788162521919127602/Kuwauso_Heavy_Refit_Mk2.sub

Circuit diagrams for relevant circuits:
S-R:
![image](https://user-images.githubusercontent.com/1065204/102142817-ed0d9080-3e5a-11eb-96f1-8eb39bd5ba91.png)
J-K:
![image](https://user-images.githubusercontent.com/1065204/102142876-00b8f700-3e5b-11eb-9c36-de304ba3c450.png)

**Comment by Alaac** [comment]
Sad to see low priority, but I also encountered this bug and it's terribly annoying. I suppose we can find a workaround using MEM blocks instead tho but ideally a JK block would be much welcome

**Comment by Regalis11** [comment]
I've created a "general" ticket about signal timing issues, closing this one https://github.com/Regalis11/Barotrauma/issues/12993
