### ISSUE TITLE
[Unstable V0.12.0.0] Switches and Levers do not toggle_state properly.

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4526]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Detailed reproduction steps of the issue below, the title is as concise as I can describe it..

**Steps To Reproduce**
1) Go into sub editor and make a basic test area, mainly a hull and floor, with dim lighting.
2) Set up two emergency lights (light range 500, default off)

These are Emergency Light A and B, shortened to EL-A and EL-B.

3) Add a switch and hook it up to EL-A's toggle.
4) Add a lever and hook it up to EL-B's toggle.
5) Run the simulation

6A) Flick the switch 1 time per second.
6B) Flick the switch rapidly.

In both experiments, notice there are three states.

State 1: Off.
State 2: Soft flickering, but visibly on.
State 3: Fully on, no flicker.

7) Do step 6A and 6B with lever as well, and notice the similarity.

**Version**
Unstable V0.12.0.0 on Windows 10

**Additional information**
This is only when the switch is wired to toggle_state instead of set_state (the latter functioning normally as expected)
These state changes are random from what I can tell, is this a bug or "working as intended"?

**Comment by Regalis11** [comment]
I don't think this is a bug: switches send a continuous signal of 1, which causes the lights to toggle continuously when the signal is being sent to "toggle_state".
