### ISSUE TITLE
Text goes outside the box on scaled-up text displays 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4527]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When scaling the display scale above 1.000,  the text does not match the sprite

**Steps To Reproduce**
1. Scale up a text display to 2.000 and write a text at default scale (caps preferably)
2. Text goes outside the box (more visible on scrolling text)

**Version**
v0.11.0.9 Win10

**Additional information**
![Capture](https://user-images.githubusercontent.com/73229309/102149708-58f9f400-3e6f-11eb-8e95-8c88600f5a8c.JPG)

**Comment by Regalis11** [comment]
Should be fixed in the latest unstable build (fixed in commit https://github.com/Regalis11/Barotrauma-development/commit/1d4df6a4)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
