### ISSUE TITLE
Submarine getting stuck on the map ceiling at start of mission and unable to move

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4530]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If your submarine has a shuttle extending out of its model, the shuttle can clip into the ceiling and the submarine is unable to move

**Steps To Reproduce**
1. Dock a very tall shuttle above your submarine
2. Shuttle will clip on the ceiling

**Version**
 v0.11.0.9 Win10

**Additional information**
Tried finding the level seed in logs but it doesn't seem to match when loaded in editor

![unknown](https://user-images.githubusercontent.com/73229309/102151778-e3445700-3e73-11eb-88e4-ab06251ba36e.png)

**Comment by ubertpendragon** [comment]
Note: this seems to be happening in after entering "Linea", but not after leaving outposts

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/72fca2390d59204b24037c6d031d6595ac0dae14

**Comment by Rokvach** [comment]
There hasn't been any sightings of this happening since it was fixed, closing for now.
