### ISSUE TITLE
All Items in Item Assembly Should be Selected After Placing

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#4539]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After placing an item assembly, all parts of it should be selected. This allows for easier movement of the items.

**Version**
0.11.0.9+

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/260b1fb7df857c9c00dbb43deafda00a7e09cf65

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
