### ISSUE TITLE
[0.1200.0.0] Leucocyte count too much after commit 2fc02b4

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4542]
**Description**
Leucocyte count is too much and unfair, proposal to revert changes or make it minimal since event manager throws you plenty of enemies at higher difficulties anyway. (Also causes fps to tank heavily due to ~40-50 leucocytes)

**Steps To Reproduce**
Use save provided
`freecam`
Find wreck with thalamus in map
`teleportsub` near it

**Save :**  [testsave.zip](https://github.com/Regalis11/Barotrauma/files/5703579/testsave.zip)

**Version :** [0.1200.0.0]

**Additional information**
![bruhomega](https://user-images.githubusercontent.com/72674994/102366991-380edb80-3ff4-11eb-8100-5b485a4a8001.jpg)

**Comment by itchyOwl** [comment]
It's not intentional that there's so much leucocytes. I'll check it out.

**Comment by Xeavas** [comment]
IMO thirty is still a lot, considering how they "stunlock" you and other attributes you face at higher difficulties may make this more unfair than "reasonable". Possibly additional considerations regarding this would be taken into account too 👍

**Comment by itchyOwl** [comment]
Well I think I'll just fix the code first. We can always bring the values down, but right now there's something wrong in the math.

**Comment by itchyOwl** [comment]
At least there seems to be 10x more cells in general than what is supposed to. I remember changing / 100 to * 0.01f (probably after testing), but apparently there's 0.1f in the code :D Well.. Good that this didn't get into a release version...

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@ee43c4b.

**Comment by itchyOwl** [comment]
When testing, also give it a general test, for example using the level editor and please report if the count of leucocytes is not what you expect it to be. In general there should be approximately the same level of leucocytes than before when the difficulty level is 50. The values in ThalamusAI.xml are for the highest difficulty level, from where they are scaled down linearily. Note that there's also some random that can be configured in the same xml file.

**Comment by Xeavas** [comment]
I see, will do! Probably will be alright after the fix (well enough that it doesn't tank fps), I first discovered this in level editor actually, then went and confirm it in campaign to make sure its not an edge case. And thanks for explaining the spawn rates more clearly, sounds good 👍

**Comment by Rokvach** [comment]
Tested in couple of different difficulties and the leucocyte count was acceptable, didn't spot any further issues with this. Closing.
