### ISSUE TITLE
[Unstable V0.12.0.0] Medical item stats and use limits

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4543]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm comparing medical items now that small items can stack, and I've noticed their healing stats have changed a lot.

**Steps To Reproduce**
Did a quick comparison with Medical 0 as Captain in sub editor.

setskill Medical 0
giveaffliction Burn 75
spawnitem Bandage inventory
spawnitem Bandage inventory

On Stable, 3 uses of Bandage (1 whole item) got me from Vitality -75 to Vitality -2.
In Unstable, it took 6 uses of Bandage (2 items, but at the cost of 1 less inventory space since they stack up to 8), going from Vitality -75 to Vitality -1.

Medical 100 (On Unstable) gave the same results, so there is no penalty for unskilled bandaging it seems.

**Version**
Unstable V0.12.0.0 on WIndows 10

**Additional information**
Also noteworthy, the amount of times you can use a medical item (based on your medical skill) is gone?
Medical 0 resulted in 4 uses of a Saline pack, and 2 uses of a Blood pack, when the wiki's info indicates that you would only get a single use of these items without being skilled enough.

(Not only on Saline and Blood packs, seemingly on all items that have a use limit based on skill)

fEstivEcodE guy on Discord mentioned bandage stats had not been touched in over 8 months, thought it was strange.
Maybe percentage based weirdness due to stacking?

**Comment by Regalis11** [comment]
Bandages are configured to reduce burns by 15, and it seems to be working as expected. I'm pretty sure the reduction was caused by us fixing this issue: https://github.com/Regalis11/Barotrauma/issues/4336
