### ISSUE TITLE
[Unstable V0.12.0.0] DIving Suit uses room oxygen.

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4546]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Diving Suit (with no oxygen tank) uses oxygen from the room, but still chokes you out.

**Steps To Reproduce**
Wire up an oxygen sensor to a text screen to see oxygen level.
Stand alone in the room and wear a diving suit with no oxygen tank.
Notice that the air is being used up, but you are still choked.

**Version**
Unstable V0.12.0.0 on Windows 10

**Additional information**
An empty mask (with or without oxygen tank) lets you breathe oxygen from the room normally, without choking you out.
So it's weird that the suit uses up room oxygen yet still choke to death.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cefd2b635bfa7874484a8484c2ebb2d8ac32a801

**Comment by Rokvach** [comment]
Tested, I was still able to reproduce this.

1. Start a multiplayer round with Orca
2. Use godmode command on your character
3. Equip a diving suit
4. Go stand in the airlock or on the room right of nav terminal
5. Take the oxygen tank off from diving suit
6. Notice that the room oxygen level starts to deplete (using debugdraw to see oxygen level)
7. Place the oxygen tank on the diving suit and the depletion stops

**Comment by Regalis11** [comment]
2nd attempt: https://github.com/Regalis11/Barotrauma-development/commit/43527f8927dada89229cfd4d5207d3702364c316

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
