### ISSUE TITLE
Bot fails to fix the Azimuth engine as they try to reach it from the oxygen generator room

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4547]
Branch: dev
Build: Release
Game mode: Multiplayer mission
Commit: https://github.com/Regalis11/Barotrauma-development/commit/7a8dd00493899afacf2bf96ecbcaa60e41b30bc1

Looks like a waypoint issue or a bad placement for the engine

The bot is just stuck there trying to walk towards the wall in order to get closer to the engine. Even if I teleport the bot in to the engine room he will walk to the oxygen generator room again when trying to repair the engine.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bb4bfdd1-29a3-4010-9bec-1d589f7b304b)

**Comment by Rokvach** [comment]
Will need to re-test with the new waypoints

**Comment by itchyOwl** [comment]
Can't repro with the new waypoints.

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate too with the new waypoints (gave it several attempts) 👍

**Comment by Rokvach** [comment]
Closing
