### ISSUE TITLE
[v0.1200.0.0] Secure Steel Cabinet is not waterproof

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4549]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All other cabinets are waterproof now, with exception of the "Secure Steel Cabinet" which doesn't really make much sense since it looks the most waterproof of them all.

**Version**
Unstable v0.1200.0.0 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/45f5ec5bb007e45bab2e886a5f55a84af979583b

**Comment by Rokvach** [comment]
No issues, closing.
