### ISSUE TITLE
Visual bug on medium weapon display

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#4550]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Medium weapon display have items in them rotated side way
![image](https://user-images.githubusercontent.com/70696707/102495623-e4aa9500-40a8-11eb-9378-61045b4e84a4.png)

**Steps To Reproduce**
Put in a medium weapon display in sub editor

**Version**
0.1200.0.0 (Windows).

**Additional information**
Has been around for a few versions.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1bbe4b4af2e2528dad911ac4037e86ff931f1811

**Comment by Xeavas** [comment]
[0.1200.0.1] - No Issues 👍

**Comment by Rokvach** [comment]
Closing
