### ISSUE TITLE
[Unstable 0.12.0.0] Unable to cancel multiple fabrications of items that are not stackable

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#4551]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am unable to cancel a duplicate fabrication (after the first item has been crafted) of a non-stackable item.
Put simply, I am unable to make only 1 if a non-stackable item, if there are enough materials to make multiple, because I cannot cancel the job while the second one is being made.

**Steps To Reproduce**
1) Link a cabinet to a Fabricator
2) Place enough materials for 3 sets of Piercing Ammo in the cabinet
3) Construct Piercing Ammo
4) Try to cancel fabricating after the 1st ammo box is completed
You will be unable to stop it

**Version**
Unstable 0.1200, Windows 10, 64 bit

**Additional information**
The issue happens with all coil ammo types and railgun shell types.
 The one common factor between them all is that they are non-stackable.

Video:
https://streamable.com/pfbqv6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f1af423347a4895385dd10429ca554fe59868f6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
