### ISSUE TITLE
[Unstable V0.12.0.0] Button pops off after use.

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4555]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Single-use button or switch, pops off after pressing under very specific editor condition.

**Steps To Reproduce**
1) Connect a button to a door's toggle_state.
2) Open the button's edit panel and press "Reset to prefab"
3) Try using the button ingame.
4) Go back into editor and try re-opening the button's connection panel.

**Version**
Unstable V0.12.0.0 on Windows 10

**Additional information**
It might be a bug but it's also kinda fun to make these, you don't lose the button or wire when it pops off.
The negative thing about it is step 4, so that's mainly what I'm reporting here.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ff5ee6d933b4e3a63cd0e740840aefa36ba7bd7b

**Comment by Xeavas** [comment]
[0.1200.0.1] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing.
