### ISSUE TITLE
[0.1200.0.1] You can stack medicines in syringe gun

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4557]
Self Explanatory
![syringestack](https://user-images.githubusercontent.com/72674994/102638230-22cfb380-4192-11eb-990d-b1067e94a942.jpg)

**Version** [0.1200.0.1]

**Comment by danielasteljoki** [comment]
Decreased syringe gun ammunition slots to one in 2743b06.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
