### ISSUE TITLE
[0.1200.0.1] Crash - Near non-thalamus Wreck

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4561]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5718781/crashreport.log)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/5718782/Save.zip)
I was about to park next to the wreck in this level. There's an artifact on this wreck as well. My security officer spotted a mudraptor coming out of it, killed it, and kept shooting at something else that was probably coming out of the wreck. I crashed shortly after.

**Version**
0.1200.0.1

**Comment by Kaillera** [comment]
I went over to another wreck in another level, switched to my bot gunner on a coilgun to look at the wreck, shortly after I crashed.

**Comment by 3e849f2e5c** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/6af30e67e4a237d4f622e163ec8866ab7ad8f841
No real repro steps, happened because the game tried to make an enemy face against it's target when the target has been removed

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
