### ISSUE TITLE
[Unstable V0.12.0.1] Wrecked tank shelf visual bug.

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4563]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When placing tanks inside a wrecked tank shelf, you can stack 24 tanks into it.

**Steps To Reproduce**
Place a wrecked tank shelf in editor and fill it with tanks.
Picture supplied in Additional Info

**Version**
Unstable V0.12.0.1 on WIndows 10

**Additional information**
![reference_wrecked_tank](https://user-images.githubusercontent.com/69410159/102689788-29494400-4201-11eb-892e-08009c155117.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9e80135d42e53f1a92be229067ef7f3d2e8d225b

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
