### ISSUE TITLE
[Unstable V0.12.0.1] Unusable room oxygen.

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#4564]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A portion of the room's oxygen is completely unusable at a certain air quality.

**Steps To Reproduce**
1) Make a sealed room and spawn alone in it.
2) Enable debugdraw to watch oxygen.
3) A low oxygen warning is given at ~50 but does not seem to give you a debuff.
4) At oxygen levels of 30 and below, you start choking at (what I feel is) the same rate of being in water.

**Version**
Unstable V0.12.0.1 on Windows 10.

**Additional information**
Rokvach commented on discord that this _might_ be related to the suits being fixed to not use room oxygen.
Discord message link: https://discord.com/channels/103209684680323072/668819422919524352/789584280413405194

https://user-images.githubusercontent.com/69410159/102693212-4db11a80-4219-11eb-9b08-1be5aa0d698d.mp4

**Comment by Regalis11** [comment]
This is intentional, you start suffocating if the oxygen level is below 30% (faster the lower the oxygen level is).
