### ISSUE TITLE
Unreliable propeller damage & phasing through shell at high speed

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#4565]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
2 problems:
1. Propeller do not reliably cut all the time. 
2.  On high speed (80km/h+), enemies may phase through walls, entirely or partially, and cause lags when too many are being phased

https://user-images.githubusercontent.com/70696707/102694765-bd44fb00-4255-11eb-9b57-a58bee6cdf1c.mp4

https://user-images.githubusercontent.com/70696707/102694891-84f1ec80-4256-11eb-8888-5dc575d7b17e.mp4

 **Steps To Reproduce**
1. Use the attached sub.
[Nova VX 2.5.6 Test.sub.zip](https://github.com/Regalis11/Barotrauma/files/5719854/Nova.VX.2.5.6.Test.sub.zip)
2. Use nav terminal to move forward, press overdrive to push the sub to extremely high speed.
3.  Enable cheats, spawn monsters ahead of the sub.
4. See monsters phased through the shell (2m thick, 4 shells side by side) or not chopped by propeller

**Version**
0.1200.01

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
