### ISSUE TITLE
[Unstable] Fin wings are too dark to recolor nicely

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4566]
New art assets for fin wings are far too dark by default to work well recolored decorative usage.
![image](https://user-images.githubusercontent.com/55356135/102696321-7f1aed80-41fb-11eb-976a-5fde7a7212d0.png)
I suggest that fins are brightened up a bit to near their previous sprites, and possibly desaturated about 50% as they currently have a heavy blue hue on the grime and dirt.
![image](https://user-images.githubusercontent.com/55356135/102696368-c7d2a680-41fb-11eb-924b-d489ac4184f0.png)

**Comment by Rokvach** [comment]
Tested, looking fine to me. Closing.
