### ISSUE TITLE
[0.1200.0.1] Purchased items in stacks unnecessarily gave more crates

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4568]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I bought:

2 Memory Components
2 Multiply Components
1 Divide Components
2 Signal Checks
2 WIFI
20 Wires of varying colors

I received 2 crates. One with almost everything I purchased in the list, still wasn't full. The other crate had just 10 wires.

**Version**
0.1200.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/36e68cde01ec7371be3b4f424c20c599ca4c3be5

**Comment by Rokvach** [comment]
Tested, only received a single crate with the same items, working correctly. Closing.
