### ISSUE TITLE
We are effectively capped at 8 batteries per power network

### ISSUE THREAD

**Issue by lifearoundfreaks** [Regalis11/Barotrauma#4571]
- [✅] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://github.com/Regalis11/Barotrauma/blob/bbf06f09844276cbb41924dd8e1eefb92c6d1759/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Power/PowerContainer.cs#L195
Because of how CurrPowerOutput variable is adjusted if `deltaTime * {amount of batteries}` exceeds the value of 2 it causes the runaway effect that fries the power network.

**Steps To Reproduce**
Connect 9 or more charged batteries to a power network with some load.

**Version**
Tested in 0.10.0.9

**Additional information**
https://www.reddit.com/r/Barotrauma/comments/hswpv5/power_distribution_issue/

**Comment by Will-Aspden** [comment]
Could this be fixed with a very simple Math.Min() to cap `deltaTime * (gridLoad - gridPower)` at 1.99?

**Comment by lifearoundfreaks** [comment]
> Could this be fixed with a very simple Math.Min() to cap `deltaTime * (gridLoad - gridPower)` at 1.99?

The used formula is fine. They don't need to clamp anything in it and it would not fix anything. The problem lies in the fact that "battery race" occurs - the fact that batteries don't know about each other and all adjust their output at the same time, totally overshooting in the process.

**Comment by lifearoundfreaks** [comment]
As a suggestion, we can add a parameter to POWERCONTAINER components that would be responsible for power adjustment speed. Leave it the same as the current adjustment speed to not break any submarines and just leave further adjustment to the sub creators.

**Comment by Regalis11** [comment]
Should be addressed by `power-rework`, moving to testing

**Comment by Rokvach** [comment]
Tested by Jade Harley and confirmed working (video proof), closing.
