### ISSUE TITLE
Diving suit suffocating us no matter how much O2 it had

### ISSUE THREAD

**Issue by cueballtv** [Regalis11/Barotrauma#4573]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A diving suit instantly suffocated no matter how much O2 was in its tank

**Steps To Reproduce**
Unfortunately no clue; it killed four of us though :(

**Version**
0.10.0.9 windows 1909

**Comment by Regalis11** [comment]
Haven't been able to reproduce this: I wonder if it could be that there was a welding fuel tank inside the suit instead of an oxygen tank? Does this happen consistently or was it a one-time thing?

**Comment by cueballtv** [comment]
> Haven't been able to reproduce this: I wonder if it could be that there was a welding fuel tank inside the suit instead of an oxygen tank? Does this happen consistently or was it a one-time thing?

I actually came to the same conclusion after some more play! Sorry for the mix up!
