### ISSUE TITLE
Motion detector with Target: Monster detects pets

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4574]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if its intentional, but it means that pets can trigger traps and other systems that were designed with actual monsters in mind.

**Version**
v0.1200.0.1 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5adccd9762b52bcbc6a93952051f2b108628a109

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
