### ISSUE TITLE
[MULTIPLAYER CAMPAIGN] Character inventory kicks other players off the game

### ISSUE THREAD

**Issue by AldymG9** [Regalis11/Barotrauma#4577]
**Description**
During our campaign session, after entering one of the outposts the game bugged itself and deleted 4 out of 8 playable characters, and dropped the entire inventory of other surviving characters on the ground. The NPCs on station have been also walking around without any inventory on their person. After quitting to the server lobby and starting the mission again, the bug have occured again. After restarting the entire game and testing a bit, we've pinpointed one player which was causing the bug after his character appeared in the world (he could join to the game to spectate, but once his character joined on the submarine, the entire process had repeated itself). After deleting this character inventory off of the CharacterData.xml file everything worked, but the character inventory and skill progress has been obviously deleted. This outcome is less then ideal, but if nothing can be done about it, we can just create another character for the player with only replacing the skill values for newly created character.

**Steps To Reproduce**
Unknown. It happened after entering one of the station like always. The player has been in process of interacting with some items in the deconstructor/fabricator during the mission end screen, but nothing out of the ordinary has happened. The station has been a part of the newly revealed area on the campaign map.

**Version**
v0.11.0.10 on Windows 10, revision dc7157029e

**Additional information**
I've provided the CharacterData.xml file in the .txt format for further review. The character in question that has been affecting the entire server is named "Ricardo Hamon". Without him on the server everything works just fine. 
[Gamer9 0_CharacterData.txt](https://github.com/Regalis11/Barotrauma/files/5732328/Gamer9.0_CharacterData.txt)

**Comment by Coryf88** [comment]
Delete the text in the `Terminal`'s `msg0` attribute of the `handheldterminal` in "Ricardo Hamon"'s inventory.
Specifically the `"&#xA;Day 1 of the expedition out of Meltwater. We're navigating through a newly...."` text.

#4460

**Comment by AldymG9** [comment]
Worked like a charm. Thank you kindly!
