### ISSUE TITLE
Steering velocity_y_out signal range does not match pump set_targetlevel clamping

### ISSUE THREAD

**Issue by tsteiner** [Regalis11/Barotrauma#4578]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pump's set_targetlevel input expects a signal from -50 to 50, as seen here:
https://github.com/Regalis11/Barotrauma/blob/e47f0850a52709d6b3e0e92c67135124c1e61a11/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Pump.cs#L169

Steering's velocity_y_out is set from TargetVelocity, which has a range of -100 to 100.  Furthermore, when neutralBallastLevel isn't 0.5, the range can be shifted (eg: -125 to 75).
https://github.com/Regalis11/Barotrauma/blob/e47f0850a52709d6b3e0e92c67135124c1e61a11/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Steering.cs#L332-L333 
This mismatch results in the pump target level being maxed out well before the input target velocity is maxed out, and at different levels when neutralBallastLevel has been changed.

**Steps To Reproduce**
Manually steer a sub to descend/ascend at about 75% maximum speed.
The ballast tanks will be completely full/empty.

**Version**
v0.10.0.9 Windows

**Additional information**

**Comment by Confodore** [comment]
The resulting "Deadzone" appears to go from 50% up to 100% vertical speed. Was testing on recommended neutral ballast of 0.5

- In the top half of the picture: tests show that at 100% ascend signal shows -99 and water detector shows 0% watter. This is expected.
- In the bottom half of the picture : at 50% ascend speed the ballast is still empty. Not good.

![04](https://user-images.githubusercontent.com/57303910/105390795-baa14100-5c19-11eb-9889-af17312d438b.png)

Almost certainly is causing problems with autopilot in some way or another.

I strongly recommend changing:
`targetLevel += (neutralBallastLevel - 0.5f) * 100.0f;`
into:
`targetLevel += (neutralBallastLevel * 200f) - 100.0f;`

while also removing the strange and nonsensical +50 calculation from the pumps target level:
` TargetLevel = MathHelper.Clamp(tempTarget + 50.0f, 0.0f, 100.0f); `
into:
` TargetLevel = MathHelper.Clamp(tempTarget, 0.0f, 100.0f); `

**Version**
Stable v0.11.0.10 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf5860fd93d5a17b1356f457e80ef49a389f8dff

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
