### ISSUE TITLE
Multiplayer - Paying to Recover Shuttle, Shuttle damage desynced (Again)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4579]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My crew undocked a shuttle at the outpost level, and somehow sank it. We left the outpost and went back to it to be able to pay to recover it. We left the outpost again to have the shuttle respawned in. When we inspect the shuttle and went to weld the damage, the shell/wall repairs were not reflecting on the client side exactly like what happened in #4325. It repairs but all clients will see it still damaged with water leaking in. We redocked to the outpost and the repairs made in the previous level synced up properly again.

**Version**
~0.1200.0.1

**Comment by Regalis11** [comment]
I wasn't able to reproduce this, but I suspect https://github.com/Regalis11/Barotrauma-development/commit/32105d59ec210da12823a7ebe77b55cbb10f9901 could fix it

**Comment by Rokvach** [comment]
I was able to reproduce this issue, tested in dev

1. Start a multiplayer campaign with Remora
2. On outpost level undock the drone
3. Wait for it to be a decent distance away from the sub
4. Use "Explosion 1000 1000 1000" on the drone
5. Undock from outpost
6. Dock to outpost
7. Buy to recover shuttle
8. Undock from outpost
9. Notice that the Remora drone is fully damaged, water keeps fluctuating inside the drone, when you try to weld the walls, the walls health bar doesn't change but stays empty. Close the door to the drone and notice that the water that got inside the sub suddenly vanish as well. 

Dock back to the outpost and notice that the drone is now suddenly fully repaired with no water inside it

**Comment by Regalis11** [comment]
Thanks, I was able to repro it now, and pretty sure it's fixed: https://github.com/Regalis11/Barotrauma-development/commit/f4a6c9961a4a236438ef61abd57d5e23133a26b9

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue using the earlier pointed out steps. Working correctly. Closing.
