### ISSUE TITLE
Bug - Docking shuttle, attached to main sub, does not connect correctly

### ISSUE THREAD

**Issue by Guhlius** [Regalis11/Barotrauma#4580]
**Description**
I made a sub with a shuttle on top, docking to stations via the shuttle.
When docking this contraption to a station, there is a gap in the docking port, sucking people out when trying to cross.
Docking is done from the main subs terminal, using the "dock via tip" button, since wiring the shuttles docking port to the main sub using wifi did not spawn the big red "dock" button.
Undocking the main sub from the shuttle and redocking fixes this problem.

**Steps To Reproduce**
Dock this contraption to an outpost. (https://steamcommunity.com/sharedfiles/filedetails/?id=2327428307)

**Version**
 [0.10.0.9] - Windows

Screenshots:
https://imgur.com/a/q94iBET

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
