### ISSUE TITLE
Bug/ Bots/ Behaviour/ No Oxygen

### ISSUE THREAD

**Issue by Swato85** [Regalis11/Barotrauma#4583]
- [ ] I have searched the issue tracker to check if the issue has already been reported.
RE: I have searched google, nothing found on this.

**Description**
RE: When there is no oxygen, bots do not put on masks or other sources of oxygen even though they have everything available, inluding masks with oxygen in inventory.
NOTE: If I flood the room or simply let some water leak inside, they put on masks immediately.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
RE: Build a ship without oxygen source, once hulls are without oxygen, bots will prefer to suffocate instead of putting on masks.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
RE: WINDOWS 10. Playing on Steam stable=latest versions as of 24.12.2020

**Additional information**
RE: Just as was said above, bots react to presence of water but choose to die when without oxygen, instead of putting on masks.

**Comment by itchyOwl** [comment]
It's a known issue and should already be fixed in the unstable, see #4390. Closing as a duplicate.
