### ISSUE TITLE
Spawning cargo in custom named hull throws errors in multiplayer

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4585]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If cargo spawnpoint is set in hull with custom name (not using preset strings), when cargo is spawning in multiplayer, errors are thrown in console. Cargo still spawns correctly.

**Steps To Reproduce**
Rename hull with cargo spawnpoint to any custom name and launch a multiplayer mission with "Additional Cargo" items selected.

**Version**
v0.1200.0.1 Windows

**Additional information**
![image](https://user-images.githubusercontent.com/48099798/103134947-e4b42180-46b4-11eb-8d5c-4b7c45305f09.png)

**Comment by ubertpendragon** [comment]
Can confirm, error disappeared when I used the in-game tag **roomname.cargo**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/55edecc9c5e27a6b212e91537037bf81e0c71408

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
