### ISSUE TITLE
"Additional Cargo" menu for missions has questionable stuff available

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4586]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using "additional cargo" option in settings there are some items available that seem like they shouldn't be.
List of some that caught my eye:
- ID Card
- Shipwreck ID Card
- Alien Button
- Alien light Component
- Lamps
- Camera (& legacy Camera)
- Terminal
- Logbook
- Scrap
- Emergency light
- SMG Round
- Wrecked Lamps
- Mutated Pomegrenade
- Outpost terminal

**Version**
v0.1200.0.1 Windows

**Additional information**
![image](https://user-images.githubusercontent.com/48099798/103135012-820f5580-46b5-11eb-847a-a5a88addbbce.png)
Buying those lamps made them attach to the wall in the cargo hull when they spawned.

**Comment by ezjamsen** [comment]
There are a few there which are useful for RP. Regardless, let's removed the following from the list:

- Alien Button
- Alien light Component
- Lamps
- Scrap
- Outpost terminal

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6b30ccbd0af5c3a4c8875dee7390707d1a0bd7fb

**Comment by Rokvach** [comment]
Tested, didn't spot any unusual items on the list. Working correctly. Closing.
