### ISSUE TITLE
Missing component checkmark on the Dugongs wreck 

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#4587]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I was poking around in the submarine editor and looked at the Dugongs wreck, I found a circuit that sends out a [[D-35 DISTRESS-CALL]] on the WIFI channel 911, but since the WIFI component doesnt have crossteam-communication enabled, the circuit is pretty much uselsss.

**Steps To Reproduce**
Open the submarine editor
Open the Dugongs wreck
Look at the airlocks cabinet, then to the right inside the wall

**Version**
Windows 10
![grafik](https://user-images.githubusercontent.com/63376072/103140566-6ffada80-46e8-11eb-9ce5-1d2a8aa175a2.png)

**Additional information**
(Im talking about this one here)
![grafik](https://user-images.githubusercontent.com/63376072/103140568-7e48f680-46e8-11eb-9756-50944a9c77bc.png)

**Comment by danielasteljoki** [comment]
That's a remnant of a distress call test I did. The idea was to have a terminal aboard your sub that received these distress calls. That didn't pan out, but I left those components there just in case.
