### ISSUE TITLE
Critical Missing files, such as config_player and hashcache.txt,

### ISSUE THREAD

**Issue by Antikythera1901** [Regalis11/Barotrauma#4588]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When attempting to enter any playable form of the game, including multiplayer, Single player, as well as the tutorials, causes multiple different critical game errors preventing the game from launching. Complete game re-installs and steam cloud wipes have already been attempted and have not fixed the issue

**Steps To Reproduce**
I installed the game, and attempted to play it, was able to finish all the tutorials once, but as soon as I attempted to enter a multiplayer, the issue began occurring. 

**Version**
Version: 0.10.0.9
Operating system: Windows 10

**Additional information**
![barotrauma, player](https://user-images.githubusercontent.com/76603232/103144023-2dd59700-46f0-11eb-9988-a0c22391fbab.png) 

![blocked hashecache](https://user-images.githubusercontent.com/76603232/103144026-362dd200-46f0-11eb-90b6-13a4cbfa46e5.png)
![Autosave submarine not found](https://user-images.githubusercontent.com/76603232/103144030-49d93880-46f0-11eb-8ff3-682e359f7ff2.png)

**Comment by Regalis11** [comment]
Thank you for the report, and sorry for the late response!

Based on the error messages, it seems the game is somehow failing to write to the game folder. One potential cause for this could be that the Windows user you're logged in as doesn't have a permission to write to the folder for some reason. I'd try launching the game as an administrator directly from the game folder (right click Barotrauma.exe -> "Run as Administrator"): if you no longer see the errors, it would suggest the problem has to do with Window's user permissions.

If that's the case, you should be able to fix it by right-clicking the Barotrauma folder, going to the Security tab, and making sue the user group is allowed to modify, read & execute, read and write to the folder:
![image](https://user-images.githubusercontent.com/14351070/103543842-d978a700-4ea7-11eb-8d68-6d70d41d547b.png)
