### ISSUE TITLE
Text-linked WiFi components don't work in Shuttles

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#4589]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wifi components don't send messages to chat when part of a shuttle, even within the range and cross-team communication turned on

**Steps To Reproduce**
1. Make a shuttle
2. Send signal through wifi component
3. Enable Link To Chat on channel 0
4. Link shuttle to a submarine and load
5. No text message

**Version**
 v0.11.0.10 Win10

**Additional information**

https://user-images.githubusercontent.com/73229309/103145161-c7736780-4735-11eb-94ef-5d4291ef5ae6.mp4

**Comment by subarotrauma** [comment]
Can you maybe share ur submarine file, I might be able to help the.

**Comment by ubertpendragon** [comment]
It's the base Dugong in the video, didn't work on my sub either so I assume it doesn't work in general

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this. Tested with the following sub and shuttle (the terminal is in the room below the command room, and set to channel 821): 
[Kastrull-wifitest.zip](https://github.com/Regalis11/Barotrauma/files/5836560/Kastrull-wifitest.zip)


So I the issue has something to do with how you've set up the custom circuits in the shuttle or the main sub.

**Comment by ubertpendragon** [comment]
This is the "sub" I'm using:
[Wifinotworking.zip](https://github.com/Regalis11/Barotrauma/files/5842695/Wifinotworking.zip)

If you use the Hemulen_Beacon alone, standing around the navigation terminal will send the Wifi message in chat

However, if you use the BeaconCeiling (which is a combination of a Beacon station + Hemulen_Beacon shuttle), you won't get the Wifi message at all

**Comment by ubertpendragon** [comment]
@Regalis11 

So apparently this is a sub editor test problem; I tested it by launching a mission (turning my beacon into a submarine, not sure how it'll behave as a beacon) and the Wifi works. 

Speaking about non-working sub editor items, Sonar Beacons also don't work in sub editor test while working fine in missions. Their status (on/off) also resets when saving, which means you can't have sonar beacons by default

Feel free to close the ticket as it technically works, but not in sub editor
