### ISSUE TITLE
[Unstable,Modding] SpawnItem effect unable to place additional items in a container.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4590]
**Bug:** When trying to use a status effect to spawn items inside of containers with a max contained stack size of 1 but multiple item slots, no more items spawn when the status effect is triggered after the first slot has spawned an item in it.

**Steps to reproduce:**
Create item container with `capacity="8" maxstacksize="1"` 
add a SpawnItem status effect for any stackable item, IE revolver rounds 
( use something easy to trigger it, like an OnUse effect or CustomInterface )
Triggering the effect will cause the first item to appear, but subsequent triggers will make no new items appear inside
despite there being room for empty slots.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6473bd3a3b071bd6e9bd37ed696b76138a58d90

**Comment by Rokvach** [comment]
This hasn't caused any issues, so seems to be working. Closing.
