### ISSUE TITLE
Text Display broken in submarine editor

### ISSUE THREAD

**Issue by Farkas122** [Regalis11/Barotrauma#4593]
- I have searched the issue tracker to check if the issue has already been reported.

**Description**
The text display icon disappeared and I can't even place it.

**Steps To Reproduce**
I think I did something to a label like removed the sprite.

**Version**
v0.11.0.10 Windows

I fixed it by restarting the game.

![bug](https://user-images.githubusercontent.com/71283839/103160056-dc510900-47d0-11eb-807e-2d2bf6299b64.PNG)

**Comment by itchyOwl** [comment]
Looks like a missing sprite. What do you mean by possibly removing the sprite?
