### ISSUE TITLE
submarine stuck at map

### ISSUE THREAD

**Issue by 1stLtv2** [Regalis11/Barotrauma#4596]
![baro](https://user-images.githubusercontent.com/65464699/103211793-1ee72280-4944-11eb-9e5c-63517528c783.jpg)
typhon jammed under beacon station

[since28DEC2020.zip](https://github.com/Regalis11/Barotrauma/files/5747160/since28DEC2020.zip)

**Comment by Regalis11** [comment]
Potential duplicate of #4632. Even though this is an earlier ticket, I'll close this one since the newer one has a bit more info.
