### ISSUE TITLE
[Feature request] Junction boxes and batteries should reduce air quality or outright poison it - IF Europa ocean is cloride-rich

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#4598]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I know it can be a little bit TOO hardcore addition, but at least I can put it for discussion here.
Also it depends on how devs see lore of their game.
So, Europa ocean is salty, because in-sub plants dont like it. IF these salts is mostly clorines like on Earth ocean, exposure of that solution to open electric components will produce clorine. It was dangerous back on Earth and many sub crews fall victims to clorine poisoning.
So I suggest either define what is sea water on Europa and throw out that idea completely, or discuss how it would change the gameplay. Currently Im not talking about ALL electrical devices, only junction boxes and batteries.

**Comment by ezjamsen** [comment]
This is pretty severe :D The game is already pretty difficult. @Regalis11 do you see this as something you'd want to explore?

**Comment by Regalis11** [comment]
Even though this could make sense from the perspective of realism, I'm not sure if it'd work that well gameplay-wise. The implication would be that having any water on the sub can make the air unbreathable, which I could imagine resulting in everyone wearing masks/suits almost all the time (or at least much more than now). In a way, there would be no state where the sub is flooding "just a bit", it'd be a binary choice between fully dry and needing diving gear. I think it'd also be challenging to communicate this feature to the players effectively enough.
