### ISSUE TITLE
Suggestion: Make Textures clippable by polygon or bezier

### ISSUE THREAD

**Issue by Konfuz** [Regalis11/Barotrauma#4599]
Despite searching I found no way to clip a background texture so that it does not exceed the bounds of the submarine in the editor. This happens alot, if the hull has round shapes. The way it is done now seems to be to add smaller tiles of the same texture and manage the texture-offsets by hand to make them match which is tedious and can lead to visual imperfections.  

Instead it would be great to use the editor to define a polygon that clips the texture to a visual area and leaves the rest to the renderer. This would lead to smoother results. Even better results could be achieved by clipping to bezier curves, but that is likely harder to implement. 

I included a graphic to illustrate my point. 
![texture_clipping](https://user-images.githubusercontent.com/11818151/103309993-d9475a00-4a16-11eb-99ab-d013e1368d84.png)

**Comment by Regalis11** [comment]
Even though this would be a very handy addition, it'd require such extensive changes to the rendering logic that I'm afraid it's out of scope at least for the time being.
