### ISSUE TITLE
Barotrauma.exe disappears on 0.8.1.3

### ISSUE THREAD

**Issue by Niko27000** [Regalis11/Barotrauma#460]
I wanted to play today but the Exe and the launcher are just impossible to find. Nothing in the bin, nothing where I looked... Does anyone has the same problem ?

**Comment by Hans134** [comment]
Same!

**Comment by Niko27000** [comment]
Do you know how to officially report that ? It seems like a heavy problem

**Comment by Hans134** [comment]
It seems to be a big problem. However, I do not know how to report it officially.

**Comment by Niko27000** [comment]
Well yeah that's the problem :p guess I'll go back to 1.2 for now and just wait for news

**Comment by Hans134** [comment]
It doesn't even work on 1.2 for me.

**Comment by Regalis11** [comment]
The exe and launcher are inside the game folder, the same place as before. There have been reports of antivirus software moving the exe to guarantine, I wonder if that could be what's happening here? Did you update the game using the launcher or download the zip from the website?

Also, this issue tracker is the way to report issues officially, so you've posted in the right place. :)

**Comment by Niko27000** [comment]
Perfect then, and I download every new version from the website
