### ISSUE TITLE
Failed to read event for EntitySpawner

### ISSUE THREAD

**Issue by dmex** [Regalis11/Barotrauma#4604]
- [X] I have searched the issue tracker to check if the issue has already been reported.

Our server crashed everyone with an "Failed to read event for EntitySpawner" error. We tried restarting both the server and clients but everyone constantly spawned dead and we're not able to continue that savegame at all.

I wasn't able to find any crashreport_object.log or similar file containing the error information and only have this screenshot:

![image](https://user-images.githubusercontent.com/1306177/103323626-e5bfc700-4a97-11eb-84fc-7fff202b4436.png)

**Steps To Reproduce**
Unknown. A player was using the deconstructor/cabinets/crates when the error occoured.

**Version**
0.11.0.10
Windows 7 x64 - server
Windows 10 x64 - clients

**Comment by dmex** [comment]
Fixed the issue by editing Deep_SIX_CharacterData.xml and removing a few duplicate Items with the same ID and removed some other entries for handheldterminal.

**Comment by EdusFF** [comment]
From a friend of mine, playing multiplayer campaign. No crash or anything - just a lot of rubberbanding for a moment before everything went back to normal

![ss+(2021-02-07+at+12.20.58).png](https://images.zenhubusercontent.com/5c9c9f992250f9495b572b76/e95eb06c-5b52-4cd5-8464-189153076084)

**Comment by dmex** [comment]
@Regalis11 

I haven't come across the same issue since the last patch. Is it ok to close this issue?

**Comment by Regalis11** [comment]
I suppose this can be closed, we can create a new ticket or reopen this if the issue resurfaces.
