### ISSUE TITLE
Respawn Shuttles does not autofill at least once

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4605]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Autofill on Respawn Shuttles does not work. Expected items to spawn in for the first time it spawn.

**Version**
~0.1200.0.1

**Comment by itchyOwl** [comment]
The autofiller only runs on main subs. Should we change this? Not sure if it's intentional or just an oversight.

**Comment by ezjamsen** [comment]
Do you mean that we should for example, re-autofill the shuttles each time they spawn?

**Comment by Kaillera** [comment]
Just at least once instead of every respawn
