### ISSUE TITLE
No way to keep complex circuits wired for custom beacons

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#4606]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wires are randomly removed from beacons, which prevents adding custom circuits.

**Steps To Reproduce**
Go to beacon, see that wires are randomly missing.

**Version**
All versions.

**Additional information**
It would help to have a toggle button for something like "does not get removed for beacon missions" on individual wires.

**Comment by mygamingaccount** [comment]
I figured those components in your wrecks must had been for something.

https://github.com/Regalis11/Barotrauma/blob/f433a7ba10f6a6f1d33ba5229fbe936d8e7161f4/Barotrauma/BarotraumaShared/SharedSource/Map/Levels/Level.cs#L3123-L3129

Barotrauma rips up wires completely randomly.
Here's an idea: put more redundant wires in parallel to reduce the chance of it breaking!

**Comment by ubertpendragon** [comment]
**Suggestion:**
The game should not remove wires set to *Not Interactable*, this way we'd be able to build custom beacon circuits

**Comment by ezjamsen** [comment]
We do need a way to prevent destruction of certain beacon elements, there was a plan for this right @juanjp600 ?

**Comment by Regalis11** [comment]
@ezjamsen The plan was to not remove wires that are locked or non-interactable, but looks like no-one got around to implementing it. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e26f38ad41129160b2e14a87a66fd07ddca0fb4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
