### ISSUE TITLE
Station NPCS follow me into the sub for no reason.

### ISSUE THREAD

**Issue by PeacekeeperLife** [Regalis11/Barotrauma#4607]
- [x] I have searched the issue tracker to check if the issue has already been reported.
The first few pages.
**Description**
When I spawn into a multiplayer campaign with a friend, there is a chance that the Station NPCs will follow me no matter where I go.

**Steps To Reproduce**
Spawn into a multiplayer campaign. (Obviously doesn't happen all the time.)
**Version**
12/31/2020 (Windows)

**Additional information**
Its amusing.

**Comment by itchyOwl** [comment]
Haven't encountered this myself. If someone figures out the steps with which this issue can be triggered, please write them down here.

**Comment by Rokvach** [comment]
This sounds like the teenager event where the 3 teens starts to follow you around wherever you go.

**Comment by itchyOwl** [comment]
If so, that's intentional right?

**Comment by Rokvach** [comment]
Yeah its intentional, but could still be limited so they only follow you inside the outpost.

**Comment by Kaillera** [comment]
They follow you but never activate the event.

**Comment by itchyOwl** [comment]
I also noted that they seem to spawn out of thin air near the player. Could someone more familiar with the even system look into this?

**Comment by Udrakan** [comment]
Usually this happens to me in multiplayer, but I cant bugtest it because event editor is empty in MP.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
