### ISSUE TITLE
Main Docking Port and Level Generation problem

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4612]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you use a submarine that has multiple docking ports and it's using a Main Docking Port that isn't closest to the center of the submarine, the level generates the start of the level with the submarine undoked around the centerish area without the Main Docking Port offset. This could lead into being unable to dock the submarine because the level doesn't factor in where the Main Docking Port is.

**Steps To Reproduce**
You can see this behavior easily with my old sub with multiple port and shuttles [HERE](https://steamcommunity.com/sharedfiles/filedetails/?id=2008809055). The main docking port is the most upper left side of the submarine, and it spawns into every level at the center point. This makes it so that you have to try to fit the submarine with any other ports instead of Main Docking Port if it doesn't fit. Other subs may not have the logic to handle multiple docking port docking for this scenario.

**Version**
~0.1200.0.1

**Additional Informations**
Expected the level to start the submarine with the Main Docking Port adjacent to the Outpost Port.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/43a6d9371e48bba9cdc9f55fbc71e908bf90f81e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
