### ISSUE TITLE
Issue with interactions

### ISSUE THREAD

**Issue by CareCallsLTD** [Regalis11/Barotrauma#4618]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Certain items are not properly intractable, seems to be things at floor-height, video in editor and running test to fully explain and show issue here:
https://share.getcloudapp.com/X6u0nXrr
There is as much detail as I could think of throughout the whole video, let me know if I can do anything to help.

**Steps To Reproduce**
Attached submarine bug appears on, the HMS Seafist and its Shuttle
[HMS Seafist and shuttle.zip](https://github.com/Regalis11/Barotrauma/files/5760195/HMS.Seafist.and.shuttle.zip)

**Version**

<img width="598" alt="Screenshot 2021-01-02 at 11 40 06" src="https://user-images.githubusercontent.com/57261151/103456577-53b1fb80-4cef-11eb-9672-303ecefec1db.png">

**Additional information**
Love Barotruma! <3 <3

**Comment by Regalis11** [comment]
Hello and thank you for the report!

I wasn't able to open the video, that link gives a "not found" error. Could you check if the url is correct?

**Comment by CareCallsLTD** [comment]
Hi Joonas

Been meaning to update this as just found the solution. Its because I had
the main sub and shuttle linked to each other both ways in the editor. I
think I created some kinda crazy loop which made in-game run really slowly
and created these little bugs as described.
Might be worth putting a check to see 'Does the submarine file I am linking
to contain a link to the submarine I am linking from?' and if so not
allowing it to happen.
I did it as it made it a lot easier to test the shuttle quickly but it also
makes sense that if there was not some kind of check-in place this would
cause a lot of issues, surprised the game ran at all when I did this tbh
haha.

Hope that helps, absolutely love your game <3

Kind regards

Max Pownall
CEO | CareCalls.co.uk
<http://carecalls.co.uk/?utm_campaign=general&utm_medium=email&utm_source=email-sig>
linkedin.com/in/maxpownall/ <https://www.linkedin.com/in/maxpownall/>
07540116031 • 0330 058 8244
*Read how CareCalls can help during COVID-19* 🦠
<https://www.carecalls.co.uk/2020/03/23/how-carecalls-can-help-with-covid-19/?utm_campaign=covid19&utm_medium=email&utm_source=email-sig>
* <https://www.linkedin.com/company/carecalls/>*

ᐧ
