### ISSUE TITLE
[Suggestion] Teleport Style Door / Z depth level.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4619]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

Okay imagine this: You find a Jovian hideout in the level:
![Idea2](https://user-images.githubusercontent.com/5086682/103462526-c4f3ad80-4cf3-11eb-8e10-eb82d9b1ceef.PNG)

and you Press E on the background door to enter it. The background door can be key card locked, wirable, etc. You will be moved into an isolated part of the map or instanced a level behind the main level and come out to this: 

[Gif 1](https://cdn.discordapp.com/attachments/668819422919524352/794975289423560784/Dungeon-Idea2.gif)
[Gif 2](https://cdn.discordapp.com/attachments/220881718666723328/795061465705873438/Dungeon_Idea_2.gif)

There's a lot of dungeon and puzzle potential with this, and you can also create more interesting submarine design if it can be used for it. You can make completely uncheesable dungeons. They can be completely dry, or wet. The door can have the option to add in water into the interior if the door isn't closed.

For some monster ai logic, they will have a cooldown on using these doors if they are not hunting a target, to let them search around for preys. If they've acquired a target, they'll follow the player into the same doors they've used unless the player was able to stay out of sight long enough.

Players will be able to design big submarines without having to worry about filling up the space inside as much (Big plus really). All monsters really have to do is break the outer shell of a submarine, swim in, and find whatever room they like to breach into too.

**Comment by aeondez** [comment]
I'm onboard with having doors/cave entrances for dry land. Slap a waypoint on it, call it "Cave" as a mission type, and let all types of enemies fight back. Monsters, humans, new dry-land monsters, the more the merrier. I'd especially like to have a reason to get into a human vs. human shootout.

I think this could potentially solve a lot of the existing issues with Barotrauma not having a great mechanism for including "dry" caves in the game.

Jumping off of that, just because it's dry doesn't mean the air is breathable.

**Comment by ezjamsen** [comment]
This might be something we could use down the road, with alien ruins.

**Comment by Sviat** [comment]
roguelike potential rises!

**Comment by Ek-Videogames** [comment]
( This seems like good outpost fodder, just saying. Although maybe you'd need some kind of logic for linking doors together if you wanted to have them able to generate between different modules. )
