### ISSUE TITLE
exterior submarine devices cannot be wired mid-game (Railguns/Lights)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#462]
Version 0.8.1.3

I have just realized when a player removes wires from a submarine, most of it can be mended in game. 

The exception to this is exterior railguns. once a player exits a submarine the wire connection is cancelled. however there are cases where this may be required.

It also prevents the wiring of detonators inside of ruins but that is not too important.

Not sure if this is a bug or a feature request, but the inability to mend railgun wiring and other external devices is ultimately game-ending at times for a submarine.

**Comment by Regalis11** [comment]
Fixed in 869b725 & d0b61b3
