### ISSUE TITLE
Raptorbane doesn't work on nest mudraptors

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4620]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Raptorbane doesn't work on nest mudraptors. They don't take organ damage.

**Version**
~0.1200.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e62c9742d3a5d499cead9aa183774fffe53b981e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
