### ISSUE TITLE
duplicate submarine in sub editor load menu

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4623]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Two submarine entries appear in sub editor's submarine loader after doing some editing on the sub.
using slightly different slash and backslash.

![img](https://cdn.discordapp.com/attachments/427654262453960724/795218981807325184/unknown.png)
![](https://cdn.discordapp.com/attachments/427654262453960724/795218998613639198/unknown.png)

goes away by restarting barotrauma/pretending it doesn't exist

**Steps To Reproduce**
edit a sub, save
sometimes see a 2nd entry in loader (including multiplayer lobby? not sure about single player) for rest of session.

**Version**
windows 10

0.11

**Additional information**
[04:18] hashcode fellow: bruh
[04:18] hashcode fellow: yeah no clue what's going on there

**Comment by Udrakan** [comment]
Im getting those too

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/103488022-d6c77480-4e09-11eb-94eb-00958c7d2aaf.png)
-have any contentpackage that has subs in it
-save a new submarine in editor
-reload game
Thats what does it for me

**Comment by Udrakan** [comment]
idk if content package has an effect on it, but I had it

**Comment by MonstraG** [comment]
Happened to me too, one common thing between me and repoductions above: submarine name conains "."

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce and haven't seen this happen. Closing.
