### ISSUE TITLE
Floating ice chunks take half a coilgun box or more than a few railgun shells to break

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4627]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ice Blocks takes half a coilgun box or more than a few railgun shells to break. It's too durable.

**Version**
~0.1200.0.1

**Comment by ezjamsen** [comment]
You mean the ice blockages in caves?

**Comment by itchyOwl** [comment]
Spires?

**Comment by Kaillera** [comment]
The natural floating ice blocks in the middle of level. Not spires.

**Comment by Gwilt** [comment]
We typically use a railgun with Compound N installed, Only takes one shot.

**Comment by Regalis11** [comment]
Reduced the health a bit in https://github.com/Regalis11/Barotrauma-development/commit/e7002f12c296ac38a8e7f15e1a5d5079479de454

**Comment by Rokvach** [comment]
Tested, takes a lot less now but still you need to shoot it quite a long time without any feedback other than particles telling you that you are actually damaging it. But seems a bit better, closing.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/95e796c6-fc7f-433b-9369-f4a3a46547ce)
