### ISSUE TITLE
bots willing to use mission cargo for medicine

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4628]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
bots reportedly are willing to use mission cargo (i.e., medicine) to heal themselves, causing the mission to be uncompletable

**Steps To Reproduce**
take medicine mission
hurt bots
bot uses medicine for mission

**Version**
0.11.0.11 stable

**Additional information**
hearsay from discord
"mark mission cargo as 'stealing'"

**Comment by aeondez** [comment]
To expand this a bit more, it was suggested to use the same red-hand tag(stolen?)  for goods transported for cargo missions to prevent bots from accidentally touching cargo, as well as to identify players caught stealing from the cargo.

**Comment by ekqvist** [comment]
Adding the tag "ignorebyai" to the items when they are created for the mission should also prevent the AI from using the items on their own, in case we want to just do that

**Comment by itchyOwl** [comment]
I think what aeondez suggested would solve both issues, but we can do either. Which one would you prefer, @ezjamsen ?

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@1721c53.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
