### ISSUE TITLE
Talking to station NPC during event prompt breaks event.  

### ISSUE THREAD

**Issue by xrabohrok** [Regalis11/Barotrauma#4629]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Station quest where you need to place a listening bug for the head of security to prevent a jailbreak can be permanently broken by talking to an NPC (in my case, a mission-giver) when about to place the bug in the crew quarters.  I know of no way to bring the mission prompt back.

Talking to the NPC clobbers the text box so that the choice is no longer available, and then closes.  

**Steps To Reproduce**
1. Receive the "place bug in crew-quarters" event/quest in a station (doesn't matter where or how).
2. Go to the crew quarters.  You will need an NPC with some sort of intractability, in my case being able to press 'E' on them to receive a mission to also be in the crew quarters, standing near the trigger for the next part of the quest/event.
3. when the "What do you do: place bug in electronics, place bug in bunk" screen prompt comes up, press 'E' on the mission-giver NPC when they wander by.
4. Dismiss the Mission Prompt.

Result: The player is now unable to finish the event/quest.  

**Version**
0.10.0.9

**Additional information**
Happened in my case during a multiplayer game.  I have a suspicion that this can happen during any multi-part event.

**Comment by Rokvach** [comment]
This shouldn't be possible to happen with the latest event changes, closing.
