### ISSUE TITLE
Inconsistent Deconstructor to Linked Cabinet behavior

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4634]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're deconstructing items using the deconstructor that is linked to a cabinet has these behaviors:

1) When items are deconstructed, the items remain in the output slot instead of moving into a cabinet every other time.

2) When items are deconstructed and outputs 3 items or more, and the deconstructor already has 3 items in it before hand, the remaining output that couldn't fit drops onto the floor. Every other time it will move into the cabinet after deconstructing.

Expected: Items to be moved into the cabinets every time, or move the previous output into the cabinet while leaving the new output in the deconstructor. With the new stacking feature, the items could remain in the output until the stacks are full, or the new output contain different items, then move into the cabinet to make room for the new items.

**Version**
~0.1200.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6d7561a9af52b238819dd1e38a4aadc92569770c

**Comment by Rokvach** [comment]
Tested, all items even if they are on the output are moved in to the cabinet. Working correctly, closing.
