### ISSUE TITLE
[0.1200.0.1] When Bots are switching Oxygen Tanks while being outside the sub, they throw the empty tank outside.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4636]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When Bots are switching Oxygen Tanks while being outside the sub, they throw the empty tank outside. Nowadays with the stacking feature, my bot's toolbelts have lots of inventory space. I feel like they should keep the tanks in their inventory if they are switching tanks outside the sub. Preferably in their toolbelt first if they have it.

**Steps To Reproduce**
1. Give a bot a few oxygen tanks.
2. Go outside the sub.
3. Tell the bot to follow you.
4. Let the bot consume the tank entirely.

**Version**
~0,1200.0.1

**Comment by itchyOwl** [comment]
It's an oversight. I think we could just make them put the empty containers in the inventory when they are outside the sub and if there's enough space.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@4f7bcc4.

**Comment by itchyOwl** [comment]
Also fixed for ammunition and welding fuel tanks.

**Comment by Xeavas** [comment]
[0.1200.0.3] - Unable to replicate for original Issue 👍 

Noticed an issue but I've created a new ticket for it. #4842

**Comment by Rokvach** [comment]
Closing

**Comment by itchyOwl** [comment]
In some cases bots may still drop the bottles in the sea. Should be fixed in Regalis11/Barotrauma-development@03c9788.
