### ISSUE TITLE
[Suggestion] Beacon Station - Add some monsters to them

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4637]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think at least a few enemies in Beacon Stations would spice them up a bit.

**Comment by aeondez** [comment]
Please. The spawnpoints do nothing. Corpses would be cool, too.

And it's only ever crawlers. The odd spineling, thresher, or mudraptor would make things much spicier.

**Comment by hubismal** [comment]
i for one kind of like beacons as a little safe haven away from all the dangers of the ocean.

**Comment by aeondez** [comment]
> i for one kind of like beacons as a little safe haven away from all the dangers of the ocean.

Yeah, but wouldn't it be more satisfying if you had to clear them out first?

**Comment by JeroonBosch** [comment]
Code for spawning monsters is done, will just need to add beacon stations with the spawn points in it

**Comment by JeroonBosch** [comment]
Just have to add more monsters to the sets in randomevents_campaign.xml

**Comment by Rokvach** [comment]
I noticed crawlers spawning in on the beacons, so working correctly. Closing.
