### ISSUE TITLE
Outpost guards lose ability to open doors and pathfind when in combat

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#4641]
**Description**
![image](https://user-images.githubusercontent.com/59519434/103625046-ae8b6300-4f3a-11eb-910c-e8b7c215ec21.png)

**Steps To Reproduce**
-use "setlocationreputation -100" command while in outpost
-look at guards when they try to fight you, but arent in the same room
-as soon as combat ends, they can navigate outpost normally again and can open doors

**Version**
Stable

**Comment by Udrakan** [comment]
Related issue:
NPCs have the same pathfinding problems when they are set to follow a target.
STR: 
-Have NPC follow something through events.
-observe
In this video, you can see the NPC not being able to open doors when running to the target. Idle NPCs operate in this outpost normally.

https://user-images.githubusercontent.com/59519434/103714074-0dde8700-4fbe-11eb-8eac-390fc31c12e2.mp4

**Comment by Udrakan** [comment]
Got more for you. Here is a gif of what they do.
Here is the save, but its modded >_< (you need ITA for it https://steamcommunity.com/sharedfiles/filedetails/?id=2005463692)
[Dugong - Military Blank Rep.zip](https://github.com/Regalis11/Barotrauma/files/5774491/Dugong.-.Military.Blank.Rep.zip)
![bad pathfind](https://user-images.githubusercontent.com/59519434/103743301-43a26080-4ffc-11eb-8079-94f0cd751a39.gif)

**Comment by Regalis11** [comment]
I gave this a quick test but couldn't reproduce it, so it doesn't seem to be a consistent issue. Needs some more testing and debugging.

**Comment by Udrakan** [comment]
This has not happened to me in the latest unstable, not even once.
