### ISSUE TITLE
Another steering issue with ladders

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#4642]
Bots will drop from ladders when they follow a path like this (Kastrull):

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/256cedce-93d8-4531-8a01-b59e2ca7b5c0)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@7b627fd.

**Comment by Xeavas** [comment]
[0.1200.0.2] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
