### ISSUE TITLE
Battery charging docks always draw power

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4643]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Charging docks always draw 200 power even if battery cells inside them are fully charged or there aren't any cells in them.
Having multiple of those charging docks can put a significant passive load on power grid, especially compared to using standard submarine batteries which can recharge battery cells without any power cost whatsoever.

**Version**
v0.1200.0.1 Windows

**Additional information**
New diving suit locker and oxygen tank shelves have the same problem with drawing power even if they aren't refilling bottles

**Comment by subarotrauma** [comment]
I think that is intentional. Batteries lose power over time in real life too, even when not used.

**Comment by ignis05** [comment]
If you recharge cells in submarine battery its completely 100% free, it doesn't even drain the charge from the battery itself (I would assume the capacity difference is so huge between submarine battery and battery cell that the drain is not noticeable - makes sense from "realism" perspective). It just makes very little sense to me, that when it comes to recharging cells, the dedicated cell recharging equipment works worse than secondary function of submarine batteries in pretty much every way.
