### ISSUE TITLE
Suggestion - Restrict Reactor Power_Out pin to just 1 Wire

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4645]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Restrict Reactor Power_Out pin to just 1 Wire. Asking this because it's almost every new creator's mistake that causes their grid to overvolt.

**Version**
~0.1200.0.1

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/2601c1b036a746aefc7b5d787bc3f813c008a148

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
