### ISSUE TITLE
[Suggestion] Diving suits should take longer to equip.

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#4647]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Much like fertilizing or removing components, diving suits should take longer to equip by having a longer picking time.

**Steps To Reproduce**
Find diving suit, wait for relatively short progress bar before suit is equipped.

**Version**
All versions.

**Additional information**
Diving masks are basically useless when you can just walk around in a diving suit and easily put it on/take it off. It'd be nice to see diving masks used as something other than raw materials after deconstructing. It would feel more realistic if diving suits were more of a hassle to put on, and would overall make the game just a slight bit more difficult in stressful situations.

**Comment by subarotrauma** [comment]
I don't think diving masks are useless, u can have them in your inventory and you don't lose as much moving speed as with a diving suit.
But I don't mind having your suggestion added.
