### ISSUE TITLE
Mission Logbook always spawns in the same cabinet

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4649]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mission Logbook always spawns in the same cabinet

**Version**
~0.1200.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/327bfaf453f24c738fd80ce070bf394a6ad64704

**Comment by Rokvach** [comment]
Tested by using the same seed for multiple mission rounds, the cabinet the logbook spawned changed each time. Working correctly. Closing.
