### ISSUE TITLE
Easy way to kill everyone in a station with minimal resistance.

### ISSUE THREAD

**Issue by Veritius** [Regalis11/Barotrauma#4654]
I have searched the issue tracker to check if the issue has already been reported.

**Description**
Easy way to kill everyone in a station (and loot all their stuff) without being hit once.

**Steps To Reproduce**
Go to any station, preferably a military outpost for maximum profit.
Incapacitate and handcuff security and other threats. Killing is not recommended due to security response.
Incapacitate and handcuff reactor room staff. Get an oxygen mask or dive suit (and a few extra tanks)
Remove reactor rods from reactor. Oxygen machine shuts down and oxygen will slowly lower.
Wait in submarine or nearby for every station crewmember to perish.
Station crewmembers will never fight back if this is executed well, and only one person (which you should have incapacitated) can replace the rods.

**Version**
v0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)

**Comment by Regalis11** [comment]
No longer possible in the latest unstable version (see https://github.com/Regalis11/Barotrauma/issues/4126)
