### ISSUE TITLE
Bots don't follow the Wait order inside ruins

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4655]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you use the wait command outside the sub after follow, the Bot kind of just keep swimming in the same direction with the same momentum.

[Gif](https://cdn.discordapp.com/attachments/668819422919524352/796735434893426726/BotWait.gif)

**Steps To Reproduce**
[Save.zip](https://github.com/Regalis11/Barotrauma/files/5781967/Save.zip) used in this example.
1. Give bot command to Wait and Follow to add them into their history.
2. Click the command to have them follow you say inside the ruin found in the save.
3. Click the command to have them wait while they're in the middle of following you.

**Version**
~0.1200.0.1

**Comment by Kaillera** [comment]
Actually even though I had given my bot an order to wait in the Sub ages ago and controlled him to get inside a ruin, he'll start trying to swim towards the sub even with an active Wait command.

**Comment by Rokvach** [comment]
I wonder if the wait orders position persists in the history, so when you toggle the wait order back on from the order history it will use the old position instead of assign a new position for the bot to wait. But might not be the case as I have a faint memory of using the wait order and the bot did stay in place then.

**Comment by ekqvist** [comment]
> I wonder if the wait orders position persists in the history

In code, the "regular" wait order should basically make the bot attempt to move to the position where they are themselves, making them stay still. The contextual version of the order should target the position originally targeted with the order.

Needs some additional debugging to see what's going on.

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@4541382. There was a bug that the character wasn't allowed to go outside while completing the objective of waiting when ordered to wait inside a ruin. This caused the objective priority to drop to 0 and made them act on the idle objective instead.

**Comment by Xeavas** [comment]
[0.1200.0.2] - Unable to replicate 👍 

Testing methods :
1. Use save provided
2. Replicate in 0.1200.0.1 with provided methods
3. Attempt to replicate in 0.1200.0.2 with provided methods

**Comment by Rokvach** [comment]
Closing
