### ISSUE TITLE
[0.1200.0.1] Trying to switch ammo stack when inventory is full using stacks greater than ammo capacity gives error + narnia'd item.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4656]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I tried putting 8 Ahab Spears into a Harpoon Gun with 5 Harpoons while my inventory was practically full.

![Capture](https://user-images.githubusercontent.com/5086682/103909515-cd702d80-50d1-11eb-98f8-d9f65cbc9efc.PNG)

6 Ahab Spears gets put into the gun, but I only got 4 Harpoon swapped slots with it. 1 Harpoon and 3 Ahab Spears get Narnia'd.

**Version**
~0.1200.0.1

**Comment by Kaillera** [comment]
[111.txt](https://github.com/Regalis11/Barotrauma/files/5789231/111.txt)

Somehow I forgot to add the dump.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4aff61338037035c77624a13a34fef907392399

**Comment by Rokvach** [comment]
Was the change so you can't swap the items if you try to swap with a stack that is bigger than the allowed maximum stack size for the item?

I am trying to swap x4 Harpoons in Harpoon Gun with x7 Explosive Harpoon but I can't swap them, only if I make the Explosive Harpoon stack to be x4 I am able to swap. This feels like it leads to a bit too micromanagement of stack sizes you have

But this does raise a question should you be able to stack those items which goes inside a specific item only to that maximum stack size that is allowed? So for example, only being able to stack harpoons up to x4, same with medicine in syringe gun

**Comment by Rokvach** [comment]
I guess we can go with this way of handling the issue first and then see if we get some feedback about it from the community. Closing.
