### ISSUE TITLE
Suggestion - Plant Scanner

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4663]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We can see minerals now, why not plants?

**Comment by Regalis11** [comment]
Thank you for the request!
We are only using the issue tracker for reports about bugs and issues. Please post feature requests and ideas on Barotrauma's [GitHub discussion board](https://github.com/Regalis11/Barotrauma/discussions).
