### ISSUE TITLE
Mudraptor Shell Item Spawns Outside of Mudraptors Inventory

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4664]
[Bug, Oversight]
When the mudraptors have their inventory loot tables selected, it seems that the ones who have the shell loot table selected aren't actually able to carry around the shell with them, probably because of item tag related reasons.
![image](https://user-images.githubusercontent.com/47284081/103974783-71a5b300-516a-11eb-90e7-ee353f190520.png)
you can replicate this by manually spawning in mudraptor after mudraptor until you get the shell loot table. This explains why nobody ever seems to find shells in the mudraptors; Presumably there are a bunch of mudraptor shells lying all over the ocean floor of europa.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd3a6a7df7df2cf00043a911738a41c21898dc9d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
