### ISSUE TITLE
Button not resetting

### ISSUE THREAD

**Issue by dLantee** [Regalis11/Barotrauma#4665]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems by default ("state" and "toggle" are off) when the simple "press button" is pressed, provides signal "1" and never resets. The signal stuck. Based on the wiki it supposed to reset after 0.02 sec.
When we set "state" attribute we get the same behavior.

**Steps To Reproduce**
I just created a simple press button and connected to display text item.

**Version**
Windows
v0.11.0.10

**Comment by Regalis11** [comment]
This is actually the intended behavior. The button sends a signal of "1" when pressed, but nothing else. So if you connect it to a text display, all it does is setting the text to "1" when you press it.
