### ISSUE TITLE
Crowbar open secure steel cabinet

### ISSUE THREAD

**Issue by Veritius** [Regalis11/Barotrauma#4667]
Simple as it sounds. Allow the crowbar to be used for forcibly opening secure steel cabinets.
It'd have to take a while, due to the fact something quite valuable and/or dangerous is probably being stored inside.
The same with the toxin cabinet, as well.

Additionally, make it an option that is enabled by default, named "Allow crowbar to open container" that toggles this functionality on a per-cabinet basis.

**Comment by Regalis11** [comment]
Thank you for the request!
We are only using the issue tracker for reports about bugs and issues. Please post feature requests and ideas on Barotrauma's [GitHub discussion board](https://github.com/Regalis11/Barotrauma/discussions).
