### ISSUE TITLE
[Bug][Sub Editor] Texture offset does not work properly at texture scales larger than 1

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#4677]
- [:heart:] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Setting the texture offset on structures with an increased texture scale will cause unexpected behaviour. There will be jumps in the offset which make it impossible to have certain parts of the sprite in view. 
Additionally, mirroring a sprite does not preserve the texture offset, making the problem more apparent on mirrored sprites.
 
**Steps To Reproduce**
Place a structure in the sub editor. Increase the texture scale (something like [5, 5] the larger the sprite the more noticable the bug is). Increase one of the texture offsets. There will be periodic jumps in the offset. 

**Additional information**
Fixing this bug will have major reverse compatibility issues. It will certainly break many existing subs containing decorations built with scaled structures. If the fix doesn't include some tool to fix scales on existing subs I'd rather not see it fixed at all. :)

 **Version**
Any version up to v0.1200.0.1

**Comment by karaolidis** [comment]
I think this is related to #11540 too. As far as reverse-compatibility goes, isn't it the case that existing subs with this issue break in PvP mode?

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/64bb4c47ac7bd94890ee1f34012748b0ecf1a974.
