### ISSUE TITLE
Save file corruption and disconnect

### ISSUE THREAD

**Issue by dlc2006** [Regalis11/Barotrauma#4679]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crashing upon having more than 3 players in game.

**Steps To Reproduce**
Any time we have more than 3 players online and sometimes even then - people will crash with error messages as seen in the screenshots. Posted about it on twitter and was directed here. Save file attached.

**Version**
Windows -- Latest Steam Version (Up to date)

**Additional information**
Using Vengeance Sub with Shuttle - Equipped... https://steamcommunity.com/sharedfiles/filedetails/?id=2121725686 and also using Calic's Storage Containers https://steamcommunity.com/sharedfiles/filedetails/?id=2299240718

Screenshots: https://imgur.com/a/PkrOTm9

Save File: 
[Game Saves.zip](https://github.com/Regalis11/Barotrauma/files/5789696/Game.Saves.zip)

**Comment by Regalis11** [comment]
Hello again, and thanks for the save file!

This seems to be related to an issue we fixed earlier (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/52ac7ea0): the save file has somehow gotten corrupted, causing the game to think the submarine is located at an uninhabited location, which should not be possible to actually enter like outpost levels. This should be fixed for the update.

I manually modified your save file to move the submarine back to a valid location, you could give this file a try:
[Carlos Super RV Take 3.zip](https://github.com/Regalis11/Barotrauma/files/5794497/Carlos.Super.RV.Take.3.zip)

**Comment by Rokvach** [comment]
Tested, I was able to load the save file without any issues. Working correctly, closing.
