### ISSUE TITLE
Husk spawned ontop of me

### ISSUE THREAD

**Issue by Neko-LoverDisc** [Regalis11/Barotrauma#4681]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had cleared out a shipwreck, brought back a crate to loot the shipwreck. As I was looting, I had a husk literally spawn ontop of me. I had already cleared out the sub, and the husk just magically existed with its face up my rear end

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
N/A Sadly.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Stable Linux
**Additional information**

**Comment by Regalis11** [comment]
I'm afraid this might be impossible to reproduce, but let's keep an eye out for this
