### ISSUE TITLE
Game Crash When StatusEffect Applied to Removed Limb

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4685]
You can apply statuseffects to characters that have been removed through things such as `delay="2.0"` (where the character is removed before the delay expires and the game tries to apply the status effect to nothing, usually a missing limb in the case of repairtools) or duration="1.0" (the duration keeps running the statuseffect after the character is removed anyway).
It results in the crashlog:
[crashreport (171).log](https://github.com/Regalis11/Barotrauma/files/5790235/crashreport.171.log)
[crashreport (172).log](https://github.com/Regalis11/Barotrauma/files/5790236/crashreport.172.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0c1f64b434d5d1ac8f25df34230227f4fcaf71f8

**Comment by Rokvach** [comment]
This hasn't caused any issues, so seems to be working. Closing.
