### ISSUE TITLE
Intense level music plays when inside a sub that's docked to outpost

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#4686]
**Description**
It would be nice doing inventory management to calm outpost music, instead of hearing relatively intense lvl music over and over.

**Steps To Reproduce**
-dock to outpost
-while in the outpost level, go to your submarine

**Version**
Stable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/48b5e26d3e945c06302976be547f75e15ce7c86e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
