### ISSUE TITLE
Multiple Status Tags Break Badly

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4689]
[High prio (threatens clown songs), Modding]
If status effects try to apply more than one status tag onto a character, it breaks in the sense that HasStatusTag seems to only recognize the first tag applied chronoligcally.
So for example, if you were to apply an active status tag with a long ongoing duration, then put on the clown mask afterwards, playing on a guitar would not give you the clown songs because for whatever reason HasStatusTag only checks the first status tag added for some reason.
This is a modding issue because i think the game doesn't use HasStatusTag for literally anything but the clown guitar check. But a lot of mods break the clown songs and wearing a clown mask can break a lot of mods.
REPRODUCE:
you can load up my mod, thalassophobia, turn on commands. giveaffliction "Explosive Diarrhea" 30 (this should apply a status tag). After this is applied, give yourself a clown mask, and try strumming on a guitar. the clown music won't play because the guitar is looking at the diarrhea status tag for some reason.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f5cd639f2c2b6fb105820bc373b21538f46d3eac

**Comment by Rokvach** [comment]
This hasn't caused any issues, so seems to be working. Closing.
