### ISSUE TITLE
Healing AI with Liquid Oxygenate causes AI to become aggressive and attack

### ISSUE THREAD

**Issue by Entelin** [Regalis11/Barotrauma#4697]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This was observed multiple times during a ballast flora.

**Version**
Windows / Steam Stable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16f4338af0c7fab856052bf645e132445f48de5f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
