### ISSUE TITLE
Infinite explosions by oxygen

### ISSUE THREAD

**Issue by sylvinite** [Regalis11/Barotrauma#470]
Setting an oxygen generator aflame with oxygen inside will cause an infinitely looping explosion to occur.
Typically exploded items are deleted (e.g. potassium) however this is not the case for the oxygen canisters.
Explosions will continue to occur until a point where it is literally impossible to join a server from the massive amount of information. Crew is also unable to do anything to resolve the situation

**Comment by BlueTheKing** [comment]
Fixed in #471

**Comment by Regalis11** [comment]
#471 feels more like a workaround than a fix to me, it does prevent infinite explosions but it still causes the explosions to go off continuously for several seconds. IMO a better solution would be to prevent the oxygen tanks from exploding if their condition is below a certain value. Doesn't make much sense that a 0.1% filled tank explodes as violently as a full one anyway.

**Comment by BlueTheKing** [comment]
Would adding a conditional to the oxygen tank explosion fix this? 
To add the scaling explosions in the xmls there would be a ton of conditionals, unless it can be done outside xmls more efficiently in which case i don't know how to add those.

**Comment by NilanthAnimosus** [comment]
I think having a conditional that causes the explosion is the best bet about this - but the condition should always be set to 0 even if that condition is not met if possible (Otherwise it would just result in an explosion every X time).
