### ISSUE TITLE
"Where no man has gone before" achievement not unlocking

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#4702]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The achievement for descending below 5000 meters doesn't unlock even if the sub gets that deep.

**Version**
v0.10.0.x

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91bc9dc82709c7acd1e437d88d71a62e87ad24fb

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
