### ISSUE TITLE
Bots can't shoot guns through turret bases

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4703]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots won't try to shoot coilgun through the turret base hitbox, even though the shots won't damage it or be blocked by it.
![image](https://user-images.githubusercontent.com/48099798/104174113-b6e61100-5406-11eb-8d5a-85c83318121d.png)
This makes coilgun+railgun setup like that one inoperable by the ai, they will aim at the enemies but never try to shoot them with the coilgun.

**Steps To Reproduce**
I've build a test setup which clearly shows how ai won't try to shoot through turret bases.
![image](https://user-images.githubusercontent.com/48099798/104176230-48558300-5407-11eb-983c-e0c44ec85755.png)
Just order bot to operate the coilgun and spawn a couple of crawlers in the area.
(I recommend enabling "maintain position" first or the shots will accelerate the sub and squash the crawlers against the wall)

**Version**
v0.1200.0.1 and prior

**Additional information**
Test setup I used:
[AI shooting test.zip](https://github.com/Regalis11/Barotrauma/files/5795416/AI.shooting.test.zip)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@9830a3d.

**Comment by ignis05** [comment]
Not able to reproduce in v0.1200.0.3

**Comment by Rokvach** [comment]
Closing.
