### ISSUE TITLE
Ice obstacles not fading into background after destroyed

### ISSUE THREAD

**Issue by Kulik242** [Regalis11/Barotrauma#4706]
The damage model of ice obstacles is really underwhelming for a physics based game and they can be surmounted very easily by a couple of coilgun shots. 

I propose the ice obstacles to be constituted by smaller ice blocks that can be shot, physics would apply for all blocks so the players have to think twice how to collapse the spire to not hurt themself, the sub or not block their passage by ice.

**Comment by Regalis11** [comment]
Thank you for the request!
We are only using the issue tracker for reports about bugs and issues. Please post feature requests and ideas on Barotrauma's [GitHub discussion board](https://github.com/Regalis11/Barotrauma/discussions).
