### ISSUE TITLE
Damaged save (singleplayer).

### ISSUE THREAD

**Issue by Cafting** [Regalis11/Barotrauma#4709]
- [x]  I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the single player campaign, I completed the mission, after docking to the desired outpost, the game crashed. When loading this save, my console pops up with errors.
![image](https://user-images.githubusercontent.com/77291209/104215649-a74ce380-546b-11eb-8598-ddbc6e6e00ad.png)
![image](https://user-images.githubusercontent.com/77291209/104215743-c77ca280-546b-11eb-8058-82ed648599cf.png)

**Steps To Reproduce**
1. Docked at the outpost.
2. The game crashed when loading an outpost.
![image](https://user-images.githubusercontent.com/77291209/104216282-6ef9d500-546c-11eb-9036-b4b6dee1f067.png)
3. After restarting the game, I can not load the save, after loading the console crashes (in the description).

**Version**
Version 0.11.0.10 - Windows 8.1

**Additional information**
My save:
[Poop.zip](https://github.com/Regalis11/Barotrauma/files/5797403/Poop.zip)
Error log:
[crashreportlog.txt](https://github.com/Regalis11/Barotrauma/files/5797411/crashreportlog.txt)
The submarine I used:
[Sweet Pea.zip](https://github.com/Regalis11/Barotrauma/files/5797419/Sweet.Pea.zip)
 
**P.S.**
I used google translate because I don't know much English.

**Comment by Regalis11** [comment]
It looks like this was caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/4581. Until this fix is released, here's a patched save file that should allow you to continue the campaign without this error: 
[Poop.zip](https://github.com/Regalis11/Barotrauma/files/5797634/Poop.zip)

**Comment by Cafting** [comment]
Thank you very much for the fix, I hope this bug will be fixed in the next patch.
