### ISSUE TITLE
(UI Issue) Oscillator missing "Component" in its name

### ISSUE THREAD

**Issue by Saevon** [Regalis11/Barotrauma#4710]
- [x] I have searched the issue tracker to check if the issue has already been 

**Description**
When searching for circuit components, the easiest search is "comp" which removes things like batteries, chargers, lights, etc.  However the "Oscillator" is the only one inconsistently missing the suffix.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2dc773060462e73dc559bd420f2665f07080b007

**Comment by Rokvach** [comment]
No issues, closing.
