### ISSUE TITLE
Crash report happend often

### ISSUE THREAD

**Issue by Sonicalejado** [Regalis11/Barotrauma#4715]
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5798285/crashreport.log)
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was playing barotrauma with some mods the mods are listed in the crashing report that i sending,so i was driving my submarine "Slayer" i don't now if is a problem but there are maybe 15 or 20 idk right now and them when i was driving in  one speficly part of the map the game just crash it happend two time i did not tried more than this. the mission of the campaing that i was playing alone was to drive some clown suits do a place
 
**Steps To Reproduce**
Drive the submarine at any time the game will crash it happen 2 times 

**Version**
Windows 10 - Version 0.11.0.10

**Additional information**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5798315/crashreport.2.log)
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5798316/crashreport.log)
it is two crashes report from the both times that happen (sorry for my inglish i don't speak inglish)
#4117

**Comment by Regalis11** [comment]
This seems to be caused by the Xenomorph mod: the game fails to find the XML files for the Xeno and Facehugger characters. It could be a problem in the mod itself or perhaps a corrupted install of the mod. I would recommend reinstalling the mod, and if that doesn't help, uninstalling it completely.
