### ISSUE TITLE
Oxygen tank shelves don't refill bottles that have 0% condition

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4716]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bottles need to have at least 1% condition to be refilled in oxygen tank shelf or diving suit shelf. If bottle reaches 0% putting it in the shelf wont refill it. Refilling 0% bottles in oxygen generator works fine.

**Steps To Reproduce**
Place an oxygen bottle with 0% condition in powered oxygen tank shelf using sub editor.

**Version**
v0.1200.0.1 Windows

**Comment by itchyOwl** [comment]
Should be fixed in dev.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
