### ISSUE TITLE
Bots - When following players in/out of ruins, the bot struggles between staying and leaving the ruins

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4717]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots are following players in/out of ruins, the bot struggles between staying and leaving the ruins. You can see them go inward/outward through holes that were made by plasma cutters or at the entrance of ruins (Even worst when the main entrance and vault entrance are pretty much near eachother).

**Steps To Reproduce**
1. Have bots follow you.
2. Go inside the ruin.
 a. Enter via cutting a hole with a plasma cutter
 b. Enter via main/vault entrances.
3. Let the bot enter the ruin with you.
4. Exit the ruin.

**Version**
~0.1200.0.1

**Comment by itchyOwl** [comment]
It's because there's no waypoints in the ruins.

**Comment by itchyOwl** [comment]
Actually there's also something else too.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@f33a941.

We should probably also add waypoints to the ruins, but that's a bit more to do.

**Comment by Xeavas** [comment]
[v0.1300.0.3] - After some testing between v0.1300.0.3 and v0.1300.0.2, bots seem to have less/no trouble going in and out of gaps (walls, in ruins) in 0.3 than 0.2 so I think the fix f33a941 in that context is effective.  👍

**Comment by Rokvach** [comment]
Closing
