### ISSUE TITLE
[unstable] Oxygen tank shelves can refill welding fuel

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4718]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Placing partially used welding fuel tank in powered oxygen tank shelf (big or small variant) will refill welding fuel.

**Steps To Reproduce**
Just make sure that welding fuel condition is higher than 0% (#4716 )

**Version**
v0.1200.0.1 Windows

**Additional information**
Putting welding fuel tank in a diving suit and the diving suit in a powered diving suit locker won't refill the welding fuel.

**Comment by itchyOwl** [comment]
Should be fixed in dev.

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
