### ISSUE TITLE
Connectionpanels don't work with kinematicbodies

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4719]
[Issue]
I swear I already made this one but i can't find my old issue so sorry if this is a duplicate.
The game automatically rejects anything with a physicsbody having a connectionpanel. This shouldn't apply if it has a kinematicbody, since items with kinematic bodies stay in place regardless.

**Comment by Regalis11** [comment]
We moved the ticket to our private repo (https://github.com/Regalis11/Barotrauma-development/issues/2302) because it's technically a feature request, closing this one.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/4a59b931ae9d46d0387953d71d7c43acf09dc521
