### ISSUE TITLE
Issue in barotrauma when trying to load a submarine I made on my server

### ISSUE THREAD

**Issue by Isy232** [Regalis11/Barotrauma#472]
Serverside there don't seem to be any issues, however players loading up the sub for the first time get these errors:

https://cdn.discordapp.com/attachments/419192460909215756/467338703816359936/unknown.png

It causes them to be unable to load the sub correctly until they rejoin the server, after that it seems to work fine.

Sub in question:
[Sub.zip](https://github.com/Regalis11/Barotrauma/files/2193091/Sub.zip)

**Comment by NilanthAnimosus** [comment]
I think I remember a possible cause of this issue - submarines can be saved with illegal characters in their name, I also recall certain characters would interrupt the download yet work on a rejoin.

Perhaps there are other issues but right off the bat this submarine contains two . 's

**Comment by Regalis11** [comment]
I could not reproduce the issue. The error message seems to imply that it's caused by the respawn shuttle instead of the main sub, do you know which shuttle was selected when this happened?

**Comment by NilanthAnimosus** [comment]
if I recall correctly this bug went as such.
A server could have the relevant submarine files and it would run fine.
A client having the relevant submarine files would also join fine
If a client was missing the files - it would download them but not seem to add them to the submarine list / fail to load the submarine. 
A rejoin seems to add the submarine to the list properly.

I'll see if I can reproduce it myself later.

Additionally, the topmost line despite the error indicates this likely is the main submarine failing:
(Shared - Gamesession.cs - startround)
```csharp
if (submarine == null)
            {
                DebugConsole.ThrowError("Couldn't start game session, submarine not selected");
                return;
            }
```

Its an issue on the clientside on their first join when missing submarine files with unusual names, I'll see if I can get a name that reproduces this though.

**Comment by NilanthAnimosus** [comment]
As a note in both sides I have used my mod, but the handling of this code should be vanilla.

I have just done a test of the above and this was the result between my two clients:

![](http://puu.sh/AXmDP/47fa4168ae.jpg)

Essentially, the left side is the joining client who does not have the submarine files.
The right side is the server host (Running a client-hosted version)
The client has accepted both downloads - but neither list has selected that submarine contained in the subs.zip

The host starts the game fine, the client fails to load the game with the error in Isy's image.

**Comment by Regalis11** [comment]
Ah yeah, I found the problem now. The clients initialized a new submarine and assigned GetFileNameWithoutExtension(filePath) as the name of the sub. The file path didn't have the .sub extension, so .IV was considered the extension and stripped out. Thanks for the debugging help once again!
