### ISSUE TITLE
Reactor goes critical once it stops recieving a negative value

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4729]
- [sorta] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1) After the orca's reactor's set_fission rate went from a negative value (example -0.1) to no signal, the reactor sets itself on fire and eventually melts down comedically.

**Steps To Reproduce**
1. implement a circuit based reactor control
2 .set the fission rate to negative
3. disconnect the set_fission wire
4. wait for reactor to go critical... while the temperature is still low!

**Version**
0.11 stable windows 10

**Additional information**
It was kind of funny, It was kind of sad.

Video demonstration attached.
https://user-images.githubusercontent.com/5103517/104406807-24409180-552e-11eb-92e9-d51851f52a6b.mp4

**Comment by Tsunder** [comment]
save file of video

[AAA.zip](https://github.com/Regalis11/Barotrauma/files/5806390/AAA.zip)

**Comment by Tsunder** [comment]
pulling off both fission and turbine rate showed the reactor's fission sliding up to max
hooking up the output of the componnent setting fission rate to a text display did not reveal any unusual outputs

**Comment by Tsunder** [comment]
somehow, removing the output (in this video, by removing an input, stopping the circuit from completing), the fission rate jumps to a very high number, yet the turbine rate does not change.

https://user-images.githubusercontent.com/5103517/104409190-b72ffa80-5533-11eb-867c-ddc096937176.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4da31c2b587a537df36a40eefa190bad9de9befb

**Comment by Rokvach** [comment]
Tested by doing the exact same thing as shown on the video, the reactor doesn't go critical so seems to be working correctly. Closing.
