### ISSUE TITLE
Inconsistency with Death-By-Calyxanide for husks and humanhusks

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#4737]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Depending on how you deliver calyxanide to a husk, or human husk, they take organ damage different ways. I have tested a syringe gun and then a melee attack with calyxanide on a husk. 

Only the syringe gun seems to trigger the organ damage in a husk (Fig. 1)

Applying calyxanide via melee does not harm the husk (Fig. 2)

Vice versa, the syringe gun does not work on a humanhusk. Only applying it like any other medication works
Syringe gun with calyxanide leaves the humanhusk unharmed (Fig. 3)

Applying calyxanide via melee triggers the organ damage (Fig. 4)

**Steps To Reproduce**
I spawned a medical HUD in, as well as a regular husk and giving an NPC affliction "husk infection 100". I let them turn into a humanhusk from there. Then, spawn in some calyxanide and attempt to inject the subjects by both melee and syringe gun

**Version**
v.0.11.0.10

 Fig. 1 and Fig. 2
![image](https://user-images.githubusercontent.com/63509011/104476846-9493f500-55b8-11eb-8d34-ea7d3012a62b.png)
![image](https://user-images.githubusercontent.com/63509011/104476948-ae353c80-55b8-11eb-8fbc-139d665cbe7a.png)

Fig. 3 and Fig. 4
![image](https://user-images.githubusercontent.com/63509011/104477286-d2911900-55b8-11eb-8be0-25192363c2c0.png)
![image](https://user-images.githubusercontent.com/63509011/104477668-4b907080-55b9-11eb-9025-7e2bbf95f2a9.png)

**Comment by Rokvach** [comment]
Tested, only Human Husk takes organ damage from Calyxanide in both methods while Husk doesn't

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
