### ISSUE TITLE
Character variants: Add support for overriding the animations

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#4741]
We need this mainly because scaling is not taken into account in many animation parameters and forces. And changing that would break all the existing characters, so let's not do that.

Instead allow to override entire animation definitions, like CrawlerWalk.xml.

**Comment by itchyOwl** [comment]
Also spotted a serious issue in the movement speed implementation.

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-development@5fefff9.

**Comment by Rokvach** [comment]
Tested, no issues, closing.
