### ISSUE TITLE
Relay components will toggle when receiving a "0" signal

### ISSUE THREAD

**Issue by ReconDoge** [Regalis11/Barotrauma#4749]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the "toggle_state" pin on a relay component is connected the the "signal_out" pin of a regex component with a certain expression set, the relay component will toggle its state regardless of what signal is passed into the regex component. E.g. a regex component with the expression "spaghetti" will still toggle the relay component when the phrase "sijefakj" is inputted.

**Steps To Reproduce**
1. Connect "toggle state" on a relay component to the "signal out" pin on a regex component. Ensure "continuous output" property on the regex component is disabled.  
2. Connect "signal in" pin on the regex component to the "signal out" pin on a wifi component.
3. Set an expression for the regex component.
4. Set "link to chat" property on wifi component to true.
5. Type any random phrase into the chat that does not match the set expression in the regex.

**Version**
Windows V0.10.0.9

**Comment by Regalis11** [comment]
Thank you for the report! This didn't seem to be related to regex components, the problem was that any received signal would toggle the relay, even though most other items ignore a "0" signal. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/323770fc843f126153023d7ee44fec8b824875aa

**Comment by Xeavas** [comment]
[0.1200.0.2] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing.
