### ISSUE TITLE
Clean Up Order is broken

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4757]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots do nothing under the Clean Up order. They clean up just fine in Idle.

**Version**
~0.1200.0.1

**Additional Informations**
Contextual works fine, but not the general order.

**Comment by ekqvist** [comment]
@itchyOwl already fixed in Regalis11/Barotrauma-development@04087dc?

**Comment by itchyOwl** [comment]
Yeah, and it was based on Kaillera's report on Discord. Good to have a ticket about it here too!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
