### ISSUE TITLE
[Unstable] Recipes with partial ingredient condition usage conflicting with inventory stacking behavior ?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4759]
**Unstable v0.1200.0.1**

Fabrication and deconstruction parameters for items do not seem to work correctly when using multiple entries of the same ingredient but with different use-condition / copy-condition / out-condition settings. It seems to prioritize only the first condition and then just duplicate it for all following entries.

In this example, the game will try to stack 2 full steel bars into one slot to craft the item, and give you a stack of 2 steel bars from deconstructing it.
```
<Deconstruct time="1">
  <Item identifier="steel" />
  <Item identifier="steel" outcondition="0.5" />
</Deconstruct>
<Fabricate suitablefabricators="fabricator" requiredtime="1">
  <RequiredItem identifier="steel" />
  <RequiredItem identifier="steel" mincondition="0.5" usecondition="true" />
</Fabricate>
```
If the orders are swapped so the half-item is first, the recipe will show two half-bars of steel and use half the condition of both of them (due to how fabricator inventory handling works now it immediately merges these two halves into 1 remaining bar)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa8a47f55703a5a5c8db320cbcea26626b1f3d0d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
