### ISSUE TITLE
[Unstable] [Modded] Creature variants of husked monsters crash the game when spawned.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4764]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a variant of a monster which has "husk" set to true is spawned, the game will crash.
For example, the husked crawler is a creature that has the variable "husk" set to true, and if we were to create a variant of it, like a "husked swarm crawler" and try to spawn it in, it simply will crash the game.

**Steps To Reproduce**
1) Enable a mod that adds a creature variant of a husked monster
2) Attempt to spawn said variant in the game.

**Version**
V.1200.0.2  - Unstable Branch. OS: Windows 10.

**Comment by Regalis11** [comment]
Error message:
![image](https://user-images.githubusercontent.com/14351070/104814527-1afa4200-5818-11eb-88fb-c0da9ffdbfde.png)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma@5b440cd.

**Comment by Emanthealmighty** [comment]
The game no longer crashes as of version 0.1200.0.3 when spawning variants of husked monsters.

**Comment by Rokvach** [comment]
Closing
