### ISSUE TITLE
[Unstable] Crawler Hatchling doesn't use its custom texture.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4765]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The crawler hatchling has a custom texture found in the files, however the one in the game will use the normal crawler textures

**Steps To Reproduce**
1) Spawn a crawler hatchling

**Version**
v0.1200.0.2 - Unstable Branch. OS: Windows 10.

**Additional information**
I know that the crawler hatchling does not really ever spawn, but there's always the possibility of someone with console permissions spawning them in, so it feels like a waste to not make them use their custom textures.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4cdbaef36d861238bb59eba15701ced18bf0f00

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
