### ISSUE TITLE
[Unstable] Mudraptor hatchling - Small change to texture

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#4767]
**Description**
The new mudraptor hatchling appears too much like a smaller mudraptor with a bloodier texture right now, and less of a baby. I think part of the problem is the size of the tail. I would suggest lobbing off about 60% of it and making it stubbier, like so. The crawler hatchling, if it's ever finished, could benefit from some similar changes

**Version**
v0.1200.0.2

Sort of like a duck tail
![image](https://user-images.githubusercontent.com/63509011/104752376-7fe96580-574e-11eb-9231-9dfd811687b2.png)

Current appearance. Appears much too long
![image](https://user-images.githubusercontent.com/63509011/104752470-9db6ca80-574e-11eb-9e28-1a6eba44d7e5.png)

**Comment by Regalis11** [comment]
Thanks for the suggestion! We've relayed this to our art team, but I'll close the ticket, because we now only use the issue tracker for bugs, while ideas/suggestions should go in the [discussions](https://github.com/Regalis11/Barotrauma/discussions).
