### ISSUE TITLE
[0.1200.0.2] Multiplayer - Missing Cave Entrance Blip for Nest Missions

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4771]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cave entrance blip for nest missions does not appear in Multiplayer.

**Version**
0.1200.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d797d7ba1962f0b9b549f5ec75dfb52573dc4618

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
