### ISSUE TITLE
[Unstable 0.1200.0.2] - Crates Spawn with Storage Containers

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#4788]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crates spawn with storage containers when you purchase them from the vendor in Campaign mode, or when you add additional cargo in Mission mode

**Steps To Reproduce**
In Campaign Mode:
1) Purchase storage containers from vendor.
2) Start round

In Mission Mode:
1) Got to "Settings>Gameplay>Additional Cargo" and add storage containers
2) Start round

The number of crates = the number of storage containers

**Version**
Unstable version 0.1200.0.2. Windows 10 (64 bit)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6c28719682da04ef2ebb6426db83493e3849574

**Comment by Rokvach** [comment]
No issues, closing.
