### ISSUE TITLE
Can't add any linked submarines

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4791]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Adding a shuttle to the main submarine through the menu on top middle isn't working. It appears that the shuttle has been added normally, but when entering the test mode, errors will appear in console and the linked submarine will be removed. Saving .sub file with newly added linked submarine will throw errors whenever that .sub file is loaded in sub editor on in game.

**Steps To Reproduce**
1. Open any submarine in the editor.
2. Place any submarine as linked submarine.
3. Enter test mode
Errors will be thrown in the console, the linked submarine won't spawn and it will disappear when returning back to the sub editor.

**Version**
v0.1200.0.2 Windows

**Additional information**
Submarines which had shuttles added prior to this version work normally (unless you try to add a second shuttle to it).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6507900dcf9ecfa59cf07d05fba2212b235f9f66

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore. Working correctly, closing.
