### ISSUE TITLE
Unattached wire cannot be picked-up (sub-editor)

### ISSUE THREAD

**Issue by Saevon** [Regalis11/Barotrauma#4797]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If both ends of a wire are unattached. It cannot be picked up anymore.  Does not interact well with saves either.

**Steps To Reproduce**
 1. Create 2 components.
 2. Set a wire between then
 3. Unattach both ends from the terminals, leaving it floating in the Wire-Panel

TRY to double-click the wires in the main-editor… cannot pick them up

 4. Save the Game
 5. Quit and Reload the Save now

The wire forgets it was every hanging, and is now a "wire-item" on one of the ends

 1. Create a wire between 2 components
 2. Unattach one end
 3. Save & reload

Now the wire forgets it was unattached to one machine, not showing in the wiring Panel.

**Version**
OSX Catalina, v0.11.0.10, dc7157

**Additional information**
Reloading a save with one end unattached (but visible in the wiring-panel) forgets it was there.  So you cannot leave a wire "ready to attach for emergencies" in the sub-editor

**Comment by Regalis11** [comment]
This no longer seems to happen in the latest version

**Comment by Rokvach** [comment]
I haven't seen this happen for a while now, closing.

**Comment by llamerr** [comment]
@Rokvach This is still a problem, check this sub: https://steamcommunity.com/sharedfiles/filedetails/?id=2813956790
Check red power wire near engine. If I double click it's end nothing happens and I can't connect it back to engine.
![20220528224955_1](https://user-images.githubusercontent.com/1281970/170840873-947f6626-8b4d-4e3d-998f-7d5a16fb26a9.jpg)
