### ISSUE TITLE
Outpost buying prices do not seem to update after moving to another outpost

### ISSUE THREAD

**Issue by lifearoundfreaks** [Regalis11/Barotrauma#4803]
✅ I have searched the issue tracker to check if the issue has already been reported.

**Description**
Either buying price multipliers or prices themself do not update when you move to another location.

**What I did to get this effect**
- Loaded the game at a military outpost.
- Riot shotgun costs 441, as it should according to my reputation at that outpost. (0.9 multiplier)
- Travelled to a colony outpost.
- Riot shotgun costs the same, but it should cost around 600. (1.25 multiplier)
- Move back to a military outpost.
- It still costs 441.

**Version**
v0.11.0.10 (Windows).

**Additional information**
If you load the save at the location with an incorrect price, it then shows the correct price, which tells me that either prices or price multipliers are only loaded once and not updated after location change.

I did not notice the same behavior with sell prices, but may still be worth checking them too.

**Comment by ekqvist** [comment]
Thanks for the report! Was easy to reproduce with the steps provided. Should be fixed in Regalis11/Barotrauma-development@261033b.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
