### ISSUE TITLE
Strange difference between items depended on way the of spawning it

### ISSUE THREAD

**Issue by DeinococcusR** [Regalis11/Barotrauma#4825]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I added reload sounds to magazine based guns in my mod and ran into a strange thing while testing it. It works by the gun setting a specific scale to a slotted magazine with a very short delay. the sound plays only if the scale differs from that scale. The magazine resets the scale when not being slotted in the gun. Thus the sound only plays once. 

Somehow the guns behave differently depending on the way they are spawned in the level. When a weapon is spawned with a character or in a auto filled cabinet in the player sub everything works as normal. -when a weapon is spawned in a wreck or via console command the reload sound is played in a loop.

**Steps To Reproduce**
Active Mods: 
- Some custom subs ( I can tell you more if it's important)
- World War II - German Weapons, Equipment & Friends (my mod)

This example uses the MP-40(smg) but basically works the same for the other magazine based guns(P08, MG34, STG44, FG42) too.

I started the game as private multiplayer server with the Orca and 6 bots, difficulty 9%. 

In the weapons cabinet of the orca spawned one smg magazine and one smg with magazine slotted. So one smg and two smg mags in total. MP-40 is the smg.

I then spawned via console commands one additional smg and one additional smg magazine. If everything works correctly there should be a reload sound playing once when I slot a magazine into a gun. That's the setup.

What happened: I slotted the two smg magazines that came with the orca into my console spawned smg. -> the reload sound looped without stopping.

I slotted the smg magazine I spawned with the console into the console spawned smg and the sound played only once as it should

I slotted all three smg magazines in the smg spawned with the orca and all three only played the reload sound once as it should

Wreck spawned guns behave the same as console spawned guns. Played several rounds on my multiplayer server to test it.

It also happens with all the other magazine based weapons of the mod.

If you need more information feel free to ask. I'm also active in discord - modding. 

**Version**
v0.11.0.10  Windows 10

**Additional information**
Possible that there is a problem with the hastag conditional of the magazine which prevents that the mag resets the scale when slotted into a gun. 

[WW2Mod.zip](https://github.com/Regalis11/Barotrauma/files/5835335/WW2Mod.zip)

**Comment by DeinococcusR** [comment]
Just found out that thing behave differently if the gun spawns in Dugong's auto filled secure steel cabinet with or without a mag slotted. If the mag is already slotted everything works fine. If the guns spawns without a mag it bugs/plays the sound on loop

**Comment by Regalis11** [comment]
Potentially related:
https://github.com/Regalis11/Barotrauma/issues/2388, https://github.com/Regalis11/Barotrauma/issues/2847

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e88d843846c140cc6e7f1897e766faeacdec8267.

The issue seemed to be that the conditional that checked the parent item's tags didn't only check the Item object, but it's ItemComponents as well. The ItemComponents didn't have the "gun" tag (because they don't have tags in the first place), so the conditional would always succeed.

**Comment by Rokvach** [comment]
This can be tested in Unstable

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
