### ISSUE TITLE
[Unstable] [Modded] Variant multipliers do not work on variants of husked monsters.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4829]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a variant of a monster which has "husk" set to true is spawned, no matter what its multipliers are set to in the xml file, it will always have the same stats and size as the original one.

**Steps To Reproduce**
1) Enable a mod that adds a weaker/stronger and smaller/bigger creature variant of a husked monster
2) Spawn said variant in the game
3) Compare the size and strength of it with the original non-variant monster, notice how they're the same

**Version**
V.1200.0.3  - Unstable Branch. OS: Windows 10.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@a66faa2 by @Emanthemighty.

**Comment by Emanthealmighty** [comment]
Working properly as of v0.1500.2.0 (Unstable).
Creature variants of monsters that have "husk" set to true can properly be smaller / bigger and be stronger / weaker in terms of attack power depending on the variant's parameters.

**Comment by Rokvach** [comment]
Closing
