### ISSUE TITLE
[Unstable] Mainpath monster events spawn creatures too close to the submarine

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#4832]
**Description**
Sometimes way withing sonar range.

**Steps To Reproduce**
Have godmode AI crew submarine and make it go forward at about 20km/h
Killmonsters command from time to time to make room for more spawns
Observe monster spawns

**Version**
Unstable

**Comment by Jasontti** [comment]
Tested.
Could not reproduce, when going full tilt on azimuth.
