### ISSUE TITLE
Traitor Mission "Easterbunny" Bugged

### ISSUE THREAD

**Issue by DeinococcusR** [Regalis11/Barotrauma#4838]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Easterbunny traitor mission is instantly lost after the mudraptor hatches, even if it's still alive. 

**Steps To Reproduce**
Start the traitor mission easterbunny and feed the mudraptor egg saline until it hatches.

**Version**
v0.11.0.10 stable. Windows 10

**Additional information**
Tested in private multiplayer server.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c91149951cbb36c79d52351d28ec15834f441c36

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
