### ISSUE TITLE
Losing Submarine Upgrades through docking shuttles without the parent submarine.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4839]
**Description**
You're able to lose submarine upgrades by docking without the parent submarine thus transferring existing upgrades to the shuttle, but upon recovering parent submarine through the outpost terminal, all upgrades will be lost as the shuttle isn't considered a submarine to the outpost terminal (neither should it be).

**Steps To Reproduce**
1. Upgrade the submarine which has shuttle (I used a modified Kastull that replaces its drone with the Selkie) 
2. Undock from the parent submarine and redock to the outpost with the shuttle
3. Observe the upgrade menu
4. Recover parent submarine through Outpost Terminal
5. Undock and redock to recover parent submarine
6. Observe the upgrade menu again

**Version :** [0.1200.0.3]

**Comment by Regalis11** [comment]
No longer an issue as of https://github.com/Regalis11/Barotrauma-development/issues/2644
