### ISSUE TITLE
[Unstable] Sub editor outpost save window resets locationtype to null everytime its opened

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#4841]
**Description**
![outpostsavebug](https://user-images.githubusercontent.com/59519434/105218184-21a8f200-5b55-11eb-88b1-7fee6bd59ef2.gif)
The 2nd time I open the save menu, it still says "City" but when I roll out the locationtype list, nothing is actually selected. If you use outpost module in outpost that has empty locationtype, it causes a crash, so we gotta doublecheck everytime we save outpost to re-select locationtype/locationtypes everytime.

**Steps To Reproduce**
-sub editor
-save your thing as outpost with some locationtype
-go to save menu again, change nothing, save
-decompress your .sub file and notice that locationtype=" "

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/398ae5ada493be43e7de2e8ce0b1aab8c93620a6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
