### ISSUE TITLE
[0.1200.0.3] - Bots can't swap oxygen tanks in this situation.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4842]
![o2swapbot](https://user-images.githubusercontent.com/72674994/105221060-8e42e180-5b93-11eb-8031-b6fc8e23657e.jpg)

**Comment by Rokvach** [comment]
Even players can't swap oxygen tanks in this situation, but they can drop the empty one which AI can't.

**Comment by Xeavas** [comment]
I can swap fine in this case by dragging it over the empty oxygen tank no?

**Comment by Rokvach** [comment]
Aa could be that it places the empty one in to your hand slot which normally doesn't happen if you don't have anything on your hand slot

**Comment by Xeavas** [comment]
[0.12.0.0] (Release Build), Unable to replicate, seems like the issue was only present in .12.0.3 (unstable), Thus closing issue.
