### ISSUE TITLE
[Unstable] Mission Cargo items in stacks unnecessarily gave more crates

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4850]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mission Cargo items in stacks unnecessarily gave more crates. For instance: Medical Transport. It gives you 8 different types of items of 5 in a stack, which is 40 items, but it gives you 2 crates for 8 slots worth of items with plenty of rooms left over.

**Version**
~0.1200.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60411c778c03759a84afa6ef65344e832b11fdd5

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
