### ISSUE TITLE
[0.1200.0.3] Option to turn off the Watson Concoction effect when diving?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4851]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Please let us turn off this effect. It's super nauseating.

https://cdn.discordapp.com/attachments/668819422919524352/801803697939021864/2021-01-21_08-20-58.mp4

**Version**
0.1200.0.3

**Comment by Xeavas** [comment]
I recommend a rework, tried it out and it isn't pleasant to the eyes at all, and the effect is applied widely regardless of how near you're to one of those shrooms.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/4cf9aa88ec19f902e08e59b243542409b27ea3d3. The effect has also been dialed down a bit.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
