### ISSUE TITLE
Character variants have no inventories

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#4853]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crawlers from the Kill a Swarm Mission don't have any inventory slots when searched

**Steps To Reproduce**
- Select Kill a Swarm mission
- Kill crawlers
- try to loot the crawlers from the mission

**Version**
Unstable 1200.0.3, revision a8aa61912d
Windows 10, 64 bit

**Additional information**
Screenshot of 2 different crawlers from the swarm.
![20210121102443_1](https://user-images.githubusercontent.com/58775950/105364748-e699d380-5bd3-11eb-9713-5c8a799ca56d.jpg)
![20210121102502_1](https://user-images.githubusercontent.com/58775950/105364764-eac5f100-5bd3-11eb-8575-808fedaa7c11.jpg)
I searched all of them. They were all the same.

**Comment by mrjpjr** [comment]
Update:
Just did the Moloch mission.
Same thing. No inventory slots

![20210121120741_1](https://user-images.githubusercontent.com/58775950/105390985-06d78b80-5bf0-11eb-9989-5c641cb68724.jpg)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@018ceae. Also included on the release branch.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
