### ISSUE TITLE
[Unstable 12.0.3] Unable to access the Medical Cabinet while in the Health window

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#4854]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Medical cabinet cannot be open at the same time as a Character's Health window.
One window will close when you try to open the other.

**Steps To Reproduce**
- Open Health window
- Open Medical cabinet

The health window will close. The same thing happens if you try to open the Medical cabinet first.

**Version**
Unstable 1200.0.3, revision a8aa61912d

**Additional information**
I did a quick check with a supply cabinet, and the same thing happened.

**Comment by Regalis11** [comment]
This is technically not a bug: opening the health interface deselcts any items/devices you've selected.
