### ISSUE TITLE
Crawler husk attempts to spawn with three items when it only has two inventory slots

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4855]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The crawler husk has an inventory of commonness 1 that contains three items, however the monster itself only has two inventory slots.
`  <Inventory slots="Any, Any" accessiblewhenalive="False" commonness="1">
    <Item identifier="alienblood" />
    <Item identifier="huskeggs"/>
    <Item identifier="huskstinger"/>
  </Inventory>`

**Version**
Version: 0.11.0.10 - Public Branch. OS: Windows 10.

**Additional information**
For this to be fixed, the options would be to either remove one item from the commonness 1 inventory, or increase the inventory slots to three, however, that last option would cause [this issue](https://github.com/Regalis11/Barotrauma/issues/4856) when a crawler turns into a husk and it spawns with the commonness 1 inventory.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/47d156329a225bedf5a488df0bdfaa0ee9e3faaa

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
