### ISSUE TITLE
[Modded] Error when transferring inventory items to husk monster when inventory sizes don't match

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4856]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At the moment if a monster has an inventory and transforms into a husk, its items will be carried over to the husked monster.
If the husked monster also has an inventory of its own, it will try to add them to the inventory which has the items that were carried over by the non-husk monster. 
If the inventory is already full, the new items will spawn on the ground.

**If a monster that has an inventory transforms into a husk and has more or less inventory slots than the husked version, the game will throw an error.** This will not happen if one of them has no inventory at all.

Expected outcome:
If the non-husk monster has less slots than the husked one, then the items should transfer over normally like described above.
If the non-husk monster has more slots than the husked one, then much like how any items the husked monster tries to spawn when the inventory is already full, the excess items from the non-husk monster should drop on the ground.

**Steps To Reproduce**
1) Spawn a monster that has an inventory (crawler, for example)
2) Make sure the husked version doesn't have the same inventory slots as the normal version.
3) Transform the monster into a husk 

**Version**
Version: 0.11.0.10 - Public Branch. OS: Windows 10.

**Comment by Emanthealmighty** [comment]
I tested this issue after removing the error, and everything seems to be working fine anyway, even if the inventories aren't transferred. Why does there _need_ to be an error that interrupts gameplay in the first place?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b42d3587af0baf65fa57b6b2abf2c5e433d01708. I decided to remove the error message altogether (not just for human characters). I think it was a remnant from back when the husk affliction was much less customizable and only usable on human characters, but it's no longer that necessary.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
