### ISSUE TITLE
Votekick-bans persist until server restart

### ISSUE THREAD

**Issue by sylvinite** [Regalis11/Barotrauma#486]
Temporary bans introduced by votekicking persist indefinitely, or more accurately until the server has been restarted (as the information is not permanently stored anywhere).

**Comment by Regalis11** [comment]
I wasn't able to reproduce this. The BanPlayer method seems to add the player to the banlist and save it as it should (line 106 in BanList.cs).

**Comment by sylvinite** [comment]
Closing this until I'm able to verify better

**Comment by NilanthAnimosus** [comment]
This is a problem of my mod.

My mod replaces the Autoban with a different path that doesn't ban the user for a duration - but instead adds a name change warning and a timed rejoin denial, configurable individually for command and votekick based causes.

The dedicatedserver of my mod however was missing the update loop for my mod which in turn caused all timers related to my mod not to count down (Including the votekick methods) as part of my main classes update loop.

Its been fixed but my current code is not ready just yet.

If any hosts are using it, Autoban will take effect if the setting "VoteKickDenyRejoinTimer" is under 1 second in the mods main settings file and Autoban is a positive value.
