### ISSUE TITLE
[0.1200.0.3] Bot shooting spire logic doesn't shoot when you're trying pull back or avoid but will still crash into it.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4860]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When your bots are on guns and see spires, they don't fire at the spires when you pull back on the engine/ballast. This will usually result in you crashing into the spire with the bots shooting the spire none to little.

I think the range of detection should be increased a lot more and the logic should be based on the velocity of the sub rather than if the pilot direction is still heading that way.

**Steps To Reproduce**
Drive about +12km/h toward an ice spire
Pull back before you run into them

**Version**
0.1200.0.3

**Comment by itchyOwl** [comment]
It is based on the velocity. I made some adjustments on it, which are included in the latest unstable. Test how you like it now.

**Comment by Rokvach** [comment]
Tested, didn't notice any issues, closing.
