### ISSUE TITLE
[0.1200.0.3] Navigation - Ice Spire Detected message doesn't get cleared

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4861]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was on automatic control for a bit and the ice spire detected message came up. I took manual control, but the message never went away even though there's no spires anywhere nearby left.

![Capture](https://user-images.githubusercontent.com/5086682/105429842-428a4980-5c20-11eb-8ea2-92bd108de049.PNG)

**Version**
0.1200.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/regalis11/barotrauma/issues/4861#event-4237407307

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
