### ISSUE TITLE
[Unstable] Using "editsubs" command during gameplay, all items in the subs are badly placed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4862]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using "editsubs" command during gameplay, all items in the subs are badly placed
![Capture](https://user-images.githubusercontent.com/5086682/105434413-89c90800-5c29-11eb-84fd-c15caedfce80.PNG)

**Version**
0.1200.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06ee5e778a994f40b85a7a7a852537606069edf0

**Comment by Rokvach** [comment]
Tested, I didn't spot any issues. Working correctly, closing.
