### ISSUE TITLE
Human Limb Layering Issues

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4865]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At random, a player's limbs begin merging into each other as if they are on the same layer, slowly affecting other players client-side as rounds go on, carrying over between campaign levels.

**(Possible) Steps To Reproduce**
1. Enable multiplayer/spawn multiple bots
2. Use a submarine with many layers..? (This submarine was used when the bug was spotted: [HGN Dugong.zip](https://github.com/Regalis11/Barotrauma/files/5856084/HGN.Dugong.zip), but I doubt it connects in some way).
3. Hopefully see your limbs merging into each other (the problem seems to slowly stack as other players client-side get affected).
![image](https://user-images.githubusercontent.com/72813628/105495231-ebb95a00-5c89-11eb-8d92-a2f1f2dffa06.png)
![image](https://user-images.githubusercontent.com/72813628/105495270-f96edf80-5c89-11eb-93e9-3f012ea55e81.png)

**Version**
Current Stable Release, Windows 10

**Additional information**
This bug is VERY unreliable and random in reproducing as after restarting, I was completely unable to recreate the bug.

**Comment by Ek-Videogames** [comment]
If this helps at all, from my experience this can happen from interacting with items with very deep sprite depth such as ladders / chairs / periscopes. Something like, the game moves the character into a very far sprite depth to the point that their limbs get crushed into the same Z constraints, and when you move back to layer 0.5 the game does not un-squish your limbs back to normal depth.
