### ISSUE TITLE
Cannot create a server, clients disconnecting

### ISSUE THREAD

**Issue by Chaos456456** [Regalis11/Barotrauma#487]
some people cant create server. AND while i start paly in server im left the game 
![image](https://user-images.githubusercontent.com/35542296/42841163-e1abffd8-8a11-11e8-96e0-e0f23d36ea2f.png)

**Comment by ZealanL** [comment]
This is an annoying problem I as a server owner have a lot. It seems that the server is giving players incorrect/no data about the in-game environment, causing them to desync and be kicked upon playing and spectating. This tends (for me at least) to have to do with switching around submarines.
