### ISSUE TITLE
[0.12.0.0] When bots are outside the sub and runs out of oxygen in the tank in their suit and while still having full tanks in their inventory, they ignore follow/wait command and tries to swim to the sub temporarily while changing their tank out.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4870]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots are outside the sub and runs out of oxygen in the tank in their suit and while still having full tanks in their inventory, they ignore follow/wait command and tries to swim to the sub temporarily while changing their tank out.

**Steps To Reproduce**
1. Have bot follow you outside the sub.
2. Give bot some oxygen tank.
3. Give their suit a empty oxygen tank or let it run out naturally.
4. They will now panic and swim back to the sub while changing out their oxygen tank, and won't stop until they finish doing so.

**Version**
0.12.0.0

**Comment by itchyOwl** [comment]
I couldn't repro this: the bots seem to wait until the oxygen has run out until swapping another tank. Swapping the tank shouldn't take more than a frame. I suppose the bot somehow was in the FindSafetyState. A screenshot with the debug infor would help.

But I found some issues with trying to swap the oxygen tanks. Related to this, see Regalis11/Barotrauma-development@220e02b, which should make the bots not to try to swap the oxygen tanks before they run out of them.

**Comment by Benzin73** [comment]
I too have encountered this issue several times on Current stable 0.11.0.10 - Windows 10 64bits.
The bot will say "I need an oxigen tank" and swim back to the sub, even though he has 3 of them in their inventory. 
Im not 100% sure, but i _think_ all times this has happened, the o2 tanks were in the bot´s utility belt. Not on his "normal" inventory.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
