### ISSUE TITLE
Kastrull and Azimuth Reactor Outputs default

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4871]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Kastrul and Azimuth both have 10 000kw reactors, while their usual maximum grid load is much lower, at ~4600kw and ~3000kw, approximately 50% and 30% of the reactor's maximum output. 
Compared to other submarines reactors which utilize about 90% to about 105% of the reactor output, this seems like an oversight.

**Version**
0.11 release

**Additional information**
The Azimuth's reactor is entirely default, with 20s fire and 120s meltdown.

**Comment by danielasteljoki** [comment]
Changed reactor values in b57879a.

**Comment by Rokvach** [comment]
Tested, no issues, closing.
