### ISSUE TITLE
Remora Oxygen Generator Linked to Hull

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4872]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the Oxygen Generator on the Remora is linked to command room's hull.

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/5103517/105546305-33aca100-5ccb-11eb-811a-f5a30f51036b.png)

**Version**
0.11 release

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7d9e7318ba104215e14bc5674866080b6ced8e7

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
