### ISSUE TITLE
Typhon's hulling makes some rooms undrainable

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4873]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some rooms in the typhon are unable to be drained due to the gaps being above the lowest point of the hull/ the hulls extending down past the gaps. The only way to drain these rooms would be plasma cutting the floor open. Some of the rooms aren't so lucky, as below them is the outside.

This essentially means there will permanently be water in the sub, altering its buoyancy.

Examples include: Crew Quarters (top left), Command Room (top right)
![image](https://user-images.githubusercontent.com/5103517/105547170-3a87e380-5ccc-11eb-984f-03398f1ff9e9.png)

![image](https://user-images.githubusercontent.com/5103517/105547233-470c3c00-5ccc-11eb-94ae-aff0d0c5f337.png)

**Version**
0.11 release

**Additional information**
There are some cases in various subs where the bilge systems water detectors aren't at the very bottom of the hull, in which case they should use water %_out instead of signal_out to fully detect water presence in the hull.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3958/commits/4682c3d562e62ab969475725c0f397feee26dcaa
