### ISSUE TITLE
wikiimage_sub - highlighted objects are yellow on the generated image

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#4878]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have a wall or a shell highlighted when using this command it will also be highlighted on the generated image.
Example of a highlighted wall:
![image](https://user-images.githubusercontent.com/48099798/105606762-80f84380-5d9b-11eb-89c2-00f34333e55b.png)

**Steps To Reproduce**
Open console and use the command while having a background wall highlighted - it will be highlighted on the generated image.

**Version**
v0.12.0.0 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d030f9449e1f3634eeb7bac1e683ebba614338c2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
