### ISSUE TITLE
Static Battery Power Draw

### ISSUE THREAD

**Issue by Aluvir** [Regalis11/Barotrauma#4880]
- I have searched the issue tracker to check if the issue has already been reported?
Yes, it is different than the infinite power via relays & batteries and other issues.

**Description**
If the load on a battery's output is greater than 1/10000 the input, the battery will draw its entire recharge rate from the input grid. If the discharge load is 1/10000 or less the recharge rate, the battery will not draw any power to recharge itself.

**Steps To Reproduce**
Create three of these: a reactor with 50000 kw output, wire it to a junction box , then a battery with charge 0, max charge 50k, recharge/discharge both at 50000 kw. Wire the battery's output to a junction box. Hook up one lamp to that junction box in each setup, with the first setup's lamp drawing 0.5kw (this does turn on, even though the junction reads this as zero load), the second's drawing 5kw, and the third's drawing 50w.

**Version**
Barotrauma v0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)

**Additional information**
The most significant impact it has on gameplay is when you are operating with normal equipment (500kw recharge on battery powering a simple 5kw lamp draws 500kw from the whole system) & using a battery buffer to smooth power spikes, but the overall effect is such that the reactor is almost always having to supply 100% of the battery's recharge rates even if the discharge is substantially less.
[Clown Command Ship (light).zip](https://github.com/Regalis11/Barotrauma/files/5860897/Clown.Command.Ship.light.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9f40d1996d2007d984da78d9408a7bc93a13afc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
