### ISSUE TITLE
[0.12.0.0] Strongest husk I've ever seen

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4881]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://youtu.be/E7nVrBHharg

**Version**
0.12.0.0

**Comment by Regalis11** [comment]
I'm not sure I understand what the issue is, the husk didn't get killed despite being squashed between the sub and the level?

**Comment by Kaillera** [comment]
He's able to shake the entire wreck. He also spawned wedge underneath the wreck instead of inside.

**Comment by Rokvach** [comment]
Is it possible to remove the impact shake from creatures on wrecks and other structures which are fairly well grounded?

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this. It shouldn't be possible for small creatures to do impact damage to the submarine (which includes this knockback effect and the sound): there's a mass threshold that's much higher than the mass of the husks. So I wonder if something else than the husk could've caused this.
