### ISSUE TITLE
[Modding] Custom type for music is unrecognizable by events.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4887]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When adding new music, you might want to give it a different "music type" than the already existing ones such as "monster, start, levelend, endround, wreck".  Doing so however will seemingly make it unrecognizable for events, even though the randomevents.xml says: `musictype               = a music tag that matches a value defined in the sound config (e.g. monster, deep, flooded, levelend, ruins...)`

From what I understand, there should be no reason to not be able to set the music type to something custom, so that it only plays in certain events, but it simply does not work. So if you add a new music file with a custom type, and then try to use that custom type tag in a random event, the music will simply not play.

**Version**
Version: 0.11.0.10 - Public Branch. OS: Windows 10.

**Comment by Regalis11** [comment]
Looks like the "music type" property hasn't actually even been implemented: all of the tags are hard-coded (for instance, the monster music plays whenever there's a monster nearby).
