### ISSUE TITLE
[Unstable] any (nearly) empty container will have the indicator animated 

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#4888]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seemingly any (nearly) empty container will have the indicator animated similar to how guns animate their bar when empty and in the selected slot. I've tested among others toolbelts, crates, storage containers and even headsets, all have the same effect.

**Steps To Reproduce**
spawn in a (nearly empty) container. In game, the container indicator will pulsate.

**Version**
Unstable v0.12.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dfb5640b74df97639d298e0b3267ca00ab352bc8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
