### ISSUE TITLE
Ban evasion through family sharing

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#4890]
[Meta, Griefing]
Apparently, family sharing is enabling a particularly notorious group of griefers to grief RP servers on a large scale. Supposedly, alt steam accounts can use family sharing with a legit purchased copy of the game, and resultingly have a different steam id while using the same copy of the game. It might be ideal if family sharing were disabled for barotrauma, if possible. While this isn't ideal it seems like a necessary step to counter ban evasion, which is apparently being used on a wide scale:
![image](https://user-images.githubusercontent.com/47284081/105652815-230a4f80-5eb2-11eb-8b14-53e73036dff2.png)
![image](https://user-images.githubusercontent.com/47284081/105652860-3fa68780-5eb2-11eb-9be7-559cf6f727c9.png)

**Comment by hubismal** [comment]
![image](https://user-images.githubusercontent.com/47284081/105653419-aed0ab80-5eb3-11eb-9de2-57604d8583f1.png)
Another report of the same issue.

**Comment by Regalis11** [comment]
TODO note: we can get the Steam ID of the user who owns the game from the OnValidateAuthTicketResponse callback, let's consider the client banned if the owner has been banned.

**Comment by hubismal** [comment]
What if the owner hasn't been banned but the clients keep getting banned using the owners game (which I think is what's happening in this scenario)? I assume you're implying that getting banned as a client using the owners game should also ban the owner (and everyone else who plays that copy of the game) from the server?

**Comment by juanjp600** [comment]
Should be addressed in https://github.com/Regalis11/Barotrauma-development/commit/faf5ba65a87817389ee59f082203a43d49560d99

**Comment by Rokvach** [comment]
First pass on testing, currently if owner gets banned all the alts are banned as well but doesn't work the other way around yet

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f1503faac00f38b7852b7f32ad5f850a7908994e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
