### ISSUE TITLE
Game updates to having Game Analytics default to true, skipping the request entirely

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#490]
Version 0.8.1.5

The update replaces the config.xml with one that contains senduserstatistics="true" - This effectively means the user of the game is not asked if they wish to have it active or not.

Additionally there is no ingame method to ever toggle it, making this a potentially unaware choice that most won't even know how to turn off.

**Comment by Regalis11** [comment]
Fix'd
