### ISSUE TITLE
Ignore Icon that was placed on an item on the floor does not get cleared if it gets consumed by pets

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4900]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ignore Icon that was placed on an item on the floor does not get cleared if it gets consumed by pets.

**Steps To Reproduce**
1. Put Saline on the floor
2. Contextual Order to ignore Saline
3. Let pet consume the Saline

**Version**
0.12.0.0

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@b4e7b5f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
