### ISSUE TITLE
[0.12.0.0] (Release Build) Partials doesn't automatically combine in the deconstructer

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4905]
**Steps To Reproduce**
Get 4 glowsticks, put it in the deconstructer and deconstruct them.
![glowdec](https://user-images.githubusercontent.com/72674994/105830797-e305b280-6000-11eb-836c-97f2ca2a05f0.jpg)

**Version** [v0.12.0.0] (Release Build)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2aec915d44d2be94b193c6a3915fd3fd66521770

**Comment by Rokvach** [comment]
Tested, another good QoL addition would be to stack the combined items automatically as well, currently they can cause overflow if you are deconstructing a lot of items which still has partials when deconstructed. But otherwise working correctly, so closing.
