### ISSUE TITLE
Curiosity regarding Game Analytics and code modifications

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#491]
With the addition of the new Game Analytics I am wondering how it should be treated in my/others mods as the behaviour of how the game is tends to change from server to server in my code pretty wildly (Such as characters not dying unless give in)

Assuming it is wanted to be left active in the code I am also wondering if there are any statistics specific to mods that may wish to be added (Such as if it is a vanilla or modded server, even if a simple value string is sent to record different copies of the game) or any other statistics.

I think around 1/3 to 1/2 of servers are using my mods code usually, and maybe 1/100th or less of clients.

My mod also handles crash reports a little differently and has different content in parts of it - hopefully this isn't a problem for whatever handles the crash reports?

**Comment by Regalis11** [comment]
I would appreciate it if you and other modders kept the statistics that are applicable to the mod (selected game mode, submarine, etc), but if any of the analytics stuff is causing trouble or hard to adapt to your code, you're free to remove it. In your case for example you could leave out sending information about causes of death (or maybe only send it when the player gives in, if possible).

The game sends the selected content package to GameAnalytics, but I didn't consider that servers/clients may use code modifications despite using the vanilla content package. I think at the moment you can ignore it, but in future updates I'll add some way to track it - maybe just a simple string as you suggested.

Sending the crash reports can be handled the same way as in the vanilla game. The string sent using GameAnalytics.AddErrorEvent is simply saved on the GameAnalytics server and can be viewed from their web interface, so it doesn't have to be in a specific format or anything like that.

**Comment by NilanthAnimosus** [comment]
Everything has been implemented generally fine. including crash reports (I've gutted that area quite a bit, adding unrecoverable crash handlers which automatically restarts the process and sets it back up to a server in the event of a crash).

I implemented it fully with no issues, just the actual information tracked wouldn't be the vanilla game. It doesn't count as a death unless they give in / are eaten (Same kill function and code roughly). It was more incase you were gauging information off this for vanilla and my mod can tend to reduce/skew death rates and other details quite a bit.

I'll keep it all in and enabled based on the setting.

**Comment by NilanthAnimosus** [comment]
Now I'm further wondering on errors - I've modified/customized some of them to include more details where applicable so not sure what to do there.

But there are errors that could be caused by my mod (such as for example, a week ago I learned I was having character reference issues as one of my GUI's was not correctly disposing of the hosts characters) that don't exist in the vanilla game.

Does the game analytics separate these issues or generally would I be having errors that may be specific to my mod be triggered and added to a general pool for vanilla?

I don't feel it would be very helpful if say, you thought there were character reference issues or other errors that are only in my mod.

I'll be trying to include them as they look where they fit/are applicable and leave them in for now, but I don't really want to damage the analytics in any sense or confuse you with issues unrelated to vanilla.

**Comment by Regalis11** [comment]
Sending error messages that may only be specific to your mod mod is completely fine, they may still provide some useful information about issues in the vanilla version. However if you could modify the version string configured in GameAnalyticsManager, that'd make it super easy for me to filter out errors/events coming from modded games. You could for example change line 20 to GameAnalytics.ConfigureBuild(GameMain.Version.ToString() + "NilMod").

I think for the next update I'll include the name and hash of the executable in the version string automatically, so modders won't have to do this themselves. I thought the design event on line 39 would've been enough to identify if the errors sent during the session are coming from a vanilla version, but so far I haven't been able to find a way to filter things based on other events sent during the session (and the GameAnalytics documentation is very scarce regarding custom queries).

**Comment by NilanthAnimosus** [comment]
also just a small change I think might be worth doing is a small refactor on all the checks for if game analytics is active, to send them through a method in GameAnalytics instead of at the source its written.

Literally just GameAnalytics.AddDesignEvent() instead of say the (Current) below? perhaps the same for setting the Dimension for consistency.

`csharp
                if (GameSettings.SendUserStatistics) 
                { 
                    Mission mission = GameMain.GameSession.Mission; 
                    GameAnalyticsSDK.Net.GameAnalytics.AddDesignEvent("QuitRound:" + (save ? "Save" : "NoSave")); 
                    GameAnalyticsSDK.Net.GameAnalytics.AddDesignEvent("EndRound:" + (mission == null ? "NoMission" : (mission.Completed ? "MissionCompleted" : "MissionFailed"))); 
                } 
```

**Comment by Regalis11** [comment]
Yeah, that's a good idea! I think it should be added to the GameAnalyticsManager wrapper class instead of the GameAnalytics class itself though, so we don't have to modify the framework and compile it from source.

**Comment by NilanthAnimosus** [comment]
Yeah, thats sort of what I meant, I just forgot its named GameAnalyticsManager instead of GameAnalytics.

**Comment by NilanthAnimosus** [comment]
I'm not sure if this sounds odd or not, but perhaps the errors should have some partial reproduction information if they do not already.

Either as part of the method and/or as a boolean to the wrappers method for adding errors extra information could be added to the error:

-level seed
-Submarine name.
-other small, applicable details, like campaign details, runtime (Errors like ogg seem tied to runtime of the client)

I believe dimension records Server/Client/Campaign/MultiCampaign/SubEditor so I doubt this is needed.

I don't know if this would make it very messy on the end you read/receive this information and most current errors sent via gameanalytics likely are not reproducable by level conditions, but for errors such as not finding a suitable location of interest or level gen errors (Though I don't think your logging either via gameanalytics) it would be useful to have any information to reproduce the errors.

It's just another thought for improving its usefulness.

**Comment by NilanthAnimosus** [comment]
Curious - should I include my own version string in the version string sent? My mods versioning is based off a date (Such as 0.8.1.7 is the game version. but my mod uses say, 20/07/2018-1 for the version of the mod).

As of right now its:

```csharp
GameAnalytics.ConfigureBuild(GameMain.Version.ToString() + "_NilMod");
```

but I could instead use:
```csharp
GameAnalytics.ConfigureBuild(GameMain.Version.ToString() + "_NilMod_"
+ GameMain.NilMod.NilModVersionDate); ///outputs "20/07/2018-1"
```

I tend to release multiple versions (Like hotfixes for issues)

**Comment by Regalis11** [comment]
I'd go with the second one, it's good to have some extra info in case there's the need to determine the exact game version at some point.

**Comment by NilanthAnimosus** [comment]
Noticed the changes to the analytics and decided to use:

```csharp
GameAnalytics.ConfigureBuild(GameMain.Version.ToString()
                + (string.IsNullOrEmpty(exeName) ? "Unknown" : exeName)
                + "_(" + NilMod.NilModVersionDate + ")" + ":"
                + ((exeHash?.ShortHash == null) ? "Unknown" : exeHash.ShortHash));
```
