### ISSUE TITLE
Fully upgraded deep diver gets crushed by pressure in the final level

### ISSUE THREAD

**Issue by KB0MB4** [Regalis11/Barotrauma#4910]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Currently it's impossible to finish the campaign legit ways due to crushing depth. The class of the boat doesn't matter, couldn't finish even on custom fully upgraded deep diver, tried even on remora to be sure. After about 5800 hull damage starts, and if you go even deeper its just sinks to bottom and sits there impossible to be repaired because of outdamaging crush.
And because we need a boat to actually finish, we basically got locked out of legitimate ending.

**Steps To Reproduce**
Upgrade deep diver shell health to max, select last mission, struggle :D

**Version**
0.10.0.9 on windows 10

**Additional information**
Additionaly, it's felt really weird so we could swim outside just fine, but cant do that on a sub.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8a195bc6970556851821acb045f43b435f7279b

**Comment by Rokvach** [comment]
The drone might need to be tagged as a deep diver as well

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/99698172-78a8-4708-939f-358f0febdec1)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/457835ecbef9a43a09cf7074c51f7e8da9eed1e0

**Comment by KB0MB4** [comment]
Not sure if its related but i wounder if this ok or not.
So to workaround this situation i tryed to edit sub file, changed setentityproperties crushdepth to above 6200, still got crushed after 5800
Tryed to do upgradeitem increasewallhealth over the max limit in editor, same thing.
So i guess that 5800 crush depth is somehow hardcoded?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
