### ISSUE TITLE
[0.12.0.0] Crafting times for auto-crafting are broken after level change

### ISSUE THREAD

**Issue by anubis-barotrauma** [Regalis11/Barotrauma#4921]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the player is crafting multiple items and they change levels, the remaining items after the current one finishes take too long to craft.

**Steps To Reproduce**
1. Place ingredients in medical fabricator, enough to craft at least two of the same medicine.
2. Start crafting the medicine and undock immediately.
3. The first item will be crafted normally. Crafting of the second item will automatically begin, as expected.
4. The second item will take hours to craft. Hunch: The game attempts to start crafting with 0 skill.

**Version**
v0.12.0.0, Windows 10.

**Comment by Regalis11** [comment]
Auto-crafting has been disabled in the latest unstable build, this should no longer be an issue

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
