### ISSUE TITLE
spawnitem command appears to no longer autocombine item names

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#493]
Version 0.8.1.5 vanilla

I wanted to test possible issues with emp and edited a stun grenade but found myself unable to spawn items to inventory, cursor or otherwise until it clicked in my head it was the item names space.

![](http://puu.sh/AYi6r/0be1871606.jpg)

I usually use client hosting for testing, but its taking the other half of item names with spaces as the last arg. Sure I have gotten it to work with "" but the help text doesn't indicate one should use quotes for items, just for names (Which would normally be the last to input).

I recall previous behaviour was to combine everything to the left of the last arg, but this behaviour seems to have been lost.

**Comment by NilanthAnimosus** [comment]
I've just successfully written code that automatically combines all args but the last much like 0.8.1.4 behaviour but still can be used on characters.

Essentially I've taken the extraparams and if the item prefab is not found (and params is equal to 0) instead of returning, it checks for a client equal in name to the last arg (Which is the one that should be combined).

If its found, it increments the extra params, then rechecks the prefab. if the prefab is null again and extraparams is null again it returns with an error.

**Comment by Regalis11** [comment]
Fixed in 2df7d6a
