### ISSUE TITLE
[0.12.0.1] Error - Invalid Inventory for Hatchlings

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4932]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever a hatchling hatches from an egg, there's some kind of error of invalid inventory for them.

**Version**
0.12.0.1

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@08601b2. Cherry picked to release.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue. Working correctly, closing.
