### ISSUE TITLE
[Unstable] Humpback bottom airlock hatch can't be repaired if its broken

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4936]
Tested in 0.12.0.1 Unstable build in Multiplayer campaign outpost level. 

Can be repaired with a welding tool. 

Not sure about similar airlock hatches
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/3701cbca-287a-48af-adf3-d886c438ed19)

**Comment by Benzin73** [comment]
I can confirm this issue in the current stable version as well.
That hatch breaks, but i cannot repair it with any tool. In fact i cant interacti with it at all except to rewire with a screw driver. Ibe approached it with a crowbar, wrench, welding tool, even plasma cutter. And nothing seems to have any effect on the hatch.

The way i fixed this issue, was to take the sub to the nearest outpost, look up the "sub ugrades guy", and order "Repair all items". After i did this, on the next mission the hatch was fixed.

**Comment by danielasteljoki** [comment]
Fixed in 7fc71e2.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
