### ISSUE TITLE
changelog states devices can be wired outside the submarine - but this feature is only on dev

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#494]
Version 0.8.1.5

I was going through the code and looking at the changelog to realize what was added to dev branch only is in the changelog for master for 0.8.1.5. 

I do not see a merge nor a relevant commit that appears to contain this change on master.

**Comment by Regalis11** [comment]
Whoops, should've gone through the commit history more carefully when writing the changelog. Fixed in e0455ca & 41800af.
