### ISSUE TITLE
[Unstable] Decorative sprite typo on 'Frozen Seeds Display Shelf'

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#4945]
The decorative sprite for the frozen seeds display shelf appears to be wrong in either source-rect or texture path, instead showing part of an outpost background wall texture.
![image](https://user-images.githubusercontent.com/55356135/106343391-22d3d080-6273-11eb-9f5f-52fe0907271e.png)

**Comment by Regalis11** [comment]
![image](https://user-images.githubusercontent.com/14351070/106445462-ba117180-6487-11eb-93af-34f8f3b58c35.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
