### ISSUE TITLE
Beds hurt.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#4949]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Beds increase the damage of an affliction you have instead of healing it.

**Steps To Reproduce**
Have one of the afflictions that the bed is supposed to heal, and lie down.

**Version**
V0.12.0.1 Windows

**Comment by Jlobblet** [comment]
Pretty sure this one is caused by the StatusEffects reducing the afflictions by a negative amount, causing them to add instead.
```xml
<StatusEffect type="OnActive" target="Character">
  <reduceaffliction type="damage" strength="-0.05" />
  <reduceaffliction identifier="bloodloss" strength="-0.05" />
  <reduceaffliction identifier="bleeding" strength="-0.05" />
  <reduceaffliction identifier="nausea" strength="-0.05" />
  <reduceaffliction identifier="opiatewithdrawal" strength="-0.05" />
  <reduceaffliction identifier="opiateaddiction" strength="-0.05" />
  <reduceaffliction identifier="drunk" strength="-0.05" />
</StatusEffect>
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c77c817c5cca36f4aba9d0505ac7a40608fb2e8

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
