### ISSUE TITLE
Beds and health scanners

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#4950]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using a health scanner on someone in a bed shows the afflictions x4

**Steps To Reproduce**
Have a person lying down a bed with any affliction, wait a while, then the "blood loss" icon will start appearing on the person, and the other affliction will be seen x4 in the health scanner

**Version**
V0.12.0.1 Windows

**Comment by LePiromano** [comment]
This happened once and now i cant make it happen again...

**Comment by Regalis11** [comment]
Side-effect of https://github.com/Regalis11/Barotrauma/issues/4949
