### ISSUE TITLE
Multiple HuskAffliction Species Spawn if Multiple HuskAfflictions Active

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4954]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This [exact issue](https://github.com/Regalis11/Barotrauma/issues/4674) has resurfaced (unless the fix never made it into the unstable branch).
It was fixed in version 0.12.0.0 according to the changelog, however it seems that in version 0.12.0.1 it is still an issue.

**Version**
V.1200.0.1 - Unstable Branch. OS: Windows 10.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a2623fd10924af7247541e007ae9db7204cab7f

**Comment by Emanthealmighty** [comment]
Not fixed as of V.0.1200.0.2.

**Comment by hubismal** [comment]
Still does not seem to be fixed

**Comment by hubismal** [comment]
The 1300.1 or whatever unstable build seems to fix this.

**Comment by Emanthealmighty** [comment]
Fixed as of version 0.1300.0.1 (Unstable).
When a human dies to any sort of husk infection, the infection that was inflicted first will be the one that's used to spawn the "husked" version of the human.

**Comment by Rokvach** [comment]
Closing
