### ISSUE TITLE
[Unstable] When trying to put a stack of items into your hands while inventory is full by double clicking, you only grab 1 piece per hand. You can still stack it in the hand though.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4955]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to put a stack of items into your hands while inventory is full by double clicking, you only grab 1 piece per hand. You can still stack it in the hand though. This makes it so that we have to unnecessarily merge it manually in our hands.

**Steps To Reproduce**
1. Fill up inventory except hand slots.
2. Grab stack of items.

**Version**
0.12.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e8d25f99e39f0dad1a3d4adc200f417eb4ed013 by preventing items from being stacked in equip slots

**Comment by Rokvach** [comment]
Seems like if you select a stack whilst your inventory is full it puts the same item on both of your hands, I think it should only select one item per hand rather than auto-fill them.

**Comment by Rokvach** [comment]
Moving back to misc

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a034d9e98f9ec569aa542506174589b571e02324

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
