### ISSUE TITLE
[Unstable] Cave marker and Nest location mismatched

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4956]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![Capture](https://user-images.githubusercontent.com/5086682/106405601-ca343d00-6404-11eb-947a-1316a7b1797e.PNG)

[Save.zip](https://github.com/Regalis11/Barotrauma/files/5901373/Save.zip)

**Version**
0.12.0.1

**Comment by Regalis11** [comment]
Could not reproduce. I think the level generation might be affected by the mods you have installed. Is "Kaillera Map Mod" available somewhere so I could give this another test with the mods?

**Comment by Kaillera** [comment]
It was included in the zip

**Comment by Regalis11** [comment]
Marked as high prio, this seems to be a larger issue in the level generator that causes caves and ruins to be misplaced in mirrored levels (related: https://github.com/Regalis11/Barotrauma/issues/4529)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a7137d44c2287a6b99a00750f6047b58fd2461bb

**Comment by Rokvach** [comment]
Tested, haven't been able to reproduce this. Seems to be working correctly. Closing.
