### ISSUE TITLE
[Unstable] When bots cleans up cargo, they grab 1 item from a stack at a time instead of the whole stacks.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4958]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots cleans up cargo, they grab 1 item from a stack at a time instead of the whole stacks.

**Version**
0.12.0.1

**Comment by itchyOwl** [comment]
I think it's better if @Regalis11 takes a look into this, as he knows the inventory and the stacks better.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a1943e67e73529ce4600e93db77eaa835d65f6f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
