### ISSUE TITLE
[Unstable 0.12.0.1] Ancient Weapon in Wreck 1 can be placed inside a toolbelt

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#4969]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The manually placed Ancient Weapon in the secure cabinet of Wreck 1 has the 'smallitem' tag (allowing it to be placed inside a toolbelt and other small item containers.

**Steps To Reproduce**
Get the Ancient weapon from the secure cabinet in Wreck 1
Place in toolbelt

**Version**
v0.12.0.1, ReleaseWindows, branch release, revision 53206fbfc3
Windows 10 64 bit

**Additional information**
https://streamable.com/icauf8
The AW in the crate was obtained from a Ruin, while the one in inventory came from Wreck 1

![wreck 1 ancient weapon](https://user-images.githubusercontent.com/58775950/106741365-f365f080-65f1-11eb-9b51-72326d5f4035.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/748ac6412ce19a39783359a7cb0220f08d1daa77

**Comment by Udrakan** [comment]
Would be nice if that weapon was removed from the wreck entirely and replaced with more fitting loot

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
