### ISSUE TITLE
[Modding] NearbyCharacters target for status effects ignores conditionals for individual characters.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4970]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using a "neabycharacters" tag, you may want to add a conditional to the status effect it belongs to, so for example if we want to cause a small AoE effect that will deal an affliction to only a certain species, we would add "conditional speciesname=[speciesname]", and any other conditional we want.

The problem is, however, that once the status effect recognizes one single character that meets these requirements, every other single character in range will have the status effect applied to them

**Steps To Reproduce**
1) Create a status effect with "nearbycharacters" as its target. Add a few conditionals to the status effect.
2) Run the status effect in game with a character nearby that meets the requirements we set earlier with the conditionals.
3) Notice how the character is affected by the status effect.
4) Spawn another character next to the previous one that does not meet the same requirements above.
5) Run the status effect again, notice how both of the characters get affected, while the expected outcome would have been that only the first character gets affected.

**Version**
Version: 0.11.0.10 - Public Branch. OS: Windows 10.

**Comment by hubismal** [comment]
FYI there are a lot of workarounds for this. You can use nearbycharacters to afflict afflictions in an area and have the afflictions do whatever if a speciesname checks out.

Devs: please don't change the core functionality or else it'll break a lot of mods

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.

As mentioned in the PR, currently the conditionals determine whether the status effect can execute, not what it can target, so in a sense this isn't a bug. As there are ways around this and since changing it would break a lot of mods, we're not planning to address this at least for the time being.
