### ISSUE TITLE
docking hatch when dockling at a outpost 

### ISSUE THREAD

**Issue by tiba666** [Regalis11/Barotrauma#4973]
**Description**
if you  make a button to the docking hatch toggle state you can force the server owner to have to go to the next map becuase you will be force to pick a new locations on the map both in 0.11 and in 0.12 unstable 

**Steps To Reproduce**
wire a button signal out put when docked at a station to the docking hatch toggle_State

**Version**
0.11 and in 0.12 unstable 

**Additional information**

**Comment by Regalis11** [comment]
Todo note: prevent rewiring docking ports in outpost levels?

**Comment by Regalis11** [comment]
Prevented rewiring in outpost levels now: https://github.com/Regalis11/Barotrauma-development/commit/756eae683fb0f85123e630d96729c63c59a6309d

**Comment by Rokvach** [comment]
Might be good to also make the wires look like they are locked, so it looks less like a issue

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2cd5d75f-39dd-4ade-a354-14aac3c94c72)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
