### ISSUE TITLE
[unstable] diving suit locker 

### ISSUE THREAD

**Issue by tiba666** [Regalis11/Barotrauma#4974]
**Description**
if oxygentank in the suit is 0% i will not start fill it up with oxygen need atleast 1% oxygen in the bottle before it start filling up 

**Steps To Reproduce**
emtry oxygentank in the suit in the suit locker 

**Version**
unstable 

**Additional information**
remember to add the wire first

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4933
