### ISSUE TITLE
[Unstable] [Modded] Creature variants of husked monsters with custom inventories crash the game when spawned. 

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#4979]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a variant of a monster which has the property "husk" set to true is spawned and said monster has any sort of custom inventory, the game will crash.
The game won't crash if said monster doesn't have _any_ inventory defined, as it will instead spawn with the same items as its inherited monster.

**Steps To Reproduce**
1) Enable a mod that adds a creature variant of a husked monster that has a custom inventory.
2) Attempt to spawn said variant in the game.

**Version**
V0.12.0.2 - Unstable Branch. OS: Windows 10.

**Additional Information**
Very likely to be connected to this [issue](https://github.com/Regalis11/Barotrauma/issues/4829).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a46d2f937b3fcb807d3e822cd9ece5ad1f8de9dc

**Comment by Emanthealmighty** [comment]
Seems fixed as of V0.1300.0.2 (Unstable).

**Comment by Rokvach** [comment]
Closing
