### ISSUE TITLE
[Unstable] Chain piece art error

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#4980]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The chain pieces (The ones on the Remora, for example) have a slight tilt in their art, causing these juts at the ends of the texture. The new art has broke a few sub aesthetics that use long chains

**Version**
v0.12.0.2
![image](https://user-images.githubusercontent.com/63509011/106919514-1f709700-6702-11eb-9be0-0a1ccd61ceeb.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
