### ISSUE TITLE
[0.12.0.2] Two ruins merged together

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4981]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5928278/Multiplayer.zip)
![Capture](https://user-images.githubusercontent.com/5086682/106950314-37451c80-66fc-11eb-883e-78cb4ca14f05.PNG)

**Version**
0.12.0.2

**Additional Informations**
NGL it was pretty cool and lots of enemies.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66f52ef496aedb64d7eca2a361283c5872dd005c

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue. Working correctly, closing.
