### ISSUE TITLE
Buzzer Component's Position Does not Update When Held

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#4982]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When holding a buzzer in either hand, its position will not update when your mouse is dragged around.

![image](https://user-images.githubusercontent.com/72813628/106953561-855c1f00-6700-11eb-9689-c25ca59e4004.png)

**Steps To Reproduce**
1. Spawn/Fabricate a Buzzer Component
2. Attempt to place it/move your character to see it stuck in the air

**Version**
Unstable V. 0.12.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dce2dd84b0f9c59c02712fb028b045ca60f36770

**Comment by Rokvach** [comment]
Tested, working correctly.
