### ISSUE TITLE
[0.12.0.2] Crush Depth music always play at 3500m and below

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4988]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crush Depth music always play at 3500m and below. Should be in relation to submarine's hull upgrade.

**Version**
0.12.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3a027c39f66ce662e5b5874673ab34d79f99d392

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
