### ISSUE TITLE
[0.12.0.2] Piezo Crystal Rock right at spawn point

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4989]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Piezo Crystal Rock Formation was right on us when we spawned in. I managed to lowered the sub before taking a picture:
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5929117/Multiplayer.zip)
![Capture](https://user-images.githubusercontent.com/5086682/106968184-5b155c00-6716-11eb-863f-a591cfe3ca40.PNG)

**Version**
0.12.0.2

**Comment by Regalis11** [comment]
Moved this to the abyss team because it relates to Regalis11/Barotrauma#5110 (the minerals in the abyss and the crystals are spawned with similar logic)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f6bd196113b1fae7c91b64d68ff27e3744275a2

**Comment by Rokvach** [comment]
Tested on dev using the provided save and its still there, does it only affect newer saves?
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f364fe46-9003-428b-b1a6-32eca41f1881)

**Comment by Rokvach** [comment]
Shouldn't be happening anymore, closing.
