### ISSUE TITLE
[0.12.0.2] Invisible Ballast Flora Spores

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4997]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://youtu.be/CVdpqeY9_tU?t=2504
Was driving through the level with sonar on, didn't see any spores. Caught Ballast flora somehow. This was in Multiplayer, so I don't know if there was some sort of desync with spore locations for the clients.

**Version**
0.12.0.2

**Comment by Regalis11** [comment]
They're a little hard to spot, but if you look closely, you steered through spore clouds at 41:20 and 42:10.
