### ISSUE TITLE
[Unstable] Bad sprite for toolbelt

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5002]
**Description**
![image](https://user-images.githubusercontent.com/59519434/107113068-b5203980-685c-11eb-98be-3c52f17c04fa.png)
**Steps To Reproduce**
-sub editor
-spawn toolbelt

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c80155fa1a6d7d0da242e1d762d7f5edc0278070

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

Note: Won't be part of the next update
