### ISSUE TITLE
Intensity layers are not playing

### ISSUE THREAD

**Issue by V1Htor** [Regalis11/Barotrauma#5003]
**Description**
A music tracks that depends on intensity layer are not playing (Intensity layers 1-4, desperation, exterrestrial broadcast...). And they're not playing only in multiplayer.

**Steps To Reproduce**
I don't know, i can send you my zipped game folder if needed, but my friend has the same issue with layers.
**Version**
Windows, stable 0.11.0.10 (and maybe 0.12.0.2)

**Additional information**
New frontiers - intensity broken, pets update - intensity is back to work, uncharted depth - broken again.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/90c02a777c464c4b30a037726f444043929de0db

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
