### ISSUE TITLE
Left Handed Issues

### ISSUE THREAD

**Issue by Caithloki** [Regalis11/Barotrauma#5006]
- [x] I have searched the issue tracker to check if the issue has already been reported.

When the played has there mouse setup in the OS for right click as the main mouse button instead of left click, it will cause the mission map screen to close when primary clicked instead of accepting the travel choice.

Steps to reproduce
Changing the mouse settings on the OS from left to right primary button will cause the issue, option can be changed well in game to allow it to work,

Version
Latest game stable version, v0.10.0.9, on Windows 10 home edition.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/499920fa3591619307debcf7576d8a534e59fd36

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

Note: Fix not included in the next update
