### ISSUE TITLE
Misleading "Drop" tooltip when interacting with linked containers

### ISSUE THREAD

**Issue by moxian** [Regalis11/Barotrauma#5008]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When interacting with a container that was opened via a different linked object, trying to put an item in a slot gives a red "Drop" text, that's confusing.

Please compare:
- Trying to move an item, when the UI was opened by clicking on a container (steel cabinet in this case):
![20210208-032258-Barotrauma](https://user-images.githubusercontent.com/7831163/107172310-f3346f00-69bc-11eb-972d-be735be658e6.png)

- Trying to move an item when the UI was opened by clicking on a linked container (fabricator in this case):
![20210208-032339-Barotrauma](https://user-images.githubusercontent.com/7831163/107172355-0ba48980-69bd-11eb-8ac9-3ea58c649472.png)

**Steps To Reproduce**
- Start on a humpback sub
- go to the engineering
- click on fabricator
- move items in the steel cabinet around
- see the slots not lighting up, and the scary red "Drop" persisting

**Version**
Current unstable steam beta,  
![20210208-032707-Barotrauma](https://user-images.githubusercontent.com/7831163/107172543-88376800-69bd-11eb-97bf-c8a37336a139.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6a722231e12adbb3069ee90b7dcdf59bd4618cd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
