### ISSUE TITLE
Unreliable dynamic hull creation with docking port

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#5009]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the sub I am working on dynamic hull is not being generated properly:
![image](https://user-images.githubusercontent.com/70696707/107204577-6a0a5000-6a2f-11eb-921f-764e7d09ba00.png)
This is however not a problem if I move the docking area far from the sub:
![image](https://user-images.githubusercontent.com/70696707/107204859-c66d6f80-6a2f-11eb-9a59-67bdc461db95.png)
![image](https://user-images.githubusercontent.com/70696707/107204883-cbcaba00-6a2f-11eb-9c22-6cd13ee5012a.png)
![image](https://user-images.githubusercontent.com/70696707/107204955-e2711100-6a2f-11eb-85b1-27ad44b91791.png)
It is only a problem if I put it near the original location: 
![image](https://user-images.githubusercontent.com/70696707/107205057-ffa5df80-6a2f-11eb-9e06-5bac1dc481f0.png)

**Steps To Reproduce**
Use the attached sub, and move the docking area as demonstrated above.
[Vajra V0.1.7.sub.zip](https://github.com/Regalis11/Barotrauma/files/5942851/Vajra.V0.1.7.sub.zip)

**Version**
0.12.0.2

**Additional information**
This is only tested in the editor.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/96a2a590c3992e311eb4a165495943deb0d4aa28.

Note for QA: I think it'd be good to test several subs and see if the hulls still generate correctly everywhere, particularly in custom subs with more exotic docking port configurations (same for #5281 which could be tested simultaneously with this).

**Comment by Rokvach** [comment]
I went through around 10 custom subs with attached linked subs and didn't spot any issues. Seems to be working correctly, closing.
