### ISSUE TITLE
[EVENTS] Switching characters or falling unconscious will cancel an event

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5010]
**Description**
Switching to different crewmate while event is active cancels the event

**Steps To Reproduce**
-eventeditor
-load huskcultist event
-tell the cultist you dont have the eggs right now, but will get them for him
-switch to another character
-->event gets interrupted and finished

It lead to a lot of confusion when I was making events today, trying to figure out what went wrong all the time.

**Version**
Unstable

**Comment by ekqvist** [comment]
It seems that the same can happen if your character falls unconscious. Either falling unconscious or switching to another character will deem the original character an invalid target and will interrupt and complete the event without the chance to return to the NPC and complete the event.

**Comment by Udrakan** [comment]
Still the case on Stable 0.18.15.1
-husk cultist event spawned when I played as mechanic SP
-I switched to captain to obtain eggs from a locked toxin cabinet
-event is cancelled

**Comment by Regalis11** [comment]
Finally got around to fixing this: https://github.com/Regalis11/Barotrauma-development/pull/3680/commits/c99bef96447d8066f55e3a334dc8733656c64d0b

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/7f4419b844f51ca2fa31f33f7c509ab1eb783aeb no issues found, closing.
