### ISSUE TITLE
[Modding] Upgrade "offsetonselected" does not work on searchlights and cameras

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5014]
**This issue was mentioned in off-hand addition to the list of #3674 - but kind of being its own known issue specific to modding and the fact that it still happens in the current build I feel it deserves a dedicated ticket at this point.**

Upgrade system cannot be used to add upgrades to the range of searchlights and cameras viewed through a periscope. Despite having searchlight even explicitly having an offset defined in it's XML:
`  <Item
    name=""
    identifier="searchlight"
    tags="searchlight"
    aliases="Searchlight"
    category="Machine"
    focusonselected="true"
    offsetonselected="515"
    linkable="false"
    Scale="0.5">`
Attempting to upgrade a searchlight ( or camera ) with the same upgrade code used in vanilla results in an error saying the item does not have an offsetonselected, even though it does.
`  <UpgradeModule identifier="searchlightincreaseoffsetonselected" maxlevel="4" categories="searchlights">
    <Price baseprice="1000" increaselow="+50%" increasehigh="+50%"/>
    <Item offsetonselected="+10%"/>
    <LightComponent range="+10%"/>
    <Sprite texture="Content/UI/CampaignUIAtlas2.png" sourcerect="384,768,128,128" origin="0.5,0.5"/>
  </UpgradeModule>`
  
![image](https://user-images.githubusercontent.com/55356135/107305387-e6f9f180-6a50-11eb-8d2c-1c0c45da843c.png)

**Comment by Regalis11** [comment]
Items don't have a property called "OffsetOnSelected", you need to use "OffsetOnSelectedMultiplier" instead (example in the turret range upgrade).
