### ISSUE TITLE
[Modding] Bots unable load "hands only" items into a reactor

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5020]
When a bot is ordered to operate a reactor with fuel that cannot be held in inventory ( ` does not have slots="Any" ` ) and instead requires it to be held in the hands; the bot is unable to decide to pick up the item with their hands so they loop back and forth between the nearest fuel containing item and the reactor attempting to fuel it.

**Comment by Regalis11** [comment]
Could not reproduce. Tested by removing the "Any" slot from the fuel rod, and the bots seem to have no trouble refueling the reactor.

**Comment by Regalis11** [comment]
I'm afraid there's not much we can do about this without further info. I suspect it could be caused by something else in the custom item's config.
