### ISSUE TITLE
[Modding] Allow for <ParticleEmitter> to be halted/removed by NPC upon particle impact with NPC

### ISSUE THREAD

**Issue by nakedcrook** [Regalis11/Barotrauma#5022]
Hitscan weapons with a ParticleEmitter will not obey collision removal when impacting another NPC/Character. When a hitscan weapon with a particle in motion impacts a wall, the particle will be removed from the scene once the particle impacts the wall. However, particles will pass right through NPCs, and keep going, even though the hitscan registers a hit on an NPC. The particle will not be removed by impacts with NPCs.

Here is sample particle code (Please mind the last line for sprite texture):

```
<testshot1
lifetime="0.35"
startdelaymin="0"
startdelaymax="0"
angularvelocitymin="0"
angularvelocitymax="0"
startrotationmin="0"
startrotationmax="0"
rotatetodirection="True"
drag="0"
waterdrag="0"
velocitychange="0,0"
velocitychangewater="0,0"
usecollision="True"
CollisionRadius="20.0"
DeleteOnCollision="True"
Restitution="0"
friction="0.0"
startsizemin="0.35,0.35"
startsizemax="0.35,0.35"
sizechangemin="0,0"
sizechangemax="0,0"
growtime="0.0"
startcolor="255,255,255,255"
endcolor="255,255,255,255"
drawtarget="Both"
blendstate="Additive"
animduration="0.0"
loopanim="False">
<sprite texture="(path to sprite).png" sourcerect="0,0,L,W" origin="0.5,0.5" premultiplyalpha="false" />
</testshot1>
```

Add this status effect to the projectile of a hit scan weapon (for example, the revolver)

```
<StatusEffect type="OnActive" target="This">
<ParticleEmitter particle="testshot1" copyentityangle="true" anglemin="0" anglemax="0" particleamount="1" velocitymin="4000" velocitymax="4000" scalemin="1" scalemax="1" />
</StatusEffect>
```

**Comment by Regalis11** [comment]
Particles don't collide with characters, only walls. 

Since this is technically a feature request and not a bug report, I'll close the ticket. There's a chance we might implement this at some point in the future, but I'm afraid it's not a very high priority.
