### ISSUE TITLE
Item duplication from stacked crafting recipes 

### ISSUE THREAD

**Issue by desmonddentresti** [Regalis11/Barotrauma#5027]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can multiply crafting materials and thereby, the items, by deconstructing some objects with recipes that output stacked items; Bandages, Plastiseal.

**Steps To Reproduce**
1. Have 1x Bandage
2. Deconstruct (Gain 1x Organic Fibre)
3. Craft Bandage using 1x Organic Fibre (Gain 2x Bandages)
4. Deconstruct 2x Bandages (Gain 2x Organic Fibre)
5. Repeat

**Version**
0.12.0.2

**Additional information**
Does not occur with Flares. Deconstructed materials output from Flares spawn with 25% 'health' and combined manufacture the expected four flares.

**Comment by danielasteljoki** [comment]
Fixed in f3bd145 on dev.
