### ISSUE TITLE
No stack restrictions on older saves

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5029]
If you are running a older save you are able to place full stacks on items which otherwise has a restriction in place, for example 8 oxygen tanks in to a diving mask.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f8e3d5b5-7dc1-4d5c-9b15-72ab2388333a)

**Comment by Regalis11** [comment]
Could not reproduce. Tested by doing the following:
1. Start a new campaign in v0.11.0.9
2. Put a diving mask in the inventory, save and quit
3. Switch to v0.12.0.2
4. Load the campaign
5. Try to put more than 1 oxygen tank in the mask

A save file where this occurs would be helpful.

**Comment by Rokvach** [comment]
It seems that this is mainly caused by certain mods and not by old saves. So might not be something we should act upon as the mods creator would need to update their mod to have the restrictions. There just seems to be more mods that changes the vanilla weaponry and items than I thought.

**Comment by Rokvach** [comment]
Seems like the issue wasn't due to old saves but rather some mods which still needs to be updated by the mods creators. Closing this ticket as there's nothing that we can do about it. Closing.
