### ISSUE TITLE
large diving suit locker

### ISSUE THREAD

**Issue by tiba666** [Regalis11/Barotrauma#5030]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
no wire connection like the small diving suit locker so you cant get it to auto fell the suit with oxygen

**Steps To Reproduce**
no option with a screwdriver on the large diving suit locker

**Version**
0.12.0.2

**Comment by Regalis11** [comment]
The large diving suit locker is a legacy item, meaning that it's only included in the game for backwards compatibility.
