### ISSUE TITLE
SMG mag description

### ISSUE THREAD

**Issue by EdusFF** [Regalis11/Barotrauma#5032]
Description has a written value for magazine size instead of using the actual value:
<entitydescription.smgmagazine>A magazine for 15 .45 caliber rounds.</entitydescription.smgmagazine>

Currently magazines hold 20 rounds so the description is incorrect

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c0f9c327cc255449e4fdce6a465bf450e7b4fd9

**Comment by Rokvach** [comment]
No issues, closing.
