### ISSUE TITLE
wikiimage_sub command doesn't capture full sub

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5034]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wikiimage_sub command produces images without considering the sprite of a turret, causing subs with protruding weapons to produce a cropped image.

**Steps To Reproduce**
make sub where the turret barrel extends further than any other part
take wikiimage_sub

**Version**
0.12.0.2 stable

**Additional information**
workaround is to move an invisible piece to increase bounding box of sub, including waypoints.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2339b13f5ec30eabd44ce18babf460f5ee3cd50f

**Comment by Rokvach** [comment]
Tested, haven't been able to reproduce. Working correctly. Closing.
