### ISSUE TITLE
AI ignores the hideinsonar="True" .xml parameter when notifying the crew

### ISSUE THREAD

**Issue by RayTrace082** [Regalis11/Barotrauma#5038]
- [✔️] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An AI, if ordered to operate the navigation terminal, will notify the crew about `"Something on the sonar at X o'clock!"`, despite the target being invisible in the sonar

**Steps To Reproduce**
(No creature from the core package makes use of this parameter (AFAIK?), so it's necessary to edit/add a new creature with this parameter)
Spawn creature with `hideinsonar="True"` while an AI is on the Navigation Terminal
Wait for the AI to notify the crew about the direction
Switch character for the AI in the navigation terminal, confirm that nothing can be seen in the Sonar

**Version**
Latest unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62eb90da0d305485ab3b444c1fc906d4aa5603c8
