### ISSUE TITLE
Connection Panels and Picking on R-29 should not be locked for a Vanilla submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5039]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Connection Panels and Picking on R-29 should not be locked for a Vanilla submarine. Players should be able to reconfigure/repurpose/detach/recycle the components. It's quite inconvenient for good signal engineers.

**Version**
~0.12.0.2

**Comment by Regalis11** [comment]
I couldn't find a single locked component in the sub. I wonder if this has been addressed already at some point?

**Comment by Kaillera** [comment]
Way back in v12 they were locked. I think the only issue left are the lamps being locked or non interactable or something.

**Comment by Rokvach** [comment]
I can access wiring of the lamps but can't change their color, I can only change the color of the lamp located in medbay. Water detectors seems to also be configured the same way, not sure about other more hidden parts of the sub.

**Comment by danielasteljoki** [comment]
Allowed editing of lamps in a7968d6.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
