### ISSUE TITLE
Crash on launch (SteamManager.InstallWorkshopItem())

### ISSUE THREAD

**Issue by Stupitar** [Regalis11/Barotrauma#5042]
[crashreport (84).log](https://github.com/Regalis11/Barotrauma/files/5972689/crashreport.84.log)
game crashes while loading
v 0.12.0.2
macOS 11.2.1

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a9772d9e85a47debbf13092dd06082d5982ea7f4

**Comment by Rokvach** [comment]
There hasn't been any sightings to this crash nor issues caused by the fix. Seems to be working correctly, closing.
