### ISSUE TITLE
Fight Intruders behaves differently when a non-security officer role does it

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5047]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're telling non-security officer roles to Fight Intruders, they behave a lot differently than when a Security Officer does it.

When the crew member that is on Fight Intruder is attacked by an enemy, they'll flee to find safety and defend themselves to get out of the room the hostile is in. After they find safety, they'll loop back to Fight Intruder again. Where as a real security officer would stay and battle to the death instead.

**Steps To Reproduce**
1. Give Captain the same gear as a security officer (Baton, Knife, Batteries)
2. Tell Captain to Fight Intruders
3. Spawn Intruders like Crawlers in the sub
4. Observe the Captain fighting the intruder and make sure he at least get hurt by the alien once per encounter.

**Version**
0.12.0.2

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@df3c009. Non intentional bug that only happened when the bot got damaged by an enemy. However, it is intentional that security and other bots act in a different way when they don't have fight intruders order.

**Comment by Rokvach** [comment]
Tested, didn't notice anything strange. Working correctly. Closing.
