### ISSUE TITLE
Glitch: Weird gratis store offers in Barotrauma

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#505]
Story:
I bought more than 9000 credits worth items from multiplayer campaign store on my solo voyage save file. I completed the mission and store wanted me to purchase same items i bought before for free (I have stored those items in containers not my inventory, before completing mission). When I wanted to refuse one of those for free items I gained credits for it and the rest of the items was removed giving me no credits.

How glitch works:
New barotrauma updates may have glitched stores, so they no longer remove purchased items from store screen after starting the mission. If the player refuses one of those multiplied items he will receive credits for it, but not the rest presented. The rest will vanish as the first one selected.

**Comment by NilanthAnimosus** [comment]
I think I recall seeing that this is indeed a thing, but thought nothing of it as I wasn't watching the credit count, as the list simply wiped itself clean.
