### ISSUE TITLE
Game always crashs now after newest update

### ISSUE THREAD

**Issue by sonicmaster155** [Regalis11/Barotrauma#5054]
[servercrashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5976298/servercrashreport.2.log)
[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/5976299/servercrashreport.log)

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report! This seems to happen because a coilgun or a railgun in the custom sub is linked to an item that's not a valid coilgun/railgun loader. I added a check that prevents this from crashing the game (https://github.com/Regalis11/Barotrauma-development/commit/44d459b52808d391cff9811f03496298f162e416), but until the fix is released, you should be able to work around the issue by removing those links.

**Comment by Rokvach** [comment]
Tested, wasn't able to crash the server whilst using the same sub, working correctly. Closing.

**Comment by sonicmaster155** [comment]
> Thank you for the report! This seems to happen because a coilgun or a railgun in the custom sub is linked to an item that's not a valid coilgun/railgun loader. I added a check that prevents this from crashing the game ([Regalis11/Barotrauma-development@44d459b](https://github.com/Regalis11/Barotrauma-development/commit/44d459b52808d391cff9811f03496298f162e416)), but until the fix is released, you should be able to work around the issue by removing those links.

i removed the links that arent to the loaders ill see if its playble =D thank you for the help =)

**Comment by sonicmaster155** [comment]
> Tested, wasn't able to crash the server whilst using the same sub, working correctly. Closing.

game crashed many times though im testing to see if it works now  though =o

**Comment by Rokvach** [comment]
Will be fixed in the next update

**Comment by sonicmaster155** [comment]
> Will be fixed in the next update

thank you =)
