### ISSUE TITLE
The more loader linked to the coilgun, the faster the ammunition will be consumed Abnormal ammo consumption rate when the coilgun is linked to multiple loaders

### ISSUE THREAD

**Issue by EchoSaber-114** [Regalis11/Barotrauma#5061]
- [ √ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://www.bilibili.com/video/BV16o4y197q1
As the video shows,when the turret is linked to one (Can shoot without interruption for 54 seconds) or two (108s) loader, the ammunition consumption rate is normal.
However, when turret linked to three or more loader, (in this video is 7) ammunition consumption rate is abnormal, 7 ammunition boxes can only support uninterrupted fire for 108 seconds, just like two boxes.
All ammunition boxes after the second may not be launched. 

**Steps To Reproduce**
When the coil gun is connected to more than two loaders.

**Version**
v0.12.0.2 in Windows. In fact, even earlier versions had this problem

**Additional information**
Thank you for your hard work and hope you can fix this bug as soon as possible.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2016cb5c62b0530ba7bcc7b943a2028f7c9bbfb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
