### ISSUE TITLE
[Modded,Networking] The clientside fabrication recipe desync issue.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5063]
The bugfixes to mod load order reversal has reduced the commonness of these issues, but still happens frequently enough to be a problem. Modded fabrication recipes seem to have desynced network events, causing the client to see either fabrication progress not start, fabrication progress bar go off the edge of the screen and never finish, or each person see a completely different recipe selected.

From an outside perspective it first seemed like the "order" that fabrication recipes were loaded differed between server and between clients. From looking at the item-prefab and networking code, it seems **List<FabricationRecipe>** fits this description.
Perhaps something else is still causing the clientside fabrication recipe index to be wrong despite load order enforcement???

Only reason this does not seem to affect vanilla items is because they are **always** loaded before everything else, so their beginning order of indexing will always be consistent?

**Steps to reproduce:**

- Load 2 (probably) mods which add their own <Fabricate/> on a server
- Try different combinations of server-side order, client load order, with them enabled or disabled by client before joining
*(For instance, have one mod enabled already clientside but the other turned off)*
- Have a non-host try fabricate a modded item

**Current workaround:** Disconnect from the server, manually re-enable the mods on the clientside (if they have been turned off by hotloading's 'revert' feature), restart the game (this seems to be essential because it resets client load order to a known state), then rejoin the server and the server load order will suddenly sync recipes correctly.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a8564b8f230b77e8695b941d13f365636b058fd2

**Comment by Rokvach** [comment]
At least hasn't broken anything in Vanilla, can't say anything about when using mods

**Comment by Rokvach** [comment]
Haven't tested with EK directly but haven't noticed any issues when crafting with some other mods and vanilla, so I think this is working correctly. Can be re-opened if the issue resurfaces. closing.
