### ISSUE TITLE
Medic priority system seems broken since last update.

### ISSUE THREAD

**Issue by Benzin73** [Regalis11/Barotrauma#5066]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ever since the stable release 0.12.0.2 the way Medics prioritize who to heal first seems to be completely broken. At least in Single player games. 
Medics under "Heal & Rescue" orders will very often NOT heal other injured bots. Even though the other bots are injured, some times severely, and screaming "Help im bleeding!" "help i been shot!", etc. And their healt is below 60%, the medic will still not heal them. 
The ONLY way ibe found to go arround this problem, is if i switch to one of the injured bots. In wich case the medic immediately heals me (the human player). But he will not heal other bots, unless i switch to play as those bots.

Rescue doesnt work either. I lost my engineer because i did not noticed he was down, and the medic was just standing there instead of trying to resusitate him. When i noticed this, i switched to the medic and ran to rescue the engineer, but it was too late.

Needless to say, i did make sure the proper meds were on board (proof of this is that the medic DID healed the bots when i switched to the injured bots), and the medic was in effect in "Heal & rescue" orders. And this has happened all the time. On all missions. 

It seems the healing priority system on the medics as been changed in a way to prioritize human players first (wich is fine), but now they dont heal other bots. Needless to say, its is an EXTREMELY severe problem for us single player users. As we have to constantly switch to each bot to see their status, and get the doctor to heal them.
To be honest, ibe stopped playing the game completely due to this issue.

**Steps To Reproduce**
- On a single player campaign, get a crew of (on my case) 7 bots, make sure one of them is a medic. 
- Wait untill they get some injuries, and see the medic ignore them.
- Switch to one of the injured bots, and see the medic run to heal you.

**Version**
0.12.0.2

**Additional information**
Something to note is, i played the 12.0.2 version when it was in the "unstable" / beta branch on steam, and this problem was not there. It was the complete opposite. I noticed that doctors immediatelly healed everyone who was injured (bot or me), even if the patient had only minor injuries. I was very happy to see medics worked better than in version 11.x
This only started happening when the stable version of 12.0.2 came out, and i switched back to the "stable" / normal branch on steam. So i guess the problem is cause by something done just before release.

Please fix this issue guys, i love the game. But i only do single player and i cant play it like this. :)

**Comment by Benzin73** [comment]
Hi devs, sorry to pester you with this issue. I would just like to know if you were able to reproduce the bug, and if so, if there is a patch / hotfix coming for it? I miss playing the game :)

**Comment by itchyOwl** [comment]
Hi, I haven't had time to look into it yet. But I know which changes it relates to and I'll try to fix it for the next update. It should be a fairly quick one to fix, but getting it right requires testing. So you could actually help here a lot by giving the unstable build a test after the fix. I'll notify here when it should be fixed.

**Comment by Benzin73** [comment]
Hi, sure thing! happy to help. Please let me know when the unstable version is updated with the fix, and i will test it out.
Thanks!

**Comment by itchyOwl** [comment]
Hmm, I have difficulties in reproducing this issue. The steps I tried:
1. Give an order to a medic
2. Shoot another bot in leg / spawn monster to do some damage / spawn an explosion on the character
3. Observe the medic healing the target.

I found out one issue, but that's post 12.0.2 and related to the multiple orders. There's only one change to the priority logic and I can't see how that would cause this issue.

@Rokvach have you seen any other reports about this issue and have you been able to repro it?

**Comment by Rokvach** [comment]
I've only seen and heard the opposite where medics are a bit too adamant of healing even the minor bruises (which was addressed couple days ago)

Last time I tested the order was when we added the multiple orders support and I didn't spot anything strange with their behavior then.

**Comment by Benzin73** [comment]
Then maybe it is something on **my** end after all? I have no clue of what that could be, as i dont use mods or even workshop subs. But for me the issue happens all the time. To the point where medics let other bots die. 

Tonight i will completely uninstall the game again, delete the files under %APPDATA%, reinstall, and give it another try?
I will report back here after i do this and test.
