### ISSUE TITLE
PVP - "Additional Cargo" only spawns on the left team Submarine

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5075]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Additional Cargo" only spawns on the left team Submarine in PVP.

**Version**
~0.12.0.2

**Comment by Leonidas-ai** [comment]
Huh. This has been a bug since 0.9.0.7. I guess they really don't get fixed unless you file a bug report. Thanks for adding this.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/111314e9481af47143055b7e64db4b2b697bc720

**Comment by Rokvach** [comment]
You get two notifications about purchased cargo, would need to limit the notification per team. But should additional cargo even show that notification?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6597a50ad29e17a24df66d2ce4f58afa2f264948

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
