### ISSUE TITLE
Kastrull - EDC range is so small that you have to literally be in the EDC to get hit.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5078]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Kastrull's EDC range is so small that you have to literally be in the EDC to get hit.

**Version**
~0.12.0.2

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@2177075

**Comment by Rokvach** [comment]
The range still seems rather poor and even if the EDC hits it seems to only stun for couple seconds

If you have a crawler attached at this point the EDC doesn't reach it so the crawler is just free to gnaw through the hull
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9bd5090a-6eae-4b94-b381-c81188f5df41)

**Comment by ezjamsen** [comment]
The discharge isn't actually able to arc across those angled wall parts, unfortunately. I tried! The range however should be all the way to the edge of the angled wall part, and the airlock, to the left, and to the angled wall part and the glass to the right.

**Comment by Rokvach** [comment]
Closing
