### ISSUE TITLE
Typhon 1 - The fuel rod in the reactor starts at 67% condition

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5079]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The fuel rod in the reactor in Typhon 1 starts at 67% condition.

**Version**
~0.12.0.2

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@76031ef

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
