### ISSUE TITLE
Rotated items don't mirror correctly

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5084]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A rotated object does not get mirrored on the separatist sub
Letter/number labels DO get mirrored which renders then unreadable

**Steps To Reproduce**
rotate an object 90 degrees, for example status monitor, or a reactor
spawn mirror'd sub

**Version**
0.12.~

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8197af689f979af0862b977f52a002fd8c2da37d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
