### ISSUE TITLE
"Trigger" pins do not differentiate between 1 and 0

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5089]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trigger pins on Coilguns/Railguns/Depth charge tubes/Discharge coils/Detonators react to 0 as if it was a trigger. 

They react to any "signal", as opposed to only reacting to 1, leading to several wiring complications

**Steps To Reproduce**
Wire a switch to a trigger
Trigger is activated even when switch is sending 0 

![Capture](https://user-images.githubusercontent.com/73229309/108101638-cb619d00-7087-11eb-8dfe-067e6ad733da.JPG)

**Version**
v0.12.0.2

**Comment by Bertaz** [comment]
Also, if you wire the trigger to a button (or a switch with isToggle disabled) the trigger is activated every other presses of the button.

If the buttons are supposed to send a 1 signal every activation, the triggers don't react to any signal. Maybe every change in the signal?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f2215cd1c0301aed74fb960d24c60f4db8692379

**Comment by Working-Joe** [comment]
Tested, appears to work in V0.1300.0.0 for both turrets and detonators.

**Comment by Rokvach** [comment]
Closing
