### ISSUE TITLE
Navigation Terminals don't emit signals if you haven't interacted with them manually

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5090]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you send a signal via VELOCITY_IN, the signal doesn't go through the X/Y OUT until you manually interact with the terminal

**Steps To Reproduce**
Send a vector signal to VELOCITY_IN
Use velocity X/Y out on engine/pump
Engine and Pumps don't move until you touch the terminal

Hidden or Non-interactable terminals are effectively "dead"

![Capture](https://user-images.githubusercontent.com/73229309/108104770-fcdc6780-708b-11eb-9660-fd9691a0e15c.JPG)

**Version**
v0.12.0.2

Also see: #4443
Being able to change the "screen" vector itself by using VELOCITY_IN would solve that problem, as well as allowing sub stabilization (autopilot at 0, velocity reset at 0)

**Comment by Bertaz** [comment]
> [...] allowing sub stabilization (autopilot at 0, velocity reset at 0)

Sending "0,0", empty or even an invalid value reset the vector to 0,0. An AutopilotMaintain_In would be useful

**Comment by ubertpendragon** [comment]
More about that:

VELOCITY_IN effectively only saves a few components (it was already possible to switch control from terminal to another mode of control) but doesn't allow us to reset the manual vector

In practice this means that as soon as you stop controlling with IN signal (for example, periscope control), it will fly off in whatever direction the manual vector is set on.

The manual vector should be completely reset to 0,0 every time VELOCITY_IN receives a signal to avoid that, with the added benefit of allowing autopilot to dynamically stabilize on the last known location

**Comment by Bertaz** [comment]
> [...] it was already possible to switch control from terminal to another mode of control [...]
> [...] controlling with IN signal (for example, periscope control)

You managed to steer the ship with a periscope? In older version of the game periscopes sent a world coordinate, but now they just send the rotation°. I tried with sin(θ),cos(θ) but couldn't make it work

> The manual vector should be completely reset to 0,0 every time VELOCITY_IN receives a signal

I agree

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/19bf0070035955f9b4a255861d50e90ee05f142f

**Comment by ubertpendragon** [comment]
Tested with hidden terminal
Sumarine immediately moves on startup

Working fine
