### ISSUE TITLE
Oxygenite tanks/shards are recharged when placed in a powered O² tank shelf

### ISSUE THREAD

**Issue by Thirty-Percent** [Regalis11/Barotrauma#5091]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Oxygenite Tanks and Oxygenite Shards, having the "oxygensource" tag, are recharged when placed inside powered oxygen tank shelves, which recharge everything that has the tag

**Steps To Reproduce**
Drain a bit of O² from aforementioned items, then place them inside a powered O² shelf

**Version**
0.12.0.3

**Additional Information**
Doesn't work when the tank/shard is inside a diving suit inside a locker, because the diving suit only recharges "oxygentank". If oxygenite recharge is intended, then the issue is this

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b9f635f4d7a5bb2da50e1e0e265d0482ab551093

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
