### ISSUE TITLE
Shuttle thumbnails significantly increase main .sub file size

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5092]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When saving a submarine that uses one or several shuttles, their xml is "added" to the main sub's xml, INCLUDING the thumbnail. This significantly increases main sub file size the more shuttles there are.

Shuttle thumbnail is useless if you do not want the shuttle to appear in the sub list (example: drones)

**Steps To Reproduce**
Replace the thumbnail of the RemoraDrone by a 4x4 black square .jpg
Refresh Remoradrone on Remora, and save
Remora size is now much smaller

![Capture](https://user-images.githubusercontent.com/73229309/108122108-17223f80-70a4-11eb-8508-46b23eed2462.JPG)

_Replaced Remoradrone thumbnail with 4x4 black square_

**Version**
v0.12.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9701a55760278af0661231583ea854197ced1fc2

**Comment by ubertpendragon** [comment]
Vanilla Remora and Kastrull both had their file size reduced
Custom saved subs had their file size reduced as well

Seems to be working fine
