### ISSUE TITLE
StatusEffect OnUse in attack doesn't work as expected for HuskAppendages

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5094]
[Issue, Bug?]
On non-huskappendage ragdolls, having an attack within a limb with a statuseffect of type "OnUse" triggers whenever an attack is attempted at all by a monster. If you were controlling a mudraptor with an OnUse statuseffect attatched to its attack and you pressed creature attack, the attack would trigger.

This doesn't seem to be the case in HuskAppendages for whatever reason. Attempting to attack won't do anything, and the statuseffect only triggers when the attack connects (by damaging something).

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this in either the current public version (v0.12.0.3) or the latest unstable build (v0.1300.0.9), in both cases the StatusEffects only trigger when the attack hits something.
