### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by convict-toaster** [Regalis11/Barotrauma#5096]
I'm attempting launch the game. Upon launch I hear the logo sound playing then I'm brought back to desktop with the crash report. I managed to get to the main menu, but was only getting about 3 frames per second before it crashed again.

**Comment by Regalis11** [comment]
Hi! 
Could you please send us the crash report? Without the report, it's very difficult for us to diagnose the problem. Thanks and sorry for the trouble!
