### ISSUE TITLE
[0.1300.0.0] Light casted by coilgun flickers constantly whenever it's shooting

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5098]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Light casted by coilgun flickers constantly whenever it's shooting.

**Version**
0.1300.0.0

**Comment by Rokvach** [comment]
This was in multiplayer while using the Orca sub (Not sure if it exists on every sub)

**Comment by anubis-barotrauma** [comment]
Confirming this - happened in submarine editor test mode for a custom submarine.

**Comment by Ek-Videogames** [comment]
An interesting side-note, because this bug attempts to find a LightComponent to spam on the turret item, if you try to shoot any turret that does not have a light component on unstable the game will just immediately crash.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6236ef5c077aa1e0c99525f00d23225cf9c5c76

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
