### ISSUE TITLE
Mission Mode - Respawn Shuttles spawns in players that chosed to be Spectators

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5099]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Respawn Shuttles spawns in players that chosed to be Spectators in Mission Mode

**Version**
~0.1300.0.0

**Comment by Regalis11** [comment]
I'm afraid I wasn't able to reproduce this. Are you sure spectating was allowed in the server settings?

**Comment by Kaillera** [comment]
Spectating was allowed in the server. I checked Spectator mode in the lobby on an on-going round. The respawn shuttle was already counting down. After the countdown I was immediately put into the game.

**Comment by Regalis11** [comment]
Thanks for the extra details! I only tested this by joining before the respawn countdown started, but I'll give that a try next.

**Comment by Regalis11** [comment]
Nope, still no luck. :/

**Comment by Regalis11** [comment]
No known steps to repro, closing
