### ISSUE TITLE
Retain a reference for a characters visual info and death reason for the round summary screen even if they no longer exist

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#510]
It makes sense to remove references to characters that have been eaten / deleted or otherwise, but it would be interesting to know they had existed or how they had died.

A simple copy of the species (or creatures filepath)/headsprite and gender values with the character name from the character info after the character and their crew reference is removed just for the round end screen could let these characters that no longer exist still be shown on a summary.

**Comment by Regalis11** [comment]
Fixed in the dev branch
