### ISSUE TITLE
[0.1300.0.0] Endworm was able to fit into abyss caves and get stuck there

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5100]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Endworm was able to fit into abyss caves and get stuck there.
![Capture](https://user-images.githubusercontent.com/5086682/108528749-bd876400-72a1-11eb-9e89-396ba226843b.PNG)

**Version**
0.1300.0.0

**Comment by itchyOwl** [comment]
Hmm, maybe we should just design the caves so that abyss creatures won't get inside? Might require some AI changes too...

**Comment by Regalis11** [comment]
The caves have been made more narrow since this report, I think it's now so unlikely they'd end up inside the caves that we can consider this fixed.
![image](https://user-images.githubusercontent.com/14351070/111795444-df3f2f80-88cf-11eb-8aca-511d9591e47a.png)

**Comment by Rokvach** [comment]
No issues, closing.
