### ISSUE TITLE
[0.1300.0.0] When moving stacked items to cabinets/fabricator/crates, you only move 1 item at a time via double click

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5103]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When moving stacked items to cabinets/fabricator/crates, you only move 1 item at a time via double click. This makes it very slow to loot and move items around.

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ba5a31d92cfd339dbe50531e64fc62dcb8338153

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
