### ISSUE TITLE
[0.1300.0.0] Launching Depth Charge crashes game/server

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5104]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Launching Depth Charge crashes game/server.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6012717/crashreport.log)

**Steps To Reproduce**
1. Select Orca
2. Launch Depth Charge

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6236ef5c077aa1e0c99525f00d23225cf9c5c76

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
