### ISSUE TITLE
[0.1300.0.0] Immdiately death to "High Pressure" affliction when wearing a suit in Abyss depth

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5105]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever a player is afflicted with "High Pressure" while wearing a suit and is inside the sub, they'll immediately die when the sub is in Abyss depth.

**Reproduction**
1. Sit in Abyss Depth with the sub.
2. Wear a Diving Suit.
3. Enter and Open Airlock to fill it with water, or manually pump in water into a hull until pressurized.

**Version**
0.1300.0.0

**Info**
Was in Campaign.

**Comment by Regalis11** [comment]
This also happens when you dive outside the sub, making most abyss islands impossible to get to.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/cf74983

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
