### ISSUE TITLE
[0.1300.0.0] No ID Card to open Abandoned Outpost Secured Steel Cabinet

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5106]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There are no ID Cards to open Abandoned Outpost Secured Steel Cabinet.

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d6c2b5c10e457c093d658c8b130d67d1b4cae127

**Comment by Xeavas** [comment]
[v0.1300.0.3] - No issues, was able to access sec locker with one of their IDs 👍

**Comment by Rokvach** [comment]
Closing
