### ISSUE TITLE
[0.1300.0.0] Abandoned Outposts - Missing Platforms for Hatches

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5107]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There's a lot of modules with missing platforms for the hatches in Abandoned Outposts.

**Version**
0.1300.0.0

**Additional information**
There's also a module with ladders that don't extend all the way to the leveled ground.

**Comment by danielasteljoki** [comment]
Fixed platforms in 742a137. The broken ladder in engineering module is intentional.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
