### ISSUE TITLE
[0.1300.0.0] Navigation terminal outputs wrong y-value for neutral level

### ISSUE THREAD

**Issue by anubis-barotrauma** [Regalis11/Barotrauma#5108]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pump target level calculations were recently changed in commit bf5860f. Navigation terminal outputs wrong value for neutral ballast level, causing the ship to start sinking even though the navigation arrow is at the dead center.

See the example test submarine attachment - the target value given by navigation terminal is half of what would keep the submarine floating. If we were to connect the navigation terminal to the pump, it would pump in water and the ship would sink.

**Version**
v0.1300.0.0 Unstable

[BallastBugReport.zip](https://github.com/Regalis11/Barotrauma/files/6014774/BallastBugReport.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a113c1de9ccf6e5108b1b52cccff0dcd2210377

**Comment by anubis-barotrauma** [comment]
Confirming that the issue is fixed. Thanks for the great work!

The issue can be closed now. I'd close it myself, but I don't know your issue policy (e.g. if Rokvach needs to confirm).

**Comment by Rokvach** [comment]
Closing
