### ISSUE TITLE
Breathing directly out of air tanks

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#511]
Judging by videos like [this one](https://www.youtube.com/watch?v=8qX5w-_Omjg), it seems to be tricky, but possible to breath out of the air tanks without using any diving equipment(though not sure if it's as easy when you are deeper underwater). It would be nice to be able to save your life if you have the tanks but no mask or diving suit. Considering the difficulty of the action, to be more realistic, it should probably stop you from moving and doing any other actions when you are using the tank.

**Comment by Billsofat** [comment]
Eh. I don't know. Don't want to make things too easy.

**Comment by BillCombs** [comment]
I mean, it's already pretty easy to manage your oxygen when you know how to prepare for possible upcoming situations. Also, almost every time, when you have oxygen tanks, you also have a diving mask, because they are usually put together in most containers. I just think it would be nice to have more possible actions during dangerous situations to make your brain work more often. Instead of thinking: "there are no masks or suits nearby, i will die, no point in trying to stay alive any longer" and giving up, you will start thinking about possible additional locations of oxygen tanks, it will give you another chance, another hope. This is one of the things that makes games of this kind fun, the adrenaline rush when being in a near-death state and the strong will to live motivating you to keep moving.

Though it could be pretty unbalanced when playing with small amounts of players, because, when there are not many players who also need the oxygen, you could get a lot of the spare tanks for yourself, and you are currently able to carry a lot of them in your inventory(especially when you have a jumpsuit inside of a jumpsuit inside of a jumpsuit and so on). Not sure if it would be enough to balance it, but you could make that action consume a lot more air from the tank since a lot of it would be wasted by not being properly sealed(what means even if you survive and find a mask, you will have a lot less of full oxygen tanks to use them with that mask). It would just give you a bit more time to think about your next actions.

But i guess it probably would take more effort to implement than it's worth, especially since, as i said, if you have the tanks, you most likely have a mask with you as well. It's just one of those small additions that you can easily live without but probably wouldn't mind having.

Just trying to give some things think about. Even if it's a bad idea, the thought process can lead to the new, good ones. It's still up to the developers to consider them worth implementing or not.

**Comment by ZealanL** [comment]
In reality, you would be blasted in the face with air for a couple of seconds. If you managed to put your mouth on an open oxygen tank, your lungs could explode (depending on the oxygen pressure).

This makes breathing underwater incredibly easy, sorta ruins the point of diving masks (you could breath out of an O2 tank while using a radio, which you can't do with a diving mask).

If this is a balanced feature, it should use up a large portion of the tank and emit some kind of air-blowing particle system, like you opened a big tank of compressed oxygen. This way it would be highly inefficient but possibly usable for a couple of deep breaths in an emergency, in order to swim to real diving gear.

**Comment by BillCombs** [comment]
> If you managed to put your mouth on an open oxygen tank, your lungs could explode

This is why the person in the video i gave the link to is using his hand instead of putting his mouth directly on the tank.
>If this were a feature, that would breathing underwater incredibly easy

It's already incredibly easy, the masks are usually always placed in containers right next to your spawnpoints. If you make it spend a lot more oxygen, it would be a fair trade, since it would be harder for you once you get to the real equipment, because you wouldn't have as many tanks full of oxygen.

> you could breathe out of an O2 tank while using a radio

I don't think you should be able to talk underwater at all if you have nothing covering your mouth from water.

>If this is a balanced feature, it should use up a large portion of the tank

This is pretty much what i said in my second comment "Not sure if it would be enough to balance it, but  you could make that action consume a lot more air from the tank since a lot of it would be wasted by not being properly sealed"

**Comment by ZealanL** [comment]
If this were implemented, I would suggest that oxygen tanks would have the "use" button appear on them, similar to medical syringes. When pressed, your oxygen meter regenerates and the oxygen tank loses a large portion of its oxygen (say - 20%).

I would still worry about players abusing this unrealistically, though. Maybe it lowers your health by a tiny bit?

**Comment by BillCombs** [comment]
It would probably not look that good if you were just standing there, holding it in your hand near your belt and making bubbles. Perhaps it should either have an animation and a cooldown when you press the use button, or must be moved to your mouth with a specific animation by pressing right mouse button and start giving oxygen when you press the left one.

But at same time it would have to work differently when not in water, since it would be unrealistic to make bubbles in air just by releasing oxygen.

Honestly, now, after i thought about it some more, i think that this whole thing would take so much effort to implement it properly without having any bugs or getting it abused and at same time make it look good enough that it just seems to be not worth all that effort. Plus not many players will be using it anyway since you usually get a mask almost as soon as you spawn.

I am not going to close this, because this feature is not really that bad, but it definitely should be one of the last on the list to be worked on.

**Comment by BlueTheKing** [comment]
Im not sure (atleast with the current code) if you could stop that, meaning once you press the use button be it accidentally or on purpose it will empty the the tank. Possibly even won't stop emptying even when you place it into a diving suit/mask, so it would just empty quicker than if you were breathing normally. And since there are so many masks in most subs there really isn't a reason for it IMO.

**Comment by BillCombs** [comment]
I think i should actually just close this, because even if not counting the effort that you will have to put in, it's not really worth the weight that it adds to the game files and the possible game performance issues. Even though both would most likely be quite small, the feature is even smaller(especially in terms of how often the players will use it) and seems to be not worth it.

As i said, i am posting this type of ideas just to give something to think about. There are a lot of possible ways the game could improve in, and even discussing this kind of small ideas may help to find the right direction.
