### ISSUE TITLE
[0.1300.0.0] Abandoned Outposts JB/Oxygen Generator eventually fails, suffocating all the bandits.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5113]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Abandoned Outposts JB/Oxygen Generator eventually fails, suffocating all the bandits. That or you can sabotage the JBs to the generator too.

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
No longer an issue, the oxygen generator works without power

**Comment by Rokvach** [comment]
Closing.
