### ISSUE TITLE
[0.1300.0.0] Bots spams Antirad/Stabilozine in Radiation Zones at low sickness %.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5114]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots spams Antirad in Radiation Zones at low sickness %.

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2cf9dfb41c7ff83445e29af4c16c57b07f30cb8

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
