### ISSUE TITLE
[0.1300.0.0] Aliens tends to die to radiation sickness by the time you find them in the level of a radiated zone?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5115]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Aliens tends to die to radiation sickness by the time you find them in the level of a radiated zone? Especially when you take your time in the level. I feel like they're taking damage while in their waiting to be deployed state or something.

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
Yes, this is by design.
