### ISSUE TITLE
Using NearbyCharacters or NearbyItems in an Affliction causes crash

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5116]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using an affliction with a NearbyItems or NearbyCharacters target, the affliction causes a crash.  
Included here is a crash report and an example mod to test with.
[crashreport (20).log](https://github.com/Regalis11/Barotrauma/files/6016885/crashreport.20.log)
[AfflictionCrashMod.zip](https://github.com/Regalis11/Barotrauma/files/6016886/AfflictionCrashMod.zip)

**Steps To Reproduce**
1. Run `giveaffliction "Crash Affliction" 1` in the console.
2. Observe.

**Version**
v0.12.0.2, Windows 10

**Additional information**
Potential fix:
The update method here
https://github.com/Regalis11/Barotrauma/blob/0697d7fc6412f972e5089fa88b693b486e55fb86/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/CharacterHealth.cs#L713
passes `null` as the `targetLimb` which is then sent all the way this crash position:
https://github.com/Regalis11/Barotrauma/blob/0697d7fc6412f972e5089fa88b693b486e55fb86/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/Affliction.cs#L257

Since `targetLimb` is `null`, a NullReferenceException is thrown. 

A potential fix I found was sending the main limb as the `targetLimb`:
![image](https://user-images.githubusercontent.com/37539527/108611690-cc246700-73d8-11eb-9629-2f85c6108c97.png)
Although I have not tested it thoroughly.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62491f7845103f7d246cd85c0875cf321dea2cf3

**Comment by Jlobblet** [comment]
Tested with the attached mod and another. Working as expected.

**Comment by Rokvach** [comment]
Closing
