### ISSUE TITLE
[0.1300.0.0] Multiplayer Campaign - You can respawn in Abandoned Outposts

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5117]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can respawn in Abandoned Outposts in MP Campaign with servers that have respawn enabled. There's no risk of gameover especially when the server has low respawn time.

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2d763fed89f7ac9c29168e982669eb04571fdf4d

**Comment by Rokvach** [comment]
Tested, wasn't able to respawn. Working correctly, closing.
