### ISSUE TITLE
Hunting Grounds "side quest" spawns a second Endworm

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5118]
- [yos ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Entering the abyss while on a hunting grounds side quest will spawn an endworm, and another endworm will spawn by default.

**Version**
V0.1300.0.0
![20210221000736_1](https://user-images.githubusercontent.com/55637865/108614544-3e497b80-73da-11eb-8971-57689507f0b5.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/68201992c37d70c8c689e0f611b4e47a52b7fb96

**Comment by Rokvach** [comment]
Tested, only spawns one endworm, working correctly. Closing.
