### ISSUE TITLE
Cant move my mouse to the right side of the screen

### ISSUE THREAD

**Issue by JeremyCam** [Regalis11/Barotrauma#512]
![image](https://user-images.githubusercontent.com/41529812/43041818-220a766e-8d31-11e8-870a-d950bb4e2020.png)
I can't get my mouse to move any farther right whilst tabbed into the game, not sure how to fix. It moves just fine when im tabbed out.

**Comment by ZealanL** [comment]
Try changing your resolution or trying Windowed or just plain Fullscreen.
What device and operating system are you using?

**Comment by Regalis11** [comment]
What's your display resolution? This may happen if the resolution is set higher than your display resolution.

**Comment by ZealanL** [comment]
Yeah, but that would likely cause the mouse to get stuck going down as well. Maybe a window issue? Window drawing an image bigger then it actually is?

My best guess is the window is a bit less wide then the screen, but still draws fully. This happened during the development of my own C# game, and I am pretty familiar. Messing with settings should fix it.
