### ISSUE TITLE
[0.1300.0.0] Bandit corpses eventually turns into duffel bags / become duffel bags when leaving outpost on your sub

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5121]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bandit corpses eventually turns into duffel bags / become duffel bags when leaving outpost on your sub.

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
I'm not sure I see why this is a problem, does it cause some kind of issues?

**Comment by Kaillera** [comment]
I think it's too easy to get duffel bags this way and loot the entire AO without ever having to manually loot the corpses or bring your own crates up.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0f3efc96efadb90c5d0d8e2265346ee34c2f1843

**Comment by Rokvach** [comment]
No issues, closing.
