### ISSUE TITLE
[0.1300.0.0] Mining outposts mine into "nothing"; outposts "float" in open water

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5123]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mining outpost modules dig into open water instead of icy rock. 
Also, bulkhead doors have no collision and if you go through them, you'll end up in water outside

**Steps To Reproduce**
Any mining outpost
![unknown](https://user-images.githubusercontent.com/73229309/108636480-be78eb00-7485-11eb-840d-bfe3da1383cc.png)

Encase outposts in a rock/ice background?

**Comment by Regalis11** [comment]
Added colliders to the doors in https://github.com/Regalis11/Barotrauma-development/commit/068ec605a1760770c6fc684bb5307feaf56988fc

**Comment by ezjamsen** [comment]
Short of ensuring that only the docking module of an outpost protrudes from the ice/rock, I don't know what we can really do about this. I'd be inclined to close this as a known and acceptable issue unless there's an easy path forward.

**Comment by ubertpendragon** [comment]
> ensuring that only the docking module of an outpost protrudes from the ice/rock

If you consider that outposts are dug out of rock/ice, which they seem to be as they hang from the map ceiling, they should be encased. 

This also allows more open outpost design with larger rooms as you don't have to make every room "floodproof" with its on set of pumps and compartments
