### ISSUE TITLE
[0.1300.0.0] Cannot enter Abandoned Outposts with submarines that have shuttles

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5125]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot enter Abandoned Outposts with submarines that have shuttles.
[111.txt](https://github.com/Regalis11/Barotrauma/files/6018762/111.txt)

**Version**
0.1300.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e7140f2ddb485da40f2bf338aeb45d03a0bd201a

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly. closing.
