### ISSUE TITLE
[0.1300.0.0] Abandoned Outpost Reactor consumes fuel

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5126]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Abandoned Outpost Reactor consumes fuel. Some players might crank the fission too high to try to melt down the reactor and ends up draining the rods instead.

**Version**
0.1300.0.0

**Comment by danielasteljoki** [comment]
Decreased abandoned outpost reactor meltdown delay, fire delay and fuel consumption in 5d1414e.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
