### ISSUE TITLE
[0.1300.0.0] You can sit in the tipped-over chairs in abandoned outposts

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5130]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can sit in the tipped-over chairs in abandoned outposts.

**Version**
v0.1300.0.0

**Additional information**
![image](https://user-images.githubusercontent.com/14351070/108700808-d1d09880-750f-11eb-8caa-9235d5f50cfa.png)

**Comment by danielasteljoki** [comment]
Fixed in c9b20f5.

**Comment by Rokvach** [comment]
Tipped over chair which I can sit on in research module

Screen: Level editor
Outpost parameter: abandonedoutpost
Seed: nty34y

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/184aac64-3c4f-40e2-8326-142963ffd75b)

**Comment by Rokvach** [comment]
Fixed, didn't spot any more chairs. Closing.
