### ISSUE TITLE
Lossy Physicorium Ammunition Box deconstruction

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5131]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Full or partially empty Physicorium Ammunition Boxes deconstruct just into Aluminum.
At the same time, they're constructed from 1 Physicorium Bar, 1 Steel Bar, and 1 Aluminum.
This may or may not be a feature.

**Steps To Reproduce**
Deconstruct a full or partially-empty Physicorium Ammunition Box.

**Version**
v0.12.0.3

**Comment by Krzeszny** [comment]
So is it a bug or a feature? I don't understand what tagging something as a Bug and a Design feature at the same time means. 
Also, notice that the steel bar vaporizes, too.

**Comment by Ek-Videogames** [comment]
This is intentional because they don't want deconstructed boxes to produce a bunch of half-items. Its just kind of disagreed on by people for obvious reasons of conservation of material.

**Comment by Krzeszny** [comment]
> This is intentional because they don't want deconstructed boxes to produce a bunch of half-items. Its just kind of disagreed on by people for obvious reasons of conservation of material.

Well yes, but actually no.
1. You missed the point. Deconstructing a full Physicorium ammo box yields just aluminum. Steel and Physicorium disappear. It looks like a design mistake. No other ammo does it.
2. If that's true, why do _all other_ coilgun ammo boxes deconstruct partially?

**Comment by danielasteljoki** [comment]
We do shy away from using or receiving partial items, but coilgun ammo boxes are an exception because of how they work. Differing crafting recipes was an oversight. Fixed in 7ae727c in dev repo.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
