### ISSUE TITLE
AI engineer always switches the reactor to automatic without being ordered to operate it (between rounds)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5134]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a minor annoyance when using reactor control circuits.

A few seconds after undocking, an AI engineer starts the procedure of switching the reactor to automatic without being ordered to do so. 
If it's off, they switch it on and put it in automatic mode, taking "excess" fuel rods out. 
If it's already on and on manual (using a control circuit), they also put it in automatic mode and take "excess" fuel rods out.

The command "operate the reactor" seems to have no use, since AI Engineers do it by themselves.

**Steps To Reproduce**
Undock and wait for a few seconds. 

Tested on a new save on Dugong and Humpback.

**Version**
v0.12.0.3

**Additional information**
2-part solution: 
1. AI engineers should not turn the reactor on OR put it in automatic mode unless ordered to do so.
and 2. When an AI engineer is _not_ ordered to operate the reactor, they _should_ add fuel rods by themselves **if** all fuel rods have run out.

Additional suggestion: When ordered to operate the reactor, AI engineers could start to operate it manually, provided that they did it better than on automatic.

**Comment by Udrakan** [comment]
Additional suggestion: Don't have any of the other crewmembers operate the reactor while idle. They often mess around with it when walking around

**Comment by itchyOwl** [comment]
I don't think this is a bug. It's intentional that engineers operate the reactor autonomously. However, if a player has adjusted the reactor, the bots should leave it be until ordered to operate it. This behavior resets after each round. Not sure if we should make it persistent or not.

If the bot has good enough skills, it does not turn auto temp on while operating the reactor: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/63f56a5e-e024-4705-bf93-270349588461)

There was another issue related to multiple bots operating the reactor, which should now be fixed (#5259).

**Comment by Krzeszny** [comment]
> I don't think this is a bug. It's intentional that engineers operate the reactor autonomously. However, if a player has adjusted the reactor, the bots should leave it be until ordered to operate it. This behavior resets after each round. Not sure if we should make it persistent or not.

The problem is that while they operate it when the round starts, they take fuel rods out even if the reactor uses a circuit. I don't see why it shouldn't be persistent and why they should operate it without being ordered to do so with "operate the reactor".

**Comment by itchyOwl** [comment]
> The problem is that while they operate it when the round starts

Yeah I agree. And I think the solution would be to make the bots not to forget what they should (not) do between the rounds. It's also consistent with the current, persisting orders.

**Comment by Krzeszny** [comment]
> > The problem is that while they operate it when the round starts
> 
> Yeah I agree. And I think the solution would be to make the bots not to forget what they should (not) do between the rounds. It's also consistent with the current, persisting orders.

What _current_ persisting orders? We have persisting orders?

**Comment by itchyOwl** [comment]
Oh, right, it's not implemented yet. I thought it was. So, yes we are working to keep the orders persisting between rounds.

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-development@be8c5a6.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
