### ISSUE TITLE
Custom beacon station does not spawn

### ISSUE THREAD

**Issue by Lexicality** [Regalis11/Barotrauma#5137]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I created a custom beacon station, but it does not appear when I host a multiplayer server and select a beacon mission.
I'm aware the selection is random, but I tried 10+ times and every time got `BeaconStation1`, so either I'm incredibly unlucky or it doesn't work.

**Steps To Reproduce**
1. Create a custom beacon station in the in-game editor
2. Create a multiplayer server
3. Launch a beacon mission
4. Enable cheats and freecam over. It is the built in beacon station

**Version**
v0.12.0.3 Windows

**Additional information**
I uploaded it here in case I did something wrong: [BeaconStation2.sub](https://github.com/Regalis11/Barotrauma/files/6023878/BeaconStation2.sub.gz) (I had to append `.gz` on the end for the upload to work, just delete it)

**Comment by Jlobblet** [comment]
You need to create a `ContentPackage` with the beacon in it. Here's an example `filelist.xml`.
The file structure should look like this:
```
Barotrauma
└── Mods
    └── BeaconMod
        ├── filelist.xml
        └── BeaconStation2.sub
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<contentpackage name="Beacon Mod" path="Mods/BeaconMod/filelist.xml" corepackage="false" gameversion="0.12.0.2">
    <BeaconStation file="Mods/BeaconMod/BeaconStation2.sub"/>
</contentpackage>
```
After doing this you should be able to enable the mod in settings and see it spawn ingame.
