### ISSUE TITLE
Bots grab bought items and keep them

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5138]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Npcs take the the items from the crates that appear when you buy at an outpost, even without the cleanup order. Which can sometimes lead to confusion, sometimes the npcs even keep the items and dont place them anywhere.

**Version**
Windows V0.1300.0.0 unstable

**Comment by Veritius** [comment]
Bot crewmates or station NPCs?

**Comment by LePiromano** [comment]
> Bot crewmates or station NPCs?

Crewmates, sorry

**Comment by Rokvach** [comment]
They should place them in to cabinets, but I do think that it might be better to let the player choose if they want the bots to cleanup the purchased items or not. Seeing as to how many think that its a bug that items keeps disappearing from the crates or are confused as to why they have empty crates.

**Comment by itchyOwl** [comment]
They should place them into where they belong to so that the players don't have to, but let's revisit this.

**Comment by Dynamoon** [comment]
Three counts of players being confused by this (or so we may assume): https://steamcommunity.com/app/602960/eventcomments/3113646281425491574/?tscn=1613807862#c3113646913570103658

**Comment by LePiromano** [comment]
Ok I found the problem, the bots leave a single item from the stack in their target locker and keep the rest.

**Comment by itchyOwl** [comment]
The only way I could repro the issue was when I ordered the bots to do something else while they were carrying the items.

Changed it so that idle bots shouldn't take the items from the containers anymore. Also ensured that the bots drop the items they are carrying when they switch objectives.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
