### ISSUE TITLE
Captain's Pipe bug

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5139]
- [ yeah] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can see particles, increasing psychosis ressistance, and pipe tobacco durability decreasing while reproducing the bug, but you're not holding or doing the pipe animation.

**Steps To Reproduce**
1_ Equip pipe
2_ Dock/undock outpost/Enter natural formation
3_ Hold right and left mouse

**Version**
Windows v0.1300.0.0 unstable

**Comment by LePiromano** [comment]
> * [ yeah] I have searched the issue tracker to check if the issue has already been reported.
> 
> **Description**
> You can see particles, increasing psychosis ressistance, and pipe tobacco durability decreasing while reproducing the bug, but you're not holding or doing the pipe animation.
> 
> **Steps To Reproduce**
> 1_ Equip pipe
> 2_ Dock/undock outpost/Enter natural formation
> 3_ Hold right and left mouse
> 
> **Version**
> Windows v0.1300.0.0 unstable

**Comment by Rokvach** [comment]
This issue also happens with other items as well

For example if you have a shotgun equipped and dock to a outpost, the shotgun is still equipped but your character looks as if its not holding anything, re-equipping the shotgun makes it visible.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a48b899a622b9bf7c96495d58808b9d10878456

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce anymore. Working correctly, closing.
