### ISSUE TITLE
File Disassociation

### ISSUE THREAD

**Issue by ZealanL** [Regalis11/Barotrauma#514]
This is a very frustrating issue I've encountered since 0.8.15, where Visual Studio marks all .cs files as "miscellaneous files", instead of associating them with a project. This only occurs with Barotrauma projects, Client, Server and Shared. Libraries like Lidgren Network and Farseer Physics work fine. I reinstalled Visual Studio in multiple versions and tried downloading from git different ways. I even manually downloaded the repo, still having the same issue.

I believe this could possibly be an issue with Baro's C# project files and not my machine, as I even have this problem on my laptop. Only Barotrauma projects are disassociated, and I because of this, I cannot use IntelliSense and essentially have no suggestions, rendering using Visual Studio useless.

This means I cannot reference other classes and namespaces, and I do not have automatic suggestions.
(See image)
![barotraumamiscissue](https://user-images.githubusercontent.com/36944229/43049024-0a0cdfb4-8da6-11e8-9f39-31161e8d5fda.png)

I have redownloaded the repository several times in different ways and still experience this issue.

**Comment by NilanthAnimosus** [comment]
I suffer this issue too, my visual studio has become completely unable to recognize anything intellisense - But it will still compile fine, it is even capable of finding references or navigation - but not of errors and such

My own code doesn't do this but I often manually add the git commits when it comes to my project (Its more a local working copy that I occasionally toss my changes up online for others to see/use than it is a clean git repository....its quite horrifying actually)

It doesn't effect my own project yet I cannot seem to create a new clone nor get the original to show .cs file types all the same - But this is more something peculier visual studio has been doing.

**Comment by ZealanL** [comment]
This is still an issue in the latest version, no matter how I get the files.

I am forced to create a new project and import all the files manually for intellisense, very time consuming.

**Comment by Rokvach** [comment]
Haven't noticed anyone having this issue in a while now. Don't think its suitable to keep this open. Closing.
