### ISSUE TITLE
Physical projectiles' OnImpact inconsistent when hitting severed limbs / gibs

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5140]
Severed limbs / corpses' gibs retain their collision to projectiles for a short time before they fade out, during this time physics projectiles can still hit them, pushing them around and causing the projectile to be pushed around. However actions that are supposed to happen OnImpact such as standard coilgun bolts deleting themselves or exploding ammo detonating seem to only trigger very occasionally, most of the time just slowing down enough after hitting the limb to become inactive or bouncing off at an odd angle. This can be particularly annoying for exploding coilgun ammo and railguns with which stray shots can even bounce back and cause damage to the submarine.

**Steps to reproduce:**

- Shoot a monster until a limb is severed, or kill a relatively weak monster like a crawler and keep shooting until it is gibbed.
- Try hitting the severed limbs with shots and notice most either bounce off and continue flying or impact and physically stop but do still do not 'break' themselves and despawn properly on hit.
- ( This effect is very easy to see with exploding coilgun ammo, as it will blow an enemy apart but once it is gibbed the shots will not detonate unless hitting the creature's core limb or any other limb still attached to the core limb )

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fe6b3a793600384dd7c7eb2737da6011ab38ef1f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
