### ISSUE TITLE
Crash when using freecam command while in wiring mode of subeditor

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#5143]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A bit of an edge case. Using the freecam command while in wiring mode of sub editor will cause a crash.

**Steps To Reproduce**
1.Go to Sub editor, switch to wiring mode
2. F3, enablecheats, freecam

**Version**
Unstable 0.1300

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9ea177d6fce2529d57b8677f4fc312f4013aa0ba

**Comment by Rokvach** [comment]
Tested, wasn't able to repro. Freecamera can't be used in sub editor anymore. Working correctly. closing.
