### ISSUE TITLE
Electric Batons do not stun teammates in Campaign Mode

### ISSUE THREAD

**Issue by Turbinales** [Regalis11/Barotrauma#5146]
Electric Batons do not stun teammates in Company Mode

**Comment by Regalis11** [comment]
The only way I was able to get this to happen is in a multiplayer campaign with friendly fire disabled. Does it happen in other situations as well?

If not, https://github.com/Regalis11/Barotrauma-development/commit/a15125be37e386d53abd20b280127fa159d5cd13 should fix this.
