### ISSUE TITLE
HSV colour editor bug

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5152]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
From Ecchi Senpai: @・‿・ i have a bug to report, it doesn't change the colour of all selected components

**Steps To Reproduce**
1) Select multiple items
2) Bring the the color picker
3) Play with the colours

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Ecchi-Ki-Senpai** [comment]
In submarine editor, HSV colour panel does not update when HSV is adjusted via sliders.
![HSV bug](https://user-images.githubusercontent.com/55001203/111072568-89265280-84b1-11eb-938d-8a3158923a1a.gif)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d597c96371d82e8bae2ee7e233ec4268258cb952

**Comment by Rokvach** [comment]
If you select the entire sub and change the color using the picker it only affects the items color, hiding the items and selecting the entire sub changes the walls color

Repro steps:
1. Load Dugong in sub editor
2. Select everything
3. Paint it red using color picker
4. Notice that only items are colored
5. Hide items and color everything again
6. Notice that walls gets painted

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2f4e043d-1d23-446c-a236-985b6b3e9544)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fa635a4b215304e37b7c74e81de016383fcb541f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
