### ISSUE TITLE
setting long inputs / values for components crash server

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5153]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempting to input a very long value for components crashes everyone (on one team?)

**Steps To Reproduce**
1. place component
2. copy paste in a very long value
3. press enter/exit text field to save
4. something about network and too long

**Version**
0.12 stable

**Additional information**
discovered while attempting to implement this* during a PVP game. only the editor's team crashed apparently, the other team was ok.

*this: https://steamcommunity.com/sharedfiles/filedetails/?id=2391831040

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61728562df27d0e2370b9ec9db405e1627d8a1bb

**Comment by Rokvach** [comment]
Tested, not possible anymore with the restrictions. Closing.
