### ISSUE TITLE
[XML] Cyanide poisoning above 70 strength causes stun and slow movement at the same time

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5158]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In Afflictions.xml cyanide poisoning causes this above 70 strength:
```xml
      <StatusEffect target="Character" setvalue="true" SpeedMultiplier="0.1">
        <Affliction identifier="stun" amount="1" />
      </StatusEffect>
```
SpeedMultiplier (movement speed) and Stun are redundant.

**Version**
v0.12.0.3

**Additional information**
Paralysant "stuns" at 100 but Cyanide causes Stun much sooner – at 70.
It is not a bug per se, and definitely a minor issue, but it seems weird for a poison to cause Stun (and trying to slow movement during a Stun). Maybe it should be using the Paralysis code and slowing movement to a halt before it reaches 70?

**Comment by danielasteljoki** [comment]
Addressed, among other poison-related things, in 8db8dc6.

**Comment by Xeavas** [comment]
[v0.1300.0.6] - Working correctly, cyanide no longer apply stun >70% 👍

**Comment by Rokvach** [comment]
Closing
