### ISSUE TITLE
Can't fully get rid of hallucinating effect

### ISSUE THREAD

**Issue by nroht** [Regalis11/Barotrauma#5159]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I get into caves and get hallucinating effect from plants, the effect worn off overtime but it always just stays at "light" effect
I have tried Haloperidol and it had no effect to getting rid of it. Is there anyway to get rid of it or is it a bug?

**Version**
V0.12.0.3

**Additional information**
![image](https://user-images.githubusercontent.com/79766686/109398815-b59a8480-7971-11eb-9d79-64a29c130aa0.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3811d4da0c1db283dd056648f0e1762e37f5cf6d

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
