### ISSUE TITLE
Invalid physics body velocities on joining a server and syncing

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#516]
Version 0.8.1.8 (Nilmod client - Also effects vanilla as much
![](http://puu.sh/B1CI3/42a6593a36.jpg)

**Comment by Regalis11** [comment]
Haven't seen this happen in v0.8.1.9 yet (nor any other error messages regarding invalid physics values), but I'll keep this open for a bit longer in case there's still something I've missed.

**Comment by Regalis11** [comment]
Doesn't seem to be happening anymore, I think this can be closed.
