### ISSUE TITLE
Invisible items are now part of the sub's thumbnail, shuttle frames as well

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5164]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Thumbnails now frame invisible items, resulting in bad thumbnail creation
![Capture2](https://user-images.githubusercontent.com/73229309/109540104-5730eb80-7ac2-11eb-9a5a-83c294510edd.JPG)

Shuttle frames also possibly have this issue
![Capture](https://user-images.githubusercontent.com/73229309/109539774-fdc8bc80-7ac1-11eb-9d26-2bcefbf40ed8.JPG)
Before and After of the same shuttle, shuttle on the right was updated and saved on 01/03/2021

**Steps To Reproduce**
Put an invisible text label outside the sub
Create a thumbnail
Thumbnail "frames" the invisible item

 Probable cause: #5034
 
Version
V0.12.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4d15820af1828b8217f447630009d82d9d626a6

**Comment by ubertpendragon** [comment]
Somewhat inconsistent, shuttle pictured above is now properly framed
![image](https://user-images.githubusercontent.com/73229309/110346507-eb093700-802f-11eb-8530-498cbe29e6e5.png)

But, other shuttles aren't, probably due to max zoom (this is a really small shuttle), and not centered for some reason
![image](https://user-images.githubusercontent.com/73229309/110346475-e17fcf00-802f-11eb-942d-23f0fd416134.png)

Impossible to get the original shuttle "frame" of the original post back, might be a separate issue

Works well enough to close
