### ISSUE TITLE
Vanilla Outposts/Wrecks/Modules appear in the "Your Items" section of workshop publishing

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5165]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Vanilla Outposts/Wrecks/Modules appear in the "Your Items" section of workshop publishing

**Steps To Reproduce**
Open the workshop publishing
![image](https://user-images.githubusercontent.com/73229309/109541169-c9ee9680-7ac3-11eb-8781-98de77d17a53.png)

Also, there is no alphabetical sorting

Version
V0.12.0.3

**Additional information**
Checking "Hide in menus" in editor makes them disappear from the list

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ebd83d4d4b7788a1565221853884c5ab87787ac5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
