### ISSUE TITLE
Single use items get de-selected after usage

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5166]
- [ x I have searched the issue tracker to check if the issue has already been reported.

**Description**
Single use items, like syringes of opium and grenades, deselect the inventory slot after usage even if there's still more of the item in the stack

**Steps To Reproduce**
1. have a stack of 2 or more opium/grenade
2. use
3. item is now unselected

**Version**
0.12 stable

**Additional information**
behaviour is inconsistent with other items that don't de-select on use (like crowbars or welding tools)
it is very annoying to reselect and partially defeats one of the benefits of stacking

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f52ea1aa83da2611c37aeb5ba37434fe21ba569e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
