### ISSUE TITLE
Navigation terminal draws the same amount of power with Sonar On or Off

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5173]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Navigation terminal draws the same amount of power with Sonar On or Off despite having separate power settings in editor

**Steps To Reproduce**
Use a Navigation Terminal with sonar On
Use a Navigation Terminal with sonar Off
Check junction box, power draw is the same

**Comment by Regalis11** [comment]
Changed in https://github.com/Regalis11/Barotrauma-development/commit/d735126a21bd1ddcb0a836977ca97e3002603a49.

As a note for testing: the sonar still consumes power in the passive mode, but only 10% of the full power consumption. I think it makes sense for the sonar to require a bit of power in the passive mode as well: amplifying, processing and displaying the sounds must take some amount of power.

**Comment by ubertpendragon** [comment]
Both full power / 10% are working
Also working at 0 voltage
