### ISSUE TITLE
Terrain obstructed by submarine structures/decor / fins

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5174]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fins (and presumably other structures) show in the foreground compared to the terrain, sometimes blocking important game information, like whether there is terrain behind it. 

**Steps To Reproduce**
1. Pilot the berilia / a sub that has fins/external structures, 
2. move the sub to a place where the terrain would overlap with the sturcture
3. structure obscures terrain

**Version**
0.12

**Additional information**
Usually when the submarine is at control this is not a problem but when trying to leave/move outside this is important for trying to swim around or shoot through.

Examples: 

Berilia, near the aft. ![image](https://user-images.githubusercontent.com/5103517/109906935-4d98b680-7c6f-11eb-8bde-f24de1838ded.png)

Berilia , just under airlock. Hard to tell if one could swim to the right, and the gun can't tell if it can shoot to the left (it can't) 
![image](https://user-images.githubusercontent.com/5103517/109907103-a700e580-7c6f-11eb-9567-b4d1dc99e640.png)

Workshop sub "Glitterbug (s)", the airlock exit is entirely blocked in by the terrain, but a player can't see it. ![image](https://user-images.githubusercontent.com/5103517/109906954-57bab500-7c6f-11eb-9e85-8044ba06b035.png)

**Comment by Regalis11** [comment]
I'm afraid changing this would require such extensive changes to the way the submarines are rendered (splitting it up to more passes before and after the level is rendered) that it's probably not worth the trouble to change it in order to address a minor problem like this. :/
