### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#518]
Genuine question: why do you have to go through the most fucking painful thing in existence: port forwarding, in this game, but not any other game I've ever played?

Don't Starve Together? No manual port forwarding.

Garry's mod? No manual port forwarding.

Super fighters deluxe? No manual port forwarding.

It's literally this game only, and such fact makes me pissed.

Seriously, this manual port forwarding business is the ONLY REASON people like I do not host servers. This is what is limiting the game's expansion. There are never enough servers, and when one server stops hosting most people are left in the FUCKING DUST. If this was fixed, there'd be more servers, and the player base would most likely fucking EXPLODE.

Seriously, why is this game LITERALLY the ONLY GAME to ever NEED to fucking MANUALLY port FORWARD.

Sorry if this sounded like a rant, but this was after three hours of trying (unsuccessfully) to port forward.

**Comment by AbominationBanisher** [comment]
I mean, my ISP is a piece of shit. And believe me, I don't want to have to be learning "basic networking skills", when my original intent was to play a game with my friends. Just, no.

**Comment by AbominationBanisher** [comment]
By your analogy, I guess we shouldn't even be playing this game. Let alone using a pre built computer. 

Actually, yeah! Why let everybody else do stuff for us! Let's build our own computers! Let's make our own video games!



The problem is, I don't have the time to port forward, as I already tried to do that, unsuccessfully, for the last three hours.

**Comment by NilanthAnimosus** [comment]
Games tend to require some external thing (Such as steam) to perform NAT Punchthrough which is how services like steam manage to connect players together without a port forward (And even then - most games don't manage it and various router brands can prohib it to work quite right)

The other method is UPNP where it attempts to automatically configure ports temporarilly on request which most routers do not support correctly and is of no fault to the game nor networking library it uses - most of them simply break standards as there isn't much of a standard to doing it.

The computer also needs its firewalls to be configured correctly and (If applicable) its anti virus to not block it either or it is simply blocked right at the source.

Networking skills are good to have, and generally it takes minutes to do. It does not sound like you have the patience to port forward so it is better if a friend attempts it.

Port forwarding is simple, and its best described as the following:
Your External IP Address is like a street but you cannot see the houses from the outside.
You have a single package to deliver but need the house number - port forwarding is like telling the delivery man which house number to send the package to.
Without defining that street address you cant simply duplicate the package to go to every house it just doesn't work that way.

To port forward you need:
-cmd prompt (Type IP config, the relevant information will appear there - you record "Default gateway" and "IPv4 Address" on the adapter relevant for your connection, typically "Local Area Connection #")
-Physical access to the router or to ask the one who manages it for its username and password (Usually found on a sticker on the router for its default)
-You type into your browser address box your default gateway (Usually a number like 192.168.0.1 / 192.168.1.1)
-Use the username/password to login
-Find the port forwarding page, it may be under a different name. You can try using a search engine for your router make and port forwarding to get a better idea for its name)
-You will need to use the IPv4 Address from cmd prompt to specify the IP for your computer behind the routers network, not the external IP
-Barotrauma uses UDP port 14242 by default, it shouldn't be harmful to use TCP/UDP as an option if this for some reason does not work. Enter this in as the Port
-Some routers will autorestart themselves on apply, some will not require a restart, and some others may require manually restarting after the rule is added.

**Comment by AbominationBanisher** [comment]
I really love your patience, and after following all your steps, I'll be restarting the router, tommorow. 

Hope your laid out steps help.

**Comment by Regalis11** [comment]
I would guess that all of the games you mentioned use Steamworks to make it possible to host servers without port forwarding, which we can't do yet until the game is out on Steam. Anyway, NilanthAnimosus gave such a thorough explanation that there's not much else to say, I hope you can get your server working and I'm sorry that setting it up is such a pain at the moment!

**Comment by AbominationBanisher** [comment]
Yeah, it worked.
