### ISSUE TITLE
[0.1300.0.1] Bots report characters being "back in shape" even if the bot didn't actually treat them

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5180]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots report characters being "back in shape" even if the bot didn't actually treat them

**Steps To Reproduce**
Happens when a target has very minor injuries (below the treatment threshold which is 5% on most afflictions)

**Version**
0.1300.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b04af9b3f502fa6eeeacc43d982df8bdbf03e03

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
