### ISSUE TITLE
Some monsters go down infinitely after trying to atack (Unstable)

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5182]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Certain hostile creatures start going down vertically after getting near the submarine (which i assume is a try to atack)
So far this happened with mudraptors, crawlers and moloch_m (haven't seen any non _m molochs yet)

**Version**
Unstable v0.1300.0.1 Windows

**Comment by Rokvach** [comment]
I added a bit more info about this in here #2447

**Comment by LePiromano** [comment]
It seems that every creature variant (hatchling, unarmored) has this issue

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/55aa20ccdf27e6c24206b520a894f2bb3c6c31d0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
