### ISSUE TITLE
Unstable - Maximum nav terminal output cannot completely fill ballast on small-ratio submarines.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5183]
With the changes to fix maintain-position ballast code, now submarines with very large ballast volumes are unable to fully fill even when navigation terminal is on maximum downwards setting. When ballast ratio is low enough, nav terminal does not seem to be able to output a high enough output that when multiplied equals a ballast level of 100.

![image](https://user-images.githubusercontent.com/55356135/110151417-75426880-7dae-11eb-9c98-ad123f1cbda3.png)

**Comment by Regalis11** [comment]
Potentially related https://github.com/Regalis11/Barotrauma/issues/5108

**Comment by Ek-Videogames** [comment]
Indeed may be related, or might be a separate clamping issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a113c1de9ccf6e5108b1b52cccff0dcd2210377

**Comment by Ek-Videogames** [comment]
v0.1300.0.3 on subs with absurdly large ballast pumps still seem to know how to eventually fill the whole volume. Appears fixed.

**Comment by Rokvach** [comment]
Closing
