### ISSUE TITLE
unstable - terminals do not receive signals as a result of their output.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#5185]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Sorry for the vague title, my understanding of the problem is limited. A terminal was connected to an array of signal checks, outputting various text messages back, in response to simple commands such as 'help'. In unstable no response comes from signal check components, with text or numerical inputs, with items placed before or after switching to unstable. The terminals still output and receive signals from other items (including other terminals), but no text is displayed if the received signal is the result of this terminals input.

**Steps To Reproduce**
Terminal (signal_out) - signal check component (signal_in - signal_out) - same terminal. No visible result when inputting the correct target signal.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b1cd0ef3bfe2af1150185270282e34973b4ac541

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
