### ISSUE TITLE
Spawns don't seem to avoid overlapping subs/other creatures/blocking some paths

### ISSUE THREAD

**Issue by LHJ** [Regalis11/Barotrauma#5187]
- [X] I have searched the issue tracker to check if the issue has already been reported.
Checked for spawn and Hydrothermal just in case.  

**Description**  
Sometimes enemy monsters/structures spawn too close to players, or occasionally themselves.   
Examples:  
- Two black molochs spawning ~5-10m from the sub, stacked so that they look like one, until they split.  
- Spinelings spawning inside of the sub, shooting and killing part of the crew instantly.  
- Matriarch spawning inside of the ship, being unable to shake loose, constantly rocking the ship and hiding most of what you want to shoot (also its little hammerheads spawned inside and suffocated after the head popped).  
- Alien ruins spawning _basically_ touching the sub such that you can't redock after undocking.  

**Steps To Reproduce**
Not a clue, but it seems to have started recently (we've been playing semi-frequently before the new campaign came and got to the Hydrothermal Wastes yesterday, and the weird spawning started yesterday/today as far as we can tell, with the alien ruins being the first instance about 1h after we got there). We are using the stock Typhoon 2, if at all relevant.  

**Version**
Latest, which afaik should be v0.12.0.3. Windows 10 (server host and clients). 

**Additional information**
Some pics (the Moloch one was just after they split)
![20210306222308_1](https://user-images.githubusercontent.com/17006123/110224211-e9c5f600-7ed9-11eb-8e8f-e4ef23150676.jpg)
![20210306234253_1](https://user-images.githubusercontent.com/17006123/110224220-f6e2e500-7ed9-11eb-9de0-7d17fe6aa5c7.jpg)
![20210306235407_1](https://user-images.githubusercontent.com/17006123/110224222-fea28980-7ed9-11eb-8ab3-04f840d442fc.jpg)  

![image](https://user-images.githubusercontent.com/17006123/110224379-6907f980-7edb-11eb-8b59-871804501136.png)
![image](https://user-images.githubusercontent.com/17006123/110224384-76bd7f00-7edb-11eb-8cd7-829a03eb87de.png)
![image](https://user-images.githubusercontent.com/17006123/110224382-72916180-7edb-11eb-8f0b-5979ee51bf5f.png)

Ayy  
![20210306015033_1](https://user-images.githubusercontent.com/17006123/110224423-c13efb80-7edb-11eb-8bfa-80a260e6832c.jpg)
![20210306015034_1](https://user-images.githubusercontent.com/17006123/110224425-c13efb80-7edb-11eb-8aeb-2d3b66642780.jpg)
![20210306015329_1_edit](https://user-images.githubusercontent.com/17006123/110480900-4b0ee480-80e7-11eb-9f26-2a4936d5590b.jpg)

**Comment by itchyOwl** [comment]
I think I fixed this a while ago. Moving to QA.

**Comment by itchyOwl** [comment]
Actually that fix might not have been enough: https://github.com/Regalis11/Barotrauma-development/commit/375dc34.

**Comment by Regalis11** [comment]
Related (or duplicate?): https://github.com/Regalis11/Barotrauma/issues/4832

**Comment by Regalis11** [comment]
Happened in the following level, it seems that a cave was generated in open water:
https://files.slack.com/files-pri/T0D058T4P-F032ZUF6DEU/image.png

**Comment by itchyOwl** [comment]
Possibly related: #10026

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/84b88bb46a200a26bff62566914098699fce08ee?

**Comment by Rokvach** [comment]
There hasn't been any sighting of creatures spawning inside the sub, so the above fix seems to have fixed the issue. Seems to be working correctly, closing.
