### ISSUE TITLE
Pulse Oscillator does not trigger memory component lock_state

### ISSUE THREAD

**Issue by pixartist** [Regalis11/Barotrauma#5192]
When trying to set up some timing with memory components, I realized that the oscillator does not actually provide any relevant signal to the lock input of the memory component when set to emit a pulse signal.

How to reproduce: Connect an oscillator output to a memory component lock_state. Feed the memory a varying signal and connect the output to a text display.

Expected behavior: The value of the memory component will updates at the interval of the pulse component
Actual behavior: The memory component never updates its value

**Comment by tiba666** [comment]
pulse sends a pulse of 1and nothing else like the tool tip say what a pulse does..  and to lock_state a memory you will need to send a 0 and to open it agian you need to send 1.  so pulse can only open for the memory lock and not lock it. 

you can think it about like a button  a button can also only unlock a locked_State memory but not lock it its not like a togle_state like the relay have
