### ISSUE TITLE
Unstable : Command-spawned crewmembers do not seem to have jobid:(job) tags on their id cards.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5193]
_(This is probably a low priority issue as it only affects crew spawned with cheats / in testing.)_

With the addition for controller components to detect the "hidden" `jobid:` tag it added new possibilities for ID secured containers and improved ID tag compatibility between different custom submarines. However in some testing I noticed that command-spawned crewmembers do not seem to have their ID recognized when testing using this tag-workaround method.

This is rather annoying as spawning crew via commands is the only way to get security officer & medical doctor in sub editor test-mode in order to debug job permissions, and this prevents the tag workaround for being usable with the fresh-spawned crew in this case.

**Steps to Reproduce:**
- Submarine with a locked door/cabinet/button with the picking requirement `jobid:captain`
- Captain spawnpoint with no additional tags added
- Test mode: 'Original' captain with no 'custom' ID tags can still pick the item because of their detected `jobid:captain`.
- `spawncharacter captain cursor`
- The command spawned captain is unable to pick the item.
even though they should be the same fresh ID with no tags apart from jobid?

**Expected Behavior:**
Both captains should be able to pick the item.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d84255f28ce7e545198eaeed0b3f67bc4c8631c6

**Comment by Rokvach** [comment]
Spawned humans don't seem to get access to certain things the class otherwise has access to, medic can't access the toxic cabinet, security officer can't access armory etc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
