### ISSUE TITLE
Sub editor waypoints do not correctly update their colours

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5194]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There seems to be an issue with new waypoints' colour not updating in the editor when they've just been placed or generated. Unless you use the sub editor test mode, the waypoints will continue to appear blue even if inside the submarine.

**Steps To Reproduce**
Create a new file in sub editor
Create a basic hull with 4 walls and a spawn point
Generate waypoints
 - Notice all waypoints are blue
 - Notice that moving or nudging the waypoint does NOT update its' colour either

Hit test mode
Return to editor
- Notice the waypoints being of the correct colour now and properly updating.

**Version**
Windows 10, Barotrauma V. 0.12.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ff521d2c0dae37e91162c740a3a11497ace176e

**Comment by Ecchi-Ki-Senpai** [comment]
Tested in 1300.0.9, working correctly

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. Closing.
