### ISSUE TITLE
"Biome access" outposts can be abandoned

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5195]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The outpost that gives you access to the next biome can be abandoned.

**Version**
Unstable v0.1300.0.1 Windows
![20210307212615_1](https://user-images.githubusercontent.com/55637865/110261092-8dbca980-7f8d-11eb-83ad-8733bdea2050.jpg)
![20210307213419_1](https://user-images.githubusercontent.com/55637865/110261093-90b79a00-7f8d-11eb-80c6-97757626594a.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/49be4db13f253f36f35308ef554cbaf6ac59bcbf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
