### ISSUE TITLE
Reinforced Artifact Room + Coil Trap + Power Generator causes entry to be impossible

### ISSUE THREAD

**Issue by paxone** [Regalis11/Barotrauma#5198]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Due to the generation of the game, artifact rooms can spawn with coil traps and unreachable generators making the mission impossible to beat. If the rooms weren't reinforced you could break into the part to shut it down, but that isnt possible in this case. The player is unable to get around this in game and try to shut down the generators to get to the artifact.

**Version**
 0.12. 0.3

**Additional information**
I can understand the need for reinforced rooms, and even coil traps within the area of the artifact to enhance the gameplay and skill of players. This isn't possible to work around though and would require changes within the game to allow the player to actually make it through at all.

**Comment by Regalis11** [comment]
The alien ruins are randomly generated, and in some unlucky cases this can lead to unfair trap arrangements, but usually there should be ways around the traps: for example, letting water in the room to gain access to the generator or disabling the generator with an EMP grenade.

It could be possible though that in some situation the room really is impossible to pass. Do you happen to have a save file where this occurred so we could give it a test?

**Comment by Regalis11** [comment]
Thank you, if you could provide us some screenshots that'd help a lot!

**Comment by paxone** [comment]
Hopefully these can show the layout well enough to explain the situation! Taken from the clip I had.
![Capture4](https://user-images.githubusercontent.com/80257048/110711759-300db300-8254-11eb-9f2c-1cddc7698126.PNG)
![Capture6](https://user-images.githubusercontent.com/80257048/110711783-3a2fb180-8254-11eb-8b07-60642300a201.PNG)
![Capture5](https://user-images.githubusercontent.com/80257048/110711797-3e5bcf00-8254-11eb-8277-e152b01ea76a.PNG)
![Capture3](https://user-images.githubusercontent.com/80257048/110711818-43b91980-8254-11eb-9857-9c9e560b5047.PNG)

Each time I would try getting past the motion sensors they'd go off. Last screenshot I tried to get close enough to damage and was killed.

**Comment by danielasteljoki** [comment]
Ruin generation issues like this should no longer occur when we move onto the new generator. Closing.
