### ISSUE TITLE
Railgun bug (While editing sub)

### ISSUE THREAD

**Issue by yaelatletl** [Regalis11/Barotrauma#52]
Railguns do not link to their ammo holders, and trying to rewire the Railgun controler ends up in a crash
![imagen](https://user-images.githubusercontent.com/28612272/33501537-8c76a7a2-d6a2-11e7-9339-cec48ae222b7.png)

**Comment by CryIz** [comment]
It is also impossible to link the generator air ventilation. Personally, the game gives an error.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma/commit/5cb603b3e56d616b902fb1c67a9b3092309f33ae and https://github.com/Regalis11/Barotrauma/commit/343b8efd871305de039c0858be49c3ed8ecceaf4
