### ISSUE TITLE
Shuttle stuck in the ceiling

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#520]
I don't know if this was reported before, but I think that this is an enormous error.

**Comment by ZealanL** [comment]
Yeah, it's understandable why it happens though. If the main sub is pressed against the ceiling, where should the shuttle go? Perhaps it should push the main submarine down? The most annoying part is players exiting the shuttle only to get stuck in the ceiling. The shuttle can leave the ceiling unless you go up too far. Definitely a bug. Maybe spawn the shuttle right under the ceiling if necessary? Force the main submarine to move?

Anyway, this has been a bug for a really long time. Definitely needs a quick fix, one of these suggestions will probably work. I can fix it myself and make a pull request if necessary.

**Comment by NilanthAnimosus** [comment]
No, I have witnessed this bug and it has nothing to do with being sandwiched by submarines.

I have seen the respawn shuttle fail to pass through the level boundary on multiple occasions now, such as on spawn and on return - Where it will literally sit there without a visible timer auto piloting back to the spawn stuck on its ceiling (Unable to pass through it).

**Comment by Regalis11** [comment]
Should be fixed for the next patch, as the shuttles now spawn inside the level instead of above it.

**Comment by Rokvach** [comment]
Tested, working correctly now. Closing.
