### ISSUE TITLE
Cave generated only halfway

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5200]
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/d814eaf93f40fb2f0ea0b5d3ef37f72ac29c1db8
Multiplayer
Game mode: Monster mission
Seed: lrswJi9G

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d5a4966a-2d58-4eef-9761-c179dcec2a6d)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b8c6f0e7405739c1e8de9d243f6a2c05ded6bd00

**Comment by Rokvach** [comment]
Tested, I didn't notice any issues. Closing.
