### ISSUE TITLE
Typo in aphotic plateau to great sea access unlock

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5202]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Im going from the aphotic plateau to the great sea, but the text says i went trough the "ridge" to get to the great sea.

**Version**
v0.1300.0.1 unstable Windows
![20210308122449_1](https://user-images.githubusercontent.com/55637865/110342348-0feab380-800a-11eb-83cd-14fe115f0245.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bbc5e172d11be4111ba82b7b4bd90e82c61deeb4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
