### ISSUE TITLE
Biome access outposts located incorrectly

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5203]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outposts that give you access to the next biome sometimes spawn one path too early, "bro....zip" is a save with an example (between the great void and the hydrothermal wastes)

**Version**
v0.1300.0.1
![20210308140145_1](https://user-images.githubusercontent.com/55637865/110371609-f9555400-802b-11eb-8bc7-0b96f100992d.jpg)
[Bro....zip](https://github.com/Regalis11/Barotrauma/files/6103714/Bro.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2b39df7a2a4898dc0135cd6681e33a92506d2e8

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
