### ISSUE TITLE
[XML] [Design] Diving suit's damage multipliers affect some afflictions/identifiers twice

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5204]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
divinggear.xml has this under the diving suit:
```xml
<damagemodifier armorsector="0.0,360.0" afflictionidentifiers="bitewounds,blunttrauma,lacerations,gunshotwound" damagemultiplier="0.8" damagesound="LimbArmor" deflectprojectiles="true" />
```
and
```xml
<damagemodifier armorsector="0.0,360.0" afflictionidentifiers="bitewounds" damagemultiplier="0.5" damagesound="LimbArmor" deflectprojectiles="true" />
<damagemodifier armorsector="0.0,360.0" afflictionidentifiers="lacerations" damagemultiplier="0.5" damagesound="LimbArmor" deflectprojectiles="true" />
```
Which makes `bitewounds` and `lacerations` have a 0.4 effective multiplier, as I'm guessing.

**Version**
v0.12.0.3

**Additional information**
It's literally the same `identifiers` listed twice, so it doesn't look intentional.

**Comment by Ek-Videogames** [comment]
Some crew uniforms define the damage resist for the generic category of 'damage' which covers all damage types, but then go on to specify bitewounds specifically or burns later on. Although in this case it might be intended as a XML shorthand method of stacking a bit more resistance on top of the already existing blanket protection.

**Comment by itchyOwl** [comment]
It seems the issue was introduced in Regalis11/Barotrauma-development@8015905, which was in last August. I just removed the identifiers from the first modifier definition. Could you @ezjamsen check this one?

@Ek-Videogames, which crew uniforms did you mean? I couldn't spot any issues.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
