### ISSUE TITLE
Unstable - Crew AI can't weld leaks anymore

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5205]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When ordered to fix leaks, crew AI is able to move to the leaks' location but are unable to weld it. They simply stay in front of the leak and wait. If the leak is fixed, by a player for example, bots go back to their other tasks

**Steps To Reproduce**
Create leaks on a submarine, I have noticed the issue on the Dugong so you may use this submarine as well.
Order the AI to weld the leaks
Notice the AI sitting in front of the leak without doing anything.

Note: In my tests, the AI had welders and welding fuel tanks in their inventory

**Version**
Windows 10, Unstable - V0.1300.0.1
![unknown (1)](https://user-images.githubusercontent.com/55001203/110508685-42aaaf80-80cf-11eb-857c-1448ac174845.png)
![unknown(2)](https://user-images.githubusercontent.com/55001203/110509231-e4320100-80cf-11eb-8910-8ce7143f8d71.png)

**Comment by Rokvach** [comment]
Encountered this as well, the bot just stands next to the leak with a welder on his hand not actually fixing it but just looking at it

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d7de82ad-45b4-44cd-ad68-9a4cd01d539a)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/faacb8bb-5a20-4177-92f0-b11ef95c5cf7)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7029a98c-5da7-4b58-bb9a-0aa5e303a360)

**Comment by Rokvach** [comment]
This can also lead to bots suffocating as they don't move anywhere even if the hull is flooded

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c1db65c.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
