### ISSUE TITLE
Players get disconnected when a Husked player dies or loses consciousness (modded server)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5206]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This happened thrice on the same modded server.
First time, I was next to an AFK Husked player and when he lost consciousness, I got disconnected.
Second time, I was Husked and when I pressed "GIVE UP", dying, half the players on the server got disconnected with me.
Third time, I was spectating and a Husked player died, and at least me with someone else got disconnected.

**Steps To Reproduce**
It did not happen each time but here's the load order:
![Barotrauma_2tBQ77f9ZW](https://user-images.githubusercontent.com/10529134/110552482-b680a280-8137-11eb-9a5d-e029a4f34ba9.png)
![Barotrauma_sCyebAtwEo](https://user-images.githubusercontent.com/10529134/110552489-b8e2fc80-8137-11eb-9b2d-fd3612f398ee.png)

**Version**
v0.12.0.3 Windows 20H2

**Additional information**
1. [networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/6110834/networkerror_data.log)
2. [networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/6111243/networkerror_data.log)
3. [networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/6112016/networkerror_data.log)

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
