### ISSUE TITLE
text displays / text labels poor image quality / scale blurry

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5210]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Scaled up text in labels/text displays pixelates really badly
Expected is to use bigger pt font

**Steps To Reproduce**
1. place text display/text label
2. type something in
3. scale the label up 

**Version**
0.12

**Additional information**
At scale 10 for emphasis
![image](https://user-images.githubusercontent.com/5103517/110593160-38c59280-8149-11eb-9111-36561f77f417.png)

**Comment by Tsunder** [comment]
point: using labels/text displays would be preferred for larger text over using the letter labels, as text displays and labels offer two major benefits:
1. Localization
2. Mirrors nicely

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. This is more of a feature request than a bug report. Closing.
