### ISSUE TITLE
[AI] Bots can sometimes place multiple fuel rods in to the reactor

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5213]
I had the game tabbed out for a solid 30 min to 1 hour and a bot somehow managed to place in a second rod inside the reactor causing the reactor to catch on fire, there was a empty rod on the ground in front of the reactor, so he definitely were replacing rods, but not sure how he managed to get two in there

No known reproduction steps, I've tried by just being afk for a long time while a bot is operating the reactor and couldn't get it to happen, tested in singleplayer however. Will need to take a look at it in multiplayer which I believe I encountered the issue first time

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/89928711-5afc-4853-8467-a576befb3dc8)

**Comment by Phlaxith** [comment]
It also appear in multiplayer, and in addition of putting 2 rodes, they put down some rods on the ground that are barely consumed (9x%).

As a reproduction :  playing Remora ship, try to put a bot on reactor, whatever full manual direction on navigation, and click on "secondary engine", the bot will try to manage the energy spike and will certainly burn everything 😁

**Comment by Rokvach** [comment]
Noticed a dropped 90-99% full rod in front of the reactor today whilst a engineer bot was using it

**Comment by itchyOwl** [comment]
Possibly duplicate of #5259?

**Comment by CurePindal** [comment]
> 
> 
> Noticed a dropped 90-99% full rod in front of the reactor today whilst a engineer bot was using it

Still an issue in 1300.0.7. (tested SP vanilla) 
Havent caught a bot in the act so far, so no idea when they fuck it up.

**Comment by ekqvist** [comment]
> cleanup command also doesnt apply to any of those rods

Is it possible that the related cabinets are full? As far as I know, items are only put in preferred containers when bots are cleaning up, and for fuel rods that means only containers tagged as "reactorcab". On Humpback, for example, that means only the cabinet closest to the reactor. I just tested it and managed to get bots to successfully clean up partially used fuel rods.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@aefa5af. Closely related to #5503.

**Comment by Rokvach** [comment]
Tested, haven't seen this happening since the fix, working correctly. Closing.
