### ISSUE TITLE
[Unstable][Design][Submarine] R-29 extinguisher support misplaced

### ISSUE THREAD

**Issue by Phlaxith** [Regalis11/Barotrauma#5216]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An extinguisher support in the medical center is hidden behind a locker. It shouldn't even exist here.

Image taken in-game
![unknown](https://user-images.githubusercontent.com/32924025/110657816-71a14e00-81c1-11eb-99b8-12e14b5ccaaa.png)

I did go in editor to see what was going on :
![Barotrauma](https://user-images.githubusercontent.com/32924025/110658149-bb8a3400-81c1-11eb-9fc1-51174f1a2cbb.jpg)

WELL here you are sneaky boi
![Barotrauma_1](https://user-images.githubusercontent.com/32924025/110658290-d8bf0280-81c1-11eb-8620-1e0d12473e59.jpg)

There is definitely something with these supports...

**Steps To Reproduce**
Reproductible everytime.

**Version**
V0.1300.0.1 WINDOWS

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/841dd2d

**Comment by Rokvach** [comment]
Closing this as its listed on the main ticket about the fixes
