### ISSUE TITLE
[UI][Lobby] Bots number selection inactive

### ISSUE THREAD

**Issue by Phlaxith** [Regalis11/Barotrauma#5217]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Starting a campaign, the input number for "bots number" is set to 0 and cannot be incremented or decremented whether the apparition mode is NORMAL or FILLING.

![Barotrauma_bots_number](https://user-images.githubusercontent.com/32924025/110664500-bcbe5f80-81c7-11eb-9cfa-f80df9b4c7cf.jpg)

**Steps To Reproduce**
host a server, click on campaign mod, modify settings.

**Version**
V0.1300.0.1 WINDOWS

**Comment by Rokvach** [comment]
This has been fixed for the next Unstable build already, closing.
