### ISSUE TITLE
Game wont launch if have too many store purchases

### ISSUE THREAD

**Issue by ursinewalrus** [Regalis11/Barotrauma#522]
Specifically if you have too many buys such that all types that go in a specific container don't fit in it, the game will fail to launch and give you a dictionary no key error. 
![barobug](https://user-images.githubusercontent.com/4681514/43144527-f6b351ea-8f22-11e8-8ed4-d6d4510c8cf2.png)
For Example, if you buy 21 flairs or 11 bandages, your last flair or bandage won't fit in the container and it will try to remove a space from an empty container.

**Comment by ursinewalrus** [comment]
https://github.com/Regalis11/Barotrauma/pull/523/files

**Comment by Regalis11** [comment]
Closed in 2705edd
