### ISSUE TITLE
Both of the abyss creatures can spawn during hunting grounds mission

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5221]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During a hunting grounds side quest mission, an endworm spawns, but that doesn't stop a charybdis from spawning when you enter the abyss to kill the target endworm, which is unfair for any player experienced or not.

**Version**
Unstable v0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5b9a4146dff3984628122fa0baa0c392795603ee

**Comment by Rokvach** [comment]
Tested, only seeing Endworms now. So at least they aren't both spawning anymore. Closing.
