### ISSUE TITLE
Rejected from entering next biome having the reputation needed

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5222]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The lock asks for 30 coaltion rep, i have 30 coaltion rep, but it rejected me when i spoke with the npc.

**Version**
v0.1300.0.2 Windows
![20210312124211_1](https://user-images.githubusercontent.com/55637865/110963346-b7c8ef80-8330-11eb-9809-d98c8785c9a2.jpg)
![20210312124215_1](https://user-images.githubusercontent.com/55637865/110963350-b992b300-8330-11eb-8c1d-6e83e5eaa6c9.jpg)

**Comment by LePiromano** [comment]
Here's the save where this is happening.
[the poopenfarden.zip](https://github.com/Regalis11/Barotrauma/files/6131170/the.poopenfarden.zip)

**Comment by LePiromano** [comment]
This only seems to happen when you have the EXACT reputation needed

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/22ae9db20370fed9be42702db990ca6de1ff7a28

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
