### ISSUE TITLE
[Unstable] - On some levels, natural formation entrances will be blocked by map gen

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5223]
**Description**
You can't go back to the route selection menu as the entrance is blocked.
![routeblock](https://user-images.githubusercontent.com/72674994/110967905-ddd2ac00-8391-11eb-880a-99703447a90d.jpg)

**Steps To Reproduce**
Seen in this save provided
[routeblockoverload.zip](https://github.com/Regalis11/Barotrauma/files/6131365/routeblockoverload.zip)

**Version**
V0.1300.0.2

**Comment by LePiromano** [comment]
This probably only happens in the greate sea with the piezo crystal icebergs, i've also seen them block side paths

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/416d8a8e2acd46f4316a86148ebec4aa7e112cf4

**Comment by Rokvach** [comment]
Tested, didn't find any. Seems to be working correctly,  Closing.
