### ISSUE TITLE
[Unstable] - Hunting grounds can't be removed even after killing endworm.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5225]
**Steps To Reproduce**
-Load a campaign save
-Travel to a route with hunting grounds
-Complete the side mission by killing Endworm
-Travel back to either ends and dock/end round and observe map

**Version**
V0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b046316165aa84f741cf50ce50ea2d43a7e493c6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
