### ISSUE TITLE
[Unstable] - All hunting grounds are cleared on map upon completing 1 campaign ending

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5226]
**Description**
All hunting grounds on the map will be wiped upon completing the first playthrough and triggering the ending of the save.

**Steps To Reproduce**
-`togglecampaignteleport` 1 location before the end and travel to the end
-Complete endlocation and trigger ending
-When spawned back with the "refreshed" map, proceed to check it for hunting grounds

**Version**
V0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ec0be29f8752feeb21324954236e6b03c54e4360

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
