### ISSUE TITLE
Changing the name of an NPC crewmate doesn't update their ID

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5227]
- [yea ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Changing the name of a crewmember at an outpost will not update their ID card, so whenever the crewmate is "disguised" it shows their original name

**Version**
v0.1300.0.2
![20210312143929_1](https://user-images.githubusercontent.com/55637865/110977682-3594f700-8341-11eb-80ba-c4fffb3028bc.jpg)
![20210312143928_1](https://user-images.githubusercontent.com/55637865/110977692-375eba80-8341-11eb-85bb-0d306a87321b.jpg)

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@068cf58

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
