### ISSUE TITLE
"current reputation" in the biome lock shows the outpost reputation

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5228]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The lock to the next biome (in my situation, the hydrothermal wastes) states it requires 75 Europa Coaltion reputation, but the "current reputation" that the lock shows is not the Europa Coaltion rep, it's the current Outpost rep.

**Version**
Unstable v.1300.0.2

![20210312190323_1](https://user-images.githubusercontent.com/55637865/111003539-19578100-8366-11eb-9327-2ec7d59dfbd3.jpg)
![20210312190328_1](https://user-images.githubusercontent.com/55637865/111003544-1b214480-8366-11eb-9e4e-6c38a05fa9c0.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e3299c2f86c38c56301bc9af16460b2af1d9a8dd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
