### ISSUE TITLE
[Unstable 13.0.2] No green progress indicator when crafting on a stack

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#5230]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When crafting the 2nd-8th of a stackable item in the Fabricator, the green progress indicator does not appear.

**Steps To Reproduce**
1) Craft multiple of any stackable item
From the second item onward, the green progress indicator will not appear

**Version**
Unstable 0.1300.0.2, revision f18186e1c6
Windows 10

**Additional information**
video: 
https://cdn.discordapp.com/attachments/668819422919524352/820302100067647488/Barotrauma_2021-03-13_10-12-06.mp4

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@06203ee

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
