### ISSUE TITLE
[Unstable] [Modded] Overrided afflictions can't increase/decrease their own strength.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#5231]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When overriding any affliction, it will become completely unable to increase / decrease itself through the "strengthchange" parameter (tested with an exact copy of the normal husk infection and sufforin poisoning). Custom non-overrided afflictions work properly.

**Version**
V0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7100e2623d758a799d3a095dcabd58c0e7ee06d

**Comment by Emanthealmighty** [comment]
Fixed as of version V0.1300.0.3 (Unstable)

**Comment by Rokvach** [comment]
Closing
