### ISSUE TITLE
[Unstable] - Submarine editor filter resetting when swapping categories

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5233]
**Description**
The filter will not apply and will refresh upon selecting another category.
It was fixed and addressed in commit 32f3c3f by @3e849f2e5c but seems like the issue came back.

**Steps To Reproduce**
Type door into search bar and swap between categories

**Version**
V0.1300.0.2

**Comment by 3e849f2e5c** [comment]
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/ada29c9f7081cf241f927a15c1777988f7e27b87

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
