### ISSUE TITLE
Remora pumps not working

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5236]
![image](https://user-images.githubusercontent.com/59519434/111055352-49417a00-8475-11eb-9bda-b6b9aa5fd03e.png)
These 2 pumps dont pump out water by default. I don't mean to talk into your work, but I recommend:
-testmode
-commands: freecam, lighting,water
-click in rooms to spawn water in, which will test the pumps for you quickly
For every new pump/change of pump. Takes a couple seconds.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7d9e7318ba104215e14bc5674866080b6ced8e7

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
