### ISSUE TITLE
Floating artifact due to a quirk in map generation

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5237]
**Description**
Artifact spawned floating in place in the save provided.
![floatA1](https://user-images.githubusercontent.com/72674994/111055652-35b50400-84b3-11eb-9f85-bda6d08c84e9.jpg)
![floatA2](https://user-images.githubusercontent.com/72674994/111055654-377ec780-84b3-11eb-9e86-692327886106.jpg)

**The save**
[Floatingartifactgen.zip](https://github.com/Regalis11/Barotrauma/files/6135984/Floatingartifactgen.zip)

**Version**
V0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a920a902ee7a29449639d2f0342cd32e68d4f53d

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
