### ISSUE TITLE
Plasma cutter does not work on alien doors.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5239]
Previously it was possible to crowbar as well as plasma cut alien ruin doors, however now it seems cutting does not affect alien doors and the beam just goes through and hits whatever is behind the door. (be it a character or wall structure)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e65158bb214b20a0e5c92edf7e7ddf735ea6ca7e

**Comment by Xeavas** [comment]
[v0.1300.0.3] - No issues, working correctly. 👍

**Comment by Rokvach** [comment]
Closing
