### ISSUE TITLE
Unstable - Submarine editor - Delete key has Inconsistent behaviour (REEEEEEEEEEE I CAN'T DELETE)

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5240]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Opening the item panel with Q causes some sort of focus on the panel so you can't delete items anymore
Closing the item panel with Q causes focus to go back on the world and allows you to delete items

This is the issue:
Closing the item panel with LMB does not give back focus on the world and delete key is blocked
Reopening the panel with Q gives back focus on world and allows you to delete items despite having the item panel opened

**Steps To Reproduce**
See video

**Version**
v.0.1300.0.2

https://user-images.githubusercontent.com/55001203/111073558-a3fac600-84b5-11eb-95d0-260a1d4d0967.mp4

**Comment by Udrakan** [comment]
I keep having issues where key presses of some keys stop working, most notably the delete and arrow key inputs. Pressing Esc two times (to pause menu and back) seems to fix this for me

**Comment by Udrakan** [comment]
https://discord.com/channels/103209684680323072/668819422919524352/796264515221454859
Heres a vid of this hapenning in the event editor, but it hapens with delete and arrow keys for me in game and editor this patch for some reason.

**Comment by Ecchi-Ki-Senpai** [comment]
This seems to affect all keys that interact with the selected object: 
arrow keys, Ctrl^C, Ctrl^V

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/39ef454339dd9cdcde2e540c1bd817ce1252312d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
