### ISSUE TITLE
Unstable - Submarine editor - HSV colour panel does not properly update

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5241]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
HSV colour panel in submarine editor does not properly update when using the HSV sliders

**Steps To Reproduce**
See video

**Version**
v.0.1300.0.2
![HSV bug](https://user-images.githubusercontent.com/55001203/111074505-a2cb9800-84b9-11eb-825e-ef570d1bf558.gif)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bbfb8cd96d927b1f6b8e8429196f398b3e4d2a77

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
