### ISSUE TITLE
Remora drone vs bot AI issues

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5242]
**Description**
In this spot, bots have trouble
-cleaning up the clown item
-fixing damaged wall
-gif:
![bug_remora1](https://user-images.githubusercontent.com/59519434/111074671-67928e80-84e4-11eb-8261-5bb4bf93a4a9.gif)

**Additional information**
Consider it a non-issue if it takes more work, but currently theres no reason to make drone's engine invulnerable, since now it can be reached compared to previous versions and repaired. It's a bit cheaty to have it not deteriorate, hence this comment:
https://github.com/Regalis11/Barotrauma/issues/2971#issuecomment-639118126
Also, these hatches don't have platforms. Character gets up by smashing him self with the hatch when they close it.

**Comment by itchyOwl** [comment]
I didn't notice any issues with cleaning up things, but the waypoints were not connected to the ladders, so there was no path to the ballasts. Fixed that in Regalis11/Barotrauma-development@6c083f1. Could also be that #7274 affected also this: if the drone was undocked and then re-docked the path was permanently gone.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
