### ISSUE TITLE
Unstable - Submarine Editor - Submarine class selection menu does not appear when declassifying a submarine as shuttle

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5243]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Submarine class selection menu does not appear when declassifying a submarine as shuttle

**Steps To Reproduce**
See video
1)Save a submarine file as shuttle
2)Open the save file menu and declassify as shuttle
3)The submarine class selection menu does not appear

**Version**
v0.1300.0.2

https://user-images.githubusercontent.com/55001203/111074805-39e51f80-84bb-11eb-8be6-b8927cb6c1ec.mp4

**Comment by ekqvist** [comment]
The "Class" dropdown should now be enabled based on the "Shuttle" tickbox state (Regalis11/Barotrauma-development@009acdc)

**Comment by Ecchi-Ki-Senpai** [comment]
This does not work in v.1300.0.9
![image](https://user-images.githubusercontent.com/55001203/114743464-b5382c00-9d1a-11eb-89ab-e3ff417a7d4f.png)

**Comment by ekqvist** [comment]
The change was made after the release of v0.1300.0.9

**Comment by Ecchi-Ki-Senpai** [comment]
My bad. I confused everything

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue. Working correctly, closing.
