### ISSUE TITLE
All lights are on when previewing them in the sub editor

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5245]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Enabling lighting visibility displays all lights as if they were ON despite if they are OFF by default after loading a submarine file
If `Lighting Visibility` was enabled prior to loading a submarine file, all lights will appear OFF and toggling lighting visibility OFF and ON again will make all lights appear ON despite being OFF by default

**Steps To Reproduce**
See video
1)Create a basic submarine file
2)Place a few light components with default settings (OFF)
3)Save the file
4)Open the file again and enable lighting visibility

**Version**
v0.1300.0.2

**Additional information**
The issue fixes itself when pressing the `Test` button
The issue does not resolve when toggling lighting visibility ON&OFF
All lights are OFF when returning to the Submarine Editor from Test mode despite lights being ON by default if Lighting visibility was enabled prior to testing the sub. Toggling lighting visibility OFF and ON again does fix the issue

https://user-images.githubusercontent.com/55001203/111075859-3ef89d80-84c0-11eb-93ee-28640b22834f.mp4

**Comment by Regalis11** [comment]
This is actually intentional: it makes it easier to adjust lights that aren't on by default (e.g. emergency lights or indicators that only turn on in some specific situation). I'm not sure if this is something we should change; I suppose those lights could also stay off and be adjusted by turning them on manually.

**Comment by Ecchi-Ki-Senpai** [comment]
I'm fine with it either way personally.  The issue is that it's not doing either consistently. 

Only when the file is first loaded will all lights appear ON
But placing new lights that are OFF will not be displayed when lighting visibility os enabled

**Comment by Regalis11** [comment]
Fixed that one in https://github.com/Regalis11/Barotrauma-development/commit/01b8b7030128a0efd81f3c6b4e27a014e1aae9bb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
