### ISSUE TITLE
Outpost Event confuses electrical engineer and mechanic

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5246]
**Description**
Event name: Engineers_are_special
This event checks for mechanical skill
![](https://media.discordapp.net/attachments/668819422919524352/820693961604726794/unknown.png)
-event sprite shows a man in yellow clothes (colour of electrical engineer)
![image](https://user-images.githubusercontent.com/59519434/111076511-d83da900-84ec-11eb-85db-d5f40a0c6775.png)
-event NPC speaks of "engineering crew"
-event name "Engineers..." might be ok because players don't see event names

Some quick text changes to inform players that it's *mechanical* that they need and/or changing the sprite's clothing colour could be enough to polish this event.
Sprite suggestion: (source - ITA)
![image](https://user-images.githubusercontent.com/59519434/111076518-e095e400-84ec-11eb-941c-d37804876096.png)

**Comment by Regalis11** [comment]
I don't think there's anything wrong with the texts: in my opinion describing the NPC as "engineering crew chief" doesn't imply you need electrical skills to repair the engine. Let's just change the event sprite.

**Comment by NamAnhLe** [comment]
Fixed in d76acc4

**Comment by Regalis11** [comment]
https://github.com/Regalis11/Barotrauma-development/commit/d76acc4f9617aae50656decb97f5ecd0e8196b89 changed the sprite in all the other events using the sprite. In the "occupational hazards" event it doesn't matter, but in the campaign tutorial event in which the engineer speaks, it's incorrect.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/008c559db08bf780c920c05ae848f11ba12966f2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
