### ISSUE TITLE
Unstable - Submarine Editor - Gaps are unable to handle small horizontal hulls

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5247]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Gaps are unable both in the submarine editor and in `Test` mode to handle small horizontal hulls if the width is smaller or equal to 16 units

However, they are able to handle hulls of the same width if they are arranged vertically

**Steps To Reproduce**
See video
1) Create 2 horizontal hulls of width 16
2) Attempt to place a gap in between the hulls
3) Does not work

https://user-images.githubusercontent.com/55001203/111076621-6c931600-84c3-11eb-809c-3df64cb0e575.mp4

**Version**
v0.1300.0.2

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Fixing this would significantly complicate the gap logic, and it's trivial to work around (by making the hulls just slightly taller), so doesn't seem necessary to address.
