### ISSUE TITLE
Unstable - Pump/Engine not receiving data signals through junction boxes

### ISSUE THREAD

**Issue by BluntTongs** [Regalis11/Barotrauma#5248]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pumps and engines do not get set to automatic control mode if they are wired through junction box logic ports and will not react to navigation terminal output.

**Steps To Reproduce**
Wire any nav terminal's x- or y-output to a logic pin on a junction box, then wire that to either a ballast pump or an engine's set_targetlevel pin. 

**Version**
v0.1300.0.2 (unstable)

**Additional information**
This is new in v0.1300.0.2; I had played on the same sub in v0.1300.0.1 and it was navigating just fine.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/abdf10ef3effe9b4acc315a1a009ab117b6b1a88

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
