### ISSUE TITLE
Remora shuttle undock prevention is poorly communicated

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5249]
**Description**
When the door to the shuttle is open, Remora prevents undocking of the drone, however, it is poorly communicated and from PoV of the player, nothing happens when they click the undock button. The tiny text display that says a long sentence in the drone control room is not ideal.

**Suggestion**
Just like the Kastrull drone, have the undock button close the shuttle's door and undock normally.

**Comment by Xeavas** [comment]
Agreed

**Comment by danielasteljoki** [comment]
Made the docking system simpler in 68963a9.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
