### ISSUE TITLE
Bug with harpoon

### ISSUE THREAD

**Issue by Tonchor** [Regalis11/Barotrauma#525]
If at the beginning of the game to buy a harpoon and spear then the game does not start and gives an error.
![screenshot_1](https://user-images.githubusercontent.com/24594463/43161421-be15fcac-8f90-11e8-8198-1974e36cfdff.png)
Translate:
Данный ключ отсутствует в словаре. - This key is not in the dictionary.
в - in.

**Comment by Regalis11** [comment]
Fixed in 01e97fe
