### ISSUE TITLE
Remora drone walls are transparent

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5251]
**Description**
heres what it looks like
![image](https://user-images.githubusercontent.com/59519434/111091196-6f791f80-8532-11eb-8e58-83303c20e03c.png)

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7d9e7318ba104215e14bc5674866080b6ced8e7

**Comment by Rokvach** [comment]
Tested, no issues.  Closing.
