### ISSUE TITLE
Destroying reactor without fuel rods in them still creates a nuclear detonation.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5252]
Destroying reactors with grenades or other means than water damage will cause a nuclear explosion even without fuel rods in them. the lack of consistency between 0% from water damage or 0% from any damage creates some confusion for the player.

Furthermore you're unable to safely destroy reactors as an objective if the outpost reactors are generated too near to the submarine, thus causing damage and radiation poisoning to people inside said submarine, or said expectation that it should be safe to grenade the reactor if it has no fuel rods in it.

Version : V0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/38053f145983a9195e2211ce2009f436c3e05441

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
