### ISSUE TITLE
backwall pipes wall doesn't fill dimensions

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5254]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
background is visible around edges of the "backwall pipes" wall ![image](https://user-images.githubusercontent.com/5103517/111122777-e1f2fb00-8544-11eb-8dd7-9ca44a2f7164.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.12

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef0fa4ce63b6c6a335b00dad7e6b8f2c65467971

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
