### ISSUE TITLE
fabicator counting wrong  (modded) (never got updatat after stacking items got implemented) 

### ISSUE THREAD

**Issue by tiba666** [Regalis11/Barotrauma#5255]
i hit a bug in the game tried to make a custom recipe. 
i dug into the code and found out that from that the file Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Fabricator.cs at line 118 -> 126

never got updatet to the new stacking system i tired to do a recipy there needed 8 steel and 1 plastic but got the  " DebugConsole.ThrowError" even it only should have taken 2 slots in the recipe 

if the code got modifed it would also look more clean on the older recipes instead of show plastic rubber rubber  it would show like platic rubber^2 in the gui.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a9acec23cc026917f3fa25f69a1919b429cfac6

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
