### ISSUE TITLE
Odd performance issues on joining mid-game servers

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#526]
Version 0.8.1.9 (Nilmod in use)
I am not sure if this is caused by my modification by missing something or as a result of the new changes - but at times joining a round in session will cause the game to freeze-up for several seconds which was not occurring in 0.8.1.8.

It also seems to have odd behavior with character ragdolls and submarine positions - more so when they have gotten far from the initial spawn, I think there could be something odd occurring with the max velocity being 100f when its finished its mid round sync and attempts to set the position causing my game to completely stall, but so far nobody else has told me there are odd issues.

There is also a typically amusing but awkward effect that after it stops freezing, it is as-if objects move in fast forward such as submarines.

I asked around but nobody has even replied if they have issues or not (Other than some thinking they take longer to finish mid round sync or being kicked more often from it).

**Comment by Rokvach** [comment]
I don't think this is still an issue, closing.
