### ISSUE TITLE
smoke detector /other detector inconsistencies

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5261]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
smoke detector with an empty output will send the empty string as a signal, thereby tripping set_state
smoke detector requires a screwdriver to edit its fields in game

water detector and motion detector with an empty output will NOT send a signal, and can be edited by hand

**Steps To Reproduce**
set the true/false output of smoke detector to empty, connect to a terminal

click on smoke detector (does not option menu)

**Version**
0.12

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a5253ae2481dfaa9a5634dd6c84792b84e9b0975 and https://github.com/Regalis11/Barotrauma-development/commit/28cd3c5099420588a94565d8bd72a9a53884e63d

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
