### ISSUE TITLE
Event Engineers_are_special doesn't use SetPriceMultiplier discount, despite the dialogue claiming it does

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5262]
**Description**
title, heres the image of the dialogue
![image](https://user-images.githubusercontent.com/59519434/111240232-24770f00-85fb-11eb-9de3-e5531dddc81b.png)

**Version**
Unstable

**Suggestion**
![image](https://user-images.githubusercontent.com/59519434/111240373-62743300-85fb-11eb-99aa-f31ecd77b4b6.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3697f3f5163f982ae72cdc035c9788763fe96821

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
