### ISSUE TITLE
Doors outside of hulls cannot block projectiles - inconsistently

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5264]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Doors placed outside of hulls don't have any collision with physical projectiles, unless they're really close to the hull
Bullets, Harpoons and other projectiles can collide if the door is close enough 
Coilgun ammunition _always_ pierces the door, even if it detonates and damages the door (explosive)

Top windowed door has collision, bottom one doesn't
Both are outside of hulls
![image](https://user-images.githubusercontent.com/73229309/111365716-1d9bdb00-8693-11eb-8b6a-579faa5c4050.png)

**Steps To Reproduce**
Use several different weapons against the doors on test platform
[[Hubert] Shuttle test platform.zip](https://github.com/Regalis11/Barotrauma/files/6151646/Hubert.Shuttle.test.platform.zip)

**Additional information**
Doors also not have collision with humans/monsters outside hulls; you can swim or drive entire submarines through them
See this very old issue: **Doors don't work as solid objects when they are outside of hulls** #853

**Comment by Regalis11** [comment]
This is essentially a symptom of #853, so I'll close the ticket as a duplicate.
