### ISSUE TITLE
Same depth items change their relative position when copy / pasting in editor

### ISSUE THREAD

**Issue by N0p1n** [Regalis11/Barotrauma#5268]
**Description**
When placing items in the editor they have a preset depth. In this bug i use the items **light component** and **camera**, which both have depth of 0.8.  I need both items to stay on this depth (!!!). When placing the items in the editor, its common, that the first item placed is relativley in front of the second item placed, even if they both are on the same depth level. When copy pasting both items, they change their relative placement.

**Steps To Reproduce**
Simple set up: 
1. Go to editor.
2. Place light component
3. Place camera next to it
4. Place light component next to camera (both lights should frame in the camera)
5. Move the camera, you see it will be behind item 2, but infront of item 4.
6. Copy all 3 items, paste all 3 items somewhere else
7. Repeat Step 5
8. Camera is in front of item 2, but behind item 4.

**Version**
v0.12.0.3 on Manjaro Linux

**Additional information**

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. If items have the exact same depth, their draw order is undefined. Closing.
