### ISSUE TITLE
Events - Propaganda event triggers inside the submarine, instead of outpost

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5272]
**Description**
Title, here is a picture of it:
![image](https://user-images.githubusercontent.com/59519434/111785714-3c7db580-88bd-11eb-9b76-228743a598bb.png)

**Steps To Reproduce**
-Select submarine that has structure opdeco_hrflyers on it (for example Remora like on the picture)
-triggerevent propaganda
-run past the tagged posters in the sub

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/582f3e64e00037fa53b655a4ebbf1adadd31fefd

**Comment by Xeavas** [comment]
[v0.1300.0.3] - Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
