### ISSUE TITLE
Outposts - Mission giver spawns inside a prison cell

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5273]
**Description**
Mission guy spawns in the prison like on this pitcture
![image](https://user-images.githubusercontent.com/59519434/111806529-5e356780-88d2-11eb-8024-3fec1a6cf918.png)

I suspect it's this spawnpoint. NPCs like to spawn all over the place when spawning on spawn points, which gave me some trouble when doing custom events. Would be nice if they spawned closer to the spawnpoint.
![image](https://user-images.githubusercontent.com/59519434/111805501-5de89c80-88d1-11eb-932e-cc20b6572f77.png)

**Steps To Reproduce**
Reload in military outposts with this module repeatedly until you get it.

**Version**
Unstable

**Comment by ubertpendragon** [comment]
Same with mining outposts

#4335

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b3de4a2: the NPCs should now always spawn at a spawnpoint if there's one available in the outpost.

**Comment by Rokvach** [comment]
Tested, no issues, closing.
