### ISSUE TITLE
Outposts - Platform appears behind the reactor

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5274]
**Description**
![image](https://user-images.githubusercontent.com/59519434/111806739-976dd780-88d2-11eb-9466-361a4e955978.png)

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f40cf65278d5c0814346cbebe5a272ff30bbaf25

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
