### ISSUE TITLE
Engine propellers do not deal damage inside hulls

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5277]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Engine propellers do not deal damage inside hulls

**Steps To Reproduce**
Place an engine inside a hull (flooded or not)
Set force to 100
Walk/swim through the propeller unharmed

**Comment by Regalis11** [comment]
fIXED IN https://github.com/Regalis11/Barotrauma-development/commit/f38d08c1875df5f220d646e6a81f9cec05817fbd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
