### ISSUE TITLE
Melee item structure damage not working on certain 'resizeable' structures ?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5279]
Melee items I noticed have structure-damage defined on their attack now, but did not seem to do damage for the longest time.
I have figured out this issue seems to be specific to 'resizeable' structures - as testing with structures with single hitboxes such as shuttle shells & shell curves & endcaps items seem to do damage as expected.

https://user-images.githubusercontent.com/55356135/111886107-20a00f80-89a2-11eb-8625-d88f56e2526e.mp4

Working as intended when on non-scaled walls:

https://user-images.githubusercontent.com/55356135/111886182-b50a7200-89a2-11eb-9f02-6e9f0e52a732.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1fead3ef3f42ed25b6ee37177a5ce9cb30603a3d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/28a32b5c-df99-4a21-8732-e6e1d32cd001)
