### ISSUE TITLE
Invalid docking port network event.

### ISSUE THREAD

**Issue by Krisscut** [Regalis11/Barotrauma#5282]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hangar doors made of shuttle going from 1 docking port to another are often used in submarine designs to have an enclosed area to park the shuttle.
In a multiplayer environment, the error "Invalid docking port network event(can't dock to null) often occurs when the shuttle moves from one docking port to the other.
It opens the console for all the people on the server, but doesn't seems to cause other issues.

**Steps To Reproduce**
-Load the submarine in a multiplayer environment.
-Go right when spawning as the captain to go to the remote shuttle console, and hit the "Open" button to open the hangar.
![image](https://user-images.githubusercontent.com/8125922/111912196-e0f02b00-8a68-11eb-8d33-227e8cec8fcf.png)
-Error opens the console. (try the close button as then open again, it doesn't seems to happen 100% of the time.)

**Version**
Windows, stable version . V0.12.0.3

**Additional information**

Screenshot of the error.
![Barotrauma_2021-03-21_16-04-55](https://user-images.githubusercontent.com/8125922/111911977-ef8a1280-8a67-11eb-9d94-28afa4f730ea.png)
Main sub (Initiatior) + hangar door standalone in zip.
[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/6177833/Submarines.zip)

Also i was told that it might be related to the event in white as well (issue with the dynamic hulls). Maybe for such usecases a checkbox or something on the docking port in the editor would be nice to tell the game that it is not a "normal" docking port and it shouldn't try to do the usual stuff with the dynamic hulls to pass through it.

**Comment by Regalis11** [comment]
Could no longer reproduce this in the latest unstable version, I think fixing https://github.com/Regalis11/Barotrauma/issues/5026 took care of this one as well.

**Comment by Krisscut** [comment]
Oh, nice thanks !
I might try to install the unstable on a separate directory to test it and see if it's not related to something else like my env/mods used.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by Krisscut** [comment]
Yes i can confirm, it seems fixed on last unstable
