### ISSUE TITLE
opening items with long values freeze sub editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5291]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
sub editor freezes when selecting an item with a long parameter value

**Steps To Reproduce**
1. load a sub file containing an item (example: regex component's true output) with a long (lots of characters) output value
2. select the item
3.  select the output field
4. game freezes for a while

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
discovered using: https://steamcommunity.com/sharedfiles/filedetails/?id=2391831040
freezes repeat when unselecting the field and reselecting

**Comment by Regalis11** [comment]
I think this is such an extreme case that it's bound to cause issues. The length of the text (the entire bee movie!) in this case is over 240 times more than the default maximum output length of the regex component.
