### ISSUE TITLE
Purchase sub at crush depth

### ISSUE THREAD

**Issue by misgnosia** [Regalis11/Barotrauma#5295]
Had a hull upgraded humpback, switched to Remora, but we were far below its crush depth (I was shocked to learn deep diver had a crush depth), and by the time the game let you control the character you had a second to live before you pressure popped. 
Full server and campaign save ruined, it was a bad time, and I was the second guy in a day to complain about it in discord.

related: It'd be really nice if there was a rotating backup for the game save that let me go one round back

v.0.12.0.3 ReleaseWindows, branch release, rev ea245a2f34

**Comment by diegoyocys** [comment]
try to enable cheats to enable godmode, that way your sub wont take damage and you can re-dock, and if you also prefer, togglecampaignteleport, so you can teleport to an outpost further back and start using the remora straight away, or do it old fashion way and use your humback to travel back to a safe area for you to use the remora

**Comment by EtiamNullam** [comment]
> of course this cheats would only be available on single player

These cheats are also available in multiplayer if you are the host or have permissions.

**Comment by ekqvist** [comment]
There is a related issue in the Stable build that after switching the sub, the crush depth warnings on the map are still displayed based on the sub you docked with. So, you'll have no warning if the sub you switched you can't withstand the pressure in the next level. This should now be fixed in the latest Unstable build. (#5497)

**Comment by Rokvach** [comment]
This isn't a issue anymore with the new global upgrades, closing.
