### ISSUE TITLE
Corpses always spawn on wrecks despite having no defined spawn points

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5298]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Corpses always spawn on wrecks despite having no defined spawn points

**Steps To Reproduce**
Steps To Reproduce
Add the "Naval Mine Dropper" wreck in the wreck pool (using wrecks mod or otherwise)
Naval Mine Dropper.zip
Launch a mission
Corspes spawn near the wreck
![image](https://user-images.githubusercontent.com/73229309/112231199-899fb580-8c36-11eb-8719-5c8ed385b34d.png)

**Version**
v.0.12.0.3

**Additional information**
![image](https://user-images.githubusercontent.com/73229309/112231113-5c530780-8c36-11eb-8670-fca88b875ae7.png)

Corpse spawns are defined by the level (as seen in _leveleditor_), ignoring the absence of spawnpoints

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/85b56573eb3152e738ebdae0b3b21eca09887739

**Comment by ubertpendragon** [comment]
![image](https://user-images.githubusercontent.com/73229309/112347442-26119880-8cc7-11eb-8935-426a38a49825.png)

Note: Monsters also spawn without waypoints. 2 husks + 2 crawlers appeared as well 
![image](https://user-images.githubusercontent.com/73229309/112347580-46d9ee00-8cc7-11eb-9bfe-e9c4479d957d.png)

**Comment by ubertpendragon** [comment]
Tested on unstable, monsters still spawn on wreck location despite no spawnpoints

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3b2b679f0d2567adf885332b4f8cc979b2fb2d7

**Comment by Jlobblet** [comment]
Tested by replacing vanilla wrecks with ones that have no spawnpoints of either kind. Did not see monsters or corpses spawn.

**Comment by Rokvach** [comment]
Closing
