### ISSUE TITLE
When you press and hold the keyboard to move, the mouse will be stuck when you slide it (there will be jerky and teleportation)

### ISSUE THREAD

**Issue by uestc-alayi** [Regalis11/Barotrauma#5304]
- [x] I have searched the issue tracker to check if the issue has already been   

**Description**

**Steps To Reproduce**
 新手教程中，按住键盘进行左右移动的同时，滑动鼠标，会出现鼠标指针移动缓慢、瞬移等情况

**Version**
Windows 0.12.03
**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report!

Unfortunately no-one in the development team speaks Chinese, so I had to rely on Google Translate and I'm not sure if I understood this correctly: "in the beginner's tutorial, while holding the keyboard to move left and right, the mouse pointer will move slowly and teleport"? With this information I unfortunately wasn't able to reproduce the issue: pressing left or right doesn't seem to have an effect on the cursor, and there seems to be no slow movement, teleporting or other oddities.

**Comment by uestc-alayi** [comment]
你好，由于我免费体验到期了，借了别人的账号测试了一下，发现仍然存在问题。
键盘：蓝牙键盘
鼠标：蓝牙鼠标

https://user-images.githubusercontent.com/48664118/113151161-6349cd80-9267-11eb-9785-dbf042299227.mp4

**Comment by uestc-alayi** [comment]
又尝试了一下
1.蓝牙键盘+无线鼠标（非蓝牙鼠标）
2.有线键盘+蓝牙鼠标
3.有线键盘+无线鼠标（非蓝牙鼠标）
以上三种情况都出现了按住键盘左右移动时，鼠标滑动受影响的情况

**Comment by Regalis11** [comment]
I'm afraid we haven't found a way to reproduce this and we haven't gotten any other reports about these kinds of problems, so I'd suspect it has something to do with your computer's input settings or devices. I wonder if it's possible that you have enabled Windows' Ease of Access option that allows moving the cursor with the keyboard?
