### ISSUE TITLE
Orca still using legacy small pumps in some places

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5306]
![Lpump2](https://user-images.githubusercontent.com/72674994/112465358-9b509c80-8d9f-11eb-94bd-44038a263118.jpg)
![Lpump1](https://user-images.githubusercontent.com/72674994/112465363-9c81c980-8d9f-11eb-8162-c7dffd3a7972.jpg)
![Lpump3](https://user-images.githubusercontent.com/72674994/112465542-d05cef00-8d9f-11eb-85d2-e076095278d7.jpg)

**Version**
V0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/baf2e9621345b6592e4d56171feece03b160b90a

**Comment by Rokvach** [comment]
No issues, closing.
