### ISSUE TITLE
Annoyance (noises) with humpback's fore ballast compartment (hulls)

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5307]
**Description**
With humpbacks fore ballast being cut into two hulls (the rightmost is classified as a ballast tank via room name) operating it like a ballast with doors open will create a lot of noise causing annoyance.

![linkyhumpback](https://user-images.githubusercontent.com/72674994/112470137-42840280-8da5-11eb-8896-3324b03c6c75.jpg)

**Solution**
Link the two hulls so that it doesn't generate noise when water flows between them, and them showing up as one on the status monitor.

**Version**
V0.1300.0.2

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Linking the hulls together would cause other kinds of issues (e.g. the nav terminal and bots would treat them as a single room, even though they're not).
