### ISSUE TITLE
Trying to scroll the drop down (or when cursor is on the ui) in Character Editor zooms out/in the display

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5310]
Opening the drop down when selecting characters and attempting to scroll through the selection causes the display to zoom in and out.

V0.1300.0.3

**Comment by Jlobblet** [comment]
Also present in the sub editor.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/27400ac84d94ebaa9164cd61f466c8e86e4671c9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
