### ISSUE TITLE
Respawn shuttle can't withstand abyss depths

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5313]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The respawn shuttle can only withstand the amount of pressure a normal, non-upgraded sub would, which causes problems when respawning in the abyss or late-game biomes in the campaign.

**Version**
0.1300.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/23c22f23363b1ed51525d176506ed81358ba5849

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
