### ISSUE TITLE
[Unstable V0.1300.0.3] Loading subs from previous versions with more than 200 characters in the output fields cuts them short to the default 200 characters.

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#5315]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Subs loaded from previous versions that contain more characters than the default Max Output Length of 200 characters are cut short to 200 characters upon being loaded. 

Perhaps it would be possible to set the character limit of a sub to a be at the number of characters in the output field upon loading the component (or sub/assembly that the component is in)

**Steps To Reproduce**
Rollback to a previous version without the (soft) character limit. Place a component (e.g. as a signal check with target signal 1 and a button for easy testing). Paste a string of more than 200 characters into the component. Update the game to V0.1300.0.3. Load the sub file. The component now has a max output length of 200 and any further text in the component has been removed.

Useful test string: "....5...10...15...20...25...30...35...40...45...50...55...60...65...70...75...80...85...90...95..100..105..110..115..120..125..130..135..140..145..150..155..160..165..170..175..180..185..190..195..200..205..210..215..220..225..230..235..240..245..250..255..260..265..270..275..280..285..290..295..300"

**Version**
Unstable V0.1300.0.3

**Additional Information**
Related to #5314, but decided to go with a separate issue as fixing #5314 does not guarantee this problem is resolved.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a92a14aa54bbd6c25e082dd66ff0f10725ff8b78

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
