### ISSUE TITLE
Batteries connected to each other seem to generate power out of nowhere

### ISSUE THREAD

**Issue by uselessgoddess** [Regalis11/Barotrauma#5318]
***TRANSLATE:***
**Description**
I invented the perpetual motion machine

**Steps To Reproduce**
Everything is quite simple. I did it quite unconsciously, and I don't even know if it's true.

1. First, we need a simple power source. I took the reactor and threw the rod into it for about 10 seconds.
2. From him, the current went in a simple cable box.
3. The box itself is connected to a bunch of batteries. About this now in more detail.
Battery construction:
     I took 4 batteries, but I'm sure that 2 or more are enough(maybe even one)
     Battery connections:
            1 -> 2
            2 -> 3
            3 -> 4
            4 -> 3
            3 -> 2
            2 -> 1
The cable from the box is connected to the first battery.
It is also worth noting that each battery has a value of "Battery recharge" set to 100%

4. After that, you should also power something else from this box(for example, a couple of lamps).
5. The battery charge will not change, and the lamps will shine

**Version**
12.0.3 Windows (just like that)

**Additional information**
I know that the editor is still not in its proper form right now(it is more likely not for the game, but for the developers themselves)

If anything, I just wanted to make a backup supply of energy in case of a reactor shutdown(similar to the 'Humpback' boat). So I will be very happy if you can help with this.

***ORIGINAL:***
**Description**
Я изобрёл вечный двигатель

**Steps To Reproduce**
Всё достаточно просто. У меня получилось это совсем неосознанно, и я даже не знаю, правда ли это. 
1. Для начала нам понадобится простой источник энергии. Я взял реактор и закинул в него стержень секунд на 10.
2. От него ток пошёл в простой кабельной коробке.
3. Сама коробка соединена со связкой батарей. Про это сейчас подробней.
Конструкция из батарей:
     Я взял 4 батареи, но уверен, что достаточно 2 и более(может даже и одной)
     Соединения батарей:  
            1 -> 2
            2 -> 3
            3 -> 4
            4 -> 3
            3 -> 2 
            2 -> 1

      Кабель из коробки подсоединяется к первой батарее.
      Также стоит заметить, что у каждой батареи выставлено значение "Перезарядка батареи" на 100%

4. После также от этой коробки стоит запитать ещё что-то(например пару ламп).
5. Всё. Заряд батарей не будет изменяться, а лампы будут светить

**Version**
12.0.3 Windows (просто так)

**Additional information**
Я знаю, что сейчас редактор всё еще не в надлежащем виде(он скорее не для игры, а для самих разработчиков)

Если что, я просто хотел сделать резервный запас энергии на случай отключения реактора(по аналогии с лодкой 'Humpback'). Поэтому буду очень рад, если вы поможете с этим.

**Comment by uselessgoddess** [comment]
Description
I invented the perpetual motion machine

Steps To Reproduce
Everything is quite simple. I did it quite unconsciously, and I don't even know if it's true.

First, we need a simple power source. I took the reactor and threw the rod into it for about 10 seconds.
From him, the current went in a simple cable box.
The box itself is connected to a bunch of batteries. About this now in more detail.
Battery construction:
I took 4 batteries, but I'm sure that 2 or more are enough(maybe even one)
Battery connections:
           1 -> 2
           2 -> 3
           3 -> 4
           4 -> 3
           3 -> 2
           2 -> 1
The cable from the box is connected to the first battery.
It is also worth noting that each battery has a value of "Battery recharge" set to 100%

After that, you should also power something else from this box(for example, a couple of lamps).
The battery charge will not change, and the lamps will shine
Version
12.0.3 Windows (just like that)

Additional information
I know that the editor is still not in its proper form right now(it is more likely not for the game, but for the developers themselves)

If anything, I just wanted to make a backup supply of energy in case of a reactor shutdown(similar to the 'Humpback' boat). So I will be very happy if you can help with this.

**Comment by Regalis11** [comment]
Thank you! Unfortunately no-one in the development team speaks Russian, so the translation was very helpful.

I built a quick test submarine to debug this, attaching it here to make further work on the issue easier. Couldn't come up with an easy way to fix this off the top of my head, it might require some bigger changes to the power logic. I'll get back to this later when we get some more urgent issues out of the way first.

[Batterytest.zip](https://github.com/Regalis11/Barotrauma/files/6271015/Batterytest.zip)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
