### ISSUE TITLE
[Unstable] Freecam command keeps line of sight active and creates a huge black sphere

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5319]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/73229309/112513280-730f7080-8d94-11eb-8f35-405b1c702dda.png)

**Steps To Reproduce**
Type Freecam in console
Zoom out

**Version**
v0.1300.0.3

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6875807c249c83fdcd69fd7bae22894e5669ce52

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
