### ISSUE TITLE
[Unstable] Using console commands (such as freecam) spam "aaa" in the console

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5320]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/73229309/112513468-a7832c80-8d94-11eb-9858-315618fbe218.png)

**Steps To Reproduce**
Type Freecam in console
**aaa
aaa
aaa**

**Version**
v0.1300.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eb813b9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
