### ISSUE TITLE
players appear as "disconnected" in tab menu, can't be clicked on

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5322]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
in multiplayer, in game players often appear as "disconencted" in tab menu despite being connected and actively playing.
this causes issues with trying to manage the player, as clicking on a "disconnected" player doesn't do anything.

**Steps To Reproduce**
1. set up multiplayer
2. have people join
3. start round
4. open menu

**Version**
0.12

**Additional information**
samples:
![image](https://user-images.githubusercontent.com/5103517/112538681-8287bd00-8d86-11eb-99d0-19815ccdf9c3.png)

![image](https://user-images.githubusercontent.com/5103517/112538856-aea33e00-8d86-11eb-9925-f1392559dc14.png)

happens in campaign too

update: not even I'm connected
![image](https://user-images.githubusercontent.com/5103517/112548634-e912d800-8d92-11eb-9121-b4f33100f60d.png)

**Comment by Rokvach** [comment]
This has already been fixed in Unstable, closing.
