### ISSUE TITLE
[Unstable] Crash caused by attempting to use server log in a lobby that you have lost connection to

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#5323]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description/Steps To Reproduce**
If you are given server log permissions on another player's server, then get desynced from said server (whilst in the lobby, specifically), the game won't outright kick you out of the lobby and back into the server list. You can still press on the server log button next to the chat, which I did and it caused a crash.
To reproduce, I suggest triggering desync by just cutting your connection to the router. In my case, I was AFK for long enough that my computer went into sleep mode.

**Version**
V0.1300.0.3, Windows
![image](https://user-images.githubusercontent.com/63509011/112553110-d06ae800-8dbb-11eb-8b46-efc5014d3e72.png)

**Comment by Solbusaur** [comment]
[crashreport (24).log](https://github.com/Regalis11/Barotrauma/files/6208321/crashreport.24.log)
The crash report

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/290bdf74df94c5249ed0b7305f8456b4b13e59ea

**Comment by Rokvach** [comment]
Tested, accessing server log doesn't cause a crash but accessing server settings does, I made a separate ticket for that. So working correctly, closing.
