### ISSUE TITLE
[Unstable v.0.1300.0.3] unused code in AfflictionHusk/AfflictionHusk does not properly unsubscribe 

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#5324]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I found something odd when doing some source code modding:

The following code excerpt from `AfflictionHusk.cs` seems to never be called. Not when the affliction is removed, but also not when the character is killed or removed.
https://github.com/Regalis11/Barotrauma/blob/694cdfee7bd986242b9a772cb3d1a8a65d19c29c/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionHusk.cs#L151-L157

What this means in practice is that `CharacterDead` is called even if the character that dies has had their huskaffliction cured. (confirmed by putting some code throwing a warning in CharacterDead). In the end it ends up not mattering too much, since the function does another check for the huskaffliction level.
https://github.com/Regalis11/Barotrauma/blob/694cdfee7bd986242b9a772cb3d1a8a65d19c29c/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionHusk.cs#L162

It's interesting though that if the character dies it can still call CharacterDead on the huskaffliction that is removed from the character (in terms of strength). Could this be because all afflictions remain on the character even if they have 0 strength or are afflictions generally sort of static?

**Version**
Unstable v.0.1300.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/08cee1af1af5dbbd6eba544702201e852308b8e8

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
