### ISSUE TITLE
Outpost Guards not dying to Morbusine/Poisons

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#5333]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Guards, if shot with a syringe gun containing morbusine, do not die or exhibit symptoms such as oxygen loss, even if the poison affliction reaches 100% strength. In addition, they will continually "warn" the player to stop messing around every 15 seconds or so after the poison is applied, but never aggro on the player.

**Steps To Reproduce**
Shoot a guard with a syringe gun containing morbusine.
**Version**
Current stable vanilla release, Windows 10
**Additional information**
I have not tried cynaide or sufforin but it is likely these do not work to kill guards either. Radiotoxin does inflict burns, but they show no symptoms of radiation exposure. Tested only in singleplayer.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bc092f58833bd7a575008505099bd5c94e6fa29e

**Comment by Rokvach** [comment]
I was still able to reproduce this, I didn't use a syringe gun however but just directly injected the guard with Morbusine

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f3021050-1e9f-4bb0-9bde-bc32a61e5c4d)

**Comment by Regalis11** [comment]
> But should it even be possible to kill them this easily

This is a good point actually, on a second though I don't think it should. Outpost security has twice as much health as other characters, and they're supposed to be tougher than the average character, so I think it's actually a good thing there isn't such an easy way to kill them. This also applies to the upcoming bandit leaders in the abandoned outposts, which should be equally tough.

I reverted the previous change (https://github.com/Regalis11/Barotrauma-development/commit/6690af655f54af09a80309ed9373b78294d6328e) and readjusted the affliction: now the affliction is always non-lethal until it reaches 80% strength, and after that it becomes lethal to characters without extra health.
