### ISSUE TITLE
Coilgun/Railgun sight range reduced massively

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5334]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While using a rail/coilgun in the latest unstable build, you only seem to have about 50% of what the normal sight used to be, the searchlights seem to be working correctly.

**Version**
v0.1300.0.3 Windows
![20210326154100_1](https://user-images.githubusercontent.com/55637865/112678854-37cf7900-8e4a-11eb-883e-2afc63b3b4c5.jpg)
![20210326154110_1](https://user-images.githubusercontent.com/55637865/112678857-3900a600-8e4a-11eb-9304-3f53889c2fb6.jpg)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/57c8b02133f76dec51e9325df1c02420dc228c36, TODO: `feature/camera-refactor` because this is way too complicated

**Comment by Rokvach** [comment]
Something which might use some attention is when your aiming directly to one direction your range is more limited than when you are aiming at the corner of your screen

Left is aiming directly down while right is aiming at bottom right corner of my screen
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5711e4f7-fc4c-4e95-b594-5d3cd8863046)

**Comment by Rokvach** [comment]
I think they look fine now, we don't really have time to address the above issue for this update, but certainly something we should look in to later on. Closing as I think the ranges are fine now.

**Comment by Regalis11** [comment]
I think this needs to be reopened, there's still several issues with this:
- [ ] The behavior of the camera has changed when using turrets: previously the zoom didn't depend on where your cursor is on the screen and the range didn't get restricted this much when aiming directly up/down.
- [ ] You now need to take the cursor all the way to the edge of the screen to utilize the full range (also applies to situations where you're not using a turret)

**Comment by Rokvach** [comment]
Did a comparison between stable and dev

Stable - As you can see there's no zooming at all the railgun stays the same size on both directly down and to the corner screenshots, only the camera pans out 

Dev - There's zoom in when looking directly down and then there's zoom out when looking at the corner which makes the range differ depending which way you look

Stable:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0fbca847-d9f0-4d5e-8c63-3dd4045bf547)
Dev:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4fe355da-8579-4e5f-9d3b-bac755aceb1b)

Stable:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/da41aff2-32f5-4c19-974f-d7ff06e34407)
Dev:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ebfab78a-6cf7-42cb-a831-6a2a634fd1bb)

**Comment by Regalis11** [comment]
There also seems to be something weird going on at the bottom of the screen, some kind of a dead zone where the turret doesn't react to the movement of the cursor:
![image](https://user-images.githubusercontent.com/14351070/112976324-66f12d80-915d-11eb-99f9-eaceccd4ed89.png)

**Comment by juanjp600** [comment]
All issues should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c679edce0d77c85d196757e2a97978f704c5e71, I've changed my approach for fixing the resolution-based scaling. I'll probably revisit this eventually to make things clearer and rely less on magic numbers to do everything, because this didn't need to be this complicated.

**Comment by Regalis11** [comment]
That dead zone seems to still be there. I initially thought it was because the charge/ammo indicators were moved to the bottom of the screen, but the issue was there even before it was changed. Didn't seem to happen in previous Release version.

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4bd6c205bd531db3392d20389583a16586e8a8fc

**Comment by Rokvach** [comment]
I think they look fine now, closing.
