### ISSUE TITLE
Empty Coilgun Ammunition Boxes don't deconstruct into aluminium

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5336]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deconstructing empty coilgun ammunition boxes of any kind no longer gives aluminium, or anything, they just desintegrate.

**Version**
v0.1300.0.3 Windows

**Comment by danielasteljoki** [comment]
Aluminum condition was copied when deconstructing boxes. Fixed in 0d0bed7.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
