### ISSUE TITLE
Decal Prefab names using capital letters cause game crash

### ISSUE THREAD

**Issue by LordFrith** [Regalis11/Barotrauma#5337]
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/6214878/crashreport.7.log)
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Defining a custom Decal Prefab, such as those used by explosions, with a capital letter in the name causes the game to crash when the game tries to use it

**Steps To Reproduce**
making a mod, create custom decal using prefab file

call it "CustomDecal" instead of "customdecal"

tried to use this decal in an explosion triggered by a status effect.
game crashes when status effect is triggered

**Version**
stable v0.12.0.3 windows 10
**Additional information**
crash file should be attached
https://discord.com/channels/103209684680323072/426913209602146315/825155498000777296
link to discussion on discord

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b49f10448e3b668139b6b144270cfe0f08fd512

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
