### ISSUE TITLE
Blocking special characters

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#534]
![image](https://user-images.githubusercontent.com/15182031/43284580-88be25b0-911c-11e8-82d3-093112f24fc7.png)
I had this pop up on the server.

When i tried to ban by name (atleast through a ssh client) the server crashed. Banning the ip still works though.

To fix this my idea is that all of these special characters should be blocked and maybe add a config file so hosts can add and remove as they see fit.

Though instead of manually blocking all special characters, make it so the name is checked to be valid (aka uses letters from the english alphabet). But with this you would probably have to make a bypass for cyrillic and other similar non-english letters as well, though IMO i would block those either way.

**Comment by CommanderMark** [comment]
> But with this you would probably have to make a bypass for cyrillic and other similar non-english letters as well, though IMO i would block those either way.

Dicking over your non-English player base to stop Unicode abuse seems kinda short-sighted imo.

**Comment by NilanthAnimosus** [comment]
I implemented this as a server option in my mod to block cryllic or english characters, but indeed its not a good idea to just kill entire alphabets and enforce english,

There is likely a good number of none-letter characters though that shouldn't be usable in unicode that are not part of any used language specifically.

**Comment by BlueTheKing** [comment]
When i said "i would block those either way" i meant that on my server i would block those, half of those don't speak english and their names are a pain to deal with when not ingame. Im fine with however it is by default.
