### ISSUE TITLE
Creaking hull sounds constantly playing

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5344]
- [ ye] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Creaking hulls" sounds, which I believe should only play in the zones where your sub cannot withstand the pressure, seem to be constantly in campaign levels from the European Ridge and on, even when your submarine is not taking any damage from pressure or is near the crush depth.

**Version**
v0.1300.0.3

**Additional information**
I think this happens because of the combat diving suits (or normal diving suits if you're in Aphotic Plateau or further), since those cannot withstand the pressure outside, maybe the game detects that and plays the creaking hull noises thinking you're in crush depth.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/71d33eb9014bdc953e5cb880d35990647e8781e1

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
