### ISSUE TITLE
Dedicated server will allow 1 less player to join than set by maxplayers option

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#5347]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dedicated server will allow 1 less player to join than set by `maxplayers` option.

**Steps To Reproduce**
1. Launch a dedicated server.
2. Set max player count to `1` by `maxplayers 1` command.
3. Notice server is listed as `0/1` in server browser.
4. Try to join your server.
5. Notice you can't join and will be asked to queue in.

**Version**
0.12.0.3 Windows

**Additional information**
It does not matter if you set `maxplayers` by command or in `serversettings.xml`.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0eb14abba94c985d4dfde0b96609854d7e4d2065

**Comment by Rokvach** [comment]
No issues. Closing.
