### ISSUE TITLE
Dedicated Server 'hemulen_wreck' Submarine Vote

### ISSUE THREAD

**Issue by Waluijay** [Regalis11/Barotrauma#5353]
If players vote on a Custom Submarine they don't have downloaded, the server will not prompt them to download it unless it is Manually Selected by the server. If it is not Manually Selected and is instead Voted for, the server will prompt users to download 'hemulen_wreck' infinitely until the user selects to decline the download, at which point their game will crash OR boot them to the main menu.

**Steps to Reproduce**
Vote for a Custom .sub in a Dedicated Server (not a Hosted Server) without the server Manually Selecting the sub.

**Version**
v0.12.0.3 (ReleaseWindows, branch release, revision ea245a2f34)

**Additional information**
If a user manages to bypass the 'Submarine File Missing' prompt when a sub is Voted for, and enters the game, they are immediately despawned and their game will crash to desktop. Server log files also indicate the 'hemulen_wreck' was the ship voted in regardless of actual vote, and fails to spawn.
![Annotation 2021-03-28 202626](https://user-images.githubusercontent.com/81510198/112749129-19b17680-900c-11eb-839d-0c34e3959391.jpg)
![Annotation 2021-03-28 212620](https://user-images.githubusercontent.com/81510198/112749162-41a0da00-900c-11eb-9f91-16b7fe694ca4.jpg)

**Comment by Rokvach** [comment]
We encountered this same issue on the latest Unstable build as well

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7006f6edd956121ebfbbcfce87969fc4c96985de

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
