### ISSUE TITLE
[Unstable] - In game submarine preview moves when the actual submarine moves.

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5354]
**Description**
It seems that the camera in the in-game submarine preview is not relative to the submarine in the preview, thus when moving the actual submarine it would seem as if the submarine is "panning out" of the preview.
Not sure how to describe the "preview" but here's what it looks like.
![subpreview](https://user-images.githubusercontent.com/72674994/112751057-70b04f00-8ffe-11eb-9c31-5c3b210e1d83.jpg)

**Replication Steps**
-Set the submarine on autopilot traveling somewhere
-Open the in game submarine preview

**Version**
V0.1300.0.3

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3baf6c0ddcbf03e92752eccb97448a66756beb0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
