### ISSUE TITLE
Clownbrutality event clowns prioritize tools if they have them in their inventory

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5355]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I believe clownbrutality event clowns should be prioritizing the toy hammer, but instead they use their tools on their target

**Version**
v0.1300.0.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/012298ffe139acbe2987d07e0924093e01d26efb

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
