### ISSUE TITLE
You never meet watchers if you speed trough levels.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5372]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The watcher has a cool and unique hostile role in the game so it shouldn't be saturated, but i've completed 4 campaigns in the last 4 unstable builds and i've only seen 1, because aparently they only spawn when you're stationary. And when they spawn, 90% of the times they spawn alone so you don't get to see the effect of the watcher gaze in other creatures. Maybe adding some "offensive" spawns that don't rely on the player staying in the same place for too long would get players that speed trough levels to see watchers more often...

**Version**
v0.1300.0.3 Windows

**Comment by Rokvach** [comment]
Afaik they only spawn if you take too long to complete a round of if you are just stationary in the level for a long time they start appearing one after another.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
