### ISSUE TITLE
(One word fix) revolvers don't shoot custom ammo due to tag mishap.

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5374]
[Modding]
basically, revolvers' itemcontainer accepts anything with the "revolverammo" tag, but in the rangedweapon itself, it won't fire because it has <RequiredItem identifiers="revolverround" />. It would obviously be better for everyone if the requireditem was changed to "revolverammo" so custom modded ammos could be fired.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75ce507eec07cb498a1e9816a80278eb9c5dc220

**Comment by Rokvach** [comment]
No issues, closing.
