### ISSUE TITLE
Items with Rope Components don't use rope when shot from creature attack

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5376]
[Modding, Bug]
Self explanatory title. This can be tested by making the spineling spawn a fleshgun tendon or the like in its ranged attack. The rope component won't link the projectile and the limb that fired it in the way you'd expect it to.

Is this relatively easy to fix? I'm making this report right now before the QA build is submitted because I assume yes.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1856339949bfcb6b6b9fb25382db0b92eb30ed94

**Comment by hubismal** [comment]
Did this make it into the latest unstable branch? Will this make into the Embrace The Abyss update? Just curious.

**Comment by hubismal** [comment]
Emanthealmighty also reports this doesn't seem to work

**Comment by Regalis11** [comment]
How does it not work specifically? Does the rope not appear at all? 

I tested this by swapping the spineling's spikes to fleshgun tendons, and it seems to be working fine. I wonder if it has something to do with the way Emanthealmighty has configured the item/character?

![image](https://user-images.githubusercontent.com/14351070/119099195-518ed600-ba1f-11eb-91d5-41f4f5b756ef.png)

**Comment by Emanthealmighty** [comment]
> How does it not work specifically? Does the rope not appear at all?
> 
> I tested this by swapping the spineling's spikes to fleshgun tendons, and it seems to be working fine. I wonder if it has something to do with the way Emanthealmighty has configured the item/character?
> 
> ![image](https://user-images.githubusercontent.com/14351070/119099195-518ed600-ba1f-11eb-91d5-41f4f5b756ef.png)

The way I tested it involved replacing "spinelingspike" with "fleshguntendon1" in the spineling's ragdoll xml file.

The spineling would shoot the "projectile" properly but there would be no rope attaching the projectile to the spineling.

**Comment by Regalis11** [comment]
And you tested this in the latest unstable, not the public stable version, right?

**Comment by Emanthealmighty** [comment]
> And you tested this in the latest unstable, not the public stable version, right?

I tested this on the public stable version... I thought that the fix had made it into the abyss update

**Comment by Rokvach** [comment]
This can be tested in Unstable

**Comment by hubismal** [comment]
![image](https://user-images.githubusercontent.com/47284081/120937288-44026d00-c6fc-11eb-97d5-81b24f6cca62.png)
This works now. Thanks!

**Comment by Rokvach** [comment]
Closing
