### ISSUE TITLE
Oxygen tank inventory-icon inconsistency

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5377]
Oxygen tanks always have appeared more blue-colored in inventory icon, but their item is green - about the same color as an oxygenite tank.

![image](https://user-images.githubusercontent.com/55356135/112875817-ae5eb780-9092-11eb-834d-9ad7dba43b32.png)

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@3c2a6ee
