### ISSUE TITLE
Explosions with only levelwalldamage cannot break ice walls/spikes

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5379]
_(This issue persists across unstable build aswell.)_

The explosion parameter levelwalldamage (as used in explosives.xml for example) does not appear to have any effect on breakable ice, the only reason explosives still damage them seems to be because structuredamage is also applying damage to breakable ice.
An explosion with levelwalldamage on its own however seems to be incapable of breaking ice walls and spires.

**Steps to reproduce:**
- Create an item with an explosion and have something like `range="1000.0" structuredamage="0" levelwalldamage="1000"`
- Use the item on an ice wall, it won't seem to have any effect.

- Change to something like `structuredamage="500"` and now the ice will break due to structure damage.

**Comment by Regalis11** [comment]
Thank you for the report! Looks like the issue was that the explosion didn't do any kind of wall damage (structure or level) if the structure damage was set to 0; a leftover from the time we didn't have damageable level walls.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b369a696a5e5830c94e12d1bb66f6206d1340c28

**Comment by Ek-Videogames** [comment]
The current check seems to not consider level-wall-damage at all though, because - for instance - setting structure damage to something like 50 while level wall damage is 1000 would still act as if it is doing only 50 damage. 
However I trust that whatever changes to implementation probably will account for this anyways, so I guess its just to wait and see.

**Comment by Regalis11** [comment]
>The current check seems to not consider level-wall-damage at all though

Yep, that's exactly what the problem was and what I fixed in that commit.

**Comment by Jlobblet** [comment]
Tested with this mod: [UnstableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6299440/UnstableTestMod.zip).

1. Open `leveleditor`.
2. Generate a level and test it.
3. Spawn a diving suit, oxygen, grenade launcher, and `40mmlevelgrenade`.
4. Teleport to an ice spire.
5. Fire at it.

No issues.

**Comment by Rokvach** [comment]
Closing

**Comment by Ek-Videogames** [comment]
> Tested with this mod: [UnstableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6299440/UnstableTestMod.zip).
> 
> 1. Open `leveleditor`.
> 2. Generate a level and test it.
> 3. Spawn a diving suit, oxygen, grenade launcher, and `40mmlevelgrenade`.
> 4. Teleport to an ice spire.
> 5. Fire at it.
> 
> No issues.

@Rokvach Might require reopening or a different ticket? Not sure.

Explosion damage now appears to be working as intended, but bizarrely only with projectiles that directly impact the surface.

Explosion area-of-effect does not seem to produce any damage particles at all despite how large the radius is made, only something about the explosion being directly next to / partially inside the surface seems to allow it to work. Suggesting its something strange happening hitbox related?

https://user-images.githubusercontent.com/55356135/115093406-342e8f80-9ee8-11eb-8f74-5110452eb071.mp4

Just to make absolutely sure that was what is happening I modded an item that just explodes instantly upon spawning for using with spawnitem commands. [ " levelexplosiondebugger " [UnstableTestMod2.zip](https://github.com/Regalis11/Barotrauma/files/6328220/UnstableTestMod2.zip) ] Same results.

https://user-images.githubusercontent.com/55356135/115093443-53c5b800-9ee8-11eb-99e4-af34e6d23a99.mp4
