### ISSUE TITLE
Problem with loading into levels on MacBook Pro

### ISSUE THREAD

**Issue by Llolpros** [Regalis11/Barotrauma#5381]
The save file will run into trouble when entering levels at random. It will crash the game and will refuse to let me load the save. This happens at random levels and will remain bugged meaning I will have to avoid that level and find another path through the map. The only workaround I have found is by using the unstable version which will allow me to load the save but it's more like borrowed time. If I don't exit that level by going back into the outpost it will crash after a short amount of time and leave me back at square one. I use a MacBook Pro and am on macOS Catalina
here is the save file converted into PDF so I could upload it here.
[The Imperial Gold.save copy.pdf](https://github.com/Regalis11/Barotrauma/files/6227164/The.Imperial.Gold.save.copy.pdf)
.
If you need more info or if there is anyway I can help my Discord is Llolpros#9981

**Comment by ekqvist** [comment]
Here's the error posted on Discord
![image](https://user-images.githubusercontent.com/16864465/112951356-eeca3e00-9143-11eb-975d-9c81d2e9478d.png)

**Comment by ekqvist** [comment]
Zipped save file: [The_Imperial_Gold.zip](https://github.com/Regalis11/Barotrauma/files/6227365/The_Imperial_Gold.zip)

**Comment by ekqvist** [comment]
@Llolpros Currently, it seems that the game has been saved in Unstable and some of the locations have a type of "Abandoned" that don't exist in the Stable version yet, therefore resulting in the error on the right, unable to load the file. I didn't notice any immediate issues with the save while doing a quick test with it in Unstable.
