### ISSUE TITLE
"Follow sub" toggle is rendered on top of the map button in MP campaign

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5386]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Follow sub" toggle is rendered on top of the map button in MP campaign

**Steps To Reproduce**
Spectate in an outpost or when the sub is at the end of the level

**Version**
v0.1300.0.4, probably earlier versions as well

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/b5f62b4b-c80d-4a82-ab10-1b43f583f253)

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@364b54b. The end round button (and the vote button) are now moved down whenever the "Follow Submarine" tickbox is visible. The top message area was also moved down a bit to avoid overlap with the messages.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
