### ISSUE TITLE
Dead boss health bar can be seen when shot

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5388]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shooting the dead corpse of the target boss will show you the health bar for a fraction of a second

**Version**
v0.1300.0.4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b52710b1302c8a743b7b9ee8df96c8d3108ed0c1

**Comment by Rokvach** [comment]
I think the boss health bar should linger a bit of time before it fades out, currently its just faded as soon as the creature dies which doesn't make it as rewarding as a gameplay experience

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
