### ISSUE TITLE
listtraitor non-functional for non-host

### ISSUE THREAD

**Issue by sylvinite** [Regalis11/Barotrauma#539]
`listtraitor` is only functional for the host of the game.
For any other player with the granted permission, the command evaluates but nothing is returned.

**Comment by NilanthAnimosus** [comment]
The client doesn't even have a list of traitors on their side (Its stored solely on the server-side and the clients are never informed of who the traitors are, only if they are one and their target if that's the case).

So there wouldn't be any local information to retrieve if its doing that.

Whats confusing however is I thought listtraitor is a NilMod command.

Vanilla contains the command "traitorlist" but I had removed this command from the console (Given I had created the above listtraitor command as a means to return messages back to the clients console).

I will later see if my mods listtraitor is broken, it did include code for OnClientRequestExec with a null onClientExecute - Its likely I have simply configured the command wrong for server->client usage as it didn't make much sense to me before (Or now honestly).

**Comment by sylvinite** [comment]
Traitorlist is referred to in original barotrauma, both in the help file and https://barotrauma.gamepedia.com/Console_Commands .  As you mention I've seen the command resolve itself as `listtraitor`; but this command is equally inaccessible through the original BT.

Your mod's traitorlist is likely to work fine.
The one (very tangential issue) seems to be that some original clients have problems resolving the command from a non-host machine, despite the host itself running your mod. I however haven't explored this issue fully.

**Comment by NilanthAnimosus** [comment]
I actually commented out and deleted the code for traitorlist in my mod, clients would see traitorlist in their help on their console - but otherwise the original barotrauma had was kind of useless as a client. and I wanted client admins to have the ability to see the traitors somehow.

when I check the vanilla code on this, there is only:
```csharp
"traitorlist", "traitorlist: List all the traitors and their targets.",
```

listtraitor is a completely different command added in my mod:
```csharp
commands.Add(new Command("listtraitor|listtraitors|traitorlist", CommandType.Network, "listtraitor: Sends to chat the current traitors, targets and their status."
```
