### ISSUE TITLE
Sub Previews Fail to render subs with Modded Doors

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5392]
![image](https://user-images.githubusercontent.com/47284081/113040937-e6e0bd00-9188-11eb-98e3-2cc2df800459.png)
Unsure why this happens. Modded doors work fine when actually loading the sub, but fail when the sub preview loads them.

**Comment by Rokvach** [comment]
Tested with Thalassophobia by placing a plexiglass door to a dugong and checking the preview, no errors and preview loaded correctly showing the modded door. Working correctly. Closing.
