### ISSUE TITLE
Play in submarine editor cuts all wires more than 5 if using maxwires="more than 5"

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#5394]
parameter maxwires="any number above 5" allows to connect more than 5 wires to a pin in the ship editor, but once you playtest the game, all wires above 5 are forcefully disconnected and hanging out
asked about this in Discord server, been told it's a bug
![Issue](https://user-images.githubusercontent.com/74479084/113045554-aa708980-91a7-11eb-886f-10dfc0b9b32b.png)

**Comment by Jlobblet** [comment]
Tested with this mod: [UnstableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6299501/UnstableTestMod.zip).
Contains a test submarine and junction box.

1. Open submarine editor.
2. Load `AzimuthBigJunctionbox`.
3. Start round and enjoy the connected wires and smooth powerflow of a large junction box.

No issues.
