### ISSUE TITLE
[Unstable 1300.0.4] Going into ruin causes crash

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#5396]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes (no command console errors, no crash report) after the alien coil in a ruin comes into view.

**Steps To Reproduce**
- Load the attached save file
- Enter the main entrance (top right side) of the ruin, that the infrasonic signal takes you to
  (edit: this map has 2 ruins. Follow the map wall down 430m from the start of the map to get to the ruin in question
image: 
![buggy ruin location](https://user-images.githubusercontent.com/58775950/113051764-57c9aa00-9174-11eb-99ea-db2fa8323a92.jpg))
- In that first room, swim down until you see the alien coil (at the bottom right side)

Game will crash 

**Version**
Unstable 1300.0.4, Windows 10 64 bit

**Additional information**
- Save file: 
[Unstable 13.2_Malaco 2.0 SP Campaign.save.zip](https://github.com/Regalis11/Barotrauma/files/6231860/Unstable.13.2_Malaco.2.0.SP.Campaign.save.zip)
- The save (as seen in the name) was created in Unstable version 130.0.2
- There is a strange streak of light above the alien coil
https://cdn.discordapp.com/attachments/668819422919524352/826544900739694592/20210330155040_1.jpg
I wonder if that has anything to do with the crash?

**Comment by mrjpjr** [comment]
Update: I went into the second ruin (left of the map exit), and when I came across an alien turret (somewhere top right section of the ruin) the same thing happened... game crashed

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e5fc44bf6b5ffe702ed94f628d7424b1ac2d25e

Also noticed another issue while debugging this, the alien turret assembly didn't rotate towards the motion sensors, that should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/67b5144ca826c803c998fb0f66bc102d027055dd

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
