### ISSUE TITLE
Nav Term Sonar Mineral scanner uses a different marker than handheld sonar's

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5397]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The navigation terminal's sonar mineral scanner uses the red square marker (which can get you to confuse the mineral with a mission) and the handheld sonar uses the white marker designed for minerals.

**Version**
v0.1300.0.4

**Comment by ekqvist** [comment]
Added the missing icon for the sonar monitor in Regalis11/Barotrauma-development@bf81e44. It seems that the icon was overwritten with the new empty location icon in Regalis11/Barotrauma-development@9c02a25.

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
