### ISSUE TITLE
Sprite repeat issue with existing "Tail Fin Old A" pieces

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5398]
Tested in dev

Load up a Dugong and take a look at the tail piece, issue only seems to exist with existing tail pieces as placing a new one looks correct

Also spotted in other subs which uses the sprite

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/3ab840db-3b35-4727-89ce-e9406cb1d999)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/67bee558-9d35-4054-82b0-3d7b9c5895b5)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/130f41116adfa0b21e57dbe424d61b64f864c464 and https://github.com/Regalis11/Barotrauma-development/commit/ccb52db66983f57ac2c98577ce8eb2851dacc9a4

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
