### ISSUE TITLE
Map Editor- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#540]
### Players can make their own campaign mode maps using it's editor:

*Player can select randomized or already existing level seed to edit it.

*Player can select start point of submarine of course.

*Stations can be connected between each other by holding space button and clicking (black bold line generates automatically).

*Players can give stations custom names.

*Player can set what kind of station is this (military, city and other). This determines who is for hire to the crew.

*Player can edit on paths between stations it's length, minimum and maximum depth of the map and what missions can be done there. Player can even select if alien ruins or hydrothermal vents have to generate and which enemies have to be disabled there. In-game path between stations player passes by is than generated automatically according to settings.

If the player will try to make depth of the map to be at least 2000 he will be informed about the abyss's pressure mechanic and what it does.

Non-standard and optional in my request:
*(Completely optional goal) player can decide to set which mission after being completed makes a message pop-out about map being completed. Player can still continue playing map if he wants to. Custom maps does not need to have it.
*Map description when about to select it (can remain empty).
*Recommended crew experience when about to select map (does not have to be displayed).
*Recommended submarine when about to select a map (can remain empty).
*Starting credits amount (can remain default).
*Starting crew (can remain default).
*Starting additional cargo (does not have to be used).
*Disable shuttle usage warning. If player wants to use a shuttle he will not receive warning about how dangerous it is. This feature does not have to occur and is determined by editor's settings.

**Comment by Regalis11** [comment]
I think there would very little benefit to having a map editor, even less after the campaign changes in the dev branch. The things that could be made customizable don't have much effect on the gameplay: it doesn't really make much difference what the names of the stations are, how exactly the connections between them are laid out or where you start from. Also, in the dev version the stations change types dynamically (progressing to new areas causes new outposts to pop up and failing to clear breeding grounds may cause locations to be overrun), so the initial location types don't matter that much either.
