### ISSUE TITLE
[Minor] Bot trying to clean up another bot

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#5400]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots trying to clean the same thing, they sometimes report to be able to reach another bot in an attempt to clean them up. Does not exactly cause them to break or anything.

![image](https://user-images.githubusercontent.com/70696707/113150351-304f0c00-925e-11eb-96e6-792bd2234dab.png)

**Steps To Reproduce**
1. Have multiple bots
2. Order them to clean up
3. Drop multiple items
4. Watch them sometimes shout out "Cannot reach [name]"

**Version**
V0.1300.0.4 (Windows).

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@36c2e35 (not included in the latest unstable).

**Comment by Rokvach** [comment]
I was still able to reproduce this

Tested in the bugfixes branch

Repro steps:
1. Load up a multiplayer round with 16 bots (singleplayer might work as well)
2. Order every bot to cleanup items
3. Run around sub and drop every item from cabinets you come across
4. Notice that they will start reporting that they can't reach another bot

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9844abaf-872f-4584-8b5e-b3ab7f97b3a3)

**Comment by itchyOwl** [comment]
Try the same in the release branch. The fix doesn't seem to be in the bugfixes branch.

**Comment by itchyOwl** [comment]
Actually it seems that they just report unnecessarily about it, but otherwise act like they should: abort the current task when the target item is taken by someone else. I'll push a fix in a sec.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@32ccaf8. (bugfixes)
