### ISSUE TITLE
Unstable - Submarine Editor - When adding a shuttle to a submarine, its filepath is not saved

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5401]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When adding a new shuttle to a file, its filepath will appear when selecting the shuttle object. However, when pressing the test button, the filepath is cleared when coming back to the editor

**Steps To Reproduce**
See video or
1) Add a shuttle to any submarine
2) Click on the shuttle
3) Notice the filepath of the shuttle being there
4) Hit the test mode
5) Exit back to editor mode
6) Click on the shuttle again
7) The filepath disappeared

**Version**
Windows unstable v0.1300.0.4

**Additional information**
The workaround is to immediately refresh the shuttle after it has been added

https://user-images.githubusercontent.com/55001203/113159426-97db6c00-920a-11eb-842a-e7d0ac2ece54.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ada7091f270a119a74cffcb5045b1a27fccea089

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
