### ISSUE TITLE
Unstable - Submarine Editor - Outside pressure does not crush a character without a diving suit

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5402]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outside pressure does not crush a character without a diving suit

**Steps To Reproduce**
1) Open the Dugong zubmarine
2) Test the zubmarine
3) Step out of the airlock without any gear
4) Expect to die crushed, but instead you die of asphyxiation

**Version**
Windows Unstable v.0.1300.0.4

**Additional information**
It this intentional?

This only happens in sub editor. Other modes work fine

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d7adeb54424e8b5beaa86644657b5f7ab9d1b8f2

**Comment by Rokvach** [comment]
Tested, popped nicely. Closing.
