### ISSUE TITLE
Remove inactive orders from the crew panel by right clicking

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#5406]
I've found that I tend to right click on the inactive orders to get rid of them when I don't need them anymore. And I always forget that it doesn't work. So why not add it in? In the player experience, it's the same logic as when an active order is dismissed. So it would be quite coherent too. Functionally this doesn't matter, as new orders will make the old disappear.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/583e8c78-1ca5-45b5-a6c9-42c24f3878ce)

**Comment by Rokvach** [comment]
I've found myself doing this exact same couple times as well, maybe it was a thing at some point

**Comment by ekqvist** [comment]
Implemented in Regalis11/Barotrauma-development@e1cc22f

**Comment by Rokvach** [comment]
Tested both singleplayer and multiplayer and didn't notice any issues. Closing.
