### ISSUE TITLE
When a coilgun loader is broken, the hud will flash "no ammo", when we should tell the player that the loader is broken instead

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#5409]
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/6859ab66-5728-449d-8934-77c4cc987d11)

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/6042e3e9756c7b247f469174021ae8e2fac137be, could maybe use some visual tuning

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
