### ISSUE TITLE
More challenging endworm- Rebalancing default challenge

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#541]
I think endworm is not challenging enough to be worth 10000 credits for being killed as he can be easily dispatched using Hit&Run tactic. 

Here are ideas:

*Changed speed from 2.0 to 3.5.

*It's entire body except of front jam takes 50% less damage. This means to kill endworm with nukes now it has to be hit 10 times in jam with them or 20 times anywhere else.

*Immune to be stunned.

*Touching endworm's spiky armor by crew members outside submarine deals damage to crew.

*Endworm will go after humans if there are no submarines detected by it.

*Maybe reduce damage dealt by endworm due to his increased movement speed from 500 structural to 400 structural. Overall deal 40% more damage if that.

**Comment by NilanthAnimosus** [comment]
10 is a rediculous speed. Im not even sure you know what a 10 is.
10 is practically faster than every submarine in the game made to date given their ability to change direction...the fastest vanilla creature is around a 4-5 and practically impossible to escape usually.

I don't feel the endworm needs to be buffed, given the fact he disintegrates a massive amount of the submarine now unlike in the past, he also has an absolutely massive health pool which tends to take considerable resources that easilly equal the pay your getting (The cost is very high).

Personally if you want to "Buff" the endworm, it should have an AOE damaging effect on targets other than itself near its body, so it cannot be cuttered or welding torched to its death slowly over the course of 5-10 minutes using rechargable items or simply poisoned with ease or even granting it the possibility of immunities to such.

currently an endworm has a whopping 10000 health for 10000 credits. if you buy nuclear shells just for the occasion its 5000 credits alone to take down. with empty railgun shells its about 20000 credits. if you add explosives you cant buy compound N nor IC-4 blocks, so assuming you use C-4 blocks and railgun shells it would take 200+100 credits/shell to deal 100+200 damage. this would be 300 credits per 300 damage, the reward is 10000 and the health is 10000...it actually still costs more than the mission gives using standard railgun ammo.

Assuming the player uses a mix of whatever is available to him this mission can very easilly barely pay off.

**Comment by rico6822** [comment]
Alright, but endworm has a very large body, even at 2 speed he is slowest enemy in the game, slower than 1.2 husk. 2.0 mantis or crawler are faster, than endworm, because they are less massive.

I believe making endworm immune to stun and making his armor deal damage to people should be enough. Speed can be changed to 3.5 in case, if body mass does not have to count as slow down.

**Comment by AbominationBanisher** [comment]
I think that the endworm should be reworked, to be honest. Instead of disintegrating a bunch of walls, I feel like it should have some sort of special attack. Maybe it's teeth go through the ship and latch on, then it drags the ship to the abyss until the ship explodes? Something like that.

**Comment by rico6822** [comment]
If endworm had an special ability like it tied up with my suggestions on rebalancing endworm it's credits reward would be worth higher value than 10000, but nothing stands in the way in making endworm a very challenging mini-boss/boss enemy, since some challenging video game have bosses like it you have to try fighting them a few cautious times, before winning.

**Comment by Billsofat** [comment]
I thought it be cool if a boss monster had some kind of ranged attack, like blowing superhot steam or shells it sucks up or something. Not sure if endworm would be the best application for that though.

**Comment by rico6822** [comment]
If endworm had a smoke attack I hope it would be casted every 60 seconds. This attack causes items on the floor of the submarine or even players themselves to rapidly shake and change their positions, like they had to hit something at moderate force, it also damages walls of submarine. This smoke attack also damages crew members not shielded by the walls for more damage, than hydrothermal vents and spreads from one hull to another damaging oxygen in rooms. This attack is casted for 10 seconds and has a range of 25 meters.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
