### ISSUE TITLE
Crew orders clearing after any loading screen in campaign

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#5411]
As title says
not sure if it's a bug or just a missing feature, but that would be very helpful if AI Crewmates would keep their orders unless i manually dismiss them, so after finishing a campaign mission and starting a new one, you wouldn't have to reassign same orders for 13 crewmates over again

**Comment by itchyOwl** [comment]
It's not yet implemented. Going to be. Closing the ticket.
