### ISSUE TITLE
Moloch creating a lot of particles after nuclear explosion

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5412]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shot a nuclear shell at a moloch and it started creating an insane amount of particles.
![image](https://user-images.githubusercontent.com/55637865/113343958-df472280-9306-11eb-9042-ffe62e8d3bca.png)

**Version**
v0.1300.0.5 Windows

**Additional information**
I believe the particles were so many, that i shot at another moloch with piercing ammo and the impact particles didn't generate because the game already reached the max ammount of particles (i don't know if it works like that)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@b30e480.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
