### ISSUE TITLE
R-29 top "airlock"

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5413]
- [y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The R-29's top "airlock" / docking port does not quite function.

during the round it is closed at all times. (until someone plasma cuts it open)

It is presented as an airlock with the diving suits, cabinet, buttons by the hatch, and room label "airlock"

Further, the hatch/docking hatch are placed so high above the room they are out of reach of a screwdriver for rewiring purpose.

**Steps To Reproduce**
test round with R-29
attempt to open top airlock by pressing button

**Version**
0.12

**Additional information**
the wiring surrounding the airlock is also rather disturbing and should be looked at from a safe distance. particularly that oscillator component including circuit.

**Comment by rav2n** [comment]
https://github.com/Regalis11/Barotrauma/issues/5429

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/841dd2d

**Comment by Rokvach** [comment]
Closing this as its listed on the main ticket about the fixes
