### ISSUE TITLE
R-29 medical Item loadout

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5414]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The R-29's main medical cabinet is mostly filled with singular bandages/morphine/saline. which would have been decent an update ago. But since the stacking feature, it feels quite anemic, despite the saline..

It hits the R-29 especially hard because it is a higher crew sub and a lack of a medical fabricator.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
The complete autofill based supply cabinets leads to volatile item drops (notably the lack of manually played diving mask)
There are loose harpoons by one of the armory cabinets, also caused by stacking update.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/841dd2d

**Comment by Rokvach** [comment]
Closing this as its listed on the main ticket about the fixes
