### ISSUE TITLE
Physicorium shell not piercing?

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5415]
- [yea ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've heard the Physicorium Railgun Shell is supposed to pierce the same as a piercing ammo box and i can also see the property "maxtargetstohit=3" property in the xml, but in-game, it appears not to work as intended, i've used the moloch as an example, the shell destroys a piece armor, yet doesn't deal almost any damage at all to the body?

**Version**
v0.1300.0.6

**Comment by Rokvach** [comment]
Tested this with Humpback on the dev branch, for some reason my character died (exploded) as as soon as I fired the Physicorium shell at a Moloch

All the Physicorium shells I had in the loader just blew up, there's no trace of them.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
