### ISSUE TITLE
Heal command doesnt heal some afflictions

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5419]
**Description**
Using the `heal` command wont heal afflictions not limited to : Radiation sickness, sufforin, cyanide, morbusine poisoning (maybe deliurime too?), organ damage and nausea. Theres possibly more than the listed thus "not limited to"

**Steps To Reproduce**
Use `heal` command on the listed afflictions

**Version**
v0.1300.0.6

**Comment by Showdoze** [comment]
also it does not remove husk infection

**Comment by Ek-Videogames** [comment]
Honestly I think this disparity should be maintained but maybe clarified better in terminology.

Using the 'revive' command on a character appears to clear them of all afflictions correctly, while Heal only affects physical damage and most poisons. The ability to do this 'partial heal' for instance without losing husk infection or losing buff afflictions should be maintained in some form.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/4bbefb945d1398d444a3c48c57f53a3957032f31. Now the command can be given an extra argument ("all") to heal everything, and the help text mentions that by default it only heals "normal" damage types.

**Comment by Rokvach** [comment]
Tested in dev in sub editor test mode

Doesn't seem to be working, it thinks that the all argument is part of the name
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0eb5686a-6e2a-4fd1-be79-e94dc2207c86)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ae15cfcbd01a2eff900444096d17f048a4bf1ea

**Comment by Rokvach** [comment]
Should the all argument be tab autocompleted?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
