### ISSUE TITLE
Campaign mode handicaps to increase challenge level- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#542]
### Below request is exclusive to another request made by same author:

When starting a new game player can select one or more of below handicaps of my idea to increase difficulty of the game:

*Quality Left Behind: Items do not restore their condition upon finishing mission.

*Locked Stores: No stores.

*No Recruits: No hiring. Single player only.

*No Crew Orders: Crew orders are disabled and everybody is set to "Dismiss". Single player only.

*No Skill Leveling: Characters cannot increase their skills. Single player only.

*Solo: Only one crew member of player's choice job. Automatically triggers "No Recruits" and "No Crew Orders". In the left corner of the screen there is no option to switch between crew members (so screen is not blocked). Player can as an advantage customize his name and appearance. Single player only.

*No Retreat Option : Player cannot enter station he just started voyage from and must reach the station he selected, before moving back. Single player only.

*Time Limited Missions: Task becomes invalid if too much time passes. If xml files do not feature specified time amount of a mission it will be set for a placeholder amount of 5 minutes on cargo mission and 10 on the rest.

*Invisible Health Bars: Monsters won't have their health bars visible. In multiplayer fellow cremates also cannot have their health bars visible to others. Health Scanner HUD can be used, to see health bar of a unit cursor does point at.

*No Label Informing: Missions after displaying your distance from your objective do not update position of that objective on the map if it changes position (they still however update distance). It is also disabled to see other vessels on the map (outside of sonar's range) being displayed and their names (names are disabled at all). Sonar monitors and navigation terminals do not display distance from objectives or stations if they have no power. If objective is completed and submarine needs to leave crew is not informed about it and mission's objective first position is still being displayed. In multiplayer this feature has an additional effect of informing about respawn's shuttle timing only by sonar monitors or navigation terminals, if they have no power they will not inform about it. Handheld sonar is also affected by this feature.

*Permanent death: If a character reaches a station dead, that character is removed from crew list. Same thing comes with player's IP in multiplayer mode. Host is immune to permanent death.

*Frail Breathing: Sprinting consumes oxygen, having less and less oxygen slows sprint, less than 50% disables sprint. Every percentage of lost oxygen makes sprint slower by 1,5%.

*Hunger: Just like in BTE mod, but in vanilla there is no vending machine and not satisfying hunger results in health drain and slower movement speed. Hunger do not replenish upon completing a voyage.

*Hitscan: Being hit in head deals more damage and always stuns. Being hit in leg lowers movement speed or may even disable movement at all.

*Xenophobic Creatures: Monsters will always destroy you or your submarine, before returning to attack each other.

Note: Composing "Locked Stores" with "No Recruits" results in credits mechanic being fully disabled. "Locked Stores" already fully disable credits mechanic in multiplayer.

All those handicaps have a bonus feature called: "Difficulty Cumulating". Difficulty Cumulating feature an value called "Hardening Severity" in game's source code (but you decide how to name it if you want) if it reaches certain value or higher it's recommended crew experience will change. Having all handicaps turned off is having this value on 0. Recommended crew experience is always intermediate on from 0 to 3 Hardening Severity, anything higher will set it to experienced or higher recommendations. 

Certain handicaps increase this value by it's own amount. Let's just say No Retreat Option exclusive to single player mode increases this value by 0.5, when Time Limited Missions does 2. Reaching maximum value amount possible results in recommended crew experience being displayed as "Champion" and it happens only in single player mode, since multiplayer gives us fellow players in assistance. Difficulty Cumulating's only purpose is to judge difficulty of the campaign.

Optional: Most of these handicaps can be triggered in multiplayer's host's settings menu for non-campaign rounds.

**Comment by NilanthAnimosus** [comment]
I was unaware items were repairing themselves to begin with - I had to explicitly make this a feature of my mod to repair specifically electricals/walls/unflood rooms and other such, actual items remained damaged last I recall as it was saved into the submarine file.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
