### ISSUE TITLE
High Nausea affliction causing medic bots to hold you for a long time

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5420]
**Description**
Having high or maxed nausea affliction will cause medic bots to bug out and hold you forever, presumably because nausea has no given treatments with meds, so it just holds you forever until the nausea affliction is reduced enough/gone.

**Steps To Reproduce**
using the `giveaffliction` command, give a character 100 Nausea affliction and order a medic to Heal and Rescue, get near them and wait.

**Version**
v0.1300.0.6

**Additional information**
For consistency I tested it in this save :
[aaaa.zip](https://github.com/Regalis11/Barotrauma/files/6249717/aaaa.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ac1b1102b8563a0391ff74201450d92ec45a2037

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
