### ISSUE TITLE
Server Lobby Screen Sometimes Breaks

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5423]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Most of the UI elements can't be interacted with. 
![unknown](https://user-images.githubusercontent.com/37539527/113433949-06215980-93d8-11eb-89e1-2b603d1bdb75.png)

**Steps To Reproduce**
Afraid I don't know any steps to reproduce yet - it just happens sometimes.

**Version**
v0.12.0.3
Windows 10

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/4137
