### ISSUE TITLE
Wreck (Thalamus) spawned right next to the destination.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5424]
- [yeah ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A thalamus'd kastrull wreck spawned about 70m away from the destination, it was not blocking the path, yet i don't think i could've been able to avoid the thalamus' fleshgun.

**Version**
v0.1300.0.6 Windows

**Additional information**
Here's a save in the level where this happened.
[insane whiping.zip](https://github.com/Regalis11/Barotrauma/files/6250507/insane.whiping.zip)

**Comment by itchyOwl** [comment]
Couldn't open the zip. Is it corrupted?

**Comment by itchyOwl** [comment]
With "destination" do you mean the end of the level? Was there an outpost there?

**Comment by itchyOwl** [comment]
Can't see anything wrong with the positioning: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/a0fac2c0-6645-4012-8757-45fd3d24450b)

**Comment by itchyOwl** [comment]
Found the issue and fixed it in Regalis11/Barotrauma-development@e4dde14. Thanks for reporting!

Steps to repro:
1. load the save before the fix -> observe the wreck position (too close to the end position)
2. load the save after the fix -> observe the wreck being positioned elsewhere, far enough (10 000px/100m) from the end position.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by LePiromano** [comment]
[man.zip](https://github.com/Regalis11/Barotrauma/files/6593477/man.zip)
still happens in unstable v0.1400.3.0, but only on missions where the biome is cold caverns basic.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@e2ad9f3. The distance check failed there because the waypoint was far enough from the exit. The wrecks should no longer spawn on the right side of the exit positions (outposts).

Easy to repro and test with the save.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
