### ISSUE TITLE
Leucocyte-free thalamus

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5425]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A thalamus appeared with no leucocytes in it, and the cell spawner didn't seem to be spawning any either, terminal cells did get spawned once the spike breached the sub tho. I believe it's because of the difficulty, but it just makes the thalamus a wreck that hugs you and takes all the threat away from it.

**Version**
v.0.1300.0.6

**Additional information**
Save where the leucocyte-free thalamus is
[insane.whiping.zip](https://github.com/Regalis11/Barotrauma/files/6250576/insane.whiping.zip)

**Comment by itchyOwl** [comment]
There should always be some leucocytes inside and around Thalamus.

Couldn't open the zip. Is it corrupted?

**Comment by itchyOwl** [comment]
There should always be some leucocytes around and inside Thalamus, and it seems there's now some too. But not enough. Seems that there's something wrong with the spawn time in lower difficulty levels.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b69c89c6-7cb2-43c0-91dd-8f8e10d2b6b7)

**Comment by itchyOwl** [comment]
Partially fixed in Regalis11/Barotrauma-development@47d0e68.

**Comment by itchyOwl** [comment]
Increased the min amount of cells in Regalis11/Barotrauma-development@8e02266.

**Comment by itchyOwl** [comment]
Some suggested steps to test:
1. Do this change in the code to always spawn Thalamus ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b0174ec0-f427-496b-9e3a-0f5b0a39f21d)
2. load the save

3. Use "setdifficulty x" debug console command to test how many leucocytes there are in different levels, e.g. 0, 10, 20, 40, 60, 80, and 100.
4. After forcing the difficulty level, load a round and spawn a Thalamus infested wreck using console commands "spawnsub Wreck1 true" (The above mentioned code change is not required for this approach).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
