### ISSUE TITLE
"Praise the Honkmother" mission bug

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5427]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bikehorns from the "Praise the honkmother" mission drop into the floor when the round starts since there's only 1 crate.

**Version**
v0.1300.0.6

**Comment by ekqvist** [comment]
Reduced the amount of clown gear to fit everything into the crate (Regalis11/Barotrauma-development@544ca7e)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
