### ISSUE TITLE
Output "velocity_in" on the terminal display

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#5428]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not so long ago, the "velocity_in" input on the terminal was fixed in the game. But when transferring values to it from another terminal, the data along the Y-axis is incorrectly received, the direction of movement on the receiving terminal is opposite to the real one.

Real direction of travel (data from the control terminal):
![image](https://user-images.githubusercontent.com/29980468/113466866-bda18480-9447-11eb-8f10-e919f0631f80.png)

Displayed direction of travel at the receiving terminal:
![image](https://user-images.githubusercontent.com/29980468/113466898-fccfd580-9447-11eb-880e-d6125d08825d.png)

Checking the data sent after processing by the circuit (two concatenation elements + a memory element for separating X and Y with a comma):
![333](https://user-images.githubusercontent.com/29980468/113467197-1e31c100-944a-11eb-8a1f-016becf64946.png)

**Steps To Reproduce**
Send parameters for "velocity_in" to the terminal and check the correctness of the received data along the Y-axis.

**Version**
v.0.1300.0.6

**Additional information**
It is easy to get around this problem when passing parameters to the terminal by adding multiplication by -1 for the Y-axis to the circuit.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/de045868284450c1fe3f88d2ea5c0311eae0be3d

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
