### ISSUE TITLE
R-29 fix

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#5429]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm still not very clear about whether I should even interfere in keeping this submarine update. But since I originally made the submarine, I consider it necessary to send these corrections.

1. Changed the automatic closing circuit of the airlocks. Due to the outdated circuit, problems with hatches appeared in the current versions of the game. 
The problem is described in this ticket: https://github.com/Regalis11/Barotrauma/issues/5413

2. Changed the power consumption parameters of the discharge coils, which will slightly increase the submarine's chances of survival.

3. Changed the parameters for turning on the spotlights in the cargo bay. This now works via set_light.

4. Fixed dropping ammo and stacked medicaments that are on the submarine by default. 
The problem is described in this ticket: https://github.com/Regalis11/Barotrauma/issues/5414

5. Minor decoration fixes related to new textures and sprite depth.

6. The room containing the oxygen generator has been renamed to the oxygen generator compartment. 

7. Moved the fire extinguisher.
The problem is described in this ticket: https://github.com/Regalis11/Barotrauma/issues/5216

[R-29-fix.zip](https://github.com/Regalis11/Barotrauma/files/6252042/R-29-fix.zip)

**Version**
v.0.1300.0.6

**Additional information**

**Comment by danielasteljoki** [comment]
Thank you. Applied in 841dd2d. Since you're the original creator, we're happy to receive any modifications you want to do. 

We usually let the issues to submarines pile up a bit so we can address them in batches, and we will get to them sooner or later.

**Comment by rav2n** [comment]
I am glad to help. I will try to keep this submarine operational further.

**Comment by Rokvach** [comment]
Tested, didn't spot any issues. Closing.
