### ISSUE TITLE
Unstable - Submarine Editor - Memory Component does not have an editable max output length

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5430]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All components have an editor exposed max output length editable by the player. However this is not the case for the memory component

**Steps To Reproduce**
Place a MEM in submarine editor and look at its parameters.
Max output length is absent

**Version**
Windows, Unstable v.0.13.0.6

**Additional information**
This forces players to fall back on other methods to store long strings of data and other less efficient methods to have the same "lock_state" behaviour.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c85c7ff78dd8150a357b0dd98b597f0111dcf9f

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
