### ISSUE TITLE
[unstable 1300.0.6] Mapgen - Location without connections

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5432]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mapgen - Location without connections (pic below)

**Steps To Reproduce**
sorry, no clue yet

**Version**
win10, singleplayer, campaign map probably generated with 1300.0.3 or .0.2

**Additional information**
Pic (unlinked location is Kennet Linea) ![20210403165234_1](https://user-images.githubusercontent.com/3466193/113490620-98565a00-94cb-11eb-925f-4444ed2cb5e5.jpg)

Save: [CampMarch21.zip](https://github.com/Regalis11/Barotrauma/files/6253336/CampMarch21.zip)

**Comment by Regalis11** [comment]
The map seems to have been generated on v0.1300.0.2, and this issue was fixed in v0.1300.0.3. We have a ticket about this in our private repo (https://github.com/Regalis11/Barotrauma-development/issues/2468) that's been tested and closed, so I'll go ahead and close this one as well.
