### ISSUE TITLE
Nuclear EMP effects are technically doing 10,000% of an item's maxcondition ?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5434]
Following my previous ticket about empstrength I kept noticing that nuclear EMP effect still seems to be acting as an almost completely hard cut-off at the edge of it's radius. _(Items instantly fried, with perfectly fine ones just a couple meters further away)_

Looking at source code it appears the damage empstrength does is getting multiplied by the item's maxcondition:
https://github.com/Regalis11/Barotrauma/blob/694cdfee7bd986242b9a772cb3d1a8a65d19c29c/Barotrauma/BarotraumaShared/SharedSource/Map/Explosion.cs#L160
In this implementation it seems like its working as a sort of multiplier of a fraction of the item's condition. IE, that fraction being a decimal number from 0 to 1, with 1 being 100% of an item's maxcondition.

In XML stats however, it seems this value is being treated like a flat damage amount the same as structure or item damage. IE, a damage of `X` being applied directly out of an item's maxcondition. These values are many times higher than 1 - _which would be multiplying by 100% of an item's maxcondition_ - so essentially nukes' `empstrength="1000"` seems to be doing 1000 * 100 = 10,000% of an item's condition (regardless of it's maximum condition, due to the multiplier)

This seems like a unintentional oversight given how EMP damage appears to work VS normal item damage.

**Just personal suggestion:** changing nuclear effect `empstrength="2"` or possibly 3 at most? Maybe increase the range of the effect slightly, but basically in this form items *should* still be fully damaged if they are within' 1/2 ( or 2/3 ) of the radius. With damage falling off past that point to max radius.

**Comment by Rokvach** [comment]
It was changed to 2.5 now. Closing as this ticket has already been handled.
