### ISSUE TITLE
With dedicated server, CTRL+F and scroll bar freeze the server

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#544]
I'm using Windows 10.

It seems that using CTRL+F to search through the log causes the server to freeze, like everything just stops happening. Everyone seems to enter into desync. In my experience, closing CTRL+F dialog doesn't fix it, I usually need to restart the server.

Using the scroll bar also seems to freeze it, but everything resumes when I let go of the bar.

The mouse wheel doesn't freeze it, but this is ineffective at looking through the logs as I keep being jumped back to the newest one that pops up.

I haven't heard about this from anyone else, so it'd be helpful if someone else tries this.

**Comment by Billsofat** [comment]
Seems it is cmd doing this. Selecting text makes it go into select mode (it says select in window name), which freezes the process. This can be unfrozen by right clicking, I just found,

**Comment by Regalis11** [comment]
You can disable this behavior by disabling quick edit mode on the command prompt (Properties -> Options -> QuickEdit Mode).
