### ISSUE TITLE
[0.1300.0.6] Failed to read event for entity

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#5440]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/6258454/Multiplayer.zip)

**Steps To Reproduce**
1. Started Multiplayer Campaign.
2. Selected [Corsair](https://steamcommunity.com/sharedfiles/filedetails/?id=2071873647) as sub.
3. Sold some stuff, bought some stuff, wired up reactor logic, hired an engineer, and renamed all the bots to my moniker.
4. Started Tiger Thresher Swarm mission.

**Version**
0.1300.0.6

**Comment by Rokvach** [comment]
I think this is related https://github.com/Regalis11/Barotrauma/issues/5439

Buying something in the first outpost seems to be throwing entity issues, so far it seems its limited to the first outpost but I might be wrong with that

**Comment by Rokvach** [comment]
Here's all my findings so far

Event logs (From server host side only)

Client
[https://app.zenhub.com/files/93301055/648b217f-d56f-462e-9bb5-e0d7658e0e88/download](https://app.zenhub.com/files/93301055/648b217f-d56f-462e-9bb5-e0d7658e0e88/download)

Server
[https://app.zenhub.com/files/93301055/97f1007c-53d6-458a-9b5a-6d2beeff3000/download](https://app.zenhub.com/files/93301055/97f1007c-53d6-458a-9b5a-6d2beeff3000/download)

Tested myself by buying a combat diving suit in the first outpost and undocked, got this
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bfc75bd6-1b3d-4c67-8a9b-58387c8d9dd5)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1db55769d0a43b7d8e3d8989074da5a407dfc20a

**Comment by Rokvach** [comment]
Tested solo, didn't encounter any entity issues. Will keep the ticket open till the next Unstable testing

**Comment by Rokvach** [comment]
There's still some event entity issues, but not this one. Seems to be working correctly. Closing.
