### ISSUE TITLE
Clients don't get the option to download a custom sub they don't have

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5444]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clients don't get the option to download a custom sub they don't have unless they have permissions to edit server settings.

**Steps To Reproduce**
1. Host a server with custom subs
2. Join as a client, make sure you don't have any special permissions
3. Select one of the custom subs and try to start a new round

**Version**
v0.1300.x.x

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a132b606f27d928c716785a2a8c4dd2bc1ac9ff

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
