### ISSUE TITLE
[v0.1300.0.6] My bots steal diving suits from outposts

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5445]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I noticed excess suits on my sub in SP campaign. Just verified that bots steal them from the outposts.

**Steps To Reproduce**
More a guess, but seems to happen like this:
1. My bot is on the station 
2. Set bot to follow me
3. Player puts on a diving suit
4. Bot graps next suit available - probably from the outpost suits.

**Version**
Win10, singleplayer campaign, vanilla, fresh testrun with v0.1300.0.6

**Additional information**
We tried a crew internal intervention talk with the bot. 
He refuses to accept his wrongdoing and stays in denial.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
