### ISSUE TITLE
[v0.1300.0.6] Medic bots still munch through medical supplies like crazy

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5448]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Didnt handhold my medic bot for a moment and he went though 10 morphine and 8 bandages in an instant by healing very minor scratches of the other bot crew. Seems he e.g. slapped 5 bandages on a bot - on each body part where he had less than 3% burns....

We really need a better way to manhandle those dreaded medic bots. Please consider more access to the AI statemachine, so we have more options to set action priorities for the bots. (Pulsar Lost Colony did a very good job in this department, btw)

**Steps To Reproduce**
Well, give medic bots medical supply stuff and bots finds every single, minor way to waste them....!

**Version**
Win10, SP campaign, vanilla, [v0.1300.0.6]

**Additional information**
We tried a crew-wide intervention talk with the medic bot. He refuses to see his fault in wasteing med supplies. Captain considers to shoot him for subordination...

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/98be27b19993cf2d8dcb368a326aaefde9a43586

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
