### ISSUE TITLE
Ruins spawn on top of each other

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5450]
**Description**
Same save as #5449
[BigIron2.zip](https://github.com/Regalis11/Barotrauma/files/6273007/BigIron2.zip)
![image](https://user-images.githubusercontent.com/59519434/113898525-40ba3600-97cc-11eb-86de-7bc8c9e5c9d2.png)

**Steps To Reproduce**
-load save and check the ruins on the mid bottom part of map

**Version**
Unstable

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this in either the latest unstable version (0.1300.0.8) or the one in the screenshot (0.1300.0.7). This is the level I got in 0.1300.0.7:

![image](https://user-images.githubusercontent.com/14351070/114402696-c3683a00-9bac-11eb-81b3-a15f59cb3322.png)
