### ISSUE TITLE
Damaging husks decreases player's Karma

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5452]
**Description**
Enable karma damage for enemies
Shoot husks
I dont know if this log is descriptive enough. The only negative karma setting I had was for damaging friendly.
[Big Iron_2021-04-07_1614.txt](https://github.com/Regalis11/Barotrauma/files/6273035/Big.Iron_2021-04-07_1614.txt)

**Version**
Unstable

**Comment by ekqvist** [comment]
I tried reproducing this but the karma seemed to increase when attacking a husk, no matter if it was an "original" husk or a crew member turned into a husk. Can you reproduce this consistently? If so, can you provide additional steps for this?

**Comment by Rokvach** [comment]
I'm suspecting its a misunderstanding, when a player has a very low karma all of their actions are highlighted in the server log. So if the action was just colored that would mean that the player doing the action has low karma. But if it stated that the players karma was lowered (can't remember if we show that) then ofc it would be an issue.

**Comment by ekqvist** [comment]
No known steps to reproduce this and hasn't been reported since, as far as I know. Closing the issue.
