### ISSUE TITLE
Outpost module - lightswitch on top of vending machines in crewmodule

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5457]
**Description**
![image](https://user-images.githubusercontent.com/59519434/113921633-8552cb00-97e6-11eb-819e-f8732cf4c229.png)

Just a bit of shuffling needed

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/591da40453112ef2176b5817a3a7e4dd335aca72

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
