### ISSUE TITLE
[Unstable] Can't spectate if you get kicked to lobby while a new round is starting

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5463]
Noticed in multiplayer campaign

Shows up like this in lobby
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6e499db7-f4cb-44bb-9d99-ea2fabef1032)

**Comment by Regalis11** [comment]
Steps to repro?
![image](https://user-images.githubusercontent.com/14351070/114007097-b2948d00-9869-11eb-8598-1edcaa3e626f.png)

**Comment by Rokvach** [comment]
Tested with two clients running on a dedicated server, wasn't able to reproduce this. But players who weren't able to spectate were disconnected at the start of the abandoned outpost round because of this error, so could be because of that error that the game didn't let them spectate. 

https://github.com/Regalis11/Barotrauma/issues/5464

**Comment by Rokvach** [comment]
Closing this one as I fully forgot that I wrote it and the new ticket has a bit more details
https://github.com/Regalis11/Barotrauma-development/issues/2580
