### ISSUE TITLE
[Unstable] Some players are set as spectators when leaving an outpost level in multiplayer campaign

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5465]
When leaving a outpost some players are forced in to spectators, host has to enter lobby in order to get everyone onboard. The players were alive in the outpost level.

**Comment by Regalis11** [comment]
Steps to repro?

**Comment by Rokvach** [comment]
I wasn't able to reproduce this issue when playing with two clients on a dedicated server. But this happened every time we left a outpost or a abandoned outpost yesterday during Udrakan's campaign server. There  wasn't any type of errors popping up when it happened you just noticed that you were suddenly a spectator with the spectator icon in the crewlist when the round started and no way of respawning in so Udrakan had to return to lobby each time and hit continue from there to get those spectating players back to their characters.

**Comment by Udrakan** [comment]
This also hapenned when leaving towards a normal outpost. I cant remember if it hapenned for natural formation transition. Will report if it does.

**Comment by Rokvach** [comment]
We didn't encounter this at all in the latest Unstable build

**Comment by Rokvach** [comment]
This might of been caused by something else that was already fixed for the latest Unstable build. There was no sightings of this happening. Closing.
