### ISSUE TITLE
[Unstable] Biohazard mission doesn't use the correct icon

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5466]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1033c6d2-13e9-4c8d-a98a-ced36eba7de1)

**Comment by ekqvist** [comment]
Changed the icon in Regalis11/Barotrauma-development@ad0ef66

![image](https://user-images.githubusercontent.com/16864465/113979565-1610c180-984e-11eb-8acd-3416c0af3f3c.png)

**Comment by Rokvach** [comment]
No issues, closing.
