### ISSUE TITLE
[1300.0.7] Error Mudraptor_hatchling and ESC not available

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5467]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At the start of a no mission run this error popped up in the console and ESC key wasnt working at all.

ESC was working again when the next level was loaded.

**Steps To Reproduce**
Sorry, none found. Single situation so far

**Version**
Win10, unstable SP campaign
mods: wrecks extended, more wrecks

**Comment by Regalis11** [comment]
Do you happen to remember what the error message was or do you have a log file or screenshot?

**Comment by CurePindal** [comment]
ooff, Im such a dork - i was sure I added the copy from the console here, but forgot. Problem is ive already removed the txt I used as placeholder. Deeply sorry! =(
Its was a ragdoll file issue with the mudraptor hatchling and i think Mudraptor_hatchling.xml was mentioned.

**Comment by Regalis11** [comment]
Most likely caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/5696
