### ISSUE TITLE
[1300.0.7]Map vs bot command menu glitch

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5468]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Having bot commands open and opening the map keeps the bot command menu open while the map in the background is unusable. (see attached pic)

Expected behaviour: 
- Bot menu closes when opening the map, because 'either or'.

**Steps To Reproduce**
Open bot commands, open map, voila!

**Version**
Win10, unstable SP camp, vanilla.

**Additional information**
![20210408121035_1](https://user-images.githubusercontent.com/3466193/114027480-b0392f80-9877-11eb-9ce7-3a0f2233c372.jpg)

**Comment by Rokvach** [comment]
I think this is intentional, the bot commands should be accessible everywhere same with the crewlist, you can always just close the bot commands by pressing MMB again or right clicking, if closing the commands menu doesn't work in that state then its an issue.
