### ISSUE TITLE
Crazy Idea About Docking- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#547]
How is it possible, that two submarines while docking to each other leave no water between themselves, even when not powered to each other?

This idea increases logistics of submarines being docked to each other, as there is no longer any hull between them (that's what this request is trying to achieve) preventing flood from occurring while going from one submarine to another. Why? Because there is still water visible in the background in the space, between submarines. That water should flood entire space between them instead of being prevented out of it by some unknown Jedi force. It also increases the challenge of the game, as diving suits have to be used, when transcending between submarines and the rest of the door have to be locked, while doing it to prevent other parts of both submarines to flood.

**Comment by Regalis11** [comment]
I'm personally not that fond of the idea, I feel it would just be an extra annoyance to players and submarine designers. While automatically emptying the tiny space between the docking ports may not be that realistic, we could do a bit of handwaving and say the ports are equipped with some sort of automatic system that pumps the water out (perhaps the same automatic system that somehow clamps the sub in place regardless of whether there's power or not).
