### ISSUE TITLE
[1300.0.7] Sub/screen jittering, killing FPS (European Ridge currents?)

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5470]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The past few days I noticed cases where the sub started to jitter in a rather unnatural way. 
Yesterday evening all 5 players in the game confirmed the jittering and significant framedrops.

**Steps To Reproduce**
Nothing consistent, but my guess is that its related to the currents in the european ridge biome.
It seems that the currents shake the ship and the shake frequency maybe goes bonkers into frentic jittering with almost micro-stutters and frame drops.

The same MP game hasnt had this issues in the previous biome.
My current SP run in the plateau so far no longer shows this jittering.
The client-hosted game had no visible tech issues - RAM fine, CPU ~15% total, GPU relaxed, Internet connection fast, short routes and stable.

**Version**
Win10, noticed with: vanilla SP/ vanilla MP with 5 players/modded unstable with EK Armory/Utilities, Extended Wrecks

**Additional information**

**Comment by Udrakan** [comment]
I have removed the screen shake via xml and can confirm that the game is much smoother for me (i have relatively weak system)

**Comment by CurePindal** [comment]
> 
> 
> I have removed the screen shake via xml and can confirm that the game is much smoother for me (i have relatively weak system)

Mind to share the xml name and your changes? Would like to try it too, because i wasnt sure if its acutally screen shake or if the sub is shaking.

But just for clarification, this effect was more than just the usual, even heavy, shaking.. Significantly, unusual,  faster jittering.

**Comment by Regalis11** [comment]
Could be related to https://github.com/regalis11/barotrauma/issues/4597 and the fix implemented in https://github.com/Regalis11/Barotrauma-development/commit/ec6eaccdee3a8a8650b71240f0368fd62067e816 might help with this.

**Comment by Rokvach** [comment]
Tested, didn't notice this happening. Seems to be working. Closing
