### ISSUE TITLE
Non issue? Stealing something and then place the item to a stack with non stolen items, makes them non stealed.

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#5483]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Steal an item, place it in a stack of other same items, more than 3 items, after it it is stacked as 4 item stack the stolen item doesn't have it's stolen mark on it anymore.

**Version**
win/linux 0.12.0.3

**Additional information**
Maybe a non issue. As who cares anymore you have all ready lost the reputation.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/5e4ab8a1272c9fc55c73e1745a01f981d79f0c8c

> Show the stolen icon on stacks that contain any stolen items, not just when the 1st item in the stack is stolen

**Comment by CurePindal** [comment]
> 
> 
> Addressed in [Regalis11/Barotrauma-development@5e4ab8a](https://github.com/Regalis11/Barotrauma-development/commit/5e4ab8a1272c9fc55c73e1745a01f981d79f0c8c)
> 
> > Show the stolen icon on stacks that contain any stolen items, not just when the 1st item in the stack is stolen

But what happens when you put 1 stolen item on a stack, so the stack gets flagged as whole, and then you separate the stack again?
Wouldnt it be better to disallow stacking of stolen with legal items instead?

**Comment by ekqvist** [comment]
Thanks for taking the time to close the issue, but we'll keep it open until it's been reviewed by QA.

**Comment by JoneKone** [comment]
ok

**Comment by Regalis11** [comment]
> But what happens when you put 1 stolen item on a legal stack, so the stack gets flagged as whole, and then you separate the stack again? Wouldnt it be better to disallow stacking of stolen with legal items instead?

The thing is, the stacks don't really get "flagged" in any way: some items in the stack are stolen, others aren't, and if you split the stack you can still see which ones are. While this might not be a perfect solution, I think it's a better option than preventing them from stacking. The minor inconvenience of not being able to tell how many of the items in the stack are stolen on a glance is imo much less bad than adding an extra rule (or inconsistency) to the inventory logic and UX to "solve" a rare edge case like this.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
