### ISSUE TITLE
[1300.0.7] Glitch: Minor Inventory drag & drop issue

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5484]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dragging an oxy tank from a full toolbelt into your diving suit drops the tank from the suit on the bottom even when theres free space in your main tool bar slots.

Expected: Exchanged, empty tank ends up in a main tool bar slot - if available - instead of being dropped on the ground.

**Steps To Reproduce**
- with diving suit on: drag a oxy tank from a full tool belt into the diving suit.
- exchanged tank gets dropped onto the ground even when a main tool bar slot is available.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2090646f90aaf36441bd5c47b4e2f1f50224e70

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
