### ISSUE TITLE
Cannot load save if there are too many items in inventory

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5487]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a character's inventory somehow gets more items in it than it has space, the game will refuse to load the save.

This could happen because a mod is enabled that reduces the stack size of items, the game is updated and the stack size of items is reduced, or the save is edited (which is how I produced this example save).

**Steps To Reproduce**
1. Load this save [Inventory Size Error.zip](https://github.com/Regalis11/Barotrauma/files/6286912/Inventory.Size.Error.zip)
2. Observe.

Expected output: similar to [consoleOutput.txt](https://github.com/Regalis11/Barotrauma/files/6286918/consoleOutput.txt).

**Version**
v0.12.0.3 and also v0.13.0.8 (tested on v0.13.0.8)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bff3f39157aedb905df0d24933cf868d7bbe204a, now these excess items should spawn in a duffel bag in the sub.

**Comment by Jlobblet** [comment]
Tested with the attached save. No issues.

**Comment by Rokvach** [comment]
Closing
