### ISSUE TITLE
Client can't connect to any servers related to the game

### ISSUE THREAD

**Issue by DataCrusade** [Regalis11/Barotrauma#549]
First off, when I open the launcher, it says this:
![screenshot_18](https://user-images.githubusercontent.com/36621129/43423478-24c0360e-9412-11e8-8687-21f1a62ab9b5.png)
Not a huge deal, can still open the game and doesn't stop me from playing. However...

When I click Join Server, I get this error message:
![screenshot_17](https://user-images.githubusercontent.com/36621129/43423509-418708e4-9412-11e8-81ce-4d8fe673fd9b.png) 
When I click ok, it closes the message and the server list is completely empty, not even any "Can't find any servers" message. This error message pops up every time after I click refresh and I can't play Multiplayer because of this.

I have no idea why this is happening and I basically can't play the game because of it, unless I want to play the boring Singleplayer mode.

**Comment by Regalis11** [comment]
The error message seems to imply that something is preventing Barotrauma from using that socket. Could it be that your antivirus of firewall is blocking the game?
