### ISSUE TITLE
Large enemies, including abyss monsters, cause extreme screenshake for long periods

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5491]
**Description**
Title and also, here is a clip:
https://medal.tv/clips/49014663/d13371SeM05M

**Steps To Reproduce**
-have a large monster or abyss monster attack you repeatedly while sub lodged against terrain

**Version**
Unstable

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
