### ISSUE TITLE
Charybdis pushes the submarine kilometers outside the level after it falls on sea floor

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5492]
**Description**
Title, here is a save
[BigIron2.zip](https://github.com/Regalis11/Barotrauma/files/6288233/BigIron2.zip)

**Steps To Reproduce**
-load save, select the abyss monster path
-engage charybdis, the sonar distance is usually wrong sometimes even by 500m, so just approach the x
-fall onto the sea floor with the charybdis still attacking
-it might push you outside of the level at extreme speeds with extreme screenshake like here:#5491

**Version**
Unstable

**Comment by Rokvach** [comment]
This hasn't happened for a long time now, already fixed so closing.
