### ISSUE TITLE
Modded loading screen tips are never shown.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#5494]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Within xml files defined as "text files" in filelists, you can find loading screen tips among text for the names and description of characters / items / afflictions / missions etc. 

Creating a modded text file and including it in your mod will allow you to write your own text for your modded things, which works perfectly well for all languages.
However, adding your own loading screen tips to a modded text file will not result in your tip showing up in the loading menu while playing.

**Version**
Stable build: v0.12.0.3
I'm assuming it also happens in unstable though I haven't checked.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/583aecb652b21f84d173181e101ecf0f9484ddc4

**Comment by Rokvach** [comment]
Looks like this broke newlines 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f04816af-860d-4ce1-b86d-b824872093c3)

**Comment by Jlobblet** [comment]
Tested with this mod: 
[UnstableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6342690/UnstableTestMod.zip)
No issues.

**Comment by Rokvach** [comment]
Closing
