### ISSUE TITLE
Campaign softlock-Map crush depth warning doesn't show until submarine switch, stopping campaign

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5497]
**Description**
After we switched to Dugong mid campaign and looked at map, there were no warnings, yet when we loaded the level we instantly plummeted onto seafloor without a way to get back to outpost. Because submarine was too far, we couldnt enter the docking module and press the outpost button. Reloading the level resulted in the same situation, there was no time to press the docking button in time, resulting in a campaign being locked. I had to go to the docking port, use teleportsub and click the button while the sub was still near. Here is save:
[BigIron2.zip](https://github.com/Regalis11/Barotrauma/files/6290748/BigIron2.zip)

**Steps To Reproduce**
-load save
-switch to Dugong on the outpost terminal
-look at the map screen: theres no crush depth warning
-load the level
-Dugong is now near crush depth (we upgraded hull, so it no longer gets crushed instantly)
-redock
-map now shows crush depths warning properly

**Version**
Unstable

**Additional information**
Seems the map should display depth warnings for the sub the crew switched to, instead of current sub.

**Comment by ekqvist** [comment]
We should now also take into account the possible pending submarine switch (Regalis11/Barotrauma-development@b2d5444)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
