### ISSUE TITLE
[1300.0.8] Bots swap out full fuel rods

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5503]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Very often I find 99% fuel rods dropped in front of the reactor. (default reactor, single rod usage)

**Steps To Reproduce**
Couldnt catch the bots in the act so far, so no idea when that actually happens
- rough guess: 2 bots pickup the refuel reactor job at the same time and dont notice that the first bot already replaced an empty rod? So the 2nd would still have the task active and swaps rods again.

**Version**
Win10, SP, vanilla. This happened across all 1300.x releases.

**Additional information**
The issue was mentioned in the comments here, but is a different issue. https://github.com/Regalis11/Barotrauma/issues/5213

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@aefa5af. Closely related to #5213.

**Comment by Rokvach** [comment]
Tested, haven't seen this happening since the fix. Working correctly, closing.
