### ISSUE TITLE
Caret is misaligned when selecting text fields

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#5506]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to position the caret in textfields consistently places it too far to the left of the cursor. 

Some examples:

![image](https://user-images.githubusercontent.com/50582661/114551511-cbcf7c00-9c63-11eb-96d4-1a2a38b0478d.png)

**Steps To Reproduce**
Place a component with a text field, like a mem. Type some text in it. Place the cursor somewhere on the text and click. The caret is not placed where the cursor is aiming. Note that the offset seems to be dependent on the text width, so for testing it would be advisable to use characters of different widths.

**Version**
Pretty sure this bug has been plaguing the editor since the dawn of mankind.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e43d74696f6d434bef8130c0b83a6983796f648d

**Comment by Working-Joe** [comment]
Tested, working

**Comment by Rokvach** [comment]
Closing
