### ISSUE TITLE
[QoL Suggestion] Submarine editor Test mode and "quickstart" command would use submarines spawn jobs

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#5507]
Just a little Quality of life improvement suggestion to a Sub editor playtest and quickstart command, it would be really handy if spawn points in submarine would spawn their assigned jobs and you won't be forced to spawn as specific team (captain engineer and mechanic in Sub editor and captain, engineer, mechanic. medic, security officer in quickstart)  so you can test custom jobs and equipment on AI without manually spawning them through console or going to campaign mode where spawn points are working as intended

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. This is a feature request rather than a bug report. Closing.
