### ISSUE TITLE
Condition on Tooltip Does Not Update

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5508]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When hovering over an item, the tooltip's "condition" section does not update. Instead, it displays the value when the item was hovered over.

**Steps To Reproduce**
1. Place a fuel rod in a reactor (with high fuel consumption rate), or an empty oxygen tank in an oxygen generator.
2. Hover over the item.
3. Observe the difference between the tooltip condition and the condition bar.

**Version**
0.12.0.3+

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ced82cfd6127cb2a5f7f64b98a36e0cc51fb5367

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Jlobblet** [comment]
This also applies to contained items.
Steps to reproduce:
1. Place a crate in the first slot of a deconstructor.
2. Start deconstructing items.
3. Hover over the crate.
4. Observe.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3869de8bbb17beb756cd6f3b2e54bcb7afaf3908

**Comment by Jlobblet** [comment]
Tested with the above steps. The tooltip updates appopriately, however the animation for an item being placed in a slot is in the second slot not the first.

**Comment by Rokvach** [comment]
Closing
