### ISSUE TITLE
Docking Ports and Hatches issue

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#551]
v0.8.1.10 is causing some docking ports/hatches to flood areas. It only happens on certain submarines, though.

I did some testing with vanilla only custom subs in v0.8.1.7, v0.8.1.9 and v0.8.1.10 and it only happens in the latest version.

**Comment by Regalis11** [comment]
Which submarines does this happen on? I've been testing a bunch of custom submarines (both vanilla and BTE) and haven't been able to reproduce this.

**Comment by Regalis11** [comment]
Looks like this still happens: https://undertowgames.com/forum/viewtopic.php?f=18&t=10516

**Comment by BillCombs** [comment]
I have a problem where i cannot get from the shuttle up into the submarine, for some reason something is pushing the character back down into the shuttle(sometimes even hard enough to push the character through the walls into the water).
