### ISSUE TITLE
[Unstable] Characters spawn duffelbags with random items in them at the start of a round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5511]
Needs more investigation but it seems that characters spawn duffelbags at the start of a campaign round with seemingly random items in it, noticed a bag with just a welding tool in it. Might be related to how we handle item overload if there's not enough inventory space but somehow its getting messed up at round start.

**Comment by LePiromano** [comment]
Figured out, it drops the item you were holding before the round end in a duffel bag, if the item doesn't fit in a duffel bag it just dissapears

**Comment by Rokvach** [comment]
Repro steps:
1. Start a singleplayer game
2. Fill up your inventory to the point that you have items in your hands
3. Leave outpost
4. Notice that a duffel bag spawns in

I've mainly noticed it happening with two handed items like the underwater scooter or welder

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/769e2571433910fc83139e6bdc2c7009e03e50dc

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce, working correctly. Closing.
