### ISSUE TITLE
[1300.0.x] Advanced diving suit requirement not communitcated ingame

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5513]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems its nowhere communicated when you actually need the advanced diving suits (abyss/combat).

I think its important that this info is somehow relayed to the players ingame properly to prevent those nasty "oops, nobody told me"-situations. 
And I think the warning that the default suits arent suitable when you want to leave the sub is a tad too late ("oops, surprise mechanic!!!")

**Comment by CurePindal** [comment]
I tried to find out the differences between the abyss- and combat suit. Was told on discord that the combat suit also has a limited diving depth. So far nobody could tell me how deep it can go.
So yeah, that info is definatly not well communicated ingame, hehe :P

**Comment by RaptorIM** [comment]
Perhaps adding the maximum depth the suits are certified for into their in-game descriptions would resolve this easily?

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/622250707e38e0762cac68819b87632633ecd671

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
