### ISSUE TITLE
The interaction range of the Engine in Remora only covers half the device

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5514]
Can be interacted only if you are inside the highlighted area of the picture

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e557d20a-be0c-425f-b347-82f714314c3b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6891e64c3f87fc7205fdc1b5d24a998760e55146

**Comment by Rokvach** [comment]
The range looks to be the same still, does it update when we bump the version number?

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
