### ISSUE TITLE
[1300.0.x] Need larger abandoned outposts

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5518]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The abandoned outposts are amazingly fun! Great job here, guys! (Extra points to the design department - almost looks like my home....)
But we need larger outposts!

I/we did them a lot in the past 2 weeks and they are easy to solo quickly after you got the hang of it.
Still fun with 2-3 players, but they soon become too small. And with that its just run'n'gun to clear it.

Also, usually most players on the sub want to go in. Even the weird crafter who never gets out of his workshop suddenly joins this ride. Its just too much fun to miss out.
I also hope that larger outposts might require a tad more tactical approach instead of just run'n'gun. More maze, more corners, more uncertainity.

Also: husk- and thalamus-infected stations possible? =)

**Comment by Regalis11** [comment]
Thank you for the request! I agree that the abandoned outposts could be bigger, especially on higher difficulty levels. Also relayed this to our design team.

However, since we only use the issue tracker for bug reports, I'll close the ticket.
