### ISSUE TITLE
[Unstable V0.1300.0.9] attempting to equip armor while wearing a suit drops the suit

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#5519]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a player has armor on their hotbar, double clicking armor, pressing the hotkey button or dragging it onto the suit ditches the suit for the armor. This is problematic as especially hotkeys are easy to mispress, which if outside will result in you dropping your suit into the abyss and dying to barotrauma:tm:.

Ideally wearing the armor would require removing the suit manually first, at least underwater. Trying to equip the armor otherwise should give the failing animation on the diving suit slot, similar to how it works now if you try to equip a suit while wearing armor with a full inventory

**Steps To Reproduce**
Put armor in your hotbar. Wear a diving suit. Press the hotkey for the armor. You now wear the armor.

**Version**
Unstable V0.1300.0.9

**Additional Information**
It is also currently possible to equip a suit while wearing armor, as long as your inventory is not full. This, however, is beneficial as it is convenient to be able to be able to quickly suit up.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/194358c562a28916a52a20a473473e0c60c02431

**Comment by Rokvach** [comment]
Only thing I noticed was if your inventory is full you can't pickup a diving suit if you are wearing a body armor, could we handle that similarly as we do with the oxygen tanks where we just drop the body armor in favor of the diving suit? As that's what the player would need to do, unless they drop something of less valuable from their inventory and place the body armor in there, but thats still quite a slow process to manually do in a pressurized situation

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
