### ISSUE TITLE
[1300.0.9] Cant grab ragdolled players

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5520]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We noticed that we can no longer grab ragdolled players (in suits) and pull them along.

Expected: Ragdolled players (in diving suits) can be grabbed and pulled along as before (because its also a great cooperative gameplay feature)

**Steps To Reproduce**
- Both players in suits (also works without)
- one player ragdolls
- no "grab" action shown on the ragdolled player

The issue is 100% reproduceable with the attached save.
Tested all suits. Same issue with or without suits.

test: 
- grab is shown perfectly fine on stunned players
- grab and drag technically still works when grabbing the player with "heal" instead

**Version**
bugged along the 1300.x versions. Tested today on x.9, vanilla, multiplayer

**Additional information**

Save created with version x.9, vanilla
[test_suits.zip](https://github.com/Regalis11/Barotrauma/files/6317946/test_suits.zip)

**Comment by Rokvach** [comment]
This can be reproduced in the sub editor by using the "ragdoll" command and then switching to a bot and you will notice that there is no grab option at all on the ragdolled bot

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/477480f77c98142f0e87fa89f539f0efedabadd3

**Comment by itchyOwl** [comment]
I don't think that fix works as it should.

**Comment by Regalis11** [comment]
Should be working now https://github.com/Regalis11/Barotrauma-development/commit/880b056b436cb8545b074dde5a4abe2667f86908

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore, working correctly. Closing.
