### ISSUE TITLE
In game, text fields in components don't update until you've interacted with a different component

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#5521]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The values in text fields of components only update after you've interacted with a different component. Ideally these values would be updated every time you open the component, or even in real time until you press the component's text field. 

**Steps To Reproduce**
- Place a terminal and two memory components component. 
- Make a connection  from "signal_out" on the terminal to the "signal_in" on the first memory component.
- Press test. 
- In game, look at the contents of the first memory component. It should be empty. 
- Type something in the terminal. 
- Look at the contents of the first memory component again. It still appears empty. 
- Look at the contents of the second memory component. 
- Look at the contents of the first memory component once more. Only now has the value updated to whatever was typed in the terminal. 

**Version**
Present for a long time already, currently tested in Unstable V0.1300.0.9.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e77a7aba0af09ec12e80c19f3019ff4af2025b12

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
