### ISSUE TITLE
Bots wait for the oxygen tanks to be entirely drained before swapping new tanks in

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#5524]
Happens only in the main sub.

Steps to repro:
1. Using the sub editor, add as many new oxygen tanks as there's suits in the sub
2. Set exactly 10 condition for each tank
3. Insert these tanks in the suits
4. Ensure that all bots have a full oxygen tank in the inventory 
5. Make some holes to make the sub flood
6. Observe the bots to take the suits and wait for the oxygen to deplete before continuing.

Fixed in Regalis11/Barotrauma-development@05f165b

**Comment by Rokvach** [comment]
Tested, as soon as they equipped the suits which had the 10% filled tanks they immediately swapped those with the full ones they had in their inventories rather than wait for the tank to fully drain

**Comment by Rokvach** [comment]
Working correctly, closing.
