### ISSUE TITLE
Bots throw full oxygen tanks away when they are not in the main sub (e.g. in wrecks)

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#5525]
Bots throw full oxygen tanks away when they are not in the main sub, resulting in suffocation and lost oxygen tanks while exploring e.g. wrecks. Happened because they tried to be smart and act early but then failed to swap the bottles because the current tank was not yet empty and the contain item objective failed.

Steps to repro:
1. Take a full stack of oxygen bottles with you
2. Equip a diving suit
3. Teleport inside a wreck
4. Ensure that the hull floods, for example by spawning some explosions
5. Enter freecam mode and observe the bot's behavior: when the oxygen is at 10%, the bot throws all the oxygen tanks away unless the tank currently equipped in the suit is depleted. Does not happen when there's no oxygen tank inside the suit or if the tank is empty.

To make it easier to test, you should make masks and suits deplete oxygen tanks faster. For that, do the following changes in divinggear.xml:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/73454be6-d365-4337-bd70-3b5991b8f28f)

Fixed in Regalis11/Barotrauma-development@40652d3.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce anymore, working correctly. Closing.
