### ISSUE TITLE
[Unstable V0.1300.0.9] Copy pasting components with more than 200 characters in a field will cause the field to be cut off

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#5529]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a component with more than the default 200 characters is copied, regardless of the set max output length, the new component will have only the first 200 characters of the original component.

**Steps To Reproduce**
- Place a component with an adjustable max output length, for instance a signal check.
- Adjust the max output length to be above 200 characters
- Paste a long string in the text field
- Copy-Paste the item to duplicate it
The new component now contains only 200 characters

Useful test string:
"....5...10...15...20...25...30...35...40...45...50...55...60...65...70...75...80...85...90...95..100..105..110..115..120..125..130..135..140..145..150..155..160..165..170..175..180..185..190..195..200..205..210..215..220..225..230..235..240..245..250..255..260..265..270..275..280..285..290..295..300"

**Version**
Unstable V0.1300.0.9

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4a11248bd665aeb4eafe7e958b90ccb386bbad0a

**Comment by Working-Joe** [comment]
Hmm, this still seems broken in v0.13.0.11

**Comment by Regalis11** [comment]
Unfortunately the fix didn't make it to the latest release version.

**Comment by Working-Joe** [comment]
tested, working correctly in V0.1300.1.11. Thanks again!

**Comment by Ecchi-Ki-Senpai** [comment]
tested in v0.1300.1.11, working correctly

**Comment by Rokvach** [comment]
closing
