### ISSUE TITLE
can't launch missions

### ISSUE THREAD

**Issue by drowedfox** [Regalis11/Barotrauma#553]
I finished one mission, saved then couldn't launch any other missions

**Comment by Regalis11** [comment]
I'm guessing you mean the bug where the start button stays disabled after returning to the map screen and can't be re-enabled if there's only one location you can travel to? Or is there some error message when you attempt to launch a new mission?

**Comment by Regalis11** [comment]
I'm not sure if the bug fixed in 027ceba was what you meant - if not, let me know and I'll reopen this.
