### ISSUE TITLE
[Unstable] Docking with a respawn shuttle to a outpost ends the round and makes the respawn shuttle into your sub

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5532]
The main sub does still exist in the level, so if you retrieve the main sub and dock with it to the outpost you will get your sub back

Also if you keep repeatedly docking with a respawn shuttle you can have multiple of them in the level

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dc8f4b465c6d82ee1244a8cc6bfba1e6e84b1d3d

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce anymore. Working correctly, closing.
