### ISSUE TITLE
Invalid affliction IDs in a husk appendage straight up crash the game

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#5534]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Should you have a husk appendage, and on attack it inflicts an affliction, like so:
![Screenshot from 2021-04-16 22-40-07](https://user-images.githubusercontent.com/48958412/115099648-44089c80-9f05-11eb-94ca-b41fc4931783.png)
If the affliction doesn't exist, the game will crash.
Surely it should throw an error instead?

**Steps To Reproduce**
![Screenshot from 2021-04-16 22-40-07](https://user-images.githubusercontent.com/48958412/115099681-7619fe80-9f05-11eb-94df-61e8942f8150.png)
![Screenshot from 2021-04-16 22-46-35](https://user-images.githubusercontent.com/48958412/115099734-d315b480-9f05-11eb-9255-41374b9dbe1d.png)
![Screenshot from 2021-04-16 22-48-45](https://user-images.githubusercontent.com/48958412/115099742-ea54a200-9f05-11eb-850b-8c1cde72d00e.png)

**Version**
0.12.0.3 Linux

**Additional information**
Full crash report: https://pastebin.com/aDzRAU2B

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@aedcf1d.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
