### ISSUE TITLE
Genocide and Xenocide achievements aren't working correctly

### ISSUE THREAD

**Issue by T-Hutch** [Regalis11/Barotrauma#5535]
- [Y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the steam platform, I went through the entire campaign as well as many missions and internally, steam is only showing that I killed 5 monsters and 5 humans.  This is not the case.

**Steps To Reproduce**
Create a mission with 16 bots and mow them down, alternatively, wipe out a colony in campaign.  Human deaths don't increment.  If this is player deaths, the achievement should be reworded.  Kill monsters in the campaign or in missions, notice that the steam counter doesn't increment.

**Version**
Windows 10:  Vanilla no mods or cheats.

**Additional information**
I know that this has already been reported and resolved in the past, but considering I just played for an hour and didn't make any progress, I'd appreciate your looking into it.

**Comment by T-Hutch** [comment]
![barotrauma_sam](https://user-images.githubusercontent.com/10341215/115114449-73e38e80-9f5d-11eb-8eee-615e7355fe51.png)

**Comment by Regalis11** [comment]
Thank you for the report! Turns out the problem was in the way we reported the stats/achievements to Steam. They only got updated when an achievement is unlocked, but not when the kill counters were incremented.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e82f7baecf7d9dbcd8160a4a18eb9c67048ee094

**Comment by T-Hutch** [comment]
Thanks so much for looking at this!
It's really a great game.  I have five friends who play weekly and it would
have been a shame to not 100% it.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
