### ISSUE TITLE
[1300.0.10] Outpost NPC speech bubbles disappear too soon

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5537]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost NPC speech bubbles disappear too soon when you get closer.

Got to a point where it annoys a tad too much. You try to find the way to the questgivers in the snailhouse of an outpost and when you get closer the indicating speech bubble just disappears. 
Too often its no longer clear where to go when the bubble is gone. Above? More right? Do i have to get around a wall - or not?

Expected: Speech bubbles stay long enough so I can path my way to the targets location.
Suggestion:  Blend out speech bubbles only when youre in the same room. Orientational problem solved.

**Comment by Udrakan** [comment]
Same problem here. Sometimes NPC is in a room above/below you and the marker disappears.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/4d1c72113f0ea35270056658fd078008f733ab2a

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
