### ISSUE TITLE
[Feature Request] Allow the wifi component's link to chat feature to be editable during play.

### ISSUE THREAD

**Issue by CommandSergeantMajor** [Regalis11/Barotrauma#5538]
During campaign with my friends, I would wire up detonators so that they open on command of doors or buttons. Then I found the Wifi Component. Very recently, I have been trying to set up Detonators to ReGex and Wifi components to create caht-based activated IEDs. The issue with this is I am unable to edit the Wifi Component to be linked to chat during in game. I have tried with my own sub to make Wifi Component be linked to chat and put it into a storage container, but the change did not persist between the editor and server.

The feature I am asking, if it won't take too much time, is to allow the Link To Chat feature of the Wifi Component to be editable in-game. Thank you for your time.

**Comment by Regalis11** [comment]
As it happens, we had a pull request that implements exactly this (https://github.com/Regalis11/Barotrauma/pull/4531) and I finally got around to merging it now.

In single player the "link to chat" setting is always editable, and in multiplayer it can be enabled/disabled in the server settings (having it always enabled would have too much griefing potential).

Commit in our private repository: https://github.com/Regalis11/Barotrauma-development/commit/c8fcd3278f5a19bf7b53f5409088ad1525f1e747

**Comment by CommandSergeantMajor** [comment]
My apologies that I didn't clear this through the GitHub Discussions, I am a little new to this. While I am going to close this thread as Git will only let me close it, is the private repository something I am supposed to have access as a buyer of the game?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
