### ISSUE TITLE
[1300.0.x] Big diving suit storage power pin missing or it was intended?

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5540]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was the power pin on big diving suit storage not added on purpose or simply forgotten?

**Version**
[Unstable 1300.0.10], Windows 10 pro.

**Comment by Regalis11** [comment]
This is intentional, the large diving suit locker is a legacy item which we generally don't add new features to (= the cabinet doesn't refill tanks so a power input isn't needed).
