### ISSUE TITLE
[ Unstable ] Turret ammo slot placement overlaps charge meter

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5543]
**Unstable v0.1300.0.10**
Railgun turrets ammo indicator slots still wrap around downwards as more slots are added, which means after the first line it overlaps the charge bar and after that will continue off the bottom of the screen.

![image](https://user-images.githubusercontent.com/55356135/115161357-3c630800-a06b-11eb-8081-869f45353e44.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d17246696b50991470e49b7d61397f223336d2e

**Comment by Rokvach** [comment]
Tested, there's no overlapping anymore, ofc having too many will just block your view. But working correctly, closing.
