### ISSUE TITLE
[ Unstable ] Followup: Explosion LevelWallDamage Hit Inconsistencies

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5544]
### Unstable v0.1300.0.10

Issue #5379 with level wall damage partially fixed, however still can reproduce the issue that level wall damage at-range (with no structure damage) does not seem to be applied.

In effect, is is as if the explosion is not doing anything unless it is directly on top of the wall / point of impact.

> Explosion damage now appears to be working as intended, but bizarrely only with projectiles that directly impact the surface.
> 
> Explosion area-of-effect does not seem to produce any damage particles at all despite how large the radius is made, only something about the explosion being directly next to / partially inside the surface seems to allow it to work. Suggesting its something strange happening hitbox related?
> 
> https://user-images.githubusercontent.com/55356135/115093406-342e8f80-9ee8-11eb-8f74-5110452eb071.mp4
> 
> Just to make absolutely sure that was what is happening I modded an item that just explodes instantly upon spawning for using with spawnitem commands. [ " levelexplosiondebugger " [UnstableTestMod2.zip](https://github.com/Regalis11/Barotrauma/files/6328220/UnstableTestMod2.zip) ] Same results.
> 
> https://user-images.githubusercontent.com/55356135/115093443-53c5b800-9ee8-11eb-99e4-af34e6d23a99.mp4
>

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d4744ef6a6ae7e762ca8c8deabda342de2dee2d3

**Comment by Rokvach** [comment]
Tested with the provided mod, the explosion still needs to be directly above it for it to destroy, I'm seeing the exact same behavior as seen on the video.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/36e160867b33ca03986f9852140cae4ac082f5ef

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
