### ISSUE TITLE
[UI] [Legacy] Various problems with legacy installations

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#5545]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Legacy items such as: fabricator, junction box, railgun loaders and periscopes have different issues with UI ranging from oversized wiring box and interact box to missing item's name, also legacy periscopes have an unused wire pin (*power_in*) and one of the legacy periscopes (right facing one) has broken interact animation

#### Here are some examples of the issues mentioned:
* Oversized legacy fabricator's connection panel.
![image](https://user-images.githubusercontent.com/62324831/115163712-60b7f680-a0f6-11eb-81a0-9edc0e74e8bb.png)

* Oversized interaction panel of a legacy junction box.
![image](https://user-images.githubusercontent.com/62324831/115163741-8218e280-a0f6-11eb-8dc5-fdb96474284a.png)
Interaction panel of a modern JB for example.
![image](https://user-images.githubusercontent.com/62324831/115163761-9ceb5700-a0f6-11eb-84ae-a6e6ea623204.png)

* Missing identification text from both legacy railgun loaders.
![image](https://user-images.githubusercontent.com/62324831/115163779-bdb3ac80-a0f6-11eb-9bfb-d8540a2004fb.png)
Modern ones for example.
![image](https://user-images.githubusercontent.com/62324831/115163792-d3c16d00-a0f6-11eb-8241-c99893908617.png)

* Unused *power_in* pin on both legacy periscopes that doesn't exist in modern periscope.
![image](https://user-images.githubusercontent.com/62324831/115163803-eb98f100-a0f6-11eb-9a9e-61e92a11a1dc.png)

* Broken *"use"* animation on right facing legacy periscope.
![image](https://user-images.githubusercontent.com/62324831/115163830-14b98180-a0f7-11eb-98c3-0bedc965ddec.png)

**Steps To Reproduce**
Place any items that were mentioned in a testing environment and interact with them in wiring mode and with character in test mode.

**Version**
Both Stable 0.12.0.3 and Unstable 0.1300.0.10

**Additional information**
All legacy storage containers have the same problem as a legacy railgun loaders (missing item text and an undersized inventory window compared to modern counterparts).
![image](https://user-images.githubusercontent.com/62324831/115165325-0cfadc80-a0f9-11eb-8dad-a352efce77f5.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4d677c2329e31b78c462139c29bcfd29fcf7134f

I decided to leave the "power_in" input in the legacy periscopes: even though it's unnecessary as the periscopes don't require power, removing it could misalign wires in old subs that still use them.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
