### ISSUE TITLE
RangedWeapons Cannot Use OnSecondaryUse

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5547]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
RangedWeapons cannot use OnSecondaryUse. This would be useful for modding for playing sounds when someone starts aiming a weapon, or turning on an attached light when the weapon is aimed.
[UnstableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6335355/UnstableTestMod.zip)

**Steps To Reproduce**
1. Install the attached mod
2. Aim with the `harpoongunsound`
3. Be sad that you do not hear the HONK.

**Version**
v0.12.0.3+ (tested on unstable)

**Additional information**
RangedWeapon does not override
https://github.com/Regalis11/Barotrauma/blob/0697d7fc6412f972e5089fa88b693b486e55fb86/Barotrauma/BarotraumaShared/SharedSource/Items/Components/ItemComponent.cs#L423-L427
Which is called for this block
https://github.com/Regalis11/Barotrauma/blob/0697d7fc6412f972e5089fa88b693b486e55fb86/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs#L2135-L2146
Responsible for sounds and StatusEffects.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d2eb3300fa8062df825fbe67514b1e98b70e8d30

**Comment by Leonidas-ai** [comment]
Had no luck with activating lights or sounds with OnSecondaryUse either inside or outside RangedWeapons. Jlobblet's example mod does not work either.

**Comment by Regalis11** [comment]
Looks like this happened because the weapon isn't set to be character usable (`characterusable="true"`). I changed it so that RangedWeapons are always characterUsable by default - there's not really a reason to be able to set it to false, because ranged weapons don't work unless there's an user aiming them. https://github.com/Regalis11/Barotrauma-development/commit/79bfaf2d2b0a1b0668e3aeb9ec6f55ea9f5084db

**Comment by Rokvach** [comment]
This can be tested in Unstable

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
