### ISSUE TITLE
Inconsistent tags assignment behaviour between characters and items

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5549]
[Modding, Bug?/Unexpected Behaviour]
When you use a statuseffect that's supposed to assign statustags like the one in the clown mask
`<StatusEffect tags="clown" type="OnWearing" target="Character" HideFace="true" duration="0.1" stackable="false" />`
The tag only lasts as long as the duration/statuseffect, before being undetectable by `HasStatusTag` or `HasTag`. 
However, when you target an Item as opposed to a character, the tag lasts forever and is permanently assigned despite setvalue not being set to true. 
I assume this is a bug or unintended since there's no real reason for characters to exclusively have this functionality.
It would be immensely useful if this behaved consistently across items instead of just characters, as temporary tags that only applied so long as a status effect was running would be extremely valuable (especially since there isn't a way to remove permanent tags).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c967cb73aed082c2502b415e42266b6717fbd4ed

> Fixed inconsistent StatusEffect tag behavior between characters and items. A status effect with a duration can have tags, which other effects can use to check whether that effect is active. When the effect targeted an item though, "tags" was also interpreted as the item's "Tags" property, causing the item's tags to permanently change. Now effects with a duration don't try to modify the item tags except if setvalue="true".

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
