### ISSUE TITLE
Barotrauma making servers?

### ISSUE THREAD

**Issue by tayyo1** [Regalis11/Barotrauma#555]
Hello and i try to make serrvers with my friends to play with and it shows 0 players for everyone and it says:

Couldn't Connect to Server
Failed to establish connection - no response from host.

http://prntscr.com/kdcy2l
Help would be nice.
                                                                                                                                                       Thanks!

**Comment by NilanthAnimosus** [comment]
have a read of: #518 and scroll down to a comment I made, it details some things you can try. essentially this is an issue of port forwarding and I left some steps on how to go about it there.

**Comment by Regalis11** [comment]
Most likely a duplicate of #518. If port forwarding does not work, please let me know and I'll reopen this.
