### ISSUE TITLE
 Diving Suit desync after reconnect

### ISSUE THREAD

**Issue by johnthq** [Regalis11/Barotrauma#5552]
Ive been experiencing issues after reconnecting after a brief disconnect. the suit locally will go on it will appear i am wearing it but on the server i am not.. If i was wearing a suit before disconnect if i try and take it off locally on my client the suit will come off but on the friend who is hosting the suit does not get removed. Often causing an instance where they have to remove the suit as i show no visual symptoms no alarm of a dead 02 tank on the suit. I do get the low 02 health status though.

**Comment by Regalis11** [comment]
Potentially related: https://github.com/regalis11/barotrauma/issues/6403

**Comment by Tsunder** [comment]
seems similar to #6125 as well

dropped/missed packets?

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe.

**Comment by johnthq** [comment]
Unreproducible? I basically stopped playing because the problem was fairly
consistent.
