### ISSUE TITLE
[Subeditor] Reload sprite button makes entities vanish for good

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#5559]
Steps to repro:
1. Load a sub
2. Select some item or structure
3. Press "Reload Sprite" button a couple of times
4. Observe that some entities to vanish from the sub. If it doesn't happen, select some other entity and try again.

Seems to be most apparent with the Thalamus category.

Requires reload to recover the entities. Reloading the sub doesn't work, as they seem to be lost in the prefab level.

Note: Back in the days the button did work, so it's broken by some later changes in the editor or the prefab system.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/345b5cfc-0945-4f30-b8a7-4bf934146d4b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1f295fb83d621a858a7f8c508468c24a64c9ed08

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
