### ISSUE TITLE
Crafted welding fuel does nothing.

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#556]
I crafted some welding fuel in the fabricator, and I tried multiple tanks, they would let the tool play the animation, but nothing would get repaired. I replaced the fabricated tank with one spawned with the ship and it worked.

**Comment by thegrb93** [comment]
I was wondering why my welder wasn't doing anything sometimes. Interesting.

**Comment by Regalis11** [comment]
Crafted welding fuel and oxygen _tanks_ are empty, so they're not supposed to work.

**Comment by thegrb93** [comment]
On the client they are shown as full though. How do you fill a fuel tank anyway?
