### ISSUE TITLE
[1300.x] Client host lobby: save&quit does not save and quit

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5560]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While hosting a campaign via client the host can leave to the lobby and sees a "save&quit" option there. This is somewhat misleading, because we expect it to save the current campaign progress (which it doesnt) and quit the server (which it doesnt). 
Seems it rather closes the selected campaign, so you can select a different game mode?

Expected: When I see a save&quit option as host in the lobby I expect it at least to save my progress. Yes, when you leave TO the lobby you get a warning that "unsaved progress" will be lost. It doesnt it make it less misleading.

Also, clarification needed: The game does not explain when it actually saves (on level changes) (what is actually "unsaved progress" in that perspective?). An option to leave and manually save for client hosts is needed.

**Comment by Regalis11** [comment]
Technically the "save & quit" button doesn't save, because the game has already saved when you've come back to the lobby. So you don't really lose any unsaved progress by clicking that button.

**Comment by Regalis11** [comment]
Ah, thanks for the clarification! We have an existing ticket about this issue (https://github.com/Regalis11/Barotrauma/issues/4064), closing this one as a duplicate.
