### ISSUE TITLE
[13.x] Abandoned outpost mission creation weighting needed

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5564]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We currently run a 5-player vanilla unstable campaign. We raided 5 abandoned outposts and each was a "destroy reactor" mission. (Now that we are in the thermal wastes its unlikely that we will see more abandoned outposts, so sadly no chance for varied missions.)

Expected: Weighted mission generation so more variations abandoned outpost missions come into a campaign run. With 4 variations its not unlikely that they all will be the of the same kind.

Suggestion:  Roughly, if there was already 2 of a mission variation prevent the selection of that one again until most variations have been selected twice. (yes, i know theres a weighting formula for this, but lets say maths and me arent friends any longer, hehe)

**Version**
All 13x versions

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/30e04d1fe0c6e7cde9e11fb7c294549f26e44e1d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
