### ISSUE TITLE
Clothing losing color after starting mission

### ISSUE THREAD

**Issue by JobScholten** [Regalis11/Barotrauma#5568]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

We had some clown's clothing colored, but after starting a mission they changed back to their original colours.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Make clowns clothing a different colour, start a mission

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

Build ID: 6582868 (Just after the new abyss update) on Windows

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/434a372a51b4e1cb178da5bd4cdcdd3758e12fec

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
