### ISSUE TITLE
[13.0.11] Mods not getting updated by Steam Workshop

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5570]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Mods in barotrauma stopped being updated after release of `13.0.11`

**Steps To Reproduce**
1. Create mod
2. Upload it on workshop
3. Update mod
or
1.Download New Wrecks For Barotrauma/ EK mods
2. ask panman (me)/EkVideogames to update it
3. watch steam not updating it
**Version**
13.0.11 stable, Windows 10 pro

**Comment by juanjp600** [comment]
First batch of fixes in https://github.com/Regalis11/Barotrauma-development/commit/ff5f09aa23795f71cbbc47619d8f40361c7fcf29, more to come with `feature/modding-refactor`

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
