### ISSUE TITLE
Publish tab of workshop takes long time to load for users with many published items

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5571]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At 10+ published items, the first time opening of the "publish" tab freezes the game for 20+ seconds. 
May also be related to installed mods/workshop items?
I have 53 submarines (including vanilla) totalling 12MB in size in /submarines/ and 120 folders in /mods/ totalling 360 MB

**Steps To Reproduce**
have a multiple mods published, and/or maybe installed (in /mods/ and /submarine/ folders)

**Version**
0.13 release

**Additional information**
Publish tab is used to update mods as well.

**Comment by Rokvach** [comment]
Seems to be loading fairly fast no matter how many published items I add to the list, no issues. Closing.
