### ISSUE TITLE
Submarine preview issues

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5572]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hull Preview:
- [x] shows items that are hidden in game
- [ ] does not get flipped for flipped subs (renegade team in PVP ) 
- [x] "escape" key doesn't close the preview
- [ ] generated preview does not include shuttles
- [ ] parts of subs that are not close to hulls may be past the border of the main area on generation
- [ ] gap boxes obscure doors/hatches
- [x] scaled guns have improper offsets for their barrels

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by JoneKone** [comment]
Can confirm.

**Comment by Regalis11** [comment]
Related: https://github.com/Regalis11/Barotrauma/issues/6149

**Comment by Ek-Videogames** [comment]
A note pertaining to item 6; "gap boxes obscure doors/hatches"
**green gap box does not seem to scale correctly if door or hatch has been resized.**
(as in; the box is always the same size as it would be for a normal door gap)
![image](https://user-images.githubusercontent.com/55356135/129456442-1ae00f06-3d63-4692-9c1d-305a612ad0f0.png)

**Comment by Regalis11** [comment]
Tested https://github.com/Regalis11/Barotrauma-development/pull/3811. All the issues marked as done seem to be addressed, and I'd consider the rest more on the feature request territory than actual bugs. Closing.
