### ISSUE TITLE
Followup: Contentpackage hash mismatch download loop issue

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5574]
### Follow up to closed issue #5154 
Thought to be fixed in commit at https://github.com/Regalis11/Barotrauma-development/commit/331e79385fca6078323908fd2d3b1e2b16001ef3

Still are alot of cases of host with successfully workshop-updated / currently up-to-date content package and clients unable to join because they are prompted to download a content package in an endless loop because of hash mismatching. Seems like in depth situation testing might be needed to determine a reproducible cause, because it seems mostly random among recently updated _(as in the past month or two)_ content packages.

**Comment by Singularia** [comment]
Can confirm, i recently updated my mod ([Beacons Extended)](https://steamcommunity.com/sharedfiles/filedetails/?id=2389600483) then i quit the game and cleaned `mods` folder and `config_player.xml` too. After restart, the game downloaded previous version of my mod.
![image](https://user-images.githubusercontent.com/62324831/115836409-2e462a80-a463-11eb-8433-ab16cdd19c81.png)

Using [3rd party tool](https://steamworkshopdownloader.io/) i downloaded my mod from workshop and it downloaded newest version of it.
![image](https://user-images.githubusercontent.com/62324831/115837142-fc819380-a463-11eb-8df1-0f849729f7bf.png)

**Comment by CurePindal** [comment]
This somewhat urgently needs a fix.

It finally explains the issues we constantly encounter currently with mods (and the amount of modded "incompatible servers" which shouldnt be incompatible). 
Right now we cant continue our campaign with just 3 mods, because of constantly conflicting, different hash issues.

**Comment by Alkanty** [comment]
Yes we experience the same problem with my friends. We cant play anymore ou game because it...

**Comment by CurePindal** [comment]
The fix is probably already done but not yet released?
`1e56256: When publishing a Workshop mod, nuke Steam's cache of it to prevent incorrect reinstalls`

**Comment by juanjp600** [comment]
Could not replicate. The issues described in #5571 appear to more accurately describe the current issues with the mod system
