### ISSUE TITLE
[sub-editor] Entity list becomes empty if you have a cabinet open and change tabs

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5575]
Tested in stable

Repro steps: 
1. Place down a cabinet or load up a sub
2. Open the cabinet
3. While cabinet is open change tabs on the entity list
4. Notice that the entity list becomes empty

Exit out of cabinet and change tab to get it visible again

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/659b8ab1-5a15-456e-9828-7b7894594966)

If you have "All" or "Structure" tabs open when you access the cabinet it does show some items, I also somehow got this to break even further where it showed the entity list this way even when I didn't have a cabinet open, haven't been able to find a way to repro it.
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/24f93c7b-6f5a-4cf7-a5e3-97332f9bbafc)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/00dd776361ee52e5ff029e10964ce914210c6def

**Comment by Rokvach** [comment]
Looks like only the Structure tab now stays empty, feels more like a bug than intentional as other tabs are visible even though the items in them can't be placed in to the cabinet

**Comment by Regalis11** [comment]
Changed in https://github.com/Regalis11/Barotrauma-development/commit/5c7cac337e83f6c65c1f555590a25ce0c6f2285a: now whether a container is selected or not doesn't affect how the list is filtered.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
