### ISSUE TITLE
Oxygenite tanks impossible to place in oxygen tank shelves

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#5576]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Oxygenite tanks are impossible (unlike other tanks) to put in tank shelves, both tall legacy and a small ones.

**Steps To Reproduce**
In sub editor try to place oxygenite tanks in any mentioned shelves

**Version**
0.13.0.11; Stable; Windows 10 x64

**Additional information**
In containers.xml `oxygensource` tag was removed from both shelves. Possibly to fix issue https://github.com/Regalis11/Barotrauma/issues/5091
![image](https://user-images.githubusercontent.com/62324831/115870061-7593e180-a48a-11eb-9486-9f93b0661908.png)

**Comment by Jlobblet** [comment]
I suggest changing this section to read as follows. This allows oxygenite tanks to still be stored in shelves, but will not refill them.
![image](https://user-images.githubusercontent.com/37539527/115873079-6f761480-a43a-11eb-96c4-d0c28c5bf5fe.png)

Alternatively, a new tag could be created for easier mod integration.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ed50dfa905e00155eda8307bcf17bdb9d6d7d98

**Comment by Jlobblet** [comment]
While oxygenite tanks can now be placed in shelves (and shards cannot?), this re-introduces #5091.

**Comment by Rokvach** [comment]
Closing this one as there's a ticket dedicated to the above comment here https://github.com/Regalis11/Barotrauma/issues/5627
