### ISSUE TITLE
Sometimes when transferring items between inventory and container the item drops instead.

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#558]
The effect seems inconsistent but is more common when double clicking to transfer.

**Comment by thegrb93** [comment]
This happens to me a lot too.

**Comment by rico6822** [comment]
Basically:
If you put an item into non-mobile container or crafting device it drops on the ground. Sometimes you cannot even take it as it drops again.

**Comment by thegrb93** [comment]
Reactor rods have this happen a lot as well.

**Comment by thegrb93** [comment]
Still isn't fixed unfortunately

**Comment by thegrb93** [comment]
In addition wiring is completely broken. Attempting to wire causes all wires to become unwired.

**Comment by thegrb93** [comment]
Video:
https://www.dropbox.com/s/9bzjjcfsqda7xuh/2018-09-10%2022-47-33.flv

**Comment by thegrb93** [comment]
Cool. I'll try it out once it's live.

**Comment by Regalis11** [comment]
Another attempt to fix this: 5c06210. I'm pretty confident it's fixed now: we found out that it's easy to reproduce by moving items around in the inventory while inside a sub that's moving fast. Haven't been able to reproduce it anymore after 5c06210.

**Comment by Rokvach** [comment]
I couldn't reproduce this with my previous method of testing the issue, so I can only assume that it is fixed now, closing.
