### ISSUE TITLE
Reverse thrust does not work when swimming

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5580]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The ancient weapon and fire extinguisher do not push the wielder backwards when used underwater, instead they go slightly forwards as if swimming

**Steps To Reproduce**
Put on diving suit
Go swimming
Fire the ancient weapon/fire extinguisher

**Version**
windows, 0.13 stable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/41cb2fcf7323570d873a1dd6635648f2a25b3cb4

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
