### ISSUE TITLE
Submarine editor - Shuttle link is sometimes shuffled with other objects

### ISSUE THREAD

**Issue by Ecchi-Ki-Senpai** [Regalis11/Barotrauma#5581]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The original link of the shuttle to the docking port is sometimes "randomly" switched to another object after saving/loading a submarine.

**Steps To Reproduce**
I have not been able to reproduce it consistently, but it sometimes happen when loading a submarine or saving the submarine. Is it possible items/components are reordered for some kind of optimization and the shuffle happens then?

**Version**
Windows, Stable:

**Additional information**
Nothing game breaking, but a minor inconvenience.
This seems to only affect specifically shuttle links

**Comment by Regalis11** [comment]
No known steps to repro, closing
