### ISSUE TITLE
Text obscured by UI

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5583]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
text obscured by UI
![image](https://user-images.githubusercontent.com/5103517/115926661-385f2d80-a451-11eb-9b7e-40e6ad03ba7b.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
windows 0.13

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/96464bd9998ca020f293cd5eaa0469159d299acd

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
