### ISSUE TITLE
Status monitor bug, precent on linux/windows multiplayer (Only on certain ships)

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#5584]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://steamcommunity.com/sharedfiles/filedetails/?id=2465855238

**Steps To Reproduce**
Open status monitor, and the status screen seems to be very very small. (Kastrul) out of prefab ships seems to have this issue, as well as bunch of custom ships. Some ships work perfectly.

**Version**
v0.13.0.11

**Additional information**
Was confirmed by multiple other players across multiple servers.

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I couldn't find a way to reproduce this using Kastrull: I tried moving between levels in the campaign, left the shuttle behind, and returned to the level the shuttle was left in, but the status monitor was displayed normally during all rounds.

Would it be possible to provide us with a save where this happens?

**Comment by JoneKone** [comment]
I have since verified my data, and all my .sub files where removed/replaced. The current kastrul seems to work fine, maybe it had something to do with an older file, negative on that. I had an older version of the ship loaded and it's status monitor seemed fine on mission/attached to a station.

Ok so take old kastrul start a PVP server and it gives you the result. Even the New Kastrul does the same thing. on PVP.

**Comment by Regalis11** [comment]
Thanks for the extra info, managed to reproduce this now. Seems to only happen in mirrored submarines that have a shuttle. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a38fa8d34f7bde7483a324dde678a79ca57292a9

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
