### ISSUE TITLE
Mission "Praise the Honkmother" always fails

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5586]
**Description**
No matter what, this cargo mission ends in failure.
Players started to report it here: https://discord.com/channels/103209684680323072/157565009726144513/835312867279372328
So I tested it and found out it's indeed the case.

**Steps To Reproduce**
New campaign
triggerevent missionevent_clownoutbreak
(outpost needs to have potential fliers for event trigger to work)
accept mission
try to complete it
it fails, even when it shouldn't

**Version**
Stable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/28df65c3e41aa38b1806ace09fb5e0432ab7365a

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
