### ISSUE TITLE
Cannot repair while on ladder

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#5587]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Impossible to repair
https://streamable.com/dlraes

**Version**
Win 0.13.0.11

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly with minor note on default controls.

its easy for a player to repair on ladders however a player will just fall off said ladder once they let go of their aim key (which shares with the deselect key by default)...and if its high enough not a bad way to get a small amount of damage.

As for AI, I couldn't immediately find a submarine where the repair was too high and pathfinding up the ladder was setup already, I made an AI follow me halfway up the ladder then commanded them to fix leaks - they repaired from the ladder to the wall just fine in that case. I tried a few move times without the following (where they come from an angle its fastest to repair while at the top of the ladder than going all the way down) and they also repaired in that instance just fine.

**Comment by thegrb93** [comment]
>Just realized - "Repair" in this case likely means electrical boxes and such which the streamable link is dead so this issue had virtually no description/context. will test that too.

I think I remember this being the case, but it might've also been a broken hatch.

**Comment by NilanthAnimosus** [comment]
Tested AI repairing broken hatches just in case, and that also seems ok (for the submarines I tested).

**Comment by Regalis11** [comment]
Created another [ticket about using aimable tools while on ladders](https://github.com/Regalis11/Barotrauma/issues/9790), closing this one
