### ISSUE TITLE
Bots spawning like normal in abandoned outpost instead of in sub. Chaos ensues

### ISSUE THREAD

**Issue by Riftbetween** [Regalis11/Barotrauma#5588]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The bots spawn in a abandoned outpost just like a normal outpost. Therefore they have the chance to instantly get mauled or shot by bandits.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Just go into an abandoned outpost. I had one with the hostages.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

v0.13.0.11 I think. The major update with embrace the abyss.  Windows

**Additional information**

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this, the bots seem to spawn in the sub in single player campaign, multiplayer campaign and the single mission mode:
![image](https://user-images.githubusercontent.com/14351070/116064893-1eab2980-a68f-11eb-8fc8-1078a6416abb.png)
![image](https://user-images.githubusercontent.com/14351070/116065627-e1936700-a68f-11eb-8548-11e8111860ab.png)

Which game mode did this happen in? Were you using some kind of a custom sub?
