### ISSUE TITLE
Detaching a component creates ghost of the component that drops to the ground and can't be interacted with

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#559]
I know for sure it happens when using wrench on button.

**Comment by rico6822** [comment]
Does this occur, when it's detaching is over?

Can you pick it up, but it drops on the ground?

**Comment by thegrb93** [comment]
Yeah when the detaching is over. It goes to your inventory, but the ghost one drops to the floor and can't be picked up.
