### ISSUE TITLE
Seizuring physics when laying in bed with diving suit

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#5594]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Spazzes when laying down with diving suit.
https://streamable.com/ql1ew3

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this.

**Comment by thegrb93** [comment]
I saw it happen twice. Maybe sub needs to be moving and in multiplayer.

**Comment by thegrb93** [comment]
It looked like the joints were stuck on something, tangled, or they were colliding with the bed.

**Comment by thegrb93** [comment]
I wonder if he was holding something and doing it on purpose. Not sure how if so

**Comment by thegrb93** [comment]
Look at his legs, they're backwards lol

**Comment by thegrb93** [comment]
Must be some specific way of entering the bed

**Comment by thegrb93** [comment]
This never happened to me so maybe it's exclusive to other players. Seeing another player enter the bed a certain way.
