### ISSUE TITLE
Beacon Diving Suit has durability.

### ISSUE THREAD

**Issue by TheSanctifier** [Regalis11/Barotrauma#5595]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you go to a vanilla beacon station the dive suit there is occasionally depicted with a durability bar around the 66% range.

**Steps To Reproduce**
Go to a beacon station, preferably with the difficulty at least higher than 20% since this will cause more items to be damaged at the location. Than observe the diving suit locker near the entrance and notice that the suit will occasionally be damaged.   

**Version**
v0.13.0.11 Windows
![Beacon Suit Bug](https://user-images.githubusercontent.com/37763748/115952611-446aee00-a52a-11eb-9666-63a88bf6d4ee.png)

**Additional information**
Issue doesn't appear at wrecks or anywhere else, only beacons.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c4ad992313a31a90cbd96423955a5ad4baa7063

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
