### ISSUE TITLE
[0.13.0.11] Traitor mission "Easter Bunny" Bugged

### ISSUE THREAD

**Issue by Sfreck** [Regalis11/Barotrauma#5598]
- [X] I have searched the issue tracker to check if the issue has already been reported. *Note bug seems to have resurfaced from last report by #4838 on 21 Jan 2021.

**Description**
The traitor mission immediately fails once the egg hatches the baby mudraptor.

**Steps To Reproduce**
Complete the steps of feeding saline to the egg leading up to the hatching of the baby mudraptor. Once hatched the traitor mission will immediately fail.

Encountered in public matches and tested in private hosts of traitor missions.

**Version**
v0.13.0.11. (Windows).

**Additional information**
Issue was reported previously by #4838 on 21 Jan 2021 and was appeared to be marked to be fixed. However, the issue seems to have resurfaced in recent versions.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bccf04e1a34d09bcb5b6d94a4c94afaf0d03c947

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
