### ISSUE TITLE
Exception: One or more errors occurred. (Cannot access a closed pipe.) (System.AggregateException)

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#5599]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Server crashed and disconnected everybody, left me lingering (client hosted server)

**Steps To Reproduce**
Banned a guy. dunno if it has any meaning it crashed right after that.

**Version**
0.13.0.11 linux

**Additional information**
https://p.ip.fi/crWu  // Crash report client
https://p.ip.fi/jwWJ // Crash report server

The logs of the whole session.

[Happy Traitor_2021-04-24_1624.txt](https://github.com/Regalis11/Barotrauma/files/6369690/Happy.Traitor_2021-04-24_1624.txt)
[Happy Traitor_2021-04-24_1615 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369691/Happy.Traitor_2021-04-24_1615.2.txt)
[Happy Traitor_2021-04-24_1615.txt](https://github.com/Regalis11/Barotrauma/files/6369692/Happy.Traitor_2021-04-24_1615.txt)
[Happy Traitor_2021-04-24_1613.txt](https://github.com/Regalis11/Barotrauma/files/6369693/Happy.Traitor_2021-04-24_1613.txt)
[Happy Traitor_2021-04-24_1606 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369694/Happy.Traitor_2021-04-24_1606.2.txt)
[Happy Traitor_2021-04-24_1606.txt](https://github.com/Regalis11/Barotrauma/files/6369695/Happy.Traitor_2021-04-24_1606.txt)
[Happy Traitor_2021-04-24_1602.txt](https://github.com/Regalis11/Barotrauma/files/6369696/Happy.Traitor_2021-04-24_1602.txt)
[Happy Traitor_2021-04-24_1555 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369697/Happy.Traitor_2021-04-24_1555.2.txt)
[Happy Traitor_2021-04-24_1555.txt](https://github.com/Regalis11/Barotrauma/files/6369698/Happy.Traitor_2021-04-24_1555.txt)
[Happy Traitor_2021-04-24_1548.txt](https://github.com/Regalis11/Barotrauma/files/6369699/Happy.Traitor_2021-04-24_1548.txt)
[Happy Traitor_2021-04-24_1547.txt](https://github.com/Regalis11/Barotrauma/files/6369700/Happy.Traitor_2021-04-24_1547.txt)
[Happy Traitor_2021-04-24_1539 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369701/Happy.Traitor_2021-04-24_1539.2.txt)
[Happy Traitor_2021-04-24_1539.txt](https://github.com/Regalis11/Barotrauma/files/6369702/Happy.Traitor_2021-04-24_1539.txt)
[Happy Traitor_2021-04-24_1530 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369703/Happy.Traitor_2021-04-24_1530.2.txt)
[Happy Traitor_2021-04-24_1530.txt](https://github.com/Regalis11/Barotrauma/files/6369704/Happy.Traitor_2021-04-24_1530.txt)
[Happy Traitor_2021-04-24_1527.txt](https://github.com/Regalis11/Barotrauma/files/6369706/Happy.Traitor_2021-04-24_1527.txt)
[Happy Traitor_2021-04-24_1512.txt](https://github.com/Regalis11/Barotrauma/files/6369707/Happy.Traitor_2021-04-24_1512.txt)
[Happy Traitor_2021-04-24_1511 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369709/Happy.Traitor_2021-04-24_1511.2.txt)
[Happy Traitor_2021-04-24_1511.txt](https://github.com/Regalis11/Barotrauma/files/6369710/Happy.Traitor_2021-04-24_1511.txt)
[Happy Traitor_2021-04-24_1458 (3).txt](https://github.com/Regalis11/Barotrauma/files/6369711/Happy.Traitor_2021-04-24_1458.3.txt)
[Happy Traitor_2021-04-24_1458 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369712/Happy.Traitor_2021-04-24_1458.2.txt)
[Happy Traitor_2021-04-24_1458.txt](https://github.com/Regalis11/Barotrauma/files/6369713/Happy.Traitor_2021-04-24_1458.txt)
[Happy Traitor_2021-04-24_1442 (2).txt](https://github.com/Regalis11/Barotrauma/files/6369714/Happy.Traitor_2021-04-24_1442.2.txt)
[Happy Traitor_2021-04-24_1442.txt](https://github.com/Regalis11/Barotrauma/files/6369715/Happy.Traitor_2021-04-24_1442.txt)
[Happy Traitor_2021-04-24_1424.txt](https://github.com/Regalis11/Barotrauma/files/6369716/Happy.Traitor_2021-04-24_1424.txt)

**Comment by Calyxman** [comment]
His friend here, what he's saying is 100% true 
He banned a griefer then mysteriously crashed.

**Comment by JoneKone** [comment]
Also =D I think I banned the wrong guy.

**Comment by Regalis11** [comment]
Addressed the server-side crash in https://github.com/Regalis11/Barotrauma-development/commit/60b53c65e1d073a448194d849c76f8c855b4c7a1: I wasn't sure how to repro this or what exactly caused the nullref exception, but I spotted two potential causes and fixed those.

The client-side crash is still unaddressed though, we should make the client disconnect gracefully and return to the main menu with the "server crashed" error message when this happens.
