### ISSUE TITLE
Chatting doesn't disable letter-bound keybinds

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#56]
For example, if you bound your chat key to T, every time you pressed T you would switch chat off, making it impossible to use it as a keybind.
Moreover, in Debug mode, when you chat you will "accidentaly" press the i j k l keys and fling the sub all over the place.

**Comment by Regalis11** [comment]
I see what you mean, but how would you deselect the chatbox if the chat hotkey was disabled when writing a chat message? The sub movement controls should definitely be disabled when chatting though.

**Comment by Crystalwarrior** [comment]
Usually games simply deselect it if you press enter even if there's no message, though iirc the game let's

**Comment by Crystalwarrior** [comment]
Fucking phone, anyway the game lets you send blank messages. This might have to be fixed to simply deselect.

**Comment by Regalis11** [comment]
Closed by #79
