### ISSUE TITLE
Barotrauma Thalamus Bugged Submarine Along X Axis

### ISSUE THREAD

**Issue by AFlockofDogs** [Regalis11/Barotrauma#5600]
- [x] I have searched the issue tracker to check if the issue has already been reported.

I removed a fleshgun from the submarine just as it was attaching, and somehow this triggered my submarine to begin flying along the X axis. I travelled at around 50 km/h, which is twice as fast as the top speed the sub can move on its own, about 600 m away from the thalamus, crashing into the bare rock near the next base, becoming glued to it just as I was with the thalamus.

Suspecting that the thalamus was still to blame, I armed to go kill it, swam the 600 m, killed it, and came back to find that it DID release the sub. Somehow the game just glued the submarine to the wrong place!

I am not sure how it can be reproduced, but I think it had to do with killing multiple fleshgun shots in quick succession, one of which was just getting attached. 

I am using the current version of the game on Windows.

**Comment by Regalis11** [comment]
No known steps to reproduce, closing
