### ISSUE TITLE
Can't switch between radio / local voice chat in certain dialogue windows.

### ISSUE THREAD

**Issue by lewis-conroy** [Regalis11/Barotrauma#5601]
[✔] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're in certain dialogues - namely the shop and submarine upgrade windows - you can't switch between local and radio voice transmit modes.

**Steps To Reproduce**
Set your voice chat settings so that it's local chat by default, and voice activity mode.
Go to the trader at an outpost and open the trade window.
Hold the button you have bound to switch to radio mode.
It doesn't switch.

**Version**
v0.13.0.11 releaseWindows, branch release, revision 840b932557
Windows 10

**Additional information**
It's not a huge issue, but it's quite frustrating when discussing what to buy / upgrade etc. with crewmates.

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this (except by selecting one of the textboxes in the interface, which is supposed to disable the hotkey, as typing into the box takes precedence over the hotkey).

**Comment by lewis-conroy** [comment]
Is it possible that the my push-to-talk key being Left Alt is having an impact? The two windows I was experiencing this issue in were the Shop and Ship Upgrades menus. It is also possible that the issue was fixed thanks to some other change since I submitted the bug. Thanks
De : Joonas ***@***.***>
Envoyé le :vendredi 9 juillet 2021 10:17
À : ***@***.***>
Cc : Lewis ***@***.***>; ***@***.***>
Objet :Re: [Regalis11/Barotrauma] Can't switch between radio / local voice chat in certain dialogue windows. (#5601)


I'm afraid I could not reproduce this (except by selecting one of the textboxes in the interface, which is supposed to disable the hotkey, as typing into the box takes precedence over the hotkey).
