### ISSUE TITLE
Railgun payload disappears on impact

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5603]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Railguns loaded with explosives (uex/c4/frag nades etc) do not detonate

**Steps To Reproduce**
place explosive in railgun
fire railgun

**Version**
windows 0.13.0.11 release

**Additional information**

**Comment by Tsunder** [comment]
revision:
all items inside railguns just disappear entirely on impact.

**Comment by Tsunder** [comment]
probably affects all items that remove on impact (nuclear shells)?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/edd4d44ddf2c11929d6820891ca7ab2cb7e3e94c

**Comment by Rokvach** [comment]
Tested, didn't spot any issues. Closing.
