### ISSUE TITLE
Sonar beacon does not disaplay in test mode

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5604]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sonar beacons do not appear in sonar menus (nav terminal etc) in test mode

**Steps To Reproduce**
enter test mode
turn a sonar beacon on
view sonar

**Version**
0.13 release

**Additional information**
sonar beacon being a tiny white cross makes it also blend in a bit with any other grey/white/bright stuff in sonar, including sonar pings and walls. the previous red box was really visible.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/080024e5b986ed21560f90e64903a4060037d31b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
