### ISSUE TITLE
Followup :  Tiny gap of high pressure with vertical docking port and dynamic hulls

### ISSUE THREAD

**Issue by Krisscut** [Regalis11/Barotrauma#5607]
Hi,

This is a followup issue for this one that has been closed but is still reproduceable on latest stable with the same submarine as previously provided.
https://github.com/Regalis11/Barotrauma/issues/5281

Now also happening on stable V0.13.0.11
Main issue is that it prevents the bots from going on the other side of the gap of high pressure. (ragdoll is an inconvenience but not critical)

**Comment by Regalis11** [comment]
Thank you for the report! I reopened the old ticket since it has a bit more information than this
