### ISSUE TITLE
Not bugs but very much interfere with the gameplay.

### ISSUE THREAD

**Issue by Kufrum** [Regalis11/Barotrauma#5610]
- [x] I have searched the issue tracker to check if the issue has already been reported.

These are not bugs, but they interfere with the game. Belts can be folded into the container into which you can also fold things. 120 slots per container (20 standart). In the editor, I faced the problem of connecting a large number of detectors to one alarm. They work unpredictably, although I have tried different methods, just like on standard boats, they do not help, only connecting two or more alarms solves the problem. AI sometimes goes into the fire to repair devices, but at the same time ignore the fire and die.

Ver. v0.13.0.11 Windows 10

**Comment by Regalis11** [comment]
>I faced the problem of connecting a large number of detectors to one alarm. They work unpredictably, although I have tried different methods, just like on standard boats, they do not help, only connecting two or more alarms solves the problem

The problem with this is that the detectors are all sending signals to the alarm simultaneously, and the alarm "doesn't know" which of them it should react to. You might want to use logic components like AND/OR to determine how you want the circuit to work: e.g. if you want the alarm to trigger when any of the detectors trigger, you could OR all the detector outputs together.
