### ISSUE TITLE
Items placed on outside of sub can not be detached

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5611]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
items placed outside of the sub that normally can be detached (for example a motion detector via a wrench).

**Steps To Reproduce**
1. place a motion detector a the fin outside of the sub
2. no option to detach appears, and pressing E on it with a wrench does nothing

**Version**
windows 0.13.0.11

**Additional information**
they can be rewired though

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9e5e2176f02cbcf3ce1a64e28db1b3a83b43b53

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
