### ISSUE TITLE
Overriding Character Ragdolls and Animations Doesn't Work

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5612]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you override an existing character and set the `folder` attribute on the `ragdolls` or `animations` element, it doesn't work.
[crashreport (27).log](https://github.com/Regalis11/Barotrauma/files/6376368/crashreport.27.log)

**Steps To Reproduce**
1. Install this test mod: [StableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6376366/StableTestMod.zip)
2. Spawn a hammerhead.
3. Observe.

**Version**
0.13.0.11+

**Additional information**
Some quick investigation found the cause:
https://github.com/Regalis11/Barotrauma/blob/841d755394c6da98ec6de69e79c6ef65897fa07b/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs#L108

https://github.com/Regalis11/Barotrauma/blob/841d755394c6da98ec6de69e79c6ef65897fa07b/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Animation/AnimationParams.cs#L134

In the meantime, here's a horrible workaround:
```xml
<Override>
  <Character>
    ...
  </Character>
  <ragdolls folder=""/>
</Override>
```
Make sure the `ragdolls` and `animations` come after the `Character` - the order matters.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/65c4a5bb224563da3ce97a0550e788456dba38eb

**Comment by Rokvach** [comment]
Tested, I didn't spot any issues. Seems to be working correctly, closing.
