### ISSUE TITLE
Make ice shards in caves destructible

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5613]
Atm the only way to destroy the shards is to swim against them, should make it possible to destroy them with weapons/explosives

**Comment by Jlobblet** [comment]
The plasma cutter should also be able to destroy them.

**Comment by JoneKone** [comment]
Plasma cuter isn't really feasible in real world to cut ice, all ice should be cut with mechanical force (explosives) i suggest remove plasma cutting from all ice. And go straight to explosives only.

**Comment by Tsunder** [comment]
should be really quick to destroy, like <3s, i think, to not be severely slowing down on flow / reasonable for something that "explodes/breaks" on collision with a diving suit

**Comment by Reed0506** [comment]
theres also the green exploding things that are like the crystals except they do deep tissue damage

**Comment by JoneKone** [comment]
> should be really quick to destroy, like <3s, i think, to not be severely slowing down on flow / reasonable for something that "explodes/breaks" on collision with a diving suit

You can use multiple grenades. Or plant 1 C-4

**Comment by Reed0506** [comment]
having to use multiple grenades or a c-4 for every single crystal you want to get rid of would be awful, and make just bumping them more cost-effective than destroying them.

**Comment by JoneKone** [comment]
> having to use multiple grenades or a c-4 for every single crystal you want to get rid of would be awful, and make just bumping them more cost-effective than destroying them.

Oh sorry my suggestion may have been obscured, a crystal ice structure would die with mechanical force grenades/weapons/harpoons but not body/plasma cutting. The ice in caves and free floating ice would take minimum to zero damage from ammunition based weapons and instead should only be destroy able by coil gun/rail gun/c-4/grenades and remove plasma cutting damage.

**Comment by Krzeszny** [comment]
Since they're brittle enough to destroy them by touch, any type of damage except for burn damage should destroy them instantly.
This includes knives, batons, bullets, etc. 
Maybe even hitting them with the scooter if that's possible.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/f21404ecae181c9cfa068ed0f51f6473c3e06bb4

**Comment by Rokvach** [comment]
Should harpoon guns work on them too? 

Some ice shards are harder to hit than others

Video: https://www.youtube.com/watch?v=idtdI9ONBQQ

**Comment by Regalis11** [comment]
Addressed both in https://github.com/Regalis11/Barotrauma-development/commit/b8699fccc398665d40df27d2f39a0acb1bfd6281.
I also noticed the crystals in crystal caves didn't disappear when shot (fixed that now).

**Comment by Rokvach** [comment]
Raycast projectile weapons seems to sometimes hit nothing, looks as if you need to be inside some "area" before you can hit the ice shards, this doesn't happen with harpoons. 

https://www.youtube.com/watch?v=Er8at3JKpQA

**Comment by Rokvach** [comment]
Sometimes it also appears that the bullet got to the ice shard but it doesn't actually hit it

**Comment by Rokvach** [comment]
There's still some shards I can't hit, seems to depend on the angle I shoot at them, fairly noticeable if you go through a cave and just shoot at any ice shards you come across with a SMG or other raycast projectile weapon

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
