### ISSUE TITLE
Game crashes if a non-human humanoid tries wearing an innerclothes wearable if said wearable was being worn by a human at round start.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#5615]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every single humanoid that isn't a human or a humanhusk, modded and non modded, will crash the game when trying to wear an item that goes in the "innerclothes" slot IF said item was being worn by a human when the current round started.

Can be tested by giving the normal husk character this inventory 
`<inventory arrowslot="9" slots="Card, Headset, Head, InnerClothes, OuterClothes, LeftHand, RightHand, Bag, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any"/>`, controlling it and attempting to wear any clothes that go in the innerclothes slot that were worn by a human when the round started.

**Version**
v0.13.3.11

**Additional information**
Crash log: [crashreport.log](https://github.com/Regalis11/Barotrauma/files/6385006/crashreport.146.log)
Video: https://youtu.be/8f-Eai5UmwI

**Comment by Regalis11** [comment]
I couldn't get this to crash the game, although it does cause the following console errors: 
![image](https://user-images.githubusercontent.com/14351070/116225041-06541100-a75a-11eb-8891-c147fb7d9197.png)

Would it be possible to send us the crash report?

**Comment by Regalis11** [comment]
Fixed the above console errors in https://github.com/Regalis11/Barotrauma-development/commit/3898de13b40bbf1ece4a12363a6d0666e5689345

**Comment by Emanthealmighty** [comment]
Crash log: [crashreport.log](https://github.com/Regalis11/Barotrauma/files/6385006/crashreport.146.log)
Video: https://youtu.be/8f-Eai5UmwI

**Comment by Emanthealmighty** [comment]
Found new important information regarding this issue.
Not fixed as of version V0.1400.0.0 (Unstable).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67aa4a0a43328d3d4d15071888f9218371fb35cb

**Comment by Rokvach** [comment]
This can be tested in Unstable

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
