### ISSUE TITLE
minor wall overlap issue in orca

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5616]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
inner walls in the top deck of orca appear "over" the shell

![image](https://user-images.githubusercontent.com/5103517/116105491-6033d880-a67f-11eb-93c7-0acfa8222ec3.png)
![image](https://user-images.githubusercontent.com/5103517/116105518-65912300-a67f-11eb-936e-76b2465891a5.png)

**Steps To Reproduce**
0.13.0.11 release windows

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d2875abd44c60002c50a2086bc6bc09ebdf9672

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
