### ISSUE TITLE
Prevent detaching items outside hulls

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#562]
This is how we can fix issues with unwired railguns outside submarine and other stuff:

You can rewire outside submarine's hulls, but you cannot detach what already have been put in there from level editor. If a wire is left click outside of submarine's hull, when equipped it won't be attached to the background outside of submarine, but when it's connected to something outside of it, it will actually reveal itself connected to it.

**Comment by Regalis11** [comment]
Isn't this how wiring works already? Preventing players from detaching items outside the sub is something that should be added though.

**Comment by rico6822** [comment]
Alright, I didn't knew you can rewire outside submarine, but I think detaching must be disabled, since you cannot place components outside of submarine
