### ISSUE TITLE
[13.0.11] Finished Campaign: New map keeps previous path

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5623]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After you finished the campaign and the save gets reset to the start of the map the previous path is still visible on the campaign map.

Expected: Previous path not visible.
Honestly expected: A fresh map with a new seed.

**Additional information**
![20210426231304_1](https://user-images.githubusercontent.com/3466193/116151908-8724f580-a6e5-11eb-997c-64713d0f7a76.jpg)

**Comment by LePiromano** [comment]
i'd keep that, maybe you want to choose new paths and options this time

**Comment by CurePindal** [comment]
I wouldnt keep that, unless I get a different color for my new path.
But even then it becomes a mess on the 2nd, and definatly on the 3rd run.
So rather "no thx", hehe.

**Comment by Regalis11** [comment]
> i'd keep that, maybe you want to choose new paths and options this time

I agree, imo this is a good thing because you can take a different path on the successive runs

**Comment by CurePindal** [comment]
Wow, thats disappointing.
