### ISSUE TITLE
Sufforin kills endworm

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5624]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Endworm can be killed with one (1) dose of sufforin

**Steps To Reproduce**
[H]eal the endw-- shoot a syringe of sufforin into the endworm, wait for poison to kick in.

**Version**
0.13.0.11 release windows

**Additional information**
lol

**Comment by LePiromano** [comment]
and charybdis, and every creature in the game.

**Comment by Reed0506** [comment]
also doesnt award the achievement if you do it this way from what i can tell

would be cool if sufforin would be effective in higher doses rather than not at all
and of course the syringe gun is for losers, so that would make sufforin ineffective

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d4c1883e3a57e170c1c3cc19aab26b306b6cc87f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
