### ISSUE TITLE
[13.0.11] Purchases stuck in the floor

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5626]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every other time purchased items get stuck in or under the floor. The pic below is a planter in a Kastrull. We also had this happen with a crate in a Humpback.

**Steps To Reproduce**
Happens sometimes after purchases are delievered.
No idea how to reproduce.

**Version**
13.0.11 Win10, MP, vanilla

**Additional information**
![20210427000042_1](https://user-images.githubusercontent.com/3466193/116160411-42538b80-a6f2-11eb-993c-240ae4635587.jpg)

**Comment by Regalis11** [comment]
Gave this a quick test with Dugong and Kastrull, but couldn't get it to happen yet. If anyone has a save file where this occurs, please let me know!
