### ISSUE TITLE
Oxygen shelves can refill oxygenite tanks

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5627]
_(Under the impression that this was the original reason oxygenite tanks were not allowed to be placed into shelves.)_
A powered oxygen shelf can refill oxygenite tanks placed in them - but this behavior is not happening with welding fuel tanks which also became placable. So this seems like an easy fix if you just specify more strict tag requirements, or an entirely new item tag like "refillableoxygensource" or something.

**Comment by Jlobblet** [comment]
See also #5091

**Comment by Jlobblet** [comment]
Another option would be to only refill oxygen tanks but I think this is less preferable to making a new tag - a tag for refilling oxygen allows easily for modded tanks to specify whether they can be refilled or not, instead of requiring the mod to override tank shelves and the oxygen generator.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4dc0d1bc9849fa45d546d7df383075467b29f640

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
