### ISSUE TITLE
[Unstable 0.1300.1.11] Kastrull slams to the roof of the level at the start of a round, doesn't maintain position like other subs

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5628]
So far only noticed this with Kastrull, it slammed to the roof so fast that it caused some heavy leaks in the sub

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e95031003f2ace39fcd0db536788fab3e2b05288

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore. Working correctly, closing.
