### ISSUE TITLE
Diving suits disappear client-side when attemping to retrieve them from wrecks in multiplayer.

### ISSUE THREAD

**Issue by Reed0506** [Regalis11/Barotrauma#5634]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a multiplayer server, attempting to bring a dive suit into your sub via spam-click will cause it to disappear client-side once you reach your ship's airlock.
**Steps To Reproduce**
Join another player's multiplayer server (havent tested if it happens while hosting or in singleplayer). Find wreck (or anything else really) with diving suits. Attempt to spam-click a diving suit out of a wreck into your own sub. Diving suit should disappear once it gets inside of the sub. Diving suit can be seen and interacted by other players and once they put it down you can interact with it again.
**Version**
v0.13.0.11 Window 10
**Additional information**
This probably would not be an issue if we could hold diving suits in our hands, but thats just my opinion.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4cfa6905914d54594d866d30ae8f5d5390549f01

>This probably would not be an issue if we could hold diving suits in our hands, but thats just my opinion.
This is also coming up, we implemented it just recently but unfortunately it didn't make it in time for the latest update.

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
