### ISSUE TITLE
Game crash when switching to another character in campaign

### ISSUE THREAD

**Issue by Jatimatik** [Regalis11/Barotrauma#5636]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While playing the campaign in single player the game suddenly crashed. I was exploring an alien ruin with the captain, and the game crashed when I switched to the engineer on the ship.

**Version**
v0.13.0.11 Windows 10 Home

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6386934/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c486db90ecbbbe96c0675ed859df93e2de2e991

Seems to be pretty simple to repro: just teleport a bot to a non-flooded room in the ruins.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
