### ISSUE TITLE
Incorrectly Formatted Game Version in Content Package Crashes Silently

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5637]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempting to load the game with one or more content packages with an incorrectly formated `gameversion` will cause the game to crash with no crash report.

**Steps To Reproduce**
1. Install this mod [StableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6390570/StableTestMod.zip)
2. Try to boot the game
3. Observe

**Version**
0.13.0.11+, Windows 10

**Additional information**
Crash is caused from here (found by running with debugger attached) https://github.com/Regalis11/Barotrauma/blob/841d755394c6da98ec6de69e79c6ef65897fa07b/Barotrauma/BarotraumaShared/SharedSource/ContentPackage.cs#L279

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b78100e4c20a708da9c86fec8886b6d46ea646d

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, working correctly. Closing.
