### ISSUE TITLE
You Can See Health Bars Through Walls

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5639]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When there are monsters outside the sub - most noticeably below it - you can see their health bars through the walls.

(I'll just put some keywords here to help searchability health bar healthbar health bars healthbars)

**Steps To Reproduce**
1. Go to the bottom floor of a sub.
2. Spawn characters (e.g. crawlers) outside.
3. Damage it slightly.
3. Observe.
![image](https://user-images.githubusercontent.com/37539527/116394068-5b575c00-a81a-11eb-93f5-8a8383d99ade.png)

**Version**
0.13.0.11+

**Comment by HeatedWafflez** [comment]
I do wish this would be looked into. It's been in the game for awhile and can completely kill stealth for combat missions.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2aabae834e0a4cf491d81ec5846dadc1c307f488

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
