### ISSUE TITLE
[0.13.0.11] Dragging a stack of seeds onto a planter box consumes the entire stack

### ISSUE THREAD

**Issue by Sfreck** [Regalis11/Barotrauma#5640]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dragging a stack of seeds of any type (e.g. a stack of 8 tobacco seeds) onto a planter box consumes the entire stack (as opposed to consuming only one seed). 

**Steps To Reproduce**
Put down a planter box and drag from your inventory a stack of seeds onto it. The entire stack will sadly be consumed. 

**Version**
[0.13.0.11] Windows

**Additional information**
Encountered in public matches and tested in private hosts.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e94460198429924d56b32c0b302f84c6b897603c

**Comment by Rokvach** [comment]
Tested, no issues, closing.
