### ISSUE TITLE
[13.3.11] continue Finished campaign: no more missions offered

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5642]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We finished the campaign for the first time. Continuing the save gave us available missions at the first station, but then no more missions are offered at other stations.

**Steps To Reproduce**
Campaign finished
Save loaded
First outpost offered missions. From there on no more missions are offered

**Version**
13.3.11, MP, client hosted, EK armory/utilities, Beacons extended, wrecks extended

**Additional information**
Campaign save:
[March21modded.zip](https://github.com/Regalis11/Barotrauma/files/6394775/March21modded.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d227b9f57cb9d11c4b56829b21bbf334e02c4f26

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
