### ISSUE TITLE
[13.3.11] Mod updates still messed up.

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5644]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Updating mods still does not work.
ITA got updated today and I got the info that it was updated on launch. Checking the files in /mods it was still the outdated, 12.x installation.
Another update a few hours later, again info that it was updated, still outdated old files installed.

Also today we continued our MP campaign with Ek armory/utilities. Last update of EK Utilities was last thursday and my buddies havent used it since last wednesday. But somehow the hosts false updated version was the issue. Unsub, delete folders, resub - same issue.
Had to use a workshopdownloader to fix the issue.

**Version**
13.3.11 SP, tested with Into the Abyss mod. (old version was still subscribed and installed from before) and EK Utilities earlier

**Comment by Rokvach** [comment]
I've been seeing a similar thing happening, only workaround for it is to use the reinstall button in the steam workshop menu in-game, this way it does a fresh install of the mod and gets the update. But the automatic update that happens at the start of the game doesn't seem to actually update the mod even though it says it does.

**Comment by Rokvach** [comment]
I haven't noticed any issues in mod updating in the modding refactor, tested very extensively.
