### ISSUE TITLE
Bots can only pick from 6 traits (Even if more are modded in)

### ISSUE THREAD

**Issue by AstraAegis** [Regalis11/Barotrauma#5646]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've tested this for quite awhile, spawning in new AI, having randomly named traits to see if it's a problem with certain named traits, but after alot of testing, I can assure you that bots can only select from 6 traits in a trait-pool. 6 Traits is the Vanilla number currently, but it would really be great for modding if more could be selected from. It also helps if vanilla conversations are updated for more than 6 traits.

**Steps To Reproduce**
1. Add more traits, through NPCConversations_English, and then through EnglishVanilla.
2. Spawn in bots in console with "spawn human cursor"
3. Spawn in a very large amount
4. Press tab and check all their traits, and you'll find only 6 traits actually show up.

**Version**
I've seen this happen before 0.13.0.11 came out, and now after it's release, it's still happening. I run Barotrauma on Windows.

**Additional information**
I think it's related to position on the trait tree? Or editing the positions will reroll traits? Cause I've had more than 6 traits on a crew before by just moving the positions on traits in the files, but it will still only have 6 traits max for hire, even after messing with positions.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4bdfe11dc2adc819f54e1dd3875ed22d5b39ba03

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7615624b94121f23eb0b15cea3f525259a105c0d

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, working correctly, closing.
