### ISSUE TITLE
Diving Suits Do Not Refill Items With refillableoxygensource Tag

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5647]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Diving suits only refill `oxygentank`, not any item with the `refillableoxygensource` tag.
![image](https://user-images.githubusercontent.com/37539527/116550619-e73ab800-a8ee-11eb-90ec-b6bb83ef47eb.png)

**Steps To Reproduce**
1. Install this mod: [StableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6398650/StableTestMod.zip).
2. Load "Azimuth Test" in the sub editor.
3. Observe the condition of the oxygen tank in the rightmost locker (blue).

**Version**
0.13.3.11+

**Additional information**
Simply update the `RequiredItem`:
```xml
<!-- Refill oxygen when the suit is contained. -->
<StatusEffect type="OnContained" target="Contained" Condition="1.0">
  <Conditional Voltage="gt 0.01" targetcontainer="true" targetgrandparent="true" targetitemcomponent="Powered" />
  <RequiredItem items="refillableoxygensource" type="Contained" excludebroken="false" />
</StatusEffect>
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/777e478227e4393e2a40cf993f9065c68f75ee2e

**Comment by Jlobblet** [comment]
Just checked and the oxygen generators need updating, too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d153f3c5663a580618b7d124df5df8d8f0032d6c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by Krzeszny** [comment]
> Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d153f3c5663a580618b7d124df5df8d8f0032d6c

> Tested, no issues. Closing.

Diving suit uses `refillableoxygensource` but Abyss and Combat suits use `oxygentank` in RequiredItems.
