### ISSUE TITLE
[13.3.11] Thalamus walls becomes invisible and not dissappering when no thalamus present

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5648]
- [x] I have searched the issue tracker to check if the issue has already been reported. (Yes, it was reported long time ago)

**Description**
You cant get in wreck in places where thalamus wall supposed to be even if thalamus not present! (collision of wall is left while no wall is present)

**Steps To Reproduce**
1. create wreck or use already existing one (in my case dugong)
2. place thalamus wall (not decorative one)
3. quickstart on any sub
4. spawnsub Dugong_Test_Wrecked false
5. try to enter through holes where thalamus wall was placed

**Version**
13.3.11 unstable, windows 10 pro

**Additional information**
for easier testing, i will provide wreck that got this problem
[Dugong_Test_Wrecked.zip](https://github.com/Regalis11/Barotrauma/files/6399361/Dugong_Test_Wrecked.zip)
also screenshots
![image](https://user-images.githubusercontent.com/42521948/116566867-c5056200-a90f-11eb-9bd9-1d1773554926.png)
![image](https://user-images.githubusercontent.com/42521948/116566884-c9ca1600-a90f-11eb-9cfa-0152c73166e3.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/93dd33e09db7ce99e53d15936488317cee33f308
