### ISSUE TITLE
Bots will handcuff you before you are fully stunned

### ISSUE THREAD

**Issue by TurpinHero** [Regalis11/Barotrauma#5649]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots try to arrest you the will sometimes handcuff you after they hit you once with a stun stick.

**Steps To Reproduce**
1. Deal enough damage to a bot to get the guards to try to arrest you
2. Most of the time the will only hit you once or twice and then handcuff you before your full stunned

**Version**
v0.13.3.11 Windows 10

**Additional information**
https://user-images.githubusercontent.com/64657392/116581022-8bb1ff80-a8d9-11eb-8315-b3ef8c7c4965.mp4

**Comment by itchyOwl** [comment]
Seems that there's a very brief moment after the hit where the character was considered as knocked down even though it shouldn't. The bots were just quick enough to take advantage of this.

Fixed in Regalis11/Barotrauma-development@b5149ce.

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue. Working correctly, closing.
