### ISSUE TITLE
Loading Screen Tips- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#565]
This request adds to the game random loading screen tips. Player can select in settings menu which tips have to be displayed. Disabling all tips: Beginner, Intermediate and Experienced results in tips not displaying at all.

By default in settings menu tips are being enabled only at beginner and intermediate grade. 

Tips can be edited by xml files and changing it does not break multiplayer mode.

**Here are the tips of my idea to be added to the game:**

Beginner:
*You will not receive a reward for delivering the cargo, if cargo boxes lack any of it's starting content or condition of that content.
*You can access tutorial level right above single player mode.
*Junction boxes will break, if reactor generates too much power.
*Engineer and Mechanic are considered to be most crucial members of the crew due to them having most fixing skills of all crew members. 
*You can use submarine editor to edit already existing submarines or create your own.
*You will get informed, if you kill a creature you were tasked to hunt instantly after it dies.
*The safest place to store an artifact inside submarine is most often airlock.
*Not being able to speak is caused by husk parasite.

Intermediate:
*Watcher can be killed without triggering a fight with it by shooting any nuclear shell to it's limbs.
*Batteries deliver limited amount of backup power at once. They are unable to fully surpass flooded reactor.
*Endworm is the most vital creature in Europa, but it does not have any armored body parts.
*Crawler is a strong appetite creature. It will devour a corpse of a fellow crawler in the middle of combat. Kill one of the crawlers, while being chased by a swarm of them to make the rest busy.
*An entirely injected morbusine kills all creatures in Europa, but endworm.
*Be sure to equip useful equipment and set devices at their best, before moving your submarine.
*If you decide to take a shuttle with you as your main vessel ensure it at least has well enough prospering nuclear reactor for permanent campaigns.
*Inventory resets to default in campaign mode, when doing that in multiplayer. Clear your inventory to have it for your next mission.
*Monsters do not need oxygen to breath, so sufforin is not the way of dealing with them.
*Deconstructing items result in them giving items used to craft them.
*Deconstructing an item having no crafting recipe will result in it being permanently lost. 
*Mantises are vicious and will quickly kill any human in a single strike not being covered by ballistic set. They also are immune to death of a blood loss themselves.
*Husks in diving suits do not make their victims bleed. Victim who does not wear a diving suit will however do, after being taken over by parasite.
*You cannot cure humans of husk parasite, who already died. Instead of having husk being instakilled it only takes regular damage.

Experienced:
*Charybdis deals low direct damage to humans, but inflicts powerful bleeding into them.
*Alive humans in advanced stage of husk parasite infection does not need an oxygen to breath and are immune to water pressure, but they will lose health over time. Using husk parasite infection as an alternate manner of diving outside submarine is advised to be made in presence of auxiriozine.
*Endworm does ignore humans trespassing near it.
*Engines do not occupy grid load, if they are having their force set to 0% at the time.

Note: If "Expert" and "Champion" recommended crew experiences are gonna be added to the game, they will most likely have no vanilla variations of themselves due to being quite complex.

See also this: https://github.com/Regalis11/Barotrauma/issues/538

**Comment by Regalis11** [comment]
Added in the dev branch
