### ISSUE TITLE
Elastin cannot be combined

### ISSUE THREAD

**Issue by dennzil** [Regalis11/Barotrauma#5652]
[x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After deconstructing plastiseals, the 50% elastin from each one does not stack in deconstructor nor can you combine it in your inventory or a container.

**Steps To Reproduce**
Deconstruct 2 x plastiseal
Deconstructor has 2 individual elastins at 50%

**Version**
Embrace the Abyss update (On windows 10)

**Comment by thegrb93** [comment]
Fruits also can't be combined which is annoying

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/085a92f57a261d1cdf193fed8370c81829b4023d

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
