### ISSUE TITLE
Health Scanner HUD shows all targets as "friendly"

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5659]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Health scanner hud uses the white "friendly" colour for people it hovers over, including enemies which are normally on red.

**Steps To Reproduce**
1. wear health scanner hud
2. scan someone who is not on the same team
3.
**Version**
windows 0.13.3.11

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/00ac13df49ea97ff37c57a88644760616e98e456

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
