### ISSUE TITLE
No modding control over links between biomes

### ISSUE THREAD

**Issue by LordFrith** [Regalis11/Barotrauma#5671]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the single connections between biomes which you have to raise reputation to pass are hardcoded.
From a campaign map modding POV would be good to be able to enable/disable these links, to be able to change the number of links between biomes and ideally to be able to control the conditions required to proceed
I make REALLYBIGMAP mod where these single links can be a huge distance (vertically) from players starting position. Pic included,

**Steps To Reproduce**
make a modded campaign map with large vertical scale. try to find single link to next biome

**Version**
v0.13.3.11 windows 10

**Additional information**
![20210501201903_1](https://user-images.githubusercontent.com/63119172/116793349-384cd680-aabe-11eb-90ed-779f893a36e8.jpg)

**Comment by Udrakan** [comment]
I agree that having a way to control custom playthrough routes might increase replayability for modded campaigns. It would be great being able to setup amount of gates between biomes and setup custom outpostgenerationtype for a gate outpost. Maybe

locationtypes.xml
canbegate="true" gatedzones="1,2,4,5"

mapgenerationparamteters.xml
mingatesamount="1"
maxgatesamount="5"

**Comment by Singularia** [comment]
Aside from modding an ability to tweak such parameters in vanilla campaign settings (at least in MP) would be much appreciated.

**Comment by Regalis11** [comment]
Partially implemented in https://github.com/Regalis11/Barotrauma-development/commit/bdba058513d17014b254e0a76f4af14e3a9cc2b9: the number of gates between each biome can now be configured in the map generation parameters.

**Comment by LordFrith** [comment]
tested in unstable branch
made various tests with various map sizes, big and small, and changing numbers of gates
works as expected, seem flexible and fixes my issue. thanks!
