### ISSUE TITLE
ISSUE:  UI text boxes appear to become out of sync with application state.

### ISSUE THREAD

**Issue by BrooftheBread** [Regalis11/Barotrauma#5672]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**ISSUE:  UI text boxes appear to become out of sync with application state.**

**REPRO:  In chat or developer console, after typing, press ENTER followed quickly by another key.**

**VERSION: v0.13.3.11**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**RESULT:  Chat or dev console receives last keystroke.  So, in chat for example, ENTER followed by 'R' within a fraction of a second result in an 'R' in the chat box.**

**EXPECTED RESULT:  Keystroke is not passed to chat or dev console  after user presses ENTER, is not lost, and activates the expected command or mode.**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/29aa1770d3d5d558900f317d76c4bb4f9d3e03f1

**Comment by Lithosagym** [comment]
Tested and confirmed that the issue was fixed.

**Comment by Rokvach** [comment]
Closing
