### ISSUE TITLE
Minerals sometimes can not be mined in outposts

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5674]
**Description**
If a mineral, say stannite, has a lightcomponent, it cannot be mined in outpostlevels.

**Steps To Reproduce**
-open outpost module in sub editor
-spawn uranium ore and stannite ore and save
-generate this module in leveleditor
-uranium is minable, but stannite isn't!

**Comment by Regalis11** [comment]
Turns out this wasn't related to the light components (both stannite and uranium have one), but the collider of the mineral not being moved when the item is moved to it's place. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4d21fe0c114f42ba25becc501fb63153c483ad06

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
