### ISSUE TITLE
Security Bots batteries in headset running out when hired.

### ISSUE THREAD

**Issue by frijoles108** [Regalis11/Barotrauma#5681]
I am playing on windows 10, the latest version of the game.
There is a bug where I believe the batteries in headsets still get drained for only certain BOT jobs. I had this on multiple campaign runs where I hired a new security member and they stopped being able to receive orders around the same time I would expect the battery to stop working, they only would receive orders from then on in local chat. I tested on multiple occasions after stunning the BOT in question, I would find their headset had a burnt out battery. This only occurred with security bots if i recall correctly. The most recent one, right before I made this report was a security bot. After replacing their burnt out battery they spawned with they no longer have their batteries running out.

**Comment by itchyOwl** [comment]
Hmm, it could be that they use those batteries for stun batons.

**Comment by frijoles108** [comment]
> Hmm, it could be that they use those batteries for stun batons.

I meant to post this update. The same security guard went through another battery and is now requiring a new headset battery. Your theory of the baton would make sense for sure, as I witnessed them using it since I'd replaced battery.

**Comment by itchyOwl** [comment]
It was as I suspected. Prevented them from using the headset batteries in Regalis11/Barotrauma-development@9d6cf15.

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue, working correctly. Closing.

**Comment by frijoles108** [comment]
Rokvach, did you try to reproduce the issue? You need to have the security guard fighting invaders with stun batons, they use up the battery from the headset.

**Comment by frijoles108** [comment]
> It was as I suspected. Prevented them from using the headset batteries in [Regalis11/Barotrauma-development@9d6cf15](https://github.com/Regalis11/Barotrauma-development/commit/9d6cf15).

Why was this closed?

**Comment by Rokvach** [comment]
Because this issue was fixed and tested to be working correctly
