### ISSUE TITLE
gap issue in dugong

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5685]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dugong has improper gaps for its engine room
has:
![image](https://user-images.githubusercontent.com/5103517/116823067-57944400-ab50-11eb-8d58-8d38686a6e79.png)

should be:
![image](https://user-images.githubusercontent.com/5103517/116823107-ab069200-ab50-11eb-9d8a-286ea6db00c9.png)

**Version**
0.13.3.11 windows release

**Additional information**

**Comment by itchyOwl** [comment]
Does it matter? Does it affect the water flow? If it does, the gaps are invalid. If it doesn't, there's no reason to change it. I couldn't notice the difference.

**Comment by Tsunder** [comment]
it does matter,
gaps only connect 2 hulls, chosen seemingly by the middle of the gap, so the side two hulls on the top are not connected directly to the bototm. 

this can be tested by removing the gaps that connect the top 3 hulls. the side two hulls will not drain without a specific gap connecting them to the bottom area.

![image](https://user-images.githubusercontent.com/5103517/116847428-7cbc9d00-abb8-11eb-8583-0be6a98e45d1.png)

![image](https://user-images.githubusercontent.com/5103517/116847398-70384480-abb8-11eb-968b-c96ecc804467.png)

**Comment by Regalis11** [comment]
Why does it matter that the two hulls on the side aren't connected to the hull at the bottom? Since the 3 hulls on top are all connected to each other, water will flow down regardless if the side hulls are connected to the one below or not.

**Comment by Tsunder** [comment]
they're connected yes, but the rate of water flow (and technically o2, but that's rare to matter) and direction is bottlenecked to about 1/3 the rate it could/should be. 

To be clear, the one large gap is equivalent to this:
![image](https://user-images.githubusercontent.com/5103517/116905681-4cebb480-ac0d-11eb-8d2e-e464c3b051ed.png)

The undersized gap is particularly noticeable when the command room is flooded and the door gets opened - the hull with the ladder gets filled up a lot due to the small gap and when a large breach occurs in the top.

**Comment by Tsunder** [comment]
aside: fixing this gap issue will also help players who look at the vanilla subs for build reference avoid making the same mistake in their subs a bit. >_>

**Comment by Regalis11** [comment]
Adjusted in https://github.com/Regalis11/Barotrauma-development/commit/890f70e9fae0ac80dd1882c9840dfd19a67ff15c

**Comment by Rokvach** [comment]
I did notice that using a welding tool in there looks a bit strange, its as if the welding tool is hitting something

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/912716bb-90a7-408a-9be6-493517792bf0)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b2b6f9aa-174d-41f9-9703-78ef340ebf0e)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
