### ISSUE TITLE
[13.3.11] Thalamus cant use discharge coils

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5686]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
From wiki and other sources seems like thalamus should be able to use discharge coil (like the one on berillia wreck) but in reality thalamus not using discharge coil as defensive tool at all.

**Steps To Reproduce**
1. quick start on selkie or any other submarine of choice
2. use command `spawnsub Berilia_Wrecked true` to spawn wrecked berillia with thalamus
3. go near discharge coil

**Version**
13.3.11 stable and unstable, windows 10 pro

**Additional information**
idk actually if this was a cut feature or really forgoten, but if thalamus gonna be able to use discharge coils it is gonna make him more dangerous enemy than he is right now (really ez to kill)!

**Comment by itchyOwl** [comment]
It's never been planned or implemented to do that. Not a bad idea though. Perhaps some day. Thalamus can currently only use turrets (that have ammunition in the loaders).

**Comment by Lefttroll** [comment]
thx for reply! (do i need close it or no tho?)

**Comment by itchyOwl** [comment]
No, let's leave it open, so we might even implement it one day ;)
