### ISSUE TITLE
RailSprite and BarrelSprite don't show up in spriteeditor

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5687]
[Bug, Modding]
Fairly self explanatory. RailSprites and BarrelSprites in Turrets don't show up in the sprite editor, and make centering turrets a lot more troublesome.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1b7a8e645a96bb779f5d62f04a1fe6f91e44c2a3

**Comment by Rokvach** [comment]
Tested, working correclty. Closing.
