### ISSUE TITLE
Disconnecting at random times on mission start and end

### ISSUE THREAD

**Issue by dlc2006** [Regalis11/Barotrauma#5688]
- [*] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I tried to send a message on twitter about this. I sent a bug report in several months ago and someone here fixed it I believe saying the sub was out of position? The game will crash upon clicking to start a new campaign mission. Sometimes it is fine other times it will crash each time. This has been the case on several custom workshop subs - right now we are using the Matriarch MK IV.

**Steps To Reproduce**
Start new mission in campaign with 3-4+ real players, 4-6 bots.

**Version**
Latest verision on steam for windows of both the game and sub.

**Additional information**
Attached the save files.
[Latest Saves.zip](https://github.com/Regalis11/Barotrauma/files/6412220/Latest.Saves.zip)

**Comment by dlc2006** [comment]
We have played a bit more... the issue persists but I have included an updated save file so we don't lose any progress if it was a simple fix again like the sub being out of position of however it was.
[Latest Saves 5-3.zip](https://github.com/Regalis11/Barotrauma/files/6418840/Latest.Saves.5-3.zip)

**Comment by Regalis11** [comment]
I'm afraid I couldn't get the game to crash using any of the provided save files. Would it be possible to send us the crash report? Or if you got kicked to the main menu with some kind of an error message, a screenshot of that message?

Sorry for the trouble, I hope we can squash this bug (and maybe fix the save file if that's possible) soon so you get to continue the campaign!

**Comment by dlc2006** [comment]
Where are the crash files located?

**Comment by Regalis11** [comment]
They should be in the game's installation folder (the filename is "crashreport.log" if the client crashed, and "crashreport_server.log" if it was the server). To be clear, did the game actually crash to desktop or did you get disconnected with some kind of an error message?

**Comment by dlc2006** [comment]
People disconnect from the server - time out. They do not crash to the desktop. When the mission loads in it spins and spins, it takes longer than normal so you can tell they are going to "crash". Their character stays in the sub but when they rejoin they can only spectate, they do not go back into play. This is only when a mission is started and sometimes ended.

**Comment by dlc2006** [comment]
I do not have any crash logs of either type but we played again tonight and there were still crashes upon two out of three mission starts. There were a total of three of us playing. The first round one person crashed/disconnected and the second round both did.

[Latest Saves 5-4.zip](https://github.com/Regalis11/Barotrauma/files/6424924/Latest.Saves.5-4.zip)

**Comment by Regalis11** [comment]
Thanks! It's hard to say what exactly the issue was without knowing what kind of an error message is shown when the clients disconnect, but if it was something along the lines of "Error while starting the round (did not receive STARTGAMEFINALIZE message from the server). Stopping the round...", this is most likely the same issue as https://github.com/Regalis11/Barotrauma/issues/5702.

I implemented a fix for this in https://github.com/Regalis11/Barotrauma-development/commit/34df975378b0a4371edd9c9656da05e7735c05e5 (link to our private repo)

**Comment by dlc2006** [comment]
However the missions loads initially seems to work perfectly - as we first start the server but when we select a new mission start from a station and it send us off then its a roll of the dice who is going to get disconnected.

**Comment by Regalis11** [comment]
That could be explained by the bug we fixed: the problem was that if loading the campaign save took long enough, the client would time out and get disconnected with the above error message. The save file tends to grow in size as the campaign progresses, so the issue would be more likely to occur further in the campaign. But it's hard to say if that was the problem in your case without knowing what the error message was.

**Comment by dlc2006** [comment]
So could we somehow get a hotfix for it? We are trying to play through the campaign but my teammates get restless having to reload each time from menu. Thanks for the efforts.

**Comment by Rokvach** [comment]
Tested, there hasn't been any sightings of this happening during the Unstable period, seems to be working correctly. Closing.

**Comment by dlc2006** [comment]
This has still been happening to us every time we play, not sure if you were referring to an updated beta tested version or not but otherwise the live version is still very much broken.

**Comment by Rokvach** [comment]
The fix is currently in the Unstable version of the game, coming in the next update
