### ISSUE TITLE
You can still fire a Railgun round when the Railgun Loaders condition is at 0

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5694]
Tested in dev in commit https://github.com/Regalis11/Barotrauma-development/commit/c38d3c5c43a1845741f5d8ac5ef372c4b49e4007

Repro steps:
1. Open up a sub which has a Railgun on sub editor
2. Select the Railgun Loader and set its condition to 0
3. Start test mode
4. Notice that you can freely fire the Railgun even when the loader is fully damaged

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/706af7dfb3dc36c930df5117ef6d34d606260780

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
