### ISSUE TITLE
[Gardening] You can instantly plant seeds by drag and dropping them directly to the planter

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5695]
Doing it by dropping the seed directly to the planter doesn't trigger the planting process that you would otherwise get when you left click with the seed to the planter.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0192f6bba499254d2097947bd9d3ac5a3a2d2205

**Comment by Rokvach** [comment]
Tested, this will most likely cause some confusion but it is working correctly, closing.
