### ISSUE TITLE
[13.3.11] Please sort the clients mod list

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5697]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The more people use modS the more subbed mods pile up - and the list really becomes an annoying issue.

Please for the love of god sort the mod lists in the client at least alphabetically! :P

**Steps To Reproduce**
Open settings
scroll for certain mods
scroll back to find mod
change direction again
build up anger
throw tantrum
throw keyboard at the next wall..
mouse still there? Some more scrolling....
... ;)

**Version**
all.

**Additional information**
![man-smashes-mechanical-computer-keyboard-rage-using-both-fists-stressed-completely-wrecks-anger-83712167](https://user-images.githubusercontent.com/3466193/116869335-d355c580-ac10-11eb-8b0a-a4fac1f98f6a.jpg)
...hulk smash....

**Comment by Rokvach** [comment]
I don't fully agree with this, as mods are loaded in the order they are shown in the list, it would mean if we force a alphabetic order the players own defined mod load order will break. We could always add some sort methods which are only visual and wouldn't affect the mod load order but what happens then if you sort them by alphabet and then decide you want to change the order of the mods after, would you have to exit out of the alphabetic view just to do that. 

There might need to be a second list of all the mods somewhere else which would be more manageable and keep the current list as the mod load order one. IIRC Juan was talking about merging the workshop within the settings too so maybe we could take a look at that when ever that happens.

**Comment by CurePindal** [comment]
Thanks for the info.

That leads pretty much to the next issue with the mod lists: Who on gods earth, and which Joe Average does know about the list and its mod load order functionality? No offense, but I had to tackle mod load orders a few times and this current systems is a nightmare.
I doubt informational and functional features should be squeezed into such list. And especially not without proper information about its functionality given.

**Comment by Rokvach** [comment]
I do agree that it isn't obvious enough that you can drag the mods around in the list, we are using a icon to display if a UI can be dragged as well as changing the cursor, but this functionality just isn't so widely used across the game, its mainly in the mods list and on crate/storage container UI's which can be dragged around. But I feel like this is a universal issue across many media, some games even show a animation of 
the dragging process when first accessing a menu

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c6ac9cf5-7e1c-46df-bb3f-bbfb55ff0284)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f479fe99-8c35-4661-a9a3-8ae68ad5e173)

**Comment by CurePindal** [comment]
Sry, but the issue is not about being draggable in the first place - its about the fuctionality that derived from the oder thats intransparent.

Thinking about it I dont even know if the order matters even when the mods are not yet activated and get activated when joining a server. Or does the server set the load order? The system does not communicate its functionallity. Its intransparent, hence badly implemented. (doesnt give proper overview without sorting and has an additional functionallity thats not even obvious on the 2nd or 3rd look)

**Comment by juanjp600** [comment]
I have some plans to change the way the mods list works, primarily I was going to focus on unifying the Workshop menu with the side panel in the settings menu so everything modding-related can be in one place, and I will need a solution for conveying override order. Perhaps we should turn this issue into a discussion about general QoL improvements to the mods list.

**Comment by hubismal** [comment]
A bit late on this, but the best way seems to be something like what juanjp is planning combined with the minecraft two-lists, one with all the disabled mods on the right and one with all the enabled mods on the left. This might warrant its own tab in the settings though, it would be pretty cramped.

**Comment by Krzeszny** [comment]
Simply the fact that you can't create load order presets is mildly to highly annoying.

**Comment by CurePindal** [comment]
This mess is even highly annoying, regarding the fact that the mod order is messed up when a mod is updated.
Seems updated mods get moved to the bottom of the list.

Can we get an overhaul, please?
