### ISSUE TITLE
Players time out simultaneously

### ISSUE THREAD

**Issue by TomV4** [Regalis11/Barotrauma#5702]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Everytime I host a barotrauma game, usually the first game goes fine, whether I'm docked to a station or on a mission, the first one always goes great, however every single time all players simultaneously time out on the second match, sometimes rarely with the exception of one player.

**Steps To Reproduce**
- Host a game
- Set the server size to whatever amount needed (I use 5 players).
- Play till the 2nd round/match.

**Version**
Windows - Barotrauma latest version

**Additional information**
This issue has occured on all versions for me so far - picture below.
![Barotrauma](https://user-images.githubusercontent.com/83643109/117050725-fc13b300-ad15-11eb-9414-88481d5947a9.png)

**Comment by Regalis11** [comment]
It's hard to say for sure what caused this without knowing what kind of an error message was shown client-side, but if the error was "Error while starting the round (did not receive STARTGAMEFINALIZE message from the server). Stopping the round...", https://github.com/Regalis11/Barotrauma-development/commit/34df975378b0a4371edd9c9656da05e7735c05e5 should fix this.

**Comment by TomV4** [comment]
Hey Regalis. Thanks for the help but unfortunatly the link you sent me doesn't work.

**Comment by Regalis11** [comment]
That's a link to a commit in our private repository, I'm afraid you have to wait for the next patch for the fix to be available. Sorry for the trouble!

**Comment by TomV4** [comment]
No problem, guess I'll stick to public servers for now. Closing this issue.
