### ISSUE TITLE
[0.13.3.11] Linux dedicated server can't launch on VPS

### ISSUE THREAD

**Issue by VozdyxDev** [Regalis11/Barotrauma#5705]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am tried run dedicated server Barotrauma on my VPS but it's crashed without crash log.

**Steps To Reproduce**

1. Install Barotrauma using SteamCMD 
2. Run DedicatedServer file

**Version**
Barotrauma Dedicated Server 0.13.3.11 (ReleaseLinux, branch release, revision 7096536cf1)

**Additional information**
My VPS system info:

Virtualization: OpenVZ
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-1127.8.2.vz7.151.14
CPU: Intel Xeon E5-2695 v4 @ 2.010GHz x3 cores
RAM: 4096MiB

**Terminal screenshot**
![image](https://user-images.githubusercontent.com/51175216/117131246-dfc15600-ada9-11eb-9089-e90af997e242.png)

**Comment by VozdyxDev** [comment]
I'm also trying to run in DEBUG mode [LinuxServer.csproj](https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaServer/LinuxServer.csproj) using .NET Core 3.0 SDK but get same result

**Comment by GWXerxes** [comment]
I've been having the same issue for some time on a dedicated server. I assumed it was due to the steamclient.so issues, but those have been fixed now and the issue still persists. The server crashes with exit code 255 after printing the "Loaded languages" message

Ubuntu 20.04.2 LTS
Kernel: 5.4.0-67
CPU: Intel Xeon L5420

**Comment by VozdyxDev** [comment]
@GWXerxes
What is your VPS provider and what kind of virtualization do you use?

**Comment by GWXerxes** [comment]
@VozdyxDev 
I'm not on a VPS, I'm having the same issue on a dedicated system

**Comment by GWXerxes** [comment]
@VozdyxDev 
I solved my problem. A different service was already binding to port 27015. Is it easy to get the Barotrauma Server to report that as an error?

**Comment by VozdyxDev** [comment]
@GWXerxes are you sure this was the problem?
In my case, ports were not binding.

**Comment by VozdyxDev** [comment]
In any case, I will no longer be able to find out if this problem was fixed for me, since I changed my hosting provider.

**Comment by GWXerxes** [comment]
@VozdyxDev I'm fairly certain. In my case Killing Floor 2 was binding to the same ports. I changed the ports in serversettings.xml to 20716 and the server starts reliably now
