### ISSUE TITLE
[0.13.3.11] Cannot give orders to bots

### ISSUE THREAD

**Issue by mbartnic** [Regalis11/Barotrauma#5711]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During campaign mode:
One character (captain cannot give orders to bots. Other characters can do it though.
Additionally chat has some static in it even if the character is in the sub. Other characters do not respond.
Issue persists between levels.

**Steps To Reproduce**
Observed this bug when captain went to mine some minerals and got severely damaged. Ate some alien blood (in health menu) and started to have psychosis. Psychosis persisted until end of level.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows 10 pro x64 version 2004
Game version: 0.13.3.11

**Additional information**
Uploaded save game:
[Save 1.zip](https://github.com/Regalis11/Barotrauma/files/6437723/Save.1.zip)

**Comment by mbartnic** [comment]
Workaround:
Buy/fabricate new headset and equip it to bugged character

**Comment by Regalis11** [comment]
This is not a bug: the captain's headset is switched to a different channel than the rest of the characters.
