### ISSUE TITLE
[ Unstable ] Endworm attack sometimes does no damage.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5712]
( Maybe this is already fixed in the next unstable build that isn't on public yet. )

Endworm's attack sometimes does not do any structure damage - only push the submarine and knock the crew around. From some previous discussions it seems that it may be the endworm's attack range is not long enough to reach the submarine hull in certain situations - such as if it's jaws prevent it from getting any closer against the submarine, or if the endworm is attacking from an oblique angle or a somewhat unusual submarine shape.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c1ba43f.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
