### ISSUE TITLE
[0.13.3.11] Using welding tool to repair custom hatch

### ISSUE THREAD

**Issue by nroht** [Regalis11/Barotrauma#5714]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Kastrull drone uses a welding tool to repair the custom hatch instead of a wrench.

![Untitled](https://user-images.githubusercontent.com/79766686/117399728-65b8da80-af2b-11eb-8925-4f036bef62d9.png)

**Version**
v0.13.3.11

**Comment by Rokvach** [comment]
Might be good to check if the docking port item assembly has this configured incorrectly still as this issue keeps coming up after we do any type of changes to subs

**Comment by Regalis11** [comment]
>Might be good to check if the docking port item assembly has this configured incorrectly

Nope, all of the seem to be up-to-date

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a67a2527891f24892eb58f881ae4d483c9e535e6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ab23977feb59de5d7e16b0ad9cef7b5fcc27039 and https://github.com/Regalis11/Barotrauma-development/commit/2bcbb896c24afba1192bd145251d5e2f622e1e22

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
