### ISSUE TITLE
Enabling a mod or changing the load order shifts the load order impredictably until Barotrauma is restarted

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#5717]
- [x] I have searched the issue tracker to check if the issue has already been reported.
This is likely _not_ related to #4044

**Description**
Enabling any mod or changing the load order and applying the changes causes other mods to shuffle around impredictably. 
Disabling a mod does not cause it.
The changes aren't visible in the menu but the mods aren't loaded correctly.

When the game is restarted, the load order goes back to normal.

**Steps To Reproduce**
**Step 1.** My example: have these 3 mods enabled in this particular order and restart the game (first test without other mods enabled, and if it doesn't break, enable other mods above and below these 3):
Jlobblet Tweaks + Into The Abyss
Into The Abyss
Jlobblet Tweaks

Correctly, the alien pistol's inventory sprite has a custom red icon over it. It's overwritten by these mods in the correct order.

**Step 2.** Enable any additional mod or change the load order of other mods:

The 3 mods listed above shuffle around impredictably.
The alien pistol has the default sprite because the mods aren't loaded in the right order.

**Step 3.** Restart the game: 
The load order goes back to normal, the alien pistol again has a custom inventory sprite.

**Version**
v0.13.3.11

**Comment by Leonidas-ai** [comment]
Also getting this bug whenever any mod is updated. Only is disabling all mods, restarting, and reloading them. A similar issue occurs during server loading mods for the host. When re-hosting a server after a crash, the mods will be out of order and a full restart is required.

**Comment by Krzeszny** [comment]
> Also getting this bug whenever any mod is updated. Only is disabling all mods, restarting, and reloading them. A similar issue occurs during server loading mods for the host. When re-hosting a server after a crash, the mods will be out of order and a full restart is required.

That's weird. In my case it's enough to just restart Barotrauma.

**Comment by NilanthAnimosus** [comment]
Tested in version 0.8.12.0, appears to work fine now. could not find any issues with adding, removing and reordering mods with restarting the game or not. server and client both had the same load order too on join.
