### ISSUE TITLE
Water flow forces often end up far too strong to break free from

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#572]
for a long time (Ever since it was added) I have found in various scenarios the water forces can become so strong that they effectively can nail you to a ceiling/floor that even a scooter cannot break free from, usually fixed from welding a single wall nearby or fixing a breach that others feels it should not cause the level of flow force applied to the character.

I don't have a test example at the moment, but the forces can easily exceed character movement.

**Comment by Momiro** [comment]
It would be nice if ladders and a new item, hand rails would let you pull yourself past the water flow.

**Comment by rico6822** [comment]
I think having to remove it would make this game less realistic, since flows like it are a part of real life disaster physics.

**Comment by NilanthAnimosus** [comment]
I was not thinking of having it removed, its more about characters being propelled at mach speeds into the ceiling of a shuttle because of the flow force and a single broken wall nearby.

Either their stacking in odd ways, or the force is a really high value. I like the force at times making me flood half the submarine because one didn't seal a door behind him and flood it locally. it makes sense it'd do that.

Just in a fully flooded room with something like a small pump removing some water and thats it, you cant exit the room at times depending on the submarines design, which seems to be unrealistic actually as its just too much.

**Comment by thegrb93** [comment]
They only issue I've seen is sometimes hatches or vertical stairwells seem to get an obscenely high amount of force and it is desynced too between server and client since it causes glitchy movement as well.

Other than that, I've always just been smart enough to stop the flow of water in order to allow mobility.

**Comment by thegrb93** [comment]
Seems like vertical flow goes the wrong way at times too. Like it's always pushing up and sometimes it pushes so hard that the water scooter can't even get past it.
