### ISSUE TITLE
Welding tool stopped working

### ISSUE THREAD

**Issue by DyadkaRuslan** [Regalis11/Barotrauma#5721]
During the game, the welding machines stop working, even if you put a new fuel tank.
I'm playing a campaign on the hunchback submarine
Game Version 0.13.3.11 for Windows 7
The picture shows that a new fuel tank is required. The welding machine shakes, but does not work :(
![20210508172239_1](https://user-images.githubusercontent.com/83873243/117543118-1dc9ae80-b024-11eb-99f1-dda81099a11f.jpg)

**Comment by Velaron** [comment]
Ты уверен что внутри не кислородный баллон?

**Comment by DyadkaRuslan** [comment]
Да.  Если вставить кислородный баллон, он взорвётся. (Уже проверил)

**Comment by LePiromano** [comment]
I've had this issue before, i believe it only happens when you replace the fuel in your welding tool with a welding fuel tank you bought in an outpost

**Comment by DyadkaRuslan** [comment]
I didn't buy fuel tanks. I find them in abandoned lighthouses and submerged submarines

**Comment by thompd27** [comment]
I am having this bug with any campaign after running out of fuel. After refilling it no longer works. However, its just THAT tool that doesn't work, so you can deconstruct and reconstruct the tool as a mitigation strategy until fixed.

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to get this to happen. :/ Tested with tanks purchased from an outpost, and tanks salvaged from a wreck and a beacon station, and in all cases the tanks worked even after saving and reloading.

If anyone has a save file where this happens consistently, posting it here would help us a lot in diagnosing this.

**Comment by DyadkaRuslan** [comment]
At the moment, I don't have a save with non-working welding machines. If I get them again, I'll post a save

**Comment by DyadkaRuslan** [comment]
I managed to reproduce the error. I explain: I took the welding machine with half the fuel, then filled the fuel tank at the fabricator and returned it back. The welding machine is not working. (from the captain) I attach the save below

**Comment by Regalis11** [comment]
Okay, I think I partially figured out what's causing this: the welding tool in that save file requires an item with the tag "weldingtoolfuel" inside it to work, but the welding fuel tank does not have that tag in the current public version. I'm not sure how that can have happened: the "weldingtoolfuel" tag was added just recently (see https://github.com/Regalis11/Barotrauma/issues/5527) and to my knowledge it hasn't been included in any public version before today's Unstable build.

I wonder if you have been using some mods that might've modified the welding tool at some point?

In any case, I implemented a fix that should get rid of the error in save files where this occurs: https://github.com/Regalis11/Barotrauma-development/commit/b70efba4f64f4bcfbcfafdd85185ddc5d7b274bc

**Comment by thompd27** [comment]
Interesting thought. We just came back to the game so I wasn't sure what I was running. Looking at the steam workshop shows I'm only subscribed to 3 custom submarines that haven't been updated in months. We weren't using any of those subs at the time though, I think its always been Humpback. 

![mods](https://user-images.githubusercontent.com/25060282/117849640-8302e700-b252-11eb-8057-3501a98e847a.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
