### ISSUE TITLE
Some text in Reactor UI is so small it doesn't render correctly

### ISSUE THREAD

**Issue by maxrothman** [Regalis11/Barotrauma#5723]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At text scale 100%, the circled areas are not just uncomfortably small (which they are), but the letters also render glitchy.
<img width="1440" alt="Screen Shot 2021-05-08 at 6 29 14 PM" src="https://user-images.githubusercontent.com/2607086/117555464-69348a80-b02d-11eb-805d-edce67d27b62.png">

Increasing the UI text scale to 120% only helps a small amount:
<img width="1440" alt="Screen Shot 2021-05-08 at 6 29 38 PM" src="https://user-images.githubusercontent.com/2607086/117555494-b1ec4380-b02d-11eb-9d63-3f9a154c9ca4.png">

Increasing the UI text scale more makes other parts of the game look weird, so going higher isn't a great workaround.

**Steps To Reproduce**
This issue occurs consistently and doesn't require any specific steps to trigger.

**Version**
- Barotrauma: v0.13.3.11 (ReleaseMac, branch release, revision 7096536cf1)
- OS: MacOS 10.15.7
- Hardward: Macbook Pro (Retina, 15-inch, Mid 2015)
- Graphics: Intel Iris Pro 1536 MB

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/34b8afc000293565d3c847aae6c4d223dc8eddb6

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
