### ISSUE TITLE
The Head is not focused when holding right mouse button

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#5728]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![98469885-15f69200-21da-11eb-90ea-1dd8f43e7104](https://user-images.githubusercontent.com/62313026/117594692-8d2fc300-b136-11eb-8547-e4c318bfa827.png)
When holding the right mouse button on an equip-able weapon/tool, the head does not look at the crosshair. Please fix it.

**Comment by Regalis11** [comment]
I'd consider this a feature request rather than a bug report, and since we generally only use the issue tracker for bug reports, I'll close the ticket.

I agree that this would be a nice little touch though, although currently not a very high priority to add.

**Comment by Erars** [comment]
It might be a feature request, but in a couple patches back when holding the ctrl Key, you can force the head to look at the mouse cursor.  Currently this does not work so something has changed.
