### ISSUE TITLE
Eggs inside walls at stations

### ISSUE THREAD

**Issue by Bakkeli** [Regalis11/Barotrauma#5733]
In destroy station missions monster eggs spawn along the floor but if a wall starts above the floor the eggs can spawn inside it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1b6188fe3f290a52b9dd59ccb43fa2f20971513

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
