### ISSUE TITLE
Loading screen tips out of date

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5738]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

><loadingscreentip>Administering drugs without sufficient medical knowledge may reduce the number of doses a single syringe provides, and may also reduce the quality of the effects of the drug.</loadingscreentip>

all syringes are single dose since item stacking update.

> <loadingscreentip>Morbusine is a neurotoxin potent enough to take down even some of the largest Europan predators. A trained medical doctor can manufacture it relatively easily using a medical fabricator.</loadingscreentip>

morbusizine literally doesn't affect monsters that don't require o2 (and poisons fail in general vs large monsters as per some recent commit)

><loadingscreentip>Be careful not to dive too deep. Most submarine hulls will start collapsing at the depth of approximately 2,000 meters.</loadingscreentip>

default depth is now 3.5km?

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
windows 0.13.3.11

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3c323b3fe18d75c4e5115be3365306472d9ba61

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
