### ISSUE TITLE
Worn items do not appear to use their spritecolor that is set in the sub editor by custom submarines

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#574]
I think held items do correctly show the right colour, but specifically worn items (IE. jumpsuits) do not appear to recolour to the sprite colour modified in the submarine editor.

I could be wrong if say, there are two colour values to set in the editor to this, it is more an in game observation than something I have tested, it is odd to see a brown-tinted Orange Jumpsuit that has the default orange colour when worn.

**Comment by NilanthAnimosus** [comment]
It actually appears at another check that the draw code in limb uses color which is based on the brightness. this however is not multiplied or based in any sense on the sprite color of the wearable components item, but entirely from the brightness itself.

**Comment by Momiro** [comment]
Would be cool to have tinted jumpsuits tinted when worn.
