### ISSUE TITLE
Enemy Submarine Location Appears on Handheld Sonar in PvP Mode

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#5743]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When in PvP, if a player swims outside and turns on a handheld sonar, the enemy submarine's coordinates will be revealed, contrary to what the main sub's sonar shows.

![image](https://user-images.githubusercontent.com/72813628/117823759-d158bb80-b23b-11eb-8952-af181c0a7d61.png)

**Steps To Reproduce**
1. Go outside your submarine in PvP mode
2. Turn on active sonar on your handheld sonar

**Version**
Unstable  V0.1400.0.0, however this is also a bug in vanilla.

**Comment by Leonidas-ai** [comment]
Sad. I'm going to miss this one
