### ISSUE TITLE
Pirate Submarines Have a Ghost/Two Sonar Points

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#5744]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pirates seems to have two locations on sonar, with only one of them corresponding to their physical location. Once inside a certain range, the distances of the ranges will be equal, but in opposite directions (ex: Submarine is shown 443 meters in opposite directions away from a user's sub)

![image](https://user-images.githubusercontent.com/72813628/117824997-ee41be80-b23c-11eb-8678-38b82020d45b.png)
![image](https://user-images.githubusercontent.com/72813628/117824983-eb46ce00-b23c-11eb-8c7a-02e8b391d91e.png)

**Steps To Reproduce**
1. Load into a Pirate Mission
 2. Check Sonar (additionally navigate to a certain point to see where both points intersect)

**Version**
Unstable V0.1400.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c5403288a2139d4709fd1e0e3fa235efb0597c0f

**Comment by Regalis11** [comment]
Thanks for taking the time to close this, but we'll keep the issue report open until we've tested an verified the bug is completely fixed.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
