### ISSUE TITLE
Pirate Missions End Abruptly due to Ballast Flora(?)

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#5745]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Enemy Submarines appear to be "neutralized" when coming into contact with ballast flora, or for other unknown reasons - this may just be coincidence, as I was unable to test it consistently.

![image](https://user-images.githubusercontent.com/72813628/117825847-a707fd80-b23d-11eb-8c89-9de3286ee9b5.png)

**Steps To Reproduce**
1. Load into a Pirate Mission
2. Have the enemy submarine navigate through Flora 
3. "Win" the mission

**Version**
Unstable V0.1400.0.0

**Additional Information**
The flora connection to this may be coincidence. The pirate sub was not interacted with, but the mission was seen as a success.

**Comment by M61Dev** [comment]
Not quite sure how to solve this in an intuitive way - it doesn't seem right that you couldn't abuse map hazards against the pirates, though it also doesn't make much sense that the pirates don't avoid them. Will try to scope out a good solution for this.

**Comment by M61Dev** [comment]
Pirate submarines can no longer be neutralized by destroying the reactor, so this shouldn't be able to happen anymore (unless whatever map hazard the pirates drive into takes out their whole crew)

**Comment by Rokvach** [comment]
Tested, no issues. Closing
