### ISSUE TITLE
Guns set to hidden in game can still be selected for upgrade.

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#5746]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Guns set to hidden in game can still be selected for upgrade when at the ship upgrader.

**Steps To Reproduce**
1.Have a sub with a gun hidden in game.
2.Use the ship upgrader to customize guns
3. See that the hidden gun is still selectable for customize.

**Version**
0.1400.0.0 Windows

**Additional information**
Should have a check box or something similar to upgrade tags to disable guns from being able to be customized.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
