### ISSUE TITLE
HumpbackPirate 2.0 uses default humpback description

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5750]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/117840605-b47bb280-b252-11eb-8c4c-0cb5ad775bc5.png)

**Version**
Unstable 0.1400.0.0 windows

**Comment by Regalis11** [comment]
Let's keep this open until the issue has been fixed / until the sub has been deleted

**Comment by M61Dev** [comment]
Deleted the sub
