### ISSUE TITLE
Ridiculous withdrawal

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5752]
- [of course ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Failing a single morphine injection is now completely lethal, is this intended?
https://user-images.githubusercontent.com/55637865/117845397-e1ca5f80-b256-11eb-8752-c0c5037037fe.mp4

**Version**
Unstable v0.1400.0.0 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5fc43eb6ccc7fbc825312d7fc68ffe61e38ce64c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
