### ISSUE TITLE
[Unstable] Joining a server with an ongoing round doesn't let you spectate

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5756]
Joined one of the public server where there was a active Escort mission going on (not campaign) and when I pressed Spectate nothing happened, the spectate button just disabled and no matter how long I waited I never got into the round.

**Comment by Regalis11** [comment]
Could not reproduce

**Comment by Rokvach** [comment]
The same also happened with any other player trying to join that server, the host had to return to lobby in order for other players to get in

**Comment by Regalis11** [comment]
Still couldn't find a way to get this to happen. Steps to repro would be much appreciated
