### ISSUE TITLE
The campaign doesn't run on the specific boat I made.

### ISSUE THREAD

**Issue by MokshinIvan** [Regalis11/Barotrauma#5758]
The company doesn't run on the specific boat I made.
All other game modes work. Other people have the same problem with my boat. 
The game version is currently the latest stable version.
![image](https://user-images.githubusercontent.com/84043497/117877323-179a3300-b2ad-11eb-991e-f8bd9726e99c.png)
![image](https://user-images.githubusercontent.com/84043497/117880103-63021080-b2b0-11eb-940a-8321aafd13e8.png)
https://steamcommunity.com/sharedfiles/filedetails/?id=2484390216&searchtext=a-531
The problem is not really in the boat, because the bug remained after the removal of the entire boat, except for the docking port. The bug is that when loading into the campaign, after loading there is a sound, but it is not possible to run around the outpost and interact with the NPCs. The boat docks and the company map opens, which can not be closed

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
This seems to happen because the sub's main docking port is connected to a motion detector that automatically undocks the sub at the start of the round.
