### ISSUE TITLE
[Unstable] Component swapping does not inherit itemprefab scale / spritedepth / color

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5759]
Components swapped at a station have their itemprefab properties reset. Scale / sprite depth / sprite color.

Swapped items inherit their 'origin point' currently. For the sake of consistency between swaps when using custom submarines, swapping items should preserve scale aswell as their sprite-depth and spritecolor for aesthetics' sake. All just sort of quality-of-life and compatibility and visual issues.

**Additional Information:**
Also there is some weirdness with loaders 'contained item position' getting offset when swapping between types.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26922eb3a1801ed05abf571ca43e4c86311d7d58

>Also there is some weirdness with loaders 'contained item position' getting offset when swapping between types.

I wasn't able to reproduce this though. Do you recall which weapon your were swapping to/from?

**Comment by Rokvach** [comment]
Tested by coloring a loader red, scaling it down, rotating it and mirroring it. Only the rotation of the item wasn't inherited.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/736dde5a215bc68d85351b9cb75d7dcac733fa1b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
