### ISSUE TITLE
Abandoned outpost don't have the docking port icon

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5760]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You're still able to dock abandoned outposts, but while docking, the outpost doesn't have the green bar that allows you to see what you're docking to

**Version**
Unstable v0.1400.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fa167d9eaaa92c57e6513b027b5aa8f98613fb0a

**Comment by RagingFlames** [comment]
Shouldn't they not have a docking port icon, since the computers that tell you where the port are wouldn't be working?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
