### ISSUE TITLE
Artie Dolittle's headset doesn't work

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5762]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Artie ain't receiving orders and his messages are cutting out from distances where we both should be able to hear eachother. My assumption is that his headset is broken.

**Version**
Unstable v0.1400.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0b70a356b307fb71f490c98fac247c547f1a573

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
