### ISSUE TITLE
Wreckless logbook (failed to place a wreck in the level)

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5763]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The mission's logbook spawned on top of a level wall with no wreck, here's the save with the issue.
[wrecklesslogbook.zip](https://github.com/Regalis11/Barotrauma/files/6462959/wrecklesslogbook.zip)

**Version**
Unstable v0.1400.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7c78a713f1d40f873e9fa91069110b328e705b8

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce, seems to be working correctly. Closing.

**Comment by LePiromano** [comment]
happened again
[dietznutz.zip](https://github.com/Regalis11/Barotrauma/files/6670276/dietznutz.zip)
