### ISSUE TITLE
[0.1400.0.0] Unable to upload any custom pirate submarines to workshop

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5765]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when trying to upload custom pirate submarine, an error occurs.

**Steps To Reproduce**
1. choose a submarine
2. try to upload it on workshop with tag `EnemySubmarine` 
3. get error

**Version**
[0.1400.0.0] Unstable, windows 10 pro

**Additional information**
here is error itself:
![Barotrauma_d5cjac6DGU](https://user-images.githubusercontent.com/42521948/117919558-e2fe9980-b2f5-11eb-9436-a1fd81786780.png)
here is mod (made by rundoomer) for quicker testing: 
[BrusilovPirates.zip](https://github.com/Regalis11/Barotrauma/files/6463487/BrusilovPirates.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4533af5b7f291c6c8d93b3ef48e97111362387b8

**Comment by Lefttroll** [comment]
Thank you!
