### ISSUE TITLE
[0.1400.0.0] Custom pirate submarines not being able to spawn

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5766]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Vanilla pirate humpback overrides any custom pirate submarines. No custom spawned in-game in 30 rounds span.
If you gonna try to remove pirate humpback from `Vanilla 0.9.xml`, pirate search-n-destroy mission will never load and will give you errors even if other custom pirate submarine were present

**Steps To Reproduce**
1. add any custom submarine in `Vanilla 0.9.xml`
2. add file of choosen submarine in `Barotrauma\Content\Map\EnemySubmarines`
3. Get in game and load pirate mission atleast 10 times to see that all 10 gonna be a vanilla pirate humpback and not custom sub.

**Version**
[0.1400.0.0] Unstable, windows 10 pro

**Additional information**
File of submarine i used for testing:
[AP_Brusilov.zip](https://github.com/Regalis11/Barotrauma/files/6463494/AP_Brusilov.zip)
Edited `Vanilla 0.9.xml` i used for testing:
[Vanilla 0.9.zip](https://github.com/Regalis11/Barotrauma/files/6463498/Vanilla.0.9.zip)

**Comment by Regalis11** [comment]
This is technically not a bug: the set of pirate subs used for a given pirate mission is defined in the mission xml, so atm adding custom pirate subs requires adding new missions that use the subs. We might reconsider this though, being able to add custom subs without having to add new missions could be useful.

**Comment by Lefttroll** [comment]
@Regalis11 Thank you for reply, but make pirate mission use same principe as wreck salvage will be much better and easier for modding community! (Also, do i need to close problem now or leave it be?)

**Comment by Regalis11** [comment]
I think we can leave this ticket open for now, we'll think about how to address/fix this!

**Comment by Lefttroll** [comment]
gotcha

**Comment by Regalis11** [comment]
We decided to leave the system as-is: the submarines need to be configured in the mission xml. Doing it this way (as opposed to selecting any random pirate sub) gives more control over the difficulty of the missions (harder pirate subs in high-difficulty levels) and makes it possible to adjust the size of the pirate crew according to the selected sub.

**Comment by Singularia** [comment]
Based on this conversation i made some suggestions https://github.com/Regalis11/Barotrauma/discussions/5945 to the current system that i think will be much better option than what we have now.
