### ISSUE TITLE
Reputation gate unlock needs clarification

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5767]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since 13.x on stable theres a lot of players asking about how to unlock the reputation gates into the next biome.

Hence the need to talk to the officer at the outpost next to the gate seems a tad too obscured and needs a bit more visible clarification.

Suggestion: The mouse hover over the gate on the map could mention the officer to unlock the gate.

**Version**
13.x onwards

**Comment by CurePindal** [comment]
Another confused customer:
https://steamcommunity.com/app/602960/discussions/0/5625537320583143682/

**Comment by Regalis11** [comment]
Added a mention of the officer to the tooltip in https://github.com/Regalis11/Barotrauma-development/commit/8b7bff251f2ac17dec38721b0c43a957c412f4ad

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
