### ISSUE TITLE
[13.3.11] On trying to join a MP game: Mission equality check failed

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5768]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Tried to join a vanilla MP game of a buddy and got kicked back to the server lobby with this bug message.
`There was an error initializing the round. {Mission equality check failed. Mission count doesn't match the server (server: 0, client: 1)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1016
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1637
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__93" has failed`

**Steps To Reproduce**
Join server, click spectage, bugged out.
Happened every time

**Version**
13.3.11, win10, MP, vanilla

**Additional information**
Not sure if it might matter but I switched back from the 14.x unstable branch before.

![20210512134703_1](https://user-images.githubusercontent.com/3466193/117970375-dfd0d100-b328-11eb-980b-a094f0d8f554.jpg)

**Comment by Regalis11** [comment]
>Not sure if it might matter but I switched back from the 14.x unstable branch before.

I think this might've had something to do with it, do you still happen to have the save file?

**Comment by CurePindal** [comment]
It wasnt my game. Just asked the host for a save. Will attach later.
I closed the client, did a verify (no issues found), restarted and could join without that issue popping up again.
But at that time the group was already moving on another route.
