### ISSUE TITLE
Charybdis inside the level

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5771]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Found a level in the aphotic plateau where the charybdis spawns before you get to the abyss and targets you inside the level, in the same level there's also a mission logbook spawning in the abyss, could be related, here's a save that should spawn you in the level with the issue
[level charybdis.zip](https://github.com/Regalis11/Barotrauma/files/6467610/level.charybdis.zip)

**Version**
Unstable v0.1400.0.0

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this. The charybdis doesn't seem to spawn until you're below the level:
![image](https://user-images.githubusercontent.com/14351070/118240762-07987400-b4a4-11eb-9073-106b3aa9e5e1.png)

I suspect the abyss is just so close to the bottom of the level here that it's easy to accidentally go there.

**Comment by LePiromano** [comment]
I wasn't able to repro it again either, you're probably right, looking at the map there's a path to the abyss really easy to confuse with a side-path.
