### ISSUE TITLE
Save won't open 

### ISSUE THREAD

**Issue by EtgOST** [Regalis11/Barotrauma#5775]
- Yes i checked the issue tracker.

when after doing a mission which i was in the world for about    30 mins tops.But when I entered a station nothing abnormal happened I saved and quit.But the next day when I went to go play the game it started me off at the at the picking language menu which was weird so after the menu it went to the main menu and i went  to load game and my save was red with no name here are some screen shots of the save file and error messages.A couple notes to add is the last screenshot shows the save being red,when i was in game before this bug i did explore a thallamuses ship and defeated it and if i can recall I also explored a wreck the same game.and i was running the humpback ship with 9 ai crew in singleplayer no mods.that is pretty much it from what i know.
version 0.13.3.11 you can also see this in the screenshots.
[](url)
![Screenshot (8)](https://user-images.githubusercontent.com/84118001/118084643-10e3ec80-b38f-11eb-8737-bce46ecf7673.png)
![Screenshot (9)](https://user-images.githubusercontent.com/84118001/118084687-20fbcc00-b38f-11eb-8cb1-227dd525d440.png)
![Screenshot (10)](https://user-images.githubusercontent.com/84118001/118084722-2ce78e00-b38f-11eb-855c-03c3ef9d9012.png)
![Screenshot (11)](https://user-images.githubusercontent.com/84118001/118084738-33760580-b38f-11eb-97d5-9cab709defbd.png)

**Comment by Regalis11** [comment]
Do you happen to still have this save file? If you could send it to us it'd help us a lot in diagnosing this. Note that you need to .zip the file to attach it here, since GitHub doesn't support the .save file extension.

**Comment by EtgOST** [comment]
> Do you happen to still have this save file? If you could send it to us it'd help us a lot in diagnosing this. Note that you need to .zip the file to attach it here, since GitHub doesn't support the .save file extension.

[Save 1.zip](https://github.com/Regalis11/Barotrauma/files/6481804/Save.1.zip)
I think this should work Thanks in advanced,

**Comment by Regalis11** [comment]
Thank you!

Unfortunately the file didn't shed much light into what caused this or how it can be fixed though. It seems the file has gotten corrupted somehow and can't be decompressed (the save files are technically .gz archives which need to be decompressed to be read). It sounds like something may have gone wrong when you save and quit the campaign or as a result of updating the game, but unless we happen to run into this again or find a way to get it to occur, I'm afraid it may be difficult or impossible for us to diagnose what caused the file to get corrupted. :/

**Comment by EtgOST** [comment]
> Thank you!
> 
> Unfortunately the file didn't shed much light into what caused this or how it can be fixed though. It seems the file has gotten corrupted somehow and can't be decompressed (the save files are technically .gz archives which need to be decompressed to be read). It sounds like something may have gone wrong when you save and quit the campaign or as a result of updating the game, but unless we happen to run into this again or find a way to get it to occur, I'm afraid it may be difficult or impossible for us to diagnose what caused the file to get corrupted. :/

[Save 1.zip](https://github.com/Regalis11/Barotrauma/files/6504183/Save.1.zip)
Ok this should work now after fixing it and making sure Ty again in advanced.

**Comment by Regalis11** [comment]
I mean I was able to download and unzip the file with no issues, but unfortunately I still couldn't diagnose why the save's gotten corrupted and fails to load.

**Comment by EtgOST** [comment]
Oh ok
