### ISSUE TITLE
[Unstable] Railgun loaders now explode when linked to tubes

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5777]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you link a (now legacy) railgun loader to a depth charge tube, it no longer fires the shell, but explodes at the location of the loader instead.
This doesn't happen in stable
Changing tags to "depthchargeammosource" does nothing

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/73229309/118121687-20485180-b3f2-11eb-9e0f-80690ca5a5cf.png)

**Version**
Unstable 0.1400.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f280f2b0fd9a334ed8bad45226dd7dac84040684

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
