### ISSUE TITLE
Watcher always spawns at the start

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5778]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since you reach 10% difficulty, every "watcher + small enemy" spawns appear at the start of the level, it's super predictable and happens in every mission.

**Version**
Unstable v0.1400.0.0 Windows

**Additional information**
(Is this for testing purposes?)

**Comment by itchyOwl** [comment]
Not intentional. Thanks for reporting.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@0bf3f15.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
