### ISSUE TITLE
[Unstable] Morbusine medical transport mission only loads 1 crate 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5779]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using a berillia: 
![image](https://user-images.githubusercontent.com/73229309/118126943-4e7d5f80-b3f9-11eb-96dc-cefb45af4631.png)

**Version**
Unstable 0.1400.0.0

**Comment by Regalis11** [comment]
This is intentional. Some of the cargo missions have less crates to transport, but offer a higher reward.
