### ISSUE TITLE
[Unstable] Cargo mission: You can use the content of crates and still get the reward

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5780]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can use the content of crates (medical, resources) to heal or craft, and still deliver the crates for the full reward, as long as you leave one item in the crate

**Steps To Reproduce**
1. Get mining material mission
2. Take aluminum/iron from the stacks, but leave 1
3. Craft items
4. Dock and still get the full reward while keeping crafted items

**Version**
 Unstable 0.1400.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56a5d659681bc3fe0ec842f884faa82831111047

**Comment by CurePindal** [comment]
I think trade runs should maybe have some unique trade goods instead of items instead. (e.g. "European Brandy" or such)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by ubertpendragon** [comment]
@Regalis11 @Rokvach 

Tested on latest unstable
You can also deconstruct items in the same fashion and get the full reward...

**Comment by Regalis11** [comment]
I couldn't fully reproduce this: the reward is given if you deliver at least 90% of the items, but when I deconstructed all but 1 item, the mission failed as expected.

In any case, I increased the threshold from 90% to 98%, it's a bit too generous to allow the players to "steal" 10% of the items.

**Comment by ubertpendragon** [comment]
@Regalis11 
I deconstructed and reconstructed 5x morphine and 5x fentanyl and refabricated them (out of 3 crates) on current unstable
![image](https://user-images.githubusercontent.com/73229309/120305437-099a6980-c2d1-11eb-9487-14b33428ecbf.png)

Also, not a bug but a severe balance issue:
**Being able to manipulate contents will always lead to broken results. Here's a simple experiment:**
![image](https://user-images.githubusercontent.com/73229309/120303685-5d0bb800-c2cf-11eb-82cd-b5703d2c1c40.png)

120mk reward per medical crate

This is the content of a medical crate:
![image](https://user-images.githubusercontent.com/73229309/120304291-f3d87480-c2cf-11eb-9a1d-c389a8549f98.png)

I _only_ deconstructed all the fentanyl and morphine and crafted it back, this is what the shop offers me:
![image](https://user-images.githubusercontent.com/73229309/120305578-351d5400-c2d1-11eb-8ea6-e0c20799f5ec.png)

With the mineral cargo mission that offers 500mk per crate, the most rewarding of all, I still managed to get 360mk off crafted diving knives from iron alone; there's also plenty of titanium which is precious and I can combine with aluminum easily and sell back for about 150mk a piece

Why am I bringing this up? 
You'll have to fix and balance the mission in several different ways as long as cargo is interactable. I think it's a pretty big design issue on top of others #5783
Cargo missions feel the weakest of the bunch and also the most easy to break

**Comment by ubertpendragon** [comment]
Tested with the same amount of items, the 98% change did the trick

No longer getting rewards by stealing (as many) items. 
Can still keep the deconstructed stuff and resell for a higher amount than mission reward though

**Comment by Rokvach** [comment]
Closing. I think selling the deconstructed items should be addressed later on
