### ISSUE TITLE
Key bindings unusable on a MacBook Pro touchpad.

### ISSUE THREAD

**Issue by jvriesem** [Regalis11/Barotrauma#5785]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On a MacBook Pro (and presumably other single-click touchpads), there's no way to simultaneously right-click and left-click. This halted gameplay for me after the first step of the first tutorial (when the mechanic needs to fix their first leak). I've played a bit more on another computer with a regular mouse, and it's fine for computers with two-button mice. Having some other keybinding for this action would make the game more accessible and usable. 

**Steps To Reproduce**
Use a single-button touchpad such as that on any MacBook Pro. The touchpad seems to only register one click at a time — despite ideas such as [this one](https://apple.stackexchange.com/questions/186983/simultaneous-left-and-right-click-with-trackpad) on Stack Exchange's _Think Different_ site.  Because of this, things like welding guns that require simultaneous pressing of the right and left mouse buttons do not work. This renders the game unusable for those with single-click touchpads (except for, perhaps, elaborate workarounds). 

**Version**
OS: macOS 10.15.7
(Steam) Build ID: 6614174
Barotrauma v.0.13.3.11 (ReleaseMac, branch release, revision 7096536cf1).

**Comment by Regalis11** [comment]
The keybinds can be changed in the game's settings.
