### ISSUE TITLE
[0.1400.0.0] (Feature Request) Ballast flora zap ability

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5787]
- [x] I have searched the request tracker to check if the request has already been asked.

**Description**
Make ballast flora be able to zap people when it reaches batts and supercharges

I always wanted to see more defense systems for ballast flora when it managed to reach a power source, so why not give it an ability to zap people when it managed to infect batts/supercharges. It gonna use same pricinpe as accelerated growth.
If attacked, use stored power in internal battery to produce discharge coil-ish zap on room.
**Version**
[0.1400.0.0] Unstable, Windows 10 pro

**Additional information**

**Comment by Regalis11** [comment]
Thanks for the idea! I'll close the ticket though since the issue tracker is only for bug reports.
