### ISSUE TITLE
mouse interacts with other UIs when server log is open

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5793]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
clients click on other UIs hidden "behind" the server log when the server log is open, i.e., clicking on navigation terminal.

**Steps To Reproduce**
1. open nav terminal
2. open server logs
3. click somewhere in nthe middle
4. close server logs
5. see that nav terminal was interacted with as if server log wasn't open
6

**Version**
windows 0.14.00 unstable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/312092dceced3fb9f498b85553dabffc122faf28

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
