### ISSUE TITLE
Morbusine insta kill

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#5798]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Morbusine kill way too fast.

**Steps To Reproduce**
1. Get Morbusine poison or Europan handshake
2. Apply to a humanoid character
3. See them die instantly

https://user-images.githubusercontent.com/70696707/118349700-67624e00-b57c-11eb-9666-d5bf68b1b45a.mp4

**Version**
Unstable 0.1400.0.0

**Additional information**
Apparently is also a bug on current stable

**Comment by Regalis11** [comment]
Seems to have been caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/5752, fixed in https://github.com/Regalis11/Barotrauma-development/commit/5fc43eb6ccc7fbc825312d7fc68ffe61e38ce64c.

Could not reproduce in the current stable.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
