### ISSUE TITLE
I Think That Grenades May Deal Damage Through Walls And Doors

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#5805]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was merely watching "Lucky Luke" on youtube just to notice him taking damage before someone yelled about a grenade (it was too late).

**Steps To Reproduce**
Obvious.

**Version**
Recent.

**Additional information**
https://www.youtube.com/watch?v=4WgxW7HdFAY go to 14:21

**Comment by Regalis11** [comment]
The damage seems to have come from the spineling spikes that hit the character (if you look closely, you can see them at 14:24 and 14:25).

**Comment by rico6822** [comment]
> 
> 
> The damage seems to have come from the spineling spikes that hit the character (if you look closely, you can see them at 14:24 and 14:25).

Ok.
