### ISSUE TITLE
Piezo crystals immune to chain gun

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5806]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
shot a full box of chaingun into at 2 different piezo crystals, didn't blow up.

**Version**
v0.1400.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4998898f163d0532a4b9de05370134e206fa6a70

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
