### ISSUE TITLE
[0.1400.0.0] You cant double honk when holding 2 horns in hands

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5809]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you cant double honk consistently.
you can only double honk if you do it the second you equip it.
in all other scenarios it's single honks.

**Steps To Reproduce**
1. load in game
2. spawn 2 horns
3. try to double honk (so there is 2 honks)

**Version**
[0.1400.0.0] Unstable (also was spotted on stable), Windows 10 pro

**Additional information**
honkmother is dissapointed.

**Comment by Regalis11** [comment]
It does seem that both of the horns play the sound, but it's hard to tell because they both play it at the same time.
![image](https://user-images.githubusercontent.com/14351070/118401914-395e3600-b670-11eb-9832-c718574a1c5f.png)
