### ISSUE TITLE
Inability to enter the route with sufficient reputation

### ISSUE THREAD

**Issue by HiWip** [Regalis11/Barotrauma#5810]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Inability to enter the route with sufficient reputation

**Steps To Reproduce**
Reached the given reputation, sailed to the route 

**Version**
Windows 10

**Additional information**
![20210516204543_1](https://user-images.githubusercontent.com/84270726/118394388-d11b4e80-b687-11eb-8b56-199c43693185.jpg)
![20210516204541_1](https://user-images.githubusercontent.com/84270726/118394389-d6789900-b687-11eb-8c65-1adaf6c6395c.jpg)

**Comment by Regalis11** [comment]
You need to talk to an officer in the outpost to unlock the passageway. We got another report about this (https://github.com/Regalis11/Barotrauma/issues/5767), and we've since changed the tooltip to be a bit more descriptive.
