### ISSUE TITLE
[0.1400.0.0] Level Editor causing game to crash

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5811]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Level editor crashes every time i try to generate level and it happens ONLY on unstable

**Steps To Reproduce**
1. Load on unstable
2. leveleditor in console
3. select needed biom
4. press `generate`

**Version**
[0.1400.0.0] Unstable, Windows 10 Pro

**Additional information**
happens only on Unstable

crashlog (with mods):
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/6489199/crashreport.7.log)
crashlog (without mods):
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6489205/crashreport.log)

Update: you can bypass this problem via quickstarting and then switching to leveleditor

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e2f46e70

**Comment by Lefttroll** [comment]
Thx for fix!
