### ISSUE TITLE
Pirate submarines are listed in the server lobby and "new game" menu

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5818]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9890c6d84e84c04a3193b6a7ac1f3267fa37dca6

**Comment by Rokvach** [comment]
Should pirate subs get their own category in the sub editor Open menu? I can see that getting quite messy if a mod adds in a lot of them.

**Comment by Rokvach** [comment]
No issues. Closing.
