### ISSUE TITLE
[Unstable] V0.1400.0.0 Husks non aggressive to pirates

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#5822]
Husks do not seem to attack pirates even when they are directly in front of them.

Windows 10

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. The huks do seem to attack the pirates and vice versa. Tested in both single player and multiplayer.
![image](https://user-images.githubusercontent.com/14351070/118615382-59553d00-b7c9-11eb-989a-73ad9a811065.png)

**Comment by Cogs16** [comment]
The only thing I can think is that when this occurred the main sub was very far away from the pirates, and I was watching via freecam.
