### ISSUE TITLE
light sources from other side of walls are visible on wall

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5828]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The lighting effect on a wall is visible even if the effect is on the other side of the wall ("behind"). It tells information about the surroundings that the person on "this side" of the wall wouldn't know about when following LOS rules.

**Steps To Reproduce**
1. go to a sub with lights that hit shells/walls
2. observe

**Version**
0.14

**Additional information**
creation of this issue spurred by #5639

it quite breaks stealth in PVP when one sees light effects from diving suits/scooters on the shell and can deduce enemy presence.

example images:
![image](https://user-images.githubusercontent.com/5103517/118686563-19df1e80-b7d2-11eb-956a-d83cd23162cd.png)
![image](https://user-images.githubusercontent.com/5103517/118686612-26637700-b7d2-11eb-8f0f-b97874c8c4b2.png)

**Comment by Tsunder** [comment]
particles also quite visible
![image](https://user-images.githubusercontent.com/5103517/118686700-3d09ce00-b7d2-11eb-89a6-c58e60a6337e.png)

**Comment by Regalis11** [comment]
I don't think we will be addressing this: it'd require such extensive changes to the lighting and los algorithms that I don't feel it's worth the time and resources for such a minor issue.
