### ISSUE TITLE
publishing a submarine "disables" it from editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5830]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
publishing a submarine to the workshop disables the submarine, because the workshop mod is disabled
this confuses new editors and sometimes encourages bad practices (like moving/deleting the /mods/submarine and putting it back into /submarines/)

**Steps To Reproduce**
1. publish a submarine on the workshop
2. submarine now gone from editor!!  
3. cry about "game deleting submarine" after publishing
5. enable workshop mod

**Version**
0.14 unstable

**Additional information**
expected is for subs to stay visible/usable after publishing

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fcae487ad96670ed9fdeb89b87b0393f1cd41447

**Comment by Rokvach** [comment]
Tested, it does take a moment for it to show up if you don't restart after publishing, but eventually it will. Working correctly, closing.
