### ISSUE TITLE
particle effects are drawn behind fins

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5836]
- [tried] I have searched the issue tracker to check if the issue has already been reported.

**Description**
particle effects such as water bubbles and muzzle flashes show up behind fins

**Steps To Reproduce**
1. have a coilgun/railgun near a fin, enough to point at/overlap
2. fire the gun
3. muzzle flash/bubbles do not appear in front of fin

**Version**
0.14.00 unstable
**Additional information**

humpback coilgun example:
![image](https://user-images.githubusercontent.com/5103517/118759799-ad9b0400-b83f-11eb-991f-afae6ec40108.png)

**Comment by Tsunder** [comment]
https://user-images.githubusercontent.com/5103517/119266272-1b388e80-bbb8-11eb-8c17-3db6e5dc2b7e.mp4

**Comment by Tsunder** [comment]
persists even with lit fins
https://user-images.githubusercontent.com/5103517/119266327-5f2b9380-bbb8-11eb-93a0-e2fefed88630.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b869b1ed921f36905b367cd81867b38097d752ea

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
