### ISSUE TITLE
draw behind sub weird lighting

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5837]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

a) fins will obscure items (like coilguns and characters) even if they're lit otherwise - expectation is that the lit item remains lit
b) draw behind sub doesn't light anything between 0.900 and 0.999 (all black!) - 

**Steps To Reproduce**
1. shine a draw behind sub light on a fin with default (0.970) depth
2. observe
3. swim to the fin where the light shines
4. observe

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

a) humpback coilgun
![image](https://user-images.githubusercontent.com/5103517/118760828-7594c080-b841-11eb-89b1-0c62c91a6aa7.png)

feet pic
![image](https://user-images.githubusercontent.com/5103517/118760720-4a11d600-b841-11eb-9f8d-3f5743ed8991.png)
Implies that the character swims behind the fin
but when shone with a casting light (for example the headlamp of the diving suit), the character is clearly in front of the fin.

b) all of the vanilla subs / default fin depth are 0.970

**Comment by Regalis11** [comment]
While I wouldn't necessarily consider this a bug (lights that are set to be rendered behind subs are rendered behind all structures, including the fins), I agree that it looks a little off.

I changed the lighting algorithm a bit to address this https://github.com/Regalis11/Barotrauma-development/commit/905025bfbe78914cccb0ae8778c3f744f5d9e087:

> Experimental lighting change: only hulls and structures with a physics body obstruct lights that are set to be rendered behind subs - decorative structures like fins are now illuminated. See Regalis11/Barotrauma#5837. Might cause weird-looking lighting in some situations (although I couldn't find any obvious problems in the vanilla subs), so let's keep an eye out for those.

**Comment by Rokvach** [comment]
It does look a lot better but it also now highlights all the LOS flaws, which might be why those pieces were set to be so dark in the first place.
