### ISSUE TITLE
Respawn shuttles using the "airlock doors assembly" end up having both open and close at the same time.

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#5842]
This could be a mistake on my end, however on the hemulen and one of my own shuttles I have noticed that the doors in the "airlock doors" assembly will end up both opening or closing at the same time. This causes the respawn shuttle to flood and sink and become unusable. In the editor they work fine(Async) however in game they get switched to synchronous closing.

Current Release.

**Comment by Regalis11** [comment]
This most likely happens because all the doors in the shuttle are forced to close when the shuttle leaves. The airlock assembly simply toggles the doors, which only works properly if one of the doors is open and the other closed.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5acac08a7c41c3c1614ee4e1f1d45f85b9f73a9b

**Comment by Cogs16** [comment]
This seems to occur before the respawn shuttle departs in my experience.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
