### ISSUE TITLE
Reload Sprites button in sub editor breaks diving suit lockers visually

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5843]
Didn't notice any issues with other items

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5e9ee84b-de57-4490-8a7d-5b43cab8b125)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d75e04febd740df435c1a8843e9d50cddf02f4c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
