### ISSUE TITLE
Raycast projectiles go through destructible walls and can even hit creatures and other things on the other side

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5844]
Video:
https://www.youtube.com/watch?v=Pwi3MsAbcpY

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bc68de3f3f711444d9e55eed2fc73c7625fca132 (I think)

**Comment by Rokvach** [comment]
I was still able to reproduce this, its a bit less reliable than before but there's still areas where you can shoot through

https://www.youtube.com/watch?v=-hYrull7Tok
https://www.youtube.com/watch?v=y5NsXLZhmCg

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
