### ISSUE TITLE
Campaign Store: Sell quantity can be displayed incorrectly

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#5845]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The sell quantity can sometimes appear bugged, not reflecting the actual total you're about to sell.

**Steps To Reproduce**

1. Have a single riot shotgun in your inventory.
2. Open the store, put the shotgun into the selling crate.
3. Close the store, get another riot shotgun.
4. Open the store again and move the second shotgun into the selling crate by clicking the big button.
5. Notice that the basket quantity is maxed at the previous maximum (1), but the total selling price will reflect the price of 2 shotguns.

**Version**
v0.1400.1.0 (unstable), probably happens in earlier versions as well

**Additional information**
Removing all the shotguns from the sell crate will allow you to re-add them without the quantity maximum being displayed incorrectly.

**Comment by ekqvist** [comment]
Fixed in 7eb418b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
