### ISSUE TITLE
[Unstable] Shuttle docking port doesn't show in sonar

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5846]
Just like during playtesting but in reverse this time, noticed whilst looking that the nav terminal at the subs end

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5c014c11f7bfd27d0368e12f2a463190d5163141

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
