### ISSUE TITLE
[Unstable] Players with no campaign management permissions can toggle missons on and off

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5847]

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/72b386ff23dbd3d45139072a921313eb9e027e25

**Comment by Rokvach** [comment]
Tested, working correctly. closing.

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
