### ISSUE TITLE
Events - goodsamaritan trigger doesnt show "[E] Examine"

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5849]
**Description**
After finding the unconcious man, the only prompt is for pressing G to grab him. However, E works completely fine, it just doesnt show. Vid:
https://user-images.githubusercontent.com/59519434/119064885-aceba480-b9dc-11eb-9e62-e9e4c466cf45.mp4

**Steps To Reproduce**
-start a MP server
-triggerevent goodsamaritan
-walk up to unconscious man
-look at interactable options, E is missing
-press E and it works as intended

**Version**
Unstable

**Comment by Rokvach** [comment]
This has been fixed in the `chained-events` branch afaik, haven't yet taken a look at the branch to confirm it

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
