### ISSUE TITLE
[Unstable 1400.1] Hardpoint/Turret placement mismatch

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#5851]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a rotated Hardpoint changes to a (purchased) Turret, there is a placement discrepancy.

**Steps To Reproduce**
(images provided)
- Place a rotated hardpoint 
![malaco_front hardpoint](https://user-images.githubusercontent.com/58775950/119145869-10df8e80-ba18-11eb-9995-79195822ace2.jpg)
- Load game
- Purchase a turret for that hardpoint
- Go to the next round to change the hardpoint to the purchased turret
Result:
The location of the base of the turret will not match the location of the base of the hardpoint, causing the turret to be recessed.
In other words, instead of getting this:
![malaco_front_laser](https://user-images.githubusercontent.com/58775950/119146034-38cef200-ba18-11eb-9d95-d4e5225ec5bb.jpg)
You get this:
![malaco_front_laser_embedded](https://user-images.githubusercontent.com/58775950/119146212-69af2700-ba18-11eb-9a69-949d742b1f80.jpg)
And if I were to purchase a railgun, this would be the result:
![20210520143532_1](https://user-images.githubusercontent.com/58775950/119146502-b0048600-ba18-11eb-9a28-1bebf5237918.jpg)

**Version**
Unstable V 0.1400.1.0
(UnstableWindows, branch dev, revision 211c005be3)

**Additional information**
Another (smaller) issue with hardpoints is the lack of these settings for the hardpoint/turret:
![hardpoint mission properties](https://user-images.githubusercontent.com/58775950/119146854-0d003c00-ba19-11eb-9d1b-1fd3c4f81cf3.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/19df3cb2686d7fb0cbb8812695bab4e811f8ff15

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
