### ISSUE TITLE
[Unstable] Doors wired with buttons can be INSTANTLY opened with Crowbar equipped, even with the wrong Id

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5854]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have:
-a Crowbar equipped
-a Custom Door with a button wired to it (toggle)

Left click on the door; it will open and you won't have the ability to "force" the door with crowbar
Doors *not* wired and button doors behave normally

**Steps To Reproduce**
Pick a vanilla sub
Equip crowbar
Left click on airlock door
Break the airlock sync

**Version**
Unstable, possibly live as well

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@b84fb51.

**Comment by Lithosagym** [comment]
Tested, opening custom doors instantly with a crowbar confirmed fixed.

**Comment by Rokvach** [comment]
Closing
