### ISSUE TITLE
Feature request, start using registered (protected users) (steam username) "kinda urgent" Also logs should show steam id on join.

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#5857]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A way to register your nick/alias so other ppl cannot impersonate being you.

**Additional information**
So I have come across this issue where I'm being accused of a "Known grieffer" (this is being written after I was banned from a server instantly after joining (I remember you) Before that somebody on another server suddenly attacked  (after saying that I allegedly killed him somewhere somehow) me but it didn't race any alarms. Now in my opinion I'm no grieffer usually my karma is very high. Today I joined 2 servers and ppl started to accuse me of being a known grieffer. I'm pretty convinced this is a hate campaign against me from a person whom I shall not mention.

So I have deducted that someone could be using my nick to grief and shift the blame on me. This is why I feel after I have been promoting a global grieffer ban list =D That Omg I could end up on this list, and ppl who have been saying that maybe it's not such a good idea could be right. So my new and improved proposal is 2 part,

1. Make usernames register-able/Steam Name only.
2. Make logs show steam id's on join and karma events, and kick 

Why? cause it's not a humongous community where 1 can just ignore the bad side, we have to live together and if somebody starts to wage a war against somebody like this it's a sad situation :(
https://steamcommunity.com/sharedfiles/filedetails/?id=2493830392

**Comment by thegrb93** [comment]
Embrace the honkmother
