### ISSUE TITLE
Can do already done missions.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5859]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can do the same mission twice if you select the exact same path from the exact same outpost

**Steps To Reproduce**
Do a mission (in my case, it was VIP transport mission)
Go back to the outpost, get new missions, select the missions that are in the same path you used when you did the first mission.
If the issuse is happening, you will get the missions you selected AND the mission you did the first time, even if it doesn't show up while selecting the missions.

**Version**
v0.1400.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e98befe4fdfc595ed54ed01f486cc1a0d77071a5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
