### ISSUE TITLE
abyss and combat diving suits don't spawn with oxygen tanks

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5861]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
abyss and combat diving suits don't spawn with oxygen tanks
abyss and combat diving suits don't have the "divingsuit" tag/identifier that oxygentank refers to to spawn it in

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.13 stable

**Additional information**

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
