### ISSUE TITLE
Undocking a subs shuttle and docking at an outpost lets you change back to your previous sub

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#5864]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you undock your subs shuttle and dock at an outpost, you can select your original sub at the submarine terminal of the outpost. Doing so spawns the sub in its state in which it started the previous level. The shuttle seems to be docked do the sub and it is also in its state in which it started the previous level

**Steps To Reproduce**
Load up any submarine that has a shuttle
Undock the shuttle and dock at an outpost
Go to the outposts submarine terminal (at which you can change your current sub)
Select the main sub
Start a round

The main sub should be respawned now, and the shuttle should be docked

**Version**
Windows 10
![grafik](https://user-images.githubusercontent.com/63376072/119224849-bb32e100-bb00-11eb-97ad-a3eca4ae0a9d.png)

**Additional information**
//

**Comment by Melolatius** [comment]
Also, I noticed that if you undock a shuttle, but stay in the main sub and dock it at an outpost, the shuttle is spawned at its location it would be docked at. Is this normal, or a bug?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/39f9299f6b9a4bec316681fb824c7d48c6c9909a

**Comment by Lithosagym** [comment]
Tested, confirmed that you cannot switch back to the main submarine if the sub isn't nearby when you dock using a shuttle.

**Comment by Rokvach** [comment]
Closing
