### ISSUE TITLE
uneditable max player field  for lobbies

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5869]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
can't type in this field, despite the pencil, can ONLY use the +- buttons
![image](https://user-images.githubusercontent.com/5103517/119239330-5d10f880-bb16-11eb-9ee7-650962e34649.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.13 stable

**Additional information**
pencil shouldn't be there or it should be type-able

UI max player text field multiplayer lobby

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b1fcb73bf5061f13e7acaaff38e3e20d5e7062cc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
