### ISSUE TITLE
Calyxanide cannot self-cure velonceps calyx infections (husk)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#587]
I am not sure if this has been fixed yet, or was even known as an issue, but last I recall playing the calyxanide drug is incapable via GUI use of curing yourself of husk infections.

Not to be confused with a maxed out infection, this is akin to using 3 bottles of calyxanide around the time the message appears that you can no longer speak, yet the infection never stops.

It does cure when used on another person, which is the most curious thing.

**Comment by Regalis11** [comment]
Calyxanide has to be injected for it to work (or used with a medical dart or inhaler if you're playing BTE). I think this could be changed though, it should probably have a milder effect when taken directly like most of the other drugs.

**Comment by NilanthAnimosus** [comment]
Actually the bug was that it wouldn't take effect when self-using with a syringe.

**Comment by NilanthAnimosus** [comment]
I went to test this out on my modified server I've been tweaking the last few days, and the host on a server can cure himself fine with calyxanide.

**Comment by Regalis11** [comment]
You're right, it's broken client-side. I just noticed that the statuseffects applied with the self-use buttons are multiplied by deltatime even though they should be instantaneous, making calyxanide (and other other meds with instantaneous effects) do almost nothing.

**Comment by NilanthAnimosus** [comment]
Yes, I just spammed myself client-side on a server with calyxanide. 

On the server side he is still infected, despite 4 uses of calyxanide.

![](http://puu.sh/Ba5fd/7a1bd16740.jpg)
