### ISSUE TITLE
[Unstable,Modding] Shared upgrade & hardpoint tag means any kind of turret is swappable with any other.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5871]
Because there is **only 1 tag for 'turret' and its used by both the swappable & upgrade**, it means you can't create a separate 'class' of hardpoints with a unique tag for them and **still have them compatible 'valid' for use with the vanilla turret upgrade purchases.** Basically, in order for them to be upgradeable they would also end up being interchangeable with every turret in the game - thus breaking the intended hardpoint restriction.

Differentiation between marking a weapon as valid upgradable VS valid swappable would be needed!
- Temporary workaround for the time being is for mods which add their own hardpoints to create a 'clone' of the turret upgrade category which applies only to their own unique tag.

Also possible thoughts on hardpoints being classed if other heavier weapons are added in addition to railgun, as it doesn't make a whole lot of sense to be able to replace everything with railguns given the size difference.

**Comment by Regalis11** [comment]
I don't think this is just a matter of changing the tags. We group entities by category in the upgrade menu, and upgrades and swaps apply to everything in the category. I think changing that would require redesigning the upgrade menu. So to me it seems like adding a new category for items that shouldn't be swappable with the rest of the weapons seems like a sensible choice UX-wise. Or do you have some other type of solution in mind on how/where the custom weapons would be displayed in the menu?

**Comment by Ek-Videogames** [comment]
Just saying that the 'tag' fix does not seem so complicated to require such 'changing upgrade UX' as it would mostly be XML-side tweaking into the definitions between what is a "turret" a "swappable hardpoint" and an "upgradeable turret". 

Creating a new upgrade category or tweaking the existing one implying changes to tags associated with the,
( In this example being just changing the upgrademodules.xml to add a new second tag or something )

The problem in simple terms being that we have **basically three different standalone systems that are all intrinsically linked to one defining tag** "turret" so there is no way to only get one set of 'functionality' **without being forced to have all three.**

### Edit:
Also noted that if removing the 'turret' tag from them makes it no longer show up on bot orders menu, so keeping shared turret tag because of the AI is something to be aware of.

**Comment by Rokvach** [comment]
This can be tested in Unstable

**Comment by Rokvach** [comment]
As this is a very specific niche and no issues have surfaced because of this I will be closing it, can be re-opened if issues arrive once the patch is out and mods starts to utilize this properly.
