### ISSUE TITLE
Ballast flora infecting respawn shuttle doesn't disappear once the shuttle despawns

### ISSUE THREAD

**Issue by Padex98** [Regalis11/Barotrauma#5874]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
once ballast flora infects a shuttle, it persists in the entirety of the run, even when the shuttle respawns multiple times

**Steps To Reproduce**
infect a respawn shuttle, make it despawn, then spawn it again

**Version**
windows, game version is 0.13.3.11

**Additional information**
n/a

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4474c373208a1bdc8133b43d8d870299f091d418

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
