### ISSUE TITLE
[Unstable] Chaingun barrels do not change sprite-depth with the rest of the turret.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5875]
**Unstable v0.1400.1.0**

Unlike the behavior of `railsprite` and `barrelsprite` on turrets, the `spinningbarrelsprite` of chaingun does not seem to maintain it's sprite depth relative to the base sprite depth. Instead, it remains in 0.11 to 0.13 sprite depth regardless of the rest of the turret sprites, causing the barrels to be in front of just about anything greater than the 0.13 depth.

![image](https://user-images.githubusercontent.com/55356135/119245387-0243c500-bb47-11eb-8159-d1f58f4bd570.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ebfe83aed90b0c605905c7d1cddceebabb55341a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
