### ISSUE TITLE
explosions do not seem to have, nor trigger any status effects - but may load them via attack

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#588]
Explosions load an attack and an attack can contain status effects - but the attack is unused except to store the damage values and range.

This damage is then applied on a per-limb basis without ever triggering the effects for the attack itself.

Can the attack status effects be added into the explosion (for all entity types if possible, if the explosion is under water perhaps, etc).

**Comment by Regalis11** [comment]
Implemented in the dev branch
