### ISSUE TITLE
You can complete a round with a pirate sub but the pirate subs rotation never changes

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5883]
So even if you can own a pirate sub it will always be moving backwards

But still should you be able to own one this way? Especially if we've done some adjustments to the pirate subs already to beef them up for the pirates

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/437a95ab168239eb902140bd0f64e06c721bca4c

**Comment by Rokvach** [comment]
Tested, not possible anymore. Working correctly. Closing.
