### ISSUE TITLE
docking ports seem to break to voltage damage if connected to a grid - even if the voltage is 0.6

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#589]
I think it was doing this since the optimizations on the power grid, but they cant seem to handle any level of load when it comes to power transfer. if their connected, they break within about 10-20 seconds regardless of voltage.

Typically nobody notices this as players may not have even left their spawns.

I simply tried feeding into docking port power a shuttles own batteries (4 batteries, unwired 2. had them at 100% charge for 1100 power output of 2000). the relays had a max power of 99999. essentially nothing should have gone wrong at such a low voltage but they broke repeatedly.

Mind you I tested this without being docked to a submarine. but in theory it just shouldn't be causing this to begin with even if not docked or the docked submarine is not after power.

**Comment by Regalis11** [comment]
You mean you were feeding power through a relay to a docking port that's not connected to anything (i.e. load was at zero)? If that's the case, it's supposed to break - it's essentially the same as powering up the reactor when nothing is consuming power.

**Comment by NilanthAnimosus** [comment]
I guess not a single sub designer understands this or has any indication it is meant to be done this way. especially given the logic outputs continuously usually if I recall correctly when a submarine is docked while relays are toggle based? (I'm not a logic expert, i am very bad with logic components in the game actually haha I couldn't even wire up airlocks usually).

I only examined this as sub designers kept wondering why their shuttles are not charging, why its going wrong etc. 

The power was fed via batteries and fed back into the same batteries (the batteries at around 50% - 70% capacity) - the load was consumed correctly essentially, same as if there was oxygen generators running and such, the networks voltage behind the docking port was below 1.0 but the port exploads without anything docked to it was my main point.

I take it by what you say, the docking port should not be connected to power and should be severed if nothing is docked to the port? and it is intentional that a docking port that has no docked sub should expload from a perfectly fine network behind it. I would have thought the docking port should instead be drawing 0 load and simply not count it?

**Comment by Regalis11** [comment]
I agree that the way relays currently work is confusing, and should probably be reworked. I think the problem you're having here is that you've connected multiple power-consuming devices and the docking port into the output of the relay. In that case what happens is that the relay passes through a non-zero amount of power. The docking port (which works the same way as junction boxes) has a zero load because it's not connected to anything that draws power, and the power causes it to break.

**Comment by NilanthAnimosus** [comment]
Just for the record, the Aegir MK III is wired reactor -> junction -> straight to docking port.

I guess there is no good example to understand this is a thing that should be done, its honestly not obvious they perform this way due to the fact players likely see them as machines that give power to another submarine instead of literal separate junction networks that take the power even when they don't need it (Also unlike relays actually).

Relay behaviour is if its turned on, it doesn't matter if nothing is wired on the other side. while junctions just detonate instead. thats the only true confusing part about this to me. you can wire a relay to power in without a power out.

At the very least perhaps later the default submarines could be updated to have the correct wiring to prevent this issue as an example of working ports if this was the intended behaviour.

**Comment by NilanthAnimosus** [comment]
Well, this scenario does indeed break all 4 docking ports, yet doesn't do anything to the relay that has a listed power of 3580 kW and a load of 0 kW:

![image](https://user-images.githubusercontent.com/29177976/43777074-a8956570-9a49-11e8-8baf-fd3acd9fc10f.png)

**Comment by NilanthAnimosus** [comment]
Correction - it broke 3/4, the one where the power came from did not break (?)
