### ISSUE TITLE
When buying a lot of items in bulk it only spawns a single crate per item category

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5894]
So items which goes to a normal metal crate will be left on the ground once that one metal crate is full, same happens with the medic crates etc

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b6dfc99492a3c3ad38aa96711e22f8bdb69ade9b

**Comment by Rokvach** [comment]
Tested, for some reason Captain's Pipes weren't placed into crates but everything else that fits into a crate was 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d7319dfc-c473-4fff-ab10-5b574b845c33)

**Comment by Regalis11** [comment]
Looks like that was an unrelated issue, none of the items in misc.xml were configured to spawn in crates. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/00f9036c412d371925dc1489abba602be12acbc6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
