### ISSUE TITLE
Bad performance when using a Shadow Cloud PC as a client

### ISSUE THREAD

**Issue by Krisscut** [Regalis11/Barotrauma#5895]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A buddy of mine is using a shadow (see https://shadow.tech/en-gb/specs) cloud computing PC and he is having some pretty terrible performance.
For example 15 FPS as a client while i get 75 as a host with a kinda similar spec on a "real" PC.
Best performance is docked at a station with around 30 FPS, but it drops to 15 and lower when roaming through a level and lot of NPC spawns.

**Steps To Reproduce**
Subscribe to a shadow and play a multiplayer game from there.

**Version**
Windows - Latest stable Barotrauma v0.13.3.11

**Additional information**

Probably an optimization issue, and might be also on shadow's end and unrelated to barotauma ? Let us know if you think he should contact Shadow themself instead.

Real specification on the shadow is showing: 
- Processor: Intel Xeon CPU E5-2667 v3 @ 3.2GHz
- Graphic card: NVIDIA Quadro P5000
- Ram: 12 GB

He is able to run Satisfactory, Control, Sea of thieves, Witcher 3 and even a bit of VR without any drop in FPS so there is something weird here.

I have attached the sub that we are using for reference as well.
It is quite big and detailed with lot of objects, but it shouldn't be that bad for him.
Let us know if you need more details to investigate this !

[The Initiatior - v1.16.sub.zip](https://github.com/Regalis11/Barotrauma/files/6546902/The.Initiatior.-.v1.16.sub.zip)

**Comment by Regalis11** [comment]
Looking at the specs, that should be more than enough to run the game smoothly. Something that might help us diagnose this is if your friend could enter the command "showperf" in the debug console (which can be opened by pressing F3) and send us a screenshot of the performance diagnostics view that shows up. Might help us narrow down whether the bottleneck is in the game logic, rendering or somewhere else. Thanks in advance, and sorry for the trouble!

**Comment by Krisscut** [comment]
We just tried but it seems we can't run the "showperf" command:
![Barotrauma_2021-05-26_16-56-01](https://user-images.githubusercontent.com/8125922/119682559-4551b100-be43-11eb-999e-cd3c7143180d.png)

**Comment by Krisscut** [comment]
Ok, so we tried in different configurations, and we have both the performance from me and him. My PC specs are (1080, 32GB, I7 7700K CPU 4.2Ghz, on NVME disk)
We have also enabled the steam FPS counter. (top left for him, top right for me)

Hopefully it will help !

Stats from the lobby from him:
![Lobby from him](https://cdn.discordapp.com/attachments/179264667775008770/847127267502456852/unknown.png)

After spawn - undocked - no ennemies - him
![After spawn - undocked - no ennemies - him](https://cdn.discordapp.com/attachments/179264667775008770/847127560613527552/unknown.png)

After spawn - undocked - no ennemies - Me
![After spawn - undocked - no ennemies - Me](https://cdn.discordapp.com/attachments/179264667775008770/847127826859294740/unknown.png)

Docker at abandoned bandit outpost - Him
![Docker at abandoned bandit outpost - Him](https://cdn.discordapp.com/attachments/179264667775008770/847128249393217627/unknown.png)

Docker at abandoned bandit outpost - Me
![Docker at abandoned bandit outpost - Me](https://cdn.discordapp.com/attachments/179264667775008770/847128333678673940/unknown.png)

Roaming the seas and getting attacked by 4 mudraptors that i spawned- Him:
![Roaming the seas and getting attacked by 4 mudraptors that i spawned- Him](https://cdn.discordapp.com/attachments/179264667775008770/847129983251775508/unknown.png)
![Roaming the seas and getting attacked by 4 mudraptors that i spawned- Him](https://cdn.discordapp.com/attachments/179264667775008770/847130109744119858/unknown.png)

Me nearly at the same time
![Roaming the seas and getting attacked by 4 mudraptors that i spawned- Me](https://cdn.discordapp.com/attachments/179264667775008770/847130211098296320/unknown.png)

A few moment latter, him:
![Roaming the seas and getting attacked by 4 mudraptors that i spawned- Me](https://cdn.discordapp.com/attachments/179264667775008770/847130438803914772/unknown.png)

Docked at a station outpost (no bandits) - Him:
![Docked at a station outpost (no bandits) - Him:](https://cdn.discordapp.com/attachments/179264667775008770/847131514612219934/unknown.png)

Docked at a station outpost (no bandits) - Me:
![Docked at a station outpost (no bandits) - Me:](https://cdn.discordapp.com/attachments/179264667775008770/847131634011602964/unknown.png)

Docked at a station outpost (no bandits) - In the sub itself - Him:
![Docked at a station outpost (no bandits) - Him:](https://cdn.discordapp.com/attachments/179264667775008770/847131732175749195/unknown.png)

Docked at a station outpost (no bandits) - In the sub itself - Me:
![Docked at a station outpost (no bandits) - Me:](https://cdn.discordapp.com/attachments/179264667775008770/847131808059097178/unknown.png)

**Comment by Regalis11** [comment]
Thank you!

Unfortunately these values don't shed much light into the issue: it seems that there isn't one specific thing that's bottlenecking the game, but the performance appears to be worse than usual in all parts of the logic and rendering. I'm sorry to say that I don't have much ideas on what we could do to address this or diagnose it further, so I'd maybe suggest contacting Shadow themselves and see if there's something they can do about this at their end. :/

**Comment by Krisscut** [comment]
Alright, yes looking at the stats that's what we feared as well, it seems it's worse everywhere for some reason.

He will try to contact Shadow to see what they can do on their side, he will give this ticket number as reference, i will keep you updated !

Thanks for having a look :)

**Comment by Krisscut** [comment]
One lead that we will check if it's not some duplicate of https://github.com/Regalis11/Barotrauma/issues/2688 where it uses the integrated GPU of the CPU instead of the dedicated graphic card.
