### ISSUE TITLE
Unable to talk to the Husk Cultist event when returning to the NPC a second time

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#5899]
**Description**
You can't trigger the conversation when returning to the NPC a second time. Seem to happen because the NPC's custom interaction isn't set in `ConversationAction.Update()` because `speaker.ActiveConversation == this`.

**Steps To Reproduce**
1. Load the "huskcultist" event in the event editor.
2. Talk to the NPC and tell them that you'll get the eggs for them.
3. Talk to the NPC again without the eggs and finish the conversation.
4. Notice that you cannot talk to the NPC anymore even though the event hasn't been finished.

**Version**
dev branch (Regalis11/Barotrauma-development@fe8788d) - not sure if already present on unstable 0.1400.1.0

**Comment by ekqvist** [comment]
First issue should be fixed in Regalis11/Barotrauma-development@a333806

**Comment by ekqvist** [comment]
Originally listed two issues on this ticket, moved the second one to a separate ticket (#5902)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
