### ISSUE TITLE
[AI] Outpost guards start shooting at each other if one of them accidentally shoots a civilian NPC

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5900]
Trigger a event where the outcome is that you get attacked, once the guards comes in and starts to shoot at the event NPC notice that after the NPC dies the guards still have their weapons out, move around a bit and notice that the guards starts to shoot each other once they have a line of sight (no civilians on the way) to the guard that accidentally damaged a civilian.

I assume this can also be triggered by just attacking a guard in a crowded area so they accidentally shoot at civilians whilst trying to shoot at you, once your character dies they should start targeting the guard that misfired. 

Also as the guards shoots at each other they will do more misfiring to civilians and the target changes to a different guard, so it only ends once there's only one guard left.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@f6a6f11 and Regalis11/Barotrauma-development@0de59ed.

**Comment by Lithosagym** [comment]
Tested and confirmed to be fixed.
**Unfortunate, I might've been able to start Barotrauma Battle Royale again**

**Comment by Rokvach** [comment]
Closing
