### ISSUE TITLE
Battery power output dividing incorrectly?

### ISSUE THREAD

**Issue by BorrowedBullets** [Regalis11/Barotrauma#5901]
- [ ✓ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When hooking the output of a battery into more than one junction box, the power is divided among the boxes equally, instead of by load required.

Noticed this while play-testing the sub I'm building. The oxygen generator was not providing enough O2.
The vents were all linked to it, so it wasn't a output problem, it was a production problem.
Go to the electrical room, and start checking wires and junctions...
The junction box leading to the Oxygen Generator had a draw of 900, but a power 377.
The junction box next to it, hooked to the same battery, had a draw of 155, and a power 377.
The third junction box  hooked onto the battery had a draw of 75, but again, had a power of 377.

Basic math shows, for whatever reason, the battery has decided to take all three power draws, add them, and divide the output equally... 900+155+75=1130 & 1130/3=376.666666
To further confirm this, I tried removing the outputs of a box, but leaving the box itself connected. And sure enough, same deal.
A draw of 900, 0, & 75, results in each box now receiving 325 power.
Removing another box's outputs; Resulting in power draw of 900, 0, & 0, results in each box receiving 300 power.

**Steps To Reproduce**
Place a battery (default settings aside from changing the available charge to 2000).
Connect the battery outputs to more than one junction box. (2/3/4)
Place down a machine (I used an Oxygen Gen), connect its power to one of the boxes, and turn it on.
Swap to Test mode, and check the draw & power of any of the junction boxes.
The power provided to the junction will be equal to load, divided by the amount of boxes hooked up.
EG: A default Oxygen Gen. drawing 1000kw. Two junction boxes: Power 500. Three boxes: 333. Four: 250. Five: 200.

**Version**
"Embrace the Abyss" Patch v0.13.3.11 - Steam Build ID: 6614174 - Windows 10 Home

**Additional information**
Did the very basic troubleshooting of reloading the map, restarting Barotrauma, and loading up a different save.
It was the same result in every instance.
This doesn't _SEEM_ like it's intentional. And the wiki doesn't make mention of it...
But I do notice that none of the pre-made ships have their batteries output hooked to more than one source, so perhaps it is.

![power vs draw](https://user-images.githubusercontent.com/84906831/119816133-31d53300-bea1-11eb-9067-367cd208a9ea.PNG)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
