### ISSUE TITLE
[ Unstable ] Unit load device has no maxstacksize property.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5903]
**v0.1400.1.0 Unstable** - low priority xml tweak

Unit Load Device has no maxstack size defined, which is inconsistent with behavior of normal crate shelves. 
This means it would be possible to place any kind of stacked items in it if they are containable - without the normal '1 per slot' restriction as is the case with normal shelves.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4209bbc20f0c9978af0b076ea3649370507ca95

**Comment by Rokvach** [comment]
Tested, no issues.  Closing.
