### ISSUE TITLE
[ Unstable ] Sprite overlap on Medium Weapon Display Case

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5906]
Medium weapon display case's decorativesprite explosive items overlap with eachother and cause ugly sprite depth problems.

https://user-images.githubusercontent.com/55356135/119997791-1a2fa480-bf9e-11eb-8856-fefacb4e661c.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/20bcac6ad0ee0a4bfacbf5e13778a2cd3225ca4e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
