### ISSUE TITLE
"_m" hammerheads remain un-buffed

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5907]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seems like the new hammerheads have 325 health now, but the mission variants that i assume are supposed to be harder, have 300.

**Version**
v0.1400.3.0

**Comment by M61Dev** [comment]
Could we get rid of the mission variants altogether? It would be one less thing to maintain, and I'm not very fond of like of identical enemies having different stats

**Comment by itchyOwl** [comment]
The variants were requested by @ezjamsen. I'm fine with removing them, but the point of the variant system is that there's not much to maintain. In this case, there is manual work, because the variant buffed the health a bit.

I guess I'll buff the mission variant just a bit.

**Comment by ezjamsen** [comment]
Yep. Now we have the variants, it should be safe to remove them.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@57a7feb.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
