### ISSUE TITLE
[ Unstable ] Negative skill modifiers still display a positive sign in front of them

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5908]
A skill modifier with a negative value displays as "+-X" instead of just "-X"

![image](https://user-images.githubusercontent.com/55356135/120002477-e014d180-bfa2-11eb-9b5b-e9d03660b327.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/abeb210aa151c1fac42fbb674cab3d0c92f55e68

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
