### ISSUE TITLE
[Unstable] Vanilla beacon "dry room" sometimes floods, killing the event NPC

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5910]
**Description**
Title, here is a picture and save. It happened after a couple reloads.
![image](https://user-images.githubusercontent.com/59519434/120023245-d2d10480-bfed-11eb-942d-00e226d76044.png)
[Save.save.gz](https://github.com/Regalis11/Barotrauma/files/6562519/Save.save.gz)

**Steps To Reproduce**
-load level with beacon in it
-triggerevent shockjock2
-observe
-reload till it breaks

**Version**
Unstable

**Additional information**
Worked okay most of the reloads

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56ca06fec50221de29f6e92353473c72df0548cb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
