### ISSUE TITLE
[Unstable] shockjock2 is missing a TagAction

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5911]
**Description**
Event is looking for a trigger distance between 2 targets, but "player" tag is not specified in the event, leading to the NPC in the beacon station remaining idle:
![image](https://user-images.githubusercontent.com/59519434/120023505-29d6d980-bfee-11eb-9cb7-906d4aa934b0.png)

**Steps To Reproduce**
-load beacon level
-triggerevent shockjock2
-get within 200 units of tag: okelly
-nothing happens

**Solution**
![image](https://user-images.githubusercontent.com/59519434/120023606-52f76a00-bfee-11eb-9c57-8cb63aa9cb39.png)
This makes the event progress as it should

**Version**
Unstable

**Comment by danielasteljoki** [comment]
Fixed in 46c96b6.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
