### ISSUE TITLE
[Unstable] shockjock2 event NPC fails to attack player

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5912]
**Description**
The NPC in the beacon station fails to attack player because it has no weapon in it's inventory. Spawning a screwdriver to it fixes the issue and Offensive combat action ensues as intended by the event script.

**Steps To Reproduce**
-load level with beacon in it
-triggerevent shockjock2
-apply fix from #5911 so the combat action can happen
-observe

**Version**
Unstable

**Additional information**
NPC attacks player as usual if it has any kind of weapon. Even screwdriver helps.

**Comment by danielasteljoki** [comment]
Fixed among other changes in 0a3dd8c.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
