### ISSUE TITLE
broken door/hatch sprite depth in front of player

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5913]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/5103517/120031284-9ccc5a00-bfc6-11eb-8d98-091be6600227.png)
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.2 unstable

**Additional information**

**Comment by Regalis11** [comment]
This is intentional: the solid part of the door is rendered in front of the characters, and personally I don't see why that should change when the door breaks.
