### ISSUE TITLE
broken hatches can not be dropped past using down key

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5914]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
broken hatches act as closed hatches for purpose of walking

**Steps To Reproduce**
1. break a hatch
2. go on top of it

**Version**
0.14.2

**Additional information**
![image](https://user-images.githubusercontent.com/5103517/120031783-401d6f00-bfc7-11eb-8f0e-81ef16ab3b33.png)

**Comment by Leonidas-ai** [comment]
Maybe related to #5817

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9f48dbe874da99fc1c116e29113a5064679f90d7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
