### ISSUE TITLE
unstable watermark gone?

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5915]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Unstable version.x.y.z watermark is missing!!!
from sub editor/in game mode

**Steps To Reproduce**
open unstable 0.1400.2.0

**Version**
0.1400.2.0

**Additional information**
unplayable

**Comment by 3e849f2e5c** [comment]
This is intended, unstable watermark only appears when the game is compiled with the unstable preset and the last couple unstables are always compiled on the release preset to make sure that what is being tested is the exact same game that will go on stable.

**Comment by Tsunder** [comment]
ok, very cool!
