### ISSUE TITLE
Heavy performance load on motion detectors. 

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#5917]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Because motion detectors loop over each character and for nearby characters over each limb of the character, they tend to be the component with the highest impact on performance. With the changes in unstable relating to wall detection this impact can be even worse. 

motionsensor.cs already contains a [hardcoded variable](https://github.com/Regalis11/Barotrauma/blob/0b3fb5e44062eb42d13d735a31e89f8a083f8ae5/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/MotionSensor.cs#L11) that controls the update period to limit the impact slightly. It would be fantastic if the value of this variable was exposed to the sub editor. It would be even better if it was exposed to an actual wiring input. This would allow sub builders to make wiring turn motion sensors off altogether if they are not needed to save on performance.

**Comment by Regalis11** [comment]
I'm not entirely convinced the motion detectors are the issue. I did some quick profiling on this and checking what's near the detector seems to take a few hundred CPU ticks at most (= a few hundredths of a milliseconds), so it shouldn't have a noticeable effect even if there's hundreds of motion detectors in the sub. I also couldn't notice any performance problems by adding several hundred motion detectors to a sub.

I think the more likely cause are the circuits the motion detectors are connected to, especially if the sensors are sending continuous signals and the circuits are complex. Do you have some specific custom subs in mind where the detectors seem to be causing issues so I could do some more profiling/optimization using them?

**Comment by Regalis11** [comment]
But in any case, I agree that being able to modify the update interval would be useful (not just for optimization purposes), implemented that in https://github.com/Regalis11/Barotrauma-development/commit/d94f37708edce8594e663cab18558064fa461873.

I also made the game randomize the update timer when instantiating a motion detector so all of the detectors that have the same update interval aren't updated in unison.

**Comment by Working-Joe** [comment]
Awesome, I'll have a go at testing it next unstable release! I don't have a specific sub in mind, it's just sort of common consensus that you end up with a lot of lag if you have many detectors. (which doesn't happen with other large circuits). I'll see if I can find a few good examples though. 

One thing to note is that not just a large amount of motion detectors is a problem, but also the number of characters, submarines and level cells. I'd be curious to know how the amount of characters (whether they are in or outside detection range) affects results further

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
