### ISSUE TITLE
separatist vending machine bomb event does not give reputation

### ISSUE THREAD

**Issue by the1eyedduck** [Regalis11/Barotrauma#5920]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
completing the event does not give reputation (console log: "Faction with the identifier "separatist" was not found")
EDIT: it seem there is a couple more events with the misspelled (missing 1 "s")

**Steps To Reproduce**
trigger the event and complete it and no rep point with the separatists will be added

**Version**
0.1400.2.0

**Additional information**
it is likely just a misspelled from OutpostEvents.xml

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/49d3342

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
