### ISSUE TITLE
Incorrect Password text has no UI

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5921]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Incorrect password just shows as red text in the middle of the screen

![image](https://user-images.githubusercontent.com/5103517/120080004-c946ab80-c084-11eb-82a7-a5a591edacfe.png)

**Steps To Reproduce**
1. enter an incorrect password to a server

**Version**
0.13.3.11 stable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/992712479609ce0af63112e3ba4751396a9de2e9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
