### ISSUE TITLE
inventory icon bleeding

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5922]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 lashtear: there is a smudge in the inventory icon of IC-4 Block

![image](https://user-images.githubusercontent.com/5103517/120081888-d6b46380-c08d-11eb-9ee8-62a1ed90cc2e.png)
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
seems to bleed from bottom of welding fuel tank
![image](https://user-images.githubusercontent.com/5103517/120081936-1bd89580-c08e-11eb-82e3-367794fd06b9.png)
many inventory icons seem to have very low opacity borders (0-25ish alpha)
blur smudge inventory icon inventoryicon sprite

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fdbff916f9ece88d87d63f3349d0291c4aec40dd

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
