### ISSUE TITLE
[Unstable] Friendly/Neutral Bandit in Abandoned Outpost mission has quest marker, does nothing

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5928]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Friendly/Neutral Bandit in Abandoned Outpost mission has quest marker, does nothing

You can see the quest marker through walls

**Steps To Reproduce**
Launch an outpost mission until he spawns
Get close to the NPC, can't talk to it, nothing happens

![image](https://user-images.githubusercontent.com/73229309/120098893-bd1c2600-c138-11eb-9ee3-49437c39db76.png)

NPC has "stolen" inventory

![image](https://user-images.githubusercontent.com/73229309/120099025-8266bd80-c139-11eb-8a1f-df97c18c5433.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/04208337f38c445b823e12d813a292099c608143

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
