### ISSUE TITLE
Biome ambience tied to music volume

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5932]
![image](https://user-images.githubusercontent.com/47284081/120133841-63f5d600-c1bc-11eb-97f6-04f7f6ead6dd.png)
The biome ambiences are tied to music volume. A sizeable amount of players have the music turned off and will never hear the biome ambience. What a waste of sound design!
Some kind of support for ambiences in an official capacity with maybe a parameter like ambience="true" to make it tied to sound effect volume instead of music volume would probably be good, and also make a strong base for potential future soundscapes like ambiences in outposts.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/c4230f43e4e858f1ef1c9ce90a40439a5f9e3828

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
