### ISSUE TITLE
[unstable] Console error when loading a SP Campaign save

### ISSUE THREAD

**Issue by Mikolaj1900G** [Regalis11/Barotrauma#5933]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every time I load my save file (not at the concrete location, just every time I load it) a console pops up with a bunch of a repeated error message.

**Steps To Reproduce**
Load up the attached save file and load the game.

**Version**
v0.1400.2.0 (windows)

**Additional information**
The errors started once I finished a mission early in the campaign that resulted in a error that (if I remember correctly) said something about a failure to generate an outpost (unfortunately I can't remember which specific one it was). It then put me in a softlock-like situation from which I could only save myself by pressing the restart mission button. Once I did that, next time I finished the same mission everything worked properly but once I loaded the game next day the mentioned above problems started.

[Save.zip](https://github.com/Regalis11/Barotrauma/files/6569194/Save.zip)

![barrorum errorum](https://user-images.githubusercontent.com/57800630/120170441-40a14a00-c201-11eb-8e13-3de166fa7f5f.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2fc133875e17e0dc00fee3b29ecc0363c5d92d35

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
