### ISSUE TITLE
[Unstable] Cargo mission: You can deconstruct the content of crates and still get the reward

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5934]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can deconstruct the content of crates (medical, resources), and still deliver the crates for the full reward, as long as you leave one item in the crate

**Steps To Reproduce**
1. Select Medical transport mission
2. Deconstruct Saline
3. Reach outpost 
4. Keep the resources and get the reward

_Not the case with Compound-N which can't be deconstructed_

Cargo content being interactable is nothing but problems...  #5780

**Comment by Regalis11** [comment]
Thank you for the report! I'll reopen the previous ticket and close this one.
