### ISSUE TITLE
crash at the ending level

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5937]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashed mid way trough the ending level.

**Version**
Unstable v0.1400.3.0 Windows

**Additional information**
[insanity.zip](https://github.com/Regalis11/Barotrauma/files/6572231/insanity.zip)
[crashreport (17).log](https://github.com/Regalis11/Barotrauma/files/6572232/crashreport.17.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5754277

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
