### ISSUE TITLE
Issue with Repeatable Missions is not Solved

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#594]
I had a task to kill endworm after the other monster hunt on the same path. I quited the game and endworm just disappeared.

**Comment by Regalis11** [comment]
You mean issue #517? I tried reproducing it a couple of times just now, but everything seems to be working normally. Are you sure you saved before quitting?

**Comment by rico6822** [comment]
Yes, I have cash from previous task.

**Comment by Regalis11** [comment]
That's strange. Could you upload the save file in case I could find some clues there?

**Comment by rico6822** [comment]
Just wait.

**Comment by rico6822** [comment]
https://jumpshare.com/v/OMjsFj6Lag5cKy6ZKpzR

**Comment by Regalis11** [comment]
Which version of the game are you playing? That save file appears to be from a version before v0.8.1.10.

**Comment by rico6822** [comment]
0.7.0.1

**Comment by rico6822** [comment]
Wait.

**Comment by rico6822** [comment]
There is another one.

**Comment by rico6822** [comment]
https://jumpshare.com/v/nDuooGPp7O2NRdNe2iFn

It needs BTE 6.7 mod.

**Comment by Regalis11** [comment]
Could you describe what kind of bug you had with the latter save file? According to the save file you've completed a mission in all of the locations you've passed except the nitroglycerin mission in the last connection (from Thasus to Yelland), is that right?

**Comment by rico6822** [comment]
Yes, but your verdict makes me ask a question:

Does credits gained from a mission save automatically, but completed mission have to be manually?

**Comment by Regalis11** [comment]
When you click "save and quit", everything gets saved. So if the credit got saved the completed missions should've been saved too.

I may have an idea about what's causing this - the number of completed missions is increased in the getter of the connection's Mission property, which doesn't necessarily get called after completing the mission. I'll take a closer look at this tomorrow.

**Comment by rico6822** [comment]
Thanks.
