### ISSUE TITLE
Credits button inconsistent behaviour from other menu buttons

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5940]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Credits button disables the main menu, requiring the "back" button to be pressed
other buttons in the main menu that bring up a screen can still access the main menu (new game/load game/host server/settings)

**Steps To Reproduce**
press Credits in main menu

**Version**
0.13.3.11 stable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/720e4fc4b0d3dc1e9e32e600b3bcdd0921745126

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
