### ISSUE TITLE
can't read content packages section in server browser

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5943]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
content package section of server browser is super dark and small (only fits 2 lines for me, 2560x1440p, and the 2nd package is clipped)

**Steps To Reproduce**
check out a modded server in server browser

**Version**
0.13.3.11

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd1485b84d238acd4af500d76c35e00112689a63

**Comment by Rokvach** [comment]
This is more of a global UI issue I guess, but if you scroll up the content packages list it also scrolls up the server information, I think if your mouse is over the content packages list it should only scroll the content packages list and if its outside of the list it should scroll the entire info area. 

I can make a new ticket for this, but this is the only area in the game where this is currently happening so decided to write on this one instead.

**Comment by Rokvach** [comment]
Moving to Misc as I think the above could use some attention

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/22f060a4f72d17054118472ec7ba156d5624a2f1

**Comment by Rokvach** [comment]
Would it be possible to only focus the scrolling on the text box if the scrollbar is visible? Currently it can feel a bit confusing/buggy to see that you can't suddenly scroll just because your mouse is over the description which doesn't have a scrollbar in it.

**Comment by Regalis11** [comment]
Good catch, fixed that in https://github.com/Regalis11/Barotrauma-development/commit/3f64ed86d14f7dd0423871abe8415f2c37ac4b31

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
