### ISSUE TITLE
[Unstable] Lightcomponent of turrets

### ISSUE THREAD

**Issue by pabimuri** [Regalis11/Barotrauma#5946]
Since we will get a new possibilities to build a submarines with "placeholders" for turrets (turret hardpoints), we will get an issue: "draw behind subs" option is turned on by default. 
My friend noticed that bought turrets wont light exterior structures, making them just dark places. Can we turn off "Draw behind subs"?

https://steamuserimages-a.akamaihd.net/ugc/1744561997147781668/2DE6020687805429F8C02D260E6FE6A6D495002D/ not ok
https://steamuserimages-a.akamaihd.net/ugc/1744561997147783598/33257F8B7C414E94A8E5516DBDC643214509B79D/ ok

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c644639e5d84c033cae11650bfd4e7e65f3dde5c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
