### ISSUE TITLE
You can get missions that send you back into radiation

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5947]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can get missions that send you back into already irradiated territory

![image](https://user-images.githubusercontent.com/73229309/120301614-55e3aa80-c2cd-11eb-90f2-7f924ff17c95.png)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2420f2a367f53e17fc11f15626dfc0689188ba23

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
