### ISSUE TITLE
Missing attribute "enabled" in gamesession.xml makes it misleading/hard to disable Jovian Radiation

### ISSUE THREAD

**Issue by KelvallRogers** [Regalis11/Barotrauma#5950]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
gamesession.xml is missing attribute "enabled" on tag "Radiation" in save games with Jovian Radiation, which makes it confusing to disable.
`<CampaignSettings radiationenabled="false" />` does not seem to be considered/utilized by the game for controlling Jovian radiation, this is likely not intended. 

**Steps To Reproduce**
Produce a new save with Jovian Radiation enabled, and a second new save with it disabled. Decompress each save and compare gamesession.xml. You will see that the `<Radiation amount="-200" enabled="False" />` is on the game with disabled, and in the other enabled save it is missing `<Radiation amount="0" />`

**Version**
Latest Windows stable - Steam (June 1st)

**Additional information**
Adding "enabled="True"" would make it much more clear to people who want to disable the Jovian Radiation as the `<CampaignSettings radiationenabled="false" />` DOES NOT disable the radiation

**Comment by 3e849f2e5c** [comment]
> \<CampaignSettings radiationenabled="false" /\> does not seem to be considered/utilized by the game for controlling Jovian radiation, this is likely not intended.

This is intended. CampaignSettings is only used for passing starting arguments to the campaign save file which currently only contains whether the game should create the save file with radiation or not so it's only used at the start but it keeps getting saved into the save file because of technical reasons.

**Comment by 3e849f2e5c** [comment]
Made <Radiation> element always save attributes even if they are set to the default value in https://github.com/Regalis11/Barotrauma-development/commit/180bb0ca003b504ac3ba30df684bf8cc6a71edc2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
