### ISSUE TITLE
missing console commands from help

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5951]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
help command doesn't list dumptofile, money

money and dumptofile also have no help response text

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.2 

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b677e2304083bd521a583fa5746ce3ae49efcb2c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
