### ISSUE TITLE
flipped submarine's docking ports don't drain fully

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5955]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
a flipped submarine's (i.e., pvp) shuttle docking port dynamic hull never drains

![image](https://user-images.githubusercontent.com/5103517/120397967-4d0fca80-c307-11eb-9c91-05b8dbdc4b25.png)

**Steps To Reproduce**
flood the dynamic hull area in a flipped sub

**Version**
0.14.2

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e421f321b6afac532e790667cbfc23ea1cea7356

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
