### ISSUE TITLE
dynamic hulls that are on fire stay on fire

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5956]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
a dynamic hull that was put on fire stays on fire until the hull is destroyed
flooding the hull with water does nothing, fire returns after the water is gone

**Steps To Reproduce**
set a dynamic hull on fire (flamer, fire command, incendium grenade)

**Version**
0.14.2

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/caa03e1d2a62189fd21dda63726b1c16b030f287

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
