### ISSUE TITLE
[Unstable] 'event psychosis artifact' is not hidden in editor

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5958]
The custom coded variant of the psychosis artifact is not hidden in editor, so two different items named 'psychosis artifact' appear in sub editor which could be a bit confusing.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ecb39fc707808ead845bff4c7da0b6e47e45881f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
