### ISSUE TITLE
Crashed while alt-tabbed away from ship editor.

### ISSUE THREAD

**Issue by chemicalvamp** [Regalis11/Barotrauma#5959]
**Description**
Crash with bug report.

**Steps To Reproduce**
Enter ship editor and alt-tab to a different window for awhile.

**Version**
see your bug report. (2) Should be a clean slate of nothing but launching the game and alt-tabbing out.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6581310/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/6581311/crashreport.2.log)

**Additional information**

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833
