### ISSUE TITLE
Crates From Stores Don't Disappear After Changing Location in Campaign- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#596]
I'm not sure if that's intended, but if not an interesting solution would be having only those store crates removed, only if they remain in cargo spawnpoint hull they came from. Those in other hulls will became player's personal storages.

**Comment by Regalis11** [comment]
It is intentional - the new items can be stored in the container they come in, or moved somewhere else and the container thrown away or used for something else.
