### ISSUE TITLE
BUG: Docking Door and Unable to Weld

### ISSUE THREAD

**Issue by BigBrendo11** [Regalis11/Barotrauma#5963]
I've recently played a lot of Barotrauma in the last couple of weeks, and I've encountered some bugs that weren't present during the beginning of my private, multiplayer campaign.

When docking to outposts none of the crew can re enter the sub because the docking door that leads to the sub is locked, and we can't use a crowbar, or plasma cutter to enter. This issue started about 10+ hours into our campaign, and this issue occurs regularly, however, there are some outposts where the docking door functions normally and it stays open. (Note: This issue is only present on outposts, not abandoned outposts)

Another issue that wasn't present early in our campaign was being unable to weld. NPCs and bots can weld the sub normally, but when it comes to players trying to weld it usually doesn't work, (it never works for me, the host, and only consistently works for one other player, but no one else). We've tried using new welding tools, swapping the welding tanks, and it doesn't work. Sometimes the animation to the welding doesn't appear, and it doesn't weld, and other times the animation to weld does appear but it still doesn't weld. 

**Note** that the docking door bug that I've encountered is only present in one of my campaigns, and hasn't appeared anywhere else & the welding tool bug is also only present in the same campaign also. Both work fine in other saves in campaigns and other modes.

**Comment by Regalis11** [comment]
Would it be possible to send us the save file where this occurs? It'd make it much easier for us to reproduce and diagnose the bug. Note that the save files need to be .zipped to attach them here, because GitHub doesn't support the .save file extension.

Thank you and sorry for the inconvenience!

**Comment by BigBrendo11** [comment]
Here is the save file, let me know if this works; if it doesn't I'll make sure to send a working one.
[THE ONE.zipped.zip](https://github.com/Regalis11/Barotrauma/files/6601901/THE.ONE.zipped.zip)

**Comment by BigBrendo11** [comment]
> Would it be possible to send us the save file where this occurs? It'd make it much easier for us to reproduce and diagnose the bug. Note that the save files need to be .zipped to attach them here, because GitHub doesn't support the .save file extension.
> 
> Thank you and sorry for the inconvenience!

**Comment by civilCornball** [comment]
Was this in another version? I'm unable to load the save file.

Not part of the staff btw. Just really, really bored.

**Comment by BigBrendo11** [comment]
This was in the most recent patch.

**Comment by Regalis11** [comment]
Sorry for the super late reply!

There seems to be some custom wiring in the docking hatch circuit that prevents it from working correctly: namely, the wire from one of the delay components to the hatch seems to have been removed.

**Comment by BigBrendo11** [comment]
It's all good! I really appreciate you taking the time to figure out the issue, I realize you guys are very busy and dedicated to your work so again, I appreciate the reply and that you found the solution to our problem.

Have a good one, and keep up with the fantastic work you guys all do,

Cheers,

________________________________
