### ISSUE TITLE
Certain light sprites darkening the entire item if the alpha color has been changed ?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5964]
Some machines and items have a darkening or discoloration when their light component's alpha channel is used.

Shuttle navigation terminal unpowered
![image](https://user-images.githubusercontent.com/55356135/120729459-3014fc00-c4ad-11eb-864d-0d7f96780d2e.png)
Shuttle navigation terminal powered, light overlay seems to darken the whole sprite instead of behave as additive.
![image](https://user-images.githubusercontent.com/55356135/120729479-3dca8180-c4ad-11eb-8e2c-0e7658cd6421.png)

Nuclear reactor
![image](https://user-images.githubusercontent.com/55356135/120729642-a87bbd00-c4ad-11eb-923f-1f5f5a1e47ad.png)
Nuclear reactor running
![image](https://user-images.githubusercontent.com/55356135/120729656-b29dbb80-c4ad-11eb-9024-e3b7d00b2b42.png)

However this is not true in the case of the normal navigation terminal or the outpost nuclear reactor.

**Comment by Regalis11** [comment]
Is there a reason to set the alpha of these light components above zero? It makes the light texture (which includes those dark edges) visible, which causes the lighting to look off.
