### ISSUE TITLE
Windup particles for laser gun doesn't match when swinging

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5965]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the turret the gun is on swings while the pulse laser is winding up, the particle effects don't come from the muzzle

**Steps To Reproduce**
fire up the pulse laser while turning the turret

**Version**
0.14.3 unstable

**Additional information**

https://user-images.githubusercontent.com/5103517/120732520-78cfb380-c4b3-11eb-921a-331465f76ccf.mp4

**Comment by Regalis11** [comment]
They do come from the muzzle, but because they don't follow it's movement, they appear to trail behind it. I think this is such a tiny issue that I don't see the need to address it.
