### ISSUE TITLE
double front on pirate humpback 

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5966]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pirate humpback has a really tanky nose + collision issues from having to destroy 2 layers of nose 

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.3

**Additional information**
suggested solution: remove the non-pirate front A, as the pirate nose is huuge and completely hides the regular nose

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/880691f74ca99a91532872bc00f57ad58da7285d

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
