### ISSUE TITLE
Cave Oxygen depervation lasts until returning to sub.

### ISSUE THREAD

**Issue by ImperialCommandantOtter** [Regalis11/Barotrauma#5967]
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
7 player multiplayer no mods on the R-29.  Went exploring a cave looking for an artifact and to clear a crawler nest.  Upon entering the cave we encountered the oxygen removal gas however when continuing away the oxygen removal effect stayed until a player would return to the sub.
[Unstable(OliverCap).zip](https://github.com/Regalis11/Barotrauma/files/6596309/Unstable.OliverCap.zip)

**Steps To Reproduce**
Unknown how to reproduce but save file will is included.
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows version for all players involved.
Unstable version: V0.1400.3.0

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d2db6c61b785cb10df612bf64839c5a855ac9c3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
