### ISSUE TITLE
(Custom) Beacons don't need to receive a signal when unpowered

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5969]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using a custom beacon station, you only need to flip the switch to validate the mission
It doesn't matter if the nagivation terminal is powered or wired

**Steps To Reproduce**
1. In Barotrauma\Content\Map\BeaconStations, paste:
[BeaconCeiling.zip](https://github.com/Regalis11/Barotrauma/files/6597768/BeaconCeiling.zip) and rename it into Beaconstation1.sub

2. Launch a beacon mission

3. Unwire the terminal 

4. Flip the sonar switch (message appears)

5. Dock to the end of the level and complete mission

**Comment by ubertpendragon** [comment]
I will rewrite the ticket as I need to test further 

The issue has to do with a custom beacon, power supply AND custom transducer signal

**Comment by Regalis11** [comment]
The transducers are completely decorative atm and they're not required to complete the mission. We have an existing ticket about this: https://github.com/Regalis11/Barotrauma/issues/4278
