### ISSUE TITLE
Shooting Something by Targetting in Front of it or Behind it Misses it- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#597]
If your revolver or any other rangered ballistic weapon will aim at your target, but it will aim behind or in front of it, it will miss. 

This bug can be explained with that player character is trying to shot something behind it completely ignoring what is blocking it from the front as he intentionally spares the target in the front to terminate what is behind it.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this. Ranged weapons don't care how far your cursor is, they just launch the projectile in the direction of the cursor.

**Comment by NilanthAnimosus** [comment]
I believe this is actually an issue of networking syncing and lag + server side character position vs client side character position.

Firing too close to the target (where it may have already passed you server-side) or near another target (where it could be past the other character server-side already by the time the shot from the client reaches the server and travels the distance) will easily cause this noticable effect of hitting Guy A but damaging guy B behind him and such.

**Comment by rico6822** [comment]
I have something else about it to say:

If you target something with your revolver behind it (background), besides of it being on your line of fire you're not gonna hit it, instead you have to point your mouse cursor directly on the target to have 100% hit chance.

**Comment by NilanthAnimosus** [comment]
Do note weapons have skill and revolvers have a very high skill to shoot, which when you fail the shot your bullet arcs somewhat into a different direction.

**Comment by rico6822** [comment]
Yes, but my target had large sizes I shouldn't miss.

**Comment by NilanthAnimosus** [comment]
The collider is the only aspect of characters that is actually synced iirc, not the animation or even the rotation of the characters limbs is strictly synced.

"Shouldnt" miss and missing are two different things, its still possible for this to cause misses, I generally play using a client-hosted server while using a separate client to play (Instead of play yourself) and have came to notice the differences at times over many hours of play.

**Comment by rico6822** [comment]
Alright here comes something really worth attention:

If you use a stun baton on someone or something, stun baton touches it, but your mouse cursor is far behind it stun baton will actually miss.

**Comment by Regalis11** [comment]
I'm pretty sure the problem with the stun baton is also related to inaccuracies network syncing, because melee weapons don't use the cursor position in any way.
