### ISSUE TITLE
gun camera offset too low

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5973]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the camera offset / POV for when manning (coil)guns isn't centered on the barrel/ aim reticle focus point, but lower. this causes shadow issues where the gun can aim at something that is not visible due to shadows

the POV should probably be at the rotation point of the gun, or even somewhat beyond it, to .

**Steps To Reproduce**
place a coilgun near a shell, line of sight on

**Version**
0.14.3 unstable

**Additional information**
example: coilgun has fine aim at a shell, but the shadow blocks it
![image](https://user-images.githubusercontent.com/5103517/120862979-d4ec1380-c557-11eb-83fc-0d3bbfec03c1.png)

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
