### ISSUE TITLE
Press E on a non-interactable deconstructor in editor cause crash

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#5977]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pressing E on a deconstructor set to non-interactable after saving it cause a crash.

**Steps To Reproduce**
1. Start sub editor
2. Put a deconstructor in
3. Set it to non-interactable
4. Save it.
5. Load the save.
6. Press E on the deconstructor
7. Crash

**Version**
Unstable 0.1400.3.0

**Additional information**
Crash report here, seems to be a null exception error
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/6602563/crashreport.3.log)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/01d56de9bf77148487ffedb8fe7d11bd8ab7768a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
