### ISSUE TITLE
Appearance of Hull Lines in Editor Is Weird

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#5979]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the "hulls" layer is enabled, the intensity of the hull lines increases over time.
See the following video: [https://jlobblet.s3.eu-west-2.amazonaws.com/2021-06-05+14-13-40.mkv](https://jlobblet.s3.eu-west-2.amazonaws.com/2021-06-05+14-13-40.mkv)

**Steps To Reproduce**
1. Open the sub editor.
2. Enable the "hulls" layer.
3. Load a submarine.
4. Observe.

**Version**
0.13.3.11

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e7f967ef0accb6a4dfa00c61c51ddcac9b58d371

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
