### ISSUE TITLE
Windowed mode (And perhaps other modes) when minimised still takes game input

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#598]
This is using vanilla 0.8.1.11 with no modifications on windows 7 64bit

I am not entirely sure as to why, but my character still takes my keyboards input as if it was in focus once it has been minimised, though if left visible (not minimised) it will lose focus and not accept keyboard input.

I have numerous times tabbed back in to find myself with a console open full of command spam from typing.

**Comment by Rokvach** [comment]
This issue has already been fixed, closing.
