### ISSUE TITLE
[0.1400.3.0] engine propellers do not deal any damage

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#5981]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
engine propellers do not cause damage to living creatures in any state (idle, working)

**Steps To Reproduce**
1. open sub editor
2. select any submarine with correctly installed propellers hitboxes (in my case hemulen)
3. go to propellers area
4. order character to wait there
5. change your char to another crewmate and make submarine move
6. watch your original character not getting any damage from propellers
**Version**
Unstable 0.1400.3.0, Windows 10 Pro

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/31bfd5e1b93615768f7beb45b4058b171a4f001b

**Comment by Lefttroll** [comment]
@Regalis11 thx for fix, but can we avert this 680e78ecfd? We dont really need nerfs of damage for propellers + there is a bubble warning + most submarines already hightlight engines!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
