### ISSUE TITLE
Particles from pumps aren't affected by mirror X\Y and rotation

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#5983]
- [x] I've searched the issue tracker to check if the issue has already been reported.

**Description**
Particle effects from pumps (like bubbles and water streams) are not change directions when pumps are mirrored with Mirror X\Y and or rotated. This affects both standard pumps and small ones. 
![image](https://user-images.githubusercontent.com/62324831/120910099-9ecda180-c6c7-11eb-98cd-df6baf8be720.png)

**Steps To Reproduce**
Place both types of pumps in sub editor and their mirrored\rotated versions and turn them ON and set them to pump IN water.

**Version**
Tested on:
Unstable v0.1400.3.0
Stable v0.13.3.11

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8bf0efcb3c6248d1d6853e351a63e9aa51422c7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
