### ISSUE TITLE
Crash when i start a mission

### ISSUE THREAD

**Issue by ZalaraLion** [Regalis11/Barotrauma#5984]
When i start mission my game crashed

Game version 0.13.3.11
Windows 
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/6604092/crashreport.5.log)
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/6604093/crashreport.6.log)
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/6604094/crashreport.7.log)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1833
