### ISSUE TITLE
[Unstable] Mods can no longer override vanilla jobs

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#5987]
**Description**
Vanilla jobs can be overriden in current stable, but they dont get overriden in unstable. Here is a testmod where I tried it:
[UnstableTest.zip](https://github.com/Regalis11/Barotrauma/files/6604824/UnstableTest.zip)
It should modify captain to only have the veteran variant and add wrench to his kit. It does neither.

**Steps To Reproduce**
-try to modify vanilla job prefabs
-see that it has no effect in game

**Version**
Unstable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1cc966273655d88bdd1c75d6168a979672856b92

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
