### ISSUE TITLE
Hitscan Projectiles don't function properly when "shot" from Characters

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5989]
[Bug]
You can reproduce by making spinelings spawn revolverrounds in their firing status effects. They don't seem to fire or target correctly at all.
They do seem to occasionally leave tracer particles, but they fly way across the screen

**Comment by Regalis11** [comment]
Could not reproduce, the projectiles seem to be working in both single player and multiplayer:
![image](https://user-images.githubusercontent.com/14351070/121029008-ebd97280-c7b0-11eb-9412-e983c863662e.png)

Which version did you test this in? Single player or multiplayer?

**Comment by hubismal** [comment]
This was on the latest unstable in the sub editor test mode. I will try again.
