### ISSUE TITLE
wrong out for "fuel" in reactor

### ISSUE THREAD

**Issue by pofigist1** [Regalis11/Barotrauma#5990]
i need a warning - 'uranium rod is low charge',
but
 the only one out is summ of max capacity(or 0 if empty) all rods in reactor
 not CURRENT capasity, but MAX capasity
pls fix it.
and we need a campain for clown)

**Comment by mygamingaccount** [comment]
Fuel out is the sum of the thermal output of the fuel rods, not the remaining fissile material.

**Comment by pofigist1** [comment]
Thank you. Sorry for wasted time(
