### ISSUE TITLE
Security Officers Remove Power Cell From Headset To Power Baton

### ISSUE THREAD

**Issue by Tactical-Shrubbery** [Regalis11/Barotrauma#5991]
Description:
When an NPC security officer's stun baton runs out of juice, they pull the cell out of their headset to power it, which leaves them unable to speak on the radio.

Reproduce:
1) Have security officer use baton
2) Attempt radio communication

Version:
I am on v0.13.0.11, Windows 10, only submarine files downloaded from the workshop.

**Comment by Rokvach** [comment]
This issue has already been fixed for the upcoming update. Closing
