### ISSUE TITLE
CauseSpeechImpediment no longer works

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5992]
[Bug]
The CauseSpeechImpediment property, used in afflictions of type alieninfection/huskinfection to prevent the users speech from being restricted, no longer functions properly in the latest unstable.

Many mods use this feature to allow husk afflictions to be leveraged to give users new abilities. As a result, many mods will be broken by this.

**Comment by 3e849f2e5c** [comment]
Wasn't able to reproduce by adding the property to vanilla husk infection. Can you elaborate what "no longer functions properly" means? or did you perhaps not write it in all lowercase since the attribute is case sensitive.

![](https://kosblue.com/e/nyyti.png)

**Comment by hubismal** [comment]
It works now but I swear in the past it had to be capitalized and wouldn't work if it were lowercase. Maybe I've finally lost it. Thanks.
