### ISSUE TITLE
Crash while exploring alien ruins with a bot

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#5998]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game can crash when exploring alien ruins with bots.

**Steps To Reproduce**

1. Load the save attached below
2. Pick up a diving suit and order one of the bots to follow you
3. Navigate or teleport outside the alien ruins located below the main path further along the path
4. Enter the ruins and go to the room with the chest, motion sensor, coil, and generator.
5. Once that room is filled with water, move to the hatch at the bottom of the room and have the bot follow you there.
6. Open the hatch to the dry room below and watch the game crash as your characters are dropping through the hatch.

[Save](https://app.zenhub.com/files/93301055/4fcf10b3-92b2-45e1-a9ea-73b5e7992e73/download)

**Version**
Unstable v0.1400.3.0

**Comment by ekqvist** [comment]
This can basically happen any time a bot is entering a dry room (or any room with not enough water for the bot to require a diving suit) in the ruins as the bot will check if they should remove their diving gear. It will then throw a null reference exception. But with the steps above, it should be possible to reproduce this reliably.

**Comment by ekqvist** [comment]
The fix has also been cherry picked to the release branch now

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
