### ISSUE TITLE
[ Unstable ] Canceling a turret installation does not revert it's icon.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#5999]
Buying a hardpoint turret and then canceling your pending upgrade does not update it's icon back to the original item.

Steps to reproduce:
- Purchase a hardpoint turret installation upgrade
- Cancel pending installation

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/25eeb3e68865095240a5cb07a73b966c18af2a1d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
