### ISSUE TITLE
LOS shader gives inconsistent and unsightly results 

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6000]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
To put it blunt, the current LOS shader fails in most circumstances where two colliders overlap. 

To give an example, take this back of a submarine I made:
<img src="https://user-images.githubusercontent.com/50582661/121258652-743e3d00-c8af-11eb-8419-22b7e4d87d0c.png" width="500">
This looks fine in the editor. But once you open it in game, it looks like this: 
<img src="https://user-images.githubusercontent.com/50582661/121258915-c67f5e00-c8af-11eb-9296-8fafd8e86b8b.png" width="500">
Which looks rather unappealing. To make things worse all the triangles move with the character just to drag that extra bit of attention to it. 

It is only very rarely possible to mitigate these problems by very precisely aligning the colliders, but with most shell combinations it is outright impossible. Removing these artefacts usually requires redesigning parts of a sub over and over until you're lucky enough to have somewhat acceptable spikes.

Note that I assume this issue is known given how long it has been in the game. I'm reporting it anyways because I could find no open issues about it while it is one of the biggest eye-sores in sub building. This is also one of these topics that keeps coming up again and again in the sub-building channel on discord. 

As daunting of a task it may be to rewrite the LOS shader or even some part of the rendering code to fix this, I think it would be worth it given that it affects all submarines including the vanilla subs. It may also affect gameplay somewhat since there will be less spots where you can incorrectly see outside of the submarine, which currently kind of breaks the immersion of being inside somewhat (at least for me :).

**Steps To Reproduce**
I've attached the specific sub to which the images belong [here](https://github.com/Regalis11/Barotrauma/files/6619639/sub.concept.A.zip).

**Comment by Working-Joe** [comment]
Because I didn't just want to file a complaint I've been looking a bit into ways in which the shader could be improved, and I think the following approach may achieve results very similar to the existing LOS shader but without the weird spikes that the current shader has:

![image](https://user-images.githubusercontent.com/50582661/121345524-3ed43680-c925-11eb-8feb-89c9b2eb6ad1.png)

The end result will then look something like this (note that I did this mockup in paint.netso some things, especially the zoom blur, are not ideal)

![image](https://user-images.githubusercontent.com/50582661/121346091-f49f8500-c925-11eb-8964-94042ba19876.png)

The first step is rendering the geometry of all items that are opaque to a separate layer. Something like this is necessary because the colliders are not aligned with the sprites which is part of what breaks the current shader. (I suppose that alternatively the colliders could be rendered if the walls were updated to have multiple colliders that align better with the sprite). I'm not sure about the rendering pipeline of baro but usually this is just done with a separate camera. Overhead should be fairly small since only the walls have to be rendered and the albedo/lighting of the textures does not matter. 

The next and probably most complicated step is to create a shadow map. What makes things a bit more complicated here is that you want to create a shadow map that excludes the geometry - that is, the shadows should start after the geometry ends but should overlap with any geometry beyond that. Otherwise you'll run into trouble with the next step. 
I found [this blog post](http://www.catalinzima.com/2010/07/my-technique-for-the-shader-based-dynamic-2d-shadows/) that I thought had an interesting approach. It would have to be modified so that instead of finding the first wall from the player you find the first gap after a wall, though. This could involve changing the reduction part slightly to instead of the minimum finding the minimum only if there is a decrease in the adjacent pixels (or in the pixel before it, otherwise you may miss the gap).

Next, the shadow on the geometry should be blurred to allow looking some distance into walls so that walls are not just opaque black blocks. I think this could be done using some sort of outward radial/zoom blur where you average the value of a pixel with the values on a short line towards the head of the character (not away from, this will cause shadows to blur towards the character too. Also make sure to clamp the line near the character head!).  Because this involves blurring over a line it could be a bit cheaper than usual 2D blurring shaders. 

To get the penumbra effect, it may be possible to use a radial blur, which is for each pixel the average of the values on a ring sector. Only interesting part here is that you'll want to add/subtract this average to the pixel rather than replacing it, because the areas that are in full shadow should not be affected.

**Comment by cshingle** [comment]
[This PR](https://github.com/Regalis11/Barotrauma/pull/8570) appears to be related to this issue.

**Comment by Working-Joe** [comment]
Not unlikely since I wrote both :)

I'll link to the issue in the PR

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
