### ISSUE TITLE
tiger threshers going trough hull easily

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6001]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i was playing singleplayer so the issue isn't desync, apparently tiger thresher's tail can easily go trough the hull and you can damage it, if you stun it while moving the sub into the direction where the rest of it's body is, it'll teleport inside.

**Steps To Reproduce**
get the tiger thresher to focus on a flat wall, then move your sub full speed in the direction where the thresher is.
if the issue is happening you will see the thresher's tail poking inside the ship, if you stun it, the tiger thresher will teleport inside.

**Version**
v0.1400.3.0 Unstable

**Additional information**
I've seen it happen to other creatures but tiger thresher is the only one that seems to get the issue constantly.
![bruh](https://user-images.githubusercontent.com/55637865/121268663-c160e580-c894-11eb-875f-a47600aca391.png)

**Comment by Regalis11** [comment]
I unfortunately couldn't get this to happen, not even by moving the sub at a huge velocity using the IJKL keys in a debug build. I'll do some more testing with other subs to see if I can repro it, but if you or anyone else can get it to occur reliably, a screenshot with debugdraw enabled could give some more clues on why this is happening. My first guess would be that the monster's collider has ended up far away from the ragdoll, which should make the game disable the ragdoll's collisions and force it back to the collider (which is probably failing somehow here).

**Comment by Ek-Videogames** [comment]
A variety of enemy 'tunneling' physics behavior can be observed. Not sure if its relevant to this particular bug, but the hull instancing code that is designed to "Push characters back inbounds if they somehow partially clip into the exterior shell of the submarine" can sometimes be a bit overzealous and try to 'clip back inside' a monster that's outside the sub.
*( For a specific common example, 'crawlers & raptors when impacting around areas of sloped/curved hulls.' )*

**Comment by LePiromano** [comment]
he didn't get in a lot like the last time this happens, i'll try to get a better one

![image](https://user-images.githubusercontent.com/55637865/121764172-41e34880-cb18-11eb-817c-fe2bdcc10308.png)

**Comment by LePiromano** [comment]
got a good one
![image](https://user-images.githubusercontent.com/55637865/121934322-8f7cd280-cd1d-11eb-8860-a01003e56cbf.png)

**Comment by Regalis11** [comment]
Hmm, still no luck .:/

@Ek-Videogames 
> Not sure if its relevant to this particular bug, but the hull instancing code that is designed to "Push characters back inbounds if they somehow partially clip into the exterior shell of the submarine" can sometimes be a bit overzealous and try to 'clip back inside' a monster that's outside the sub.

What exactly do you mean by this? To my knowledge there's no logic like this in place.
