### ISSUE TITLE
Atan Component is not working properly

### ISSUE THREAD

**Issue by EchoSaber-114** [Regalis11/Barotrauma#6003]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
      Four coordinates (x, y), respectively (-1, -1), (1, -1), (1, 1), (-1, 1). Under normal circumstances, the output of the atan component should be as shown in Figure 1-1, but in the current version, it becomes as shown in Figure 1-2. In addition, when I change the input of the two memory elements of the (1,-1) turret in the game, it may become normal. However, the (-1,-1) and (1,1) turrets cannot be restored to normal no matter how the input is changed, and it will always remain at 0°.
      All turrets are set with a rotatable range of 0~360° as shown in Figure 2.
      Wiring shown in Figure 3.

**Steps To Reproduce**
      Use Atan components and use vector input (coordinate x and coordinate y), It does not work at certain values.

**Version**
v0.13.3.11  Windows

**Additional information**
This problem did not occur in the previous version
![1-1](https://user-images.githubusercontent.com/79043871/121350631-7fe83d00-c95d-11eb-9e5f-0541bd8a1601.png)
![1-2](https://user-images.githubusercontent.com/79043871/121350650-837bc400-c95d-11eb-801d-32e2237a3409.png)
![2](https://user-images.githubusercontent.com/79043871/121350666-85458780-c95d-11eb-8884-0e12b8b93459.png)
![3](https://user-images.githubusercontent.com/79043871/121350683-870f4b00-c95d-11eb-9f2f-be8e6013e206.png)

**Comment by Regalis11** [comment]
Thank you for the report! Turns out the way atan components handle the separate x/y inputs was bugged, and they'd only work correctly when using the "signal_in" connection. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e416846bbf6f6a2be3928cc410a76899773d67d5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
