### ISSUE TITLE
missalligned lighting sprite for command items

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6006]
- [no] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the sprites on the humpback's navigation terminal and status monitor (and possibly other subs) seems to be off.

**Version**
v0.1400.4.0

**Additional information**
![image](https://user-images.githubusercontent.com/55637865/121382686-3b3cb180-c91d-11eb-946f-6e349f6b94a2.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cd56d0c54efd10bc6c8827afaaa14a923fef2943

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
