### ISSUE TITLE
Dynamic hull has no name

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6007]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The dynamic hull between docking ports have no name. Radio reports will be like "Hull breach in  !" and the hull will have no name in the status monitor.

**Steps To Reproduce**
Make a dynamic hull using a docked shuttled

**Version**
0.14.3

**Additional information**
Maybe name it docking port, or copy the name of the hull it attaches to?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f8e30c214bece231002ed1f24076e41d67ed0f29

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
