### ISSUE TITLE
[0.1400.3.0] Small Circuit can crash servers

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6009]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
a small little circuit can easily make whole server crash or make it unplayable

Basically, take any trigonometric function and loop the fractional calculations (they are all in double).

**Steps To Reproduce**
use provided ItemAssemblies to see what it can do

**Version**
Stable and unstable [0.1400.3.0], Windows 10 pro

**Additional information**
schemes: both crash and ddos one
[ItemAssemblies.zip](https://github.com/Regalis11/Barotrauma/files/6626348/ItemAssemblies.zip)
sub file versions:
[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/6626422/Submarines.zip)

**Comment by Gast9ra** [comment]
Crash work on "sin, cos, acos, asin, atan, tan" component. If in component two wire on signal_in and one wire signal_out, tree wire on signal_1 in cabel box, crash not work. If in component one wire on signal_in and two wire signal_out, tree wire on signal_1 in cabel box, crash work.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/pull/2736/commits/175804c63e3a1054dece8141fb251c1e1f2794ad

**Comment by Rokvach** [comment]
Tested with the provided subs and didn't spot any issues then I tested it with the Barotronics - Turrets and all of them worked correctly both in singleplayer and multiplayer. 

For reference:
https://steamcommunity.com/sharedfiles/filedetails/?id=2483236185

**Comment by Gast9ra** [comment]
Crash work only with Junction Box and trigonometric component. Turrets not use.

**Comment by Working-Joe** [comment]
The test with the turrets is to check if other circuits are not affected by the changes.

**Comment by Gast9ra** [comment]
Ok
