### ISSUE TITLE
level depth is actually not deep enough to remove items for MaxEntityDepth

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#601]
almost all levels now have a sea floor, volcanic floors and other such, while the maximum entity depth is -300000f these floors are never below this value, so this is actually code that no longer does anything.

inside the level generation parameter file no sea floor goes below -300000f, the lowest one is exactly this, so no item/submarine can pass below the distance off the bat.

I think the level floor should be tweaked to be beyond the entity deletion distance, either by increasing the depth of levels or by slightly nudging the MaxEntityDepth.

Most item deletion/removal/disable from maxentitydepth is server-sided, and I've been customizing values like Max Depth before pressure crush so it would be nice if these were not tweaked too harshly

Additionally the setting "SeaFloorDepth" in level generation params also defaults to -300000.0f

just to add a small footnote to this - I allow servers to modify the max pressure depths as I introduced mechanics which changed the pressure crush from an immediate set of explosions to slow small chances of leaks and cracks forming - where the characters had a different internal submarine max depth to the external so they could "fight back" against abyssing, naturally I wouldn't want the submarine being deleted or characters disabled and such from this becoming too high instead.

Perhaps the max entity distance could be tied to the generated level itself actually as an XML setting of the level generation parameters.

**Comment by Regalis11** [comment]
The max entity distance is just  to make sure that items that end up way too deep to be reached anymore don't have to be updated (or that they don't reach some ridiculously far-away position that might cause problem with the physics engine). It's supposed to be way below the actual seafloor, so deep that it should never be reached by normal means. And it _is_ possible for entities to go below MaxEntityDepth, because the sea floor is not infinitely wide.

**Comment by NilanthAnimosus** [comment]
I always figured it was there as a means to remove items that have sunk so deep there is no reason to keep them around anymore (since it does add items to the entity spawner remove queues and such, along with disabling things that sink so deep). and felt it was odd that essentially it was almost never triggered, but this makes more sense then.
