### ISSUE TITLE
Sprayer sound effect continues until player stops aiming sprayer

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#6010]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sprayer starts sound effect after aiming and beginning to spray with left mouse button. When not spraying anymore, sound effect continues until player stops aiming with right mouse button.

**Steps To Reproduce**
Acquire sprayer with ethanol. Aim sprayer, then start spraying. Stop spraying while continuing to aim.

**Version**
Windows, latest unstable release (0.14.4.0)

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/28ff9db325177d276d39f6cbfc6173e740e66e36

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
