### ISSUE TITLE
Reactor's set_fissionrate and set_turbineoutput pins aren't clamped

### ISSUE THREAD

**Issue by kwogger** [Regalis11/Barotrauma#6011]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The reactor's set_fissionrate and set_turbineoutput pins aren't clamped, allowing components to set values outside of the range [0-100]. This lets components to give reactors performance "beyond" what is possible from the UI.

**Steps To Reproduce**
Start a reactor wired with its max load. Wait for steady state. Set  set_fissionrate and set_turbineoutput to 0. Do the same again, but set set_fissionrate and set_turbineoutput to -9999999. Observe that the two power curves are different when they should be the same.

**Version**
Windows 0.13.3.11

**Additional information**
Code reference:
https://github.com/Regalis11/Barotrauma/blob/3f324b14e8d815955391a1ba97e119bbb1913a6f/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Reactor.cs#L731
set_fissionrate and set_turbineoutput should both be clamped

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb2112df60518aadd7a6ec44c288bce4cb9bc848

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
