### ISSUE TITLE
Beacon Station Hull Bug

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#6017]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a player runs and ragdolls into this corner on BeaconStation1, they will be permanently stuck and unable to be freed without cheats (crouching, moving, ragdolling, etc have no effect on positioning).
![image](https://user-images.githubusercontent.com/72813628/121488872-7ed8ff00-c9a1-11eb-8b54-83bbda39b0e2.png)
![image](https://user-images.githubusercontent.com/72813628/121488398-0d00b580-c9a1-11eb-8bdb-b25e94bad095.png)

**Steps To Reproduce**
1. Enter a drained Beacon Station
2. Run to the right and ragdoll into the room's corner

**Version**
V0.14.4.0, Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b698be737c4aa62d333d3c5fb369b66fe623e0db

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
