### ISSUE TITLE
Radiation + O2 Low Effects not Blending Correctly

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#6018]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Radiation and O2 Low effects hard cut into eachother rather than fading between the two, or blending together.

**Steps To Reproduce**
1. Inject yourself with radiotoxin or be affected by Jovian Radiation
2. Go in a low O2 environment
3. Watch as Radiation Static immediately disappears when the O2 warping effect is introduced (most noticeable when O2 is reintroduced where the Radiation Static cuts back into view)

**Version**
V0.14.4.0, Windows

**Additional information**
+minor bug, when vomiting underwater, vomit explodes and causes burns.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2d93160760cb272009649296853f868bc00ce02d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
