### ISSUE TITLE
Health UI Cursor Resets When Applying Bandages with Radiation Affliction

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#6020]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using hotkeys/clicking bandages to heal body parts while under the effects of radiation recenters the health UI cursor and leaves players unable to heal certain body parts without dragging for several seconds with each bandage applied.

This is best shown in video form (note that video starts after bandage has been applied due to github file size restrictions + how whenever a body part is clicked after a bandage has been applied it resets the "applied body part" to the chest):
 
![ui bug(2)](https://user-images.githubusercontent.com/72813628/121499106-13942a80-c9ab-11eb-9fce-63b77cc727bb.gif)

**Steps To Reproduce**
1. Inject yourself with radiotoxin or stay in Jovian Radiation long enough for burns to start developing
2. Double click/hotkey heal yourself and try to select other limbs to heal
3. Body parts are "unequipped" and recentered on the chest

**Version**
V0.14.4.0, Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d2aad36a916ca934f90ef73548eb45783413efcf

**Comment by Ek-Videogames** [comment]
@SoobGorl 
Just as a medical tip, it is good practice to apply bandages (or any other limb-specific) by dragging item from hotbar onto the limb in question. As using the 'cursor selection' can be prone to misclicks and randomly resetting (one such example shown here) which can cause a wasted use on a limb that does not need it, etc.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
