### ISSUE TITLE
Outpost Location Backgrounds Do Not Update with Biomes

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#6021]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The background biomes of outposts do not update the deeper players go into the map. 

![image](https://user-images.githubusercontent.com/72813628/121500948-c1540900-c9ac-11eb-953a-c87a0794c523.png)

**Steps To Reproduce**
1. Go to the end of a level in a biome that is not the cold caverns (the default is very similar)
2. Dock to an outpost and swim outside

**Version**
V0.14.4.0, Windows

**Additional information**
I'm not sure if this is intended, as gameplay implies otherwise (+ the default background is the same as the pre-campaign overhaul one before biomes had unique backgrounds), but lore does? Sorry if it is intended!!

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
