### ISSUE TITLE
Holding Hatchlings Creates Bugged UI Element

### ISSUE THREAD

**Issue by SoobGorl** [Regalis11/Barotrauma#6023]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Holding any killed hatchlings creates a random UI element on the left side of the screen.

![image](https://user-images.githubusercontent.com/72813628/121504594-21987a00-c9b0-11eb-91fe-18b85592b2bb.png)

**Steps To Reproduce**
1. Spawn/kill a hatchling
2. Pick them up

**Version**
V0.14.4.0, Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c11699784cdd96636aa14ce10386a177d1b5ff56

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
