### ISSUE TITLE
A submarine's cargo capacity doesn't take slots that already have crates in them into account

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#6025]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Only free slots are taken into account when determining the cargo capacity to show in the submarine info (e.g. in the new game menu).

**Steps To Reproduce**
1. Add a couple of crates to the crate shelves in Dugong
2. The cargo capacity is now <8

**Version**
v0.14xx

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8a8e9f15e9706043020a4c2de7c93a1661d3a4a8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
