### ISSUE TITLE
Outside visible in some parts of the berilia

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6027]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In some parts of the berilia there are no background walls where there is expected to be, making the outside visible

1. front ballast 
![image](https://user-images.githubusercontent.com/5103517/121608337-b7b7b900-ca1f-11eb-8dbf-0ee6f5a95d59.png)

2. hatch above bilge
![image](https://user-images.githubusercontent.com/5103517/121608354-c3a37b00-ca1f-11eb-92f0-5e545901224f.png)

3. some ducts when open 
![image](https://user-images.githubusercontent.com/5103517/121608392-d918a500-ca1f-11eb-9cdd-678c5fe58dee.png) 
![image](https://user-images.githubusercontent.com/5103517/121608410-e33aa380-ca1f-11eb-948f-065865e3debe.png) 
![image](https://user-images.githubusercontent.com/5103517/121608423-e9308480-ca1f-11eb-9f40-4af570abdf88.png)

**Steps To Reproduce**
open the berilia

**Version**
0.14.4 unstable

**Additional information**

**Comment by Rokvach** [comment]
I'm not sure if you would really notice these in normal gameplay but I found some areas still which shows the background

I'm still seeing some green in the front ballast
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b491ef01-10db-47c9-9d6d-477cacc3260f)

There's also a sliver under the top airlock
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d4ca1a4b-18ad-4453-b37f-9c86622c010b)

There's no background wall behind the large engine above reactor, so some green coming through
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8869fe70-c152-4c93-a3c0-713a56422407)
Without engine 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/cae579c4-b5d0-4ba5-b173-e23e69fb4b56)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/233c6ff23df75b9007c8fbcfceca319260cadc6f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
