### ISSUE TITLE
line coming out of berilia

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6028]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/5103517/121608961-df5b5100-ca20-11eb-9b6b-d08b081d8cd0.png)
caused by this fin somehow
![image](https://user-images.githubusercontent.com/5103517/121608983-ea15e600-ca20-11eb-81fc-7e2ede2acfc6.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.4 unstable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6114a8d74f56948616f85ed460b85e353ec681b1

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
