### ISSUE TITLE
lights offset in status monitor and navigation terminal

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6029]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
ambient lights in status monitor and navigation terminal are offset
![image](https://user-images.githubusercontent.com/5103517/121609195-60b2e380-ca21-11eb-92e7-99193c7ed857.png)

possibly related to the change in boxes? 
![image](https://user-images.githubusercontent.com/5103517/121609250-788a6780-ca21-11eb-8507-83cfcb3fe291.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.4

**Additional information**

**Comment by Rokvach** [comment]
Already fixed for the next build, closing.
