### ISSUE TITLE
Searchlights are outclassed for viewrange compared to guns

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6030]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Searchlights have 2/3 the camera offset compared to guns, at "515" for the searchlight vs 750-800 for turrets. this makes it both poorer at spotting both monsters and terrain things compared to any gun. 
Searchlights are often placed in spots to provide vision or additional vision without another gun, but their poor view offset inhibits that somewhat. (more so on lower resolution monitors where the offset will be worth more? not sure)

**Steps To Reproduce**
> use searchlight
> be disappointed in view range
> switch to coilgun instead to look at stuff

**Version**
0.14.4 unstable

**Comment by Ek-Videogames** [comment]
- as are cameras, though the latter can be argued for interior use.

That does raise the question, would we want some kind of exterior camera item variant which shares a camera range more like that of turrets? While the current one keep's its "default character view range"

**Comment by Regalis11** [comment]
Increased the range in https://github.com/Regalis11/Barotrauma-development/commit/427d43b949f09e069c0d2f939c053d4fd8e71e35

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
