### ISSUE TITLE
ID cards work on enemy ships ( PVP )

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6032]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
ID cards work on enemy ship, intentional?
Expectation is that only allied crew are authorized on a team (as it is IRL), and that it wouldn't work on someone else's ship.

**Steps To Reproduce**
1. use your team's ID card to open the opposing team's doors/secure lockers

**Version**
0.13.3

**Additional information**

sub vs sub PVP access authorization idcard id cards lock

**Comment by Regalis11** [comment]
Related: Regalis11/Barotrauma#5459

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6681cdad74581226ba8b9b39dd18adcb3fe349fa

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
