### ISSUE TITLE
[0.1400.4.0] engine propellers have a very small hitbox, allowing you to slip past their kill zone

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6034]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hitboxes on many engines are too small for it sizes, causing humans being able to slip behind without getting killed by them
![image](https://user-images.githubusercontent.com/42521948/121697596-e09a8580-cad5-11eb-9022-08497bbeb03f.png)

**Steps To Reproduce**
1. open sub editor
2. select any submarine with correctly installed propellers hitboxes (in my case humpback)
3. go to propellers area
4. order character to wait there
5. change your char to another crewmate and make submarine move
6. watch your original character surviving the engine and slipping behind hitbox are

**Version**
Unstable 0.1400.4.0, Windows 10 pro
**Additional information**
possible fixes is to increase damage from proppelers, so it will 1 tap humans in diving suits or make hitbox zone customizable (a.k.a can make it bigger, smaller or even change shape of it)

**Comment by Regalis11** [comment]
Tbh I don't quite see why this is an issue, the way I see it the propeller/turbine is at the back of the engine, so it'd make sense to be able to stay in that area without getting hurt.
