### ISSUE TITLE
Human corpses' hand slots getting overlapped by player's inventory

### ISSUE THREAD

**Issue by SumNutz** [Regalis11/Barotrauma#6035]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Human corpses' hand slots (specifically the right hand slot) get overlapped by player's inventory, preventing interaction, since the player's slots get in the way.
![20210611111815_1](https://user-images.githubusercontent.com/46006004/121701314-2724bb80-caa7-11eb-936b-1d56e18f4118.jpg).

**Steps To Reproduce**
Find/spawn human corpse, take a storage container or a single hand held item, double click storage container in player's inventory to transfer it to the corpse's inventory, attempt to transfer it back to the player by double clicking it in the corpse's hand slots, unable to.

**Version**
Windows Unstable V0.14.4.0.

**Additional information**
No additional info.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b9454942fbfd7501c6012676f29762bc50be99f7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
