### ISSUE TITLE
[0.1400.4.0] Items fall out of the inventory when you load them into the gun or put them on

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6037]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
items like 40mm grenades, clothing or any other ammo will fall below your character when you loading gun while standing up like on screenshot
![Barotrauma_kfdRQcS8JT](https://user-images.githubusercontent.com/42521948/121713256-5528f080-cae5-11eb-967a-1a54f95a2f27.png)

**Steps To Reproduce**
1, go outside submarine
2. get a person with grenade launcher and grenades out with you
3. make him put grenades in and out grenade launcher
4. watch items fall off

WARNING: IT CAN BE TESTED ONLY IN MULTIPLAYER AND ONLY WITH OTHER PLAYER!
**Version**
0.1400.4.0 Unstable, windows 10 pro

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. Tested by putting the grenades in and out in a bunch of different ways: taking one grenade out and another in, swapping them, swapping from stacks, double clicking and drag-n-dropping, but couldn't get them to drop.

**Comment by Lefttroll** [comment]
We were unable to replicate it in new unstable patch too, so seems like problem is closed?

**Comment by mrjpjr** [comment]
This sounds similar to an issue with mined/harvested/looted items occasionally dropping out of inventory experienced in a server I play on.

That said, the host's internet is bad (almost every round most/all players except host don't load in correctly, and have to spectate/rejoin), so I always assumed that was the cause.

Once the update comes out, I will check and update here.
