### ISSUE TITLE
You can keep dragging an item from a stunned/ragdolled character's inventory after they get back up

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6038]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when you click and hold item (like suit) and then stunned person get ups, you still able to move item (even tho after dropping or putting this item somewhere it gets back on host
![Barotrauma_b9PhGmpShv](https://user-images.githubusercontent.com/42521948/121725525-0b92d280-caf2-11eb-9fd0-6724d18c34ad.png)

**Steps To Reproduce**
1. get second player
2. tell him to get suit on
3. tell him to get raggdolled via holding space
4. take and hold suit
5. tell him to get up

**Version**
0.1400.4.0 unstable, windows 10 pro

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8677b97df8acdb42f7f85e5d6a0b42597c954da

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
