### ISSUE TITLE
[ Unstable ] Flare particles don't move relative to hull.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#6040]
Normal flare particles rather than their previous behavior of slowly drifting upwards - instead now appear to move relative to the world instead of whatever instanced hull they are inside. Obvious when the submarine is moving.

![image](https://user-images.githubusercontent.com/55356135/121741778-f6f01380-cacc-11eb-98be-f07cdc451c50.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7cbbecb087801c6c04bd231443b2757a539e38d6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
