### ISSUE TITLE
submarine preview maker doesn't display texts when not in view

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6045]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when creating a preview image, labels (and text displays) won't show if the editor doesn't have them in view.

**Steps To Reproduce**
1. look away from the labels/text displays
2. create preview image

**Version**
0.14.4 unstable

**Additional information**
preview image made when whole sub was in view (zoomed out)
![image](https://user-images.githubusercontent.com/5103517/121762029-83b4c480-cb01-11eb-8558-cf4c42cec142.png)

preview image made when sub not in view
![image](https://user-images.githubusercontent.com/5103517/121762070-a6df7400-cb01-11eb-8d83-8f7fcbc57e6b.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97715d53b215b732fba91eec503d51a7ee32b14e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
