### ISSUE TITLE
mission-less and event-less outpost

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6046]
- [ ye] I have searched the issue tracker to check if the issue has already been reported.

**Description**
docked to an outpost, waited for 5 minutes, no missions or events loaded in, retried, same result

**Version**
v0.1400.4.0 Unstable

**Comment by LePiromano** [comment]
oh sorry i forgot to attach it :P
[dietznutz.zip](https://github.com/Regalis11/Barotrauma/files/6649050/dietznutz.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2595b98712f4e919b7e58f51d9e25f1f7c0d56b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
