### ISSUE TITLE
Disguising as someone does not change name in text chat

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6049]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
disguising as somebody will not change color of team and your name when you talking in text chat

**Steps To Reproduce**
1. get a diving mask/diving suit and put it on
2. get a spare IDCARD (In my case of another player but it works with bots too) and put it on instead of your IDCARD
3. type text in chat
4. watch how chat still displays your name to everyone including you

**Version**
0.1400.4.0 Unstable, Windows 10 pro

**Additional information**
i recommend testing it on players

**Comment by Regalis11** [comment]
This is not a bug. It's always worked liked this: we think it makes sense that speaking ruins the disguise (others should be able to recognize you by your voice). Being able to speak as someone else also has quite a bit of griefing potential.
