### ISSUE TITLE
Maximum Starting Recharge Speed of Batteries is 500- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#605]
I have set my battery to recharge for more, than 500 (same I did with maximum amount) and my generator have broken on the next mission, because batteries have set themselves from 100% to 10%, because any recharge speed above 500 is not saving and returns to 500.

Was that intended?

**Comment by NilanthAnimosus** [comment]
I believe this may have been fixed back in #368 however I personally have yet to see a single submarine starting with a recharge rate past 500 well after this fix.

Noticing in my mod project this value is set to "false" on savable, despite there is a commit for fixing it - I think that commit may be dev-only and not on the master branch.
