### ISSUE TITLE
[0.1400.4.0] outpost NPCs are able to open doors in submarine 

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6050]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
outpost NPCs are able to open any normal door in submarine (without ID_LOCK) and i think it should be fixed. (same principe as in PVP, that you cant open doors of enemy/not yours submarine)

**Steps To Reproduce**
1. got `leveleditor` and generate outpost level
2. load in and control one of the bots (in my case guard)
3. go to player submarine and try to open normal doors (doors without id_lock)
![image](https://user-images.githubusercontent.com/42521948/121779803-2cb4fb00-cba6-11eb-9bdd-fd991ac24313.png)

**Version**
0.1400.4.0 Unstable, windows 10 pro

**Additional information**
It is very annoying when you trying to hide from angry security guards only to find that doors can be freely opened by bots that not on your team.

**Comment by Regalis11** [comment]
This is intentional: the NPCs can open non-access-restricted doors (just like the players can in the outpost). We feel changing this would make fighting the NPCs a bit too easy: you could just always return to the sub without the NPCs being able to follow you.
