### ISSUE TITLE
[0.1400.4.0] every empty non-coilgun ammobox does not drop ingriedients after being deconstructed

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6053]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
every empty non-coilgun ammobox does not drop ingriedients after being deconstructed!

**Steps To Reproduce**
1. get empty chaingun/laser box
2. deconstuct it

**Version**
0.1400.4.0 Unstable, windows 10 pro

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d28923107034bae05253cc6a022fe346e91f2389

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
