### ISSUE TITLE
[Unstable] Typhon 2 the railgun is not connected to ammunition loader.

### ISSUE THREAD

**Issue by 1v01** [Regalis11/Barotrauma#6054]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In Typhon 2 the railgun is not connected to the ammunition loader. 

**Steps To Reproduce**
Open sub editor and check it there. Or host/start a game with the Typhon 2 and try to fire the railgun.

**Version**
0.14.4.0 Unstable, Windows 10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8579faaf8be0973735520680ecff186bdf086c19

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
