### ISSUE TITLE
Missions can sometimes unlock in a different path between server and client

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6055]
Noticed on the bugfixes branch by just playing the campaign normally, when I reached the second outpost and unlocked all the available missions, I tried to go and select a mission in the campaign map and noticed that couple of the missions didn't get selected properly, they just reverted back to unselected when I clicked them.
I decided to reload the save and now those missions which I couldn't select were positioned in totally different paths than where they were before reloading.

This is after reloading the save, arrows pointing where the missions used to be before reloading
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d375e466-4366-4c16-ab84-bc4cea91a0fe)

Save: 
[https://app.zenhub.com/files/93301055/d8bea28e-cf47-4ef3-b616-77ab7276158a/download](https://app.zenhub.com/files/93301055/d8bea28e-cf47-4ef3-b616-77ab7276158a/download)

**Comment by M61Dev** [comment]
Save appears to not have survived being put on the internet, try putting it in a compressed archive

**Comment by Regalis11** [comment]
Could not find a way to reproduce this
