### ISSUE TITLE
I offer a big improvement for the game

### ISSUE THREAD

**Issue by vichenk** [Regalis11/Barotrauma#6059]
Hello everyone, I would like to bring up an interesting innovation in the game for discussion. We play with the guys and basically I do the submarine change for everyone. I started doing this only because I didn't like a lot of things about the proposed submarines in the proposed game, and I began to modify Typhon-2, I got a cool submarine on which we go through the company. But the game does not delay many for a long time, because if you make a cool submarine, you don’t feel much progress as you progress through the game (I didn’t make an imbalanced one). I would like to propose to make improvements to submarines at the level of submarine modifications. What I mean? For example, so that you could buy an automatic battery management on power outage in the store, or an additional tank of water, or add a cannon / nuclear warhead. Or, for example, an additional compartment with suits. In essence, this is a versioning of a submarine. That is, so that as the company progresses, it would be possible to buy some new pieces for your submarine. It seems to me that this would solve several problems.

1. Players would not leave the game when they made / downloaded a cool submarine, because they immediately have a choice of either turd or imbalance (from mods), especially for a beginner it is completely unclear how it will behave
2. In this case, it will all make sense to try to make interesting submarines for the passage of the company and create something balanced for a cool gaming session
3. Modders would have reached a new level of interest, because each modification affects the passage of the company and, in fact, the submarine that you chose would completely change the sensations of passing the game, while not slipping easily into the beginning and not being horrified by the complexity at the end

It seems to me that such changes would bring the game to a new level, players are attracted by large modifications of the submarine during the game, improvements that they can buy

On the other hand, it's great that the only way to improve your favorite submarine in the game is to figure out the editor, so a lot of players sit there.

But I would leave the editor as a sandbox or a game for engineering lovers like me

And for ordinary players, a clear way to modify a submarine

I am also not interested in making a balanced submarine for other players right now. everyone has their own needs, but if there was an opportunity to make a boat and a bunch of options for improving it, so that other players would get excited about the variability of changes and improve it as they wanted in a very simple way during the passage of the game

What do you think of improving the game in such a way that this idea would help develop it for the better side of the game?

Sorry for my English

**Comment by Regalis11** [comment]
Thank you for the idea! This is actually not that far from what we have planned. In the next update, you will be able to customize the submarine's weapons mid-campaign, and we may expand this system to other parts of the submarine as well in the future.

But in any case, we generally only use the issue tracker for bug reports, feature requests and ideas should go in the [Discussions](https://github.com/Regalis11/Barotrauma/discussions).

**Comment by vichenk** [comment]
Okey, sry. From now on I will be more careful. Thanks for the development and improving of the game
