### ISSUE TITLE
Remora's lower front AI pathfinding not working

### ISSUE THREAD

**Issue by SumNutz** [Regalis11/Barotrauma#6060]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI crew members attempting to move up the ladder between the Remora's airlock and drone fail to do so by letting go of the ladder too early(?)

https://user-images.githubusercontent.com/46006004/121822374-36596400-cc75-11eb-8da5-2303da7b4b03.mp4

**Steps To Reproduce**
Spawn/move crew member down mentioned ladder and get him off the ladder at lower end, order to follow/repair/operate target requiring movement up the ladder, AI fails to move up the ladder.

**Version**
Windows Unstable V0.14.4.0

**Additional information**
Maybe messing with Remora's waypoints in the sub editor might fix the problem.

**Comment by itchyOwl** [comment]
Fixed the issue by adding an extra waypoint: Regalis11/Barotrauma-development@04acd04.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
