### ISSUE TITLE
arrow labels have borders, implying lighting direction

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6061]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
arrow labels have borders. 

This implies light direction, making them sometimes "wrong" if flipped one way or another relative to a light source. 

Pic: White labels on a white background, showing clearly the partial outlines
![image](https://user-images.githubusercontent.com/5103517/121851141-c28e7a00-ccbb-11eb-9383-23cd351e6637.png)

**Steps To Reproduce**
place/look at an arrow label

**Version**
0.14.4 unstable

**Additional information**
It also somewhat looks bad with "unexpected" thin black lines in for decorating

graphical spriting sprite labels

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
