### ISSUE TITLE
Items with the same name will continously switch places on the store interface

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#6062]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items with the same name, e.g. the different eggs, will keep switching places on the store interface.

**Steps To Reproduce**

1. Start a campaign
2. Go to the store
3. Sort by price (high to low)
4. See that the eggs will keep switching places

**Version**
v0.14.5.0

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@c519d70

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
