### ISSUE TITLE
[0.1400.5.0] Endworm is only enemy that spawns in `hunting grounds` missions

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6063]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It is seems like charbdys stopped spawning in `hunting grounds` missions for no reason

i did couple of campaigns and one them was with LePiromano and in  none of hunting grounds spawned charbdys   instead of endorm

same about abyss itself, although in abyss you can actually charbdys while on missions you cant

**Steps To Reproduce**
1. launch new campaign
2. teleport through outposts to hunting grounds 
3. start doing levels like a normal player

**Version**
Unstable 0.1400.4.0/1400.5.0, windows 10 pro

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3957c35645a95eff0e43eeca68f73e3fc7c25f74

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
