### ISSUE TITLE
[0.1400.5.0] you cannot rotate pumps even tho rotation function is here

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6064]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you cant rotate big pumps 
![image](https://user-images.githubusercontent.com/42521948/121946144-4d738100-cd5d-11eb-9b0b-94170a5c5e50.png)

**Steps To Reproduce**
1. go to sub edtor
2. spawn big pump
3. try to rotate it

**Version**
0.1400.5.0 Unstable, Windows 10 pro

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e1b735ef863cda8de2b5e6c945fa60145a16bad

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
