### ISSUE TITLE
[0.1400.5.0] Multiple pressure protection items do not take the highest value into consideration

### ISSUE THREAD

**Issue by RaptorIM** [Regalis11/Barotrauma#6065]
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When wearing multiple pressure-protective items (innerwear with 4000 pressure protection and on top of that abyss diving suit with 10000 pressure protection) I get squashed by pressure already below 4000m depth.

**Steps To Reproduce**
1) Mod innerwear to provide pressure protection. 
2) Wear it underneath proper diving suit. 
3) Get squashed by pressure that item with lower protection can't protect against, but item with higher protection should protect against.

**Version**
v0.14.5.0, Windows, latest unstable version. 

**Additional information**
Item with the highest pressure protection should take precedence over items with lower ones.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f7ee9f30714a671d6f03e465ede91d2b9e7b7da0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
