### ISSUE TITLE
[bug] Walls Ignored Outside the Sub When Moving Towards a Gap

### ISSUE THREAD

**Issue by CRedinger** [Regalis11/Barotrauma#6066]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Player can move through walls outside the sub when approaching an open door/hatch or gap.

[Gap bug test.zip](https://github.com/Regalis11/Barotrauma/files/6651984/Gap.bug.test.zip)

**Steps To Reproduce**

- Using the attached outpost -

1. Test the attached outpost in the sub editor. 
2. Equip the dive suit. 
3. Open the door.
4. Swim right through the walls.

- Recreating from scratch - 

1. Create a gap large enough to move through.
2. On one side create a hull overlapping the gap.
3. On the opposite side of the gap create a wall parallel to the gap. 
    (Wall should be within a 10 feet or so of the gap)
4. Swim from the side of the wall opposite the gap, through the wall towards the gap.

**Version**

v 0.13.3.11
Windows 10

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/55aa37dee10235188d00d44352c7c337d24a3037

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
