### ISSUE TITLE
[0.14.5.0] Thalamus Terminal cells causing errors in multiplayer

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#6068]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a **major** issue with the terminal cells that the thalamus spawns in. It appears as soon as the terminal cell makes contact with the sub's hull, where then the multiplayer server will crash with the following message and kick all players out and send the host back to the lobby.
https://puu.sh/HOZJr/457b04b358.jpg
The event id and entity id appears to be random to me at least and I wouldn't know what it means.

**Steps To Reproduce**
This is VERY easy to reproduce given if a thalamus is in the area. I was able to locate a seed with a thally in it: "biomedical" for testing and recording the bug and crash in action. It is also easily replicable by simply spawning the terminal cell outside of the sub. I have recorded it and will provide a link to it to show it in action.
https://www.youtube.com/watch?v=_BzZXBQ7lWE

**Version**
v0.14.5.0

**Additional information**
I am reporting this bug on behalf of an acquaintance who was also experiencing this bug in unstable and I wanted to test it myself. I have confirmed that it isn't just their side and could possibly affect everyone. I hope this bug gets patched before the major update hits.

**Comment by Regalis11** [comment]
Thank you for the report! Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f2a2c969ba65f699069c65ad2ac295cdfa5d0c17.

**Comment by Rokvach** [comment]
Tested, working  correctly. Closing.
