### ISSUE TITLE
Alien ruins spawned inside level wall, cannot access trough the places where the level wall should be inside the ruins.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6072]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On a salvage an artifact mission, the room where the artifact is cannot be entered because a level wall is blocking the entrance.

**Steps To Reproduce**
use the save attached and try to get the artifact without busting trough the thick wall.

**Version**
v0.1400.5.0

**Additional information**
[dietznutz.zip](https://github.com/Regalis11/Barotrauma/files/6656079/dietznutz.zip)
(for some reason sometimes it loads the wrong artifact as the mission artifact, the artifact im talking about is the one on the alien ruins way below the start)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2709d7a10e84342f12e09200e9a521f9c7d1a1dd

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly, closing.
