### ISSUE TITLE
"targetlimbs" Statuseffect Doesn't Work as Expected

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#6073]
[Coding, Bug]
Basically, using `<StatusEffect target="This" targetlimbs="Head" />` will not truly target the head (the way target="Limb" works for something like a meleeweapon, where it truly targets the limb class of whatever limb it hits), it will only make particles and afflictions target the head. The same goes for the other limbs.
An example of something that actually targets the limb is the bandage (or more specifically the "limb" target in the meleeweapon).
So for example, if you edit the bandage's reduceaffliction statuseffect that targets "Limb", it properly sets/gets the properties of the actual limb class (eg you can put in hidelimb="true" to actually make the limb the bandage hits when swinging disappear).
It's kind of unexpected that a property called targetlimbs doesn't actually target a limb, so I assume this is an issue/bug.

**Comment by Regalis11** [comment]
I'm not entirely sure I understand the issue correctly (what exactly are you trying to do with that status effect?), but to me it sounds like this isn't a bug.

The "target" attribute determines what the StatusEffect targets, and if you set it to `This`, it'll target whatever "This" means in that context (e.g. an item). The targetlimbs attribute can be used to further restrict the targets, but if the targets aren't Limbs in the first place, it can lead to some strange behavior (e.g. applies to the actual target(s), but takes take targetlimbs into account when doing something limb-specific like applying afflictions).
