### ISSUE TITLE
Laser destroys moloch armor

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6076]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
as far as i know the laser is not supposed to break moloch armor, and simply cook the moloch instead, but in-game it does both things.

**Version**
v0.1400.6.0

Edit: apparently non-trilaser ammo destroys moloch armor too.

**Comment by Regalis11** [comment]
This is intentional
