### ISSUE TITLE
canister shell reloading after round end

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6077]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
canister shells refill themselves and can be used again once you complete a campaign round and appear the next one, they seem empty but can be used again.

**Steps To Reproduce**
1_ empty canister shell on a campaign mission
2_ end the mission (dock/enter back or dock/enter to the destination)
3_ the empty canister shell can be used again!

**Version**
v0.1400.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f3fc8af98e9a1918b9e85638e3042419e83f2f30

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
