### ISSUE TITLE
Abandoned outposts appear empty after campaing loop.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6078]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every abandoned outpost i've visited so far after i finished the campaign has no mission or enemies inside it, but still has loot.

**Steps to reproduce**
Complete a campaign (i visited a few abandoned outposts before finishing it, maybe that affected something), then after entering the loop, check the abandoned outposts.

**Version**
v0.1400.5.0 Unstable

**Additional information**
here's a save with 2 empty abandoned outposts, haven't checked the rest yet.
[dietznutz.zip](https://github.com/Regalis11/Barotrauma/files/6658622/dietznutz.zip)

**Comment by LePiromano** [comment]
I found this exploring an outpost after a campaign loop, i know this was fixed once... i travelled back in time?
![image](https://user-images.githubusercontent.com/55637865/122283490-fa1b4300-cec2-11eb-9a4a-a7f6a09302bb.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7da9584cc5ccaa1036d41136d17faa1eebae9b7e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
