### ISSUE TITLE
[Unstable] No way to trigger event assassinationofjacovsubra2

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6079]
**Description**
I've searched OutpostEvents, randomevents, missions, items... there seems to be no way at all to trigger assassinationofjacovsubra2 event.

**Steps To Reproduce**
Try to finish assassinationofjacovsubra, all parts. You will get stuck at finishing 1.

**Version**
Unstable

**Comment by danielasteljoki** [comment]
Fixed in 78d513e.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by Udrakan** [comment]
As far as I can see and test, theres no natural way to trigger assassinationofjacovsubra3, the next part of the event

**Comment by danielasteljoki** [comment]
Fixed in 8d6eb1d on dev.
