### ISSUE TITLE
Host always spawns in same location.

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#6082]
While this is a low priority problem, I find it can sometimes make certain gamemodes such as Prison RP boring. Instead of spawning in a random cell, that may have different gameplay from other cells, I am always spawned in the same one. When playing the same map on a different server as a non-host I get spawned randomly as usual.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/decb196c55975f31b0f6a4b0c626f5a2d649097d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
