### ISSUE TITLE
[Unstable] Turret swapping shenanigans when linking two turrets to the same Loader(s)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6085]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you link two coilguns to the same loader, it causes issues when swapping only one gun

**Steps To Reproduce**
1. Go in editor, add a coilgun to Dungong
2. Link the coilgun to an existing loader
3. Wire the coilgun trigger 
4. Start a campaign, swap one of the linked coilguns with a laser, 
5. Start a mission and fire. One gun is replaced by laser, but coilgun can fire lasers too with coilgun stats

Works with any kind of swap
![image](https://user-images.githubusercontent.com/73229309/122255030-048f0a00-cece-11eb-9169-ed52d977db93.png)

The weapon that was swapped last takes priority over the loader type
Not sure how big of an issue that is; you can avoid having this issue by buying the weapon twice, and none of the Vanilla subs link two guns to the same loader.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/205e2fe6d6863c5569b90dc49b28e787939b9f11

**Comment by ubertpendragon** [comment]
> Fixed turrets working with incorrect loader types (e.g. coilgun being able to fire laser bolts when linked to a pulse laser loader). Regalis11/Barotrauma#6085

I hope this isn't going to break the ability to link cabinets to coilguns as ammo source, as some subs will use "medical" coilguns
The remedy could be worse than the cure, I'll keep an eye on it next unstable

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
