### ISSUE TITLE
Uncompleted connection is not deleted if a new wire is created using the hotkeys while the uncompleted connection is dragged

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6088]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the hotkeys are used to change the wire colour of a connection while the connection is being dragged inside the connection box a new connection is created without deleting the old connection.

The expected behaviour is that the held connection is deleted so that you are no longer dragging it. 

**Steps To Reproduce**
- Place a component into the sub. 
- Place a new wire on one of the connectors. 
- Drag the wire off the connection. Do not let go
- While dragging, press one of the wire hotkeys (1-8)

At this point a new wire corresponding to the hotkey is created.  However, the original wire's connection is not deleted. This can still be placed on a pin. The resulting connection only has one end, and trying to delete it results in an error.

**Version**
Unstable v0.14.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d30becf7e78f003df7bdd67de833d283e8926116

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
