### ISSUE TITLE
Kastrull engine room roof can't be repaired by AIs.

### ISSUE THREAD

**Issue by 1v01** [Regalis11/Barotrauma#6089]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the engine room of the Kastrull AIs can't reach the roof (exactly below the engine) to repair leaks and get stuck there trying to repair it. I can weld it thou. They don't use the full range of the welding tool (I think).

**Steps To Reproduce**
Make a leak exactly above Kastrull engine

**Version**
Unstable V0.14.5.0 (maybe it's in 13 too not sure haven't tested) (Windows 10).

**Comment by Krzeszny** [comment]
It's a universal bug, not just on Kastrull.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a03eab4f635cd58ff403905c2b5a850cceabacfb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
