### ISSUE TITLE
Carrying diving suit into base causes pressure warning

### ISSUE THREAD

**Issue by WilliamRoyNelson** [Regalis11/Barotrauma#6093]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pressure exceeds diving suit capabilities tooltip pops up when carrying suit in city.

**Steps To Reproduce**
When I was carrying a diving suit, wearing no diving suit, while parked at a city, as I crossed the threshold from my submarine to the city, an alert popped up saying "Caution: Exterior pressure exceeds diving suit capabilities."

To make it happen again, undock, re-dock (or retry), then re-ascend the ladder while carrying a diving suit and not wearing a diving suit.
Does not occur when not wearing suit AND not carrying suit
Does not occur when wearing suit AND not carrying suit
Does not occur when wearing suit AND carrying suit
Occurs when not wearing suit AND carrying suit

Similar behavior when tested with Abyss Diving Suit
No notable messages in console log even with verbose logging enabled.

**Version**
Windows. Version: Unstable 0.14.5.0 (ReleaseWindows, branch release, revision 97c4dd32f9)

**Comment by WilliamRoyNelson** [comment]
I'm not particularly competent at c#, but if it helps, the exact hint text is "divingsuitwarning" and the only reference I see in the codebase to that occurs here:
https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaClient/ClientSource/GameSession/HintManager.cs#L557

**Comment by WilliamRoyNelson** [comment]
On Azimuth, crossing threshold from below:
![image](https://user-images.githubusercontent.com/7910938/122339534-108ec200-cef6-11eb-9ed1-caa9aa546391.png)
On Azimuth, crossing threshold from above:
![image](https://user-images.githubusercontent.com/7910938/122339685-3ddb7000-cef6-11eb-8a46-9633edab426a.png)

On Typhon 2, crossing threshold from below:
![image](https://user-images.githubusercontent.com/7910938/122340391-0e793300-cef7-11eb-9518-13ca709d2308.png)
On Typhon 2, crossing threshold from above:
![image](https://user-images.githubusercontent.com/7910938/122340521-37012d00-cef7-11eb-8653-28d70f26fc68.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c6e934476edb3fbddca9636deaff9a2fb58a088

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
