### ISSUE TITLE
Hydroxyapatite not deconstructing into calcium and phosphorus

### ISSUE THREAD

**Issue by SumNutz** [Regalis11/Barotrauma#6095]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deconstructing this mineral is not giving out the intended materials, in fact, not giving any resources.

https://user-images.githubusercontent.com/46006004/122410928-bb38cc00-cf5a-11eb-8c28-fabd4db429aa.mp4

**Steps To Reproduce**
Acquire Hydroxyapatite, drop into deconstructor, deconstruct, no resources given out.

**Version**
Windows Unstable V0.14.5.0.

**Additional information**
Will test with other minerals.

**Comment by LePiromano** [comment]
the materials are going into the storage container.

**Comment by SumNutz** [comment]
did not know this was a feature. well, saved me some energy from useless testing.
