### ISSUE TITLE
Talking to friendly mudraptor generates error.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6097]
- [no] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Talking to rex in your submarine generates an error, happened in a multiplayer campaign
![image](https://user-images.githubusercontent.com/55637865/122448238-edf2bc80-cf7a-11eb-9abf-245d762899f1.png)

**Version**
v0.14.6.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26798b8bcf7637976ef063576b645b09793dcc2d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
