### ISSUE TITLE
Destroying reactor with grenades didn't deplete fuel rods

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6098]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
destroying the reactor with frag grenades didn't deplete the fuel rods like a meltdown would

**Steps To Reproduce**
throw several frag grenades at a working reactor

**Version**
0.14.6

**Additional information**
melting down the reactor by overheat still depleted the rods

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fa77ce70058c0092cd9012b860a77f1a0975b15

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
