### ISSUE TITLE
broken nuclear reactor outputs signal?

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6099]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
a broken nuclear reactor still outputs signals, at least the temperature
unlike broken navigation terminal or other devices (battery, doors)
expectation was that no signals are outputted from a broken reactor

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.6 stable

**Additional information**

**Comment by Regalis11** [comment]
I don't see a problem with this: it could be useful if you want to build some kind of a circuit that detects when the reactor is broken.

**Comment by Tsunder** [comment]
It's inconsistent behaviour compared to afaik all other devices when broken. doors state_outs aren't sent, navigation doesn't send, junction boxes don't send, batteries don't send

It's not useful for detecting brokenness either as sending a signal (0) when broken would be indistinguishable with a shutdown reactor, or a reactor going at 0%/insufficient fission/no fuel. Detecting a lack of signal is a non-issue for circuit purposes.

**Comment by Tsunder** [comment]
also i think it's way cooler for reactor temperature readings to stop at 10000 after a meltdown rather than going to 0
