### ISSUE TITLE
Linux: Game is not able to join server

### ISSUE THREAD

**Issue by oscarr-reyes** [Regalis11/Barotrauma#61]
The game is not able to join any game on linux version

OS tested: Debian/Ubuntu 16.04.1 x64

**Comment by Regalis11** [comment]
Couldn't reproduce this on Ubuntu 16.04. What kind of an error message do you get? "No response from remote host", "content package does not match"...?

**Comment by oscarr-reyes** [comment]
no, i get the error "failed to initialize client (method or operation is not implemented)"

here is the screenshot of the error
![screenshot from 2017-12-03 17-31-25](https://user-images.githubusercontent.com/5789159/33530612-010edefa-d850-11e7-9634-211cf49d0dcc.png)

**Comment by juanjp600** [comment]
Type `mono --version` in a terminal so we can know which version you're on, and if possible, update to the latest version.
