### ISSUE TITLE
NPC's want grab diving suits and ultimatly wont fix leaks singeplayer

### ISSUE THREAD

**Issue by Autisem** [Regalis11/Barotrauma#610]
NPC's dont grab diving suits. Even if they see the leak they cant grab the diving suits, and since they FIRST have to grab the diving suit before they will start fixing the leak, this means that they will just fail.  [I made a small gif to showcase this](https://gyazo.com/b582c7dde6d80af0f3d271330c449b3b). It can be replicated simply by making a leak in aegir mark III(haven't tested other subs but I presume the same results). Making sure a NPC that is set on fixing leaks see it. And then watch as he/she runs to the airlock and just go left to right as you saw in the GIF.

**Comment by Regalis11** [comment]
Fixed in the dev branch

**Comment by Autisem** [comment]
That was quick
