### ISSUE TITLE
Crash after creating a new single player game (Access to the path '...hashcache.txt' is denied.)

### ISSUE THREAD

**Issue by NaitTrip** [Regalis11/Barotrauma#6100]
After selecting a submarine and everything else, when the start button is pressed, the game crashes (the same story with the character and submarine editor), I have not tested the multiplayer, but I can say that some old savegames are loaded, and the training is also loaded (but sometimes the console is shown with an error ( without crash))

Latest version of Thunder Under The Ice so far (out 3 hours ago)

Here are the crash logs
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/6672698/crashreport.5.log)
And another one, from single player mode
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/6672726/crashreport.6.log)

**Comment by Regalis11** [comment]
Thank you for the report! The crash reports seem to indicate that the game is for some reason not allowed to access the file "E:\Steam\steamapps\common\Barotrauma\Data\hashcache.txt". I'm not entirely sure how that can happen, but I'd try doing the following:
1. Navigate to that path and find the "hashcache.txt" file.
2. Right-click the file, select "Properties"
3. Make sure the "Read-only" checkbox isn't selected in the "General" tab
4. Go to the "Security" tab, and make sure the current user has permissions to read and write to the file.

I hope that helps, if not, please let us know! Sorry for the inconvenience.

**Comment by NaitTrip** [comment]
That's the problem, I don't have this file, and after reinstalling it did not appear, I think I need to find this file somewhere and manually add it to the game folder (if you thought the antivirus was somehow related with that, no, it's not his fault)

**Comment by NaitTrip** [comment]
Ok, I downloaded the pirated version, found this file in the Data folder and uploaded that to the Steam version of the game, but it still didn't work, and after many restarts, after some voodoo magic, now everything works if anyone has a similar problem, here is this file.
[hashcache.txt](https://github.com/Regalis11/Barotrauma/files/6678664/hashcache.txt)

All I can say is to disable the antivirus when starting the game or give special permission to Steam or the game folder, since the antivirus prevents Steam or the game from using the "new" file.
