### ISSUE TITLE
can interact with items when on periscope

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6101]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
interaction with items/installations isn't disabled when player is on a periscope

**Steps To Reproduce**
1. have a camera/turret close by periscope
2. get on periscope
3. interact with nearby objects via periscope

**Version**
0.14.6

**Additional information**

https://user-images.githubusercontent.com/5103517/122473136-6fece080-cf8f-11eb-8ff8-a3577d3a1b28.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fae30cb7831fca4ff9f253abd1ed1e538acfbde6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
