### ISSUE TITLE
console (Failed to parse the string "color gui.green" to color)

### ISSUE THREAD

**Issue by Jake-V-CMD** [Regalis11/Barotrauma#6104]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
apparently this bug is about the color in the upgrade interface, it only appears when I try to see the guns customization sectios
hope this helps :)

**Steps To Reproduce**
I'm not quite sure but after the update start to happen, just opening the upgrade interface and going to the guns customization section triggers the bug, I hope you'll see it too...

**Version**
0.14.6.0 Windows version

![image_2021-06-17_220545](https://user-images.githubusercontent.com/82491493/122490338-2a90d900-cfb8-11eb-8f57-f323ba5c24e0.png)

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I couldn't get this to happen (also tested switching the language to Spanish in case that had something to do with the error). Are you using any mods?

**Comment by nake90** [comment]
Hello. I also get the same issue every time, as explained above.
I just bought and installed the game, no mods nor workshop items in any way.

My language is also set to Spanish, and I am on Linux.

**Comment by AloranMX** [comment]
Today i got this error, it seems that is related to "latin american spanish" language option, i re start the game with english and it doesn't happen again

**Comment by Ek-Videogames** [comment]
> Today i got this error, it seems that is related to "latin american spanish" language option, i re start the game with english and it doesn't happen again

The character `‖` isn't part of standard ascii character set, and is actually encoded as three characters `â€–` in UTF-8.

Although I have no real clue why its only causing issue on Spanish, I guess maybe it thinks `â` is the beginning of a word - since in Spanish it would be seen as an allowed character - rather than part of an encoded command character?
