### ISSUE TITLE
Ais use oxygen masks and diving suits at the same time.

### ISSUE THREAD

**Issue by 1v01** [Regalis11/Barotrauma#6108]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When there are many floods and the AI needs diving suits (abyss suits in my case). The AI does not remove their oxygen masks when putting the diving suit. So they end up using both at once.

**Steps To Reproduce**
Have leaks that grow bigger and the sub floods. Then click on the AIs to play as them and check what they are wearing.

**Version**

Stable v0.14.6.0 (Windows 10).

**Additional information**
This is on my old singleplayer campaign from 0.13 and unstable 0.14, also I have a few mods (3 mods - EK utilitys begin the bigest one). Haven't tested it in a new campaign.

**Comment by itchyOwl** [comment]
It was an oversight that I had forgotten to fix. Implemented in Regalis11/Barotrauma-development@a27fbcb.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
