### ISSUE TITLE
Pick-up bug of Underwater Scooters

### ISSUE THREAD

**Issue by OmegaSybers** [Regalis11/Barotrauma#6109]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you drop a scooter on the floor, you can't pick it back up. Not even cutting the floor under it and letting it drop a floor beneath does help.

**Steps To Reproduce**
This bug happened multiple times on multiple ships already. To reproduce you simply drag the scooter out of a tool box or your hands and let it drop on the floor

**Version**
0.14.4.0 on Windows 10 64-bit

**Comment by aeondez** [comment]
I am not getting this issue. Tested multiple times.

Version
0.14.4.0 on Windows 10 64-bit

**Comment by Regalis11** [comment]
I'm afraid I could not get this to happen either.
