### ISSUE TITLE
[0.1400.6.0] Endworm is only enemy that spawns in abyss

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6113]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

It is seems like charbdys got very low chances of actually showing up in abyss (i seen couple, but most of time it is still endoworm only)

**Steps To Reproduce**
1. launch new campaign
2. get out on first level
3. start going into abyss triggering abyss monsters to come

or just use `leveleditor` or `quickstart` lol

**Version**
0.1400.6.0 stable, windows 10 pro

**Comment by Regalis11** [comment]
This most likely happens as a result of https://github.com/Regalis11/Barotrauma/issues/6063 (which has been fixed, but the fix didn't make it in time for the update). Gave this a quick test and charybdises seem to be just as common as endworms in the latest dev version.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
