### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Pod-vodnik** [Regalis11/Barotrauma#6114]
**Description**
An error was found in the translation of the item "Capsule for pulsed laser" and "Chain gun ammunition".

**Steps To Reproduce**
Item Description Window\Fabricator Window.

**Version**
v0.14.6.0    OS: Windows 10

**Additional information**
![Screenshot_1](https://user-images.githubusercontent.com/63470746/122594626-b0785700-d080-11eb-9504-c088cfd47ab1.png)
![Screenshot_2](https://user-images.githubusercontent.com/63470746/122595037-46ac7d00-d081-11eb-8473-0f1b51ed6165.png)

**Comment by Regalis11** [comment]
The descriptions were added https://github.com/Regalis11/Barotrauma-development/commit/9825c36b, the text didn't make it to this localization batch but will be translated in the next batch.
