### ISSUE TITLE
Small Planter Boxes have "Uproot" Msg even when empty

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#6115]
Easily reproducable. The planters constantly have the [E] Uproot message when placed down, even when there aren't any seeds in it.
Place one down yourself and see it happen. Multiplayer and singleplayer.
May be related to https://github.com/Regalis11/Barotrauma/issues/6116

**Comment by aeondez** [comment]
I get this a lot when hosting Multiplayer servers. Other players on the server have the same issue as well.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ebef134e7c4f0ee4e4f2a8df5226a73eed484c8d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
