### ISSUE TITLE
Planter Desync Issues make plants "nonexistent" for clients

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#6116]
[Bug, Networking]
This one is kind of a doozy but reports of it have been popping up all over discord for both modded games and unmodded games since the 0.14.6.0 update. A lot of people are experiencing this issue, all the time.
This seems to be a desync issue c. 
When planting something in a planter in multiplayer, it appears as though the seed is removed from your inventory, but the planter doesn't look like there's anything inside of it (The light is off, nothing is moving in it). As far as the client seems to be concerned, there isn't: Nothing grows, and the player is offered more opportunities to plant something while holding a seed.
Players playing campaign, however, will note that when the next round starts (after docking or undocking from an outpost, or moving through a natural formation), a plant will appear in the planter as though it's been there all along. This points to the players just not being able to see the plant they've planted, but it still existing serverside.

If someone has pictures of this it would be appreciated. Might be related to https://github.com/Regalis11/Barotrauma/issues/6115

**Comment by aeondez** [comment]
I sometimes go through 20-30 seeds before they finally take root. Room size and seed type do not seem to be relevant.

**Comment by ParadoxSong** [comment]
I can confirm this problem even as host - in fact, I once had everyone but me be able to see it, and have had no one be able to see it at all and it didn't appear in the next round.

**Comment by Regalis11** [comment]
I can no longer reproduce after the fix I implemented for https://github.com/Regalis11/Barotrauma/issues/6115, moving to QA

**Comment by Regalis11** [comment]
Nvm, was still able to reproduce this by enabling simulated latency. Should be properly fixed now: https://github.com/Regalis11/Barotrauma-development/commit/d66cd0224e5a188385ac31b290cf94c785502a3f

**Comment by Veritius** [comment]
I've been encountering this issue _as_ the host, in a MP server with no players except me. Both modded and unmodded.
https://user-images.githubusercontent.com/45957058/125218776-f1256200-e306-11eb-9220-f8553ad15224.mp4

**Comment by ParadoxSong** [comment]
On Unstable?

**Comment by Regalis11** [comment]
@ParadoxSong The fix isn't publicly available anywhere yet, but will be included in the next Unstable (which we'll be releasing soon).

**Comment by thegrb93** [comment]
Pls hotfix stable. So damn annoying

**Comment by Rokvach** [comment]
This seems to still be an issue to an extend. 

Commented on the testing doc

> Seeds still kind of vanishes when planting them in MP, the rate seems to be much less than the current version of the game. Still, the problem exists.

Moving to Misc

**Comment by ParadoxSong** [comment]
Can confirm the problem still exists though significantly lessened. Encountered a plant disappearing after fertilizing, though it remained visible for the clients, just not the host.

**Comment by JoneKone** [comment]
![Screenshot from 2021-09-21 18-21-33](https://user-images.githubusercontent.com/1114115/134199318-2bae9e53-e13b-4ec5-9f36-9294d974ae16.png)

I just planted every single planterbox with a seed. I'm the only guy on the server, ping 83/118  dedicated host/metal on hetzner.

**Comment by Regalis11** [comment]
No known steps to repro, closing
