### ISSUE TITLE
Sometimes mission markers mark positions outside playable area

### ISSUE THREAD

**Issue by baroknugen** [Regalis11/Barotrauma#6117]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One marker for thresher swarm spawned outside the map, outside the playable area, when playing with 'kill thresher swarm' mission. I don't think this has happened to us before. Everyone saw the same marker placement.

**Steps To Reproduce**
Launch a campaign mission with thresher swarm repeatedly until at least one mission marker on the sonar interface is placed to the left and above the original spawn location of the sub. We have not tried to reproduce this issue.

**Version**
0.4.6.0 (Windows/Linux).
Host player was playing on windows

**Additional information**
We did go left of the map, trying to chase the marker but could not reach it.

**Comment by Krzeszny** [comment]
Did you mean version 0.**14**?

**Comment by baroknugen** [comment]
Yes, I did mean 0.14.

**Comment by Regalis11** [comment]
Thank you for the report! I gave this a couple of tests, but couldn't so far couldn't find a level/mission where this occurs. If anyone happens to run into a seed where this occurs, or has a campaign save where it can be reproduce, posting it here would help us a lot in diagnosing this.
