### ISSUE TITLE
Minor GUI bug in Wiring Mode

### ISSUE THREAD

**Issue by civilCornball** [Regalis11/Barotrauma#6121]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/48499004/122648202-1226d880-d0f6-11eb-9990-061be2d5e705.png)
In wiring mode, it is possible to have **this** occur.
It's easily fixable by entering and exiting wiring mode again.

**Steps To Reproduce**
1. In wiring mode, click the "hide equipped gear" button to the left of the portrait. This hides the bar.
2. Click the portrait. Normally, this hides the portrait. However, this seems to cause the "equipped gear" bar to reappear.

**Version**
Barotrauma v0.14.6.0. The Windows release, revision 12d7084c07.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/19dcf451a573d7ac776d376c69d0c2f164d8f7d7

**Comment by Rokvach** [comment]
Tested, seems to be working correctly. But is there a reason as to why we don't just hide this part of the UI entirely? It doesn't really have any purpose being visible in the wiring mode. Moving to Misc for further evaluation. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ffaa6653-7d64-4d60-b764-940123fccd47)

**Comment by Regalis11** [comment]
That's a good point. Implemented in https://github.com/Regalis11/Barotrauma-development/commit/c6f2a76b0429d78c7391918291c7ff9945bc7013

**Comment by Rokvach** [comment]
Just a visual issue, your cursor changes  from a arrow to a pointer when you have your mouse over the area where the portrait should be

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ab45e65e-d069-422e-bdc5-ad53c13c75e6)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91b3d94643677c5960f9d884246678be38c11907

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
