### ISSUE TITLE
Bot gunner shoots through my own sub to target pirates while on drone gun of the Kastrull

### ISSUE THREAD

**Issue by jakebonz** [Regalis11/Barotrauma#6122]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was on a pirate hunt mission.  The pirates came from above and to the right of my Kastrull.  Their damaged sub had taken on water and pushed the both of us to the sea floor.  I was operating the railgun and I had noticed fire coming from below.  I had discovered that it was my drone gun firing straight upwards through the ship to hit the pirates.

Video: https://clips.twitch.tv/PrettiestOptimisticSnailPeanutButterJellyTime-zVD0eWuwqjWCtPwx

**Steps To Reproduce**
Use a Kastrull on a pirate hunt mission.  Put a bot on the drone gun.  Approach the pirates in such a way that the pirate sub is above you and to the right.  In the 1:30 position is the best way to describe it.

**Version**
0.14.6 according to the exe.  Windows 10

**Additional information**
Your game is fun as hell.  Keep up the good work!

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@666f7fa.

**Comment by itchyOwl** [comment]
Here's a save file for easier testing: [https://app.zenhub.com/files/93301055/f3277e4d-7306-4bc2-9c94-a6b8413eef42/download](https://app.zenhub.com/files/93301055/f3277e4d-7306-4bc2-9c94-a6b8413eef42/download)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
