### ISSUE TITLE
Automatic Reactor Control doesn't appear to be functioning properly.

### ISSUE THREAD

**Issue by RoshTMG** [Regalis11/Barotrauma#6123]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There appears to be some issue with how the automatic option, and by extension, AI reactor management works in regards to generating the right amount of power for current reactor load. At the moment, if you put the engine to 100% in one direction with the batteries charging at at least 50% on a sub like the Dugong, and then set it to auto, the reactor will set itself in such a way that most systems in the sub will under-voltage. A player managing the power can manually fix this issue. I've included a streamable link in the reproduction section below, just in case I'm not clear enough. Note that it works as it did before with a mass excess of power, but a single normal fuel-rod no longer powers the sub as it should(or as it did), even with an ARC.

**Steps To Reproduce**
1.) Load into a vanilla sub with a stable power system, like the Dugong.
2.) Have the AI turn on the reactor, and then set the engine to 100% in one direction after stabilizing the sub.
3.) Go down to engineering, make sure batteries are charging at default 50% recharge rate.
4.) Watch reactor auto control settle to just below optimal power range indicated by the red arrows, and stay there, no matter how much you play with it and then set it back to auto.

https://streamable.com/4dn8q5 (video of the above, just in case.)

**Version**
v0.14.6.0 (Thunder Under The Ice) - Windows 10

**Additional information**
I happened across it while designing a custom sub. Before the update, all methods of automated reactor control seemed to work fine. After the update, all automated reactor controllers, even vanilla ones were under-voltaging and performing extremely poorly. I thought it may have just been a problem with my custom sub, so I tested on the Dugong to see if the same problem happened, and it does. I'd also like to point out that it has something to do with batteries. I can't reproduce the issues if the batteries are not charging at all, or are charging at an extremely low recharge rate, like 10% or so. There also maybe some issue with how it's displaying the readout for turbine output. I don't think this was happening before the update, and I'd revert if I could to check.

**Comment by Tsunder** [comment]
doesn't seem like a bug with reactor control, but rather AIs &/ fuel grade

**Comment by Krzeszny** [comment]
It's not a bug it's a feature :) The automatic mode isn't "smart", it's just automatic. What you did in the video was smart and at the same unintuitive. You lowered the turbine turbine speed and increased the power output at the same time.

The reason for this behavior is that the turbine lowers reactor's temperature, and too low temperature lowers the output. Lowering the turbine in some cases may bring the temperature back up, increasing output.
The automatic mode tries to match output to load, but as you can even see in the video, it can't (even in manual mode) do that, as it is limited by fission rate. 

There are 2 solutions: use manual mode to balance turbine speed, or increase the fission rate by upgrading the reactor or adding/changing fuel rods.

**Comment by Regalis11** [comment]
Krzeszny is correct, this isn't a bug. In the video the load is very close to the reactor's maximum power output, and there isn't really a way to keep everything in the optimal range with just one rod.
