### ISSUE TITLE
ocassional mass item disappearance / desync in multiplayer

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6125]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Occasionally (trigger somewhat unknown), items will disappear en masse across an entire team in multiplayer (PVP).
Some notable/frequent disappearences so far have been: Morphine, Steroids, Diving Suits
By disappear, I mean they do not appear in the clients inventory ("my X disappeared! did someone steal...") but serverside they are still there in the player's inventory. (Confirmed by my own diving suit "disappearing" while I were wearing it, and I went into high pressure area without death, despite the client side displaying unsuited High Pressure visual effects. I also got the low O2 Affliction Icon but it didn't seem to advance)
Seems to be indiscriminate to whether the client is host or not.
Seems to happen more frequently with often moved items (morphine, steroids, diving suits are often moved to different places/inventories/inventory slots)
some time after (several minutes?), the items will start reappearing, usually on the floor, around where people who owned them spent a lot of their time (i.e., steroids sometimes found under the captain's position at helm)
some clients may see the items, some might not.

**Steps To Reproduce**
1. play multiplayer with 8+ people and PVP mode?
2. move items around a lot? placing in cabinets/different inventory slots, by using drop on empty/swapping?

**Version**
0.14.6 stable

**Additional information**
has occurred in 0.13 as well
the bug has occurred on ships both large and small, from dugong to humpback and bigger.
usually the people I play with include inter-continental players. (150+ ping)
no console messages popped up when this occurred

words: network desync disappear items missing multiplayer PVP

**Comment by Tsunder** [comment]
Caught an instance of the act on video - the diving suit just goes poof while on the ladder!!:

https://user-images.githubusercontent.com/5103517/134759353-23e81634-7de0-4e78-912f-3c895d877739.mp4


Has mostly occurred with diving suits and morphine, frequently used/moved items (And in pvp gamemode - steroids)

Ocurrence is maybe 0-4 times in 60 minutes, could happen multiple times in one match.

**Comment by TristanTurcotte** [comment]
I encountered this issue today while playing multiplayer with 1 other person (<100 ping, Humpback submarine) on 0.15.13.0, the 20+ morphine that we had stored all disappeared, including morphine that was being held by a player (This morphine was either just purchased at the previous station, or was crafted during the mission). The items disappeared on level transition when we docked at a station. We had just completed a wreck salvage mission.

During that same mission we had a metal crate filled with 4 stacks of salt bulbs and 2 stacks of pomegranates lose its contents randomly as well (This occurred while playing, without any level transition). One player was filling the crate as plants grew, then the other player checked the crate and saw its inventory, 2 minutes later the player who was filling the crate noticed its contents had reverted to what the crate had at the beginning of the mission.

**Comment by toneo-** [comment]
Also had this one today (albeit modded) in a 3-person multiplayer campaign. All of us had multiple cases of items disappearing at random, mainly diving suits, but also things like weapons and magazines. Most of the time they were just gone, but on a couple of occasions a couple would just 'turn up' elsewhere on the submarine.
The most egregious case was when we were exploring an alien ruin and my diving suit suddenly disappeared. Another player saw me apparently drop my suit in the ruin, but I didn't pop from the pressure. My oxygen ran out before I could get back to the submarine.
