### ISSUE TITLE
preview images for subs not updated

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6126]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
preview images of some subs aren't updated (new hardpoints)
- [x] azimuth
- [x] humpback
- [x] berilia
- [x] kastrull
- [x] orca
- [x] r-29
- [x] typhon
- [x] typhon2

**Steps To Reproduce**
look at the preview images

**Version**
0.14.6 stable

**Additional information**
think that's every sub other than the dugong lol

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f0ef9547ea1070c9199fee80cb2acf63400b17d7
