### ISSUE TITLE
Wrecks automatically undocking submarines, that were linked in sub-editor

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6127]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wrecks automatically undocking submarines, that were linked in sub-editor upon loading in level
generated in `leveldeditor`
![Barotrauma_9e3Bny0QKv](https://user-images.githubusercontent.com/42521948/122671898-6eaaf600-d1d1-11eb-9836-e13d1d1c9751.jpg)

WARNING: SPAWNING WRECK VIA `SPAWNSUB` WONT TRIGGER BUG, SO USE `LEVELEDITOR` WITH 6 WRECKS SETTING ONLY
spawned with `spawnsub` command
![Barotrauma_32jHqtDtcy](https://user-images.githubusercontent.com/42521948/122671932-926e3c00-d1d1-11eb-9be1-d429e936096f.png)

**Steps To Reproduce**
1. use test wreck provided in end of report
2. upload it as mod
3. restart game to make sure everything is working
4. go to `levelgen` and set wrecks amount to 6 so game will spawn all vanilla wrecks + needed one
5. find it via `debugai` and `freecam`

**Version**
0.1400.6.0 stable, windows 10 pro

**Additional information**
Test wreck:
[Outpost_Wrecked_test.zip](https://github.com/Regalis11/Barotrauma/files/6682172/Outpost_Wrecked_test.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b46822412485e786c348bac1c4ac579e5f918ac

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
