### ISSUE TITLE
Chat Not Appearing

### ISSUE THREAD

**Issue by MCPolice5** [Regalis11/Barotrauma#6131]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hello! My bug is that every time I join any barotrauma server, be it dedicated or hosted, after 10 - 30 minutes I will not be able to see anything in chat. Players joining/leaving, people typing in chat, or admins using msg/say commands. This happens in both alive and dead chat.

**Steps To Reproduce**
Again, it just randomly occurs every 10 - 30 minutes. I am not dead when this happens.

**Version**
According to Steam: v0.14.6.0

**Additional information**
I have not attempted to see if this occurs in a singleplayer world. The chat does however show me how I have died.

**Comment by MCPolice5** [comment]
Please help me, this is making it impossible to admin my dedicated server.

**Comment by Regalis11** [comment]
No known steps to repro, closing
