### ISSUE TITLE
You still can get crushed by static submarine 

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6132]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you still can get crushed by static submarine with 0 movement at all

**Steps To Reproduce**
1. go to `levelgen`
2. use this seed: `eg2UpLMX`
3. go to this part of map and park submarine in designated zone 
![image](https://user-images.githubusercontent.com/42521948/122684178-9c616080-d20c-11eb-8031-8ebc56904f33.png)
4. swim into this little area 
![image](https://user-images.githubusercontent.com/42521948/122684197-b307b780-d20c-11eb-8f62-69dddfdeeea9.png)
5. get crushed
![Barotrauma_E31WtMvl3j](https://user-images.githubusercontent.com/42521948/122684219-d2064980-d20c-11eb-9561-e9e2680d5ade.png)

**Version**
0.1400.6.0 stable, windows 10 pro

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/98d346ded70ba19a396c1cfefb73a6b2e4fd04e5

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, working correctly. Closing.
