### ISSUE TITLE
Canister shell's penetration broken?

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6134]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I don't know exactly how the penetration is calculated, but here's something i noticed:
A bonethresher has 300 health and a 90% resistance armor, the canister shell deals 770 damage if every pellet connects.
Canister shell's pellets have 20% penetration, which i assume should ignore 20% of the thresher's 90% protection (armor still has 72% resistance if that's the case), so every pellet should deal 26,6 damage, so if they all connect to the armor it'd deal 292,6 damage.
But in-game, bonethresher is still 1shotted by a canister shell, is my math crap or am i right?

**Version**
v0.1400.6.0

**Additional information**
i suggest just completely removing the canister shell's penetration

**Comment by Udrakan** [comment]
Does it have 90% resistance all over it's body?

**Comment by LePiromano** [comment]
> Does it have 90% resistance all over it's body?

Not on the head, it has a damage multiplier there. But i've tested specifically landing every shot on the body

**Comment by Krzeszny** [comment]
According to my math, the canister shell deals 803 damage vs no armor and vs 90% armor it should deal 224.8 damage.

**Comment by Regalis11** [comment]
I gave this a quick test, and couldn't find any discrepancies in the damage values. Almost none of the limbs have 360 degree armor coverage, and the last few parts of the tail aren't armored, so it's pretty difficult to only hit the armor with the canister shell.
