### ISSUE TITLE
[Pathfinding] Wrong door waypoint on Berilla

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6140]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Node 2313 looks like a door which **stops AI crew from passing it**. AI keeps trying to open a non-existent door at the waypoint.

![Barotrauma_aT18LEbGbG](https://user-images.githubusercontent.com/10529134/122837816-0ead7000-d2f5-11eb-9b3c-042917e63e3a.jpg)
**Video:**
https://user-images.githubusercontent.com/10529134/122837561-96df4580-d2f4-11eb-9770-689d6877d2be.mp4

**Steps To Reproduce**
Load the Berilla submarine. 

Clicking on the waypoint removes the door tag.

**Version**
14.6.0 Windows Steam

**Comment by Krzeszny** [comment]
Anyone? This is an actual bug that breaks AI

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ccaf3e9c982a45055a508b6f615743a047001518

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
