### ISSUE TITLE
End-Of-Round Bugs

### ISSUE THREAD

**Issue by ParadoxSong** [Regalis11/Barotrauma#6141]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items in the deconstructor that are not yet deconstructed are deleted entirely from the game.
Players who are still respawning in the campaign when the round ends have their skills reset rather than reaper's tax applied (obviously unintended behaviour since they elected to take the penalty to keep their stats), ~~and the corpses with all items are destroyed at this point, not producing a duffle bag.~~
**Steps To Reproduce**
Described.

**Version**
Windows 10, Thunder Under The Ice (0.14.6.0).

**Additional information**

**Comment by Regalis11** [comment]
The duffel bag issue should be fixed now (got a separate ticket about that https://github.com/regalis11/barotrauma/issues/6213)

**Comment by Regalis11** [comment]
> Players who are still respawning in the campaign when the round ends have their skills reset rather than reaper's tax applied

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cd897d7ce50ed2d6a11baec5a71eb99362d79492

**Comment by Regalis11** [comment]
> Items in the deconstructor that are not yet deconstructed are deleted entirely from the game.

Unfortunately I wasn't able to reproduce this. I placed a couple of items in the deconstructor and started it up:
![image](https://user-images.githubusercontent.com/14351070/124952957-5cc4b200-e01d-11eb-9cf4-42719830fb85.png)

I then entered the next level, and the items hadn't disappeared:
![image](https://user-images.githubusercontent.com/14351070/124953444-d5c40980-e01d-11eb-907f-5ee358f83770.png)

I couldn't spot any issues when the deconstructor was off when leaving the level either (all the items were present in the input slots).

**Comment by ParadoxSong** [comment]
Hey, we only saw it occur once (we avoided it afterwards) so I wouldn't
waste a lot of time on it. The steps you followed are exactly what we did
so its possibly incidentally fixed or intermittent. We'll keep an eye out
and re-report it if we see it after all these fixes make it to stable.


Thank you so so much for fixing these things!!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
