### ISSUE TITLE
Pirates run out of oxygen and die

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6143]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pirates will run out of oxygen in their suits and die, without refilling from fairly full oxygen tanks. This makes it possible to simply out-live the pirates by O2 as long as there's a flooded area in the pirate sub. (It takes about 5.5 minutes to run out of o2 for a single tank)

**Steps To Reproduce**
1. fill pirate sub with water, keep it filled
2. wait 5.5 minutes
3. pirates start asphyxiating to death

**Version**
0.14.6 stable

**Additional information**
pirates also won't put O2 into oxygen generators to refill oxygen, but that's a problem for like 30 minutes later or something

AI oxygen air diving suits

**Comment by itchyOwl** [comment]
Couldn't repro the main issue. I kept the pirate sub flooded for a half an hour, but the pirates managed to survive without suffocating.

What were you doing while tesing the issue? Where you in the freecam, watching the pirates, or were you actually playing the game and doing some other things? If the latter is true, it could be that the AI or the physics still got disabled for the pirates (even though they shouldn't) in some cases.

Fixed the pirates not putting empty oxygen tanks in the oxygen generator in Regalis11/Barotrauma-development@c3a571f.

**Comment by JoneKone** [comment]
Yeah on regular game play the pirates are little inept and don't have the resources to survive attrition combat. They don't have ppl up keeping systems refilling o2 tanks. etc. They could do with more fuel rods, welding fuel and every suit/oxygen cabinet locker wired to power.

**Comment by itchyOwl** [comment]
Pirates can't run out of power anymore: Regalis11/Barotrauma-development@a524d94.

Assigned @danielasteljoki to handle wiring the divingsuit containers and oxygen tank shelves to the power grid, so that they would refill the tanks.

**Comment by linax3-genuine** [comment]
15.13 (latest steam release)
i was taking my time in the beginning part of the level and at some point(1 hour?) i received "pirates defeated" message. i assumed, they got killed by monsters, as i have seen them being boarded by raptors.

**Comment by itchyOwl** [comment]
The monsters shouldn't spawn near the pirates if you are far away from them. And the monster shouldn't spawn if you idle near the start location either.

**Comment by linax3-genuine** [comment]
i was not idle. i was exploring alien station and a sunken submarine. also by saying "assumed", that implies, that i dont know the reason.
i have to clarify, that i have seen them being boarded by monsters, in other runs. not in this particular one.

**Comment by danielasteljoki** [comment]
As far as divingsuit containers and oxygen tank shelves go, they're now wired in pirate subs also.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
