### ISSUE TITLE
Delay components with delay set to 0 do not transmit signals.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#6150]
- [x] I have searched the issue tracker to check if the issue has already been reported.
![2021-06-22 23_06_32-Barotrauma](https://user-images.githubusercontent.com/41012467/122992452-cfdbf080-d3ae-11eb-83b9-281eeaa5d38e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9c9b20c1f2c7aa08c954aa8a47e4d02a31e3d1a6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
