### ISSUE TITLE
laser shots frequently invisible in multiplayer

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6151]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
pulse laser's particles/graphics are invisible often in multiplayer
 when shooting long range (out of visual sight, 20+m)
the beam thing just doesn't appear

**Steps To Reproduce**
shoot at subs in PVP pewpew

**Version**
0.14.6

**Additional information**
video sometime maybe

**Comment by Regalis11** [comment]
I'd suspect this is caused by the same issue as https://github.com/regalis11/barotrauma/issues/6136

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
