### ISSUE TITLE
Loading a Campaign saved stuff after docking and changed the roles of 2 crew members 

### ISSUE THREAD

**Issue by RandoGamer** [Regalis11/Barotrauma#6156]
- [] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I loaded a campaign last played 6/21/2021 at 10:15 (time and date listed on campaign) and after loading in I was unconscious and another crew member had injuries from before we left the campaign where had a free-for-all between the crew members thinking it would not carry over. Along with this, the jobs of two players had changed, one from medical officer to captain and the other captain to a mechanic. For the medical player, they only had a medical officer as a job. The missions we did before docking were delivering clown equipment, terminating a swarm, and activating a beacon station.

**Steps To Reproduce**
I got no idea, I guess doing three missions and after docking, start shooting each other and then leave and come back.

**Version**
Version 0.14.6.0 Windows 10 32bit

**Additional information**
The player who was captain and changed to mechanic also changed from Caucasian to African American despite never messing with their character's appearance afterward cause we move to do something else

**Comment by Regalis11** [comment]
No known steps to repro, closing
