### ISSUE TITLE
Multiple translation errors and inconsistencies in German

### ISSUE THREAD

**Issue by LookiDev** [Regalis11/Barotrauma#6158]
This issue has been reported on the Russian translation (#4553), but as there are many errors in the German translation as well, I want to point out that it is not limited to that language.

**Description**
There are multiple translation errors in the German translation. Here are some examples:

- many of the items in the sub editor aren't translated, such as: hull, gap, waypoint, labels, structures, walls, ...
- "legacy" elements in the Sub editor are translated with "Legende" which means "legend" or "key on a map"
- in the texts for labels, there are misleading translations as well: label.flood is translated with "Fluten" (this should be "Leck"); label.fire is translated with "Feuern" (this should be "Feuer"); label.hatchoverride is translated with "Lukenumgehung" (misleading, should be something like "Lukenüberbrückung")
- there are definitely more, I could add them when I get to them ingame.

**Steps To Reproduce**
1. start up the game in German.
2. start a game and look at the translations (e.g. the two leftmost signs in the command room of the Typhon 2)

**Version**
Windows 10, v0.14.6.0 (12d7084c07)

**Comment by Master-Miner** [comment]
On the same Note (german translation):
The labels in the pumps for pumpin->ein and pumpout->aus can be misinterpreted as ein->on and aus->off.
Possible non misleading translations would be:

pumpin->rein & pumpout->raus (into & out of) 
pumpin->hinein & pumpout->hinaus (into & out of)
pumpin->füllen & pumpout->leeren (fill & empty out)

All three would be better understood than the current one but the first is probably best.

**Comment by pucgenie** [comment]
junction box LOAD should read "Last" (or "Belastung") instead of "Laden".

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/88cdd5e1b7b9264936375f96c844e79d652408ce

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
