### ISSUE TITLE
Revolver round crafting seems dodgy

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#616]
I cant tell why, but I cannot combine the aluminium after crafting revolver rounds as a client.

Nor can I select the option to craft with it.
there was 1 bar copper of and 3 units of 50% aluminium each was used to craft a revolver round itself once.

I know if these changes were caused by my server mod (Which im sure this server im on is not using) it would remove the items correctly via the entity spawner, as well as control the condition correctly despite a desynced MD5, something else seems wrong here in item sync / the GUI menu itself

**Comment by rico6822** [comment]
I remember I had to craft something using 25% condition item. That item had 75% condition and could not be used.
