### ISSUE TITLE
Something in the files for music or ambience(which is tied to music) is causing horrible noise.

### ISSUE THREAD

**Issue by RoshTMG** [Regalis11/Barotrauma#6161]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Most of the time when you play, the ambience/audio track is paired with an almost unnoticeable hissing, or mild TV static noise after awhile if you're not wearing headphones. If you are wearing headphones, it is VERY noticeable, loud, and irritating. I'm not sure if this happens on all audio tracks, but it's grating enough that it has caused me headaches many times playing the game over long periods.

**Steps To Reproduce**
1.) Start the game, wearing headphones of course.
2.) Set your music to 100%, though it is still noticeable with headphones at 10% or more.
3.) Quickstart into a submarine of your choice.
4.) Wait for an affected audio track.
5.) Play for 45 minutes and then take off your headphones, allowing the blood that has pooled in the ear cups from your mangled eardrums to flow out freely.

**Version**
v0.14.6.0 - Thunder Under The Ice.

**Additional information**
Phenomena in action.
https://streamable.com/dxamnq

**Comment by Regalis11** [comment]
Addressed alongside https://github.com/regalis11/barotrauma/issues/5932

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
