### ISSUE TITLE
R-29 Docking hatch is repairable, but instead of by wrench it requires a welder in hands

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6163]
**Description**
![image](https://user-images.githubusercontent.com/59519434/123185575-8797fd80-d496-11eb-8763-f48c6281b7da.png)

**Steps To Reproduce**
Have top hatch damaged
Try to repair it

**Version**
Stable

**Additional information**
-mod doesnt alter hatches or welders
-might be a case for other hatches too

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@cd082f9

**Comment by ekqvist** [comment]
And the same issue seemed to be with the bottom docking hatch, too. That should be fixed in Regalis11/Barotrauma-development@947bdc1.

**Comment by ekqvist** [comment]
Went through the vanilla subs' docking hatches and found a few more: the Berilia top hatch, the Hemulen top and bottom hatches, and the Venture bottom hatch. These should be fixed in Regalis11/Barotrauma-development@112a364.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
