### ISSUE TITLE
Can't use heal interface for transport VIPs

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6166]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't use heal GUI on the mudraptor's VIP human, even when they were unconscious 

(Also can't use it on the mudraptor itself)

**Steps To Reproduce**
mudraptor transport mission

**Version**
0.14.6.0 stable

**Additional information**
Played in multiplayer

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/874c4fcc555c21bd6a1d26741ef371f35ad197ce

**Comment by Rokvach** [comment]
Trying to heal the Mudraptor crashes game, moving to Misc
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/eb166baa-e9c0-4127-81e9-96f6c0ce0725)

**Comment by itchyOwl** [comment]
Added some null checks in Regalis11/Barotrauma-development@3c50f81. I'll leave testing to you, as I don't have a save where that mission appears.

**Comment by Rokvach** [comment]
Tested, wasn't able to heal the mudraptor anymore, as the mudraptor isn't required to stay alive this is working correctly. Closing

**Comment by Regalis11** [comment]
Still caused a crash in multiplayer, fixed in https://github.com/Regalis11/Barotrauma-development/commit/0828d8d840949316153eec7e02564891087abb3e

**Comment by Rokvach** [comment]
The health interface does still briefly show up in multiplayer, but its so brief that I am not fast enough to use the interface, but should the option to access the interface be visible at all? At least in singleplayer I don't even have the option to access the health interface for the passive mudraptor.

**Comment by Regalis11** [comment]
3rd time's the charm...? https://github.com/Regalis11/Barotrauma-development/commit/005fc31ce8942f74b74ae3aa8f38f7203c43ba75

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
