### ISSUE TITLE
Crash when trying to target a sub weapon with a contextual Operate Weapons order

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#6167]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Targeting the weapon outside (not the periscope) with the contextual order will crash the game. I don't think the order should even be available when targeting the weapon itself.

**Steps To Reproduce**

1. Go outside the sub
2. Open the contextual command interface on a sub weapon
3. Attempt to give the Operate Weapons order
4. Game will crash

**Version**
v0.14.6.0

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@33da8e9

**Comment by Maxthefatcutecat** [comment]
Similar issue with Flesh gun of alien ruins. Was recreated in sub editor.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
