### ISSUE TITLE
Stacking half used items

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6168]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
there's some problems when you have stacked half used items, like explosives that got damaged from another fire or explosion. When you end a round a start another round in a campaign every stack of half used items will be either dropped in a duffel bag and be un-stacked or will dissapear entirely.

**Steps To Reproduce**
shoot a stack ic-4/compound n with a grenade launcher or welder bomb it and start another round

**Version**
v0.1400.6.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3f9c0448f0e30a8b4155e3cf37937fe66f15fe1

**Comment by Rokvach** [comment]
Tested by placing a stack of IC-4 into a cabinet and used a welder bomb next to the cabinet and then re-docked to the outpost, the IC-4's weren't stacked anymore but laying on the floor next to the cabinet with only one of them being still inside the cabinet. So the items still seems to unstack. Moving to Misc.

**Comment by Regalis11** [comment]
Right, the previous fix only addressed items in character inventories. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/04c50efb1d464c9c7d034861ed9f6ae25d26793a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
