### ISSUE TITLE
depth charges go trough doors

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6169]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i believe if there's a door on top of a submarine, and that door has a bit of hull on the exterior side, depth charges will think they're inside the sub so they'll go trough the door.

**Steps To Reproduce**
Drop a depth charge from the typhon into the dugong's docking hatch

**Version**
v0.1400.6.0

**Additional information**
https://user-images.githubusercontent.com/55637865/123340468-a643d600-d522-11eb-963e-18a11eb4a230.mp4

**Comment by ubertpendragon** [comment]
Doors and Hatches in general still have trouble blocking projectiles, even with the last update

See:
#5264

#853

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8d5499860d183b1507dadec02e2d3723062757f3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
