### ISSUE TITLE
Sonar Does not Respect the Speed of Sound

### ISSUE THREAD

**Issue by GenericDM** [Regalis11/Barotrauma#6170]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sonar pings take the same amount of time to reach the edge of the console regardless of zoom level. This implies that the speed of sound is directly linked to your console's zoom level, which I doubt is intentional. This makes it bothersome to navigate at high zoom levels due to obstacles being much closer than at low zooms, while also taking the same amount of time to be seen.

**Steps To Reproduce**
Zoom all the way out on a navigation console, ping sonar and see how long it takes to reach the edge. Zoom all the way in, repeat previous steps and realize it's the same.

**Version**
v0.14.6.0 Windows

**Additional information**
![zoomout](https://user-images.githubusercontent.com/34109002/123342673-12afdc80-d505-11eb-9fc5-8b34c2519f34.gif)
![zoomin](https://user-images.githubusercontent.com/34109002/123342679-13e10980-d505-11eb-97e4-4f91a1fd71c4.gif)

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
