### ISSUE TITLE
Docking hatch can be docked to docking ports and vise versa

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#6173]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Docking hatch can be docked to a docking port and vise versa.

**Steps To Reproduce**
On Remora in sub editor place docking hatch in a free space near submarine and try to dock drone to it 

**Version**
Stable v0.14.6.0

**Additional information**
![image](https://user-images.githubusercontent.com/62324831/123358742-b954b580-d5b7-11eb-8592-a7b253bb7775.png)
![image](https://user-images.githubusercontent.com/62324831/123358727-b5c12e80-d5b7-11eb-8448-1a6809606b45.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9925ec6c8b11ce8269f0414a6bee6d19a8b4067

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
