### ISSUE TITLE
After crash  I see "Submarine equality check failed". And this error too

### ISSUE THREAD

**Issue by dawideka1221** [Regalis11/Barotrauma#6176]

**Comment by Regalis11** [comment]
This seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/6159

**Comment by Regalis11** [comment]
Nvm, the previous ticket was closed, reopening this one

**Comment by Regalis11** [comment]
Possibly fixed in Regalis11/Barotrauma-development@269ca20

**Comment by Rokvach** [comment]
There hasn't been any encounters to this still happening in the Unstable build, seems to be working correctly. Closing.
