### ISSUE TITLE
server browser default sorting

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6177]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
server browser default sort puts a lot of empty servers in the front
![image](https://user-images.githubusercontent.com/5103517/123496762-b2e62e00-d5f7-11eb-8e34-37b46ba39d7c.png)

This is bad for inexperienced/casual players trying to find a game/bad optics
better to show populated servers and/or nearby servers by default

**Steps To Reproduce**
1. shut down game, restart (to clear settings?)
2. open server browser
3. wait for server list to finish loading

**Version**
0.14.6.0

**Additional information**

**Comment by Regalis11** [comment]
Atm the servers are listed in the order Steam happens to report the available servers to the game. I suppose we could do some changes to the way they're sorted, but I'd consider this more of a feature request than a bug report, so I'll close the ticket.
