### ISSUE TITLE
Stun gun spawns half empty

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6178]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
stun gun only spawns half full, with 1 dart instead of 2

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.6

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/98e6f205697f791c078920de3fe3a9af821e214c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
