### ISSUE TITLE
Ballast flora impossible to kill, sends error messages ("Received BranchRemove for a branch that doesn't exist")

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6181]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It's sometimes impossible to kill flora in multiplayer despite hitting visible branches and roots

![image](https://user-images.githubusercontent.com/73229309/123514984-f4c5b180-d695-11eb-8aad-5c03d0616bb2.png)

0.14.6.0

**Comment by ubertpendragon** [comment]
#6234

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/70986a7c04df1cc6f8a6362be47a6c24287b4331

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
