### ISSUE TITLE
1st Release of TUTI only escort missions ever selected.

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#6183]
I found one issue while playing. When I select only the abandoned outpost, pirate, and escort missions during casual missions mode, escort is the only mission chosen. I don't think the game ever selected either the outpost or pirate missions while they were selected along with escort missions.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d5a1abf88006bfd52cf81288b9412354c5f53a58

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
