### ISSUE TITLE
Failed to load a new campaign level (nullref exception in WreckAI constructor)

### ISSUE THREAD

**Issue by TehSpidah** [Regalis11/Barotrauma#6187]
The version is 0.14.6.0. operating system: Mac

Shortly said, the bug causes the game to quit to main menu whenever I try to start it. No matter if I have mods enabled or not, if I start a new game or load an old save or try to connect to a server it always quits immediately.

I'm not sure as to a way of reproducing it, it seems to only occur for me specifically

The bug simply appeared while I was playing in my single player campaign and it ended with a crash. Now when I boot the game and load my save it switches to the loading screen and then quits to main menu after reaching 100%

This is what console shows:
<img width="821" alt="Снимок экрана 2021-06-27 в 00 20 08" src="https://user-images.githubusercontent.com/86535845/123526434-8823d480-d6e0-11eb-82b3-f302339a5103.png">

<img width="821" alt="Снимок экрана 2021-06-27 в 00 20 43" src="https://user-images.githubusercontent.com/86535845/123526452-b0133800-d6e0-11eb-9ca5-425e19b8f62f.png">

Then, after it quits for the first time since the game was booted, shows this if I try to load my save again:

<img width="810" alt="Снимок экрана 2021-06-27 в 00 35 31" src="https://user-images.githubusercontent.com/86535845/123526491-f23c7980-d6e0-11eb-94fe-8305ff53de31.png">

<img width="807" alt="Снимок экрана 2021-06-27 в 00 35 45" src="https://user-images.githubusercontent.com/86535845/123526493-f8325a80-d6e0-11eb-81d5-e3921c2bf667.png">

This cycle repeats if I reboot the game: first try to load -> loading screen -> quits to main menu; second and other tries -> quits to main menu

My playthrough involved several mods, including a submarine. Yet, as I already mentioned, even if I try to begin from scratch on a vanilla sub with mods turned off or connect to some server this bug still appears.

Sub editor and character editor seem to work fine and overall there were no troubles whatsoever until this day.

It may sound similar to #6160 and other cases of crushes, but I think it's different

**Comment by Regalis11** [comment]
Thank you for the report!

For some reason it seems the game is failing to create a wreck properly, but I'm unsure how exactly this can happen. It could be related to some of the mods you've installed - would it be possible to list the mods you were using (mods that modify/add wrecks in particular)?

**Comment by TehSpidah** [comment]
Yes, I used this one that affected wrecks - [New Wrecks for Barotrauma](https://steamcommunity.com/sharedfiles/filedetails/?id=2184257427&searchtext=new+wrecks)
And these mods:
[Ulysses 2.28 ](https://steamcommunity.com/sharedfiles/filedetails/?id=1768666616&searchtext=Ulysses)(adds a sub I've mentioned)
[Surgery Technology Expansion Modification ](https://steamcommunity.com/sharedfiles/filedetails/?id=2261916290&searchtext=surgery)(an unfinished mod)
[Thalassophobia: Ultra Science Content Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2003946282&searchtext=thalassophobia) (Didn't get to use content from this one at that moment)
[BetterCharacterHead](https://steamcommunity.com/sharedfiles/filedetails/?id=2078692889&searchtext=better)(I don't think it's important, but I'll leave it here anyways)

Also, for some reason after I manually deleted all the game files and placed the save back it worked fine. Although some weird occasional freezes appeared, but that might not even be relevant

**Comment by Regalis11** [comment]
Thank you, I think I managed to figure this out now. Seems to happen when some of thalamus organs in the wreck have been placed outside the wreck's hulls. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07e5682fc213352ed2a4e0f2be0534a23eaed15a

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
