### ISSUE TITLE
Storage container has no sprite depth

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6191]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Storage container's sprite depth is not defined, which defaults it to 0.001 apparently.
expected was something similar to the depth of Crates

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.6.0 stable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/27f0bccce027387bdf5909578aa7eb47a767e0a2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
