### ISSUE TITLE
Broken Doors sprite depth weird

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6192]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Broken Doors are defined to have a sprite depth of 0.051 but actually appear at 0.500

2. Broken doors appear in front of characters and I don't think it's intentional:
0.051 seems like a typo of 0.510, the fixed door's sprite, which is slightly behind characters

**Steps To Reproduce**
break a door/hatch

**Version**
0.14.6.0

**Additional information**
suggest sprite depth of 0.509, or 0.510 if the layering engine reliably places the broken sprite in front of the fixed sprite

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/166d0db55f6e2ebfdb6ddd50c3bf411d59dd58dc

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
