### ISSUE TITLE
Can't craft additional oxygen tanks in fabricator if the output slot is full

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6193]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempting to craft a oxygen tank in the fabricator fails if there is crafted oxygen tank in the output.
The output oxygen tank has to be removed to continue crafting
Expectation is that it will craft and stack the two empty oxygen tanks

**Steps To Reproduce**
1. craft an oxygen tank in fabricator
2. leave it in the output slot
3. craft a 2nd oxygen tank (fails)
4. 
**Version**
0.14.6.0

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a84977978fb6eae1be923a4526cdbef81392cbd7

**Comment by Rokvach** [comment]
Is there some reason why we don't allow stacking even the non-empty ones?

But works correctly on the empty ones, but will still move this to Misc as I think it would be better to just stack every item that is stackable.

**Comment by Regalis11** [comment]
The commit message was a bit misleading, the intention was to allow stacking all items that are stackable, including full tanks. Seems to work as expected.

**Comment by Rokvach** [comment]
It seems that not all item categories stack in the fabricator even though they do stack elsewhere, I didn't go through all the items but I think its restricted by the item grouping/category 

Couple that I noticed

Harpoon
Sin component
Ballistic fiber
Screwdriver

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9625eeeef954445ec90cb823aedfed4ab9bfb2eb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
