### ISSUE TITLE
[Modded] Artifact events don't work for certain mods.

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#6195]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Artifacts events have been stated to not be working for the following mods:
https://steamcommunity.com/sharedfiles/filedetails/?id=2085783214 - Improved Husks
https://steamcommunity.com/sharedfiles/filedetails/?id=2108010462 - Xan Monsters
https://steamcommunity.com/sharedfiles/filedetails/?id=2127575896 - Xan Monsters 2

However they apparently work for this one:
https://steamcommunity.com/sharedfiles/filedetails/?id=2197353935 - Extended Monsters

I've looked extensively at the random events files of all four mods and I can't find a determining factor for why one would be working properly over the other.

The random events file I've personally made (for Improved Husks) was built on top of the vanilla random events file, however vanilla random events has been confirmed to spawn artifacts correctly, so I'm not sure where the issue resides.

**Version**
v0.14.6.0 Stable

**Comment by Regalis11** [comment]
None of the event sets in the first 3 mods include any artifact events.

**Comment by Emanthealmighty** [comment]
> None of the event sets in the first 3 mods include any artifact events.

All of the mods mentioned above have artifact events.
![image](https://user-images.githubusercontent.com/9964331/125074628-d318f100-e0bd-11eb-89c3-e6355a284208.png)

I received a very specific report stating that those 3 mods didn't have functioning artifact events even though they did have artifact events in their events files, so I thought it was worth checking out, even though I wasn't fully sure if I was able to replicate the issue at first. 
I have however tested the mods some more and was actually able to encounter artifacts both in singleplayer and multiplayer, so I'll be asking for more information to the original bug reporter to see if the issue can be narrowed down a bit more, because I do believe there is an issue there somewhere.
