### ISSUE TITLE
Pirates get ballast flora and cry

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6197]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When pirates get ballast flora, they make no actions to respond to it.
This can result in very easy wins for the player if they wait long enough/are slow enough. Additionally, it feels really weird to break open a pirate ship and see it's heavily infested with flora.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.6.0

**Additional information**

**Comment by M61Dev** [comment]
Implemented on bugfixes

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
