### ISSUE TITLE
Error code: EECA616DF2BA4F9511EEC52AB1F63877

### ISSUE THREAD

**Issue by PolenH** [Regalis11/Barotrauma#6199]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every time I launch the game even after verifying within minutes of doing anything in the game it gives me this bug.

**Steps To Reproduce**
There is no way in my mind of reproducing this bug the only thing I did was move files from the mod folder which were subs I downloaded and copied them to my sub folder so I could edit my subs on different pcs.

**Version**
Most recent

**Additional information**
I am just wondering to fix this because I have just got this game and played it for 20hrs and I love it

**Comment by Regalis11** [comment]
Thank you for the report!

I've never seen this kind of error code before and couldn't find any places in the code that could be throwing an error with this kind of a message. Where exactly does this error appear, is it shown in the debug console or does the game crash with a popup containing this code? Is there any other info in the error message in addition to this code?

**Comment by PolenH** [comment]
I'll send the file it is indeed a popup after the crash
