### ISSUE TITLE
Items in Single Player Disappear Upon Completing Task- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#621]
I had my welding tool and plasma cutter filled with welding fuel tank and oxygen tank and more items like that. Welding fuel tank and oxygen tank disappeared. Is this intended in case if a mission took too much time to finish in order to punish player for wasting time or it's a bug?

**Comment by NilanthAnimosus** [comment]
Were these items per chance cargo items? were they empty at the end of the round?

Was this a multiplayer campaign game? items do not save in inventories yet in multiplayer campaigns.

**Comment by rico6822** [comment]
It was single player (see title).

No, they were not mission cargo items. I bought them personally from the store.

Some of them had less, than 50% condition, but even items with full condition were removed, such as ammo to my gun.

**Comment by Regalis11** [comment]
When exactly did they disappear? Mid-round or when you returned to the campaign map?

**Comment by rico6822** [comment]
They disappear upon starting new mission.

**Comment by Regalis11** [comment]
By mission completed, do you mean after finishing the objective or returning to the map screen?

**Comment by rico6822** [comment]
After completing mission this happens and I don't know if even in case of returning to map screen this happens too.
