### ISSUE TITLE
Duffel bags don't spawn when dead crewmembers or players are present on the sub at round end in campaign.

### ISSUE THREAD

**Issue by PetMudstone** [Regalis11/Barotrauma#6213]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a campaign when dead crewmembers, AI or player, are present on the sub at round end their bodies are not replaced by duffel bags containing the items on their person in the next round. This can result in the loss of many valuable items if other players do not recover them from corpses before they despawn. Duffel bags will still replace dead crewmembers if they respawn mid-round.

**Steps To Reproduce**
In a campaign round, make sure there are dead crewmembers (don't let them respawn) on your sub when said round comes to an end. After the round ends and the next round starts there will be no duffel bags where their corpses were.

**Version**
0.14.6.0, Windows 10

**Additional information**
I initially encountered this bug when playing modded multiplayer with my friends. Further testing had the bug appear in unmodded singleplayer and multiplayer so I do not believe any mods are causing it however.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/51867e737302643f52ee630ff8b2610d9c090f6e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
