### ISSUE TITLE
silly items requested for sale in shop

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6216]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
shop can request silly items for sale, like a Shipwreck ID card:

![image](https://user-images.githubusercontent.com/5103517/123887180-066dba00-d91f-11eb-9b9b-94c2ae83550f.png)

**Steps To Reproduce**
luck

**Version**
0.14.6.0

**Additional information**

**Comment by Regalis11** [comment]
Not a bug
