### ISSUE TITLE
Abyss Diving Suit Description Typo

### ISSUE THREAD

**Issue by tastesliketriangle** [Regalis11/Barotrauma#6218]
**Description**
The entity description for the abyss diving suit says it protects from pressure down to 100,000 meters, but in the source it only protects down to 10,000 meters.

**Version**
0.14.6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9d7a401779798aba13ac23a8902d9c2a692888b

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
