### ISSUE TITLE
[Configs/Design] No explosiondamage or internaldamage modifiers on vanilla diving suits

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6220]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Diving suits protect only from 4 out of 6 damage-type affliction identifiers:
`blunttrauma`, `gunshotwound`, `lacerations`, `bitewounds`
They don't protect from `explosiondamage` or `internaldamage` afflictions
**Steps To Reproduce**
n/a

**Version**
v0.14.6.0

**Additional information**
Many months ago diving suits had `afflictiontypes="damage"`.

I can imagine that a rubberized titanium suit could protect from explosions, as shockwaves tend to not travel from one medium (water) to another (metal and air).

**Comment by Krzeszny** [comment]
Speaking of damage, maybe diving suits should reduce Stun?

**Comment by itchyOwl** [comment]
We can't use affliction type "damage" here, because the suits shouldn't protect against internal damage or organ damage. We don't use internal damage for many things anymore, and all the things are such where the source of the damage is something unknown or generic, i.e. not an external hit. Closing the ticket.

**Comment by Krzeszny** [comment]
> We can't use affliction type "damage" here, because the suits shouldn't protect against internal damage or organ damage. We don't use internal damage for many things anymore, and all the things are such where the source of the damage is something unknown or generic, i.e. not an external hit. Closing the ticket.

You've mentioned internal damage but it's not used and organ damage is something caused by poisons.
What about explosion damage a.k.a. Deep Tissue Injuries? It's damage from explosions (which suits should protect from?)
