### ISSUE TITLE
My game disconnects after I go from/to any mission/station (Submarine equality check failed)

### ISSUE THREAD

**Issue by dawideka1221** [Regalis11/Barotrauma#6222]
-have searched the issue tracker to check if the issue has already been reported.I can't find someone who has same issueDescriptionAfter crash I see "Submarine equality check failed". And this error too
**Description**
After crash  I see "Submarine equality check failed". And this error too
![image](https://user-images.githubusercontent.com/86360781/123102897-cb0e4f80-d435-11eb-9b70-2ff92872aff5.png)

**Steps To Reproduce**
To do this I host server and click start mission
**Version**
Vanilla

**Additional information**
![image](https://user-images.githubusercontent.com/86360781/123104774-8aafd100-d437-11eb-8f84-0394ce1bfac9.png)
{Console Scrypt}
am experiencing this from beginning, I tried reinstalling game or making another seed

**Comment by dawideka1221** [comment]
- [ ] I want to know how I could fix this

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I can't think of what could be causing this off the top of my head. Are you using some kind of a custom/modded submarine? If not, it might be worth a shot to verify the integrity of the game files to make sure all of the files are in tact (see https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335).

**Comment by dawideka1221** [comment]
Sorry for not contacting for week but this worked I think game was detecting ship incompatible in files with host and players so game couldn't load ship correctly
