### ISSUE TITLE
Sub Editor - Shuttle Shell A Glass A (wrecked) sprite error

### ISSUE THREAD

**Issue by DabsCrabs** [Regalis11/Barotrauma#6224]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The sub piece "Shuttle Shell A Glass A (Wrecked)" loads incorrectly, causing the sprite to repeat and create a large tower.
![Screenshot (91)](https://user-images.githubusercontent.com/86172252/124059357-96c7ff80-d9f0-11eb-96c1-36aff4e4ca47.png)

**Steps To Reproduce**
Open submarine editor, look up "Shuttle Shell A Glass A (Wrecked)", voila.

**Version**
Current Version "Thunder Under The Ice", I have a Windows Operating System

**Additional information**
I've verified the steam files, restarted barotrauma and reloaded the sprite. As well as that I had my friend check the editor to see if he had the same bug and it was the same for his game as well.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/31064cb74233031bd0f535210b565a635c463a48

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
