### ISSUE TITLE
Dugong distress signal WiFi isnt set for cross-team communication

### ISSUE THREAD

**Issue by Stallfighter** [Regalis11/Barotrauma#6227]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Apparently there are WiFi module connected to signal check inside Dugong wreck. Is uses oscillator to send message [[DG-35 DISTRESS CALL]] every 10 seconds on channel 911. HOWEVER, WiFi component does not have "Allow cross-team communication" option enabled, making that feature completely useless.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9eb7c185b5075617c6ffa0b4642d1f9f6885063e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
