### ISSUE TITLE
Loader base sprite inconsistency

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#6228]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have a Loader Base and buy a gun for the hard point then the, new loader is not aligned with the Loader base sprite that was placed in the editor.

**Steps To Reproduce**
place loader base next to a different loader sprite side by side, set up the loader base with a hardpoint. run campaign and buy a weapon for the hardpoint. compare sprites positions for the loaders

**Version**
0.14.6.0 w10

**Additional information**
it bothers my "ocd" :P

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/368c11b0f307c54be8223776cd6b2913288ab622

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
