### ISSUE TITLE
pirates can spawn and be stuck impossibly in caves

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6229]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pirates sometimes spawn in caves
said caves are sometimes physically not big enough to let the pirate ship in/out

**Steps To Reproduce**
random pirate missions

**Version**
0.14.6.0

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/776cc1abdd3943fa4f1911daea71bbd07d197c18

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
