### ISSUE TITLE
To prevent griefing, players should have an account before playing online.

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#623]
This is probably a feature that would need to be implemented once the game cost money, players would need an account to connect to servers, which could ban the barotrauma account, as well as their IP. That way VPN's would be a less popular method of griefing servers.

**Comment by BlueTheKing** [comment]
Well yeah, once it comes to steam you will need an account and VPNs become basically useless.

**Comment by Momiro** [comment]
While I think steam would help, I don't think this will be a steam exclusive game, so I don't think it would rely entirely on steam servers.

**Comment by BlueTheKing** [comment]
Ah, i see. Yeah in that case bt accounts would help.

**Comment by NilanthAnimosus** [comment]
There is nothing to stop people simply creating more accounts, what method would you use to prevent someone simply registering 5? 10? 25? accounts.

This merely adds an extra step, its not like your paying or using real world details or something to register I imagine. It would help against VPN's by slowing them down but the steam version will have 0 uses for an account system.

I do think this won't be a steam exclusive game as the old masterserver would be kept around I think for places like GOG, so an account system would actually be a nice addition (But again

**Comment by Momiro** [comment]
Well, at least, the cost of the game would be a deterrent for most people. If someone has enough income to keep buying the game, then yeah, that's another problem, but at least this would stop a majority, I think.
