### ISSUE TITLE
Bots ignoring broken devices

### ISSUE THREAD

**Issue by MateusJK15** [Regalis11/Barotrauma#6230]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since the last update, when i order multiple bots to fix broken devices (both electrical and mechanical) and there's multiple devices broken, only 1 or 2 go fix something and the others become idle even if there's multiple devices not being fixed by anyone, instead of only becoming idle when all the broken devices are already being fixed by someone. When the round starts (single player campaign) the bots behave normally, but after some time they start to ignore broken devices and it persists between rounds. It only happens with broken devices though, they behave normally in case of leaks of fire.

**Steps To Reproduce**
Order multiple bots (5 is a good number) to fix broken devices and type "explosion 30000 0 0 0 0 100" in the console to destroy all the devices in the sub and it will eventually happen.

**Version**
Barotrauma 0.14.6.0 Thunder Under The Ice update running on Windows 8.1

**Additional information**
Custom submarine
![20210702002823_1](https://user-images.githubusercontent.com/86162808/124333290-1cbb8600-db6a-11eb-9d41-0f16f1fb0470.jpg)

Default Dugong (i disabled the lighting for a better visualization). Look at those 3 mechanics at the lower deck, they are like "those 2 idiots are fixing the sub already, i will just watch".
![20210702185907_1](https://user-images.githubusercontent.com/86162808/124333312-2ba23880-db6a-11eb-9d73-37535e8be84f.jpg)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c814a5e.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
