### ISSUE TITLE
Pirates wallhack aim

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6232]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pirates aim directly at players through the submarine shell.
They have no practical way to know the position of a player, yet snipe them with unerring accuracy.

**Steps To Reproduce**
1. hide behind walls
2. get within gun range of pirate
3. get instantly zero'd in on despite having 0 LOS view

**Version**
0.14.6.0

**Additional information**
This makes for "defending" against pirate attacks extremely punishing compared to a more realistic/player-like making random hole/spray n pray until something is visible.

Consistently results in instant criticals/kills with railguns without vision through a full strength shell, and incredibly fast kills with coilguns. I don't know how they handle pulse lasers but given that those like 3 shot players in diving suits, I don't think it'd be pretty.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eece5b9cad84719f2fca23c2af42bdd8783a4d16

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
