### ISSUE TITLE
Pirate ships and beacon station can be deleted in the editor

### ISSUE THREAD

**Issue by WhySmau** [Regalis11/Barotrauma#6233]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Select a pirate ship/beacon station in the saves and delete

**Version**
v0.14.6.0 windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ee9229fcce9963ba7e7962cf01f98c812f2b1c2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
