### ISSUE TITLE
Multiple cargo missions reward calculation bug

### ISSUE THREAD

**Issue by ZimneMienso** [Regalis11/Barotrauma#6235]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Right now every cargo mission is basically calculated separately in terms of cargo space and rewards. For example one can take two cargo missions each allowing for up to 10 crates of cargo, while using Remora, which has 12 cargo space and, while practically transporting 12 crates in total, still be rewarded as if transporting full 20.

**Steps To Reproduce**
Take enough cargo missions at once for them to exceed the cargo space the submarine you are using has.

**Version**
0.14.6.0
**Additional information**
I haven't checked if this is a problem related to misinforming mission summary screen (in case you don't really get the full reward despite beeing told you do).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f02801407046fca56dc8c4c42b0199e0f706b9b5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
