### ISSUE TITLE
hull parameters not saved when item assembly/copying

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6236]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
hulls do not copy/save data for item assemblies/copypasting:
- ambient light
- room name
- is wet/avoid staying

**Steps To Reproduce**
make copy of a hull with modified settings

**Version**
0.14.6.0

**Additional information**

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
