### ISSUE TITLE
feature request: setting hardcoded variables in the console + storing these settings in XML or File + network syncing for it (If possible)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#624]
Something one could consider as my "All time # 1 wanted feature request since the dawn of time but left unmentioned for over a year"

Essentially a lot of this is what my mod essentially is constructed around, just not available to the console and done in a hardcoded manner in an XML file.

The serializable properties for various classes is something I particularly find both interesting and love about barotrauma, they seem to have settings for is savable/editable and such along with default values letting any classes variables be potentially exposed to the XML system for editing, Submarine editor and status effects and such.

Using a similar system (And this is code I only half understand so I've never tried this myself) hard-coded aspects of the game, like constants and values in classes that could be left to the server/local settings to decide.
Here are some examples of values that could be set by such a system most of which are what my mod already does and even syncs values of on join with mod clients or provides syncing support for when it comes to vanilla (such as fire syncing event handling for hulls when the speed was changed to prevent barotraumas deterministic nature becoming too problematic, though this wouldn't be an issue if these were synced in vanilla on join before midroundsync):
- The hulls deterioration rate of oxygen, oxygen transfer speeds
- The unbreathable percentage of hull oxygen
- The rate characters gain/lose oxygen and rate its used in the hull
- water flow force multiplier
- A husks incubation period
- The Min/Max voltage for electrical damage and minimum power
- The speeds of fire growth/shrinking, the ratio of oxygen consumption for active fires, water extinguish rate and tool extinguish rate multipliers
- The level of damage caused by fires
- The crush depth for characters and submarines
- The colour of the ocean water
- Maximum line counts for debugconsole and serverlog
- Maximum stored chat messages for the chatbox
- Maximum particle count
- Multipliers for reactor meltdown time
- Multiplier for relay max power (If a server wanted to bypass or edit this for older submarines, its something I do in my mod)
- Max voltage before a character is stunned for electrical fail
- The multiplier on collision damage
- The health lost per bleed icon / second
- Stats lost while unconcious
- Various settings used in the gameserversettings and user settings (Just to have a console way to set any of them fast without a GUI, such as the dedicated server)

the idea is to use something like serializable properties and to "Register" them with the debugconsole or a class that handles it which the debugconsole could draw from.

Having them sync with players (Sending a file or sending them which values have been changed from default) would be nice too if not required for about half of these.

Having the above able to be updated mid-match would be a good idea too (My mod already handles that by re-syncing itself with the mod clients, not sure how this should be handled to save on the networking usage for an event)

Finally, if possible, it would be nice if a custom content pack could specify what these values are, as to have it be defaulted to the game defaults, overridden by the content packs defaults, overridden by the server setting.

It may also be a good idea to have minimum/maximums built-in, for the sake of sanity checks.

(Perhaps defaulted in the default content pack?)
[ConsoleEditable, minval, maxval, Sync to clients]

**Comment by NilanthAnimosus** [comment]
As an additional note for example, various engines such as the source engine implement something fairly similar to the idea above, It also would have the benefit of being useful during debugging to simply change values in-game without using edit and continue or stopping the debugging for experimenting with.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
