### ISSUE TITLE
Pumps are off by default ):

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#6247]
Pumps are off by default as of v0.14.6.0, I may have missed the commit that may have reverted the changes about pumps from commit `006a70f`. But just making this issue report due to people getting confused why their pumps aren't working.

Version : 0.14.6.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d873be955c4ce48215ed32917022048adec4a380

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
