### ISSUE TITLE
VELOCITY_IN pin does nothing on autopilot

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6248]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the navigation terminal is set to AUTOPILOT, sending values to VELOCITY_IN will change the manual steering vector but not the autopilot

**Steps To Reproduce**
1. Button => OR with 0,0 output => VELOCITY_IN
2. Set a course with autopilot
3. Press button
4. Manual Steering vector is reset, but not autopilot

**Version**
 v0.1400.6.0

**Additional information**
Would be VERY useful for braking

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2369e7bb3f4e8d71602dcaa7f7d7372f99b1e625. Note that sending a single signal as you described is still not very effective, because the autopilot will quickly readjust the steering vector. If you want a more effective braking system, the signal should be sent for some time (depending on how long you want the sub to brake).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by ubertpendragon** [comment]
> 
> 
> Fixed in [Regalis11/Barotrauma-development@2369e7b](https://github.com/Regalis11/Barotrauma-development/commit/2369e7bb3f4e8d71602dcaa7f7d7372f99b1e625). Note that sending a single signal as you described is still not very effective, because the autopilot will quickly readjust the steering vector. If you want a more effective braking system, the signal should be sent for some time (depending on how long you want the sub to brake).

Sorry to be a bother but this isn't what the ticket was refering to

The issue is that the vector (or arrow, or target position) of AUTOMATIC control doesn't go to the center of the terminal, when you send 0,0.

It doesn't go the the sub's "current position". If it did, in the same way you'd flip the swith to "Maintain position", the sub would automatically apply counter force to slow down and brake

I am not sure what the change actually does; it's strange that the pin can control manual but not automatic
