### ISSUE TITLE
Increase Skill Level of Crew as Campaign Progresses-Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#625]
It would be interesting if crew could increase their skills by preforming actions requiring it.

Construction- Welding or cutting walls (both submarine and ruins), crafting items requiring construction skill, fixing devices requiring construction skill to fix.

Electrical Engineering- Rewiring devices, fixing devices needing electrical engineering skill.

Medical- Preforming CPR, using medicals, crafting items requiring medical skill.

Weapons- Hitting something with weapons or ranged attacks, detonating explosives

Xml files can be edited during modding for items needing electrical engineering to craft them or weapons skill.

Does this feature already exists and if not can we have it?

Final note: A mission has to be completed successfully in order to have their skills level up. This prevents crew from spamming actions requiring leveling to not make themselves "overpowered" (in short: OP). Otherwise crew would enter station they haven't even moved from, after they level themselves and repeat that again.

**Comment by Regalis11** [comment]
Implemented in the dev branch
