### ISSUE TITLE
sub editor crashed when handling large strings

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6250]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i input a ~950 000 or characters for the output of the sigcheck and the game started lagging hard

![image](https://user-images.githubusercontent.com/5103517/124496938-1efb2b80-dd88-11eb-8bc3-970e30218f19.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.6.0 stable

**Additional information**

**Comment by Regalis11** [comment]
I'd say you're asking for this if you set the maximum output length this high. 😅
