### ISSUE TITLE
Clients timeout the connection if loading takes more than 10 seconds

### ISSUE THREAD

**Issue by Coryf88** [Regalis11/Barotrauma#6253]
- [x] I have searched the issue tracker to check if the issue has already been reported.
#5702
#3512

**Description**
If clients take longer than 10 seconds to load after entering/leaving a station, they get disconnected with only the following in the console log:
> Received a disconnect message ()
> Attempting to reconnect...

Clients are also placed into spectator, instead of taking control of their body, after reconnecting via the automatic reconnect or manually.

**Steps To Reproduce**
1. Enter/leave a station in multiplayer.
2. Have the client take more than 10 seconds to load.

**Version**
0.14.6.0 (Windows)

**Additional information**
Occurred multiple times when leaving stations, while doing a campaign with [Into The Abyss: Campaign Overhaul for Seaworthy Men](https://steamcommunity.com/sharedfiles/filedetails/?id=2005463692).

https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaShared/SharedSource/Networking/Primitives/NetworkConnection/NetworkConnection.cs#L14

A disconnect message reason for timeouts would be nice too...
https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/SteamP2PClientPeer.cs#L219

**Comment by JoneKone** [comment]
Can confirm
![Screenshot from 2021-07-06 13-42-12](https://user-images.githubusercontent.com/1114115/124594907-057de080-de69-11eb-993f-938d54551f01.png)

**Comment by Ek-Videogames** [comment]
Can confirm this bug still exists in current build:

![image](https://user-images.githubusercontent.com/55356135/135769639-dfecf481-0f79-4ff5-aa8f-8e3788e2a8d4.png)

**Comment by Regalis11** [comment]
Possibly fixed in Regalis11/Barotrauma-development@269ca20

**Comment by Rokvach** [comment]
There hasn't been any encounters to this still happening in the Unstable build, seems to be working correctly. Closing.
