### ISSUE TITLE
water detector doesn't detect to bottom of its placement

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6254]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
water detector state_out doesn't detect to bottom of its apparent placement

**Steps To Reproduce**
place water detector at bottom of a hull
use water detector's state_out to measure presence of water
fill hull with miniscule amount of water
water detector says the room is dry

**Version**
0.14.6.0

**Additional information**
https://user-images.githubusercontent.com/5103517/124518100-9db98e00-ddb3-11eb-85b1-6e493484323b.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bec60e42401e087b4e1cfee959a7b4cd31dbf0b3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
