### ISSUE TITLE
pump with set_level -100 doesn't drain hull fully

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6255]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
pump with set_level -100 doesn't drain hull fully
it leaves a small quantity behind

**Steps To Reproduce**
use set_targetylevel = -100 on a pump

**Version**
0.14.6.0

**Additional information**

https://user-images.githubusercontent.com/5103517/124519023-1de0f300-ddb6-11eb-9427-a42f64a8e43a.mp4
video also shows the minor water detection discrepencies in #6254

**Comment by Regalis11** [comment]
This happens because neither the pump or the detector are at the bottom of the hull in this case.

**Comment by Tsunder** [comment]
the location of the pump is irrelevant 

the water detector doesn't actually control the pump at all, it's the memory component. 

this video and sub should display non-water detector control of the pump better.

https://user-images.githubusercontent.com/5103517/124557112-1f86d700-de07-11eb-9d2b-057e8e5608b3.mp4


[waterbox.zip](https://github.com/Regalis11/Barotrauma/files/6768018/waterbox.zip)
