### ISSUE TITLE
Kastrull drone ballast pump being inaccessable bugs out bots

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#6262]
Description
Bots will get stuck in drone doing random moves because the dron ballast pump gets down to the repair threshold.

Steps To Reproduce
Emp the drone and watch bots repair everything except pump. 

Version
Unstable V0.14.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5442f80717618a9859bd5be1c54a66149f3f5da7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
