### ISSUE TITLE
Subs download at the same time for everyone during a campaign.

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#6263]
- [x] I have searched the issue tracker to check if the issue has already been reported. Yes

**Description**
When starting a campaign that has the option for a lot of different workshop subs, the game forces new joins to download every single sub at the very start, causing a very long load time. 

**Steps To Reproduce**
Have a campaign with a lot of workshop subs, have new people join.

**Version**
V0.14.6.0

**Comment by Regalis11** [comment]
This is not a bug, the players need to have the subs the server is using to be able to play the campaign.
