### ISSUE TITLE
"Oops! Barotrauma just crashed."-window uses an unrecognizable and unreadable font

### ISSUE THREAD

**Issue by baroknugen** [Regalis11/Barotrauma#6264]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The window that spawns before a crash report log after a crash is unreadable because of the font it uses.
![bro](https://user-images.githubusercontent.com/85737030/124656885-1434b980-dea2-11eb-8abf-84d57dc8648b.png)

**Steps To Reproduce**
crash the game.

**Version**
0.14.6 Linux

**Additional information**
While the window has appeared, with the weird font, every time the games has crashed, I have not crashed the game intentionally. So I will also provide the crash log below.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6772404/crashreport.log)

**Comment by Regalis11** [comment]
The crash seems to be caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/6187, still need to look into why the font's getting messed up.
