### ISSUE TITLE
ExcessiveDesyncOldEventYou have been disconnected because your client was expecting a very old network event. Server

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#6266]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ppl are Disconnecting from my server constantly as they are getting kicked by the server saying ExcessiveDesyncOldEventYou

**Steps To Reproduce**
Keep a (Linux) side server on for a day and at some point ppl start to disconnect constantly, some connections work perfectly.

**Version**
Game version 0.14.6.0 (ReleaseLinux, branch release, revision 12d7084c07)

**Additional information**
We where mostly playing missions and few pvp in the middle.
The log's won't show the event, so i'm including screenshots of chat.

![Screenshot from 2021-07-06 22-59-06](https://user-images.githubusercontent.com/1114115/124660421-d7bb8a80-deae-11eb-9434-0cbe7cffa9e5.png)
![Screenshot from 2021-07-06 22-59-08](https://user-images.githubusercontent.com/1114115/124660413-d68a5d80-deae-11eb-9b0c-1fb30804367a.png)
![Screenshot from 2021-07-06 22-59-11](https://user-images.githubusercontent.com/1114115/124660403-d4280380-deae-11eb-911a-8fad6a36423f.png)
![Screenshot from 2021-07-06 22-59-04](https://user-images.githubusercontent.com/1114115/124660427-d9854e00-deae-11eb-96ab-36ef2f38b00e.png)
![Screenshot from 2021-07-06 22-59-02](https://user-images.githubusercontent.com/1114115/124660434-dab67b00-deae-11eb-900e-95607c9c7d44.png)
![Screenshot from 2021-07-06 22-58-59](https://user-images.githubusercontent.com/1114115/124660439-dc803e80-deae-11eb-8ffd-e95a0815e19c.png)

**Comment by gerakis** [comment]
Just now had this. Kicked every single player on my server. I had internet the whole time

![very old network event](https://user-images.githubusercontent.com/16128947/145521172-fb699608-02ad-45b0-a57d-fcf03614a8dd.png)
.
