### ISSUE TITLE
Add hardpoint customization to mission gamemode lobby

### ISSUE THREAD

**Issue by ahzidaljun** [Regalis11/Barotrauma#6268]
Before starting a mission gamemode match in multiplayer, it would be nice to be able to customize the sub's turrets via an upgrade interface within the lobby itself, especially for custom submarines designed with campaign progression in mind whose guns are mostly empty hardpoints, making them very ill-fitted for 100% difficulty matches.

![Screenshot_50](https://user-images.githubusercontent.com/72061961/124665436-19ced700-de83-11eb-9045-40f202a958a8.png)

This could also be available for PvP and other gamemodes as applicable. Maybe the amount of marks alloted for customization could be proportional to the difficulty slider, but it being infinite shouldn't be a problem.

**Comment by Regalis11** [comment]
Thank you for the idea, this could definitely be something to consider! The issue tracker is only for bug reports though, feature requests should go on the [github discussions](https://github.com/Regalis11/Barotrauma/discussions).
