### ISSUE TITLE
odd nest generation error

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6270]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
nest decided to spawn like 100m away from the cave it's supposed to be in
[coolnest.zip](https://github.com/Regalis11/Barotrauma/files/6773895/coolnest.zip)

**Steps To Reproduce**
use the save attached

**Version**
v0.1400.6.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7bdbfee4dee0e4566077a5759438b39147f8fbc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
