### ISSUE TITLE
No enemies at difficulty 70%+

### ISSUE THREAD

**Issue by NKGra** [Regalis11/Barotrauma#6271]
[ yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No enemies at all starting at ~70% difficulty in the single campaign or at 100% difficulty in a hosted multiplayer mission. 

**Steps To Reproduce**
Reach near the end of the campaign or play a multiplayer mission set to 100% difficulty.

**Version**
0.14.6.0, Windows 10.

**Additional information**

No mods. Tested with Orca and Remora.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/588af7d08afd7586fc4f4366f6b63a6269581d9e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
