### ISSUE TITLE
Respawn Shuttle Locked Me in, Before I Ever Left It White Docking- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#628]
I was in respawn shuttle and I docked. I left normally shuttle, but before I left it it locked behind me 10 seconds, before it had to leave automatically by itself and pulled me in, even when 75% of my body was already on the board of regular submarine.

**Comment by thegrb93** [comment]
It would be nice if the shuttle waited until the timer. I've gotten stuck on it before as well.

**Comment by rico6822** [comment]
I think the range of when it starts to leave by itself should be set to 1 meter of player's range instead of 0,25 meter or something like that.

**Comment by Rokvach** [comment]
This issue was by design, improvements should be coming in the next patch. Closing this issue as it should be solved.
