### ISSUE TITLE
Pirates stuck, trying to move through a rock formation

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6280]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Notice the rock formation at 2 o'clock

![Barotrauma_x3mdjji6HU](https://user-images.githubusercontent.com/10529134/124945867-d86b3280-e00e-11eb-8954-8e8b2e2922d5.jpg)

**Steps To Reproduce**
Unknown

**Version**
v0.14.6.0

**Comment by Regalis11** [comment]
This is probably impossible to reproduce without the seed/save. Are you sure the sub is trying to move through the formation? Based on the engine particles, it seems to be trying to move to the left.

**Comment by Krzeszny** [comment]
> This is probably impossible to reproduce without the seed/save. Are you sure the sub is trying to move through the formation? Based on the engine particles, it seems to be trying to move to the left.

I'm not sure where it was trying to move. We've already passed that mission so I can't provide more info.

**Comment by Krzeszny** [comment]
@Regalis11 A guy on #baro-general just got the same issue but it was on a random server they joined, so I can't help diagnose it.
![Barobug](https://user-images.githubusercontent.com/10529134/130798470-80a8d028-f3da-4051-95d2-e65304399d13.png)
