### ISSUE TITLE
connecting non-water detector signals into status monitor's water data input makes status monitor freak

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6281]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the status monitor water display for a hull with go up/down rapidly rather than display the inputted water data by the signal sender

**Steps To Reproduce**
1. make status monitor require water input
2. wire up a memory/ any other signal to the monitor, set the value to 10 or something
3. check status monitor

**Version**
0.14.6.0

**Additional information**
o2 input seems fine

https://user-images.githubusercontent.com/5103517/124981940-27f83100-e004-11eb-88bf-ec799c025634.mp4

[astraltor's campaign sub.zip](https://github.com/Regalis11/Barotrauma/files/6786925/astraltor.s.campaign.sub.zip)

**Comment by Regalis11** [comment]
This is an intentional feature, sending invalid data to the inputs makes the display freak out.
