### ISSUE TITLE
nuclear weapons do not damage ballast flora

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6282]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
nuclear weapons do not damage ballast flora
yet their components do

**Steps To Reproduce**
1. get ballast flora
2. use a nuclear weapon at it
3. ballast flora is fine and dandy

**Version**
0.14.6.0 stable

**Additional information**
suggesting: nuclear weapon deal very excess of the ballast flora's health so that it can be killed even if it's not a direct hit.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6b1ae9cab172e8a79ab3ca2dafa470dac1e5115b

**Comment by Rokvach** [comment]
Tested, no issues. Closing
