### ISSUE TITLE
[Sourcecode] targetitemcomponent, targetitself, targetcontainer are not implemented

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6283]
- [x] I have searched the issue tracker to check if the issue has already been reported.
Related to #2777

**Description**
https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/PropertyConditional.cs#L63-L75

**Version**
v0.1300.0.0

**Comment by Udrakan** [comment]
Found out about this the hard way yesterday kek

**Comment by Regalis11** [comment]
Yes it is. The attribute is read in the PropertyConditional constructor, this is just to prevent the attribute from being loaded as a separate conditional. All of these attributes are used in vanilla items and seem to be working correctly, but if you're having trouble using them, please create a bug report with some more details and we'll take a look.
