### ISSUE TITLE
Crash upon interacting with Beacon Station sonar/status monitor

### ISSUE THREAD

**Issue by elantzb** [Regalis11/Barotrauma#6284]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashed as I attempted to interact with the sonar/status monitor in a beacon station. I had already interacted with it before in order to start the station sonar, but was checking it once more to see how many baddies had been attracted, so I could plan my escape.

Twitch VOD here: [https://www.twitch.tv/videos/1081833898](https://www.twitch.tv/videos/1081833898)

**Steps To Reproduce**
(See VOD above for any missed details)
1. Use the attached save to (hopefully) test this. Pick up the missions described in the crash log. Choose Thresher Swarm mission.
2. Set Captain task to keep ship in-place. Descend through an ice spike and panic-weld all over the interior until leaks stop.
2. Defeat swarm, head to beacon station. Park and switch to Electrician. Grab combat diving suit, scooter, fuel rod.
3. Enter station. Start-up station reactor, fix leaks. Set non-automatic pumps to 100% "out." Set station sonar to "active."
4. Hesitate for a few moments, check containers for loot. Hear monsters outside.
5. Interact with station sonar/status monitor. 

**Version**
See attached Crash Log.

**Additional information**
Crash Log:
[crashreport_beacon_station.log](https://github.com/Regalis11/Barotrauma/files/6794015/crashreport_beacon_station.log)

Local Appdata Contents:
[appdata_barotrauma_contents.zip](https://github.com/Regalis11/Barotrauma/files/6794030/appdata_barotrauma_contents.zip)

**Comment by elantzb** [comment]
Probably an easy fix by checking for nulls or handling exceptions in the function on top of the stack trace.

**Comment by Regalis11** [comment]
Thank you for the report! I couldn't find a way to reproduce this, but added a null check that should prevent this from happening. https://github.com/Regalis11/Barotrauma-development/commit/a9a1fb000abd75d067ac2419b29f4e66737a8c93

**Comment by elantzb** [comment]
When's the code release?

**Comment by Regalis11** [comment]
Unfortunately we have no ETA for the patch yet.

**Comment by Rokvach** [comment]
No known steps to reproduce, I will keep this open until the end of the Unstable testing period and see if anyone happens to encounter it.

**Comment by Rokvach** [comment]
As there's no known steps to reproduce this and no encounters to this issue during the Unstable testing period, I will be closing this ticket. This ticket can be opened again if the issue resurfaces. Closing.
