### ISSUE TITLE
Performing CPR as a Husk causes a crash

### ISSUE THREAD

**Issue by mc-oofert** [Regalis11/Barotrauma#6289]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Controlling a husk and attempting to perform CPR on a human crashes the game.
**Steps To Reproduce**
1. "Control" a huskified character/husk
2. Find some random human to perform CPR on
3. CPR
4. Crash

**Version**
0.14.6.0

**Comment by mc-oofert** [comment]
It seems like this can only happen on servers and on a character that isnt yours and is a player

https://cdn.glitch.com/1c6278df-8ef2-4c22-8707-9cf25493672a%2Ftrimmedfootage_bug.mp4?v=1625939353210
[servercrashreport (4).log](https://github.com/Regalis11/Barotrauma/files/6795722/servercrashreport.4.log)

(Note: The husk is modded but it shouldnt really matter that much considering its almost the same to a normal Husk)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/94fb75dde146461736c91aecbb9ba7d89be0f6d0.

Happens when the CPR'd character is revived in both single player and multiplayer.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
