### ISSUE TITLE
Alien turrets crashing game.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#6293]
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ordering to operate an alien turret through the contextual menu causes an instant crash.

**Steps To Reproduce**
Find an alien ruin, find an alien turret inside, and use the context menu to order someone to operate it. 

**Version**
v0.14.6.0, using windows 10.

**Additional information**
I was playing modded campaign when my game crashed. But I don't think the mods are what caused the crash, as alien turrets are part of the base game.

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this: the operate order isn't available as a contextual option for the turret. Which mods were you using? I wonder if they could be modifying the behavior somehow.
