### ISSUE TITLE
Pirates completely ignore job restriction on spawnpoints

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6296]
**Description**
Pirate NPCs with different jobs spawn on whatever spawnpoints inside the pirate submarine, completely ignoring set jobs for the spawnpoints. Because of this, custom NPC spawns on the pirate subs are very limited, since anyone can spawn anywhere.

**Steps To Reproduce**
-start a pirate mission (campaign or mission)
-pause the round at start, debugdraw
-look at the pirates and where the different jobs spawned
-they don't adhere to the spawnpoint job restrictions

Description of the job label on spawnpoint:
![image](https://user-images.githubusercontent.com/59519434/125226768-fb793900-e2d1-11eb-8ea7-84ab35fc2c2d.png)

**Version**
Stable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d96e4149f2c03ea4c2c2805908b1c6d90cbd3d47

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
