### ISSUE TITLE
Repairing walls as a husk causes a crash

### ISSUE THREAD

**Issue by mc-oofert** [Regalis11/Barotrauma#6297]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you repair a damaged wall with a welding tool as a husk,the server crashes.
Tested on multiplayer.

[servercrashreport.log](https://github.com/Regalis11/Barotrauma/files/6802752/servercrashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/56e71eb7d42387b50b6725f29995ad8d5f099d05

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.
