### ISSUE TITLE
using contained items doesn't use them at the item's position

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6299]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Contained items are not used at their actual position, but at the container's center.
Expectation is that an item is used at its actual position

**Steps To Reproduce**
1. place an item that has an effect into a container with an offset
2. the item is used at the container's center, rather than where the item appears to be

**Version**
0.14.6.0 stable

**Additional information**
matters more for items that have a large offset between the body center and the contained item

Example video of an offset contained item being used:

https://user-images.githubusercontent.com/5103517/125344686-98b18d00-e325-11eb-91f3-4cb7db9450ba.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1729ae5c148f10158cbe1977311003758ac81597

**Comment by Rokvach** [comment]
An example mod could help a lot with testing this

**Comment by Tsunder** [comment]
> An example mod could help a lot with testing this

https://steamcommunity.com/sharedfiles/filedetails/?id=2564511586

incidentally, two bugs with flash powder...

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
