### ISSUE TITLE
MD5 hash from ubuntu incompatible with other hashes

### ISSUE THREAD

**Issue by CaptainGector** [Regalis11/Barotrauma#630]
Anyone trying to connect to my server gets a "wrong content package hash", and I can't connect to any server from my ubuntu client. 
![image](https://user-images.githubusercontent.com/16970830/43974047-27da2974-9c8e-11e8-9b74-c419af057b9d.png)

**Comment by rico6822** [comment]
What content package do you use?

**Comment by CaptainGector** [comment]
No content packages, I will go back and make sure the sub folder is vanilla but other than that and serversettings.xml everything should be "stock", downloaded directly from https://undertowgames.com/barotrauma/

**Comment by CaptainGector** [comment]
Oh also, I can't connect to most servers from the client, which is entirely stock. I've tried both building from source and the downloaded game. (They have different hashes). Neither seems to work. The hash that seems to work start with 37F, and the servers using it seem to have the most clients.

**Comment by CaptainGector** [comment]
I think I found the issue, content file in linux still has the `<Item file="Content/Items/Electricity/monitors.xml" />` line (16), commit 0fa046b3251aa11716953ffe7f0ffcbbfc302cdd apperently didn't apply to the linux build for some reason.

**Comment by CaptainGector** [comment]
Simply using the content file from the windows download seems to fix the issue in the server, I'll try the client next (I've just been setting it manually and building from source)

**Comment by Regalis11** [comment]
Should be fixed now by redownloading the latest version.
