### ISSUE TITLE
RegEX component not working after recieving the first message from a chat-linked Wi-Fi component

### ISSUE THREAD

**Issue by Paskky** [Regalis11/Barotrauma#6302]
- [x]  I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a chat-linked Wi-Fi component recieves a message from the chat and sends it to a RegEX component, the signal will go through only the first time.

**Steps To Reproduce**
Go to the sub building mode, place a chat-linked Wi-Fi component on channel 0, a RegEX component with "Continuous signal" unchecked and a light component. We'll call them WIFI, RX and L respectively.

Set RX to output a "1" for both true and false signals. Set the target signal to anything (ex. "(.*)" should always return true), it doesn't really matter what you choose since both true and false signals return 1.
Connect WIFI signal_out to RX signal_in. Connect RX signal_out to L "toggle_state".
Write something in the radio chat connected to channel 0. Only the first message will switch the light, then it will stop working.

**Version**
Latest version, that is v0.14.6.0, revision 12d7084c07
OS: Windows 10 64bit

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4687943c7ad53e44c6d6b46469cae2ab46c97ac1

**Comment by Rokvach** [comment]
Tested, now when ever I type something it toggles the light, working correctly. Closing.
