### ISSUE TITLE
Fire becoming invisible

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6308]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fire particles become invisible

**Steps To Reproduce**
1. Download assembly [Invisible Fire Bug.zip](https://github.com/Regalis11/Barotrauma/files/6816770/Invisible.Fire.Bug.zip)
2. Start burning
3. Thalamus cells produce a lot of blood and fire becomes invisible

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/096f37f63b8a2ca23ae28addbad6c7e089fca39b and https://github.com/Regalis11/Barotrauma-development/commit/16d3a81d70051123eac972bed74072921bee3ba0

**Comment by ubertpendragon** [comment]
Tested with the same assembly, seems good

**Comment by Rokvach** [comment]
Closing
