### ISSUE TITLE
late stage husk infection desync of inventory?

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6309]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A human that is in the final(?) stages of husk infection (where they are forced to slav squat) can't use items - it gets used in their client's inventory but it's not registered on the server

**Steps To Reproduce**
0. multiplayer
1. get to late stage husk - vomit + squatting only
2. try to attack crewmates

**Version**
0.14.6.0 stable

**Additional information**
friendly fire was on, as earlier I had accidentally stun baton'd a crewmate or several.

player firing weapons at final stages of husk into their crewmates, unsuccessfully
https://user-images.githubusercontent.com/5103517/125648169-470aa58f-33f2-4719-a483-58a014d511b2.mp4

**Comment by Emanthealmighty** [comment]
When the infection reaches that stage you are actually supposed to fall to the ground stunned, unable to move at all until you die.
How are you even still walking around?

**Comment by Tsunder** [comment]
i injected hyperizine on myself shortly before that stage, in hopes that I would become a methed up, roided up, armored husk causing chaos.

sadly that did not happen. (the buffs seemed to be removed on death? i suppose that should go in another issue)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/309b49dde04d63f47ebeedf75d5ca2b719ff7e02

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
