### ISSUE TITLE
Swapping Railgun to Coilgun. The coilgun retain railgun energy usage pershot

### ISSUE THREAD

**Issue by mercury2004** [Regalis11/Barotrauma#6312]
I have searched the issue tracker to check if the issue has already been reported.

Created on Typhon 2, Unmodded. Multiplayer - Campaign mode

**Description**
The new coilgun still retain its energy consumption pershot as same as railgun when swapped.
**Reproduction**
Change default frontal Railgun into Coilgun with ingame sub management
 
Did tried to test it by connecting it directly to the grid. The grid could not supply the gun. 
Siphoning from other supercap by Relay does not work. Since the energy use pershot exceed relay power max cap
![image](https://user-images.githubusercontent.com/16900782/125672262-f677bdc5-e6e9-4423-a4bf-82d09b04aeb4.png)
This is the image from one shot from coilgun
![image](https://user-images.githubusercontent.com/16900782/125672363-7e7e3e34-7a90-4fba-b8e4-7c724b16c26f.png)
**Version**
0.14.6.0

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I couldn't get this to happen: the power consumption seems to be correct after swapping the gun:
![image](https://user-images.githubusercontent.com/14351070/125760154-a8b30a9e-741f-40f1-980d-a65b04ea3f36.png)

Tested in both multiplayer and singleplayer. I wonder if something else could've affected this: are you using some kind of mods, had you swapped the gun to something else before...?

**Comment by mercury2004** [comment]
All vanilla gameplay, No mod was added to thee game
Railgun was left on default until we made the change to coilgun yesterday. So the gun was swap only once.

Frankly, I could not reproduce this exact bug in my client too. Its just only on my friend's client. And its just that save.

I have upload the save file with the bug we reported here
https://mega.nz/file/255ERToK#ywqk6L50yvT0z8b3RVKTsNLnvwfJ9ioYWWi4Kse-K7o

**Comment by Regalis11** [comment]
Thank you for the extra info! I suspect this has something to do with the power consumption upgrade, I'll do some more debugging.

**Comment by Regalis11** [comment]
Found a way to repro this now:
1. Purchase an upgrade to the railgun's power consumption.
2. Leave the outpost and re-enter it to get the upgrade to be applied.
3. Swap the railgun to a coilgun.
4. Leave the outpost.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6dd36a403926005470d05a591db1da9dadd711a6

Note for testing: the power consumption will still be incorrect in the provided save file, this fix prevents it from being set to the incorrect value but doesn't affect old save files.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
