### ISSUE TITLE
EDC electric discharge coil discharges when attempting to rewire

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6314]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
EDC / electric discharge coil immediately shocks anyone trying to rewire it, so long as it's powered

**Steps To Reproduce**
1. hold screwdriver, try to rewire a discharge coil that has power

**Version**
0.14.6.0

**Additional information**
wasn't getting shocked in 0.13 and before.

**Comment by MateusJK15** [comment]
Happened with me too, it's impossible to rewire it if it's powered.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7bf662f2b2805c4c2fdf25c8b47191d3f5cde1fa

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
