### ISSUE TITLE
Finishing fabricating an item as a husk crashes the game

### ISSUE THREAD

**Issue by mc-oofert** [Regalis11/Barotrauma#6317]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes as soon as you finish fabricating an item as a husk. (Or when you get EXP? if thats the correct cause)

**Steps To Reproduce**
1. Control Husk
2. Get Organic Fiber/other item
3. Go to Medical Fabricator/Fabricator,start crafting bandages for example
4. Game should crash sometime during fabrication

**Version**
0.14.6.0

**Log**
[servercrashreport (10).log](https://github.com/Regalis11/Barotrauma/files/6825110/servercrashreport.10.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ff69eeeed40252472247f628759f484218ae543

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
