### ISSUE TITLE
buffs do not persist through husk infection "death"

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6318]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
player/human turning husk does not keep their buffs when they turn into a husk

**Steps To Reproduce**
1. inject husk
2  inject buffs at very late stage husk
3. give up when downed
4. husk player does not have buffs?

**Version**
0.14.6.0

**Additional information**

https://user-images.githubusercontent.com/5103517/125834702-08ed93e0-1989-4ddd-8dc0-194c8a27a9dc.mp4

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/52a7d73517130116eb01225cd6f896aecb2e6d82

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
