### ISSUE TITLE
Can't crouch as humanoid while testing in character editor

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#6326]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When pressing the keybind that makes your character crouch, the character in the character editor will simply stop moving without crouching. This makes it hard to tweak the crouching parameters for human animations.

**Version**
v0.14.0.6.0 Stable

**Comment by itchyOwl** [comment]
It's a known issue. IIRC I disabled crouching because control is used for other things in the editor. But something we'd have to address before the full release.

**Comment by itchyOwl** [comment]
Crouching is now implemented as separate animation parameters in Regalis11@Barotrauma-development.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
