### ISSUE TITLE
Bots stuck at typhon ballast trying to repair

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#6334]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots get stuck at waypoint 551 trying to repair the small pump in docking port due to there being no normal waypoints in said pump's hull.
![Untitled](https://user-images.githubusercontent.com/86010664/126053422-e66de57f-e07a-4ff9-8fae-e4bd44d5e2ea.png)

**Steps To Reproduce**
1. Get bots on repair systems duty.
2. Emp grenade the lower docking bay small pump.
3. Bots gets stuck in ballast.

**Version**
0.14.6.0 windows.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6e13b0c7755a451bb0109d63bc3875838df43017

**Comment by Rokvach** [comment]
Tested, no issues. closing.
