### ISSUE TITLE
Publishing to workshop > "Files included in the item" list displays non-XML files

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6336]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "Files included in the item" list allows checking images and sounds, which affects absolutely nothing.
However, it clutters the list and creates confusion among players thinking that images and sounds should be included in filelist.xml

**Steps To Reproduce**
Open the PUBLISH tab and click on a mod that has at least one image or sound file. 
The non-XML file will be on the list. 

**Version**
v0.14.6.0

**Additional information**
File types which aren't loaded from filelist.xml shouldn't be displayed on that list **or at least shouldn't have the check box.**

**Comment by Rokvach** [comment]
We don't seem to be even showing the filelist anymore, so this doesn't seem to be an issue anymore. Closing.
