### ISSUE TITLE
[0.14.6.0] wreck tries to generate on outpost level

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#6337]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
it's like it's trying to place a thalamus in an outpost, which means it's generating a wreck on outpost level

**Steps To Reproduce**
1. download save files pinned in `additional information section` and place em in your barotrauma multiplayer save folder
2. download mods named Jlobblet Tweaks+, Into The Abyss and New Wrecks For barotrauma
(JT+: https://steamcommunity.com/sharedfiles/filedetails/?id=2409328414)
3. make sure load order is exactly like in previous step
4. start a server
5. try to start a save file
6. get crashed

**Version**
0.14.6.0 stable, windows 10 pro

**Additional information**
console log: [consoleOutput.txt](https://github.com/Regalis11/Barotrauma/files/6842266/consoleOutput.txt)
save files:  [Save.zip](https://github.com/Regalis11/Barotrauma/files/6842275/Save.zip)
(also dont ask why it named this way, im not original author of this save)

**Comment by Regalis11** [comment]
The save seems to have been done in a normal non-outpost level, so the issue isn't that the wreck is being generated in an incorrect level. Seems to be a duplicate of #6187

**Comment by Lefttroll** [comment]
thanks for solving this problem!
