### ISSUE TITLE
Emergency lights are set to cast shadows by default

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6338]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Emergency lights are set to cast shadows by default. This is likely unintended as these lights generally have a very short range. Furthermore, the problem XML for the lights contains `castlights="false"` instead of `castshadows="false"`.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6517a1bfe3d5b900a0c58e22f71ca6a3b27c05b2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
