### ISSUE TITLE
loading the railgun loader refills the first shells to be fired

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6342]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
after firing a railgun, the next shell to be fired is ... whichever shell is in slot 1, which is now empty, rather than occupied by the slot 2 shell from before.

This causes players to mess up the shell firing order by reloading, because instead of:

plain round, 4x canister, + new load of nuclear round

it goes

plain round, + new load of nuclear round, 4x canister 

**Steps To Reproduce**
1. fire a shell from a railgun loader
2. reload a shell to the loader
3. newly loaded shell is the next in line for firing
 
**Version**
0.14.6.0

**Additional information**
fig. 1 
![image](https://user-images.githubusercontent.com/5103517/126258398-5225ae6b-5ad1-4e27-8bd3-eab41792a2e8.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d5efb2cc0da8de7e3dbc5c28cc25e046bcdff60d

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
