### ISSUE TITLE
hitscan="true" projectiles (bullets) don't use `maxtargetstohit`

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6343]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Projectiles that use `hitscan="true"` won't function correctly with `maxtargetstohit="x"`

**Steps To Reproduce**
Modify a vanilla weapon's bullets to use maxtargetstohit="10" (or at least 2) and shoot at a character's legs or at a character in front of another character.
The hitscan bullet won't pierce and won't hit multiple targets.
Projectiles **without** hitscan="true" will correctly go through limbs or walls.

**Version**
v0.14.6.0

**Additional information**
Please add a variable that prevents projectiles from piercing walls. Using `maxtargetstohit` would for example allow harpoons to pierce walls while the intention could be to make them pierce limbs.

Idea: it's easy to mix up `maxtargetstohit` with incorrect `maxtargetsonhit` so the misspelling could be added as an alias if aliases exist.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6427a6375116ed7329f26fc1cb284b92ec7bf6e

**Comment by Krzeszny** [comment]
> Fixed in [Regalis11/Barotrauma-development@f6427a6](https://github.com/Regalis11/Barotrauma-development/commit/f6427a6375116ed7329f26fc1cb284b92ec7bf6e)

Will hitscan projectiles pierce walls?

**Comment by Regalis11** [comment]
Yeah, they'll work essentially the same as non-hitscan projectiles: if MaxTargetsToHit is set to let's say 2, it'd be able to pierce through one wall.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
