### ISSUE TITLE
Signals do not travel from one wi-fi component to another.

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#6346]
- [x] I have searched the issue tracker to check if the issue has already been reported.

One wi-fi component receives chat messages from channel 0 and transfers them to another of a different channel. This setup used to work and now it doesn't. Test with a text display showed no signal being transfered between the wi-fi's. Signals travel normally from wi-fi to other components. It's the "wi-fi ---> wi-fi" setup that's bugged.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8632c5b4a9a2a21adc40f6927ce67c9f4b083d63. 

Here's a sub for testing the fix (chat messages sent on channel 0 should appear on the text display):
[wifitest.zip](https://github.com/Regalis11/Barotrauma/files/8002051/wifitest.zip)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
