### ISSUE TITLE
Campaign settings reset when reopening the campaign settings menu

### ISSUE THREAD

**Issue by Demyxa** [Regalis11/Barotrauma#6347]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When reopening the settings in the "New Game" option for single player, the "Enable Jovian Radiation" Checkbox is checked, even if it was previously unchecked by the player.

**Steps To Reproduce**
Hit "New Game" -> Open "Settings" -> Uncheck "Enable Jovian Radiation" -> Hit "Ok" -> Reopen "Settings"

**Version**
v0.14.6.0 (Windows)

**Additional information**

https://user-images.githubusercontent.com/48883376/126381036-be1efcfc-28af-48f4-a306-cef409b68849.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bcbdf109741cb2cef99a7a7e85eeb71f87a7472b

**Comment by Jlobblet** [comment]
Does this also happen with the selected max missions?

**Comment by Demyxa** [comment]
Only one way to find out: And yes it does.


https://user-images.githubusercontent.com/48883376/126627772-8c800b52-243a-450f-8890-fe5942c2223b.mp4

**Comment by Regalis11** [comment]
Good catch! Fixed that one in https://github.com/Regalis11/Barotrauma-development/commit/9e8b3a2a8ef7661e3ec922d682ab1ce4bc76c748

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
