### ISSUE TITLE
Traitors Don't Know Immediately Their Targets- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#635]
Sometimes (occurs never randomly or always depending on server settings) enemy corporation will not have enough time to tell their traitors their target to assassinate and will send them information by navigation terminal, who to kill in few minutes. Terminal must be powered up to read or delete info. Traitors after reaching terminal can delete data within it to prevent rest of the crew from knowing, who betrayed. The data is not displayed immediately, traitor has to use his ID card on it and wait 10 seconds. The ID is not consumed.

It would be unfair, if assassination target had to die immediately, after start of the round, because they are chosen for it. That's what this request is for.

**Comment by Regalis11** [comment]
Yeah, the intention behind this idea is good but I think it would cause more problems than it would solve. There are better ways to make traitors less of a pain in the ass - maybe alternative objectives that don't involve killing anyone, or some sort of preliminary objectives before you can proceed to the assassination.
