### ISSUE TITLE
Pulse Laser won't fire through Shell unless there is a Hull on the side it is firing from.

### ISSUE THREAD

**Issue by david-sharer** [Regalis11/Barotrauma#6354]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Probably related to #2058, but found to be an issue with default guns instead of modded-in guns.  
- (when a Pulse Laser is placed within hull) the Pulse Laser will not fire at Shell if there is no Hull on the side the pulse laser is firing from.
    - (see comment below: this issue appears to only occur when the Pulse Laser is within hull)
- It still consumes power and ammunition when it fails to fire.
- This appears to also apply to (docked?) shuttles.

**Steps To Reproduce**
(The first two images will probably make more sense than this text blurb.)

1. Configure a sub:
    1. Pulse Laser configured pointing downward (in my configured sub, this is inside hull)
    2. Shell segments below
    3. Hull segments touching Shell Segments below
        * Extending Above Shell (and not below)
        * Entirely Within Shell
        * Extending Below Shell (and not above)
        * No Hull at all
2. Fire the Pulse Laser at the various Shell-Hull configurations
3. Observe that the gun only fires at the first configuration

**Extended investigation**
I have configured a sub like so:
![image](https://user-images.githubusercontent.com/26589071/126602001-b6303092-04ab-4228-b175-20b83beb258e.png)
The bar of shell at the bottom is for testing this behavior.

The Pulse Laser fires at the test structure like so (all of these shots were tested):
![image](https://user-images.githubusercontent.com/26589071/126602049-ab2c97ab-d0a8-4635-b94a-0e22a2b631e1.png)

Only the left sections (where hull is extended into the water on the top) works. When aiming at the others, the pulse laser does not animate or deal damage to the Shell. So the gun will not fire (but still consumes power/ammo) when:
- shell has no connected hull
- hull is entirely internal to the shell
- hull extends out the far side of the shell, but not the near side of the shell

This also appears to apply to (docked) shuttles. The gun will only fire thru the docked hatch of the shuttle, like so:
![image](https://user-images.githubusercontent.com/26589071/126602435-efac1672-cb9f-4a07-856d-b90537dc0d12.png)
All other shots at the shuttle do nothing.

The results were identical for hatches. Configured like so:
![image](https://user-images.githubusercontent.com/26589071/126602813-d4939475-89d6-4070-b5dc-e8707b7aa380.png)
Only the left hatch will receive fire (from above)

Gaps do not appear to have an effect like hull. None of these worked:
![image](https://user-images.githubusercontent.com/26589071/126602956-cb5a6404-cb81-4e49-8374-c2c8b9a078d1.png)

**Version**
![image](https://user-images.githubusercontent.com/26589071/126601211-4c79aa3a-448c-4f36-a95b-f167aabe2faf.png)

**Additional information**
- I have not produced a separate sub to test this more deeply (for other gun types, for instance)
- Not tested on hatches in docked or undocked shuttles

**Comment by david-sharer** [comment]
Further testing!

This issue only occurs when the gun is inside a hull!

All of these shots worked.
![image](https://user-images.githubusercontent.com/26589071/126604349-a505b12b-967a-4f48-8cc1-7eac15b07c1b.png)

**Comment by david-sharer** [comment]
More Tests!

With Hull around the same configuration above:
![image](https://user-images.githubusercontent.com/26589071/126605436-bf8b0f62-fef9-4928-aa9b-3eb13a3f54ed.png)

Shot appears to hit the inside of the containing hull when there is no hull at the target? 
![image](https://user-images.githubusercontent.com/26589071/126605497-31edf969-cb5c-4c10-9214-f4946181eafa.png)

**Comment by david-sharer** [comment]
More tests!

When firing through an additional hull, the behavior is identical, and the "failed" shot still explodes inside the first shell.
![image](https://user-images.githubusercontent.com/26589071/126606474-27ed969f-4aa5-4cc3-8ad4-1bdece5487dd.png)

![image](https://user-images.githubusercontent.com/26589071/126606429-69c1871b-0aa4-4f86-89f7-a61584e6493d.png)

**Comment by david-sharer** [comment]
This works as you'd expect. Hits the Shell and deals damage as expected.
![image](https://user-images.githubusercontent.com/26589071/126607710-1819b578-0818-42fc-8a4c-ca66c9824426.png)

**Comment by david-sharer** [comment]
## For anyone attempting to build a sub with an interior Pulse Laser, here was my workaround

Short version:
- Embed a teeny tiny Pulse Laser (that actually fires) inside a regular-size pulse laser (which doesn't)
- Surround the small Pulse Laser in water, and shield your crew from it (with glass?)
- The smallest Pulse Laser you can make should fit inside a 1x1 tile of water

Longer version:
1. Very, very tiny Pulse Laser (this is your actual pulse laser)
    - This is because the tip of the gun must be in water. If it swings around a lot you'd need a very large water area
2. Second, unpowered, regular-size Pulse Laser (this is your dummy laser)
3. Embed the regular-size Pulse Laser deep into a wall, so the pivot point is barely off the ceiling
4. Control position_in of the regular-size pulse laser, but nothing else
5. Place the very tiny Pulse Laser at the center of the arc for the regular-size pulse laser
4. Make a hole in the hull around the tiny Pulse Laser
      - With my 2x1 tile (see below) this does not even cause water pressure issues if you somehow intersect it
5. Cover the hole in glass, to help keep your crew from becoming 5 inch cubes (and pretend the laser requires maintenance after firing?)
6. Make the glass invisible in game

The visual effects and such appear identical to me, except now the gun is inside the ship and can obliterate your crewmates as well as other structures
![image](https://user-images.githubusercontent.com/26589071/126613632-94c370c7-3f62-4b02-a6cd-55641ee5693d.png)
![image](https://user-images.githubusercontent.com/26589071/126612959-d37459ec-49a9-4e6f-b080-74fefc722296.png)
![image](https://user-images.githubusercontent.com/26589071/126613027-ab524768-831e-43c6-90c7-f0d8f2105cca.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8899f15c3904c93005d19e2277ac0780e94d0742

**Comment by david-sharer** [comment]
Wow that was fast!

**Comment by Rokvach** [comment]
Tested, confirmed to be working correctly by the community, closing.
