### ISSUE TITLE
traitor items will spawn in non-interactable containers

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6355]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Traitor items can spawn in non-interactable, hidden in game, or unpickable containers

**Steps To Reproduce**
1. place some non-interactable, hidden in game, or unpickable containers
2. traitor mission!
3. item spawns in said containers

**Version**
0.14.6.0

**Additional information**
this method?
https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaServer/ServerSource/Traitors/Goals/GoalFindItem.cs#L76

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/08756b8d4fcce309f9d58ce8d844a4021fb5de73

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
