### ISSUE TITLE
Stun Gun darts take 10 seconds to stun characters

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6356]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stun Gun is useless.

**Steps To Reproduce**
Shoot a character with a stun dart. Stun takes place after 10 seconds.

**Version**
v0.14.6.0 since the stun update

**Additional information**
What I suggest is making a StatusEffect or an affliction that stuns only human characters.

**Comment by Tsunder** [comment]
how is this a bug? it's clearly intentional.

it also slows the target down, stun gun is fine for pacifying.

**Comment by VolcanoTheGod** [comment]
> how is this a bug? it's clearly intentional.
> 
> it also slows the target down, stun gun is fine for pacifying.
It's more of a tranquilizer than of a stun dart then. It's using wires in its craft though

**Comment by Regalis11** [comment]
This was an intentional change to make stunning a little less OP. We're going to be reviewing the afflictions for a future update though so there's a chance we'll do some further adjustments to the stunning, but since this isn't really a bug, I'll close the ticket.
