### ISSUE TITLE
Sub editor interface bug

### ISSUE THREAD

**Issue by MateusJK15** [Regalis11/Barotrauma#6357]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the sub editor when a turret is selected a green line and 2 yellow squares are shown around it showing the turret rotation limits. Sometimes when i click on the yellow squares i can select them, drag them around and change the rotation limits, but sometimes when i click on them i can't select them, i click multiple times and nothing happens. if it will work or not is completely random.
![20210722190659_1](https://user-images.githubusercontent.com/86162808/126717266-2c143498-83f5-4e0c-bc89-9030ac199be5.jpg)

**Steps To Reproduce**
Go to the sub editor, select a turret and click on the yellow squares, sometimes it will work, sometimes it won't

**Version**
0.14.6.0, running on windows 8.1

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/463c04cb7e9d25a5e381bc6385d21864d520f2e3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
