### ISSUE TITLE
unresisted burndamage kills humans absurdly fast

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6361]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
exploding ammo can 2 shot a human or 4 shot a human wearing a diving suit
pulse laser comes close to 1 shotting humans
burn damage being effectively unmitigated/"pure" and also dealing damage in an explosion which multiplicatively increases the effectiveness against creatures with smaller limbs, like humans.
This makes them an absurdly potent anti-personnel weapon, yet only average/above average performing weapons against larger targets like moloch+'s compared to their non-aoe/non-burn damage counterparts.

**Steps To Reproduce**

**Version**
0.14.6 stable

**Additional information**
short comparison of effectiveness of exploding ammo, pulse laser, and piercing ammo.
https://user-images.githubusercontent.com/5103517/126857847-ccd1abca-ec7c-4374-99ae-b57a9452dd9f.mp4

**Comment by WrillWasTaken** [comment]
Aren't these supposed to be bug reports?

**Comment by ezjamsen** [comment]
Duplicate issue.

**Comment by Regalis11** [comment]
https://github.com/Regalis11/Barotrauma-development/issues/2739
