### ISSUE TITLE
Docked subs losing collisions when inside of the parent submarine's hull.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#6362]
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Docked submarines lose all collisions when inside of a parent submarine's hull.

**Steps To Reproduce**
Create a hull, place a docking port inside of it, link a submarine to the docking port, now try to enter the docked submarine.

**Version**
V0.14.6.0 (Windows)

**Additional information**
Video evidence: https://youtu.be/C4jCO0wKXTo
I also do not have any mods enabled.

**Comment by ubertpendragon** [comment]
Can confirm

You can technically dock shuttles inside bigger hulls, but it has the same issue. Docking port "magnetism" basically teleports the shuttle inside the hull (despite hulls not being able to collide), but the shuttle loses all collision when inside

**Comment by MaaiG** [comment]
**Regalis11**
If it’s a bug, what’s the plan?
Will the game add the ability to create a "dry dock"? `Hull` in the other `hull`?
This is gonna be great! I want to keep my shuttles and drones in a locked dry hangar!
