### ISSUE TITLE
Browsing the shop for too long causes an AFK kick-out

### ISSUE THREAD

**Issue by JinHansson** [Regalis11/Barotrauma#6364]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We got players kicked out twice for browsing the shop for too long, the reason being they were "away from the keyboard."

**Steps To Reproduce**
Dock a station, go to a shop, scroll through the wares for long enough, just don't touch the keyboard.

**Version**
Windows, latest version as of 22 Jul 2021.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0d84cb18d14f28abab872cb47c1ae241a51a8db

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
