### ISSUE TITLE
Bandage duplication

### ISSUE THREAD

**Issue by PolySoup** [Regalis11/Barotrauma#6366]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you deconstruct Plastiseal you get 2x the Bandages used to craft it.

**Steps To Reproduce**
Get a stack of 4 Plastiseal. Deconstruct them. You now have 4x Bandages and 2 Elastin. Take them to a Medical Fabricator and craft 4 Plastiseal. You now have 4 Plastiseal and 2 Bandages.

**Version**
0.14.6.0 on Windows

**Additional information**
Discovered during a single player campaign using the Humpback.

**Comment by terrykwan1** [comment]
that does seem to be what the xml would imply, that u get 1 bandage and 0.5 elastin per plasti seal but it only takes 1 bandage and 1 elastin to make 2 plastiseal.
![image](https://user-images.githubusercontent.com/80422211/127213926-02b0cd5a-7b23-4f4f-b493-edc2d9fbe68e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/49356b3f0d5ce7650f8d2839bb85d3d4f77c8950

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
