### ISSUE TITLE
AI gets stuck if they try to heal themselves

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6370]
Branch: bugfixes
Commit: https://github.com/Regalis11/Barotrauma-development/commit/7644391e746253b89b56bdffa17eba7550c8d842

Video:
https://www.youtube.com/watch?v=xohlPQaEomo

Tested in multiplayer

I was testing the ticket regarding AI ignoring broken devices ( https://github.com/Regalis11/Barotrauma/issues/6230 ) and by using the steps provided on the ticket, I encountered a situation where one of the bots just got entirely stuck repairing a junction box, even if I controlled the bot I couldn't move them. 
Even if I interacted with the junction box I wasn't able to get unstuck, also tested what happened if I ragdolled or got electrocuted, still wasn't able to get unstuck. 

I was able to get unstuck only when pressing H to heal

**Comment by itchyOwl** [comment]
Doesn't sound like an AI issue. Could it be related to #2296?

**Comment by Rokvach** [comment]
Not related, happened a second time whilst community testing too. The AI just ends up standing next to the broken device with a screwdriver in their hand and hands raised as if they are still repairing the device. I think it has something to do with the repair UI or some other interface not closing properly and letting the bot free, as I mentioned that if you control the bot and open the health interface the bot gets freed.

**Comment by itchyOwl** [comment]
Oh, on the first read I understood that you didn't manage to get unstuck. Would be useful if we'd have the steps to repro.

**Comment by Rokvach** [comment]
I did write that I managed to get unstuck on the ticket, I've only seen this happen when bots are just repairing devices as usual with the repair order applied to them. 

But as I wrote above you can just use the "explosion 30000 0 0 0 0 100" command and order all of your bots to repair all the damaged devices, they should eventually get stuck like this. 

I've also seen this happen both in singleplayer and multiplayer and in both times I was using Dugong as the sub, but it didn't happen in the same room as the first one happened on the reactor room and the second one in the engine room, can't tell which device they were especially repairing as when they get stuck they keep walking forwards endlessly as seen on the video.

**Comment by Rokvach** [comment]
Tested in the Bugfixes branch

I managed to find a way how to reliably reproduce this issue, it seems that rather than getting stuck at repairing a junction box the bot actually gets stuck at operating a reactor, or at least in this case. 

I have a feeling that it has something to do with bots healing themselves whilst they have a access to a device.

Repro steps:
1. Go to sub editor, select Dugong and enter test mode
2. Navigate to the armory and get yourself a Revolver
3. Wait until one of the bots starts to operate the reactor (Don't order them to)
4. Shoot the bot in the leg
5. Hear that the bot uses a bandage and notice that their arms are now raised in a odd position and they start to slowly walk away from the reactor.

You can now take control of the bot and notice that your movement is being slowed down, you cant free the bot from that state by interacting with the devices, only if you access the health interface you can free the bot.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/739b9c17f086ae3505b15f2e39d18f99d3715adc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
