### ISSUE TITLE
nest wipes itself out on mission start

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6371]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using the save attached will lead you to a campaign mission where somehow a mudraptor nest dies instantly after the round starts

**Version**
Unstable v0.1400.7.0 Windows

**Additional information**
[condensed rage.zip](https://github.com/Regalis11/Barotrauma/files/6879573/condensed.rage.zip)

**Comment by LePiromano** [comment]
apparently it happens with every nest

**Comment by Regalis11** [comment]
Seemed to have been caused as a result of the fix implemented for https://github.com/regalis11/barotrauma/issues/6270. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e366181946704a1eab3bec64cdbc0fbc13ddc9b1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
