### ISSUE TITLE
Can't stack items in fabricator output slot

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6372]
- [ye] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can drag stacks into the output slot but the game wont let you craft another item of the same kind while there's already one in the output slot
https://user-images.githubusercontent.com/55637865/127031656-b8040441-a87e-490b-91a5-348139a48cbb.mp4

**Version**
v0.1400.7.0

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6193
