### ISSUE TITLE
invisible ice spires when going through ruins

### ISSUE THREAD

**Issue by M1suu** [Regalis11/Barotrauma#6373]
- [x] i have searched the issue tracker to check if the issue has already been reported.

**Description**
Ice spire goes partly invisible if inside/going through an alien ruin. The ice spire still has collision and takes damage but you just can't see it.

**Steps To Reproduce**
get an ice spire to spawn and go through an alien ruin.

**Version**
0.14.6.0 Linux

**Comment by Regalis11** [comment]
Thank you for the report!

This will be less of a problem in the next major update when we start using the outpost generator to generate the ruins (as the ruins will technically be submarines, and the spires won't collide with things inside the ruins). However, the spires shouldn't overlap with the ruins in the first place. Do you happen to have a save file or a level seed where this occurs?

**Comment by M1suu** [comment]
Unfortunately i don't have a save file or seed to give since the bug occurred on a campaign i no longer have.
Both the ice spire and ruin spawned inside a small tight cave where the spire had pretty much the length of a player before it hit the alien ruin. Most likely a rare issue to occur.

**Comment by Rokvach** [comment]
As there is no real way of reproducing this and this will get fixed with the new ruins I think I will just close this
