### ISSUE TITLE
You cant get out of Remora Drones engine/ballast if the hatches break

### ISSUE THREAD

**Issue by WhySmau** [Regalis11/Barotrauma#6374]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You cant get out of Remora Drones engine/ballast if the hatches break because there are no platforms behind the hatches

**Steps To Reproduce**
Get the engine/ballast hatch broken and fall in it

**Version**
0.14.6.0 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8d5f4a6169d1f5e55c020c65d2ac486b9f0219dd

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
