### ISSUE TITLE
[Modding] targetitemcomponent does not filter out other component targets, applies to all if any match

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#6385]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I know we have already had issue #6283 stating it is not implemented, however I believe the implementation is flawed in how modder's wish to use it as it will target other item components regardless, perhaps giving the impression it is not implemented.

**Version**
Unstable 0.1400.7.0

**Additional information**
Code for the behaviour under the "And" property conditional:
![image](https://user-images.githubusercontent.com/29177976/127708288-253dc32b-5054-43ff-b395-a1c478b3c216.png)

so, to explain this clearly, Lets say we have several components all with a shared similarly named value to set. such as canbeselected between a memorycomponent and an itemcontainer. though im sure there are many other overlapping value names between components.

One trying to use the targetitemcomponent="ItemContainer" in a statuseffect for canbeselected is likely trying to exclude setting the memorycomponent's canbeselected, but due to the code the targets list does not get reduced, if even one of say, four components contains the right name it is unanimously applied to all components still in that entity.

I believe the expected result for the And comparison at least should be to exclude these other components from the targets, if not both comparison's to exclude different component types somehow. I figure the current implementation is possibly intended to target one of many items with one of these components inside it, Which would make this closer to a feature request then - Though even I thought initially the intended behavior was to exclude a different component target if they are all indeed different targets.

If this was intended to (say in an explosion hitting 20 items, I have not tested this) intended to only trigger on items with a specified component - then it could theoretically still hit all 20 items even if they did not contain it if their all lumped into targets (Not sure if they are though), given the targets list is not reduced that I can see.

Additionally not sure if this is designed to deal with uppercase characters (Doesn't seem to be ToLowerInvariant()) in comparison logic or when initially reading it, but that would be another issue if it doesn't.
`TargetItemComponentName = attribute.Parent.GetAttributeString("targetitemcomponent", "");`

**Comment by Regalis11** [comment]
I think there's a bit of a misunderstanding on what the conditionals do here: they don't determine which entities/components the StatusEffect can target, but whether the entire StatusEffect can trigger or not.

If you want to restrict e.g. which types of nearby items a StatusEffect can target, you should probably be using the StatusEffect's `targets` attribute instead of conditionals.
