### ISSUE TITLE
Excessive GC due to RegEx components evaluating capture groups when not necessary

### ISSUE THREAD

**Issue by kwogger** [Regalis11/Barotrauma#6396]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Excessive GC due to evaluation of capture group regardless of any signal being emitted.

Likely root cause:
https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/RegExFindComponent.cs#L113

**Steps To Reproduce**
See "working" and "broken" subs in https://www20.zippyshare.com/v/tlBEOnV6/file.html
The only difference is the purple tinted signal check component. In the "working" sub, the signal check emits a `&` on false, where the "broken" sub emits nothing. The `&` causes all its attached RegEx to evaluate false as well. Note that in *both* subs, the attached RexEx do not emit any signal as continuous output is set to off.

Turning the circuit "off" via the bottom right button does not stop the lag. Debugging shows that no signal is being emitted from any component, yet the lag persists.

"Working" sub
![20210801155105_1](https://user-images.githubusercontent.com/320801/127787647-152bac6f-345b-41b9-819b-d9ee7c469472.jpg)

"Broken" sub
![20210801155105_1](https://user-images.githubusercontent.com/320801/127786826-db125066-0657-4925-bb2e-b45e30ec6596.jpg)

**Version**
0.14.6.0 Windows

**Additional information**
The root cause of the issue is `previousGroups.TryGetValue(Output, out Group group)` in https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/RegExFindComponent.cs#L113

The execution of TryGetValue causes some memory allocation, where on very large strings (presumably), can cause an large amount of memory allocation that will require GCing. The issue is that TryGetValue is executed regardless of if the signal will be emitted, thus, even if no signal will be emitted (i.e. `ContinuousOutput` is false), TryGetValue will still be evaluated.

One fix would be to cache the value of `previousGroups.TryGetValue(Output, out Group group)` and `Output` and only re-evaluate if `Output` changes.

An alternate fix would be to wrap and defer the code determining `signalOut` https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/RegExFindComponent.cs#L108-L130 to only execute as necessary inside the if-blocks determining that an output is necessary https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/RegExFindComponent.cs#L132-L140
This fix would still have the extra unnecessary evaluation, but at least it would not be running the evaluation and causing GCing when the RegEx component is not emitting any signal.

**Comment by Regalis11** [comment]
Implemented the 2nd proposed optimization in https://github.com/Regalis11/Barotrauma-development/commit/bb5fb8a5815cc7e2f53b0d047d746019e9e30eb9. Caching the value returned by TryGetValue seems like a good idea too, but I'll leave that for later at least for now when there's some more pressing issues to fix first.

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. The previous optimizations seem to have mostly solved this problem, optimizing it further doesn't seem that necessary.
