### ISSUE TITLE
[Unstable v0.1400.7.0] Can no longer use Tubes/Guns with cabinets as ammo source, even by changing tags

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6397]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On stable, you can simply link a cabinet to a coilgun and the coilgun will use the cabinet as a loader

On unstable, it's not possible any more

**Steps To Reproduce**
1. Link a supply cabinet to a depth charge tube
2. Add revolver bullets in the supply cabinet
3. Wire a button to depth charge tube trigger
4. Nothing happens

![image](https://user-images.githubusercontent.com/73229309/127825232-f60c57e5-4c80-4f7d-97c5-f0730be74702.png)

Even when adding the `depthchargeammosource` tag to the supply cabinet, it doesn't shoot. 

Lots of submarines use this trick for contraptions such as medical coilguns or spinal railguns. 

Probably a side effect of fixing #6328 #6085

**Comment by Regalis11** [comment]
This was an intentional change: now turrets and depth charge tubes only worked when linked to a valid container. You can modify which links are considered valid by using the `allowedlinks` attribute.

**Comment by ubertpendragon** [comment]
@Regalis11 
Is this going to be editable in game, or behind xml editing? The ease of setting up a simple link to a tube was greatly appreciated for building setpieces, medical dispensers and all kinds of useful contraptions
