### ISSUE TITLE
Flash powder not immediately used

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6399]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Flash powder doesn't explode immediately when used by an item (i.e., detonator on a stick)
instead it rapidly drains condition over time.

**Steps To Reproduce**
1. place Flash Powder in the detonator on a stick
2. use
3. flash powder drains condition instead of immediately exploding

**Version**
0.1400.7.0 unstable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a079b5e29932526eaea017b6a2c41f72f544d3f6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
