### ISSUE TITLE
Headset Having Larger Range- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#640]
Even completely standard Aegir Mark III has communication trouble with headset, when mechanic is at the engine and captain is close to navigation terminal. I think the wifi strength of headset should be minimum 30000 always and should be larger automatically, if submarine's sizes require it. If that happens in respawn shuttle, the range of headsets will still be increased, if submarine, they have to arrive at is large enough. Fulgurium battery cell always multiplier's that range by 1,5; but it lasts double shorter.

**Comment by Regalis11** [comment]
Fixed in the dev branch
