### ISSUE TITLE
can't add items to a stack of items sub editor when the container is full

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6400]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
attempting to place/add to a stack of item in a container in sub editor fails when the container has an item in every slot, even if the stack itself is not full

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0,1400,7,0

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3efc00bd9ba42f5c4e27c8bc33f4a64ccfe885e3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
