### ISSUE TITLE
Pulse laser and chaingun have parts missing in submarine preview

### ISSUE THREAD

**Issue by WhySmau** [Regalis11/Barotrauma#6401]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pulse laser and chaingun have parts missing in submarine preview

**Steps To Reproduce**
Make a submarine with pulse laser/chaingun and look at it in sub preview
![Näyttökuva (393)](https://user-images.githubusercontent.com/86321358/128020770-365f0bf1-193c-4e8c-988a-bed7c9d2d4dc.png)

**Version**
0.14.6.0 Windows

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
