### ISSUE TITLE
Diving Suit disappearing

### ISSUE THREAD

**Issue by NikoTheFricko** [Regalis11/Barotrauma#6403]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
my friends were diving down in the normal diving suits to go and kill a mudraptor nest as they entered a cave they went past crystals that can hurt but they didnt get hurt by them as they went around them and destroyed them with the plasma cutter. before they arrived at the nest their diving suits just disappeared on their screen for them, the other person had the suit on but they didnt and this was for both players. At first we thought it was psychosis but then actually started to die from the pressure. we were so confused. when they had actually been killed due to the pressure we reloaded and then mission screen did say they were killed by the pressure.

This was done in the Normal diving suits you start of with and they hadnt been tampered by mods they were also not below 4000 ft which by the wiki says they wouldve been fine. a theory my friend has is that he was upgrading another suit to be the better version it some how teleported them back or made them out of sync with the players and he thought that cos he was the host.

**Steps To Reproduce**
I guess a way to reproduce is someone host a game and two other players go underwater and break the crystals that hurt and then at the same time start crafting the better suit of the original diving, we were also at a depth of 2000-2300

**Version**
0.14.0.6
**Additional information**

**Comment by Krzeszny** [comment]
I experienced something similar with coilgun ammo boxes:

I wanted to recycle an ammo box and when I activated the fabricator, the item disappeared from my hands and dropped on the floor but I couldn't pick anything up. 
For other players I was carrying an ammo box but there wasn't anything on my screen that would suggest it. To resync, I had to pick up that box from the floor.

**Comment by Tsunder** [comment]
think it's related to #6125

**Comment by lnternecion** [comment]
I had the same problem although we were just swimming through alien ruins

**Comment by Torusaynim** [comment]
Encountered this problem while swimming in caves with a friend, diving suits just disappeared and dropped somewhere on the ground, luckily no casualties. Also sometimes this bug makes diving suits impossible to equip back again, they drop back on the ground in like half a second.

**Comment by AaronSherwood117** [comment]
Just had this happen while someone back on the sub was crafting new diving suits, might be related.

**Comment by Regalis11** [comment]
No known steps to repro, closing
