### ISSUE TITLE
Line of sight from player origin rather than from their eyes

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6405]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
line of sight is from the character origin rather than from the eyes

**Steps To Reproduce**
look at some shadows
![image](https://user-images.githubusercontent.com/5103517/128388477-7274909a-7273-48b5-a19a-67fb2fa75016.png)
![image](https://user-images.githubusercontent.com/5103517/128388487-c36c3eab-d44c-4c93-b72c-cd939694f4d8.png)

**Version**
0.14.6.0

**Additional information**
i have no eyes and i must scream

LOS , POV , vision, shadows

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
