### ISSUE TITLE
Some outdated loading tips

### ISSUE THREAD

**Issue by WhySmau** [Regalis11/Barotrauma#6407]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There are some outdated loading tips:
"The cephalopod-like watchers are generally docile, but may attack when provoked."
"Be careful not to dive too deep. Most submarine hulls will start collapsing at the depth of approximately 2,000 meters."
"Administering drugs without sufficient medical knowledge may reduce **the number of doses a single syringe provides**, and may also reduce the quality of the effects of the drug."

**Version**
0.14.6.0 Windows

**Comment by Regalis11** [comment]
The last 2 have been reported in https://github.com/Regalis11/Barotrauma/issues/5738 and fixed since. Fixed the 1st one in https://github.com/Regalis11/Barotrauma-development/commit/c0e8554892a2ff38612a2dc034d7c604d860ab5e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
