### ISSUE TITLE
Comparison="And" not working with tag conditional on 2 different item

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#6408]
Issue was reported as fixed in  #4631 but I encountered it while trying to mod a fuel rod

**Description**
Comparison="And" fail to check if all conditional are met before apllying SE in in this case when it has to check for tags on 2 separate item

**Steps To Reproduce**
		
Add this to a fuel rod (radioactive tag is a tag I made when rod is below 100% condition) for some reason  the SE doesn't appear in xml format here so I removed < and /> from the text

StatusEffect type="OnContained" target="This" disabledeltatime="true" stackable="false" delay="4" comparison="And"
Conditional hastag="eq radioactive"
Conditional hastag="neq reactor" targetcontainer="true" 
Fire 
StatusEffect

If  you only use the radioactive tag conditional : start fire if item has the tag in all container
If you only use the container tag conditional  : start fire in any container without the reactor tag

When both are used : start fire in any container

**Version**
V0.14.6.0  branch release window revision 12d7084c07

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bfb87b8d862127fbbb3b008af893d9d7c3ba5e73

**Comment by Rokvach** [comment]
I'm just going to close this, this hasn't caused any issues to the actual game, if the fix doesn't work in practice this ticket can be re-opened but for now closing.
