### ISSUE TITLE
LevelResource item component deattaches much sooner than the DeattachDuration field suggests.

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#6411]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
LevelResources deattach faster than expected by the DeattachDuration field.

**Steps To Reproduce**
Just time it. Mod test item included in *Additional information* field.

**Version**
Windows 0.14.6.0.

**Additional information**
Test item (just place it in the sub editor):
```
<Item name="TEST levelresource" identifier="test_levelresource" category="Material" Tags="smallitem,ore" canbepicked="true" description="" scale="0.5">
	<ContainedSprite texture="Content/Items/Materials/MineralEnvironment.png" usewhenattached="true" decorativespritebehavior="HideWhenNotVisible"	depth="0.55" sourcerect="512,0,86,147" origin="0.5,0.5" />
	<Sprite texture="Content/Items/Materials/Minerals.png" depth="0.3" sourcerect="258,4,126,121" origin="0.5,0.5" />
	<Body radius="40" width="20" density="50" />
	<Holdable slots="Any,RightHand,LeftHand" msg="ItemMsgUsePlasmaCutter" handle1="0,0" pickingtime="5.0" attachable="true" reattachable="false" attachedbydefault="true" />
	<LevelResource deattachduration="60" randomoffsetfromwall="0">
		<Commonness commonness="0" />
		<RequiredItem items="cuttingequipment" type="Equipped" />
	</LevelResource>
</Item>
```

**Comment by UzricRash** [comment]
I suspect this bug only occurs because I wanted to mod something for a sub, that is, because the LevelResource is not (only) generated by the level.
If that is the case then it is probably related to a trigger duplication or something obscure like that.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2503e52c4e51946d1f8bc39931e240f5c7f58db6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
