### ISSUE TITLE
Multiple Dedicated servers (2) from same ipv4 seem to mess up master servers listing's

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#6412]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Tried to spin up multiple dedicated servers different names (different ports) same ip (first server loses ping value on serverlist and second is not visible)

**Steps To Reproduce**
spin up 2 dedicated server with own files from same ip.

**Version**
v0.14.6.0

'''' additional info ''
You can direct connect to the unlisted fine, the first one is visible on server list and you can connect to that 2.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3605/commits/d0ef7bc6d9e560aa6c6003bc641ca69f013838d4

**Comment by NilanthAnimosus** [comment]
Tested against serverlist-ping-fix commit https://github.com/Regalis11/Barotrauma-development/commit/95c040146060302b57b5c01dda76c63a2fd4ee31, no issues found

Notes:
Before the fix on the same machine even (using both different port and query port per server instance):
![image](https://user-images.githubusercontent.com/29177976/194882905-cadec805-d5bd-41ed-9f77-568a51ac0ecb.png)

Same test with fix:
![image](https://user-images.githubusercontent.com/29177976/194883089-82f056d8-6416-495c-bb58-f264213be180.png)

I think this can be safely merged. but I've only tested this on my own machine (which still seems to be an improvement overall for the server list for both public servers).

**Comment by Rokvach** [comment]
Moving to waiting as this is waiting to be merged
