### ISSUE TITLE
Job Variants With the Same Outfit Are Not Shown

### ISSUE THREAD

**Issue by Jlobblet** [Regalis11/Barotrauma#6414]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When multiple `ItemSet`s of a job have the same item identifier with `outfit="true"`, they do not appear separately on the job selection interface. Additionally, the previewed uniform is sometimes incorrect.

To prove this is the case, I have created a minimal example:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Jobs>
	<Job identifier="testjobbroken">
		<ItemSet>
			<Item identifier="assistantclothes" equip="true" outfit="true"/>
		</ItemSet>
		<ItemSet>
			<Item identifier="assistantclothes" equip="true" outfit="true"/>
		</ItemSet>
	</Job>
	<Job identifier="testjobworking">
		<ItemSet>
			<Item identifier="assistantclothes" equip="true" outfit="true"/>
		</ItemSet>
		<ItemSet>
			<Item identifier="bluejumpsuit2" equip="true" outfit="true"/>
		</ItemSet>
	</Job>
</Jobs>
```
As you can see, the only thing that _could_ be different in this mod is the identifier of the outfit.
![image](https://user-images.githubusercontent.com/37539527/128749996-fe6b8efd-9777-454f-af44-007379a634c3.png)
In this screenshot, the shown uniform is incorrect for Test Job Working as it shows the 1st variant selected, but the uniform of the 2nd.

The mod is attached here: [StableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6956342/StableTestMod.zip)

**Steps To Reproduce**
1. Install [StableTestMod.zip](https://github.com/Regalis11/Barotrauma/files/6956342/StableTestMod.zip) and enable it in settings.
2. Host a server.
3. Observe that "Test Job Broken" has no available variants to select.

**Version**
v0.14.6.0, Windows 10 + Ubuntu 20.04

**Comment by NilanthAnimosus** [comment]
To add to this (although not completely related to this specific issue) if a wearble item has no inventory icon defined (IE. prisoner clothing), it does not default to anything. Leaving the preview blank and also perhaps contributing to multiple itemsets not looking correct or showing up properly as well.

Thing is, I believe if you have one that is defined, and one that is not - that too may potentially cause similar issues over just using a duplicate outfit.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
