### ISSUE TITLE
Circuitry (or wires?) set to "hidden in game" doesn't actually work

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#6415]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A circuitry component (like an and or delay component) will stop working when hidden in game.

**Steps To Reproduce**
Create a small circuit, set all of it to hidden in game, and attempt to use the circuit in game.

**Version**
0.14.6.0 linux

**Additional information**
Seems inconsistent. Perhaps it only affects some components, or maybe it only happens with wires, testing was really mixed.

**Comment by Regalis11** [comment]
I did a few quick tests by adding some control circuits to a door (using and and delay components) and hiding them, but unfortunately couldn't reproduce the issue. Would it be possible to post an example circuit where the problem occurs?
