### ISSUE TITLE
Multiplayer campaign fails to load a new campaign level due to not available level transitions

### ISSUE THREAD

**Issue by someaccount44** [Regalis11/Barotrauma#6418]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Campaign won't proceed after 6-8 points at linux server.
It would crash both clients and a server.

**Steps To Reproduce**
Crash happens at the start of level transition.

**Version**
Should be the latest you get from steamcmd.
Client - Windows. Server- Linux.

**Additional information**
Attaching a save file and a couple of screenshots.

[test.save.csv](https://github.com/Regalis11/Barotrauma/files/6960308/test.save.csv) (renamed .save to .save.csv to upload the file)
![image](https://user-images.githubusercontent.com/88710477/128838847-0bc7b910-0ae7-4d60-95e2-f454efb2a373.png)
![image](https://user-images.githubusercontent.com/88710477/128838877-0317a33b-0c24-4049-b089-c3b041a0ca6f.png)

**Comment by someaccount44** [comment]
Wanted to note that

1) Creating any company at linux leads to crash.
2) Creating company at windows while undocked and transfering save files to server would work fine.
3) Most probably the error is due to currentLocation="-1" in save and session files, as soon as we have any valid currentLocationId in save and session data linux server would work as expected.

**Comment by someaccount44** [comment]
![image](https://user-images.githubusercontent.com/88710477/128991698-1d02a0d3-85d7-4245-89ca-4d46fa206be8.png)

Fresh working new save of the company created yesterday.

![image](https://user-images.githubusercontent.com/88710477/128991777-22af75bf-8400-432e-a464-5865fe8bea4f.png)

The same save today (crashing and not working), locaitons are changed, bases moved, damn.

**Comment by someaccount44** [comment]
Manual replacing currentlocation with deepsea would fix the issue.

**Comment by lsby** [comment]
We also encountered this problem, and finally we used the console command `campaigndestination` to modify the destination.

**Comment by Regalis11** [comment]
No known steps to repro. Potentially related to https://github.com/Regalis11/Barotrauma/issues/12045, and most likely fixed since this ticket was created.
