### ISSUE TITLE
Shuttle terminal having issues with sonar 

### ISSUE THREAD

**Issue by MudraptorSeks** [Regalis11/Barotrauma#6423]
I've struggled with this issue for quite some time, going to many people for help. It works on some user's computers but on my computer, the sonar controls (active/passive switch) is greyed out. I can still press shift to toggle it, and it displays the drone and pings on the actual monitor, plus I can steer. 

https://drive.google.com/folderview?id=1QRBgpkCSHx3lYsaWEwsc6JNRv48vi5-o

I'm also having issues docking, but I think that's my own error (plugging the signal in sub-side will allow me to undock, but not redock. Plugging it in shuttle-side does not make the button appear at all)

IMPORTANT edit: the terminals do have use transducers checked. 

Edit 2: only the terminals for the drones in the bottom left (corresponding) have power. Test with those

Edit 3: didn't change anything,just double checked that the boxes were checked. They were, and now somehow they spontaneously work (even though I changed nothing). Only issue now is docking

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8add40a, the fix should be included in the latest unstable build (v0.1400.8.0)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
