### ISSUE TITLE
Category identifiers unapplicable for disallowed upgrades field

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#6424]
**Description**
Category identifiers like `engines` in "disallow upgrades" field won't disallow the engine from being upgraded in campaign, while prefab identifiers such as the listed `increaseenginemaxforce,increasedeteriorationdelay,decreasepowerconsumption,decreasedeteriorationspeed,decreaselowskillfixduration,decreaserequiredskilllevel` works for disabling upgrades in campaign.

**Steps To Reproduce**
Load up Dugong
Enter `engines` into the "disallowed upgrades" field
Save it as another name and launch a campaign with it as the starting sub
Check in the upgrades menu

**Version**
0.1400.8.0

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/8ecade6ffb2a4baf510498bbfb5a0c85d80a385a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
