### ISSUE TITLE
Pirates ignore monsters attacking and breaking in

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6425]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If monsters are attacking a pirate sub, the pirates won't get on the coilguns. If the monsters break in or just break hulls, they also ignore them.

**Steps To Reproduce**
Make mudraptors attack a pirate vessel.

**Version**
v0.14.6.0

**Comment by itchyOwl** [comment]
Targeting monsters fixed in Regalis11/Barotrauma-development@7637b54. It didn't work very well when there was less than 3 monsters.

I didn't find anything wrong with fighting monsters that had broken in the submarine.

**Comment by Rokvach** [comment]
Tested, I was still able to partially repro this, if the pirates the pirate captain has ordered to man weapons gets off of those weapons later on the pirate captain wont order anyone to man the weapons anymore. 

Steps:
1. Host a server and pick the Pirates game mode
2. Start a round and enter freecamera to spectate the pirate sub
3. Spawn a Tiger Thresher and notice that the pirate captain does order someone to man the weapons
4. Wait until Tiger Thresher flees or dies and the pirate operating the weapon gets off the weapon (Can also be achieved by spawning a crawler inside the room)
5. Now that nobody is operating any weapons spawn more creatures around the sub and notice that he captain doesn't say order anything else except fix leaks.

**Comment by itchyOwl** [comment]
Test if Regalis11/Barotrauma-development@6ec070b is enough to fix it. Wasn't able to repro the issue after that.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
