### ISSUE TITLE
[Unstable v0.1400.8.0] Hover nametags stays visible if you hover over a character before accessing a periscope

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6428]
In the below screenshot I moused over Hubert before accessing the periscope and the nametag stays visible and doesn't vanish over time. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4ea35cf3-7eda-4412-9a4d-f40d77ccf0f0)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd4d3347a729edabf63a597c68e11341556f3bdf (originally commited in dev to fix a different issue, but fixes this as well)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
