### ISSUE TITLE
[Unstable v0.1400.8.0] items held in "behind" hand are rendered on top "behind" leg

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6429]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/eb25cf0f-b021-4683-a246-8fd173c32797)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d91b0f1298497cbe4d735ea03a40215342dc9fd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
