### ISSUE TITLE
New Crew Order: Give Medical Assistance- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#643]
Crew member can be ordered one of those things:
*Heal- Will try to restore to 100 nearest person's health by using medicals. Will craft chemicals, if there are none present.
*Restore consciousness- Will preform CPR on characters to restore consciousness or use chemicals to restore health above 0. Will tame bleeding, before preforming CPR.
*Tame bleeding- Will use medicals to remove someone's bleeding.
*Cure husk infection- Will start scanning crew for husk infection and will use or craft calyxanide, when detects it.
*Cure deprivation- Will use morbusanide, or liquid oxygenite to counter oxygen deprivation or morbusine's poison.

If a crew member ordered to preform those actions suffers them himself, he will preform removal actions on himself first. If he is bleeding and is ordered to heal bleeding, he will heal his own bleeding first, not someone else. If he bleeds, but is ordered to seek husk infection, he will ignore own bleeding and of others.

**Comment by Regalis11** [comment]
This has been partially implemented in the dev branch, although not exactly the way you described. There's one "rescue" command, which causes the character to search for unconscious characters, get them to safety and give them appropriate treatment (not fully functional yet, has to be updated for the new affliction system).

IMO the AI doctors should be able to figure out the appropriate treatment themselves - I feel that adding separate commands for different types of injuries/afflictions (bleeding, damage, oxygen deprivation, husk infection, etc) would add too much micromanagement.

**Comment by rico6822** [comment]
Ok.
