### ISSUE TITLE
Ballast flora can not grow/pass through ducts

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6433]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ballast flora neither targets nor can pass through ducts.

This reduces the spread/effect of the ballast flora a lot, depending on the layout of the submarine.
Both during its initial exit from a ballast, and while spreading through a submarine main hallways.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.6.0

**Additional information**
I'm not fully confident in this being a bug, but as the flora growth behaviour is quite alike a creeper plant... yeah
This is definitely not related to any unusual configurations of ballast access, no siree.

**Comment by mc-oofert** [comment]
this would just makre ballast flora hell

**Comment by Krzeszny** [comment]
> this would just makre ballast flora hell

It's not as bad as it is scary. It only drains power and you should always have at least one flamer/steam cannon/incendium grenade on board (or a plasma cutter, diving suit, morphine and patience)
