### ISSUE TITLE
Selecting items with a disconnected wire ignores the wire

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6434]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you select items with a disconnected wire (one of them connected to wire), it doesn't select the wire

If you move the items, wire doesn't move. If you copy-paste the item, wire isn't copied 

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/73229309/129767015-3ddbb65e-9cab-40bc-b558-b143d20fe1b4.png)
_Copied, Original and Moved items_

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f38fb4c23b6c839981eb291d5fc0e486a2ca8ad8

**Comment by Rokvach** [comment]
Moving wires around works fine now, only found issues when copying them

> If you copy-paste the item, wire isn't copied

Noticed a issue with this, when I copied the whole thing with the wire being disconnected it copied the wire correctly but the wire isn't shown as disconnected anymore when viewing the wiring interface and there's a wire item spawned next to the component which had the disconnected wire

Setup
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/61b0b92e-1413-47cd-8043-c0b317e27ba2)

Copied version
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f2d91a84-fb31-4bc0-bc7d-deca854eb4b7)

Disconnected wire isn't shown in copied version
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9641469e-f73a-4f21-8941-72b29c1fd44c)

If I select everything and move them the wire disappears
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/17cd8844-b423-4e5e-aaad-b0f9f385befb)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/630a940b5bcbd44fa3a50fd09ff1a98e740cb4aa
