### ISSUE TITLE
Typo in Affliction "Watcher's Gaze"

### ISSUE THREAD

**Issue by dhakim87** [Regalis11/Barotrauma#6441]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
        <Conditional speciesname="bonethrersher" /> appears three times in the Watcher's Gaze affliction xml.  
I think it should say
        <Conditional speciesname="bonethresher" />

**Steps To Reproduce**
Look in Afflictions.xml

**Version**
Mac OS X

**Comment by Regalis11** [comment]
Which typos do you mean? I couldn't spot any in the affliction xml.

**Comment by dhakim87** [comment]
Bah, github removed the xml tags.  Where it says Conditional speciesname="bonethrersher"

**Comment by dhakim87** [comment]
The deliriumine poisoning also has a causeofdeathdescription Died of sufforin poisoning.

**Comment by Regalis11** [comment]
Ah, didn't notice that one! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f88f3dc8c7d8e33073807237e6d901670e2a37c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
