### ISSUE TITLE
All players drop an equipped item (headsets) when someone fabricates a specific modded equippable item

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6442]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Another desync problem, as the title explains. It's been happening over and over again for us.

**Steps To Reproduce**
Fabricate a T**at**ical Scanner (not Ta**c**tical) from the mod Black Sea's Armory (BArmory in mod menu). All or some players will drop their headsets when the crafting finishes.

**Version**
v.0.14.6.0

**Additional information**
I've been observing an unusually high amount of desync problems lately, such as friends unable to join or people getting kicked.

If requested, I can provide the full mod list.

**Comment by Rokvach** [comment]
I haven't seen this happening nor heard of anyone having this issue for a while now. Seems to have been fixed at some point so working correctly. Closing.
