### ISSUE TITLE
never getting pirate/escort missions in singleplayer campaign

### ISSUE THREAD

**Issue by DeltaNedas** [Regalis11/Barotrauma#6446]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Over 2 singleplayer campaigns started in the current versions, I have never gotten a mission to escort anyone or take out a pirate sub.

**Steps To Reproduce**
1. go from outpost to outpost
2. check everyone for missions
3. only find old missions e.g. killing a hammerhead, chemical shipment, killing a moloch
4. never get a new mission, not even once

**Version**
0.14.6.0, Debian GNU/Linux

**Additional information**
checked between cold sea and end of aphotic plateau in current save
started noticing it in great sea in last save

also I just got the "praise the honkmother" mission which I think is new, still no sight of pirate or escort.

**Comment by Regalis11** [comment]
There's an issue in the current public version that causes these mission types to only be available from cities below 40% difficulty. Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7dc0f626 and https://github.com/Regalis11/Barotrauma-development/commit/da8d9763

**Comment by DeltaNedas** [comment]
yeah i tested out pirate sub in multiplayer, it's definitely not a mission for cold caverns

**Comment by Rokvach** [comment]
This has been tested already and coming in the next update, can be tested in the Unstable branch on Steam already, closing.
