### ISSUE TITLE
"Place in" information isn't shown anymore when you directly drop items to cabinets/loaders/etc

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6447]
Noticed on the dev branch

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1c536386-1b6f-41a5-be80-5ccb25a6c010)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2016bcbf-b125-432a-b06d-919c9b256fec)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1283aef067dfd6a608a9e9b385c500af1e159bcb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
