### ISSUE TITLE
Esperite sprite double definition

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6448]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Esperite has 2 Sprite defintions in minerals.xml, the 2nd one being Chalcopyrite's sprite.

**Steps To Reproduce**
Esperite:
    <Sprite texture="Content/Items/Materials/Minerals.png" depth="0.3" sourcerect="142,262,112,119" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Materials/Minerals.png" depth="0.3" sourcerect="781,133,101,113" origin="0.5,0.5" />

Chalcopyrite:
    <Sprite texture="Content/Items/Materials/Minerals.png" depth="0.3" sourcerect="781,133,101,113" origin="0.5,0.5" />

**Version**
0.14.6.0 and 0.14.9.0

**Additional information**
someone did an oopsy copy paste

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b46c8dc75e4e1f91c0053225f1dae7b58818cd3a

**Comment by Rokvach** [comment]
No issues, closing.
