### ISSUE TITLE
New Crew Order: Threat Fires- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#645]
Crew members can be ordered one of two things in order to remove fire:
*Use fire extinguisher- We all know that. They will simply be dismissed upon not having an extinguisher.
*Flood fire- Will either use pumps, cut walls or flood airlock to remove water. Considered to be a dangerous and alternate option.

**Comment by Regalis11** [comment]
Imo this should be something you have to do yourself, it's such a dangerous procedure even for human players that letting the AI characters do it would often cause a worse disaster than the fire.
