### ISSUE TITLE
Ballast flora can trigger trypophobia [Request]

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6451]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some ballast flora textures can trigger [trypophobia](https://en.wikipedia.org/wiki/Trypophobia). While there's a popular [mod ](https://steamcommunity.com/sharedfiles/filedetails/?id=2326401563)that fixes it, **it's serverside** so I feel it should be tweaked in vanilla, like colors for colorblind people.

**Steps To Reproduce**
_Have trypophobia_

**Version**
v14.6.0

**Additional information**
If there's a mod for it, there's a need for it.

**Comment by Regalis11** [comment]
Thank you for the suggestion, this is definitely something we'll need to consider. I'll close the ticket though, since the issue tracker is for bug reports and this is more of a feature request.
