### ISSUE TITLE
can link deconstructor to diving suit locker but not diving suit locker to deconstructor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6452]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
can link deconstructor to diving suit locker but not diving suit locker to deconstructor

**Steps To Reproduce**
1. select diving suit locker, try to link to deconstructor. no work.
2. select deconstructor. try to link to deconstructor. work.

**Version**
0.14.6.0

**Additional information**
lmao

**Comment by Tsunder** [comment]
sorry, made a typo,

meant to say that Deconstructors, Fabricators, Medical Fabs can be linked to Diving Suit Lockers and just about every other shelf,
and it works as expected

but trying to link the special shelves to decons/etc doesn't link.

**Comment by Regalis11** [comment]
Sorry but I still don't quite follow. Why are you trying to link a diving suit locker to a deconstructor?

**Comment by Tsunder** [comment]
just checking what can and can not be done in the editor

this would have a fun cool behaviour of being able to quickly fill diving suit lockers by sending them from the output slots of the deconstructor

**Comment by Regalis11** [comment]
You can do that by linking the deconstructor to the diving suit locker, instead of the other way around.
