### ISSUE TITLE
Diving mask task as traitor not completing.

### ISSUE THREAD

**Issue by CherryShobe** [Regalis11/Barotrauma#6453]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I get the destory/dispose of diving mask task as a traitor, it doesn't complete.

**Steps To Reproduce**
I get the task, and whenever I either: Deconstruct the diving masks, or throw them out of the airlock, it still doesnt complete the task.

**Version**
0.9

**Additional information**
N/A

**Comment by JoneKone** [comment]
It counts diving masks that are on the ground.

**Comment by CherryShobe** [comment]
> It counts diving masks that are on the ground.

There are none on the ground, I checked every part of the sub.

**Comment by Regalis11** [comment]
No known steps to repro, closing
