### ISSUE TITLE
Reactor Sectors and Pointers Don't Share Same Rotational Origin Position

### ISSUE THREAD

**Issue by matthewpost** [Regalis11/Barotrauma#6454]
- [Indeed] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The reactor sector sprites are not drawn with the same rotational centre as the pointer, causing new users difficulty in knowing where they actually are in the safe/warning zone on the dials.

This might seem low priority, but it's fairly simple to change I hope, and is of great benefit to anyone learning or unfamiliar with the reactor interface.

By allowing to a user to put the needle in the middle of the green rather than trying to match the angles of the pointer to the sector, players will have much more intuitive time.

**Steps To Reproduce**
Open the reactor indicator ui, and configure your load to be maximum, or minimum (easiest in sub editor). I noticed this after implementing a PID controller for the reactor, it's obvious that when you're perfectly matching load the pointer is not in the middle of the green sector. Notice how when you're at the minimum, the pointer always appears clockwise of where it should theoretically be, and at the high end, the pointer always appears counter-clockwise of where it should be. In fact the sectors are too low relative to the pointer (Y axis offsets).

Furthermore, if you draw trace lines from the sector bounds, you can see that it is rotating around a point lower than the pointer rotational origin.

I've given the code a glance, and I think these Draw function calls in reactor.cs need to use the same Y position or at least have the Y changed, though I'm not sure what the preferable offset would be:

```
 if (optimalRangeNormalized.X == optimalRangeNormalized.Y)
            {
                sectorSprite.Draw(spriteBatch, pos, GUI.Style.Red, MathHelper.PiOver2, scale);
            }
            else
            {
                spriteBatch.End();
                Rectangle prevScissorRect = spriteBatch.GraphicsDevice.ScissorRectangle;
                spriteBatch.GraphicsDevice.ScissorRectangle = new Rectangle(0, 0, GameMain.GraphicsWidth, (int)(pos.Y + (meterSprite.size.Y - meterSprite.Origin.Y) * scale) - 3);
                spriteBatch.Begin(SpriteSortMode.Deferred, rasterizerState: GameMain.ScissorTestEnable);

                float scaleMultiplier = 0.95f;
                sectorSprite.Draw(spriteBatch, pos, optimalRangeColor, MathHelper.PiOver2 + (allowedSectorRad.X + allowedSectorRad.Y) / 2.0f, scale * scaleMultiplier);
                sectorSprite.Draw(spriteBatch, pos, offRangeColor, optimalSectorRad.X, scale * scaleMultiplier);
                sectorSprite.Draw(spriteBatch, pos, warningColor, allowedSectorRad.X, scale * scaleMultiplier);
                sectorSprite.Draw(spriteBatch, pos, offRangeColor, MathHelper.Pi + optimalSectorRad.Y, scale * scaleMultiplier);
                sectorSprite.Draw(spriteBatch, pos, warningColor, MathHelper.Pi + allowedSectorRad.Y, scale * scaleMultiplier);

                spriteBatch.End();
                spriteBatch.GraphicsDevice.ScissorRectangle = prevScissorRect;
                spriteBatch.Begin(SpriteSortMode.Deferred);
            }

            meterSprite.Draw(spriteBatch, pos, 0, scale);

            float normalizedValue = (value - range.X) / (range.Y - range.X);
            float valueRad = MathHelper.Lerp(sectorRad.X, sectorRad.Y, normalizedValue);
            Vector2 offset = new Vector2(0, 40) * scale;
            meterPointer.Draw(spriteBatch, pos - offset, valueRad, scale);      // Other lines could be changed to match this??
```

I think the desirable solution is to move the sectors to match the needles and keep the meterPointer and meterSprite, but UI design has never been my strong point.

**Version**
I'm using Vanilla Steam Release version 0.14.6.0 as of 2021-08-21.

**Additional information**
![image](https://user-images.githubusercontent.com/23487461/130354900-d3b2d309-36eb-4b96-a89a-0954e1283aae.png)
The origin of the reactor sector doesn't line up with the rotational origin of the pointer. I think the colour sectors should be moved up (-Y, to pos-offset instead of just pos) to match the pointer, and the pointer/meterSprite should stay where they are.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
