### ISSUE TITLE
Damaged glass in Kastrull's command room doesn't cause a leak

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6469]
Noticed on the dev branch

Can be tested by plasma cutting that part of the wall that is shown on the picture below. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/dffa9923-1b4d-4b55-9b5c-827907d0c38a)

**Comment by itchyOwl** [comment]
We have an old ticket on the private repo, which is probably related if not a duplicate: Regalis11/Barotrauma-development#2031.

**Comment by Regalis11** [comment]
We have a newer ticket about the general issues with these sloped walls https://github.com/Regalis11/Barotrauma/issues/7154, closing this one
