### ISSUE TITLE
Chained Relay Load Calculations Ignore Throughput

### ISSUE THREAD

**Issue by Lughbaloo** [Regalis11/Barotrauma#6471]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Relays will calculate the load of a grid, and then transmit that load to its' provider grid in an attempt to receive power. This is expected behavior.

When multiple relays are chained in a series, each relay will send its' load value to the provider grid which is another relay. That provider relay's new load will now equal **total load up to throughput value** + **load from any connected relays**. Instead it should be **total load including connected relays up to throughput value**. As it is now, a relay with a throughput of 1000 can have a load on its' provider grid wayyy higher. The grid will then generate that amount of power and send it to the relay. Because relay throughput is still only 1000 though, only 1000 power will actually make it through the relay, potentially undervolting many devices.

**Steps To Reproduce**
Connect a grid as such: Battery > Junction Box > Relay > Any # of Relays. Have the throughput of the first relay (really any relay) set to 1000 (default). Attach more than 1000 load across the relays, and the load value seen on the first provider grid will exceed 1000 despite the relay's throughput.

**Version**
Windows
Build ID 6884680, Main branch Thunder under the ice

**Additional information**
The load displayed on the Relay's GUI is independent from the actual load on the provider grid. In my testing, I have found that while a relay may display Total Load + Attached Relays, it will actually transmit Throughput + Attached Relays. If Total Load is higher than Throughput, this will lead to mismatched numbers.

**Comment by Regalis11** [comment]
Most likely fixed by `power-rework`, moving to testing

**Comment by Rokvach** [comment]
Tested by Jade Harley and confirmed working (video proof), closing.
