### ISSUE TITLE
Reactor and particle effect of stored item offset to top left corner

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#6472]
**Description**
Contained item particles are offset to top left corner of the sprite box

**Steps To Reproduce**
Store an item with a particle effect in a reactor, instead of generating the particle at the center of the reactor it spawn them at the top left corner

**Version**
0.14.9.0 Windows release version

**Additional information**
This did not happen before the recent update, affects new reactor added via mods it also move the explosion effects attached to the item to this position

![image](https://user-images.githubusercontent.com/87786019/130833627-347a9242-9891-44db-96d7-548d7a7b9d9f.png)
![image](https://user-images.githubusercontent.com/87786019/130833677-ca9a6b38-57dd-496c-930b-87a08d609881.png)

**Comment by Lithosagym** [comment]
Tested, seems to be fixed.

**Comment by Rokvach** [comment]
Closing.
