### ISSUE TITLE
scale issue with construction barrier

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6474]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Scaling "construction barrier" decoration (the yellow/black tape, not the post) results in a console error and invisible tape.

**Steps To Reproduce**
> be me
> open sub editor
> place "construction barrier" (tape)
> increase the scale
> mfw

**Version**
0.14.9.0

**Additional information**
![image](https://user-images.githubusercontent.com/5103517/130834548-9680ea4f-4cf5-411d-b308-49e7d97ee708.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ee9669b2ce357ffa8b03f1a61a881965c1de4f7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
