### ISSUE TITLE
No structure damage from melee weapons when outside hull

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6475]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Melee weapons with structure damage are only dealing damage when the wielder is inside hull, and are not dealing the damage when attacking from outside.

expectation is that the attack works regardless of where the attacker is, so long as they're in range.

**Steps To Reproduce**
1. use a structure damaging melee weapon (i.e., screwdriver, toolbox) from outside the submarine to attack the submarine

**Version**
0.14.9.0

**Additional information**
It's quite difficult to tell where the attack effect of weapons are tbh

**Comment by Tsunder** [comment]
made a video of it

https://user-images.githubusercontent.com/5103517/153690311-12a9cb40-e69b-40d8-9cad-13893785b1a8.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5420de91f636eea1190fb9aa3ae531a9d78d4f0c

**Comment by NilanthAnimosus** [comment]
Tested against 0.18.15.0 unstable. Working correctly, closing.
