### ISSUE TITLE
Shorten or differentiate diving suit low oxygen beeping

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6481]
Original idea from this thread: https://steamcommunity.com/app/602960/discussions/2/3042732243090571647/

I think it would be wise to revisit how we communicate the low oxygen state to players, currently the beeping starts way earlier to alarm the player that their oxygen is about to run out, as we have visually improved with screen effects when a player doesn't have any oxygen I don't think this long of a warning would be necessary anymore.

There's couple things that can go wrong with the current approach
1. Players replace oxygen tanks way too early which leads to inventory fill of 5% or less oxygen tanks.
2. Players forget to replace oxygen tanks if they wait for them to be empty first.

Couple suggestions on how we could change this:

A. Only start beeping either seconds before oxygen runs out or when tank is already empty.
B. Differentiate the beep sound before and after the oxygen has ran out. The beep before could just be slower variant of the current beep.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/d995d26f2d2409475c87862c40c73ae9cd79806b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
