### ISSUE TITLE
[0.1500.0.0] Crash when an attack is applied on a character from a source that's not another character

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#6488]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes when an item (for example a propeller) applies an attack on a character.

**Steps To Reproduce**
Swim into a propeller

**Version**
0.1500.0.0

**Additional information**

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7060395/crashreport.log)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
