### ISSUE TITLE
Crew Orders in Multiplayer Replaced With Gesture Panel- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#649]
Under "c" key in multiplayer players can display certain animations to signalize something. "C" has to be hold and gestures are automatically executed, after pointing at them (clicking is not involved).

**Examples:**

I can't speak- Pats own throat. Cannot be used, while in advanced stage of husk infection. Can be used when not infected at all. With 1+2 item in hands will pat own throat with that item.

Look- Points at direction, where mouse cursor is set. Can't be done with 1+2 items.

Get down- Covers head with own hands (for crouching ctrl has to be held). Does kneel normally, when crouching. Can't be done with 1+2 items.

It's mine- When holding an item in hands will hold that item opposite direction faced behind own back. Must hold any item for this gesture.

Take it- Holds item in front of self, but other crew members can take it. Must hold an item for this gesture.

Thanks- At least one hand must be free for that gesture. Makes a thumb up in direction pointed.

Hello- Releases a hand in front of self and waves it at moderate speed. Not supported by 1+2 items.

Good job- Begins to clap in pointed direction. Must be empty handed. Also makes sound effect.

Facepalm- At least one hand must be free for that gesture. Will cover own face with own hand and than have own head face floor.

Double facepalm- When one hand is not enough. Both hands must be free for that gesture.

All those gestures are looped infinitely, unless character gets unconscious, mission ends or they press "c" again to stop animation.

Trivia: Husks controlled by other players can also preform gestures.

**Comment by Regalis11** [comment]
This seems pretty redundant, considering we already have the chat, the report/order system and the upcoming voice chat.
