### ISSUE TITLE
[unstable] poor choice of hull to display status in

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6490]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Status monitor ID display puts the icon in the "middle" of linked hull, rather than where the holder actually is.
This is very notable when there's 3 linked hulls, the largest being a non-center one.

**Steps To Reproduce**
1. have 3 linked hulls of different size
2. status monitor

**Version**
0.15.0.0

**Additional information**
example, on the mayari:
![image](https://user-images.githubusercontent.com/5103517/130996360-82e138bc-b57c-4b96-8f2c-4e578fbac06a.png)

**Comment by 3e849f2e5c** [comment]
I haven't encountered this since https://github.com/Regalis11/Barotrauma-development/commit/6699604b5e7e52e3c77236123b5a01ceb423ec9c possibly fixed?

**Comment by Rokvach** [comment]
Tested with multiple custom subs, seems to be working correctly. Closing.
