### ISSUE TITLE
fuel rods condition appear to be bullets

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6491]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/5103517/130997853-8fe1ec6f-af93-4ff5-abf4-eb6add43064d.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15

**Additional information**
lol

**Comment by Rokvach** [comment]
Tested, no issues.Closing.
