### ISSUE TITLE
[unstable] Disguising does not fool radio buttons nor NPCs

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6492]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Disguising does not fool NPCs, nor the radio button.

**Steps To Reproduce**
1. PVP
2. take opposing team's ID card, disguise as.
3. opposing team NPCs/intruder radio alert still triggers
 
**Version**
0.15.0

**Additional information**

**Comment by Regalis11** [comment]
I'd consider this more of a feature request than a bug report, so I'll close the ticket. But regardless, it'd be fun to be able to use disguises against AI characters, so this is definitely something we'll consider!
