### ISSUE TITLE
[unstable] status monitor hull bleed

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6494]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
water% bleeds into other hulls, especially noticable at further zooms
![image](https://user-images.githubusercontent.com/5103517/131006839-c94b2ef8-485a-4e51-a79f-7409a94c587f.png)

![image](https://user-images.githubusercontent.com/5103517/131006780-1f6213a7-e291-4218-a0ec-e888299ed3b6.png)
**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.0
**Additional information**

**Comment by Rokvach** [comment]
I'm not fully sure what to look for but if it means that the water surface is shown 1 pixel above the hull border that still seems to happen

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/53f42c5e-021e-4501-8b87-dc509cdd638f)

**Comment by 3e849f2e5c** [comment]
seems like I offset the line in the wrong direction, should be actually fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e7b3ba0aa5c34335e656ea4a667c965a7830145

**Comment by Rokvach** [comment]
Not sure if this is related to these changes or just a old issue that I only now spotted but the water level seems to only go up to 99%, tested on Dugong and Humpback and got the same results in both of them

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/578f5b36-b76e-4722-9b1a-98a94ffd1f60)

**Comment by Tsunder** [comment]
I presumed it to be intentional ballast behaviour.

this occurs on stable for as long as I know.

**Comment by Rokvach** [comment]
The above issue isn't related to this ticket, closing as the ticket works correctly.
