### ISSUE TITLE
[unstable] position_y_out on navigation terminal does not output

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6495]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Position_y_out on navigation terminal doesn't output any signal
pos_x, vel_x, vel_y work though.

**Steps To Reproduce**
1. connect position_y_out from nav terminal to a text display / terminal
2. no output

**Version**
0.15.00

**Additional information**

**Comment by Ecchi-Ki-Senpai** [comment]
Position_y_out is outputting as of  0.1500.1.0

**Comment by Rokvach** [comment]
Closing
