### ISSUE TITLE
Terminal welcome message repeat

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6497]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
welcome message repeats at humpback's terminal

**Steps To Reproduce**
1. load in the humpback in sub editor or in multiplayer
2. check terminal
**Version**
0.15.00

**Additional information**
![image](https://user-images.githubusercontent.com/5103517/131013592-251fe115-d1ae-44d6-9eb0-de9825ae0aac.png)

**Comment by Rokvach** [comment]
The terminal doesn't have any message now

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/74157801759221c5e3b9b0dc3aa1d08dd8308181

**Comment by Rokvach** [comment]
I see a welcome message at the top terminal twice and none at the bottom terminal what is next to the reactor

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
