### ISSUE TITLE
timing issue with XOR component

### ISSUE THREAD

**Issue by Stupitar** [Regalis11/Barotrauma#6501]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
XOR component outputs a double signal from two input pulses that should be synchronized.

**Steps To Reproduce**
Periscope trigger -> Delay 1 input and Delay 2 input.  Delay 1 has a 0.05s delay and "reset when signal received" is set; Delay 2 has a 0.25s delay.  Delay 1 output -> AND input 1 and  Delay 1 output -> XOR input 1.  Delay 2 output -> AND input 2.  AND output -> XOR input 2.  XOR output to Terminal.

XOR produces 1 signal pulse from a single periscope trigger.  The XOR should not produce a signal when the periscope trigger is held for at least 0.25s before being released but instead it produces 2 pulses.  I added a second AND component with a complimentary Memory component between Delay 1 and XOR, but the result was the same.

**Version**
v0.14.9.0.  Mac 11.5.2

**Additional information**
![XOR-AttemptedDelayClickCircuit](https://user-images.githubusercontent.com/77932907/131072297-b39e2cf7-2add-415c-933a-7378b2925f9f.png)

**Comment by Regalis11** [comment]
I've created a "general" ticket about signal timing issues, closing this one https://github.com/Regalis11/Barotrauma/issues/12993
