### ISSUE TITLE
Bots don't pick up certain ammo types

### ISSUE THREAD

**Issue by kitpaddel** [Regalis11/Barotrauma#6502]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems bots given the "cleanup items" order ignore certain ammo types. I observed this at least with "revolver round", "shotgun shell" and "stun gun dart".

**Steps To Reproduce**
- Start a session, preferably with a sub having a "secarmcap" (i.e. the dugong)
- Give the "cleanup items" order to a character having access to the secarmcap (i.e. the captain)
- Drop a revolver round/shotgun shell/stun gun dart to the ground as well as a smg magazine
- Observe how the bot picks up the smg magazine and stores it in the "secarmcap" (or another place when available) but ignores the revolver round/shotgun shell/stun gun dart.

**Version**
Windows v0.14.9.0
as well as the unstable version

**Additional information**
This problem is not specific to the secure containers. If the ammo is modded to be places in other containers as well, bots still ignore them.

**Comment by itchyOwl** [comment]
Fixed in Regali11/Barotrauma-development@6cab795.

**Comment by Xeavas** [comment]
[V0.1500.2.0] Unable to replicate, bots were able to clean up revolver rounds, shotgun shells and stun gun darts 👍

**Comment by Rokvach** [comment]
Closing
