### ISSUE TITLE
Cannot pop up candidate box when using Microsoft Pinyin input method 

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6509]
The problem is very simple:
in the game, when using the Microsoft Pinyin input method, typing characters will not pop up the candidate box, which makes the code word very difficult for Chinese, so almost all Chinese players are accustomed to using voice communication. 

I have noticed that many Chinese players are talking about this issue, but no one seems to report this issue.

**Comment by changhexiong** [comment]
There is an unofficial solution to this problem now.
[https://steamcommunity.com/sharedfiles/filedetails/?id=2789811877](url)
But it is not compatible with LuaForBarotrauma.
So I hope the official can solve this problem as soon as possible.

**Comment by Regalis11** [comment]
I'm closing this in favor of a newer ticket https://github.com/Regalis11/Barotrauma/issues/9509
