### ISSUE TITLE
Repairing overloaded junctions boxes causes the item to break many times a second, causing fires 100% of the time.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#6513]
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempting to repair a completely broken junction box while it's being overloaded will cause the item to break many times per second, creating almost guaranteed fires (On junctions that have fires enabled ofc) and a lot of particles.

**Steps To Reproduce**
Pump enough power into a junction to overload it until it breaks, and attempt to repair it while it's still being overloaded.

**Version**
V0.14.9.0 (Windows)

**Additional information**
I also recorded this bug https://youtu.be/jDSgd-yHfKo

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/64933046c600236efd949141c8dbb77a1ef5727b

**Comment by Lithosagym** [comment]
Tested, confirmed to be fixed.

**Comment by Rokvach** [comment]
Closing.
