### ISSUE TITLE
When pets eat player corpses, they also eat the player's inventory

### ISSUE THREAD

**Issue by GammaWhiskey** [Regalis11/Barotrauma#6514]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a pet eats a player's corpse, they consume the contents of the players inventory as well.

**Steps To Reproduce**
1. Die near a hungry pet.
2. Let the pet eat the corpse.
3. The player's inventory contents are gone.

**Version**
v0.14.9.0 on Windows.

**Additional information**
Ideally, a pet eating a player's corpse would leave behind a duffel bag containing the player's items. I am unsure if this occurs with other corpses with inventories.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/430ce527c9188a0e14e8b92440cfd023d4a28f2d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
