### ISSUE TITLE
Submarine part FRONT G, all parts appear transparent for Line of Sight (LoS)

### ISSUE THREAD

**Issue by matthewpost** [Regalis11/Barotrauma#6515]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All of the FRONT G1 and G2 parts don't obstruct LoS at all. They look as though they should be opaque as they match the style of FRONT A and FRONT B. If the "G" was used to denote glass, I'm a little surprised (because there are front parts A-G). It's not something that can be noticed until playtesting the submarine. I noticed it while swimming around outside of the sub, and I could see inside.

Similarly, FRONT A Doesn't block LoS beyond its rectangular selection box (as seen in the editor). It leaves ugly LoS gaps.

This is related to #6000, but I think it's different. My concern is with the size of the box used to block LoS with certain sub parts.

I made a little dummy sub and resized the FRONT G2 Parts on the left to match the size of the FRONT A parts on the right. You can see the missing LoS obstruction on left, and a bad LoS box on the right.
![image](https://user-images.githubusercontent.com/23487461/131234216-7e18f8bd-932a-4114-a02e-a5653e40b5a4.png)

**Steps To Reproduce**
Build a sub with at least one of the parts: FRONT G1 p1, FRONT G1 p2, FRONT G1 p3, FRONT G2 p1, FRONT G2 p2, FRONT G2 p3

**Version**
Steam release v0.14.9.0 vanilla

**Additional information**
- I think the LoS boxes are a bit wonky on any curved parts, because right now the obstruction boxes are rectangles.
- The descriptions of FRONT G parts in the build selection menu say "Submarine front C temp", when FRONT A and FRONT B say "Submarine front A temp" and "Submarine front B temp" respectively

**Comment by Regalis11** [comment]
The front parts were intentionally made see-through, because the rectangular occluders look bad on pieces shaped like this. Could be fixed when we address https://github.com/Regalis11/Barotrauma/issues/6000
