### ISSUE TITLE
[Status monitor] Item finder ping isn't positioned relative to the submarine when zooming in/out

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6520]
Noticed in dev branch

Before zoom
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9e2a7fef-9a83-4444-9469-8cc49f6b0e0a)

After zoom
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/93938218-5beb-412f-84b1-061a12960e94)

**Comment by 3e849f2e5c** [comment]
Broke it by accident when I made hull status view not zoomable, fixed in https://github.com/Regalis11/Barotrauma-development/commit/aed8c1375f7ed64fc322e7ae8f60b695263723df

**Comment by Rokvach** [comment]
The pings now follow correctly when zooming but they are positioned higher than where the submarine is, wrote a separate ticket for that so closing this one.
