### ISSUE TITLE
Crewlist background blocks mouse input

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6521]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fe41aebf-5bb0-4d3c-ba28-c6183dab5ceb)

**Comment by itchyOwl** [comment]
Yeah I noticed too. Was this fixed at some point?

**Comment by ekqvist** [comment]
I think I fixed it last year in Regalis11/Barotrauma-development@5610484. It might have been broken again with the elements being made draggable.

**Comment by ekqvist** [comment]
Should be fixed with Regalis11/Barotrauma-development@62e1198 and Regalis11/Barotrauma-development@9028924

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
