### ISSUE TITLE
Use wire to connect between two submarines

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6522]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Use wire to connect between two submarines

**Steps To Reproduce**
1. Open Submarine editor
2. Load Remora.sub
3. Test
4. Use wire to connect the DockingPort'Power of Remora to the DockingPort'Power of Remora Drone
![bug](https://user-images.githubusercontent.com/73634685/131311464-3264bd16-4987-49f6-b232-185e649b8be7.png)
5. Let Remora Drone undock
6. The battery of Remora Drone can still get power from Remora

**Version**
0.14.9.0 Windows

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3c53bfcedadfae43578369b9dd6477141c38df4c

**Comment by Xeavas** [comment]
[V0.1500.2.0] Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing
