### ISSUE TITLE
[Status monitor] Item finder pings are positioned higher than where the submarine is

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6527]
The pings are positioned higher than what they should be

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a0c7cd46-3ee4-4f26-b109-ad604b61e4c5)

**Comment by Rokvach** [comment]
Nvm doesn't seem to be related to the outpost at all, even when you undock from the outpost the position of the pings is incorrect

**Comment by 3e849f2e5c** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/67f87b467f216151bfa65345ffa801995beb26cb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
