### ISSUE TITLE
Items with multiple layers rotate wrong if mirrored y

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#6528]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items with multiple layers such as loaders, bed, or fabricator will have their other layers rotated wrong if using mirrored y (rightmost 2 items are not mirrored and is normal when rotated): 
![image](https://user-images.githubusercontent.com/70696707/131475995-38844b0f-2259-4f0f-a67c-29beec29eee9.png)

**Steps To Reproduce**
Place an item with multiple layers in editor such as loader, mirror y, then rotate.

**Version**
Windows Unstable V0.1500.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7737c27b26cd07c17de8bda776635fc597916686

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
