### ISSUE TITLE
Periscope base is positioned too high in Humpback

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6529]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7d9d06e8-b8ea-4a24-bec7-72f56db1b1e4)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9108eb6c1f9ebd4c57433bea72bcd8010280bf48

**Comment by Rokvach** [comment]
The base looks off to me still
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/3bdf6f1a-480e-4836-bb27-7e2f4ef01d99)

**Comment by Regalis11** [comment]
Whoops, attempt 2: https://github.com/Regalis11/Barotrauma-development/commit/2505c6151e471f53bc4a840989a0e32b46691425

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
