### ISSUE TITLE
Tremor Detector- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#653]
Will send out signal, once it detects hydrothermal vents or any other shake.

**Comment by NilanthAnimosus** [comment]
I literally do not see the point to a hydrothermal vent / shake detector. Maybe a detector that works out if a strong impact has occured for the submarine/character body instead (for collissions/submarine crashes).

I think players would clearly know they crashed near/into a hydrothermal vent. they are extremely hard to miss given the amount of sound and screen shake they actually emit, and there is no submarine wiring I can think of that has any benefit for hydrothermal vents so I know if won't be used for any kind of wiring I can think of. It doesn't seem to have any in-game usage.

**Comment by Regalis11** [comment]
I have to agree with Nilanth, I can't really think of any practical use for this kind of item.
