### ISSUE TITLE
Sonar Transducer Power Consumption

### ISSUE THREAD

**Issue by Stupitar** [Regalis11/Barotrauma#6531]
The Sonar Transducer draws power while active and passive, but the sonar of a Navigation Terminal draws power only when active.  Why?

**Comment by PaladynMinak** [comment]
You can set transducer or navigation terminal sonar power consumption independently. So if you're e.g. building drone without terminal, you can set consumption for transducer alone, or if you have shuttle with transducer, you can set transducer power consumption to 0, because navigation terminal will generate consumption, when using sonar. Or you can leave it, which can help negate low/overvoltage resulting from sudden changes in work of engine/pumps etc.

**Comment by Stupitar** [comment]
I understand your work arounds for the game in its current version, but that is not an answer to my question.

In a future update can the sonar transducer's power draw be determined by the terminals using it? 

Also if a sonar transducer is activated by one terminal, can an ancillary terminal connected to it receive the active sonar transducer data automatically?  The system seems a bit incomplete or not fully thought through since the addition of the mineral scanner and the rendering of its incompatibility with the steering component.

The simplest fix is to allow the mineral scanner feature to be active with the steering feature.  If not I have these suggestions:

Redesign the sonar terminal to be a master control for the sonar transducer.
Let the sonar terminal be a sonar transducer or depend on an external one.
  Give the sonar terminal a sonar data out pin to potentially be used by a navigation terminal.
  Give the sonar terminal translation data (x and y velocities) out pins.
  Give the sonar terminal a depth data out pin.

Let the nav terminal be a sonar transducer or depend on an external sonar transducer or a sonar terminal.
  allow the nav terminal to toggle the sonar active or passive state wether it has its own sonar transducer or is dependent on an external source, the sonar terminal or external sonar transducer.

If using an external sonar transducer let its power draw be determined by its active or passive state

**Comment by Regalis11** [comment]
The navigation terminal and sonar monitor do actually consume power in passive mode as well, but just 10% of the normal power consumption. I made the sonar transducers behave the same way in https://github.com/Regalis11/Barotrauma-development/commit/15d9caa33784b960195e9f67e11b015de23e2969 to make it more consistent.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
