### ISSUE TITLE
Unable to load drag and drop files in the sub editor when using NetEase UU

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6537]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If I open steam on Netease uu(https://uu.163.com/), and then start the game on steam, you will be unable to load .sub, .xml, .png and .jpeg files in sub editor by dragging and dropping them onto the game window.
In fact, most Chinese players need to use NetEase uu to log in to Steam,
However, there may be conflicts between the game and NetEase uu, resulting in the inability to drag and drop to load .sub file.
I think it's a unnecessary issue, but at least a large number of players haven't been able to use this feature, and It would be best if problem can be solved.

**Steps To Reproduce**
1. Launch Steam on NetEase uu
2. Launch Barotrauma
3. Open Submarine Editor
4. Drag and drop a .sub file onto the game window
5. Nothing happens
![GIF 2021-09-01 下午 03-43-16](https://user-images.githubusercontent.com/73634685/131637848-f30a6ed1-7957-47b6-8134-760b2d915f37.gif)

**Version**
0.14.9.0 Windows

**Comment by zhu-rengong** [comment]
And I don’t know if I’m the only one with this problem.

**Comment by zhu-rengong** [comment]
No problem, it does work.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
