### ISSUE TITLE
Smoke Detector- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#654]
Will either send signal, when fire extinguisher is used on it or there is fire nearby capable of damaging physically players or deprivate their oxygen.

**Comment by NilanthAnimosus** [comment]
Compared to a fire detector I am not even sure what the applicable uses of this is, Either you want to detect fire, or the smoke of the fire - I don't see a reason to have both this and #655 - it feels more like pointless feature/content creep than actually serving any kind of new purpose.
