### ISSUE TITLE
You can swap non-interactable items out of inventories

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#6541]
**Description**
You can swap non-interactable items out of inventories, potentially getting stuck in the players inventories if they don't know the cause or how to reverse it.

**Steps To Reproduce**
1. Have a coilgun loader
2. Make a coilgun ammo box uninteractable and place it in said loader
3. Have a interactable coilgun ammo box
4. Load into game and dragging the interactable one over the uninteractable one.

**Version**
V0.1500.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a8229426e4fdc21e944ae21859eeb708775659f6

**Comment by Xeavas** [comment]
[V0.1500.2.0] No issues 👍

**Comment by Rokvach** [comment]
Closing
