### ISSUE TITLE
Crash when fabricator is running at the end of a round and finishes the next round

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6546]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i got 2 crashes in the same level, 1 is from the already fixed atack bug and the other one is new
[crashreport (18).log](https://github.com/Regalis11/Barotrauma/files/7102163/crashreport.18.log)
[crashreport (19).log](https://github.com/Regalis11/Barotrauma/files/7102164/crashreport.19.log)

happened again in another level
[crashreport (21).log](https://github.com/Regalis11/Barotrauma/files/7102202/crashreport.21.log)

another crash, inside an outpost.
[crashreport (22).log](https://github.com/Regalis11/Barotrauma/files/7102217/crashreport.22.log)

i think i figured it out:
starting to fabricate an item, end a round, and starting a new one will make it so whenever the item is done the game crashes, for me it happened with a combat suit, i have to test if it's consistant. 

**Version**
windows v0.15.0.0 unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97354563f991c094dda615ad1c8e851770b778b4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
