### ISSUE TITLE
Bots are having a hard time operating a reactor

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6547]
After class progression was merged to dev all the outposts are without a power and when you start a round all the bots spams the chat with "loading more fuel to the reactor" messages but fails to actually turn the reactor on

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7febaba2-96be-441d-8b40-c97c60fca1d3)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c15280ef467c61982360d5863a4f361e366ff72

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
