### ISSUE TITLE
Mirrored item does not remember their updated rotation angle when copied

### ISSUE THREAD

**Issue by DreamerOfRain** [Regalis11/Barotrauma#6548]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After mirroring an item, if you copy it the rotation angle that was supposed to be updated after mirroring does not get carried over. 

https://user-images.githubusercontent.com/70696707/131983348-6ce585d5-6808-4daa-a551-b82f7f784002.mp4

**Steps To Reproduce**
1. Place an item, rotate it, then mirror. The item rotation value should have been updated for this item.
2. Copy said item and paste it. The newly pasted item has the sprite mirrored, but the rotation value does not have the updated value.

**Version**
Window 0.1500.0.0

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3d4efc0fbd97d525ddc4e4e738ed5ceedc41bf9.

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/99170ee5-b68d-488a-aeda-fdd9c0368a2a)

**Comment by Rokvach** [comment]
The above screenshot wasn't clear enough so took a new one
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/1866f9de-7bbd-4745-a2b3-3b4ec25681eb)
