### ISSUE TITLE
[Unstable] Crash when loading a submarine

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6549]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash when loading a submarine

**Steps To Reproduce**
Load this "sub"
[[Hubert] Shuttle test platform.zip](https://github.com/Regalis11/Barotrauma/files/7105548/Hubert.Shuttle.test.platform.zip)

Crash report: 
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/7105546/crashreport.10.log)

v0.1500.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06a8aa45c99b2a6ca6f07762e9e65de3698cf14f

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.
