### ISSUE TITLE
[Unstable] Crew icons have different sizes on status monitor based on room

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6550]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crew icons have different sizes on status monitor based on room
The bigger the room the bigger the icon

![image](https://user-images.githubusercontent.com/73229309/132000423-572aed20-91bb-487a-b08b-ae12c4ae3084.png)

v0.1500.1.0

**Comment by Tsunder** [comment]
the icons touching both the ceiling and floor also looks aesthetically unpleasing

**Comment by Regalis11** [comment]
@3e849f2e5c I suppose this was addressed in https://github.com/Regalis11/Barotrauma-development/commit/cfe4e84?

**Comment by 3e849f2e5c** [comment]
I was waiting on to see if it needed some fine adjustments first before moving to QA but yeah implemented in https://github.com/Regalis11/Barotrauma-development/commit/cfe4e84

Made the icons always be the same size regardless of the hull size and lowered the alpha a bit in case the icons are in small so you can see thru them

**Comment by Rokvach** [comment]
Tested, looks good. Closing.
