### ISSUE TITLE
[Unstable] Assault rifle recoil makes it fly past character shoulder

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6551]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Assault rifle recoil makes it fly past character shoulder

**Steps To Reproduce**
Shoot the new assault rifle

The stock goes past the shoulder
![image](https://user-images.githubusercontent.com/73229309/132002376-2bbfcc4b-34df-4693-9dfb-8461a41813f0.png)

v0.1500.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/acdb5ec0ef80b4343a030a738f1f1eb17030dc34

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
