### ISSUE TITLE
[Unstable 1500.10] Unable to load Save (Single Player Campaign)

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#6552]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Loading a Single Player Campaign save is unsuccessful and results in an error (shown below).

**Steps To Reproduce**
- Load save file

**Version**
Unstable 0.1500.1.0 revision 888c5e3298. Windows 10

**Additional information**
Error:
![image](https://user-images.githubusercontent.com/58775950/132005042-414bfe84-3e77-4888-be1e-db5015dc2806.png)

Save file:
[Unstable_1500_Malaco.zip](https://github.com/Regalis11/Barotrauma/files/7105832/Unstable_1500_Malaco.zip)

Rokvach said it appears to be similar to issue #6549

**Comment by Regalis11** [comment]
Based on the stack trace this seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/6549
