### ISSUE TITLE
Sonar Beacon keeps working even after the battery depletes

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#6557]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sonar Beacon keeps working even after the battery depletes

**Steps To Reproduce**
1. Get a Sonar Beacon
2. Activate it
3. Put it in your toolbar or any inventory
4. Wait for the battery to reach 0%
5. Watch the beacon still making sound and showing up in the sonar monitor

**Version**
Release 0.14.9.0 - Windows 10 64 bits

**Additional information**
Dropping the Sonar Beacon on the ground or equipping it will make the beacon go inactive. This probably happens with other items as well, that consume the battery while not equipped.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d786d1061f0fc9924d71571061442dd385149576

**Comment by Xeavas** [comment]
[V0.1500.2.0] Unable to replicate, beacon stops making noise and displaying on nav terminal after battery depletion 👍

**Comment by Rokvach** [comment]
Closing
