### ISSUE TITLE
Attach Components Inside Ruins and Preform Wiring- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#656]
You can simply plant detonator inside ruins or use a button on the alien door to open it by wiring.

**Comment by thegrb93** [comment]
Wiring an alien door doesn't make any sense to me but placing detonators might be useful

**Comment by rico6822** [comment]
It's a manner of details.

**Comment by NilanthAnimosus** [comment]
Hilariously, the artifact holders essentially emit signals, I wouldn't mind being able to hook something like that to an alien door as if it were some kind of simple puzzle that you might not have any access to when locked in.

of course I think it would be nice to be able to place detonators inside ruins, right now the detonators only use is hilariously to blow up submarines in multiplayer (Which most hosts don't even want their traitors doing)

**Comment by Regalis11** [comment]
I don't believe alien devices should be possible to rewire, but attaching devices on alien ruins would be a good way to give the players some additional means to explore the ruins and deal with the fractal guardians.

Issue #738 encompasses attaching detonators and other items on ruin walls if we implement it by making it possible to attach things on any sort of background wall, so I think this one can be closed.
