### ISSUE TITLE
"Once upon a time in Europa" affects sailor's guide

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6561]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
using the sailor's guide while having the once upon a time talent gives you an extra 1 weapons skill

**Version**
v0.15.1.0

**Comment by M61Dev** [comment]
Should be fixed

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
