### ISSUE TITLE
Using a welding tool on someone with mollusc genes gives them max vigor instantly

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6564]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
hit someone using a gene splicer with mollusc genes with a welding tool

**Version**
windows 0.15.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/95c9cf385064ca6e5837adf25a18033446ac354e

**Comment by Xeavas** [comment]
[0.1500.2.0] Unable to replicate, welding too damage no longer applies vigor with mollusc genes active. 👍

**Comment by Rokvach** [comment]
Closing
