### ISSUE TITLE
Serious performance issues with oxygen detectors and WiFi components 

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#6565]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Prior to the most recent update (Fix patch and summer’s end greetings) the custom sub I had been working on had relatively decent performance, with it clocking in around 120+ fps in the editor tester.  However I loaded the submarine up a couple days ago in the tested and after loading in it was apparent something was wrong, I was only getting 7 fps.  So after troubleshooting the problem I believe I have found the source of the issue: the oxygen detectors hooked up to WIFI components for the status monitors.   In testing, after I removed all of my oxygen detectors and the wifi components they were wired to, i saw my performance increase to 170 fps+. 

**Steps To Reproduce**
In the attached ZIP file are two submarine files, one is my sub with the oxygen detectors and WIFI components as they were prior to the update and the other does not have the WIFI components and their attached oxygen detectors (I simply deleted them from the sub).  Load into the submarine with the oxygen detectors/wifi components in the submarine editor and then proceed to test the sub, it should be immediately apparent as soon as you load in that the performance of the sub is horrible to say the least.  You can then load into the one with the oxygen detectors/wifi components removed and see the immediate increase in performance 

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Version 0.14.9.0 on Windows, I also opted into the unstable public beta test and had the same issue

**Additional information**
System specs: Windows 10, AMD 2600x, Nvidia RTX 2060 Super, 16gb of ddr4 3133mhz ram, stored on a Corsair mp510 nvme ssd.
I tested other subs and noticed performance degradation in some but not all after the most recent update.  My go to comparison was the Vengeance mk3 (https://steamcommunity.com/sharedfiles/filedetails/?id=2121725686), it is a sub of similar size with far more items.  When testing this sub in the editor I noticed that their were far more fps drops than I expected with this submarine as I have used it a lot and noticed that the overall experience was far choppier than I would expect.  Though as a counter example, when I tested the olympus (https://steamcommunity.com/sharedfiles/filedetails/?id=2187915999), I noticed no performance difference.

[TEST SUBS.zip](https://github.com/Regalis11/Barotrauma/files/7108449/TEST.SUBS.zip)

**Comment by Leonidas-ai** [comment]
How does this compare with the latest update where performance is even worse? I didn't think to track fps as I didn't realize it would be impacted so much

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/7f3f6c800271e4dbdc682bb79cdd4e7e6c074a11.

compared to the original description of the issue, there is a definite huge improvement over the previous case, especially given I was running in debug which tends to have additional performance overheads.

but in my own performance profiling of the submarines originally provided and comparing them. My differences were the following:

around 60+ FPS for the submarine without the wifi/oxygen detectors linked. Top 5 functions did not have send signal and lowest was 1.77% (so send signal used no more than this).
Around 48~ FPS for the submarine with wifi/oxygen detectors linked. top 5 functions had Send Signal at over 7%-9% total CPU usage for me.

Note: the high usage line in question is: Barotrauma.Items.Components.Connection.SendSignal(Barotrauma.Items.Components.Signal)
