### ISSUE TITLE
status monitor overlap of shuttle and UI

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6567]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
shuttle and alerts overlap

![image](https://user-images.githubusercontent.com/5103517/132071847-0d595378-ce44-4889-90de-0c0b79d2db39.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.1

**Additional information**

**Comment by Regalis11** [comment]
Fixed in Regalis11/Barotrauma-development@0ab3b33

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
