### ISSUE TITLE
AI gunners don't shoot at visible hostile NPCs

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6568]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI gunners are primarily shooting at rooms, seemingly ignoring visible targets

**Steps To Reproduce**
pirate mission vs dugong

**Version**
0.15.1

**Additional information**

**Comment by itchyOwl** [comment]
IIRC they should also target visible characters, but it's true that they mainly target rooms.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@7e2d68c. They now should shoot the enemies if they can see them.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
