### ISSUE TITLE
Overlapping map markers make both markers text unreadable

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6570]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when multiple map markers are at the same angle, the text overlaps, resulting in NONE of the markers texts being readable

**Steps To Reproduce**
have 2 map markers in approximately the same direction, so that their text boxes overlap on the nav terminal

**Version**
0.15 

**Additional information**
it's been going on for multiple versions
maybe fix is to increase opaqness?

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
