### ISSUE TITLE
heal doesn't remove this affliction

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6573]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
heal command doesn't remove this affliction

![image](https://user-images.githubusercontent.com/5103517/132074159-290b87fa-66d8-42d1-b801-75aea4282253.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
This is the intended behavior of the "heal" command:

> heal [character name] [all]: Restore the specified character to full health. If the name parameter is omitted, the controlled character will be healed. By default only heals common afflictions such as physical damage and blood loss: use the \"all\" argument to heal everything, including poisonings/addictions/etc.
