### ISSUE TITLE
status monitor hull rounding issues

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6575]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
equal dimension hulls have different sizes on status monitor

Status monitor view:
![image](https://user-images.githubusercontent.com/5103517/132074597-0d0d2e24-4cb3-4f6d-adaf-b6ea19bed9d7.png)

the hulls in actuality are flush and have no such bumps.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.001

**Additional information**
this was on the rally sub
baroaaah

**Comment by 3e849f2e5c** [comment]
Note: this is probably a limitation with GUIComponent/RectTransform using Rectangle class which uses integers, only real way to fix it is to refactor the UI to use RectangleF

**Comment by Rokvach** [comment]
No issues, closing.
