### ISSUE TITLE
Destroyed door/hatch signal

### ISSUE THREAD

**Issue by PaladynMinak** [Regalis11/Barotrauma#6579]
Please, make door/hatch state_out sends 1 (or e.g. 2 for difference) if such door/hatch is destroyed, because it acts like if opened, or make a new socket for signal that would let know of a such state.

**Comment by Regalis11** [comment]
Thank you for the suggestion! The issue tracker is for bug reports though, feature requests should be posted in the [Discussions](https://github.com/Regalis11/Barotrauma/discussions).
