### ISSUE TITLE
spineling's gene projectile triggers evasive maneuvers talent

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6580]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
hitting a piece of hull with your spineling projectiles gives you the effect the evasive maneuvers talent gives you.

**Version**
0.15.1.0

**Comment by Regalis11** [comment]
@M61Dev addressed in https://github.com/Regalis11/Barotrauma-development/commit/7e83ae2f?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
