### ISSUE TITLE
equipping item has 1 frame aim delay?

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6582]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
there's like 1 frame or something when equipping an item before it goes to the position

https://user-images.githubusercontent.com/5103517/132103699-f0acb4ac-c70b-4e9f-a4f3-a9784e8acdfb.mp4

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.14.9

**Additional information**

**Comment by Tsunder** [comment]
here it is being shown on a vanilla item (stun baton)

https://user-images.githubusercontent.com/5103517/132105174-e30f7530-0417-4bb7-8f66-77d5eec38e0f.mp4

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
