### ISSUE TITLE
Buggy abandoned outpost (ID taken by ...)

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6586]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I got an error when entering an abandoned outpost, its generation is weird and it's missing some walls.
![image](https://user-images.githubusercontent.com/55637865/132111341-e930ae89-703f-49a4-894e-561c08ef9b75.png)

**Steps To Reproduce**
use save attached

**Version**
windows v0.15.1.0 unstable

**Additional information**
[stfu.zip](https://github.com/Regalis11/Barotrauma/files/7110700/stfu.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/435e40ed86d45b5692c3c32aaa022256263bc561

**Comment by Lithosagym** [comment]
Tested, confirmed to be fixed.

**Comment by Rokvach** [comment]
Closing.
