### ISSUE TITLE
Installed gene disappears if you try to stack same genetic materials in gene splicer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6596]
1. Install a 16% mudraptor genetic material
2. Drop another 16% mudraptor genetic material on top of the existing one in gene splicer
3. Notice that the gene disappears entirely

What I would expect to happen is that the new one gets installed

**Comment by Regalis11** [comment]
This actually swaps the items with each other, and since removing a material from the splicer destroys it, it appears to inexplicably disappear. I think we should disable swapping in this case.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/cac9d1638cb877e5e5d43443fbe05329c2770bfe

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
