### ISSUE TITLE
Double clicking or using a hotkey to place stabilozine in research station fills both input slots with stabilozine

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6597]
I think it should only place one stabilozine in if you double click or hotkey a stack

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6a3699b40bc1da58fca29f80044bf98867e5cf94

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
