### ISSUE TITLE
You can drop a genetic material directly to a limb it also doesn't display the genetic materials type

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6599]
I think this can be a bit misleading, even though it doesn't actually do anything if you try to place it to a limb
Also the type isn't shown here

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9b226da9-83d0-47c0-bb3d-69c6589720aa)

**Comment by Regalis11** [comment]
Looks like this was the case with all item, not just genetic materials. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6dc47066c5d3df922a8f33c27ad0ab2e16e1ed13

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
