### ISSUE TITLE
[Unstable 0.1500.1.0] Event "atwitsend" NPC Artie Dolittle is unauthorized

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6600]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you agree Artie Dolittle aboard your sub when event "atwitsend" triggers, but he's unauthorized to access any door(default properties) in your sub.
![bug4](https://user-images.githubusercontent.com/73634685/132210626-988563ea-d7e5-43ca-b297-81b74c6836f0.png)

**Version**
0.1500.1.0 Windows

**Comment by WrillWasTaken** [comment]
That's.... an armory door. Assistants can't access it.

**Comment by zhu-rengong** [comment]
> That's.... an armory door. Assistants can't access it.

Oh, what a coincidence, when I took the screenshot, I visited this armory door, but the other doors are still inaccessible for him.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
