### ISSUE TITLE
[Unstable 0.1500.1.0] Medical Doctor tries to treat the unharmed crew but donothing.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6602]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when i order the medical doctor to heal and rescue, he will tries to treat the unharmed crew, but donothing and just follows. I'm not sure if it is caused by hammerhead matriarch gene.
![bug2](https://user-images.githubusercontent.com/73634685/132237996-ba073505-ec2d-46c1-bef2-d730ac541b94.png)
![bug1_compress](https://user-images.githubusercontent.com/73634685/132238223-6135b458-4f4f-4611-bee9-9689b2a8a18a.gif)

**Version**
0.1500.1.0 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7cc8d83ba7d9a526cade1e76e3cc252ff4e1bb16

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
