### ISSUE TITLE
Campaign broken after destroyed submarine, ballast flora and death at a outpost.

### ISSUE THREAD

**Issue by L1NTHALO** [Regalis11/Barotrauma#6605]
**Description**
We arrived at the Staldon Linea military outpost and noticed that there was ballast flora in our ballast tank. That was the first time we encountered ballast tank and we had no idea what to do so we tried to destroy it and everyone except one of us died because of the toxic gas. After that our friend destroyed the submarine with grenades and other explosives and caused a nuclear meltdown. We did that because we thought that it wouldn't be saved but it got saved and we start with a destroyed submarine. We fixed the boat but now we cant start a mission because if I hit the start button to start the mission I and everyone else loses all his items and can't pick them up again. I also can't return to the server lobby, the only thing I can do is to go back to the Main Menu.

**Steps To Reproduce**
I will upload my save files so you won't have to reproduce the bug.

**Version**
Barotrauma v.0.14.9.0, Windows 10 20H2.

**Additional information**
We tried fixing the problem ourselves by deleting the server logs, giving the save files to a friend so that he can host the server, verifying the game files and unsubscribing from all workshop packages. Nothing worked. I will upload files that would maybe be useful for fixing the bug. I will also upload screenshots from error codes etc.
![20210906211728_1](https://user-images.githubusercontent.com/90216907/132257288-51c86cb6-3d2b-4ff5-92ce-130165c719aa.jpg)
![20210906204754_1](https://user-images.githubusercontent.com/90216907/132257304-10dc2861-9d4c-4fae-a3e9-882b73b616f5.jpg)

Here's the link to the save files & server logs: https://mega.nz/folder/jA43jIqD#DmyhetdWGk0vFnYgF37oDg

Sorry for my completely broken english.

**Comment by Regalis11** [comment]
Seems to be caused by the same issue as https://github.com/regalis11/barotrauma/issues/6586
