### ISSUE TITLE
Rendering Issue.

### ISSUE THREAD

**Issue by StealthMeister1** [Regalis11/Barotrauma#6606]
For some reason, whenever I try to go into the room for 079, the entire room blacks out and I can go to places where I normally can't go. It's like having noclip without being in noclip. If I walk forward, I can see the hallways above me and around me. Eventually I'll fall a short distance and still be able to run around. Eventually I had to enable noclip to get back to where I was.

I didn't take a screenshot, as I forgot to. I was also unable to talk to 079 so I ended up just teleporting to the gate to end the game as that is about how far I was when this happened.

If I can replicate it, I'll throw in a screenshot on here.

**Comment by Regalis11** [comment]
This issue tracker is for bug reports about Barotrauma, not SCP - Containment Breach.
