### ISSUE TITLE
After leaving the city, items stolen in the outpost will not be considered as cleanup target

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6608]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After leaving the city, items stolen in the outpost will not be considered as cleanup target, although stolen mark is disappeared, nobody want to clean them.

**Steps To Reproduce**
1. NEW GAME
2. Steal some items
3. Leave the city
4. Drop stolen items
5. order the crew to cleanup
6. crew do nothing

**Version**
Unstable 0.1500.1.0 Windows

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@f4783a4

**Comment by ekqvist** [comment]
I guess this hasn't been tested yet anyway but should keep in mind that there's a possibility that changes for Regalis11/Barotrauma-development#7268 might affect this. I'll have another look if there's still an issue after this.

**Comment by Rokvach** [comment]
The fix to the other issue seems to have broken this again, I dropped stolen items to the submarine and asked a bot to clean them up but they just ignore them.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2050db9e6afdf9e4df37beaa313d74b8c34a6031

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
