### ISSUE TITLE
[Unstable 0.1500.1.0] Commando and First Aid Training talents are incompatible with each other

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#6609]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the health of the security officer who has commando and firstaidtraining talents is lower than 50, and cause him bleeding, game will keeps popping up DebugConsole:
![bug8](https://user-images.githubusercontent.com/73634685/132312491-35af01d7-9f72-4aa9-ac4a-59ddac01aee8.gif)

**Steps To Reproduce**
1. give a crew commando and firstaidtraining talents
2. cause him bleeding and reduce his health to below 50
3. pop up console and show "Used data-reliant ability condition when data is incompatible! Expected ..., but received ..."

**Version**
Unstable 0.1500.1.0 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ea853d

**Comment by Xeavas** [comment]
[V0.1500.2.0] Unable to replicate, console doesnt throw errors using the provided replication steps. 👍 
![noconsoleerrorsectal](https://user-images.githubusercontent.com/72674994/133160642-d2eb3b92-df96-47cb-8c66-063180fddade.jpg)

**Comment by Rokvach** [comment]
Closing
