### ISSUE TITLE
Opening talents tab on freecam crashes the game

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6610]
- [no] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport (43).log](https://github.com/Regalis11/Barotrauma/files/7122632/crashreport.43.log)

**Steps To Reproduce**
open talents tab on freecam (in my case it happened in the sub builder's test mode i have to see if it happens in a normal mission too)

**Version**
windows v0.15.1.0 unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66885985f44b3a51ad0b7295e5cea17e9e6ac7c5

**Comment by Rokvach** [comment]
Tested, the talent tab is now disabled if you aren't controlling any character. Working correctly, closing.
