### ISSUE TITLE
unstable genetic material mix's debuff stays after removing the material

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6611]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Putting a mix of 2 genetic materials on usually gives you a debuff, when you take the mix out of your gene splicer the debuff stays forever and cannot be cured unless you use another genetic material (i *think*)
this isn't really annoying unless you're lacking gentic materials, but it doesn't seem right

seems like it doesn't happen with every debuff, it happaned to me with tunnel vision.

**Version**
Windows 0.15.1.0 Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aaa6e2a57a9739ec7febf52b2384dc72fb39b315

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
