### ISSUE TITLE
When researching or combining research station shows a message "No material inserted, insert genetic material."

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6615]
Branch: dev

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c71bfdd2-dd04-456c-8d03-f1f86459337d)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/09b9682aa88d2edb4499ece31d9abc84e75fa053

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
