### ISSUE TITLE
Genetic materials type isn't shown in status monitors item finder

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6619]
Seems to be quite common that the type isn't properly fetched on certain places

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/93f78ee5-e14c-43ae-a68d-319304344948)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c56ee1dfa3ce1f70aaa20a29f8cc205c33c337a7

**Comment by Rokvach** [comment]
I can't find anything related to the genetics with the item finder, tried placing a gene splicer to a locker and it doesn't show up, nor does any of the genetic materials.

**Comment by Rokvach** [comment]
Intentionally hidden currently, gene splicer not being visible was fixed same with all wearables. We will revisit this later on but for now this workaround is fine. Closing.
