### ISSUE TITLE
[Unstable v0.1500.2.0] Server crashed when everyone on the server died and the game was trying to enter lobby

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6621]
We were running a multiplayer campaign and once everyone on the server died the below error was thrown to the console and the server crashed

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/dfe0ca7f-8e6c-442f-a86f-b5710ecd6fbe)

We encountered a strange issue where the game didn't allow us to leave the level, we tested by first trying to enter the next level over and then traveling backwards to the outpost we left and nothing happened, I even tried to use the server lobby button and even clicking that didn't do anything, only when everyone died the round actually ended resulting in the crash. While this was happening players joining the server weren't able to spectate the round.

Testers were suspecting that it was caused because radiation caught up to us in the middle of the round, but it might of been caused by something else. 

```
Barotrauma Dedicated Server crash report (generated on 9.9.2021 23:40:48)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.1500.2.0 (UnstableWindows, branch dev, revision 12c1bd4373)
Language: English
Selected content packages: Vanilla 0.9
Level seed: The BucketArgiope Linea
Loaded submarine: Humpback (7DAB3F2AA829C0E59BD860D635BDE83F)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void End()
Stack trace: 
   at Barotrauma.SalvageMission.End() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\SalvageMission.cs:line 250
   at Barotrauma.GameSession.EndRound(String endMessage, List`1 traitorResults, TransitionType transitionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 678
   at Barotrauma.Networking.GameServer.EndGame(TransitionType transitionType) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 2570
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 520
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 385
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 58


Last debug messages:
   9.9.2021 23:40:48 - [9.9.2021 23:40:48]
  Saving banlist
   9.9.2021 23:40:48 - [9.9.2021 23:40:48]
  Ending the round...
   9.9.2021 23:40:48 - [9.9.2021 23:40:48]
  Ending round (no living players left)
   9.9.2021 23:40:48 - [9.9.2021 23:40:48]
  The respawn shuttle is leaving.
   9.9.2021 23:40:47 - [9.9.2021 23:40:47]
  Console command "explosion 9999 9999 99999 9999 9999 999" executed by LePiromano.
   9.9.2021 23:40:47 - [9.9.2021 23:40:47]
  Jade Harley has died (Cause of death: Internal damage)
   9.9.2021 23:40:46 - [9.9.2021 23:40:46]
  Minx: stinky
   9.9.2021 23:40:43 - [9.9.2021 23:40:43]
  Outer wall breached by Spineling
   9.9.2021 23:40:42 - [9.9.2021 23:40:42]
  Inner wall breached by Spineling
   9.9.2021 23:40:42 - [9.9.2021 23:40:42]
  Inner wall breached by Spineling
   9.9.2021 23:40:41 - [9.9.2021 23:40:41]
  Dbat: uh oh
   9.9.2021 23:40:40 - [9.9.2021 23:40:40]
  Console command "explosion 9999 9999 99999 9999 9999 999" executed by LePiromano.
   9.9.2021 23:40:40 - [9.9.2021 23:40:40]
  Minx has died (Cause of death: Internal damage)
   9.9.2021 23:40:38 - [9.9.2021 23:40:38]
  Ending the round...

```

**Comment by LePiromano** [comment]
[STINKY.zip](https://github.com/Regalis11/Barotrauma/files/7139701/STINKY.zip)
this is a MP save with the same thing happening, wait for a while (about ~15 minutes), try to enter the formation, it won't let you enter and you'll start getting radiation

**Comment by Regalis11** [comment]
I couldn't find a way to repro this, but added a null check that should prevent the crash (https://github.com/Regalis11/Barotrauma-development/commit/451cf35f774ddace38f23c4e012bac0d26c966a7).

Were you completely unable to access the map screen or did nothing happen when you tried to use it?

**Comment by Rokvach** [comment]
You were able to access the map screen but trying to start a new round by pressing the start button did nothing

**Comment by Rokvach** [comment]
The game doesn't crash anymore but not sure about the other issue of not being able to end a round, I think I will still just close this ticket as the crashing is fixed and open a new one if we still encounter the other issue. Closing.
