### ISSUE TITLE
buccaneer talent issues

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6622]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
First: Buccaneer talent unlocks the boarding axe, but it doesn't state it in its description

Second: Its description states it adds up to 250% to an atack, but all my tests end up in it just adding about 70% damage to an atack when it's fully charged.

**Version**
v0.15.2.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/48bf17a6a7b2e0682f95e958f09918b658e829a8

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
