### ISSUE TITLE
[Unstable 0.1500.2.0] Cargo scooter uses batteries from other items that contains a battery if those items are placed in the battery slot

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6624]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8508e651-ca69-4a85-bc7d-db2703a59105)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/38d2c763549c939bcc0bd018f8e639bdce57fa6a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
