### ISSUE TITLE
[Unstable V0.1500.2.0] Suitable treatments showing for hidden afflictions

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#6626]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The suitable treatments menu can show suitable treatments for hidden afflictions, but only when the part has a seperate and visible affliction. 

**Steps To Reproduce**
Get husk infection, then damage the torso. The health menu will show calyxanide as a suitable treatment.

**Version**
Unstable V0.1500.2.0 Windows

**Additional information**
Screenshots of this bug with psychosis, husk infection and opiate addiction:
![20210910154446_1](https://user-images.githubusercontent.com/86113712/132872307-d850c7c0-b371-49b6-af54-6d5f1e92b145.jpg)
![20210910154010_1](https://user-images.githubusercontent.com/86113712/132872353-0ea92fe3-67c0-46ca-9156-a393a610c62d.jpg)
![20210910154718_1](https://user-images.githubusercontent.com/86113712/132872518-29ffebe6-f549-46d0-a3e2-d1f0974b4d2e.jpg)

Technically you can now test for husk infections with a bullet.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/04aee451803e0d8c9d4d94ec567e2fcb108e6b1f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
