### ISSUE TITLE
Issues with outpost people's damage detection

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6629]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- Husking someone by biting them wont trigger them
- Shooting someone with 300 health with a handcannon tickles them and they don't aggro
- Stun grenades don't trigger guards allowing you to easily cuff them with their own handcuffs

**Version**
v0.15.2.0

**Additional information**
https://user-images.githubusercontent.com/55637865/132994224-90f2e444-c8b5-4d9c-96f6-83e892b69f65.mp4

**Comment by ekqvist** [comment]
There was a somewhat related issue reported earlier (#6558)

**Comment by itchyOwl** [comment]
Can't repro any of the issues in dev.

The husk issue was addressed in Regalis11/Barotrauma-development@abe31ee. And there's been a bunch of other related commits after that.

**Comment by Rokvach** [comment]
Closing.
