### ISSUE TITLE
[Unstable V0.1500.0.2] Vomiting when being afflicted with nausea gives maximal concussion effect

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6630]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Characters with the nausea affliction will receive a strength 100 concussion when vomiting

**Steps To Reproduce**
-Cover yourself in Nausea
-Wait for it to vomit
-Get concussion

**Version**
Unstable V0.1500.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/834c56287855588d7d63093f9cc25791e5b8047e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
