### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by DesertFoxPrime** [Regalis11/Barotrauma#6633]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
It keeps crashing every time i try to start the game

**Comment by Regalis11** [comment]
Please fill the issue report template before posting a report. I'm afraid there's not much we can do about this without more info - the crash report in particular would be helpful in this case.
