### ISSUE TITLE
Mudraptor beak mutation damage

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6634]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hitting the mudraptor beak that the mudraptor genes gives you will damage your torso, and it doesn't have that 50% natural resistance to everything so you take extra damage when it gets hit.

**Version**
v0.15.2.0

**Additional information**
my suggestion:
1 increase its size and resistances so you can use it as a helmet
2 remove its collision

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/02fdea7bc3a36b79a5a536da78c65fb88ef833fb

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
