### ISSUE TITLE
Endworm doesn't have enough sight to continuously atack prey

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6635]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Endworm can hear submarines just fine, but when it comes to living beings, divers can just swim away with no trouble, since the circling behaviour's radius is so large that the prey goes outside of it's sight range every time it atacks.

**Version**
v0.15.2.0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
