### ISSUE TITLE
buccaneer affects stuff other than melee weapons

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6637]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The buccaneer talent's affliction appears when you aim a harpoon gun, welding tool, plasma cutter, flamer, prototype steam cannon, and alien pistol, the power atack doesn't seem to actually affect the damage of any of these but it does show up

**Version**
v0.15.2.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/48bf17a6a7b2e0682f95e958f09918b658e829a8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
