### ISSUE TITLE
Cargo scooter spawns without a battery

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6642]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e81d3580-f6fb-4d63-b35e-18913deb31a8)

**Comment by Regalis11** [comment]
The cargo scooters shouldn't autospawn in containers in the first place, fixed in https://github.com/Regalis11/Barotrauma-development/commit/8abbe6254d14337ec75ac5603b40cd8f7a494e46

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
