### ISSUE TITLE
[Unstable] Assault reticle shows when stowed away on back

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#6643]
**Description**
Assault Rifle will show its reticle while holding the right mouse button while its in the toobelt slot

**Steps To Reproduce**
1. Store Assault Rifle in toolbelt slot
2. Aim by holding right mouse button

**Version :** Unstable [V0.1500.2.0]

**Additional information**
![baroARreticle](https://user-images.githubusercontent.com/72674994/133153611-1f0c9ffc-db17-4164-91eb-49ed1514c56a.jpg)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
