### ISSUE TITLE
[Unstable] Station O2 Generator doesn't have "Condition_Out" pin.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#6645]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The station version of the Oxygen Generator does not include a "Condition_Out" pin in it's connection panel like other repairable installations do.

**Version**
Unstable V0.1500.2.0

**Additional information**
unbelievable... no more gaming...

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/756a7583ea811eb3f61d610ec4fc99870a420d0a

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
