### ISSUE TITLE
[Suggestion] Speed up or slow down instruments based on afflictions

### ISSUE THREAD

**Issue by SydoxX** [Regalis11/Barotrauma#6648]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Instruments should be played faster or slower, depending on the drugs the player has taken.
Methamphetamine = Haste --> Play guitar faster.
Paralyzant = Paralysis --> Play guitar slower.

**Comment by Regalis11** [comment]
That's a fun idea! :) We only use this issue tracker for bug reports though, so I'll close the ticker.
