### ISSUE TITLE
Console Command for Setting Character's Selected Skill- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#665]
A command to set someone's skill level. In case if there had to be 2 skills of the same name due to modding skills are programmed to have own ID, after which they are being recognized. Having two skills of same ID crashes game. Characters in single player are being selected for editing skills after their order on the crew list in case of having the same name.

**Comment by NilanthAnimosus** [comment]
There shouldn't ever be skills of the same name for any character, the game would only use one anyways (likely of the first matching), so it may as well set the same one as it uses (also likely, the first matching)

giving skills ID's and such isn't necessary, though if you ask me they should be in the same order regardless of skill level.

The game should also just not have same-named crew members, and simply use another name on generation if an existing character is found with the same (Again, if you ask me, thats how it should be) and if crew-naming becomes a thing - to deny renaming crew to have identical names, even if they have to be given a number after not finding a name after X tries.

The ability to update character information post-spawn would be nice though, not just for skills, but teams and other information too.
