### ISSUE TITLE
[status-monitor] Electrical and item finder tabs doesn't display linked submarines

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6650]
Sub: https://steamcommunity.com/sharedfiles/filedetails/?id=2567584141

General status
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e332ae05-18ac-405e-932c-accbc31f60d6)

Electrical view
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9462b78f-d939-4695-8aa4-ab033c7b97e6)

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/63f47e27cce6a262da53766d9d928a57cf4fae62

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
