### ISSUE TITLE
[status-monitor] Report icons aren't shown in hulls at the Hull Condition tab

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6651]
You can report just fine just the icons aren't displayed in the hulls

But might be better to first decide if we want the hull condition in a separate tab

**Comment by Regalis11** [comment]
Merged the tabs in https://github.com/Regalis11/Barotrauma-development/commit/1f4999bc2b15704b99669b99f467c9f6fc45e0ec

**Comment by Rokvach** [comment]
No issues, closing.
