### ISSUE TITLE
Reactor PDA renders on top of the command wheel

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6652]
Command wheel is always rendered on top of any UI, so for consistency it should render on top here as well

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/589d72c2-d94e-49cb-8d8f-65a680b40839)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16075a3cd7b0051e117fd3149669b6ed50fcbba4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
