### ISSUE TITLE
Terminal Scroll Bar

### ISSUE THREAD

**Issue by FrankieEnc** [Regalis11/Barotrauma#6656]
I searched for this issue on the github and didn't find anything
ver. 0.14.9 or whatever.  ubuntu 20.04.

If you have way too much text, like say 10000 lines, the scroll bar jumps at such large rates that you miss a lot of text. Scrolling should be based on some line number and not by a percentage or whatever it's doing now.

**Comment by FrankieEnc** [comment]
Here's some video.

https://user-images.githubusercontent.com/22733784/133720563-17e93397-60a3-4ae6-b3af-4fded4d1bf74.mp4

**Comment by Rokvach** [comment]
Overall I think it would be better to adjust the scrollbar to work better with a lot of content, for example in fabricator or sub editor entity list its a bit of a struggle to target a certain part within the lists

One way would be to make scrolling smooth

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
