### ISSUE TITLE
Здраствуйте, я нашёл баг с выбором миссии. Устраните его побыстрее пожалуйста

### ISSUE THREAD

**Issue by matvejsalnikov** [Regalis11/Barotrauma#6657]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
![Снимок экрана (8)](https://user-images.githubusercontent.com/90891639/133735492-87152e46-ea6b-459b-89f9-26ad7099d1e5.png)
![Снимок экрана (9)](https://user-images.githubusercontent.com/90891639/133735495-9dda4e43-1a04-4e9d-8e97-23e40eac8995.png)
![Снимок экрана (10)](https://user-images.githubusercontent.com/90891639/133735497-35748255-1c08-4199-9767-a7a4cce7cb44.png)

**Comment by matvejsalnikov** [comment]
Windows X64 Здраствуйте при я не могу выбрать миссию хотя она доступна и задания выдаются нормально, миссия показвыается но я немогу ее выбрать

**Comment by Regalis11** [comment]
Addressed alongside https://github.com/Regalis11/Barotrauma/issues/6539
