### ISSUE TITLE
[Unstable 0.1500.3.0] Suitable treatments don't update if you gradually gain a affliction on the limb you have selected

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6661]
Repro steps:
1. Find some Antibiotic Glue
2. Open Health Interface and select the torso
3. Now use the Antibiotic Glue
4. Notice that the Organ Damage increases but the suitable treatments still shows up as None
5. Re-select the torso
6. Now suitable treatments shows correctly

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/35a02f88-d9a7-4a83-a1b3-36f91d9a60ba)

After re-selecting the torso
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8326ba2f-b3ee-421b-84a8-bcf3a7b8a52d)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c86f01fe94daf8429c9f56260646e4d2399ff714

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
