### ISSUE TITLE
[Unstable 0.1500.3.0] "Invalid stat type type "Coauthor" in CharacterTalent (coauthor)" gets thrown when you learn the Co-Author talent

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6662]
When you learn engineers Co-Author talent you will receive this console error

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/727aa5ff-f217-4136-9199-220e45dfa29a)

**Comment by M61Dev** [comment]
Fixed

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d18fd77, merged to dev now too

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
