### ISSUE TITLE
[Unstable 0.1500.3.0] Can't progress Electrician talent tree because there's a talent missing

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6663]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6c320fa8-30ca-458f-a192-5e65dbfd4c1e)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a5ef13da9669724787dff8e41a944886362978e3

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
