### ISSUE TITLE
[Unstable 0.1500.3.0] Clown honk explosion is maybe too dangerous 

### ISSUE THREAD

**Issue by WDebon** [Regalis11/Barotrauma#6664]
Steps to reproduce:
-Get talent "Inspiring Tunes"(Assistant talent) + The basic talents needed 
-Get bike horn
-Get clown suit(Any)
-Honk near anything that can explode with an outside interaction, specially explosions(Like O2 tanks or Railgun shells)

Usually it either dries out all of the O2 inside a tank or it just explodes them 

https://user-images.githubusercontent.com/38989015/133808001-9b83ae43-c934-43b0-ae8d-1a01f1387dcc.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/515f28c1221769e33e39b2213d1b99d4e391ba21

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
