### ISSUE TITLE
[Unstable 0.1500.3.0] Accordion XP not working

### ISSUE THREAD

**Issue by WDebon** [Regalis11/Barotrauma#6665]
Steps to reproduce:
-Get mechanics Accordion Talent + other talents needed to get there(I forgot the name)
-Get accordion

https://user-images.githubusercontent.com/38989015/133809097-a20e1be3-c860-484d-ba95-a14b09370859.mp4

**Comment by Regalis11** [comment]
Which talent do you mean? Afaik the mechanic doesn't have any talents relating to accordions or any other instruments.

**Comment by WDebon** [comment]
I see, i dont know where i got that from, sorry for the ticket
