### ISSUE TITLE
last 2 deconstructor slots don't show stacks

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6667]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/133836258-6c6f4226-0434-464c-844a-22d7293a7123.png)

**Version**
v0.15.3.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1d439e844a79d4ec2c8d7530d563bc1f07d82cd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
