### ISSUE TITLE
position out x and y scale is off by a factor of 100

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6668]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
position X seems to be in CM, while position Y seems to be in meters
would be nice if they were at the same units.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.150.3.00

**Additional information**
I would prefer if X output distance in meters

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ad3e4efdbc0c68453a2a208d40470b89f4dbfe0

**Comment by Lithosagym** [comment]
Tested, confirmed fixed.

**Comment by Rokvach** [comment]
Closing.
