### ISSUE TITLE
[unstable] status monitor 

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6669]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- [x] status monitor standalone is offset from center of screen (inconsistent with rest of the furniture/item UIs)
- [x] status monitor standalone window overlaps with the chatbox
- [x] status monitor menu buttons/alert buttons overlap with the submarine on large submarines
- [x] status monitor doesn't show wires (that are stored in containers)

![image](https://user-images.githubusercontent.com/5103517/133843027-5964416c-c802-4259-8908-9ba7e8887ac5.png)

![image](https://user-images.githubusercontent.com/5103517/133843832-ccdc40bc-b0ff-424f-ba15-bbd9b0908ed9.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.30.00

**Additional information**
not sure if 4 issues would have been better
idk if showing light/wiring components is ideal since those

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ab3b3351be377c16c98c92b9cea0289e7755ec2

**Comment by Lithosagym** [comment]
Tested, confirmed fixed.

**Comment by Rokvach** [comment]
Closing.
