### ISSUE TITLE
Player Can Edit Campaign's Map Sizes Before Creating Save File- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#667]
Very Small- 90% less structures.

Small- 50% less structures.

Moderate- Default.

Large- 100% more structures.

Huge- 300% more structures.

**Comment by NilanthAnimosus** [comment]
By less structures - is this ruins, or map length/height, or is this the lobby's map where you see cities and stations?

**Comment by rico6822** [comment]
Structures are cities and stations.

**Comment by Regalis11** [comment]
In the dev version the map generation can be customized, not just the size but also how many locations there are and how they are placed across the map.
