### ISSUE TITLE
[unstable] status monitor hulls astral ascend

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6671]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
clicking between linked view / unlinked view makes the hulls astral ascend

https://user-images.githubusercontent.com/5103517/133848239-f00cba7c-5142-49d4-aa98-94df6c799944.mp4

**Steps To Reproduce**
1. linked nav/status monitor
2. status monitor has "show side by side" checked, navigation terminal does NOT
3. switch between status monitor and navigation terminal

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
This is intentional: the status monitor interface is only shrunk down when there's other interfaces visible at the same time.

**Comment by Tsunder** [comment]
right but the hull outlines kind of... don't match the hull positions anymore. some of them get shifted up (and stay up)
