### ISSUE TITLE
depleted fuel cannot be crafted

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6672]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/133852061-8d3c27e5-87ca-435d-81e3-1c83963fddb6.png)

**Version**
v0.15.3.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8a91599

**Comment by Rokvach** [comment]
I'm unable to craft the item even when I have the recipes, it just shows disabled in the fabricator
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/828e1847-e256-4787-801e-191fa108f77f)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
