### ISSUE TITLE
You're able to self apply stacks of Saline/BloodPacks near instantly

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#6673]
**Description & **Steps To Reproduce****
You're able to self apply (entire stacks of) Saline/BloodPacks by holding RMB and LMB using legacy bindings

**Version**
v0.14.9.1 & v0.1500.3.0

**Comment by Regalis11** [comment]
I wouldn't consider this a bug: there's no cooldown/delay to using medical items, so I'd say this is the expected behavior.

**Comment by Rokvach** [comment]
I would still classify this as a bug, you can also do this with the default keybindings by using E + RMB and as E is only meant to be used for interactions with default binds it doesn't make sense that it has a hidden usage case like this. 

Also we have previously tried to avoid using entire stacks of items all at once so allowing it here isn't consistent elsewhere

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
