### ISSUE TITLE
Make it easier to spawn genetic materials

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6674]
Currently trying to spawn in genetic materials is a bit of a struggle as its hard to remember the long name they use and you can't use tab correction either, also remembering what the unprocesssed genetic materials are called is very difficult.

I think we should also display the processed genetic materials in the sub editor just to make it easier for modders to test their genes while still having the unprocessed ones hidden.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2fe493aaf647f9437e2b0f81593745d79cc9c8a3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
