### ISSUE TITLE
regex component false can send empty strings when set from editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6679]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the false output of the regex can send empty strings when set in the editor

**Steps To Reproduce**
1. set an expression and an input
2. output to a terminal
3. true = 1, false = (leave empty)
4. make the expression true, then false

**Version**
0.149.1

**Additional information**
once touched the false output field in test mode, it no longer sent empty strings

the reactor here is wired up to a regex with said parameters. it should send false (send nothing) once the reactor heats to 6000+ temperature

[testgong.zip](https://github.com/Regalis11/Barotrauma/files/7189370/testgong.zip)

**Comment by Tsunder** [comment]
video proof but
https://user-images.githubusercontent.com/5103517/133894637-c7d58ff3-44d1-42bd-82f1-d682bd1ad9a2.mp4

decompressing the sub file the false output appears to actually be

&#xD;

I have no idea what character this is.

**Comment by Regalis11** [comment]
That symbol seems to be a carriage return (\r). I'm not sure how it got set to that, and wasn't able to reproduce this: I tried erasing the default "0" with backspace, delete and by highlighting it first and then pressing backspace or delete, and in all cases the output got set to an empty string.

**Comment by Tsunder** [comment]
yeah i tried various methods and haven't been able to replicate it. posted it to some other code-familiar sub builders and they were likewise bemused and confused too.

for the record: I had accidentally copy-pasted an expression from regexr.com into the false output before moving it into the expression field.
