### ISSUE TITLE
Renegade Mode For Campaign- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#668]
While creating save file player can select to play as renegade, which is only gonna flip submarines and make levels by played from right to left. Towns can be visited normally with no credit or hiring changes.

**Comment by Regalis11** [comment]
I don't see the point of this tbh. Mirroring the sub and the level makes no difference to gameplay, the only thing it does is making the layout of the subs you've familiarized yourself with a little more confusing.

A renegade mode _might_ be worth considering at some point in the future after the campaign is much more fleshed out and the outposts changed to actual physical locations (see #23), but now that the campaign barely has any story or anything that explains who you're playing as and why, it wouldn't make any difference whether we call it a Coalition or Renegade vessel.
