### ISSUE TITLE
[Unstable 0.1500.3.0] You can place a Cargo Scooter inside a Toolbelt and a Crate

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6681]
Considering the amount of slots a Cargo Scooter has and the fact that you can't carry it in your inventory I don't think it makes sense to be able to place it in other containers. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/cea7cfec-e973-4338-be7b-f81e61ace3fa)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f2135c03863aa0fb244c4ef2e37f76f828b1b3a9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
