### ISSUE TITLE
[Unstable 0.1500.3.0] Boarding Axe makes a flesh sound when you hit walls with it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6682]
The sound is the same as if you were hitting a character with it

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62b96132988d65e16bb5967782beab8e83aa5d9c

**Comment by Rokvach** [comment]
It doesn't make any sound now when you hit things with it

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16a3b9618aaaf72d16dc5e5531108c9f4f912ca5

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
