### ISSUE TITLE
Regular expression square brackets

### ISSUE THREAD

**Issue by PaladynMinak** [Regalis11/Barotrauma#6684]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Square brackets in expression should check for single character in specific place, e.g.
[a][b][c]
should only match exact phrase "abc". Right now it seems only to check order of characters, but its behavior is somehow inconsistent.

**Steps To Reproduce**
Use terminal wired to RegEx, with expression set to something in square brackets, e.g. [e][x][p][r][e][s][s][i][o][n] or [a][b][c], or whatever and try some similar expressions like 'aabc', 'ababc' etc.

**Version**
v0.14.9.1 revision df0088ca33 Windows 10

**Additional information**
![image](https://user-images.githubusercontent.com/58741172/133898343-f4908c26-54d8-49c2-9aea-69bef5a60418.png)
![image](https://user-images.githubusercontent.com/58741172/133898536-a39acbbc-e763-45f4-8011-1a908abcfeb0.png)
![image](https://user-images.githubusercontent.com/58741172/133898479-c7cf60a4-4d50-468a-bc1d-2e614e1bbecf.png)
![image](https://user-images.githubusercontent.com/58741172/133898462-c974f959-a058-485e-8ef2-0df313b50427.png)

**Comment by Regalis11** [comment]
The regex component outputs "1" if it finds a matching string, and all of these examples do contain a matching string. If you want to check whether the input is identical to some string, you might want to use the signal check component instead.

**Comment by PaladynMinak** [comment]
From what I understand [] should check for specific signs in specific place. So e.g. "aabc" for "[a][b][c]" should be false, because second sign, "a" in "aabc" doesn't match "[b]", third sign, "b" doesn't match "[c]" and fourth sign, "c" doesn't match anything.

Lets say I want to check for expression abc, but also for ABC or Abc. I would type [Aa][Bb][Cc]. Also I've tried using [Aa]{1}[Bb]{1}[Cc]{1}, what also failed to accomplish desired effect.

I've literally learned about regular expression at https://regexone.com/
Please, see particularly https://regexone.com/lesson/matching_characters
Is it what it says incorrect?
