### ISSUE TITLE
RegEx sends output on game load

### ISSUE THREAD

**Issue by PaladynMinak** [Regalis11/Barotrauma#6685]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On game load regex sends output without receiving any signal, even without anything wired to it. It causes e.g. false output at terminal, if wired to one, for no reason.

**Steps To Reproduce**
Connect regex to terminal or memory, set its false output to any visible characters.

**Version**
v0.14.9.1 revision df0088ca33 Windows 10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0116bf026a4416ca47bce315fd11ca1ea81b22ee

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
