### ISSUE TITLE
Unstable - Intensity lowers too slowly, leading to uncomfortable audio not fitting the situation

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6686]
**Description**
Title

**Steps To Reproduce**
-do basic crawler swarm mission
-debugdraw, ctrl E, watch intensity
-fight and defeat the crawler swarm
-have everything repaired and drained
-keep an eye on intensity - it will stay up minutes after the combat, leading to intensity tracks playing during calm gameplay time, taking up most of the music time during a level

**Version**
Unstable

EDIT
-might be worth changing the intensity intervals for sounds instead of intensity it self

**Comment by Rokvach** [comment]
Tested, working correctly. Closing
