### ISSUE TITLE
Unstable - Players can set "Allow swapping" on submarine guns mid-round

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6688]
**Description**
I smell grief and confusion potential with this
![image](https://user-images.githubusercontent.com/59519434/133909585-36c48fad-0370-4c1f-8ee1-b6e830107c37.png)

**Steps To Reproduce**
-start campaign on orca
-grab a screwdriver and use it on front coilgun

**Version**
Unstable

**Additional information**
Could be the case for submarine weapons on more subs.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9ff4fae25ff44f14f20008cf36e4e7aa4c9b3d7

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
