### ISSUE TITLE
Unstable - Can't tinker a loader

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6689]
**Description**
![image](https://user-images.githubusercontent.com/59519434/133909726-349456c6-11b4-408b-b4c2-e6e44c010188.png)

**Steps To Reproduce**
-try to tinker a loader on Orca, same way you do it with other devices

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb1e1c3352ab1a23c00805c7bb5ec6b7b7e7433a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
