### ISSUE TITLE
Multiplayer-like Monster and Additional Cargo Settings For Campaign- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#669]
Just like in multiplayer sandbox or mission mode player can set, while creating save file monsters to enable/disable and more starting cargo, if he wants to.

**Comment by Regalis11** [comment]
Imo this would kind of defeat the purpose of the campaign. If one wants to play without monsters or spawn free extra cargo, that can be done in the sandbox mode or by using console commands in the campaign.
