### ISSUE TITLE
WASD

### ISSUE THREAD

**Issue by bijo17** [Regalis11/Barotrauma#6695]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by ekqvist** [comment]
Hi! Unfortunately, without any information about the issue, we cannot help with it. Please, consider submitting another ticket with the relevant (and requested) information if there's an issue we can help you with!
