### ISSUE TITLE
Harmless Hydrothermal Vents- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#670]
Monsters can be disabled in multiplayer, but what about hydrothermal vents? In case if game's source code makes it impossible to prevent them from generating on specific seeds could those vents not generate harmful smoke, when they are set in host's option menu to be disabled? This would help sometimes, when testing submarines.

**Comment by Regalis11** [comment]
In the dev version it's possible to select the difficulty of the level, and hydrothermal vents only appear in the more high-difficulty levels. So I'm not sure if we need a separate setting for this when the players can instead play a low-difficulty level with no major environmental hazards.
