### ISSUE TITLE
[Talents] Security Officers Navy Diver talent throws errors when you unlock it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6703]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8054d65f-fa27-4c53-8607-6967c9a9c66b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2c55f9e4ec9a0ffa6b84fac29fe4e54858b8b6a0

**Comment by Rokvach** [comment]
Tested, didn't receive a error, seems to be working correctly. Closing.
