### ISSUE TITLE
[Talents] Medics Alien Hoarder talent throws an error when unlocked

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6704]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/28622b91-60ba-485d-a67b-904ca177cdca)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f0d0f259eecceba52532837ef3bcd4729a50c9b

**Comment by Rokvach** [comment]
Tested, didn't receive a error, seems to be working correctly. Closing.
