### ISSUE TITLE
[Talents] Engineers Polymath talent throws a error

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6705]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6216daeb-3f02-4e1d-8528-2710a5b0da71)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ebb010af5090ae15848d454c5a2dac1bc696ad2

**Comment by Rokvach** [comment]
Tested, didn't receive a error, seems to be working correctly. Closing.
