### ISSUE TITLE
[Talents] Medics Double Duty talent throws an error

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6706]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/78936c29-8a87-45e8-b983-d1bef1e6c1d6)

Also started to receive these each time I tried to close the console 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6ce47725-8f4f-4b4f-9f4d-a25f61cf96d6)

If its not related to the above mentioned talent, these are the medic talents I have selected right now
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a0283d21-76f3-4d44-83ee-1d3ca537c70a)

**Comment by Regalis11** [comment]
@M61Dev fixed in https://github.com/Regalis11/Barotrauma-development/commit/7112cf9? Should this be moved to QA?

**Comment by M61Dev** [comment]
Yeah I forgot to move the ticket, it should be fixed now

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
