### ISSUE TITLE
[Genetics] If you take one of the genes off from the advanced gene splicer you lose both of the genes (bug or feature?)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6713]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/146f9c4e-bd0c-4fb7-bdf8-ad2b551b2eb7)

**Comment by Regalis11** [comment]
Not a bug: this happened because the 1st genetic material was 100% refined, preventing the 2nd one from doing anything.
