### ISSUE TITLE
Pressing Esc does nothing if you are hovering over an inventory slot

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6715]
Place your cursor above a slot and press Esc, notice that nothing happens
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/52dbf658-92e4-417b-bd43-6a990c7ed65e)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9231cdb5b253bf371e5ce6d7b5a77d6b355607c1
