### ISSUE TITLE
[Unstable v0.1500.3.0] Kastrull explosive junction boxes

### ISSUE THREAD

**Issue by Varenvel** [Regalis11/Barotrauma#6717]
- [yes ] I have searched the issue tracker to check if the issue has already been reported. (atleast could not find one relating to ship it happened)

**Description**
So short story short Kestrull is properly my most played ship and glad some other bugs were ironed out , but this one keeps happening to me , even on latest unstable version , and that is explosive junction boxes , i played other ships but this one seams to almost exclusively happen when playing kestrull
(its definitely not bot not repairing stuff fast enough as in 4 cases it happened we were doing "quick missions" ignoring everything including wildlife and do transport missions , going as fast as captain could go)

https://steamcommunity.com/sharedfiles/filedetails/?id=2608973821 (i had screenshot of fire but it happened few months ago and since then i reinstalled windows , i never uploaded it to steam i think , was also new to the game and was sure i did something wrong)

- older clip from same bug , https://youtu.be/AGz6-N2qcQY (but managed to find clip just today) (some mods here)

**Steps To Reproduce**
-no upgrade's on submarine , this seams close to essential as 4ish times i seen this happen (in older versions and one today) seams to only happen on fresh saves where you have fully un-upgraded submarine or close to
-Play game normally , do missions , dock at stations ,and once mission finishes  sometimes (20% of time or 40%) all junction boxes on ship will be destroyed/close to destroyed , and 10% of time there will be fire 
-This happens on both singleplayer and multiplayer , had this bug happen twice in SP , and twice in MP
-station does not seam to be essential as long ago when it happened it also happened on non-station level transition in campaign
-I had it happen 2 times with mods and 2 times vanilla (recent one is vanilla)

**Version**
Unstable v0.1500.3.0 , windows PC

**Additional information**
-All time i had it happened only happened on kestrull , and always when bot was managing the reactor , 3 times it was uranium fuel rod , 4th time i not remember if it was uranium or thorium rod
-who is a bit stupid as first time i had fire it nearly blew up entire sub as bots ignore orders when on station and i had to manually enstingish fire myself , died , reloaded the save and this time fire was not there , just damaged junction boxes(as game saved when we docked)
- i only have 8 gigabites of ram , not sure if "low memory of host/SP is factor"
(corrected some typos)

added clip , edited extra info about mods

**Comment by Varenvel** [comment]
Found the clip , its from few months ago when we played moded play , but mods seam not affect this bug to apear , 2 times it apeared on moded and 2 unmoded.

had to upload to youtube due 10mb restriction https://youtu.be/AGz6-N2qcQY

**Comment by Varenvel** [comment]
I done some more testing and there is something definitly wrong with fuseboxes(idk if just kastrull or all ships) , especialy in experimental(latest octrober combat revision , i played the ship to check if its not a fluke and im not entirely sure whats wrong (ill provide video and save game)

Game is unmoded and uncheated
Ship has some upgreades , i spend really a lot money on reactor , fuseboxes , yet they still randomly get huge amount of damage , or burst into flames both between missions and "even by changing direction of ship just by tinybit) and this seams to be very random , this seams to happen a lot even by small change of course (who from 80 hours of playing game , mostly as captain) was never a case

ship has 2-3 reactor upgreades
power efficiency upgreades on engine and a lot modules
4-6 upgreades on fuseboxes

Latest clip: https://youtu.be/lu73hbA9wPM
savegame: https://drive.google.com/file/d/1ouctCCAqOCAHgtkV4vTGVvBBP37BDgWr/view?usp=sharing

(please devs atleast acknowlage this as its been 2 weeks i made post and it does not even has tags attached)

**Comment by Regalis11** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/d1fc12946e443269e422b51909c8079e4cbc24b9

**Comment by HeatedWafflez** [comment]
This is also an issue on the Typhon 2.

**Comment by Rokvach** [comment]
I haven't seen this happening since the fix was introduced to the Unstable, also this hasn't caused any new issue so I think this is working correctly. Closing.
