### ISSUE TITLE
[Unstable] Using Return command on hostages crashes game

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#6720]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When playing the outpost rescue abandoned outpost mission variant in mission mode, using the Return command on the hostages caused the server to shut down. I was able to reproduce the error multiple times. 

**Steps To Reproduce**
-In mission mode, select the abandoned outpost mission type and play the outpost rescue variant.
-Once you reach the hostages, issue the Return command to one of them and the server should crash. 

**Version**
Unstable v0.1500.3.0 , windows PC

**Additional information**
I was playing alone with no bot crewmates. I do not know if that has any impact, and it most likely doesn't, but I thought I should mention it.

![image](https://user-images.githubusercontent.com/91236493/134453199-28e6f020-15bf-4d36-822b-b3d016e63289.png)

**Comment by ekqvist** [comment]
Fixed the crash issue in Regalis11/Barotrauma-development@7b0bcc5. Also, fixed the target sub for return orders not being set correctly when targeting friendly NPCs (e.g. hostages) in Regalis11/Barotrauma-development@6e91082.

There still seems to be some kind of an issue with the order when targeting friendly NPCs, as they abandon Go To sub-objectives without saying anything. I will investigate that issue further.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
