### ISSUE TITLE
Assault rifle bullets don't appear from barrel position

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6721]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c6afc4ea-53f2-4373-947f-f9e385bfad69)

**Comment by Regalis11** [comment]
Probably related to https://github.com/Regalis11/Barotrauma/issues/6553, I suspect the bullets do spawn at the correct position but the tracer particles don't

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/85f5747915fc8622f5d92fb755c88104c5af4e5d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
