### ISSUE TITLE
Fabricator doesn't display if the item required needs to be a spent one

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6722]
When crafting Depleted Fuel it shows as if it requires a full Fuel Rod even though the item has to be a spent one, only way to know this is to read the description of the Depleted Fuel. I think this information needs to be displayed in the Fabricator by showing that the item required is spent. 

Displaying the empty bar under the item
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5e01be77-dbda-4eb4-8a3c-0e8cc7ebbae6)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2452a4344a1e5eaa3acf8fa9d3f84b41aa9da228

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
