### ISSUE TITLE
Auto-Injector Headset still uses the normal Headset sprite when you wear it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6723]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c838ccef-29cf-41fd-8f49-9305c8df8173)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/445245117881c92711192ecee17aa7d699bbc7d3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
