### ISSUE TITLE
funny spin when holding a syringe

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6726]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Holding a syringe and holding right click causes the arm to start spinning infinitely (in my case it was a syringe of anabolic steroids probably works with other syringes too).

**Version**
Unstable v0.15.4.0 windows

**Comment by LePiromano** [comment]
it seems like syringes are not the only ones affected by this so in this comment i'm going to write a list of what else is affected by it:
medals

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9cb860372a01e84856c60a6e3064c0e4575bc794

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
