### ISSUE TITLE
Events - Would it be bad to spawn their creatures/items server-side only?

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#673]
As of right now (in 0.8.1.12 master branch), the clients and server perform syncing by both creating in level generation the events, which in turn create the creatures/items and other relevant event information before they are considered synced (And thus cannot be changed through any code means without causing everybody to desync in various forms if they were modified).

I've often let hosts do a form of unconventional modding where they can edit the XML files server-side in small ways, usually to modify stats like changing creature health or stun/damage values, if not adding different results to status effects and such. - typically harmless changes as long as they are not client side required ones (Such as changing potassium explosions and not removing the item).

It would be nice if the creatures were created after the syncing was done, in the form of spawning them. I'm sure I could simply turn off all the spawns completely and do my own event system for spawning or such but I figure it never hurts to ask to let the server handle the creation of creatures in a level instead of just their respawning.

**Comment by Regalis11** [comment]
Implemented in the dev branch
