### ISSUE TITLE
Theory/Error checking suggestion for excessive desync

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#674]
Vanilla has this odd issue mid-game where trying to join an in-progress game causes an excessive desync disconnect.

And it had me thinking - What if the event system was in some cases writing (For over the duration of a game) creating more events than could be sent out per update for protracted periods? (more than 64/update/second, each character writes an event, and various status effects and other content does too).

The game doesn't exactly check for this, but in modded content packs and large complicated submarines with high player counts - its not the most far fetched thing possible I think for their to begin to be a "Backlog" of events (Given it doesn't even take 64 to max it out even).

It may be once the events are synced up and it changes to the normal mode - the events that would be processed is just too much for this backlog (Though i don't think this is the issue, its more towards excessive desync disconnections for players in a vanilla server - they tend to be common for BTE servers)? at least for on connect excessive desyncs. But I've not been playing in verbose to see if there was any errors from this nor examining a server when it starts occurring.

**Comment by Regalis11** [comment]
Actually it's not 64 per second, it's 64 per message, and the server writes and send the messages every 150 ms. So that's about 427 events per second, which sounds unlikely, although it's still a possibility and there should be some checks in place to make sure that doesn't happen (or that it's logged at least).

**Comment by NilanthAnimosus** [comment]
I know its 64 per message, I did not mean it the way I seem to have written it haha, but its still a possibility as I meant it on a per-update basis.

Juan changed it (Due to numerous flaws and problems) so characters queue a network update every update instead of on stat changes (Often characters would have problems in general the other way around) but they do count as an event, so having some 20-30 characters is actually halfway to the max that could be output per networking update.

**Comment by Regalis11** [comment]
Actually the character status updates do not use the entity event system, they're just included in the position data sent every frame. They're also written to the messages last, and only if there's space, so too many network events should just cause the status updates to be delayed until there's less events to send.

**Comment by SandPoot** [comment]
Can this be fixed, because whenever this happens, players that already were in the game get the desync.

**Comment by Regalis11** [comment]
I think this can be closed: desync is still a problem, but this particular issue (creating events at a higher rate than what can be sent) should be fixed by 27917ee.
