### ISSUE TITLE
ID tags not correct for Kastrull and Typhon2

### ISSUE THREAD

**Issue by Skywardhigh** [Regalis11/Barotrauma#6741]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I checked for a previous issue and found [0.1002.0] ID Cards tag issues between switching Submarines #3083 mentioning this and it being fixed, however I was recently playing a new save and noticed after buying the Kastrull I couldn't access the Toxins Cabinet or Security Locker as the captain, when checking in the sub editor I noticed they had the old ID tags 'idcaptain', 'idsecurity' and 'idmedic', the spawnpoint ID card tags were also the old ones. I went through all the other subs and noticed the Typhon2 has the same old tags and old spawnpoint ID card tags.

**Steps To Reproduce**
Go into the sub editor, look at either the Kastrull or Typhon2 Security Locker/Toxins Cabinet and it shows the old IDs. Alternatively start a new game with say the Dugong then buy the Kastrull and try opening the locker/cabinet.

**Version**
v0.14.9.1 (Windows)

**Additional information**
Hopefully I'm not being dumb and this has been fixed and just my game being weird, I haven't played for a while and only recently came back.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3fcc95e0d8f8b3bd29bbcf103bf08453e8db9775

**Comment by Lithosagym** [comment]
Tested, Kastrull and Typhon2 have correct IDs for spawnpoints and containers, fixed.

**Comment by Rokvach** [comment]
Closing.
