### ISSUE TITLE
[AI] Bots do not finish off incapacitated Human Husks when fighting in person

### ISSUE THREAD

**Issue by Cusuno** [Regalis11/Barotrauma#6745]
- I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will immediately start ignoring Human Husks once they become incapacitated, not realizing that Human Husks possess health regeneration just like their natural spawning counterparts and can recover from the incapacitated state on their own. This results in an endless loop in which the bots will re-attempt to incapacitate the Human Husk again as soon as the Human Husk has regenerated enough health to stand up again.

This behaviour does not occur when the bot in question is manning a submarine weapon, as they fire at their target until it is completely dead.

**Steps To Reproduce**
- Spawn a Human Husk and a decently armed Bot
- Let them fight
- The bot should now ignore the Human Husk once it is incapacitated until it stands up again

**Version**
Windows - v.0.14.9.1 (Also tested in unstable v0.1500.4.0)

**Video footage**
https://streamable.com/5vmpcx

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce5fbf1b04b413c5d0f4584a6d6c3e429c21d8fd

**Comment by Rokvach** [comment]
This works fine if the bot is using guns, but if multiple bots tries to melee the unconscious human husk they will just end up killing each other as they can't reach the unconscious enemy on the floor

Easy way to test is to spawn a human husk in a outpost and let the guards try and handle it

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/55787216-b5f7-49ef-acb8-70d5f9150803)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/02b25492-2eaa-44d3-a3ae-be2ed7ff54de)

**Comment by Cusuno** [comment]
> This works fine if the bot is using guns, but if multiple bots tries to melee the unconscious human husk they will just end up killing each other as they can't reach the unconscious enemy on the floor

Might be related to this bug: https://github.com/Regalis11/Barotrauma/issues/6747#issue-1007160205

**Comment by Rokvach** [comment]
Closing this ticket as we have a separate one for the issue I listed. Closing.
