### ISSUE TITLE
There is a bug report about the displacement sensor in the barotrauma

### ISSUE THREAD

**Issue by 2937015922** [Regalis11/Barotrauma#6748]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The displacement detector cannot detect me continuously. I set its false output to 0; the output is set to 1. At this time, the displacement detector sometimes outputs 0 and sometimes outputs 1

**Steps To Reproduce**
1. Set the output of the displacement sensor to 1 and set the false output to 0 and then connect to the terminal. 2. Enter the detection range of the sensor so that the sensor can detect you. 3. View the sensor output. At this time you will see sometimes output 1 and sometimes output 0.

**Version**
Barotrama v0.14.9.1(ReleaseWindows,branch release,revision df0088ca33)           system：(Windows10).

**Additional information**

**Comment by Regalis11** [comment]
This is normal: the _motion_ detector only detects you when you're moving.
