### ISSUE TITLE
UI overlap when Tinker button is visible

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6763]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f1cba1fb-1fa1-411b-bcf3-306e402602d1)

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ca166de50425007e9aa32c88ee3b1e9a4a4c1d5d, although I didn't test this with resolutions larger than 1080p

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
