### ISSUE TITLE
[Unstable] Handheld Status/Electrical monitor uis show when picked up but not equipped 

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#6767]
**Description**
Handheld status and electrical monitor uis will show up when you pick them up, without it being equipped in your hand. To replicate, pick up handheld status/electrical monitors on the floor

**Version**
V0.1500.4.0

**Additional information**
![handheldpick](https://user-images.githubusercontent.com/72674994/134956047-e3f2a1da-76b7-490c-8f45-eb56d77012af.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd06320d3d6814deac1bb91b90b5358c53f0c502

**Comment by Xeavas** [comment]
[v0.1500.5.0] Unable to replicate 👍

**Comment by Rokvach** [comment]
Closing.
