### ISSUE TITLE
Single Player A.I. Controlled Crew Won't Follow My Orders Once I Translate Them to Polish- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#677]
And yes I am using Notepad ++.  What I found funny about all of this is that they threat my "Follow", "Wait", "Fix Leaks" and "Dismissed" orders as "Dismissed" most likely, because they don't have accurate objective in the corner of the xml file. Like they are told to directly operate reactor or railgun.

**Comment by NilanthAnimosus** [comment]
They are hard coded in the AIObjectiveManager to "follow" "wait" "fixleaks" and "fix leaks".

Its possible the translated orders may work for things like operating the reactor - but not the above, at least until those string cases are not hard coded.

**Comment by Regalis11** [comment]
Fixed in the dev branch
