### ISSUE TITLE
Tileable lightcomponent

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#6773]
Support for tiling the light components' additive sprite (see LightSource.DrawSprite).

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/a447c864b8e8a7e95929be2f95194f5eb829d851

Use <light> XML element in Structures that has the same syntax as <LightComponent> XML element has in Items minus couple like Range because it makes no sense in this case

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
