### ISSUE TITLE
Sabotage starts to repair the device if you control a different characters in multiplayer after you have been chosen as a traitor

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6774]
Repro steps:
1. Start a traitor mission in multiplayer
2. Equip a wrench and wait until you get chosed as a traitor
3. Once you are a traitor sabotage a item so see that its working fine
4. Control a bot and try to sabotage
5. Notice that sabotaging now instead repairs the device

This also seems to affect button scales if you are playing with the Tinker skill unlocked, the sabotage button gets larger.

**Comment by Rokvach** [comment]
Looks like the issue isn't as simple as that, so I somehow managed to switch the buttons around. Trying to find how I did it.

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
