### ISSUE TITLE
Severe ping spikes in Multiplayer

### ISSUE THREAD

**Issue by EvilBadger34** [Regalis11/Barotrauma#6775]
While Playing with friends they had a solid 60 ping, but every 2 seconds it would jump to 10x the ping (600-800) and jolt them through walls or down a ladder. I wasn't even playing long distance from them, they were in the next room.

It hindered their abilities during emergencies and they were always jerking back and freezing every 2-5 seconds.

**Comment by Regalis11** [comment]
I'm afraid this might be impossible for us to diagnose without some more info.

If this happens again, something that might give some more clues about what caused this is enabling the performance statistics by entering "showperf" in the debug console that opens with F3. If this is some type of a performance issue, a screenshot of the view might help us pinpoint what's causing the performance drops. Another thing would be to enter the console command "verboselogging", which makes the game output more debug information in the console. If there's any red/orange texts or warnings in the debug info, a screenshot of those would be very helpful.

Thank you and sorry for not being able to offer any more help for this for the time being. :/
