### ISSUE TITLE
You can run while ragdolled in multiplayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6779]
Repro steps:
1. Start a multiplayer round
2. Run like you would usually
3. Tap spacebar (don't hold)
4. Notice that your character is ragdolled whilst still running forward

Video:
https://www.youtube.com/watch?v=wOb8TALxqJ0

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e1e63110fb2f920a95f9651c10b236ad1a3362e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
