### ISSUE TITLE
More Texts in "Texts" xml file- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#678]
It's lacking lines like "Active sonar" or "Press [Crew Orders] for crew orders".

**Comment by Regalis11** [comment]
Duplicate of #80

**Comment by rico6822** [comment]
Another example:

English "Reward: 500 credits" should be in Polish "Nagroda: 500 kredytów" not "Nagroda: 500 kredyty".

I can only translate one "Credits" to "Kredyty", because same translation is sharing 2 different spots requiring different translations.

**Comment by NilanthAnimosus** [comment]
You may want to add more flaws you find with translation to issue #80 as this is a closed duplicate, so they can be worked on with the main issue.
