### ISSUE TITLE
[Alien ruins]  Ruin Scanner actually uses E to pick it up instead of Left Mouse that is shown in the controls

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6781]
Picking it up should however be Left Mouse

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/491b4d26-2e0d-44c8-ab76-963bd9d828f1)

**Comment by ekqvist** [comment]
Should be fixed in c1cd169

**Comment by Rokvach** [comment]
If you switch to legacy controls it should show [E] instead of [Left mouse] other than that its working correctly.

**Comment by ekqvist** [comment]
Fixed the issue of the original Select keybind being displayed in the HUD text when switching the Select keybind mid-game in Regalis11/Barotrauma-development@c2d93b0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
