### ISSUE TITLE
oxygen detector for status monitor doesn't work across subs/shuttles

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6783]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An oxygen detector going into wifi in a docked shuttle doesn't give o2 data on an appropriately wired status monitor on the docked submarine.

**Steps To Reproduce**
1. oxygen detector -> wifi on shuttle, wifi -> oxygen_data_in on status monitor on docked sub/main sub
2. check status monitor

**Version**
0.14.9

**Additional information**
Probably also water detectors.

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. Tested by adding an oxygen detector and a wifi component into Kastrull's drone, passing the output into Kastrull's status monitor and enabling the "require oxygen detectors" setting on the monitor. Seems to work with no issues:
![image](https://user-images.githubusercontent.com/14351070/135850168-0b5ffdf6-662f-4b28-af11-b4aadb66c63b.png)

**Comment by Tsunder** [comment]
I am experiencing this phenomena on one sub, but not another.

The sub I was experiencing this on is the Mercurial

It appears to have several things going on, likely caused by the same bug:
![image](https://user-images.githubusercontent.com/5103517/136244806-f2dd78f3-f1fa-46a0-b24b-6163a0a8b720.png)

1. the airlock below the command room has o2 information. It does not have an o2 detector, but the wifi component that feeds the status monitor is in that hull.
2. the reactor room where the mechanic is has an o2 detector+ wifi, but is not giving information
3. the shuttle's center room has no information
4. there is a second status monitor in the upper part of the sub, it has a wifi feeding it, and only has o2 information for the room below (where its wifi component is)
![image](https://user-images.githubusercontent.com/5103517/136245672-8f32ff45-ce05-4686-b766-9e6605abee0e.png)

Deleting the wifi + detector from the Engine room in the editor gave the main sub's command room status monitor expected o2 detector display (except for the now missing engine room o2 detector). 

Yet somehow neither of the other 2 status monitors have expected o2 information - the shuttle only sees itself, and the upper monitor is missing reactor room + shuttle + additional detectors added for testing.

Removing the Engine Room o2+wifi with a wrench in test mode did NOT yield the same results - no additional o2 data was revealed, only the engine room o2 was lost.

Re-adding a wifi +detector in the Engine room after deleting the old one did not result in buggy o2 display in command (the other 2 monitors had no change in display)

Expected status monitor (as seen from command, after remoing and re-adding wifi+detector in engine room)
![image](https://user-images.githubusercontent.com/5103517/136246871-34e056ba-cf0b-4765-a843-dc7710655905.png)

**Comment by Tsunder** [comment]
attached a zip archive containing the baseline submarine + version with engine o2+wifi deleted and re-added.

[Mercurial -o2 engine replace.zip](https://github.com/Regalis11/Barotrauma/files/7295768/Mercurial.-o2.engine.replace.zip)

**Comment by Tsunder** [comment]
Side note: This is happening on stable 0.14.9 as well (all 3 status monitors) (though i believe it may have been happening in 0.13 even or before!

![image](https://user-images.githubusercontent.com/5103517/136248518-902c774b-d289-4984-b57e-f135eaa9df13.png)

and removing the Engine Room wifi+o2 detector "fixed" it for command status monitor as well

**Comment by Regalis11** [comment]
Thank you for the extra info, I think I was able to fix the issue now (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/63cd8e7fee050d6837ef1682b6a39f378a4c4016).

This happened because the game cuts off long signal chains after the signal has passed through 10 steps and continues them during the next frame, but there was a bug in the wifi component logic that counted each wifi component that receives the signal as "one step", causing it to always cut it off on some of the recipients if there's more than 10 recipients in the sub. There was also another issue that caused the "source" of the signal to be the wifi component itself when those cut off signals resumed during the next frame, even though the source should've been the oxygen detector.
