### ISSUE TITLE
Attach rope component to the position of the barrel

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#6784]
Atm rope components attach to the origin of the item, which looks a bit weird on the harpoon gun

**Comment by Regalis11** [comment]
Looks like it did attach to the barrel, the barrel position was just configured wrong. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b9eaeffce77a6867851dc84f502a42e1af6ed68e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
