### ISSUE TITLE
SMG doesn't do any damage after the first bullet nor does the magazine get spent so you can infinitely fire it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6785]
Tested with a SMG spawned inside the Humpback armory in single player

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/af0e0f4ba93cfdf842e71480a27d5cd19500488b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
