### ISSUE TITLE
Medics Overtreat Husk Infection

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#6786]
- [X] I have searched the issue tracker to check if the issue has already been reported.

Medic Bots, when lacking antibiotics or calxyizide, just pump the patient full of morphine/fentanyl until they OD and die.

**Steps To Reproduce**

Get rid of all meds except opiates, reach critical husk infection, and set medic bot to heal/rescue

**Version**

Steam Stable

**Additional information**

This MAY be caused by the lacerations given by the husks, and the medic just doesn't stop trying to treat them even once it's gone. Can't be sure though.

**Comment by Krzeszny** [comment]
Medic bots are terrible in general :/

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/98be27b19993cf2d8dcb368a326aaefde9a43586

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
