### ISSUE TITLE
Game Crashes During Ragdoll Validation

### ISSUE THREAD

**Issue by Unknown025** [Regalis11/Barotrauma#6789]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game has crashed while "attempting to check the validity of a potentially removed ragdoll." The game stopped responding as seen here:
![Game image](https://media.discordapp.net/attachments/566304603818164235/893400557950218250/unknown.png)

**Steps To Reproduce**
Not sure if it's possible to easily reproduce, this has happened only twice as far as I've seen.

**Version**
0.14.9.1 (Running on Windows 10 x64 10.0.19043.0)

**Additional information**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7265218/crashreport.2.log)

**Comment by Regalis11** [comment]
Seems to have happened as a result of https://github.com/Regalis11/Barotrauma/issues/6627, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ccd0f33afeea78ae942b9ae9f6b97c2124e0861

**Comment by Unknown025** [comment]
Glad to hear, thanks!
