### ISSUE TITLE
Items with concussion resistance display the affliction's description

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6798]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/135669010-e2aff9e9-f62a-4e44-8bda-aac337d96d1b.png)

**Version**
v0.15.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3db5919dfbd2c6286e252d50a93f6455de81bd8a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
