### ISSUE TITLE
Recommended Crew Experience Issue- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#680]
When I translate to Polish language recommended crew experience I will still have "intermediate" and other variants displayed in English, but when I translate them and try to create submarine using it. It will be in polish language, but everyone can see it even without a mod.

Example:
When I translate "Beginner" to "Początkująca" submarines with "Beginner" will still be beginner and everyone sees it, but I can create submarines with "Początkująca" translation and no mod will be need to see this.

**Comment by Regalis11** [comment]
I renamed issue #80 as "translation support" - I think we could keep translation related issues there.
