### ISSUE TITLE
Can't "aim" with boarding axe

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6800]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can't hold the boarding axe before atacking, making it impossible to use the "power atack" with it.

**Version**
v0.15.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d40e7bad65097151d62476b4a630fcfa4ecaf4a

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
