### ISSUE TITLE
Unstable - Harpoon causes crash

### ISSUE THREAD

**Issue by hnappinn** [Regalis11/Barotrauma#6804]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you pick up a harpoon immediately after the shot, then the game crashes

**Steps To Reproduce**
Fire the harpoon gun. And immediately pick up the harpoon

**Version**
![Screenshot_24](https://user-images.githubusercontent.com/59388392/135718293-ce767cbd-5f45-495e-96a6-d3015f786ddf.png)

**Additional information**
[crashreport (74).log](https://github.com/Regalis11/Barotrauma/files/7271527/crashreport.74.log)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6797
