### ISSUE TITLE
[0.14.9.1] Character skills reset in multiplayer

### ISSUE THREAD

**Issue by napolean250** [Regalis11/Barotrauma#6809]
- I have searched the issue tracker to check if the issue has already been reported

**Description**
Under certain circumstances in multiplayer, a player will have their skills reset to their starting values, and occasionally will have their role changed as well.

**Steps To Reproduce**
The first instance of this happening was when two of our crew members died in a fire in the docking area between the submarine and the outpost. One respawned with their stats reset, and the other respawned as an electrical engineer with her stats reset (Originally a medic, we had another medic on board and suspect this is why her role was changed along with her stat reset)

The second instance happened a month or so later in a different campaign when one of our members left early for the night when the rest of us kept playing. We purchased and swapped submarines later in the night (from the Humpback to the Berilia), proceeded to fail those missions as the sub couldn't fit, swapped back to the humpback at the next outpost, and continued from there. We switched between the Berilia and Humpback then back once more since that point. When our crewmate logged on to play with us a day or two later, his stats were reset. There were no duplicates of his role on board (Electrical Engineer), so we suspect that is why his profession was not changed (apologies for the lengthy details, I felt it was important to include as much detail as possible)

**Version**
Version 0.14.9.1, all of us are running windows.

**Additional information**
We are able to change the stats back using the XML file for the character data, but find it rather inconvenient

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e1d2bfc02e2cfe86d1456b6a60083d61646431a

**Comment by Krzeszny** [comment]
I hope it's fixed, I'm also getting it now.

**Comment by Krzeszny** [comment]
@Regalis11 does the campaign have to be reset in order to fix it? I'm getting it each time I join a specific campaign in unstable even though it's already v0.15.6.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
