### ISSUE TITLE
Reactor Fuel_Out pin outputs heating power not durability

### ISSUE THREAD

**Issue by jdoxley** [Regalis11/Barotrauma#6812]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reactor Fuel_Out pin outputs heating power not durability, if this is not a bug then there should be a pin added to the reactor to output fuel rod durability.

**Steps To Reproduce**
Wire a display up to the fuel out pin
It should display the fuel rods durability but it displays the heating power instead.

**Version**
V0.14.9.1 Windows 10

**Additional information**

**Comment by Regalis11** [comment]
Added a "fuel_percentage_left" output in https://github.com/Regalis11/Barotrauma-development/commit/ae6827838e0864280c9df0f34d25f8eb0bed75db

**Comment by Lithosagym** [comment]
Tested, fuel_out pin displays heating power and fuel_percentage_left correctly displays fuel rod percentage, confirmed working.

**Comment by Rokvach** [comment]
Closing.
