### ISSUE TITLE
Сoncussion balance

### ISSUE THREAD

**Issue by hnappinn** [Regalis11/Barotrauma#6814]
### What's wrong with the concussion?
Concussion happens quite rarely, requires a lot of damage in one hit. The grenade should cause concussion, but does not cause because of minstrength.

### How do you propose to fix it?

- `minstrength="10"` reduce.

- `probability="0.5"` preferably reduce.

- Or you can just make a new StatusEffect for explosion damage.

### What will it change?
A crowbar, grenade or something like that can cause contusion.

Now the concussion looks like this:
`<StatusEffect type="OnDamaged" target="This"> `
      `<RequiredAffliction identifier="internaldamage,blunttrauma,bitewounds,explosiondamage" minstrength="10"/>`
     ` <Affliction identifier="concussion" strength="10" probability="0.5"/>`
`</StatusEffect>`

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/023f05c43fc905c11e34ed6597607237034fd80d

**Comment by Rokvach** [comment]
No issues, closing.
