### ISSUE TITLE
[0.14.9.1] Relay component draws all available power

### ISSUE THREAD

**Issue by atik1n** [Regalis11/Barotrauma#6824]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Relay component draws all available power instead of needed power.
We have this config with consume values as displayed on image:
![image](https://user-images.githubusercontent.com/14612180/135780316-8d29c4e1-d9df-41c5-9f78-351fd4ba092c.png)
If there's no relays, junction boxes will draw exact that power, what system needs, because they are connected to another "main" box and they will not fire up.

But. If there is relay between main and secondary relays, actual load on them will be 500kW, because relay draws from `power_in` and sends 500kW to the `power_out`. That will break and fire all junction boxes on image without actual overload from reactor.

Is relay actually must draw all power and transmit it away? Maybe it must work exactly as junction boxes `power` node?

**Steps To Reproduce**
Connect reactor -> junction box -> multiple relays -> corresponding junction boxes -> power consumers

**Version**
v0.14.9.1 (ReleaseWindows, branch release, revision df0099ca33)

**Additional information**
Junction box actually just connects everything connected to the `power` node and maybe that's the reason.
Maybe related issue: #6471

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
