### ISSUE TITLE
[Unstable] Fractal Guardian gets stuck in ALIEN_MAINTENANCEPASSAGES (and others)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6826]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fractal Guardian will get stuck in tight passages, most notably on ALIEN_MAINTENANCEPASSAGES room

Guardian collision box needs to be reduced

![image](https://user-images.githubusercontent.com/73229309/135847947-50d7dceb-5f58-4569-b0a3-567e11d44b9b.png)

_Watcher stuck in artifact room:_
![image](https://user-images.githubusercontent.com/73229309/135848041-8fae2692-96d0-4175-b1b5-967a5022791b.png)

**Comment by itchyOwl** [comment]
Could you @Rokvach test if this still happens? The guardians shouldn't go into those passages, as they are too tight. And they shouldn't spawn in that room either.

**Comment by Rokvach** [comment]
Tested, I wasn't able to lure the guardians to the tight passages nor did I find any of them inside modules where they don't fit. I think this is working correctly. Closing.
