### ISSUE TITLE
[Unstable] Alien trinkets can stack but not Alien Curio/Ornament

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6827]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alien trinkets can stack but not Alien Curio/Ornament

![image](https://user-images.githubusercontent.com/73229309/135848689-7132fef8-97b7-4900-89d6-311887deb799.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/00687db9

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
