### ISSUE TITLE
[Unstable] Gravity sphere STATE_OUT doesn't work 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6828]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Gravity sphere STATE_OUT doesn't work 

**Steps To Reproduce**
1. Wire a gravity sphere STATE_OUT to a text display
2. Nothing is displayed

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
