### ISSUE TITLE
Captain's Pipe isn't aligned with mouth when you smoke it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6834]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fa85f2d8-3cb9-4733-99bc-468c1c411178)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/88afc9753d6dc3b50651d0a6df26bda062e24123
