### ISSUE TITLE
[Character overhaul] PUCS and Slip Suit are missing dropped sprites

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6835]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9c78dbc8-cef4-4f06-800b-5cf954736c7c)

**Comment by NamAnhLe** [comment]
Fixed in [0de50ab]

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
