### ISSUE TITLE
[Talents] When you equip a Rapid Fissile Accelerator to your toolbelt slot the weapon isn't shown in your back but instead front of your character

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6844]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1e61578c-be9c-45b4-8091-c4f76b1b963b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/726f64d5cc6a457ecbcf59aa0e6816550a057e21
