### ISSUE TITLE
Unstable - Outpost guards don't react to being poisoned with paralysis

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#6849]
**Description**
You can inflict paralysis on outpost dwellers and guards, wait a bit, then loot them. You can also transfer their loot directly into station's deconstructor and fabricator and launder the goods.

**Steps To Reproduce**
-poison outpost dwellers with paralysis and watch their reactions

**Version**
Unstable

**Additional information**
It might be worth giving outpost doctors some anaparalysant, because they try to heal the poisoned people, they just don't have the means. This might apply to other poisons as well.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
