### ISSUE TITLE
[Unstable] Husks can spawn inside alien ruins, consistently kill guardians

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6850]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Husks can spawn inside alien ruins
In some rooms where the guardian cannot navigate, the husk will kill the guardian thanks to its regeneration

Often occurs in **ALIEN_MAINTENANCEPASSAGES**

![image](https://user-images.githubusercontent.com/73229309/136272519-a39bddba-cd2e-4a1b-be34-7186578129bc.png)

**Comment by itchyOwl** [comment]
Should be fixed now. Guardians shouldn't spawn there anymore and they should be much stronger against husks. Not all the adjustments made it to the current unstable, but there will be another this week.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
