### ISSUE TITLE
AI repeadely attempts to run through ballast flora gases 

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#6854]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The AI crew will repeatedly attempt to path through rooms filled with ballast flora gas, even after initially running away from it after being harmed by the gases. Combined with the medic bots going a bit overkill on treatment this chews through opiates very quickly.

**Steps To Reproduce**
Infect a room with ballast flora until it covers the walls, and make sure an npc crew (e.g. a emchanic) has a job in said room (such as the broken pump that's infected.) Attack the flora until it spews gases everywhere.

**Version**
Steam Stable
**Additional information**
I've only seen mechanics do this, but I expect all NPC crew have this issue.

**Comment by ekqvist** [comment]
Adjusted bot behavior around ballast flora in Regalis11/Barotrauma-development@0ebf75e:
- Priority of some objectives now drops to 0 when the target's been claimed by ballast flora
- Items claimed by ballast flora aren't valid targets for some objectives anymore

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
