### ISSUE TITLE
[UI] Issues with UI of Sonar Monitor and Navigation terminal

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#6856]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is some issues that i found regarding sonar monitors and nav. terminals.

(All mentioned bellow was tested in 1920x1080 and 2560x1440 screen resolutions, both in fullscreen and borderless modes)

1. Sonar ring of a sonar monitor is much smaller (almost the same as handheld sonar's UI) than similar ring of a navigation terminal despite that sonar terminal is dedicated to sonar scanning and has much more free space compared to nav. terminal.
2. Navigation terminal's sonar ring has a black semi-transparent rectangle that darkens background but for some reason it's shifted to the right side of a ring. Also sonar terminal doesn't have one

**Steps To Reproduce**
Observe how UI of mentioned terminals look, be it in-game or in submarine editor.

**Version**
Report was written in unstable 0.1500.5.0 but mentioned issues were a thing even before "Uncharted Depths" update.

**Additional information**
Here is some screenshots that were taken to demonstrate how mentioned issues look (2560x1440)

1. 1.Nav. terminal's UI with linked status monitor (looks the same with and without): semi-transparent rectangle doesn't cover all control panels and also misaligned to sonar ring.
![image](https://user-images.githubusercontent.com/62324831/136524486-3a403628-3bca-4b80-8c00-9a06c1857219.png)

2. Sonar terminal's UI: Very small sonar ring (similar to handheld sonar) and no semi-transparent rectangle to darken background of a sonar ring. (also control panel's placement is rather not aesthetically pleasing if there is a link to status monitor)
![image](https://user-images.githubusercontent.com/62324831/136524971-cabd5a4f-8f83-4be7-9509-c93acb215f30.png)

**Comment by Singularia** [comment]
Already saw an improvement of the sonar monitor's UI in 0.1500.6.0, but also noticed that sonar ring now slightly overlaps a control panel (zoom, active/passive switch etc.).

Resolution is the same as before, 2560x1440
![image](https://user-images.githubusercontent.com/62324831/136735112-150827d8-610c-447e-93f4-632678e477fa.png)

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
