### ISSUE TITLE
Copy, paste, and various text editor feature request for submarine editor and console.

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#686]
I'd love to see windows text editor features enabled for Barotrauma, like Ctrl +C and Ctrl + V, arrow left and right to navigate text, Ctrl left and right to jump forward and backward text groups, and all the Page up, down, home, end, etc.

**Comment by NilanthAnimosus** [comment]
This may be my daftest question yet but does linux actually have a clipboard to copy into? I recall clipboard features (such as copying) were actually compiled only into the windows version.

I assume it has some kind of equivilant, but it was a curiosity I Recall seeing in the code someday (And not even remembering where anymore - probably sub editor or entities or such).

**Comment by Momiro** [comment]
Linux does have a clipboard, and on some interfaces a clipboard viewer.

**Comment by Regalis11** [comment]
Added in the dev branch
