### ISSUE TITLE
[Unstable] You can remotely refuel reactors with PDA

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#6868]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The reactor PDA allows to refuel the reactor remotely by dragging fuel in its inventory (but not the other way around)

**Steps To Reproduce**
1. Grab a fuel rod
2. Open reactor PDA
3. Drag a fuel rod from your inventory into reactor

![image](https://user-images.githubusercontent.com/73229309/136597812-c797cc62-356c-43cf-8821-252283deb50f.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dfd72b2abb48aa35b6485bbc10697154ff0c1413
