### ISSUE TITLE
[unstable?] Ballast flora doesn't grow back if cut in the middle

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6878]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you cut ballast flora not on the root but somewhere else, it doesn't grow back that cut part but it keeps growing without connection to the root.

It should grow back the cut part from the root.

**Steps To Reproduce**
- Have somewhat long ballast flora and an incendium grenade:
- Throw an incendium grenade at ballast flora away from the root, somewhere in the middle
The middle part is cut, the root exists, the rest still exists and keeps growing without connection to the root.

In the instance we tested this, an incendium grenade blew up in the ballast tank destroying everything BUT the root.

**Version**
Tested on unstable 0.15.6.0 but I believe it exists in stable, too.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/tree/feature/ballastflora-improvements

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
