### ISSUE TITLE
[unstable] Player becomes a second captain with other classes chosen and unoccupied

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6880]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the save where my character resets each time I join the server, I had a medic chosen as first priority and mechanic as second priority. I spawned as a second captain, even though there were no medics and no mechanics. 

I created a new character, we docked and undocked. I became a second captain again. I left the server and joined the lobby immediately. In the lobby my name was red like a medic while I was still a captain (presumably because medic was my first priority).

**Steps To Reproduce**
1. Be unlucky
2. Presumably have a corrupted save file

**Version**
v0.15.6.0

**Additional information**
Logs:
https://drive.google.com/file/d/1-qzW1V4BSJ3KMoLX117ch9JSx7zIJUEE/view?usp=sharing

Save but after I kept becoming a second captain:
https://drive.google.com/file/d/1-rf_JFxkPMTDEBBBQRuo2lIK0KpyhDS_/view?usp=sharing
Player data, same as above:
https://drive.google.com/file/d/1-ttQ_7V1ZYJPgxYEPAuOED-_ov1w_002/view?usp=sharing

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
