### ISSUE TITLE
I can't select some certain missions

### ISSUE THREAD

**Issue by Shadowguadrian** [Regalis11/Barotrauma#6882]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I try and check the box for an example an wreck salvage in automatically un check the box. 

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Unstable version 

**Additional information**

**Comment by Regalis11** [comment]
No known steps to repro, closing
