### ISSUE TITLE
Mission with hostages has been buged. I've kill all bandits and make hotages free, but mission steel not completed. They don't want go with me to submarine.

### ISSUE THREAD

**Issue by Yappikey** [Regalis11/Barotrauma#6883]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report!

The hostage missions require you to take the hostages to the submarine; killing the bandits and freeing them isn't enough to complete the mission. You can also order the hostages to follow you (the same way you'd order your crewmembers) - did you try to do that, and did it fail somehow?

**Comment by Regalis11** [comment]
Seems to have been addressed in https://github.com/Regalis11/Barotrauma/issues/6975
