### ISSUE TITLE
[Unstable] Better-than-normal quality fuel rods deconstruct into nothing

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6884]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Applies to:
- Fuel rods with quality better than normal (**tested on Excellent Fulgurium and Good Thorium fuel rods**)

Does not apply to:
- Fuel rods of normal quality (tested on normal Uranium and Thorium fuel rods)
- Empty fuel rods of any quality (tested on Excellent Fulgurium empty fuel rod)
- Tools of any quality (tested on Good quality welder)

**Steps To Reproduce**
Deconstruct a beter-than-normal quality fuel rod

**Version**
v0.15.6.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
