### ISSUE TITLE
[Talents] When you pickup a Reactor PDA from the ground it automatically opens up the UI even though the item isn't equipped

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6889]
Trying to equip/unequip the item doesn't close the UI either, you need to right click in order to close the UI.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a6238f65b6c03fd5740c60c32af1fcfa634093c7
