### ISSUE TITLE
Vent in small room receives disproportionally large amount of oxygen

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6895]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Somehow a small room within my sub is receiving a disproportionally large amount of generated oxygen.

The smallest room on my sub is the medical bay. I'd expect the room to receive `131072/(3*289792+188416+315392+131072)=0.0871341048=8.7%` of all oxygen. With the generated amount of 400 on the generator that's less than 35. Since 7 is needed to support a human that would support at most 6 humans. Yet somehow the room gets enough oxygen to support 22 characters, which would correspond to 157 units: 

![(medical professional conference)](https://user-images.githubusercontent.com/50582661/136860590-9089f8f7-d404-4323-8acd-db26fdf0ae58.png)
(*medical professional conference*)

This results in the problem that other rooms get disproportionally little O2. For instance, only 4 characters can stay in the fabrication section even though this room is larger.

**Steps To Reproduce**
See this sub file: 
[Crescent.zip](https://github.com/Regalis11/Barotrauma/files/7325544/Crescent.zip)

The O2 generator only runs for some time if the O2 level in the room gets below 70%, so you may have to wait a short bit. 

I suspect the problem has something to do with the way in which connected hulls for a vent are calculated,  although in game O2 does not seem to spread between these hulls. 

https://github.com/Regalis11/Barotrauma/blob/c8943ef9c446dd12d637406a8f4abf396e789193/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/OxygenGenerator.cs#L87

**Version**
Unstable v0.1500.6.0

**Comment by Regalis11** [comment]
This seems to happen because the game calculates the total volume of the hulls connected to the hull the vent only once when the round starts. In this case, the ducts are open at the start of the round, causing it to add up the volumes of all the adjacent rooms to the medbay's hull volume.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c3ff88f85c16970ea8df8754f2ec7d174dea1be8.

**Comment by Rokvach** [comment]
Tested, I haven't spotted any oxygen issues, seems to be working correctly. Closing.
