### ISSUE TITLE
[Unstable] Camera stops moving when trying to drag items from inventory while mission notification present

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#6897]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While there is a mission notification on screen, I have found that the camera stops moving when trying to drag items out of your inventory, IE dragging and dropping a crate from your hands onto a shelf. This will bring the camera downwards while bringing your mouse to your hotbar, and upon dragging the item, the camera will be locked down below. The camera will unfreeze upon letting go of the item. 

**Steps To Reproduce**
For me, this happened in a multiplayer server, but I am unsure if it can be reproduced in singleplayer. Simply accept a mission, so you have the mission pop up on the bottom of your screen, then attempt to drop any item from your inventory onto the floor. You should find that the camera gets locked from rising back up

**Version**
This bug happened on windows, on the latest version of the unstable branch. (I am not currently on my computer that has barotrauma installed, and so I do not remember the exact current version number.)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by StruggleDuck** [comment]
A similar bug is present in the new Factions/Endgame testing build. Having notifications on screen causes the camera to lock up, although I am not 100% sure of the cause.
