### ISSUE TITLE
Implement a tag / parameter / value for items that denies fabrication/deconstruction of the item

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#690]
This is for starter items primarily, but would be nice if its a property that could be set via XMLs and/or a server, and is to stop them being used as an ingredient or as a deconstruct-able item.

In a nutshell though as to why, starter items are given free every round, yet are typically made of fairly valuable materials (a security uniform alone is 5 polycarbonate or so). for a multiplayer game simply going through the beginning items for materials can give quite a bit each mission which has a fairly high enough value to make it a tactic - which I feel shouldn't be in there while inventories are not saved in multiplayer.

It could also be used at least for items that have no deconstruction value for now, to allow it to be specified to not deconstruct them at all (And to simply ignore the item in the slot). as well as perhaps the various mission cargoes for none-traitors as a possibility.

**Comment by Regalis11** [comment]
Fixed in c85cf63
