### ISSUE TITLE
[Unstable] Suffocating in typhon 2 after waiting in room long enough

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#6901]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the typhon 2, while sitting in the crew quarters (image of location provided), after a certain amount of time, you will start suffocation. Happened to my friend while he was afk, after a few minutes, captain noticed oxygen in there was almost at 0, and he had suffocated.
![image](https://user-images.githubusercontent.com/92034548/136966852-0a491b71-0f08-4586-b770-92174a97b31c.png)

**Steps To Reproduce**
enter the crew quarters on the typhon 2, and close the door. Then just wait, and you should eventually suffocate.

**Version**
Latest unstable build

Note: this happened on a multiplayer server, unsure if that had anything to do with it.

**Comment by Rokvach** [comment]
Tested, the oxygen stayed at 100 no matter how long I was in the room, seems to be working correctly. Closing.
