### ISSUE TITLE
Directional sonar for stealthy gameplay

### ISSUE THREAD

**Issue by Waagher** [Regalis11/Barotrauma#691]
This may be a tall order, but it would be great to be able to launch singular controlled sonar pings in a specific direction as opposed to alerting everything around you in 360° to your presence. The reasoning behind submitting this issue is that currently the only choice you usually get when encountering monsters is fight or flight. Despite the fact that the game technically allows the possibility to get past undetected, piloting in passive sonar mode usually just means that both you and the creatures detect each other at much closer distances before engaging in combat with little to no chance of avoiding it at all. I have also experimented with creating subs that can sail completely silently, but that just makes your passive sonar go completely dark, due to there being no sound to get visual data from.

**Comment by Momiro** [comment]
I'd love to see some kind of module that can aim or auto rotate the sonar pulse, with a toggle to change the mode, and one more slider, to control the strength of the frequency.

**Comment by Regalis11** [comment]
Added in cd44544e
