### ISSUE TITLE
Guardian pods starts to spin when you destroy them in Multiplayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6915]
I think this same happens with Thalamus organs too

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d1e855d3-02be-40e7-a742-74b6d109a650)

**Comment by PokkeTigrex** [comment]
Out of my current testing, the best way to replicate this is to go to each and every guardian pod and destroy it through any means, how the spinning occurs seems to be inconsistent, but it doesn't seem to be tied to methods of destruction. At some point, you will find one that starts to rotate clockwise. Interesting thing to note is that when spawning guardian pods in through console, it seems like the ones spawned will either rotate similar to the reported bug or just stand still as it should be.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, working correctly. Closing.
