### ISSUE TITLE
Custom Gaps for Doors and Hatches- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#692]
Sometimes gaps by autohull command are glitched and giving in submarine editor an option to make custom gaps make things easier.

This is what I wish to be added:

*Option to unlink gaps from doors and hatches.

*Blue gaps are becoming red gaps upon linkink with doors or hatches.

*You cannot link 2 gaps to same door or hatch.

*Custom gaps don't let water and oxygen go only 1 way instead of both.

**Comment by Regalis11** [comment]
Gaps on doors and hatches are already editable and it's also possible to add custom ones and link them. Making gaps linked to a closed door red and restricting the links to 1 gap per door/hatch are both good ideas, and I guess unlinking would be useful too in case you accidentally link a door to a wrong gap, but I don't understand the last point. You mean custom gaps can cause water to only go in one direction now? Is there an easy way to reproduce that, or could you post a screenshot of a setup where that happens?

**Comment by NilanthAnimosus** [comment]
You already have the option to create your own gaps, autohull only places gaps generated from hulls, not doors and such I believe.

one of the categories contains manually place-able gaps.

Red/Blue gaps are when the door is opened/closed.

**Comment by rico6822** [comment]
I mean Regalis, when I was making my own aegir's version gaps would let water go only 1 way, while I was debugging submarine. I couldn't fix this. I was making a playable version of playable submarine.
