### ISSUE TITLE
Can't end the round when the host is dead and there's no-one else with permissions

### ISSUE THREAD

**Issue by paleEferit** [Regalis11/Barotrauma#6921]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Multiplayer campaign, mode in which only host can choose the cource. Outpost clearing mission (with sabotage of reactor). Being a host, got my character killed. Other players finished mission successfully (notification appeared). Team could not undock, since host's character was dead and host didn't have a button for choosing cource at the top of the screen 

**Steps To Reproduce**
1. Start multiplayer server in campaign mode with at leash two player
2. Take outpost clearing mission by docking to abandoned outpost
3. Let the host player get their character killed
4. Get the mission objective done
5. Let the host try to choose the cource

**Version**
v0.14.9.1 Windows 10

**Additional information**
There should be some obvious work-around for this case, if host can't choose cource for gameplay-specific reasons. Getting whole team stuck like that breaks the game

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/7a78192a6ad64d711b9b1c43da62955ba78764ad

I killed a host and had respawns off in an outpost level, the player without permissions for campaign was unable to select a destination while the host/player with permissions couldn't select the location to go to (or respawn).

players with no permissions were able to dock to an outpost. but you cannot undock without a destination (Map also appears but cannot select a destination when you hit undock). so presumably an issue between destinations without an outpost as well.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2dc922b34327c96aeaa1191ae550ba3cf157c37f

> Fixed inability to manage the campaign if there's no-one with permissions alive. Previously we allowed anyone to manage the campaign if there's no-one with permissions present in the server, but that's not enough, because the players with permissions can't end the round if they're dead.

**Comment by Rokvach** [comment]
Tested, I was able to select a location, mission and start a round while host was dead. Working correctly, closing.
