### ISSUE TITLE
Two monitors trouble on linux.

### ISSUE THREAD

**Issue by FOCCms** [Regalis11/Barotrauma#6926]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have two monitors and linux. Then i run the game it's gonna randomly destroy my screen

**Steps To Reproduce**
step 1. take two monitors
step 2. setup linux mint
step 3. install and run the game

**Version**
0.14.9.0

**Comment by Regalis11** [comment]
Sorry for the late reply! What do you mean by destroying the screen? Do you run the game in windowed, fullscreen or borderless windowed and does it affect the issue your having?

**Comment by Regalis11** [comment]
No known steps to repro, closing
