### ISSUE TITLE
Becoming a random class(?) in co-op even if prioritized classes aren't full

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6932]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you choose specific classes that aren't even overoccupied and still become an assistant etc. It happened to 2 players at once on a 12-player server.

**Steps To Reproduce**
I have a suspicion that it happens when the player has less than 3 classes prioritized and there are many other players on the server (choose 1 or 2 classes).

- When it happened in unstable (0.15.7.0) today, I had only 2 priorities chosen (medic, mechanic).

- #6880 also happened when I had the same classes prioritized (medic, mechanic). They were the 2 leftmost priorities.

- It happened in 0.14.9.1 at least once and I had 1 class prioritized: There was a captain, medic and mechanic. I had medic prioritized and there was another player spectating. We became second and third mechanics.

**Version**
At least from 0.14 up to 0.15

**Additional information**
This was with Medic>Mechanic chosen:
![Barotrauma_HsL5KmeQQK](https://user-images.githubusercontent.com/10529134/137600008-47ab0493-f7b9-44e6-812b-d5e25926792b.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Krzeszny** [comment]
Not working correctly: #11999
