### ISSUE TITLE
[SUB EDITOR] Light textures don't rotate with lamps in editor but do rotate in-game

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#6937]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In submarine editor light texture will not rotate with lamps themselves, but in the actual game (normal game or test mode) work as intended.
While this doesn't cause problems in-game, it makes it harder to precisely adjust/position lamps with custom rotation angles.

**Steps To Reproduce**
In sub editor rotate any lamp or emergency light

**Version**
Unstable 0.1500.8.0, but was an issue at least since rotation was introduced (additionally tested on 0.10.4.0)

**Additional information**
Screenshot from subeditor with example of this issue
![image](https://user-images.githubusercontent.com/62324831/137604900-2521c267-649b-4508-90db-744e28f7af7b.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ea345286951991b922c51ce03cdd140f2633706

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
