### ISSUE TITLE
[Unstable 0.1500.8.0] XP spam issues if you have a spectator present when you try to dock in order to complete a round in campaign

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6939]
Repro  steps:

1. Setup two clients and host a dedicated server
2. Join with one of the clients and start campaign
3. Pick a easy mission like kill a monster
4. Do killmonsters to complete the mission
5. Join as the second client to the server and spectate
6. Use teleportsub end and dock to the destination outpost
7. XP spam should start

Another way to break this is to have the second client join and spectate before you complete the mission, this way whenever you try to select the next mission you instead get 505xp each time you press Start on the map selection instead of a constant spam of XP.

Everything works fine if the spectating client spawns in before you dock

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4707e2a44dd24d5a87456d3ead183f714d385b81

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue nor did I find any other methods of achieving this, working correctly. Closing.
