### ISSUE TITLE
[Unstable] Autoshotgun can't be stored in inventory

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6940]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This might be a balancing decision, but the Autoshotgun can not be stored in the inventory. it can only be held inside both hands, rendering the rest of the inventory unusable. This means that the weapon has little to no use in single player, except for combat within the sub which is quite rare. 

In multiplayer it is also inconvenient since the weapon can only be stored in large cabinets or on the floor.

It would seem logical to at least allow it to be stored inside the toolbelt slot.

**Comment by Krzeszny** [comment]
If it can't be stored on the toolbelt, it's a bug.

When it comes to the CQB-only argument, you can use it with explosive slugs and I don't see why you wouldn't use it on missions, especially in wrecks and ruins.

**Comment by Regalis11** [comment]
>The new guns are hard-coded to fit in the toolbelt slot for some reason (even though they could use tags). Weird.

The slots the new guns go to are configured the same way as any other item (the slots-attribute in the xml), not hard-coded - is there some way to configure which inventory slots an item goes to using tags or what do you mean by that?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f8f9a839c100bc016f8892184a0e08caa72b66d

**Comment by Krzeszny** [comment]
> @Krzeszny
> >The new guns are hard-coded to fit in the toolbelt slot for some reason (even though they could use tags). Weird.
> 
> The slots the new guns go to are configured the same way as any other item (the slots-attribute in the xml), not hard-coded - is there some way to configure which inventory slots an item goes to using tags or what do you mean by that?

Oh, I didn't know you configured slots in 'Holdable'. I thought the tags defined the slots. For example, 'smallitem' fits in inventories, 'mediumitem' does not but can be carried in hands. I do believe, although didn't test, that you could place an item in the toolbelt slot just by adding the tag 'toolbelt'.

Speaking of slots, just wanted to mention that your lack of 3 separate slots for masks, for goggles and for helmets... disturbs me.
