### ISSUE TITLE
If a client joins after a mission objective has been completed they don't receive the objective completion notice

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6951]
As the client doesn't receive the completion message this means that the mission will fail for them but not the rest of the crew. Easiest to test with monster missions where the completion of the mission relies on the confirmation message. 

This did however work correctly before the latest XP spam issue fix, but this could also just be some jank when playing the game with two clients on the same machine

1. Host a dedicated server
2. Setup two clients and join the server with one of them
3. Start campaign and select a monster kill mission
4. Kill monster to complete the mission using killmonsters command
5. Join as the second client, notice that they don't get the kill confirmation message
6. Switch to first client and dock to the destination outpost4
7. Notice that the mission fails for the client who joined mid-round

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@6b2f1a1. Keep an eye out if there's any unexpected behavior with the missions since this basically affects all of them for players who join mid-round.

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue anymore, seems to be working correctly. Closing.
