### ISSUE TITLE
[Unstable] Slipsuit doesn't have visible fins

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6952]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

It claims to have "additional fins" which make it "difficult to walk on solid ground".

Because of the slowest walking speed in the game, you'd expect it to have **scuba diving fins** (and perhaps some fins for the hands, too). It doesn't have them.
![lPbsb9q2yp](https://user-images.githubusercontent.com/10529134/137777666-3a1495e4-8e3c-4fed-9b3e-042984c2e025.png)
An alternative to changing the art design would be to have it **accelerate and decelerate slowly** instead of walking slowly.

**Version**
v0.1500.8.0

Since we're discussing fins, all diving suits could have small visual fins because they're designed for swimming.
Maybe in some future update there could be fins for a feet slot attachable to any suit.
Finally, PUCS is a straight upgrade to the Combat Suit while Slipsuit feels like a sidegrade. In my opinion, significantly reducing the debuff wouldn't make it OP.

**Comment by Krzeszny** [comment]
> they do have fins on the feet

No. Those things you see look more like the Long Fall Boots from Portal. They don't look like something that functions as a fin or even something that limits feet movement. Have you even read my report?
If the suit had scuba diving fins, it would make sense. If there are no fins, there's no reason to have the walking speed debuff. It's just annoying.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.

**Comment by Krzeszny** [comment]
> We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.

Aww man... Current unstable is about visual changes and all it needs is scuba diving fins... unless the art team is really busy.
