### ISSUE TITLE
[Unstable] Select Matching Item deletes unrelated gaps when a duct/door like is selected

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6954]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When "select matching items" is used on a door-like that has a gap, it will also select all gaps in the submarine.

**Steps To Reproduce**
0. Place gaps, ducts, doors
1. select a door
2. select all matching items
3. all gaps should now be selected

**Version**
0.1,508

**Additional information**
related maybe #6421

video related

https://user-images.githubusercontent.com/5103517/137783869-07202c98-710b-4f51-b17e-a804031bfdb0.mp4

**Comment by Regalis11** [comment]
Fixed in Regalis11/Barotrauma-development@f7e9b96

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
