### ISSUE TITLE
[Unstable 9] Railguns do not charge anymore

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6955]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Railguns do not charge.

**Steps To Reproduce**
1. Load any vanilla ship with a railgun (tested on Humpback and Typhon 2)
2. Start the reactor and get on a railgun.
![Barotrauma_ktxNIeusR0](https://user-images.githubusercontent.com/10529134/137795614-9e89f644-7c5b-4737-a906-fef0c16b7e7f.png)

**Version**
v0.1500.9.0

**Comment by mrjpjr** [comment]
The railgun is not the issue. The supercapacitor is not charging.
