### ISSUE TITLE
Modding / Code : Explosion.cs 'flashcolor' only parses 0-1 not 0-255

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#6956]
Explosion serializable property 'flashcolor' behavior seems to be not consistent with other properties accepting a color value.

**Expected Behavior:**
_( All other cases the game accepts both decimal or 256 color input. Examples such as decimal color being used on many item light sources and legacy particle effects, but 0-255 being used on other particle effects. )_

The vanilla implementation example of `pulselaser.xml` on line 107 would suggest this.
`< Explosion range="150.0" structuredamage="25" itemdamage="25" force="10.0" flames="false" smoke="false" sparks="false" underwaterbubble="false" flashcolor="255,0,0,255" >`
Seems this oversight was not noticed in testing though, since there aren't any non-zero values for the other channels it does not produce any visual difference parsed as "1,0,0,1"

**Steps to reproduce:**
For example, entering a flashcolor of flashcolor="255,1,1,255" will just produce an entirely white flash,
or entering flashcolor="255,1,0,255" will produce a yellow one.

**Comment by Rokvach** [comment]
Seems to be working correctly, closing.
