### ISSUE TITLE
[unstable] Wrong chat messages for navigation terminal's drag and drop commands

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6957]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Yes.

**Steps To Reproduce**
1. Open the command console
2. Drag and drop a command to a different room
3. Controlled character says that it's in the same room (usually command room) but the icon appears in the correct room

**Version**
up until v.0.1500.9.0

**Comment by PokkeTigrex** [comment]
This is better reproduced while hosting or in a multiplayer server, this doesn't appear to be an issue in singleplayer or shipbuilder.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
