### ISSUE TITLE
[steam]#issue connection failure even if game is running local

### ISSUE THREAD

**Issue by StevenLi-phoenix** [Regalis11/Barotrauma#6963]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
单玩家，新建服务器在本地。
玩了一会自动断连，把我踢出去了。
只发生过一次

**Steps To Reproduce**
Don‘t Know

**Version**
MacOS BIgsur V11.6

**Additional information**
None

**Comment by Regalis11** [comment]
Sorry for the super late reply. I'm afraid there might no be much we can do about this without some more clues regarding the problem. Do you happen to remember what kind of error messages you got when you got disconnected (if any)?

**Comment by Regalis11** [comment]
No known steps to repro, closing
