### ISSUE TITLE
[Unstable] flickering when in UI while wearing an item that reduces vision

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6965]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If your character is wearing a wearable that obscures vision, such as a PUCS or other diving suit, the screen will flicker if the player interacts with an item with UI. It's as if the character is looking left and then right every other frame, 

**Version**
V0.15.9.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
