### ISSUE TITLE
Pumps, supercapacitors and batteries deteriorate when the reactor is off

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6970]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While junction boxes don't seem to deteriorate at all with the reactor off, pumps, supercapacitors, and batteries deteriorate – it feels quicker than normally. **Shouldn't they stop deteriorating completely?**

**Steps To Reproduce**
(tested on vanilla Humpback)
Turn the reactor off, observe the pumps, supercapacitors and batteries deteriorate.

**Version**
v0.14.9.1

**Additional information**
I'd assume batteries/supercapacitors would only deteriorate when being charged or discharged and pumps when they're pumping. Pumps wouldn't deteriorate from just being in water...

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
