### ISSUE TITLE
[Unstable] Skills going down after every level change.

### ISSUE THREAD

**Issue by Seamlemm** [Regalis11/Barotrauma#6971]
Description
After me and my friends finish a mission we noticed that our skills were going down and not going back up.

Steps To Reproduce
After every level change, our skills went down by as much as 7-8 points and we found it hard to keep up.

Version
The latest Unstable Branch version. All of us are Windows 10.

Additional information
We tested with 3 people and still ran into it. we had 6 and also encountered it. All of us uninstalled mods and reinstalled the game a few times, and still encountered this issue

Skills On Spawn:
![Skills on Spawn](https://user-images.githubusercontent.com/81660413/138195585-fbf47fb6-4be5-49d4-80bd-80d5e64f25a8.png)
Skills after leaving the station:
![Skills after leaving first station](https://user-images.githubusercontent.com/81660413/138195586-16a1f623-9981-4e87-81ee-5d3ace895fdc.png)
Skills just before docking:
![Skills Before Docking](https://user-images.githubusercontent.com/81660413/138195584-19d514ee-e4ac-4b96-910e-7add46008bcc.png)
Skills after docking:
![Skills After docking](https://user-images.githubusercontent.com/81660413/138195582-49c81d88-9a75-4573-981e-599ac8f00748.png)

EDIT: Imaged were in wrong order. Fixed them now

**Comment by DaisukeFeng** [comment]
As a side note, the skill reduction isn't simply visual. After multiple missions and a cumulative number of points that would have let me be level 55, the ability to repair an electrical engineering device without fail, I was electrocuted.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
