### ISSUE TITLE
[0.15.9.0] Talent icons are unclickable/no tooltip when you underlay menus like fabricator behind it.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6972]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Talent icons are unclickable/lacks tooltip when you underlay menus like fabricator behind it.

**Steps To Reproduce**
1. Give yourself skill points for the click test.
2. Interact with Fabricator
3. Open the Talent tree and try to read talent description or click on them to spend points.

**Version**
0.15.9.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
