### ISSUE TITLE
[0.15.9.0] Bots - Giving Clean Up Task to Bots will store away all your toolbelts from a Crate/Duffel Bag that the players uses to sell things

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6978]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Giving Clean Up Task to Bots will store away all your toolbelts from a Crate/Duffel Bag that the players uses to sell things. I have to find them all over the sub again.

**Steps To Reproduce**
Fill a crate/duffel bag with Toolbelts to make a "Sell Crate/Bag" and then task a bot to Clean Up.

**Version**
0.15.9.0

**Comment by Regalis11** [comment]
Hmm, I'm not quite sure how this could be addressed: how could the bots know which containers you're intending to use as "sell crates/bags"? Have you tried ordering the bots to ignore the container?
