### ISSUE TITLE
Fabricator does not find items inside containers

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#6980]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While the fabricator does consider items within linked containers, it does not find items within containers stored in the fabricator or linked cabinet.

This is inconvenient as it's very common to store items in storage containers within the linked container, especially on subs with limited storage. Whenever you want to craft something, you have to go through all your storage containers to get the required materials out or to search whether you have the material in the first place, which can be pretty cumbersome.

It might also allow linking crate storages like the ULD in the long term, although this not being possible may be a design choice given that crate storage seems more intented for use in trading items at outposts or as temporary storage after looting.  

**Additional Information**
These changes probably require some performance considerations since currently the fabricator goes through all inventories every frame in the update method.

https://github.com/Regalis11/Barotrauma/blob/bf95e82d80e847eb0f6974558c66bc90a0291d5e/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Fabricator.cs#L243

It might be possible to do this only when someone is within the fabricator UI, or by reducing the frequency of these checks and doing a final check before updating the item is crafted.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
