### ISSUE TITLE
[0.15.9.0] Bots - Orders requires reassigning after leaving outpost

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6981]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[OrderTrouble.zip](https://github.com/Regalis11/Barotrauma/files/7388558/OrderTrouble.zip)
For some reasons every time I go to an outpost, my bots don't remember how to man the guns or do the tasks they were ordered to from a previous level after undocking. I need to reassign their orders l every time.

**Steps To Reproduce**
1. Load Save
2. View orders in character list
3. Undock
4. Observe bots

**Version**
0.15.9.0

**Comment by ekqvist** [comment]
No known steps to reproduce to issue. Closing the ticket.
