### ISSUE TITLE
[0.15.9.0] Bots - Your crew members assists the Outpost in arresting/beating/killing you if you're hostile to the Outpost

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6982]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Your bot crew members assists the Outpost in arresting/beating/killing you if you're hostile to the Outpost.

**Steps To Reproduce**
1. Give your whole bot crew a gun.
2. Shoot an outpost NPC.

**Version**
0.15.9.0

**Comment by Kaillera** [comment]
https://www.twitch.tv/videos/1182220307?t=00h36m00s

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@188c6e7.

**Comment by Rokvach** [comment]
Seems like own crew security officers will attack player in multiplayer if the player attacks a outpost NPC, is this intentional?

**Comment by itchyOwl** [comment]
Not intentional. Fixed in Regalis11/Barotrauma-development@cbd862a.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
