### ISSUE TITLE
[0.15.9.0] Bots - Follow order is switching who they're following based on the player's actively controlled character

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6983]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Follow order for bots is switching who they're following based on the player's actively controlled character.

**Steps To Reproduce**
1. Have your Main character assign a Bot to follow you... say outside the sub.
2. Switch to a Secondary character inside the sub... you probably forgot to water the plants before you left.
3. The Bot will follow the Secondary Character instead of remaining with the Main Character.

**Version**
0.15.9.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
