### ISSUE TITLE
Reactor still shocks/electrocutes when it's off (when rewiring)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6984]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can turn a reactor off but it still has the same chance to shock you when manipulating its wires.

Turn a reactor off and keep clicking any wire.

**Version**
v0.14.9.1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
