### ISSUE TITLE
[0.15.9.0] Neutralized Pirate Vessel, but it didn't count

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#6986]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I was in Singleplayer with one mission to neutralize a Pirate Vessel. I went to encounter it, and my crew shot it down, killing most of the crew except 1 Pirate Captain left on board. It sank and landed on an Abyss island. I swam out and board it and killed the last Pirate Captain while dual wielding a knife and screwdriver, but the mission didn't considered it neutralized. I've checked the entire sub, and didn't find any other living pirates. Shortly after a Charybdis spawned and attacked both my sub and the vessel. I defeated the Charybdis and then docked my sub to the vessel. I set the vessel on nuclear meltdown and then dropped it off into the abyss. It still didn't counted. I just went back and dock to the outpost and found out I still failed it.

**Version**
0.15.9.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Kaillera** [comment]
[Save.zip](https://github.com/Regalis11/Barotrauma/files/7638198/Save.zip)

So I sunk a pirate vessel down 3000m below and the mission didn't give a complete prompt.

I started the level and went and repair the Beacon Station first. I immediately cleared out the crawlers that spawns after fixing a Beacon to ensure it's survival. Next I went and crafted one nuclear railgun shell with a IC-4 block from my armory. I loaded it up and went to the Pirate Vessel sighting. The battle ensues and they started sinking. I decided to make a guess and fire my nuclear railgun shell at them without being able to see them on the periscope. They kept sinking and I wasn't sure if they were dead or not. I decided to freecam and check their submarine out. I was able to hit their engine room with the nuke shell. Once I started seeing their submarine cracking apart from pressure, I went back and took control of my Captain. Shortly after, all my crew members said things like: "I think I got it!" and "Enemy down!", which I assume they all died to pressure. I didn't get a mission complete prompt for it, so I decided to freecam and check their sub again. No one is left alive in their sub. I went and dock for this result screen:

![Capture](https://user-images.githubusercontent.com/5086682/144341343-9e9e7a10-eb7b-4705-89e0-db5f3ae88463.PNG)

**Comment by Rokvach** [comment]
During the community test session last(?) weekend we were able to complete a pirate mission because they fell into the abyss and were killed by the pressure. So I wonder what the actual issue of this might be

**Comment by Regalis11** [comment]
I gave the above save a test, but no luck :/ The mission seems to complete as soon as the pirate sub gets to crush depth and the pirates die.

**Comment by Regalis11** [comment]
I'm still not entirely sure what caused this, but while trying to repro it, one of the pirates ended up outside their sub during a massive hull breach, and got left behind when the sub sank into the abyss. That pirate prevented the mission from being considered a success, so it could maybe explain what happened in your case.

Now pirates that are outside their sub or unconscious are considered dead, let's see if that gets rid of the issue. https://github.com/Regalis11/Barotrauma-development/commit/feebf32b5bcc7b960bdb4b843107ba36ee2d7777

**Comment by Rokvach** [comment]
I noticed that if the whole pirate crew is paralyzed it doesn't count as them being unconscious so the pirate mission fails, ofc paralysing the whole crew might not be the easiest strategy to go by but I think it would still be good to treat it the same just incase. 

Other than that this is working correctly.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
