### ISSUE TITLE
Sonar favours smaller subs

### ISSUE THREAD

**Issue by Peenarse** [Regalis11/Barotrauma#6990]
I notice that on smaller subs you can zoom out on the sonar UI a long way, and get great visibility of what lies ahead. On the largest subs you have to be fully zoomed out to get any visibility at all - any zoom-in has the edges of your sub outside the sonar UI, making it essentially pointless to do so outside of docking.

Since the larger subs tend to be more sluggish anyway, and require more careful and precise manoeuvring, having the added handicap of (effectively) reduced visibility range on the sonar is a real disincentive to use them. Could the sonar UI not scale with submarine size in order to remain consistent?

Here are two very different sized subs at the same levels of zoom, to better demonstrate what I mean.
![smallsub](https://user-images.githubusercontent.com/92940695/138320355-f050f703-1f38-47d2-afbc-2ead8c4f8778.jpg)
![bigsub](https://user-images.githubusercontent.com/92940695/138320374-b089d025-640a-49fe-a8c1-4447a7dcf039.jpg)

An alternative suggestion is giving transducers their own sonar "bubble" centred at their location, so that larger subs could place them at their extremities to give them better coverage. This would have minimal impact on the functionality of shuttles and drones considering their tiny size. Just an idea.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/5f2216991cf3d578af1d3e79cf86804e6d5f710f by adding an option to make the sonar centered on the position of the transducer.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
