### ISSUE TITLE
Wires render in strange fashion ingame and in submarine editor

### ISSUE THREAD

**Issue by Gerald7777** [Regalis11/Barotrauma#6991]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wires render behind submarine when first loading in the editor. Not sure if related to the submarine (in additional information) or to render engine. 
**Steps To Reproduce**
Open attached file in submarine editor. Try testing it and return to the editor.

As seen after loading the sub:
![Screenshot 2021-10-22 00 11 37](https://user-images.githubusercontent.com/65957231/138364267-1326fd6d-071b-4adc-a5f6-81aad711fc48.png)

As seen in test mode:
![Screenshot 2021-10-22 00 11 58](https://user-images.githubusercontent.com/65957231/138364344-24d0d881-c9af-4591-8d78-0996a01d18f5.png)

As seen after exiting test mode:
![Screenshot 2021-10-22 00 12 14](https://user-images.githubusercontent.com/65957231/138364403-90712c15-d005-4763-ba2e-9166989eb58c.png)

As seen after reentering test mode:
![Screenshot 2021-10-22 00 12 35](https://user-images.githubusercontent.com/65957231/138364527-e290a489-0276-47a7-b2cf-4bc1bde22fb0.png)

As seen after exiting 2nd testmode:
![Screenshot 2021-10-22 00 12 53](https://user-images.githubusercontent.com/65957231/138364505-a5089cba-2fde-426a-8e42-ae27c90ccbfc.png)

**Version**
Windows v0.15.9.0 and v0.15.10.0

**Additional information**
Submarine file:
[Engineering Dream.zip](https://github.com/Regalis11/Barotrauma/files/7393157/Engineering.Dream.zip)

**Comment by Regalis11** [comment]
This seems to have happened because these wires had been mirrored (or rather, the groups of doors, components and wires had been mirrored), which caused problems when loading the wire. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eefd31cae61eae80ed0f2908571a6745bf5aaa75

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
