### ISSUE TITLE
[Unstable] Assistant has no accsess on the sub. 

### ISSUE THREAD

**Issue by N1ght-Raven** [Regalis11/Barotrauma#6992]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i detting drunk man from outpost on boart as assistant, he can't open any doors on the sub cuz of invalid acsess.

**Steps To Reproduce**
Just take a assistant crewmate from outpost quest with drunk man 

**Version**
Last version I played, is Unstable V0.15.9.0

**Additional information**
I not tested it on multiplayer.

**Comment by Gerald7777** [comment]
1. What sub was it on? (permissions to open doors and access security containers are set in .sub file so it may be a bug with submarine)
2. If you can try to access his inventory and check what ID does he have, it may be useful.

**Comment by N1ght-Raven** [comment]
> 1. What sub was it on? (permissions to open doors and access security containers are set in .sub file so it may be a bug with submarine)
> 2. If you can try to access his inventory and check what ID does he have, it may be useful.

It heppening even on a default dugong.
