### ISSUE TITLE
MotionSensor ItemComponent detects its own motion

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6993]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is an issue when modding items that detect motion such as bombs.
`<MotionSensor/>` in an item with a `<Body/>`  **always detects whether it's moving**.

It works like this:
- When the item that detects motion is inside a hull, it detects its movement relative to the hull.
- When the item is outside, it detects its movement relative to the map.
- This is all separate from the settings (whether it should detect humans or monsters, or walls)

**Steps To Reproduce**
Take the item from the super-simple mod attached. It should only light up when a human character is moving within a 1-meter radius.
1. Throw it outside of the airlock (it lights up as long as it's falling)
2. Throw it against the floor (it lights up as long as it's rolling)
3. Place it on the outside of a submarine (it lights up as long as the sub moves relative to the map)

**Version**
Up to 0.15.10.0

**Additional information**
There is a workaround that I've "patented". It involves repeatedly spawning an invisible item with a `<MotionSensor/>` but without a `<Body/>` that nearly instantly removes itself while still being able to send a signal to the spawner.

Example item:
https://drive.google.com/file/d/10B5TRDfAjOVurFwRcTzmUy6dyf2jQEwI/view?usp=sharing
Video:
https://user-images.githubusercontent.com/10529134/138445988-266d009b-667c-414d-959b-8528b6c6a9f3.mp4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Krzeszny** [comment]
Working but only in unstable v0.15.15 :/
