### ISSUE TITLE
Wrong location after docking and stuck in map screen

### ISSUE THREAD

**Issue by ArmaWave** [Regalis11/Barotrauma#6998]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

Description
Wrong location after docking and can't travel to a new destination

Steps To Reproduce
After docking to a military outpost and getting to the traveling map, got placed in another location instead of the outpost and can't travel to a new location so im stuck in the map screen, also the military outpost turned into a colony

Version
0.14.9.1

Additional information
Crash when loading that campaign

**Comment by ArmaWave** [comment]
Hello, sorry for not replying, if you still need the save file let me know

**Comment by ArmaWave** [comment]
> 

Hello, sorry for not replying, if you still need the save file let me know

**Comment by Regalis11** [comment]
If you still have it, it'd help us a lot in diagnosing this. We just received [another report about a similar-sounding issue](https://github.com/regalis11/barotrauma/issues/7490), and it could be related to this one, but without the save file we can't be 100% sure.

**Comment by ArmaWave** [comment]
> If you still have it, it'd help us a lot in diagnosing this. We just received [another report about a similar-sounding issue](https://github.com/regalis11/barotrauma/issues/7490), and it could be related to this one, but without the save file we can't be 100% sure.

sure, where do i send it?

**Comment by Regalis11** [comment]
You can send it here (you can attach files by dragging or dropping them in the message field or click the text below the field). Note that you need to .zip the file first since GitHub doesn't allow attaching files with the .save file extension. Thanks in advance!

**Comment by ArmaWave** [comment]
[DiegoTrauma 2.zip](https://github.com/Regalis11/Barotrauma/files/7707127/DiegoTrauma.2.zip)
here it is, hope it helps


> You can send it here (you can attach files by dragging or dropping them in the message field or click the text below the field). Note that you need to .zip the file first since GitHub doesn't allow attaching files with the .save file extension. Thanks in advance!

**Comment by ArmaWave** [comment]
in the map you can see a colony to the left named Libya Linea, thats the military outpost i docked at that got turned into a colony, i got teleported to Cilicia Flexus iirc, when i tried to load the save the game crashed but now i was able to load the save and somehow now im at Phineus Linea

**Comment by Regalis11** [comment]
No known steps to repro (and this is such an old ticket there's a chance the issue has been fixed since). Closing.
