### ISSUE TITLE
husk "bite" and mudraptor beak genetics arent attacking properly.

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#6999]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
both the mudraptor beak genetic and being partial husked have an R based attack, neither of them actually ever hit, even when fully touching other characters.

**Steps To Reproduce**
be partially husked (enough to get the husk tongue thing) or get the mudraptor beak genetic, and try to attack with R, which promptly just does no damage, no matter what.

**Version**
Unstable, windows 10

**Additional information**
-

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
