### ISSUE TITLE
[Unstable] PUCS diving locker sprite is almost undistinguishable from Combat Suit locker sprite

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7006]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While they're side-by-side, it's easy to distinguish them but otherwise the orange shade is too similar to the red
![ApplicationFrameHost_16KvLiMyN1](https://user-images.githubusercontent.com/10529134/138570646-4454ff38-42b7-4d09-829c-a58f9e41aff9.png)
**(too red)**

30-second fix
![gimp-2 10_qDOzMRvely](https://user-images.githubusercontent.com/10529134/138570659-7c7afd14-012c-4ed7-827c-d55454325595.png)
**(not too red, not too yellow)**

**Version**
v0.15.10

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
