### ISSUE TITLE
"Ignore This" orders carry over on submarine swaps & target mismatches ensue.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7009]
When items on the submarine are ordered to be ignored by bots and then you buy & swap to a new submarine, the old "ignore this" orders will carry over but be assigned to seemingly-random ( but most likely just whatever the corresponding item ID was on the old submarine ) other items onboard the submarine. Given the large variety of items on a submarine, this can lead to the "ignore this" icon being assigned to completely un-interactable things like shell walls and decorations, therefore making them impossible to 'dismiss' from.

**steps to reproduce:**
- Order bots to ignore a few items around the submarine
- Purchase & switch to a new submarine
- Start round
- "Ignore This" orders are now _'randomly'_ distributed among items of the new submarine

The low-effort solution would be to maybe stop these orders from carrying over entirely, the high-effort solution would be a system that can allow items carried by characters & inside containers to inherit their ignore order while ignoring any 'structural elements' and items left on the old vessel.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
