### ISSUE TITLE
Cargo mission application order when calculating reward.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7012]
When taking more than one cargo mission, priority goes in order of mission listing. If the submarine only has enough room to complete one of the missions partially, the higher mission will always take the room first. This can become an issue if - for instance - the top mission is a lower paying one but the bottom mission is a higher paying one. 

( In situations it can end up being more profitable to drop the 'first' mission entirely - as the reward combined with partial completion of the second mission is less than just finishing the second one )

![image](https://user-images.githubusercontent.com/55356135/138610160-4bd2287a-f0b4-4b31-a978-88ddc594e427.png)

Possibly allow cargo missions to be applied in order that they are accepted for the sake of simplicity
 (and player expectation with regards to apparent reward math)

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
