### ISSUE TITLE
[Unstable] Ammunition inserted into a weapon will playout it's impact sound when said weapon hits the ground

### ISSUE THREAD

**Issue by SpazzMaticus107** [Regalis11/Barotrauma#7013]
- [yep ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ammunition inside of a harpoon gun and any other weapon will play the "impact" sound when said weapon hits the ground. This means a revolver with 6 bullets inside of it will produce a sharp and loud noise upon hitting the ground.

**Steps To Reproduce**
Spawn two revolvers/harpoon guns and fill one of them with ammunition, then drop the first and the second one to look for the sound issue. The reloaded weapon will play it's "impact" sound and so will each of the contained items inside of it.

**Version**
Windows, Unstable

**Additional information**

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
