### ISSUE TITLE
AI crewmembers operating turrets too chatty when fighting enemy swarms.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7015]
AI crewmembers report every time they acquire a new target and every time a target is killed, this leads to the chat being completely flooded with them yelling when fighting larger swarms on the later difficulties with even just 2 gunners.

![image](https://user-images.githubusercontent.com/55356135/138618759-18cfc193-3e6a-4e81-b08e-b761e3f85ad1.png)

Maybe either a maximum cooldown is needed between they can report again, or ignore reporting 'incidental' target changes when fighting multiple enemies.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
