### ISSUE TITLE
Make Vents Automatically Lock Themselves Upon Having Water Reach Them- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#702]
Let submerged vents no longer deliver oxygen due to locking themselves, so this would explain, why water does not reach other parts of submarine by ventilation tunnels. Vents don't need water detectors for that and consume no power doing it.

**Comment by thegrb93** [comment]
Or the vents just have a one-way valve. Bubble effect would be neat for submerged vents.

**Comment by rico6822** [comment]
So the bubble effect allows vents to supply with oxygen those rooms even, when submerged?

**Comment by BlueTheKing** [comment]
Since the "bubble effect" is oxygen leaving the vent, yes it would.

**Comment by Baywatcher11** [comment]
Vents being not connected to power and closing themselves automatically wouldn't make sense at all, after all, it's just an "oxygen pipe".

**Comment by rico6822** [comment]
I haven't thinked about that. I wander if Regalis is gonna add it anyway, since he loves making his video games challenging.

**Comment by Regalis11** [comment]
Seconding a one-way valve
