### ISSUE TITLE
[0.15.10.0] Crashed while trying to use camera to look at Pirate Vessel or something

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7020]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Save.zip](https://github.com/Regalis11/Barotrauma/files/7410610/Save.zip)
[crashreport .log](https://github.com/Regalis11/Barotrauma/files/7410612/crashreport.log)

I crashed in the middle of a 1 hour level when I was using my submarine's camera to try to look at the Pirate Vessel infront of me.

![Capture](https://user-images.githubusercontent.com/5086682/138708946-6fb16a3d-b9d6-4d6f-af57-07261eec06ab.PNG)

My crew sank the Pirate Vessel on top of the Beacon Station. We were both being harassed by the mission Thresher Swarm at the same time. I pilot my sub closer to get a look at what the Pirate Vessel was. The periscope in the navigation terminal can view the exterior of my sub. It's a multi-camera system, so I started left clicking in order to get the top right searchlight. Once I switched the camera and saw the Pirate Vessel (Humpback) sitting ontop of the beacon station, it crashed.

**Version**
0.15.10.0

**Additional information**
I went and retrieved the artifact in the ruin right before attempting the Pirate Vessel mission.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
