### ISSUE TITLE
[0.15.10.0] Talent - Gene Harvester only activates on kills made by the Medic with the talent

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7021]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Gene Harvester only activates on kills made by the Medic with the talent.

**Steps To Reproduce**
Give Gene Harvester to a Medic.

Spawn and kill 20 crawlers with your captain.
Spawn and kill 20 crawlers with your medic.

**Version**
0.15.10.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
