### ISSUE TITLE
[0.15.10.0] Reverse Gravity Rubberbanding Hyperspeed Swimming when Harpooned by Fractal Guardian and you become free

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7022]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I don't know if any devs remembered a long time ago #3069 caused a weird character swimming issue where they can't really control their swimming very well, and it would pull the character upward instead of downward. They would go very fast in any directions.

I ran into the same problem after I got harpooned by a Fractal Guardian and somehow it loosen the rope on me.

**Steps To Reproduce**
Somehow have the Fractal Guardian loose the Rope on you.

**Version**
0.15.10.9

**Additional information**
I think the crash from #7020 that happened much later in the same round was related to this.

**Comment by itchyOwl** [comment]
Possibly fixed by Regalis11/Barotrauma-development@508ba09 and Regalis11/Barotrauma-development@4590589.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
