### ISSUE TITLE
[0.15.10.0] Abandoned Outpost Event - Reggie Nunez the Doctor that joins you doesn't have an ID card that can access your submarine's door

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7024]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Abandoned Outpost Event - Reggie Nunez the Doctor that joins you doesn't have an ID card that can access your submarine's door

**Steps To Reproduce**
Recruit the Captured Drug Dealer in an Abandoned Outpost.

**Version**
0.15.10.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
