### ISSUE TITLE
Medic bot sometimes keeps following the patient that's already healed

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#7026]
Possibly only happens when ordered.

**Comment by TimFragmagnet** [comment]
I can almost guarantee that medic AI is trying to heal buffs currently applied to characters, such as the captain's "ready to draw" buff.

These buffs are classified as a heavy injury for some reason.

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6988

**Comment by itchyOwl** [comment]
I think it's a separate issue, because I didn't have any active genes.

**Comment by itchyOwl** [comment]
I'll try to repro it and debug it when/if I do.

**Comment by itchyOwl** [comment]
Can't repro. Maybe I had some buff afterall.
