### ISSUE TITLE
Beacon station and Hunting grounds side missions missing exp gain upon completion

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#7027]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Beacon station and Hunting grounds do not have any exp gain upon completion. This isn't really a bug since these don't give marks, but they have lost incentive in some people to complete it due to colony missions only giving the exp needed for character progression. Giving these two exp gain will bring back that incentive especially early game when there isn't too much need to get additional outposts and help with gaining exp while out in the ocean when outposts are less abundant mid to late-game.

Example: Beacon station could give around 150 to 220 exp
Hunting ground could give around 450 to 700 exp

**Version**
0.15.10

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e409fb15

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
