### ISSUE TITLE
Difficulties w/ add Submarine menu in sub editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7030]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "Add Submarine" Dropdown shows all submarines from /mods/ alphabetically first, then submarines in /submarines/ alphabetically rather than displaying all of them alphabetically.

This leads to (current) player made submarines being somewhere near the bottom of the list, mixed in with vanilla subs, until they get published, which moves them into the other list of submarines.

The current menu only displays 10 submarines, which, on my monitor, utilizes only like 30% of the available height, leading to more scrolling.

**Steps To Reproduce**
1. Have submarines in both /mods/ and /submarines/
2. Open "Add Submarine" dropdown menu
3. submarines from /mods/ appear first, then /submarines/

**Version**
0.1500.10

**Additional information**
These get progressively more annoying the more subs a player has (either in /submarines/ folder or simply subscribed to).

Name filter would be neat (i.e., typing "amo" would filter to only submarines with "amo" in the name, like in the load sub menu)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
