### ISSUE TITLE
Selection box jitter in submarine editor 

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7033]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The selection box of things may jitter, at certain zoom distances on certain objects.

Demonstration on Shuttle Shell A17a:

https://user-images.githubusercontent.com/5103517/138991829-f433124c-14c0-4062-bc86-f2899036bbba.mp4

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.1500.10

**Additional information**
![882680558960906370 1](https://user-images.githubusercontent.com/5103517/138991998-b9a860a0-d8dd-4fe4-8dd3-12dbdf77c043.png)

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
