### ISSUE TITLE
toggle_light shows light at previous angle for a single frame

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7034]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When toggling a turret light back on, it will light up the position that it was last lit for a single frame

https://user-images.githubusercontent.com/5103517/139023713-d9138e33-908b-42ff-910c-58160e47b6dd.mp4

**Steps To Reproduce**
1. gun light on 
2. oscillator (pulse, 0.5 hz) to toggle light
3. when the light turns off, swing the gun to a new position
4. light turns back on, illuminating previous position for 1 frame

**Version**
0.1500.10

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e70dfc0648a42400d417860200eda77e6c886084

**Comment by Lithosagym** [comment]
Tested, there is no longer a frame where the turret is illuminating the previous position, confirmed fixed.

**Comment by Rokvach** [comment]
Closing
