### ISSUE TITLE
Alien ruins can randomly generate next to the starting outpost

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7037]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Because the generation is random, ruins can generate right next to the outpost or on the other side of the map.

Related to #5187

**Version**
v0.15.11

![Barotrauma_27 10 2021_09_00_45](https://user-images.githubusercontent.com/10529134/139047878-47612b4f-f57c-406f-802d-7f2e4446184b.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07a37d53c6ce3b2e368cdf7c8c99412e1334a65a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
