### ISSUE TITLE
NOT gate uses 1 and 0 outputs while AND gate interprets all signals, even 0 as 1.

### ISSUE THREAD

**Issue by Momiro** [Regalis11/Barotrauma#704]
To get some not gate logic to work I'm having to set up a bunch of signal checks to properly get the gates to behave how they should.

**Comment by rico6822** [comment]
I had the same thing.

**Comment by Momiro** [comment]
I also seem to be having an issue where the absence of a signal doesn't trigger a LOW state on the and signal after already setting it to HIGH

**Comment by Regalis11** [comment]
I wasn't able to reproduce this, could you send me a sub file where this problem appears?
