### ISSUE TITLE
[0.15.12.0] Bug in the co-op game (Failed to read event for entity "EntitySpawner")

### ISSUE THREAD

**Issue by Dieu-le-veut** [Regalis11/Barotrauma#7042]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In cooperative game, it does not let you choose another dispatch point for next journey after entering the miner's outpost named Sontu. And after that if you choose some item of yours with a hotkey, all items from character are thrown on the floor and cannot be taken back (literally all, including jackets, headphones, etc. They are thrown away again after couple of seconds). All items that you can carry are stolen ones only. Moreover, all hatches and doors on the outpost become closed and ID restricted (as on screenshot below):
![image](https://user-images.githubusercontent.com/68340620/139114385-0afc5494-221d-423b-8462-ee3fa592235e.png)
There are many errors in console window. which appears after some period of time:
![image](https://user-images.githubusercontent.com/68340620/139114348-17f79e20-ebb3-47f5-8926-22e06ac7f6f4.png)

**Steps To Reproduce**
Precondition: cooperative server game with two real people and some bots. The crew have arrived to the outpost on the ballast flora overgrown Dugong (if it matters).
Steps:
1) Climb up to the outpost;
2) Choose a next point to travel by map;
3) Choose some item from any your slot;
4) That's all: happens all, that was written in the description.
The console window appears if you start making some troubles (we were bored with friend and started to steal items and kill occasional NPC on outpost🙁) 

**Version**
v0.15.12.0  Russia Language
Windows 10
Game's client is clean, no mods

**Additional information**

There are no additional saves, we can't roll anything back. It's a pity the progress of this company :(
In other saves this bug was not noticed
Saves in the attached file:

[Факен слееееееееееееейвс.zip](https://github.com/Regalis11/Barotrauma/files/7428144/default.zip)

**Comment by JoneKone** [comment]
On my The Happy Traitor server we constantly get the Failed to read event for entity "Human"! error. dunno if related.

https://p.ip.fi/RGne

even if only 1 player on the server

Version: 0.15.23.0

**Comment by Regalis11** [comment]
This has most likely been addressed since the ticket was created. The issue reported by JoneKone seems to be unrelated based on the stack trace.
