### ISSUE TITLE
Pulse Laser power usage not editable

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7053]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Editing the pulse laser's power consumption for the turret reverts back to default (1400) upon entering test mode

**Steps To Reproduce**
1. wire up and place pulse laser
2. change pulse laser power usage to 1
3. enter test mode - pulse laser appears to have default power usage
4. exit test mode, pulse laser is set to 1400 power consumption

**Version**
0.15.12

**Additional information**

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
