### ISSUE TITLE
Doors with motion sensors react incorrectly to AI

### ISSUE THREAD

**Issue by TheDarkBox** [Regalis11/Barotrauma#7057]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Doors that have motion sensors connected to them seem to rapidly open and close while AI (Human) characters are passing through them (but it is fine for players). Curiously, connecting the motion sensor to a text display shows it outputting a 1 despite the door visibly and audibly opening and closing. It doesn't always happen, but I was able to reproduce it more or less reliably.

**Steps To Reproduce**
1. Place a motion sensor with a relatively large tracking area (My X value was 190) and connect it to a door.
2. Order an AI character to follow you or make it walk through the door some other way.
3. Watch the door as the AI passes through it.

**Version**
0.15.12.0 (Windows)

**Additional information**
N/A

**Comment by itchyOwl** [comment]
I haven't encountered this on vanilla subs. Also ruins use motion sensor to close the doors behind the guardians, which seems to work ok.

**Comment by TheDarkBox** [comment]
Hm.. well, I still seem to get it in the editor, but it doesn't really matter because it's only affecting the editor.. or if not, then it would have to be something with my game. If you're sure this issue doesn't occur in the submarine editor, then there's not much more info I can offer.

**Comment by itchyOwl** [comment]
Quickly tested in Humpback in the editor and the doors seem to work ok and the bots manage to follow me as they should.

**Comment by Regalis11** [comment]
No known steps to repro, closing
