### ISSUE TITLE
Abyss diving suit doesn't fit the new ragdoll

### ISSUE THREAD

**Issue by ServenAlive** [Regalis11/Barotrauma#7059]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Rokvach** [comment]
The arm hole seems to be still off
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6968d4ec-4806-46bb-a55b-e74ed3ca83d2)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
