### ISSUE TITLE
Separate Save Files to Editable xml File and Second Uneditable dll File- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#707]
Editable part includes crew and current campaign credits. It would looks like this:

`<?xml version="1.0" encoding="utf-8" ?>
<credits="3849"/>
<lastsaved="(insert here time)"/>
<crew>
 <member>
  <name="Mino Koorunta"/>
  <gender="Male"/>
  <head="3"/>
  <job="Captain"/>
  <subposition="(insert something here)"/>
  <skills>
   <skill name="Weapons" level="54"/>
   <Skill name="Construction" level="25"/>
   <Skill name="Electrical Engineering" level="22"/>
   <Skill name="Medical" level="16"/>
  </skills>
  <headslot="Captain's Cap"/>
  <torsoslot="Captain's Jacket">
   <containerslot="1"/>
   <containerslot="2" item="Corrigodone"/>
   <containerslot="3"/>
   <containerslot="4"/>
   <containerslot="5/>
  <legsslot="Captain's Trousers"/>
  <faceslot="Headset">
   <containerslot="1" item="Battery Cell/>
  <idslot="ID Card"/>
  <handslot1="Railgun Shell" 1+2="true">
  <handslot2="Railgun Shell" 1+2="true">
   <containerslot=/>
  <inventoryslot1=/>
  <inventoryslot2="Revolver">
   <containerslot="1" item="Revolver Round"/>
   <containerslot="2"/>
   <containerslot="3"/>
   <containerslot="4"/>
   <containerslot="5" item="Revolver Round"/>
   <containerslot="6"/>
  <inventoryslot3=/>
  <inventoryslot4=/>
  <inventoryslot5=/>
  <inventoryslot6=/>
  <inventoryslot7=/>
  <inventoryslot8=/>
  <inventoryslot9=/>
  <inventoryslot10=/>
 <member/>
<crew/>`

The dll file contains information about map, submarine and campaign progress. They are obviously encoded.

Those both files are put into different folders to evade information about 2 files of the same name or other circumstances like it. They are also storing information about inventory like this to avoid bug causing inventory not to save correctly upon end of the mission and items being lost.

**Comment by rico6822** [comment]
Github have glitched a bit the way I drew example editable save file part. Here is how it looks (ignore the file not being xml and not having colours, it's a makeshift example):

https://jumpshare.com/v/tL0w5biRm1hG764PA5Bd

**Comment by Regalis11** [comment]
The save files are saved in a non-human-readable format on purpose, IMO they're not something that the players should be easily able to edit. But if someone does wish to cheat by editing them, it's not that difficult to decompress them first.

**Comment by rico6822** [comment]
Ok, but I have another question. Can you reprogram save file system the way I showed, but entirely dll to prevent inventory from being incorrectly saved?
