### ISSUE TITLE
Trying to open Characherx in character editor will cause crash

### ISSUE THREAD

**Issue by IChKEInDEUTSCH** [Regalis11/Barotrauma#7072]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When opening the character editor, scrolled down to the bottom and choose Characterx will cause the game crash, using the button "next" will cause the game crash too.

**Crash Report quick view**
Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: Void AddLimb(LimbParams)

**Version**
Game version:0.15.12.0, Using Windows

**Crash report**
[
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7441257/crashreport.log)
](url)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7a7592f5e6e275d6747ae50e1fc8beae2c95a67e

**Comment by Rokvach** [comment]
The mod doesn't seem that have that CharacterX anymore so haven't been able to test this, but I'm still going to close the ticket as I haven't noticed any other issues come by the changes. This can be re-opened if the issue happens to resurface later on in some other mod. Closing.
