### ISSUE TITLE
Water Prankster doesn't appear to protect from pressure client-side

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#7074]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The blood and screen effects are visible client-side when the client goes outside with the talent. The character still doesn't get killed by the pressure.

**Steps To Reproduce**
1. Give yourself "Enrolling into clown college" and "water prankster" in multiplayer
2. Go outside

**Version**
v0.15.12.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by AlexanderSporovets** [comment]
Hello, i am experiencing this issue currently. The characters, while having this perk, suffer from pressure and die of it (tested it in docked condition and  <2000 depth).
Tested it with all mods deactivated, with a fresh campaign
