### ISSUE TITLE
Combat Suit deconstructs to only 1 out of 3 rubber (and rubber losses in general)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7080]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Normally, diving suit deconstruction is lossy, with one rubber missing. Personally, I don't like it but that's up to you.
Combat Suit takes **3** rubber to fabricate (2 from a Diving Suit, 1 additional). It deconstructs to **1**.

**Version**
v0.15.12

**Additional information**
What is the point in lossy deconstruction if no other items do that?

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/aacddcb85fe335342a8ce44e719b7bacf8fd7cde

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
