### ISSUE TITLE
Reactor PDA showing interface of non-interactable reactor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7082]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
reactor PDA can show the "wrong" reactor, including hidden / non-interactable reactors

**Steps To Reproduce**
1. place a regular and a non-interactable/hidden in game reactor
2. open reactor PDA

**Version**
0.15.12

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d772fdc370b86ce0c0f02e3f6289de7fde0e11ab

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
