### ISSUE TITLE
Barotrauma.Networking.GameClient.ReadIngameUpdate - crash to menu

### ISSUE THREAD

**Issue by tastesliketriangle** [Regalis11/Barotrauma#7087]
joined a server, chose roles, clicked spectate. loading seemed to be almost finished when it crashed to menu, said to post this log file.

[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/7445735/networkerror_data.log)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/1815
