### ISSUE TITLE
quick reloading of weapons

### ISSUE THREAD

**Issue by gnomesh** [Regalis11/Barotrauma#7093]
is it possible to add accelerated weapons to the game by double-clicking on the number on which the cartridge is located, if the weapon is in the hands

**Comment by Regalis11** [comment]
This should already be implemented: double-clicking on the magazine automatically places it in the equipped weapon. I gave it a quick test with a couple of the vanilla weapons and couldn't spot any issues: does it not work with some specific weapon?

**Comment by gnomesh** [comment]
maybe you didn't understand me). I meant recharging without using the cursor by double-clicking on the number where the store is located, and now it is only taken in hand instead of recharging

**Comment by Regalis11** [comment]
Ah, you mean pressing the slots' number key twice? That could be worth considering, but I'll close the ticket since this isn't really a bug report but a feature request.
