### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#7095]
There are two critical mistakes in Russian localization of the connection terminals:
(file: RussianVanilla.xml)
1.
`<connection.togglestate>включить_состояние</connection.togglestate> `
currently it means TURN ON STATE which has no sense. This bug is described in all Russian guidelines for at least one year. There is no way an inexperienced player can guess the function of this terminal. Correct translations are: **переключить_состояние** (_toggle state_) or **изменить_состояние** (_change state_).

2. The same applies for
`<connection.conditionout>состояние_выкл</connection.conditionout> `
currently it means STATE OFF. Correct direct translations is: состояние_из (_condition out_ or _state out_) however it would be the same as translation for state_out terminal (STATE and CONDITION have the same translation in Russian). The best solution is to name it **статус_из** (means _status out_) which has the exact sense of the function of this new terminal.

There are other minor translation bugs, but these two are critical - it is impossible to understand the function of the terminal without searching the Internet.

**Comment by Regalis11** [comment]
Addressed in Regalis11/Barotrauma-development@f18a16a

**Comment by MaaiG** [comment]
`<connection.conditionout>состояние_выкл</connection.conditionout>` - it's horrible.

Но народ, зачем огород городить! Есть куда более соответствующее смыслу слово "Кондиция", пока иное не пришло на ум. Оно гораздо точнее отражает суть информации выдаваемой этой точкой подключения! **Выдается информация о текущей технической исправности устройства в процентах!** "Техническое состояние", "Исправность". За неимением свободного места для длинных вариантов приходится искать короткие варианты.
Но "статус" это из другой оперы. Статус чего? Статус, как что? 

Now
`<connection.conditionout>condition_out</connection.conditionout>`
Need
`<connection.conditionout>Кондиция_из</connection.conditionout>`
Maybe
`<connection.conditionout>Исправность_из</connection.conditionout>`

P.S. Give this post to your russian translator.

**Comment by MaaiG** [comment]
`<connection.conditionout>condition_out</connection.conditionout>`
as
`<connection.conditionout>состояние_выкл</connection.conditionout>` - it's horrible. Nothing like that.

Но народ, зачем огород городить! Есть куда более соответствующее смыслу слово "Кондиция", пока иное не пришло на ум. Оно гораздо точнее отражает суть информации выдаваемой этой точкой подключения! **Выдается информация о текущей технической исправности устройства в процентах!** "Техническое состояние", "Исправность". За неимением свободного места для длинных вариантов приходится искать короткие варианты.
Но "статус" это из другой оперы. Статус чего? Статус, как что? 

Now
`<connection.conditionout>состояние_выкл</connection.conditionout>`
Need
`<connection.conditionout>Кондиция_из</connection.conditionout>`
Maybe
`<connection.conditionout>Исправность_из</connection.conditionout>`

P.S. Give this post to your russian translator.

**Comment by MaaiG** [comment]
`<connection.conditionout>condition_out</connection.conditionout>`
as
`<connection.conditionout>состояние_выкл</connection.conditionout>` - it's horrible. Nothing like that.

Но народ, зачем огород городить! Есть куда более соответствующие смыслу слова "Кондиция" и "Исправность", пока иное не пришло на ум. Они гораздо точнее отражают суть информации выдаваемой этой точкой подключения, а также назначение других строк отвечающих за этот же параметр! **Выдается информация о текущей технической исправности устройства в процентах!** "Техническое состояние", "Исправность". За неимением свободного места для длинных вариантов приходится искать короткие.
Но "статус" это из другой оперы. Статус чего? Статус, как что? Report your status? Ну нет, это уже больше похоже на англицизм.

Now
`<connection.conditionout>состояние_выкл</connection.conditionout>`
Need
`<connection.conditionout>Исправность_из</connection.conditionout>`

Кроме того, в `мониторе состояния` этот параметр вообще показан как "Прочность"!
![Image 002_21-31](https://user-images.githubusercontent.com/93348499/147779158-e345dfde-9a4d-4ce0-9e68-23c320d1f968.png)

А также не стоит забывать о таком же назначении пункта в редакторе (в окне настроек компонентов и других объектов)
`<sp.item.condition.name>Состояние</sp.item.condition.name>`
Видимо везде стоит использовать слово "исправность".

P.S. Give this post to your russian translator. :)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/88cdd5e1b7b9264936375f96c844e79d652408ce

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
