### ISSUE TITLE
Dedicated servers have no cap on MaxPlayers

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#71]
Although not harmful I cannot think of many computers able to handle 64+ players.

The client hosting is limited to 16 players, making this at the very least inconsistent.

**Comment by Crystalwarrior** [comment]
Honestly tho why not keep it?
It'll be useful for some stress tests when more optimizations come along

**Comment by Regalis11** [comment]
I agree with Crystalwarrior. If someone wants to run a server with an excessively high number of players for whatever reason (stress testing, or maybe they just have a beefy computer and a really fast internet connection), I see no reason to have a hard-coded cap to stop them. In the non-dedicated servers however I think it makes sense to restrict the setting - being able to set the cap to 16+ via the UI would give the impression that it's something you can do without problems (although, maybe the cap should be unrestricted even in the normal game when editing the config files directly?).
