### ISSUE TITLE
Add One or Some Lovecraft Elements to Barotrauma- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#710]
I don't mean magic, since Barotrauma is scientific, but a monster being slightly similar to Lovecraft's universe elements. Maybe an artifact making players forcefully lose control over characters, after being too close to it for too long. Player can still regain control over that character, if rightful chemicals are used or a station is being entered.

Why Lovecraft:
Because Barotrauma is a co-op video game with high difficulty level. The best way to win is to cooperate and Lovecraft's universe does the same thing.

**Comment by Regalis11** [comment]
Coming up when we finish the ending of the campaign! ;)
