### ISSUE TITLE
PUCS suit does not provide a low O2 warning and drains O2 tanks while in an oxygenated environment

### ISSUE THREAD

**Issue by TimFragmagnet** [Regalis11/Barotrauma#7104]
- [x] I have searched the issue tracker to check if the issue has already been reported.
No relevant results upon searching for PUCS

**Description**
As per the title, the PUCS suit does not present the player with a low oxygen warning when low on oxygen.

Also as per the title, the PUCS suit drains oxygen tanks while in an oxygenated environment despite having the ability to breathe from the environment O2 when available.
The PUCS suit does properly allow the player to breathe environment O2 without an oxygen tank installed.

**Steps To Reproduce**
Put on the PUCS suit with an oxygen tank in it, and wait in the ocean for it to run out

Put on the PUCS suit with an oxygen tank in it, and wait in the sub for it to run out

**Version**
0.15.12.0 Windows

**Additional information**
It is possible that both of these issues are by design, but it would at least be nice QOL to see the PUCS O2 tanks not drain while in an otherwise oxygenated room. I'm honestly fine with not having a low O2 warning as the low O2 screen effects are sufficient enough warning for me.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b8c56124be838eec39f477cb2397076ff9ac8733 and https://github.com/Regalis11/Barotrauma-development/commit/f2390fe5c369e4b4169ff7124e03ec6d93f00d56

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
