### ISSUE TITLE
Alien blood refuses to combine.

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#7106]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alien blood will not combine

**Steps To Reproduce**
try to combine alien blood, which promptly fails

**Version**
stable, windows10

**Additional information**
i tried to break down a pulse laser box to combine it with another one, i was then saddened by the fact i cant combine alien blood, and as such, wasted 2 boxes of ammo.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6144d94f9bdd07156eb8791755e8d92b99b77945

**Comment by Rokvach** [comment]
No issues, closing.
