### ISSUE TITLE
[AI] Bots know how to use Scooters for outside exploration, but will not equip them on their own

### ISSUE THREAD

**Issue by Cusuno** [Regalis11/Barotrauma#7108]
- [✔] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While experimenting with Bots for outside exploration after the recent update in a singleplayer campaign, it turns out they are actually capable of using underwater scooters when they have one in their inventory.

This makes them a more valuable asset for tasks outside the sub.
However, when ordering bots to follow you outside the submarine, they will only equip the necessary diving suit and nothing else, resulting in them always staying behind when heading out with players wielding scooters.
In singleplayer this can be circumvented by switching characters and giving the bot a scooter manually.
In multiplayer however, the only way to access a bot's inventory is by making them unconscious, which makes them retaliate as a result.

**Steps To Reproduce**
 - Spawn a charged scooter inside the sub
 - Order the bot to follow you and head outside the sub
 - The bot will swim towards you without a scooter, despite one being available at the sub

**Version**
v0.15.12.0

**Additional information**
This is more of a feature suggestion, but I would highly love to see a "Collect This" command for bots, similar to the "Ignore This" command in order to prepare them appropiately for outside travel, especially when playing in multiplayer.

**Comment by itchyOwl** [comment]
Not implemented. We've been planning on giving a new "prepare" order and introducing a proper way to give items to the bots. I think this scooters should be taken into account there too.

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development#1101.

**Comment by Rokvach** [comment]
Closing.
