### ISSUE TITLE
Engineer Talent Bug (All Seeing Eye)

### ISSUE THREAD

**Issue by TrueDARK** [Regalis11/Barotrauma#7111]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"All Seeing Eye" talent breaks being able to take additional talents by not giving you points until you have leveled up 4 times, in which you are given 1 point, and can select 4 talents and spend only 1. After which, talent points are given as normal.

**Steps To Reproduce**
1) Be Engineer. (2) Reach Level 4 and take All Seeing Eye. (3) Reach levels 5, 6 and 7 and not be able to get Talent Points, but are able to select talents as if you can buy them. (4) Reach any level higher and receive talent points again, but 4 for 1, and fix it
**Version**
0.15.12.0 Windows 10

**Additional information**
Seems to me like the game thinks since All Seeing Eye grants you 3 talents without giving you Talent Points, that you have a negative point value, although it doesn't show that, and thinks you owe it 3 points. Could be as simple of a fix such as having the All Seeing Eye talent give 3 points, and just not mention anything about it. Probably another way to go about it, but that would be my smol brain fix

**Comment by GpointChen** [comment]
I also met this bug after applied the talent. As what I understand, there is a attribute named `additionaltalentpoints`  in `character` tags in the `_CharacterData.xml` save file. Set the value as 3 (`additionaltalentpoints="3"` ) should save the problem.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75bf0c21611fdcaaa41ea7edb0635a3675153bd7

**Comment by Regalis11** [comment]
Still not fixed according to https://github.com/Regalis11/Barotrauma/issues/7416, moving back to todo

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9bbb8cdec6fbd854a1b139b31c281d69da878edd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by lkorczowski** [comment]
I don't know how it was fixed but here is an example of my engineer not being able to apply any new talent point

How to reproduce: 
- apply 4 talents points into Physicist
- apply 3 talents points into Electrician
- apply 1 talent point into weapons engineer
- apply 1 talent points to unlock the entire electrician three
- now any talent point left could not be applied in the remaining weapons engineer, both "reset" and "apply" are grey.

![Screenshot 2022-04-07 at 23 49 32](https://user-images.githubusercontent.com/15196605/162325836-44cc75de-6130-4dc8-aeb7-ba367947e5c6.png)
