### ISSUE TITLE
Pulse Laser does not have any penetration value ?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7112]
According to the changelogs the custom affliction `"burndamage"` used to allow pulse laser to bypass damage modifiers was removed, however looking at the current XML for pulse laser; `penetration` - the mechanic intended to replace this temporary workaround - does not seem to be applied to pulse laser at all, leaving the pulse laser now very ineffective against monsters with armor resistances compared to before this change.

Just to clarify if this is a **intentional balancing decision** - if a rather odd one - or an oversight as originally suspected?

**Comment by PokkeTigrex** [comment]
There was a commit that increased the pulse laser damage but removed penetration on Oct 17th.

**Comment by M61Dev** [comment]
This is intentional, since the laser now deals its own damage type against monsters (burn) which have unique own resistances for it. Though the exact damage values and monster resistances may need further tuning.

**Comment by Ek-Videogames** [comment]
Ah, I got the impression from the change history that "burn" damage was not allowing it to penetrate armor, hence the need for the custom "burndamage" affliction as a workaround.
