### ISSUE TITLE
Onpsl Rarctraurna just crashed.A uresh lepurl Ccrashiepurtl ().)uy') nas seved in lhe IuLl

### ISSUE THREAD

**Issue by aizuosi** [Regalis11/Barotrauma#7115]
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7452280/crashreport.log)
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7452283/crashreport.2.log)
![20211101175333](https://user-images.githubusercontent.com/93519146/139655079-726c40a6-85cb-4274-97d5-4186d61835a5.png)

**Comment by Regalis11** [comment]
Duplicate of #7020
