### ISSUE TITLE
Container OnBroken SE with a setvalue parameter affects item spawning after it breaks

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#7122]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
OnBroken SE with a setvalue parameter affects items that spawn afterwards

**Steps To Reproduce**
Create a SE to spawn an item in the reactor when it breaks, item spawn with condition set at 0 even when their spawn is delayed multiple seconds after the reactor breaks

**Version**
Windows release branch 0.15.12.0 revision 575e12eab6

**Additional information**
Issue wasn't there before the update

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. I tested this by adding a SpawnItem element to the OnBroken effect of the reactor as follows:

```
<StatusEffect type="OnBroken" target="This" FissionRate="0.0" disabledeltatime="true">
  <sound file="Content/Items/Weapons/ExplosionLarge2.ogg" range="8000" selectionmode="All" />
  <sound file="Content/Items/Weapons/ExplosionDebris5.ogg" range="8000" />
  <Explosion range="800" structuredamage="100" force="5.0" camerashake="200" flashrange="10000" flashduration="5.0" screencolor="255,255,255,255" screencolorrange="5000" screencolorduration="3.0">
    <Affliction identifier="burn" strength="200" />
    <Affliction identifier="explosiondamage" strength="50" />
    <Affliction identifier="radiationsickness" strength="50" />
    <Affliction identifier="stun" strength="5" />
  </Explosion>
  <SpawnItem identifiers="thoriumfuelrod" spawnposition="ThisInventory" />
</StatusEffect>
```

And the fuel rod did spawn in 100% condition after the reactor exploded. If you post the xml you're using here I can take a look and see if it's an issue with the way the effect is configured or a bug in the game.
