### ISSUE TITLE
Oxygenite Tanks do not get drained by gas vents in caves

### ISSUE THREAD

**Issue by TimFragmagnet** [Regalis11/Barotrauma#7125]
- [x] I have searched the issue tracker to check if the issue has already been reported.
Plenty of other oxygenite entries, none about this though.

**Description**
The gas vents inside of caves normally drain your oxygen supply while you are within their AOE, if you are breathing from an oxygenite tank, this does not happen, I imagine it is also the same if you are breathing from any other source of oxygen.

**Steps To Reproduce**
Breathe from an oxygenite tank while in gas vent gas.

**Version**
0.15.12.0 windows

**Additional information**
Honestly I'm unsure if this is an intentional feature or a bug, as it seems possible that it's just an oversight in the way the gas vent was implemented.

As a side note, it would be interesting if the PUCS suit had this as a feature, being immune to gas vent gas seems like it would be perfect for a hazmat suit.

**Comment by Rokvach** [comment]
This was originally intentional behavior, but no complaints as its better to keep it consistent, working correctly. Closing.
