### ISSUE TITLE
The harpoon gun is capable of holding 6 harpoons but only spawns with 5.

### ISSUE THREAD

**Issue by TimFragmagnet** [Regalis11/Barotrauma#7131]
- [X] I have searched the issue tracker to check if the issue has already been reported.
seriously how has this apparently not been reported

It has been like this for a long long time, The harpoon gun has a capacity of 6 harpoons, but the harpoon guns you find spawned in your submarine are only ever loaded with 5. Some say this is apparently intended.

If this IS intended I would like to know why as I'm honestly just curious as to why it has been like this for so long.

The stun gun is the same way, can hold 2 stun darts but only spawns with 1.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bff8a80c4969f4082ab6c30877f5183a5f781420

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
