### ISSUE TITLE
Pirate crew knows where hostile intruders are when they shouldn't.

### ISSUE THREAD

**Issue by TimFragmagnet** [Regalis11/Barotrauma#7135]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**

In short, if you do damage to the pirate crew from within their submarine, while none of them can see you, even if that damage instantly kills the target, the entire crew now knows where you are.

---
Upon doing assorted tests to see whether or not it is possible to complete the pirate mission without alerting a single enemy, I have come across the bug wherein if you deal damage to a member of the pirate crew while they are otherwise unaware of your presence within the sub, every single member of the crew will become aware of your exact position, even if no one should know where you are.

The simplest example is with a grenade, if you open a ladder door while no one can see you through it, drop a grenade down, and close the door before anyone sees you. Anyone killed by that explosion will alert the rest of the crew that there is an intruder, despite the fact that they are dead.

Putting explosives in a detonator and killing them with it does not cause this to happen.
So yes, it is currently technically possible to complete the pirate mission via very loud stealth, yes this includes having them not get activated by your submarine getting too close.

**Version**
0.15.13.0 unstable Windows

**Comment by Cusuno** [comment]
From what I have experienced, stealth gameplay is straight up impossible with bots in general - not just pirates.
They immediately know when and where to fix devices, are capable of instantly locating leaks, and as soon as a hostile entity enters the sub while a bot is in the "Fight Intruders" order, they will instantly know where the enemy is.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3f3cae6cdb90cc03657d8cff31f09bc6b15962e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
