### ISSUE TITLE
Medic bug(tries to heal "husk infection resistance")

### ISSUE THREAD

**Issue by BruhWhyIAmHere** [Regalis11/Barotrauma#7137]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Medic tries to heal resistance to husk but can't and just stay near me

**Steps To Reproduce**
Just use antibiotics and then bug will appear 

**Version**
v.0.15.12.0 Windows

**Additional information**
Maybe this bug appears when I have gene only

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/98be27b19993cf2d8dcb368a326aaefde9a43586

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
