### ISSUE TITLE
Monitors Displaying Warning About Approaching Abyss- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#714]
Some players do not understand why does their submarine explode. We can make navigation terminal, sonar monitor and status monitor display warning about approaching the abyss once submarine is at depth of 1850 meter or more.

**Comment by thegrb93** [comment]
I thought the rushing water and shaking screen made it obvious enough.

**Comment by thegrb93** [comment]
Maybe a warning on the nav terminal would be good enough.

**Comment by rico6822** [comment]
Some people believe shaking is done by game lag, that's what is that for.
