### ISSUE TITLE
Annoying Audio I can't seem to get rid of.

### ISSUE THREAD

**Issue by DimensionalDrift1** [Regalis11/Barotrauma#7147]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've been playing a campaign with my friends and noticed a seemingly new ambient sound after reaching the Europan Ridge. It plays every couple seconds. It's very annoying to me for whatever reason, so I tried getting rid of it. It wouldn't go away, even after bottoming out the volume sliders, and I can say for certain that it's coming from the game. My friend said he heard it every so often, but not as commonly as I do.

Here is a clip of the audio: https://www.youtube.com/watch?v=VmjvtyWCX1M
The clip does have other sounds in it, notably the sonar, but it's not that. If I had to describe it, I guess I would say it's a weird droning sound. I haven't played since I got that clip, so I haven't had any opportunity to get one with less noise. I'm also aware that there has been a patch since I last played, but I'm going to post this as I don't see any fixes/changes related to my issue.

**Steps To Reproduce**
I have no idea what causes this, and it just happens whenever I play the game.

**Version**
Windows 10, v0.15.12.0

**Comment by Regalis11** [comment]
I'm pretty sure this is one of the biome ambience loops that were added in the previous update. There was an issue in v0.15.12.0 that caused its volume to not be affected by the audio settings, which caused it to be much louder than it should: https://github.com/Regalis11/Barotrauma/issues/7070
