### ISSUE TITLE
[BUG] Monster loot teleporting between corpses

### ISSUE THREAD

**Issue by Gabreski** [Regalis11/Barotrauma#7148]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i kill a group of monsters and pick up the loot with left click, shift-click or ctrl-click the loot is teleporting to another corpse. Even after doing it once i can repeat this action by putting blood back into crawler and picking it up with left click, ctrl or shift-left click only for it to appear not inside my inventory but inside the mudraptor next to crawler  (doesnt work from mudraptor to crawler in this one case). 

**Steps To Reproduce**
Kill a group or swarm of crawlers or other monsters and try to pick up all the loot with left click, shift-left click or ctrl-left click and the loot will teleport to another corpse.

**Version**
Now happened in v0.15.13.0, I encounter this bug ever since i got the game on 11th July 2021. My operating system is Windows 10 Home

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/90ef918ccb1a9edef29378417e25a75a7b4ddbd3

**Comment by ekqvist** [comment]
Thanks for taking the time to close this, but we'll keep it open until it's been through QA

**Comment by Rokvach** [comment]
Tested, haven't seen this happening, seems to be working correctly. Closing.
