### ISSUE TITLE
Deconstructor destroys items inside toolbelts (if DC output is full)

### ISSUE THREAD

**Issue by sublettj** [Regalis11/Barotrauma#7149]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deconstructing a metal crate, storage container, or toolbelt containing items destroys some/all of the items.  If there are no open spots in deconstructor output, all items are destroyed.

**Steps To Reproduce**
Fill deconstructor output with items.  Place metal crate/storage container/toolbelt containing items in deconstructor.  Deconstruct the container.   If there are not enough spaces in output for container's items, they will be destroyed.  Deconstructing a full toolbelt/container with no available output spots will delete all contained items, and only generate organic fiber/steel bar.

**Version**
0.15.13.0 Windows

**Additional information**
Edited to include testing on more container types.

**Comment by sublettj** [comment]
![20211102143117_1](https://user-images.githubusercontent.com/71276779/139924809-7a194dea-52d8-4e0d-83ab-a4501fc0d4ce.jpg)

**Comment by sublettj** [comment]
Although this *could* be by design, I feel like it isn't since the deconstructor dumps overflow during normal operation.  Expected behavior would be dumping the contents onto the floor.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0df00d95ce900a7110ca5efedd0f73f906fb814f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
