### ISSUE TITLE
Make Red Text Display Itself in Front of Nuclear Reactor When Submerged- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#715]
Not all the players understand, that to make nuclear reactor work under water it needs 3 fuel rods at once to be inside. This red text displays information about a need for 3 fuel rods to make it work. It is the same kind of text, that displays on insufficient skill level to do something.

**Comment by Regalis11** [comment]
Not needed anymore because the reactors no longer cool down underwater.
