### ISSUE TITLE
Merging item with a stack of damaged items will change a stack to a single item

### ISSUE THREAD

**Issue by EtiamNullam** [Regalis11/Barotrauma#7153]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Merging item with a stack of damaged items will change a stack to a single item.

**Steps To Reproduce**
1. Place stack of full oxygen tanks in a container in some distance to reactor.
2. Overload the reactor so it explodes.
3. Notice stack will have its condition reduced and displayed (make sure its not completely destroyed).

![image](https://user-images.githubusercontent.com/10875340/139964084-558cfa50-d441-4420-8ba6-1bced6d95ff6.png)

4. Notice you can extract single item from the stack (which seems like a correct behavior).
5. Notice that merging item with full condition with the damaged stack will turn it into a single item.

https://user-images.githubusercontent.com/10875340/139965655-58197ad6-a3c4-4d66-9ce2-d80e4ca6462a.mp4

6. Notice how merging item with not full condition will glitch the stack - it will appear full but moving it around will just move single item while reducing stack condition.

https://user-images.githubusercontent.com/10875340/139965669-89ba2743-aa23-4683-ba1f-f1be1f301705.mp4

NOTE: no modifier key is held here.

**Version**
v0.15.13.0
Windows 10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/342df5273f5f1fe802e390091a552deae5771e90

**Comment by Lithosagym** [comment]
Tested, can no longer fully stack a reduced condition stack with a full condition stack, fixed.

**Comment by Rokvach** [comment]
Closing.
