### ISSUE TITLE
Hulling issues in subs/wrecks

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7154]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The hulls of vanilla subs/wrecks around glass / curved/sloped pieces is sometimes placed poorly - hull extending beyond the shell hitbox, causing gaps to not quite form properly, leading to issues like:

a) cutting the wall not causing breaches
b) the breach being unboardable or very difficult to board from the outside (player and AI)

Subs it's on:

1. Kastrull command room 
![image](https://user-images.githubusercontent.com/5103517/140016504-100f06f0-75fb-456a-9f45-7f41e34648de.png)

2. Hemulen  command

![image](https://user-images.githubusercontent.com/5103517/140016517-ded0d952-6068-440c-937a-a142771345f7.png)

3. Selkie Command
 
![image](https://user-images.githubusercontent.com/5103517/140016533-c724f9c1-1505-41f6-904d-42b51b7407c7.png)

4. Hemulen Wreck 
![image](https://user-images.githubusercontent.com/5103517/140016549-1de9221a-3aa9-4971-b6bb-faa5c3f79872.png)

5. Kastrull Wreck
![image](https://user-images.githubusercontent.com/5103517/140016565-2bdd9f1f-d0d1-4c5a-b1c3-e1cf532d33ea.png)

**Steps To Reproduce**
1. plasma cutting/breaching/boarding these areas from the outside

**Version**
0.15.13 

**Additional information**
Preferred fix would be collision boxes that match the shell curve (though that would slightly break many existing subs, maybe)
but otherwise making the hulls be as much inside the hitbox as possible would be pretty good (example below) 
![image](https://user-images.githubusercontent.com/5103517/140016739-98cd7a30-71cd-4e5b-a935-6e93ae27c193.png)

**Comment by itchyOwl** [comment]
For information on how to fix it, see  Regalis11/Barotrauma-development@#2031.

**Comment by itchyOwl** [comment]
Addressed (finally) in Regalis11/Barotrauma-development@ac8d7bd (dev). Couldn't repro any issues with Hemulen or Selkie (possibly fixed in #8842), although the hulling isn't optimal. Found and fixed issues on Kastrull, Kastrull_Wrecked, and Venture (had to replace the front window with two pieces).

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/8650d05f17cee7897dfd96f0fbf0133fd6ad2f39

Only things I could find were:

- [ ] Hemulen - One wall can be destroyed without the shuttle leaking (Doesn't seem like it would effect gameplay much but it is an inside to outside wall):

![image](https://user-images.githubusercontent.com/29177976/210242640-5f830600-c7bb-4ada-87e5-e41f99690670.png)

- [ ] Venture - Rear section doesn't leak when breached at the middle and top diagonal walls:

![image](https://user-images.githubusercontent.com/29177976/210243530-8ef6f46b-bebf-4a47-9d51-e4a4ae367b4b.png)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@04fea39 (accidentally committed to bugfixes, cherry-picked to dev).

**Comment by itchyOwl** [comment]
Had to change that tail piece on Venture. Couldn't get it work.

**Comment by Tsunder** [comment]
if the hull doesn't leak when the shell is broken, doesn't that also mean creatures/humans can't swim from outside to in?

**Comment by NilanthAnimosus** [comment]
Tested Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/4daf3d5b3220b598adde534f883c56bbddef4d3b

they now correctly form gaps that flood (and can be swam through etc all the same)

But on the Helmulen the linked hulls have a different room name than the ballast, and they have not been factored in for the neutral ballast level (0.4620 is the new value, the nav terminal has a value of 0.4930):

![image](https://user-images.githubusercontent.com/29177976/212060160-7999c692-698e-48c6-9403-420448d02ef7.png)

Additionally the small linked hulls have a roomname of RoomName.SubTopLeft instead of RoomName.Ballast and another room may be named a ballast over an airlock (?) or other room name (As below that hull is one named airlock without a hatch/door).

![image](https://user-images.githubusercontent.com/29177976/212060715-e0faec79-afaf-4288-a199-b0cb5c721522.png)

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/ca67f2830907ec7178c6011c2a94ef11ba98d2ca

The room names seem correct on the hemulen now, as well as the neutral ballast level. However I am noting the new hulls added also do not have any ambient light settings set - not sure if this is worth fixing but you can tell how extremely dark it is ambient lighting wise without that:
![image](https://user-images.githubusercontent.com/29177976/213198724-a38ea3c4-d844-4cb9-8b89-a376a0cfa928.png)

Additionally the top left smaller hull has no ambient lighting set as opposed to the top centre hatch and top right small hull from that which does:

![image](https://user-images.githubusercontent.com/29177976/213205086-72a2506b-50da-43d2-a29a-a7ae02773a60.png)

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/acd3623c058c74be8ae333e6733f8467f98eda1e, no issues found, closing.
