### ISSUE TITLE
Throwables thrown on button press in multiplayer, on button release in singleplayer/sub editor

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#7155]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Previously throwables were always thrown on button release. Now they're thrown on button press but only in multiplayer.

**Steps To Reproduce**
- Host a server.
- Enable cheats and spawn a throwable (tested with all grenades and nitroglycerin).
- Hold aim key.
- Hold shoot key. Previous behaviour would not throw the grenade before key release but current does.

**Version**
Windows 0.15.13.0.

**Additional information**
Behaviour reported as well on previous 0.15 version (but I didn't test it personally).

**Comment by Krzeszny** [comment]
@UzricRash I'd rename it to "Throwables are thrown on button press, previously on button release"

**Comment by UzricRash** [comment]
Mmmm I mean sure but the terminology is the one that the code uses (Throwable, Key.isDown, Key.isHit, etc).

**Comment by Rokvach** [comment]
Tested, the behavior is exactly the same in singleplayer and multiplayer. Closing.
