### ISSUE TITLE
[0.15.13] Can sell worn/equipped items from bots

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#7160]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It is possible that I can sell items equipped by bots like the engis hazmat suit.
Found out because suddenly my engi bot was naked.

Expected: Equipped items are protected from being sold accidently.

**Steps To Reproduce**
in Singleplayer:
Open trader
Sell stuff
Sell the worn items of any bot (not tested if MP player inventories arent included)

**Version**
[0.15.13] Win, Singleplayer, vanilla

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@525967b. Should have only affected singleplayer since selling from the sub isn't implemented for multiplayer yet.

**Comment by Lithosagym** [comment]
Tested, you can no longer sell items on crewmembers inside the submarine, fixed.

**Comment by Rokvach** [comment]
Closing.
