### ISSUE TITLE
Boarding axe and Assault rifle cannot be placed in storage while Autoshotgun, Rapid fissile accelerator and grenade launcher can be stored just fine

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#7161]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While playing, I couldn't help but get annoyed at the fact I cannot store boarding axes, an item which your character could carry easily around in their inventory, like harpoon guns. Heavy weapons like the Autoshotgun and the rapid fissile accelerator doesn't even have this problem despite being unable to be carried unless using the belt slot. The only method of reasonable storing boarding axes, as well as assault rifles which also have this issue (when the autoshotgun doesn't), can only be stored on weapon holders, an installation which subs don't often have all the time. This feels like more like an oversight than intentional design choice as its just does not match the behavior of other medium to large sized items.

![Barotrauma_wTJl6sUZr9](https://user-images.githubusercontent.com/85914375/140093310-92a4f269-9bcf-4b49-b635-b60ddb4905be.png)

**Steps To Reproduce**
Just try to store the axe and assault rifle

**Version**
0.15.13.0 Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7eae66478785405e436bcca9f003f853460b37d3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
