### ISSUE TITLE
Text "SkillName.engineering" not found 

### ISSUE THREAD

**Issue by DrViktor41** [Regalis11/Barotrauma#7162]
![image](https://user-images.githubusercontent.com/93672416/140120978-964db6bc-3b66-4a38-b208-3bcdd76a03a1.png)
it started with me and my friend after we arrived at the outpost. Its happens, when i hit enemy or healing sombody. How fix it? pls help

**Comment by ekqvist** [comment]
Duplicate of #7099. This was potentially caused by an outpost event giving XP for a skill that doesn't exist.
