### ISSUE TITLE
The spineling gene attack does not properly target hostile entities and thus fires in a random direction.

### ISSUE THREAD

**Issue by TimFragmagnet** [Regalis11/Barotrauma#7163]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I don't actually strictly understand how this gene is supposed to function, I do know it's not functioning properly though.

I believe the intended function of the spineling gene attack is for it to automatically lock on to a nearby hostile entity and fire upon it once the player presses the creature attack button. This is not properly happening. It would appear that the spines are technically acquiring a target, as the console does not provide a targeting error when something is nearby like it does when there isn't anything to target, but regardless of this, the spines fly off in a random direction, making the gene effectively worthless.

As a note, they do appear to try to target the player sub's hull and properly do sometimes it would appear.

There are also times where it looks like the spines want to shoot in the direction they're facing off of the player model but that direction gets inverted while diving.

And then there's the times where it shoots straight up out of the player's head or down out of their feet.

**Steps To Reproduce**
Give yourself spineling gene,
Spawn crawler in ocean
Attempt to shoot at crawler with nothing else nearby.

**Version**
0.15.13.0 Windows

**Additional information**
Also a good change would be for the spines to not actually fire unless they do have a target, or at the very least, target the cursor if they don't have a hostile entity targeted.

![image](https://user-images.githubusercontent.com/93403970/140168198-ae5f8ff8-5d29-4382-9e7f-629c464cbf33.png)

![image](https://user-images.githubusercontent.com/93403970/140168291-9d8a155f-8531-47c5-9b74-125bbe5653e3.png)

**Comment by Regalis11** [comment]
The spikes should actually just launch in the direction they're pointing towards (so you have to orient the character in a suitable way before firing), but seems like that isn't working correctly (possibly only in multiplayer)? Thank you for the report, I'll do some debugging!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd43e38e5eef3385198fba0c1216166d351fd285

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
