### ISSUE TITLE
Friendly Fire setting affecting talents that give bonuses to others crewmates

### ISSUE THREAD

**Issue by MRobinson12** [Regalis11/Barotrauma#7165]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While playing a campaign we noticed that when trying to use the talents to give temporary buffs to other crew mates - Commander, Enroll Into Clown College -  would not work and thus meant that we were unable to make the most of those trees. We uninstalled all our mods and it still wouldn't work, as well as start a new savegame just incase the previous was corrupted to no avail. Verifying our games reset our server configs so when we tried again it worked and turning off friendly fire stopped it working again so we think it's safe to say that's was the cause 
Additionally disabling friendly fire does not disable friendly fire but that's probably best to put down in a seperate issue tracker

**Steps To Reproduce**
1. Create a multiplayer session
2. Go to Server Settings > Anti-Griefing 
3. Disable "Allow Friendly Fire"
4. Load/Play a Campaign Mode
5. Attempting to buff a teammate using the commander perk ect. does not apply
6. (Additionally - Friendly fire still happens)

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using 
v0.15.13.0 Windows 10 (19043)

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d5d75a75ca912fecbc8681293dd86c2fb1c3886

**Comment by Lithosagym** [comment]
Tested, talent buffs with friendly fire disabled and disabling friendly fire itself properly work, fixed.

**Comment by Rokvach** [comment]
Closing.
