### ISSUE TITLE
Cigar and Captain Pipe provide effectively 0 psychosis resistance

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7166]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since Psychosis Resistance decreases at 1/second, the 0.1 increases of Captain's Pipe and Cigar are virutally non-existant.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.13

**Additional information**
captain's pipe actually has a very minor gain, since it gives 0.1 per frame it's used, rather than 0.1 per second. but it's still basically nothing.
Further, 10 psychosis resistance is incredibly ineffective, due to ${math}.
(... captain's pipe tobacco effectively has zero mechanical value (and is outclassed by cigar in every way lol))

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60779abac48e2bdcf71a62bad7682a641b8c08b4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
