### ISSUE TITLE
Beacon Missions Break Multiplayer

### ISSUE THREAD

**Issue by Pinkyyyy** [Regalis11/Barotrauma#7167]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As soon as people started going into the beacon the whole server would get desynced people would get disconnected etc, and it would just mess everything up. We tried to two this several times, it seems like the beacon mission would break it. We also had another mission while doing this one, if thats important.

**Steps To Reproduce**
Go to a beacon and go inside it.

**Version**
Windows v0.15.13.0

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid that I couldn't get this to occur. Do you happen to remember what kind of error messages you got when you entered the beacon? Or even better, if you still run into this, a screenshot of the error(s) would be very helpful.

**Comment by Pinkyyyy** [comment]
I personally didn't enter the beacon, some of my crew did that. I as host stayed on the ship, as soon as they got in they all started disconnecting and having server issues no matter where they were. This happened several times, one time they managed to actually fix the beacon and then issues started happening, another time issues occurred as soon as they entered it. I do have a event error log file in my ServerLogs if that helps
[event_error_log_server_Strix_2123.log](https://github.com/Regalis11/Barotrauma/files/7490910/event_error_log_server_Strix_2123.log)

**Comment by Pinkyyyy** [comment]
My crew was the one that went to the beacon. Here is a log file of one of the players that were at the beacon, the desync starts happening at the end.
player1 is the player who sent me the log file, player4 is me aka host
[Pinky_Time_2021-11-03_2225_names_redacted.txt](https://github.com/Regalis11/Barotrauma/files/7492619/Pinky_Time_2021-11-03_2225_names_redacted.txt)

**Comment by Regalis11** [comment]
No known steps to repro, closing
