### ISSUE TITLE
Make Characters With Insufficient Skill Level Still See Crafting Recipes- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#717]
Characters not having enough skill to craft something have blocked preview on crafting recipe. Same thing comes with submarine editor. I think it would be useful in submarine editor to see crafting recipes inside fabricators to adjust chemicals for crafting them in the nearby cabinet.

**Comment by BillCombs** [comment]
I agree with this, it would be pretty handy to know what things are possible to craft with the materials you have when you are playing as a captain and want to order a mechanic to craft something. That way you wouldn't have to memorize every possible recipe.
