### ISSUE TITLE
Tiger Thresher genes / Pressure Stabilizer uses room oxygen

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7170]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Tiger Thresher genes at its full capacity (100%) still uses up room oxygen and oxygen items in diving masks / suits. This also happens with the chemical Pressure Stabilizer. User doesn't drown if submerged under water whilst under the effect of any of these, so oxygen need removal works. A workaround is to wear an empty diving suit, but it constantly beeps. Also notice how you get a "Low Oxygen" affliction with any of these in a room without oxygen and the accompanying degraded vision. 

**Steps To Reproduce**
1. Spawn gene splicer, and tiger thresher genes.
2. Inject yourself with genes and watch room oxygen.
3. Add water to room and dive under, confirm no need for oxygen.
4. Spawn diving suit with any oxygen item inside, confirm usage of oxygen.
5. Remove genes and please confirm above steps with the pressure stabilizer instead of tiger thresher.

**Version**
Latest Unstable, WIndows 10.

**Additional information**
A combination of the genes and chemical had no noteworthy interaction on the oxygen usage.
Tested with PUCS suit as well, it never beeps. Even in a room without oxygen or if it had an empty oxygen item inside it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/35aeb551ff144f5c5f98ffb7c0091c9171584f08

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
