### ISSUE TITLE
Buffs/Heals from honking horns affects enemies too

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7172]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Buffs/Heals from honking horns affects enemies too

**Version**
0.15.13.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f121ccfb2f864cf8c78648a2279fecf7bc3ff1df

**Comment by Lithosagym** [comment]
Tested, clown power healing no longer affects enemies, confirmed fixed.

**Comment by Rokvach** [comment]
Closing.
