### ISSUE TITLE
ItemContainer variables apply to SubContainer

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7173]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It isn't possible to hide items in ItemContainer but don't hide them in SubContainer, and vice-versa.
It also isn't possible to have different `itempos`, `itemrotation` and other such variables for SubContainer.

**Steps To Reproduce**
1. Add `hideitems="false"` to Cargo Scooter's SubContainer.
2. Put a battery in primary and something in secondary slots.
3. All items are still hidden.

1. Have a different `itempos` and `itemrotation` in SubContainer than ItemContainer

**Version**
v0.15.13

**Comment by Regalis11** [comment]
I'd consider this a feature request: these are properties of the component itself, not the subcontainers, so they can't be modified individually.
