### ISSUE TITLE
Spliced Bots Equip Diving Gear They Don't Need

### ISSUE THREAD

**Issue by soosgjr** [Regalis11/Barotrauma#7174]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots spliced with husk genes will still equip diving masks and suits, even when they're breathless or immune to pressure. When all oxygen runs out, they get stuck in the find safety mode.

**Steps To Reproduce**
1. Give a bot final stage husk infection and splice them with husk genes.
2. Assign an order to the bot that requires going under water or high pressure.
3. Observe the bot trying to find a diving mask or suit before proceeding with their order.

**Version**
Version 0.15.13 hotfix on Windows 10.

**Additional information**
Also effects bots spliced with perfect tiger thresher genes, sans the pressure related behavior.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddc98e896579ec4ce792c93423d28944a7c60158

**Comment by Lithosagym** [comment]
Tested, crewmembers with genes that remove the need for oxygen / have pressure resistance do not equip diving gear, confirmed fixed.

**Comment by Rokvach** [comment]
Closing.
