### ISSUE TITLE
Multiplayer - Game Desyncs sooner with big save files?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7175]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I was planning to run a campaign where every time we reach an outpost, that we would change submarine based on a randomizer. I purchased every vanilla submarines beforehand. The first round, we started with a dugong and it ran fine. We packed up some items into a crate when we got to a new outpost. After doing the usual stuff on the outpost, we switched over to Orca with items from our crate and Dugong in hand.

Upon loading the next level with the Orca, one player failed to join out of four. We started noticing wierd things happening, such as the crew list (pressing C) was completely empty, despite there being players. Pressing Tab to view the player list, only showed me and the disconnected player. Other players can still be heard in the game. I restarted the server, and we regrouped.

Reloading the save, the game put us back into the outpost, but with the Orca docked to it. We immediately start the level we were going to do again. It played out fine. We completed the mission and docked to the new outpost with six players in the game now.

We did the usual stuff on the outpost again, like buying and upgrading. We packed items into our transferable crate. We chose to switch to the R-29 Big Rig. Afterward, players were desyncing after the vote. I couldn't see the crew list, or player list. I couldn't even select a location or missions on the map anymore. I decided to end the campaign here.

**Steps To Reproduce**
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/7475465/Multiplayer.zip)
Play on this save file with 3~6 players. Every time you go to a new outpost, switch to a different sub that was already purchased. Then do the usual stuff in the outpost, like buying/selling/upgrading before you leave.

**Version**
0.15.13.0

**Comment by Regalis11** [comment]
Possibly fixed in Regalis11/Barotrauma-development@269ca20

**Comment by Kaillera** [comment]
After trying another bout of sub randomizer campaign, it is definitely a lot more stable. It does feel like there's still that one player that drops out every now and then somehow. There was also an instance of #7375, originating from this session.

**Comment by Rokvach** [comment]
I think this ticket is safe to close now, it seemed like a huge improvement whilst we were playing yesterday and I think the occasional disconnections were more of a hardware issue on the clients end

Closing as I did notice an improvement in here
