### ISSUE TITLE
When swimming into and out of hull objects, character becomes unresponsive

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7176]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When swimming in and out out of hull objects, the controlled player becomes unresponsive and will not move, and the player only regains control after the character is no longer in-between the objects will the player regain control

**Steps To Reproduce**
I have had this happen with regular hull objects, but I can consistently reproduce this issue by going though hull objects that have a destroyed section of wall on it.

**Version**
latest release

**Comment by Ek-Videogames** [comment]
It seems this behavior can also occur when passing a gap connection by climbing or descending stairs.

**Comment by JoneKone** [comment]
Yes, especially on laggy servers where the server doesn't agree to the position of client it makes loads of raggdolling.

**Comment by Regalis11** [comment]
I tried to repro this in various spots in Humpback, with high simulated latency, but no luck so far. :/

![image](https://user-images.githubusercontent.com/14351070/140931289-53da8659-637a-4452-88a9-79c2084b5ca5.png)

If anyone can find a spot where this occurs consistently, a screenshot might help us diagnose this. I wonder if it could be related to the amount of water flowing through the gap? Heavy water flow can temporarily stun and push the character back.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/82a4d1f89be94528994abe0fe53146be1e85c058

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
