### ISSUE TITLE
FPS Drops at navigational terminal

### ISSUE THREAD

**Issue by Slolwhat** [Regalis11/Barotrauma#7178]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When save has been loaded in multiplayer, anyone who's tried to operate the sub via navigational terminal, or jsut interract with it, fps dropped as low as 24(might go lower).

**Steps To Reproduce**
Interract with navigational terminal? didn't reproduce after lobby recreation.

**Version**
on mine host - Win10, current latest?  0.15.13.0
for everyone else in lobby - no idea, but issue reproduced for everyone

**Comment by Slolwhat** [comment]
it seems to be similar to this closed issue : https://github.com/Regalis11/Barotrauma/issues/6796

**Comment by Regalis11** [comment]
I suspect this happened as a result of https://github.com/regalis11/barotrauma/issues/7179: when that occurred, the blips would stay visible on the monitor for way too long, making the game render an enormous amount of blips which wrecked the framerate.

**Comment by etomarat** [comment]
I have same problem

**Comment by Ek-Videogames** [comment]
Reproducing this same sort of issue in singleplayer:
- for me only happens whenever the submarine is within' close vicinity of outpost 'dummy' docking port ( ~80m ) either departing or arriving at one.
- framerate drops to ~12 whenever navigation terminal is open, in spite of no increase in resource usage according to either in-game debug or external programs

**Comment by Leonidas-ai** [comment]
It only occurred for me when 100s of targets were on the sonar such as for an unusually large number of labelled monsters in one  area. Perhaps culling farthest labels would help when over the limit

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
