### ISSUE TITLE
Sonar overdraws info so there's nothing but white picture instead of obstacles\terrain

### ISSUE THREAD

**Issue by Slolwhat** [Regalis11/Barotrauma#7179]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Navigation Terminal sonar seem to be overdrawing over itself? after a while issue might disappear.(and might not disapper)

**Steps To Reproduce**
No idea, just at some point it gets weird and overwrites info on itself and it gets white.

**Version**
Win10, game - 0.15.13.0.

**Additional information**

didn't want to bother with video edit to cut 1 mb from file so its on puush-
https://puu.sh/In0a8.mp4

**Comment by Slolwhat** [comment]
was able to reproduce it and find the problem! it happens when someone has perk to repair an item above 100%, so, while its status is above 100% - the bug appears, once it drops to 100 or below - everything back to normal

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86c7a88822c8f08f8214740262a873ea6218c172

**Comment by Lithosagym** [comment]
Tested, navigation terminal no longer overdraws when repaired above 100%, fixed.

**Comment by Rokvach** [comment]
Closing.
