### ISSUE TITLE
Make Only Fractual Guardians Spawn Inside Ruins and Lower Their Maximum HP- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#718]
Most submarines don't have enough resources in multiplayer mission gamemode to deal with fractual guardians inside and not every crew spawns with medical doctor on board to craft morbusine for it.

**Comment by BillCombs** [comment]
You don't have to always kill them. Guardians are pretty easy to trick if you are working as a team. One crew member has to be distracting the guardians while the other is taking the artifact. And the distraction can be done through the walls, so you don't have to be inside of the ruins to trick them.

Dealing with them alone can be hard, but this is a team based game. A lot of tasks can only be done by multiple people(for example, you can't fix both junction box and engine as one person, you need an engineer and a mechanic for that).
