### ISSUE TITLE
variantof inherits items before <Override/> is applied

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7180]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
`variantof` inherits items before `<Override/>` is applied. This makes it impossible to use in mods that override items. 
I don't know about `inherit`, haven't tested that one.

**Steps To Reproduce**
1. Override an item with a change that's easy to spot
2. Try to use `variantof` to create an item from the modded item. It will instead inherit the original.

**Version**
v0.15.13

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f532e1c9ee2178ba691bae5f7cf45c8c080477d9

**Comment by Krzeszny** [comment]
That was quick! I also found out that `variantof` _most likely_ gets applied correctly if the parent item that uses `<Override/>` is in the same XML file. But not if the parent is in a different file. Just FYI.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
