### ISSUE TITLE
Gun holding positions and muzzleflashes v2: shotgununique aimpos, grenade launcher explosion & barrelpos

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7182]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
`shotgununique` a.k.a. Boom Stick has the same wrong holding animation as the Riot Shotgun as reported in #7118
![Barotrauma_eat85YUQBk](https://user-images.githubusercontent.com/10529134/140424207-233b26cf-4896-4f6d-b6d0-a31583116ed1.png)
Grenade launcher has a weird explosion effect with a shockwave (seen below) and a misplaced `barrelpos` (muzzleflash, also seen below):
![Barotrauma_6j2WgerwJo](https://user-images.githubusercontent.com/10529134/140424462-d17e9ea6-53cd-4977-a681-d5de9ae206ed.png)

**Steps To Reproduce**
Spawn `shotgununique` and `grenadelauncher` with some `40mmgrenade`s.
Additionally, spawn `smgunique` with `smgmagazine`.

**Version**
v0.15.13

**Additional information**
`smgunique` a.k.a. Deadeye Carbine has a slightly misplaced muzzleflash but it's not very noticeable
![Barotrauma_xJ172d7K0P](https://user-images.githubusercontent.com/10529134/140424868-f0157414-f8c6-46bb-ad9f-7bef282706d7.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/39355c782c7db4c7085d0baa2b93e5af2ec1ff29

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
