### ISSUE TITLE
Lock command persists after exiting editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7183]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Lock" command persists client side after leaving editor, and joining a multiplayer game
results in the client seemingly rapidly switching between moving and being still (nav terminals will flicker between displaying 0/0 and actual velocity)
visually it's extremely disorienting as well because of camera jitter.

**Steps To Reproduce**
1. open sub editor
2. enable cheats, "lock"
3. enter multiplayer, spawn in

**Version**
0.15.13

**Additional information**
Workaround is to go back to main menu and (un)lock. restarting barotrauma also works.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a6b0422e0cb32c5cd069690a7346f8fa7036e08f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
