### ISSUE TITLE
The number of missions given by outposts does not scale with the Max mission number set by campaign setting+talents. Need to outpost scum to fill up on missions.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7185]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The amount of missions we get from outposts does not scale with the Max mission setting and talents. It makes players outpost scum (redock to them multiple times) to fill up on missions before actually leaving.

**Version**
~0.15.13.0

**Additional information**
There's also a lack of having duplicate mission going in one route. It would be interesting to have to terminate multiple mudraptor nests or crawler swarms.

**Comment by Regalis11** [comment]
We're doing some cleaning on the repository and closing low-prio tickets we most likely won't be addressing at least for the game's full release.
