### ISSUE TITLE
Auto Fill in sub editor doesn't work for new items from latest update

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7186]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Auto Fill should fill an empty item when you get in-game, Revolver gets filled with Revolver Rounds, Headsets, and Scooters get filled with Battery Cells, and so on but this doesn't work for the following items:

Cargo Scooter (no battery cell)
Auto-Injector Headset (no battery cell)
Alien Pistol (no alien power cell)
Handcannon (no handcannon rounds)
Autoshotgun (no shotgun shells)
Assault Rifle (no assault rifle magazine)
Rapid Fissile Accelerator (no fuel rod)

**Steps To Reproduce**
Spawn any of these in sub editor, and make sure Auto Fill is checked in the Item Container category.

**Version**
Latest Unstable, Windows 10.

**Additional information**
![Screenshot 2021-11-05 153700](https://user-images.githubusercontent.com/69410159/140530386-871d12c0-9463-43f9-ac2a-452cd5197dbb.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f0636d57a926bf249faa27a4d669ccb7c34cec8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
