### ISSUE TITLE
Bots can't clean up any of the new talent items

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#7188]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots can't clean up any of the new talent items

**Version**
v0.15.13.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a80ed442e3295c9f803d56a5c10a36c92dabc739

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
