### ISSUE TITLE
the game crashes immediately after starting

### ISSUE THREAD

**Issue by Kahless1980** [Regalis11/Barotrauma#7189]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when I start the game on steam using the "play" button. A window appears where I should choose whether I want to start barotrauma or have the bonus content. he changes to "pause" and after a few seconds who changes back to "play". 

The Barotrauma task appears briefly in the Task Manager, but it is also closed again for a short time. Even if the Windows defender is deactivated, the same error still happens. 

I also made a video of the desktop where you can see the error, even if there is an older version of the game, the error is still the same.  Here the link :  https://youtu.be/Kb1A0ag60Mc 

**Steps To Reproduce**
1. Run Steam
2. Select "Play"-Button of Barotrauma
3. in the new open window, select run Barotrauma. not bonus content
4.  Few seconds later , the game was crashed or so what.
5. The "Stop"-Button switch to "Play"-Button back

**Version**
Which version of the game did the bug happen in. At all version since i buy the game (december 2020)

**Additional information**

**Comment by Krzeszny** [comment]
To clarify, does it run correctly if you don't press the Play button but start directly from the .EXE?

**Comment by Kahless1980** [comment]
so i tested it. It's the same mistake.
Started via the Barotrauma.exe in the ...\steam\steamapps\common\Barotrauma folder. in the task manager it swaps briefly with the background processes and then immediately goes away again. It is similar via the taskbar with a right click on steam and then barotrauma. Even running as administrator does not change anything.

I also started the delicated server and it look like good to run.

**Comment by Krzeszny** [comment]
Post your system specs and OS version.

**Comment by Kahless1980** [comment]
OS : Windows 8.1 Pro, 64-bit, x64-basierter Prozessor

System :
Prozessor : Intel Core i5-4690 CPU @3,5 Ghz 
RAM : 32 GB
GPU : Nvidia GeForce GTX 1070 8GB
Harddisk 1 for the OS : 256 GB SSD 
Harddisk 2 for Programs : 1 TB HDD
Harddisk 3 for Games : 2 TB HDD

**Comment by Regalis11** [comment]
Hello and thank you for the report!

Unfortunately I'm not sure what could be causing this. Your computer's specs seem more than enough to run the game. There are couple of things that you could check which might help us get to the bottom of the problem:
1. Make sure you have DirectX 11 or later installed and that your GPU drivers are up-to-date.
2. Go to the game folder (right-click the game on your Steam library -> Properties -> Local files -> Browse local files) and check if there's a file called "crashreport.log" in there. If there is, posting the contents here would help us a lot in diagnosing the issue.

Sorry for the inconvenience! :/

Potentially related ticket: https://github.com/Regalis11/Barotrauma/issues/3492

**Comment by Kahless1980** [comment]
So i was check the dxdiag. there are no problems. Then i look for windows update and install them.
the gpu drivers from nvidia at time 20.09.2021 version 472.12.
in the game folder of "Barotrauma" is no fils. i was search "cra*" they came some files, but i search to "cras*" is there nothing.

Here are a link to the "[dxdiag.txt](https://1drv.ms/t/s!AhKRfnwc-TVp6VncsPnvp-HEQejk?e=pfqiXy)"

**Comment by Kahless1980** [comment]
Hello,
it´s now 3 weeks ago, at your last post. 
Need you more info, too or is the dxdiag enough.
What info need you to have a chance to fix the bug?

**Comment by Regalis11** [comment]
Hi, I'm sorry but we still have no idea what's causing this. :/ Since you seem to have DirectX 11 installed, the issue has to be somewhere else. I'm not sure what kind of information you could provide us to help us fix this; the only thing I can suggest is giving a shot [at some common ways to fix launch issues](https://www.getdroidtips.com/fix-barotrauma-crashing/) and seeing if any of those help. If not, we encourage you to refund the game on Steam, because it is not in our interest any more than yours that you should keep a game which you are not able to play. The problems you experienced should provide ample grounds for a refund.

I'm sorry I can't offer more tangible help with the problem. :/

**Comment by Kahless1980** [comment]
Ok, i has refund the game by steam.
it´s bad that it not work, the game looks good and i whoud play it with friend.
