### ISSUE TITLE
Invisible second artifact after the update:Among the ancient

### ISSUE THREAD

**Issue by Phesaoof** [Regalis11/Barotrauma#7190]
**Description**
I was playing singleplayer, I got a missions containing artifact. When I played, I found one ruins spawn, but when I was going for the second one, signal was just in the open, I swam to it and it is invisible, but still there making a noise, I couldn't pick it up. Also I can drive a sub through it with no problems

**Steps To Reproduce**
Don't know if it would work, but start a map with 2 Salvaging an artifact missions, then go to the locations
**Version**
v0.15.13.0 Windows 10
**Additional information**
proof that I can drive through it
![Screenshot](https://user-images.githubusercontent.com/52252688/140559734-7f9f3203-0233-495b-8de6-77f75ac5f9b0.png)
.

**Comment by Regalis11** [comment]
I gave this a quick test but couldn't find any levels where this would've happen. If you still happen to have the save file this occurred in, or if anyone happens to run into this, sending the save here would help us a lot in diagnosing this!

Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
No known steps to repro, closing
