### ISSUE TITLE
Infinite free scrap in wrecks

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7192]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Placing an item (with an inventory) inside wrecks triggers Mechanic's talents for scrap (linked in info)
Works with portable pumps (multiple times) and detonator (once each) from what I've initially tested.
After obtaining scrap from the portable pump this way, you have to deconstruct and craft a new one.

**Steps To Reproduce**
1. Start a new campaign with a sub that has deconstructor and fabricator.
2. Select your mechanic and type: givetalent Scrounger and givetalent "Scrap Savant", then leave outpost.
3. Spawn a detonator and a portable pump.
4. Find a wreck, recommend using console command lighting and freecam, then teleport your mechanic inside.
5. Place the detonator and portable pump inside wreck and open them up, 0-2 scrap should have fallen out.
6. **Portable Pump only** Pick the pump back up with wrench and deconstruct it, then craft a new one, repeat from step 5.

**Version**
Latest Unstable, Windows 10.

**Additional information**
![talents](https://user-images.githubusercontent.com/69410159/140597480-c5255999-20fe-4681-8c30-2377deb818bd.png)

Addendun: Multiple Mechanics can get scrap from a single portable pump / detonator if they also have the talents. 2 engineers = potentially 0-6 scrap.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/41f82c189f7a9a5fef16122fcec06bdb00031eb3

**Comment by Lithosagym** [comment]
Tested, you can no longer acquire scrap from placing a detonator or portable pump in a wreck, fixed.

**Comment by Rokvach** [comment]
Closing
