### ISSUE TITLE
Outpost reactor does not accept volatile fulgurium rods as fuel

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#7193]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Outpost reactors (*Content/Map/Outposts/OutpostItem.xml*) do not accept the new talent item volatile fulgurium rod unlike regular reactors (*Content/Items/Reactor/reactor.xml*).
This is an issue because some submarine editors like better the outpost reactor's sprite than the regular reactor's, and they behaved the same until now.

**Steps To Reproduce**
Just see the files' ItemContainers. You could also:
1. Open the sub editor.
2. Place both types of reactors.
3. Try to place the volatile fulgurium fuel rod in both of them.

**Version**
Windows 0.15.13.0.

**Additional information**
Easy fix, just copy regular's ItemContainer to the outpost's.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
