### ISSUE TITLE
[SUBMARINE] [TYPHON 1] Various issues with walls, sprite layers and hulls

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#7195]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
First Typhon has a lot of issues starting with internal hull-less area, unnecessary double walls and serious sprite depth issues.

1. Hull
There is hull-less area between electrical and closest to the airlock access shaft. This area can lead to flooding without external damage to submarine (due to accident's or griefing)
![image](https://user-images.githubusercontent.com/62324831/140615894-dba74d36-e2ae-4f65-b134-4267ecba6d39.png)

**Possible solution**
Extend the electrical room to top and right
![image](https://user-images.githubusercontent.com/62324831/140615991-dd9e34ef-cbb2-452d-b093-5d6987656f28.png)
 
2. Double walls
a. Double walls can be a problem for monster's AI. This also create issue in the armory when if top wall is breached armory will flood but there won't be visual indication of that because second wall is intact.
![image](https://user-images.githubusercontent.com/62324831/140616218-32d40cb9-610e-4a53-90a2-aa658cac93ca.png)

b. Wall between medbay and crew quarters has this issue and issue (https://github.com/Regalis11/Barotrauma/issues/4873) with possible undrainability.
![image](https://user-images.githubusercontent.com/62324831/140616327-3b63d61c-7801-46e4-8b09-0de6247bdd96.png)

c. Bottom walls can be removed and replaced with backwalls or other purely decorative supports.
![image](https://user-images.githubusercontent.com/62324831/140616373-e54c3d19-7406-44a5-bc4e-ef1247d67ec1.png)

**Possible solutions**
a. Double wall between gunneries can be replaced with a single wall (without cables) with size of 1.150 and Y texture scale of 0.5. Some hull rearrangement is also advised
![image](https://user-images.githubusercontent.com/62324831/140616239-b25f2ab3-f12b-46f4-80d8-f85c67f650a3.png)

b. Wall between medbay and crew quarters can be made like this and decorative wires and/or pipes can be added if necessary
![image](https://user-images.githubusercontent.com/62324831/140616486-d127bd44-1bd8-44ca-a360-a10aa905db69.png)

c. Bottom walls can be removed and replaced with backwalls or other purely decorative supports.
![image](https://user-images.githubusercontent.com/62324831/140616430-0c073c02-26f0-4391-b415-f0437944c29a.png)

3. Sprite layering issues
a. Central Access Passage, right side has serious sprite layering issues regarding props and background walls, they have identical depth values which make them look like this
![image](https://user-images.githubusercontent.com/62324831/140616557-af2279de-f952-4e30-afe3-ead7cc8c9dfc.png)
b. Central Access Passage, right side also has some strange looking prop placement, particular vents, columns, supply cabinet and loose panel.

**Possible solution**
a. Set props like cabinets, columns, etc. to have sprite depth values lover than background wall
b. Rearrange decoration placements or even replace "Outpost Airlock Wall" background with something else, possibly some solid background
![image](https://user-images.githubusercontent.com/62324831/140616764-44783cd7-8c7b-43e8-bd23-fb3a1b747383.png)
![image](https://user-images.githubusercontent.com/62324831/140616788-8b31ec61-751c-46f5-86ef-596f7d46bd85.png)

**Steps To Reproduce**
Inspect Typhon in subeditor or in game. Layering issue may look different for different users.

**Version**
Stable, 0.15.1.0

**Comment by ubertpendragon** [comment]
https://github.com/Regalis11/Barotrauma/issues/4873

Typhon 1 is maybe the most outdated submarine: undrainable rooms, none of the hulls are aligned with floors, legacy sprites, broken gaps

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3958/commits/4682c3d562e62ab969475725c0f397feee26dcaa
