### ISSUE TITLE
PUCS doesn't protect against radiation

### ISSUE THREAD

**Issue by iKirian** [Regalis11/Barotrauma#7196]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
PUCS doesn't protect against map radiation in multiplayer campaign, even with or without Hazmat Suit added. Oxygen tank doesn't affect this situation.

**Steps To Reproduce**
Wear PUCS, stay on region of map campaign with Jupiter radiation presence, observe how Radiation Sickness rate would grow on character.

**Version**
0.15.13.0 Windows 8.1, Windows 10

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ec6d6d44b8b69e3e60012ce56e4dec2178181fd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
