### ISSUE TITLE
Status monitor won't draw the submarine blueprint correctly.

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#7197]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On submarines that may have moving parts like on a fan-made Orca 2 with a retracting/extending nose cap I've designed, I noticed that the status monitor doesn't draw the blueprint of the submarine correctly. 

Nose cap retracted (it hasn't moved at all yet.)
![image](https://user-images.githubusercontent.com/51425624/140619298-aa30e4f7-098a-4aeb-b70a-6fa40f0dd5e8.png)
![image](https://user-images.githubusercontent.com/51425624/140619459-8bffbc20-cd32-4a2f-9046-f43ccec83c21.png)

Nose cap extended
![image](https://user-images.githubusercontent.com/51425624/140619307-2da7d998-8f6b-48af-a3bd-d3192493da50.png)
![image](https://user-images.githubusercontent.com/51425624/140619480-bacab000-2b57-44ca-b876-d45c81c9531c.png)

Nose cap retracted (from being extended) **this is where the issue is, since there's a discrepancy between the images**
![image](https://user-images.githubusercontent.com/51425624/140619333-ccd3d57f-d767-483b-bc1e-b89355c48647.png)
![image](https://user-images.githubusercontent.com/51425624/140619509-6f3204e4-b0bc-4ca8-8a47-a8379d4bee74.png)

**Steps To Reproduce**
It seems like this happens because the status monitor only draws the submarine blueprint when the docking ports get close enough for their proximity prompts to activate, and they start "magically" moving towards each other to dock. It seems like the practical solution would be to draw the submarine blueprint after both docking ports are attached and fixed.

**Version**
v0.15.13.0
Windows 7 Professional

**Additional information**
orca 2 sneak peek when

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d44c2c2eb6662af693fdad5dbf1915a527a1f5f4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
