### ISSUE TITLE
[Bug?/Question] Custom made outpost modules completely misalign in level generation

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#7199]
As the title states, my attempts to create custom outpost modules from custom made structures hit a wall, despite modules built almost 95% like vanilla ones, with door-w-buttons and hatch-w-buttons at every "socket" where the next room should connect, and linked wall pieces that should be removed if the room have connections, on level generation, doors became misaligned severely, and wall pieces were not removed making custom outposts basically broken, i don't know how Hardcoded level generation is and does it even allow a possibility of creating custom outpost modules that aren't made from vanilla parts
that's why i put a "question" in the beginning since i'm not sure where to categorize this issue

Game version: 0.15.13.0

attaching screenshots
![Barotrauma_2021 11 07-00 11](https://user-images.githubusercontent.com/74479084/140625573-1437c0f3-83f3-4820-9bf4-78796e803dce.png)
![Barotrauma_2021 11 07-00 11_1](https://user-images.githubusercontent.com/74479084/140625574-8ab59936-dd7d-47aa-aae6-3e9298d995ea.png)
![Barotrauma_2021 11 07-00 11_2](https://user-images.githubusercontent.com/74479084/140625575-e2f5dcf3-b64d-427a-acea-e1ee4af2ccf2.png)
![Barotrauma_2021 11 07-00 12](https://user-images.githubusercontent.com/74479084/140625576-150c16a1-007c-45c0-b61b-250a5e75a82e.png)
![Barotrauma_2021 11 07-00 12_1](https://user-images.githubusercontent.com/74479084/140625577-5d5ddec9-1175-440c-a0f8-b435a0589211.png)
![Barotrauma_2021 11 07-00 13](https://user-images.githubusercontent.com/74479084/140625578-a56ff1e2-020f-4ce1-bf34-00d4da2281be.png)
![Barotrauma_2021 11 07-00 13_1](https://user-images.githubusercontent.com/74479084/140625579-bd2f4a0d-110a-4b69-8b21-54357c9dac17.png)
![Barotrauma_2021 11 07-00 13_2](https://user-images.githubusercontent.com/74479084/140625580-df87bab9-37e9-462f-a658-82a99309bfc4.png)
![Barotrauma_2021 11 07-00 13_3](https://user-images.githubusercontent.com/74479084/140625581-6f7543e0-bcdd-41b5-a30a-6e619df1b7e3.png)

**Comment by Regalis11** [comment]
I believe this happens because these modules have been marked as hallway modules. Hallways are a bit of a special case: they're pieces used between the actual "rooms", and their length can vary according to the layout of the outpost. The generator also scales the structures (or moves if they're non-scalable) in the hallway according to the length.

I'd recommend removing the "hallway" flags from those modules and making a couple of simpler and smaller modules to be used as the hallways.
