### ISSUE TITLE
Syringe gun creates ghost syringe when shot

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#720]

**Comment by rico6822** [comment]
You mean a syringe going through target?

**Comment by thegrb93** [comment]
No, it creates a clientside syringe object that can't be picked up

**Comment by NilanthAnimosus** [comment]
Its more explainable and a common bug regarding item position syncing, This makes it sound extremely unusual but what it really should be is item positions are not synced correctly.

My mod actually contains code to try to workaround / fix this issue, but I don't know its cause.

After a submarine crash, or a weapons shot or something else, the client can predict something else than the server. The server should send the item position and i'm fairly certain it probably does or tries to - such as diving suits sliding down a corridoor. But its common to find trying to pick these objects (such as to wear them, or recollect used ammunition) simply drops them immediately again.

given you can keep pick-up dropping the object to "Move" it along a room or corridoor, eventually it sticks / picks up, which point I recognize the difference between the server-side position and client-side position, and its considerably larger than the distance an object can move before sleeping, potentially the distance of an entire aegir hallway.

**Comment by thegrb93** [comment]
That makes sense

**Comment by Regalis11** [comment]
I think this is fixed by the recent item syncing changes (similar to what Nilanth did in his mod).
