### ISSUE TITLE
No 'condition_out' pin on empty loader base.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7200]
There is no condition pin on the turret loader base like there is for the other loaders. This creates issues with sub editor as we can't link condition to the same kinds of systems and have them work when a turret is swapped into a empty base slot, in addition if a turret with loader is uninstalled to return it to a base loader that wiring connection is then lost.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e38c7e61805fb2c31b1fae486eeecfd1ecfae465

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
