### ISSUE TITLE
XML : Detonator's contained item position isn't centered right.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7202]
Stuff placed in detonators has had the wrong item position for a verrrrry long time now.
![image](https://user-images.githubusercontent.com/55356135/140635931-a9a8a9d8-8c88-4fd3-89e1-21f36a6eef0f.png)
Container has `itempos="0,0"` `( May genuinely be a carryover from legacy back when item origin was center not top-left corner? )` so its just a simple task to set it to something like `itempos="20,10"` or whatever.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6d56b6c3014e9e404ad16cd21f717217c5bab246

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
