### ISSUE TITLE
No condition_out on Fabricator, Medical Fabricator, and Deconstructor.

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#7205]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The fabricator, medical fabricator, and deconstructor have no condition_out pins, which is a bit weird considering that every other machine and even doors have that pin.

**Steps To Reproduce**
Check the items' connection panel in the sub editor or in game.

**Version**
Windows 0.15.13.0.

**Additional information**
The shuttle battery has a condition_out pin but is not needed since the shuttle battery has no Repairable ItemComponent. Although if it happens to be a design choice or something planned for the future (swappable batteries?) then it's okay if it stays I guess.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/80b1e304613e309dd599beaff240115c30aa904c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
