### ISSUE TITLE
Crash related to Genetic Research Station Deconstruction and Power

### ISSUE THREAD

**Issue by JustCoda** [Regalis11/Barotrauma#7206]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had forgot to power the research station on my sub. I hosted a game for friends on a non dedicated server. I attempted to deconstruct an unidentified genetic material with stabilozine before I had found out that I forgot to wire it in editor. So while the deconstruction process was stalled by lack of power I tried to connect it to a junction box and the server crashed. Tried repeating it two more times with same result before cancelling the deconstruction, emptying the table and then wiring. Which worked without crash. 

**Steps To Reproduce**
1) Start campaign with research station not connected to power
2) Insert unidentified genetic material and stabilozine
3) Start deconstruction and do not cancel at "insufficient power"
4) Wire from research station to Junction Box
5) Wait 30 seconds

**Version**
Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Additional information**
Last server crash log attached.

[servercrashreport (4).log](https://github.com/Regalis11/Barotrauma/files/7492412/servercrashreport.4.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5806329534920ef495019ed7a0be4d469f7b0243

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
