### ISSUE TITLE
Revolver ammunition is too expensive relative to other ammunition

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7211]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Alternative title**
Other ammunition is too cheap relative to revolver ammunition and explosive harpoons.

**Description**
I'm not claiming that there's something wrong with damage. Only the costs are relatively unbalanced.

My spreadsheet (please pay special attention to column **W**). 
![brave_KM6iTsZlFE](https://user-images.githubusercontent.com/10529134/140924606-89bbc0fc-6f51-44f2-a4ed-0dcc6496bc24.png)
(Note: DPS for explosive ammo is simulated for Humans/Husks, not just theoretical)

Facts for revolver ammo:
- Revolver ammo (depleted, too) is exactly **2 times more expensive per damage** per shot than Assault Rifle ammunition and 2.5 times more expensive per damage than SMG ammunition.
- Revolver ammo has 40% per-second stunlock, rifle has 104%, SMG has 86%, shotgun has 107%.

**Version**
v0.15.13

**Spreadsheet**
https://docs.google.com/spreadsheets/d/16kbeZaq8rprirMFH405HplRjSakshxaQFP6N7HBaJ6M/edit?usp=sharing

**Comment by LePiromano** [comment]
i disagree

**Comment by HeatedWafflez** [comment]
i disagree

**Comment by Krzeszny** [comment]
> i disagree

i disagree with your mom

**Comment by Regalis11** [comment]
I disagree as well: I think it's fine that the more "high-level" weapons are more cost-effective to use than the captain's starting gear.

**Comment by Krzeszny** [comment]
> I disagree as well: I think it's fine that the more "high-level" weapons are more cost-effective to use than the captain's starting gear.

Good point, I won't argue.

By the way, @Regalis11 I've noticed that Handcannon is very, very cost-inefficient, as you can see in the chart. I don't want to open another issue because there are far too many, so can we elaborate here?

For example, SMG has 0.4 cost/damage but handcannon has 1.22 which results in 3 times worse economy.
Does it stunlock? While yes, the shotgun also stunlocks and has 0.5 cost/damage.
Handcannon deals less DPS than the SMG. 
While it has more penetration, SMG with depleted fuel ammo has slightly better anti-armor economy while having the benefit of dealing radiation dagame and almost 3 times better raw cost/damage. Basically, compare the DPS columns and the price/damage columns between the Handcannon, the SMG and the riot shotgun.

Handcannon only has good DPS when dual wielding but the ammunition economy remains bad (uses Titanium-Aluminium alloy), so why would you use it over the shotgun, SMG or the assault rifle?

**Comment by LePiromano** [comment]
I still disagree

**Comment by Krzeszny** [comment]
> I still disagree
Fine, at least explain why. I don't understand why you'd use the handcannon over the SMG, especially with dep fuel.

**Comment by strategsc2** [comment]
> > I still disagree
> 
> Fine, at least explain why. I don't understand why you'd use the handcannon if you have SMG ammo (esp. dep. fuel), shotgun ammo or the AR. It's just inefficient to use TiAl and Physicorium given the DPS.

Except killing guardian with SMG/AR is a pain, while handcannon just obliterate them. I think the main reasons for it is high initial burst, armor penetration and in some encounters it's a little bit easier to land all your shots to the weak points. The thing is, during first 1.45 seconds of the combat you'll actually shoot twice, and with something like quickdraw you'll end up with a decent dps at the start.
Also, you can enjoy the convenience of having a toolbelt, as opposed to AR/AS)

As for the price I wonder how exactly the ammo economy was calculated. If you used prices is marks, than I think this metric is flawed because right now recourse availability is way more important than money.
