### ISSUE TITLE
Transport mission payout too high

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#7213]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Balance: Transport missions for 500Mk x 25 crates is way too high. Even with just 10 crates its already 5000Mk which you get for a Moloch mission.

Expected: Either significantly lower per-crate payout or significantly lower max amount of crates (e.g. 5 crates max?).
Lower per-crate payout = more max crates, higher crate value = lower max amount of crates?

**Steps To Reproduce**
./.
**Version**
v0.15.13

**Comment by CurePindal** [comment]
> 
> 
> but R-29 and Berilia can really only make good money this way...

Sorry, but I dont understand? Do you say its "the only way a transport ship can make money" or only the transport ships really profit from this?

Either way I politely disagree. Theres also missions that offer 25 crates max for 250Mk each. Thats also insane income.
Especially in perspective with the change that we can now take up to 2 missions. And yes, I even already saw a 250Mk- and 500Mk-transport mission on the same route.

And with the addition of the Uber-like personal transport missions the overall options for income have blown any kind of economical-vs.-difficulty balance out of proportion. Well, granted, that balance was already messy before.

**Comment by Krzeszny** [comment]
A solution would be to set a maximum reward for a transport mission that doesn't depend on the number of crates but literally on the reward.

**Comment by Woestel** [comment]
Instead of making transport missions worthless, I think it would be better to adjust the rewards for transporting on known routes.

**Comment by JeroonBosch** [comment]
Main issue was there was one transport mission that could give 12500Mk in one run. Fixed that in feature/economy-balancing.
https://docs.google.com/spreadsheets/d/1XgKkI7YrA2ZBn66zNyGPs0zo_zkS2akMXw93TWL0XXI/edit#gid=1899075539 see here for actual amounts... they don't look too out of line now

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
