### ISSUE TITLE
[0.15.x] Colonisation vs Research outpost conflicting for a Research Station

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#7215]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The colonisation system changes stations at the probably worst times possible!
Three times we tried to reach our first Research outpost this update to use a research station.
Three times in a row the dreaded colonisation mechanic flipped the stations to cities right in front of us.
We reached the 3rd biome without getting access to a research station yet. We gave up.

Expected: I dont know - meaningful colonisation?
Overhaul the dreaded colonisation system. It drives us nuts since the Radiation update. Its wrong all over the board.
- with radiation enabled colonisation usually happens way behind you.
- since 0.15 colonisation suddenly morphs stations (science stations) you need/want ahead of you.

**Steps To Reproduce**
./.

**Version**
0.15.x

**Comment by Jallu** [comment]
@danielasteljoki check the stations

**Comment by danielasteljoki** [comment]
Should be fixed with upcoming update. Every colony has a research module with a research station.
