### ISSUE TITLE
Spamming ragdoll button negates fall damage

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#7217]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Spamming ragdoll button while falling still makes you fall, but negates any fall damage.

**Steps To Reproduce**
1. Find somewhere where you would get fall damage.
2. Jump.
3. Spam space.
4. Watch not receiving any fall damage.

**Version**
Latest version, Windows 10.

**Additional information**

*Spamming space*
https://user-images.githubusercontent.com/36804725/140792885-cc23ca1c-9466-45b6-a6ce-1ddac9c608d4.mp4
*Not spamming space*
https://user-images.githubusercontent.com/36804725/140792938-a7d3736a-fb83-449c-be0d-03eeecbde510.mp4

**Comment by ubertpendragon** [comment]
As a side note, fall damage is also really low. 
It's not something you notice inside a regular sub, but in "adventure" maps high falls don't hurt much

**Comment by MateusJK15** [comment]
Fall damage in general is really low, even of you fall from a height of 8 oxygen generators it barely hurts, 1 morphine and you're fine.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eff6dbfd02902356a6d555ca16fe7c0c92ee9912
