### ISSUE TITLE
Fabricator eats oxy bottle when upgrading diving suits

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#7219]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fabricator eats oxy bottle when upgrading diving suits

**Steps To Reproduce**
1. upgrade a diving suit with an oxy bottle to a higher tier suit
2. suit is crafted, oxy bottle vanishs

expected: Oxy bottle is either in the newly crafted suit, or oxy bottle is dropped into the output slots (e.g. like a battery from a headset in the deconstructor)

**Version**
0.15.13, win, singleplayer, vanilla

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/33616e61e777acfa69fcb4f9ea9d40a93b6e30a9

**Comment by Rokvach** [comment]
Tested, the oxygen tank drops from the fabricator now, we could improve this behavior at some point to transfer the tank directly to the new suit or place it in a free slot inside the fabricator. But for now the fabricator doesn't consume the tanks anymore so the issue has been fixed. Closing.
