### ISSUE TITLE
[Suggestion] Extra parameters in lobby for Mission and Traitor mode

### ISSUE THREAD

**Issue by Pinkyyyy** [Regalis11/Barotrauma#7220]
Would be nice if there could be extra parameters for the Mission and Traitor mode.

For Mission mode let us adjust how many missions we want to do, not only 1.

For Traitor mode it would be nice if you could set how many traitors you'd like to have, which jobs cant be a traitor (eg captain) and like a setting for if you'd like for mission to continue after the traitor has won, or end. If missions continues the traitor becomes a spectator. And like difficulty of said traitor missions, and how many tasks etc. Maybe also a setting if you'd like non-traitor players to see a notification that the Traitor has completed a task. (With delay) Something to let non-traitors be aware of the progress the Traitor is making somehow?

**Comment by Regalis11** [comment]
Thanks for the ideas, these would definitely be nice additions to the game! However, we use the issue tracker for bug reports, ideas and suggestions should go in the [GitHub discussions](https://github.com/Regalis11/Barotrauma/discussions).

**Comment by Pinkyyyy** [comment]
oh sorry, should i repost there or?
