### ISSUE TITLE
disco lamp

### ISSUE THREAD

**Issue by pofigist1** [Regalis11/Barotrauma#7222]
**Description**
i play only in sub editor, and in new version of game i saw what you added ability to change color of POWER EATING lamp. 
if (lamp 'condition' is off) or ((it is on) and (power is ok)
then all is good, but if i change color on lamp and electrical grid is too weak, lamp start flashing, every time it got a new color.
it so sad, pls fix it
**Steps To Reproduce**
take one battary(empty), powering lamp, taking one Oscillator element on square mode, one signal check element with two different color output and here we go
**Version**
win10
bara 0.15.13.
![20211108235014_1](https://user-images.githubusercontent.com/57585733/140816813-ef9ea8f0-54be-490d-aa38-ab507d04b4b8.jpg)
![20211108235026_1](https://user-images.githubusercontent.com/57585733/140816814-459973d1-ed9c-4c9e-88c0-08c35717ef9b.jpg)
![20211108234951_1](https://user-images.githubusercontent.com/57585733/140816816-cc0e6e3d-9edd-4621-a986-5fb7f5b75a50.jpg)
![20211108235007_1](https://user-images.githubusercontent.com/57585733/140816819-53ceeba7-550e-462b-843f-de9b298e8582.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/99a3df6d5b8a899c757a192a199aae9358772bad

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
