### ISSUE TITLE
Shuttles attached to shuttles appear on sonar in PvP

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#7226]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have a shuttle attached to a shuttle, it will appear for the enemy team on the sonar, giving away its location
![image](https://user-images.githubusercontent.com/73229309/140832592-4f47f967-1335-4fb0-a1ea-25148aea0e4b.png)

**Steps To Reproduce**
1. Download the sub: [PvP sub with boarding shuttle.zip](https://github.com/Regalis11/Barotrauma/files/7500665/PvP.sub.with.boarding.shuttle.zip)
2. Start a PvP server using the "**PvP sub project**" submarine
3. You can see the shuttle "boardingpodclaw" appear on radar

The "boardingpodclaw" is a shuttle attached to the boarding pod, itself attached to the main sub

Also see https://github.com/Regalis11/Barotrauma/issues/5297

**Comment by Tsunder** [comment]
only separatist's shuttleshuttle appears on sonar for coalition

coalition's shuttleshuttle doesn't appear on separtists end.

![image](https://user-images.githubusercontent.com/5103517/140877429-892ad25f-9cff-4917-af2a-e73ee30e826a.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/36f80404571fb20a445831006a24089a7dd686f5

**Comment by ubertpendragon** [comment]
Tested on the same sub, on both sides, seems fixed

**Comment by Rokvach** [comment]
Closing.
