### ISSUE TITLE
Some Images on Barotrauma's Main Download Page Are Outdated- Community Related

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#723]
Sonars are blue now, not green and job preference setup in multiplayer is no longer yellow, brown (other colours).

**Comment by BlueTheKing** [comment]
Duplicate of #684

**Comment by Regalis11** [comment]
Duplicate of #684

**Comment by rico6822** [comment]
Oh I forgot I already reported it before.
