### ISSUE TITLE
Didn't funny bug in human.xml

### ISSUE THREAD

**Issue by hnappinn** [Regalis11/Barotrauma#7231]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The burn has type="burn", but in VitalityMultipier only damage sooo... I think you understand what's wrong

**Steps To Reproduce**
Look to this

**Version** Windows.

**Additional information**
![Screenshot_1](https://user-images.githubusercontent.com/59388392/140947723-054b3109-6e0d-4493-af3a-bd8c1c2f2d75.png)
![Screenshot_2](https://user-images.githubusercontent.com/59388392/140947744-452b6a30-4668-4e9e-ad8f-3042d8927e6f.png)

**Comment by Regalis11** [comment]
This is intentional: these modifiers are only supposed to affect the physical damage types like internal damage, lacerations, blunt force trauma and such.

**Comment by hnappinn** [comment]
Okay

**Comment by hnappinn** [comment]
@Regalis11  I'm sorry to distract you, but I can't figure out how to solve one problem, can you please help? Why do I have broken afflictions on limbs in my mod. I'm not sure if it's a bug, but most likely it's a bug related to conditional sprite

![Screenshot_5](https://user-images.githubusercontent.com/59388392/140963942-f24f4390-a07e-4a5c-9025-34f9e3af5c2e.png)
![Screenshot_6](https://user-images.githubusercontent.com/59388392/140964366-6c62ac42-5b2a-4724-8198-fa1c1fc9bb17.png)
![Screenshot_7](https://user-images.githubusercontent.com/59388392/140964438-1dec7b01-c8bc-4a4c-8c3a-6a685cb774c7.png)

**Comment by hnappinn** [comment]
I also have a lot of changes on torso and head, but there is no conditionalsprite, and there it works fine

**Comment by hnappinn** [comment]
I found it seems to cause bugs
![Screenshot_8](https://user-images.githubusercontent.com/59388392/140966428-7e192009-d396-4ac3-b2f2-fb843df9bb27.png)

Strange why it breaks the affliction
