### ISSUE TITLE
Sometimes when an assistant with the Graduation Ceremony perk starts a new character as a mechanic, the assistant perks are not deleted

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#7234]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes when an assistant with the Graduation Ceremony perk starts a new character as a mechanic, there is a chance for the new character to keep all the old character perks. This results in a mechanic that has enrolled into the clown college, for example.
It's very difficult to replicate because it doesn't happens everytime, I do not understand what the preconditions are for the bug to happen.

**Steps To Reproduce**
1- Make an assistant character in campaign.
2- Give yourself 18.000 exp.
3- Unlock all the perk trees.
4- Create new character. The bug has been sighted when the new character is a mechanic, but maybe that is not the only affected target role.
5- Suicide the assistant and respawnnow. If the resulting character is still an assistant then (un)dock the sub from the outpost.
6- There is a chance that the resulting mechanic has all the old perks retained.

**Version**
Windows 0.15.13.0.

**Additional information**
Difficult to replicate, happened twice in a half an hour stretch of dedicated testing.

**Comment by UzricRash** [comment]
Further testing has reported the bug from assistant to captain. I no longer think the target role is relevant.

**Comment by Regalis11** [comment]
I gave this a quick test, but so far couldn't find a way to repro the issue. To clarify, did the talent menu actually display the assistant's talents as opposed to the the class you were playing as, or did you notice that you'd retained the talents based on their effects?

**Comment by Regalis11** [comment]
No known steps to repro, closing
