### ISSUE TITLE
`slotsperrow` isn't functional

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7236]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
`slotsperrow` or even `itemsperrow` appears to have no function. 
AFAIK it's supposed to define the shape of a container's UI.

**Steps To Reproduce**
For example, add `slotsperrow="3"` to toolbelt's ItemContainer

**Version**
v0.15.13

**Comment by Regalis11** [comment]
SlotsPerRow determines the _maximum_ number of slots per row, but with a low-capacity container the actual number of slots may be smaller.

`int columns = MathHelper.Clamp((int)Math.Floor(Math.Sqrt(itemCapacity)), 1, container.SlotsPerRow);`

ItemsPerRow determines the number of items to draw on the container per row, and only affects containers that render the contained items.
