### ISSUE TITLE
[Feature suggestion] Hacking / Handheld terminal

### ISSUE THREAD

**Issue by Thirty-Percent** [Regalis11/Barotrauma#7238]
Hacking could work nicely with the existing wiring mechanics, and gameplay options.

The most basic implementation of this would be doors, but it could be expanded to inverted pumps, buggy engines, exploding fabricators, maybe even unlocking talent items in a fabricator for a limited time, O² generator sending helium instead of O² and other goodies. 

Installations can be hacked individually, or, provided enough skill (or some minigame completion? *note below), the entire submarine may be accessed from a simple door button.
Easy hacks would include door control, lights control, temporary pump shutdown/inversion or nav terminal shutdown.
Medium hacks would include O² vent closure, remote wiring component setting, temporary remote nav or shuttle terminal control
Hard hacks would include airlock overrides, forced power overloads, unlocking secured containers, maybe remote access to the current station's systems (shop prices, reputation, O² generation...)

Hacking (skill?) wouldn't necessarily be for evil purposes; you could actually want to enable wiring component remote customization, or making it harder for others to hack you.

Hacking would require a handheld terminal of some kind.

Pirates (or drones? fractal guardians?) could board your ship, hack the doors and settle in your airlock access area. If you have a second airlock maybe you can swim around and engage them from behind, or if you don't, you could try to shut down oxygen vents in their room. Or pump water out, if they need water.

Wrecks could still be partially functional and have survivors. Some of them could try to hack your sub trying to get away, you could attack or try to hack them back and drown them. Being stranded in a wreck could be a game start option.

I hope this flood of thoughts isn't inappropriate, and I know this would be a major thing and would have countless implications. I just think it would fit very nicely with Barotrauma.

(*)About the minigame thing: thinking about hacking, made me think of a game called Duskers https://store.steampowered.com/app/254320/Duskers/
You command drones through a command line interface, typing orders to open doors, move, hack terminals, grab items etc. A similar thing (not the drones part, I mean the CLI) could be interesting. Hacking could also allow looting locked containers (in wrecks or in the current sub) and so on.

**Comment by ekqvist** [comment]
Hi! Thanks for the feature request! However, we try to reserve the issue tracker mostly for bug reports. Feature requests and ideas can still be discussed on GitHub Discussions.
