### ISSUE TITLE
Bots can not open custom doors with switches wired to the toggle open (when the switch is toggle off)

### ISSUE THREAD

**Issue by FLundin** [Regalis11/Barotrauma#7240]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI is unable to open custom doors where the door have a switch with mode (toggle off) wired to the doors toggle state

**Steps To Reproduce**
It appears when a switch with mode (toggle off) wired to the doors toggle state. I also seen it occur more often when the door mare 3 connections to its toggle state and sometimes with a mix between buttons and switches.
https://youtu.be/QO2Yf-WhY7w (sorry about the quality) So basically the doors that have the wire top on the UI connected to the buttons far away wont work for the AI. But if the top wire leads to the buttons right next to the door, then the AI can operate it.

**Version**
0.15.13.0 w10

**Additional information**
This bug report was described as something else but after more testing I come to other conclusions and have therefor edited the post.

Additions

(No longer relevant text below)
So I tried to replace the door with a regular scaled door. and the problem appears again.

I think I have determine the issue. It does not seam to have to do with upscaled doors, it have to do with multiple buttons wired to the door.

So for the door I have next to it on both sides wired custom switch (toggle off) for the players to use to operate the door. but I have also in a different location of the sub added a 3rd switch (toggle off). I tried to unwire the 3rd switch and the AI then managed to open the door.

So my new conclusion is that (which I didn't know before) is that the AI need a interface wired to the door to open (not only a WP which I first thought). So the problem is more that the AI does not realize it have a button/switch at the door (even tho there is one) and thinks is the far away located button they need to use, but can not reach, hence they can no operate the door. but when they wanna close the door, they seam unaffected by this issue all together.

(No longer relevant text above)

This seams to be more related to the switch in toggle mode off, being used to work as a button on a doors toggle state.

**Comment by FLundin** [comment]
So I tried to replace the door with a regular scaled door. and the problem appears again. 

I think I have determine the issue. It does not seam to have to do with upscaled doors, it have to do with multiple buttons wired to the door.

So for the door I have next to it on both sides wired custom switch (toggle off) for the players to use to operate the door. but I have also in a different location of the sub added a 3rd switch (toggle off). I tried to unwire the 3rd switch and the AI then managed to open the door.

So my new conclusion is that (which I didn't know before) is that the AI need a interface wired to the door to open (not only a WP which I first thought). So the problem is more that the AI does not realize it have a button/switch at the door (even tho there is one) and thinks is the far away located button they need to use, but can not reach, hence they can no operate the door. but when they wanna close the door, they seam unaffected by this issue all together.

**Comment by FLundin** [comment]
So I changed out the switches (toggle off) to buttons and the AI could open the door even with multiple wired switches (toggle off) on them.. so I don't know if this is a custom door problem or a switch problem....

**Comment by itchyOwl** [comment]
There's been a bunch of fixes to the bots using doors and buttons. Eg. I found out that they didn't always use the closest button and they also tried to use doors that were inside their theoretical reach but in practice behind another door.  I think those fixes have probably fixed this too. Requires testing.

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
