### ISSUE TITLE
AND Component with Non-Zero Timeframe Fires at Start of Round

### ISSUE THREAD

**Issue by jamsspinle** [Regalis11/Barotrauma#7242]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Non-zero timeframe attribute on AND Component causes unexpected output at start of round.

**Steps To Reproduce**
Using the sub editor, set up a test. Take an AND component and set its Timeframe attribute to a positive integer. Then, connect the SIGNAL_OUT of the AND component to a light's TOGGLE_STATE. Then, test the sub and see the light turn on and off for the length of the timeframe even though the AND component had no input during this period. This also happens at the start of a round.

**Version**
Version 0.15.13.0, Running on Windows.

**Additional information**
I have been trying to set up a two button launch system for a depth charge launcher, but the AND component causes it to launch any stored shell at the start of a round, despite no input.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7def14a23c52a5a177a96e9b706e8cb66bddac52

**Comment by ubertpendragon** [comment]
Tested with a 10 second timeframe on several components + tested on a sub that had a timeframe on round start
![image](https://user-images.githubusercontent.com/73229309/142504580-b1132cb8-c900-4db4-838f-b860ff7649c2.png)

Seems to be fixed, no longer getting signals

**Comment by Rokvach** [comment]
I think I'm still going to close this in favor of the new ticket, closing.
