### ISSUE TITLE
Memory component lock state isn't toggleable in editor

### ISSUE THREAD

**Issue by Dornam0930** [Regalis11/Barotrauma#7244]
Memory components have the lock_state pin, but don't have any way to manually toggle the state when in the ship editor.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/dd00193a3c2f9792117c1aa5e307605608a092c3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
