### ISSUE TITLE
Ruins generated partially outside of the level

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#7245]
**Description**
Ruins are generated partially outside of the level (inside the level ceiling):

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/aa650651-b295-486d-b813-443b5c31bed8)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/54611a90-d056-43c0-b158-5d1a9c447efb)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/df2a71d6-7390-4879-974e-802d43a89db1)

**Steps To Reproduce**
Quickstart using the seed given above.

**Version**
v0.15.13.0 Debug

Commit: https://github.com/Regalis11/Barotrauma-development/commit/d234453704fd2e1fb482985daa295e727c064389 (bugfixes)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e7c3f8e9e5e8a76ef67479bf507c77b743d82a75

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
