### ISSUE TITLE
Thermal artifacts are not suppressed by the transport case, except if the case is placed in a container

### ISSUE THREAD

**Issue by Thirty-Percent** [Regalis11/Barotrauma#7247]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Thermal Artifacts still trigger fires when not in water and contained in an Artifact Transport Case, despite  `<Conditional hastag="neq artifactcontainer" targetcontainer="true"/>` which all artifacts have. The other artifacts are suppressed properly (didn't test Nasonov)

However, placing the thermal artifact in the case, and then placing the case in another container (1), e.g. a supply cabinet, will prevent the fire from triggering.
(1): except for example portable containers (eg cargo scooter), or large steel cabinets **if** they're linked to a fabricator (tested on the humpback one). A large steel cabinet that's not linked to a fabricator will prevent the fire trigger.

Once `<Fire />` has been prevented this way, it won't trigger again until the artifact is taken out of the transport case.

**Steps To Reproduce**
Place a thermal artifact in a transport case that's not in water, wait 30 seconds, fire
Place the transport case in a container (1), wait 30 seconds, no fire
Take the transport case out of the container, wait 30 seconds, no fire
Take the artifact out of the case, wait 30 seconds, fire

**Version**
0.15.13.0

**Additional information**
(That being said, the case seems a bit OP / too easy to acquire?..)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3a1c84d019211848f7502c28eb353a77bea459ec

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
