### ISSUE TITLE
[WRECK] Wrecked charging dock can hold more than 1 battery per slot

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#7250]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wrecked charging dock can hold 8 stacked batteries per slot (32 batteries per dock) when it should hold only 1 battery per slot (4 batteries total)

![image](https://user-images.githubusercontent.com/62324831/141107753-f111a592-ce27-4a6d-85a3-78c65825ac7f.png)

**Steps To Reproduce**
In sub-editor or on any wreck try to fill wrecked charging dock with batteries

**Version**
Stable, 0.15.13.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/77ffca6415803736bc1f1d5a10e13163ac4ec178

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
