### ISSUE TITLE
Combat Medic's Too Fast for Its Own Good

### ISSUE THREAD

**Issue by soosgjr** [Regalis11/Barotrauma#7257]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a long-running campaign it's pretty easy to get a medic's medical skill well above 400 through the Advanced Splicing talent by the time of reaching the 4th biome. Combined with the Combat Medic talent this can result in such a movement speed bonus that the medic running at an auto-door will splatter themselves on it before it had a chance to open, resulting in tripping and some blunt trauma. The same happens with static walls. While annoying (and hilarious), it's still somewhat manageable for a human player, at least until their medical bonus gets way higher. However, it completely cripples the movement of bots, who'll wear their health down pretty quickly while throwing themselves across the room, so it could probably use a movement speed cap.

**Steps To Reproduce**
1. Play as a medic in single player on the Humpback.
2. Unlock the Advanced Splicing and Combat Medic talents.
3. Get your medical skill to 100 and its bonus to 350-400 through working with genetic material.
4. Start running towards a door that would normally open automatically.
5. Observe your medic doing their Wile E. Coyote impression, taking damage from colliding with the door.
6. Relieve the control of the medic to a bot.
7. Assign an order to the medic that requires running around the sub, like hull repair under crush depth.
8. Observe the bot throwing themselves across the rooms, into walls, and down stairs/ladders, gradually losing health.

**Version**
Version 0.15.13 hotfix on Windows 10.

**Additional information**
Might be the explanation for https://github.com/Regalis11/Barotrauma/issues/6788.

**Comment by Krzeszny** [comment]
This is more of a general issue because of the lack of a skill ceiling but could be fixed by limiting the maximum speed boost.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/6c3a73c5e31853c6b4e715beb624b6fe67dce9fb

**Comment by Lithosagym** [comment]
Tested, the movement speed bonus based on the talent is indeed capped, although the ai may still hurt themselves when sliding down ladders to the floor and running to an adjacent room due to getting off of the ladder too early. Main issue fixed.

**Comment by Rokvach** [comment]
I think that's a separate ticket entirely, but closing this one.
