### ISSUE TITLE
Bots Don't Want to Wear PUCS

### ISSUE THREAD

**Issue by soosgjr** [Regalis11/Barotrauma#7258]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots seem to treat PUCS like any other diving suit, dropping it whenever they're not under pressure or low on oxygen, even though its description imply a purpose seemingly fit for general use.

**Steps To Reproduce**
1. Equip a character with PUCS.
2. Assign the character an order that normally shouldn't affect outerwear usage, like manning a turret.
3. Relieve the control of the character to a bot.
4. Observe the bot immediately tossing the PUCS to the ground.

**Version**
Version 0.15.13 hotfix on Windows 10.

**Additional information**
Might be related to https://github.com/Regalis11/Barotrauma/issues/7104, don't know if the draining of oxygen determines the bots' behavior.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6248fcf26ddbc90bc370580ea460312ac6bf8984

**Comment by Lithosagym** [comment]
Tested, bots no longer take off PUCS, confirmed fixed.

**Comment by Rokvach** [comment]
Closing.
