### ISSUE TITLE
Husk Pressure Immunity Takes Precedence Over Abyss Diving Suit

### ISSUE THREAD

**Issue by soosgjr** [Regalis11/Barotrauma#7259]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The pressure immunity of the final stage husk infection overrides the pressure immunity of the abyss diving suit, causing characters to explode while wearing the suit at ~6km instead of the expected 10km.

**Steps To Reproduce**
1. Give your character final stage husk infection and splice them with husk genes, to remove the time limit.
2. Equip the character with an abyss diving suit.
3. Dive below 6km.
4. Observer the character dying from the pressure.

**Version**
Version 0.15.13 hotfix on Windows 10.

**Additional information**
The explosion happens immediately without the zoom-in warning and slightly before than it should to someone wearing a combat diving suit, at ~5945m. I don't believe magnitude matters for husk genes, but I've been using 18% ones for testing.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e03c57e279c7e626d4ad1687e5d699d1c9a716d5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
