### ISSUE TITLE
`variantof` attempts to open Sprites from an undefined path instead of the original folder

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7260]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**What should happen**
`variantof` should copy sprites from the original item's directory if a path isn't specified in the original item.

**What happens**
When an item has sprites without a defined path (which is very popular in vanilla files and in mods) and you create a variant of it in a different folder, it won't find the sprites.
Example errors:
![Barotrauma_8EmPflehmE](https://user-images.githubusercontent.com/10529134/141210949-f2d1a9de-12aa-4df4-bd82-2a8e45702209.png)

**Steps To Reproduce**
1. Create a `variantof="pulselaser"`
Pulse laser turret is just one of hundreds of items with undefined sprite paths.
2. Modify anything in it using <Override> tags in an example mod
3. Load the mod and a pulse laser turret

**Version**
v0.15.13

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ded801543900d558b85f8cb0792a356e27c82c8b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
