### ISSUE TITLE
Missing sprites cause exceptions/errors

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7261]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Definitely low prio.

As shown in #7260, missing sprites cause errors like this (are they called exceptions?) repeated 4 times in the console for each sprite
![Barotrauma_8EmPflehmE](https://user-images.githubusercontent.com/10529134/141211794-5bb5e405-2af1-4841-8465-5e732f03f2e4.png)

**Steps To Reproduce**
1. Have an item without a sprite or with a wrong sprite file name/path
2. Load that item

**Version**
v0.15.13

**Additional information**
The main problem with this exception is that it's hard to read, as it could be a one-line error but other than that items should have sprites by default. However, some modded items are supposed to have no sprites if they're designed to be invisible.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/9fdf1a837c6d4136aeb2efc8a7a71a1841c22572

**Comment by Lithosagym** [comment]
Tested, "sprite not found" errors are indeed more user-friendly (doesn't repeat it 4 times), confirmed working.

**Comment by Rokvach** [comment]
Closing.
