### ISSUE TITLE
Text display set_color socket does not work

### ISSUE THREAD

**Issue by Lvl2Pillow** [Regalis11/Barotrauma#7262]
**Description**
The text display does not seem to work with the color component. Unable to update the text color in-game.

**Steps To Reproduce**
I have a color component with the static value "255,0,0,255", which should be red. Its signal_out is connected to a text display on the set_color socket. However, the text color is still white (or whatever color was set from the editor).

**Version**
v0.15.13.0 revision 4e66dd7b5d
Windows 10

**Additional information**
N/a

**Comment by Regalis11** [comment]
The `set_color` input changes the color of the light on the display. We've added another input to change the color of the text, but it isn't included in the current public version yet.
