### ISSUE TITLE
Exit to lobby button is sometimes annoying.

### ISSUE THREAD

**Issue by OceanFish1** [Regalis11/Barotrauma#7264]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It's not a bug, but can we please get an option to add a promt when leaving to lobby (like leaving to main menu)? It happens sometimes that me or my folks (with admin perms) accidentally click "quit to lobby" that is placed nearly in the middle of the screen after pressing ESC instead of right mouse button to close certain things. Not like it causes some catastrophic consequences, but it can be annoying.

**Steps To Reproduce**
1. Forget about right mouse button.
2. Press ESC when you shouldn't to that.
3. Be surprised of the menu.
4. Accidentally click on the mouse.
5. Get sent to lobby without a warning.

**Version**
0.15.13.0. Windows 10.

**Additional information**
Really annoying.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e9790534d2139f5cabac0e04e04b8cce2ee51078

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
