### ISSUE TITLE
Stolen items lose their stolen icon when you undock from a outpost

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7268]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stealing items and re-docking to a outpost shows the items as if they aren't stolen, you can't sell them to the outpost store so they are still marked as stolen but just doesn't have the icon. Previously the icon showed up all the way to the next station over. 

**Steps To Reproduce**
Start singleplayer campaign and steal some items from the starting outpost, undock from the outpost and notice that the stolen icon vanishes from the items.

**Version**
v0.15.13.0
Dev branch with Release build
Commit: https://github.com/Regalis11/Barotrauma-development/commit/81a48601328ac8068a6efdc84fee639e4e1775c5

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/727509cb752df19680d478ead06e777e8907f7a5

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
