### ISSUE TITLE
Water Pits For Campaign Mode- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#727]
Water pits can be found in the most stations in Barotrauma. The player (or server's host) can decide to enter water pit, where submarine is submerged to use the water inside of it to flood submarine in order to rewire or edit content of submarine on the ceiling in a pit being always slightly larger, than submarine. The light from above is always in very positive condition to see submarine from outside. Flooding however is considered a secondary thing to do in a pit. The player can use time inside the pit to set railguns, personal equipment, pumps or rewire components for implementing new non-default functions.

Water pit is also having it's own docking hatch on the ceiling of it's icy crust to recharge batteries of shuttles. This requires credits to use. 100 credits after docking and 1 credit per every second should be enough, but you decide. If there is not enough credits to have shuttle docking for longer the shuttle will be forcefully undocked and docking hatch will be blocked by a horizontal blockade. If somebody is spamming docking in multiplayer host can always ban that person and restart pit to refill credits.

If the player tries to autopilot for another station an error on the sonar will occur "Second station not found".

Chance to be generated:
Chance of water pits to occur is determined by xml files responsible for stations in Barotrauma. Military Outposts are having 92% chance for them to be and "Beacons" are having the lowest chance of 23%.

I leave decision to developers if water pressure should be there. If no, than I guess filling submarine with water would lower the height of water outside submarine, since the pit has limited capacity.

On the screen in submarine editor, where player is about to save submarine it can be decided at which corners of the snow pit docking hatches or ports should be spawning for refilling energy to shuttles. Both default shuttles are having it set to only 1 hatch on the ceiling and other vanilla submarines are having none.

Lore:
The coalition have decided, that it would be a good idea to use water instead of ladders to maintain submarines, because ladders are annoying.

Also one question:
If that feature is going to be implemented, does it mean default shuttles can finally have lamps consume 5 kW's, since water pits can be used to refill energy? Same thing comes with navigation terminal.

Another request (minor):
Rename "none" location to "Beacon" in xml file of location types.

**Comment by Regalis11** [comment]
I'm not sure if I fully understand the point of this idea. It's possible to do the rewiring, maintenance and such at the start or end of the level without the need to pay money to dock to a port. And once the physical stations/outposts are implemented, there will be even less need for this.

And again, the vanilla shuttles are not meant to be usable on their own (hence the warning when you select one). If you want to play on a shuttle, you need to use one that has some means of generating power.

**Comment by rico6822** [comment]
While not doing a mission player can optionally access a pit.
