### ISSUE TITLE
Unable to spectate and join in on a campaign.

### ISSUE THREAD

**Issue by HeatedWafflez** [Regalis11/Barotrauma#7271]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/51425624/141377274-9ec2f236-c036-4171-b8c8-b5fe93966e04.png)
![image](https://user-images.githubusercontent.com/51425624/141377290-bb4c4a5f-7a1c-4798-b24b-eb1e553bb31d.png)
I am met with the first message in the console upon joining the server, and the second message upon attempting to spectate.

**Steps To Reproduce**
-After spawning in as a mechanic despite wanting to be an assistant, I created a new character with the intent of being an assistant while at the outpost
-I then walked out the airlock and killed myself
-I left the server and rejoined, only to be met with these messages as described in the **description** section

**Version**
v0.15.13.0

**Additional information**
I left and rejoined the server, as well as restarted the game. Neither fixed this problem.

**Comment by Regalis11** [comment]
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/269ca20cfdeddb6444f0d10e60d7eea39ced8a18

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
