### ISSUE TITLE
Pirates can immediately die due to crush depth.

### ISSUE THREAD

**Issue by RemervKeberb** [Regalis11/Barotrauma#7272]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon starting a pirate hunt mission at significant depth in the campaign. Pirates have a chance to spawn below their crush depth killing them instantly.

**Steps To Reproduce**
Get to a stage of the campaign where the depth is very low with a pirate vessel mission.
Pirates will now have a chance to spawn at a depth that neither their submarine nor their suits can handle.

**Version**
v0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Additional information**
Couldn't replicate in single mission, only happened in campaign.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb9bfd6c2918485288c1174891fff31aff49b0f4

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
