### ISSUE TITLE
[Bug?] Custom outpost spawn with no personnel

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#7273]
Hello, once again i need some guidance, previous issue with misaligned modules was successfully resolved, my gratitude)

As the title states, now i have to seek help about custom outposts spawning with no crew inside, despite me making an NPCset and stating said NPCs onto the outpost, i might've missed something tho, not denying that, i tried both custom job spawn points and "any" job spawnpoints, both give the same result with or without the tags designated to said spawnpoints

Attaching screenshots of xml files and SubEditor module with how it's saved

![BR1](https://user-images.githubusercontent.com/74479084/141383383-74550255-8f84-4d12-8fb0-44b28c473258.PNG)
![BR2](https://user-images.githubusercontent.com/74479084/141383385-3c2ffad6-bb76-4697-a3b3-85d0bce27784.PNG)
![BR3](https://user-images.githubusercontent.com/74479084/141383386-4f2e776f-0f00-4707-97e6-e38a72c8d89f.PNG)
![BR4](https://user-images.githubusercontent.com/74479084/141383387-3277b2e7-09ae-4551-b7da-93ef13aefcb4.PNG)

**Comment by Regalis11** [comment]
Hmm, I can't see anything wrong with the xml files you posted. Do the combine outpost generate normally in the campaign, but just without any NPCs? Are there console errors of any kind? I could also try to debug this at my end if you posted the xml files you're using here.

Thanks and sorry for the inconvenience!

**Comment by Showdoze** [comment]
forgot to add job descriptor
[Combine_personnel.zip](https://github.com/Regalis11/Barotrauma/files/7528475/Combine_personnel.zip)

**Comment by Regalis11** [comment]
Thank you for the extra info! It seems that the problem is the "allowedlocationtypes" property in "Combine_level_generation.xml": you've set it to "Outpost" (the default outpost) instead of the custom "Combine_outpost" location type. Because of this, the combine outpost generation parameters aren't used in the combine outposts, so it fails to spawn the correct NPCs.

**Comment by Showdoze** [comment]
Thanks you for you assistance, i'm really grateful for your help)
