### ISSUE TITLE
Bots no longer follow way-points  when shuttle is docked

### ISSUE THREAD

**Issue by logan-six** [Regalis11/Barotrauma#7274]
- [ y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
At the start of a round, Bots can freely navigate between the main sub and shuttle(s).  If  during the round the shuttle undocks and then docks to the main submarine, bots appear to no longer be able to open/shut doors or hatches or navigate in or out of the shuttle independently. 

**Steps To Reproduce**
1.  At round start , command a bot to perform a task that requires it to transit both into and out of , a docked shuttle (should work fine).
2. With a bot present inside the shuttle, perform an undock and then dock.
3. after docking,  command the bot to perform a task within the main sub.
4. Bot should be unable to independantly navigate a path from the shuttle to the main sub through the docking hatch.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using 
Version 0.15.13.0 hotfix
(Windows/Linux/Mac).
Windows 10
**Additional information**
Link to video of issue - 
https://youtu.be/Hd1PSsrkl2M

**Comment by carducciz** [comment]
I have also been running into this bug and was about to make a separate post before seeing this. I have uploaded a video of the bug (link below) to show a similar issue of bots suddenly being unable to use doors properly from inside the shuttle after undocking and redocking.

https://youtu.be/Ul5d1WtVapo

**Comment by itchyOwl** [comment]
itchyOwl changed the pipeline from TEAM2 Bot AI to In Progress in Barotrauma 3 days ago <- can't remember doing that. But yeah, I can take a look :D

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c1a7d60.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
