### ISSUE TITLE
Bots slam the door in your face

### ISSUE THREAD

**Issue by jimj316** [Regalis11/Barotrauma#7275]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After walking through a door, a bot will always try to close it (which is good) but they will do so even if there's someone in or approaching the door (which is very rude!). This isn't the biggest issue in the world, but it adds another layer of frustration when playing with bots.

**Steps To Reproduce**
Try walking through a door after a bot, or just watch bots on a busy station.

**Version**
v0.15.13.0 on Linux, but I'm pretty sure this has always been an issue.

**Additional information**
My suggested fix would be pretty simple: whenever a bot would close a door, it quickly checks its immediate area (I'd say 1m would be safe) for any other friendly humans, who are currently moving in the direction of the door. If there are any, don't close the door. 

Caveat: it's possible that this could lead to no-one closing the door, so there might need to be some inter-bot communication, but humans do that anyway so just say it's a feature ;)

**Comment by HeatedWafflez** [comment]
cry about it
