### ISSUE TITLE
All RuinGenerationParams are named "RuinGenerationParams" instead of using their identifier in the level editor

### ISSUE THREAD

**Issue by dakkhuza** [Regalis11/Barotrauma#7278]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ruin generation parameters always use the name "RuinGenerationParams" instead of the identifier like other outpost generation configs in the level editor. This is purely visual [and happens due to this line of code](https://github.com/Regalis11/Barotrauma/blob/10e5fd5f3e5439f446f2ba42c41a1f094814678a/Barotrauma/BarotraumaShared/SharedSource/Map/Levels/Ruins/RuinGenerationParams.cs#L39). Removing the override fixes the issue.

**Steps To Reproduce**
Add any number of extra ruin generation params, they'll all be called "RuinGenerationParams" instead of their identifier.

**Version**
v0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/12bda2c58771a865e42b6f08d28d96ef1e2d87e4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
