### ISSUE TITLE
Game crashes when using Handheld Monitors outside of the submarine after getting disconnected from server.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#7279]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Go outside the main submarine with a handheld status/electrical monitor.
2. Get kicked/disconnect from the server.
3. Rejoin the server.
4. Equip the monitor. The game will proceed to crash to desktop.

**Version**
Version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Additional information**
Only the client's game crashed.
Crash report: [crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/7529472/crashreport.7.log)

**Comment by Jade-Harleyy** [comment]
Also, if I had to guess, I think it's because the game loads the sub you're in when you rejoin the round.
So the game has null loaded for the sub you're in such that when it tries to draw the map, it tries to load null and the game crashes due to a null reference exception.
At least that's what I can gather from my experience and the crash report.

**Comment by Regalis11** [comment]
This seems to happen with all handheld status monitors that initially spawned outside subs: can also be reproduced by spawning one in your inventory with console commands when you're outside. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67f7eeed2f2abcac624011bf3a5ffe5a8a54d5b2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
