### ISSUE TITLE
Non human characters can't move their hands while aiming an item if they are not swimming

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#7282]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Monsters equipped with an holdable and aimable item will move their hand and subsequently their item towards their target.
This, however, seems to only happen if the character is swimming in the water. A character who is on dry ground will simply aim their item towards their target without actually moving their hand to accompany this movement.

**Steps To Reproduce**
Spawn a "humanhusk", take control of it and give yourself any aimable item (ranged/melee/utility/etc) then press mouse2 to aim while using the item. **If you are on dry land**, you'll see that your item rotates towards your mouse, however **your hand will remain perfectly still**. If you are swimming in the water, your hands will move as they would if you were doing the same thing as a human.

**Version**
v0.15.13.0

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this:
![image](https://user-images.githubusercontent.com/14351070/142214214-c1f818a6-e2c0-4139-9e6f-ce6810309b71.png)

Did this happen in a fully vanilla game or are you using some mods?
