### ISSUE TITLE
Bots Can Get Stuck walking back and forth or into walls when a shuttle is present.

### ISSUE THREAD

**Issue by VoltzDuck** [Regalis11/Barotrauma#7284]
Playing Campaign with a freind and had a shuttle on a personal sub. After a while they wouldnt react to commands and just stood there in a ballast tank and next to the shuttle hatch. They died when a fire started and they coudent leave. After shuttle was ejected they worked fine.

**Comment by Krzeszny** [comment]
@VoltzDuck Out of courtesy, I'll ask for the devs. 
Can you please provide more info?
1. First and foremost, did you have the waypoints configured properly between the sub and the docking port? To test it, can you make another bot follow you through the shuttle docking port, both ways?
2. Can you post screenshots or a video showing the issue happening for a second time?
3. Can you reproduce the issue at all?

**Comment by VoltzDuck** [comment]
The sub has the same section as the kastrull, as i didnt know much about way points or docking mechanics so is the same, although the bots bug out not near the docking hatch, and yes the bot can go both ways through the port.

That being said i did still check over the waypointys and i am fairly confident that there is no clear issue with them, the other problem that there could be is that the bots are interacting with the way points on the shuttle. (there are no waypoints on the outside of the shuttle like there ae with most as its intended to be an escape / wreck buster pod, players only).
I have attatched a vid of me reproducing it

https://user-images.githubusercontent.com/94201499/142676684-601191a9-99bf-4c8d-b5bb-db39a45b7e42.mp4

As you can see in the video, after the walking around for a bit the bot gets stuck and wont respond to commands,( happens in multiuple areas not just the ballast including far away from the shuttle).

appoligies if this is down to my stupidity.
sorry for spelling English is not my first language.

**Comment by NilanthAnimosus** [comment]
Tested against Release/1.0-patch-2 commit https://github.com/Regalis11/Barotrauma-development/commit/baf2d4b71b05a365354ecbeab42db0287ad329d5

confirmed issue still exists, image and test submarine below.

Reproducing is simple, tell the AI to follow you or give an order that should get them moving, although the shuttle intersects a bit I'm fairly confident its related to the waypoints on the outside of the shuttle being close to the AI inside the hull and/or intersecting causing pathfinding issues.

![image](https://github.com/Regalis11/Barotrauma/assets/29177976/6d07172b-17c8-4a8b-a118-189414522334)

Test submarine: 
[bot stuck test.zip](https://github.com/Regalis11/Barotrauma/files/11723249/bot.stuck.test.zip)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@82fb647.

**Comment by Jasontti** [comment]
Tested.
Works with vanilla subs and combinations of rescue subs and vanilla subs.
Closing ticket.
