### ISSUE TITLE
Crash: "Exception: Object reference not set to an instance of an object." on Outpost leave

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#7285]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fresh save, no mods. Visited the outpost, completed the 'toss the mic into living room' quest (selected 'hide in electronics' option), left the Outpost by selecting Explosive cargo + Mining pyromorphite , have crashed.

**Steps To Reproduce**
Load the save, get the crash.

**Version**
Win10 x64 Home (RU), the game: latest release version to date. Completely fresh install.

**Additional information**
Save & logs attached (hell, this new GitHub interface is painful to use properly...):
[Desktop.zip](https://github.com/Regalis11/Barotrauma/files/7530757/Desktop.zip)
Quote from logs:

`Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void PlaceResources(Barotrauma.ItemPrefab, Int32, ClusterLocation, System.Collections.Generic.List`1[Barotrauma.Item] ByRef, System.Nullable`1[System.Single], Single)
Stack trace: 
   at Barotrauma.Level.PlaceResources(ItemPrefab resourcePrefab, Int32 resourceCount, ClusterLocation location, List`1& placedResources, Nullable`1 edgeLength, Single maxResourceOverlap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 2817`

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b2f32e42719054ba6b6501e80f73ca4100ad2619

**Comment by DDusktv** [comment]
Could you please update me once this is solved would appreciate being kept in the loop!

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
