### ISSUE TITLE
Nav Nodes not automatically generating for stairs

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#7286]
**Description**
On both new and old ships, when I generate nodes for bot navigation, the nodes don't generate for stairs even though they used to.

**Steps To Reproduce**
Even when the stairs are properly aligned and there is a properly placed gap, nodes do not generate for the stairs.

![image](https://user-images.githubusercontent.com/83255239/141605199-d7f1cebf-9383-4d65-93c5-0e8ebc758876.png)

**Version**
Latest version

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3bfa36b69ed4d8e7ab054c5fe7e03a3a7e2ad5f5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
