### ISSUE TITLE
Abandoned outpost reactor blows up sub

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#7289]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Outpost Recovery mission that needs me to blow up the reactor but the nuclear explosion destroys my sub."

Expected: Outpost reactor is placed in locations that are no risk to the player sub?

**Steps To Reproduce**
Not my issue - its reported here:
https://steamcommunity.com/app/602960/discussions/0/5938553975805766279/

**Version**
0.15.13, assumed

**Additional information**

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/77ea7763f3b02b0338f5fc4451b45f6186e925b4

**Comment by Regalis11** [comment]
Changed in https://github.com/Regalis11/Barotrauma-development/commit/6e911ecd95350ab1ad67d28e02da49c5bd7b8d39

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
