### ISSUE TITLE
Crash while trying to make a walking creature

### ISSUE THREAD

**Issue by Akwar** [Regalis11/Barotrauma#7290]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was trying to make my own mod that adds creatures, everytime I tried to make a creature that is able to walk my game crashes and always the report says: Exception: Crouch (System.NotImplementedException)

**Steps To Reproduce**
start making a creature in the ingame program, when you get to making the new ragdoll check can walk and add the texture, get to the next step and don't change anything

**Version**
Barotrauma v0.15.13.0
Windows

**Additional information**
this only happens when I try to make a walking creature
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/7531989/crashreport.10.log)
.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/850c18255863380addcf30f4efb6507fac23cf8a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
