### ISSUE TITLE
Russian translation for shopping is unclear "В наличии\В наличии"

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7291]
In Russian translation of store interface there is two lines under each item:
"В наличии"
"В наличии"
In English it was easy to distinguish labels, like "in shop" and "you have" 
In Russian it translated to messy "available" and "available"
I think it should be translated like 
"В продаже" (you can buy it)
"В инвентаре" ([we have] At inventory)

**Version**
Also. I think your "bug" button should show version number, I do not really want to exit to menu from gameplay just to check version number.
System is Windows7, not sure translation depends on OS.

**Comment by Regalis11** [comment]
Addressed in Regalis11/Barotrauma-development@f18a16a
