### ISSUE TITLE
Feature request -> Bug button in menu should show version number.

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7292]
I think your "bug" button should show version number, I do not really want to exit to menu from gaming process just to check version number.

**Comment by Regalis11** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/e2606b7975ca51aeee7f7a4ed269aa6d865e9911

**Comment by Rokvach** [comment]
The bug report button in settings doesn't show the version, could we also adjust the position of that button? As we have added more settings tabs the buttons position looks a bit awkward now
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5ea7c8e0-48f8-4a99-a20f-fa0b9435f94e)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/d892d762fd49ca1f502a4045faa26a1c5b4b9412

**Comment by SoNickRND** [comment]
But there is still no version info in "bug" menu, my original idea is not realized. ((((
