### ISSUE TITLE
Russian "sorry, I can't help you" (about healing) is very tragic, when it shouldn't be.

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7296]
When crew-member says "Мне жаль, [name], тебе уже не помочь!" it means "Nothing can help you [you're doomed, walking corpse, have few hours\days to live].
But in reality he says like "Sorry, my skills\supplies limited, this is my best".
Maybe better use something like "Мне жаль, [name], это всё, что я могу сделать!" like "That's all I can do for you"

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f18a16a5533e1a51f45972e27b820596621328ec
