### ISSUE TITLE
Non-QWERTY keyboard layouts do not work correcty

### ISSUE THREAD

**Issue by pystub** [Regalis11/Barotrauma#7299]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All general keybinds are mapped through current keyboard layout. This means that a pressed key might be interpreted int game as a key that is physically in a different place on the keyboard.

This suggests that somewhere in input event handling code the key symbol is used (what it would type) instead of key scan code (by convention ASCII number of an equivalent QWERTY keyboard).

**Steps To Reproduce**
* Start any game mode, e.g. mechanical training;
* press physical D key;
* nothing happens.

**Version**
Barotrauma v0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Additional information**
I think this is one of the offending lines, although I'm not sure it applies to Windows:
https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs#L137
Related:
https://github.com/Regalis11/Barotrauma/blob/ef55b68431074f95c018eee1a4cadc20450a85ff/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDL2.cs#L776

Typing in text areas should work as it does now, i.e. use symbol code.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/07d50db3

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
