### ISSUE TITLE
Sector AITargets are much larger than they appear to be

### ISSUE THREAD

**Issue by 3e849f2e5c** [Regalis11/Barotrauma#7306]
`AITarget.IsWithinSector()` returns true on a much larger area than intended causing directional ping to attract monsters in around 180 degree radius instead of the small sliver

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a1c25dac544bd7224d0f0de0349dd568b8e7d13

**Comment by StruggleDuck** [comment]
the chad dev back at it again

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
