### ISSUE TITLE
Options for opposite game world movement

### ISSUE THREAD

**Issue by muldjord** [Regalis11/Barotrauma#7307]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not a bug, but a "first exposure to game" observation. The implementation of the mouse moving one way, and the game scene moving the opposite way is upsetting my brain balance center to the point where I don't think I can play the game for longer periods of time. It makes me queasy.

3 things that could alleviate this. All would be useful as options:

1. Allow for it to only be enabled when a "View world peripherals" hotkey is pressed. 
2. Delay the movement of the game world slightly so it isn't 1:1 with the mouse movement. Makes it less erratic, and if the mouse is moved one way quickly, and the other way  quickly, the game world movement would be cancelled out and simply not happen.
3. Allow the game world movement to be scaled so we might loose some peripheral, but at least the movement of the game world isn't as outspoken.

I have complete understanding if you don't want to change this. In that case, just close the issue, I won't mind at all. I just wanted to let you know that, from a newcomer, that opposite movement can be an issue.

Game looks great!

**Steps To Reproduce**
Play the first tutorial.

**Version**
Linux, 0.15.13.0

**Additional information**
None of relevance.

**Comment by Regalis11** [comment]
Hello and thank you for the report!

It's possible to disable the camera movement in the game settings ("Enable mouse look" in the "Controls" tab). However, the art and subs have been generally designed with the assumption that the player can control the amount of zoom and the position of the camera, so it disabling it altogether may not be a perfect solution either. You're not the first person to bring this up though, so I think we do need a better way to address the problem.

We've got a ticket about improving the camera movement in our private repository (https://github.com/Regalis11/Barotrauma-development/issues/2246), so I'll close this one.
