### ISSUE TITLE
Server browser locking up client when updating list

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#7308]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Server browser is locking up/fullly unresponsive when the server list is updated from the master server when opened the first time after client start. With the current high player/server count this issue becomes very apparent.

Expected: Client stays responsible. Visible list is either updated live or master server update runs in the background without triggering the non-responsive state of the OS.

**Steps To Reproduce**
Start client
Open server browser for the first time
Client is unresponsive/locked up
And user inputs often triggers "non-responsive app"-warning in Win10

**Version**
0.15.13 and before

**Comment by Regalis11** [comment]
Could no longer reproduce this in v0.17
