### ISSUE TITLE
Replacing lost ID cards

### ISSUE THREAD

**Issue by camtheprogram** [Regalis11/Barotrauma#7315]
- [V] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a character loses their I.D badge they have no way of replacing it. My A.I engineer in a campaign lost their badge somehow and can't complete any of their tasks now because they can't open doors. Causes the A.I to bug out.

**Steps To Reproduce**
n/a

**Version**
Windows. 11/14/2021

**Comment by Krzeszny** [comment]
For the easiest fix, ID's should respawn on round's end **or** each mission if not equipped.

**Comment by Regalis11** [comment]
Let's make them available in outpost stores, and assign the tags according to the character who purchased the card. This won't fully solve the problem atm when only people with campaign permissions can purchase them from the store, but the upcoming personal wallets will solve that.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/f5df1f5c3c49982ffe1012ea8bbde7503f100beb

**Comment by Rokvach** [comment]
The bought ID is for the person who buys it, so if you don't have an ID you aren't able to reach the store and your friends can't buy the ID for you, so how are you going to get a new ID with your name on it. 

Couple ways to handle this
1. Allow to "Use" the ID once it has been bought to assign a name to it which then makes it bound to the player who used it
2. Allow players to navigate the outpost without a ID (This might still have an issue as you might not be able to get to where your ID spawned on the submarine)
