### ISSUE TITLE
Mechanics can infinitely gain health and melee damage while using the Elbow Grease talent

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7321]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A mechanic using the elbow grease talent is able to infinitely increase their health and melee damage by deconstructing scrap

**Steps To Reproduce**
obtain elbow grease talent, then deconstruct lots of scrap

**Version**
0.15.13.0

**Additional information**
Video I found on the internet which showcases the bug: (https://www.youtube.com/watch?v=ABkHHFQtDGo)

**Comment by M61Dev** [comment]
This was originally intentional, but admittedly it might be a bit too strong in the hands of veteran players. See https://github.com/Regalis11/Barotrauma-development/commit/6c3a73c5e31853c6b4e715beb624b6fe67dce9fb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
