### ISSUE TITLE
Pulse laser sometimes shoot on strange direction

### ISSUE THREAD

**Issue by tt36999** [Regalis11/Barotrauma#7326]
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When pulse laser shooting, sometimes it will hit crew in MY ship, no hull damage on my ship, just crew injured. I will upload some image to show what happened

**Steps To Reproduce**
Just install some pulse laser on ship and shoot, is it happen randomly, all tested in mulitplayer mode(Only me in server) or editor mode

**Version**
Barotrauma v0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)

**Additional information**
Here you can see the laser on strange direction, this  only happen when AI operating the pulse laser
![image](https://user-images.githubusercontent.com/12522418/141792397-e19e7729-eb46-46e3-b1f1-dcb2cefd7508.png)

**Comment by FalconPilot** [comment]
I can confirm it happened to me. I was the one handling the pulse laser, though, so it doesn't necessarily applies to AI only ! However, it does not happen on all shots, only a few of them.

**Comment by Regalis11** [comment]
I gave this a test with a modified Dugong in both multiplayer and the sub editor, but unfortunately I couldn't get it to happen.
![image](https://user-images.githubusercontent.com/14351070/142204713-fe673311-7260-4888-8fa0-f5f601f998a3.png)

Is the submarine you're using available in the Steam Workshop? I'm wondering how the double lasers have been wired in it or whether there's any kind of custom aiming circuits in it that could cause this. In my test I simply connected both lasers directly to the same periscope, supercapacitor and loader.

**Comment by tt36999** [comment]
The submarine are build by myself, I have confirm this will not happen on Dugong.
I will test again, if this still happen on me, i will upload the submarine file.

**Comment by tt36999** [comment]
OK I am back, I think the key is you must move turret when turret shooting. But I can't repeat on Dugong, so here are the submarine
https://steamcommunity.com/sharedfiles/filedetails/?id=2657784470

And I upload a screen record to show what happened
sorry I forget change language when I recording.
First line AI said "What the hell are you doing? !",  second line "warehouse needs a doctor"

https://user-images.githubusercontent.com/12522418/142419653-a0bf5498-f481-4682-9785-c93a5200528a.mp4

**Comment by Thador** [comment]
I have an unfinished sub to reliably reproduce this in editor and local multiplayer testing sorry for the missing lights:
[https://steamcommunity.com/sharedfiles/filedetails/?id=2662205850](url)
Zip: [Tie-Test-B.zip](https://github.com/Regalis11/Barotrauma/files/7589063/Tie-Test-B.zip)
The laser is mounted on the shuttle below the dockingport, the idea was making it a hardmounted Superweapon without direct control, the button is at the nav terminal "Toggle Siren", where you can also toggle camera control(left lower btn) 

![LazorBug](https://user-images.githubusercontent.com/94911649/143052396-416e5779-e044-4ca8-aaa4-a21eac7f73c0.gif)
Things i tried to debug:
- resetting turret stats
- setting the turret position with a mem module, also tested with oscilation(currently: 90+-1)
- wiring it to a periscope instead but restricting the turret angles in editor to 89-91
- setting no position signal but restricting the turret angles in editor to 89-91

The laser always hits people but not structures in a straight line close to the Nav-Terminal center, maybe shifting a bit to the right depending on turret input. My engineer Velma in the reactor room also dies. It has no animation.
I did not try to reproduce it on the dugong, but i think the "phantom laser" is appearing at a set distance away from the turret so one would need a larger testing station.

I looked at the projectiles being created/retrieved in the debug info and setting the reload of the turret to 0.016 will make it behave like a beam, which was my goal but going any lower will decrease the amount of projectiles generated (np its cheasy anyway)

This is hilarious, I even thought about making this a part of the sub like a charge conduit no-go zone, god i love this game
pls fix tho

**Comment by Regalis11** [comment]
Thank you, I was able to reproduce this now. It happened as a result of the linked subs: the hitscans done by the lasers done in the linked subs's coordinate space sometimes hit limbs in the other sub's coordinate space. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/796c788195874ec17946d2923228922d547ce481

**Comment by war3scv** [comment]
seem only happen for ventral mount laser, happen for all my ship with at least a shuttle or drone, whether laser monut on mainship or shuttle. Europa is dangerous.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
