### ISSUE TITLE
Security Officer's clothes have wrong icons (swapped)

### ISSUE THREAD

**Issue by panvxv** [Regalis11/Barotrauma#7330]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Security Officer's Uniform and Gunner's Uniform inventory icons are swapped. 

**Steps To Reproduce**
Put on yourself Security Officer's Uniform and check inventory icon to realise that it isn't even similiar look then to the same with Gunner's Uniform and realise that icons for those clothes are swapped. 

**Version**
Barotrauma v0.15.13.0      Windows 10

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by panvxv** [comment]
https://i.imgur.com/sMGq1DQ.png
Maybe I am going crazy but those icons are swapped.

**Comment by panvxv** [comment]
> 
> 
> Tested, no issues. Closing.

Maybe I am going crazy but those icons are swapped.
![obraz](https://user-images.githubusercontent.com/68397497/142082119-fc08a834-9f8e-49e3-bb4b-5fb101712e5a.png)
