### ISSUE TITLE
Reactor repair failure chance always possible even when turned off compeltely

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#7331]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Repairing the reactor, even when turned off (set on "off", 0 temperature, no lights,power generation at 0) can still cause repair failure to occure

**Steps To Reproduce**
Spam repair on a turned off reactor be it modded or not for pure mechanical repair.

**Version**
Windows release branch V 0.15.13.0 revision 4e66dd7b5d

**Additional information**
No other item has the property to cause repair failure when unpowered only the reactor

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5c6e291a82528a50ac7faf2e4602f1a5c3c98e8

**Comment by Lithosagym** [comment]
Tested, confirmed fixed.

**Comment by Rokvach** [comment]
Closing.
