### ISSUE TITLE
Repaired shuttles cannot float

### ISSUE THREAD

**Issue by bradjackson53** [Regalis11/Barotrauma#7335]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**

I have built a cargo drone to use on my primary sub but have had issues with it. If the drone's hull is breached at any point, the drone will permanently sink. The drone can still move left and right but can only fall down.

The drone operates as expected prior to being damaged and is able to freely ascend and descend.

I have used water detectors to verify that the drone's interior hull is clear of water and the ballast's water level is at expected levels depending on directional input. 

Possibly relevant is that the drone is controlled using a periscope rather than a Nav Console.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Create a shuttle and attach it to a primary submarine.
Damage the hull of the shuttle so that it floods (recommend parking shuttle on top of primary sub).
Repair the shuttle and let it drain of all water.
Attempt to make the shuttle rise up.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

v0.15.13.0 hotfix - Windows

**Additional information**

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this with any of the vanilla subs: they seem to float with no issues after the walls have been repaired and hulls drained. Would it be possible to send us the sub file you're using so I could give it a test? Note that you should .zip the submarine file first to attach it here, since GitHub doesn't support the .sub file extension. Thanks and sorry for the trouble!

**Comment by Regalis11** [comment]
It seems that the drone's upper hull never drains fully, because the water detector is so high above the bottom of the hull that it deactivates the pump before the water is fully drained:
![image](https://user-images.githubusercontent.com/14351070/142002106-14108ecf-d16d-4bb8-a62b-591478f37e10.png)

**Comment by bradjackson53** [comment]
Ah, crude. Thanks for pointing out what I did wrong. Sorry for the bother.
