### ISSUE TITLE
Orders' "MustManuallyAssign" attribute works incorrectly with some order definitions

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#7336]
**Description**
If the order has the `MustSetTarget="true"` or multiple order options, choosing the order will skip both the target and the option selection.

**Steps To Reproduce**
1. Add `mustmanuallyassign="true"` attribute to the Operate Reactor, Operate Weapons, and Pump Water orders.
2. Assign those orders using the command interface. (Note: the Pump Water order only appears contextually when targeting a non-automatic pump.)

**Version**
v0.15.13.0

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@02c1d5d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
