### ISSUE TITLE
Pyromaniac talent doesn't work (at least part of it)

### ISSUE THREAD

**Issue by panvxv** [Regalis11/Barotrauma#7338]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Pyromaniac talent should give player 40% physical damage resistance after dealing burn damage to an enemy, sadly after dealing damage with plasma cutters or welding tool player doesn't get this buff.

**Steps To Reproduce**
Get yourself a Pyromaniac talent, I did it by using console. Spawn enemies, I spawned husk, huskhuman and mudraptor. Attack them with tools like plasma cutters, welding tool or even use Incendium grenade. Realise that you didn't get 40% physicla damage resistance by looking above your health bar.

**Version**
v.0.15.13.0    Windows 10

**Additional information**
Also tested on people on stations by burning them with tools and grenades, still didn't work.

I coudn't see it but maybe Pyromaniac doesn't even give more burn damage.

Should this talent work with C4 and railgun loaded with them?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6946e985876442ec878ecf0fb2c7b97e9e8b426

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
