### ISSUE TITLE
Riot Security Officer Loadout doesn't start with a Riot Shotgun

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7342]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Let's be honest, almost no one picks any other security officer loadout other than Commando because of the SMG. No one likes to start as a security guard without an actual gun. The riot security officer loadout should start with a shotgun to be as competitive as the commando loadout.

**Version**
~0.15.13.0

**Comment by danielasteljoki** [comment]
Let's give it a try. Changed in a1dbee0.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
