### ISSUE TITLE
Flamer's visual fire effect does not work properly

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7343]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The flamer's fire effect is currently very short and concentrated, like the sprites / particles aren't being given any forward momentum at all. This should not be the case if you compare with reference images in Additional Info. The unique version of the Flamer (Prototype Steam Cannon) works properly for comparison.

**Steps To Reproduce**
1. Give yourself a Flamer and a Prototype Steam Cannon
2. Compare the two and measure how far the flames go
3. Add a test subject and measure damage range. Notice flamer still damages target as if the fire was much longer than its visual effect would indicate.

**Version**
Latest Unstable, Windows 10.

**Additional information**
Latest Unstable:
![damage range](https://user-images.githubusercontent.com/69410159/142087199-67fa3687-b51e-4945-b8f6-2c03c1b74e12.png)

Old effect:
![flamer 1](https://user-images.githubusercontent.com/69410159/142087212-3328f698-92a9-4a89-a9b6-c01f1ff14371.png)
![flamer 2](https://user-images.githubusercontent.com/69410159/142087224-9067ff69-5cfe-4a74-b54b-871092319577.png)
![flamer 3](https://user-images.githubusercontent.com/69410159/142087243-3ff3bbdd-34e2-4371-8f5c-a7138315abf7.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/35454656b1d21d88470935c247f7e472b322d591

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
