### ISSUE TITLE
If a player reconnects to the server after death the server wont try to respawn them in so the reconnected player is stuck as a spectator

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7345]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reconnecting to the server after your character has died causes you to be stuck as a spectator until the round changes or host enters lobby

**Steps To Reproduce**
1. Have a two client setup by making a copy of the build and disabling all the steam related settings
2. Host a dedicated server and join it with both of your clients
3. Start campaign and leave starting outpost
4. Use console command kill to kill one of your clients
5. Disconnect with the client who just died
6. Join back into the server
7. Notice that the server doesn't ask you if you want to respawn nor is there any respawn related text on the top left

**Version**
Branch: networking-fixes
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/176b96b4f2da1cccfbee3a18b91acae89068ca0d

**Additional information**
none

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5636dfb0d49d9fe2a3cc7c1990c7b5b9f3f34c89

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
