### ISSUE TITLE
Crash on unstable (AIObjectiveCombat.GetWeapon)

### ISSUE THREAD

**Issue by uyemeb** [Regalis11/Barotrauma#7348]
i have no idea what crashed it
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/7556422/crashreport.3.log)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@feae9dc. It crashes every time a bot starts a combat :/

**Comment by kento10** [comment]
Also crashes when terrorist mission bots activate to attack also crashes the game. With the same error trace word for word of AIObjectiveCombat.GetWeapon. Each crash happens at different times but it spits out the same error. This is during Single Player and on servers both with terrorists. Going to avoid these missions until the new version is up pirates seem to not be affected by this just killed some and did not crash.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
