### ISSUE TITLE
The "Status Monitor" misrepresents the oxygen ratio in the two "hulls" if were "linked".

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7349]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "Status Monitor" misrepresents the oxygen ratio in the two "hulls" if were "linked".

**Steps To Reproduce**
1. You have two hulls and there’s a fire door between them.
2. There’s a vent in the right hull.
3. In order to display these hulls on a minicard as one space, you establish a "link" between them (use spacebar).
4. In the left hull, a fire breaks out and the fire door closes to separate the right hull.
5. There’s no ventilation in the left hull and the door’s closed.
6. Set fire to the left hull
7. Make Left hull - oxigen=0% 
8. Check out the oxygen level for both "Hulls" at the "Status monitor"!

The problem with "Status monitor" - incorrectly displays ratio of percentage of oxygen in connected spaces. If in reality in the left hull = 0% oxygen and in the right hull = 100% oxygen, but the "Status Monitor" shows: Left Hull=33% and Right Hull=67%

**Version**
Barotrauma v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
![142042656-1ac6efb8-5b35-4520-bfb9-b0617a851dfb](https://user-images.githubusercontent.com/93348499/142248218-1d3d19a7-9e60-4858-9857-649428e4f1d8.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2905397106e10d9e0c319265d59a8513b7e96568

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
