### ISSUE TITLE
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)

### ISSUE THREAD

**Issue by Rattle189** [Regalis11/Barotrauma#7352]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I run a dedicated server for me and my friends and I also play on the dedicated server under the same machine. Every time we undock from an outpost, the console is spammed by this:
`
WARNING: event count very high: 1335
1. EntitySpawner x222
2. Barotrauma.Hull x47
3. Barotrauma.LevelObjectManager x19
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
WARNING: event count very high: 1215
1. EntitySpawner x135
2. Barotrauma.Hull x47
3. Barotrauma.LevelObjectManager x19
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
Error when writing character spawn data: status data caused the length of the message to exceed 255 bytes (411 + 16)
`

**Steps To Reproduce**

1. Do your usual thing in the outpost: buy things, receive missions, upgrade sub, or hire/fire crew.
2. Choose a mission and undock from the outpost.

**Version**
Barotrauma v0.15.13.0 under Windows Server 2022 Standard Evaluation 21H2 20348.350

**Additional information**

**Comment by LuckyLuke980** [comment]
We have ran into the same issue. Steps to reproduce are the same as above. Version 0.15.21.
[event_error_log_server_Mr.Andersson_2015.log](https://github.com/Regalis11/Barotrauma/files/7963214/event_error_log_server_Mr.Andersson_2015.log)
0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/daf657ad9451cc96b1e47b8f346f1ebb3b3c4079
