### ISSUE TITLE
override-ing talents and talent trees are STILL not possible

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#7353]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
still cannot override talents or their trees

**Steps To Reproduce**
try to override talents or their trees

**Version**
Unstable, windows

**Additional information**

![bug](https://user-images.githubusercontent.com/82000521/142275643-4449768e-9737-4744-8f4d-2419d7ea61e3.png)

**Comment by doornydew** [comment]
and yes, i've tried everything from individual override's for each talent to switching out places of the override, each change ends up with even larger error logs, this is the most clear and make sense error.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f49265091313d10768b1f801be33a82229a3fe8f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Nvm, the error pointed out in the ticket doesn't happen anymore but it seems that the overrides aren't actually applied, tested with a mod that tries to override talents.

The mod should change the location of the Engineers `All Seeing Eye` talent by moving it to the left talent tree, this doesn't seem to be happening. 

https://steamcommunity.com/sharedfiles/filedetails/?id=2639135936

**Comment by doornydew** [comment]
confirmed working, mod which overrides talents and their trees are confirmed working, however, with errors coming in:
https://cdn.discordapp.com/attachments/668819422919524352/911590484793778176/unknown.png

**Comment by doornydew** [comment]
forgot to include the steam workshop file i used
https://steamcommunity.com/sharedfiles/filedetails/?id=2639135936

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4caec3fe69db79f3fdee14577d47cb3751248323

**Comment by doornydew** [comment]
testing.

**Comment by Rokvach** [comment]
Tested with the provided mod, seems to be working now. Closing.
