### ISSUE TITLE
Deconstructors don't combine partials materials if they land in a container

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7355]
- [x] I have searched the issue tracker to check if the issue has already been reported.
Seems like the perfect issue to fix for a QoL update.
![Barotrauma_C1xFfOfuvm](https://user-images.githubusercontent.com/10529134/143241853-61e091d3-172c-41da-9cd8-b5dc69eca61f.png)

**Steps To Reproduce**
1. Place a container into a Deconstructor's output slots
2. Deconstruct at least 2 wires (or stun gun darts)

**Version**
v0.15.15

**Comment by Regalis11** [comment]
Could not reproduce in v0.15.15

**Comment by Krzeszny** [comment]
> Could not reproduce in v0.15.15

Sry, wrong reproduction steps. I'm editing them now. You're supposed to deconstruct thiose wires (etc.) into a container placed in Deconstructor's output slots.

**Comment by Rokvach** [comment]
Tested, I was able to reproduce the issue with the new steps.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e2870df75aba55f6fb7de9fce95015b1a6ad25c

**Comment by Rokvach** [comment]
I kinda liked the idea of being able to directly deconstruct items into a container, but issue has been fixed. Closing.
