### ISSUE TITLE
[AI] Bots Get Stuck on Hatch when Descending Ladder and Fall Through Sub 

### ISSUE THREAD

**Issue by desukakes** [Regalis11/Barotrauma#7357]
Bots sometimes get stuck on a closed hatch when descending ladders and when the hatch opens, they get ejected out of the sub and die. I've only noted this happening to the mechanic and engineer so far.

**Comment by itchyOwl** [comment]
I haven't seen this happen. There have been some fixes related to bots getting stuck to ladders next to a hatch. But if a bot (or some other character) gets drained out from an open hatch, I think that's just a feature. If the sub doesn't move too fast, they should be able to get back inside though.

**Comment by itchyOwl** [comment]
Closing the issue, becasue there's no steps to repro or further reports about it.
