### ISSUE TITLE
Balance pass: explosions

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#7365]
Now that we have added burn damage modifiers to all monsters, the actual damage of explosions against monsters is probably relatively lower than it used to be, which is something we should adjust. There are a couple of possible approaches here, which we might need to combine: A) increase the explosion damage B) increase the penetration of the explosions (which effectively lowers the protection, but don't affect the weak spots or the damage to unprotected limbs) C) adjust the damagemodifiers on monsters.

So in brief: go through the sources of explosions, test how they work against monsters, and adjust: 
a) explosion damage and burn
b) penetration?
c) damagemodifiers on monsters

**Comment by Regalis11** [comment]
Related ticket in the public repo: https://github.com/Regalis11/Barotrauma/issues/7411

**Comment by Regalis11** [comment]
Related ticket in the public repo https://github.com/regalis11/barotrauma/issues/8122

**Comment by Regalis11** [comment]
Thoughts about this in the discussions https://github.com/Regalis11/Barotrauma/discussions/8144

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be merged.
