### ISSUE TITLE
Unstable - Wreck Salvage Mission item unobtainable

### ISSUE THREAD

**Issue by kento10** [Regalis11/Barotrauma#7366]
- [ yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The logbook seems to be spawned inside a wreaked secure steel cabinet cannot get mission items I checked with sonar for location.
**Steps To Reproduce**
Seed bestseed was on mission with scan vip and wreakage there was a becon along the route.
**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows unstable 0.15.15
**Additional information**

**Comment by Regalis11** [comment]
It should be possible to open those secure steel cabinets by getting an ID card from the corpses in the wreck.
