### ISSUE TITLE
[Unstable] Pressing R or T doesn't bring up chat if its minimized

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7367]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have chat minimized and press R the chat doesn't show up, instead just flashes in yellow. 

Noticed in multiplayer

**Steps To Reproduce**
Have chat minimized and press R or T

**Version**
Unstable 0.15.15.0

**Additional information**
None

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a234286d81f2c91174c93e1b9a376e3a8637e4a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
