### ISSUE TITLE
Purchasing a turret and then switching to a different submarine for the next level, and then switching back to the old submarine at the level after that, the turret is not purchased

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7368]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Purchasing a turret and then switching to a different submarine for the next level, and then switching back to the old submarine at the level after that, the turret is not purchased.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Could not reproduce. Did this happen in single player or multiplier? By purchasing do you mean just buying the turret, but not trying to install it?

**Comment by Kaillera** [comment]
> Could not reproduce. Did this happen in single player or multiplier? By purchasing do you mean just buying the turret, but not trying to install it?

It was in multiplayer (dedicated)

1. Play Dugong.
2. Install a turret to the hardpoint that has no gun yet.
3. Switch submarine to like Orca.
4. Drive through the next level with Orca.
5. Switch back to Dugong at the outpost.
6. Start the next level and look at the hardpoint.

**Comment by Regalis11** [comment]
Damn, still no luck. :/ I'm still not entirely sure what you mean by installing the turret: do you mean you purchased it (so it'll show "pending" in the UI and gets installed when you depart), or that you departed and returned back to the outpost with the newly installed weapon to switch to Orca? I gave it a test both ways, but in both cases the weapon got installed.

**Comment by Kaillera** [comment]
I'll give this a crack at it again.
