### ISSUE TITLE
Make Door Hide in The Background Instead of Going Up- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#737]
If you open door and try to see above of it's frame, where does the opened door's seal went it's gone, like it had to travel to another dimension. Simply go on the floor above that door and you see it's not here. Same thing comes with hatches.

**Comment by BillCombs** [comment]
There are some doors that roll up or just move to the ceiling when they open
![default](https://user-images.githubusercontent.com/38168249/44621556-44764400-a8d2-11e8-8c94-0d67ecb947c4.jpg)![images](https://user-images.githubusercontent.com/38168249/44621577-acc52580-a8d2-11e8-9bc5-2e5e6d880a7c.jpg)
Perhaps the doors on the subs just go inside of the floor above them.

I like the way the current doors open and close and would miss it if it was gone. But i wouldn't mind having an extra option. Perhaps there should be 2 kinds of ways the doors open so sub editors could pick whatever fits their tastes.

**Comment by BillCombs** [comment]
That does not have to be glass, there are some other transparent materials. Also don't forget that the game takes place in the future. They could possibly invent really durable but at same time flexible materials.

**Comment by thegrb93** [comment]
This comes down to the design of the ships. However, nobody is this nitpicky. If they really wanted to, the dev could add this so ships have the option for it, but to me it's unnecessary.
