### ISSUE TITLE
[0.15.15.0] Prepare for Expedition order is lacking

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7370]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bot took only ONE extra oxygen tank during the prepare expedition order.

**Version**
0.15.15.0

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@62c0c08 and Regalis11/Barotrauma@a2aa9b5. They now try to take five tanks.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
