### ISSUE TITLE
[0.15.15.0] Orca2 issues

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7371]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. The reactor is using default power settings (10000 output).
2. No Med Fabricator or Med Cabinet except for the small supply cabinets. If intentional, then OK. Starting to look very inferior to Orca1.
3. No Turret Hardpoint for perhaps the bottom side? The bottom is completely defenseless.
4. All of the small pumps have a default pump speed of 0, making the players having to manually set it to -100.
5. The depth charge tube is a bit inside the submarine too much, which can cause any depth charge to collide with the submarine too easily.

**Version**
0.15.15.0

**Comment by danielasteljoki** [comment]
Added med fabricator and bottom defenses. Other issues were oversights that have also been taken care of.

**Comment by Kaillera** [comment]
> Added med fabricator and bottom defenses. Other issues were oversights that have also been taken care of.

Docking port is not connected to power

**Comment by danielasteljoki** [comment]
Docking port is connected in 8b1d684

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
