### ISSUE TITLE
[0.15.15.0] Can't find unstable dedicated server with Same Version filter on?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7372]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
According to the three players including Rokvach, it seems like my dedicated server in unstable we were testing with, wouldn't show up in the server list if Same Version filter was on.

**Version**
0.15.15.0

**Comment by Regalis11** [comment]
We gave this a test now and unfortunately couldn't repro the problem, neither with a dedicated server or one hosted from in-game.
![image](https://user-images.githubusercontent.com/14351070/142600572-da25d100-6516-4342-bb70-c03057468cdc.png)
![image](https://user-images.githubusercontent.com/14351070/142600599-a7779f52-049d-45ed-91de-acc800df2529.png)
