### ISSUE TITLE
Changing Submarine name then deleting it from Steam Workshop Upload menu causes pre-rename sub to persist somewhere

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#7376]
- [x] I have searched the issue tracker to check if the issue has already been reported.

If you have a copy of same custom submarine under different names, then delete one, the game will throw occasional exceptions and will fail to recognize another submarine.

**Steps To Reproduce**
1. Start building a submarine in Editor. Do not give it a name yet.
2. (probably optional) make invalid submarine (i. e. do not close hulls or do not put any spawnpoints to trigger validation errors) but keep valid Submarine type (i. e. not wrecks, etc). Do not give it a name yet.
3. Give it a name, then save it manually to generate first .sub file.
4. Tinker with this submarine for some more.
5. Give your submatine a new name (in my case old name from step 3 was Metal Slug, new name was Metal Slug (prototype) + I made it fully valid, fixed spawnpoints etc).
6. (probably optional) tinker with it until few auto-saves would trigger. Then save it manually once (just to be completely sure).
7. Go to Steam Workshop Upload menu. Check your Submarines-to-upload list.
8. Select a sub with new name. Delete it at this window.

Expected result:
Sub with new name is gone.
([probably](https://steamcommunity.com/app/602960/discussions/2/3201491842001877811) since it's completely different feature piece) its autosaves are gone.
(not sure since technically these still have same mod ID) Sub with old name (probably with its autosaves) is still available.
If sub with old name had to be deleted - it's deleted fully, without remaining loose files.
Actual result:
Sub with new name is gone.
Sub with old name is gone.
(from Sub Editor's main list too)
![20211118215837_1](https://user-images.githubusercontent.com/81986452/142481416-cea81637-e521-4c9a-9e34-53c177a6bd37.jpg)
New named sub's autosaves are NOT gone.
![20211118215845_1](https://user-images.githubusercontent.com/81986452/142481449-610cd317-4555-427c-83cb-344a3b427709.jpg)
Sub with old name IS available somewhere in the game since client relaunch triggers an exception with old sub's name. Note that it've disabled Steam Workshop menu temporarily (until Console closure).
![20211118215740_1](https://user-images.githubusercontent.com/81986452/142481516-811ddfbe-55e6-4035-8f7c-93ebfb946af9.jpg)

**Version**
Latest Steam Release, no mods.

**Additional information**
Borked autosaves with new name (from Submarines folder):
[AutoSaves.zip](https://github.com/Regalis11/Barotrauma/files/7565426/AutoSaves.zip)
My Mods folder 'as is' right after issue's reproduction:
[Mods.zip](https://github.com/Regalis11/Barotrauma/files/7565433/Mods.zip)
I don't seem to see any relevant logs, somehow.

**Comment by Rokvach** [comment]
Tested, not an issue anymore, closing.
