### ISSUE TITLE
Moloch shellshield does not protect user or properly block players

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7377]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Moloch shell fragments offer no protection currently, their collision is also somewhat buggy.
XML references in Additional Info

You can push people around with the shell if you walk towards them, and they can't get past you if they walk into the shell (from any side). You are also able to push people while you are running, but only if they are completely idle. Effects which increase your movement speed make this impossible however. At a high movement speed both players completely slip through the shell hitbox. So its use as riot control is very limited this way.

I tweaked the xml a bit and found out this is because the body width of the item is not thick enough, but if it's too wide you can push people through walls, that's bad, that would lead to griefing. Needs to be fine tuned.

At its standard body width it cannot stop bullets, but will be able to with a modified width.  (See additional info for video)

**Steps To Reproduce**
Protection:
1. Spawn a Moloch shell fragment, first test is just get shot by a revolver or hit with a weapon, then compare damage without shell.
2. Try aiming it while holding right mouse button and get damaged again, shell does nothing, all projectiles and weapons hit arms.
3. Try dropping in on the ground, crouch behind it just for thoroughness, shield does not deflect bullets this way either.

Block player:
1. Stand still and have someone walk into you, they can't get past.
2. Start walking towards them while they are walking into your shield, you'll push them slowly away.
3. If they start running, they'll run past you (with a minor collision)
4. Run into an idle player, and you'll push them.

**Version**
Latest Unstable, Windows 10.

**Additional information**
Here is the relevant piece of xml I found (trimmed for convenience):

**shellshield, has no functional code other than a degraded movement speed affliction while it's being held.**

  <Item name="" identifier="shellshield" category="Equipment" tags="smallitem" cargocontaineridentifier="metalcrate" impactsoundtag="impact_soft" scale="0.5" allowasextracargo="true">
    <Sprite texture="Content/Items/CreatureLoot/CreatureLoot.png" sourcerect="464,1,48,229" origin="0.5,0.5" depth="0.55" />
    <Body width="40" height="145" density="30" />
    <Holdable slots="RightHand+LeftHand" aimpos="60,-30" holdpos="45,-30" handle1="-10,0" handle2="10,0" controlpose="true" blocksplayers="true" msg="ItemMsgPickUpSelect">
      <StatusEffect type="OnActive" target="Character" SpeedMultiplier="0.6" setvalue="true" />
    </Holdable>
  </Item>

A suggestion but not a complete fix would be find an optimal body width and maybe add something like
damagedbyprojectiles="" damagedbyexplosions="" projectilesdamagemultiplier="" explosiondamagemultiplier="" 
Maybe remove it on 0 condition?

Body width 64 showcased, (don't mind the extra height, did a lot of xml hacking)
Note, shield does not have this ability while being carried, which is weird.. Can only protect while it's dropped?
https://user-images.githubusercontent.com/69410159/142482545-11801408-d6cb-400c-b669-fcece324bd19.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa76536498b720edf4aba497262fd61743222a1d

**Comment by Rokvach** [comment]
Seems like the shield doesn't block all damage types

Couple things I noticed

1. Harpoons go directly through the shield not causing any damage to the shield
2. Stun baton hits goes through the shield and stuns the user using the shield
3. When you crouch it feels like you are less protected with the shield when it should be the opposite.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/9a5589a635bcde59c27d544050ebba405ad6a6b7. It still doesn't protect from those 100% reliably (especially if you hit close to the character's hand), but to me that seems like a good thing: imo it shouldn't be a 100% reliable way to block all damage.

**Comment by Marutzo** [comment]
Agreeing with Rokvach's point 3. The exposed head is usually protected by head gear so no problems there, but if you're a good enough shot you can get much better damage at the feet which are not covered when crouching, You are already penalized by a huge speed loss when holding shield while crouched, so protected legs only when crouching would be fair balance in my opinion. Additionally noticed explosions don't damage shield at all?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
