### ISSUE TITLE
Game crashes at startup if the selected Core content package doesn't exist

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#7380]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes at startup if the selected Core content package doesn't exist, not really a big issue, but mostly happens when you exit the game with a custom Core content package selected and is deleted by unsubscribing it via steam workshop, the solution to this is to default to the vanilla package if the selected content package isn't found.

**Steps To Reproduce**
1. Subscribe to any Core content package on Steam workshop
2. Selected it on settings
3. Exit the game
4. Unsubscribe from the Core content package
5. Start the game again

**Version**
Windows 10, Latest stable release of the game.

**Additional information**
[crashreport (26).log](https://github.com/Regalis11/Barotrauma/files/7566303/crashreport.26.log)

**Comment by Regalis11** [comment]
I could no longer reproduce this in the latest unstable version (v0.17.6.0), neither by unsubscribing or deleting the entire mod from the installation folder. The game now switches to the vanilla package automatically if the mod can't be found. I added an error message when that happens though: https://github.com/Regalis11/Barotrauma-development/commit/d6faa734da786ced5342c63ca42d8f836e45a9da

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
