### ISSUE TITLE
Stun affliction doesn't work properly on security officer

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7384]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Security officer seems almost immune to stun effect given by regular stun gun darts.
Fulgurium stun gun darts and other forms of stun weapons such as stun baton, stun grenade, 40mm stun grenade, all seem to work with a reduced effect on security officer as well.

Also noticed cumulative stun from "progressivestun" does not work with regular stun darts or stun batons.

See video in Additional Info

**Steps To Reproduce**
1. Spawn a stun gun and shoot a security officer, and another job.
2. Increase quality level of stun gun (which adds 10% stopping power per level), same results.

**Version**
Latest Unstable, Windows 10.

**Additional information**
Security Officer on the right
https://user-images.githubusercontent.com/69410159/142512921-4875e33f-3889-417f-be45-d8df74a08cc3.mp4

**Comment by Regalis11** [comment]
This is intentional: the extra health security officers have make them more resistant to stun.
