### ISSUE TITLE
[0.15.15.0] Gunner's Uniform and Security Uniform art's been swapped

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7385]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Gunner's Uniform and Security Uniform art's been swapped

**Version**
0.15.15.0

**Comment by Regalis11** [comment]
I can't see anything wrong here, are you using some kind of mods?
![image](https://user-images.githubusercontent.com/14351070/142594014-70f33eee-2d29-4c02-84dc-a27471e5da67.png)

**Comment by Kaillera** [comment]
According to my game, the left uniform is now security, and right is gunner's

**Comment by Regalis11** [comment]
Ahh, I see! That's actually intentional, the green one was supposed to be the gunner uniform and the blue one the security uniform. Previously the icon and the in-game sprite didn't match, which we fixed in the latest unstable. https://github.com/Regalis11/Barotrauma/issues/7330
