### ISSUE TITLE
Analyzeitem / Deconstructvalue console command crash

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7386]
- [ ✔ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Providing the Analyzeitem / Deconstructvalue console commands with invalid items / strings crashes the game.

**Steps To Reproduce**
Analyzeitem:
F3 console -> analyzeitem "stun gun dart"
Deconstructvalue:
F3 console -> deconstructvalue "body armor"

**Version**
Latest Unstable, Windows 10.

**Additional information**
[crashreport (28).log](https://github.com/Regalis11/Barotrauma/files/7567246/crashreport.28.log)
[crashreport (29).log](https://github.com/Regalis11/Barotrauma/files/7567248/crashreport.29.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/031a0b6b56e173fa32c335fd32b5bba75aeaf067

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
