### ISSUE TITLE
Azimuth潛艇 購買商品的問題 (Azimuth submarine purchase problem)

### ISSUE THREAD

**Issue by Automan0105** [Regalis11/Barotrauma#7387]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
無法取得貨品

**Steps To Reproduce**
在關卡開始，中繼站購買的貨物會卡進Azimuth潛艇的牆裡，以至於無法取得。
At the beginning of the level, the goods purchased by the relay station will get stuck in the wall of the Azimuth submarine, making it impossible to obtain it.

**Version**
v0.15.13.0
**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91b1c5cfa01abc18dc2dfea371e0f0cba5692394

**Comment by Lithosagym** [comment]
Tested, Azimuth cargo no longer clips into the submarine, fixed.

**Comment by Rokvach** [comment]
Closing.
