### ISSUE TITLE
"Pump Water" order doesn't appear in the contextual menu immediately after removing wires from the pump

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7389]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Unwire a automatic pump and access the contextual menu, notice that the pump order is missing. Open the pump UI and then close it, check contextual menu again and now the order is visible. 

**Version**
0.15.15.0
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/0a234286d81f2c91174c93e1b9a376e3a8637e4a

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@a6aece0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
