### ISSUE TITLE
Outpost reactor dials haven't been updated for the new position

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7390]
- [x] I have searched the issue tracker to check if the issue has already been reported.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7ceba6b9-9a68-4d89-aa8e-813a33d02afc)

**Version**
0.15.15.0
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/0a234286d81f2c91174c93e1b9a376e3a8637e4a

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0fb5a93ec401a1c9e3aa7571d4b6dd889193d90d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
