### ISSUE TITLE
Localization (Russian, maybe etc.) - Problems with output line to display!

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7391]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**1. There are no lines to translate some of the inscriptions into the menu of the editor.**
For example:
![Image 010](https://user-images.githubusercontent.com/93348499/142616070-fecb608d-3264-4aee-8083-31b06f5d2bf6.png)

**2. Lines for translation are present, but their translation does not result and is not displayed in the editor!**
For example:
**a)** 
 - Eng local:
`<sp.pickingtime.name>Picking Time</sp.pickingtime.name>
`
`<sp.pickingtime.description>How long it takes to pick up the item (in seconds).</sp.pickingtime.description>
`
- Translation into Russian:
`<sp.pickingtime.name>Время демонтажа</sp.pickingtime.name>
`
`<sp.pickingtime.description>Время необходимое для демонтажа объекта (в секундах).</sp.pickingtime.description>
`

**b)**
 - Eng local:
`<sp.canbepicked.name>Can Be Picked</sp.canbepicked.name>
`
`<sp.canbepicked.description>Can the item be picked up (or interacted with, if the pick action does something else than picking up the item).</sp.canbepicked.description>`
- Translation into Russian:
`<sp.canbepicked.name>Можно демонтировать</sp.canbepicked.name>
`
`<sp.canbepicked.description>Возможно ли демонтировать объект (или взаимодействовать с ним, если он демонтируется или происходит какое-то еще действие).</sp.canbepicked.description>
`

**c)**
 - Eng local:
`<sp.allowingameediting.name>Allow In Game Editing</sp.allowingameediting.name>
`
`<sp.allowingameediting.description>Can the properties of the component be edited in-game (only applicable if the component has in-game editable properties).</sp.allowingameediting.description>
`
- Translation into Russian:
`<sp.allowingameediting.name>Редактирование в игре</sp.allowingameediting.name>
`
`<sp.allowingameediting.description>Можно ли редактировать свойства объекта в игре (только если компонент имеет свойства допустимые к редактированию в игре).</sp.allowingameediting.description>`

The first line translation, for each example, does not change!
The result of the translation in the submarine editor:
![Image 014](https://user-images.githubusercontent.com/93348499/142615507-c944823b-7cd1-4be5-8946-733dceae2060.png)

**Steps To Reproduce**
See the example in the description.

**Version**
Barotrauma v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Comment by Regalis11** [comment]
Thank you for the report!

The 1st issue is because we've so far decided not to translate all of the editable property names, because they change so much during the development and we would end up translating a lot of unnecessary text. But with the full release getting slowly closer, we'll get around to translating those too in the near future! We have a ticket about this in our private repo https://github.com/Regalis11/Barotrauma-development/issues/297

The 2nd issue should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f78536e7975f2ab55a0bacb687d4a1142dd0a909

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
