### ISSUE TITLE
Infinite Plasma Cutter

### ISSUE THREAD

**Issue by shadosx** [Regalis11/Barotrauma#7393]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You can use Plasma Cutter for unlimited time.

**Steps To Reproduce**
Use Oxygenite Shard as fuel for Plasma Cutter.

**Version**
0.15.13.0 Windows.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c04f93622e502549c20223504f5c729de3e94f8f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
