### ISSUE TITLE
[0.15.15.0] Shading of inner arm sprites: quartermaster.png, engineer_2.png

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7395]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Many clothes have inconsistent shading of inner limbs (more on that below) but 2 sets have completely black inner limbs which is very noticeable in-game:

engineer_2.png (upper arm, lower arm and hand sprites)
![QKpsPOzJyv](https://user-images.githubusercontent.com/10529134/142652265-9d60d2d5-bcd2-4e8a-81dc-f727ca14714f.png)
![PicasaPhotoViewer_dC5iGzd1of](https://user-images.githubusercontent.com/10529134/142646135-d9d3d46b-81ce-4fe6-b96c-d9c7e50a1051.png)
quartermaster.png, (upper arm, lower arm and maybe hand, although not as bad as the engineer's clothes, but much worse than other clothes)
![Barotrauma_zg5WVPyA22](https://user-images.githubusercontent.com/10529134/142652615-894bb0e4-538f-41b1-a9ec-56bbe3375a45.png)
![PicasaPhotoViewer_pmQDwqSdhw](https://user-images.githubusercontent.com/10529134/142647577-3eb36e20-259d-46ae-9579-b3f68c70717e.png)

Some sprites, on the other hand, (no pun intended) have no shading of some inner limbs, such as assistant's and clown's clothes and as mentioned previously, some have heavy shading and some have light shading.
![PicasaPhotoViewer_4hKHRdP9z3](https://user-images.githubusercontent.com/10529134/142653177-2e31470c-44ec-4681-827f-7f6f27723b2e.png)
![PicasaPhotoViewer_Du6K3EnzkJ](https://user-images.githubusercontent.com/10529134/142653268-84ff324f-4fda-4235-a3ba-06658555aba1.png)

**Version**
v0.15.15.0

**Comment by Regalis11** [comment]
Fixed in v0.16
