### ISSUE TITLE
Lack of Mudraptors in Ruins from the Trailers

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7396]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So in the update trailer of Among the Ancients, at around 2:03 mark, there were mudraptors co-existing with Fractal Guardians in ruins. That's missing from the actual game :(

![image](https://user-images.githubusercontent.com/5086682/142662520-9675c53a-42d6-4a10-b2bf-442616d3dcac.png)

**Version**
~0.15.15.0

**Comment by HeatedWafflez** [comment]
:moyai: .
