### ISSUE TITLE
Sub editor bugs regarding item quality, unique items, and pirate stuff

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7397]
- [ ✔ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The quality component for items sadly does not have a way to change item quality in sub editor, we have to rely on the console command "setentityproperties quality" for this.

Also, item quality seems like it's not saved to the item, because copy-pasting a quality 3 item results in a normal quality version.

![Screenshot 2021-11-19 164949](https://user-images.githubusercontent.com/69410159/142652004-f6717b8b-3352-4fff-b898-85c57d3f54d4.png)

Unique versions of items aren't available in the sub editor, even through the spawnitem console command. It used to spawn an invisible non-removable item in earlier versions.

![Screenshot 2021-11-19 170049](https://user-images.githubusercontent.com/69410159/142653353-97ef8e38-8ec9-4f95-b27b-6861bf7f461d.png)

In single player mode / campaign, as suggested by 3e849f2e5c, you can spawn the item in-game and then use the command "subeditor" and it will be visible so you can select and alter it.

![Screenshot 2021-11-19 171342](https://user-images.githubusercontent.com/69410159/142656497-215ae61e-6a2d-4251-add1-e5aa880bad78.png)

but.. It becomes invisible if you move it in and out of a container. Going back in game after this removes the item.

![Screenshot 2021-11-19 171646](https://user-images.githubusercontent.com/69410159/142656053-b63014a9-b4a7-44f6-94ef-e3357a2135bc.png)

Additionally, switching between subeditor and gameplay through "game" command is prone to bugs so it's not a real fix around the issue, also since it's single player only.

![Screenshot 2021-11-19 171753](https://user-images.githubusercontent.com/69410159/142656459-ecc7e966-1625-4e91-b0a8-0c4de1c5892d.png)

**Steps To Reproduce**
1. Start campaign and spawn any unique item, such as "spawnitem "Boom Stick" cursor" .
2. Type "subeditor" in console.
3. Your camera will be placed on the sub, scroll up to the outpost and locate the item.
4. Create a supplies cabinet nearby.
5. Select the unique item and type "setentityproperties quality 3" in console.
6. Shift-drag the item into the cabinet, then type "game" into console.
7. Confirm that the item is inside and works properly, then go back into subeditor with the command.
8. Drag the unique item out of the cabinet, close the cabinet and move the item someplace else, and go back into gameplay via "game" command.
9. Confirm item no longer exists.

**Version**
Latest Unstable, Windows 10.

**Additional information**
Also noteworthy is, after spawning any item and going into subeditor, instead of dragging the item inside a cabinet, drag it up into the air and resume gameplay. The item will be stuck floating in the air as if it was in a weapon holder and you can click to pick it up. 

Any items spawned while in sub editor will be automatically invisible (but selectable at least) and will properly spawn when retuning to gameplay, but ONLY if you do not move it after spawning it. (Weird stuff, see video example below)

https://user-images.githubusercontent.com/69410159/142660618-4e4609d7-d69b-4c7c-85c6-c6b161fef6fb.mp4

Finally, I'd like to mention pirate items have not been added to the "spawnitem" command's tab autocompletion list. If you want to spawn a pirate item you will have to look up the name in sub editor and remember it.

And with pirate items and clothes in general with multiple versions like the "pirate costume", the command "spawnitem "Pirate Costume" inventory" will give you the middle tier one with 30% damage protection. They don't have unique names so you can't do "spawnitem "Pirate Costume 1" inventory" or anything like that. This is true for outpost outfits too.

**Comment by Regalis11** [comment]
Fixed the quality issues in https://github.com/Regalis11/Barotrauma-development/commit/4d2bf52792b272d88ad28d02a303c6f8914d4aa4 and spawnitem command not working in https://github.com/Regalis11/Barotrauma-development/commit/908fd372b4801ca5c50b7fa6ca989f77e6db7cb1.

I didn't touch the rest of the issues, because switching to the editor and back mid-round is not intended to be something you can reliably use, and as mentioned in the warning, it can lead to bugs (such as the ones you mentioned).

>Finally, I'd like to mention pirate items have not been added to the "spawnitem" command's tab autocompletion list. If you want to spawn a pirate item you will have to look up the name in sub editor and remember it.

This doesn't seem to case, they seem to autocomplete as expected. There's just a bunch of structures starting with the word "pirate" that you need to skip past before you get to the items. Many of them have the same name, so it may appear as if tab didn't skip to the next name - fixed that in https://github.com/Regalis11/Barotrauma-development/commit/4d4812db6a9e4f89df32570114c22e9a73757b09 by only adding each name to the autocomplete list once, even if there's multiple items/structures with the same name.

>They don't have unique names so you can't do "spawnitem "Pirate Costume 1" inventory" or anything like that. This is true for outpost outfits too.

You can also use the items' identifiers to spawn them, e.g. "pirateclothes", "pirateclothesnovice", "pirateclotheshard".

**Comment by Marutzo** [comment]
Understood, appreciate the partial fix. Hope unique items will be available with the fixed spawnitem command in sub editor. Didn't know about spawning with identifiers, that was educational, Those are only viewable through xml I think? Would be a nice quality of life addition if it was displayed in sub editor too.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
