### ISSUE TITLE
"Ph.D in Nuclear Physics" talent lowers electrical devices' repair threshold to 56%~

### ISSUE THREAD

**Issue by Jvisti** [Regalis11/Barotrauma#7398]
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After selecting the engineer talent "Ph.D in Nuclear Physics" you can only repair electrical devices at 56%~ condition vs the default 80%~. 

**Steps To Reproduce**
Choose "Ph.D in Nuclear Physics" and try to repair electrical devices below their usual threshold.

**Version**
0.15.15.0 Unstable (Windows 10 Home 21H1)

**Additional information**
Seems related to the bug with device deterioration submarine upgrades (was fixed in 0.15.14.0).

**Comment by Marutzo** [comment]
If I remember correctly, you had 70% slower deterioration speed from sub upgrades, so your electrical items would have a total of 170 condition.

80% of 170 would allow you to repair 136~ condition.
However, we discovered 40% bonus condition added through the "Ph.D in Nuclear Physics" is an increase of 40% of your total condition, not a flat 40 points.

170 + 40% = 238.
And 80% of 238 should allow you to repair at 190.4~

But this is not calculated correctly, so it bases repair threshold on the original condition of 170 before "Ph.D" talent is taken into account, thus 136 / 238 = 56% repair threshold.

**Comment by Jvisti** [comment]
Yes that's correct. Our submarine (Typhon 2 if that matters) has 70% upgraded durability for electrical devices. Forgot to mention it, thanks!

**Comment by Jvisti** [comment]
Did some additional testing in sub editor with an unmodified Dugong. I added xp to the engineer and chose Ph.D in nuclear physics + set skills to 100 so the over-repair is active. 

If the player is controlling the engineer, you can't repair boxes at their normal threshold but AI controlled engineers can (tested by swapping to another character and gave the maintenance command). The AI proceeded to fix all electrical devices below 80% condition successfully.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d6ec2a535a595513146b585cd4e7f2d46f5b7d36

**Comment by Jvisti** [comment]
Can confirm this is now fixed in unstable 0.15.16.0

**Comment by Rokvach** [comment]
Closing
