### ISSUE TITLE
Crosshair does not appear when aiming with the Alien Pistol

### ISSUE THREAD

**Issue by Cusuno** [Regalis11/Barotrauma#7399]
- [✔] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Normally you would see a crosshair appear when aiming with any kind of weapon, such as revolvers.
However, this does not seem to be the case when aiming with Alien Pistols and the cursor remains unchanged.

**Steps To Reproduce**
Equip an Alien Pistol and aim with it.

**Version**
v.0.15.13.0 Windows 

**Additional Information**
Attached some screenshots below as reference
![Revolver](https://user-images.githubusercontent.com/91386792/142665230-4b005682-1ab1-490e-9f08-e5b4a00515f3.PNG)
![Alien Pistol](https://user-images.githubusercontent.com/91386792/142665244-377a40f8-d28e-4ff8-a83f-aaf2b6a59067.PNG)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a6937181c52ee6962a9e9e2ed554c87f8e86a9cb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
