### ISSUE TITLE
Is It a Good Time To Publish New Version of Barotrauma?

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#740]
In the past few days I noticed playerbase of Barotrauma have dropped. It always drops, when no updates are made in some time. Introducing a new update to Barotrauma now would prove people, that progress were made and restore for few weeks popularity to the game.

**Comment by BlueTheKing** [comment]
Rushing an update isn't the solution.

**Comment by CommanderMark** [comment]
> In the past few days I noticed playerbase of Barotrauma have dropped.
Did you go down to the local lake and measure the pH level of Barotrauma's player base?

Anyway it seems like the game's gearing for a Steam release, so alongside that, they're sitting on a ton of changes so that the first commercial release has a sizeable amount of new material. And, unsurprisingly, game development takes time.

**Comment by rico6822** [comment]
Ok.

**Comment by Regalis11** [comment]
Yep, at the moment we're mostly focusing on getting the game ready for a Steam release, and most of the work is happening in the dev branch (and most of the new features in there will not be released until Steam).

I apologize for the lack of blog posts or any sort of updates about what's going on with the development - this year we've been trying to make a collaboration deal with a game studio I've been working at for some time now, and I haven't wanted to make an official announcement until all the legal questions have been worked out and the contracts signed. But we're starting to be at the point where all the paperwork is out of the way and we can shift to a higher gear and do an update about what's going on and what the future plans are. Possibly next week!
