### ISSUE TITLE
Loading Screen Typo

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#7400]
- [Yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of the loading screens spells Mudraptor as mud raptor. It is not spelt like that anywhere else in the game.

![20211119092006_1](https://user-images.githubusercontent.com/91236493/142665397-b04e5aac-c698-47b8-8a7a-023ec040f0ae.jpg)

**Version**
The latest unstable, but I believe the typo has been around for at least over a year.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3cd7a8b7fb409a0183cb3c6ee64a6386f5924149

**Comment by Rokvach** [comment]
No issues, closing.
