### ISSUE TITLE
Human Husk has incorrect sprite in Character Editor.

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#7401]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The humanhusk in the character editor also displays the sprites for the mudraptor and spineling mutations. This causes them to have a mudraptor beak, husk stinger, and back spines all at once. The spines and beak do not seem to be actually functional, so its likely a purely visual issue.
 
![image](https://user-images.githubusercontent.com/91236493/142667386-f9dc1e6f-30cb-4ae9-a85c-64d75cbf3b76.png)

**Steps To Reproduce**
Open up the character editor and select the humanhusk.

**Version**
Latest unstable, but this issue has been around since the unstable that implemented the new human models.

**Comment by Regalis11** [comment]
This is not a bug: all the "extra appendages" a human can grow are defined in the same ragdoll file, which causes them to show like this in the editor, and allows editing them in one place without having to define 3 different ragdolls.
