### ISSUE TITLE
"Added submarine" - does not display the structures of submarine that have been added.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7402]
- [x] I have searched the issue tracker to check if the issue has already been reported.

It may not be a bug, but for this reason elevator to move ammunition and ammo (how I invented it) not work at my submarine, because "wide"-elevator is invisible. ))

**Description**

The problem arisen from [this idea](http://github.com/Regalis11/Barotrauma/discussions/7432).

If the structures of the added submarine located far from its `hull`  - the structures are displayed only when the zoom is reduced (freecam mode). The further the structure from the `hull` is, the less scale is needed.
...Just watch attached video:

https://user-images.githubusercontent.com/93348499/142743019-0f721932-1414-4d1e-af76-eaafdc695506.mp4

**Steps To Reproduce**
1. Watch attach video
2. Download `submarines.zip` and run main submarine `_Test_Main-SUB.sub` with shuttle `_Test_Add-sub.sub` in the submarine editor: [Submarines.zip](https://github.com/Regalis11/Barotrauma/files/7572027/Submarines.zip)
3. Use console command `freecam` for free zoom, as in the video.

**Version**
Barotrauma v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Unfortunately, there is no tool for creating elevators and other moving devices, such as sliding weapons turret, and etc in the game.
If you want to create something like this, you create an object as an extra submarine!
And you use:
- "Docking ports" - as endpoints.
- "Pumps" - as a motor for vertical motion.

I created an elevator in the game! And it works well, BUT...!

To move vertically it is necessary to place the pump in the "hull" (elevator engine). And to create the elevator itself (for example "cabinet", "Shell Rack" or "pillar of ammunition" etc.).
Together they are a "separate submarine"!

The movement of `elevator engine` is only possible in a separate vertical tunnel (outside your submarine).
Therefore, in a large boat such a tunnel is located at the edge of the submarine and the `elevator` itself (the cupboard, the post of ammunition) can be located at a great distance from its `elevator engine`.

That’s where the problem comes in!
In the game, attached submarines (your elevator) have an unpleasant feature.
- When your elevator is near its engine, everything’s fine.
![Image 014](https://user-images.githubusercontent.com/93348499/142664884-d23b3d66-ddfb-4f7e-add8-523b21c1c987.png)
- When they are wide - located far apart from each other, the elevator body is invisible in the game.
![Image 020](https://user-images.githubusercontent.com/93348499/142664921-a1757f9e-459b-471e-bd90-30a0dff8e791.png)
The peculiarity is that the further away your `elevator` is from its `elevator engine` - the more you need to reduce the scale (in freecam mode) to make your `elevator` visible.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/40b90afca4b6c0583880c078d49b934af939fb2b.

The problem was that the game only took the structures with a physics body into account when determining which submarines are visible.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
