### ISSUE TITLE
Expert Commando needs a HUD icon

### ISSUE THREAD

**Issue by panvxv** [Regalis11/Barotrauma#7404]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 Expert Commando when crouched gives you buff to damage as well as debuff to firing rate speed. This can work not only when you are crouched but also when you are swimming and you are holding your crouch button.
 Some would think this is a bug but I think this is a feature :)

 It would be nice if this talent could give you notification on HUD(above healthbar) when you are holding button that makes you crouched that it is working.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/c5b864277e93643b491eee10eca5d777ddbe7368

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
