### ISSUE TITLE
Having bandolier in toolbelt slot and not outerwear

### ISSUE THREAD

**Issue by panvxv** [Regalis11/Barotrauma#7405]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Toolbelt slot right now is use only for toolbelt that is used and made by everyone as other items like big weapons (auto shotgun, grenade launcher) need to be made when having talent or you have to find them making those items hard to get, so everyone are just using toolbelts.

Bandolier would be nice addition to the spectrum of things that can be wear in toolbelt slot as there is no many of them.

Such change would make Gunsmith talent and bandolier much useful. Not only you can use it during swimming when still having diving suit on but also security officers would be much better prepared.

It would also make talents better work with eachother. Security officer could use Navy Diver(Slipsuit), Deep Sea Slayer and Gunsmith (Bandolier) with all of those working making builds even more fun and every point spend on talent more worth.

There are of course drawbacks such us not having so many slots for items when having both toolbelt and bandolier.
Big weapon would have to be in hands all the time or dropped when you want to use other item.

**Comment by MaaiG** [comment]
I think it’s odd that a `bandolier` can’t be worn on a `body armor`!

**Comment by Marutzo** [comment]
It does give increased attack speed for weapons, that's the only "balance concern" I can think of.

**Comment by StruggleDuck** [comment]
Im pretty sure the main idea behind the bandolier is to provide the user with more space for storing ammunition when using things like the assault rifle and autoshotgun, as it takes away the ability to use the toolbelt as a means of storing ammo.
