### ISSUE TITLE
Balance Inconsistencies : Afflictions Received From Explosions

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7411]
> Some explosions deal 'explosiondamage' which is a damage-type affliction, but many from weapons only deal burn type 
> which - with the reverted changes to how damage resistances work - means enemies take very little damage from burns.
> I've found this damage-type inconsistency to be odd and may deserve its own ticket.
> _Originally posted by @Ek-Videogames in https://github.com/Regalis11/Barotrauma/issues/7347#issuecomment-972590747_

Explosive items and projectiles give varying types and amounts of damage, one of which being burns. However as result of many monsters being immune to burns - or conversely taking more damage from burns - items relying on primarily burn affliction for their explosion AOE can be very weak when they shouldn't be.

With internal-damage being branched into blunt, organ, and tissue damage - it makes sense that 'explosiondamage' should now be a more primary affliction in causing damage by explosions. 
_( Plus it doesn't make much sense to be getting damaged more by the heat of an explosion rather the shockwave. )_

As some examples:
- Stable explosives, UEX, C-4, Compund-N, IC-4
- Explosive coilgun ammo causes exclusively burns in its AOE
- Incendium grenade ( can be argued that its initial blast should still cause tissue-damage )

Items which use combinations of other afflictions such as explosiondamage and lacerations:
- Frag grenade
- Explosive harpoon
- 40mm grenade

**Edit:**
I also neglected to mention shotgun "explosive" slugs. They function very poorly due to primarily causing burn damage, although this makes sense thematically with them being made of incendium - the natural burn resistance of many monsters and crew clothes makes them perform worse than standard shot in almost all scenarios. Range however does serve a benefit.

**Further Edit:**
I just realized, with regards to Issue #7347 and #7112 this means fractal guardians also are going to be immune to pulse lasers too, technically not an explosive weapon in the traditional sense. - Although to be fair you will not often be fighting them outside of a ruin with pulse lasers.

**Comment by Regalis11** [comment]
Thank you for the report! We're aware that explosion damage is now a bit all over the place, especially after the changes to burn damage. We've got already got an [existing ticket](https://github.com/Regalis11/Barotrauma/issues/7365) about balancing the explosions though, so I'll close this one.
