### ISSUE TITLE
Bots will still attempt to path through doors that are set or 'ignore' but won't be able to open them

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7412]
**Steps to Reproduce:**
- Order bots to 'ignore' a door in a remote part of sub or an area with multiple paths
- Cause bots to target something like a repair item or a 'follow me' order that causes their path to include the door
- Bots will try to still use the door in their navigation path, but the ignore order will prevent them actually clicking it to open it.

**Expected Behavior**
It is up to dev interpretation if the "intended behavior" for the ignore order is that bots should not use the door altogether - IE not allow bots to path through the AI-node of a prohibited door, or bots should be able to open and close 'ignored' doors just not target them as part of an AI repair goal. 

The former might be useful to allow us to 'prohibit' bots from entering rooms like milling about in armory or trying to enter the 'artifact storage room' on a custom submarine.

**Comment by itchyOwl** [comment]
Cannot repro: I ignored a hatch, told a bot to follow me, teleported behind the hatch, and the bot attempted to go around using a longer path. When I also told the bot to not use the other door, it didn't find a path.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/70ad2284-4744-4876-8c36-f5a35b195908)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/7d34c4b1-5926-4f2c-b9a1-a2302088b878)
