### ISSUE TITLE
Remora : supplies delivered in the sub hull

### ISSUE THREAD

**Issue by Zhertva** [Regalis11/Barotrauma#7415]
**Description**
With the **Remora** sub, after buying small items and leaving a station, delivered supplies crates pop into the sub bottom hull and are impossible to take excepting by cutting the shell with a plasma cutter. 

**Steps To Reproduce**
Take Remora, buy small item suppliers go down to the Cargo room. If you are fast enough you can see the crate (left image) but it's impossible to click on it. After a moment the crate completly disapear (right image), but the crate is still there and if you completly cut the hull with a plasma cutter you can take it back.

![remora](https://user-images.githubusercontent.com/85393144/142719963-b39c5336-4222-4445-b908-6bc534d4b0bb.jpg)

**Version**
Win10. I can't tell when the bug appeared because i changed my sub recently, but the bug occurs in v 0.15.13.0

**Additional information**
The bug systematically occurs. Crates from previous missions can accumulate into the wall.

**Comment by Regalis11** [comment]
Related ticket: https://github.com/Regalis11/Barotrauma/issues/7387 (seems to be the same issue but in a different sub)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91b1c5cfa01abc18dc2dfea371e0f0cba5692394

**Comment by Lithosagym** [comment]
Tested, Remora cargo no longer clips into the submarine, fixed.

**Comment by Rokvach** [comment]
Closing.
