### ISSUE TITLE
Severe performance drop in latest update

### ISSUE THREAD

**Issue by Leonidas-ai** [Regalis11/Barotrauma#7418]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Severe performance drop in latest update

**Steps To Reproduce**
Load any sub with 10,000 items, 20,000 lights, 5,000 casting lights preferably in search and destroy to emphasize the issue. Attempt to play in 0.15.13.0 and observe CPU usage, low fps, and stuttering. Play in 0.14.9.1 with no problem.

**Version**
0.15.13.0

**Additional information**
No additional remarks

**Comment by Leonidas-ai** [comment]
[Paradise Lost.zip](https://github.com/Regalis11/Barotrauma/files/7582346/Paradise.Lost.zip)
If a sub file is required for testing, I suggest the Paradise Lost as a reasonably designed large sub towards the maximum expected limits of the game engine.

**Comment by evilfactory** [comment]
I noticed significant performance loss in the latest update, i used to get somewhat consistent 60 fps on Prometheus Station, but now fps starts at somewhere around 40 and drops to almost 10 when the action on the round starts.

**Comment by Leonidas-ai** [comment]
Please, more people report this issue. Current unstable appears to exacerbate the problem and it's unlikely this will be fixed for the Christmas update if no one mentions what a huge problem this is. If anything, it will be worse.

**Comment by Rokvach** [comment]
I'm noticing a notable performance increase but I wouldn't still classify the Paradise Lost as a playable submarine as I get 40 fps out of my normal 170 fps when using it. Prior to entity update improvements my fps was around 15.

**Comment by Rokvach** [comment]
Deciding to close this as the Paradise Lost is really pushing the performance and even getting 40 fps while using it is a lot better than before. Closing.
