### ISSUE TITLE
Medical Curtain is static and cannot be opened or closed (easy fix included).

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#7419]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The medical curtain is a static decoration element. It'd be cooler if it could be opened and closed with a click.
This is an issue *because of the implication*.
XML fix in additional information.

**Steps To Reproduce**
Sure.

**Version**
Windows 0.15.13.0.

**Additional information**
Item identifier is not a valid identifier right now, use your own.
Also there could be a moving curtain sound included in the controller itemcomponent (example in switches and levers in *Content/Items/Button/button.xml*).
```xml
<Item name="" identifier="opdeco_medcurtain" category="Decorative" width="416" height="32" scale="0.5">
  <Sprite texture="Content/Map/Outposts/Art/MedBayAssets.png" sourcerect="96,128,416,32" depth="0.49" premultiplyalpha="false" origin="0.5,0.5" />
  <DecorativeSprite texture="Content/Map/Outposts/Art/MedBayAssets.png" sourcerect="512,128,384,368" depth="0.48" premultiplyalpha="false" origin="0.5,0.05">
    <Conditional targetitemcomponent="Controller" State="eq true" />
  </DecorativeSprite>
  <DecorativeSprite texture="Content/Map/Outposts/Art/MedBayAssets.png" sourcerect="896,128,128,368" depth="0.48" premultiplyalpha="false" origin="1.5,0.05">
    <Conditional targetitemcomponent="Controller" State="ne true" />
  </DecorativeSprite>
  <Controller direction="None" canbepicked="true" istoggle="true" msg="ItemMsgPressSelect" />
</Item>
```

**Comment by MaaiG** [comment]
Great! Plus, maybe clicking on the monitor screen to open a window with the camera connected to it is also a not bad idea...

**Comment by Regalis11** [comment]
That's a great idea, thanks! Implemented in https://github.com/Regalis11/Barotrauma-development/commit/12c0a5d82609ad4d0e26db4e0210d1e9073bc438
