### ISSUE TITLE
'flashduration' acts strangely when second decimal is used

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7420]
When an `Explosion`'s `flashduration` is defined and uses two decimal places (hundredths) the flash behaves strangely. If the flash duration is <1s the fading animation seems to loop continuously for the duration of about 1 second, can appear as a strobelight if the value used has a small number in the 'tenths' position.

**Steps to Reproduce:**
- Explosion flash duration set to any value with nonzero in the hundredths position such as:
`flashduration="0.31"` `flashduration="0.09"` `flashduration="0.25"`

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/24df3699615b018f7f66dcf82b31f9ad6273005e

**Comment by Rokvach** [comment]
Tested, no issues. Closing
