### ISSUE TITLE
still getting reaper's tax when respawning at a base

### ISSUE THREAD

**Issue by Ozzieeee** [Regalis11/Barotrauma#7422]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When i respawn at a station, i'm still getting reaper's tax

**Steps To Reproduce**
Die, respawn at a station 

**Version**
windows, among the ancients

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e059c45acb2db377e964ebbc7062d4cedaf6ab53

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
