### ISSUE TITLE
Outposts do not spawn when abandoning sub

### ISSUE THREAD

**Issue by Yooxs** [Regalis11/Barotrauma#7427]
During a campaign game, our sub had suffered catastrophic damage beyond repair. We decided to abandon it and swim to a nearby outpost to buy a new one. When we arrived at the outpost location (as per the handheld sonar) the outpost was nowhere to be seen. I suspect the outpost is only loaded into the game when the players are close enough, but approaching the outpost in diving suits (while the sub sank) did not load the outpost.

**Comment by Regalis11** [comment]
> I suspect the outpost is only loaded into the game when the players are close enough

This is not the case actually, the outposts should be loaded at the beginning of the round. Are you sure the was an outpost at the end of the level, and that you weren't heading towards an uninhabited location? Do you still happen to have the save file available so we could give it a test?

**Comment by Regalis11** [comment]
No known steps to repro, closing
