### ISSUE TITLE
Color component on HSV only outputs 0 to 1 instead of 0 to 255.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#7428]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a Color component is set to HSV mode, the red, green and blue values in the output are only 0 to 1 instead of 0 to 255.

**Steps To Reproduce**
1. Place down and set a color component to HSV mode.
2. Input 1 to the green and blue pins, and 255 to the alpha pin.
3. Input any number from 0 to 360 into the red pin.

**Version**
Windows v0.15.15.0

**Additional information**
Non-HSV mode works completely fine.

**Comment by Jade-Harleyy** [comment]
Edit: also an issue on stable version Windows v0.15.13.0

**Comment by Regalis11** [comment]
This is intentional https://github.com/Regalis11/Barotrauma/discussions/4967

**Comment by Regalis11** [comment]
Oh, I read this a bit too hastily: the inputs should be interpreted as being between 0-1, but the outputs should be 0-255.

**Comment by 3e849f2e5c** [comment]
Changed in https://github.com/Regalis11/Barotrauma-development/commit/40c24274cd97578be4a3baf8e5141ca83132b756

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
