### ISSUE TITLE
Reaper Tax returns at base without a second death

### ISSUE THREAD

**Issue by VictoriaSteger** [Regalis11/Barotrauma#7429]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On a multiplayer server, a character died on a mission, chose to respawn mid-mission, and paid the reaper's tax when visiting the next base.  The negative penalties were removed and the icon for the tax in the health menu disappeared.  The ship left on a new mission, completed it, and went to a new port, and the reaper's tax had been reapplied, despite that character not dying a second time.

**Steps To Reproduce**
-die on a mission
-chose to respawn
-complete the mission and dock at the next base
-pay the reaper's tax
-start a new mission
(Unsure if relevant: have a different player die on that mission)
-complete the mission and dock at the next base

**Version**
From the bottom left of the title screen: Barotrauma v0.15.13.0, ReleaseWindows, branch release, revision 4e66dd7b5d

**Additional information**
This happened for 3 different players over the span of a few missions.  (The 4th player never died, and never had the tax applied for any reason.)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e059c45acb2db377e964ebbc7062d4cedaf6ab53

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
