### ISSUE TITLE
Adhesive Tape- (Item) Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#743]
Adhesive tape can be equipped into headset slot. It prevents it's wearer from speaking. Can be used if a cuffed player is being annoying and won't stop speaking. Huskified players can destroy adhesive tape on them by using "a strange chitinous appendage".

**Comment by thegrb93** [comment]
Just take their radio

**Comment by rico6822** [comment]
What about people near them?

**Comment by Regalis11** [comment]
Duplicate of #413
