### ISSUE TITLE
[Unstable 0.15.15.0] Slipsuit locker sprite not found

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7431]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Placing a slipsuit into a locker in sub editor throws a error that the sprite can't be found

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/28c345d5-da93-42a4-a80e-1116c063399e)

**Steps To Reproduce**
Open up sub editor, place a "Diving Suit Locker" select Slipsuit and place it inside the locker, error should popup

**Version**
Unstable 0.15.15.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2936148f9b86881f02ca65ed5d08505280f01194

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
