### ISSUE TITLE
Player spawns as if they were dead if the server ended round in campaign while they were loading in

### ISSUE THREAD

**Issue by LukeS5310** [Regalis11/Barotrauma#7433]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Player spawns as if they were dead if the server ended round in campaign mode

**Steps To Reproduce**
1. Player joins the server while round in campaign is underway, and selects to load as spectator
2. Server ends round while the player is lodading (e.g. docking to station)
3. Player spawns with starter inventory even if they had some items before (Skills, talents and appearance remains)

**Version**
Windows 0.15.13.0

**Comment by Krzeszny** [comment]
It happens very often when restarting a server. For me it's almost every time.

**Comment by Rokvach** [comment]
Tested, we didn't encounter this while explicitly testing all the potential ways, working correctly. Closing.
