### ISSUE TITLE
Coilgun ammo loaders damaged, but cannot be fixed

### ISSUE THREAD

**Issue by salunn** [Regalis11/Barotrauma#7436]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the Dugong vessel, the coilgun loaders can get damaged so that they smoke, but they cannot be repaired manually or with the "repair all items" upgrade bought at a station.

**Steps To Reproduce**
Unclear, in our campaign the vessel got very badly damaged and the command area got massively flooded for a long time. The loaders started smoking then and have not stopped since.

**Version**
Running on the Steam-bought PC version 0.15.13.0.

**Additional information**
-

**Comment by Regalis11** [comment]
Have you purchased the "enhanced durability" upgrade for mechanical devices? There's a known issue that causes problems with the repair thresholds when devices' maximum condition is increased: https://github.com/Regalis11/Barotrauma/issues/7085

**Comment by salunn** [comment]
Good catch, I actually have bought the upgrade. Seems like this is the same issue then.

**Comment by Xardion495** [comment]
Hello. It's also affects to all mechanical items like engines, fabricators, deconstructors, oxygen generators, pumps, etc.
Guess if buy an electrical upgrades we'll see the same results.
