### ISSUE TITLE
Outpost Fabrication problem

### ISSUE THREAD

**Issue by Outsider1273** [Regalis11/Barotrauma#7437]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I attempted to craft Abyss Diving Suit on Military outpost fabricator, then went away to do one thing on sub and when I came back, there was absolutely no trace of the suit or the materials used. I searched whole station and submarine, no trace. 

**Steps To Reproduce**
Put resources into Fabricator on station, select Abyss diving suit and go away from fabricator for about 6-7 minutes (probably, haven't measured the time)

**Version**
Win 0.15.13.0

**Additional information**
I don't think there's anything I could add

**Comment by MaaiG** [comment]
It would be cool if the bots stole them! )

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to reproduce this. I wonder if the bots could've stowed the suit away in some cabinet somewhere?

**Comment by Regalis11** [comment]
No known steps to repro, closing
