### ISSUE TITLE
`amount` does not function inside `<RequiredItem/>`

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7438]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While `amount` works correctly in Deconstructor recipes such as `<Item identifier="steel" amount="2"/>`
...it does _not_ function in Fabricator recipes:
`<RequiredItem identifier="steel" amount="2"/>` will ignore the amount. I think I recall it working correctly in the past.

**Steps To Reproduce**
Add `amount="2"` (or any number) to any fabricating recipe. `amount` will be ignored.

**Version**
v0.15.13.0

**Additional information**
One workaround is adding multiple lines at once:
```
<RequiredItem identifier="steel" />
<RequiredItem identifier="steel" />
```
which correctly makes the recipe require a stack of 2 Steel.

**Comment by Regalis11** [comment]
Looks like the attribute was called "count" for some reason - I made it accept both "amount" and "count" in https://github.com/Regalis11/Barotrauma-development/commit/ffef0a5f9abc44b222a89924b4c3d09bee1a5eb6.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
