### ISSUE TITLE
Changes in Oxygenite Shard- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#744]
* Oxygenite shard drains it's condition, while it replenishes oxygen inside hulls.
* To ensure oxygenite shard is gonna keep it's condition on 100% before deconstructing, air quality must be less than 82% for it to give oxygen to hull.

Note:
Oxygenite shard would give players immortal life under water for it's unlimited oxygen. That's what this change is for.

**Comment by thegrb93** [comment]
They don't provide any air to the ruins so why in the ship?

**Comment by rico6822** [comment]
Not everybody knows it, but oxygenite shards already fill rooms with oxygen. See gamepedia.

**Comment by Regalis11** [comment]
I think the risk of having the shards explode keeps them balanced enough. There was however the loophole that you could store them safely inside a cabinet and still have them replenish the oxygen, but as of 42cb2b1 that's not a problem anymore.
