### ISSUE TITLE
UI Glitch on New Campaign Crew Menu

### ISSUE THREAD

**Issue by AKiwiMain** [Regalis11/Barotrauma#7440]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I am in the crew selection screen for a new campaign, if I press down arrow key followed by up arrow key, the frame bugs out and rapidly flips over to the ship selection screen back to the crew selection screen. To my understanding, the down arrow key is supposed to take you to the previous screen, as sometimes it will and sometimes it does nothing or glitches out like reported.

**Steps To Reproduce**
Select new game.
I found that both starting vessels have this issue.
Select any settings for crew cosmetics.
From here, attempt to recreate with arrow keys.

**Version**
Windows 10 home, on version 0.15.13.0, revision 4e66dd7b5d

**Additional information**
I understand this is a very minor bug, but wanted to report it regardless to help the quality of the game, I love it and keep it up! :)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c7c90dfa0afa7af1346b08d559dfaa7d4a4c2b99

**Comment by Lithosagym** [comment]
Tested, scrolling with arrow keys no longer messes up the campaign start menu, fixed.

**Comment by Rokvach** [comment]
Closing.
