### ISSUE TITLE
Weapons skill above 100 makes weapons less accurate

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#7441]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a character's "Weapons" skill is greater than 100, then handheld weapons will become less accurate.

**Steps To Reproduce**
1. Fire a loaded SMG at 100 weapons skill.
2. Fire a loaded SMG at 500 weapons skill.
3. Compare shot accuracy.

**Version**
Windows v0.15.15.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a85e7d87e5b0043de0f98513bdec68fefd32c032

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
