### ISSUE TITLE
Going thru hatches with water sensitive items has a chance to glitch out the character

### ISSUE THREAD

**Issue by 3e849f2e5c** [Regalis11/Barotrauma#7442]
Going thru docking hatches with inventory full of items that explode in water and an auto-injector headset has a chance to glitch out the character for other crew members in multiplayer

Steps to repro:
- Have 2 clients in a multiplayer campaign
- Give one of them an auto-injector headset with fentanyl inside and a storage container full of Salt Bulbs
- On the character with an auto-injector go thru the docking hatch into the outpost and back couple times
- On the 2nd client you should eventually see the other character's dead body flailing around and the auto-injector constantly going off causing lag
- Taking the auto-injector headset off for couple seconds will return the character to normal

**Comment by Regalis11** [comment]
This seems to be related to https://github.com/Regalis11/Barotrauma/issues/7449: the gaps/hulls between the sub and the outpost generate incorrectly client-side, which causes water to accumulate there and trigger the InWater effects at the client's end.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3f50df38fe501c1fe94d035b3c22641da2f9df64

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
