### ISSUE TITLE
Crash in AIObjectiveGetItem.CountItems

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#7443]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash in AIObjectiveGetItem.CountItems

**Steps To Reproduce**
Unknown, but it seems that the AIObjectiveGetItem instance was created with the 1st constructor (which assigns the targetitem directly and leaves the IdentifiersOrTags array uninitialized) - I suspect a bot was trying to operate a welding tool in their inventory.

**Version**
v0.15.15.0, commit https://github.com/Regalis11/Barotrauma-development/commit/2a5c47a551354ee411d29f5b3634b3932d2db915

**Additional information**
![image](https://user-images.githubusercontent.com/14351070/142852617-ce9797ad-934f-4d94-b159-8f0bc11cd361.png)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@bcc71b9.

Steps to repro:
1. Cause a hull breach
2. Order a bot to repair that, using a contextual order

I guess any order triggering a contextual get item objective would do it. Like cleaning up something specific lying on the floor.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
