### ISSUE TITLE
Able to access contents of toxin cabinet when linked to med. fabricator, even when you don't have the proper id requirements.

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7447]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You are able to fabricate items using materials in the toxin cabinet (while it is linked to a fabricator), even when not having the right ID requirements.

**Steps To Reproduce**
Link a toxin cabinet to a medical fabricator, and put materials inside the toxin cabinet. Attempt to fabricate something that requires the materials inside the toxin cabinet.

**Version**
0.15.13.0

**Additional information**
Video of me demonstrating the bug:

https://user-images.githubusercontent.com/92034548/142921234-23ace1d0-9902-419e-9a46-36fed3336e84.mp4

**Comment by StruggleDuck** [comment]
Biggest issue with this bug that I have found is that when combined with the fact that crewmembers can search for items inside the sub, they can identify what poisons are inside the toxin cabinet, and by starting and canceling the respective antidote someone can easily remove any poison's that may be inside the cabinet.

**Comment by MaaiG** [comment]
> they can identify what poisons are inside the toxin cabinet,

Limited access cabinets should only be displayed for characters with appropriate access?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e8a9309cec85dcf2a91ba4c651713f745df2f8d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
