### ISSUE TITLE
Docking Hatch Lets Water Float in Mid Air at Outposts

### ISSUE THREAD

**Issue by Subodai2** [Regalis11/Barotrauma#7449]
- [X] I have searched the issue tracker to check if the issue has already been reported

When docked to a station there is a small area where water just floats in mid air in the docking hatch.

Take any sub into an abandoned outpost mission, open and close the outpost airlocks after a second and wait for the water to empty out, in between the docking hatches some water will be floating between the hulls

**Version**
Windows Version 0.15.13.0 hotfix

Obviously its not a game changing bug or anything, if someone is determined enough they could drown themselves in it which is kinda funny.  It does bother me a bit since every time I see it my brain goes "Wait that shouldn't happen". Just wanted to make sure you guys were aware. I'm loving the game otherwise!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7c350787dcfb4fae1a534998cf810ca7b84e80f1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
