### ISSUE TITLE
Assistant Talent "Rich in Knowledge" Gives Wrong Experience

### ISSUE THREAD

**Issue by Voideka** [Regalis11/Barotrauma#7450]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Assistant talent "Rich in Knowledge" gives all 30 experience to the Assistant, and none to allies.

**Steps To Reproduce**
Gain the "Rich in Knowledge" talent, then gain a skill point.

**Version**
0.15.13.0 Windows

**Additional information**
I have tested this in single player and multiplayer modes.

**Comment by M61Dev** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/841ae28346394e043294338d1a3e82a3951aecb9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
