### ISSUE TITLE
Server browser / lobby screen playstyle info mismatch

### ISSUE THREAD

**Issue by underscoren** [Regalis11/Barotrauma#7452]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The lobby screen always displays "Serious" as the playstyle, even if in the server browser info panel, the playstyle was something different.

**Steps To Reproduce**
 - Open server browser
 - Find server that doesn't have a "Serious" playstyle and note what it is
 - Join server
 - Find that the in the lobby screen the playstyle is displayed as "Serious", despite this being wrong

**Version**
v0.15.13.0 Windows

**Additional information**
N/A

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf1cfa39c4cade211c43ec7340bf8411b4afda4a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
