### ISSUE TITLE
Handheld status monitor glitchy UI

### ISSUE THREAD

**Issue by metakot** [Regalis11/Barotrauma#7453]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Handheld status monitor UI is bugged when outside of the sub, won't show the outlines and leaks.
Tested on Typhoon and Humpback.
Also when going to the outpost through outpost's doors the UI bug is switched to different state, outlines are returned, but leaks showing in wrong positions, and UI remains in that state even if I move inside the sub, and switched back to first mode when outside.

**Steps To Reproduce**
Get handheld status monitor, go outside.

**Version**
0.15.13.0 Windows
On screenshots there are some mods for characters, but without them the bug is the same.

![20211123103307_1](https://user-images.githubusercontent.com/5718037/142990216-1832c621-2dab-4071-ae82-d86b2d936954.jpg)
![20211123103355_1](https://user-images.githubusercontent.com/5718037/142990233-b70da641-ee04-4ecb-82eb-01f2174cafd1.jpg)

**Comment by metakot** [comment]
Also has a crash once, when handheld status monitor was activated outside. But can't reproduce.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7586623/crashreport.log)
e.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e895c12522c2ea0328e4246148a16fed43d3c09c

**Comment by Lithosagym** [comment]
Tested, bringing a handheld status monitor no longer shows water levels, character icons, and breaches from the previous ship, fixed.

**Comment by Rokvach** [comment]
Closing.
