### ISSUE TITLE
Upgrading Junction Boxes to 100% durability makes them unfixable

### ISSUE THREAD

**Issue by Cptcuddlybuns** [Regalis11/Barotrauma#7454]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After upgrading our Electrical Systems durability to 100% at station, the option to repair them no longer appears when holding a screwdriver.

**Steps To Reproduce**
Upgrade the electrical systems to 100%

**Version**
0.15.13.0

**Additional information**
The sub we were using is the Humpback, we had just started a new mission after leaving the station when we realized we couldn't fix the Junction Boxes. We were also using one of the new cores in the reactor so it goes overvoltage pretty often.

**Comment by ekqvist** [comment]
There's currently a known issue (#7085) that causes problems with the repair thresholds when devices' maximum condition is increased. This can happen by purchasing the "enhanced durability" upgrade for mechanical devices. The issue should be fixed in the Unstable version now.
