### ISSUE TITLE
Players can join public servers beyond max players allowed

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#7456]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes players can skip/disregard maximum players limit on public server.

**Steps To Reproduce**
No idea how to reproduce it reliably. I see 9/8 and 11/10 servers in servers list often though. So it should be reproducible relatively reliably.
In an occurrence I had, extra player started joining exactly AFTER I pushed 'Start' button.

More detailed sequence of actions I took:
1. Run Barotrauma.
2. Host Server. All relevant settings were preconfigured during yesterday's session (Public, Casual, Max Players 1, No Password).
3. Delete older campaign save.
4. Swap Humpback to Dugong.
5. Change preferred roles list.
6. 'Start' - failed because no savegame name was specified.
7. Specify savegame name.
8. 'Start' again.
Got server startup/connection pop-up - and new player https://steamcommunity.com/profiles/76561198123587937 started joining. Which should not happen as I have max players = 1 AND since even Spectator players take up player slots.
Extra player did spawned as a character (Medic). I did spawned in as Medic too.
The player was spawning in even after returning to lobby (??? a separate bug - max players is not respected if max was reached already prior to returning to lobby?)
Upon returning to lobby through ESC menu, the session force-started the campaign again (??? a separate bug?). Only fully leaving to main menu stopped this from happening.

**Version**
Win10 x64 Home RU (on extremely laggy laptop Lenovo IdeaPad L340-15API, SSD-less version)

**Additional information**
Server logs + configs:
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/7587346/Barotrauma.zip)

**Comment by Leonidas-ai** [comment]
Custom servers can allow any number of players to join.

**Comment by Ek-Videogames** [comment]
Master-server displaying information wrong / dedicated servers reporting the information to master server wrong seems like it would be a bug.

Just a hunch, but it may have to do with when clients are getting disconnected by any one of the various netcode wrinkles there is a part of the server that counts number of connections which still 'thinks' they are on the server because they never "properly" disconnected?

**Comment by DrinkFromTheCup** [comment]
> Custom servers can allow any number of players to join. That is not a bug.
I cordially apologize for sprinkling some... hmm... bile but...
If server's option is named Max Players, what is it expected to affect?
Friendly Fire? Monster density? Oxygen-to-repairs conversion rate? Hmm? Hmmmm?
If it's not a bug, then the option should be removed, to avoid cluttering GUI, that's what common sense sez.

**Comment by Regalis11** [comment]
Super late reply: but I finally got around to trying to diagnose this, and unfortunately couldn't find a way to reproduce the issue.

**Comment by Wheatley1001** [comment]
> This part might not be a bug though, the players who've opted to wait for a slot to free up on the server are included in the player count.

You can have a maximum of 17 players active in a lobby, the player count doesn't factor in the host. In a few sessions of my testing campaign we had 17 players playing the game at once with nobody in a waiting list for a free spot (tbh I didn't even know that was a feature...)

**Comment by Regalis11** [comment]
Still haven't found a way to reproduce this. The host does seem to be included in the count, and players in the queue don't seem to be included in the player count.
