### ISSUE TITLE
Expert Commando affects submarine turrets

### ISSUE THREAD

**Issue by MrBirdmann** [Regalis11/Barotrauma#7457]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Holding ctrl while operating a sub gun with Expert Commando will apply the talent's damage and armor pen buffs, but won't decrease firing speed like with small arms.

**Steps To Reproduce**
Play as a security Officer with the Expert Commando talent, hold the ctrl key while using any sub gun, the gun does noticeably more damage while fire rate remains unchanged.

**Version**
v0.15.13.0; Windows 10

**Additional Information**
Melee weapons can also gain the damage buff without the attack speed penalty

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ae14ba44e3348c8366f85e0a931d78abfad06aa

**Comment by Lithosagym** [comment]
Tested, melee weapons no longer gain any buff from Expert Commando, fixed. Submarine guns do still gain the buff from Expert Commando.

**Comment by Rokvach** [comment]
Moved to Team1 for further evaluation

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
