### ISSUE TITLE
Ammunition loaders - mispositioning the ammunition box and different loaders sprite size

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7459]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

1. Pulse Laser Loader
a) Pulse Laser Loader `<entityname.pulselaserloader>` - mispositioning the ammunition box: Pulse Laser Fuel Box `<entityname.pulselaserammobox>`, Pulse Tri-Laser Fuel Box `<entityname.pulselaserammoboxtrilaser>`
b) And sprite is the wrong height.
2. Chaingun Loader - sprite is the wrong width and height.
3. Loader Base `<entityname.blankloader>` - same size things.
![Image 013](https://user-images.githubusercontent.com/93348499/143040723-b4bfb65d-9080-4026-9b9b-2f5675444cea.png)

**Steps To Reproduce**
Submarine editor. Load ammunition into `Pulse Laser Loader`, also watch Loaders size.

**Version**
Barotrauma v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
![Image 008](https://user-images.githubusercontent.com/93348499/143041773-9bd044fc-f646-461a-82c4-bae2f40fedff.png)

**Comment by Regalis11** [comment]
This isn't a bug, they intentionally have slightly different sizes and looks. The bottom-center of the sprite should be used as the origin when swapping them, so they should still align with the floor regardless of these differences.

**Comment by MaaiG** [comment]
> This isn't a bug, they intentionally have slightly different sizes and looks. The bottom-center of the sprite should be used as the origin when swapping them, so they should still align with the floor regardless of these differences.

Honestly, I don’t get it.
But I see in the game the box and the loader are curved... 
![Image 001_22-32](https://user-images.githubusercontent.com/93348499/147502111-06989f77-1037-4151-b9df-39badb13882a.png)

**Comment by VaelophisNyx** [comment]
This is something I think would make sense for them all to fit; the mismatch looks incredibly unprofessional and really messes with ship aesthetics
