### ISSUE TITLE
Reputation- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#746]
Reputation is a percentage based value in Barotrauma for campaign mode.

Reputation allows the player in campaign mode to access more items in store or possible missions to receive. It also increases amount of possible hiring options in single player. All of it can be edited in xml files.

If a monster is terrorizing nearby outposts and player is not having enough reputation to fight it, that linea is being blocked for the player.

If for some reason all paths are being blocked all linea restrictions are removed.

Player can salvage artifacts he is not tasked to salvage, but their location remains hidden and player won't be informed during voyage if he salvaged correct artifact. He can only know after finishing it. Interestingly enough salvaging an artifact like that will be considered to be a completed mission and player will receive credits for it.

Cargo missions are also visible, but player cannot complete the mission at all as he will never receive cargo for it. The voyage will be threatened like the tasked never occured, so player won't lose reputation for not completing cargo mission.

Crew always starts the game with a reputation randomly set between 60 to 90 percent.

If the crew's reputation falls below 50% the game has to be restarted to the last save.

Reputation can be very slowly risen by:
* Completing missions in certain amount of time.
* Killing/Hurting non-quest monsters.
* Selling non-quest alien stuff.
* Having a lot of credits on account.
* Doing any of above things solo.

Reputation can be quickly dropped by:
* Completing cargo missions, but without full starting quest cargo (cargo is partially lost, but still enough of it to receive credits).
* Having alien items being dropped by the player into abyss with no return for retrieval.
* Failing a mission.
* Spending too much time on a voyage.
* Having crew members die.
* Selecting non-mission path instead of mission path (not included, while no missions are available).
* Having low amount of credits on account.

**Comment by thegrb93** [comment]
Credits already serves the purpose of punishing the player for losses. Many of these reputation modifiers don't make any sense.

**Comment by Regalis11** [comment]
The campaign does need to have a better sense of progression and some obstacles the player needs some time to get past (and some work has been done on this in the dev branch, with more to come), I don't believe this is a good way to do it. How you've described the reputation mechanic is essentially if you lose, you get punished and the game becomes more difficult, and if you win, you get rewarded and it becomes easier. To me this idea seems like it'd just make the campaign more frustrating.
