### ISSUE TITLE
Safety First talent - description effect is inverted

### ISSUE THREAD

**Issue by Wilron04** [Regalis11/Barotrauma#7460]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The effect from the "Safety First" talent in the Mechanic talent tree is inverted compared to the description. i.e. You do not gain electrical engineering skill points when obtaining mechanical engineering skill points, instead you gain mechanical engineering skill points when obtaining electrical engineering skill points.

**Steps To Reproduce**
1. Play as a Mechanic.
2. Choose the Safety First talent. 
3. Obtain a mechanical skill point through activity. (Receive no bonus electrical skill point)
4. Obtain a electrical skill point through activity. (Receive a bonus mechanical skill point)

**Version**
0.15.13.0 Windows

**Additional information**
I have experienced this bug in both single player and multiplayer.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a31977eceb307869b6f24632b44140363b46b4e8

**Comment by Lithosagym** [comment]
Tested, electrical skill is gained after gaining mechanical skill and mechanical skill is not gained after gaining electrical skill, fixed.

**Comment by Rokvach** [comment]
Closing.
