### ISSUE TITLE
Light component - some lighting problems

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7464]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Light component behind the character and the ladder. When you climb on the ladder the light component placed before.
2. Light component is translucent through the character.
![Image 021](https://user-images.githubusercontent.com/93348499/143112899-286744b0-868d-4591-b3e6-de3cb7f91aa2.png)

**Steps To Reproduce**
Watch screenshot.

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/318a3df6050860201958a7e21ac0820b8dbcd3dc

**Comment by Lithosagym** [comment]
Tested, light component no longer shines or appears through the character on a ladder, confirmed fixed.

**Comment by Rokvach** [comment]
Closing.

**Comment by MaaiG** [comment]
> Tested, light component no longer shines or appears through the character on a ladder, confirmed fixed.
1. Yes
2. No!

v 0.17.12.0 - "Light component" shines through the character. The light from the docking port is the same.
![Image 001_13-32](https://user-images.githubusercontent.com/93348499/165073428-d6c889e5-df37-4e0a-933d-91addc4818ca.png)

**Comment by MaaiG** [comment]
@Regalis11 

> Closing.

v0.19.11.0 
1. Light component behind the character and the ladder. When you climb on the ladder the light component placed before.
![Image 002_20-35](https://user-images.githubusercontent.com/93348499/194720445-84c777e9-d6fe-4101-850d-e3bad5226b39.png)
2. "Light component" shines through the character. 
![Image 001_20-41](https://user-images.githubusercontent.com/93348499/194720656-f26062db-74ad-42fe-a0fd-d617d9b10bc7.png)
