### ISSUE TITLE
Ammo naming conventions - Coilgun-less "Piercing Ammunition Box" Railgun-less "Physicorium Shell" etc.

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7465]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1a. After the hardpoints update, legacy coilgun ammo names became outdated (Piercing Ammunition Box) and only the icon and description tells you it's for the coilgun, not, say, the chaingun.
2a. Most legacy coilgun ammo can't be filtered with the keyword "coilgun"
2b. Same for railgun shells, the keyword is only "shell" (Nuclear Shell) but not "railgun"

**Solutions for Railgun shells;**
"Nuclear Shell" > `Nuclear Railgun Shell`
"Canister Shell" > `Railgun Canister` (because it's not really a shell) or 'Railgun Canister Shell' 
"Physicorium Shell" > `Physicorium Railgun Shell`

**Solutions for coilgun/chaingun/laser ammo:**
"Coilgun Ammunition Box" > `Coilgun Ammo` (alternatively, skip the Box part everywhere)
"Piercing Ammunition Box" > `Piercing Coilgun Ammo`
"Exploding Ammunition Box" > `Exploding Coilgun Ammo`
"Physicorium Ammunition Box" > `Physicorium Coilgun Ammo`
"Depleted Fuel Coilgun Ammunition Box" > `Depleted Fuel Coilgun Ammo`
Notice - it's not "Depleted Fuel Ammunition Box", it's "Depleted Fuel Coilgun Ammunition Box", unlike the legacy ammo types.
Same for Chaingun and Pulse Laser:
eg. "Physicorium Chaingun Ammunition Box:" > `Physicorium Chaingun Ammo`

The reason for adding the word "Coilgun" is obvious, but why "Ammo" instead of "Ammunition Box"? - you might ask.
This is why:
![Barotrauma_F3WWhMWuj7](https://user-images.githubusercontent.com/10529134/143125515-20cf20dd-7c98-4f12-a0b4-526c04fe38d5.png)
completely cut _(recycle)_
And this:
![Barotrauma_zUXUsoCB0v](https://user-images.githubusercontent.com/10529134/143116506-0c0952d2-1d2a-4541-89d4-b2bfa3d3e53a.png)
(re

**Version**
v0.15.13.0

**Comment by Krzeszny** [comment]
Excuse me, here's a meme I made a while ago
![memedmeme](https://user-images.githubusercontent.com/10529134/143129863-8d381fcd-4c4a-4a83-86e7-bbae0b4077b4.png)

**Comment by HeatedWafflez** [comment]
Also we seem to be missing tags to apply to ammo shelves for different things like chainguns and lasers, am I mistaken?

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.

**Comment by Krzeszny** [comment]
This problem is so easy to fix in 2 minutes :(
![Barotrauma_C8GEcpTFnx](https://user-images.githubusercontent.com/10529134/224494506-188df6b0-e7dd-4613-8449-a16f30bdc97e.png)
