### ISSUE TITLE
Oxygen does not leave the open airlock!

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7466]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Oxygen does not leave the open airlock chamber. The airlock is filled with water and the oxygen level is 100-99%. When water is pumped out, the oxygen level is 100%. No ventilation installed.

**Steps To Reproduce**
Use the oxygen detector and open the outer hatch. Then close it and pump the water out of the airlock chamber.
Oxygen level remains unchanged.

**Version**
I think in all versions, but...
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Water displaces air? Yes!

**Comment by Regalis11** [comment]
This is intentional. In my opinion, it would be quite unintuitive and hard to understand why you can't breathe in a room that's just been pumped empty of water - even if the sub is powered and there's oxygen everywhere else in the sub. 

I'd also argue that it'd be unrealistic: if there's no air flowing in to displace the water that's being pumped out, what _is_ flowing in? The pumps obviously aren't forming a vacuum inside the sub when they're pumping water out.

**Comment by MaaiG** [comment]
Thank you!
>In my opinion, it would be quite unintuitive and hard to understand why you can't breathe in a room that's just been pumped empty of water - even if the sub is powered and there's oxygen everywhere else in the sub.

But no one’s surprised that there’s no oxygen in the room because there’s no ventilation!
Otherwise, why do we need ventilation?

>The pumps obviously aren't forming a vacuum inside the sub when they're pumping water out.

And again we have the question! Why do we need a ventilation grid if there’s a pump!
I agree with you, but there’s a difference between "pumping water from the compartment" and "blowing ballast". I don’t think a man can survive in a ballast tank blowing ballast.
In the boat compartments and airlock chambers, we don’t "blowing"! We pump the water and run the oxygen.

Then the question arises as to the mechanism of this process.
The oxygen level in the flooded compartment is now 100%.
That is, you have 100% water and 100% oxygen in your compartment. The oxygen detector does not do its job and cannot participate in logical circuits.
IMHO in this situation can be a compromise solution for logic in a cycle:
* H2O=50% - O2=50%
* H2O=80% - O2=20%
* H2O=100% - O2=0%
* H2O=80% - O2=20%
* H2O=50% - O2=50%

Anyway. We see good animation of the water flowing from above.
So, why not see the animation of air bubbles rising up from a hole in the hull, an open hatch, or a Duct Block?

**Comment by MaaiG** [comment]
In addition, if the airlock has run out of oxygen (you inhaled it)), it will not recover after the lock cycle. So it is still a "vacuum".
So, it would be logical that oxygen would flow out from an open hatch or be pumped out at the start of the airlocking cycle.
More water, less air!
Flooded = no air!

**Comment by Krzeszny** [comment]
What MaaiG is trying to say is that if pumps replace water with air, they should function as vents.

**Comment by MaaiG** [comment]
> What MaaiG is trying to say is that if pumps replace water with air, they should function as vents. Otherwise, where do you get the air from?

- No, what I’m trying to say is that when the airlock hatch is open, the air has to come out.
- If you pump water into the compartment, the water displaces the air. And if you’re pump water from a compartment where there’s no ventilation, when you pump the water, there will be no air. And if there is ventilation, the volume of air and the volume of water should be proportionate
_PS Sorry for the language barrier._
