### ISSUE TITLE
Having too many additional cargo prevents you from starting a round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7470]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I guess the same can happen if you have too many items in the submarine in general. But I think we should limit the additional cargo from being 100 per item to 5 or 10 per item as it doesn't feel necessary to have that many.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/69a46d46-9eae-4ebb-8363-7bfe1aecc5ad)

This was more of a stress test as we do allow players to adjust the additional cargo freely it doesn't limit someone to going all out. So I think there would need to be some safe guarding in place so the player doesn't brick their server by doing this.

**Steps To Reproduce**
Go to Additional Cargo server setting and set half of the listed items to 100

**Version**
0.15.15.0
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/ce5e8633979909f1732dcbb126f7fa46c927fa09

**Comment by Rokvach** [comment]
The additional cargo setting does reset if you restart your server so it doesn't at least fully brick it

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/3856

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1f527f06b56e10c4a1486d08f557a54b7ba02960

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
