### ISSUE TITLE
Unable to start a mission and leave the station in multiplayer campaign

### ISSUE THREAD

**Issue by UnderpaidActor** [Regalis11/Barotrauma#7472]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After arriving at a Military Outpost in the third region of the campaign, I am unable to leave the station. I can still select the map and chose missions, but pressing on "Start" doesn't work. Everytime I press "Start" my character and all other players drop their gear and are unable to pick it back up. Furthermore we are rubberbanding back to the same room, where we pressed "Start" and can't move further than this room. 

**Steps To Reproduce**
It might have something to do with the following event that happened at the station: "An announcement comes over the PA. "Calling the crew of the vessel that just docked. Please send a representative to see the security chef in administration."".

**Version**
Version of the game is v.0.15.13.0. Operating system is Windows 10.

**Additional information**
-I can still accept missions, buy stuff and move around the station and submarine until I press on "Start".
-Completing or failing the event mentioned above doesn't solve the problem.
-After pressing "Start" the client states: "Client '(name)' has ended the round".
-After pressing "Start" it is impossible to go back to Server Lobby. Only going back to the Main Menu works.

**Comment by Regalis11** [comment]
Potentially related to https://github.com/regalis11/barotrauma/issues/7490. Do you happen to still have the save file available so we could give it a test?

**Comment by Regalis11** [comment]
No known steps to repro, closing
