### ISSUE TITLE
Possibly misconfigured affliction effects in `Afflictions.xml`

### ISSUE THREAD

**Issue by underscoren** [Regalis11/Barotrauma#7479]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In `Barotrauma\Content\Afflictions.xml` there are a few `Affliction`s defined in the `Effect` element directly, and not inside a `StatusEffect`. They are ignored, and not applied in-game. This is incorrectly configured, and should either be nested inside a `StatusEffect` / `PeriodicEffect` like all the others, or removed.

**Steps To Reproduce**
 - Look at one of the misconfigured afflictions, e.g. `opiatewithdrawl` (Lines 580 - 636)
 - Note the `nausea` affliction inside the `Effect` ranging from strength 20-40
 - Apply `opiatewithdrawl` affliction with strength 30
 - Note that the `nausea` affliction is not applied to the character

**Version**
v0.15.13.0

**Additional information**
Specifically, the following lines are wrong:

 - Lines 1620, 1631, 1645 (inside `chemwithdrawl` effects)
 - Lines 602, 617, 635 (inside `opiatewithdrawl` effects)
 - Lines 556, 574 (inside `drunk` effects)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf6177b637fa6ed21ace0e6cb8314d3c5d5e410e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
