### ISSUE TITLE
Sufforin Can Kill Endworm In 2 Injections- Nerfing Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#748]
All monsters in the game have same amount of oxygen. If they stop breathing they are still conscious, but if they remain without breath for some time they die instantly. I think monsters either need custom oxygen values or be immune to lose it.

I checked all of those with health scanner HUD. Not breathing monsters are still active, but they still die of it.

**Comment by Regalis11** [comment]
Fixed in the dev branch
