### ISSUE TITLE
Using the terminal's "clear" function flips the text alignment.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#7483]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The terminal's clear function changes the text from being aligned from the bottom of the screen to the top.

**Steps To Reproduce**
1. Type some text into the terminal.
2. Send a signal of "1" into the "Clear_Text" pin.
3. Type some more text into the terminal.

**Version**
Windows v0.15.15.0

**Additional information**
Before clearing the text:
![image](https://user-images.githubusercontent.com/67431770/143420259-05b53fa4-d1ec-48f1-a40e-dcadeb4c1183.png)
After clearing the text:
![image](https://user-images.githubusercontent.com/67431770/143420337-05ec9bec-d9e5-4ef2-8181-5dcc267b5eee.png)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce87142f14ec62104dfa6ab3b0e338b69761532d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
