### ISSUE TITLE
Cannot Remove Wire

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7486]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The power wire connecting the junction box to the oxygen generator on the Dugong submarine cannot be removed. Neither can the power wire between the junction box and the engines. This is during normal play, NOT from the sub editor.

**Steps To Reproduce**
Use a screwdriver, take the wires out from both ends, and try to drag the wire out of the box from either device. The mouse turns into a wire 1x sprite as though it becomes an item, but it doesn't and the wire is not removed from the panel.

**Version**
Windows 10, game v0.15.13.0

**Additional information**
After fiddling with it for several minutes, I was able to remove the oxygen wire by standing just to the right of the junction box. A vision issue somehow? I was unable to remove the engine wire no matter what.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/527649dce7ebad1de6156aec36c443f1e98df6e3

**Comment by Lithosagym** [comment]
Tested, both oxygen generator and engine wires are able to have the wires removed, fixed.

**Comment by Rokvach** [comment]
Closing.
