### ISSUE TITLE
0.15.13.0 Kicked out the server every time when docking an outpost [Multiplayer]

### ISSUE THREAD

**Issue by taurviz** [Regalis11/Barotrauma#7487]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I have been kicked out of the server every time after passing/docking an outpost. 

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Dock an outpost

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows 10 x64

**Additional information**
Add any other context about the problem here
[四季发财_2021-11-24_0006.txt](https://github.com/Regalis11/Barotrauma/files/7604632/_2021-11-24_0006.txt)
[四季发财_2021-11-24_0046.txt](https://github.com/Regalis11/Barotrauma/files/7604634/_2021-11-24_0046.txt)
[四季发财_2021-11-24_0128.txt](https://github.com/Regalis11/Barotrauma/files/7604635/_2021-11-24_0128.txt)
[四季发财_2021-11-24_0226.txt](https://github.com/Regalis11/Barotrauma/files/7604636/_2021-11-24_0226.txt)
[四季发财_2021-11-24_2140 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604637/_2021-11-24_2140.2.txt)
[四季发财_2021-11-24_2140.txt](https://github.com/Regalis11/Barotrauma/files/7604638/_2021-11-24_2140.txt)
[四季发财_2021-11-24_2220.txt](https://github.com/Regalis11/Barotrauma/files/7604639/_2021-11-24_2220.txt)
[四季发财_2021-11-24_2233 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604640/_2021-11-24_2233.2.txt)
[四季发财_2021-11-24_2233.txt](https://github.com/Regalis11/Barotrauma/files/7604642/_2021-11-24_2233.txt)
[四季发财_2021-11-24_2325 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604643/_2021-11-24_2325.2.txt)
[四季发财_2021-11-24_2325.txt](https://github.com/Regalis11/Barotrauma/files/7604644/_2021-11-24_2325.txt)
[四季发财_2021-11-25_0043.txt](https://github.com/Regalis11/Barotrauma/files/7604646/_2021-11-25_0043.txt)
[四季发财_2021-11-25_2052.txt](https://github.com/Regalis11/Barotrauma/files/7604647/_2021-11-25_2052.txt)
[四季发财_2021-11-25_2118.txt](https://github.com/Regalis11/Barotrauma/files/7604648/_2021-11-25_2118.txt)
[四季发财_2021-11-25_2209.txt](https://github.com/Regalis11/Barotrauma/files/7604650/_2021-11-25_2209.txt)
[四季发财_2021-11-25_2235 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604651/_2021-11-25_2235.2.txt)
[四季发财_2021-11-25_2235.txt](https://github.com/Regalis11/Barotrauma/files/7604652/_2021-11-25_2235.txt)
[四季发财_2021-11-25_2244 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604653/_2021-11-25_2244.2.txt)
[四季发财_2021-11-25_2244.txt](https://github.com/Regalis11/Barotrauma/files/7604654/_2021-11-25_2244.txt)
[四季发财_2021-11-25_2312 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604655/_2021-11-25_2312.2.txt)
[四季发财_2021-11-25_2312.txt](https://github.com/Regalis11/Barotrauma/files/7604656/_2021-11-25_2312.txt)
[四季发财_2021-11-25_2325 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604657/_2021-11-25_2325.2.txt)
[四季发财_2021-11-25_2325.txt](https://github.com/Regalis11/Barotrauma/files/7604658/_2021-11-25_2325.txt)
[四季发财_2021-11-25_2345 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604659/_2021-11-25_2345.2.txt)
[四季发财_2021-11-25_2345.txt](https://github.com/Regalis11/Barotrauma/files/7604660/_2021-11-25_2345.txt)
[四季发财_2021-11-25_2348 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604661/_2021-11-25_2348.2.txt)
[四季发财_2021-11-25_2348.txt](https://github.com/Regalis11/Barotrauma/files/7604662/_2021-11-25_2348.txt)
[四季发财_2021-11-26_0038.txt](https://github.com/Regalis11/Barotrauma/files/7604663/_2021-11-26_0038.txt)
[四季发财_2021-11-26_0041 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604664/_2021-11-26_0041.2.txt)
[四季发财_2021-11-26_0041.txt](https://github.com/Regalis11/Barotrauma/files/7604665/_2021-11-26_0041.txt)
[四季发财_2021-11-26_0052 (2).txt](https://github.com/Regalis11/Barotrauma/files/7604666/_2021-11-26_0052.2.txt)
[四季发财_2021-11-26_0052.txt](https://github.com/Regalis11/Barotrauma/files/7604667/_2021-11-26_0052.txt)
.

**Comment by Regalis11** [comment]
Thank you for the report!

Do you by any chance remember what kind of an error message you got when you got kicked out from the server? I unfortunately couldn't find anything about the disconnections in any of these server logs.

**Comment by taurviz** [comment]
HI, it's mostly "File transfer error: received data without a transfer initiation message" in red
or the message saying "You have been disconnected because the client data is not sync" something like that in a dialog
or "Submarine equality check failed"
or "AuthTicketCanceled"

**Comment by gerakis** [comment]
I have also had this bug. My error messages have been "AuthTicketCanceled" and also sometimes something like "File missing: custom hatch" or something like that. This was on someones custom sub though, not a vanilla sub.

**Comment by Regalis11** [comment]
That sounds like it could be related to https://github.com/Regalis11/Barotrauma/issues/7175. We've addressed some of these issues in the [recent unstable builds](https://barotraumagame.com/announcements/barotrauma-tester-version-made-public/) so it could be worth a shot to try whether the problem goes away by switching to the unstable branch. Or, you can also wait for the next bugfix patch, which should be coming out later this month. Sorry for the trouble!
