### ISSUE TITLE
0.15.13.0 - docking the outpost then CTD [Multiplayer]

### ISSUE THREAD

**Issue by taurviz** [Regalis11/Barotrauma#7488]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashed to the desktop at the loading screen after docking to the outpost.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
Dock an outpost in MP

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
Windows 10 x 64

**Additional information**
Add any other context about the problem here
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7604677/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/7604678/crashreport.3.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/7604679/crashreport.4.log)
.

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/482de887f4a59d0a955a5d0eb611ef50d6e74ff4

**Comment by Rokvach** [comment]
There hasn't been any sighting of this issue happening after the fix, seems to be working correctly. Closing.
