### ISSUE TITLE
[Feature Request] Remote Start Reactor Through Wiring

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7489]
I would like to remotely start the reactor through wiring. I can shut it down, but not turn it on. I have my sub set to auto shutdown the reactor at when docked at stations to save power, but I cannot auto restart on leaving. So i've got to climb down to the reactor and hit the button every time.

This seems like a simple change. You could even change the shutdown pin to be a start/stop pin, where an output of 1 starts the reactor and an output of 0 stops it.

Also I don't know if this is a bug but the reactor shutdown pin currently shuts down on any input signal, even a 0.

**Comment by TBenz4Sportsball** [comment]
While a more formal way to start the reactor with wiring would be nice, you can achieve a soft reactor shutdown by sending 0 to the set_fission_rate pin while docked, and no signal while undocked.

**Comment by MaaiG** [comment]
You can do it now.
1. Reactor On - Auto Mode
2. The relay is switched "On" when you docking and the "memory" component sends "Zero"
3. Reactor "stalled"
4. When undocking the relay is switched "Off"
5. Reactor On - Auto Mode
![Image 013 (1)](https://user-images.githubusercontent.com/93348499/143511432-e6c9c3c9-3d29-458f-b0ad-a8fbdbaba576.png)

**Comment by Regalis11** [comment]
Thank you for the idea! The issue tracker is for bug reports however, so I'll close the ticket.
