### ISSUE TITLE
Huskification's Attacks Won't Hurt Monsters- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#749]
So I decided to attack endworm under "R" attack key to see what happens and it took zero damage. Is this implemented?

**Comment by Regalis11** [comment]
Huskified humans only do bleeding damage, so they cannot damage endworms or other monsters that are immune to bleeding.

**Comment by rico6822** [comment]
But when I attacked humans they took like 10 direct damage, not only bleeding.
