### ISSUE TITLE
DockingStationMissonScreenBug

### ISSUE THREAD

**Issue by OGRobinson** [Regalis11/Barotrauma#7490]
I'm running Barotrauma on Windows 10 and it's the latest version.
Have encountered an issue that doesn't let me continue the game in Multiplayer.
The issue: I docked to a station. The station is loading up. I can see my character standing on the usual spot. Then the MissionMap pops up and I'm unable to close it again. Furthermore I'm not able to start any "mission" to go on into the next "level". I have posted a clip of it in Barotrauma Discord (tech support)

**Comment by Regalis11** [comment]
It seems that this was the result of two different problems:
- The circuit in the submarine's docking hatch has been modified to toggle docking when it's receiving a signal from the current_velocity_y connection of the nav terminal. As a result, the sub immediately undocks from the outpost at the start of the round.
- The immediate undocking caused the game to get stuck in an invalid state where it can't select the next destination and start a new round. Fixed that in https://github.com/Regalis11/Barotrauma-development/commit/4fed494834f03b5108e55920e948a679ea25c94d.

After fixing the bug above I was able to undock and save in the next level, here's that save that should hopefully allow you to continue the campaign
[new_0.zip](https://github.com/Regalis11/Barotrauma/files/7608885/new_0.zip)
:

**Comment by OGRobinson** [comment]
Wow thank you! So someone must have messed around with the docking hatch?

**Comment by OGRobinson** [comment]
So i tried the "new" save but the same thing is happening again.     :/

**Comment by Regalis11** [comment]
I didn't do anything to the faulty docking hatch circuit, it needs to be repaired or the sub will keep automatically undocking every time you try to enter an outpost.

**Comment by Rokvach** [comment]
Tested with the provided save, the sub does undock when loaded into a outpost as it should but my progression isn't locked as I'm able to select a destination and start a round so this is working correctly. Closing.
