### ISSUE TITLE
railgun firing order ambiguous

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7491]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
New players are likely to be mislead about what shells fire in which order for railgun.

- when on the periscope, there is no UI indicating which railgun shell is going to be fired (leftmost)
- in the loader, no UI indicating which shell is going to be fired (also leftmost)
- -loader is even more ambiguous due to the empty slot appearing on the right side

the common case of loaded shells being all the same (ex: all 5 being empty regular shells) doesn't help the situation either

**Steps To Reproduce**
1. Ask multiple new players to describe the railgun / shells.

**Version**
yes

**Additional information**
something like this idk
![image](https://user-images.githubusercontent.com/5103517/143518911-15e15e9d-2b56-4f19-9ca0-87333758fbd3.png)
![image](https://user-images.githubusercontent.com/5103517/143519022-ebd8173e-6cfc-4913-a24e-2af58c27d5da.png)
![image](https://user-images.githubusercontent.com/5103517/143519234-aa7d489c-4329-41bc-a8b5-e7f114ff81f3.png)

**Comment by Jallu** [comment]
@danielasteljoki check out the wire and throw the ball to art
