### ISSUE TITLE
orca2 hulling issues

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7492]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Orca2 in public unstable has some hulling issues, pics below, but may not be exhaustive

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/5103517/143519868-18d4586e-0886-4993-a5d4-ffa40444a436.png)
![image](https://user-images.githubusercontent.com/5103517/143519875-e24891b7-de29-4656-8919-1ba7bded20c8.png)
![image](https://user-images.githubusercontent.com/5103517/143519882-3f772e61-d2d5-446d-862b-34950efc279a.png)

**Version**
15.15 unstable

**Additional information**
Don't recall seeing any github commits related to changes to orca2, just deco, so i thought i'd put this in for now

**Comment by danielasteljoki** [comment]
Made hulls nicer in cca0ae5.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
