### ISSUE TITLE
Object lost (battery cell), and wrongly reported location by object detector/tracker

### ISSUE THREAD

**Issue by tmerlin59** [Regalis11/Barotrauma#7493]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hi, I am fairly new to the game so I am not sure if it is a known bug. I had very few runs in a campaign (3 or 4), until I noticed there were no battery cells in my ship (Dugong). In a previous campaign, the ship contained battery cells at least in the locker inside the room next to the hatch. Moreover, the object detector wrongly detects battery cells in 3 parts of the submarine (I checked, and no battery cell in any of the highlighted area).

**Steps To Reproduce**
I am not sure if I did anything special. Previously to finding this bug, I started a mission, and immediatly reconnected to the outpost when I figured out I forgot to buy new combustible. Additionnally I used steam in offline mod a couple of time when I played the game.

**Version**
Version is v0.15.13.0, Windows, branch Release, revision 4e66dd7b5d.

**Additional information**
Some steam screenshots about the wrong object detector:

Battery cell (cellules de Batterie) detected in several areas:
https://steamcommunity.com/sharedfiles/filedetails/?id=2664280531

Object detector pretending that battery cell is located in locker in the command room:
https://steamcommunity.com/sharedfiles/filedetails/?id=2664282021

Bummer, no battery cell in that locker:
https://steamcommunity.com/sharedfiles/filedetails/?id=2664282130

**Comment by Tsunder** [comment]
flashlights contain battery cells

**Comment by Regalis11** [comment]
Yeah, this doesn't seem to be a bug: it appears there's a battery inside the flashlight.

**Comment by tmerlin59** [comment]
Thanks for the answers, indeed I totally overlooked that the tracker would point to the cell inside the flashlights or other items. And I guess the bots used most of the spare cells somehow, without me noticing.
Sorry for the erroneous report.
