### ISSUE TITLE
Texture offset - Computer Terminal

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7495]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Texture offset - `Computer Terminal`.
So small, but annoying as hell )).
Goes from  version to version!

**Steps To Reproduce**
![Image 010 (1) (1) (1)](https://user-images.githubusercontent.com/93348499/143585766-c3f362f9-8a81-4b0b-b519-6b94bc11d67c.png)
**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a3ee47bbc2d2a70d8189c98240659748d73114b0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
