### ISSUE TITLE
Duct Block - No animation of leaking water + Additional

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7496]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Duct Block - There is no animation of leaking water if it is arranged between the hulls.
- Hatch  - animation present always!
- Duct Block - only when water entering the hull from outside! Between the hulls - No yet!

**Steps To Reproduce**

https://user-images.githubusercontent.com/93348499/143597068-569b46d9-1ed8-4561-b264-e534d1c116de.mp4

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
In addition. An open `Duct Block` displays everything behind it. Often it’s not nice and you have to insert a black square texture.
![Image 001_15-08](https://user-images.githubusercontent.com/93348499/147750876-2ccd7490-3476-4b65-95f3-76b0875942ca.png)
I propose to make a black background for an open `Duct Block`. Or activate this (If this is it):
![Image 001_15-02](https://user-images.githubusercontent.com/93348499/147750884-47ac8fbf-a900-4a3a-b6fc-84e33b03bf42.png)

**Comment by MaaiG** [comment]
I don’t want to bother anyone, but without this, I feel bad. You can’t see where the water is coming from. The water just comes in.
I’m afraid the "low prio" status is almost like a gravestone 0.0
I’m very sorry from this. I won’t bother you anymore. 😳

**Comment by Krzeszny** [comment]
Ok, this issue _is_ annoying. You can't see if there's a leak because of it.

**Comment by Krzeszny** [comment]
@Regalis11 can you please look into this?
I've just it on v0.18.12.0 and on current unstable, and both bugs are still present on this test bench 
(no water coming from duct block, no black background) 
https://github.com/Regalis11/Barotrauma/files/8897632/__Test-Water.zip

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.13.0, doesn't seem quite right to me visually.

Regardless of how much water the hull has to transfer to the other hull, its effectively a strong hose for internal hull to hull duct blocks. Meanwhile water from the exterior of a hull (that is from no hull, the ocean) is both faster in filling the hull and calmer in particles.

https://i.gyazo.com/55fa722a7893d9c62c512903e364884e.mp4

Exterior leakage from a duct block looks like a trickle of water (But the hull to hull transfer appears to actually be slower than the exterior to hull duct block? so assumedly more water is entering with less particles to show for it?)

I feel the rates of particles are back to front, and it does not matter if one or the other is closed or how full a hull appears to be. Additionally the underwater bubble effects are much thicker/more numerous with a lesser flowrate than if the flowrate is higher it appears.

Using a water command to show hatches and duct blocks side by side:

https://i.gyazo.com/2a605abeb8f44c5eb3ae0fcdb608385b.mp4

**Comment by MaaiG** [comment]
@NilanthAnimosus You use my test chamber! You are sure to have disabled the pump or closed the door? ;)
![Image 001_20-31](https://user-images.githubusercontent.com/93348499/176943712-01a37d02-718c-4d38-97a9-686c51bd7c5f.png)

**Comment by NilanthAnimosus** [comment]
Its the same even if the door to that pump is closed and the room is allowed to fill from my testing, it was only open to keep the room from flooding and hiding the particles.

**Comment by MaaiG** [comment]
Maybe there aren’t enough particles...

https://user-images.githubusercontent.com/93348499/177052492-593447a7-6913-4c37-8d62-4662c73a9fba.mp4

**Comment by Regalis11** [comment]
Tweaked the rates in https://github.com/Regalis11/Barotrauma-development/commit/ea8c3f46fd102ffc239d0723057d0b028a7fd4f4

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/36e3a2755f5fc201a748a32b63cc93a8eb30d90a, works correctly, closing.

Notes:

sideways duct flow (Yes, the pump is off that has target level and the pump to the left though the latter doesn't change the particles visibly, the quantity of sideways flow particles is lacking, but I also know a higher-up duct block will not drain water to the bottom of the hull and yes - for these tests I am using the water command on top of outside-hull water inputs):
https://i.gyazo.com/26d6625e816149f576fd9e519203fb19.mp4

duct flow from above, top is external to internal hull and fills at a faster rate:
https://i.gyazo.com/2dbbbf12b3d4d7d25fdbdaeb5d5db6a4.mp4

flow rates definitely seem more consistent, outside->insides faster flow of water is pretty clear, and inside-> inside is consistent too with the speed of water flow, I'm content to say this is fine now and can be closed.

**Comment by MaaiG** [comment]
>flow rates definitely seem more consistent, outside->insides faster flow of water is pretty clear, and inside-> inside is consistent too with the speed of water flow, I'm content to say this is fine now and can be closed.

@NilanthAnimosus 
I’m afraid that now between the hulls is more like a water sprinkler. :( 
Water should flow a steady stream, but it doesn’t look like that. It’s more like a swinging hose. The strength of the stream has decreased, but its width seems to have increased or remained the same! The flow of water from above became like a sprinkler. Now it looks very weak and unnatural... :(

https://user-images.githubusercontent.com/93348499/188627243-ef6a8b66-f517-43b7-9a93-34f1c325aefd.mp4

It is better to let them be the same!
In addition, in both cases, water penetrates into the bodies at the same rate. If the speed is the same, it should look the same.

https://user-images.githubusercontent.com/93348499/188627698-340a08e9-ace6-4f68-b9cb-86ff0578fb9f.mp4

**Comment by NilanthAnimosus** [comment]
Just an FYI, but the amount of particles is based off the flow rate (the amount transferring) of water.

Given in my last test when I considered it fixed, it was a much longer room than the one below, filling visually faster than the one below despite the greater amount of water needed to fill it. while the room below, much smaller and requiring less water wasn't filling nearly as fast despite the smaller area. This tells me that its flowing slower and the particles appeared to match that.

I will agree though that perhaps if the water flow is slow enough that there is large gaps in the particles and it has a wide area, it can look a bit unusual, so I'm reopening the issue but feel maybe this should be its own new issue at this point as there are particles and animations of leaking water now with the duct blocks, and this is more an issue of flow rates vs particles.

It wouldn't make much sense for a hole letting in 4 times as much water to look as strong as one letting in 1 times or a fraction of that amount, but I can agree there should perhaps be more consistency to the particles.

**Comment by MaaiG** [comment]
In the last video ([20220906_144934.mp4](https://user-images.githubusercontent.com/93348499/188627698-340a08e9-ace6-4f68-b9cb-86ff0578fb9f.mp4)) I made rooms of equal volume.

**Comment by NilanthAnimosus** [comment]
Hm, probably needs more of a look at then. This was the latest unstable right (0.19.4.0) ?

**Comment by MaaiG** [comment]
Sorry, I forgot to specify the version: Stable 0.18.15.1

**Comment by NilanthAnimosus** [comment]
Those changes should have been  in v0.18.14.0 but just wanted to make sure

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/a938c70848e7d512ad8b8f2a3a352ba4d0f40bf9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
