### ISSUE TITLE
A Change in Oxygen's Lack Mechanic- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#750]
Instead of having character being instakilled upon reaching some minus oxygen amount I think character should start losing (red) health. Character will lose more health the more minus oxygen he has.

**Comment by Regalis11** [comment]
This is pretty much how the health system works already, once the character falls unconscious they start losing health and die when it drops down to -100.

In the new health system implemented in the dev branch it's perhaps slightly more intuitive: the characters have a "vitality" value which can be reduced by any type of damage or lack of oxygen. When the vitality drops to zero, a second red health bar appears, and when that drops to zero, the character dies.
