### ISSUE TITLE
Modding : overwriting a <controller/> does not keep its toggle & state settings.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7500]
Originally was tipped off to this issue by a user experiencing problems with submarine buttons and levers when using the "Sounds of Europa" mass-overwrite mod. Made some further testing and it seems that buttons / levers / switches which are overwritten lose their item-prefab controller component settings.

**Steps to reproduce:**
- Use a submarine with buttons edited to different toggle and state settings.
- Activate an overwrite to the button's item.
- Button settings get loaded from item prefab overwrite instead of submarine.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9cf40b246f4248a1b06006e3207607df4b352caa

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
