### ISSUE TITLE
[0.15.16.0] Fight Intruder order does not ignore Neutralized Hostiles.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7502]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I did a Terrorist Stakeout mission, and I well equipped all my crews with Stun Batons and 2x Handcuffs. The moment the terrorists revealed themselves, they were neutralized with stun and handcuffs as expected. Even though they have orders for submarines maintenance, they are just standing still if the Fight Intruders order is in a higher priority position instead.

Expected Result: Ignore Neutralized Hostiles and execute other orders even if the Fight Intruder order is in highest priority position.

**Steps To Reproduce**
1. Take Terrorist Stakeout Mission.
2. Equip every crew members with Stun Baton and 2x Handcuffs.
3. Give every crew members usual submarine routine orders, but give them Fight Intruder in first priority.
4. Make sure to lock up armory very well so that it's easier to neutralize the terrorists.
5. Let the terrorists reveal themselves and get neutralized by the crew members.
6. Observe crew member behaviours after hostiles are neutralized.

**Version**
0.15.16.0

**Comment by Regalis11** [comment]
Fixed in Regalis11/Barotrauma-development@641495e

**Comment by Rokvach** [comment]
I tried to test this couple ways in multiplayer pirate game mode

First I took control of one of the pirates and then handcuffed them and teleported to the main sub, all bots panicked and reported the handcuffed pirate as a hostile and security officers went into fight intruders mode. 

Second I used disablecrewai and teleported a pirate onto my sub and then handcuffed them and did enablecrewai, again bots freaked out

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9fee62b05a4d5a164b47c134965ed043e79bfff

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
