### ISSUE TITLE
[0.15.16.0] Bots will keep reporting Neutralized Hostiles on the submarine.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7503]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots will keep reporting Neutralized Hostiles on the submarine.

**Steps To Reproduce**
1. Neutralize a hostile terrorist or pirate on your submarine.
2. Let your crew members meet the neutralized hostile.

**Version**
0.15.16.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/641495eb059a631f19f56c9e6e345f922e18d348

**Comment by Rokvach** [comment]
I tried to test this couple ways in multiplayer pirate game mode

First I took control of one of the pirates and then handcuffed them and teleported to the main sub, all bots panicked and reported the handcuffed pirate as a hostile and security officers went into fight intruders mode. 

Second I used disablecrewai and teleported a pirate onto my sub and then handcuffed them and did enablecrewai, again bots freaked out

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9fee62b05a4d5a164b47c134965ed043e79bfff

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
