### ISSUE TITLE
[0.15.16.0] Missing background wall for this Ruin Module

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7504]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Missing background wall for this Ruin Module
![Capture](https://user-images.githubusercontent.com/5086682/143658124-8eab597b-2dc5-4eb7-aab0-6ba4b81b4e33.PNG)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/7610793/Save.zip)
**Version**
0.15.16.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b8408d22f6d2df4ac37be38a62b88a80a02f8ed7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
