### ISSUE TITLE
[0.15.16.0] Trap Door for Artifact Module in Ruin always starts off closed?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7505]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've seen this modules many times and it's always closed when I see it. I'm not sure what's the purpose of this contraption if it always starts off closed, since the terminal does nothing useful. Either the players can't crowbar the door open because the sensor is already locking it up, or they cut it open and the sensor is ineffective.

![Capture](https://user-images.githubusercontent.com/5086682/143658368-127022b0-367d-422e-90ba-0a5edb72e4b2.PNG)

**Version**
0.15.16.0

**Comment by Regalis11** [comment]
Apparently this is the intended behavior: the motion sensor forces the door to stay closed, and you can deactivate that motion sensor using the terminal.
