### ISSUE TITLE
Bots try to put oxygen tanks in diving suits while they're being crafted/used as a crafting item

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#7506]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you start fabricating something that uses a diving suit for its recipe (eg: combat suit), bots will stand there shaking trying to put an oxygen tank in the diving suit (if it's empty)

**Version**
unstable v0.15.16

**Comment by Regalis11** [comment]
I couldn't figure out a way to reproduce this. How do you get the bots to put items inside diving suits?

**Comment by LePiromano** [comment]
> I couldn't figure out a way to reproduce this. How do you get the bots to put items inside diving suits?

From what i remember, 2 of my bots, the ones that got stuck in the fabricator targeting the diving suit, had the recharge oxygen tanks order. I'll try reproducing this with debug on, I'll get back to you if i get results

**Comment by LePiromano** [comment]
I was able to do it, start crafting an item, give a bot the cleanup items order while targeting an oxygen tank, and the bot will attempt to put the tank in the diving suit in the fabricato

https://user-images.githubusercontent.com/55637865/144754472-6279a392-c3d7-4820-935d-9b2311df3e64.mp4

r.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/22323750dd423bd7fe116aaacf22083990e69062

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Regalis11** [comment]
The fix didn't work for deconstructors, see https://github.com/regalis11/barotrauma/issues/8859. Should be fixed properly now https://github.com/Regalis11/Barotrauma-development/commit/945042ef50a7444c6868d5415c861fec455c9a53

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
