### ISSUE TITLE
[0.15.16.0] These alien lights are off in these modules

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7507]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
These alien lights are off in these modules
![Capture](https://user-images.githubusercontent.com/5086682/143658576-bef9d36d-478d-41ee-8f8e-89e00de1fb96.PNG)
![Capture](https://user-images.githubusercontent.com/5086682/143658827-a8e1c377-04ef-494e-8c9c-09a29d7ae6b2.PNG)

**Version**
0.15.16.0

**Comment by Kaillera** [comment]
Well if they are deliberately off, I feel like they need to be at least visually broken or flickering or something.

**Comment by danielasteljoki** [comment]
That is intentional. Some lights are on, some are off and some are flickering.
