### ISSUE TITLE
[0.15.16.0] Refill Battery order is only putting battery cells in the first battery charger they can find, even if it's full and other chargers are unoccupied

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7509]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Refill Battery order is only putting battery cells in the first battery charger they can find, even if it's full and other chargers are unoccupied. They'll drop battery cells that were in the chargers to swap it with the ones they're recharging.

**Steps To Reproduce**
1. Play Humpback.
2. Fill the right most submarine battery with battery cells.
3. Tell a bot to refill a used battery cell from some other rooms other than electrical.

**Version**
0.15.16.0

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@524804d. Bots should now prioritize placing items in non-full containers.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
