### ISSUE TITLE
Health Scanner HUD Makes it Possible to See Walls of Submarines From Behind Walls- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#751]
I don't know if that's implemented, but health scanner HUD does see walls from behind other walls.

This happened to me as I saw walls outside of my submarines being shadowy, while I was inside. Normally they are invisible from inside.

**Comment by Regalis11** [comment]
You should be able to see the walls even without the health scanner HUD, the line of sight effect only hides movable objects but lets you see static structures.
