### ISSUE TITLE
Abyss islands feel unrewarding virtually always, players don't want to go there

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7511]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a design issue nobody has reported yet because, based on my theory, almost nobody uses this feature. Nobody ever goes into the Abyss to look for abyssal islands. If nobody goes there, nobody is disappointed by what they find, so nobody cares. I'm serious.

**There is no reason to go to the abyssal islands**, as players could just as well explore wrecks for scrap, alien materials and weapons (and diving suits for TiAl) or ruins for everything you can find there, and have fun while doing it, or just use mineral scanners to look for useful minerals, without descending into the abyss, wasting ammunition on Endworms and spending ages to ascend back up. 

According to a spreadsheet I've made, defeating an endworm can take 20 boxes of piercing coilgun ammunition on strong subs that only have coilguns. Some subs are balanced around coilguns and players can, out of bad luck, fall in. There's the choice to give up (and abandon the survival aspect of Barotrauma) or defeat that worm. But what's the reward for doing the latter?
An island with usually 3 or 4 of the most basic minerals or plants players usually don't need. Nothing that would even pay for the ammunition used: **aluminium, silicon, zinc, phosphorus, calcium, copper, iron, carbon, tin, lithium, chlorine, potassium, plants with ethanol, fiber or antibiotics or elastin** – because it's very likely to already have loads of those in storage. Even magnesium and lead can be useless if players don't have the needed talents. Yes, you can sell them but isn't worth going there and back. The only universally high-value finds are Aquatic Poppies, Titanite, Uranium Ore and Thorianite, and finding them is very unlikely. The fewer players, the less useful the mineral rewards are in practice, because there's very little crafting and little medicine being used.

**Solution**
These sprites are still unused, as far as I know, and placing only alien materials on all Abyssal islands would make them rewarding at any point in a campaign, and would make all players happy.
![PicasaPhotoViewer_pSlH7caij2](https://user-images.githubusercontent.com/10529134/143660244-24e8ea4c-1722-45a1-ac03-df020c8fa244.png)

**Steps To Reproduce**
1. Teleport to different abyssal islands. 
2. Find 3 or 4 random minerals: amblygonite, aragonite, bornite, cassiterite, chalcopyrite, chamosite, chrysophase, diamond, esperite, graphite, hydroxyapatite, ilmenite, iron ore, lazurite, pyromorphite, quartz, sphalerite, stannite, triphylite or, unlikely, something better.

**Version**
v0.15.13

**Additional information**
Another solution, although much worse, would be to increase the amount of minerals fond and spawn all existing minerals, not just a few random ones.
I think nobody has ever complained because everyone is so incredibly disappointed. I've only been there twice since the Embrace the Abyss update (had to look that up) and boy, am I disappointed myself. The abyssal islands of gambling. You still lose too much time even if you find something good.

Quote from an official Barotrauma blog post on the Embrace the Abyss update:
> Besides that, we’re adding islands – floating land masses that can contain caves, with rare minerals. They should make the abyss a little more enticing to explore, and more interesting to behold

**False.** Rare materials are very rare on the abyss islands.
https://barotraumagame.com/gameplay-features/here-be-dragons-reintroducing-abyss-creatures/

You could say we're not supposed to fight Endworms with coilguns. Firstly, Barotrauma is a survival game. I'd say, we're not supposed to give up. Even if you skip the ammunition part, it's still unrewarding and not fun. And lastly, the monsters were supposed to guard rewards, not rubbish. Pretty much every game has bosses guarding prizes.
Whileas here, the chance to find bad loot is so high that most of the time, **it's not even worth it to mine the minerals you find when you're already there.**

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/5e31df234cc9ec4a7555e1b157de4278034e0440

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
