### ISSUE TITLE
Bots flying unnaturally on repair failure after running

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#7514]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots switch states almost instantly, with completely inhumane reaction.
It leads to weird consequences due to preservation of momentum from movement.
Like, if bot was running to repair something and got repair failure - the bot will continue flying ragdolled in direction of its movement.
Which may and will lead to mishaps in particular sub configurations.

Suggestion: make bot stop for ~0.5 seconds or so prior to initiating repairs with wrench/screwdriver, to negate the momentum from movement, thus preventing flying.

**Steps To Reproduce**
Synthetic steps to reproduce:
1. Place two powered repairables with exceptionally high skill requirement on same sub level, preferrably with no obstacles between these.
2. Make these repairables lose durability fully once per, let's say, 15 seconds.
3. Issue repair order to the bot.
4. Watch bot flying to and fro after each repair failure.

**Version**
Latest Steam release version.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5a2a8f4b7640ac32cd9dd40026c6045c6cbe21e5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
