### ISSUE TITLE
Round component can output -0 (negative 0)

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7515]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Round component outputs -0 when fed with a number between (exclusive) -0 and -1

expectation is that it outputs 0, i think is reasonable?

**Steps To Reproduce**
feed a round component -0.2

**Version**
0.15.13

**Additional information**

**Comment by Tsunder** [comment]
ceil component as well

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/385e79327694536151fb16d80cd92aeb18f3fdfc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
