### ISSUE TITLE
R-29 Big Rig Pathfinding Error in Bots

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7517]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a section of the hull just to the top right of the right ballast in the R-29 Big Rig submarine is damaged, bots will get stuck walking into the wall trying to reach it.

**Steps To Reproduce**
Put on a diving suit and go outside the right of the ship. If you cut into the hull just above the ballast tank all the bots will freak out. Ive attached a screenshot that should show exactly which tile to target. Its just above where that bulbous section starts to stick out from the main wall. The one with the healthbar is the problem tile. This bug is easy to reproduce.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
![bugged tile](https://user-images.githubusercontent.com/16128947/143691983-02e2090f-bbe4-43f9-976f-743729e92a72.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce9cb7d5990751e09039b189eff9fcb868d39866

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
