### ISSUE TITLE
[Unstable 0.15.16.0] If Oxygen Generator is full a bot with Refill Oxygen Tanks order will just drop the full oxygen tanks to the floor in favor for empty/spent ones

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7518]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As the title states

**Steps To Reproduce**
Fill Oxygen Generator up with oxygen tanks and order bot to refill them, use up some oxygen tanks for the bot and notice what the bot does once they go to refill the spent tanks. I think the bot should instead loot the full oxygen tanks and clean/return them

**Version**
Unstable 0.15.16.0

**Comment by ekqvist** [comment]
I replaced the Bug label with the Feature Request label. If I understood the issue correctly, I would say that this is more of something that's not been implemented than a bug.
