### ISSUE TITLE
[Unstable 0.15.16.0] Players are vanishing when they travel from sub to outpost

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7519]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Doesn't seem to matter if you are a host or a client, either one can vanish when they travel from sub to the outpost. Its similar to the psychosis effect where you can just see doors opening and closing. 

**Steps To Reproduce**
Play on multiplayer and have players traveling from sub to outpost, notice that some of them will vanish when they cross over to the outpost.

**Version**
Unstable 0.15.16.0

**Comment by Rokvach** [comment]
Seems like its when traveling from sub to sub, had it happen for respawning players when they were coming from a shuttle to the sub

**Comment by Regalis11** [comment]
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/9eee04a1ef82abfa32cb15ec0f75cecaf3368479

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
