### ISSUE TITLE
Particles spawned at incorrect position if item mirrored and copyentityangle is true 

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#7523]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Particles with copyentityangle true, a distance and some rotation spawn at a different position when mirrored. For instance, on this item with the origin at the center a particleemitter with `distance=20, angle=90, copyentityangle=true` spawns on the bottom of mirrored and on the top otherwise:
![image](https://user-images.githubusercontent.com/50582661/143770104-51469ece-86df-436e-b10b-e8064e937c51.png)

**Steps To Reproduce**
Example XML for an affected item would be 
```xml
<Items>
	<Item name="oxygentankcopy" identifier="oxygentankcopy" category="Equipment,Misc" maxstacksize="8" Tags="smallitem,oxygensource,refillableoxygensource" cargocontaineridentifier="metalcrate" scale="0.5" impactsoundtag="impact_metal_light" allowdroppingonswap="true">
		<InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="896,0,64,64" origin="0.5,0.5" />
		<Sprite texture="Content/Items/Tools/tools.png" sourcerect="410,71,24,66" depth="0.55" origin="0.5,0.5" />
		<Body width="22" height="64" density="9.7" />
		<Holdable canbecombined="true" slots="Any,RightHand,LeftHand" holdpos="30,-15" handle1="0,5" handle2="0,-5" msg="ItemMsgPickUpSelect">
			<StatusEffect type="Always" targettype="This" duration="1" stackable="false">
				<ParticleEmitter particle="scannerdot" anglemin="90" anglemax="90" distancemin="20" distancemax="20" scalemin="0.4" scalemax="0.4"
									scalemultiplier="1,1" particlespersecond="5" copyentityangle="True" colormultiplier="150,200,100,255" />
			</StatusEffect>
		</Holdable>
	</Item>
</Items>
```
**Version**
Unstable v0.15.16.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ad7605a0870fc435e66ceff913252af1a9eabef

**Comment by Rokvach** [comment]
WorkingJoe tested this issue on the latest Unstable build and its working correctly, closing.
