### ISSUE TITLE
Cannot go through a low "hull" without using a ladder!

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7524]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Character cannot go through a low `hull` without using a ladder!

**Steps To Reproduce**
Use low hull before lock hatch or any place with low `hull`!
It can happens anywhere on the sub if you use low `hull`.

https://user-images.githubusercontent.com/93348499/143772211-ab307fc2-10ff-400d-99e3-58489fb3cbf4.mp4

P.S. By the way, on the sub `R-29`, the same situation with the upper airlock! 

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
![Image 012](https://user-images.githubusercontent.com/93348499/143771925-237b88e4-594f-4319-b880-890f4bb6b480.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/59c8c50b89f7bde148cacb5749302f8cb89db40f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
