### ISSUE TITLE
Bug  window doesn't closed on "ESC" keypress.

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7526]
**Description**
Bug window doesn't closed on "ESC" keypress, can be closed by mouse.

**Steps To Reproduce**
Start game, start new\load game. 
Press ESC to go game menu.
Press ESC again to close, this how it should works.
Press ESC to go to game menu again.
Click "bug" button.
Press ESC, to close it. 

Expected result: bug window closed, game menu open, game paused.
Factual result: bug window is open, game menu is closed, game is running.     I can even control characters with WASD, but can't open doors))))

**Version**
v 0.15.13.0 hotfix (Steam\Windows)

**Comment by SoNickRND** [comment]
![20211128182532_1](https://user-images.githubusercontent.com/125238/143774697-f2b43c30-f72f-43d1-884b-6ac223a6db3f.jpg)
Screen shows bug window open and in-game menu closed

**Comment by RadinQue** [comment]
Fixed the issue in #7527

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/73bb2e30ad9d9d37b2b878dee5e24bfd8e71f70b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
