### ISSUE TITLE
Using A Tool On A Door Disables Aiming

### ISSUE THREAD

**Issue by Lithosagym** [Regalis11/Barotrauma#7528]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using a wrench or screwdriver on a door and then unequipping/switching to a different item makes all items unable to be aimed. The effect only wears off after walking away from the door. Video provided below.

**Steps To Reproduce**
1. Use a Wrench or Screwdriver on a door 
2. If using a screwdriver, unequip or switch to a different item, as long as you no longer have a screwdriver in your hand
3. The crew list should disappear after using a tool
4. Try to aim with a melee weapon or ranged weapon, doesn't work (shooting with a weapon still works, but you can't aim.)
5. Walk away from door and the crew list will appear again and you'll be able to aim again.

**Version**
Windows: v0.15.16.0

**Additional information**
Most likely caused by the game thinking you're still wiring/repairing as the interface is gone but it still acts like it.
This issue is likely connected to part 2 of #7356

https://user-images.githubusercontent.com/60911734/143783083-c903c377-282f-41ae-905d-d19067400b72.mp4

**Comment by Regalis11** [comment]
Doesn't seem to happen any longer, closing
