### ISSUE TITLE
Prototype Steam Cannon does not do damage to Ballast Flora

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7534]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As it is in the game currently, the Prototype Steam Cannon does not actually inflict any damage to ballast flora. Upon testing this, I was extremely surprised to find this, considering the fact that the Steam Cannon would seem to be the perfect answer to ballast flora, seeing as it works very similar to the flame thrower, but will work under water and not cause your sub to burst into flames.

**Steps To Reproduce**
Get a ballast tank infected with ballast flora, then attempt to remove it with the Steam Cannon

**Version**
Latest Stable Version of the game

**Additional information**
Should be pretty simple to fix, I would imagine you could just copy a few lines of code from the Flamer.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dbd156b123e486ec47baf8c6eda89b96488cb4fb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
