### ISSUE TITLE
(unstable) Orca 2 design issues

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7537]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some issues that showed up during a test session w/ the orca 2 in 0.15.16:

1. It's heavily relay based. This results in muted player feedback for the power grid/undervolting from large increases in load, which is a half of the hints that sudden load changes can result in electrical problems. (the other half being overvolting). It also reduces the amount of maintenance to be done, resulting in more idle hands.

2. battery chargers increase ship load by a lot. The battery chargers have the default 200 load, the 3 of them increasing the ship's baseline load by 600, or about 17% of the reactor's maximum 3500 output, increasing the approximate idle load of the ship to 1900 or so. This results in the ship being quite difficult to suffer overvolt damage/suffer minimal overvolt damage.

3. Switches being non-toggle is very odd as it doesn't match what a default switch's behaviour is. It can mislead players into crafting switches expecting them to work like buttons. They can be toggle switches and instead go to the lights set_states, or use buttons to send the signal to toggle_state. (Switches also have this nice red/green light to indicate its state, which is lost when it's isToggle=false)

**Steps To Reproduce**
orca 2

**Version**
0.15.16 public unstable

**Additional information**

**Comment by Tsunder** [comment]
4. despite its description, the orca 2 is worse armed than regular orca. It has no 2nd gun on top dorsal side.

5. the Fin A Patch 5's in command room have a sprite depth that hides them behind the vent ducts. (Also the display is clearly ripped from the kastrull)

**Comment by danielasteljoki** [comment]
Good point about relays. Changed the sub to use more direct connections from junction boxes. Also removed some chargers and lowered reactor max output in e8e785c. Switches have been fixed earlier. Fins' depth fixed in cdbf1c4.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
