### ISSUE TITLE
Faraday Artifacts Continue to Make Noise Inside an Artifact Case

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7544]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Faraday artifacts continue to make noise inside an artifact case. Nasonov and thermal do not make noise in a case so I think this is a bug. Now that the doctor talent incentivizes you to keep artifacts aboard this gets really annoying because every time I go to my storage room I get blasted by that awful noise coming from the closet.

UPDATE: actually both thermal and faraday keep making noise. Psychosis and Nasonov are silent.

**Steps To Reproduce**
Obtain a faraday artifact, and put it in an artifact storage case. The sound effect will not stop.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
I really hope this is a bug because that sound really gets on my nerves.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/523fff1a9ed21944450b47143f3b447a38e849e8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
