### ISSUE TITLE
Passed through solid rock somehow

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7545]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was somehow able to pass into solid rock using my security guy. I think a combination of speed from my scooter, slipsuit and ragdoll boost was somehow able to bypass collision and transfer me right into the ground. I could swim around inside the rock and could also escape back out of the rock the same way.

**Steps To Reproduce**
Not entirely sure so this might be hard to reproduce. Try putting on all that speed boost stuff and ragdoll boost yourself at the ground. You might be able to pass right through. I was moving to the left when it happened. I recorded a video so you can see what happened.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
(https://youtu.be/-dQG5k-MdCw)

**Comment by Regalis11** [comment]
No known steps to repro, closing
