### ISSUE TITLE
Low-prio, Modding: Stereo sounds do not fade properly with distance.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7546]
When playing sound effects formatted in stereo, volume does not properly fade with distance from the source - causing a hard cutoff effect when entering and leaving the sound's range.

**Comment by Regalis11** [comment]
The audio library we're using (OpenAL) doesn't support positional stereo audio. I think this is the case for most audio libraries: it doesn't make much sense to make a sound that has both left and right channels, and is essentially coming from "around you", play from a single point.
