### ISSUE TITLE
Stunned/Unconscious NPC can still see you steal stuff & report it after they wake up or get healed

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7548]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stunned/Unconscious NPC can still see you steal stuff & report it after they wake up or get healed

**Steps To Reproduce**
1. Somehow drown the Outpost NPC in a room with a item you can steal
2. Wait until he's suffocating
3. Steal item when he starts suffocating
4. NPC Medic CPR him or revive command

**Version**
~0.15.16.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1467f8eca4123f4d376aa0cb2897013d47f29ec9

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/626e10150456e0338dd4ca781fd532bd1d27ac53

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
