### ISSUE TITLE
"Nuclear Blast Survivor" Achievement awarded when causing enemy pirate submarines reactor to melt down.

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7549]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I got the achievement without ever having my reactor melt down. I did attack a pirate sub and i'm assuming their reactor melted down instead.

**Steps To Reproduce**
Don't have the achievement, the go jack up an enemy sub so hard their reactor melts down. You should get the achievement even though you didn't really do anything special.

**Version**
V0.15.13.0 Windows 10 x64

**Additional information**
This was in single player campaign if it matters.

**Comment by Regalis11** [comment]
Looking at the description of the achievement, I'd say this is a valid way to unlock it:

> Complete a round after a nuclear meltdown.

I'd even say sneaking on board a pirate sub, melting down the reactor and escaping alive is a bigger achievement than blowing up the sub's reactor and surviving (which is pretty easy to do in a controlled manner).
