### ISSUE TITLE
Outpost Event - Get rid of all clown from station for 1k marks not counting

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7550]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So I'm not sure what's the intended way for this event to actually go, but I got all the clowns to suffocate/death to pressure/death by external fire or explosions, but that didn't give me the credit for getting rid of them. If there was supposed to be a dialogue with the clowns, I've never seen a chat bubble or yellow exclamation mark for one.

**Version**
~0.15.16.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/39791aa98132d67b65cd3a780c911483d829b02e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
