### ISSUE TITLE
[0.15.16.0] Genetic Materials don't fit inside storage containers anymore?

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7552]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Genetic Materials don't fit inside storage containers anymore?

**Version**
0.15.16.0

**Comment by Regalis11** [comment]
They do?
![image](https://user-images.githubusercontent.com/14351070/144018988-635cd3bd-869f-48e4-a909-fa0e0adee98e.png)

**Comment by Kaillera** [comment]
Okay I found what it is. For some reason you cannot put genetic materials into storage containers, if the storage container was in a medicine cabinet first.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/27d70f4a1f970add22d8797871b39e0a7a27d966

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
