### ISSUE TITLE
Flamer and Prototype Steam Cannon have no quality modifiers

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7553]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Neither the Flamer nor Prototype Steam Cannon have quality modifiers

Prototype steam cannon is a fairly straightforward weapon, and the other wreck items have quality.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.13

**Additional information**

**Comment by Regalis11** [comment]
Not a bug
