### ISSUE TITLE
Mod's files can load before vanilla files, breaking the use of `variantof`

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7555]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I've made a mod that uses `variantof` inside `<Override/>` to change single values in vanilla items, and I've had 2 people (out of a hundred or so) report a rare issue. According to them, `variantof` would create an item before the vanilla item that's to be modified was loaded.
In other words, and this is a logical assumption, **the mod's XML file would load before the vanilla XML file.**

**Steps To Reproduce**
One of the players who reported it to me added that it had happened twice in a row.
The first theory is that it only happens on a faulty startup, or just an unlucky startup.
Another theory is that it happens when texture paths are broken for other vanilla items, which somehow causes a domino effect, making this bug more likely (due to multiple console errors messing with the loading time).
All in all, it happens very rarely. Here's a simple example that may or may not cause it:
```
<Override>
  <Item name="" identifier="alienspear" variantof="alienspear">
    <Projectile launchimpulse="30.0"/>
  </Item>
</Override>
```
With the right amount of bad luck, this file could cause that item to lose all its properties and become invisible.

**Version**
v0.15.13

**Additional information**
`variantof` smh, more trouble than benefits

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
