### ISSUE TITLE
Volatile Fulgurium gives the Fissile Accelerator less shots than Fulgurium

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7556]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

This may be intentional, or not (only one way to find out).

Uranium and Thorium: 4 shots
Volatile Fulgurium: 5
Fulgurium: 8

**Version**
v0.15.13

**Additional information (updated)**
Thorium fuel rods are 2 times less efficient per cost than Uranium, for shooting. Just FYI
![brave_uuBmJAQsJX](https://user-images.githubusercontent.com/10529134/144327667-4ac9cce3-5e2f-4430-a443-4e3e51eb868a.png)

**Comment by Regalis11** [comment]
This doesn't seem to be the case: the normal fuel rods give 4 shots, fulgurium rods 12 and volatile fulgurium rods 20. Where did you get these values? If you just looked at the xml, note that the higher-tier rods have more than 100 health.

**Comment by Krzeszny** [comment]
> This doesn't seem to be the case: the normal fuel rods give 4 shots, fulgurium rods 12 and volatile fulgurium rods 20. Where did you get these values? If you just looked at the xml, note that the higher-tier rods have more than 100 health.

Sorry, I didn't notice the health parameter. You can close this issue.
