### ISSUE TITLE
[Unstable V0.15.16.0] Remora: can't order bots to operate the drone turret

### ISSUE THREAD

**Issue by SumNutz** [Regalis11/Barotrauma#7557]
- [x]  I have (not) searched the issue tracker to check if the issue has already been reported.

Description:
it is not possible to order any of my bots to man the turret on the Remora's drone.

Steps to reproduce:
purchase and switch to Remora from Humpback in my case. even before installing an additional weapon the issue was present.

Video showcasing the problem:

https://user-images.githubusercontent.com/46006004/144106084-abab4d9c-73b9-41eb-83d7-cf75c3eca9e7.mp4

**Comment by SumNutz** [comment]
looks similar to #7481

**Comment by Regalis11** [comment]
Seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/7481, closing as a duplicate
