### ISSUE TITLE
Deusizine damage will cause revived AI crewmembers to turn hostile.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7561]
Organ damage caused by liquid oxygenite - and burns caused by deusizine, will trigger AI crewmembers threshold to enter combat.
This is particularly an issue now that oxygenite and deusizine are the sole medicines providing healing to oxygen-loss.

- _( Also both are less effective in practice, because the vitality-loss from said damage actively works against the vitality gained from healing oxygen-loss. So usually multiple doses are needed - which then results in even more burn or organ damage by the time they are stabilized. )_

**Comment by Regalis11** [comment]
Existing ticket about liquid oxygenite: https://github.com/Regalis11/Barotrauma/issues/4697

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16f4338af0c7fab856052bf645e132445f48de5f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
