### ISSUE TITLE
XML : `"Watcher's Gaze"` sets a players psychosis strength instead of incrementing it

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7562]
When afflicted with a heavy amount of watcher's gaze, its affliction sets the player's psychosis amount to 3 - effectively 'curing' them of their psychosis if allowed to progress to the late stages. According to the status effect in XML `line# 1351` of `Afflictions.xml`.

The fix for this would seem to be separating the player speed modifier & psychosis affliction into separate status-effects so the `setvalue` properly is not being applied to the afflictions as well.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7a5cab02c83ace8b0baebbc78848b264e4f54704

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
