### ISSUE TITLE
Im cannot feed my pet (the food is right)

### ISSUE THREAD

**Issue by BarotraumaIsEpic** [Regalis11/Barotrauma#7566]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
I'm afraid I could not get this bug to happen: the pets seem to eat the items I give to them when they're hungry.

Which pet did this happen with and what were you trying to feed to it? Did this happen in single player or multiplayer? Are you sure the pet was hungry (= was there a bubble with the )?

And if it was a Peanut, were there people around it? Like [the SCP Peanut is a reference to](https://scp-wiki.wikidot.com/scp-173), it stops moving when there's people near it (excluding the owner).

**Comment by BarotraumaIsEpic** [comment]
Orange boy, iron | Single player | Yes | Idk what is it i buy this game 1-2
months later

ср, 1 дек. 2021 г., 13:46 Joonas Rikkonen ***@***.***>:

**Comment by MaaiG** [comment]
I threw that filthy into the airlock! ))  ...Let him live free.

**Comment by Regalis11** [comment]
No known steps to repro, closing
