### ISSUE TITLE
When crafting Chemicals in multiplayer I can't craft with the rest of the stuff left.

### ISSUE THREAD

**Issue by Bestparty** [Regalis11/Barotrauma#757]
Recently when I was playing as medic I tried making a bottle of corrigone from the leftovers of another corrigone bottle and I wasn't able to do it even if the Ingridients were at 50% durability.I think that desync is causing this by putting the chemicals at 49.99% or lower just like the reactor shutdown temperature in multiplayer.This Should be fixed asap as Some chemicals are rare to come by.

**Comment by thegrb93** [comment]
That would explain why fabricator can't use 1/2 left vials in crafting. I thought a recent commit fixed that though. Or I'm not remembering correctly.

**Comment by Regalis11** [comment]
This has been fixed in 7a7c92a. There's been quite a few bugfixes since the last patch so I think I'll release a new one soon!
