### ISSUE TITLE
[V0.15.16.0] Linked hulls on status monitor display water level strangely.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7570]
Linked hulls display an average water-level percent of all their parts on status monitor, however this also seems to be applied the the visual water representation resulting in strangeness with multiple-hull ballasts and flooded rooms.
![image](https://user-images.githubusercontent.com/55356135/144274212-a1cdb8c7-3e81-49ce-9c4e-b93a11e7c13b.png)

![image](https://user-images.githubusercontent.com/55356135/144274006-4a0d922b-4b3e-445b-a79a-258904a1fc2a.png)

![image](https://user-images.githubusercontent.com/55356135/144274820-cdd05666-cfcd-413b-83bc-758499502fb2.png)

![image](https://user-images.githubusercontent.com/55356135/144274673-2221ef95-2c97-4ad1-978a-39e9aa0f3350.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97fcd5beab25b43acfbfb9a02764d4ed2b1fcd72

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
