### ISSUE TITLE
[V0.15.16.0] Leaking water is extremely loud.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7572]
The looping sound of water leaking through a broken wall or flowing through a hull connection is now extremely loud, even louder than explosions drowning out pretty much all other sound.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f5b1f6e72b51aa1734bf394d39ac0ea9c47d7acc

**Comment by Rokvach** [comment]
Tested, seems fine now. Closing.
