### ISSUE TITLE
Electrical view tab in the status monitor shows numbers incorrectly.

### ISSUE THREAD

**Issue by noonetohelp** [Regalis11/Barotrauma#7574]
- [ ✓ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Electrical view tab added in the Among the Ancients update shows conditions of installations. The condition value in this tab is currently broken in the Korean language settings and shows as "Condition:[value]%", instead of "Condition: 100%". I've tested Chinese and Japanese so far and found the numbers display as normal. It seems like a bug caused by the auto-localization feature of Barotrauma, translating the [value] instead of displaying it as numbers.

**Steps To Reproduce**
Just set the language settings to Korean. Uncertain this bug is in other languages.

**Version**
v0.15.13.0

**Additional information**
The localization is displayed as "내구성:[양]%", instead of something like "내구성:80%".

![20211202182034_1](https://user-images.githubusercontent.com/95409750/144393530-539d8b77-428d-4ceb-ad40-86d9a67e61e9.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ceb8549e9a5eb13d7c334200c851d5b89215154c

**Comment by Rokvach** [comment]
Tested, no issues. Closing
