### ISSUE TITLE
Sonar Beacon becomes very quiet when your wearing a diving suit

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7577]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Turn on a Sonar Beacon and then equip a diving suit and try to listen for the beacon sound

**Version**
0.15.16.0
Branch: dev
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/dcfd55558039cab2fcb1edb5a9755a7933facd5b

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/effb5c9ac9ced2119947bf1b7d0d787e4d87ee0e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
