### ISSUE TITLE
Automatic temperature control makes reactor consume fuel even if shutdown temperature is set to 0 / bots don't turn off automatic temperature control when told to shut down the reactor

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#758]
Just a minor Quality of Life issue, isn't a problem when you are controlling the reactor manually, since you can just turn the ATC off, but for some reason bots don't do that when you order them to shut down the reactor, what makes you have to switch to the bot who controls the reactor to turn it off.
It also appears that shutting it down using "shutdown" wire signal input also only sets the temperature to 0, but leaves the ATC on, which might be a bit inconvenient for some automated subs. Perhaps there should be wire input related to ATC?

**Comment by rico6822** [comment]
I think fuel rods should drain as fast as their fission rate. Heat absorbers are required for cooling rates. If output matches grid load or higher fission rate will set itself to 0% and will return to higher amounts upon output being below grid load. This doesn't happen if ready heat absorbers are inside.

**Comment by Regalis11** [comment]
Both of these have been fixed in the dev branch (the fuel consumption rate is relative to the fission rate).

![sfhstfh](https://user-images.githubusercontent.com/14351070/44927773-6a7e6700-ad5e-11e8-89aa-e57421f90b23.png)
