### ISSUE TITLE
When traveling at high speed, it is not possible to adjust the cursor precisely to the object.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7581]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Mayby its [partly related question - 7540](https://github.com/Regalis11/Barotrauma/issues/7540), but I don't think so. Not sure there’s a problem with the size of the object.

**Description**
When traveling at high speed, it is not possible to adjust the cursor precisely to the object.
It’s hard to use a `switch` when the submarine moves fast.
Standard scale - 500
Scale used - 600!

**Steps To Reproduce**
Watch current speed and behavior of the cursor on the switch.

https://user-images.githubusercontent.com/93348499/144480887-45e100f9-c174-4e11-968f-badfec094e6e.mp4

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Ek-Videogames** [comment]
There used to issues with the whole screen jittering when the submarine is moving, but the camera shaking has been fixed so the effect of appearing to be stationary when the sub is moving is almost seamless - what isn't seamless however is mouse interaction still has these issues.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/70c1e25a973a68afadc4ebcdc70f2beeb0b9f8d1

**Comment by Rokvach** [comment]
Tested, haven't seen this happening, working correctly. Closing.
