### ISSUE TITLE
Suggestion: Bandages instead of Morphine as best burn treatment

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#7582]
I've noticed, especially through long campaigns, that the most common injuries ingame are the numerous types of internal damage and burns (most from electric bots zapping themselves.) The issue is, both of these are treated with morphine, and given how medibots tend to be overzealous to heal people you're almost ALWAYS out of morphine, while being full on bandages, especially how bleeding isn't inflicted by anything that's normally on a submarine. My idea was to switch the burn heal values of Bandages (18), Plastiseal (36) and Morphine (50) around. I felt that given how the actual real-world treatment for a burn is to apply gauze, this could be a way to stop medic bots from eating up morphine at the rate they currently do, and make morphine less of a cure-all, while still keeping the game realistic.  I'm unsure if this would mean you'd have to rebalance fentanyl as well.

**Comment by gerakis** [comment]
Another thing is bandages seem to only help with one part of the body, while morphine does the whole body. When I do attempt to bandage I end up using way more bandages than I would have if it were morphine. It also takes more time to drag and drop all those bandages which is a real problem in an emergency. I agree that bandages need a huge buff.

**Comment by StruggleDuck** [comment]
I think what could be a good idea is that either a) bandages should get multiple uses again(otherwise it's not viable to carry around bandages because of required inventory space) or b) bandages and similar med items should automatically apply to impacted areas when you have high enough medical skill by double clicking them in the health Gui

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/caa40eab0ddfa833b585d6bd8766b9812325aaf2

**Comment by Rokvach** [comment]
Tested, working correctly .Closing
