### ISSUE TITLE
Oxygenite Shards, Sulphurite Shards, and Books Get Dumped on Floor when Purchased

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7583]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you buy oxygenite shards, sulphurite shards, or any books from a store they do not arrive in crates. They just get dumped on the floor. I'm not sure if its all books but The Sailor's Guide and Europan Medicine for sure go on the ground.

UPDATE: It seems like its all books.

**Steps To Reproduce**
Buy one of those items from the store at a station. When they arrive it won't be in a crate.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
This was in singleplayer.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4b22cd662a1ce0c53b2c673d807ef8249ab55d52

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
