### ISSUE TITLE
Fabricator Item Quality, Skills Required and Time to Produce do not Update between Characters in Single Player

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7585]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have one character make something in the fabricator, and then have another character open the fabricator and try to make the same item, he will see the resulting item as though it used the skills and talents from the first character. Meaning the quality and time to finish are wrong. The actual produced item will be correct though.

Example: Engineer can make masterwork fuel rods. If security guard tried to make a fuel rod after the engineer did, it will say they can make masterwork rods too even though they cannot. The actual output will be a normal rod as expected, it simply doesn't change the text upon opening the fabricator. It will update to the correct information if you click another recipe and then click back to the first recipe using the second character.

**Steps To Reproduce**
Have a character make an item. Have a second character with different skills make the same item. You will see that the recipe page did not update.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
This is in single player.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d540899724c0b6872bf149417463a087d820d376

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
