### ISSUE TITLE
Installed Weapon Name Missing

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7586]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The name of any gun that is installed doesn't have a name listed. You have to figure out what it is from the description alone, or process of elimination.

**Steps To Reproduce**
Go to the upgrade merchant and open the weapons section. No name will be listed for the installed gun, even though names are listed for all non-installed guns. Please see screenshot.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
This was in single player.
![missing gun name of installed gun](https://user-images.githubusercontent.com/16128947/144532437-734c9872-1933-41d9-a840-1ed53ac7cd64.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/178467ed8179e6cc9d7af2987fbfa15f918db5af

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
