### ISSUE TITLE
Dedicated Server/Lidgren: Use Steam IDs in addition to IPs for identifying players in the console

### ISSUE THREAD

**Issue by zoktiik** [Regalis11/Barotrauma#7587]
There's one issue I have with the Dedicated Server, and it's the fact that the game doesn't allow you to use SteamIDs in the console commands when using Lidgren networking, despite the server requiring players to have Steam and knowing each player's SteamID. This is inconvenient for administration purposes: I would much prefer to add a moderator with `giverank` by his/her SteamID, or ban a player by SteamID in addition to IP (maybe with a new command for that dual ban: `stickyban`, perhaps?). 
It would also be convenient if `clientlist` could show both identifiers, and I could see use in the server notifying admins when a player joins with the same SteamID/IP as a "non-sticky" banned player.

**Comment by Regalis11** [comment]
This ticket doesn't seem to be relevant any longer, both the `giverank` and the `ban` command support banning by Steam ID.
