### ISSUE TITLE
Buffs and Poisons do not show additional info in health UI

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#7589]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Many afflictions, especially poisons and buffs, do not show extra info when the affected limb is clicked in the health UI. It also does not show available treatments.
![image](https://user-images.githubusercontent.com/50582661/144618729-97ac2616-2611-435e-b6b4-8261bfcfe968.png)
First thought says it could have something to do with limb aspecific afflictions. 

**Version**
v0.16.15.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e27b67ff48731d59e6e5add71e89d97df434c192

**Comment by Rokvach** [comment]
The afflictions does show up but it doesn't seem to display any suitable treatments still

**Comment by Rokvach** [comment]
Moved to Team 1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e27b67ff48731d59e6e5add71e89d97df434c192

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Regalis11** [comment]
Oh, didn't mean to reopen this
