### ISSUE TITLE
LightComponent on Broken Items

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#759]
LightComponent stays on even when the item they are attached is broken. They only seem to turn off when the main item is recieving no power.

The only way I've found to adress this for now is to add this to the items:

<StatusEffect type="Always" target="This" IsOn="true"/>
<StatusEffect type="OnBroken" target="This" IsOn="false">

But this prevents them to be turned off manually via toggle on/off mechanics.

This also happens with items such as cameras. I tried to make cameras temporarily breakable via EMP blasts but they keep working when the main item is broken too.

**Comment by Regalis11** [comment]
The camera issue was fixed in cfc03f84
