### ISSUE TITLE
[V0.15.17.0] Art: Outpost Wall 3 sourcerect completely borked

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7593]
Outpost Wall 3 texture is literally just **gone**
![image](https://user-images.githubusercontent.com/55356135/144645276-e3aa8c54-15f8-4da7-a918-015934cee5b3.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f8405769593e50e487f0d1f12dee8fc25663abb8

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
