### ISSUE TITLE
[Unstable 0.15.17.0] Monster events aren't working

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7596]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No matter which difficulty you are there's just absolutely nothing spawning in the paths and there is no spawn markers there either

**Steps To Reproduce**
Play campaign and notice that the levels are just empty

**Version**
Unstable 0.15.17.0

**Additional information**
These screenshots are from the last biome
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bac8cce6-7063-41f6-9da5-9fecd01ffd41)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d9719c20-9d6d-45fb-b9a5-7c600543aad2)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fb492c4b32d2ffd8f0bd624cbd83e65a9fb7964

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
