### ISSUE TITLE
Changing the scale of the wire does not work.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7597]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I wanted to highlight the `wire` and increase its size, but it didn’t work.

**Steps To Reproduce**
Change this value:
![Image 001_22-19 (1)](https://user-images.githubusercontent.com/93348499/144662832-13061c58-ada6-411f-a055-160dc90fa3f4.png)

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
The scale setting doesn't effect the width of these lines, but the scale of the item itself.
