### ISSUE TITLE
When you change object scale  - the object cannot be dragged by mouse.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7599]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you change object scale the `white box` moves away from the object. When the `box` is not superimposed on the object, it cannot be moved by mouse. The object can be moved only areas where the `box` is superimposed on the object.

**Steps To Reproduce**
![Image 001_23-16 (1) (1)](https://user-images.githubusercontent.com/93348499/144670221-99d6018a-2c0e-4923-bf28-855b2b9a827b.png)

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
![Image 001_15-05 (1)](https://user-images.githubusercontent.com/93348499/144708956-57216ef9-c3ba-4e29-82ed-cf0d7914555c.png)

**Comment by Ek-Videogames** [comment]
"Small/Shuttle" engine also has problems being selected when scaled down

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/89e5c350c19b6a238933dc6f4024fb4b531ca67b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
