### ISSUE TITLE
Saving a Custom Sub While Hard Drive is Full Will Ruin Your Save File

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7602]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If saving a custom sub in the sub editor, if the hard drive is completely full, it will save some kind of broken file overwriting the previous good file and completely erase hours of hard work.

**Steps To Reproduce**
Save a sub in the sub editor. Fill up your hard drive completely (I was torrenting.) Try to save your new sub again. A console log with a bunch of red text will pop up. Your sub is now gone forever.

**Version**
v0.15.13.0

**Additional information**
This is extremely not cool. I spent hours on that sub.
![youve ruined my masterpiece](https://user-images.githubusercontent.com/16128947/144695951-0fb37eec-943a-4371-9645-be61294379be.png)

**Comment by MaaiG** [comment]
Bad case. Try searching your submarine in the hidden folder ". AutoSaves".
**Path: "Barotrauma/Submarines/. AutoSaves/"**

I’ve been there before, but I can’t tell you exactly what happened.
It’s a shame to lose the result of a few hours of work or even months. I always try to make backups.

**Comment by gerakis** [comment]
MaaiG's suggestion worked and I was able to get my sub back. They should still fix this bug though. Just allocate a megabyte or so for new subs when the game is first installed, then use that to store the subs. That way they don't have to worry about running out of space. A meg can store like 50 subs or something? Its a lot.

**Comment by MaaiG** [comment]
Just now I had the same situation. I checked that! If no space on the disk, when you save the submarine, the game opens console window and red warning!
