### ISSUE TITLE
[V0.15.17.0] Water_% output does not work

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7603]
Water_% output from water sensor does not change from 0 at all when water is present in the hull.
![image](https://user-images.githubusercontent.com/55356135/144696089-ae6b5ee7-7cc9-4d0e-b5fc-e39e5e9c52f2.png)

**Comment by Regalis11** [comment]
Seems to have been caused as a result of the fix for https://github.com/Regalis11/Barotrauma/issues/7539, I'll close this one and comment on that ticket
