### ISSUE TITLE
Targetself in attack conditionals that check afflictions seems to target both the attacker and target character

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#7605]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to use a character's owned afflictions as a condition to be able to perform an attack, which could look something like this:
```xml
    <attack>
      <Conditional anyaffliction="gt 0" targetself="true"/>      
      <Affliction identifier="bitewounds" strength="5" />
    </attack>
```
The attack simply becomes completely unusable whether or not the character has the affliction or not, also disregarding any strength thresholds we might have put for the attack to be usable. However, if both the attacker and the attacked character meet the conditions we had set, then the attack becomes usable.

**Version**
v.15.13.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9e491a741a0fbc519805ac6c800a3c96395d774

**Comment by Rokvach** [comment]
This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
