### ISSUE TITLE
Issues with two handed held items in latest master

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#761]
I have yet to test this but i'm throwing it up as its something I've been informed of in my mod - which uses a few of the changes in the current master despite being .12 (though usually client side acceptable ones as I try to keep the networking fine).

What I was told was "Two-handed items that have no holding animation when not aimed will inherit the rotation of the wrong hand" - I am not sure if this was the BTE content  package or vanilla nor have tried to reproduce it yet, but I am listing the bug up in case its an issue with commit 8d5e5a8a15e2a75e52d61be880382822ea020f3d

**Comment by Regalis11** [comment]
Fixed in 6e606fd
