### ISSUE TITLE
Linked Containers Open at Strange Angles

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7610]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If both linked containers have the check mark for "Display side by side when linked" the first time a container is opened it will display at a bizarre angle compared to the other window. See video link.

**Steps To Reproduce**
In sub editor create a fabricator and a cabinet and link them together. Check the box for "Display side by side when linked" for both of them. Then open the cabinet with your character in test mode.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
This video was in the sub editor.
https://youtu.be/TKp1phCp8bk

**Comment by MaaiG** [comment]
I have them overlapping!
![Image 001_20-35 (1)](https://user-images.githubusercontent.com/93348499/144719044-71009052-5644-457e-a890-54dd97ee1c3b.png)

**Comment by StruggleDuck** [comment]
As far as I know, this is already a well known issue, and the devs plan on fixing it _eventually_

**Comment by MaaiG** [comment]
I’m afraid the developers have so much work to do that’s the least of their problems.

**Comment by StruggleDuck** [comment]
yea, from my knowledge the reason all of this happens is because the underlying code for determining the position of all the windows is completely broken, and it has quite a few "Band-Aid" fixes in place that _somewhat_ fix the issue, but we still end up with this buggy mess.

**Comment by gerakis** [comment]
They still havent added the bug tag to this one.

**Comment by Rokvach** [comment]
Tested, working correctly.  Closing.

**Comment by gerakis** [comment]
This bug is back again. I just now took this screenshot on the vanilla Herja.

![linked containers](https://user-images.githubusercontent.com/16128947/187108596-9b053bce-18c7-4230-ae0c-08a759254185.png)

I cannot access the storage container because this fabricator window is in the way.
