### ISSUE TITLE
Texture Background - Parasitic mirroring.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7617]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Scaling error with parasitic mirroring.

**Steps To Reproduce**

https://user-images.githubusercontent.com/93348499/144722193-da5001b6-83b8-40fd-ab4e-7b0a99fb515f.mp4

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Сan’t repeat it with a new texture, but here are working copies (*.sub, *.xml):
[_Bad_Background.zip](https://github.com/Regalis11/Barotrauma/files/7654574/_Bad_Background.zip)

The parasite - is part of another texture (ResearchBackgroundWalls.png):
![Image 001_00-04 (1) (1) (1) (1)](https://user-images.githubusercontent.com/93348499/144724558-0bac0041-2647-49d0-8cdf-b4a3d4d56bcd.png)

_P.S. I can report that these textures are contained in my submarine. It has been built over a long period of time and has undergone several game updates, but not more than a one year. ...I think._

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/64bb4c47ac7bd94890ee1f34012748b0ecf1a974.
