### ISSUE TITLE
2 mechanic and one engineer Bug

### ISSUE THREAD

**Issue by Link2049** [Regalis11/Barotrauma#7619]
So this bug is a odd one if you quit the game at a stations, then when you go back to play a again to get crew it will all ways be 2 mechanic and one engineer everytime even if you saw different crew before you quit it will be 2 mechanic and one engineer again and restarting does not fix it.

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to get this to happen. Did it happen in single player or multiplayer? Are you using any mods?

**Comment by Link2049** [comment]
Single player and there were no mods used.

**Comment by Regalis11** [comment]
No known steps to repro, closing
