### ISSUE TITLE
Container submenus close prematurely

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#762]
Hover mouse over a work suit or anything with a submenu and it's an absolute pain in the ass sometimes to keep the submenu open.

**Comment by thegrb93** [comment]
Usually it's not a problem, but there's something that triggers it to start happening, and once it does, it keeps happening. Just had it start acting up in a round I was in.

**Comment by Rokvach** [comment]
Improvements are coming to this issue in the next patch, closing this one.
