### ISSUE TITLE
[Unstable 0.15.18.0] Ready check button doesn't visually reset between outposts

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7621]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you used a ready check on a previous outpost the ready check button is shown as red on the next outpost even though you can use it normally. So visually it just doesn't reset while functionally it does. The button is shown as red after using it because there's a cooldown on when you can use it a second time, so it prevents spamming it. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1ed09e3f-a2c0-4550-8c9b-180ec38b7be9)

**Version**
Unstable 0.15.18.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a12b7f959880be6005766e6622cd75603208756e
