### ISSUE TITLE
[Unstable 0.15.18.0] Bot tries to refill Welding Fuel Tanks in Oxygen Tank Shelves

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7624]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had a bot ordered to clean items and refill oxygen tanks and the bot kept constantly taking partially used/empty welding fuel tanks from cabinets and placed them inside a oxygen tank shelf. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f51d1321-2006-491e-90e7-9b29b2f590ea)

**Steps To Reproduce**
Place a empty or partially used welding fuel tank into a cabinet and order a bot to refill oxygen tanks and clean items

**Version**
Unstable 0.15.18.0

**Comment by ekqvist** [comment]
Should be addressed in Regalis11/Barotrauma-development@71c8a0b

**Comment by ekqvist** [comment]
Pushed a temporary, non-volatile fix to this on the bugfixes branch in b322575. This fix makes the bots only target oxygen generators for now.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
