### ISSUE TITLE
[Unstable 0.15.18.0] Stolen items will always display the item name in red

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7625]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stole some items from a outpost and noticed way later on the campaign that the item name was still colored red
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/10245517-7b9a-4a00-89fa-1bc567de70d8)

**Version**
Unstable 0.15.18.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e7f18f6de22667ebe0105026fa7b9863bf1844c7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
