### ISSUE TITLE
[Unstable 0.15.18.0] Character trait changes each round on multiplayer campaign

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7626]
- [x] I have searched the issue tracker to check if the issue has already been reported.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f1736d98-4889-407e-b51e-3ae0d87d9c5b)![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/228e3a74-deae-45a8-a99d-a14729829538)

**Version**
Unstable 0.15.18.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/feb6526ce72bd8a798bc91bc91929bf6a9eb3fbe

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by TheSurvivalist395** [comment]
> Fixed in [Regalis11/Barotrauma-development@feb6526](https://github.com/Regalis11/Barotrauma-development/commit/feb6526ce72bd8a798bc91bc91929bf6a9eb3fbe)

Link is 404'd.

**Comment by ekqvist** [comment]
@TheSurvivalist395 The link leads to a private development repository so unfortunately you cannot access it
