### ISSUE TITLE
Supercapacitors Powering Electric Discharge Coil in Parallel Not Calculating Load Correctly

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7627]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The load from an electric discharge coil (EDC) seems to not be split correctly among multiple supercapacitors powering the same EDC in parallel. If wired to a single supercapacitor (prefab, no changes in editor)  the drain from one EDC blast is about 50% of a supercapacitors total charge. If powered from two identical supercapacitors, the drain is about 42% from both capacitors. If wired to 4, the drain is about 39% from all capacitors. 

1 cap: 50% drain
2 caps: 42% drain
4 caps: 39% drain

This means its consuming more charge overall the more caps are connected. More than the 10k its supposed to draw. I would expect the drain from 4 caps to be about 12.5% (50 / 4 = 12.5.) That's how it would work in the real world at least.

At first I thought this was intentional; the devs just don't want us to split the load. Then I saw that the vanilla Berilia splits its load on the coilguns and that actually works fine. So something is weird about the way EDCs calculate power drain vs how coilguns do it.

**Steps To Reproduce**
Make a setup like in this picture:

![EDC test](https://user-images.githubusercontent.com/16128947/144728662-bef7c23f-d6e7-4186-967f-27a37a549c63.png)

Don't change any of the default settings. Fire the coil with the button. Check the charge on the capacitors. Then remove some capacitors from the EDC and run the test again. You will see that the numbers don't add up correctly.

The capacitors should be getting power from the junction box, which gets its power from the reactor. Then the capacitors should be connected directly to the coil. Use a button to fire it. I added a text box to measure the battery charge percentage easier.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
This seems to happen both in the editor and the campaign.

**Comment by gerakis** [comment]
You are really consider this to be low prio? This bug messed up my R-29 plans real bad. Yeah I can go fiddle with it in the sub editor but that feels like cheating. Running out of supercap energy is a big problem on a lot of subs. If an electrician could fix that in game they would be considered a hero.

**Comment by ReconDoge** [comment]
I think this might also be related to the fact that discharge coils now sometimes won't stop firing.

**Comment by Regalis11** [comment]
Possibly fixed by `power-rework`, needs testing

**Comment by Rokvach** [comment]
Tested by Jade Harley and confirmed working (video proof), closing.
