### ISSUE TITLE
[V0.15.18.0] Self ordering 'load items' while another order is queued plays wrong dialogue.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7628]
![image](https://user-images.githubusercontent.com/55356135/144730765-90461c09-e5ab-420d-9578-047601e481c5.png)

**Steps to reproduce:**
- Order yourself in crew menu with another order
- Order yourself with any 'load items' order
- Your character will incorrectly use `rearrangeorders` dialog instead of `orderdialogself.loaditems`

**Comment by ekqvist** [comment]
I think this might be an issue with other orders with a lower assignment priority, too. IIRC, that dialogue is used whenever an order is assigned to another slot than the first one. Previously, that would happen only when reordering the current orders on the crew list, of course. But now it's possible whenever a new order is assigned, depending on the order definition. I will look into it.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@1b9ad3e

**Comment by ekqvist** [comment]
Note: remember to test both singleplayer and multiplayer since this included some networking changes

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Ek-Videogames** [comment]
### Issue may need reopening ?

Characters still talk about themselves in the third-person when rearranging crew orders in build **v0.16.1.0**
![image](https://user-images.githubusercontent.com/55356135/151211342-ad1b2eac-c56b-493f-8315-667e442f8ec9.png)

**Comment by ekqvist** [comment]
Yeah, that's definitely a bug. I'll look into it.

**Comment by ekqvist** [comment]
Fixed characters talking about themselves in third-person (Regalis11/Barotrauma-development@476a69d)

Also noticed and fixed the "check your order priorities" dialogue not being used in multiplayer (Regalis11/Barotrauma-development@b99d0cc)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
