### ISSUE TITLE
Votekick is way too strict

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#763]
It takes so many people to votekick someone. Many times the troll gets away with what they are doing.

**Comment by Regalis11** [comment]
The amount of required kick votes can be set by the server hosts. The default is 60%, maybe we should reduce that a bit?

**Comment by thegrb93** [comment]
60% should be fine. Maybe it was just the server I was on. Question though, does votekicking a second person void the first votekick you did? We were trying to kick two people and failed every time. We just resorted to killing them at the start of each round.
