### ISSUE TITLE
Spectator mode soft lock

### ISSUE THREAD

**Issue by CLASSlCS** [Regalis11/Barotrauma#7630]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Played several missions of campaign in same lobby, no issues.
When leaving from a station/port, after the loading screen to the next area, was sent back to the multiplayer lobby screen.
Clicked the button to reconnect (only option is "as spectator")
Couldn't re-assume control of my character, was just standing there watching myself as spectator.
Even when my character died, couldn't respawn (Yes, respawn shuttle was enabled).

**Steps To Reproduce**
Loading into a mission from a station during a campaign, at the end of the load screen end up back in the lobby (not sure how, maybe a loading error or momentary disconnect/desync?), click join back into the mission in progress "as spectator". Be unable to control your character or respawn.

**Version**
Barotrauma v0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Windows 10

**Additional information**
I was not the only person to experience this issue, several other players in the same lobby experienced the same thing. I'm Classics in those screenshots, this was after I had rejoined the game, you can see me stuck standing there spectating myself, unable to controll my character and unable to respawn. Vanilla, no mods. Restarting the mission did fix the bug, but if a player gets stuck by this bug they have no way to communicate as the living can't see spectator chat.
![20211205023633_1](https://user-images.githubusercontent.com/83607673/144739633-45e03d7b-a0a9-4be8-80dc-2ec83aecda1e.jpg)
![20211205023644_1](https://user-images.githubusercontent.com/83607673/144739635-809ee37a-10a1-4648-892e-120fa6af130f.jpg)

**Comment by Regalis11** [comment]
Possibly caused by the same bug as https://github.com/Regalis11/Barotrauma/issues/7345, let's see if this still occurs after the fix is out

**Comment by CLASSlCS** [comment]
Still occurs lately upon loading, sometimes in the debug console (usually around the time that it is generating outposts for beginning/end of level, you'll get text "Recieved disconnect message ()" and that usually seems to trigger it when that happens

**Comment by CLASSlCS** [comment]
Can be resolved in-game only with the command <setclientcharacter "client_name" "character_name">

Commands like <respawnnow> or <revive "name">

So it seems to be an issue where a client is somehow seperated from their character when experiencing certain network disconnect events during loading new areas, both outposts and levels.

Also, I personally have only noticed this issue on P2P player hosted servers, I haven't had any issues with dedicated servers doing this.

**Comment by CLASSlCS** [comment]
One more thing I've noticed, if you have the following issue occur https://github.com/Regalis11/Barotrauma/issues/4137 then close barotrauma and rejoin the same lobby, you often get stuck in this spectator mode soft lock afterwards.
