### ISSUE TITLE
[Barotrauma v.0.15.13.0] Lobby doesnt host

### ISSUE THREAD

**Issue by DetectiveKaktus** [Regalis11/Barotrauma#7631]
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I guess this bug is continue of previous my bug 7445. What's to come: now i cant host lobby ever and even play on servers.

Later I could start lobby with big ping or with becoming spectator with no reason. Now this bug or new bug doesnt allow me to host lobby.

**Steps To Reproduce**
1. Try to host lobby.
2. You should get a connection error or get lobby error in 'servercrashreport.log'. I dont have this file in my folder.

**Version**
Barotrauma v.0.15.13.0 (RealeaseWindows, branch realease, revision 4e66dd7b5d), Windows 10 64 bit

**Additional information**
Also I cannot play on servers. I mean when round starts I got kicked by timed out or something else. 

I wanna say that my internet connection is ok. This is not my fault.

**Comment by Regalis11** [comment]
I'm sorry to hear you're still having issues with the game. :/ What kind of error messages do you get when you fail to host a server or join one? Also, something that could be worth a try is starting up the server directly from the game folder: you can do it by navigating to the installation folder and double-clicking DedicatedServer.exe. There _could_ possibly be some error messages in the window that pops up that'd help us diagnose why you're failing to host servers.

**Comment by DetectiveKaktus** [comment]
![image](https://user-images.githubusercontent.com/59024441/145022443-9c8f1928-d704-44c1-92b1-27642dc1bbe3.png)

**Comment by DetectiveKaktus** [comment]
Steam downloaded something for Barotrauma.

**Comment by DetectiveKaktus** [comment]
![20211208192846_1](https://user-images.githubusercontent.com/59024441/145246299-dc9db784-1ac6-4f23-9b53-5713cc5b1176.jpg)
![20211208192852_1](https://user-images.githubusercontent.com/59024441/145246306-92ddb3b7-d0ca-4605-8eea-a25992884dc2.jpg)
![20211208192857_1](https://user-images.githubusercontent.com/59024441/145246307-0e809296-750b-4e0a-8838-b6172d58165f.jpg)
![20211208192902_1](https://user-images.githubusercontent.com/59024441/145246308-51d08e87-7381-4cac-9dd6-038ce88f5329.jpg)
![20211208192905_1](https://user-images.githubusercontent.com/59024441/145246311-141a4697-0823-42e6-ae33-4fddfd97108c.jpg)

**Comment by DetectiveKaktus** [comment]
When Im trying to load into round.

**Comment by Regalis11** [comment]
No known steps to repro, closing
