### ISSUE TITLE
Modding - SchematicSprite of variants throw redundant yellow warning when a reload is attempted.

### ISSUE THREAD

**Issue by UzricRash** [Regalis11/Barotrauma#7636]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When modding a variant with a new `<SchematicSprite>` there is a chance of a yellow error to be thrown to the console. The error says:
```
[Sprite] Could not parse the content path from the source element (<SchematicSprite> texture="correct_path_to_my_texture" sourcerect="correct_source_rect" />) uri:
```
Notice that the message ends after the "uri:".
[Sprite.cs](https://github.com/Regalis11/Barotrauma/blob/cdfd9751743bfe1ab902278e244af36234eebe3d/Barotrauma/BarotraumaShared/SharedSource/Sprite/Sprite.cs#L260) tells me that the error happens when the sprite is reloaded.
This error does not alter the in-game behaviour, presumably because it happens on reload but does not happen on the first load.

**Steps To Reproduce**
1- Create a mod that uses an itemvariant of a vanilla item that has a SchematicSprite (i.e.: a railgun).
2- Override the SchematicSprite to use a modded sprite in the mod path.
3- Enable the mod and open the sprite editor.
4- Exit the sprite editor and check the console, the error will be there.

**Version**
Windows 0.15.13.0.

**Additional information**
Not critical because everything works despite the error.

**Comment by Regalis11** [comment]
The element seems to be formatted incorrectly: it should be 
`<SchematicSprite texture="correct_path_to_my_texture" sourcerect="correct_source_rect" />`

**Comment by UzricRash** [comment]
My apologies, the syntax is correct in the mod I just borked while copying here the warning.
Further tests show me this error with other Sprites that are not SchematicSprites but are still with itemvariants. Note that in those errors the full path is given so it's not a relative path issue.
