### ISSUE TITLE
Ideas regarding wiring connections and logic chips

### ISSUE THREAD

**Issue by lifearoundfreaks** [Regalis11/Barotrauma#764]
I will refer to another issue often, since it's on the same topic:
[Original post](https://github.com/Regalis11/Barotrauma/issues/392)
I will call it OP.

### Logic chips
OP has almost all of those, but I'm going to share some of my own thoughts on them.

**Comparer**
Instead of using separate chips for each type of a COMPARE operation, as OP suggested, it could be one single chip with all of the operations (the same way as the oscillator chip acts now - you can choose the type of the oscillation). I think, we only really need three types, but I may be wrong: >, >=. =.
**Function**
OP's idea may be hard to implement and/or may cause some problems. So my take would be the same thing as with a comparer. It would have several most common trigonometric functions (also logarithms would be neat) as options in the editor. And it would only do that specific thing.
**Memory**
Indefinitely stores and outputs the last signal which was sent to it. It could hold some value from the game start (you add it via editing), meaning that it can also be used as a 'constant' chip if it has nothing connected to its input. Would be really helpful for more complex schematics, where you need to hold some value.
**Vector merger and vector splicer chips**
Merger gets several _non-vector_ input signals and outputs them as 'input1,input2, ... ,inputN'. For example, if there are connected input signals '1', '0.6' and '-1' the output would be '1,0.6,-1'.
Splicer, on the other hand, does the opposite - it gets a vector and outputs several signals. For example, '1,0.6' would output '1', '0.6', 'none', ... ,'none' on its different 'out' connections. If there are too much vector dimentions, it simply ignores excess ones. I personally want it for smoother lightbulb color changing, but I'm sure, that there will be other uses.
**Multiplication and power**
I simply wanted to add to OP, that multiplication is a must-have for more complex schematics. You don't even need division and sign flip if you have multiplication. 'Power' chips would be nice too, but not as neccesary.
Edit: Well, 'power' chips can be really handy when you need a square root or when you need to divide something by a variable. So power chips are also quite neccesary for more complex things.

### Wiring connections
Some of them may be excessive, (especially considering the size of the wiring panel) but I hope that there will be atleast a few good ideas.

**AND and OR chips**
More input connections on those chips (3-5), because sometimes you need to merge a lot of signals into one (for example, a flooding alarm, connected to all the water detectors onboard). If an input is not connected, just ignore it. For example, AND(_true, true, empty, empty_) should return _true_.
**Steering**
_'autopilot_in'_ - '0' turns autopilot off, '1' turns autopilot on and sets it to maintain position, '2' turns autopilot on and sets it to go to 1st destination, '3' - to second.
_'autopilot_out'_ - outputs current autopilot status. Values correspond to the ones in the 'autopilot_in'.
_'block'_ - while the input here is '1' you can still use the terminal, but any controls are inactive.
**Reactor**
_'set_temperature'_ - sets shutdown temperature. 0 to 10000.
_'set_fission_rate'_ - sets target fission rate. 0 to 100.
_'set_cooling_rate'_ - sets target cooling rate. 0 to 100.
Edit: Thinking about it, also ''toggle_auto_control' for automatic temperature control. And while it's on, ignore any input on 'set_fission_rate' and 'set_cooling_rate'.
**Batteries**
_'set_recharge_rate'_ - sets recharge rate. Either 0 to 100 meaning percents, or clamped between 0 and MaxRechargeSpeed.
_'charge_out'_ - gets the current battery charge level.
**Wifi**
_'set_channel'_ - sets channel. Obviously, also converts float input values into integer ones.
**Doors**
_'block'_ - while the input here is '1', the door will never open.
_'close'_ - works the same as _'toggle'_, but only when the door is open, otherwise nothing happens.
_'open'_ - works the same as _'toggle'_, but only when the door is closed, otherwise nothing happens.
**Junction boxes**
_'power_out'_ - outputs current power.
_'load_out'_ - outputs current load.
or
_'voltage_out'_ - outputs current voltage.

_'toggle'_ and  _'set_state'_ - not sure it is the right way to go, but it would be neat to be able to make overload prevention systems.

### Finally
That's all that I could think of for now, but I would very likely come up with more later.

**Comment by Regalis11** [comment]
We're moving feature requests from the issue tracker to the Barotrauma forums. From now on only actual issues (bugs, crashes, design flaws, oversights) should be reported here. We're doing this because the issue tracker has started to become extremely cluttered - it's getting harder for us to find the more critical issues when they're mixed in with hundreds of ideas and feature requests. And even though we are closing the existing feature requests, we are still planning on implementing many of them further down the line. 

So from now on, please post your feature requests on the [Collaboration section on the Barotrauma forums](https://undertowgames.com/forum/viewforum.php?f=19&sid=3ef7ed701ca460dc3503e2ab4e3cf7c9).
