### ISSUE TITLE
No zoom functionality in graphics settings makes playing game difficult on smaller screens.  

### ISSUE THREAD

**Issue by Cogs16** [Regalis11/Barotrauma#7644]
I normally play on a desktop with 2560x1440 resolution, and I love it. Recently though I tried playing the game on my laptop, with a 1920x1080 resolution. Even though I could resize the hud, the fact that I couldn't zoom in on my character while I was alive made it difficult to play the game. If the graphics panel in settings had a zoom slider, my gameplay experience would be much improved. Most of the screen space on both of the monitors, is black since my character can't see those areas, so being able to zoom would only really be a benefit.

Other than that great game.

**Comment by MaaiG** [comment]
Yea! I think the mouse wheel should work in a wider range! At least more zoom...
