### ISSUE TITLE
Characters read books upside down

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#7645]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
how
![image](https://user-images.githubusercontent.com/55637865/144889037-a87a7a28-86fb-4149-817b-90e86777f0f4.png)
![image](https://user-images.githubusercontent.com/55637865/144889104-cfb16a8d-d1c3-4142-b4b6-ac750f7bc2bd.png)

**Version**
v0.15.18.0

**Comment by StruggleDuck** [comment]
this is actually funny af, kinda hope it stays the way it is

**Comment by LePiromano** [comment]
same tbh

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/305f7188f1113f919537bd4c76eb72d68765d3fa

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
