### ISSUE TITLE
Non-humanoid player controlled characters with "caninteract" set to true can eat characters alive

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#7646]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A player who is controlling a monster such as a fractal guardian can start eating another character as long as they are grabbing it.
This means that a player controlled fractal guardian can stun a player, grab them and eat them alive.
This also means that a fractal guardian can eat bodies in general despite having "caneat" set to false, and can't actually choose not to eat a dragged body.

**Version**
v.0.15.13.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d21a0779b0622288c5724343ec879a68addc8bb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
