### ISSUE TITLE
Greater Than Component Time Frame non-functional

### ISSUE THREAD

**Issue by HalfdeadKiller** [Regalis11/Barotrauma#7654]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Time Frame does not function as expected, when compared to OR or AND components.

**Steps To Reproduce**
Adjust time frame to a value greater than 0 and observe.
Time Frame should make the component output it's true value for that time frame. I'm unsure of the super specifics, but that's how it works in my observations of working with it.

**Version**
Windows 10. Barotrauma v0.15.13.0 rev 4e66dd7b5d

**Additional information**
Attached is a submarine showcasing that AND and OR timeframes function correctly, while GreaterThan does not.

[a.TimeFrameTest.sub.zip](https://github.com/Regalis11/Barotrauma/files/7665834/a.TimeFrameTest.sub.zip)

**Comment by Tsunder** [comment]
greater than's Timeframe description isn't that it holds True output for timeframe though

**Comment by HalfdeadKiller** [comment]
![image](https://user-images.githubusercontent.com/16188887/144978533-632f7e40-fdf2-4351-9fe2-c04e1e9d0668.png)
![image](https://user-images.githubusercontent.com/16188887/144978574-1249424f-0baa-46f5-9d47-f29bfb68ccb7.png)

Indeed it is different. I have no idea how to use that field then.

**Comment by Regalis11** [comment]
As explained in the tooltip, the component outputs a signal if it has received inputs within that timeframe. In your circuit it receives signals continuously, so it turns the light off as soon as you pull the lever.
