### ISSUE TITLE
Map of Remora Sub Displays as Blue Screen

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7655]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing multiplayer I opened the map of the sub using the tab menu and could only see a blue screen. Im pretty sure the map worked earlier in the round so this happened halfway through somehow.

**Steps To Reproduce**
Not sure what caused this so it may be hard to reproduce. I was on the remora on a multiplayer server as a security guard if that helps. Just hit tab and open the map of the sub (second from the bottom). It worked earlier in the round, and then later it didnt.

**Version**
V0.15.13.0 Windows 10x64

**Additional information*
![blue screen map remora](https://user-images.githubusercontent.com/16128947/144978026-bf690604-b5ad-4c85-aec3-8b9f7b83bd81.png)
*

**Comment by Regalis11** [comment]
Thank you for the report!

I gave this a quick test, but unfortunately couldn't get it to happen. I suspected it might've had something to do with the drone, so I tried leaving it behind and later purchasing it back, but that didn't work. We'll keep an eye out for this and see if we can figure out a way to repro it.

**Comment by gerakis** [comment]
Ok. Sorry I didnt have more info for you. Thank you for trying. Yes I think the drone fell out of range or something that round. I remember them talking about it.

**Comment by Regalis11** [comment]
No known steps to repro, closing
