### ISSUE TITLE
Outposts during a level (while undocked) do not produce any oxygen. 

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7658]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Currently in game if one was to swim back to the starting outpost or to the outpost at the end, they would end up suffocating inside due to the fact that their is no oxygen generator. 

**Steps To Reproduce**
while undocked, enter a station either at the end or start of the level

**Version**
Latest version of the game, windows

**Additional information**
Although it may seem like an unimportant thing to fix, I have myself been in numerous situations where the main sub is much further behind or is busy completing a mission, and I am sitting in the station slowly suffocating, unable to get more oxygen from the shuttle due to it either not having enough power/fuel to both re-dock and provide oxygen.

**Comment by Regalis11** [comment]
I'd consider this a part of this ticket https://github.com/Regalis11/Barotrauma/issues/3604
