### ISSUE TITLE
Component AND with Timeframe sends signal without source

### ISSUE THREAD

**Issue by GILLIBON** [Regalis11/Barotrauma#7661]
**Description**
Two buttons is connected to the AND component. In the properties of the AND component I set the Timeframe to 1.00 (the number may be different). When I start the Test mode, the AND component sends signal 1 for the 1 sec.

**Version**
Windows, v0.15.13.0

**Comment by Regalis11** [comment]
Duplicate of https://github.com/regalis11/barotrauma/issues/7242
