### ISSUE TITLE
Mining station inhabitants are suicidal

### ISSUE THREAD

**Issue by cryptopotato-source** [Regalis11/Barotrauma#7662]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

A mining station was generated with a little room without an oxygen vent. Station inhabitant NPCs walk into there and stand around until the oxygen runs out. When oxygen deprivation kicks in they don't try to find safety and just suffocate in there.

![image](https://user-images.githubusercontent.com/34369302/145099954-838f9dbd-7493-4abe-b838-ba7843f2b105.png)

(Life on Europa is hard, but geez.)

**Steps To Reproduce**

Dock to a station with such an unfortunate layout and wait. Can provide a save file on request.

**Version**

Stable 0.15.13.0, Windows.

**Comment by MaaiG** [comment]
I saw that place and I thought it was a glacier with corpse... So I figured they needed body bags!

**Comment by gerakis** [comment]
Your NPC crew members will go die in there too on single player. Its really annoying, just add a vent please.

**Comment by Regalis11** [comment]
I'm afraid I couldn't fully repro this, the bots seem to run out of the room as soon as the oxygen level drops low enough. Maybe this requires some specific kind of outpost layout or generation problem to occur...?

In any case, I added some hidden vents to these rooms to work around the problem (https://github.com/Regalis11/Barotrauma-development/commit/b8bb75ef00bc4724e5c5af9087e5232b976262da).

**Comment by Cusuno** [comment]
I can confirm that the bug definitely exists.

The same happened in my case that the NPCs were suffocating in the same room. They were trying to get out, but for some reason couldn't interact with the door during the "Find Safety" state,

**Comment by ubertpendragon** [comment]
https://github.com/Regalis11/Barotrauma/issues/4335#issuecomment-797856858

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
