### ISSUE TITLE
Displacement wires when objects are ungrouped and moved.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7663]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When moving objects the wire of other objects moves from it's position.
With a lot of components there’s a confusion that’s hard to recover.
![Image 001_23-12 (1)](https://user-images.githubusercontent.com/93348499/145100657-f2d3fbee-9abb-46fc-92d9-0f15010878b5.png)

**Steps To Reproduce**

https://user-images.githubusercontent.com/93348499/145101257-13e999d4-3433-44cc-a364-b0a53a816a17.mp4

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
This thing just killing me!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4231813d6118a57203dc386720b6f5ac9f70ebf1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
