### ISSUE TITLE
On character change, previous character disappears with all their inventory (and carried items???)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7664]
- [x] I have searched the issue tracker to check if the issue has already been reported.
Someone must have reported it before, right? I couldn't find it either way. This issue is so obvious...

**Additional Information**
It's been in the game for years, I think.
One of the most annoying bugs in this game if a player has a full inventory, the round ends and they forgot they had chosen a new character.

**Solution**
When a player changes their character, their items should just drop on the ground in a duffle bag, except for the starting items. Anything in the equipment slots and their inventories/subinventories that isn't a starting item should also drop in the duffle bag (such as things in pockets).

**Steps To Reproduce**
1. Have items on your character (worst case scenario, have lots of valuable items)
2. Change the character
3. Respawn on a shuttle or on the ship for whatever reason (most of the time when a round changes)
I am not sure if items carried in hands are dropped or if they despawn.

**Version**
ALL OF THEM

**Comment by Regalis11** [comment]
This isn't a bug: generating a new character does get rid of the old character entirely, including their items. It could be a good idea to put the items in a duffel bag instead though, we'll consider this!

**Comment by Regalis11** [comment]
We've decided no to address this: the verification prompt shown when you try to change to a new character clearly says you're going to lose all your items.

**Comment by Krzeszny** [comment]
> This isn't a bug: generating a new character does get rid of the old character entirely, including their items. It could be a good idea to put the items in a duffel bag instead though, we'll consider this!

Could you please change it now? It's really annoying when you create a new character and wait for the round to end, but the captain ends the round without a warning.
