### ISSUE TITLE
[0.15.18.0] Bots - Can't repair hatches and doors

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7667]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are not able to repair hatches and doors again.

**Version**
0.15.18.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f41e8a4

**Comment by Rokvach** [comment]
Tested, I didn't spot any issues in bots repairing doors and hatches, working correctly. Closing.
