### ISSUE TITLE
Crawlers takes forever to break down doors

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7668]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crawlers takes forever to break down doors compared to hull shells. Not sure if intentional. I had them rubbing against my airlock door for ages with very little damage being done to it over time.

**Version**
0.15.18.0

**Comment by Regalis11** [comment]
This is actually intentional: we didn't want the crawlers to get through doors/hatches easily because we felt it would've made them so much more difficult to deal with (which in the case of mudraptors is fine, but not for a low-tier enemy that spawns in large swarms).
