### ISSUE TITLE
Bot - When they runs out of revolver ammo, they go seek for more revolver ammo to shoot at intruders, but they only take 1 bullet at a time.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7669]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When bots runs out of revolver ammo, they go seek for more revolver ammo to shoot at intruders, but they only take 1 bullet at a time. If the target is not dead per shot, the bot will proceed to go grab another round again and again.

This might also likely affect Shotguns.

**Version**
0.15.18.0

**Additional information**
I'm not sure what's the best way to deal with this logic is. I don't know if they should grab 3 rounds, 6 rounds, or maybe look for a new gun entirely (preferably full capacity)?

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@5a39585. I think it used to work, but it's probably been broken since the introduction of stacking.

**Comment by itchyOwl** [comment]
Also improved their behavior a bit in Regalis11/Barotrauma-development@8210949 (in dev -> in unstable a bit later).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
