### ISSUE TITLE
Junction Boxes Are Not Becoming Flipped- Potential Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#767]
Not sure if that's intended, but junction boxes have their electricity warning triangles not being flipped in PVP on renegade's vessel.

**Comment by Regalis11** [comment]
It's intentional. The junction boxes are perfectly rectangular so there's not really any reason to mirror the sprite.

**Comment by BlueTheKing** [comment]
What would you gain from it being flipped? Its fine as it is.

**Comment by NilanthAnimosus** [comment]
I don't understand why you would want to flip the graphic of a junction box. If an engine faced the wrong way I could understand. if something decorative like a sign faced the wrong way I could understand. There comes a point where something over 99.9% of players wouldn't even take notice of, effects the game by 0%, and has no conceivable purpose to actually flip.

Not to mention - a mod can simply make it flipable, if its custom sprite graphics actually require it. in this case, I don't even think it cosmetically serves a purpose.

**Comment by rico6822** [comment]
Ok.
