### ISSUE TITLE
Can't sell items that contain other items

### ISSUE THREAD

**Issue by gabepombo1** [Regalis11/Barotrauma#7670]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

Cannot sell welders, sprayers, plasma cutters unless you remove the fuel from them. When the fuel is in the tool, the shop says you can sell the fuel but not the item itself.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Go to a shop and try to sell tools with fuel in them.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
 Latest verison, I am not sure what it is.
**Additional information**

**Comment by ekqvist** [comment]
This is currently intentional behavior. We don't allow selling items without selling or taking out the items contained in them. But it's probably something to think about. We have discussed it briefly in the past, but it would require more discussion and design to make it happen in some way.
