### ISSUE TITLE
Sabotaging and tinkering seems to be broken, most likely due to the repair minigame

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7672]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't sabotage a device because the button isn't clickable, the tinkering button doesn't show up at all. 

**Steps To Reproduce**
Host a server and have traitors enabled, use the starttratormissionimmediately command and find yourself a wrench and a screwdriver, notice that you can't sabotage anything.

Unlock the mechanics tinkering talent and notice that you can't tinker any of the devices because the button is missing from the repair interface.

**Version**
0.15.18.0
Branch: bugfixes
Commit: https://github.com/Regalis11/Barotrauma-development/commit/5da584abf4367329a3d6ad31c693cb4e51678c03

**Comment by Regalis11** [comment]
Fixed the sabotage button in https://github.com/Regalis11/Barotrauma-development/commit/0df8c00e9b3a167156f37edaa4f44e4f802fddfb, couldn't repro the tinkering issue

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
