### ISSUE TITLE
Wiring tutorial incomplete?

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7675]
Going thru tutorial I can wire some items together.
 In game all wires looks nice and aligned.
 If I try to wire something via door, i have to press door button, and wire also pins there.
Pressing door button, then go thru, then rightclick to unpin wire is working, but I can't say it's clear or nice.
 Maybe just forbid to pin wires to door buttons? 
Or note about doors in tutorial text?

**Comment by Regalis11** [comment]
I agree that this is a little clunky, but I can't think of an easy way to address it: in my opinion it needs to be possible to connect wires to door buttons (not being able to do that would heavily restrict what kind of door control circuits you can build), and it also needs to be possible to place wire nodes on the buttons. Something like a different key for pressing the button and placing a node would work, but in my opinion it'd unnecessarily complicate things just to solve a somewhat niche issue that can be worked around by removing the node by right clicking.

**Comment by SoNickRND** [comment]
Then note in tutorial))
