### ISSUE TITLE
sprite bleed in Mining Crane structure

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7678]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
lower right corner has a blue thing
![image](https://user-images.githubusercontent.com/5103517/145279649-e33045d4-fe5e-4259-9316-05c62d19a5b2.png)

**Version**
0.15.13 stable

**Additional information**

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
