### ISSUE TITLE
[Unstable 0.15.19.0] Oxygenite Shards can still be used as an o2 source for tools and diving gear

### ISSUE THREAD

**Issue by strategsc2** [Regalis11/Barotrauma#7679]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was able to use Oxygenite Shard as an o2 supply for Plasma Cutter/Diving Suit, which should not be possible, according to a changelog.

**Steps To Reproduce**
Spawn an Oxygenite Shard, and insert it into a Plasma Cutter.

**Version**
Windows 10, 0.15.19.0 

**Additional information**
Initially I tried to test how the game will react to a save from stable version, that contains a character possessing an item that loaded with an Oxygenite Shard, but I was able to reproduce it on a fresh save as well.

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
