### ISSUE TITLE
Double clicking an item to switch to/from hand will sometimes drop it

### ISSUE THREAD

**Issue by thegrb93** [Regalis11/Barotrauma#768]
Probably related to https://github.com/Regalis11/Barotrauma/issues/558

**Comment by rico6822** [comment]
This thread is a duplicate. Somebody already reported that before.

**Comment by rico6822** [comment]
I have experienced this issue besides of updates.

**Comment by thegrb93** [comment]
Just tried playing the alpha some more today. The problem is still very bad if not worse.

**Comment by Regalis11** [comment]
Just to clarify, by alpha do you mean the publicly available version or the dev version? I haven't encountered in the dev version so far, could be that it's been accidentally fixed by some changes to the inventory UI/syncing logic.

**Comment by thegrb93** [comment]
The publicly available one

**Comment by Regalis11** [comment]
Another attempt to fix this: 5c06210. I'm pretty confident it's fixed now: we found out that it's easy to reproduce by moving items around in the inventory while inside a sub that's moving fast. Haven't been able to reproduce it anymore after 5c06210.

**Comment by Rokvach** [comment]
I couldn't reproduce this with my previous method of testing the issue, so I can only assume that it is fixed now, closing.
