### ISSUE TITLE
Repair packs don't work

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#7681]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Repair packs can't be used to repair anything

**Steps To Reproduce**
Try to use a repair pack

**Version**
v0.15.9.0 (Among the Ancients) and later

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b71330fe7536b70140680bc08166b58bd57d3e9c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
