### ISSUE TITLE
Pirate Captain/Lord should stop giving orders once they get captured

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7682]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Taking a Pirate Captain as a hostage causes the captain to spam your chat
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c737f8f3-24cf-45a0-b756-4446cb0f0610)

**Steps To Reproduce**
How I tested this was
1. Take control of Pirate Captain
2. Put handcuffs on them and teleport to your submarine
3. Notice that the captain will start spamming the chat with orders

**Version**
0.15.19.0
Branch: Bugfixes
Commit: https://github.com/Regalis11/Barotrauma-development/commit/76cf4c344adeeeb357f8e05746d739daea6f6ba5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ce72ea3e5890f887c8ef53207c6bbdd5a29189a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
