### ISSUE TITLE
[0.15.19.0] Microphone Range has became very small

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7683]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Was playing last night in my new sub in P2P multiplayer:
[50L1-TUD3 Transportation.zip](https://github.com/Regalis11/Barotrauma/files/7686019/50L1-TUD3.Transportation.zip)

Players had a really hard time hearing eachother like 2 rooms across. Even when we were out inside a cave mission with one person in a shuttle, I can see another diver infront of me by like 15m but he couldn't hear me until he was under 15m.

**Version**
0.15.19.0

**Comment by Regalis11** [comment]
Couldn't find a way to repro this unfortunately :/
![image](https://user-images.githubusercontent.com/14351070/145428883-b42a9b1a-775a-4ba0-ade5-44c809a73ff7.png)

I assume you checked that you had equipped working headsets with batteries left, and everyone was using the same channel?

**Comment by Kaillera** [comment]
https://clips.twitch.tv/SleepyPhilanthropicHerdPanicVis-TnTHR8xzRgx4WyDY

**Comment by Kaillera** [comment]
https://clips.twitch.tv/ThoughtfulAssiduousAyeayeDoritosChip-Xbb68J-SgUfsVc_n

**Comment by Kaillera** [comment]
[Solitude.zip](https://github.com/Regalis11/Barotrauma/files/7686152/Solitude.zip)

Also try this save file and replace your characters with Kaileris and Darkrider and see if that changes anything.

**Comment by Kaillera** [comment]
I can give orders to bots just fine, but not to players that's a like 10m away from me.

**Comment by Regalis11** [comment]
That .zip doesn't contain any character data. Looking at the video, it seems that Darkrider is using channel 1, so I have a feeling this is related to the radio channels and [this ticket](https://github.com/regalis11/barotrauma/issues/7689) somehow.

**Comment by Kaillera** [comment]
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/7691646/Multiplayer.zip)

was asleep, here's the latest save and server settings.

**Comment by Kaillera** [comment]
[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/7691669/Barotrauma.zip)
heres my configs too

**Comment by Kaillera** [comment]
There's also a strange issue. When I host my server, my server's LOS setting is always reverted to none and respawn shuttle is off and selected as Hemulen everytime I relaunch the game.

When I close the game out and open it quickly after changing it back to opaque and respawn shuttle on, I get steam cloud cannot fetch my sync.

**Comment by Regalis11** [comment]
Thank you for the extra info! I couldn't quite get to the bottom of this yet, but I got some more clues about what's going on here. For some reason the headset in your inventory is set to the "None" team (as opposed to "Team 1"), which prevents it from communicating with the other players' headsets. And might also explain https://github.com/regalis11/barotrauma/issues/7689

**Comment by Kaillera** [comment]
> Thank you for the extra info! I couldn't quite get to the bottom of this yet, but I got some more clues about what's going on here. For some reason the headset in your inventory is set to the "None" team (as opposed to "Team 1"), which prevents it from communicating with the other players' headsets. And might also explain #7689
> 
> > I get steam cloud cannot fetch my sync.
> 
> This could potentially be explained by your cloud storage space being full (due to a large number of custom subs and saves maybe?).

Should I just hack my character save to change the headset team value then?

**Comment by Kaillera** [comment]
> There's also a strange issue. When I host my server, my server's LOS setting is always reverted to none and respawn shuttle is off and selected as Hemulen everytime I relaunch the game.
> 
> When I close the game out and open it quickly after changing it back to opaque and respawn shuttle on, I get steam cloud cannot fetch my sync.
> 
> But even if there's no sync error when I give it more time, it still resets my server settings.

I don't think this is a steam cloud issue this time. Moving it to #7706

**Comment by Kaillera** [comment]
> Should I just hack my character save to change the headset team value then? We started with our headsets like that.

Tried it, didn't fixed anything. Here's another issue we found: JP was able to give me contextual orders, but I don't see it on my end:
![20211210122224_1](https://user-images.githubusercontent.com/5086682/145607540-040b793f-8475-44ad-959b-17c716663ece.jpg)
![Capture](https://user-images.githubusercontent.com/5086682/145607545-a176117b-d68d-4553-b66f-e9c8a19bd671.PNG)

**Comment by Kaillera** [comment]
Okay so we did more testing today: The issues seems to happen on my server only (As far as checking with 3 other hosters). Not every players are affected by the issue in my server (Though usually they are). Rokvach was the only one so far that was able to not be affected by the issue in my server. Rokvach found these in the server log:

![](https://cdn.discordapp.com/attachments/668819422919524352/918958205789433936/unknown.png)

Any players infected with this bug on my server will override every headset that they touch, even instantly when they take control of other characters.

This issue does not exist in the current Stable version of the game, even though the same LinkToChat becomes False in Stable.

**Comment by Regalis11** [comment]
That's a great find! I suspect this is related to the "allow linking wifi to chat" server setting, which determines whether the "link to chat" setting is editable or not. The players who don't have settings management permissions won't be notified of the state of that setting, which will cause them to get the editable properties mixed up and switch LinkToChat to false. This most likely also explains https://github.com/Regalis11/Barotrauma/issues/7689

**Comment by Rokvach** [comment]
Oh yeah I didn't even think about the "allow linking wifi components to chat" setting, on my server its disabled so that would explain why we didn't experience the issue when I was hosting. Can't remember if its by default disabled or enabled, but if its enabled by default I think we should try and get this fixed for the upcoming update.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef747547ec0580808f7b1972f7720514cfd9088c. Steps to repro:

1. Host a server with "allow linking wifi to chat" enabled.
2. Join the server as a client without settings management permissions
3. Start a round: you should see that `set "LinkToChat" to "false"` message in the server log.
4. The client's headset should now be in this broken state.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore, working correctly. Closing.
