### ISSUE TITLE
[0.15.19.0] Wreckless Level

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7684]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Solitude.zip](https://github.com/Regalis11/Barotrauma/files/7686152/Solitude.zip)
No wreck for this level to do my mission at.

**Version**
0.15.19.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5682223915a57f59b3946e68c67abeb292517fb6

**Comment by Rokvach** [comment]
There hasn't been any further reports of this happening in Unstable, nor have I noticed this happening during my tests. Seems to be working correctly. Closing.
