### ISSUE TITLE
Connecting signal out pins on navigation terminal in anything other than sequential order results in misaligned interface

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7685]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you attach wires to the signal out pins of the navigation console (the captains steering terminal) the display gets messed up. So if you have nothing on pin 1 or pin 2 but put a wire on pin 3, the display gets weird. Its not as bad if you use pin 2 only, but still messed up. See screenshot.

**Steps To Reproduce**
Create a navigation terminal in sub editor. Attach a wire to "Signal_Out_3" only. Enter test mode and open the navigation terminal. See that the display is all messed up; you cant even read the button. The same thing happens if you do Signal_Out_2 only but not as bad.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
![dont connect to terminal 3](https://user-images.githubusercontent.com/16128947/145433340-fb6516d1-2bc2-4545-a1ee-0c719c9ca007.png)

**Comment by MaaiG** [comment]
Yes! Buttons are not scaled for second and third connections.
![Image 002_20-01](https://user-images.githubusercontent.com/93348499/145442662-a15e4d48-6e0e-46cf-bcd2-43249f553068.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3397f5c28aecacf07001fb35d45cc7ff28e65fab

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
