### ISSUE TITLE
Husk infection is noticed too early

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#7688]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you're infected, you instantly get a red message, unless it's your first time getting infected, you instantly know you've been infected, which removes the threat of the infection (if you have the means to cure it). Having a teammate with a health scanner also makes it easy to evade, but that at least requires an item and another person to be there.

This is kind of a suggestion, but i feel like it's a design issue so i put it here.

Maybe increase the time for the red messages to appear or just remove them?

**Version**
v0.15.19.0

**Comment by strategsc2** [comment]
I'm not sure if this red message is always accurate. At least once I received this message after I got bitten, but didn't got the infection.

**Comment by Regalis11** [comment]
This seems to have been changed accidentally in https://github.com/Regalis11/Barotrauma-development/commit/d6713331297085625b491c37866242161c70a97f (link to a commit in our private repo), fixed in https://github.com/Regalis11/Barotrauma-development/commit/220ef7e09bb443a6ca400932724421b537aac944

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
