### ISSUE TITLE
VIP and Personnel NPC will keep PUCS on forever if they were ever to put it on

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7692]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
VIP and Personnel NPC will keep PUCS on forever if they were ever to put it on.

Only have PUCS on your sub. If there's any water hazards, they'll put it on and never put them back.

**Version**
0.15.19.0

**Comment by gerakis** [comment]
That would be quite useful for bots, but for escorts I just hope they dont keep the suit.

**Comment by Kaillera** [comment]
> That would be quite useful for bots, but for escorts I just hope they dont keep the suit.

Yeah they keep the suit and whisk it out of existance at the end of the level

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
