### ISSUE TITLE
Error while reading entity of the type Barotrauma.Item (nullref exception in ItemPrefab.Find)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7694]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the same modded server where everyone starts crashing exactly after 2 missions (the save file is only 300KB) I got an unusual error:
![Barotrauma_Xxrgpr23Wm](https://user-images.githubusercontent.com/10529134/145501793-2b96a76f-1bb6-40f2-b201-6e8779686728.png)

**Steps To Reproduce**
Start a third mission with specific... mods?

**Version**
v0.15.13

**Additional information**
Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Advanced Medicine, DynamicEuropa, BaroTraumatic, Stations from beyond, Undersea Horrors, Survivor Monster Pack Test fixes, Survivor Other Creature fixes, Survivor Survivator Fixes, Survivor Extended Monsters Fixes, Survivor Xanmonsters2 Fixes, Survivor Xanmonsters1 Fixes, Huskmod, ADV Beacon Stations, BaroCraftables, Backpacks, JobsExtended, Useful Trash Can, Saber Deep Diving, EK Gunnery, EK Dockyard, EK Utilities, EK Armory, Hazardous Reactors, Hazardous Reactors + advanced medecin patch
Level seed: Gortyna FlexusDyfed
Loaded submarine: EKM_Stiletto_Mk-III Custom 2 (BD49439A50D8DCDB62BD4BFCCF16AB68)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

**Comment by Regalis11** [comment]
Hmm, this is a weird one. The stack trace seems to imply that there was an item with neither a name or an identifier in the sub file, which prevented it from finding the correct item prefab. I have no idea how that can happen, but I added some extra logging in https://github.com/Regalis11/Barotrauma-development/commit/afc299d0ff7be2d4de2aa9866f1ea2ca0df4cdb9 to help diagnose this.

**Comment by Rokvach** [comment]
There  hasn't been any sightings of this happening in Unstable, seems to be working correctly. Closing.
