### ISSUE TITLE
If an endworm dies to "unstoppable bleeding" it doesn't count as your kill

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#7696]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If an endworm is splitted and it dies due to the "unstoppable bleeding" it gives itself when split, the kill wont count as yours, so you wont get the achievement, the bounty hunter reward, or any kind of reward for the kill.

**Version**
v0.15.19.0

**Comment by gerakis** [comment]
I was wondering why I didn't get the achievement.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e663c945c812ab1d12eac3c478050f24a3facc75

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/aeb526ed334f61686bb57bf860653f8ae553db15:

> Don't use the "LastAttacker" to determine the killer when the cause of death affliction has no source. This leads to the killer being determined incorrectly when some other affliction kills a character after an attack: e.g. if you attacked someone with a wrench and they died due to high pressure afterwards, you'd still be considered the killer. Note that this might prevent the killer from being determined if there are cases left where we fail to track the source of an affliction correctly, even though some of these issues were addressed in https://github.com/Regalis11/Barotrauma/issues/7696.

**Comment by LePiromano** [comment]
fix doesn't seem to work, testing it with the bounty hunter talent

**Comment by Regalis11** [comment]
Ah, it seems talents were still determining the killer incorrectly. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c9cabe1b6b08873ee5a67a16f58a4291046e5808

**Comment by Rokvach** [comment]
Closing.
