### ISSUE TITLE
Campaign character permanence and permadeath

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#77]
As of now, if you survive the campaign mission as a character with like 20 revolvers in your inventory, all of it will be gone the next mission, though the sub state persists.
Thinking about it, I think for Campaign mode there should be a similar crew system to single-player. Perhaps you don't pick "job preferences" but choose "characters" with randomized stats and job? Or maybe just do job prefs on first-come-first-serve basis, and starting from your first spawn you will keep playing that job with that skill set until your demise?

In the event that you die, you will be able to take an empty job slot. Expanding on this idea, an EXP mechanic could be thrown in where, if you complete a mission, every surviving crew member will get several skill points they could spend on their skills and improve themselves, which means that in campaign endgame, if you manage to survive with those characters, you will have a very efficient and skilled crew that can do many jobs at once.

This could also be extended to traitor victory/loss, where for every detained traitor, surviving crew gets a slight EXP bonus, while traitor victory will boost their own exp.

**Comment by Regalis11** [comment]
Added in the dev branch
