### ISSUE TITLE
Xenocide Achievement not working

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7701]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Currently, it would appear that the Xenocide achievement is not counting the players kills correctly. I have been playing the game for over 400 hours now and the achievement claims that I only have killed 30 monsters. I know for a fact I have killed more than that, even in hand to hand combat alone.

**Steps To Reproduce**
Kill creatures for a while, then check achievement.

**Version**
current versions

**Additional information**
More proof that the achievement is broken is the fact that only 1.9% of people have the achievement, even though that number should be much higher.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8956dc3ac415382c1710bf077f8dde59956d741

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
