### ISSUE TITLE
[0.15.19.0] Server settings keeps reverting or defaulting

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7706]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I create a P2P server, open Server Settings for the first time, but every other settings are default or off. I close the Server Settings and open Server Settings again, it brings back my original settings. I change Line of sight effect to Opaque and On.

I close the server, and host the server again without relaunching the game. I open the server settings again and still see every other settings are default or off. Closing it and opening it again brings back my old setting. Now for some reasons Line of sight effect and Respawn Shuttle settings are specifically reverted back to None and Off. All other settings like Allow respawning is being saved.

**Version**
0.15.19.0

**Comment by Kaillera** [comment]
I tried manually changing losmode and userespawnshuttle in my serversettings.xml, but it reverts back to off too.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e85fabb8a080acc1ef318d09bd1b2debc5c5d40

**Comment by Kaillera** [comment]
Working in 0.15.20.0
