### ISSUE TITLE
Unable to use workshop_download_item with anonymous login in steamcmd

### ISSUE THREAD

**Issue by tconnard** [Regalis11/Barotrauma#7707]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using steamcmd's workshop_download_item command mod fails when not logged into an authenticated steam account.
According to https://steamworkshopdownloader.io/contact (under "Download not supported by game." subheading) it is possible to enable downloading workshop mods for anonymous steamcmd users
>The exact steps are: log into steamworksm, go to the page of your app (https://partner.steamgames.com/apps/workshop/[appid]), scroll down to "Technical tools", go to "Edit steamworks setting", go to the "Workshop" tab, scroll down to the setting "Enable anonymous game servers to download workshop items" and check the checkbox, hit "Save" on the bottom of the page, then you probably have to Publish the app. Unfortunately I can't show screenshots because that breaks the NDA.

**Steps To Reproduce**
```steamcmd +login anonymous +workshop_download_item 602960 2005463692 +quit```

**Version**
Barotrauma Dedicated Server 0.15.13.0 (ReleaseLinux, branch release, revision 4e66dd7b5d)
**Additional information**
Yes I am aware this won't make the mods "just work" but it does help with dedicated server automation.

**Comment by Regalis11** [comment]
Thank you for the report! This should now be fixed.

**Comment by Rokvach** [comment]
No issues, closing.
