### ISSUE TITLE
[Unstable 0.15.20.0] "Repair devices past their normal maximum condition" talents cause repair minigame to not register some "successful" clicks

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#7710]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Acquiring talents that allow players to repair devices past their maximum condition (Mechanic/Engineer) causes the repair progress bar to not indicate the actual area for "successful" clicks, which can cause the character to get stunned even if they are well within the progress bar.

**Steps To Reproduce**
Get the Ph.D in Nuclear Physics (Engineer) or Aggressive Engineering (Mechanic) talent and attempt to click during the minigame as soon as the line reaches the progress bar.

**Version**
Unstable 0.15.20.0
Windows 10

https://user-images.githubusercontent.com/15182031/145636038-b670ab2b-d075-4044-938d-4d540b5af482.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e2ffa28e7ad1ce843fe2240a79a474eb98387f37

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
