### ISSUE TITLE
[V0.15.20.0] Miscolored shell segment on Orca 1

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7711]
Shell segment between the airlock and docking port was missed when converting to new color scheme.
![image](https://user-images.githubusercontent.com/55356135/145653443-5f75d05b-d6b8-48f5-b866-cf5727ec3aae.png)

**Comment by ZeWaka** [comment]
Here's [a link to a fixed file](https://drive.google.com/file/d/14n_s5GZzQ9EGF67ACrbMLfuVAM0Rzo-8/view?usp=sharing), can't PR due to the recolor not being present with the current repository version.
Also would probably be pretty unreviewable due to the binary format.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ba9292532745ff4d3165db39d67344332ac8afe

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
