### ISSUE TITLE
[V0.15.20.0] Code / Modding - weird hitscan interaction when holding a shield

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#7714]
Shell shield now stops bullets as it should - and requites two hands to hold. However, if say a modder wanted to add a shield that could be held with one hand to allow firing a weapon such as revolver in the other - a strange interaction occurs in which **the hitscan weapon seems to fire from the shoulder of the character rather than the correct muzzle position of the weapon.** This causes the shot to impact your own shield.
No shield:
![image](https://user-images.githubusercontent.com/55356135/145663400-69e1279f-7c67-4abc-945e-0aaa9a204584.png)
With shield:
![image](https://user-images.githubusercontent.com/55356135/145663391-27a96281-938d-4175-8662-20148cc9810a.png)

### Steps To Reproduce:
Custom item is just an overwrite of shellshield with slots changed to `slots="RightHand,LeftHand"` 

### Additional Information:
This issue seems to only happen when the shield is being held by your character. Firing through a shield while standing behind it poses no issue and hitscan works as expected.
![image](https://user-images.githubusercontent.com/55356135/145663541-f9d20239-fd75-4237-ac94-829cc3cfb277.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/975b68e58711e33184bfffede5afa75d5a3c6cc3

**Comment by Rokvach** [comment]
This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.
