### ISSUE TITLE
Components - lack of uniformity

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7722]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Textures shifted, sizes different.

**Steps To Reproduce**
![Image 003](https://user-images.githubusercontent.com/93348499/145681465-666fd7eb-0574-43cb-a579-39982b9b7d52.png)

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
I think you know that, but I’m still creating that theme. It wouldn't hurt.

**Comment by Ek-Videogames** [comment]
Its also commonly known issue among submakers that this breaks wiring grid functionality.

**Comment by Regalis11** [comment]
Note for art: these should preferably be 32x32 px in size to make them adhere to the grid.

**Comment by MaaiG** [comment]
> Note for art: the sprites should preferably be in 32x32 px resolution to make them adhere to the grid.

Forgot to mention:
https://github.com/Regalis11/Barotrauma/discussions/6543
[Mod!](https://steamcommunity.com/sharedfiles/filedetails/?id=2590928641&searchtext=32x32)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/3a5e4b313fd3a6eec5d51fe140efa3d782e51b1f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
