### ISSUE TITLE
Misson selection screen auto align feature?

### ISSUE THREAD

**Issue by SoNickRND** [Regalis11/Barotrauma#7725]
When selecting mission, card is popup, blocking right part of screen (with possible routes too)
 Maybe better re-center current on ship position after clicking on destination?

**Comment by SoNickRND** [comment]
![image](https://user-images.githubusercontent.com/125238/145687811-ca534228-35ea-430f-9a75-f290d865f886.png)
![image](https://user-images.githubusercontent.com/125238/145687815-7363d358-8d6b-4494-8ef5-2cda4aba0f22.png)
I found there is a A|D for moving map, but it not very user friendly)))

**Comment by gerakis** [comment]
Suggestions for improvement to the game go in the discussions tab above, but they seem to get mostly ignored. I like your suggestion.

**Comment by Regalis11** [comment]
As a side note, you can also move the map with the middle mouse button. I think this is a good suggestion as well though, it's particularly annoying when the mission screen pops up over the location you selected.
