### ISSUE TITLE
The water animation from pump goes beyond the hull boundary

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7728]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The animation of the pouring water penetrates the other hull.

**Steps To Reproduce**

https://user-images.githubusercontent.com/93348499/145689826-35242368-3432-418a-bb8e-3307be34f4b8.mp4

**Version**
v0.15.13.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by gerakis** [comment]
Its much more noticeable if you have the pump near the left wall.

**Comment by MaaiG** [comment]
v 0.17.12.0 - Nothing has changed but closed! Why?
