### ISSUE TITLE
About Servers

### ISSUE THREAD

**Issue by Chaos456456** [Regalis11/Barotrauma#773]
![image](https://user-images.githubusercontent.com/35542296/45220872-55528c80-b2b8-11e8-8527-7e2fd231e9d1.png)
How make this green messages in my server?

**Comment by Chaos456456** [comment]
How make this green messages*

**Comment by rico6822** [comment]
You need a plugin for it.

**Comment by rico6822** [comment]
Plugin is a term used in many video games with multiplayer feature. Plugin is a script to multiplayer's gameplay features most commonly for administrative purposes.
