### ISSUE TITLE
Gear menu on status screen peeks out

### ISSUE THREAD

**Issue by Torusaynim** [Regalis11/Barotrauma#7731]
- [X] I have searched the issue tracker to check if the issue has already been reported

**Description**
When gear menu is collapsed (1st screenshot), gear menu on status screen peeks out (2nd screenshot)

**Steps To Reproduce**
![1](https://user-images.githubusercontent.com/56824839/145690376-3e9dc8dd-27a5-43bf-a12a-cb819d9ed045.jpg)
![2](https://user-images.githubusercontent.com/56824839/145690381-6abfdb26-31cb-4e67-954a-f15067391394.jpg)

**Version**
v0.15.13.0 (Windows, branch release)

**Additional information**
None, close this if this is not an issue

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce8f4ce9ae2b07130c741232c683dfbe3d711074

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
