### ISSUE TITLE
Items Wont Stack into cargo scooter on D-click

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7736]
**Description**
Items Wont Stack into cargo scooter on D-click

**Steps To Reproduce**
Use cargo scooter, double click items and receive error message. 

For instance, with open slots, and partial stacks, double clicking paralaxys results in error bloop noise instead of going into the scooter.

requires actually hopping off scooter, grabbing item into hands, then putting into scooter.

Seems inconsistent? As you can grab the amoeba thing, then drag it directly into scooter from the amoeba inventory without dismounting.

current steam version

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this.

Here's my initial inventory:
![image](https://user-images.githubusercontent.com/14351070/145816205-65e4754d-fba9-494c-b86f-e7f2d95ebc37.png)

Double-clicked on paralyxis:
![image](https://user-images.githubusercontent.com/14351070/145816307-d1185a44-1ec2-4ea8-926b-16c8538d6e09.png)

And it seems to stack correctly:
![image](https://user-images.githubusercontent.com/14351070/145816356-1b68908f-fab3-4532-9c76-2c68b7e48caa.png)

**Comment by Regalis11** [comment]
I'm sorry but I don't quite follow. You mean you're trying to move the item from a container (like a cabinet?) to the scooter when it's equipped? I was unable to repro it that way either.

**Comment by Dopamin3** [comment]
No. Drop the item on the ground, hold the scooter, double click the item.
It doesn't go into the scooter. It should.

**Comment by Dopamin3** [comment]
Sorry, with full hotbar***

Here is html for twitch stream:
Https://www.twitch.tv/videos/1233165682

Timestamp for demonstration:
1:59:37

I narrate it and explain. You can see/here exact demonsrratiom here.

**Comment by Regalis11** [comment]
I don't think this is a bug: clicking on dropped items should not put items in the scooter (or any other container you're holding) automatically.
