### ISSUE TITLE
Switches and Levers don't have "Picked required" options in the item's Controller settings

### ISSUE THREAD

**Issue by notphyre** [Regalis11/Barotrauma#7738]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The switch and lever objects in the sub editor do not have settings for "pick required" like buttons and button doors, which can be used to make them only interactable while holding ID cards with specific tags.

**Steps To Reproduce**
In the submarine editor, place down a button and scroll down to the Controller section of the item settings and there will be a box for "Picked required" where tags can be added. Place down a lever or switch and see that it does not have these options in Controller settings.

**Version**
v0.15.13.0

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
