### ISSUE TITLE
Make Flares Activate Upon Pressing "Use"- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#774]
Some people accidentally activate flares by equipping into hands.

**Comment by Regalis11** [comment]
The use-button has been removed in the dev branch.

**Comment by rico6822** [comment]
Why?

**Comment by Regalis11** [comment]
Because all the items that were previously used with the "Use" button are now used via the new health interface.

**Comment by NilanthAnimosus** [comment]
Hmmm, some mods try to add things like a use to shoot yourself, or trigger an additional item effect beyond that of the medical scope, such as an item that requires usage before being tossed (Or letting it detonate in your hands) - I assume moddable item aspects like this are no longer possible from this change?

It does make sense to remove the Use button though, and maybe #195 can be closed as a result of these changes (It no longer exists to need a cooldown). though I feel it might be removing a potential secondary/tertiary function from items (Especially for thrown ones I think).

**Comment by Regalis11** [comment]
@NilanthAnimosus It's still possible to shoot yourself or use other items on yourself via the health interface, but obviously that's not an optimal way to do it when you're doing something like arming a grenade before throwing it. 

I do think something similar to the Use button should be implemented, but imo the way it was done before always felt a little hacky - it was mostly used for things other than it's intended usage, the button on top of the inventory felt out of place and there was no indication about what it does (even though it behaved completely differently depending on the item). Something like a context-sensitive dropdown menu might be a better way to go, and would allow more than one option ("turn off", "activate", "change channel"...)

**Comment by NilanthAnimosus** [comment]
its funny, I was just thinking of context menus when looking at another issue before checking the comments on this one, Had a very similar thought that context menus would be an amazing way to go about things. though trying to arm a grenade via a context menu when something is chaotically trying to rip your head off down the corridoor may not be amazing for that either - A method of "Quick use" or a common "Quick Action" beyond the aim and main use (Such as Attack) key would be nice in of itself. a tertiary / secondary function that is not directly the aim / attack function.
