### ISSUE TITLE
Remora AI Interaction

### ISSUE THREAD

**Issue by Testingforfree** [Regalis11/Barotrauma#7742]
Noticed some odd AI interactions when using Remora in single player campaign, probably needs further verification and to be broken down into discrete bugs.

- When AI ordered to 'repair all system' there is a tendency for AI to loop around in armoury area next to cockpit
    -possibility that AI is detecting an un-interactable system
    -may be linked to a bug where buying a new submarine and applying existing durability upgrades cause systems to spawn in damaged 
- When AI ordered to 'repair leaks' there is a tendency for AI to put on diving suits and walk into walls
    -noticed that this can happen when no damage is visible on 'control terminal'
    -possibility that mapping of what AI should/can fix vs damage visible on console out of sync
    -issue can be worked around by sending character outside to fix hull damage
- AI drowned in ballast tank when diving mask and usable canister was available in inventory (tentative)
    -may be due to tank not always full
    -may be due to AI idling after task finished 

v0.15.13.0
Windows

**Comment by Kaillera** [comment]
Overall the bots are actually pretty bad in the current Stable Build. There's a huge difference between stable and unstable ai logic currently.

There's a night and day difference between them when I was seeing if my new large sub would play well in stable and saw lots of wall rubbing myself.

**Comment by Testingforfree** [comment]
![image](https://user-images.githubusercontent.com/96045680/145857005-3e3ecba3-d03f-42aa-8e7c-b99150183c21.png)

For first dot point, bot seems to be shimmying in the purple box. I looked in the sub editor and the only objects in the area are the rack and super capacitator.

It seems to be able to attraction point.

![image](https://user-images.githubusercontent.com/96045680/145860290-c921352f-48d2-4f2d-a818-a8e41e7a8a6a.png)

and above as below.

![image](https://user-images.githubusercontent.com/96045680/145860666-f6053615-9a60-43f0-af7a-3f152d126775.png)

This is where the disco is.

![image](https://user-images.githubusercontent.com/96045680/145861357-d6552cad-c51e-449e-b79d-10f2c49cccfd.png)

Given the dance floor goes both high and low, I think my initial guesses are moot. Now I can't even guess what is going on anymore.

**Comment by itchyOwl** [comment]
I noticed that the bots sometimes attempted to reach a leak in the drone from that point. Hopefully fixed in Regalis11/Barotrauma-development@14fa671, which should prevent the bots getting stuck there, but doesn't solve any pathing issues (if there's any).

Other than that, I didn't encounter any issues. 

Needs testing and clear definition of the issues + steps to repro to be able to debug this further.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
