### ISSUE TITLE
Alien ruins coil sensor and vent

### ISSUE THREAD

**Issue by Testingforfree** [Regalis11/Barotrauma#7744]
The electric coil sensor in alien ruins can be interacted with, without any tools.

The interface will allow the player to have the sensor only detect humans, monsters or all.

Unsure if this is an intended feature or the only intended way to neutralize sensor is meant to be the alien access panel.

Also finding black wire in alien access panel for vent access around to bypass coil sensor. This wire cannot be removed from inventory unless switched with a curio into the access panel.

**Comment by danielasteljoki** [comment]
Not intentional. Fixed in cee9de9.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
