### ISSUE TITLE
Buying new submarine after full upgrade

### ISSUE THREAD

**Issue by Testingforfree** [Regalis11/Barotrauma#7745]
When buying new submarine after full upgrade in campaign (humpback to remora), upgrades did not apply properly (mainly noticed via durability).

Systems seems to start off damaged but cannot be repaired. Damage persists after game restart.

When systems decay, the damage can be repaired to full.

Workaround to use overclock tinker to cause damage, so that system can be repaired.

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7085
