### ISSUE TITLE
Infinite Scaling Interactions (more balance than bug?)

### ISSUE THREAD

**Issue by Testingforfree** [Regalis11/Barotrauma#7746]
Medic, mechanic and assistant have infinite scaling through skill system (unsure if intended)

-medic genetic refining gives +5 to medical and provides infinite scaling speed, att speed etc
-mechanic gives gains damage via deconstruction
-assistant can gain damage and health via skill cap removal

May be more of a balancing issue than bug, or an issue of long playtime but scaling can get a bit ridiculous.

Some unintended effects may be assistants or mechanics exceeding damage threshold after accidentally hitting another character with tools with single hit, causing AI aggro.

**Comment by Regalis11** [comment]
This has been addressed in the unstable branch
