### ISSUE TITLE
Electrochemist stun works on submarine weaponry and ranged weapons

### ISSUE THREAD

**Issue by Testingforfree** [Regalis11/Barotrauma#7753]
Electrochemist effects submarine weaponry. Shooting a character with electrochemist (using a coilgun) will stun the gunner out of periscope.

Ranged projectile type weapons hit will also cause stun to trigger. Exception exists for non-projectile ranged weapons, (e.g. flamer, alien weapon, plasma cutter, welder) as these do not trigger the stun effect.

~~Non-damaging hits, (e.g. skillbooks and medals) will trigger stun.~~

I think some of these interactions are not intentional.

v0.15.13.0 
Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
