### ISSUE TITLE
(Stacked) Hulls draining differently on mirrored subs (PvP)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#7754]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Under some circumstances, when a hull is damaged on a mirrored sub, sometimes the water doesn't fully drain on the Separatist version. Repairing the hull with a welder or using `fixhulls` does nothing, only using `water `allows fully draining the hull(s)

**Steps To Reproduce**
1. [Download these submarines (including shuttle at the front)](https://github.com/Regalis11/Barotrauma/files/7706303/PvPBuoyancybug.zip)
2. Start a PvP game with the Doma Prototype
3. Hop in the Seabike shuttle at the front as separatist
4. Ram the seabike into a wall, and repair it
5. The seabike cannot go up unless the main hull is fully drained by using `water`
6. Repeat the process but on the Coalition seabike; it works just fine

![image](https://user-images.githubusercontent.com/73229309/145873408-e6e22a13-b2f2-4700-89c8-2e95a2200eb3.png)

The miniature shuttles/seabikes work by stacking hulls in the same space, so there might be something going on with stacked hulls only, but there could also be a larger problem with Separatists working differently

**Comment by Regalis11** [comment]
This seems to happen as a result of the duplicate hulls: items can only be inside one hull at a time, and as a consequence the pump only empties one of the hulls. Leaks also only connect to one of the hulls, and if it happens to be a different one than what the pump got connected to, the space at the bottom will never be emptied. I'm not sure why it behaves differently in a mirrored sub though, so I'll still need to do some more debugging.
