### ISSUE TITLE
Docked Station: Buying ship then retrying, doesn't reset ship/currency

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7759]
**Description**
Bought the 20k military ship at an Outpost.

Messing around, had a crew die.

Retried mission, and ship is still purchased. Everything else has reset. 

**Steps To Reproduce**
I'm assuming just go to an outpost, purchase a ship without switching, go back to your ship, mess around a bit, then kill a crew, then retry.

Seed
3.1415926
Resolution
2560x1080
Version
Steam Current Windows

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this. I'm not sure if I understood the steps correctly though: did your entire crew die, forcing you to click "load game" in the end-of-round summary screen, or did you retry by exiting through the pause menu and reloading the save? Did this happen in single player or multiplayer?

**Comment by Dopamin3** [comment]
It's on stream I'll link it.

It's exactly as I described.
