### ISSUE TITLE
REALLY weird wiring issue, 1 wire replaced another to separate relay

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7767]
I saw a bunch of bugs related to electric but this one seems different, and it may be related to the weird wire thing and how they aren't able to be pulled off the panels. 

I noticed if i go back and forth to each end and tug, sometimes they will come into hotbar.

This one in particular, will not, and it just so happens another wire replaced itself as it?

I am not sure but i have video footage of where I go to wire the new relay (because this particular circuit only worked perfectly for a few min then has become erratic) and it instantly snaps to the terminal, then the other wire like.. comes loose? but is stuck there? and I can't access the first wire anymore. It has completely destroyed the circuit and i'll have to rewire it all.

Video footage can be found here: 
https://www.twitch.tv/videos/1233165682
10:40:00
Sorry like 10:40:30~ to be more exact. *edit*
^^^ The first time it happens, you see me snapping a wire from the one NOT gate and then you'll notice a DIAGONAL WIRE appears out of nowhere, ran all the way from the top floor Relay by the command panel thing. So something was addressed wrong in memory or something, and overwrite the space for the other terminal? or something? I have no idea.

After that wire glitches like that, I go upstairs, and try to pull it off, and it's the same bug as i encountered and reported previously, wire is stuck/glitched onto the panel and will not remove.

It goes on and you can see me fucking with it up until this bug report.

This is the Circuit 11:04:30.
Please let me know if there's a way of doing this that works since I just want my extra ballast conversion room to work for this campaign run :D :D :D :D :D :D

**Comment by Dopamin3** [comment]
Not sure if related but the pump on that circuit is now running by itself with no inputs. I had a data wire from the command panel but lifted it, still is occasionally pumping things out of the bilge in that diving room. It's in the stream. Idk what the hell is going on here. would love any assistance lol

**Comment by Regalis11** [comment]
I'm not entirely sure I understand what the problem is here. To me the behavior in the video, aside from [the irremovable wires](https://github.com/Regalis11/Barotrauma/issues/7486), seems normal: you connect the disconnected wire from the relay to the not component, and it runs the diagonal wire from that relay to the not component.
