### ISSUE TITLE
Steel Cabinet sparking as if it isn't wired properly xD

### ISSUE THREAD

**Issue by Dopamin3** [Regalis11/Barotrauma#7768]
hahahahahaha

Same stream
12:18:32

**Comment by Regalis11** [comment]
No known steps to repro: I suspect this was caused by a disconnected wire behind the cabinet though.

**Comment by Dopamin3** [comment]
Nope! All part of the same set of fucked up bugs and bullshit in the 15
hour video I have repeatedly fucking linked that you haven't even skimmed
apparently.

I removed the video, you guys are hopeless. Absolutely not even sure I'm
talking to a real programmer haha

**Comment by Dopamin3** [comment]
I think you might actually be full-on retarded if you can fucking watch
that God damn mess of horrendous broken shit you call a functioning game
and close a single fucking thing I posted about it.

**Comment by Dopamin3** [comment]
It's so fucking buggy and broken it's hilarious and obvious you are a
fucking troll lol

**Comment by Dopamin3** [comment]
The fucking entire game broke itself to the point where cabinets are
randomly fucking sparking dude what world do you live in?

THE REPRODUCTION STEPS ARE THE FUCKING 15 HOUR VIDEO
