### ISSUE TITLE
[0.15.21.0] Bots - [Once Upon A Time In Europa] does not give Weapons Skill when Helm levels up

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7769]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[Once Upon A Time In Europa] does not give Weapons Skill when Helm levels up for Bots.

![Capture](https://user-images.githubusercontent.com/5086682/146101698-be307220-5999-4d48-902f-1ba320a177b3.PNG)

**Version**
0.15.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/19eae8d38ea88a82c2f2ad69ec7feba049b9dac0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
