### ISSUE TITLE
Campaign Map comes up and blocks usage of stations

### ISSUE THREAD

**Issue by jimkingiii** [Regalis11/Barotrauma#7771]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When we dock at a station, the campaign map immediately comes up and cannot be closed by any means we can find. Thus it is impossible to move around the stations, take missions etc; we can only choose new destinations and immediately depart-- though without the ability to take missions this stalls the campaign.

This occurred in multiplayer without an apparent cause, and has "stuck" to us as we moved. Rarely, we were given 2-3 minutes of time to move freely/normally which allowed us to continue playing (we were blaming each other for "undocking" before we diagnosed it as a bug)

**Steps To Reproduce**
I don't know how to start the bug, but it's immediately apparent upon docking with a station. The problem persisted even when we transferred the save file from the host to another player to host, through restarting the server, restarting the game, etc etc.

**Version**
0.15.13.0 hotfix
Windows 10
No mods installed.

**Additional information**

We will be restarting the campaign fresh, if it occurs again I will try to follow up.
I have attached our save file, since the problem has been shown to persist. The character data file is also attached.

I had to change the file extensions from .save and .xml to .txt so that github would allow me to attach them :P

[erk-civ-tav-blag.txt](https://github.com/Regalis11/Barotrauma/files/7716185/erk-civ-tav-blag.txt
[erk-civ-tav-blag_CharacterData.txt](https://github.com/Regalis11/Barotrauma/files/7716193/erk-civ-tav-blag_CharacterData.txt)

**Comment by Regalis11** [comment]
It seems that the circuit controlling the docking port has been tampered with, making the docking port immediately undock from anything it's docked to. Even though this isn't technically a bug, it definitely looks like one and can be very hard to diagnose and fix, so I created a ticket about addressing the problem: https://github.com/Regalis11/Barotrauma/issues/7772
