### ISSUE TITLE
Prevent docking ports from automatically undocking from the outpost

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#7772]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It's possible to rewire the docking ports in a way that makes the sub undock immediately from outposts, forcing the player to the map screen at the start of an outpost round. This can seem like a bug, and it's often hard to fix especially if the players aren't aware someone's tampered with the docking circuits.

One example case here: https://github.com/Regalis11/Barotrauma/issues/7771

Some possible ways to address this:
- Prevent rewiring the docking port and the circuits that control it (might not be the best way to go, since it'd prevent making useful changes to the docking circuit too).
- Show a prompt that asks the player whether they want to undock when this happens.
- Show a warning that tells the player the docking port has been wired this way to make the problem easier to diagnose.

**Steps To Reproduce**
Wire a memory component that sends out "0" to the "set_state" input of the docking port, dock with an outpost.

**Version**
Any

**Comment by Regalis11** [comment]
Note: this can also be done the other way around (forcing the sub to dock to the outpost).

By sending a constant signal to the docking port's toggle input and by rewiring the ballast pumps in a way that forces them to stay empty, you can completely soft-lock the campaign.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/tree/feature/autodocking-fix

Now when a signal that wasn't sent by a player (e.g. originated from some automated circuit instead of a button pressed by a player) tries to undock the sub from an outpost, or make it dock with an outpost, the players are asked whether they want to dock or not (host, a player with ManageMap permission, or anyone if no-one has permissions).

**Comment by Regalis11** [comment]
Could not find a way to reproduce the issue exactly, but I did find some issues that are probably related:
https://github.com/Regalis11/Barotrauma-development/commit/6c413b10f3a499332e48f708cbfcef2cfc899280

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
