### ISSUE TITLE
Having multiple bots doing the same tasks causes misleading messages

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7774]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have multiple bots fixing leaks, repairing or refilling oxygen tanks and they compete for the same targets the AI feedback gets misleading, because once the first bot that reaches the leak/device/oxygen tank does their task the other bots who tried to do the same will mention in chat that they can't reach that specific target, which for the player feels like that there's some type of an AI issue as to why they can't reach it. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/12446ee6-c9e0-4e42-8d4d-d18ab0059300)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/10b2e5b5-b29f-426b-8801-122f7b016321)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4bab2c8a-b09c-4fd7-b992-e73f3a998dc7)

**Steps To Reproduce**
Have multiple bots doing the same task and wait until devices deteriorate or there's a leak. 

**Version**
0.15.21.0

**Comment by ekqvist** [comment]
Fixed the issue with the Fix Leaks order in Regalis11/Barotrauma-development@fb88ecb

Couldn't reproduce the issue with the Repair Devices order

**Comment by Kaillera** [comment]
> Fixed the issue with the Fix Leaks order in [Regalis11/Barotrauma-development@fb88ecb](https://github.com/Regalis11/Barotrauma-development/commit/fb88ecb)
> 
> Couldn't reproduce the issue with the Repair Devices order

It actually does happen as well for when someone repair devices before them

**Comment by ekqvist** [comment]
Okay, in that case I'll try to reproduce it again

**Comment by ekqvist** [comment]
Still unable to reproduce the issue with repairing devices. Here's how I tried to do it:

1. Start a game with Dugong
2. Give the Repair Devices order to multiple characters
3. Use the `subeditor` command
4. Set the condition of all items in the junction compartment to 20
5. Use the `game` command
6. Watch the bots repair the devices with no expected comments about not being able to reach a target

**Comment by ekqvist** [comment]
Issue with the Load Items order should be fixed in Regalis11/Barotrauma-development@2537d17

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
