### ISSUE TITLE
PUCS Suit Loses Radiation Protection when Oxygen Tank Runs Out

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7779]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This might be the same as #7196, but this one is tank dependent. When the oxygen tank runs out in pucs suit you start to take damage. If you swap tanks you are protected again. This was on a ship with a lot of volatile fuel rods, and also in a cloud of jovian radiation.

**Steps To Reproduce**
Go near a strong radiation source like volatile fulgarium fuel rods while wearing a pucs suit. Put an empty oxygen tank in the suit. Notice that you start to take radiation damage. Swap to a full tank and the damage stops.

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
This was in multiplayer on the berillia.

**Comment by Regalis11** [comment]
I think this was probably caused by  the Jovian Radiation, [which bypassed PUCS's radiation protection completely](https://github.com/Regalis11/Barotrauma/issues/7196). I could no longer reproduce the problem in the latest version that was just released (v0.15.21.0).
