### ISSUE TITLE
Railgun Still Goes Through Ruins- Bug

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#778]
Simply the railgun still does go through walls of ruins, both base of railgun and it's tube.

**Comment by Regalis11** [comment]
The barrel goes through everything atm (should add a collider to that one too though), but the base seems to be colliding with ruins as it should. If you have any more info on how to reproduce the bug it'd be very helpful!

![dsfghdhrth](https://user-images.githubusercontent.com/14351070/45268342-73201d00-b483-11e8-9f91-c6b641d3b161.png)
