### ISSUE TITLE
Pirate Sub Wiring Locked

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#7781]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes the wiring on pirate subs is locked. This means I cant unwire the guns to render a safe path to the ship, and I cant unwire the reactor or oxygen to force the pirates to come deal with it. This is one of the most fun things about pirates so I was pretty bummed out. This makes them much harder to board.

Please put some kind of exception into the code so pirates can always be unwired.

**Steps To Reproduce**
Ive seen this twice and im not sure what causes it. Both were in multiplayer

The first time the wires just said "locked" and were grayed out. I think the server host had wiring disabled on his own ship, but it also disabled the pirates wiring. As I don't think the host would deliberately protect the enemy I would call this a bug.

The second time the wiring did not say locked, I just couldn't pull the wires out. I couldn't even disconnect them. 

**Version**
v0.15.13.0 Windows 10 x64

**Additional information**
I don't use any mods or play on modded servers so this was pure vanilla.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/37869f9dfe6ad1e115ed9d1b56ac1e8d317b6e88

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
