### ISSUE TITLE
GameAnalytics consent window doesn't fit on the screen on small resolutions

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#7782]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The GameAnalytics consent window goes outside the bounds of the window on small resolutions and/or when UI scale has been increased, making it impossible to click the yes/no buttons and dismiss the prompt.

**Version**
v0.15.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bbcb55ee1858007cbe0da3b83ff25c19467c2f05

**Comment by Rokvach** [comment]
Going to the smallest resolution possible causes a text overflow at the top

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/915c0cf0-6bc3-481d-bd85-3e15ce8cc6bb)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d683fe523ef14e23ee0aa38819aaebcf824a32a7

**Comment by Rokvach** [comment]
Tested, I wasn't able to break it anymore no matter what I did, working correctly. Closing.
