### ISSUE TITLE
Monsterevent Delay Feature Request

### ISSUE THREAD

**Issue by MasonMachineGun** [Regalis11/Barotrauma#7784]
**Description**
Using the delay tag for monsterevents in randomevents.xml does not have access to the Delay functionality. 

**Steps To Reproduce**
Here is an example of some code that is nonfunctional:       <MonsterEvent characterfile="Watcher" minamount="1" maxamount="1" spawntype="abyss" delay="20"/>, this code will not add a 20 second delay to once the submarine enters the abyss to spawn the watcher.

**Version**
v0.15.21.0 Windows

**Additional information**
This functionality would allow events to be able to spawn large amounts of enemies but not "all at once", giving creators the ability to create lag free large points of engagement. This could also allow the event to "foreshadow" another incoming event even in a large set of possible events.

**Comment by Regalis11** [comment]
To my knowledge, there's never been a delay parameter for the monster events. Did it work in some previous version?

**Comment by Ek-Videogames** [comment]
> To my knowledge, there's never been a delay parameter for the monster events. Did it work in some previous version?

`mindistancetraveled` and `minmissiontime` I believe are the ones he's referring to. 

Previous there was a situation that was very-much the opposite, #3447 - in which delay events were the only ones working, with distance events were being ignored entirely.

**Comment by Regalis11** [comment]
I couldn't find any problems with `minmissiontime`. If the ticket is about that attribute, I think @MasonMachineGun may have misunderstood how it works: it won't delay the spawn after the sub enters the abyss, it only prevents the spawn from happening during the first x seconds of the round.

**Comment by MasonMachineGun** [comment]
I'm not marking this as a bug, but more of a feature request. Minmissiontime or whatever it is DOES WORK as intended with the intensity system in mind.  I'm referring to adding a feature to where when an eventset triggers, I would think the ability to add a delay to the monsterevents within.  This would allow large events such as mudraptor packs or hammerhead groups to not generate lag as there would be time between each creature spawning. This could apply for almost all situations where multiple enemies or swarms spawn in to antagonize the players.

**Comment by MasonMachineGun** [comment]
I changed the title of this card to better reflect my intentions. I'm seeking to improve large difficulty mods such as my own called BaroTraumatic by reducing lag for not only the base game, but adding a simple feature that could improve entity spawning performance in almost any situation.

**Comment by Regalis11** [comment]
Ah, I see! We generally only use the issue tracker for bug reports, and feature requests should go in the [Discussions](url), but I went ahead and implemented this in https://github.com/Regalis11/Barotrauma-development/commit/c7713c0cd901337748f120f6f724e955780a2777 since it was such a quick thing to add.

**Comment by MasonMachineGun** [comment]
Someone told me there was a way to delay monster events aside from the minmissiontime, that's why I posted this as a bug originally. I suppose they were wrong. Either way, this is great. Thanks.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
