### ISSUE TITLE
Website linux download doesn't have the server exe

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#779]
The linux download from [here](https://undertowgames.com/barotrauma/) doesn't have the BarotraumaServer.exe. 

Plz fix.

**Comment by Regalis11** [comment]
Fixed

**Comment by BlueTheKing** [comment]
Though it does include the BarotraumaServer.exe now, the vanilla download crashes on start. 

Since the FarseerPhysics.dll is missing by default, it will keep crashing, by grabbing the dll from the 0.8.1.12 download i was able to fix it and make it run properly.

Plz fix?
