### ISSUE TITLE
Deconstructor not giving materials

### ISSUE THREAD

**Issue by ColeThunder** [Regalis11/Barotrauma#7793]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
deconstructor destroy items but does not give components or materials

**Steps To Reproduce**
deconstruct item with apo chainsaw mod and dead space gear mod installed, did not have issue before current update

**Version**
the current version on windows 10.

**Additional information**

**Comment by Regalis11** [comment]
I unfortunatel couldn't reproduce this. I'm also suspecting the items might've gone to a linked cabinet (or maybe a container in the deconstructor's output slots?). Did it only happen with some specific item(s) or with anything you tried to deconstruct?

**Comment by WickedWolfy** [comment]
Have successfully verified items going to linked containers on deconstruct 12/17/2021 Windows v 0.15.22.1

Steps to reproduce:
- Empty linked container,
- Deconstruct item
- Notice new stack created
OR
- Watch linked container
- Have Player 2 in Online mission deconstruct item
- Notice stack increments

**Comment by ColeThunder** [comment]
Yeah it was linked to a container, thank you though

**Comment by Regalis11** [comment]
No known steps to repro, closing
