### ISSUE TITLE
Kastrull drone undocks and goes through the main sub at the start of a multiplayer round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7798]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Kastrull drone is positioned inside or sometimes above the main sub at the start of a multiplayer round

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/86108378-34bc-4115-b80c-4e4f71e5455a)

**Steps To Reproduce**
Host a server, select Kastrull and start a single mission round

**Version**
Stable 0.15.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/70b68e159e24cd50afd1426ea95cfb2a96764cb6

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue anymore. Working correctly. Closing.
