### ISSUE TITLE
Launcher auto update clears bannedplayers.txt

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#78]
As stated above, I heard reports that this occurs periodically / every update just, so I went to check it with a copy of 0.6.1.4

the bannedplayers.txt file is replaced by the auto updater in the launcher which should not be the case as it clears a hosts permament and temporary bans which should be up to the host.

Picture of issue:
http://puu.sh/yzyy6/f94cf24fc2.jpg

**Comment by Regalis11** [comment]
Fixed by removing bannedplayers.txt from the master server file list.
