### ISSUE TITLE
Sometimes when passing through cave bushes, the slowness doesn't disappear when you're out of it

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7800]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes when passing through cave bushes, the slowness doesn't disappear when you're out of it.

**Steps To Reproduce**
I'm not sure how to reproduce it reliably in regular gameplay other than just scootering through them in and out in very specific ways that even I don't know of. However, if you teleport in and out of those bushes, you will get the same effect.

**Version**
~0.15.21.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3895398ffec9197dabc553f54b91acb645878d71

**Comment by Rokvach** [comment]
Tested,  working correctly. Closing.
