### ISSUE TITLE
Sub editor - Links for Add submarine (connection sequence is important for disconnection)

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7808]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**If the `added submarine` is `linked` to the `docking port`:**
When you try `unlinked` the `docking port` from the `added submarine` a secondary link takes place! Connection sequence is important for disconnection!

Steel Cabinet, Fabricator, Deconstructor, Oxygen Generator, Vent etc - working normally! Linked sequence is not important for unlinked!

**Steps To Reproduce**
https://user-images.githubusercontent.com/93348499/146416971-4db7d7e3-cf1c-413e-ab0c-bbafa09eb99c.mp4

**Version**
v0.15.21.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67ab4faed5b031116940ad1d92f3f251e9e9d87d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
