### ISSUE TITLE
Give a Very Short Topwall to The Left of Docking Hatches of Default Submarines to Make Docking Easier- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#781]
A short topwall close on the left outside submarine from docking hatch prevents shuttle while docking by itself from sliding further into left, so shuttle will stop at the point it has to dock. Docking without a topwall like it is already difficult.

**Comment by Regalis11** [comment]
Copypasting the comment from #784:

I agree that docking needs to be made easier, but I think there are better ways to do it than this or #781, which only help in some specific cases with specific shapes of shuttles and submarines. One option we've been thinking of is adding a separate "docking mode" to the nav terminals which would give you a more fine-grained control over the sub, show precisely where the ports are and possibly even automatically help you with aligning the ports.
