### ISSUE TITLE
Periscope and broken hardware issue with "position_out" connection 

### ISSUE THREAD

**Issue by cccpvs** [Regalis11/Barotrauma#7812]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the weapon of the submarine has the "Repair" property, then when connected to the periscope, the interface of the removed item and the "Repair" window are displayed. This is what appears when the wire is connected to the **"position_out"** connector.

**Steps To Reproduce**
null

**Version**
0.15.22.1 (Windows)

**Additional information**

The weapon is completely broken. We are doing repairs so that the periscope starts working.
![](http://barotrauma.dayz-vologda.ru/images/Issue_bug_periscope_v0.15.22.0_1.png)
Using the periscope
![](http://barotrauma.dayz-vologda.ru/images/Issue_bug_periscope_v0.15.22.0_2.png)
When activated, there is also a weapon repair window
![](http://barotrauma.dayz-vologda.ru/images/Issue_bug_periscope_v0.15.22.0_3.png)

**Comment by iridescent-lightning** [comment]
Yesterday I came across the same issue with my mod. I was so frustrated.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a63e75c1a0ecaf31e6b884cab71649fbcc9dabc2

**Comment by Rokvach** [comment]
This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.
