### ISSUE TITLE
Barotrauma/workshop folder huge folder size

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7815]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the /workshop/ folder in my baro is 457mb large and contains 1.4k items, presumably all workshop preview images. this is a rather large folder of nothing important.

![image](https://user-images.githubusercontent.com/5103517/146489488-1f41c64e-56af-456d-af7e-e38f9ef2eebd.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.22.1

**Additional information**

**Comment by Regalis11** [comment]
I think we could address this by only keeping something like 20 latest preview images in the folder

**Comment by Tsunder** [comment]
opening the workshop tab to update one of my mods yielded this as loot. I didn't even scroll down the popular mods list!

![image](https://user-images.githubusercontent.com/5103517/146587846-55c17929-04be-439d-827c-4d530d63c936.png)


perhaps related to  #5571 ?

**Comment by Tsunder** [comment]
partly affected by baro generating images in png and large images being used over jpg + smaller images. but also workshop allowing up to 1mb images. the images could be like 10kb jpgs with no discernable difference probably

in game the images are what, 256px? 

at any rate, modding-refactor

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dc196e5bf7fe1cd57e9caf9a14d32b73ca5c0b33

**Comment by Rokvach** [comment]
Not an issue anymore, working correctly, closing.
