### ISSUE TITLE
Dead crew carrying over to re-load

### ISSUE THREAD

**Issue by gabepombo1** [Regalis11/Barotrauma#7821]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

My crew died and then, when I reloaded the save, the crew was still dead. If I did not have backups of my saves, my game would be completely screwed. This is game-breaking/completely unplayable. 

My friend also sees fire animations while there is nothing going on.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

Have your crew die and then reload a save in the multiplayer main campaign.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

The Holiday update. Windows 10.

**Additional information**

**Comment by Regalis11** [comment]
Even though this report was done before https://github.com/regalis11/barotrauma/issues/7939, I'll close this one since the latter has more info on the issue
