### ISSUE TITLE
Dedicated Server: Lobby freezed after round is finished

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#7823]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After round is finished (multiplayer missions) the lobby is "jammed": no text message can be sent (after typing and sending it doesn't appear in the chat window), voice chat lags up to no sound at all, selecting of submarine or other server settings doesn't work (I can do it on my client but after I close the settings window server doesn't change the settings), if I type a command in F3 command line nothing happens. It can be fixed by restarting the server.

There is a chance that this jamming will not happen after a mission or two, but we have it in 100% cases after couple of hours. we have tested it with three different dedicated servers (hosted by different providers). 

I do not have enough statistics (2 or 3 reports from moderators) but it looks like if a new mission can be started (by pressing start button many times) from this jammed lobby and immediately finished by pressing round finish button the lobby is not jammed anymore until the next round is ended.

**Steps To Reproduce**
Run a dedicated server with some amount of players in missions mode. Jamming will happen in 1-5 hours.

**Version**
0.15.20
0.15.21
0.15.22.1
Windows hosted dedicated server, no mods

**Additional information**
There is no problem with chat or voice during rounds, only in lobby after round ends.

**Comment by Hegny** [comment]
Some players report that if they reconnect to the server lobby jamming disappears for them.

**Comment by Hegny** [comment]
I have solved the problem.
It was caused by serverPeer.Send() using DeliveryMethod.Reliable for long messages in ClientWriteLobby function (ServerSource\Networking\GameServer.cs)

replacing the string
if (isInitialUpdate || messageTooLarge)
by

**Comment by Hegny** [comment]
I completely agree with motivation to use reliable delivery method.

However, so far we have it running 24/7 for one month with three servers of [RU/RP] Команда Ноль and never had any issues in Lobby.

Anyway I will try to change this part of code back to get a logfile as you have described here.

**Comment by Regalis11** [comment]
This seems to have been remedied by https://github.com/Regalis11/Barotrauma-development/pull/3020 (server can now sync individual NetProperties selectively) - it's not much more difficult to get the messages to go over the MTU.

That change isn't available in the public version yet, but we'll keep an eye out for this issue and the previously mentioned warnings during unstable testing.

**Comment by Rokvach** [comment]
There hasn't been any reports of this happening in the Unstable, seems to be working correctly. Closing.

**Comment by Hegny** [comment]
> This seems to have been remedied by https://github.com/Regalis11/Barotrauma-development/pull/3020 (server can now sync individual NetProperties selectively) - it's not much more difficult to get the messages to go over the MTU.
> 
> That change isn't available in the public version yet, but we'll keep an eye out for this issue and the previously mentioned warnings during unstable testing.

The same issue in 16.6.1. 
Solved the same way.
