### ISSUE TITLE
The submarine’s weapon is disappeared (In an attempt to rearrange the submarine’s weapons)

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7825]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Maybe I don’t understand something or it’s not a mistake but nevertheless...

**Description**
In an attempt to rearrange the `submarine’s weapons` (move from `Turret Hardpoint 1` to `Turret Hardpoint 2`), all the weapons disappeared. The sub weapons money didn’t come back.

**Steps To Reproduce**

- Dock with the outpost
- Take the `weapons` off the `Turret Hardpoint`
- Turret Hardpoint (Pending)
- Pending? Weapon removed but not available in other `Turret Hardpoint` list!
- I decided maybe I should undock and dock back again... )))
- Ок.
- As a result - The submarine’s weapon is missing! The sub weapons money didn’t come!
How do you rearrange a submarine’s weapon?

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
This is actually the intended behavior: uninstalling a weapon doesn't give you a refund, nor can the uninstalled weapon be installed on another hardpoint for free. You can however install the weapon back free of charge (essentially cancel the uninstallation). So in a sense, you can buy weapons for a hardpoint, and swap between those weapons for free, but there's no way to sell weapons.
