### ISSUE TITLE
Selection logic of railgun loader has been changed

### ISSUE THREAD

**Issue by Charile1890** [Regalis11/Barotrauma#7826]
- [v] I have searched the issue tracker to check if the issue has already been reported.

**Description**
(please refer to my post image)
Before the latest update , if I link railgun to loader in order from 1~3
I can fire it in B mode instead of A mode, that is, always use first loaders unless it is empty.
This design is useful to manage the high value (and dangerous) shell such as nuclear shell or shell including C-4.
I can maintain 1st loader empty , fire 2nd loader with full of normal shell until I dicide to use nuclear shell , than call my crewmate to load it into 1st loader (or do it by myself when single-play).
But it is failed after the latest update (now can only fire in A mode).

I think these two fire option should can be choiced by the player.
  
**Steps To Reproduce**
Link multiple loaders to a railgun.

**Version**
![text](https://user-images.githubusercontent.com/96295564/146544889-0493ea53-d859-42b4-8489-d8a49b527ae0.png)

**Comment by Regalis11** [comment]
This was implemented as an intentional fix to https://github.com/Regalis11/Barotrauma/issues/7324

**Comment by Charile1890** [comment]
So......should I take this post to the Discussions Tab ?

**Comment by Ek-Videogames** [comment]
It feels like this needs a function to be able to differentiate between `<OnUse>` ( Magazine-based ammo ) 
and `<Projectile>` (Individually loaded rounds)

- Also I note that this fix works for multiple discrete loader items, but a modded loader that say - can hold 2 boxes of coilgun ammo in 1 inventory - the turret will still deplete the `<OnUse>` effect on both.
