### ISSUE TITLE
Interacting with a beacon's reactor with the hazardous materials talent will spawn alien materials on the floor.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#7828]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Getting the "Hazardous materials" talent and then attempting to power up a beacon's reactor will cause it to spawn alien materials, despite it not being a wreck.

**Steps To Reproduce**
1. Get the hazardous materials talent
2. Find a beacon
3. Interact with the beacon's reactor
4. Look on the floor

**Version**
Windows, V0.15.22.1

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7762
