### ISSUE TITLE
Having a high enough electrical skill will allow a reactor to generate power without fuel.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#7829]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Having a high enough electrical skill (I found this bug with 2k skill) will bring the low heat bar thing so low that it goes below 0, allowing a reactor to function with 0 heat, and therefore 0 fuel rods.

**Steps To Reproduce**
1. Set electrical skill to 2k
2. Press the power button on a reactor
3. Turn up the turbine rate

**Version**
Windows, V0.15.22.1

**Additional information**
Can be achieved using the assistant's olympian talent and only generates tiny amounts of power, but I am still 100% certain this is NOT an intended feature.

**Comment by Regalis11** [comment]
Is there a way to get the electrical skill that high without the use of console commands? If not, I'd say this is a pretty low-prio issue: most skills start having weird side-effects if you go that high.

**Comment by WrillWasTaken** [comment]
> Is there a way to get the electrical skill that high without the use of console commands? If not, I'd say this is a pretty low-prio issue: most skills start having weird side-effects if you go that high.

Yes, you can purchase books later into campaigns I believe.

**Comment by Regalis11** [comment]
As of yesterday's update, there is a hard limit of 500 to the skills you can gain through talents, so 2000 should not be possible. In any case, addressed this in https://github.com/Regalis11/Barotrauma-development/commit/8e60435516bdd22db0657663e7c5d48d6e333abf

**Comment by WrillWasTaken** [comment]
Alright.

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we generally keep the tickets open until we've tested and verified the fix is working. :)

**Comment by WrillWasTaken** [comment]
I just finished testing it, the fix is working and I cannot gain medical skill past 500.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
