### ISSUE TITLE
Crawlers will target corpses inside submarines

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7830]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
From what I have experienced, crawlers will target corpses inside submarines even if they cant see them. I was playing and had a mudraptor corpse inside my submarine (the orca 2), and a group of 6 crawlers all breached the sub in the exact same place and all went and swarmed the body. Even though there was multiple doors and walls in the way, they specifically were targeting the mudraptor.

**Steps To Reproduce**
1) have some corpse inside your sub, unsure if using different sub makes any difference. 
2) spawn some crawlers outside your sub or locate a group of them
3) watch what they do

**Version**
Latest Version: v0.15.21.0

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@ab046c4 (monster-variants).

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
