### ISSUE TITLE
Hammerhead spawning inside alien ruin

### ISSUE THREAD

**Issue by StruggleDuck** [Regalis11/Barotrauma#7838]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hammerhead spawned inside of a ruin

**Version**
Latest version

**Additional information**
Save file: https://drive.google.com/file/d/1WFXdF5kMdYiBSzNZpL1JLdvJiUI-GimK/view?usp=drivesdk

Image of sonar:
![unknown](https://user-images.githubusercontent.com/92034548/146587792-50da2fda-0903-4323-b572-ba0a7ae32292.png)

**Comment by StruggleDuck** [comment]
Sub link: https://drive.google.com/file/d/1WJJIA5-jJFXzwLtFJw8Zbk46Lf2ZImgF/view?usp=drivesdk

**Comment by gerakis** [comment]
I saw this last night also. Confirming the bug exists.

**Comment by Regalis11** [comment]
I unfortunately wasn't able to reproduce this. In the provided save, the hammerhead seems to spawn on the main path. I wonder if it could be that the hammerhead swam up to the ruin? Are you sure it was actually inside the ruins? Looking at the picture, it looks more like it was above the ruin, not inside it, somewhere around this spot:
![image](https://user-images.githubusercontent.com/14351070/148085966-c3259dd3-8653-41f9-a900-84457fa3aaba.png)

**Comment by Regalis11** [comment]
No known steps to repro, closing
