### ISSUE TITLE
Give Ladders a Collider For Structural Objects- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#784]
This does not include hatches or duct blocks regardless if they are closed or opened.

2 different ladders can collide with each other.

Two reasons for all of it:

1. How can a ladder of a shuttle go through a topwall while docking?

2. Makes docking even easier, than what I drew in https://github.com/Regalis11/Barotrauma/issues/781. Normally barely anyone can dock with respawn shuttle without https://github.com/Regalis11/Barotrauma/issues/781 or this thread. People sometimes even open shuttle's hatch, before docking occurs, because they think it's fine at the moment to go outside.

**Comment by Regalis11** [comment]
1. One could also ask how a ladder can go through a closed hatch or duct block.
2. I agree that docking needs to be made easier, but I think there are better ways to do it than this or #781, which only help in some specific cases with specific shapes of shuttles and submarines. One option we've been thinking of is adding a separate "docking mode" to the nav terminals which would give you a more fine-grained control over the sub, show precisely where the ports are and possibly even automatically help you with aligning the ports.
