### ISSUE TITLE
Crush depth is 0 meters on a newly purchased sub

### ISSUE THREAD

**Issue by ServenAlive** [Regalis11/Barotrauma#7842]
I bought new sub and switched to it, and then i saw it. Playing on windows 10 game version is 0.15.22.1
![20211218005622_1](https://user-images.githubusercontent.com/93344591/146613015-b3e145cc-afc8-4e93-a188-68b1dfe030dd.jpg)

**Comment by MaaiG** [comment]
Cool, the bots sold a leaky bucket...

**Comment by Regalis11** [comment]
Which submarine did you switch to? Was it a vanilla submarine, or a custom one?

**Comment by ServenAlive** [comment]
> Which submarine did you switch to? Was it a vanilla submarine, or a custom one?
I used custom submarine called "Brusilov" 
https://steamcommunity.com/sharedfiles/filedetails/?id=2383080722
And switched from "Tarbatagai"
https://steamcommunity.com/sharedfiles/filedetails/?id=2286292591

**Comment by Regalis11** [comment]
Thank you for the extra info! I gave these subs a test but unfortunately couldn't get the issue to appear though, so I guess it requires some more specific circumstances to occur. :/
