### ISSUE TITLE
XOR gate is ON when Input A and Input B are ON

### ISSUE THREAD

**Issue by WickedWolfy** [Regalis11/Barotrauma#7844]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
XOR gate is ON when both inputs are ON

0 XOR 0 is 0 - ok
0 XOR 1 is 1 - ok
1 XOR 0 is 1 - ok
**1 XOR 1 is 1** - not ok -> Should be 0

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/621696/146626475-bbd191d9-9251-4c73-bfd6-c21911bba3ed.png)

I've made a simple circuit using the SuperCapacitor.
SC's `Charge %` is output, compared to `50` and `100` `Mem` values using `GreaterThan` gate.
When both value for 50% and 100% are 1/true, XOR returns 1/true.
Expected 0/false

**Version**
PC latest version - 0.15.22.1

**Additional information**
N/A

**Comment by MaaiG** [comment]
I checked. Still functional. v0.15.22.1
https://user-images.githubusercontent.com/93348499/146643056-4c8427ae-123e-4f5e-8cd0-5ac10900e544.mp4

Check this:
![Image 001_16-37 (1)](https://user-images.githubusercontent.com/93348499/146643091-578f238b-5b85-4e69-82bc-f108849961c2.png)
:

**Comment by WickedWolfy** [comment]
> I checked. Still functional IMHO (v0.15.22.1)

Confirming that setting the default `False` output to a value of `0` fixed the issue.
Modified original circuit and recreated XOR from scratch
![image](https://user-images.githubusercontent.com/621696/146646451-5dcc8819-d7b9-43b6-b717-bbf8f0c8817e.png)

I think it is reasonable to modify my ticket to a request to set default `False Output` to be a `0` instead of blank...
But I will leave it up to developers to make that decision.

Per original issue opened - This is resolved.
