### ISSUE TITLE
Bots - Still injecting multiple cures for very light damage that can be cured with one dose

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7846]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots are still injecting multiple cures for very light damage that can be cured with one dose.

**Steps To Reproduce**

**Version**
~0.15.22.1

**Comment by Regalis11** [comment]
I couldn't find a way to reproduce this. Tested by doing the following:
1. Put a bunch of morphine in the bot's inventory
2. Give myself a small amount (5) of internal damage to each limb
3. The bot only applies one dose of morphine

Also tested with burns, and by replacing the morphine with bandages, but the bot didn't use any excess items. Did you notice this happening with some specific afflictions or drugs?

**Comment by Kaillera** [comment]
In this case, the drugs used were oppiates. I see it happen every other time whenever I come back from EVA missions (caves, ruins, wrecks), even when I was only damages very slightly.

**Comment by Regalis11** [comment]
Did some more tests by giving the character the exact amount of damage (50) that can be healed with one dose of morphine and by giving the medic two medic's fatigues full of morphine (total of 48). Also tested giving the character an amount of damage (55) that can't entirely be healed with one dose, but close enough that the medic should ignore the leftover damage. Also repeated both of these tests with Reaper's Tax, in case the reduced vitality had something to do with the issue.

Still no dice, the medics still seem to only use one dose. :/

**Comment by Regalis11** [comment]
No known steps to repro, closing
