### ISSUE TITLE
[0.15.22.1] Character skill stats being reset on death permanently in multiplayer

### ISSUE THREAD

**Issue by Kollator** [Regalis11/Barotrauma#7848]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Upon character death stats of characters are reset to the starting base values. Getting rid of the Reaper's Tax does not fix the issue. Bonuses gained from talents are retained, but the base stats are irreversibly reset to base values. 

**Steps To Reproduce**
Character that has a higher than starting base skill stats gets killed (e.g. Helm is 30 as a base value and he/she has gained +15 in the course of several games == Helm value is 45 without bonuses included) -> The character respawns with the Reaper's Tax penalty and his/her stats are reset to base values (e.g. 1st points base value of 30) -> Even when curing the Reaper's Tax the value of the character's skill value is still reset to the base rather than base+gained skill levels.

**Version**
Client version: 0.15.22.1
Client OS: Windows
Revision: 898f64d2c0

**Additional information**
Just to cross reference another ticket which seems like the same problem, but with a different version without the hotfix: [https://github.com/Regalis11/Barotrauma/issues/7755]

Not really much else. Love you long time.
Stay healthy and Godspeed.

**Comment by zkxs** [comment]
![image](https://user-images.githubusercontent.com/1807509/146659634-3fdc5e6a-5fae-44b1-91a5-0e4f83c589b1.png)
![image](https://user-images.githubusercontent.com/1807509/146659636-5297f583-aacd-479d-8708-c9df0516f7b0.png)

I've got more evidence of this in Windows 0.15.22.

The screenshots are from the current save (so the moment we departed the station) and partway though the round after Ashton died and had his skills nuked.

**Comment by zkxs** [comment]
Possible related to #7755?

**Comment by Kollator** [comment]
> Possibly related to #7755?

Along the same lines, yes, but in the version before so the hotfix did not include mention of this one. This was also cross-referenced on the original post above.

**Comment by Regalis11** [comment]
This was actually an intentional change added in the Among the Ancients update: dying does reset your skills. The talent system makes it easier to gain skills and permanent improvements to the character, and resetting the skills was intended as a way to balance that out.

**Comment by Kollator** [comment]
> This was actually an intentional change added in the Among the Ancients update: dying does reset your skills. The talent system makes it easier to gain skills and permanent improvements to the character, and resetting the skills was intended as a way to balance that out.

Oh, now I see. 
Thank you for the clarification. What however was a bit confusing is that this did not actually come up into effect until the patches 0.15.22.0 and 0.15.22.1, even when we played at the launch of both, the Among the Ancients and Holiday updates.

Cheers mate!

**Comment by BaronPlatinum** [comment]
> This was actually an intentional change added in the Among the Ancients update: dying does reset your skills. The talent system makes it easier to gain skills and permanent improvements to the character, and resetting the skills was intended as a way to balance that out.

If that is the case, I wish that you would have communicated it more clearly, as the Among the Ancients update states:
" - **Characters lose some skill points when respawning mid-round**. The talent system makes it easier to gain skills and permanent improvements to the character, and this change is intended to balance that out. "
[Link to the steam page for the update's patchnotes](https://store.steampowered.com/news/app/602960/view/3020219432742726116)

Personally I don't think that loosing over half of my skill points counts as "some".
