### ISSUE TITLE
Makeshift Oxygen Tanks and Welding Fuel Tanks- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#785]
While crafting those tanks using a steel bar how can they still be labered with blue or brown lines informing about their content, if they do not use any crafting resource of those colours?

Make those custom tanks completely while.

**Comment by Regalis11** [comment]
You could extend this argument to basically any item the fabricators can make. If we went for 100% realism, almost none of the items would be possible to make from the couple of metal and plastic bars the fabricators require.
