### ISSUE TITLE
Crash with reloadcorepackage

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7850]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/7739961/crashreport.2.log)

**Steps To Reproduce**
reloadcorepackage at the main menu.

**Version**
0.15.22.1

**Comment by Rokvach** [comment]
This has been fixed with the modding refactor. Closing.
