### ISSUE TITLE
PUCS Still Draining Oxygen In Sub

### ISSUE THREAD

**Issue by ThemiusADP** [Regalis11/Barotrauma#7852]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The PUCS is still draining O2 while in an oxygenated environment like the sub or outpost

**Steps To Reproduce**
Put an oxygen tank into the PUCS. I used a normal and a masterwork one.

**Version**
Version 0.15.22.1. Using Windows 10

**Comment by MaaiG** [comment]
v0.15.22.1 - Only if the oxygen level in the compartment is below 50% (Test with sub editor).

**Comment by Regalis11** [comment]
I could not find a way to reproduce this

**Comment by Regalis11** [comment]
No known steps to repro, closing
