### ISSUE TITLE
Returning to server lobby after receiving purchased items deletes those items

### ISSUE THREAD

**Issue by ToyDragon** [Regalis11/Barotrauma#7853]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In a multiplayer campaign game, after having purchased items spawn in the ship, going to the Server Lobby and back doesn't respawn the purchased items.

**Steps To Reproduce**
1. Start a multiplayer campaign. One player is fine.
2. Buy some stuff at the starting outpost
3. Start a mission, notice stuff correctly spawns in cargo bay
4. Go to server lobby, hit continue to load back into the game
5. Notice stuff you purchased didn't spawn.

**Version**
0.15.22.1, windows 10, branch release, revision 898f64d2c0

**Additional information**
After purchasing items on the station, if you go to server lobby and continue you can get the purchased items to spawn while your still in the station. Another server lobby/continue cycle will lead to the original issue, where they don't spawn and your money is still gone.

**Comment by ToyDragon** [comment]
I tried reproducing this at the last commit and the issue isn't reproducible there.
https://github.com/Regalis11/Barotrauma/commit/617d9ede88b1ed42074c43c4e5f71826cfee50a5

**Comment by ToyDragon** [comment]
Issue with the parameters to an RPC changing in the server, but not being updated on the client. Fix in PR https://github.com/Regalis11/Barotrauma/pull/7855

**Comment by atlas-callisto** [comment]
I had this recently too, however we fully closed the lobby and relaunched it and luckily got our purchased supplies back.

**Comment by Qowyn** [comment]
The main issue is that starting the mission spawns all items that should be spawned, and then the CargoManager forgets about them. So the next time you start the items won't spawn, unless you exit the campaign and reload it. Same for missions lost after going to lobby, but this is worse, because if you managed to complete the missions, then go to lobby, and then go back into the campaign you will keep the XP and money gains without using up items.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/48f7d39e87dbbdc1085e33b94649fc3daf280d0b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
