### ISSUE TITLE
volcanos very laggy in multiplayer

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7854]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
when the volcano is actively blowing fire/lava into a ship, the performance of game drops greatly
kills FPS into like <20, and stuttery.

**Steps To Reproduce**
take a ship (flooded) onto volcano

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8401092404ed875a561371f8d5504f39e5e62830

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
