### ISSUE TITLE
Gene harvester talent does not work on some monsters

### ISSUE THREAD

**Issue by mxdmxdmxdmxd** [Regalis11/Barotrauma#7857]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Creatures that do not have default drops such as the threshers and spineling will never drop genetic material

**Steps To Reproduce**
Kill said creatures outside sub with related the talent and compare drop rate with creatures with default drops

**Version**
v0.15.21.0  (Windows).

**Additional information**
I have tested this in sub editor by spawning various creatures hundreds times with godmode and noticed this discrepancy.

Note this also seems to be the case for the Deep Sea Slayer talent.

If this is intended then rephrasing of said talent descriptions would be very much appreciated.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f22279a19851ac28a6fc02d9458c9b838b954643

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
