### ISSUE TITLE
Cannot change submarine in multiplayer campaign

### ISSUE THREAD

**Issue by dexteryip** [Regalis11/Barotrauma#7862]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bought new ship but cannot change into new one in multiplayer campaign mode.

**Steps To Reproduce**
Using sub "Humpback" and docked at a station "OSHAN" research outpost, voted and bought a new sub "Kastrull". Marks were paid. We selected "change later" or sth like that.
We tried to change submarine in the same outpost using Submarine Delivery Service. Both ships are shown at the terminal.
Vote button showed up but nothing happened after pressing. Other people also tried to change but still no use.

**Version**
Host and players are all on Windows. Latest steam version v0.15.22.1 

**Additional information**
no mod installed. all on vanilla

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/92d8fec3a8b5565b961561b24695e0d90a3b3c22 (see #7904)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
