### ISSUE TITLE
Values not shown correctly on supercapacitor on Traditional Chinese

### ISSUE THREAD

**Issue by dexteryip** [Regalis11/Barotrauma#7863]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Showing [CHARGE] and [PERCENTAGE] instead of value. see attached image

**Steps To Reproduce**
Open interface on supercapacitor.

**Version**
Latest steam version v0.15.22.1 on Windows

**Additional information**
![image](https://user-images.githubusercontent.com/42698631/146685115-493566ea-a53f-47aa-b974-fdd738d1da49.png)

**Comment by Regalis11** [comment]
Fixed this myself in the loca file [Regalis11/Barotrauma-development@cc0b4dd](https://github.com/Regalis11/Barotrauma-development/commit/4d1a93f5ec0086d3d6669df46b195c4f68a4c1ab), but let's wait until we get the next batch of localized text and make sure it's been fixed at their end in the master localization kit too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d89f5f475bef74ed36d9b45b26c53e928bd8a955

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
