### ISSUE TITLE
Ошибка в игре с переключением корабля!

### ISSUE THREAD

**Issue by Aleksandr-Kudriashov** [Regalis11/Barotrauma#7874]
Windows 10
Версия игры 0.15.22.1
При покупки нового корабля, не даете на него переключиться. Перезагрузка системы и перезагрузка игры не дало результатов.

**Comment by MaaiG** [comment]
Has already been: https://github.com/Regalis11/Barotrauma/issues/7862

**Comment by MaaiG** [comment]
Has already exist: https://github.com/Regalis11/Barotrauma/issues/7862

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/7862
