### ISSUE TITLE
Docking port - Invalid scale for "Dockingportlights" and Offset

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7875]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
**1. Invalid scale for Dockingportlights.png (Horizontally, vertically )** 
Now:
![Hatch-light](https://user-images.githubusercontent.com/93348499/146758752-2a237996-2a86-4501-ae54-7efd1114b685.gif)

Should be:
![Image 001_20-14](https://user-images.githubusercontent.com/93348499/146806272-b5f99c5a-f26d-423a-a251-f82bd3be7552.png)

**2. Offset**
![Image 001_14-07](https://user-images.githubusercontent.com/93348499/146759177-01a8481c-fada-4d5c-9210-1e880fa67bc1.png)

**Steps To Reproduce**
See above.

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
For 1:
Need add "scale="2.0" IMHO!
I’m not sure what’s right, but it works ))

Sould be IMHO 

`Line 229:     <LightComponent range="10.0" lightcolor="255,0,0,0" scale="2.0" powerconsumption="0" IsOn="false" castshadows="false" allowingameediting="false">`
`Line 234:     <LightComponent range="10.0" lightcolor="0,255,0,0" scale="2.0" powerconsumption="0" IsOn="false" castshadows="false" allowingameediting="false">`
`Line 269:     <LightComponent range="10.0" lightcolor="255,0,0,0" scale="2.0" powerconsumption="0" IsOn="false" castshadows="false" allowingameediting="false">`
`Line 274:     <LightComponent range="10.0" lightcolor="0,255,0,0" scale="2.0" powerconsumption="0" IsOn="false" castshadows="false" allowingameediting="false">`

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0175fec9f87ce2611c8e663cca91925f200d7ce3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
