### ISSUE TITLE
Spawnpoint - No tooltip for GUI sections

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7876]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
No pop-up window for these GUI sections:
`<idcarddescriptiontooltip>Characters spawning at this spawnpoint will have the specified description added to their ID card. This can be used to describe additional access levels their card has on the sub.</idcarddescriptiontooltip>`

`<idcardtagstooltip>Characters spawning at this spawnpoint will have the specified tags added to their ID card. You can, for example, use these tags to limit access to some parts of the sub.</idcardtagstooltip>`

`<spawnpointtagstooltip>Can be used to refer to the spawnpoint in events and human prefabs.</spawnpointtagstooltip>`

**Steps To Reproduce**

![Image 001_23-08](https://user-images.githubusercontent.com/93348499/146760219-d5acce34-fedf-4262-a66b-fe37d82c9607.png)

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86a29a6da535f34cc916833620d93b4afe44a517

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
