### ISSUE TITLE
Scrollbar does not hide when few objects to display

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7877]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clutters the screen for no reason.

**Steps To Reproduce**
![Image 001_19-20](https://user-images.githubusercontent.com/93348499/146763925-0443e5ec-c534-4f01-a65b-d4501fb33ecf.png)

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
Not a bug, we decided to keep it always visible to keep the layout consistent regardless of the number of crew members.
