### ISSUE TITLE
Talent - Let It Drain doesn't give power to tinkering devices

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7878]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Let It Drain talent doesn't give power to tinkering devices

**Version**
0.15.22.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/539103c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
