### ISSUE TITLE
Bots - Cleanup Items does not clean up fruits

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#7879]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots with Cleanup Items does not clean up fruits.

**Version**
0.15.22.1

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@2df77db.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
