### ISSUE TITLE
The "StatusMonitor" monitor shows the equipment even if it is not on "MiniMap"

### ISSUE THREAD

**Issue by cccpvs** [Regalis11/Barotrauma#7885]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If the object **"junctionbox"** is destroyed, it will continue to be displayed on the **StatusMonitor**.
This problem has become relevant since **version 0.15.21**.
When created in the editor, the **junctionbox** is displayed normally. But when destroyed, it does not disappear from the **StatusMonitor**
The **MiniMap** settings in **Item** did not help to get the desired result.

**Steps To Reproduce**
null

**Version**
0.15.22.1 (Windows)

**Additional information**
We load the standard submarine. We are looking for our cable box.
![](http://barotrauma.dayz-vologda.ru/images/Issue_bug_minimap_v0.15.22.0_1.png)

we check it on the status monitor and see that it is working correctly
![](http://barotrauma.dayz-vologda.ru/images/Issue_bug_minimap_v0.15.22.0_2.png)

after being destroyed by an explosion, it continues to be on the status monitor.
![](http://barotrauma.dayz-vologda.ru/images/Issue_bug_minimap_v0.15.22.0_3.png)

to be precise, before the update of version 0.15.13, the status monitor worked as it should. after destruction, the cable box disappeared.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/075653966010ac361827552a1d26b6e654a102fc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
