### ISSUE TITLE
default reactor settings on vanilla subs

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7889]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Orca2 and r29 have default reactor fire/meltdown timers, which are extremely lenient and will rarely result in fire and almost never in meltdowns.

Other vanilla ships have shorter timers for both.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.22

**Additional information**

**Comment by gerakis** [comment]
That doesnt even sound like a bug. R-29 needs all the help it can get.

**Comment by danielasteljoki** [comment]
Fixed in 89b0e8c.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
