### ISSUE TITLE
Bot AI broken

### ISSUE THREAD

**Issue by leekypipes** [Regalis11/Barotrauma#7890]
I have been playing with the same small handful of mods for over 100 hours, now all of a sudden after this last update, the AI is broken as hell. They wear diving suits into stations, then just drop them wherever, forcing you to retrieve them after every trip. They don't fix hull breaches anymore, leaving that entirely up to me, and I like to play solo, so that's a real pain. And it was really awesome, but as I was fighting a Moloch, and frantically trying to fix the hull that my AI crew would not help me with, I accidentally welded my security officer, causing them to retaliate, beat me, and cuff me, while we were completely full of water! I couldn't refill my oxygen mask, I couldn't steer, I couldn't do anything and I almost failed the mission and died, on a mission that I already tried 3 times, because for some reason, alongside the rest of these issues, whenever I fix a beacon station, it doesn't register and I fail the side mission. I keep trying over and over again but it just doesn't work. I have played almost 150 hours, and I have never had ANY of these issues. So... What the hell?

**Comment by Kaillera** [comment]
outdated mods?

**Comment by gerakis** [comment]
AIs work ok on the vanilla ships, with some exceptions like the azimuth. Modded ships very rarely have good waypoints so that generally doesnt work too well. If the designer actually did waypoints right then they work ok there too.

**Comment by Regalis11** [comment]
Thank you for the report!

I'm sorry to hear about the problems you're having. :/ It's hard for us to do much about this without further info though, since this doesn't seem to occur in the vanilla game. Which mods and subs are you using?

**Comment by Regalis11** [comment]
No known steps to repro, closing
