### ISSUE TITLE
r-29 shell issue

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7899]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
2 parter:
1. Shells in the nose and tail of the R-29 are set to AI target, or rather, not set to "no AI target".
  this results in those two spots, particularly the scoop-like nose hitboxes, easily catching monsters and getting permanently stuck there. 
  Compare to every other vanilla sub which has the nose/tail set to No AI Target.

2. This shell contributes to hull integrity, but damage to the shell can NOT be directly seen. Vision of damage/leaks from that shell is blocked by the inside horizontal wall.
![image](https://user-images.githubusercontent.com/5103517/147063007-4aaf5847-38ff-4c30-a757-f1670a67fa0f.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.22.1

**Additional information**
compounds with the exceptionally low firepower for a really bad time if a mudraptor/bonethresher/crawler gets in the nose section.

**Comment by danielasteljoki** [comment]
Fixed #2, but can you describe issue #1 in more detail? The tags seem to me to be correct. What's the problematic spot where monsters are getting stuck in?

**Comment by danielasteljoki** [comment]
Should be fixed in R-29 update in fbb595a

**Comment by Rokvach** [comment]
Should these pieces also have the no ai target toggled? I can see how creatures could get stuck there
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/19c4f86e-6f85-4d8c-84d6-e2b1746f0c08)

**Comment by danielasteljoki** [comment]
>Turned on the "No AI target" flag for the lower part of the bow of the submarine. There will probably be problems with monsters getting stuck with the upper part, so only for the lower part
Is what rav2n said in the update ticket

**Comment by Rokvach** [comment]
Then no issues, closing.
