### ISSUE TITLE
A Few Feature Requests For Steam Version of Barotrauma

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#790]
* Need to drink or eat.

* Need for sleeping.

* Player can warp time for mission refreshing or having characters wake up from sleep.

**Comment by Regalis11** [comment]
I agree with BillCombs, I don't think these would work that well in practice.

As a side note, feature requests like this would be much more useful (and more likely to be considered) if you tried to describe _why_ you think adding them is a good idea. Especially if the feature has been already suggested and discussed before: you already brought up the hunger mechanic in #695, and then the conclusion was that it won't be added.
