### ISSUE TITLE
Bug healing with Broad Spectrum Antibiotics - npc attack the medic.

### ISSUE THREAD

**Issue by AL0NZO** [Regalis11/Barotrauma#7901]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I try to heal someone with ABX ingame in campaign mode, the npc attacks the medic as the ABx give some internal damage.
I don't think it is intended in the game.

**Steps To Reproduce**
- Grab an ABX in inventory.
- Press H to heal someone of your crew.
- Put ABX on the character
- Wait for the npc to attack you when the internal damage is above 10.
- If the npc doesn't have handcuffes, it is hit until death.

**Version**
Windows 

**Additional information**

**Comment by Oukido** [comment]
I can confirm the part that the medic gets attacked, but they usually stop for me when the medic is beat unconcious.
But I also have already reacted to that beaviour by building a quarantine room for the medic which can be locked by a circuit, in which the medic can cure the infected patient without interruption.
But this brings up another behaviour in the AI that I also would call a bug. If the patient is cured the guards still stand outside the door, ready to beat the **** out of the Medic and there is NO way to stop them from it... Wait command does not do it... sending them on the turrets does not do it... they will always come back to the locked door. They even ignore creatures chewing through the ships shell while they are stuck in this mode.

**Comment by Ek-Videogames** [comment]
This was supposedly fixed in [Regalis11/Barotrauma-development@16f4338](https://github.com/Regalis11/Barotrauma-development/commit/16f4338af0c7fab856052bf645e132445f48de5f) ? I guess needs re-testing.

**Comment by Oukido** [comment]
I did some further testing and found out 3 things relevant to this:
1. Knocking the patient out with paralyzant prevents security from intervening when using ABX.
2. While the descriptions of the Husk infection say the victim is mute at a certain threshold, it seems still able to call for help.
3. Using handcuffs (also self) on the medic after the security has been alerted breaks the combat loop. (Still no good solution if enemies attack the shell)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/caa40eab0ddfa833b585d6bd8766b9812325aaf2
