### ISSUE TITLE
Pet Peanut's behavior regarding food and movement is bugged

### ISSUE THREAD

**Issue by Multipogopuschel** [Regalis11/Barotrauma#7903]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since the new patch all Peanut pets stopped moving and therefore eating when they are in a room with other pets. The other pet types are not afflicted. Two Peanuts afflict each other, so both don't move and eat.

**Steps To Reproduce**
Hatch a Peanut and another pet.
Place both of them in the same room.
Peanut does not move or eat.
Place Peanut in a room without the other pet present and it will move and eat as intended.

**Version**
Barotrauma v0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)
Windows 10 

**Additional information**
I tried to place Peanut in different situations and rooms to narrow down the issue, since it sometimes seemed like humans were also impairing Peanut's behavior. I boiled it down to other pets, but I might have missed other situations.

**Comment by Regalis11** [comment]
This is intentional: like [the SCP it's based on](https://scp-wiki.wikidot.com/scp-173), Peanut doesn't move when it's being observed by someone (excluding its owner).
