### ISSUE TITLE
Mod drone will crash the game when character drop into it

### ISSUE THREAD

**Issue by Caeures** [Regalis11/Barotrauma#7905]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Here are some small drone, and opened with a door to make crew get in and out. It had never crash before, but today sometimes a character drop into it or be washed into it by the water. The game will crash, and even without crash report.

[Drone.zip](https://github.com/Regalis11/Barotrauma/files/7765983/Drone.zip)

**Steps To Reproduce**
Attach the drone into Selkie lower hatch.
Fill the drone with water.
Then try to fall off the ladder into it.
The game won't crash every time, but probably one of five it will crash.

**Version**
Operating system: Microsoft Windows NT 11 64 bit
GPU name: NVIDIA GeForce GTX 1060

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/836681334c8043ec5abe5b744ecebc2cb28bc40e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
