### ISSUE TITLE
Bot AI reload coil gun with random ammunition

### ISSUE THREAD

**Issue by LemADEC** [Regalis11/Barotrauma#7911]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When reloading a coil gun, bot seems to prefer to newly crafted (100% durability) ammunition, even if it's further away. I'm expecting them to use first the partially consumed ammunition of the same type first, or at least the closest shelf.

**Steps To Reproduce**
1- Put 3 shelfs of ammunitions with first normal but partially used ammunitions, then a different kind (piercing or whatever) with full durability, then normal with full durability.
2- Assign to boat to operate the coil gun, spawn some mobs
=> bot should always reload with this decreasing priority :
- same type as current but partially used
- same type as current and not used
- other type as current, but partially used
- other type as current and not used

**Version**
0.15.22 Windows, no mods

**Additional information**
I didn't try to reproduce, I've just described what I was expecting to happen since bots consistently choose the wrong ammunition so far in my playthrough.

**Comment by ekqvist** [comment]
They should now also prefer items with the same identifier as one of the contained items when acting on the Load Items order (Regalis11/Barotrauma-development@50b5cef)

**Comment by ekqvist** [comment]
I think it's actually better that they prefer fuller boxes and rods as preferring emptier items could lead them to have to get more items more frequently

**Comment by LemADEC** [comment]
Preferring full ones means we end up with only partially used ones in stock.
Preferring the partially used ones means there's hardly more than one used in stock.
To be more flexible, they could just use the closest one of the same kind, provided it's not empty.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
