### ISSUE TITLE
Fabricator desync?

### ISSUE THREAD

**Issue by LemADEC** [Regalis11/Barotrauma#7914]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In the fabricator, when recycling Shell canister with lead, if I right click to close the dialog (to do some repair, waiting for the output), the fabrication is cancelled. Furthermore, after this initial issue, the CREATE button no longer work until the input slots are changed.

**Steps To Reproduce**
1- (Get into a fight, run out of Railgun ammunition, pick a used shell, run to the fabricator)
2- while empty shell is in hand, and lead is already in the fabricator input slots, select the recycling recipe
3- click CREATE than immediately right click outside the dialog to close it
4- wait a few seconds, (go repair the hull or whatnot)
5- open fabricator again
=> at this point crafting should be done
Practically, the fabrication was cancelled, the empty shell is in an input slot and we can't start the fabrication again
Closing/opening the fabricator doesn't fix it.
Adding an item or swapping 2 inputs slots will fix the CREATE button so we can request the initial fabrication again.

**Version**
0.15.22 Windows, no mods, multiplayer campaign

**Additional information**
Issue was seen with a single player in the game.
This doesn't happen all the time, I've seen it mostly (only?) in combat, so it could be related to a desync between client fabricating and monster hitting the sub server side?

**Comment by gerakis** [comment]
Ive seen this bug. I think it has something to do with having crafting ingredients in your personal inventory when hitting create. As long as I move them to the fabricator itself or a linked storage it seems to work ok.

**Comment by LemADEC** [comment]
It seems related to using an item from your inventory and, while it's fabricating, select another slot in my hotbar.
There's no need to close the fabricator dialog to cause the issue.
I see it in combat because I try to repair the hull while it's fabricating.

**Steps to reproduce**
1- fill fabricator with required ingredients (Steel bar and lead), leaving at least 1 empty slot
2- have an empty Canister shell in hand, not in the input slot
3- select the Canister shell (recycle) recipe
4- click CREATE
5- while it's fabricating, press a shortcut key to select an hotbar slot (for example, your welding tool)

It's also reproduced when recycling Coil ammuntion.

**Comment by JoneKone** [comment]
This might be related. there is a bug where when you craft stuff in fabricator it can drop the crafting material to ground and it seems to stop the crafting (button stays gray), but it's still crafting and the material is on the ground.

When crafting is done the item on the ground disappears and the fabricator shows the new crafted item, like nothing happened.

Also when the button is gray you can push it and it will cancel the crafting. (not sure what happens then as I haven't really paid attention.) 


reproduce i don't know how, but it has happened to me multiple times..

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/52c4d259d6738148e3fcff8bb8b1b4cea155c237

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore, working correctly. Closing.
