### ISSUE TITLE
Doctor atmosmachine alienpistol typo

### ISSUE THREAD

**Issue by mLuby** [Regalis11/Barotrauma#7922]
_Content/Talents/Doctor/TalentsDoctor.xml_ `identifier="atmosmachine"`
```xml
<SpawnItem identifiers="alienpistol" spawnposspawnposition="ThisInventory" spawnifinventoryfull="true"/>
```

Looks like a simple typo. 😇

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5c15b6e6f8acb797617efe352e4421c3feb15049

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
