### ISSUE TITLE
Coaxial Turret System Only Displays One Turret's Ammo on UI

### ISSUE THREAD

**Issue by Breligar** [Regalis11/Barotrauma#7924]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Setting up a coaxial turret system (in this case, a Coilgun/Railgun) functions mechanically, but the periscope/turret UI only shows one turret's ammo display above the Supercapacitor charge bar regardless of what weapon is selected. In the Coilgun/Railgun example the periscope UI will only display the Railgun's ammo and not the Coilgun ammo no matter which turret is used.

**Steps To Reproduce**
1. In sub editor, set up a coaxial turret system. (I've tried two so far, both had this issue. First was Lever, (1) XOR, (2+2) Relay, second was Lever, (1) NOT, (1+1) Relay; copies of these can be found on the Workshop, Doomich's K-24 Crocodile for the former, Crusade's Turret Assemblies for the latter.)
2. You'll notice that both assemblies function in test at default; however, upon editing or replacing any of the assembly, or even copy+pasting it somewhere, it will show the aforementioned error with the UI's ammo display upon further testing.

**Version**
0.15.22.1 (Windows, Revision 898f64d2c0)

**Additional information**

I originally posted about this on the Barotrauma Reddit; a user named Glandziu replied with their own testing results:

"The whole screen visuals seem to depend on the position_out connection of the periscope, the UI included. The railgun takes priority for some reason too.

This could be intended behaviour as you'd most likely want to see what the turret you're controlling is doing. Though in this case having it render based on the trigger_out connection is the point.

Tested with a separate camera and linking the guns positions through a relay, the camera takes the priority then but you get no UI in exchange.

I see no way around this either, other than outright disconnecting one of the guns positioning connection.

I suggest marking this as a thing for the devs to look into in the future, perhaps drawing based on what both connections are connected to? As in still controlling both with position_out but seeing it from the perspective of the one trigger_out is connected to.

Edit: Which turret is being picked for rendering also seems to be impacted by how many components are inbetween the turret input and periscope output."

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b5c007d20200dcf28e6fe0402ea488d0ed0707d7

**Comment by Working-Joe** [comment]
I noticed on the commit channel that this fix may involve using the `trigger_in` connection on the turrets to determine what turret the periscope to focus on. Has it been taken account that it's common for sub builders to put circuits inbetween the periscope and the turret? Either for firerate control, custom firemodes like burst, but also things like periscope steering of shuttles. If the implementation with `trigger_in` works the same as the `position_in` these circuits would now not be able to focus on the turrets at all

**Comment by Regalis11** [comment]
@Working-Joe Yes, that's been taken into account. The turret sends a "probe signal" through the trigger_out output and checks if it reaches a turret, and if not, it tries to find it using position_out.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Regalis11** [comment]
Not working correctly, reopening https://github.com/Regalis11/Barotrauma/issues/8075

**Comment by Regalis11** [comment]
I decide to revert the commit, since it appears to cause issues in circuits where the trigger_out signal is used to control relays (the "probe signal" toggles the relays).
