### ISSUE TITLE
Portable Pumps behave as though they are unpowered when toggle state is used to control them

### ISSUE THREAD

**Issue by Gravityowl** [Regalis11/Barotrauma#7925]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a disabled, or off, a portable pump that has a battery in it, that is connected by a wire and controlled via TOGGLE_STATE, will quickly drain a small amount of power from the battery placed inside and then begin to behave as though it is unpowered when the pump's state is toggled on. 

Removing and placing the battery back in the pump fixes this error so long as the pump is on, or believing that is on and unpowered. Manually switching the pump on while the error is occurring also fixes this if controlled via TOGGLE_STATE afterwards. 

This does not occur if the battery is placed in the pump while on, but will still occur if placed while on but then manually toggled off, and then controlled via TOGGLE_STATE

**Steps To Reproduce**
1. Place a Portable pump
2. Turn it on and set water rate to -100%
3. Turn it off and place a battery inside
4. Attempt to control the pump using a pulse signal such as a button that is connected to TOGGLE_STATE

**Version**
v0.15.22.1(ReleaseWindows, branch release, revision 898f64d2c0) 

**Additional information**
Tested on Windows 10. SET_STATE seems to be working as intended

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07f31d663e8ec8ac14123cfcc8714d017854e57a (referenced a wrong issue in the commit message)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
