### ISSUE TITLE
Wifi linked to chat messages pick up discarded messages

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#7928]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Wifis linked to chat will recieve constant signals from other wifis that are linked to chat, ignoring the "discard duplicate chat messages"

I expected that duplicate messages sent out by "link to chat, discard duplicate chat messages" wifis would drop duplicate signals but ah well

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.15.22.1

**Additional information**

**Comment by Regalis11** [comment]
Removing the bug label. The behavior seems to be in line with the description of the property: "If set to true, the component will only create chat messages when the received signal changes.".
