### ISSUE TITLE
Potentially pets turns hostile after friendly NPC turns hostile by event

### ISSUE THREAD

**Issue by soledad630** [Regalis11/Barotrauma#7935]
- [Y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Currently i have experienced pets turning hostile and constantly biting other pets and/or crewmates, 2 of them after right after a terrorist stakeout terrorist reveal event. In all cases their affinity gauge shows that they are well fed. Which makes me suspect that they are being affect by npc changes imbedded in missions.

**Steps To Reproduce**
1. Own 3+ pets, 5+ to be safe.
2. Start a terrorist stakeout event
3. Wait for terrorist to turn

**Version**
0.15.22.1

**Additional information**
The whole cause of issue is mostly a educated guess, but it's happening only after the event is added and 2 of the 3 occurrences are after the terrorists starting to attacks so I suspect they are related.

**Comment by MaaiG** [comment]
I felt bad for the little critters, but they might be rabid. 👼 ...tossed out of the nearest airlock.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0f573cfaf4cf5d11d26d87a875c3312fffc588e7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
