### ISSUE TITLE
Stungun dart recipe bug

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#7937]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When crafting a stungun dart and having multiple colors of wires in the characters inventory the fabricator pulls one of EACH (up to 4) color of the wires into the fabricator and also uses them up in the crafting process

**Steps To Reproduce**
Take a steel bar and up to 4 wires of different colors into your inventory and craft a stungun dart

**Version**
v0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/96f01bf5a7b2d8c2de9910db1fd44ad87765a2b8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
