### ISSUE TITLE
Multiplayer bug in Barotrauma v.0.15.22.1

### ISSUE THREAD

**Issue by VAYZAD** [Regalis11/Barotrauma#7938]
Description
When I start a round in Barotrauma, everyone except the host gets thrown from the server.

Steps to reproduce
I just started the server in Barotrauma mode, everything is serious and when you start a round after purchasing and choosing missions, the participants have an endless load and have the opportunity to close the panel with tasks and after they close it they kicks from the server because of waiting.

Version
Game version 0.15.22.1 I am using Windows 10 operating system and my friend is Windows 7.

Additional information
I have nothing to add yet all of the above is all I can say, please help as soon as possible, otherwise I really want to play with my friends

**Description**
Когда я запускаю раунд в Barotrauma у всех кроме хоста выкидывает с сервера .

**Steps To Reproduce**
Просто запустил сервер в Barotrauma режим все всерьёз и когда запускаешь раунд после закупки и выбора миссий у участников бесконечная загрузка и есть возможность закрыть панель с заданиями и после того как они его закроют их кикает с сервера из-за ожидания .

**Version**
Версия игры 0.15.22.1 я использую операционную систему Windows 10 а друг Windows 7.

**Additional information**
Мне нечего добавить ещё всё выше перечисленное  это все что я могу сказать прошу помогите поскорее а то играть очень хочется вместе с друзьями

**Comment by Regalis11** [comment]
I'm afraid there's not enough info in this ticket (e.g. the error message) to diagnose the issue, but I suspect this is a duplicate of one of the many similar reports we've gotten since.
