### ISSUE TITLE
Motion detector - "Detect Offset" will be reverse when copying.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7941]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

https://user-images.githubusercontent.com/93348499/147477174-83aeee38-1fb0-44cd-8abd-701acd1a4037.mp4

**Steps To Reproduce**
1. `Motion detector` - Mirror-Y - Copy (with Ctrl) - Copy - Copy....
2. Mirror-X = >>> Same problem!
3. Mirror-X + Mirror-Y >>> Same problem! 

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Possible related problem https://github.com/Regalis11/Barotrauma/issues/7789

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f521961fbfc4bdd39813f686db4ee79199f72ecc

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
