### ISSUE TITLE
Feature Request - Prevent Character from falling out of a bed when being "sedated" with paralyzant

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#7951]
While I was looking for ways to circumvent AI Problems with healing husk infection with ABX (https://github.com/Regalis11/Barotrauma/issues/7901) I stumbled across the possibility to use paralyzant as sedative. While this would open a few more possibilities for medical gameplay, right now patients fall out of bed as soon as they are knocked out.

It would be nice if they would stay in bed to keep the healing bonus and also since it makes sense.

**Comment by Regalis11** [comment]
That's a nice idea, I think we could consider this! I'll close the ticket though since the issue tracker is intended for bug reports.
