### ISSUE TITLE
small issue on boarding axe's description

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#7953]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The description of the axe still says "occasionally", but the damage rng of it was removed
![image](https://user-images.githubusercontent.com/55637865/147713768-1efbe9cf-c115-44d0-8100-589eab4719fa.png)

**Version**
stable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1993289cb39593fd0c29e09b147f83ecf063c952

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
