### ISSUE TITLE
Scaling the size of duct blocks glitches the size of gaps attached to it.

### ISSUE THREAD

**Issue by Woestel** [Regalis11/Barotrauma#7957]
- [x] I have searched the issue tracker to check if the issue has already been reported.
I searched for "duct block gap"

**Description**
Title. see the gif animation attached.
https://gyazo.com/872f1d282ee0636b9a93c446dd5a5055

**Steps To Reproduce**
1. Open sub editor.
2. Place duct blocks.
3. Change the scale. The gap is now the same size as the block.
4. Restore the scale. The margin of the gap is irreversible.

**Version**
Windows v0.15.22.1

**Additional information**
I discovered this when trying to match the size of the duct block with the Large Horizontal Inside Wall.

**Comment by MaaiG** [comment]
How lazy I was to write )), but since this is the case... ok. In the same piggy bank! ))
Similar situation with the motion detector.
For some unknown (to me) reason "Detect Offset Y" cannot be smaller than "Range Y". But it does happen.
https://user-images.githubusercontent.com/93348499/147751801-11324cb7-6e82-427f-a9ab-53f56eaea0a5.mp4
Once restarted, it disappears.

**Comment by Woestel** [comment]
I just checked and the hatch with buttons has the same problem.
On the left is the rescaled hatch and on the right is the default hatch.
https://gyazo.com/ed1d6493af3a0d28162bb5ca40ef9da8

**Comment by Woestel** [comment]
Once the gap is gliched, it is saved in the sub.
Restarting will not undo the gap.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/12beca02157c89dac63843ad76be27b1f0d76238

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Woestel** [comment]
https://gyazo.com/e870dc47004ee26b9b62fc8465c83cd2

Things got worse with the 0.16.6.1 update.
The gap margin that used to be around the duct block (or door or hatch) is now lost, and the duct block is no longer allowed to snap to the hull.

We didn't want to lose the gap, we wanted the gap to be maintained......
Probably not just me, but many submarine designers.
