### ISSUE TITLE
Shadow inside the wall.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7959]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shadow inside the wall from the other wall.

**Steps To Reproduce**
https://user-images.githubusercontent.com/93348499/147767071-bd283e44-d0f0-494d-ba09-14ad60ed9286.mp4

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
This can be fixed by not extending the wall half-way through the other wall like that.

Although, I agree the LOS algorithm should take situations like this into account and not cast a shadow, but I'd say that's a broader issue covered by https://github.com/Regalis11/Barotrauma/issues/6000
