### ISSUE TITLE
Sub Editor - cursor glitches

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7960]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Sometimes the cursor glitches. Locks in the "grab" animation.
https://user-images.githubusercontent.com/93348499/147768486-36e82e6c-2a8d-4013-bafe-66ee3da36ea1.mp4

**Steps To Reproduce**
No pattern found.

**Version**
Now it's v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
No known steps to repro, closing
