### ISSUE TITLE
extreme number of draw calls per frame

### ISSUE THREAD

**Issue by DeltaNedas** [Regalis11/Barotrauma#7964]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game uses a very large number of draw calls (5200-6500) in new-old saves, many more used when drawing ui.

**Steps To Reproduce**
```
$ apitrace Barotrauma
<open up save or create a new game>
$ qapitrace Barotrauma.trace
```

**Version**
v0.15.22.1, debian sid

**Additional information**
Running barotrauma on a crappy 2.5ghz quad core cpu (1 core contantly maxed while playing)

I decided to do some **basic** profiling to check out some causes of lag.
I used `apitrace trace ./Barotrauma` to check how many draw calls the game uses, around 120 for loading screen which is pretty good but around 6500(!) for a singleplayer campaign game on the Typhon with 6 crew members.
This results in around 20 fps (on both 1920x1080 and 1280x720), in comparison to a new game (Humpback) with around 45 fps and 5200 draw calls. I'm sure a part of this slowdown is caused by the increased draw calls, but obviously not all of it.

I also noticed that when opening containers with lots of items it gets a bit slower (an increase of ~400 draw calls for 13 items in a medical cabinet, roughly checked) which would indicate that UI drawing probably isn't being batched.
It seems like making more drawing batched would be a nice way to reduce draw calls and gain a few fps.

**Comment by Regalis11** [comment]
This is a known issue, and something we're planning on optimizing (ticket in our private repo: https://github.com/Regalis11/Barotrauma-development/issues/2707). I'll close the ticket though, since it isn't strictly a bug.
