### ISSUE TITLE
Delay inside delaycomponents can not be reduced in game (only increased)

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#7965]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Entering a lower value in a delay in game will not actually shorten the delay.  Instead, the highest value that the delay has had that round will be used.

Likely a side-effect of the PR on the `set_delay` pin. 

**Steps To Reproduce**
- In the sub editor wire `button -> delay -> (toggle_state) lightcomponent`
- Start testing
- Reduce the delay by typing a new value into the component
- press the button
The light switches after the original delay value, rather than the new, shorter delay. Increasing the delay works, but after than any lower. Likely works after a sub reload on level changes.

**Comment by Regalis11** [comment]
I'm afraid I couldn't repro this:


https://user-images.githubusercontent.com/14351070/147917978-65569ba6-5683-4ae0-9805-e86aaedf3bd4.mp4

**Comment by Working-Joe** [comment]
You're right, it seems to work fine with a button. It seems a constant signal is required. It does break if you use a lever and the `set_state` input of the light.

**Comment by Regalis11** [comment]
Ah, I see! Managed to repro and fix it now https://github.com/Regalis11/Barotrauma-development/commit/975ce5469f87cc9ce57d2262a0c15296161116a0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
