### ISSUE TITLE
Make Calyxanide Deal Damage to Carrier- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#797]
3 damage per second. Slows down carrier. Effect lasts for 30 seconds.

**Comment by Regalis11** [comment]
Even though it's not directly explained anywhere (yet), the carrier is actually not infected by the husk parasite. The idea was that it has something to do with the alien ruins (as hinted by the fractal-like growth on it). As such I don't think calyxanide should have an effect on them.
