### ISSUE TITLE
All Seeing Eye Talent Bug 2: Electric Boogaloo

### ISSUE THREAD

**Issue by zkxs** [Regalis11/Barotrauma#7975]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After taking all-seeing eye as my last talent everything worked as expected at first, but after the round ended it had been replaced with the T1 talent from the electrician tree, setting me three talents behind where I should have been.
![image](https://user-images.githubusercontent.com/1807509/147912131-5855665b-d147-4696-b60e-b7e581d8ca42.png)

**Steps To Reproduce**
I'm not certain, but maybe take all-seeing eye as your final skill? I'll update if I learn more.

**Version**
Windows v0.15.22.1

**Additional information**

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to reproduce this. Tested in a multiplayer campaign by unlocking All-Seeing Eye as the last talent and starting a new round, and the talent selection remained unchanged:
![image](https://user-images.githubusercontent.com/14351070/148550735-78ca882b-abef-470f-8eb9-91feed0dd153.png)

**Comment by Regalis11** [comment]
Nvm, found a way to repro this now. The problem before was that I gave the character a ton of experience (more than enough to unlock all the talents) using console commands, but the issue only occurred when the character had only one unused talent point available for unlocking All-Seeing Eye.

Steps to repro:
1. Give yourself enough experience to unlock 4 talents
2. Unlock everything in the Electrician talent tree except all-seeing eye (or, optionally some extra talents from other trees in addition to the ones in the Electrician tree)
3. Start a new round
4. Unlock All-Seeing Eye
5. Start a new round

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e08b6a406386b7000b51b208179006b1037c627a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
