### ISSUE TITLE
Level gen bug ('Invisible' wall)

### ISSUE THREAD

**Issue by dsr1231248D** [Regalis11/Barotrauma#7978]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There seems to be a map generation bug for the level seed "Phoenix LineaZamoroska" with size "120000x100000" (map seed is i4yezDRM), where a giant wall is made outside of the parameters. This wall is invisible to sonar but with full collision. In the image provided, you can see how it even goes through a cave and some minerals.

**Steps To Reproduce**
The save file provided starts at the round in which this error happens, I suppose it has to do with the generation so I'm guessing inspection of the file can help on seeing what went wrong? Either way on round start, the wall spike is just a few hundred meters to the east of the starting outpost.

**Version**
Windows 11; game v0.15.22.0.

**Additional information**
No mods were being used, this happened in just vanilla Baro using the standard Dugong. A custom submarine was enabled, but not being used when the error was produced.

**Attachments:**
[Save 2.zip](https://github.com/Regalis11/Barotrauma/files/7802535/Save.2.zip)
![Level gen bug](https://user-images.githubusercontent.com/17814596/147945220-d6a0cca1-9234-40f0-88cb-ef7b30fc8f6e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d95efc4821e3f401b63ada501944cd5db23d62ac

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
