### ISSUE TITLE
Vanilla sub - Berillia strange unique offset texture problem

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7979]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Platform Large" - texture problem with strange unique offset

**Steps To Reproduce**

https://user-images.githubusercontent.com/93348499/147950958-f7760143-2163-4a0c-955d-cbe8b97e2ec9.mp4

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
May have something to do with it: https://github.com/Regalis11/Barotrauma/issues/7617

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/355acf0f07fc6843ccb89230f3d3870b554e2448

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
