### ISSUE TITLE
Vanilla sub - Orca2 design flaws

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7980]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Need a universal standard for all docking ports!
The docking port ladder is out of "standard" - left-stepping offset. Ladder not matched to outpost.
2. The lamp in the wall
3. The hatch - wrong depth of the sprite
4. Shell - no shadow

**Steps To Reproduce**
1. Need a universal standard for all docking ports!

https://user-images.githubusercontent.com/93348499/147953178-fbe5d202-5d58-4f04-abd1-f37db7ebe4c0.mp4

2. The lamp in the wall
![Image 001_18-37](https://user-images.githubusercontent.com/93348499/147953574-7498c64c-25da-4447-8753-66f0a505220d.png)

3. The hatch - wrong depth of the sprite
![Image 001_18-40](https://user-images.githubusercontent.com/93348499/147953606-78a8c595-483d-4da8-8c10-7b15dddf925c.png)
![Image 001_18-41](https://user-images.githubusercontent.com/93348499/147953615-adb8691d-544a-40c1-a00e-ebef7bd40d6d.png)

4. Shell - no shadow
![Image 001_18-42](https://user-images.githubusercontent.com/93348499/147953639-fdee254d-70a6-4647-a9f7-121d26906a64.png)

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by danielasteljoki** [comment]
Fixed lamp, docking port and drop shadows in 15c6a05. Hatch depth is set so they're on top of the wires that would otherwise go on top of the button.

**Comment by Oukido** [comment]
Setting the hatches sprite depth to 570+ resolves the clipping problem with the ladder.
The sprite depth of wires is not the same that it shows when selecting them. It is about 855. You can see this if you take a backwall for example and gradually reduce its depth until it overlaps wires.

**Comment by MaaiG** [comment]
> Hatch depth is set so they're on top of the wires that would otherwise go on top of the button.

I forgot to mention another thing.
1. There is a problem when the overlay textures depth is the same. In the game, it may look different than intended.
`Back Wall H1` - depth must be set +1. Should be 0.981
Otherwise `Outpost Barracks Background 3` may be below.
https://user-images.githubusercontent.com/93348499/148081219-972dd3bd-75b4-4a98-8abd-f35a9d706c1e.mp4

2. And you can reduce the number of Structures. Without detriment to design _(I always worry about the large number of constructions on my subs and the performance of the computer :))_
 On the central deck there are six `Platform Basic`! But you can use one long. ;)

_P.S. Cool! I found one hidden stashes 🤡_

**Comment by danielasteljoki** [comment]
Fixed some sprite depths in 326ea0b. Thanks for the help!

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
