### ISSUE TITLE
вылет игроков в BAROTRAUMA

### ISSUE THREAD

**Issue by igroviiakk** [Regalis11/Barotrauma#7983]
Когда я начинаю раунд на своем сервере тогда все игроки спавнятся на аванпосте и они могут управлять своими персонажами     но когда я уже начал заплыв то почему-то все игроки (кроме меня)появляются в режиме наблюдателя .Почему это происходит?

**Comment by Regalis11** [comment]
If Google Translate isn't completely off, this seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/4081
