### ISSUE TITLE
Wrong numbers displayed for commander talent buff "Inspired to act"

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#7984]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bonus skillpoints from commander buff show +9 instead of +10. But they count as +10 because I just was able to craft a masterwork weapon with the summed 99 points shown in the window.
![grafik](https://user-images.githubusercontent.com/83960267/148095291-f2c9d54a-43c2-4179-994d-e2c836607089.png)

Also the 4% buff strength shown by the Health Scanner HUD are quite nonsensical and I'd prefer to not see them at all:
![grafik](https://user-images.githubusercontent.com/83960267/148096314-b590d0bd-b29c-4f97-9b01-5ae19fa58f32.png)

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/148095670-caeac585-1a04-43ed-91b2-9b06d1046855.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e1af6fd53a8046401215d0c7b8a9b43f67f16e72

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
