### ISSUE TITLE
Components - Change settings for components group

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#7987]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
To apply the modified parameter on a component - just close the parameters window.
Issues:
- When you select a group of similar components, the modified parameters apply only if you click on another field in the parameter window. If the parameter window is simply closed then the prameters are only applied for one of the components (conventional name - the `"last component"`!)
- If the one of component already has the necessary settings in the parameter window, the same changes for the other components will not be applied until the  parameter field of this component has been cleared individually.
- The status of the parameter field of the `"last component"` has the advantage!
- Main component parameter string status

**For example:** `Component "And"` - watch the video there are more situations.

**Steps To Reproduce**

https://user-images.githubusercontent.com/93348499/148219090-4cdb279f-151b-48c9-8006-599c3573d5cc.mp4

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Another option involving the `"last component"` (He’s on top now):

https://user-images.githubusercontent.com/93348499/148227051-2a936dfa-f6f3-4f72-86bc-86883e4955bd.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/49a752b32363a51de802a6402c73a691cfcaa7e9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
