### ISSUE TITLE
Artifact mission and transport case + death

### ISSUE THREAD

**Issue by subarotrauma** [Regalis11/Barotrauma#7990]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After having collected the mission artifact, placed it inside the transport case and then having died in the ruins, the artifact transport case is lost and the artifact itself is now located beneath the seafloor.

**Steps To Reproduce**
1. Go to ruins
2. Get the mission artifact
3. Place it inside the transport case
4. Die in the ruins

**Version**
v0.15.22.0, Windows 11
**Additional information**

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to reproduce this. The artifact transport case seems to stay in the dead character's inventory, or if I wait until the character despawns, it gets dropped next to the character. Did this happen in multiplayer or single player?

**Comment by subarotrauma** [comment]
It was in multiplayer (happened twice). Both times, separate missions I died and respawned (becoming a duffel and dropping things from hand slots) only to have lost both the artifact transport case and the rapid fissile accelerator I had. Searched my death spot in the ruins thoroughly but couldn't find either.
We were in the ruins for that mission but later captain noticed the infrasonic signal had moved 700m below us.
I did not die in open waters.

**Comment by subarotrauma** [comment]
This has always happened to me.
Multiplayer campaign.

1. I go to ruins to grab the mission artifact.
2. Put it in the artifact holder.
3. Die inside the ruins.
4. Respawn mid-round.
5. Artifact is no longer inside the ruins.

**Comment by Regalis11** [comment]
I think I managed to fix this now https://github.com/Regalis11/Barotrauma-development/commit/a209eb2c4f7a7b4cae7d4b8d51406e2fc289e46f: the issue only occurred when the transport case was not equipped which I didn't test previously.

**Comment by Rokvach** [comment]
Tested by community, working correctly. Closing.
