### ISSUE TITLE
Limb-targeting StatusEffects in limb-specific afflictions do not target the right limb

### ISSUE THREAD

**Issue by mcbanekenney** [Regalis11/Barotrauma#7991]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
StatusEffects within afflictions that are Limb-Specific will not target the limb the affliction is applied to if the StatusEffect target is set to 'Limb'.

**Steps To Reproduce**
Make a test affliction that has the attribute limbspecific="true" which causes max bleeding with a StatusEffect that has the attribute target="Limb", and see if bleeding is applied to the right limb or even at all.

**Version**
Windows 10, Barotrauma v0.15.22.1

**Additional information**
I am attempting to make a unique form of infection for a mod and this seemed like the right solution to avoid bloating my xml with afflictions personalized to each limb.

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. Tested with the following affliction:
```
<InternalDamage
    name="BleedTest"
    identifier="bleedtest"
    description=""
    type="damage"
    causeofdeathdescription=""
    selfcauseofdeathdescription=""
    limbspecific="true"
    maxstrength="200"
    damageoverlayalpha="1">
    <Effect minstrength="0" maxstrength="200" multiplybymaxvitality="true"
    minvitalitydecrease="0"
    maxvitalitydecrease="2">
        <StatusEffect target="Limb">
            <Affliction identifier="bleeding" strength="1" />
        </StatusEffect>
    </Effect>
    <icon texture="Content/UI/MainIconsAtlas.png" sourcerect="896,0,128,128" color="195,136,60,255" origin="0,0"/>
</InternalDamage>

Which seems to apply to bleeding affliction to the correct limb:
![image](https://user-images.githubusercontent.com/14351070/148520879-aeac8da3-f4fc-4602-ba35-c44cf471d1b1.png)

```

**Comment by mcbanekenney** [comment]
that's odd, must've been a fluke on my end
I will continue testing methods and hope it works properly
my apologies

**Comment by mcbanekenney** [comment]
one more question, is there perhaps a way to apply different afflictions depending on what limb this test affliction is applied to? 
if not, that would make the features I am trying to add a lot easier to implement
