### ISSUE TITLE
Talent gained by applying Endocrine Booster stays after reloading round

### ISSUE THREAD

**Issue by Torusaynim** [Regalis11/Barotrauma#7994]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crafted Endocrine Booster in multiplayer server and applied it on myself, later on we went back to server lobby and loaded save again, after loading I noticed that talent gained with Endocrine Booster is still here so it is possible now to craft another one and apply it again.

**Steps To Reproduce**
1. Craft and apply Endocrine Booster
2. Return to lobby
![image](https://user-images.githubusercontent.com/56824839/148571113-8086fbcb-03e7-4db4-ad77-5067898c5eaf.png)

3. Load campaign again
![image](https://user-images.githubusercontent.com/56824839/148571437-4fbffd2c-3cfc-434e-8d36-8d186d2eb59f.png)

4. Despite telling the player that all unsaved progress will be lost, gained talent should still be here
5. Repeat

**Version**
v0.15.22.1 (Windows, branch release)

**Additional information**
Tried to reproduce it in singleplayer with both "save and quit" and "retry" but both didn't work.

**Comment by Regalis11** [comment]
This seems to have happened as a result of the same bug as https://github.com/Regalis11/Barotrauma/issues/7853, fixed in https://github.com/Regalis11/Barotrauma-development/commit/48f7d39e87dbbdc1085e33b94649fc3daf280d0b
