### ISSUE TITLE
AI Bug - Idle cleanup order picks up and equips a filled gene splicer and puts it in [medcab] container, destroying the genetic material in the process

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#7995]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you have a medicine cabinet with the tag "medcab" and put a gene splicer on the ground. The ai picks it up and puts it into the cabinet. While doing so it equips it in the splicer slot and when it stows it away rips the splicer out and destroys the genetic material.

To reproduce put the medcab autofill tag into a medicine cabinet and drop a splicer on the ground with some bots.

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/148095670-caeac585-1a04-43ed-91b2-9b06d1046855.png)

**Comment by itchyOwl** [comment]
Seems intentional: https://github.com/Regalis11/Barotrauma-development/commit/a80ed442e3295c9f803d56a5c10a36c92dabc739. Maybe an overisght?

**Comment by Regalis11** [comment]
@itchyOwl  It is intentional that they clean the splicers up, but they should no equip and unequip them because it destroys the genetic material.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e3845aa7bf2e08b66592097fc0c723899f4b978

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
