### ISSUE TITLE
Recived an achivement while Cheats Were enabled

### ISSUE THREAD

**Issue by Trapper444** [Regalis11/Barotrauma#8002]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was doing some small minor tests with husk mutagen in the sub editor, so i spawned a few husks and was aparently close enought to get the achivement, didnt joined any servers before or after getting the achivement, literally only thing i did in the day related to barotrauma

**Steps To Reproduce**
Hard to reproduce multiple times since would require multiple steam accounts. Just enable cheats in the sub editor while testing a sub live and attempt to get an achivement would guess would work

**Version**
Current Latest version, 0.15.22.0. Windows 10 Pro.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b81cf7d5a30c23ab854eb28b33d677963629bf84

**Comment by Danielkaas94** [comment]
I got "Xenocide" while testing with spawns

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
