### ISSUE TITLE
Wifi SET_CHANNEL malfunctions only in MP

### ISSUE THREAD

**Issue by droopleshlef** [Regalis11/Barotrauma#8003]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A wifi component's channel cannot be set by a signal originating from a wifi component connected to chat, regardless of how many other components are in between the two wifi components and regardless of anti-griefing settings, but *only* in multiplayer. In single player modes and the sub tester, this bug does not exist.

**Steps To Reproduce**
Create a minimal submarine in the sub editor. Add wifi component A and wifi component B. Connect signal_out of wifi component A to set_channel of wifi component B. Enable connection to chat in wifi component A. In the sub editor tester or a single player campaign, send a radio chat to set the wifi channel. Take the same sub to a multiplayer game self-hosted or otherwise to see that the same functionality does not exist. Be sure to check the anti-griefing option allowing wifi components to connect to chat.

Optionally, include a terminal signal_out->wifi component set_channel to ensure that wifi channel changing is working correctly otherwise, regardless of mode.

**Version**
OS: Windows 10 Version 21H1
Barotrauma Version: v0.15.22.1

**Additional information**
The circuit that led me to isolating this problem takes input from a terminal or a wifi component (via chat). This circuit takes a number as input and does some math to it. The output comes from two adder components. The terminal and remote options use the same input and the same output. If the initial signal comes from the terminal, then the channels change correctly. In multiplayer, if the initial signal comes from the chat-connected wifi component, it will not. This is true despite the fact that the adder components produce the correct channel numbers based on the radio chat input and will correctly output these channel numbers to text displays at the same time as not changing the wifi component channels as intended.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dee7446384d93b3e9d423e29631f0da4abff3d48

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
