### ISSUE TITLE
Concatenation Component - Please eval() before concat()

### ISSUE THREAD

**Issue by YanWenKun** [Regalis11/Barotrauma#8004]
**Example:**

![01](https://user-images.githubusercontent.com/58008456/148693531-08b36cc6-ed7a-45ac-b6b5-894a1310e433.png)

Trying to concat "Saline" & "Blood Pack" using Text ID.
(`entityname.antibloodloss1`, `entityname.antibloodloss2`)

**Result:**

![02](https://user-images.githubusercontent.com/58008456/148693543-f3ec52b8-8a35-453e-a051-0f4e042cfd2b.png)

It just display "entityname.antibloodloss1, entityname.antibloodloss2"

**Expected:**

Please eval strings before concatenation, so this circuit will display "Saline, Blood Pack"

**PS.**
I'm using text IDs to make my item assembly available in multi-language. I found some ways to achieve it, but not so neat (label array => not consistent across languages. Text.xml => need Mod always enabled). Concatenation of text IDs seems much more promising (and better utilizing official translations). Please let me know if there is a better way to do i18n.

**Comment by MaaiG** [comment]
In addition!
Dear **Regalis11** please make the "Set Separator" option for component deconcatenation settings. Now you have to use separate components just to make a separator. This will help simplify the circuits and make them easier to create. Please!

**Comment by Regalis11** [comment]
Implemented the "separator" property in https://github.com/Regalis11/Barotrauma-development/commit/f2583f5131fd222fc63694613bd96e7fb687bac8.

However, making the concat components use localized strings is a little complicated. It would mean circuits can behave differently depending on the language you're using, which would be a problem in multiplayer in particular, and would also lead to issues if the values are being compared to non-localized strings (e.g. if you were using a signal check component to evaluate the output of the concat component). So I think changing this might actually require making the clients use the same language as the server in the signal components, and possibly also adding localization support to _all_ components that handle strings. 

We could possibly look into this in the future, but for the time being, I don't think it's worth complicating things this much for a niche use-case like this when there's more high-prio issues to work on.

**Comment by YanWenKun** [comment]
Thanks. From your description I can see it's more complicated than necessary. I'll try other ways I mentioned to workaround.

**Comment by MaaiG** [comment]
Thank you so much! 😁
