### ISSUE TITLE
Can't swap subs in multiplayer

### ISSUE THREAD

**Issue by barotraumaluke** [Regalis11/Barotrauma#8006]
- [y ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't swap to pre-purchased submarines in multiplayer

**Steps To Reproduce**
-have any sub
-purchase any new sub (not purchase and switch)
-swap to new sub (fails)

OR

-have any sub
-purchase and switch to new sub
-swap to original sub (fails)

**Version**
0.15.22.1 Windows

**Additional information**
None

**Comment by Regalis11** [comment]
Duplicate of #7862

**Comment by barotraumaluke** [comment]
how do i fix it?
________________________________

**Comment by Regalis11** [comment]
The issue has been fixed in our private repository, but unfortunately the fix isn't out in the public version yet (although we're trying to push out a hotfix soon).

**Comment by barotraumaluke** [comment]
thank you for your reply, i look forward to the next release. lovely game !
________________________________
