### ISSUE TITLE
Motion Detector - Signal is dropped to zero on update

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#8012]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Cannot fully use `motion detector` as `presence detector`!
During signal data updating, the `motion detector` is dropped signal to zero (2-3 sec). As a result, the devices connected to such detector are "ON" for short periods of time.
**For example:** the door tries to opened for a while.
**Expected Behavior:** While the character is in the detection zone, the `motion detector` should always "signal 1" without drop to zero when signal update.

~~2. Localization
Incorrect device name translation (Сorrect Name - "Детектор движени**я**")
`<entityname.motiondetector>Детектор движений</entityname.motiondetector>`
Should be
`<entityname.motiondetector>Детектор движения</entityname.motiondetector>`~~

**Steps To Reproduce**
1. Set `Minimum Velocity` = "0.000"
https://user-images.githubusercontent.com/93348499/148988550-915e0378-4c52-44da-811b-ed4a2d500981.mp4

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
Fixed the signal issue in https://github.com/Regalis11/Barotrauma-development/commit/bddc94ab26ee33925339e6cd9af9b16ad442cfd6, copied the 2nd issue to another ticket: https://github.com/Regalis11/Barotrauma/issues/8015

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
