### ISSUE TITLE
UI Bug - Exclamation mark gets not cleared when more talentpoints are obtained than can be spent

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#8014]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I experienced this bug with my medic in singleplayer who had only one talent left to be chosen, and accumulated 3 talentpoints by deconstructing a large quantity of alien artifacts.
With the one point I was able to spend I had 2 points left which were hidden behind the "All talents unlocked" label.
But the exclamationmark symbol did persist, even over quit and load.

Example:
![grafik](https://user-images.githubusercontent.com/83960267/149019184-733a0972-163d-4d2d-a9c2-8c482179c550.png)

**Steps To Reproduce**
Easiest way:
giveexperiance 100000
spend all possible points
exclamationmark stays

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/148095670-caeac585-1a04-43ed-91b2-9b06d1046855.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ce09cdea993f7074e20dbf9e3050296822feeed2

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
