### ISSUE TITLE
Motion detector translated incorrectly in Russian

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8015]
Copied from ticket https://github.com/regalis11/barotrauma/issues/8012 which originally contained 2 separate bug reports:

**Description**
Incorrect device name translation (Сorrect Name - "Детектор движени**я**")
`<entityname.motiondetector>Детектор движений</entityname.motiondetector>`
Should be
`<entityname.motiondetector>Детектор движения</entityname.motiondetector>`

**Version**
Any

**Comment by Regalis11** [comment]
Passed on to the translators, lets wait for the next loca pass

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/88cdd5e1b7b9264936375f96c844e79d652408ce

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
