### ISSUE TITLE
Game Mechanics - Genetic effects get removed when a duplicate effect is removed (both get removed)

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#8016]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ok this one was hard to find a good Headline.

If you have duplicate genetic effects like if you equip the same genetic material twice, and remove one of the two, the genetic effect gets completely removed for both genetic materials.

While this is kind of ok for buffs so people have to think about what they are doing, this also applies to the negative genetic traits of tainted genetic material.

If you equip 2 different tainted materials with the same genetic malus and you rip one out, the malus is completely gone. But the positive effects of the other material stays. So it can be abused to "de-taintify" a tainted material

**Steps To Reproduce**
Equip 2 tained genetic material with the same tainted effect in an advanced gene splicer and rip one out. Malus is gone.

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/148095670-caeac585-1a04-43ed-91b2-9b06d1046855.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/55b92cfd2d8d63d0b570b4a458dd520a68ce77f9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
