### ISSUE TITLE
Copying a modified object group - Wrong direction of wire 

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#8017]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When copying a modified group of objects, wire direction is wrong.

**Steps To Reproduce**

https://user-images.githubusercontent.com/93348499/149147285-76ee7137-aa47-4856-bc38-e39783ec4266.mp4

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Related: https://github.com/Regalis11/Barotrauma/issues/8018

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
