### ISSUE TITLE
Copying a modified object group - Fell out wire clone

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#8018]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When copying a modified group of objects, a wire clone fell out and its direction is wrong.

https://user-images.githubusercontent.com/93348499/149147200-aa2be83a-5567-448e-a3d5-2d22f51a0515.mp4

**Steps To Reproduce**
~~Circuit: [1-Test_Wire-out.zip](https://github.com/Regalis11/Barotrauma/files/785473-/1-Test_Wire-out.zip)~~
Circuit after paste doesn’t work for some reason! Can try this "sub": [__Test-3.zip](https://github.com/Regalis11/Barotrauma/files/7855069/__Test-3.zip)
How to: https://user-images.githubusercontent.com/93348499/149154853-f2f26410-4f89-469d-ac9f-1bdefd1ff16b.mp4
Step by step: "Select group - Copy - Change group (Ctrl) - Copy".

**Version**
v0.15.22.1, Vanilla 0.9 (Windows 10-x64).

**Additional information**
Related: https://github.com/Regalis11/Barotrauma/issues/8017

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a10109ebb8e216d18bbb8845bfe9345ed4871ae

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
