### ISSUE TITLE
Husk genes do not allow commands to be made.

### ISSUE THREAD

**Issue by rubeste** [Regalis11/Barotrauma#8021]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
From my understanding, if you have the Husk genes you can still command your crew members. Sadly I can not do this. When I try to assign new tasks via clicking in the crew menu it just doesn't work.

**Steps To Reproduce**
1. Insert Husk Gene into character. (Note I combined another gene (Mollusc) with this one)
2. Infect the character with the Husk parisite.
3. Wait till the max infection is reached.
4. Try to command characters.

**Version**
- Version: 0.15.22.1
- OS: Windows 10

**Additional information**
No mods were installed.
Husk gene was combined with the Mollusc gene with the muscular negative effect.
I used the advanced Gene splicer with the other slot used by the hammerhead matriarch gene.
All genes are at 100% quality.

**Comment by Renko-6662** [comment]
This isn't a bug, when you reach above 50% infection, you are muted and can't give orders anymore ;)

**Comment by rubeste** [comment]
Now that I read the wiki again. I see that I miss read it.
