### ISSUE TITLE
Autoshotgun show as full when it's not

### ISSUE THREAD

**Issue by Renko-6662** [Regalis11/Barotrauma#8022]
![autoshotgun](https://user-images.githubusercontent.com/66101079/149348691-6337450d-f575-43c8-a552-8f4d0e2fa14e.png)

**Description :**

From what I understand, the stateindicator only check if a slot is not empty, it doesn't care about the amount of items in this slots.
So an autoshotgun will show as full like in the picture, even when it only has 4/32 ammo.
That would also help a lot with modding.

**Version :** This has been here for as long the autoshotgun has been here.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/186391b06064616f24d41dfb843284440f91c4dc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
