### ISSUE TITLE
Make the character crouch more

### ISSUE THREAD

**Issue by Nyxlyzers** [Regalis11/Barotrauma#8023]
The title and the images self-explain the suggestion, just make the character crouch more, so we can actually shoot when standing behind someone.

(Credit of the images to "Is this Dark Souls" and his Crouch Harder mod)

![image](https://user-images.githubusercontent.com/66521547/149357374-666be14e-0102-4acc-a201-7cdd96e45fa9.png)
![dowasdsadnload](https://user-images.githubusercontent.com/66521547/149358110-46c3a339-ace8-405d-aa2f-97c544589bc0.jpg)

**Comment by Regalis11** [comment]
Even though we generally only use the issue tracker for bug reports and don't take feature requests through it, this was such a quick thing to change that I went ahead and did it: https://github.com/Regalis11/Barotrauma-development/commit/7de4f1838aae7523204d54c2c72e9c8bd52f1cab

**Comment by Nyxlyzers** [comment]
why i can't access the page?

**Comment by Rokvach** [comment]
Walking while crouched looks a bit off right now, it looks fine if you are stationary but as soon as you start walking around it looks more silly than tactical. There's also some issues with the feet sometimes like whole feet bending backwards as it gets stuck somewhere etc. Also entering the crouch state is very frantic, not sure if we can adjust that. 

Is it possible to raise the character up higher if they walk and when they are stationary have them in the lowest position?

**Comment by Regalis11** [comment]
@Nyxlyzers it's a link to a commit in our private repository.

**Comment by Regalis11** [comment]
@Rokvach addressed in https://github.com/Regalis11/Barotrauma-development/commit/dafb57f547a15d041864ae61aa1ac7b36a4bd1a6

**Comment by Rokvach** [comment]
Looking good, no issues. Closing.
