### ISSUE TITLE
[Unstable] wikiimage_sub outputs blank image

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8025]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Open sub in sub editor
2. Use the `wikiimage_sub` command
3. View created image

**Version**
Windows Unstable v0.16.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f18b3952d06ac930eddfb02c4ac7c509b9dfef81

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
