### ISSUE TITLE
[Unstable] Outpost wall 3 is cropped wrong

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8026]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/67431770/149373621-d05d4647-8e52-4a57-971f-523cc318299c.png)

**Version**
Windows Unstable v0.16.0.0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
