### ISSUE TITLE
[Unstable] Component item picker sprite does not match in-game sprite

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8027]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Version**
Windows Unstable v0.16.0.0

**Comment by Regalis11** [comment]
I don't see the problem here, do you mean the inventory icon is slightly less saturated, or that the in-game icon has a lower resolution...?

**Comment by Jade-Harleyy** [comment]
The inventory icon is still the one from the previous version, you can see the pins and outer part don't match what the new sprite looks like in-game.
