### ISSUE TITLE
"Stairs left" is mirrored on the status monitor's sub blueprint

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8029]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"Stairs left" is mirrored on the status monitor's sub blueprint

**Version**
Any

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/4ba82683-d492-44a9-a50d-44cd1f733a76)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/975d78cd413b2478c3e4d523d430206dcd004936

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
