### ISSUE TITLE
Duct block's closing element is at the wrong position

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#803]
I assume the closing element is that black and orange colored square, judging by the fact that the opened duct block doesn't have such a thing. If that's the case, i feel like it probably was supposed to be in the middle of the duct block.
The closed one is on the left side and the open one is on the right side.
![duct block](https://user-images.githubusercontent.com/38168249/45658956-2cce5c00-bb1c-11e8-8034-12656593a008.png)

**Comment by Regalis11** [comment]
Fixed in fb3eff5 and 1d2a892
