### ISSUE TITLE
Dugong incorrect ballast level

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8030]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Dugong's ballast level is calculated at 0.5213
the nav terminal has the level set to 0.5230

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.16 unsdtable

**Additional information**

**Comment by Regalis11** [comment]
The value displayed in the sub editor is the ballast level at which the submarine is neutrally buoyant; diverging it doesn't mean the value is necessarily _incorrect_. A difference of less than one percent makes no difference in this case.
