### ISSUE TITLE
[Unstable] some issues with new barsuk sub

### ISSUE THREAD

**Issue by LordFrith** [Regalis11/Barotrauma#8032]
- [ yup] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. top docking hatch seems to be unfixable for bots as they fall off ladder when attempting to repair
2. no gap between upper and lower "docking port" hulls
3. toggledocking not wired. cannot dock at the end of a level
4. waypoint issues in the lower part of reactor room, bots get stuck after repairing the engine and cannot get to upper floor to continue work
5. waypoint issue in oxygen compartment. bots get stuck on door and cannot enter
6.front weapon obscured when aiming up. turret clips behind hull section

**Steps To Reproduce**
tested in campaign using Bartok sub.

**Version**
windows 10 barotrauma unstable 0.16.0

**Comment by ConnorsSilverpaws** [comment]
Expanding on 4, waypoint issues with lower fore side
7. Oxygen generator compartment misnamed as Reactor room
8. Depth charge loader isn't linked to the tube

**Comment by danielasteljoki** [comment]
Fixed above issues in 03f236a and 67590be

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
