### ISSUE TITLE
button sprite bleed

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8035]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Button sprite bleed
also the red "button" on it looks pretty bad, fortunately in game you can only see it as like 4 pixels though lol

![image](https://user-images.githubusercontent.com/5103517/149431156-7c2cdf20-9077-403f-a512-746c8d059b0a.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.16 unstable

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8bc4d1322e4f917e16f83c0e8a8d061da7277193

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
