### ISSUE TITLE
Respawn shuttle 19 player server 50% rounds up shows 9/9 to respawn, waits for 10 players (low prio)

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#8039]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is a rounding "error" the counter rounds up when odd number of players are playing and it requires 50% of players so the next shuttle is send. 

**Steps To Reproduce**
Make 15 player server and make minimum players to respawn 50% and it actually needs 8 players to respawn.

**Version**
0.15.23.0

**Additional information**
![Screenshot from 2022-01-15 00-43-49](https://user-images.githubusercontent.com/1114115/149595716-36bee951-dcdd-4dcd-8815-0369b7ce68ff.png)

in this picture illustrated.

I expect it to either say 9/10 or spawn at 9/9

**Comment by Ek-Videogames** [comment]
30% also seems to experience this 'round up' error.
IE, 30% = 4/9 instead of 3/9 , 5/12 instead of 4/12.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f1878c9955aaacd657dd4ee70b972698f422b632

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
