### ISSUE TITLE
Cannot connect to master server

### ISSUE THREAD

**Issue by trolltv7** [Regalis11/Barotrauma#804]
My servers don't work.
![default](https://user-images.githubusercontent.com/43380482/45694943-0a166480-bb69-11e8-9b47-0bfab4ebdeac.png)

**Comment by Regalis11** [comment]
Do you have .NET Framework 4.6 or later installed?

**Comment by trolltv7** [comment]
Oh, thank you so much! It really worked! I just forgot to update the .NET Framework -_-
