### ISSUE TITLE
[v0.16.0.0] Junction box data pins don't work ?

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8045]
**Description**
Signals passed through the 'data' pins `(signal_0,signal_1,signal_2,signal_3)` no longer propagate through junction connections seemingly at all. This issue does not occur on the current stable build v0.15.23.0.

**Steps To Reproduce**
Any sort of signal; logic components, buttons, navigation controls, etc.
![image](https://user-images.githubusercontent.com/55356135/149647657-1ba490fd-1e7c-48cb-9f5d-823bde6a89f5.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2f45eaf199592164204a88de9fb6ab150b1d2d5e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
