### ISSUE TITLE
[v0.16.0.0] Holding an artifact in your hands nullifies it.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8049]
**Description:**
When an alien artifact is equipped in the character's hands - its sound, particles, and active effect ceases as if it thinks that the character's inventory is an artifact container. Artifacts when placed into other devices ( Holders, Deconstructors, etc ) continue to play their effects as intended, seems to only be an issue with character holding ?

**Steps To Reproduce:**
- Procure alien artifact ( in a ruin, in sub editor, or with commands )
- When held in both hands the artifact is completely inert
- When dropped again or placed inside a non-insulating container the artifact functions again

**Other Bug Noted:**
Changes to logic evaluation also seem to have broken the incidental 'shockwaves' particle emitted by the nasonov artifact, 
but all other artifacts appear to function as intended as long as not held by a character.

### **Edit:** Additional logic issue
There also appears to be an issue on both unstable & stable where putting an artifact inside a container during the 0.5 second 'reset' period ( nasonov & faraday ) or a level transition will break the internal logic. Specifically the "OnBroken" status effect not triggering properly, resulting in the condition status never resetting itself again. Using the "fixitems" command to restore the condition of the artifacts will make them start to work again.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/391cd28a81a7585170aea10a4fcbd6c021617eea and https://github.com/Regalis11/Barotrauma-development/commit/d015258aa4636943950a478d71fcff268f855e3a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
