### ISSUE TITLE
Possible bug: 1 grid splits into 2 different grids if there is a relay component in connection between junction boxes

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#805]
Which causes grid load to not spread equally.

I wanted to make a toggleable reactor output using relay component, but the problem is that for some reason grid load on the other end of the component is smaller than the one connected to the reactor.
For some reason parts of the grid that have a relay component in connection between them seem to work almost like 2 different grids.
The reactor seems to only count and produce power for the grid connected to it, but it does not see the second part of the grid(while still sending there the same amount of power that it produced for the first part of the grid), which leads to overload if the grid load of the first one is bigger.
The overload can be kind of worked around by increasing voltage resistance of the junction boxes of the second grid, but that might be a bit confusing for players playing on the sub.

It could also somehow be my own fault. I am not that experienced in sub making. Just in case, here is the sub in question:
[Cyclop 6.zip](https://github.com/Regalis11/Barotrauma/files/2393954/Cyclop.6.zip)

Edit: Nevermind the power lacking problem, reactor seems to actually be adding more power for both grids when there is a need for that(though still seems to give more than needed). But in that case it probably means that it actually can see the second part of the grid? Then i don't really know why it does not spread properly.
I most likely don't completely understand the cause of problem, might have to do more testing.

The whole system starts working fine once i remove the relay component and connect junction boxes directly to each other. There is definitely some problem with the relay component, i just don't know what it is exactly.

Probably related to #329, may be a duplicate.

The most noticeable part is the relay components that are connected to such a low power consuming thing as lamps
![wilson-pc-2018-sep-25-007](https://user-images.githubusercontent.com/38168249/46002455-4b15f800-c0d8-11e8-88c0-b505832eca23.jpg)
It seems like the game only calculates grid load on relay components' power output's side and doesn't add the grid load from their power input's side.

Checked older versions to see when the bug appeared:

0.7.0.1  | No visible issues
0.8.0.0  | The grid load is spreading equally, but for some reason it's twice as big when the reactor is connected to it via relay components
0.8.0.1  | The double grid load bug is still there
0.8.0.2  | The grid load is -2147483648 on my sub(the vanilla ones seem to be fine) everywhere except for relay components that are not connected directly to junction boxes. For some reason even removing the relay components and connecting the reactor directly to the grid does not fix it.
0.8.0.3  | No visible issues
0.8.0.4  | No visible issues
0.8.0.5  | The unequal grid load spread bug appears here            <--
0.8.1.0  | The bug still persists
0.8.1.5  | The bug still persists
0.8.1.10| The bug still persists
0.8.1.11| The bug still persists
0.8.1.12| The bug still persists
0.8.2.0  | The bug still persists

Changelog says there has been a "Bunch of fixes to relay component logic" in 0.8.0.5, so that is probably the change that could cause the issue.
Commits that are possibly related to this:
e15fad6 1255b21 ab99aa9

**Comment by Regalis11** [comment]
Fixed in f4b85b3
