### ISSUE TITLE
"Whatever works" was taken in a wrong way

### ISSUE THREAD

**Issue by Rparvitn** [Regalis11/Barotrauma#8053]
**Description**
In submarine editor I tried to check a maximum immersion depth of my submarine, and at 3000 everybody died, and I took achievement whatever works. I even hadn't anything in my hands, and was watching sonar.

**Steps To Reproduce**
I Don't know, but as far as I remember, that was my 2-nd death at 3000 there, but achievement was taken just in moment of death

**Version**
v. 0.15.23.0 for Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/aeb526ed334f61686bb57bf860653f8ae553db15:

> Don't use the "LastAttacker" to determine the killer when the cause of death affliction has no source. This leads to the killer being determined incorrectly when some other affliction kills a character after an attack: e.g. if you attacked someone with a wrench and they died due to high pressure afterwards, you'd still be considered the killer. Note that this might prevent the killer from being determined if there are cases left where we fail to track the source of an affliction correctly, even though some of these issues were addressed in https://github.com/Regalis11/Barotrauma/issues/7696.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
