### ISSUE TITLE
Strange options of Endworm

### ISSUE THREAD

**Issue by Rparvitn** [Regalis11/Barotrauma#8054]
**Description**
Left tooth has burn damage, right tooth has not.
![image](https://user-images.githubusercontent.com/97904411/149821770-86cf2fd8-dd95-4269-9a50-19836e91452d.png)
![image](https://user-images.githubusercontent.com/97904411/149821808-72f27f96-08e9-495d-8468-2553d2dfefe9.png)

**Steps To Reproduce**
Open creature redactor and see

**Version**
v. 0.15.23.0 for Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/539eb2667ad75e79fc8c7cac562353b722f53eb2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
