### ISSUE TITLE
Oxygenite shards don't work in depth charge shells 

### ISSUE THREAD

**Issue by Anarengon** [Regalis11/Barotrauma#8055]
Just a minor issue, as title says: oxygenite shards don't explode as other explosives do when used in depth charge shells of any type. Unlike in rail shells

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b3a4b5ae27dd1f018ef2fdee396a321a66c3659

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
