### ISSUE TITLE
Disappearing combat suits when looting wrecked diving suit lockers (singleplayer) 

### ISSUE THREAD

**Issue by Hinny** [Regalis11/Barotrauma#8056]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In single player campaign, when wearing combat diving suit or slip suit (possible other suits as well) and double clicking a wrecked diving suit locker, you equip the ordinary suit from the locker but the one you previously worn completely disappears. I have made this mistake twice now costing several hundreds of marks.

**Steps To Reproduce**

-  Start single player campaign
- Equip a combat diving suit
- Find a wreck with a wrecked diving suit locker containing a ordinary diving suit
- Left click the locker
- Double left click the diving suit in the locker
- Watch as you change to the ordinary diving suit and now the combat diving suit is nowhere to be found.

**Version**
v 15.23.0 on a Windows PC.

**Additional information**
Looks like it could be connected to #7709 as this reports that wrecked suit lockers only accepts ordinary diving suits and not other types.

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this. Tested with my hands empty first, in which case the suit went in the hand slots, and then while holding an item, which caused the suit to be dropped.
https://user-images.githubusercontent.com/14351070/150109334-40e9e032-4b58-4913-86e6-7da4e0e48be2.mp4

**Comment by Hinny** [comment]
Would it make a difference if I told you that it happened when we were submerged in water? 

I thought it was just a fluke at first, but when it happened a second time I was sure it was a bug.

Ok I will try again when in a similar situation to see if I can replicate it for a third time (for science).

**Comment by Hinny** [comment]
I couldn't reproduce this bug either. I will close it
