### ISSUE TITLE
[Sub editor group system] Group list shows empty if you enter test mode

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8059]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Entering test mode makes the group list appear empty, only way to get the groups to show up again is to either add a new group to the list or save your sub and load the newly saved sub. 

**Steps To Reproduce**
1. Load up a sub on sub editor and create a group
2. Start test mode and return back to editor
3. Check the groups and notice that the list is empty
4. Create a new group and notice that the old group appears

You can also group the same items as the old group had when its not visible. 

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/7fb1ac31c4e8cee95d9c4952c0dd7409c92dd8ad

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/61ca62bb5372ad4fd0ccb0d432df14147254cfb0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
