### ISSUE TITLE
A small issue with setting railgun's rotation limits

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#806]
Not sure if it's somehow my fault or a problem just on my side, but for some reason when i am trying to set rotation limits for railguns, the numbers i set often change into some other random ones once i click away from the gun.
Feels like it mostly happens when i am working with Y, so to work around that i have to set Y first and only then set X.
When making X bigger than 3 digits, it seems to switch places with Y(when Y is less than 3 digits);
When changing Y, it often makes X 0, but sometimes some other number.
I did not do that much testing since it's not that big of an issue.

**Comment by TheGoldenGuardian** [comment]
I'm pretty sure there's a built-in system to prevent the 2 boundaries from colliding, or something like that.
This just makes it a pain in the ass trying to set the rotation limits correctly cuz you have to remove numbers on one end, but that changes the number drastically, and into the other number, fucking that one up too.

**Comment by BlueTheKing** [comment]
https://undertowgames.com/forum/viewtopic.php?f=18&t=8514&p=119924#p119928

"Enter Y first, then X, and it'll look exactly as you need it."

**Comment by BillCombs** [comment]
I see. I think there should be a hint about that when hovering your mouse above the setting, because i had no idea that it is how it worked. That might be pretty confusing for new players.

**Comment by TheGoldenGuardian** [comment]
It's still an issue that could be fixed entirely.
We need:
_s l i d e r s_

**Comment by TheGoldenGuardian** [comment]
Maybe it be one of those sliders with keyboard input to adjust by single digits :^)

**Comment by BillCombs** [comment]
That would be nice.

**Comment by Regalis11** [comment]
I don't think this is needed anymore now that we have the widgets that can be used to modify the range.
