### ISSUE TITLE
Localization - one string - two names (Russian)

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#8062]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Localization -  a one-string translation. Should be two string for russian.
![Image 001_14-45](https://user-images.githubusercontent.com/93348499/150132126-5aea4154-7ac1-43a4-bbef-f0a796c73917.png)
In the Fabricator and the Deconstructor to produce the text `input` one string is used:
`<uilabel.input>Input</uilabel.input>`
translated in to russian as
`<uilabel.input>Сырье</uilabel.input>`
But that’s the wrong term for `Deconstructor`.

This text should differ depending on the device (at least in Russian).
Two lines should be in charge of the localization of the text:
- First line `input` for the deconstructor
- The second line `input` for the fabricator.

In the Fabricator the "raw material" is placed and the "product" is produced.
In the Deconstructor a "product" is placed and a "raw material" is produced.

Names for type of placed objects should be different.

**Fabricator:**
_Raw material >>> The product
Сырье >>> Продукт_
Should be
`<uilabel.input>Сырье</uilabel.input>`

**Deconstructor:**
_The product >>> Raw material
Продукт >>> Сырье_
Should be
`<uilabel.input>Продукт</uilabel.input>`

**Steps To Reproduce**
Fabricator and Deconstructor
Place - `Input`
In this context, it is difficult to adequately translate into Russian using a same short word.

**Version**
Any. But now v0.15.23.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
For line
`<uilabel.output>Output</uilabel.output>`
this does not necessarily!
Because that thing in the fabricator doesn’t have a name in that place.
![Image 002_14-45](https://user-images.githubusercontent.com/93348499/150132039-93c5fea8-8c86-4d99-b672-74f4e8dcc0d9.png)
But if that changes it’ll be the same issue.

**Comment by Regalis11** [comment]
Added separate texts for these in https://github.com/Regalis11/Barotrauma-development/commit/bbaad79433caa35586c220bd093d9d98299037cc, let's wait for them to be localized before closing this

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
