### ISSUE TITLE
Console error - Failed to parse the string to Vector2

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8063]
**Description**
Upon loading an abandoned outpost level in the campaign, this console error appeared.
![image](https://user-images.githubusercontent.com/59519434/150179421-0ab87f99-6a9a-4e48-a358-169c75b3bfa0.png)
Failed to parse the string "355,39062,3,953125" to Vector2

**Version**
Unstable

**Additional information**
Save:
[Save 11.zip](https://github.com/Regalis11/Barotrauma/files/7899141/Save.11.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/35a8dd12464504ba95b676c42be12596c7e2a3f7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
