### ISSUE TITLE
"Could not connect to server" on joining modded servers

### ISSUE THREAD

**Issue by Speaker15071** [Regalis11/Barotrauma#8064]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
People could not connect to modded servers with heavy mods, when they press "connect" button, they get massive lag, then "Could not connect to server" message appears. No errors in console. At that time people on server see nothing or "Player1 Joined Server, Player1 Disconnected from server" instant messages. That problem often occurs for users with Barotrauma installed on HDD. I suspect that happens because loading lag is too big, so server drops connection. We found workaround for this problem, which works for 1/3 of players: start game with all necessary mods, then disable them in main menu, then try to connect to server without restarting game.
PC specs of user with this problem (can use workaround): Intel core I5 2400 3.1 GHz, 16GB RAM DDR3, Geforce GTX 1050, Game installed on 120GB SSD (Kingston SUV400S37120G ATA). No problems with playing vanilla servers. 
**Steps To Reproduce**
Host heavily modded server(EK + all wrecks,beacons,stations of workshop + barotraumatic full pack + misc fixes of all above), then try to join it with mediocre PC, game installed on HDD.

**Version**
Windows 10, Current stable version

![BUGS](https://user-images.githubusercontent.com/5286113/150209594-1062e788-3d67-4e5b-ac70-4a4a55250f77.png)

**Comment by Regalis11** [comment]
Most likely the same issue as https://github.com/Regalis11/Barotrauma/issues/8891, should (hopefully) be fixed
