### ISSUE TITLE
Bots can't enter drones via ladder

### ISSUE THREAD

**Issue by Ras-Tafari** [Regalis11/Barotrauma#8067]
I have searched the issue tracker to check if the issue has already been reported with no luck.

**Description**
Bots cannot enter drones via docking port with ladder (they say: "Can't get there!") and just stand near the ladder. Happens both in custom subs and vanilla.

**Steps To Reproduce**
Tested it in sub editor and when hosting a casual combat server

1. Use Kastrull sub
2. Tell a crewmember to follow you and enter the drone.

**Screenshots:**
Kastrull:
![image](https://user-images.githubusercontent.com/4569855/150343168-a05cc50f-134a-45b1-9698-377d8bb7586b.png)
My own sub:
![image](https://user-images.githubusercontent.com/4569855/150343222-4a9fa62e-3f7d-4eed-ad16-bd134c43d062.png)

Remora works fine:
![image](https://user-images.githubusercontent.com/4569855/150343273-50ff9223-506f-4495-9d75-fea65a6f2933.png)

Version
v0.15.23.0, revision 0a990787e8, Steam and Windows 10

**Comment by itchyOwl** [comment]
Seems to be broken since 28d023c (Merge ruin-monsters into dev). Not necessarily a pathing issue, because the bots can find a path and follow it when the end hull is not the biggest hull in the Kastrull's drone. Need to test withdifferent drones. I'll look into it later.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8970261ffbb3cfc66d97930e86a5c7c5d5328e6b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
