### ISSUE TITLE
Sprite Depth of machines can sometimes have items drop behind them.

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8073]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Since many machines like deconstructors have the same sprite as most items (0.8), sometimes/on some subs? dropping items from the machines/placing items "on" the machine will have the item appear in the background of the machine / the machine will win the Z-fight.

Preferably, machines would be further back, like 0.81, so that this can't occur.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
> Since many machines like deconstructors have the same sprite as most items (0.8)

It appears most items have their depth set to 0.5; the only ones set to 0.8 I could find were the electrical components. Could you give some examples of the items you've noticed this issue on?

**Comment by Tsunder** [comment]
Ah, then I was biased somewhat since the most commonly placed item I place in sub walls are signal components, sorry!

for the purpose of this bug report;
wiring/signal Components sprite depths,
Explosives sprite depth is 0.8 (they can't be attached to walls except in a detonator, but don't they then take on the detonator's depth?)

(also pet ID / ID cards apparently are 0.8)

can items have a different depth when dropped loosely vs attached to walls ?

**Comment by Regalis11** [comment]
Thanks for the clarification! Atm it's not possible to make the items change their depth when attached to a wall, but I think we'll need to add that option to fix this; it'd look weird if signal components attached to walls were drawn in front of the devices.

**Comment by Regalis11** [comment]
Fixed ID cards and pet name tags in https://github.com/Regalis11/Barotrauma-development/commit/7eb3982da607d2af9bc38392a9e9615ca82115e2

And signal components in https://github.com/Regalis11/Barotrauma-development/commit/85d5c17910cf6998fdf8e7968a8b3ea53d2f4ae0
