### ISSUE TITLE
R-29 update

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#8074]
I made a number of changes to the submarine, as well as fixed a few bugs.

1. Overhaul of electrical wiring. Almost all relays that were hidden in the walls are now available for modifications to players. The battery connection scheme has been changed. Now all three work through one relay.
For all junction boxes set the same overvoltage value to 1.7 (it used to be 1.8 for some boxes).
2. Changes have been made to the design of some compartments. I hope I didn't overdo it with the number of structures.
3. A hatch repair platform has been added to the upper airlock. Added waypoint to lower airlock. Added waypoint to lower airlock. https://github.com/Regalis11/Barotrauma/issues/8009
4. Turned on the "No AI target" flag for the lower part of the bow of the submarine. There will probably be problems with monsters getting stuck with the upper part, so only for the lower part. https://github.com/Regalis11/Barotrauma/issues/7899
5. Discharge coils are now controlled separately.
6. The bulbs at the discharge coils are synchronized through an oscillator.
7. Added spawnpoints for passengers.
8. Unlocked editing of all light bulbs.
9. Replaced old pumps in airlocks.
10. Changed the content of diving cabinets. The hidden panel from the engineering compartment has been moved to the stowage compartment.
11. Changed the scheme for switching between cameras at the periscope. Does not work! https://github.com/Regalis11/Barotrauma/issues/8075
12. Hull of the Cargo Bay was divided into two by analogy with the Humpback.

[R-29-dev.zip](https://github.com/Regalis11/Barotrauma/files/7918341/R-29-dev.zip)

V 0.16.0.0

**Comment by danielasteljoki** [comment]
Received and applied.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
