### ISSUE TITLE
Switching between cameras and spotlights is broken.

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#8075]
In the unstable version, switching between cameras by pressing LMB at the periscope does not work. To verify this, try using the periscope on the R-29 bridge.

V 0.16.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c5ff5f8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
