### ISSUE TITLE
Ballast Flora present in re-bought shuttle. 

### ISSUE THREAD

**Issue by ralfbiedert** [Regalis11/Barotrauma#8076]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A shuttle that had Ballast Flora and was ditched will still have Ballast Flora when re-bought next outpost. 

**Steps To Reproduce**
- Have main sub with shuttle
- Get Ballast Flora in shuttle
- Abandon the shuttle somewhere on the map
- Next outpost go to upgrade dealer, and replace lost shuttle

Now, the shuttle will still (again?) have Ballast Flora. This could, of course, be explained if the vendor went back and retrieved the shuttle, but the button says "Replace Lost Shuttles", so I assumed I'd get a new one. 

**Version**
`0.15.23.0`

**Additional information**
Might be related to #5874

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e324c11a23eb59263ed9c79737ecc072f450921

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
