### ISSUE TITLE
Dragging a body through docking pathways causes it to get launched away at high speeds

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#809]
Or when just falling in there in ragdoll mode.(though it does not happen as often as when somebody is dragging the body)
Might be a pretty serious issue, since it seems to happen on vanilla subs as well(Aegir mark III, not sure if other ones even have a shuttle).
Not only it is harmful and sometimes deadly to the body who is being dragged, but it also damages the submarine in some cases.(at rare times it makes even more damage than 2 boxes of nitroglycerine(seriously, it can potentially destroy the whole submarine, it should be fixed asap))

**Comment by thegrb93** [comment]
Maybe related to https://github.com/Regalis11/Barotrauma/issues/742

**Comment by Regalis11** [comment]
I believe this was partially fixed by fec7740, although I haven't been able to reproduce it when falling through the docking port in ragdoll mode.

**Comment by BillCombs** [comment]
The part with falling happened in multiplayer. It could be caused by lag or, perhaps, is not actually because of falling.  I assume it could either be really rare or perhaps somehow is not really what it looked like. It could be some kind of desync; i could be actually getting dragged on server side while just falling on client side(i don't have any friends who play this game so i only managed to get a chance to test it in multiplayer for a single time with a random player).

Perhaps the only cause of the problem was getting dragged, so i assume this can actually be considered completely fixed.
