### ISSUE TITLE
Submarine crush depth displayed incorrectly after switching the sub

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8090]
- [x] I have searched the issue tracker to check if the issue has already been reported.

Hull durability upgrades aren't taken into account in the crush depth displayed after switching the sub.

**Steps To Reproduce**
1. Purchase hull upgrades
2. Check the crush depth on the campaign map
3. Purchase and switch to another sub
4. Check the campaign map again: the crush depth warnings now display your sub's crush depth as 3500m, even though the hull durability upgrades carry over to the new sub and increase it higher than that.

**Version**
v0.15.23.0, most likely earlier too

**Comment by Wheatley1001** [comment]
I know this ticket hasn't been closed but I am reporting that it exists in 100.5.0.0. It caused quite a bit of panic amongst the crew once we saw this.

![image](https://user-images.githubusercontent.com/105495756/202923365-7b659504-2712-4efd-9727-254d181a60e0.png)

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@a0ce391

For testing, also try to

1. purchase the upgrade
2. buy and switch to a new sub
3. leave the outpost and return immediately
4. check the map
5. switch to the first sub and check the map again

**Comment by Regalis11** [comment]
Tested with both repro steps, no issues found. Also gave a try at switching from a maxed tier 2 sub to a tier 1 (clamping the hull upgrades from 4 to 2), and the crush depth was displayed correctly for the tier 1 sub.
