### ISSUE TITLE
The medical clinic sometimes shows non-existent afflictions

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8091]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Entered the medical clinic, treated the crew, but it still shows an icon for the bloodloss affliction.

![health_interface.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/00fa4fff-4e38-4aa1-959b-d153aa25104e)

I think it's because the character has an affliction with a strength lower than prefab.ShowIconToOthersThreshold. So we should probably use that instead of zero?
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/5d2f832a-46b5-4f0d-a3d4-8113f9b7a9b4)

**Steps To Reproduce**
- "giveaffliction bloodloss 4" in the console
- enter the medical clinic

**Version**
0.16.0.0 Release build, Regalis11/Barotrauma-development@2b9a05a (monster-variants).

**Comment by Regalis11** [comment]
The changes I did in https://github.com/Regalis11/Barotrauma-development/commit/4bea08d6433386af2c1d0aeb98b850b72ced8490 to address another issue seem to have fixed this too

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
