### ISSUE TITLE
AI is unable to open doors when the button does not connect directly to the door

### ISSUE THREAD

**Issue by ransomname** [Regalis11/Barotrauma#8093]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had buttons going into a logic, which set relais which then set_stated doors. the buttons where able to togge_state the relais. AI wasnt able to open the doors, but could use the path normally when they were already open. i resolved the issue for the doors in question, but it would have been much cleaner to have all the logic in one place. also, because the room was so cramped, i first thought it was a pathfinding issue until trying to let the buttons go directly into the doors. maybe it would be a good idea to just let the bots use either buttons connecting directly to a door and then if there aren't any, just use buttons that are item-linked to the door they want to use.

**Steps To Reproduce**
have a button not connected directly to a door but to a logic connected to the door.

**Version**
0.15.23.0 (Windows).

**Comment by Regalis11** [comment]
The bots should be able to use buttons that are connected to the door through some kind of a circuit too, and we in fact use that kind of buttons in vanilla subs with no issues. I suppose it's a problem with some specific kind of circuit - would it be possible to send us a sub file where we could give this a test?

**Comment by ransomname** [comment]
sure. the problem happens in all the doors/hatches in both airlocks. i hope the upload works, i just crudely changed the extension  to gif to be able to upload it here. if theres a better way let me know.
![CachalotWaypoints sub](https://user-images.githubusercontent.com/24641427/150945673-a18d4810-4f4d-4425-bb9b-a00558382301.gif)

**Comment by Regalis11** [comment]
Another way to attach sub or save files here is to zip them first, but that works too, thanks!

It seems the reason why the bots fail to figure out which buttons control the doors is that the signal from the button doesn't go directly through the circuit to the door, but controls whether the door can receive signals from another source. I'll think about a way to solve this (ideally the bots would be able to figure it out automatically without having to link the button to the door).

**Comment by ransomname** [comment]
i just tested properly and my fix for the upper airlock doesnt work. i do in fact need the relais there for the logic to work as intended. lower airlock is fine.
![Cachalottest sub](https://user-images.githubusercontent.com/24641427/150953241-1e440391-bddc-4b92-81e1-e46953e42214.gif)

**Comment by ransomname** [comment]
Interesting! Thanks for the quick reply and taking on the issue btw :)

**Comment by Regalis11** [comment]
I tried to come up with a way to determine the correct button automatically, but that turned out to be really complex (and still probably wouldn't work 100% reliably with all kinds of circuits or circuits with multiple buttons controlling the door in different situations), so I decided to take the easy route and made the bots use buttons linked to the door if they can't find one automatically based on the wiring: https://github.com/Regalis11/Barotrauma-development/commit/3b35d3daf92daa16a54220ad3da5d74c193cc1ae

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
