### ISSUE TITLE
Some guardian pods can't be destroyed with a trinket

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8096]
Most pods work as they should, but not all. ![pod.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/3815db8e-0149-4d81-b936-dd6f1b538f18)

**Comment by danielasteljoki** [comment]
Wiring seems to be correct, but I couldn't destroy any pods via terminals. Tested in Alien_Chambers4Way

**Comment by itchyOwl** [comment]
Maybe related to the status effect optimizations, as it used to work. Assigning @Regalis11.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2313893f733629b4158bd91a7823c203415b7902

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
