### ISSUE TITLE
Indicate when the bots are following someone else than you

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8097]
Currently it's not indicated anywhere when a bot is following another character than you. Especially in single player this is a bit problematic, because you can change the characters.

Let's change it so that the color of the icon changes to gray when the bot is following someone else. Might be a good addition to multiplayer too.

A quick and dirty implementation added in Regalis11/Barotrauma-development@f3f5f5a.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/f445f0cc-02dd-416c-abfe-4a8c1817f51e)

**Comment by ekqvist** [comment]
Also related: adding the followed person to the tooltip (Regalis11/Barotrauma-development#3097)

**Comment by ekqvist** [comment]
Modified the implementation in Regalis11/Barotrauma-development@5215925. It should now also work in multiplayer.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
