### ISSUE TITLE
Good idea.

### ISSUE THREAD

**Issue by trolltv7** [Regalis11/Barotrauma#810]
How do you like the idea of rapid movement of inventory to any container holding any hot keys? This hot key can be configured in the settings accordingly.

**Comment by Regalis11** [comment]
Already added in the dev branch :)

![asdfasdgdfg](https://user-images.githubusercontent.com/14351070/45817602-f6453c80-bce7-11e8-98f4-70b8de710449.png)

**Comment by trolltv7** [comment]
Oh yay!
