### ISSUE TITLE
Salvage Artifact mission spawns outside of game bounds.

### ISSUE THREAD

**Issue by rubeste** [Regalis11/Barotrauma#8102]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The artifact I am supposed to collect is impossible due to it being out of bounds (The current is too strong).

**Steps To Reproduce**
Due to the highly randomized nature of spawn mechanics, I am not sure how but I have the following:
- I have two Salvage Artifact missions. One spawned in an Alien ruin.
- I have enabled mods. (although I don't think it should affect the spawn behavior.)

**Version**
0.15.23.0

**Mods**
- BaroDrama Diving Suits
- All The Talent Trees
- Genes+
- Aegis (A sub)
- Bronze Age 1.0.0 (Another sub)
- Improved XP Rates
- Alarms Extended

**Additional information**
![image](https://user-images.githubusercontent.com/28504874/151186394-445e2f0a-fa91-445e-b2aa-786cbee7f8ca.png)

**Comment by Regalis11** [comment]
Do you still happen to have this campaign save saved? If you could send it to us here, it'd help us a lot in diagnosing this.

Thanks and sorry for the trouble!

**Comment by rubeste** [comment]
As a matter of fact, I do.
[broke.zip](https://github.com/Regalis11/Barotrauma/files/7943916/broke.zip)

**Comment by Regalis11** [comment]
Thank you, I was able to diagnose this now! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c748bb60bf9ac97fe74a5e2b821baeb3888c279c

**Comment by rubeste** [comment]
No problem.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
