### ISSUE TITLE
[Unstable] Herja issues 1

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8103]
- [x] 1) Top docking port power not wired
![image](https://user-images.githubusercontent.com/59519434/151198659-7783013c-e247-4108-8e86-0407d65562e6.png)
- [x] 2) Chaingun ammo rack has coilgun boxes in it
![image](https://user-images.githubusercontent.com/59519434/151198857-48ddea18-8f3c-488a-aac3-ec0f9785d77f.png)
- [x] 3) Wall doesn't extend over this hull boundary
![image](https://user-images.githubusercontent.com/59519434/151202071-11a49a31-2793-4a7a-b283-8bab45d89698.png)
- [x] 4) Weird background wall
![image](https://user-images.githubusercontent.com/59519434/151211213-99b8607a-8bfd-40a3-9b82-3539c8f7326a.png)
- [x] 5) Duct is 90° rotated in the reactor room
![image](https://user-images.githubusercontent.com/59519434/151213698-93f4ef3d-5c0d-487e-82e0-e41862c3f47d.png)

**Comment by Udrakan** [comment]
Also, the rear coilgun can shoot directly into the engine room. It's more of a potential griefing problem than an actuall issue.

**Comment by Udrakan** [comment]
The airlock design is such, that when pirates shot a couple holes in it, we couldn't exit the sub and should the wiring be disabled on the server or should we be new players who don't know how to wire, we would be locked inside our own submarine, unless we cut our selves out. We had to rewire it to a standard design of the other vanilla subs.

**Comment by aeondez** [comment]
None of the guns are loaded

Supercapacitors start empty and with a recharge rate of 0%

**Comment by ubertpendragon** [comment]
You do NOT want the discharge coil to be triggered by a simple motion detector

![image](https://user-images.githubusercontent.com/73229309/151252527-69e9da56-c95a-4813-8526-87e1fafaab60.png)

This is what a single crawler at the front does to supercapacitors: 
From 100% charge to 0% in one second

![image](https://user-images.githubusercontent.com/73229309/151252542-d35b56c0-399b-4a43-a314-062e8847b514.png)


Not only the motion detector is missing a false output, the discharge coil will fire every 0.25 seconds as long as there's a monster in front of the ship. 

To prevent this you need a "cooldown" on the discharge coil

Here is Astraltor's auto-discharge coil, with a 10 second cooldown between zaps:
[Auto-dischargecoil.zip](https://github.com/Regalis11/Barotrauma/files/7946094/Auto-dischargecoil.zip)

![image](https://user-images.githubusercontent.com/73229309/151259205-331bce2b-f839-4613-8778-12dfe38a3d20.png)

**Comment by Udrakan** [comment]
Yea, the supercapacitors got drained instantly when a crawler came to our nose during today's test session. Either a separate supercapacitor, or better yet the cooldown system provided above should be added.

**Comment by danielasteljoki** [comment]
Fixed in 4c5d614. Decided to nix the discharge coil.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
