### ISSUE TITLE
[Unstable] Winterhalter issues

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#8104]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Winterhalter issues

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Unstable 0.16.1.0

**Additional information**
Unrepairable pump in lower cargo room (blocked by stairs):
![image](https://user-images.githubusercontent.com/21000916/151231570-ab17c2b7-de7f-4534-81b0-c7142042c6eb.png)

Missing wall in research room:
![image](https://user-images.githubusercontent.com/21000916/151231708-466c95e8-1165-4b1e-98fb-7bb8bd40d5ec.png)

**Comment by aeondez** [comment]
Bottom rear coilgun firing arc can hit the sub:

![image](https://user-images.githubusercontent.com/21000916/151232488-20577b22-3379-481f-87f3-163ad267ddec.png)

**Comment by aeondez** [comment]
Supercapacitors initially set to 0% recharge rate:

![image](https://user-images.githubusercontent.com/21000916/151232620-fb4864cd-9719-4a09-9eb7-a218ec0585df.png)

**Comment by aeondez** [comment]
Toxin cabinet only accessible by Medic: 

![image](https://user-images.githubusercontent.com/21000916/151232741-c81ae1ef-2402-484d-be01-5e6cd6f95c00.png)

**Comment by aeondez** [comment]
Captain spawns in lower section of sub when you'd expect the captain to spawn near the navigation terminal:

![image](https://user-images.githubusercontent.com/21000916/151232839-952e6e4f-4f5a-4640-b335-ec37c19da35d.png)

**Comment by aeondez** [comment]
From UberPendragon:

-Emergency light switches don't work (bunch of switches on a single relay)
-Batteries are wired to the electrical circuit both ways, no toggle (battery drain and recharge at the same time)
-Docking port power not wired
-No light in ballasts
-Bottom airlock is a death trap if flooded
-Engine room is huge, sinks the sub (design)
-Bad bilging power in both engine room and research ballsack (design)

**Comment by aeondez** [comment]
Partially exposed door components in lower section:

![image](https://user-images.githubusercontent.com/21000916/151234357-34ea4723-a817-4e4b-b1bd-c19af17cb22d.png)

**Comment by ubertpendragon** [comment]
Here is my attempt at fixing most of the above problems

![image](https://user-images.githubusercontent.com/73229309/151233892-a2fe3788-8c1f-4be6-9c6b-ac4521eee122.png)
[Winterhalter fixes 2.zip](https://github.com/Regalis11/Barotrauma/files/7944719/Winterhalter.fixes.2.zip)

The most radical change is the engine room; I tried to really cut down the amount of potentially floodable hull. Separated it in two, reduced the total hull size, shortened the sub a little

When the vanilla hinterwalter engine room is flooded, **the sub sinks at a record 26 km/h.** 
With this new engine room, flooding the back only makes it sink at 6 km/h

The gunnery room also has this issue of being a very large room so it's worth taking a look at it and maybe separating it in two

**Comment by aeondez** [comment]
Assistant spawnpoint in research lab causes assistant to spawn in the floor. Bots are too dumb to escape by ragdolling. Suggest moving spawnpoint # 626 up or down half a floor:

![image](https://user-images.githubusercontent.com/21000916/151274716-c620bac0-2fa8-4767-af23-5f504252061e.png)

**Comment by aeondez** [comment]
"Intruder repellant" button is not in a logical place:

![image](https://user-images.githubusercontent.com/21000916/151275457-917e587e-eda9-4073-a5f5-73934a49471e.png)

**Comment by aeondez** [comment]
There are no duct blocks on the Winterhalter.

**Comment by aeondez** [comment]
Missing gap between Navigation and Gunnery decks:

![image](https://user-images.githubusercontent.com/21000916/151278648-c985f863-7317-44c1-a5f0-29ff9cd8aaa7.png)

**Comment by aeondez** [comment]
Hull health is set to 200 (compare with existing Vanilla subs, which are all at 100)

![image](https://user-images.githubusercontent.com/21000916/151281020-47f7e413-b4ae-4ca5-8698-071dc55e5195.png)

**Comment by ubertpendragon** [comment]
I'll keep updating my fixed version with most of these in mind

**Comment by danielasteljoki** [comment]
Fixed in 4c5d614

**Comment by Udrakan** [comment]
I don't mind the low bilging power in engine and research module in our campaign. As a mechanic, I tinker these pumps and utilise portable pumps to drain them much quicker and that feels pretty impactful.

**Comment by ubertpendragon** [comment]
> I don't mind the low bilging power in engine and research module in our campaign. As a mechanic, I tinker these pumps and utilise portable pumps to drain them much quicker and that feels pretty impactful.

Portable pumps have 10x the draining power of a small pump, "solving" a bad bilge because you've increased the pumping power ten fold doesn't really sound reasonable.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
