### ISSUE TITLE
[Unstable] Hair clips through hats and caps

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#8105]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Certain hairstyles clip through some hats and caps.

![image](https://user-images.githubusercontent.com/15182031/151240056-5182d28a-92fe-4f0c-bffc-582999f000ea.png)

**Version**
0.16.1.0 (Unstable)

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/a665fb94e7086949201dcec6ba74214b61006eb4

**Comment by Rokvach** [comment]
The hair is z-fighting with the hats now, easy to notice if you look at the hat and move around, for couple frames the hair is rendered on top of it.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
