### ISSUE TITLE
[Unstable] Barsuk airlock won't open when leaking

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#8106]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Soft-lock; stuck inside Barsuk, as airlock does not open when there is a leak in the airlock. Can't get into airlock to repair without crowbar, plasma cutter, or re-wiring the door.

**Steps To Reproduce**
Cause enough damage to the airlock when inside the Barsuk to cause a leak. Monsters can do this, or you can take a plasma cutter and one person outside, then switch to a different person and try to open the airlock from the inside.

**Version**
Unstable 0.16.1.0

**Additional information**
There should be an emergency override for the airlock. Also, bots get stuck trying to fix it, which is impossible without draining it first.

If this is intentionally designed to be a known issue with the sub (for flavor or whatever), then feel free to close this.

**Comment by Udrakan** [comment]
Same as Herja's. Those airlocks don't feel good at all. There should be an override lever or something, if devs want to have an airlock that prevents you from opening it if water is there.

**Comment by danielasteljoki** [comment]
Changed airlock functionality in 9633d40 and bc565b7. Simpler is better here after all.

**Comment by Rokvach** [comment]
Tested, no issues. closing.
