### ISSUE TITLE
[Unstable] Lights are ON even if they're OFF

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8107]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Lights are on, even if you uncheck "Is On"

**Steps To Reproduce**
Launch sub editor
Place down a light component
Make sure it's off
Launch test
Light component is on

This is true for all items that have the "Lightcomponent" property

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd306cc715d13852529399b8e65b60c1ac7ab920

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
