### ISSUE TITLE
Irregularly shaped Ballast Fill Issue

### ISSUE THREAD

**Issue by Pspritechologist** [Regalis11/Barotrauma#8108]
Ballasts made up of multiple hulls in a shape other than a rectangle do not fill properly, most often affecting NBL. The pump only checks the fill level of the hull it is placed in, and thus ignores how filled the rest of the ballast might be.

To reproduce, simply make a ballast of two or more hulls in any shape other than a rectangle. If the pump is not placed in the tallest of the hulls, the ballast will not fill to the top. Regardless of what hull it is placed in, it will not correctly fill to any given percentage.

This occurs in version 0.15.23.0, and I am using a Windows 10 PC.

A series of components can fix the problem for now by manually detecting the fill level of the entire ballast.

**Comment by Udrakan** [comment]
Unstable has Herja with irregularly shaped ballast. Might be worth checking it there.

**Comment by Pspritechologist** [comment]
> Unstable has Herja with irregularly shaped ballast. Might be worth checking it there.

Yep, just tested now, it floats up at -3km/h at NBL. Good catch, that's now an actually mildly broken "vanilla" (unstable) sub due to the bug. Makes me wonder if there are anymore with unusual ballasts in the base game.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a8cdc6e33c88f1c38a300ab3649c9c30893fcabb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
