### ISSUE TITLE
enablecheats are more or less required to do submarine testing

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8115]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
enablecheats is more or less required for comprehensive submarine testing (item/monster spawning, debugdraw, damage testing, etc etc)

would be nice is cheats didn't need to be enabled for these commands in test/editor mode

**Steps To Reproduce**
1. try to thoroughly test a submarine without cheats

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
~~or better yet a GUI (in visual basic)~~

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f7c5e8443a491d37d537bea474730c765965fa76

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
