### ISSUE TITLE
Mirroring Sub causes bigger/longer "Add submarine" preview line

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8116]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
[50L1-TUD3 Transportation.zip](https://github.com/Regalis11/Barotrauma/files/7960264/50L1-TUD3.Transportation.zip)
![Capture](https://user-images.githubusercontent.com/5086682/151585668-ca5e087f-4d04-4bda-a53b-543aa6b58969.PNG)

So I made a shuttle and simply flipped it. For some reason the Leftey shuttle has a bigger ghost preview than the original shuttle.

**Version**
~0.16.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d31cc0bfc5db8f5652980daf412db047bad6434

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
