### ISSUE TITLE
Please make docking ports set to 'hidden in game' also invisible on the sonar screen.

### ISSUE THREAD

**Issue by ReconDoge** [Regalis11/Barotrauma#8117]
Docking ports have been shown to be far more versatile than simply as a means for docking between submarines. They can be used to create dynamic elements within a sub such as elevators, sliding doors and turrets, as well as shuttle dry docks. 

By allowing docking ports to be effectively hidden, these mechanisms will become less clunky and more feasible than they are currently. Also, if possible, an option could be added to disable the particle effect and sound when docking. This will be greatly appreciated by sub builders who are trying to include more innovative contraptions on their subs.

**Comment by rav2n** [comment]
Since we are talking about creating moving elements, it would be nice if there was an opportunity to turn off their display on the sonar.

**Comment by MaaiG** [comment]
I agree.
> creating moving elements

Also, it would be good if special tools were created to create such [moving devices!](https://github.com/Regalis11/Barotrauma/discussions/7432})
Solving these problems with moving devices has significant technical limitations if you use docking ports.
In this case, the docking ports are not used for their intended purpose and this is more like a duct tape solution (FIXME).

> shuttle dry docks.

Whatever that means... Problem not solved but [marked as Bug](https://github.com/Regalis11/Barotrauma/issues/6362).
Hope doesn’t die, does it?

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/a1e5f56c9404054ecb0735bcd87a78d727838aaf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
