### ISSUE TITLE
Server Profanity Block Redundancy

### ISSUE THREAD

**Issue by Pspritechologist** [Regalis11/Barotrauma#8118]
When starting a server with profanity in the name and set to private only, the game still warns you the server will not be listed publicly. This is a mild inconvenience for people who name their servers dumb things, knowing only their friends will see it, and is somewhat unintuitive as the server would not be listed publicly either way.

To reproduce, simply host a server with profanity in the title and with "Public" disabled.

This occurred in version v0.15.23.0, on a Windows 10 PC.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/64ffe69db42c696e17b67265f541d6e902984c4e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
