### ISSUE TITLE
Sub Pricing in Multiplayer

### ISSUE THREAD

**Issue by Pspritechologist** [Regalis11/Barotrauma#8119]
When starting a multiplayer campaign, the sub price is taken into account when determining starting funds, but there is no way to view sub price within the server lobby. It is also unclear that this is happening, as their is no upper limit to the cost of a sub you can start with, but rather a lower limit to the funds you can start with. This is very unintuitive, especially considering that there are only 2 base game subs cheap enough that you're supposed to be able to start with them.

Start a multiplayer lobby, select a new campaign, and begin selecting your starting sub. The amount of marks you begin with will fluctuate, bottoming out at 500, but with no other indication as to why this might be happening, or what the price of the subs you're looking at are.

This occurred in version v0.15.23.0, on a Windows 10 PC.

Allowing you to start with any sub is good for a multitude of reasons, but the ability to enforce starting funds would be very nice as a server option.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/5aac70462b9a6ba74ab9ec75df64826647b5c217 by adding the price to the submarine's specs window, although we should also consider indicating more clearly how the starting funds are calculated and maybe add a way to adjust them as you suggested.

**Comment by Rokvach** [comment]
No issues, closing.
