### ISSUE TITLE
Crash when controlling any creature

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8121]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to control a creature crashes the game, happened with swarmfeeder and doomworm so far
[crashreport (58).log](https://github.com/Regalis11/Barotrauma/files/7964126/crashreport.58.log)
[crashreport (59).log](https://github.com/Regalis11/Barotrauma/files/7964127/crashreport.59.log)
[crashreport (60).log](https://github.com/Regalis11/Barotrauma/files/7964237/crashreport.60.log)

**Version**
unstable v0.16.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cc8c5289a95269ca8c0b583bc3740b3da7ee547a

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
