### ISSUE TITLE
Wrong talent point behavior (free talent points) for engineer

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8128]
**Description**
Situation: Singleplayer unstable campaign
I dock at an outpost after a finished mission, get 1 talent point for engineer.
If I select 1 talent, Apply button is gray. Image:
![image](https://user-images.githubusercontent.com/59519434/151702626-53ed280f-9109-475b-9b05-f9c26e1ca583.png)
If I select entire talent tree, Apply button works and applies talents, despite only having 1 talent point.
Video:
https://user-images.githubusercontent.com/59519434/151702299-c334442e-b185-48be-9df1-cff52d8a0914.mp4

**Steps To Reproduce**
Unknown

**Version**
Unstable

**Additional information**
Save:
[Engi Talent Bug.zip](https://github.com/Regalis11/Barotrauma/files/7966009/Engi.Talent.Bug.zip)

**Comment by Udrakan** [comment]
No endocrine boosters were used in the entire campaign.

**Comment by Regalis11** [comment]
I suspect this is yet another case of All-Seeing Eye messing up the talent point calculations, but I couldn't find a way to repro this even with the save provided. Tested by gaining enough xp to unlock All-Seeing Eye, unlocking it, and then gaining more xp to get another talent point, and everything seemed to work as expected:
![image](https://user-images.githubusercontent.com/14351070/151783448-e5853506-446e-487e-936c-985f2a731b21.png)

**Comment by Cherman0** [comment]
I also have a singleplayer save with this bug. I had heard about a bug that makes you need to level up enough to make up for the free levels from all-seeing eye, so I just kept playing for 4 more level ups, assuming that things would start working again at the 4th level (having gotten 3 to repay the 3 "free" ones from all-seeing eye). It still does not let me pick any talents, even though it lets me select the whole tree and I have enough talent points to get every remaining talent. Selecting a talent also doesn't show the (-1) indicator for the talent point counter or enable the reset and apply buttons.

![20220218195314_1](https://user-images.githubusercontent.com/99766513/154779583-388ce241-a1b6-477c-8100-fcfd5203bec2.jpg)

This is the save file exhibiting the bug. It does use a custom submarine, but that probably isn't relevant and there are no other mods.
[AllSeeingEyeBug.zip](https://github.com/Regalis11/Barotrauma/files/8101163/AllSeeingEyeBug.zip)

**Comment by Regalis11** [comment]
Thank you! I was able to repro and (hopefully) fix this for good now https://github.com/Regalis11/Barotrauma-development/commit/ae990ff9e1243948d55cbb61e0fe7edd754d098e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
