### ISSUE TITLE
Fps drops because of using arrows as controls instead wasd in character editor.

### ISSUE THREAD

**Issue by ValentinMel** [Regalis11/Barotrauma#8133]
So, i am usually playing games using arrows because wasd is not very comfortable for me. I went to the character editor and tried to control unmodified endworm with arrows. And my fps fell from stable 60 to 12. 
When i changing controls from arrows to wasd everything works fine, and endworm doesn't give any fps drops, but even in this situation if i press any arrow buttons fps still fall down to 10 -12 fps. I not sure, but i think sometimes i have the same issue in main campaign when i control a standart human. i have this problem on 0.15.23.0 and on 0.15.22,1. Disabling mods doesn't help.
Also i have a suggestion. Could you please add possibility to change controls in editors. Cause when i trying to move an object using arrows i also moving my camera. So it is possible to do something in editor only on wasd as controls and nothing else.
That wasn't very pleasent experience when i created to create my own boat and tried to debug it with constant controls changing.
But after all i still like creating my own boats, thanks for this possibility.

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this: using the arrow keys doesn't seem to cause any performance hit on my end. :/

Does this happen in some specific situation, like when you have some specific panel open in the editor?

**Comment by ValentinMel** [comment]
I am starting the game, then i go into the character editor, and i see a standart human. If i controlling him using any arrow keys then fps is normal but my 2nd cpu core is starting to load up to 40% as long as i press one of the arrow buttons. when if i am not pressing anything it's about 4-6%. 
Then i choiсe endworm in the character bar and again press and hold any of arrow keys, then i see 10 fps and my second cpu core is loaded up to 88%. Nothing is pressed in options, show and edit bars.
I even set all my controls back to classic with wasd and retest again. And i still have this problem. Press and hold any arrow keys in character editor increases cpu load and gives low fps.
I checked in the campaign and all works fine with no high 2nd cpu load and it doesn't matter if im using wasd or arrows to control the character in campaign. All characters is standart i didn't modified any of them. And also i cannot see this problem in boat editor.
I am gaming on windows 10 with latest updates and all drivers is updated. I have i7 9700k(8cores) 32 gb of ram and rtx 2070.

**Comment by ValentinMel** [comment]
> I'm afraid I could not find a way to reproduce this: using the arrow keys doesn't seem to cause any performance hit on my end. :/
> 
> Does this happen in some specific situation, like when you have some specific panel open in the editor?

So have you found something? I actually found another bug. It's about audio. When i am playing the game i can always hear "Click" when ogg audio track ends and start to loop again. This is most annoying when i stand near ventilation or oxygen generator or when i am using plasma cutter.
I even can hear this click in windows when i am listen vetilation.ogg with loop mode in barotramafolder/content/items/oxygen generator.
I am not sure if this is only my problem. I tried to disable sound comprasion but it doesn't help. 
Actually i read about this click. And it happens when you trying to loop track but the start an end of this track doesn't have 0 volume or something like this :) 
Audio editors usually have "snap" function. It prevents "Click" that you can hear at the end of the track when constantly loops. Guess those who created the sounds for you doesn't use thIs function. I even download to ableton this ventilation.ogg and yes this track definitely doesn't use snap function. I tried to fix this bug by my self and i even could change the file and apply this snap function but i couldn't save this file back to ogg. This is because i am not a professional in ableton, or maybe i just need another app for this.
And i found lightning bug when lights from outside of the boat can go to the boat if the wall is curved. There is a screenshot of this.
<img width="1280" alt="light bug" src="https://user-images.githubusercontent.com/93443384/153276670-95e9b038-6fe7-4dd3-ade0-aedea180e1b6.png">
By the way bots sometimes can avoid waypoints if they outside of the boat. They just keep float straight to the bottom wall of the boat like if there is an entrance. And Sometimes they even tring to float up to the open sea. This usually happens when i explore caves with 2 bots. i chain both of them with "follow me". so i can constantly change from one to another bot. And sometimes when i am doing this change, they starting to float away from me even if they have follow me instruction.
I think this is because the mission "find cover" is a bit broken. I guess they trying to float to the nearest outpost even though the whole level. But the only cover for them have to be the boat. And they definitely shouldn't listen to this mission when they have follow me instruction.
So it's 4 bugs in this topic. Ohh i don't really want to create 4 new topics. i am to lazy for this.

**Comment by ValentinMel** [comment]
Don't worry it is not a problem. I guess we both want to make this game better.
Ok about that fps bug. Controls set to wasd.
<img width="1280" alt="Fps bug i am hold w button " src="https://user-images.githubusercontent.com/93443384/154145369-2bd8bf75-3337-4cee-82a8-40893754cf92.png">
Controls still set to wasd, but i am hold up arrow key
<img width="1280" alt="Fps bug iam hold up arrow key" src="https://user-images.githubusercontent.com/93443384/154145492-7dae995c-e152-4344-b1b7-16a69b2691c9.png">
All mods disabled. Consol deasn't have any red errors. I even retest without msi afteburner, but i have the same picture.
About that light bug.
I am using cast shadows but draw behand subs is off and with 300 range everything is fine.
<img width="1280" alt="300 range" src="https://user-images.githubusercontent.com/93443384/154148561-84f8db30-02d1-4ce1-afcb-2de911ff21a5.png">
But with 280 range this happens
<img width="1280" alt="280" src="https://user-images.githubusercontent.com/93443384/154148680-24dc39a4-35e8-4fa1-b7e5-3fec6dd30648.png">
Also i created my own "Improved Dugong" And i using sonar monitor with mineral scaner in it, with 0.2 scale of course, because i don't have alot of space for place it without intersections with other textures.
And since i technically i have 2 sonars in my boat, i have to listen 2 sonar ping which is 2 times louder than usual and very annoying.
I think it will be good to have an option in editor that if one sonar is already working, then you will not hear another one. 
I actually fix this by my self simply goes to barotramafolder/content/items/command and deleted this stuff from command.xml
<img width="1280" alt="Fixing problems by my self with deleting stuff" src="https://user-images.githubusercontent.com/93443384/154154283-78a769be-6db8-4657-8ba4-07ce0cfaf416.png">
It's easy and works best in my case. but it's not the most beautiful solution.
And i would like to have an option where if you enable one sonar than will automaticly enable second one and same with shut off them.
Also i really want to give traders more money. When i am doing 10 missions per 1 round. I usually have alot of stuff to sell because i am search in every corner including abyss. But i cannot sell all of it because they have only 5000 crd. and sometimes i can sell up to 50000 or more crd. So game tell me "go to another outpost so you can sell the rest of it". But with another round i will get even more stuff. And where the hell i should use all this where i already crafted everything that i needed and there is nothing to buy from the store. Except for boat upgrades and this is why i need money.
I usually solve this problem with cheat engine so i can give more money to trader (200000) and then i can legalize them with selling thing that i found to him. Also make traders to update their money at least with 2-3 rounds.

**Comment by ValentinMel** [comment]
> No, I'm sorry but I still haven't found a way to get this to happen. I don't notice any kind of performance hit when moving the character in the character editor, no matter if I'm using WASD or the arrow keys.
> 
> It could be possible to get some more clues on what's causing this by looking at the additional performance statistics that can be enabled with the command "showperf". You can use it by opening the debug console by pressing F3, and then entering "showperf" which enables an extra overlay at the top-left corner of the screen. A screenshot of what the overlay shows when you're trying to move the character _should_ give us some extra info on what exactly is causing the performance hit.
> 
> Sorry for the trouble, and thank you for the extra bug reports as well!
So did find something?

**Comment by Regalis11** [comment]
No know steps to repro, closing

**Comment by ValentinMel** [comment]
Well, i already told you about the steps. I still have bug on 0.17.15.
