### ISSUE TITLE
(Orca 2) The water pump in the top airlock lacks a power source

### ISSUE THREAD

**Issue by Sevenecho** [Regalis11/Barotrauma#8134]
Every time my crew uses the upper airlock, there's a water they have to deal with manually. Naturally I decided to figure out the cause of a such behavior. At first I checked the logical circuits - they work as intended, I double checked the outcome on a nearby door. So it became obvious something is not quite right with a pump. It appears, as it was already mentioned in the title, the power cord gone missing. 

My next thought was one of my engineers removed the pump's power for some reason and forgot to put it back later, but just to be sure I started a fresh campaign, loading with Orca 2 intact. Nope, that's clearly a design/construction flaw, you can see a place that wire belongs - the 4th top power junction box using just 4 wires instead of 5 and powering up 2 another submarine pumps. 
Easy to fix in-game, yet I'm quite suspicious that shouldn't even be the case in a first place.
v0.15.23.0, latest Steam version

**Comment by danielasteljoki** [comment]
This has been fixed on unstable. Coming in the next update.
