### ISSUE TITLE
Texts overflow in the sub editor's group menu

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8137]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/93b6dcd3-4cce-4015-b17e-9d77e017515e)

**Version**
v0.16.0.0 +

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7826438f9388dc21b14cf72b7a38a38c08a20455

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
