### ISSUE TITLE
Remora drone engine room doesnt have a pump

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#8138]
Remora drone engine room doesnt have a pump making the drone unable to go up if its filled with water
![Näyttökuva (947)](https://user-images.githubusercontent.com/86321358/151816295-b64d4123-92e2-41ba-b98e-47e3482a96fd.png)
**Version*
0.19.14.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/25a97c596fd53131e14f5671ca49cc2d2c84b4c0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
