### ISSUE TITLE
crashreport(15).log

### ISSUE THREAD

**Issue by HebertPivatto** [Regalis11/Barotrauma#8140]
Description Just crash before the game starts.

Steps To Reproduce Starting the game and got the problem.

Version 0.15.23.0

Additional information 5E97EDD260EEE4EDB6E67D0BB5D09D73

Game version 0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8) Graphics mode: 1920x1080 (BorderlessWindowed) VSync ON Language: English Selected content packages: Vanilla 0.9 Level seed: no level loaded Loaded submarine: None Selected screen: None SteamManager initialized

System info: Operating system: Microsoft Windows NT 10.0.19042.0 64 bit GPU name: NVIDIA GeForce GTX 1050 Ti Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778} GPU status: Normal

Exception: HRESULT: [0x8876017C], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown (SharpDX.SharpDXException) Target site: Void CheckError() Stack trace: at SharpDX.Result.CheckError() at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags) at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010 at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 601 at Microsoft.Xna.Framework.SdlGamePlatform.Present() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 251 at Microsoft.Xna.Framework.Game.EndDraw() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 523 at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669 at Microsoft.Xna.Framework.Game.Tick() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511 at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94 at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398 at Microsoft.Xna.Framework.Game.Run() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368 at Barotrauma.Program.Main(String[] args) in \Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages: [28/01/2022 23:45:06] Attempting to open ALC device "OpenAL Soft on Alto-falantes (2- G600)" [28/01/2022 23:45:04] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean [28/01/2022 23:45:04] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean [28/01/2022 23:45:01] Logged in as ChucrutzSPBR [PzG] (SteamID STEAM_1:1:16002717)

**Comment by SP412** [comment]
I got this problem.. what do i do?
