### ISSUE TITLE
non-interactable items can't be wired/opened in sub editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8142]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't target a non-interactable item for wiring in sub editor. Must unset non-interactable, wire, and then set as non-interactable again.

similarly, containers that are set to non-interactable can't have their inventory viewed/opened in the editor. 

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Oukido** [comment]
Please consider overlapping items on this one. If you for example put text panels ontop of the nav-terminal and zero their alpha, you can build custom displays. Without the option to make them not targetable for the wiring mode, this will become a mess.

**Comment by Tsunder** [comment]
i believe the upcoming feature "sub editor layers" will help with that, but the reasonably overlapping wireables won't have that much difficulty being wired. 

Text display and nav terminal have greatly different hitboxes and would be using different sprite depths to make the text displays show up anyway. Non-issue. If you're stacking like 3 text displays on top of each other, well, I'd say that's a rare and questionable thing to do.

**Comment by Regalis11** [comment]
I agree with Tsunder. In most cases making it'll still be possible to select one of the overlapping items even if all of them are interactable. I'd also argue situations like that are much more rare than situations where you want to access a non-interactable item, so even if it might make it more cumbersome to select a specific overlapping item in some situations, fixing this is justified.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91a1a75002e2eb4cf4f6b9f20f6376a76eb9f643

**Comment by Ek-Videogames** [comment]
I've just been using "NonPlayerTeamInteractable" as a sort of workaround for items that I want to be non-interactable ingame but still accessible for wiring/inventory in subeditor.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
