### ISSUE TITLE
Operate orders aren't automatically dismissed when another character is given the same order

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#8150]
**Description**
Operate orders aren't automatically dismissed when another character is given the same order. This used to happen before.

**Steps To Reproduce**

1. Order a character to operate a weapon
2. Order another character to operate the same weapon
3. Now they are both tasked with operating the same weapon

**Version**
v0.16.1.0

**Additional information**
This behavior seems to have been broken for a few months.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@1d924c9 and Regalis11/Barotrauma-development@2165a9d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
