### ISSUE TITLE
If someone is SpectateOnly in multiplayer, the player sometimes cannot control husk.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#8153]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
problem has been found, check out this code:
AfflictionHusk.cs
```
                if (huskPrefab.ControlHusk)
                {
#if SERVER
                    var client = GameMain.Server?.ConnectedClients.FirstOrDefault(c => c.CharacterInfo.Character == character);
                    if (client != null)
                    {
                        GameMain.Server.SetClientCharacter(client, husk);
                    }
#else
                    if (!character.IsRemotelyControlled && character == Character.Controlled)
                    {
                        Character.Controlled = husk; 
                    }
#endif
                }
```
If someone in the multiplayer online is SpectateOnly, then c.CharacterInfo is null, so an exception will be thrown: "Object reference not set to an instance of an object.", so sometimes the husk can't be controlled.

**Version** 0.15.23.0

**Comment by Regalis11** [comment]
This should not affect the vanilla game because ControlHusk is false on the vanilla husk affliction (= when the player transforms, they don't gain control of the ai-controlled "enemy husk"). But regardless, this is something we should fix because some mods do use this property. Thank you for pointing this out! :)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bfb92e25b05ff6098d8a928218f62b3b6e56836f

**Comment by Rokvach** [comment]
This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.

**Comment by zhu-rengong** [comment]
> This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.

Now it doesn't work at all. ````c.Character```` is always null, so it is impossible to tell who controls husk. This is due to calling:
```Entity.Spawner.AddToRemoveQueue(character)```
it makes c.Character null

**Comment by zhu-rengong** [comment]
> > This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.
> 
> Now it doesn't work at all. `c.Character` is always null, so it is impossible to tell who controls husk. This is due to calling: `Entity.Spawner.AddToRemoveQueue(character)` it makes c.Character null

@Regalis11 Seems like I forgot to call @.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86010e45ada79ddc217764f7eb06b8ce3f3ba2a0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
