### ISSUE TITLE
Terrorist stakeout very overpriced

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8154]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/152025878-23ddefe7-5e33-4f2a-afa6-dc92f6cfb4de.png)
blowing a guy's head off is fun and easy, not enough for it to give you 7,500 marks
killing up to 6 hammerheads that can demolish your submarine  is not that hard either, but certainly worth much more than killing one or two guys that are unarmed.

**Version**
v0.16.1

**Comment by Udrakan** [comment]
There was massive issues with prisoner mission and terrorist stakeout on a 10 player pub server, because of all the mess and newbs killing innocents, however, even with all that trouble, it's still an extreme amount of cash. Might I suggest 4000?

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/02f9d5b8d407f104cb3518d5cca241246da93465

**Comment by itchyOwl** [comment]
I don't think it's really addressed in that commit. Didn't take those scalings into account. And it's WIP still. Good to have this ticket.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@da25754. Didn't have time to test it yet.

**Comment by Rokvach** [comment]
No issues, closing.
