### ISSUE TITLE
[Unstable] Herja's ballasts are not named properly

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8155]
**Description**
![image](https://user-images.githubusercontent.com/59519434/152025851-8d99e66e-6066-4b3e-a464-babbf633e4dc.png)
![image](https://user-images.githubusercontent.com/59519434/152025900-5e9ff456-3862-4978-8066-09534bd76a54.png)
![image](https://user-images.githubusercontent.com/59519434/152025884-4a52a997-051c-45cb-921a-ea2ba5d71e98.png)

**Comment by danielasteljoki** [comment]
Fixed in ba344e6.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
