### ISSUE TITLE
[Unstable] Forcefield above a terrain

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8156]
**Description**
I have reached and collided with an invisible forcefield around a terrain wall. Video shows it:

https://user-images.githubusercontent.com/59519434/152030248-e67eae4a-bbeb-4b2f-9c4d-a08daaa48c06.mp4

Level was from Research outpost to Abandoned outpost nearby. Save:
[Big Iron 4.zip](https://github.com/Regalis11/Barotrauma/files/7981116/Big.Iron.4.zip)

- i could swim inside
- we could shoot inside it
- couldnt approach it from sides

**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b73af0a94466fdfa613487ea08a8b1a4f37b1606

**Comment by Rokvach** [comment]
Tested, working correctly.Closing.
