### ISSUE TITLE
Tigerthreshers don't break through doors

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8158]
**Description**
Might be a deliberate dev decision, however it feels like if multiple threshers assault and break through the door, there might be some serious combat inside the submarine, which is fun because it's like snakes on a plane.
https://user-images.githubusercontent.com/59519434/152032114-cacb49b9-9c5c-4be0-a1c2-342eb4786c40.mp4

**Comment by Kafkatrap** [comment]
Yeah they should let more enemies actually enter the sub. I know it was a thing way back in the day.

**Comment by itchyOwl** [comment]
Should be able to break through doors in the latest unstable.

**Comment by LePiromano** [comment]
it works for me

**Comment by Rokvach** [comment]
No issues, closing.
