### ISSUE TITLE
The Selkie "emergency hatch" is a death-trap

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8159]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using the Selkie as a respawn shuttle on public servers is, in practice, impossible.
Players will randomly press the emergency hatch button not knowing what it does and sink the entire shuttle. 
This happens on a regular basis

![image](https://user-images.githubusercontent.com/73229309/152036923-f33a2f95-9320-40ee-9b82-8e8b8df219e5.png)
_Button of death_

Either remove said button (there's a plasma cutter to escape the shuttle if need be), or use the version I made that is somewhat idiot-proof (can't escape if sub is moving or not flooded). 

[Selkie (stupid-proof).zip](https://github.com/Regalis11/Barotrauma/files/7981396/Selkie.stupid-proof.zip)

It's a little crude and I could refine it but the circuit would get more complex

**Comment by danielasteljoki** [comment]
Changed the system to only work when the shuttle is flooded (>30%) in 80ce283

**Comment by Rokvach** [comment]
Tested, no issues, closing.
