### ISSUE TITLE
[Unstable] Sub Editor Crash when Dragging Docking Port and Moving Camera

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8160]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After placing a docking port, i selected it and attempted to drag it while moving the camera, which caused the game to crash.

**Steps To Reproduce**
1. Place a "Docking Port" in the Submarine Editor.
2. Select the Docking Port.
3. Drag the Docking Port while moving the camera with WASD.

**Version**
Windows Unstable v0.16.2.0

**Additional information**
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/7981521/crashreport.10.log)

**Comment by Singularia** [comment]
You don't even need to drag the camera, just dragging a docking port/hatch anywhere is enough to cause CTD.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a1c4203e673523d608ca6d3e3bdcb3fcc084d2d6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
