### ISSUE TITLE
Russian incorrect translation of the subject

### ISSUE THREAD

**Issue by SaiborgR** [Regalis11/Barotrauma#8161]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
incorrect translation of the subject "depthchargelauncher" - "Турба для глубинных бомб" then how would it be more correct "Пусковая установка для глубинных зарядов"
"Турба"(Turba) -  there is no such word in Russian

**Steps To Reproduce**
Switch to Russian )

**Version**
Windows 0.15.23.0

**Additional information**
![изображение](https://user-images.githubusercontent.com/98849046/152047949-0f476e2e-d048-49d2-97dd-17ab47ec5e0e.png)

**Comment by MaaiG** [comment]
~~depthchargelauncher"~~
"depthchargetube"

"Пусковая установка для глубинных ~~зарядов~~"
"Пусковая установка для глубинных бомб"
IMHO
`<entityname.depthchargetube>Турба для глубинных бомб</entityname.depthchargetube>`
Should be:
`<entityname.depthchargetube>Пусковая установка для глубинных бомб</entityname.depthchargetube>`

**Comment by Regalis11** [comment]
Thank you for the report! I passed this to the translators, so this'll hopefully get fixed in the next update.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/04e7201cdbad0836601a678307847e798cae4b74
