### ISSUE TITLE
[Unstable] Orca2/Winterhalter/Barsuk/Herja issues, round 2

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8162]
**Barsuk**:

- [x] Coilgun wired to power_in instead of power_out
![image](https://user-images.githubusercontent.com/73229309/152059368-a3955f39-c54e-4d64-bd5a-549998a05912.png)

- [x] Badly sized gap
![image](https://user-images.githubusercontent.com/73229309/152059196-37b4622c-31e6-4312-9806-b60f3d61f763.png)

- [ ] Two redudant junction boxes
These JBs only have one connection. There are still empty connection pins left after you remove them
![image](https://user-images.githubusercontent.com/73229309/152059013-19d7eb11-72c1-4ca4-a911-b4b6acdc155e.png)

- [x] Dark ballast, not lit up by an emergency light. **Same goes for Orca2, Winterhalter and Herja**
![image](https://user-images.githubusercontent.com/73229309/152059510-b490b6a6-7099-42e1-a8df-5416ec0d4af9.png)

- [x] Feedback-loop battery circuit: 
When activating the backup battery, the batteries are still draining power, creating a feedback loop of feeding its own power into itself
Instead, rewired it like below:
Disable "is toggle" on the switch so it acts as a button, and wire it to both "toggle state" on relays
**This affects every vanilla sub, I'm honestly considering making a bigger ticket about that with all the implications**
![image](https://user-images.githubusercontent.com/73229309/152060410-4fa495e8-20d3-4034-a739-45950c7ef157.png)

**Orca2:**

- [x] Airlock access room is designated as "airlock", and a wet room.
Other subs have the same problem (like Typhon2)
![image](https://user-images.githubusercontent.com/73229309/152060621-5ef7a325-697d-4172-bd4a-31fb75e9e758.png)

- [x] Battery relay only outputs 1000 max power, for 2x1000 batteries
![image](https://user-images.githubusercontent.com/73229309/152061279-06bc83ac-9154-4305-b045-da0ed05cc08a.png)

- [ ] Poorly optimized color circuit
You can remove all 5 components here, and just set the R,G,B,A signals on the Greater component. Check the Winterhalter circuit
Dugong and Typhon2 have the same problem
![image](https://user-images.githubusercontent.com/73229309/152062361-11dc3b62-b1b7-4596-990e-17959042abb6.png)

- [x] Dark ballasts

- [ ] Two redudant junction boxes
A small amount of rewiring allows to remove two redundant junction boxes.
There are still empty connection pins left after you remove them
![image](https://user-images.githubusercontent.com/73229309/152063752-294ae85d-1834-4016-92f3-ce4ca6eff1f4.png)

- [ ] Water, Smoke detectors and OR components daisy-chained
The navigation room uses a board with Fire and Flood alarms. Instead of using ORs, 5 water/smoke detectors can be put on a wifi component at a time, saving a lot of wires and components.
Dugong and Typhon2 have the same issue
![image](https://user-images.githubusercontent.com/73229309/152062787-01c65373-fc42-46dc-b3ad-9cab4108332d.png)

**Winterhalter:**

- [x] Two battery switches sharing the same input.
You can't activate/deactivate the backup battery without activating BOTH levers at the same time. 
USE TOGGLE STATE
![image](https://user-images.githubusercontent.com/73229309/152064113-936f18e5-18ca-4054-9392-8e2e8e493107.png)

- [x] Door and motion detector offset
![image](https://user-images.githubusercontent.com/73229309/152064279-a3b0232b-021c-451e-b619-89f3111f1ea8.png)

- [x] Useless/Leftover signal checks in airlock
![image](https://user-images.githubusercontent.com/73229309/152064424-e7203592-4397-4129-8fbe-92f077e6cf3c.png)

- [ ] Two redudant junction boxes
A small amount of rewiring allows to remove two redundant junction boxes.
There are still empty connection pins left after you remove them
![image](https://user-images.githubusercontent.com/73229309/152063752-294ae85d-1834-4016-92f3-ce4ca6eff1f4.png)

- [x] Dark ballasts

**Herja**

- [ ] Shuttle batteries can't take damage (unlike normal batteries)

- [ ] Batteries give (almost?) infinite power to the weapons
The way batteries vs supercapacitors work, batteries are much more efficient at drawing power than supercapacitors, and their capacity is much higher by default. You can store very large amounts of spare energy and even recharge faster than the supercapacitor, for less load on the grid.
Example: firing at 10x the fire rate with seemingly no power in reserve
![image](https://user-images.githubusercontent.com/73229309/152066060-76d6b15f-80d4-4d76-89b6-ed618e72318f.png)

- [x] Ballasts not named properly
https://github.com/Regalis11/Barotrauma/issues/8155#issue-1121039854

- [x] Dark ballasts

**Comment by aeondez** [comment]
Somewhat related, but the coilgun being wired to the supercapacitor was probably an oversight because supercaps are busted: https://github.com/Regalis11/Barotrauma/issues/8168

In the Winterhalter, switching the relay from SET_STATE to TOGGLE_STATE doesn't resolve the issue, it just causes an infinite loop of on/off at computer speeds.

A better method would be to replace both switches with buttons (or at least turn off "IS Toggle") run both through an OR component SIGNAL_IN, then route the OR component SIGNAL_OUT to the TOGGLE_STATE of the relay.

Extra JBs never killed anyone.

Dark Ballasts have probably killed people, but it's not a crisis, more of a mood.

Winterhalter now has bad lighting in the engine room because the light in the engine room is cut off by a brand new wall.

**Comment by Regalis11** [comment]
Imo it's good to have some redundant junction boxes in the subs to leave some room for changes to the electrical grid.

**Comment by danielasteljoki** [comment]
Fixed most of the issues in ba344e6. Removed shuttle batteries to make room for another supercapacitor in Herja

**Comment by ubertpendragon** [comment]
> Imo it's good to have some redundant junction boxes in the subs to leave some room for changes to the electrical grid.

I've made sure to check there are available power pins left after removing 2 JBs on all ships. 
At least getting rid of one on the small-crewed Barsuk would help the lone repairman

> Removed shuttle batteries to make room for another supercapacitor in Herja

One such changes to the electrical grid involves wiring guns directly to batteries, which I'll open a ticket about

**Comment by aeondez** [comment]
I don't see the issue with leaving some junction boxes free for future machines or powered devices. Not everything has to be optimized.

**Comment by aeondez** [comment]
Sorry, didn't mean it to come off in a bad sort of way.

I meant more along the lines of "let the devs make their own subs; the flaws and quirks give it character, as long as they aren't broken"

**Comment by Regalis11** [comment]
Nah, I didn't take it in a bad way, that sounded more like a compliment to me. :) Just saying that it's completely fine to point out flaws in the subs: sometimes they're intentional design choices, but they can also be oversights.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
