### ISSUE TITLE
[Unstable] Mission Mode Subs Default to Supercapacitor Recharge Rate of 0kW

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8166]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When beginning a round in Mission mode, the submarine's supercapacitor recharge slider starts at 0kW. This is a problem because it leaves the sub's guns incapable of firing until the player manual adjusts the recharge rate. I've encountered this consistently on the Dugong, Humpback, Orca 2, Barsuk, and even custom submarines that previously did not start at 0kW. The only exceptions I have been able to find are the Winterhalter and the Herja, which both start with a recharge rate of 80kW. It is not necessarily game breaking, but this could be a major issue for new players who are still trying to learn the basics, and it is tedious to fix every round. 

**Steps To Reproduce**
Start a mission in mission mode with a submarine that is not the Winterhalter or Herja. Mission type does not seem to matter

**Version**
Unstable V0.16.2.0, but I believe this was also present in v0.16.1.0

**Additional information**
It is definitely not a coincidence that the only subs to start at 80kW are the two most recently introduced and updated.

**Comment by danielasteljoki** [comment]
Supercapacitors are now charging by default (0b56d35).

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
