### ISSUE TITLE
Supercapacitor POWER_IN pin busted

### ISSUE THREAD

**Issue by aeondez** [Regalis11/Barotrauma#8168]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
POWER_IN pin on supercapacitors is functioning as generic POWER (two way power transfer). POWER_OUT pin works as expected, though.

**Steps To Reproduce**
Open up any sub, put everything on POWER_IN pin
use periscope to shoot something
dakka dakka

**Version**
Windows 10, Unstable V0.16.2.0

**Additional information**
![bug](https://user-images.githubusercontent.com/21000916/152081897-9b698a94-8a30-4bfe-8354-8abebf036851.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2f483297ee798d862ddc660160f9ee3ba2cf4f1d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
