### ISSUE TITLE
Bot Crewmates remove Combat Stimulant (CS) from worn PUCS suits.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8171]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a bot is given a PUCS suit with CS in it, they will return the CS to a medicine cabinet on the ship instead of keeping it.

**Steps To Reproduce**
1. Give a bot a PUCS suit with CS in it.
2. Wait for them to take it out and return it to a medicine cabinet.

**Version**
Windows Unstable v0.16.2.0

**Additional information**
I believe this bug might also happen in the main build of Barotrauma, not just in the unstable build.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a6643e98597fadce85f4eca43466d0fbe875ef0e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
