### ISSUE TITLE
Wiring guns to batteries make them recharge far faster, and far cheaper than supercapacitors

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8172]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Guns wired directly to batteries instead of supercapacitors have a much better power capacity and recharge rate. 
This can be done in-game easily on every sub

**Steps To Reproduce**
Set up a single circuit, where one gun is wired to a battery and the other to a supercapacitor
Set the recharge rate of both to 100%
The battery only drains 500 power (2000 for the supercap), while having 100 times the capacity

[BatteryVSsupercap.zip](https://github.com/Regalis11/Barotrauma/files/7986399/BatteryVSsupercap.zip)
![image](https://user-images.githubusercontent.com/73229309/152155185-e1e0d98a-e4fd-49a8-80d8-d20d92952fd1.png)

For comparison, a standard 500kW battery at 100% drains 500kW and a supercap set at 70% will drain 490kW

Chainguns and Coilguns can work directly off a single battery, a Laser with a power consumption of 1400 can work by wiring two batteries on it. This wiring trick isn't feasible with a railgun (power consumption of 16000)

**One solution for preventing this would be increasing power consumption of guns but also capacity, output and recharge rate of supercapacitors.** With a factor of 5-6, this knocks most gun's power consumption out of the battery range (except chaingun).

Coilgun/Laser required power would go from 1000+ (battery-powerable) to 5000+, which is impossible to power with 5 batteries. Only the chaingun remains, with its low base power consumption of 400.

Reducing the amount of possible wires on guns is a no-no since some contraptions use those multiple wiring pins.

Maybe a hybrid between reducing battery output by half and increasing cost? May hurt vanilla drones

Maybe change how the gun power draw costs to "per second" like discharge coils (bumping the required power output to huge numbers) instead of "per shot", with each shot duration being 1/firerate?

There's also the issue of the actual power draw of capacitors. Maybe this is possible by flattening the power consumption curve?

_This is quite the conundrum_

**Comment by ubertpendragon** [comment]
_But wait, I'm not done yet!_

I've ran some more tests, and if you simply wire a default battery directly into a supercap, **you can multiply your reserve power by 10**.

A supercap drains about 200kw from the battery to fill its own 20kw. Default batteriees have 2000 capacity thus the effective equivalent of 10 supercaps 

Considering an equivalent power draw (500 for 100% charge rate battery, 490 for a 70% charge rate supercap), both refill an equivalent amount of supercap power at the same exact speed (200 for battery 20 for supercap).

It all comes from the discrepancy between battery and supercap capacity. 
I'm not really sure how to fix this

**Comment by Regalis11** [comment]
I don't quite see the problem there. Using a battery to recharge the supercapacitors seems like an entirely valid strategy to me. Unless I'm missing something, you don't get the charge "for free" - if you're charging the battery at maximum rate, and using that battery to recharge the supercapacitor, isn't the end result the same as if you were recharging the capacitor directly?

Or, to put it in another way, the whole point of batteries is to allow you to reserve some power for when you need it. Using it for charging the capacitors is one of the ways you can use that reserve power.

**Comment by ubertpendragon** [comment]
I'll try to reformulate:

Coilguns use ammunition and power capacity as a limiter. 
You can increase that limited energy supply by **inducing huge stress on the grid, in tense combat situations**, by pushing supercaps to 100%. It's a "hazard multiplier".

BUT, if you wire a battery to the supercap, you do not have to face any grid stress. You can charge the battery outside of combat, and the supercap will feed on the battery. No, you're not getting the power "for free", but you're getting much larger amounts of it at the same cost in reserve, during downtime.

You end up with an extremely simply, 1-wire operation that increases your guns' energy reserve **ten-fold**.
At 100%, a battery is the equivalent of a 70% charge rate supercap; but with 10x the capacity

As a final comparison, extra power on guns is much more valuable than extra power on any other sub systems.

2000 kw of battery capacity can run
-an O2 generator for 120 seconds
or
-a coilgun for 200 seconds
 
 Running out of coilgun power is a much bigger deal than temporarily running out of any other machinery. Expect players to disconnect batteries from the main grid and feed them into supercaps directly

**Comment by Tsunder** [comment]
it's just how turret.cs and powercontainer.cs (get battery output or something) are coded, and how power is consumed from each battery connected.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
