### ISSUE TITLE
Inventory.TryPutItem failed

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8173]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Occasional "Inventory.TryPutItem failed: index was out of range" error when joining servers.

**Steps To Reproduce**
The issue happens because the server writes the index of the slot the item is _currently_ in into the spawn data, as opposed to the index in the inventory it spawned in. If the current index is outside the capacity of the original container, it'll lead to this error. One way to repro this is:

1. Fabricate some medical item in multiplayer
2. Put the item in the 2nd or 3rd slot your medic uniform
3. Join the server as another client
4. The client will not try to spawn the item in the 2nd or 3rd output slot of the fabricator, even though it only has one, leading to the error.

**Version**
Any

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/09384242a65c2591a8ec11d6c6ed5bdfe32bc211

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
