### ISSUE TITLE
Bug: It doesn't fit in with the city.

### ISSUE THREAD

**Issue by ArmanMakhashev** [Regalis11/Barotrauma#8174]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report! Looks like you forgot to fill in the information on the bug report though, so I don't know what the issue is

**Comment by Regalis11** [comment]
Closing, let's reopen this if we get more info
