### ISSUE TITLE
Becoming a class different from the selected priorities

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#8175]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It's still an issue, it seems. In this example, I had these priorities chosen
**1. Medic
2. Security 
3. nothing**
There was one medic and 2 security.
The game made me a second mechanic (I'm Charley Fox below)
![Barotrauma_ohIl87ls1d](https://user-images.githubusercontent.com/10529134/152195950-3ead2668-f8ad-47e9-9911-6ecf659b3991.png)

**Steps To Reproduce**
Select less than 3 classes?

**Version**
Windows v0.15.23.0

**Comment by Krzeszny** [comment]
Thanks for the awesome job in testing @NilanthAnimosus 

I haven't experienced this problem in 0.18, don't remember about 0.17 and 0.16. I think it's safe to assume it's been resolved.

**Comment by NilanthAnimosus** [comment]
Thank you for the additional information, I'll keep this open for now to check at a later date as its quite possible it still occurs when using mods that re-implement the minimum counts, having this extra context will help with testing with that and check if its an issue specifically involving mid-round join respawns instead.

**Comment by Krzeszny** [comment]
I chose medic as my only class priority but the game spawned me as an assistant because there already was a medic. The players keep telling me it's because of vanilla.

**Comment by Regalis11** [comment]
No known steps to repro, closing
