### ISSUE TITLE
Bots set to "Recharge Batteries" take non-empty batteries out of portable pumps

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8179]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots that have a currently active "Recharge Batteries" order will take non-empty batteries out of Portable Pumps.

**Steps To Reproduce**
1. Place a portable pump down with a battery in it.
2. Give a bot the "Recharge Batteries" order.

**Version**
Windows Unstable v0.16.2.0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
