### ISSUE TITLE
Bots take fuel tanks out of Prototype Steam Cannons

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8180]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bots with empty welders will steal fuel tanks from Prototype Steam Cannons.

**Steps To Reproduce**
1. Insert a fuel tank into a Prototype Steam Cannon.
2. Empty a bot's welder.

**Version**
Windows Unstable v0.16.2.0

**Additional information**
I used masterwork incendium tanks in my Prototype Steam Cannon, but I'm not sure if normal tanks would work too.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b58889d986fae049ab1b7326894750019f70af83. I made the bots prioritize items that aren't inside another item, so they _can_ still take tanks from the steam cannon, but should heavily prefer tanks that aren't already inside some tool.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
