### ISSUE TITLE
Mudraptors don't have enough priority on doors

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8182]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The addition of the mudraptor veteran is really good because of how fast they can break doors, but i constantly see them and normal mudraptors attack walls instead of doors, which makes them a lot easier to kill and a lot less dangerous.

**Version**
v0.16.2

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@08b21ec and Regalis11/Barotrauma-development@70e022b. Didn't touch the priorities yet.

**Comment by Rokvach** [comment]
Tested, didn't spot any issues. Closing.
