### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by dexpiper** [Regalis11/Barotrauma#8186]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Cannot use letter keyboard keys in game like W, A, S, D to move or E to use an item. But SPACE and SHIFT seem to work as expected. Chat works well. Game restarting solved the problem.

**Steps To Reproduce**
Start the game for the first time after installation. Say "no" to GameAnalytics. Start first game tutorial as mechanic.

**Version**
Linux 21.10
Barotrauma v0.15.23.0 (Release Linux, branch release, revision 0a990787e8)

**Additional information**
When I tried to rebind some keys in settings I've got "None" key instead of the key I just pressed. Also tried to change keyboard language. Nothing helped. In-game chat works normally. Chat window closing does not change the problem.

UPD:
I also saw this issue, but do not know if there is any connection:
https://github.com/Regalis11/Barotrauma/issues/7299#issue-1052801282

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by SlavaVlad** [comment]
The specified problem still exists on Linux

I use Manjaro linux, the problem still shows up quite often, even restarting the game does not help. You can repeat the behavior by switching between windows from the game and into the game. I also had a problem when I was watching a video in the background and pressing the multimedia keys.

**Comment by basedrussian** [comment]
same

**Comment by 05126619z** [comment]
Still relevant BTW. @Regalis11
