### ISSUE TITLE
mudraptor veteran has trouble hitting humans on the floor

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8187]
- [ye] I have searched the issue tracker to check if the issue has already been reported.

**Description**
after being hit by a charge attack from a veteran mudraptor you get thrown on the floor and the mudraptor just can't hit you until you stand up again

https://user-images.githubusercontent.com/55637865/152602887-43f91a27-88fe-4e7a-9801-099a29300e44.mp4
https://user-images.githubusercontent.com/55637865/152602906-b94e65f1-fe43-4041-a6ef-86e190725f08.mp4

**Version**
0.16.2.0

**Additional information**
(i feel like it doesn't do enough damage either)

**Comment by itchyOwl** [comment]
The damage from that attack was doubled for all mudraptors in Regalis11/Barotrauma-development@fbe231d (a general damage balance pass on all monsters).

**Comment by itchyOwl** [comment]
It seems, I've added an attack on their feet to prevent this from happening. But that attack had 0 priority, meaning they didn't ever use it. Fixed in Regalis11/Barotrauma-development@8b3371b.

**Comment by itchyOwl** [comment]
So it's not just an issue with the veterans. All mudraptors are affected.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
