### ISSUE TITLE
[LEGACY] Issues with legacy installations

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#8191]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some legacy installations have some problems like missing pins, links, tags, misaligned UI, strange behaviour etc.

**Version**
Tested on 0.16.2.0

1. Legacy variants of Deconstructor, (Med)Fabricator, Navigation Terminal and Sonar/Status monitors lack some pins that their modern variants have.

2. Legacy variants of Deconstructor and (Med)Fabricator open their work windows when entering their connection panel.

- a. Legacy Deconstructor lacks `CONDITION_OUT` pin and open working window upon opening connection panel.
![decon leg](https://user-images.githubusercontent.com/62324831/152643955-b9a10548-d198-44ab-b892-aba7eec193b0.png)
- b. Legacy Fabricator lacks `CONDITION_OUT` pin and open working window upon opening connection panel.
![fab leg](https://user-images.githubusercontent.com/62324831/152643961-4c838729-9f74-4ced-b3fa-22325dab7fc5.png)
- c. Legacy Medical Fabricator lacks `CONDITION_OUT` pin and open working window upon opening connection panel.
![med cab leg](https://user-images.githubusercontent.com/62324831/152643974-3c148952-8655-4b41-9f0f-f1fc21066fc2.png)
- d. Legacy Sonar monitor lacks `CONDITION_OUT` and `TRANSDUCER_IN` pins.
![sonar leg](https://user-images.githubusercontent.com/62324831/152644092-20f9f0f1-eb10-4bb5-8b95-223faf631959.png)
- e.Legacy Status Monitor lacks `CONDITION_OUT` pin.
![statmon leg](https://user-images.githubusercontent.com/62324831/152644103-2518907d-8b6e-4ed5-bbb4-83d486677f1b.png)
- f. Legacy Navigation Terminal lacks a majority of pins that its new variants have.
![nav term leg](https://user-images.githubusercontent.com/62324831/152644196-8ab79cc8-3967-4cb7-ad1a-f9dc7fa852d5.png)

3. Legacy Status Monitor has its UI slightly misaligned compared to its normal variant.

New Status Monitor UI
![statmon std](https://user-images.githubusercontent.com/62324831/152644636-044a2715-f2e8-4a9f-8a09-91877c9dbb92.png)
Legacy Status Monitor UI
![statmon leg](https://user-images.githubusercontent.com/62324831/152644647-38dfe0ec-f689-4fb6-a72c-d67caeb8b4e3.png)

4. Legacy Sonar Monitor's UI is not in line with the UI of a new Navigation Terminal and Sonar Monitor.
![sonar leg](https://user-images.githubusercontent.com/62324831/152644769-1ed5915f-275b-4c00-b584-e5dfab002070.png)

5. Legacy installations lack "Allowed links" and/or tags that their new variants have

**Legacy Deconstructor**
![decon leg](https://user-images.githubusercontent.com/62324831/152645047-211b59a6-595c-47e5-8bff-8e6df9e5f25a.png)
New Deconstructor
![decon std](https://user-images.githubusercontent.com/62324831/152645060-7cdb55f0-4532-4bd8-aa05-cd4122784660.png)

**Legacy Fabricator**
![fab leg](https://user-images.githubusercontent.com/62324831/152645068-3ccc9320-d88b-4245-9795-4142a65cb8a8.png)
New Fabricator
![fab std](https://user-images.githubusercontent.com/62324831/152645071-bd307af9-f184-44e1-9f30-9395c3e3e9ff.png)

**Legacy Medical Fabricator**
![medfab leg](https://user-images.githubusercontent.com/62324831/152645080-a2a536a6-6073-48a0-8455-76bddfe7469f.png)
New Medical Fabricator
![medfab std](https://user-images.githubusercontent.com/62324831/152645083-5dd3e473-8c10-4810-aa66-ec39c679cfde.png)

**Legacy Navigation Terminal**
![nav term leg](https://user-images.githubusercontent.com/62324831/152645095-88388062-78eb-4d39-b05e-a39b28044f12.png)
New Navigation Terminal
![nav term std](https://user-images.githubusercontent.com/62324831/152645096-d2a259de-599c-40f7-91d3-614bdf038b9a.png)

**Legacy Status Monitor**
![statmon leg](https://user-images.githubusercontent.com/62324831/152645212-ef64fdd2-f4cf-4a7a-84f5-b5606a75cff1.png)
New Status Monitor
![statmon std](https://user-images.githubusercontent.com/62324831/152645214-a6ab3e57-8d2a-4893-ae11-f9d2a961ab8d.png)

**Legacy Sonar Monitor**
![sonar leg](https://user-images.githubusercontent.com/62324831/152645262-fc0cb4a4-7084-48ab-b127-52bd063bff09.png)
New SonarMonitor
![Sonar std](https://user-images.githubusercontent.com/62324831/152645263-7155331b-4809-4972-b226-aa67d5876013.png)

**Comment by Regalis11** [comment]
Legacy items/structures are only in the game for backwards compatibility reasons: we don't maintain them (excluding fixes to issues that make them completely non-functional) nor add any new features to them.
