### ISSUE TITLE
Issues with some containers

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#8192]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some containers have issues like mismatched selection box, different Sprite Depth compared to other containers and missing tags.

**Version**
Tested on 0.16.2.0

1. Outpost Cabinets' selection box is bigger than the sprite itself, this can create difficulty in selecting any item that is placed above it.
It also has default Sprite Depth set to 0.920 while the standard depth for cabinets is 0.840.
![cabinets](https://user-images.githubusercontent.com/62324831/152645685-4a4f4017-4d72-4180-a0cb-8426c79d8620.png)

2. Medical Compartments have their default Sprite Depth set to 0.970 while the standard depth for cabinets is 0.840.
They also lack any "Allowed links" choices and item tags
![med comp](https://user-images.githubusercontent.com/62324831/152645805-728a30d4-7062-49ad-b39d-38fc0eecf5f5.png)

**Additional information**
It's not an issue, but a personal opinion regarding Medical Compartments.
Medical Compartments most of the time used (for Sub-Builders) as a general-purpose compartments (for armouries, reactor rooms, crew quarters, kitchens etc.) and not just for medical purposes, so it may be **better to rename them as "Storage Compartment"** to make them better fit in any room variants.

**Comment by Singularia** [comment]
3. Weapon Holder won't accept Syringe Gun because current Syringe Gun lacks required tags.

**Expected behaviour**
Syringe Gun can be put in weapon holder (tested using Stable version 0.9.10.0).
![image](https://user-images.githubusercontent.com/62324831/152670918-d0f8be7f-66a8-465e-a651-1bb6adf71d1d.png)
_Example 1_

**Actual behaviour**
Syringe Gun alongside with Crowbar, Toy Hammer, Sprayer, Welding Tool and Plasma Cutter can't be placed in weapon holders.
![image](https://user-images.githubusercontent.com/62324831/152671004-723c6241-bd6e-475e-be52-eb7fc5b2d8cd.png)
_Example 2_

**Possible cause**
This is because in previous releases Syringe Gun had 3 tag `weapon, mediumitem, gun` but currently it has only `smallitem` tag.
Lack of the `weapon` tag prevents it from being put in weapon holders.

**Additional information**
Some items have slightly wrong offset when in a weapon holder (look at example pic 2):
- Standard Shotgun noticeably shifted to the right side.
- Steam Cannon shifted slightly to the right compared to a Flamethrower.
- Standart Revolver shifted slightly to the bottom.

**Comment by Singularia** [comment]
4. Medicine Cabinet can't be mirrored by X-Axis, only by Y-Axis
_I already mentioned a related issue in #7709 (Item 14)_

**Comment by Tsunder** [comment]
the position of the stun baton is also kind of weird. It's "held" by its "blade" section, rather than something like the handle.

I guess this applies to the knives also.

**Comment by Regalis11** [comment]
Fixed most of the issues in https://github.com/Regalis11/Barotrauma-development/commit/7c62a1d82cbd000824081c0e43f9e9e2e8fd3a0b

Changing the name of the medical compartments will have to wait until next loca batch though.

> Some items have slightly wrong offset when in a weapon holder (look at example pic 2):

What would you consider the "right" offset? Atm we just place the origin of the item's sprite to the center of the weapon holder.

>the position of the stun baton is also kind of weird. It's "held" by its "blade" section, rather than something like the handle.
>I guess this applies to the knives also.

That makes sense to me, if it was held by the handle wouldn't you have to grab it by the blade to take it from the holder?

>Medicine Cabinet can't be mirrored by X-Axis, only by Y-Axis

Is there some necessary use case for this?

**Comment by Singularia** [comment]
> What would you consider the "right" offset?

It's a poor choice of word on my side here, by "wrong" I meant one that stands out from the rest (visually), like Shotgun with its noticeable shift to the right side of a holder

Also regarding Knives, I think they should be held blade side down and handle up (assuming that we take items from the top side of a holder).

> Is there some necessary use case for this?

In some cases, the front decoration pieces can conceal a painted cross on its right side, thus preventing players from visually identifying that it's indeed a Medicine Cabinet.

Unlike Crate Shelf or Railgun Shell Rack, for example, Medicine Cabinet has a different texture on its right and left (if sliced vertically) so mirroring is by X-axis makes sense.
![image](https://user-images.githubusercontent.com/62324831/152769375-db68fe4e-5c3a-4f98-8143-ac11dc5c4865.png)

> That makes sense to me, if it was held by the handle wouldn't you have to grab it by the blade to take it from the holder?

I think there is nothing wrong with it being held by the handle, it's just strange that "blade" part goes up, especially for knives, or handles up for pistols/revolvers.

**Comment by Singularia** [comment]
5a. Not sure if it's an oversight or intentional change but i noticed that new (that were added with hardpoints) have different Sprite Depth, all old loaders had Sprite Depth value of 0.800 and now most have a value of 0.780.
![image](https://user-images.githubusercontent.com/62324831/152784212-a34c92ad-f494-42ac-9975-239f7aa7f415.png)

5b. White rectangles (not sure how to call it properly) and the initial position of loaders are misaligned between each other.

- This makes it harder to place loaders without using arrow keys when building a submarine.
- This also makes it harder to estimate what gap you need to have if you plan to make loader/cannon upgradable since they don't align with each other.

![image](https://user-images.githubusercontent.com/62324831/152785361-5b92976f-a116-493e-988a-bf1fd7702e87.png)

**Comment by Singularia** [comment]
6. Alien Artifact Holder's connection panel can't be opened using a screwdriver both in wiring mode and in-game, instead the item container's window opens.

**Comment by Regalis11** [comment]
> Alien Artifact Holder's connection panel can't be opened using a screwdriver both in wiring mode and in-game. Instead, the item container's window opens.

This is intentional, the holders are not supposed to be rewireable.

**Comment by Singularia** [comment]
> This is intentional, the holders are not supposed to be rewireable.

Oh, it's intentional, that was unexpected. Though it is an odd decision since as players we can't rewire alien stuff in ruins anyway, but in the editor, on the other hand, we can (re)wire all alien tech, except for Artifact Holder.

IMO this restriction only makes it harder to work with it, since it still possible to manually create a custom Item Assembly where Artifact Holder is wired to JB for example.

**Comment by Regalis11** [comment]
@Singularia 

Oh, that's a good point! You're right, it'd make sense for them to be rewireable in the editor.

@MaaiG

I wouldn't call them hitboxes because they have nothing to do with collision detection: they just visualize the position and extents of the item. In the code they're just called the "rects" of the item, but outside the code I'd maybe use something like "outline" or "borders".

**Comment by MaaiG** [comment]
@Regalis11
Thank you very much. A small dictionary (or large :)) of such special terms could help to better describe problems in error reports and more appropriately express your thoughts on this specific issue, considering language difficulties.

**Comment by itchyOwl** [comment]
Related to the comment above: 

Added a separate tag ("mountableweapon") that defines whether the item can be placed on weapon holders or not in Regalis11/Barotrauma-development@6e68a55.

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/99907d9c-ce74-458c-98f7-112e7df68caf)

**Comment by Regalis11** [comment]
Made the loaders' sprite depths consistent in https://github.com/Regalis11/Barotrauma-development/commit/62a1c1f9fb952a46f7a13b212964b9d661847c2f. I think everything here has now been addressed, aside from the ones that aren't actual bugs? Moving to review

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
