### ISSUE TITLE
Decapitating characters can only happen when you hit the torso, not head

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8193]
Found out that there's a bug causing heads being severed when the character is hit at the torso, not at the head, as it should be. 

For crawlers this meant that decapitating didn't work, because severing the main limb isn't allowed. It seemed like it did, because the head could pop off e.g. when shot with a shotgun. But that was because the Crawler was already dead before the last shots hit -> and those shots could decapitate the creature regardless of the issue.

For mudraptors, it meant that beheading _only_ happened when hitting the chest, never when hitting the head, because mudraptors' chest is of type "None" and hence the connected joints are allowed to break when this limb was hit. Note that Endworms still worked as they should: decapitation happens when you hit the first segment after the head.

The roots for the issue are in that normally the joints have been created starting from the body, but heads are a separate case. With many creatures we've started from the head, not the torso. Although with the new human, we've done the other way around (which is better).

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/7a93bdc9-4945-4747-84cf-b8dd38477c83)

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/adf7bfe3-8e84-42c0-a796-327a4289d873)

Fixed in Regalis11/Barotrauma-development@0277935.

Steps to repro:
- disable enemyai
- spawn a crawler/unarmored mudraptor
- shoot at the head -> the neck joint never breaks
- shoot at the chest -> the head can be severed (mudraptors)
- the issue can be reproed more easily by ignoring the severance probability in the code (so that it's practically 100%) and by setting the health of the creatures to something ridiculous, like 10k.
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/20006e40-067d-4211-ba8b-f16f9c8b179c)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
