### ISSUE TITLE
Oxygen Generators only output a percentage

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#8194]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a feature request
Oxygen generators only put out a percentage of oxygen in the current hull. This makes creating circuits that toggle on and off the oxygen generator a complete abomination that likely impacts performance. This seems to be getting more popular (maybe I am just noticing people do it more).
See;
https://steamcommunity.com/sharedfiles/filedetails/?id=2732232801
https://steamcommunity.com/sharedfiles/filedetails/?id=2732422820
https://steamcommunity.com/sharedfiles/filedetails/?id=2419010949

This is easily resolved by adding a low_oxygen pin to the oxygen generator similar to how the Water Detector has a high_pressure pin. Adding this pin would also make creating an alarm for low oxygen work in a similar manor to how fire and flood alarms work in vanilla subs.

**Steps To Reproduce**
Attempt to create a circuit that will toggle on and off the oxygen generator if the oxygen is low in any hull without using a ridiculous number of components.

**Version**
v0.15.23.0 (Windows/Linux).
I play on Linux, but develop/debug on windows because I use Visual Studio.

**Additional information**
PR
https://github.com/Regalis11/Barotrauma/pull/8195

**Comment by Rokvach** [comment]
Tested, working correcly. Closing.
