### ISSUE TITLE
Text overlap in Settings screen

### ISSUE THREAD

**Issue by p2635** [Regalis11/Barotrauma#8196]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It's my first time playing the game, when I change the settings I notice a small overlap in the text.

**Steps To Reproduce**
1. Set Resolution: 1920x1080
2. Go to Settings > Gameplay/UI, change Text Scale to 150%
3. Observe the text on the top left of the window, 'Settings' collides with 'Content Packages'

![image](https://user-images.githubusercontent.com/4522927/152663843-3f4ba9e7-8130-4be7-98cc-4d079fe5597c.png)

**Version**
Game version: See bottom left of the above image
Windows 10

**Additional information**
Resolution: 1920x1080

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cb92b61fb1705aa5e1f99d837e71daf5eb98618b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
