### ISSUE TITLE
Consider broken floor as a ledge 

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#82]
So if you cut open the floor above command you can climb down it as if it was a ledge.
Right now, you can stand on the "hole" but can't really fall down.

**Comment by Crystalwarrior** [comment]
Turns out ragdolls can go down broken floors anyway.
With ragdoll button this becomes less of an issue, but still pretty annoying.

**Comment by juanjp600** [comment]
Closed by https://github.com/Regalis11/Barotrauma/commit/d34c783c30d620b8392ef356e38ef869d9b3f9bf
