### ISSUE TITLE
[Unstable] Strange husk infection message, despite not being husked

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8200]
**Description**
Right after loading a SP save, I get husk infection messages, despite no characters being husked prior to save. There are husks at an abandoned outpost where the save is currently located. Switching to different characters keeps displaying the message. I don't see any husk infection on health scanner HUD
**Save**
[Save 11.zip](https://github.com/Regalis11/Barotrauma/files/8010480/Save.11.zip)
**Additional info**
Same happened to us 1 version back on multiplayer, where husks were in a wreck. Somebody spawned in a shuttle and immediately saw husk infection messages, despite there being no way for them to get infected, since they've just spawned. Idk how to repro.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c3ab263eec913f522747815ee29316241fceeaf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
