### ISSUE TITLE
Maximum intensity music keeps playing looped in abandoned outposts, despite vibes being chill

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8201]
**Description**
Title. It's due to spawned creatures:
![image](https://user-images.githubusercontent.com/59519434/152687828-af7d7aa6-79ad-41d3-a290-a2d1f6d2bc19.png)
Save: #8200 
**Version**
Stable and unstable

Moribund, Wondrous places or SSN Rusty Clown sound like more fitting music. Maybe watery shadows too. No music might also fit.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e5a442b6c15013f2021e87c0d814fcf6c248200

**Comment by Rokvach** [comment]
Tested, no issues.  Closing.
