### ISSUE TITLE
[Unstable] Navigation terminals using "center on transducer" do not use coordinates of their own

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8206]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using "Center on transducers", the position X/Y outputs of the navigation terminal does not output coordinates relative to the transducer's position.

All navigation terminals using transducers from the same sub have the same coordinates:
![image](https://user-images.githubusercontent.com/73229309/152814016-163e4156-ac4d-49e8-a301-25f1586528a3.png)

The old method (using a separate shuttle with transducer) still works fine.

**Comment by ubertpendragon** [comment]
#6990

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/36f7fc5f0c8798a2e4af037408031ae3ffc85b00
