### ISSUE TITLE
Orca 2 Flood alarm bug and discharge coil 

### ISSUE THREAD

**Issue by Keryoth** [Regalis11/Barotrauma#8209]
**Description**
Sorry for bad english in advance

1-On Orca 2 submarine Discharge coil is powered by junction box, not supercapacitors. With this you can spam it even you clearly dont have power. I dont think thats intentional.

2- There is problem with flood buzzer. If upper floors get flooded it wont stop. Pumps in upper airlock and oxygen generator are not powered

**Steps To Reproduce**
Made video how that can happen. Link on yt https://youtu.be/GPbasJlUWXQ

**Version**
Current version of game (7.2.2022) Windows 8.1

**Additional information**
1-Eazy fix by changing wiring to supercapacitors
2-Wiring pumps to power.The upper floor room ( the one next to gunnery and armoury) should have duct block. With that i fixed it. Even if its intentional to not have pumps powered its just annoing and new players dont know where is the problem and how to fix that. 
Also gunnery compartment is wet room but that is minor thing

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/14b74b0bf1cc6db101b875547f3ebe996e35a89b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
