### ISSUE TITLE
Skitter Gene uses Hammerhead Matriarch Gene's spirte

### ISSUE THREAD

**Issue by Aku230** [Regalis11/Barotrauma#8213]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Skitter Gene inventory sprite uses the same sprite as Hammerhead Matriarch's one

**Version**
0.15.23 and 0.16.2

**Additional information**
Both of them share the same sheetindex in xml file.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e0a16b7de675dd63349df486d582f91712f78282

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
