### ISSUE TITLE
fixfoam grenade timer too long (balance issue) 

### ISSUE THREAD

**Issue by Anarengon** [Regalis11/Barotrauma#8214]
The use case for using fixfoam grenades over welder is usually a gaping hole in the hull, but because of their 3 second timer, throwing them anywhere near a hole in the hull means they'll roll towards it, fall out, then explode 2 seconds later. Or you throw it upwards at a hole, then it falls back to the ground.

suggestion: change the timer either to something supremely low like .4s, low enough that it explodes at the end of the throw, or change it to explode on impact. Downside of short timer being the timer can still be too early or too late in the throw arc. Downside of impact being it's really hard to use on a large hull hole.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
