### ISSUE TITLE
Outdated description for oscillator component's output types

### ISSUE THREAD

**Issue by Singularia** [Regalis11/Barotrauma#8216]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Description text for Oscillator Component's output type is lack description of new modes. In the current description, there is only information about Pulse, Sine and Square, but no information about Sawtooth and Triangle.
```
<sp.oscillatorcomponent.outputtype.description>What` kind of a signal the item outputs. Pulse: periodically sends out a signal of 1. Sine: sends out a sine wave oscillating between -1 and 1. Square: sends out a signal that alternates between 0 and 1.</sp.oscillatorcomponent.outputtype.description>
```
![image](https://user-images.githubusercontent.com/62324831/153199315-7c43e2cf-b570-40c2-8e8d-ddca7fcc7454.png)

**Version**
Unstable 0.16.2.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/620dffb830b14aad62c4794138007e6608486fec

**Comment by Rokvach** [comment]
No issues, closing.
