### ISSUE TITLE
[Unstable] Nuclear Depth Decoys don't loop sonar beacon sound

### ISSUE THREAD

**Issue by Anarengon** [Regalis11/Barotrauma#8218]
while normal depth decoys play a looping sonar beacon sound, nuclear depth decoys seem to play the sonar beacon sound once and then not again

V0.16.2.0 UnstableWindows, branch dev, revision 87700d0b71

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/df5c943f5f0b7aece4631b3a89311e238df1e410

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
