### ISSUE TITLE
Make it Possible to Disable Console Pop-Outs Upon Errors- Feature Request

### ISSUE THREAD

**Issue by rico6822** [Regalis11/Barotrauma#822]
Some people get easily annoyed by console menu showing up right after the error. They cannot control their characters during, exceptionally that sometimes those errors repeat in very short time making game barely playable.

**Comment by CommanderMark** [comment]
Giving the player the option to completely ignore errors doesn't sound like a good idea. They're needed for fixing issues with the game, and even if they can be annoying that's far better than having the game never tell you the errors occurred in the first place.

**Comment by BillCombs** [comment]
I think this still should be an option for those players who are not planning to debug the game or report bugs. Perhaps it should always be enabled upon launching the game, so the player would not be completely oblivious to any new and sudden errors, but i feel like you should be able to disable it while playing the game, if you don't care about the errors, or especially if you are planning to do something, that causes errors, on purpose.

**Comment by Regalis11** [comment]
I agree with CommanderMark. Hiding or disabling errors in generally not a good idea - we do it in specific cases where we know ignoring the error won't cause any ill side-effects or can work around the error in some way, but if some unexpected error happens and causes the console to pop up constantly, we _want_ the game to become unplayable or crash. Letting the player keep playing even if some unexpected error we haven't accounted for has occurred would not only make it harder for us to find out about the error, but it might also cause additional errors further down the line.
