### ISSUE TITLE
[Unstable] Barsuk/Winterhalter/Herja/Orca2 issues, round 3

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8220]
**Barsuk**

- [x] Relays capped at 1000 with two batteries 
![image](https://user-images.githubusercontent.com/73229309/153297892-2052c52c-b6d3-41d3-9d65-16bf37f7c990.png)

- [x] Dark bilge:
![image](https://user-images.githubusercontent.com/73229309/153297795-8734c8b9-55f3-42c6-bd62-d4055d0c32bf.png)

- [x] Bilge not "avoid staying" (bots like to chill in there)
![image](https://user-images.githubusercontent.com/73229309/153298823-fdbe4347-db6d-47f4-8e88-d98e7f5fcee0.png)

**Winterhalter**

- [x] Supercaps wired to a relay capped at 1000 _(I'm grabbing the whip)_
There's plenty of spare junction boxes to wire them to
![image](https://user-images.githubusercontent.com/73229309/153299108-eedfe65f-e381-4314-b0e2-e7f6753bdab4.png)

- [x] Bad waypoints from back when it had stairs
![image](https://user-images.githubusercontent.com/73229309/153299370-3b4ff1cf-c3b1-477b-8d12-2145da8b7aa7.png)

- [x] Dark engine room
![image](https://user-images.githubusercontent.com/73229309/153299856-348264a6-00d4-45d7-8fc2-02a895534e77.png)

- [x] No vent in engine room

- [ ] Twin Engines causing extreme load (4000 + 2000)
Suggesting to tone down engine load and reactor output
![image](https://user-images.githubusercontent.com/73229309/153300535-907f0365-f51b-42ab-9f05-ac5ee4b9cd9c.png)

- [x] Duct alignment
![image](https://user-images.githubusercontent.com/73229309/153299717-c6e0d9c9-9344-4878-bb14-2b9e6e645bfa.png)

- [x] Ballast pump spitting water particles inside "shuttle" (too close)
![image](https://user-images.githubusercontent.com/73229309/153300665-4a471d45-f7d6-4c52-9262-abc0b4d5efac.png)

- [x] Overlapping wall textures/same sprite depth near airlock
Suggest deleting the small piece of backround, setting outpost background depth to 0.970 and resizing 
![image](https://user-images.githubusercontent.com/73229309/153300842-350d0565-0017-4dc9-ad68-8e62d3eb2eb0.png)

**Herja**

- [x] Supercap not wired
![image](https://user-images.githubusercontent.com/73229309/153301615-7952a85e-364e-4e6b-8b75-92e5e17e1e36.png)

- [x] Junction boxes that don't have signal pins
![image](https://user-images.githubusercontent.com/73229309/153301696-377102e2-f1c9-4554-b9eb-b81a036b7694.png)

- [x] Monsters can trigger the discharge coil outside of its zapping range
![image](https://user-images.githubusercontent.com/73229309/153303638-8fabe6fe-874c-4d8b-8ee3-c6cf4ccd38a0.png)

- [x] No way to charge batteries on the sub (no batteries/charging dock)

- [x] Herja supercap wired to a junction box not wired to the grid
![image](https://user-images.githubusercontent.com/73229309/153643031-c7e99e28-7bc4-4056-9efa-91ce98888c79.png)

- [x] Railgun is too chonky for the mount (might need to add some fins)
![image](https://user-images.githubusercontent.com/73229309/153649772-dbab7dcd-0054-48d4-baa2-1e4bdbfa2f8c.png)

- [ ] Coilgun is too small for the mount (disable swapping?)
![image](https://user-images.githubusercontent.com/73229309/153669134-bc9eded5-6be8-4cbe-8616-0d5b39306482.png)

- [x] Motion sensor is wired to the wrong light/turret (proximity detector)
 Rear turret doesn't have a light, Ventral turret to rear sensor  (but no sensor of its own)
![image](https://user-images.githubusercontent.com/73229309/153669526-a1f771f6-6273-4441-9de0-febc4ec6904e.png)

- [x] Bottom right ballast pump spitting water particles inside gunnery (flip it)

**Orca2**
Nothing

----------
 #8162

**Comment by Regalis11** [comment]
> Twin Engines causing extreme load (4000 + 2000)

This is intentional: you shouldn't be able to operate both of the engines at full power with a non-upgraded reactor. The rest of the issues should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d1076a902ab2d745202864ea6e7ab2e4852b4ee3 and https://github.com/Regalis11/Barotrauma-development/commit/551a353d2d79610d31fd10203af5b4af8d9245de

**Comment by ubertpendragon** [comment]
> This is intentional: you shouldn't be able to operate both of the engines at full power with a non-upgraded reactor.

For reference, both of Berilia's large engines draw1500 power each, and its reactor is capped at 6500

Winterhalter has a 10000 reactor capacity, for a 6000 total engine draw
This increases the Walter's fuel consumption overall and makes it prone to overvolting

If you lower both the max reactor capacity to 8000 and reduce the engine draw by 1000 on each you get a better fuel efficiency and less overvolting (plus it's more in line with other subs balance wise)

**Comment by ubertpendragon** [comment]
- [ ] Herja supercap wired to a junction box not wired to the grid
![image](https://user-images.githubusercontent.com/73229309/153643031-c7e99e28-7bc4-4056-9efa-91ce98888c79.png)

**Comment by Regalis11** [comment]
Thank you! All of these should now be fixed aside from the railgun mount (not sure if that's something we need to address, to me the gun seems to fit alright between those decorative pieces).

> If you lower both the max reactor capacity to 8000 and reduce the engine draw by 1000 and 500 respectively (4500/8000) on each you get a better fuel efficiency and less overvolting (plus it's more in line with other subs balance wise)

The thing is, we want the subs to have different pros and cons. In this case we have a very high-capacity reactor that's offset by the 2 power-hungry engines that can lead to power outages or overvolting if used carelessly.

**Comment by Rokvach** [comment]
Tested, no issues.  Closing.
