### ISSUE TITLE
[Unstable] Can't copy/CTRL+Drag docking ports/hatches in editor

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8221]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can't copy/CTRL+Drag docking ports/hatches in editor

Docking ports aren't saved in assemblies either

**Steps To Reproduce**
Select a docking hatch
Hold CTRL and drag it
Nothing happens
CTRL+C CTRL+V
Nothing happens

**Version**
v0.16.3.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4181650224d7aa0221263e285e723bd904a2b618

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
