### ISSUE TITLE
spiky bushes break ragdoll

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8222]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Going through a spiky bush in a "forest cave" will break your ragdoll when yo go back to the sub, your arms stay behind you when you walk and your y speed is reduced.

**Version**
0.16.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/400b510e79f639a06af2d69cf8ff79dbe54b17b0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
