### ISSUE TITLE
[Unstable] Crash when shooting a Watcher

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8224]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a Watcher is shot, the game crashes to desktop.

**Steps To Reproduce**
1. Spawn a Watcher
2. Shoot it

**Version**
Windows Unstable v0.16.3.0

**Additional information**
Crash Report: [crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/8038531/crashreport.14.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d5e51d6428b3bfc48d4a1eb644273d98d7466eeb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
