### ISSUE TITLE
"Error" when trying to heal disconnected clients in the medical clinic

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8225]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/c1fd9703-0453-4132-b109-02a01e6b0e17)

**Steps To Reproduce**
1. MP campaign
2. Have one of the clients disconnect
3. Try to heal that client in the medical clinic

**Version**
v0.16.x

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d0e34a4c8ab88e5be68a5f3238c4329e409b173e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
