### ISSUE TITLE
New crash

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8229]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Happened a few seconds after a watcher spawned along with a small group of crawlers, when i got on a coilgun.
[crashreport (60).log](https://github.com/Regalis11/Barotrauma/files/8045289/crashreport.60.log)

**Steps To Reproduce**
Use this save, the crash happens 3 quarters into the level
[dontcaredidntask.zip](https://github.com/Regalis11/Barotrauma/files/8045301/dontcaredidntask.zip)

**Version**
0.16.3 windows

**Comment by Regalis11** [comment]
Did you accidentally send the wrong crash report? That seems to be from version v0.16.1.0, and happened after taking control of a doomworm.

**Comment by LePiromano** [comment]
> Did you accidentally send the wrong crash report? That seems to be from version v0.16.1.0, and happened after taking control of a doomworm.

I sent that one because it's the latest one i have, it seems like the crash didn't actually generate a crash report log, and now i can't replicate the crash again using the save. It might've been fixed in 16.4?

**Comment by Regalis11** [comment]
Yeah, I'm suspecting this was caused by https://github.com/Regalis11/Barotrauma/issues/8224
