### ISSUE TITLE
R-29 supercapacitor fix

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#8230]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Increased the max recharge speed to 1000 to match the new mechanics.
![1111](https://user-images.githubusercontent.com/29980468/153545803-4b090ee4-3c30-45d5-a28a-5482916de60d.jpg)

**Version**
v 0.16.3.0

[R-29-dev.zip](https://github.com/Regalis11/Barotrauma/files/8046380/R-29-dev.zip)

**Comment by Regalis11** [comment]
Thank you! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/22b8e2230812e8e0a75968620241da6b406faaf0

**Comment by Jade-Harleyy** [comment]
The new value seems to work alright, although the Supercapacitors charge a little slower than on other subs due to the reduced Efficiency value (0.10 -> 0.05).
Charging is fast enough to sustain the default Coilgun for an entire box without stopping, never going below 50% charge in the process.

**Comment by Rokvach** [comment]
Closing.
