### ISSUE TITLE
(modding) failure to load .png files: "can't parse XML file"

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#8234]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An attempt to add a .png file into mod package directly causes two problems:
1. The game won't attempt to actually load it.
2. On game restart, the game will decide that it's .xml file. And will fail to read it (of course). Regardless of file type selected during file adding.
I see that people succeed with adding new and replacement textures into packages somehow.

**Steps To Reproduce**
1. Copy \Barotrauma\Content\Characters\Human\Human_male.png into \Barotrauma\Mods\somemod\Characters\Human\ folder.
2. Edit that copy somehow noticeably (let's say, make him... purple).
3. Include it into somemod's filelist.xml (through either manual file edit - or from in-game package assembler).
4. Reload the game.
5. Enable the mod. Note that no errors are present - nor restart prompt.
6. Restart the game. Get the error.

**Version**
I'm on Unstable currently - however, there are no difference in modding related scripts between Release and Unstable... riiiiight?

**Additional information**
It perplexes me... I'd really like to edit some textures to make ppl have less humpy backs - but can't.

**Comment by Regalis11** [comment]
I gave this a test by setting the file type to "None", and it seems to work without any issues. Other file types throw an error as expected.

> I'd really like to edit some textures to make ppl have less humpy backs - but can't.

You have to override the human config file and make it point to your custom texture.

**Comment by DrinkFromTheCup** [comment]
Re-tried with file type: None , indeed no error anymore. Weird. Will keep an eye on it.
Tried to sneak ragdoll file into the mod under Character tag - more errors. Well... disregard that. More than a note to self to make everything None if in doubt.

As of utilizing config file for ultimate replacement goal...

I see that for Human_male.png I have to redefine whole ragdoll, since texture I want to replace is being nailed to ragdoll XML's root tag.
Which is an overkill: I'll be pulling all content included into root tag just for a single texture replacer.
(from two root tags of two files because I must follow "define Human.xml override for ragdoll > define HumanDefaultRagdoll.xml override for texture > finally make appropriate texture file replacer". )
Not if that I'm in a position to ask... just providing feedback.
A mere replacer shouldn't demand copy-pasting unrelated data, for better compatibility's sake (and all involved parties' happiness). It creates... a bit unhealthy modding flow. Which is still MUCH better than Unity based games' (and, despite their decade of development, way better than Paradox's Clausewitz). But still... uh...

P. S. An attempt to utilize <Override> to snipe at root tag only ended up in a crash, will post it into separate issue (steps are synthetic - but it might help with something in advance).
And even assuming that this dirty hacking attempt MIGHT succeed, I'll probably need to copy WHOLE content of both XML files, which is an overkill x2 for such a purpose...

**Comment by Regalis11** [comment]
I completely agree that having to override the entire character config file just to replace the texture is overkill. We've got a ticket in our private repository about overhauling this https://github.com/Regalis11/Barotrauma-development/issues/1067, but so far we haven't gotten around to implementing it.

We're also in the process of refactoring the modding system and writing better documentation for it, so hopefully figuring this type of stuff out should get easier in the future.

>Re-tried with file type: None , indeed no error anymore. Weird. Will keep an eye on it.
Tried to sneak ragdoll file into the mod under Character tag - more errors. Well... disregard that. More than a note to self to make everything None if in doubt.

As for this: you generally don't need to use the content type "None" for anything: it's just the default type for content files until you specify what kind of content they actually are. They won't do anything by themselves.

**Comment by DrinkFromTheCup** [comment]
Thank you for exhaustive response, @Regalis11 .
As I don't possess in-depth intel on real plans and intended designs, yet am really liking the game (and the intent behind it), of course I'm a bit too jumpy when it comes to such cases where both extra good and extra bad outcome are equally possible (from a bystander-like-me's point of view). Especially after witnessing so much crappo on my previous jobs (which were related to design&development).
I hope that my... unforbearance with words selection didn't impacted anything negatively today. And I cordially apologize if it did.

**Comment by Regalis11** [comment]
> I hope that my... unforbearance with words selection didn't impacted anything negatively today. And I cordially apologize if it did.

No, not at all! :) I don't think anyone should hesitate to point out flaws or possible bugs in the game. Even if there's the chance something is a WIP feature rather than a bug, there's always the chance it is actually a bug we're not aware of. And if nothing else, pointing out things like this serves as a reminder to us about these flaws that still need our attention.
