### ISSUE TITLE
Medic Bot dialogue error (low priority)

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8236]
- [Yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Medic bot reported that they resuscitated me, but I was not unconscious or close to death. Resuscitating typically refers to reviving someone from near death/unconsciousness.

**Steps To Reproduce**
Take a minor amount of damage and let a medic bot heal you. Getting injured enough to cripple a limb may be ideal.

**Version**
Unstable v0.16.4.0

**Additional information**
I know this is extremely minor, but an error's an error. At its worse I can it being confusing to see a report that someone was brought back from the brink of death when they were not really close to death.

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@fab8393

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
