### ISSUE TITLE
Bandit's Attacks are Very Slow 

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8238]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bandits have a long downtime period in-between attacks. I haven't timed it, but it certainly feels like they will fire/swing their weapon only once every 10 seconds or so. This makes fights incredibly clunky as there is a lot of the bandits just standing there, firing a shot, and then standing completely still while you hit them until they fire a second shot 10 seconds later. Looks especially weird on knife-wielding bandits as they just hover around you, waiting to stab you again.

**Steps To Reproduce**
Start a bandit outpost mission and walk up to a bandit. 

**Version**
Unstable v0.16.4.0

**Additional information**
Best way I could describe it is that bandits act as if they are in a turn-based game, while players are free to do everything in real time. With no health boosting perks or medicine, they are a cakewalk with just simple body armor. They really do not feel like a mid-game threat.

**Comment by itchyOwl** [comment]
Seems to work as it should. The bandits (and also most pirates) just seem to have very low aim speeds. Values closer to 1 feels more natural, but it's a question of balance too. Personally I think they are way too easy now. I'll look into it.

**Comment by LePiromano** [comment]
considering the fact most bandits have only 40 health and a knife/revolver, i think it's fair to give them a rather quick reaction time

**Comment by Regalis11** [comment]
Since @itchyOwl is off this week I went ahead and increased the aim speeds a bit to get the changes to the unstable sooner. Might still need some adjustments.

https://github.com/Regalis11/Barotrauma-development/commit/e698f3b44737525c9b85e2b282a1d3aa4f02637e

**Comment by itchyOwl** [comment]
Based on a quick test the reaction times feel ok to me now.

**Comment by Rokvach** [comment]
Tested, no issues.  Closing.
