### ISSUE TITLE
Enemies can spawn inside piezo crystal icebergs

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8244]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Enemies can spawn inside the rocks  where the piezo crystals are.
![image](https://user-images.githubusercontent.com/55637865/153688788-9bd04968-1ef8-43e7-9795-d2833b0fbf78.png)
(that's a whole spineling swarm inside a piezo crystal rock)

**Version**
0.16.4

**Comment by itchyOwl** [comment]
There's more information in a more recent ticket here: #10026. Closing this one as a duplicate (although the new ticket is actually the duplicate).

**Comment by Regalis11** [comment]
Reopening, https://github.com/Regalis11/Barotrauma/issues/10026 seems like a different issue (piezo crystals aren't destructible rocks)

**Comment by Regalis11** [comment]
Nvm, misread this, they don't seem to spawn inside the crystals themselves
