### ISSUE TITLE
Diving Suit - offset when placed in a Diving Suit Locker

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#8247]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shifting at the right side:
![Image 001_15-04](https://user-images.githubusercontent.com/93348499/153710794-4a846414-66c4-4bea-b019-9bac74f216f0.png)

**Steps To Reproduce**
Put the suit in the closet

**Version**
v0.15.23.0, Vanilla 0.9 (Windows 10-x64).

**Additional information**
No.

**Comment by Regalis11** [comment]
I'm not sure I understand the problem: I can't see anything wrong at the right side. I noticed that the suit is drawn slightly too far up though (the window on the cabinet seems to move a couple of pixels up when you put the suit in), is that what you meant?
![image](https://user-images.githubusercontent.com/14351070/153858605-953c0ec3-756f-452b-8d76-20e1a47ddb52.png)

**Comment by Regalis11** [comment]
Fixed the vertical offset in https://github.com/Regalis11/Barotrauma-development/commit/99d0323438db547c4fd84177fcbf9bb92221551f

**Comment by MaaiG** [comment]
I think the suit is not in the center of the cabinet.
![153710794-4a846414-66c4-4bea-b019-9bac74f216f0](https://user-images.githubusercontent.com/93348499/154034674-2174fb51-3228-4422-8783-0cfa7afcf1c8.png)

**Comment by Regalis11** [comment]
Ah, I see! I wouldn't consider that a bug though, that's just the way the sprite looks.
