### ISSUE TITLE
Handcannon round stack size remains the same

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8252]
- [yea] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Shotgun shells, revolver rounds, and even explosive slugs got their max stack size changed to 12, but the handcannon round's max stack size is still 8

**Version**
v0.16.4

**Additional information**
(can you increase the handcannon damage a bit 🥺)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c7ae224e7ea045ec1072966988ee674b10e9847

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
