### ISSUE TITLE
Multiplayer campaign inventories resetting.

### ISSUE THREAD

**Issue by CLASSlCS** [Regalis11/Barotrauma#8255]
- [+] I have searched the issue tracker to check if the issue has already been reported. There's some similar ones, but they're not detailed enough for me to be sure they're trying to report the exact same issue.

**Description**
When you join mid round of a campaign you've previously played, and don't get to spawn in before the end of the round, bug causes your inventory to be reset, permanently deleting all items they previously had, and your character spawns in with their class's starter items.

**Steps To Reproduce**
1. Play on a multiplayer server, as a connected client, not the host.
2. Get items in your inventory.
3. Disconnect with your items on you, or host saves and quits from station.
4. Rejoin at a later time mid-round. (your character must be not spawned in, so can't be the same round you disconnected from)
5. Spectate and/or wait for round to end. (do not spawn in mid-round, either do it on a campaign with respawning off or do it such that the round ends before your character spawns in)
6. Next round starts and your character spawns in.
7. Now, instead of having the items from when you disconnected or played last, your inventory will have reset to initial class starter items.

**Version**
0.15.23.0 Release Windows

**Additional information**
This bug seems to be highly re-creatable and occurs almost every time you join mid-round and don't get to spawn in before the next round in a campaign you've previously played.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
