### ISSUE TITLE
Spelling mistake in notice box.

### ISSUE THREAD

**Issue by Demyxa** [Regalis11/Barotrauma#8263]
![image](https://user-images.githubusercontent.com/48883376/153751486-f889fb47-bdab-4f09-abbc-b2437f6c6595.png)

Stowage uwu!

I did not mod this. This is in the game. Submarine used is the new Barsuk.

**Comment by Regalis11** [comment]
This is not a spelling mistage.

https://en.wikipedia.org/wiki/Stowage
