### ISSUE TITLE
(unstable) Editor's Playtest mode: AI Captain keeps switching autopilot on for absolutely no reason

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#8268]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
In playtest mode, AI captains are not expected to interact with sub controls unless asked.
But they do.
Which doesn't look right...

(didn't tried in actual gameplay yet since I'm at the helm as Capt'n anyway.
But somehow I have a feeling that AI Captains might do these things to players there too.
Especially if the player did hired a backup captain.)

**Steps To Reproduce**
Load any sub in Editor.
Start Playtest Mode.
Swap to Mechanic.
Set stirring mode to Manual > any direction you like at navigation console.
Exit navigation console. See Captain running, heels above head, to switch it back to Auto > Maintain Position.

**Version**
Today's Unstable.

**Additional information**
Noticed this weird stuff when fiddling with my handicapped sub from bug report #8267 .

**Comment by Regalis11** [comment]
I wouldn't necessarily consider this a bug: the default "autonomous objective" for the captains (= what they do when they have no explicit orders or any emergency to deal with) is to helm the sub, and the default behavior for that objective is to maintain position.

I can see this being a minor inconvenience, but changing it could lead to other kinds of problems: if you for example switched to another character without having assigned any orders for the captain and they just left the nav terminal to whatever state it was (or started navigating somewhere else on their own), you might end up crashing to a wall or consider it a bug when the captain suddenly sets a course somewhere else.

While we _could_ change this behavior in the test mode and make the captain leave the nav terminal alone, I'm not quite sure if this is a good idea either: having the bots behave the same way in the test mode and during normal gameplay is in my opinion a good thing from the perspective of testing.

**Comment by DrinkFromTheCup** [comment]
Sounds reasonable. Well, I'll have to spawn extra pair of handcuffs during my experiments, then... unless auto unhandcuffing would make it into the release.

I'd like to mention, however, that while Captains auto-Holding Position for my sub without my explicit reminder is a neat feature, sometimes I do know what I'm doing when setting the course somewhere then switching from Captain to someone else for extended periods of time...
Necessity to have all present AI Captains controlled, occupied or restrained just to enact some tactical maeuver unhindered seems to be a bit too... unnecessary. Manageable, yet these extra IQ points for AI could have better applications.

**Comment by Tsunder** [comment]
in test mode, there is no level generated, so having the captain touch the nav terminal has... I'm not sure what advantages there is really to that.

mostly I will use disablecrewai or order everyone to hold position though (because I like to swap characters better than teleport)
