### ISSUE TITLE
"Gate outpost" between biomes got wiped out by radiation

### ISSUE THREAD

**Issue by RostKostia** [Regalis11/Barotrauma#8269]
helo devs
While in the first location you can run out of outpost and then you are locked inside this location. Because you can't buy a ticket to the next location. 
Also we had a very strange bug with our Security officers. After our arrival to the station we were kicked out of the game (only Security). And our genes and gear just disappeared. without bags or dead bodies.

**Comment by Regalis11** [comment]
Thank you for the report!

> While in the first location you can run out of outpost and then you are locked inside this location. Because you can't buy a ticket to the next location.

Just to check, was there an outpost at the next location? If not, you just need to select a new destination by pressing the "select destination" button that appears at the top of the screen when you reach the end of the level.

> Also we had a very strange bug with our Security officers. After our arrival to the station we were kicked out of the game (only Security).

Do you happen to remember if there was some kind of an error message when you got kicked out? We have a couple of existing tickets about similar issues, but it's hard to say whether this is something new without knowing what caused the disconnect.

**Comment by RostKostia** [comment]
No there were no outposts. We were loxked inside cold caves.
Yes we had an error message something about equipment. Only security was
kicked all others were fine.

пн, 14 февр. 2022 г., 11:13 Joonas Rikkonen ***@***.***>:

**Comment by Regalis11** [comment]
Ahh, do you mean you were locked in the cold caverns biome, and couldn't get to the next biome because the outposts got wiped out by radiation? That should never happen (the radiation should never kill the "gate outpost" between biomes), but sounds like that could be bugged somehow.

**Comment by RostKostia** [comment]
Yes exactly. Thank you for your effort. Your game is very fun and devs are
listening to their players. Thank you x2.



пн, 14 февр. 2022 г., 19:25 Joonas Rikkonen ***@***.***>:

**Comment by Regalis11** [comment]
No known steps to repro, closing
