### ISSUE TITLE
Railgun with Oxygenite Shard destroys own hull when fired

### ISSUE THREAD

**Issue by Aku230** [Regalis11/Barotrauma#8286]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After changing non-default-railgun weapon slot to a railgun, loading railgun shell with oxygenite shard and shooting it at specific angle will detonate oxygenite shard "in chamber" causing massive dmg to own hull.

**Steps To Reproduce**
1. Start a Campaign with ship that has a non-railgun weapon slot on an angled surface
2. Replace said weapon with Railgun
3. Insert Oxygenite Shard inside Railgun Shell
4. Line-up gun chamber with its base and shoot

**Version**
0.15.23 and 0.16.4

**Additional information**
I have tested it on Orca, Orca2, Humpback, Berilia, Azimuth.
I have not noticed this behaviour with UEX or C4.
I have not noticed this behaviour when gun base is horizontal/vertical or with default railgun that is placed at an angle.
The bug will also occur when you swap angled railgun to other weapon and then back to railgun.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/15c62c14f072c3cfe0aa0b4ab4db481a92bf7e8c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
