### ISSUE TITLE
Players get Kickout of the session when connecting to match

### ISSUE THREAD

**Issue by MGSantic** [Regalis11/Barotrauma#8289]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players with either better connection or better equipment in their PCs are Kicked Out of the match if the connect into the game before the Server Owner connects into the match.
REPRO RATE: 5/5

**Steps To Reproduce**
1.Start a match with a group
2.Spawn in an Outpost
3.Accept a mission
4.Start the Quest
5.Wait until Loading Finishes
**EXPECTED  RESULT**
Players are flushed into a match
**ACTUAL RESULT**
Players who connect before of the Server Owner get Disconnected from the match

**Version**
v0.15.23.0
Windows: Occurs
Linux: Not Tested
Mac: Not Tested

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report! Do you recall what kind of an error message the players get when they disconnect (if any)?

**Comment by Regalis11** [comment]
I'm afraid there's not much we can do about this without knowing what the error message was
