### ISSUE TITLE
Server browser causes game to stop responding temporarily when loading

### ISSUE THREAD

**Issue by Calyxman** [Regalis11/Barotrauma#8290]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I click on the server browser, the game freezes up for maybe a minute and then loads the server browser.

**Steps To Reproduce**
Step 1(?) Maybe have a lot of mods and custom subs, like me.
Step 2. Open server browser.
Step 3. Use optical organs to detect problematic occurrence.

**Version**
Windows 10, v0.15.23.0

**Additional information**
This seems like it should have been fixed a while ago, there doesn't seem to be a clear fix in any of the previously made bug reports.

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6511
