### ISSUE TITLE
IDcard description is not added when the ID card tags of the spawnpoint are empty.

### ISSUE THREAD

**Issue by az689** [Regalis11/Barotrauma#8294]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As the question

**Steps To Reproduce**
1. Fill in the description for the spawnpoint and keep the ID card tags empty
2. Enter the game, the description is not added

**Version**
0.15.23.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/923788033cd9258ae1726db1b684d130ff9a6e63

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
