### ISSUE TITLE
IDcard descriptions are lost

### ISSUE THREAD

**Issue by az689** [Regalis11/Barotrauma#8295]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
IDcard description set at the spawnpoint seems to be lost when saving, regardless of whether the id card is on the submarine or on the character.
IDcard description exists when creating a new save for a single player campaign, if you don't save and exit, the id card description still exists when re-entering, if you save, the description disappears when re-entering.
Create Multiplayer campaign save and enter game,ID card description exist, but whether it is saved or not, the description will disappear when entering again.
After the multiplayer campaign save is created, check the character file, no IDcard description is found, the ID card description was lost at the time the save was created.

**Steps To Reproduce**
Prepare a working submarine, exclude extra spawnpoints, add descriptions to spawnpoints and fill in IDCard tags (to prevent triggering #8294)

- Singleplayer mode:
	1. Create a new campaign, enter the game, the description is normal
	2. Do not save and exit
	3. Re-enter the campaign, the description is normal, you can repeat 2-3 steps to try more times
	4. Enter the campaign, save and exit
	5. Enter the campaign again, then the description is lost
- Multiplayer mode:
	1. Create a new campaign, enter the game, then the description is normal
	2. Check the character file, there is no ID card description
	3. Save/not save and exit, when you enter again, the description disappears
	
**Version**
0.15.23.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4090e6e91d24948096c80d4a1352e2eab69738e1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
