### ISSUE TITLE
Force Update Super Capacitor Values in Unstable Ver.

### ISSUE THREAD

**Issue by ArianHeight** [Regalis11/Barotrauma#8296]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It appears that changing to the unstable version and loading an existing sub with custom capacitor values results in those custom values betting overwritten by new default values. This is a problem for some of my subs that have supercapacitors with custom and drastically different parameters. I am using supercapacitors to buffer load basically and those values getting changed causes entire electrical systems to not work.

**Steps To Reproduce**
-Find a sub from the stable version of the game that has a supercapacitor with a modified recharge rate(I use GreateWhiteShark, the capacitor on the engine is modified)
-Load it in the sub editor in the unstable ver.
-Select the modified super capacitor and see that the values have been overwritten by the new default values

**Version**
Unstable 16.4.0 on Windows

**Additional information**
Is it possible to only update supercapacitor parameters that haven't been modified to the new default?
Thank you.

**Comment by ArianHeight** [comment]
There has been new power/electrical system changes so maybe it's alright if this issue gets tossed

**Comment by Regalis11** [comment]
Yeah, I'm afraid there's probably no easy/robust way to automatically make all of the custom subs work properly after the changes done to the capacitors. So manual adjustments to capacitors that are being used in a non-standard way will be required in the next update. Sorry for the inconvenience! :/

**Comment by ArianHeight** [comment]
all good, thnx for taking a look~
