### ISSUE TITLE
Unable to delete letters in text chat?

### ISSUE THREAD

**Issue by Calyxman** [Regalis11/Barotrauma#8298]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to delete English letters in text chat on multiplayer.

**Steps To Reproduce**
Step 1. Try using text chat
Step 2. Try deleting a letter
Step 3. Use optical organs to observe problem

**Version**
v0.15.23.0

**Additional information**
Happens only sometimes. Other times it works fine.

**Comment by Regalis11** [comment]
Thank you for the report!

Unfortunately I couldn't observe this problem with my optical organs. I guess it might require some more specific circumstances to happen, but I couldn't figure out what it could be.

https://user-images.githubusercontent.com/14351070/154227715-fe0c19bf-0e48-4e71-b746-93f4704262ad.mp4

**Comment by Calyxman** [comment]
I used backspace. This only happens sometimes, and quickly goes away. Maybe a really obscure bug?
I'll close it if you still can't figure out, and it's relatively minor.

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by Calyxman** [comment]
Just here to say that I've figured a fix: close anything other than Barotrauma, maybe text boxes in other programs are selected when you hit backspace?
Pretty weird, not sure if this is fixable either.
And.. sorry for necro, had to post in case anyone else had this
