### ISSUE TITLE
Discrepancies between talent effects and descriptions and other unusual talent behaviours.

### ISSUE THREAD

**Issue by Cherman0** [Regalis11/Barotrauma#8299]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**

- [x] .xml data for In The Flow contains a 25% buff to swimming speed that is not mentioned in the description (likely intentional but missing from the description).
- [x] .xml data for Polymath shows that it boosts all experience gains, not only "mission experience" as the description states (possibly intentional but the description is incorrect).
- [x] .xml data for Mass Production shows that it sets the `TinkeringPowersDevices` flag despite not claiming to do this in the description and this making the same effect from Let It Drain redundant.
- [x] .xml data for Pyromaniac shows that the 40% physical damage resistance for 5 seconds actually decays to 39.9% physical damage resistance over those 5 seconds.
- [x] The description for Atmos Machine claims that artifacts may "instead" be transformed into another alien item when deconstructed, but deconstructed artifacts that transform still give their original deconstruction loot (likely the intentional behavior but the description is incorrect).
- [x] .xml data for Atmos Machine shows that it will never create a Psychosis Artifact, and that the Alien Power cell is on the loot list twice.
- [x] .xml data for Deep Sea Slayer contains duplicate code for granting the permanent 25% harpoon damage boost.
- [x] .xml data for Insurance Policy shows that it gives 100% Reaper's Tax resistance that is not mentioned in the description (likely intentional but missing from the description).
- [x] .xml data for Inspiring Tunes shows that the repair effect from honking a bikehorn has a range of 500, whereas all other effects from honking a bikehorn have a range of 600 (possibly intentional but unintuitive).
- [x] Survival Package gives the listed items after every round end where a mission was completed. However, the talent description simply lists the items without telling how they are obtained, which is unlike every other talent which gives items on mission completion (likely intentional behavior but missing from the description).

**Steps To Reproduce**

- Open the .xml data for the talents found at `Barotrauma\Content\Talents` and navigate to the entries for the listed talents.

**Version**

- Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Additional information**

- These oddities were discovered when reading the .xml data for the talents in order to add more information to the wiki.

**Comment by Cherman0** [comment]
As of 0.19.11 those all seem to be in the game? Unless I'm wildly misinterpreting what you're saying, I'm not aware of any talents being removed. Some of these have been fixed in the meantime, such as the extra TinkeringPowersDevices flag and the Atmos Machine loot table, but I don't believe any descriptions have been updated.

**Comment by Regalis11** [comment]
@Cherman0 We are working on a talent overhaul atm: it's not out to the public yet but many of these talents have been removed in our private repository
