### ISSUE TITLE
Barsuk Pricing Inconsistent

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8302]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The price of the Barsuk is 3,999 marks. Every other vanilla sub's pricing is a multiple of 100. 
![image](https://user-images.githubusercontent.com/91236493/154190322-81670e55-08bd-40d3-ba6e-9a2ad819a539.png)

**Steps To Reproduce**
Look at the sub pricing at the start of a campaign

**Version**
Unstable V0.16.5.0

**Additional information**
The one spare mark haunts me

**Comment by Regalis11** [comment]
This is not a bug. I think it's thematically appropriate for a cheap entry-level sub like Barsuk to use This One Weird Pricing Trick That Makes It Seem Cheaper Than It Is™.
