### ISSUE TITLE
Unstable - Giant Spineling too powerful for early mission

### ISSUE THREAD

**Issue by brjc** [Regalis11/Barotrauma#8306]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Giant Spineling is too powerful for early missions and has about 0% success chance if taken.

**Steps To Reproduce**
1. Putzing around on single player
2. Back and forth between first settlements
3. Maybe 6 mission sets completed so far
4. Using Humpback, 6~7 crew
5. Accept Giant Spineling mission
6. Fight Giant Spineling
7. First shot tears entirely through sub
8. Death

**Version**
Unstable 0.16.4.0, rev a92cd175a9
Windows 10 Home

**Additional information**
This monster seems significantly stronger than Tiger Threshers, Hammerheads, or Mollochs. Mission difficulty indicator is the same or lower, and reward is lower for Giant Spineling compared to other big monster missions.

**Comment by brjc** [comment]
Additional note - I was able to defeat it by having the entire crew pre-stage with diving suits on. Still, this level of challenge for only 3000 marks feels off.

**Comment by LePiromano** [comment]
The giant spineling still dies to 1 railgun shell, it's just a comically large glass cannon. I think it's mostly fine and the mission reward is fair if you compare it to other hunting missions.

**Comment by itchyOwl** [comment]
It's supposed to be a deadly and still relatively weak enemy. Tearing the submarine with single shots is intentional, but it's not an enemy that you should be facing too early on. Feedback taken, I'll take it into account.

**Comment by itchyOwl** [comment]
Adjusted the missions slightly in Regalis11/Barotrauma-development@2be4410.

**Comment by LePiromano** [comment]
3500 is good if you ask me, i don't know what the ticket's creator thinks

**Comment by Rokvach** [comment]
No issues, closing.
