### ISSUE TITLE
Removing or changing order priority gives the commander talent buff

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8308]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you remove an order or change the priority of a crewmember's orders while having the commander talent, you'll give the crewmember the buff.
The talent's description specifies it only gives the buff when giving an order, plus it makes it difficult to know which bot/crewmember currently has the buff

**Version**
0.16.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f7565b2de056c9acd0a0e09c073279d1b9c48908

**Comment by Regalis11** [comment]
The fix didn't fully solve this, see https://github.com/Regalis11/Barotrauma/issues/8445

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
