### ISSUE TITLE
depleted fuel coilgun ammo is broken

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8309]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Depleted fuel coilgun ammo seems to be currently the most versatile combat item in the game, it's cheap (since fuel is not rare), it melts small monsters, medium and large targets die easily no matter if you hit the armor or not, abyss creatures eat half of a box and then start getting 300 damage per second because of the radiation, plus there's no monster armor in the game that protects against radiation. And it's a tier 1 talent item.
Some other ammunitions or weapons are better in certain situations but depleted fuel ammo is a cost efficient jack of all trades, i see a lot of people covering their subs with nothing but coilguns with depleted fuel ammo.
(I was gonna put it in discussions but it seems to be more of an issue than my own opinion)

**Version**
0.16.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57ca65273a15c06667937942bc6d41e5e0023674

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
