### ISSUE TITLE
showperf overlaps crew UI

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8314]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The showperf data overlaps with the crew UI, obscuring microphone and orders

**Steps To Reproduce**
showperf and have crew menu open at the same time

**Version**
0.15.23

**Additional information**
![image](https://user-images.githubusercontent.com/5103517/154778674-a29810dd-63dc-435d-8282-f1b81400bb98.png)

**Comment by Rokvach** [comment]
This has hindered my testing previously as it does hide some important information from the crew list, so can't play properly while its on.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/01d3faa917e9a2ae09b61fe0e64e28cf173ac938

**Comment by Rokvach** [comment]
Tested, no issues, closing.
