### ISSUE TITLE
Objects become unselectable after refreshing shuttle in editor

### ISSUE THREAD

**Issue by sakari119** [Regalis11/Barotrauma#8315]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ive been working on a custom sub, and large segments of the submarine become unelectable while in game after I refresh a shuttle

**Steps To Reproduce**
The sub and shuttle combo
[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/8102115/Submarines.zip)
Load the Azure Mk2
Refresh the shuttle
Test the sub
Some of the components may become unselectable (entirely random) usually the junction boxes on the top row

**Version**
v0.15.23.0 Windows release
Windows 10, version 20H2, OS build 19042.1526

**Additional information**
Uhh Idk

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I couldn't find a way to reproduce this. Tested by repeating the steps a bunch of times and also by saving and reloading the sub and the shuttle a bunch of times. 

How exactly do the items become unselectable - are you unable to highlight them at all, or does nothing happen when you highlight and click them?

**Comment by sakari119** [comment]
You become fully unable to select them while in test mode, when testing a version when the junctions become unelectable, physics in that room becomes, glitchy
[Video](https://cdn.discordapp.com/attachments/427654262453960724/944555241024667668/2022-02-19_12-24-36.mp4)

**Comment by Regalis11** [comment]
No known steps to repro, closing
