### ISSUE TITLE
Medic AI will not heal crewmates on other docked subs/shuttles

### ISSUE THREAD

**Issue by Punchington** [Regalis11/Barotrauma#8322]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you've ever done an Outpost mission, you may be aware that, while security can be ordered to attack intruders and they'll climb up into the outpost to kill... whatever... medics will only heal characters on the same sub.  However outpost missions aren't the only thing this bug affects.

If you have a shuttle on your sub, and if a character in that shuttle is injured, medics on the main sub ordered to heal crew will not recognize that injured character until they're both on the same sub.

This is problematic with my current sub design as I'm using shuttles (or "trams") to bridge the two ends of my sub.  What ends up happening is, if the medic is on the left side of the sub and an injured engineer is on the right side, the medic will start crossing the trams to reach the engineer; the moment the medic steps into the trams, they stop trying to reach the engineer and end up never treating them.  This means you can't assign the medic to a periscope on the left side of the sub because the moment they step back onto the sub, they will try to cross and heal the engineer again and fail over and over.

As far as I know, no other order is affected in this sense - repairs, intruders, these key orders work across docking ports (I think cleanup also works, too), but the heal order does not for whatever reason.

**Steps To Reproduce**
Easiest way to test this is to do an outpost mission.  Assign someone the Heal and Rescue order and then proceed to board the outpost and get shot/bitten. That crewmember will not come into the outpost to treat you. To get treated, return to the sub; the moment you re-enter your sub, the crewmember should start trying to treat you.

If you order the crewmember to follow you onto the outpost and then dismiss that Follow order, they will then heal you if you get hurt in the outpost, but yet again if you leave the outpost and re-enter your sub, they will no longer try to heal you as you are not in the same vessel.

**Version**
Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Additional information**
You can refer to my previous issue post regarding Cargo and Escort missions for an image of my sub to get a better sense of why this can be very problematic.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3fdbb6776c6d8ceed67d61c828da4cda8ae912a0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
