### ISSUE TITLE
AI will not attack across docking hatches/ports

### ISSUE THREAD

**Issue by Punchington** [Regalis11/Barotrauma#8323]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI crewmembers given the Fight Intruders order will target enemies on docked shuttles/subs, and will even aim guns at monsters across docking ports and docking hatches.  However they will not actually open fire unless both characters are within the same sub.

Because they're able to see and target the aggressor, they will not cross the docking port/hatch to engage unless they're trying to use a melee weapon. As a result you may end up with all your Security Officers looking down into your shuttle or drone watching assistants and who ever else getting mauled trying to escape, and not one of them will open fire so long as they have a clear line of sight and the target is on a different sub.

**Steps To Reproduce**
Create or use a sub that has a shuttle/drone docked in which the doors/hatches remain open while docked. Spawn monsters in the shuttle/drone under the hatch or across the door (depending on the docking arrangement), and order Security Officers or anyone equipped with a gun to Fight Intruders. They will approach the docking port/hatch and, provided a monster is visible from outside the drone/shuttle, they will aim at the monsters from within your sub, but will not fire their guns.

**Version**
Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Additional information**
The sub I'm presently working on has two trams used to cross the sub. I can confirm with these that both docking ports and docking hatches are affected by this - AI will not shoot monsters across the two trams, even if there's a clear line of sight, until the monster enters the same tram as the crewmember(s). They will also not shoot down at monsters in the sub from within the trams, just aim menacingly.
![image](https://user-images.githubusercontent.com/97642079/154827183-7480ac78-70f8-4e18-a941-434033f5a330.png)
_This image was taken in the sub editor, shuttles merged for the screenshot. In normal play, the doors and hatches are open while docked._

**Comment by itchyOwl** [comment]
Can be easily reproed on Remora by teleporting a bot near the shuttle docking port and giving a fight intruders order, then spawning a monster inside the shuttle and taking the control of it:

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/2153dc6f-430a-4b4b-8d1c-2cb6626a409d)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@1b5bac7 (ai-fixes-january2)

**Comment by Regalis11** [comment]
Tested the following:
- Bot firing from a sub to another (used the same test setup in Remora as you)
- Bot firing at a monster inside a sub
- Bot firing at a monster outside a sub
- Bot firing from inside a sub at a monster outside a sub

All seemed to work with no issues. Closing.
