### ISSUE TITLE
Pumps and Engines setting to -39% instead of -40%

### ISSUE THREAD

**Issue by Punchington** [Regalis11/Barotrauma#8324]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Minor issue but weird nonetheless. If you manually try to set a pump or engine to -40%, it will instead snap to -39%.
40% works, just not -40%.

I think at one point while trying to set a pump to -39%, it would, after a brief moment, set itself down to -30%. Not sure what that was about...

**Steps To Reproduce**
Disconnect the automatic control of an engine or pump, and manually try to set it to -40%. It will instead snap to -39%.

**Version**
Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef54b9459a65e0c57eff4763656bb5c070ebdf7d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
