### ISSUE TITLE
Unable to interact with Hatch with Buttons across docking hatches

### ISSUE THREAD

**Issue by Punchington** [Regalis11/Barotrauma#8325]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
May need further testing, but I tried using a Hatch with Buttons for my sub's main docking port and intended for it to only lock closed when undocked - otherwise it could be freely opened and closed while docked to stations. In practice, while testing in a MP Campaign*, I could not open the hatch from within the station's airlock.

From my point of view, it would open, then close itself, and my character could not go through at all. I only managed to get through after glitching my character through the hatch itself (crossing docking ports is already kinda glitchy on its own), and I was able to open the hatch from within.

I have an older docking port assembly that uses individual, separate Buttons for its Custom Hatch, and I haven't had any issues with it in the past, so I think it's just Hatch with Buttons' that's affected.

_*Side note: I've only tested this docking arrangement in MP, not sure if this persists in SP._

**Steps To Reproduce**
Take a sub and remove its existing Docking Hatch and Custom Hatch and all the components relevant. Replace it with a new Docking Hatch - wire its toggle state to your Nav Terminal - and a Hatch with Buttons on top of it like a normal docking port. Start a Campaign in Multiplayer, and attempt to open the Hatch with Buttons and board your sub.

**Version**
Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Additional information**
I have tried shifting the hatch up and down but to no avail. If this _is_ just a placement issue, any advice on how to position the hatch is appreciated.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b109241bcf1aacfbb9257523c7306f19e5e96a53

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
