### ISSUE TITLE
Ducts, Doors, and Hatches returned by Item Finder

### ISSUE THREAD

**Issue by Punchington** [Regalis11/Barotrauma#8326]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Not sure if this is a bug or intended, but if you use a Status Terminal's _Item Finder_, you can search for Ducts, Custom Hatches, Custom Doors, Hatch with Buttons, and Door with Buttons, and all of these will come up as items, even though they're static items integrated into the sub.

**Steps To Reproduce**
Start a round on a sub and interact with its Status Terminal. Enter the Item Finder tab and search for Duct, Door, or Hatch.

**Version**
Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Comment by Regalis11** [comment]
This is not a bug, as they are technically items
