### ISSUE TITLE
Launcher missing

### ISSUE THREAD

**Issue by FritzGessler** [Regalis11/Barotrauma#833]
Downloaded Barotrauma again. I have a missing launcher but I have the executable file.

**Comment by ZealanL** [comment]
You may have to scroll down a bit, or search for _Launcher.exe_ in your file explorer. I've never had a situation where he launcher was not included in the game folder, but sometimes it takes a minute to find. I suggest pinning it to your taskbar.

**Comment by BlueTheKing** [comment]
Both fresh downloads on the website are missing the launcher. 
Grab a launcher from .12 and run that.

**Comment by Regalis11** [comment]
Fixed now, sorry for the inconvenience!
