### ISSUE TITLE
Common hammerheads attack stronger creatures, golden hammerheads don't.

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8334]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The golden hammerhead is stronger and has a higher combatstrenght than the common hammerhead, but it's set to avoid fighting stronger creatures. The common hammerhead will attack pretty much everything. I'm guessing this is an oversight?

**Version**
v0.16.5.0

**Comment by itchyOwl** [comment]
They are meant to behave differently, but that decision is a remnant of an older design. Behavior changed to PassiveAggressive in Regalis11/Barotrauma-development@df91df1.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
