### ISSUE TITLE
Spawning Bots inside with cheats does not respect assigned jobs of spawnpoints

### ISSUE THREAD

**Issue by Punchington** [Regalis11/Barotrauma#8335]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A similar bug was reported back in March of 2021 (#5193) regarding AI spawned in without correct IDcard tags, but to expand on that issue, using the `spawncharacter ___ inside` command to spawn Engineers, Mechanics, Captains, Security Officers, Medical Doctors, Assistants, or any other character with a dedicated Assigned Job for spawnpoints will spawn them at **any** Human spawnpoint on your sub.

This leads to spawned-in crew having tags for the wrong job whenever they spawn at an inappropriate spawnpoint. For instance I could enablecheats and use `spawncharacter Engineer inside`, and an Engineer could spawn at a Security Officer's spawnpoint with the Security Officer's tags, and vice versa.

This can make sub-testing harder since spawning in crew is the only way to test tags for non-Engineers, -Mechanics, and -Captains, since these are the only roles spawned by default when testing subs - and even then, there's no guarantee that characters will have the intended tags you're trying to test.

This applies to SP and MP sessions and is a general fault of this cheat command's arguement.

**Steps To Reproduce**
Open a sub in the editor that has job-assigned spawn points, where some of them (in this case, lets say Security Officers) have tags providing clearance to things like doors or secure cabinets. Test the sub, and open the console (F3), and enter `enablecheats` and `spawncharacter "Security Officer" inside` over and over, and observe as they spawn at random Human spawnpoints. Take control of some of these characters and attempt to access the doors or cabinets that they're supposed to have the tags for. Only the one or two that actually spawn at the right spawnpoint will have the correct tags.

You can try this with any role and notice that Assistants, or Engineers or whatever you've spawned inside, who spawned at Security Officer spawnpoints have the Security Officer tags.

**Version**
Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
