### ISSUE TITLE
Missing the name translation of biome "the great sea" in Simplified/Traditional Chinese

### ISSUE THREAD

**Issue by lzhou1998** [Regalis11/Barotrauma#8336]
- [ √] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The fourth biomes "the great sea" has no translation in Simplified/Traditional Chinese, and show as a blank in campagin map and in the start of a round. This situation lasted for years and has not been fixed until now.

This translation tag can be found in
line 4352, path\to\Barotrauma\Content\Texts\SimplifiedChinese\SimplifiedChineseVanilla.xml
line 4352, path\to\Barotrauma\Content\Texts\TraditionalChinese\TraditionalChineseVanilla.xml

**Steps To Reproduce**
As above

**Version**
v0.15.23.0, ReleaseWindows

**Additional information**
If need help to translate, I can start a vote in Chinsese community of this game.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d89f5f475bef74ed36d9b45b26c53e928bd8a955

**Comment by Rokvach** [comment]
No issues, closing.
