### ISSUE TITLE
Successive events in the Jacov Subra event chain may be too uncommon

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8337]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
According to Discord

> Part 3 is currently bugged and you have to input "triggerevent assassinationofjacovsubra3" in the console while being in an outpost (requires cheats), then look around for a wall paper you can interact with.

**Steps To Reproduce**
Try to complete the event chain I guess

**Version**
Any

**Comment by LePiromano** [comment]
That's my fault, I wrote the tag while the event was broken and didn't edit it after https://github.com/Regalis11/Barotrauma/issues/6079 got fixed. It does work, I managed to complete the full event chain.

**Comment by LePiromano** [comment]
It does feel like the event doesn't work sometimes because you aren't guaranteed to get part 2 after  completing part 1, same with part 3.

**Comment by Regalis11** [comment]
It seems the game doesn't "automatically" continue the event chain: you need to get the successive events by chance as one of the randomly selected scripted events.

I think we should consider forcing the events to appear or increasing their probability: now it seems pretty rare for a player to get through the whole chain.

**Comment by LePiromano** [comment]
same with the shockjock event, i don't think i've ever done that one without cheating
