### ISSUE TITLE
Medic and Doctor uniform stats potentially backwards

### ISSUE THREAD

**Issue by Punchington** [Regalis11/Barotrauma#8338]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Low prio. issue but the stats for the Medic and Doctor uniforms may be backwards.

Medic's Fatigues:
_"For frontline medics. Offers some protection against enemies."_
-10% Blunt force trauma
**-10% Lacerations**
-10% Bite wounds

Doctor's Uniform:
_"Makes you look like you might be useful in a medical emergency."_
-10% Blunt force trauma
**-10% Gunshot wound**
-10% Bite wounds

I would have thought that the Medic Fatigues, which have the appearance of body armour, would protect from gunshots, but instead the Doctor's Uniform does when it doesn't look like it should - the Doctor's Uniform better resembles other crew uniforms which protect from lacerations.

Not to mention that the Medic's Fatigues description makes it sound more protective than the Doctor's Uniform even though they're basically the same.

**Steps To Reproduce**
In the sub editor, place a Medic's Fatigues and a Doctor's Uniform down, and hit Test. In-game pick up these uniforms and read their stats, and wear them to see how they look on characters to decide whether or not their stats line up with their appearances.

**Version**
Barotrauma v0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8)

**Comment by Regalis11** [comment]
That's a good catch! I'm not sure if this was an oversight or intentional, but it does make more sense the other way around, so I swapped them in https://github.com/Regalis11/Barotrauma-development/commit/ce40c606310eeeb8b86e2627bf30bdefd325a801

**Comment by Ek-Videogames** [comment]
This is also backed up by the 'first responder' class description, which is equipped with medic fatigues.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
