### ISSUE TITLE
Initialized Beacon Station. Got a notice it was complete. Get to next station and the Beacon Station mission says failed, station remains uninitialized.

### ISSUE THREAD

**Issue by Freight-Train** [Regalis11/Barotrauma#8339]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Re-initialized a beacon station along the way, had a mission for it. Fully functional, all water pumped out, reactor running, everything repaired. Got a notice while in the beacon station that the beacon station was reinitialized(looked like a quest notice). When I got to the next main station, it says mission fail beacon station remains uninitialized.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/59e01790876279770d9ca55dad0789ba8e43da67
