### ISSUE TITLE
Searchlight's 'toggle' connection doesn't work, searchlights don't require power

### ISSUE THREAD

**Issue by lifearoundfreaks** [Regalis11/Barotrauma#834]
What it says in the title. Searchlights have working _IsOn_ parameter, however _'toggle'_ connection doesn't work. I think it's because it's interpreted as a turret and Turret.cs doesn't seem to have a line for _'toggle'_ connection.

Also, they do not require power. Even with no power connection, searchlights still work. This is probably for similar reasons.

**Comment by rico6822** [comment]
I guess that's why vanilla submarines don't have those.
