### ISSUE TITLE
Пропал звук и не могу говорить. Проблема только в этой игре 

### ISSUE THREAD

**Issue by Ebnyl** [Regalis11/Barotrauma#8340]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Thank you for the report!

Unfortunately no-one in the team speaks Russian, but based on Google Translate it seems the game audio stopped working? Please check the audio settings and make sure you have selected the correct audio device.
