### ISSUE TITLE
идея

### ISSUE THREAD

**Issue by nefriston** [Regalis11/Barotrauma#8341]
это добавит дополнительную стадию у толамус и хача
к примеру у 2 стадии трупного паразита жало вылезет изо рта и будут как замена ногам. Дать ему высокую скорость в замкнутом пространстве  и появление в обломках и заброшенных аванпостах  и жуткие звуки и будет крайне жуткое и опасное существо.
Толамус ему можно дать собственный корпус из плоти и свои пули для орудий и возможность плавать
(цель этого поста дать вам образ новых существ)

**Comment by MaaiG** [comment]
Russian is my native language, but what's written here is more like a Google translation into Russian from some other language.

**Comment by Regalis11** [comment]
From what I could make out of this with Google Translate, it seems to be a feature request, which should go in the [discussions](https://github.com/Regalis11/Barotrauma/discussions) instead of the issue tracker.
