### ISSUE TITLE
Game crashes when you held two items and try to swap a resource like a battery to one of the items

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8347]
@Rokvach commented on [Wed Feb 23 2022](https://github.com/Regalis11/Barotrauma-development/issues/3163)

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Equip a screwdriver
2. Equip a stun baton
3. Find a battery cell
4. Use hotkeys to try and equip the battery cell while both of your hands are occupied by the other items
5. Game crashes

**Version**
0.16.6.0 and current Unstable

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8f764ee4-15c2-458c-a900-ae2bf923ed47)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c9d4101574f3ee3698cda54ef09c2f6c4e85c7e

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue anymore, nor did I find other issues whilst testing this. Working correctly, closing.

**Comment by Abkim27** [comment]
Thanks
