### ISSUE TITLE
KastrullDrone doesnt drain all water

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#8349]
**Description**
If KastrullDrone is flooded it cant drain the remaining 10% of the water lowering its ascending speed
![Näyttökuva (1068)](https://user-images.githubusercontent.com/86321358/155320092-2b11defb-8ea4-48c3-9b7e-ff38653aa8e8.png)

**Version**
v0.15.23.0

**Comment by Rokvach** [comment]
Already fixed and working correctly, closing.
