### ISSUE TITLE
Unstable - Bad quick-reloading

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#8352]
**Description**
Quick-reloading - you can just press one button and your weapon is reloaded! Holding a riot shotgun and pressing a button assigned to an inventory slot with shotgun shells will reload it, but it has problems - very common that it doesn't reload right and shotgun shells stack in inventory, not in shotgun. This bug happens with revolvers, harpoon guns and riot shotguns only.

**Steps To Reproduce**
Equip a half loaded revolver and take 4 revolver rounds. Then press a button of inventory slot with revolver rounds. As you see it stack in inventory, not in weapon. If you take 3 revolver rounds it reloads normally.

**Version**
Windows V0.16.6.0

**Additional information**
If number of ammo is more than 6 **or** less, equal to *weapon's max number of ammo minus weapon's number of ammo now* it doesn't happen.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb2767adc060b03f49a6e42ba87c4c7336eaa8e8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
