### ISSUE TITLE
Typhon electrical room lamp is not turned on

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#8353]
**Description**
Typhon has a light in the electrical room that is not turned on in the sub editor
![Näyttökuva (1080)](https://user-images.githubusercontent.com/86321358/155368174-5c71d300-084f-4f7e-aede-9824338846db.png)

**Version**
0.19.14.0

**Comment by NilanthAnimosus** [comment]
Tested against Fix/Typhon-1 commit https://github.com/Regalis11/Barotrauma-development/commit/4682c3d562e62ab969475725c0f397feee26dcaa, no issues found, closing.
