### ISSUE TITLE
Bots accidentally shooting with weapons when they use the underwater scooter

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8354]

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c2a1176.

Steps to repro:
- Tell a bot to prepare for an expedition and to follow you.
- Equip a diving suit and a scooter. Go outside.
- Order your character to wait outside.
- Take control of the bot who is following you.
- Spawn a revolver (or any gun) and load the weapon with some ammunition.
- Equip the weapon.
- Take control of the character you were initially controlling.
- Use the scooter -> the bot should shoot once before using the scooter.

**Comment by Lithosagym** [comment]
Tested, bot no longer shoots once before using the underwater scooter, fixed.

**Comment by Rokvach** [comment]
Closing.
