### ISSUE TITLE
A problem about banning players in multiplay

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#8355]
Hello, devs.
There's a problem which I found when in multiplay.
In multiplay, players with permissions may not be able to ban some players in time, but when they want to ban those players by looking up the server logs, they can't find the corresponding steamID - in other words, they can't ban them.Is there a way to record players' steamID as soon as they connect to server, or there's already a way to make this?Thanks.

**Comment by cshingle** [comment]
@CanXue233 I typically ban people via the following methods
1) right click on their name on the left and select ban
2) Open the console via F3 and type "ban" followed by their name. Good old copy paste works here.
Are these options not working for you?

**Comment by CanXue233** [comment]
I know that, but in some case, we can't find out who we want to ban in time because of returning to the server interface too soon. Then we can't confirm who to ban without the details in game.

**Comment by cshingle** [comment]
Oh, you returned to the lobby and the logs are gone so you can't see who did what? 
I have had that happen.

**Comment by CanXue233** [comment]
Yeah, and I just find a few of steamIDs in the server logs and that's not I want.

**Comment by Regalis11** [comment]
I'm not entirely sure I understand the problem. It's possible to access the server logs in the lobby too, and to ban players by clicking on their name either in the server log or the chat. Is the issue that the player left such a long time ago that their name is no longer visible in either?

**Comment by GenericGoose** [comment]
after a player disconnects (and some time passes?) their name is no longer clickable 
very annoying

**Comment by Rokvach** [comment]
This issue has already been fixed, closing.
