### ISSUE TITLE
Recycling an SMG magazine spawns one extra ammunition

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8356]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Recycling an SMG magazine spawns one extra ammunition and drops it on the ground. The round can't be used, but it can be picked up.

**Version**
0.16.6.1. release (or any after adding the recipe for recycling the magazines)

**Additional information**
Fabricating a new SMG magazine doesn't do the same.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/60b01e6fd5dc98c13770671caa20575055431183

**Comment by Rokvach** [comment]
Tested, every other time you recycle a SMG magazine (even a full one) it will spawn a extra SMG magazine which drops in front of the fabricator.

**Comment by Regalis11** [comment]
Not a bug, happened as a result of the "Munitions Expertise" talent

**Comment by Rokvach** [comment]
Working correctly, closing.
