### ISSUE TITLE
SMG sometimes doesn't have smg magazine when spawned in

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8357]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
ocassionally (1/5?) of the time, autofill doesn't quite fill the smg

(no pre-placed items, entirely autofill with secarmcab)

![image](https://user-images.githubusercontent.com/5103517/155426693-a92578ce-618e-4b70-b260-d577810f3eb0.png)

affects multiple cabinets at once - i have cloned the cabinet several times and ALL their SMGs this round spawned w/ empty ammo. Most of the time they do have loaded ammo though.

**Steps To Reproduce**
add secarmcab tag to medical cabinet (6 slots)
clone the cabinet several times
spawn into test mode several times

**Version**
0.15

0.16

**Additional information**
Also occurs outside of editor - first noticed in PVP mode (complaints about people hoarding ammo were quickly made)

#2264 last issue about smg and autofill, seems different.

![image](https://user-images.githubusercontent.com/5103517/155426815-be195447-c133-424f-81e3-ac76ab4ba30c.png)
![image](https://user-images.githubusercontent.com/5103517/155427066-dd8cc77c-6b6c-4f5e-8980-9c4032c18b53.png)

**Comment by itchyOwl** [comment]
Not sure if it's related, but it seems that all weapons that you buy also come without ammunition. Has it always been like that? I doubt it's intentional.

**Comment by Tsunder** [comment]
IMO that is unrelated and more of a design issue (purchased/spawned (console/lobby option) items don't spawn autofilled. one would expect prices to be much higher if they did... (batteries and ammo sold separately))

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/10ccbef030f6079b69c990d5a9d7a896d1a070d0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
