### ISSUE TITLE
"Curiosity" talent possible bug

### ISSUE THREAD

**Issue by Sevenecho** [Regalis11/Barotrauma#8358]
- [x] I have searched the issue tracker to check if the issue has already been reported.

It seems "curiosity" talent is bugged, because its description tells medic and a random crewmate should get 150exp each for every artefact deconstructed, while in practice (in my session) medic recieved 300exp all alone. Our crew checked their exp numbers beforehand - no one got anything at all, medic raised his level twice with ~20 artefacts disassembled.

**Steps To Reproduce**
Have a medic with the "curiosity" talent, collect an artefact, let this medic deconstructing an artefact, observe the "300exp" notification above his head.

**Version**
0.15.23.0, release Windows, branch release, revision 0a990787e8

**Additional information**
I've seen no topics about this talent being bugged, so probably the unstable version could inherit it too. Can anyone check it? My friends are not very fond of testing things in beta, and that's not something you can do with bots.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cdf648b3e17eeb861a79d8d21e9ea1530af59986

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
