### ISSUE TITLE
"Toggle Cool Down" for Buttons.

### ISSUE THREAD

**Issue by SeaverBeaver** [Regalis11/Barotrauma#8359]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
With many systems, most notably airlock doors, multiple people trying to enter/exit the sub at once means the button triggering the airlock may be pressed many times in the span of a second, causing havoc on anything more complex than the most rudimentary airlock.

**Steps To Reproduce**
Have you and another player try to enter/exit the sub at the same time, watch the airlocks break / hilarity ensue. This goes for _any_ system that operates on a toggle_state basis, appearing most frequently with airlocks. 

**Version**
V 0.15.23.0 (Release Version)

**Additional information**
It's more of a QOL issue than anything, but adding a toggle cool down field to buttons, in much the same way as it is for doors/hatches would make life words easier for sub builders. Spam-proofing would be made much easier, and in some cases, possible where it wasn't before.

**Comment by Regalis11** [comment]
I think this'd be a great addition, thank you for the idea! I'll close the ticket though since this is more of a feature request than issue report.
