### ISSUE TITLE
Unstable - When crouching your sight mislined

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#8360]
**Description**
When crouching you shoot under crosshair

**Version**
0.16.6.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b75dbc517ad5eb7e94aceefa366cd51abc0bbc34

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
