### ISSUE TITLE
sprite issue w/ new letter R

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8361]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/5103517/155594423-ce8d5ba4-589e-4aba-aa44-9a9f8463a0df.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.16.6

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0ad4fe2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
