### ISSUE TITLE
Turret lights point in the incorrect direction in the editor until their sweep is modified

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8362]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When loading a sub, the turret lights appear to be pointed in the wrong direction, until at least one of the angles of the turret's sweep are modified.

**Steps To Reproduce**
Load a sub with a turret in the editor (e.g. the humpback) and without changing any angles on the gun, turn on lighting, at look at where the light goes.  On the humpback the railgun's light points into the body of the sub while the gun itself is pointed away.

**Version**
v0.16.6.1 Linux

**Additional information**
Some turrets are worse than others.

**Comment by Tsunder** [comment]
possibly related to #7778

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/87e0fbde5f6c41779bb8a447c064b0a92bdd9d98

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
