### ISSUE TITLE
Reactor's automatic control having trouble generating more power than it can with one regular fuel rod

### ISSUE THREAD

**Issue by TetrisDuTrou** [Regalis11/Barotrauma#8363]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The reactor tries to output more power than it can, the automatic control set the output to the maximum but the fission rate is limited by having only one regular fuel rod, so the temperature goes low and the output goes much lower than it should.

**Steps To Reproduce**
- have a reactor with one uranium fuel rod inside it
- have the load go over the reactor's maximum output
- use the automatic control

**Version**
v0.16.6.1
windows

**Additional information**
the problem happens in a custom sub
the reactor's maximum output is 6000 KW

automatic control enabled:
![unknown](https://user-images.githubusercontent.com/72306596/155608287-483ae093-3546-44a2-9d3b-02f00bfb3c46.png)

automatic control disabled:
![unknown](https://user-images.githubusercontent.com/72306596/155610040-5206b169-8e26-4031-89cb-6e8eccfa7d39.png)

**Comment by Abkim27** [comment]
It's a feature, see the fisson rate not all space unlocked? When you have 2 uranium rod, you don't have this problem, and all works fine

**Comment by TetrisDuTrou** [comment]
I know, but I don't want the automatic control to become obsolete in this situation, because I don't really want to have two fuel rods in the reactor all the time

**Comment by Abkim27** [comment]
Two fuel rods will work fine with regular auto-control, just need to set it right, so it won't melt

**Comment by Abkim27** [comment]
That's a price for good work. Also you could just upgrade reactor on station

**Comment by TetrisDuTrou** [comment]
I don't really want the reactor to be able to produce that amount of energy, I would just increase that in the editor. Also a bot is managing the reactor, since I play in single player

**Comment by Kaillera** [comment]
Avoid straining the reactor. You can also pump more power to get responses back with battery and then dial the power back down.

**Comment by BlackMoons** [comment]
The problem here is the automatic control sets the turbine output too high, causing temp to crash.

Even at the same fission rate as 'automatic' caps to, you can get 20~30% more power by lowering turbine output so temp rises to the first > <

**Comment by Regalis11** [comment]
I'd consider this a feature too. Automatic control is not supposed to be perfect: even though a human player would be able to handle this "abnormal" (load higher than the reactor's maximum output, not enough fuel to increase the fission rate) situation better by reducing the turbine output just enough to prevent the reactor from cooling down too much, I think it's completely fine that the automatic control (or bots) aren't smart enough to do that.

I would also recommend increasing the reactor's output a bit if you want to avoid this, or trying to avoid drawing this much power from it.
