### ISSUE TITLE
Concatenation seperator field isn't editable mid-round

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8364]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seperator field of concatenation component isn't exposed/editable mid-round

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.16.6

**Additional information**

**Comment by Regalis11** [comment]
Changed in https://github.com/Regalis11/Barotrauma-development/commit/b9095b843b084d755f4087e816cf5e86c7d98c4c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
