### ISSUE TITLE
Submarines added to the hidden list don't stay hidden on next lobby creation

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#8376]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Submarines added to the hidden list aren't kept there on text lobby creation, but they are updated in the serversettings.xml.

**Steps To Reproduce**
Add submarines to the hidden list
Exit lobby
Create server

**Version**
0.16.7.0/0.17.0.0

**Comment by JoneKone** [comment]
Yes this is an issue.. can confirm.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab70595f61ad100a2c025e483c859d4a8eb22025

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
