### ISSUE TITLE
Contact with a nearby wreck by a charybdis knocks players

### ISSUE THREAD

**Issue by MudraptorSeks** [Regalis11/Barotrauma#8377]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I dropped a sonar beacon on a wreck, so the charybdis was attacking the wreck instead of the sub. The sub was no longer being damaged or impacted by the charybdis, but I was still flying around any time it attacked the wreck

**Steps To Reproduce**
I guess just uhhh put your sub near a wreck and put a sonar beacon in it

**Version**
The new one uhhh 

**Additional information**
This was in multiplayer 

https://youtu.be/hlX2eR6i6jY?t=8559 timestamped at 2:22:38 from where you can see the bug happening

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this: impacts with the wreck didn't seem to cause any impact effects. And looking at the code, that's expected: they should only trigger if the monster impacts the submarine you're currently inside.

I wonder if the charybdis actually hit your sub while chasing the beacon? It's impossible to tell from the video, but the beacon was close enough to the sub that it seems entirely possible that e.g. its tail hit the sub.

**Comment by MudraptorSeks** [comment]
I suppose it's possible, but I did not see it get any closer to the sub than when I saw it on the camera
I also didn't hear any impact noise, which, if I recall, is triggered by the tail as well

I will do further testing and comment with a video
