### ISSUE TITLE
If a player joins the server while the round is running, an error is thrown and the player sees only a blank lobby screen

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#8381]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a player joins the server while the round is running, the following error is thrown:
```
Failed to write a network message for the client "zhurengong"! {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameServer.ClientWriteLobby(Client c) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 1849
   at Barotrauma.Networking.GameServer.ClientWrite(Client c) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 0
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 615
```
while further investigating, it looks like it's caused when respawnManager is `null`, so it only happens if a server has respawns disabled.

**Steps To Reproduce**
1. Host a server with at least **one** player and respawns disabled
2. Start the round
3. Join the server

**Version**
Windows 10, latest stable release.

**Additional information**
Thanks to @Leonidas-ai for helping to reproduce this bug:
![image](https://user-images.githubusercontent.com/36804725/155820032-3dcc8096-b4d4-423c-9edf-c8b0e3bc9a31.png)
![image](https://user-images.githubusercontent.com/36804725/155820154-c49741bd-d806-4431-b824-3526276b9dff.png)

**Comment by Tsunder** [comment]
potential semi-workaround: set respawn to 100% players?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/10516900764fdce66f2af4560527a1881cabb480

**Comment by Ek-Videogames** [comment]
> "I call it **the hell dimension**"

Feel free to close duplicate issue #4137 when the fix is confirmed.

**Comment by evilfactory** [comment]
> > "I call it **the hell dimension**"
> 
> Feel free to close duplicate issue #4137 when the fix is confirmed.

I feel like your issue is different from this, yours happens when a client disconnects, but the server still thinks he is connected, so when he rejoins, he comes to this bugged state, where the lobby screen is blank

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by evilfactory** [comment]
While testing on unstable v0.17.8.0, i noticed that if someone joins an on-going round with respawns disabled, the server console will spam the exact same error.

![image](https://user-images.githubusercontent.com/36804725/162630553-0b19bf7f-93da-4ce7-8952-53ef45d8f2ee.png)

**Comment by Rokvach** [comment]
Reopening

**Comment by Regalis11** [comment]
Hopefully fixed for good now: https://github.com/Regalis11/Barotrauma-development/commit/102c48262675052294c339c7efbfd462d6b2adfd

**Comment by Rokvach** [comment]
Not fully sure if related but I had respawning and even respawn shuttle disabled and when a player tried to join the already ongoing campaign round they got this error, later on I enabled both of the options and players were able to join without any issues. 


![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5be74ba7-9904-4ba1-856b-f750628e32a1)

**Comment by Rokvach** [comment]
No new sightings of issues

**Comment by Rokvach** [comment]
No further issues has  been spotted, I'll just close this ticket. Can be re-opened if it still causes some issues. Closing.
