### ISSUE TITLE
No output JB Load & Power value out

### ISSUE THREAD

**Issue by Torca2001** [Regalis11/Barotrauma#8386]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Junction boxes power_value_out and load_value_out only output 0 regardless of the load and power on the grid shown by clicking on the junction box.

**Steps To Reproduce**
Load up the humpback, attach a text display each for the power_value_out and load_value_out pin of a junction box next to the nav terminal.
Observe the 0's

**Version**
V0.17.0.0 Unstable, Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
