### ISSUE TITLE
Multi Reactor incorrect load

### ISSUE THREAD

**Issue by Torca2001** [Regalis11/Barotrauma#8387]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reactor will display the wrong load during shutdown spiking down to zero. In multi reactor configurations each reactor would report significantly lower load than the true load and the sum of all the reactor loads was closer to half the true load.

**Steps To Reproduce**
Loading in the humpback and attaching a second reactor to the main grid and turn both reactors on and put them on auto.

**Version**
V0.17.0.0 Unstable, Windows

**Additional information**
It was previously working in my PR #8184

**Comment by Regalis11** [comment]
Fixed in Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f65b9e6fde47c41cc135c487fde44db370c2712

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
