### ISSUE TITLE
Reactor shutdown incorrect load

### ISSUE THREAD

**Issue by Torca2001** [Regalis11/Barotrauma#8388]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a reactor is outputting power to a grid and is shut down, the load reading of the reactor jumps down to 0 and slowly comes back to the true load.

**Steps To Reproduce**
Power up a reactor and wait for it to stabilise to the grid's load.
Shut down the reactor and observe the sudden load drop.

**Version**
V0.17.0.0 Unstable, Windows

**Additional information**
It is most likely related to the multi reactor load behaviour being incorrect as during shutdown the calculations accidently used the multi reactor calculations for the load.
It was previously working in my PR #8184

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f65b9e6fde47c41cc135c487fde44db370c2712

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
