### ISSUE TITLE
Workshop Publishing Page freezes when clicking on previously released object, preview image doesn't load

### ISSUE THREAD

**Issue by NystokeAkers** [Regalis11/Barotrauma#8389]
When trying to publish an update for my custom submarine in the games workshop page, trying to click on my previously published object results in the game freezing and not responding anymore. The preview image of the Mod doesn't load either.

• Go to Steam workshop, publishing tab
• Click on previously published object
• no preview image, game freezes and has to be force quit.

Version im running is v0.16.7.0 ( macOS, revision aa4c852c2c )
Running on an Apple Silicon Mac through Rosetta 2 
( if that is something that can cause issues, but it worked fine previously )

<img width="1512" alt="Bildschirmfoto 2022-02-26 um 11 23 23" src="https://user-images.githubusercontent.com/93075907/155839973-3c31dece-9e77-48c3-8ced-928a1b5a3a0e.png">
( sorry I set my game to German )

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly. Closing.
