### ISSUE TITLE
Crash in CharacterHealth.ReduceAfflictionOnLimb

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#8390]
[crashreport (9).log](https://github.com/Regalis11/Barotrauma/files/8146412/crashreport.9.log)

**Comment by Regalis11** [comment]
I wasn't able to reproduce this, but added a null check in https://github.com/Regalis11/Barotrauma-development/commit/1c6a972bd1e2d930a8279ac5fbc7ca424af1c3d9 that should prevent this from crashing the game

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
