### ISSUE TITLE
Inconsequential, purely aesthetic problems with the new Orca 2 after the update

### ISSUE THREAD

**Issue by AFK-TankyMOFO** [Regalis11/Barotrauma#8396]
The wire connected to the small pump in upper airlock is slightly crooked, and the floors around the new duct block in upper fore side have no wall caps on them like all the other floors.

Sorry if I'm wasting your time, but every time I see them I feel physically uncomfortable.

**Comment by danielasteljoki** [comment]
Fixed in 15d2bd8.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
