### ISSUE TITLE
Winterhalter missing oxygen vent in the room next to its research facility. 

### ISSUE THREAD

**Issue by Cherman0** [Regalis11/Barotrauma#8399]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The room in question:
![20220226174909_1](https://user-images.githubusercontent.com/99766513/155861486-250fb0f0-ef3e-4029-9165-a5819092570a.jpg)
Exactly as stated in title. There is no vent in the cabinet room next to the medbay, meaning that players can suffocate and die if afk in this room.

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Should be present in any version with the Winterhalter. Version that I used is Barotrauma v0.16.7.0 (ReleaseWindows, branch releaase, revision aa4c852c2c).

**Additional information**
Found this one out the hard way.

**Comment by ExoMoon** [comment]
This is a mod, please leave comments on the steam pages site.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/445211e7e4565a8bad37395bbd49c3cf351b1f5d

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
