### ISSUE TITLE
Attached Object position issue + Server->Client Detaching/attaching not synced correctly.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#84]
As a note I've tested this under 0.7.0.1 (using vanilla files)

In previous versions of Barotrauma objects used to attach to the aimed position of the held position - Now this is always the players position (Their center).

If another client or the host when your playing as a client attaches an object where he aims - this object will attach at the handle position for other clients but still at the center for yourself, resulting in the button being unable to be selected for using, rewiring or detaching. the host sees this at the center position (The players position) as noted above.

Joining a round that has already started which has had a few buttons moved around can result in no visible button where it should have been attached.

Additionally if you are the server host - you can see players detaching objects with a wrench such as buttons, but clients do not see this from the host or other clients.

Hosts view:
![image](http://puu.sh/yAhAp/641b3394cb.jpg)

Client 1's view (Started with round)
![image](http://puu.sh/yAhBH/51c162cc3c.jpg)

Client 2's view (Joined midgame)
![image](http://puu.sh/yAhCy/9da2f09775.jpg)

**Comment by Crystalwarrior** [comment]
Huh, this is really weird, I don't think I ever had this happen to me.
However, this seems to be a pretty big issue nonetheless.

**Comment by Regalis11** [comment]
74ef5c6e fixes this I believe.
