### ISSUE TITLE
Make radio headsets craftable

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#840]
Most custom submarines either don't include any spare radio headsets at all or have a small amount of them in rooms that are not accessible by the low rank crew members.
  Because of that, getting your headset stolen makes you almost completely deaf and mute for the rest of the round, unless some other crew member dies and you get to take their headset.
  It's really easy for the thief to take the radio without many consequences(since it's hard to alert the crew about the thief when you don't have the radio).
  Being unable to communicate with the crew is really frustrating, especially during long rounds.

  Making headsets craftable would help with that problem.

**Comment by KingChairis1** [comment]
Maybe a WiFi component + steel could be used as the recipe

**Comment by BillCombs** [comment]
Perhaps instead of steel it should be polycarbonate, since plastic is lighter and more flexible. That would be
More comfortable to wear on your head.
