### ISSUE TITLE
[Modding] Broken removecharacter status effect after the update

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#8401]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
```xml
    <attack>
      <Conditional isdead="false" />
      <Conditional stun="gt 0" />
      <Conditional speciesname="eq human" />
      <StatusEffect type="OnFailure" target="This">
        <RemoveCharacter />
      </StatusEffect>
    </attack>
```
This code is meant to make an attacking character disappear after attacking.

The status effect included in this attack used to work prior to the "Rising Tide" update, however now, the "removecharacter" portion of it will just never trigger. The temporary solution to this is to give the attacking character an affliction which then deletes it, however it would have been better if "removecharacter" just worked in that status effect without having to use an affliction, especially considering that it did indeed work prior to the update.

Changing the status effect type to "OnUse" did not work prior to the update and does not work now either.
Changing the target to "Character" will make the attacked character disappear properly.

**Version**
v.0.16.7.0

**Comment by Regalis11** [comment]
"This" now refers to the limb the attack is defined in (previously it wasn't possible to make the StatusEffects target it). It's still possible to target the character using "UseTarget" instead.

I think I'll also add an option to target the character using "Parent" as the target type, and to remove the character even when you're targeting a limb instead of a character.

**Comment by Regalis11** [comment]
Implemented the above in https://github.com/Regalis11/Barotrauma-development/commit/0b2fcbcd20cc869c5754f78223e102958bdd6769

> Made it possible for attack StatusEffects to target the character doing the attack instead of the limb, using RemoveCharacter on a limb removes the character that limb belongs to

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
