### ISSUE TITLE
[Unstable] Core Content Packages can't include dll, exe or json files in the mod folder

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#8402]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Core Content Packages can't include dll, exe or json files in the mod folder, this makes the DedicatedServer content type pretty much useless for modding, because you can't include your own server build of the game in the mods folder.

**Steps To Reproduce**
1. Try to download any core content package mod that includes dll, exe or any blocked file extensions.
2. Watch the game complain in the debug console that these files can't be copied because they are blocked.

**Version**
Windows 10, Unstable 0.17.0.0

**Additional information**
![image](https://user-images.githubusercontent.com/36804725/155894199-7756931c-6292-42bd-8a46-3a60581f8582.png)

**Comment by DrinkFromTheCup** [comment]
Query from friendly modder: why would you want to distribute .exe or .dll through game mods?
There are more convenient means for deployment for headless (dedicated) servers.
As of hosting from in-game, allowing executables/DLLs is likely pointless: exe won't get replaced (because of being already launched) and DLLs won't get auto-loaded (because of inappropriate placement for that).

**Comment by evilfactory** [comment]
> Query from friendly modder: why would you want to distribute .exe or .dll through game mods? There are more convenient means for deployment for headless (dedicated) servers. As of hosting from in-game, allowing executables/DLLs is likely pointless: exe won't get replaced (because of being already launched) and DLLs won't get auto-loaded (because of inappropriate placement for that). Upd. Oh. I see... A friendly advice: despite all my hatred and bile towards [tModLoader](https://store.steampowered.com/app/1281930/tModLoader/) (similar, for Terraria), it's preferrable to resort to their method of .exe/.dll redistribution. I believe, the community can gather needed funds for publishing it. Because you're doing a good thing which would be beneficial for everyone. Allowing random murderhobos to haul executables around is extremely dangerous - expecially with community such... creative in their destructive intents...

With this new change, it will break the workshop version of my mod [LuaForBarotrauma](https://steamcommunity.com/sharedfiles/filedetails/?id=2559634234), that was meant for technical inept people or people that were too lazy to do the manual install process. 

And anyway, if security is the problem, why not just include a text popup saying **"This core package changes the ServerExecutable, make sure you trust the mod's author"**, instead of completely removing it/making it useless

**Comment by evilfactory** [comment]
Seems to be working correctly, though i found that the selection of the server executable doesn't save when restarting the game, it would be nice if it saved in the config.

**Comment by Rokvach** [comment]
Closing.

**Comment by evilfactory** [comment]
There still seems to be an issue with uploading mods that contain blocked file extensions, i just tried to publish a mod on unstable and this happened:
![image](https://user-images.githubusercontent.com/36804725/162596897-3079ea3f-0456-40d6-addf-a72e73299c09.png)
![image](https://user-images.githubusercontent.com/36804725/162596901-00ef5a05-c701-4938-979f-5f190a044401.png)

**Comment by evilfactory** [comment]
Seems to be working with `.dll`, `.exe` and `.json`, though, `.pdb`, `.so` and `.dylib` files seem to be in the block list for some reason, i know they aren't needed for the program to function, but it would be nice if i could include them in the mod files.

![image](https://user-images.githubusercontent.com/36804725/162812742-d989619e-1cca-46c0-859e-5e9d21f6c37e.png)

**Comment by evilfactory** [comment]
Seems to be working correctly, was able to publish the publish without getting errors.

**Comment by Rokvach** [comment]
Closing.
