### ISSUE TITLE
Can sell terminals and text displays

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8404]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
they appear in the submarine sell tab
![image](https://user-images.githubusercontent.com/55637865/155898241-90bfaefa-8cf5-4485-8fe7-df41c47418ef.png)

**Version**
v0.17.0.0

apparently you can also just take them off the walls when you first try to interact with them, i'm using a humpback if that matters

**Comment by DrinkFromTheCup** [comment]
Correction: can sell MOUNTED (i. e. attached, wired and fully operating) Terminals & Displays.
Unstable, today's latest.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ab371b89afa4d50c2e7644e9dc9f0b9197dc2c5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
