### ISSUE TITLE
error when near moloch_m

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8406]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/155899022-3e5d48a0-5a2d-45ff-a1ce-50fb2933d41d.png)

**Steps To Reproduce**
approach a moloch_m

**Version**
v0.17.0.0

**Comment by LePiromano** [comment]
all of its animations seem to bug out so it doesn't do anything

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d9743213047e4c91818aa99aa024842142340c5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
