### ISSUE TITLE
rep gain/loss color is gone

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8407]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/155899244-942e08f0-6e49-4986-8ab9-d2bfab38d9e3.png)
colors of gaining or losing reputation are gone, now it's all just white, not sure if this is intended but it does take a bit of soul out of the loading screens

**Version**
v0.17.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/94189d1ea01d11b3458f01bd9925a3f2366b5ddc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
