### ISSUE TITLE
order menu is randomized/inconsistent 

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8408]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
this is probably intentional, but it makes numeric orders useless, previously you could manage your crew's orders super quick by using numbers, but now the orders change depending on some factors so it's impossible to do it

**Version**
v0.17.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d883f8ab2cefa89c10c58860113953750687e835

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
