### ISSUE TITLE
drugs aint workin

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8409]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i gave myself 100 medical skill in this video
https://user-images.githubusercontent.com/55637865/155900566-68a6ee74-ce8a-4401-8fad-5cb4f654e7dc.mp4

**Version**
v0.17.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1ca767623a75c42d3a11f1c7c873109432725496

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
