### ISSUE TITLE
More obvious sound cues that a stun/incendiary grenade was thrown

### ISSUE THREAD

**Issue by DataCrusade** [Regalis11/Barotrauma#841]
It's small, makes no noise until it explodes, and is fairly dangerous. Even something like noise when it bounces on the ground would make it a lot more balanced.

**Comment by ZealanL** [comment]
I would love a metal bouncing sound for grenades and other items. Would help make it feel more dynamic, and give realistic environmental clues. If you heard a light metal sound followed by bounces in your direction, you could tell something was thrown at you. This would be really nice, as well as maybe body impact sounds similar to games like GMod.
