### ISSUE TITLE
things keep randomly switching places

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8411]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the order of factions on loading screens, the submarine upgrades on the outpost trader, orders, talents, the color of hair and beards, and a lot of other random things keep just switching places for no reason

they seem to change every time you re-open a save

**Version**
v0.17.0

**Comment by Regalis11** [comment]
> the color of hair and beards

I'm afraid I couldn't reproduce this.

**Comment by LePiromano** [comment]
> > the color of hair and beards
> 
> I'm afraid I couldn't reproduce this.

https://user-images.githubusercontent.com/55637865/156186523-efc84ecb-35ef-4d2c-88b6-5f4580d08596.mp4

**Comment by Regalis11** [comment]
Ahh, thank you! I thought you meant the order of the face/hair colors in the menus.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/157bb486823fba9ef0c18128008ab83a9ee6cd71

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
