### ISSUE TITLE
game fps downs

### ISSUE THREAD

**Issue by zombiedragon8090** [Regalis11/Barotrauma#8412]
not sure what's happening but when ever my sub gets attacked by anything the game starts hitting like 3 fps the sub I'm using is the Winterhalter

**Comment by LePiromano** [comment]
had the same issue, it's usually with mudraptors, and there's still the bug where a spineling hitting a door has a chance of just killing your game.

**Comment by zombiedragon8090** [comment]
thank you for telling me have you had any fps drop with the crawler broodmother

**Comment by Regalis11** [comment]
I unfortunately haven't been able to find a way to reproduce this (been testing with simulated bad networking conditions and various subs and monsters).

Does it happen in single player, multiplayer or both? Something that could also give us more clues is if you enabled the in-game performance statistics and sent us a screenshot of what you see when the FPS drops. You can enable it by opening the debug console by pressing F3, and entering the command "showperf" in the console.

**Comment by LePiromano** [comment]
the fps drops i had with spinelings happened in singleplayer

**Comment by zombiedragon8090** [comment]
same on my end with mudraptors haven't seen any spinelings yet

**Comment by LePiromano** [comment]
watcher's gazer rage effect particle seems to also lag the game a lot

**Comment by acghhinzGIT** [comment]
I had the same issue in single player mode. FPS drop and mouse/keyboard lag when fighting a pirate sub, or swarms of tough smaller monsters(hammerhead). here are my screenshots.  
<img width="960" alt="遭遇海盗时卡顿2" src="https://user-images.githubusercontent.com/101189370/157256531-4a0edd36-2abb-4998-a4fb-3c6ce380d6f8.png">
<img width="960" alt="遭遇海盗时卡顿1" src="https://user-images.githubusercontent.com/101189370/157256544-fcaec534-6bc4-4a7b-8f72-893d6e312bcf.png">

**Comment by acghhinzGIT** [comment]
Sounds like the same issue. Surely the attack event will give more pressure to the processor and cause fps down, but the mouse/keyboard lag is really awful. Maybe the attack of mudraptor(the newly added one) is the worst. After killing last of them, the game immediately back to normal.

In this pirate mission round, the attack of 4 mudraptors nearly lock my mouse, and a single mudraptor in the pirate sub can also lag the input.
![image](https://user-images.githubusercontent.com/101189370/158106323-0c8368e8-d88c-46c9-a0af-a5f89cde7bf2.png)

**Comment by Regalis11** [comment]
Closing in favor of this newer ticket with more info https://github.com/Regalis11/Barotrauma/issues/8961
