### ISSUE TITLE
Reactor gauges background offset

### ISSUE THREAD

**Issue by Foxtrot39** [Regalis11/Barotrauma#8413]
**Description**
Reactor gauges background are offset and visibly stick out the gauges

**Steps To Reproduce**
Select any reactor

**Version**
Windows game version v 0.16.7.0 release branch revision aa4c852c2c

![Sans titre](https://user-images.githubusercontent.com/87786019/155988368-f9596856-e53f-4a99-ba59-f7d1a9277b67.png)

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f90fc7762a9d6daf02455ca24b35f739f87a6402

Note for testing: this seems to only happen in the sub editor.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
