### ISSUE TITLE
Doors affecting light sources directly from afar

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8414]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Doors can sometimes cast a shadow directly on the light source when closed
(idk how to describe it properly)

**Steps To Reproduce**
Download [Tadpole Trader.zip](https://github.com/Regalis11/Barotrauma/files/8153831/Tadpole.Trader.zip)
Check the light in the fabrication room
Open and close the left door

Closed
![image](https://user-images.githubusercontent.com/73229309/155995834-276e4c63-a183-4ab6-ac1d-33a463e4c756.png)
Open
![image](https://user-images.githubusercontent.com/73229309/155995850-fc4a5d45-a4a1-46fd-a54c-dedcf98bbdd8.png)

![image](https://user-images.githubusercontent.com/73229309/155996018-19117a27-7acd-49cb-8c82-62df9b39e068.png)

**Comment by Regalis11** [comment]
Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/3366 (even though in this case the occluder is more reasonably sized)
