### ISSUE TITLE
Gap placed exactly at the edge of a hull doesn't connect to the hull next to it

### ISSUE THREAD

**Issue by Woestel** [Regalis11/Barotrauma#8417]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Title. see the picture.
https://gyazo.com/e870dc47004ee26b9b62fc8465c83cd2

**Steps To Reproduce**
1. Open sub editor.
2. Place duct blocks. and two hulls.
3. It works when the duct block is placed below the hull border, but not when it is placed above it.

**Version**
1.16.7.0 Hotfix (Windows)

**Additional information**
https://github.com/Regalis11/Barotrauma/issues/7957

Things got worse with the 0.16.6.1 update.
The gap margin that used to be around the duct block (or door or hatch) is now lost, and the duct block is no longer allowed to snap to the hull.

We didn't want to lose the gap, we wanted the gap to be keep......
Probably not just me, but many submarine designers.

**Comment by Regalis11** [comment]
Thank you for the report! Gaps should be placed _between_ hulls: in this case they're basically just inside one hull. I'd recommend nudging them up/down a bit, or preferably placing them exactly between the hulls.

Regardless, I decided to add a 1 extra pixel of tolerance to the hull search logic to make gaps placed like this work in the future (https://github.com/Regalis11/Barotrauma-development/commit/7c04b5ec4903ee4644a847642cf8a75be4eca6dd).

**Comment by Woestel** [comment]
Thanks, A 1px margin should be enough to solve this problem.
Hopefully, that 1px will remain after resizing.

I was given the recommendation to stack the gap between the hull, but that is difficult to do for the duct blocks.
I don't think the current specs for duct blocks and water detectors are designed to stack hull against the wall.

The water detector only outputs a signal when water touches the bottom edge, so if you stack the hull on top of a duct block (or horizontal wall), the water detector must also be embedded in the wall to drain the water.

If you embed the water detector in the wall, you will have to destroy the wall to change the wiring, which will ruin the traitor mode.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
