### ISSUE TITLE
Gas vents' trigger area is too large

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8419]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
gas vents affect you when you're not on them
https://user-images.githubusercontent.com/55637865/156061901-0bc15948-ad4a-48bb-8024-da0ffdde24d2.mp4

**Version**
v0.17.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/786fba004a17e82289de4da4c3d09ba332889e95

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
