### ISSUE TITLE
Make console forget previously used commands if they have been used again

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#842]
Not sure if the title explains it properly.

For example, you want to spawn a crawler and 10 mantises; you use the commands in that order:

spawn crawler cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor
spawn mantis cursor

the console remembers every command even if they are the same, which means, if you wanted to go back to the "spawn crawler cursor" command, in case of the example you would have to press Up arrow key 11 times before you could get to it.
Making the console forget duplicate commands would make it more convenient.

**Comment by CommanderMark** [comment]
Rather than removing duplicate inputs you could make it so that cycling skips any inputs that are equal to the currently selected one.
