### ISSUE TITLE
projectiles bounce off all hulls

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8420]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Haven't tried with every type of ammo, but coilgun and railgun shots seem to bounce off normal and wrecked exterior hulls dealing 0 damage to it.

**Version**
v0.17.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7946c41aa7c2d91b15810e864ddcd9ccbfef3fd1

**Comment by mrjpjr** [comment]
I noticed this today as well.
Regular, Physicorium (with payloads) and Nuclear railgun shells bounced off the Pirate sub's (outer) shell, doing no damage

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
