### ISSUE TITLE
deadeye burst leaves 2 bullets in the mag

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8423]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the deadeye carbine shoots bursts of 3 bullets, but the magazine holds 20, so if you'll end up with 2 bullets in the mag, if the bursts were of 4 bullets it would look better (this is super low prio but i'm a perfectionist)

**Version**
v0.17.0

**Comment by cshingle** [comment]
Honestly I think it makes more sense to increase the mag to 21 rounds so the mag size is a multiple of 3.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/ed0c2c4fa3e724aaaaec14c5424963ac61e9a579 by increasing the magazine's capacity to 21

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
