### ISSUE TITLE
clicking the submarine's weapons in the sub upgrade menu crashes the game

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8426]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
in the display of the submarine that shows up when you're upgrading your guns, if you click the weapons in the display the game crashes
[crashreport (62).log](https://github.com/Regalis11/Barotrauma/files/8157559/crashreport.62.log)

**Version**
v0.17.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b91ae20a90f36e0c934de763a637e44605a4abf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
