### ISSUE TITLE
Bots don't know to open a door if their pathfinding target is immedeately behind it.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8428]
### More weirdness with bots and their relation to doors:
It seems another scenario where bots will just walk into a door without opening it is if their target objective is sitting immediately on the other side of the door. _(like they don't seem to register the door as blocking line of sight to their target?)_

This happens particularly often on submarines if there is a room with repairable items or containers close to the doors of the room, or small side closets that are a short distance horizontally.
**Example: Junction box next to a door.**
![image](https://user-images.githubusercontent.com/55356135/156102741-3b2125eb-4816-4e19-b8c5-b24c717feed6.png)

Seems like the "Leniency" of pathfinding that allows bots to reach stuff further away from the room nodes could be mistakenly making a bot think it can reach their target prematurely - rather than pathing into the room and requiring it to open the door.

*(I think this can still happen with items that are near the other side of a wall too, such as on the remora. Not just doors.)*

**Comment by itchyOwl** [comment]
Would be helpful to have a wider picture where you can see the objectives and hence the current "state".

But it seems that the bot is following the "go to" objective, meaning it doesn't consider to have reached the target. I don't see the purple line there or path cost, which would indicate that it hasn't found a proper path (yet?).

**Comment by Regalis11** [comment]
Seems to be easy to repro by ordering the bot to repair something right at the other side of the door:
![image](https://user-images.githubusercontent.com/14351070/156371674-c8d9503c-6795-49fe-ac4f-0e5ff09bb0c8.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
