### ISSUE TITLE
Crash barotrauma 

### ISSUE THREAD

**Issue by trollpolado** [Regalis11/Barotrauma#843]
it have happened more than 3 times now

**Comment by trollpolado** [comment]
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/2462368/crashreport.log)

**Comment by Regalis11** [comment]
What build this is? Apparently it's some dev build, but the line numbers don't correspond to the current code in the dev branch.

**Comment by trollpolado** [comment]
It is a pre mounted version of the dev version i think its old you may alread have fixed. do you have any way that a guy like me can get the the most updated dev version?

**Comment by Regalis11** [comment]
If you got the build from https://archive.database.red/ it is indeed at little outdated. I'll close this for now, and reopen if the issue appears in an up-to-date build.

We don't share dev builds publicly, so I think your best bet is to either compile it yourself or wait until the build in https://archive.database.red/ is updated.
