### ISSUE TITLE
Issue with starting a new game

### ISSUE THREAD

**Issue by someguythatplaysbarotrauma** [Regalis11/Barotrauma#8434]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
so a few days ago (this was created march 1, 2022) I decided to start a new save in Barotrauma and once I picked a sub, there was no screen for customizing my crew, and I thought, "huh that's strange. It's probably nothing anyways" so I started the new save file and was greeted with a warm, welcoming message saying, "The ocean has claimed (submarine name) and its crew" and I thought it was just a weird one-time glitch, but apparently it was not. Today, I uninstalled and re-installed the game, but that didn't work. I do play the game with a lot of custom submarines and a bit of mods.

**Steps To Reproduce**
I do not know how how to reproduce this glitch, but my list of mods and custom submarines are:
[AP] Sakala
Airdsgainne 'Dropshipper'
Tadpole raider (pvp)
Tadpole Trader
Dugong Mk-II
Amethyst Geode Exotic Warship
SCP Pelagic Anomalies (at the time of writing this it is in stage 1, or as they call it, R&D)
EK : Armory
[VY] Hierophant - Diviner of Secrets
Combat mask
Rorqual
King Layne Mining Cruiser
Barracuda Escort Corvette
Mining Station A
Taringr
Wanted Alive
Convict Station
Sanctuary Transport
Abyssal Warsuit
T.I.T.A.N. power suit - New update, new me.
Improved xp rates
Innautishell
Dugong V2
Lootbelt
Aurora
Mannamusic
The Peregrine
Unlocked Captian Talents
Half Life Series Armor
Half-Life Combine Module Pack
Half-Life Arsenal

**Version**
This bug started happening after the rising tide update, and I am playing on windows.

**Comment by Regalis11** [comment]
This seems to be caused by the "SCP Pelagic Anomalies" mod. It overrides all the vanilla jobs and sets their initial counts to 0, meaning that there are no characters in your starting crew.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1fa7884d4764a6dc4423df04c6e476326494add3 by making the game select the 3 first jobs as the starting crew when using mods that don't configure the starting crew.

**Comment by someguythatplaysbarotrauma** [comment]
oh thanks for telling me, I really appreciate it
