### ISSUE TITLE
Xor Component not working

### ISSUE THREAD

**Issue by BobertGoneMad** [Regalis11/Barotrauma#8436]
I've recently tried using the Xor Component and I discovered it isn't working as expected. Obviously it states that only 1 signal may pass through at a given time, but even if both or neither are sending a signal through it constantly outputs a signal. The false output it set to 0 if unedited, I tried to make it 0 since I noticed it wasn't working but still no dice. Any thoughts?

**Comment by Tsunder** [comment]
works for me (xor output into terminal's signal_in)

to be clear, if both/neither are recieving non-0 signals, or if no signals are being recieved, the component outputs its false output

perhaps an issue with your display method?

**Comment by BobertGoneMad** [comment]
I'm using the xor comp like a minecraft comparator. 1 signal can go through but if another is introduced then it locks off the flow of power. nothing complex, but like I described if either inputs go through it's just stuck sending a constant output. The output length is set to 1, output to 1, false (0 by default).

**Comment by BobertGoneMad** [comment]
@Regalis11  The false is set to 0 by default, I have not edited that, yet it persists on outputting 1 after both/neither inputs are active.

**Comment by BobertGoneMad** [comment]
I believe the issue is with the component itself, I cannot edit the false output, pressing enter does not stop editing the false output #.

**Comment by BobertGoneMad** [comment]
well I tired again and I can enter in a false output #, but if it's undefined it results in the issue I was having. works as intended if I manually set false as 0

**Comment by Regalis11** [comment]
The only explanation I can think of is that there's some issue in the way you're checking what the xor component is outputting. How are you doing it, i.e. what's receiving the input from the component?

**Comment by BobertGoneMad** [comment]
I was using it as a bypass for my auto airlock and for the reactor "no output" alarm. The context doesn't matter, I tested it with lights and switches. As long as I manually set the false output to 0 I had no issues, if not then the Xor output was just on and no fuction affected weather or not it was gonna change output.

**Comment by BobertGoneMad** [comment]
I found a workaround using Signal check comp. for alarm and Exponentiation comp. for the airlock. So it was just an inconvenience. 
Leave a comment

**Comment by Regalis11** [comment]
I tried building a similar circuit now, and it actually seems the default false output of the xor component is empty, not 0. Could it be that you'd just accidentally left it empty when you were encountering this issue?

**Comment by BobertGoneMad** [comment]
I intentionally left it empty expecting it to default to 0. It says in the Xor false output description that "if empty, no signal is sent".

**Comment by Regalis11** [comment]
Ah, I think the misunderstanding here is about the meaning of "no signal". In the game's signal logic, there's a difference between "0" and "no signal". For example, a light turns of when it receives a signal of "0", but if it does not receive a signal, nothing happens.

**Comment by BobertGoneMad** [comment]
I will remember that onward.
