### ISSUE TITLE
[Dev version] Some requests and issues

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#844]
I played the dev version (taken from https://archive.database.red) for some time and overall i really love the changes you have made to the game, especially ones made to the tense moments when the sub hits something or gets hit by big creatures. The new camera moves and other visual effects really make these kinds of situations a lot more immersive and fun.

Here are some issues and requests related to this version. I am not sure if they should really be compiled in one issue, so, if it's more convenient for you to work with each of them separately, i will close this one and make separate issues.
Some of the issues are probably just still work in progress, but i decided to put them here anyway, just in case they are considered finished, or so they wouldn't get forgotten.
 
1:
The recently added walls(the ones that have curved versions of them) seem to be as weak as windows, one revolver shot is enough to destroy a whole piece of the wall. I think a single revolver shot at submarine's wall shouldn't be able to make the whole submarine suddenly get almost completely flooded.

2:
The fuction to grab a body by the torso seems to be gone for some reason(or perhaps just not added to the new hud yet). It was pretty useful for roleplay and carrying bodies. And it was also awesome to use people as hostages or meat shields in cases of a gunfight. I think it should be kept in the game(unless it's causing issues, though i personally have not seen any).

3:
I am personally not a big fan of items like crates or structures like ladders being transparent for bodies.
![transparency](https://user-images.githubusercontent.com/38168249/46727952-dfbd5000-ccab-11e8-883b-8a1bbf490621.jpg) 
Can't really explain why, but it kinda makes the game less immersive for me. I think there should be an option to toggle such transparency of items and structures, if that's not too hard to implement.

4:
The grip of players feels a bit too hard to get rid of. It can be justified for handcuffs, since you wouldn't want your captive to run away from you every time you check their inventory. But it should be a bit weaker when interacting with other player's health hud. Right now it feels like it could be abused. You could hold players just to mess with them, or you could hold them and easily stun them or inject poisons with almost no chances for the victim to avoid it. It may be kind of realistic to be able to grab live people, but it feels like it's too powerful right now.

5:
I love the tension and music layers mechanic, but i feel like the current Intensity Layer 4 soundtrack does not really fit to the game and situation. No offense to whoever chose or made it, but it honestly sounds like if the game was crashing. Other soundtracks are more like light vibrations or music, but this one is just not fun to listen to. I really tried to enjoy it but just couldn't.

6:
There is a bug with changing properties of items in the recent(relative to https://archive.database.red) dev version(probably has been already fixed)
Don't know how to describe it well enough.
Basically, when you are clicking on the text field to edit the text, the text cursor disappears, like if the text has not even been clicked at. So right now it's really hard to change properties. Only tested it in sub editor. Not sure if the same happens in the actual game.

7:
Handcuffs can be put on a player with one- or two-handed items at same time.
You still can use the items you are holding while you are handcuffed.
Other players are not  able to take the cuffs off you in that case. However they can give you items and make you equip them while you are cuffed. 
The bug does not happen all the time, sometimes you just put handcuffs on yourself and other players actually can take them off.
video examples:
https://streamable.com/kan0e
https://streamable.com/7fe0n

8:
There should be an option to hide the sonar markers on the monitor.
![sonar markeers](https://user-images.githubusercontent.com/38168249/46727340-87398300-ccaa-11e8-94f9-f6f0c56b8742.jpg)
They cover a lot of space, that could be problematic in cases when you need to get information about positions of enemies or your crewmates near the submarine, or just trying to swim through tight cave systems. There should be an option to hide them or just their names. Perhaps the squares that are showing positions of the sonar markers should be kept, since they don't take that much space on the
screen.

9:
(I am probably just nitpicking here. Though i still think this is something worth looking into once you begin polishing the game)
The sliders in the huds of machines are great, but to me feel a bit too sensitive, which makes it a bit hard to set certain values quickly and precisely. Perhaps each step should require just a little bit more mouse movement? Also there are some issues with the cursor movement. When controlling the slider and still seeing mouse cursor you might expect it to be the thing controlling the slider. But instead it looks more like it depends just on the mouse movement. (https://streamable.com/nquje) The cursor is able to go anywhere on the screen, which can be a bit confusing and not looking that great. Also, the option to change settings by clicking on the slider instead of holding it isn't a bad thing, but the slider moves to the cursor even when you are just releasing the mouse button after holding the slider. It should either not affect settings upon releasing the slider, or perhaps you could make the cursor stick to the slider or just disappear when the player is holding it.

10:
Make selecting autopilot and maintain position mode select current sub's location as the position to maintain.
The ability to control the sub using autopilot's maintain position is really useful, but for some reason now selecting this mode makes the submarine's autopilot move the sub to the last spot it had to maintain. Because of that, you have to also select a new maintaining position at your submarine's location to make it stop moving. It's not that problematic to get used to, but there is another problem with it. Often the last location that the submarine was supposed to maintain is really far away from the new submarine's location. Because of that, as soon as you switch to the autopilot, it will force the sub to accelerate towards the last spot at full power. That is not a big problem for slow subs, but it's enough for subs with powerful engines to pick up speeds high enough to make it hard to select the location before the submarine gets enough speed to inevitably hit something.

11:
Add an option to order currently selected character to wait or be dismissed. In the non-dev version you can order your selected character to stand still, so when you switch to another and then switch back to the first one, he is still standing at your desired location. That makes it easier to multitask by switching between multiple characters. In the dev version there is no such option, which means that to make your selected character stand still you have to switch to one of the other characters and order the former character to wait. And by the time you do that, your character can already walk a long way away from your desired waiting position.
(kinda related to the issue with orders)Also, when you order ai to follow somebody, they follow the person even when it becomes a corpse. That might be pretty deadly for the ai, since the game basically forces them to stand in dangerous spots(corpses don't appear in safe places). Perhaps they should be dismissed once the person they are following is dead.

12:
Has swimming speed been lowered?
It seems like swimming speed has been lowered for about 25-50%, no matter if you are using Underwater scooter or not. I assume it has been made for balance purposes. However there is a problem with it. Carrying artifacts to the submarine is just too slow now. If the artifact is in a tight cave, where even shuttles don't fit, you have to swim to the artifact and back all by yourself. It takes about 40 seconds to swim 100 meters using underwater scooter and about 80 seconds if you are not using underwater scooter. I had an artifact mission where the artifact had been placed about 500 meters away from the open cave spot where only humans and small creatures could fit. That means i had to spend about 3 and a half minutes to get to the artifact using scooter and then had to spend about 6 and a half minutes to get back with the artifact in hands. In total that makes it about 10 minutes that have to be spent just to swim to the artifact and back to the submarine. By the time i got back to the submarine, it got attacked and flooded by creatures, and my other ai crew members were dead. That is not fun to spend that much time to just swim without any action, especially while your submarine is getting destroyed during that time. There should be something done about that. I tried using hyperzine, but it seems like it either does not work at all for swimming, or its effect is too small to notice.
I think there should be something that could increase swimming speed when you can't use Underwater scooter. Either some chemical like hyperzine or something in the suit. Perhaps you could make diving suits increase your swimming speed when they are powered by batteries. Pretend that they have some kind of hydraulics or motors in them that help you swim faster.

===================================================================

Still not sure if i should make new issues for problems related to the dev version. Going to put any new ones here for now. (They might be outdated, since i am using the build taken from https://archive.database.red)

13: Game crashes upon any attempt to use Alt codes. Don't even need to click on any text window. As soon as you get to the main menu, pressing alt and any numpad number is enough for it to crash.

14: Putting this request here since voice controlled devices only work in the dev version.
Add an option to enable text chat in singleplayer, so players could use voice controlled devices without having to host a server.

15: Items that have new icons don't change the color of the icons when you color their sprites.
It was pretty convenient to see colors of the sprites when checking inventory or containers, as they are indicate special properties of the items.
For example, colored sprites of the flares indicate their light's colors.
![wilson-pc-2018-oct-15-015](https://user-images.githubusercontent.com/38168249/46927537-20c4b400-d060-11e8-80a3-2d59751f1826.jpg)
It's pretty hard to know that in the dev version if the description of the items has not been changed.
![wilson-pc-2018-oct-15-021](https://user-images.githubusercontent.com/38168249/46927546-27ebc200-d060-11e8-856e-7c980420a9dc.jpg)
There should be some kind of color indication, either by coloring the new sprites as well, or via some other way.
Perhaps something like this would work(though not sure if that would look good).
![wilson-pc-2018-oct-15-013](https://user-images.githubusercontent.com/38168249/46927629-8d3fb300-d060-11e8-84f0-6ec660e3d892.jpg)

16: The placement of containers' slots when just interacting with them or when holding them is different.
Not holding:
![wilson-pc-2018-oct-15-009](https://user-images.githubusercontent.com/38168249/46927732-279ff680-d061-11e8-9c68-6c921a8d8e25.jpg)
Holding:
![wilson-pc-2018-oct-15-023](https://user-images.githubusercontent.com/38168249/46927739-2cfd4100-d061-11e8-9185-c0a588294f37.jpg)

17: Can't access adder component's wiring panel. Also, this component does not have a fabrication recipe.

18: (Most likely just because the health and damage system is WIP)
Melee hits and explosives stun, but don't deal any damage, except for ic4 and nuclear shells with their fire damage type. Also creatures seem to deal less damage than before.

18.1: Kinda related to this, but more to the healing system: Xenogland extract's side effects are more harmful than its healing effect. Right now it can be used as poison, because even using it 1 time is enough to kill a person.

19: Some(Probably just the oxygenite tank now) items look like they have been cut in half.
Example(oxygenite tank);
![wilson-pc-2018-oct-15-006](https://user-images.githubusercontent.com/38168249/46961101-3078e280-d0ca-11e8-882d-abdfe2fb9e6d.jpg)
![wilson-pc-2018-oct-15-007](https://user-images.githubusercontent.com/38168249/46961069-20f99980-d0ca-11e8-8ad0-9f5f4dc646de.jpg)

20: Upon spawn of the submarine, sliders look like the settings are set at 0 while they are not.
![wilson-pc-2018-oct-15-004](https://user-images.githubusercontent.com/38168249/46961305-b137de80-d0ca-11e8-89cf-e87a9a4959dd.jpg)

21: Harpoon gun makes explosion effects similar to revolver when used underwater.

22: Clicking on selected items in sub editor sometimes moves them even if you did not move the mouse at all but just clicked on them.

23: Directional ping checkmark should be available on the sonar in both passive and active mode. Having to turn on active sonar before enabling directional ping makes your first sonar ping go in all directions, which makes using directional ping after it less effective.
Same thing with the zoom setting. Why not allow to use it in passive mode if you still can see the map when there is sonar noise nearby.

24: Knockback from revolver feels a bit too powerful, it sends ragdolls pretty far away. It should be lowered(I know that this is a game with "goofy ragdoll physics", but i feel like big knockback wouldn't be fun for both shooter and victim, since the target would be too unpredictable to aim at for the shooter and it would be unfun for the victim to be pushed around while being attacked(probably just a matter of preference though. Some might actually enjoy feeling the power of their weapons)).

25: Sprite scale resets upon saving and loading the submarine.(Probably just still WIP?)

26: To access your own or somebody else's health hud you have to press h; to close your own health hud you can just press h again, but to close somebody else's health hud you have to press g. That's a bit confusing and inconvenient.

27: Threshers somehow managed to get inside my submarine. Not sure if it's my fault or not.
![wilson-pc-2018-nov-5-005](https://user-images.githubusercontent.com/38168249/47993872-47d44a00-e123-11e8-95f7-8e10da654853.jpg)
Looks like they can get through hatches too. Is that intentional?
![wilson-pc-2018-nov-6-021](https://user-images.githubusercontent.com/38168249/48068822-6eb77c80-e206-11e8-87c0-1a8019f92251.jpg)

28: Upon converting a public version's submarine to the dev version black wires disappear. I assume it has been caused by replacement of black wires with brown wires. Might be fatal for some subs that used black wires in their systems.

29: Coilgun ammo crates placed in newly spawned coilgun loaders are at wrong positions. Coilgun loaders copied from subs that have it fine (like Turso) work fine even in other subs.
![wilson-pc-2018-nov-5-002](https://user-images.githubusercontent.com/38168249/48000060-051c6d00-e137-11e8-83cf-3f1d40a1c989.jpg)

30: It seems that sometimes submarine spawns right near the top of the map, which makes its top railgun get stuck in there(and that prevents the sub from moving downwards). Probably caused by map generation. It only happened a couple of times, so i was not aware of it enough to get any map seeds with that bug yet.

31: Probably related to number 4. 
Characters don't let go unconscious bodies after they regained consciousness, which lets you hit a player with a melee weapon like a wrench, grab them while they are stunned for a second, and keep beating them while you are holding them. 

32: Can't access rear railgun controller's wiring panel. Not a problem when making a new sub, since you have a sprite mirroring function, but might be an inconvenience if you decided to mess with the wiring on old subs. Perhaps you could make them get automatically converted into mirrored railgun controllers when opened in dev version, if that won't take too much effort.

33: Seems like in this version the reactor does not make sonar noise even if it's overheating. Bug or a feature?

**Comment by Regalis11** [comment]
Wow, thanks for putting this much time on the issue report! A lot of this feedback will be really useful. Many of these however are things that are already fixed, or things that we are aware of but haven't yet gotten around to fixing (but still it's good to have them listed here as reminders).

1: The new walls are placeholders. We're still trying to figure out what kind of pieces we need and what the final look of the walls should be, so we haven't yet started looking into balancing the durability values and such.

2: Torso grabbing was causing quite a lot of issues and in my opinion looked pretty bad. There's a chance will reimplement it later though.

3: Fixed in 5246ecf.

4: It should not be possible to grab conscious characters, so this seems to be a bug we have to look into.

5: I think Layer 4 was not intended to be something that's fun to listen to, it's only used on the highest intensity levels and it's unpleasant and unsettling on purpose. But I do somewhat agree with you, it may be a bit too much. I'll pass this to our audio guy and suggest toning it down a little.

6: This has been fixed too.

7 - 11: Yep, these are all bugs/problems that have to be taken care of. I wasn't aware of the handcuff or the autopilot issues, thanks for pointing those out!

12: I believe this was caused by the changes to the animation logic, not something that was done intentionally. There's been other unintentional changes to the movement/animation values too, but we haven't put much time into fixing those yet because all of the characters and their animations will be redone anyway.

**Comment by extraneus** [comment]
Hi BillCombs and thank you for the detailed feedback!

Swimming speed is related to animations, which are work in progress. It's possible that the humanoids swim slower now than they used to. However, that's not by design. Animations are run with parameters that are not yet tweaked. We are currently working on a character editor, which allows to edit the animations. When it's functional enough and after the new graphics and the design is ready, we'll start tweaking the values. There are also faster swim animations for all the characters, but they are not currently enabled for humanoids in game.

We'll have to take a look at the slider functionality. It might need some refining/fixing.

Also note that grabbing is now mapped to a separate key (default is "G"), so that it's easier to grab intentionally and not accidentally.

**Comment by BillCombs** [comment]
Thanks for your replies. It's really nice to game see developers work with the community. The whole game idea and mechanics are a lot of fun to play with. I am definitely buying the game once it comes out.

**Comment by BillCombs** [comment]
Closing this due to most of its content being moved to separate issues and the rest being insignificant.
