### ISSUE TITLE
Issues with deleting subs in subeditor

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8442]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deleting a sub in the sub editor seems to throw the following error in the console, although the file is successfully removed:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/5bf03f90-e1de-454b-bb74-3319894404d5)

The following steps will throw a null reference exception:
- Open sub editor
- Save a sub
- Delete the sub
- Save it again
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/56edaebb-c57f-446b-ac1b-6ecef9b5dc76)

Also managed to get another exception when I returned to the main menu (doesn't seem to happen consistently or I'm unsure about the exact steps):
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/b778e65b-9a88-4006-9c19-63ccc40b33ea)

**Version**
Unstable 0.17, debug windows : Regalis11/Barotrauma-development@54bfad1.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/728639dbb2038f072b798fd3d78441996994296c

**Comment by Rokvach** [comment]
My game crashed when I tried to reproduce this with the exact same steps

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b0fe3104-9cdf-4ed4-bd5f-92dd18a92e1b)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/91090efcd62a6e2a165e64b68b3290cac7bfa0c9

**Comment by Rokvach** [comment]
The delete button stopped functioning entirely now, after restarting the game it now allows me to only delete the submarine I just saved and nothing else.

**Comment by juanjp600** [comment]
Deleting from the Submarines folder has been re-enabled in https://github.com/Regalis11/Barotrauma-development/commit/4ac8b4ec7c26c8fff1a88c323d1465d0fcb59412, but note that #3198 should make this obsolete.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
