### ISSUE TITLE
commander talent doesn't give buff when giving maintenance orders

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8445]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
giving maintenance (blue colored) orders to bots doesn't give them the buff

assuming this is caused by https://github.com/Regalis11/Barotrauma-development/commit/f7565b2de056c9acd0a0e09c073279d1b9c48908

**Version**
v0.17.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fddd8d23a8abb544a3b8959c58fe6c1a10234197. Closing this ticket since this is sort of an extension of https://github.com/Regalis11/Barotrauma/issues/8308 (the fix for the previous issue didn't work correctly)
