### ISSUE TITLE
continuous output for NOT component hidden in game

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8446]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"continuous output" toggle for not component is hidden in game

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.16.6

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/25a549ad7280b52f25d2be5c14b1217004176a23

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
