### ISSUE TITLE
Navigation terminal that controls one docking port shows dock button as though it controls a different docking port.

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8447]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The docking button on a navigation terminal can appear as though that terminal controls a different docking hatch from the one it actually controls.  See [this image](https://files.catbox.moe/sqchsn.webp) for a better explanation.

**Steps To Reproduce**
Load up [this example sub](https://cdn.discordapp.com/attachments/427654262453960724/949128046881943572/buggy.sub) in the editor.  Note that the button controls the top (i.e. main) docking port, yet the dock button (when testing directly from the editor) still appears even though the submarine is not docked at the main docking port.  Thought testing I found that the game thinks it is controlling the docking port where the drone is docked.

**Version**
v0.16.7.0 Linux

**Additional information**
Possibly related to #8143 (as I'm not sure if that patch is present in the version I'm running).

I would like if we could just link a navigation terminal directly to the docking port it controls (for the purposes of the dock button appearing/hiding) by just spacebar + left click, to create a link similar to linking vents to an oxygen generator.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4bd458e6ddbb1d0c93942d106c8cd63d347a8dca

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
