### ISSUE TITLE
Game Crash after railgun shell shot damages a pirate (CharacterHealth.ReduceAfflictionOnLimb)

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#8448]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game Crashed after shooting a railgun shell into a Pirate Sub (next to one of the pirate crew)

**Steps To Reproduce**

**Version**
UnstableWindows, branch dev, revision 173eebf85d 

**Additional information**
Crash Log attached
[crashreport (61).log](https://github.com/Regalis11/Barotrauma/files/8186335/crashreport.61.log)

**Comment by Regalis11** [comment]
The stack trace seems to be the exact same as in https://github.com/regalis11/barotrauma/issues/8390, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c6a972bd1e2d930a8279ac5fbc7ca424af1c3d9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
