### ISSUE TITLE
Incorrect gap forming on Shell A 70 Degrees

### ISSUE THREAD

**Issue by k-Knight** [Regalis11/Barotrauma#8449]
**Description**
A gap when `Shell A 70 Degrees` breaks is formed having vertical direction instead of having a horizontal one.
That is one would expect breaches to appear at the left/right side of the hull since the piece is more of a vertical one, rather than a horizontal one. but the breaches appear at the top and the bottom sides of the hull instead.

**Steps To Reproduce**
* create a square hull
* add the  `Shell A 70 Degrees`  on the right edge of the hull
* enable `debugdraw`
* test by breaking the shell

**Version**
Latest version, windows

**Additional information**
Now it works like this: 
![image](https://user-images.githubusercontent.com/28106261/156786331-fad17e4a-093f-4beb-8c17-80844975dede.png)
But it should be like this:
![image](https://user-images.githubusercontent.com/28106261/156786400-127b72db-60ce-4297-8987-7eb59c0ffdfc.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f38c72f8be88a60ab4ac3e4e062350fca2703b5a

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
