### ISSUE TITLE
Localizations Overrides not working / Picking pointers at random

### ISSUE THREAD

**Issue by EricPfau** [Regalis11/Barotrauma#8450]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Created a mod which overrides the name and description of several vanilla items, and also translates these into different languages as well via localization. Upon launching the game in English, the overriden names will be used at random. EX. Renamed revolver to ".38 Revolver", when loading the game it will sometimes be ".38 Revolver" but closing and loading the game again it might say "Revolver" again.

**Steps To Reproduce**
1. Make a new localization file for a test mod and just test these 2 items.

infotexts language="English" nowhitespace="false" translatedname="English"
  entityname.revolver>.38 Revolver</entityname.revolver
  entitydescription.revolver>.38 caliber Revolver. Holds 6 rounds.</entitydescription.revolver
  entityname.revolverround>.38 ACP round</entityname.revolverround
  entitydescription.revolverround>A standard .38 ACP cartridge.</entitydescription.revolverround
/infotexts

Edit: Had to remove <, > due to formatting it seems.

2. Next, launch the game with this test mod enabled and this localization file included. "revolver" and "revolverround" will switch their names at random each launch. Sometimes you will load the game and it will say ".38 Revolver" sometimes you load the game and it says "Revolver" etc..

**Version**
v0.16.7.30
WIN10

**Additional information**
Seems a few other people have replicated this via the Baro Discord.

**Comment by esirprus** [comment]
As an unofficial localizer modder, I think it is good to let modders to override the localizations, so official won't have to check the localization, especially in languages they don't know. Yes, as devs you still need [Waiting](https://github.com/Regalis11/Barotrauma/labels/Waiting) official-localizers' work and merge them. But as players and modders we will have other solution.Such as "Simplified Chinese Texts Optimisation"(https://steamcommunity.com/sharedfiles/filedetails/?id=2608626775), it has 47,098 subscribers.

**Comment by Regalis11** [comment]
Finally got around to addressing this. Proper support for overriding texts is now implemented in https://github.com/Regalis11/Barotrauma-development/commit/cea04ab6e4d52b37434f60c84803617388008fad (commit in our private repo), meaning you can override texts the same way as any other content, e.g.
```
<override>
  <entityname.revolver>.38 Revolver</entityname.revolver>
  <entitydescription.revolver>.38 caliber Revolver. Holds 6 rounds.</entitydescription.revolver>
  <entityname.revolverround>.38 ACP round</entityname.revolverround>
  <entitydescription.revolverround>A standard .38 ACP cartridge.</entitydescription.revolverround>
</override>
```

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4596/commits/06055308efd9425324f3530d33e861b2d9ca61da

Testing notes in PR: https://github.com/Regalis11/Barotrauma-development/pull/4596

Attaching working test mods here also for reference
[override mod.zip](https://github.com/Regalis11/Barotrauma/files/13366318/override.mod.zip)

Closing ticket
