### ISSUE TITLE
Terrain generation: tiny pockets that things can slide into

### ISSUE THREAD

**Issue by AFK-TankyMOFO** [Regalis11/Barotrauma#8454]
Sometimes in terrain there will be tiny pockets that only small things can slide into, in my case usually harpoons, making them irretrievable.

In one case I even got sucked into one, like literally sucked in there like a vacuum and got stuck in there, unable to get out.

This is the clearest picture I have, me getting stuck in terrain with some crawlers:
![20220211171158_1](https://user-images.githubusercontent.com/75913633/156868953-848c676f-0315-43e2-853b-1a6b1c960380.jpg)

**Comment by Regalis11** [comment]
Thank you for the report! If anyone happens to find a level seed or has a save file where this occurs, those would help us a lot in debugging this.

**Comment by Regalis11** [comment]
No known steps to repro, closing
