### ISSUE TITLE
Disconnect brain-death triggers no-death round talents 

### ISSUE THREAD

**Issue by Anarengon** [Regalis11/Barotrauma#8455]
Talents like field medic, R&D, Bootcamp, that give bonuses if nobody dies don't give any bonus if someone leaves the server and their ragdoll gets braindeath

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5fb4447c94491d5f9af2844caecd2e7778a6cbc2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
