### ISSUE TITLE
Ambiguous Translation for Terminology "Condition" in Chinese Translations

### ISSUE THREAD

**Issue by Tanimodori** [Regalis11/Barotrauma#8456]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

In the game, term "condition" of a machine means its duability, "condition" of fabricating an item means its level requirement, and term  "state" means its working state. Since the word "condition" can mean ***"[1] the state of something with regard to its appearance, quality, or working order"*** or ***"[2] an ability to do or learn something well and easily"*** in English, these two terms are translated into "状态/狀態" ***(lit. state, condition[1])*** or "条件/條件" ***(lit. condition[2])*** in Chinese Translations.  **I suggest avoid using the term "condition"**.

The related translation items are listed below:

```xml
<!-- English, Simp. Chinese, Trad. Chinese Transaltions of same items -->

<!-- "Condition" meaning: [2] level requirement-->
<fabricatorrequiredcondition>Condition</fabricatorrequiredcondition>
<fabricatorrequiredcondition>条件</fabricatorrequiredcondition>
<fabricatorrequiredcondition>條件</fabricatorrequiredcondition>
<!-- Suggeseted Fix -->
<fabricatorrequiredcondition>Level Requirement</fabricatorrequiredcondition>
<fabricatorrequiredcondition>等级需求</fabricatorrequiredcondition>
<fabricatorrequiredcondition>等級需求</fabricatorrequiredcondition>

<!-- "Condition" meaning: [1] duability -->
<qualitystattypenames.condition>Max Condition</qualitystattypenames.condition>
<qualitystattypenames.condition>最大条件</qualitystattypenames.condition>
<qualitystattypenames.condition>最大條件</qualitystattypenames.condition>
<!-- Suggeseted Fix -->
<qualitystattypenames.condition>Max Duability</qualitystattypenames.condition>
<qualitystattypenames.condition>最大耐久</qualitystattypenames.condition>
<qualitystattypenames.condition>最大耐久</qualitystattypenames.condition>

<!-- "Condition" meaning: [1] duability -->
<statusmonitorbutton.hullcondition.tooltip>Hull condition</statusmonitorbutton.hullcondition.tooltip>
<statusmonitorbutton.hullcondition.tooltip>船体状况</statusmonitorbutton.hullcondition.tooltip>
<statusmonitorbutton.hullcondition.tooltip>船體狀況</statusmonitorbutton.hullcondition.tooltip>
<!-- Suggeseted Fix -->
<statusmonitorbutton.hullcondition.tooltip>Hull duability</statusmonitorbutton.hullcondition.tooltip>
<statusmonitorbutton.hullcondition.tooltip>船体耐久</statusmonitorbutton.hullcondition.tooltip>
<statusmonitorbutton.hullcondition.tooltip>船體耐久</statusmonitorbutton.hullcondition.tooltip>


<!-- "Condition" meaning: [1] duability -->
<connection.conditionout>condition_out</connection.conditionout>
<connection.conditionout>状态输出</connection.conditionout>
<connection.conditionout>狀態輸出</connection.conditionout>
<!-- Suggeseted Fix -->
<connection.conditionout>duability_out</connection.conditionout>
<connection.conditionout>耐久输出</connection.conditionout>
<connection.conditionout>耐久輸出</connection.conditionout>
<!-- Note there're state_outs meaning working states with same translation -->
<connection.stateout>state_out</connection.stateout>
<connection.stateout>状态输出</connection.stateout>
<connection.stateout>狀態輸出</connection.stateout>
```

**Steps To Reproduce**
In-game display.

**Version**
v0.16.7.0 (Windows, revision aa4c852c2c)

**Comment by Regalis11** [comment]
>In the game, term "condition" of a machine means its duability

I don't think this is entirely accurate. The condition of a machine essentially means how damaged it is, while I'd interpret durability as "how much damage the item can withstand". Or in gameplay terms, the condition would be the device's current health, while durability is its maximum health.

>"condition" of fabricating an item means its level requirement

This isn't true, it doesn't mean a level requirement but the condition of the ingredient.

**Comment by Regalis11** [comment]
Thank you for the follow-up! I've passed this report to the translators.

**Comment by Regalis11** [comment]
Doesn't seem to have been addressed, moving back to backlog

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f16958f6774ea0c5194c509710918caaa76d841a
