### ISSUE TITLE
Inconsistent Translation in Wiring Components in Chinese Translations

### ISSUE THREAD

**Issue by Tanimodori** [Regalis11/Barotrauma#8457]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There're 4 different translation for word "component" in Chinese translations, e.g.

```xml
<!-- English, Simp. Chinese, Trad. Chinese Transaltions of same items -->

<!-- Translation A: 逻辑门/邏輯門 (lit. Logic Gate) -->
<entityname.andcomponent>And Component</entityname.andcomponent>
<entityname.andcomponent>与逻辑门</entityname.andcomponent>
<entityname.andcomponent>與邏輯門</entityname.andcomponent>

<!-- Translation B: 元件/元件 (lit. element, component) -->
<entityname.sincomponent>Sin Component</entityname.sincomponent>
<entityname.sincomponent>正弦元件</entityname.sincomponent>
<entityname.sincomponent>正弦元件</entityname.sincomponent>

<!-- Translation C: 模块/模組 (lit. module) -->
<entityname.concatcomponent>Concatenation Component</entityname.concatcomponent>
<entityname.concatcomponent>连接模块</entityname.concatcomponent>
<entityname.concatcomponent>連接模組</entityname.concatcomponent>

<!-- Translation D: 组件/組件 (lit. component) -->
<entityname.signalcheckcomponent>Signal Check Component</entityname.signalcheckcomponent>
<entityname.signalcheckcomponent>信号检查组件</entityname.signalcheckcomponent>
<entityname.signalcheckcomponent>信號檢查組件</entityname.signalcheckcomponent>
```

The inconsistency makes filtering wiring components in fabricator difficult. I suggest apply Translation D to all translations of wiring comonents.

The term "false output" also has different translations: "假输出/假輸出" (lit. falsy output) and "伪输出/偽輸出" (lit. default output). I suggest apply the former to all translations of "false output".

**Steps To Reproduce**
In-game display.

**Version**
v0.16.7.0 (Windows, revision aa4c852c2c)

**Comment by Regalis11** [comment]
Passed this report to the translators, let's wait for the next batch of texts and verify this is fixed

**Comment by Regalis11** [comment]
Doesn't seem to have been addressed, moving back to backlog

**Comment by Regalis11** [comment]
Still doesn't seem to have been addressed, moving back to backlog

**Comment by Tanimodori** [comment]
Come on, man. You don't want to remember which word to use -- "length", "size", "count" or "capacity" -- on an array-like object without IntelliSense when coding, as well as I don't want to remember which word to use -- "逻辑门", "元件", "组件", or "模块" when searching for a specific MODULE in game. **JUST MAKE THE TRANSLATION CONSISTENT PLEASE.**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/22878056810e8dcb49983205cb94acd2cc210c77

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
