### ISSUE TITLE
changing audio output ain't workin

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8459]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
manually changing audio output in-game from speakers to wireless headphones doesn't seem to be working, audio keeps coming out from speakers, also doesn't work vice versa

**Version**
v0.17.0

**Comment by cshingle** [comment]
Likely a duplicate of #7081

**Comment by LePiromano** [comment]
> Likely a duplicate of #7081

Nah this is new, didn't happen before 0.17

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6804b0e1028eb83b94fb48e419b89d78a2f2a8bb

**Comment by LePiromano** [comment]
tested, the fix works

**Comment by Rokvach** [comment]
Closing.
