### ISSUE TITLE
Add an option to make RegEx Find component only send a signal while it's receiving a signal

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#846]
Right now it just keeps sending a signal without stopping, even if no signal is coming to its input, which might make it hard to use in some systems.
It can probably be worked around using additional wires and electronic components, but it takes more resources, more inventory slots and some time to fabricate those additional components, if there aren't any on the sub. That makes it pretty bulky. It should be simplified.

Though i don't really know how it works with the game and its code. If that feature would make the component update a lot, that probably would heavily affect performance in cases of big wire systems. But i don't really know how much of an impact wiring has on the performance when it does not affect lighting and moving parts of the sub. Perhaps it's actually really small. But if it's big enough to be noticeable, perhaps that component should just have an option to make it only send a signal one time whenever it gets a new signal, instead of making it constantly check if a signal is still coming to it. That would still help a lot.

I think the wiring should be as simple as possible to do during the actual gameplay. You could be automating the sub's systems to make your crew's work easier, or use them to get an advantage when playing as a traitor. It would encourage players to work with the wiring more when playing as engineer or mechanic, and it would also give more options to traitors. The less bulky it is - the more often it will be used. Encouraging players to try new things makes the gameplay more diverse.

**Comment by Regalis11** [comment]
This is a good idea, there's really no reason to make the railguns react to invalid signals.

As a hint though, the regex find component is really handy for this sort of stuff. Regular expressions can be a little hard to figure out at first, but they're really powerful once you get a hang of them. And if you don't want to bother, you can find basic expressions like "check if a string only contains numbers", "check if a string is a number between x and y", "check if a string contains any of these words" with a little bit of googling. But in any case, thanks for pointing this out, we don't want to make the sub creators learn regex just to do something this simple. :)
