### ISSUE TITLE
broodmother has no gaze rage sprite

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8463]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
every creature affected by watcher's gaze has a glowing head sprite when afflicted gazer rage, broodmother doesn't and i'm very curious to see what its brain looks like

**Version**
v0.17.0

**Comment by itchyOwl** [comment]
An oversight. Thanks for reporting.

**Comment by itchyOwl** [comment]
I think it never was intentional that the broodmother would be affected by the watcher's gaze. Don't see it an issue if she would, but as there's no sprite for it, I disabled it in Regalis11/Barotrauma-development@21bd2f2.

Let's keep the ticket open in case we'll want to revisit this.

**Comment by LePiromano** [comment]
yeah honestly a broodmother with 3000 health sounds a bit ridiculous

**Comment by itchyOwl** [comment]
Broodmother is not normally spawned with Watcher, so it's should be a rare occasion that they are around at same time.

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
