### ISSUE TITLE
trusted and esteemed captain talents giving medals when they shouldn't

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8467]
- [yea] I have searched the issue tracker to check if the issue has already been reported.

**Description**
didn't do a repair beacon side quest which was the only mission and got both a commendation and a medal, but only 1 commendation, so trucker is not affected by the bug.

**Version**
v0.17.0

**Comment by LePiromano** [comment]
apparently they always give medals, even when you dont have a misión at all

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb720cdf2167fd6e7beaf0e7d5333c66fb2c8d29

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
