### ISSUE TITLE
Text color bug in abandoned outpost tooltip

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8469]
- [yea] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/156946797-8f147118-57ae-4fa6-b0fa-59c2cbe402f6.png)

**Version**
v0.17.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ebb029730dfe7d262eb6533355ccccf041eb4a5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
