### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Wasbay** [Regalis11/Barotrauma#847]
So, when I try to refresh the servers, it shows that there are no servers avaiable, and when I try to refresh again, pop up a message on the screen saying:
Connection Error
Error while connecting to master server {System.Net.WebExeption: O servidor cometeu uma violação de protocolo.
Section=ResponseStatusLine em System.Net.HttpWebRequest.EndGetResponse(IAsyncResultaSyncResult)
em RestSharp.Http.GetRaw.ResponseAsync(IAsyncResultresult.Action'1 callback)
em RestSharp.Http.ResponseCallback(IAsyncResult result, Action'1 callback) }.
Can you tell me how to solve it?

**Comment by Regalis11** [comment]
Should not be a problem in the Steam version because it uses Steamworks for the server list instead of the old master server.
