### ISSUE TITLE
Battery draw does not change when condition hits 0

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8470]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a battery is damaged to the point it is no longer functional (i.e. condition transitions from a positive number to 0), its draw from the grid is 'locked' to whatever it was at the time it was last functioning.  However, when a battery's condition is 0, the battery will not receive any charge, regardless of how much it's actually pulling from the grid.

For example, if a default battery was half full (1000 charge), and set to a 100% charge rate (500W draw), and was then damaged to the point it was not functional (0 condition), it will still pull 500W.  Even if the charge rate slider is adjusted, so long as the battery is not repaired, it will still pull 500W, but charge will not change.  The same battery set to 0% charge (or a completely full battery set to any amount of charge) at the time it was damaged to 0 condition would pull 0W.

**Steps To Reproduce**
Create a sub with a battery, and connect its `POWER_IN` to a junction box `POWER` and that `POWER` to a functioning reactor.  Connect the `LOAD_VALUE_OUT` on the JB to `SET_TEXT` on a text display to monitor how much power the battery attempting to draw.  Set the `Recharge Rate` slider to anything higher than 0, then damage the battery to the point it is completely broken with an explosive (reads 0 on `CONDITION_OUT`, which can be sent to another text display) before it reaches full charge.

The battery will no longer receive any charge, but will still pull however many watts it was configured to at the time it 'died'.  Further adjustments of the slider result in no change to the amount of watts pulled by the damaged battery, until repaired.

**Version**
v0.16.7.0 Linux

**Additional information**
I think it would be best if all batteries at 0 condition also had their drain set to 0 (as the cannot be charged until repaired anyway), though this should *not* graphically affect the charge rate slider or what the charge rate is when the battery is repaired.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e94638827a4eb21761d1c8356fa6c00f1c5dd977

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
