### ISSUE TITLE
Ballast Flora infected small pump uses a wrong sprite

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8474]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Use `ballastflora infect` and `ballastflora growthwarp 1000` and notice the appearance of small pumps once they get infected

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/aa38bb66e5320fe151789b2fcdbd55f416958f4d

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/53162b31-d6cf-4f4f-bac6-183748083d13)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/10aae1b33f5a8707800cf116c9c797b974759b1a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
