### ISSUE TITLE
Compilation of Ruins issues

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8479]
- [x] LOTS of ruin decal sprites misaligned. The sprites themselves are not scaled properly, "looping" the texture. _I did not check them all but this is affecting almost every sprite_

Left: default size
Right: rescaled sprite
![image](https://user-images.githubusercontent.com/73229309/157048068-5045c95f-41e2-48ca-a487-b31e6a0e13c1.png)

![image](https://user-images.githubusercontent.com/73229309/157047144-945d3b99-a819-4893-a85e-93b310314ba9.png)

- [x] Disconnected wires in Alien_chambers1
![image](https://user-images.githubusercontent.com/73229309/157046896-ee20b3b2-35c5-4ad5-9cc3-dcfbc08702c3.png)

- [x] Disconnected wires in Alien_chambers2
![image](https://user-images.githubusercontent.com/73229309/157047422-a7988cb6-d860-4c9a-822f-b31aa89119c6.png)

- [x] Alien_entrance3 doors not wired at all
![image](https://user-images.githubusercontent.com/73229309/157049785-a6401abe-fddd-4bae-90ac-977e3e449777.png)

- [x] Alien_hallwaysphere gravity sphere can be interacted with a screwdriver
![image](https://user-images.githubusercontent.com/73229309/157050376-f76d7600-ef5b-4899-a502-a54b154c6ef8.png)

- [x] Door connection panels are interactable in some rooms 
![image](https://user-images.githubusercontent.com/73229309/157051204-79fe5847-acec-45f8-b2ef-40690752a7e1.png)

- [x] Terminals connection panels are interactable in some rooms 
![image](https://user-images.githubusercontent.com/73229309/157052673-6b400866-7624-46c2-a20e-7589c7bf49f0.png)

- [x] Light components are interactable in Alien_vaultmodule2
![image](https://user-images.githubusercontent.com/73229309/157058566-1f51f461-9419-4124-b9c1-bfe7efe9cda0.png)

- [x] Some terminals have trinkets in them
![image](https://user-images.githubusercontent.com/73229309/157059039-b9a08af6-4f1c-405b-a2ff-fc14938c6d19.png)

- [x] Doors not reaching walls in Alien_storage1R
![image](https://user-images.githubusercontent.com/73229309/157335899-a482c9b1-a957-4618-9b03-85568fc9c930.png)

- [x] Alien_Entrance2 top door can block access when connected
- [x] Alien_Entrance2 right door can lead into a hallway into nothing _(pic is from my version but the vanilla module has the same problem)_
![image](https://user-images.githubusercontent.com/73229309/157453980-e0aa45d4-0037-44a8-b6f7-8cd046511258.png)

- [x] Alien_maintenancetunnels2 (L and R) can lead into nothing/outside. Should only appear between two modules? How?
![image](https://user-images.githubusercontent.com/73229309/157455724-61122c83-b30e-4860-bb04-6476ced68dd5.png)

- [x] Same issue for Alien_HallwayHorizontal/Vertical
![image](https://user-images.githubusercontent.com/73229309/157523151-20f3e50b-c889-45c2-ae39-52459e9cf4d6.png)

- [x] Alien_maintenancetunnels1 only connects to the right, has no walls on both ends
![image](https://user-images.githubusercontent.com/73229309/157514231-25fa20f7-38b1-45d0-afa3-15cf2719fd48.png)

- [x] Dead-ends sometimes appear without a wall blocking them off
![image](https://user-images.githubusercontent.com/73229309/157516000-6fd0640b-d15a-49b4-bb7b-bdb1a2529652.png)

- [x] Closed off walls can still generate waypoints outside, with watchers trying to flee and getting stuck
_This is from my custom ruins, I removed the doors and this leads to a waypoint linking to the outside_
![image](https://user-images.githubusercontent.com/73229309/157564042-1c5e2ae8-26a3-44fb-ad67-4eb530aa4cb9.png)
![image](https://user-images.githubusercontent.com/73229309/157877668-4a2a2a54-81ed-47a6-9fdc-9841945b4a3f.png)

- [x] Guardians still try to heal (and do so?) on deactivated (not *destroyed*) pods

- [ ] Medium-sized Alien Hatches/Doors don't have a connection panel "Equipped required"

**Version**
v0.16.7.0

**Comment by ekqvist** [comment]
> Ruin vents with no spawn parameters

That's intentional, some of them are intended as pure decorative

**Comment by ubertpendragon** [comment]
Also check https://github.com/Regalis11/Barotrauma/discussions/8492

Where I attempt to tackle some of the design issues in ruins with a somewhat functional rework

**Comment by danielasteljoki** [comment]
>Some terminals have trinkets in them

That's intentional. So is ruins generating dead ends and doors that lead to outside. Fixed connection panels and doors in a4f4c3b.

**Comment by dinhtuananhfakefish** [comment]
Fixed in f0ee4c8

**Comment by ubertpendragon** [comment]
- [ ] Alien_Entrance3 walls and doors aren't linked + waypoints not refreshed

![image](https://user-images.githubusercontent.com/73229309/188270686-837cdd37-4953-4dfc-ac53-163bc83255cf.pn
![image](https://user-images.githubusercontent.com/73229309/188270707-d8c08770-b7ed-47de-bebd-40ca2ae28f7e.png)
![image](https://user-images.githubusercontent.com/73229309/188270769-c99e81e6-7009-4229-8ee7-6fa6312f50d7.png)

**Comment by Regalis11** [comment]
Fixed Alien_Entrance3 in https://github.com/Regalis11/Barotrauma-development/commit/d641b3359ce29ce968c037c093eb1dc671be2f28.

I also noticed there are still problems with the ruin decals in almost every module, I'll uncheck the checkbox

**Comment by dinhtuananhfakefish** [comment]
Fixed the ruin modules misaligned in f85ccba

**Comment by Regalis11** [comment]
> Closed off walls can still generate waypoints outside, with watchers trying to flee and getting stuck
> This is from my custom ruins, I removed the doors and this leads to a waypoint linking to the outside

To me this looks like an issue with those custom ruin modules. The ruin generator creates a path out from the waypoints linked to gaps at the edge of the ruin (= gaps leading from inside the ruin to outside), and there seems to be a gap like that in all of those screenshots. Removing those should fix the issue.

**Comment by Regalis11** [comment]
> Medium-sized Alien Hatches/Doors don't have a connection panel "Equipped required"

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/449c942f51254117704713dab5aa49378c7b4153

Note for testing:
An easy way to test this is by editing a vanilla module in the sub editor (e.g. Alien_Chambers1). Wire a switch to the set_state input of the pod to make it easier to activate/deactivate. You also need to comment out the following line, otherwise the guardian will consider the module an outpost and ignore the pod:
![image](https://user-images.githubusercontent.com/14351070/211882676-e3a91611-80c1-4236-8c16-2bb9adf15e90.png)

**Comment by Rokvach** [comment]
Tested, didn't spot any issues. Everything seems to be fixed and working. Closing.
