### ISSUE TITLE
Some issues with the latest Linux build

### ISSUE THREAD

**Issue by escept** [Regalis11/Barotrauma#848]
On my server randomly at spawn people start receiving entity not found errors, then get disconnected for syncing with the server for too long. This only started happening when I switched to Linux. I downloaded the game from the UG mirror.
Edit: this was on 0.8.2.0,I didn't notice the new release. I'll see tomorrow if 0.8.2.1 has the same issue.

**Comment by escept** [comment]
Reopening, the issue is still present on 0.8.2.1 for me.

**Comment by Regalis11** [comment]
Unfortunately I'm not sure what's causing this, but if you could provide some more info it might be easier to diagnose:
1. Are you using the dedicated server or hosting from the normal game?
2. Does it happen immediately after a round starts, or only when a client joins mid-round?
3. Are you using any mods?
4. If you were able to find out what the entity that's causing those errors is, it'd be extremely helpful. You can get a list of entities and their IDs using the console command "dumpids [count]", where the count parameter is the number of entities to list. In this case, you could enter "dumpids 1951" at the server's side and hopefully see the entity in question at the end of the list.

I'm sorry for the inconvenience! If you can find any more details about this (in particular what the entity is) it'd be a great help.

**Comment by escept** [comment]
1. Dedicated server. I'm running Ubuntu server (64 bit).
2. I never saw it happen after a respawn shuttle, only at round starts occasionally.
3. No mods.
4. Now, that I've tested it, (now said entity 1777 not found), dumpids showed that ID 1777 is actually the player.

**Comment by Regalis11** [comment]
Managed to reproduce it now. It seems that it has something to do with level generation, in some cases the ruins generate differently at the client's side, causing a different number of structures and items to be created which leads to a ton of entity ID mismatches. Not sure what's causing it yet - at first I suspected it was due to the recently added level mirroring, but it seems to happen in non-mirrored levels as well. I'll do some more debugging and try to fix this asap.

**Comment by Regalis11** [comment]
Floating point errors, my arch nemesis.
![screenshot from 2018-10-17 23-32-01](https://user-images.githubusercontent.com/14351070/47114729-58e91400-d265-11e8-91c4-195d7687cea4.png)

Looks like a few of the floating point calculations done during the level generation may produce different results on different machines (and apparently even on the same machine), which causes the layouts of the levels to differ, leading to the number of items/structures in the level being different and IDs getting completely messed up.

I'm not quite sure why this seems to only happen (or at least be more common) on Linux, nor why this problem hasn't surfaced before, but in any case I need to rethink the level generation logic a bit to fix it.

**Comment by escept** [comment]
I'm glad to hear that you figured it out! I'm confused how this error never surfaced for people I asked hosting on Linux, though.

**Comment by escept** [comment]
Oh... It happened again. Seems to be more rare now, though

**Comment by Panzergrenadier** [comment]
How can i install mono 5.4 on Ubuntu 14.04?

**Comment by hubismal** [comment]
> How can i install mono 5.4 on Ubuntu 14.04?

This was such a frequently asked issue I made a guide for it. You can find out how to install Mono 5.4 [here](https://hubismal.neocities.org/barotrauma/)

Note that this isn't/won't be necessary for the full release.

**Comment by SaulApostle** [comment]
![2UQ51NF9J`U5QS4JKMBHD~V](https://user-images.githubusercontent.com/11502419/60386262-4b0eb280-9ac5-11e9-95b3-a4a924d08c27.png)
9.0.7 win10

**Comment by Regalis11** [comment]
Created a new ticket with more info: #2723

**Comment by DarkDestiny21** [comment]
I had this happened to me when I want to join my friend modded lobbies I have to enable or disable some mods to fix it or just rejoin the lobbies.

**Comment by gosver** [comment]
> Looks like a few of the floating point calculations done during the level generation may produce different results on different machines (and apparently even on the same machine), which causes the layouts of the levels to differ, leading to the number of items/structures in the level being different and IDs getting completely messed up.
> 
> I'm not quite sure why this seems to only happen (or at least be more common) on Linux, nor why this problem hasn't surfaced before, but in any case I need to rethink the level generation logic a bit to fix it.

I get this problem on Winodws 10, server Player-Hosted with mods
