### ISSUE TITLE
Ruin Vent Y axis offset is inverted

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8480]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Y axis offset is inverted
![image](https://user-images.githubusercontent.com/73229309/157062092-bf0a62e6-77e3-449b-aa4b-316a5d8b06ed.png)

**Steps To Reproduce**
Place a Ruin spawner
Set parameters as screenshot
Wrenches spawn 200 units above, not below

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab055448f7e2b95e96c9beeb7a2e6bc69eadcf6a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
