### ISSUE TITLE
Periscope does not move camera or show targeting overlay when there are several components between it and the turret.

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8483]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When there are several components between the periscope and the turret, it will not center the camera on the turret or provide the aiming overlay (circle/cross-hair).

**Steps To Reproduce**
Download and extract [this tar file](https://cdn.discordapp.com/attachments/427654262453960724/950631980423348314/Buggy.tar) into Barotrauma's `Submarines` directory.  Load the 'Buggy' submarine in the editor, and test it.  Get on the periscope, and notice that while the drone is docked, the drone's turret responds to the angle but does not center the camera over the turret, and the overlay does not appear.  When the drone is undocked (and the signal has a shorter path to the turret and unrestricted turret sweep) the problem does not occur.

**Version**
v0.16.7.0 Linux

**Additional information**
The intent here is to limit the range of the turret's sweep when the drone is docked (so it doesn't shoot the main submarine), but give it its full range when it's not docked.  The math is working (as can be seen on the Text Display), but the camera does not center on the drone's gun while it is docked and using the periscope.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/238c06eeb2ceb8fe0a8b7793fd1a28f17f437d87

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
