### ISSUE TITLE
Make railgun's position input ignore signals that are not made of numbers

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#849]
So it would be easier to make systems that control railgun's position.

 For example, i am currently trying to make railguns controllable by ingame chat:
![voice controlled railgun](https://user-images.githubusercontent.com/38168249/46964891-7dad8200-d0d3-11e8-91b9-320e7780b86c.gif)
 One wifi component receives a signal from the radio and sends it to railgun's position and trigger inputs. The trigger one has a signal check component connected to it, so it won't shoot upon changing position, but would shoot upon receiving a certain text signal(in that case letter " f ").
The problem is that for some reason railgun seems to count non-number inputs as 0. Therefore, since the wifi component sends signals to both inputs, making it shoot also resets its position.
 One of possible workarounds would be adding more components that would check for every possible position number(or at least integers) and the word or letter that triggers shooting, but that is just too bulky; too many things needed to do a simple function. You could also try connecting railgun's trigger input to wifi with a different channel and select it on the radio when you need to shoot(when the feature of switching radio channels comes). But that's also pretty bulky, especially for the case of using railguns while being outside with a hostile creature near you; you need to be able to work as fast as possible to stay alive.
 One interesting way to fix this would be adding a component that filters input and only lets certain signals to pass. But that would most likely require a lot more effort to implement(though it would also help with other kinds of wire systems).
 It would probably be easier to make railgun ignore letters and words. That shouldn't cause any problems, since they are most likely not really used for anything in those systems.

**Comment by Regalis11** [comment]
This is a good idea, there's really no reason to make the railguns react to invalid signals.

As a hint though, the regex find component is really handy for this sort of stuff. Regular expressions can be a little hard to figure out at first, but they're really powerful once you get a hang of them. And if you don't want to bother, you can find basic expressions like "check if a string only contains numbers", "check if a string is a number between x and y", "check if a string contains any of these words" with a little bit of googling. But in any case, thanks for pointing this out, we don't want to make the sub creators learn regex just to do something this simple. :)

**Comment by BillCombs** [comment]
Appreciate the advice, though there is a problem with it in this case. Regex find component doesn't work like a filter, it has a set output. So in this case it wouldn't work, since you need to send different signals to different inputs, but it only sends one kind of a signal no matter what the input is. That means you would still have to use one for each possible combination.

It would be nice to have some kind of regex based signal filter.
