### ISSUE TITLE
Sub sprite size, color and depth reset

### ISSUE THREAD

**Issue by VulpineJAO** [Regalis11/Barotrauma#8493]
**Description**
Submarine saved in the V 0.17.0.0 unstable versions submarine editor loaded in the stable versions submarine editor gets its sprites depths, colors and scales reset to their default values. - I really hope it doesn't stay this way... :(

**Steps To Reproduce**
1. Save a submarine in the V 0.17.0.0 unstable versions submarine editor.
2. Load this submarine in the stable versions submarine editor.

**Version**
V 0.16.7.0 and V 0.17.0.0

**Additional information**
If the same submarine is then loaded in the unstable versions submarine editor again, it loads correctly. 
There seems to be a problem or a difference in the way the submarine file is read between the two game versions. 
The stable version seems to incorrectly read the submarine file created or edited in the unstable versions submarine editor.
This problem didn't seem to exist before the "Rising Tide" update.
Screenshots and the submarines file are all uploaded below.

![V_0 17 0 0_unstable](https://user-images.githubusercontent.com/45701649/157516950-98d7b221-0580-4f0e-a153-8075ccc1e280.jpg)
![V_0 16 0 0_stable](https://user-images.githubusercontent.com/45701649/157516998-17218b48-2f70-4968-8aa8-be7e225eb4cb.jpg)
[Horizon mk II.zip](https://github.com/Regalis11/Barotrauma/files/8217566/Horizon.mk.II.zip)

**Comment by Regalis11** [comment]
> once you save a sub in the new version of the editor it would break if you go backward, but have not tried it.

Yeah, trying to load subs saved with a newer version of the game in an older version can lead to all sorts of problems, so I would not recommend it. This is the case with v0.17 and all the modding-related refactoring in particular: it _will_ break the sub due to changes relating to how we handle case-sensitivity in xml files.
