### ISSUE TITLE
Drag and drop preview picture in sub editor sends an error message

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8494]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When dragging and dropping a .jpg or .png from the explorer into the sub editor window, you get an error message
![image](https://user-images.githubusercontent.com/73229309/157530201-cd9207e3-5f05-47e3-8bad-e056f757a662.png)

Using the in-game browser works fine however

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4201b02c43df0d37031b45abbe10351157e8e8d7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
