### ISSUE TITLE
Crash after updating tag on secure cabinet in sub editor

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#8497]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I updated the tag on my fuel rod cabinet and the game crashed. I removed all mods (except custom subs), restarted the game and tried it again and it crashed again. I tried it a third time on an empty sub editor sub and was unable to replicate it. I loaded up a vanilla sub and tried it again and again was unable to replicate it. Once I was unable to replicate it, it worked fine on my sub, so I don't think sending my sub file will be helpful.
I attached the log from the second try, but the exception was the same both times.

**Steps To Reproduce**
Start with a secure steel cabinet with the tags "locker,container,securecontainer,weaponcontainer"
Change the tags to "locker,container,securecontainer,engcab"
It has a Picked required of id_engineer if that matters.

**Version**
Game version 0.16.7.0 (ReleaseLinux, branch release, revision aa4c852c2c).
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/8220960/crashreport.6.log)

**Additional information**
Hopefully the stack trace will get you pointed in the right directing because reproducing it seems very random.

**Comment by Regalis11** [comment]
Seems to have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/632fdd418949fc49f47bf65e5b1fdd6893b032ad

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
