### ISSUE TITLE
Supercapacitor efficiency 2x worse on Herja, Winterhalter and Barsuk

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8499]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The default Supercapacitor Efficiency setting is 0.10
Every vanilla sub is set to 0.10 efficiency, except the 3 new subs where it is set to 0.05.

These subs charge twice as slow

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
