### ISSUE TITLE
'Endround' button overlapping 'Serverlog' button

### ISSUE THREAD

**Issue by LandonGam3r** [Regalis11/Barotrauma#850]
Not sure if this has been reported already. As client it's not possible to open the serverlog viewer when having permissions both for ending round and viewing logs. The buttons overlap each other. 

Adding to that: It's possible to see and click the 'Serverlog' button even though not having permissions to view serverlogs, although there are no logs visible when opened.

**Comment by Andrej134234** [comment]
XD its  the host of the public servers

**Comment by Regalis11** [comment]
Fixed in the dev version
