### ISSUE TITLE
The bug about the security officer's talent

### ISSUE THREAD

**Issue by CanXue233** [Regalis11/Barotrauma#8500]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems that the extra SMG magazine made by the security officer who had picked the talent Munitions Expertise will be replaced by a SMG round.(when the talent is activated)

**Steps To Reproduce**
Choose the security officer and pick the talent Munitions Expertise, then make some SMG magazines, you will see the SMG round if everything goes well.

**Version**
0.16.6.7   Windows10

**Additional information**
None

**Comment by CanXue233** [comment]
It may have something to do with this [https://github.com/Regalis11/Barotrauma/issues/8356](url)

**Comment by Regalis11** [comment]
Seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/8356. The bullet doesn't seem to actually replace the magazine, it just looks like it if you don't happen to get the extra magazine (the talent has a 50% chance of giving you that extra mag).
