### ISSUE TITLE
new supercap defaults/ used values means supercap never run dry

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8502]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the new and force updated values of supercap are much higher than their effective previously, even at a low setting, resulting in unlimited energy for firing.

Previously: max effective recharge 20, can fire a while and will run supercap dry

Now: max effective recharge 100, a 5x increase, can continuously fire as long as there's ammo. Even at ~60% (36 recharge), that's enough to fire forever with no drawbacks

Proposal: 

make > 50% recharge rate damage the power container while charging. (Quickly for supercaps) Honestly the graphics of the Red Glow and orange/red bars was percieved to be "Dangerous" >_>

reduce max effective recharge from 100 to about 20-30

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.17.0.0

**Additional information**

**Comment by ubertpendragon** [comment]
At 100% the supercaps draw a lot of extra power so having "infinite" coilgun energy is somewhat balanced as long as you have limited reactor capacity, which is up to sub designers? Charge speed can be easily adjusted

**However, it's really easy to break by simply wiring batteries into supercap**. The battery acts as a massive power bank for the supercap. 

A default 2000kw/min battery can hold 10x the capacity of a 20kw/min Supercap (with efficiency factored). 
You can easily and much more efficiently create a huge power backup for supercaps.

**Comment by cshingle** [comment]
I have an alternative suggestion which seems to be in the direction that the recent update has gone.
Make the capacitor behave like real capacitors. Reduce their energy storage further so they charge/discharge very quickly but only hold a few shots worth of power. As @ubertpendragon mentioned you COULD put a battery in front of them as an optimization, but that is up to the sub designers. It would also mean that if the battery breaks then the guns stop working VERY quickly. 

On a related note, the battery efficiency seems too high, and supercaps seem too low. I think that batteries could be reduced down to %90 efficiency, and supercaps should he higher but hold like 5kw/min or a bit less.

If stacking batteries in front of spiky loads is really something that wants to be discouraged, then add an overload like mechanic to batteries to make them take damage if the output voltage drops too low.

**Comment by Tsunder** [comment]
> can easily cripple the sub's power grid.

On the flip side, there is no practical need to set a supercap to 100% recharge now. 40% - 70% will suffice.

The equivalent of the previous 100% recharge (20kw/min), which is ~40%-50% load now, which is only 160 - 250kw, which barely matters. And a single 20kw/min recharge is far less than a coilgun (or other guns) use the energy. 

Even 70% recharge (490 kw load, 49 effective recharge, the same as 2.5 supercaps previously, only needed to sustain fire on like 3-4 guns at once... this very rarely happens and doesn't last for long) barely matters, because subs come with backup batteries and the engines/pumps aren't necessarily running at 100%. And if they are, then the deltas of 500kw recharge are minor for 3000-5000kw reactors. It's only at brownout levels where undervolting truly has effect.

Practically, one only needs enough to sustain continuous fire - or near continuous fire, or just a very slow depletion rate (due to  guns targets not having infinite health/infinite things to shoot). For coilguns this is achieved at around 36 kw/min recharge IIRC (math) (and other guns are less notable, pulse laser is lower energy/time). 36kw/min is 360kw to the load. A negligible hit.

Numbers apply for all vanilla subs. (excepting i think the herja and winterhalter? Which have 0.05 efficiency. still, 720kw is negligible for their 5k / 10k reactors)



Another perspective take I suppose is:

The max effective recharge rate of supercaps was increased 5x from 20 to 100 while guns power consumption stayed the same.

**Comment by Rokvach** [comment]
No issues, closing.
