### ISSUE TITLE
Non-full crew spawns in test mode

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8504]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Only 3 of 6 jobs spawn in test mode

notably: security and medic often have permissions set for their spawn points 

and assistant is a good sandbag

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
This isn't a bug: the test mode spawns the same initial crew that you'd get in a campaign. Additional characters spawned with console commands should now get the permissions from the spawnpoint they spawn at: https://github.com/Regalis11/Barotrauma/issues/8335
