### ISSUE TITLE
reactor only creates fire once after crossing fire time

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8509]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Reactor will only generate fire once after entering fire time.

After that, it is "safe" (in the sense that there will be no further fires) to continue to use in the fire temperature zone

**Steps To Reproduce**
1. turn reactor up to fire heat (, about 7000), maintain this heat
2. wait for fire
3. extinguish fire
5. no further fires despite reactor still being at same heat

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
trolololol

**Comment by Lithosagym** [comment]
Tested, the reactor is able to start multiple fires while above fire threshold, issue appears to be fixed.

**Comment by Rokvach** [comment]
Closing.
