### ISSUE TITLE
Kastrull hardpoint location too close to docking port

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8512]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you buy a new turret for the Kastrul, it'll be on top of whatever you dock in the bottom-left docking port

![image](https://user-images.githubusercontent.com/73229309/158032422-16b9c00e-6c44-4d90-b074-bc0408cc3c08.png)
![image](https://user-images.githubusercontent.com/73229309/158032525-bb404985-8ef1-4c01-842e-bbff8de86776.png)

Move it to the tail where this isn't a problem
![image](https://user-images.githubusercontent.com/73229309/158032558-92ebfdf7-975b-4b50-94d7-c4b50a0f601f.png)

**Comment by danielasteljoki** [comment]
Fixed in 1cb68f8
