### ISSUE TITLE
turret sprite layering sometimes incorect?

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8515]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Railgun and possibly others sometimes has incorrect sprite depthing? where the turret/barrel part shows on top of the base

might be spectator only?

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.16.6 

**Additional information**
on a modified humpback (humpback B from [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2756660345))
![image](https://user-images.githubusercontent.com/5103517/158038119-662c18ee-c008-4dd6-b2b9-cfffa483ce4c.png)
![image](https://user-images.githubusercontent.com/5103517/158038181-3029b2a1-b536-4bd3-a3ee-b8660183f225.png)

**Comment by Regalis11** [comment]
I unfortunately couldn't find a way to repro this. Tested with that same sub, starting a couple of rounds, and with spectators and players controlling a character.

**Comment by Tsunder** [comment]
sadly, I have no known way to reproduce this either, reliably or otherwise.

the only additional context I have is that the lobby was hosted on a dedicated server, running for 2+ hours, full/nearly full 16 player lobby, 10+ rounds completed. I was on windows 10 and had OBS recording at the time

**Comment by Regalis11** [comment]
No known steps to repro, closing
