### ISSUE TITLE
Text display margin does not scale properly.

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#8516]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you scale a text display, reguardless of the text scale it lets less characters be displayed. 

**Steps To Reproduce**
Reduce scale of text display from default 0.5 to 0.2. Will only show "A..." if you type in 'Air', reguardless what you set text scale to. 
0.3 only shows 'Air...' if you attempt to display "Air123" despite both taking up the same amount of space. 

**Expected behavior** 

When you reduce 'text scale', it would let you display more characters at once, letting you make smaller labels. 

**Version**
Windows, Latest version as of 12/03/2022

**Comment by Ek-Videogames** [comment]
The text margins don't seem to scale correctly, which is why it gets cut off graphically where it seemingly shouldn't.
- only issue is that fixing it would break all formatting now that is accustomed to the offset.

**Comment by Regalis11** [comment]
The padding did seem to get scaled, the issue was the text scale wasn't being taken into account when truncating the text. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd9d5ed007e18cb07ab4f562ef9c7f6850a3901f

**Comment by BlackMoons** [comment]
Thank you very much for the fix!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
