### ISSUE TITLE
Helm skill does not boost engines if not directly connected to engine.

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#8517]
Helm skill does not boost engine output (Horizontal speed) if there is any logic between the helm unit and the engine.

**Comment by Regalis11** [comment]
Thank you for the report! Which game version did this happen in, and which components did you try specifically? I couldn't reproduce this with relays in v0.17.0.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/268072f4b4ceb97d07ea81acb7ec455e77a3aae9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
