### ISSUE TITLE
Crash after using the "dumpeventtexts" command with no parameters

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8518]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes to desktop after the `dumpeventtexts` command is used without any parameters.

**Steps To Reproduce**
1. Load Barotrauma.
2. Use the `dumpeventtexts` command without any extra parameters.

**Version**
Windows v0.16.7.0

**Additional information**
Crash Report: [crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/8240146/crashreport.3.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6264aed18cb4290c78fd15bd7cb10f8d34cb679

**Comment by Lithosagym** [comment]
Tested, command `dumpeventtexts` without parameters no longer crashes to desktop and instead gives an error message, issue appears to be fixed.

**Comment by Rokvach** [comment]
Closing.
