### ISSUE TITLE
[DEV] Active sonar pulses are too synchronous, yet not well synced

### ISSUE THREAD

**Issue by JJRcop** [Regalis11/Barotrauma#852]
Related to #851 and ab59e36bd86188ff43e091ea2e4387257b21fa71, zooming in or out with the sonar screen will affect what the ongoing sonar pulse returns back, so you can effectively hold it from going any further by zooming in all the way quickly. I haven't tested how monsters react to this. On top of this, turning active sonar off will stop the ongoing pulse and remember its `pingState` var. The next time you turn on active sonar, the pulse will continue from before and `pingState` will not be reset.

Sonar pulses are also not very well synced between clients. Flipping Active Sonar on and off rapidly will cause the `pingState` to drift between clients, each one maintaining their own sonar loop and not receiving timings from the server. Because of this, the type of ping is only decided by the client, and may not match what the server's ping type is. I have intentionally caused drift between two clients by a half a second and managed to cause one client to show a directional pulse while the other shows a non-directional pulse. This makes me wonder how much the clients have drifted not only from each other, but from the server.

If you could figure out your drift from the server's `pingState`, you could keep timing it so that you switch the ping type from directional to non-directional just after the server has started its ping and just before you start yours, so that the server doesn't alert any of the creatures, but you see a non-directional ping. Get in a good rhythm and you side step the downsides of sonar, as long as you maintain a safe sonar direction for the server, which will be easier because you know where the monsters are already.

**Comment by JJRcop** [comment]
I couldn't resist the word play

**Comment by JJRcop** [comment]
Still confirmed on v0.8.9.6

I think the main issue is, sonar console only have one master 'ping', with internal vars storing the characteristics and properties of the one and only ping. This would likely be fixed if the sonar was rewritten to spawn 'ping' data structures it stores in a list, and to loop over the list until it's empty when all current pings are done, even if active sonar is turned off. Ideally there will only be one sonar ping in this list, because the sonar would wait until the list is empty before spawning another one, but if there end up being two or more somehow it will process all of them and still work. The ping spawning event should be done by the server, the clients shouldn't spawn pings until the server tells them.

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
