### ISSUE TITLE
Smoke detector doesn't detect a nearby fire.

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#8523]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Even when there are medium-sizes fires near a smoke detector, at times these are not detected by the smoke detector.  For example, the smoke detector here (located in the upper left; the item immediately above the fire is an O2 detector) does not detect the medium-sized fire in the same hull, despite not being far away:
![fire that is not detected](https://cdn.discordapp.com/attachments/427654262453960724/952907949091721266/where_theres_fire_theres_no_smoke.webp)

**Steps To Reproduce**
Create a small room (e.g. roughly the same size as in the screenshot above) and put a smoke detector wired directly to a light component so you can tell if it's detecting a fire.  Light a fire in the room using either a flamer or the `fire` console command, and see how large/long the fire can burn before it's finally detected.

**Version**
v0.16.7.0 Linux

**Additional information**
I looked at issue #2792 but that appears to have been 'fixed' quite some time ago so I don't think it's related.

I'm not sure if this behavior is intentional or not, but it would be nice if they would at least detect fire in the hull they're in and linked hulls.

It's frustrating mostly when trying to disable the O2 generator when there's a fire, so as to starve it of oxygen, only to have the O2 generator start back up as the fire is finally dying down (but not out).  There are some workarounds that can be done (e.g. an 'or' component with a reasonable time frame set), but this seems like it shouldn't be necessary.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f0833c59d73bfd97bda3641a47601ea25d439f36

The detectors would previously only trigger if they're within double the damage range of the fire, and in the case of small fires, the damage range can be very short. Addressed that by always clamping the range above 500 px.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
