### ISSUE TITLE
Attribute "controlhusk" doesn't work

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#8526]
Find `AfflictionHusk.cs` file.
`Entity.Spawner.AddToRemoveQueue(character)` has been called before calling `SetClientCharacter(client, husk)`, which causes it can't match the specific client. So this bug is not fixed in #8153 

**Version**
0.16.7.0

**Comment by Regalis11** [comment]
Thank you for the report! I reopened the previous ticket.
