### ISSUE TITLE
Disguises don't work in multiplayer

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8527]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever you hide your face in multiplayer, the character portrait disappears regardless if you have an ID card or not.

**Steps To Reproduce**
1. Start a multiplayer round
2. Equip a diving suit

**Version**
v0.17.0.0

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/634d7631c10c6d460c5c2a83cbbd569339406f1f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
