### ISSUE TITLE
Placing a full oxygen tank on a diving suit which already has a oxygen tank causes the oxygen tank from the suit to drop

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8529]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4f16bf95-0406-474d-93aa-c70d35877977)

**Steps To Reproduce**
Start a multiplayer campaign, navigate to the submarine once you load in, equip some oxygen tanks and try and switch the tank in any of the diving suits located on the diving suit lockers by dragging and dropping it in, wait for a moment and notice that a oxygen tank drops to the ground

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/dba766422360b314614f5d7c7307c8d0a8d27e9e

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/34baa6be8990b657e1ffcde1866d5c64ef824e42

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
