### ISSUE TITLE
Doors don't work as solid objects when they are outside of hulls

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#853]
I wanted to make something similar to garage doors for a shuttle, so small creatures like crawlers wouldn't get inside and get stuck between the sub and the shuttle.
But it appears that creatures and shuttles don't have collision with doors(and probably hatches too) when they are outside of hulls.
![wilson-pc-2018-oct-18-002](https://user-images.githubusercontent.com/38168249/47133500-32fa5880-d2d3-11e8-9371-943373c367b4.jpg)
![wilson-pc-2018-oct-18-003](https://user-images.githubusercontent.com/38168249/47133501-3392ef00-d2d3-11e8-8989-f236d2f05c80.jpg)

**Comment by Regalis11** [comment]
Digging this up from the icebox because we need it for https://github.com/Regalis11/Barotrauma-development/tree/feature/endgame-prototyping

**Comment by NilanthAnimosus** [comment]
Tested against WIP branch commit https://github.com/Regalis11/Barotrauma-development/commit/baf018697b7ccb429b18b29b5f63c2f7d0be0603

They appear to act as solid objects fine now (for both other submarines/shuttles/ruins etc), but the code for not closing on a submarine doesn't appear to function correctly. it still closed on a remora drone I was using with the door as part of an edited remora sticking out as a sort of box. something seems odd with the logic to determine if the rects overlap for large doors and submarines.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8770d887fcd4a7987f3dd5e66198290d9bf116fb

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
