### ISSUE TITLE
[Modding refactor] If you have published two mods with the same name you aren't able to access one of them through the publish tab anymore

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8534]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Having two mods with the same name locks you out from editing one of the mods as it just keeps asking you to create a local copy of the mod and pressing yes on the prompt doesn't do anything. 

**Steps To Reproduce**
Have two mods with same name published and try and edit one of them

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/dc7d874972c5c5f2d465a3c3d098c80ddf7bc56e

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d3229056-755e-4bb0-a95a-a86414122346)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bf56ed58-8829-4055-b1b5-46ea59444ef1)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/d00af99ee45cb7f601c4d87728ba4680daa5cf85

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
