### ISSUE TITLE
You get prompted twice about a server crash

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8536]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a server crashes the prompt telling you that it crashes is shown twice

**Steps To Reproduce**
Crash a server and notice that you need to close the prompt twice

**Version**
Unstable 0.17.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/134c1b1008833e024a37f8f3f59d56824f59bf06

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
