### ISSUE TITLE
you lose money by selling from the submarine in singleplayer

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8537]
- [y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
https://user-images.githubusercontent.com/55637865/158694947-fd6dbf3d-b52b-4415-b1ca-038b322b85df.mp4

**Version**
v0.17.1.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f92b3fe022cd7cd971a0223183c00db1279094f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
