### ISSUE TITLE
immediate console error when docking to outpost in singleplayer

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8538]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/158696481-ffd8ea40-acac-447b-af79-9ff338e5e498.png)
the error pops out again instantly as long as you are docked, closing it will make it just reappear again, and it's impossible to undock, spamming the close console button won't allow you to enter the outpost either so it's impossible to enter an outpost

**Version**
v0.17.1

also apparently every time you try to close the console with this error you get the mission rewards again
![image](https://user-images.githubusercontent.com/55637865/158697114-f94c1ac9-3a7c-44dd-a38b-95868ff15c12.png)
and it breaks the escape menu so i can't leave without alt-f4-ing

**Comment by mrjpjr** [comment]
same issue. 
yep. seems all mission rewards are given again when you try to close the console (all my new shiny medals)
![wallet error mission rewards](https://user-images.githubusercontent.com/58775950/158727235-05a483ec-d033-4a8c-b9c0-704af9983c99.jpg)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d9afb71a9da57736a2c3f43b9fa8bf2f71df7ea7

**Comment by Rokvach** [comment]
Tested,  working correctly. Closing.
