### ISSUE TITLE
Servers show up as incompatible in the server browser

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8542]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/7066fdaf-2c7e-4db9-b1b8-7ca7158ade4e)

**Steps To Reproduce**
Host a server, open the server browser I suppose, haven't tested this myself.

**Version**
v0.17.1.0

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/cb08fd82c6b8968b6aed7df7ceae69a450c7a8f5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
