### ISSUE TITLE
Clients fail to determine who's controlling a character in some situations

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8544]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Switching control between characters seems to make clients confused about who's controlling who. I encountered this myself after using console commands to take control of a monster, but this could also be related to the issue we faced during an internal playtest session (@jallu becoming unable to control his character).

**Steps To Reproduce**
1. Spawn a monster
2. Take control of that monster with the `control` command
3. `Freecam`
4. The monster should appear motionless at your end (could be that the client still thinks they're controlling the monster locally?), but move server-side (making holes in the sub and whatnot)

**Version**
v0.17.2.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5007c78076295b42f492ec0f21a8637fec3e957e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
