### ISSUE TITLE
Doors cannot be forced open with Crowbar if it receives a 0 SET_STATE signal

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8546]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If doors receive a 0 signal (closed) on SET_STATE and are opened with a crowbar, they shut close immediately.

This prevents forcing doors open with a crowbar. 
Crowbars should override SET_STATE momentarily?

**Comment by Regalis11** [comment]
> I always considered this a feature that makes door "locking" possible

I would say so too, closing
