### ISSUE TITLE
[Unstable 0.17.2.0] Used oxygen tanks shows as full in the next round on multiplayer campaign

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8547]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b4b81aa9b03f7ac5fe824cf6ee90e9a6366f27cf

**Comment by mrjpjr** [comment]
It isn't just O2 tanks. I also observed welding fuel tanks and partially used minerals IN MY INVENTORY are full when the next round begins

**Comment by Regalis11** [comment]
Yep, the issue affects all items in characters' inventories.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
