### ISSUE TITLE
[Crew Wallets] Salary % doesn't update properly in multiplayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8549]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you adjust the salary % the % value doesn't change so you have to re-open the tab menu for the value to update

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ef740f13-18e1-471d-bfb2-cf1ee8f03c7f)

**Steps To Reproduce**
Play on multiplayer with other players and try adjusting the salary

**Version**
Unstable 0.17.2.0

**Comment by 3e849f2e5c** [comment]
Should be fixed after the changes in https://github.com/Regalis11/Barotrauma-development/commit/36d9aa5142b41df353bddf9a72c7e4068e3238c6

at least wasn't able to repro

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
