### ISSUE TITLE
Losing artifact using the transport case

### ISSUE THREAD

**Issue by subarotrauma** [Regalis11/Barotrauma#8550]
- Issue stated previously in https://github.com/Regalis11/Barotrauma/issues/7990

**Description**
In multiplayer I've always lost the artifact in transport case if I die inside ruins and respawn mid-round.

**Steps To Reproduce**
1. Start a salvage artifact mission in multiplayer
2. Go to ruins
3.  Get the artifact and put it in the transport case
4. Die inside the ruins
5. Respawn mid-round so your previous body will be lost
6. Transport case did not drop but disappeared with its contents

**Version**
Windows. v0.16.7.0

**Comment by Regalis11** [comment]
Reopened the previous ticket, I'll close this on as a duplicate
