### ISSUE TITLE
Characters default to the same appearance when entering a server

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8551]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you enter a server, you character's appearance is always the same: 1st face with no hair, face attachments and colors set to black.

**Steps To Reproduce**
Enter a server

**Version**
v0.17.x.x

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
