### ISSUE TITLE
Text scale setting does nothing

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8552]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Text scale setting doesn't change text scale

**Version**
v0.17.x.x

**Comment by mrjpjr** [comment]
could this be the possible reason why this happened?

![text overlap_mission status](https://user-images.githubusercontent.com/58775950/159368604-8ced2e28-4272-408e-9e3b-9d0b2e58b20e.jpg)

**Comment by juanjp600** [comment]
Text scale slider should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/69bb0e1b942f6987940abe73f137d75f4848888c.

> could this be the possible reason why this happened?
@mrjpjr This might be related, but ultimately it looks like a separate issue. Could you write a separate ticket about it?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
