### ISSUE TITLE
bots cant repair leaks on the ceiling in dry spaces

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8555]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the easiest place i was able to repro this is in humpback's medbay, drill a hole in the ceiling of it and bots stand below it with welding tools in their hands not fixing it

**Version**
v0.17.2

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@6417feb.

**Comment by Rokvach** [comment]
I haven't noticed any issues, seems to be fixed. Closing.
