### ISSUE TITLE
mudraptor veterans not as aggressive [unstable]

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8556]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
it feels like mudraptor veterans are way less aggressive than normal mudraptors, completed many  "Getting Rid of Mudraptors" missions and the normal ones always attack first, the veterans only attack when really close or when provoked

**Version**
v0.17.2

**Comment by mrjpjr** [comment]
yes, I have the same experience.
I mudraptors charge to attack while the veterans (casually) swim away from the sub. They only attack if close and/or are attacked. In a few cases, I have killed them (with pulse laser at distance) and they never attacked.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@3033ca7. The issue was only in the Unstable.

**Comment by LePiromano** [comment]
the fix works

**Comment by Rokvach** [comment]
Closing.
