### ISSUE TITLE
Cargos and other mission items stocked in containers that is outside a hull cannot be correctly settled after a cruise

### ISSUE THREAD

**Issue by Aeolina** [Regalis11/Barotrauma#8557]
**Description**
I'm a modder who just uploaded a pack of underwater motorbikes in the workshops(which was fortunate enough to sit on the first page for more than half a week) and I happen to find some issue when playing my own product(I'm going to put a link of it down there. As you can see, all the hull I used, except a ballast, only serves one function -- to keep crews in a flooded hull so that he or she won't be throw out of the bike ). Although in one cruise I thought I sucessfully completed a cargo transport mission and a wreck salvage mission, as crates stay safely in the crate shelf and log in a secured cabinet, it reported a failure. The only reason I could image is that for the best game experience, my hull arrangement didn't cover these containers.

**Steps To Reproduce**
 I took 4 missions: cargo transport for jesters, wreck salvage, mining titanium and terminate a crawler swarm. 
The last one was sucessful as I killed all of them
And I just abandoned mining mission because I simply failed to find a way into the cave. 
I didn't touch any of the cargo crates so I suppose they are quite safe, and the wreck log I retrived was in a secured cabinet when I docked on the destination post. 
However, after docking, the game told me I failed the these missions, leaving me astonished.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
0.16.7.0, on Windows
**Additional information**
The ship I used: Kettenkrad_brown (Sd.Anh.1) from [https://steamcommunity.com/sharedfiles/filedetails/?id=2777537094&searchtext=](url)
![image](https://user-images.githubusercontent.com/101935648/159125802-dc36166c-c86c-45d3-b563-07754f2c3d47.png)
I do hope this is a bug and should be fixed. A restriction like this would be devastating for creativity. Surely you can and should not only play submarine in Barotrauma.

**Comment by Aeolina** [comment]
plus: cargo drone I used

![image](https://user-images.githubusercontent.com/101935648/159125910-fad77b37-f645-428a-99ed-ebfa63e20c2c.png)

**Comment by Regalis11** [comment]
Thank you for the report! 

The cargo missions required the items to be inside one of the submarine's hulls: I changed this in https://github.com/Regalis11/Barotrauma-development/commit/f83df1835c8b0a94819e49bfc278cf9225358eab so that being in the sub is enough.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
