### ISSUE TITLE
grenade launcher pirate elites are more common than intended due to a typo?

### ISSUE THREAD

**Issue by GenericGoose** [Regalis11/Barotrauma#8559]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Searching through stuff I found a typo  on line 944 of OutpostGenerationNpcs.xml, spelling commonness = "0.3" as ommonness = "0.3". This seems to cause the parameter to be invalid and uses some default number instead, which makes grenade launcher pirates more common than the other variant at times. Fixing the typo made 1-2 spawn instead of 2-4 in the tests I ran.
**Steps To Reproduce**
100% difficulty pirate mission, enablecheats, lighting, freecam. Check the number of pirates with grenadelaunchers.
**Version**
Windows 10 Rising Tide update.
**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d099043c4c6f80b37303a3876fdf6aaecbc0c6b4

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
