### ISSUE TITLE
Artifact might have been spawned below safe depth

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#856]
Happened in multiplayer. The artifact spawned about 2200-2400m deep.
 I know that the critical depth varies, but it seems like in this seed it was enough to get near the artifact for the sub to start getting its hull broken.

 The only info i have is the map seed (drruykDI) and this screenshot:
![wilson-pc-2018-oct-18-013](https://user-images.githubusercontent.com/38168249/47166865-52bb6c00-d327-11e8-8992-18485a49573f.jpg)

 I am not 100% sure if it was actually caused by depth, because the left side of the sub has almost no scratches. Plus, anything can happen in multiplayer, it's pretty hard to control what's going on(somebody could have just used explosives).
 But judging by the background and color of the rock it seems very likely. Hopefully the map seed is enough to find that out. Otherwise this can be closed due to lack of proof and information.

**Comment by BillCombs** [comment]
Nevermind, it appears that map seed changes at the end of the round, so i actually got the wrong one, because i took it after the round ended. Since i don't have the correct one, there is probably no point in having this issue open since it has nothing useful to know except for the fact that the artifacts might spawn too deep sometimes.

**Comment by Rokvach** [comment]
This shouldn't be an issue anymore, closing.
