### ISSUE TITLE
[Modding refactor] Updating a mod gets stuck on the "Installing..." process

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8561]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to update a mod always gets stuck on the installing part of the process and doesn't allow closing the prompt, so forces you to restart the game. The mod seems to correctly update however. 

**Steps To Reproduce**
Publish a mod and then do some edits to the mod and hit the publish item button again to try and update it

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/b0c70f9e290a08dc409199b6b3b2774ca31c1853

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6d052932-ba16-4e13-b045-848fe1cb23dc)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/2fdae51db46c3fab00b9bb08156a42383a762a1a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
