### ISSUE TITLE
[Modding refactor?] trying to create an ItemAssembly in the sub editor crashes the game

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#8562]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes if you try to create an ItemAssembly. Seems to be related to the Modding Refactor as the error is about saving the assembly to a path in the LocalMods folder rather than the ItemAssemblies folder previously used.

**Steps To Reproduce**
select some nice things. Try to create an assembly out of it. I did this on the "Unnamed" default sub, that might be related.

**Version**
Game version 0.17.2.0 (UnstableWindows, branch dev, revision 0746913a00)

**Additional information**
Crash log
[crashreport (144).log](https://github.com/Regalis11/Barotrauma/files/8316566/crashreport.144.log)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a805259f61776a023853a2e9c106f2a76b0ddb0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
