### ISSUE TITLE
[Unstable 17.2] - Tutorial - Selecting Engineer Training opens the Medical Doctor training mission

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#8567]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Selecting the Engineer Training tutorial mission opens the Medical Doctor training tutorial mission

**Steps To Reproduce**
- In main menu select "Training"
- Complete the Captain and Medical Doctor training
- Click on Engineer Training

**Result:** The Medical Doctor Training tutorial mission will start
 

**Version**
Unstable 17.2.0 
Windows

**Comment by Regalis11** [comment]
Note for testing: modding-refactor included quite a lot of changes to the tutorial classes, we should retest all the tutorials (+ make sure all the videos are still working).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/50ff3e0c256018931f1b97cc44af8b07bf70c760

**Comment by Rokvach** [comment]
Tested, didn't find any issues relating to this, working correctly. Closing.
