### ISSUE TITLE
Docking port ApplyEffectsOnDocking can't be changed in the editor

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#8568]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Docking Port recently got the ApplyEffectsOnDocking attribute, but it can't be changed in the editor. This is inconvenient as you now have to make a mod just to be able to disable the effect for what would otherwise be vanilla contraptions. Is this intentional?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b8f53c52dc9ef5396a45c4b70de6779ea711f790

**Comment by Rokvach** [comment]
Confirmed working correctly, closing.
