### ISSUE TITLE
outposts have no oxygen

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8573]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
seems like the outpost runs out of oxygen real quick and it doesn't restore

**Version**
v0.17.3

**Comment by ubertpendragon** [comment]
Outposts have no vents in any of their rooms

**Comment by danielasteljoki** [comment]
Fixed in 1bb53e1

**Comment by Rokvach** [comment]
There's no vents in these storage rooms
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ea8daf6a-bb22-4681-85a5-80a52a87121b)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
