### ISSUE TITLE
error when showing talent stat boosts

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8574]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
this happens on a few talents with stat boosts
![image](https://user-images.githubusercontent.com/55637865/159559298-4f7a773e-848e-4fe6-a25b-12e7aec0572d.png)

**Version**
v0.17.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e41ca345bcc5dd67f6eb27620985053a6f26727

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
