### ISSUE TITLE
NEW OUTPOST ISSUES

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8575]
**Description**
Post various smaller issues regarding new outposts

- [x] NPC stuck walking into a wall here
![image](https://user-images.githubusercontent.com/59519434/159570414-51280e87-5186-44d0-9402-034091d97ffa.png)

- [x] Pickable fiber plant through a glass window
![image](https://user-images.githubusercontent.com/59519434/159571855-ab7f51c0-c06e-4be3-bab2-73076206c7d5.png)

- [x] Bad background wall border
![image](https://user-images.githubusercontent.com/59519434/159571500-bb5a5a28-9656-4ebb-a642-9d5874405be9.png)

- [x] floating table
![image](https://user-images.githubusercontent.com/59519434/159571570-c0255ca7-f402-4b5e-84e6-031c10e6dc50.png)

- [x] This chair is sittable
![image](https://user-images.githubusercontent.com/59519434/159571606-c2bdbd29-c24e-4875-9a36-c79b7585c379.png)

- [x] Missing gap
![image](https://user-images.githubusercontent.com/59519434/159574933-2f9566cb-36c8-4fe7-9889-1808633f7fed.png)

- [x] bad mega-gap (should be 3)
![image](https://user-images.githubusercontent.com/59519434/159574994-0603f4c0-080a-4143-9598-3f1a7e3cca73.png)

- [x] same
![image](https://user-images.githubusercontent.com/59519434/159575103-f5cf1cea-bae2-4267-aaa4-02cf14873080.png)

- [x] no ambient light on this hull
![image](https://user-images.githubusercontent.com/59519434/159575134-f0f4a63e-88b0-4afa-ab10-5804a419990f.png)

- [x] these lamps are shadow-casting for no reason
![image](https://user-images.githubusercontent.com/59519434/159575220-8fc80170-bef2-4ccd-a647-8caf76708d4c.png)

- [x] wrong sprite depth
![image](https://user-images.githubusercontent.com/59519434/159802415-f4c85400-fa57-48b2-97c0-0bcaec62183c.png)

- [x] unreachable door
![image](https://user-images.githubusercontent.com/59519434/159802442-db2c4e5c-fcc5-4f56-ae04-9f3a2cf10223.png)

- [x] unlit room
![image](https://user-images.githubusercontent.com/59519434/159802876-d9e94411-124d-4567-bfad-fb1e32d6a481.png)

- [x] can't get past these stairs
![image](https://user-images.githubusercontent.com/59519434/159804100-afff04c0-123a-4a5c-bce2-216066c374f4.png)

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/159570612-2611d097-ee90-4021-bbcb-dc20799e03e1.png)
Pickable fiber plant through a glass window

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/159570765-7fded36b-7661-44bb-9b23-5676f7ebef68.png)
Bad background wall border

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/159570978-cf03b0ed-e74e-4431-8847-42114810acd7.png)
floating table

**Comment by Udrakan** [comment]
![image](https://user-images.githubusercontent.com/59519434/159571241-e7b02e04-9181-45d5-a86f-10627d600eeb.png)
This chair is sittable

**Comment by itchyOwl** [comment]
The issue with NPCs is probably due to changes in the navigation logic. I'll have to revisit the stair waypoints (and fix the generator).

**Comment by danielasteljoki** [comment]
Fixed in 1bb53e1

**Comment by Regalis11** [comment]
Waypoint issue in one of the modules:
![image](https://user-images.githubusercontent.com/14351070/160383264-5eb3c05b-800d-4e30-a2b1-65534ac89f70.png)

**Comment by Regalis11** [comment]
- [ ] There should be a normal floor in these spots instead of a platform. These can cause you to fall down if you press the down key a bit too soon to get on the stairs.
![image](https://user-images.githubusercontent.com/14351070/160403722-58945ea7-8ec8-414b-9657-ee1c13a47a79.png)
- [ ] These stairs start from inside the floor, which makes it difficult for characters to get on the stairs without falling/tumbling
![image](https://user-images.githubusercontent.com/14351070/160404043-c11f547c-da34-403a-b48a-65dcf079528e.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
