### ISSUE TITLE
[Unstable] Group names not appearing

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8579]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Group names appear invisible on the "Send selection to group..." dropdown in the sub editor right-click context menu.

**Steps To Reproduce**
1. Open sub editor
2. Make a new group with any name
3. Place an item down
4. Right-click on the placed item, and navigate to "Send selection to group..."

**Version**
Windows Unstable v0.17.3.0

**Additional information**
![image](https://user-images.githubusercontent.com/67431770/159603652-c11332ae-bb73-4c3a-81f6-f0db7ea98f11.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/08ed02e2cd82cb7cbf1020ec5ce6a94974e2699d

**Comment by Rokvach** [comment]
Tested, working correctly.  Closing.
