### ISSUE TITLE
[Unstable] Weird sitting animation for the new Office Chair

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8580]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The character sits weirdly on the new Office Chair.

**Steps To Reproduce**
1. Find the new office chair
2. Sit in the new office chair

**Version**
Windows Unstable v0.17.3.0

**Additional information**
![image](https://user-images.githubusercontent.com/67431770/159605251-a78b3dc0-2c01-4c07-a540-8725595e310c.png)

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@ec96ae2. I think all the sitting animations would require a bit of tweaking, but currently iterating on it is too tedious because the limb positions don't seem to be saved. So, need to fix that first and then do another tweaking pass.

**Comment by Regalis11** [comment]
Not an ideal solution, but I've previously adjusted them from the code with the help of Edit & Continue so there's no need to restart or reload the xml every time.

**Comment by itchyOwl** [comment]
Controller limb positions can now be adjusted and saved in the editor: Regalis11/Barotrauma-development@cdcbf28.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
