### ISSUE TITLE
[Unstable] Drop shadow is forced on for walls

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8581]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After testing a sub and returning to the editor, drop shadow is re-enabled.

**Steps To Reproduce**
1. Build a room in the sub editor
2. Test the submarine (drop shadow will be visible by this point)
3. Return to the editor screen

**Version**
Windows Unstable v0.17.3.0

**Additional information**
In editor before testing:
![image](https://user-images.githubusercontent.com/67431770/159605335-2c3e70f5-2355-4089-b36f-b27a44855eff.png)

In editor after testing:
![image](https://user-images.githubusercontent.com/67431770/159605419-cd59cc0d-f96b-4c7b-9ee8-ed6dac7c84a3.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e6454935869f9dd7f8828e3c62cb478b8369b0d4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
