### ISSUE TITLE
[Unstable 17.3] targetcontaineditem doesn't work if set comparison as and

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#8584]
- [x] I have searched the issue tracker to check if the issue has already been reported.
> Based on #8525 this is still not working correctly. I could no longer reproduce the issue though: I tested it by adding the following status effect to a flashlight:
> 
> ```
> <StatusEffect type="OnActive" targettype="This">
>   <Conditional condition="gt 80" targetcontaineditem="true"/>
>   <ParticleEmitter particle="spark" copyentityangle="true" anglemin="-10" anglemax="10" particleamount="5" velocitymin="-10" velocitymax="-200" scalemin="0.5" scalemax="1" />
> </StatusEffect>
> ```
> 
>This should make the item emit sparks when there's a battery with >80% charge in it, and it seems to be working correctly. @zhu-rengong would it be possible to send us the xml of the status effect you're having problems with?

This xml does work, but it won't work if you add `comparison="and"` to `StatusEffect`.
Until I found:
```
public static bool IsValid(XAttribute attribute)
{
    switch (attribute.Name.ToString().ToLowerInvariant())
    {
        case "targetitemcomponent":
        case "targetself":
        case "targetcontainer":
            return false;
        default:
            return true;
    }
}
```
`targetcontaineditem` will be considered as `PropertyValue` type, it should not be valid.

**Comment by Regalis11** [comment]
Thank you for the report!

Hopefully fixed for good in https://github.com/Regalis11/Barotrauma-development/commit/df99306a2e95610789521878e684be9de8e43c6f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
