### ISSUE TITLE
Server crashes if you take control of a bot who's been recently attacked by a diving knife

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8586]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was just attacking a bot with a diving knife and then controlling it and the server suddently crashed

**Steps To Reproduce**
1. Start a multiplayer campaign
2. Make sure you have some bots onboard your sub
3. Leave starting outpost
4. Spawn or find a diving knife
5. Attack nearest bot with diving knife
6. Take control of the bot you attacked, I waited while their health was around 50%
7. Just wait while controlling the bot and the server should crash eventually

**Version**
0.17.3.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/615d93642c4ed466abc2501df31526af077df7de

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c75fd423-18e8-4abe-8130-9652dc8d41fe)

```
Barotrauma Dedicated Server crash report (generated on 23.3.2022 11:28:18)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.17.3.0 (ReleaseWindows, branch dev, revision 615d93642c)
Language: English
Selected content packages: Vanilla
Level seed: St. MayVorta
Loaded submarine: Dugong (803ED8EC28713D1DE09B44360F7B801C)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: An item with the same key has already been added. Key: 7585 (System.ArgumentException)
Target site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Barotrauma.MultiPlayerCampaign.UpdateClientsToCheck(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 522
   at Barotrauma.MultiPlayerCampaign.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 474
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 705
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 141
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 327
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75


Last debug messages:
   23.3.2022 11:28:18 - [23.3.2022 11:28:18]
  Saving banlist
   23.3.2022 11:28:11 - [23.3.2022 11:28:11]
  Alton Cobble equipped Bandage
   23.3.2022 11:28:11 - [23.3.2022 11:28:11]
  Micheal Severance set the value "Channel" of the item "Headset" to "0".
   23.3.2022 11:28:10 - [23.3.2022 11:28:10]
  Console command "control "Micheal Severance"" executed by Rokvach.
   23.3.2022 11:28:08 - [23.3.2022 11:28:08]
  Alton Cobble: I need blood pack, saline, morphine or pomegrenade extract to treat Micheal Severance!
   23.3.2022 11:28:07 - [23.3.2022 11:28:07]
  Alton Cobble equipped Blood Pack
   23.3.2022 11:28:06 - [23.3.2022 11:28:06]
  Alton Cobble: Treating Micheal Severance in command room!
   23.3.2022 11:28:02 - [23.3.2022 11:28:02]
  Owen Lawson: I'm losing blood!
   23.3.2022 11:28:00 - [23.3.2022 11:28:00]
  Rokvach used Diving Knife on Micheal Severance.
   23.3.2022 11:28:00 - [23.3.2022 11:28:00]
  Micheal Severance attacked by Rokvach. Lacerations: 5 Bleeding: 7,5 Stun: 0,2
   23.3.2022 11:27:59 - [23.3.2022 11:27:59]
  Micheal Severance: Help, I'm bleeding!
   23.3.2022 11:27:57 - [23.3.2022 11:27:57]
  Rokvach used Diving Knife on Micheal Severance.
   23.3.2022 11:27:57 - [23.3.2022 11:27:57]
  Micheal Severance attacked by Rokvach. Lacerations: 4,5 Bleeding: 7,5 Stun: 0,2
   23.3.2022 11:27:51 - [23.3.2022 11:27:51]
  Alton Cobble equipped Bandage
```

**Comment by Regalis11** [comment]
I don't think the diving knife is related: this seems to happen because Mission.GetSalaryEligibleCrew returns the same character twice if a client takes control of a bot.

As I mentioned in https://github.com/Regalis11/Barotrauma-development/commit/fcc18d677ee4532a684a8fc96ab93e15a2cd81a7, I'd prefer to get rid of this method altogether and use one method for getting the crew.

> I think I'd prefer getting rid of this method and using the existing methods instead. We now have several different methods for getting the crew (GameSession.GetSessionCrewCharacters, CrewManager.GetCharacters and Mission.GetSalaryEliglibleCrew), each of which behaves slightly differently. Imo it'd be better to have one method with parameters for filtering out bots (if we need to do that), or at the very least comment these methods to explain the differences between them.

**Comment by 3e849f2e5c** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/e8e276c4bea50c02e9ed8f7ef9f1dfc5c5c5dcf2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
