### ISSUE TITLE
[Modding refactor] Finicky search functinality

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8587]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you search a mod on the mod list and then leave the mod list to check mods details the search filtering resets but not the actual search text, the same happens if you go to the publish tab and then return to the mod list.

I think the search filtering should persist maybe in both of those cases and only get cleared when closing the settings?

Additionally you can't just select the search field and then press enter to search again, instead you need to either add or a remove a character to do it.

**Steps To Reproduce**
Have some mods installed and try to search a specific one from the list, after searching press the details button on the mod and then return to the mod list from the details view. 

**Version**
0.17.3.0

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8e23d4ea-3128-45b5-b665-bec337639ca4)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ddadc7a6-59af-4a42-b67d-95196cd8b5ae)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/855c2e3d70e9df873812503f9d6711465bc6b8c2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
