### ISSUE TITLE
new abyss creature doesn't emmit the sonar warning

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8591]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the cool orange lines the charybdis and endworm do in the sonar don't appear when the new abyss thing detects you

**Version**
v0.17.3

**Comment by itchyOwl** [comment]
It's intentional. The new monster doesn't make the constant howling of Charybdis and Endworm and it does not circle around the sub like thos, so I'm not sure if we need or want to add the sonar effect either. What do you think?

**Comment by itchyOwl** [comment]
The intention was to make it stealthy. It's not lethal afterall unless you provoke it.
