### ISSUE TITLE
[Unstable] The editor doesn't see files saved in Localmods after relaunching the game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8594]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you save a sub, close and relaunch, you won't find your sub in the sub editor

**Steps To Reproduce**
1. Open Barsuk
2. Save it as "Save test"
3. Close and Relaunch
4. Open editor
5. Search for "save test", it doesn't appear on the list

**Version**
Unstable v0.17.3.0

![image](https://user-images.githubusercontent.com/73229309/159707210-659df76e-8a6f-428b-8cb5-206ece519497.png)
![image](https://user-images.githubusercontent.com/73229309/159707223-d21f8f81-7916-49d9-ae17-cbf102e76a54.png)

**Comment by ubertpendragon** [comment]
I assume you need to manually enable the mod in the settings menu to see your own sub after saving it

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0517043f8c59b020d220557185ad4c53f79278a8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
