### ISSUE TITLE
General list of Colony issues

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8595]
@Rokvach commented on [Mon Mar 21 2022](https://github.com/Regalis11/Barotrauma-development/issues/3201)

1. - [x] No oxygen generators/vents anywhere, stay long enough and everyone will die to oxygen loss

2. - [x] You can access the outpost reactor

3. - [x] Generating a military outpost always throws a error
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/80608259-b123-4ac4-91d3-879a80a173da)

4. - [ ] Hardly any cabinets and loot anywhere

5. - [x] Colony name isn't displayed correctly on the welcome display and the scrolling isn't smooth
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c39d8168-52de-4ba0-9977-61649783e856)

### Tested in seed `D938CCoj` on leveleditor

6. - [x] Z-fighting (flickering) in these plants
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9e8a6448-5a4f-4514-8ff5-007377e3e6df)

7. - [x] Same module, plants rendering over player
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bc2fade0-1a3a-4d76-b3ea-f45ed936180d)

8. - [x] Docking module plants rendering over player
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/7d5780e4-18b5-42d5-a30f-a369ce2b267f)

9. - [x] A lot of z-fighting in flowers
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/79495b59-1b43-4b7c-903a-df1bd5cfa05c)

10. - [x] Can't get up to this platform as the ladder doesn't extend high enough
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8d2509f0-14dc-457b-a93b-e1909cdf6b50)

11. - [x] Module connection issues
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6e880289-a8fb-44d1-95c4-2b53db40f39d)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/80f7da08-8603-40e4-897d-833b1df2c0ff)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5d8e3e85-289b-47ad-a279-f7ff03c16bf3)

12. - [x] Hidden platform so characters appear to be floating
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9a9886a2-fcfa-4564-9a96-f3fab0db8a49)

13. - [x] Intentionally super dark?
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4f3db2ea-82b3-4f68-bc14-1380ccf6f4cc)

14. - [x] Awkward poster placement
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fbe76598-dec1-47cd-add6-4a3faf22f0b3)

15. - [x] No way to get into these rooms, intentional? 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/aabb0108-e562-4d5f-a5de-abd8d96da90a)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6e37b63d-f52c-4b74-bc69-14de27571525)

### Tested in seed `lcHJTgNb` on leveleditor

16. - [x] Intentionally no lights?
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4934827f-d7ca-4405-a2bd-d4ed647ee594)

17. - [x] Z-fighting
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c22973fc-00c4-4a2a-83cf-bac5ef4d6a2c)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b36833b5-edc4-4945-b293-4c84a58c65f1)

18. - [x] Can't get through these stairs
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/303092e0-88a0-404b-bf7b-b29004c3d5b4)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9db2172f-31a1-4f54-8e8e-f79943a1a588)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ae36747c-ef8d-49e6-a5f2-b2684de2b70a)

19. - [x] Depth issues
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/30a99211-2b10-4c42-8c1a-f65db62ab932)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d64d9213-4d63-435f-b2bc-ff16e4fa38cd)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fe04302c-0b61-48bc-8e78-29f4c1d41bd7)

20. - [x] Module connection issue
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2208d9d3-3c6b-4f6e-bb32-b9c86ddda9a2)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d9263489-2df4-442d-8896-3cbdef184dd0)

---

@Regalis11 commented on [Tue Mar 22 2022](https://github.com/Regalis11/Barotrauma-development/issues/3201#issuecomment-1075225873)

- [x] Neon lights have hard-coded names:
![image](https://user-images.githubusercontent.com/14351070/159500232-3e491945-0de2-42b7-9593-f920fe601ff8.png)

**Comment by Udrakan** [comment]
1 other general issue are gaps - outpost doesn't flood properly and O2 would have issues as well when added.

**Comment by Rokvach** [comment]
- [ ] Hidden nav terminal in colonies can deteriorate
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/66394d90-f7b7-4d78-80dd-76286a955ee9)

**Comment by Rokvach** [comment]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c4e573be-42d7-43b5-83c6-ecf162b2ae12)

**Comment by Regalis11** [comment]
@Rokvach reported in https://github.com/Regalis11/Barotrauma/issues/8629

**Comment by danielasteljoki** [comment]
A lot of the visual issues were fixed by art team, finished the list in 1bb53e1

**Comment by ubertpendragon** [comment]
- [ ] Status monitor / Sonar monitor in ResearchModule_01 are not invulnerable to damage and will break

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
