### ISSUE TITLE
[Unstable] Selecting "Allow attaching" "Any" crashes the game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8597]
- [x] I have searched the issue tracker to check if the issue has already been reported.

![image](https://user-images.githubusercontent.com/73229309/159812838-d81f9750-d30c-41a1-ba14-803cc682ac48.png)

**Steps To Reproduce**
1. Open any outpost module in editor
2. Check "Allow attaching" "Any"

[crashreport (47).log](https://github.com/Regalis11/Barotrauma/files/8337267/crashreport.47.log)

If "Any" is already selected and you check another option, it will also crash

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/585d2ed09780d9ad46e89fce7abc2ac0444b2b8c and https://github.com/Regalis11/Barotrauma-development/commit/e8a6d31c1142080c369bf3a3b2ad25b842460577

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
