### ISSUE TITLE
you can buy terminals

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8601]
- [y] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image](https://user-images.githubusercontent.com/55637865/159829040-d2cb8bb0-8426-479c-a00b-9f9f5319a3d4.png)

**Version**
v0.17.3

**Comment by Regalis11** [comment]
This is intentional, does this cause some kind of issues or why do you consider this a bug?

**Comment by LePiromano** [comment]
> This is intentional, does this cause some kind of issues or why do you consider this a bug?

oh i didnt know It was intentional, my bad, closing
