### ISSUE TITLE
[Unstable 17.3.0] Outpost unpowered docking hatch

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#8605]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of the new outpost modules does not have a wire to the power pin of its docking hatch.

**Steps To Reproduce**
See images below for details 

**Version**
Unstable 17.3.0
Windows

**Additional information**
This is the outpost module in question:
![20220324104335_1](https://user-images.githubusercontent.com/58775950/159943204-e9ce50fb-4b11-4211-87ea-4d223602ca88.jpg)
Docking hatch wiring:
![outpost docking_no power](https://user-images.githubusercontent.com/58775950/159943445-9e9c048e-0333-4275-b608-d83023101307.jpg)

This is the only unpowered hatch I have come across thus far.

**Comment by danielasteljoki** [comment]
Fixed in 29226b8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
