### ISSUE TITLE
Money command's character argument doesn't work

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8607]
@Regalis11 commented on [Thu Mar 24 2022](https://github.com/Regalis11/Barotrauma-development/issues/3215)

- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Money command's character argument doesn't work, the money always goes to the bank.

**Steps To Reproduce**
Try to give money to a specific character in mp with the `money` command.

**Version**
v0.17.1.0 and later

**Comment by 3e849f2e5c** [comment]
I was unable to repro,

`money 500 "3e849f2e5c"` correctly sent to money to my characters personal wallet while `money 500` sends it to the bank

**Comment by Regalis11** [comment]
Hmm, I couldn't repro this now either. Not sure why I couldn't get it working earlier, maybe I didn't have the appropriate permissions or smth.

**Comment by Regalis11** [comment]
Found a way to repro this now: use the command in the server console instead of client-side. Giving money to specific characters is only implemented in AssignOnClientRequestExecute, not the "base" implementation of the command.

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a238825e88224748a2afa008fc46a57d99e45668

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
