### ISSUE TITLE
Submarine delivery fees don't work

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8608]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There's supposed to be a delivery fee when you try to switch to a sub you've left or purchased at another outpost. Looks like it has never actually worked as intended: the fee is calculated based on the distance to the closest outpost, which is always zero because the switching happens at an outpost. It also seems that DeliveryFeePerDistanceTravelled (1000 mk) only exists client-side, and the server uses the distance (number of steps to the outpost) as the fee directly.

Although, I'm not sure if this is even something we should fix. The fee doesn't really serve any gameplay purpose, IIRC it was mainly intended as an explanation for being able to switch to a sub that should logically be located somewhere else. I'd even say the fee is a bad thing from a gameplay perspective: we want to encourage submarine switching, not to make it even more cumbersome.

**Steps To Reproduce**
1. Purchase a sub
2. Travel to another outpost
3. Switch to the previously purchased sub

**Version**
Any

**Comment by JeroonBosch** [comment]
Unsure how to test this: as far as I can see it, you removed code that wasn't functional in the first place... so nothing actually changed?

**Comment by JeroonBosch** [comment]
Switch submarines still works (without any fee), so see no issues here - closing
