### ISSUE TITLE
Deep Sea Slayer ain't workin'

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8610]
- [yea] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The buff the deep sea slayer talent states it has  underwater doesn't seem to be doing anything

**Version**
v0.17.3

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c2c5c26cdeb16588b85a37d16604dd0a49e89ac6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
