### ISSUE TITLE
[Unstable 17.3.0] battery draws power whether relay is trun on or not.

### ISSUE THREAD

**Issue by war3scv** [Regalis11/Barotrauma#8612]
![20220325125651_1](https://user-images.githubusercontent.com/95470279/160058490-2bb7f39d-20cb-4737-aa6b-4abbb6d240fc.jpg)
![20220325125627_1](https://user-images.githubusercontent.com/95470279/160058524-d22a2e92-b817-42c7-a872-294ca6ccb0ab.jpg)
![20220325125631_1](https://user-images.githubusercontent.com/95470279/160058536-65df500f-4f42-49e7-ad55-b4e93350576d.jpg)
![20220325125657_1](https://user-images.githubusercontent.com/95470279/160058547-1e33ec20-0bac-4a42-bf9c-07883bb350a3.jpg)
![20220325125749_1](https://user-images.githubusercontent.com/95470279/160058549-223c1754-2e2f-4bef-a9cc-d0680a53eafb.jpg)

me again, this sub again:) bot still can't fire her weapons, and may I suggest buff that "Abyssmonster" somewhat? at least should pose the same level of threat of giant spineling to match its name.

[Submarines.zip](https://github.com/Regalis11/Barotrauma/files/8347644/Submarines.zip)

**Comment by Regalis11** [comment]
This seems to happen because the battery is connected directly to the grid (both plugged to the same power_out connection of the relay). 
![image](https://user-images.githubusercontent.com/14351070/160094822-2ef5b3ee-1ba2-4c97-b1c7-d8ee2a6f10dc.png)

The wires need to be connected at different sides of the relay (power_in and power_out) for the relay to break the circuit.

**Comment by war3scv** [comment]
that's weird..other people also say the same, and I didn't change anything on sub...let me check again

**Comment by war3scv** [comment]
![20220325220912_1](https://user-images.githubusercontent.com/95470279/160137209-65dbca1b-adf3-4153-ae64-3d1936ddb221.jpg)
![20220325220920_1](https://user-images.githubusercontent.com/95470279/160137224-8da4187f-342f-4a45-a3f9-2a3dee94
![20220325220938_1](https://user-images.githubusercontent.com/95470279/160137230-08e5b3d7-83f8-4284-b200-36b32a0f4012.jpg)
d05f.jpg)
![image](https://user-images.githubusercontent.com/95470279/160138050-32933cd3-ede1-4d5d-976b-233550d25c9f.png)

can you still see this? this barttery is not directly connected to the grid (previous screenshots was the relay's panel)

**Comment by Regalis11** [comment]
The problem is not the way the battery is wired, but the way the relays is wired.
![image](https://user-images.githubusercontent.com/14351070/160140349-0c0d185c-8689-42a6-a367-6f2150e4ef4e.png)

**Comment by war3scv** [comment]
oh you can still see this thanks god..I upload video then...

**Comment by war3scv** [comment]
https://user-images.githubusercontent.com/95470279/160144923-00821e73-9374-4fe2-8f1d-2cb76a5f8a08.mp4

https://user-images.githubusercontent.com/95470279/160144949-4fe72a32-5c27-40fa-895b-b9f69a095b35.mp4

forgive my horny mod:) 
yes it can be fix that way, but when a relay is turned off should there be any power going through?
anyhow sorry for you trouble.

**Comment by Regalis11** [comment]
> yes it can be fix that way, but when a relay is turned off should there be any power going through?

The problem is that the way you've wired the relay, the power isn't going through it. The battery is receiving power directly from the junction box. As I mentioned, the wires need to be connected at different sides of the relay (power_in and power_out) for the relay to break the circuit.

**Comment by war3scv** [comment]
thanks for the explanation is just that arrangement work on all the previous version, (lot of people need to fix thier sub now.
