### ISSUE TITLE
Tab menu renders on top of everything

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8613]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you have a tab menu open, you can't interact with anything outside of the menu. The tab menu also renders on top of its own contextual menus so you can't adjust players permissions or ban them from the tab menu. 

**Steps To Reproduce**
1. Launch multiplayer campaign
2. Open tab menu
3. Right click your own character in the crew list
4. Notice that no contextual menu comes up
5. Close tab menu and notice that the contextual menu is actually visible but its just rendered below the UI

You can also test using chat while tab menu is open.

**Version**
0.17.3.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/296abff8468e00033438719481f80507770bddb1

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/42eb3ddc3cceed50932eb7f80fd5c2727d23e1c5

Swapped the positions in https://github.com/Regalis11/Barotrauma-development/commit/9d222815c99d14bba4e10720bb9ef849544a47bb as discussed in Slack
