### ISSUE TITLE
[Unstable] Trying to save a sub in editor crashes the game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8616]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Self explanatory

**Version**
v0.17.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/582686e3664ea60d7f5e1af761ad482caf58a546

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
