### ISSUE TITLE
[Unstable] Traveling Tradesman does not work in new shops

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8617]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The special deals amount in new stores is not affected by the Traveling Tradesmen talent

**Steps To Reproduce**
Give yourself the Traveling Tradesmen talent and then travel to a colony outpost. Interact with any vendors.

**Version**
Unstable v0.17.4.0

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@3010cb3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
