### ISSUE TITLE
Hognose Event Boss Healthbar Mislabeled 

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8618]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Hognose mission has specialized objective text for Moping Jack (ie. Kill Moping Jack instead of Kill Hammerhead), and the sonar has a label for Moping Jack, but the healthbar just reads Hammerhead instead of Moping Jack.

![image](https://user-images.githubusercontent.com/91236493/160177414-1608e11f-f0dc-4b37-9dfa-e9db0f22f5c4.png)

**Steps To Reproduce**
Start the Hognose outpost event and take the Kill Moping Jack mission. Attack Moping Jack so their healthbar appears

**Version**
Unstable v0.17.4.0

**Comment by danielasteljoki** [comment]
Added named Moping Jack hammerhead in eee5d1c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
