### ISSUE TITLE
[Unstable] More vendors = More sales

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8619]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Adding more vendors also increased the potential amount of items on sale.

Not really a big deal with electronics/general vendors but always having  3x weapons/medical sales can be pretty huge 
![image](https://user-images.githubusercontent.com/73229309/160177558-2ee2ce47-7792-4d22-bedd-34fa4de89e16.png)

**Comment by ekqvist** [comment]
Decreased the number of daily specials and requested goods for merchan
ts (Regalis11/Barotrauma-development@05cd2d2). Merchants at colonies will have 2 daily specials and 2 requested goods. Merchants at other locations will only have 1 of both.

It is now also possible to change this in the location type definition.

**Comment by Rokvach** [comment]
Only issue I spotted with this is that there's now some unnecessary padding at the top of the list on sell and submarine tabs
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9c3484ae-db64-4d4b-ab41-12ae724fe842)

**Comment by Rokvach** [comment]
There seems to be some overlapping in the submarine tab
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/74b9e77d-aa2c-48d5-b745-d51e6820787a)

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@c3c2e59

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
