### ISSUE TITLE
[Unstable] (Low Priority) Colony Poster Layering Inconsistent

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8620]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Poster decoration layer does not seem to be consistent. Some can be painted on while others can. 

![image](https://user-images.githubusercontent.com/91236493/160178068-20577446-1289-4240-b13b-546895419dbd.png)

**Version**
v0.17.4.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/12c95474e1bf5cb0319aa7f136f501c85a10568f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
