### ISSUE TITLE
cargo missions display "reward x12" on humpback

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8621]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
haven't tested with other subs yet, when you start the mission you get the right amount of cargo.
![image](https://user-images.githubusercontent.com/55637865/160192919-f4a6c382-9522-42a1-85ac-d54a29c10413.png)

**Version**
0.17.4

**Comment by LePiromano** [comment]
it stopped doing it after a few missions, but i didn't change anything

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d521a8be12a00ff51770cac7981c3331f7f2f938

**Comment by Rokvach** [comment]
Tested, working correctly. closing.

**Comment by LePiromano** [comment]
happened again in v0.17.10.0
![image](https://user-images.githubusercontent.com/55637865/163495686-c7628d40-2436-431a-bc77-905a6df288b8.png)
