### ISSUE TITLE
1,500mk hammerhead mission spawned 2 hammerheads

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8622]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the "easier" hammerhead mission spawned both a hammerhead_m and a hammerheadgold_m but the description still talked about a singular hammerhead

**Version**
v0.17.4

**Comment by itchyOwl** [comment]
It's intentional that they may spawn more than one Hammerhead, because one regular is not much of a challenge. Changed the texts to speak about "Hammerheads" in plural: Regalis11/Barotrauma-development@e246842 and adjusted the missions a bit in Regalis11/Barotrauma-development@53be6ff.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
