### ISSUE TITLE
crawlers are a bit too tanky compared to mudraptors

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8623]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
i believe mudraptors are supposed to be at least twice as tanky as crawlers, but with the new feature where crawlers take less damage in almost every part of their body, mudraptor armor breaking so easily, and the health difference between the 2 monsters only being 40, it does feel like mudraptors are only very slightly tankier than crawlers. i don't know if this is the intended feeling but looking at the reward differences between crawler killing and mudraptor killing missions it seems like it isn't

**Version**
0.17.4

**Comment by itchyOwl** [comment]
The mudraptor armor was adjusted to break less easily when we added the veteran, not more easily. Crawler was slightly boosted, but takes more damage at head. I think I could adjust the damage at tail to be slightly higher, but it doesn't feel horribly wrong to me. How did you test it? Wich weapons did you use? Where did you shot them? Does it feel different when you shoot at the veteran (it uses the same modifiers, but just has more hp).

It's intended that the mudraptor feels very "tanky" if you can't shoot past the armor or break it. That is when you shoot them with small arms, not so much with turrets, which should be able to break the armor more easily.

**Comment by itchyOwl** [comment]
Coilgun does break the armor easily, but that's not a new thing. I think we should adjust that a bit.

**Comment by itchyOwl** [comment]
Based on quick testing I did a bit of adjustments:

Mudraptor adjustments:
- Reduced the 2x damage modifier on head to 1.5x.
- Increased health from 120 to 150.

Reduced the coilgun limb severing probability. Physicorium ammo left untouched. Note that coilgun and chain gun ammo also partially penetrate the armor (partially ignoring it), which has a big effect. Penetration was added after introducing mudraptors, so it might require a bit tweaking to get it right. We'll do a turret balancing pass at some point.

Adjusted the vitality multipliers on Crawlers tail and hands: 50% -> 75%

**Comment by LePiromano** [comment]
just discovered https://github.com/Regalis11/Barotrauma/issues/8667, probably had a big impact in this.

**Comment by LePiromano** [comment]
i've been testing around, now the mudraptors seems to be fairly tankier than the crawlers, i think the changes are sufficient

**Comment by Rokvach** [comment]
Closing.
