### ISSUE TITLE
Combat Medic skill cancelled by god mode

### ISSUE THREAD

**Issue by BeanyBoi69** [Regalis11/Barotrauma#8625]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Combat Medic skill stops working when god mode is enabled.

**Steps To Reproduce**
1. get combat medic skill
2. enable godmode
3. it stops working

**Version**
[0.16.7.0] Windows 10

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
