### ISSUE TITLE
Medical Clinic screen gives "Please Wait..." message

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#8628]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I typically run into this issue when having a larger crew in multiplayer. There is an easy workaround, but the menu doesn't work correctly which is really annoying. It is also more difficult to track the total cost since you end up healing the crew in a few batches.

**Steps To Reproduce**
Have a largish crew. (I have not tried this in single player)
Go to the Medical Clinic (Medic on station)
Go though each crew member and queue their ailments.
After you have queue a bunch you will get the "Please Wait..." message when you click on someone. <- this is the issue
You can click Heal and it will let you queue a bunch more until you run into the issue again.
![image](https://user-images.githubusercontent.com/2231937/160256767-926cfa3d-6a72-4cc8-afe7-7d44a640a56d.png)

**Version**
v0.16.7.0 on Linux

**Additional information**
Can we get a heal all button? Unless I am really broke I just heal everything.

**Comment by Xardion495** [comment]
Guess this is cause of UDP protocol issue. Also voting for the 'cure all' button

**Comment by 3e849f2e5c** [comment]
The medical clinic has a rate limiter of 5 requests per 5 seconds and after the limit is reached the server stops responding to the client causing the client to think it has timed out, clearly it seems to be a bit too low (an affliction is at least 2 requests) so I've doubled the limit in https://github.com/Regalis11/Barotrauma-development/commit/aa6ab6007aa20898c73acbf47649f7119b304672

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
