### ISSUE TITLE
Bad outpost generation with console error

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8629]
**Description**
Outpost generated wrongly

**Version**
Unstable. I have an item mod that shouldn't interfere with an outpost in any way at all.

**Additional information**
Pic:
![image](https://user-images.githubusercontent.com/59519434/160257897-0275b473-1553-4694-aa2f-9e880e5b78df.png)

Save:
[Feel.zip](https://github.com/Regalis11/Barotrauma/files/8356404/Feel.zip)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0f70af566b05d19fdff8919c477499f498e71f87

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
