### ISSUE TITLE
Modding - Item variants don't use new item description

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8630]
**Description**
This
![image](https://user-images.githubusercontent.com/59519434/160260377-24092611-7ab6-4b12-a81b-0224061e1e6c.png)
 
results in this:

![image](https://user-images.githubusercontent.com/59519434/160260371-f94adee8-37d7-4cf2-8512-27e687198a63.png)

Would it be possible to make item variants have the ability to use new description?
If it's already possible, please lmk how.

**Comment by Regalis11** [comment]
This should be possible already. Tested with the following xml and it seems to be working fine:
```
<Items>
	<Item name="Rusted Tank" variantof="oxygentank" identifier="rustedtank" description="Rusty oxygen tank description aksjdnfjkasdfnjkasd"/>
</Items>
```
![image](https://user-images.githubusercontent.com/14351070/160367005-ea8035e3-6255-438d-9660-afa54baeb4de.png)

**Comment by Regalis11** [comment]
No known steps to repro, closing
