### ISSUE TITLE
Stabilozine does not heal poisoning if skill check is failed

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8631]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Stabilozine does not heal afflictions of type "poison" if the skill check is failed on use due to a typo in the XML.

**Version**
Windows v0.16.7.0

**Additional information**
![image](https://user-images.githubusercontent.com/67431770/160269035-2419d432-efcf-4304-a331-652698c3ec45.png)

**Comment by Regalis11** [comment]
Could not reproduce: the OnFailure effect seems to be working fine.

**Comment by Jade-Harleyy** [comment]
Ah, nevermind then. I had just assumed it wouldn't work because it used `identifier` instead of `type`.
