### ISSUE TITLE
spinelings dropping frames per second like crazy

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8637]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
your fps randomly drop to below 0 when spinelings are attacking your submarine and then go back to normal after a while.

**Version**
0.17.4

**Comment by Regalis11** [comment]
Could not reproduce:
![image](https://user-images.githubusercontent.com/14351070/160346536-5af79143-8bb3-46cc-8759-338e29738d45.png)

Does this happen in single player or multiplayer? Are you using any mods?

**Comment by LePiromano** [comment]
> Does this happen in single player or multiplayer? Are you using any mods?

Playing singleplayer, no mods.

**Comment by Rokvach** [comment]
Found a way to reproduce this

1. Load up a pirate mission in multiplayer
2. Go to freecamera and find the pirate sub
3. Spawn some spinelings next to the pirate sub, I spawned near the turrets
4. Notice that the performance takes a massive hit and then it eases out again

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/cd890ffd-c04e-40d6-ab1e-b196cb74eca2)

**Comment by Regalis11** [comment]
Managed to repro this now, should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab0cc8a0d2d231ac4ba96ee3ee03c8a3c7229ff0

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce this anymore. Working correctly. Closing.
