### ISSUE TITLE
Character progress wiped after death on the next round

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#8638]
**Description**
A player character died in the round. On the next one we arrived at abandoned outpost. After revived player noticed that all skills and perks are nullified. Previously in case of death only the skills reset to default and perks remained untouched

**Steps To Reproduce**
Unknown

**Version**
Barotrauma Dedicated Server from 11 March 2022 – 02:10:10 UTC
OS: Ubuntu Server 20.04.4 LTS (GNU/Linux 5.4.0-91-generic x86_64)

**Additional information**
tickrate="20"
randomizeseed="True"
userespawnshuttle="False"
respawninterval="0"
allowrespawn="False"
karmaenabled="True"
karmapreset="strict"

Mods:
oClockRadar / Sonar [Alt Appearance]
Stations from beyond
Beacons Extended
Shipwrecks Extended

**Comment by Ek-Videogames** [comment]
"Reaper's Tax" implementation is in a weird state of limbo right now, so I still am not entirely confident to say what is "intended" and what is a bug. What I can say is that this is a widely known issue with players choosing to respawn with reapers tax or waiting until the next round and still getting their skills reset regardless.

**Comment by Xardion495** [comment]
By perks I meant the talents, yes. Your steps were right but in our case the talents are gone. I guess this is floating error.
Recently I noticed in CLI some error messages but when I checked the log, they weren't there. And serversettings.xml has no logging level parameter. That's making tracing harder
