### ISSUE TITLE
Bot pathfinding breaks when outside subs with single hatch based airlocks

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#8639]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was testing a friend's sub when I noticed how poorly bots followed waypoints outside of a sub when attempting to return to it. I tried to see what the issue was by looking at different subs and how waypoints were set up and how bots navigated it. Turns out that ships, such as the Remora and the Humpback as well as my friend's sub, which has one hatch airlock on the bottom, seemingly breaks the AI's pathfinding and will resort to attempting to go directly towards the airlock with no respect to obstacles like the ship's hull and almost all the times get stuck. Subs with two hatch airlocks on both top and bottom like the Orca seems fine for them to path either or to and the more common door airlocks found on ships like the Azimuth and the Typhons, AI seems to have no trouble following their waypoints towards those airlock, even when sent to the far ends of the ships to navigate back to the airlock.

**Steps To Reproduce
Using the Humpback as an example, and can be replicated with Remora as well. When the bot is brought or teleported to the same side of where the airlock is, they generally seem to have no problem navigating back into the ship using that airlock. When they are brought on top the Humpback, they seemingly start using the waypoints for a second or two before breaking and resorting to trying to brute force their way to the airlock by swimming at the direction of the airlock, causing them to get stuck.

![image](https://user-images.githubusercontent.com/85914375/160308683-181ab45f-10fe-4cb9-b2fd-adee3f9fe912.png)
3 bots stuck on top the humpback, unable to path back.

![image](https://user-images.githubusercontent.com/85914375/160308701-923dae7c-f79f-4d18-a65c-bf831f0cb6f9.png)
5 bots returning back to the Azimuth's door airlock successfully

**Version**
0.16.7.0

**Comment by itchyOwl** [comment]
Ok, so here's the issue (debugai in console to see it): ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/ffb480f6-0471-4a09-be0b-5ec15cbb06a6)

Happened because the raycast for the visibility check didn't take Submarine's collider into account. Disabled node skipping when the character is close to the sub, because it would still fail if there's multiple subs around (e.g. a drone).

Fixed in Regalis11/Barotrauma-development@18f682c.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
