### ISSUE TITLE
[Unstable] Relay oscillations 

### ISSUE THREAD

**Issue by Torca2001** [Regalis11/Barotrauma#8643]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Having a reactor partially power the grid and having batteries connected to the main grid through a relay causes rapid spiking, the power jumps between the reactor output to close to 1:1 with the load.
The issue arises due toe the reactor providing partial power and the batteries being unable to provide sufficient power, causes the relay to undervolt and not output due to the voltage difference and then charge its internal buffer, lowering the input side voltage and rapidly discharging, this repeated indefinitely.

**Steps To Reproduce**
Load up the typhon 2, set the reactor to turbine output around 15%.
Set both batteries to 25 charge and ensure they have a recharge set to 50%
Turn on the relay directly below the batteries that connects them to the grid.
Watch the lights flicker, check in junction box as the power value jumps erratically.

**Version**
Unstable 17.4.0.0

**Additional information**
I've tried to resolve the issue as its a problem with the interaction of the relay and batteries but the only solution I have found only fixes the problem partially by turning off the pseudo overvoltage and under-voltage of the relay turning it into a mini battery if the only source devices on its input are batteries and the batteries make up a majority of the grid.
This does fix it but any relay chain in front of it will break it as the chained relay won't enter the mode, this might not matter as this edge case only occurs if there is a reactor downstream of the relay chain providing partial power.

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. It seems like this only happens in very specific circumstances, doesn't cause any major problems, and we haven't gotten any other reports about it, so to me it seems safe to ignore.
