### ISSUE TITLE
[Unstable 17.4] Flashlight sparks when equipped

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#8644]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
An equipped flashlight generates sparks when equipped.

**Steps To Reproduce**
- Place full (regular) battery into flashlight.
- Equip flashlight

**Version**
Unstable 17.4
Windows

**Additional information**
Video showing issue:
https://streamable.com/z0zxdg

**Comment by Regalis11** [comment]
Whoops, I added this to test https://github.com/Regalis11/Barotrauma/issues/8584 and accidentally committed the changes. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cb433baf47e8cd77cf060fe11aee630e030965b3

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
