### ISSUE TITLE
Typhon 2 may need a price tag rework

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#8645]
Back when it was added, the typhon subs were one of the few with railguns, making their high cost and inherit flaws (e.g. massive forward facing gun blindspot often resulting in an inhittable mudraptor tunneling into the bridge, tendency for junction box fires, being slow as molasses) justifiable if you were going to go somewhere dangerous. However, due to the guns under the ice rework, any sub can now mount a railgun, and at least in my experience the typhon 2 is now largely beaten out by cheaper, faster subs like a railgun equipped orca or the herja's higher gun count. This isn't me asking for a typhon revamp (though moving the unused gun mount to the bow / turning the useless ventral shuttle dock into an airlock would be nice), but it is definitely not worth the current 20k marks price tag if cheaper subs can do the same job better. Not a requirement or a 1st priority, but I've got a soft spot for the typhon class so i hate seeing it turning obsolete.

**Comment by Rokvach** [comment]
No issues, closing.
