### ISSUE TITLE
Ai autopilot unable to pass certain environmental hazards

### ISSUE THREAD

**Issue by KingkumaArt** [Regalis11/Barotrauma#8647]
Issue: sometimes the autopilot AI will stop the sub dead if it sees an ice spire/iceberg it could easily pass, or gets the ship permanently stuck in a peizo crystal emp loop.

Steps to reproduce: The ice one is much more common, and probably the easier fix, but run any tall sub like a kastrull or typhon on autopilot  through the cold caverns without any ai gunners and you'll probably run into this. The crystal emp is rarer but basically involves the ai getting too close to a peizo crystal and for one reason or another not maintaining enough velocity to escape a sort of emp feedback loop.

Version: Stable.

Additional note: I've had the autopilot leeroy Jenkins through ballast flora to avoid icebergs, but I'm unsure if that's a bug or just icebergs having being a higher priority to avoid for the autopilot. Also I'm aware of the issue thread about gunners not shooting spires, just felt a general list of autopilot issues would be okay.

**Comment by Regalis11** [comment]
This is intentional: as instructed in the warning on the monitor, you should switch to manual steering to navigate around ice spires.
