### ISSUE TITLE
Disabling karma does not disable the spam filter auto-kicking 

### ISSUE THREAD

**Issue by philippewarren** [Regalis11/Barotrauma#8648]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There is no option to disable the spam filter, and it is not disabled by default when karma is disabled. For small servers with a few friends, it is annoying when you get automatically kicked because of spam, even if you disabled karma.

**Steps To Reproduce**
Create a server with karma disabled. Look in the server options. There is no way to disable the spam auto-kick feature. Launch the server, and spam a request. You will be kicked.

**Version**
v0.16.7.0, Windows

**Additional information**
I'm unsure if this is a bug or a feature request. I would consider it a potential bug that disabling karma doesn't disable the spam filter kicking feature, too. But if the option was a separate option, it might be more of a feature request. In any way, it is really annoying when it happens.

**Comment by Regalis11** [comment]
We decided to close this as it's not really a bug: the karma system is a feature separate from the spam filter. That being said, having more settings for the spam filter would be useful, we'll look into it in the future!
