### ISSUE TITLE
[Unstable] Barotrauma crashes on startup when having a modded language enabled

### ISSUE THREAD

**Issue by FweeGamerHD** [Regalis11/Barotrauma#8649]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
As per usual, I play the game with a modded language called "NocksLang" All it does is pretty much just add some more details to item descriptions. Turn out, the current unstable version doesn't like me having the language still enabled from when I played the stable version, hence why the game crashes on start up.

**Steps To Reproduce**
1. Boot up the game in the stable version and switch the language to any modded one
2. Reboot the game, but this time as unstable
3. Observe how it crashes

**Version**
Unstable V0.17.5.0, Windows 10

**Additional information**
See crashreport for additional info, has been the same for 3 crashes when booting up the unstable version now.
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/8373925/crashreport.3.log)

**Comment by FweeGamerHD** [comment]
This also causes the config_player.xml to be broken to the point of needing to be removed to boot the game in either stable/unstable.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/02b67c6d3027a6e0d67a45cdd967d4e3bb182f2a
