### ISSUE TITLE
Feature Request - Aim for the Melee Weapons

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#8650]
I think it's hard to aim with melee weapon in water at moments like trying to make an exit without plasma caster or hit the part of the enemy body that you want (mostly head) and i think it's just satisfying.

**Comment by Regalis11** [comment]
Thank you for the request! We are actually working on this atm (ticket in our private repo https://github.com/Regalis11/Barotrauma-development/issues/1633). We generally only use this issue tracker for bug reports though, so I'll close this ticket.
