### ISSUE TITLE
[Unstable] Items you buy from vending machine are of Excellent Quality

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8651]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Title

**Steps To Reproduce**
Buy a battery/oxygen tank/welding fuel from a vending machine
It is of excellent quality

Version
Unstable V0.17.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1b0e989306b7bae52a5d7d235e6d00fd60d5beba (referenced incorrect issue in the commit message)

**Comment by Rokvach** [comment]
The item quality is still displayed wrong on the vending machine
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/23238449-efb5-4f81-b887-271d47be2c99)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9a78c2fd5da68fe8eb9c0ac8f7b791de04e0dc06

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
