### ISSUE TITLE
[Unstable] Items in vending machine do not show as out of stock, takes your money

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8652]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After buying a certain amount of one item from a vending machine, the machine stops giving you the item, but still takes your money.
The item is most likely out of stock, but still shows as purcheasable

Version
Unstable V0.17.5.0

**Comment by Regalis11** [comment]
In multiplayer I guess?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/660bc13f47c766568cde594b413601e1019d9cd1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
