### ISSUE TITLE
Stairs not climbable when water at a certain level

### ISSUE THREAD

**Issue by Zetabite** [Regalis11/Barotrauma#8656]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to navigate up the stairs while water is at a certain level covering them, they are not climbable and the character will just lay flat, parallel to the diagonal of the stairs. This makes it impossible in Barsuk for example, to get back on the platform, and you will die because you cant maintain any of the equipment. This happens with the AI controlled characters, and the player. Its only possible to swim away from it, but impossible to get up the stairs

**Steps To Reproduce**
1. Have water leaking
2. Fill it up a room to a certain level, so that a portion of the stairs is covered in water
3. Fall, or be in the water
4. Try to climb up stairs
5. Observe that you lay parallel to the stairs, impossible to climb them up

**Version**
0.16.7.0 (Linux)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cc1475282eda9d8b2d7575ab77fe96f5de34048a

> Improved the logic that determines whether a character should swim or walk: always check if the water is shallow enough to walk instead of assuming the character has to swim if the hull they're in is full of water. Fixes characters getting stuck on stairs that lead up from a flooded hull to another hull, because the character was forced to swim while they were in the flooded room (even if they could get up on the stairs).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
