### ISSUE TITLE
[Unstable] Crash on startup (FreeType error: Horizontal metrics (hmtx) table missing)

### ISSUE THREAD

**Issue by Zetabite** [Regalis11/Barotrauma#8658]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes on startup.

**Steps To Reproduce**
1. Use unstable

2. Launch
3. Crash

**Version**
0.17.5.0 Linux

Files:
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/8376626/crashreport.2.log)
[crashreport (3).log](https://github.com/Regalis11/Barotrauma/files/8376627/crashreport.3.log)

**Comment by Regalis11** [comment]
Should be fixed in the latest unstable (v0.17.6.0)

**Comment by Zetabite** [comment]
Can confirm, seems to be fixed. Closing
