### ISSUE TITLE
Status Effect bug

### ISSUE THREAD

**Issue by ChikoEduardo** [Regalis11/Barotrauma#866]
So, I made an item that can only be applied to unconscious characters: 

  `<MeleeWeapon characterusable="true" canBeCombined="true" slots="Any,RightHand,LeftHand"
              aimpos="5,0" handle1="-5,0" holdangle="10" reload="1.0">
      <StatusEffect tags="auxiliorizine,medical" type="OnUse" target="Character" Health="0.1" 
  Oxygen="0.25" Bleeding="-0.005" delay="12" duration="90">
        <Conditional stun="gt 0"/>
      </StatusEffect>     
	  <StatusEffect type="OnUse" target="This,Character" Condition="-25" disabledeltatime="true">
        <Conditional stun="gt 0"/>
      </StatusEffect>
    </MeleeWeapon>`

It works but the delay="12" in there somehow forces it to ignore the conditional and apply the effects after the delay. I tried checkconditionalalways="true" but it just prevents it from doing anything at all.

I'll remove the delay for now since it's the only way so far for it to work.

**Comment by Regalis11** [comment]
Typoed the issue number in commit 5c054bea, didn't mean to reference this one
