### ISSUE TITLE
Herja still broken

### ISSUE THREAD

**Issue by Smau35** [Regalis11/Barotrauma#8661]
Herja still has an offset motion detector and rear turret motion detector wired to the light of the ventral hardpoint sign (Which is incorrectly named rear turret)

![Näyttökuva (1171)](https://user-images.githubusercontent.com/86321358/160800768-d5e56cf6-e97a-43ed-9a5b-fb1baf823e03.png)

![Näyttökuva (1172)](https://user-images.githubusercontent.com/86321358/160800780-572e5c0f-e657-44a2-bdd4-2b6ad00b231f.png)

![Näyttökuva (1173)](https://user-images.githubusercontent.com/86321358/160800793-6812e4ba-2549-41b5-b089-90a5a0795214.png)

**Version**
V0.17.5.0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
