### ISSUE TITLE
Medical curtains vanish too early if they partially go off screen

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8662]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/42aca398-bd86-46f1-ae7b-ac4bdfae716d)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/92d68d6a-0713-4e07-976a-d126e13c4075)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c8b55209a7f57b6591ad786f919fdb782eb0395

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
