### ISSUE TITLE
Cannot add container tags with the sub editor's tag picking menu

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#8665]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It is not possible to select tags for containers from the dropdown list. Only a comma is added to the list of tags, not the tag itself.

**Steps To Reproduce**
Open the submarine editor and try to assign a new tag from the list to any container.

**Version**
v0.17.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a345cb040689b78ab265fc6e02fa5a9a11f4aaa6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
