### ISSUE TITLE
Vitality multipliers ain't workin

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8667]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
no wonder the crawlers felt tanky, the damage modifiers seem to straight up not work on any of the creatures, not even humans.
https://user-images.githubusercontent.com/55637865/160957989-37781914-9a94-4a27-8ba3-5386805541b0.mp4
husks
https://user-images.githubusercontent.com/55637865/160957424-c4f33b4c-2fb9-4d86-8632-3849fb823e9d.mp4
crawlers
https://user-images.githubusercontent.com/55637865/160957536-64afbad1-c7fd-4c16-a29d-a7d5e2a6dd82.mp4

they do work on other creatures because they use normal limb damage multipliers instead of the ones that used to only be used by husks and humans

**Version**
v0.17.5

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/637fdb4b374de648c6be6096112577887aa54126
