### ISSUE TITLE
[Unstable] Crash when choosing "Create a Level Object" in the Level Editor

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8669]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the "Create a Level Object" button is pressed in the Level Editor, the game crashes.

**Steps To Reproduce**
1. Open the Level Editor with the `editlevels` command.
2. Generate a level (unknown if required).
3. Press the "Create a Level Object" button.

**Version**
Windows Unstable v0.17.5.0

**Additional information**
[crashreport (6).log](https://github.com/Regalis11/Barotrauma/files/8386228/crashreport.6.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b9318c5fcf9e04108bf1f065dd377a4fe7ed68b6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
