### ISSUE TITLE
Null reference exception (crash) in the bot combat state while following the player

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8670]
Steps to repro:
- Tell a bot to follow you
- Ensure that the bot don't have ranged weapons
- Go outside of sub
- Tell the character that you are controlling to hold the position
- Spawn Swarmfeeder near the bot
- Control the Swarmfeeder and attack the bot
- The bot should start fleeing from the monster
- Dismiss the follow order with right click
- The game should crash with a null reference exception at AIObjectiveManager.cs:633.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
