### ISSUE TITLE
Event art is missing

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8671]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Just do any outpost event and notice that there isn't any art displayed next to the event dialog

**Version**
0.17.5.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/51d129605367dcce09bd8949ce3eb73691c87a09

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
