### ISSUE TITLE
Can't keep crewlist minimized

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8673]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you minimize the crewllist it will just show up if you use any type of item, like a ladder. Previously when crewlist was hidden it only showed up on areas where it might be useful to have visible. 

**Version**
0.17.5.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/2fd7cd14e379897fb706546859f902c7f431c8c6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7e7428dc757741307097b2b2f2397fc73707eb92

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
