### ISSUE TITLE
Character names are all uppercase when using the health scanner

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8674]
I remember that we fixed this one before but it seems to be back, it mainly causes overflowing if they are uppercase

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d8b43632-d23a-4655-b15f-d8a15933e766)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/623a80726060539cacdd2c57fb94bb343982384b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
