### ISSUE TITLE
StoreUpdate is misaligned in showperf

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8676]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8934cb1b-02a6-4ca0-9990-0f19cd72d6d5)

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@a8e5f54

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
