### ISSUE TITLE
[Unstable] File Transfer does not include Item Assemblies

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8677]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Item Assemblies are not included in the file transfer to LocalMods.

**Version**
Windows Unstable v0.17.5.0

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f1938cdf4960468831657c41ad3754cdc8e54831
