### ISSUE TITLE
Outpost guards stuck on ladder

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8678]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was just testing what happens when I attack outpost NPC's and I noticed that the outposts guards didn't come and attack me, noticed that all of them were stuck on the same ladder

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/07c76dd0-0727-4acd-96d1-3408b9ade1e3)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fdd9fae1-95a2-42e7-b6f6-5c55a7af70af)

**Steps To Reproduce**
Load up the multiplayer campaign save, run to the reactor room and shoot one of the NPC's there now walk back to the docking area and notice that there should be some guards stuck on the ladder in the hallway leading up. If those guards were up there when you shot the NPC's ofc. 

[https://app.zenhub.com/files/93301055/8dfb275d-073b-4344-b9d6-36be6dc0a17d/download](https://app.zenhub.com/files/93301055/8dfb275d-073b-4344-b9d6-36be6dc0a17d/download)

**Version**
0.17.5.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/d4a069145ee12ae804b86257a4017dd97562920e

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@c640771.

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue. Seems to be working correctly, closing.

**Comment by itchyOwl** [comment]
Seems to still get stuck occasionally: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/6a1a1de3-9a0b-4405-b175-99c10ca016e1)

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
