### ISSUE TITLE
server doesnt remember the karma preset

### ISSUE THREAD

**Issue by GenericGoose** [Regalis11/Barotrauma#8680]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After rehosting, the server sets the karma preset to default, instead of the one you were using.

**Steps To Reproduce**
Host a server through the game. Set karma preset to custom. Shut the server off. Host again. Karma preset is now default.

**Version**
0.16.7.0
Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
