### ISSUE TITLE
Article about Barotrauma

### ISSUE THREAD

**Issue by MikhailEvt** [Regalis11/Barotrauma#8681]
I analyzed the source code of Barotrauma on static analyzer PVS-Studio and wrote an [article](https://pvs-studio.com/en/blog/posts/csharp/0930/) about it. 
Please, read it. Perhaps fixing the described errors will help improve the code. 
Hope this helps you.

**Comment by Regalis11** [comment]
Thank you, these were really helpful findings! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/a4abe34a46d9eff29cc7ea7936c8acaa568ff997
