### ISSUE TITLE
Research Station cannot handle being damaged

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8683]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Research Station has a condition, a condition_out pin, can be damaged, but:
-it doesn't have a damaged sprite
-it doesn't deteriorate passively like other machines do
-it cannot be repaired via its wiring panel (you need to click on it for repairs to show up, can't press E)
![image](https://user-images.githubusercontent.com/73229309/161085445-3c99129b-91c5-410c-9989-8baef9cacde9.png)

Compare to a JB:
![image](https://user-images.githubusercontent.com/73229309/161085516-36869478-1f84-41ec-aafe-ee064aba02d1.png)

**Steps To Reproduce**
Go in sub editor and spawn a research station with 0 condition
Try to interact with it using a screwdriver

**Comment by Regalis11** [comment]
> it cannot be repaired via its wiring panel (you need to click on it for repairs to show up, can't press E)

Fixed this one in https://github.com/Regalis11/Barotrauma-development/commit/6d4acbf90e371a6431e31c12720759a60e8c75a6, but I don't think we need to fix the rest as there's no way for the device to get damaged "naturally".

**Comment by ubertpendragon** [comment]
> I don't think we need to fix the rest as there's no way for the device to get damaged "naturally".

It does takes damage from explosions and EMP. It just a little weird to have a pristine research station after the sub got nuked

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
