### ISSUE TITLE
When joining mid-round, subs purchased during that round aren't visible in the sub switch menu

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8686]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When joining mid-round, subs purchased during that round aren't visible in the sub switch menu

**Steps To Reproduce**
1. Start a multiplayer campaign
2. Purchase another sub
3. Join the server as another client
4. Check the submarine switch terminal, and you should only see the starting sub

**Version**
v0.16 and later, possibly earlier versions as well

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d1c4417edec0ac7073596a9a803856ddd22f297

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
