### ISSUE TITLE
Dugong's Small Pumps draw but do not require Power

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8687]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The small pumps around the Dugong draw but don't require power due to their Min Voltages being set to 0.

**Version**
Windows 0.16.7.0

**Additional information**
Picture of one of the Dugong's small pumps' settings:
![image](https://user-images.githubusercontent.com/67431770/161235024-92d6c5a8-98c2-4c98-832a-4176bf01259a.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b723e6edd44c4195af741260c550b6297f7272c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
