### ISSUE TITLE
[Unstable] Terminal has odd hitbox

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8688]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Terminal installation has an odd hitbox that is slightly above the sprite

**Steps To Reproduce**
1. Open the Submarine Editor
2. Spawn a Terminal
3. Select the Terminal

**Version**
Windows Unstable v0.17.5.0

**Additional information**
Picture of the Terminal's hitbox with gridlines on:
![image](https://user-images.githubusercontent.com/67431770/161236795-3fa1d8e5-f692-49cc-9065-05669387b7b4.png)

**Comment by Regalis11** [comment]
This is intentional, the sprite is centered at the monitor to get it's physics body to align with the sprite.
