### ISSUE TITLE
Can't switch submarines in the campaign

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8689]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to switch the submarine does nothing

**Version**
v0.17.0.0

**Additional information**
Seems to have been broken in https://github.com/Regalis11/Barotrauma-development/commit/c86ecb06c1a3b75f3960e446472d8ad5d553eea1, accidentally removed a line when resolving a merge conflict?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d1c4417edec0ac7073596a9a803856ddd22f297

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
