### ISSUE TITLE
[Modding refactor] Modded server is shown as not compatible

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8692]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think modded servers should be shown as compatible even though you don't have the mods installed as you will get the mods from the server anyway. So having the server shown as not compatible just makes the player think that they can't join it. 

**Version**
Unstable 0.17.6.0

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b367f95d-9ee1-4405-9383-4cfb616eeb31)

**Comment by juanjp600** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d6cf284f7bba7f04c322e819fb986329e1e7b7e
