### ISSUE TITLE
cigar remains un-buffed

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8697]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you noticeably buffed the captain's pipe, but the cigar remains unchanged, is this intended?

**Version**
v0.17.6

**Comment by JeroonBosch** [comment]
Put the cigar on par with pipe tobacco now, thanks for reminding me.
Sneaked in a nerf as well to tobacco products, as growing and selling cigars seemed to be quite lucrative in my experience.

**Comment by Rokvach** [comment]
No issues, closing.
