### ISSUE TITLE
vomiting doesn't make the sound

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8698]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the sound that used to play when vomiting doesn't play anymore

**Version**
v0.17.6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16566a4dab21354a853b31cb64587cc587b3eb91

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
