### ISSUE TITLE
Joining a server that is in the process of ending round results in an exception

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#87]
Joining a server can result in an error for the End Game co routine under game client for "Object Reference not set to an instance of an object."

If a player does not spectate after joining a server, and the server is ending the error will be thrown on the clients side. - This is likely due to not being synced yet and having the character data for the crew list or other such.

**Comment by Crystalwarrior** [comment]
Perhaps a viable fix is to simply deny spectating during end?

**Comment by NilanthAnimosus** [comment]
this is caused without clicking spectate or even beginning mid round sync - if anything that might actually prevent it.

This is more towards Joined -> not hit spectate and the round has ended / begun ending.

**Comment by Regalis11** [comment]
Haven't been able to reproduce this and I don't really see what could be throwing the exception in the EndGame coroutine. I did found a bug that causes an exception when the round ends, but it happens before the coroutine is started (see 466e6f8). If that's not related to this issue and the exception does indeed happen in the coroutine, a crash report would help a lot in figuring out the cause.

**Comment by NilanthAnimosus** [comment]
It seems this got reproduced despite the fact I recall I saw a co-routine error and couldn't seem to reproduce it. seeing 633bd85 I'm sure this is solved now (I almost closed this for thinking it was fixed or I'd gone mad but kept it here while trying to cause it on 0.7.0.1).
