### ISSUE TITLE
[Dev version] Another issue with docks

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#870]
Similar to issue described in my comment in #551, but this time it does not push you away, but instead just does not let you move inside and makes you die from pressure in the spot between the docks.

Seems to be an issue with custom subs, as it does not appear on Aegir mark III.

For some reason this bug is only in the dev version. Public version works fine.

Videos:
Public: https://streamable.com/cj1lh
Dev:    https://streamable.com/05jvl

The submarine in which the bug occurs:
[Sub.zip](https://github.com/Regalis11/Barotrauma/files/2553508/Sub.zip)
The bug happens only when trying to get inside the shuttle from the bottom of the sub in question.
_______________________________________________________________________________________________________________
(Unrelated to the issue)

By the way, i have been updating #844, not sure if you noticed(recency of edits is not visible in the issues tab when browsing it with sorting set to "newest"(which is set by default)). I still don't know if it's convenient for you to work with a big compilation of small issues or if i should split them all into separate issues. For now i will keep updating the #844.

**Comment by Regalis11** [comment]
Thanks for the report and the sub file, I was able to reproduce it and looking into fixing it.

As for #844, splitting it into separate issues would be really helpful: it's easier for us to keep track of what has been fixed when each bug/request is separate, and we notice new issue reports faster than edits because of the email notifications.

**Comment by BillCombs** [comment]
Alright, in that case i am going to work on splitting the issues. Thanks for replying.
