### ISSUE TITLE
Radiochat/localchat reconnecting issues when teammates leave too far/long

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#8700]
- ✅ I have searched the issue tracker to check if the issue has already been reported.

**Description**
When teammates leave the sub for a while and return, expedition crew and submarine crew (who stayed to waiting) can't hear each other even in local voice chat. After a while the bug disappears and voicechat restoring. Channel toggling, headset reequipping, headset battery resetting are not helping. Sometimes the bug is not showing up (round-to-round), sometimes the bug causing effect to a part of crews.

**Steps To Reproduce**
1. Send an expedition team
2. Wait for their return
3. Try to communicate

**Version**
Barotrauma Dedicated Server 0.16.7.0 (ReleaseLinux, branch release, revision aa4c852c2c)
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)

**Additional information**
Radio and local text chats working normally

**Comment by Rokvach** [comment]
This issue hasn't come up with internal and Unstable testing, the ticket was also posted a while ago and there's been changes to the voip since, so even if this issue did happen at some point there's no recent mentions of it happening. Closing.
