### ISSUE TITLE
tearing mudraptor's jaw and front head armor off makes them harmless

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8701]
- [yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you can blow off both the mudraptor's (or mudraptor veteran's) front armor and jaw with a single shotgun shell and leave them with no way to defend themselves on dry land other than kicking, they can't even break doors.
you should probably move their charge/fast attacks to their "main head" instead of the jaw and armor

**Version**
v0.17.6

**Comment by itchyOwl** [comment]
I don't see the current behavior problematic. We could make the jaw non-severable, but I think it would be weird if the creature could attack without a jaw or head armor by just head-butting or something. It can use the legs, so it's not harmless.

The chance for severing the jaw is pretty low too.
