### ISSUE TITLE
Lights ignore min voltage for flicker calculations

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#8704]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you set min voltage on a light to 0.9, it still takes 0.5x undervoltage for them to completely flicker out.

**Steps To Reproduce**
Add a light with min voltage 0.9. It will stay lit with say, 1200W load and 1000W power, and won't go fully out untill 2000W load. 

**Version**
current stable version

**Comment by Regalis11** [comment]
This is intentional: the brightness of the light is directly proportional to the voltage (meaning that they'll start turning on as soon as the voltage is above 0).
