### ISSUE TITLE
VELOCITY_IN socket in Navigation Terminal doesn't affect on engine thrust and ballast_pumps in multiplayer

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#8707]
- ✅ I have searched the issue tracker to check if the issue has already been reported.

**Description**
VELOCITY_IN socket in Navigation Terminal doesn't affect on engine thrust and ballast_pumps in multiplayer. It's only dropping terminal vector to zero values.

**Steps To Reproduce**
1. Set thrust and water level to any values using terminal vector
2. Ask teammate to press the button connected with the socket
3. Check the thrust level/water level on the engine/ballast pump interface

**Version**
Barotrauma Dedicated Server 0.16.7.0 (ReleaseLinux, branch release, revision aa4c852c2c)
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)

**Additional information**
tickrate="40"

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I could not reproduce this though. Tested by sending values from a terminal to the navigation terminal's "velocity_in" connection.

What kind of an item or circuit did you use to send signals to the terminal?

**Comment by Xardion495** [comment]
Simple button - https://barotraumagame.com/wiki/Button with default behavior (sends one-time signal "1" when clicked)

**Comment by Regalis11** [comment]
A button will not work for this purpose: the velocity_in input takes in a vector (e.g. `100,0`), not a single numeric value like `1`.

**Comment by Xardion495** [comment]
In singleplayer when VELOCITY_IN socket receive any value (negative, zero, positive) it's dropping terminal vector to the center, so engine thrust setting to zero and ballast pumps pumping the water level to 'neutral ballast level' parameter of navigation terminal (steering section). The button causes the same effect. So i expecting this behavior in multiplayer too. Am I wrong?

**Comment by Xardion495** [comment]
Maybe the name of the socket is misleading cause at this moment that's name more appropriate as VELOCITY_ZEROING_IN. Hope to see the final conclusion.
