### ISSUE TITLE
Moderator icon doesn't show up when giving permissions mid round

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8713]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The star icon that indicates special permissions doesn't show up in the tab menu when you give permissions to a client mid-round.

**Steps To Reproduce**
1. Start a round
2. Give permissions to one of the clients in the server
3. Check the tab menu: there's no icon next to the client's name

**Version**
v0.17.x.x, possibly earlier too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b725b0305772710632dda34743a92d0d06697d0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
