### ISSUE TITLE
Tab menu truncates the amount of money too eagerly

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8714]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When there's not enough space to display a client's wallet balance, it gets replaced with "LOTS". This is done a little too eagerly, just ~1000 mk or so is enough to go above the limit.

**Steps To Reproduce**
1. Start an mp campaign, with the resolution set to e.g. 1600x900
2. Give one of the clients 1000 marks

![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/b123e050-4c52-4fbe-b73d-d2a808d61d68)

**Version**
v0.17.6.0

**Additional information**
Maybe we should use the default font here instead of the larger subheading font and make sure there's more space for the text

**Comment by 3e849f2e5c** [comment]
Adjusted in https://github.com/Regalis11/Barotrauma-development/commit/55186c74d077fce2826c2eff5b2286afad78871a and https://github.com/Regalis11/Barotrauma-development/commit/c8de1a4b2e3ef6bb5201fbe4f1f3f575de3b771c

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ab81378caa9cdeaab0f73b8ebc64b6d28734ec0

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
