### ISSUE TITLE
Deep Sea Slayer talent not affecting harpoon explosion damages

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8716]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deep Sea Slayer talent only increases direct impact damage, doesn't affect the explosion effects of harpoons

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.16. stable

**Additional information**
reported via wiki editing

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
