### ISSUE TITLE
wire lock doesn't apply to drones

### ISSUE THREAD

**Issue by GenericGoose** [Regalis11/Barotrauma#8717]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On a server with default wire lock the setting doesn't lock the wires on the shuttle/drone attached to the sub

**Steps To Reproduce**
Host a server with the wire lock on and use a sub that has a drone/shuttle

**Version**
0.16 stable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1871e53eb86971ea174b0c512852533a426dd14d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
