### ISSUE TITLE
[Wallets] Allow host to set a maximum amount that the crew can request money in server settings

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8718]
Currently its a bit too easy to just request a massive amounts and maybe get the vote to pass if crew doesn't pay enough attention to the vote. So having a way to set a maximum request amount would be ideal.

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/8cdae33fd7181f4a5f7a68e731c0f041accb1110

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
