### ISSUE TITLE
[Wallet] Crewlist wallet and ping switches places when player dies

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8721]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Also Udrakan looted my marks but the marks are still shown as if I have them, everything is shown correctly once you respawn. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c2184f90-09a2-400a-a1ec-c036f8323a7b)

**Version**
Unstable 0.17.6.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e55da9eb21c2ed1e380f43a2dbf1b49b6030ec9c

**Comment by Lithosagym** [comment]
Tested, the ping and wallet interfaces no longer swap with death, confirmed fixed.
