### ISSUE TITLE
Add money to wreck corpses and enemy NPC's

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8723]
Just some pocket change

**Comment by 3e849f2e5c** [comment]
This ticket is ready for design insight, (how much money do we want to put on corpses?)

**Comment by itchyOwl** [comment]
Hmm, I think this is related to economy balancing (@JeroonBosch). Currently there's corpses only in wrecks (3-6). Maybe random 10-50 per corpse for starters? We can then adjust this later.

**Comment by JeroonBosch** [comment]
Does this give anything in SP to the general bank, or purely for MP? 30 Mk to 300 Mk per wreck seems fine, nothing gamebreaking

**Comment by 3e849f2e5c** [comment]
Currently on dev branch grabbing corpses does nothing so it only works in multiplayer, this has been changed to also work in singleplayer in the `feature/crew-wallet-improvements` branch which is awaiting to be merged

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-development@25152ac.
