### ISSUE TITLE
Small UI overlap in reputation screen (1440p resolution)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8724]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing on 1440p resolution the next reward section of reputation is rendered slightly on top of the faction description
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4cffc455-c1cb-4b2d-bb62-56533510b5c8)

**Comment by ekqvist** [comment]
Note: seems to only happens in the Reputation panel on the round summary, not in the tab menu

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@f510c3c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
