### ISSUE TITLE
[Wallet] When multiple players request money at the same time only the first one to request gets the vote

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8726]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think this is fine that the first one gets the vote but the second player would still need to be informed somehow that their request failed, or then just queue the requests.

**Version**
Unstable 0.17.6.0

**Comment by Regalis11** [comment]
The votes should be queued, this is a bug

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/635b60f691d3bc436ac8abc2ec6bb35920836871

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
