### ISSUE TITLE
EASY handheld weapon abyss monster kill

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#8727]
- [yea] I have searched the issue tracker to check if the issue has already been reported.

**Description**
you can just get inside an abyss island and the abyss creature won't fit  in but still try to get you so you can just sit there and kill it
it wont target the sub before targeting the guy inside the abyss island either so the sub can just shoot it down and the creature will be too angry at the guy in the island to care
https://user-images.githubusercontent.com/55637865/161656515-d67ebda9-bf29-4029-9cb1-e072c77c5348.mp4

**Version**
v0.17.6

**Comment by itchyOwl** [comment]
I'd say this is mainly a design issue. Of course any possible solution might require code too. Any suggestions?

**Comment by Regalis11** [comment]
Maybe the monster could slowly lose interest in the target if they fail to do damage to it?

**Comment by itchyOwl** [comment]
Yeah I think this is a more general level issue with the enemy AI. Can also happen e.g. if the monster can't for some reason rotate so that it can reach a wall target. Need to think about it.

**Comment by cshingle** [comment]
A bit of ice and rock wont save you from these beasts. I suspect it would be a coding nightmare this would be, but what if terrain was somewhat destructible by abyss monsters? As a shortcut to making terrain destructible just let them clip into the terrain a bit.

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@613d330. The monsters now ignore the targets for a while, if they fail to reach them after trying a while.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
