### ISSUE TITLE
[Wallet] Allow hosts to change where looted money is stored

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8729]
Would be ideal especially if it becomes a huge problem on some public server where players just start killing other players to accumulate marks.

The money could be transferred to the bank instead.

**Comment by 3e849f2e5c** [comment]
Changed grabbing bodies to move to campaign wallet in https://github.com/Regalis11/Barotrauma-development/commit/c72935a7e86d6120723bd6c27d51b8ab47dbe4fc need to implement setting in the next update so moving back to backlog

**Comment by 3e849f2e5c** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/8cdae33fd7181f4a5f7a68e731c0f041accb1110

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
