### ISSUE TITLE
Itemassemblies become misaligned after saving

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8737]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Saved itemassemblies are vertically misaligned by 1/2 of a grid square after saving them.
Horizontal alignment is fine.

**Steps To Reproduce**
1. Open the submarine editor
2. Place any item down
3. Save it as an itemassembly
4. Place the saved itemassembly next to the original item to compare.

**Version**
Windows 0.16.7.0

**Additional information**
Original items (left) vs. placed itemassembly (right)
![image](https://user-images.githubusercontent.com/67431770/161986421-6a6958f7-686c-4673-925f-827be1262cad.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ff400509e58345834e3794a424edb46af48b39ef

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Regalis11** [comment]
Not working, reopening https://github.com/regalis11/barotrauma/issues/9036

**Comment by Regalis11** [comment]
Hopefully fixed for good now https://github.com/Regalis11/Barotrauma-development/commit/5dc4a90ec250c99d0a0acd4356ca69b0918d5837

**Comment by Captain2137** [comment]
When would I be able to test it?

**Comment by Rokvach** [comment]
Tested, didn't spot any issues. Working correctly. Closing.
