### ISSUE TITLE
Screwdrivers/Wrenches from wrecks can't stack

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8740]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Screwdrivers/Wrenches from wrecks can't stack
Includes items found on corpses
Probably uses an older, non stackable version of these?

**Steps To Reproduce**
Open Berilia_Wrecked
Loot the cabinets
Can't stack screwdrivers

**Comment by Regalis11** [comment]
This is not a bug: no screwdrivers/wrenches (or other handheld tools) can be stacked.
