### ISSUE TITLE
The "name" parameter does not work when placed in a "structure" tag

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8741]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Version**
Windows Unstable v0.17.6.0

**Additional information**
XML in my text editor:
![image](https://user-images.githubusercontent.com/67431770/162062764-7be20974-49dd-47ee-a078-57980579e9e4.png)

Opening the console in the Submarine Editor:
![image](https://user-images.githubusercontent.com/67431770/162062784-26930b82-85b2-4810-9ea0-3efefcd24600.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86431afb9a28c49420398516232891d20a139fa3

**Comment by Rokvach** [comment]
Confirmed working by lordFrith, closing.
