### ISSUE TITLE
[Modding refactor] New game submarine list doesn't remove disabled subs

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8742]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
These subs shouldn't be here as I disabled them.
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/693c4171-e8d2-481e-ab71-d1288c2e5bb7)

**Steps To Reproduce**
Have a custom sub enabled and check the new game sub list, disable the custom sub and check it again

**Version**
0.17.6.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d9d667b76aad57f6f83d4627510785437496112a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
