### ISSUE TITLE
[Modding refactor] Don't show any server prompts when player is still on the process of downloading mods

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8745]
Currently while downloading mods you can get all types of server prompts, permission edits, round has started etc which the player downloading mods doesn't really need to see at that point and just slows the process down as you need to answer the prompts.

**Comment by Regalis11** [comment]
I'm not sure if I actually see a problem with these prompts. All you're doing is waiting anyway, so to me it seems like a good thing that you can read through the prompts and get an idea of what's going. I also don't see how it slows anything down: you're just waiting?

**Comment by Rokvach** [comment]
This isn't an issue when you are downloading mods from the host but if you choose the option to subscribe to the mods instead the prompts appear before the download starts, the whole process works a bit different from when you download mods from the host directlly. 

After clicking the bulk subscribe button
1. It brings you to the main menu
2. You get a prompt "The round has already started, please wait" its the only thing shown on the main menu
3. If you have any permissions the permission prompt opens
4. The downloading can finally start
5. If the host has any local mods installled or for some reason some of the mods can't be fetched from workshop you get the second download screen where you then download the local mods
6. Can't remember if it showed the prompts a second time
7. You are finally loading into the server

**Comment by Regalis11** [comment]
Ahh, right, I was just thinking of the prompt when downloading the mods from the server. In that case removing the prompts makes sense

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/fb0765fa16c9ae04d3a83749e1d6bd08bb969064

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
