### ISSUE TITLE
Adjusting lamp color when there's no power in the submarine causes the lamp to flicker each time you change the values

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8748]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Load up a sub in sub editor test mode and ask a bot to turn off the reactor, equip a screwdriver and adjust nearest lamps colors using the arrow buttons

**Version**
0.17.7.0
Branch: release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/9ada22532a0f080e592ae291d6798386907a8e4a

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c85af3f5bc87fea688715d87493871d753b7e8e

**Comment by Regalis11** [comment]
The fix is included in the current unstable, moving to QA Todo

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
