### ISSUE TITLE
[Unstable] Level editor doesn't spawn the same level/wrecks/beacon as in preview

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8749]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The level layout, wrecks and beacons you see when generating a level in `leveleditor` aren't the same as what you get once you test it.

It can spawn a different item at a different place entirely

Preview (custom beacon) near center
![image](https://user-images.githubusercontent.com/73229309/162464030-81a80e7a-1417-41ad-ba17-b7de70b63277.png)

Testing (regular beacon) on bottom left
![image](https://user-images.githubusercontent.com/73229309/162464150-9383eeb6-d3d9-482d-921d-dfee3ba72fb2.png)

**Steps to reproduce:**
1. Extract in Localmods
[BeaconCustom1.zip](https://github.com/Regalis11/Barotrauma/files/8452979/BeaconCustom1.zip)
2. Open in editor and save to make sure it properly enables the beacon
3. Open leveleditor, keep generating until a beacon appears
4. Test the level, the beacon sometimes doesn't match with the one shown in preview

**Version**
Unstable 0.17.7.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/adf6473449600b84180f98a163bae99e5a1fcdcf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
