### ISSUE TITLE
Blocky text in menu and missing texture ingame

### ISSUE THREAD

**Issue by Noodd090** [Regalis11/Barotrauma#8755]
One day ago Barotrauma started looking like this and I don't even know how it happened I have tried to look at the community discussions but there was only one post that mentioned it and wasn't helpful at fixing the problem saying to delete all mods and check for file integrity and if all else fails to uninstall the game and reinstall but none of those worked and I'm still having the problem I'm unsure what game version this is but its the current one since I bought the game two days ago. I have not tinkered with the files of the game or tried to mess with it in-game
![20220409201251_1](https://user-images.githubusercontent.com/103342229/162597072-e6fd6bc5-9198-4448-a136-ff862070e343.jpg)
![20220409201303_1](https://user-images.githubusercontent.com/103342229/162597078-bcaadf1d-a7e9-4b86-8212-87d33eb44a19.jpg)

**Comment by Regalis11** [comment]
That's strange, I haven't seen this kind of issue happen before. It's even stranger that a clean uninstall doesn't get rid of it.

I wonder if this could have something to do with your system? Which operating system are you playing the game on? Do you have some kind 3rd party "game optimization" software or anything similar installed, like GeForce Experience or GameBooster...?

**Comment by Regalis11** [comment]
No known steps to repro, closing
