### ISSUE TITLE
(Unstable) When you save a new sub in the editor the mod defaults to disabled

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#8756]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you create and save a new sub in the editor, it creates a new mod, but that mod is disabled so it doesn't show up in the load sub list.

**Steps To Reproduce**
1) Create new sub and save it
2) Restart the game
3) Open the Sub editor and click load
4) Freekout that your sub is not in the list (A little dramatization)
5) Go to settings then mods.
6) Find the sub in the long list of mods because you forgot what you called it
7) Enable it
8) Go back to the sub editor
9) Load your sub

**Version**
V0.17.8.0 Linux etc.

**Obligatory Unrelated Feature Request**
Make the Handheld Sonar not work when it is not under water.

**Comment by Rokvach** [comment]
Strange for me the subs I save seems to be enabled automatically, I don't restart the game after saving the sub however just save -> Check mod list and its there enabled. Could be that the restart in the middle messes it up for some reason.

**Comment by cshingle** [comment]
Hmm. I am trying to reproducing it now as well but am having no luck. I switched between stable and unstable several times before running into the issue. I think that the real issue was me reporting a bug at 4:00 AM as it seems to be working as intended for me now.
