### ISSUE TITLE
the husk genes will disapere

### ISSUE THREAD

**Issue by mastoon32** [Regalis11/Barotrauma#8757]
i have had i repeatable problem with the husk genes why you have hi psycosi it will randomly decide to dicaper alowing the husk to complte to 100 i dobbled checd with my host that there where no mods at all and ever time we relode the same save point it will disaper all around the same time

**Comment by mastoon32** [comment]
sorry for grammer

**Comment by mastoon32** [comment]
and spelling

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not reproduce this though. Tested by equipping husk genes in a gene splicer and giving myself the husk affliction, and waiting until the affliction gets to 90%, and then moving between levels and saving and reloading the campaign. The affliction still wouldn't go above 90%.

Did you notice how exactly the genes disappeared: did the genetic material disappear from the gene splicer, did the splicer disappear, or just the "husk genes" affliction?

**Comment by mastoon32** [comment]
the husk genes just disapered from the genes leaveing no damage

**Comment by mastoon32** [comment]
i also had a littile bit of phycosis

**Comment by mastoon32** [comment]
but i do think it kinda cool that the husk gene can breake becues of the husk
