### ISSUE TITLE
cargo falls through platforms

### ISSUE THREAD

**Issue by GenericGoose** [Regalis11/Barotrauma#8758]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Items spawned by cargo spawnpoints fall through platforms, even though they can be placed on them normally

**Steps To Reproduce**
Make a custom sub. Make a room with a platform in the middle, place cargo spawnpoint above it. Buy items.

**Version**
0.16.7.0
Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately wasn't able to reproduce this. Tested in this kind of a minimal sub:
![image](https://user-images.githubusercontent.com/14351070/163139597-e737411b-7aca-4962-bd4a-23a96a6f73ef.png)
![image](https://user-images.githubusercontent.com/14351070/163139937-a86f1eca-ea0a-4221-a5e1-430670deb9e5.png)

I wonder if this could have something to do with the way the cargo room or the spawnpoint is set up in your sub. Could you send us a screenshot of it or the sub file?

**Comment by Regalis11** [comment]
No know steps to repro, closing
