### ISSUE TITLE
Kill mission completes prematurely

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8760]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
You get a kill mission complete notification before even the target is fully dead
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0f631552-5a9a-4188-b2d4-78769765f685)

**Steps To Reproduce**
Do a monster mission, not sure if singleplayer has it. 

**Version**
Unstable 0.17.8.0

**Comment by Regalis11** [comment]
Could not reproduce in either multiplayer or single player. Did the monster actually stay alive, or was there just some delay between the popup and the healthbar going to 0?

**Comment by Rokvach** [comment]
I think the monster was dead, or at least didn't seem to do any attacks after the popup came up

You can observe the same thing happening in this video from Stable

https://youtu.be/jj8T2m9oB2U?t=182

**Comment by Regalis11** [comment]
It seems the health of the monster doesn't get updated client-side when it dies. So the issue doesn't seem to be that the mission completes prematurely, but that the health is displayed incorrectly. This also isn't an unstable-specific issue since it happens in that video.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/28efce5cc36921fd354697923c298e5423ab3ca8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
