### ISSUE TITLE
[Unstable 0.17.8.0] Failed to parse the string "GUI.ITEMQUALITYCOLORGOOD" to Color

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8761]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of the clients on my server kept getting this error while seemingly they weren't doing anything. 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6f276e49-a9b5-4d42-aee9-93ff370cd08f)

**Steps To Reproduce**
Unknown

**Version**
Unstable 0.17.8.0

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6945fa308a43b41d0f5b26f47531f9202e84725d

**Comment by Rokvach** [comment]
No sightings of this happening, seems to be working correctly. Closing.
