### ISSUE TITLE
[Modding refactor] Download getting stuck when trying to download hosts published mod

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8764]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am able to succesfully download all the other mods on the list but when the download reaches the hosts published mod it just shows 0 b / 0 b and doesn't move from there

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c997e9c9-b5be-4315-af58-b61178586027)

**Steps To Reproduce**
Have someone to host a server with a self published mod enabled and the local version disabled. 

**Version**
Unstable 0.17.8.0

**Comment by juanjp600** [comment]
Added some logging in https://github.com/Regalis11/Barotrauma-development/commit/6d544eef32cd17819fda553be552d6fb31cd6510, since I suspect that the issue was that a mod failed to compress on the host's end.

**Comment by Rokvach** [comment]
I have only seen this happens that one time, there hasn't been any errors about this either since the logging was added. Closing.
