### ISSUE TITLE
[Modding refactor] TempMods_Download folder only clears when you either host or join a server

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8766]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

### **This ticket can be closed if its intentional**

Mainly writing this ticket to see if clearing the folder should be done more aggressively, just wondering if it causes some possible issues if that folder isn't cleared when rejoining the same server (I could be wrong). The folder isn't cleared when you relaunch the game. 

**Steps To Reproduce**
Join a modded server and download the mods from that server. 

**Version**
Unstable 0.17.8.0

**Comment by juanjp600** [comment]
I don't see any issues with the current behavior, closing.
