### ISSUE TITLE
[Wallet] Vending machine steals your money if you have a exact amount on your wallet as one of the items costs

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8767]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Transfer 80 mk from bank and try to buy Ethanol from a vending machine

**Version**
Unstable 0.17.8.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8be0783881bcd5ac529723a565bdfb65d03f7956

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
