### ISSUE TITLE
[Wallet] Salary slider skips 5% - 10% - 15% values

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8768]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Adjust salary and notice that you can't set it to those percentages

**Version**
Unstable 0.17.8.0

**Comment by Kaillera** [comment]
It would also be nice if we can incorporate A/D or Left Arrow/Right Arrow to adjust the slider.

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@885d2e4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
