### ISSUE TITLE
[Wallet] Each time a player moves something to the shopping cart in store it shows a -0mk notification to every client

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8769]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Play multiplayer and have another client move items to the shopping cart and notice the -0mk notifications

**Version**
Unstable 0.17.8.0

**Additional information**
Doing this for too many times will cause a massive spam of "maximum packet size exceeded" errors on dedicated server console.

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c436dbced867d9d43970fcda47eb5c68f527043

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
