### ISSUE TITLE
[Colony] Z fighting

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#8770]
![image](https://user-images.githubusercontent.com/59519434/162640438-ef30c9cc-e51a-4d48-bdfa-cccc7ee207d4.png)

**Comment by Rokvach** [comment]
Happens with the flowers, listed this on the bigger colony ticket too but nothing was changed.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78541144d621d03a1cd38640295de4cd6fe76056

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
