### ISSUE TITLE
[Wallet] When a client disconnects the money is lost

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8771]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you disconnect from a server with money on your wallet none of the players can loot the money when they grab you and when you return to the server you have 0mk, so the money just vanishes.

I think its good that you can't loot the money from a disconnected character but the money should still be present once that character comes back. 

**Steps To Reproduce**
Host a dedicated server or join a server as a client, transfer some money to your wallet and then rejoin the server, notice that you have 0mk once you come back

**Version**
Unstable 0.17.8.0

**Comment by Rokvach** [comment]
Doesn't happen if you kill a disconnected player, but apparently then you need to regrab the body in order to loot it, if you kill the disconnected player while grabbing it.

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0c2cf1d46f4677408b6df93f33fd82b1cbd7761f

This appears to have been a visual only bug the marks were still on the character but it would display as 0 until the amount of money was changed

**Comment by Regalis11** [comment]
The commit seems to have caused a new issue:
1. Start a fresh campaign round
2. Move some money to your wallet
3. Start a new round
4. Notice that the money is gone from both the bank and your wallet

I don't think it's safe to call the new RefreshCampaignDatas method in UpdateWallets. It does a lot of things that should only be done at the end of the round, like reducing the character's skills and resetting their cause of death if they've died during the round and removing control of the current character if the client is controlling a monster.

**Comment by 3e849f2e5c** [comment]
Reverted the accidentally included changes in bugfixes branch

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
