### ISSUE TITLE
[Unstable 0.17.8.0] Wires are in wrong order

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#8772]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems the wires from the wire picking menu have changed order:
![image](https://user-images.githubusercontent.com/50582661/162641937-92d0e80c-35dd-4959-ab22-a40c2ed33426.png)

This is inconvenient, as the most common wires (blue, red, green) are now under the furthest keybinds (used to be 123, are now 456), or you have to scroll down.

**Comment by Rokvach** [comment]
This seems to be related to the issue we've had on other lists too where the list order changes, here's how my wires are listed

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/93d181ef-e940-40c5-be6e-fd1857479eb6)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bfc9742a16bfb32360f55c9b59d33ed87799b48a

**Comment by Regalis11** [comment]
Hopefully fixed now https://github.com/Regalis11/Barotrauma-development/commit/bfc9742a16bfb32360f55c9b59d33ed87799b48a
