### ISSUE TITLE
WiFi components linked to chat do not work properly multiplayer

### ISSUE THREAD

**Issue by Working-Joe** [Regalis11/Barotrauma#8773]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
During testing on the official testing server we ran into a few weird behaviours relating to WiFi components linked to chat. They seem not to work in a bunch of situations.

**Steps To Reproduce**
I do not know what causes this at the moment, I only have some observations from the testing campaign. There I placed a WiFi component that was linked to chat and on channel 0.  

With that the following happened:
-Connecting the WiFi comp to a terminal and then typing in chat did not make the messages appear at the terminal
-After a round change, all the sent messages did appear, also those which the component would have received when not connected to the terminal

-Connecting the WiFi comp to a lamp's set_color input and typing "1,0,0,1" in chat did not turn the lamp red.
-Connecting a terminal and than typing "1,0,0,1" _did_ turn the lamp red.

-Connecting the WiFi comp to a lamp's set_state input and typing "1" or "0" turns the lamp on and off.

**Additional information**
These issues are not present in the sub editor. Here the signals are received just fine.

**Comment by Regalis11** [comment]
Doesn't seem to be an issue specific to the unstable builds, happens in stable as well

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b7e1d0b1e05cf71e16f575e7c1f46f8cdca3f35

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
