### ISSUE TITLE
Munitions expertise does not double revolver ammo.

### ISSUE THREAD

**Issue by doornydew** [Regalis11/Barotrauma#8774]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
as the title says

**Steps To Reproduce**
try to double revolver ammo, it just will never happen

**Version**
latest, windows

**Comment by PokkeTigrex** [comment]
Munitions expertise explicitly states its for smg mags and shotgun shells and slugs. Security cannot make revolver rounds, its a captain exclusive talent.

**Comment by doornydew** [comment]
bruh, well fair enough then.
