### ISSUE TITLE
Tab menu visible/persists during loading screens

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8775]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the sub menu is visible and persists through loading screens

expected is for all windows (except maybe settings? including settings?) to be closed when entering loading screen I guess. Or at least not behind part of UIs

**Steps To Reproduce**
have (sub menu from) tab menu open at end of a round in campaign

**Version**
unstable 0.17.8.0

**Additional information**
![image](https://user-images.githubusercontent.com/5103517/162688840-b31f2afe-0bf8-442b-8ab3-f5e53de1ef00.png)

![image](https://user-images.githubusercontent.com/5103517/162688809-4ab3b124-4485-4eaa-9916-4d763d6a1a3c.png)

It went away during this part (new round loading?)

![image](https://user-images.githubusercontent.com/5103517/162689127-ce8d659b-0602-4a48-bf36-951beae6043f.png)

but then returned as the new round began

![image](https://user-images.githubusercontent.com/5103517/162689190-5c2ce7aa-6b83-4208-8828-038c0e7ec2be.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dbee64bbfbcc45f0ca423cdf4c4e0731532adcd5

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
