### ISSUE TITLE
Modded game locks up from buildup of hull events

### ISSUE THREAD

**Issue by DeltaNedas** [Regalis11/Barotrauma#8778]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Seems to be a build up of events that causes update times to spike, eventually reaching several seconds before the clients die entirely.

Notable event counts:
```
WARNING: event count very high: 1163
1. Barotrauma.Hull x664
2. Secure Locker (Medical Locker) (ID: 2184) x254 *this is from the EK Utilities mod*
3. Nuclear Reactor (ID: 123) x127
```

**Steps To Reproduce**
no clue sorry, all I know is that it was on an outpost with lots of mods and dead npcs

**Version**
Server: 0.16.7.0 windows 10
My client: 0.16.7.0 debian sid

**Additional information**
showperf of before i killed barotrauma:
![showperf](https://user-images.githubusercontent.com/39013340/162746775-3b4aca0b-74d4-4bdd-ac3f-b9057176d80b.png)

**Comment by Regalis11** [comment]
No known steps to repro, closing
