### ISSUE TITLE
[0.17.8.0] Multiplayer - There's no cooldown on how frequent a crew member can keep asking for money from the bank

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8779]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
There's no cooldown on how frequent a crew member in multiplayer can keep asking for money from the bank. They can pretty much just spam the vote over and over even if people keeps rejecting.

**Version**
0.17.8.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/628e1f7f86003e3cedc36fc7d2913be439ff2f1e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
