### ISSUE TITLE
[0.17.8.0] Crew Wallet - Marks gets sent to the bank when selling items from crew member's inventory

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8780]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Marks gets sent to the bank when selling items from crew member's inventory instead of their crew wallet. There's also no +## mark announcement when an item is sold.

**Version**
0.17.8.0

**Comment by cshingle** [comment]
This feels pretty similar to person account looting.
On public servers I would not want players to be able to sell items and get money for it because I feel that some people will abuse it by selling needed sub gear for personal gain. On private servers this would likely be less of an issue.

**Comment by cshingle** [comment]
> The thing is, you cannot sell stuff without permissions granted from the admin to begin with. There's no need to go through another loop of withdrawing from the bank which is locked behind another permission when you sold it in person.

Fair enough.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
