### ISSUE TITLE
[0.17.8.0] Multiplayer - Selling partial item did not remove from player's inventory

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8781]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So yesturday in Rokvach's official test server, I deconstructed a partially used coilgun ammo box (93 or 94%). I took the partial steel and lead up, along with a partially used coilgun ammo (93%) as well. When I sold them to a vender, it removed the coilgun ammo box from my inventory, but the steel and lead remained. I could no longer sell the steel and lead. I asked Udrakan to pick up the partial steel and lead from me, and he was able to sell it to the vendor, but the steel and lead remained in his inventory as well. We repeated it again with lordfrithe. I didn't checked if we received any money from it.

**Version**
0.17.8.0

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ffdd621c67d55dc998d937b19f66b845358e867

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
