### ISSUE TITLE
[Unstable] Faction/Outpost Icons in the Reputation menu are very small

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#8782]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Version**
Windows Unstable v0.17.8.0

**Additional information**
![image](https://user-images.githubusercontent.com/67431770/162786137-0f601c0a-79a9-4d18-a4b9-594d734d1fdf.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8912ca3a254364d880842ebb548590d70babaa93

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
