### ISSUE TITLE
items can be placed X flipped

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8783]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
facing left while placing held items X flips them

this looks funny for components and terminals

**Steps To Reproduce**
1. hold a regex component
2. aim to left of character
3. place component
4. enjoy your GER XE component!

**Version**
0.17.8.0

**Additional information**
lol

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
