### ISSUE TITLE
[Unstable 0.17.9.0] Winterhalter junction boxes catching on fire and breaking constantly

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8786]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
We started our first campaign round with Winterhalter and 5 minutes in all the junction boxes on the sub catched on fire, we didn't stress it in anyway which would lead to overvoltage. Had to repair the junctions constantly during the round. 

**Version**
Unstable 0.17.9.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e4124b2a13843f5be560bccbe2273cda94390bd2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
