### ISSUE TITLE
[Wallet] Clients can adjust salary slider visually

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8787]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The interaction of the salary slider isn't disabled anymore so clients can adjust it but it resets to the host defined value when they re-open the interface

**Version**
Unstable 0.17.9.0

**Comment by Regalis11** [comment]
Possibly caused by the same bug as https://github.com/regalis11/barotrauma/issues/8784 (the issue allowed the client to interact with anything that requires campaign permissions when there was no host present)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
