### ISSUE TITLE
docking port that isn't in use is locked at outpost levels

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8788]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the bottom docking port of the typhon2 on the test server was wiring locked during an outpost level

this docking port wasn't attached to the outpost, so I expected it to be unlocked wiring and usable

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.17.8.0

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b774589d3fdc2d74ac18168d9b5c7dc28b15bd54

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
