### ISSUE TITLE
AI pathing to hull damage on the Winterhalter

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#8790]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bots where trying to walk though the wall to reach the hull damage on the other side (see status monitor on the third screen shot). To fix them I had to give them a different order so they jumped down, then I ordered them to fix and hull again and they pathed correctly.
![20220411192745_1](https://user-images.githubusercontent.com/2231937/162859155-743a9201-fd42-49d4-a9f3-80dbed2a2202.jpg)
![20220411192901_1](https://user-images.githubusercontent.com/2231937/162859159-476cdc5e-08a0-4d9f-a002-ebf55728ff8c.jpg)
![20220411193033_1](https://user-images.githubusercontent.com/2231937/162859164-0a6d12ed-ee53-495c-9b4b-c79c4b14a2c4.jpg)
Second run
![20220411205257_1](https://user-images.githubusercontent.com/2231937/162863161-3fc05af9-a88e-4254-8f42-b1d76e756b89.jpg)
![20220411205300_1](https://user-images.githubusercontent.com/2231937/162863169-0aae9982-d0f0-4ce9-a577-8e0293f6515c.jpg)
![20220411205311_1](https://user-images.githubusercontent.com/2231937/162863177-152a6c21-8f35-422b-a8e1-cb098c1591e0.jpg)

I am guessing the fix is to move the waypoint back from the wall a bit, but honestly it is stranger to me that the AI works differently between the sub editor test mode and multiplayer.

**Steps To Reproduce**
I was unable to reproduce this in the sub editor test mode, only in multiplayer. I did it on the "Official Test Server".

To reproduce it the second time I ordered the bot to follow me to the wall where I put him on wait. I then used a plasma cutter to damage the hull then switched the bot to repair hull. He didn't go strait to the wall. He first jumps down, runs around the room then climbs back up where he gets stuck.

**Version**
v0.17.9.0 Linux

**Additional information**
Nope

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
