### ISSUE TITLE
Not a bug but feedback

### ISSUE THREAD

**Issue by TwentyOneEchoes** [Regalis11/Barotrauma#8791]
- [X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This isn't a bug, but I was told to bring feedback here by a moderator in the discord. I find the new, arbitrary limit on lights in general and shadow-casting lights specifically in the sub editor extremely binding. The number of lights on my sub has never been an issue, and I don't think I should be told what I can and can't do with my sub. The old warning was fine. Sorry if this sounds demanding; I didn't mean it to sound that way.

**Comment by Regalis11** [comment]
Thank you for the feedback!

It may be that you've optimized the submarine well enough to make it run with such a huge number of lights, but many submarine builders don't, and as a consequence a ton of custom subs have an excessive number lights that seriously hinders the game's performance (and tends to lead to said sub builders complaining about bad performance). You should also note that even if the submarine runs fine on your PC, a less powerful PC might have trouble running it.

I'd also argue that there's very rarely any need to go past the shadow-casting light limit: there's almost always ways to turn shadow-casting off or make them draw behind the submarine without any noticeable difference on the visuals.

However, if you really do want to keep such a high number of lights, we left in a small hidden feature to bypass it: if you enter "debugdraw" in the console before saving, the limits wil be ignored.
