### ISSUE TITLE
[Unstable] Power problem causing constant drain, even when not directly wired

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8793]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some items can cause constant drain on the grid even after being unwired (it's complicated)

The issue is two-fold; one with pumps (Torca is looking into it) causing drain when off but also a grid issue and machines still being connected even when unwired

**Steps To Reproduce**
Open [Seapnir.zip](https://github.com/Regalis11/Barotrauma/files/8472399/Seapnir.zip) in sub editor
Grab a screwdriver and check the supercapacitors and the red pump in the ballast:
![image](https://user-images.githubusercontent.com/73229309/162950025-d84c084c-9e30-4403-a1f8-c24c1a84b233.png)

You'll notice the supercaps are draining by default, even though the pump isn't on.

Try disconnecting the power wire:
-If the wire of supercap 1 is disconnected (or even REMOVED), both supercaps will keep draining
-If the wire of both supercaps are disconnected, it stops draining power

**Version**
v0.17.9.0

**Comment by Regalis11** [comment]
Fixed pumps consuming power in https://github.com/Regalis11/Barotrauma-development/commit/2c6d15af0e470bb9f7da1fb4669c289e4c525f27, still need to look into the disconnection issue

**Comment by Regalis11** [comment]
The disconnection issue doesn't seem to actually be a bug: even after you disconnect one of the capacitors, they're still in the same grid with the pump, because they're connected in the power input of the electrical discharge coil

**Comment by ubertpendragon** [comment]
V0.17.10.0
 
 Pumps have been fixed, but power still drains even if the wire is removed.

**Comment by Rokvach** [comment]
> but power still drains even if the wire is removed.

As Regalis mentioned above this isn't a bug, the pumps are still connected to the same grid through the discharge coil

So working correctly, closing.

**Comment by Regalis11** [comment]
Here's a quick sketch of what's happening here
![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/e01c906f-5e43-43bd-8a8f-a169bcb2d130)
