### ISSUE TITLE
[Unstable] Velonaceps Calyx Egg Syringe held the wrong way

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8795]
**Description**
When poking someone with a husk egg syringe, the player hits the victim with the non-needle end of the syringe. The syringe sprite seems to be flipped the wrong direction.

Husk Egg: 
![image](https://user-images.githubusercontent.com/91236493/163023999-94a0eb41-f6d9-43b4-8ecd-5006f45c0eaa.png)

Other syringes:
![image](https://user-images.githubusercontent.com/91236493/163024106-0c99bcab-5bfe-49df-afd1-74bb8a5cf0b1.png)

**Steps To Reproduce**
Spawn in some Velonaceps Calyx Eggs and hold them.

**Version**
Unstable V0.17.9.0

**Additional information**
I did some testing with other syringes and it seems that husk eggs are the only ones to have this issue, but I did not test every syringe.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e5b68ee0e59a5f918d0d6821969a9dd3c8ee37f

**Comment by Rokvach** [comment]
Tested, no issues. closing.
