### ISSUE TITLE
[Unstable] Head Movement While Aiming Looks Off With Melee Items

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8797]
**Description**
Aiming with items allows the player's head to follow the cursor, but it looks extremely off with items that do not follow the cursor like melee items. Their arms remain still while the head has free movement. When swinging the tool, the players head briefly stops looking at the cursor and goes back to its standard position, and then goes back to looking at the cursor. It's just so much stranger looking then if the head didn't follow the cursor when aiming with items like the syringe. 

Head following cursor:
![image](https://user-images.githubusercontent.com/91236493/163028452-6b4a3c3d-ac6e-43c1-92c0-d3c0b6e99ac1.png)

The head moving back to standard position near the end of the swing instead of following cursor:
![image](https://user-images.githubusercontent.com/91236493/163028174-ff497575-1303-486d-9dd3-63befc9f2923.png)
I know it doesn't look like I'm holding any items but there is a syringe in my other hand.

**Steps To Reproduce**
Equip a syringe, hold right click and move the cursor around. It looks strange when compared to revolver or welder. Swing the syringe   and you'll see how the head moves during the attack. 

**Version**
Unstable V0.17.9.0

**Additional information**
Holding a ranged weapon that follows the cursor in your other hand seems to prevent the head from moving back to its default position.
I'm not fully sure how much of this is just a bug, I guess its maybe more of a feedback post, but the movement certainly feels wrong.

**Comment by itchyOwl** [comment]
Fixed in Regali11/Barotrauma-development@2fcd518.

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
