### ISSUE TITLE
Sub hulls not linked

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8798]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'll keep adding more

Herja
![image](https://user-images.githubusercontent.com/73229309/163058713-25796b1f-d019-4483-a0f4-3a35f4d0639a.png)

Humpback
![image](https://user-images.githubusercontent.com/73229309/163059538-bd000a4b-e915-45a3-a6df-f9701913f044.png)
![image](https://user-images.githubusercontent.com/73229309/163059836-aabaf3f5-473b-421c-98d0-fef4a02dc7fc.png)

Kastrull
![image](https://user-images.githubusercontent.com/73229309/163060434-3cc77e2b-91bc-4cac-aa92-c8ffe50daec5.png)

Orca2
![image](https://user-images.githubusercontent.com/73229309/163062426-0203945f-931a-42a6-bd60-0feb94ba6e1d.png)

Remora
![image](https://user-images.githubusercontent.com/73229309/163063873-d18da524-5aaa-4930-b6f1-adf4772f54d6.png)

Winterhalter
![image](https://user-images.githubusercontent.com/73229309/163079029-945ef52e-c456-4d83-b4f4-b5ce44d63023.png)

**Comment by danielasteljoki** [comment]
Linked Herja's docking port hulls in b7dc7b5.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
