### ISSUE TITLE
 Typhon2 hardpoint location too close to docking port

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8799]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
 If you buy a new turret for the Typhon2, it'll be on top of whatever you dock in the bottom-left docking port

![image](https://user-images.githubusercontent.com/73229309/163078288-e2005530-3513-40fe-b5ca-5161a619009d.png)

#8512

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
