### ISSUE TITLE
Pushing/Pulling players while holding on to them / Selectable body parts

### ISSUE THREAD

**Issue by GGSnipa** [Regalis11/Barotrauma#88]
Being able to pull players closer to you and "aim" them by holding the right mouse button would add much more control to the dragging system, making it easier to save drowning players as well as pulling passed out allies into a tight airlock.

Furthermore, selecting which body part to drag (the hands, under the arms, legs) can make it easier on a crewmember to drag someone somewhere with less flopping around.

As an expansion to this, injecting yourself with hyperzine would allow you to effectively throw crewmen around by pressing left click, potentially saving or causing harm to them. Holding them by the torso/under the arms would also grant you a human meat shield, innovative and totally ad-friendly.

**Comment by Crystalwarrior** [comment]
#101 ayy

**Comment by GGSnipa** [comment]
ayyyyy

**Comment by Regalis11** [comment]
Added in dde320b
