### ISSUE TITLE
Treat All only treats one crew member at a time

### ISSUE THREAD

**Issue by ParadoxSong** [Regalis11/Barotrauma#8800]
- [X] I have searched the issue tracker to check if the issue has already been reported.

There's no treat-all button for the whole crew, which seems like a huge oversight. 

**Version**
.17.9.0

**Additional information**
The most common use case for the medical clinic is unaddressed - multiple crewmembers, multiple injuries.

**Comment by Rokvach** [comment]
- [ ] Disable Treat all button when there's nobody to treat
- [ ] I'd change the "Treat All" text to be more specific as there is already a Treat All button and figuring out the difference between those buttons might not be clear. for example "Treat Everyone" and maybe even "Treat Afflictions" (Not as necessary)

**Comment by 3e849f2e5c** [comment]
Disabled the button in https://github.com/Regalis11/Barotrauma-development/commit/4fb8ac82f0625f6769810ef5d7b85a9e80edd02e

Not sure about the treat all text tho

**Comment by Regalis11** [comment]
Changed the text in https://github.com/Regalis11/Barotrauma-development/commit/eeb3d0145d3c6a524667d0438241b8d2a012f97a

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
