### ISSUE TITLE
Medical clinic UI truncates affliction descriptions too eagerly

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8801]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image.png](https://images.zenhubusercontent.com/5c8f770fd06a4e6d359ecd4c/55247a0c-0442-4329-853e-e70bf055cca7)

**Version**
Any

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4de201496bcc63517f79dbbd7a09041b21b04164

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
