### ISSUE TITLE
[Wallet] When creating a new character the money you had in your wallet vanishes

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8802]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I think the money should be transferred into the bank as players wont have access to the corpse during level transition so they can't loot the money back. The player who is going to change character is going to do it by themselves manually once they learn about it anyway so its just better to have it automated. 

**Steps To Reproduce**
Start multiplayer campaign, give your character some money from the bank, in Tab menu character tab create a new character and load into the next round, notice that the money you moved is gone. 

**Version**
0.17.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67234f5b4eb77a6ecd056b4bda70ab52e7e30376

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
