### ISSUE TITLE
[Tutorials] Order engineer to operate a reactor part in captain tutorial fails because the order is assigned to a wrong class

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8804]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Operate reactor order is given to a medic rather than engineer when you give the operate a reactor order without specifiying the character the order is given to. 

Works correctly if you give the order specifically to the engineer.

**Steps To Reproduce**
Play the captain tutorial and use the global command wheel to give orders, notice that when you try to give the operate reactor order either from the shortcut or from the actual order it gives that order to the medic rather than engineer, when the order is given to the medic the order automatically dismisses itself. 

**Version**
0.17.9.0
Branch: bugfixes

**Comment by Regalis11** [comment]
Could not reproduce

**Comment by Regalis11** [comment]
The follow order needed to be dismissed before giving the operate reactor order for this to happen. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/537f341c831922c655a2be1b60c6a9f4fb7cabb7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
