### ISSUE TITLE
Automatically healing burns cause problems in the medic tutorial

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8805]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Now that burns heal automatically, some parts of the medic tutorial don't always work as intended: treatment suggestions stop working after the burns have healed enough, and some segments of the tutorial get skipped entirely if the player waits long enough for the burns to heal completely.

**Steps To Reproduce**
1. Start the medic tutorial
2. Wait a few minutes before starting it, or play through it pretty slowly: notice that there's no treatment suggestions for the players whose burns have dropped below 5%, and that some of the characters asking for medical assistance have no afflictions.

**Version**
v0.16.x.x

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e262ba22d4bbbd07b11abbc06eaa84557346e6fa

Note that I also cherry-picked a commit from dev that made this much simpler and cleaner to fix (due to the affliction reductions being simple properties that can be edited on the fly, instead of them being used to hack together a status effect XML and add it to the character when it's being initialized): https://github.com/Regalis11/Barotrauma-development/commit/eb5a4d309b3e1776196440c99d5a26484c130d76

Even though I tried to test that commit thoroughly, it could be that I missed something, so would be good to go give the things it affects another test:
- Status effects defined in characters
- Monster's health regeneration
- Burn reductions
- Bleeding reductions
- Health regen when eating

**Comment by Rokvach** [comment]
I did notice that burns aren't healing outside of the tutorial

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
