### ISSUE TITLE
[Medical UI] Descriptions for medical afflictions assume the worst

### ISSUE THREAD

**Issue by SeaverBeaver** [Regalis11/Barotrauma#8806]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
(Most likely low priority)
The descriptions for most non-poison afflictions are indicative of the worst and most severe forms of the affliction. Burns, for example, will always be described as 2nd-3rd degree even if its only -1 vitality. Blunt force trauma is another good example, even if you only fall down a ladder, the description says that the patient is in a great deal of pain and you suspect a bone might be broken. This has caused some confusion among newer medics I've played with, so much so that i've made this report.

**Steps To Reproduce**
It's the medical UI. 'Nuff said.

**Version**
Release Build

**Additional information**
Having the description of the injury change based on the severity of it, <50%, >50%, would clear up the confusion.

Burns:
< 50% - The skin is red and irritated, and the patient is in pain.
> 50% - The skin is leathery and covered in blisters, and large patches have started to peel off. The patient is in a great deal of pain.

Blunt Force Trauma:
< 50% - The skin is bruised, and is starting to swell.
> 50% - The area is an ugly shade of purple, and apparently very painful to touch. You suspect a bone might be broken.

Radiation Sickness:
< 50% - The patients skin is red and blistering, and they feel queasy. 
> 50% - The patients skin is leathery and peeling off, and they are vomiting intermittently. 

These are just a couple examples of the "worst offenders." I'm no doctor, but i've tried to get them as accurate as possible.

Another point that was brought up is that some afflictions list bleeding as a symptom when they themselves don't cause bleeding. Bite Wounds and Bullet Wounds describe the injuries as bleeding, but when bandaged, there is no bleeding.

Overall, not hugely important, but a good QOL thing for newer players.

**Comment by SeaverBeaver** [comment]
Ugh, formatting. The grey text are the afflictions with greater than 50% severity.

**Comment by Regalis11** [comment]
Support for this + some example texts implemented in https://github.com/Regalis11/Barotrauma-development/commit/3c6ce18e8192375879b3818665986400ee67191c

Doc for writing the rest of the texts: https://docs.google.com/document/d/1eyxSkWxofofI_8BysShwEJXUpTSIxyEA9qvLykcZk90/edit

**Comment by Dynamoon** [comment]
Added variants to all those marked texts where either "self" seemed missing or I could achieve grading. Would like feedback https://docs.google.com/document/d/1eyxSkWxofofI_8BysShwEJXUpTSIxyEA9qvLykcZk90/edit#

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
