### ISSUE TITLE
Tutorial completion isn't saved

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8807]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Complete a tutorial or few
2. Relaunch the game
3. Tutorials no longer appear to be completed

**Version**
v0.17.x.x

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3a9c7583459f228eb5b2ec077aeb15f67065b01e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
