### ISSUE TITLE
Autopilot conflicts with VELOCITY_IN 

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#8809]
- [*] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When autopilot is enabled, vectors to Velocity_IN get mixed with autopilot results

**Steps To Reproduce**
Connect a memory component with "50,50" to VELOCITY_IN of navigation console. Enable autopilot and direct it to go somewhere. When you read the Velocity_X_OUT or Velocity_Y_OUT pin, it won't read 50 but more like 45 to 55, depending on where the autopilot is requesting to go. It seems to add a small amount of the autopilots request to the velocity_in amount. 

I would expect for velocity_in to either completely override autopilot, or for autopilot to completely override velocity_in, not for the two signals to get 'mixed'

This problem is made more annoying by the fact any time you leave the nav console on manual, some 'helpful AI' will see to it to set the thing to automatic unless you make them explicitly ignore the nav console. 

**Version**
V0.16.7.0

**Comment by Tsunder** [comment]
AI don't touch the helm except for captains w/o orders

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
