### ISSUE TITLE
Died of barotrauma while having husk genes + infection

### ISSUE THREAD

**Issue by Bolt-Lee** [Regalis11/Barotrauma#8810]
- [Yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was going from gunnery in the winterhalter to the command room of it, I had husk & hammerhead matriarch combined together with the debuff of glass jaw, when I got into the command room I died almost immediately of barotrauma, I am unsure how, we have no medics that could've done this and no information on logs about it aside from the fact I died of barotrauma.

**Steps To Reproduce**
Have husk genes with final stage of husk infection... at most that's all I know

**Version**
v0.16.7.0

**Additional information**
Im not to unable to get much information on it, it was just sudden. About halfway into the 4th biome into the abyss. Ill try to reproduce if possible, but im just lost

**Comment by Regalis11** [comment]
The husk infection doesn't make you entirely immune to pressure - the pressure in the abyss is still enough to kill you.
