### ISSUE TITLE
[Tutorials] Security Officer tutorial Mudraptor always spawns looking weird

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8812]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e1bc16df-e541-4abd-9ee7-e7b0b9dffaa5)

**Version**
0.17.9.0
Branch: bugfixes

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf355825641febd52e531dc67de53d3fb1633f15

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
