### ISSUE TITLE
Power Rework - Talent "Let It Drain" don't work

### ISSUE THREAD

**Issue by Abkim27** [Regalis11/Barotrauma#8813]
**Description**
Fabricators, pumps, etc. doesn't work without power, if you tinker it with talent "Let It Drain". I think it's because of Power Rework.

**Steps To Reproduce**
Give mechanic experience and take tinkerer, mass production(optional), let it drain talents. Then without power tinker fabricator or pump, and try to make them work(start doing smth in fabricator or make pump start pumping). Fabricator or pump wouldn't work, because of not having power.

**Version**
Windows V0.17.9.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd6011221b31e6d6e281d7b6c146c0861734ad00

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
