### ISSUE TITLE
Submarine price not deducted from starting funds in mp campaign

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8814]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you choose a sub that costs more than the starting funds in the multiplayer campaign (8500 mk), the price doesn't get deducted at all (meaning that you get to start with the whole 8500 mk, instead of the 500 mk "minimum starting funds").

**Steps To Reproduce**
1. Start a multiplayer campaign with e.g. Azimuth
2. Notice that you have 8500 mk in the bank

**Version**
v0.17.x.x

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a5ae02d1100cda944d41caf085af5ff5fd726e74

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
