### ISSUE TITLE
[Unstable] Ducts don't produce water "splashes" between hulls

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8815]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When water flows through an horizontal gap from hull to hull, it doesn't produce water splashes
Water from outside -> hull does

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/73229309/163430979-4006949b-4fbc-4172-ae0a-6369acb4d14a.png)
![image](https://user-images.githubusercontent.com/73229309/163431052-890e5a08-f046-4466-a295-c1f3c3d297cd.png)

**Version**
Unstable V0.17.10.0

**Comment by ubertpendragon** [comment]
I made the mistake of linking some hulls which made the splash disappear

Ducts however should produce those sprites but don't

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.15.0, works correctly, closing.

Note: this was fixed in #7496 - but just in case checked again using gap's between hull's (without linking them) and duct blocks, water splashes appear as expected now just fine regardless if it is a hull or gap, so long as the hull's are not linked.
