### ISSUE TITLE
herja, barsuk, and winterhalter lack ambient lighting

### ISSUE THREAD

**Issue by internet-person** [Regalis11/Barotrauma#8818]
ive noticed that the new(er) submarines are entirely lacking ambient lighting, as the other submarines do have ambient lighting i assume this is unintended and am reporting it.

![winterref](https://user-images.githubusercontent.com/81054892/163514144-f460c3c0-8322-463a-9353-8f337d625a24.PNG)
example picture of winterhalter with the power off, no ambient lighting.

**Comment by danielasteljoki** [comment]
Addressed in 5801475

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
