### ISSUE TITLE
[Wallet] Wallet info in player portrait is shown outside of campaign

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8819]
This is from mission mode

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/67ae20e0-d548-4f0a-8be4-3c06fe0705af)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/439e5e36d5f2c4a2086dff1e775d4c27f7f36bdf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
