### ISSUE TITLE
workshop sub/files path shows full path, exposes client's user

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8820]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The client's user is shown when saving/selecting subs

![image](https://user-images.githubusercontent.com/5103517/163623386-4a715e58-2350-454f-8d40-6146451c8088.png)
![image](https://user-images.githubusercontent.com/5103517/163623475-f23abdcd-4406-485d-9d40-10ed4b59e90c.png)

**Steps To Reproduce**
save a workshop sub

**Version**
0.17.10 unstable

**Additional information**

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/97981e9597882ef6aeb6686f672fcd84b478250d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
