### ISSUE TITLE
sub editor takes a long time to open a sub

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8821]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Opening subs can take 5-10 seconds, and freezes barotrauma while doing so. I feel like this is longer than in 0.16 stable

counted with dugong.

potentially related to having lots of mods (subs and otherwise?) installed/enabled.

**Steps To Reproduce**
1. enable 30+ mods?
2. open dugong in sub editor

**Version**
0.17.10 unstable

**Additional information**
after opening/closing dugong several times it seems to be faster

**Comment by Regalis11** [comment]
Addressed to some extent in https://github.com/Regalis11/Barotrauma-development/pull/3316

**Comment by Rokvach** [comment]
There is still a freeze but the loading time seems to be shorter when comparing to stable. So addressed to some extend at least and working correctly. Closing.
