### ISSUE TITLE
saving workshop sub "loses" the preview image after the first save

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8822]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**
1. load workshop sub in editor
2. save sub (1x)
3. open save sub menu again
4. preview image is GONE, to atoms

**Version**
0.17.10

**Additional information**
Add any other context about the pro

https://user-images.githubusercontent.com/5103517/163624228-0b49462c-9e70-4f8c-b6c4-5d4ef4f5234a.mp4

blem here.

**Comment by Tsunder** [comment]
localmods/subname lost preview image as well

**Comment by cshingle** [comment]
I don't think this is a new bug. I have seen this happen a bunch in 0.16.x as well.

**Comment by Tsunder** [comment]
the symptom yeah, but this can be reliably produced

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d230113ec69ce03c2e90841977c8b7fd3d6fee9d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
