### ISSUE TITLE
vanilla subs emergency lights are shadow casting

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8823]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
since some version ago, emergency lights were set to non-shadow casting by default for performance reasons

however, this change was not implemented on the vanilla subs (azimuth etc).

**Steps To Reproduce**
1. vanilla subs emergency lights are shadow casting
**Version**
0.17.10
**Additional information**

**Comment by Regalis11** [comment]
This is intentional. The numbers of shadow-casting lights in vanilla subs are low enough that we can afford to keep shadow-casting enabled on many of the emergency lights that would otherwise shine through walls.
