### ISSUE TITLE
Server name text position breaks when editing the middle of it

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8824]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
the text gets pushed to the left when editing a server name that was already put into the field (i.e., the "previous server name")

https://user-images.githubusercontent.com/5103517/163626856-1778f347-696d-43f2-b7c6-549844946b2a.mp4

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**
I don't know

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/44af13b745d1fa76bfa2e5861112f9a7f502f4e8.

**Comment by Regalis11** [comment]
The fix seems to have caused some text alignment issues:
![image](https://user-images.githubusercontent.com/14351070/163790021-5440a399-6024-412f-9564-d4e591e6ae3c.png)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ef05b31aeffa8b6f7bfea4d779073dda5bc3488

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
