### ISSUE TITLE
[Unstable 0.17.10.0] Purchased displays spawn attached to wall

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8825]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you purchase displays you need to detach them from wall

**Version**
Unstable 0.17.10.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0350851154a5ae9c555fbb7e48bcfc50ea981834

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
