### ISSUE TITLE
[Unstable] Relay Can be overloaded condition

### ISSUE THREAD

**Issue by Torca2001** [Regalis11/Barotrauma#8826]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Relays marked as "Can be overloaded" will die when they meet their overload threshold and cause the grids to disconnect and won't output power. This is a problem as relays can't be repaired and generally screws with the grids with no indication the relay has broken.

**Steps To Reproduce**
Loaded up humpback
Connect relay to grid and attach a load like a lamp
Set relay "Can be overloaded" to true and lower the overload condition to make it easier
Overload the reactor above the overload condition
Observe relay behaviour

**Version**
Windows Version 0.17.10.0

**Additional information**
The problem is at line 144 of the [Relay.cs](https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/RelayComponent.cs#L144)
There is no check for repairable and thus on overload the relay condition is set to 0
Compared it to stable power code and they both do the same thing, but the power rework will no longer consider the relay as valid as it is viewed as "dead"

Also if you attempt to reconnect the wires, if the device only has one connection in then the connection.cs grid shortcut is used and allows for an invalid connection to be made.
At line 288 in [connection.cs ](https://github.com/Regalis11/Barotrauma/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/Connection.cs#L288)
There is no condition check so a fix could be changing the if statement to
`if (Powered.ValidPowerConnection(this, otherConnection) && item.Condition > 0 && otherConnection.item.Condition > 0)`
Or maybe this if check could be implemented into the ValidPowerConnection function

**Comment by Regalis11** [comment]
Thank you for the report, I'm glad you spotted this! Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9a75a734afa3a53f7e80ec6d297a388bdfed18ff

**Comment by Torca2001** [comment]
Gotta thank Astraltor for pointing out there something being wrong with a sub utilising heavy amount of relays otherwise I probably wouldn't have noticed it.

**Comment by Rokvach** [comment]
Tested by Torca, working correctly, closing.
