### ISSUE TITLE
[Unstable] Alien Generator

### ISSUE THREAD

**Issue by Torca2001** [Regalis11/Barotrauma#8827]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Alien generator when provided with a power cell doesn't output power.

**Steps To Reproduce**
Connect up a alien generator to a grid
Provide the generator with an alien power cell

**Version**
Windows 0.17.10.0

**Additional information**
This can be fixed by change the alien generator's xml file and moving the line for the powercontainer above the lightcomponent.
This is due to the behaviour of the GetComponent<Powered>() function returning the first occurence of a powered class and thus the UpdatePower function calls the code for the light instead of the power container of the generator.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/429e40ce94c9a34d8013fb240927ace0b243d056

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
