### ISSUE TITLE
Cargo missions can place Crates into containers flagged as Non Interactable

### ISSUE THREAD

**Issue by LuleNZ** [Regalis11/Barotrauma#8828]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.
(using search word "Cargo")

**Description**
Cargo missions can put cargo into containers that are set to be "Non Interactable"
(Tested with Unit Load Device in Multiplayer Campaign, don't know if it applies to the Crate Shelf)

**Steps To Reproduce**
1. Add a Unit Loader to a submarine (via sub editor) and set the "Non Interactable" flag on it.  
2. Remove enough other Cargo Shelves / Unit Loaders to be sure that a Cargo mission will need to use storage inside the above placed object.
3. Start a multiplayer campaign and take a large enough Cargo Mission to ensure that other Cargo Shelves / Unit Loaders won't be able to take all of it

**Version**
Windows (Steam) v0.16.7.0 Hotfix

**Additional information**
If  the unit has been resized, it can look very silly when Cargo is put into it.
It throws off intended cargo capacity
If the unit is outside a Hull object, it can still have cargo put into, which will make you fail the mission.

**Comment by BlackMoons** [comment]
Can I add that I would really love an editor option for 'Interactable' cargo shelfs to not automatically load cargo from missions?

It causes issues when cargo shelfs in ballast tanks are used in cargo missions for storing sodium in non-waterproof containers. (Security materials transport). I guess ignoring cargo shelfs in hulls marked as 'wet', when starting this one mission might also be a solution?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3ed0b18e08f8ea5de45c50a19a1948be5273afb
