### ISSUE TITLE
GameAnalytics could not be initialized due to an error

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#8829]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Version**
0.16.7.0, release windows, branch release, revision aa4c852c2c

**Additional information**
**Is this some kind of IP blocking by your side?**

After a few seconds on the starting screen I receive an error message in debug console:

- Error while connecting to master server { System.Net.WebException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера. Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера.
-  ---> System.Net.Http.HttpRequestException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера.
-  ---> System.Net.Sockets.SocketException (10060): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера.
-    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
-    --- End of inner exception stack trace ---
-    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
-    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
-    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
-    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
-    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
-    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
-    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
-    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
-    at System.Net.HttpWebRequest.SendRequest()
-    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
-    --- End of inner exception stack trace ---
-    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
-    at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
-    at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback) }
 
**I connecting from a public static IP address. No one of my browsers can't open the page 'barotraumagame.com'. Tracing results below:**

- Microsoft Windows [Version 10.0.19044.1620]
- (c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

- C:\Users\Butuzov_DP>**nslookup barotraumagame.com**
- ╤хЁтхЁ:  dlinkrouter.Dlink
- Address:  192.168.0.1
- Не заслуживающий доверия ответ:
- ╚ь :     barotraumagame.com
- Addresses:  
-  2a06:98c1:3120::2
- 2a06:98c1:3121::2
- 188.114.96.2
-  188.114.97.2

- C:\Users\Butuzov_DP>**tracert 188.114.96.2**
- Трассировка маршрута к 188.114.96.2 с максимальным числом прыжков 30
-   1    <1 мс    <1 мс    <1 мс  dlinkrouter.Dlink [192.168.0.1]
-   2     1 ms     1 ms     1 ms  10.5.0.1
-   3     2 ms     1 ms     1 ms  10.244.14.118
-   4     1 ms     1 ms     1 ms  188.123.255.45
-   5     7 ms    10 ms     3 ms  62.117.100.21
-   6    39 ms    39 ms    46 ms  62.117.100.8
-   7    40 ms    40 ms    43 ms  de-cix-frankfurt.as13335.net [80.81.194.180]
-   8    52 ms    40 ms    39 ms  172.70.248.3
-   9    39 ms    39 ms    41 ms  188.114.96.2
- Трассировка завершена.

- C:\Users\Butuzov_DP>**tracert 188.114.97.2**
- Трассировка маршрута к 188.114.97.2 с максимальным числом прыжков 30
-   1    <1 мс    <1 мс    <1 мс  dlinkrouter.Dlink [192.168.0.1]
-   2    48 ms    56 ms    29 ms  10.5.0.1
-   3     4 ms     2 ms     2 ms  10.244.14.118
-   4     2 ms     2 ms     1 ms  188.123.255.45
-   5    16 ms    84 ms    21 ms  62.117.100.21
-   6    39 ms    39 ms    39 ms  62.117.100.8
-   7    47 ms    40 ms    40 ms  de-cix-frankfurt.as13335.net [80.81.194.180]
-   8    40 ms    39 ms    39 ms  172.70.244.3
-   9    39 ms    39 ms    39 ms  188.114.97.2
- Трассировка завершена.

**Comment by Regalis11** [comment]
Thank you for the report!

The game doesn't try to connect to barotraumagame.com when initializing GameAnalytics, but to gameanalytics.com. Since both pages seem to be up and reachable (https://www.isitdownrightnow.com/barotraumagame.com.html and https://www.isitdownrightnow.com/gameanalytics.com.html), I suspect that there is some kind of an issue with your connection. Both pages use CloudFlare, and following the Russian invasion to Ukraine, CloudFlare has implemented some sort of limited measures to restrict access to their network from Russia. Another explanation could be that the connection has been blocked from Russia's side, since Russian authorities have apparently implemented a series of blocking actions against websites and operators recently.

**Comment by Xardion495** [comment]
Understood. Thanks for the answers. I suspected something like this. I just using CloudFlare as a default DNS-service (and Google as second) on my router. Your words gave me an idea to switch a default service to internet provider's DNS. Now it's working, so and main site.
