### ISSUE TITLE
Wifi component to state+proximity on drone/shuttle dock when docked issue

### ISSUE THREAD

**Issue by JimmySlickD** [Regalis11/Barotrauma#8830]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When connecting wifi component to state and/or proximity output on drone/shuttle dock (when the drone is docked) causes docking/undocking UI to appear on navigation terminal (ui does nothing when clicked as navigation terminal is not connected to shuttle terminal. 

**Steps To Reproduce**
reproduce by:
Dock -> Signal component -> Wifi component (to chat, 0000)

**Version**
Current 0.16.7.0, win 11, intel 12700k, 2080ti

**Additional information**
no

**Comment by JimmySlickD** [comment]
Why this is important: say you want an automated chat message when drone is about to dock, is docked or just undocked, this bug makes it impossible

**Comment by Regalis11** [comment]
I unfortunately couldn't reproduce this one either. Tested with a modified version of Kastrull (removed the wires from the "toggle_docking" output of the shuttle navigation terminal to prevent the docking button from appearing and added a circuit that outputs the state of the docking port to the chat as you described), and the docking button doesn't show up.

[Kastrull.zip](https://github.com/Regalis11/Barotrauma/files/8519372/Kastrull.zip)

**Comment by JimmySlickD** [comment]
here is bug reproduced with this wire setup:
![image](https://user-images.githubusercontent.com/38655363/164187335-4902ebe5-e1d1-48a3-8cf2-c42c79d092a8.png)
![image](https://user-images.githubusercontent.com/38655363/164187434-6dfbb77c-db98-4d1b-b9c8-db4cf24a9fa6.png)
removed proximity and stateout on dock and it is fixed:
![image](https://user-images.githubusercontent.com/38655363/164187702-be897e40-5875-4a65-969b-1231d1eec0b4.png)
![image](https://user-images.githubusercontent.com/38655363/164187653-33f8279a-bc02-40bd-9f47-0ba23a0b7e69.png)
[Riftback #8830.zip](https://github.com/Regalis11/Barotrauma/files/8519828/Riftback.8830.zip)
maybe there needs to be more wires connected somewhere to promote this bug, i am not sure - i have however tried to mess will so many wires and my testing only found these two to be at fault

**Comment by Regalis11** [comment]
Thank you for the extra info! This seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/8447
