### ISSUE TITLE
Venture shuttle is outdated/broken (includes fix)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8840]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Venture has several big issues:
Airlock sinks the sub, inaccessible ballasts, bad hulls, bad LOS/shadows, bad waypoints, doors not reaching walls, power consumption

I fixed that so you don't have to
[Venture_fixed.zip](https://github.com/Regalis11/Barotrauma/files/8506444/Venture_fixed.zip)

Before
![image](https://user-images.githubusercontent.com/73229309/163828181-f3d82280-606b-4ecc-9cf2-f37a38c0638c.png)

After
![image](https://user-images.githubusercontent.com/73229309/163828255-d50cba43-35d3-4eb6-b501-de095032135e.png)

![image](https://user-images.githubusercontent.com/73229309/163826464-047e7fc1-e991-498d-9cd5-2c6e5ae7c749.png)

**Comment by danielasteljoki** [comment]
Addressed in 5801475

**Comment by Rokvach** [comment]
Should this door have a button? I thought the whole advantage of using venture was that you can safely leave the shuttle whenever you want
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/07bfa5ee-959d-4e0e-8152-e25b568a301f)

**Comment by danielasteljoki** [comment]
Well not the _whole_ advantage but yes. Fixed in 6a1d756.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by ubertpendragon** [comment]
The waypoints do not connect, bots can't get up/down the bottom exit
![image](https://user-images.githubusercontent.com/73229309/169698848-bc147e52-0c6e-48c0-9eee-6a41255b0aa8.png)

The doors don't touch the walls (LOS issues)
![image](https://user-images.githubusercontent.com/73229309/169698941-b39a2be5-ba34-4893-947c-1e0eecee2f40.png)

Same at the top docking port
![image](https://user-images.githubusercontent.com/73229309/169698989-fd53bf5e-4269-4421-904f-40026ec395c1.png)
