### ISSUE TITLE
Selkie using the wrong NBL + bad hulls

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8842]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Selkie using the wrong NBL 

Also, hulls are bad
![image](https://user-images.githubusercontent.com/73229309/163834046-efe6421e-f05f-48f1-aa9b-adc5fc64280e.png)

#7154

**Comment by Ek-Videogames** [comment]
Take into consideration that the collision boxes don't even match up with the visual sprites on most shuttle shell parts.

- and the latter issue isn't really fixable unless you triple the amount of hulls, then you end up with the physics problems.

**Comment by danielasteljoki** [comment]
Addressed in 5801475

**Comment by Rokvach** [comment]
No issues, closing.
