### ISSUE TITLE
[Unstable] Discharge coil 0 draw on grid

### ISSUE THREAD

**Issue by Torca2001** [Regalis11/Barotrauma#8845]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Discharge coil that is wired directly to the grid with no supercapacitors will draw 0 power if the discharge coil is triggered through components.

**Steps To Reproduce**
I've had difficulty trying to reproduce from scratch, but it consistently happens on UberPendragon's Sub
[Winterhalter2Shuttle.zip](https://github.com/Regalis11/Barotrauma/files/8509301/Winterhalter2Shuttle.zip)
(Renamed the .sub file to .zip)
To use the sub simply spawn in and go to the right and press the blue button
This will discharge the coil whenever the light is blue.
There are two text displays above you displaying power and load of the nearby junction boxes.
The discharge coil is wired directly to this grid.
Pressing the button you will notice there to be no change in load(Normally it should jump briefly to the 50k power consumption of the discharge coil)

The important part is that the discharge coil is connected to a grid and is being triggered through UberPendragon's circuit, directly wiring the button to the coil seems to resolve the issue.

**Version**
Windows Unstable 0.17.10.0

**Additional information**
I've found the issue to be related to the update order of the device.
The main functions being the
PowerUpdate of the grid,
"Use" function of the discharge coil when it is triggered
"Update" function of the discharge coil.

The problem arises as normally the execution order is
"Use"
PowerUpdate
"Update"
Since the "Use" function will add the new load and the power update will take this load into account, then the "update" function of the coil performs its voltage check on whether it should discharge.

For some unknown reason the wiring and sub itself changes this order to
PowerUpdate
"Use"
"Update"

Causing the new load to not be accounted for in the voltage calculation and thus the coil passes the power check in the "update" function causing it to discharge and immediately set its load back to 0 thus causing 0 power draw.
Possible fix is to have the "Update" function of the coil check whether the Use function was called before or after the PowerUpdate so it can know whether to invalidate the voltage check and the next update frame perform the check and pass.

**Comment by Regalis11** [comment]
Hmm, is this the correct submarine file? The EDC seems to be connected directly to the supercapacitor and I can't see any displays displaying the power or the load.

**Comment by Regalis11** [comment]
Nvm, I was able to repro this just by switching the wire from the supercapacitor to a junction box. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dad06e6f12d2e66cf91529986c6f800ff1018657

**Comment by Torca2001** [comment]
Oh I just saw this, haha my bad must have not saved it before grabbing the file. Regardless thanks for the quick response to the issue.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
