### ISSUE TITLE
[Unstable 0.17.10.0] Can't enter levels with a Hunting Grounds mission (Mission equality check failed)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8847]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever you try to load into a level with a Hunting Grounds mission in multiplayer campaign all clients gets disconnected

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a0e80357-af52-409a-b2ff-113bc46a598c)

**Steps To Reproduce**
Load up the attached save file on multiplayer and try to enter one of the levels with Hunting Grounds mission. 

**Version**
Unstable 0.17.10.0

**Additional information**
Save (Inside zip):
[https://app.zenhub.com/files/93301055/5ec5e4b3-c495-4757-84ac-6f6a6f8e68ab/download](https://app.zenhub.com/files/93301055/5ec5e4b3-c495-4757-84ac-6f6a6f8e68ab/download)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4079bf6a07056b3b0e5da5b92fa66e3c448d6f9d

**Comment by Rokvach** [comment]
My game crashed when I was testing this

Steps:
1. Load the included campaign save in dedicated server
2. Join the server and start the campaign
3. Crash

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ba674aa1-1dce-490f-9898-32b490ad9d8f)

**Comment by Rokvach** [comment]
I wasn't able to reproduce the above crash in release branch
