### ISSUE TITLE
[Unstable 0.17.10.0] Trying to spawn a ladder on cursor throws an error

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8849]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to spawn a ladder or other such item throws a error on the console, previously you were able to spawn them in. 

`Failed to spawn item, prefab not found (name: , identifier: ladder)`

**Steps To Reproduce**
Spawn a ladder on cursor position

**Version**
Unstable 0.17.10.0

**Comment by Regalis11** [comment]
Couldn't repro
![image](https://user-images.githubusercontent.com/14351070/163954695-7fecae0c-95b3-49fa-a152-96637cc1337b.png)

**Comment by Rokvach** [comment]
Looks like you have to be in multiplayer for it to throw the error

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d940870c21a69084ee18f1d43005897497c000f1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
