### ISSUE TITLE
When using a plasma cutter/welding tool at round end the light they emit will be still on in the next round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8850]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/548c349b-320e-44c3-a6fd-001cbb0278f7)

**Steps To Reproduce**
Use a plasma cutter and ask someone else to end the round in multiplayer, notice that the light is still on when the next round loads. 

**Version**
0.17.10.0

**Comment by Regalis11** [comment]
Happens in single player too, addressed in https://github.com/Regalis11/Barotrauma-development/commit/39db3435814af29ce49f0d9d26f68077139b709d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
