### ISSUE TITLE
[Unstable v17.10.0] Some structures lacks names, labels are randomly ordered

### ISSUE THREAD

**Issue by Renko-6662** [Regalis11/Barotrauma#8851]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm playing in French, and basically, this is what I got in the editor :
![image](https://user-images.githubusercontent.com/66101079/163994432-e1bbd162-f543-43bf-b6ee-03e7e3a3d28d.png)
- Names are in red, and aren't actually names but item identifiers.
- When I place multiple items on top of each other, the pop-up list only show blanks black lines.

![image](https://user-images.githubusercontent.com/66101079/163994666-c6a636f2-011b-4beb-a3fb-35232d3542bd.png)
- All the items that don't have names are randomly ordered. 
- I also can't find them using the search bar (for example "label" will show no items, as it seems it look for name and not identifiers)

**Steps To Reproduce**
I'm guessing all the problematic items are the one lacking translation ?
So, steps to reproduce, I'd guess > Launch Unstable in French, then launch editor

**Version**
Unstable v17.10.0, W10

**Additional information**
Newly added items seems to work tho
![image](https://user-images.githubusercontent.com/66101079/163995039-17bc69cc-b22c-4123-8f13-60b0de747408.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c5f54b66d67d6b6141362f69f98aec47d4b82c0b

**Comment by Renko-6662** [comment]
![image](https://user-images.githubusercontent.com/66101079/164039651-e69b6e59-0ddc-4985-b85b-65ccedb3b5dd.png)

Everything is fixed except the random order

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ba03751773d2fdd66762eb630912feeefbef4f89

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
