### ISSUE TITLE
[Unstable v17.11.0] jobid:xxx doesn't work anymore

### ISSUE THREAD

**Issue by Renko-6662** [Regalis11/Barotrauma#8856]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
jobid:xxx don't work anymore as Picked Required for doors and lockers.

**Steps To Reproduce**
- Set a secure locker with "jobid:captain" as Picked Required
- Spawn with a captain and try to open it

**Version**
Unstable V17.11, W10

**Additional information**
Although for subs you can work with tags, for mods, having the jobid:xxx allow things to be compatible with every sub, no matter their spawnpoint tags.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/cf608939caa107953577a0efed479a531725796c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
