### ISSUE TITLE
[Bot AI] Bot puts crate into running deconstructor

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#8859]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you switch characters in singleplayer and the previous character had no wait order, it puts the crate into the deconstructor input slot.

**Steps To Reproduce**
have a crate in your hands and leave one slot in the deconstructor free
(have all output slots filled with crates [not sure if it matters])
start deconstruction
have no wait order on the character who did that
switch to another character

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/164241084-d3b6adc4-b047-4d87-a573-6440600251d3.png)

**Additional information**
Happened on a vanilla Humpback (unedited, no mods)

**Comment by Regalis11** [comment]
It seems that the fix to https://github.com/Regalis11/Barotrauma/issues/8859 didn't work correctly, reopening that ticket instead
