### ISSUE TITLE
Bots have problems opening hatches inside the sub when using scooters

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#8860]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When you give the bots scooters in their inventory they use them inside the sub if it is heavily flooded. But they have trouble using hatches and they use the scooter endlessly swimming against the hatch.

**Steps To Reproduce**
Give bots scooters
flood the sub
have a hatch with enough sidespace so the bot gets into a horizontal body position
bot wont reach the hatch waypoint to open it

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/164243559-7f7f4333-80d0-4bb1-8046-b3a2ce486b0f.png)

**Comment by itchyOwl** [comment]
Unfortunately couldn't repro the issue. Tested on Humpback and Kastrull. Might be specific to certain subs and plaching the hatches inside them?

**Comment by Regalis11** [comment]
No known steps to repro, closing
