### ISSUE TITLE
Assembly tab/previews crash sub editor

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#8862]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to display a certain assembly in sub editor's search bar, the game crashes to desktop

Some assemblies are quite big so this might be the cause (other assemblies can be displayed in search bar by typing their name)
![image](https://user-images.githubusercontent.com/73229309/164299363-0cd7c89c-de05-4130-ada2-f982cbb4bee7.png)

Check out Spankylaboratory (the biggest one). 
My game stopped crashing after removing it when I used the search bar, but the assembly tab still crashes 

I suspect it doesn't like loading too many previews at once

Download the whole assembly mod in Localmods:
[Assemblies.zip](https://github.com/Regalis11/Barotrauma/files/8524364/Assemblies.zip)

**Comment by Hultipoo** [comment]
I have encountered this issue as well. I believe I have narrowed it down to when an item assembly has an item from a mod that you currently don't have enabled.

**Comment by Ek-Videogames** [comment]
I believe I have narrowed it down to an item assembly has an item from a mod that is currently installed.

Maybe the thumbnail generating code has not been properly updated to work with the new %moddirectory% formatting system?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f98ca9d2c8915f209a87f78fe0c550658407bd5

**Comment by JoneKone** [comment]
https://p.ip.fi/qsXP


just going to leave this here although the issue seems to been have fixed.

**Comment by Rokvach** [comment]
Game doesn't crash if the Spankylaboratory assembly is shown on the entity list or if I select the assembly category, but if I try to load the Spankylaboratory assembly my game just straight up closes without any crash report, most likely because the assembly is too big.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a8788525668826ef6cd3ee0823940f2f36c0eec1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
