### ISSUE TITLE
[Re-appearance of old bug] 'CargoContainerIdentifier' accepts items with tags instead of identifier

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8866]
**Description:**
Cargo container identifier field will try to spawn any item who's tags contains the same string.
- if **item-A** has the identifier="cargobox"
and **item-B** has the identifier="treasurebox" tags="cargobox"
- the cargocontaineridentifier="cargobox" will cause the game to sometimes decide to spawn **item-B** as the cargo container because of its tags being treated as a valid id.

_(Shared item tagging/ids are still a common convention used in mods in order to facilitate compatibility between large item sets. 
Which is why this lack of distinction can still be a problem)_

**Comment by Regalis11** [comment]
This is not a bug: just like in most other places, tags and identifiers are used interchangeably here.

> Shared item tagging/ids are still a common convention used in mods in order to facilitate compatibility between large item sets

It's a convention that should not be used if you don't want the game to consider the items to be interchangeable. To facilitate compatibility, the items should be using the same tags, but not using the identifiers of another item as the tags.
