### ISSUE TITLE
New Stations - Box keeps clipping from station wall

### ISSUE THREAD

**Issue by fr45** [Regalis11/Barotrauma#8868]
- [- ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A box on a station keeps clipping, hiding behind the station wall texture.

**Steps To Reproduce**
No idea. Try loading a station.

**Version**
Urban Expanses update, 20 april 2022. Windows x64.

**Additional information**
Added a screenshot.
Box in question is highlighted in pink rectangle.
![image](https://user-images.githubusercontent.com/1794500/164311353-11a11817-e1db-415f-8288-2933a98c3452.png)
Now the box is invisible.
![image](https://user-images.githubusercontent.com/1794500/164311854-9ef94173-dd0c-4a08-a2a1-7797b9b66c7d.png)

**Comment by danielasteljoki** [comment]
Fixed in bce8eb5

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
