### ISSUE TITLE
[Dev version] Items that have new icons don't change the color of the icons when you color their sprites

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#887]
It was pretty convenient to see colors of the sprites when checking inventory or containers, as they indicate special properties of the items.

For example, colored sprites of the flares indicate their light's colors.
![wilson-pc-2018-oct-15-015](https://user-images.githubusercontent.com/38168249/46927537-20c4b400-d060-11e8-80a3-2d59751f1826.jpg)
It's pretty hard to know about the special properties in the dev version if the description of the items is not different.
![wilson-pc-2018-oct-15-021](https://user-images.githubusercontent.com/38168249/46927546-27ebc200-d060-11e8-856e-7c980420a9dc.jpg)
There should be some kind of color indication, either by coloring the new sprites as well, or via some other way.
Perhaps something like this could work(though not sure if that would look good).
![wilson-pc-2018-oct-15-013](https://user-images.githubusercontent.com/38168249/46927629-8d3fb300-d060-11e8-84f0-6ec660e3d892.jpg)

**Comment by Regalis11** [comment]
This is actually not a bug: the color of the icon is now configured separately from the color of the sprite. But in any case it's good you brought it up, the attribute should be exposed to the sub editor to allow creating stuff like the colored flares.

**Comment by BillCombs** [comment]
Also, the syringes don't change color of their icons when they have a chemical inside them. Makes it kind of inconvenient, especially in urgent situations. You may accidentally poison yourself instead of healing, if you don't take the time to look inside of the syringe.
