### ISSUE TITLE
Game crashing on start

### ISSUE THREAD

**Issue by bruhmogus** [Regalis11/Barotrauma#8871]
- [✓ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When starting Barotrauma, it sometimes crashes whenever I press the start button.

**Steps To Reproduce**
The crashes only appears to happen if you launch the game with WeMod. (you do not have to have any mods active)

**Version**
Most recent as time of writing. I am playing on Windows 10.

**Additional information**
This text prints when I get the message. "Barotrauma Client crash report (generated on 4/20/2022 7:11:34 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F5A9DEA86521334DB4300590CA8EF0EF

Game version 0.17.12.0 (ReleaseWindows, branch release, revision 2971300777)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, EK | Armory, EK | Utility, Improved Husks, SCP-500 "The Panacea", Meaningful CPR, Pockets For All, Doom Eternal, Unique Starred Items & More, Defibrillator (Batteries), Hungry Sailor, Stanford Security Vessel - 012, Half life series armor, Stanford Security Vessel - 013
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce MX130
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Attempted to divide by zero. (System.DivideByZeroException)
Target site: Void Draw(Microsoft.Xna.Framework.Graphics.SpriteBatch)" Someone please explain why it is attempting to divide by zero.

**Comment by Regalis11** [comment]
> The crashes only appears to happen if you launch the game with WeMod

Since it only happens when using a 3rd party software we don't officially support, I don't think we will be addressing this.

**Comment by bruhmogus** [comment]
i know regalis closed this, but to anyone wondering, it appeared more to be a mod that would conflict, enabled or disabled
