### ISSUE TITLE
Deadeye Carbine burstfire visually/audibly broken in Multiplayer

### ISSUE THREAD

**Issue by SeaverBeaver** [Regalis11/Barotrauma#8876]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Deadeye carbine will visually fire 4 or even 5 shots in a burst while only consuming 15% of the magazines durability, (3 shots)

**Steps To Reproduce**
Open the Sub Editor, fire a burst with the Deadeye, watch as it fires 3 shots.
Do the same in a Multiplayer server, watch as it fires anywhere from 2 to 5 shots in a a burst, while only consuming 3 shots.

**Version**
Latest Release (V 0.17.12.0)

**Additional information**
While the carbine visually fires 2-5 shots, and the tracers reflect this, the impacts and damage done still, (thankfully,) reflect 3 shots.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b1824576d90c0a1900729ebf2c8519a75e38d489

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
