### ISSUE TITLE
[Talent]"cannedheat" cannot enhance the quality of "oxygenitetank"

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#8878]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"cannedheat" cannot enhance the quality of "oxygenitetank", if you get 100 mechanical and the "cannedheat", you still cannot make master tier "oxygenitetank"

**Steps To Reproduce**
get 100 mechanical and the "cannedheat" and start manufacturing "oxygenitetank"

**Version**
v0.17.12.0 windows

**Additional information**
Oxygenitetank are consumed by cave gas, is this a bug or a feature？

**Comment by Regalis11** [comment]
Yeah, as the talent description says, it only affects oxygen and welding fuel tanks, not oxygenite tanks.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e4c7899345116a39477bec6d4323c1fb7ac63832

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
