### ISSUE TITLE
Crash when language is set to None (= when using a fresh config file)

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#8880]
- [x] I have searched the issue tracker to check if the issue has already been reported.
- I feel this belongs here.

**Description**
When I start a dedicated server On linux it doesn't start the round fails it with this message.

https://p.ip.fi/NC1A

It continues to fail with a slightly different message.

https://p.ip.fi/RuMG

Apparently it keeps happening on different scenarios on windows side too

https://cdn.discordapp.com/attachments/587647684794515468/966430035416334346/unknown.png

**Steps To Reproduce**
Get fresh dedicated server from the source and start it on linux.

**Version**
0.17.12.0
Linux/Windows

**Additional information**

Work around
```
[Yesterday, 23:54]
Evil:
	found the issue
	looks like by default the language is set to None
	and thats causing issues
	open config_player.xml
	and change language from None to English
```
I think the issue is somewhere here.

https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Settings/GameSettings.cs

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/52fde7b70f6e90365848962a73795ba556617488

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
