### ISSUE TITLE
[Talent] "Canned Heat" cannot upgrade modded welding fuel tanks that cant fit into vanilla welding tools.

### ISSUE THREAD

**Issue by Dailyyy** [Regalis11/Barotrauma#8881]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Attempting to make Canned Heat upgrade modded welding fuel tanks without making it fit into vanilla welding tools is currently impossible without vanilla overrides (which I dont want to do)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.
- Make a custom welding fuel tank
- If you give it the "weldingtoolfuel" tag (which is the tag that lets it be upgraded by Canned Heat, then it will also fit into vanilla welding tools.)

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).
latest version of the game, windows.

**Additional information**

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/aecd165174d5add8e54dcc7f091aac756f854b2b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
