### ISSUE TITLE
Fabricators, deconstructors and research stations aren't wired in colonies

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8884]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Fabricators, deconstructors and research stations aren't wired to the rest of the grid in colonies, making them unusable

**Version**
v0.17.12.0

**Comment by danielasteljoki** [comment]
Fixed in 777f45b and 1adb13b.

**Comment by ubertpendragon** [comment]
May I suggest adding **medical fabricators?** 

Outposts do not have any, it feels necessary for subs that don't have fabricators (Dugong relies on outposts entirely).

Here
![image](https://user-images.githubusercontent.com/73229309/164465859-1aa7560d-941e-44bd-8045-6bf5c351ed97.png)

and here
![image](https://user-images.githubusercontent.com/73229309/164465968-b3ff36c1-9b36-46af-8c40-49fe7e76d4f7.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
