### ISSUE TITLE
Dugong Submarine Select Image Uses Outdated Sprites

### ISSUE THREAD

**Issue by Dbat2** [Regalis11/Barotrauma#8889]
**Description**
It seems the submarine select image for when you start a singleplayer campaign has a slightly outdated image for the Dugong. The diving suit containers are the old orange tint instead of the new green tint. Other subs use the green tint.

Dugong: 
![image](https://user-images.githubusercontent.com/91236493/164520356-b364f47e-acd7-45a5-928b-674ed9a37f5b.png)

Humpback:
![image](https://user-images.githubusercontent.com/91236493/164520441-01151d49-d238-4782-ab96-8f4fd9dbd52f.png)

**Steps To Reproduce**
Start a singleplayer campaign and pick Dugong as your starter sub. 

**Version**
v0.17.12.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2d55827a5677fd961e05559648b3403fdcd70a0c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
