### ISSUE TITLE
If you host via the in game buttons and the server takes too long to load, you will get disconnected from it

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#8891]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Looks like for a few selected people, they get disconnected from the in game server before the server can fully load, making it impossible to host using the in game buttons.

**Steps To Reproduce**
1) Host a server using the in game buttons and somehow make it take a while for it to load for the first time
2) Watch you get disconnected before the server can fully load

**Version**
v0.17.12.0

**Additional information**
![21212121](https://user-images.githubusercontent.com/36804725/164527630-a8cc7b01-5ad3-48c0-bb5b-48c1ae311ee9.png)

**Comment by Speaker15071** [comment]
It looks similar to my [issue](https://github.com/Regalis11/Barotrauma/issues/8064). If player load too long, server drop connection. Is there any way to increase client timeout delay?

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8ee062f423eaf2f718cc1e9763aee1099fba09dd

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/749914f4707c8b61fc62ade029de1ff75aee3ac9.

After awhile a prompt will appear to return to lobby or wait longer. where if it does finish loading (and you hit return to lobby) you can spectate back into the round. one can also wait until the level finally does load. the popup appears multiple times preventing you from ever getting stuck if the server actually freezes allowing to return to lobby (and then to menu).

One issue has been noted. If you go to lobby then hit spectate (and the server finishes loading after this) - the spectate button will still be unclickable but they will not join the round. But disconnecting (IE. if you wanted to rejoin) would actually close the server in this case.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/5db992c8b7b9ba63b10ce6339db89d0f5f032ccf, works correctly, closing.

Notes:
Tested wrong thing previously, the longer timeout works fine and could see no issues with cancelling or letting it run its full length. It can still timeout, but it now has 5 times longer (200 seconds) before disconnecting the host trying to launch the server. servers can be re-hosted regardless of outcome too.
