### ISSUE TITLE
Kastrull - several pumps have no power consumption

### ISSUE THREAD

**Issue by fr45** [Regalis11/Barotrauma#8894]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Two smal pumps have no min.voltage and no power consumption on Kastrull.

**Steps To Reproduce**
Load up Kastrull in editor, look at pumps in top and bottom airlock access.

**Version**
0.17.12.0, Win10 x64

**Additional information**
First - bottom airlock access:
![image](https://user-images.githubusercontent.com/1794500/164529776-ffe5bb02-2b47-4971-8f3f-729ed5aadb48.png)
Second - top airlock access:
![image](https://user-images.githubusercontent.com/1794500/164530109-d653353a-3e36-4739-b8a9-fe77f08e3859.png)

**Comment by danielasteljoki** [comment]
Fixed in 832a628

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
