### ISSUE TITLE
Clients keeps dropping at next level's round start or round end in campaign when hosting P2P (SteamP2PTimeout)

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8899]
Clients keeps dropping at next level's round start or round end in campaign when hosting P2P except for the host.

All other clients except the host will get sent back to the lobby. If they try to rejoin, they will end up in freecam mode while their characters are still actively standing around. If they rejoin the server after that, they will get control back of their character.

Hosting via Dedicated server is the only workaround so far.

**Comment by CurePindal** [comment]
Yep. Disapointing to see that this issues still plague the game after such a long time. 
When will this finally be fixed?

**Comment by Sozzky** [comment]
Same. Hopefully, this will get fixed soon as currently it happens almost every round. The equipment of the ones who get kicked also gets reset.

**Comment by Regalis11** [comment]
What's the error message you get when this occurs?

**Comment by Sozzky** [comment]
[ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/8541355/ServerLogs.zip)

These are some logs files that will hopefully help.

**Comment by Ek-Videogames** [comment]
Sometimes you will just get kicked with "connection lost, do not allow reconnect" and no error in log.

Sometimes it is the usual "received update for an entity that doesn't exist" error.

**Comment by Regalis11** [comment]
Thank you for the extra info! I think it seems there are two different issues going on here, the one that's causing the disconnections with an ambiguous error message, and the "missing entity" errors.

> Sometimes you will just get kicked with "connection lost, do not allow reconnect" and no error in log.

This error message should mention the reason for the disconnection (+ some extra details in the debug console), any ideas what it could've been?

**Comment by cshingle** [comment]
> This error message should mention the reason for the disconnection (+ some extra details in the debug console), any ideas what it could've been?

This is a little messy because there are a few errors that people are getting. I don't currently have screenshots/logs for these but I will get them and add them to issues over the weekend. The multiplayer issues seem pretty widespread but most people are just bitching about it and not reporting issues. 

1) There is the one that kicks people when a new round is loading. Their character will usually spawn but most of the lobby is kicked. When they rejoin they will not have control over their character. This seems to happen ever few rounds or so. This is the one that [Kaillera](https://github.com/Kaillera) is talking about.

2) There is the MISSING ENTITY issue that seem to be happening Much more often on Vanilla servers.

3) There is also a new server crash issue that I am waiting to get server logs for. I have been playing on other peoples servers rather than hosting and am waiting for a copy of their crash logs.

**Comment by Kaillera** [comment]
So here's what happens:
1. Start the next level.
2. Clients are immediately booted out.
3. If booted to the server browser, the mission briefing UI remains opened and requires alt-f4 to exit.
![Capture](https://user-images.githubusercontent.com/5086682/164768098-846e1110-4177-4f5e-8a89-a595a27b0e28.PNG)

Here's the console dump for that.
[1.txt](https://github.com/Regalis11/Barotrauma/files/8542959/1.txt)

4. If stuck at the loading screen (won't connect client to the next level), the mission briefing UI remains opened, but you can hit the Close button on the mission UI, and will tell you that you've timed out.
![Capture](https://user-images.githubusercontent.com/5086682/164769155-bf5cf19d-f6be-4e9b-96ab-04455daf88ea.PNG)

[2.txt](https://github.com/Regalis11/Barotrauma/files/8542998/2.txt)

Even if you rejoin the server now, you will be stuck in freecam mode. If you aren't in your body when the level transitions, the players loses their characters and will spawn in with new ones.

**Comment by CarlosRollo** [comment]
after disconnecting everyone with steam p2p connection error.
In around 1/3 of all level starts, the in-game crew list (the one under the "c" in the qwerty layout) becomes empty (doesn't even show the host).
After restarting the level all bots disappear, they don't even have their bodybags.

**Comment by Regalis11** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/f5f70e809d7b51f9658b4e0a1fcf14aab2d7242b

**Comment by Rokvach** [comment]
Tested, players aren't being timed out anymore during loading screens and this is working correctly. Tested with the new simulatedlongloadingtime command and wasn't able to time my client out no matter how long they waited. So working correctly, closing.

**Comment by idogadol** [comment]
The problem still occurs for me and my crew.

**Comment by Sozzky** [comment]
> Tested, players aren't being timed out anymore during loading screens and this is working correctly. Tested with the new simulatedlongloadingtime command and wasn't able to time my client out no matter how long they waited. So working correctly, closing.

Great! Is it the hotfix live already? If not, any ETA?

**Comment by Kaillera** [comment]
> The problem still occurs for me and my crew.

> Great! Is it the hotfix live already? If not, any ETA?

Relax guys, it's actually going to be in testing in Unstable build today.

**Comment by idogadol** [comment]
Can we get notified when it will be in the Unstable build, please?

**Comment by Kaillera** [comment]
> Can we get notified when it will be in the Unstable build, please?

It's already up

**Comment by Kaillera** [comment]
Fix is working so far, as far as the first two level transitions goes anyways.

**Comment by idogadol** [comment]
Yup, it works, many level transitions into the campaign! :D

**Comment by Ek-Videogames** [comment]
Not sure if you have it, but some level of transparency to the "disconnect dialog" would be nice, some kind of indicator of **weather or not the game is still getting information from the server** during this time - to help prevent people wasting their time by separating possible 'false-positive' situations where the server is quite obviously crashed from the game's perspective.
