### ISSUE TITLE
using %ModDir:Y% to reference files from a different mod errors on startup

### ISSUE THREAD

**Issue by Mannatwo** [Regalis11/Barotrauma#8902]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When referencing files from other mods in mod X using the new %ModDir:Y% with X and Y being any non-equal mods, mod X errors and gets automatically disabled when starting the game.
Switching load order doesn't fix the issue.
Reenabling mod X afterwards remedies the issue.

**Steps To Reproduce**
- Create two mods, X and Y.
- In mod X, create an item or an affliction whose sprite or icon uses a texture from mod Y, using texture="%ModDir:Y%/z.png"
- Enable both mods
- Restart the game

**Version**
v0.17.12.0, Windows

**Additional information**
Tested with local mods.
Console error:
![image](https://user-images.githubusercontent.com/103883287/164622056-2566deb4-2940-4089-b980-363a2c565f80.png)

**Comment by Krzeszny** [comment]
It's REALLY bad. People are beign mass-disconnected and they can't reconnect, because this item from a mod references another mod
![Barotrauma_fHkkpGO8nu](https://user-images.githubusercontent.com/10529134/164995035-f6a71b06-5962-439b-9fcd-afe8fcc2bb1f.png)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/9902129b5058e0ae330535e032d8c683b065949e

**Comment by Rokvach** [comment]
I tested with the NT Surgery Plus mod, if I have Neurotrauma installed but its disabled I am still able to use the NT Surgery Plus mod but if I only have the NT Surgery Plus mod installed it will show a error at the start of the game about the missing Neurotrauma. 

Also when the error shows up it also disables the NT Surgery Plus mod so you aren't able to cause a crash anymore when starting a new singleplayer game for example like you used to. 

Working correctly, closing.
