### ISSUE TITLE
[0.17.12.0] Shopping list UI not actualized after taking money from the bank

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#8903]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The shopping list in a shop is not properly actualized when you deduct money from the bank while the shopping list stays open.

It most cases it does not allow the purchase if you meet the needed cash after deducting it from the bank. (amount to pay still shown in red while the available amount  matches or is higher)

Expected: Shopping list is properly actualized after deducting money from the bank without having to close and re-open the shop interface.

**Steps To Reproduce**
- assemble a purchase shopping list which price exceeds your currently available/personal money
- without closing the shop UI (important!) open the player menu with tab and deduct the needed cash from the bank (permissions needed)
- in most cases the purchase cant be made because the price still stays red while the available cash is properly shown (and is equal or exceeds the total price, ofc). Sometimes it somehow is properly actualized (roughly ~20% of tested cases)
- closing and re-opening the shop UI works as workaround

**Version**
tested in 0.17.12.0, win, MP, being the host

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
