### ISSUE TITLE
[0.17.12.0]Unable to load a weapon whose <ItemContainer> capacity is above 1 with ammo on the hotbar by pressing the hotkey

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#8906]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Before the newest update, player can load an auto shotgun with shotgun shells on the hotbar by pressing the corresponding hotkey.
Now, doing the same operation causes player trying to unequip the gun and equip the ammo instead.

**Steps To Reproduce**
1.place some shotgun shells on any hotbar slot
2.equip an auto shotgun
3.press the hotkey to the slot where you placed shotgun shells

**Version**
0.17.12.0 on Windows 10

**Additional information**
Weapons whose <ItemContainer> capacity is 1 (for instance, smg or revolver) is not affected by this issue.
In the newest changelog, there's a line:
"- Fixed inability to equip one-handed items when there's a suitable container in the other hand (e.g. flashlight when there's a storage container in the other hand). "
I believe this issue is related to this change.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
