### ISSUE TITLE
Always require ManageMoney permissions to access the bank

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8907]
Currently ManageMoney works the same way as other campaign permissions: if no-one in the server has special permissions, anyone is permitted to do it. This can be a little too risky, because a random player joining a non-moderated server could just withdraw everything from the bank and disconnect.

We should change it so that only the host + people with permissions are allowed to transfer money from the bank.

**Comment by 3e849f2e5c** [comment]
Changed in https://github.com/Regalis11/Barotrauma-development/commit/ed693bf24508bb791f638cf602083810d6855e94

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
