### ISSUE TITLE
repair tools cause monsters to attack with insane speed

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#891]
multiplying cooldown timer by 0.1 in enemyaicontroller in OnAttacked causes all creatures attack with really fast speed(faster than spamming r when controlling it) when they are being attacked with any repairtool. removing that would fix it, it would also allow for more skill based combat by being able to hit the monster and then retreat without instantly getting killed
https://cdn.discordapp.com/attachments/220881718666723328/506498744922013716/unknown.png
https://www.youtube.com/watch?v=cJghE_PAuPU&feature=youtu.bethe difference when using repair tool and when not

**Comment by Regalis11** [comment]
Fixed in the dev branch

**Comment by etet2** [comment]
i've just tested it, it is still a thing. they still attack with insane speed

**Comment by etet2** [comment]
https://youtu.be/NvJRjaozd2c

**Comment by etet2** [comment]
@Regalis11 i think you should reopen this

**Comment by Regalis11** [comment]
I think the behavior in the clip makes sense, it would be weird to have the monster enter a 5 second cooldown before attacking again when you're blasting a welding tool on its face.

**Comment by etet2** [comment]
1.but why doesn't it do that when using literally any other weapons(i know the cooldown is reduced but not to such and extent where an attack starts literally after another one ended)?
2. makes modded long range repairtool weapons pretty anoying as creatures instantly charge you and insta kill you.
3.insta kills are not fun.
4.animation looks very unnatural - mudraptor(and a lot of other creatures) seem like they meant to do big swings/charges and it does not make sense when you start welding it for it to start slashing you that fast
5.behavior making sense is debatable, it is general assumption that animals are afraid of fire and hot things, you could argue that sensible behavior would be for it to start running away

**Comment by etet2** [comment]
6.makes repairtool the worst weapon in the game as bashing a creature with a wrench is much safer which isn't very intuitive

**Comment by BillCombs** [comment]
Got to agree with etet2 here, just look at the difference:

Revolver:             https://streamable.com/kzr90

Ancient weapon: https://streamable.com/o7a9j

The weapon that is given to the captain at the very beginning of the game is better than the weapon that requires risking looking for it in alien ruins.

**Comment by itchyOwl** [comment]
I agree that the cooldown shouldn't reset when the character takes damage, if the behaviour of the character is not to retreat after attacking, which it should be in this case. However, if the character retreats and then it's attacked, it's only natural that it retaliates as soon as it can (or flees). Previously all the characters retreated after attacking, so this might explain the cooldown reset (if that really is the case). Maybe there needs to be an extra variable for the reaction delay after the character has been attacked against. I can take a look into it at some point, when I'll get back to the monster ai things.

**Comment by itchyOwl** [comment]
Fixed in the dev branch. The enemies now retaliate quickly only when attacked by a character first time. The second attack doesn't reduce the cooldown anymore.
