### ISSUE TITLE
Haloperidol is ineffective against psychosis

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#8912]
**Description**
Haloperidol doesn't cure psychosis. In the health screen the affliction bar changes color when the drug is selected, but once applied nothing happens.

**Steps To Reproduce**
_In the sub editor_
Spawn in a stack of Alien Blood (`spawnitem "Alien Blood" inventory 8`)
Drink the alien blood
_Switch characters_
Set medical skill to maximum (`setskill medical max`)
Observe the character afllictions
Spawn a stack of Haloperidol (`spawnitem Haloperidol inventory 8`)
Apply haloperidol for no effect.

**Version**
Barotrauma v0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)

**Additional information**
Other antipsychotics such as Ethanol and Deliriumine Antidote work as expected

**Comment by Ek-Videogames** [comment]
For some reason Haloperidol targets a limb (ethanol, delirumine antidote, cigar etc don't).
This seems to be the issue since psychosis is not limb-specific and targeting a limb would do nothing.

**Comment by mygamingaccount** [comment]
By the way I also tested injecting into limbs, and it didn't work.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b0ec597964371695543da4a75cba730bbcce9156

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
