### ISSUE TITLE
Overvoltage damage seems broken

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#8913]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After the last game update overvoltage damage of junction boxes seems broken. During all the round junction boxes have no damage from the overvoltage cases in multiplayer campaign. Later I tested it on Typhoon 2, Dugong, Herja in sandbox mode. During the trip from the start point to the destination I maximized an engine thrust and stop it all the time. Even if reactor output exceeded by 1000-2000 kWatts then load, j.boxes have no damage. One time I succeeded to receive 1% damage to jboxes on Herja but no more.
As result all our engineers have a lot of free time in current update.

**Steps To Reproduce**
Choose any submarine. Start the round in sandbox mode with zero threat. During the trip to the destination periodically maximize and stop engine thrust all the time.

**Version**
Barotrauma 0.17.12.0 (ReleaseWindows, branch release, revision 2971300777)

**Additional information**
Possibly all the subs have this problem

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately wasn't able to reproduce this. Supplying more than x2 of the load to the grid seems to damage the junction boxes reliably in both single player and multiplayer:
![image](https://user-images.githubusercontent.com/14351070/164740008-e39f7b9e-44c8-4a72-a058-dc0a2dda7b98.png)

**Comment by Xardion495** [comment]
Guess i found out what happened. In this update you made some tweaks to power grid mechanics, but most junction boxes now have Overload Voltage parameter with default values: 2.0
I checked some of the other subs too. Values of this parameter varies from 1.7 to 2.0 on them. This value is too high and made 'Enhanced Resistors' upgrade almost useless, cause 2x energy overload is almost unreachable at this moment (honestly, I can't remember such overloading values for all of my gameplay time).

![20220422190302_1](https://user-images.githubusercontent.com/17722887/164752246-b67cd43a-16a5-4eb5-8321-cd043ac468af.jpg)

Usually junction boxes damaged and fired cause of steering mistakes (including autopilot actions) and not by reactor over output cause the players usually settling reactor on the self auto-control which not allow prolonged overloads. So it forced the helmsman to be more careful with submarine driving.
Now this game feature is broken and junction boxes almost not damaging during the round **from overloads**, so engineer players begin to get bored.

Now, even the default Kastrull with no upgrades is just a relaxation yacht, but earlier, it was considered one of the most hardcore submarines in context of junction boxes. Earlier excess by 500-1000 kWt during a few seconds caused a fire on this sub.

![20220422185507_1](https://user-images.githubusercontent.com/17722887/164751772-bdbfb8eb-1913-419d-959e-d6f10ddd1165.jpg)

**Comment by Xardion495** [comment]
After the last hotfix the problem is gone, thx
