### ISSUE TITLE
Failed to parse the string 'COLOR.GUI.GREEN' to Color

### ISSUE THREAD

**Issue by SardinaDePato** [Regalis11/Barotrauma#8914]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When the game is in Spanish, and you try to upgrade weapons, a wild console appears saying "Failed to parse the string 'COLOR.GUI.GREEN' to Color".

**Steps To Reproduce**
Put the game in Spanish and try to upgrade a weapon.
**Version**
v0.17.12.0

**Additional information**
The command prompt also don't want to close, so every time I want to upgrade or add a weapon I need to change the language.
![image](https://user-images.githubusercontent.com/73857534/164736302-0b8a441e-16d1-4870-b9ed-4831c9c9dad4.png)

**Comment by Ek-Videogames** [comment]
español moment

duplicate: #6104

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/96b0deec9ee4b243eb195a8ec31361c35dec8cd4

**Comment by MacmanamanHG** [comment]
> Fixed in [Regalis11/Barotrauma-development@96b0dee](https://github.com/Regalis11/Barotrauma-development/commit/96b0deec9ee4b243eb195a8ec31361c35dec8cd4)

That page does not seem to exist, it throws the 404 error.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
