### ISSUE TITLE
When the "min voltage" and "power consumption" of some sub ediitor's items is set to 0 and no wiring for them, they do not work properly.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#8916]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Some items in sub editor with "powered", when you set "min voltage" and "power consumption" to "0", and no wiring for them, it will not work, such as oxygen tank shelf and charging dock.

**Steps To Reproduce**
Choose oxygen tank shelf and set "min voltage" and "power consumption" to "0", and no wiring for it. you will see it cannot refill the oxyen tank. But this was possible in the previous version. This items seem all have "powered".

**Version**
v0.17.12.0 on Windows 10

**Additional information**
If you connect these non-working items to the power supply with wires, then they will work properly. 
Seems only items have "powered" have this problem.

**Comment by Renko-6662** [comment]
I've got exactly the same problem.
Only the Power Consumption need to be set to 0 for the item to stop working, tweaking min voltage doesn't change anything.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/91c62128a7db3604a31fa886e65e42cc2104dc62

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
