### ISSUE TITLE
Can't see ID Card Jobs

### ISSUE THREAD

**Issue by civilCornball** [Regalis11/Barotrauma#8920]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Before this update, you could mouse over an ID to check the owner's job - and by extension, access permissions.
After the update, you can't even check the ID's previous job by disguising as them.

See: This medic's ID.
![image](https://user-images.githubusercontent.com/48499004/164785595-b483b970-cd2a-48f1-806c-ccbbc376a9ae.png)

**Steps To Reproduce**
Join literally any multiplayer game.
Or maybe even a singleplayer game. Haven't checked yet.

**Version**
Current safe version, the "Urban Expanses" update.

**Additional information**
Apparently this was supposed to be fixed by the update? Even though I haven't seen it ever before this one?

To quote:
"- Fixed ID card descriptions disappearing between rounds.
- Fixed ID card description not being added if the ID card tags are empty."

**Comment by civilCornball** [comment]
I'd label this a bug if I knew how to.

**Comment by Ek-Videogames** [comment]
Oh yeah... I noticed those were gone but I wasn't sure if it was just a problem with our sub specifically.
This is possibly just another symptom resulting from the jobid:[job] tag on cards not working.

**Comment by fr45** [comment]
In my current campaing job symbols are no longer shown on status monitor.
Hired a new bot - he immediately appeared on the monitor. Symbols of others are still not shown.

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/cf608939caa107953577a0efed479a531725796c

**Comment by Rokvach** [comment]
Just tested in sub editor and loading up singleplayer and can't see any jobs on the ID cards

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/49813a9f-8c78-4d14-97da-0b5c566949f2)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/042807173de667c087a1d3835364e76ed485af9c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
