### ISSUE TITLE
Junction boxes not degrading over time

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#8926]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Junction boxes just do not lose condition overtime, only taking damage from outside forces like water, emp, overvolting, etc.

**Steps To Reproduce**
Sit and watch, or just let it run, probably execute the mech and engi bots too so they don't fix anything, check status monitor after a few minutes or more.

**Version**
0.17.12.0

**Additional information**
bruh

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f72a5ebf06bed3a36774b58ade4c778f16b6e3a0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
