### ISSUE TITLE
Filth on walls takes too long to render.

### ISSUE THREAD

**Issue by BlackMoons** [Regalis11/Barotrauma#8930]
Was trying to track down why late campaign subs have such low FPS, I discovered that filth on the walls is a real FPS killer. editing a late game sub I found drawmap go from 8ms to 5ms after removing all filth from the walls. (tested in sub editor's test sub mode, so the rest of the world was not rendering)

I don't think dirt on the walls is worth a 60% increase in rendering time. Its a nice feature idea but not worth that much FPS, can we have a console command to clean the sub? And an outpost vendor who will do it for money? And a cleaning sprayer that isn't a waste of ethanol? Iv literally never seen anyone use it once in a campaign game since it would take forever to clean one room for no in game benefit other then FPS. 

A client side option to disable rendering of it would be a *great* feature for people with low spec machines. 

Currently, the only sane way to clean the sub iv found is uncompress the save, edit the sub, delete every hull and replace every hull, since you can't even 'clean' a hull in the sub editor.

**Comment by Rokvach** [comment]
Looks like when playing with a older save the wall grime is still being rendered, on the latest update we have fully removed this feature so walls doesn't get dirty when the submarine floods but seems like that change didn't affect older saves.

**Comment by BlackMoons** [comment]
Ahhhh. Good to know, Didn't realize you guys changed the filth behavior in the last update. Thank you very much for this improvement!
