### ISSUE TITLE
Morbusine doesn't affect NPCs

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Regalis11/Barotrauma#8932]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

The NPCs at Outposts aren't affected by Morbusine.

**Steps To Reproduce**

1. Start a new campaign or multiplayer server
2. At an Outpost, acquire a lot of Morbusine and a Health Scanner HUD
3. Poison many NPCs
   * Some dwellers
   * Some security officers
   * Some interactables (shopkeeps, sub maintenance, etc.)
4. Observe nothing happens to *any* of them, even when the poisoning reaches 100%
   * nb: On multiplayer, the client will see some "rubberbanding" in the oxygen low stat, but the server always insists that the NPC doesn't have oxygen low, and the NPC never suffers ill consequences from it
5. (Optional) Go back through and poison half of the subjects (and a few non-subjects) with Sufforin as an additional test

**Version**

v0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)

I have observed this since 2 major releases ago. I did not test it before then.

**Additional information**

Sufforin *is not affected* by this bug.

**Comment by mygamingaccount** [comment]
Could be related to #8912

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06357727c41044c441f7567604cf7c073a1e41e7. Looks like there were a couple of things wrong here:

> - Fixed HumanPrefab's health multipliers being applied twice (in OutpostGenerator.SpawnNPCs and HumanPrefab.InitializeCharacter), causing some outpost NPCs to have x9 health.
> - Fixed HumanPrefab's health multipliers not being applied client-side, causing "health rubberbanding".
> - Fixed morbusine not killing NPCs with a large health multiplier.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
