### ISSUE TITLE
clientpermissions.xml baloons to 2.5 GB from 2.5 kB, and apparently the presets are nolonger a thing!??!

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#8933]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I hope this is a bug cause if it's a feature and somebody ripped the permissionpresets.xml code away...

Basically what it says on the topic. I could also call it "Permission Presets no longer work"
(server it self turns the preset pointing clientpermission.xml file to a Mangled file where it wants to make all command based not preset list based.)

**Steps To Reproduce**
Make clientpermission.xml (we have 10 users and 6 presets)
```
﻿<?xml version="1.0" encoding="utf-8"?>
<ClientPermissions>
  <Client
    name="JoneKone"
    steamid="xxxxxxxxxxxxxxxx"
    preset="Sadmin" />
</ClientPermissions>
```
Make permissionpresets.xml
I'm not going to copy ours here.

Restart the server few times. and see how it balloons to be the biggest file ever seen.

https://steamuserimages-a.akamaihd.net/ugc/1821152507222966283/29D495C8AC18F525AC3BC74F905FE6BD60C13B69/

**Version**
0.17.12.0 Linux Dedicated (Yes it's lua server, but I believe issue does not lie there)

**Additional information**
Re work the whole permission system to respect the .xml files and give gui the list of presets that are actually present.

Presets are basis of our server and very important. If there is any kind of love to our server from dev's please include the fix on next hotfix. This is the reason our servers are down.

**Comment by Kaillera** [comment]
I've been hosting a few times in this version and been handing out permissions via default presets like admin and moderator to people I trust, and modified the None preset as well to include SellInventory and ServerLogs. The only user in my clientpermissions.xml is still just me.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/418c1b3efbc51311c72c8233afc373eda1abd86b

**Comment by Rokvach** [comment]
Tested, the size of the clientpermissions.xml stayed the same no matter what I did. Working correctly, closing.
