### ISSUE TITLE
Watcher ink slows down the game

### ISSUE THREAD

**Issue by MadJack-Churchill** [Regalis11/Barotrauma#8941]
- [] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a Watcher appears, shooting it releases its ink and walks away. When this happens the fps drops too much and the game becomes slow. On my Acer Aspire 7 it could be normal, but it also happens on a friend's PC which is much more powerful, that's why I'm reporting.

**Steps To Reproduce**
Find a Watcher during multiplayer campaign and shoot until it drops ink.

**Version**
v0.17.12.0 (ReleaseWindows, branch release, revision 2971300777)

**Additional information**
I don't know how to mark the check mark at the beginning, sorry, I'm new...

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/253118a1159c720575b8ab4672fd12527358bada

**Comment by Rokvach** [comment]
I didn't notice any framerate issues when Watcher used the acid attack, working correctly. Closing.
