### ISSUE TITLE
Ruins no longer generate in early biomes

### ISSUE THREAD

**Issue by jooshdd** [Regalis11/Barotrauma#8942]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Ruins no longer spawn in coldcavernsbasic/maze and ridgebasic.

**Steps To Reproduce**
Using editlevels or exploring the map manually shows no ruins in any level.

**Version**
Windows 10 v0.17.12.0

**Additional information**
Using editlevels and manually exploring over 100 different levels with various seeds i can confidently say no ruins spawn in coldcavernsbasic/maze and ridgebasic. ruins still generate in biomes beyond them in every level.

**Comment by fr45** [comment]
Sounds like intentional. Ruins are pretty hard in the beginning if you don't know what to do.

**Comment by Kaillera** [comment]
This was recently a change to wreck and ruins to prevent being able to have end-game items before you even left the first two biomes.

**Comment by Regalis11** [comment]
Yes, this is intentional. In the early biomes you only encounter ruins if you specifically choose a ruin mission.
