### ISSUE TITLE
Deconstructing an assault rifle magazine yields a steel whose condition is based on magazine's condition

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#8946]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Deconstructing an assault rifle magazine yields a steel whose condition is based on magazine's condition,
while it is supposed to yield a full condition steel like the smg magazine.

**Steps To Reproduce**
Deconstruct an Assault Rifle Magazine of which condition is not full.

**Version**
0.17.12.0 on Windows 10

**Additional information**
It only requires a simple modification to the Assault Rifle Magazine's document in "Barotrauma\Content\Items\Jobgear\Securitysecurityofficer_talent_items.xml" to solve the problem.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5370ac93514b002ffcb24de4fad08115df1b7d76

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
