### ISSUE TITLE
Cannot start new game or cannot host a server.

### ISSUE THREAD

**Issue by BENZINCoffinmaker** [Regalis11/Barotrauma#8954]
Issue:
After the "Urban Expanses" update I can no longer generate a new world. This issue occurs both when I try to create a new world via a new campaign or a server campaign.

What have I tried:
I unsubscribed from all the mods and uninstalled Barotrauma and deleted all the files in AppData. Issue still continues to occur when installed the game again.

Version:
Windows 10 / Vanilla, v0.17.12.0

Error code:
![Errorcode](https://user-images.githubusercontent.com/104306829/164976777-70bf5cbd-f602-467b-8c16-945c33cda9c4.jpg)

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8887
