### ISSUE TITLE
Broken supercapacitors provide unlimited power to attached weapons

### ISSUE THREAD

**Issue by Quilan** [Regalis11/Barotrauma#8959]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If a supercapacitor is destroyed (condition reduced to zero) and is charged, any attached weapon will fire without consuming any charge.

**Steps To Reproduce**
This can be reproduced either in-game or in the sub editor + test mode.
1: Load a sub with a power-consuming weapon, e.g. Dugong.
2: Charge the weapon's supercapacitor (or edit it to maximum charge in the editor).
Optional: Disconnect the supercapacitor's "power in" pin to verify it is not being fed from the power grid.
3: Destroy the supercapacitor, either with a structure-destroying weapon (or editing its condition to zero).
4: Man the weapon's periscope. The charge bar at the bottom should appear full and green.
5: Fire the weapon.
Expected: The weapon does not fire because the supercapacitor is destroyed.
Actual: The weapon will fire and will not deplete charge from the supercapacitor, allowing it to fire indefinitely.

**Version**
Windows 0.17.12.0

**Additional information**
If the supercapacitor does not have sufficient charge to fire the weapon, it will not fire; it appears to check there is enough charge to fire but does not consume it, nor does it check if the capacitor is functioning.

**Comment by Torca2001** [comment]
This is part of the same issue of #8949

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/634f7634bfad3b60cda348bedfd8ef93ea378eee

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
