### ISSUE TITLE
Server breaks when human with some talents transform to a husk

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#8963]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This is a really frequently malignant bug, it broke my server many times.

**Steps To Reproduce**
1. give a talent to a human, e.g. "Let It Drain"
2. give affliction "Husk infection" to the human by 100
3. wait for the human to die and transform into a husk
4. server breaks

**Version**
Windows 0.17.12.0 (pure vanilla without any mods)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/961ff37d1ece7a82f32c63536a4a2e5db2524db3

**Comment by Rokvach** [comment]
This hasn't come up during community testing, working correctly. Closing.
