### ISSUE TITLE
Startgame Networking Error?

### ISSUE THREAD

**Issue by Galaxies12** [Regalis11/Barotrauma#8971]
- [ Yes ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The issue can be seen in the picture, not _quite_ sure what it means. Just posting this here for help fixing the bug.

**Steps To Reproduce**
I'm sorry, I'm not exactly sure how to reproduce this error. It occured on a **heavily** modded multiplayer server. I don't think it's the mods though, even though the issue is referring to a mod called "SCP-008".

**Version**
Newest version, this may not be correct: Build ID 8589268 (According to Steam?)
Using Windows 10.

**Additional information**
This was on a multiplayer server with many mods, multiple being relatively broken.

If I could be of any more help, feel free to contact me over Github or Discord. 
Discord - Galaxies#6458

![20220424183516_1](https://user-images.githubusercontent.com/103787407/165137385-48e1a9fc-095c-46ee-86d8-f366b0e63534.jpg)

**Comment by Galaxies12** [comment]
Please know that I'm new to posting bug reports, and if any information is wrong I'll do my best to fix it. :D

**Comment by Regalis11** [comment]
I unfortunately haven't found a way to reproduce this. Tested by installing [the mod in question](https://steamcommunity.com/sharedfiles/filedetails/?id=2794406667) on the server and client, and by only installing it server-side and downloading it from the server.

**Comment by Regalis11** [comment]
No known steps to repro, closing
