### ISSUE TITLE
mission UI shows up in lobby for non-spectators

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#8973]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

**Steps To Reproduce**

1. join a lobby
2. players get a mission?
3. I see this 
![image](https://user-images.githubusercontent.com/5103517/165184114-d56dbd08-5759-4c35-b021-6b21eca58245.png)
**Version**
1.7.12
**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fde3b9c668b6211db1493679a66dabef04563f95

**Comment by Jasontti** [comment]
Tested. Notifications of new missions come after leaving the lobby and joining the game.
