### ISSUE TITLE
MISSING_ENTITY when moving a welding tool from a storage container to hotbar

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8978]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing as normal, Player Darkrider moved a welding tool from a storage container to his hotbar after some intense situation happens throughout the round, and it caused all players to get kicked from the server. Respawns were OFF. Was playing with [New Wrecks for Barotrauma](https://steamcommunity.com/sharedfiles/filedetails/?id=2184257427).

Logs of 3 of the players that were in it (I was a client while hosting with dedicated):
[ServerLogs.zip](https://github.com/Regalis11/Barotrauma/files/8564276/ServerLogs.zip)

**Version**
0.17.12.0

**Comment by Rokvach** [comment]
Closing as the other tickets has already been tested and closed, there also hasn't been any GA reports about this.
