### ISSUE TITLE
Respawn shuttle causes mission end and players to be kicked

### ISSUE THREAD

**Issue by Brumes-Wolf** [Regalis11/Barotrauma#8982]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Every so often when a player respawn it will cause the mission to end and kick all players. A message will appear for the host saying that an item (different every time) was not found on the shuttle.

**Steps To Reproduce**
Have players die, and then have them respawn. Does not happen every time.

**Version**
V0.17.12.0, Windows 10

**Additional information**
When host verifies integrity of game files a few files will sometimes fail to validate.

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/8879
