### ISSUE TITLE
Husk Infection does not appear on health scanner HUD from 1% to 20%

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#8983]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
For some reason, husk infection cannot be diagnosed by a health scanner until it reaches ~~30%~~ 20% infection. Patch notes doesn't state any changes to detectability so I'm led to assume this is a bug.

**Steps To Reproduce**
Infect someone in any way and immediately check them using the health scanner HUD

**Version**
0.17.12.0

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this. The infection seems to appear on the health scanner at 20%, and becomes visible to the player at 40%.
![image](https://user-images.githubusercontent.com/14351070/165471863-3e45305a-8c26-4d09-89fc-11d57a238f28.png)

**Comment by PokkeTigrex** [comment]
My fault, I didn't really make it very clear what I'm trying to say. What I meant to say is that 1% husk infection up to 20% is not visible on the medical hud. This, again, was never on the patch notes, and does not seem to be intended.

**Comment by Regalis11** [comment]
That was actually an intentional change, looks like we forgot to mention it in the changelog.
