### ISSUE TITLE
An Unknown Error About Testing Submarines Under 3000m Depth

### ISSUE THREAD

**Issue by BanXianSch** [Regalis11/Barotrauma#8984]
- [x] I have searched the issue tracker to check if the issue or anything similar has already been reported.

In the test of submarine editor, when it goes down to about 3000m depth, all crews including myself dead and disappear from crew list immidiately without any warning, my field of vision also blurred. Every subsystem and every crew was working normally before this happened.

This will happen to official submarine builds and DIY MODs. No predictively textual description can be found in game or manual.

Barotrauma v0.17.12.0 (ReleaseWindows, branch release, revision 2971300777)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a4a6c596fb8909ddd29d45de171468da011a9cd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
