### ISSUE TITLE
Inconsistency: structure-damage reputation re Abandoned Outposts

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Regalis11/Barotrauma#8989]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**

I lose reputation with an Abandoned Outpost if the bandits _see_ me damaging the structure. This seems inconsistent:

* If the reputation loss is due to the subsequent dwellers noticing the damage and connecting-the-dots to the famed rescuer, what does it matter whether the bandits saw me?
* If the reputation loss is due to the bandits "snitching" on me to the general public, how can they do that if they're _all dead_?

**Steps To Reproduce**

1. Start an abandoned outpost mission
2. Damage the outpost walls out-of-sight of the bandits
   * Observe no reputation loss
3. Damage the outpost walls in sight of the bandits
   * Observe reputation loss

**Version**

v0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)

**Additional information**

This is especially annoying when missing shots: why do I lose more reputation for a stray bullet that harmed no-one than I do from scootering around back and _destroying_ the medical clinic to flood the bandits out?

**Comment by Regalis11** [comment]
Thank you for the report!

We're actually planning on getting rid of location-based reputation altogether and just using faction reputation, so I don't think we'll be addressing this (since the fix would become obsolete in the near future).
