### ISSUE TITLE
Cant earn marks in campaign mode

### ISSUE THREAD

**Issue by protogencpu** [Regalis11/Barotrauma#8990]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Marks cant be earned in the campaign mode in anyway

**Steps To Reproduce**
Launching campaign mode I have tested this multiple times with and without modes

**Version**
Windows 0.17.12.0

**Additional information**
It dosent give marks after missions or the starting marks

**Comment by Regalis11** [comment]
Mission rewards go into the bank (a kind of "shared wallet"), have you tried moving them do your own wallet? Money can be transferred in the wallet interface that can be opened by clicking on the wallet icon near your character portrait, or by selecting your character in the tab menu's crew list.
