### ISSUE TITLE
Clicking on settings or workshop causes the game to crash

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#8994]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Clicking on settings or workshop causes the game to crash.
(Issue uploaded for my friend)

**Version**
v0.17.12.0 windows

**Additional information**
download report to see more.
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/8569358/crashreport.8.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2a53ea0ad2240db047ac0fec8446adb1870faa91

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
