### ISSUE TITLE
Modded language not in dictionary

### ISSUE THREAD

**Issue by ALIAS-001** [Regalis11/Barotrauma#8996]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am unable to start anything when selecting nockslang as a language
Nockslang is a mod that adds a language that adds numerical stats to item descriptions

**Steps To Reproduce**
Install nockslang from the steam workshop
Enable nockslang under the mod menu
Select nockslang under language
Attempt to create a game or join a server

**Version**
V 0.17.12.0 Windows

**Additional information**
Crash log:
https://pastebin.com/fa8fDdmM

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a0da3ea2e9bd27d51efae3c3a96ec46d493454cd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
