### ISSUE TITLE
Outpost NPCs die due to radiation sickness caused by volatile fulgurium fuel rods

### ISSUE THREAD

**Issue by Oukido** [Regalis11/Barotrauma#8999]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
If enough time passes all reactors that need to be fueled will use up any fuel rods spawned with the npcs until the game spawns additional fuel rods when needed, which now are volatile fulgurium fuel rods.

This leads to ncps dying from radiation sickness on outposts and even faster on pirate subs.

In the past it spawned only normal fuel rods.

**Steps To Reproduce**
Have an outpost with fuel usage greater than zero run out of fuel rods
Observe NPCs with long contact to the reactor dying.

**Version**
![grafik](https://user-images.githubusercontent.com/83960267/164326502-cfe82275-0662-4c92-813f-7010be07fa55.png)

**Comment by Regalis11** [comment]
I think the underlying issue here is that the NPCs now choose the type of fuel rod to spawn randomly, instead of spawning a normal one. This probably also applies to other AI objectives, e.g. they might end up with a different kind of welding-capable item than the normal welding tool when fixing leaks.

**Comment by Oukido** [comment]
Hmm the strange thing is 3 out of 3 times I encountered the reactor running out of fuel on outpost / pirate sub, it was always a volatile fulgurium fuel rod in the reactor. Of course this can still be conicidence but the frequency it happens is concerning.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b586518b38aae150b52de311da0509e1b3253adb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
