### ISSUE TITLE
Solve ordering issues when serializing lists

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#900]
The order of the elements in lists matters when syncing their states. Sometimes, the order may change, depending on any number of factors, including but not limited to differences in the .NET implementation and platform.

Lists potentially in need of fixing:
- MonsterEnabled
- ExtraCargo
- ~~Map.locations~~ fixed, the issues with this had to do with rng

Some solutions to consider:
- Add sorting criteria to each list so the order is always guaranteed to be the same. Cannot be used when some elements may be absent on either end.
- Use a predictable hashing algorithm on the elements and sync that. May not be optimal in terms of bandwidth usage in some cases.

**Comment by Regalis11** [comment]
Would it make sense to instead try to ensure that the number and order of the elements is the same? If the players are using the same content packages, I think the lists of available monsters should be the same (and if it's not, they should not be allowed to play on the same server). Same for map locations, the generated maps should be identical, and if they're not, it may be impossible to get the campaign to work correctly. As a related note, #848 could be affecting the map generation as well and causing this kind of mismatches.

As for extra cargo, could we send the identifiers (or names in the master branch) and the numbers of items so the order wouldn't matter?

**Comment by juanjp600** [comment]
In most cases it should be fairly safe to assume that the number of elements is the same, and sorting all of these (with a known algorithm that we can guarantee to be the same across platforms) should be easy enough. ExtraCargo should be able to get away with doing this since we already have the content package hashes to ensure that both ends have the same items. The same is applicable to MonsterEnabled.

The only reason I suggested using a hashing algorithm to generate identifiers is because I already have a case where the amount of properties may not necessarily be the same (ServerSettings uses this to allow for server-side additions to the synced properties without breaking unmodded clients).

**Comment by juanjp600** [comment]
Doesn't seem to have been a problem for a while now
