### ISSUE TITLE
Changing the resolution doesn't rescale fonts

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9001]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Font sizes don't change when you change the resolution.

**Steps To Reproduce**
1. Start with a large resolution
2. Switch to a smaller resolution
3. Texts will remain the same size, and be too large

Or the other way around, starting with a small resolution and increasing it

**Version**
v0.17.x.x

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd9dbc69c898b773ef85c3c2177b47ee1b60a7ca

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
