### ISSUE TITLE
button sprite offset

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9002]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
button sprite appears offset in X axis
![image](https://user-images.githubusercontent.com/5103517/165584456-2a6cafc1-85e0-4a55-846f-2ba07a422a73.png)

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**

**Additional information**

**Comment by Regalis11** [comment]
Couldn't repro 
![image](https://user-images.githubusercontent.com/14351070/165587880-5b6a1c57-4ecb-4fe0-8c3e-55be6108a068.png)

It would be helpful if you could fill in the details in the issue report, namely the steps to reproduce the issue and the version it happened in.

**Comment by Tsunder** [comment]
sorry, the report is made on behalf of another user

![image](https://user-images.githubusercontent.com/5103517/165594514-9ddc54b5-1837-4f4b-bd33-ed32e1913c74.png)

appears to be from a mod, not vanilla.
