### ISSUE TITLE
low particle limit issue

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9009]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
important/informative particle effects may not be shown if particle limit is reached

**Steps To Reproduce**
1. set particle limit to minimum (100)
2.  throw down some flares (i threw 2)
3. throw frag grenades
4. frag grenade explosion effect is just a flash, no green explosion thing as I see when limit is at max (1500)

**Version**
0.17.12.0

**Additional information**
I'm not fully sure how else to name this

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/cdab028a016331a5ddd3634e8db30ccb5440d301

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
