### ISSUE TITLE
Ignore orders disappear after saving and reloading

### ISSUE THREAD

**Issue by Sozzky** [Regalis11/Barotrauma#9011]
- [X] I have searched the issue tracker to check if the issue has already been reported. 

**Description**
After reloading a multiplayer save, all the items tagged with "Ignore this" are missing the tag, requiring us to retag everything again to avoid bots taking what they're not supposed to. Might also reproduce on singleplayer, have not tried yet.

**Steps To Reproduce**
1. Open up a new game or a save
2. Tag a few items as ignore with Shift+MMB
3. Save and Quit
4. Load the save again
Notice that all the tags are gone

**Version**
Windows 0.17.12.0 stable

**Additional information**
I'm unsure if this is by design or if it's a bug, but wanted to report it just in case.

**Comment by ekqvist** [comment]
Seems that this is a multiplayer-only issue. If you give orders and load into the next level, the orders will persist. But if you exit the game after moving to the next level and then reload the save, the orders will be gone.

**Comment by Sozzky** [comment]
In addition, it seems that holding an item in the hands while finishing a mission also removes the ignore tag.

**Comment by ekqvist** [comment]
Based on my testing, it seems that this likely never worked correctly in multiplayer. However, it should now be fixed in Regalis11/Barotrauma-development@9f46260.

**Comment by Sozzky** [comment]
> Based on my testing, it seems that this likely never worked correctly in multiplayer. However, it should now be fixed in [Regalis11/Barotrauma-development@9f46260](https://github.com/Regalis11/Barotrauma-development/commit/9f46260).

Awesome! :)

**Comment by ekqvist** [comment]
@Rokvach The original issue should be fixed. There's still an issue with items that are part of a character's inventory. Not sure yet how to address that or if it's something that needs to be addressed. If we decide to do something about it, I think we should create a new ticket for it.

**Comment by Rokvach** [comment]
I was only able to get this to work in multiplayer but not in singleplayer

Singleplayer steps
1. Load up new save with humpback
2. Add ignore this to deconstructor
3. Hit save and quit
4. Load save
5. Run to deconstructor and notice that the ignore this order is gone

Multiplayer steps:
1. Load up new save with humpback
2. Add ignore this to deconstructor
3. Hit save and quit
4. Hit continue in lobby
5. Run to the deconstructor and notice that the ignore this order is still there

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@073e906. I broke it with the fix for multiplayer. Was just an issue with trying to find the active orders element under the wrong parent element.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
