### ISSUE TITLE
"Sprite not found" error when playing with mods that add characters and random events that spawn them

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#9013]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Got this report on Discord, here are the images sent:
![image](https://user-images.githubusercontent.com/8607119/165760518-3ea42b6f-6d47-4b45-9192-8866bea38861.png)
![image](https://user-images.githubusercontent.com/8607119/165760589-57bb7fa3-56f0-452d-b102-eaa5addd5b0f.png)

**Steps To Reproduce**
- Create a mod that introduces a character with a custom texture. The path should use %ModDir%.
- Add a random event that will spawn this character.
- Load up a round that will use this random event, triggering the preloading code.

**Version**
v0.17.12.0

**Additional information**
The game will still be able to load the characters correctly, this error just appears at the start of the round.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/99b0341a066c96a498535af256c8ca524c66b388

**Comment by Rokvach** [comment]
Tested, didn't receive any errors, seems to be working correctly. Closing.
