### ISSUE TITLE
Debug console cannot be interacted with during a broken loadscreen

### ISSUE THREAD

**Issue by gerbilOFdoom** [Regalis11/Barotrauma#9016]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game ~~crashed~~ failed to finish loading when leaving outpost, this is a known issue and unrelated to this. When my client ~~crashed~~ experienced a in a broken loading state, I found that the F3 debug menu was hidden behind much of the load screen interface. This prevented me from interacting with or even reading the debug window to gather information. A crash log was not generated, as far as I can tell. 

**Steps To Reproduce**
Be in a multiplayer lobby and be a client. Host leaves an outpost. Game crashes during load for some reason. This will probably happen in this case.

**Version**
v0.17.15.0

**Additional information**
N/A

**Comment by Rokvach** [comment]
If you still have input to the game you can press F3 twice to open the console above any other UI, ofc this isn't possibility if the game crashes or halts to a point where you can't use any inputs. But I think we should try to make sure that the console is always rendered on top of any other UI. I've mainly seen this happen in the round summary screen where the console has opened before the round summary and therefore been rendered below it.

**Comment by gerbilOFdoom** [comment]
@Rokvach Interesting thing here - I did press F3 a few times. The console always rendered below content boxes from the load screen.

**Comment by Regalis11** [comment]
> Game crashed failed to finish loading when leaving outpost, this is a known issue and unrelated to this

I'm not sure what issue you're referring to, do you know if there's a ticket about this in the issue tracker?

**Comment by gerbilOFdoom** [comment]
@Regalis11 I believe the disconnect/freeze I experienced is related to #8635. If correct, this is the method by which I discovered the bug I made this ticket for. However, in my case, only I lost connection with the server while others completed loading successfully.

**Comment by Regalis11** [comment]
Made the debug console render in front of everything else in https://github.com/Regalis11/Barotrauma-development/commit/a2c849eb43c7f8e5463e00930ceaa8fb89f1f4c2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
