### ISSUE TITLE
Modding: Targetslot behavior issue ( with RequiredItem & values in the StatusEffect element )

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9019]
Behavior of 'target slot' seems to be not working as intended, in this particular case I have used it to designate an oxygen slot inside a suit with multiple inventory slots. This involves the use 'OnWearing' status effect with 'RequiredItem' for the activation and 'OxygenAvailable' being the resulting effect defined in the 'root' StatusEffect.

I've reproduced this problem with a [simple mod](https://github.com/Regalis11/Barotrauma/files/8587990/TargetslotBugMod.zip) which takes an otherwise unmodified PUCS - is the functionality I tried to replicate - and replaces the chem slot with a generic small-item storage slot.

**Steps To Reproduce:**
- Put on the suit and enter an atmosphere with no oxygen (for instance outside the submarine entirely)
- Oxygen tank in 'slot 0' works as intended, providing oxygen and depleting the tank's condition
- Nothing in either slots works as intended, character oxygen begins to deplete as no oxygen is supplied
- Oxygen tank in the secondary slot produces issue, character is supplied unlimited oxygen without the tank being consumed

At some point in the process it seems 'targetslot' is not being correctly respected by all the conditions checked by the game for this StatusEffect to trigger, this is particularly strange because despite `OxygenAvailable="1000"` and `Condition="-0.3"` being part of the same status effect the oxygen is still triggering while the condition is not.

**Comment by Regalis11** [comment]
This seems to happen as a result of this status effect.

```
<StatusEffect type="OnWearing" target="Contained,Character" UseHullOxygen="false" OxygenAvailable="1000.0" Condition="-0.3" comparison="And" targetslot="0">
  <Conditional InWater="true" />
  <RequiredItem items="oxygentank" type="Contained" />
</StatusEffect>
```

Basically what it does is it applies the effect on the contained tank in slot 0 and the character, if the character is in water, and if there's an oxygen tank inside (no requirements on which slot). If the tank is in slot 1, the effect will only target the character.

To require the tank to be in slot 0 for the effect to execute, move `targetslot="0"` into the RequiredItem element (in a sense, change it from "this effect should be applied on the tank in slot 0" to "a tank in slot 0 is required for this effect to execute").
