### ISSUE TITLE
Native Apple Silicon build

### ISSUE THREAD

**Issue by Ichicoro** [Regalis11/Barotrauma#9022]
I tried building Barotrauma on M1 natively, and the performance (well, the FPS) almost doubled (went from an average of around 110 to an average of 200). To build it, I just had to replace the SDL, freetype and openal dylibs with arm64 ones in the solution and then I had to change the `TargetFramework` from `netcoreapp3.1` to `net6.0` and the `PlatformTarget` from `x64` to `AnyCPU`. I think this is worth a look, since it means higher framerates/lower power consuption on Apple Silicon Macs.

This is with the Intel build of the game (current Steam release)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21175939/166072928-b83c6ba3-5281-4d4e-9e38-b8f4cff3bbbe.png">

This is with the ARM64 native build of the game (built on my M1 Air)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21175939/166073070-17618082-1c28-410d-8188-8f4f2d38e06a.png">

**Comment by evilfactory** [comment]
I would like to note that while testing the game on net6.0, i noticed that anything related to compression was pretty much broken, all old saves were unable to be loaded, joining any server would cause you to get errors, etc.

**Comment by cshingle** [comment]
I too built the game on net6.0 on Linux and found a significant performance improvement. I was able to load a saved campaign and load a custom sub in the sub editor without any issues.
```
quickstart Azimuth
```
Here is the steam build
![Screenshot from 2022-05-02 16-21-30](https://user-images.githubusercontent.com/2231937/166331995-82a9f0e1-4ae6-470b-b3a6-f5f51fe18c19.png)
vs my release build on .Net 6.0
![Screenshot from 2022-05-02 16-26-33](https://user-images.githubusercontent.com/2231937/166332057-d45fa478-3f4a-4890-9e5b-026791ef3063.png)

**Comment by cshingle** [comment]
I too built the game on net6.0 on Linux and found a significant performance improvement. I was able to load a saved campaign and load a custom sub in the sub editor without any issues.
```
quickstart Azimuth
```
Here is the steam build
![Screenshot from 2022-05-02 16-21-30](https://user-images.githubusercontent.com/2231937/166331995-82a9f0e1-4ae6-470b-b3a6-f5f51fe18c19.png)
vs my release build on .Net 6.0
![Screenshot from 2022-05-02 16-26-33](https://user-images.githubusercontent.com/2231937/166332057-d45fa478-3f4a-4890-9e5b-026791ef3063.png)

**Comment by 3e849f2e5c** [comment]
Since this is pretty much the ".NET 6.0" ticket I'm gathering all the code workarounds for .NET 6.0 here for the sake of having them in one place

- https://github.com/Regalis11/Barotrauma-development/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Utils/SaveUtil.cs#L486-L496
Fixes save decompression

- https://github.com/Regalis11/Barotrauma-development/blob/dev/Barotrauma/BarotraumaShared/SharedSource/Networking/ChildServerRelay.cs#L110-L123
Fixes client crashing when shutting down locally hosted server

**Comment by Regalis11** [comment]
Closing this in favor of a ticket in our private repo https://github.com/regalis11/barotrauma-development/issues/3448 (since we generally only use the public repo for issue reports)
