### ISSUE TITLE
All outposts turn into colonies

### ISSUE THREAD

**Issue by Sozzky** [Regalis11/Barotrauma#9025]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
All the outposts in our multiplayer save have turned into colonies. A few rounds ago one turned back into a research station and then right back into a colony when we finished a round.

**Steps To Reproduce**
Just by progressing through the campaign, I guess. I'll attach the save in the additional information section. 
We do have some mods, but none of them should really touch anything outpost related.

**Version**
0.17.15.0 Windows

**Additional information**
Modlist if needed:
[Collection](https://steamcommunity.com/sharedfiles/filedetails/?id=2799635474)

Save:
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/8597582/Multiplayer.zip)

Some screenshots:
![1](https://user-images.githubusercontent.com/13069429/166117609-042b65e6-7e70-4885-b7db-4c58e3da0867.png)
![2](https://user-images.githubusercontent.com/13069429/166117614-3ba9f4c7-ffca-432f-9100-b568d95ee46b.png)

**Comment by BlackMoons** [comment]
Can confirm seeing a lot of 'XYZ has turned onto a colony!' but almost no other messages about turning into anything else in vanilla campaigns. 

Some times there will be 2~5 'XYZ has turned into a colony!' messages in a single round start, later in the campaign.

**Comment by danielasteljoki** [comment]
Addressed in 58a5cd3. Limited the amount of colonies that can be formed, along with some probability and duration changes.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
