### ISSUE TITLE
Creating a new Item Assembly with a space at the end causes the game to instantly crash

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9028]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Creating a new Item Assembly with a space at the end causes the game to instantly crash.

**Steps To Reproduce**
1) Open sub editor and create a new Item Assembly
2) Put a space at the end of the name

**Version**
0.17.15.0 Windows 10

**Additional information**
[message.txt](https://github.com/Regalis11/Barotrauma/files/8598140/message.txt)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a74969ccf215b9f4270d973df188baeeaac2911f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
