### ISSUE TITLE
Bots consider <StaticBody> as blocking turret line-of-sight

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9033]
Bots operating periscopes seem to treat the collision boxes (StaticBody) of other turrets as an obstruction to line-of-sight. 
This doesn't make much sense as StaticBody only collides with characters and structures, not projectiles - so they shouldn't care about shooting through other turrets.

This is an issue that you would never encounter naturally on a vanilla submarine as all turrets are spaced apart, but on custom submarines a setup like having a turret switching between a railgun & coilgun placed in the same spot would not allow the AI to fire them even if wired in an AI-friendly manner.

**Steps To Reproduce**
Controlled turret occluded by other static bodies or placed inside another turret.
![image](https://user-images.githubusercontent.com/55356135/166154464-b5405f8e-b940-4415-bd01-80d9451aabd0.png)
![image](https://user-images.githubusercontent.com/55356135/166154379-c3a2f613-1a1c-4997-b45b-1763f0d2a11d.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d747cf0fb919e9112db0029b0ae74675ed0834af

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
