### ISSUE TITLE
Error in calculation of hull optimal ballast level

### ISSUE THREAD

**Issue by Torvald118** [Regalis11/Barotrauma#9034]
[✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I`ve found that optimal neutral ballast level has wrong calculation.
It is calculated incorrectly each time I reselect it.

**Steps To Reproduce**
Place hull in sub editor and see what will happen if you manipulate with it`s size and pos.

**Version**
v0.17.15.0 hotfix
Windows 10 x64

**Additional information**
I recorded and saved it on youtube: https://youtu.be/JVTG-lX694Q

**Comment by Regalis11** [comment]
Thank you for the report! I don't see what the issue is here; these values seem correct.

**Comment by Torvald118** [comment]
> Thank you for the report! I don't see what the issue is here; these values seem correct.

Yes, my bad, looks like I found it too suspicious after long time non-playing.

I think it`s closed.
