### ISSUE TITLE
Frame drops in sub-editor when selecting containers

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9035]
Game seems to freeze for about a fifth of a second when selecting a container item - this performance difference didn't happen in previous versions, so it seems something may have gotten slower that could be cause for concern?

**All affected items seem to have some similarities:**
- Must be able to contain 'smallitem's 
_( Doesn't happen to railgun shelves, oxygen tank shelves, charging dock, unit load device, fire extinguisher holder, etc )_
- Doesn't matter if it is holdable item or static item 
_( IE, both crates & lockers are affected )_
- Happens even with entirely empty containers

**Examples of items this happens:**
- Supplies Cabinet, Medium Steel Cabinet, Large Steel Cabinet, Secure Steel Cabinet, Metal Crate, Storage Container, Cargo Scooter, Fabricator, Medical Fabricator, Deconstructor, Loose Panel, Loose Vent, Medical Compartment.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/a1d8abe966b7721542ad30dcf61c49576170518e

**Comment by Rokvach** [comment]
Tested, I didn't notice any frame drops when selecting containers no matter how many items they had in them. Working correctly. Closing.
