### ISSUE TITLE
Shell A 18 Degrees is misaligned in vanilla subs

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9040]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Load up Humpback on sub editor and notice that the hulls are misaligned

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/9f462601f9a45bf135645234dd8ae97e57340a19

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4470ea4d-b910-4a7b-bc9d-c2ee7f35e2ec)

**Comment by Rokvach** [comment]
Could be already fixed in the bugfixes branch?

**Comment by Regalis11** [comment]
Couldn't find any other affected subs than Humpback and Kastrull, fixed those in https://github.com/Regalis11/Barotrauma-development/commit/b5207a8d71b2688b4628e30f740495b276d0b1a6

**Comment by Regalis11** [comment]
There seems to be one in Herja as well
![image](https://user-images.githubusercontent.com/14351070/166417575-d429cd84-b948-45c9-a1b6-fbe768a11d3f.png)

**Comment by Rokvach** [comment]
Should this be in QA?

**Comment by Regalis11** [comment]
I think so, IIRC Lauri fixed these in all the vanilla subs

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
