### ISSUE TITLE
Ballast Flora causes errors on dedicated server

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#9041]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
1. Any explosion (grenade or "explosion" command ) close to ballast flora causes the error for every player ("_Received an update for an entity that doesn't exist_").
2. If a respawn shuttle is infected with flora and undocks (and disappears) from the main submarine, the following error pops up (on client side): "_Message byte position incorrect after reading an event for the entity "Barotrauma.Hull" (ID 7805). The previous entity was "" (ID 0) Read 16 bits, expected message length was 112 bits.
recieved msg 42432, entity 18432 not found._" 

Server doesn't crash. It is possible to end the round from lobby by a console command.

**Version**
0.17.15 Windows dedicated server.

**Comment by Regalis11** [comment]
Seems to have been fixed by the fixes I did to address https://github.com/Regalis11/Barotrauma/issues/9024

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
