### ISSUE TITLE
Switching the sub loses the preview images of the subs

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#9042]
After returning to the outpost
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/ca6402c6-1091-4083-ab94-02616c9c9533)

After entering the next outpost, both submarines images are lost:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/1b6a0990-70ee-49b8-b6f2-d024be61a393)

The issue is sometimes(?) partially(?) fixed after reloading the save:
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/fce90f9e-2545-49b6-9e14-af2f9987e693)

Steps:
1. Switch the sub
2. Return to the previous outpost
3. Check the sub switching panel
4. Go to the next oustpost
5. Exit and reload the save

Debug build v.0.17.16.0, possibly earlier. Tested in Regalis11/Barotrauma-development@7b6c5a6.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1cd52b73f739e171dc9a1424834d13c88f38223c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
