### ISSUE TITLE
Barotrauma reading \ as / in item assembly's regex component

### ISSUE THREAD

**Issue by tajetaje** [Regalis11/Barotrauma#9047]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Barotrauma seems to have rewritten the backslashes (\\) in the XML file for an item assembly into forward slashes (/)

[The inconsistency](https://i.imgur.com/1H6xBmt.png)

**Steps To Reproduce**
1. Subscribed to https://steamcommunity.com/sharedfiles/filedetails/?id=2625060379
2. Enabled the mod
3. Opened sub editor
4. Placed Airlock[RTL,BtnDoor]
5. Regex components are wrong

**Version**
0.17.15.0
Windows 11

**Additional information**
N/A: even happened when placing the assembly in the mod's included demo sub (worth noting that the demo sub itself worked fine)

Below is the mod's contents from my PC
[2625060379.zip](https://github.com/Regalis11/Barotrauma/files/8605819/2625060379.zip)

**Comment by WrillWasTaken** [comment]
I believe I had a similar issue with the game converting \ in xml to / in-game when trying to make logbooks with a multi-line welcome message, though I haven't tested it properly.
