### ISSUE TITLE
Character preview breaks when hair and accessories are removed and re-added

### ISSUE THREAD

**Issue by emmyposs** [Regalis11/Barotrauma#9051]
- [x] I have searched the issue tracker to check if the issue has already been reported.
*Most likely related to #8292*

**Description**
Character customization preview rendering breaks when the hair, accessory, and (if applicable) facial hair sliders are set to 0, then any slider is changed back off of 0.
This breakage persists until the game is restarted.

**Steps To Reproduce**
Go to any screen with one or more character customization panels, set all sliders for all characters to 0, move any slider back off of 0.

**Version**
Barotrauma build v0.17.15.0, Arch Linux 5.17.3-arch1-1 x86_64

https://user-images.githubusercontent.com/96921124/166340506-4aff3075-6539-4fef-b614-dd8773727bed.mp4

**Comment by MichaelPetersen22** [comment]
I have also experienced this issue on Barotrauma for Arch Linux

**Comment by emmyposs** [comment]
After further testing I've found that the steps listed above are not guaranteed to cause this bug - from the netgame lobby screen, setting all sliders to 0 and back did not break the preview. Instead, the preview broke immediately after returning to the lobby screen after ending the round.
The steps listed in the main post worked again after restarting the game.

**Comment by Rokvach** [comment]
Tested on linux, didn't spot any issues. Working correctly, closing.
