### ISSUE TITLE
PUC suit injector lagging the whole game.

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#9054]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Apparently if you have allot of PUC suits and Medical items inside the PUC suits it lags the game allot noticeably, only when you have an item inside the injector it lags out.

**Steps To Reproduce**
Spawn 100 puc suits with humans and start putting steroids in them.. 

**Version**
0.17.15.0 (all)

**Additional information**
I have not tested this my self. But it was brought to my attention by an very reliable source, so reliable that I'm doing this bug report based on their word.

They have tested it with player's only not AI.

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this, although I tested it with only 10 humans wearing PUCS. I suspect it might have been caused by something else? If the testing was actually being done with 100 humans, then that's the problem: that many humans will tank the framerate even without PUCS.

**Comment by JoneKone** [comment]
I'm now thinking it was something else that caused the failure.. as I have been testing and testing.. and nothing.
