### ISSUE TITLE
Player can put items into own inventory despite being inaccessible

### ISSUE THREAD

**Issue by emmyposs** [Regalis11/Barotrauma#9057]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players controlling a character whose inventory is marked inaccessible while alive can pick up items and take items from other characters. In a multiplayer game, items taken from other characters will drop from the controlled character after around 1 second.
Items in static containers (e.g. lockers, shelves) are unaffected, and cannot be taken this way without first being dropped on the ground.

**Steps To Reproduce**
Start a singleplayer or multiplayer game, spawn a Husk, take control of it, try to pick up a dropped item or grab another character and try to take an item from them by double-clicking it.

**Version**
Barotrauma v0.17.15.0, Arch Linux 5.17.3-arch1-1 x86_64

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6eec10ec336993638606541d720d9b2fde46c32c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
