### ISSUE TITLE
Level floor isn't rendered in sonar

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9058]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Teleport sub to the bottom of the abyss

Multiplayer
Sub: Typhon 2
Single mission mode
Gamemode: Pirates
Seed: S6eLLsL0
Difficulty: 100%

**Version**
0.17.15.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/940413854d072d8db8fa24c44d9c582658cf8607

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f6fb1a8c-755a-4676-88ee-5e56a75337d3)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bc0074d8-ad06-40b8-91db-346236821271)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0932fbeac6de976de96c2dbecf9a48acafed15db

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
