### ISSUE TITLE
Level walls don't have collision

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9059]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Teleport sub above abyss mountain and notice that you can just go through it

Multiplayer
Sub: Typhon 2
Single mission mode
Gamemode: Pirates
Seed: S6eLLsL0
Difficulty: 100%

**Version**
0.17.15.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/940413854d072d8db8fa24c44d9c582658cf8607

**Comment by Regalis11** [comment]
Seems to apply to all walls

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/18d234db9b8c3acd802ceff3e737aae884554271

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
