### ISSUE TITLE
publishing workshop item with image that does not meet steam requirements spits an error

### ISSUE THREAD

**Issue by EgorIII** [Regalis11/Barotrauma#9060]
story
i tried to publish a submarine with 4 k wiki image, it started uploading, then errored that publishing to the steam workshop is failed.
Directed by the usefulness of that error, i poked around and found that steam workshop indeed has a limits of filesize, and resolution of an image. So i compressed the image and was able to upload successfully
 
reproduce
So to reproduce you try need to upload to workshop with preview image heavier than 2 MB or larger than 2000x2000 (not exact idk)

version
latest stable version 17.15.00, linux and windows run on multiple proton versions (that was not the problem)))

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/96cd6f3c71e45769d78c271c3b41f18546dad54b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
