### ISSUE TITLE
[Dev version] Item scale that has been set in the sub editor does not save/resets to default

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#907]
Perhaps an ability to edit item scale in the editor was not intended, in which case this issue is a request for that to be a feature. Otherwise this is a bug report or just a reminder.
 Some subs would look nicer with bigger looking guns, other subs would be better with smaller looking guns; some smaller subs would be able to fit items that otherwise don't fit inside them, and for bigger subs it would make sense to have bigger looking machines, etc.
 There might be some problems with interaction or collision boxes because of them not getting their scale changed with the sprite, but i think it would still work pretty well and be useful as long as sub makers would do it to items, that work well with resizing, and wouldn't make the items too big or too small.

**Comment by BillCombs** [comment]
Nevermind, judging by 693176e, i guess it's just still WIP.
I probably shouldn't be pushing the progress of features that were implemented very recently. Will try to do more research before requesting features or reporting bugs next time.

**Comment by Regalis11** [comment]
Yep, currently the scale feature does not affect many of the things it should affect, so it's only enabled to allow testing different sizes of items and to set the scale in directly in the XMLs (in which case the properties like collider sizes, handle positions etc can be manually adjusted accordingly).
