### ISSUE TITLE
[Feature Request] Medical Fabricators in stations

### ISSUE THREAD

**Issue by Coduss** [Regalis11/Barotrauma#9071]
So, my friends and I tend to stick to smaller subs like the Dugong, but that limits us on our fabrication abilities. normally this is fine, because most stations have a deconstructer and a fabricator, but no station we've been able to find, including research outposts and colonies, have a medical fabricator available for use.

Would it be possible to get them added in at some point?

**Comment by danielasteljoki** [comment]
Added med fabricators in 39a0719.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
