### ISSUE TITLE
Crashlog: System.NullReferenceException  (line: 579)

### ISSUE THREAD

**Issue by my-digital-plug** [Regalis11/Barotrauma#9072]
This crash seems to happen whenever i go to power up a beacon.  I remember the last couple times and they were right as i power on the nuclear generator and flip it to auto.

**Exception:** _Object reference not set to an instance of an object. (System.NullReferenceException)_

**Target site:** _Void .ctor(Barotrauma.Identifier, System.String, System.String, Barotrauma.Either`2[Barotrauma.Job,Barotrauma.JobPrefab], System.String, Int32, RandSync, Barotrauma.Identifier)_

**Stack trace:** 
_at Barotrauma.CharacterInfo..ctor(Identifier speciesName, String name, String originalName, Either`2 jobOrJobPrefab, String ragdollFileName, Int32 variant, RandSync randSync, Identifier npcIdentifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\CharacterInfo.cs:line 579_

![Code_evTVpXIj8y](https://user-images.githubusercontent.com/11957909/167035132-da3af72b-c935-41ff-8c22-6c8f95edf013.png)

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately wasn't able to reproduce this in the vanilla game. The error message seems to indicate that the game was trying to create some type of a husked character (not the "husk" species though), which should not happen in the vanilla game as the beacon missions only spawn crawlers, mudraptors, husks or threshers. I assume you are using some kind of mods? Any idea if any of them modify the beacon missions in any way?
