### ISSUE TITLE
Wreck salvage missions seem either incredibly rare or don't appear naturally anymore.

### ISSUE THREAD

**Issue by PetMudstone** [Regalis11/Barotrauma#9083]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I have been playing a multiplayer campaign for a while now and not once did we come across a single wreck salvage mission in about two dozen hours of play. We have entered into the Aphotic Plateau at this point. 
While we have been using mods, none of them should modify mission probability. Additionally I've tested solo without mods and have docked 40 times at settlements. I have not seen a single wreck salvage mission appear any of those times.

### Reproduction steps

1. Play campaign.
2. Dock at multiple settlements.
3. Never receive a wreck salvage mission.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The only change we did to wreck missions in the recent update was to prevent them from appearing in levels below 20% difficulty (= they shouldn't start appearing until you leave the Cold Caverns). The probability of getting a wreck mission seems to be about 10%, so it seems unlikely that it was just bad luck you didn't run into one, but testing this myself I was able to get a wreck missions after a dozen or so rerolls in the Europan Ridge. That might still be too rare though, so I think I'll bump up the commonness a bit.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/248e40e58d4b5edde8008471028b77d47b795cee

**Comment by PetMudstone** [comment]
Ah that makes sense that they don't appear in certain difficulties. I did roll a dozen times in the Plateau and didn't get a wreck salvage mission there during testing.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
