### ISSUE TITLE
Use local chat as default option missing

### ISSUE THREAD

**Issue by NiiloKH** [Regalis11/Barotrauma#9087]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There used to be a setting to have voice activated voice chat be proximity by default but that button is now missing from the options menu and can only be toggled through the config files.

### Reproduction steps

Open voice settings

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NiiloKH** [comment]
Setting found in config_player.xml as "uselocalvoicebydefault="

**Comment by ekqvist** [comment]
Will be addressed with the implementation of Regalis11/Barotrauma-development#1593 as it will be possible to toggle the mode between local and radio with a separate keybind

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
