### ISSUE TITLE
Server doesn't load mods.

### ISSUE THREAD

**Issue by neohary** [Regalis11/Barotrauma#9088]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I followed[ this wiki guide](https://barotrauma.fandom.com/wiki/Enabling_Mods_on_a_Dedicated_Server ) to install some mods from Steam Workshop, but when I start the server, the server still says it's vanilla. Did I missed something?
Here is my server's config_player.xml and my Mods folder.
![QQ截图20220508192837](https://user-images.githubusercontent.com/66161411/167294271-8c454cbb-7497-48fc-a945-3853374567cd.png)

### Reproduction steps

1. Create Mods folder under Barotrauma Dedicated Server directory
2. Copy the mods into Mods/ directory
3. Change the config_player.xml
4. Run DedicatedServer.exe
5. Server not load any mods
![QQ截图20220508193701](https://user-images.githubusercontent.com/66161411/167294383-0f15435b-a052-497a-9a93-ba6d04b8a2c8.png)

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The Fandom wiki is severely out of date, I recommend using the [official wiki](https://barotraumagame.com/wiki/) instead.

Looks like the instructions on enabling mods on a dedicated server are actually out of date too. As of the latest update, mods are now installed in the AppData folder (`C:\Users\[user]\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods`), the same place as the game's save files.
