### ISSUE TITLE
AI pathfinding on Orca 2

### ISSUE THREAD

**Issue by AFK-TankyMOFO** [Regalis11/Barotrauma#9090]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The there's a hull breach in a Ballast Tank, instead of going in there to seal it up, AI will go to the Ballast tank next to it, and slam their face repeatedly against the wall, trying to get to the hull breach.

Pathfinding in Orca 2 also need improvement in general, they take a long time to fix the most simple leak in outer hull.

### Reproduction steps

1. Start a single player campaign.
2. Use Orca 2.
3. Order AI to fix leaks.
4. Blow a huge fucking hole in Ballast Tank B.
5. Find AI in Ballast Tank C.

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@c8a7eb1. I don't think these issues are specific to Orca2 or any other sub.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
