### ISSUE TITLE
Misplaced hull in beacon station

### ISSUE THREAD

**Issue by Maks300091** [Regalis11/Barotrauma#9091]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![602960_screenshots_20220508214425_1](https://user-images.githubusercontent.com/105166144/167305244-f25a10d7-3be3-4126-85c7-889812d2dc04.jpg)
Недоработка в Hull

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/12d17b04205eb335c3063d359790a4ff9ef2619f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
