### ISSUE TITLE
I just can't get the "don't you die on me!" Achievement. 

### ISSUE THREAD

**Issue by Scubsterr** [Regalis11/Barotrauma#9096]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For context I have tried every single game mode for this, even singleplayer campaign. I don't have any cheats enabled.

Even when they are collapsed, unconscious, bleeding heavily, not breathing, and are below the 25% health mark in critical state, I revive them of every ailment they have up to 100%, I don't get anything for it.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
It seems that this achievement actually only triggers if you revive someone by performing CPR. I adjusted the description of the achievement now to make it more clear.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
