### ISSUE TITLE
Character position is incorrect when using a flipped periscope

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9097]
**Description**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f8d79a6c-5f30-4fd8-9916-c75c9edaaa85)

**Steps To Reproduce**
Load up Dugong on sub editor test mode and use the right side periscope, notice how your character looks while using it

**Version**
0.17.15.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/58a5cd3c98254a8cc4e8da748f416e42e0c6f1c3

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@2b07cec.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
