### ISSUE TITLE
Unable to detach wired components

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9100]
**Description**
I tried to detach a terminal from Humpback reactor room and it threw an error

Seems to happen with any item that are wired and can be detached

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0a90462d-1cfd-48b6-a7c2-18331eb33f80)

**Steps To Reproduce**
1. Load up Humpback in singleplayer
2. Navigate to the reactor room
3. Equip a wrench and try to detach the terminal
4. Error should come up
5. A wire will drop to the ground but the terminal doesn't detach

**Version**
0.17.15.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/70c77249f597cd9c7d51734ee39c6ac327bee162

**Comment by Regalis11** [comment]
Seems to have been caused by feature/connection-wires-simplification, fixed in https://github.com/Regalis11/Barotrauma-development/commit/61aca5399ab34608dfde2f8bab3bc676a218daaf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
