### ISSUE TITLE
Toxin cabinet isn't restricted in Dugong

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9101]
**Description**
The newly placed toxin cabinet in Dugong doesn't have a restricted access, most likely the same for all the submarines which didn't previously have one but now does due to the item transferring feature. 

**Steps To Reproduce**
Load up Dugong and open the toxin cabinet with a class which isn't Captain or Medic. 

**Version**
0.17.15.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/4172539ec125de47fd5535952cebb1e5f9f66d68

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@0203b14.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
