### ISSUE TITLE
Outpost Event is bugged

### ISSUE THREAD

**Issue by Redofreko** [Regalis11/Barotrauma#9102]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the outpost event where you try to intervene with a group of juveniles vandalizing an outpost in which you get attacked there is a bug where when you are attacked, security guards on the outpost do nothing to stop it unless they are indirectly hit. If the player tries to defend themself against the juveniles then they will be handcuffed and the game will potentially softlock

### Reproduction steps

1. Try to intervene juveniles
2. Try to fight back

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d461a52a8f900b193f96cfae8ac6988fbde47dc1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
