### ISSUE TITLE
kicked out of lobby after spawning endworm

### ISSUE THREAD

**Issue by Dailyyy** [Regalis11/Barotrauma#9107]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Attempting to spawn in an Endworm that I made a mod for to play a sound file will kick you out of the lobby. It also told me to send this file.
[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/8675516/networkerror_data.log)

### Reproduction steps

1. Use my mod (file is attached)
2. Make a server and enable cheats
3. Spawn in Endworm.
4. Get kicked out
[Final Hours Endworm.zip](https://github.com/Regalis11/Barotrauma/files/8675525/Final.Hours.Endworm.zip)

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

**Comment by Regalis11** [comment]
This seems to happen as a result of two issues:
1. The sound file doesn't seem to be a valid .ogg file. I'm not sure what the actual format of the file is, is it an mp3 file renamed as .ogg?
2. The client fails to spawn the endworm because loading the sound fails, but the server doesn't load sounds so it succeeds in spawning it. This leads to the networking error you received.

**Comment by Regalis11** [comment]
Fixed the 2nd issue in https://github.com/Regalis11/Barotrauma-development/commit/a28692561000cfd120765cbf5c0ead255e0959bf, the sound failing to load seems to be an issue with the mod itself

**Comment by R4to0** [comment]
>     1. The sound file doesn't seem to be a valid .ogg file. I'm not sure what the actual format of the file is, is it an mp3 file renamed as .ogg?

Just checked the file, it is using **opus** codec instead of **vorbis**, which both uses the ogg container. OP should convert the audio file properly to vorbis I think.

```
Audio
ID                          : 3458031319 (0xCE1D5ED7)
Format                      : Opus
```

**Comment by Dailyyy** [comment]
yeah i figured this out. idk why this happened

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
