### ISSUE TITLE
Giant spineling's spike seems weakened…maybe？

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9109]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After v0.17.X.X, giant spineling‘s spike seems lost its powerful penetration, before the v0.17.X.X, the spike can easily penetrates multiple layers of shells. Is this an unmentioned change or a bug？

### Reproduction steps

Spawn spineling_giant, and see its spike's penetration.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@74211e8.

**Comment by Rokvach** [comment]
Tested, didn't notice any issues, looks correct to me. Closing.
