### ISSUE TITLE
Add a "false output" setting to Regex Find component

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#911]
The more i mess with components and wiring, the more i notice that the size and complexity of the wiring system affects ingame performance quite noticeably(at least on weak PCs). The more complex and big the wiring is, the more noticeable the fps loss is.

Having no setting such as "false output" in the Regex Find component makes you have to use additional components to make the system work, which creates an additional loss of performance that could be optimized.

I think the wiring should require as least additional components as possible. Not only it would help with performance, but it would also be more convenient for players to work with it in the actual game.

**Comment by Saevon** [comment]
Is this no longer in the game?  I'm on 0.11 and there is no "false output" setting for the regex find component
