### ISSUE TITLE
[Wallet] Players with no permissions don't have any access to request money

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9112]
**Description**
Players can't request or even type anything on the input field when they don't have any permissions and there's a host on the server

**Steps To Reproduce**
Play with two clients, give host to one client and with the client that doesn't have any permissions try and use the wallet. 

**Version**
Unstable 0.18.0.0

**Comment by Regalis11** [comment]
Seems to have been caused by https://github.com/Regalis11/Barotrauma/issues/8718, the clients keep the input box disabled if MaximumTransferRequest is set to 0, and if the client has no permissions to manage the settings, it will always stay at 0 client-side.

**Comment by Rokvach** [comment]
But I set the maximum amount to be 500

**Comment by Regalis11** [comment]
Yes, but if the client has no permissions to manage the settings, it will always stay at 0 client-side.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/49ba3453a894054093d91f825e8cb3b8ac52b730

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
