### ISSUE TITLE
Server description cuts off after line 22/23

### ISSUE THREAD

**Issue by TerraTheUnwise** [Regalis11/Barotrauma#9113]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm hosting a server called Subonized. And a good 90% of the players report not being able to see past line 22/23. I have no mods enabled. And it's a vanilla RP server. I honestly have no idea why this happens.

### Reproduction steps

1. Start a multiplayer server.
2. Join.
3. Not be able to see past line 22/23
4. Give the host a headache.

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by TerraPlanet** [comment]
erm

**Comment by ekqvist** [comment]
Not sure what the cause of this is, but it seems that the text is there, but the element just won't scroll enough.

**Comment by TerraPlanet** [comment]
It's an anomaly for sure.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab0c730b29588fa82c33019bc4675a599ac3d477

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
