### ISSUE TITLE
[Unstable] Disposable diving suit can't go inside diving suit locker

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9114]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Disposable diving suit can't go inside diving suit locker.

Can't put them in the locker in editor

They spawn on the ground in respawn shuttles
![image](https://user-images.githubusercontent.com/73229309/168116775-113c1f5f-06ca-4e4b-90f9-c19a3ed5b248.png)

**Comment by itchyOwl** [comment]
Fixed in Regali11/Barotrauma-development@afe526c. The disposable suit seems to be using the same sprite as the abyss suit. Not a big thing, but we might want to change it?

**Comment by Rokvach** [comment]
Tested, working correctly. Just needs the proper art which I think Iiro is working on so closing.
