### ISSUE TITLE
[Unstable] Disposable diving suit can used with 0% condition via using a diving mask 

### ISSUE THREAD

**Issue by AbyssBeast09** [Regalis11/Barotrauma#9117]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

 Disposable diving suit can used with 0% condution via using a diving mask 
 Just wait a 0% condution of a suit and wear a diving mask 

### Reproduction steps

1: Spawn and wear a Disposable diving suit
2: Wait for 0% condution
3: Wear a diving mask 
![Screenshot_35](https://user-images.githubusercontent.com/85645359/168121124-f225eb0e-9195-475f-bba4-a8b8803a558e.png)

### Bug prevalence

Happens regularly

### Version

Other

### -

Barotrauma Unstable V0.18.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
