### ISSUE TITLE
Unable to copy error messages from console, context menu renders behind console

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9119]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to copy error messages from console by right clicking them the context menu is rendered behind the console

### Reproduction steps

1. Receive a error
2. Try and copy it
3. Notice that there is no context menu
4. Close console
5. Context menu is shown

### Bug prevalence

Happens every time I play

### Version

Other

### -

Unstable 0.18.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eccd24ccda9fe39980f24490f7b415f79fab9eda

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
