### ISSUE TITLE
[Unstable] Loading a old campaign causes headsets to stop functionating

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9120]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Loading a campaign save that was created before v0.18.0.0 causes headsets to stop functionating.

Campaign File:
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/8680943/Multiplayer.zip)

### Reproduction steps

1) Load up a campaign that was created before the version v0.18.0.0
2) Watch you unable to send radio chat messages, because your headset doesn't work

### Bug prevalence

Happens every time I play

### Version

Other

### -

Unstable v0.18.0.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

__None

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/777fd61c7ded88b0a0d44267a3a16eba0bf87013

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
