### ISSUE TITLE
[Sub-Editor]: Hull Integrity toggle on status-monitor does nothing.

### ISSUE THREAD

**Issue by aeldred28** [Regalis11/Barotrauma#9121]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Since the feature was initially implemented, players have no option of disabling the hull integrity warning on subs despite there being a toggle for it. Therefore players cannot disable the buff for challenge purposes, or to create legacy gameplay-feature subs. 

![Untitled](https://user-images.githubusercontent.com/75105816/168148532-1f641741-3cba-49c2-980d-2cf93bac40b7.png)

Results:

![Untitled2](https://user-images.githubusercontent.com/75105816/168148800-d9ced8be-6ea7-4653-b3cc-aaab24d6ef53.png)

### Reproduction steps

1. Toggle Status monitor options, unchecking Hull Integrity or any combination of other toggles.

2. Test in editor or in a campaign/mission by damaging sub walls.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd7eb3a1a14bff0680289e0283e4f74c3983615f

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
