### ISSUE TITLE
Remove equipment icons next to the character portrait

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9125]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/44423036/168186245-2d4564c3-c628-4f53-b700-9fdcd2e6cad0.png)
I think it should be green?

### Reproduction steps

start a campaign and see the headset icons

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.18.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Todo note: let's get rid of that whole panel as it doesn't serve much purpose any more
![image](https://user-images.githubusercontent.com/14351070/168251533-3a6fb533-b2bc-4bc4-b6fb-e1bd3a9496a1.png)

**Comment by Rokvach** [comment]
Should the healthbar be aligned with the portrait or is this a resolution issue?
![image](https://user-images.githubusercontent.com/7299826/170986350-1290a6ec-e4fd-420c-8171-bb6c38d3e612.png)

**Comment by ekqvist** [comment]
Should be fixed in af98b56

**Comment by Rokvach** [comment]
Seems like the gap is a bit larger now
![image](https://user-images.githubusercontent.com/7299826/171576633-bc70adb4-82fa-44ce-88da-5499c4925e05.png)

**Comment by ekqvist** [comment]
Should be fixed in 7768bf2 (fingers crossed)

**Comment by Rokvach** [comment]
Looks perfect now, closing.
