### ISSUE TITLE
Elements overlap in the server settings menu

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9127]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There's some overlap in the gameplay-tab of the server settings menu if the vertical resolution is below 1000px or so
![image](https://user-images.githubusercontent.com/14351070/168248412-8d713b1a-0772-4046-884b-e73f330ded94.png)

### Reproduction steps

1. Set vertical resolution below 1000px
2. There's not enough spacing between the "line of sight effect" label and the elements above it

### Bug prevalence

Happens every time I play

### Version

0.18.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ccd8b8baf1d20735b8296acd5bb13c39796e6305 the whole screen still breaks when changing resolution but I believer that's another issue we have a ticket of

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
