### ISSUE TITLE
Dropped diving suits have their helmet light on after level transition or when sub is spawned

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9128]
**Description**
Noticed that the new respawn suits had their lights on when a respawn shuttle spawned and later on when I spawned PUCS to the floor of a submarine and transitioned to the next level all the suits had their lights on as well. 

**Steps To Reproduce**
Start singleplayer campaign, navigate to sub and spawn diving suits to the floor or take diving suits off the lockers. Leave outpost and notice that all of the suits will have their lights on

**Version**
Unstable 0.18.0.0

**Comment by Regalis11** [comment]
Seems to have been caused by https://github.com/Regalis11/Barotrauma-development/commit/91c62128a7db3604a31fa886e65e42cc2104dc62, fixed in https://github.com/Regalis11/Barotrauma-development/commit/3b35cecdc240c0c43aed9e96912f65fa88f319a4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
