### ISSUE TITLE
Captain Hognose's Appearance Inconsistencies

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#9129]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**What we were looking for:** 
Inconsistencies within the appearance of the Captain Hognose NPC. Specifically, if the skin tone, beard type, gender, and accessories were consistent across instances of Captain Hognose. **We looked for this as there was concern that the visual representation of Captain Hognose did not match the written description of Captain Hognose.**

**What was tested:** 
600 Hognose events across 6 campaigns split between both stable and unstable versions of the game **(0.17.15.0 and 0.18.0.0 respectively).** 100 Hognose spawns per campaign, three campaigns per version, each campaign was created using a new seed but with the same submarine. 

**What we found:** 
We discovered that the only variables that remains consistent are the **skin tone, beard colour, beard type**, and **uniform** of Captain Hognose. The gender changes at a rough ratio of 7:3 (male:female). The beard is **not** certain to spawn, and the eyepatch accessory has a 0% chance to spawn with Captain Hognose.

**What was not tested:** 
If the skills of Captain Hognose are accurate to the code or not. Honestly I'm not sure if the game allows for 100 instances of Captain Hognose to exist in a submarine at a single point in time.

### Reproduction steps

1. Load a new campaign
2. Enable cheats in the console commands (speeds up the process)
3. Type "triggerevent hognose"
4. Repeat step 3 100 times for an accurate sample pool of Captain Hognose
5. Observe the visual differences between each Captain Hognose which spawns

### Bug prevalence

Happens regularly

### Version

0.18.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, all captains looks identical now. Working correctly. Closing.
