### ISSUE TITLE
Abyssal creatures sometimes unable to attack submarines at seafloor 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#9130]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**The issue at a glance**
Submarines can be sunk to the seafloor by an abyssal creature, at which the abyssal creature will retreat and stop attacking the submarine. As soon as the submarine starts moving up, the abyssal creature will return to attack the submarine.

**What we tested:**
Start a multiplayer lobby with 16 bots. Mode: mission (any). Order the bots to operate the guns. Send the submarine to the seafloor. Turn on sonar on navigation terminal. Spawn an endworm within several different distances of the submarine (including right next to the submarine). Turn debugai on and observe the behaviour of the endworm. 

**What we found:** 
The endworm would continuously move directly towards the submarine, then turn around and retreat after travelling a short distance (as a guess, I'd say 10 meters). After a while, it would repeat this behaviour, clearly trying to target the submarine but being unable to get close to it. 

**Current theories:** 
The current theory behind the issue is that some levels have the seafloor and abyssal end at different levels, making it possible for submarines to sink out of the abyss. Since abyssal creatures cannot leave the abyss, this causes them to start a targeting loop in which the creature continuously tries to attack the submarine, only to retreat back into the abyss since they are unable to leave it. This means that the moment the submarine enters the abyss again, it is pushed back down out of the abyss.

![image](https://user-images.githubusercontent.com/105495756/168300347-b545beca-e778-4074-aae6-2ae05d0cc061.png)

(Image for reference)

### Reproduction steps

1. Bring a submarine down to the seafloor.
2. Spawn an endworm (unsure if every abyssal creature behaves like this, though they probably do).
3. Observe its behaviour and see if it can attack the submarine.

### Bug prevalence

Happens every now and then

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is actually intentional: the abyss creatures try to stay within the designated "abyss area". What wasn't intentional though was that the abyss area was this small in the aphotic plateau, fixed in https://github.com/Regalis11/Barotrauma-development/commit/a866ed776efac2fe45fb615fcd892ff63c00f89b

**Comment by Rokvach** [comment]
There can still be levels where the abyss doesn't stretch all the way down to the level floor in aphotic plateau

1. Load up level editor
2. Use seed axET5V7E
3. Hit generate
4. Look at the abyss height
4. Test the level, set sub to godmode and teleport it right above the level floor and spawn creatures near the sub and notice that the abyss creatures just ignores the submarine and swims to the abyss area. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/53bc0e48-9f18-47a4-9b50-295d72f190af)

**Comment by Regalis11** [comment]
2nd attempt: https://github.com/Regalis11/Barotrauma-development/commit/04c5835f66e62f194a37d2f8806203871ed9f5c9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
