### ISSUE TITLE
Chaingun Ammunition Boxes have visible sprite looping

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#9131]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Well simply enough, the sprites for the boxes of specifically chaingun ammo have visible lines sticking outside the box itself, presumably from Sprite Looping, easy to see in sent image. Its especially notable for the Shredder ammo boxes
![Shredder](https://user-images.githubusercontent.com/104232152/168306806-2bb403ab-c913-48dd-9963-699f590de649.png)

### Reproduction steps

1.Taking a good look at chaingun box sprites

### Bug prevalence

Happens every time I play

### Version

0.18.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Fixed in 3d3603caefb837c7664d98472fec22d3e2daa647 by adjusting the sourcerect. 
The containers.png might be too cramped atm, so let me know if it needs a different solution.

**Comment by Regalis11** [comment]
The colliders of the boxes are now slightly too large, making them hover above the floor

**Comment by IiroEnges** [comment]
I trimmed the containers a bit, I'll adjust the source rects as well

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
