### ISSUE TITLE
[Unstable] Energy drink / Protein bar issues

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9132]
**Description**

- [x] **Energy drink / Protein bar can by instantly used like medicine via medical interface**
Open medical interface, use either drag n drop or hotkeys and the item is used instantly like a syringe

- [x] **Haste buff duration is different based on application**
If you "drink" the drink, the Hyperactivity buff lasts about 5 seconds
If you apply it via medical interface, it lasts much longer.

- [x] **50% chance of nausea cancels energy drink benefits**
Nausea will slow you down and occurs too often so it defeats the purpose of the drink

**Comment by Regalis11** [comment]
The 1st one is intentional.

Fixed the 2nd issue in https://github.com/Regalis11/Barotrauma-development/commit/847f75b880449276db9164c8189c72a1e5c3f9c7
