### ISSUE TITLE
lategame items spawning in early game

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#9133]
Please use the other report form to report issues. This old template is only here until we've replaced the bug report links in the game.

**Description**
the new loot tables seem to be spawning a few late game items pretty early on, here's a list of odd things i found in cold cavern's outpost lockers, wrecks and beacons
-hardened/dementionite tools (outpost and beacons)
-fulgurium fuel rods (beacons)
-combat diving suits (wrecks)
-handcannon rounds (wrecks)

the reason of this ticket is that i personally find this makes a lot of talents less useful

**Version**
v0.18.1

**Comment by itchyOwl** [comment]
Better to fix this in the level-progression branch, because of the changes to the difficulty level.

**Comment by JeroonBosch** [comment]
Might need some additional parameter for 
`<PreferredContainer primary="wreckdivingsuitcontainer" spawnprobability="0.05"/>`
like so:
`<PreferredContainer primary="wreckdivingsuitcontainer" spawnprobability="0.05" minleveldifficulty="35"/>`

**Comment by JeroonBosch** [comment]
Fixed the initial bug in dev, might want to expand with a minleveldifficulty tag to make loot spawning gradually better? Will create new issue for that.

**Comment by cshingle** [comment]
> Fixed the initial bug in dev, might want to expand with a minleveldifficulty tag to make loot spawning gradually better? Will create new issue for that.

I had my sub spawn at the beginning of a recent campaign (after the hotfix) with abyss suits in 2/3rds of the lockers. This issue affects divingsuitcontainer as well as the wrecked variant.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
