### ISSUE TITLE
hammerheads mission too cheap (sometimes)

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#9134]
Please use the other report form to report issues. This old template is only here until we've replaced the bug report links in the game.

**Description**
the mission where you hunt 1 to 3 hammerhead_m can be cheap sometimes if you get 2 or 3 hammerheads_m which already makes for a fight as hard as fighting a moloch_m is

opened this ticket just to ask for a slight raise in the reward, maybe 2000

**Version**
v0.18.1

**Comment by JeroonBosch** [comment]
Part of level-progression branch

**Comment by Rokvach** [comment]
Tested, looked fine to me. Closing.
