### ISSUE TITLE
[UNSTABLE] Can't completely unload the rubber shells from shotgun

### ISSUE THREAD

**Issue by Ramlik** [Regalis11/Barotrauma#9140]
### Discussed in https://github.com/Regalis11/Barotrauma/discussions/9124

<div type='discussions-op-text'>

<sup>Originally posted by **Ramlik** May 12, 2022</sup>
Basically, [here](https://gyazo.com/52a91b7528807af81f90d5c306ece408) is how it works </div>

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this.

**Comment by Regalis11** [comment]
No known steps to repro, closing
