### ISSUE TITLE
[Unstable 0.18.1.0] Midround joining client got a update for a item which doesn't exist

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9141]
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is a duplicate but wanted to record it down as it has all the necessary documents to potentially figure what caused it. 

Hosting a multiplayer campaign and a new client joined in middle of a round and each time they tried to spawn in they got a missing entity error. Had to wait until we reached the next level until they were able to join. 

Server
[event_error_log_server_Renko_2109.log](https://github.com/Regalis11/Barotrauma/files/8693927/event_error_log_server_Renko_2109.log)
[event_error_log_server_Renko_2108.log](https://github.com/Regalis11/Barotrauma/files/8693929/event_error_log_server_Renko_2108.log)

Client
[event_error_log_client_Renko_2109.log](https://github.com/Regalis11/Barotrauma/files/8693930/event_error_log_client_Renko_2109.log)
[event_error_log_client_Renko_2108.log](https://github.com/Regalis11/Barotrauma/files/8693931/event_error_log_client_Renko_2108.log)

### Bug prevalence

Happens every now and then

### Version

0.18.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro and the logs didn't shed much light into what could've caused this

**Comment by Regalis11** [comment]
No known steps to repro, closing
