### ISSUE TITLE
Stabilozine can't be used in research stations

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9142]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/7299826/168449268-d62f5499-d384-4e8d-9f4b-f2a4ba02a51d.png)

### Reproduction steps

1. Place undefined genetic material and stabilozine to research station
2. Try to research
3. Notice that stabilozine flashes red

### Bug prevalence

Happens every time I play

### Version

0.18.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/641a2a259453f4e60818eba6e22b97b830e37655

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
