### ISSUE TITLE
Submarine equality check failed when host starts a campaign before any client has joined

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9144]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a host starts campaign before any client has joined the server, any client who tries to join the already running campaign will get a submarine equality check failed error and are unable to join. Host has to return back to lobby in order to get the clients to join, once there's at least one client playing on the campaign all new clients are able to join without any issues. 

### Reproduction steps

1. Host a SteamP2P server
2. Start campaign round
3. Ask someone to join your server
4. They will receive an error once they try to join the already running campaign

Not sure if this is possible to do with multiple clients on the same machine

### Bug prevalence

Happens every time I play

### Version

0.18.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
There was an error initializing the round. {Submarine equality check failed. The submarine loaded at your end doesn't match the one loaded by the server. There may have been an error in receiving the up-to-date submarine file from the server.}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1023
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1743

Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__99" has failed
```

**Comment by Regalis11** [comment]
Seems to happen because of https://github.com/Regalis11/Barotrauma-development/commit/5e60e0f1f4065191cca2b0d41315099b213847a3, the server now always saves the sub at the beginning of the round but doesn't use that saved version of the sub.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/820f8e419ad2fee5d84b0a3f7f9c6341ad1fa126 (please read the commit message).

The commit reverts some of the changes done for the item transfer feature. I did verify that the "[fix items not being transferred on quit and save](https://github.com/regalis11/barotrauma-development/issues/3208#issuecomment-1114717747)" issue that the changes addressed didn't reappear, but please try and see if you can find any new issue in the item transfer feature or submarine saving in the campaign.

**Comment by Regalis11** [comment]
The issue reappeared due to https://github.com/Regalis11/Barotrauma-development/commit/4b2eecd, moving back to team 1

**Comment by Regalis11** [comment]
Hopefully fixed now https://github.com/Regalis11/Barotrauma-development/commit/9e200ab2406b66a43e7aa16a0f6dadb4243383de

**Comment by Rokvach** [comment]
Tested, this is working correctly. Closing.
