### ISSUE TITLE
AI bots leaving diving suits on outposts.

### ISSUE THREAD

**Issue by OceanFish1** [Regalis11/Barotrauma#9147]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I just got this happened in my campaign coop session several times. When we dock to an outpost and by the time bots were wearing diving suits (while fixing holes and by other reasons), as soon as they spawn on a docked outpost they immediately drop the diving suit and do nothing about that. Sometimes when I spawn on outpost I see our diving suits laying around and nobody but players are to get those back to the ship. I think we actually lose the suits if we don't get them back.

Ship: Kastrul

My mod collection we were using during the session (if relevant): https://steamcommunity.com/sharedfiles/filedetails/?id=2804465126

### Reproduction steps

1. Play campaign with bots.
2. Make them go fix a hole and get a diving suit to do that.
3. Dock to an outpost while bots are wearing diving suits.
4. Watch cluelessly as AI leaving all your diving suits on an outpost.

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The suits dropped by the bots should get automatically moved back to the sub when you leave. We tested this internally and it seems to be working as expected. Did you notice that they didn't get moved, or did you just assume they would get left behind?
