### ISSUE TITLE
Can't move, errors in console (Error reading character health data)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9148]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The moment I took a storage container in my hands, this console spam started. I couldn't use any keys other than F3 but the console kept immediatelly reopening after being closed. I was able to keep using the mouse. Even after the round changed and a mission ended, it continued. It stopped on its own after about 10 minutes. Rejoining the server didn't help and I couldn't create a new character because each time I rejoined with a different class selected, the game kept me alive as the same character. (which could be another bug)

![Barotrauma_ps6GQo8dvK](https://user-images.githubusercontent.com/10529134/168490124-47c5c991-a510-453c-b6a2-1d36e2c560d7.png)

### Reproduction steps

Most likely caused by a mod being corrupted. I've been told it's caused by downloading mods from the host instead of from the workshop, but I didn't download any mods from the host.

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading character health data: affliction with the uint ID 227313110 not found.
```

**Comment by Regalis11** [comment]
Which mods are you using? I suspect that this is either somehow related to [inventory syncing](https://github.com/Regalis11/Barotrauma/issues/9216) or some custom afflictions (I wonder if there could've been something in the container that causes afflictions when held)?

**Comment by Krzeszny** [comment]
> Which mods are you using? I suspect that this is either somehow related to [inventory syncing](https://github.com/Regalis11/Barotrauma/issues/9216) or some custom afflictions (I wonder if there could've been something in the container that causes afflictions when held)?

Most likely Neurotrauma with LUA

**Comment by Regalis11** [comment]
No known steps to repro, closing
