### ISSUE TITLE
Water detector not matching reported water level in status monitor

### ISSUE THREAD

**Issue by alphasierra59** [Regalis11/Barotrauma#9149]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Attempting to make airlock using a pump set to +-100 water level, reading water level in room using water detector. When pump set to -100 pump stops after draining room. Status monitor shows water level as 0%, water detector shows water level at 1%. 

Manually setting pump to drain will make water detector read 0%, only the automatic target level function isn't fully draining.

### Reproduction steps

1. Make room with doors on each end, pump in room with lever and signal component to send 100 or -100 to target level for pump.
2. Place water detector on floor in room, with text display to watch output of water level.
3. Fill room using pump
4. Drain room using pump
5. Water detector shows 1%, portable status monitor shows 0%.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports
<img width="878" alt="pump error" src="https://user-images.githubusercontent.com/17458293/168493486-0677e4ac-26ec-432b-bd9d-cbaa9d9ffac2.png">
<img width="1062" alt="pumperror2" src="https://user-images.githubusercontent.com/17458293/168493538-2883086f-13f8-4363-ac4b-c53088ec7d66.PNG">

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/045ee2509ea81f07b4e7801270a52e6c541e007e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
