### ISSUE TITLE
Ignore this order doesn't have a tooltip

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9158]
**Description**
There's no tooltip on the ignore this order
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ee2e8d72-aff6-4030-acde-7e10660083d8)

**Steps To Reproduce**
Use shift + MMB on a cabinet and hover your mouse over the ignore order, notice that there is no tooltip

**Version**
0.18.1.0
Branch: dev

**Comment by Regalis11** [comment]
This seems to have affected all orders except "wait here" (the name of the order wasn't displayed on the other orders either), fixed in https://github.com/Regalis11/Barotrauma-development/commit/dec097b30a1dd0d2152fbeac88d69cdc9477f0b6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
