### ISSUE TITLE
Husks aren't able to open automated doors

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9159]
Can be closed if this is intended behavior

**Steps To Reproduce**
1. Load up humpback in singleplayer
2. Spawn a husk near a automated door
3. Give godmode to husk
4. Control husk
5. Try and open any of the automated doors in humpback

Without controlling the husk you can do

3. Spawn human on the other side of the door
4. Notice that the husk can't open the door to reach the human

**Version**
0.18.1.0
Branch: dev

**Comment by itchyOwl** [comment]
I'm not sure if it's a bug. The doors are controlled with motion sensors that target only Humans. Setting that to "Any" should solve the issue. But I guess it's up to the sub designers to decide on it. @danielasteljoki 

![image](https://user-images.githubusercontent.com/5370738/169016264-4cbcb8ed-4da5-4258-9f9b-5c5909a7ec40.png)

**Comment by itchyOwl** [comment]
Or is the motion sensor only for closing the door? Maybe there's a bug afterall?

**Comment by Regalis11** [comment]
This is intentional
