### ISSUE TITLE
Unlimited experience by using research station

### ISSUE THREAD

**Issue by Kommandant420** [Regalis11/Barotrauma#9164]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After the medic unlocks the "Advanced splicing" talent, you can refine or combine genetic materials at a research station to gain experience.
If you combine one genetic material that has already been combined and isnt tainted with another one it does not change the states of the materials and you gain 125 experience. This can be repeated infinitely.

It only works on the winterhalter while it is *NOT* docked at a station, since the winterhalter is the only vanilla submarine with a research station on it.

![Bug1](https://user-images.githubusercontent.com/105808331/169091965-e5a7b9bf-3b56-4524-bedd-57eb93d46f86.png)
![Bug2](https://user-images.githubusercontent.com/105808331/169091980-961be6c2-cf36-4b90-ae9b-085002b4e79a.png)

### Reproduction steps

1. Use the winterhalter submarine and be a medic.
2. Unlock the "Advanced splicing" talent.
3. Gain and refine some genetic materials.
4. Once you have 3 untainted genetic materials, combine 2 of them to get an untainted double genetic material.
5. Make sure you are on a mission with the winterhalter and are not at a station. (While at a station the bug does not work and it combines the materials as it should).
5. Combine the untainted double material with the single genetic material.
6. Repeat for unlimited experience.

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No crashes.
```

https://user-images.githubusercontent.com/105808331/169097491-11f67d5c-5d7f-43ba-ac38-0b5f25f59111.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/41ccc55f14cab445da322a61a9530750bc388c95

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
