### ISSUE TITLE
Purchased Europan Medicine books will drop directly on the floor, not in the metal crate.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9168]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Purchased Europan Medicine books will drop directly on the floor, not in the metal crate.Because it lacks cargocontaineridentifier="metalcrate"

### Reproduction steps

Purchase Europan Medicine, and see what will happen when the goods are delivered.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ab511240d9ead055c93a57ef5f439f476b5a1e9

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
