### ISSUE TITLE
[DEV] Can't interact/repair engine on Turso

### ISSUE THREAD

**Issue by Diffle** [Regalis11/Barotrauma#917]
![image](https://user-images.githubusercontent.com/25946304/48626581-a626e580-e9cb-11e8-91c8-35f4bf14dfe4.png)
To repair it, you need to go to the left edge, and when I do this, I click on repair button, my character trying reach the engine with his hand, and then repair just fails. After that, when the engine emits smoke, neither I nor my engineer can rapair it, because it's considered as repaired(?) and opens power interface.

**Comment by Diffle** [comment]
![image](https://user-images.githubusercontent.com/25946304/48659096-82b07900-ea65-11e8-98dc-c3eef524a905.png)
Even worse. New sprite is fully non-interactive

**Comment by BillCombs** [comment]
Yep. I even tried to go to the other side and repair it from there, but it gave me an error.
![-2018-nov-17-001](https://user-images.githubusercontent.com/38168249/48659588-df239080-ea85-11e8-9bcb-5fe8cc6acd3b.jpg)
I assume the error has something to do with parts of character's ragdoll being pulled too far away from each other.

I think there should be something done to the points of repairing interaction(the points to which the character moves their hands when they are interacting with the object via their tools). Perhaps there could be multiple points of that kind, and the character would only interact with the nearest one.
Or there could be an option to change the position of that one point in the sub editor. So the sub maker could put it at the spot where the object is open to interaction. That would help too.
Those are just suggestions, i have no idea how possible it is to implement such things.

**Comment by Regalis11** [comment]
This should be easy to fix, the trigger areas (~ points of interaction) just haven't been updated on Turso or Polaris after the changes to the dimensions of the engines.
