### ISSUE TITLE
New game+ assigns incorrect colors to biomes

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9170]
**Description**
While testing the level-progression branch I teleported to each of the biomes one by one and then finished the campaign, by loading back to the start of a campaign the cold caverns were tinted green rather than the normal blue.

**Steps To Reproduce**
Play through campaign by teleporting to each biome one by one and take note of the biome color on the new game+. 

**Version**
0.18.1.0
Branch: level-progression (I don't think this issue is limited to this branch)

**Additional information**
Save with wrong color: 
[https://app.zenhub.com/files/93301055/5ef8618b-3535-429b-b8e9-41e57d8dfaff/download](https://app.zenhub.com/files/93301055/5ef8618b-3535-429b-b8e9-41e57d8dfaff/download)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4c0b7a92-5d07-418c-a32a-8c7df3f05264)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/954e5aea-0b71-4258-b83f-14ca397bd0b0)

**Comment by Regalis11** [comment]
Happened because after the difficulty increase the game happened to pick the "coldcavernstransition" level gen params for this level.
