### ISSUE TITLE
Client disconnects if they join in middle of a ongoing vote

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9171]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

We were testing a money request issue while a client tried to join the server

![image](https://user-images.githubusercontent.com/7299826/169335338-283997bd-f305-4616-bf7f-cf1d6e33482c.png)

### Reproduction steps

1. Have client 1 on the server request money from bank
2. Have client 2 join while the money request vote is still on
3. Client 2 disconnects immediately and receives a error

### Bug prevalence

Just once

### Version

0.18.2.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a096cd76739101f2381b23305390b3456434e10

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
