### ISSUE TITLE
Clients can show the new docking verification prompt even when docking via the nav terminal button

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9173]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The clients sometimes show the "trying to automatically dock with the outpost" prompt even when the docking is being done manually. Happens because the sender of the signal from the nav terminal isn't set client-side. The prompt isn't shown always though, because often the server manages to end the round before the client receives the info about the signal being sent.

### Reproduction steps

1. Try to dock to an outpost with Kastrull (which has a somewhat complex docking circuit) in a multiplayer campaign
2. Get the prompt

Might take a couple of tries

### Bug prevalence

Happens every now and then

### Version

0.18.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eb7c8531f95a23bcc6ac1cf6e4411ead040770fb

**Comment by Rokvach** [comment]
Tested, haven't seen this come up since. Working correctly. Closing.
