### ISSUE TITLE
Increasing the amount of experience required

### ISSUE THREAD

**Issue by Prostocvasha** [Regalis11/Barotrauma#9180]
I think the current cost of raising the level is too low, and talents for additional experience are useless.

My last two campaigns have shown that most players already have at least two-thirds of the talents by the middle of the map. And this is for a direct route to the end. Talents are too easy to get, and their conditional value is quite low. For 2-5 people, this is quite good, but with a larger team, I want to see more highly specialized players who will complement each other.

I propose to increase the basic required experience to increase the level by x2-x3 and add a slider modifier of this value to the settings when creating a campaign.

**Comment by VolcanoTheGod** [comment]
I suggest making an experience gain modifier slider in server settings instead
