### ISSUE TITLE
[Unstable] Shuttles gone after purchasing a sub

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9183]
**Description**
If you purchase and switch to a sub with shuttles, your submarine will lose all of its shuttles.
If you dock back to the outpost, the shuttle is floating somewhere in the outpost level

**Steps To Reproduce**
Start campaign with Dugong
Purchase and switch to Kastrull
Load next level
No drone
Dock back to the outpost 
Freecam and look for the drone

**Version**
Unstable v0.18.3.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e918b9d4506ae1ebcbe313426804531c4e1c3f6f
