### ISSUE TITLE
R-29 and small hulls

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#9186]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The bots could not close the leak in the bilge of the cargo compartment. This is due to the fact that the bilge compartment is very small in height, if the compartment is lower than the chest of the character, then the bot will not be able to close the leak in it, although at the same time the bot copes with pump repairs in such compartments. I'm attaching the fixed submarine below, I returned one large hull as it was before + minor fixes to the waypoints on the ladders.
However, this will not fully fix the situation with bots, as similar bugs can occur on players submarines. Without remembering for a long time, I counted 4 pieces with similar ballasts or bilges.
![image](https://user-images.githubusercontent.com/29980468/169633437-66e93667-0689-4b7f-8cbb-b3b8c9e81fc0.png)

[R-29-dev.zip](https://github.com/Regalis11/Barotrauma/files/8746877/R-29-dev.zip)

### Reproduction steps

1. Play on R-29 in any mode.
2. Make a small leak in the bottom of the cargo compartment.
3. Order the bot to seal the leak.
4. Watch the suffering of the unfortunate bots.

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Varangianoi** [comment]
This happens in Unstable too. The bots just run back and forth on top of the cracked point.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6fe7dde6d1e5a47960e068748e602113e117a8a6

**Comment by Rokvach** [comment]
Tested using the repro steps, bots were able to fix leaks without any issues, closing.
