### ISSUE TITLE
Unexpected loss of thrust performance when engine is controlled by logic components

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#9187]
Originally observed on the Orca 2, verified using the Dugong in the editor.

When the following circuit outputs a constant 100 to the engine, the Dugong tops out at 17km/h instead of 22km/h. Electric power uptake is identical.

![Screenshot_20220521_083703](https://user-images.githubusercontent.com/68995233/169640015-19c750b0-e7ad-413b-bde9-a8ae61cd84d0.png)

The circuit is a PWM converter that keeps the thrust at either 100 or -100 to increase the power usage so more depleted fuel is produced for ammunition. **Any circuit controlling the engine will have this effect**

![Screenshot_20220521_084546](https://user-images.githubusercontent.com/68995233/169639771-55f46af2-0cc5-4bfc-995f-c0904f300c13.png)

![Screenshot_20220521_084436](https://user-images.githubusercontent.com/68995233/169640029-465f2e7e-6fbf-4b4e-a6d3-0efd02c21e38.png)

When the navigation terminal `velocity_x_output` is 100, the circuit also outputs a constant 100, verified by a terminal attached to the comparator output. 

### Reproduction steps

Reproduction is possible in the ship editor. (rename the attachment to Dugong.PWM.sub)

[Dugong PWM.sub.gz](https://github.com/Regalis11/Barotrauma/files/8747115/Dugong.PWM.sub.gz)

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Manually dragging the engine thrust on the engine control UI seems affect the top speed as well depending on which crewmember holds the lever.

**Comment by Oukido** [comment]
This one made me curious and I tested it too. I used relays to switch engine controls between Nav / Memory  / None.
On my test, when not touched by the mechanic at all, the Engines max speed was 51.
When the control wire was disconnected and the lvl100 mechanic used it, max speed was 56.
When you switched to the Memory with value 100 the max speed dropped down to 40.
And now it gets Tricky: **When you switched off all signals the engine kept the 100% setting it got from the memory, but when the Mechanic now reduces the slider from 100% to 90% the engine suddenly ACCELERATES.**

**Comment by mygamingaccount** [comment]
I think I found the cultprit. It is this rather unintuitive bit:

https://github.com/Regalis11/Barotrauma/blob/c81410b83eabdb455e7bef08e9b87feac16ee390/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Engine.cs#L127-L132

In Barotrauma, when the gas pedal of your Prius is pushed by Verstappen, it goes faster.

**Comment by Regalis11** [comment]
> In Barotrauma, when the gas pedal of your Prius is pushed by Verstappen, it goes faster.

Yep, this is intentional
