### ISSUE TITLE
Saving with required content package doesn't save the file in the content package folder

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9188]
**Description**
Saving with required content package doesn't save the file in the content package folder
Instead it creates its own independent mod folder and doesn't upate filelist

**Steps To Reproduce**
Open sub editor
Save a sub as a wreck, "testwreck"
Make a second sub
Save it as a wreck with "testwreck" content package required
It saves in another folder

**Comment by Regalis11** [comment]
This is intentional. The "required content packages" only mean that your mod requires some other mods to work as intended, not that your mod is _a part of_ the other mods.

**Comment by MaaiG** [comment]
Technically, yes! Apparently it’s intentionally! This is not a bug but I can’t keep my job! I guess it’s a mistake!
I can’t finish the submarine in one session! I want to leave many solutions to the next time!

And furthermore, there were no such restrictions in previous versions!
1. I open my old submarine (Shadow light >60)
2. Change it
3. I try to save and exit
4. Get such a surprise! :)
The first time I didn’t pay attention to this window and went out. My work did not survive! :(

For example:
Currently, there are no directional light sources without a shadow in the game. All lamps emit light in all directions. It takes a lot of effort to make a minimum number of shadow lamps and provide reasonable lighting design.
It would be easier if lamps without shadows could emit adjustable directional light:
![Light](https://user-images.githubusercontent.com/93348499/173058525-174d9ef1-183a-4b96-8baa-8a59965c5aab.gif)
This could simplify and speed up the process of placing light sources without shadows...
But now I can’t quickly adjust all the light sources I want to leave it for the future. I need to Save and Get out! Now I can’t do it! I’ll lose all my work!
