### ISSUE TITLE
EventManager spawning monsters causing a lag spike (and is very obvious)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9193]
**Description**
Monsters spawning, whether it's a pack of Crawlers or Thalamus cells, create a noticeable lag spike / performance drop.

Molochs are less impactful (even a pack of baby molochs), but packs of crawlers/threshers/mudraptors consistently generate a drop in FPS. It's somewhat known that lag spike = something spawning, so you can tell every time the event manager triggers

**Steps to reproduce**
Host any mission at 100% difficulty
Set sub to autopilot
Go in freecam
Enable showperf
Monsters spawning = FPS drop

https://user-images.githubusercontent.com/73229309/169691921-356d0773-cf71-4f73-93df-a4ddf4b38e78.mp4

**Comment by Regalis11** [comment]
Closing because we have an existing ticket about this in our private repo https://github.com/Regalis11/Barotrauma-development/issues/3252
