### ISSUE TITLE
Relay Component Transfers Power Between Power-In Inputs?

### ISSUE THREAD

**Issue by Nerdycus** [Regalis11/Barotrauma#9194]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Was editing a sub, and power crossed between wires on the Relay's Power In connection.

Having a power source connect through a relay, and connecting other relays (and probably objects) to the same IN connection will allow power to go through.

![beans](https://user-images.githubusercontent.com/39609028/169695894-7247a1e4-2cb8-4aba-9358-6c9ea578505f.PNG)

This connection works to provide power to said lamp, when connected to the offending IN connection.

### Reproduction steps

Open Dugong in editor.
Place 2 Relay Components, 1 Lamp.
Connect one component to the junction box by the reactor, POWER to POWER IN.
Connect the other Relay's POWER OUT to the powered Relay's POWER IN.
Connect the 'unpowered' Relay to the Lamp.
Viola.

### Bug prevalence

Just once (It took me a while to encounter it, but it's consistent on my version.)

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Nerdycus** [comment]
Unless this was intentional. In which case- trying to give something two possible power inputs can feed back up the line a ways, which still doesn't help the case in which I actually found it out.

**Comment by mygamingaccount** [comment]
This is similar to #9195
Same effect occurs with supercapacitor outputs.

**Comment by Regalis11** [comment]
This is actually intentional, see https://github.com/Regalis11/Barotrauma/pull/8184
