### ISSUE TITLE
barsuk nose shelling

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9198]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

barsuk's nose inside wall is overlaps with other shell pieces a lot and it doesn't match with the ending "inside wall caps"

pictured is actual:

![image](https://user-images.githubusercontent.com/5103517/169737131-e2055b16-2e8b-443f-b084-7442db97d439.png)

think it's supposed to be like this 
![image](https://user-images.githubusercontent.com/5103517/169737218-27b1bedd-f7ef-4317-a032-0d78e6044b38.png)

(needed to use shift+drag on the bottom part to match w/ the inside cap's position- it's not snapped to grid)

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Why is this a problem?

**Comment by Tsunder** [comment]
top side: it collides into the other shells (and would maybe stick out when the shell is damaged?)

bottom side: it collides into the other shells, and also it visibly sticks out

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
