### ISSUE TITLE
Store interface aligns pending purchases incorrectly

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9203]
**Description**
If you add enough items to the pending list until scrollbar shows up, anything added to the pending list once the scrollbar is visible gets misaligned, or rather the existing items on the list doesn't adjust to the scrollbar becoming visible as you can see that the pending list buttons are partially rendered below the scrollbar

Could be a resolution issue as I play in 1440p

Before:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/58b9acc0-a818-44e3-924c-4299cb83e872)

After: 
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a70d00e0-86d5-4106-a325-3cbfb5788246)

**Steps To Reproduce**
1. Add items to the list until the scrollbar shows up
2. Notice that the list isn't aligned correctly when you add new items

**Version**
0.18.3.0

**Comment by ekqvist** [comment]
Doesn't seem to be a resolution issue, but an issue with the existing item elements not being scaled correctly after the scroll bar is enabled. Notice that when you add new items after the scroll bar has been enabled, they will be displayed correctly, but the ones added before will overlap with the bar.

**Comment by ekqvist** [comment]
Should be fixed in [3865a00](https://github.com/Regalis11/Barotrauma-development/commit/3865a00983bdc0b834657377a82e4460616c37a1) by making the list boxes keep space for the scroll bars
