### ISSUE TITLE
Character portrait and health bar buttons aren't disabled when health interface is open

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#9204]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Character portrait and health bar buttons aren't disabled when the health interface is open. Player can click on the hidden "buttons" to cause funky interface behavior.

### Reproduction steps

1. Start a game
2. Click on the character portrait or the health bar to open the health interface
3. See the health interface open
4. Click on the same area where the those "buttons" were before they were hidden
5. See the health interface close and open again

### Bug prevalence

Happens every time I play

### Version

0.18.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Addressed in Regalis11/Barotrauma-development@febf595

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
