### ISSUE TITLE
Outpost generator sometimes places abandoned modules in normal outposts

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9206]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The outpost generator sometimes uses abandoned outpost modules in normal ones

### Reproduction steps

Generate an outpost level in the level editor with the seed 3 (tested in current stable), note that it generates an abandoned version of the admin module
![image](https://user-images.githubusercontent.com/14351070/170278069-d532f5ad-0b79-405c-8d42-6642daacc100.png)

### Bug prevalence

Happens every now and then

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
