### ISSUE TITLE
Graphics Not Rendering Properly Despite Having Adequate Graphics Card

### ISSUE THREAD

**Issue by aricsanders1** [Regalis11/Barotrauma#9213]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have a Nvidia GTX 1650 and whenever I load up the game, I am greeted with the attached image. My drivers are up to date and I assume that this card is enough to run this game, however it clearly does not want to work.

![20220517231222_1](https://user-images.githubusercontent.com/100909112/170529543-e826b972-ffad-4de9-89e1-7ea982e2e6c0.jpg)

I can interact with the menus and stuff, but the graphics remain broken.

### Reproduction steps

1. Open the Game.
2. Loading displays properly.
3. After "Press Any Button", Greeted with screen.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Hash calculation for content package "EK | Dockyard" didn't match expected hash (73A57A4912E20509876C9521C0FED49A != E80088776B33A63C6A98ADF0C99434C4)
```

**Comment by Regalis11** [comment]
Hello and thank you for the report!

We got [a similar report](https://github.com/Regalis11/Barotrauma/issues/8755) some time ago but unfortunately couldn't find a way to reproduce (nor diagnose) the issue with the information with got from that ticket. This is just a wild guess, but do you have some kind 3rd party "game optimization" software or anything similar installed, like GeForce Experience or GameBooster...?

**Comment by aricsanders1** [comment]
I do have the Razer Cortex App. I will try running without any optimization
apps and I'll let you know if the issue persists.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/654f298681929a9e83dff0e2269539a64b63c296

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
