### ISSUE TITLE
periscope's connection panel's "trigger_out" not working properly

### ISSUE THREAD

**Issue by BillBiniou** [Regalis11/Barotrauma#9217]
**Description**
The "trigger_out" wiring pin seem to give out the wrong output ; when the periscope is used and triggered for the first time the "trigger_out" output takes the value 1 and stays that way no matter what and yet controls the canon it is wired to properly. This doesn't happen when the option "is toggle" and "state" are ticked on in the options UI in the submarine editor.

**Steps To Reproduce**
In the submarine editor, place a periscope and wire its "trigger_out" pin to the "set_state" pin of a lamp for instance for debuging purposes. Once this is done, test the submarine and try interacting with the periscope, left clicking once makes you use the periscope and left clicking again will press the trigger which will turn on the lamp. The lamp will never turn off ; left clicking again doesn't do anything, letting go of the periscope doesnt work either.

**Version**
barotrauma v0.17.15.0 (ReleaseWindows, branch release, revision 62bb4ecab3)

**Additional information**
This seems to be a general problem which should be reproduceable in the submarine editor. Voila

**Comment by Regalis11** [comment]
This isn't actually a bug. By default, the periscope sends out a signal of "1" when you left click, otherwise it sends nothing, so there's nothing that'd turn off the light. If you enable the "is toggle" setting, it'll make the periscope send out "1" or "0" depending on whether you've toggled it to fire.
