### ISSUE TITLE
"The bigger they are" achievement not triggering

### ISSUE THREAD

**Issue by toalhikan** [Regalis11/Barotrauma#9218]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Playing single player on v0.17.15.0
I just killed an endworm and only got the survive crush depth achievement, but not the kill an endworm achievement. Not game breaking or anything, just thought you should know. I did see an old report (v0.15.19.0) that it might happen when the worm dies from bleeding but supposedly that one was fixed?

### Reproduction steps

Haven't tried a second endworm mission yet, will do later.

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report, and sorry for the late reply!

I unfortunately couldn't find a way to reproduce this. Do you recall how exactly you killed the endworm? It could be that in some specific situation the game fails to correctly determine which character the affliction(s) that killed the endworm originated from.

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by toalhikan** [comment]
So far I've beaten several endworms in single player campaign without
triggering the achievement. It's supposed to be the character that's
currently selected by the player that deals the finishing damage, right? If
one of the npcs deals bleeding damage to it and that's technically the
final damage that wouldn't trigger the achievement?

Benjamin Chaim
(IPA: /ˈχa.jim/)
Pronouns: he/him or they/them
