### ISSUE TITLE
Razer Cortex overlay breaks the game's rendering

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/Barotrauma#9219]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This comes from a report on Discord, after inquiring about the overlay I downloaded Razer Cortex 10 Beta and managed to replicate the issue.

![image](https://user-images.githubusercontent.com/8607119/170852786-bd8ca398-6f80-45a2-96a0-9a553a07e632.png)

### Reproduction steps

1. If necessary, install Razer Cortex 10 Beta
2. Enable the custom overlay
3. Launch Barotrauma and get past the initial loading screen

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/654f298681929a9e83dff0e2269539a64b63c296

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/9213?

**Comment by juanjp600** [comment]
Yep, this looks like the exact same thing. Closing.
