### ISSUE TITLE
Kind of noclip?

### ISSUE THREAD

**Issue by MysteryPolarBear** [Regalis11/Barotrauma#922]
I have a glitch where when I make a save it just has no walls the only things that are visible is the entities and npcs if I get near the npcs like 173 or the random mtf just standing in the void they just fall and dissapear without a trace.

**Comment by BillCombs** [comment]
> 173

> mtf

I think you are in the wrong repository. This one is for Barotrauma.
SCP - Containment breach is here: https://github.com/Regalis11/scpcb

(Unless you are talking about some scp mod for barotrauma, though i am not sure if those have mtf npcs)
