### ISSUE TITLE
Cannot connect to IPv4 servers when IPv6 is disabled.

### ISSUE THREAD

**Issue by Orum** [Regalis11/Barotrauma#9221]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When trying to connect to a IPv4 server (by entering its address directly into the direct join prompt), the connection will fail with `Couldn't connect to [IP address] Error message: Address family not supported by protocol` if the IPv6 stack is disabled on the client.

### Reproduction steps

1. Set up a dedicated server with an IPv4 stack & IP address.
2. Set up a client with the same, and ensure that IPv6 **not** enabled on the client.  (e.g. in Linux `ipv6.disable=1` in `grub.conf`)
3. Attempt to connect to the server's IPv4 address.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a09a97ed82ab3b01de06b88d8dd4af24ae538a3

**Comment by Regalis11** [comment]
Tested, no issues found. Closing.
