### ISSUE TITLE
Cabinet inconsistencies in vanilla submarines - Weapon access

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9223]
**Barsuk**
- Weapons stored in large cabinet, accessible by everyone

**Azimuth**
- Weapons stored in large cabinet, accessible by everyone

**Orca 2**
- Weapons stored in large cabinet, accessible by everyone

**Berilia**
- Weapons stored in large cabinet, accessible by everyone
- Medical crafting cabinet is used to storing weapons

**Herja**
- Weapons stored in large cabinet, accessible by everyone

**R-29** 
- Harpoon gun is stored in the weapon holder located on the medbay, previously the weapon holder was holding a Ethanol, maybe remove the weapon holder and move the toxin cabinet to that space? As the toxin cabinet is located in armory.
- Weapons are stored in the command room where security officer doesn't have access to them as that Secure Steel Cabinet is only meant for the captain to use, maybe there needs to be a check when deciding which secure cabinet the weapons are stored based on if a security officer has access to them?

**Winterhalter**
- Same as R-29 security officer can't access weaponry as the weapons are stored in the command room

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@d7c8489 and Regalis11/Barotrauma-development@4361aa1.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
