### ISSUE TITLE
sprite depth error on weapon holder

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9228]
Please use the other report form to report issues. This old template is only here until we've replaced the bug report links in the game.

**Description**
te weapon holder's sprite depth is rather too high for its decorative sprite (the little strap thing)

    <DecorativeSprite texture="containers.png" depth="0.5" sourcerect="188,682,124,33" origin="0.5,0.5" />

it's set at 0.5 which is in front of all objects except for player layer

notably this is in front of a bunch of things that wouldn't normally be put inside the holder, like diving suits, or players on ladders.

![image](https://user-images.githubusercontent.com/5103517/171057099-9d3beec7-06a3-418b-8077-f6cda2964271.png)

**Steps To Reproduce**
1. place weapon holder near the ground
2. place some offending item in front of the holder - diving suits, weapons that aren't placed in the holder

1. place holder near a ladder
2. climb onto ladder

**Version**
0.17 stable

**Additional information**
watcher responds with old bug report link

**Comment by Regalis11** [comment]
Please use the other report form to report issues. This old template is only here until we've replaced the bug report links in the game..

Fixed in https://github.com/Regalis11/Barotrauma/issues/9228

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
