### ISSUE TITLE
Changing the resolution doesn't update the fixed-size UI elements

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9230]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Certain UI styles define a fixed size for the element (tickboxes, buttons, textboxes). The size is defined separately for different resolutions, but changing the resolution doesn't change the sizes on the fly, causing them to be too small/large after the resolution change.

### Reproduction steps

1. Start the game with e.g. 1024x768 resolution
2. Switch to 1920x1080
3. Notice that some UI elements are very small

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d1ee225bf73c0e5b8daa1050a29670fcac1e7f99

**Comment by Rokvach** [comment]
Switching from 1440p to the lowest resolution results in some UI parts being too large

I'm noticing that the size of almost everything does get corrected on the settings when you re-open it after the resolution change but this doesn't happen outside settings

Settings slider handles
![image](https://user-images.githubusercontent.com/7299826/171582936-f1aba94d-8354-4190-81e2-5014f8fbcb32.png)

On new game the text fields and buttons are large
![image](https://user-images.githubusercontent.com/7299826/171583121-d24063a6-35ac-407e-934c-16d6eea4324e.png)

Host server
![image](https://user-images.githubusercontent.com/7299826/171583214-4deef4dd-0580-4da7-b80c-9feb386196db.png)

Server browser
![image](https://user-images.githubusercontent.com/7299826/171583366-ff8da478-d282-4044-a15b-7f3bf46f81b3.png)

**Comment by Regalis11** [comment]
Fixed the 1st one in https://github.com/Regalis11/Barotrauma-development/commit/4eec07648381a539152d86f9640d225a615025ba

The rest aren't actually new bugs: those menus don't seem to be recreated when changing the resolution.

**Comment by Regalis11** [comment]
Actually no, I was wrong: the menus do get recreated, but the problem was they were recreated before updating the size restrictions of the elements. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/628b3c73fe184adc5eb61504bea3ea76c26b1fd8

Also fixed settings menu not getting recreated https://github.com/Regalis11/Barotrauma-development/commit/6398acd6bbb04291f3c4f18c2c06145918637095

**Comment by Rokvach** [comment]
Only thing I noticed was that it takes a bit longer to switch resolutions now

**Comment by Daniel-Chin** [comment]
There are other game elements that don't scale with resolution. Related: #12180 #10679 #11662 #12221 #12538 

Here's the problem that bothers me the most. The yellow dots shown by the mineral scanner are drawn at a fixed pixel radius. At high resolutions, it is quite impossible to hover your cursor over them and see their mineral type. That's quite a bummer. 

I understand adaptive resolution issues are usually tedious to fix. But let's keep track of them ;-)

Another solution to the adaptive resolution problem is to use rendering scaling (#12549). Players can play in a "recommended resolution" while using scaling to fit text elements to their monitors.
