### ISSUE TITLE
Campaign settings menu doesn't have a min/max value for Max missions per round

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9233]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Campaign settings menu doesn't have a min/max for Max missions per round.
![Barotrauma_XMEH7RUV9U](https://user-images.githubusercontent.com/36804725/171227035-9019fc5e-e38b-4258-92d9-1e1490c1323e.png)

Also for some reason, if you input -99999999 into the max missions input, the ok button will stop working.
https://cdn.discordapp.com/attachments/668819422919524352/981231326017486878/2022-05-31_13-22-37.mp4

### Reproduction steps

1. Go to mainmenu -> new game -> Settings
2. Notice you can input any value into the max missions per round

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.4.0 Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dc0b421b62182a951d2c7759266146e37d65c304

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
