### ISSUE TITLE
mudraptor veterans and hatchling cause console errors

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#9235]
**Description**
![image](https://user-images.githubusercontent.com/55637865/171271335-abfd9bdd-77a5-4be4-842c-7746d86bd5ef.png)
![image](https://user-images.githubusercontent.com/55637865/171271267-40f982bc-a18a-40b0-bd20-b6261f3214ed.png)

**Version**
v0.18.4

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@5ca17d3 (Related to #9089).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
