### ISSUE TITLE
[Bug] Wreck reactor toggle for "non-interactable" resets to default value, every time it is instantiated.

### ISSUE THREAD

**Issue by DanJF** [Regalis11/Barotrauma#9236]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The wreck reactor component does not maintain the toggle for "Non-interactable" as soon as it is instantiated, whether by entering testing mode in the editor, or simply loading the sub containing it: e.g. you can set the wreck reactor to non-interactable, save the sub, then immediately load that save, and the "non-interactable" toggle will be in its default state again (0/false). 

Would like to use the wreck reactor as a prop piece, with a functional reactor in front of it with sprite color A=0, however the wreck reactor always returns to its default state.

### Reproduction steps

1. Place wreck reactor component
2. Set non-interactable toggle to "True"
3a. Enter testing mode, or
3b. Save the submarine to a file
4a. Approach wreck reactor, and see it is still interactable. Upon exiting test mode and returning to the editor, you will find the wreck reactor "non-interactable" toggle has returned to its default state
4b. Load the submarine save file, and see it is still interactable, toggle box is returned to its default state

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/A
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/df9ec3dd61e29509f4b289433e200d6acad6c2f0

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
