### ISSUE TITLE
default Chaingun on Orca 2 has outdated property value

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#9239]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Its "maxchargetime" is 1.7 seconds which should have been changed to 1 in a previous update.

### Reproduction steps

1.open the Sub Editor.
2.choose Orca 2.
3.select the top Chaingun.
4.enable cheats with console.
5.input "setentityproperties MaxChargeTime 1" in console.
6.you will see the property is changed from 1.7 to 1.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/836a2e22c6adc074b43b920d0c1b9173ca3e9266

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
