### ISSUE TITLE
Support IPv6 addresses

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#924]
It seems that clients are unable to join servers that have an IPv6 address.

**Comment by SandPoot** [comment]
My game suddenly started using ipv6 when players connect to it when i updated, what happened?

**Comment by Regalis11** [comment]
The master server uses whatever IP your messages are coming from as the IP to add to the server list, so my guess would be that something in your network has changed and caused you to switch to IPv6. Unfortunately the game doesn't support IPv6 addresses yet, but we're working on it (see https://github.com/Regalis11/Barotrauma/tree/IPv6-support). 

You _might_ be able to fix it by temporarily switching back to IPv4 by changing your network adapter settings.

**Comment by SandPoot** [comment]
Any idea on how to undo this, since I didn’t even want to use ipv6 at all?

**Comment by Regalis11** [comment]
Added in 38ef4db
