### ISSUE TITLE
Wrong name in player name change message

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#9242]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a player changes their name in a multiplayer game, the server message about the name change has the new name where the old name should be.

### Reproduction steps

1. Join a multiplayer lobby
2. Change your name
3. Read the server message about the name change

### Bug prevalence

Happens every time I play

### Version

0.18.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@3123764

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
