### ISSUE TITLE
Moving doors/ducts/hatches in the Editor using "SNAP TO GRID" does not move the corresponding gap

### ISSUE THREAD

**Issue by T1MM5H** [Regalis11/Barotrauma#9244]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When placing down an item with automatic gap placement, such as a door or duct block in the editor, then using the SNAP TO GRID button on said object, only the object gets snapped to the grid, not the corresponding gap. 

Additionally, thanks to the unbreakable link between the two, deleting and manually creating a correct gap is not possible.

### Reproduction steps

1. Open Editor
2. Place walls for reference
3. Place hatch/door/duct between them.
4. Align said object off-grid
5. Click "SNAP TO GRID" with object selected
6. Observe the object return to its grid position without the gap moving from it's old position

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.17.16.0 rev. 05309f303f

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5d9a01ea7d220d2ff5e9270d9b631bd62a0bcb17

**Comment by T1MM5H** [comment]
Thanks for the comment! Couldn't find a previous report, so i assumed it was new. Glad to hear it'll be fixed soon-ish.
