### ISSUE TITLE
Core content packages can't be updated

### ISSUE THREAD

**Issue by mrmanlikesbt** [Regalis11/Barotrauma#9245]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

Core content packages can't be updated which often causes errors when the game gets updated. 
The only way to update the mod is it delete it in the workshop mods folder.

### Reproduction steps

1. Make a core content package mod on the steam workshop
2. Get somebody to install it
3. Add a new file to the mod and update it
4. The player who installed the mod can't update it

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Are you aware of a specific core content package in the Workshop that we could use to test this? Now that LuaForBarotrauma is no longer a core package, I'm not aware of any.

**Comment by mrmanlikesbt** [comment]
My mod actually, for a while I've been working on a mod that reverts the game to legacy but until I feel it's ready to present I'm keeping it unlisted on the steam workshop. 

[](https://steamcommunity.com/sharedfiles/filedetails/?id=2742945438)

**Comment by HomelessMage** [comment]
This is quite an issue for a dedicated server, currently it basically disables the ability to join the server for 80% of people, due to `corepackage` desync, after the mod gets updated.
Our [corepackage](https://steamcommunity.com/sharedfiles/filedetails/?id=2826890267).

**Comment by ArtiomLiakh** [comment]
Same woes

**Comment by PuchaBro** [comment]
fix the same

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/3797/commits/f261fdf3aa85f467ad3fc3cac5177235eb599bc4 (commit in our private repo, not out in unstable yet)
