### ISSUE TITLE
Items vanish when transferring items between subs

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9246]
**Description**
Some items seems to vanish now when you transfer your items to a new submarine

**Steps To Reproduce**
Issue 1
1. Load up Typhon 2 in singleplayer
2. Buy Dugong and switch + transfer items to it
3. Leave outpost and notice that there is no extra diving suits on the floor and only enough diving suits to fill the lockers

Issue 2 (continuation)
4. Take notice that there is a crate on the floor with clown etc items in it
5. Dock back to outpost
6. In outpost switch back to Typhon 2
7. Leave outpost
8. Notice that there is no crate anywhere to be seen, nor can you find any clown masks when you use the item finder on the nav terminal

**Version**
0.18.4.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/c07b50bc77f8b1f0347b05c3d669e549e379e9b6

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb0cc4a10ffd2d59f08d054f026b2a216ff168a1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
