### ISSUE TITLE
You can soft-lock campaign if you switch to an empty submarine

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9247]
**Description**
I noticed that you can lose the fuel rod from your reactor if you transfer items in a specific way

**Steps To Reproduce**
1. Start singleplayer (Dugong)
2. Buy a new sub (Azimuth) and transfer items to the new sub
3. Leave outpost
4. Dock back to outpost
5. Now switch to your old sub and choose not to transfer items
6. Notice that there is no fuel rod in the reactor

**Version**
0.18.4.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/c07b50bc77f8b1f0347b05c3d669e549e379e9b6

**Comment by itchyOwl** [comment]
Addressed this in Regalis11/Barotrauma-development@25c15de.

Added an option to define that the sub is manually outfitted and can be switched to without transferring the items. Forced item transfers for all subs that have this setting disabled (default) or when the items of the sub have been previously transferred on some other sub. Being allowed to switch to an empty sub (and therefore potentially softlocking the campaign) should now be impossible without purposely creating such a sub in the editor and manually disabling the item transfer option when switching the sub. 

Admittedly, this change adds a limitation for not being able to manually move items between the subs, unless the subs have been pre-configured to allow this. But I think a mere warning is not enough to address this.

**Comment by Rokvach** [comment]
I'm getting build errors, tested both Release and Debug

> Error	CS0029	Cannot implicitly convert type 'void' to 'bool'	WindowsClient	C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs	339	Active


> Error	CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type	WindowsClient	C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs	339	Active

**Comment by ekqvist** [comment]
You seem to have noticed it already but just noting here that the errors were fixed in 877a806

**Comment by Rokvach** [comment]
Tested, didn't spot any issues with this. Can be merged and closed
