### ISSUE TITLE
Switch - wrong lighting position

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9248]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Switch - incorrect lighting position when switch turning in the sub editor.

### Reproduction steps

1. Start editor and add `switch`
2. Showlighting
3. Turn the switch

Video:
https://user-images.githubusercontent.com/93348499/171834072-7ec74bf7-a770-46ea-bca2-2b3e1e96fe09.mp4

### Bug prevalence

Happens every time I play

### Version

0.17.15.0
0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Seems to have been fixed in https://github.com/Regalis11/Barotrauma-development/commit/bece38dda5b512ebfe2f13c5db1de6e287660265

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
