### ISSUE TITLE
Changing HUD scale doesn't do anything unless you're controlling a character

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9249]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Changing HUD scale doesn't do anything unless you're controlling a character, seems to have been left unimplemented during modding refactor
![image](https://user-images.githubusercontent.com/14351070/171867277-05cf6d7c-8fe1-44ee-a2ec-37bc93ad534b.png)

### Reproduction steps

1. Start a round
2. Die or freecam
3. Change the HUD scale in the settings
4. Nothing happens

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/242623a4c7bb9462e80a90145cd4fc0d9b8937a0

**Comment by Rokvach** [comment]
Tested I did notice this when testing this issue https://github.com/Regalis11/Barotrauma/issues/9303 but as I wrote a separate ticket for it, I didn't notice any issues relating to this ticket. Closing.
