### ISSUE TITLE
Ballast Flora is Suicidal

### ISSUE THREAD

**Issue by SirNightKnight** [Regalis11/Barotrauma#9250]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I tried testing the bug of indestructible ballast flora and found that ballast flora is now self-destructing. I am pretty sure it's not intended for ballast flora to rid itself spontaneously without any player input whatsoever so I think it's a bug. The bug was found on the Barsuk and Humpback in a solo campaign while in the starting biome. 

Only mods installed were added submarine and assembly files

### Reproduction steps

1. Create a new solo campaign
2. Enable cheats
4. Make sure the submarine's ballasts have a powered pump and there is water covering the pump
5. Use the _ballastflora infect_ command while docked at a station or undocked
6. Watch the ballast flora grow for 5-15 seconds and then kill itself

 

### Bug prevalence

Happens every time I play

### Version

Other

### -

V0.18.6.0

### Which operating system did you encounter this bug on?

MacOS

**Comment by Rokvach** [comment]
Seems like its only visually shown dead as it still can kill you with gas

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/895495f95da6cb748930c806f67b1d4ff51299e4

**Comment by Rokvach** [comment]
There is still something strange as to where the Ballast Flora starts to die, in this test I cut the branch from the marked area and undocked from the outpost as soon as the branch was separated and then on the next round the flora started to die near the seed

![image](https://user-images.githubusercontent.com/7299826/172134247-bbe925a7-5066-43bc-a75a-53b06a2f0e09.png)
![image](https://user-images.githubusercontent.com/7299826/172134562-f9fb3bed-d27d-43fa-91f7-88f605b834c2.png)

**Comment by Rokvach** [comment]
Moving this back to review as the above issue hasn't been looked into yet

**Comment by Regalis11** [comment]
Hopefully fixed now https://github.com/Regalis11/Barotrauma-development/commit/1864733bd993d06b274b4068786f3dce2812ae7b

**Comment by Rokvach** [comment]
Tested, I wasnt able to get the issue to happen anymore, dor did I notice anything else relating to the original issue so this is working correctly and can be closed if nothing new comes up from the review
