### ISSUE TITLE
[Unstable] Radio button in bottom left of chat box closes chat box

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#9251]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**See reproduction steps for detail.** 
Unfortunately there's no scientific experiment for this one, it's quite a simple bug to reproduce and experiment with. If you click the chat box button, the radio button works as intended. It's purely when it opens when a player presses "T".

Image below for reference.
![image](https://user-images.githubusercontent.com/105495756/171899120-df063aa8-1021-4a0b-9a96-5128eb9a01a3.png)

### Reproduction steps

1. Press T to open the chat
2. Click the "radio" button in the bottom left
3. Observe how the chat box disappears
4. Repeat

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@7a58a24

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be closed if nothing is found in review relating to this
