### ISSUE TITLE
[Unstable] Headset bot commands don't work in multiplayer (P2P)

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#9252]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**The Issue At a Glance**

I tried to give commands to the AI via the headset and nothing happened. 

**What I Tested**

Give commands to the AI via the headset. Do three (3) of each command of each category (for example "follow me", "man the guns", or "clean items"). Do this across all modes available, across each class. 

**Results**

Giving commands to the AI will not work in multiplayer (P2P) under any condition. There is no chat response, nor any feedback from the AI whatsoever. Class, mode, or submarine condition (docked or undocked) does not influence this. 
Interestingly, if you click one of the speed-commands (the icons in the bottom left corner) the hull you are in will have the icon appear as if the command was executed successfully. However, nothing will happen.

Image for reference.
![image](https://user-images.githubusercontent.com/105495756/171911039-4508ca0a-f6c3-4538-a8e0-25944301954b.png)

**ADDITIONAL NOTES**
*Headset commands work as intended in Singleplayer Campaign.

### Reproduction steps

1. Start a game by clicking "host a server". Choose any mode.
2. Once you've spawned in, press the middle mouse button.
3. Choose any command. Both random selection (left click) and specific selection (right click) work.
4. Observe how there is no response from the AI, nor text in the chat to signify a response.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Also noticed this in dedicated server when trying to give orders
![image](https://user-images.githubusercontent.com/7299826/172041943-b1eca2f4-0400-43e7-b539-921c16aeb9df.png)

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@0e8f33b

**Comment by Rokvach** [comment]
Closing.
