### ISSUE TITLE
Visual Bug on cutting doors in unstable

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#9256]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems plasmacutting any door in the baro unstable build 18.6.0 has the "broken door" sprite stretch on a y-axis, instead of the normal x-axis to make it look like its breaking. This leads to it kind of comically stretching downward (Image) 
![image](https://user-images.githubusercontent.com/104232152/172020717-b56dde06-8dcb-48aa-92be-d7580ba01887.png)

### Reproduction steps

1.Go to sub editor
2.Use a plasmacutter on any door
3.Notice that the sprite for the broken door is moving in a wrong way

### Bug prevalence

Happens every time I play

### Version

Other

### -

V0.18.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e68a71a580f169f5584c0b7ce7ea94a57c03cf3

**Comment by Rokvach** [comment]
Tested already and didn't spot any issues, this ticket can be closed if there is no further adjustments after review
