### ISSUE TITLE
[Unstable] Sub editor save can't handle (nested) mod folders?

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9259]
**Description**
If you save a .sub in save editor and select a local package, it will always save that sub in the root of the Localmod folder, regardless of where the sub is located and has been loaded from

**Where the sub is saved**
![image](https://user-images.githubusercontent.com/73229309/172047495-da0dcf10-657a-4728-a1eb-f75232c603ea.png)

**What happens when you try saving the sub (no "update")**
![image](https://user-images.githubusercontent.com/73229309/172047509-8e22d552-3d95-40c8-aa28-70afedb7d72e.png)

**What it should look like:**
![image](https://user-images.githubusercontent.com/73229309/172047481-bf018132-a2c5-41a8-bf3c-84d73e56176c.png)

**What it does (saves in the root folder):**
![image](https://user-images.githubusercontent.com/73229309/172047512-dab6354a-2774-4ac6-9f3d-ee5126131cef.png)

**Version**
v0.18.0.6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
