### ISSUE TITLE
[Minor] Mission UI overlap

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9260]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![Barotrauma_2uHsq5mb5c](https://user-images.githubusercontent.com/10529134/172060947-06147cdf-e796-45b8-981d-c27701389759.png)

### Reproduction steps

Unknown

### Bug prevalence

Happens every now and then

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/afabe9e004560e0c526f1de4415ce0825699cd81

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be closed if nothing is found in review relating to this
