### ISSUE TITLE
Engineering and Security Modules not generating in colonies/cities

### ISSUE THREAD

**Issue by Rimrue** [Regalis11/Barotrauma#9263]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While playing a multiplayer campaign and visiting a colony in the Cold Caverns, the colony did not generate an Engineering Module.

### Reproduction steps

I have not reproduced the error in a campaign, but generating a city outpost level in leveleditor produces the same error every time I generate a city outpost level. I suspect that the problem has to do with the tags in the "Allow Attaching To" box in the save menu. Currently the EngineeringModule has "Airlock, SecurityModule" selected and the Security Module has "EngineeringModule, ArmoryModule" selected), however I have been able to correctly generate city outposts in the leveleditor using custom modules with only the tag "Airlock" for the Engineering Module and the tag "EngineeringModule" for the Security Module, Hope this helps!

### Bug prevalence

Happens every time I play

### Version

Other

### -

18.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Screenshots of the errors produced in the Command Console:

```
![Error1](https://user-images.githubusercontent.com/27902974/172073437-52d521b7-f6ad-46cc-afd6-f2d9e4489cc9.png)
![Error2](https://user-images.githubusercontent.com/27902974/172073443-77b04f0c-af5d-4a90-8948-9309e26dd708.png)

**Comment by Regalis11** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/c9043f4559e44f600c7768048a2e2169c2285948

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
