### ISSUE TITLE
Maintain 3 shell rack as a legacy option 

### ISSUE THREAD

**Issue by Yowbaby** [Regalis11/Barotrauma#9264]
Please have an option to keep the 3 shells on the railgun rack as a legacy item for balancing and editorial flexibility.

**Comment by itchyOwl** [comment]
Implemented in Regalis11/Barotrauma-development@4c3b1a2.

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

Notes: The 3 shelf rack can be found under the "Legacy" tab.
