### ISSUE TITLE
[Tutorial] Character has starting items

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9266]
**Description**
Characters in tutorials shouldn't have any starting items as they are given the items they need on the tutorial

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c26380156078a8a04718d1026685d80d5f2d6506

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Regalis11** [comment]
The characters now spawn without a headset, reopened

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/898a3d3c04600b6d03d63828c493388333807008

**Comment by Rokvach** [comment]
Tested, no issues. closing.
