### ISSUE TITLE
Changing difficulty settings in New Game causes the selected submarine to change

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9267]
**Steps To Reproduce**
1. Select New Game from main menu
3. Select Dugong
4. Press "Settings" and hit "Ok"
5. Notice that the selected submarine changes, if the sub doesn't change then open settings again

**Version**
Unstabe 0.18.6.0

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8dcfc96bb0a7f12ba2e22e3978b12e5b89cc7255

**Comment by Rokvach** [comment]
Tested, I noticed that the submarine list doesn't refresh now when you change the starting balance, so if you go from medium to high you don't see the newly available submarines until you re-open the new game window

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/02e48c13ac459cf24300fb07488536c218d6c8ad

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
