### ISSUE TITLE
Medical fabricator once delinked, can't be linked again.

### ISSUE THREAD

**Issue by alienara** [Regalis11/Barotrauma#9268]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In the sub editor, when I was playing around with it, I unlinked the medical fabricator. I realised the mistake and tried to link it again. I couldn't link from the fabricator to the cabinet but I can link from the cabinet to the fabricator.

When I open the fabricator, I don't see the cabinet even though both have the "display side by side" ticked. When I open the cabinet, I see the fabricator but the fabricator doesn't see the items in the cabinet as part of the recipe. I can move the items from the cabinet into the fabricator and click create, but I can't remove items from the fabricator screen unless I click on the fabricator itself.

I have tried this on other subs and it's the same. Once I unlink, I can't link it again.

### Reproduction steps

1. Open a sub in the sub editor.
2. Unlink the medical fabricator from the cabinet
3. Click on the medical fabricator to attempt to link to cabinet.
4. Click on cabinet to link on medical fabricator
5. Tick "display side by side" on both fabricator and cabinet
6. Test

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against release 0.18.15.0, works correctly, closing.

notes: I can successfully link a medical fabricator to everything except a supplies cabinet and "cabinets" item used by outposts. they link fine regardless of which way around you link them as well. deconstructors, lockers (of all 3 types), medical and toxin cabinets were also fine.

I would like to add the "Medical compartment" is not linkable, despite its name suggests it could be, though they are only 3-slot containers and I don't think one would normally want to link those to a fabricator over larger containers either.
