### ISSUE TITLE
Commands done in submarine test mode carries over to signleplayer without having to enable cheat

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9270]
**Steps To Reproduce**
1. Load up sub editor test mode
2. Use commands that aren't game mode specific like debugdraw and lighting
3. Hit Esc and Main Menu
4. Load up singleplayer
5. Notice that the commands are still in use but you can't even disable them as you don't have cheats enabled

**Version**
0.18.6.0
Branch: bugfixes

**Comment by Regalis11** [comment]
Fixed `debugdraw`, `lighting`, `water `and `fire `in https://github.com/Regalis11/Barotrauma-development/commit/76477355a8979f5d7c3bac347ff4f61612f12959. There might be some more still though.

**Comment by Rokvach** [comment]
I was still able to reproduce this with all the commands above, it does work if I do the commands in sub editor and then jump to singleplayer but not when I'm in the test mode and go to main menu from there

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fa5ed82f757ad1124e01f1e24b2e05be09e33bb

**Comment by Wheatley1001** [comment]
Tested on Version 0.18.8.0 (unstable). Here are the results:

**Commands that do not work:**
LOS
Lighting
Debugdraw
Water
Fire
Freecam
Godmode
showseed
netstats
godmode_mainsub


**Commands that work:** 
interactdebugdraw
disablecrewai
oxygen
disableenemyai

**Comment by Rokvach** [comment]
Moving to review

**Comment by Regalis11** [comment]
Fixed debugdrawinteract, disableenemyai and disablecrewai in https://github.com/Regalis11/Barotrauma-development/commit/6d34a86176a3677e0b33edc4b176d3498f15cbdb. I don't quite understand the issue with oxygen though - I don't see how it can carry over since it's something that just runs once and has no on/off state.

**Comment by Wheatley1001** [comment]
For the oxygen test, I completely unwired the oxygen generator, closed the doors to the command bay (in the Dugong), and observed the oxygen status on the status monitor. After five minutes, the value was still 100%. In a previous test to see if the command actually worked, I repeated this method and had the oxygen level drop to 76% before I called off the experiment

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
