### ISSUE TITLE
[Unstable] Depth charges can't go inside wrecked ammunition shelves

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9271]
**Description**
Depth charges can't go inside wrecked ammunition shelves

Not sure if it's planned for depth charges to spawn inside those containers in wrecks either (most importantly decoys/nuclears)

**Comment by Regalis11** [comment]
This has not been reviewed or tested yet, reopening

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be closed if nothing is found in review relating to this

**Comment by Regalis11** [comment]
I can't see any issues with the changes either
