### ISSUE TITLE
My game won't stop playing disco music after I have entered the server menu.

### ISSUE THREAD

**Issue by bruhmogus** [Regalis11/Barotrauma#9275]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I just got done using the sub editor, and I decided to play online. Now, my game is constantly playing disco music, and it won't stop. I was in fact using mods, but it shouldn't of been any of the ones I had enabled at the time, as the music seems to have multiple instruments. Identifying the music with Shazam failed.

### Reproduction steps

1. Enter Sub Editor for around 10 minutes.
2. Exit Sub Editor
3. Open Server Browser
4. g r o o v e

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
As far as I know there's no disco music in the vanilla game, so I suspect this is caused by one of the mods you have enabled.

**Comment by Krzeszny** [comment]
There are several mods that change the main menu music.
