### ISSUE TITLE
[0.18.6.0] Unable to charge the batteries in this new beacon station

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#9276]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/5086682/172209403-31e6c64f-47c4-47bc-a49a-19b4d43f4fa9.png)

Unable to charge the batteries in this new beacon station to keep it from going out of charge.

### Bug prevalence

Happens every time I play

### Version

0.18.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Fixed in 9b47eb7d777e136e5ef26e0521c2772ee03ea48a on bugfixes branch

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be closed if nothing is found in review relating to this
