### ISSUE TITLE
Vanilla Wrecks, Beacons, Pirates and some outpost rooms have thumbnails (longer load times?)

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9277]
**Description**
Vanilla Wrecks, Beacons, Pirates and some outpost rooms have thumbnails

Thumbnails are only relevant for submarines that can be played, and significanty increase the size of the .sub file, this may lead to longer loading times, although I'm not sure how to measure that. 

If loading times do get faster by removing thumbnails, maybe consider always saving without them by default in sub editor?
Most Wreck/Beacon mods have a policy to not save thumbnails.

_To find these thumbnailed .subs, consider that any file that is about 100KB has a thumbnail._

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/698506c0636833663403adb56beda43de67d4af4

**Comment by ubertpendragon** [comment]
These still have thumbnails:
![image](https://user-images.githubusercontent.com/73229309/172625641-6d98dd05-fb17-42fe-b58b-d3baa39399f0.png)

**Comment by Rokvach** [comment]
Afaik those modules aren't in use anymore and have been removed on the dev branch already

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
