### ISSUE TITLE
Water physic is buggy in small hulls (animation not smooth)

### ISSUE THREAD

**Issue by Yowbaby** [Regalis11/Barotrauma#9279]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Before the update, replicating the effects of water falling (from water particle effect) can be done if the hull (and the distance between the gap) is small enough. After the update, not only the water particles are missing, but these small gaps are forced to have actual water in between them, creating a very ugly water physic that is not desirable whatsoever.  

**A) Here is how the water physic should ideally look like (pre-update):**

https://user-images.githubusercontent.com/93289071/172302167-e8375884-2b6a-489c-a107-947e4ceff4f4.mp4

**B) Here is how the water physic currently looks like (and it's not nice):**

https://user-images.githubusercontent.com/93289071/172302119-13ecb1dd-3251-45a0-be4f-66bd4c844e74.mp4

Q: Why small gaps?
A: Unconventional hulls and curved shells makes it hard to make hulls that allow water to flood nicely, small gaps and hulls solved all that issue. However, with the update, it seems that this has become more of an issue than a solution that it used to be.

Q: Just make bigger hulls? 
A: Yes, but it is still not pretty either, the same water janky physic still applies for decent sized hulls in curved shells rooms. A square room is no big deal, but rooms like these need to look good considering how tricky it is to hull an unconventional room.

Appendix:

![image0](https://user-images.githubusercontent.com/93289071/172302470-4802f5e0-8f18-44fa-84ae-a9e8041eb472.png)

Hulls might look messy but aside from the editor point of view, the most important thing I care about is the water physics right now. 

### Reproduction steps

1) Produce a hull with small gaps segments like those in the Appendix. 
2) Break the walls/ glass/ shells 
3) Let water leak in 

You will see that water physics gets very janky and clunky now, and the lack of water particle is not helping either. 

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by DuckY-Y** [comment]
It's so annoying.

**Comment by DuckY-Y** [comment]
It's not the animation but the physics as well, you constantly get knocked off your feet when attempting to stand in those hulls during flooding. How can this be Low Priority when the flooding feature is one of the biggest if not the biggest selling point of this game.

**Comment by Regalis11** [comment]
Although, I don't think I completely understood the implications of this when I originally labelled the ticket. I thought it was mainly a visual issue, but since it does cause the ragdoll to behave in a very erratic way, it seems this is a bigger issue than I thought.
