### ISSUE TITLE
SecurityModule01 does not generate in Military Outposts

### ISSUE THREAD

**Issue by Rimrue** [Regalis11/Barotrauma#9291]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I noticed that only one of the two security modules generates at military outposts while playing both singleplayer and multiplayer campaigns and then confirmed it by testing in the leveleditor.

### Reproduction steps

1. Open leveleditor
2. Select outpost level and military outpost
3. Observe that only SecurityModule_02 ever generates and SecurityModule_01 does not
4. Rinse and repeat with same results

I think it may have to do with the "Can attach to previous" tags (see attached screenshot) in the save menu as saving it as a new module and selecting "left, top, bottom" will allow the module to generate in the leveleditor.

### Bug prevalence

Happens every time I play

### Version

Other

### -

18.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
https://cdn.discordapp.com/attachments/410238540383911944/984174637481078804/unknown.png
```
![unknown](https://user-images.githubusercontent.com/27902974/172699952-0ae2540b-8045-4d6c-b753-273ebde0110a.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing as this doesn't need a code review.
