### ISSUE TITLE
Secure cabinets in abandoned monster-infested outposts can't be opened

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9292]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

ID cards don't spawn, or we haven't been able to find them

### Reproduction steps

Start an abandoned outpost mission with monsters

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by danielasteljoki** [comment]
Addressed in df052b7.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
