### ISSUE TITLE
Using Freecamera during tutorial softlocks the game

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9297]
**Description**
If you use Freecamera during a tutorial it pauses the game and doesn't even let you press Esc to leave the tutorial, so you are forced to restart the game entirely. 

**Version**
0.18.6.0
Branch: bugfixes

**Comment by Regalis11** [comment]
I couldn't get this to happen and was about to ask for steps to repro, but then I realized it only happens if you enter the command when the tutorial is paused. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/872d3246184b4c07bd8cf8aa7074629cfb2b5e45

**Comment by Rokvach** [comment]
Tested couldn't get this to happen anymore, can be closed after review
