### ISSUE TITLE
Switch, etc - "lightcomponents" editing error when editing multiple switches

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9301]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When you select group of `Switch` and editing color settings for one lightcomponent of two, the effect is applied to both lightcomponents at once. The settings for lightcomponent 1 apply to the settings of lightсomponent 2!
**This is true for** all "lightcomponent" settings!
Video:
https://user-images.githubusercontent.com/93348499/172914816-56342479-7bc2-445b-8f45-228ada808615.mp4

### Reproduction steps

1. Start editor
2. Create two or more `Switches`
3. Select all `Switches`
4. Change the settings of one of the lightcomponents
5. Changes will apply to both lightcomponents!
6. Try to change other parameters of lightcomponent partition.

**This is true fo**r `Reactor` and possible for other objects whose settings have two lightcomponent partitions!
So, You can change the color settings and other settings of lightcomponent just one switch at a time!

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ff53d9fc323b40a308bbecb2cecfde9e4c336c8

**Comment by NilanthAnimosus** [comment]
Tested against 0.18.15.0 unstable, no issues found, closing.

Notes: Only thing I could find worthy of mention (and I consider it harmless) is if you have different types of items selected (IE. a fabricator and a cabinet) which share item component types (IE. item container, light component) if you edit the first in one that has two it will edit the first in the other that only has one of that component, while editing the second will edit nothing on the one that has only one of that component. Tested with multiple switches, fabricators and fabricators and cabinets.
