### ISSUE TITLE
Top left buttons aren't affected when changing HUD scale

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9303]
**Description**
If I change the hud scale these buttons aren't affected
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f91eac45-5c74-4cde-9a70-998e90ef0bfc)

**Version**
0.18.6.0
Branch: bugfixes

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dcf55fb09f741122eb983e9d36fb4c0addd826bf

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, works correctly, closing.
