### ISSUE TITLE
Cargo mission reward displayed incorrectly when a sub switch is pending

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9305]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The number of crates and the reward for cargo mission is displayed for the current sub instead of the sub you've opted to switch to in the UI.

### Reproduction steps

1. Start a campaign with Dugong
2. Unlock some cargo mission that spawns a larger number of crates than Dugong's cargo capacity
3. Buy and switch to e.g. Berilia (don't start a new round yet)
4. Notice that the reward and number of crates is still calculated based on Dugong's cargo capacity

### Bug prevalence

Happens regularly

### Version

0.18.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
