### ISSUE TITLE
Campaign teleporting related crash (Store.ActiveStore is null)

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#9306]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Talking to an outpost merchant after using campaign teleporting crashed the game.

### Reproduction steps

1. Start a campaign
2. Use the `togglecampaignteleport` console command
3. Teleport to a location with no outpost
4. Go talk to a merchant in the starting outpost where you still are
5. Game will crash because Store.ActiveStore is null

### Bug prevalence

Happens every now and then

### Version

0.18.6.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Note: this issue should only happen when using campaign teleporting which requires cheats to be enabled to work

**Comment by ekqvist** [comment]
IIRC stores are only created for locations once they have been discovered (i.e. visited), so that's likely a cause for the issue.

**Comment by ekqvist** [comment]
Fixed in Regalis11/Barotrauma-development@e0d4e64

**Comment by Rokvach** [comment]
There hasn't been any sighting of this appearing in GA after the fix nor has it caused any new issues to surface, seems to be working correctly. Closing.
