### ISSUE TITLE
Occasional prolonged dizziness when firing the gun (sometimes can be really, really, really long).

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9310]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

both happened on vanilla and LFB server
mod Jobs Extend 
sub Typhon 2 [JE]

https://user-images.githubusercontent.com/44423036/173097423-364c0f83-48e0-4502-a0d1-c65be8be8d0f.mp4

### Reproduction steps

very strange... cannot know how to reproduce this, just firing and then this happen.

### Bug prevalence

Happens every now and then

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
Is that a regular moloch, or a moloch boss?

**Comment by esirprus** [comment]
i think that is not important, here is another clip

https://user-images.githubusercontent.com/44423036/173199887-47a12247-993b-46df-8e47-8813699b19c5.mp4

**Comment by mygamingaccount** [comment]
I remember having this happen, but I'm unable to find a way to reproduce it.

**Comment by esirprus** [comment]
same, cannot find how to reproduce this

**Comment by Regalis11** [comment]
No known steps to repro, closing
