### ISSUE TITLE
Button "Snap to Grid" will overlap in "Wiring mode" 

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9311]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Button "Snap to Grid" will overlap in "Wiring mode" .
Something like that: 
https://user-images.githubusercontent.com/93348499/173100799-559d9d6d-1a4e-4025-ad05-13c5ad03ac80.mp4

P.S. For those of you who don’t understand... and confused 😉
It’s quite difficult to place or change the placement of so many wires manually one at a time: 
![Image 002_13-12](https://user-images.githubusercontent.com/93348499/173183633-3dc4da5b-529b-42d8-a3b0-ec1b0dd22bfe.png)
It is not possible to choose several wires at once.
Snap to grid does not work for multiple wires.
Perhaps you should remove these buttons from the interface in wiring mode or it will work with wiring!
Leveling the wiring is a living hell! https://github.com/Regalis11/Barotrauma/discussions/7327

### Reproduction steps

1. Wiring mode
2. Button "Snap to Grid"

### Bug prevalence

Happens every time I play

### Version

0.17.16.0 - This is the latest version but it is missing from the drop-down list!
![Image 001_18-44](https://user-images.githubusercontent.com/93348499/173103092-f40e9bd0-5b2a-4ce3-a32f-8b4a4603d6d5.png)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/112bbe90846ff82b7d7130e6e64c0ea40551444e

**Comment by NilanthAnimosus** [comment]
Tested, works correctly, closing.
