### ISSUE TITLE
Pumps no longer increase pressure in rooms

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#9312]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.

### What happened?

Staying in a room with a pump pumping in used to increase the pressure to lethal levels, but not any more.

The opposite is expected according to the following line:
https://github.com/Regalis11/Barotrauma/blob/564656eded8b45f46dce9d69d5745b513d36da99/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Pump.cs#L143-L144

### Reproduction steps

1. Jump into the Dugong ballast
2. Unwire the contol input
3. Set pump speed to 100
4. Stay in the ballast

Instead of death, nothing happens.

![image](https://user-images.githubusercontent.com/68995233/173106248-5de0b59b-b7a7-4e58-a50e-bd98439a1e18.png)

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Tested unstable 0.18.7.0, result is identical

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5c6c3af5bc502485fefece56a31776820d6e590

I decided to just remove this line from the code: in my opinion, it doesn't make sense for the pumps to increase the pressure to lethal levels in the first place, and I could imagine it being confusing if they did (one probably wouldn't expect the pressure be that high in situations where there's no leaks anywhere).

**Comment by mygamingaccount** [comment]
We used to be able to equalize pressure in airlocks using a pump

**Comment by Regalis11** [comment]
This line doesn't affect that: as long as the hull is full, no water flows into it when you open the airlock door.

**Comment by Regalis11** [comment]
Actually, looks like this line was needed after all: the pump needs to be able to increase the pressure in the hull, or water can't move up from the hull.

**Comment by mygamingaccount** [comment]
Mamma mia, that's some saucy spaghetti!

> I decided to just remove this line from the code: in my opinion, it doesn't make sense for the pumps to increase the pressure to lethal levels in the first place, and I could imagine it being confusing if they did (one probably wouldn't expect the pressure be that high in situations where there's no leaks anywhere).

If you think about it, you don't actually pump water into a ballast tank, you let it in by opening a vent. The pressure is already higher outside the sub, so the pump does no do any work. It shouldn't even consume power when flooding.
