### ISSUE TITLE
Logical components created in different versions of the game - no uniformity of borders?

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9315]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I noticed that in my submarine, the "borders" of the same logical components are different!
I think the "borders" of logical components created in other versions of the game differ from the current component "borders".
Video:
https://user-images.githubusercontent.com/93348499/173181579-7b169b20-7ba0-4b54-ae57-294bbe5d4dfa.mp4 

P.S https://github.com/Regalis11/Barotrauma/issues/7722

### Reproduction steps

Load your submarine in the editor and check the borders of old and new logical components.
1. You can start editor
2. Load vanilla submarine "Azimuth"
3. Add component "OR" (or some other) and compare with existing  component "OR"

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Yes, that is the case. I don't think we should address this though, because it'd misalign these components in older subs.

**Comment by MaaiG** [comment]
> because it'd misalign these components in older subs.

Ок, Is there any way I can do this?
Is there any console command to rebuild them manually or something? :)

**Comment by Regalis11** [comment]
Yep, you can use the command "refreshrect" which updates all the selected items. I don't recommend it though: the non-uniform borders should cause no functional problems, but if you change them, you'll have to realign all of the items manually.
