### ISSUE TITLE
Something’s wrong with the Grid - No uniformity

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9317]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There is no uniformity position.

1. (Video 00:00 - 00:20) - ~~Object is displaced after placing~~ Object moves slightly after placement
    (Video 00:30) - And is knocked out of the grid after several moves
2. (Video 00:20 - 01:26) - Objects are placed differently on different sections of the grid
3. (Video 01:26) - `Switch` light offset

Video: 

https://user-images.githubusercontent.com/93348499/173182404-06793706-734a-4de2-bc99-a7f1cad1ea0d.mp4

### Reproduction steps

**I**
1. Start editor
2. Toggle grid
3. Add logical component
5. Look at the gap between the component borders

**II (Video 01:26)**
1. Create multiple switches
2. Showlighting
3. Look at the light offset

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8c200b8b9e7848edc48d729baf46a5e4c8ade4d8

**Comment by NilanthAnimosus** [comment]
Tested, Working fine. Closing.

Note: tested against commit https://github.com/Regalis11/Barotrauma-development/commit/ 7836074a565ad5656c7d7e7edfbb84cea2bbb5e8 (29th june release branch 0.18.13.0)
