### ISSUE TITLE
Where is the option to log errors too?

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#9320]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seems both the client host and dedicated servers have no way to actually log errors too?

In case I havent overseen any option to enable it: Please add an option to log errors too! Its super important to debug issues! 
And its definately not enough to just show errors in the console in 2022.

Thanks!

### Bug prevalence

Happens every now and then

### Version

Other

### -

any

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
There's a setting called "SaveDebugConsoleLogs" that can be edited in the config file, did you give that a try?

**Comment by CurePindal** [comment]
Well, indeed. No clue how I could oversee that. Multiple times. Guess I expected such option in the serversettings.xml..
