### ISSUE TITLE
(0.18.5+) Regular client connection drop. Cant rejoin (MP, campaign)

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#9321]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

We play an unstable campaign with 5-6 clients (weekly) started with .18.5. Regularily 1 (sometimes 2) client drops out of the game and cant rejoin (at least every other route). Not even as spectator. We have to go back to the lobby so the dropped player can rejoin.

This happens both, client hosted and with a dedicated server. CPU, RAM and network stats are very good with lots of headroom. Pings to the clients are 65ms max. Tracert also shows no traffic issues and no significant packet losses visible.

I assume the rejoin issue is somehow connected to the server not actually disconnecting the player (player is still shown in the player list on the top-left)

If theres anything else I can add/monitor, please let me know. I try to catch the console errors when a player tries to rejoin during our next session.

Only mod used: New Wrecks For Barotrauma (With sellable wrecks)
Custom sub

### Reproduction steps

info above

### Bug prevalence

Happens regularly

### Version

Other

### -

.18.5 to 18.7 tested

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Is there some kind of an error message when the client gets dropped or when they try to reconnect?

**Comment by CurePindal** [comment]
I think there was an error message when they tried to rejoin but it got lost in the console. 
From the feedback there was no kind of error msg for the client when it gets dropped. On rejoin they get stuck in an endless loading screen, so they have to kill the client and restart.
I will try to pinpoint the errors on our next session this wednesday. This time with activated error logging on the dedicated server.
