### ISSUE TITLE
Ballast Flora bug not getting deleted upon respawn shuttle respawning sometimes still triggering

### ISSUE THREAD

**Issue by Padex98** [Regalis11/Barotrauma#9322]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sometimes, if ballast flora infects the respawn shuttle, it doesn't get removed once the shuttle despawns. it doesn't happen very often, but every once in a while it happens just like it used to.

### Reproduction steps

-infect respawn shuttle with ballast flora
-wait for it to despawn and respawn

### Bug prevalence

Happens every now and then

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/85ee5feaa9ce73253fe7f10d15bb17239116daf9

**Comment by NilanthAnimosus** [comment]
Tested, working correctly. closing.
