### ISSUE TITLE
Visible Lights limit affects editor lighting layer

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9327]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the new lights count affects lighting layer in editor

it shouldn't because FPS is not really important for editing (and lighting layer is generally off except to see how things look)

it's really obtrusive to have to change settings between editing and other modes.

### Reproduction steps

1., set lights count to 10

2. open dugong in editor
3. turn on lighting layer
4. only 10 lights

### Bug prevalence

Happens every time I play

### Version

0.18.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
Dugong, according to editor of someone who has lights set to minimum 
![image](https://user-images.githubusercontent.com/5103517/173305116-16dc9230-604f-4e2a-a753-e6b7119bc229.png)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/781aeaddb9d7600135c47d7b824966bbc2f1681c

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.13.0, works correctly, closing.
