### ISSUE TITLE
[Unstable 0.18.9.0] Game corrupts upon veryfying/installing it from steam

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#9331]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When i was veryfying files of unstable barotrauma, some of them always get corrupted. Here is example of it:
[info.txt](https://github.com/Regalis11/Barotrauma/files/8892903/info.txt)
[cityNames.txt](https://github.com/Regalis11/Barotrauma/files/8892904/cityNames.txt)
[locationNames.txt](https://github.com/Regalis11/Barotrauma/files/8892905/locationNames.txt)
[MapGenerationParameters.txt](https://github.com/Regalis11/Barotrauma/files/8892906/MapGenerationParameters.txt)
[alienNames.txt](https://github.com/Regalis11/Barotrauma/files/8892907/alienNames.txt)
and it happens with nearly every file expect for files inside `Character` and main folder.

after that game refuses to launch.

This thing doesnt occur with stable version of game.

### Reproduction steps

1. Delete Barotrauma in steam
2. Delete left-overs in `\Steam\steamapps\common`
3. Install unstable barotrauma

### Bug prevalence

Happens every time I play

### Version

0.18.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by Regalis11** [comment]
Should be fixed now

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
