### ISSUE TITLE
Fabricator search problem

### ISSUE THREAD

**Issue by PiatraAlatyr** [Regalis11/Barotrauma#9334]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This happens when the game is in Russian. Recipe search in fabricator does not work correctly. For example, if I search for a recipe for a projectile, it shows me recipes other than the word "projectile" other than "projectile" itself. Or, if you search for "battery", it will only show its fulgurium version.
I doubt that the mods that I have could affect this, since they do not affect crafting.
![Снимок экрана (1884)](https://user-images.githubusercontent.com/36773134/173573835-1cfb2b5d-1fad-40c9-a83d-b657c822bad6.png)
![Снимок экрана (1886)](https://user-images.githubusercontent.com/36773134/173573864-49b52b88-5fdb-44ce-860f-758e0b0549db.png)

### Reproduction steps

1. Change game language to Russian
2. Type a recipe name in fabricator
3. It doesn't show it

### Bug prevalence

Happens every time I play

### Version

0.18.10.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This seems to have been caused by a change we did to address https://github.com/regalis11/barotrauma/issues/8858. I reverted that change for now, so this should be fixed.

**Comment by PiatraAlatyr** [comment]
So it is. Now there is no problem.
