### ISSUE TITLE
[Unstable 0.18.10.0] Dual pistols cannot be reloaded properly via quick reload feature

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#9339]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dual Alien Pistols still cant be reloaded with alien power cells via quick reload feature

refering to this
`Fixed quick-reloading working incorrectly when trying to reload from a stack that doesn't fully fit in the weapon (e.g. when double clicking on a full stack of revolver rounds with a half-loaded revolver in hand).`

### Reproduction steps

1. quickstart selkie in console
2. spawn 2 alient pistols with 2 powercells
3. try to reload em like you do with dual-revolvers

### Bug prevalence

Happens every time I play

### Version

0.18.10.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/83b4644bb58bd4862bdcd3212319493e8cba52b9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
