### ISSUE TITLE
"Black Market" event has broken CheckMoneyAction

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#9341]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The highlighted CheckMoneyAction tag doesn't have a specified "amount", so it will always succeed even if the player has less than 500 marks.
![image](https://user-images.githubusercontent.com/67431770/173709188-b672277e-989f-4605-b0ac-e6a05e883ea3.png)

### Reproduction steps

1. Start a multiplayer campaign and enable cheats.
2. Run the command `money -1000000` to set your money to 0.
3. Run the command `triggerevent blackmarket`.
4. Talk to the guy that spawns and select option 1.
5. Repeat steps 3 and 4 until you get the option to purchase eggs.
6. Purchase the eggs.

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/377f38410f4632b267ef803d32cd004eb8248e7b

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.13.0, works correctly, closing

Note: Checked other events and they should also be fine and have a value assigned.
