### ISSUE TITLE
You spawn in as a new character if you use freecamera and the round ends

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9342]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

During community testing I was using freecamera to check what everyone was doing and the round completed while I was still using freecamera, I did use the control command during level transition/round summary but ofc it didn't work, just threw a error "Could not find the speficied character" and when the next level loaded in I started as a new character

### Reproduction steps

1. Load up multiplayer campaign
2. Use freecamera and transition to the next level (might require multiple clients)
3. Use control command during loading screen when you have access to console (This step might not be necessary)
4. Once the new level loads notice that you have a new character

### Bug prevalence

Just once

### Version

0.18.10.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm suspecting this might be the same issue as https://github.com/regalis11/barotrauma/issues/9536. If that's the case, this should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6f6d88536afb55f97efe7638da019d1ff89b63d

**Comment by Rokvach** [comment]
Tested, you spawn in your correct character and keep all of your items and wallet etc as they were. Closing.
