### ISSUE TITLE
Deconstructor doesnt lock input if started before switching rounds

### ISSUE THREAD

**Issue by Liberation546** [Regalis11/Barotrauma#9344]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I noticed that when the deconstructor is running when you enter a new session, you can put items into it while it's processing. I expected it to lock the input slots when the session changes.

### Reproduction steps

1. Start campaign save
2. Put item in deconstructor and turn it on
3. Undock
4. Go to the deconstructor and attempt to put items in it while processing

### Bug prevalence

Happens regularly

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.15.1

It indeed doesn't lock, but actually getting to the deconstructor fast enough (I.e.. docking at an outpost or such) is difficult, and it doesn't break anything or cause issues (the deconstructor simply stops deconstructing the item in question

if more than one item is loaded the timer to deconstruct continues (IE. 30% done) on the next item moving it along.

if an item is moved along when the currently deconstructed item is removed, it gives out the correct resources too.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ea79530f0240af1936bcee17c42e902d05f96f3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
