### ISSUE TITLE
Unable to reset keybinds during round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9347]
**Description**
If you press the Reset button during a round it will just close the settings menu without actually resetting your keybinds

**Steps To Reproduce**
1. Load into singleplayer
2. Try resetting keybinds
3. Notice that settings just closes

**Version**
0.18.10.0

**Comment by Regalis11** [comment]
I wasn't able to fully repro this: the button reset the keybinds correctly, the problem seemed to just be that the settings menu closed. Fixed the closing in https://github.com/Regalis11/Barotrauma-development/commit/6c0752189d29e4c8254a767f577ee3dce86b081d

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/36e3a2755f5fc201a748a32b63cc93a8eb30d90a, works correctly, closing.
