### ISSUE TITLE
Campaign saving doesn't load

### ISSUE THREAD

**Issue by TheKabachek** [Regalis11/Barotrauma#9350]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/107561411/173844883-39af1f24-3ee3-42af-8cda-0c304bce2cc2.png)
When you start a certain save, this window appears, if you click "no", nothing will happen and the save will load indefinitely. Everything is fine with the other saves.

### Bug prevalence

Happens regularly

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Do you mean this always happens with some specific save? Would it be possible to send us that save so we could give it a try? Note that you need to .zip the save files to post them here, because github doesn't allow attaching files with the .save file extension.
