### ISSUE TITLE
Shredder ammo called exploding in russian version

### ISSUE THREAD

**Issue by AbyssBeast09** [Regalis11/Barotrauma#9351]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![unknown](https://user-images.githubusercontent.com/85645359/173899685-5ccc5be4-1104-45d4-9f60-191bd2ae7177.png)
![unknow2n](https://user-images.githubusercontent.com/85645359/173899682-e782e3d9-65cf-4e19-8c5a-5ddb0331342f.png)

Shredder ammo(aka piercing ) called exploding in Russian translation 
Dont know why but its a fact 

(Пробивные - piercing 

Разрывные - exploding)

### Reproduction steps

Just read the name of shredder ammo in russian version

### Bug prevalence

Happens regularly

### Version

Other

### -

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Note that the shredder ammo is not the same as piercing ammo. Shredder ammo causes heavier bleeding than normal ammo, while piercing has high armor penetration. In any case, I'll pass this report to the translators!

**Comment by itchyOwl** [comment]
Yeah it's not quite the same: more flesh tearing, less piercing. Coilgun has piercing ammunition that you goes through multiple targets cleanly, causing less damage, whereas the chaingun shredder bullets don't go through multiple targets but will cause heavy bleeding and also are relatively good at breaking the armor. Certainly they don't explode.

**Comment by Krzeszny** [comment]
Convenient evidence proving that the sprite is indeed misleading #9429  :)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
