### ISSUE TITLE
Shotgun Rubber Shells are impossible to fabricate

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#9353]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The new Rubber Shells are impossible to fabricate, because they require a recipe but no talent unlocks it.

### Reproduction steps

1. `quickstart humpback`
2. `power`
3. `unlocktalents All`
4. search "Shotgun Rubber Shell" in the fabricator's menu.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a80d903bca00fe29e77d06816d57d53459262a82

**Comment by Rokvach** [comment]
Tested, no issues. Closing as this doesn't need a review.
