### ISSUE TITLE
Oxygen tanks way too abundant on colonies

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#9358]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This crewmate went around stealing and brought back like 80 something O2 tanks from a colony station

### Bug prevalence

Just once

### Version

Other

### -

0.18.11.0

### Which operating system did you encounter this bug on?

I use Linux, by the way

**Comment by ubertpendragon** [comment]
In colony supply cabinets, there are 3x8 oxygen tanks

Very easy to steal without getting seen since colonies are huge

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@37b99e7.

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0,

All tank holders generated with 3x1 tanks (not 3x8 tanks and such).

I couldn't find any oxygen tanks (4 from diving masks?) in the city outpost. I tried a few, but there was basically none now.

In other station types I could find around 10 or maybe 12 tanks (from 2 diving suit lockers with 3 spare tanks below them each, plus an odd diving mask perhaps in supply cabinets)

Are we intending to have virtually no oxygen tanks be the norm with the "City" type here as they don't tend to generate with any diving suits?

**Comment by itchyOwl** [comment]
Nah, it's just an oversight. Need to check it out.

**Comment by itchyOwl** [comment]
It seems to be that there's no diving suit containers, oxygen tank containers, or crew cabinets in the colonies. But there are supply cabs, which should were missing the spawns. Fixed in Regalis11/Barotrauma-development@9902d35.

**Comment by Regalis11** [comment]
@NilanthAnimosus [The commit](https://github.com/Regalis11/Barotrauma-development/commit/37b99e7) that removed the tanks from the cabinets is not present in bugfixes. This should be tested in dev.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by mygamingaccount** [comment]
Version 0.19.3
![image](https://user-images.githubusercontent.com/68995233/188688390-72f818a4-c52e-47d9-80ce-6915493d7003.png)

**Comment by Regalis11** [comment]
I took a quick look at some of the colony modules, and couldn't find any tanks in any other cabinet than that specific one in DockingModule_01_Colony. @itchyOwl probably missed that one when removing the manually placed tanks from the modules. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a4514e7b8478e89c1da06ee5ea0910b7cbd6df0

**Comment by ubertpendragon** [comment]
You also might want to look at both Engineering modules (not Colony)

Both of them have isolated, easy to steal Diving Suits + Oxygen Tanks, so every single outpost you get away with free resources
Unless reputation/stealing is reworked in the future to be more punishing, perhaps remove the bottles and replace it with a disposable suit
 
![image](https://user-images.githubusercontent.com/73229309/188842768-ff1499c4-b216-41f8-b0f2-e0a7d6fab697.png)
![image](https://user-images.githubusercontent.com/73229309/188842993-00af0c82-069f-40ec-a93f-988d39fb4858.png)

**Comment by Rokvach** [comment]
No issues, closing.
