### ISSUE TITLE
Respawn shuttle: Diving suits don't spawn inside lockers

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9359]
No Diving suits inside lockers, they kind of just drop on the floor
Happens in both missions and campaign

![image](https://user-images.githubusercontent.com/73229309/173963623-3788d873-d066-46af-8104-6ea7349db8d1.png)

Put a disposable in editor by default and don't spawn extra suits? (players can pick the respawn shuttles and amount of suits accordingly)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62fa2c0f7695bb1eb1128e40aff7083e2ae6733b

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f609686dfa35292886709d3d100245059f6a595

> Fixed server trying to place all previously spawned respawn items into containers on every respawn, even if the items have already been removed. Happened because we never cleared respawnItems, and because we used that list when placing new respawn items into containers

**Comment by NilanthAnimosus** [comment]
What about the crash related to "tried to stack different types of items" ? does the above fix resolve that too?

**Comment by ubertpendragon** [comment]
> Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f609686dfa35292886709d3d100245059f6a595
> 
> > Fixed server trying to place all previously spawned respawn items into containers on every respawn, even if the items have already been removed. Happened because we never cleared respawnItems, and because we used that list when placing new respawn items into containers

Isn't this a little overengineered?

Selkie and Venture have respectively 2 and 4 suits. Hemulen can fit 6, then it's up to the host to pick a shuttle of the proper size
It's probably simpler to pre-equip respawn shuttles with Disposable suit.

It's strange that the Hemulen only has 2 suit slots
![image](https://user-images.githubusercontent.com/73229309/185181547-c9e2dcd5-43a4-4b2b-8897-030b780f28e7.png)

All respawn shuttles have issues of their own and could use some cleanup in the future

**Comment by Rokvach** [comment]
Tested, the suits spawn depending how many players are respawning and first fills the lockers and then spawns them on the ground, I think this is a lot better than previously when all of them just spawned on the floor and the lockers were empty, so working correctly. Closing.
