### ISSUE TITLE
UI Suggestion 

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#936]
I'm more content with the UI as it is now than before, but I have a few more suggestions for it.

#1: remove the profile photo of the head, it takes up space and is generally silly looking
#2: keep the bot commands auto closed, to take up less space
#3: move the text box into the bottom right corner
#4: move the inventory and clothes and radio and id card to the bottom left, and shrink them a bit
#5: on that note shrink most of it!
#6: profit?

Generally I'd like that more, but if you're certain, could you add the option to switch between my proposed UI and the default UI (yours)?

Thanks in advance, moi

**Comment by Regalis11** [comment]
1. The profile photo is still a work in progress, we might add the option to toggle it off.
2. This sounds like a good idea, I think I'll test it and see how it works.
3. I think the way the UI elements are spread out at different corners of the screen prevents any individual part of the view being obstructed too much. Is there a particular reason you want the chat box to be in the bottom right corner?
4. Why bottom left?
5. The scale of the UI elements and inventory can be adjusted in the settings menu.

**Comment by AbominationBanisher** [comment]
For points #4 and #3, it's mainly because I think the playerbase got pretty used to where those things usually were (including me a tad bit). Just thinking it would be a bit unusual with those things in such places, but this shouldn't be a priority in the development, just a detail that would be nice.
