### ISSUE TITLE
The sounds of ventilation, oxygen generator and reactor on all boats disappeared

### ISSUE THREAD

**Issue by foolinthedesert** [Regalis11/Barotrauma#9361]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The sounds of ventilation and oxygen generator on all boats disappeared.

### Bug prevalence

Happens every time I play

### Version

0.18.10.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9d8516c3d9e5a3054d53c9700e4c6b6d6da902bd

**Comment by Rokvach** [comment]
Tested, I didn't spot any issues, if nothing is found during review this ticket can be closed
