### ISSUE TITLE
Cannot save a ship with more than 60 shadow casting lights.

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#9364]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

There I was... Excited cause finally this version will allow me to edit ships again, without the fear of losing the save suddenly...

And.. You can't save the ship in local............................................................................ Because ... ... reasons.
![20220616115623_1](https://user-images.githubusercontent.com/1114115/174034600-a28f5152-2c9c-4b09-96ec-30360c70c0c4.jpg)

So Now I have to search manually for every single shadow casting light, because it was too much to ask for a search function. A Filter I asked for, year ago.

### Reproduction steps

Open old ship that has more than 60 shadow casting light. Try to save it.

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
:( sad face
```

**Comment by MaaiG** [comment]
I sad too ;)
https://github.com/Regalis11/Barotrauma/discussions/9308

**Comment by Regalis11** [comment]
This is not a bug: we added this specifically to prevent sub builders from adding such a huge number of lights to their submarines. A warning didn't seem to be enough, so we unfortunately had to take more strict measures. You should try to keep the number of lights way lower than this, or it _will_ lead to performance issues, but if you really insist on doing this, you can bypass the limitation by entering the command "debugdraw" in the console.
