### ISSUE TITLE
Issues on character damage visuals

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9365]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Damage visuals (skin tints and overlays) don't show up on wreck corpses, and potentially other characters/monsters that die off-screen. 

There's a couple of issues that cause this:
- [x] The visuals are only updated when the character is alive (when CharacterHealth.Update runs) or when the character is killed. As a result, only the first afflictions applied on the corpses take effect (i.e. the oxygen loss).
- [x] I added an optimization in https://github.com/Regalis11/Barotrauma-development/commit/b74a86310073918b5d9c3560572fd29426996e23 that skips updating the visuals when the character is not visible, so if a character stays off-screen for the entire duration it's taking damage and dies off-screen, the visuals won't show up.
- [x] In multiplayer, the server doesn't include the full affliction data in the "Kill" messages (just the cause of death), so clients won't know about the afflictions and can't apply the visuals correctly.

- [x] Somewhat related: applying the oxygen loss on the corpses kills them, which is logged in the server log. We only skipped logging in the last part of the corpse spawning where we explicitly kill the character.

### Reproduction steps

1. Start a wreck mission
2. Go and take a look at the corpses

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Partially fixed in https://github.com/Regalis11/Barotrauma-development/commit/f63eaa3580892bf077ad372165f3309ef51c349b: the only remaining issue is that clients aren't notified of dead characters' afflictions.

**Comment by itchyOwl** [comment]
Hmm, I'm pretty sure they did work like I intended when I implemenented them.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b26d318bf9871f7ff468f28aa3f910b8810e3552

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.13.0 with a server, Some minor issues found.

Testing concludes most wreck corpses have afflictions and the details show correctly with the exception of when a networking issue occurs probably related to the issues in #9318 regarding writing spawn data.

However off-screen (Presumably disabled) living characters do not have damage effects applied. (IE. giveaffliction on a living pirate after moving your sub extremely far from them). if they die to the first affliction or the 10th, none of it is sent. the client will have whatever old state of afflictions they saw before they were dead - dying not updating the afflictions and thus the damage visuals are also incorrect.

**Comment by Regalis11** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/22b91d6a1e2c5df9b350d744e69781836cc2d4b1

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/6efb667a91d39ee7715a094a89a32ed20b73d6ec, Works correctly, closing.

Small note: You can now hilariously see death by kill command, though you can still achieve a kill by using giveaffliction (Say, radiation poisoning is a solid way to kill somebody usually).
