### ISSUE TITLE
Localization (russian) - some new issues

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9366]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**1. Localization is no longer displayed for these strings:**
Sub editor
![Image 001_14-33](https://user-images.githubusercontent.com/93348499/174061969-26c25e00-6fe2-44c4-9b57-f2ee99533546.png)
`<sp.item.spritedepth.name>Sprite Depth</sp.item.spritedepth.name>`
`<sp.structure.spritedepth.name>Sprite Depth</sp.structure.spritedepth.name>`
`<sp.hull.spritedepth.name>Sprite Depth</sp.hull.spritedepth.name>`
`<sp.item.hiddeningame.name>Hidden In Game</sp.item.hiddeningame.name>`

Settings
![Image 001_14-17](https://user-images.githubusercontent.com/93348499/174062461-e7916df4-9031-4e23-989d-10aa0504063f.png)

Saving submarine
![Image 001_15-38](https://user-images.githubusercontent.com/93348499/174071705-16d0ba55-6954-4f4a-b4c4-9a29c09aef29.png)

**2. Isn't translated**
![Image 001_14-26](https://user-images.githubusercontent.com/93348499/174062535-339c2764-ded3-48f9-93b9-1f5e438d80a3.png)

**3. Doesn't fit**
![Image 002_14-26](https://user-images.githubusercontent.com/93348499/174072296-2ed3e108-6e26-4b0e-b486-8de7980a2fec.png)
Localization fixed on image!
`<editor.layer.headervisible>Отображение</editor.layer.headervisible>`
`<editor.layer.headerlink>Соединить</editor.layer.headerlink>`
Must be:
`<editor.layer.headervisible>Показать</editor.layer.headervisible>`
`<editor.layer.headerlink>Связать</editor.layer.headerlink>`

_P.S. Is there a console command to reboot and apply fix localization files without restarting the game ("on-the-fly"). Is it possible to do this?_

### Reproduction steps

1. Change language to Russian
2. Watch

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed the "apply" and "cancel" buttons in https://github.com/Regalis11/Barotrauma-development/commit/46af20b3ad88ded6eb6510b6843105dad993f867

Fixed the "save" button and added the "outpost" subcategory to localization in https://github.com/Regalis11/Barotrauma-development/commit/2f1c0bc46a1bb272b815a6d90bb7127ac77cc48b

"Sprite depth" and "hidden in game" have been left unlocalized on purpose for the time being, along with a big chunk of other entity properties. Since there's a huge amount of different properties to localize, and we make frequent changes to the properties, we've decided to leave localizing them for later (although, we will get to it pretty soon).

**Comment by MaaiG** [comment]
Ок. Just in case russian version for your translator :)
`<sp.item.spritedepth.name>Глубина спрайта</sp.item.spritedepth.name>`
`<sp.structure.spritedepth.name>Глубина спрайта</sp.structure.spritedepth.name>`
`<sp.hull.spritedepth.name>Глубина спрайта</sp.hull.spritedepth.name>`
`<sp.item.hiddeningame.name>Скрывать в игре</sp.item.hiddeningame.name>`

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/19bb2dffd537d3a9dde093d6d5c2bb41b4a68b25, looks fine now. will leave open incase the new translation is off for outpost text.

notes:

- Can confirm all language packs now contain the subcategory outpost with a translation.
- Save submarine button is correctly translated now as well as settings menu cancel/apply.
- Manage groups text for "Link" list header still doesn't fit, but UI elements not fitting could probably be its own issue.
