### ISSUE TITLE
Duffle bags become invisible instead of despawning

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9372]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Once duffle bags reach 0% durability, they become invisible. The items even remain inside.

I've only tested this once, in multiplayer.

### Reproduction steps

1. Wait out the durability
2. Mouse over the place a duffle bag was at

### Bug prevalence

Just once

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this:

https://user-images.githubusercontent.com/14351070/174269028-2befacf2-6acc-432c-855d-551927761875.mp4

Do you mean that the duffel bag was on the floor when it disappeared? That seems like a bug in itself: the bags should only deteriorate when they're being held. I gave this a test too, but the bag didn't seem to deteriorate nor become invisible when on the floor.

**Comment by Krzeszny** [comment]
> Do you mean that the duffel bag was on the floor when it disappeared? That seems like a bug in itself: the bags should only deteriorate when they're being held. I gave this a test too, but the bag didn't seem to deteriorate nor become invisible when on the floor.
> 
> I also wonder if the mods you're using could have something to do with this?

Yes, the bags became invisible on the floor. If it's hardcoded (could it be?), it could have something to do with mods. Otherwise, I don't know. It only happened once.
