### ISSUE TITLE
Unfinished Dialogue Options

### ISSUE THREAD

**Issue by BigSweatyMen** [Regalis11/Barotrauma#9374]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The dialogue tree for captive souls is incomplete.
![Incomplete Dialogue Barotrauma](https://user-images.githubusercontent.com/107653064/174190744-dfa6bcbe-18e2-47dc-89d1-d71b5c2e38f3.png)

### Reproduction steps

I would assume this happens to everyone that gets this set piece.

### Bug prevalence

Just once

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/34f88105da134f916b143413e6709d56382630e7

**Comment by Rokvach** [comment]
Tested, working correctly. I don't think this needs a review. Closing.
