### ISSUE TITLE
can't harpoon or melee nest eggs

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#9378]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

can't hit the eggs in nest missions with non-explosive harpoons or melee weapons

### Reproduction steps

try to hit nest eggs with one of those

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by AbyssBeast09** [comment]
balls issue

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9e18db0ff0cc04b49fd5c89edcff53e094a3f13e

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.13.0, Seems to be working fine but one small note.

At first with melee specifically I wasn't sure if I was hitting the egg or not (I thought I might have been hitting the background wall) - as no health bar or measure of progress appears and I was easily missing the damage effects on the egg itself with melee - especially so if in the darkness and it can be hard to hit on a server with a diving knife.

Harpoons, knives and crowbars were all fine though.

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, working correctly, closing.
