### ISSUE TITLE
Occasional "the given key was not present in the dictionary" errors when giving orders

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9383]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can sometimes disconnect with an error saying "the given key 'xxxx' was not present in the dictionary" when someone gives orders or reports something.

### Reproduction steps

This can be a little difficult to repro since it only occurs if the bytes in the message happen to align in a specific way. I was able to repro it reliably by doing the following:

1. Make the server include multiple chat messages in the same packet (duplicate the line WriteChatMessages(outmsg, c) a couple of times in GameServer.ClientWriteIngame). Normally this can happen when multiple orders are given nearly simultaneously.
2. Make two clients join a server
3. Give some orders

### Bug prevalence

Happens every now and then

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bc2a87ffa609988397819f4c0b299710a0d41911

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce this with the given steps, seems to be working correctly. Can be closed if nothing is found in review
