### ISSUE TITLE
Not mirrored Illumination - Heater

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9387]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When mirroring an `heater` (after 90 degree twist) not mirrored Illumination.
https://user-images.githubusercontent.com/93348499/174329896-977b1ba8-5b41-45d5-beb7-54aff95db866.mp4

### Reproduction steps

1. editor
2. create heater
3. rotate `heater` - 90 degries
4. mirror-X
5. not mirrored heater Illumination.

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/68229452cc6fb879d508e659e4cc5cada2a5add1

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.13.0, works correctly, closing:
