### ISSUE TITLE
Incorrect information in the error message window

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9389]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Image 001_18-47](https://user-images.githubusercontent.com/93348499/174333448-f11ca958-874c-418f-9388-956ca1a3ed1a.png)

### Reproduction steps

1. Editor
2. Try save sub with more than 600 lighting sources.

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6bb8033fcaa4d986c09582a43146c24dfc34c87f

**Comment by NilanthAnimosus** [comment]
Tested, working correctly. Closing.
