### ISSUE TITLE
Unable to reset keybindings back to default with the reset button.

### ISSUE THREAD

**Issue by GracedTarkov** [Regalis11/Barotrauma#9400]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I thought that LOCAL CHAT (LEGACY) and RADIO CHAT (LEGACY) were the old push to talk keys. Turns out they are for text chat and when I tried to use the reset button to unbind them back to none it didn't work. I have them set to RightAlt for now so they are out of the way. Then I checked to see if this happened to the other keybinds. I changed some of them around then tried to use the reset button to put them back to default and they stayed their changed binds. So I manually changed them back to default, but I am unable to change LOCAL CHAT (LEGACY) and the RADIO CHAT (LEGACY) binds to none still. 

![issue (2)](https://user-images.githubusercontent.com/96236991/174431721-024f6795-5d6d-4eab-88f2-6c5ac2669bd7.PNG)

### Reproduction steps

Go into settings and change some keybinds then apply. Then try and use the reset button to set them back to default. 

### Bug prevalence

Just once

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce this:

https://user-images.githubusercontent.com/14351070/174571818-694e2036-ca46-4ba1-bb32-98cd0378e5e3.mp4
