### ISSUE TITLE
Winterhalter has a 10k output default reactor

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#9407]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Winterhalter has a 10k output default reactor.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Yes?

**Comment by Kaillera** [comment]
> Yes?

Doesn't seem in lined with all the other subs. It also allows the EDC at the bottom to be spammed when plugged into junction box.

**Comment by danielasteljoki** [comment]
Adressed in c8efbad.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
