### ISSUE TITLE
Kastrull drone failed to load (empty XML document)

### ISSUE THREAD

**Issue by FrenzySlayer** [Regalis11/Barotrauma#9409]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever I load into a mission the debug console pops up and says "Failed to load a linked submarine (empty XML document). The save file may be corrupted." This only happened after I purchased and used the Kastrull and possibly after we tried to fumble around with the wiring in the sub; however, there was never a drone on the sub. When we loaded into the first mission we could not use the drone that I assume was supposed to come with the sub. Picture of the debug console included
![20220618155718_1](https://user-images.githubusercontent.com/107772281/174455423-a5282ccf-9ba3-4c44-83f8-1d4a566ee5d3.jpg)
.

### Reproduction steps

1. Host multiplayer campaign server.
2. Load into mission
3. Check Debug console

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to load a linked submarine (empty XML element). The save file may be corrupted.
```

**Comment by Regalis11** [comment]
Most likely a duplicate of https://github.com/regalis11/barotrauma/issues/9380, needs testing

**Comment by abc8773** [comment]
This also occurs in solo campaign

**Comment by Rokvach** [comment]
This issue hasn't been spotted during internal and Unstable testing, we've also done quite a few changes to linked subs and tested them extensively, I doubt this issue will come up again. Closing.
