### ISSUE TITLE
Huskappendages refer to the wrong filepath

### ISSUE THREAD

**Issue by mcbanekenney** [Regalis11/Barotrauma#9411]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I am modding in the version of the husk infection seen in the pre-alpha versions of the game as a separate infection, and ever since the modding refactor the huskappendage has produced the attached error when it should render at 100% infection.

The filepath the texture refers to is "%ModDir%/Huskappendage.png" where the texture file is stored.

### Reproduction steps

Create a custom husk infection as a local mod, put a texture file for a husk appendage in the mod folder, reference said texture in that infection's huskappendage, should create a similar error when the appendage renders at the active threshold.

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Sprite "Content/ContentPackages/Huskappendage.png" not found!
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ca81c3b5edb091a95a808add55d3cb7fc83108b

**Comment by NilanthAnimosus** [comment]
The above noted behavior was fixed in https://github.com/Regalis11/Barotrauma-development/commit/9e54e27396a0da5261d702fe56923ddb45faf3fa.

**Comment by NilanthAnimosus** [comment]
Tested, works correctly, closing.
