### ISSUE TITLE
Grabbing Bandolier grants +30 Weapon Skills

### ISSUE THREAD

**Issue by armoha** [Regalis11/Barotrauma#9413]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Grabbing Bandolier gives +30 Weapon Skills. I think +15 Weapon Skill bonuses are calculated on each hand.
Wearing Bandolier and Gunner's Helmet, and carrying Bandolier grants total of +55 Weapon Skills, easy to produce Masterwork quality weapon.

### Reproduction steps

1. Get Security Officer's Tier 2 talent Gunsmith
2. Craft Bandolier
3. Drop Bandolier and grab it by 'E'.
4. You'll see +30 Weapon Skills bonus on tab status window.

![image](https://user-images.githubusercontent.com/16814706/174471929-1d8d8a9e-5b5f-4cb8-a99e-4694ea43040a.png)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/23719e7e0eddee390c26acca75b13d23e29dd07e
