### ISSUE TITLE
Implacable gets wasted if you have Still Kicking

### ISSUE THREAD

**Issue by Bugfinder1** [Regalis11/Barotrauma#9415]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If a Security Guard has the Implacable talent and Still kicking from an endocrine booster, implacable will be wasted

### Reproduction steps

1. Start a Server
2. Using Console commands give your character Implacable and Still Kicking talents
3. Wear a mask with welding fuel inside
4. Go unconscious 
5. Observe how your character gets revived and uses Implacable at the same time.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Still Kicking no longer exists in the reworked talents
