### ISSUE TITLE
Ballast Flora & Docking Ports

### ISSUE THREAD

**Issue by Zeklo** [Regalis11/Barotrauma#9419]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Ballast Flora doesn't spread between docking ports from shuttles into ships or from ships into shuttles.

I'm not sure if it's a simple error, or a technical limitation but it'd be a shame. Ejectable ballast pumps on custom ships could be really fun! 

### Reproduction steps

1 - Get ballast flora.
2 - Check docking ports.
3 - The flora won't cross over.

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is sort of intentional, sort of a technical limitation - it's somewhat complicated to make the flora spread across multiple subs, and we decided to just make it stay in one.
