### ISSUE TITLE
When resizing a structure, an object located on its border stays highlighted

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9424]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When resizing a background wall, an object located on its border (drag point) is selected.

https://user-images.githubusercontent.com/93348499/174589439-7da0aa2a-ea17-4f5f-be15-910ea4f0e15f.mp4

### Reproduction steps

1. Editor
2. The size change point must be within the object
3. Resizing a background wall

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Krzeszny** [comment]
Looks low prio

**Comment by MaaiG** [comment]
> Looks low prio

Yep, but since I stumbled upon it... It's probably nothing, but since I did some reports, I mentioned this too. ;)

[That’s](https://github.com/Regalis11/Barotrauma/issues/7496) what really bothers me :)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5031bef1cc8572eea44d4dee0049b77232011da7.

Note for testing: the object didn't get selected (as you can see in the video), it only stayed highlighted (showing the white border around it).

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

Tested both selecting then dragging items from intersecting points and resizing walls where they intersect other objects, the selection border no longer appears over items that are not selected when moving or resizing other objects/walls.
