### ISSUE TITLE
Bug or Tool? Object properties window works like a storage buffer

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9425]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A) When you move an object to the properties window, you can release the RMB and configure the properties of the object. Then, you can "take" the object from any place in the properties window and move it to the desired location. Or simply drag the mouse over the property window.
B) This is useful when copying an object and changing the properties of its copy, but unfortunately the properties of both copies will be change.

If it's a mistake - it is for the copy operation only (B), as the properties of both objects are changed, not just their copy.
That interesting as a tool for using the second (B) option: `copying an object with changing properties`!
But need fix - only copy properties must be changed!

https://user-images.githubusercontent.com/93348499/174593432-44d905b6-954b-4119-ba3f-209bb6e19b4c.mp4

### Reproduction steps

1. Copy object
2. Drop a copy to the properties window
3. Change property
4. Hold CTRL
5. Take object from property window
6. Drag to the right place

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I would not consider this a bug - you're still dragging the item when you bring the cursor over the panel, and then edit it's properties, and when you finally place the copy on the screen, it copies the current (edited) properties of the old one.
