### ISSUE TITLE
Typo in event text

### ISSUE THREAD

**Issue by YurakuHigurashi** [Regalis11/Barotrauma#9428]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

EnglishVanilla.xml :
```
<eventtext.unlockpatheuropanridge.o1>“Would a donation of 4,000 suffice?”</eventtext.unlockpatheuropanridge.o1>
<eventtext.unlockpatheuropanridge.c1>“It says here you've been helping the effort to colonize the Ridge. For that, we've decided to grant you access to the Aphotic Plateau. Bon voyage!”</eventtext.unlockpatheuropanridge.c1>
<eventtext.unlockpatheuropanridge.c2>“Looking to pass through to the Plateau? I don't know... I haven't seen much effort from your side to prove your loyalty to the cause. A donation would go a long way.”</eventtext.unlockpatheuropanridge.c2>
<eventtext.unlockpatheuropanridge.o1.c1>“Ah yes, that will work. You shall now pass.”</eventtext.unlockpatheuropanridge.o1.c1>
<eventtext.unlockpatheuropanridge.o2.c1>“Oh? You're welcome to stay in the Europan Ridge for as long as you want, in that case.”</eventtext.unlockpatheuropanridge.o2.c1>
<eventtext.unlockpatheuropanridge.o1.nomoney>“I'm sorry. I can't accept anything less than twelve thousand marks. Maybe you should salvage a couple more wrecks. Or whatever it is you do.”</eventtext.unlockpatheuropanridge.o1.nomoney>

```
Passage prices were changed but <eventtext.unlockpatheuropanridge.o1.nomoney> line wasn't changed. This issue is present in other languages (Russian).

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2df64e097d444b50e0ae15db29f7f8d4c0a12e99

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.13.0, fixed in english, not fixed in most if not all none-english translations.

This issue is prevelant amongst Brazilianportuguese, germanvanilla, japanesevanilla, polishvanilla, russianvanilla and I think turkishvanilla - so it is likely in every translation text other than english.

**Comment by Regalis11** [comment]
Yeah, we still haven't received the localized texts from the translators, should've mentioned that in the comment. I'll add the 'waiting' label, let's re-check this when the texts have been updated.

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/fce88d95d454f11167d99f1010d2acadacf60dcc

**Comment by NilanthAnimosus** [comment]
Tested against 0.18.14.0, works correctly, closing

Note: checked through the translations as well as english and found all lines for this event now correctly use 4000 marks instead of 12000 marks as the insufficient money text, considering this fixed and closed.
