### ISSUE TITLE
Physicorium Coilgun Ammo and Shredder Chaingun Ammo sprite inconsistencies

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9429]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. Physicorium Coilgun Ammo's color, although legacy-like, is inconsistent with Physicorium Chaingun Ammo and Physicorium itself (which is yellow or orange). Chaingun ammo looks alright, so props for the designer. 
![Barotrauma_S1JkZiGcoG](https://user-images.githubusercontent.com/10529134/174612390-7603ffbf-487a-422b-8e0e-e38d666cb68b.png)
One more reason to recolor physicorium ammo is that it looks exactly like depleted fuel ammo.
![Barotrauma_b5KUy8zT7D](https://user-images.githubusercontent.com/10529134/174615360-e884524b-1fcd-4148-bf8c-5db2cd18a5a6.png)

2. Shredder Chaingun Ammo looks misleading, almost like it's Piercing ammo (but it doesn't pierce):
![Barotrauma_XMJIlZ5po8](https://user-images.githubusercontent.com/10529134/174612788-71d8246e-25c0-44af-b055-5d7a2050d638.png) ![Barotrauma_WxA57x0m4S](https://user-images.githubusercontent.com/10529134/174612794-82a3671a-6ec0-4140-b5ac-a646ae1a879e.png)
And it could be confused with Physicorium ammo:
![Barotrauma_XMJIlZ5po8](https://user-images.githubusercontent.com/10529134/174612788-71d8246e-25c0-44af-b055-5d7a2050d638.png) ![Barotrauma_kv1PxzVBq7](https://user-images.githubusercontent.com/10529134/174615863-234acd95-d551-4fb5-8954-00166b08d463.png)

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by deltanedas** [comment]
![funny](https://user-images.githubusercontent.com/39013340/178225546-183f3cee-c1d4-4ec2-8262-58cc63717394.png)

also related, physicorium ammo box has a smaller sprite on shelves

**Comment by deltanedas** [comment]
also whats funny is that every ammo box besides physicorium is grimy, but physicorium is nice and clean

**Comment by Rokvach** [comment]
Physicorium ammo box seems to be different from the rest, it doesn't fit into the correct grid and when you select it the selection outline is larger than the other ammo boxes 

So when you place it down its placed lower than the other ammo boxes and needs to be moved with arrow keys to match
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/14282059-8e9c-4fd4-8367-6ffc6172cb3b)

Here's the difference in the selection rectangle
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/97e83240-e122-4bd5-9314-4fb54ea153b7)![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/aac1f57b-39db-4b13-9ffe-98830b3d97f3
)

**Comment by IiroEnges** [comment]
I'll take care of this

**Comment by Rokvach** [comment]
The above commented issue about the Physicorium ammo box hasn't yet been adressed, moving to Team1

**Comment by IiroEnges** [comment]
I readjusted the physicorium coilgun ammo box source rect, pushed to dev

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
