### ISSUE TITLE
Channel presets not kept during loading screens

### ISSUE THREAD

**Issue by Majkl-J** [Regalis11/Barotrauma#9430]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Every time the game loads a mission or outpost in the campaign, the radio channel presets reset to default.

### Reproduction steps

1. Start a campaign
2. Save a custom radio channel number
3. Go through a loading screen
4. Notice how it didn't save

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/953545640a2e90160094841d186a667f6ea0fb3f

**Comment by ekqvist** [comment]
Saving channels to memory keeps them there even after loading to a new level. Fix seems to be working correctly. Closing the issue.
