### ISSUE TITLE
Depleted Fuel looks exactly like Thorium Fuel Rod

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9431]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?
What happened is that I found a problem _where no man has found a problem before_.

Because depleted fuel revolver rounds and smg mags are darker than their normal counterparts:
![Barotrauma_BbDXkdM9mv](https://user-images.githubusercontent.com/10529134/174618528-df182b1e-f521-4e04-adc1-2b8b74c544f0.png)
![Barotrauma_nCKBqiq4dp](https://user-images.githubusercontent.com/10529134/174618540-9c6366ef-0bb9-4ec1-bf78-67e94135d155.png)

This doesn't seem intentional
![Barotrauma_p5yXDX0kni](https://user-images.githubusercontent.com/10529134/174618407-79230a5e-e122-4f35-ad21-df1e6b507aa5.png) ![Barotrauma_4J3MYAyR2O](https://user-images.githubusercontent.com/10529134/174618225-b91b2b49-20eb-4722-b1b2-e3a7635f228f.png)

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/67f58b2886b20e0b6fac5ea842695b273c03d9ef

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.13.0, works correctly, closing.
