### ISSUE TITLE
Item assembly - Description not displayed

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9434]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After creating the assembly of items and filling in the section "Description" on the tab "Assembling items" the description is the same as the name of the assembly of items.

### Reproduction steps

1. Video: step by step
https://user-images.githubusercontent.com/93348499/174646644-bd266bcb-4c31-4cd3-a5b9-bbae9d94891f.mp4

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug. The purple text is not a description, it tells which content package that item assembly is from.

**Comment by MaaiG** [comment]
I could have sworn... I’ve seen a description there before or somewhere else...🤔
And why fill out a section of the description if it is not visible in the game?
Now, purple text always repeat the name of the item assembly...
