### ISSUE TITLE
Can't harm opposite team with spineling spikes in PvP

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#9437]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title say.

### Reproduction steps

1. Host Server
2. Start PVP
3. Spawn Spineling Genes and apply it to self.
4. Press F to attck the opposite team's humans by launching the spikes.
5. They don't suffer any damage.

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.15.0 unstable, doesn't seem to work correctly.

I'm unable to cause any damage on both enemy team (in PvP) humans and NPC's.

A quick debug reveals the following:

![image](https://user-images.githubusercontent.com/29177976/178879598-d9ee752e-fd66-49e6-aeef-81f367fedbcb.png)

It appears a second friendly check occurs at handling the projectile collision, which the fix does not address (Cancelling the attack)

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, working fine, closing.

Notes: Both friendly fire on and off, spineling attacks (and other projectile types like spears and hitscan bullets) can hit the opposite team fine.

Also tested against bots on a different team and that seemed ok too.
