### ISSUE TITLE
Docking port - no signal from connection point the proximity_sensor

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9438]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

`Docking port` - no signal from connection point the `proximity_sensor` at the beginning of the round if the shuttle is docked!
![Image 001_13-26](https://user-images.githubusercontent.com/93348499/174784910-7f065393-2796-46ca-878b-ccf3933935f4.png)

### Reproduction steps

1. Editor
2. Shuttle must be link with `docking port`
3. Start test
4. Signal from `proximity_sensor` will appear only after redocking the shuttle!

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is not a bug. The proximity sensor doesn't output anything when the port is docked - if you want to check that, use the "state_out" output.

**Comment by MaaiG** [comment]
> This is not a bug. The proximity sensor doesn't output anything when the port is docked - if you want to check that, use the "state_out" output.

But now `proximity_sensor` sends a signal when docked!

https://user-images.githubusercontent.com/93348499/174787141-d6463146-b679-4fc2-9c8b-5fc8b00beb6d.mp4

**Comment by Regalis11** [comment]
That's not actually what's happening there: it set the text to "1" when undocked, and when you dock again, it no longer sends anything (so nothing sets the text back to "0" or anything else).

**Comment by MaaiG** [comment]
> and when you dock again, it no longer sends anything (so nothing sets the text back to "0" or anything else).

I’m sorry, I may have misunderstood. How does a zero appear on the `Text Display`? 😳
When the shuttle is undock - signal 1
When the shuttle  has sailed far away, - 0 appears!
When shuttle gets close, it’ll be siglal 1
If it’s gone again, it’ll be 0!
![Image 001_19-42](https://user-images.githubusercontent.com/93348499/174854976-e7139425-6aec-429d-ab33-e55a8eb7ab8e.png)

On this principle I made the color change of the connecting lights!
Red - shuttle out of range
Yellow - the shuttle in the docking area (can be docked)
Green - the shuttle is docked.

I mean the following:
1. If the shuttle is **not docked at the beginning of the round**, the signal from connection point `proximity_sensor` on the `Text Display` will be `0`!
2. If the shuttle is **docked at the beginning of the round**, the signal from connection point `proximity_sensor` on the `Text Display` will be `nothing`! - **I thought it was a mistake!**
