### ISSUE TITLE
[XML] Depleted fuel revolver rounds cause no severance

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9439]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While all other ammunition, even DF ammunition causes some severance chance, DF RR don't cause any.

```
      <Attack structuredamage="10" targetforce="10" itemdamage="15" penetration="0.25">
        <Affliction identifier="bleeding" strength="10" />
        <Affliction identifier="gunshotwound" strength="35" />
        <Affliction identifier="stun" strength="0.4" />
```

### Version

0.18.12.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/1b10621eb2a1a99dfdcc1993d3928e8ee323339d

**Comment by Rokvach** [comment]
Teste, working correctly, closing.
