### ISSUE TITLE
X-Ray Screen - something’s wrong with backlightscreen

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9441]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After restarting the `X-ray screen` backlightscreen it's too bright.

### Reproduction steps

Step by step
https://user-images.githubusercontent.com/93348499/174895365-a948c7b2-bd8d-4dff-8d39-0970d533f6c8.mp4

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This seemed to also affect all instances of this item in the vanilla game (e.g. in MedicalModule_01 and MedicalModule_02). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/48b36340ef385697bf32afa44e96c7f12abd130a

**Comment by MaaiG** [comment]
> This seemed to also affect all instances of this item in the vanilla game (e.g. in MedicalModule_01 and MedicalModule_02). 

Does that apply, too?
All `Neon Lighting` v0.18.12.0
https://user-images.githubusercontent.com/93348499/175126151-f7acdabc-417e-47cf-87fb-948c958d0dd4.mp4

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.13.0, More investigation is needed into this issue.

![image](https://user-images.githubusercontent.com/29177976/176935500-e6b37f7d-7569-4012-856d-3e8cb5f4adea.png)

As you can see, the top objects I spawned in, saved with the same method as above and re-loaded in the submarine editor, then compared to those not saved in the sub editor and found various differences in components that appear to exit light components with a range of 0 (And this is probably not all of them across the game). This does not effect decorative objects with light components that have a small light range IE. lightbox's and advertisement signs.

The differences can vary from extremely minute colour changes to extreme changes in gradient. and one or two do not even appear almost when there is no light source.

![image](https://user-images.githubusercontent.com/29177976/176935896-4bbd9a1d-3932-44ad-9baf-bc52b72335c2.png)

The items that had changes appear to work just fine and are fixed. from these closer images you can see more of the subtle changes such as the research tanks, vending machines and Maybe just barely the slight colour differential in hologram signs.

![image](https://user-images.githubusercontent.com/29177976/176936225-32689308-fa00-4162-b372-5b01d5d774d8.png)

(Flicker removed to standardise the colours as its just that subtle, as if a tiny amount of cyan injected into the blue)
![image](https://user-images.githubusercontent.com/29177976/176936440-12b73466-297f-42fc-99c0-ae416839543b.png)

Im very curious to how its different in the sub editor initially, implies the sub editor handles lighting differently until its loaded - or saves something then loads something very different than it initially is.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/2701ddef99aaa10dc44869196e7e1e285e9be855

> Happened because the brightness of the lights was set in OnMapLoaded, which didn't get called in the editor. As a result the "fully opaque" light sprite wouldn't show up until you started a round.

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/36e3a2755f5fc201a748a32b63cc93a8eb30d90a, works correctly, closing.

Note: the light of the heater changed but that is an intentional change (It is a dimmer gentler glow)
