### ISSUE TITLE
The gap between vertical hulls works (for water) only after linking

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9449]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The gap between vertical hulls not work for water:
 **_I replaced the video with a new one without distraction factors!_**

https://user-images.githubusercontent.com/93348499/175516859-75c38401-f975-49ee-be7a-8b0b9e64ff71.mp4

After **link**ing everything works!

Horizontal hulls does not require **link**ing:

https://user-images.githubusercontent.com/93348499/175122625-8c9ecd51-e09f-418d-80f7-9f7d2dcec64d.mp4

### Reproduction steps

Watch the first video or:
1. Two vertical hulls and a `Gap` between them
2. Lower hull is quickly filled with water
3. Water does not enter the upper hull!
4. If you add `link` for both hull all will works fine.
So, Install `Gap` only - is not enough! Vertical design requires `Gap` and `Link`!!!

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
The gaps are setup incorrectly here: the vertical gap overlaps with 3 hulls: the top one, and the 2 hulls at the bottom. The hull will only get connected to two hulls though, and whether it happens to connect to the bottom-left or bottom-right one affects how water will flow between them. You need 3 gaps here, one on each hull boundary, to make this setup work correctly.

**Comment by MaaiG** [comment]
> The gaps are setup incorrectly here: the vertical gap overlaps with 3 hulls: the top one, and the 2 hulls at the bottom. The hull will only get connected to two hulls though, and whether it happens to connect to the bottom-left or bottom-right one affects how water will flow between them. You need 3 gaps here, one on each hull boundary, to make this setup work correctly.

Dear **Regalis11** I think you misunderstood me!
I know! The left case does not matter! It is the remnants of the removal of horizontal work!
Forget about it :) Here’s a new video:

Water doesn’t flow from the bottom up if the hulls aren’t linked! 
Install `Gap` - is **not enough!**
Vertical design requires **`Gap` and `Link`!!!**

https://user-images.githubusercontent.com/93348499/175318496-429bda89-4539-4f87-8923-7044ea09ef27.mp4

**Comment by Regalis11** [comment]
I unfortunately could not reproduce this. How are you controlling the pump, via `set_targetlevel`?

**Comment by MaaiG** [comment]
> How are you controlling the pump, via `set_targetlevel`?

Yes! Navigation Terminal `velocity_y_out` >>> Pump `set_targetlevel`
Ver 0.18.12.0
Sub file: [__Test-Hull-V.zip](https://github.com/Regalis11/Barotrauma/files/8993295/__Test-Hull-V.zip)

**Comment by Regalis11** [comment]
In that case I think it's working as intended. `set_targetlevel` determines the level at which you want the water to be in that room: if the hulls are not linked, only the lower hull is considered to be "that room", so setting the target level to 100 will only fill the lower hull.

**Comment by MaaiG** [comment]
You’re right! I didn’t think of that! I’m sorry )).
The problem doesn’t exist!
Thank you for explaining! Sorry for wasting your time!
