### ISSUE TITLE
Can i will buy  press relise or join beta this game  when it go steam beta?

### ISSUE THREAD

**Issue by Chaos456456** [Regalis11/Barotrauma#945]

**Comment by yaelatletl** [comment]
I'm no dev, but this game's already on alpha, you can go get it in gamejolt and it's oficial web site. 
Later, you may get the game buying it on steam ;)

**Comment by Regalis11** [comment]
We will have a short closed beta testing period before the Steam release, there's a chance you'll get to try the Steam version then. :) We haven't yet decided how exactly we'll choose the beta testers, but modders, collaborators, and other active members of the community will most likely be given Steam keys, and there'll probably be some sort of open "apply as a beta tester" form for others.
