### ISSUE TITLE
FPS drop when changing character appearance

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9454]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Moving the character appearance sliders can sometimes cause a noticeable FPS drop (a brief freeze on every slider step). Seems to happen because reloading the attachment/face sprites removes and reloads the texture if another sprite is not using that same texture.

### Reproduction steps

1. Go to the SP character customization menu
2. Make the 1st and 2nd characters female to ensure there's no other male textures loaded
3. Make the 3rd character male and move the beard slider

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/93a404dd4d69d039af2a9286deec913b45f56397

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.13.0, works correctly, closing.

Notes: Tested from a fresh copy where the new game character customization choices had two female and one male (Without even switching the genders) and still found I was unable to drop a single frame dragging the options quickly on the male hairstyles and such. Additionally tried against my slowest hard drive and also was buttery smooth fine.
