### ISSUE TITLE
при ожидании  челнока выкинуло, возможно при стыковке

### ISSUE THREAD

**Issue by Baroromka** [Regalis11/Barotrauma#9459]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

вылетел с сервера при стыковке корабля или просто при ожидании челнока
![Barotrauma Screenshot 2022 06 24 - 18 06 55 51](https://user-images.githubusercontent.com/108141701/175565491-f7c96dc6-f085-4a19-9722-384d71e89782.png)
простите первый раз тут не умею пользоваться сайтом, не читал другие статьи, просто решил сообщить о факте вылета.
Игра ванильная, без модов, карма, огонь по своим

### Bug prevalence

Just once

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6265
