### ISSUE TITLE
missing door buttons or sprite depth bug

### ISSUE THREAD

**Issue by Randy624** [Regalis11/Barotrauma#9462]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

missing door buttons or sprite depth bug

### Reproduction steps

Easy in reproduction
Door has default sprite depth - 510.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response

https://user-images.githubusercontent.com/108170820/175769761-ea894e75-28a9-4784-9f69-e983a6232356.mov

_

**Comment by MaaiG** [comment]
I thing sprite depth bug.
The depth scale of left background wall does not match the depth scale of right background wall!
Something [like that!](https://github.com/Regalis11/Barotrauma/issues/8061#issuecomment-1016785895)

P.S. You can add the video just by dragging it into the message body (maximum 10 mb). И не нужен никакой яндекс.

**Comment by Randy624** [comment]
I do not understand the logic of button behavior in this at all. And why is it different from the rest of the door.

**Comment by Randy624** [comment]
https://user-images.githubusercontent.com/108170820/175769619-35b8ba70-a0f9-43f7-bf5e-7816ee8460de.mov

**Comment by MaaiG** [comment]
> I do not understand the logic of button behavior in this at all. And why is it different from the rest of the door.

В смысле? Дверь конструкция составная. Рама с кнопками и собственно дверь это два элемента. Они расположены на разных уровнях шкалы глубины.
![111](https://user-images.githubusercontent.com/93348499/175777732-3c428400-0ddd-4b28-8177-bc61109fb952.gif)
В вашем примере - с дверью все в порядке. 
Проблема в том, что фоновая стена слева и фоновая стена справа имеют одинаковые настройки глубины, но левая оказывается выше чем правая. То есть уровень глубины 890 для левой не равен уровню глубины 890 для правой.
Видимо у них две разных [точки отсчета глубины или разные шкалы глубины](https://github.com/Regalis11/Barotrauma/issues/8061#issuecomment-1016785895).
Левая фоновая стена была добавлена недавно в новом наборе фоновых стен! Очевидно, что эта проблема со всеми стенами нового набора по сравнению со старыми стенами.
Если взять фоновую стену из того же нового набора, что и левая, то проблемы между ними не будет.

https://user-images.githubusercontent.com/93348499/175778323-ff7ffb8d-7e7e-4bf7-ab5f-6e1806f7a57f.mp4

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/82e7e2c87e8b6e37cc013836b54b4cf107f9c790 by separating the buttons from the door's background sprite, so the buttons can have a lower sprite depth than the background.

**Comment by NilanthAnimosus** [comment]
Tested in 0.18.13.0, works correctly, closing.

Notes: could not find any outpost module/vanilla submarine that appeared to use values that may cause any issues. Moving walls around shows the button hides at the intended depth of 0.75 offset by the door depth (IE. +0.01 to door depth is +0.01 to button depth).
