### ISSUE TITLE
"Good quality" items start at very low skill requirements

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9467]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You get "Good quality" items as soon as you unlock the skill requirement craft them

As low as 20 skill is enough to get good quality:
![image](https://user-images.githubusercontent.com/73229309/175832523-6860f896-503f-4ed2-bf84-1f2b63d155b9.png)
Excellent quality requires 100 skill

Increase the requirements for good quality to a halfway point or at least 50?

### Version

0.18.12.0

**Comment by ubertpendragon** [comment]
`ed6cb18618: Changed the quality calculations for fabricated item: the character's skills need to be x2 the skill requirement of the fabricated item, instead of equal to or higher, to create a good quality item (Regalis11/Barotrauma#9467)`

Some items have requirements 50 and above so you can't get them to "Good" before Excellent (or even capping skills?)

Here's a short list:
-Frag grenade
-EMP grenade
-C4
-IC4
-Compound N
-Volatile Compound N
-Fulgurium rod
-Volatile Fulgurium rod
-Assault Rifle
-Autoshotgun
-Handcannon
-Rapid Fissile Accelerator

**Comment by Krzeszny** [comment]
To prevent future bugs, please make sure that modded items which would need 100 of a given skill to be Good, will be Excellent instead (or Masterwork.) 

(On a personal note, +20 skill is a somewhat high requirement for +10%, especially for items that already need 70+ skill to fabricate.)

**Comment by Tsunder** [comment]
What about linear interpolation / lerp from crafting requirement to 100? ^_^

**Comment by Regalis11** [comment]
Good points. I decided to change this once more: now the limit is 20% from the minimum skill requirement towards 100 (or in other words, `skillRequirement = MathHelper.Lerp(skill.Level, MaxCraftingSkill, 0.2f)`).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
