### ISSUE TITLE
Scaling the background wall (without changing its actual size) increased the borders of the added shuttle unexpectedly

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9472]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you increase the scale of the background wall the size of the borders of such a shuttle (submarine) will be increased unexpectedly.

### Reproduction steps

https://user-images.githubusercontent.com/93348499/175955169-c59e2d17-be27-4ef9-a778-2d520d7a406b.mp4

[_____111.zip](https://github.com/Regalis11/Barotrauma/files/8992483/_____111.zip)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.13.0, works correctly. closing.
