### ISSUE TITLE
`RangedWeapon` reload always skips up to 2 frames, causing 33% slower Chaingun rate of fire (and up to 70% RoF/RPM reduction in extreme cases)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9474]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**Disclaimer:** I've edited this report based on Regalis's comments and new testing ideas. Previously it was tested with a stopwatch and the results had 1 mistake (chaingun was 33% slower instead of 11% slower) and 1 typo (0.25 coilgun reload instead of 0.15)**

In the editor, I recorded videos in 60 fps showing how many frames it takes between shots of the default Coilgun, default Chaingun, Pulse Laser, Chaingun modified to 1 shot per second and 60 shots per second. Using the theoretical reloads (0.25, 0.1, modded 1 and modded 0.01667) and knowing that the game engine runs at 60 Hz, I calculated their actual reloads.

- The **Coilgun** skips 2 frames per reload, resulting in 13% slower firing than expected
- The **Chaingun** skips 2 frames per reload, resulting in **33%** slower firing than expected
- The **Laser** skips 2 frames per second, resulting in 2.6% slower firing than expected
- Chaingun mod. 60 skips 2 frames per shot when firing at 60 RPM, resulting in 3.3% slower firing than expected
- Chaingun mod. 3600 skips **1** frame per shot when firing at 3600 RPM, resulting in 100% slower firing than expected (theoretical maximum = 1800 RPM)

It has been like that at least since update 0.14.6.

![brave_ldezrQoa6w](https://user-images.githubusercontent.com/10529134/176167169-700cead6-10b2-417a-9286-6000d78b118c.png)

I've created a formula used to calculate the RoF. It works between a 0.01 second reload and infinity:
EU:
`=60/(1/60*IF(Reload=0,05;4;FLOOR(Reload/(1/60);1)+2))`
US:
`=60/(1/60*IF(Reload=0.05,4,FLOOR(Reload/(1/60),1)+2))`

### Reproduction steps

1. Load the Orca 2
2. Set its supercapacitors to 100%
3. Record firing a few shots at 60 fps
6. Calculate frames per shot in a video editing software
7. Compare the actual value with the expected value

### Bug prevalence

Happens every time I play

### Version

Oldest: 0.14.6 or older (Coilgun and small arms only, before the submarine gun update)
Newest: 0.18.12

### Which operating system did you encounter this bug on?

Windows

### Additional info

The highest possible RPM is currently 1800 (instead of 3600 or 6000 as expected from reload times), which is  1 shot per 2 frames.

**Comment by Krzeszny** [comment]
I was playing at 100 fps.

Anyway, it's fine if it's balanced, although it causes confusion when trying to calculate rounds per minute.

**Comment by Regalis11** [comment]
Yeah, by frames I mean the updates (physics, item/entity updates and such) which run at a fixed 60 Hz.

**Comment by Krzeszny** [comment]
Ok, this issue can be:
a) closed as "won't fix", or rather "can't fix"
b) be left open indefinitely for informational purposes (in case someone else notices the chaingun doesn't fire 10 shots per second) or until tick rate gets increased in the far future (probably not)
