### ISSUE TITLE
[Unstable] Tri-Laser and Piercing coilgun ammo recycle recipes are more expensive than non-recycle

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9485]
### What happened?

 Tri-Laser and Piercing coilgun ammo recycle recipes are more expensive than non-recycle
 
 
![image](https://user-images.githubusercontent.com/73229309/176451053-c00fcf67-9ee8-4fa9-ad44-0c1bea9ca839.png)

![image](https://user-images.githubusercontent.com/73229309/176451071-97eb2dfa-554c-4822-83c5-681b054633b3.png)

![image](https://user-images.githubusercontent.com/73229309/176451095-2c999890-7e5c-4987-b348-87370ef62630.png)

![image](https://user-images.githubusercontent.com/73229309/176451120-792ec8d4-531d-473e-b76f-f5ab432e6a1a.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/27fa72f3d2941b5faec8f319508503fd4bb67097

**Comment by NilanthAnimosus** [comment]
I believe this is a duplicate of issue #9432 which I've already confirmed is working fine and for other ammo types in version 0.18.13.0 (Currently the unstable branch, not stable release).
