### ISSUE TITLE
[Dev version] ruins blocking the main way of the submarine

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#949]
A rock formation on the bottom and ruins at the top, no way for the main sub to get past that.

![ruins blocking sub s main path](https://user-images.githubusercontent.com/38168249/49197259-d6ee1e00-f3c0-11e8-82a3-7c76d7d7955b.jpg)

Map seed: 9VXnwQbU
Save file: [save.zip](https://github.com/Regalis11/Barotrauma/files/2627474/save.zip)
On the campaign map in the save it's the path from Chandelle Crevasse City to Serac.

---

You seem to be currently working on the ruins, so the issue is just something that should probably be kept in mind during the work.

**Comment by Regalis11** [comment]
I believe this has been fixed now.
