### ISSUE TITLE
Stutter when mobs spawn

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#9491]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Each time mobs spawn connected clients notice short mild- to medium stutters. Its seems the stutters are more intense the more entities are spawned.

We usually run the game dedicated on a Ryzen 3600 (4-6 clients, pretty untaxed even by heavy gameplay) and monitoring the server and network doesnt seem to show the stutters performance-wise. Yet each client notices them, so "Had stutters, mobs spawned" became a common call in our MP campaigns.

We watch this issue for many many months and its also discussed in the community. I filed be bug report, because I havent found this reported!?

It would be great if the mob spawn system could be overhauled to work more smoothly. Once because stutters=bad but also because it also gives away most mob spawns, which spoils the surprises.

Only mod used: New Wrecks For Barotrauma
https://steamcommunity.com/sharedfiles/filedetails/?id=2184257427

### Reproduction steps

1. Run client host or dedicated
2. mobs spawn accompanied by a short ripple of stutters noticeable by connected clients

### Bug prevalence

Happens every time I play

### Version

Other

### -

many versions up to .18.13 (last tested)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3478/commits/65a9dec225bde460cbbd6388d4ae8b13b23105b1

**Comment by Regalis11** [comment]
Note for testing: as @juanjp600 pointed out in https://github.com/Regalis11/Barotrauma-development/pull/3478, there's a todo note about testing Jovian Radiation's effect on monster events in multiplayer in MonsterEvent.cs. Even though not strictly related to this ticket, let's give that a test as well (= checking that Jovian Radiation kills monsters in MP).

**Comment by Rokvach** [comment]
Singleplayer works fine, I did notice a micro stutter in the second to last level in campaign but its mostly just a skipped frame when the first creatures on the level gets enabled. Its also easy to miss if you blink or aren't paying that close of a attention but it does show up in showperf as a spike in update. 

Multiplayer doesn't seem to be working, tested by selecting a monster mission game mode and setting difficulty to 100%, the round just booted me back to the lobby once it finished loading and the console was spammed with a lot of errors

All the errors as there's too many to post here
[monster.txt](https://github.com/Regalis11/Barotrauma/files/9353425/monster.txt)

**Comment by Rokvach** [comment]
Moved to review

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1130cd8270e5d97b66ea79a888ceb51609498ec8

**Comment by Rokvach** [comment]
When a round starts all bots in your crew just starts to running around like crazy, its like everything is just fast forwarded

**Comment by Regalis11** [comment]
Happens because the client freezes for a bit at the beginning of the round when loading the monsters, after which it appears to "fast-forward" to catch up with the server. Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c10462f4763de3a9289e9698e948aad8c9d0ef4c

**Comment by Rokvach** [comment]
I did notice some client freezing still when loading up a single mission game mode, but it doesn't last as long as before, the issue also doesn't seem to happen in campaign (unless it requires there to be a certain amount of creatures in the level before it becomes noticeable)

I also tested radiation and it works as it should

I think we can merge this
