### ISSUE TITLE
Route issues when start- and target outpost have the same name

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#9492]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

We had a route where the target and starting station had the same name (Level seed="Phocis FlexusPhocis Flexus" biome="hydrothermalwastes" type="LocationConnection", attached save file Line 22712)

1. The distance meter went bonkers. Both locations showed the same distance while the number became greater the furthe we went to the target station. Only when we got very close to the target station (<200m?) the target location number adjusted (as seen in the attached screenshot)
2. The random name generator is too small and creates way too many duplicates on a campaign map

Expected behaviour: 
a) Distances shown properly
b) random name generator not generating duplicates, or at least preventing routes having duplicate station names (immersion breaking)

### Reproduction steps

Save file: [Marburg0.17_Mai22.zip](https://github.com/Regalis11/Barotrauma/files/9017796/Marburg0.17_Mai22.zip)

Screenshot:
![20220629224302_1](https://user-images.githubusercontent.com/3466193/176629080-978f1791-1df2-45f0-bcc1-d1624924466b.jpg)

### Bug prevalence

Happens every time I play

### Version

Other

### -

tested in 0.18.3, map Gen was ~0.17.x

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/374c52cd8601d504d7307726676198ff35201b32, https://github.com/Regalis11/Barotrauma-development/commit/ec6a3e91e323f572ffc353144c6ae844349a3161 and https://github.com/Regalis11/Barotrauma-development/commit/afe8ffc60d714fda44e754240c30191116382465

**Comment by NilanthAnimosus** [comment]
Tested against 0.18.15.0 unstable, works correctly - closing.

Notes: Unable to find any issues with navigation, sonar, autopilot or the labels/distances/positions on the console of locations when forcing same names. campaign appeared to work fine too with every location having the same names.
