### ISSUE TITLE
Crawler in a crate event triggers between destinations with no outposts/settlements

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9494]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is maybe not strictly a bug and more I feel an event not making sense in a situation so not sure its intended this way.

I was jumping from campaign destination to campaign destination, and found a cargo box spawned with a yellow (!) marker, checking it out it was a scripted event...But I had gone from a location with no outpost to another location with no outpost in the great sea's with nothing to dock to, so a sealed container appearing feels sort of unusual unless barotrauma has deep-sea ninjas nobody would pick up on sonar depositing boxes.

Feel this may be more a mechanics thing on events not knowing where you traveled from (for relevance sake) or just a specific event doesn't have this set correctly (such as triggering if leaving an outpost)

### Reproduction steps

Not sure this can be reproduced easily as I am not sure if random outpost/starting events are tied down to level seeds / saves and would trigger the same event if a save file was used. I have kept the save file if its reproducible via save in case that is needed.

### Bug prevalence

Just once

### Version

Other

### -

0.18.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe.
