### ISSUE TITLE
Drones disconnects when starting a campaign, not in editor.

### ISSUE THREAD

**Issue by Ragamuff** [Regalis11/Barotrauma#9495]
[MAKO II.zip](https://github.com/Regalis11/Barotrauma/files/9023064/MAKO.II.zip)
Submarine works fine in editor, but disconnects its drones in campaign. Thought it could be useful to send it up, as its reproducible.
Hope it helps.

**Comment by Regalis11** [comment]
Thank you for the report! I gave this a test, but the drones seemed to worked normally. The only way I got them to disconnect was to purchase and switch to this submarine, which is [a known issue we've got another ticket about](https://github.com/Regalis11/Barotrauma/issues/9380) (and a fix coming up soon!).

**Comment by Regalis11** [comment]
No known steps to repro, closing
