### ISSUE TITLE
Local mod submarines can appear twice in campaign submarine purchase menu

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9499]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Created a new campaign and found a localmod had its one submarine in the buy submarine menu twice.

![image](https://user-images.githubusercontent.com/29177976/176861437-899ea1a1-4085-45d8-a7de-bc4de4e77612.png)

### Reproduction steps

I created a localmod to test a campaign with a custom shuttle-sized mainsub. I left it in there and curiously noticed it appear twice in a new single player campaign in the menu to buy submarines.

Seems potentially possible to occur when creating a submarine and saving it as a local mod, then proceeding to disable and enable that local mod before starting a single player campaign caused my save to duplicate localmod submarines.

### Bug prevalence

Happens every now and then

### Version

Other

### -

0.18.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to reproduce this. Tested the following:

1. Save a copy of Azimuth as a local mod (with the name "Azimuth edited")
2. Start a new campaign
3. The sub only shows up once in the menu

And a second attempt by doing the following
1. Disable "Azimuth edited"
2. Re-enable "Azimuth edited"
3. Start a new campaign
3. The sub only shows up once in the menu

**Comment by Regalis11** [comment]
No known steps to repro, closing
