### ISSUE TITLE
Questions regarding making reports and requests related to the dev version

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#950]
There have been [news regarding archive.database.red stopping uploading dev versions](https://database.gitbook.io/project/transparency-report-barotrauma-archives), which are completely understandable.

 What was interesting for me is the sentence in one of your messages saying that the amount of reports and requests regarding unfinished features you are currently working on is starting to be irritating.

 I assume it is my fault for the most or at least a pretty big part, judging by the amount of recent dev-related issues i made. So i just wanted to know if i should stop creating or reduce the amount of issues i create regarding the dev version? Or are there any specific conditions in which i should not create an issue? 
 For example, is [this recent issue](https://github.com/Regalis11/Barotrauma/issues/949) acceptable? Bug reports of this kind are probably not completely necessary, since you would notice those kinds of bugs yourself at some point. But you seem to be currently working on the ruins, so i assumed it would be better for you to know about the problems that appear while you are working on them, and not find out about them some time later when you are doing something else. However, that's just an assumption, i don't actually know if what i am doing is helpful or a waste of time for you and waste of space in the repository. You may already know about the problem and just have plans to deal with it later, in which case my issue becomes almost completely pointless.
 All my actions, related to the game and its development, are only made with good intentions in mind. But i may not notice if i am crossing the line of acceptable actions and doing something harmful.

 I hope it's not too rude of me to point out sentences in messages between other people. And the one i pointed out might not even be as big of a problem as it seems to me. But i genuinely wondered if i was doing too much even before the news, but was not sure how to ask about it properly; so this just might be the good time for me to ask about it.

**Comment by Regalis11** [comment]
That was supposed to be a half-joking statement - even though I admit it's sometimes annoying to have people point out problems in something you're currently working on and that you're already aware of, it's still a good thing that players report those things. There's often no way for you to know if it's something we've overlooked, and even if it isn't, having an issue report about it on GitHub will at least be a good reminder that makes sure we don't forget about it. 

In general your bug reports are usually the most informative and useful ones on the issue tracker, and I wish more of the reports here would be as detailed as yours. So please do keep reporting bugs you spot if you want to keep helping us improve the game. :)
