### ISSUE TITLE
Recruited bandit during abandoned outpost event refused to leave station

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9500]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Station AI on your side (Such as converted bandits becoming one of your crew) appear to not want to enter the submarine under any circumstances via pathfinding, even to find a safer location. this could be an orders-related issue (Of recruiting a bandit as he did cancel orders a lot such as follow) or a pathfinding related issue.

I had entered an abandoned outpost in the high-difficulty last region in campaign and it was full of bandits. an event triggered where one bandit claims to be a chemist/drug maker, throws down their weapon and states they don't want to be a bandit anymore.

I chose the options to recruit them and proceeded to murder all the bandits - they survived just fine. The goal of the abandoned outpost was to destroy its reactor, The new bandit crewman refused to follow me into the submarine, and even when I blew the reactor he would not go down - opting for barotrauma instead and dying swimming into the flooded sections and outside the hull.

Reviving him and teleporting and such, He was as determined as possible to die in that outpost or the ocean, it took teleporting him inside and reviving him to get him to sort of "Stay" - but he did not appear the next mission even with that, he really was dedicated to that station.

### Reproduction steps

Not sure how to force this specific event or which event it is.

Unfortunately I do not have a save file for this.

### Bug prevalence

Just once

### Version

Other

### -

0.18.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Note for testing: this can be triggered with the command `triggerevent heartofgold`

**Comment by Regalis11** [comment]
I wasn't able to repro this:
https://user-images.githubusercontent.com/14351070/176879667-485f52fd-3e19-461f-8077-39ce175c4682.mp4

**Comment by deltanedas** [comment]
i can reproduce this on orca 2 with bots on a large colony, i tell them to follow me (in engineering) and they immediately cancel it

**Comment by Regalis11** [comment]
No known steps to repro, closing
