### ISSUE TITLE
monsters spawning on sonar

### ISSUE THREAD

**Issue by deltanedas** [Regalis11/Barotrauma#9501]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

monsters can spawn inside of sonar range which looks janky

### Reproduction steps

1. use Meaningful Upgrades mod, might be important
2. max out sonar range
3. see fish spawning ~half of the sonar range away, very easy to spot

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
I'd say this is an issue with the mod itself: it increases the range of the sonar so much you can see the monsters spawning.

**Comment by deltanedas** [comment]
> I'd say this is an issue with the mod itself: it increases the range of the sonar so much you can see the monsters spawning.

good to know, i thought it was an upgrade that was in vanilla originally
