### ISSUE TITLE
Supercapacitor - charge slider does not follow settings! (same with `Battery`)

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9503]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/93348499/176884116-becd22c1-3060-4bdf-9f2e-c115973d5240.mp4

### Reproduction steps

1. Start Editor
2. Create `Supercapasitor` or `Battery`
3. Select `Supercapacitor` or `Battery`
4. Change charging speed in the device settings menu
5. RMB - Open
6. `Charge slider` does not follow settings!

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This doesn't seem to cause any actual issues (the slider is correct when the round starts), so I don't think this needs to be addressed.
