### ISSUE TITLE
Can't complete objective in the security officer tutorial

### ISSUE THREAD

**Issue by NONNOLUPO** [Regalis11/Barotrauma#9506]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

in training mode - security officer
after executing the objective, the mission was not unlocked

### Reproduction steps

1. I put on armor and helmet
2. I take stun baton 
3. The objective doesn't unlock
4. I'm sad

### Bug prevalence

Just once

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
no one
```

**Comment by Regalis11** [comment]
Thank you for the report! I'm afraid I could not find a way to reproduce this: the objective seems to complete with no issues. I wonder if there's any other factors that could be preventing it from working in your case, can you think of anything that you might be doing differently than in this clip?

https://user-images.githubusercontent.com/14351070/177034353-0ffac96c-48c4-4991-905f-602328052165.mp4

**Comment by Jade-Harleyy** [comment]
Not sure this is what they meant but if you drop the items on the floor as shown in [this video](https://www.youtube.com/watch?v=q-0N2NSWWBE), the game does not show new objectives, and the player has to press ESC to unfreeze the game.

**Comment by NilanthAnimosus** [comment]
![image](https://user-images.githubusercontent.com/29177976/177259695-177c4f13-a878-4d1c-a41f-2dd53e45c7b9.png)

Well, I have managed to reproduce this, I had to take the items before the message and objective appeared to get them, stood still a good 10-20 seconds and the objective still didn't complete despite i'm clearly wearing them even when I removed the bandage from my hand.

Unequipping and re-equipping the stun baton didn't trigger the objective clear.

then I took my chest armour off and put it back on, then my helmet off to the hotbar and put it back on...and it still didn't complete the objective.

Then I placed them all back into the cabinet, and took them all back out and used double clicks for the armour pieces and then equiped the stun baton and it still did not complete. at this point, I actually wondered what I had done to break it.

I can at least confirm this is doable - In my case I simply sprinted right out of the room as fast as i possibly could, equipped a bandage and the stun baton into my hands and grabbed/equipped the armour before I even got the objective to hit Ok to.

**Comment by Regalis11** [comment]
Thanks, I go it to happen as well now. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ba1dcbb2b131f489ee7a1bc6c1e828a3afc2b43

> Fixed Coroutines sometimes not pausing when they should (WaitForSeconds only considered the game to be paused when the pause menu is active). Caused security officer tutorial to potentiall get stuck (https://github.com/Regalis11/Barotrauma/issues/9506) - the problem was that we triggered a tutorial segment, started waiting for the equipment to be equipped, and if it was equipped, immediately tried to remove the current objective (which apparently isn't created until the player dismisses the prompt for the tutorial segment). Now that the "waiting" takes pausing into account, this no longer happens, because we can't continue until the prompt is dismissed and the game unpaused.

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0

there are new issues now, specifically doing the same thing as before:

Start security tutorial
immediately sprint out and open the locker before any objective/messages appear.
grab all items from the locker without closing it.
equip the armour, helmet and stun baton without closing it
Close the locker and attempt to proceed
Find the game now freezes instead of showing messages and objectives, you now must hit escape everytime it freezes to continue.

**Comment by Regalis11** [comment]
Couldn't repro :/

https://user-images.githubusercontent.com/14351070/180384178-82319a7f-fe1d-40f7-97dd-54674cdf4803.mp4

**Comment by NilanthAnimosus** [comment]
After at least 20 attempts, I'm unable to get the same behavior in 0.19.0.0, I think the core problem with this issue is resolved now, and I somehow experienced an edge-case that almost nobody is likely to get.
