### ISSUE TITLE
Incorrect light rotation on detaching/attaching certain items in single player

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9507]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Best description is when attaching an object to the wall - its preview rotation is the final rotation for its light components inside. for ranged lighting this isn't so noticeable, for 0 range lights its very noticeable like a ghost image of the entity.

Not sure if this occurs to any vanilla items you can sanely detach and attach, as most lights or other entities are not long or likely noticeable for this small issue. I was testing issue #9375 and found attaching the vending machine actually resulted in the light component being whatever rotation it was before it attaches - note this was in single player and not on a server.

![image](https://user-images.githubusercontent.com/29177976/176978376-e6088151-7cbb-41ab-a24b-8b170a8c24f6.png)

https://i.gyazo.com/b335c5719a9c2790c5bc3b33fe34fc93.mp4

### Reproduction steps

First start a single player game (This does not occur as a client in servers)

Easiest and most noticeable is to detach then attach any long rectangular entity that uses a 0 range light component to add a glow effect (One example is vending machines).

Not sure of any vanilla objects allowing for this but there may be one or two I'm unaware of, but I used the vending machine edits Regalis used in issue #9375 and spawned that in via spawnitem to inventory.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Ek-Videogames** [comment]
This bug also applies to visible contained-items in an attached-item's inventory.

**Comment by Regalis11** [comment]
The only way I was able to reproduce this was by disabling lighting before I attached the item - was that the case in your situation as well or did you get it to happen with the lighting enabled too? In any case, fixed the rotation when lighting is disabled in https://github.com/Regalis11/Barotrauma-development/commit/8f6ca0daa0ef7c70a3d1c17574c8fab48a5a0782

**Comment by NilanthAnimosus** [comment]
I likely did have lighting disabled, I've often been doing that in testing so that makes sense if you cannot reproduce it with lighting enabled.

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0 - Works correctly, closing.
