### ISSUE TITLE
Performance drop to 6 FPS

### ISSUE THREAD

**Issue by kytkueyrkkrukrykr** [Regalis11/Barotrauma#9508]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Когда в сервере появляется четвёртый игрок fps опускается до 6, хотя до этого мог стабильно держатся на 60. когда играешь на 100% сложности игра прям зависает. При этом видеокарта максимум, используется только 60%. Видеокарта Radeon RX 5500 XT.

### Reproduction steps

Нужна видеокарта от amd. Просто играешь и видешь как видекарта нагружена на 30% а у тебя пять fpc.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

Unfortunately no-one in the team speaks Russian, but I think I was able to get the gist of this with Google Translate. I'm afraid there's not enough information here to diagnose the issue: performance issues on AMD GPUs do not seem to be something that occurs consistently, and it doesn't seem like the GPU is the bottleneck here considering how low the usage was in your case. So I think there is something else going on here - it might give us more clues if you opened the debug console with F3, entered the command "showperf" which enables some extra performance statistics, and took a screenshot of what you see when the FPS drops.

Sorry for the inconvenience!
