### ISSUE TITLE
quality option for items in sub editor has no min/max

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9513]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

can press the up/down button for quality and it goes above 3 and below 0.

granted it gets reverted to 3/0 after unselecting/reselecting, but it shouldn't go > 3 / <0 in the first place.

### Reproduction steps

1. place a welding fuel tank in sub editor
2.  select fuel tank
3. press the upvote arrow on quality 4+ times

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b543127f34869a4162d8ec3ae0d41c974148fc9c

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, works correctly. closing.

Notes: Not possible to set it above 3 / below 0 in the UI, typed in or incremented/decremented. Additionally couldn't set by changing it to 5 and clicking off (not that it was originally an issue there).
