### ISSUE TITLE
mods are displayed on left align momentarily in publish sub menu

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9514]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

mods show up on left side of menu momentarily when scrolling publish mod tab

https://user-images.githubusercontent.com/5103517/177023661-e247f111-edee-47b6-b098-e31fda415791.mp4

### Reproduction steps

1. have over 1 screen length of local mods?
2. scroll down publish mod menu

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9386502f4b6a9187a5e7f4803acf0ce7554eacc8

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

notes: I had around 19-20 local mods in my publish list, on two separate restarts of the game I scrolled both slowly and as fast as I could and saw zero alignment issues.
