### ISSUE TITLE
bandolier gives bonus when held

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9516]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

bandolier  (and other items that give bonuses when worn) shouldn't give their bonuses when merely held in inventory?

related to #9413 referencing bandolier giving 2x bonus. 

this post is hearsay from discord people who don't report bugs on github.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a427409c75413b3ba132253233ef9db3ff1fe7f

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, works correctly, closing.
