### ISSUE TITLE
Cannot open Toxin Cabinet in the Barsuk as the Medical Doctor

### ISSUE THREAD

**Issue by Colsta** [Regalis11/Barotrauma#9517]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This happened in version v0.18.12.0, vanilla.

From the start of the campaign, as the Medical Doctor, I have had no access to the Toxin Cabinet even with my Medical ID equipped. The only way I can interact with it is with the Captain's ID.

I am not the host.
I have not tried to reproduce this on another campaign.

### Reproduction steps

1. Start multiplayer campaign
2. Be the medical doctor
3. Have the medical ID
4. Click the toxin cabinet
5. Unauthorised access

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d41a0e79a0a4b47c07f022774ce1454d1872ef93

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

Notes: Will not work if spawning human/medical doctor in the sub via cursor, need to use "inside" to properly apply the ID card tags to a spawned human, buying in outposts is fine or multiplayer spawning.
