### ISSUE TITLE
Terminal doesn't ignore empty messages in wiring ports

### ISSUE THREAD

**Issue by CaptainSqrBeard** [Regalis11/Barotrauma#9518]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you send "" into terminal "signal_in", it will send it anyways. If you use memory component for terminal, it will spam into it. I think it should ignore that message. If you need to send space into terminal, you still can use " " for it.

### Reproduction steps

1. Connect memory component with "" to terminal
2. Enjoy spamming

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7709d80e9917a09bdaec423c4f12239cde388901

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0 - Works correctly, closing.
