### ISSUE TITLE
Deleting containers doesn't delete their contents

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#952]
Occurs in both public and dev version.
Deleting a container just makes the contained items drop at the position of the container, which makes you have to do the deleting action twice or even 3 and more times, in cases of deleting containers that contain other containers.

Might also make you accidentally leave unwanted items in the sub if you don't pay enough attention while deleting stuff.

Video: https://streamable.com/frk13

**Comment by EetuFF** [comment]
Added in e8d7c56
