### ISSUE TITLE
event_error_log_server_cess183_1159 PM.log

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#9523]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Dedicated Server error.
[event_error_log_server_cess183_1159 PM.log](https://github.com/Regalis11/Barotrauma/files/9039337/event_error_log_server_cess183_1159.PM.log)

### Bug prevalence

Just once

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Duplicate of https://github.com/Regalis11/Barotrauma/issues/6265
