### ISSUE TITLE
Mission objective swarm swam out of map bounds

### ISSUE THREAD

**Issue by RaptorIM** [Regalis11/Barotrauma#9528]
**Disclaimers**

- [X]  I have searched the issue tracker to check if the issue has already been reported.

- [x]  My issue happened while using mods.

**What happened?**
While chasing crawler swarm, they swam beyond the map and further out to the point where currents bring the submarine to halt.

**Reproduction steps**
Slowly approaching swarm near the edge of map may make the swarm swim out of map bounds.

**Bug prevalence**
Happened only once so far.

**Version**
0.18.12.0

**Which operating system did you encounter this bug on?**
Windows 10

**Relevant error messages and crash reports**
None

**Comment by Regalis11** [comment]
We unfortunately still haven't been able to get this to occur at our end. :/ The monsters should always start heading back towards the level if they're about 300 meters outside the the bounds, which is much sooner than the currents become strong enough to stop the submarine.

A couple of details that might help us diagnose this:
- Did you actually see the swarm? I wonder if the problem could be that the marker is shown incorrectly, or that the monsters spawned somewhere far away (and didn't just swam there).
- Which submarine are you playing on? On the off chance that the issue has something to do with the submarine not being able to get as far outside the level as it should.
- Do you have any guesses why the crawlers might've been heading that way? Did you manage to damage them and make them flee, could they have been chasing something?

**Comment by Regalis11** [comment]
Actually, just after posting that message I think I ran into this, or at least another bug that causes a similar-looking outcome.

It seems that if a monster ends up inside the submarine, its marker is shown incorrectly (somewhere far away in the top-left corner of the sonar, making it seem as if it had escaped outside the level).
![image](https://user-images.githubusercontent.com/14351070/177302643-1deaa642-8242-4811-a4de-f65cc515e545.png)

This is easy to reproduce:
1. Start a swarm mission
2. Teleport the sub and the swarm somewhere outside the level
3. Teleport one of the monsters inside the sub
4. Look at the sonar and wait a bit

**Comment by Regalis11** [comment]
Fixed the issue mentioned above in https://github.com/Regalis11/Barotrauma-development/commit/2eef7086f0b3557e3d9f7c3fe34dfe8ab58ee7ad

**Comment by RaptorIM** [comment]
Thank you for looking into it!

- Did you actually see the swarm? I wonder if the problem could be that the marker is shown incorrectly, or that the monsters spawned somewhere far away (and didn't just swam there).
- No, I only saw them on scanner some 90m away, gaining more distance as I was trying to catch them. I was playing single player with bots, after I started chasing after the swarm of crawlers, I couldn't catch up with them. The swarm was already spawned near the exit station.

- Which submarine are you playing on? On the off chance that the issue has something to do with the submarine not being able to get as far outside the level as it should.
- It was unmodified Barsuk, this happened early in the campaign, so it is possible the engine was too weak to counter early end-level currents.

- Do you have any guesses why the crawlers might've been heading that way? Did you manage to damage them and make them flee, could they have been chasing something?
- I think it might have spawned together with another large crawler or mudraptor and they might have attacked each other off-screen, maybe?

- Did this happen in multiplayer or single player?
- Single player.

- What kind of mods are you using - is there a chance some of them could be modifying the behavior of the monsters?
- I was only using some modded items, mechanites, no new monsters or anything I'd be aware that would purposefully modify monster behaviors.

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0

They no longer have incorrect sonar positions if they enter the submarine (hull or within the walls but where there is no hull).

However, I decided to do some testing by trying to spawn regular crawlers and check what happens when they flee - they could be fleeing from another creature it seems as they will indeed flee beyond where the submarine can reach if they just keep heading the same direction. doing this in practice for a large distance though seems very unlikely to me (and around level geometry) but still a possibility if they are already near the level end and something like a mudraptor spawns.

**Comment by NilanthAnimosus** [comment]
Further testing on 0.19.0.0 possibly reveals this:

In some very edge cases, it may be possible for creatures to swim past the level boundry, where the submarine begins to be pushed back. they are allowed to go approximately 300 meters past that point before turning around. however in my testing a barsuk could only go around 100~ meters distance into that based on the level size and distance from that in debugdraw.

A swarm for instance can move under certain (Unknown) circumstances, they do not flee from any target as a mission objective and will attack everything, however once they lose a target or the swarm moves and reforms somewhere it might move in a singular direction, which could be out of the level and turning at the boundry until it gets close to the abyss outside the level.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/31ce4a9fc49fc5d182eee2628ea0b6bcde9afee6

> Made the water current outside the levels start from the same point where monsters start heading towards the level, to make sure monsters can't escape too far from sub with a weak engine.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861, no issues found, closing.

notes:
I found fish only went out so far, and even a low engine power submarine like the Barsuk was able to go out to the distance where they retreated from the map border.
