### ISSUE TITLE
physicorium harpoon doesn't have preferred container harpoon gun

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9530]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

alienspear / physicorium harpoon doesn't have preferred container harpoon gun, only arm/sec cab, so bots won't ever try to (re)load harpoon guns w/ them.

this is odd because the other physocirum weapons do have usable preffered containers (railgun, coilgun) and the unique spear also has harpoon gun as well.

### Reproduction steps

1. fill a harpoon gun w/ alien spears
2. enter test mode
3. shoot spears inside sub, drop harpoon gun
4. tell AI to clean up
5. harpoon gun isn't reloaded

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8d47f4e1971380ec0d8f64b15c5ce14ae139133d. Also applied to explosive harpoons

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0 - Works correctly, closing.
