### ISSUE TITLE
Submarine files docked shuttle changes linked state after being used, undocked and level changed in campaign

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9531]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So I encountered this when testing another issue but it appears the submarine loaded into memory can be changed somehow in a single player game, effecting new campaign games you make with that submarine, new purchases of that submarine in new campaigns and the sub editor's copy of that submarine (but not a new instanced copy of barotrauma or the actual sub files themselves, just whatever is held in memory).

### Reproduction steps

It seems pretty reliable to replicate by starting a new campaign game with any submarine, then adding enough money to buy a submarine with a shuttle - Buy and switch to it then undock.

While undocked, move the shuttle a modest distance (50 meters should suffice) as to not lose the shuttle but also not have it docked. dock back to the outpost then go to the main menu.

now the submarine file with the shuttle (IE. a remora) will have its shuttle unlinked and the shuttles relative position reset to the center of the mainsub in the editor, Any new games made from this point will also throw an error with the shuttle not being docked to anything and remain that way in the save permanently. restarting the game corrects the issue - and peculiarly if you link the submarine in the sub editor and quit this will also resolve the issue.

### Bug prevalence

Happens regularly

### Version

Other

### -

Release branch release commit https://github.com/Regalis11/Barotrauma-development/commit/36e3a2755f5fc201a748a32b63cc93a8eb30d90a

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/284e755dfc8656f1c9ab25861324b73918a82261

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/d686a264bfa008dc4e19d346f446dd8028864ea8, working correctly, closing.
