### ISSUE TITLE
Issues with prevention on upgrading submarines / doing maintenance after submarine purchase and switch

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9534]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This is two separate but very related issues, one in single and one in multiplayer

I found myself unable to to upgrade or perform maintenance on a submarine after buying and switching to a sub (then proceeding to change back to the original submarine) before undocking and redocking to an outpost.

Additionally multiplayer completely skips this restriction that single player abides to and its dialogue - so its a case of keeping it or fixing it?

I would have assumed this may have been put in place to not repair the items and other aspects of the wrong submarine, which makes this a bug in multiplayer, meanwhile if it is no longer an issue (IE. repairs are applied before saving the sub and switching to another) then I'm not sure its relevant to keep this anymore? if it is relevant, then these two separate issues should probably be fixed at some point.

### Reproduction steps

1. Start a single player campaign game.
2. Add enough money to buy a new submarine
3. Buy and switch to submarine
4. Use selection console to switch to your current submarine (IE. if you started with barsuk, switch to barsuk)
5. Now leave the outpost
6. immediately redock with the outpost
7. Attempt to upgrade or repair your submarine, you will be told their unable to work on your new submarine until it has been delivered despite we are not switching submarine anymore.

For multiplayer issue's reproduction:
Just buy and switch to a new submarine then attempt to upgrade/repair, you will find you do not get the restriction or dialogue that prevents you from attempting this.

### Bug prevalence

Happens every now and then

### Version

Other

### -

0.8.13.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I couldn't repro the single-player part: upgrading the sub starts to work again after I switch the sub and return to the outpost.

Fixed the multiplayer part in https://github.com/Regalis11/Barotrauma-development/commit/6d7e4b19d3842670f18062a90d5aaa470c46181f

**Comment by NilanthAnimosus** [comment]
I am still able to repro the single player part in 0.18.15.0

Specifically, I am:
starting a new campaign in single player
using the money command
buying and transferring new submarine
going to the submarine selection console and choosing my current (beginning) submarine
Going to the submarine upgrade merchant and being told I cannot work until the new submarine is delivered - despite I am no longer intending to use it.
I then proceed to leave the outpost and then redock going through two loading screens.
I then run back to the submarine merchant, I am still denied from upgrading or repairing.
This is only resolved by finally switching to the new submarine.

Expected behaviour: Once cancelling the submarine switch, be allowed to upgrade. Alternatively: Changing locations should allow submarine upgrades again.

**Comment by Regalis11** [comment]
Ty, got it to happen now. Not sure what I did wrong the first time around. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ab4dc26d0807ba905a45d3c9e6b6d044a6a879c2

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0

Single player aspect works correctly.

Tested multiplayer aspect of the issue, works correctly too, closing.
