### ISSUE TITLE
Autosave function in subeditor seems not working properly.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9535]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

According to “Diving deeper into the sub editor” (Written by @3e849f2e5c ), the subeditor should automatically save subs every 5min. But I test this, and find it may not work properly.
![image](https://user-images.githubusercontent.com/44423036/177563345-764380a2-d21e-492a-a577-59d957aef112.png)
If I understand this correctly, this function should save the submarine every 5 minutes, but in the picture we can see that it takes more than 15 minutes.
![image](https://user-images.githubusercontent.com/44423036/177563639-af1cb487-8792-48b4-af42-4994e4dc9be0.png)

### Reproduction steps

this is how I found this:
1.go subeditor
2.open a sub called "humpbacktest", this is a copy of humpack
3.now press "Esc", let the game start an autosave. (time is 21:11:30)
4.add "Label number 1", and Every five minutes I just add a “Label Number”, so when time is 21:16:30, I add "2"...
5.on 21:26:30 I add "4", and on 21:27:00 I press "Esc"
6.See how many subs have been saved by autosave.

Oh, you don't have to do what I did, I just wanted to show that autosave doesn't trigger properly every 5 minutes.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d8d80afdb405f211aa7b45ffe683cbccb5b20ad5 (link to our private repo)

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.
