### ISSUE TITLE
Losing sync mid-campaign round resulted in submarines to load differently only on reconnect, not rejoin

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9539]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Reopening this as I've gotten it during testing - curiously however I had not toggled off the respawn shuttle during the round (Or messed with it at all really) so it is not tied to #7700.

![image](https://user-images.githubusercontent.com/29177976/177732304-69d0c65a-5b5e-4a3e-8488-ce0663c128d8.png)

![image](https://user-images.githubusercontent.com/29177976/177731781-946ebdcf-b3da-44f9-821c-df2703d170cb.png)

Managed to trigger this while testing ballastflora in a campaign round that had a pirate submarine for context, I had paused my client code via visual studio and forgot to pause the server as well which disconnected me to an entity event that no longer existed (as standard) - however when it reconnected it threw the error.

Reconnecting from the main menu then spectating in worked fine however, which made this all the more curious.

### Reproduction steps

not fully known, this is how/where it occurred though:

Was testing ballastflora in a campaign game, I also had a pirate mission in the same loaded level which also has evidence of a wreck being present. so any of these may be factors.

used commands ballastflora infect and ballastflora growthwarp 30 twice each. I had also teleported some pirates I gave afflictions to and spawned+killed a few humans with varied afflictions in testing

I had paused the client's code via visual studio long enough to get a disconnection by events no longer existing server-side. the game attempted to reconnect triggering the error of submarines not matching (Likely respawn shuttle).

No server settings were changed since the server started (Other than loading an existing campaign save). pirate event was triggered via command and left from outpost into the round.

Here is the save in case its helpful (Should be the save of the round which the disconnect occurred): 
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/9061991/Multiplayer.zip)

### Bug prevalence

Happens regularly

### Version

Other

### -

0.8.13.0 bugfix branch commit https://github.com/Regalis11/Barotrauma-development/commit/6efb667a91d39ee7715a094a89a32ed20b73d6ec

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Quick check showed on reconnect sometimes the client does not know what selected shuttle is in use:

![image](https://user-images.githubusercontent.com/29177976/177738684-628ad3da-f8a2-4f7a-b9a4-6f491f1472c6.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c5beb2ec8d51706b8c0ce6cbf2457fd6636761c

Can be reproduced as follows:
1. Start a campaign round with a respawn shuttle enabled and loaded (= needs to be a non-outpost level)
2. Pause the client for a minute or so
3. Unpause, you should get an error about waiting for a removed event and get kicked to the lobby
4. Spectate, and the client should start the round without the shuttle, leading to the "missing entity" error.

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, works correctly, closing.
