### ISSUE TITLE
Add a .github folder for issue and PR templates.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/Barotrauma#954]
Github supports a .github folder for holding templates for the following:

* CONTRIBUTING.md - General contribution guideline document for anyone making contribs.
* ISSUE_TEMPLATE.md - A template for issues. Multiple templates can be made for different types of reports (bugs, feature requests, ect.)
* PULL_REQUEST_TEMPLATE.md - Same thing but for PRs.

[Additionally the issue templates can appear at the top of the issues board so people can select what type of issue they want to make](https://help.github.com/articles/about-issue-and-pull-request-templates/).

Might help incentivize people to be thorough with future issues.

**Comment by Regalis11** [comment]
I didn't even know these were a thing, thanks for the tip! I'll look into adding these this weekend.
