### ISSUE TITLE
"Decoy" tag is too strong and enemies (including abyssals) will ignore everything else

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9540]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The "Decoy" tag (used by decoy depth charges) has a 500 priority for all AI

![image](https://user-images.githubusercontent.com/73229309/177724874-76fb933e-9cfe-404c-b746-10e16db914ab.png)

Monsters will ignore *everything* around them, even getting hit and fired at by submarine guns.
This applies to abyssal, you can zoom past the Doomworm using decoy

https://user-images.githubusercontent.com/73229309/177727143-d85b2253-5f3f-4979-aa18-e0a6697789bf.mp4

It doesn't matter if you're shooting guns  at the fishies or running the engine at full speed blasting sonar, monsters will focus on the decoy alone for the full duration

**Possible changes:**

1. Reduce the duration of decoys. Aitarget fadeout time is 50 seconds which is very long, 15-20s is enough for a moving sub to create distance

2. Reduce the AI priority for "Decoy" on all enemies severely, somehow. A very loud sub (turrets blasting and whatnot) should take priority over the decoy
 _I've tried fiddling with Crawler AI priority, "decoy" and "provocative" tags to no avail. Reducing decoy priority to 1 and reactdistance to 0 didn't seem to achieve anyting. Maybe it's hard-coded I have no idea._ 

3. Abyssals should have lower priority for decoys

**Comment by ubertpendragon** [comment]
See what Ghostsheet just did here

https://steamcommunity.com/sharedfiles/filedetails/?id=2834119941

**Comment by itchyOwl** [comment]
Destructable decoys is actually pretty good idea.

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development#3495. Thanks for the link to the mod!
