### ISSUE TITLE
Detonator crashing the game

### ISSUE THREAD

**Issue by VelehoMeister** [Regalis11/Barotrauma#9542]
While using a button to trigger explosives, an error occurred which crashed the server.

![image](https://user-images.githubusercontent.com/32824502/177833768-baf72344-f0e5-4657-b970-104b5fddaa78.png)

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not find a way to reproduce this though. Tested by putting a C-4 block inside a detonator in multiplayer and triggering it with a button. Are you using some kind of mods by any chance? What kind of explosives were you using?

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by MatiP911** [comment]
Found way to reproduce bug. All You need to do is place explosive on breakable ice surface and detonate it
![SharedScreenshot](https://user-images.githubusercontent.com/64082311/185434249-e11e05d3-d12b-4841-8f08-dbc645c1eb1d.jpg)
.
