### ISSUE TITLE
Can't save my submarine

### ISSUE THREAD

**Issue by Rparvitn** [Regalis11/Barotrauma#9545]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I did my own submarine in one of last versions. Now, when I try to save it, this error appears.
![image](https://user-images.githubusercontent.com/97904411/178014674-c59e64c3-8682-4e65-bf39-b6df188980d2.png)
(screen of save, just in case)
![image](https://user-images.githubusercontent.com/97904411/178014919-6bb27084-27c0-468e-928b-81271ce4ba72.png)
At first I fixed it by deleting submarine files from localmods, but the next day problem returned.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Rparvitn** [comment]
additionally - autosave still works

**Comment by Regalis11** [comment]
I was able to get this same error message with the steps provided in https://github.com/Regalis11/Barotrauma/issues/9554. I'm not 100% sure if that was what happened here, but that error should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/68e7f201a468d07babf65907a2e4b3a9fa364939

**Comment by FlareFlo** [comment]
> I was able to get this same error message with the steps provided in #9554. I'm not 100% sure if that was what happened here, but that error should be fixed in [Regalis11/Barotrauma-development@68e7f20](https://github.com/Regalis11/Barotrauma-development/commit/68e7f201a468d07babf65907a2e4b3a9fa364939)

Link is dead / 404s

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

I tried:

- Editing and saving an autosaved submarine (both before and after being added to a local content package)
- Submarine whose name does not match the content package name (Multiple submarines in a content package) and its autosave
- Removing the local mod from the games folders, restarting the game and then loading and saving an autosave.
