### ISSUE TITLE
Thalamus walls size and sourceerect are wrong + lack of background sprite

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9548]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Thalamus wall collision box is too large

You can see the shadow box far behind the actual sprite
![image](https://user-images.githubusercontent.com/73229309/178107482-dce03261-7d8d-4545-94a0-b66b7fcbc5bb.png)

Improper hitbox 
![image](https://user-images.githubusercontent.com/73229309/178107891-92b056db-6f3b-4408-b0d9-1f5e3e329c33.png)

and

Thalamus wall has no destroyed sprite. Unlike other walls, it doesn't have a background sprite that makes it darker when detroyed

Here's a fix by replacing Thalamusstructures.xml 
[thalamusstructures.zip](https://github.com/Regalis11/Barotrauma/files/9076585/thalamusstructures.zip)

Also added a fleshy hit sound when the wall gets shot but you can get rid of it.

After:

Proper shadow box
![image](https://user-images.githubusercontent.com/73229309/178107617-49512c9d-f672-49c3-9c1f-1fbfe9588c36.png)

Proper hitbox
![image](https://user-images.githubusercontent.com/73229309/178107646-2bb839a9-51a6-40ae-a5c2-d332825a37d5.png)

Proper background
![image](https://user-images.githubusercontent.com/73229309/178107659-e2808168-8769-4e7f-9346-e790f70e6dda.png)

```xml

    <structure name="" identifier="thalamus_wall_vertical_1" tags="thalamus,thalamuswall_vertical" width="68" height="50" resizevertical="true" body="true" castshadow="true" health="50" category="Thalamus" damagesound="LimbSlash">
      <sprite texture="Content/Map/Thalamus/thalamus.png" depth="0.4" sourcerect="1006,64,96,513" origin="0.5,0.5" />
	  <backgroundsprite texture="Content/Map/Thalamus/thalamus.png" color="80,80,80,255" depth="0.6" sourcerect="1006,64,96,513" origin="0.5,0.5" />
    </structure>
    <structure name="" identifier="thalamus_wall_horizontal_1" tags="thalamus,thalamuswall_horizontal" width="50" height="67" resizehorizontal="true" body="true" castshadow="true" health="50" category="Thalamus" damagesound="LimbSlash">
      <sprite texture="Content/Map/Thalamus/thalamus.png" depth="0.4" sourcerect="96,299,512,67" origin="0.5,0.5" />
	  <backgroundsprite texture="Content/Map/Thalamus/thalamus.png" color="80,80,80,255" depth="0.6" sourcerect="96,299,512,77" origin="0.5,0.5" />
    </structure>

```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f53b389af0460c035945d37de6188e723493e9e9

I didn't change the size of the sourcerect, but instead scaled down the collider, because changing the sourcerect will cause issues in existing subs and won't even fix the issue completely (there was still a small gap between the edges of the sprite and the edge of the collider with the way you'd set it up).

**Comment by Regalis11** [comment]
Those are decorative wall pieces with no collider: afaik there are no solid thalamus wall pieces in the Kastrull wreck. And the collider size should be loaded from the prefab, not the sub file, so I don't think there's actually an issue here.

**Comment by NilanthAnimosus** [comment]
My bad didn't know there was even decorative walls for thalamus, re-checking using the Hemulen which has one at the top indicated a much smaller, virtually insignificant difference, but curiosity none the less:

![image](https://user-images.githubusercontent.com/29177976/180158304-815b0652-7fc7-49f1-af49-a81468103f62.png)

This is after setting the new ones scale to .7, snapping both to grid, moving them side by side with arrow keys and dragging to get as close a match as possible.

looks like the above is not specific to this version (or the changes here) and is just a quirk from older placed pieces in general.
