### ISSUE TITLE
Nuclear depth charge has no EMP

### ISSUE THREAD

**Issue by ghostsheet** [Regalis11/Barotrauma#9549]
Nuclear depth charge and nuclear railgun shells are practically the same
Especially in terms of cost and explosion damage
However the nuclear depth charge lacks the EMP effect of the nuke railgun
Massively reducing their viability against pirates and other sub/structures

This discrepency should be changed for the sake of gameplay and inconsistency

please and thank you
(quick two line change)

also it would be nice if nuclear decoy has a Radioactive Symbol on it to differentiate from a normal decoy

**Comment by MaaiG** [comment]
> also it would be nice if nuclear depth charge has a Radioactive Symbol on it to differentiate from a normal decoy

Yea!
![Image 001_13-23](https://user-images.githubusercontent.com/93348499/178141086-db8bb0e9-5e1c-4779-a4f6-43bf4248b9fb.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b3b3c8b660d0cde80416ea78f9a5cd8cb62c70a0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
