### ISSUE TITLE
"OnDeath" status effects no longer work for afflictions

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#9552]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I am not exactly sure when this started being the case, however I've noticed that any status effect with the type "OnDeath" simply no longer works if triggered from an affliction.

### Reproduction steps

[Here is a mod containing an overrided version of "morbusine poisoning". I have added an on death status effect for when the strength of the affliction reaches 80-100.](https://github.com/Regalis11/Barotrauma/files/9079338/Testaffliction.zip)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2240d25499cc8adb54db7ff33b2a9ead7a2fccbf

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

Notes: Tested both ondeath statuseffects via items and from afflictions where an effect gives an ondeath statuseffect.
