### ISSUE TITLE
Thalamus/Ice walls can be repaired

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9553]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Thalamus/Ice walls can be repaired with a welding tool

That's just kind of wild

### Version

0.18.12.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/e63d0b86f12ff984b344e2a51a29f374041b68db

**Comment by Regalis11** [comment]
> As a note, both thalamus walls and ice walls can be repaired via fixfoam grenades

Imo that's not that much of an issue, if it plugs the walls with some kind of foam and doesn't require them to be metallic like welding does, I don't see why it couldn't repair them.
