### ISSUE TITLE
Vitalitymultiplier limb attribute does not work

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9556]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Vitalitymultiplier limb attribute which can be found in a character.xml file does not seem to work properly.
Changing the multiplier of one specific damage type and number does not increase/decrease damage taken.

**Only "damage" and "burn", which increases global damage and can be found on Crawler limbs, works.**
```xml
<Limb name="Head">
<VitalityMultiplier type="damage,burn" multiplier="1.5"/>
</Limb>
```

Here's an example:
Fractalguardian has modifier for each of its limbs

```xml
    <Limb name="Torso">
      <VitalityMultiplier type="bleeding" multiplier="0" />
      <VitalityMultiplier type="burn" multiplier="0.25" />
      <VitalityMultiplier type="lacerations" multiplier="0.5" />
      <VitalityMultiplier type="bitewounds" multiplier="0.5" />
    </Limb>
```

### Reproduction steps

1. Change one of the above multiplier values in Fractalguardian.xml, ideally explosiondamage, to 100
2. Spawn a fractalguardian
3. Shoot it with a weapon that does damage of said type

It takes the same amount of damage when using lacerations, explosions, blunt...

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

**Comment by itchyOwl** [comment]
Damn, need to check the balance after this. Burn should be type btw.

**Comment by ubertpendragon** [comment]
> Damn, need to check the balance after this.

Fractal guardian balance is very inconsistent which prompted me to change some of the values in the ruins mod


Most important part is limb multipliers:

Head is 1.25x
Arms are 0.65x
Tails are 0.35x

So you get a factor of 1 to 4 damage depending on where you aim 

Arms often block headshots
Fractalguardian(1) moves a lot with its rear exposed most of the time, taking little to no projectile damage
Fractalguardian2 will stare at you and shoot with steam cannon, exposing its head a lot

Explosives barely hurt them: It takes from 8x to 9x 40mm grenades to kill
And if the vitality modifiers actually worked it would simply be _impossible_ to kill with burn damage (Fissile accelerator, Steam gun)

In my case I just set all limb multipliers to 1 and head to 1.25x and increased its total health _+ severable tail for flavor_

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly

Notes: I went and did a quick find in files check for all characters examining all the vitalitymultiplier's. No more incorrect identifier/type values could be seen other than bleeding is used interchangably (With minor effect)

IE. Bleeding is used as a type on human and an identifier on fractal guardians. though technically both are valid this does mark a slight difference.

Since fractal guardians use the identifier, they could be suceptible to the bleeding identifier "bleedingnonstop" but I don't know if that is used anywhere by vanilla.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4b0f112763a4f550a5ea3e461d7076fed46f322e

**Comment by NilanthAnimosus** [comment]
re-examined against dev branch Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/bb09d83d99ad00711a0eb53b06788895d76d0ec1

Fractalguardian2 still has identifier="bleeding" over type="bleeding". all other characters seem to have correct identifiers or types.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/72564f22437b8045b6b687678c41250e373bc6e7

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/44da366f073b582aa15434dc2b4874f9fd970d97, no issues found, closing.
