### ISSUE TITLE
Pulse laser fires in wrong direction

### ISSUE THREAD

**Issue by Qualiqola** [Regalis11/Barotrauma#9557]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

While firing the pulse laser, certain angles the pulse laser is aimed at fires it in an off direction that is not the location that I am aiming at. The pulse laser seems to still damage monsters that I am aiming my cursor at, but structures seem to take no damage. The issue seems to only happen near structures such as alien ruins or wrecked subs. I am using a modded submarine called the R-278 «Dugong», other than the sub, no other mods are active.

### Reproduction steps

1. Start a campaign level with a submarine with a pulse laser
2. Approach a structure such as an alien ruins or wrecked submarine to where it can be clearly seen using periscopes
3. Fire the pulse laser at different parts of the ruins/wreck and see if the pulse laser fires weirdly.

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to reproduce this. Tested by firing at ruins, wrecks and beacon stations from various angles:
![image](https://user-images.githubusercontent.com/14351070/178439494-0e7a19a4-5346-4649-b1ef-18cdaced20cb.png)
![image](https://user-images.githubusercontent.com/14351070/178439538-698d174e-cace-4f60-804b-dc5689dc0ce5.png)
![image](https://user-images.githubusercontent.com/14351070/178439574-2185e37d-c7cd-4809-beec-e30132f5fdbc.png)
![image](https://user-images.githubusercontent.com/14351070/178439621-28d5988f-4c75-4fa8-9665-9017ebf25f2f.png)
![image](https://user-images.githubusercontent.com/14351070/178439687-6b1bd04a-7fd6-43be-9300-785353e135c6.png)

Did the issue occur in multiplayer or singleplayer?

**Comment by Regalis11** [comment]
No known steps to repro, closing
