### ISSUE TITLE
Duplicate "Decorative wire" structures

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#9558]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Two of the "Decorative wire" structures have the exact same sprite.
Item picker view:
![image](https://user-images.githubusercontent.com/67431770/178406366-ddc807ed-cea2-4d09-8aae-5786755f8759.png)
In game:
![image](https://user-images.githubusercontent.com/67431770/178406751-4e1ac83e-c8a4-4e77-881e-5fcbfe1dc13b.png)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/12bc2456d95f8dcafa2a5f5e4a46126d3959bf18

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.

Notes: Used a sub file with both copies placed from 0.18.15.0 and checked that sub file out in 0.19.0.0 with zero issues to be thorough.
