### ISSUE TITLE
The velocity of fall objects does not change in water. No splashes from falling.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9559]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. The velocity of fall objects does not change in water.
2. Some objects did not fall out of the lower hull.
3. No splashes from falling into the water!

### Reproduction steps

Test chamber: 
[_Test-Drop_W.zip](https://github.com/Regalis11/Barotrauma/files/9092232/_Test-Drop_W.zip)

https://user-images.githubusercontent.com/93348499/178474994-7745d829-ef3a-42ab-bf00-ffd464fa6c8a.mp4

Especially noticeable with cargo crates:

https://user-images.githubusercontent.com/93348499/178475787-3a0f65d9-f5bf-42de-9501-764e7001cc72.mp4

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by MaaiG** [comment]
@Regalis11 
Why do I think these things are mistakes.
The game is simply positioned as a [submariner’s simulation in space](https://www.youtube.com/watch?v=5astpd0RRrY&t=3s). If I don’t shush, those are the words that Sean Connery says. Am [I right?](https://barotraumagame.com/wiki/Credits) He sounded like.

In this regard, it seems to me that the main things for the game are such environments as liquids, gases, pressure, gravity, radiation and so on. All this is a game world in which the player will live, survive, explore, die, lose and find, experience different emotions. Plunged into this world and rest your soul in these adventures )).
So playing with these things in the editor I expect them to behave accordingly.
It seems to me possible to build a mass of addictive, atmosphere-immersive mini-games, exciting game moments, puzzles, mazes, and adventures requiring thoughtful decisions on the verge of life and death using all these environments. So I thought that any unnatural or not expected behavior of these environments was a mistake.

I think every player should get the impression at the end of the mission that he has done the impossible, he’s a real hero and he’ll have something for remember and to tell someone his story. ))

But in order for there to be interesting stories about adventures, you need a world where these adventures are possible. A world that stimulates the imagination of the player. Well, like old games: you look at a bunch of pixels but you see something else, perfectly beautiful and detailed. Need just a correct frame and your imagination will do the rest.

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed
