### ISSUE TITLE
The server list does not work

### ISSUE THREAD

**Issue by CAPPAGLI** [Regalis11/Barotrauma#956]
I have searched the issue tracker to check if the issue has already been reported.

The server list does not work. Everything is fine with the Internet

It started a month ago, after updating. The server is loaded for a long time, after which a notification *Connection error
Could not connect to master(request timed out)*
appears (with my Internet, everything is fine). I reinstalled the game several times, but it did not help.

version 0.8.2.2 / windows 7

![image](https://user-images.githubusercontent.com/45564484/49378530-cbe01880-f747-11e8-8cd0-fc4387445fa5.png)

If you have questions, write to this email: ghoster25@yandex.ru

**Comment by Regalis11** [comment]
The most likely cause for this is your antivirus/firewall preventing your game from connecting to the master server. Try adding a firewall exception for the game and see if that helps.

**Comment by CAPPAGLI** [comment]
I do not have an antivirus, and the firewall was disabled before the problem appeared

**Comment by rico6822** [comment]
Sometimes it happens randomly not by user's fault. Maybe bad weather conditions caused you to lose connection with master server.

**Comment by Regalis11** [comment]
The legacy master server has been deprecated, so I think we can get rid of this issue

**Comment by maks900level** [comment]
A new master server list was created for legacy!

Go to your Barotrauma installation and edit config.xml. From there you should see masterserverurl and then the old master server. Replace the URL with the new one "http://baromaster.gq/" and then you can start playing again! Feel free to start some new ones so we can play other mods and gamemodes!

New Legacy Barotrauma discord server - https://discord.gg/9rMDwsyEGs
