### ISSUE TITLE
Alieninfection appendages break if applied in a certain order

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#9562]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The human husk has its appendages defined in this order:
```xml  
  <huskappendage affliction="huskinfection" path="Content/Characters/Humanhusk/Huskappendage.xml" /> 
  <huskappendage affliction="naturalmeleeweapon" path="Content/Characters/Humanhusk/Mudraptorbeak.xml" onlyfromafflictions="true" />
  <huskappendage affliction="naturalrangedweapon" path="Content/Characters/Humanhusk/Spinelingspine.xml" onlyfromafflictions="true" /> 
```

If you give yourself these appendages through console commands by going from top to bottom, all the appendages will render on your character properly.
If you give yourself these appendages going from bottom to top (or starting with middle, then bottom, then top), once you give yourself the husk infection, the stinger will visually break:
![hobrobrius](https://user-images.githubusercontent.com/9964331/178784640-fda42377-46b2-442f-b45b-3b3cef5b1268.png)

This is possible to achieve without commands, as you can have both the mudraptor and spineling genes, and then have the husk appendage show up either through husk genes or by just being infected.

It is also possible to simply edit the human husk's character XML file to manually put the huskinfection appendage at the end of the list, like so
```xml  
  <huskappendage affliction="naturalmeleeweapon" path="Content/Characters/Humanhusk/Mudraptorbeak.xml" onlyfromafflictions="true" />
  <huskappendage affliction="naturalrangedweapon" path="Content/Characters/Humanhusk/Spinelingspine.xml" onlyfromafflictions="true" /> 
  <huskappendage affliction="huskinfection" path="Content/Characters/Humanhusk/Huskappendage.xml" /> 
```
Resulting in the broken appenadges being viewable from the character editor by looking at the humanhusk character.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.15.1

This also occurs in game if typing out the following on a character via commands:

giveaffliction "Husk genes" 100 character (So they don't die of the infection)
giveaffliction naturalmeleeweapon 100 character
giveaffliction naturalrangedweapon 100 character
giveaffliction huskinfection 90 character

and doesn't occur if you change the order in game to:

giveaffliction "Husk genes" 100 character (So they don't die of the infection)
giveaffliction huskinfection 90 character
giveaffliction naturalmeleeweapon 100 character
giveaffliction naturalrangedweapon 100 character

![image](https://user-images.githubusercontent.com/29177976/185456371-0f15ed82-1e5a-44d5-b81e-58f29b434e05.png)

it looks like the husk infection applies something to each extra limb (?)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
