### ISSUE TITLE
Handle SIGTERM gracefully

### ISSUE THREAD

**Issue by notpeelz** [Regalis11/Barotrauma#9565]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm running `DedicatedServer` in a docker container. If I try to stop the docker container, it crashes with a SIGSEGV (segfault).

```
src/tier1/fileio.cpp (5164) : m_vecRegisteredWriters.Count() == 0
Segmentation fault (core dumped)
```

### Reproduction steps

1. Start a linux dedicated server
2. `kill -TERM "$(pidof DedicatedServer)"`
3. Observe how the server takes longer than usual to shut down

Note that this doesn't happen with `kill -INT "$(pidof DedicatedServer)"` (`SIGINT` is the signal sent when pressing CTRL-C)

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6eccd571a4921840de3c0bc980bcf6ff1367a272

**Comment by notpeelz** [comment]
Is this in the 0.18.15.0 release?

**Comment by NilanthAnimosus** [comment]
This is in the 0.19.0.0 unstable version, not in 0.18.15.0

**Comment by Rokvach** [comment]
Tested, using the command the server closed immediately. Working correctly, closing.
