### ISSUE TITLE
Limb attacks in multiplayer can result in limb index out of bounds on reconnect

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9566]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was using spliced genes (Specifically I had combined 2 genes into 1 tainted gene at the time, which involved a spineling genetics)

I had used the spineling attacks then disconnected myself from the server, upon reconnecting I got limb index out of bounds, presumably they had not "Grown back" or the mere act of using the spineling attacks causes invalid executeattack messages in console once you rejoin.

![image](https://user-images.githubusercontent.com/29177976/178859093-8c0c6605-267b-4546-aad9-01947c4f068d.png)

### Reproduction steps

Presumably:

1. Start a multiplayer match on a dedicated server
2. spawn in genetics for a spineling and a gene splicer to hold it
3. Add them to a character, use up all its attacks
4. Disconnect from the server.
5. Reconnect to the server and spectate the round.

### Bug prevalence

Happens every now and then

### Version

Other

### -

0.18.15.0 - Unstable

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5c82b4ed13e3f721cc0cbc90a0f03e512a489e6a

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0, works correctly, closing.
