### ISSUE TITLE
Viva la Revolution achievement not unlocking

### ISSUE THREAD

**Issue by 4546ReaperLeviathan** [Regalis11/Barotrauma#9569]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I don't know if it's just me, but i could'nt get the ''Viva la Revolution'' achievement despite having done what the description said.

### Reproduction steps

https://user-images.githubusercontent.com/101508666/179077183-1d214c0a-1711-4344-9f3f-7b99726a1e4c.mp4
![Steam 14 07 2022 23_27_52](https://user-images.githubusercontent.com/101508666/179077255-a2233714-6922-4cbb-b9f7-0356f7283ad5.png)

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately wasn't able to reproduce this: completing the mission seems to unlock the achievement correctly. To be clear, to unlock this you need to play a multiplayer PvP mission as the Separatist crew, win the mission, and still be alive at the end of the round (it's not enough that your team wins, you need to survive as well). Was that how you tried to unlock it? Are you sure cheats were not enabled on the server (which disables achievements)?

**Comment by 4546ReaperLeviathan** [comment]
I didn't see the host using cheats, but they might have still been on. Thanks for the support.
