### ISSUE TITLE
item count is increased by 1 when in wiring mode in sub editor

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9571]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the screwdriver that's held in the "hand" in wiring mode increases the item count display until wiring mode is exited

### Reproduction steps

1. open sub editor
2. enter wiring mode

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.15

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, works correctly, closing.
