### ISSUE TITLE
The "bindkey" command crashes the game when attempting to bind an already bound key.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#9575]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I attempted to bind the key "F" to the command "followsub" while it was already bound to "Creature attack" in the settings menu.

Actual behavior:
The game crashed.

Expected behavior:
The game should allow the key to be bound to both the command and the action at the same time.

### Reproduction steps

1. Launch the game.
2. Attempt to bind any key that is already bound to an action in the controls menu.
3. The game will crash.

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.18.15.0 (please update the template)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

[crashreport (15).log](https://github.com/Regalis11/Barotrauma/files/9119679/crashreport.15.log)

**Comment by Jade-Harleyy** [comment]
Additionally, when I was filling out the form, the last text entry would not allow me to upload the crash report.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/934d1a6539c7747d84f01a6491b82c8d964eec88

**Comment by Jade-Harleyy** [comment]
Tested, works perfectly now!
Appreciate the warning it displays in the console as well.
