### ISSUE TITLE
Water pressure pushes the character out of the hull, through the wall.

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9577]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?
Nice bug. I long wanted to report about it, but my hands did not reach to reproduce. ))
On the video v0.18.15.0.

https://user-images.githubusercontent.com/93348499/179214678-e18c2731-7117-45b8-a95f-c7e6b0dc6bd9.mp4

### Reproduction steps

Reproduced periodically at the start of the test. Found in v0.18.12.0 and higher:

https://user-images.githubusercontent.com/93348499/179214701-dc6548e5-6522-4b86-9e3f-dc1a4d0f8604.mp4

Test chamber: [_Test-Water-Hull.zip](https://github.com/Regalis11/Barotrauma/files/9120436/_Test-Water-Hull.zip) 

It seemed to me that in order to re-play the test, we had to restart it.
It doesn’t work twice in a row...IMHO. Only after restarting Test chamber.

### Bug prevalence

Happens regularly

### Version

0.18.15.0
0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b287090ad0cd0ea6933b91b30e7c662ff89edab3

**Comment by Rokvach** [comment]
Tested in the mechanic tutorial where I was previously able to reproduce this, I wasn't able to get my character to phase through the inner wall of the tutorial anymore after the fix. Working correctly. Closing.
