### ISSUE TITLE
Physicorium Chaingun Ammo's price wasn't changed despite recipe changes

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9579]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Despite the much cheaper recipe (Physicorium, Titanium, Aluminium) Physicorium Chaingun Ammo's base price is still 520.

It effectively became (probably) the best item to sell to make money.

### Version

0.18.15.0

**Comment by JeroonBosch** [comment]
Updated to 410 in dev

**Comment by NilanthAnimosus** [comment]
Examined further against dev commit https://github.com/Regalis11/Barotrauma-development/commit/6c89a275a94f5c3410996a8f8ebdad8227021421.

Gone through the items and found (Identifiers in XML):

coilgunammobox base price is 120 (not 100)
alienshell base price is 400 (not 300)

I checked depleted fuel as well as coilgun, railgun, chaingun, pulse laser and depth charge ammo costs and found only these two not matching expected values.

**Comment by JeroonBosch** [comment]
Fixed the sheets

**Comment by NilanthAnimosus** [comment]
Tested against 0.19.1.0, works correctly - closing.
