### ISSUE TITLE
Inflamed Lung affliction doesn't go down with husk infection

### ISSUE THREAD

**Issue by notpeelz** [Regalis11/Barotrauma#9585]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you have a husk infection and the inflamed lung tainted gene, low O2 no longer reduces inflamed lungs.

### Reproduction steps

1. `giveaffliction "Inflamed Lung" 50`
2. `giveaffliction "Husk Genes" 100`
3. `giveaffliction "Husk Infection" 90`
4. Go into the water
5. Notice how the inflamed lung affliction doesn't go down

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, works correctly, closing.
