### ISSUE TITLE
Drastic performance drop when a character has a large number of sub talent trees

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9590]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Having a large number of sub talent trees (and/or talents) causes a drastic performance drop, especially when the talent menu is open. Can be easily reproduced by installing the ["All The Talent Trees" mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2691181887), which adds all the sub talent trees to every job.

### Reproduction steps

1. Install ["All The Talent Trees"](https://steamcommunity.com/sharedfiles/filedetails/?id=2691181887)
2. Open the talent menu
3. For bonus points, unlock all talents and notice the performance degrades further

### Bug prevalence

Happens every now and then

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/3480/commits/46b861d3b037badef51ce3d62fdf1b8351965c6b

**Comment by Rokvach** [comment]
Tested first in vanilla and then with the mod and the fps results were the same when you had none or you had all of the talents unlocked. Tested also in singleplayer and multiplayer and didn't notice any issues. 

This can be merged.
