### ISSUE TITLE
Dementonite tools higher crafting cost than files state

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9595]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

dementonite knife (and other dementonite tools) cost 2x of the tools + 2x of the dementonite in fabricator. XML appears to only have 1x tool + 2x dementonite crafting.

```
<Fabricate requiresrecipe="true">
      <RequiredItem identifier="divingknife" />
      <RequiredItem identifier="dementonite" amount="2" />
    </Fabricate>
```

explicitly stating amount = "1" for the tool fixes it.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
on a further check, engineer's hardened tools too, and depleted items (incl depleted revolver round)

I note that for these, they seem to be all VariantOf items, and the original item has material costs in the format of 2x, 2x. perhaps inheritance is being odd here.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/efd30039e7dfcb6c8ab12ab10f651659570e2b9b

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0

Hardened diving knives require 2 knives (?) - I think this has been missed out.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4d2dfa025cf27a8eaa2a5d2d266427fbf07fc6e2

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
