### ISSUE TITLE
team preference generates highly imbalanced teams for PVP

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9597]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using team preferences can result in wildly unbalanced teams:
example:

team selection 3 coalition, 1 renegade, 6 no prefence:
![image](https://user-images.githubusercontent.com/5103517/179563825-5d808f07-ffeb-4ffa-9806-bffc2570384b.png)

generated team:
4 coalition, 6 renegade
![image](https://user-images.githubusercontent.com/5103517/179563863-8e2baa68-deff-4511-a795-e36313bb1ccc.png)

expectation would be for teams to be 5 on both sides.

I believe unbalanced teams can also happen w/o team selection.

### Reproduction steps

1. pick teams for sub vs sub mode

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/72bc46ce029f939f7e4ee8f5c8224aa815e6c9e9

**Comment by Rokvach** [comment]
There were no obvious issues to the pvp mode with this change, but I wasn't able to test the balance as for that we will need more players. I think this is ready for merge and further testing with the community.
