### ISSUE TITLE
It is possible to join servers with job preferences that are otherwise hidden in selection (but not spawn as)

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9604]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It is possible to edit your player config file to set preferences to NPC only jobs such as vipsecurityofficer or prisoner which will show (for the player and other clients) as their preferred job in a lobby.

This does not cause the job to actually be picked when a round starts with vanilla NPC jobs (going for the 2nd/3rd preference or a random job if their all NPC jobs) but still probably doesn't make sense to be doable, especially if it works with ones that have positive/no limits set or something in modded jobs (As I don't know what'd happen there).

Essentially this allows you to pick hiddenjobs, which I also believe the server doesn't strictly prevent you from spawning as (I think?)

### Reproduction steps

Edit the player config file to have job preferences that otherwise cannot be selected, such as prisoner or vip, IE:
```
<player
    name="Bob"
    tags=""
    HairIndex="6"
    BeardIndex="13"
    MoustacheIndex="0"
    FaceAttachmentIndex="0"
    HairColor="#000000"
    FacialHairColor="#000000"
    SkinColor="#000000">
    <job
      identifier="vipsecurityofficer"
      variant="-1" />
    <job
      identifier="prisoner"
      variant="0" />
    <job
      identifier="medicaldoctor"
      variant="0" />
  </player>
  ```
  
  The above will show these as preferences in lobby, but still spawn you as a medical doctor.

### Bug prevalence

Happens every now and then

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e0931e37fca9333f724cfb6f8cbbbdc492ba101

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/b285014e5e3d9de0af55014c9711566d6dd92662 and https://github.com/Regalis11/Barotrauma-development/commit/0d815db99a2214ee658bdd53a6a66b33800e4c19

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f82a333e436d97a8051448f960194e41892e9be5, no issues found, closing.
