### ISSUE TITLE
Duct block background sprite - depth issue (interaction with some other objects)

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9606]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The specified objects can be below the `Duct block background sprite` only at a depth of more than 500.
![Image 001_11-51](https://user-images.githubusercontent.com/93348499/179711533-6a6f835e-5d94-46a8-a250-efafa536684a.png)
It’s the same with the their wreckage!
![Image 001_12-22](https://user-images.githubusercontent.com/93348499/179716048-e89978b1-aa1a-495c-80d9-b69e3d317097.png)

### Reproduction steps

[__Test-Duct block BSprite.zip](https://github.com/Regalis11/Barotrauma/files/9139241/__Test-Duct.block.BSprite.zip)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Why's this an issue?

**Comment by MaaiG** [comment]
@Regalis11 I think the black background should be on top of the object! So is the frame of the dгсе block.
Like this: 
![Image 001_12-06](https://user-images.githubusercontent.com/93348499/179712680-609227a7-b7ff-4482-a65a-ab2bcfcb2995.png)

**Comment by Regalis11** [comment]
Ah, yeah, that's a good point. I wouldn't have expected the ducts to be placed inside walls, but I suppose that's a valid use case too

**Comment by MaaiG** [comment]
Fire extinguishing system without a pump (or when there is no power) - is a duсt block in the outer hull of the submarine ))

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/02fd4fdd487e5147bfbfbe91b03a1c7557753aab

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0, works correctly, closing.
