### ISSUE TITLE
Cant undo ladder

### ISSUE THREAD

**Issue by FlareFlo** [Regalis11/Barotrauma#9608]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

A placed ladder is ignored from undoing rules, and the item(s) placed previous to the ladder will be removed instead the ladder

### Reproduction steps

1. Open sub-editor
2. Place any non-ladder item
3. Place ladder
4. Press undo

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e9818439a67d7c3cce88aba09dba739b12499496

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
