### ISSUE TITLE
Mods not requiring Server side are not showing up in the server mod's list

### ISSUE THREAD

**Issue by theCrius** [Regalis11/Barotrauma#9609]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

We need someone else to further investigate this to be sure it's not just a problem I'm running into with my configuration.
This is the docker image I've been using, built by myself using another as a starting point: https://github.com/theCrius/barotrauma-docker

I've been running a dedicated server for several months now, since the release of the mod's refactor in Barotrauma really.

The behaviour that I keep seeing consistently is this:

- If a mod requires it to be installed server side to be able to function on a dedicated server, it will show up and work as expected (provided the mod doesn't have bugs itself). With working as intended I mean that it shows up in the server's mods' list and who connect can download it from the server if not already subscribed to the mod.

- If a mod **does not** requires to be installed on the server, even if installed (mod's file in the right directory and `config_player.xml` edited to include it) it will not show up in the server's mods' list.

Now this second case would be fine as if a mod's not requiring a server side, doesn't matter if it's visible or not.
However, unfortunately, when connecting to a server, the clients are forced to have the exact same list of mods running which means that mods that are meant to work just client's side will be disabled as they are not in the server's mods' list.

### Reproduction steps

- If possible, deploy a fresh VM, if not, at least create a new user to be sure to have a clean-ish system
- Clone https://github.com/theCrius/barotrauma-docker and follow the `readme.md` on how to install a modded server
- Add a server side mod, for example Riba Portable Items (https://steamcommunity.com/sharedfiles/filedetails/?id=2382545579)
- Add a client side mod, for example BetterHealthUI (https://steamcommunity.com/sharedfiles/filedetails/?id=2807158602)
- Be sure to add the relevant lines in `config_player.xml` as explained in the readme mentioned above
- Restart the server to be sure it picks up the mod list from the `config_player.xml`
- Try to connect and check from the server's list if the BetterHealthUI is listed.
- [OPTIONAL] Feel free to try with other mods checking which is actually requiring a server side installation and which not

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by theCrius** [comment]
Good point. I'll create a ticket over to EvilFactory repo then, to see if we can get to the bottom of this

**Comment by theCrius** [comment]
Issue created on EvilFactory repo for Lua For Barotrauma: https://github.com/evilfactory/LuaCsForBarotrauma/issues/94

**Comment by Regalis11** [comment]
...Sorry, I take that back, actually there is indeed an issue in the vanilla game. Even though I was able to join the server with no apparent issues, on a closer look it does seem like the client disables the mods.

**Comment by theCrius** [comment]
No problem, thanks for double checking. If there is anything I can help with (testing other scenarios etc) please let me know.

**Comment by theCrius** [comment]
Reporting an answer from EvilFactory that may help: https://github.com/evilfactory/LuaCsForBarotrauma/issues/94#issuecomment-1190324461

> This happens because those mods don't have any XML content, so barotrauma assumes they are just submarine files or something similar and discards them, the solution is to add an empty XML content file to the filelist.xml.

The solution proposed would require each mod's author to make this change. I don't think it's a solution per se but maybe this insight can help you figure out a simple way to have barotrauma "consider" them.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
