### ISSUE TITLE
newer subs don't have any hidden containers

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9612]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

newer subs - Herja, Winterhalter, barsuk don't have any hidden containers (loose vents / loose panels)

Orca2's "loose panels" are very hidden, I'm not confident that they're really findable outside of heavy aim assist or viewing in sub editor.

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad1bb6abd23e4f723da66c8ace1ecb737f4f6460

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
