### ISSUE TITLE
Wearable tooltip doesn't display probability modifier

### ISSUE THREAD

**Issue by notpeelz** [Regalis11/Barotrauma#9613]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I was changing the `huskinfection` damage modifier for a custom suit but noticed the resistance wasn't listed on the tooltip:
```xml
<damagemodifier
  armorsector="0.0,360.0"
  afflictionidentifiers="huskinfection"
  damagemultiplier="1.0"
  probabilitymultiplier="0.5"
  damagesound="LimbArmor" />
```
- `damagemultiplier="0.5" probabilitymultiplier="0.5"` displays `-75%`.
- `damagemultiplier="1.0" probabilitymultiplier="0.5"` doesn't display anything.

I expected it to display "-50% Husk Infection" because of the `0.5` probability multiplier.

Relevant line: https://github.com/Regalis11/Barotrauma/blob/2e2663a175b28800acc565745a70e3225ab5eafe/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Wearable.cs#L29-L32

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d830e9c83b77c64096e6ba069c1da80ce029c907

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/17a4e29619e49adc0a329be654296cf8f8ddc5d6, works correctly. closing.

Note: this is inside the current unstable build 0.19.1.0
