### ISSUE TITLE
Could not reconnect to server - Missing character

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9616]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Was deliberately making myself reconnect with pausing the code on either side (Client/server) using a debugger on debug builds.

using some local mods and steam mods (with the client not having them and having to download every time) the server failed to sync every single attempt I tried.

Associated Modlist and local mods:
[Mods in use.zip](https://github.com/Regalis11/Barotrauma/files/9158001/Mods.in.use.zip)

The workshop mods were nothing special - Just EK Armory (ID 1769403760) and 32x Stack (ID 2683570256)
The local mods were just a copy of the human XML as an override, and an override for human traits.

I believe going to server lobby was fine, but not entirely sure now...It definitely occurred every single time while 

### Reproduction steps

Have two separate folders of the game
Run the dedicated server with the mods active
Run the client with the mods not active - in my case this folder did not even have the mods locally and was forced to download.
Pause either the client or server and force a reconnect mid-round (but not a disconnect to server list), I recommend server for this.
find you are kicked to server lobby for missing character, indicating a lack of parity between client/server on reconnect.

Further notes: This was merely sandbox mode, a few bots maybe spawned...and literally nothing done in a round on a default submarine (Probably whatever was at the top).

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1f142ff7c4a34e2772ecd5e5d9c6640b16a3f1bc

> Fixed disconnecting and immediately reconnecting to a server that's using different mods than you sometimes causing "missing entity" errors (and potentially other kinds of errors too). Happened because the clients restored their own mods when the connection was lost, which would remove e.g. custom items and characters from that mod. Now we won't restore the mods until the client actually shuts down for good. + Renamed the Disconnect and OnDisconnect methods to Quit and OnClientPeerDisconnect respectively to make the difference between them more clear.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f82a333e436d97a8051448f960194e41892e9be5

Using a few mods, and then having the server hosted with said mods and the client having no mods active on joining, I got this error once I had achieved (from pausing the client) a disconnect kick for excessive desync on a no longer existing event:
![image](https://user-images.githubusercontent.com/29177976/186152374-c26ed12a-4fe3-4154-88a3-64403ab5c813.png)

I failed to enter the lobby, so although we have not rejoined with incorrect/no mods loaded it appears to have failed to rejoin with an error I am not familiar with. rejoining works fine, and although an improvement over unknown entity event errors such as missing characters, the fix does not appear to work correctly.

**Comment by Regalis11** [comment]
Once again referenced an incorrect ticket in the commit message (https://github.com/Regalis11/Barotrauma-development/commit/44da366f073b582aa15434dc2b4874f9fd970d97), was supposed to be https://github.com/Regalis11/Barotrauma/issues/9753

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/937eaf2243db745a5293ca4865a5d22e7734174f

**Comment by NilanthAnimosus** [comment]
Tested against dev branch commit https://github.com/Regalis11/Barotrauma-development/commit/f6ac4f7844d2814e53fb5f78e60f9ac7d8aca803

Pausing the client and reconnecting works fine. pausing the server and reconnecting seems ok with mods. Doing so during a level transition also had no issues in my tests, considering this fixed and closing.
