### ISSUE TITLE
Cannot drag window if in front of another window

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#9618]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Having two non-held windows or inventories open at the same time does not allow the window that is overlapping another window to be clicked and dragged.

### Reproduction steps

1. Link cabinet with fabricator
2. Enable show side-by-side
3. Open cabinet
4. Drag cabinet over fabricator window such that the drag bar overlaps the fabricator's inventory
5. Attempt to drag cabinet inventory

### Bug prevalence

Happens every now and then

### Version

Other

### -

0.19.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed by disallowing moving the UIs on top of each other https://github.com/Regalis11/Barotrauma/issues/9617
