### ISSUE TITLE
minor menu accessibility/QOL

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9632]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

- the submarine view menu (from info/tab menu-> submarine -> expand view) doesn't get closed by using [tab], though this does close the info menu itself. escape DOES close both the info menu and sub view menu at once for some reason. expected behaviour is for both of these keys to only close one layer of menu. (i.e., close the giant sub view and go back to submarine tab of the info menu)

- closing the info/tab menu with mouse can only be done by clicking the "info" button in the top left of the screen, which isn't part of the menu itself. there should be a button to close the menu?

- can't right click outside the tab menu area to close. not sure if a bug because this menu is some hybrid of gameplay (info menu includes character talents and sub info. most game UIs like health and containers and interactables can be closed with right clicking) and settings (it has details about the connected players metagame stuff, network, moderation options)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe. Closing.
