### ISSUE TITLE
AI and their own diving suit.

### ISSUE THREAD

**Issue by Reloadnet0Ashes** [Regalis11/Barotrauma#9641]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Disclaimer: I am unable to point out the cause of this since it randomly happened during my playing session on my friend's server. (Non-modding at all)

So, the AI crewmate picked up his Diving Suit to repair and filled out the hole in our ship, and so then, once we reached the station, I found that the bot has dropped his own diving suit into the ground of said station, making it incredibly difficult to restore them out. I thought it was just a coincidence, but on another station, but it still happened, so I was pretty sure that it was either a bug or just pure bad luck. For now, I label it as a bug. (Also, there was once a breach outside of the docking port, and so the AI endlessly tried to reach it out, making it stuck at the docking port forever until I reached out the Station. 
Sorry if this is actually just AI design or like, already pointed out bug, glad you read this!

### Reproduction steps

1. Having some part of the ship breached, AI suited themselves up in Diving Suit.
2. Arriving at the Station or Outpost, AI hasn't dropped their suit yet.
3. I don't know more.

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Hm, given the AI tends not to be able to pathfind from the station to the submarine and they tend to start within the station, I can picture them ending the round with a diving suit on them immediately dropping it into the outpost.

**Comment by Regalis11** [comment]
The suits the bots drop in the outpost should get automatically moved to the sub at the end of the round (see HumanAIController.HandleRelocation). I think we should verify that's still working as intended.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/c5ced73211d01ed01b27db6993a7817765d37807 and everything is fine with the diving suits getting relocated to the submarine after leaving.

I feel this issue may be more a question of design than a bug report, given the mention of restoring out the suits (I assume recharging the tanks inside them before leaving for a mission), to which the diving suits are not relocated in the same match of the submarine and nor do they attempt to path find to manually place them back when at the outpost, dropping them on the floor so they get stored back in the submarine.
