### ISSUE TITLE
Renamed bots disguised as old name

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#9649]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After renaming all the bots/AI crewmembers to short and simple names, to include after undocking, the bots wearing diving suits had their previous names. The IDs were updated to show that their names had changed. Issue occurs in both single player and multiplayer.

### Reproduction steps

1. Rename bot
2. Bot wears a diving suit
3. Bot is disguised as previous name for the bot

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.19.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Looks like this issue is likely due to the rename function (Shared CharacterInfo.cs line 1276 Rename(string newName) changes the ID card tag, but not the Item Component IDCard that keeps "Ownername" of the previous character, which presumably is what the disguise code is going off.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26323f8ba9a4503625840058b56ccd29307ce53d (reference incorrect ticket in the commit message)

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
