### ISSUE TITLE
[Dev version] A questionable feature in the ingame chat

### ISSUE THREAD

**Issue by BillCombs** [Regalis11/Barotrauma#965]
I know that this feature is likely just still WIP, but i don't know which parts of it are considered finished and which ones are not, so i am going to give my opinion regarding each part as if it was considered finished.
___

 The chat in the dev version has a feature that makes disguise also change player's name in chat.
While it might give traitors another interesting way to play the game, i feel like it would be abused more than used properly.

 Imagine a situation: player "A" kills player "B", hides their body, and then disguises as them. Now the player "A" has "B" player's name. They start using the ingame chat, using offensive words towards their crewmembers, making them mad, ruining "B"'s reputation. Later, "A" can just hide the card and walk around with their own name, pretending that they are not related to the situation in any way.  Since the player "B" is dead, they can't even defend themselves. Next time "B" spawns, they will likely get a lot of hate, be cuffed or killed, or even votekicked from the server, even though they did not do anything bad. They could try to explain the situation, but, depending on how mad the players are, they might not believe in "B"'s words or not even listen to him. The player "A" just gets away with ruining reputation of a person and offending other players.
 Another situation, that could happen, is some player offending other players and then pretending that somebody else took their card and said the offensive words.

 I feel like with a possibility of creating such situations, it would be possible for griefers to make a big part of the playerbase become hateful and distrustful towards each other, making it a lot harder to make friends and play the game as a team.

**Other problems with the feature:**
 The name isn't showing in the chat if the player has no card and has equipped a mask or a diving suit, which means that if somebody's card got stolen during a massive flood, it would be really hard for them to communicate with the rest of the crew without making it confusing and looking suspicious. 
 It also feels pretty weird to suddenly make other people fail to recognize your voice just because you lost your id card.
![-2018-dec-7-028](https://user-images.githubusercontent.com/38168249/49659038-eed73900-fa75-11e8-927a-4d219fd21c87.jpg)

 Female characters can somehow speak like if they were male, which, imho, is not making much sense, as it's very unlikely to happen in real life, because of how hard it is for one gender to mimic other gender's voice precisely.
 Overall, it's pretty questionable how a character is able to copy voice of any other character.
![-2018-dec-7-030](https://user-images.githubusercontent.com/38168249/49659040-ef6fcf80-fa75-11e8-845d-e33275927988.jpg)
___

 I personally don't feel that good about this feature. However, my opinion is currently mostly based on predictions. I hadn't had a chance to see the feature in action yet(since this version is not public yet). So i wouldn't mind seeing what others think about this feature. But at the moment i think the feature should be removed or at least be optional for servers and turned off by default.

**Comment by Regalis11** [comment]
This was actually not an intentional addition, but something I didn't take into account when refactoring the chat logic. I fully agree with your concerns and think this should be changed.
