### ISSUE TITLE
%ModDir% for modded creature textures doesn't always implicitly point to one's own mod's filepath

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#9650]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This issue is pretty hard to describe as it has occurred in other instances other than the one described in this post. I'm fairly certain that it only happens for creature textures and nothing else.

When you create a new character and define its textures within its ragdoll, you usually type your filepaths like this:
`%ModDir%/Characters/Crawler/crawler.png`

This means that the game has to look inside "ModDir" to then find the "crawler.png" file inside two other folders.
For pretty much everything else in the game, such as sounds or textures for items, %ModDir% on its own implicitly means `LocalMods/YourMod`, where YourMod is the name of your mod.

However for creature textures, it is often required to specify the name of your mod within %ModDir%, so that the filepath becomes like this:
`%ModDir:YourMod%/Characters/Crawler/crawler.png`

This would normally be necessary to reference files from other mods, but here it seems that it is necessary to specify the name of your own mod in order for certain things not to break. The things that can break vary a lot, but I managed to find a way to easily verify one problem in particular:
[Testcrawl.zip](https://github.com/Regalis11/Barotrauma/files/9200891/Testcrawl.zip)

This mod overrides the crawler character and changes its texture to something else, and its filepath looks like the one I put at the beginning of this post. If you were to then check out the "crawler_large" character in the character editor, you'd see that it's invisible, while you'd expect that it would just use the same texture as your overridden crawler, as it doesn't have a custom texture of its own like the "crawler_hatchling" character, which works properly.

To fix this, you need to include the name of your mod after ModDir where the overridden crawler's texture is defined:
`%ModDir:Testcrawl%/Characters/Crawler/crawler.png` 

The problem here is that you simply shouldn't have to type the name of your own mod for things to work properly, as %ModDir% on its own should mean that we're talking about your own mod already. At the very least, the practice of putting your mod's name after ModDir should be included in the official character modding guide, to reduce the amount of people running into problems because they didn't do so.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by shangjiaxuan** [comment]
Your sample yields "%ModDir/Characters/Crawler/crawler.png" for Texture attribute in ragdoll xml. Is that what you entered in character editor or is it saved incorrectly?

**Comment by shangjiaxuan** [comment]
Tested with edited "%ModDir%/Characters/Crawler/crawler.png", and current game 0.18.15 works.

**Comment by shangjiaxuan** [comment]
Edit: your problem shouldn't happen with the example you are giving, but instead with a combination of:
Character has `usehuskappendage=true`, so the ragdoll evaluates to the non-husked species (seems like hack?)
Then the character prefab is different from the ragdoll evaluated xml location, and sprite path will evaluate to the husked character's location but the non-husked ragdoll file content. This is what I just encountered testing my pr to add partial inheritance, and fixed.

Location to look at:
`Limb.cs` in `ClientSource` lines 476-497
```
        private string GetSpritePath(ContentXElement element, SpriteParams spriteParams, ref string path)
        {
            if (path == null)
            {
                if (spriteParams != null)
                {
                    ContentPath texturePath =
                        character.Params.VariantFile?.Root?.GetAttributeContentPath("texture", character.Prefab.ContentPackage)
                        ?? ContentPath.FromRaw(character.Prefab.ContentPackage, spriteParams.GetTexturePath());
                    path = GetSpritePath(texturePath);
                }
                else
                {
                    ContentPath texturePath = element.GetAttributeContentPath("texture");
                    texturePath = texturePath.IsNullOrWhiteSpace()
                        ? ContentPath.FromRaw(character.Prefab.ContentPackage, ragdoll.RagdollParams.Texture)
                        : texturePath;
                    path = GetSpritePath(texturePath);
                }
            }
            return path;
        }
```
In shared source `Character.cs` lines 1245-1249:
```
                if (ragdollParams == null && prefab.VariantOf == null)
                {
                    Identifier name = Params.UseHuskAppendage ? nonHuskedSpeciesName : speciesName;
                    ragdollParams = IsHumanoid ? RagdollParams.GetDefaultRagdollParams<HumanRagdollParams>(name) : RagdollParams.GetDefaultRagdollParams<FishRagdollParams>(name) as RagdollParams;
                }
```
The previous reference are from 0.18.15, but it seems current dev branch 0.19.3 still have this problem.

**Comment by shangjiaxuan** [comment]
> > Tested with edited "%ModDir%/Characters/Crawler/crawler.png", and current game 0.18.15 works.
> 
> Not sure how this typo managed to slip in, thanks for pointing it out! Either way, I fixed it on my own version of the mod, and it is still causing issues for me. The crawler_large variant of the crawler, which has been overridden, is showing up as invisible, accompanied by console error messages.

Ahh, so you mean Crawler_Large, not Crawler itself. This is because Crawler Large in vanilla inherits from Crawler, and Crawler is  from your package, instead of the package where Crawler large is from (Vanilla). And the current game only takes into account the current character's content package, and that is Vanilla for Crawler Large, and evaluating your xml literally will result in Vanilla's content directory.

This problem has been addressed in my pr that allows partial override (https://github.com/Regalis11/Barotrauma/pull/9779/commits/f7e4e60d4c117c96e9698110caf5f746f54e764f), but that pr is WIP and don't know when devs would merge that.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9cb0e63526c92f11ac27956cf95838ecafe4effb (commit in our private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
