### ISSUE TITLE
Handcuffs sprite shines through the character

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9653]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Handcuffs are placed on both hands but a second bracelet is placed on the hand behind the character, but both bracelets are placed in front of the character.
![Image 001_19-52](https://user-images.githubusercontent.com/93348499/181305100-e9f4f89b-b304-4372-a97c-7266aa4f8b98.png)

### Reproduction steps

Handcuff the character and take him somewhere else. Look at his hands.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/327b745a93faaeb3d78dc0d5e06955c4f9e18b97

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
