### ISSUE TITLE
Unwired pump in city dock

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#9659]
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/59519434/181870286-9f4abb97-d6a4-4de8-b118-c621bde77c9c.png)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This pump does seem to be wired to the water detector at least in v0.19.4.0 (not sure if it was fixed at some point). There is no power wire, but it's not necessary because the pump is set to work without power.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
