### ISSUE TITLE
can grab UI box edge and wire at the same time in wiring modes

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9660]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

while rewiring, i was able to grab the wire and the window edge at the same time, resulting in both window and the wire bieng moved around.

expectation was to only grab the wire

### Reproduction steps

1. wiring mode (editor, but i expect it to be also in regular mode w/ a character etc)
2. have a wire between 2 components
3. click on wire near the edge of the wiring menu

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.19.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/9b4a0fd20bbb09340e396e130f928818cb441fa5

**Comment by Rokvach** [comment]
I was still able to reproduce this, if you select the wire where there's an icon is it will select both the wire and the window
![image](https://user-images.githubusercontent.com/7299826/184653489-ecb3da2a-e4c1-4e97-831c-e6af77d1f75e.png)
![image](https://user-images.githubusercontent.com/7299826/184653543-7bd4848b-3906-4070-9c6d-83431f7428d4.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2b2c18327ec4a1499ddb45dd775f44cef8c1668c

**Comment by Rokvach** [comment]
Tested, working correctly now, closing.
