### ISSUE TITLE
Graduation Ceremony additional 10% maximum health doesn't have a cap on how much health it can give you

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9661]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Graduation Ceremony assistant talent can basically make you immortal if you have lots of experience, the talent should have a cap on how much maximum health it can give you.

### Reproduction steps

1. Spawn as assistant
2. Give yourself an insane amount of experience
3. Pick the Graduation Ceremony talent
4. Watch that you are basically immortal due to your large amount of health

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Thanks for the report! tested on 0.18.15.1.

I found that if you fill all three of the assistants tree's, the final max vitality will go from 100 to 245 max vitality (+15 from one of the Apprenticeship Talent in the jack of all trades tree)

without that talent, this talent alone with all skill picks raises vitality from 100 to 230.

With even more points over the max you can spend (Beyond the "All Talents Unlocked" I managed to raise the vitality to 260. so this does indeed allow one to forever gain vitality with enough experience gains.

**Comment by JeroonBosch** [comment]
Graduation Ceremony is reworked, there's no infinite health scaling anymore
