### ISSUE TITLE
[Balance] Black Molochs' EMP radius

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9662]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The black moloch EMP attack radius is 4000

```xml
<Explosion range="4000" force="0" underwaterbubble="false" flames="false" smoke="false" sparks="false" flash="true" shockwave="true" camerashake="0" empstrength="0.5" flashrange="2000" flashduration="0.1" applyFireEffects="false"/>
```

This covers the size of an entire entire Berilia
![image](https://user-images.githubusercontent.com/73229309/182014453-f7820e48-cab0-471b-93d7-e9c820dab09a.png)

Black Molochs already have increased health over regular molochs too.

I get that they are late-game enemies but, having to repair several dozen electrical systems across the entire sub while dumping several struggling to keep your guns powered is not very enjoyable. It turns Black Moloch encounters into minutes long sub-humping sessions.

At least reduce the EMP range to something more reasonable like 1000 so it doesn't fry the entire ship all the time:
![image](https://user-images.githubusercontent.com/73229309/182014588-597a19bb-b3ab-4bf5-918b-af8593b0f783.png)

### Version

0.18.15.0

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/615de1e2c64e44b59093af9cce23de4e496189c1

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
