### ISSUE TITLE
small pumps are not visible on the typhoon 1 preview in the lobby

### ISSUE THREAD

**Issue by Brillcrafter** [Regalis11/Barotrauma#9664]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I should have been able to see the small pumps in expanded preview for the typhoon in the game lobby

### Reproduction steps

1. load up a lobby
2. select the typhon
3. open the expanded preview
4. check for the small pumps

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Which pumps? These ones seem to be visible at least

![image](https://user-images.githubusercontent.com/14351070/185142421-056e14ab-b1b6-4963-b5ab-6000c25d99db.png)

**Comment by Regalis11** [comment]
No known steps to repro, closing
