### ISSUE TITLE
Typhon2 bottom left turret bad wires

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9666]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Someone dragged the turret and forgot about wires 

![image](https://user-images.githubusercontent.com/73229309/182025610-9fa644d9-2e94-43ac-a7d6-825fdcde76a1.png)

### Version

0.18.15.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4642d6fa8d4d9dbe110bdff36dc508c3e7ffaa76

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by Regalis11** [comment]
Had to redo the fix because it got overwritten by a merge https://github.com/Regalis11/Barotrauma-development/commit/6821ad3b988b374bbac7c545764cf3c3d4f81040

**Comment by Rokvach** [comment]
No issues again, closing.
