### ISSUE TITLE
Gene Harvester and Deep Sea Slayer work on Outposts, Pirates and Bandits

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9672]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Gene Harvester and Deep Sea Slayer work on pirates and bandits
All humans, including Outpost dwellers, Pirates and Bandits can drop genes and alien materials, even inside their own submarine.

![image](https://user-images.githubusercontent.com/73229309/182430825-5ae68546-5a27-49de-a888-41994e5146ac.png)

Probably caused by the "Enemy" target type

```xml
    <AbilityGroupEffect abilityeffecttype="OnCrewKillCharacter">
      <Conditions>
        <AbilityConditionServerRandom randomchance="0.35" />
        <AbilityConditionCharacter targettype="Enemy,Monster" />
        <AbilityConditionGeneHarvester />
      </Conditions>
```
```xml
    <AbilityGroupEffect abilityeffecttype="OnKillCharacter">
      <Conditions>
        <AbilityConditionCharacter targettype="Enemy,Monster" />
        <AbilityConditionInFriendlySubmarine invert="true" />
        <AbilityConditionServerRandom randomchance="0.4" />
      </Conditions>
```

### Version

0.18.15.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f8516c4da14999707a6517f64f7177f985be9cdf

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
