### ISSUE TITLE
Wiring mode bug

### ISSUE THREAD

**Issue by Napalmolive** [Regalis11/Barotrauma#968]
- [Yes] I have searched the issue tracker to check if the issue has already been reported.

Description
After the last update in the game, it seems that the wiring mod is broken. I opened "the blind carp" vanilla shuttle and with a screwdriver in my hand, tried to open some of the components (buttons, "NOT"/"OR"/"AND" components, pumps and etc), but they were not available. The game required a screwdriver (which I already had in my hand) and the table was red. However, some other components worked fine.

Version of the game: Vanilla v0.8.2.2 
OS: Windows 7.

![bug](https://user-images.githubusercontent.com/45718367/49689167-55b82900-fb2e-11e8-896a-525b72d7953c.jpg)

**Comment by BillCombs** [comment]
I am pretty sure vanilla shuttles have most of the important parts of the wiring locked to prevent players from griefing them. 
 See the "Equipped required" parameter. The unlocked one has names or tags of the required tools,
![-2018-dec-8-005](https://user-images.githubusercontent.com/38168249/49689420-89597a00-fb53-11e8-93fc-1d85ed96806a.jpg)
 But the locked one just has a "locked" tag. That prevents you from interacting with its wiring panel using a screwdriver. You have to change the tags back to names of the required tools(Screwdriver) to interact with the wiring panel.
![-2018-dec-8-003](https://user-images.githubusercontent.com/38168249/49689421-89597a00-fb53-11e8-9f83-87056415a594.jpg)
 This way to lock the wiring panels was used before the addition of the checkmark option "Locked".
 The checkmark one allows you to make the wiring panels be locked during the actual gameplay, but also be freely editable in the sub editor.

**Comment by Regalis11** [comment]
Yep, this is intentional.
