### ISSUE TITLE
Mineral items create lighting effect at the location where they are stored (locker/crate)

### ISSUE THREAD

**Issue by chen27890007** [Regalis11/Barotrauma#9683]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Mineral items create lighting effect at the location where they are stored (locker/crate). 
In particular, there were 25 pieces of titanite stored in a crate which is placed on a shelf. That particular spot has a light aura around it. The intensity of that light is very high, so probably there were 25 light source stacked at the same position. 

### Reproduction steps

Put a lot of same minerals (e.g. titanite) in a crate, save and reload game. 

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not find a way to reproduce this. Tested in 2 different ways:

1. Place a crate in the sub editor
2. Fill it with minerals
3. Save and reload the sub
4. The lights aren't showing in either the editor view or in-game

And

1. Mine some minerals in the singleplayer campaign
2. Place them in a crate inside the sub
3. Enter the next level
4. The lights aren't showing
5. Save and reload, the lights still aren't showing

Can you think of what you might've done differently when this occurred? Did it happen in multiplayer or singleplayer? And to be sure, you were playing v0.18.15.0 in the default branch on Steam, not the Unstable version (v0.19.0.0, which reportedly has a similar issue https://github.com/Regalis11/Barotrauma/issues/9701)?

**Comment by Regalis11** [comment]
No known steps to repro, closing. I suspect this happened in the Unstable version, [which recently had this exact issue](https://github.com/Regalis11/Barotrauma/issues/9701).
