### ISSUE TITLE
Seated bots ignore orders

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#9685]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots/AI will ignore all orders and subobjectives (fix leaks, follow, repair systems, find safety) and continue to stay seated in chairs, even if they start drowning.

### Reproduction steps

1. Have submarine with chair
2. Give orders
3. Wait for the bot to sit
4. Have something that would make them follow their orders
5. Watch them sit

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.19.0.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7803eef38487d7db40412b1a990f165b461d8f4a

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue. Working correctly, closing.
