### ISSUE TITLE
Alien_VaultModule2 Motion sensor puzzle not working

### ISSUE THREAD

**Issue by Yoshbie** [Regalis11/Barotrauma#9688]
The door in Alien_VaultModule2 doesn't open through what I can only imagine is the intended way of disabling the motion sensor since the motion sensor does not have a false output of 1 and nothing else controls the door. This means that the only way into the alien artifact chamber is by forcing the door open. 

![image](https://user-images.githubusercontent.com/30814255/183558477-7e936607-6168-4e28-8626-b0d94ae7defb.png)
relay component connecting the terminal to the sensor and the two light nodes.

![image](https://user-images.githubusercontent.com/30814255/183558875-78066235-4b42-4912-9b23-802a8b0ef928.png)
No false output meaning that signal_in_1 never tells the hatch to open, only close

Suggested fixes: 
1. Make the motion sensor's false output 1. If there is no motion or you disable the sensor through the terminal, the door remains open
2. Make the hatch open by default. The door is open, but if anybody gets too close, the door is closed and cannot be reopened except with a crowbar/plasma cutter. This one makes the door puzzle more punishing and a trap rather than a convoluted way to just make the terminal control the hatch indirectly.

**Comment by danielasteljoki** [comment]
Fixed in bbfe871

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
