### ISSUE TITLE
In the TerminalComponent SyncHistory() doesn't work properly

### ISSUE THREAD

**Issue by CaptainSqrBeard** [Regalis11/Barotrauma#9690]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

https://github.com/Regalis11/Barotrauma/blob/2e2663a175b28800acc565745a70e3225ab5eafe/Barotrauma/BarotraumaServer/ServerSource/Items/Components/Signal/Terminal.cs#L53

This method should synchronize message history with clients. But in real it doesn't. It just resends entire history above already existing messages. 

This is how it looks:
![terminal](https://user-images.githubusercontent.com/56765288/183622584-0b0c37fc-9c1c-4750-bc42-2eeed2db0ff7.png)

### Reproduction steps

1. Get any item with Terminal component (I used "handheldterminal")
2. Write some messages in it
3. Call SyncHistory() method
4. There they are

### Bug prevalence

Happens regularly

### Version

Other

### -

0.18.15.0 with server-side LuaForBarotrauma

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is the intended behavior of the method. The vanilla game only calls it once after initializing the terminal, but if you want to use it to "resync" the history on the fly, you need to make it skip over lines that have already been added.

**Comment by CaptainSqrBeard** [comment]
Well it can work if i will not clear messages from terminal. I don't see any possibility to sync cleared messages, except sending 60 empty messages to hide previous one behind limit

**Comment by Regalis11** [comment]
> I don't see any possibility to sync cleared messages, except sending 60 empty messages to hide previous one behind limit

Personally the way I would implement this is by only making the server send the messages that _haven't been sent yet_, not by syncing cleared messages.
