### ISSUE TITLE
[Unstable] Cannot interact with 'devices' while in a chair.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9698]
- Build Unstable 0.19.0.0 Windows
- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Description
Changelog entry "Allow using devices while on a ladder or sitting on a chair." - which, it seems simply does not work.
Judging by issue #9655 as well, this seems like something went wrong that is definitely not part of the intended behavior.

### Reproduction steps
- Slap a chair on your dugong
- Try to sit in a chair and interact with the nav terminal, or press buttons, or use the reactor.
- Character will instead stand-up from the chair before you can interact, functionally identical to the 'old behavior'.

**Comment by Regalis11** [comment]
I could not reproduce this. LMB (the default key to select a device) doesn't make the character stand up from the chair. Are you using some kind of non-default keybinds by any chance?

**Comment by Regalis11** [comment]
No known steps to repro, closing
