### ISSUE TITLE
Unconscious characters skip requiring oxygen and taking bleed damage/recovering from bleed

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#97]
A character who is Unconscious due to health but still has positive oxygen no longer uses the code required to breathe from a hull / suit, and will neither gain or lose oxygen as oxygen is only lost while unconscious if it is below 0%.

Edit: Additionally worth noting if a player is suffocating but still has positive health they will skip bleed damage and also skip natural bleed recovery.

Not sure if this behavior is preferred or considered a bug/unintended feature.

**Comment by yaelatletl** [comment]
It also happens with characters using ragdoll mode

**Comment by NilanthAnimosus** [comment]
That would imply this could also effect stunned characters.

as a note - this does not mean the drain from status effects - such as a diving mask with welding fuel, but specifically breathing related gains/drains.

**Comment by Crystalwarrior** [comment]
I've seen the code that handles this and found it to be a weird exception.
Pretty sure bleeding must be affected as well, will have to look into it.

**Comment by NilanthAnimosus** [comment]
Bleeding is sort of effected and not. if your health is under 0 you will take either 0.5% health damage OR bleeding if its higher, otherwise the bleed damage is indeed skipped yes.

**Comment by Regalis11** [comment]
Fixed in dde320b
