### ISSUE TITLE
[ Unstable ] Mineral/Plant light-sources stay after mined

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#9701]
- Build Unstable 0.19.0.0 Windows
- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Description
The glow emitted from mineral & plant resources in the level stays even after the item is detached.
Possibly similar item-update issue as #9683

### Reproduction steps
- Mine minerals or detach plants
- Light effect persists after the mineral/plant is detached and picked up
- End up with a bunch of random glow coming from nothing

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3ba613eb5206fc0800237887282a95bdbc2b10d0

**Comment by Rokvach** [comment]
Tested, light is correctly removed from level wall once the item has been looted,  working correctly. Closing.
