### ISSUE TITLE
Floating point inaccuracy causes RequiredItem "Condition" check to fail

### ISSUE THREAD

**Issue by notpeelz** [Regalis11/Barotrauma#9703]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Given an item with this recipe:

```xml
<Fabricate suitablefabricators="fabricator" requiredtime="10">
  <RequiredSkill identifier="medical" level="30"/>
  <RequiredItem identifier="plastic"/>
  <RequiredItem identifier="rubber"/>
  <RequiredItem identifier="oxygentank"/>
</Fabricate>
```

It's currently impossible to craft it with an oxygen tank that was refilled in the oxygen generator, due to floating point inaccuracy.

![image](https://user-images.githubusercontent.com/920910/184464990-3f2a7cb7-5ea7-430e-b2fc-90365adc83e1.png)

This can be fixed by comparing the two values with a margin of error (epsilon).
![image](https://user-images.githubusercontent.com/920910/184465298-fe9d5e3b-9867-45d0-84b0-8003d491b215.png)

Relevant lines: https://github.com/Regalis11/Barotrauma/blob/b17019db95865cc0551aa3a5a967e885a7f8b50d/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Fabricator.cs#L605-L617

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bb198cc0ba070357eebd842988f0c68779b58629

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/17a4e29619e49adc0a329be654296cf8f8ddc5d6, works correctly. closing.

Tested in multiplayer by using recharged oxygen tanks with a custom recipe with no observable issues.

Note: this is inside the current unstable build 0.19.1.0
