### ISSUE TITLE
Mission to a passageway

### ISSUE THREAD

**Issue by janosdebugs** [Regalis11/Barotrauma#9707]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I picked up two missions at the very first station in my game (easy mode) and it requested me to transport cargo and passengers to the next way point. This waypoint was the only option to go, and it was a passageway. Since I cannot dock at a passageway, I cannot complete the mission.

Map segment I'm on:

![Screenshot_20220813_202218](https://user-images.githubusercontent.com/86970079/184506192-5d685f5e-f1d6-461d-960e-dc6a75e88fbb.png)

Missions:

![Screenshot_20220813_202233](https://user-images.githubusercontent.com/86970079/184506194-33bb7f50-71e0-4aad-8e6a-3eb885079c4d.png)

### Reproduction steps

1. Start a game with seed `gBRZGwRQ`.
2. Pick up the missions from the station commander.
3. Travel to next waypoint (Onga Linea)

### Bug prevalence

Happens every now and then

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report!

Cargo and transport missions leading to empty locations are [a known issue](https://github.com/Regalis11/Barotrauma/issues/7497), but they should still be possible to complete: you just need to make it to the destination, and it doesn't matter if there's an outpost there or not. I gave this a test and both of the missions seemed to complete successfully when I arrived in Onga Linea:
![image](https://user-images.githubusercontent.com/14351070/184598841-aa6731f4-acb3-40c9-930d-37d8f3c08afe.png)
