### ISSUE TITLE
Talent, Traveling Salesman, is not working

### ISSUE THREAD

**Issue by BigMike3180** [Regalis11/Barotrauma#9720]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The perk traveling salesman no longer provides the 4 items on sale. Only the default one item is on sale. The 500 mks is also not added upon reaching a new station.

### Reproduction steps

The only "mod" I used was a custom-edited vanilla sub.

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
I think I figured out what is happening. If you get to a new station (first time only) you get the 500 marks, but you do not get the extra sales. If you revisit and older station you have been to before you do not get the money, but you do get the extra sales.

Its like someone used an if/else statement when they shouldn't have.

**Comment by BigMike3180** [comment]
Ok that sounds right, because the play through where I was having this
issue I wasn’t getting sales until they would “randomly” pop up, probably
revisiting the station and I didn’t connect the dots at the time. I also
noticed sales DO appear for new spawning stations.

Keep up the good work, love the game!
-Michael

**Comment by JeroonBosch** [comment]
No longer has the 500Mk gained upon reaching a new station, but the 4 extra items on sale effect still exists in this talent in the rework.

Likely the extra sales bug is still relevant.

**Comment by 3e849f2e5c** [comment]
Mitigated the issue in https://github.com/Regalis11/Barotrauma-development/commit/4500de7d2a23f38e17a532668b051b2214281b98

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/2b57faa07493e732f98261ead832ba904168f57b

Each player/AI with the talent adds additional (+3) instances of store deals. Is this intended? Otherwise the fixes/mitigation does work.

**Comment by 3e849f2e5c** [comment]
Do we want multiple captains having the same talent stack? @JeroonBosch

**Comment by JeroonBosch** [comment]
No, I think stacking doesn't make sense here @3e849f2e5c

**Comment by 3e849f2e5c** [comment]
Adjusted in https://github.com/Regalis11/Barotrauma-development/commit/db7a7f0895d5b94a29b6ca25dcf8f8595cc908ae

**Comment by NilanthAnimosus** [comment]
Tested against talent-fixes-7 commit https://github.com/Regalis11/Barotrauma-development/commit/0b2d49ccd119c0e932389f71cf6fa7ab6d7680f0 no issues found, closing.
