### ISSUE TITLE
If the mod does not have localised content for the language you have set, the name and description of the afflictions of the mod are not shown.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9722]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I choose one mod Neurotrauma to claim this issue.

As we can see Neurotrauma, this mod support these language:
![image](https://user-images.githubusercontent.com/44423036/185090542-0e07e9df-6afc-4713-ae92-4c4c8e4e2a5f.png)
if you choose language as "English", will work properly, you can see the name and description of the afflictions:
![image](https://user-images.githubusercontent.com/44423036/185091433-614889b8-5305-49b2-a96e-c921e59d1bef.png)

if you choose language as "Simplified Chinese", will be this:
![image](https://user-images.githubusercontent.com/44423036/185091137-35204eb3-e718-4f91-a1ca-bf608279d0cf.png)

I think it should show English texts, rather than nothing. Like items.
![image](https://user-images.githubusercontent.com/44423036/185092608-b783fa0a-34c9-434d-a21c-00f062584f62.png)

### Reproduction steps

1.load game with Neurotrauma mod 
2.do something and get Neurotrauma-specific afflictions
3.see these afflictions in English
4.change language to Simplified Chinese (even if you don't know this language), see these afflictions again

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/75d82b92b1fb7835ddb640250140b961100cc607

**Comment by Regalis11** [comment]
Reference incorrect ticket in the https://github.com/Regalis11/Barotrauma-development/commit/26323f8ba9a4503625840058b56ccd29307ce53d commit message, was supposed to be https://github.com/regalis11/barotrauma/issues/9649

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/17a4e29619e49adc0a329be654296cf8f8ddc5d6, works correctly. closing.

Tested using neurotrauma setting the language to several which the mod did not have, all afflictions were shown in English as a correct fallback over nothing including when setting before being in game (Just in case)

Note: this is inside the current unstable build 0.19.1.0
