### ISSUE TITLE
Bug: line of sight errors with partially overlapping LOS for character and ship weapons.

### ISSUE THREAD

**Issue by tjbiel85** [Regalis11/Barotrauma#9724]
The game appears to be determining what can be seen through certain ship weapons (periscopes) based on what should not be visible to the character using them according to that player character's visibility on the boat.

It results in things like this, where the wide firing arc of the rear coilgun is significantly obscured based on where the character aboard the ship would have shadows, if they were partially seeing through the body of the ship.

![image](https://user-images.githubusercontent.com/70725621/185699699-29fef682-ef02-4ebb-8b99-2f8b0100dbc8.png)

It appears to be related to the line of sight effect options. When this is changed from "transparent" to "none" the issue resolves, though that of course makes the interior of a boat visible from the outside as well.

![image](https://user-images.githubusercontent.com/70725621/185525053-8c32f501-81f7-4492-936d-fc21671f665f.png)
![image](https://user-images.githubusercontent.com/70725621/185525075-3878e59d-930c-4d06-bbbb-c407672d0936.png)
![image](https://user-images.githubusercontent.com/70725621/185525086-8ebd6fdb-b501-4b45-9057-badea9226462.png)

I have tried to adjust the positioning and layer depth of walls and weapons to solve this, but to no avail. The boat used to generate these images is a custom small attack sub (Lavern) included in this issue posting.

[Laverne.zip](https://github.com/Regalis11/Barotrauma/files/9378650/Laverne.zip)

**Edited: First picture was awfully dark and hard to see on some monitors. Brightened it a bit to show the affected line of sight vectors.

**Comment by Regalis11** [comment]
Thank you for the report, and sorry for the super late reply!

The issue here seems to actually be that the coilgun is placed partially inside a wall. Moving it slightly outwards should fix the issue.
