### ISSUE TITLE
[Unstable] Selecting an item in editor menu will automatically place it down

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9725]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Selecting items in the editor menu automatically places them

### Reproduction steps

1. Open sub editor
2. Select a Coilgun in the entity menu
3. Collapse the menu
4. Coilgun appeared where you clicked on the menu

### Version

Unstable V0.19.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8cfb29c69bb98c9fd2faf3a9df282b658d2ecc1e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
