### ISSUE TITLE
[Unstable] Flares/Glowsticks are turned on by default on startup

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9728]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Flares are on by default on startup and lose durability (+ make a lot of noise)

![image](https://user-images.githubusercontent.com/73229309/185675925-649f8dc3-f6c3-4906-87af-969849a8e092.png)

**Comment by ConnorsSilverpaws** [comment]
Occurs on autofilled, spawnitem (inventory and cursor), or directly placed when in submarine editor's test mode. Issue also includes item Alien Flare.
Does not occur in single-player/multiplayer campaign/mission modes when autofilled, using spawnitem, or when purchased.

**Comment by ConnorsSilverpaws** [comment]
Issue also occurring during campaign after docking to a station for flares/glowsticks/alienflares in cabinets and crates, but did not affect player inventory.

**Comment by Regalis11** [comment]
Closing in favor https://github.com/Regalis11/Barotrauma/issues/9739
