### ISSUE TITLE
"Transfer Items" Breaks Topside Mounted Shuttles on Modded Subs:

### ISSUE THREAD

**Issue by aeldred28** [Regalis11/Barotrauma#9730]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

--This issue can be replicated/observed in the mod "Community Curated Subs" (https://steamcommunity.com/sharedfiles/filedetails/?id=2847239902)" --

When players buy a new sub from an outpost and leave, any shuttles that were mounted on the top of the sub will attempt to mount from the bottom. This only happens when buying a sub with "transfer items" checked, and NOT when starting a fresh round or when testing in the editor.

!!! This issue only occurs when "Transfer Items" has been selected. Otherwise the shuttles will mount as they should. !!!

The shuttle/sub docking parts were also marked correctly as "Top" and "Bottom" respectively. Choosing a "Main Dock" doesn't help either. 

![image](https://user-images.githubusercontent.com/75105816/185679494-cff0d489-c99d-4221-855b-b4f82651b51a.png)
![image](https://user-images.githubusercontent.com/75105816/185681080-cb3da034-bbf4-4a11-a5c7-a64f18d7919c.png)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/47332877eb38e9ce97ab4aacedd3904582beec2f

**Comment by Regalis11** [comment]
Seems that the fix caused shuttles with [ForceDockingDirection not set to spawn undocked](https://github.com/Regalis11/Barotrauma/issues/9756), fixed in https://github.com/Regalis11/Barotrauma-development/commit/c864d04488f6aeb8ff84678a1cd366760f50e711

**Comment by Rokvach** [comment]
The attached sub is in the correct position now, but it isn't attached to the main sub

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e081e28f-52a2-4dc8-b17b-66b582cfd735)

**Comment by Regalis11** [comment]
Couldn't repro. Which branch/commit did you test this on? 
![image](https://user-images.githubusercontent.com/14351070/187417576-270374ee-0f2b-4e5d-a006-6ad7c5c5a1ea.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6ac4f7844d2814e53fb5f78e60f9ac7d8aca803

Since this changes the logic for loading linked subs, I'll reopen https://github.com/Regalis11/Barotrauma/issues/9309 and https://github.com/Regalis11/Barotrauma/issues/9172: we should ensure those didn't reappear

**Comment by aeldred28** [comment]
> 

I should also mention (perhaps in a new issue thread) that all/most of these subs are marked as "Manually Outfitted" but they receive starting crates regardless in both MP/SP. 

_Additionally I'd like to thank the team for investigating this topic so quickly._

**Comment by Rokvach** [comment]
Tested, this is now working correctly, closing.
