### ISSUE TITLE
deconstructor shows contents of the item about to be deconstructed

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#9733]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you put an item container with items in it or magazines for any gun, the deconstructor will show the items inside of such item container or the ammunition in such magazines.
![image](https://user-images.githubusercontent.com/55637865/185702834-119136de-7db7-431d-9744-0431b595f784.png)

### Reproduction steps

put thingy with things in it in the deconstructor

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.19.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1b6bfd2b12ef111de33fa2e591ad79497410cf57

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
