### ISSUE TITLE
Misplaced red light component on Orca 2

### ISSUE THREAD

**Issue by Koku0** [Regalis11/Barotrauma#9735]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Misplaced red light component on the Orca 2 sub.
In the top left of the sub, a red emergency light component is floating, attached to nothing.

### Reproduction steps

1. Load up Orca 2 in the Sub Editor on the Unstable build.

### Bug prevalence

Happens every time I play

### Version

Other

### -

Unstable: 0.19.1.0

### Which operating system did you encounter this bug on?

Windows

**Comment by danielasteljoki** [comment]
Fixed in 11404e1

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
