### ISSUE TITLE
Insurance policy money does not add to the bank and can wipe the whole bank

### ISSUE THREAD

**Issue by ironic-and-dead** [Regalis11/Barotrauma#9737]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When an assistant dies in a multiplayer game after obtaining the skill insurance policy, the payout for the dead person is on their wallet. However if this money is not moved out from a dead persons wallet by someone who can use the bank, When the submarine docks at a station this money is removed from the game and is not retrievable.

Also when a person is dead, their wallet cannot then be transferred back to the bank. If a banker accidentally transferred money to a dead person/assistant with the talent insurance policy, then whatever was transferred is lost, resulting in the bank being completely lost. 

### Reproduction steps

To reproduce we have completed some missions whilst having assistant with the talent.
They then die to crush pressure
Then dock at the station and the money disappears. 
Also tested on giving assistant money and seeing the bank disappear. 

### Bug prevalence

Happens every time I play

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
not a game bug/crash report
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/59a0df2e64107cdb1237d0e959209c368d1b26bc

**Comment by Rokvach** [comment]
Tested, when a assistant dies with the talent and the money is automatically deposited to the bank from the talent, the money that is on the assistants wallet is left on the body, so this is working correctly. Closing.
