### ISSUE TITLE
[UNSTABLE] Light components turn on themselves after the start of the round

### ISSUE THREAD

**Issue by AbyssBeast09** [Regalis11/Barotrauma#9739]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

 Light components turn on themselves after the start of the round

### Reproduction steps

1. Turn off a "Is On" function on lamp
2. Start submarine test/round 

### Bug prevalence

Happens regularly

### Version

0.19.1.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ConnorsSilverpaws** [comment]
Might be related: Was also seeing Camel's Emergency Siren toggling on/off when docking/undocking for just the light but not for sound.

**Comment by ubertpendragon** [comment]
And flares!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a8f7d64137cf9e38fc900e9577c239d9069c020

**Comment by SirNightKnight** [comment]
Also welding tools

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
