### ISSUE TITLE
Server list gives false ip when my server is clicked on

### ISSUE THREAD

**Issue by Billsofat** [Regalis11/Barotrauma#974]
This has only started happening recently. When I try to host a server, dedicated or in-game, and my server is clicked on in the list, the game picks up a totally weird ip that's not mine- as far as I can tell, it doesn't exist anywhere. Trying to join fails, however, if my real ip is manually entered, it connects fine. I'm not using any sort of vpn or anything.

The port it gives on the false ip, however, is correct.
False ip: 242.120.94.64
My real ip: 108.201.177.116

It should also be noted that I can join other server in the list. Other people get the same false ip from mine too, not just me.

**Comment by Jules189** [comment]
I am also having this issue, and was able to host servers normally in the past.

**Comment by Regalis11** [comment]
Seems to only be an issue in the legacy version, closing this as the legacy version is not supported anymore
