### ISSUE TITLE
Double coilgun doesn't play a sound on every shot

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9743]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Essentially the same issue as https://github.com/Regalis11/Barotrauma/issues/9489: the double coilgun has such a high firing rate that it exhausts the available audio channels.

### Reproduction steps

Fire continuously with the double coilgun

### Bug prevalence

Happens every time I play

### Version

0.19.1.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/35757647f923f6d10e39c9dcea0d44859626f889

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
