### ISSUE TITLE
Weapon skill gain for shooting enemies is too fast?

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9747]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You gain weapon skill by dealing damage to enemies (1 point for 70 health?)

Killing a Hammerhead gives 5 weapon skill
Killing a Moloch gives 16 weapon skill

With talents:
![image](https://user-images.githubusercontent.com/73229309/186098013-4d77d859-2320-47ee-8168-43d63c9bc190.png)

That's a lot

**Comment by Regalis11** [comment]
The amount of weapon skill you gain is relative to the damage done to the enemy, so in theory a large number of sub-projectiles shouldn't make it easier to gain skills. I gave this a quick test and couldn't spot anything unusual: the skill increase I got by killing a hammerhead with the flak cannon was the same as when I killed it with a coilgun.

**Comment by ubertpendragon** [comment]
You're right, I probably never paid attention while actually playing and was surprised to get as much as 5 weapon skill on shooting a single Hammerhead. Killing a Moloch got me 16 weapon skill.

It seems a little crazy in retrospect; the game will spawn several waves of them as early as cold caverns.
