### ISSUE TITLE
FABRICATOR BUG -BAROTRAUMA-

### ISSUE THREAD

**Issue by FireKingExtreme** [Regalis11/Barotrauma#9749]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

whenever i used the fabricator the FPS tanks, this isnt always the case, im not sure why this happens.
from 60 fps to 30 fps.

### Bug prevalence

Happens every now and then

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does this happen with a fabricator linked to a container with lots of items inside it? What kind of mods are you using?

I suspect this may be related to, or the same issue as https://github.com/Regalis11/Barotrauma/issues/9284
