### ISSUE TITLE
Waiting to response at a station hurt game play

### ISSUE THREAD

**Issue by jstiled** [Regalis11/Barotrauma#9750]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When a new place is forced to wait at a station while a group is starting to play it creates a negative game play for playesr

### Reproduction steps

1. Have life
2. Put children to bed
3. force to wait at a station
4. ....
5. Dislike game for waiting during a trivial part of the game. 

### Bug prevalence

Happens every time I play

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Pls help
```

**Comment by Regalis11** [comment]
Thank you for the report!

I'm not entirely sure what you mean, what response do you need to wait? Do you mean waiting at the station before you can respawn?

**Comment by Krzeszny** [comment]
I think @jstiled meant that players trend to plod on when docked to a station instead of going on the next mission, which is boring for those who don't have anything to do. This is mostly a player issue, but could be alleviated by introducing some kind of **time-based docking fee**.

**Comment by jstiled** [comment]
My group that I dive with will always wait for new players to spawn before starting the mission when docked.  Causing dead game play for everyone.  Would it be possible or a quick fix to remove the respond timer when new players are joining when docked.  

I think the timer is good when diving to stop players from leaving the game and rejoining to get around the waiting.  This use case is only when the sub is docked.  

@Krzeszny A time-based docking fee would also solve this as well.

**Comment by Regalis11** [comment]
Thank you for the clarification!

> My group that I dive with will always wait for new players to spawn before starting the mission when docked

I'm curious, why? Also, are you aware the respawn delay can be adjusted in the server settings?
