### ISSUE TITLE
[Unstable] Camel issues and feedback

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9751]
Issues ranging from major to nitpicks:

- [x] Bad gaps
Multiple gaps, not a single large gap
![image](https://user-images.githubusercontent.com/73229309/186065274-63bf4521-6701-4788-a583-984d5ef8b7aa.png)

- [x] Front Ballast walls impossible to reach
The lack of support prevents from welding the front part wall from inside. Bots can get confused and climb the ladder back and forth to repair inner walls. Suggest adding platforms and waypoints
![image](https://user-images.githubusercontent.com/73229309/186068377-55fc7cc8-226f-4bbb-8ada-47825604ac4e.png)

- [ ] Airlock pump not turned on by default

- [ ] Airlock emergency lights not shadow-casting
![image](https://user-images.githubusercontent.com/73229309/186070254-6de94296-4293-4027-a5b7-91f4ad1da5e5.png)

- [x] O2 hull as "Wet room"
![image](https://user-images.githubusercontent.com/73229309/186289812-4fd3976d-a923-41e3-80c1-f3547cf1d27c.png)

- [x] Flood prone electrical
The junction box compartment will systematically flood before water ever flows into ballasts since it's an open gap.
Consider closing it off with hatches
![image](https://user-images.githubusercontent.com/73229309/186063598-9977180a-26ba-418c-a1bf-3475b8e1e376.png)

- [ ] Airlock alarm spazzing out
Doesn't ignore dead, minimum velocity not set to 0, it's rather annoying + the sub already has an alarm
![image](https://user-images.githubusercontent.com/73229309/186065383-ffa3ad6f-4043-48a2-83be-692c6e0aa688.png)

- [x] Docking port not wired to power
Although it doesn't really matter since docking to outposts doesn't use fuel

- [ ] No docking hatch on the left tit
For consistency's sake, both humps are supposed to be identical "detachable" modules. If one breast has a docking hatch, then so should the other 
![image](https://user-images.githubusercontent.com/73229309/186068918-4af33516-7ad6-4fcf-94f4-77afd3c2f32d.png)

- [ ] Status board hard to see
Probably better to set a Green/Red output on Set_color for True/False as it makes broken items more visible on the status display
![image](https://user-images.githubusercontent.com/73229309/186067397-50a318f9-1348-4888-98ab-220846ad681d.png)

More to come after actually playing with it.
I won't go into visuals until the next update.
There are some weird design quirks too like battery linked to fabricators.
You can also shave off 5 shadow casting lights by tweaking emergency lights (especially those in ballasts)

### Version

0.19.1.0 (unstable)

**Comment by JeroonBosch** [comment]
"The junction box compartment will systematically flood" - intended

"Bad gaps 
Multiple gaps, not a single large gap" - don't see anything wrong here

"Docking port not wired to power
Although it doesn't really matter since docking to outposts doesn't use fuel" - doesn't matter

**Comment by ubertpendragon** [comment]
> "Bad gaps Multiple gaps, not a single large gap" - don't see anything wrong here

There shouldn't be one horizontal gap, but multiple small gaps between each hull

**Comment by Regalis11** [comment]
Addressed some of the remaining issues in https://github.com/Regalis11/Barotrauma-development/commit/197d4a825dbe695bf213bbcbce0019aefda68174

> Airlock pump not turned on by default

It does seem to be now, idk if @JeroonBosch already turned it on?

> Airlock emergency lights not shadow-casting

This seems to be intentional: it's better for performance and they're so dim it's barely noticeable they "shine through walls".

> Airlock alarm spazzing out: Doesn't ignore dead, minimum velocity not set to 0, it's rather annoying + the sub already has an alarm

Why should the minimum velocity be set to 0? 

> For consistency's sake, both humps are supposed to be identical "detachable" modules. If one breast has a docking hatch, then so should the other

What makes you think they're supposed to be identical? To me it seems logical that they would've only installed a hatch on one of them, as the sub only needs one.

**Comment by JeroonBosch** [comment]
> It does seem to be now, idk if @JeroonBosch already turned it on?

I turned some pumps on at some point, but don't recall touching it since it hit unstable

**Comment by Rokvach** [comment]
I didn't notice any issues with the entries that were covered, Closing.
