### ISSUE TITLE
Mic broadcasts when downloading mods from a server

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9757]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing the  `file-transfer-speedup` branch we noticed that if you have your mic set to voice activity it will broadcast it to players currently in the lobby, but the player joining wont hear them. 

### Reproduction steps

1. Have voip set to voice activity
2. Join a modded server and talk while downloading the listed mods
3. Players in the server should be able to hear you

### Bug prevalence

Happens every time I play

### Version

Other

### -

file-transfer-speedup branch

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f0b0c229bfb951912e79721a6ca544f77be35909

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
