### ISSUE TITLE
Conditional or Property Conditional can't read integer or int

### ISSUE THREAD

**Issue by ghostsheet** [Regalis11/Barotrauma#9758]
Tried to check an integer such as quailty or qualitylevel from an item or quality itemcomponent.
Comes back with errors!

I think Property Conditional can't read integers as it tries to read it as float?

`
        <StatusEffect type="OnContaining" target="Contained">
          <Conditional QualityLevel="eq 1" />
        </StatusEffect>
`

![integer problem](https://user-images.githubusercontent.com/43085828/186574681-657ac20f-4377-4582-9f47-d4e31c490eed.png)
!

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/560322c6a9f1ef46401a5c8a68727e88a15a99ed
