### ISSUE TITLE
[Unstable] Vote kicking a player then removing the ban via lobby settings results in an immediate re-ban on rejoin

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9761]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I votekicked a client in my server. then used the settings button as a client with all permissions and commands in the lobby to unban the player. however upon joining they are simply banned again automatically.

### Reproduction steps

1. Start a server (In my case I used a dedicated)
2. Get 3 clients or more to join
3. use two clients to vote kick the third
4. With one of the two clients, access the settings menu in the lobby on the banlist tab
5. Due to another issue, you may need to open this twice to show the ban
6. use the "Remove" button for the third clients ban that was vote kicked.
7. have the third client rejoin - Find they are given an error or a notification they are banned.
8. the ingame chat for other clients indicates they are banned again.
9. the entry will reappear in the banlist (after opening it twice due to another issue)

### Bug prevalence

Happens every time I play

### Version

0.19.1.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports
Error message that sometimes appears (Instead of X is banned):
![image](https://user-images.githubusercontent.com/29177976/186597969-10f0b704-0af9-482b-b373-dc4336dbd487.png)

Messages after being unbanned (all shown are a single rejoin after the unban):
![image](https://user-images.githubusercontent.com/29177976/186598316-623d5507-a923-474c-baf1-7ae7f07e7c03.png)

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/f518331ffa4fef123c70ab8e783221e0215bc69b

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/7f3f6c800271e4dbdc682bb79cdd4e7e6c074a11

Players are still immediately banned upon rejoining after the ban has been removed, and the fix does appear to be in the branch so it appears something else is still causing this.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861.

Just leaving this here as I'm not sure if its resolved in future networking changes, but current dev does list a lot of messages for doing a singular vote kick ban. The below is missing the voted to kick for messages and includes a rejoin message after unbanning the client successfully, but it is an excessive amount of overlapping messages.

![image](https://user-images.githubusercontent.com/29177976/189167800-98efaf9b-2846-47cd-ace4-fe647e674971.png)
