### ISSUE TITLE
[Unstable] In-lobby server settings ban list needs to be opened twice to refresh listed bans

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9762]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As a client on a server with permissions to edit the server settings and see the banlist, after a ban has been made if you open the settings in the server lobby and go to the banlist tab the new ban will not be there. you then need to close the server settings, reopen it and go back to the banlist a second time to see the new ban in order to remove it.

Expectation: it should only need to be opened once, or at least update while it is open if waiting on the server.

### Reproduction steps

1. ban another client as a client. It probably works through server console commands or the in game UI but in my case it was via vote kick autobans.
2. (With permissions to) open the server settings and go to the banlist.
3. find the ban does not show. close and reopen the banlist to find the ban now appears correctly.

### Bug prevalence

Happens every time I play

### Version

0.19.1.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/182ef45877f07857da9010e8f2723c33dede5eaa
