### ISSUE TITLE
[Unstable] Resizable structures can't be resized upon placing

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9763]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you try placing down a resizable wall (like a 90° shell), you won't be able to stretch it upon placing.

It will be placed down at its minimum size

### Version

0.19.1.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/50cf887c35af7d1bba2f75ed2119228ec492df1e

**Comment by ubertpendragon** [comment]
Working as of V0.19.2.0, closing
