### ISSUE TITLE
Pet disappears when docking at a station

### ISSUE THREAD

**Issue by frostcrystal** [Regalis11/Barotrauma#9767]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After the recent update, pets on board the ship disappear when docking at a station. Sometimes they reappear after undocking, but more often than not they don't.

(Before the update, the pet would always appear in the area belonging to the owner, e.g. I'm a medic, it appears in medical bay, when docking/undocking, regardless of where it originally was.)

### Reproduction steps

1. Have a pet on board ship (I have a Peanut, fed, high happiness).
2. Dock at a station (we're in Campaign mode, multiplayer, in the Aphotic Plateau, just discovered the Great Sea).
3. Pet should disappear from the submarine after docking. 

### Bug prevalence

Happens every time I play

### Version

0.18.15.1

### -

Whatever version is currently the default on Steam

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
None
```

**Comment by frostcrystal** [comment]
Not sure if something changed since I last posted, but today Peanut is sometimes appearing at stations (we play once a week and the bug started showing up right after July/August update).

**Comment by Regalis11** [comment]
Thank you for the report (and sorry for the super late reply)!

I gave this a test in a multiplayer campaign now, but even after docking and undocking several times at several different outposts, I could not find a way to get this to happen. So I think it might be the issues been fixed since.

Another possible explanation might be that the pet spawned somewhere you couldn't find it. The pets always spawn inside the submarine when you enter an outpost, and if they happen to spawn in some remote corner of a big sub I could easily imagine not finding the pet and thinking it's disappeared.

**Comment by frostcrystal** [comment]
> Thank you for the report (and sorry for the super late reply)!
> 
> I gave this a test in a multiplayer campaign now, but even after docking and undocking several times at several different outposts, I could not find a way to get this to happen. So I think it might be the issues been fixed since.
> 
> Another possible explanation might be that the pet spawned somewhere you couldn't find it. The pets always spawn inside the submarine when you enter an outpost, and if they happen to spawn in some remote corner of a big sub I could easily imagine not finding the pet and thinking it's disappeared.


Thanks for doing the testing! :) Our group dropped the game a few months back due to lag/rubberbanding issues, but I believe you're right and that I hadn't seen a reappearance of the problem since my last update in September. It's hard to say exactly because something killed off my entire Peanut farm and I never bothered recreating it.
