### ISSUE TITLE
spam server in server browser

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9768]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Seeing what appears to be a spam server in server browser

![image](https://user-images.githubusercontent.com/5103517/186820472-a1987848-9416-4b09-8ebf-06ccb9e913b2.png)

obviously, there is not going to be 1337 players in a lobby

modified executables have been used to have server caps of >16, usually 32 or 64, peaking at 128 at some time with playerhigh tides, and I believe there legitimately have been >50 players on a single server (some may testify)

Anyway, reporting this now so there's a record of a spam server, should it increase in frequency.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
noted - faked player numbers have been seen for a while, this picture is dated february 2022 
![image](https://user-images.githubusercontent.com/5103517/186960257-90c266c2-6881-4ed3-a88c-348f4f4d59cf.png)

and again in may 2022 
![image](https://user-images.githubusercontent.com/5103517/186960419-cf0c7a27-1194-4a40-a1fb-833873ce33e1.png)

**Comment by NilanthAnimosus** [comment]
Anyone can edit the code from the public repo to report high player numbers to the steam serverlist, the actual harm of doing so is pretty minimal in my eyes, I don't think there would be much to do against it, but it also has no harm. Kudo's if they manage to host an actual server modded to handle a full 228 (or 1337) players connected, though it may just be as likely they broke the client counting mechanisms somehow by accident too.

**Comment by Tsunder** [comment]
minor status update: the phone number server is still up (disappeared for a week?)(has been up for like a week now?) but has a different phone number now.

**Comment by Wheatley1001** [comment]
Hello everyone! As of 1.0.7.0's launch there has been a malicious attack on the server browser with 99/100 servers advertising a discord link. Following the link brings you to a server which harbours harmful content (such as gore) and an eight point list of "why Barotrauma is the worst game ever". Additionally, there is a livestream of two people in the server watching the server browser and many users have reported that these individuals are targeting public lobbies and taking them down (the specifics about the methods used are unknown to me, but I've heard reports of ddos attacks or "sending ping towards servers to take them down"). 

This specific instance has been reported in issue #11499. The malicious servers appear front and centre on the server browser to the point in which avoiding them is neigh impossible.

![image](https://user-images.githubusercontent.com/105495756/224835761-cee69241-4ddb-414b-92ff-0a2eade2305e.png)

This is a group of misinformed and hateful individuals that are utilising weaknesses in the server browser to spread misinformation and harmful content to any user, whilst actively trying to prevent other users from enjoying the game.

**Comment by evilfactory** [comment]
I propose having a system similar to how dedicated servers in Garry's Mod work, by forcing operators to have a steam account connected to the dedicated server. 
https://wiki.facepunch.com/gmod/Steam_Game_Server_Accounts 
This should allow to more easily ban spam servers based on the steam id.
