### ISSUE TITLE
Auto Dock Circuit Popup Does Not Work

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9769]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I made an auto dock circuit to dock my boat as soon as I come within range of a station. Instead of docking instantly like I would expect (and what used to happen) I get this awful popup that does not even work correctly:

![auto dock](https://user-images.githubusercontent.com/16128947/186830469-15d7caaf-c3b5-462f-a577-347675b09463.png)

Yes, clearly I want to use the circuit that I myself deliberately made. This is in a single player campaign. If this is meant to deter griefing it does not apply to me.

Even worse, if I click yes on the popup it still doesn't dock. I have to manually dock using the big red button as through my circuit doesn't even exist. Yet I know my circuit works because i'm getting this popup saying its attempting to dock correctly.

So fix the yes button to actually work, but more importantly can you make something in options to turn this popup off completely? It pops up every single time and its completely ruining my auto-dock circuit.

### Reproduction steps

Create an auto-docking circuit to dock with a station as soon as your sub is within range.
Turn the circuit on.
Move the sub within range of a station.
Popup happens. Click yes.
Notice you still aren't docked even though you clicked yes.
Become frustrated because this popup should not even exist in the first place.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a1f157dade2c827390e9d061386016ed792ee54d

**Comment by gerakis** [comment]
I really hope you got rid of the popup completely. Having to click "yes" on a prompt completely defeats the purpose of not having to click on "dock". The whole point of the auto dock was to eliminate clicks.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/030a5bfce9e0da98c5d3527bd128c7c32996a0ff, works correctly. closing.

Notes:
Popup does not appear in single player and auto docking circuits work just fine for their purpose, but still appears in multiplayer correctly to prevent potential griefing / issues.

**Comment by gerakis** [comment]
I guess you closed it, but I would like it if it was on undock only. Thats almost always done manually anyway, and it would still prevent a softlock. So allow auto docking, but do a warning confirmation on undocking.

**Comment by NilanthAnimosus** [comment]
Hm, the submarines I tested on that had auto docking circuits did not immediately redock but likely had some mechanism to disable that, do you have or know of a submarine that doesn't do that and attempts to infinitely undock and redock as I don't really tend to create circuits to test that properly so I went with a few submarines instead.

**Comment by gerakis** [comment]
![auto docking hatch](https://user-images.githubusercontent.com/16128947/189694000-8e878692-003b-42b4-af3a-f96cee2ab926.png)

This is the one I use. It will auto dock, but not auto undock. You have to undock manually.

If someone screwed up the wiring though, you can get into a situation where it redocks, then undocks, then redocks again, forever in a loop. Because you dont have time to fix the wiring before the new load happens, you get softlocked. Based on the previous patch notes it sounds like what they were trying to fix. I think the best way to stop that loop would be to do a popup confirmation on undock only as that is never automated from what ive seen. That way you get the softlock prevention, and can still use auto docking circuits.
