### ISSUE TITLE
Deconstructor and Research Station Showing Genes

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#9771]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Placing unidentified genetic material in a deconstructor or research station shows what genes it will refine/research into. Also silly that the research station states "deconstructs into".

### Reproduction steps

1. Place genes in deconstructor or research station
2. See the "deconstructs into" to read what it will be

### Bug prevalence

Happens every now and then

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ConnorsSilverpaws** [comment]
![baro 0 19 2 0 decon genes](https://user-images.githubusercontent.com/39156231/186934660-f0f78e9d-a22b-418c-be1b-1e4ba8c35cf2.png)
![baro 0 19 2 0 decon conditionissue](https://user-images.githubusercontent.com/39156231/186934677-77501f85-2309-4763-99d2-6d2ae8dc193b.png)

**Comment by ubertpendragon** [comment]
That's because each unidentified genetic material is predefined as its own item with a set output

```xml
  <Item name="" identifier="geneticmaterialcrawler_unresearched" nameidentifier="unidentifiedgeneticmaterial" category="Material" maxstacksize="1" tags="smallitem,unidentifiedgeneticmaterial" cargocontaineridentifier="mediccrate" description="" scale="0.5" impactsoundtag="impact_soft" hideinmenus="true">
    <PreferredContainer primary="medfabcab" spawnprobability="0"/>
    <PreferredContainer secondary="abandonedmedcab,wreckmedcab,outpostmedcab" spawnprobability="0.01"/>
    <PreferredContainer secondary="geneticstorage" spawnprobability="0.02" />
    <Deconstruct time="5" requireddeconstructor="geneticresearchstation">
      <Item identifier="geneticmaterialcrawler" requiredotheritem="stabilozine" outconditionmin="0.1" outconditionmax="0.2" activatebuttontext="researchstation.research" infotext="researchstation.research.infotext" infotextonotheritemmissing="researchstation.combine.missingitem" />
    </Deconstruct>
    <Sprite texture="Content/Items/Genetic/Genetic.png" sourcerect="0,79,58,40" depth="0.6" origin="0.5,0.5" />
    <Body width="15" radius="15" density="20" />
    <Pickable slots="Any" />
  </Item>
```

Compare to scrap which uses a random selection:

```xml

    <Deconstruct time="10" chooserandom="true" amount="2">
      <Item identifier="iron" commonness="0.8"/>
      <Item identifier="thorium" commonness="0.2"/>
      <Item identifier="steel" commonness="0.6"/>
      <Item identifier="aluminium" commonness="0.6"/>
      <Item identifier="titaniumaluminiumalloy" commonness="0.3"/>
      <Item identifier="copper" commonness="0.8"/>
      <Item identifier="rubber" commonness="0.5"/>
      <Item identifier="carbon" commonness="0.6"/>
      <Item identifier="lead" commonness="0.7"/>
    </Deconstruct>

```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e08bee6104421cf2ea6f5d546aa2e4fd239da628

**Comment by Rokvach** [comment]
The genetic material you get from unidentified genetic material is still displayed on the deconstructor
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9555c54c-210c-44b3-8593-8550c052656c)

Everything else seems fine

**Comment by Regalis11** [comment]
Fixed deconstructors in https://github.com/Regalis11/Barotrauma-development/commit/497ac6256b1c06d3e7c233f4ca6e854c887495dd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
