### ISSUE TITLE
Fabrication Does Not Show Required Item Count

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#9772]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Fabricating an item that requires multiple of the same item is not shown in the input.
Example: oxygen tank requires 2 aluminum, but the fabricator will only show a single aluminum.

### Reproduction steps

1. Interact with fabricator
2. Select an item that requires more than one of the same item
3. See the input recipe require only one of what should be multiple
4. Crafting will still pull/request from storage to consume multiple of item correctly, against what is show
![baro 0 19 2 0 fab wrong count](https://user-images.githubusercontent.com/39156231/186936472-e35a6cfa-71ec-49de-8331-6cc4f8b37c1c.png)
n

### Bug prevalence

Happens every time I play

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/503414874759b27b7a3775d42cdb691a7bd2cd33

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
