### ISSUE TITLE
Impossible to Navigate Map

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9773]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Something went wrong with the level generation here. I cant escape the starter cavern. Its pretty small so if there were a way out it seems like I would notice. I don't see anything I can shoot through.

![impossible map](https://user-images.githubusercontent.com/16128947/186977304-c7cdeaec-8a9a-4f09-9064-593bce550541.png)

Im going to link my save file so hopefully you can figure out what caused this:
https://mega.nz/file/HI1F1CiT#9A9S_hJpNYHiGbvfcM8jkUd7k_HVGZ041NRjaPyCXho

I saw other reports of this but pretty much all of them were flagged with "needs more info" so i'm hoping that save file will be enough.

### Reproduction steps

Put my save file in your saved games directory. (C:\Users\*your name*\AppData\Local\Daedalic Entertainment GmbH\Barotrauma)
Load the game.
Notice you can't escape.

### Bug prevalence

Just once

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Thanks for the report!

Although you've stated its both on macOS and on windows at the same time (?) I gave this a quick test and there is a cave directly above the outpost you start from, and the level is indeed far too tight for what you would need to do the level in the provided save.

https://user-images.githubusercontent.com/29177976/187016438-47fd76bd-219a-479e-9746-4f7c9141335b.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/50a3b7fd788384cccd72439a27d0ae32d7642843

**Comment by NilanthAnimosus** [comment]
Tested against level-gen-fix branch commit https://github.com/Regalis11/Barotrauma-development/commit/d96194a894b99e2a43213a2281beb04eb4cb7455, no issues found, seems ready to merge and close this issue.

Notes:
Tested original save and it fixes that, then used the level editor with 3 different submarines across a multitude of biomes totaling approximately 60 to 80 maps generated and all seemed passable/normal, so nothing seems evidently broken by these changes.
