### ISSUE TITLE
Item recipes with multiple skills (like Health Scanner HUD) can be crafted without all necessary skills

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#9777]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When crafting items with multiple required skills, the skill check can be passed if not all skills are actually at the required level.

Using the health scanner as an example: a character can craft it in the base 10 seconds if the sum of their mechanical and medical skills exceeds 80. This means that it can be crafted with 0 mechanical skill, as long as medical is 80 or above, and vice-versa. Notably, the "**SKILLS REQUIIRED TO CALIBRATE**" text is still red, as it would if the skill check was not met. 
The "**REQUIRED TIME**" text is yellow/green, as expected, since the fabrication time is not increased.

Further testing with modded items, an item is craftable if the sum of the character's (relevant) skills exceeds the sum of the required skills.

I am unsure whether this is intentional or not, but I am creating this just in case this is not working as intended.

It might make some sense that a character who is very skilled in medicine might be able to create a health scanner, even if their mechanical knowledge is sub-par, but it could also be argued the other way.

Regardless, I believe the red "**SKILLS REQUIIRED TO CALIBRATE**" text is not working correctly, since it implies that the skill check is not passed, even though the item is crafted in the normal amount of time.
This currently only affects the Health Scanner HUD in vanilla, but can also occur in modded items.

![image_2022-08-27_152800961](https://user-images.githubusercontent.com/37850646/187016257-815fa6d2-9a38-46c9-890f-fc40e5a4779d.png)

### Reproduction steps

1. Have a character with 80 mechanical and 0 medical skill access a fabricator (use "setskill mechanical 80" and "setskill medical 0" in console)
2. Find the Health Scanner HUD and observe that it can be fabricated in 10 seconds, despite the "**SKILLS REQUIIRED TO CALIBRATE**" text being red, and the required skills not being met.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/a0b2d59001804156270052c3c566e3b6247165d0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
