### ISSUE TITLE
ULDs only hold 10 crates but it looks like they can fit 12 crates

### ISSUE THREAD

**Issue by ahzidaljun** [Regalis11/Barotrauma#9778]
The Unit Load Device item can only hold 10 crates, but it looks like it has enough room for two more crates for a total of 12. This has significant consequences for game balance, especially in regards to its competitor, the crate shelf, which in the same space can indeed hold 12 crates. 
The long-lasting impact of this two crate deficiency could wreak havoc on campaign runs, and has troubling implications for the sub editor metagame, in which ULDs are used as mere skins for the superior crate shelf stack.

![Screenshot_65](https://user-images.githubusercontent.com/72061961/187040004-953e03de-9d90-4430-959c-aaf5574f014e.png)

It would positively impact game balance if ULDs were buffed to hold 12 crates. Furthermore, I think it is worth considering to make the ULD as a whole waterproof even if the crates within them are not - it looks like a sealed container, and it would give an extra incentive to using subs with ULDs for cargo missions, since it will be safer for water-sensitive items.

**Comment by ubertpendragon** [comment]
I cannot sleep at night knowing the ULD only carries 10 crates and not 12.

**Comment by gerakis** [comment]
It is kind of jarring when you notice it. I think the reason they got away with it for so long is because cargo hold are always really dark.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2b98a31932311824f6a4f7a8ed6b7d5ed685d656

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
