### ISSUE TITLE
Localization not work if target name or description is not blank.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9782]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

see this mod I upload, I write name="name_A" and desciption="desciption_A" in item xml, and write name_B and description_B in language xml. In game we can see this item are called name_A.
![image](https://user-images.githubusercontent.com/44423036/187084054-68f12cfa-cf6b-42f2-9e91-f49c189d2ba0.png)

I often translate English mods into Chinese, but I suddenly became aware of this problem (as described in the title).
I often notice modders not leaving the name and discription blank in their mods for some reason.
If this happens, I'll have to contact the author for permission to modify their mod in order to implement the localization.
So I wonder, is this a feature or bug?
If this is a feature, why don't we improve it? Let language file has high priority.
If this is a bug, why don't I report it? Make barotrauma better and better.

### Reproduction steps

1. download the mod and load it
2. see mod item's name and description. (item's identifier is "test")

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by esirprus** [comment]
[localization bug.zip](https://github.com/Regalis11/Barotrauma/files/9440033/localization.bug.zip)

**Comment by esirprus** [comment]
Most likely related to this #8450

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1084d070501d5d84bb4684db7e89b6f0d775bfa5

**Comment by esirprus** [comment]
Ah, this will make translators and modders easier to work, thanks!

**Comment by Rokvach** [comment]
Looks like the name is correct now but the description isn't shown as description_B

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2480d6a6-f402-4393-8032-d135ee3b7cf3)

**Comment by esirprus** [comment]
<del>devs you let me low oxygen</del> anyway it's good if this can be totally fixed in the end.

**Comment by Regalis11** [comment]
Fixed the descriptions in https://github.com/Regalis11/Barotrauma-development/commit/ff6ba10e2bfc5f621ec9e4133c8732cafb7c9482

**Comment by Regalis11** [comment]
Note for testing: these changes caused a new issue, see https://github.com/Regalis11/Barotrauma/issues/9820

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
