### ISSUE TITLE
geneticmaterialcrawler_unresearched3 deconstructs into mudraptor genes

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#9785]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When deconstructing the item "geneticmaterialcrawler_unresearched3" in the research station, it produces mudraptor genes.

The error is in line 274 of genetic.xml

I checked all other unresearched genetic material and they all seem correct.

### Reproduction steps

1. spawn in the item "spawnitem geneticmaterialcrawler_unresearched3 inventory"
2. research it with stabilozine in a research station
3. observe that it produces mudraptor genes, instead of crawler genes, as the identifier might imply.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/497ac6256b1c06d3e7c233f4ca6e854c887495dd

**Comment by Regalis11** [comment]
Fixed deconstructors in https://github.com/Regalis11/Barotrauma-development/commit/497ac6256b1c06d3e7c233f4ca6e854c887495dd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
