### ISSUE TITLE
Dr. Submarine does not work when swinging medicine

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#9786]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The medic talent Dr. Submarine does not apply its "50% of the effects on you as well" perk when swinging medicine by hand, only when applying via Health GUI.

This seems to affect every type of medicine that I have tested.

### Reproduction steps

1. give your character the talent [givetalent "Dr. Submarine"]
2. spawn a test dummy [spawn assistant cursor]
3. spawn your medicine of choice [spawnitem Fentanyl inventory 8]
4. select your item, crouch, and hold left and right click to continuously swing all the medicine on the target
5. observe that your test dummy will die of overdose, but your character is unaffected.

Repeating the test, but using the health GUI instead of swinging yields the opposite (and expected) result: you die of overdose.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This talent, and the effect it uses, have been removed.
