### ISSUE TITLE
Husk infection overwrites water prankster

### ISSUE THREAD

**Issue by WizzleWuzzle** [Regalis11/Barotrauma#9789]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Was playing in Multiplayer (reproduced in Single Player Campaign) as assistant. Had "Water Prankster" talent as well as Husk Genes / Infection (Think of it as a poor mans perfect Thresher Genes). Was sunk in the Abyss due to Endworm. Swam out with nothing but Clown Suit/Mask and Sonar Beacon to try and distract it. Blew up to pressure immediately upon exiting the sub. Expected Water Prankster pressure immunity to allow me to exit sub safely.

Testing in Single Player and had character approx 1000m below the outpost, 400m below the bottom of the map. Screenshots show Clown Power active and character safely in the Abyss. 2nd Screenshot shows clown power still active yet character died. Character was not moved between 2 screenshots. 

![20220829064119_1](https://user-images.githubusercontent.com/39940210/187198337-eff51e0a-94f3-4b71-8d68-b17dc4d0cadd.jpg)
![20220829064248_1](https://user-images.githubusercontent.com/39940210/187198349-66052343-5459-44ec-844c-f0d2a01de665.jpg)

### Reproduction steps

1. Start Campaign (Single/Multi) as Assistant.
2. Obtain/Wear the Clown Suit/Mask
3. Obtain 2 Levels and select "Water Prankster" as Tier 2 talent
4. Obtain Husk Genetic Material + Gene Splicer. Use on self
5. Swim to "Abyss" (Testing was done at approx 400m below the map). Ensure Clown Power is present and no Dive Suit worn
6. Note no negative effects
7. Infect self with Husk Infection
8. Upon Husk Infection reaching "Heavy" stage (where you can press F to infect creatures) character immediately implodes due to pressure

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/18d41f9daee249339a46b8fa26e24b434199bd06

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/5da5cc44d9ea552da144b7cff41cab3eba66276c, no issues found, closing.
