### ISSUE TITLE
Can't use aimable tools while on ladders without falling off

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9790]
Due to the same key being used for aiming and letting go of ladders, it's difficult to e.g. weld things while on a ladder. We need to consider how to address this.

**Comment by Ek-Videogames** [comment]
Strangely - this conflict didn't seem to matter before the "interaction overhauls" like ability to interact with items while sitting in a chair. Some interactions would cause you to fall off ladders, but using a welding tool was not one of them.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/055b5e609eaa43518ff06009221960de6a7739c2

**Comment by Jade-Harleyy** [comment]
Tested; aiming and shooting, and interacting with other items while on ladders seems to be working perfectly now!
