### ISSUE TITLE
Traveling Tradesman (Captain Talent) Does Not Stack With Multiple Captains

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9792]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you have more than one captain with traveling tradesman, it doesn't seem to stack. Meaning you don't get 9 sales per station, you just get 5. The wording says "additional" so I would assume it would stack. This bug seems to occur every time.

### Reproduction steps

Hire a bunch of NPC captains in single player.
Give them all traveling tradesman talent.
Go to a new station.
Check the shops and realize you only get 5 sales.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2ddf21fe63107e9c85d0113b757b6ee42b2622e8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
