### ISSUE TITLE
publish tab message for family shared baro displays message for free weekened

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9794]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

going to publish tab shows a "free weekend" message instead of something relevant about playing through steam family sharing

![image](https://user-images.githubusercontent.com/5103517/187327349-b4e36774-0084-44df-8361-bee5b7f812ae.png)

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9fa3b3c3fde294b968c8668ece403e56f5ad4927

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/553dc482307ed1776adba4f56ec07c1972f258af, no issues found, closing.

Notes: In game when family sharing shows as "via Family Sharing" correctly now.
