### ISSUE TITLE
Turret sprites in status monitor are rotated 180 degrees if turret has been mirrored in X

### ISSUE THREAD

**Issue by matthewpost** [Regalis11/Barotrauma#9797]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a submarine has turrets which have been mirrored in the X direction, the turret position indicators in the status monitor are rotated 180 degrees from the correct position.

I first noticed this when editing a submarine and flipping the turrets. This bug is present in turrets which have been mirrored in X on normal subs, and also subs which have been flipped for PVP. Mirror Y does not seem to produce this bug.

I have an image of a mirrored Dugong from PVP, where the turrets are clearly aimed into the sub, which is incorrect based on the true positions.

See the attached images for the Dugong Status monitor, and also an example made in the submarine editor, where the two left turrets have been mirrored X. Notice the issue is not present on the bottom right turret, which has only been mirrored in Y.

Dugong:
![image](https://user-images.githubusercontent.com/23487461/187571177-fe12c8f9-a74a-4e5d-adfc-9d484455ba20.png)

Example in editor with all mirrored versions of coilgun:
![image](https://user-images.githubusercontent.com/23487461/187573884-9ee9bd07-4eb3-4174-9ba1-b23d2d4dff01.png)

![image](https://user-images.githubusercontent.com/23487461/187572678-0242ad39-dc04-43e9-b3c8-52a0114fba65.png)

### Reproduction steps

1. Start any mission with any sub (or editor test mode) with turrets that have been mirrored in the X direction
2. check the status monitor and see mirrored turrets are shown as rotated 180 degrees from correct

Alternatively:
1. Start a pvp match and try to get a mirrored sub
2. If in a mirrored submarine, check the status monitor and see turrets are rotated 180 from correct angle
3. If not in a mirrored submarine, restart until you are in the flipped version

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9b6c600a5b9a0706de13165f9421bd8fee24f541

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
