### ISSUE TITLE
Chaingun high skill rotation speed default is inconsistent with all other turrets

### ISSUE THREAD

**Issue by matthewpost** [Regalis11/Barotrauma#9798]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Another player brought this up, but the chaingun's "Rotation Speed High Skill" is the same as the low skill speed, meaning having high weapons skill does not change the turret rotation rate (1.00). This is inconsistent with all other turrets, which all get equally faster for high skill (8.00). Even the railgun has a Rotation Speed High Skill of 8.00.

Moreover, all 4 turret types share identical rotation speed, spring stiffness and damping parameters except for this one anomalous value. I believe the value for the chaingun's "Rotation Speed High Skill" should be 8.00 by defualt.

This is a default value and can of course be edited in the editor when this is an option, but it is a strange quirk. 

Coilgun defaults (8.00):
![image](https://user-images.githubusercontent.com/23487461/187574773-a0ec41db-3b7b-4c85-b035-fa812d208e4e.png)

Chaingun defaults (1.00):
![image](https://user-images.githubusercontent.com/23487461/187574878-b9dcdeed-e006-43b2-b873-8a67a8798e2b.png)

Pulse Laser defaults (8.00):
![image](https://user-images.githubusercontent.com/23487461/187574967-0b5ca82d-1ea5-4a86-b092-8bd3efe9e445.png)

Railgun Default (8.00):
![image](https://user-images.githubusercontent.com/23487461/187575081-75491d20-adaa-4234-bb7b-a5ae2e1c91da.png)

### Reproduction steps

1. Create a submarine with all 4 turret types and test
2. Select a character with high weapons skill
3. Feel the difference between the turrets rotating over full range of motion. Chaingun is weirdly slow, even compared to railgun.

### Bug prevalence

Happens every now and then

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a791de42f9e507d23a59f4cd7089b50034bb7a6

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861.

Is the default value intended to be 5 instead of 8?

the other turret types use 8. even all of the heavy turret types (railgun, double coilgun and flak cannon) have a rotation speed high skill of 8.

additionally worthy of note - all submarines that have an existing chaingun still have 1.0 rotation speed high skill, such as the typhon2. Not sure which other vanilla submarines use this, but this would also effect all none vanilla submarines - perhaps suggest using the version upgrade method for this is possible given it was likely never intentional?

**Comment by Regalis11** [comment]
> Is the default value intended to be 5 instead of 8?

Yes, I intentionally kept it a little slower than other turrets. Made the game automatically correct the values in existing chainguns in https://github.com/Regalis11/Barotrauma-development/commit/4e4ff20876aababda79b892a1138442e1258bb94

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/68d02ff7ba62555e380a24ff29b99b8a05450339.

Fix works for workshop submarines, however vanilla submarines using a chaingun (IE. typhon2) did not update - likely each vanilla submarine needs a look through to update their chainguns manually.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/e08ae5ae1f52f831c2483183a21f2086fa9fa051, no issues found, closing

Notes:

Fixes issues with the vanilla submarines: Camel, Herja, Typhon2 which had incorrect stats for the chaingun.
