### ISSUE TITLE
pressing escape to exit map also opens the exit game menu

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9799]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the escape menu is opened when leaving the "map" screen

-also the escape button is the only way to close the map screen, despite the screen being opened with mouse.

tangental to #9632  i guess

### Reproduction steps

1. open map screen (end of a campaign area)
2. press escape

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Gave this a quick test on dev (commit https://github.com/Regalis11/Barotrauma-development/commit/f0aad9b5bf57a882922e1b77354982f72a4e5ff3)

Just a note here, but right clicking (Deselect or perhaps aim key by default binds)  will close the map screen. Though I can see why some would assume escape key is the one to hit (I do this myself time to time with various menus).

Perhaps the escape key could close an open interface/deselect first before opening the pause menu, but I think the deslect key was actually intended in cases like these.

**Comment by Tsunder** [comment]
the right click doesn't work for most menus I think (and there's no UI to say to use right click) 

I think the only way i've noticed to exit most baro in-game UIs is to click (left/right both work) outside of the UI windows

which... is pretty bad UX IMO

and it's exacerbated on the map window because the map takes up 95% of the screen

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f292f22201c82e4bef752713d67436e7c6ac703f

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/e176d08351da8d12043ea5020c9227d120dd502b, no issues found, closing.
