### ISSUE TITLE
Repair tools behave differently for singleplayer(and host) and multiplayer

### ISSUE THREAD

**Issue by etet2** [Regalis11/Barotrauma#980]
demonstration of this: https://youtu.be/fWf8BmoGo-U
even though damage is synced and does not cause any balance/desync issues, it looks very glitchy.
judging from #869 comments, the client has to wait for host to confirm that something has happend to an item. 

i suggest clients having a seperate instance of all items that are processed localy and then state of items is updated once a second or so with the host. this would prevent this graphical glitch.

**Comment by etet2** [comment]
here is the xml of the item used.

`<Item
    name="FN Scar"
	description="Overall good weapon"
    category="Equipment"
	tags="meditem,weapon"
    impacttolerance="3">

    <Sprite texture="items.png" sourcerect="0,0,141,33" origin="0.5,0.5" depth="0.1"/>

    <Body width="141" height="33" density="25"/>
	
	
	<ItemContainer capacity="1" itempos="-5,-8" hideitems="false">
      <Containable name="Scar Mag"/>
    </ItemContainer>
	
	<RepairTool structurefixamount="0" limbfixamount="-8" range="3000" barrelpos="71,5" particles="flame">
	  <ParticleEmitter particle="plasma" particlespersecond="100"/>
	  <ParticleEmitterHitStructure particle="plasmaspark" particlespersecond="80" anglemin="-40" anglemax="40" velocitymin="100" velocitymax="800"/>
	  <ParticleEmitterHitStructure particle="plasmaspark" particlespersecond="80" anglemin="-40" anglemax="40" velocitymin="100" velocitymax="800"/>
	  <ParticleEmitterHitCharacter particle="gib" particlespersecond="500" anglemin="-40" anglemax="40" velocitymin="100" velocitymax="800"/>
      <sound file="scar.ogg" type="OnUse" range="3000"/>
	  <Fixable name="structure"/>
	   <RequiredItems name="Scar Mag" type="Contained" msg="Out Of Ammo"/>
	  <StatusEffect type="OnUse" target="This">
	    <Explosion range="65" force="0" shockwave="false" flames="false" smoke="false" sparks="false" camerashake="25"/>
      </StatusEffect>
	  <StatusEffect type="OnUse" target="Contained" Condition="-2.5" disabledeltatime="true"/>
    </RepairTool>
	
	
	<Holdable slots="RightHand+LeftHand,Any" controlpose="true"  
          holdpos="30,-10"    aimpos="50,8" handle1="-15,-4" handle2="20,10">
	  <StatusEffect type="OnUse" target="This" Condition="-99" disabledeltatime="true">
	    <RequiredItems name="Scar Mag" type="Contained"/>
		
	  </StatusEffect>
	  <StatusEffect type="OnBroken" target="This" Condition="100" delay="0.2">
	  </StatusEffect>
	</Holdable>
  </Item>
  	<Item
    name="Scar Mag"
    category="Equipment"
    Tags="smallitem,weapon"
	impacttolerance="3">

    <Sprite texture="items.png" sourcerect="0,37,14,18" depth="0.3"/>

    <Body width="14" height="18" density="14" friction="0.95"/>

    <Holdable slots="RightHand,LeftHand,Any"/>
  </Item>`

**Comment by Rokvach** [comment]
There's been allot of improvements to this issue since this was posted, I don't see the point of keeping this open. Closing.
