### ISSUE TITLE
Reactor fission rate is climbing after leaving the component control wire dangling

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#9800]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Control signal from component into reactor set_fissionrate persists after detaching the wire
![image](https://user-images.githubusercontent.com/68995233/187645814-210dc612-548e-48ac-bd2d-2717dbf077a8.png)

### Reproduction steps

Signal from a component = 100 to reactor set_fissionrate
Reactor's toasty, shut it down
Detach the set_fissionrate wire
Power on the reactor
Either on manual or automatic, the control is steadily increasing. Reactor's toasty again.

### Bug prevalence

Happens every time I play

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f1a85e41f252e5cf65244e1b826eaef21717157d

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/5da5cc44d9ea552da144b7cff41cab3eba66276c, no issues found, closing.
