### ISSUE TITLE
Bots getting stuck on ladders (again)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9802]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I keep noticing bots just stuck on bottom of ladders each time I load into a outpost

![image](https://user-images.githubusercontent.com/7299826/187697078-cd7dce3e-9c57-4838-bfe2-8f0591b8dc30.png)
![image](https://user-images.githubusercontent.com/7299826/187696970-71d94f8c-681b-4ff7-bfd5-84bac8dd77d1.png)

### Reproduction steps

1. Launch singleplayer
2. Fly around outpost and take notice of bots
3. You should see some that are just humping ladders
4. If you don't notice any then load a new outpost

### Bug prevalence

Happens regularly

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/f2b6f358552c3195aef78f97c763b26fe447bc0e

**Comment by Rokvach** [comment]
Tested, I haven't noticed any bots idling on ladders after the fix, working correctly. Closing.
