### ISSUE TITLE
sub editor background images are lost on restart

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9804]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

background images in sub editor do not persist through game restarts

previously, they persisted (multiple images in position)

### Reproduction steps

1. add background image to sub editor
2. main menu
3. exit game
4. restart, enter sub editor
5. no image!

### Bug prevalence

Happens every time I play

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Tsunder** [comment]
if this was intentional, the process for adding an image is quite tedious to do every time.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c0aecd516ebbebb6116390b5b7992cf91ce6e02

**Comment by Rokvach** [comment]
Any image edits using the "toggle image editing" setting aren't being saved (new position, rotation and scale) the image is saved as it was when first adding it

**Comment by Regalis11** [comment]
Seemed to only happen if you exit the game without leaving the image editing mode, addressed in https://github.com/Regalis11/Barotrauma-development/commit/9f2d05871d0bab7fb64b723fd07e500f2a572e56
