### ISSUE TITLE
PVP mode "tie" end condition 

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9805]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

a PVP match ended with the last players (no bots in this round) being all killed together (frag grenade encouraged rapid disassembly of nuclear reactor)

However, the round itself went into no-players-alive fallback rather than considering it a tie.

Expected would be the game to declare it a tie (everyone is dead)

### Bug prevalence

Just once

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
happened just once so far (it's not often we get ties)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/26398c9de37e7ddea0440b2b881fdd81de24f2df

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/66dce3a1f38c2a862158f621a7dc8734d4f56ae1, no issues found, closing.
