### ISSUE TITLE
bot gunner has xray vision

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9807]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

bot gunner was able to say "I'm firing at Artie Doalot" even though the target was like 60m+ away from gun and the sub was fully obscured

bot gunner can name their targets through walls with 0 vision

expected was that the bot would just be like "firing at [ship name]", or perhaps "firing at [hull name]" idk.

### Bug prevalence

Happens every time I play

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I could not find any lines like this in the game (none of the "firing" lines include the name of the target). The name was mentioned in the "target spotted" lines though, fixed that in https://github.com/Regalis11/Barotrauma-development/commit/de33998a19b513b4701b2685cf406a816e891298

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/66dce3a1f38c2a862158f621a7dc8734d4f56ae1, no issues found, closing.
