### ISSUE TITLE
gaps don't appear when placing doors/ducts when gaps layer is on

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9809]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

placing doors/things with gaps don't have their gaps appear until after they get selected

### Reproduction steps

1. editor mode
2. turn gaps layer on
3. place door
4. no gap on door visible
4.a toggle gap layer on /off (optional), still no gap
6. click on door
7. gap now visible

### Bug prevalence

Happens every time I play

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Does this cause some kind of issues?

**Comment by Tsunder** [comment]
Means one needs to click /select all new doors to show their gaps

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0bfd0ea1e1dc10e3d7824ec1715a986fa5b96464

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
