### ISSUE TITLE
Handheld device to trigger WiFi components

### ISSUE THREAD

**Issue by Kampfkarren** [Regalis11/Barotrauma#981]
I am willing to work on this, just want to know if this is something people would be interested in.

**Comment by etet2** [comment]
could be really cool. go ahead

**Comment by Regalis11** [comment]
I don't know if you're already aware of this, but in the dev version you can use the chat even in single player and use the headset to trigger WiFi components. We'd still need a way to change the channel (see #28) however. But in any case a separate item could still be useful even though not strictly necessary.

**Comment by Kampfkarren** [comment]
I was having trouble implementing using capabilities effectively, so it's good that there's already something for it!

**Comment by Kampfkarren** [comment]
However, chat cannot be used in singleplayer, so make sure to get that settled before releasing it.
