### ISSUE TITLE
[Unstable] ULD missing some containedspritedepths

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9812]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/73229309/188182695-1a1ef2b3-e9b5-4c4f-b874-70d3d083a6a5.png)

There's only 10 containedspritedepths in the xml for 12 crates, missing two.

`<ItemContainer capacity="12" maxstacksize="1" canbeselected="true" hideitems="false" itempos="120,-364" iteminterval="150,80" itemsperrow="3" msg="ItemMsgInteractSelect" containedspritedepths="0.81,0.82,0.81,0.82,0.81,0.82,0.81,0.82,0.81,0.82">`

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e0aa05b898afcac917f7774cd0c921788381628

**Comment by ubertpendragon** [comment]
Oh to avoid the weird UI don't forget to add `slotsperrow="3"` in `<Itemcontainer>` for a nice 3x4 grid

![image](https://user-images.githubusercontent.com/73229309/188270387-153b3961-c94f-4dc7-aae4-71eff6685eb2.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e3aa5ac024d9b929fbfd396e88b9e36947ee1c2e

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/7f3f6c800271e4dbdc682bb79cdd4e7e6c074a11, no issues found, closing.
