### ISSUE TITLE
[Dev] remove or scramble definitions of medications when player has inadequate skill level

### ISSUE THREAD

**Issue by Llamaz4Lyfe** [Regalis11/Barotrauma#982]
The treatment suggestion feature is a nice touch, but it seems useless when there is ample enough information in the medications' descriptions.

**Comment by chesse20** [comment]
skill system is already bad, there shouldnt even be one, ss13 doesnt have it in most servers and its fine

**Comment by Llamaz4Lyfe** [comment]
thanks for the feedback!
imo since the devs have already started scrambling treatment suggestions it would make the most sense to go all the way or scrap it completely.

**Comment by BillCombs** [comment]
Making it a lot harder to deal with medical problems for a crew without a doctor would make having them a necessity, especially considering how often players get hurt during the gameplay. I think this would make it a lot harder to play in small crews where you don't have enough people to also have a doctor.
And even if you have a crew big enough to have a doctor, you cannot guarantee that they are not going to be a random new player who has no idea how the game works, and that they won't die in the first couple of minutes of the round.

Perhaps doctors should have better healing(and hurting) effects, compared to other members of the crew. They likely know better regarding how applying injections and other medical items should be done, which makes them more efficient at using those items.

**Comment by etet2** [comment]
@chesse20 even though barotrauma has some roots in ss13, they are completely different games. the reason ss13 works without skill systems is because there are admins constantly enforcing proper roleplay and knowing only things that you can do.

Barotrauma is focused on cooperation. if you remove all skills a single person would be able to operate whole sub

**Comment by Regalis11** [comment]
The idea behind the skill system in the dev version is that all classes can do any task (give medical treatment, repair things, fabricate new items), the characters with a higher skill only do it more efficiently. I feel hiding or scrambling the definitions or names of the items would go against that idea. I think what it would end up doing is making the game much more difficult and confusing to new players (and we definitely don't want to make the learning curve any steeper for them), and not change anything if you're a more experienced player who already knows what the medical items do.

I know the treatment suggestions aren't a perfect solution either - an experienced player doesn't need those and can play a medic regardless of their medical skill. However, we're going to make the medical items more effective when the medical skill is high (basically what BillCombs suggested). If your medical skill is low, there's a chance that using the item fails and causes a reduced or negative effect.
