### ISSUE TITLE
 If the mod does not have localised content for the language you have set, the description of the items of the mod are not shown.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9820]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Directly related issues: issue #9722 and issue #9782
Unstable version:
I cannot use lua so i test mod "More Artifacts(AOCS)" rather than "Neurotrauma", set my language to Simplified Chinese.
I noticed that DAI-injector has no description.
![image](https://user-images.githubusercontent.com/44423036/188261615-ba824c2c-69d2-4e57-b86d-15457893dea5.png)
But the affliction works, it has name and description.
![image](https://user-images.githubusercontent.com/44423036/188261633-ebe94d5d-d403-4a8b-a8ff-8b83720389a6.png)
I checked that the name and description in %ModDir%/Afflictions/resistances.xml is blank.

### Reproduction steps

1. Enable "More Artifacts(AOCS)" mod and set your language to other language (not EN and RU)
2. input spawnitem DAI-injector inventory
3. see item's name and description
4. use this item and see affliction's name and description

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/643ce3e11ddc3b5d8c59cdb681ad7fc26c5784eb

**Comment by esirprus** [comment]
uh, thanks, and I wanna ask how can I join Barotrauma-development?

**Comment by Regalis11** [comment]
I'm afraid you can't: that's our private repository, we only include the links here for our own use. But it usually doesn't take long before new changes are included in the unstable version and in the dev branch of the public repository.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
