### ISSUE TITLE
[Unstable] You can select submarine Tier in editor, but Tier is actually dependent on Price

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9821]
### What happened?

You can't actually set the tier of the submarine in sub editor. 
Price alone dictates the tier of the submarine and if you try saving a tier that doesnt match its cost, it will ignore it.

Tier 1 < 10k < Tier 2 < 20k < Tier 3

You might want a tooltip for that

![image](https://user-images.githubusercontent.com/73229309/188268259-1918df07-a207-4eeb-bc8d-5088cb35608d.png)

### Version

0.19.3.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/195956c65c3fe93eeff4c655781859eae987929e

**Comment by ubertpendragon** [comment]
> _Fixed submarine tier set in the sub editor not being saved, causing all subs to use the default tier determined by the price_ 

Does that mean Tier will be freely adjustable, allowing for <10000 Tier3 submarines? 

If so what prevents builders from always set their submarines as T3?

**Comment by Regalis11** [comment]
Yes, it does. In my opinion the sub designer should be free to set the tier to what they want (similar to the price).

> If so what prevents builders from always set their submarines as T3?

Nothing, but I think the same "problem" applies to pretty much anything you can do in the sub editor, and imo it's up to the sub designer to decide how balanced they want to make their submarine. There's nothing stopping you from equipping a tier 1 submarine with indestructible walls, a dozen turrets, devices with maxed out stats and giving it a ridiculously low price, why should the tier have a hard limit?

**Comment by ubertpendragon** [comment]
> There's nothing stopping you from equipping a tier 1 submarine with indestructible walls, a dozen turrets, devices with maxed out stats and giving it a ridiculously low price, why should the tier have a hard limit?

Mostly as a baseline for balance. 
You can't prevent builders from making broken subs but vanilla subs set a standard.

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/7f3f6c800271e4dbdc682bb79cdd4e7e6c074a11, no issues found, closing.

Notes:

Submarine tier now correctly saves (and thus is used by the game) allowing for total control by the sub creator / updating of previous submarines to pick tiers they would prefer to use as a sub creator.

Older submarines (that have not been editing for the new submarine upgrades tiers) use the price if not defined to gauge the likely tier.
