### ISSUE TITLE
Oxygenite shard (also Sulphurite shard?) not spawn at abyss.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9823]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

it seems Oxygenite shard and Sulphurite shard (in alienitems) not have these code, but incendium fulgurium physicorium dementonite (in materials.xml) and paralyxis (in medmaterials.xml) have.
![N4`OVG IVKKJ$Y7XRFW7M20](https://user-images.githubusercontent.com/44423036/188275932-50884b03-fde0-462b-8bc8-9700facea41f.png)
but incendium fulgurium physicorium dementonite (in materials.xml) and paralyxis (in medmaterials.xml) have

### Reproduction steps

uh, hard to produce, but I also did a survey (in Chinese) ,let people vote something they haven't seen (ignore 7)

![image](https://user-images.githubusercontent.com/44423036/188276304-fc435135-ff2c-448a-8803-cabe2c51f56c.png)
![image](https://user-images.githubusercontent.com/44423036/188276308-f2663fbd-9d48-4779-8c4f-47b6c3f2464d.png)

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is intentional: out of these alien materials, only incendium, fulgurium, physicorium, dementonite and paralyxis are supposed to spawn in the abyss islands.
