### ISSUE TITLE
Naturally spawned items now only have normal quality rather than random quality, which makes the quality of uncraftable items useless in vanilla.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9824]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I vaguely remember previous editions where you could find random quality revolvers and shotguns in shipwrecks, but now you can no longer find items better than normal quality.
This is the result of a discussion on my server.
If this was deliberately removed, then the change/fix to the grenade launcher can only be explained by "consideration of mods".
So I start this issue.

### Reproduction steps

1. start game and find shipwreck, and salvage it.
2. check the items' quality you have found.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/pull/3594/commits/3b7aaa0dd1fb57efc8a6f73fbbd0c591f7673b09

**Comment by esirprus** [comment]
> Implemented in [Regalis11/Barotrauma-development@3b7aaa0](https://github.com/Regalis11/Barotrauma-development/commit/3b7aaa0dd1fb57efc8a6f73fbbd0c591f7673b09)

oh, that's good, and can we find master quality weapons/items in wrecks?
