### ISSUE TITLE
"Timeframe" explanation tooltip is copy pasted from the AND component for XOR and OR comps

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#9827]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Explanation tooltip AND:
![image](https://user-images.githubusercontent.com/68995233/188292310-d5e16781-db21-4d0b-a72c-f2956b2e4844.png)

OR component:
![image](https://user-images.githubusercontent.com/68995233/188292338-61eee3f1-48be-4a81-b68f-4623326d0532.png)
Should read:
The item sends the output if either inputs have received a non-zero signal within the timeframe.

XOR component:
![image](https://user-images.githubusercontent.com/68995233/188292364-34341e73-ad30-4b7f-8be6-3e7a4a20032a.png)
Should read:
The item sends the output if exactly one of its inputs have received a non-zero signal within the timeframe.

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Linux

**Comment by Tsunder** [comment]
the tooltips are correct, as the components send false otherwise.

**Comment by mygamingaccount** [comment]
@Tsunder If _both inputs recieve a non-zero signal within the timeframe_ of the **XOR** component, it should **not** send the output.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8078511ad432af9d621e4e3ad8fb27f6e5c1ff7a

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/43f70c948290ea8e80acaa71e194b27700fff0db, no issues found, closing.
