### ISSUE TITLE
[Suggestion] Instrument Tracks

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#983]
So I've heard that instruments are officially coming to the steam release, which is a good step forward.

I'd like to suggest just like how in BTE, if there is to be a guitar or harmonica as instruments in the steam release, I'd appreciate if the same instrument tracks used in the BTE instruments would be used in the official release as well.

These tracks for the instruments used in BTE are the following videos.

https://www.youtube.com/watch?v=KRRGYEFZF4A

https://www.youtube.com/watch?v=-bXyMCLYbU0

Thanks in advance, Devs.

**Comment by Regalis11** [comment]
While I would love to use the tracks from S.T.A.L.K.E.R, I'm afraid we can't just steal assets from other games.
