### ISSUE TITLE
All "Load Items" Commands Cannot be Assigned to Specific Characters. (No Right Click Available)

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9832]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When playing in single player, I cannot right click any of the "load items" commands to choose a specific bot I want to do those actions. The left click still works normally.

<img width="506" alt="load items no right click" src="https://user-images.githubusercontent.com/16128947/188481092-e03d09ff-9925-4325-af3e-96d64590265e.png">

It doesn't work with refill oxygen tanks, recharge battery cells, or refill ammo. 

I know this is not the suggestion area, but if you could make a command that deconstructs empty ammo boxes that would also be a life saver on single player.

### Reproduction steps

Start a single player campaign.
Try to assign one of your bots to refill oxygen tanks using the right click for manual assignment.
Notice it doesn't work.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Hi! Thanks for reporting this! It seems that there's actually a bug with all of the orders that have options (Steer, Operate Reactor, Load Items, etc.). It seems it's not possible to use the manual assignment for any of them. We'll investigate this!

In the meantime, there's a way to operate around this. You can set orders through the crew list as well and this will allow to also give these orders to specific characters.

Sorry for the inconvenience, but thanks for bringing this to our attention!

**Comment by ekqvist** [comment]
Should be fixed in Regalis11/Barotrauma-development@4b59ebd

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
