### ISSUE TITLE
Mineral Scanner Does Not Detect Exotic Alien Mineral Deposits in Abyss

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9833]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While using a handheld sonar set to detect minerals, it cannot find alien material nodes such as fulgurite chunks. It still finds regular minerals just fine even in the abyss. 

This is specifically for handheld sonars. I don't know if a subs giant mineral scanner can find them or not as I didn't have that on my sub to test with.

### Reproduction steps

Go to the abyss and find a mineral island with alien materials.
Swim out and try to mine it.
Pull out your handheld sonar.
Put it in active mode, and toggle detect minerals on.
Notice you cannot see any alien material nodes even if you are right in front of them.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
I notice alien mining nodes also don't have any "glow" to them which makes them really hard to find. All other minerals and plants have a bit of glow on them I assume so you can find them easier. I don't know if this is intentional.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/14a9cf26af970c01095ab5e7c389da30c5ad823a
