### ISSUE TITLE
[Unstable] Repair UI doesn't show insufficient skills

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9834]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Either the UI doesn't display "insufficient" skill like it used to, either the skill isn't checked for repairs

![image](https://user-images.githubusercontent.com/73229309/188680358-1aef1d1d-8603-438b-9788-6189f569ea09.png)

### Version

0.19.4.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ac8c847a281b57f9f2bb26b29e621642a2316952

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
