### ISSUE TITLE
[Unstable] Flak Cannon screen shake is too much

### ISSUE THREAD

**Issue by Solbusaur** [Regalis11/Barotrauma#9835]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The flak cannon has too much screen shake compared to other guns. I recorded footage from the helm of the R-29 and the Typhon to compare the screen shake of a railgun and a flak cannon. Even though the railgun sits right on top of the Typhon's helm, the screen shake is far weaker than the flak cannon's. It's verrry distracting and makes it hard to keep your mouse aim accurate for healing, shooting or placing items while in gunfights

https://user-images.githubusercontent.com/63509011/188702379-971b85a3-09cd-46b0-84e7-06d4a29257cf.mp4
https://user-images.githubusercontent.com/63509011/188702403-95077655-2c3b-4702-ad61-b5b3efb5d7a4.mp4

### Bug prevalence

Happens regularly

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/34f578b5e2e0c31036d3472aacb8a98f4a6783e6. I did not actually reduce the strength of the shake, just the radius: in my opinion the shake feels alright when you're firing the gun, but I agree it's a bit too distracting when you're just inside the sub while someone else is firing it. Now the shake shouldn't be anywhere near as heavy unless you're the one manning it.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
