### ISSUE TITLE
Server settings fails to sync correctly when giving new permissions to a connected player

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9839]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Granting permissions while in the server lobby to a client caused various forms of desynced settings to said client. When changing certain server settings as one who already had permissions, it somehow caused other settings like respawn using a shuttle to uncheck themselves as well to add to the strange behaviour.

Note: Toggling a setting (IE. allow respawns) in the server settings will only re-sync that single setting to the client who is out of sync.

Host view (Actual settings):
![image](https://user-images.githubusercontent.com/29177976/188834850-a354f743-f4a0-45fb-be98-ee4c47c82c62.png)
![image](https://user-images.githubusercontent.com/29177976/188835023-b17aedf2-edd9-46d5-b925-bfc9f92feca3.png)

client view (Who just got permissions):
![image](https://user-images.githubusercontent.com/29177976/188834759-c441ec65-401d-44fc-b1f9-ae522246baa4.png)
![image](https://user-images.githubusercontent.com/29177976/188834992-0fa9c2a5-1dd0-46cf-8ff2-024c9b7d7248.png)

note: these will sync properly later, its just when they are initially given until either starting a round and returning, or rejoining the server from what I could tell.

### Reproduction steps

1. Have a client with all permissions join first (IE. host in game) who already has them.
2. Have a client with no permissions join second.
3. Grant the second all permissions (Server console or by GUI is fine).
4. Check the settings as the second client, notice all the sliders are probably at the far left or right, and some checkboxes won't match the first clients.
5. Have the first client (with existing perms) change to mission mode, then toggle some of the missions - notice the respawn submarine checkbox flickering on/off. This will effect in game too IE. its originally on but changing the missions to cargo only from all will result in no respawn shuttle from the desync.
6. Have the client who was given permissions either return to server lobby from a match or rejoin the server, they will now likely be in sync correctly and weird behavior like the above will not occur.

### Bug prevalence

Happens regularly

### Version

Other

### -

0.19.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/db60cf73b080d368afe411ee88ce3cd1aa7f761e and https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861

**Comment by Rokvach** [comment]
Tested on serverlist-cleanup branch which has the latest dev merged to it. Working correctly, closing.
