### ISSUE TITLE
Cannot rewire orca2 depth charge tube

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9842]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I removed the button to the depth charge tube because I accidentally hit it. I figured I would just wire it to the captains console. It turns out I cannot actually wire to the tube for some reason. So I permanently broke the depth tube. Not good.

I cant even access the wiring panel with a screwdriver. Clicking E does nothing.

This was in multiplayer but im not sure it matters.

### Reproduction steps

Remove the button to the depth charge tube with a wrench on the orca2.
Try to wire in a replacement.
Notice you cant.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Couldn't repro in the latest unstable
![image](https://user-images.githubusercontent.com/14351070/189103312-83ac85a6-1641-4b3d-bb0c-030541e2c091.png)

**Comment by gerakis** [comment]
Oh whoops, I mean the loader. The part you put the ammo into.
