### ISSUE TITLE
editing false output of a component from null to something in game does not immediately update output

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9844]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

in game updating an AND component's false output from empty string to non-empty doesn't change the current/future signals until the item gets new signals

### Reproduction steps

1. load AND comp sub from #9826 
2. enter test mode
3. select and comp, set false to 0
4. terminal has no signals coming in

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f384d2c7f95d1c76146a3d5df04b8aed9c29cbde

**Comment by Rokvach** [comment]
Tested, using provided repro steps, working correctly. Closing.
