### ISSUE TITLE
Only host can see extra deals from traveling tradesman (captains talent)

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9845]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the captain is anyone other than the host, only the host will be able to see the extra deals created by traveling tradesman. The captain himself (not the host) will only see a single deal. This is in multiplayer.

### Reproduction steps

Have someone host a game as a non-captain.
Have a second player join as captain.
Have that second player pick traveling tradesman.
Have the second player (the captain, not the host) check the sales. Only a single deal.

### Bug prevalence

Happens only sometimes.

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
hmmm ok it seams it only happens sometimes. Other time I see all 5 deals. A bit premature on my report, sorry.

**Comment by JeroonBosch** [comment]
Likely still relevant in the talent rework

**Comment by Regalis11** [comment]
No known steps to repro, closing
