### ISSUE TITLE
some bow shell pieces not set to "no ai target" by default

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9846]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the nose/tail pieces seem to *not* be set to "no ai target" by default (anymore?)

on almost all vanilla subs (except camel because it's unstable) (except winterhalter because it doesn't use any) the large "bow" shells are set to "no ai target" and IIRC this was the default? but when i placed some of them in unstable they were NOT "no ai target"

### Reproduction steps

place a bow shell piece in editor

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
To my knowledge, they've never defaulted to "no ai target". Why should they?

**Comment by Tsunder** [comment]
for new player convenience I suppose, really,

I thought they set by default since on vanilla subs they (+some more nearby shells when needed) are all set to no ai target.
