### ISSUE TITLE
winterhalter's bow shells are AI targettable

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9847]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

these two shells are AI targettable and i think they should be "no AI target" 
![image](https://user-images.githubusercontent.com/5103517/189048938-fb6089c5-c25d-49df-86a9-30c056eef3af.png)

though perhaps just the 90 deg shell if "possibly clipping" a monster with the other guns can work 
![image](https://user-images.githubusercontent.com/5103517/189049278-5cb6d153-82a4-4737-8226-a2bc49585fe4.png)

tail gun + its "no ai target" shells for comparison 
![image](https://user-images.githubusercontent.com/5103517/189049365-4778ffad-1166-4e51-8c74-f7a37af20c29.png)

### Bug prevalence

Happens regularly

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I don't see why the AI shouldn't be targeting these?

**Comment by MaaiG** [comment]
It seems to me this question seems to have arisen from some specific problems.

For example: While testing my submarine, I created a series of mud raptors around it. I wanted to see how they attacked the submarine and how long it would last.
I was very disappointed when the mud raptors immediately attacked the docking hatches of the escape pods and completely destroyed them. 
The escape pods were immediately captured and destroyed. The only questionable positive was that the monsters were stuck inside them and could not get further into the submarine.
My goal was to build a submarine from which to escape on an escape pod and the idea failed.
1. Monsters attack outer hatches and there is no way to protect them.
2. The Mostron spray the outer casing with incredible ease.
3. Getting inside the monster submarine rode through and sweep away any bulkheads in its way. The design of the submarine’s interior became meaningless.

However, it seems to me that the inclusion of the parameter "AI - do not attack" will not solve such questions.
Maybe need some reassessment of the hull strength of the submarine, the monster attacks, their AI, etc.

**Comment by Tsunder** [comment]
> I don't see why the AI shouldn't be targeting these?

well, I can't tell what the sub designer was thinking/the devs own sub build methods, but I do think that the bow and tail are similar situation on the winterhalter that the same rules would apply to both.

Inference from other vanilla subs is that the bow/nose are generally set as "no ai target", especially the parts that are out of gun arcs. 

For example on the tail of the winterhalter the lower slanted shell is set to "no ai target", it's just barely out of range of the coilgun there. 

Unless the bow's an intentional design deviation, I don't see why it should be "yes ai target"

**Comment by Regalis11** [comment]
We've generally disabled AI targeting on bow pieces if there's an empty space between the bow and the inner hull the monsters could get stuck inside, but I see no reason to disable it here.
