### ISSUE TITLE
Battery, Supercapacitor  - charge indicator does not rotate when the battery is rotated

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9848]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Charge indicator does not rotate when the battery is rotated!

### Reproduction steps

![Image 001_22-28](https://user-images.githubusercontent.com/93348499/189160500-986dbbe7-e51c-45fe-8c3c-9c281f1ddc41.png)
![Image 002_18-21](https://user-images.githubusercontent.com/93348499/189161761-42e30ec2-605c-41d4-a7fd-aea313035067.png)

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/59f2fe767592d2868f5f621e89e468b121a62c1c

**Comment by someone972** [comment]
So github will link these: This should have also fixed issue #9106

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/3f874d71a8cdc82d1d16314abdd6ae91f7e42098, no issues found, closing.
