### ISSUE TITLE
Excessive vote kick / vote ban messages when kicking via vote kick.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9849]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the current dev (08/09/2022) vote kicking a player lists a lot of messages for doing a singular vote kick ban. The below image is missing the voted to kick for messages from clients and includes a rejoin message after unbanning the client successfully, but it is an excessive amount of overlapping messages that probably should be attempted to reduce to a singular (more relevant) message.

![image](https://user-images.githubusercontent.com/29177976/189167800-98efaf9b-2846-47cd-ace4-fe647e674971.png).

### Reproduction steps

Vote kick a player in a server in unstable 0.19.4.0 (Or a later dev branch from there).

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.19.4.0 - dev commit https://github.com/Regalis11/Barotrauma-development/commit/f60a2ad003be4fcf1fd3e7d6c675a3f0dbcce861

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/7d1f75f8b44f7d4587c0abe640e19c596ad3400b

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/d206ec490f7210e2731599fac655a232d893b804.

In game the only message seen (to all clients) after a votekick is  "Reason: Banned"

![image](https://user-images.githubusercontent.com/29177976/190405764-0eb36b31-ab9e-458e-831d-fa36b60ead38.png)

and the client sees:

![image](https://user-images.githubusercontent.com/29177976/190405850-07ad1de5-aeb3-45bf-8966-f1646329041f.png)

I feel it should say kicked (not banned) especially given its the same even if the banduration from votekicks is set to 0 seconds and no ban actually occurs.

Otherwise, this is working fine and much less messages are shown now.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/f1b11472995af2a064ea4f85f091e7e435e87641

**Comment by NilanthAnimosus** [comment]
Tested, working correctly - closing.

Notes: It will still state its banned (even if a duration of 0) but clients ingame and the kicked client now see correct reasons.

![image](https://user-images.githubusercontent.com/29177976/192406417-adad5143-33df-4be6-ac86-c21ebcbe6ff1.png)
