### ISSUE TITLE
duct block damage mask broken

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9851]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

damage blocks damage mask are offset
pictured in editor, but shows up in game too

![image](https://user-images.githubusercontent.com/5103517/189232810-4116059a-9a1d-47d9-ad58-b95fcb052661.png)

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/df5c79e02e416eb524ac756762e5c97669c6ba66

**Comment by Regalis11** [comment]
Fixed a new issue with the sprite: it appeared as soon as the condition was below 100, even though it isn't repairable until the condition is below 80. https://github.com/Regalis11/Barotrauma-development/commit/c2ed4bb0a5af39184a9b13c0ee0a4b4161b6cdcc

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/373b429eaed92741b3dd4dd58397917e06ad8647, no issues found, closing.
