### ISSUE TITLE
Guns with shared loaders - get counted multiple times for upgrading at stations

### ISSUE THREAD

**Issue by AndyPuettmann** [Regalis11/Barotrauma#9852]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When sharing ammo loaders between multiple guns, they get counted multiple times in campaigns and their price for upgrades seems to go up exponential.

View at upgrader:
![image](https://user-images.githubusercontent.com/8194066/189410898-51e29332-5b1c-4144-80e5-94156330b315.png)
Physically there are:
4 guns: Slot 1, 2, 3, 4 sharing 2 loaders -> list entry: 1,2,3,4,2,3,4
2 guns: Slot 6 and 7 sharing 2 loaders. - List entry: 6,7,7
And another gun in slot 5 having a single loader - List entry: 5 

Example sub that has this issue happen:
https://steamcommunity.com/sharedfiles/filedetails/?id=2860698170

**Requirements** to have this happen:
**Multiple** guns, share **multiple** loaders.

4 guns, 1 loader -> No issues
1 gun, 2 loaders -> No issues
2 guns, 2 loaders -> last gun gets duplicated
3 guns, 2 loaders -> gun 2 and 3 get duplicated
4 guns, 2 loaders -> gun 2, 3 and 4 get duplicated

Also, this issue has only effects on the upgrade menu, it does not affect the submarine price or any other operational parameter.

### Reproduction steps

1. Open submarine editor (create a sub that can be loaded in a campaign - other details don't matter)
2. Place 2 guns
3. Place 2 loaders
4. Place 2 persicopes
5. wire periscope 1 to gun 1
6. wire periscope 2 to gun 2
7. link gun 1 to loader 1 and 2
8. link gun 2 to loader 1 and 2
9. save the sub
10. load in a campaign and talk to the upgrader person to upgrade the guns

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
I reported this same bug as #7916 a long time ago. They said its not actually a bug and they wont fix it. It certainly looks bugged to me but what do I know.

**Comment by AndyPuettmann** [comment]
Hm, I honestly only searched open issues.

Anyway, when you start with mixed gun types, I would expect quirks or problems to arise. As any gun type could trigger a change.
Like 2 coilguns and 2 railguns swapped to a chaingun - would have a 'to change list' that could contain up to 8 items.
However, starting with the same gun and loader type - should at least notice they add the guns multiple times.
Like it even shows the slot numbers of the gun multiple times. (Shouldn't an 'add to list' check if it is already there?)

And sadly this is the 'only' shortcoming of this system. The extreme upgrade cost. Anything else works perfectly fine and well.

**Comment by Regalis11** [comment]
> I reported this same bug as https://github.com/Regalis11/Barotrauma/issues/7916 a long time ago. They said its not actually a bug and they wont fix it.

I think I misunderstood your report: I thought the issue was about the turrets being essentially treated as one group that you need to upgrade/swap in one go, but looking at this more detailed explanation of the issue, there is definitely a bug here that we need to look into.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6505c1868dab88eab91e1ee9d891a9fffbbb67e3

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
