### ISSUE TITLE
Wrecked item issues megathread

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9855]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

# EDIT: DO NOT SEND THIS UPDATE TO LIVE. IT BREAKS A LOT OF WRECKS. REASONS BELOW

So I've made a ton of wrecks and ran into issues.

For future reference, in case an in-game wreckifier/piratifier/factionifier is implemented _wink wink_, this is where I'll dump any issues I find. The most common problems are:

# The bad sprites

Most of the wrecked machines are low-res sprites
![image](https://user-images.githubusercontent.com/73229309/189480264-48ca63e4-a1c1-49cb-b1cd-4b68fe8d728c.png)

Most of the machines also used legacy sprites that don't match their more recent counterpart. 
_From experience, setting condition to 0 and shifting color to a rusty hue is good enough so I don't use wrecked sprites any more as they are often uninteractable and can't be wired_

![image](https://user-images.githubusercontent.com/73229309/189480360-1b87374e-68fc-4156-8e0e-c9d1d14dbdb2.png)

There are also mismatched item sizes between sprite equivalents
![image](https://user-images.githubusercontent.com/73229309/189481152-d8d42b50-95bb-48ed-8fe9-6c095278de58.png)

Mismatched scales are also a problem:
![image](https://user-images.githubusercontent.com/73229309/189481228-524ac168-7330-4d2b-9c29-4f288b692319.png)

# Outdated functionality

As said above, wrecked machines and items aren't updated whenever a regular item gains a new functionality. This can result in no wiring, item categories that can't be contained and whatnot (#9271)

Another example includes Wrecked diving suit shelves not holding any of the new diving suits (PUCS, Slipsuit, Disposable or any modded suit)

**This calls for a push to merge wrecked items under their non-wrecked counterpart rather than replacing them so there's no discrepancy between normal and wrecked items (`Wreckedsprite?`)**

---------

What prompted me to open this is that you can see these discrepancies happening via the Jlobbet sub-wrecker which essentially swaps items to their wrecked counterparts. 
This is an essential tool for community-made content, but the discrepancies between wrecked and non-wrecked all get in the way of an efficient automation process.

**Comment by ubertpendragon** [comment]
**Size**
Most shell counterparts are identical but those 4 have a noticeable mismatch
![image](https://user-images.githubusercontent.com/73229309/190228688-6e0aaaeb-a523-48ec-a004-7dda2558e8bf.png)
![image](https://user-images.githubusercontent.com/73229309/190230842-f349a949-3622-4759-a21a-f3d36e0371aa.png)

**Comment by dinhtuananhfakefish** [comment]
Update wreck items in 91f7b8a735

**Comment by Regalis11** [comment]
Issues in the items have now been addressed, created a PR in our private repo https://github.com/Regalis11/Barotrauma-development/pull/3600

**Comment by Facehurt1** [comment]
pog

**Comment by ubertpendragon** [comment]
So items are now almost strictly "variants" of the functional items, with a recolor and condition set to 0.
This is good for item functionality BUT.....

**In short, rather than improving the wrecked texture... some items stop looking wrecked.** 
A lot of existing textures were also discarded instead of replaced with better ones

In the ticket I posted only the textures that were noticeable "low resolution". The problem was that, on the .png file, you had these items sprite that were much smaller than their counterpart:

Ladder vs Wrecked Ladder
![image](https://user-images.githubusercontent.com/73229309/201408279-a756b502-610d-4a67-b2c4-5ae29967e840.png)

Vents
![image](https://user-images.githubusercontent.com/73229309/201408771-fc3130f9-79ec-4548-aee7-c96788f3b6a4.png)

Coilgun
![image](https://user-images.githubusercontent.com/73229309/201408494-02aebd1a-9fef-446b-aa05-f0281415d8f1.png)


The textures had to be upscaled too much in the spritesheet. 

It's not a problem for some of the bigger items that can be say covered with rust decorations, example: navigation terminal with minor decoration + tilt
![image](https://user-images.githubusercontent.com/73229309/201410015-6a511878-a0bb-4a3f-a8f8-63c4cfec1861.png)

**Comment by NilanthAnimosus** [comment]
To add to issues I have noted:

Wrecked periscopes have no animations when interacted with for arms and such (so you swim freely near them) however they do hide the inventory as if you grabbed them until you get a distance away, causing confusion.

Wrecked loaders (of all varieties) cannot be interacted with but did appear to spawn with ammo (or have such in their wreck files preplaced such as endgame prototyping), It feels strange to have these none-interactable with clearly undamaged boxes inside them unless it was a deliberate choice in the endgame prototyping.

**Comment by Regalis11** [comment]
Restored some of the sprites in https://github.com/Regalis11/Barotrauma-development/commit/1a73052b2b8a44dbfef40cd86d19aaccf685b1e5.

TODO:
The following items are now using unmodified copies of the normal sprite, and should be modified to fit the wrecks better. All of these are in MiscWrecked.png:
- [ ] Ladder 
- [ ] Vent
- [ ] Medicine cabinet

**Comment by dinhtuananhfakefish** [comment]
Added in 2e0e7180ce

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
