### ISSUE TITLE
Text Display component set_color input not working on crafted components 

### ISSUE THREAD

**Issue by JohnMeadow1** [Regalis11/Barotrauma#9856]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![obraz](https://user-images.githubusercontent.com/23294139/189479855-f8c51c3e-9850-42a6-88bd-8d1d5fb2b1ba.png)

The top of the Text Display components was detached from pirate vessel and works properly
Bottom one was crafted and ignores set_color input. 

Both are wired to the same memory components. 
One memory component sets text_color, the other sets color.

In image bellow both colors are set to white
![obraz](https://user-images.githubusercontent.com/23294139/189480020-bc605fbd-6462-4c4a-97f5-96e147761cf1.png)

Looking a the Save file. The one that is looted has a flag IsActive="True"  the crafted one does not.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Could no longer reproduce in the latest unstable, seems to have been fixed

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/5da5cc44d9ea552da144b7cff41cab3eba66276c, no issues found, closing.

notes:

Tried with pre-existing, sub editor spawned and crafted text displays, using a colour component and a memory component and both were able to set the colour correctly of both background and text individually, though the format did require #,#,# (or #,#,#,#).
