### ISSUE TITLE
Water level calculation is flawed

### ISSUE THREAD

**Issue by JustMarok** [Regalis11/Barotrauma#9858]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When exploring sub editor, i noticed that game calculates water level in connected hulls in the wrong order. When hulls are connected, game first calculates water level percentage in each hull separately and then addes thouse percentages up. This results in incorrect water level readings for connected hulls of different hights. 

### Reproduction steps

1 Enter sub editor
2 Put 3 hulls of obviously different sizes (2 big and one small) 
3 Connect them, but don't put gaps between them
4 Flood one of them (small one) 
5 Status monitor will say that water level is 33%, when it clearly isn't

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell

```

**Comment by Regalis11** [comment]
Thank you for the report! The monitor didn't actually add the percentages up, but calculated the average of the water percentages (which is still incorrect of course). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9fd5156f741afec422b3f845d0a219fadeb46c12

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/373b429eaed92741b3dd4dd58397917e06ad8647, no issues found, closing.
