### ISSUE TITLE
Wrecked Coilgun/Railgun missing launchimpulse

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9859]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Wrecked Coilgun/Railgun missing launchimpulse in their `Turret` property

The projectiles fall straight down leaving the barrel:
![image](https://user-images.githubusercontent.com/73229309/189499315-55d17ed3-05d3-44cc-a8a8-7ef3cebd2076.png)

Here's what it should look like: 
`<Turret launchimpulse="80.0"`

Not sure what changed in projectile behaviour

### Version

0.19.3.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/94cdff1241c419128fbebf5f592236b20e427743

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
