### ISSUE TITLE
[Unstable] Only the first store works in multiplayer - the rest fail purchases

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9861]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When purchasing goods in campaign multiple stores seem to break each round.

It appears the first you buy from is the only one that will work for all players, the rest allowing you to add to cart but when you purchase the stock values return and next round none of those purchases counted.

If a store has shared items (IE. two stores sell fuel rods or batteries) and one of those was your first store, those goods will be purchasable from the other stores that also stock them.

### Reproduction steps

1. Start a fresh multiplayer campaign - no clients required (just the host is fine)
2. Purchase something from a store (IE. a wire from the engineer merchant) - This will be the only working store.
3. Buy something that is not present in the store you bought from previously from another (IE. fentanyl from medical).
4. Note the stock goes down when adding to cart, but back up when purchasing and your money will re-sync usually to its previous value.
5. Find when undocking the other goods you purchased (IE. fentanyl) are not present but the first merchants (IE. wires) are present.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.19.4.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Koku0** [comment]
I've found this issue too. Very annoying :(

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a539468bad6e703a63921b9eb7651f47a35736e9

**Comment by Rokvach** [comment]
Tested, stores are working correctly now, we didn't find any further issues. Closing.
