### ISSUE TITLE
Low velocity projectiles inside flooded hulls after reloading, 

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9867]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The velocity of projectiles such as Harpoons decreases dramatically when shot inside flooded hulls shortly after reloading / entering water.

This is most likely a side effect of slowing down the fall of items that splash into water as you'll often see a water splash at the edge of the hull

https://user-images.githubusercontent.com/73229309/190225496-be624cf5-bfc7-43e4-9f44-19d3e002cc6f.mp4

### Reproduction steps

1. Create a hull and flood it like a swimming pool  
2. Equip an empty harpoon gun and pick up 6 harpoons
3. Jump inside the pool and start shooting
4. Slow projectiles

It's more noticeable on grenade launchers since you load each grenade individually

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/88b3bfd5818307322a17d1b7f1ed0f47b25b8162

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/fe6a8734604346c4a2beb086b0d0d71709523bb1, no issues found, closing.
