### ISSUE TITLE
R-29 bots try to fix unreachable pump preventing any other tasks

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#9870]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Vid of it happening
https://streamable.com/tz8tq8

### Bug prevalence

Happens regularly

### Version

Other

### -

Stable

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
How did you do that cool god's eye view?

**Comment by Udrakan** [comment]
type freecam into F3 console
This happens with leaks too. Not just the pump. Pic:
![image](https://user-images.githubusercontent.com/59519434/190269765-335ba014-7287-478d-83a7-da532cc3ad75.png)

**Comment by gerakis** [comment]
Ok cool thanks. This might be a duplicate of #9186 which I think they already fixed. That was for the hull but I think its all related to that false floor thing.

**Comment by Udrakan** [comment]
Weird. I've written both R-29 and R 29 into searchfield and didn't find it. Deleting

**Comment by Regalis11** [comment]
Seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/9186, but the fix is not included in the stable version yet
