### ISSUE TITLE
Mining mission names are displayed incorrectly

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9871]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The name of the mineral isn't replaced in the mission popups, presumably because we use the name of the prefab directly instead of using Mission.ModifyMessage

### Reproduction steps

1. Trigger an event that unlocks a mineral mission (e.g. `triggerevent missionevent_collectminerals_set1`)
2. Talk to the outpost manager

![image](https://user-images.githubusercontent.com/14351070/190384680-9b803aab-c114-4497-b658-0d5a7f5cb7ab.png)

### Bug prevalence

Happens regularly

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1038619a128bd93a5342288ab28506091bb3cf18 and https://github.com/Regalis11/Barotrauma-development/commit/2b63d14d805d761dff52209f537e2e1b2a6a5e83

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
