### ISSUE TITLE
Last joining player with permissions doesn't see existing permissions of other players that joined before them

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9873]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing networking issues in dev we ran into a issue where if you joined last or after other players and tried to edit other players permissions the permissions were all unticked even though those players had all permissions. 

You also don't see the crown or a star next to the players name in tab menu crew list. 

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### -

Branch: dev Commit: https://github.com/Regalis11/Barotrauma-development/commit/ca8b2264ff5b03ff831f1f525e347ab08990655b

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/616476ee57e501824d64eebef2f2a25c4d939e16

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
