### ISSUE TITLE
Character tab menu layout is messed up if you aren't controlling a character

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9875]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the talents aren't shown anymore the character information layout is broken
![image](https://user-images.githubusercontent.com/7299826/190388514-1b06f2f2-737a-43a2-a6f8-78628390e329.png)

### Reproduction steps

1. Start a single mission mode in multiplayer
2. Go to freecamera
3. Check character tab menu

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### -

Branch: dev Commit: https://github.com/Regalis11/Barotrauma-development/commit/ca8b2264ff5b03ff831f1f525e347ab08990655b

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/37c91e588fa7c402f3f9131b513c25e763075ca0

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
