### ISSUE TITLE
Ban message is shown incorrectly if you don't give a ban reason

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9876]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/7299826/190388936-fa1c1ecd-4998-46f2-83ed-ac32c1077d52.png)
![image](https://user-images.githubusercontent.com/7299826/190389052-83bd470d-d6f6-4058-8e49-8752c2a98f36.png)

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### -

Branch: dev Commit: https://github.com/Regalis11/Barotrauma-development/commit/ca8b2264ff5b03ff831f1f525e347ab08990655b

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Note for testing: seems to only occur if another client issues the ban (not when the server executes the ban command in the server console). Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a7ba74c060c43aae0716e000d643c1a73c4d96db

**Comment by Rokvach** [comment]
The prompt is shown correctly now but not the banlist reason
![image](https://user-images.githubusercontent.com/7299826/192278713-d79c6f86-6ca2-482f-8fad-ab0562cff81e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6e9ee43c9d84cac97c43b26b58c6feccd2d6c02e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
