### ISSUE TITLE
Dedicated server doesn't display "Server Shutdown" message to clients when closing server console

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9879]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using a command to close the server shows the message correctly

Clients does get a timed out message after they wait for some time if the server console has been closed using the console's close button "x"

### Reproduction steps

1. Host a dedicated server
2. Join it as a client
3. Close the server console
4. Notice the message you get

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### -

Branch: dev Commit: https://github.com/Regalis11/Barotrauma-development/commit/ca8b2264ff5b03ff831f1f525e347ab08990655b

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This doesn't seem like something we can/should fix - if the server is shut down ungracefully it can't communicate to the clients that it was shut down (so it makes sense for the client to assume they timed out).
