### ISSUE TITLE
Having NPC's health interface open when your character has nausea and vomits closes the interface but still keeps the character grabbed

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9880]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Noticed in multiplayer, in singleplayer you don't have access to NPC health interfaces. But this should also happen when checking the health of bots and other players. 

As the title says if you vomit while you are checking a outpost NPC the health interface closes but you are still grabbed to the NPC

It should instead also lose the grab or then re-open the health interface while your character is done vomiting

### Reproduction steps

1. Start multiplayer campaign
2. Drink Ethanol until you start vomiting
3. Find a NPC and access their health interface
4. Wait until your character vomits
5. Notice that the health interface closes but you are still grabbing the NPC

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### -

Branch: dev Commit: https://github.com/Regalis11/Barotrauma-development/commit/ca8b2264ff5b03ff831f1f525e347ab08990655b

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/900c19da72a20efc46da9eab72ede791ccc6d84e and https://github.com/Regalis11/Barotrauma-development/commit/b8f826171f65fb379bfb3763cd1a8b6f95c07edb

**Comment by Rokvach** [comment]
Tested,working correctly. Closing.
