### ISSUE TITLE
Missions sometimes cannot be selected / are out of sync in multiplayer campaigns

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9881]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Created a fresh Multiplayer campaign with one other client, found ourselves unable to select the missions (3 standard and 1 event mission) on the map, after reloading the save or redocking the missions will change location showing they are likely out of sync between client and server when unlocked.

https://i.gyazo.com/2abd8a846f0d3aecfce0e92c51cb5003.mp4

### Reproduction steps

1. Start a new multiplayer campaign using the seed "yHqE2iJ3" 
2. Grab missions and any event that grants a mission, should break from the first mission though taken.
3. Attempt to select missions in the map UI.

### Bug prevalence

Happens every now and then

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2df51a2fe4148068b0958ab47b4fca93f6a9fd91

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/bdfc31d715e43fd0b20fef137eb0e3a3dc243114, no issues found, closing.
