### ISSUE TITLE
Chaingun on Typhon 2 is connected to a blankperiscope

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#9885]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/99462070/190853642-95c37fd4-e0de-49e3-a379-c554ec3be26d.png)

### Reproduction steps

check the chaingun on typhon 2 in the sub editor

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eceb25f11208160c93e0baa3b3be113fdcbe4738
