### ISSUE TITLE
Missing mission localization hides mission checkbox and doesn't show an english alternative

### ISSUE THREAD

**Issue by Gaguiglal-BR** [Regalis11/Barotrauma#9887]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![epic bug report](https://user-images.githubusercontent.com/113803116/190876845-62d28054-d810-4b1f-a829-7c3fa56fecd4.png)

so that in the image was supposed to be an mining mission, but it dosen't appears at all.
after trying to do the mission the location of the objective apperead on the sonar (a cave).
However after collecting all minerals from the cave the mission did not completed.

### Reproduction steps

1. select any mining mission

### Bug prevalence

Every time i play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by thegrb93** [comment]
Same issue as https://github.com/Regalis11/Barotrauma/issues/9881 perhaps

**Comment by thegrb93** [comment]
Or https://github.com/Regalis11/Barotrauma/issues/9871

**Comment by Gaguiglal-BR** [comment]
> Same issue as #9881 perhaps

i was playing solo on campaing mode, i also tried to do a solo mutiplayer server and the same thing happened

**Comment by esirprus** [comment]
this may due to localization. because if you choose language to English and **restart** the game, then you can see the mission and select it

**Comment by gerakis** [comment]
If you deconstruct the minerals before docking it wont succeed. You have to leave the minerals intact.

**Comment by Gaguiglal-BR** [comment]
> If you deconstruct the minerals before docking it wont succeed. You have to leave the minerals intact.

on the first time the bug happened i was in the barsuk (no desconstructor)

on the second i was in a custom sub called admiral (no descontructor either)

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/43eb0a8fb27f532a3b23dfaba500cce2c41c4eec (Essentially 0.19.5.0 with a few more changes).

When using Portugues brasileiro in a campaign (and not being on english then changing to that which gives different behaviour such as showing a description and checkbox) - the checkbox will not render (But still let you click it while its invisible to select said mission). the text is also missing but likely just missing localization.

![image](https://user-images.githubusercontent.com/29177976/191004353-3fe14261-cd3e-44c9-8d00-d7757449e84b.png)

![image](https://user-images.githubusercontent.com/29177976/191004677-8bd3843a-bc71-432a-92fe-e926f49c8aec.png)

The above is specially a quartz mining mission I tested with. No sonar labels appeared either for the mission (but it was active).

![image](https://user-images.githubusercontent.com/29177976/191005666-c6457a1e-4b34-4642-8391-f46e341250dd.png)

once mining from the only cave on the map, with the only quartz, the mission does complete correctly:

![image](https://user-images.githubusercontent.com/29177976/191005798-ed1b901a-2f9d-426c-9688-a12e111d2639.png)

so its likely the wrong minerals were mined than what was required (or from a different cave, I think you need to mine the specific indicated minerals and anywhere else is yours).

Played from launching the game in the users language, and appears to just be an issue with the checkboxes and missing localization not at least showing english.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/457ca7cf4e594833d4b72e126bf4392ff9181593 and https://github.com/Regalis11/Barotrauma-development/commit/c9302941f66ab2bec7211eab50cd0b244d691c5a

**Comment by Regalis11** [comment]
Fixed the mission success, failure and sonar label texts in https://github.com/Regalis11/Barotrauma-development/commit/65bfa5f1dfd1849fadd484b1f89952592a0342e7. These were also using an empty string as a fallback instead of the English text, excluding the "mission success" message, which for some reason used the hard-coded "mission completed successfully".

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/d48d56603c9bd7b5ca6e1f2824797975e3a21206, no issues found, closing.
