### ISSUE TITLE
Docking ports lights cant be turned off.

### ISSUE THREAD

**Issue by Psyduckdeluxe** [Regalis11/Barotrauma#9888]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Docking port lights cant be turned off.

have to reduce them to 0,0,0,0 to actually turn them off. and i assume they are still running in the back ground then.

### Reproduction steps

1. place docking ports, 
2. turn off lights  "is on" 
3. start game with something docked.

Lights will still be on.

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
This is actually not a bug. The lights on the docking port indicate the state of the port: the green lights turn on when docked, and the red ones when not. If you want to completely disable them, setting the color to black the way you described should work.
