### ISSUE TITLE
Motion Detector detects pet as monster

### ISSUE THREAD

**Issue by N58** [Regalis11/Barotrauma#9889]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Motion Detector detects pet as a monster. It happens since either Urban ExpansesUpdate or last 3rd Anniversary Update. 
It would be perfect if Motion Detector had Target type "Pet" in dropdown, so you can choose between Human, Monster, Pet and Wall.

### Reproduction steps

1. Open submarine editor, open some submarine.
2. Place Motion Detector and Text Display.
3. Set Motion Detector's false output to 0.
4. Connect Motion Detector' `state_out` with Text Display's `set_text` using wire.
5. Run test.
6. Open console, use `enablecheats` and spawn some pet somewhere, for example: `spawn peanut cursor`
7. Grab the pet and move through Motion Detector's detection zone.
8. Look how Text Display shows value `1` when there is Pet inside of detection zone.

I attach video to show what happens.

https://user-images.githubusercontent.com/21145217/190898356-db42047a-bf8a-4075-9468-4b3a75261fe7.mp4

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/24d283b3d79ba6a2a23b2039e9e56d0bea50e5df

**Comment by Tsunder** [comment]
What would pets be detected as, then?
Is there a new pet option? :O

**Comment by Regalis11** [comment]
> Is there a new pet option? :O

Yep

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/8ee062f423eaf2f718cc1e9763aee1099fba09dd

Changes do not work, appears it checks for target type human / monster and skips the block of code containing the changes for checking pets.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5c5f8d2489ace0b114f625b0bdbddb09df319de6

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/5c5f8d2489ace0b114f625b0bdbddb09df319de6, no issues found, closing.
