### ISSUE TITLE
Quality arrow in sub editor only affects the same item identifier

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9890]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the arrows beside the quality field for an item in editor only affects selected items of the same identifier. (i.e., 2 steel knives)

expected is for all items that have a quality to be edited (i.e., editing a knife and a screwdriver should work)

entering a value (0-3) works normally.

### Reproduction steps

1. place screwdriver
2. place wrench
3. select both
4. press arrows on quality field
5. only the focused item is edited

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Couldn't reproduce:
https://user-images.githubusercontent.com/14351070/191008635-6c05133c-0faa-4e6b-a5e7-e0a5cda6aa5f.mp4

**Comment by Tsunder** [comment]
hmm, that's odd, i can't reproduce it now either.
