### ISSUE TITLE
OnItemDeconstructedInventory / CharacterAbilitySpawnItemsToContainer won't spawn items if no items result of deconstructing

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9891]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

OnItemDeconstructedInventory or CharacterAbilitySpawnItemsToContainer won't spawn items if the deconstructed item itself doesn't generate items as part of its `Deconstruct` property

In other words, take **Atmos Machine**:
If you change the deconstructed item from  `<AbilityConditionItem tags="alienartifact"/>` to  `<AbilityConditionItem identifiers="alienblood"/>`, nothing happens.

Alien blood doesn't have a Deconstruct line.
Adding a simple   ` <Deconstruct time="5" requireddeconstructor="geneticresearchstation"/>` it still didnt work

```
<Deconstruct time="5" requireddeconstructor="geneticresearchstation" chooserandom="true" amount="0">
      <Item identifier="huskeggs" />
</Deconstruct>
```
didn't work either, as I tried to set the amount to 0 to not spawn anything
Only after the amount was set to 1 that deconstructing Alien Blood and spawning huskeggs started triggering the talent

Therefore I assume the ability NEEDS an item to spawn from deconstruction to trigger

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

**Comment by Regalis11** [comment]
This isn't a bug: the Atmos Machine talent is configured to trigger when the deconstruct products are placed in your inventory (`AbilityEffectType="OnItemDeconstructedInventory"`). If you want to make it trigger when the item is deconstructed, regardless of the output, you should change it to `AbilityEffectType="OnItemDeconstructed"`.

**Comment by ubertpendragon** [comment]
I can say with certainty that if you swap  `<AbilityConditionItem identifiers="alienartifact"/>` with `<AbilityConditionItem identifiers="crate"/>` (which doesn't have a deconstruct component) on Atmos Machine, it will yield nothing

**Comment by Regalis11** [comment]
Yes, that is the expected behavior. Don't use `OnItemDeconstructedInventory` if you don't want to tie the behavior of the talent to the deconstruction output.
