### ISSUE TITLE
Bot clown medic will not use horn to heal crew

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9895]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bot medics with True Potential will not use their horn to heal crew. Instead they waste a morphine for a very minor 5% injury when a single honk (free) would do just fine.

Bot medics are extremely wasteful in general. They will treat any injury no matter how minor.

### Reproduction steps

Get an assistant up level 4 and give him true potential.
Get him a clown costume and horn
Assign him to medic
Hurt some other member of the crew
Watch him waste morphine

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Yeah, bots can't really use most of the talents. We're currently reworking the whole talent system and most likely getting rid of this talent, so I don't think we'll be addressing this.
