### ISSUE TITLE
Bots keep jumping off cliff in colony outpost

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9896]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In some outposts that have the type of admin building shown in the video, bots keep jumping off the side of the building. They fall and injure themselves. They do it over and over till they die if you wait long enough.

https://user-images.githubusercontent.com/16128947/191156270-ab1313b6-5366-4638-b4aa-54e5971ecb0d.mp4

### Reproduction steps

Have a bunch of bots on your crew.
Go to a colony that has that configuration of building. These are the big colonies that have a population count in the docking area.
Climb up to the room above the quest giver.
Watch bots jump off all day.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/641e871b9ffd9b37692ff661c9d610f67736918e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
