### ISSUE TITLE
Bots using pulse lasers will not shoot ice spires

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9897]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you assign a bot to man a pulse laser, he will have trouble shooting ice spires for some reason. I can hear him trying to shoot it, but its like he is just spamming the trigger and not actually shooting. I hear him charging it on and off really fast. If I switch over to the bot and take manual control of him (its single player) I can easily shoot the spire. It wasn't a matter of distance either because we ran right into it.

They still seems able to shoot normal enemies. 

### Reproduction steps

Get a bot and a pulse laser
Put him on a pulse laser near the front of your sub
Get close to an ice spire
Watch him fail to shoot it, spam the trigger, and generally freak out

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
I think this might also effect chaingun. Anything that has to "spin up" or charge seems to be effected.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2cc7d0ce3acca8015202ba6f607404ac809d4904

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
