### ISSUE TITLE
Small Role-Specific Tutorial Bugs

### ISSUE THREAD

**Issue by CCheek** [Regalis11/Barotrauma#9898]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I'm aware it's bad practice to report multiple bugs in the same report, but they're closely related and I discovered them within a short time of each other. Bug number one is that in the role tutorial, it tells you to go to the room to the right, however the message disappears if you go back to (or select a role within) the starting room, potentially causing the user to not be able to read it fast enough. Bug number two is if you enter the room and then select to try a different role, the menu freezes, not letting you select a different role, nor continuing the selected tutorial (you can still move around though). Bug number three is if you open a door before selecting a role (any door or hatch other than the first 2) without closing it, the window to actually do the tutorial (including the bugged option mentioned above) doesn't pop up at all.

### Reproduction steps

1. In Beta, open tutorial
2. (Optional to reproduce bug number 3, but doesn't cause bug number 2) Open a third door.
3. Get to the portion with the role selection and select a role (I only tried with Captain and Mechanic, but I imagine they happen for any.)
4. Go to the starting room (bug 1).
5. Go to the room it actually wants you to.
6. If you didn't go through step 2, click change role (or whatever that button says), and it'll freeze-ish.
7. Bonus bug: Before step 6, if you select a role other than the first one you select before going to the room on the right, the game will let you walk around, but doesn't give you a keycard, which could lead you you potentially getting stuck.

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by ekqvist** [comment]
Potentially fixed in Regalis11/Barotrauma-development@701dd27

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
