### ISSUE TITLE
Discord integration/ VoIP

### ISSUE THREAD

**Issue by Crystalwarrior** [Regalis11/Barotrauma#99]
Allow servers to use discord for voice communication or implement a VoIP system.

Challenges: convincing proximity/positional audio, radio effects, radio distance cut off, general immersion tweaks. For discord - coding a bot that communicates with the server.

**Comment by Crystalwarrior** [comment]
Good case studies: intruder, sub rosa, arma

**Comment by brandon-ray** [comment]
Discord has an interesting solution for VoIP in game: https://discordapp.com/gamebridge
It is in private beta, I am sure they will support proximity voice though.

**Comment by BillCombs** [comment]
Something to consider when adding VoIP: the game should have settings that let you disable it just for yourself or for the whole server, if you are an admin. You also should be able to mute individual players just for yourself(others would still hear them if they wanted to).
Some players in games with such feature tend to Scream, or play loud music and sounds. The game would become hell without anything that would let you deal with that.
