### ISSUE TITLE
Permanently smoking panel in winterhalter bridge

### ISSUE THREAD

**Issue by gerakis** [Regalis11/Barotrauma#9900]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The "Breaking News" panel in the winterhalter bridge room is permanently smoking for some reason. 

<img width="965" alt="unfixable panel" src="https://user-images.githubusercontent.com/16128947/191285612-b9b1e383-48c5-4b71-b60f-0f2639523701.png">

I think what happened is I upgraded my electrical devices so they have more max health, but this panel cannot be repaired (or destroyed). So its just permanently at half health and smoking now.

### Reproduction steps

Buy a winterhalter
Upgrade the electrical devices so they have more max health at the upgrade merchant
Panel is now permanently smoking

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd3f355a2e4173f3d3b6a1c33ba1fe2a7bf38251

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
