### ISSUE TITLE
Boom Stick shoots in bursts of 3 shots, not 2

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#9901]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As title says, the Boom Stick weapon shoots in bursts of 3 if you reload it during the burst. Guessing its function is ripped straight out of the deadeye carbine with barely any modification.

### Reproduction steps

Get a Boom Stick and a ton of shells, hold down fire and spam the shell hotkey, you will end up shooting 3 shells per burst instead of the two.

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
My idea is to let the Boom Stick fire 2 shells in 1 shot by setting the "projectileCount" to "2" and change the "reload" to "1". Instead of copying StatusEffects from Dead Eye.

**Comment by Regalis11** [comment]
Actually, it did not seem to fire in bursts at all - it was possible to fire it 10 times per second if you reload quickly enough. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0a4c103acb9ab97e2136fd5412bcf37979a2379a by making it fire in bursts of 2

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
