### ISSUE TITLE
OnApplyTreatment doesn't work when swinging a syringe

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9903]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

`<AbilityGroupEffect abilityeffecttype="OnApplyTreatment">` only works when applying meds through the medical UI

Stabbing someone with a syringe doesn't count (probably because syringes are a "melee weapon")

### Reproduction steps

1. `Givetalent "Bedside manner"`
2. Grab morphine
3. Stab vs UI injection
4. Buff vs no buff

**Comment by Regalis11** [comment]
This is intentional: otherwise there'd be no way to differentiate between using items through the medical UI and by stabbing people with them. If you want melee attacks to trigger the talent too, you should use the OnAttack effect type (probably with a check for the item being a medical item).

**Comment by ubertpendragon** [comment]
Understood, you might want to fix Bedside manner then

**Comment by CorruptedPants** [comment]
> you should use the OnAttack effect type 
OnAttack is not triggered by medical items, neither swinging nor fired from a syringe gun.
