### ISSUE TITLE
[Modding] Weapon spread can't be increased via RangedSpreadReduction

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9905]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It's not possible to INCREASE spread via talent or affliction using a negative value.

Neither
`<CharacterAbilityModifyStat stattype="RangedSpreadReduction" value="-0.5"/>`
nor
`<StatValue stattype="RangedSpreadReduction" value="-0.5"/>`

It's only possible to postively affect spread and not negatively, unlike other stats like Movespeed (Nausea) or RangedAttackSpeed (found in Commando talent)

**Comment by Regalis11** [comment]
Could not reproduce. Negative spread reductions do seem to increase spread. Note that the change is not an absolute value, but a divisor on the original spread value:

`float spread = MathHelper.Lerp(Spread, UnskilledSpread, degreeOfFailure) / (1f + user.GetStatValue(StatTypes.RangedSpreadReduction));`

**Comment by ubertpendragon** [comment]
I supected that negative spread applied to Revolver did nothing, since the spread is   `<RangedWeapon barrelpos="29,11" spread="0" unskilledspread="2"`

But then I went testing it on Shotgun and didn't notice negative spread doing anything at all
