### ISSUE TITLE
[Modding] AbilityConditionHasItem can't actually identify specific items

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9906]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

AbilityConditionHasItem can't use identifiers="item", only tags, which means you can't actually use specific items as a condition unless you specifically tag them.

https://github.com/Regalis11/Barotrauma/blob/6cc100d98cc99e758f4ea0750528a2aa68429c0a/Barotrauma/BarotraumaShared/SharedSource/Characters/Talents/Abilities/AbilityConditionals/AbilityConditionDataless/AbilityConditionHasItem.cs#L11

It probably should

**Comment by Regalis11** [comment]
This isn't the case, both tags and identifiers are accepted here.

**Comment by ubertpendragon** [comment]
It either doesn't work or considers the item as part of the inventory to work; if you use identifiers you will not lose the buff when you stop equipping the item
