### ISSUE TITLE
[Modding] Non-deconstructible items in deconstructor prevent cancelling

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9907]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you spawn an item in a deconstructor ala Atmos machine using `CharacterAbilitySpawnItemsToContainer`, the items will appear in the deconstruction queue

If the item spawned doesn't have a `Deconstruct` property, you won't be able to cancel deconstruction until it is processed and move to the output inventory

![image](https://user-images.githubusercontent.com/73229309/191638570-b0b1b7e5-0a01-45c2-8439-4d172a2ca48b.png)

### Reproduction steps

Replace Atmos Machine spawned item by Lead
Deconstruct a bunch of artifacts
Lead will appear and jam the queue

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05f22ac9e4f433cc141bdcb1e64b304aad79fc72

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/00f795275d20e02a91cf05792d31934e9a358ffe, no issues found, closing.
