### ISSUE TITLE
OnItemDeconstructedInventory triggers several times based on deconstruct yield

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9908]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

`OnItemDeconstructedInventory` will trigger several times if the deconstructed item yields 2 or more items.
On Atmos Machine, this means the 20% chance is triggered twice in the case of artifacts

Try deconstructing different weapons with this (it has a 100% chance of triggering)

```xml
    <AbilityGroupEffect abilityeffecttype="OnItemDeconstructedInventory">
      <Conditions>
        <AbilityConditionItem tags="gunsmith"/>
      </Conditions>
      <Abilities>
        <CharacterAbilitySpawnItemsToContainer>
          <StatusEffects>
            <StatusEffect type="OnAbility" target="UseTarget">
              <SpawnItem identifiers="scrap" spawnposition="ThisInventory" spawnifcantbecontained="false"/>
            </StatusEffect>
          </StatusEffects>
        </CharacterAbilitySpawnItemsToContainer>
        <CharacterAbilityApplyStatusEffects>
          <StatusEffects>
            <StatusEffect type="OnAbility" target="This">
              <GiveSkill skillidentifier="weapons" amount="2"/>
              <GiveExperience amount="100"/>
            </StatusEffect>
          </StatusEffects>
        </CharacterAbilityApplyStatusEffects>
      </Abilities>
    </AbilityGroupEffect>
```

Diving knife
![image](https://user-images.githubusercontent.com/73229309/191731082-2039a94a-a4c5-49fe-8363-aa237512fa0c.png)

SMG
![image](https://user-images.githubusercontent.com/73229309/191731196-c4b4843e-88fc-4e0a-9fc7-11c6cf9df409.png)

**Comment by Regalis11** [comment]
As I mentioned in #9891, 

OnItemDeconstructedInventory triggers when the deconstruct products are placed in the inventory. If you want to make it trigger when the item is deconstructed, regardless of the output, you should change it to AbilityEffectType="OnItemDeconstructed".

**Comment by ubertpendragon** [comment]
> If you want to make it trigger when the item is deconstructed, regardless of the output, you should change it to AbilityEffectType="OnItemDeconstructed".

Right, it also requires changing `spawnposition="Thisinventory"`

The problem with Atmos Machine triggering several times remain, I don't know what the benefits of using OnItemDeconstructedInventory are over OnItemDeconstructed

**Comment by Regalis11** [comment]
> I don't know what the benefits of using OnItemDeconstructedInventory are over OnItemDeconstructed

It's specifically for evaluating the deconstruct products (whether something came out of deconstructing), not the action of deconstring itself. As for why we're using it in this case, I'm not sure, but afaik we're going to be getting rid of this talent anyway in the upcoming talent rework.
