### ISSUE TITLE
missing gap on outpost prison room

### ISSUE THREAD

**Issue by deltanedas** [Regalis11/Barotrauma#9909]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

In the room with 3 cells and buttons, there is a cap missing between the main room and the button room. Water does not fall down into it.
Have only noticed it once but it's probably easy to reproduce.

### Reproduction steps

1. find this room
2. flood it, i flooded the one to the right of it if it matters.
3. observe no water flow as described

### Bug prevalence

Just once

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Linux

**Comment by deltanedas** [comment]
![13:33:35](https://user-images.githubusercontent.com/39013340/191748821-41c7c92c-3c09-4c6e-b511-c3319df6ff8e.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ead941b1def4abd86e96e6837b3be3899b403aad

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
