### ISSUE TITLE
wire grabbing area in wiring UI shrunk with new margins

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9913]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

margins "eat" some of the wiring UI space that would otherwise make grabbing wires a lot easier (since they're more spread out as it goes further

![image](https://user-images.githubusercontent.com/5103517/191851858-0fc449cc-922e-4b2b-bbfc-f8ff5b189b12.png)

would be nice for the wiring UI to be bigger window too (+20%?)- the top wires here are barely visible and hard(er) to grab since they go into the window top.

Picture of normally wired junction box for comparison of wire density
![image](https://user-images.githubusercontent.com/5103517/191852193-9bf397d3-3033-4138-a3e8-275b4599989a.png)

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by MaaiG** [comment]
It would be good if something changed in that regard https://github.com/Regalis11/Barotrauma/discussions/7881
