### ISSUE TITLE
linked UI/status monitor offset

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9914]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

opening a status monitor that is linked+display when linked nav for repairs has really bad offset UI

Mooncrusher 
![image](https://user-images.githubusercontent.com/5103517/191852761-646c7c23-370f-4481-9259-2913ef7eb158.png)

Dugong
![image](https://user-images.githubusercontent.com/5103517/191852783-b2263f6c-848e-4b84-ba25-6c642f2a68ac.png)

### Reproduction steps

1. load dugong
2. throw emp grenade at monitor (in baro, not IRL)
3. wait for explode
4. screwdriver on the status monitor 

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
Pretty sure they overhauled this for the new update. Check the closed issues. I could be wrong though.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/36705807475ffa604f003df6d4d19353a8ed5ff7

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
