### ISSUE TITLE
some crawler related missions are confusing when compared

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#9915]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

there's like 10 crawler swarm related missions by now and the rewards and descriptions of some of them are confusing and not very specific
![image](https://user-images.githubusercontent.com/55637865/191855061-d5a6c159-0ed1-49ec-99d2-59b0d918b394.png)
these 2 missions have the exact same description

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Not the exact same, one mentions being a large swarm, the other just a swarm. I guess the regular swarm could say "medium-sized swarm" but that's also a bit funny

**Comment by JeroonBosch** [comment]
Not being too specific is intended (we want to keep an element of surprise on whether you're facing husked crawlers or a broodmother), but "Large swarm" giving less reward than "Swarm" is confusing, so renamed the older missions also to have "Large swarm" in their name.

**Comment by Rokvach** [comment]
No issues, closing.
