### ISSUE TITLE
Submarine transfer explosion

### ISSUE THREAD

**Issue by ThePinkPyjama** [Regalis11/Barotrauma#9918]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Playing on the Herja, stocked with all manner of explosives - Nuclear shells, compound N, chemicals, IC-4  - you name it. Transferred from the Herja to the Kastrull, the moment we left the outpost there was a huge explosion. I assume the cargo from the Herja spawned a foot or 2 above the ground, and the impact exploded all our nitroglycerin (along with everything else).

### Bug prevalence

Just once

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by gerakis** [comment]
Was it a new kastrull or a used one? Was water everywhere from previous damage?

I think the only things that blow up from shock are oxygenite shards and maybe nitroglycerin.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7f0feaef298e08cfdf82f067d12564dab55b39d9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
