### ISSUE TITLE
Make music louder

### ISSUE THREAD

**Issue by AbominationBanisher** [Regalis11/Barotrauma#992]
Regalis/Juan, I strongly suggest you all up-end the volume of the background music in game, I turned my settings all the way up and in game it is still barely audible. By strongly turning up the base volume, you'd be indeed setting more of a mood in this game, which as of now without it, makes the game just FEEL boring, we need the music to be louder in honour of atmosphere.

**Comment by AbominationBanisher** [comment]
In addition, change the current background music, it is not good at all.

**Comment by Regalis11** [comment]
I'm not sure if you're talking about the public or the dev version or which track you mean by "the background music", but I disagree about the issue. I'd say it's almost the opposite (especially with the new music in the dev branch) - on the default setting the music is maybe a bit too loud relative to the sound effects in my opinion.
