### ISSUE TITLE
[Unstable] Engineer tutorial dialog weirdness

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9921]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Heres a video of what happened, i have no idea if this is intended
https://cdn.discordapp.com/attachments/668819422919524352/1022892435589836890/Barotrauma_2022-09-23_12-28-31.mp4
After overloading the reactor, the tutorial completed and the dialogs just said "Close" -> "Close" -> "Follow", which seemed very weird.

### Reproduction steps

1. Overload the engineer tutorial reactor
2. Tutorial is completed?
3. Get some weird dialogs repeating the word "Close"

### Bug prevalence

Just once

### Version

0.19.6.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by JeroonBosch** [comment]
Could it be <CheckConditionalAction voltage="lt 1.2" targetitemcomponent="PowerTransfer" targettag="mainjunctionbox"> isn't sufficient to check the Fission  Rate being in the green?

**Comment by JeroonBosch** [comment]
Fixed the 'closed' popup and ensured that the reactor is not overheating to properly progress. Also closed the 'Follow' pop-up automatically when following now

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
