### ISSUE TITLE
Typhon 2 chaingun LOS completely blocked

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9923]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Typhon 2 chaingun stuck inside solid walls
![image](https://user-images.githubusercontent.com/73229309/192002776-6cc6cec0-d998-4075-8962-7e7df6ee0815.png)

![image](https://user-images.githubusercontent.com/73229309/192002584-e9e8241b-b44c-4078-80e2-4107b420a65f.png)
![image](https://user-images.githubusercontent.com/73229309/192002614-b650a785-f543-4e31-878c-998a8028786a.png)

### Version

0.19.6.0 (unstable)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/de8dc7e0ff170d2cb91df7de1839aeabe0bfc67e

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
