### ISSUE TITLE
Error in MultiplayerCampaign.ClientRead (Index was out of range)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#9926]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Error while trying to connect.

### Reproduction steps

1. Join a server

### Bug prevalence

Just once

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. {Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')}
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg)
   at Barotrauma.Networking.GameClient.ReadLobbyUpdate(IReadMessage inc)
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc)
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime)
   at Barotrauma.Networking.GameClient.Update(Single deltaTime)
```

**Comment by esirprus** [comment]
This is common when joining a server with very many mods and if you haven't enable the mods which server have enabled. but i cannot find how to produce it too.

**Comment by Ek-Videogames** [comment]
Can happen vanilla too.

**Comment by Regalis11** [comment]
Added a more descriptive error message that should make this easier to diagnose https://github.com/Regalis11/Barotrauma-development/commit/8dfe3de03f1034fd03987e7a03b5b82942a107b4, + prevented this from crashing the game
