### ISSUE TITLE
'Scrap' item isn't available in submarine editor

### ISSUE THREAD

**Issue by Azx1234** [Regalis11/Barotrauma#9927]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In the list of items in the submarine editor, the 'scrap' item isn't listed. It therefore cannot be put into containers.

![image](https://user-images.githubusercontent.com/113154959/192066860-e0e445e9-5c80-41d5-b87c-f74f2a5c1ca6.png)

The only way to get scrap into a container is to auto-fill it with a tag like 'abandonedstoragecab' (although it's not guaranteed to show up, and the amount will be very low).

### Reproduction steps

1. Open the submarine editor.
2. Type 'scrap' into the filter box.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/541d266071c788714a8c61e6b269956b77f1c6ca

**Comment by Rokvach** [comment]
No issues, closing.
