### ISSUE TITLE
[Unstable] Deep Diver loading screen hint still exists

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#9929]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The loading screen hint about buying a Deep Diver submarine still exists, even though Deep Divers no longer exist.

### Reproduction steps

Find the Deep Diver loading screen hint.

### Bug prevalence

Happens every now and then

### Version

0.19.6.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6e064eeba2214f8ebbb3efa43ff3c050e2e5108f

**Comment by Rokvach** [comment]
No issue, closing.
