### ISSUE TITLE
Ammo sometimes doesn't get removed properly

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9943]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Sometimes smg ammo (and coilgun bolts, though i haven't really checked/seen since 0.10 or so) doesn't remove itself from the world properly, and can be picked up.

Image of a stored single smg shot (multiplayer, crew put it into cabinet)

![image](https://user-images.githubusercontent.com/5103517/192164786-c3fd5732-3568-47ca-a895-ce77e4eab6ca.png)

### Bug prevalence

Happens every now and then

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by PokkeTigrex** [comment]
I've seen SMG rounds laying around here and there in many different servers and is rather annoying to dispose of. The problem is I don't know how to replicate it, as I've never seen them spawn from SMG usage and I just end up finding some on the floor randomly.

**Comment by Regalis11** [comment]
Most likely related to https://github.com/regalis11/barotrauma/issues/10264, and the fix implemented for that issue should fix this one as well.
