### ISSUE TITLE
Winterhalter batteries' total max input does not match the relay's max power value.

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#9944]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened:
Each battery on the Winterhalter is set to 500 Max Recharge Speed, and the input relay is only set to 1000 Max Power, artificially limiting the throughput to 1000 kW.

### What I expected to happen:
The input relay should have a high enough Max Power value to match the batteries' total Max Recharge Speed, even with the highest battery recharge speed upgrade level. (max. 1875 kW)

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a75c28235dec0441a1a5803fc88b7eb7ea59a568
