### ISSUE TITLE
password bans add the client to the ban list twice

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#9945]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a player is banned for getting the password wrong too many times, 

![image](https://user-images.githubusercontent.com/29177976/192297209-b545ec00-6006-4f2b-ad8b-61b671a530aa.png)

I noticed in the bannedplayers.xml one is the account ID and the other is the IP address, however when you ban via SteamP2P (In game hosting) and you can see the steam ID (As its hidden in dedicated), they are both a steam ID and not a steam and IP address listed, so something is still off there if its intended.

If we wanted to keep two endpoints to a ban, it would make sense if one ban could just contain both endpoints over separate bans if that is what's happening here.

### Reproduction steps

have a client be banned via wrong password. SteamP2P or dedicated.

### Bug prevalence

Happens regularly

### Version

Other

### -

0.19.6.0 + some changes on tutorial branch.

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
