### ISSUE TITLE
cant go through hatches and cant place items

### ISSUE THREAD

**Issue by MrMasos** [Regalis11/Barotrauma#9946]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

cant go through hatches of ships just gets stuck with my head or feet going through but get pushed back. i can only go through a hatch when another player is besides me going up or down the hatch alongside me. cant place items in lockers, will just fall on the floor. this occurred after a good while of playing campaign with another friend. suddenly after docking at an abandoned outpost the bug appeared. 

### Reproduction steps

play campaign
play more campaign
try to go through a hatch

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
No known steps to repro, closing
