### ISSUE TITLE
Unable to buy multiple different upgrades at a time from the same upgrade category

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9950]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I noticed that if you buy a upgrade from a category which contains multiple different upgrades, you are only able to buy one of them and then have to switch to a different category and then back to get access to buy the second upgrade. 

### Reproduction steps

Tested in multiplayer
1. Use upgrade service on outpost
2. Buy a upgrade from a category which has multiple upgrades available
3. Notice that the button can't be interacted with on the upgrade you didn't buy
4. Switch to a different category
5. Switch back
6. Notice that you can buy it now

### Bug prevalence

Happens every time I play

### Version

0.19.6.0 (unstable)

### -

Tested in dev branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/58cc307b565109880b001de3f541bdcc76a8a561

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
