### ISSUE TITLE
Lock won't actually lock your sub.

### ISSUE THREAD

**Issue by illersaver** [Regalis11/Barotrauma#9951]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Lock won't actually lock
Movement are way slower, but it still moves

That was recorded on a big submarine without water at all.
![wut](https://user-images.githubusercontent.com/55444968/192582884-fc7c08f1-e4af-406e-8efa-91f70b5dd402.gif)

### Reproduction steps

1. Start game
2. Enable cheats
3. lock command

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1c6921bf0b34078877ed636f9405f2b82572b8bb

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
