### ISSUE TITLE
Clients can get stuck to a non-functional lobby if starting a campaign round fails server-side

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9954]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If the server fails to start the campaign round and the client opts to return to the lobby due to starting the round "taking unusually long", they won't be able to end the campaign, switch to another mode, or basically do anything else but to restart the server. Happens because the client thinks the round is still running, which disables the game mode list, and makes the "quit campaign" button request ending the round (which the server ignores since the round isn't running).

### Reproduction steps

1. Checkout https://github.com/Regalis11/Barotrauma-development/commit/373b429eaed92741b3dd4dd58397917e06ad8647, start a campaign, select a mineral mission and start a new round. There is an issue in this version that causes an exception to be thrown in MineralMission.StartMissionSpecific, preventing the server from starting the round. Another way to induce this is to modify GameSession.InitializeLevel so it always throws an exception. Note that you need to do this in a Release build, as the exception crashes the server in debug builds.
2. The clients should show the "Starting the round seems to be taking unusually long" prompt after a while, and opting to return to the lobby causes the aforementioned issue.

### Bug prevalence

Happens every now and then

### Version

0.19.6.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/30a93983b4d5be77b14b8a5202468cf1fa7accaf

**Comment by NilanthAnimosus** [comment]
Tested against networking-fixes-sep28 commit https://github.com/Regalis11/Barotrauma-development/commit/54beb5ab1b1b620d05a43183867a4b7256c94cfe, no issues found, recommend merging.
