### ISSUE TITLE
Docking at a station with a running reactor sets the durability of all owned fuel rods to 100%

### ISSUE THREAD

**Issue by feru7** [Regalis11/Barotrauma#9956]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Docking at a station with a running reactor sets the durability of all fuel rods (even completely drained ones) in the crews posession to 100%, regardless if the rods are in the reactor, cabinets or inventory. Tested in single player with uranium and thorium fuel rods.

### Reproduction steps

1. Start a single player campaign.
2. Dock at a station with the reactor running.
3. Check the durability of the fuel rods.

### Bug prevalence

Happens every time I play

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by feru7** [comment]
It also seems to happen everytime I am docking after this bug has occured, regardless if the reactor is running while docking or not.

**Comment by TheMinerBoy** [comment]
Yep, this happens to me too.

**Comment by TheMinerBoy** [comment]
From reading the Discord, this issue apparently applies to all items (Ammo, batteries, welding fuel, etc.) as well as reactor fuel rods.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/00f795275d20e02a91cf05792d31934e9a358ffe

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore, working correctly. Closing.

**Comment by TheMinerBoy** [comment]
Wait
