### ISSUE TITLE
v0.18.15.1 creating new character in the middle of the round causes item loss on scene transition

### ISSUE THREAD

**Issue by Peliex** [Regalis11/Barotrauma#9957]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I created a new character in order to balance the team's jobs in the middle of a round, changing from a mechanic to a medical officer.  After retrieving my items from my corpse, and completing the round proper, the scene transition respawned me as a new medical officer with no rolled over xp from the previous round and without any of my items.

### Reproduction steps

1. Start a multiplayer campaign
2. Launch into a mission
3. Die, but make sure the round continues
4. Instead of checking respawn, spectate and create a new character from the menu
5. Check respawn
6. Respawn before the round ends, then transition to the next round
7. Character will respawn as a brand new crew member with fresh skills and loadout

### Bug prevalence

Happens every now and then

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

We've got a couple of fixes coming up for issues that seem potentially related to this (https://github.com/Regalis11/Barotrauma/issues/8255, https://github.com/Regalis11/Barotrauma/issues/9536 and https://github.com/Regalis11/Barotrauma/issues/7228): I think we need to give this a test in the latest version and see if it still occurs.

**Comment by Peliex** [comment]
Thanks for the rapid response! I haven't swapped to unstable to test this issue again on the newer version, but I will see if I can replicate it on the newest version using multiple clients and my dedicated server

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
