### ISSUE TITLE
[Unstable] Missions give you money/rep gains even if you fail them

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9961]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You always get the mission rewards regardless if the mission is completed successfully or not

### Reproduction steps

1. Start a round with some mission in campaign (sp or mp)
2. Dock back to the outpost
3. ???
4. PROFIT

### Bug prevalence

Happens every time I play

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4bb2385f2ffef6197a1cf47b620498d3c3959d18

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/7a78192a6ad64d711b9b1c43da62955ba78764ad, no issues found, closing.
