### ISSUE TITLE
(Unstable) Camel General Issues

### ISSUE THREAD

**Issue by SirNightKnight** [Regalis11/Barotrauma#9962]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

1. Bots struggle to pathfind on the Camel and get stuck on certain hatches and doors. 

Most notable areas include:
-Both hatches of the smaller ballasts
-Hatches to the cargo humps (Mostly when leaving)
-Door to crew quarters

2. Airlock pump doesn't work by default requiring the player to set the speed to pump out.

3. Ladders that are tightly spaced throughout the submarine cause issues with bot navigation (Limbs will get stuck on the shape of the submarine and will stop the bot).

### Reproduction steps

1. Play on the Camel with bots

### Bug prevalence

Happens every time I play

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

MacOS

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8aed8cf74b818b8e5f1d43390266297f6079f53d  and https://github.com/Regalis11/Barotrauma-development/commit/8945b4d742df36825e5ec8012ab42c5bd66e5953

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
