### ISSUE TITLE
dual wielding disables turning and attacking

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9965]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

when wielding a single melee weapon, moving the mouse to the other side of the character will make the character face towards the cursor when attacking.

when dual wielding melee weapons though, the character will not change their facing while attacking, until the attackings stop.

expected is for attacks to be towards where cursor is aiming (/flip direction once the attack has finished the "hitting" portion)

### Reproduction steps

1. wield single  melee weapon
2. aim and hold attack 
3. move cursor to other side of character
4. attacks will be towards cursor

1. wield two weapons
2. aim and hold attack
3. move cursor to other side of character
4. attacks will only be towards initial facing direction.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8653a1a157876d661553160ca53cd2231300edbc

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
