### ISSUE TITLE
reach of item placement exceeds reach of tools wrench/screwdriver

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#9966]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

player can place items (wiring components) further than they can reach.

I think this is ~1 grid snap  of error

expected is to be able to reach placed items.

### Reproduction steps

1. hold AND component
2. aim far (maximum distance)
3. place AND component
4. hold screwdriver/wrench/nothing
5. can't interact w/ AND component

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/13fcc8bccc61ee08c96b2543aa47b109bc1d7527

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/3f874d71a8cdc82d1d16314abdd6ae91f7e42098, no issues found, closing.
