### ISSUE TITLE
Hatch sprite depth out of alignment

### ISSUE THREAD

**Issue by KonigP86** [Regalis11/Barotrauma#9968]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The door portion of the "Custom hatch", "Hatch with Buttons" and their wrecked variants sprites is out of alignment. This results in the door's artwork sitting in front of the hatch in the majority of instances. See the attached screenshot.
![Hatches](https://user-images.githubusercontent.com/114788696/193379806-02230ea0-744d-4ebe-b485-95ab195e9226.jpg)

Players can manually correct this in the editor by setting the hatch's sprite depth to less than 0.1 however all of the vanilla subs currently have their hatches displaying incorrectly.

### Bug prevalence

Just once

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Is this still an issue? -> Adding "Needs testing" label.

**Comment by Regalis11** [comment]
@itchyOwl yes, nothing has been done about this.

**Comment by Regalis11** [comment]
We're cleaning up some low-prio/unreproducible/irrelevant/outdated tickets from the issue tracker, and this is one of the tickets we chose to axe.
