### ISSUE TITLE
[Leftover Bug] Good Quality Uranium fuel rods automatically refill themselves when you dock at a station

### ISSUE THREAD

**Issue by TheMinerBoy** [Regalis11/Barotrauma#9969]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I docked at a station with one empty good-quality uranium fuel rod in the Dugong's reactor locker and one partially empty one in the reactor itself. When I docked, both of them jumped to full condition. I'm assuming this also happens to other good-quality items with condition.

### Reproduction steps

1. Undock from a station with a good-quality uranium fuel rod in your submarine's reactor
2. Wait until it is drained a bit (Doesn't matter how much it is drained)
3. Redock or dock at a completely different station
4. Free uranium!!!

### Bug prevalence

Happens every time I play

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a2d1e3c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
