### ISSUE TITLE
Alien Generator sprite issues

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9971]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Alien generators aren't use any more, but:

1. Decorativesprite sourcerect and offset are incorrect
![image](https://user-images.githubusercontent.com/73229309/193427534-b510c9af-f76d-4f88-8618-c6c41240cdd2.png)

Properly aligned `sourcerect="0,486,176,176"`, for some reason I'm getting waaaay different offset results for `Itemcontainer itempos="6,-30"` on the mod I've been working with.
![image](https://user-images.githubusercontent.com/73229309/193427525-189b2a86-49db-4887-9a41-386ec5a3b36d.png)

2. Removing the power cell does not make the decorative sprite go away. 
I couldn't find a way to remove the sprite via XML, it seems to be using a "charge" property on containing the alien cell. You can make the sprite appear but not disappear.

3. Power cell will always be below decorative sprite (it inherits main sprite depth)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7ec6f0f3e3cee31cede8dd7cf0bd2b6fee8ffecf

**Comment by Rokvach** [comment]
The decorative sprite isn't displayed at all now, tested in release branch
![image](https://user-images.githubusercontent.com/7299826/195542692-e789e705-a4d2-4f76-81dc-306b9a1ebb00.png)

**Comment by Rokvach** [comment]
Nvm the decorative sprite was changed into light so the appearance is slightly different now. Working correctly, closing.
