### ISSUE TITLE
Typhon 2 oxygen runs out on Gunnery Compartment if all the periscopes are in use

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9972]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Having a bot on each periscope causes oxygen to run out from the room

![image](https://user-images.githubusercontent.com/7299826/193444475-f75aa4d2-1706-484b-8d0b-0c9e086f5092.png)

### Bug prevalence

Happens every time I play

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
Looks to be fine if the armory door is open, which bots tends to leave open when they go pickup more ammo or to run off from the gunnery room. Welding the armory door shut makes it sure that the gunnery compartment runs out of oxygen

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/06aed46fff2050a0dacb44ecef50ab76dd3a5448

**Comment by Rokvach** [comment]
Tested, no issues. closing.
