### ISSUE TITLE
Kastrull Drone hull gaps improper placement

### ISSUE THREAD

**Issue by Steamlined** [Regalis11/Barotrauma#9974]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The Kastrull Drone has multiple issues regarding flooding. Firstly, the hull gaps' lower boundaries are placed too high, such that, if the drone has flooded at any point during a game, then water will pool around the left and right sides, where they cannot be pumped out with the drone's own pump. Additionally, the water detector is placed too high, such that water remaining in the bottom of main hull does not fully drain either (this one at least can be fixed ingame). If the drone has flooded with both of these issues, the remaining water level is enough to almost entirely prevent the drone from ascending at all.

![image](https://user-images.githubusercontent.com/30579031/193468325-78e85348-c6e7-4164-bd81-171d96ca2719.png)
I've attached a debugai view of a post-flooding drone (I wasn't sure if a better view was available). In this picture, there is still water in the drone, but the water detector in the middle is not detecting it, and thus, the pump not running. It seems like the pump does sometimes stay on long enough to allow more water to drain, likely due to the detector not updating instantly.

![image](https://user-images.githubusercontent.com/30579031/193468657-01e50fd5-b616-4667-b9fd-0af62a250796.png)
I've also included a sub editor view, showing that the gaps do not extend down far enough to allow water to flow into the central hull. So, even if the main pump did pump out the water correctly, then the sides would still have water pooled within.

### Reproduction steps

1. Load Kastrull in a game
2. Flood the main compartment of the drone.
3. Allow water to drain with the drone's own pump.
4. Check water levels of drone hulls.
5. To verify water detector is causing issue, disconnect the small pump's 'set_targetlevel' and manually activate the pump.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4bfd31f7da8e732e7434dff4f3a311f3e6e5b54f

**Comment by Rokvach** [comment]
Tested, no issues. closing.
