### ISSUE TITLE
a minor bug

### ISSUE THREAD

**Issue by Randomhunter30** [Regalis11/Barotrauma#9975]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

there is no problem and every thing is fine but my game is spitting out a error every time i start it. Please help me get rid of it

### Reproduction steps

1.Start of the game

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to load "" at C:/Users/jespe/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2481067504/filelist.xml: Name is null or empty:    at Barotrauma.ContentPackage.AssertCondition(Boolean condition, String errorMsg) in G:\Repositories\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 185
   at Barotrauma.ContentPackage..ctor(XDocument doc, String path) in G:\Repositories\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 69
   at Barotrauma.RegularPackage..ctor(XDocument doc, String path) in G:\Repositories\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\RegularPackage.cs:line 10
   at Barotrauma.ContentPackage.TryLoad(String path) in G:\Repositories\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 130
```

**Comment by Regalis11** [comment]
It seems one of the mods you've installed is faulty, and causes this error when the game tries to load it. The mod is located in "C:/Users/jespe/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2481067504/" - you might want to delete that folder, and maybe to try to figure out which mod it is and unsubscribe from it on the Steam Workshop. Sorry for the inconvenience!

**Comment by Randomhunter30** [comment]
it is not a mod that I have downloaded it is a submarine that i created so i don´t want to delete it because I play with it with my friends. It was created 15 May, 2020 so I might have some old parts in it. Thanks for the quick answer
