### ISSUE TITLE
The metal crate that spawns the crawler baby deconstructs into a steel bar as opposed to normal crates that give you nothing

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#9979]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The random event that lets you interact with a metal crate and spawns a pet or a crawler has a weird deconstruction recipe.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/97776f1c1ef16712ec39ded0f00f59ebeec7c9a6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
