### ISSUE TITLE
Minerals touching ice deletes the minerals

### ISSUE THREAD

**Issue by chagaming** [Regalis11/Barotrauma#9983]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Minerals that touch the ice when it is broken will be deleted but still appear on mineral scanners.

### Reproduction steps

1. Find minerals touching ice
2. break the ice

### Bug prevalence

Happens every now and then

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e24d537024393e2e7b816080bb17d1b0e46ef13d

**Comment by Regalis11** [comment]
Note for testing: you can force minerals to spawn at a destructible level wall like this:
![image](https://user-images.githubusercontent.com/14351070/196651546-d3c5b01a-9b47-4694-b766-b94097b656ce.png)

```
location.Cell = ExtraWalls.Where(w => w.Cells.Any(c => c.IsDestructible)).GetRandomUnsynced().Cells.First();
location.Edge = location.Cell.Edges.GetRandomUnsynced();

item.Move(edgeNormal * moveAmount + location.Cell.Translation, ignoreContacts: true);
```

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
