### ISSUE TITLE
Large turret hardpoint misaligned

### ISSUE THREAD

**Issue by Facehurt1** [Regalis11/Barotrauma#9986]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hi there the Large Turret Hardpoint is currently Misaligned

Please refer to this album https://imgur.com/a/4ZuHbjO

### Reproduction steps

1. Start any campaign in singleplayer
2. Upgrade the large hardpoint to the railgun or any large weapon
3. Launch a mission
4. Enter debugmode by putting debugdraw in console after enabling cheats

### Bug prevalence

Happens every time I play

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa5f881c65a10cba57ec31692ed9a6c027950eb2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Facehurt1** [comment]
poggers thanks!
