### ISSUE TITLE
Storage container fell through terrain

### ISSUE THREAD

**Issue by AceCranel7** [Regalis11/Barotrauma#9988]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When I was doing a mining mission I would drop the case at some terrain but in this case it just fell through the walls, should all carriable containers do that?

### Reproduction steps

1. Launched with only Black armoury mod
2. 30 or 40 mins into the game I got the mining mission
3. got out of the airlock with the case
4. Going to drop the case at a terrain but it fell through

### Bug prevalence

Just once

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
N/a
```

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately wasn't able to reproduce the issue: the storage container doesn't seem to go through the terrain. I think this requires some more specific situation to occur: perhaps some specific kind of terrain? Did this happen in multiplayer or singleplayer?

https://user-images.githubusercontent.com/14351070/194141568-ea7d36b6-700f-46b0-ba7a-2b46ddacd89b.mp4

**Comment by Ek-Videogames** [comment]
Feels like it's a 'tunneling' issue with physics?

I've observed this effect as well - particularly with alien artifacts if placed on the ground for any reason have a chance of clipping through terrain on the server's end & blink out of existence.

**Comment by AceCranel7** [comment]
Hey, uhh yeah but I was able to experience the issue again on single player
(same thing happened) the storage briefcase / artifact case fell/ no
clipped through the terrain at europan biome I believe

**Comment by AceCranel7** [comment]
Sorry bout the late email, different time zones for work

**Comment by AceCranel7** [comment]
Oh I forgot to mention after the update it kinda brings the game
performance around 30-40% (rough guess) and it's mostly lag, tried every
fixes, mod performance fixers none to no avail. Hope there is some
performance settings during single player, while/ during attack/ pirate
sub/ abyss creature/ giant creature mission/s.

**Comment by AceCranel7** [comment]
And again thanks for hearing me out! y'all are my fave devs for creating
this game!

**Comment by Regalis11** [comment]
No known steps to repro, closing
