### ISSUE TITLE
Update all mods button non-functional

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#9989]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Attempting to update all mods causes the modlist to flicker and nothing happens.

### Reproduction steps

1. Have mods that need updates.
2. Press update all mods button.
3. Mod list flashes and nothing happens.

### Bug prevalence

Just once

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mrcalzon02** [comment]
Same
used left-hand menu to select individual mods then updated from the detail/info page.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54c219b4a4c91c8f877188c0b1634479af3f3c59
