### ISSUE TITLE
Broken map

### ISSUE THREAD

**Issue by Cyborgcr** [Regalis11/Barotrauma#999]
Me and my team successfully got the artifact and were going to the outpost only to find that the map is bugged and the outpost was in the ice wall instead of where it's supposed to be. I don't have any screenshots or seeds because I'm a slowpoke sorry, but I got a drawing of the bug!
![outpostbug](https://user-images.githubusercontent.com/46865336/51439676-4ea43f00-1cc6-11e9-8e70-96376ce4cd57.png)

**Comment by Regalis11** [comment]
Should be fixed in the dev version.
