### ISSUE TITLE
Direct Join doesn't seem to work with domains anymore.

### ISSUE THREAD

**Issue by Maselkov** [Regalis11/Barotrauma#9999]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In previous versions, I was able to connect to my server using a custom domain name, which is very useful in case of the server having a non-static IP address, and DDNS set up. On this patch, it seems that if the "Server IP / SteamID" text box contains anything besides numbers and dots, or an ipv6 address, or a steam id, pressing "join" doesn't do anything. 
I suppose this could be intentional, given the text box's name, but it worked in the past. 

### Reproduction steps

1. Enter Server Browser from the main menu.
2. Press the direct join button
3. Type in the domain
4. Press join
5. Nothing seems to happen if the text-box contains anything other than numbers and dots or an ipv6 address, or a steam id. Try `example.com`, for instance.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8ce5137f091341c3c36cf9bf6a20ac508b352c34

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/56ddb502c58d91fea177e4f4c9b9c57bb12e7c8c

You may now type in domain url's into direct connect. but it appears no connection is actually attempted or shows any failiure if the website doesn't exist.

IE. www.niltestsite.com did not exist as a domain/website to retrieve an IP from. so the game simply doesn't attempt a connection or display it was not found/incorrect.

any website that does exist or is redirected to via a modified hosts file does attempt a connection as it should.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/61446b3195c770572a6acdee8ac89e6b1cc15b2b
